### ISSUE TITLE
Cannot import users from oficial example .CSV

### ISSUE THREAD

**Issue by francogp** [snipe/snipe-it#10001]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Following the tutorial, and using the example CSV file, it fail to import users.

**To Reproduce**

1. I just start a new clean snipe-it instance
2. set it to spanish-mexican
3. download your CSV example for users in the tutorial web
4. try to import it

**Expected behavior**
To import the users

**Server (please complete the following information):**
 - Snipe-IT  Version v5.1.8 - build 6257 (master)
 - OS: Ubuntu
 - Web Server: Apache 
 - PHP Version 7.4

**Error Messages**
![image](https://user-images.githubusercontent.com/2739706/131141587-103e4b53-34f1-4009-b420-0517fce0be34.png)

**Additional context**
- Fresh install
- Git installation method

**Comment by snipe** [comment]
You already have an issue for this open. Why would you create another one?

**Comment by francogp** [comment]
> You already have an issue for this open. Why would you create another one?

Where? I did not report this issue. (I comment this on a different report, but was misplaced, and even closed for other reasons)

**Comment by francogp** [comment]
I checked issues "like" this up to 2019, and there is none
