### ISSUE TITLE
Feature: Warranty Lookup from Serial Number

### ISSUE THREAD

**Issue by dastrixuk** [snipe/snipe-it#1003]

**Comment by snipe** [comment]
What is it you want to look up?

**Comment by dastrixuk** [comment]
It would be a sweet feature if for example my our hp warranty status was looked up and a date of expiry listed.

**Comment by snipe** [comment]
How would you be looking up the hp warranty status though. I don't understand what you'd actually be searching on.

**Comment by dastrixuk** [comment]
Yeah it looks up warranty with certain manufacturers, spiceworks has the feature if it helps 

Regards 

Chris

**Comment by kobie-chasehansen** [comment]
We are a dell shop but it does seem like you can look up warranty by just modifying this URL string

http://www.dell.com/support/home/us/en/19/product-support/servicetag/SERVICETAGHERE/warranty

example
http://www.dell.com/support/home/us/en/19/product-support/servicetag/9DZPK12/warranty


my thoughts are that no matter what vendor you try to do this with it will be a pain to maintain.
