### ISSUE TITLE
Feature: Better Locations to enable bigger organisations to add buildings / floors etc

### ISSUE THREAD

**Issue by dastrixuk** [snipe/snipe-it#1004]

**Comment by snipe** [comment]
What exactly does this even mean? How are you defining "better"?

**Comment by dastrixuk** [comment]
When I say better I guess I mean locations onsite not address, 

For example we have 10 blocks and would like to say where a device is going In the building.

Regards 

Chris

**Comment by snipe** [comment]
Can you no do that through the location name?

**Comment by dastrixuk** [comment]
Yeah have done it that way, wasn't sure that was th best way though.

**Comment by snipe** [comment]
Yes, that's probably the best way to handle that.
