### ISSUE TITLE
Preview image in uploaded files for asset

### ISSUE THREAD

**Issue by vabue** [snipe/snipe-it#1007]
We often put the real photo of asset as attachment file.
It would be useful and easy to show a preview of png/jpg images in the asseet page.

Something like this - https://www.evernote.com/l/AAI-P-Xu2YFIlbgHm-AHLvO5ck_6Z8H-lBE

**Comment by snipe** [comment]
Do each of your assets look differently? Otherwise you can just upload the image at the asset model level and it will show up in the asset view.

**Comment by vabue** [comment]
They often look differently. One can be scratched and used and another
barely touched.

понедельник, 3 августа 2015 г. пользователь snipe написал:

> Do each of your assets look differently? Otherwise you can just upload the
> image at the asset model level and it will show up in the asset view.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snipe/snipe-it/issues/1007#issuecomment-127376832>.
>


-- 
_____________________________
Валентин Будкин
email/jabber: val.budkin@gmail.com
skype: val.budkin
twitter: @valbudkin
site:http://adminote.blogspot.com

**Comment by snipe** [comment]
Got it
