### ISSUE TITLE
Best Practice for Adding Seats to a License

### ISSUE THREAD

**Issue by dscherertfm** [snipe/snipe-it#1008]
I'm wondering how others have handled this in Snipe. I just added a seat to our Snagit license, however If I change the purchase cost or order number I'm not sure how to track the original purchase. We have a volume license agreement with TechSmith for this product so the license key itself does not change.

Could this be solved with a feature to perhaps extend a license? For example, when you add a seat, extend maintenance, etc maybe have the option to create a line item in the history or something to reflect the cost to extend the seats/support, any order/PO number associated with it and any other details that are important?

Keeping track of this could be useful to show TCO over time.
##

**Comment by kobie-chasehansen** [comment]
Yeah I'm running into a similar problem but with Windows Licenses.

Here is how mine is starting to look. Not sure how to improve on this...

![image](https://cloud.githubusercontent.com/assets/10247644/9087823/032e65d2-3b5b-11e5-8c66-8fb01440a6fe.png)

**Comment by dscherertfm** [comment]
Finding the key block with the open seat has to be rough in that setup, not to mention over time I imagine that will only get more and more difficult to maintain.

**Comment by kobie-chasehansen** [comment]
yeah... think i remember hearing @snipe mention that the licensing mgmt is going to get overhauled at some point to better handle situations like theses.

**Comment by snipe** [comment]
Definitely. We know it's a clunky UX. It's a priority for the next few releases after 2.0

**Comment by seanism** [comment]
I have the same issue.  Some of our vendors don't have a VLK so I'll buy a few here a few there and it turns into a huge list of the same application with a few seats in each.  Perhaps group applications together with the same name and clicking that application goes into a list view of all the licenses / agreements for that application?

**Comment by tolleiv** [comment]
+1 would be great to have application groups.
We're also using once License per purchase/ Open License which creates a lot of entries.

**Comment by Oreios** [comment]
I was wondering if something like this is being plannend. I also having this issue.

**Comment by dimon00** [comment]
License grouping would be a great help for us too.
