### ISSUE TITLE
Please make notes and mac fields searchable

### ISSUE THREAD

**Issue by goetzk** [snipe/snipe-it#1009]
Hi,
We're in a similar position to some people in #853 where we use the notes field for anything that doesn't fit in another place (such as desk location, extended service tag and some other bits and pieces). Having notes searchable would make that information far more useful and prevent needing to add more fields to snipe to handle those items.
Similarly, once we have the mac addresses in snipe it would be handy to search for them (a note on this part - we have multiple mac addresses in the mac field so for us a search would need to be a less efficient open ended search instead of a plain string match).

**Comment by snipe** [comment]
Notes field is already searchable in the next release

**Comment by goetzk** [comment]
Now that is service! thanks @snipe .
