### ISSUE TITLE
Incorrect message when uploading large images

### ISSUE THREAD

**Issue by goetzk** [snipe/snipe-it#1010]
I've just tried to attach some large images (over 2mb) and received the message on a green background: "Success: You did not select any files for upload". I feel this should be 'file to large' or similar. There was no error in the snipe logs so i assume its a combination of php refusing the file and an incorrect assumption in snipe about the resultant message.

**Comment by snipe** [comment]
What were you trying to add a large image to?

**Comment by goetzk** [comment]
Hi snipe, in my case it was attaching an image to an asset
