### ISSUE TITLE
Issue when viewing unassigned assets

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#1014]
![image](https://cloud.githubusercontent.com/assets/10247644/9069537/d7b34e70-3ab7-11e5-9da5-ce107441d849.png)

**Comment by snipe** [comment]
Version/branch?

**Comment by kobie-chasehansen** [comment]
latest 2.0

**Comment by snipe** [comment]
Where are you actually seeing this? When you click on "Ready to Deploy" in the sidenav, or...?

**Comment by kobie-chasehansen** [comment]
AH sorry, when clicking the unassigned assets report

**Comment by snipe** [comment]
Do you mean the unaccepted asset report?
