### ISSUE TITLE
UI Question with Consumables

### ISSUE THREAD

**Issue by hansenc0705** [snipe/snipe-it#1015]
Should the consumables section have a total and remaining column or just remaining?

![image](https://cloud.githubusercontent.com/assets/10247644/9069755/209060d2-3ab9-11e5-9157-814d1a6a24bf.png)
##

**Comment by madd15** [comment]
I feel it should have total and remaining

**Comment by kobie-chasehansen** [comment]
Since it's the consumables section won't the numbers always be the same? Won't be checking an item back in.

**Comment by madd15** [comment]
well, in terms of toner for example the total number would go up every time we got new ones in and the remaining obv. would go down when one gets checked out. It is useful to see how many toners we've had to how many remain.

**Comment by lcalway** [comment]
It would be helpful on the edit consumable page to have a add stock function. This would allow you to simply add the new stock count you have to the total which automatically adds the current and new stock for a new total. This would save calculation issues and overwriting the current total before saving. Sounds trivial, but it's just further fool proofing.

**Comment by zdienos** [comment]
agree with @Icalway, because we cannot tracking how much the stock added, and when. this is because when we add new stock, we just edit the existing consumable stocks

**Comment by TheGreatGene** [comment]
I've also had this problem, currently my solution is to update (increase) the "Quantity\QTY" each time I get new consumables\accessories. I think the solution for this would be to add an input field called restock or replenish to the end of each accessory/consumable items row. Updating this filed and then clicking restock would update the quantity fields.
