### ISSUE TITLE
Feature Request - Monitor Asset Inventory

### ISSUE THREAD

**Issue by hansenc0705** [snipe/snipe-it#1016]
Idea would be to mark certain asset categories/models as monitored and send an email alert when the count drops below a defined threshold.

Example, always wanting to keep at least 10 E7450 Laptops on hand.

Another one would be to assign it to an entire consumable category so we have an minimal number of toner always on hand.
##

**Comment by lcalway** [comment]
Would love this feature too! Glad its being worked on.

**Comment by markiparki** [comment]
yes we had the same idea! would be great
