### ISSUE TITLE
LDAP password / settings issues

### ISSUE THREAD

**Issue by vaneess** [snipe/snipe-it#10189]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

We upgraded to the latest version and changed the installation to git (Windows Server)

- LDAP sync works, but does not sync new passwords (it does create new users, but they cannot login)
- Cannot save LDAP settings --> Error 500
- When testing LDAP connection -->  " LDAP is not enabled, cannot test."

Screenshot 2 is with debug mode on and trying to save LDAP settings

### Reproduction steps

1. Change Password in AD
2. Run LDAP sync
3. try to Login
4. go to LDAP Settings
5. Test LDAP connection
6. Hit Save
...

### Expected behavior

- Passwords must be synced
- LDAP test must work
- LDAP settings can be saved

### Screenshots

![image](https://user-images.githubusercontent.com/1030364/136905186-9eb4d52a-c6d4-4b35-8fee-69d15e3f70e6.png)
![image](https://user-images.githubusercontent.com/1030364/136906154-363ed65c-a3ff-4bc1-a087-4718aac39c23.png)

### Snipe-IT Version

v5.2.0 build 6339 (g14a8baeca)

### Operating System

Windows Server 2019

### Web Server

IIS

### PHP Version

7.4.1

### Operating System

Windows 10

### Browser

Edge Chromium

### Version

94.0.992.38

### Error messages

```shell
[08:46:00] LOG.error: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ldap_phone_field' in 'field list' in D:\inetpub\snipeit\snipe-it\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:79

[08:46:00] LOG.error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ldap_phone_field' in 'field list' (SQL: update `settings` set `ldap_phone_field` = ?, `ldap_jobtitle` = ?, `ldap_country` = ?, `ldap_dept` = ?, `ldap_client_tls_cert` = ?, `ldap_client_tls_key` = ?, `settings`.`updated_at` = 2021-10-12 08:46:00 where `id` = 1) {"userId":721,"exception":{"errorInfo":["42S22",1054,"Unknown column 'ldap_phone_field' in 'field list'"]}}
```

**Comment by snipe** [comment]
Did you run migrations? What was the output?

**Comment by vaneess** [comment]
hi snipe
thanks for the fast response! yes we did run the migration, it was all successful. i just compared the old ldap settings with the new one. there are two new fields. the first one seams like there is something missing in the title
![image](https://user-images.githubusercontent.com/1030364/136907674-3d694950-325b-484d-9a48-f2fda28db161.png)

**Comment by vaneess** [comment]
shame over me...! seams like we did run the composer to install it (after migrating to git), but we forgot the migration command... 
now it all works fine. sorry for the inconveniences!
the field is still titled with "admin/settings/general.ldap_client_tls_key" but that doesn't bother us :-)
