### ISSUE TITLE
Create Location -> Undefined variable: location_options

### ISSUE THREAD

**Issue by balticer** [snipe/snipe-it#1019]
Hello,

i just installed snipe-it v2.0-beta and tried to create a new location. In browser a error 500 appears. Log says:

[2015-08-05 12:32:19] production.ERROR: exception 'ErrorException' with message 'Undefined variable: location_options' in /data/sitam/sitam/app/models/Location.php:88
Stack trace: ...

.

regards
Kai

**Comment by madd15** [comment]
> The 2.0 series isn't stable, that's why it's a pre-release.

Assuming you installed `v2.0-pre-beta` release, could you pull the latest from the `2.0` branch and see if your issue still exists as i have been unable to reproduce this error.

**Comment by balticer** [comment]
Works with latest pull from the 2.0 branch. Thank you!
