### ISSUE TITLE
Docker: Source Edits

### ISSUE THREAD

**Issue by RPSource** [snipe/snipe-it#1020]
Hi there,

After some toying and fooling around with the Installation for Docker I finally had it running a couple of times.

After initial tests I decided to build and run this on my Synology NAS (Synology added docker support since DSM 5.2)

It's running quite nicely but I can't seem to find a way to edit the Source files.
My Dashboard link always links to 'http://production.yourserver.com' and I would like to edit the language of the installation. 
Maybe I'm doing something wrong but I can't seem to find a way to get to the source files cause as far as docker is concerned there is no volume mapped.

**Comment by uberbrady** [comment]
The docker volume is all self-contained - the various files are inside the resulting image.

You can use ```docker exec -t -i your_container_hash /bin/bash``` and edit the various config files, but that's probably not the right way to do it. Having that domain name set as a default sounds like a bug to me.

If you're doing development, you can map a local check-out of the various files using -v, but this should be usable for production without doing that.

**Comment by uberbrady** [comment]
I need to figure out how to fix that, whether it be by documentation or some other way. Maybe as some kind of command-line option that gets read into by the various provisioning scripts? I'll figure something out.

**Comment by RPSource** [comment]
That did the trick but I agree in the long term and for newcomers this might not be the best way.
Thanks for giving an alternative though it worked nicely!

**Comment by uberbrady** [comment]
Yeah, I wanted to give you a workaround, but I definitely want to fix it for everyone else too. I'll leave this ticket open to remind me. Thanks for the heads up!

**Comment by phoemke** [comment]
I think this might be something that installer.sh is missing; I am seeing the same issue (https://production.yourserver.com/ always in dashboard, top link) in my fresh install (2.0.4). But not using Docker, just straight Ubuntu Server from install.sh. All else seems to work, at a glance. Will do some checking shortly to see if I can narrow things down. Thanks!

**Comment by phoemke** [comment]
Update: Looks like the workaround is to edit /var/www/snipe-it-master/app/config/production/app.php with the fqdn and domain, restart Apache. (True?) Looking at the install.sh etc.

**Comment by snipe** [comment]
You shouldn't need to restart apache for a change to any of the Snipe-IT app config files.

**Comment by swoopdk** [comment]
I would reccomend using an env file when doing the docker run command. Works just fine here with an env file and also including the SERVER_URL as a -e when doing docker run. 

However might be nice to include an sample env file for future release to make docker deployment even easier for people. 

Example:
```
#This env file is for snipeit and should be included with the following flag
# --env-file ./snipeit.list
#######

SERVER_URL=http://snipeit.example.com:32454/
LDAP_URL=ldaps://ldap.example.com
LDAP_USERNAME=cn=root,dc=example,dc=com
LDAP_PASSWORD=supersecretldappassword
LDAP_BASEDN=ou=people,dc=example,dc=com
LDAP_RESULT_USERNAME=uid
LDAP_RESULT_LAST_NAME=sn
LDAP_RESULT_FIRST_NAME=givenName
```

**Comment by dschnizzy** [comment]
Any chance of getting a step-bystep for setting  up Snipe-IT on a synology using Docker? I am new to Docker and learning how to use it. Would love to get Snipe-IT running using Docker on our Synology.

**Comment by snipe** [comment]
FYI, LDAP settings were just moved into the Settings page

**Comment by swoopdk** [comment]
dschnizzy i will of course be happy to post a guide, but there really isn't anything specific to Docker on Synology as opposed to Docker on any other machine. 

Especially if you just use the docker from dockerhub. So no real information i can give you at this moment. The guide on snipe-it should be plenty to get you started with both.

**Comment by dschnizzy** [comment]
That would be cool, I am new to Docker, I haven't been utilizing it as a tool on our Synology, except with Redmine, but the Syno package did everything for me. I messed with it yesterday and I was able to get the MySQL Container setup, but Syno utilizes MariaDB, which I would like to stick with if I could. I would like to use the Docker GUI if it will do everything needed for setup.
    *Do I need to use MySQL as a container, or can I use MariaDD? If so how do I point to it? Does it mess anything up to have a MySQL docker container and MariDB. I noticed they both use same port 3306. I have created a Snipe DB and user in Maria already if it can be used.
    *I do not fully understand the "Launch with Docker Run" vs. "Launch with Wizard" settings and how to plug them using the settings I found in the "README.md".
    *Not sure where to exactly store my "--env-file" that I created.
    *What is "Boot2Docker IP"?, my syno IP, sounds obvious but not sure.
Thanks in advance to the community for any help.

**Comment by snipe** [comment]
Is this issue resolved?

**Comment by dschnizzy** [comment]
Yes and No. 
Give me till 12/4/2015 to mess with Docker a bit. With the holidays here, I wasn't doing work. I managed to download the image from the registry, but haven't gotten the "Launch with Wizard" or "Launch with run" figured out. This is part of the Synyo, Docker GUI. Hence a guide would be cool. I prob wont even get to mess with it till 12/3.
As a side I installed a VM on the server, with LAMP, I am more familiar with that, but am just starting the Snipe-IT install on the VM, before I left on holiday, I installed and configured LAMP. My stubbornness would like to get it running using Docker if I can, learning experience.

**Comment by swoopdk** [comment]
I will try to get a writeup on how to use it with docker, but with changes on the horizon i haven't done too much as i'm been swamped with work. I'm hoping to get around to it later, but honestly it's not really a issue we need open i think. 
Especially not if you grab the image from docker hub. The issue is rather a Synology one as running and stopping ect from synology is kind of messy setup. I reverted to simply SSH'ing into my synology and running it quite regularly through command line.

I didn't bother with the GUI as i found it would crash the containers quite often and in general not be that useful :(

**Comment by dschnizzy** [comment]
I just resorted to a new Ubuntu VM, much easier, as I'm a little more familiar with that.  I do have an issue where it defaults to the Apache page, so I am working on that. From what I can see the ./install.sh pretty much takes care of eevrything, other than mail, otherwise am I missing anything

**Comment by dschnizzy** [comment]
I just resorted to a new Ubuntu VM, much easier, as I'm a little more familiar with that. Ill try and learn Docker over time and look at it later. Falling behind. From what I can see the ./install.sh pretty much takes care of everything, other than mail, otherwise am I missing anything?

**Comment by swoopdk** [comment]
Guessing this can be closed then ? 

The docker guide from the docker_enhancements should be perfect for most people, and i will certainly when i get everything running like i want in production make one that uses synology for the docker host.

**Comment by dschnizzy** [comment]
Cool, thanks for everyone's help
