### ISSUE TITLE
bug - when viewing deleted users its missing the deleted user warning

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#1022]
Steps to reproduce

click on users, deleted users button, select a user

![image](https://cloud.githubusercontent.com/assets/10247644/9087504/17f2a0b6-3b59-11e5-8a43-3df6d2b9c48d.png)

**Comment by snipe** [comment]
That's weird and confusing. I see it in the language file. 

```
'user_deleted_warning'      => 'This user has been deleted. You will have to restore this user to edit them or assign them new assets.',
```

**Comment by kobie-chasehansen** [comment]
Odd, confirmed my messages.php file is up-to-date.

![image](https://cloud.githubusercontent.com/assets/10247644/9097553/51ea3e6c-3b92-11e5-9288-dfa12b249a98.png)

**Comment by madd15** [comment]
`message` not `messages`
