### ISSUE TITLE
Duplicate Button missing

### ISSUE THREAD

**Issue by GustelDE** [snipe/snipe-it#10222]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Hi,

the blue "duplicate" button under Assets -> All Assets is missing.
Now I have to open a Asset and click unser Actions -> Duplicate Asset.

Could you please bring the button back? It was so handy... :)

Regards

Snipe-IT: V5.3.0 - Docker (Linux) Version
Browser: Firefox and Chrome (most current versions)

### Expected behavior

See the blue button.

### Screenshots

![Screenshot 2021-10-25 124808](https://user-images.githubusercontent.com/26502186/138682708-ef937509-1d62-49c9-b2ce-14dbfe436880.jpg)

### Snipe-IT Version

5.3.0

### Operating System

Docker (Linux)

### Web Server

Docker (Linux)

### PHP Version

Docker (Linux)

### Operating System

Win10 21H1

### Browser

Firefox and Chrome

**Comment by tamfadmin** [comment]
Hi,
FYIY--We have noticed the same thing since upgrading to v5.3.  The button was called Clone.  Our OS is Windows Server 2019 Standard.
We would like the button back as well.
Thanks,
Cameshia

**Comment by snipe** [comment]
Thanks for the heads up - I have a fix out in #10223 that should be merged soon once approved.

**Comment by tamfadmin** [comment]
Thanks so much!!!!

Cameshia

**Comment by snipe** [comment]
This merged into master now - sorry for the hiccup!

**Comment by tamfadmin** [comment]
No worries.

Thanks a million!

Have a great day!

Cameshia

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
