### ISSUE TITLE
Lack of Components sample CSV file

### ISSUE THREAD

**Issue by wkulesza** [snipe/snipe-it#10236]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I find the snipeit tool perfect for our needs to manage inventory of digital signage screens - so assets consisting of components. 
Just a small issue - when using Import, it says it supports importing assets, accessories, licenses, components, consumables, and users but in the provided link there's no sample file for components:
[https://snipe-it.readme.io/docs/importing](url)

Could you please provide an example, so that we could start importing our csv files to get going ?

### Reproduction steps

1. Login to demo
2. Select Import
3. Click on the link where it says The CSV should be comma-delimited and formatted with headers that match the ones in the sample CSVs in the documentation. [https://snipe-it.readme.io/docs/importing](url)
4. Scroll to CSV Format segment of that page. 
...

### Expected behavior

Those sample files are visible
    Sample asset import CSV
    Sample accessories import CSV
    Sample consumables import CSV
    Sample users import CSV
    Sample licenses import CSV

And it should be:
    Sample asset import CSV
    Sample accessories import CSV
    Sample components import CSV
    Sample consumables import CSV
    Sample users import CSV
    Sample licenses import CSV

### Snipe-IT Version

newest

### Operating System

linux

### Web Server

Apache

### PHP Version

newest

### Operating System

Ubuntu

**Comment by viclou** [comment]
@wkulesza I've attached a sample components import .csv file here. We'll get it added in our docs, too
[snipe-sample-components.csv](https://github.com/snipe/snipe-it/files/8317864/snipe-sample-components.csv)
.
