### ISSUE TITLE
Register The Auto Loader when selecting admin section

### ISSUE THREAD

**Issue by JoelB89** [snipe/snipe-it#10235]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I've recently updated my Snipe it to the latest build and also upgraded to the latest PHP. For 2-3 day's this has worked fine and all appeared O.K.

Yesterday we received the "Register The Auto Loader" text screen when attempting to get to the Snipe-it server.

I've corrected this with the following command - a2enmod php7.0 which has allowed us back within Snipe-IT however now when accessing the Admin section we receive the same page.

I'm quite new at Ubuntu and am still learning all the ropes so any help would be greatly appreciated.

### Reproduction steps

1.Browse to Server
2.Select Cog's top right corner.
3.Error Appears
...

### Expected behavior

Expect Admin section(LDAP and other settings to load).

### Screenshots

<?php

/**
 * Laravel - A PHP Framework For Web Artisans
 *
 * @package  Laravel
 * @author   Taylor Otwell <taylor@laravel.com>
 */

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader for
| our application. We just need to utilize it! We'll simply require it
| into the script here so that we don't have to worry about manual
| loading any of our classes later on. It feels nice to relax.
|
*/

require __DIR__.'/../bootstrap/autoload.php';

/*
|--------------------------------------------------------------------------
| Turn On The Lights
|--------------------------------------------------------------------------
|
| We need to illuminate PHP development, so let us turn on the lights.
| This bootstraps the framework and gets it ready for use, then it
| will load up this application so that we can run it and send
| the responses back to the browser and delight our users.
|
*/

$app = require_once __DIR__.'/../bootstrap/app.php';

// set the public path to this directory
$app->bind('path.public', function() {
    return __DIR__;
});

/*
|--------------------------------------------------------------------------
| Run The Application
|--------------------------------------------------------------------------
|
| Once we have the application, we can handle the incoming request
| through the kernel, and send the associated response back to
| the client's browser allowing them to enjoy the creative
| and wonderful application we have prepared for them.
|
*/

$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);

$response->send();

$kernel->terminate($request, $response);

### Snipe-IT Version

 Version v5.3.0 - build 6470 (master)

### Operating System

Ubuntu 20.04.3

### Web Server

Apache

### PHP Version

7.4

**Comment by snipe** [comment]
Closing as duplicate of https://github.com/snipe/snipe-it/issues/5611
