### ISSUE TITLE
Upgrade 5.3.0 clone button missing

### ISSUE THREAD

**Issue by ghost** [snipe/snipe-it#10244]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Clone button missing under list of assets after upgrading to 5.3.0.

### Reproduction steps

1.tried clearing all cache and multiple browsers
2.
3.
...

### Expected behavior

Clone button should be visible 

### Snipe-IT Version

5.3.0

### Operating System

ubuntu

### Web Server

apache

### PHP Version

8.0.5

### Operating System

Windows 10

### Browser

all

### Error messages

```shell
no errors seen
```

**Comment by snipe** [comment]
This is fixed on master, as mentioned in #10222
