### ISSUE TITLE
Bulk Update Users: "Login Enabled"

### ISSUE THREAD

**Issue by sylvank** [snipe/snipe-it#10247]
### Snipe-IT Version

v5.1.5

### Operating System

Linux

### Web Server

Apache

### PHP Version

7.2.34

### Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

Users automatically created via importing Assets are given the Login Enabled permission. 

### Describe the solution you'd like A clear and concise description of what you want to happen.

In the People view, when selecting "Bulk Edit" (/public/users/bulkedit), the option:

**Login Enabled [  ] This user can login**

Should be available just as it is on the individual user edit page (/public/users/2/edit)

### Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.

Having a global setting, eg. /public/admin/settings "Disable login for new users" [X] as a default would be helpful as well. 

I tried creating a group with all permissions disabled, and was able to bulk-add users to that group, but it leaves the "Login Enabled" permission on. The ability to disable login permission might also be appropriate to include here. (/public/admin/groups/1/edit)

**Comment by snipe** [comment]
This feature already exists in the current version.

<img width="358" alt="Screen Shot 2021-10-28 at 12 29 28 PM" src="https://user-images.githubusercontent.com/197404/139322736-efe3cf76-2ae5-42b0-93ba-0255565b3482.png">

**Comment by sylvank** [comment]
Apologies, the "activation status" terminology was unclear to me as I didn't see it connected to "Login Enabled" in any of the documentation I've seen so far; I assumed that would mark the user as deleted and prevent checking items out to them. Thanks for clarifying!

**Comment by snipe** [comment]
Yeah, it is a little confusing. (We changed the language on the edit screen to make it clearer, but perhaps missed it in the bulk edit screen)

**Comment by avielc** [comment]
Just curious, 
can that be fixed, I completed dodged this one and it was bothering me I couldn't block login.
