### ISSUE TITLE
Snipe IT Setup show the back end code of the program

### ISSUE THREAD

**Issue by Cjfrancisco2022** [snipe/snipe-it#10240]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Always show the code of the program instead the GUI of the snipe setup

### Reproduction steps

1. Check the APP URL
2.
3.
...

### Expected behavior

show the Snipe IT GUI

### Screenshots

![image](https://user-images.githubusercontent.com/93236329/139202326-20ad9b41-bc97-465b-ba13-d6f0b3e3b202.png)![error](https://user-images.githubusercontent.com/93236329/139202379-d2b5023e-7751-458c-8da6-70d00a824ac3.PNG)

### Snipe-IT Version

latest version

### Operating System

Ubuntu 20.04

### Web Server

Apache

### PHP Version

Php 7.4

### Operating System

Ubuntu

### Browser

Google

### Version

latest

### Device

Iphone

### Operating System

Ios

### Browser

Safari

### Version

latest

**Comment by YWatchman** [comment]
Hello,

This issue has nothing todo with the Snipe-IT app itself, please configure the PHP interpreter properly in your webserver.

**Comment by snipe** [comment]
Closing as duplicate of #5611
