### ISSUE TITLE
Mixed barcode and labels  

### ISSUE THREAD

**Issue by sasa-o** [snipe/snipe-it#1025]
When generate labels for multiple assets then barcode and it labels (asset tag and serial number) are mixed. I mean that link in barcode leads to another asset.  
v1.2.8-26

**Comment by snipe** [comment]
I don't understand what you mean - can you clarify?

**Comment by sasa-o** [comment]
I am sorry, I was wrong. Problem was in app for barcode scan. I tried to scan from monitor, and if in scan area was part another bar code, scanner recognizes link wrong. Sorry.
