### ISSUE TITLE
ui bug - adding new model from create asset screen - drop downs are cut off on the left

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#1028]
![image](https://cloud.githubusercontent.com/assets/10247644/9095059/3d84163c-3b83-11e5-867c-c5011082e7e1.png)

**Comment by snipe** [comment]
Sometimes I seriously feel like you're just trolling me lol

**Comment by kobie-chasehansen** [comment]
I feel like I troll myself.

My OCD is out of control. The people I work with hate me

**Comment by snipe** [comment]
![emergency-hug](https://cloud.githubusercontent.com/assets/197404/9096985/82102ab0-3b75-11e5-9e5f-408434ee0a19.gif)

**Comment by madd15** [comment]
not sure whether already fixed but mine don't get cut off

**Comment by kobie-chasehansen** [comment]
Looks good in Chrome on OS X, looks odd in Chrome on Windows.

**Comment by snipe** [comment]
I don't actually have a windows machine to test on, but might be able to dig up a VM

**Comment by kobie-chasehansen** [comment]
Think this is fixed, closing issue.

![image](https://cloud.githubusercontent.com/assets/10247644/11463756/d4bf1e94-96f4-11e5-8c93-500d734802a3.png)
