### ISSUE TITLE
Not able to create accessory

### ISSUE THREAD

**Issue by mbehal** [snipe/snipe-it#1030]
Hi,

While creating a new accessory, it asks for 'Accessory Category'. Is there any way to create  an 'Accessory Category' as i am not able to find one due to which i am not able to create an accessory.

Thanks
Manan

**Comment by snipe** [comment]
In the top-right admin menu.

<img width="431" alt="screen shot 2015-08-05 at 11 55 26 pm" src="https://cloud.githubusercontent.com/assets/197404/9105531/7f1bba06-3bcd-11e5-9eae-24ce00d1ea9f.png">

**Comment by mbehal** [comment]
Hi Snipe,

Actually on clicking the categories from the admin menu takes me to the assests category page. But here accessory category is different. Not able to find one. Please help.

Thanks and Regards
Manan

**Comment by snipe** [comment]
Just select "Accessory" from the dropdown. 

<img width="747" alt="screen shot 2015-08-06 at 12 02 52 am" src="https://cloud.githubusercontent.com/assets/197404/9105659/8a096124-3bce-11e5-91e1-000b376ff627.png">

**Comment by mbehal** [comment]
Hi Snipe,

i got it now, Actually on creating a new category there is a drop down of the type and in it accessory is listed.
thanks for help :)

Regards,
Manan
