### ISSUE TITLE
QR not displaying correctly in Firefox

### ISSUE THREAD

**Issue by thedaftbadger** [snipe/snipe-it#1031]
QR code being cut off when shown in Firefox
Bottom part of QR is being cut off
![screenshot_080615_014236_pm](https://cloud.githubusercontent.com/assets/13657363/9111664/19c1d856-3c41-11e5-977a-3d0de51907af.jpg)
##

**Comment by thedaftbadger** [comment]
Also the same issue with the QR code on the asset overview page
![screenshot_080615_015745_pm](https://cloud.githubusercontent.com/assets/13657363/9111942/3314b9f2-3c43-11e5-9b65-83a97afa5ad2.jpg)

*I am running Firefox for WIndows v36.0*

**Comment by snipe** [comment]
Can you confirm if this is happening on v3?
