### ISSUE TITLE
Clickable links in dashboard

### ISSUE THREAD

**Issue by seanism** [snipe/snipe-it#1038]
Make user or item clickable so you can go directly to the item or user.

**Comment by seanism** [comment]
Also the ability to show more items in the dashboard.  An option to show 5, 10, or 25 items underneath the list would be great.

**Comment by snipe** [comment]
@seanism Would a link to the Activity Report suffice? Since that is basically the extended version of the stuff on the dashboard

**Comment by seanism** [comment]
Yes that does solve it.  Figured it may be beneficial to have those links
as well but the report is perfect.  Thanks!
