### ISSUE TITLE
Is there any way to restrict an admin user of a group to see particular categories only.

### ISSUE THREAD

**Issue by mbehal** [snipe/snipe-it#1042]
Hi Snipe,

In my organization, we want to create 3 admin users and want to assign them different categories, like for an example:

Admin Users:
Desktop Team
PDA Team
Managers

Now we have asset categories:
PDA
Dektop

So is there any way that the 'Desktop Team' user can only see and manage the Desktop category assets only and every other category is invisible to him and same for 'PDA Team' can only see and manage PDA category assets.

And for 'Managers' can he see and manage the assets assigned to the members of his team.
##

**Comment by xtherebellion** [comment]
+1 I am definitely looking for something along these lines. Would also be great to have that visibility limitation, not just for assets but for licenses as well.

**Comment by PFF-Caleb** [comment]
Was this ever implemented? I would love to be able to let equipment managers see only the inventory that effects their location/site

**Comment by snipe** [comment]
It was not, and it's not on the short term roadmap.
