### ISSUE TITLE
Accessory zero stock level

### ISSUE THREAD

**Issue by thedaftbadger** [snipe/snipe-it#1045]
It isn't possible to create an accessory with a "0" stock level which is confusing when you are batch creating accessories to populate the system,

![screenshot_081115_014010_pm](https://cloud.githubusercontent.com/assets/13657363/9197711/9420b41e-402e-11e5-87d8-15fdba98d9c2.jpg)

**Comment by kobie-chasehansen** [comment]
This would be helpful for us too
