### ISSUE TITLE
Source an open source monitoring agent and provide an API that will work with it

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#1048]
##

**Comment by twistedR** [comment]
Is there any progress on this? If not, I would suggest @snipe come up with a pattern of how the API need to be created and whoever wants to write an API to any part of the system can do it. For example I would like an API to be able to get available assets and their types to be displayed on a dashboard other than snipe-it. 

If there is a standard documented way to naming the controllers, the return data blob I can create a patch to add that. This way no one person is liable to write a full on API and the community can go ahead and write parts as needed.

Thoughts?

**Comment by delize** [comment]
Can I suggest supporting Munki/MunkiReport-PHP being tied into this as well for Mac machines?
