### ISSUE TITLE
Feature Request: Schedule resources / make reservations

### ISSUE THREAD

**Issue by daihd** [snipe/snipe-it#1050]
Our users often need to reserve a resource (laptop, etc) in advance instead of doing ad-hoc check-out/ins.

This would include the following features:
- reserve a resource with a specific start and end date/time.
- within that time range no other users can make reservations nor check the item out
- other users can plan ahead with the anticipated booking end-time being displayed

As an example, [bookedscheduler.com](http://www.bookedscheduler.com) supports this feature.
##

**Comment by CrewNerd** [comment]
+1

**Comment by izharyuk** [comment]
Could really use resource reservation feature in my environment also.

**Comment by JamesIsNinja** [comment]
+1, my group will be moving to Snipe-IT from Sharepoint, but sharepoint will still have to contain our booking method at the moment

**Comment by strgn** [comment]
+1

**Comment by grifu** [comment]
Schedule resources would be a great improvement for Snipe-it. I would like to help or make a contribution to this request. however, I started working with Snipe-it today. 
Maybe including custom fields in the request procedure.

**Comment by AmoVanB** [comment]
We are also willing to have such a reservation system and it would hence be great to add this to SnipeIT which we are already using!
