### ISSUE TITLE
Docker build Fails

### ISSUE THREAD

**Issue by RPSource** [snipe/snipe-it#1052]
Today I wanted to build a new image on a Digital Ocean server.

Sadly the docker build command fails at step 15 - patching using app_start.patch

the error is:
````
Hunk #1 FAILED at 24.
1 out of 1 hunk FAILED -- saving rejects to file bootstrap/start.php.rej
The command '/bin/sh -c patch -p1 < /tmp/app_start.patch' returned a non-zero code: 1
````
Any idea how I could resolve this (I already tried changing the permissions for all files

Thanks

**Comment by uberbrady** [comment]
Oh, it's definitely something that must've broken in one of the later Ubuntu, I'd figure. It's something broken on our end for sure. I'll get it fixed.

**Comment by snipe** [comment]
<insert hunk joke here>

**Comment by uberbrady** [comment]
PR #1122 fixed this problem.

**Comment by gionniboy** [comment]
how i can fix it? i have same problem :\
[i use the lastest snipeit github repos]

~/snipe-it$ docker build -t snipeit .
Sending build context to Docker daemon 9.701 MB
Step 0 : FROM ubuntu
 ---> 91e54dfb1179
Step 1 : MAINTAINER Brady Wetherington <uberbrady@gmail.com>
 ---> Using cache
 ---> 2e46b2e30293
Step 2 : RUN apt-get update && apt-get install -y apache2-bin libapache2-mod-php5 php5-curl php5-ldap php5-mysql php5-mcrypt php5-gd patch curl vim git
 ---> Using cache
 ---> 2c1268f310e8
Step 3 : RUN php5enmod mcrypt
 ---> Using cache
 ---> 228e409a41e5
Step 4 : RUN php5enmod gd
 ---> Using cache
 ---> 1b4ef3badd0f
Step 5 : RUN sed -i 's/variables_order = .*/variables_order = "EGPCS"/' /etc/php5/apache2/php.ini
 ---> Using cache
 ---> 6d4fb8ae3a6a
Step 6 : RUN sed -i 's/variables_order = .*/variables_order = "EGPCS"/' /etc/php5/cli/php.ini
 ---> Using cache
 ---> 5ec57728ef5a
Step 7 : RUN useradd --uid 1000 --gid 50 docker
 ---> Using cache
 ---> c201a3028c43
Step 8 : RUN echo export APACHE_RUN_USER=docker >> /etc/apache2/envvars
 ---> Using cache
 ---> f38c5e804850
Step 9 : RUN echo export APACHE_RUN_GROUP=staff >> /etc/apache2/envvars
 ---> Using cache
 ---> 91c44f178fbe
Step 10 : COPY docker/000-default.conf /etc/apache2/sites-enabled/000-default.conf
 ---> b9bd2c55b1e3
Removing intermediate container bf27e4e4ff73
Step 11 : COPY . /var/www/html
 ---> 07b9283622f1
Removing intermediate container 169f263438fe
Step 12 : RUN a2enmod rewrite
 ---> Running in a2c8d5e1856c
Enabling module rewrite.
To activate the new configuration, you need to run:
  service apache2 restart
 ---> c65b38fbd674
Removing intermediate container a2c8d5e1856c
Step 13 : COPY docker/app_start.patch /tmp/app_start.patch
 ---> c88c9d060463
Removing intermediate container 153f0104991b
Step 14 : WORKDIR /var/www/html
 ---> Running in ee6e672f619c
 ---> f1b926b7b3ea
Removing intermediate container ee6e672f619c
Step 15 : RUN patch -p1 < /tmp/app_start.patch
 ---> Running in 3f999d756a1c
patching file bootstrap/start.php
Hunk #1 FAILED at 24.
1 out of 1 hunk FAILED -- saving rejects to file bootstrap/start.php.rej
The command '/bin/sh -c patch -p1 < /tmp/app_start.patch' returned a non-zero code: 1

**Comment by uberbrady** [comment]
Are you using the latest public release, or the latest from 'dev'? The latest 'master' release - 2.0 - doesn't have this fix integrated yet.

I think this fix is expected to be integrated into 2.1. If you're willing to run 'development' code, you can try to build the docker image from the 'dev' branch to see if that fixes it for you? If you don't like running development code - which totally is a reasonable thing to not like - we'll have to ask @snipe when she expects to release the 2.1 version, or if she wants to do a 2.0.1 or something like that.

**Comment by snipe** [comment]
Ask and ye shall receive.
https://github.com/snipe/snipe-it/releases/tag/v2.0.1

![opossum-bongos](https://cloud.githubusercontent.com/assets/197404/9675409/1f006c6e-5272-11e5-8533-785b24274878.gif)

**Comment by gionniboy** [comment]
oh... ok :) i will try it
thank you guys... and thank you, also, for snipeit: is a great job :)

**Comment by fpalmcrantz** [comment]
@gionniboy: Were you able to confirm the issue as resolved with 2.0.1? I'm asking because I'm still seeing issues with that version. I also tried a snapshot of the development branch this morning and same issue I'm afraid.

My attempt at building a Docker image fails at the same step (patching).
```
...
Hunk #1 FAILED at 24.
1 out of 1 hunk FAILED -- saving rejects to file bootstrap/start.php.rej
The command '/bin/sh -c patch -p1 < /tmp/app_start.patch' returned a non-zero code: 1
```

I'm assuming this is an issue with my build environment but would be very interested to learn if (and if so how) other are getting the build to complete.

**Comment by snipe** [comment]
@uberbrady can you take a look at this when you get a chance?

**Comment by uberbrady** [comment]
I'm checking this out with a fresh Master build.

**Comment by uberbrady** [comment]
Yup, one chunk failed for me to on a fresh build from master.

**Comment by fpalmcrantz** [comment]
https://github.com/snipe/snipe-it/commit/49a20c75ed4b0f9d3a66ddf6bd33d8c24bc571c0 did the trick. I was now able to build the image (used 2.0.3 release with the updated files from your latest commit).

Thank you for the quick update
