### ISSUE TITLE
Feature Request - Integrate document viewer for uploaded files

### ISSUE THREAD

**Issue by hansenc0705** [snipe/snipe-it#1053]
We are finding that a lot of the documents we upload to assets/licenses are being referenced frequently. Would be nice if they could be opened directly in browser someway.
##

**Comment by snipe** [comment]
What kind of files?

**Comment by kobie-chasehansen** [comment]
My need is for pdfs but I could see others having request for doc/docx/txt/etc.

**Comment by snipe** [comment]
What kind of document viewer did you have in mind? Does IE not have an integrated PDF viewer?

**Comment by kobie-chasehansen** [comment]
Using chrome right now, the only way to view the pdfs is to download them. maybe its just a way the PDF's are shown in the asset view screen.

**Comment by snipe** [comment]
So I think we have to let the browser do whatever we can with it (i.e. view the PDF in the browser, versus trying to come up with a special document browser plugin thing), but I think this can be solved pretty easily by providing two icons in the file view area - view, and download. 

If the filetype is a PDF, open it inline if you click on the view icon, download if you click on the download icon.

If it is an image of some kind, open it in a lightbox if you click on view, download if it says download. 

We should basically just be able to tweak the bit in the controllers to accept a parameter to determine whether we should `return Response::download($file);` (to download) or   something else to display.

**Comment by kobie-chasehansen** [comment]
sounds good to me :)

**Comment by imie** [comment]
im thinking of requesting this function too. 

but i dont need online viewer. as long i can download back the attachment is fine. mostly pdf and jpg or png type.
