### ISSUE TITLE
Bug: editing asset is broken

### ISSUE THREAD

**Issue by aalaily** [snipe/snipe-it#1054]
**Description**
After creating an asset, you cannot, you cannot edit it.  If you navigate to the assets overview page and click on the edit icon associated with the asset in question, the application will throw an Internal Server Error page.

**Error Message**
Next exception 'ErrorException' with message 'Undefined variable: statuslabel_types (View: C:\www\htdocs\snipe-it\app\views\backend\hardware\edit.blade.php)' in C:\www\htdocs\snipe-it\app\storage\views\8a9b150f27ab06a8fa4027129b8b1243:45

This error can also be reproduced on the live production demo here: https://demo.snipeitapp.com

**Comment by snipe** [comment]
Hi @aalaily - the develop branch is not 100% stable, as we're preparing for the 2.0 release. You should use one of the official releases.

**Comment by aalaily** [comment]
Sounds good.  I assumed this was an issue with the develop branch (as I'm working on that branch) ... however, when I noticed it on your live demo I figured I should flag it just in case it turns people off.  I think this is a very good tool so it would be unfortunate if people were turned off because editing doesn't work (in the demo).

Thanks for the quick reply.

**Comment by snipe** [comment]
Definitely appreciated :) The demo is a bleeding edge demo, so these things sometimes happen. (We should probably provide a stable one as well, for the reasons you mention.)

Should be fixed on develop and on the demo now.

**Comment by aalaily** [comment]
Excellent.  I will update my code.  So the demo is built off of the develop branch?

**Comment by snipe** [comment]
Yes, demo gets auto-deployed as soon as the dev branch is pushed by us, or as soon as a PR against develop is merged. Hence the bleeding edge bit ;) We're suuuuper close to a 2.0 beta release (like, days), and just merged all of our 2.0 changes into the development branch a few days ago, so still working out some kinks.

**Comment by snipe** [comment]
![failed-attempt](https://cloud.githubusercontent.com/assets/197404/9260892/663b05da-41bf-11e5-8ccb-b14bf29493cf.gif)

**Comment by snipe** [comment]
(You should just be able to do a git pull to grab the changes we just pushed out)

**Comment by aalaily** [comment]
bad usage of words on my part: my update = git pull

**Comment by aalaily** [comment]
***We're suuuuper close to a 2.0 beta release (like, days), and just merged all of our 2.0 changes into the development branch a few days ago, so still working out some kinks.***

good stuff.
