### ISSUE TITLE
Error on clicking "Dashboard" or "Snipe-IT Asset Management"

### ISSUE THREAD

**Issue by rzblue** [snipe/snipe-it#1055]
When I click on "Dashboard" or "Snipe-IT Asset Management" it gives me this
I think we're lost.
Server Error: 404 (Not Found)
What does this mean?

We couldn't find the page you requested on our servers. We're really sorry about that. It's our fault, not yours. We'll work hard to get this page back online as soon as possible.

Perhaps you would like to go to our home page?

The address bar says it sent me to this (with "myip" replacing my actual server ip):
http://myip/myip/snipe-it

**Comment by snipe** [comment]
Please see the documentation on getting help: http://docs.snipeitapp.com/getting-help.html

**Comment by xycofryx** [comment]
I have the same issue above while clicking the dashboard link and and title link. All the links are working exept for the two links.

Snipe-it version: v2.0
OS: Ubuntu Server 14.04
Browser: Chrome, Firefox, IE

**Comment by snipe** [comment]
What do you have your URL set to in your app config file?

**Comment by xycofryx** [comment]
The IP of my test server.

**Comment by snipe** [comment]
And when you click on the dashboard, what URL is it taking you to?

**Comment by xycofryx** [comment]
something like this "http://172.16.0.201:81/172.16.0.201:81"

**Comment by snipe** [comment]
Can you paste the actual URL line in your config? (You can obsure the actual IP, but looking to see if it starts with http://, which it should.)

**Comment by xycofryx** [comment]
'url' => '172.16.0.201:81',

**Comment by snipe** [comment]
Yeah, you need the http:// at the beginning

**Comment by xycofryx** [comment]
Wow! it worked like a charm. thanks snipe :)

**Comment by rzblue** [comment]
This worked for me also. Thanks!
