### ISSUE TITLE
Links in asset notes

### ISSUE THREAD

**Issue by thedaftbadger** [snipe/snipe-it#1056]
It would be good to have hyperlinks active in the notes section of assets.
For example.... we may want to include a local link to a devices management interface such as a printer etc.

For security you could argue that this should be in a field of its own so that it isnt visible to general users and only admins.

![screenshot_081415_085726_am](https://cloud.githubusercontent.com/assets/13657363/9269565/d8340c38-4262-11e5-924e-108ad7f493f2.jpg)
##

**Comment by snipe** [comment]
I feel like maybe parsing the notes field through markdown might be the easiest solution here.

**Comment by thedaftbadger** [comment]
Do you not think that sometimes admins want notes that other user don't need to see?

**Comment by snipe** [comment]
Possibly, but that's a different discussion over whether to parse links in notes. Adding a URL field is an arbitrary thing, and many people won't use that. It makes more sense to me to use parsedown in notes, and have a global setting of whether notes should be visible to non-admins.

**Comment by thedaftbadger** [comment]
Good idea :)
A much cleaner solution.

If people start to store notes for assets with markdown won't its current location above the QR code be a bit restrictive / messy?

**Comment by snipe** [comment]
That whole UI needs to be re-done, so it's one of the many challenges I'll worry about then. ;)

![bad-hula](https://cloud.githubusercontent.com/assets/197404/9285170/ed8aa350-4297-11e5-9f12-a3de61570307.gif)
