### ISSUE TITLE
Add notes on view asset page

### ISSUE THREAD

**Issue by seanism** [snipe/snipe-it#1057]
I know you can add notes when you check in/ check out but it would be great to add additional notes on the view asset page.

Also being able to change status from that page rather then going into edit view would be helpful.
##

**Comment by rayvenshire** [comment]
+1

I might also suggest that editing the note on the asset page trigger an insert into the asset view page with an action like "edited note", as otherwise those changes appear to be unlogged.

**Comment by donatt** [comment]
+1 I think it would be great to have a page with on that it's possible to select the asset (either by tag or name), the action category, person that did the action (reboot, upgrade, installation...) and a note. Than this would be visible in the overview and in and on the asset it self. The action type should be editable by the admin. The functionalty would by like a "serverjournal".
