### ISSUE TITLE
User import error

### ISSUE THREAD

**Issue by nickmacwiz** [snipe/snipe-it#1058]
On Pre-Beta 2.0 you get an error 500 page error when trying to import users thru csv file.

**Comment by snipe** [comment]
Please see the getting help documentation and provide us with specific error logs:
http://docs.snipeitapp.com/getting-help.html

**Comment by nickmacwiz** [comment]
windows server 2008 r2 iis


![screenshot 2015-08-14 17 50 51](https://cloud.githubusercontent.com/assets/11078660/9286689/dfb2578a-42ad-11e5-829e-aeca520fd46a.png)



LOG BELOW:

[2015-08-15 00:44:30] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:148
Stack trace:
#0 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1054): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1022): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#7 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#8 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#9 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#10 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#11 C:\inetpub\wwwroot\FrhsAsset\snipe-it\public\index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2015-08-15 00:46:03] production.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'Franklin High School' for column 'location_id' at row 1' in C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php:369
Stack trace:
#0 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(369): PDOStatement->execute(Array)
#1 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(617): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `us...', Array)
#2 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `us...', Array, Object(Closure))
#3 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(370): Illuminate\Database\Connection->run('insert into `us...', Array, Object(Closure))
#4 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(327): Illuminate\Database\Connection->statement('insert into `us...', Array)
#5 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1894): Illuminate\Database\Connection->insert('insert into `us...', Array)
#6 C:\inetpub\wwwroot\FrhsAsset\snipe-it\app\controllers\admin\UsersController.php(659): Illuminate\Database\Query\Builder->insert(Array)
#7 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\league\csv\src\Reader.php(76): Controllers\Admin\UsersController->Controllers\Admin\{closure}(Array, 1, Object(LimitIterator))
#8 C:\inetpub\wwwroot\FrhsAsset\snipe-it\app\controllers\admin\UsersController.php(693): League\Csv\Reader->each(Object(Closure))
#9 [internal function]: Controllers\Admin\UsersController->postImport()
#10 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#11 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postImport', Array)
#12 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\UsersController), Object(Illuminate\Routing\Route), 'postImport')
#13 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\\Adm...', 'postImport')
#14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#15 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Route.php(109): call_user_func_array(Object(Closure), Array)
#16 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#18 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#19 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#20 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#21 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#22 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#23 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#24 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#25 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#26 C:\inetpub\wwwroot\FrhsAsset\snipe-it\public\index.php(49): Illuminate\Foundation\Application->run()
#27 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'Franklin High School' for column 'location_id' at row 1 (SQL: insert into `users` (`first_name`, `last_name`, `username`, `email`, `password`, `activated`, `location_id`, `permissions`, `notes`) values (Justin, Abad Santos, 99692973, kc_abadsantos@yahoo.com, aZMyWQx5Vc, 1, Franklin High School, {"user":1}, Imported user))' in C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php:625
Stack trace:
#0 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `us...', Array, Object(Closure))
#1 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(370): Illuminate\Database\Connection->run('insert into `us...', Array, Object(Closure))
#2 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(327): Illuminate\Database\Connection->statement('insert into `us...', Array)
#3 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1894): Illuminate\Database\Connection->insert('insert into `us...', Array)
#4 C:\inetpub\wwwroot\FrhsAsset\snipe-it\app\controllers\admin\UsersController.php(659): Illuminate\Database\Query\Builder->insert(Array)
#5 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\league\csv\src\Reader.php(76): Controllers\Admin\UsersController->Controllers\Admin\{closure}(Array, 1, Object(LimitIterator))
#6 C:\inetpub\wwwroot\FrhsAsset\snipe-it\app\controllers\admin\UsersController.php(693): League\Csv\Reader->each(Object(Closure))
#7 [internal function]: Controllers\Admin\UsersController->postImport()
#8 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#9 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postImport', Array)
#10 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\UsersController), Object(Illuminate\Routing\Route), 'postImport')
#11 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\\Adm...', 'postImport')
#12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#13 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Route.php(109): call_user_func_array(Object(Closure), Array)
#14 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#16 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#17 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#18 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#19 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#20 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#21 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#22 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#23 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#24 C:\inetpub\wwwroot\FrhsAsset\snipe-it\public\index.php(49): Illuminate\Foundation\Application->run()
#25 {main} [] []
[2015-08-15 00:50:24] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:148
Stack trace:
#0 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1054): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1022): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#7 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#8 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#9 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#10 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#11 C:\inetpub\wwwroot\FrhsAsset\snipe-it\public\index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2015-08-15 00:50:33] production.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'Franklin High School' for column 'location_id' at row 1' in C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php:369
Stack trace:
#0 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(369): PDOStatement->execute(Array)
#1 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(617): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `us...', Array)
#2 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `us...', Array, Object(Closure))
#3 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(370): Illuminate\Database\Connection->run('insert into `us...', Array, Object(Closure))
#4 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(327): Illuminate\Database\Connection->statement('insert into `us...', Array)
#5 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1894): Illuminate\Database\Connection->insert('insert into `us...', Array)
#6 C:\inetpub\wwwroot\FrhsAsset\snipe-it\app\controllers\admin\UsersController.php(659): Illuminate\Database\Query\Builder->insert(Array)
#7 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\league\csv\src\Reader.php(76): Controllers\Admin\UsersController->Controllers\Admin\{closure}(Array, 1, Object(LimitIterator))
#8 C:\inetpub\wwwroot\FrhsAsset\snipe-it\app\controllers\admin\UsersController.php(693): League\Csv\Reader->each(Object(Closure))
#9 [internal function]: Controllers\Admin\UsersController->postImport()
#10 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#11 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postImport', Array)
#12 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\UsersController), Object(Illuminate\Routing\Route), 'postImport')
#13 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\\Adm...', 'postImport')
#14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#15 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Route.php(109): call_user_func_array(Object(Closure), Array)
#16 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#17 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#18 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#19 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#20 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#21 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#22 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#23 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#24 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#25 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#26 C:\inetpub\wwwroot\FrhsAsset\snipe-it\public\index.php(49): Illuminate\Foundation\Application->run()
#27 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'Franklin High School' for column 'location_id' at row 1 (SQL: insert into `users` (`first_name`, `last_name`, `username`, `email`, `password`, `activated`, `location_id`, `permissions`, `notes`) values (Justin, Abad Santos, 99692973, kc_abadsantos@yahoo.com, KXHStgcdGJ, 1, Franklin High School, {"user":1}, Imported user))' in C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php:625
Stack trace:
#0 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `us...', Array, Object(Closure))
#1 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(370): Illuminate\Database\Connection->run('insert into `us...', Array, Object(Closure))
#2 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(327): Illuminate\Database\Connection->statement('insert into `us...', Array)
#3 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1894): Illuminate\Database\Connection->insert('insert into `us...', Array)
#4 C:\inetpub\wwwroot\FrhsAsset\snipe-it\app\controllers\admin\UsersController.php(659): Illuminate\Database\Query\Builder->insert(Array)
#5 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\league\csv\src\Reader.php(76): Controllers\Admin\UsersController->Controllers\Admin\{closure}(Array, 1, Object(LimitIterator))
#6 C:\inetpub\wwwroot\FrhsAsset\snipe-it\app\controllers\admin\UsersController.php(693): League\Csv\Reader->each(Object(Closure))
#7 [internal function]: Controllers\Admin\UsersController->postImport()
#8 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#9 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postImport', Array)
#10 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\UsersController), Object(Illuminate\Routing\Route), 'postImport')
#11 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\\Adm...', 'postImport')
#12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#13 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Route.php(109): call_user_func_array(Object(Closure), Array)
#14 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#16 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#17 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#18 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#19 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#20 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#21 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#22 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#23 C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#24 C:\inetpub\wwwroot\FrhsAsset\snipe-it\public\index.php(49): Illuminate\Foundation\Application->run()
#25 {main} [] []

**Comment by snipe** [comment]
See this part of the error:

```
Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'Franklin High School' for column 'location_id' at row 1 (SQL: insert into users (first_name, last_name, username, email, password, activated, location_id, permissions, notes) values (Justin, Abad Santos, 99692973, kc_abadsantos@yahoo.com, aZMyWQx5Vc, 1, Franklin High School, {"user":1}, Imported user))' in C:\inetpub\wwwroot\FrhsAsset\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php:625
```

Looks like you have text in the location field where it's expecting an ID number of the location.

PS - which Franklin High School? I went to school at a Franklin High School.

**Comment by nickmacwiz** [comment]
Franklin High School in Elk Grove, CA

**Comment by nickmacwiz** [comment]
and thanks

**Comment by snipe** [comment]
Got it - mine was in NJ :)

**Comment by nickmacwiz** [comment]
Nice! What was your mascot?  The Franklin here are the Wildcats.   Where would i find the location ID?

**Comment by snipe** [comment]
We were the Warriors. :)

You'd find the ID by going to the Locations section of the admin. We don't display the ID number (since  most people don't need it), but if you click through on the location you want and look at the URL, you'll see it in the URL bar.

`/admin/settings/locations/4/edit`

4 would be the ID number in the above example

**Comment by snipe** [comment]
Also, if you already have assets for these users, you may wan to check out the command line tool, which is much more powerful.

http://docs.snipeitapp.com/manual/importing-assets.html

**Comment by nickmacwiz** [comment]
We dont have assets checked out to any of them however we are importing all 2700 students into the system so i have the entire student census file as a CSV to upload into the system.

**Comment by nickmacwiz** [comment]
The error it is pulling now is that not all users have email or some have duplicate because i am using the parent emails and some parents have multiple students. Any idea on a way around this?

**Comment by snipe** [comment]
All users currently have to have a unique email address, as that's what's used for the login (until version 2.0 comes out), and logins can't really work if there is more than one in the database. Will these users ever need to login, or do you plan in using the EULA/asset acceptance aspects of Snipe-IT?

**Comment by nickmacwiz** [comment]
i figured it out. I just went into excel and made is some number @ yahoo.com and dragged it down to make the email addresses unique. They won't need to log in unless they are made an admin or checkout person or certain classes will require they have access so in those cases we will edit user on an individual basis. Thanks for the help.

**Comment by nickmacwiz** [comment]
They site is still loading so i think its uploading...

**Comment by snipe** [comment]
Interesting.... you bring up a use case I hadn't thought about, and that is using parent's email addresses for students. In 2.0, it uses usernames, which still need to be unique, but I'll need to think about how to handle parent+child stuff, since so many schools use Snipe-IT.

**Comment by nickmacwiz** [comment]
well the username thing is easily handeled for our school and district because we use unique student id numbers and the file has that added as the username however the bigger problem is that i just had it throw the same error page and when i checked the log it is because it hit the maximum of 300 seconds.

**Comment by snipe** [comment]
Yeah, that execution time thing is why the other importers are command line. If you break it into smaller files, it should work. Otherwise you can try increasing your `max_execution_time` in your php.ini.

**Comment by nickmacwiz** [comment]
To handel this new issue i recommend telling people that if they are uploading from a computer off site of the server location to upload no more then 500 at a time and if onsite then 1000.

**Comment by nickmacwiz** [comment]
I would love to be a part of the planning and features and what not as far as things like this are concerned as I am a Computer Science Major and I also work part time for a school District and i just push this system out to one of our sites and if it works out they may adopt it more widely.

**Comment by nickmacwiz** [comment]
There is a feature that would be helpful to schools especially ours when we get around to the new school year. The ability for each user to have a check box next to them in the user list and then the ability to select all then deselect a few for example the admin (manually) and then the ability to select delete users. Because for example in your system at the end of the school year i need to delete 2700 students.

**Comment by aalaily** [comment]
@nickmacwiz I believe this feature already exists

**Comment by aalaily** [comment]
@nickmacwiz 
<img width="90" alt="untitled-1 fw" src="https://cloud.githubusercontent.com/assets/2475759/9289991/73318d0e-434f-11e5-87ae-8bdce2a970ed.png">

**Comment by nickmacwiz** [comment]
What version are you running?

Sincerely,


Nicholas Ruebel

**Comment by snipe** [comment]
@nickmacwiz this feature is on dev already, specifically because of folks at schools. It will be in 2.0, or you can play with it now if you grab the latest from the develop branch.

(Also, please open a new ticket for feature requests )
