### ISSUE TITLE
Two-factor authentication

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#106]
Using Duo-Security, potentially other vendors.
##

**Comment by DWSR** [comment]
Azure MFA would be my vote, since you're already providing AD Integration. This would allow companies that are Federating AD and AAD to leverage this app very effectively.

**Comment by Profecy** [comment]
YubiKey might be handy as well!
Or at least generic OTP or maybe challenge-repsonse?

**Comment by davidking727** [comment]
Will this be in V3?

**Comment by snipe** [comment]
@davidking727 no, not in v3

**Comment by snipe** [comment]
FYI, I have a working version of this that I'm about to push up to dev. Need to add some additional settings and the ability for an admin to clear a secret key/enrollment status (for the case where a user has lost their phone, etc).
