### ISSUE TITLE
v6.0.0-RC2 - Cannot select company on modal user form

### ISSUE THREAD

**Issue by Robert-Azelis** [snipe/snipe-it#10618]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

During create new asset, if I want to create new user, cannot select company.

### Reproduction steps

1. Open form for create new asset
2. Use option to create new user (modal form)
3. Select company

### Expected behavior

In modal user form, company should be propagated from asset form or should be possible to select company for which user should be assign.

### Screenshots

![image](https://user-images.githubusercontent.com/82208283/152684564-b458d4a0-1efa-4641-8968-3c4e7a96dc59.png)

### Snipe-IT Version

v6.0.0-RC2

### Operating System

Windows

### Web Server

IIS

### PHP Version

7.4

### Operating System

Windows 10

### Browser

Google Chrome, MS Edge

**Comment by snipe** [comment]
I believe this is fixed in the latest RC - thanks for testing! ♥️
