### ISSUE TITLE
HTTPS Redirection

### ISSUE THREAD

**Issue by firozhaneef** [snipe/snipe-it#1062]
Hi,

I have configured snipe-it through SSL but while i am trying to log in into snipe-it, it is always forwarding the links without https://.

Firoz

**Comment by firozhaneef** [comment]
I am using centos, apache and mysql.

**Comment by firozhaneef** [comment]
If i access snipe-it by using https://, browser is loading the login page without any enhancements, i mean plain text and user name password box, while i am trying to log in, it is redirecting to login page with out https://.

**Comment by peelman** [comment]
Did you properly set your 'url' parameter to use HTTPS under `app/config/production/app.php`?

**Comment by firozhaneef** [comment]
Yes, I think the problem was, SSL certificate was not set for the subdomain which i have created only for snipe-it, once i edited sites-available file of apache and added the ssl certificate path for the subdoamin, the page is loading fine. Thanks.
