### ISSUE TITLE
php composer.phar install fails after upgrade to ver2-pre-beta

### ISSUE THREAD

**Issue by kylevitale** [snipe/snipe-it#1066]
When I run php composer.phar install I get the below output. I also ran php composer.phar update and selfupdate.

I'm running on Ubuntu 14.04 LTS and nginx (latest).

Output:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - codeception/codeception 2.1.x-dev requires facebook/webdriver ~0.4|~0.5 -> no matching package found.
    - codeception/codeception 2.1.x-dev requires facebook/webdriver ~0.4|~0.5 -> no matching package found.
    - Installation request for codeception/codeception 2.1.x-dev -> satisfiable by codeception/codeception[2.1.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by snipe** [comment]
Are you planning on doing any development on it, or just running it? Did you install with the --no-dev flag?

**Comment by snipe** [comment]
Those versions of web driver definitely exist: https://packagist.org/packages/facebook/webdriver#v0.4

**Comment by kylevitale** [comment]
Just running it. I didn't use the no-dev flag, only followed the normal
upgrade install instructions.

**Comment by snipe** [comment]
Upgrading instructions do specify --no-dev:
http://docs.snipeitapp.com/upgrading.html

That said, I just ran a composer update locally to update the composer lock, and haven't been able to reproduce this error, using --no-dev or with dev.

Try with `--no-dev`. Codeception is a development tool, so if you're just running it to run it, you shouldn't need the codeception package.

**Comment by kylevitale** [comment]
Oops. I didn't know about the --no-dev option. It worked fine once i used follow the directions. :)

Sorry about that!

**Comment by snipe** [comment]
Still weird that you're seeing that though. I haven't been able to reproduce it, but will keep my eyes peeled for other reports of this issue.

**Comment by snipe** [comment]
Glad `--no-dev` worked for you though.
