### ISSUE TITLE
where is php.exe located?

### ISSUE THREAD

**Issue by torbuck** [snipe/snipe-it#1067]
Greetings

Our organization is looking at using Snipe-IT for managing some inventory. I am in the process of installing the software on a Windows 2008 R2 server. I'm going through the process of installing the dependencies. I am at the point where I am installing "Composer-Setup.exe". When I start the install, it asks me to select where php.exe is located. If I search the Snipe-it folder, I cannot locate php.exe, so unsure if it is included in the source files. The instructions also describe  "Right click and select Composer Install". If I right-click on "Composer-Setup.exe",  you don't get a "composer install" option. You would only have the following options:

Open
Run as administrator
Troubleshoot compatibility
Restore previous version
Send To ->
Cut 
Copy
Create Shortcut
Delete
Rename
Properties

If anyone can give me some insight as how this step should be completed on a Windows 2008 server, I would be much appreciated

Thanks

**Comment by snipe** [comment]
Do you actually have PHP downloaded? http://docs.snipeitapp.com/requirements.html

**Comment by torbuck** [comment]
I feel like an idiot. Appears that I missed that step. I totally missed the general system requirements.I just looked at the sepecifc Windows server requiremens

**Comment by snipe** [comment]
It's okay, it happens :)
