### ISSUE TITLE
Question: How do you create and print labels?

### ISSUE THREAD

**Issue by gregcornell** [snipe/snipe-it#1068]
I am having troubles trying to find a way to quickly format and print labels for assets using QR codes. Currently I am using a DYMO LabelWriter 450 DUO Label and their label making software  and the process is tedious and extremely time consuming. 

I am wondering what other users have done in terms of formatting and printing labels quickly.

Any feedback is greatly appreciated.

Thanks

**Comment by snipe** [comment]
Please see the documentation on generating labels: http://docs.snipeitapp.com/manual/labels.html

**Comment by kieran21** [comment]
I see what @gregcornell is saying. I'm thinking it it wouldn't be too difficult to code something for Snipe-IT to have the option of generating a bunch of DYMO compatible .label files (which are just XML). 

I've looked into this a little. If one were to generate say a .zip archive of .label files, I think only the URL bit needs changing - then just download, extract, select and Send To DYMO printer.

```
...
<Cell>
				<BarcodeObject>
					<Name>BARCODE</Name>
					...
					<Text>URL:http://192.168.1.148/snipe/public/hardware/6/view</Text>
					...
				</BarcodeObject>
</Cell>
...
```
Having done this manually the DYMO v.8 software generates and prints identical QR codes to those outputted by Snipe-IT.
