### ISSUE TITLE
Dashboard - Menu enhancement

### ISSUE THREAD

**Issue by tsilman-marquette** [snipe/snipe-it#1069]
Add/Remove/Rename menu items via Admin settings.

I am using SnipeIT for administering a tool crib. I do not use licenses and would like the option of removing the item from the menu.

I am looking forward to 2.0 since it includes the needed consumables menu item!
##

**Comment by thedaftbadger** [comment]
:+1:

**Comment by tbradsha** [comment]
A simple solution might be to leave the boxes in place, and just de-link and grey them out? This would prevent confused users from clicking on them.

**Comment by mahesh2471990** [comment]
Disabling the feature completely helps us to simplify the dashboard for admin as well for nora=mal users

**Comment by snipe** [comment]
> Just a Tick mark(Checkbox). Example

"Just" is one of those words that's super problematic.  It's not "just". There are hundreds of places where changes would need to be made to implement this feature.

**Comment by tsilman-marquette** [comment]
After I left the comment I started digging to try and understand the code with my limited knowledge. 
I soon realized that I am using this tool for a problem that it was not really intended to solve.
However, I'm still using snipe-it (2 years) because it solves my constellation of problems.
Keep incrementally improving!

**Comment by MrMontesa** [comment]
Just came across this FR and wanted to share my +1 👍 . We just started using Snipe and dont use Consumables nor Components. Some end-users as well as some non techie asset workers are confused by the the options, so we would love to disable those two sections.
Just hiding them via CSS would we ok for now so that we can hide them from main menu as well as from /account/view-assets view. Possibly a div container around the section and make it display:none?

Any recommendations for a dirty hack.
Thanks much

**Comment by TheNetworkGuy** [comment]
Agreed with previous post. Would love to hide specific functions. In my case consumables and accessories are not used so hiding them would be a great addition to improve usability.

Using just CSS seems a bit tricky; the main modules are referenced at multiple places (dashboard, top nav bar, left nav bar etc.)

**Comment by MoNikoCo** [comment]
I agree with the two posts above, we would definitely like the ability to remove unused functions from the navigation pane.

**Comment by RiderWJ** [comment]
So still no real solution for this? Like Snipeit, but also would like to see some updates.

**Comment by snipe** [comment]
Updates? Dude, we push updates every single day, new releases every few weeks. This one is just lower priority for us. Your priority isn’t always going to be our priority.

**Comment by RiderWJ** [comment]
> Updates? Dude, we push updates every single day, new releases every few weeks. This one is just lower priority for us. Your priority isn’t always going to be our priority.

Bro, chill out, bad wording, sorry. Just checking.

**Comment by snipe** [comment]
Not a bro, and I won't "chill out" because I wasn't un-"chill". What you're saying is just factually incorrect, and implying that we're just sitting around is obnoxious, and certainly isn't a way to push the feature up the priority list.

**Comment by kaeser49** [comment]
Hi there,
from our relaxed point of view, a customizable menu would really be not only a visual help, but also a time saver.
We do not need most of the menu labels on top level on a daily basis. 

- All ready to deploy
- Locations
- Asset Model

we need the most. The later two are shown under Settings. That I can not understand.
Please higher up these requests which are important for the users of the super software.
Thank you.

**Comment by TechnologyClassroom** [comment]
@tsilman-marquette @MrMontesa Here is a dirty CSS hack to hide the `Licenses` option from displaying.  @tbradsha If you want to hide different parts, play around with the numbers in parenthesis.

```
/* Remove Licenses from navbar. */
.navbar-nav > li:nth-child(2) {
display: none;
}
/* Remove Licenses from sidebar. */
.sidebar-menu > li:nth-child(3) {
  display: none;
}
/* Remove Licenses from dashboard. */
#webui > .row > div:nth-child(2) {
  display: none;
}
```

**Comment by ghost** [comment]
Add/Remove/Rename and maybe even reorder menu items via Admin settings would be a great feature to us as well to enhance usability.
Thx for a great software!

**Comment by webysther** [comment]
I think this can be split in two parts: only frontend and in future on backend side, now I'm using a sub_filter on nginx to support the frontend side using the @TechnologyClassroom idea, but for reduce resources usage and make more modular (feature-flag) maybe start add one module at time to make more simple and small if the change is huge. I only use the license for my homelab and disable all those things make the snipe very clean.

![image](https://github.com/snipe/snipe-it/assets/750007/07928100-e890-4c45-b895-cbeebf8e44f7)

**Comment by webysther** [comment]
I open this #13241 to request for the frontend side to track as open.

**Comment by aldoprogrammer** [comment]
@MrMontesa @TechnologyClassroom  can you tell me in which folder that the css need to modifed so it will hide some menu on the admin settings

**Comment by jordanbr20** [comment]
@aldoprogrammer The CSS file is "snipe-it\public\css\dist\all.css". You may need to sign out and sign back in. Its sad this is not a feature as I have seen SEVERAL posts about wanting this. This is the same issue as GLPI as most users want to disable built in functionality. If Snipe-IT did this, I believe a lot more users would switch over.
