### ISSUE TITLE
Add Default Location to Asset list

### ISSUE THREAD

**Issue by IDM-Helpdesk** [snipe/snipe-it#1076]
There is no way to add the asset's default location to the Asset list.  The current location value shown in the assignee's location.  This does properly represent assets that may be remote, meaning physically in a data center somewhere else in the world.

Adding a default location value will allow us to see the actual location of the system.
##

**Comment by snipe** [comment]
A default location isn't typically the real location though. Default location is really more like "Where it usually would be if it's not checked out to anyone, because if it's checked out to someone, its new location is wherever the person it's checked out to is."

**Comment by JoeFaux** [comment]
Ah… I understand now that the default location might be a storage locker where the asset is located when unused.

However, we have datacenters that contain arrays of racked machines that change owners.  The machine’s location doesn’t change as they don’t physically move to the owner’s building.  However, the system appears to report the asset is located at an incorrect building.


-   rob
