### ISSUE TITLE
Drop down list boxes not alphabetical

### ISSUE THREAD

**Issue by JoeFaux** [snipe/snipe-it#1077]
Miscellaneous drop-downs are not alphabetical, resulting in some difficulty in finding the desired value.

Create User screen
1. Manager
2. Location

Create Model screen
1. Manufacturer
2. Category

Create Category screen
1. Type

Create Asset screen
1. Location
2. Checkout to

**Comment by snipe** [comment]
Manager is listed alphabetically by last name.

**Comment by snipe** [comment]
Same thing with Checkout to

**Comment by JoeFaux** [comment]
I think it should be “last name, first name” or alphabetized by first name.

The searching feature mitigates the priority of the request.


-   rob
