### ISSUE TITLE
Feature Request: LDAP Merge - (Was [Question] LDAP with exisiting users)

### ISSUE THREAD

**Issue by thedaftbadger** [snipe/snipe-it#1079]
Hi, Just looking at the integration of LDAP in version 2 :smile: :smile: and it got me thinking....

How will it work when we have manually created and assigned assets (and accessories) to a user we now wish to have via LDAP.

So say I have manually created a user account for John Doe but now we have LDAP I want to use his LDAP account. Does the data merge, or can we just link the LDAP account to hi ssnipe-it account?

**Comment by rp-tech** [comment]
+1, let the first one who is brave enough to install in their existing environment enlighten us :D

**Comment by snipe** [comment]
Well, the logic for logging in via LDAP is still pretty basic. It's not trying to unify the accounts, and it will only try to login via LDAP if the user's notes field is "LDAP" (which would have been established during sync). So anybody who already existed during the sync will not be updated, but new people will be added and flagged as LDAP users.

            // Try to get the user from the database.
            $user = (array) DB::table('users')->where('username', Input::get('username'))->first();
            
            if ($user && strpos($user["notes"],'LDAP') !== false) {
                LOG::debug("Authenticating user against LDAP.");
                if( $this->ldap(Input::get('username'), Input::get('password')) ) {
                        LOG::debug("valid login");
                    $pass = substr(str_shuffle("0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"), 0, 10);
                    $user = Sentry::findUserByLogin( Input::get('username') );
                    $user->password = $pass;
                    $user->save();
                    $credentials = array(
                        'username' => Input::get('username'),
                        'password' => $pass,
                    );
                    Sentry::authenticate($credentials, Input::get('remember-me', 0));
                }
                else {
                    throw new Cartalyst\Sentry\Users\UserNotFoundException();
                }
            }
            /* ============================================================== */
            else {
                LOG::debug("Authenticating user against database.");
                // Try to log the user in
                Sentry::authenticate(Input::only('username', 'password'), Input::get('remember-me', 0));
            }

We'll obviously be building out this functionality over time.

**Comment by grantmoxomZoo** [comment]
Update for you guys - I have the convenient setup that all users in my organisation's ldap have an assigned email address which is the same as their snipeit login (I initially exported my ldap and imported it into snipeit). This means that in my case a merge would simply be "Check email - add all ldap fields to snipeit user). Meaning I can be a simple production test case if and when desired.

**Comment by snipe** [comment]
@grantmoxomZoo excellent, good to know!

**Comment by snipe** [comment]
@grantmoxomZoo with the dropping of email as a required field, not all users will have email addresses in Snipe-IT anymore though. We'll need to figure that out.

**Comment by thedaftbadger** [comment]
If I sync with LDAP the sync appears to work ok but fails on a lot of AD accounts as we have system service accounts that usually will be missing a first or last name in AD. 
Because these accounts don't import the overall LDAP sync doesn't complete, or import the accounts which are ok.

**Comment by snipe** [comment]
I'm not really sure what the question is here though. First name and last name are required fields in Snipe-IT, so if they're not in AD, they can't be imported.

**Comment by thedaftbadger** [comment]
I think what I mean :smile: is that when it connected to my AD via LDAP the complete sync fails if it comes across accounts without the minum criteria for Snipe-IT

**Comment by snipe** [comment]
It should only skip the entries that don't have a firstname+lastname. That's what my tests have shown to be the case.

**Comment by thedaftbadger** [comment]
hmmm seems to be the oposite on this end. The sync says it has finished but lists all the accounts it failed on..... no accounts have synced.

**Comment by snipe** [comment]
Can I see a screenshot?

**Comment by thedaftbadger** [comment]
LDAP says sync has completed ok (some failures) but nothig has synced at all.

![07-09-2015 08-57-11](https://cloud.githubusercontent.com/assets/13657363/9711856/b5aea076-553e-11e5-8cfe-cc25f2d638d6.png)

**Comment by madd15** [comment]
Make sure all attributes are in lower case in `ldap.php` config file

**Comment by thedaftbadger** [comment]
@madd15 What attributes are we talking about in the `ldap.php` file?

Do you mean all the data for `username` for example should be in lower case?

**Comment by thedaftbadger** [comment]
@madd15 The LDAP sync works ok but what seems to happen is that it doesn't create users in Snipe-IT if it comes across accounts it cant create like in the screenshot above.

**Comment by thedaftbadger** [comment]
@madd15 Just tried changing all the attributes to lower case in `ldap.php` but still the same issue. Would trying to filter out all the accounts that dont meet the basic criteria in Snipe-IT be any good?

**Comment by dc53000** [comment]
In ldap.php, you had to set these to something. The values between the double quotes need to be lower case, even if they're not lower case in your LDAP schema.

```
    'result.username' => "usernameattributeinlowercase",
    'result.last.name'  => "lastnameattributeinlowercase",
    'result.first.name' => "firstnameattributeinlowercase",
```

**Comment by thedaftbadger** [comment]
@dc53000 even with this configured the same error happens..... if you cna call it an error.
We have a lot of accounts in AD (Service accounts) which dont have the required information for them to sync with Snipe-IT (first name or last name). The connection via LDAP is ok but the sync says everything is ok but no users are created and it shows errors for all the service accounts.

This is ok but surely is should still create / sync valid LDAP users?

![error](https://cloud.githubusercontent.com/assets/13657363/9711856/b5aea076-553e-11e5-8cfe-cc25f2d638d6.png)

**Comment by mahesh2471990** [comment]
@thedaftbadger Please copy and paste code in LDAP.php file. or you can also configure in GUI also. Admin--->>Setting----->>Edit Settings---->>>(scroll down)
you can see the LDAP Settings.
You can make entry their as well i guess.

**Comment by snipe** [comment]
LDAP now syncs (versus just importing) in the upcoming v3
