### ISSUE TITLE
Wrong Button Labels

### ISSUE THREAD

**Issue by HfbK-Computerei** [snipe/snipe-it#1080]
Hey, 
i was wondering, whether we are the only ones having wrong labels on various buttons in the web-gui. Namely I see the button "create location" in the top header from where I can create Assetes, Licenses and Users. In the Users Menu it says "create location" from where to create users. Is this a bug did we just install snipe wrong?

Thanks for your help in advance.

Fred

**Comment by snipe** [comment]
Can you include screenshots please?

**Comment by snipe** [comment]
Closing due to no reply
