### ISSUE TITLE
Include editable "Asset Name" on checkout page

### ISSUE THREAD

**Issue by asmartin** [snipe/snipe-it#1081]
Thank you for creating this fantastic IT inventory tool! SnipeIT has been working well in my environment, however one thing that would be immensely helpful is the ability to set/change the "Asset Name" field on the checkout page. Simply checking out an asset to a particular person isn't ideal because a single person can have multiple very similar assets, so it is hard to distinguish between them. I've been setting the "Asset Name" field to be the hostname of the asset since that is a unique identifier. However, the hostname changes with each checkout so it would be ideal if I could just set the "Asset Name" when doing the checkout. Is this possible?

Thanks!

**Comment by rayvenshire** [comment]
+1

**Comment by asmartin** [comment]
Great, thanks for the fast turnaround on this! Does it make sense to also allow the Asset Name field to be editable on the checkin page as well, that way if you're checking an asset back in you can remove the Asset Name if it is no longer relevant (e.g for assets whose name contains a username)?
