### ISSUE TITLE
500 Error 

### ISSUE THREAD

**Issue by leemelukwork** [snipe/snipe-it#10820]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When trying to create new Accessories I get the 500 Server Error

### Reproduction steps

Tried multiple browsers/computers to check.
Tried adding an item with different name
Tried not adding notes
Tried only mandatory fields

### Expected behavior

Task to complete without error with notes added to accessory

### Snipe-IT Version

5.4.1

### Operating System

Ubuntu 20.04

### Web Server

Apache

### PHP Version

7.4.3

### Operating System

Mac OS

### Browser

Chrome

### Version

99 99.0.4844.51

### Error messages

```shell
/var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php
     * @param  array  $bindings
     * @param  \Closure  $callback
     * @return mixed
     *
     * @throws \Illuminate\Database\QueryException
     */
    protected function runQueryCallback($query, $bindings, Closure $callback)
    {
        // To execute the statement, we'll simply call the callback, which will actually
        // run the SQL against the PDO connection. Then we can calculate the time it
        // took to execute and log the query SQL, bindings and time in our memory.
        try {
            $result = $callback($query, $bindings);
        }
 
        // If an exception occurs when attempting to run a query, we'll format the error
        // message to include the bindings with SQL, which will make this exception a
        // lot more helpful to the developer instead of just the database's errors.
        catch (Exception $e) {
            throw new QueryException(
                $query, $this->prepareBindings($bindings), $e
            );
        }
 
        return $result;
    }
 
    /**
     * Log a query in the connection's query log.
     *
     * @param  string  $query
     * @param  array  $bindings
     * @param  float|null  $time
     * @return void
     */
    public function logQuery($query, $bindings, $time = null)
    {
        $this->event(new QueryExecuted($query, $bindings, $time, $this));
 
        if ($this->loggingQueries) {
Arguments
"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'notes' in 'field list' (SQL: insert into `accessories` (`name`, `category_id`, `location_id`, `min_amt`, ▶"
```

### Additional context

Upgrade.
Server is on Ubuntu 20.04.03 Desktop edition
Used install.sh in first instance, php upgrade afterwards
No manual edits

**Comment by snipe** [comment]
Whenever you see a "column not found" error, it means you need to run database migrations by running `php artisan migrate`
