### ISSUE TITLE
Custom Asset Report - "Assigned To" Generation getting broken

### ISSUE THREAD

**Issue by lokesh-sg** [snipe/snipe-it#1084]
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)

Class 'Controllers\Admin\User' not found
Open: C:\inetpub\wwwroot\snipe-it\app\controllers\admin\ReportsController.php

                        }
                    } else {
                        $row[] = '';  // Empty string if location is not set
                    }
                }
                if (e( Input::get( 'assigned_to' ) ) == '1') {
                    if ($asset->assigned_to > 0) {
                        $user  = User::find( $asset->assigned_to );
                        $row[] = $user->fullName();
                    } else {

**Comment by snipe** [comment]
What page is this on?

**Comment by snipe** [comment]
I think this has already been fixed on the develop branch
