### ISSUE TITLE
Feature Request: Global List of all items

### ISSUE THREAD

**Issue by tsilman-marquette** [snipe/snipe-it#1090]
In the reports section, place an all items in database selection. Items to be moved from Asset, to Consumable to Accessory in case of incorrect classification.
##

**Comment by snipe** [comment]
Converting one type of item to another is less trivial, since they have different attributes and business logic.

**Comment by tsilman-marquette** [comment]
I see your point and agree. In other news, I am running 3.6.2 and am happy.
