### ISSUE TITLE
LDAP and Active Directory

### ISSUE THREAD

**Issue by pfeigl** [snipe/snipe-it#1092]
Hi, 

i needed ldap option LDAP_OPT_REFERRALS set to 0 in order to be able to query our active directory. There's also quite some comments on http://php.net/manual/de/function.ldap-search.php on this topic (seems it was the same problem back with AD on WS 2003)

Regards,
Philipp

**Comment by snipe** [comment]
I just pushed out a change - can you grab the latest from develop and see if that works?
