### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by goitops** [snipe/snipe-it#1093]
Hi

Nothing happens when I try to login, after "Sing In" button, the page takes few seconds to load then again requests the username/password. No errors at all, not even in the log files. I tried to type a wrong username/password, same result. 
Debug mode is already enabled.

Thanks in advance for your assistance.

**Comment by snipe** [comment]
Can you give us a little more information? Are you running this over SSL or regular?

**Comment by snipe** [comment]
Also, what version are you running?

**Comment by goitops** [comment]
Hi, sorry for the late reply
Version is v1.2.8-26 (from app\config\version.php)
I'm not using SSL
Not sure what other information to provide, I think there is something wrong with the redirect after authentication, I think the authentication works OK (user exists in database) since there is no error
Could you please suggest some troubleshooting steps, thanks.

**Comment by snipe** [comment]
What url are you using to login?

**Comment by goitops** [comment]
I browse this one:
http://localhost:99

and it redirects to this:
http://localhost:99/auth/signin

**Comment by Elvbray** [comment]
Are you using IIS as your web server?

**Comment by goitops** [comment]
Yes, IIS version 7.5 on Windows 7 professional SP1

**Comment by ExactCare** [comment]
I am also having an issue using IIS8 and logon. I have configured and at the auth screen it tells me my password is incorrect. I changed the user password for admin in MySQL and set as MD5 and I still cannot login as well. Any suggestions?

**Comment by snipe** [comment]
@ExactCare We use bcrypt to hash passwords, so MD5 won't work. Use the forgotten password request instead to reset your password.

**Comment by ExactCare** [comment]
@snipe I wasn't able to at the time because I made an error in my mail server config. All resolved now. Thanks for the help.

**Comment by chandtech89** [comment]
I am also facing same issue. What would be the solution?
Thanks

**Comment by jdchandler** [comment]
having this issue upon fresh install using the official docker container

any insight?

I am not using any domain names, just accessing by IP

Also using NGINX with below enabled:
APP_TRUSTED_PROXIES=REMOTE_ADDR
SECURE_COOKIES=true
