### ISSUE TITLE
barcode service provider

### ISSUE THREAD

**Issue by bthurtson** [snipe/snipe-it#1094]
got this upon upgrade(most recent)
i followed the instructions and used the next commands:

php composer.phar install --no-dev 
php composer.phar dump-autoload
php artisan migrate

then receive something akin to the following:

Symfony \ Component \ Debug \ Exception \ FatalErrorException
Class 'Dinesh\Barcode\BarcodeServiceProvider' not found

any help would be appreciated

**Comment by snipe** [comment]
Can you give us more information? What specifically is in the log file? Where are you seeing this error (command line or on a page, if a page, which page, etc)?

**Comment by torriz** [comment]
He can't download/install Dinesh\Barcode, because it's taken down from github.. :-1:

**Comment by Kilrathy** [comment]
Same problem here while upgrading from 1.2.8 to 2.0.2. What can we do now?

**Comment by snipe** [comment]
Is there a question here?
