### ISSUE TITLE
Bug - artisan snipeit:backup - InvalidArgumentException

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#1095]
```batch
C:\inetpub\wwwroot\snipe-it>php artisan snipeit:backup
←[0;31m
Database backup failed. The filename, directory name, or volume label syntax is incorrect.

←[0m



  [InvalidArgumentException]
  The "C:\inetpub\wwwroot\snipe-it\app\storage/dumps/2015082023237-db.sql" directory does not exist.



snipeit:backup
````

**Comment by snipe** [comment]
Did you create a dir in storage called dumps?

**Comment by kobie-chasehansen** [comment]
Yes, it exists. the zip file was in there just not the SQL file. SQL file was also not moved into the zip.

**Comment by snipe** [comment]
Is there anything in the zip file?

**Comment by snipe** [comment]
(Running this locally, it still works for me, so I'm honestly not sure how to debug this.)

**Comment by kobie-chasehansen** [comment]
just the 3 directories

* avatars
* models
* private_uploads

**Comment by snipe** [comment]
If you run `php artisan db:backup foo.sql` what happens?

**Comment by snipe** [comment]
(Or maybe it's `php artisan db:backup filename=foo.sql`, I forget)

**Comment by kobie-chasehansen** [comment]
```batch
C:\inetpub\wwwroot\snipe-it_unstable>php artisan db:backup foo.sql
←[0;31m
Database backup failed. 'mysqldump' is not recognized as an internal or external command, operable program or batch file.

←[0m

C:\inetpub\wwwroot\snipe-it_unstable>
``````

**Comment by kobie-chasehansen** [comment]
might need to add the mysql bin to my PATH, let me try that.

**Comment by kobie-chasehansen** [comment]
well that fixes the test, but doesnt fix the actual backup.

````batch
C:\inetpub\wwwroot\snipe-it_unstable>php artisan db:backup foo.sql
←[0;32m
Database backup was successful. Saved to C:\inetpub\wwwroot\snipe-it_unstable/foo.sql
←[0m

C:\>cd \inetpub\wwwroot\snipe-it

C:\inetpub\wwwroot\snipe-it>php artisan snipeit:backup
←[0;31m
Database backup failed. The filename, directory name, or volume label syntax is incorrect.

←[0m



  [InvalidArgumentException]
  The "C:\inetpub\wwwroot\snipe-it\app\storage/dumps/2015082061354-db.sql" directory does not exist.



snipeit:backup



C:\inetpub\wwwroot\snipe-it>
````

**Comment by snipe** [comment]
Oh, there is a config file I forgot to tell you about! (Sorry!) Look in `app/config/packages/schickling` for a file called `config.example.php`. Rename that to `config.php` and try again.

**Comment by kobie-chasehansen** [comment]
found it in "app\config\packages\schickling\backup"

renamed, ran backup, same error.

**Comment by snipe** [comment]
![hi8375oxre2rcgdoe8k3_bike-block fail](https://cloud.githubusercontent.com/assets/197404/9397220/4317613a-474f-11e5-8f96-50bffbca83d2.gif)

**Comment by snipe** [comment]
Is that dumps directory writeable?

**Comment by kobie-chasehansen** [comment]
Yes, its writing the zip file into that directory.

![image](https://cloud.githubusercontent.com/assets/10247644/9397244/9dca50ce-4768-11e5-86d7-03e523d4bbe5.png)

**Comment by kobie-chasehansen** [comment]
it has to do with the full path. if i remove ````c:\inetpub\wwwroot\snipe-it```` and just leave ````\app\storage\dumps```` it works.

````
C:\inetpub\wwwroot\snipe-it_unstable>php artisan db:backup foo.sql
←[0;32m
Database backup was successful. Saved to C:\inetpub\wwwroot\snipe-it_unstable/foo.sql
←[0m
````
C:\inetpub\wwwroot\snipe-it_unstable>php artisan db:backup C:\inetpub\wwwroot\snipe-it_unstable\app\storage/dumps/2015082062145-db.sql
←[0;31m
Database backup failed. The filename, directory name, or volume label syntax is incorrect.

←[0m
````
````
C:\inetpub\wwwroot\snipe-it_unstable>php artisan db:backup \app\storage/dumps/2015082062145-db.sql
←[0;32m
Database backup was successful. Saved to C:\inetpub\wwwroot\snipe-it_unstable/\app\storage/dumps/2015082062145-db.sql
←[0m

C:\inetpub\wwwroot\snipe-it_unstable>
````

**Comment by kobie-chasehansen** [comment]
that config file doesnt seem to matter either, i changed the name back to ````config.example.php```` and the backup still ran.

**Comment by snipe** [comment]
I just pushed out a change to develop. Can you try it now? Update your config.php to the new example.

**Comment by snipe** [comment]
If you don't feel like pulling it down directly, just change the first bit in the config file to `	'path' => 'app/storage/dumps/',`

**Comment by kobie-chasehansen** [comment]
done.

Confirmed fixed!

````
C:\Users\backupadmin>cd \inetpub\wwwroot\snipe-it_unstable

C:\inetpub\wwwroot\snipe-it_unstable>php artisan snipeit:backup
←[0;32m
Database backup was successful. Saved to C:\inetpub\wwwroot\snipe-it_unstable/app/storage/dumps/2015082064135-db.sql
←[0m
Backup file created at C:\inetpub\wwwroot\snipe-it_unstable\app/storage/dumps/2015082064135-backup.zip
Removing SQL dump at app/storage/dumps/2015082064135-db.sql

C:\inetpub\wwwroot\snipe-it_unstable>
````

![image](https://cloud.githubusercontent.com/assets/10247644/9397479/29419caa-476b-11e5-8f8f-d9424898b0d5.png)

**Comment by snipe** [comment]
Sweet! Thanks for the debugging help!

![dancing-man](https://cloud.githubusercontent.com/assets/197404/9397498/24005d9e-4752-11e5-9710-f9272342f334.gif)

**Comment by kobie-chasehansen** [comment]
no problem, glad i could help!

**Comment by snipe** [comment]
FYI, docs on this feature here now: http://docs.snipeitapp.com/manual/backups.html
