### ISSUE TITLE
Feature Request: Store Passwords

### ISSUE THREAD

**Issue by firozhaneef** [snipe/snipe-it#1096]
Hi,

I think, it would be more useful, if you can integrate a feature with SNIPE-IT,which can store hashed passwords of PC's and servers.

Firoz

**Comment by snipe** [comment]
This has been discussed before, and at present, that's not something we're entertaining at this time. Secure password storage is non-trivial, and it's not really what Snipe-IT does. There are other apps and services that handle this better than we ever could.
