### ISSUE TITLE
Additional User Permissions

### ISSUE THREAD

**Issue by seanism** [snipe/snipe-it#1097]
I'd love to be able to grant our HR team access to SnipeIT with the ability to view the assets and accessories for the employees but not be able to edit anything.  I looked at the reporting permission but that doesn't show accessories.

So to summarize ability to search employees and view what an admin can view without the ability to change anything and see the serial numbers of the software.

This would help with off boarding employees so HR knows what to collect.
##

**Comment by snipe** [comment]
That's a great idea, @seanism.

**Comment by simsokleang** [comment]
Oh, okay.
I just realize it :)
Thanks for your information.

**Comment by MohammedFota** [comment]
Hi Snipe, 
this feature is really interesting, so does the Permissions list in the documentation:
http://docs.snipeitapp.com/manual/user-management/index.html
Thanks with best regards
