### ISSUE TITLE
i have installed snipe-it version 1.2.5 now i want to upgrade to snipe-it v2

### ISSUE THREAD

**Issue by umerafridi** [snipe/snipe-it#1100]
Dear All,

i want to upgrade the  snipt-it to v2 .which have recently released pl help how i upgrade to V2

**Comment by snipe** [comment]
v2 isn't released yet. We're still in pre-release status

**Comment by umerafridi** [comment]
But i received email from support@snipeitapp.com that Snipe-IT v2.0 Release

**Comment by snipe** [comment]
Yes, it's a release candidate, which means we need the community to test it out before we can release it.

**Comment by umerafridi** [comment]
So when you are plan to release the V2

**Comment by snipe** [comment]
@umerafridi probably within a week or so. We'll have upgrade instructions included with the release once it's out. 

(You're welcome to try upgrading it now, it's just that it may still have a few bugs, so we don't recommend it for production data unless you're brave.)

**Comment by umerafridi** [comment]
i want to upgrading please guide me in .how i upgrade this
