### ISSUE TITLE
LDAP Imported user error (Trying to get property of non-object)

### ISSUE THREAD

**Issue by tcresposhiver** [snipe/snipe-it#1101]
Since there was no location imported. Receiving error upon clicking the name after ldap Import. 

Image of cached view : 
![cached view](https://cloud.githubusercontent.com/assets/13354402/9402461/c2021e7a-47ab-11e5-9181-97ca280bf055.png)

Workaround : 
Click edit on affected user and hit save.

**Comment by aalaily** [comment]
This may be time consuming to do if you have hundreds or thousands of users.  A more effective solution in this case would be to add a location to the system that has an "id" value of 1.  In a typical scenario this would represent the first location that was added to the system.  At this point, the LDAP plugin adds "1" to the location ID of the person that was created.  If for whatever reason you don't have a location with id=1 in your installation (I can see this happening if you add a first location and then delete it) then the code could be enhanced to select all locations and set the user as having the first location in the selection result.

This is a possible enhancement.

**Comment by snipe** [comment]
This has been merged into develop, thanks @aalaily. I might still want to add the ability to generate a location from the optional location field - and we should write some code to prevent that page from bombing out if there is no location provided, but this is a good start.

Also, quick note, @aalaily - if you use a commit message like "Fixes #1105 - Remove hardcoded location in favour of a selection dropdown", it will automatically close the ticket once your PR has been merged :)

**Comment by snipe** [comment]
![pumpkin-dance](https://cloud.githubusercontent.com/assets/197404/9418757/2aa5869c-480b-11e5-94db-24318014568f.gif)

**Comment by aalaily** [comment]
*I might still want to add the ability to generate a location from the optional location field*
That would make things a lot easier.

@snipe: will do about the commit message.

**Comment by snipe** [comment]
No problem, thank you for all your help! (And the commit message thing isn't required by any means, just something I wasn't sure if you knew. You can see the full language that will auto-close an issue here if you're interested: https://github.com/blog/1386-closing-issues-via-commit-messages )

**Comment by aalaily** [comment]
@snipe I didn't know about the commit message auto-closing an issue, so I appreciate the pointer (and the link).  Very helpful.
