### ISSUE TITLE
(2.0RC) Default currency - when editing always $

### ISSUE THREAD

**Issue by Gehirnfussel** [snipe/snipe-it#1102]
Hi,
I just tried out the RC for 2.0 and noticed a small bug.
After setting the default currency to € and editing again, the currency is automaticly back to $ (ignoring that I set it to €) - so I need to change it manually to € every time I change the settings.

Still <3 Snipe-It :+1:

**Comment by snipe** [comment]
This is in the main Settings panel?

**Comment by Gehirnfussel** [comment]
Yes. (public/admin/settings/app)

**Comment by snipe** [comment]
Can you tell me if changing your language file in `app/config/app.php` to another language (switching between `en` and `en-GB` for example) changes anything?

**Comment by snipe** [comment]
(I'm curious to see if it's picking up the default config in the language file and overriding it that way, or if something else is amiss.)

**Comment by Gehirnfussel** [comment]
I just noticed that this bug only happens when € was set before. The other currencies stay in place (tried 4 others) o_O

(also changed the language, but don't think it did something here)
