### ISSUE TITLE
MAC Addresses not Showing When Editing/Creating Assets

### ISSUE THREAD

**Issue by DWSR** [snipe/snipe-it#1106]
I'm not seeing a place to add a MAC address when editing or creating assets. Where should it be?

**Comment by kobie-chasehansen** [comment]
need to enable the field for that asset model.

Click on Admin > Asset Models > select asset you want to enable for

![image](https://cloud.githubusercontent.com/assets/10247644/9416353/260b00aa-4813-11e5-91e9-9d6178841c85.png)

**Comment by DWSR** [comment]
I did. I am still not seeing a field for this.

**Comment by kobie-chasehansen** [comment]
Unable to duplicate in 2.0 RC both when trying to create a new access and editing an existing asset... the field shows up both times.

Do you have the ability to deploy a second possibly unstable SnipeIT site running 2.0 RC code to test against your database?

**Comment by DWSR** [comment]
I can just take a database snapshot and just upgrade to the latest version. will report back.

**Comment by DWSR** [comment]
Using the 2.0 RC code, did a git reset --hard against the tag and cleared out the listed folders in http://docs.snipeitapp.com/upgrading.html . I'm seeing the new Consumables section, but still no MAC field.
