### ISSUE TITLE
Feature Request - disable asset name field/display within system [$25]

### ISSUE THREAD

**Issue by hansenc0705** [snipe/snipe-it#1107]
So far we haven't found a use for the Asset Name field but I'm noticing my desktop group is entering things into it just because it's an empty field they feel the need to fill it with the employee's name or a desk location but none of it's consistent.

Any chance this could be disabled completely?

If this is a crazy request or a ton of work then I guess it's not a big deal. Just a nice to have.
##

**Comment by mtucker6784** [comment]
@kobie-chasehansen , so you're thinkin' something like an option under "settings" to disable / hide the asset name field when entering / updating an asset item?

**Comment by snipe** [comment]
@mtucker6784 there is already a DB setting for that. We removed it, since you can optionally show/hide columns now. I guess we could put it back, although this is a pretty fringe case.

**Comment by mtucker6784** [comment]
Gotcha, I can see what he's saying, I've had the same issue. With show/hide columns, that wouldn't remove the field "Asset Name" when in the create/edit form, right? (so one less field for peeps to worry about putting data in.)

**Comment by uberbrady** [comment]
Hey everyone - I think with the Custom fields thing, we could turn Asset Name into an optional field that could be disabled along with any other custom fields. That could potentially solve your problem, right?

There's a little bit of a novel's worth of discussion going on at: #98  - but you can see my thinking there.

**Comment by Wouter0100** [comment]
Would still love to see things implemented.
