### ISSUE TITLE
If the Asset Name is too long, labels will only generate the QR code.

### ISSUE THREAD

**Issue by IDM-Helpdesk** [snipe/snipe-it#1108]
For example, when printing labels, the Asset Name "Collaboration Coffee Machine" will only produce a QR code.  The asset name, asset number, and serial number are missing.  However, "CollaborationCoffee Machine" will print the QR code, asset name,  asset number, and serial number.  Note the missing space.

The system should either:
Restrict the length of the Asset Name during entry to allow for the labels to be printed.
or 
Truncate the length of the name to allow for the label to be printed (I like this one the best and think it would have the least impact to customers with existing names.)

**Comment by snipe** [comment]
Can you show me a screenshot of what you're seeing?

**Comment by JoeFaux** [comment]
![image](https://cloud.githubusercontent.com/assets/13545400/9481031/dc141410-4b3b-11e5-812f-5248547ddc2a.png)

I renamed one of our assets from "Backup Plus" to "Backup Plus Junk text to demonstrate Git issue 1108" for demonstration purposes.  Once the title becomes too long, the entire block of text is dropped, resulting in only the QR code.

**Comment by snipe** [comment]
Can you confirm if this is happening in v3?

**Comment by IDM-Helpdesk** [comment]
I no longer have a separate snipe-it environment to test beta releases.  It will take a few days, but I’ll see if I can set one up.

**Comment by copeprdragon** [comment]
Hi, I can confirm this is happening in (v2.1.0-55)

**Comment by snipe** [comment]
@copeprdragon this won't be fixed for v2.1.
