### ISSUE TITLE
Not able to migrate

### ISSUE THREAD

**Issue by ashokmhrj** [snipe/snipe-it#1113]
Hello, I am not able do data migration. It gives me error like 'snipeit-laravel.users table does not exists'.

**Comment by madd15** [comment]
@ashokmhrj is this a new install? have you got your DB set in `app\config\production\database.php` ?

**Comment by ashokmhrj** [comment]
Yes, it is a new install and I had set everything. I have attached screenshot. Please have a look.
![capture](https://cloud.githubusercontent.com/assets/8375784/9457989/baa75f36-4b08-11e5-9b1c-8bc1be6bd510.PNG)

**Comment by snipe** [comment]
Did you run the `php artisan app:install` to start with?

**Comment by ashokmhrj** [comment]
Thanks alot. I was missing that one. Now its working.

**Comment by snipe** [comment]
Glad you got it sorted
