### ISSUE TITLE
ldap.blade.php crashing after adding "add a drop down of locations" code

### ISSUE THREAD

**Issue by lokesh-sg** [snipe/snipe-it#1114]
After adding the following code into ldap.blade.php getting the error  ErrorException (E_ERROR)

Undefined variable: location_list (View: C:\inetpub\wwwroot\snipe-it\app\views\backend\users\ldap.blade.php) 

+        <div class="form-group {{ $errors->has('location_id') ? 'has-error' : '' }}">
+                <label class="col-md-3 control-label" for="location_id">@lang('admin/users/table.location')
+                    </label>
+                <div class="col-md-7">
+                    {{ Form::select('location_id', $location_list, array('class'=>'select2', 'style'=>'width:350px')) }}
+                    {{ $errors->first('location_id', '<br><span class="alert-msg">:message</span>') }}
+                </div>
+            </div>
+        

and 

+        
+

**Comment by aalaily** [comment]
> After adding the following code into ldap.blade.php ...

I wonder if you pulled the code for the Controller as well.  That variable is set in the User controller class.  I looked at the develop branch and the code is there.

**Comment by snipe** [comment]
Yeah, I also cannot reproduce this locally.

**Comment by aalaily** [comment]
The only way that I'm able to reproduce this particular error is to omit the new code from the UserController class.

@lokesh-sg, if you are able to look at the code, take a look at "app/controllers/admin/UsersController.php" and confirm that the following lines exists in getLDAP():

`// Show the page
        return View::make('backend/users/ldap', compact('groups', 'selectedGroups', 'permissions', 'selectedPermissions'))
                        ->with('location_list', $location_list);`

**Comment by lokesh-sg** [comment]
Awesome that worked for me. I have missed to add in "app/controllers/admin/UsersController.php". Thanks guys.

**Comment by snipe** [comment]
I'm glad you got it sorted. In general, you should probably try to keep up with the official releases (or at least branches) so you don't have to piecemeal patches. That tends to be fraught with peril.
