### ISSUE TITLE
LDAP authintication not working 6.0.1

### ISSUE THREAD

**Issue by benseroussi** [snipe/snipe-it#11185]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Since 6.0.1 LDAP authinticaion isn;t working. It worked fine on 5.4.
Everything is set correctly, "Test LDAP Synchronization" is working correctly. Synchronozing users from AD is also working.
The users are unable to log in, Test LDAP login fails with the error: "ldap_search(): Search: Bad search filter".
If I remove the "Active Directory domain" value I get a different error "Login Failed. bense did not successfully bind to LDAP".
It only happens for new users, users that logged before the upgrade works.

Debug mode is on, but I can't find with what user credentails it's trying to log in.

Edit: apperantly the "ldap_search(): Search: Bad search filter" error only happens when the credentials are correct, when I change the user name or the password to something that shouldn't work I get the "Login Failed. bense did not successfully bind to LDAP".

### Reproduction steps

1. LDAP on 5.4
2. New server with 6.0.1
3. Restore 5.4 backup
4. Set DN pasword again and test LDAP
5. New LDAP user fails to log in

### Expected behavior

LDAP login works

### Snipe-IT Version

6.0.1

### Operating System

Ubuntu 22

### Web Server

Apache

### PHP Version

8.0.19

**Comment by benseroussi** [comment]
Apparently it was the parenthesis in the start and the end of the filter.

**Comment by uberbrady** [comment]
Thanks for following up!

**Comment by snipe** [comment]
Yes, thanks for the follow up! That's always very helpful to us and to other users!
