### ISSUE TITLE
Feature Request: Azure Active Directory Integration

### ISSUE THREAD

**Issue by DWSR** [snipe/snipe-it#1118]
Would love to see this. You would be able to use it for either the hosted or on-prem versions.
##

**Comment by snipe** [comment]
I don't know anything about Azure Active Directory, but wouldn't it work the same as regular active directory?

**Comment by DWSR** [comment]
The AAD integration is very similar, but allows for a couple of things over on-prem AD integration.
1) SSO with your hosted SnipeIT instances, or with SnipeIT instances that are self-hosted off-prem (my current situation)
2) SSO for small companies that are Office 365 customers, but don't have AD deployed.
3) Allow for MFA through AAD

**Comment by RehanSaeed** [comment]
+1

**Comment by theonewolf** [comment]
+1

**Comment by karthikg** [comment]
+1 on this feature.

**Comment by Senilex** [comment]
+1 on this feature request.
Many thanks for your hard work.

**Comment by evando646** [comment]
+1

**Comment by niklasskoldmark** [comment]
+1

**Comment by gregorythomason** [comment]
+1

**Comment by theonewolf** [comment]
Still relevant.

**Comment by jarrod-marshall** [comment]
I would love to see this as well as syncing users.

**Comment by gregorythomason** [comment]
Still very much interested!  Thanks

Sent Using Outlook<https://aka.ms/qtex0l> for iOS

________________________________

**Comment by Janix1** [comment]
This feature would be great! Thanks

**Comment by afield1235** [comment]
There is not a big difference between Azure AD and most other SAML 2.0 SSO provides like OKTA, Onelogin, Ping Identity etc. They are a different protocol than Active Directory LDAP. If you can support one, you should be able to theoretically support them all.

**Comment by susumuf** [comment]
oauth2 is better.

**Comment by gregorythomason** [comment]
Hi, based on this is the 3rd or 4th stale? message and nothing has been done about it, just go ahead and dump it.

Far less frustrating than being reminded that this hasn’t been realised every 6 months or so..

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by snipe** [comment]
@gregorythomason you can always unsubscribe from the thread, you know...

**Comment by snipe** [comment]
(Additionally, this issue has the labels that should have prevented it from being closed. I don't know why stalebot isn't respecting the "feature request" and "ready for dev" labels, which should tell it not to auto-close.)

**Comment by afield1235** [comment]
Keep it. SAML SSO or OAUTH.

**Comment by JDangles** [comment]
Very important.  We authenticate against Azure AD and could really benefit from this feature.

**Comment by nebi52** [comment]
+1

**Comment by Lamera** [comment]
I would also be happy about this feature. Is something going on?

**Comment by dszp** [comment]
It looks like this is a Duplicate of #542 in that if SAML 2.0 is implemented, it will allow AzureAD SSO just as easily as Okta/OneLogin/G Suite, since it's an SSO standard. And someone there has a working demo as of a week ago.

**Comment by karolyczovek** [comment]
bump. still relevant.

**Comment by niklasskoldmark** [comment]
Is there any news on this?

**Comment by arunas-devoro** [comment]
very very relevant, thanks!

**Comment by NigelColtellaIT** [comment]
Saw OAUTH in settings and assumed this would be there... surprised it's not. I agree to above comments. Very relevant and more so now with the risks around cyber security. Integrating auth with our existing provider allows us to control who can access the app depending on whether their device is marked as compliant or not.

**Comment by adagioajanes** [comment]
Still very relevant. We are currently in the process of trying to shift to a fully Azure AD environment. This would prevent that unless I used Azure ADDS, which carries unnecessary additional support burden.

**Comment by KevinBrownRDC** [comment]
SSO through AAD with MFA very important to our deployment.

**Comment by dalonfoley** [comment]
Need this SAML integration for Azure AD

**Comment by adagioajanes** [comment]
This has now been implemented into 5.0

**Comment by snipe** [comment]
SAML integration already works with Azure AD. https://snipe-it.readme.io/docs/saml#azure-ad-as-saml-provider

**Comment by alainseys** [comment]
+1
👍🏻

**Comment by HACS-bank** [comment]
I'm using the hosted SaaS and have enabled Azure AD SSO; I don't see an option for provisioning users from Azure AD or using Azure AD groups to assign rights.

**Comment by snipe** [comment]
Hi @HACS-bank - we don’t currently allow provisioning via SAML. The workflow we see work well for customers and users is to use SAML for login, and LDAP sync for provisioning

**Comment by adagioajanes** [comment]
@snipe As the world continues to migrate to a cloud first model, some companies are starting up without having any traditional Active Directory or LDAP in place. Instead, they are opting for cloud only strategies, like managing all of their users in Azure AD. When I am deploying new applications, I try to utilize the Azure AD user synchronization or SCIM provisioning methods, rather than continuing to rely on LDAP, which is not available without additional cost in the Azure AD model.

In my case, because this is not the only application that will continue to rely on LDAP, I have an AD server deployed in Azure that Snipe IT can connect to for the user sync. But, ideally, I would like to continue to move the applications I utilize towards an SCIM or user provisioning model. https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/sync-scim

If this was the only application to rely on LDAP, I would be hard pressed to justify the cost of an LDAP/AD server, just so Snipe IT can sync users. But, in my case, I am lucky to not have to make that decision right now. :)

Just some food for thought. :)

<blockquote><img src="https://docs.microsoft.com/en-us/media/logos/logo-ms-social.png" width="48" align="right"><div><strong><a href="https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/sync-scim">SCIM synchronization with Azure Active Directory</a></strong></div><div>Architectural guidance on achieving SCIM synchronization with Azure Active Directory.</div></blockquote>

**Comment by snipe** [comment]
@adagioajanes It’s not out of the question (tho probably belongs in it’s own discussion or feature request). We’d probably need that to be a setting though, as I have seen scenarios where you wouldn’t want to auto-provision users on login (after successful auth via SSO.)

**Comment by adagioajanes** [comment]
@snipe I agree. Provisioning via SAML (at least in my opinion) was always the hacky work around to deal with user provisioning. It can work, but it doesn't manage the full lifecycle of the user from creation to deletion (or just disabled depending on the app).

SCIM would be the best way to handle it for Azure AD. But you are right, SCIM doesn't fall into this current discussion thread.

**Comment by HACS-bank** [comment]
I work in my University IT department and am responsible for IDAM strategy.
We have a dozen or more SaaS applications provisioning from Azure, and I
would like to help specify the interface to Azure if this goes ahead.

We also have a software engineer who does all our IDAM integration works
and might be able to assist you with technical details.

Best
Jem Taylor, University of the Highlands and Islands

**Comment by adagioajanes** [comment]
I have submitted a new feature request for SCIM user provisioning. Let's move the discussion about Azure AD provisioning over there. :)

#10412
