### ISSUE TITLE
Feature Request: Publisher for Licenses

### ISSUE THREAD

**Issue by DWSR** [snipe/snipe-it#1119]
I would love to have a Publisher Field for Licenses, so that we can track how many Adobe, Microsoft, etc. licenses that we have.
##

**Comment by snipe** [comment]
I think most people use Supplier for that. Do you need a separate field?

**Comment by DWSR** [comment]
I work for a charity, so we purchase licenses through a reseller (as I'm sure many people do) that are governed by an agreement with the publisher. A publisher field would be an additional field to allow us to create compliance reports that govern our software licensing agreements. We already use the supplier field to track which reseller (and thus which order number) we are ordering our licenses from.

**Comment by kobie-chasehansen** [comment]
instead of a new publisher field maybe a manufacturers field and pull from what's already setup and used by assets?
