### ISSUE TITLE
403 - Forbidden

### ISSUE THREAD

**Issue by fpinsurance** [snipe/snipe-it#1120]
I followed the installation guide all the way through, and when I attempt to access the site (either from localhost or another workstation), I get a 403 - Forbidden error.

If I manually go to localhost/snipe/public/index.php I get a 404.3 - Not Found

I'm unsure of where to go to next here.  Can anybody help out with this?

Running on Server 2012 using IIS 8

**Comment by snipe** [comment]
Your document root needs to be the `public` directory, per the installation docs. http://docs.snipeitapp.com/installation/server/windows.html

**Comment by fpinsurance** [comment]
The physical path is set to public.  Here's a screenshot of the site settings in IIS manager:

![settings](https://cloud.githubusercontent.com/assets/13983598/9502125/9aa76de0-4bec-11e5-8998-cabea42759b4.JPG)

**Comment by snipe** [comment]
Can you show me the contents of `C:\inetpub\wwwroot\snipe\public`?

**Comment by fpinsurance** [comment]
Here's a snip of the directory contents:

![capture](https://cloud.githubusercontent.com/assets/13983598/9503208/cfbe6d84-4bf2-11e5-9bbc-a6ed0462e610.JPG)

**Comment by snipe** [comment]
Maybe try restarting the web server, or check file owner permissions? If your document root is correct, it should just work.

**Comment by fpinsurance** [comment]
I've restarted the server, the site, and IIS multiple times.  I assume it should just work, but it just gives me the forbidden error message.  If I just type in localhost, it gives me the default IIS page.

**Comment by snipe** [comment]
I don't think `localhost` looking in the right folder. What about when you go to assets.fpinsuance.com (which is what's set as the binding)?

**Comment by snipe** [comment]
assets.fpinsurance.com may not resolve if you haven't set up DNS. But either way, localhost is looking somewhere else entirely, IMHO

**Comment by fpinsurance** [comment]
I have a DNS entry set up to point.  Pinging assets.fpinsurance.com results in the correct IP address.  Using the address, I get the forbidden error as seen below:

![capture](https://cloud.githubusercontent.com/assets/13983598/9503952/23e17830-4bf7-11e5-80ae-39de0c0f47f4.JPG)

**Comment by snipe** [comment]
I dunno - IIS is not really my speciality. Perhaps @madd15 can advise.

**Comment by kobie-chasehansen** [comment]
bindings look interesting.

can you stop the default site and see what you get?

also change your binding to look like this, you can leave out the https since you aren't using but if i had to guess your bindings will have a http and in hostname it will be a * or empty and then below that you will have another http with the name.

![image](https://cloud.githubusercontent.com/assets/10247644/9504199/46ac08c8-4c09-11e5-8175-ce2d51646b26.png)

**Comment by ddreier** [comment]
What do the permissions for the public folder look like? As a troubleshooting measure, you might try giving Everyone read and write permissions on the public and or whole Snipe-IT directory.

Here's what the permissions on my public folder look like:
![image](https://cloud.githubusercontent.com/assets/82290/9504314/8d672732-4c01-11e5-927c-d7ad25f63c9c.png)

**Comment by fpinsurance** [comment]
Kobie,

The bindings look about the same, I just don't have a binding for https:

![capture](https://cloud.githubusercontent.com/assets/13983598/9505081/737baa9a-4bfd-11e5-87ad-72b4052bd7a5.JPG)

**Comment by fpinsurance** [comment]
ddreier,

I tried setting Everyone with permission, but still getting the 403 - Forbidden.

**Comment by fpinsurance** [comment]
I completely removed the site and re-added it (running through setup again) and it's still giving me the Forbidden message.

**Comment by ddreier** [comment]
Did you set index.php to be the first default document for the site?

IIRC, you'll get a 403 if PHP isn't working/configured correctly as well. To test that, I'd create a new site and point it to a folder that has a something.php file in it that contains "<?php phpinfo(); ?>" (I think, my PHP is a little rusty). If browsing to that page doesn't work, then PHP isn't working.

**Comment by fpinsurance** [comment]
ddreir, I just followed the setup guide.  There wasn't anything mentioned about needing to set up index.php that I noticed.

**Comment by ddreier** [comment]
Yeah, sorry, I checked and I didn't do that myself. Sometimes it helps, sometimes it's not necessary.

**Comment by fpinsurance** [comment]
I moved it up, now I get the following error:

![capture](https://cloud.githubusercontent.com/assets/13983598/9505728/4bf8dc5a-4c01-11e5-8012-50dfac1a555f.JPG)

**Comment by snipe** [comment]
That's better. That's a 500 error, and it's a Laravel 500 error, which means it's actually processing the php files. Set debug to true as specified here: http://docs.snipeitapp.com/getting-help.html and tell us what the verbose error message is.

**Comment by fpinsurance** [comment]
Here's a snip of the top.  What do we need exactly?

**Comment by fpinsurance** [comment]
![capture](https://cloud.githubusercontent.com/assets/13983598/9505829/d934f586-4c01-11e5-8ae9-e81cb85e7c57.JPG)

**Comment by snipe** [comment]
Looks like a key wasn't included. 
http://docs.snipeitapp.com/common-issues.html#error-message-mcrypt_encrypt-size-of-key-is-too-large-for-this-algorithm

**Comment by fpinsurance** [comment]
The copy wasn't right, ended up missing a couple of letters from it :/

Now I get a 404 for /auth/signin

**Comment by snipe** [comment]
http://docs.snipeitapp.com/common-issues.html#the-requested-url-authsignin-was-not-found-on-this-server

**Comment by fpinsurance** [comment]
I've got URL Rewrite installed with rules imported.  I removed all rules and re-imported, but still no change.  Any ideas?

![capture](https://cloud.githubusercontent.com/assets/13983598/9506220/f0d456d0-4c03-11e5-99da-0341a9347169.JPG)

**Comment by fpinsurance** [comment]
I'm not sure if this has anything to do with the errors or not:

![capture](https://cloud.githubusercontent.com/assets/13983598/9506577/299d104a-4c06-11e5-854c-e145c9315a99.JPG)

**Comment by snipe** [comment]
It's a different error, but you're not going to be able to login with that one either. That means your database credentials aren't correct.

**Comment by fpinsurance** [comment]
It asks for first name, last name, email, password.  I didn't set that up anywhere else.  Where would it be pulling those credentials from?

**Comment by snipe** [comment]
http://docs.snipeitapp.com/installation/configuration.html#edit-database-settings

**Comment by fpinsurance** [comment]
That was done correctly.  When running php artisan app:install --env=production it asks for First Name, Last Name, Email Address, and Password, but no username.

**Comment by snipe** [comment]
Well, I mean that doesn't really matter, since it can't connect to your database. But it looks to me like you have an older version of Snipe-IT. 2.0 was released last night, which is where we switched from email addresses to usernames.

**Comment by fpinsurance** [comment]
I went ahead and downloaded 2.0, but I'm still stuck at the access denied when trying to run php artisan migrate.  I followed the instructions exactly when setting up the database.php file as seen below.

I'm also now stuck with a page can't be displayed after updating to 2.0

![capture](https://cloud.githubusercontent.com/assets/13983598/9507730/6062b600-4c0d-11e5-8dea-c17843c6ba08.JPG)

**Comment by madd15** [comment]
you have setup mysql and the DB I assume?

**Comment by fpinsurance** [comment]
If that's in the documentation during setup I did.  I don't recall doing it though.

**Comment by snipe** [comment]
It's in there, but if you don't remember it, chances are you never set it up. Snipe-IT doesn't do that for you, you have to set it up on your own and then use the DB access info you used to create your database in the database config file

**Comment by fpinsurance** [comment]
That shouldn't be an issue, but I'm back to "Page cannot be displayed" after putting all of the 2.0 files in and running the necessary commands using composer.

**Comment by fpinsurance** [comment]
Will this affect snipe-it?  I don't see this one in common issues.  I've deleted the compiled.php and dev directory and re-ran composer update.

![capture](https://cloud.githubusercontent.com/assets/13983598/9523224/28697372-4c96-11e5-9594-5b75b048d882.JPG)

**Comment by fpinsurance** [comment]
Disregard.  Ran through entire setup after wiping the old data, didn't get the error this time.
