### ISSUE TITLE
Email Notifications

### ISSUE THREAD

**Issue by sysnoo** [snipe/snipe-it#1124]
Hi,
Very nice tool, thanks for all.
Concerning the email notifications
For Checkout, users receive acceptance message.
Is it possible to have an email confirmation for Checkin?
I have v1.2.11-1-ga2bd425  installed in Prod.

Again thank for your useful and well conceived tool.

**Comment by madd15** [comment]
in the latest version `v2.0-RC-1-11-gda6770c ` you can send checkin notifications based on categories

**Comment by sysnoo** [comment]
Thanks for you reply.
What categories trigger the notification.
Is fine to go on prod with v2.0-RC-1-11-gda6770c ?

**Comment by madd15** [comment]
You can set whatever categories you want to trigger the notification.
![checkinnot](https://cloud.githubusercontent.com/assets/3274937/9511513/a6203178-4cb6-11e5-9b47-4fa6f5c73a1a.png)

V2.0 was released yesterday and is safe to deploy to production.

**Comment by sysnoo** [comment]
Great.
Any guide for upgrade.
I feel anxious since it is not like any other web application or CMS.
Symphony, composer ... It like minefield for me.

**Comment by madd15** [comment]
http://docs.snipeitapp.com/upgrading.html

**Comment by sysnoo** [comment]
Thanks, I will upgrade this weekend.
I have some feature request :

**Comment by sysnoo** [comment]
Oupps ...
-  Be able to add custom field for Asset (Ex. EMEI Cell, SN, Cell #...)
- Minimalist ticket system or incident records by adding notes for assets
- Print Dsiclaimer to sign PDF
...
Where I can propose them?

**Comment by madd15** [comment]
If you make another issue ticket for each of your feature requests then they can be looked at and discussed

**Comment by leobg** [comment]
When somebody requests a requestable asset - isn't this supposed to trigger email to the user who has the device in their possession or to the administrator(s) if the asset is not checked out? I see the request in the log, but no email gets triggered?
