### ISSUE TITLE
Page can't be displayed

### ISSUE THREAD

**Issue by fpinsurance** [snipe/snipe-it#1125]
I wiped the server and started over.  All dependencies went through with no errors this time.

The new issue is that when I try to access the site, it just says "Unable to connect to server" when I have the Snipe-It site running.  If I switch back to Default, I get the standard IIS page and I am able to telnet directly to port 80.

I uninstalled and reinstalled URL Rewrite, removed all imported rules and reimported them.  Still the same issue.

I ran IISReset and have rebooted the server as well.

Any ideas?

**Comment by fpinsurance** [comment]
Updated title since I entered it incorrectly.  I just get "Page can't be displayed".  All else holds true above.

**Comment by ddreier** [comment]
If you're getting "Page can't be displayed"/"Unable to connect to server" from your web browser, it sounds like either a firewall, DNS, or site binding issue.

**Comment by fpinsurance** [comment]
It's not. I can telnet to the IP and port.  If I switch off Snipe and go back to default website, it loads the IIS welcome page.

I can't even load snipe on the server it's hosted on.  If I stop the Snipe application pool, I get "Service Unavailable", and then back to Page Can't be Displayed once it's turned back on.

**Comment by ddreier** [comment]
So, what happens if you emulate an HTTP request with telnet? What do the IIS logs say? Is there anything in the Application Event Log?

**Comment by fpinsurance** [comment]
I'm going to delete the VM and just start from scratch.  We'll see how that goes.

**Comment by fpinsurance** [comment]
Ran through everything on a clean server.  All installs went fine, but I'm still getting the same error.

With the imported rules, I get a Page can't be displayed.  If I disable the rules, it comes up with the 404 error:

![capture](https://cloud.githubusercontent.com/assets/13983598/9533665/c7fb0344-4cd0-11e5-9438-3d86b2d1e7a2.JPG)

It looks like it's trying to redirect to auth/signin.  

Any ideas from anybody?

**Comment by fpinsurance** [comment]
It's the same if I navigate by name as well:

![capture](https://cloud.githubusercontent.com/assets/13983598/9533704/17d5c034-4cd1-11e5-9923-48b4bbe12cd1.JPG)

**Comment by ddreier** [comment]
That's what I get when I forgot to import the .htaccess into URL Rewrite. If you're being redirected, PHP is working and the application is loading (methinks).

**Comment by fpinsurance** [comment]
If I turn the rules back on, it gives me this:

![capture](https://cloud.githubusercontent.com/assets/13983598/9534153/b29ad04e-4cd3-11e5-8d11-9de865abd067.JPG)

**Comment by ddreier** [comment]
Sorry, there just isn't anything I can do without more information.

There were no errors when you ran all of the setup commands? What happens if you manually go to /auth/signin? What do IE's F12 tools say? What do the IIS logs say? If you enable debug mode for Snipe-IT do you get anything different? Did you try emulating an HTTP request with telnet to see the returned data from the server?

**Comment by fpinsurance** [comment]
Debug doesn't give any output.  I'm looking in the Event viewer and don't see any IIS entries under Application.  F12 tools doesn't really show much, just the code for the 404 page.

**Comment by fpinsurance** [comment]
IIS appears to be working correctly.  If I turn off the snipe-it website, and turn default back on I get the IIS page:

![capture](https://cloud.githubusercontent.com/assets/13983598/9534690/b37ae04a-4cd7-11e5-93df-da0bb96e1f24.JPG)

**Comment by fpinsurance** [comment]
Here are some of the log files directly from inetpub's log directory:

#Software: Microsoft Internet Information Services 8.5
#Version: 1.0
#Date: 2015-08-27 22:03:05
#Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) cs(Referer) sc-status sc-substatus sc-win32-status time-taken
2015-08-27 22:03:05 10.10.1.41 GET / - 80 - 10.10.24.105 Mozilla/5.0+(Windows+NT+6.1;+WOW64;+Trident/7.0;+rv:11.0)+like+Gecko - 302 0 0 296
2015-08-27 22:03:05 10.10.1.41 GET /auth/signin - 80 - 10.10.24.105 Mozilla/5.0+(Windows+NT+6.1;+WOW64;+Trident/7.0;+rv:11.0)+like+Gecko - 404 0 2 0
2015-08-27 22:04:28 10.10.1.41 GET /auth/signin - 80 - 10.10.24.105 Mozilla/5.0+(Windows+NT+6.1;+WOW64;+Trident/7.0;+rv:11.0)+like+Gecko - 404 0 2 15
2015-08-27 22:04:53 10.10.1.41 GET /auth/signin - 80 - 10.10.24.105 Mozilla/5.0+(Windows+NT+6.1;+WOW64;+Trident/7.0;+rv:11.0)+like+Gecko - 404 0 2 15
2015-08-27 22:20:00 10.10.1.41 GET / - 80 - 10.10.24.105 Mozilla/5.0+(Windows+NT+6.1;+WOW64;+Trident/7.0;+rv:11.0)+like+Gecko - 302 0 0 250
2015-08-27 22:20:00 10.10.1.41 GET /auth/signin - 80 - 10.10.24.105 Mozilla/5.0+(Windows+NT+6.1;+WOW64;+Trident/7.0;+rv:11.0)+like+Gecko - 404 0 2 0

**Comment by ddreier** [comment]
Those aren't the latest entries are they?

**Comment by fpinsurance** [comment]
The timestamps are GMT.

**Comment by ddreier** [comment]
At least it's representative of what you're seeing in the browser, though I would have expected to see a 500 code to explain the 'page cannot be displayed' message. I just looked and there is a PHP error log, and there's a link to it in the PHP Manager in IIS Manager.

Also, in PHP Manager you might make sure that all of the appropriate PHP extensions are installed. Here's what I have:
![image](https://cloud.githubusercontent.com/assets/82290/9535452/152ca24c-4ce7-11e5-956f-10072ae48a60.png)

**Comment by madd15** [comment]
@fpinsurance What is your `Physical Path` in `Basic Settings` set to?

It should be something like `C:\inetpub\wwwroot\snipeit\public`

**Comment by fpinsurance** [comment]
My physical path is C:\inetpub\wwwroot\snipe\public

**Comment by fpinsurance** [comment]
When I hit test settings, I get a green check on the top and an exclamation on the bottom.

**Comment by madd15** [comment]
could you show the rules in URL Rewrite please?

**Comment by fpinsurance** [comment]
![capture](https://cloud.githubusercontent.com/assets/13983598/9538441/bc56a4fe-4d01-11e5-8469-351f538e1a8b.PNG)

**Comment by snipe** [comment]
Try removing the first imported rule

**Comment by fpinsurance** [comment]
Removing that first line did the trick.

**Comment by snipe** [comment]
So you're all set now?

**Comment by snipe** [comment]
(That line should't have been imported in the first place - it's commented out in the htaccess file.)

**Comment by fpinsurance** [comment]
Yeah, I was able to hit it and log in.  Seems to be all happy now.

**Comment by snipe** [comment]
Great, glad you got it sorted.

**Comment by KarlThornley** [comment]
I had the same problem; I removed the first line and I'm getting a little further.  Now I get "Error in exception handler".  Any ideas?

**Comment by snipe** [comment]
need the entire error message please.

**Comment by KarlThornley** [comment]
That is the entire error message.  Where would I find a more complete error log?

**Comment by ddreier** [comment]
@KarlThornley http://snipe.github.io/snipe-it/getting-help.html

Please enable debug mode and create a new issue.
