### ISSUE TITLE
Server Error 500 When Creating New Asset Models

### ISSUE THREAD

**Issue by Liel4494** [snipe/snipe-it#11256]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I'm getting "500 | Server Error" page when trying to create new asset model.
i running the latest version v6.0.2 - build 7961 on ubuntu.

I enabled Debug mode, this is the exception:

> The /var/www/html/snipeit/bootstrap/cache directory must be present and writable. (View: /var/www/html/snipeit/resources/views/models/edit.blade.php) 

Please help me to resolve this error, thanks.

### Reproduction steps

1.Click on create new asset button

### Expected behavior

New asset page will open.

### Snipe-IT Version

6.0.2

### Operating System

ubuntu

### Web Server

Apache

### PHP Version

?

### Browser

Firefox

**Comment by snipe** [comment]
As mentioned elsewhere, if you’re getting a 500 error, we cannot help diagnose it without error logs.

**Comment by Liel4494** [comment]
I enabled Debug mode, this is the exception:

> The /var/www/html/snipeit/bootstrap/cache directory must be present and writable. (View: /var/www/html/snipeit/resources/views/models/edit.blade.php)

**Comment by snipe** [comment]
Sorta what it says on the tin then. The /var/www/html/snipeit/bootstrap/cache directory must be present and writable.

**Comment by snipe** [comment]
Closing as duplicate of #11238, #11203, #11187
