### ISSUE TITLE
Dashboard link not working

### ISSUE THREAD

**Issue by fpinsurance** [snipe/snipe-it#1126]
I hate to be a pain, but have you seen the issue where the dashboard links twice to the home page?  In my case, hovering over either dashboard or the title points to assets.fpinsurance.com/assets.fpinsurance.com.

Thanks.

**Comment by madd15** [comment]
What is set in `app/config/production/app.php` for `'url' =>`?

**Comment by fpinsurance** [comment]
/*
    |--------------------------------------------------------------------------
    | Application URL
    |--------------------------------------------------------------------------
    |
    | This URL is used by the console to properly generate URLs when using
    | the Artisan command line tool. You should set this to the root of
    | your application so that it is used when running Artisan tasks.
    |
    */

    'url' => 'assets.fpinsurance.com',

    /*

**Comment by madd15** [comment]
try setting it to `http://assets.fpinsurance.com`

**Comment by fpinsurance** [comment]
That was it.  I went ahead and donated since you guys are all over this for me.  I appreciate it!

**Comment by madd15** [comment]
Great, glad you got it sorted!
