### ISSUE TITLE
Feature Request: enable adding of multipe assets into 1 Maintenance Contract

### ISSUE THREAD

**Issue by Marc127** [snipe/snipe-it#1129]
Hi,

Is it possible to be enable multiple assets to be added into 1 Maintenance Contract under Asset Maintenances? At the moment I can only create 1 maintenance contract per asset.   My scenario would be where there are 10-100(could be a lot more) Assets that are under the same maintenance contract from the 1 supplier.

Could be as simple as adding an "Add Asset" Button to the Asset Maintenances Actions/Edit for each Maintenance Contract added?

cheers

-Marc 
##

**Comment by kongou-ae** [comment]
+1
