### ISSUE TITLE
LDAP error

### ISSUE THREAD

**Issue by fpinsurance** [snipe/snipe-it#1133]
Getting this error when trying to LDAP sync.

![capture](https://cloud.githubusercontent.com/assets/13983598/9553346/9def26e2-4d7b-11e5-8a18-693aed33f894.JPG)

**Comment by snipe** [comment]
You need to install the PHP LDAP extension

**Comment by fpinsurance** [comment]
Sweet.  It was supposed to have been saved but Notepad++ got me.  Ugh.. Thank you @snipe

**Comment by snipe** [comment]
I've updated the docs to reflect php-ldap as a requirement as well. (That was my bad for not including it.)

http://docs.snipeitapp.com/common-issues.html#call-to-undefined-function-controllersadminldap_connect
http://docs.snipeitapp.com/installation/configuration.html#optional-ldap-configuration
