### ISSUE TITLE
Feature Request - ability to remove an asset maintenance

### ISSUE THREAD

**Issue by hansenc0705** [snipe/snipe-it#1134]
Think I want to use Asset Maintenance to track hardware upgrades (like ram) we do to some of our development machines. In our case however when that asset gets checked back in the ram would come out and go back into storage and the laptop would be downgraded to our standard config.

Another thought on this would be to tie accessories maybe into asset maintenance or create a new parts section of some kind. that way we can keep track of this kind of "upgrade" inventory.
##

**Comment by kobie-chasehansen** [comment]
tagging @vsposato, think you worked on this feature originally.

**Comment by kissit** [comment]
I too would like to see this feature. We use the maintenance feature in a little different way to notate scheduled maintenance on assets in addition to maintenance contracts. For instance a quarterly patch cycle for certain servers.  Being able remove the entry after its completed would be very helpful to keep the maintenances list clean and relevant.
