### ISSUE TITLE
Upgarde to v2 Errors

### ISSUE THREAD

**Issue by sysnoo** [snipe/snipe-it#1138]
I Downloaded the link https://github.com/snipe/snipe-it/archive/v2.0.tar.gz.
I replaced the file of installed version v1.2.11-1
When I run : php composer.phar install I got this 

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for guzzle/guzzle 3.9.x-dev -> satisfiable by guzzle/guzzle[3.9.x-dev].
    - guzzle/guzzle 3.9.x-dev requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 2
    - Installation request for guzzle/guzzle dev-master -> satisfiable by guzzle/guzzle[dev-master].
    - guzzle/guzzle dev-master requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 3
    - guzzle/guzzle 3.9.x-dev requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - aws/aws-sdk-php 2.8.x-dev requires guzzle/guzzle ~3.7 -> satisfiable by guzzle/guzzle[3.9.x-dev].
    - Installation request for aws/aws-sdk-php 2.8.x-dev -> satisfiable by aws/aws-sdk-php[2.8.x-dev].

**Comment by sysnoo** [comment]
What to Now ?

 php composer.phar install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Updating erusev/parsedown dev-master (b9e5228 => fa005fd)
    The package has modified files:
    M .travis.yml
    M LICENSE.txt
    M README.md
    M composer.json
    M phpunit.xml.dist
    M test/CommonMarkTest.php
    M test/ParsedownTest.php
    M test/bootstrap.php
    M test/data/aesthetic_table.html
    M test/data/aesthetic_table.md
-10 more files modified, choose "v" to view the full list
 Discard changes [y,n,v,d,s,?]?

?????

**Comment by snipe** [comment]
It's telling you what the problem is. PHP curl, is not installed.

**Comment by sysnoo** [comment]
I figured out thanks but what to type : Y N D or S

**Comment by snipe** [comment]
http://stackoverflow.com/questions/13613619/how-to-avoid-composer-discard-changes-message

**Comment by sysnoo** [comment]
I did it by replying y for all steps.
Still confusing : discard I tought it is like ignore.
Is there a command to check that my Upgrade is clean?

**Comment by sysnoo** [comment]
I see this in the logs

production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:148

**Comment by snipe** [comment]
Are you running `php composer.phar install` with the recommended flags in the documentation? 

I need to see more of your error logs to know what's happening.

**Comment by sysnoo** [comment]
Hi,
I Have this recurrent error in the log :

[2015-09-01 22:55:24] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.                                                                    php:148
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1054): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1022): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#9 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#11 /var/www/html/public/index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []

**Comment by snipe** [comment]
Are you running `php composer.phar` install with the recommended flags in the documentation?

That stack trace doesn't really give me very much info. Can you tell me what your DocumentRoot is set to?

**Comment by snipe** [comment]
Also try running `php artisan dump-autoload`

**Comment by sysnoo** [comment]
DocumentRoot /var/www/html/public
All I did after uploading v2 files was the 3 steps :
php composer.phar install
php composer.phar dump-autoload
php artisan migrate

**Comment by sysnoo** [comment]
is it Ok to redo : php composer.phar install --no-dev --prefer-source with my current running installation?

**Comment by snipe** [comment]
Yep

**Comment by snipe** [comment]
Also add `--no-interaction`

**Comment by sysnoo** [comment]
Thanks. Done
I suppose no need to run again :
php composer.phar dump-autoload
php artisan migrate

**Comment by snipe** [comment]
Never hurts to do

**Comment by sysnoo** [comment]
LOL  you are right
php artisan migrate  ===>  Nothing to migrate.

**Comment by snipe** [comment]
Any progress on this? I'm honestly not sure what you might have done to get this so hoarked up. :-/

**Comment by torriz** [comment]
You also cannot do the upgrade to snipeit 2 because the dineshrabara barcode https://github.com/dineshrabara/barcode repository is unavailable due to DMCA takedown. Sigh.

Also: Seriously, have no one requested install script(s) for snipeit? 
It really seems like it's a pain in the *** for most users to set this up properly.

**Comment by snipe** [comment]
@torriz There is an experimental install.sh script, but this will work only on linux distros. 

If you follow the documentation, Snipe-IT shouldn't be that difficult to install. The issue is usually related to the fact that many IT people don't have experience running web servers, and this is web based software.

**Comment by snipe** [comment]
@torriz additionally, the fix fir the barcode dependency was released 3 days ago. 

And I think most people don't have an issue installing it. What you're seeing is clinicians bias: this is a support channel. The only people you'll see posting here are people who are having trouble. The thousands of other people who are not have no reason to post here.

**Comment by richardomi** [comment]
Installing php5-curl fixed this for me - apt-get install php5-curl

**Comment by snipe** [comment]
@richardomi Yeah, they already installed php-curl. Without more info from the error logs, I can't tell what's happening with their install.

**Comment by torriz** [comment]
@snipe Oh damn, I didn't notice it! My bad :(

@snipe Well, I guess you're right. Personally I only had trouble in the earlier versions, and when upgrading to the (snipe-it 2 - barcode issue). I'll check out the latest release then :)
