### ISSUE TITLE
Feature Request : Adding of Cost Field in Consumables

### ISSUE THREAD

**Issue by dahiya81** [snipe/snipe-it#1139]
It will be great to add a Cost Field and Cost Per Consumable which is assinged to user . This will help in arriving per user cost on consumables

**Comment by sysnoo** [comment]
Custom fields and attributes are also relevant for asset
Ex. LTE Tablets : SN, IMEI and Phone Line #.

Add quantity for Consumable and accessories is nice idea also.
Ex. Quantity of Paper, Batteries...

**Comment by snipe** [comment]
@sysnoo custom fields for asset models are already in development

**Comment by snipe** [comment]
This is already on the develop branch
