### ISSUE TITLE
Asset Maintenance Time (in days) Field inconsistant

### ISSUE THREAD

**Issue by drahamim** [snipe/snipe-it#1140]
Asset Maintenance Time is inconsistent between Table View and Maintenance View. 
See images. 

![image](https://cloud.githubusercontent.com/assets/3834219/9590097/67e1fb88-4fe7-11e5-98cc-f4855cc4f7e6.png)

![image](https://cloud.githubusercontent.com/assets/3834219/9590144/a9a262b0-4fe7-11e5-9a1c-0fa2b487352e.png)

**Comment by snipe** [comment]
Not sure what I'm looking at - those two images look the same to me.

**Comment by drahamim** [comment]
oh you may be seeing the original post which I had accidentally copied the same image twice. refresh.

**Comment by leobg** [comment]
I can confirm this issue, I am running snipe-it-2.0.1, here is a screenshot:

<img width="622" alt="snipeit-maintenance-bug" src="https://cloud.githubusercontent.com/assets/10868370/9701638/f8c2ef78-5400-11e5-9526-e68aa05acebe.PNG">

**Comment by leobg** [comment]
I think I know what happens. Asset maintenance time is calculated from START DATE to the date maintenance is entered in the system instead COMPLETION DATE.
