### ISSUE TITLE
Digits after decimal 

### ISSUE THREAD

**Issue by jalynrabey** [snipe/snipe-it#1142]
Its possible for my currency change to 3 digits after decimal, my currency en Chile have 3 digits after the decimal.
##

**Comment by snipe** [comment]
That's not currently a feature in Snipe-IT, but we can possibly flag it for an upcoming version.

**Comment by jalynrabey** [comment]
thanks a lot

**Comment by Jaikarthikr** [comment]
My currency can work with up to 3 digits after the decimal. In Bahrain, my currency has three digits after the decimal point.
