### ISSUE TITLE
Can't contact LDAP server 

### ISSUE THREAD

**Issue by KristijanL** [snipe/snipe-it#1144]
Hi,

i have follow the snipe-it  documentation and got snipe-it up and running, but i cant sync LDAP users.
My configuration is correct as i can successfully test with ldapsearch.
Error if i try to sync:

Error: Could not bind to the LDAP server. Please check your LDAP server configuration in the LDAP config file.
Error from LDAP Server: Can't contact LDAP server 

The weird thing is i cant see any connection being made by snipe-it if i listen with tcpdump on LDAP server.

I am not sure where to put ldap.php beacuse of : 

http://docs.snipeitapp.com/installation/configuration.html
"Optional: LDAP Configuration

To set up your Snipe-IT installation to be able to use LDAP for user login and import, copy the app/config/production/ldap.example.php over to app/config/production/ldap.php and follow the directions to use your own LDAP settings. "

and 

https://github.com/snipe/snipe-it/releases
"If you plan to take advantage of the LDAP features, you will need to make sure the php-ldap extension is installed. You will also need to copy the app/config/production/ldap.example.php file to app/config/ldap.php and update it with your LDAP settings."

[root@server www]# rpm -qa | grep php-ldap
php-ldap-5.4.16-36.el7_1.x86_64

Best Regards,
Kristijan Lecnik

**Comment by ExactCare** [comment]
@KristijanL I have recently installed and configured LDAP on SnipeIT. Create a copy of your ldap.example.php and rename said copy yo ldap.php. Edit the parameters inside to reflect your LDAP server/port etc... When pulling values from the directory, make sure to type your attribute fields in lowercase. Additionally, you must have a user account with at least read rights to access the directory and return values.

This is solely based on my experience configuring LDAP with an Active Directory account.

Also, you want to make sure the the php ldap extension is installed and enabled with your php modules/extensions.

**Comment by ESWBitto** [comment]
You might want to check and make sure that either server that you have snipe it installed on or your network firewall are not blocking the connection between the two.

**Comment by KristijanL** [comment]
Oh man, i am so embarrassed... I mistyped the hostname so no wonder there was no connection to LDAP server. I can just confirm that you need ldap.php in "app/config/production" if you use production.
Its funny how you can see the error immediately after a good night sleep.
Thank you anyway! :)
