### ISSUE TITLE
This page cannot be displayed 

### ISSUE THREAD

**Issue by ksavett** [snipe/snipe-it#1145]
Hello I am having issues with getting the page to load. I am using IIS 8 on server 2012 r2. I have followed all the steps and everything has went good. I have installed composer and artisan app with no issues. I have also imported the URL rewrite rules. The site is tied down by host and I have made a change to dns and can ping the site name. I have other sites that are running fine set up the same way. Any help would be appreciated thanks.

**Comment by snipe** [comment]
Can you show me a screenshot of your URL Rewrite rules?

**Comment by ksavett** [comment]
![screen shot 09-03-15 at 03 27 pm](https://cloud.githubusercontent.com/assets/14110870/9668617/871135f8-5250-11e5-8a5b-94d9919887e3.PNG)

**Comment by snipe** [comment]
Try removing the `Imported Rule 1`. It's commented out in the htaccess file, but for some reason it gets imported anyway on IIS, and that makes the server try to redirect to an SSL version, which, if you're not running SSL, will give you an error.

**Comment by ksavett** [comment]
I tried removing the import rule 1 and still no luck.

**Comment by snipe** [comment]
Do you have to restart IIS when you tweak rules?

**Comment by ksavett** [comment]
Ok I tried restarting IIS and the services for it but still the same.

**Comment by ddreier** [comment]
Is your Physical Path for the IIS site pointing to the public folder in your snipe-it directory?

**Comment by ksavett** [comment]
![screen shot 09-03-15 at 03 47 pm](https://cloud.githubusercontent.com/assets/14110870/9669101/2c5b229c-5253-11e5-8992-4b2fd5b3f51a.PNG)

This is how it is set up now I placed the public folder along with all my other Snipe-it files on a separate drive. Does that matter, would it have to be on the c drive in the C:\inetpub\wwwroot?

**Comment by ddreier** [comment]
The location doesn't (shouldn't) really matter as long as the permissions are set up correctly. What error code shows up in the IIS access log for the site?

**Comment by ksavett** [comment]
Not really sure what it was but it started working. Maybe the changes to the Rule took longer to enforce? Not sure but looks good now. Thanks for the help and quick response.

**Comment by snipe** [comment]
Great, glad everything is working!

![3z](https://cloud.githubusercontent.com/assets/197404/9670014/3726fda4-523f-11e5-9e6c-4b6de299b427.gif)
