### ISSUE TITLE
Feature Request: Effective Permissions based on Groups

### ISSUE THREAD

**Issue by ESWBitto** [snipe/snipe-it#1146]
I am requesting that there be a way to create effective permissions on users that belong to a group so that I can limit the amount of access they have in snipe IT.

Scenario:

I want a user to be able to assign chromebooks to students and only be able to see/manage those assets. This user would not be able to see license counts or any other asset besides the assets that the group has access to. 

I'm not sure how granular this will become. I thought it would be a nice way to take some added responsibility off of the IT guys.

**Comment by blechdom** [comment]
this worked for me...
http://stackoverflow.com/questions/21406318/how-to-get-groups-belonging-to-user-cartalyst-sentry-2
