### ISSUE TITLE
LDAP attribute case-sensitivity

### ISSUE THREAD

**Issue by dc53000** [snipe/snipe-it#1150]
When importing users with LDAP, I configured the LDAP attributes like so:
```
    'result.username' => "uid",
    'result.last.name'  => "sn",
    'result.first.name' => "givenName",
```
This resulted in the following error for every user, even though each of them has a defined givenName attribute.
```
Validator failed:
The firstname field is required.
```

If I change it to:
```
    'result.first.name' => "givenname",
```

then everyone seems to import correctly with the givenName (capital N) attribute in LDAP. It seems maybe like ldap attribute names are being lower()ed at some point that may not be appropriate. I don't really mind just using the lowercase name in the config, but it seems like non-obvious behavior that will probably trip people up.

**Comment by toddjames** [comment]
I just wanted to say thank you for posting this. I was having the same issue and this helped.
