### ISSUE TITLE
LDAP Version needs to be set to allow logins

### ISSUE THREAD

**Issue by dc53000** [snipe/snipe-it#1151]
I had to make these changes to allow LDAP authentication to work. Prior, I was getting this error in the debug log:

```
[2015-09-04 14:05:24] production.DEBUG: Authenticating user against LDAP. [] []
[2015-09-04 14:05:24] production.ERROR: ldap_bind(): Unable to bind to server: Protocol error [] []
```
Sorry for not having a patch or making a pull request, I am unfortunately git-stupid.

The fix is in app/controllers/AuthControllers.php
Add at line 35:
```
$ldapversion = Config::get('ldap.version');
```
Add at line 43:
```
ldap_set_option($connection, LDAP_OPT_PROTOCOL_VERSION,$ldapversion);
```

This was to auth against openldap server 2.4.28-1.1ubuntu4.3. 

Client libraries:
```
ii  libldap-2.4-2:amd64                 2.4.31-1+nmu2ubuntu8.1           amd64        OpenLDAP libraries
ii  php5-ldap                           5.5.9+dfsg-1ubuntu4.11           amd64        LDAP module for php5
```

**Comment by snipe** [comment]
Huh. I could have sworn I had done that already. :-/

Anyway, thanks!

![huzzah](https://cloud.githubusercontent.com/assets/197404/9774125/66bea1aa-56fb-11e5-8d10-2816b48dc86c.gif)
