### ISSUE TITLE
Feature Request: LDAP Groups Sync

### ISSUE THREAD

**Issue by crmunro** [snipe/snipe-it#1152]
It'd be great if we could automatically assign users to groups based on their LDAP/Active Directory group membership. For example, we are a school that has both our Staff and Students in Snipe-IT, as we assign certain assets to our students.

It would be very helpful if we could group them into their separate groupings easily, so we can quickly see whether a user is a staff member or not. Along with the syncing of locations (Issue #1091), we think user management with Snipe-IT will improve greatly!
##

**Comment by jghanlon** [comment]
Hope this makes it in.  Would love to be able to sync only specific groups (Department OUs) instead of everyone at once.  And then have a visual grouping in Snipe that matches so it is easier to see the grouping and hierarchy.

**Comment by mwiora** [comment]
1+

**Comment by chrisgassen** [comment]
pls?? any news?

**Comment by Kizan** [comment]
Really could use this feature!
