### ISSUE TITLE
[Bug] Renaming Button

### ISSUE THREAD

**Issue by tcresposhiver** [snipe/snipe-it#1154]
Not sure if it's just on my end but there's a button that shows the direct path of the function that it uses. Here's a screenshot  ^^ 
![youknowthelittlethings](https://cloud.githubusercontent.com/assets/13354402/9707038/67c7e64e-54c9-11e5-92e5-d02e7b6f0bc5.png)

**Comment by snipe** [comment]
That's not the function it uses, that's the localization language string. Looks like you have a missing translation.

**Comment by tcresposhiver** [comment]
whoops sorry didn't notice, thought it was pointing to a function. When i a run a git pull it says everything is up to date. If i'm not mistaken I also did a clean pull of the repo. Let me know if you want me to do anything :P. 

Thanks Snipe!
