### ISSUE TITLE
No Email to Admin or Asset "owner"

### ISSUE THREAD

**Issue by Julianh94** [snipe/snipe-it#1156]
When someone requested a asset, no Email is send to the Admins or Asset Owner to notify them about the request. 
Maybe it is not a issue, but then i would be a nice feature in the future. Also a notification (E-Mail) to a user when a admin add a asset to him would be nice too.

**Comment by snipe** [comment]
Email notifications for asset acceptance are available on the category level.

**Comment by Julianh94** [comment]
Thanks :+1: 

Sorry for the following. It has nothing todo with the "issue" before.

Exists a option to print a report for the assigned asset. So that the user must sign it and we as admins (Or as busines) have a signed paper that he has become this asset/s ?

**Comment by snipe** [comment]
@Julianh94 we don't currently support printed acceptance for assets.
