### ISSUE TITLE
Trouble with mixed content when using mod_proxy with SSL

### ISSUE THREAD

**Issue by toddjames** [snipe/snipe-it#1157]
The way our infrastructure is set up is we use Apache with mod_proxy as a reverse proxy for access to most internal applications, and the reverse proxy provides SSL. For example, https://snipeit.contoso.com (SSL) is Apache with mod_proxy that provides access to internal applications. It will proxy requests to http://snipeit.city.contoso.com (no SSL).

The reverse proxy part is working fine, as it does with the rest of our applications, but Snipe-It seems to be embedding absolute URLs into the HTML that use http:// rather than https://. This causes the browser to not load the mixed content (stylesheets, images, etc).

In app/config/production/app.php I have 'url' set to 'https://snipeit.contoso.com' but that doesn't seem to help.

Any thoughts?

**Comment by snipe** [comment]
Can you show me the browser warning so we can see which files? We run it over SSL all the time with no issues. What version are you using?

**Comment by toddjames** [comment]
This is v2.0 (cloned from GitHub on Friday).

Here's a screenshot:
![snipeit](https://cloud.githubusercontent.com/assets/860775/9739792/627ca740-561f-11e5-8e32-49c6989bf016.png)

**Comment by snipe** [comment]
Can you copy  `app/config/packages/fideloper/proxy/config.example.php` to  `app/config/packages/fideloper/proxy/config.php` and update the proxies value to reflect your IP address?

**Comment by toddjames** [comment]
I changed it from:

```'proxies' => '*',```

to

```'proxies' => '10.10.28.3',```

But I'm still experiencing the same behavior as before.

**Comment by snipe** [comment]
I'm honestly not sure then. The TrustedProxy package has always worked for us (we do run Laravel over a proxy for some projects). This issue might add more clarification: https://github.com/snipe/snipe-it/issues/859

**Comment by toddjames** [comment]
Perfect - that is exactly my issue and helps a lot. I think I'm almost there now. I enabled mod_headers on the Apache reverse proxy and added this line to my vhost: ```RequestHeader set X-Forwarded-Proto "https"```

When I make changes to ```app/config/packages/fideloper/proxy/config.php``` is there anything else I need to do in order to make changes to that file go into effect?

**Comment by toddjames** [comment]
I was able to get it working, though I'm not sure if this is the correct way (I know nothing about Laravel/PHP frameworks - I typically live in the Python world).

1. Enable mod_headers on the Apache reverse proxy
2. Add ```RequestHeader set X-Forwarded-Proto "https"``` to the vhost on the reverse proxy
3. Modify ```app/config/packages/fideloper/proxy/config.php``` as mentioned above
4. Add ```'Fideloper\Proxy\ProxyServiceProvider'``` to the ```providers``` array in ```app/config/app.php```
5. Run ```php artisan config:publish fideloper/proxy``` from the application root

I'm not sure if steps 4 and 5 were the way I was supposed to do it or if they will stick upon upgrades, but it seems to be working now.

**Comment by snipe** [comment]
Step 3 may overwrite step 5. Publishing the config creates the config.php. (We don't tell you to do the publish bit because we already provide an example config, so there's no need, you can just copy it over.)

Somehow we missed step 4 - that should have already been done in the latest release, but somehow wasn't. Sorry about that.

**Comment by snipe** [comment]
We've added the provider into the `app.php` (which we should have done before) and have updated the docs to include instructions for this. Can you take a look when you get a chance and confirm that this makes sense to you?

http://docs.snipeitapp.com/installation/proxy.html
