### ISSUE TITLE
New install -> No Users Migration

### ISSUE THREAD

**Issue by shairozan** [snipe/snipe-it#1158]
When doing a new install of version 2, once the environments are configured, migration fails after migration table. The first processed migration looks like it's trying to update a users table that doesn't exist. Needs the default users table definition first.

**Comment by snipe** [comment]
Initial migrations are done when you run the `php app:install` command

**Comment by shairozan** [comment]
`php artisan app:install` for anyone else who ran into the issue.

**Comment by snipe** [comment]
Yes, that's in the documentation: http://docs.snipeitapp.com/installation/command-line.html
