### ISSUE TITLE
DataTables warning / AJAX Error when clicking List All (assets)

### ISSUE THREAD

**Issue by strevithick** [snipe/snipe-it#1160]
Hi folks,
Somehow through the process of importing users from LDAP, and users with assets using the CLI or perhaps deleting users, I've introduced some DB corruption. When loading all assets using the List All link, I get the following error: 

DataTables: warning: table id=LdFImFzK. Ajax error. For more information about this error, please see http://datatables.net/tn/7

The table id varies each time I reload the page or click on the link.
The page list of assets than fails to load and I'm stuck with a single row result that says "Loading".

Other links such as Deployed, Ready to Deploy, Pending, etc. all work. The only "broken" link appears to be List All.

Using the most current stable version as of September 2015.

**Comment by snipe** [comment]
Can you turn debugging on and tell me what you see at http://your-hostname/api/hardware/list

**Comment by strevithick** [comment]
I get the following message:

Oh no!
Server Error: 500 (Internal Server Error)
What does this mean?

Something went wrong on our servers while we were processing your request. We're really sorry about this, and will work hard to get this resolved as soon as possible.

Perhaps you would like to go to our home page?

**Comment by snipe** [comment]
Please turn debugging on so you get verbose output.

**Comment by strevithick** [comment]
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)

Call to a member function fullName() on a non-object
Open: /var/www/snipeit/app/controllers/admin/AssetsController.php

    				    return 'No model';
    				}
    			})
     
          ->addColumn('status',function($assets)
            {
              	if ($assets->assigned_to!='') {
                	return link_to(Config::get('app.url').'/admin/users/'.$assets->assigned_to.'/view', $assets->assigneduser->fullName());
                } else {
                    if ($assets->assetstatus) {...

**Comment by snipe** [comment]
Do you know if any users were deleted manually from the database? You should only be seeing that error if data has been manually manipulated.

**Comment by strevithick** [comment]
Yes. When I initially imported from the AD server, the import was not clean and I think might have done a manual delete from the DB. I'm proficient in SQL. Did I break references to these users in another table?

**Comment by snipe** [comment]
Yeah, I'd bet money that's what happened. 
http://docs.snipeitapp.com/installation/manually-editing-data.html

You'll need to figure out the ID numbers of the users you deleted, delete their records from the asset_logs table, and null out the `assigned_to` field in any assets that are associated with those user IDs.

**Comment by strevithick** [comment]
Ok, The weird thing is that no assets had been created at that point. This is a new install that we're just starting to populate. Anyway, I'll take a look at those tables.

**Comment by snipe** [comment]
There have to have been some assets created (even just seed data or whatever), or the `assigned_to` call wouldn't have been triggered.

**Comment by snipe** [comment]
You might be able to identify the missing users by looking at the sequence of IDs in the database for the `users` table. They auto-increment, so if you see any gaps in the sequence, that's a user that was manually deleted.

**Comment by strevithick** [comment]
There is an asset with a value of 0 in the assigned_to field. All the others look like valid UIDs or NULL values. Could that be it? No asset should be assigned to the admin user.

On the other hand, there are only 5 records in asset_logs table. Should I just empty it (I have backups).

**Comment by snipe** [comment]
Try nulling that 0 record out

**Comment by strevithick** [comment]
That did it. Working again. Thanks for the responsive help!

**Comment by snipe** [comment]
No problem - glad you got it sorted.

![5jrc17t](https://cloud.githubusercontent.com/assets/197404/9769369/9d2ab692-56de-11e5-9356-b410926432af.gif)
