### ISSUE TITLE
No labels when creating asset labels

### ISSUE THREAD

**Issue by tnilsson95** [snipe/snipe-it#1162]
I have recently installed Snipe IT on windows 7 using XAMPP and everything is working great, except that when i open the asset details view there is no QR code in the top right like the demo has and if i go to the asset view list and check the selected box then click the drop down at the bottom and select generate labels, I get the next page of the asset info but where the label would be it has a broken pic sign, and if i right click and view image it says there is no directory found. Thanks,

Trent

**Comment by tnilsson95** [comment]
Also I can't add to the suppliers or manufactures from the add asset window i can only add them from the manufacture view and the add button in the top right. I don't know if they are related. The add new popup opens for when trying to add them but the save button doesn't do anything when you click it.

**Comment by snipe** [comment]
@tnilsson95 do you have QR codes enabled in the Admin > Settings page?

**Comment by snipe** [comment]
@tnilsson95 they are not related. Please open another ticket with the second issue and include any browser errors and debugging info you might be able to find.

**Comment by tnilsson95** [comment]
Thanks that worked and ok I will open another one.
