### ISSUE TITLE
Cant Add with the plus button.

### ISSUE THREAD

**Issue by tnilsson95** [snipe/snipe-it#1163]
I can't add to the suppliers or manufactures from the add asset window i can only add them from the manufacture view and the add button in the top right. I don't know if they are related. The add new popup opens for when trying to add them but the save button doesn't do anything when you click it.

I don't have debugging info because it does cause an error, I have debugging turned on, it just opens up the popup to enter the new info and after you enter it, you hit save and it doesn't do anything, doesn't close the window or add it, its like the button is dormant.

**Comment by snipe** [comment]
Please open the debugging console of your browser and tell us if you see any errors there when you load the page, or when you click on the plus or save buttons.

**Comment by snipe** [comment]
Also, since this is likely a JS issue, please tell us what browser and what version of Snipe-IT you're running

**Comment by tnilsson95** [comment]
v2.0.1, Firefox

2
https://172.0.0.102/uploads/logo.jpg Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
https://172.0.0.102/api/models/1/check Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
https://172.0.0.102/api/statuslabels/2/deployable Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
https://172.0.0.102/api/statuslabels Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
edit:722 Uncaught TypeError: Cannot read property 'error' of undefined(anonymous function) @ edit:722fire @ jquery-latest.js:3119self.fireWith @ jquery-latest.js:3231done @ jquery-latest.js:9277callback @ jquery-latest.js:9685
https://172.0.0.102/api/statuslabels Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
edit:722 Uncaught TypeError: Cannot read property 'error' of undefined(anonymous function) @ edit:722fire @ jquery-latest.js:3119self.fireWith @ jquery-latest.js:3231done @ jquery-latest.js:9277callback @ jquery-latest.js:9685
https://172.0.0.102/api/statuslabels Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
edit:722 Uncaught TypeError: Cannot read property 'error' of undefined(anonymous function) @ edit:722fire @ jquery-latest.js:3119self.fireWith @ jquery-latest.js:3231done @ jquery-latest.js:9277callback @ jquery-latest.js:9685
https://172.0.0.102/api/statuslabels Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
edit:722 Uncaught TypeError: Cannot read property 'error' of undefined(anonymous function) @ edit:722fire @ jquery-latest.js:3119self.fireWith @ jquery-latest.js:3231done @ jquery-latest.js:9277callback @ jquery-latest.js:9685
jquery-latest.js:9631 POST https://172.0.0.102/api/statuslabels net::ERR_CONNECTION_TIMED_OUTsend @ jquery-latest.js:9631jQuery.extend.ajax @ jquery-latest.js:9176jQuery.(anonymous function) @ jquery-latest.js:9322(anonymous function) @ edit:709jQuery.event.dispatch @ jquery-latest.js:4641elemData.handle @ jquery-latest.js:4309
edit:722 Uncaught TypeError: Cannot read property 'error' of undefined(anonymous function) @ edit:722fire @ jquery-latest.js:3119self.fireWith @ jquery-latest.js:3231done @ jquery-latest.js:9277callback @ jquery-latest.js:9685
jquery-latest.js:9631 POST https://172.0.0.102/api/statuslabels net::ERR_CONNECTION_TIMED_OUTsend @ jquery-latest.js:9631jQuery.extend.ajax @ jquery-latest.js:9176jQuery.(anonymous function) @ jquery-latest.js:9322(anonymous function) @ edit:709jQuery.event.dispatch @ jquery-latest.js:4641elemData.handle @ jquery-latest.js:4309
edit:722 Uncaught TypeError: Cannot read property 'error' of undefined(anonymous function) @ edit:722fire @ jquery-latest.js:3119self.fireWith @ jquery-latest.js:3231done @ jquery-latest.js:9277callback @ jquery-latest.js:9685
jquery-latest.js:9631 POST https://172.0.0.102/api/statuslabels net::ERR_CONNECTION_TIMED_OUTsend @ jquery-latest.js:9631jQuery.extend.ajax @ jquery-latest.js:9176jQuery.(anonymous function) @ jquery-latest.js:9322(anonymous function) @ edit:709jQuery.event.dispatch @ jquery-latest.js:4641elemData.handle @ jquery-latest.js:4309
edit:722 Uncaught TypeError: Cannot read property 'error' of undefined(anonymous function) @ edit:722fire @ jquery-latest.js:3119self.fireWith @ jquery-latest.js:3231done @ jquery-latest.js:9277callback @ jquery-latest.js:9685

**Comment by tnilsson95** [comment]
![image](https://cloud.githubusercontent.com/assets/14174243/9776717/2cb99dec-5710-11e5-9240-a637ed336613.png)

**Comment by tnilsson95** [comment]
sorry its google chrome

**Comment by snipe** [comment]
Well, your javascript files aren't loading, that's why it's not working. Are you actually running this over SSL? Those calls are pointing to SSL urls

**Comment by tnilsson95** [comment]
I tried loading the ssl page and it did the same this I also realized its using the wrong IP so im going to change that and I will let you know what error comes up after that.

**Comment by tnilsson95** [comment]
I updated the address and im getting the same error, but when i manually cahnge the link over to http it works is there a way to tell it to use http not https or add permissions so that the server will let https see that file

**Comment by snipe** [comment]
If you're not running SSL, you can't have it point to SSL urls, or it won't work. 

What do you have in your `app/config/production/app.php` for the `url`?

**Comment by tnilsson95** [comment]
it was https:// i cahnged it to http and it worked everything is working great thanks, should i convert it over to ssl and is that in the documentation on how to

**Comment by snipe** [comment]
We always encourage using SSL wherever possible, however SSL can be challenging to set up if you've never done it before, and it's a bit outside the scope of our documentation to explain how to set up SSL on on their servers.

Our comments on SSL are here:
http://docs.snipeitapp.com/security.html

And there's a decent tutorial on setting up SSL online here:
http://www.htmlgoodies.com/beyond/security/article.php/3774876/Setting-Up-a-Secure-SSL-Connection.htm
