### ISSUE TITLE
Consumables Report

### ISSUE THREAD

**Issue by lcalway** [snipe/snipe-it#1164]
I've looked around and can't seem to find anything for this. But it'd be great to have a report that gave us a listing for consumables, I know there is an accessory one but we would use this one for keeping track of toner stock levels and other consumable devices at a glance.

As part of the report, in combination with another request I have seen, it would be great to have a minimum alert column. Allowing you to set a minimum for each consumable and have a quick glance in the report to see what needs ordering.
##

**Comment by NicholasBentley** [comment]
I'd love to see this happen too :)

My knowledge of php is limited, but I'm working on self-implementing this.
