### ISSUE TITLE
Unable to integrate ldap

### ISSUE THREAD

**Issue by rlnigala** [snipe/snipe-it#1165]
I am unable to locate ldap server in snipe it . my OS is ubuntu 12

under Create Users from LDAP  section 
i cannot see anything in location drop box.

i have installed php5-ldap and have added extension in /etc/apache2/php.ini

the location of ldap.php is app/config/production/ldap.php
 
When i click on syncronize i get  Error: Please check the form below for errors

**Comment by dc53000** [comment]
Did you add your first location under Admin -> Locations? You need to make at least one to be able to import users somewhere.

**Comment by rlnigala** [comment]
Hi thanks i have added location but now i facing below error

: Could not bind to the LDAP server. Please check your LDAP server configuration in the LDAP config file.
Error from LDAP Server: No such object

**Comment by dc53000** [comment]
It sounds something is not configured completely with your LDAP configuration. Did you change the url, the username, the password, and the basedn to match your ldap setup? You will need to find what these are for your site, the defaults will not be correct. They should also be in a similar format as to what's in the example file. For example, if your user is just "admin", that won't work.

**Comment by rlnigala** [comment]
I have changed LDAP URL as ldap://ipaddress, gave username and password, changed basedn and i have my filter query as  'filter' => "&(cn=*)", is this correct?

**Comment by dc53000** [comment]
You should generally be able to leave the filter alone. It is most likely that your basedn is not correct, but it is very hard to guess without seeing your ldap schema. Is it something like "ou=Users,dc=example,dc=com"? What kind of LDAP server is it? Do you have some other service that uses LDAP that you can copy the settings from? Can you browse the LDAP tree in some way to verify the DN under which all your users exist?

**Comment by kobie-chasehansen** [comment]
This may help...

You can easily find your ldap path by right clicking on your OU containing your users and going into the Attribute Editor tab then scrolling down to the distinguishedName

![image](https://cloud.githubusercontent.com/assets/10247644/9788513/56b85088-5798-11e5-83bf-6023a2dd1c43.png)

**Comment by rlnigala** [comment]
We are using open LDAP on Linux Server, so my base dn was set to dc=orgname,dc=local

**Comment by rlnigala** [comment]
using command line i am able to connect to LDAP but problem exists only with snipeit. I have configured it in the same as i did in the server still i don't what is the exact problem.

**Comment by dc53000** [comment]
On your ldap server, you should be able to use ldapsearch to dump your ldap directory and look through it. Something like this:
```
ldapsearch -xLLL -b dc=orgname,dc=local
```
Then you should be able to find 2 things (hopefully near the top).
1: Your username's full DN, something like this
```
dn: cn=read-only-admin,dc=orgname,dc=local
```
2: The DN that you're using for your base DN, which if you say is dc=orgname,dc=local, then the record should start with:
```
dn: dc=orgname,dc=local
```
Are you able to find those 2 entries and do they match exactly?

**Comment by dc53000** [comment]
What command line do you use to connect to LDAP?

**Comment by rlnigala** [comment]
when i use this command ldapsearch -xLLL -b dc=orgname,dc=local i got something like below
dn: uid=username,ou=People,dc=orgname,dc=local 
and i configured basedn as ou=People,dc=orgname,dc=local but still it is same problem.
we connect through terminal to connect to LDAP

**Comment by dc53000** [comment]
Are you using an admin account or some user account? User accounts may not have the permissions they need to search the directory.

**Comment by rlnigala** [comment]
i am using admin account

**Comment by dc53000** [comment]
Are you sure your admin account is under the ou=People? Most OpenLDAP directories have their admin account at the top, like "cn=admin,dc=orgname,dc=local". If it has been moved from there, then you may be better off asking your LDAP server administrator to help you figure out the appropriate settings to use.

**Comment by rlnigala** [comment]
Hey sorry !! its like this
dn: cn=Directory Administrators,dc=smartron,dc=local

**Comment by dc53000** [comment]
That appears to be the DN of a group, not an admin user.

**Comment by rlnigala** [comment]
for all the user accounts i see ou=People only there is nothing like cn=admin
i am trying to give username as root in ldap.php

**Comment by rlnigala** [comment]
Hi all thanks for the help!! It worked . I had to contact admin for LDAP configuration.
