### ISSUE TITLE
Avery 5027 Labels not properly sized and not aligned

### ISSUE THREAD

**Issue by jonbeard** [snipe/snipe-it#1166]
Hey guys,

I have used Avery 5027 labels as suggested from Snipe - However it looks like several things are wrong - the QR code is too big for the label, and its not spaced and aligned properly. See below picture:

http://i.imgur.com/EDQxENy.jpg

**Comment by snipe** [comment]
We'll be tackling this in issue #1389. In the meantime, one user figured out this (admittedly very janky) workaround:

Check 18 assets, at the bottom select generate labels, click go.

Menu -> Print:

- Custom margins: L=0, R=0, T=0.06”, B=0.15”

- No header/footer

- Select printer: “Save as PDF”

Open pdf in Foxit Reader:

File -> Print:

- Scale:

o Custom Scale = 94%

- Check the box for “Auto-Center”

- Click Print

**Comment by sehamiltonmsdwt** [comment]
Any timetable on this?

**Comment by snipe** [comment]
v3 allows for much greater customization in labels and should resolve this issue.
