### ISSUE TITLE
Assistance on using the terminal for our Snipe-it app

### ISSUE THREAD

**Issue by mthimkhulusd** [snipe/snipe-it#1169]
I have been trying to understand how I can do the setup if I want to import assets on to our snipe-it app online. But I am struggling to actually do the whole process. Can you please assist me with that. I am not even sure how to access the terminal that will run the (php artisan ) commands.

Would greatly appreciate your assistance.

**Comment by snipe** [comment]
@mthimkhulusd What OS are you on?

**Comment by mthimkhulusd** [comment]
The app is hosted on a Linux OS server.

**Comment by snipe** [comment]
I'm honestly not even sure where to start here. Are you using the GUI on your Linux machine? 

What flavor of Linux, and what desktop environment and window manager are you using? (GNOME, UNITY, Xfce, KDE, etc.)
