### ISSUE TITLE
Install Dependencies - Barcode DMCA Takedown

### ISSUE THREAD

**Issue by TecSet** [snipe/snipe-it#1170]
Barcode got a DMCA Takedown which is a problem for installing dependencies with 
composer install --no-dev --prefer-source 
Any Alternative?

https://github.com/dineshrabara/barcode
https://github.com/github/dmca/blob/master/2015-09-09-Tecnick.md

**Comment by dc53000** [comment]
According to the DMCA takedown, the dineshrabara one is identical except for the missing GPL notices. This one appears to be suggested as the authoritative source of the same tool:
https://github.com/tecnickcom/tc-lib-barcode
