### ISSUE TITLE
Importing custom attributes via LDAP?

### ISSUE THREAD

**Issue by jbirdkerr** [snipe/snipe-it#1172]
Does Snipe IT's ldap sync currently have the ability to sync attributes other than the firstname, lastname, etc. that's featured in the documentation? Specifically, I'm trying to import the "manager" field for everyone so we can take advantage of the Snipe's reporting feature.
##

**Comment by snipe** [comment]
That's not currently possible, but also importing managers would require additional work, since the manager is stored as a user ID in the database, it's not a text field.

**Comment by DWSR** [comment]
Other attributes that would be nice to see are "Title" and "Phone".
