### ISSUE TITLE
Feature request: Insurance for equipment [$100]

### ISSUE THREAD

**Issue by ltt** [snipe/snipe-it#1176]
We constantly buy insurance for all our equipment and we need to keep track whether we have purchased insurance for our equipment or not. 

I believe it is the same for other companies too. It would be nice if snipeit has this useful feature
##

**Comment by drahamim** [comment]
Is that different from maintenance contracts?

**Comment by klemendlabs** [comment]
We are having the same feature request!

**Comment by snipe** [comment]
Hi - we need more information on what this would mean, exactly. Is this a checkbox that says "insured/not insured"? Some other field? How exactly do you see this working?

**Comment by klemendlabs** [comment]
Hi!

Suggestion for fields :
- insured ( yes / no )
--> insured == yes enables next fields
- insurance start
- insurance end
- upload insurance policy
( - auto renewal policy? )
( some sort of comment? )

**Comment by snipe** [comment]
@klemendlabs Why wouldn't you just use custom fields and a file upload for that?

**Comment by klemendlabs** [comment]
this solution, although as a feature it works, is somehow not self-intuitive, wouldn't you agree? Two different people would, for instance, choose different naming conventions for file upload...

I would suggest/propose adding insurance feature as its own feature/entity?

I would like to have an automated insurance policy upload (automated in a way of auto-naming uploaded files), maybe even upload timestamp.

Also, some sort of implementation of warnings (when due date is approaching)?

**Comment by Matthewrbowker** [comment]
There's some interest in our organization as well, so I'm interested in taking this on.  Here's what I propose:

- Insured (checkbox: if yes, enable other fields)
- Insurance Provider
- Insurance Policy Number
- Insurance Start
- Insurance End
- Upload Insurance Policy (file upload field)

Is this acceptable? Also, is it acceptable for me to take this on?

**Comment by Matthewrbowker** [comment]
Actually, after further looking at this, I think I'm going to implement this a little different than proposed.  Here's what I propose:

A separate view for "insurance," similar to manufacturers, be created.  Creation, modification, and deletion of insurance policies would be managed in a similar way to manufacturers.  This allows for a 1-to-many relationship with assets.  The following database modifications will be made:

- Creating of a "insurance" table, with each row being information on one policy.  
- Adding a column to the "assets" table, relating to an ID from the "insurance" table.  

The following view modifications will be made:
- To asset creation and editing, an additional dropdown allowing for the selection of an existing insurance policy or a "create new" option which shows the insurance creation view in a modal.  

Additionally, new "/insurance" "/insurance/{id}" "/insurance/new" "/insurance/{id}/edit" and "/insurance/id/delete" routes will be added.

**Comment by snipe** [comment]
The second way is definitely the way I'd want this to go, but also thinking about this from a less-isolated method... 

- Does insurance get applied to assets? Asset models? 
- Is it possible an asset/model would have more than one insurance?
- We should probably tie maintenances into insurance
- Are we thinking insurance is different from warranty? Should it be? Should it not be?
- People are almost definitely going to ask for some sort of maintenance+insurance file upload (insurance paperwork, maintenance orders that fall under covered claims, etc)
- Do people get insurance? (I'd assume not, but I don't know every use case)
- Would an insurance policy exist that covers assets, consumables, etc? (Homeowners equivalent, etc)

### Additional places we need to expose this info:

- Assets API (need to return the value, but also allow scoping by type of insurance so we can display assets by insurance type in the insurance view?)
- Custom Asset Report export 

We have a bunch of different similar-but-not-exactly-the-same types of potential things to wrap this into, or to have wrapped into this. Contracts (whatever that means, really), warranty, maintenance, orders, invoices, etc. People have asked for all of these things over time, and I want to spend the time to look at: Is there way to kill multiple birds with one stone without compromising the UX __OR__ the code?

Would love @uberbrady's thoughts here too.

**Comment by Matthewrbowker** [comment]
Thank you for the quick comment.  A few replies/thoughts (in order of your comments)
- In our use case, insurance would be applied to assets.  I'm not sure this is a common use case so I'd love additional feedback.
- Indeed.  A change to the proposed above (per gitter) is instead allow for a many-to-many relationship.  This would create 1 additional table, acting as a mapping table with the columns 'key', 'asset_id', 'insurance_id.'  
- Yes.  The simplest, most logical extension of this is adding another dropdown to the new maintenance record field, field name "Insurance used" with a selection of insurance.  A v2 thought might be adding your claim file upload field to the "maintenance" view.  As for insurance policy information upload, that would be under the main insurance creation/edit view.  
- It's possible for people to get insurance, for example on a film set.  Not something we would need, but something interesting to expand to cover.  See next bullet for implementation.  
- Adding the many-to-many mapping would allow us to simply create an additional mapping table per "type" (not sure what the snipe-it lingo is here...).  An example would be creating another table, for consumables with the fields "key," "consumable_id," "insurance_id."  

# Additional Places
- Didn't think of that, apologies.  I would think we would need to expose it as part of retrieving an asset via the API.  Maybe an additional API endpoint mirroring the endpoints in my previous comment as well allowing for automated management of insurance.
- Again, didn't think of that.  Again, apologies.  I would thing again it would be as an added field to the report, detailing active insurance policies.  

If there is a better place to put this as opposed to in it's own section, I'm more than OK making the changes there!  Just let me know.  

Thanks again for the quick response!

**Comment by snipe** [comment]
Thinking about this further.... let's call this new section "Contracts" for the sake of argument.

Contracts have:

- a start date and end date
- an entity you made the agreement with
- at least one checkoutable model, possibly more (although maybe not when it comes to insurance for people, since people can't be checked out)
- usually at least one file, probably more - though possibly none
- Some description of the scope of what it covers
- possibly some maintenance actions associated with the checkoutable model
- expiration alerts (optional)

Insurance certainly fits that bill. I think warranty does too. SaaS licenses might as well. Domain names and SSL certificates could. Maybe maintenances stays in its own UI section but becomes a trait on the checkoutable models.

We don't have to brand this as Contracts in the UI if that's weird... just thinking about what goes on underneath.

**Comment by Matthewrbowker** [comment]
That makes a lot of sense.  

If I may make a proposal, I can move forward implementing the "contracts" (I'd call it "agreements" on the UI but we can debate translations later :) ) with the exact same details as we've described above.  We'd be able to rename and modify if just to "insurance" if it doesn't work.

**Comment by snipe** [comment]
From a UI/UX perspective, I don't know that we'd want to group all of these things together. They may behave the same (business logic wise) but may not be semantically similar. But that's a problem for another time, I think - and the easiest one of all of these to solve.

**Comment by snipe** [comment]
Potentially related: https://github.com/snipe/snipe-it/issues/5236
