### ISSUE TITLE
Feature Request: View Assets by Location

### ISSUE THREAD

**Issue by adamboutcher** [snipe/snipe-it#1178]
So it would be nice to have an easy way to view all assets at a location, this should include any nested locations.So for instance show all assets at Site A which includes Building A and Building B

**Comment by brianjking** [comment]
Yes! Thank you! Definitely want to assign assets to a location instead of a user as well, I believe this is also included in milestone 2.1.0.

**Comment by snipe** [comment]
@brianjking That's not what this @adamboutcher  is asking for, I don't think. He wants to view a listing of all assets in a location, not assign them to a location (which is a separate issue.)

@adamboutcher - I have a rough version of this on develop now. It doesn't show child location assets yet, but it does list assets assigned to a location.

**Comment by brianjking** [comment]
@snipe Any plans for checking out assets to a location and not a particular user? 

Thanks!

**Comment by snipe** [comment]
Yes, its in development now
