### ISSUE TITLE
Feature/Enhancement: Replenish Consumables from main Consumables page

### ISSUE THREAD

**Issue by phantomofrussia** [snipe/snipe-it#1179]
Looked through the requests and did not find this. Would it be possible to create a replenish button for consumables. Instead of editing the consumable and changing the quantity. 

For example in the pic below I added a plus button to the right of the trashcan. Once you click on that, you get asked how many of that item did you get and then it would add onto the quantity from there.
![consumablesreplenishment](https://cloud.githubusercontent.com/assets/11302002/9942881/a7cc6f46-5d4b-11e5-88d2-e3578f9b31ad.jpg)
##

**Comment by Mooninaut** [comment]
I second this suggestion. My department has an in-house intranet app, which I would like to replace with Snipe-IT. We have "+" and "-" buttons on our consumables page for easy updates. I would like more operations on consumables than Snipe-IT has at present.

1. The current "Check out 1".
2. "Check out multiple" for convenience.
3. "Check in" to reflect when a consumable is checked out, but then returned unused.
4. "Stock Correct" to correct errors, account for lost, destroyed, missing, or lost-and-then-found consumables.
5. "Replenish" to add to the current supply without altering the current amount.
6. "Edit Total" to change the total without altering the current amount.

I know that's a lot to ask for. As an initial step, just having the ability to edit the total and current amounts independently would be great.

**Comment by jrhoades77** [comment]
I agree.  This would be a beneficial feature.  I have some consumables, ribbons, that get checked out up to 10 at a time.  Checking them out one at a time is quite tedious.

**Comment by seobrat** [comment]
Totally agree.  It is certainly a tedious process.

**Comment by koolk** [comment]
please please this. It would bench to have one field that is "quantity on hand" in other words how many I have or magenta toner. and As my shipping company sends me more I can click the plus button. Then as I use a cartridge on a printer I then click the minus button or the checkout button. The "total" column and the "remaining" column feel a bit confusing.

**Comment by Weaksid** [comment]
I see this is marked "Ready for dev", how close is this to be released? 
Thanks

**Comment by stevenhorner** [comment]
The closed issue #2534 asked for the same thing but the issue was closed when it became stale unfortunately. Is this any closer?

**Comment by ReignSol** [comment]
Is there going to be an update on this? It's unfortunate these are getting closed before a reply.

**Comment by phantomofrussia** [comment]
It would be great if this would be implemented. Would make things a lot easier for tracking consumables.

**Comment by jamesm-ffa** [comment]
+1 for this. Would also be essential to have this output to the "changed' field for the activity report for auditing purposes.

**Comment by afranchi74** [comment]
+1 for this feature.
