### ISSUE TITLE
Asset Maintenance Title Field within Individual Asset View

### ISSUE THREAD

**Issue by cobrien165** [snipe/snipe-it#1181]
Others should weigh in too, but I feel the "Title" field from the Asset Maintenances view would be a lot more helpful if was also shown within the individual asset view. Would there be space to include that on the far left?

![image](https://cloud.githubusercontent.com/assets/11300249/9963422/d73d99b2-5df0-11e5-8cab-18ceb1a1b449.png)

**Comment by snipe** [comment]
It looks pretty cramped on my 13" laptop screen, but I can add it
