### ISSUE TITLE
Composer Install error

### ISSUE THREAD

**Issue by djsteady** [snipe/snipe-it#1184]
Hey everyone, just trying to get through the Snipe install and I'm stuck on this and can't get past. I'm running it in admin mode as well

Command: composer install

Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package tecnick.com/tc-lib-barcode could not be found in any  version, there may be a typo in the package name.
  Problem 2
    - Installation request for intervention/image dev-master -> satisfiable by intervention/image[dev-master].    - intervention/image dev-master requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by snipe** [comment]
In `composer.json`, try changing `tecnick.com/tc-lib-barcode` to `tecnickcom/tc-lib-barcode` and run `composer update`

**Comment by rickycee** [comment]
I am completely new to setting this up as well as PHP but I cannot seem to locate the composer.json file or any instructions on how to set it up. Any assistance is greatly appreciated

**Comment by vjandrea** [comment]
`composer.json` is in the root folder of your project, where you ran `composer install`
