### ISSUE TITLE
With a few problems encountered snipe-it, hoping to get help! ! !

### ISSUE THREAD

**Issue by vdministrator** [snipe/snipe-it#1185]
1、Unrecognizable Chinese, when I export the table format .csv（Web page can be displayed properly Chinese）, how to fix it?
2、How to adjust the pattern generator label text description (the default is N and T), I now chose QRCODE format, how to reference the asset ID and assign names in QRCODE the right, what should I do?
Thank you very much developed this open source software, I wish you well !

**Comment by snipe** [comment]
1) Can you show me a screenshot of what you mean?
2) I don't understand the question here. Can you explain?

**Comment by vdministrator** [comment]
![1234](https://cloud.githubusercontent.com/assets/12219743/9988265/9293774e-6081-11e5-8cc6-aeaaf703e0d8.png)
![2345](https://cloud.githubusercontent.com/assets/12219743/9988305/e5516b08-6081-11e5-8f7f-985caf2e7774.png)

**Comment by uberbrady** [comment]
Regarding the CSV - is there a way you can attach that here (perhaps after scrubbing any identifiable data from it?) If that's a problem, let me know and we can try and work out a way for you to get the CSV file directly to me. I have a feeling if I look at the CSV as a raw text file, I'll be able to figure out what's causing the problem you're seeing. I suspect it's something to do with Unicode/UTF-8.

**Comment by uberbrady** [comment]
I think for the second issue you mention, the problem is well stated in #973

**Comment by uberbrady** [comment]
regarding your exports, can you see if this workaround makes the reports work better for you:

https://github.com/snipe/snipe-it/issues/1687#issuecomment-175371511

?
