### ISSUE TITLE
Support Contracts

### ISSUE THREAD

**Issue by dowlingw** [snipe/snipe-it#1187]
#415 and #232 seem to cover software licenses fairly well.

However it is common to have maintenance/support contracts that span multiple devices, for example switches and routers.

I feel that these are significantly different from the current software license functionality to warrant representing as a first-class concept.

Creating this ticket to get some feedback from the maintainers - if this is palatable my employer is likely to contribute this functionality.
##

**Comment by dowlingw** [comment]
A worked example:

Vendor X provides Maintenance contract Y which covers devices A, B and C.
This contact provides 4 hour NBD part replacement as well as firmware upgrades.

**Comment by imie** [comment]
i also would like to support this request. my assets have maintenance contract like above as well.

**Comment by kongou-ae** [comment]
+1
My maintenance contract includes many assets. I hope that the relationship of contract and asset will be one-to-one and one-to-many..

**Comment by jarbro** [comment]
+1

**Comment by DustinMc** [comment]
Just to throw a curly one in this if it is getting implemented....we have equipment that is end of support from the original manufacturer, so we place it on a maintenance agreement with a third party maintainer. I can move items off an on this maintenance contract, but there is a rolling 3 month notification period (or 1 month depending on the device being maintained). 
Ideally, it would be great to be able assign a maintenance agreement that does not have a specified end date, but a future time period  - does that make sense? This would work well to help get reports on what costs are involved in replacing/decommissioning equipment. 
Loving the app so far though, keep up the brilliant work!

**Comment by Myrskyvaris** [comment]
This would be great! I'm currently looking into open source/free contract management software, but if I could use Snipe-it that would be perfect.

**Comment by dowlingw** [comment]
Just circling back on this, I never managed to cut code towards this and have since moved roles - so no progress from my end and unlikely to see any in the near future - sorry guys.

Will definitely leave this feature request open though - definitely seems I wasn't alone on this one 👍
