### ISSUE TITLE
I got 500 Internal Error While Installing the Snipe-IT

### ISSUE THREAD

**Issue by 6sumitv96** [snipe/snipe-it#1189]
I use wamp server for install the Snipe-it in www folder,In Snipe-IT folder i install composer but when i am trying run that code i get 500 internal server error.I dont know where i have to give database connection and how i run this open source Snipe-IT in wamp server.

**Comment by 6sumitv96** [comment]
![image](https://cloud.githubusercontent.com/assets/14771141/10018371/ceae567c-6153-11e5-92d6-02b9d9639846.png)

**Comment by ddreier** [comment]
In your <snipe-it install dir>/app/config/production/app.php there is a "debug" option. Set that to true to get a more detailed error message.

**Comment by 6sumitv96** [comment]
Yes I try that also it's showing database is not connected,, where I have to mention database connection and how

**Comment by ddreier** [comment]
Sorry, I missed that. The "Edit Database Settings" section covers how to set up the database connection: http://docs.snipeitapp.com/installation/configuration.html.

**Comment by imie** [comment]
have you create database user and table in mysql ?

**Comment by 6sumitv96** [comment]
yes i have created database & connected also,please check the screen shot same error is shown on index.php.

![image](https://cloud.githubusercontent.com/assets/14771141/10036155/2689c602-61c1-11e5-86fd-c89a58fb702b.png)

**Comment by snipe** [comment]
As @ddreier mentioned, you have to set your debug option to true, as is detailed in the Getting Help documentation: http://docs.snipeitapp.com/getting-help.html

**Comment by 6sumitv96** [comment]
Yes its showing connection failed.

**Comment by snipe** [comment]
Please provide the specific error message. Paraphrasing isn't particularly helpful when trying to remotely debug someone's system.

**Comment by 6sumitv96** [comment]
hi please check 
![image](https://cloud.githubusercontent.com/assets/14771141/10036863/5888f20e-61cb-11e5-816a-48019b4c1eb1.png)

**Comment by snipe** [comment]
Looks like your database user is wrong in your database.php

**Comment by 6sumitv96** [comment]
ok, but i am trying to correct username  its how another error in database factory.php and how i will resolve this

**Comment by ddreier** [comment]
Another error, another screenshot. :)

**Comment by snipe** [comment]
@6sumitv96 " its how another error in database factory.php" <-- I don't know what that means

**Comment by 6sumitv96** [comment]
yup

**Comment by 6sumitv96** [comment]
ok i"ll try to make new database & then check once.
thanks

**Comment by 6sumitv96** [comment]
![image](https://cloud.githubusercontent.com/assets/14771141/10038531/013f5186-61e5-11e5-924e-5d7f2814d2d0.png)

**Comment by 6sumitv96** [comment]
i got an error of this.after creating new database with id, username & password.

**Comment by ddreier** [comment]
Looks like you're missing a table, and if you're missing one table you're probably missing them all.

http://docs.snipeitapp.com/installation/command-line.html

I recommend you give the whole set of install documentation a read before continuing.

**Comment by 6sumitv96** [comment]
can you please suggest that where i missed that table.

**Comment by snipe** [comment]
@6sumitv96 Did you run the `php artisan app:install` to set up your tables?

Also your DocumentRoot is incorrect. You should be pointing the DocumentRoot to the `public` directory. `public` should not be in the URL.

**Comment by 6sumitv96** [comment]
yes i run php artisan app:install to set up my tables.
and if i remove the public from url its shown folder not found.

**Comment by snipe** [comment]
"yes i run php artisan app:install to set up my tables." <-- did you get any errors? If the setup executed without errors, the settings table would have been created.

"and if i remove the public from url its shown folder not found." <-- that's because your DocumentRoot is not set to `public`.  http://docs.snipeitapp.com/installation/server/linux-osx.html
