### ISSUE TITLE
Feature Request: Add inventory date to asset

### ISSUE THREAD

**Issue by bailantilles** [snipe/snipe-it#1190]
For those of us that actually have to conduct a physical inventory of assets, it would be helpful if a date/time field was added to assets for the last time it was inventoried. 
##

**Comment by k-boy** [comment]
nice idea

**Comment by VanillaNinjaD** [comment]
YES!!

I've been searching for this issue for a while now, I knew someone had to have asked for this!

I'd love to add to the Bounty and work with the Dev team on the implementation on this feature since it would be a wonderful way to quickly verify the accuracy of the inventory.

**Comment by tekk45** [comment]
I too have a need for this function.

More specifically: from the "View Asset" view, preferably on the details tab, a button or link to verify the asset's information. Which will assign a timestamp and user ID of who performed the verification and give an optional space for a comment.

Such as: 
Last Inventoried by: Tekk45 @ 0945/2017-03-24
Inventory Comment: Found in Betsy's cabinet drawer

Additionally, an inventory report would be helpful too.

**Comment by VanillaNinjaD** [comment]
My mind has been running away with this Inventory Update / Reconciliation feature. This is what I'm chewing on right now...

When I originally implemented Snipe-IT, I scrubbed, cleaned and normalized approximately 1500 records/assets. Once this data was normalized and perfected, I was happy with the model names and manufacturer details but I had no way of ensuring the accuracy of the "status" they were assigned or the users the assets belonged to.

My dream is that the "Inventory Update" screen, that I have thrown together in this cruddy GIMP example, will allow my technicians to update all the computers in the field effortlessly by simply entering an Asset Tag into the box

![screen shot 2017-03-12 at 12 06 09 am](https://cloud.githubusercontent.com/assets/7405702/24298051/d8573b24-1072-11e7-8231-fb597a69fc63.png)

I visualize that in my department we will be constantly updating the "Last Seen Time".

For example, when the technicians are out in the field at an offsite location, they will use the "Inventory Update" screen to scan all of the asset barcode at the location and once each barcode has been scanned, the "Last Seen Date" will get updated with the current date and time. Then a simple report would allow me to identify which items have not been scanned/inventoried in the last "X" amount of days and allow me to send a technician hunting for a particular missing asset or simply email the user to bring their asset by the IT office and make sure it has the latest and greatest software updates and the inventory is still accurate.

This is just me spitballing but I think it will be an amazing addition to the software if we can make it a reality.

**Comment by tekk45** [comment]
@VanillaNinjaD I think your idea there would make a great "bulk inventory" feature. But I think something like that should be separate from the ability to individually search an asset and verify it.

**Comment by VanillaNinjaD** [comment]
I completely agree, are you thinking a button on the asset detail screen for this function?

**Comment by tekk45** [comment]
Yes, a button or a hyperlink was what I was thinking.
