### ISSUE TITLE
Add-On Request : PO and Invoice Number and date purchase

### ISSUE THREAD

**Issue by imie** [snipe/snipe-it#1191]
i would like to request an add on creating new assets and new license  to include PO number and PO date and also invoice number and invoice date as our warranty start on invoice date and not on delivery date.

![request2](https://cloud.githubusercontent.com/assets/2321338/10035478/42330632-61cd-11e5-9176-7f816e36c12e.JPG)

![request](https://cloud.githubusercontent.com/assets/2321338/10035423/8207dc7a-61cc-11e5-9667-6f502c5d6d28.jpg)

**Comment by snipe** [comment]
Wouldn't the purchase date *be* the PO date? There is no field tat deals with delivery date.

**Comment by imie** [comment]
im not sure the purchase date in the system is the purchase date for the order number. coz in license page, there is order number and purchase order number. in assets page, there is no purchase order number.

**Comment by imie** [comment]
there is mac address field rite, can we put another column for ip address ?

we use static ip address bind with assets mac address.

**Comment by snipe** [comment]
@imie custom fields are already in progress and would cover this.

**Comment by imie** [comment]
owh ok. thanks snipe.
