### ISSUE TITLE
Error when checking in asset - QueryException (42S22)

### ISSUE THREAD

**Issue by rp-tech** [snipe/snipe-it#1192]
Illuminate \ Database \ QueryException (42S22)

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'accepted' in 'field list' (SQL: update `assets` set `assigned_to` = , `updated_at` = 2015-09-23 18:03:21, `accepted` = where `id` = 130) 

Running v2.0.1

**Comment by snipe** [comment]
Did you run migrations?

**Comment by rp-tech** [comment]
When attempting to run the migration I get the following error:


  [Illuminate\Database\QueryException]
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'asset_maint
  enances' already exists (SQL: create table `asset_maintenances` (`id` int u
  nsigned not null auto_increment primary key, `asset_id` int unsigned not nu
  ll, `supplier_id` int unsigned not null, `asset_maintenance_type` enum('Mai
  ntenance', 'Repair', 'Upgrade') not null, `title` varchar(100) not null, `i
  s_warranty` tinyint(1) not null, `start_date` date not null, `completion_da
  te` date null, `asset_maintenance_time` int null, `notes` longtext null, `c
  ost` decimal(10, 2) null, `deleted_at` datetime null, `created_at` timestam
  p default 0 not null, `updated_at` timestamp default 0 not null) default ch
  aracter set utf8 collate utf8_unicode_ci)






  [PDOException]
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'asset_maint
  enances' already exists

**Comment by snipe** [comment]
Can you show me the contents of your `migrations` table?

**Comment by rp-tech** [comment]
![migrations](https://cloud.githubusercontent.com/assets/10659713/10054136/78aa3822-61e4-11e5-8d1f-6753c3dc569c.png)

**Comment by snipe** [comment]
I need the contents, not the structure.

**Comment by rp-tech** [comment]
+-------------------------------------------------------------------------+-----                                                                                        --+
| migration                                                               | batc                                                                                        h |
+-------------------------------------------------------------------------+-----                                                                                        --+
| 2012_12_06_225921_migration_cartalyst_sentry_install_users              |                                                                                             1 |
| 2012_12_06_225929_migration_cartalyst_sentry_install_groups             |                                                                                             1 |
| 2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot |                                                                                             1 |
| 2012_12_06_225988_migration_cartalyst_sentry_install_throttle           |                                                                                             1 |
| 2013_03_23_193214_update_users_table                                    |                                                                                             2 |
| 2013_11_13_075318_create_models_table                                   |                                                                                             2 |
| 2013_11_13_075335_create_categories_table                               |                                                                                             2 |
| 2013_11_13_075347_create_manufacturers_table                            |                                                                                             2 |
| 2013_11_15_015858_add_user_id_to_categories                             |                                                                                             2 |
| 2013_11_15_112701_add_user_id_to_manufacturers                          |                                                                                             2 |
| 2013_11_15_190327_create_assets_table                                   |                                                                                             2 |
| 2013_11_15_190357_create_licenses_table                                 |                                                                                             2 |
| 2013_11_15_201848_add_license_name_to_licenses                          |                                                                                             2 |
| 2013_11_16_040323_create_depreciations_table                            |                                                                                             2 |
| 2013_11_16_042851_add_depreciation_id_to_models                         |                                                                                             2 |
| 2013_11_16_084923_add_user_id_to_models                                 |                                                                                             2 |
| 2013_11_16_103258_create_locations_table                                |                                                                                             2 |
| 2013_11_16_103336_add_location_id_to_assets                             |                                                                                             2 |
| 2013_11_16_103407_add_checkedout_to_to_assets                           |                                                                                             2 |
| 2013_11_16_103425_create_history_table                                  |                                                                                             2 |
| 2013_11_17_054359_drop_licenses_table                                   |                                                                                             2 |
| 2013_11_17_054526_add_physical_to_assets                                |                                                                                             2 |
| 2013_11_17_055126_create_settings_table                                 |                                                                                             2 |
| 2013_11_17_062634_add_license_to_assets                                 |                                                                                             2 |
| 2013_11_18_134332_add_contacts_to_users                                 |                                                                                             2 |
| 2013_11_18_142847_add_info_to_locations                                 |                                                                                             2 |
| 2013_11_18_152942_remove_location_id_from_asset                         |                                                                                             2 |
| 2013_11_18_164423_set_nullvalues_for_user                               |                                                                                             2 |
| 2013_11_19_013337_create_asset_logs_table                               |                                                                                             2 |
| 2013_11_19_061409_edit_added_on_asset_logs_table                        |                                                                                             2 |
| 2013_11_19_062250_edit_location_id_asset_logs_table                     |                                                                                             2 |
| 2013_11_20_055822_add_soft_delete_on_assets                             |                                                                                             2 |
| 2013_11_20_121404_add_soft_delete_on_locations                          |                                                                                             2 |
| 2013_11_20_123137_add_soft_delete_on_manufacturers                      |                                                                                             2 |
| 2013_11_20_123725_add_soft_delete_on_categories                         |                                                                                             2 |
| 2013_11_20_130248_create_status_labels                                  |                                                                                             2 |
| 2013_11_20_130830_add_status_id_on_assets_table                         |                                                                                             2 |
| 2013_11_20_131544_add_status_type_on_status_labels                      |                                                                                             2 |
| 2013_11_20_134103_add_archived_to_assets                                |                                                                                             2 |
| 2013_11_21_002321_add_uploads_table                                     |                                                                                             2 |
| 2013_11_21_024531_remove_deployable_boolean_from_status_labels          |                                                                                             2 |
| 2013_11_22_075308_add_option_label_to_settings_table                    |                                                                                             2 |
| 2013_11_22_213400_edits_to_settings_table                               |                                                                                             2 |
| 2013_11_25_013244_create_licenses_table                                 |                                                                                             2 |
| 2013_11_25_031458_create_license_seats_table                            |                                                                                             2 |
| 2013_11_25_032022_add_type_to_actionlog_table                           |                                                                                             2 |
| 2013_11_25_033008_delete_bad_licenses_table                             |                                                                                             2 |
| 2013_11_25_033131_create_new_licenses_table                             |                                                                                             2 |
| 2013_11_25_033534_add_licensed_to_licenses_table                        |                                                                                             2 |
| 2013_11_25_101308_add_warrantee_to_assets_table                         |                                                                                             2 |
| 2013_11_25_104343_alter_warranty_column_on_assets                       |                                                                                             2 |
| 2013_11_25_150450_drop_parent_from_categories                           |                                                                                             2 |
| 2013_11_25_151920_add_depreciate_to_assets                              |                                                                                             2 |
| 2013_11_25_152903_add_depreciate_to_licenses_table                      |                                                                                             2 |
| 2013_11_26_211820_drop_license_from_assets_table                        |                                                                                             2 |
| 2013_11_27_062510_add_note_to_asset_logs_table                          |                                                                                             2 |
| 2013_12_01_113426_add_filename_to_asset_log                             |                                                                                             2 |
| 2013_12_06_094618_add_nullable_to_licenses_table                        |                                                                                             2 |
| 2013_12_10_084038_add_eol_on_models_table                               |                                                                                             2 |
| 2013_12_12_055218_add_manager_to_users_table                            |                                                                                             2 |
| 2014_01_28_031200_add_qr_code_to_settings_table                         |                                                                                             2 |
| 2014_02_13_183016_add_qr_text_to_settings_table                         |                                                                                             2 |
| 2014_05_24_093839_alter_default_license_depreciation_id                 |                                                                                             2 |
| 2014_05_27_231658_alter_default_values_licenses                         |                                                                                             2 |
| 2014_06_19_191508_add_asset_name_to_settings                            |                                                                                             2 |
| 2014_06_20_004847_make_asset_log_checkedout_to_nullable                 |                                                                                             2 |
| 2014_06_20_005050_make_asset_log_purchasedate_to_nullable               |                                                                                             2 |
| 2014_06_24_003011_add_suppliers                                         |                                                                                             2 |
| 2014_06_24_010742_add_supplier_id_to_asset                              |                                                                                             2 |
| 2014_06_24_012839_add_zip_to_supplier                                   |                                                                                             2 |
| 2014_06_24_033908_add_url_to_supplier                                   |                                                                                             2 |
| 2014_07_08_054116_add_employee_id_to_users                              |                                                                                             2 |
| 2014_07_09_134316_add_requestable_to_assets                             |                                                                                             2 |
| 2014_07_17_085822_add_asset_to_software                                 |                                                                                             2 |
| 2014_07_17_161625_make_asset_id_in_logs_nullable                        |                                                                                             2 |
| 2014_08_12_053504_alpha_0_4_2_release                                   |                                                                                             2 |
| 2014_08_17_083523_make_location_id_nullable                             |                                                                                             2 |
| 2014_10_16_200626_add_rtd_location_to_assets                            |                                                                                             2 |
| 2014_10_24_000417_alter_supplier_state_to_32                            |                                                                                             2 |
| 2014_10_24_015641_add_display_checkout_date                             |                                                                                             2 |
| 2014_10_28_222654_add_avatar_field_to_users_table                       |                                                                                             2 |
| 2014_10_29_045924_add_image_field_to_models_table                       |                                                                                             2 |
| 2014_11_01_214955_add_eol_display_to_settings                           |                                                                                             2 |
| 2014_11_04_231416_update_group_field_for_reporting                      |                                                                                             2 |
| 2014_11_05_212408_add_fields_to_licenses                                |                                                                                             2 |
| 2014_11_07_021042_add_image_to_supplier                                 |                                                                                             2 |
| 2014_11_20_203007_add_username_to_user                                  |                                                                                             2 |
| 2014_11_20_223947_add_auto_to_settings                                  |                                                                                             2 |
| 2014_11_20_224421_add_prefix_to_settings                                |                                                                                             2 |
| 2014_11_21_104401_change_licence_type                                   |                                                                                             2 |
| 2014_12_09_082500_add_fields_maintained_term_to_licenses                |                                                                                             2 |
| 2015_02_04_155757_increase_user_field_lengths                           |                                                                                             3 |
| 2015_02_07_013537_add_soft_deleted_to_log                               |                                                                                             3 |
| 2015_02_10_040958_fix_bad_assigned_to_ids                               |                                                                                             3 |
| 2015_02_10_053310_migrate_data_to_new_statuses                          |                                                                                             3 |
| 2015_02_11_044104_migrate_make_license_assigned_null                    |                                                                                             3 |
| 2015_02_11_104406_migrate_create_requests_table                         |                                                                                             3 |
| 2015_02_12_001312_add_mac_address_to_asset                              |                                                                                             3 |
| 2015_02_12_024100_change_license_notes_type                             |                                                                                             3 |
| 2015_02_17_231020_add_localonly_to_settings                             |                                                                                             3 |
| 2015_02_19_222322_add_logo_and_colors_to_settings                       |                                                                                             3 |
| 2015_02_24_072043_add_alerts_to_settings                                |                                                                                             3 |
| 2015_02_25_022931_add_eula_fields                                       |                                                                                             3 |
| 2015_02_25_204513_add_accessories_table                                 |                                                                                             3 |
| 2015_02_26_091228_add_accessories_user_table                            |                                                                                             3 |
| 2015_02_26_115128_add_deleted_at_models                                 |                                                                                             3 |
| 2015_02_26_233005_add_category_type                                     |                                                                                             3 |
| 2015_03_01_231912_update_accepted_at_to_acceptance_id                   |                                                                                             4 |
| 2015_03_05_011929_add_qr_type_to_settings                               |                                                                                             4 |
| 2015_03_18_055327_add_note_to_user                                      |                                                                                             4 |
| 2015_04_29_234704_add_slack_to_settings                                 |                                                                                             4 |
| 2015_05_04_085151_add_parent_id_to_locations_table                      |                                                                                             5 |
| 2015_05_22_124421_add_reassignable_to_licenses                          |                                                                                             5 |
| 2015_06_10_003314_fix_default_for_user_notes                            |                                                                                             5 |
| 2015_06_10_003554_create_consumables                                    |                                                                                             5 |
| 2015_06_15_183253_move_email_to_username                                |                                                                                             5 |
| 2015_06_23_070346_make_email_nullable                                   |                                                                                             5 |
| 2015_07_09_014359_add_currency_to_settings_and_locations                |                                                                                             5 |
+-------------------------------------------------------------------------+-----                                                                                        --+

**Comment by snipe** [comment]
Backup your database, and then add `2015_06_26_213716_create_asset_maintenances_table` with a batch of `5` into your migrations table, then re-run migrations

**Comment by rp-tech** [comment]
Sorry I am a total mysql noob. At the risk of sounding like a total idiot can you please give me the command for this? (already got the backup portion i know that much about mysql)

**Comment by snipe** [comment]
You're using PHPMyAdmin - you can just add the values there, you don't need the SQL

**Comment by rp-tech** [comment]
This time I get

  [ErrorException]
  Creating default object from empty value

**Comment by rp-tech** [comment]
Re-ran the migration, now I get

  [Illuminate\Database\QueryException]
  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'thread_id' (SQL: alter table `asset_logs` add `thread_id` int null)

  [PDOException]
  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'thread_id'

**Comment by snipe** [comment]
Let me see your migrations table content again please

**Comment by rp-tech** [comment]
+-------------------------------------------------------------------------+-------+
| migration                                                               | batch |
+-------------------------------------------------------------------------+-------+
| 2012_12_06_225921_migration_cartalyst_sentry_install_users              |     1 |
| 2012_12_06_225929_migration_cartalyst_sentry_install_groups             |     1 |
| 2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot |     1 |
| 2012_12_06_225988_migration_cartalyst_sentry_install_throttle           |     1 |
| 2013_03_23_193214_update_users_table                                    |     2 |
| 2013_11_13_075318_create_models_table                                   |     2 |
| 2013_11_13_075335_create_categories_table                               |     2 |
| 2013_11_13_075347_create_manufacturers_table                            |     2 |
| 2013_11_15_015858_add_user_id_to_categories                             |     2 |
| 2013_11_15_112701_add_user_id_to_manufacturers                          |     2 |
| 2013_11_15_190327_create_assets_table                                   |     2 |
| 2013_11_15_190357_create_licenses_table                                 |     2 |
| 2013_11_15_201848_add_license_name_to_licenses                          |     2 |
| 2013_11_16_040323_create_depreciations_table                            |     2 |
| 2013_11_16_042851_add_depreciation_id_to_models                         |     2 |
| 2013_11_16_084923_add_user_id_to_models                                 |     2 |
| 2013_11_16_103258_create_locations_table                                |     2 |
| 2013_11_16_103336_add_location_id_to_assets                             |     2 |
| 2013_11_16_103407_add_checkedout_to_to_assets                           |     2 |
| 2013_11_16_103425_create_history_table                                  |     2 |
| 2013_11_17_054359_drop_licenses_table                                   |     2 |
| 2013_11_17_054526_add_physical_to_assets                                |     2 |
| 2013_11_17_055126_create_settings_table                                 |     2 |
| 2013_11_17_062634_add_license_to_assets                                 |     2 |
| 2013_11_18_134332_add_contacts_to_users                                 |     2 |
| 2013_11_18_142847_add_info_to_locations                                 |     2 |
| 2013_11_18_152942_remove_location_id_from_asset                         |     2 |
| 2013_11_18_164423_set_nullvalues_for_user                               |     2 |
| 2013_11_19_013337_create_asset_logs_table                               |     2 |
| 2013_11_19_061409_edit_added_on_asset_logs_table                        |     2 |
| 2013_11_19_062250_edit_location_id_asset_logs_table                     |     2 |
| 2013_11_20_055822_add_soft_delete_on_assets                             |     2 |
| 2013_11_20_121404_add_soft_delete_on_locations                          |     2 |
| 2013_11_20_123137_add_soft_delete_on_manufacturers                      |     2 |
| 2013_11_20_123725_add_soft_delete_on_categories                         |     2 |
| 2013_11_20_130248_create_status_labels                                  |     2 |
| 2013_11_20_130830_add_status_id_on_assets_table                         |     2 |
| 2013_11_20_131544_add_status_type_on_status_labels                      |     2 |
| 2013_11_20_134103_add_archived_to_assets                                |     2 |
| 2013_11_21_002321_add_uploads_table                                     |     2 |
| 2013_11_21_024531_remove_deployable_boolean_from_status_labels          |     2 |
| 2013_11_22_075308_add_option_label_to_settings_table                    |     2 |
| 2013_11_22_213400_edits_to_settings_table                               |     2 |
| 2013_11_25_013244_create_licenses_table                                 |     2 |
| 2013_11_25_031458_create_license_seats_table                            |     2 |
| 2013_11_25_032022_add_type_to_actionlog_table                           |     2 |
| 2013_11_25_033008_delete_bad_licenses_table                             |     2 |
| 2013_11_25_033131_create_new_licenses_table                             |     2 |
| 2013_11_25_033534_add_licensed_to_licenses_table                        |     2 |
| 2013_11_25_101308_add_warrantee_to_assets_table                         |     2 |
| 2013_11_25_104343_alter_warranty_column_on_assets                       |     2 |
| 2013_11_25_150450_drop_parent_from_categories                           |     2 |
| 2013_11_25_151920_add_depreciate_to_assets                              |     2 |
| 2013_11_25_152903_add_depreciate_to_licenses_table                      |     2 |
| 2013_11_26_211820_drop_license_from_assets_table                        |     2 |
| 2013_11_27_062510_add_note_to_asset_logs_table                          |     2 |
| 2013_12_01_113426_add_filename_to_asset_log                             |     2 |
| 2013_12_06_094618_add_nullable_to_licenses_table                        |     2 |
| 2013_12_10_084038_add_eol_on_models_table                               |     2 |
| 2013_12_12_055218_add_manager_to_users_table                            |     2 |
| 2014_01_28_031200_add_qr_code_to_settings_table                         |     2 |
| 2014_02_13_183016_add_qr_text_to_settings_table                         |     2 |
| 2014_05_24_093839_alter_default_license_depreciation_id                 |     2 |
| 2014_05_27_231658_alter_default_values_licenses                         |     2 |
| 2014_06_19_191508_add_asset_name_to_settings                            |     2 |
| 2014_06_20_004847_make_asset_log_checkedout_to_nullable                 |     2 |
| 2014_06_20_005050_make_asset_log_purchasedate_to_nullable               |     2 |
| 2014_06_24_003011_add_suppliers                                         |     2 |
| 2014_06_24_010742_add_supplier_id_to_asset                              |     2 |
| 2014_06_24_012839_add_zip_to_supplier                                   |     2 |
| 2014_06_24_033908_add_url_to_supplier                                   |     2 |
| 2014_07_08_054116_add_employee_id_to_users                              |     2 |
| 2014_07_09_134316_add_requestable_to_assets                             |     2 |
| 2014_07_17_085822_add_asset_to_software                                 |     2 |
| 2014_07_17_161625_make_asset_id_in_logs_nullable                        |     2 |
| 2014_08_12_053504_alpha_0_4_2_release                                   |     2 |
| 2014_08_17_083523_make_location_id_nullable                             |     2 |
| 2014_10_16_200626_add_rtd_location_to_assets                            |     2 |
| 2014_10_24_000417_alter_supplier_state_to_32                            |     2 |
| 2014_10_24_015641_add_display_checkout_date                             |     2 |
| 2014_10_28_222654_add_avatar_field_to_users_table                       |     2 |
| 2014_10_29_045924_add_image_field_to_models_table                       |     2 |
| 2014_11_01_214955_add_eol_display_to_settings                           |     2 |
| 2014_11_04_231416_update_group_field_for_reporting                      |     2 |
| 2014_11_05_212408_add_fields_to_licenses                                |     2 |
| 2014_11_07_021042_add_image_to_supplier                                 |     2 |
| 2014_11_20_203007_add_username_to_user                                  |     2 |
| 2014_11_20_223947_add_auto_to_settings                                  |     2 |
| 2014_11_20_224421_add_prefix_to_settings                                |     2 |
| 2014_11_21_104401_change_licence_type                                   |     2 |
| 2014_12_09_082500_add_fields_maintained_term_to_licenses                |     2 |
| 2015_02_04_155757_increase_user_field_lengths                           |     3 |
| 2015_02_07_013537_add_soft_deleted_to_log                               |     3 |
| 2015_02_10_040958_fix_bad_assigned_to_ids                               |     3 |
| 2015_02_10_053310_migrate_data_to_new_statuses                          |     3 |
| 2015_02_11_044104_migrate_make_license_assigned_null                    |     3 |
| 2015_02_11_104406_migrate_create_requests_table                         |     3 |
| 2015_02_12_001312_add_mac_address_to_asset                              |     3 |
| 2015_02_12_024100_change_license_notes_type                             |     3 |
| 2015_02_17_231020_add_localonly_to_settings                             |     3 |
| 2015_02_19_222322_add_logo_and_colors_to_settings                       |     3 |
| 2015_02_24_072043_add_alerts_to_settings                                |     3 |
| 2015_02_25_022931_add_eula_fields                                       |     3 |
| 2015_02_25_204513_add_accessories_table                                 |     3 |
| 2015_02_26_091228_add_accessories_user_table                            |     3 |
| 2015_02_26_115128_add_deleted_at_models                                 |     3 |
| 2015_02_26_233005_add_category_type                                     |     3 |
| 2015_03_01_231912_update_accepted_at_to_acceptance_id                   |     4 |
| 2015_03_05_011929_add_qr_type_to_settings                               |     4 |
| 2015_03_18_055327_add_note_to_user                                      |     4 |
| 2015_04_29_234704_add_slack_to_settings                                 |     4 |
| 2015_05_04_085151_add_parent_id_to_locations_table                      |     5 |
| 2015_05_22_124421_add_reassignable_to_licenses                          |     5 |
| 2015_06_10_003314_fix_default_for_user_notes                            |     5 |
| 2015_06_10_003554_create_consumables                                    |     5 |
| 2015_06_15_183253_move_email_to_username                                |     5 |
| 2015_06_23_070346_make_email_nullable                                   |     5 |
| 2015_07_09_014359_add_currency_to_settings_and_locations                |     5 |
| 2015_06_26_213716_create_asset_maintenances_table                       |     5 |
| 2015_07_21_122022_add_expected_checkin_date_to_asset_logs               |     6 |
| 2015_07_24_093845_add_checkin_email_to_category_table                   |     6 |
| 2015_07_25_055415_remove_email_unique_constraint                        |     6 |
+-------------------------------------------------------------------------+-------+

**Comment by snipe** [comment]
Okay, add `2015_07_29_230054_add_thread_id_to_asset_logs_table` with a batch of `6` and then re-run migrations

**Comment by rp-tech** [comment]
Migration was successful this time - no errors.

and... drum roll..

SUCCESS - assets checked in successfully!

You *are* AWESOME!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

thank you sooooooooo much!

**Comment by snipe** [comment]
![cat five](https://cloud.githubusercontent.com/assets/197404/10055564/d464e7d2-61eb-11e5-88be-7ec2a4b591b4.gif)
