### ISSUE TITLE
Barcode image generation and barcode integration

### ISSUE THREAD

**Issue by psychfox** [snipe/snipe-it#1193]
Hi Snipe,

This project of yours is really awesome.  I have a request if possible to generate a barcode image (code 39 and others on the report output? or generate barcode of all assets so we can create the sticker tag?

also will it be possible to just scan the sticker asset code using a barcode scanner (search feature) then display the information of the scanned asset?

Thank you and hoping for this features in the next release. :+1: :+1: :+1: :100:

**Comment by snipe** [comment]
Is this somehow different than the labels we already generate? http://docs.snipeitapp.com/manual/labels.html

**Comment by psychfox** [comment]
Hi Snipe,

thank you for that quick response..that was awesome! ..

wonder if its something like this. :)  Top is  the name of company user "Property of User/Company"
then below is the barcode and asset tag. Sample is attached :) 

Thanks much.. btw, where can i donate?

![sample asset](https://cloud.githubusercontent.com/assets/14256581/10065037/5bf2b942-62b2-11e5-8539-5027f25780e4.png)

**Comment by snipe** [comment]
This is what our barcodes look like, depending on what kind of barcode you select from the Admin > Settings menu.

<img width="719" alt="screen shot 2015-09-20 at 11 12 56 pm" src="https://cloud.githubusercontent.com/assets/197404/10065059/02e1b59c-6235-11e5-8c72-1bfaec6de4ed.png">

**Comment by snipe** [comment]
<img width="841" alt="screen shot 2015-09-23 at 8 53 07 pm" src="https://cloud.githubusercontent.com/assets/197404/10065074/4a2b66d2-6235-11e5-899c-217d4e0aa9a5.png">
<img width="703" alt="screen shot 2015-09-23 at 8 53 38 pm" src="https://cloud.githubusercontent.com/assets/197404/10065075/4a2f1250-6235-11e5-9bbf-b2fba66c5309.png">

**Comment by psychfox** [comment]
Alright. that was sweet! sorry still exploring the app fully.. my bad.. but this is really a good software.

are these barcode images possibly be added on the report as well? can you teach me how to do it? 

Thanks a lot for the fast response..

Btw, how do i help ? i want to donate some for this project. how can i do it?

**Comment by snipe** [comment]
Thanks for the kind words. I'm not sure how we'd add them to the reports, since they're much larger than the single row of text per asset. I can chew on that for a bit though. 

Donations are gladly accepted :) You can do so here: https://snipeitapp.com/donate/ - Or if you have a ChangeTip account, you can donate in the comments here just by saying `@ChangeTip, send $x to @snipe!`

**Comment by snipe** [comment]
(Actually, the change tip thing might only work on PRs and commits - not sure tho)

**Comment by psychfox** [comment]
Okay. sure would gladly donate.

**Comment by snipe** [comment]
![thank-you](https://cloud.githubusercontent.com/assets/197404/10065355/6cb7c282-6239-11e5-8fd9-bc066ea23fad.gif)

**Comment by lategreat** [comment]
Hi I'm just getting started with snipe-it but I'm looking at using NFC tags with the system, I know it integrates with most barcode scanners but does it support NFC readers as well. or would I need to do a work around by generating the QR code address and programing the NFC to go to that address?
