### ISSUE TITLE
Asset Maintenance notes on view asset page

### ISSUE THREAD

**Issue by modernknight** [snipe/snipe-it#1194]
Good morning/afternoon!!

Loving the new updates! Every time this program gets better and better! I was looking through the new version and saw that when we view an asset, the Asset Maintenances appears, but we can only see "Supplier Name," "Asset Maintenance Type," "Start Date," "Completion Date," "Warranty," "Cost," and "Actions." Is there any way of getting the maintenance notes to show up as well so we are able to see what was actually done in our maintenance? At least in my job, I don't see the Supplier Name being of any use.

As we were looking at all of these new features, it is NEARLY perfect, except for this one part, for using at our school.

Thanks again, and keep up the great work!!
##

**Comment by snipe** [comment]
That's already a cramped table on my 13" laptop. I'll need to figure out how to lay out that page better so everything fits.

**Comment by snipe** [comment]
Would the title not be sufficient for this?
