### ISSUE TITLE
Ability to print QRcodes in bulk

### ISSUE THREAD

**Issue by pcmerc** [snipe/snipe-it#1195]
Ability to print QRcodes in bulk by selecting individuals or groups of assets to print.

**Comment by snipe** [comment]
Can you not use the asset search to filter on individual and just select the assets in the results?

**Comment by pcmerc** [comment]
Right you are, thanks, Snipe! :D

**Comment by snipe** [comment]
![brilliant](https://cloud.githubusercontent.com/assets/197404/10143986/042f1306-65d0-11e5-9e93-56e71a2da542.gif)
