### ISSUE TITLE
Feature Request: Change columns in license view

### ISSUE THREAD

**Issue by ebjers** [snipe/snipe-it#1196]
Is it possible to add the Licensed to Name to the show/hid columns button on the license page?

**Comment by snipe** [comment]
Do you mean on the list view, or the license detail view?

**Comment by ebjers** [comment]
List view
[image: license.jpg]

**Comment by snipe** [comment]
Well, the problem is that on the list page, there are multiple numbers of seats associated with each license, so there wouldn't just be one person in many scenarios. We used to have the licenses expanded, but it became unwieldy for licenses with many seats.

**Comment by ebjers** [comment]
I'm referring to this field when you create a license
[image: license 2.jpg]

Another, and probably better, option would be to add a location field to
the license module like you have in other assets... but I assume this would
take more coding and database modifications.

**Comment by snipe** [comment]
You can't email screenshots or images to Github, you have to use the web interface :(

**Comment by ebjers** [comment]
Sorry was not aware of that... this is all new to me
![license 2](https://cloud.githubusercontent.com/assets/14800911/10094078/cfc617d4-638d-11e5-87d0-e272871c2b8a.jpg)
