### ISSUE TITLE
Feature Request: File uploads

### ISSUE THREAD

**Issue by ebjers** [snipe/snipe-it#1197]
It would be great to have the ability to upload files to licenses or add a field to the license module that can point to a file location.  Some software requires key files instead of serial numbers so this would make tracking these licenses easier.

**Comment by snipe** [comment]
Is this different than the file upload that's already implemented? 

<img width="783" alt="screen shot 2015-09-24 at 10 12 21 pm" src="https://cloud.githubusercontent.com/assets/197404/10093587/652fa7f2-6309-11e5-8b70-33a9472ba165.png">

**Comment by ebjers** [comment]
No I did not see that, it is exactly what I was looking for.  Thank you
very much for your prompt reply.

**Comment by snipe** [comment]
![dr-who-thumbs-up](https://cloud.githubusercontent.com/assets/197404/10093637/12021078-630a-11e5-84d0-f73bc2c555bc.gif)
