### ISSUE TITLE
Site / page won't open

### ISSUE THREAD

**Issue by djsteady** [snipe/snipe-it#1199]
Snipe version 2.0.3
Windows Server 2012 R2
Successfully installed and updated all things in the install doco
This site is actually running as a folder in my main site and not as the root website
I get a page not found when browsing to the www.mysite.com/snipe 
I've done the virtual config as well

**Comment by snipe** [comment]
Can we see your server configs?

**Comment by djsteady** [comment]
What would you like

**Comment by djsteady** [comment]
This is the site as well http://www.casit.com.au/tsi-asset/

**Comment by snipe** [comment]
We need to see your server settings.

**Comment by djsteady** [comment]
As in IIS, sorry Snipe, I know I must be frustrating, i'm not sure exactly what you want. Is it log files.

**Comment by djsteady** [comment]
![error](https://cloud.githubusercontent.com/assets/7933772/10102049/c520df56-63df-11e5-8808-5d2c8dea00bc.jpg)

**Comment by djsteady** [comment]
![error1](https://cloud.githubusercontent.com/assets/7933772/10102738/730c1d44-63e3-11e5-8473-ef6ba129059d.jpg)

**Comment by djsteady** [comment]
OK, i'll guess what info you need
server 2012 R2
PHP 5.4
MySQL 5.1
Snipe IT 2.0.3
Composer Install went through ok
Composer update went through ok
php artisan app:install --env=production went through ok

**Comment by djsteady** [comment]
Also made the change to .htaccess to add RewriteBase /tsi-asset
As this is an IIS server, do I make the folder a virtual directory

**Comment by djsteady** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7933772/10103855/aceba25e-63e9-11e5-901d-c0c0f377435b.jpg)

**Comment by snipe** [comment]
Why are you doing `composer update` instead of `composer install`? Your lock file may end up being out of step with ours, which could lead to weirdness.

Can you show me the rest of the imported rewrite rules? 

Also show me the site settings in IIS.

It looks like it's hitting the app - notice how the url redirects when you go to it in a browser? It redirects you from http://www.casit.com.au/tsi-asset to http://www.casit.com.au/tsi-asset/auth/signin.

**Comment by snipe** [comment]
Also, it looks like your RewriteBase directive won't work - your screenshot shows it as being unsupported

**Comment by snipe** [comment]
Looks like the problem is in your rewrite rules.

http://www.casit.com.au/tsi-asset/index.php/auth/forgot-password
http://www.casit.com.au/tsi-asset/index.php/auth/signin

Those are returning "correctly" (no style sheets tho).

**Comment by snipe** [comment]
This may also be helpful. http://laravel-tricks.com/tricks/laravel-41-in-windows-server-iis

I don't use IIS much, so I'm not sure what other advice to give you. Maybe @madd15 can help.
