### ISSUE TITLE
A user (non-admin) should be able to request an asset [$15]

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#12]
They will have to be registered and logged in, but they can then reserve assets like set devices, etc.

**Comment by Freaksed** [comment]
it would be nice if deployed assets dont show in the requestable list either

**Comment by snipe** [comment]
@Freaksed excellent suggestion

**Comment by uberbrady** [comment]
Maybe 'requestable' should be a particular category attribute? Some assets might be requestable - like a projector, to borrow - but some assets might not - I can't request the brand new Gold MacBook that's in inventory; those just get assigned to executives...?

**Comment by snipe** [comment]
@uberbrady Right now, requestable is a per-asset attribute. For example, you may have some devices that are set up as test devices, where they wouldn't need a separate category (laptop is still a laptop), but are specific to a machine (laptop has a particular version of a particular browser or OS, for example).
