### ISSUE TITLE
Artisan error: Undefined index:

### ISSUE THREAD

**Issue by Seema-agarwal** [snipe/snipe-it#1201]
cant seem to resolve the following
> php artisan optimize
{"error":{"type":"ErrorException","message":"Undefined index: Asia\/Kolkata","file":"C:\\inetpub\\wwwroot\\Snipe-it\\vendor\\laravel\\framework\\src\\
Illuminate\\Foundation\\start.php","line":167}}

**Comment by Seema-agarwal** [comment]
My app/config dir looks:-

app.php
auth.php
cache.php
compile.php
database.php
local
packages
permissions.php
production
queue.php
remote.php
session.php
staging
testing
travis-ci
version.php
view.php
workbench.php

**Comment by snipe** [comment]
Why are you running that command?

**Comment by Seema-agarwal** [comment]
Sorry was away on tour.
I am a novice and was following the instructions on the documentation site. I had actually run the following when I got the error;-
C:\inetpub\wwwroot\Snipe-it>php artisan app:install --env=production
{"error":{"type":"ErrorException","message":"Undefined index: Asia\/Kolkata","file":"C:\\inetpub\\wwwroot\\Snipe-it\\vendor\\laravel\\framework\\src\\
Illuminate\\Foundation\\start.php","line":167}}
Then read a lot of issues on your and was trying to run the artisan optimise command as per advice on some ones comment.

I have been unable to  install snipe-It fora long time.I hope you will be able to teach me how to put it up and running.

**Comment by snipe** [comment]
Can you show me what's in your `app/config/app.php` file?

**Comment by Seema-agarwal** [comment]
<?php

return array(
   /*
    |--------------------------------------------------------------------------
    | Application Debug Mode
    |--------------------------------------------------------------------------
    |
    | When your application is in debug mode, detailed error messages with
    | stack traces will be shown on every error that occurs within your
    | application. If disabled, a simple generic error page is shown.
    |
    */

    'debug' => true,

    /*
    |--------------------------------------------------------------------------
    | Application URL
    |--------------------------------------------------------------------------
    |
    | This URL is used by the console to properly generate URLs when using
    | the Artisan command line tool. You should set this to the root of
    | your application so that it is used when running Artisan tasks.
    |
    */

    'url' => 'http://localhost',


    /*
    |--------------------------------------------------------------------------
    | Application Timezone
    |--------------------------------------------------------------------------
    |
    | Here you may specify the default timezone for your application, which
    | will be used by the PHP date and date-time functions. We have gone
    | ahead and set this to a sensible default for you out of the box.
    |
    */

    'timezone' => 'Asia/Kolkata',

    /*
    |--------------------------------------------------------------------------
    | Application Locale
    |--------------------------------------------------------------------------
    |
    | This locale ties into the languaage files in app/lang, which contain the
    | language files for each translation.
    |
    */

    'locale' => 'en',

    /*
    |--------------------------------------------------------------------------
    | Autoloaded Service Providers
    |--------------------------------------------------------------------------
    |
    | This setting may be used to control the default cipher used by the Laravel
    | encryption facilities.
    |
    | Note: In Laravel 4.2, the default cipher is MCRYPT_RIJNDAEL_128 (AES),
    | which is considered to be the most secure cipher. Changing the cipher
    | back to MCRYPT_RIJNDAEL_256 is required to decrypt cookies/values that
    | were encrypted in Laravel <= 4.1
    |
    */

    'cipher' => MCRYPT_RIJNDAEL_256,

    /*
    |--------------------------------------------------------------------------
    | Prevent Password changes
    |--------------------------------------------------------------------------
    |
    | If for some reason you do not wish for admins to be able to edit the password
    | for any user (including themselves), set this to true.
    |
    */

    'lock_passwords' => false,



    /*
    |--------------------------------------------------------------------------
    | Autoloaded Service Providers
    |--------------------------------------------------------------------------
    |
    | The service providers listed here will be automatically loaded on the
    | request to your application. Feel free to add your own services to
    | this array to grant expanded functionality to your applications.
    |
    */


    'providers' => array(

        'Illuminate\Foundation\Providers\ArtisanServiceProvider',
        'Illuminate\Auth\AuthServiceProvider',
        'Illuminate\Cache\CacheServiceProvider',
        'Illuminate\Session\CommandsServiceProvider',
        'Illuminate\Foundation\Providers\ConsoleSupportServiceProvider',
        'Illuminate\Routing\ControllerServiceProvider',
        'Illuminate\Cookie\CookieServiceProvider',
        'Illuminate\Database\DatabaseServiceProvider',
        'Illuminate\Encryption\EncryptionServiceProvider',
        'Illuminate\Filesystem\FilesystemServiceProvider',
        'Illuminate\Hashing\HashServiceProvider',
        'Illuminate\Html\HtmlServiceProvider',
        'Illuminate\Log\LogServiceProvider',
        'Illuminate\Mail\MailServiceProvider',
        'Illuminate\Database\MigrationServiceProvider',
        'Illuminate\Pagination\PaginationServiceProvider',
        'Illuminate\Queue\QueueServiceProvider',
        'Illuminate\Redis\RedisServiceProvider',
        'Illuminate\Remote\RemoteServiceProvider',
        'Illuminate\Auth\Reminders\ReminderServiceProvider',
        'Illuminate\Database\SeedServiceProvider',
        'Illuminate\Session\SessionServiceProvider',
        'Illuminate\Translation\TranslationServiceProvider',
        'Illuminate\Validation\ValidationServiceProvider',
        'Illuminate\View\ViewServiceProvider',
        'Illuminate\Workbench\WorkbenchServiceProvider',
        'Barryvdh\Debugbar\ServiceProvider',
        'Cartalyst\Sentry\SentryServiceProvider',
        'Chumper\Datatable\DatatableServiceProvider',
        'Maknz\Slack\SlackServiceProvider',
        'Schickling\Backup\BackupServiceProvider',
        'Chumper\Zipper\ZipperServiceProvider',
        'Fideloper\Proxy\ProxyServiceProvider',

    ),

    /*
    |--------------------------------------------------------------------------
    | Service Provider Manifest
    |--------------------------------------------------------------------------
    |
    | The service provider manifest is used by Laravel to lazy load service
    | providers which are not needed for each request, as well to keep a
    | list of all of the services. Here, you may set its storage spot.
    |
    */

    'manifest' => storage_path().'/meta',

    /*
    |--------------------------------------------------------------------------
    | Class Aliases
    |--------------------------------------------------------------------------
    |
    | This array of class aliases will be registered when this application
    | is started. However, feel free to register as many as you wish as
    | the aliases are "lazy" loaded so they don't hinder performance.
    |
    */

    'aliases' => array(

            'App'             		=> 'Illuminate\Support\Facades\App',
            'Artisan'         		=> 'Illuminate\Support\Facades\Artisan',
            'Auth'            		=> 'Illuminate\Support\Facades\Auth',
            'Blade'           		=> 'Illuminate\Support\Facades\Blade',
            'Cache'           		=> 'Illuminate\Support\Facades\Cache',
            'ClassLoader'     		=> 'Illuminate\Support\ClassLoader',
            'Config'          		=> 'Illuminate\Support\Facades\Config',
            'Controller'      		=> 'Illuminate\Routing\Controller',
            'Cookie'          		=> 'Illuminate\Support\Facades\Cookie',
            'Crypt'           		=> 'Illuminate\Support\Facades\Crypt',
            'DB'              		=> 'Illuminate\Support\Facades\DB',
            'Datatable' 			=> 'Chumper\Datatable\Facades\DatatableFacade',
            'Eloquent'        		=> 'Illuminate\Database\Eloquent\Model',
            'Event'           		=> 'Illuminate\Support\Facades\Event',
            'File'            		=> 'Illuminate\Support\Facades\File',
            'Form'            		=> 'Illuminate\Support\Facades\Form',
            'Hash'            		=> 'Illuminate\Support\Facades\Hash',
            'HTML'            		=> 'Illuminate\Support\Facades\HTML',
			'Image'           		=> 'Intervention\Image\ImageManagerStatic',
            'Input'           		=> 'Illuminate\Support\Facades\Input',
            'Lang'            		=> 'Illuminate\Support\Facades\Lang',
            'Log'             		=> 'Illuminate\Support\Facades\Log',
            'Mail'            		=> 'Illuminate\Support\Facades\Mail',
            'Paginator'       		=> 'Illuminate\Support\Facades\Paginator',
            'Password'        		=> 'Illuminate\Support\Facades\Password',
            'Queue'           		=> 'Illuminate\Support\Facades\Queue',
            'Redirect'        		=> 'Illuminate\Support\Facades\Redirect',
            'Redis'           		=> 'Illuminate\Support\Facades\Redis',
            'Request'         		=> 'Illuminate\Support\Facades\Request',
            'Response'        		=> 'Illuminate\Support\Facades\Response',
            'Route'           		=> 'Illuminate\Support\Facades\Route',
            'Schema'          		=> 'Illuminate\Support\Facades\Schema',
            'Seeder'          		=> 'Illuminate\Database\Seeder',
           'Sentry'          		=> 'Cartalyst\Sentry\Facades\Laravel\Sentry',
            'Session'         		=> 'Illuminate\Support\Facades\Session',
            'SoftDeletingTrait'     => 'Illuminate\Database\Eloquent\SoftDeletingTrait',
            'SSH'             		=> 'Illuminate\Support\Facades\SSH',
            'Str'             		=> 'Illuminate\Support\Str',
            'URL'             		=> 'Illuminate\Support\Facades\URL',
            'Validator'       		=> 'Illuminate\Support\Facades\Validator',
            'View'            		=> 'Illuminate\Support\Facades\View',
            'Reader'				=> 'League\Csv\Reader',
            'Slack' 				=> 'Maknz\Slack\Facades\Slack',
            'Zipper'                => 'Chumper\Zipper\Zipper',

    ),

);

**Comment by snipe** [comment]
Where did you get that config? That looks like a mix of `app/config/app.php` and `app/config/production/app.php`

**Comment by snipe** [comment]
?

**Comment by Seema-agarwal** [comment]
Sorry closed the issue by mistake

**Comment by Seema-agarwal** [comment]
I dont know
Have been trying alot of things to get it running.
What to do now?

**Comment by snipe** [comment]
I have no way of knowing what you may have manually changed, so I can't really help you unless you grab a fresh release and start again. Don't change any files other than the way the documentation instructs you to. From there we should be able to help you get it going.

**Comment by Seema-agarwal** [comment]
Is there a way I can let you access my machine on remote so that I dont have toreinstall all the dependencies again?

**Comment by snipe** [comment]
If your composer didn't run, you didn't install any of the app dependencies. If you're referring to PHP/server dependencies, you don't need to reinstall them - just replace your Snipe-IT files with a fresh download. The server settings stay the same. Download and replace the files you have on your server, and then edit the configs as detailed in the docs, and try running composer again. Then tell me what happens.

**Comment by Seema-agarwal** [comment]
ok

**Comment by Seema-agarwal** [comment]
I am in the process of installing Composer
It is installing dependencies ...as before

**Comment by snipe** [comment]
That's fine. Tell me when/if you run into errors or issues.

**Comment by Seema-agarwal** [comment]
IT suddenly says:
  - Installing maknz/slack (dev-master c8ed3e4)
    Downloading: Connecting...
Could not fetch https://api.github.com/repos/maknz/slack/zipball/c8ed3e4f919358af43516e7ab8d7fa39d3d2f736, please create a GitHub OAuth token to go ov
er the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+RSHLTP026+2015-10-28+1814
to retrieve a token. It will be stored in "C:/Users/Administrator/AppData/Roaming/Composer/auth.json" for future use by Composer.
Token (hidden):

**Comment by snipe** [comment]
You should be using the `--prefer-source` flag, per the documentation:
http://docs.snipeitapp.com/installation/composer.html

`php composer install --no-dev --prefer-source`

**Comment by Seema-agarwal** [comment]
Should I run it again

**Comment by snipe** [comment]
Yes, or create a Github OAuth token.

**Comment by Seema-agarwal** [comment]
I have created the personal token 
but only for the repo that was selected by default.

But when I paste the token it says;
Could not fetch https://api.github.com/repos/maknz/slack/zipball/c8ed3e4f919358af43516e7ab8d7fa39d3d2f736, please create a GitHub OAuth token to go ov
er the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+RSHLTP026+2015-10-28+1831
to retrieve a token. It will be stored in "C:/Users/Administrator/AppData/Roaming/Composer/auth.json" for future use by Composer.
Token (hidden):
No token given, aborting.
You can also add it manually later by using "composer config github-oauth.github.com <token>"
    Failed to download maknz/slack from dist: Could not authenticate against github.com
    Now trying to download from source
  - Installing maknz/slack (dev-master c8ed3e4)
    Cloning c8ed3e4f919358af43516e7ab8d7fa39d3d2f736

  [RuntimeException]
  Failed to clone git@github.com:maknz/slack.git, git was not found, check that it is installed and in your PATH env.
  'git' is not recognized as an internal or external command,
  operable program or batch file.

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--n
o-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [packages1] ... [packagesN]

C:\inetpub\wwwroot\Snipe-it>0cdd286e91d07f1b2683048a693f54c385d7a923

**Comment by Seema-agarwal** [comment]
That's the token at the end of the last comment.

**Comment by snipe** [comment]
Sounds like you don't have git installed. You can try using the `--prefer-dist` flag and it should try to download the zip versions of the packages.

**Comment by Seema-agarwal** [comment]
ok

**Comment by Seema-agarwal** [comment]
same:

Command: composer install --prefer-dist

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing maknz/slack (dev-master c8ed3e4)
    Downloading: Connecting...
Could not fetch https://api.github.com/repos/maknz/slack/zipball/c8ed3e4f919358af43516e7ab8d7fa39d3d2f736, please create a GitHub OAuth token to go ov
er the API rate limit
Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+RSHLTP026+2015-10-28+1836
to retrieve a token. It will be stored in "C:/Users/Administrator/AppData/Roaming/Composer/auth.json" for future use by Composer.
Token (hidden):
No token given, aborting.
You can also add it manually later by using "composer config github-oauth.github.com <token>"
    Failed to download maknz/slack from dist: Could not authenticate against github.com
    Now trying to download from source
  - Installing maknz/slack (dev-master c8ed3e4)
    Cloning c8ed3e4f919358af43516e7ab8d7fa39d3d2f736

  [RuntimeException]
  Failed to clone git@github.com:maknz/slack.git, git was not found, check that it is installed and in your PATH env.
  'git' is not recognized as an internal or external command,
  operable program or batch file.

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--n
o-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [packages1] ... [packagesN]

C:\inetpub\wwwroot\Snipe-it>c61d43d3fd5c601ceb56a5113adcbe015fc3872e

**Comment by snipe** [comment]
Just install git then, and run `php composer install --no-dev --prefer-source`

And please stop pasting your OAuth token here. Never post auth tokens on any public website.

**Comment by Seema-agarwal** [comment]
how to install git

**Comment by snipe** [comment]
http://lmgtfy.com/?q=install+git

**Comment by Seema-agarwal** [comment]
This is what happened
Basic usage: composer <command>
For more information just type "composer".

C:\inetpub\wwwroot\Snipe-it>composer install --no-dev --prefer-source
Loading composer repositories with package information
Installing dependencies from lock file
  - Installing aws/aws-sdk-php-laravel (1.0.x-dev ce9a9b5)
    Cloning ce9a9b5144d16c9bebda23f41c2dfc7f8da38471

  - Installing schickling/backup (0.6.0)
    Cloning 5243dc1d9b11390e1eb58202fd07dc3829b1bbe0

  - Installing symfony/config (2.8.x-dev a1e8e51)
    Cloning a1e8e51ed2d591bb1827d04fd1d320cd4f03e5fe

  - Installing symfony/stopwatch (2.8.x-dev 53219df)
    Cloning 53219df2141bab8c9eeabf23e0c508f0b1477ef6

  - Installing symfony/yaml (2.8.x-dev d196cb1)
    Cloning d196cb1ac36901bde7d7fbed74ee31fdb85fd119

  - Installing tecnickcom/tc-lib-color (dev-master 3e1268d)
    Cloning 3e1268d4cc95f55bbe81eac5507c02dccafcb370

  - Installing tecnickcom/tc-lib-barcode (dev-master 3d76d63)
    Cloning 3d76d63b8a622a67664ec60a13d9c33189721784

Generating autoload files

C:\inetpub\wwwroot\Snipe-it>

Now should I follow the instructions ahead with php artisan app:install --env=production

**Comment by snipe** [comment]
Yes, that looks good. Keep going with the installation

**Comment by Seema-agarwal** [comment]
ok

**Comment by Seema-agarwal** [comment]
Yay!
it says 
Admin group created successfully.

Reporting group created successfully.

Users group created successfully.

Your user was created successfully.

**Comment by Seema-agarwal** [comment]
the web application doesnt seem to be running.
i am using Windows IIS7- have followed all instructions.

**Comment by snipe** [comment]
That's a configuration issue on your end, not related to the Snipe-IT app, most likely. Maybe one of the windows users will be able to help you. 

Either way, we'll need more info than "it doesn't seem to be running". Are you getting an error? If so, what's the error?

**Comment by Seema-agarwal** [comment]
when I type
localhost/Snipe-it on my browser address window
It says

Detailed Error Information
Module	DirectoryListingModule
Notification	ExecuteRequestHandler
Handler	StaticFile
Error Code	0x00000000
Requested URL	http://localhost:80/Snipe-it/
Physical Path	C:\inetpub\wwwroot\snipe-it\
Logon Method	Anonymous
Logon User	Anonymous

**Comment by Seema-agarwal** [comment]
Could you please connect me to a window user who can help me with the configs?

**Comment by snipe** [comment]
Have you actually created a website for it in IIS? 
http://www.iisunderground.com/add-a-new-website-iis-7-5/
http://www.elvenware.com/charlie/development/web/Server/SetupAWebSite.html

I can't connect you to anyone. If one of the windows users happens to see this thread and chooses to help, they'll help. This is free software, so I can't command any of our community members to assist.

**Comment by mtucker6784** [comment]
@Seema-agarwal , I don't use Snipe It under Windows, but did you install the rewrite module and import the config over? DirectoryListingModule leads me to believe there may be a mismatch of config.

**Comment by Seema-agarwal** [comment]
Thanks a ton anyway.
Nevertheless I must congratulate you for a very intuitive UI of your application which is making me take such an effort.
No other open source IT Asset softwares are as user friendly as Snipe IT.

**Comment by Seema-agarwal** [comment]
Yes I did all that. But I will tryto look up other relevant sites and get it up.

Wont give-up.

**Comment by mtucker6784** [comment]
Hmm.. Does Eventvwr tell you anything useful about any other IIS error?

**Comment by mtucker6784** [comment]
Or any IIS logs under the Windows log directory? (sorry, not exactly sure where those logs would be, I'm not quite an IIS person :/)

**Comment by Seema-agarwal** [comment]
Thanks for the interest and support.

I will just check the earlier links and get back.

**Comment by mtucker6784** [comment]
No problem, I'll keep an eye on this thread, let us know whatever else you find and we'll go from there; I need to brush up on my Windows-side of Snipe It anyway.

**Comment by ddreier** [comment]
@Seema-agarwal did you follow all of the steps here: http://docs.snipeitapp.com/installation/server/windows.html?

You shouldn't need to type /snipe-it/ in the browser. Have you installed PHP for IIS? If not you need to download the Microsoft Web Platform Installer and use it to install PHP and PHP Manager.

**Comment by Seema-agarwal** [comment]
I have installed both.
I have another application which runs fine and is configured the same and runs ok.
In IIS I can see two folders of Snipe-it- one under sites /default and the other under sites.!!!

**Comment by Seema-agarwal** [comment]
I havent got web platform installer though.

**Comment by ddreier** [comment]
If you already have PHP and PHP Manager, don't worry about WebPI.

Try this: http://localhost/snipe-it/public/index.php

**Comment by Seema-agarwal** [comment]
it says
Module	RewriteModule
Notification	SendResponse
Handler	PHP_via_FastCGI
Error Code	0x800700b7
Config Error	Cannot add duplicate collection entry of type 'rule' with unique key attribute 'name' set to 'Imported Rule 1'
Config File	\\?\C:\inetpub\wwwroot\snipe-it\public\web.config


Config Source

    5:             <rules>
    6:                 <rule name="Imported Rule 1" stopProcessing="true">
    7:                     <match url="(.*)" ignoreCase="false" />

**Comment by ddreier** [comment]
Hmm. Well, you probably were going to need to disable that rewrite rule anyway, so disable Imported Rule 1.

**Comment by Seema-agarwal** [comment]
I did but the same error again why?
The rule is disabled in IIS??

**Comment by ddreier** [comment]
Look in the web.config file around line 5 for duplicate <rule> entries. If there are some, you'll need to remove the duplicates.

Or you could try renaming all of the rules in URL Rewrite to be different and unique.

**Comment by Seema-agarwal** [comment]
@snipe ; while installation of snipe It 
I copied the example app config from app/config/production/app.example.php to app/config/production/app.php
and changed
'url' => 'http://localhost',

and let
         'domain' => 'yourserver.com',

IS THAT THE PROBLEM?

**Comment by ddreier** [comment]
@Seema-agarwal Nope. You're getting an IIS error, not a Snipe-IT error.

Though, you should probably change `url` in `app/config/production/app.php` to reflect the actual name of the computer Snipe-IT is running on, unless you're only ever going to access it from that server.

**Comment by Seema-agarwal** [comment]
ok

**Comment by ddreier** [comment]
Have you checked Web.config for duplicate rewrite rules? It's most likely located in `C:\inetpub\wwwroot\web.config`

**Comment by Seema-agarwal** [comment]
web.config does not exist in C:\inetpub\wwwroot\web.config

But one exists in C:\inetpub\wwwroot\snipe-it\public\web.config

**Comment by Seema-agarwal** [comment]
That too has the following;
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <remove name="Imported Rule 1" />
                <rule name="Imported Rule 1" enabled="true" stopProcessing="true">
                    <match url="(.*)" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAll">
                        <add input="{HTTPS}" pattern="off" ignoreCase="false" />
                    </conditions>
                    <serverVariables />
                    <action type="Redirect" url="https://{HTTP_HOST}{URL}" redirectType="Permanent" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>

**Comment by Seema-agarwal** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <remove name="Imported Rule 1" />
                <rule name="Imported Rule 1" enabled="true" stopProcessing="true">
                    <match url="(.*)" ignoreCase="false" />
                    <conditions logicalGrouping="MatchAll">
                        <add input="{HTTPS}" pattern="off" ignoreCase="false" />
                    </conditions>
                    <serverVariables />
                    <action type="Redirect" url="https://{HTTP_HOST}{URL}" redirectType="Permanent" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>

**Comment by Seema-agarwal** [comment]
the rest does not seem to be showing?????



![webconfig](https://cloud.githubusercontent.com/assets/14859621/10794076/6f3ae980-7db9-11e5-8a31-c70b1005059c.jpg)

**Comment by ddreier** [comment]
I'd suggest removing everything between the <system.webServer> nodes and then re-import the .htaccess file.

**Comment by Seema-agarwal** [comment]
Would you mean removing everything from ths web.config file?

**Comment by Seema-agarwal** [comment]
I removed the text and re-imported rules
 but now the index page doesnot load at all
![error2](https://cloud.githubusercontent.com/assets/14859621/10796858/f9bfd780-7dc5-11e5-8e4c-ab2e90ac4c60.jpg)

**Comment by Seema-agarwal** [comment]
In internet explorer the following is seen

![error3](https://cloud.githubusercontent.com/assets/14859621/10797216/9a39f1ae-7dc7-11e5-8625-43a1f5337bec.jpg)

**Comment by ddreier** [comment]
So, I think you have a couple options here.

1. Rename the Rewrite rules and see if that fixes it (i.e. change "Imported" to "Snipe-IT" in the three rules).
2. Create a separate site in IIS for Snipe-IT, either with a different port number or a different host name/URL. This will (probably) fix the issue here, which is the inheritance of URL Rewrite rules from the default site to the Snipe-IT site/Application.
3. Try disabling inheritance for URL Rewrite rules. I found this [forum post](http://forums.iis.net/t/1182625.aspx) after a quick Google search for "iis 7.5 rewritemodule cannot add duplicate collection entry of type rule". I make no guarantees that it is valid or works.

At the end of the day, this is an IIS problem. Which is your problem to troubleshoot and resolve. I will continue to try and help as I can, but there's only so much that I can do over the internet.
