### ISSUE TITLE
artisan migrate error: Creating default object from empty value

### ISSUE THREAD

**Issue by Furchendackel** [snipe/snipe-it#1202]
I am updating to 2.0.3 from 1.2.7.

Copied all over, ran 'php composer.phar install', 'php composer.phar dump-autoload'.
Finally, 'php artisan migrate' fails with: '[ErrorException] Creating default object from empty value'

Log says:

`[2015-09-28 08:02:28] production.ERROR: exception 'ErrorException' with message 'Creating default object from empty value' in /var/www/snipeit/app/database/migrations/2015_07_29_230054_add_thread_id_to_asset_logs_table.php:191
Stack trace:
#0 /var/www/snipeit/app/database/migrations/2015_07_29_230054_add_thread_id_to_asset_logs_table.php(191): Illuminate\Exception\Handler->handleError(2, 'Creating defaul...', '/var/www/snipei...', 191, Array)
#1 /var/www/snipeit/app/database/migrations/2015_07_29_230054_add_thread_id_to_asset_logs_table.php(91): AddThreadIdToAssetLogsTable->updateAssetLogWithThreadInformation(Object(stdClass))
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(135): AddThreadIdToAssetLogsTable->up()
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(111): Illuminate\Database\Migrations\Migrator->runUp('2015_07_29_2300...', 4, false)
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(82): Illuminate\Database\Migrations\Migrator->runMigrationList(Array, false)
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(70): Illuminate\Database\Migrations\Migrator->run('/var/www/snipei...', false)
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(112): Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#7 /var/www/snipeit/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/snipeit/vendor/symfony/console/Symfony/Component/Console/Application.php(889): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/snipeit/vendor/symfony/console/Symfony/Component/Console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/snipeit/vendor/symfony/console/Symfony/Component/Console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/snipeit/artisan(59): Symfony\Component\Console\Application->run()
#13 {main} [] []`

Any suggestions?

**Comment by snipe** [comment]
@vsposato it looks like that migration is still busted. Can you take a look? I think this only happens when people have uploaded files.

**Comment by vsposato** [comment]
Yep - I've been busy these last 2 weeks finishing an audit but will get to
it this week. Sorry for being so slow on this

Vinnie

**Comment by Furchendackel** [comment]
Still present with 2.0.4.

Is there any way I can fix that/work around this?

**Comment by snipe** [comment]
@Furchendackel Do you have any file uploads in your `asset_logs` table?

**Comment by Furchendackel** [comment]
No. Just a bunch 'checkin from' and 'checkout'... AND... One 'custom' entry (manually added to the db), was just a test as I was starting with snipe-it. I wanted a special event (hdd erased) to show up in the events history of a special system.
I deleted this entry and 'php artisan migrate' completed without any error.

So, it was not a real bug but user induced *shame on me*

Thanks for pointing me to the right place!
