### ISSUE TITLE
Export doesn't work in Mozilla Firefox (blank box)

### ISSUE THREAD

**Issue by rp-tech** [snipe/snipe-it#1203]
See attached image when I go to export assets - just comes up with a small blank white box + dims the screen
![export-error](https://cloud.githubusercontent.com/assets/10659713/10141188/eb120028-65bf-11e5-9059-f4def3a33f88.png)

**Comment by hawk554** [comment]
I had the same issue and I found my problem to be that my 'url' variable in the location app/config/production/app.php to be incorrect. Make sure the url reflects whether you are using http or https. Hopefully this fixes it for you.

**Comment by rp-tech** [comment]
Thanks for the suggestion - I double-checked the URL and it is correct, no typos and using http (no cert)

**Comment by snipe** [comment]
When you turn on debugging in your browser, do you see any errors?

**Comment by rp-tech** [comment]
Nothing shows up, it just shows a blank box until I click off of the box.

![2015-10-06](https://cloud.githubusercontent.com/assets/10659713/10324094/fc4f1f24-6c3b-11e5-9a2d-09e64f99a930.png)

**Comment by snipe** [comment]
I'm more interested in seeing the HTTP status code for where it thinks it should be pulling that export SWF. Can you show me the network output status of that file?

**Comment by rp-tech** [comment]
OK chalk this one up to a (partial) PEBKAC issue.

You got me thinking about why it simply wasn't showing any debug info whatsoever. The first thing I should have done was test another browser.

I fired it up in Chrome and it works fine; checked IE, works here too - looks like this problem is limited to Firefox.

The only add-on I have is AdBlock - i disabled it, but it's still showing as blank in FF. So then I tried launching FF in safemode - same problem.

The issue appears to be something to do with Firefox, or at least the latest version. Perhaps you can try testing on your end and see whether you are able to re-produce the issue.

Cheers,

**Comment by rp-tech** [comment]
I just tested an older version of FF (38.01) completely vanilla and it's not working in that version either.

**Comment by snipe** [comment]
We're going to be switching from the current Datatables plugin (which uses Flash for the export - ew) to one that is more responsive and doesn't require flash, so I'm going to close this issue. Hopefully we won't have that dumb Flash widget for much longer.

**Comment by rp-tech** [comment]
cool beans!
