### ISSUE TITLE
Bulk Deleting users results in AJAX error

### ISSUE THREAD

**Issue by rp-tech** [snipe/snipe-it#1204]
When I go to bulk delete a user and select the 'update assets' option it changes the asset status to 0, resulting in the bug that was mentioned in #1160 

Note: following the steps in #1160 resolves the issue, but the problem appears to be caused by deleting the user and selecting the option to check in their assets - hope that is clear!

**Comment by snipe** [comment]
As literally always, I need to see log/debugging output.

**Comment by snipe** [comment]
Also a screenshot of the "check in assets" you're referring to would be very helpful.

**Comment by rp-tech** [comment]
It happens in the bulk field:
![2015-09-28 09_13_45-clipboard](https://cloud.githubusercontent.com/assets/10659713/10141421/539ae190-65c1-11e5-9620-908119dfce8e.png)

Sorry my wording wasn't clear - I updated the phrasing in my original post above.

**Comment by rp-tech** [comment]
Debug is already on - here's the resulting error, which happens after I click 'List All' AFTER using the above option to change user's assets to 'Ready to Deploy':

![2015-09-28 09_20_20-clipboard](https://cloud.githubusercontent.com/assets/10659713/10141585/3cec5ed2-65c2-11e5-81ff-12b61f564fb0.png)

**Comment by rp-tech** [comment]
Here's the resulting change to the asset, which after correcting from 0 to a NULL value using phpmyadmin fixes the List All issue (which is re-produced again by using the Bulk Delete user option in combination with changing the asset to 'ready to deploy':

![2015-09-28 09_24_15-clipboard](https://cloud.githubusercontent.com/assets/10659713/10141700/dc5c77e0-65c2-11e5-8dce-b13c2e4138eb.png)

**Comment by snipe** [comment]
That's not the error I need. The Ajax error just basically says "the data the API is returning doesn't match what we're expecting.", so it's not very helpful at all. I need the debug info from the logs, or I need you to go to the api page and trigger the error there. Is this Ajax error on the users listing page or the assets listing page? If on the assets listing page, go to `api/hardware/list` and tell me what error you see there.

**Comment by rp-tech** [comment]
It's on the Assets List All page it's the exact same issue in #1160 and the same fix to correct it.

It just appears to be getting triggered by the above steps. To be clear no error occurs when I perform the above steps - everything is fine up until the point where you go to Assets -> List All, and that problem only happens after you perform the Bulk Users -> Delete -> check in assets steps that I listed above.

**Comment by snipe** [comment]
To be honest, I'm not sure where it would be getting 0 from... This is the actual code on the bulk delete save:

                    $update_assets = Asset::whereIn('id', $asset_array)->update(
                            array(
                                'status_id' => e(Input::get('status_id')),
                                'assigned_to' => '',
                    ));

While I can change that to NULL, there is no 0 there, and 0 is not the default database field value.

**Comment by rp-tech** [comment]
Are you able to re-produce the issue using the same steps?

**Comment by snipe** [comment]
I think I see what was happening. MySQL doesn't want '' in an integer field, it wants NULL or an actual integer. The fix I just pushed out to develop should take care of it.

**Comment by rp-tech** [comment]
Awesomesauce!
