### ISSUE TITLE
Adding new license action fails with PDOException

### ISSUE THREAD

**Issue by Jengah** [snipe/snipe-it#1205]
Running 2.0 and getting this error when testing out license importer:

  [PDOException]
  SQLSTATE[HY000]: General error: 1364 Field 'purchase_order' doesn't have a default value

No mention of a Purchase Order field detailed on the License Importer instructions page: http://docs.snipeitapp.com/manual/importing-licenses.html

**Comment by snipe** [comment]
Can you check if mysql is running in strict mode?

**Comment by Jengah** [comment]
I did that after looking up another Issue. Still nada.

**Comment by snipe** [comment]
I'm asking whether it is or or not.

**Comment by Jengah** [comment]
Sorry forgot to say it was turned off after seeing that troubleshooting step in another issue. It is not in strict mode

**Comment by snipe** [comment]
How are you determining that? The only reason I can see why you'd get that error is if you're running in strict mode.

**Comment by snipe** [comment]
I've added a migration to allow default null for strict mode on the develop branch (which you can grab and then run migrations), but I'm pretty sure you're running in strict mode.

**Comment by Jengah** [comment]
SET sql_mode was apparently not working correctly so I went in and edited my.cnf file and restarted and strict mode  finally was disabled. Import ran successfully.

**Comment by snipe** [comment]
Got it. The migration I just pushed out should prevent you from having to run in strict mode moving forward.

**Comment by Jengah** [comment]
Gotcha. Thanks for your help!

**Comment by snipe** [comment]
No problem - it was my bad to begin with. I run everything locally in strict mode specifically to prevent issues for folks who *have* to run in strict mode, but for some reason it had been turned off in my local environment. :-/ 

![break-the-internet](https://cloud.githubusercontent.com/assets/197404/10149077/2392f296-65ec-11e5-80f7-a4b662773eb6.gif)
