### ISSUE TITLE
Installation - General error: 1364 Field doesn't have a default value

### ISSUE THREAD

**Issue by magic2110** [snipe/snipe-it#1206]
Searching through issue tickets I've found a few of these types of errors and it appears to be the database being in strict mode but it looks like it requires intervention on your part to allow its function within strict mode. I haven't tried changing the mode setting yet, should I?

Windows Server 2012R2
PHP: v5.6
MySQL: MariaDB 10.0

C:\inetpub\wwwroot\snipe-it>php artisan app:install --env=production
=====================================

  Step: 1

    Please follow the following
    instructions to create your
    default user.

-------------------------------------

Please enter your first name: (deleted)
Please enter your last name: (deleted)
Please enter your username: (deleted)
Please enter your email: (deleted)
Please enter your user password (at least 8 characters): (deleted)
Do you want to seed your database with dummy data? Y/n (default is yes): Y

=====================================

  Step: 2

    Preparing your Application

-------------------------------------

Application key [(deleted)] set successfully.
Migration table created successfully.
Migrated: 2012_12_06_225921_migration_cartalyst_sentry_install_users
Migrated: 2012_12_06_225929_migration_cartalyst_sentry_install_groups
Migrated: 2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivo
t
Migrated: 2012_12_06_225988_migration_cartalyst_sentry_install_throttle
Migrated: 2013_03_23_193214_update_users_table
Migrated: 2013_11_13_075318_create_models_table
Migrated: 2013_11_13_075335_create_categories_table
Migrated: 2013_11_13_075347_create_manufacturers_table
Migrated: 2013_11_15_015858_add_user_id_to_categories
Migrated: 2013_11_15_112701_add_user_id_to_manufacturers
Migrated: 2013_11_15_190327_create_assets_table
Migrated: 2013_11_15_190357_create_licenses_table
Migrated: 2013_11_15_201848_add_license_name_to_licenses
Migrated: 2013_11_16_040323_create_depreciations_table
Migrated: 2013_11_16_042851_add_depreciation_id_to_models
Migrated: 2013_11_16_084923_add_user_id_to_models
Migrated: 2013_11_16_103258_create_locations_table
Migrated: 2013_11_16_103336_add_location_id_to_assets
Migrated: 2013_11_16_103407_add_checkedout_to_to_assets
Migrated: 2013_11_16_103425_create_history_table
Migrated: 2013_11_17_054359_drop_licenses_table
Migrated: 2013_11_17_054526_add_physical_to_assets
Migrated: 2013_11_17_055126_create_settings_table
Migrated: 2013_11_17_062634_add_license_to_assets
Migrated: 2013_11_18_134332_add_contacts_to_users
Migrated: 2013_11_18_142847_add_info_to_locations
Migrated: 2013_11_18_152942_remove_location_id_from_asset
Migrated: 2013_11_18_164423_set_nullvalues_for_user
Migrated: 2013_11_19_013337_create_asset_logs_table
Migrated: 2013_11_19_061409_edit_added_on_asset_logs_table
Migrated: 2013_11_19_062250_edit_location_id_asset_logs_table
Migrated: 2013_11_20_055822_add_soft_delete_on_assets
Migrated: 2013_11_20_121404_add_soft_delete_on_locations
Migrated: 2013_11_20_123137_add_soft_delete_on_manufacturers
Migrated: 2013_11_20_123725_add_soft_delete_on_categories
Migrated: 2013_11_20_130248_create_status_labels
Migrated: 2013_11_20_130830_add_status_id_on_assets_table
Migrated: 2013_11_20_131544_add_status_type_on_status_labels
Migrated: 2013_11_20_134103_add_archived_to_assets
Migrated: 2013_11_21_002321_add_uploads_table
Migrated: 2013_11_21_024531_remove_deployable_boolean_from_status_labels
Migrated: 2013_11_22_075308_add_option_label_to_settings_table
Migrated: 2013_11_22_213400_edits_to_settings_table
Migrated: 2013_11_25_013244_create_licenses_table
Migrated: 2013_11_25_031458_create_license_seats_table
Migrated: 2013_11_25_032022_add_type_to_actionlog_table
Migrated: 2013_11_25_033008_delete_bad_licenses_table
Migrated: 2013_11_25_033131_create_new_licenses_table
Migrated: 2013_11_25_033534_add_licensed_to_licenses_table
Migrated: 2013_11_25_101308_add_warrantee_to_assets_table
Migrated: 2013_11_25_104343_alter_warranty_column_on_assets
Migrated: 2013_11_25_150450_drop_parent_from_categories
Migrated: 2013_11_25_151920_add_depreciate_to_assets
Migrated: 2013_11_25_152903_add_depreciate_to_licenses_table
Migrated: 2013_11_26_211820_drop_license_from_assets_table
Migrated: 2013_11_27_062510_add_note_to_asset_logs_table
Migrated: 2013_12_01_113426_add_filename_to_asset_log
Migrated: 2013_12_06_094618_add_nullable_to_licenses_table
Migrated: 2013_12_10_084038_add_eol_on_models_table
Migrated: 2013_12_12_055218_add_manager_to_users_table
Migrated: 2014_01_28_031200_add_qr_code_to_settings_table
Migrated: 2014_02_13_183016_add_qr_text_to_settings_table
Migrated: 2014_05_24_093839_alter_default_license_depreciation_id
Migrated: 2014_05_27_231658_alter_default_values_licenses
Migrated: 2014_06_19_191508_add_asset_name_to_settings
Migrated: 2014_06_20_004847_make_asset_log_checkedout_to_nullable
Migrated: 2014_06_20_005050_make_asset_log_purchasedate_to_nullable
Migrated: 2014_06_24_003011_add_suppliers
Migrated: 2014_06_24_010742_add_supplier_id_to_asset
Migrated: 2014_06_24_012839_add_zip_to_supplier
Migrated: 2014_06_24_033908_add_url_to_supplier
Migrated: 2014_07_08_054116_add_employee_id_to_users
Migrated: 2014_07_09_134316_add_requestable_to_assets
Migrated: 2014_07_17_085822_add_asset_to_software
Migrated: 2014_07_17_161625_make_asset_id_in_logs_nullable
Migrated: 2014_08_12_053504_alpha_0_4_2_release
Migrated: 2014_08_17_083523_make_location_id_nullable
Migrated: 2014_10_16_200626_add_rtd_location_to_assets
Migrated: 2014_10_24_000417_alter_supplier_state_to_32
Migrated: 2014_10_24_015641_add_display_checkout_date
Migrated: 2014_10_28_222654_add_avatar_field_to_users_table
Migrated: 2014_10_29_045924_add_image_field_to_models_table
Migrated: 2014_11_01_214955_add_eol_display_to_settings
Migrated: 2014_11_04_231416_update_group_field_for_reporting
Migrated: 2014_11_05_212408_add_fields_to_licenses
Migrated: 2014_11_07_021042_add_image_to_supplier
Migrated: 2014_11_20_203007_add_username_to_user
Migrated: 2014_11_20_223947_add_auto_to_settings
Migrated: 2014_11_20_224421_add_prefix_to_settings
Migrated: 2014_11_21_104401_change_licence_type
Migrated: 2014_12_09_082500_add_fields_maintained_term_to_licenses
Migrated: 2015_02_04_155757_increase_user_field_lengths
Migrated: 2015_02_07_013537_add_soft_deleted_to_log
Migrated: 2015_02_10_040958_fix_bad_assigned_to_ids
Migrated: 2015_02_10_053310_migrate_data_to_new_statuses
Migrated: 2015_02_11_044104_migrate_make_license_assigned_null
Migrated: 2015_02_11_104406_migrate_create_requests_table
Migrated: 2015_02_12_001312_add_mac_address_to_asset
Migrated: 2015_02_12_024100_change_license_notes_type
Migrated: 2015_02_17_231020_add_localonly_to_settings
Migrated: 2015_02_19_222322_add_logo_and_colors_to_settings
Migrated: 2015_02_24_072043_add_alerts_to_settings
Migrated: 2015_02_25_022931_add_eula_fields
Migrated: 2015_02_25_204513_add_accessories_table
Migrated: 2015_02_26_091228_add_accessories_user_table
Migrated: 2015_02_26_115128_add_deleted_at_models
Migrated: 2015_02_26_233005_add_category_type
Migrated: 2015_03_01_231912_update_accepted_at_to_acceptance_id
Migrated: 2015_03_05_011929_add_qr_type_to_settings
Migrated: 2015_03_18_055327_add_note_to_user
Migrated: 2015_04_29_234704_add_slack_to_settings
Migrated: 2015_05_04_085151_add_parent_id_to_locations_table
Migrated: 2015_05_22_124421_add_reassignable_to_licenses
Migrated: 2015_06_10_003314_fix_default_for_user_notes
Migrated: 2015_06_10_003554_create_consumables
Migrated: 2015_06_15_183253_move_email_to_username
Migrated: 2015_06_23_070346_make_email_nullable
Migrated: 2015_06_26_213716_create_asset_maintenances_table
Migrated: 2015_07_09_014359_add_currency_to_settings_and_locations
Migrated: 2015_07_21_122022_add_expected_checkin_date_to_asset_logs
Migrated: 2015_07_24_093845_add_checkin_email_to_category_table
Migrated: 2015_07_25_055415_remove_email_unique_constraint
Migrated: 2015_07_29_230054_add_thread_id_to_asset_logs_table
Migrated: 2015_07_31_015430_add_accepted_to_assets
Migrated: 2015_09_09_195301_add_custom_css_to_settings

Admin group created successfully.

Reporting group created successfully.

Users group created successfully.

Your user was created successfully.

Seeded: AssetsSeeder
Seeded: CategoriesSeeder
Seeded: LocationsSeeder
Seeded: ManufacturersSeeder
Seeded: ModelsSeeder
Seeded: DepreciationsSeeder
Seeded: StatuslabelsSeeder
Seeded: SettingsSeeder
Seeded: LicensesSeeder
Seeded: LicenseSeatsSeeder
Seeded: ActionlogSeeder
Seeded: AccessoriesSeeder

  [Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1364 Field 'is_warranty' doesn't have a def
  ault value (SQL: insert into `asset_maintenances` (`asset_id`, `asset_maint
  enance_type`, `cost`, `created_at`, `start_date`, `supplier_id`, `title`, `
  updated_at`) values (1, Maintenance, 200.99, 2015-09-05 22:15:12, 2015-09-0
  5 22:15:12, 1, Test Maintenance, 2015-09-05 22:15:12))

  [PDOException]
  SQLSTATE[HY000]: General error: 1364 Field 'is_warranty' doesn't have a def
  ault value

app:install

C:\inetpub\wwwroot\snipe-it>

**Comment by snipe** [comment]
You can set the mysql mode - we cannot do it for you. http://www.mysqlfaqs.net/mysql-client-server-commands/what-is-sql-mode-in-mysql-and-how-can-we-set-it

**Comment by magic2110** [comment]
Right, but where in the install instructions does it say to take the db out of strict mode? I figured the app leaves is_warranty blank on accident since it isn't explained anywhere what the db setting should be.

**Comment by snipe** [comment]
@magic2110 you shouldn't have to, which is why we pushed out fixes.
