### ISSUE TITLE
install error when using install.sh with mysql - ubuntu server

### ISSUE THREAD

**Issue by ghost** [snipe/snipe-it#1207]
Hi,

I'm using install.sh to get everything set up on Ubuntu Server 14.04.2.

While running the script, I get the following error:

...
Create MySQL accounts
mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost' (using password: NO)'

I only had mysql installed on this server before but when I saw that the install script required a fresh install of Ubuntu, I uninstalled mysql completely and then ran the script. I'd appreciate any help to get this going!

Thanks!

**Comment by snipe** [comment]
"mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'root'@'localhost' (using password: NO)'"

I'm guessing you have the wrong mysql root password.

**Comment by torriz** [comment]
Try using [this script](https://bensmann.no/reset-root-mysql-password-ubuntu/) to reset your mysql root password. :+1:
