### ISSUE TITLE
Missing responses in the openapi spec

### ISSUE THREAD

**Issue by StarlessNights** [snipe/snipe-it#12091]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

`response` attribute is missing from the following paths in [Snipe-IT v6 API - v6.0.10](https://snipe-it.readme.io/openapi/63098151fc0ba500a8e18e36) openapi spec:

- /departments (get)
- /locations/{id} (delete)
- /manufacturers (get)
- /maintenances/{id} (delete)
- /hardware/:id/restore (post)

This is a problem when generating client code based on the openapi spec.

### Reproduction steps

Run the openapi spec through a validator. For example:
```bash
$ openapi-generator-cli validate --recommend --input-spec https://snipe-it.readme.io/openapi/63098151fc0ba500a8e18e36
Validating spec (https://snipe-it.readme.io/openapi/63098151fc0ba500a8e18e36)
Errors:
        - attribute paths.'/departments'(get).responses is missing
        - attribute paths.'/locations/{id}'(delete).responses is missing
        - attribute paths.'/manufacturers'(get).responses is missing
        - attribute paths.'/maintenances/{id}'(delete).responses is missing
        - attribute paths.'/hardware/:id/restore'(post).responses is missing
Warnings: 
        - While technically allowed, GET/HEAD with request body may indicate programming error, and
          is considered an anti-pattern.

[error] Spec has 5 errors.

```

### Expected behavior

The openapi spec should have all the responses defined, and pass validation with clean papers.

### Screenshots

Can also be seen from the [live documentation](https://snipe-it.readme.io/reference/hardwareidrestore).
![image](https://user-images.githubusercontent.com/115993812/201034596-4189bc0e-3325-40b2-bebf-bccc9538f728.png)

### Snipe-IT Version

-

### Operating System

-

### Web Server

-

### PHP Version

-

### Additional context

Maybe it would be possible to automate spec validation?

**Comment by uberbrady** [comment]
I've repaired all of the errors that are reported by the `openapi-generator-cli` command. There may still be some gaps, but none of those errors show up when I re-run the `openapi-generator-cli` command against the latest (6.0.13) OpenAPI spec JSON file.
