### ISSUE TITLE
php artisan key:generate throws error about PDO support on CentOS

### ISSUE THREAD

**Issue by brianjking** [snipe/snipe-it#1210]
```
php artisan key:generate --env=production
PHP Fatal error:  Class 'PDO' not found in /home/dockbiz/public_html/app/config/production/database.php on line 16
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'PDO' not found","file":"\/home\/dockbiz\/public_html\/app\/config\/production\/database.php","line":16}}
```

However, I have setup the database.php file and my php configuration has pdo mysql support.

Please help! Thank you!

**Comment by brianjking** [comment]
cat log-cli-2015-09-29.txt
```
[2015-09-29 18:24:27] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'PDO' not found' in /home/dockbiz/public_html/app/config/production/database.php:16
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-09-29 18:39:21] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'PDO' not found' in /home/dockbiz/public_html/app/config/production/database.php:16
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-09-29 18:39:37] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'PDO' not found' in /home/dockbiz/public_html/app/config/production/database.php:16
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-09-29 18:52:35] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'PDO' not found' in /home/dockbiz/public_html/app/config/production/database.php:16
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
```

**Comment by snipe** [comment]
You need php-mysql installed

**Comment by snipe** [comment]
When you run `php -i | grep pdo` on the command line, what does it show you?

**Comment by brianjking** [comment]
@snipe 

php -i | grep pdo
```
Configure Command =>  './configure'  '--prefix=/usr/local/phpbrew/php/php-5.5.29' '--with-config-file-path=/usr/local/phpbrew/php/php-5.5.29/etc' '--with-config-file-scan-dir=/usr/local/phpbrew/php/php-5.5.29/var/db' '--with-pear=/usr/local/phpbrew/php/php-5.5.29/lib/php' '--enable-fpm' '--enable-dom' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--with-libxml-dir=/usr' '--disable-fileinfo' '--enable-bcmath' '--enable-calendar' '--enable-exif' '--enable-ftp' '--enable-gd-native-ttf' '--enable-libxml' '--enable-mbstring' '--enable-pdo=shared' '--enable-soap' '--enable-sockets' '--enable-zip' '--with-curl=/opt/curlssl/' '--with-freetype-dir=/usr' '--with-gd' '--with-gettext' '--with-imap=/opt/php_with_imap_client/' '--with-imap-ssl=/usr' '--with-jpeg-dir=/usr' '--with-kerberos' '--with-libdir=lib64' '--with-libexpat-dir=/usr' '--with-libxml-dir=/opt/xml2' '--with-libxml-dir=/opt/xml2/' '--with-mcrypt=/opt/libmcrypt/' '--with-mysql=/usr' '--with-mysql-sock=/var/lib/mysql/mysql.sock' '--with-mysqli=/usr/bin/mysql_config' '--with-openssl=/usr' '--with-openssl-dir=/usr' '--with-pcre-regex=/opt/pcre' '--with-pdo-mysql=shared' '--with-pdo-sqlite=shared' '--with-pgsql=/usr' '--with-pic' '--with-png-dir=/usr' '--with-tidy=/opt/tidy/' '--with-xmlrpc' '--with-xpm-dir=/usr' '--with-zlib' '--with-zlib-dir=/usr' '--enable-fileinfo'
```

Thanks for the quick reply.

**Comment by snipe** [comment]
I am not sure why PDO would even be invoked in the key generation, but you can try just using any 32-character string as the key in your app config instead of running the key generator.

What flavor of linux are you running? Can you try running `yum install php-pdo` or `apt get php-pdo` as root or sudo'd user?

**Comment by snipe** [comment]
Also some debugging steps here: http://www.inmotionhosting.com/support/website/website-troubleshooting/fatal-error-class-pdo-not-found

**Comment by snipe** [comment]
What was your resolution?

**Comment by yahyaerturan** [comment]
Same here.. When I run `print_r(PDO::getAvailableDrivers());` it outputs `['0'=>'sqlite','1'=>'mysql']`. Here is the output of my `php -i | grep pdo`:
```
'./configure'  '--disable-fileinfo' '--disable-opcache' '--enable-bcmath' '--enable-calendar' '--enable-exif' '--enable-ftp' '--enable-gd-native-ttf' '--enable-intl' '--enable-libxml' '--enable-mbstring' '--enable-pdo=shared' '--enable-soap' '--enable-sockets' '--enable-wddx' '--enable-zip' '--prefix=/usr/local' '--with-apxs2=/usr/local/apache/bin/apxs' '--with-bz2' '--with-curl=/opt/curlssl/' '--with-freetype-dir=/usr' '--with-gd' '--with-gettext' '--with-icu-dir=/usr' '--with-imap=/opt/php_with_imap_client/' '--with-imap-ssl=/usr' '--with-jpeg-dir=/usr' '--with-kerberos' '--with-libdir=lib64' '--with-libexpat-dir=/usr' '--with-libxml-dir=/opt/xml2' '--with-libxml-dir=/opt/xml2/' '--with-mcrypt=/opt/libmcrypt/' '--with-mm=/opt/mm/' '--with-mysql' '--with-mysqli' '--with-openssl=/usr' '--with-openssl-dir=/usr' '--with-pcre-regex=/opt/pcre' '--with-pdo-mysql=shared' '--with-pdo-sqlite=shared' '--with-pic' '--with-png-dir=/usr' '--with-snmp' '--with-tidy=/opt/tidy/' '--with-xmlrpc' '--with-xpm-dir=/usr' '--with-xsl=/opt/xslt/' '--with-zlib' '--with-zlib-dir=/usr' 'LDFLAGS= '-L/usr/X11R6/lib64''
```

Still `php artisan` throws `Fatal error: Class 'PDO' not found in /home/erturanc/Code/test/config/database.php on line 16`.

**Comment by snipe** [comment]
@yahyaerturan first off, you need fileinfo, so disabling it seems like a bad idea. It's in the system requirements, and I'm not sure how you could have run composer successfully without it.

**Comment by brianjking** [comment]
@yahyaerturan Yeah, you need to change that --disable-fileinfo line.

Did you check http://www.inmotionhosting.com/support/website/website-troubleshooting/fatal-error-class-pdo-not-found as @snipe provided?

What OS are you running? If Linux, which Distribution/version?

Are you using cPanel/WHM?

**Comment by yahyaerturan** [comment]
@brianjking Actually I figured out the problem. Yes, I have successful installation of PDO, I can use it everywhere.. But somehow it is not enabled on php-cli. I am using Centos with PHP5.6, cPanel & WHM. Still trying to figure out how to enable it for cli.

**Comment by brianjking** [comment]
@yahyaerturan How did you install PHP? EasyApache3? EasyApache4? PHPBrew?

**Comment by yahyaerturan** [comment]
@brianjking `~$ /usr/local/cpanel/scripts/easyapache --version' => `EasyApache v3326 and Cpanel v1148.` Couldn't find an option on rebuild screens..

**Comment by brianjking** [comment]
@yahyaerturan Can you navigate to your php.ini file and `vim php.ini` or `nano php.ini` (whichever you prefer) and look to see if there's a line 

`;extension=php_fileinfo.dll` 
or
`;extension=php_fileinfo.so`

**Comment by brianjking** [comment]
You can locate your php.ini file by navigating executing

`php --ini`

**Comment by yahyaerturan** [comment]
Done.. `	'./configure' '--disable-fileinfo' '--disable-opcache' .... `   But problem still persists. I need to find a way enable PDO for cli :worried:

**Comment by brianjking** [comment]
@yahyaerturan Do you have Google Hangouts? Message me there. brianjosephking at [g]mail[...]com

**Comment by yahyaerturan** [comment]
I solved the issue.

I run `php-cli --ini` and it points to `/usr/local/bin/php.ini`. I edit an add the followings:
```
extension=pdo.so
extension=pdo_sqlite.so
extension=pdo_mysql.so
```

A bit insensible because it was working through browser calls anyway. However, now it works.

**Comment by bertalanimre** [comment]
Just to update a bit this topic: All I had to do was to install php-pdo.
But I'm using alpine linux in a docker file, so it is a bit different. But I though it could help others.
