### ISSUE TITLE
Importing Parent Locations in CSV

### ISSUE THREAD

**Issue by zcsjfisher** [snipe/snipe-it#1214]
Hello,

We recently installed snipe-it and we are trying to import from our previous database.  We are a school district   so we have lots of locations (lots of rooms) with a small amount of computers.  I am wanting to know how to properly import the CSV with parent locations so that when we import, it will create the location such s ABC Elementary (parent)   RM 101 (location).  We will also have multiple RM 101's so when I exported a test it just said RM 101 with no parent location included.  
##

**Comment by snipe** [comment]
Hi @zcsjfisher - We don't have a notion of parent locations in the importers, but you should be able to import your assets, and then modify the locations that are created in the cli asset importer tool to be nested within other locations.
