### ISSUE TITLE
[BUG]: Categories table has mismatched columns

### ISSUE THREAD

**Issue by Robert-Azelis** [snipe/snipe-it#12153]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

Categories table has mismatched columns
![image](https://user-images.githubusercontent.com/82208283/203059547-3a1c02a0-cf56-4dc4-b9cc-f94192ccd239.png)

### Reproduction steps

1. Go to Settings->Categories

### Expected behavior

Fix matching of columns

### Snipe-IT Version

6.0.13

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.0

**Comment by nikomatjasic** [comment]
Thank you @Robert-Azelis. Here is the code fix: https://github.com/snipe/snipe-it/pull/12169 
@snipe please take care of the merge conflict.

**Comment by Robert-Azelis** [comment]
> #12164

Hi @nikomatjasic , it has been merged already https://github.com/snipe/snipe-it/pull/12164 , by my update
