### ISSUE TITLE
cant change password for user imported from ldap

### ISSUE THREAD

**Issue by klemenkobetic** [snipe/snipe-it#1216]
when i import an user from ldap and try to change it from snipeit it says that the old password isn't correct!

**Comment by snipe** [comment]
@klemenkobetic where are you trying to edit the password? If you're an admin, it doesn't ask you to confirm the current password.

**Comment by klemenkobetic** [comment]
If you import an user from LDAP and then you log in as that user (the imported one) and then try to change your own password.

**Comment by pcmerc** [comment]
Logically, why would you be able to change the user password from snipeIT if your using LDAP. LDAP is read-only. It's not 2 way. SnipeIT then queries LDAP for the user password is my understanding & also how I see it working in my ENV.

**Comment by snipe** [comment]
Perhaps the solve is a UX issue. If the user is imported from LDAP, the update password is disable?

**Comment by klemenkobetic** [comment]
jes, my point exactly. or at least a warning.

**Comment by dc53000** [comment]
If the LDAP server ACLs are set appropriate, you actually can set your password over LDAP. There is nothing inherent about the LDAP directory being read-only.

There is an example of this here: http://php.net/ldap-modify-batch

Not that I'm suggesting it be implemented this way. The UX change is probably the best method.

**Comment by snipe** [comment]
I'm not interested in adding the ability to change LDAP passwords through Snipe-IT. That's outside the scope of what we're trying to do here, and will only add to admin/support overhead and user confusion.
