### ISSUE TITLE
LDAP Sync errors

### ISSUE THREAD

**Issue by pgigroup** [snipe/snipe-it#1218]
Once I got the connection string to work properly I attempted a Sync and got a "Woops" error page.  After enabling the debug option I received the following message:

 ErrorException (E_WARNING)

ldap_set_option(): supplied argument is not a valid ldap link resource 

![ldap error](https://cloud.githubusercontent.com/assets/14879628/10230924/e0fc2376-684d-11e5-9336-4cde7be6d4b9.PNG)

Not sure what wrong considering this was not a file I needed to config.

**Comment by snipe** [comment]
Did you set up your `app/config/production/ldap.php` file?

**Comment by pgigroup** [comment]
Yes It has been set up with our server credentials using the host name.  Before I had the connection string I would only get a connection error.  Now that I have the string right I receive this error…. At lease I think it’s right ☺

Thank You,

Timothy Wrinkle
Technical Services Specialist
Potpourri Group, Inc.
(978) 215-3800

**Comment by snipe** [comment]
My only guess is that something is misconfigured in your ldap config file. This works for others. :-/

**Comment by pgigroup** [comment]
OK I will keep at it to see where my error is.

Thank You,

Timothy Wrinkle
Technical Services Specialist
Potpourri Group, Inc.
(978) 215-3800

**Comment by snipe** [comment]
If you want to post your ldap config here (redacting private info) we can try to help troubleshoot.

**Comment by pgigroup** [comment]
I had a typo in the ldap url, not I only have the invalid credentials error.

Thank You,

Timothy Wrinkle
Technical Services Specialist
Potpourri Group, Inc.
(978) 215-3800

**Comment by pgigroup** [comment]
OK I give what’s wrong here?






<?php

return array(

    /*
    |--------------------------------------------------------------------------
    | URL
    |--------------------------------------------------------------------------
    |
    | URL for the LDAP server. This should start with ldap://, for example:
    | ldap://ldap.yourserver.com
    |
    */
    'url' => "ldap://00itsv013.cvinet.local/",


    /*
    |--------------------------------------------------------------------------
    | Username
    |--------------------------------------------------------------------------
    |
    | Username to use to connect authenticate to LDAP, for example:
    | cn=read-only-admin,dc=example,dc=com
    |
    */
	'username' => "cn=PGIInventory,dc=domain,dc=local",

	/*
    |--------------------------------------------------------------------------
    | Password
    |--------------------------------------------------------------------------
    |
    | Password to use when authenticating to LDAP.
    |
    */
	'password' => "password",

	/*
    |--------------------------------------------------------------------------
    | Basedn
    |--------------------------------------------------------------------------
    |
    | The base where the search for users will be executed, for example:
    | dc=example,dc=com
    |
    */
	'basedn'   => "dc=cvinet,dc=local",


	/*
    |--------------------------------------------------------------------------
    | Filter
    |--------------------------------------------------------------------------
    |
    | The search filter for the LDAP query. This probably does not have to be
    | changed.
    |
    */
	'filter' => "&(cn=*)",


	/*
    |--------------------------------------------------------------------------
    | LDAP field names that will be retrieved to create a user.
    |
    | Using the username as an example:
    | If I set 'result.username' => 'my-org-username', the code will connect to
    | LDAP as follows (where $results[$i] represents a row in the LDAP query:
    | $username-to-insert-in-snipe-it = $results[$i]["my-org-username"][0]
    |
    |--------------------------------------------------------------------------
    |
    | The search filter for the LDAP query.
    | Note: all these fields are required, and they should all be lowercase.
    |
    */
    'result.username' => "",
    'result.last.name'  => "",
    'result.first.name' => "",

    /*
    | These fields are optional as not all LDAP directories will have it.  If yours
    | does not have them, just leave these blank and the extra check will
    | be omitted.
    */
    'result.active.flag' => "",
    'result.emp.num'  => "",
    'result.email' => "",

    /*
    |--------------------------------------------------------------------------
    | LDAP filter query for authentication
    |--------------------------------------------------------------------------
    |
    | The LDAP query that we want to execute when authenticating a user. This
    | should not have to be changed.
    |
    */
    'authentication.filter.query' => "uid=",

    /*
    |--------------------------------------------------------------------------
    | LDAP Version
    |--------------------------------------------------------------------------
    |
    | Version of LDAP you are using.
    |
    */
    'version' => 3,


);

**Comment by snipe** [comment]
```
 | Note: all these fields are required, and they should all be lowercase.
    |
    */
    'result.username' => "",
    'result.last.name'  => "",
    'result.first.name' => "",

```

**Comment by pgigroup** [comment]
Correct I just left them out due to their naming scheme

Thank You,

Timothy Wrinkle
Technical Services Specialist
Potpourri Group, Inc.
(978) 215-3800

**Comment by snipe** [comment]
I don't understand what you mean

**Comment by pgigroup** [comment]
I deleted those entries before I sent it to you… unless a specific php code belongs there and then I wrote that part wrong.  Is there an example of how that section should look?

**Comment by snipe** [comment]
They map to the fields in your LDAP system. For example:

```
'result.username' => "uid",
'result.last.name'  => "sn",
'result.first.name' => "givenName",
```

**Comment by snipe** [comment]
What is the specific error you're getting now?

**Comment by pgigroup** [comment]
![ldap error](https://cloud.githubusercontent.com/assets/14879628/10232106/a10ae8ea-6854-11e5-910f-6c3ddf626e74.PNG)

I have double checked the user name and password they are both correct and able to log into the server normally but when applied here with ldap I get invalid credentials.

**Comment by pgigroup** [comment]
Also i can use the credentials with LSAPExplorer2 with no issue

**Comment by snipe** [comment]
That error is coming directly from your LDAP server though.

**Comment by pgigroup** [comment]
So my guess is that I have written the php log in wrong somehow.

**Comment by snipe** [comment]
I don't think the DN should have a trailing slash

**Comment by snipe** [comment]
This is a working LDAP config I have for a public test server. (The version is a little older, so a few of the optional fields aren't there and the order is different, but you can get the idea.)

```
<?php

return array(

    /*
    |--------------------------------------------------------------------------
    | LDAP Version
    |--------------------------------------------------------------------------
    |
    | The version of LDAP you're using.
    |
    */
    'version' => 3,

    /*
    |--------------------------------------------------------------------------
    | URL
    |--------------------------------------------------------------------------
    |
    | URL for the LDAP server.
    |
    */
    'url' => "ldap://ldap.forumsys.com",


    /*
    |--------------------------------------------------------------------------
    | Username
    |--------------------------------------------------------------------------
    |
    | Username to use to connect authenticate to LDAP.
    |
    */
	'username' => "cn=read-only-admin,dc=example,dc=com",

	/*
    |--------------------------------------------------------------------------
    | Password
    |--------------------------------------------------------------------------
    |
    | Password to use when authenticating to LDAP.
    |
    */
	'password' => "password",

	/*
    |--------------------------------------------------------------------------
    | Basedn
    |--------------------------------------------------------------------------
    |
    | The base where the search for users will be executed.
    |
    */
	'basedn'   => "dc=example,dc=com",


	/*
    |--------------------------------------------------------------------------
    | Filter
    |--------------------------------------------------------------------------
    |
    | The search filter for the LDAP query.
    |
    */
	'filter' => "&(cn=*)",


	/*
    |--------------------------------------------------------------------------
    | LDAP field names that will be retrieved to create a user.
    |
    | Using the username as an example:
    | If I set 'result.username' => 'my-org-username', the code will connect to
    | LDAP as follows (where $results[$i] represents a row in the LDAP query:
    | $username-to-insert-in-snipe-it = $results[$i]["my-org-username"][0]
    |
    | Note: all these fields are required.
    |--------------------------------------------------------------------------
    |
    | The search filter for the LDAP query.
    |
    */
    'result.username' => "uid",
    'result.emp.num'  => "",
    'result.last.name'  => "sn",
    'result.first.name' => "cn",
    'result.email' => "mail",

    /*
    | This field is optional as not all LDAP directories will have it.  If yours
    | does not have it, just leave this field blank and the extra check will
    | be omitted.
    */
    'result.active.flag' => "",

    /*
    |--------------------------------------------------------------------------
    | LDAP filter query for authentication
    |--------------------------------------------------------------------------
    |
    | The LDAP query that we want to execute when authenticating a user
    |
    */
    'authentication.filter.query' => "uid="
);
```

**Comment by pgigroup** [comment]
OK, I think it has to do with the user account I’m trying to use.  I will do some reconfiguring and get back to you

**Comment by pgigroup** [comment]
I have it working now, the issue was that I had the username string written incorrectly

**Comment by snipe** [comment]
Great, thanks for the update!

![adventure-time_finn-wand](https://cloud.githubusercontent.com/assets/197404/10233953/65ee6c72-6846-11e5-866a-f1a089089d8b.gif)

**Comment by mahesh2471990** [comment]
'result.username' => "uid",
    'result.emp.num'  => "",
    'result.last.name'  => "sn",
    'result.first.name' => "cn",
    'result.email' => "mail",


Where do i get uid. I my active directory if i go to Attribute Editor Uid shows not set? what to do? @snipe
