### ISSUE TITLE
Class 'Patchwork\Utf8\Bootup\' not found

### ISSUE THREAD

**Issue by magic2110** [snipe/snipe-it#1219]
OS: ubuntu-14.04.3-server-amd64
Docker: 1.8.2
PHP: 5.6
Apache: Apache2 Ubuntu

I've verified docker, php and apache have installed correctly. I've gone over the snipeit documentation and believe I have edited my app.php and database.php correctly and run the mysql commands in the docker section of the installation without any errors. 

Installation and updating of composer work without error but when I try to run this command:
sudo php artisan app:install --env=production

it returns this error:
PHP Fatal error: Class 'Patchwork\Utf8\Bootup' not found in /home/(myusername)/snipe-it/bootstrap/autoload.php on line 45

I've tried deleting my composer.lock file and running a composer install, update and dump-autoload in various orders and I found a suggestion to add "patchwork/utf8": "1.1.*" in the composer.json file under the require section and run a composer update but this didn't appear to work either. I am very novice at linux/docker.

Any direction to a successful installation would be helpful.

**Comment by snipe** [comment]
Did you do the dump autoload and then update, or the other way around?

**Comment by magic2110** [comment]
I've tried an install command then autoload and tested, update then autoload and tested, an autoload then update and tested, could not get any variation of the error to occur in any order.

**Comment by snipe** [comment]
Try `mv ~/.composer/cache ~/.composer/cache.bak` and re-running the install

**Comment by magic2110** [comment]
No luck, still the same error. Should I delete my SnipeIT install directory and try again from the beginning?

**Comment by snipe** [comment]
I honestly don't know. This only happens every now and then to only a tiny handful of users. It's not something with Snipe-IT, but rather something funny with composer, and I've never been able to track down a single explanation or solution. Picking around with the composer dump-autoload is usually the only way to fix it.

I would try this before completely reinstalling:

1. Delete everything in your vendors directory
2. Delete your `composer.lock` file
3. `mv ~/.composer/cache ~/.composer/cache.bak`
4. `php composer.phar dump-autoload`
5. `php composer.phar update ---no-dev --prefer-source`

If that *still* doesn't work, reinstalling might be the only option - and even then, since it's a composer quirk, I don't know if it will. Some variation of these things usually fixing it for people, but we never really know why it gets stuck on that library.

**Comment by magic2110** [comment]
Thanks for the help! I'm glad to know it's not me screwing something up. I'll play with it and see if I can get it going. I'll report back if I find out anything that could be useful to you.

**Comment by snipe** [comment]
No, it's definitely not you (at least not that I'm aware of). It's one of those Heisenbugs that's impossible to reproduce on our end, and various versions of the steps above usually fix it for people, though we still never really know why or what made it break in the first place. :(

![butthole](https://cloud.githubusercontent.com/assets/197404/10239296/5f217544-6880-11e5-96b3-46a15b936ff4.gif)

**Comment by magic2110** [comment]
I ended up just deleting my installation and re-downloading. It works now for whatever reason. I like that response gif though! Its even better now that I noticed that anti-tank metal spikey thing in front of his desk. Google tells me they're called Czech hedgehogs haha

**Comment by snipe** [comment]
See what I mean. Crazy voodoo. There is NO reason why that should have worked when you repeated all of the same steps as the first time you did it. And yet. :-/

![cant-trust-the-system](https://cloud.githubusercontent.com/assets/197404/10253042/0256f954-68f0-11e5-8312-0df237211528.gif)

Anyway, I'm glad it's sorted out for you.

**Comment by krypsin** [comment]
Got same issue here - tried it on 2 different hosting providers!

Exact same setup/process as @magic2110 except running on a CentOS server.

@magic2110 can I ask whether you cloned the repo or just downloaded the ZIP and unzipped or what?

**Comment by magic2110** [comment]
It was a while ago so I don't remember the details but I know I downloaded the zip vs cloning it.

Sent from a mobile device.

On Mar 23, 2016, at 4:10 AM, krypsin <notifications@github.com<mailto:notifications@github.com>> wrote:


Got same issue here - tried it on 2 different hosting providers!

Exact same setup/process as @magic2110<https://github.com/magic2110> except running on a CentOS server.

@magic2110<https://github.com/magic2110> can I ask whether you cloned the repo or just downloaded the ZIP and unzipped or what?

-

**Comment by snipe** [comment]
Did you guys follow the process here? http://docs.snipeitapp.com/common-issues.html#php-fatal-error-class-patchworkutf8bootup-not-found-in-bootstrapautoloadphp-on-line-43
