### ISSUE TITLE
Bug - Accessory name missing in history

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#1223]
when checking in accessory assets the accessory name is missing.

![image](https://cloud.githubusercontent.com/assets/10247644/10318150/188b86f6-6c36-11e5-9d86-bf2a8c3f4c3f.png)

**Comment by snipe** [comment]
Can you reproduce this on the demo?

**Comment by snipe** [comment]
This looks like it's working as expected on the demo. Anything you can tell me about those users or those accessories that might make them behave funny?

<img width="723" alt="screen shot 2015-10-06 at 2 44 42 pm" src="https://cloud.githubusercontent.com/assets/197404/10323575/cee232a4-6c38-11e5-8baf-5b05d34340ee.png">

**Comment by kobie-chasehansen** [comment]
Looks like I just needed to update. pulled DEV branch and all is well. sorry about that.

![image](https://cloud.githubusercontent.com/assets/10247644/10326847/f08146c2-6c6d-11e5-9b37-e50d831896cd.png)

**Comment by snipe** [comment]
![thumbs-up](https://cloud.githubusercontent.com/assets/197404/10326850/dad35d4c-6c54-11e5-9f9a-821a541eb8e4.gif)
