### ISSUE TITLE
[Feature Request]: Deleted meta status

### ISSUE THREAD

**Issue by StarlessNights** [snipe/snipe-it#12235]
### Is your feature request related to a problem? Please describe.

When getting a hardware by id through the API, that is the [GET /hardware/:id](https://snipe-it.readme.io/reference/hardware-by-id) endpoint, it's possible that the returned object is in fact deleted from Snipe-IT. As far as I can tell, there are two ways to infer this. One is to note that in this case `deleted_at` field is non-null, and the second is to check if `available_actions.restore` is true.

This is all very convoluted _and undocumented!_

Intuitively, one would expect this deletedness to show up in the `status_label` object, but this isn't the case. 

### Describe the solution you'd like

I suggest adding another meta status `deleted`. In the API response this would show up in the `status_label.status_meta` field.

To my knowledge there are no other meta statuses than `deployed`, which shouldn't cause problems because it's impossible to delete an asset that's deployed. So there shouldn't be clashes.

### Describe alternatives you've considered

Since it's at least somehow possible to reason about the object's deletedness through the API, we could get away with just documentation. Instruct people that they should check the `deleted_at` field. And also about the fact that this field gets nulled when the asset is restored, which isn't obvious either.

**Comment by snipe** [comment]
We make it pretty clear throughout the documentation (and it's visible in the API explorer) that we use soft deletes. We do not expect to make changes to the status label meta values at this time.
