### ISSUE TITLE
Upgrade

### ISSUE THREAD

**Issue by fpinsurance** [snipe/snipe-it#1224]
I'm trying to upgrade to 2.0.3, but the version doesn't change when I move all of the files and run the necessary commands from composer.

System Information
Snipe-IT version: v2.0-125-g9b04954
PHP Version: 5.6.0
Laravel Version: 4.2.17

I'm copying the files to my SnipeIT installation and overwriting all files.  I then proceed to run the following commands:

composer.phar install --no-dev --prefer-source
composer dump-autoload
php artisan migrate

**Comment by snipe** [comment]
Looks like the versioning script didn't fire correctly on the latest tags. As long as it match this, you should be good to go: https://github.com/snipe/snipe-it/blob/master/app/config/version.php
