### ISSUE TITLE
Custom Report Omits "Purchase Cost" Column Heading

### ISSUE THREAD

**Issue by moterpent** [snipe/snipe-it#1226]
When selecting:

   Reports -> Custom Asset Report

...and selecting the "Purchase Cost" column, the resulting csv excludes the column "Purchase Cost" heading and any following headings are shifted one position to the left.

**Comment by ddreier** [comment]
I'm seeing the same thing on my v2.0.3. When I selected all of the columns, Purchase Cost wasn't omitted but it was in the wrong place (8 columns to the right). So each column heading after Purchase Date was incorrect (shifted left).
