### ISSUE TITLE
Database connection environment variables documentation (docker)

### ISSUE THREAD

**Issue by btrepp** [snipe/snipe-it#1227]
What are the variables that are required to connect to the database using docker?.

I have a MariaDB installation on a different machine, and wish to spin up snipe-it using docker on another. I need to tell it what connections to use, but can't seem to find what env vars are needed
in the documentation.

**Comment by fpalmcrantz** [comment]
Is http://docs.snipeitapp.com/installation/server/docker.html what you're looking for? There's a section that has the following line with the relevant env variables

`docker run --name mysql -e MYSQL_ROOT_PASSWORD=SUPERDUPERSECRETPASSWORD -e MYSQL_DATABASE=snipeit -e MYSQL_USER=snipeit -e MYSQL_PASSWORD=tinglewingler -d -p $(boot2docker ip)::3306 mysql`

**Comment by btrepp** [comment]
Hi there,

I've seen that, back the docs/that line refer to creating the mysql container, which is then linked in later. 
Are the exact same variables used in the snipe-it container?.
Does the snipe-it container support mariadb?. Those connection strings say mysql. Or does it just look for those environmental variables for both databases?.
