### ISSUE TITLE
Setup automated builds on dockerhub.

### ISSUE THREAD

**Issue by btrepp** [snipe/snipe-it#1228]
I've set one up of fork here https://hub.docker.com/r/btrepp/snipe-it/.

It would be great if snipe/snipe-it managed an official automated docker build on dockerhub. This will build the images when a git change is done, or when the FROM docker image file is updated.

It also specifies tags, so you can keep upto date builds of the different tagged versions.

**Comment by snipe** [comment]
I've set up an automatic build, but it still says "creating" and the UI isn't very helpful, so I don't know if it's working.

**Comment by snipe** [comment]
https://hub.docker.com/r/snipe/snipe-it/

**Comment by btrepp** [comment]
Thanks,

Its great to be able to pull official images of dockerhub :).
