### ISSUE TITLE
Importing people generates "Oh no!  Server Error: 500 (Internal Server Error)" message

### ISSUE THREAD

**Issue by mevere** [snipe/snipe-it#1231]
I am somewhat new to SnipeIT. I have it installed on a virtual server. I have a .CSV file with the appropriate header row (firstName, lastName, email). When I attempt to import the file using the IMPORT button in the upper-right of the PEOPLE screen, I get this message: "Oh no! Server Error: 500 (Internal Server Error)". Can someone tell me what I am doing wrong? Is it a permissions issue? My user has allow set for Superuser, Admin rights, View reports. Any assistance you can offer would be greatly appreciated! Thanks.

**Comment by snipe** [comment]
http://docs.snipeitapp.com/getting-help.html

**Comment by snipe** [comment]
You need to tell us what the errors are in order for us to help you.

**Comment by sehamiltonmsdwt** [comment]
I am having the same issue, however I am hosted with Snipeit.
