### ISSUE TITLE
Asset - Categories

### ISSUE THREAD

**Issue by PropTim** [snipe/snipe-it#1232]
Just wondered if we could get the Asset Cat's to show on the assets page? 

That's all really :) overall, pretty good. But there are some inconsistencies between the data entered and the data shown. What's the point of an Asset Cat if I can't sort by it? 

Cheers

Tim

**Comment by snipe** [comment]
Asset categories contain characteristics that determine additional business logic. We can add it to the asset listings page, but it's not a purely cosmetic/organizational function.

**Comment by PropTim** [comment]
Oh jesus. My bad. It's been a long day. I meant the accessories page.

Currently, it shows:
name - total - avail - checkout etc.

It's be absolutely delicious if it showed the category that was inserted into the accessory creation. i.e. 
name - category -etc.

I've got my accessories listing 4GB DDR3, 2GB DDR3, etc.

If it could show name: 4GB. Category: DDR3... that'd be a perfect solution.

That way I can easily see all DDR3/2/1/orwhateverelse all from just sorting, just like in the asset pages.

I hope that makes sense. Like I said, long day!

Cheers

**Comment by PropTim** [comment]
<3 thanks Snipe. :+1:

**Comment by snipe** [comment]
![excited seal](https://cloud.githubusercontent.com/assets/197404/10405361/3e8b464e-6e8d-11e5-91f3-dd74c817b0db.gif)

**Comment by PropTim** [comment]
hahaha. Love it. Thanks again.
