### ISSUE TITLE
LDAP search filter syntax issue

### ISSUE THREAD

**Issue by pcmerc** [snipe/snipe-it#1234]
Is there a reason this filter doesn't work?
'filter' => "(&(objectCategory=person)(objectClass=user)(!userAccountControl:1.2.840.113556.1.4.803:=2))",

A single filter does, for example?

'filter' => "&(objectCategory=person)",

**Comment by ddreier** [comment]
The outside parenthesis are added by Snipe-IT. If you remove them it'll work.

**Comment by tolleiv** [comment]
Hi,
in version 2.1.0 this resolution doesn't work for me.

The sync is broken with both versions:

"&(objectCategory=person)(objectClass=user)(!userAccountControl:1.2.840.113556.1.4.803:=2)"
"(&(objectCategory=person)(objectClass=user)(!userAccountControl:1.2.840.113556.1.4.803:=2))"

With both the error "Error from LDAP Server:Bad search filter" is shown, while the standard "&(cn=*)" works.

Any suggestions?

**Comment by ddreier** [comment]
Yes, you need an extra set of parenthesis around the userAccountControl section, but not including the exclamation mark. Like this: `(!(userAccountControl:1.2.840.113556.1.4.803:=2))`
