### ISSUE TITLE
Activity report timestamp inconsistency.

### ISSUE THREAD

**Issue by dkroshko** [snipe/snipe-it#1235]
Snipe IT version: (v2.0-148)
CentOS release 6.7

Activity report is logging check-in/check-out time stamps inconsistently. Some time stamps are in 24:00:00 others are in 12:00:00 format, please help :)

**Comment by dkroshko** [comment]
does anyone else notice this behavior or just my wonky setup?

**Comment by snipe** [comment]
I'm not able to reproduce this, and I'm not sure how it could be possible. We use `{{{ $log_action->created_at }}}`, which would always be in YYYY-MM-DD hh:mm:ss format

**Comment by xiao-mai-zi** [comment]
I have faced the same issue.

Snipe-IT version: v2.0.3

**Comment by snipe** [comment]
Can I see screenshots or something? I can't reproduce this.

**Comment by dkroshko** [comment]
Here is a screenshot, note the 12hour format vs 24hour format
[cid:image001.png@01D10D77.4BD4C680]

**Comment by snipe** [comment]
@dkroshko can't email images to GitHub, you have to use the web interface

**Comment by dkroshko** [comment]
Here you go:
![assetlog screenshot](https://cloud.githubusercontent.com/assets/15057766/10702567/5fc08db8-797f-11e5-9964-a74e8f92b183.png)

**Comment by snipe** [comment]
I'm not seeing inconsistency there. Can you point out a particular record?

**Comment by dkroshko** [comment]
Its specifically the format the time is recorded in - varies from 24hour format (0-23) to 12hour format (0-12). Timestamps in the log appear that some assets are checked out at 2am or 4am (04:12:31 vs 16:12:31)

**Comment by snipe** [comment]
Is it possible that you're timezone is not set correctly in your `app/config/app.php`? There is nothing we're doing in the code to change the output, so it makes more sense that the input is being logged wrong. Can you look in the database and see what the actual values are in the database?

**Comment by dkroshko** [comment]
I think timezone is correct in  app/config/app.php, I have it as:

'timezone' => 'America/Los_Angeles',

I checked the db and found something interesting: From asset_logs, the "created_at" column reflects the inconsistent time format mentioned (sometimes 12h format)... but 'updated_at' column always reflects 24 hour format. 

| 193 |       1 | checkout     |       38 |           504 |        NULL | 2015-10-22 02:43:11 | hardware   |                                                                            | NULL                                          | 2015-10-22 14:43:11 |                NULL | NULL         | NULL                |         NULL |        NULL |          NULL | NULL             |      NULL |
|

**Comment by snipe** [comment]
Can you pull the latest from develop and tell me if this issue is resolved?

**Comment by dkroshko** [comment]
FIXED!!! YOU ARE A SAINT!!!

**Comment by snipe** [comment]
![baymax-balalala](https://cloud.githubusercontent.com/assets/197404/10705051/ec3ae580-798f-11e5-90f2-e9e99b470e24.gif)
