### ISSUE TITLE
Error when running Activity Report or Custom Report with Location option

### ISSUE THREAD

**Issue by dkroshko** [snipe/snipe-it#1236]
Encountering reporting error, only when clicking on Asset Report, all other built in reports work fine. Custom report fails when checking having Location checked, if location is left unchecked custom report runs.

Snipe IT version: v2.0-148-gff6fe33
CentOS release 6.7
Apache/2.2.15
PHP/5.4.45 
Laravel Version	4.2.17

Error with debug mode on
===========================
ErrorException (E_ERROR)
HELP
Trying to get property of non-object (View: /usr/local/snipe-it/app/views/backend/reports/asset.blade.php)
Open: /usr/local/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php
		// an exception is thrown. This prevents any partial views from leaking.
		try
		{
			include $__path;
		}
		catch (\Exception $e)
		{
			$this->handleViewException($e, $obLevel);
		}
 
GET Data empty
POST Data empty
Files empty

app/storage/logs
======================
Next exception 'ErrorException' with message 'Trying to get property of non-object (View: /usr/local/snipe-it/app/views/backend/reports/asset.blade.php)' in /usr/local/snipe-it/app/storage/views/507b316e840fb7726a84014b7e704a88:105
Stack trace:
#0 /usr/local/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /usr/local/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/usr/local/snip...', Array)
#2 /usr/local/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/usr/local/snip...', Array)
#3 /usr/local/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#4 /usr/local/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#5 /usr/local/snipe-it/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#6 /usr/local/snipe-it/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /usr/local/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /usr/local/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 /usr/local/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /usr/local/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /usr/local/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /usr/local/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /usr/local/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 /usr/local/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /usr/local/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /usr/local/snipe-it/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /usr/local/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /usr/local/snipe-it/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []

/var/log/httpd/access_log
==================================
192.168.1.107 - - [09/Oct/2015:16:54:57 -0700] "GET /admin/settings/backups HTTP/1.1" 200 42102 "http://192.168.1.253/admin/settings/backups" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
192.168.1.107 - - [09/Oct/2015:16:55:04 -0700] "GET / HTTP/1.1" 200 42064 "http://192.168.1.253/admin/settings/backups" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
192.168.1.107 - - [09/Oct/2015:16:57:13 -0700] "GET /reports/activity HTTP/1.1" 200 77627 "http://192.168.1.253/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
192.168.1.107 - - [09/Oct/2015:17:09:04 -0700] "GET /reports/assets HTTP/1.1" 500 102358 "http://192.168.1.253/reports/activity" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"
192.168.1.107 - - [09/Oct/2015:17:12:22 -0700] "GET /reports/assets HTTP/1.1" 500 102362 "http://192.168.1.253/reports/activity" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36"

**Comment by snipe** [comment]
This has been fixed on the `develop` branch.

**Comment by sunjermen** [comment]
I have the same trouble. How did you solve it? 
snipe: After it was solved on develop branch, do you have new release?

**Comment by dkroshko** [comment]
There was a little more to my problem - In my case, the “asset_logs” table had rows where “location_id” value set which did not exist in locations table.

I compared location_id from locations:
mysql> select * from locations;

against location_id’s set for assets in:
            mysql> select * from asset_logs;

The special case with my scenario was more than likely due to my manipulation of database tables manually…
