### ISSUE TITLE
Trying to host a site on a Linux farm with SSL forced on the load balancer

### ISSUE THREAD

**Issue by mpiet** [snipe/snipe-it#1241]
Hi there,

This one is kind of strange. We are trying to host a site on a Linux farm with SSL forced on the load balancer, but traffic from the servers to the load balancer is still served over HTTP. When I go to the site, I get a rudimentary HTML page and a warning from Chrome that the page has insecure content. I turned debugging on, but it doesn't display any data.

Thanks.

**Comment by mpiet** [comment]
So I fixed my initial problem. I finished reading the documentation and implemented the extra line in the  Running Snipe-IT Through a Reverse Proxy part and I can get into the site! Thanks for all the hard work.

**Comment by ddreier** [comment]
> I finished reading the documentation

Lol, does wonders doesn't it?
