### ISSUE TITLE
Deleting assets or locations

### ISSUE THREAD

**Issue by sgomez12** [snipe/snipe-it#1242]
I just started using Snipe-IT and noticed that I come to a bit of a dilemma when deleting assets or locations. I noticed that if an asset or location is created and you then delete it, whether by accident or because you did not think it necessary, you cannot create it again if you wanted to. Is there a way around this so that even if something was deleted I can still create it again if I wanted?

**Comment by Mooninaut** [comment]
I just ran into this myself. I mistakenly bulk-imported a bunch of bogus locations (and then had to delete them one-by-one, but that's another issue), deleted them all (one-by-one) and then could not recreate any that I actually wanted.

**Comment by snipe** [comment]
This should be fixed in the upcoming v3.
