### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by blhf** [snipe/snipe-it#1244]
Secure Connection Failed

An error occurred during a connection to localhost:8080. SSL received a record that exceeded the maximum permissible length. (Error code: ssl_error_rx_record_too_long)

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

I'm having this kind of error after installing snipeit in xampp Im using windows pc running windows 7.

I followed every step in the documentation.
please help.

**Comment by snipe** [comment]
Are you actually running this over SSL?

**Comment by blhf** [comment]
Yep. I already edited htaccess file and uncommented # Uncomment these two lines to force SSL redirect
     RewriteCond %{HTTPS} off
	 RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

**Comment by snipe** [comment]
Sounds like some servers miscobfigurations to me. Check out http://stackoverflow.com/questions/119336/ssl-error-rx-record-too-long-and-apache-ssl

**Comment by blhf** [comment]
Still not fixed for me. Maybe I'll just try the demo and see if I can use it in our company. :)

**Comment by rita2clark** [comment]
"First check that in : 
1) Internet Explorer- go to "tools/internet options/advanced" in the settings box, scroll all the way to the bottom and select "Use TLS 1.0" and it will fix the problem. 
SSL 2.0 or 3.0 and these are should also be selected. 

2) Google Chrome-Click "wrench" sign on the tope right of it.Click "Options" then "Under the bonnet" in network click "Change Proxy Settings" and follow hte steps above as in Internet Explorer. 


IF THIS DID NOT WORK THEN DO THIS 

STEP-1: Unhide all the files and folders. 
STEP-2: Then,go to,, C:\Windows\System32\drivers\etc\hosts. 
Step-3: Right click on hosts file,then click properties. 
Then click security tab. After that click edit. 
STEP-4: Here,click system and you have to check on allow full control and uncheck deny. 
STEP-5: Click OK and then OK. 
STEP-5: Now delete the hosts file. "
You could read google forum tips from  here - http://productforums.google.com/forum/#!msg/chrome/gWOCNmiVtfQ/Y8iUxl6juYgJ
  
or you get all the details solution about err_ssl_protocol_error from here - http://www.toppctech.com/best-fix-err-ssl-protocol-error/. I hope this will work and fix the error

**Comment by blhf** [comment]
Got through this error but now I'm receiving ERROR:500 Internal Server
Error. What to do next?

**Comment by blhf** [comment]
Hi @snipe  please closed this issue. I am able to solved the issue. :+1:
