### ISSUE TITLE
Notes / user&pass on multi-seat licenses

### ISSUE THREAD

**Issue by PropTim** [snipe/snipe-it#1245]
Example: Office365 has online licensing facility. We'd like to track who has what by adding each account to snipe, however we have nowhere to store username and password info. In theory, we could add this as a note, but the notes don't appear on the user account or the license report.

If I click on our license "Office 365", it will show who it's checked out to, but not the note.

If you could either add the option to assign additional information such as username and passwords, or to show the notes on both the multi-seat license page and the user page, that'd be great.

Licenses -> click [License Name]:
![capture2](https://cloud.githubusercontent.com/assets/15049080/10452560/beec276e-719d-11e5-8c18-b7e61f22ac64.PNG)

Users -> click [Users Name]:
![capture3](https://cloud.githubusercontent.com/assets/15049080/10452561/bf06b796-719d-11e5-8fbf-717a5666209c.PNG)

thoughts? :)

**Comment by PropTim** [comment]
Any word on this? 

Cheers
Tim

**Comment by victoriapak** [comment]
In v3, the notes appear in the Checkout History page
