### ISSUE TITLE
Checking out Accessories to Assets

### ISSUE THREAD

**Issue by PropTim** [snipe/snipe-it#1246]
Hi snipe, again...

Could it be possible to check out an accessory to an asset?

We have some SSD's to deploy, and I've listed them as accessories so we can keep an eye on how many we have, so we'd like to be able to deploy them INTO assets.

The same applies to Ram, Processors, HDDs, etc etc. 

thoughts? 

Cheers

Tim :)
##

**Comment by kobie-chasehansen** [comment]
Think this might be a case where you would use the Maintenance section under the laptop assets.

**Comment by PropTim** [comment]
oh..... well, that just piddled on ones fire. 

I'll take a look and let you know. Thanks.

Tim

**Comment by chriswiggins** [comment]
Wow what timing - I'm wondering if I can do the same thing. Would make it easier to track SSDs  separately from the desktop/laptop for warranty purposes. Anything we can do to help make this functionally possible?

**Comment by ddreier** [comment]
Sub-assets (or checking out assets to assets) is on the roadmap. Not sure of an ETA.

**Comment by PropTim** [comment]
@ddreier -

That's not really the idea. Sorry, I just need to clarify :) :+1: on the sub-assets though.

Accessories consist of Keyboards, Mice, Screens, SSDs, etc. Things that aren't assets on their own, but can be paired to one. Currently, Accessories can be checked out to a person, but who unplugs their keyboard when they go home and takes it with them? 

Also - If a keyboard is paired with a user, when that user leaves the business, or moves desk... by the links, it means that they'll be taking that keyboard with them (and the SSD, mouse and monitor). That's most likely not going to be the case. 

Simply being able to assign an accessory to an asset OR a person (similar to the licenses) would be the best solution IMHO. That way it gives each business the capacity to operate their accessories as they need to.

Thoughts?

**Comment by m4rphel** [comment]
I like the idea of Sub-Assets.

Figured the same problem. Have a PC as Asset and added a SSD later - so it would be nice to track this in a convenient way

**Comment by snipe** [comment]
Well, we're working on a components section. I'm not sure if sub-assets make sense with that in mind. What do you think?

**Comment by PropTim** [comment]
sounds good. :)

**Comment by m4rphel** [comment]
agree :) looking forward for it

**Comment by wilsonben89** [comment]
Apologies for commenting on an old thread - Google brought me here. 

A great use for this feature which I am currently missing out on is being able to assign things like an RSA Authentication Key to a laptop, or a SIM card to a mobile phone.

**Comment by rayvenshire** [comment]
Google also brought me here. 

@snipe -- I'm not sure what you mean by "sub-components"; I have distinct assets and want to check them out to other assets (i.e. I care which SSD/HDD is in a machine); if "sub-components" is what does that, that's great; however, I do want these to be separate, distinct things, so if a sub-component is not equivalent to an asset, I might argue in favor of assets checked out to assets.

**Comment by asmartin** [comment]
+1, I could really use this in my environment. Any status update on this?

**Comment by snipe** [comment]
No update. We're currently running into a blocking issue with full company support and the new polymorphic features, and until we can fix that, there won't be any progress on it.

**Comment by pcbehara** [comment]
Any update on this yet? Can you please let me know ASAP. Thank you

**Comment by amartin3225** [comment]
Are there any updates on this and solving the blocking issue with full company support? This would still be useful for my use case

**Comment by asmartin** [comment]
This would still be useful to me

**Comment by kmoberg** [comment]
@asmartin The feature is available in the current version? I can check out an asset to another asset when needed.

**Comment by asmartin** [comment]
Assets to assets yes but what about accessories to assets?

**Comment by kmoberg** [comment]
@asmartin Ah, I misunderstood. Yeah, that would be nice.

**Comment by wallacj** [comment]
accessories checked out to assets would be great.  makes more sense to check a keyboard out to a workstation than a person.  we have many desks that are shared.

**Comment by Krejar** [comment]
I would like to see accessories checked out to assets.

**Comment by AmberHarding** [comment]
This would be useful.

**Comment by StevenPaulDavid** [comment]
This would be great for desktops where the keyboard and mouse change due to damage, they are not an component their an accessory

**Comment by kale1d0code** [comment]
this would be so awesome
I'm not looking forward to recreating loads of keyboards, mice, and other cables as assets after finding out they can't be checked out to desktops or other devices

**Comment by pathroot** [comment]
This would be useful.

**Comment by pocdusky** [comment]
any news about this feature?
