### ISSUE TITLE
Wrong translation for 'show_mac_address'

### ISSUE THREAD

**Issue by QuestorX** [snipe/snipe-it#1248]
Affected file:
**app\lang\de\admin\models\general.php**
+ Wrong:
'MAC Adressen Feld anzeigen für Assets mit diesses Modell'
+ Correct:
'MAC Adressen Feld anzeigen für Assets mit diesem Modell'

**Comment by snipe** [comment]
You're welcome to submit a correction: https://crowdin.com/project/snipe-it/de

**Comment by QuestorX** [comment]
done :)
Should I correct even more? Is an extra issue needed?

**Comment by snipe** [comment]
You don't need to create issues on wrong translations, you can just suggest corrections through the CrowdIn interface
