### ISSUE TITLE
Dashboard takes me to IIS start page

### ISSUE THREAD

**Issue by xxtheatrainxx** [snipe/snipe-it#1252]
Hello,

When I browse to the dashboard I am, instead, routed to the IIS start page @ server-name-01/ which is strange, as I login @ server-name-01/snipeit/index.php/auth/signin

This is my first experience with IIS/web apps...be gentle!

**Comment by snipe** [comment]
You shouldn't need /index.php in your url - check your rewrite rules if your install is requiring it.

In your `app/config/production/app.php`, what do you have set as your url?

**Comment by xxtheatrainxx** [comment]
I asked one of our developers that has a little more experience with IIS to assist.  He said he added the site to "Default Site" and took out the rewrite rules.  I can browse to the site now, so I guess it worked...maybe not the right way?

app/config/production/app.php - 'url' => 'http://hou-time-01',

**Comment by snipe** [comment]
Why would he take out the rewrite rules? They are part of the installation.

**Comment by xxtheatrainxx** [comment]
He's Australian?

**Comment by xxtheatrainxx** [comment]
I don't know why he added it to the default site, either.  I won't be able to get with him until this evening due to time difference.

**Comment by xxtheatrainxx** [comment]
I believe the rewrite rules were causing an issue with loading the page.  I'll try to find out this evening.  

I tried to follow your instructions for adding RewriteBase /xxx but URL rewrite wouldn't accept it as a valid rule and thus wouldn't allow me to save the imported rules.  

I'm not sure if the above is any help in answering why mistakes were made, but I'm doing my best to keep up in a field I know nothing about.  With all that's said and done, is there a way to get the dashboard to not take me to the IIS start page @ "http://hou-time-01/"?

**Comment by snipe** [comment]
The app uses the `url` value in `app/config/production/app.php`. If you want the dashboard to go somewhere other than `http://hou-time-01/`, change the url value to wherever you want it to point.

**Comment by xxtheatrainxx** [comment]
Thanks, that fixed the problem.  I'm not sure why he did what he did, I never got a good answer from him.  Thanks again!
