### ISSUE TITLE
Ubuntu Install help

### ISSUE THREAD

**Issue by stijni** [snipe/snipe-it#1253]
Hi,

I'm a newbie when it comes down to Ubuntu and Apache, so be kind please ;).

I've installed a clean Ubuntu and ran the script by mtucker6784. Snipe-IT is working just fine, but now I wanted to configure the mail and LDAP. 
For LDAP, I've installed php5-ldap but I don't get the option to import users from LDAP. Could someone explain me what to do step by step (as I'm a newbie).
Second one is the mail. I've configured the settings file, but is there a way to test the settings without having to create a user? It would be nice to see a test button.

Thank you for your help.

**Comment by ddreier** [comment]
I don't know what controls the visibility of the LDAP import button, but did you configure the LDAP settings in app/config/production/ldap.php?

AFAIK there isn't a way within Snipe-IT to send a test email.

**Comment by snipe** [comment]
If there is an `ldap.php` in the environment config directory, the LDAP options will be displayed.

**Comment by stijni** [comment]
Yes, I did configure the settings, but I doesn't show up. I used the settings from another application I use so there shouldn't be many errors in the config file.

**Comment by snipe** [comment]
Can you show me the contents of your `app/config/production` directory?

**Comment by stijni** [comment]
![production_content](https://cloud.githubusercontent.com/assets/15146552/10524366/770105f8-737f-11e5-9f35-458438cf9b79.jpg)
See screenshot. This is from my home computer where I have a vm with about the same config.

**Comment by ddreier** [comment]
What is the URL setting in your ldap.php?

**Comment by stijni** [comment]
I've tried it with a fqdn and an ip address. ldap://explame.domain.com or ldap://x.x.x.x

**Comment by ddreier** [comment]
What happens if you go to http://your-snipe-it/admin/users/ldap? (You should back up your db first, btw)

**Comment by stijni** [comment]
I get the following: LDAP integration has not been configured for this installation.

**Comment by stijni** [comment]
I read in issue 1165 that you have to add the extension to the php.ini file. Which ini file is this?

**Comment by ddreier** [comment]
Looks like [/etc/php5/apache2/php.ini](http://askubuntu.com/questions/356968/find-the-correct-php-ini-file) is probably the right one.

Also, Debian-based linuxes (like Ubuntu) ship with "php5enmod" now. So I think you should be able to run `php5enmod ldap` as well.

**Comment by stijni** [comment]
I've tried php5enmod ldap but that didn't change anything. 
For the extension, I don't know where and how to add it. 
I've checked the phpinfo and ldap is enabled. Any other ideas?

**Comment by snipe** [comment]
FYI, the only time you should see that `LDAP integration has not been configured for this installation` error message is if the LDAP url is not specified. The actual code that spit out that error is:

```
@if (Config::get('ldap.url')=='')
    @Lang('admin/users/message.ldap_not_configured')
@else
...
```

Can you show me your `app/configs/production/ldap.php` file (obscuring but not deleting private info). Also show me the latest few entries from `app/storage/logs`.

**Comment by stijni** [comment]
![image](https://cloud.githubusercontent.com/assets/15146552/11065679/ff2a101a-87c4-11e5-87e8-a0c637392bbf.png)

**Comment by snipe** [comment]
"See screenshot. This is from my home computer where I have a vm with about the same config." <-- can you show me the actual machine you're instilling this on tho? "about the same" isn't the same thing, and I am concerned that there are differences between these two setups. 

The only way you should see the LDAP not configured message is if there is no value for the url in the `ldap.php` file. (I've already shown you the code that determines that.) This makes me think that your local vm and the actual instance you're trying to set this up on are not configured exactly the same (missing the ldap config, it thinks it's a different environment, or ldap config exists in a different environmental config directory). There isn't any other way you'd be seeing that "LDAP not configured" message.

**Comment by stijni** [comment]
The 2 machines I'm talking about is a VM at work and a VM at home. I use the same install script (from mtucker6784) both on Ubuntu 14.04. On both machines there is no option for LDAP sync. I'll try a reinstall.

**Comment by stijni** [comment]
Ok, just reinstalled it at home and it seems to work now. Only difference is that it's 2.0.5 pre. I'll wait for the final release and reinstall it at work.
Thanks for the replies.

**Comment by mtucker6784** [comment]
I'm not sure if your reference to "option for LDAP sync" is for the install script or not, but... If it is, the script does not support LDAP configuration yet. The idea is on the board, but has not been started at this time,
