### ISSUE TITLE
QR Code Broken after upgrade to V2.0.3

### ISSUE THREAD

**Issue by JExactly** [snipe/snipe-it#1255]
After upgrading to 2.0.3(v2.0-125-g9b04954) from 2.0 RC11, It appears that all of my QR Code images are broken. Now I am aware this was an issue, But I thought Ithough that this was resolved in 2.0.3. Can someone please clarify for me if this is true? Any information you need from, just let me know and I will provide it.

Thanks in advance!

**Comment by ddreier** [comment]
Did you go through all of the steps on this page? http://docs.snipeitapp.com/upgrading.html

**Comment by ExactCare** [comment]
Yes, I am runninp snipe in IIS on a Windows Server, So i ran 
composer install via context menu on the folder,then I  ran composer dump-autoload and then artisan migrate from the command prompt.

**Comment by JExactly** [comment]
I Resolved this myself. I re-downloaded the master and ran all the upgrade procedures. QR codes are now appearing again.
