### ISSUE TITLE
Feature Request: Filtering views/Custom Views

### ISSUE THREAD

**Issue by JExactly** [snipe/snipe-it#1256]
I would like to formally request the ability to Filter the views for assets on the column header row. Also maybe the ability to create Custom views of assets based on category etc. I know we can search any filed and that works great. But I think the adding the ability to create a custom view or just filtering by a column value will add ease of use to the system

**Comment by snipe** [comment]
I'm not sure I understand - you can already filter by clicking on the arrows in the headings. Are you asking for something beyond that?

<img width="602" alt="screen shot 2015-10-20 at 5 58 03 pm" src="https://cloud.githubusercontent.com/assets/197404/10625098/3210fcd6-7754-11e5-9420-0b08acc98fc8.png">

**Comment by JExactly** [comment]
Well, yes. You can filter out unwanted values based on the broad search box and the Sort the data from the column headers. I was thinking it might be an amazing feature to be able to filter on the column header. For lack of a better comparison, it would work just like Excel works when you add a Data Filter to a range of Data, You can click on the arrow on the header row of your data and filter by a value or values in a single column.

**Comment by Mooninaut** [comment]
I'd very much like to be able to filter more precisely on individual fields. Like "All assets in location X and sub-locations of X" or "All assets in location Y but not sub-locations of Y."

I'm running a report right now for someone on all assets in their building. Or at least I'm trying to. The search is currently very imprecise. It appears to do an "Or" on all search terms. When I search for eg "Building C" I get all assets with either the word "Building" or the letter "C" in any of their fields, which is not very useful. Unless I take all the spaces out of location names and ensure that no location name is a prefix, suffix or substring of any other location or any other value in any field, I can't filter very effectively.

I can export to a spreadsheet and filter there, but not having to mess around with spreadsheets is why I want an asset management system in the first place.

I'd love options for "exact search", "all keywords", and/or "search only this field" for the main search and for reports.

**Comment by AVenzorSO** [comment]
Advanced searching as described by @Mooninaut is very important to my environment and easily my #1 feature request.

**Comment by cduverne** [comment]
+1 for the custom views part.
It would be great to be able to save custom layouts on assets view.

**Comment by veen1981** [comment]
I would also love to be able to use more advanced filtering!

**Comment by osa-ko** [comment]
Definetely a great feature to be.
