### ISSUE TITLE
Getting errors while run composer install 

### ISSUE THREAD

**Issue by Walmikg** [snipe/snipe-it#1258]
Command: composer install

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for intervention/image 2.3.x-dev -> satisfiable by in
tervention/image[2.3.x-dev].
    - intervention/image 2.3.x-dev requires ext-fileinfo * -> the requested PHP
extension fileinfo is missing from your system.
  Problem 2
    - Installation request for intervention/image dev-master -> satisfiable by i
ntervention/image[dev-master].
    - intervention/image dev-master requires ext-fileinfo * -> the requested PHP
 extension fileinfo is missing from your system.

C:\inetpub\wwwroot\Snipe-IT>

**Comment by Walmikg** [comment]
Please hel to resolve this iisue.

**Comment by Walmikg** [comment]
Please help to resolve this errors

**Comment by brianjking** [comment]
@Walmikg I think you can try to run ```composer update``` prior to ```composer install```?

**Comment by snipe** [comment]
http://docs.snipeitapp.com/common-issues.html#while-running-composer-interventionimage-dev-master-requires-ext-fileinfo---gt-the-requested-php-extension-fileinfo-is-missing-or-not-enabled-on-your-system
