### ISSUE TITLE
Error 500 - Internal Server Error when including an image with model

### ISSUE THREAD

**Issue by patgmac** [snipe/snipe-it#1259]
When I create an asset model, I can do so only if I don't include an image. If an image is included, I get the error 500. 

Snipe-IT 2.0.3
Ubuntu Server 14.04.3

**Comment by LiamKenyon** [comment]
I'm also experiencing this issue.

Same when trying to run a backup.

All files have had the permission fix done.

I'm running on Windows 2008 R2.

**Comment by patgmac** [comment]
This was resolved by installing php-gd (GD library) which was also needed if specifying a company logo in /admin/settings/app/edit. This is listed as a requirement on http://docs.snipeitapp.com/requirements.html but I missed it since I used install.sh to install. 

I see php-gd is included in the yum command, but not the apt-get command.

**Comment by patgmac** [comment]
Submitted pull request: https://github.com/snipe/snipe-it/pull/1261

**Comment by mtucker6784** [comment]
Good catch; thanks.

**Comment by LiamKenyon** [comment]
I have php-gd2 enabled as an extension on my server (Windows 2008 R2) and i'm still getting the issue.

Any ideas?

**Comment by snipe** [comment]
Guys, we can't help debug this issue without error messages. http://docs.snipeitapp.com/getting-help.html

**Comment by LiamKenyon** [comment]
I've actually solved the issue just a second ago, the permissions weren't set for 1 of the suggested folders for user IUSR. once this was done images & backup upload/generation are working.

Simple fix for simple mind as they say..

**Comment by snipe** [comment]
Liam does `app/storage/dumps` exist and is it writable?

**Comment by LiamKenyon** [comment]
Yeah, exists and is writeable.

It's the only outstanding "bug" i have.
