### ISSUE TITLE
User import with LDAP

### ISSUE THREAD

**Issue by thomsonza** [snipe/snipe-it#126]
When checking assets out to users it would be great if it was possible to get a list of users from LDAP rather than having to add each of them individually.

**Comment by snipe** [comment]
Test server here may work for anyone looking to work on this feature: http://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/

**Comment by csayre** [comment]
OK. So I am a little confused here. I have read several requests dealing with LDAP integration for assigning devices to users. Is there a way to do this or not? I see that this case has the ready label. Does that mean that this has been implemented into SNIPE-IT?

**Comment by snipe** [comment]
No, this means it's ready to be worked on

**Comment by csayre** [comment]
Ah ok. I was a little confused. Any Idea of when it will be implemented?

**Comment by snipe** [comment]
Not sure - there aren't a lot of good libraries for LDAp at this point. I know a few people have mentioned they wanted to work on it, but I haven't heard anyone report back on progress, so I would assume it's not been started yet. (I know I haven't been working on it.)

**Comment by csayre** [comment]
The company that I am working for uses ticketos ( I know there were talks of integrating the two projects). Anything more on that? We need a solution that supports ad integration, i just stumbled upon this project today. I hope you guys get ldap or AD integration implemented relatively quickly, I would love to use this at our company, but that is a big selling point for our company.

**Comment by aalaily** [comment]
***If this is still of interest***, I have created and tested an LDAP sync function.  My goal was to create users that would never have access to the system but that use our services... hence I only need to track what they have and potentially communicate with them. 
***How it works***
You configure LDAP via an ldap.php file (url, usrename, password, search query, etc...) and then when you hit sync, the application connects to LDAP and fetches the required fields.  Users are then created sequentially.  For each user, a note is added to indicate that they were created using the LDAP sync script.  In addition all accounts are automatically activated and no passwords are emailed.  I've been able to import 5,000+ users in one go using it.  I'm happy to submit a pull request but will need information on whether or not I need to create a specific branch (or the process defined for this snipe-it)
***Some screenshots***
Screen 1
![ldap-sync](https://cloud.githubusercontent.com/assets/2475759/9267354/ba6bc8b8-421b-11e5-8152-f2ac04fd3b47.png)
Screen 2
![ldap-sync-page](https://cloud.githubusercontent.com/assets/2475759/9267360/c2e0b936-421b-11e5-8cf5-644fab30c909.png)

**Comment by snipe** [comment]
Hi @aalaily - nice work! A few questions:

- How does it handle existing users? 
- How does it handle deleted users (users no longer in LDAP but still in Snipe-IT, OR users that were imported via LDAP sync and were marked as deleted in Snipe-IT)

**Comment by aalaily** [comment]
Hi Snipe,

*** How does it handle existing users? ***
If the user already exists in the system, the code simply skips over them and displays a message "exists" in the result page (which contains a summary of action for each user)
*** How does it handle deleted users (users no longer in LDAP but still in Snipe-IT ***
Right now the code doesn't cross-check.  That is, if the user is not in LDAP but is still in Snipe-IT the user remains untouched.  For this specific case, my thought was to mark them as inactive in Snipe-IT.  That should be fairly easy to do.
*** Users that were imported via LDAP sync and were marked as deleted in Snipe-IT ***
That's a case I haven't tested yet... however, if the user still exists in the user table the code will simply not touch them.

*** Extra functionality ***
I've now been able to integrate LDAP into the login.  Now, if the user has "LDAP" in the "notes" field, the authentication goes against LDAP.

**Comment by snipe** [comment]
This sounds great - I'd love a pull request against the develop branch so I can take a look. Thanks!

**Comment by aalaily** [comment]
No problem! I will submit a pull request and feedback will be much appreciated.

**Comment by aalaily** [comment]
OK... the pull request has been submitted.

**Comment by kobie-chasehansen** [comment]
@aalaily - for existing users, is it matching off the LDAP username or email address?

**Comment by aalaily** [comment]
LDAP username

**Comment by snipe** [comment]
This is now on develop

**Comment by ebjers** [comment]
How can I get the LDAP function added to my installation of Snipe-IT

I am using
Snipe-IT version	v2.0-125-g9b04954
PHP Version	5.4.24
Laravel Version	4.2.17

running on 2012 R2

**Comment by snipe** [comment]
http://docs.snipeitapp.com/installation/configuration.html#optional-ldap-configuration

**Comment by ebjers** [comment]
Thank you

**Comment by klemenkobetic** [comment]
is this just an ldap importer (this means that each time i add an user to ldap i have to manually click import to import the user) or is it an adapter (it actually checks on ldap real time)? or both?

**Comment by ddreier** [comment]
Both-ish. It will import users from your directory into Snipe-IT, and then will attempt to authenticate against the directory for the users that have been imported.

AFAIK it is not actively/regularly checking for new users in your directory.

**Comment by snipe** [comment]
@ddreier You are correct - that's exactly how LDAP integration currently works. :)

**Comment by klemenkobetic** [comment]
interesting functionality. this means that i import users from ldap, change password in ldap and then it doesn't work anymore?

**Comment by snipe** [comment]
If LDAP is enabled, it will attempt to authenticate against the LDAP server before trying a local database user, IIRC

**Comment by japhinma** [comment]
Please can someone help me. I am receiving the following error when attempting to synchronize. 
Validator failed:
The firstname field is required.
The lastname field is required.
The username field is required.

**Comment by japhinma** [comment]
Please can someone help me. I am receiving the following error when attempting to synchronize.
Validator failed:
The firstname field is required.
The lastname field is required.
The username field is required.

**Comment by snipe** [comment]
@NwaEze1 please open a new ticket - this one is closed.
