### ISSUE TITLE
Unable to import assets

### ISSUE THREAD

**Issue by patgmac** [snipe/snipe-it#1260]
When attempting to import assets from a csv, including the sample.csv that is provided, an error 500 is displayed. 

InvalidArgumentException thrown with message "The "--domain" option does not exist."

Stacktrace:
#29 InvalidArgumentException in /var/www/snipe-it-master/vendor/symfony/console/Symfony/Component/Console/Input/ArrayInput.php:177
#28 Symfony\Component\Console\Input\ArrayInput:addLongOption in /var/www/snipe-it-master/vendor/symfony/console/Symfony/Component/Console/Input/ArrayInput.php:139
#27 Symfony\Component\Console\Input\ArrayInput:parse in /var/www/snipe-it-master/vendor/symfony/console/Symfony/Component/Console/Input/Input.php:61
#26 Symfony\Component\Console\Input\Input:bind in /var/www/snipe-it-master/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:225
#25 Symfony\Component\Console\Command\Command:run in /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Console/Command.php:100
#24 Illuminate\Console\Command:run in /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Console/Application.php:101
#23 Illuminate\Console\Application:call in <#unknown>:0
#22 call_user_func_array in /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Foundation/Artisan.php:57
#21 Illuminate\Foundation\Artisan:__call in /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:214
#20 Illuminate\Foundation\Artisan:call in /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:214
#19 Illuminate\Support\Facades\Facade:__callStatic in /var/www/snipe-it-master/app/controllers/admin/AssetsController.php:711
#18 Illuminate\Support\Facades\Artisan:call in /var/www/snipe-it-master/app/controllers/admin/AssetsController.php:711
#17 Controllers\Admin\AssetsController:getProcessImportFile in <#unknown>:0
#16 call_user_func_array in /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:231
#15 Illuminate\Routing\Controller:callAction in /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:93
#14 Illuminate\Routing\ControllerDispatcher:call in /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:62
#13 Illuminate\Routing\ControllerDispatcher:dispatch in /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Routing/Router.php:967
#12 Illuminate\Routing\Router:Illuminate\Routing\{closure} in <#unknown>:0
#11 call_user_func_array in /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Routing/Route.php:109
#10 Illuminate\Routing\Route:run in /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1033
#9 Illuminate\Routing\Router:dispatchToRoute in /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1001
#8 Illuminate\Routing\Router:dispatch in /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:775
#7 Illuminate\Foundation\Application:dispatch in /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:745
#6 Illuminate\Foundation\Application:handle in /var/www/snipe-it-master/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php:34
#5 Barryvdh\Debugbar\Middleware\Stack:handle in /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Session/Middleware.php:72
#4 Illuminate\Session\Middleware:handle in /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php:47
#3 Illuminate\Cookie\Queue:handle in /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php:51
#2 Illuminate\Cookie\Guard:handle in /var/www/snipe-it-master/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23
#1 Stack\StackedHttpKernel:handle in /var/www/snipe-it-master/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:641
#0 Illuminate\Foundation\Application:run in /var/www/snipe-it-master/public/index.php:49

The same error occurs on the demo site so I know it's not site specific.

**Comment by snipe** [comment]
Is this via cli, or the web upload?
