### ISSUE TITLE
Server 500 Internal Server Error

### ISSUE THREAD

**Issue by lutherpros** [snipe/snipe-it#1262]
Im getting a Server 500 Internal Server Error, when a user accepts an item.Can anyone help?
Copy of the logs:

[2015-10-19 12:50:42] production.DEBUG: Authenticating user against database. [] []
[2015-10-19 12:51:46] production.ERROR: exception 'ErrorException' with message 'Creating default object from empty value' in C:\wamp\www\inventory\app\controllers\account\ViewAssetsController.php:214
Stack trace:
#0 C:\wamp\www\inventory\app\controllers\account\ViewAssetsController.php(214): Illuminate\Exception\Handler->handleError(2, 'Creating defaul...', 'C:\\wamp\\www\\inv...', 214, Array)
#1 [internal function]: Controllers\Account\ViewAssetsController->postAcceptAsset('25')
#2 C:\wamp\www\inventory\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(231): call_user_func_array(Array, Array)
#3 C:\wamp\www\inventory\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postAcceptAsset', Array)
#4 C:\wamp\www\inventory\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Account\ViewAssetsController), Object(Illuminate\Routing\Route), 'postAcceptAsset')
#5 C:\wamp\www\inventory\vendor\laravel\framework\src\Illuminate\Routing\Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\\Acc...', 'postAcceptAsset')
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('25')
#7 C:\wamp\www\inventory\vendor\laravel\framework\src\Illuminate\Routing\Route.php(109): call_user_func_array(Object(Closure), Array)
#8 C:\wamp\www\inventory\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 C:\wamp\www\inventory\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 C:\wamp\www\inventory\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 C:\wamp\www\inventory\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 C:\wamp\www\inventory\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 C:\wamp\www\inventory\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 C:\wamp\www\inventory\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 C:\wamp\www\inventory\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 C:\wamp\www\inventory\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 C:\wamp\www\inventory\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 C:\wamp\www\inventory\public\index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []

**Comment by snipe** [comment]
Can you tell me anything about the data for that asset?

**Comment by Dextro** [comment]
I can confirm this. What asset data do you need to debug this issue further?

**Comment by snipe** [comment]
Literally anything.

**Comment by snipe** [comment]
Are you guys still seeing this with the latest on the develop branch?
