### ISSUE TITLE
Windows Install

### ISSUE THREAD

**Issue by Pritesh07** [snipe/snipe-it#1263]
Hi,

I am new to this and there is also no web tutorial so I am trying to follow the documentation to perform the install. I am stuck in the install process of choosing the database for server2012 R2 on a offline server. I don't have access to internet on that server so I have to manually import all files required for install.

Configuration:
I want to know which one I should install (sql express or MSSQL). I am familiar with SQL express and would like to know if this would work.

Install Dependencies:
Do I need to install common updater to use the CLI commands like 'php artisan app:install'

Server Configuration:
Also, When I was setting up IIS, I don't have URL rewrite option. Do I have to install it from http://www.iis.net/downloads/microsoft/url-rewrite for the option to show up under IIS.

**Comment by ddreier** [comment]
> I want to know which one I should install (sql express or MSSQL). I am familiar with SQL express and would like to know if this would work.

Microsoft SQL Server (Express or otherwise) isn't supported. You'll need to use MySQL, MariaDB, or PostgreSQL (I think).

> Do I need to install common updater to use the CLI commands like 'php artisan app:install'

I'm not 100% sure what you mean by this. You have to install PHP for IIS and Composer, which is linked to in the docs: http://docs.snipeitapp.com/installation/composer.html.

> Also, When I was setting up IIS, I don't have URL rewrite option. Do I have to install it from http://www.iis.net/downloads/microsoft/url-rewrite for the option to show up under IIS.

Yup!

**Comment by sequencefive** [comment]
hello
i have this error after installing composer with its dependencies... 
 ErrorException (E_ERROR)

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'itasset.settings' doesn't exist (SQL: select * from `settings` where `settings`.`id` = 1 limit 1) (View: C:\wamp\www\aaa\app\views\backend\layouts\default.blade.php) (View: C:\wamp\www\aaa\app\views\backend\layouts\default.blade.php) 

please help

**Comment by snipe** [comment]
You have to run the cli-installer, per the docs. http://docs.snipeitapp.com/installation/command-line.html
