### ISSUE TITLE
Import function not working correctly

### ISSUE THREAD

**Issue by xxtheatrainxx** [snipe/snipe-it#1264]
Hello,

I've started importing assets from my spreadsheet (converted to your CSV format) and the data isn't pulling over in the correct locations.  The below screenshot shows a line from my csv document (Username removed)
![image](https://cloud.githubusercontent.com/assets/15128846/10592275/b080af28-7680-11e5-8915-093819fa4833.png)

The next image shows how this information was pulled into the database

![image](https://cloud.githubusercontent.com/assets/15128846/10592323/072ec1b6-7681-11e5-9c99-aeaa656d75f7.png)

I used your sample CSV and just filled in the blanks with my data.  The --username_format function didn't work and there was no domain section in app.php, but the username came out correctly (first.last) and the --domain worked, so everything else went fine.  I'm not sure how some of the data got moved around like that...do I need to put nul in any blank cells or something else as a placeholder?  The format for the data was consistent across each line/asset that I imported.  I'm uploading in small chunks right now to get the format correct.  Any help on this would be appreciated!

Also, I can figure out how to rework the CSV file to get everything in the right place, but there's some columns, like Notes and Asset Model, that didn't pull over at all and these are really the areas that will help save me (and other users) time in the long run.  Thanks again!

**Comment by snipe** [comment]
What version of Snipe-It are you using?

**Comment by xxtheatrainxx** [comment]
v2.0-125

**Comment by snipe** [comment]
Did you grab it from a release tho? Grab the latest off of master or develop, and tell me if this issue persists. (We made a change to the importer recently, and unfortunately don't have the sample.cv versioned.)

**Comment by xxtheatrainxx** [comment]
I did, yeah.  I grabbed it from your site the week before last, I believe.  I can grab the latest version, but I'm not sure how to apply it over the current version...Still a n00b.  I'll look into it and try tomorrow when I get in.

I imported a csv with one line using Test Asset for user, populated the UN and email fields and put 1-20 in the following fields.  From here I've come up with the below as being a suitable CSV format, though the cost and date fields are still a little wonky.  Date pulls over as 1 Jan 1970 and the cost pulled over as the date.  Did this test quickly when I was supposed to be leaving, so might be able to get that worked out tomorrow.

![image](https://cloud.githubusercontent.com/assets/15128846/10594360/f2f7e7e8-7691-11e5-881e-94f2a25b105a.png)

Nothing past column L was imported, from what I can see.  

Side note:  I'll be schoolgirl-giddy if you tell me there's a column for the MAC address

**Comment by snipe** [comment]
Yeah, we just released some updates last week, so you're likely trying to apply the new CSV format to the older importer.

**Comment by xxtheatrainxx** [comment]
Roger that.  I'll update and get back with you.

**Comment by xxtheatrainxx** [comment]
I'm having issues upgrading...I'm told there's nothing to migrate when I run php artisan migrate.  I'll have to get that sorted later, short day.  Thanks again for your help and I'll let you know if the import works with your sample csv when I get upgraded.

**Comment by snipe** [comment]
If it says there's nothing to migrate, that just means that no database changes have been made since the version you were running before

**Comment by gsoyka** [comment]
I may be having a similar issue, I pulled down the provided sample.csv file, didn't touch the headers, and put a single row of my own data in there.  First screenshot is of the csv:
![snipe file screenshot](https://cloud.githubusercontent.com/assets/15237387/10647785/b931010e-77f7-11e5-935d-6f35f1d78679.PNG)
With that file, and with any variant of it I've tried, I get this error: "trying to get property of non-object"

What makes me think it might be related is that the categories seem to be getting jumbled in the importer, ie. the category name is showing up as Latitude e4300 rather than Laptop.
![snipe screenshot import](https://cloud.githubusercontent.com/assets/15237387/10647867/4bd056c2-77f8-11e5-8ee1-87cb5c067704.PNG)

It seems like the importer is finding something it can't process, but for the life of me, I can't figure out what.

**Comment by snipe** [comment]
@gsoyka Which version are you using? That sample.cv should only be used with the latest from master or develop.

**Comment by gsoyka** [comment]
I've got v2.0-175

**Comment by snipe** [comment]
I'm not sure when that was off the top of my head. Can you pull the latest from develop?

**Comment by cjgulledge** [comment]
I came here because I had the same issue and wanted to see if there was a bug filed. I tried deploying from develop just now with this and it currently fails: http://docs.snipeitapp.com/installation/server/docker.html 

I'm retrying with the latest from master and will report back (and will update this)

**Comment by snipe** [comment]
Develop and master are the same right now, as I just pushed out a release.

**Comment by snipe** [comment]
@cjgulledge Are you saying the import fails on develop while using docker? Or that the docker build fails on develop?

**Comment by cjgulledge** [comment]
Sorry, I wasn't clear -- the docker build fails on develop currently. It could have been a fluke. here's the output:

Removing intermediate container a9291c07cc96
Step 2 : RUN apt-get update && apt-get install -y apache2-bin libapache2-mod-php5 php5-curl php5-ldap php5-mysql php5-mcrypt php5-gd patch curl vim git
 ---> Running in 1dfad73fe16a
Ign http://archive.ubuntu.com trusty InRelease
Get:1 http://archive.ubuntu.com trusty-updates InRelease [64.4 kB]
Get:2 http://archive.ubuntu.com trusty-security InRelease [64.4 kB]
Hit http://archive.ubuntu.com trusty Release.gpg
Get:3 http://archive.ubuntu.com trusty-updates/main Sources [301 kB]
Get:4 http://archive.ubuntu.com trusty-updates/restricted Sources [4513 B]
Get:5 http://archive.ubuntu.com trusty-updates/universe Sources [176 kB]
Get:6 http://archive.ubuntu.com trusty-updates/main amd64 Packages [799 kB]
Get:7 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [22.7 kB]
Get:8 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [421 kB]
Hit http://archive.ubuntu.com trusty Release
Get:9 http://archive.ubuntu.com trusty-security/main Sources [123 kB]
Get:10 http://archive.ubuntu.com trusty-security/restricted Sources [3230 B]
Get:11 http://archive.ubuntu.com trusty-security/universe Sources [35.4 kB]
Get:12 http://archive.ubuntu.com trusty-security/main amd64 Packages [448 kB]
Get:13 http://archive.ubuntu.com trusty-security/restricted amd64 Packages [19.4 kB]
Get:14 http://archive.ubuntu.com trusty-security/universe amd64 Packages [151 kB]
Get:15 http://archive.ubuntu.com trusty/main Sources [1335 kB]
Get:16 http://archive.ubuntu.com trusty/restricted Sources [5335 B]
Get:17 http://archive.ubuntu.com trusty/universe Sources [7926 kB]
Get:18 http://archive.ubuntu.com trusty/main amd64 Packages [1743 kB]
Get:19 http://archive.ubuntu.com trusty/restricted amd64 Packages [16.0 kB]
Get:20 http://archive.ubuntu.com trusty/universe amd64 Packages [7589 kB]
Fetched 21.2 MB in 24s (856 kB/s)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/source/Sources  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get install -y apache2-bin libapache2-mod-php5 php5-curl php5-ldap php5-mysql php5-mcrypt php5-gd patch curl vim git' returned a non-zero code: 100
bash-3.2$

**Comment by snipe** [comment]
@cjgulledge can you create a different ticket for that please? It's unrelated to the asset import issues.

**Comment by cjgulledge** [comment]
will do, thanks!

**Comment by cjgulledge** [comment]
OK, I've redeployed from master just now (v2.0-175-gd0aab3e) and imported using the same column format the original poster (@xxtheatrainxx) used and I'm having the same issue. 

I'm using the CSV format detailed here: http://docs.snipeitapp.com/manual/importing-assets.html
(currently: Name, Email, Username, Asset Category, Asset Model, Manufacturer, Asset Model Number, Asset Serial, Asset Tag, Location Name, Asset Notes, Purchase Date, Purchase Cost)

From my CSV file:

The "asset category" column is getting imported as the asset name. 
The "asset model" column is getting imported as the asset category. 
The "asset manufacturer" column is getting imported as the asset model. 
The "asset model number" column is getting imported as the  manufacturer. 
The "Asset serial number" column is getting imported as the model number. 
The "Asset location" column is getting imported as the asset tag. 
The "Asset notes" column is getting imported as the location.

**Comment by snipe** [comment]
Can you show me some of your cli output when you run the importer?

**Comment by cjgulledge** [comment]
I'm running the importer from the web interface at [myhost]/hardware/import  using the upload feature.

**Comment by snipe** [comment]
Ah, thats still in beta. Don't do that :P 

But it should create an output file in your private uploads folder. Can you show me what's in there?

**Comment by cjgulledge** [comment]
oops! sure thing...

**Comment by gsoyka** [comment]
I just cloned from develop, but am seeing the same version, and the same error at the CLI.  Here's the output again. The file just has the headers and one row of data, but it looks like the importer is trying to go on to another row that doesn't exist?

hdsstaff@Imaging:/var/www/html$ php artisan asset-import:csv sample_mod.csv --email_format=firstname.lastname --username_format=email
======= Importing Assets from sample_mod.csv =========
No user data provided - skipping user creation, just adding asset
Full Name: 
First Name: 
Last Name: 
Username: 
Email: 
Category Name: Latitude e4300
Item: Dell
Manufacturer ID: Vostro
Model No: 3RQVJK1
Serial No: CUHSGLT97
Asset Tag: ARC
Location: test
Purchase Date: 
Purchase Cost: 
Notes: 199
------------- Action Summary ----------------
Location test already exists
Category Latitude e4300 already exists
Manufacturer Vostro already exists
The Asset Model Dell with model number 3RQVJK1 already exists
Asset Dell with serial number CUHSGLT97 was created
=====================================
No user data provided - skipping user creation, just adding asset
Full Name: 
First Name: 
Last Name: 
Username: 
Email: 
Category Name: 
Item: 
Manufacturer ID: 
Model No: 
Serial No: 
Asset Tag: 
Location: 
Purchase Date: 
Purchase Cost: 
Notes: 
------------- Action Summary ----------------
No location given, so none created.
Category  already exists
Manufacturer  already exists
The Asset Model  with model number  already exists


                                        
  [ErrorException]                      
  Trying to get property of non-object

**Comment by xxtheatrainxx** [comment]
@cjgulledge remove the username field and try again. I don't think the importer is actually looking at the header as much as it's programmed to take data from a specific location in the csv file and place it in another. I believe the last screen shot I posted is a good format, though price and date might be backwards and price isn't working. If that fails, put a number in each cell and find out where the importer is sticking the data. Not a fix, but a decent workaround.

**Comment by xxtheatrainxx** [comment]
^place it in another specific location in the database

**Comment by cjgulledge** [comment]
Yeah, that works, but I thought it'd be more helpful to post here  how it was behaving. On the "importing assets" page, it is documented NOT to use the web interface right now (which I shouldn't have glossed over in the first place).  I'm happy with waiting until it is complete to try again.

**Comment by snipe** [comment]
Okay, I think I've got this sorted out. We added the ability to upload asset name, but missed it in the sample CSV in the docs. If you pull the latest off of develop, you'll see a sample CSV with dummy data. Otherwise you can use: http://docs.snipeitapp.com/sample-assets.csv

The docs have also been updated to reflect the additional field: http://docs.snipeitapp.com/manual/importing-assets.html

Please check it out and let me know if this resolves your issue.

**Comment by cjgulledge** [comment]
I'll give it a test once develop works being built from the dockerfile. Also, I had issues yesterday doing the import from cli -- I'm wondering if that's also related to how it's being built-out with docker. I got errors like this:

nipe-it-master/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /[redacted]/snipe-it-master/bootstrap/autoload.php on line 17
PHP Stack trace:
PHP   1. {main}() /[redacted]/snipe-it-master/artisan:0
PHP   2. require() /[redacted]/snipe-it-master/artisan:16

**Comment by gsoyka** [comment]
I pulled from develop this morning and am showing 2.0-334 as my version.  The fields seem to be lining up properly, but I'm still getting the "Trying to get property of non-object" exception.  Is there an end character that's required?
![snipe import fail](https://cloud.githubusercontent.com/assets/15237387/10669712/39a73130-789f-11e5-926a-cea008f5a70f.PNG)

**Comment by snipe** [comment]
There isn't a required end file, but can you tell me what's in your sample? It doesn't currently check if there are blank lines at the end of the file, so I'm wondering if that error was thrown at the end of your file, or in the middle

**Comment by gsoyka** [comment]
Here's what's in the file, I double checked and there is no blank space at the end.
![snipe import file](https://cloud.githubusercontent.com/assets/15237387/10673709/725656f4-78b4-11e5-9ce3-c90e4821aa61.PNG)

**Comment by cjgulledge** [comment]
The website still shows: "Name, Email Username, Asset Name, Asset Category, Asset Model, Manufacturer, Asset Model Number, Asset " here. http://docs.snipeitapp.com/manual/importing-assets.html

That tripped me up for a little bit today. The comma is needed between "Email" and "Username". It dawned on me when I looked directly below that at the table which had it correct.  The CLI importer seems to work when using the latest from develop, FYI.

**Comment by snipe** [comment]
Thanks for the heads up - will have that fixed today

**Comment by xxtheatrainxx** [comment]
Sorry for the delay in response.  The CLI importer/sample csv are working as intended after updating to the latest release.  Thanks again for your efforts!

A little off topic (ok, maybe a lot off topic):  any thoughts on adding MAC address and parent-group fields to the importer or the ability to run reports by parent or child groups?

**Comment by snipe** [comment]
@xxtheatrainxx What do you mean by parent/child groups?

**Comment by xxtheatrainxx** [comment]
It's possible I'm looking for too much, but I've setup Snipe-IT to reflect
our AD environment and our layout.  So, the parent group (location) is the
office location.  Under the parent group I have groups like Operations,
Warehouse, Accounting, etc..  After this I've added the smaller groups that
make up the bigger picture.  We also have our floor plan divided into zones
(makes printers much easier) and I've incorporated those into the setup,
just can't remember how off the top of my head.  So, once all is said and
done, I want to be able to run reports for Operations and see what devices
are deployed, how many licenses they have, etc, and also be able to run a
report on Checking (Warehouse) to see what is deployed to them.
Ultimately, it would be really nice to have this feature on the import
module.  I've already run into some issues with having two computers of the
same name, asset tag, etc that are really frustrating.  Once I've got all
the kinks worked out, my plan was to go in, create a new DB and upload the
information again.

**Comment by snipe** [comment]
When would you have two assets with the same asset tag? Those are unique by design, and asset name is not required to be unique at all.

**Comment by xxtheatrainxx** [comment]
If you upload a device twice through the CLI it creates two identical
objects.  Also, with all the troubleshooting I did the first time around, I
ended up with multiple devices with the same info that were "deleted" but
still showed in the system.  The duplicate devices with the same service
tag are causing a bit of a headache atm.

**Comment by snipe** [comment]
It should not import an item twice. The importer should be checking to see if the asset already exists. I'll check into that.

**Comment by snipe** [comment]
The latest on dev should resolve the duplicating assets issue on import.

Also, when you import assets with location, can you just move those locations under their parent locations after the import (versus trying to parse the parent/child relationship within the importer)

**Comment by AnarchyInc** [comment]
Hi all,

Experiencing some issues with the license importer.  Have a csv file created directly from the sample file on offer from the docs page.

Run the command and receive the following for all my entries. (note placeholders for actual fields used)


No user data provided - skipping user creation, just adding license
Full Name: 
First Name: 
Last Name: 
Username: 
Email: 
License Name: Software Name
Serial No: FDWQX-#####-######-#####
Licensed To Name: USER
Licensed To Email: 
Seats: 
Reassignable: 0
Supplier: 
Maintained: 0
Notes: Owner: some notes
Purchase Date: 
------------- Action Summary ----------------
Something went wrong! Supplier  was NOT created
Something went wrong! License Microsoft Office was NOT created
=====================================

This error occurs for all 300+ licenses.

Running :

Snipe-IT version | v3.6.6  build 1 (gee2c67a)
PHP Version | 7.0.21
Laravel Version | 5.2.45
Cent OS7

Any and all help would be greatly appreciated.
