### ISSUE TITLE
Delete button is not working any form

### ISSUE THREAD

**Issue by enagamani** [snipe/snipe-it#1265]
I am using snipeit version. 2.0-125. Delete button is not working in any form (assets, users, category etc.)

So, kindly solve this issues ASAP.

**Comment by snipe** [comment]
A little more info would be helpful. What does "not working" mean? Is it reproducible on the demo? Is there an error?

**Comment by enagamani** [comment]
When I click the delete button, there is no any process or any error message showing. 

 


	
		
 


Thanks & Regards,

Nagamani E | Cenza Technologies Pvt Ltd | #4, Industrial Estate, Perungudi, Chennai – 600 096 | Tel: +91 44 24960050/38 | Fax: +91 44 24960032 | Mail: systemadmin@cenzatech.com | Website: www.cenzatech.com <http://www.cenzatech.com/> 

CONFIDENTIALITY NOTICE: This E-mail and any attachments are confidential and may be protected by legal privilege. If you are not the intended recipient, be aware that any disclosure, copying, distribution or use of this E-mail or any attachment is prohibited. If you have received this E-mail in error, please notify us immediately on +91 44 24960038/50 or by email and delete this copy from your system. Thank you for your cooperation.    

P Please do not print this email unless it is absolutely necessary. Save paper. Save trees.  Spread environmental awareness

**Comment by snipe** [comment]
In your `app/config/app.php`, what is the value for `'lock_passwords'`?

**Comment by enagamani** [comment]
‘Lock_password’ value is ‘False’.

 


	
		
 


Thanks & Regards,

Nagamani E | Cenza Technologies Pvt Ltd | #4, Industrial Estate, Perungudi, Chennai – 600 096 | Tel: +91 44 24960050/38 | Fax: +91 44 24960032 | Mail: systemadmin@cenzatech.com | Website: www.cenzatech.com <http://www.cenzatech.com/> 

CONFIDENTIALITY NOTICE: This E-mail and any attachments are confidential and may be protected by legal privilege. If you are not the intended recipient, be aware that any disclosure, copying, distribution or use of this E-mail or any attachment is prohibited. If you have received this E-mail in error, please notify us immediately on +91 44 24960038/50 or by email and delete this copy from your system. Thank you for your cooperation.    

P Please do not print this email unless it is absolutely necessary. Save paper. Save trees.  Spread environmental awareness

**Comment by snipe** [comment]
I can't reproduce this on my end at all. You're going to need to check your browser's debug console to see if there are any javascript issues, etc. Only thing I can think of is that perhaps one of your javascript files isn't loading.

**Comment by enagamani** [comment]
I tried from three browsers (Chrome, Firefox & IE), but nothing worked. Also I tried from different systems, I am getting the same result. 

 


	
		
 


Thanks & Regards,

Nagamani E | Cenza Technologies Pvt Ltd | #4, Industrial Estate, Perungudi, Chennai – 600 096 | Tel: +91 44 24960050/38 | Fax: +91 44 24960032 | Mail: systemadmin@cenzatech.com | Website: www.cenzatech.com <http://www.cenzatech.com/> 

CONFIDENTIALITY NOTICE: This E-mail and any attachments are confidential and may be protected by legal privilege. If you are not the intended recipient, be aware that any disclosure, copying, distribution or use of this E-mail or any attachment is prohibited. If you have received this E-mail in error, please notify us immediately on +91 44 24960038/50 or by email and delete this copy from your system. Thank you for your cooperation.    

P Please do not print this email unless it is absolutely necessary. Save paper. Save trees.  Spread environmental awareness

**Comment by snipe** [comment]
Honestly not sure what to suggest. I can't reproduce your issue locally or on the demo.

**Comment by snipe** [comment]
(I need you to look at the debugging console of your browsers to tell me if there are any errors.)

**Comment by enagamani** [comment]
Hi,

 

I am getting the below error in the browser debugging console.

 

jquery-latest.js:1473 Uncaught Error: Syntax error, unrecognized expression: http://192.168.2.4/hardware/1072/delete

 


	
		
 


Thanks & Regards,

Nagamani E | Cenza Technologies Pvt Ltd | #4, Industrial Estate, Perungudi, Chennai – 600 096 | Tel: +91 44 24960050/38 | Fax: +91 44 24960032 | Mail: systemadmin@cenzatech.com | Website: www.cenzatech.com <http://www.cenzatech.com/> 

CONFIDENTIALITY NOTICE: This E-mail and any attachments are confidential and may be protected by legal privilege. If you are not the intended recipient, be aware that any disclosure, copying, distribution or use of this E-mail or any attachment is prohibited. If you have received this E-mail in error, please notify us immediately on +91 44 24960038/50 or by email and delete this copy from your system. Thank you for your cooperation.    

P Please do not print this email unless it is absolutely necessary. Save paper. Save trees.  Spread environmental awareness

**Comment by snipe** [comment]
What screen are you trying to delete from?

**Comment by enagamani** [comment]
The delete button is not working from all the screens.

 


	
		
 


Thanks & Regards,

Nagamani E | Cenza Technologies Pvt Ltd | #4, Industrial Estate, Perungudi, Chennai – 600 096 | Tel: +91 44 24960050/38 | Fax: +91 44 24960032 | Mail: systemadmin@cenzatech.com | Website: www.cenzatech.com <http://www.cenzatech.com/> 

CONFIDENTIALITY NOTICE: This E-mail and any attachments are confidential and may be protected by legal privilege. If you are not the intended recipient, be aware that any disclosure, copying, distribution or use of this E-mail or any attachment is prohibited. If you have received this E-mail in error, please notify us immediately on +91 44 24960038/50 or by email and delete this copy from your system. Thank you for your cooperation.    

P Please do not print this email unless it is absolutely necessary. Save paper. Save trees.  Spread environmental awareness

**Comment by snipe** [comment]
Can I see a screenshot of the debug console?

**Comment by snipe** [comment]
Any updates?

**Comment by enagamani** [comment]
No, Still now it is not working.

 


	
		
 


Thanks & Regards,

Nagamani E | Cenza Technologies Pvt Ltd | #4, Industrial Estate, Perungudi, Chennai – 600 096 | Tel: +91 44 24960050/38 | Fax: +91 44 24960032 | Mail: systemadmin@cenzatech.com | Website: www.cenzatech.com <http://www.cenzatech.com/> 

CONFIDENTIALITY NOTICE: This E-mail and any attachments are confidential and may be protected by legal privilege. If you are not the intended recipient, be aware that any disclosure, copying, distribution or use of this E-mail or any attachment is prohibited. If you have received this E-mail in error, please notify us immediately on +91 44 24960038/50 or by email and delete this copy from your system. Thank you for your cooperation.    

P Please do not print this email unless it is absolutely necessary. Save paper. Save trees.  Spread environmental awareness

**Comment by snipe** [comment]
I asked you for a screenshot of your debug console.

**Comment by enagamani** [comment]
Hi,

 

Below is the error I am getting in the debug console. 

 

Failed to load resource: the server responded with a status of 404 (Not Found)

http://192.168.2.4/assets/font/fontawesome-webfont.woff?v=4.3.0 Failed to load resource: the server responded with a status of 404 (Not Found)

jquery-latest.js:1473 Uncaught Error: Syntax error, unrecognized expression: http://192.168.2.4/hardware/1073/delete

 

Also I have attached the screen shot for the same. 

 


	
		
 


Thanks & Regards,

Nagamani E | Cenza Technologies Pvt Ltd | #4, Industrial Estate, Perungudi, Chennai – 600 096 | Tel: +91 44 24960050/38 | Fax: +91 44 24960032 | Mail: systemadmin@cenzatech.com | Website: www.cenzatech.com <http://www.cenzatech.com/> 

CONFIDENTIALITY NOTICE: This E-mail and any attachments are confidential and may be protected by legal privilege. If you are not the intended recipient, be aware that any disclosure, copying, distribution or use of this E-mail or any attachment is prohibited. If you have received this E-mail in error, please notify us immediately on +91 44 24960038/50 or by email and delete this copy from your system. Thank you for your cooperation.    

P Please do not print this email unless it is absolutely necessary. Save paper. Save trees.  Spread environmental awareness

**Comment by enagamani** [comment]
Thanks & Regards,

Nagamani E | Cenza Technologies Pvt Ltd | #4, Industrial Estate, Perungudi, Chennai – 600 096 | Tel: +91 44 24960050/38 | Fax: +91 44 24960032 | Mail: systemadmin@cenzatech.com | Website: www.cenzatech.com <http://www.cenzatech.com/> 

CONFIDENTIALITY NOTICE: This E-mail and any attachments are confidential and may be protected by legal privilege. If you are not the intended recipient, be aware that any disclosure, copying, distribution or use of this E-mail or any attachment is prohibited. If you have received this E-mail in error, please notify us immediately on +91 44 24960038/50 or by email and delete this copy from your system. Thank you for your cooperation.    

P Please do not print this email unless it is absolutely necessary. Save paper. Save trees.  Spread environmental awareness

**Comment by snipe** [comment]
As I've mentioned before, you cannot email screenshots to Github, you have to upload them to the ticket via the web UI.

**Comment by enagamani** [comment]
Below is the error I am getting in the debug console.



Failed to load resource: the server responded with a status of 404 (Not Found)

http://192.168.2.4/assets/font/fontawesome-webfont.woff?v=4.3.0 Failed to load resource: the server responded with a status of 404 (Not Found)

jquery-latest.js:1473 Uncaught Error: Syntax error, unrecognized expression: http://192.168.2.4/hardware/1073/delete



Also I have attached the screen shot for the same.
![snipeit](https://cloud.githubusercontent.com/assets/11957197/10935088/b2b6fed8-8309-11e5-8fc2-05cf31cf97f9.jpg)

**Comment by snipe** [comment]
Is it possible you're missing some files? That those font files are 404'ing seems awfully suspicious to me, as they are included in the distribution.

**Comment by enagamani** [comment]
Hi,

 

Currently I am using version 2.0.1 and I want to update it to 2.0.4. Kindly share the procedure to upgrade the snipeit in Windows environment (hosted in IIS).

 


	
		
 


Thanks & Regards,

Nagamani E | Cenza Technologies Pvt Ltd | #4, Industrial Estate, Perungudi, Chennai – 600 096 | Tel: +91 44 24960050/38 | Fax: +91 44 24960032 | Mail: systemadmin@cenzatech.com | Website: www.cenzatech.com <http://www.cenzatech.com/> 

CONFIDENTIALITY NOTICE: This E-mail and any attachments are confidential and may be protected by legal privilege. If you are not the intended recipient, be aware that any disclosure, copying, distribution or use of this E-mail or any attachment is prohibited. If you have received this E-mail in error, please notify us immediately on +91 44 24960038/50 or by email and delete this copy from your system. Thank you for your cooperation.    

P Please do not print this email unless it is absolutely necessary. Save paper. Save trees.  Spread environmental awareness

**Comment by snipe** [comment]
http://docs.snipeitapp.com/upgrading.html

**Comment by snipe** [comment]
Any updates here?
