### ISSUE TITLE
Export function doesn't work on my deployment

### ISSUE THREAD

**Issue by tzielinskiaptn** [snipe/snipe-it#1270]
I recently upgraded from version 1.2.6.1 to the stable 2.0.3 general release, following the upgrade guidelines in the documentation.

I'm running on Windows Server 2012 R2 and IIS 8.5.

It doesn't seem as though the export to csv, xls or PDF is working on my server.

When I display my deployed assets list, and I check off some items and click export, the csv, xls and PDF selection list appears, but clicking on those buttons doesn't trigger a dialog.

I'm wondering if I am missing a dependency on my server, or if there is some other way to utilize this feature. It wasn't present in my previous version, and I can definitely make use of it for reporting purposes.

Thanks for any help or direction you can provide.

**Comment by snipe** [comment]
Can you look at your browser's debugging console and tell me if you see any errors?

**Comment by tzielinskiaptn** [comment]
Yes indeed, I see a 404 (Not Found) for the /assets/swf/copy_csv_xls_pdf.swf (Which I should have looked for and caught myself)

Clicking Export triggers three of them in the debug log.

The copy_csv_xls_pdf.swf file is present in my \public\assets\swf folder.

**Comment by snipe** [comment]
We're actually replacing that system right now - can you grab the latest off of develop (and run migrations) and see if that's better?
