### ISSUE TITLE
Docker build fails on the latest from 'develop' branch

### ISSUE THREAD

**Issue by cjgulledge** [snipe/snipe-it#1271]
Tested against Develop branch (https://github.com/snipe/snipe-it/tree/develop) As of a90f7218de89051b20bf94f135476f25b2d98212

output:

Removing intermediate container a9291c07cc96
Step 2 : RUN apt-get update && apt-get install -y apache2-bin libapache2-mod-php5 php5-curl php5-ldap php5-mysql php5-mcrypt php5-gd patch curl vim git
 ---> Running in 1dfad73fe16a
Ign http://archive.ubuntu.com trusty InRelease
Get:1 http://archive.ubuntu.com trusty-updates InRelease [64.4 kB]
Get:2 http://archive.ubuntu.com trusty-security InRelease [64.4 kB]
Hit http://archive.ubuntu.com trusty Release.gpg
Get:3 http://archive.ubuntu.com trusty-updates/main Sources [301 kB]
Get:4 http://archive.ubuntu.com trusty-updates/restricted Sources [4513 B]
Get:5 http://archive.ubuntu.com trusty-updates/universe Sources [176 kB]
Get:6 http://archive.ubuntu.com trusty-updates/main amd64 Packages [799 kB]
Get:7 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [22.7 kB]
Get:8 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [421 kB]
Hit http://archive.ubuntu.com trusty Release
Get:9 http://archive.ubuntu.com trusty-security/main Sources [123 kB]
Get:10 http://archive.ubuntu.com trusty-security/restricted Sources [3230 B]
Get:11 http://archive.ubuntu.com trusty-security/universe Sources [35.4 kB]
Get:12 http://archive.ubuntu.com trusty-security/main amd64 Packages [448 kB]
Get:13 http://archive.ubuntu.com trusty-security/restricted amd64 Packages [19.4 kB]
Get:14 http://archive.ubuntu.com trusty-security/universe amd64 Packages [151 kB]
Get:15 http://archive.ubuntu.com trusty/main Sources [1335 kB]
Get:16 http://archive.ubuntu.com trusty/restricted Sources [5335 B]
Get:17 http://archive.ubuntu.com trusty/universe Sources [7926 kB]
Get:18 http://archive.ubuntu.com trusty/main amd64 Packages [1743 kB]
Get:19 http://archive.ubuntu.com trusty/restricted amd64 Packages [16.0 kB]
Get:20 http://archive.ubuntu.com trusty/universe amd64 Packages [7589 kB]
Fetched 21.2 MB in 24s (856 kB/s)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/source/Sources  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/sh -c apt-get update && apt-get install -y apache2-bin libapache2-mod-php5 php5-curl php5-ldap php5-mysql php5-mcrypt php5-gd patch curl vim git' returned a non-zero code: 100
bash-3.2$

**Comment by snipe** [comment]
Thanks :) 

Hey @uberbrady - can you take a look at this please.

**Comment by uberbrady** [comment]
Might be an issue with newer copies of Ubuntu, I might have to re-pull that down. So far I'm doing a rebuild now and it seems pretty straightforward.

**Comment by uberbrady** [comment]
Nope, just pulled the latest Ubuntu and rebuilt without problems. Can you just 'try again' - maybe from the latest in #develop - (maybe the develop branch was broken for a few moments, when you happened to try your build?

Here's another option you *might* want to try (not yet tested, but I am hoping to soon) - ```docker pull snipe/snipe-it``` - that's automatically rebuilt on git-push and seems to imply that most of the builds have been working OK.

If you do either just the simple retry, or the ```docker pull``` method - please let us know how it works out for you, and if it solves the problem.

**Comment by cjgulledge** [comment]
You can close this.  I ran 'docker pull snipe/snipe-it' and retried and the build was successful.  I guess my previous attempt was a fluke. Thank you sir!

**Comment by snipe** [comment]
![turtle high five](https://cloud.githubusercontent.com/assets/197404/10678163/75dc5c9a-78c5-11e5-8702-47222f50703e.gif)

**Comment by cjgulledge** [comment]
+1 ^
