### ISSUE TITLE
Open Sans Font Subset Choice

### ISSUE THREAD

**Issue by DoubleZed** [snipe/snipe-it#1278]
To be able to use a lot more language-specific characters in the data, and for the fonts to be displayed correctly and not replaced automatically with the "closest" font that has the special character, there should be a way to set the font itself or if a Google Font, to define the font subset.

For example:
Without a subset this sample text is displayed like 
![font_issue_1](https://cloud.githubusercontent.com/assets/15252805/10674238/904672ea-7902-11e5-8066-bcef37799cdf.PNG)
With the latin-extended subset the actual Open Sans font is used:
![font_issue_2](https://cloud.githubusercontent.com/assets/15252805/10674245/9ea91a40-7902-11e5-990f-485f268f481b.PNG)

The subset is supposed to be indicated in the html code where the stylesheet for the Google Fonts is defined:
`<link type="text/css" rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&subset=latin,latin-ext"></link>`

Since indicating all of the possible subsets (also for those using arabic or cyrillic letters) might be a waste of resources, a place where to indicate the required character subset would be nice.

**Comment by snipe** [comment]
@DoubleZed Are these the only choices we'd need to provide?

<img width="760" alt="screen shot 2015-11-04 at 4 39 30 am" src="https://cloud.githubusercontent.com/assets/197404/10938343/1b1bc6f4-82ae-11e5-9840-ed10246cd4c1.png">

https://www.google.com/fonts#UsePlace:use/Collection:Open+Sans

**Comment by DoubleZed** [comment]
If we stick with the Open Sans font, then yes, we should be golden with these character sets.
