### ISSUE TITLE
Better utf8 usage for full Unicode support

### ISSUE THREAD

**Issue by DoubleZed** [snipe/snipe-it#1279]
Someone might be able propose a better solution for this, but I suggest using **utf8mb4** character set and collate **utf8mb4_unicode_ci** for the snipe-it database. 

To have it running properly, it might include not only setting the charset and collate, but also limiting some column lengths, like the **name** column in **groups** table, which is using varchar(255), but in this case might need varchar(191) to not reach the maximum index length (787) of the **InnoDB** storage engine.

Without this you cannot really use for example eastern european special characters in person names.

Good source for this information [here](https://mathiasbynens.be/notes/mysql-utf8mb4).

**Comment by uberbrady** [comment]
This may allow us to use Emoji in asset notes - 

:hankey: laptop

**Comment by DoubleZed** [comment]
Yes, that is exactly what has been missing from the snipe-it functionality all along :+1:

**Comment by snipe** [comment]
@DoubleZed we actually can't change the groups migration (we could alter the table afterwards in a following migration though), since that table (and therefore the migration) is generated by the Catalyst Sentry package.
