### ISSUE TITLE
Expected Checkin Date

### ISSUE THREAD

**Issue by jahrj** [snipe/snipe-it#1281]
When checking out an item, there is a form field for "Expected Checkin Date". Is there a way to view that information in the All Assets column view? For that matter is there any way to review the "Expected Checkin Date" information at all after it is entered in? I feel like I could be overlooking something. Thanks!  This is an amazing project!

**Comment by snipe** [comment]
This is currently completed on the develop branch

**Comment by jahrj** [comment]
This is some of the best news I've heard in awhile! Thanks for the update.
