### ISSUE TITLE
Question regarding LDAP authentication

### ISSUE THREAD

**Issue by orygen** [snipe/snipe-it#1284]
Hi guys,
this is not an issue question, more like " will it work if ..." question.
If I manually create a user or a user created during the asset importing, then later on I add LDAP functionality my snipe-it, will the user created previously be able to authenticate via LDAP?
Or only user imported via LDAP can authenticate via LDAP?
Hope that make sense. Thanks.

**Comment by ddreier** [comment]
By default it will not work. The LDAP importer skips over accounts that already exist.

However, the LDAP authentication code simply checks the user's Notes field for the string "LDAP" to see if LDAP auth should be used. If you set the existing user's username to be the same as it is in your Directory, adding LDAP to the user's Notes might make LDAP auth work for them.

**Comment by orygen** [comment]
Thanks @ddreier
