### ISSUE TITLE
Table users not found

### ISSUE THREAD

**Issue by LarryTX** [snipe/snipe-it#1289]
I just downloaded your latest version and am attempting to install it. When I run migrations, it fails because the first migration file is "Update users," and there is no users table. Am I missing something?

**Comment by snipe** [comment]
Did you actually run the installer first?

**Comment by snipe** [comment]
http://docs.snipeitapp.com/installation/command-line.html

**Comment by LarryTX** [comment]
My apologies. Actually, I had seen that, but I thought this (https://github.com/snipe/snipe-it/releases/tag/v2.0.4) came first. Apologies.

**Comment by snipe** [comment]
No prob
