### ISSUE TITLE
Documentation: Restoring from backup

### ISSUE THREAD

**Issue by sbarsanti** [snipe/snipe-it#1292]
Is there any documentation around restoring from a backup?

**Comment by snipe** [comment]
Restoring what, specifically?

**Comment by snipe** [comment]
You can restore the db using `php artisan db:restore yourdumpfilename.sql`. The folders (with uploads etc) just need to be moved manually back to where they belong.

**Comment by sbarsanti** [comment]
In Admin>Backups I clicked "Generate Backup" now I want to use that zip file to restore my database

**Comment by sbarsanti** [comment]
Ok, thanks so much! Really love this project

**Comment by snipe** [comment]
You can't restore it using the whole zip. You have to unzip, and either manually import the SQL file back into your database, or use the command above. One-click restore might be something we add later, but it's not available at this point.

**Comment by sbarsanti** [comment]
Excellent thanks.
--
Steve Barsanti
IT Manager

**Comment by TroyShaw** [comment]
Sorry to bring this back from the dead, but has there been any progress on this? It seems like a useful feature.
