### ISSUE TITLE
Export all assets to CSV or TXT not working

### ISSUE THREAD

**Issue by dkroshko** [snipe/snipe-it#1293]
Snipe-IT Version: v2.0-334-g0aeab1a
PHP Version	5.4.45
Laravel Version	4.2.17

When exporting to csv or txt, system generates a file with no extension. I can manually change the extension to .csv and it works, but auto export does not save as appropriate extension.

*Assets > List All > shows 115 rows currently, but export to csv and manually editing extension: only reflects 51 rows.

*Custom asset report downloads .csv automagically, and includes all 115 rows.

**Comment by dkroshko** [comment]
*All assets view shows 115 rows currently, but export (after manually editing extension) shows 51 rows.

**Comment by snipe** [comment]
Yes, that's a limitation in the export javascript library int he version on develop. Right now, users have to rename the file.

**Comment by dkroshko** [comment]
aha! got it thanks
