### ISSUE TITLE
ERROR 500 (Internal Server Error)

### ISSUE THREAD

**Issue by LaneZhiyue** [snipe/snipe-it#1295]
Hi
I can't go into the application. I am running the app locally. I put the database.php under app\config and also generated new keys to replace. Here is the log under app\storage\logs

[2015-10-28 08:54:44] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\www\htdocs\snipe-it\bootstrap\compiled.php:5751
Stack trace:
#0 C:\www\htdocs\snipe-it\bootstrap\compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 C:\www\htdocs\snipe-it\bootstrap\compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 C:\www\htdocs\snipe-it\bootstrap\compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 C:\www\htdocs\snipe-it\bootstrap\compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 C:\www\htdocs\snipe-it\bootstrap\compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 C:\www\htdocs\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 C:\www\htdocs\snipe-it\bootstrap\compiled.php(7825): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#7 C:\www\htdocs\snipe-it\bootstrap\compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#8 C:\www\htdocs\snipe-it\bootstrap\compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#9 C:\www\htdocs\snipe-it\bootstrap\compiled.php(11088): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#10 C:\www\htdocs\snipe-it\bootstrap\compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#11 C:\www\htdocs\snipe-it\public\index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2015-10-28 08:54:44] production.ERROR: exception 'ErrorException' with message 'mcrypt_encrypt(): Key of size 0 not supported by this algorithm. Only keys of sizes 16, 24 or 32 supported' in C:\www\htdocs\snipe-it\bootstrap\compiled.php:8463
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'mcrypt_encrypt(...', 'C:\\www\\htdocs\\s...', 8463, Array)
#1 C:\www\htdocs\snipe-it\bootstrap\compiled.php(8463): mcrypt_encrypt('rijndael-256', '', 's:40:"b9b94e3a3...', 'cbc', ' \xE0\xEC\x9F\xAF.\x82\xEF\xEE\x16Y\xCB\x18\xBE)...')
#2 C:\www\htdocs\snipe-it\bootstrap\compiled.php(8456): Illuminate\Encryption\Encrypter->padAndMcrypt('b9b94e3a3a29d54...', ' \xE0\xEC\x9F\xAF.\x82\xEF\xEE\x16Y\xCB\x18\xBE)...')
#3 C:\www\htdocs\snipe-it\bootstrap\compiled.php(8407): Illuminate\Encryption\Encrypter->encrypt('b9b94e3a3a29d54...')
#4 C:\www\htdocs\snipe-it\bootstrap\compiled.php(8379): Illuminate\Cookie\Guard->encrypt(Object(Illuminate\Http\Response))
#5 C:\www\htdocs\snipe-it\bootstrap\compiled.php(11088): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#6 C:\www\htdocs\snipe-it\bootstrap\compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#7 C:\www\htdocs\snipe-it\public\index.php(49): Illuminate\Foundation\Application->run()
#8 {main} [] []

I appreciate your helps a lot!

**Comment by snipe** [comment]
You are running in production, according to your logs so all of your configs should be in `app/config/production`

**Comment by LaneZhiyue** [comment]
Thanks a lot. And I also have Symfony\Component\HttpKernel\Exception\NotFoundHttpException. 

[2015-10-28 09:06:00] production.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\www\htdocs\snipe-it\bootstrap\compiled.php:5751
Stack trace:
#0 C:\www\htdocs\snipe-it\bootstrap\compiled.php(5073): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 C:\www\htdocs\snipe-it\bootstrap\compiled.php(5061): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 C:\www\htdocs\snipe-it\bootstrap\compiled.php(5053): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 C:\www\htdocs\snipe-it\bootstrap\compiled.php(715): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 C:\www\htdocs\snipe-it\bootstrap\compiled.php(696): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 C:\www\htdocs\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 C:\www\htdocs\snipe-it\bootstrap\compiled.php(7825): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#7 C:\www\htdocs\snipe-it\bootstrap\compiled.php(8432): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#8 C:\www\htdocs\snipe-it\bootstrap\compiled.php(8379): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#9 C:\www\htdocs\snipe-it\bootstrap\compiled.php(11088): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#10 C:\www\htdocs\snipe-it\bootstrap\compiled.php(657): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#11 C:\www\htdocs\snipe-it\public\index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []

**Comment by snipe** [comment]
Yeah, I don't know what you did to cause that. Would need more information, like what the url bar says when you try to access the site, whether you get a 404 on all pages, etc. My guess is that you don't have your URL rewrite rules imported.

**Comment by LaneZhiyue** [comment]
OK. Could you also tell me how I can import URL rewrite rules for XAMPP?

**Comment by snipe** [comment]
http://linuxandfriends.com/how-to-enable-mod_rewrite-in-xampp/

**Comment by LaneZhiyue** [comment]
Thanks a lot! I will try agian.

**Comment by LaneZhiyue** [comment]
Got it. I was trying to access it using http://localhost/snipe-it .. Thanks a lot
