### ISSUE TITLE
Company logo

### ISSUE THREAD

**Issue by cantmz** [snipe/snipe-it#1296]
Hi all,
where company logo has to appear?
I can see it in my browser pointing to

http://www.mysite.org/uploads/logo.png

but I can't see it in frontend login page and/or dashboard after logging in.

By the way, I do see users pictures I have uploaded.

Thanks
KR

**Comment by snipe** [comment]
It appears in the top left corner of the header on every page. 

Can you open your browser's debug bar and tell me if you see any errors?

Also please tell me what version you're running.

**Comment by cantmz** [comment]
I am running v2.0-353.

I can't find any reference to logo in html generated through PHP.

![image](https://cloud.githubusercontent.com/assets/15346013/10788546/8ebc0dfc-7d78-11e5-986e-f6d050b5ecae.png)

**Comment by snipe** [comment]
Did you actually upload one in the settings panel?

**Comment by cantmz** [comment]
Yes I did, and I can see logo directly with

http://www.mysite.org/uploads/logo.png

**Comment by snipe** [comment]
Can you show me what the contents of your settings table are?

**Comment by cantmz** [comment]
I realized that when I load the file it shows logo.png
After saving changes I get this

![image](https://cloud.githubusercontent.com/assets/15346013/10788700/7ec5bb9a-7d79-11e5-88a8-2f8a506056f9.png)

**Comment by snipe** [comment]
I'm not sure what you're showing me, here.

**Comment by cantmz** [comment]
Apologies

![image](https://cloud.githubusercontent.com/assets/15346013/10788815/37c50498-7d7a-11e5-85a4-8f1a467b2b39.png)

**Comment by snipe** [comment]
What is the value for the `brand` field?

**Comment by cantmz** [comment]
3

**Comment by snipe** [comment]
Does your browser's debug tools show anything in the console?

**Comment by cantmz** [comment]
Don't know if this is what you meant.

![image](https://cloud.githubusercontent.com/assets/15346013/10789080/9e31bfd6-7d7b-11e5-9b7e-de174e45ab3b.png)

**Comment by snipe** [comment]
I just pushed out a small change - can you grab the latest and tell me if that resolves your issue?

**Comment by cantmz** [comment]
I had a git pull after you possible fix and now it works!

Many thanks!

**Comment by snipe** [comment]
![mad-max-fury-road-awesome-guitar-guy-1431710473](https://cloud.githubusercontent.com/assets/197404/10789179/14c865ca-7d39-11e5-98f4-5dfe7ca40f12.gif)
