### ISSUE TITLE
Attachement support

### ISSUE THREAD

**Issue by ejdekruijf** [snipe/snipe-it#1297]
Hello Is it possible to add a attachement function to snipe-it?
We would need this for example audits. So we can show for example the license papers.

**Comment by snipe** [comment]
Beyond the file uploads it already supports? If so, I'll need to clarify what else it needs to do.

**Comment by ejdekruijf** [comment]
Where is that file upload function? I couldn’t find it.

**Comment by snipe** [comment]
You upload files to assets or licenses, so go to one of the license or asset pages, and you'll see file uploads for that asset/license.

**Comment by ejdekruijf** [comment]
Hi,

Where is that function? Attached is an example license

[cid:image001.png@01D11186.4AEA3D50]

**Comment by snipe** [comment]
You can't send attachments via email replies on Github, you have to upload via the website

**Comment by snipe** [comment]
See the demo:
https://demo.snipeitapp.com/admin/licenses/1/view

<img width="742" alt="screen shot 2015-10-28 at 5 42 35 am" src="https://cloud.githubusercontent.com/assets/197404/10788751/b83c8496-7d36-11e5-8297-fe98a2cef6b8.png">

**Comment by ejdekruijf** [comment]
Sorry Found it. My browser didn’t showed the option. After a reload of the page I found it. Sorry but thank you for the quick support!
