### ISSUE TITLE
Dashboard link is not working

### ISSUE THREAD

**Issue by LaneZhiyue** [snipe/snipe-it#1300]
Hi. When I click "Dashboard" from the menu or the site name "SNIPE IT ASSET MANAGEMENT", it will be directed to http://snipe-it-laravel.local:8888/ 

Could you kindly provide some advice?

**Comment by snipe** [comment]
Please edit the URL in your config file, as documented here: http://docs.snipeitapp.com/installation/configuration.html#application-settings

**Comment by LaneZhiyue** [comment]
Wow, that was fast! Thanks a lot!
