### ISSUE TITLE
Installed Snipe-IT on Server 2008 R2 according to install instructions - Can't get the site to load

### ISSUE THREAD

**Issue by jkuechle** [snipe/snipe-it#1301]
I followed all of the install instructions for IIS, PHP, and Composer. Can't get the site to load. Please help if possible

**Comment by ddreier** [comment]
If you're just getting a blank page, try disabling or removing the HTTPS URL Rewrite rule.

**Comment by jkuechle** [comment]
Still no luck. I'm getting "Server not found" message in my browser. I'm sure it must be a config error somewhere, I just can't seem to find it. I have my site set up as http://hostmname.com

**Comment by jkuechle** [comment]
Ok, that did work. After looking into it more closely, I finally got it to load. I had my site binding setting configured wrong.

Thanks!

**Comment by ddreier** [comment]
Please close the issue if everything is working.
