### ISSUE TITLE
Docker setup fails during install step 

### ISSUE THREAD

**Issue by swoopdk** [snipe/snipe-it#1303]
I tried to follow a completely fresh install using Docker on OSX. 

During the step asking me to do the following:
```docker exec -i -t snipeit php artisan app:install```

I get a huge red error box (see image) complaining about "Invalid default value for 'created_at'"

![image](https://cloud.githubusercontent.com/assets/5802977/10843156/813fe9fc-7ef7-11e5-9405-518cf0fa77f6.png)

I can fix this by removing 'NO_ZERO_DATE' on the mysql container like this:

```SELECT @@GLOBAL.sql_mode;````

Note down the list, and remove the NO_ZERO_DATE from the list when doing a SET. for me it looks like this

```SET @@GLOBAL.sql_mode = "ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION";```

I'm new to both this project and Docker in general so excuse me if i'm making a wrong assumption or something here. But seems to me that it might be an update that happened in either Snipe-IT or MySQL but regardless there is an issue. 

I have previously followed the instructions point by point and had it working so i'm not sure if the bug is in Snipeit or the Mysql image from Docker.

**Comment by uberbrady** [comment]
I could've sworn @snipe has all this stuff tested pretty strong against STRICT_MODE - which I believe includes that setting?

**Comment by snipe** [comment]
So, the thing is, that's not actually even my migration, it's from Sentry. (And yes, I do all development in strict mode, to avoid the issues we're discussing here.)

That migration is kicked off by the `php artisan app:install` command, which lives in `app/commands/AppCommand.php`, specifically the line:

```
  // Run the Sentry Migrations
        $this->call('migrate', array('--package' => 'cartalyst/sentry','--force'=>true));
```

In `vendor/cartalyst/sentry/src/migrations`, we can see that the migration that creates the user's table uses standard Laravel timestamps:

```
public function up()
	{
		Schema::create('users', function($table)
		{
			$table->increments('id');
			$table->string('email');
			$table->string('password');
			$table->text('permissions')->nullable();
			$table->boolean('activated')->default(0);
			$table->string('activation_code')->nullable();
			$table->timestamp('activated_at')->nullable();
			$table->timestamp('last_login')->nullable();
			$table->string('persist_code')->nullable();
			$table->string('reset_password_code')->nullable();
			$table->string('first_name')->nullable();
			$table->string('last_name')->nullable();
			$table->timestamps();

			// We'll need to ensure that MySQL uses the InnoDB engine to
			// support the indexes, other engines aren't affected.
			$table->engine = 'InnoDB';
			$table->unique('email');
			$table->index('activation_code');
			$table->index('reset_password_code');
		});
	}
```

So I'm not sure where the value of 0 is being set as the default for the `created_at` field. Zero is obviously not a valid value for a timestamp field, but we're also not passing it a zero default, so I'm sort of at a loss as to what's happening here.

**Comment by snipe** [comment]
@uberbrady any ideas?

**Comment by uberbrady** [comment]
This looks like it's a known Laravel issue. Ugh.

https://github.com/laravel/framework/issues/3602

Hah! And here you are @snipe - same problem: https://github.com/laravel/framework/issues/5903

Let me look into a workaround - maybe something like ```->default(DB::raw("CURRENT_TIMESTAMP"))``` or something like that?

**Comment by snipe** [comment]
I guess the quick fix is to make sure mysql in the docker config is not in strict mode :( That's a shitty fix, but that laravel ticket hasn't been updated since 2014.

**Comment by swoopdk** [comment]
I have been using the shitty fix of disabling the strict mode, but would make the setup easier to not have to do this. 

Until we have a potential fix perhaps it should be mentioned under the docker install docs ?

**Comment by swoopdk** [comment]
Just an update. I was during install not disabling all the strict mode features and later i would get trouble adding anything to Snipeit. I could add things with no error but several lists would show up empty despite having data in the tables in the DB. 

Disabling all the strict mode features fixed this.

**Comment by uberbrady** [comment]
Okay, I found out why this suddenly started showing up - 

MySQL released a new version of their docker container which runs in a more strict mode.

If you specifically pick out a MySQL version running 5.6 or earlier, it won't happen. I'm updating documentation to note that.

**Comment by snipe** [comment]
@uberbrady did you update the docs on this?

**Comment by uberbrady** [comment]
@snipe on my Docker improvements branch.
