### ISSUE TITLE
Checkin button do not appear

### ISSUE THREAD

**Issue by cantmz** [snipe/snipe-it#1306]
Hi,
checkin  button appears in All assets list if I create an asset  and and upon creation I chose a user to assign.
If I assign to a user later (not at asset creation page) checkin button does not appear.

Thanks
KR

**Comment by snipe** [comment]
Can you reproduce this on the demo?

**Comment by cantmz** [comment]
Hi snipe,
This is a pic from demo.
I would have expected to have checkout button for test-pending asset.
Checkin button is ok.

![image](https://cloud.githubusercontent.com/assets/15346013/10855188/7fb1e632-7f40-11e5-8280-d84fabc65c62.png)

Thanks.
KR
Mirko

**Comment by snipe** [comment]
No, the status is pending, which means it can't be checked out yet. That's by design.

**Comment by cantmz** [comment]
Ok.
I was deceived because "ready to deploy" status selection gives you dropdown to choose user.
I woud have expected to find such a dropdown only for "in use" status.
So I assumed "pending" was the logic lower status I could not assign a user, and was expecting to find checkout button.
My 2 cents is that "ready to deploy" status should not give you the opportunity to pick up a user...if I can pick a user an assset is "deployed".
Anyway now it is clear.
Thanks snipe.
Mirko

**Comment by snipe** [comment]
There is no "deployed" status really though. If an asset is "ready to deploy" and unassigned, it's ready to deploy. If it's "ready to deploy" and is assigned, it's deployed.
