### ISSUE TITLE
Feature Request: Adding Photos to Asset Damage/Maintainance

### ISSUE THREAD

**Issue by JExactly** [snipe/snipe-it#1308]
Is it possible to add the ability to add Photos to the asset maintenance record when an asset is damaged to store a recorded image of the condition/damage to the device?

**Comment by vabue** [comment]
Great idea!

**Comment by vabue** [comment]
Also it is useful when you have check from Service Center whith some contact information and maintenance order number.

**Comment by DaltLund** [comment]
I would also love to have this as a feature. Asset Maintenance are already such a useful tool. Being able to see all the work done to an asset is a fantastic tool; being able to view these maintenances would be an extremely welcome addition.

**Comment by JExactly** [comment]
any update on this? I would still like to be able to add images to record the damage to an asset! 

Thanks!!

**Comment by TonisOrmisson** [comment]
+1
I also would like to record before->after photos to damage repair works

**Comment by JExactly** [comment]
I am still interested in this feature improvement!

**Comment by snipe** [comment]
The ability to add an image to asset maintenances was added in 4.3.0
