### ISSUE TITLE
Add Supplier From Hardware Create Screen does not save

### ISSUE THREAD

**Issue by GuloGuloDesu** [snipe/snipe-it#1309]
Snipe-It v2.0-175
Ubuntu 64-bit Server (LAMP) in Virtual Box
http://xxxxxx/snipe-it-master/public/hardware/create

When creating a new asset and I click on the blue + to create a new supplier a window opens up.  I am able to type in the new supplier name, but when I click on the Save button nothing happens.  The new supplier window does not close, and the new supplier is not created.  Literally nothing happens.
I have tested this in the following browsers on Windows 10 Pro 64-bit:
Microsoft Edge 20.10240.16384.0
Opera 33.0.1990.43
Chrome 46.0.2490.80 m
Firefox 41.0.2

If I get a chance later I will check the browsers to see if there is a POST or GET event, or something to see if anything is actually happening.  I do not have the time now to troubleshoot further.

**Comment by snipe** [comment]
Are you able to reproduce this on the demo?

**Comment by GuloGuloDesu** [comment]
It works fine on the demo.

**Comment by orygen** [comment]
I had the same issue as well.

**Comment by snipe** [comment]
Can you folks tell me if there's anything in your browser's error console?

**Comment by orygen** [comment]
Jest tested this, it seems like I no longer have this issue on the new version (2.04). I had it when I was on 2.03.
