### ISSUE TITLE
Oh no!  Server Error: 500 (Internal Server Error)

### ISSUE THREAD

**Issue by vanqy** [snipe/snipe-it#1311]
i just installed snipe-it on Ubuntu 14.0.4 
i browse to the server and i get

Whoops!
Server Error: 500 (Internal Server Error)

**Comment by mtucker6784** [comment]
Greetings, did you use the instructions from the official snipe it app, or use the install.sh in the repo?

**Comment by vanqy** [comment]
@mtucker6784 hi,I have tried both of the methods, but was still warned this error.

**Comment by snipe** [comment]
Please see the getting help page: http://docs.snipeitapp.com/getting-help.html
We need more information (such as specific log messages) in order to help.

**Comment by vanqy** [comment]
root@localhost:~# wget --no-check-certificate https://raw.github.com/GR360RY/snipeit-ansible/master/scripts/snipeit.sh -O - | sh
--2015-11-05 04:47:06--  https://raw.github.com/GR360RY/snipeit-ansible/master/scripts/snipeit.sh
Resolving raw.github.com (raw.github.com)... 23.235.47.133
Connecting to raw.github.com (raw.github.com)|23.235.47.133|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/GR360RY/snipeit-ansible/master/scripts/snipeit.sh [following]
--2015-11-05 04:47:06--  https://raw.githubusercontent.com/GR360RY/snipeit-ansible/master/scripts/snipeit.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 23.235.47.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|23.235.47.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 785 [text/plain]
Saving to: 'STDOUT'

 0% [                                                         ] 0           --.-K/s              
 >> Install Git and Ansible
100%[========================================================>] 785         --.-K/s   in 0s      

2015-11-05 04:47:07 (141 MB/s) - written to stdout [785/785]

Ign http://archive.ubuntu.com trusty InRelease
Ign http://archive.canonical.com trusty InRelease
Get:1 http://security.ubuntu.com trusty-security InRelease [64.4 kB]
Get:2 http://archive.ubuntu.com trusty-updates InRelease [64.4 kB]             
Get:3 http://archive.canonical.com trusty Release.gpg [933 B]                  
Get:4 http://archive.canonical.com trusty Release [9359 B]                     
Get:5 http://archive.canonical.com trusty/partner i386 Packages [6301 B]       
Get:6 http://security.ubuntu.com trusty-security/main i386 Packages [342 kB]   
Get:7 http://archive.ubuntu.com trusty Release.gpg [933 B]                    
Get:8 http://archive.ubuntu.com trusty-updates/main i386 Packages [623 kB]    
Ign http://archive.canonical.com trusty/partner Translation-en                 
Get:9 http://security.ubuntu.com trusty-security/restricted i386 Packages [12.2 kB]
Get:10 http://security.ubuntu.com trusty-security/universe i386 Packages [117 kB]
Get:11 http://security.ubuntu.com trusty-security/multiverse i386 Packages [3846 B]
Get:12 http://security.ubuntu.com trusty-security/main Translation-en [196 kB] 
Get:13 http://security.ubuntu.com trusty-security/multiverse Translation-en [1679 B]
Get:14 http://security.ubuntu.com trusty-security/restricted Translation-en [3076 B]
Get:15 http://security.ubuntu.com trusty-security/universe Translation-en [68.4 kB]
Get:16 http://archive.ubuntu.com trusty-updates/restricted i386 Packages [15.1 kB]
Get:17 http://archive.ubuntu.com trusty-updates/universe i386 Packages [327 kB]
Get:18 http://archive.ubuntu.com trusty-updates/main Translation-en [313 kB]
Get:19 http://archive.ubuntu.com trusty-updates/restricted Translation-en [3569 B]
Get:20 http://archive.ubuntu.com trusty-updates/universe Translation-en [172 kB]
Get:21 http://archive.ubuntu.com trusty Release [58.5 kB]                      
Get:22 http://archive.ubuntu.com trusty/main i386 Packages [1348 kB]           
Get:23 http://archive.ubuntu.com trusty/restricted i386 Packages [13.4 kB]     
Get:24 http://archive.ubuntu.com trusty/universe i386 Packages [5866 kB]       
Get:25 http://archive.ubuntu.com trusty/main Translation-en [762 kB]           
Get:26 http://archive.ubuntu.com trusty/restricted Translation-en [3457 B]     
Get:27 http://archive.ubuntu.com trusty/universe Translation-en [4089 kB]      
Fetched 14.5 MB in 1min 31s (158 kB/s)                                         
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  gir1.2-glib-2.0 iso-codes libcurl3-gnutls libdbus-glib-1-2
  libgirepository-1.0-1 librtmp0 python-apt python-apt-common python-pycurl
  python3-apt python3-dbus python3-gi python3-pycurl
  python3-software-properties unattended-upgrades
Suggested packages:
  isoquery python-apt-dbg python-gtk2 python-vte python-apt-doc
  libcurl4-gnutls-dev python-pycurl-dbg python3-apt-dbg python-dbus-doc
  python3-dbus-dbg python3-pycurl-dbg
The following NEW packages will be installed:
  gir1.2-glib-2.0 iso-codes libcurl3-gnutls libdbus-glib-1-2
  libgirepository-1.0-1 librtmp0 python-apt python-apt-common python-pycurl
  python-software-properties python3-apt python3-dbus python3-gi
  python3-pycurl python3-software-properties software-properties-common
  unattended-upgrades
0 upgraded, 17 newly installed, 0 to remove and 118 not upgraded.
Need to get 3270 kB of archives.
After this operation, 21.0 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main librtmp0 i386 2.4+20121230.gitdf6c518-1 [57.2 kB]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libcurl3-gnutls i386 7.35.0-1ubuntu2.5 [167 kB]
Get:3 http://archive.ubuntu.com/ubuntu/ trusty/main libdbus-glib-1-2 i386 0.100.2-1 [74.2 kB]
Get:4 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libgirepository-1.0-1 i386 1.40.0-1ubuntu0.2 [86.1 kB]
Get:5 http://archive.ubuntu.com/ubuntu/ trusty-updates/main gir1.2-glib-2.0 i386 1.40.0-1ubuntu0.2 [123 kB]
Get:6 http://archive.ubuntu.com/ubuntu/ trusty/main iso-codes all 3.52-1 [2073 kB]
Get:7 http://archive.ubuntu.com/ubuntu/ trusty-updates/main python-apt-common all 0.9.3.5ubuntu1 [17.1 kB]
Get:8 http://archive.ubuntu.com/ubuntu/ trusty-updates/main python3-apt i386 0.9.3.5ubuntu1 [136 kB]
Get:9 http://archive.ubuntu.com/ubuntu/ trusty/main python3-dbus i386 1.2.0-2build2 [80.6 kB]
Get:10 http://archive.ubuntu.com/ubuntu/ trusty-updates/main python3-gi i386 3.12.0-1ubuntu1 [152 kB]
Get:11 http://archive.ubuntu.com/ubuntu/ trusty-updates/main python-apt i386 0.9.3.5ubuntu1 [137 kB]
Get:12 http://archive.ubuntu.com/ubuntu/ trusty/main python-pycurl i386 7.19.3-0ubuntu3 [46.9 kB]
Get:13 http://archive.ubuntu.com/ubuntu/ trusty-updates/main unattended-upgrades all 0.82.1ubuntu2.3 [25.5 kB]
Get:14 http://archive.ubuntu.com/ubuntu/ trusty-updates/universe python-software-properties all 0.92.37.6 [19.6 kB]
Get:15 http://archive.ubuntu.com/ubuntu/ trusty/main python3-pycurl i386 7.19.3-0ubuntu3 [46.3 kB]
Get:16 http://archive.ubuntu.com/ubuntu/ trusty-updates/main python3-software-properties all 0.92.37.6 [19.1 kB]
Get:17 http://archive.ubuntu.com/ubuntu/ trusty-updates/main software-properties-common all 0.92.37.6 [9372 B]
Fetched 3270 kB in 3s (1084 kB/s)                 
Preconfiguring packages ...
Selecting previously unselected package librtmp0:i386.
(Reading database ... 25402 files and directories currently installed.)
Preparing to unpack .../librtmp0_2.4+20121230.gitdf6c518-1_i386.deb ...
Unpacking librtmp0:i386 (2.4+20121230.gitdf6c518-1) ...
Selecting previously unselected package libcurl3-gnutls:i386.
Preparing to unpack .../libcurl3-gnutls_7.35.0-1ubuntu2.5_i386.deb ...
Unpacking libcurl3-gnutls:i386 (7.35.0-1ubuntu2.5) ...
Selecting previously unselected package libdbus-glib-1-2:i386.
Preparing to unpack .../libdbus-glib-1-2_0.100.2-1_i386.deb ...
Unpacking libdbus-glib-1-2:i386 (0.100.2-1) ...
Selecting previously unselected package libgirepository-1.0-1.
Preparing to unpack .../libgirepository-1.0-1_1.40.0-1ubuntu0.2_i386.deb ...
Unpacking libgirepository-1.0-1 (1.40.0-1ubuntu0.2) ...
Selecting previously unselected package gir1.2-glib-2.0.
Preparing to unpack .../gir1.2-glib-2.0_1.40.0-1ubuntu0.2_i386.deb ...
Unpacking gir1.2-glib-2.0 (1.40.0-1ubuntu0.2) ...
Selecting previously unselected package iso-codes.
Preparing to unpack .../iso-codes_3.52-1_all.deb ...
Unpacking iso-codes (3.52-1) ...
Selecting previously unselected package python-apt-common.
Preparing to unpack .../python-apt-common_0.9.3.5ubuntu1_all.deb ...
Unpacking python-apt-common (0.9.3.5ubuntu1) ...
Selecting previously unselected package python3-apt.
Preparing to unpack .../python3-apt_0.9.3.5ubuntu1_i386.deb ...
Unpacking python3-apt (0.9.3.5ubuntu1) ...
Selecting previously unselected package python3-dbus.
Preparing to unpack .../python3-dbus_1.2.0-2build2_i386.deb ...
Unpacking python3-dbus (1.2.0-2build2) ...
Selecting previously unselected package python3-gi.
Preparing to unpack .../python3-gi_3.12.0-1ubuntu1_i386.deb ...
Unpacking python3-gi (3.12.0-1ubuntu1) ...
Selecting previously unselected package python-apt.
Preparing to unpack .../python-apt_0.9.3.5ubuntu1_i386.deb ...
Unpacking python-apt (0.9.3.5ubuntu1) ...
Selecting previously unselected package python-pycurl.
Preparing to unpack .../python-pycurl_7.19.3-0ubuntu3_i386.deb ...
Unpacking python-pycurl (7.19.3-0ubuntu3) ...
Selecting previously unselected package unattended-upgrades.
Preparing to unpack .../unattended-upgrades_0.82.1ubuntu2.3_all.deb ...
Unpacking unattended-upgrades (0.82.1ubuntu2.3) ...
Selecting previously unselected package python-software-properties.
Preparing to unpack .../python-software-properties_0.92.37.6_all.deb ...
Unpacking python-software-properties (0.92.37.6) ...
Selecting previously unselected package python3-pycurl.
Preparing to unpack .../python3-pycurl_7.19.3-0ubuntu3_i386.deb ...
Unpacking python3-pycurl (7.19.3-0ubuntu3) ...
Selecting previously unselected package python3-software-properties.
Preparing to unpack .../python3-software-properties_0.92.37.6_all.deb ...
Unpacking python3-software-properties (0.92.37.6) ...
Selecting previously unselected package software-properties-common.
Preparing to unpack .../software-properties-common_0.92.37.6_all.deb ...
Unpacking software-properties-common (0.92.37.6) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up librtmp0:i386 (2.4+20121230.gitdf6c518-1) ...
Setting up libcurl3-gnutls:i386 (7.35.0-1ubuntu2.5) ...
Setting up libdbus-glib-1-2:i386 (0.100.2-1) ...
Setting up libgirepository-1.0-1 (1.40.0-1ubuntu0.2) ...
Setting up gir1.2-glib-2.0 (1.40.0-1ubuntu0.2) ...
Setting up iso-codes (3.52-1) ...
Setting up python-apt-common (0.9.3.5ubuntu1) ...
Setting up python3-apt (0.9.3.5ubuntu1) ...
Setting up python3-dbus (1.2.0-2build2) ...
Setting up python3-gi (3.12.0-1ubuntu1) ...
Setting up python-apt (0.9.3.5ubuntu1) ...
Setting up python-pycurl (7.19.3-0ubuntu3) ...
Setting up unattended-upgrades (0.82.1ubuntu2.3) ...
Setting up python-software-properties (0.92.37.6) ...
Setting up python3-pycurl (7.19.3-0ubuntu3) ...
Setting up python3-software-properties (0.92.37.6) ...
Setting up software-properties-common (0.92.37.6) ...
Processing triggers for libc-bin (2.19-0ubuntu6.4) ...
gpg: keyring `/tmp/tmp1ok9izw7/secring.gpg' created
gpg: keyring `/tmp/tmp1ok9izw7/pubring.gpg' created
gpg: requesting key 7BB9C367 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmp1ok9izw7/trustdb.gpg: trustdb created
gpg: key 7BB9C367: public key "Launchpad PPA for Ansible, Inc." imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
Ign http://archive.ubuntu.com trusty InRelease
Hit http://security.ubuntu.com trusty-security InRelease            
Hit http://archive.ubuntu.com trusty-updates InRelease                         
Ign http://archive.canonical.com trusty InRelease                              
Hit http://security.ubuntu.com trusty-security/main i386 Packages              
Get:1 http://ppa.launchpad.net trusty InRelease [16.0 kB]                      
Hit http://archive.ubuntu.com trusty Release.gpg                               
Hit http://security.ubuntu.com trusty-security/restricted i386 Packages        
Hit http://archive.canonical.com trusty Release.gpg                            
Hit http://archive.ubuntu.com trusty-updates/main i386 Packages                
Hit http://security.ubuntu.com trusty-security/universe i386 Packages          
Hit http://archive.ubuntu.com trusty-updates/restricted i386 Packages          
Hit http://security.ubuntu.com trusty-security/multiverse i386 Packages        
Hit http://archive.canonical.com trusty Release                                
Hit http://archive.ubuntu.com trusty-updates/universe i386 Packages            
Get:2 http://ppa.launchpad.net trusty/main i386 Packages [493 B]               
Hit http://security.ubuntu.com trusty-security/main Translation-en             
Hit http://archive.ubuntu.com trusty-updates/main Translation-en               
Hit http://archive.canonical.com trusty/partner i386 Packages                  
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en       
Hit http://archive.ubuntu.com trusty-updates/restricted Translation-en         
Get:3 http://ppa.launchpad.net trusty/main Translation-en [322 B]              
Hit http://archive.ubuntu.com trusty-updates/universe Translation-en           
Hit http://security.ubuntu.com trusty-security/restricted Translation-en       
Hit http://archive.ubuntu.com trusty Release                                   
Hit http://security.ubuntu.com trusty-security/universe Translation-en         
Hit http://archive.ubuntu.com trusty/main i386 Packages                        
Hit http://archive.ubuntu.com trusty/restricted i386 Packages
Ign http://archive.canonical.com trusty/partner Translation-en           
Hit http://archive.ubuntu.com trusty/universe i386 Packages        
Hit http://archive.ubuntu.com trusty/main Translation-en
Hit http://archive.ubuntu.com trusty/restricted Translation-en
Hit http://archive.ubuntu.com trusty/universe Translation-en
Fetched 16.8 kB in 4s (4024 B/s)             
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  git-man liberror-perl libyaml-0-2 patch python-httplib2 python-jinja2
  python-markupsafe python-paramiko python-pkg-resources python-support
  python-yaml sshpass
Suggested packages:
  git-daemon-run git-daemon-sysvinit git-doc git-el git-email git-gui gitk
  gitweb git-arch git-bzr git-cvs git-mediawiki git-svn diffutils-doc
  python-jinja2-doc python-distribute python-distribute-doc
The following NEW packages will be installed:
  ansible git git-man liberror-perl libyaml-0-2 patch python-httplib2
  python-jinja2 python-markupsafe python-paramiko python-pkg-resources
  python-support python-yaml sshpass
0 upgraded, 14 newly installed, 0 to remove and 118 not upgraded.
Need to get 4512 kB of archives.
After this operation, 29.1 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libyaml-0-2 i386 0.1.4-3ubuntu3.1 [46.3 kB]
Get:2 http://ppa.launchpad.net/ansible/ansible/ubuntu/ trusty/main ansible all 1.9.4-1ppa~trusty [633 kB]
Get:3 http://archive.ubuntu.com/ubuntu/ trusty/universe python-support all 1.0.15 [26.7 kB]
Get:4 http://archive.ubuntu.com/ubuntu/ trusty/main python-markupsafe i386 0.18-1build2 [14.3 kB]
Get:5 http://archive.ubuntu.com/ubuntu/ trusty/main python-jinja2 all 2.7.2-2 [161 kB]
Get:6 http://archive.ubuntu.com/ubuntu/ trusty-updates/main python-yaml i386 3.10-4ubuntu0.1 [96.9 kB]
Get:7 http://archive.ubuntu.com/ubuntu/ trusty/main python-paramiko all 1.10.1-1git1build1 [106 kB]
Get:8 http://archive.ubuntu.com/ubuntu/ trusty/main python-httplib2 all 0.8-2build1 [35.4 kB]
Get:9 http://archive.ubuntu.com/ubuntu/ trusty/universe sshpass i386 1.05-1 [10.2 kB]
Get:10 http://archive.ubuntu.com/ubuntu/ trusty/main liberror-perl all 0.17-1.1 [21.1 kB]
Get:11 http://archive.ubuntu.com/ubuntu/ trusty-updates/main git-man all 1:1.9.1-1ubuntu0.1 [698 kB]
Get:12 http://archive.ubuntu.com/ubuntu/ trusty-updates/main git i386 1:1.9.1-1ubuntu0.1 [2511 kB]
Get:13 http://archive.ubuntu.com/ubuntu/ trusty-updates/main patch i386 2.7.1-4ubuntu2.3 [91.1 kB]
Get:14 http://archive.ubuntu.com/ubuntu/ trusty-updates/main python-pkg-resources all 3.3-1ubuntu2 [61.9 kB]
Fetched 4512 kB in 4s (1059 kB/s)           
Selecting previously unselected package libyaml-0-2:i386.
(Reading database ... 26195 files and directories currently installed.)
Preparing to unpack .../libyaml-0-2_0.1.4-3ubuntu3.1_i386.deb ...
Unpacking libyaml-0-2:i386 (0.1.4-3ubuntu3.1) ...
Selecting previously unselected package python-support.
Preparing to unpack .../python-support_1.0.15_all.deb ...
Unpacking python-support (1.0.15) ...
Selecting previously unselected package python-markupsafe.
Preparing to unpack .../python-markupsafe_0.18-1build2_i386.deb ...
Unpacking python-markupsafe (0.18-1build2) ...
Selecting previously unselected package python-jinja2.
Preparing to unpack .../python-jinja2_2.7.2-2_all.deb ...
Unpacking python-jinja2 (2.7.2-2) ...
Selecting previously unselected package python-yaml.
Preparing to unpack .../python-yaml_3.10-4ubuntu0.1_i386.deb ...
Unpacking python-yaml (3.10-4ubuntu0.1) ...
Selecting previously unselected package python-paramiko.
Preparing to unpack .../python-paramiko_1.10.1-1git1build1_all.deb ...
Unpacking python-paramiko (1.10.1-1git1build1) ...
Selecting previously unselected package python-httplib2.
Preparing to unpack .../python-httplib2_0.8-2build1_all.deb ...
Unpacking python-httplib2 (0.8-2build1) ...
Selecting previously unselected package sshpass.
Preparing to unpack .../sshpass_1.05-1_i386.deb ...
Unpacking sshpass (1.05-1) ...
Selecting previously unselected package ansible.
Preparing to unpack .../ansible_1.9.4-1ppa~trusty_all.deb ...
Unpacking ansible (1.9.4-1ppa~trusty) ...
Selecting previously unselected package liberror-perl.
Preparing to unpack .../liberror-perl_0.17-1.1_all.deb ...
Unpacking liberror-perl (0.17-1.1) ...
Selecting previously unselected package git-man.
Preparing to unpack .../git-man_1%3a1.9.1-1ubuntu0.1_all.deb ...
Unpacking git-man (1:1.9.1-1ubuntu0.1) ...
Selecting previously unselected package git.
Preparing to unpack .../git_1%3a1.9.1-1ubuntu0.1_i386.deb ...
Unpacking git (1:1.9.1-1ubuntu0.1) ...
Selecting previously unselected package patch.
Preparing to unpack .../patch_2.7.1-4ubuntu2.3_i386.deb ...
Unpacking patch (2.7.1-4ubuntu2.3) ...
Selecting previously unselected package python-pkg-resources.
Preparing to unpack .../python-pkg-resources_3.3-1ubuntu2_all.deb ...
Unpacking python-pkg-resources (3.3-1ubuntu2) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up libyaml-0-2:i386 (0.1.4-3ubuntu3.1) ...
Setting up python-support (1.0.15) ...
Setting up python-markupsafe (0.18-1build2) ...
Setting up python-jinja2 (2.7.2-2) ...
Setting up python-yaml (3.10-4ubuntu0.1) ...
Setting up python-paramiko (1.10.1-1git1build1) ...
Setting up python-httplib2 (0.8-2build1) ...
Setting up sshpass (1.05-1) ...
Setting up ansible (1.9.4-1ppa~trusty) ...
Setting up liberror-perl (0.17-1.1) ...
Setting up git-man (1:1.9.1-1ubuntu0.1) ...
Setting up git (1:1.9.1-1ubuntu0.1) ...
Setting up patch (2.7.1-4ubuntu2.3) ...
Setting up python-pkg-resources (3.3-1ubuntu2) ...
Processing triggers for libc-bin (2.19-0ubuntu6.4) ...
Processing triggers for python-support (1.0.15) ...

 >> Clone snipeit-ansible installation repository
Cloning into '/root/snipeit-ansible'...
remote: Counting objects: 181, done.
remote: Total 181 (delta 0), reused 0 (delta 0), pack-reused 181
Receiving objects: 100% (181/181), 30.17 KiB | 0 bytes/s, done.
Resolving deltas: 100% (78/78), done.
Checking connectivity... done.

 >> Install Snipe-IT

PLAY [snipeit] **************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [snipeit-ansible | Install Requirements] ******************************** 
changed: [127.0.0.1] => (item=git,apache2,mysql-server,php5,php5-mcrypt,php5-mysql,php5-gd,curl,php5-curl,python-mysqldb,expect)

TASK: [snipeit-ansible | Clone Snipe-IT repo] ********************************* 
changed: [127.0.0.1]

TASK: [snipeit-ansible | Update production bootstrap enviroment] ************** 
changed: [127.0.0.1]

TASK: [snipeit-ansible | Update production database configuration template] *** 
changed: [127.0.0.1]

TASK: [snipeit-ansible | Update production app configuration] ***************** 
changed: [127.0.0.1]

TASK: [snipeit-ansible | Update production mail settings] ********************* 
changed: [127.0.0.1]

TASK: [snipeit-ansible | Enable php extensions] ******************************* 
changed: [127.0.0.1] => (item=mcrypt)
changed: [127.0.0.1] => (item=pdo_mysql)

TASK: [snipeit-ansible | Install composer locally] **************************** 
changed: [127.0.0.1]

TASK: [snipeit-ansible | Install php requirements with composer] ************** 
changed: [127.0.0.1]

TASK: [snipeit-ansible | Generate production app key] ************************* 
changed: [127.0.0.1]

TASK: [snipeit-ansible | Make sure MySQL server is running and starts on boot] *** 
ok: [127.0.0.1]

TASK: [snipeit-ansible | Create snipeit database] ***************************** 
changed: [127.0.0.1]

TASK: [snipeit-ansible | Create snipeit mysql user] *************************** 
changed: [127.0.0.1]

TASK: [snipeit-ansible | Create snipeit mysql user for remote db access] ****** 
skipping: [127.0.0.1]

TASK: [snipeit-ansible | Run mysql on all interfaces ( for dev setup )] ******* 
skipping: [127.0.0.1]

TASK: [snipeit-ansible | Make sure mysql starts on boot] ********************** 
ok: [127.0.0.1]

TASK: [snipeit-ansible | Add expect installation script for Artisan] ********** 
changed: [127.0.0.1]

TASK: [snipeit-ansible | Install Snipe-IT Application with Artisan] *********** 
changed: [127.0.0.1]

TASK: [snipeit-ansible | Fix app/storage and public/uploads folders permissions] *** 
changed: [127.0.0.1] => (item=/opt/snipe-it/app/storage)
changed: [127.0.0.1] => (item=/opt/snipe-it/public/uploads)

TASK: [snipeit-ansible | Enable mode rewrite in Apache] *********************** 
changed: [127.0.0.1]

TASK: [snipeit-ansible | Create snipe virtual host in apache] ***************** 
changed: [127.0.0.1]

TASK: [snipeit-ansible | Enable snipeit virtual host] ************************* 
changed: [127.0.0.1]

TASK: [snipeit-ansible | Disable default Apache Site] ************************* 
changed: [127.0.0.1]

TASK: [snipeit-ansible | Make sure apache is enabled and starts on boot] ****** 
changed: [127.0.0.1]

TASK: [snipeit-ansible | Install Python Requirements] ************************* 
changed: [127.0.0.1] => (item=python-ldap,python-storm,python-pip)

TASK: [snipeit-ansible | Install ldapdict python library] ********************* 
changed: [127.0.0.1]

TASK: [snipeit-ansible | Install import_ad_users.py script] ******************* 
changed: [127.0.0.1]

NOTIFIED: [snipeit-ansible | restart apache] ********************************** 
changed: [127.0.0.1]

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=27   changed=24   unreachable=0    failed=0   

root@localhost:~#

**Comment by snipe** [comment]
We need error logs, not your install log. http://docs.snipeitapp.com/getting-help.html
