### ISSUE TITLE
Exporting to PDF,text or CSV

### ISSUE THREAD

**Issue by abdullahalasham** [snipe/snipe-it#1315]
Hi ,

indeed i am trying to Export reports or Data in assets management section is there anything i missed in my configuration 
i have tried the last three versions with same results

Kind regards

**Comment by snipe** [comment]
Can you be a little more specific? What's happening when you try to export?

**Comment by abdullahalasham** [comment]
hi,

the problem of exporting was in the version   (v2.0-175) yet with   (v2.0.5-pre) the problem has been solved but it download a files without the file extension.

by the way when i try to generate a backup i get Server Error: 500 (Internal Server Error)

and in assets management when i click on status(user name) i get The requested URL /ict/public/admin/users/6/view was not found on this server. and this can be solved if i change the link to http://127.0.0.1/ict/public/index.php/admin/users/6/view

thank you in advance for your kind support

**Comment by snipe** [comment]
Yes, you can just rename the downloaded file.

Please create separate tickets for each issue.

**Comment by snipe** [comment]
(Also, your path looks wrong. You shouldn't have `public/index.php` in the URL bar.)
