### ISSUE TITLE
Installation video for Windows PC

### ISSUE THREAD

**Issue by hltclk** [snipe/snipe-it#1316]
Hello, I am new in this. Can anybody make a video to show how to install and run it on a Windows PC with Wammp or Xammp? If there is a video already, please let me know. I tried the follow the guide but I think I am missing something. I am desperately need help. Thanks in advance.

**Comment by snipe** [comment]
Hi @hltclk - we don't gave a video, but if you tell us what steps you've taken and where you're getting stuck, we'll try to help.

**Comment by hltclk** [comment]
This is what I get when I choose "use composer here" in the "snipe" folder and type "php artisan app:install --env=production"

--------------------------------------------------------------------------------------------
Basic usage: composer <command>
For more information just type "composer".

C:\xampp\htdocs\snipe>php artisan app:install --env=production

Fatal error: Class 'Patchwork\Utf8\Bootup' not found in C:\xampp\htdocs\snipe\bo
otstrap\autoload.php on line 45

C:\xampp\htdocs\snipe>
=====================================================

**Comment by snipe** [comment]
http://docs.snipeitapp.com/common-issues.html#php-fatal-error-class-patchworkutf8bootup-not-found-in-bootstrapautoloadphp-on-line-43
