### ISSUE TITLE
[Feature Request]: Support for Microsoft SQL

### ISSUE THREAD

**Issue by israelrbb** [snipe/snipe-it#13165]
### Is your feature request related to a problem? Please describe.

Hi,

I was able to get Snipe-IT working with Microsoft SQL Version 2019, on a windows PC.
So far, I haven't found any bugs, but I'm still testing, the API's also appear to be working.

Is this something can be implemented for future support or would I have to manage it on a branch?

### Describe the solution you'd like

Integration of Microsoft SQL Support

**Comment by uberbrady** [comment]
If you need to make changes to the code to support SQL Server, it would have to be implemented in such a way that it doesn't break for MySQL users. But if you could make the changes in that fashion, we would probably accept them. If it bloats out the codebase or is messy, we probably wouldn't accept them, and you might have to maintain your own fork.

Ideally, you won't have to make any changes at all and it will "Just Work." That'd be the hope, at least.

**Comment by israelrbb** [comment]
I will see if I can get it configured to work for both.
There are only 4 files so far that need to be modified, so hopefully, it won't bloat the codebase.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
