### ISSUE TITLE
Bulk delete does not work

### ISSUE THREAD

**Issue by swoopdk** [snipe/snipe-it#1317]
Bulk delete of users doesn't seem to work. 
Tried on both the Demo and my own Docker install with same result. 

You can mark x number of users but clicking Go on bulk delete on the bottom of the pages loads the bulk edit page, but with 0 people selected for some reason. 

Tried multiple browsers with same result. Also no errors or anything i can find in console or similar.

**Comment by merid14** [comment]
looks to be an issue on (v2.0-394) as it was working before this version.

**Comment by snipe** [comment]
I'll take a look. We changed a lot of the listing views for everything when we switched to bootstrap tables, so we may have a regression issue here.
