### ISSUE TITLE
How to use LDAP password to log in users

### ISSUE THREAD

**Issue by itisNathaniel** [snipe/snipe-it#1322]
Hi, I couldn't see anything in the LDAP set up guide about configuring LDAP to use the user's own password, only setting a new password for the LDAP user in Snipe IT.
The page says passwords will be auto generated, is there a way to use the password straight from the LDAP server itself?

**Comment by snipe** [comment]
The system will automatically try to authenticate against LDAP if they were imported as an LDAP user

**Comment by itisNathaniel** [comment]
Does the password need to be defined in the search filter as the first name and surnames are?
I created a test user and imported from LDAP and it still gets an incorrect password message when it attempts to use its LDAP credentials.

**Comment by orygen** [comment]
@itisNathaniel, the user will login using the LDAP username and password. It automatically work that way, you don't need to define.

**Comment by ddreier** [comment]
@itisNathaniel is your LDAP source Active Directory? If so you need to set the `authentication.filter.query` config parameter to be `samaccountname=`. (`'authentication.filter.query' => "samaccountname="`)

**Comment by itisNathaniel** [comment]
@snipe Hi, for some reason it won't accept the LDAP credentials when I try to log in as shown here.
I'm authenticating against Synology Directory Service. 
![screen shot 2015-11-16 at 16 19 45](https://cloud.githubusercontent.com/assets/4061191/11187325/e14413e4-8c7d-11e5-888a-d8551fb2f225.png)
Here's my ldap.php:

    <?php

    return array(

    /*
    |--------------------------------------------------------------------------
    | URL
    |--------------------------------------------------------------------------
    |
    | URL for the LDAP server. This should start with ldap://, for example:
    | ldap://ldap.yourserver.com
    |
    */
    'url' => "ldap://192.168.0.1",


    /*
    |--------------------------------------------------------------------------
    | Username
    |--------------------------------------------------------------------------
    |
    | Username to use to connect authenticate to LDAP, for example:
    | cn=read-only-admin,dc=example,dc=com
    |
    */
	'username' => "uid=root,cn=users,dc=domain,dc=com",

	/*
    |--------------------------------------------------------------------------
    | Password
    |--------------------------------------------------------------------------
    |
    | Password to use when authenticating to LDAP.
    |
    */
	'password' => "ldapauthpassword",

	/*
    |--------------------------------------------------------------------------
    | Basedn
    |--------------------------------------------------------------------------
    |
    | The base where the search for users will be executed, for example:
    | dc=example,dc=com
    |
    */
	'basedn'   => "cn=users,dc=domain,dc=com",


	/*
    |--------------------------------------------------------------------------
    | Filter
    |--------------------------------------------------------------------------
    |
    | The search filter for the LDAP query. This probably does not have to be
    | changed.
    |
    */
	'filter' => "&(cn=*)",


	/*
    |--------------------------------------------------------------------------
    | LDAP field names that will be retrieved to create a user.
    |
    | Using the username as an example:
    | If I set 'result.username' => 'my-org-username', the code will connect to
    | LDAP as follows (where $results[$i] represents a row in the LDAP query:
    | $username-to-insert-in-snipe-it = $results[$i]["my-org-username"][0]
    |
    |--------------------------------------------------------------------------
    |
    | The search filter for the LDAP query.
    | Note: all these fields are required, and they should all be lowercase.
    |
    */
    'result.username' => "uid",
    'result.last.name'  => "sn",
    'result.first.name' => "cn",

    /*
    | These fields are optional as not all LDAP directories will have it.  If yours
    | does not have them, just leave these blank and the extra check will
    | be omitted.
    */
    'result.active.flag' => "",
    'result.emp.num'  => "",
    'result.email' => "",

    /*
    |--------------------------------------------------------------------------
    | LDAP filter query for authentication
    |--------------------------------------------------------------------------
    |
    | The LDAP query that we want to execute when authenticating a user. This
    | should not have to be changed.
    |
    */
    'authentication.filter.query' => "cn=users,uid=",

    /*
    |--------------------------------------------------------------------------
    | LDAP Version
    |--------------------------------------------------------------------------
    |
    | Version of LDAP you are using.
    |
    */
    'version' => 3,


    );

Thanks!

**Comment by ddreier** [comment]
Your filter query should not have the "cn=users," part in it. It should just be "uid=" *if that is the correct setting for your directory service*.

**Comment by itisNathaniel** [comment]
Thanks @ddreier! It works perfectly now.
