### ISSUE TITLE
[Feature Request] Signature on checkout / checkin

### ISSUE THREAD

**Issue by xiaochris** [snipe/snipe-it#1326]
Check in / out assets with Signatures

**Comment by snipe** [comment]
Can you be a little more specific here? What are you actually asking for?

**Comment by javi1110** [comment]
Not to answer for xia0chris, I think he means possibly a space on the form to sign either by the tech or cutomer making the status change, It would really come in handy with the consumable assets. Most of the techs that we have usethe app on their smartphones when they deliver printer paper they would love to have a plac for a signature.

**Comment by xiaochris** [comment]
Hi Snipe, 

Agree with what javi1110 said. Basically looking at a feature which can allow customer / tech to sign off after checking out or in of assets.

**Comment by snipe** [comment]
Are you suggesting a form that can actually capture a handwritten signature on the checkin/checkout?

**Comment by snipe** [comment]
(Something like this: http://szimek.github.io/signature_pad/ )

**Comment by xiaochris** [comment]
Hi Snipe,

yup. it would be good to integrate that into the asset system

**Comment by javi1110** [comment]
That would work perfectly, thanks fore taking the time.

**Comment by snipe** [comment]
This is implemented in v3.6-pre

**Comment by ekussberg** [comment]
@snipe what is with this feature in 4.0.9? We had it working in 3.6, but after upgrade even it is checked, the email, that user becomes after checkout doesn't have any button for signature.
