### ISSUE TITLE
Recent Activity Dashboard does not show creations

### ISSUE THREAD

**Issue by gmarcon** [snipe/snipe-it#1327]
In the recent activity view of the dashboard, asset creations are not shown.

This would be very helpful (for instance when more people are adding assets, they can immediately see if the asset was recently added; or when different people register new assets and assign them, this would allow to see immediately assets that became available and can be deployed).

Thank you and regards,
Giulio

**Comment by snipe** [comment]
I believe this was fixed a long while ago. Apologies for not updating this issue to reflect that.
