### ISSUE TITLE
Permissions for remote office manager

### ISSUE THREAD

**Issue by seanism** [snipe/snipe-it#1331]
We have a remote office and I'd like to have them add / assign inventory to their location and their location only.  They wouldn't need access to software as that should still go through IT.

Does this sound like a use case others would be interested in?

**Comment by snipe** [comment]
Hi @seanism - starting in v3, we've expanded user permissions, so we should be able to get this a little more granular for you. 

<img width="620" alt="screen shot 2016-07-09 at 4 45 50 pm" src="https://cloud.githubusercontent.com/assets/197404/16710872/a3ccbb5c-45f4-11e6-940d-b98cb429dcc9.png">
