### ISSUE TITLE
Bug on upgrade

### ISSUE THREAD

**Issue by NMonst4** [snipe/snipe-it#1336]
Hi,

i get an error message on some Assets (not on all) after upgrade.

Log:
Next exception 'ErrorException' with message 'Trying to get property of non-object (View: /var/www/snipe-it/app/views/backend/hardware/view.blade.php)' in /var/www/snipe-it/app/storage/views/5ecb6a32c6cd7dcf1dbd766ca9858553:371
Stack trace:

File: /var/www/snipe-it/app/storage/views/5ecb6a32c6cd7dcf1dbd766ca9858553:371
```
371                         <?php if($log->userlog->deleted_at==''): ?>
372                             <a href="<?php echo route('view/user', $log->checkedout_to); ?>">
373                             <?php echo e($log->userlog->fullName()); ?>
374
375                              </a>
376                         <?php else: ?>
377                             <del><?php echo e($log->userlog->fullName()); ?></del>
378                         <?php endif; ?>
```

Some ideas what went wrong?

**Comment by snipe** [comment]
Did you modify any of the data in the database directly?

**Comment by NMonst4** [comment]
Yes we create some users in the Database directly but now the users where replaced with LDAP users. Is there a way to fix the history data?

**Comment by snipe** [comment]
It's not finding a matching user for the log entry. You'd need to go into the asset logs table and remove any references to users that no longer exist in the database. 

http://docs.snipeitapp.com/installation/manually-editing-data.html

**Comment by NMonst4** [comment]
Thank you :) We love snipe-it :)

**Comment by snipe** [comment]
![lsp-tears](https://cloud.githubusercontent.com/assets/197404/11100469/5482e5cc-8866-11e5-806d-e1c24d1b5996.gif)
