### ISSUE TITLE
The requested URL view was not found on this server

### ISSUE THREAD

**Issue by abdullahalasham** [snipe/snipe-it#1338]
in assets management when i click on status(user name) i get The requested URL /ict/public/admin/users/6/view was not found on this server. and this can be solved if i change the link to http://127.0.0.1/ict/public/index.php/admin/users/6/view

is there anything i missed in my configuration 

kind regards

**Comment by snipe** [comment]
Your DocumentRoot should be set to the public directory. http://docs.snipeitapp.com/installation/server/linux-osx.html

You should never see /public/index.php as part of your URL.

**Comment by abdullahalasham** [comment]
indeed i am using the WAMP server how should i set public directories for that

**Comment by snipe** [comment]
http://sa-os.blogspot.com/2010/11/how-to-change-document-root-on-wamp.html

**Comment by abdullahalasham** [comment]
after setting the public directory and i navigate to http://localhost/ i get index of page and when i open http://localhost/public/ i get the following error:

ErrorException (E_WARNING)
HELP
mcrypt_encrypt(): Size of key is too large for this algorithm
Open: C:\wamp\www\ict\vendor\laravel\framework\src\Illuminate\Encryption\Encrypter.php
	 * @param  string  $iv
	 * @return string
	 */
	protected function padAndMcrypt($value, $iv)
	{
		$value = $this->addPadding(serialize($value));
 
		return mcrypt_encrypt($this->cipher, $this->key, $value, $this->mode, $iv);
	}
 
GET Data empty
POST Data empty
Files empty
Cookies empty
Session empty
Server/Request Data
HTTP_HOST	localhost
HTTP_CONNECTION	keep-alive
HTTP_CACHE_CONTROL	max-age=0
HTTP_ACCEPT	text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
HTTP_UPGRADE_INSECURE_REQUESTS	1
HTTP_USER_AGENT	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36
HTTP_ACCEPT_ENCODING	gzip, deflate, sdch
HTTP_ACCEPT_LANGUAGE	ar,en-US;q=0.8,en;q=0.6
PATH	C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\3.0\bin\x64;c:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Enterprise Vault\EVClient\x64\;C:\Program Files\Dell\Dell Data Protection\Drivers\TSS\bin\;C:\wamp\bin\php\php5.5.12;C:\ProgramData\ComposerSetup\bin;
SystemRoot	C:\Windows
COMSPEC	C:\Windows\system32\cmd.exe
PATHEXT	.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
WINDIR	C:\Windows
SERVER_SIGNATURE	<address>Apache/2.4.9 (Win64) PHP/5.5.12 Server at localhost Port 80</address>
SERVER_SOFTWARE	Apache/2.4.9 (Win64) PHP/5.5.12
SERVER_NAME	localhost
SERVER_ADDR	127.0.0.1
SERVER_PORT	80
REMOTE_ADDR	127.0.0.1
DOCUMENT_ROOT	C:/wamp/www/ict
REQUEST_SCHEME	http
CONTEXT_PREFIX	
CONTEXT_DOCUMENT_ROOT	C:/wamp/www/ict
SERVER_ADMIN	admin@example.com
SCRIPT_FILENAME	C:/wamp/www/ict/public/index.php
REMOTE_PORT	23411
GATEWAY_INTERFACE	CGI/1.1
SERVER_PROTOCOL	HTTP/1.1
REQUEST_METHOD	GET
QUERY_STRING	
REQUEST_URI	/public/
SCRIPT_NAME	/public/index.php
PHP_SELF	/public/index.php
REQUEST_TIME_FLOAT	1447272005.667
REQUEST_TIME	1447272005
Environment Variables empty

**Comment by snipe** [comment]
http://docs.snipeitapp.com/common-issues.html#error-message-mcrypt_encrypt-size-of-key-is-too-large-for-this-algorithm

**Comment by snipe** [comment]
Also, public should NOT be in your url.

**Comment by abdullahalasham** [comment]
if i did not add public in the url i get the index off : and the list of files

**Comment by snipe** [comment]
Because your document root is still not correct. The document root should be the public directory.

**Comment by abdullahalasham** [comment]
again i get another error The requested URL /auth/signin was not found on this server.

**Comment by snipe** [comment]
http://docs.snipeitapp.com/common-issues.html#the-requested-url-authsignin-was-not-found-on-this-server

**Comment by snipe** [comment]
I really need you to check the common issues page. It addresses most of what you've described so far.

**Comment by abdullahalasham** [comment]
indeed i have tried what was written in The requested URL /auth/signin was not found on this server
but i does not work 
my htaccess settings is as following:
 <IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On
 RewriteBase /ict
qwdewqdqdqwdqwdqwd
    # Uncomment these two lines to force SSL redirect
    # RewriteCond %{HTTPS} off
    # RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>

and the virtualhost config inside the httpd.conf is :


<VirtualHost *:80>

    Alias /ict  "/wamp/www/ict/public"

    <Directory /wamp/www/public>
        Allow From All
        AllowOverride All
        Options +Indexes
    </Directory>

    DocumentRoot /wamp/www/public
    ServerName 127.0.0.1
    # Other directives here
</VirtualHost>

and the app.php is as following

<?php

return array(

    /*
    |--------------------------------------------------------------------------
    | Application Debug Mode
    |--------------------------------------------------------------------------
    |
    | When your application is in debug mode, detailed error messages with
    | stack traces will be shown on every error that occurs within your
    | application. If disabled, a simple generic error page is shown.
    |
    */

    'debug' => true,

    /*
    |--------------------------------------------------------------------------
    | Application URL
    |--------------------------------------------------------------------------
    |
    | This URL is used by the console to properly generate URLs when using
    | the Artisan command line tool. You should set this to the root of
    | your application so that it is used when running Artisan tasks.
    |
    */

    'url' => 'https://127.0.0.1',


    /*
    |--------------------------------------------------------------------------
    | Organization Domain Name
    |--------------------------------------------------------------------------
    |
    | The domain name of the organization, used when generating email addresses
    | through the import tools.
    |
    */

    'domain' => '127.0.0.1',

    /*
    |--------------------------------------------------------------------------
    | Encryption Key
    |--------------------------------------------------------------------------
    |
    | This key is used by the Illuminate encrypter service and should be set
    | to a random, 32 character string, otherwise these encrypted strings
    | will not be safe. Please do this before deploying an application!
    |
    | Run a php artisan key:generate --env=staging to create a random one
    */

    'key' => '4XIIGIlD1jL1cAysWpcF707ruOUFbK51',

);
 is there anything missing???

**Comment by abdullahalasham** [comment]
sorry it was my fault the reiwrite mode was not enabled thank you for your tireless support

**Comment by snipe** [comment]
`Alias /ict  "/wamp/www/ict/public"`

`DocumentRoot /wamp/www/public`

Why are you using an alias?

**Comment by abdullahalasham** [comment]
when i removed the alias 


<VirtualHost *:80>

    <Directory /wamp/www/ict/public>
        Allow From All
        AllowOverride All
        Options +Indexes
    </Directory>

    DocumentRoot /wamp/www/ict/public
    ServerName 127.0.0.1
    # Other directives here
</VirtualHost>

i get : 

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at admin@example.com to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

**Comment by snipe** [comment]
Where do the files actually live? In `/wamp/www/public` or `/wamp/www/ict/public`?

**Comment by snipe** [comment]
You shouldn't need an alias if you're not running this in a sub-directory, but whatever path you give the DocumentRoot does need to exist and be correct for where the public directory actually exists on the machine.

**Comment by snipe** [comment]
Any updates here?

**Comment by abdullahalasham** [comment]
the issue has been resolved rewrite-modual was not enabled .
thanks for your support
