### ISSUE TITLE
Loading accessories (Ajax Error)

### ISSUE THREAD

**Issue by dmcnaughtan** [snipe/snipe-it#1342]
When I try and load accessories, I get a client-side pop-up:
![image](https://cloud.githubusercontent.com/assets/12763080/11128784/01e338fa-894a-11e5-9a1e-2cc060186f28.png)

Using the Chrome dev tools, this seems to be the culprit:

![image](https://cloud.githubusercontent.com/assets/12763080/11128868/72531498-894a-11e5-8d41-9c94e0db2d94.png)

**Comment by dmcnaughtan** [comment]
I just updated from v1.2.8 to v2.0.4.  Everything else seems to be working great!

**Comment by snipe** [comment]
Can you tell me what's in your error logs? That's a generic Datatables error that means that something broke on the data side. (Also, we're not using data tables anymore in the upcoming release.)

**Comment by dmcnaughtan** [comment]
192.168.1.123 - - [13/Nov/2015:08:47:08 -0500] "GET /assets/js/dataTables.tableTools.js HTTP/1.1" 200 21947 "http://assets.opr/admin/accessories" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36"
192.168.1.123 - - [13/Nov/2015:08:47:08 -0500] "GET /assets/js/jquery-latest.js HTTP/1.1" 200 84662 "http://assets.opr/admin/accessories" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36"
192.168.1.123 - - [13/Nov/2015:08:47:08 -0500] "GET /assets/js/select2.min.js HTTP/1.1" 200 29868 "http://assets.opr/admin/accessories" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36"
192.168.1.123 - - [13/Nov/2015:08:47:09 -0500] "GET /assets/js/snipeit.js HTTP/1.1" 200 1430 "http://assets.opr/admin/accessories" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36"
192.168.1.123 - - [13/Nov/2015:08:47:09 -0500] "GET /assets/css/compiled/print.css HTTP/1.1" 200 721 "http://assets.opr/admin/accessories" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36"
192.168.1.123 - - [13/Nov/2015:08:47:09 -0500] "GET /assets/font/fontawesome-webfont.woff2?v=4.3.0 HTTP/1.1" 200 57041 "http://assets.opr/assets/css/lib/font-awesome.min.css" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36"
192.168.1.123 - - [13/Nov/2015:08:47:09 -0500] "GET /assets/img/datatables/sort_both.png HTTP/1.1" 200 1420 "http://assets.opr/assets/css/lib/jquery.dataTables.css" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36"
192.168.1.123 - - [13/Nov/2015:08:47:09 -0500] "GET /assets/img/datatables/sort_asc.png HTTP/1.1" 200 1402 "http://assets.opr/assets/css/lib/jquery.dataTables.css" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36"
192.168.1.123 - - [13/Nov/2015:08:47:09 -0500] "GET /api/accessories/list?_=1447422436783 HTTP/1.1" 500 5728 "http://assets.opr/admin/accessories" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36"
192.168.1.123 - - [13/Nov/2015:08:47:09 -0500] "GET /assets/swf/copy_csv_xls_pdf.swf HTTP/1.1" 200 59151 "http://assets.opr/admin/accessories" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36"

**Comment by snipe** [comment]
I'm looking for your app logs, not your web server logs. http://docs.snipeitapp.com/getting-help.html

**Comment by dmcnaughtan** [comment]
The error log is empty.

**Comment by snipe** [comment]
Web server error log, or app log?

**Comment by dmcnaughtan** [comment]
my bad. sorry.  Let me go into debug mode.  Thanks for your patience.

**Comment by snipe** [comment]
You can also try loading http://assets.opr/api/accessories/list and see if there's an error thrown there (once you're on debug mode, otherwise it will just give you a generic 500 error.)

**Comment by snipe** [comment]
Also, let me know if you manually edited any data in the database at any point. That often dunks stuff up.

**Comment by dmcnaughtan** [comment]
I have no edited any data manually. 

This is the relevant info from the app log:

#1 [internal function]: Controllers\Admin\AccessoriesController->Controllers\Admin\{closure}(Object(Accessory))
#2 /var/www/Snipe-It/snipe-it/vendor/chumper/datatable/src/Chumper/Datatable/Columns/FunctionColumn.php(15): call_user_func(Object(Closure), Object(Accessory))
#3 /var/www/Snipe-It/snipe-it/vendor/chumper/datatable/src/Chumper/Datatable/Engines/CollectionEngine.php(264): Chumper\Datatable\Columns\FunctionColumn->run(Object(Accessory))
#4 [internal function]: Chumper\Datatable\Engines\CollectionEngine->Chumper\Datatable\Engines\{closure}(Object(Accessory), 0)
#5 /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Support/Collection.php(344): array_map(Object(Closure), Array, Array)
#6 /var/www/Snipe-It/snipe-it/vendor/chumper/datatable/src/Chumper/Datatable/Engines/CollectionEngine.php(270): Illuminate\Support\Collection->map(Object(Closure))
#7 /var/www/Snipe-It/snipe-it/vendor/chumper/datatable/src/Chumper/Datatable/Engines/CollectionEngine.php(123): Chumper\Datatable\Engines\CollectionEngine->compileArray(Object(Illuminate\Support\Collection))
#8 /var/www/Snipe-It/snipe-it/vendor/chumper/datatable/src/Chumper/Datatable/Engines/BaseEngine.php(225): Chumper\Datatable\Engines\CollectionEngine->internalMake(Object(Illuminate\Support\Collection), Array)
#9 /var/www/Snipe-It/snipe-it/app/controllers/admin/AccessoriesController.php(499): Chumper\Datatable\Engines\BaseEngine->make()
#10 [internal function]: Controllers\Admin\AccessoriesController->getDatatable()
#11 /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#12 /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('getDatatable', Array)
#13 /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\AccessoriesController), Object(Illuminate\Routing\Route), 'getDatatable')
#14 /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'getDatatable')
#15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#16 /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#17 /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#19 /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#20 /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#21 /var/www/Snipe-It/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#22 /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#23 /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#25 /var/www/Snipe-It/snipe-it/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#27 /var/www/Snipe-It/snipe-it/public/index.php(49): Illuminate\Foundation\Application->run()


This is the exception:

ErrorException thrown with message "Trying to get property of non-object"

Stacktrace:
#28 ErrorException in /var/www/Snipe-It/snipe-it/app/controllers/admin/AccessoriesController.php:482
#27 Illuminate\Exception\Handler:handleError in /var/www/Snipe-It/snipe-it/app/controllers/admin/AccessoriesController.php:482
#26 Controllers\Admin\AccessoriesController:Controllers\Admin\{closure} in <#unknown>:0
#25 call_user_func in /var/www/Snipe-It/snipe-it/vendor/chumper/datatable/src/Chumper/Datatable/Columns/FunctionColumn.php:15
#24 Chumper\Datatable\Columns\FunctionColumn:run in /var/www/Snipe-It/snipe-it/vendor/chumper/datatable/src/Chumper/Datatable/Engines/CollectionEngine.php:264
#23 Chumper\Datatable\Engines\CollectionEngine:Chumper\Datatable\Engines\{closure} in <#unknown>:0
#22 array_map in /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Support/Collection.php:344
#21 Illuminate\Support\Collection:map in /var/www/Snipe-It/snipe-it/vendor/chumper/datatable/src/Chumper/Datatable/Engines/CollectionEngine.php:270
#20 Chumper\Datatable\Engines\CollectionEngine:compileArray in /var/www/Snipe-It/snipe-it/vendor/chumper/datatable/src/Chumper/Datatable/Engines/CollectionEngine.php:123
#19 Chumper\Datatable\Engines\CollectionEngine:internalMake in /var/www/Snipe-It/snipe-it/vendor/chumper/datatable/src/Chumper/Datatable/Engines/BaseEngine.php:225
#18 Chumper\Datatable\Engines\BaseEngine:make in /var/www/Snipe-It/snipe-it/app/controllers/admin/AccessoriesController.php:499
#17 Controllers\Admin\AccessoriesController:getDatatable in <#unknown>:0
#16 call_user_func_array in /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:231
#15 Illuminate\Routing\Controller:callAction in /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:93
#14 Illuminate\Routing\ControllerDispatcher:call in /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:62
#13 Illuminate\Routing\ControllerDispatcher:dispatch in /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php:967
#12 Illuminate\Routing\Router:Illuminate\Routing\{closure} in <#unknown>:0
#11 call_user_func_array in /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Route.php:109
#10 Illuminate\Routing\Route:run in /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1033
#9 Illuminate\Routing\Router:dispatchToRoute in /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1001
#8 Illuminate\Routing\Router:dispatch in /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:775
#7 Illuminate\Foundation\Application:dispatch in /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:745
#6 Illuminate\Foundation\Application:handle in /var/www/Snipe-It/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php:34
#5 Barryvdh\Debugbar\Middleware\Stack:handle in /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware.php:72
#4 Illuminate\Session\Middleware:handle in /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php:47
#3 Illuminate\Cookie\Queue:handle in /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php:51
#2 Illuminate\Cookie\Guard:handle in /var/www/Snipe-It/snipe-it/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23
#1 Stack\StackedHttpKernel:handle in /var/www/Snipe-It/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:641
#0 Illuminate\Foundation\Application:run in /var/www/Snipe-It/snipe-it/public/index.php:49

**Comment by snipe** [comment]
Can you tell me what's on line 482 in `/var/www/Snipe-It/snipe-it/app/controllers/admin/AccessoriesController.php` in the version you're using?

**Comment by snipe** [comment]
(Give me a few lines above and below as well, for context)

**Comment by dmcnaughtan** [comment]
<pre>

    public function getDatatable()
    {
        $accessories = Accessory::with('category')
        ->whereNull('deleted_at')
        ->orderBy('created_at', 'DESC');

        $accessories = $accessories->get();

        $actions = new \Chumper\Datatable\Columns\FunctionColumn('actions',function($accessories)
            {
                return '<a href="'.route('checkout/accessory', $accessories->id).'" style="margin-right:5px;" class="btn btn-info btn-sm" '.(($accessories->numRe$
            });

        return Datatable::collection($accessories)
        ->addColumn('category',function($accessories)
            {
482                return $accessories->category->name;
            })
        ->addColumn('name',function($accessories)
            {
                return link_to('admin/accessories/'.$accessories->id.'/view', $accessories->name);
            })
        ->addColumn('qty',function($accessories)
            {
                return $accessories->qty;
            })
        ->addColumn('numRemaining',function($accessories)
            {
                return $accessories->numRemaining();
            })
        ->addColumn($actions)
        ->searchColumns('category','name','qty','numRemaining','actions')
        ->orderColumns('category','name','qty','numRemaining','actions')
        ->make();        
    } 
</pre>

**Comment by snipe** [comment]
Which is line 482 though?

**Comment by dmcnaughtan** [comment]
return $accessories->category->name;

**Comment by snipe** [comment]
That looks like bad data, as if there is an accessory associated with a category that was deleted.

**Comment by snipe** [comment]
(Also, that looks like an older version of Snipe-IT. Should upgrade when you get a chance. If there's bad data in there, it won't help that part, but other bug fixes and improvements are in the latest version.)
