### ISSUE TITLE
Syntax error, unexpected 'key'

### ISSUE THREAD

**Issue by rvasquez151** [snipe/snipe-it#1343]
I am trying to install Snipe-it 2.0.4 using WAMP.  It is installed on localhost only.  Tried to access page - getting this error message:
Symfony\Component\Debug\Exception\FatalErrorException thrown with message "syntax error, unexpected 'key' (T_STRING), expecting ')'"

Stacktrace:
#1 Symfony\Component\Debug\Exception\FatalErrorException in C:\wamp\www\snipe-it\app\config\production\app.php:56
#0 Illuminate\Exception\Handler:handleShutdown in <#unknown>:0

It appears to be pointing to the 32 character key I have set - '12345665432109876@#$%^&*12345678'
Below that on the left side is:
0.illuminate\Exception\Handler
handleShutdown
<#unknown>:0

Does anyone have any suggestions? I appreciated the help. 

This is the stack trace log:
Stack trace:
#0 C:\wamp\www\snipe-it\vendor\symfony\console\Symfony\Component\Console\Application.php(190): Symfony\Component\Console\Application->find('config:clear')
#1 C:\wamp\www\snipe-it\vendor\symfony\console\Symfony\Component\Console\Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 C:\wamp\www\snipe-it\artisan(59): Symfony\Component\Console\Application->run()
#3 {main} [] []
[2015-11-12 13:31:02] production.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000] [1045] Access denied for user 'houston'@'localhost' (using password: YES)' in C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:47
Stack trace:
#0 C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(47): PDO->__construct('mysql:host=loca...', 'houston', 'P@ssw0rd', Array)
#1 C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(57): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connectors\ConnectionFactory.php(46): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
#4 C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(176): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#5 C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(64): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#6 C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Migrations\DatabaseMigrationRepository.php(167): Illuminate\Database\DatabaseManager->connection(NULL)
#7 C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Migrations\DatabaseMigrationRepository.php(115): Illuminate\Database\Migrations\DatabaseMigrationRepository->getConnection()
#8 C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Console\Migrations\InstallCommand.php(52): Illuminate\Database\Migrations\DatabaseMigrationRepository->createRepository()
#9 C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(112): Illuminate\Database\Console\Migrations\InstallCommand->fire()
#10 C:\wamp\www\snipe-it\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(128): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 C:\wamp\www\snipe-it\app\commands\AppCommand.php(90): Illuminate\Console\Command->call('migrate:install')
#14 C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(112): AppCommand->fire()
#15 C:\wamp\www\snipe-it\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 C:\wamp\www\snipe-it\vendor\symfony\console\Symfony\Component\Console\Application.php(889): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 C:\wamp\www\snipe-it\vendor\symfony\console\Symfony\Component\Console\Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(AppCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 C:\wamp\www\snipe-it\vendor\symfony\console\Symfony\Component\Console\Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 C:\wamp\www\snipe-it\artisan(59): Symfony\Component\Console\Application->run()
#21 {main} [] []

**Comment by snipe** [comment]
My guess is that you donked something up when customizing the config. Can you show me your `app/configs/production/app.php` file?

**Comment by rvasquez151** [comment]
This is my app.php file in app/configs/production/app.php ( I noticed there is another app.php in the root of config:

<?php

return array(

    /*
    |--------------------------------------------------------------------------
    | Application Debug Mode
    |--------------------------------------------------------------------------
    |
    | When your application is in debug mode, detailed error messages with
    | stack traces will be shown on every error that occurs within your
    | application. If disabled, a simple generic error page is shown.
    |
    */

    'debug' => true,

    /*
    |--------------------------------------------------------------------------
    | Application URL
    |--------------------------------------------------------------------------
    |
    | This URL is used by the console to properly generate URLs when using
    | the Artisan command line tool. You should set this to the root of
    | your application so that it is used when running Artisan tasks.
    |
    */

    'url' => 'https://127.0.0.1',


    /*
    |--------------------------------------------------------------------------
    | Organization Domain Name
    |--------------------------------------------------------------------------
    |
    | The domain name of the organization, used when generating email addresses
    | through the import tools.
    |
    */

    'domain' => '127.0.0.1

    /*
    |--------------------------------------------------------------------------
    | Encryption Key
    |--------------------------------------------------------------------------
    |
    | This key is used by the Illuminate encrypter service and should be set
    | to a random, 32 character string, otherwise these encrypted strings
    | will not be safe. Please do this before deploying an application!
    |
    | Run a php artisan key:generate --env=staging to create a random one
    */

    'key' => '12345665432109876@#$%^&*12345678',

);

**Comment by snipe** [comment]
Missing a closing `'` in `'domain' => '127.0.0.1`

**Comment by rvasquez151** [comment]
Thank you.  Fixed the close... then go this error:

Symfony\Component\Debug\Exception\FatalErrorException thrown with message "syntax error, unexpected ''key'' (T_CONSTANT_ENCAPSED_STRING), expecting ')'"

Stacktrace:
#1 Symfony\Component\Debug\Exception\FatalErrorException in C:\wamp\www\snipe-it\app\config\production\app.php:56
#0 Illuminate\Exception\Handler:handleShutdown in <#unknown>:0

**Comment by snipe** [comment]
Please show me your updated config

**Comment by rvasquez151** [comment]
This one?
<?php

return array(

    /*
    |--------------------------------------------------------------------------
    | Application Debug Mode
    |--------------------------------------------------------------------------
    |
    | When your application is in debug mode, detailed error messages with
    | stack traces will be shown on every error that occurs within your
    | application. If disabled, a simple generic error page is shown.
    |
    */

    'debug' => true,

    /*
    |--------------------------------------------------------------------------
    | Application URL
    |--------------------------------------------------------------------------
    |
    | This URL is used by the console to properly generate URLs when using
    | the Artisan command line tool. You should set this to the root of
    | your application so that it is used when running Artisan tasks.
    |
    */

    'url' => 'https://127.0.0.1',


    /*
    |--------------------------------------------------------------------------
    | Organization Domain Name
    |--------------------------------------------------------------------------
    |
    | The domain name of the organization, used when generating email addresses
    | through the import tools.
    |
    */

    'domain' => '127.0.0.1'

    /*
    |--------------------------------------------------------------------------
    | Encryption Key
    |--------------------------------------------------------------------------
    |
    | This key is used by the Illuminate encrypter service and should be set
    | to a random, 32 character string, otherwise these encrypted strings
    | will not be safe. Please do this before deploying an application!
    |
    | Run a php artisan key:generate --env=staging to create a random one
    */

    'key' => '12345665432109876@#$%^&*12345678',

);

**Comment by snipe** [comment]
Missing a comma now. 

`'domain' => '127.0.0.1'`

should be 

`'domain' => '127.0.0.1',`

**Comment by snipe** [comment]
Please try to be careful when editing config files. If you're not, you can end up breaking the config files, which will prevent the app from loading. Edit the values exactly as you see them. If they are enclosed in single quotes followed by a comma, make your changes inside those quotes. PHP is a pretty forgiving language, but it's not going to be able to look past a parse error like that.

**Comment by rvasquez151** [comment]
Wow! Thank you. I have been working on this install for two days now. Finally got to the sign in page! one last question...  mind is blank.  What would be my sign in?

**Comment by snipe** [comment]
Whatever you provided as a login in the cli installer:
http://docs.snipeitapp.com/installation/command-line.html

**Comment by rvasquez151** [comment]
Got it! Thank you so much for your help.

**Comment by snipe** [comment]
No problem - good luck!

![ipk42t6](https://cloud.githubusercontent.com/assets/197404/11134102/2d3472c6-894f-11e5-96b6-8e88e47d49b8.gif)
