### ISSUE TITLE
i download v2 of snipe-it  but it don't have composer.phar

### ISSUE THREAD

**Issue by umerafridi** [snipe/snipe-it#1344]
i download V2 of Snipe from https://github.com/snipe/snipe-it/archive/master.zip this link but it don't have composer.phar  this than how i run these commands 
php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan migrate

**Comment by snipe** [comment]
Composer is not (and has never been) included. You have to download it yourself, per the docs; http://docs.snipeitapp.com/installation/composer.html
