### ISSUE TITLE
this issue is not listed in Common issue pl help to solve it

### ISSUE THREAD

**Issue by umerafridi** [snipe/snipe-it#1346]
Error in exception handler: The stream or file "/var/www/html/snipe-it-master/app/storage/logs/log-apache2handler-2015-11-12.txt" could not be opened: failed to open stream: Permission denied in /var/www/html/snipe-it-master/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:87

**Comment by umerafridi** [comment]
i all so change the permission of this app/storage  to 755 but it can't work

**Comment by snipe** [comment]
`/var/www/html/snipe-it-master/app/storage/logs/` (and all dirs within `/var/www/html/snipe-it-master/app/storage/`) needs to be writable, not just the parent directory, as per the docs.

**Comment by umerafridi** [comment]
i change all the permission but error is still there
Error in exception handler: The stream or file "/var/www/html/snipe-it-master/app/storage/logs/log-apache2handler-2015-11-15.txt" could not be opened: failed to open stream: Permission denied in /var/www/html/snipe-it-master/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:87

**Comment by dc53000** [comment]
Did you change the owner of the files to match the user that the web server is running as?

**Comment by asdarunasd1** [comment]
The owner was chaged to user in webserver which is apache...but still i am getting this error

Error in exception handler: The stream or file "/var/www/html/snipe-it-master/app/storage/logs/log-apache2handler-2015-11-15.txt" could not be opened: failed to open stream: Permission denied in /var/www/html/snipe-it-master/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:87

**Comment by saravananva** [comment]
Some Issue, I have installed Centos 7 and try to install Snipeit. But not able to access website.
Error :-
Error in exception handler: The stream or file "/var/www/html/snipeit/app/storage/logs/log-apache2handler-2016-05-05.txt" could not be opened: failed to open stream: Permission denied in /var/www/html/snipeit/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:87

Please share if you have any solution :)

**Comment by snipe** [comment]
@saravananva Please provide us with the information requested at the Getting Help documentation: http://docs.snipeitapp.com/getting-help.html

**Comment by saravananva** [comment]
Hi,

   Thanks for your support,

    Below the some details about installation i tried :-

Installer downloaded from this link :- http://docs.snipeitapp.com/installation/downloading.html
Server :- Centos 7.0 & Webservice - Apache
Database :- Mqsql
Installation Used install.sh Method
No Error available in Apache Log.

**Comment by wh0else** [comment]
If you are running CentOS 7, you probably have to change SElinux policy from enforcing to permissive
