### ISSUE TITLE
Extracting "import LDAP" call in order to automate

### ISSUE THREAD

**Issue by crguerrero1** [snipe/snipe-it#1348]
Hi,

Regarding the LDAP integration function that was introduced in https://github.com/snipe/snipe-it/issues/126.

I've very recently set up Snipe-IT for our IT dept. here, and so far it seems very promising.  I followed documentation for the LDAP integration since we have Active Directory here.  The only line in ldap.php I had to change for it to get data from our AD was this line:
    'authentication.filter.query' => "uid=",
Changed to:
    'authentication.filter.query' => "samaccountname=",

Once I made that change, "some" users got imported.  While investigating why only some users got imported, I tried  playing around with the search filter.  I have closely compared quite a few different users' AD profiles and am still unable to figure out why some users get imported with a certain search query, and some dont.

Examples of search queries I used:
'filter' => "&(cn=*)",    ##Default value --gave me some users
'filter' => "&(sn=*)",   ##Got more users... but still not all of them
'filter' => "&(objectclass=person)",   ##Again, got more users... but still not all of them
'filter' => "&(cn=*)(sn=*)",  ##This one seems to have imported the remainder of the missing users

N.B:  I tried the above 4 in order.  After the 4th attempt, I created a new test user (with required username, firstname, lastname attributes) and ran an import.  The "(cn=*)(sn=*)" filter did NOT fetch the new user.  I reverted to the default search query (cn=*) , re-synced, and there was the new user!

Very inconsistent.. I'm guessing this may be some wonkiness caused by the fact this was specifically tailored to be LDAP integration and not AD integration.(?)

I understand that the current LDAP integration is not designed to continuously sync user accounts.  However, surely there must be a way to extract the function/call that is being made to sync this, and have it scripted so I can automate it via cron --right?.

This would great to ensure new users are automatically added to Snipe-IT.  But on top of that, the bigger issue this would solve is I can automate separate imports with the multiple search queries so that I'm syncing ALL users and not just a subset.

If this is something that cannot be done as easily as I'm hoping, I can certainly close this out and I can re-open this as a Feature Request.

Best regards.

**Comment by ddreier** [comment]
Here's the query that I use:
```
&(objectcategory=person)(objectclass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2))
```
It gets all user accounts that are not disabled, and it works will in most situations AD-querying scenarios.

AFAIK you're correct in thinking that the import functionality shouldn't be that hard to implement. Well, the "doing the sync" part at least. You might have you figure out a way to swap queries around if you can't find one that gets all of your users in one go. I might take a swing at it in the next few days.

**Comment by crguerrero1** [comment]
Thanks for the query.  I tried it and it actually pulled in a few un-sync'd accounts.

I'll continue trying this out and will post any updates here.

Thanks!

**Comment by crguerrero1** [comment]
I played around with this some more today.. Admittedly, my biggest challenge here is my inexperience with PHP.

I tracked down the PHP functions that handle the LDAP sync to be in this file (my installation is under /var/snipe-it):
/var/snipe-it/app/controllers/admin/UsersController.php

I see and, mostly, understand the getLDAP and postLDAP functions in there.  In my mind, the end solution would be to run those PHP functions directly via cronjobs, so I began trying to run these functions via command line.

\#\# After looking up what 'extends' does in PHP, it made sense to include AdminController, so I tried:
$ php -r 'include "./controllers/AdminController.php"; UsersController::postLDAP();'

PHP Fatal error:  Class 'AuthorizedController' not found in /var/snipe-it/app/controllers/AdminController.php on line 4

\#\# Because of the above error, I included AuthorizedController and tried again.
$ php -r 'include "controllers/AuthorizedController.php"; include "controllers/AdminController.php"; UsersController::postLDAP();'

PHP Fatal error:  Class 'BaseController' not found in /var/snipe-it/app/controllers/AuthorizedController.php on line 4


I tried researching how to "include" entire directories (so i don't have to include each class individually), but haven't found that answer yet.  Anyway, after this point, I reluctantly tried again and included the BaseController.php file.  The output of that attempt complained "Class 'Controller' not found..."

I see two class definitions for "Controller" in these two files, so I'm unsure which is the correct one:
./vendor/doctrine/annotations/tests/Doctrine/Tests/Common/Annotations/Fixtures/Controller.php
./vendor/laravel/framework/src/Illuminate/Routing/Controller.php

I have a feeling I'm missing something with the way I'm trying to execute this PHP line.. I'll continue reading up on PHP.  Any guidance would be greatly appreciated!

Regards.

**Comment by ddreier** [comment]
So, Laravel (the PHP framework that Snipe-IT is built on) has a built in command-line task system called Artisan. I think that the right way to go about this is to add an Artisan task/command that does the same thing that clicking the button on the web page does.

I'm just not sure if it'll be best to copy and paste (then fix) the code into an Artisan command, duplicating the code, or if there's a way to call the Artisan command from the controller or vice-versa. @snipe will most likely know best here.

**Comment by crguerrero1** [comment]
Cool, thanks for the pointer.  I'll start looking into Laravel/Artisan and will report back any useful updates from my end.

**Comment by snipe** [comment]
Isn't all of this negated by this PR? https://github.com/snipe/snipe-it/pull/1298

**Comment by snipe** [comment]
Although I suppose if your users aren't logging in often (or at all), you'll still want them in the system, so that PR doesn't help that scenario.

**Comment by crguerrero1** [comment]
Hi snipe,

Thats a cool PR, glad someone is working on that as its definitely a useful feature.
Definitely for the early stages of rolling this out here, I know our helpdesk folks will be doing all the asset checking in/out on behalf of users, so yes, for this specific scenario we want users to be in the system already.

I anticipate down the road, users will be requesting things on their own.. But even then, I know there will be those users "unable"(unwilling) to use it so having all users in the system will always be a helpful feature on our end.

The PR you mentioned is definitely a very nice approach, and if we employ that, I think that would be good enough.  However, finding a way to autosync the accounts seems like the more complete approach, so I'd like to keep this ticket open if thats okay.

I haven't had much time to test this using Laravel/Artisan yet.. had to spend time familiarizing myself with the framework.  I hope to look into this more in the next few days.

Cheers!

**Comment by snipe** [comment]
The import calls themselves won't really work that way, since they return a view, which you don't want in an Artisan call. The logic would need to be pulled out of the Controller (which it should have been anyway) and moved into a model method.

**Comment by SynchronGmbH** [comment]
Hey there, 

is there any way to start the LDAP sync automatic?

Thanks for your reply! :)

**Comment by ddreier** [comment]
@SynchronGmbH No, that feature isn't currently available. It looks like it's planned for v3.1.

**Comment by riskinovitasari** [comment]
hi, then how about to call data (eg email) from ldap server to display into my system.  For example I have a db employee which stores name data, username and password. Then I also have ldap server that stores data name, username, password, position. Then when i login, i will be authenticated in db employee and ldap server to check my username exists or not. Then, after I successfully login, then I will be able to see the data name, email, and position taken from ldap server which is displayed into my system web. do you have any script references I might be able to use?

**Comment by snipe** [comment]
I don't know what you're asking, but also this thread has been closed for quite some time. Please create a new issue with clarification on what it is you're asking for.
