### ISSUE TITLE
Running composer as administrator 

### ISSUE THREAD

**Issue by peejaysantos** [snipe/snipe-it#1349]
Sorry if this question is kinda stupid. There is a note to never run composer as a super-user or Administrator. I believe our windows server have only an admin account setup. Will this be a big issue?

**Comment by ddreier** [comment]
Shouldn't be a problem.

That's in the docs as a general security best practice.

**Comment by snipe** [comment]
Well, not running a website as root is the security best practice. Not running composer as root is recommended because if you run composer as root but your webserver is running as someone less priv'ed, you'll run into a load of permission issues.
