### ISSUE TITLE
User access

### ISSUE THREAD

**Issue by peejaysantos** [snipe/snipe-it#1350]
I've just finished setting up this great application using xampp. It seems that admin and super user have the same privileges. I was looking for an admin who can change all settings and a super-user who can only perform limited actions such as addition, checking in and out items. I haven't found a ticket with regard to this so kindly point me to one if there's any. Thanks!

**Comment by snipe** [comment]
Super user will always have more access than admins. A few tickets have discussed this, and it's something on the roadmap.

#1331
#1146 
#1097
