### ISSUE TITLE
expected_checkin does not update to database on new build

### ISSUE THREAD

**Issue by blechdom** [snipe/snipe-it#1351]
Hi, 
I'm checking out assets and setting the expected checkin date. The checkin date shows up in the automatic email, but when I check the "assets_log" table, all of my expected_checkin values are NULL.

**Comment by snipe** [comment]
@blechdom Does it actually show in the table though? We've moved that to the assets table for database normalization and performance reasons.

**Comment by snipe** [comment]
@blechdom any updates?
