### ISSUE TITLE
now i sucessfull upgrade to v2 but i can't login with user which i create in previous version

### ISSUE THREAD

**Issue by umerafridi** [snipe/snipe-it#1352]
finally i got the login screen on browser now i want log in with same username and password which was i created in previous version i use old database for v2 also which i created in version 1

**Comment by umerafridi** [comment]
i need prompt reply on this pl

**Comment by mtucker6784** [comment]
This probably isn't an acceptable answer, but something to look at: Check the username column in your users table, verify that it's not null. When I was first playing with Snipe It, I managed to create a user but without populating the username column (weird; I know, I'm sure I did something just perfectly...)

**Comment by snipe** [comment]
@umerafridi can you not just do a password reset request?
