### ISSUE TITLE
Back up error

### ISSUE THREAD

**Issue by peejaysantos** [snipe/snipe-it#1354]
Hi, I would appreciate if anyone can help me with the error below whenever I try to perform a backup

ErrorException (E_WARNING)
HELP
opendir(app/storage/dumps/,app/storage/dumps/): The system cannot find the path specified. (code: 3)

I also tried doing a manual backup but still got an error:

C:\inetpub\wwwroot\snipe-it>php artisan snipeit:backup
←[0;31m
Database backup failed. 'mysqldump' is not recognized as an internal or external
 command,
operable program or batch file.

←[0m
Backup file created at C:\inetpub\wwwroot\snipe-it\app/storage/dumps/20151117735
58-backup.zip
Removing SQL dump at app/storage/dumps/2015111773558-db.sql

**Comment by snipe** [comment]
If you don't have mysqldump enabled, the backup can't work.

**Comment by snipe** [comment]
http://dev.mysql.com/doc/refman/5.5/en/mysqldump.html

**Comment by peejaysantos** [comment]
how about the "opendir(app/storage/dumps/,app/storage/dumps/): The system cannot find the path specified. (code: 3)" error?

**Comment by snipe** [comment]
See this thread for info on setting your path in the backup config. https://github.com/snipe/snipe-it/issues/1337
