### ISSUE TITLE
No assets shown in any list

### ISSUE THREAD

**Issue by Jaimer** [snipe/snipe-it#1360]
I just upgraded from 1.2.6 to 2.0, after this no assets, people, models, categories are shown in its proper lists but the data is still in the database and i can see the asset reports and recent activity properly.

I upgraded by replacing the files as the docummentation says and running the composer commands after that. I haven't seen any error message or something like that.

Attached a image showing the all assets list with debug option enabled.
![assets](https://cloud.githubusercontent.com/assets/447088/11256905/9802764e-8e1c-11e5-9484-f0c75a80a1a9.png)

**Comment by snipe** [comment]
Did you run migrations?

**Comment by snipe** [comment]
(Also, we need to see what's in the app error logs)

**Comment by Jaimer** [comment]
Yes i ran

php composer.phar install
php composer.phar dump-autoload
php artisan migrate

There is just one entry in the log from yesterday:

[2015-11-18 22:07:56] production.DEBUG: Authenticating user against database. [] []

**Comment by Jaimer** [comment]
I see there is a new release. Would it hurt if i update again.?

**Comment by Jaimer** [comment]
Ok just upgraded from 2.0.4 to 2.0.5 and all my assets came back. Haven't tested all yet but everything seems fine.
