### ISSUE TITLE
Add-On Request: IP management

### ISSUE THREAD

**Issue by rootAmeen** [snipe/snipe-it#1361]
Hey guys. Thank you for this awesome tool. 
I'm looking for a way that I can do IP management with. I believe IP addresses are key assets that must be integrated in the tool. example, I add a subnet/24, and it automatically detected the ips inside it. Then I can allocate the IPs to devices I have in my DC/Lab. 

Is there a way to do such implementation?

**Comment by vabue** [comment]
As I know right now there is no such functionality. But there is interesting discussion - #98.

**Comment by snipe** [comment]
@rootAmeen are you looking for something that will sit on your network and auto-detect things (like a network agent or something?) Or just the ability to store those fields? Custom fields are in the works, but we don't have any plans for a network agent at this time.

**Comment by rootAmeen** [comment]
Custom Fields is what I'm looking for, not a network agent. 
What would be really helpful is, as I mentioned, the ability to insert a subnet and the software automagically detects all IPs within it, then store additional data for each IP like which device is using it, and so on.

**Comment by snipe** [comment]
Closing this, since custom fields are coming very soon.
