### ISSUE TITLE
Feature Request: Display Modelname when Listing Devices for a Category

### ISSUE THREAD

**Issue by mettke** [snipe/snipe-it#1365]
In the Category View, there is a way to show all devices for one Category.
It would be nice to be able to see the Modelname on that List like it is on the Devices for a Model List.

**Comment by snipe** [comment]
I don't think I understand what you're asking. We already show the model name on that screen.
https://demo.snipeitapp.com/admin/settings/categories/1/view

<img width="1004" alt="screen shot 2015-11-20 at 9 12 54 am" src="https://cloud.githubusercontent.com/assets/197404/11306485/ebd47c2c-8f66-11e5-9678-17f32fb83595.png">

**Comment by mettke** [comment]
Invalid - Fixed with current Version
