### ISSUE TITLE
Feature Request: Add Link to Asset, Accessories and Consumables

### ISSUE THREAD

**Issue by mettke** [snipe/snipe-it#1366]
It would be nice to be able to add a Link for Asset, Accessories and Consumables. Those for example would be to link to the manufacture site for information about the device: http://www.dell.com/support/home/en/en/dedhs1/product-support/servicetag/<serial>

A Link may also be nice for Categories to see where resupplies can be bought.

**Comment by snipe** [comment]
Manufacturer links were added a ways back - not sure which version.
