### ISSUE TITLE
EOL shows incorrectly as 1yr in some tables

### ISSUE THREAD

**Issue by MarshP** [snipe/snipe-it#1367]
(v2.0-125), self-hosted

- Created a category 'Laptop' under which all asset models have 'EOL: 60 months'

- Open depreciation report or list of all assets: the EOL for most assets is incorrectly shown as 1 year from acquisition

- The exception are assets with status 'Broken - Not Fixable' which show correct EOL

**Comment by snipe** [comment]
Is this reproducible on the demo?

**Comment by MarshP** [comment]
No it's not. Either that version fixes it, else there's something weird in our deployment.

**Comment by snipe** [comment]
Do you have a value for the Warranty in those assets? An asset-level Warranty will override model-level EOL.

**Comment by MarshP** [comment]
That's it! Issue solved. (Will make a separate request to change that since it's a bit silly. Most stuff you buy has a 1 year warranty but a longer expected life.)

**Comment by kobie-chasehansen** [comment]
I would agree with @MarshP. I think this needs to be changed, the asset view already has an Expires date that would show the warranty expiration.

Know in my use case our warranty expires before our EOL goals are reached. Find myself doing the quick calculation manually to see if a user is eligible for a new computer.
