### ISSUE TITLE
Show location of the user in the asset page when asset is checked out on user

### ISSUE THREAD

**Issue by vabue** [snipe/snipe-it#1377]
When asset is checked out to some user, often there is a question what is the location of the user? In the 2.0.5 to determine it we have to go to the users profile. 

It would be much better to show users location in the asset page.

**Comment by vabue** [comment]
My mistake - it is in "Check Out To" block if a user has assigned location.

**Comment by snipe** [comment]
If the asset is checked out to a user with a location, the user's location is displayed in the location column - otherwise the asset's default location is displayed.
