### ISSUE TITLE
Error on last ckeckout data

### ISSUE THREAD

**Issue by abdullahalasham** [snipe/snipe-it#1379]
Dear Snipe,

whenever i checkout the asset to a user the last checkout data will either null or other old date however the correct date will appear on the activity report.

kindly advise

**Comment by snipe** [comment]
I don't understand the issue here. Where is the last checkout data bull or other old data? Where are you seeing that?

**Comment by abdullahalasham** [comment]
the issue was that the last checkout date  on assets table were not updated but the issue seem to disaperedd on the version   (v2.0.6-54)

thank you for your care
