### ISSUE TITLE
group Results Per Page issue

### ISSUE THREAD

**Issue by chenboshiun** [snipe/snipe-it#1380]
Hello

when i create a new group in Group Management, seems "Group was successfully created."

but redirect to Group Management page, i can't see new group , only show 14 group in Group Management page

but go to people page and edit user, we can assign a new group to user.

is group Results Per Page issue ? please help me this issue. thanks.

environment:
Snipe-IT version:v2.0.5-pre-52-gbbe0189
PHP Version:5.5.9-1ubuntu4.14
Laravel Version:4.2.17

**Comment by snipe** [comment]
Can you reproduce this on the demo?

**Comment by chenboshiun** [comment]
Demo:
1.Create Group and Save New Group : "Create Group Testing"
![1](https://cloud.githubusercontent.com/assets/5372796/11356190/35ec4ae2-9296-11e5-9d44-26cb1ed18b98.png)

2.show Group was successfully created. message. but i can't see new group below
![2](https://cloud.githubusercontent.com/assets/5372796/11356211/79a4e186-9296-11e5-841b-c776d13e855c.png)

3.go to people page and edit user, we can see new group and can't assign new group.
![3](https://cloud.githubusercontent.com/assets/5372796/11356220/99d3948e-9296-11e5-91b9-72ac286a5e04.png)

![4](https://cloud.githubusercontent.com/assets/5372796/11356250/eecf9e2e-9296-11e5-9fe9-3f6ba7d93af6.png)

so,i want to confirm whether is “group Results Per Page issue” ？

thanks.
