### ISSUE TITLE
All my accessories data gone. 

### ISSUE THREAD

**Issue by blhf** [snipe/snipe-it#1381]
I updated from 2.0.4 to the latest release but my accessories went missing. please help me fix this.

**Comment by snipe** [comment]
Can you tell me what's at /api/accessories/list?

**Comment by blhf** [comment]
example: api/accessories/list/external dvd/ no matching records found even though I have a 2 quantity

**Comment by snipe** [comment]
I'm asking you to go to that url in your system and tell me what it says on the screen.

**Comment by snipe** [comment]
(Make sure debugging is turned on)

**Comment by blhf** [comment]
sorry Im not yet familiar. heres the output: {"total":3,"rows":[{"name":"<a href=\"https:\/\/192.168.0.85:9090\/admin\/accessories\/3\/view\">HDMI<\/a>","category":"<a href=\"https:\/\/192.168.0.85:9090\/admin\/settings\/categories\/8\/view\">HDMI<\/a>","qty":1,"order_number":null,"purchase_date":null,"purchase_cost":null,"numRemaining":1,"actions":"<a href=\"https:\/\/192.168.0.85:9090\/admin\/accessories\/3\/checkout\" style=\"margin-right:5px;\" class=\"btn btn-info btn-sm\" >Checkout<\/a><a href=\"https:\/\/192.168.0.85:9090\/admin\/accessories\/3\/edit\" class=\"btn btn-warning btn-sm\" style=\"margin-right:5px;\"><i class=\"fa fa-pencil icon-white\"><\/i><\/a><a data-html=\"false\" class=\"btn delete-asset btn-danger btn-sm\" data-toggle=\"modal\" href=\"https:\/\/192.168.0.85:9090\/admin\/accessories\/3\/delete\" data-content=\"Are you sure you wish to delete this category?\" data-title=\"Delete HDMI?\" onClick=\"return false;\"><i class=\"fa fa-trash icon-white\"><\/i><\/a>"},{"name":"<a href=\"https:\/\/192.168.0.85:9090\/admin\/accessories\/2\/view\">CTI-002 (SAMSUNG-R6376GRZ302658) (External DVD)<\/a>","category":"<a href=\"https:\/\/192.168.0.85:9090\/admin\/settings\/categories\/11\/view\">External DVD<\/a>","qty":1,"order_number":null,"purchase_date":null,"purchase_cost":null,"numRemaining":1,"actions":"<a href=\"https:\/\/192.168.0.85:9090\/admin\/accessories\/2\/checkout\" style=\"margin-right:5px;\" class=\"btn btn-info btn-sm\" >Checkout<\/a><a href=\"https:\/\/192.168.0.85:9090\/admin\/accessories\/2\/edit\" class=\"btn btn-warning btn-sm\" style=\"margin-right:5px;\"><i class=\"fa fa-pencil icon-white\"><\/i><\/a><a data-html=\"false\" class=\"btn delete-asset btn-danger btn-sm\" data-toggle=\"modal\" href=\"https:\/\/192.168.0.85:9090\/admin\/accessories\/2\/delete\" data-content=\"Are you sure you wish to delete this category?\" data-title=\"Delete CTI-002 (SAMSUNG-R6376GRZ302658) (External DVD)?\" onClick=\"return false;\"><i class=\"fa fa-trash icon-white\"><\/i><\/a>"},{"name":"<a href=\"https:\/\/192.168.0.85:9090\/admin\/accessories\/1\/view\">CTI-001 (ASUS-C5D0AD065235) (External DVD)<\/a>","category":"<a href=\"https:\/\/192.168.0.85:9090\/admin\/settings\/categories\/11\/view\">External DVD<\/a>","qty":1,"order_number":null,"purchase_date":null,"purchase_cost":null,"numRemaining":1,"actions":"<a href=\"https:\/\/192.168.0.85:9090\/admin\/accessories\/1\/checkout\" style=\"margin-right:5px;\" class=\"btn btn-info btn-sm\" >Checkout<\/a><a href=\"https:\/\/192.168.0.85:9090\/admin\/accessories\/1\/edit\" class=\"btn btn-warning btn-sm\" style=\"margin-right:5px;\"><i class=\"fa fa-pencil icon-white\"><\/i><\/a><a data-html=\"false\" class=\"btn delete-asset btn-danger btn-sm\" data-toggle=\"modal\" href=\"https:\/\/192.168.0.85:9090\/admin\/accessories\/1\/delete\" data-content=\"Are you sure you wish to delete this category?\" data-title=\"Delete CTI-001 (ASUS-C5D0AD065235) (External DVD)?\" onClick=\"return false;\"><i class=\"fa fa-trash icon-white\"><\/i><\/a>"}]}

**Comment by snipe** [comment]
Are you getting any issues in your browser's console? It looks like the data is showing up correctly. Does anything change if you click on the sorting headers in that table view?

**Comment by blhf** [comment]
When I updated the data inside my accessories went missing. for example I have a laptop bag category. inside the category I have 1 asus bag and 1 hp bag. but after I updated the records of two bag is gone , I can only see the quantity of 2 laptop bags

**Comment by blhf** [comment]
browsers fine. I also tried it on other workstations locally.

**Comment by snipe** [comment]
Do you have access to the database? There's nothing in that update that would have destroyed data.

**Comment by blhf** [comment]
Yes I have. I can use PHPmyAdmin

**Comment by snipe** [comment]
So I'm clear, some accessories are missing, but some are showing up?

Can you confirm that they are still in the accessories table?

**Comment by blhf** [comment]
MySQL returned an empty result set (i.e. zero rows). (Query took 0.0000 seconds.) What would be the possible cause of this?

**Comment by snipe** [comment]
What is the query you're running?

**Comment by snipe** [comment]
(That table can't be empty, since your API request did return the HDMI data)

**Comment by blhf** [comment]
i didn't run any query in phpmyadmin it automatically displays top 10 data.

**Comment by snipe** [comment]
If you're clicking on the accessories table, that can't be empty, since we saw data in it when you hit the API.

Can you show me some screenshots of what you're seeing in the Snipe-IT app, please?

**Comment by blhf** [comment]
![snipe2](https://cloud.githubusercontent.com/assets/10716429/11358828/2e6579fe-92b1-11e5-921d-c3e1e52972b9.jpg)
![snipe](https://cloud.githubusercontent.com/assets/10716429/11358829/2e87b064-92b1-11e5-9376-53539c100831.jpg)

Please see this. thank you.

**Comment by blhf** [comment]
![image](https://cloud.githubusercontent.com/assets/10716429/11358854/77149b76-92b1-11e5-89dc-7829a82c9366.png)

how can I delete the logs that have errors?

**Comment by snipe** [comment]
Did you manually delete data from the database?

**Comment by snipe** [comment]
What do you see when you go to /api/accessories/11/view (with debugging turned on). I'm guessing some data was modified outside of the application, so you're getting errors because it's referencing things that don't exist anymore.

**Comment by blhf** [comment]
I tried to restore my backup. I didn't know that my colleague have done some encoding.

**Comment by blhf** [comment]
to delete the error I need to pinpoint those logs or should I just let it be?

**Comment by snipe** [comment]
Please answer my other question first.

**Comment by blhf** [comment]
I didn't delete anything from dbase. I just restored my backup.

**Comment by snipe** [comment]
I've asked you: What do you see when you go to /api/accessories/11/view (with debugging turned on). I

**Comment by blhf** [comment]
Oh no!

Server Error: 500 (Internal Server Error)

**Comment by snipe** [comment]
You need to turn debugging on.

**Comment by snipe** [comment]
http://docs.snipeitapp.com/getting-help.html

**Comment by blhf** [comment]
ok. what do you need to see ? 
the top returns Illuminate\Exception\Handler handleError
 return $data;
    }
 
	public function getDataView($accessoryID)
	{
		$accessory = Accessory::find($accessoryID);
        $accessory_users = $accessory->users;
        $count = $accessory_users->count();

**Comment by snipe** [comment]
Show me a screenshot

**Comment by blhf** [comment]
![image](https://cloud.githubusercontent.com/assets/10716429/11359125/2bf79c08-92b4-11e5-9dec-1f479931588f.png)

**Comment by snipe** [comment]
Someone must have deleted data, my guess would be users. You need to fix it by going through the asset logs table (and the accessories table) and remove anything that references users that no longer exist in your database.

**Comment by snipe** [comment]
http://docs.snipeitapp.com/installation/manually-editing-data.html

**Comment by blhf** [comment]
Thank you snipe. I'll do it now and report back.

**Comment by blhf** [comment]
I only have 5 asset logs. hmmm I can't delete because the date in the logs are just up to 20.

**Comment by snipe** [comment]
Why was this closed?

**Comment by terragon0852** [comment]
Hi Snipe,

I have the same issue. I was actually following this thread to maybe figure out what happened to my installation. It just happened out of nowhere. I have another admin user and I have no idea if he deleted anything that may have caused the issue. Here's a screenshot of my /api/accessories/list

![image](https://cloud.githubusercontent.com/assets/16467971/12025123/412b73a8-ad60-11e5-9198-a3edd337a9bb.png)

- I have full access to the database 
- I have sudo access to the server

Let me know if you want me to open a new issue instead of using this thread. Thanks in advance!

**Comment by terragon0852** [comment]
Adding these incase it's helpful for you:

![image](https://cloud.githubusercontent.com/assets/16467971/12025177/d5d9072c-ad60-11e5-9a5b-62d5326c1f25.png)

![image](https://cloud.githubusercontent.com/assets/16467971/12025193/fe97a9b6-ad60-11e5-8b1d-d21f2fe299c0.png)

**Comment by dmeltzer** [comment]
I think this is because the query is looking for assets in the accessory category instead of accessories in the accessory category.  Same issue with consumables--we talked about this on gitter the other day.

**Comment by terragon0852** [comment]
You were talking about this right?
![image](https://cloud.githubusercontent.com/assets/16467971/12025645/db9823b4-ad65-11e5-88c1-f137cef2125e.png)

snipe did mention that she'll be working on a fix. Was she able to? The issue kind of got lost in the conversation that followed. I know you were also trying some fix, any luck?

**Comment by dmeltzer** [comment]
I think things have slowed down for the holidays, There isn't a fix as of yet, but I suspect one will show up sometime soon.

**Comment by terragon0852** [comment]
That's all I need to know. Thanks for the update! Much appreciated.

**Comment by terragon0852** [comment]
Update:

I'm seriously confused now. After reading a thread that phones should be assets, I made some changes yesterday by converting the Phone category from "Accessory" to "Assets". After checking my installation today, all the assets (laptops, desktops, monitors, etc) are now gone; by gone I mean "No records found". What's left are only the phones that are now listed as assets. I tried changing them back to accessory but that didn't work. It's still showing up as assets when I click on "List All".
![screen shot 2015-12-29 at 3 10 21 pm](https://cloud.githubusercontent.com/assets/16467971/12043899/760c8bf0-ae3e-11e5-9a0e-f07f69d7a439.png)

**Comment by terragon0852** [comment]
I'm seriously confused now. After reading a thread that phones should be assets, I made some changes yesterday by converting the Phone category from "Accessory" to "Assets". After checking my installation today, all the assets (laptops, desktops, monitors, etc) are now gone; by gone I mean "No records found". What's left are only the phones that are now listed as assets. I tried changing them back to accessory but that didn't work. It's still showing up as assets when I click on "List All".

![screen shot 2015-12-29 at 3 10 21 pm](https://cloud.githubusercontent.com/assets/16467971/12043921/aedb1ee2-ae3e-11e5-8e09-f328c05e459d.png)

**Comment by snipe** [comment]
It doesn't really work that way. The categories aren't interchangeable, as assets only appear in the assets table, accessories only appear in the accessories table, etc. Just changing the category type doesn't actually create those entries in the appropriate table.

**Comment by terragon0852** [comment]
I second that. That's why I don't know what's happening with my setup anymore. I haven't really changed any config changes as soon as I had the site up so I don't know what's making these changes happen. Do you think downgrading to a lower stable version may make any difference? Oh here's a screenshot of the Asset categories.. Really, I'm just confused how this is happening. I might actually do a clean install if that would fix it for me.

![image](https://cloud.githubusercontent.com/assets/16467971/12044108/f7aa2a08-ae40-11e5-9576-371672b1ec39.png)

**Comment by snipe** [comment]
I think your data is messed up, so downgrading isn't going to help you. 

I'm also confused because you said "I made some changes yesterday by converting the Phone category from "Accessory" to "Assets"" - but in your listing it shows as an Accessory. Which is it?

**Comment by terragon0852** [comment]
Sorry I missed to mention that I changed it back to assets before posting today in a feeble attempt to maybe fix it. It didn't.

**Comment by snipe** [comment]
How many assets do you have?

When you go to /api/hardware/list, what do you see? (Make sure debugging is turned on)

**Comment by terragon0852** [comment]
I have "total":84,"rows"

**Comment by terragon0852** [comment]
I just thought I'd update my situation. I ended up reinstalling snipeIT with a new db, seeded it, transferred select table data (users, assets, models, categories) from the old db except accessories. It looks like some data in accessories table caused all these issues for me. There wasn't a lot of data in there so I don't mind just recreating them.
