### ISSUE TITLE
Default Currency Issue using Fresh Installation of v2.0.5-pre-57-g5ebb267

### ISSUE THREAD

**Issue by brianjking** [snipe/snipe-it#1383]
![screenshot11-23-1513 45](https://cloud.githubusercontent.com/assets/6786817/11347743/7ddee9f8-91e8-11e5-9b36-d84e64bd6679.png)

![screenshot11-23-1513 45-1](https://cloud.githubusercontent.com/assets/6786817/11347747/81849210-91e8-11e5-9359-56ea3ffa6836.png)

**Comment by brianjking** [comment]
Whenever I go back into the "Edit Settings" screen it displays TWD as default currency, despite saving it as USD and no errors shown.

**Comment by brianjking** [comment]
If I set it to Japanese Yen and click save it shows this being the selected currency on the settings display page, and persists as expected on the "Edit Settings" page. However, when I go to change it to USD once again it goes back to "TWD"

**Comment by snipe** [comment]
That's a known issue with the display, since the symbol for USD and TWD are the same.

**Comment by brianjking** [comment]
@snipe ok, glad to hear it's not something funky I did wrong.
