### ISSUE TITLE
IIS Rewrites

### ISSUE THREAD

**Issue by ACBobby** [snipe/snipe-it#1388]
I currently have Snipe in a subdomain (assets.domain.com) and I applied the rewrite rules provided from the .htaccess file, however, the server returns "You do not have permission to view this directory or page." when visiting the directory.

**Comment by snipe** [comment]
That looks like an IIS configuration issue. It's unrelated to Snipe-IT. 
http://forums.iis.net/t/1174425.aspx

**Comment by ACBobby** [comment]
What I just noticed is that the rewrites are looking for an index.php file, which doesn't exist in the top-level directory. It appears that is the problem, because IIS (by my default configuration) doesn't allow directory listing. So, that's why the error is showing.

I enabled directory browsing for the sub domain, and sure enough, the contents are there.

**Comment by snipe** [comment]
There is an index.php page in the public directory, which is what your DocumentRoot should be set to.

**Comment by ACBobby** [comment]
Ah yep, you are correct, I did not modify the DocumentRoot. I will do that now. Thanks!
