### ISSUE TITLE
Auto Asset Numbers - Fixed length

### ISSUE THREAD

**Issue by hobbit666** [snipe/snipe-it#1390]
Is there a way of getting the asset number to be a fixed size when using the Auto number option?

What I want is to use a Prefix WYN, but I want the number to be a predefined size of 5/6 numbers. 
e.g.
WYN000001
WYN000002
WYN000003
......
WYN000009
WYN000010
WYN000011
......
WYN001010

etc

At the moment if I use the prefix it coming out as WYN1 WYN2 WYN10 WYN11 etc.

**Comment by hobbit666** [comment]
Can I also add specifying a start number as I might start using Snipe-IT and entering the number manually

**Comment by vjandrea** [comment]
I need this feature as well, i will try to put it together as an optional setting

**Comment by SynchronGmbH** [comment]
hobbit666 where do you define the prefix ? 

Thanks in advance

**Comment by snipe** [comment]
@SynchronGmbH Admin > Settings 

<img width="620" alt="screen shot 2016-06-02 at 12 18 37 am" src="https://cloud.githubusercontent.com/assets/197404/15736888/9619b1be-2857-11e6-80e3-ee9a36c28d3b.png">

**Comment by SynchronGmbH** [comment]
Thanks, the field was disabled. Now it works !
