### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by vijaynageswaran** [snipe/snipe-it#1391]
Hi All,

I have done the basic configuration in the ubuntu server.For that i have followed this link http://docs.snipeitapp.com/installation/configuration.html.

And also pointed the snip-it-master package public folder as my document root and set the host name for my convenience.

I pulled the snipe-it package from github and pointed the public folder as my document root.When i enter the ip or hostname it will redirect to the public folder.but i can't see the snipe-it home page or How can i view the Snipe-IT page in my web browser.?

Please help me with this asap.

Thanks in advance.

**Comment by snipe** [comment]
@vijaynageswaran We need more information. Are there any errors? What are you seeing when you go to the hostname you specified? Is there anything in the error logs? We can't know what you missed in the setup if we don't know what you're seeing.

**Comment by vijaynageswaran** [comment]
Thanks for your quick reply.I didn't get any error message.When enter the hostname in browser , i can see only the blank white page.I think it will routed to my document root which i pointed in configuration file.


![assetcom](https://cloud.githubusercontent.com/assets/15977715/11394826/79a543e0-938d-11e5-9910-eb0bbeee0102.PNG)


I have attache the screenshot for your reference.

**Comment by snipe** [comment]
What about app/server error logs? Is Apache even running?

**Comment by vijaynageswaran** [comment]
Yes apache is running and i didn't create the error log.The configuration what i done is correct?

**Comment by snipe** [comment]
Without seeing your configuration, I couldn't possibly know whether it's correct or not. Your web server should have logs. We need to know what's in them. 

How are you verifying that the server is running?

This is not a Snipe-IT issue, this is a server configuration issue.

**Comment by vijaynageswaran** [comment]
Okay.I do understand.I am not telling this is Snipe-IT issue.Okay.I will create a log file and let you know.Thanks.

**Comment by vijaynageswaran** [comment]
Hi Snipe,

Can you tell me how to create the error log in my snipe-it server?

If you share the details , it would be great.

Server Details
OS : Ubuntu
Webserver : Apache
Document Root : /var/www/snipe-it-master/public

**Comment by vijaynageswaran** [comment]
Hi Snipe,
I have created instance in Amazon and done the basic things what is mentioned in snipeitapp.com

The URL is 
http://docs.snipeitapp.com/installation/server/linux-osx.html

I pointed the document root as snipe-it-master/public folder in conf file.When i entered the IP address in my browser , it is showing server error 500.But it should show my contents what i have on that directory.

Can you help me with that asap?

Thanks in advance.

**Comment by snipe** [comment]
Please enable debugging so we can see what the error is.

**Comment by vijaynageswaran** [comment]
I enabled the debugging mode in app.php file.Still i am getting the same error.

**Comment by snipe** [comment]
Can you show me a screenshot of your error?

**Comment by vijaynageswaran** [comment]
![error_snipeit](https://cloud.githubusercontent.com/assets/15977715/11497261/ca129c56-983d-11e5-9ee6-35bccb2ba12e.PNG)

**Comment by snipe** [comment]
What is in your server logs? This is an apache configuration error, not an error with Snipe-IT.

**Comment by vijaynageswaran** [comment]
I have mentioned the apache error logs here.Check with it and let me know.

[Tue Dec 01 08:03:45.812234 2015] [:error] [pid 1891] [client 111.93.118.228:54013] PHP Warning:  require(/var/www/html/snipeit/snipe-it-master/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/$
[Tue Dec 01 08:03:45.813937 2015] [:error] [pid 1891] [client 111.93.118.228:54013] PHP Fatal error:  require(): Failed opening required '/var/www/html/snipeit/snipe-it-master/bootstrap/../vendor/autoload.php' (include_path='.:/usr/shar$
[Tue Dec 01 08:53:32.127563 2015] [:error] [pid 1889] [client 111.93.118.228:58723] PHP Warning:  require(/var/www/html/snipeit/snipe-it-master/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/$
[Tue Dec 01 08:53:32.127595 2015] [:error] [pid 1889] [client 111.93.118.228:58723] PHP Fatal error:  require(): Failed opening required '/var/www/html/snipeit/snipe-it-master/bootstrap/../vendor/autoload.php' (include_path='.:/usr/shar$
[Tue Dec 01 09:25:31.093126 2015] [:error] [pid 1893] [client 111.93.118.228:53490] PHP Warning:  require(/var/www/html/snipeit/snipe-it-master/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/$
[Tue Dec 01 09:25:31.093157 2015] [:error] [pid 1893] [client 111.93.118.228:53490] PHP Fatal error:  require(): Failed opening required '/var/www/html/snipeit/snipe-it-master/bootstrap/../vendor/autoload.php' (include_path='.:/usr/shar$

**Comment by snipe** [comment]
http://docs.snipeitapp.com/common-issues.html#php-warning-requirevarwwwhtmlsnipeitbootstrapvendorautoloadphp-failed-to-open-stream-no-such-file-or-directory

**Comment by vijaynageswaran** [comment]
But one more thing , i forget to mentioned if i open the IP address of my server with /phpinfo.php , it will work.When i entered the IP address alone it is getting the server error.

**Comment by snipe** [comment]
Yes, because you didn't run the composer commands, per the link above.
