### ISSUE TITLE
LDAP auth Exception

### ISSUE THREAD

**Issue by MicaelRodrigues** [snipe/snipe-it#1392]
Hi Snipe,
Since this commit, my LDAP auth stopped working. 
https://github.com/snipe/snipe-it/commit/e031239cf02f15649f5dd5b4cba80f7c0caaf075
 
Illuminate \ Encryption \ DecryptException
Invalid data. 

Do I have to change anything in my ldap config file in order to this to Work? The ldap server password was in plain text.

Thanks,

Micael

**Comment by snipe** [comment]
As of that commit, the system no longer uses the LDAP config file. Check your settings page and add them there

**Comment by MicaelRodrigues** [comment]
Solved, Thanks! :)

**Comment by snipe** [comment]
No problem - sorry we haven't had a chance to update the docs on that yet.
