### ISSUE TITLE
[PDOException]   could not find driver

### ISSUE THREAD

**Issue by spOmes** [snipe/snipe-it#1393]
I get this error when trying to run "php artisan app:install --env=production"

[PDOException]   could not find driver After step 2

**Comment by snipe** [comment]
You don't have the php-mysql or php-pdo libraries installed, which is part of the system requirements.

http://docs.snipeitapp.com/requirements.html
http://stackoverflow.com/questions/2852748/pdoexception-could-not-find-driver

**Comment by spOmes** [comment]
Thank you

**Comment by snipe** [comment]
NP :)

**Comment by AL4AL** [comment]
In docker use:
`RUN docker-php-ext-install -j$(nproc) pdo_mysql
`
