### ISSUE TITLE
Getting The requested URL /auth/signin was not found on this server.

### ISSUE THREAD

**Issue by spOmes** [snipe/snipe-it#1394]
I have added jargon into my htaccess file in public seen on another issue and it blows up

**Comment by snipe** [comment]
What's your document root set to?

**Comment by spOmes** [comment]
I have set it to the public folder but its in a sub dir 

/var/www/html/snipeit/public

**Comment by spOmes** [comment]
<VirtualHost *:80>

    <Directory /var/www/html/snipeit/public>

        Allow From All

        AllowOverride All

        Options +Indexes

    </Directory>


    DocumentRoot /var/www/html/snipeit/public

    ServerName AssetDesk

    # Other directives here

</VirtualHost>

**Comment by spOmes** [comment]
a2enmod rewrite

Enabling module rewrite fixed, whould have googled first.

Cheers
