### ISSUE TITLE
Create Accessory - says "Category created successfully" and doesn't add stuff..

### ISSUE THREAD

**Issue by tottere** [snipe/snipe-it#1395]
What may I have done so wrong?...

Version:
Snipe-IT version	v2.0.5-pre-57-g5ebb267
PHP Version	5.4.45-0+deb7u2
Laravel Version	4.2.17

..on Debian Linux.

Fresh install and I think I followed the guide pretty well.. was able to delete stuff and add categories and people and stuff, but not accessories.

Image:
![accessories](https://cloud.githubusercontent.com/assets/16019433/11401538/497b23e6-9393-11e5-9d4c-83e5b3337478.png)

**Comment by snipe** [comment]
What ID number is SFP Assets?

**Comment by tottere** [comment]
ID number for SFP Asset is 16.

**Comment by tottere** [comment]
I may also mention, running the "Accessory Report" does list the items I need to find.

**Comment by tottere** [comment]
And to make it clear, it happens on every category/asset when trying to add accessory..




On Wed, Nov 25, 2015 at 7:48 AM -0800, "snipe" <notifications@github.com> wrote:





What ID number is SFP Assets?

---

**Comment by snipe** [comment]
What do you see at /api/accessories/16/view?

**Comment by tottere** [comment]
I get a 500 error there.

...and from storage/logs/cgi: (if this matters)

[2015-11-25 21:12:15] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /home/snipe/public_html/app/controllers/admin/AccessoriesController.php:550
Stack trace:
#0 /home/snipe/public_html/app/controllers/admin/AccessoriesController.php(550): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/home/snipe/pub...', 550, Array)
#1 [internal function]: Controllers\Admin\AccessoriesController->getDataView('16')
#2 /home/snipe/public_html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#3 /home/snipe/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('getDataView', Array)
#4 /home/snipe/public_html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\AccessoriesController), Object(Illuminate\Routing\Route), 'getDataView')
#5 /home/snipe/public_html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\\Adm...', 'getDataView')

**Comment by snipe** [comment]
Yes, that error report is what I was asking for (and why we ask you to turn on debugging when reporting bugs). Did you pull this from a release, or from master/develop? Also, can you tell me what's on lines 540 - 560 in `app/controllers\admin\AccessoriesController.php` on your install?

**Comment by tottere** [comment]
Hi, this is from the latest release button, downloaded it yesterday. But think its more than 20 hours ago (Which is later than that), took the version numbers and pasted them at the first post.


Here is the code from 541 (540 was just an } ending ) to 562:


        $data = array('total'=>$accessCount, 'rows'=>$rows);

        return $data;
    }

	public function getDataView($accessoryID)
	{
		$accessory = Accessory::find($accessoryID);
        $accessory_users = $accessory->users;
        $count = $accessory_users->count();

        $rows = array();

        foreach ($accessory_users as $user) {
            $actions = '<a href="'.route('checkin/accessory', $user->pivot->id).'" class="btn-flat info">Checkin</a>';

            $rows[] = array(
                'name'          => link_to('/admin/users/'.$user->id.'/view', $user->fullName()),
                'actions'       => $actions
                );
        }

**Comment by tottere** [comment]
Updated to 2.0.6 - can create accessories but they still dont show up. (except when running a report, then they all show up)

[2015-12-02 09:34:04] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /home/snipe/public_html/app/controllers/admin/AccessoriesController.php:593

593 =                 'category'      => link_to('admin/settings/categories/'.$accessory->category->id.'/view', $accessory->category->name),



587-603:

       foreach ($accessories as $accessory) {
            $actions = '<nobr><a href="'.route('checkout/accessory', $accessory->id).'" style="margin-right:5px;" class="btn btn-info btn-sm" '.(($accessory->numRemaining() > 0 ) ? '' : ' disabled').'>'.Lang::get('general.checkout').'</a><a href="'.route('update/accessory', $accessory->id).'" class="btn btn-warning btn-sm" style="margin-right:5px;"><i class="fa fa-pencil icon-white"></i></a><a data-html="false" class="btn delete-asset btn-danger btn-sm" data-toggle="modal" href="'.route('delete/accessory', $accessory->id).'" data-content="'.Lang::get('admin/accessories/message.delete.confirm').'" data-title="'.Lang::get('general.delete').' '.htmlspecialchars($accessory->name).'?" onClick="return false;"><i class="fa fa-trash icon-white"></i></a></nobr>';
            $company = $accessory->company;

            $rows[] = array(
                'name'          => link_to('admin/accessories/'.$accessory->id.'/view', $accessory->name),
                'category'      => link_to('admin/settings/categories/'.$accessory->category->id.'/view', $accessory->category->name),
                'qty'           => $accessory->qty,
                'order_number'  => $accessory->order_number,
                'location'      => ($accessory->location) ? $accessory->location->name: '',
                'purchase_date' => $accessory->purchase_date,
                'purchase_cost' => $accessory->purchase_cost,
                'numRemaining'  => $accessory->numRemaining(),
                'actions'       => $actions,
                'companyName'   => is_null($company) ? '' : e($company->name)
            );
        }

**Comment by tottere** [comment]
note: if I search for the accessories in the searchbar at the accessories page, I can find them, attaching pictures:


![snipe1](https://cloud.githubusercontent.com/assets/16019433/11527746/04cf055a-98e3-11e5-8dc6-710e881a597a.png)

![snipe2](https://cloud.githubusercontent.com/assets/16019433/11527749/0c6a3dd4-98e3-11e5-810c-7802ee936ac2.png)

![snipe3](https://cloud.githubusercontent.com/assets/16019433/11527752/1083ff18-98e3-11e5-809f-f4fff2695895.png)

**Comment by snipe** [comment]
That looks like bad data to me, as if an accessory somehow doesn't have a valid category assigned.

**Comment by snipe** [comment]
(Also, try clearing your cookies and reloading that page)

**Comment by snipe** [comment]
Can I see your accessories data? Do you have any accessories with a weird category_id, like null or 0?

**Comment by tottere** [comment]
Hi, clearing cookies didn't help, adding a company (was it there in 2.0.5? now 2.0.6) and adding new accessories after that - did show 8 of the 13 accessories I had in the accessories tab. Then I dropped all the data in the accessories database and created a new accessory. 

This new item showed up at once, but didn't show up under the category it was assigned too (just shows that the category actually has 1 item assigned to it on the summary page)

![accessories](https://cloud.githubusercontent.com/assets/16019433/11555800/21426572-99a3-11e5-96eb-97791f53bbf0.png)
![category](https://cloud.githubusercontent.com/assets/16019433/11555801/22c47566-99a3-11e5-9311-c9b362429f90.png)

**Comment by snipe** [comment]
I'm not really following where you're talking about for these examples. Can you show me screenshots of the updated screens, and tell me if your browser is reporting any errors in the browser console?

**Comment by tottere** [comment]
Ok, maybe this gives a better view:
![scr1](https://cloud.githubusercontent.com/assets/16019433/11561180/dd738614-99c5-11e5-98f1-0728576e8059.png)
![scr2](https://cloud.githubusercontent.com/assets/16019433/11561182/df24eeb2-99c5-11e5-9272-d74b460d40dd.png)
![scr3](https://cloud.githubusercontent.com/assets/16019433/11561186/e17d236e-99c5-11e5-8ffd-6c2a0a7c1fcb.png)
