### ISSUE TITLE
Support for freetds db driver

### ISSUE THREAD

**Issue by trondvh** [snipe/snipe-it#1396]
For those of us with linux webservers and MSSQL DB servers it would be nice with support for the freetds db driver.

**Comment by snipe** [comment]
I believe some of our migrations make it so that Snipe-IT doesn't install properly on non-MariaDB/MySQL databases. That's why MySQL/MariaDB are part of the system requirements.

**Comment by trondvh** [comment]
Ok. Just noticed config for the sqlsrv driver in database.php, so i hoped there was an undocumented support for mssql.

**Comment by snipe** [comment]
We used to support more databases, but some of the funky migrations we've had to go through weren't easily portable to non-mysql-ish databases. Eventually we hope to fix those, but (for example) we have some alter table statements, etc that don't exist in other RDBs

**Comment by trondvh** [comment]
Ah, then i see. Thanks for the info.
