### ISSUE TITLE
openshift snipeit

### ISSUE THREAD

**Issue by ejdekruijf** [snipe/snipe-it#1401]
Hi,

I am trying to host my snipeit on openshift but now he is giving me the error:

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 130968 bytes) in /var/lib/openshift/5656c56c0c1e66c3ed00008c/app-root/runtime/repo/bootstrap/autoload.php on line 2

Has anyone ever tried getting it to work on openshift?

**Comment by brianjking** [comment]
@ejdekruijf Openshift Online or what? Just looks like your PHP is running out of memory and can be addressed in your ````php.ini```` file.

**Comment by snipe** [comment]
@brianjking is correct. You're simply running out of memory, and you can adjust that with your php.ini file.

**Comment by brianjking** [comment]
If you're using a free gear on openshift-online you may run into issues due to the memory limit on the free plan, however, this is specifically something you can address based on your php.ini for now, good luck!
