### ISSUE TITLE
change request - allow EOL to be longer than warranty end

### ISSUE THREAD

**Issue by MarshP** [snipe/snipe-it#1402]
Current behaviour (v2.0-125) is that if warranty ends before EOL value, the warranty expiry is shown as EOL in tables such as 'List All Assets' and reports such as 'Depreciation Report'.

Usually a warranty (typical 12 months) expires before expected EOL (typical 36 or 60 months, default 60 months in v2.0-125).

Request - show an unchanged value for EOL in all tables and reports, based on purchase date and EOL calculation from the asset model. Ignore warranty in this calculation.

**Comment by kobie-chasehansen** [comment]
Would like this option was as well. I use this number to determine if a user is eligible for a new laptop. Before I realized this value was the warranty date I authorized a laptop replacement for a laptop that still had a year left in our EOL goals.

**Comment by kobie-chasehansen** [comment]
thanks

**Comment by MarshP** [comment]
Thank you so much!
