### ISSUE TITLE
How come version is not changing?

### ISSUE THREAD

**Issue by blhf** [snipe/snipe-it#1405]
![image](https://cloud.githubusercontent.com/assets/10716429/11436063/12698084-951c-11e5-99d4-b0b9df41bef0.png)

I updated from v2.0.5-pre to v2.0.5 stable then to v2.0.6 but until I can see is v2.0.5pre. how to fix did I did somthig wrong during update?

**Comment by zmorrow** [comment]
I also updated and mine still says 2.05-pre instead of 2.0.6.

**Comment by zmorrow** [comment]
If you go in to admin-settings and look under System Information, this may explain it better:


Snipe-IT version	v2.0.5-pre-191-g948be5c
PHP Version	5.6.0
Laravel Version	4.2.17

**Comment by kobie-chasehansen** [comment]
think your deployment is okay. I dont think the  version was bumped before the tag was made.

![image](https://cloud.githubusercontent.com/assets/10247644/11448168/ce88aade-9520-11e5-9460-30abb41392f8.png)

**Comment by zmorrow** [comment]
Yea, I just went in and changed it manually.

**Comment by snipe** [comment]
It's a bug in our versioning script. We're working on a fix.

**Comment by slaviknowsbest** [comment]
> Yea, I just went in and changed it manually.

How did you change it zmorrow?
