### ISSUE TITLE
Unable to Delete

### ISSUE THREAD

**Issue by christopherbox** [snipe/snipe-it#1406]
Using Build - v2.0.5-pre-191-g948be5c

I am unable to delete any assets found in Asset Manufacturers or Suppliers. When I try to do it, it will error out and redirect to locations with the following error below.

 Error: admin/locations/message.not_found

I have not found any log that relates to the error in /app/storage/logs that can assist with this issue.

**Comment by snipe** [comment]
Can you reproduce this on the demo? If so, please provide us with the steps to reproduce on our end.
