### ISSUE TITLE
Dependencies not able to install. Failed to load

### ISSUE THREAD

**Issue by hemantdhonge** [snipe/snipe-it#1409]
Loading composer repositories with package information
Installing dependencies
  - Installing dinesh/barcode (4.0.x-dev 5655ece)
    Cloning 5655ece77d2d1c4438c8d940350d5d288717de27
    Failed to download dinesh/barcode from source: Failed to clone git@github.com:dineshrabara/barcode.git via git, https, ssh protocols, aborting.

- git://github.com/dineshrabara/barcode.git
  fatal: remote error:
    Repository not found.

- https://github.com/dineshrabara/barcode.git
  remote: Invalid username or password.
  fatal: Authentication failed for 'https://github.com/dineshrabara/barcode.git/'

- git@github.com:dineshrabara/barcode.git
  Permission denied (publickey).
  fatal: Could not read from remote repository.

  Please make sure you have the correct access rights
  and the repository exists.

    Now trying to download from dist
  - Installing dinesh/barcode (4.0.x-dev 5655ece)
    Downloading: Connecting...

  [Composer\Downloader\TransportException]
  The "https://api.github.com/repos/dineshrabara/barcode/zipball/5655ece77d2d1c4438c8d940350d5d288717de27" fi
  le could not be downloaded (HTTP/1.1 404 Not Found)

**Comment by hemantdhonge** [comment]
git://github.com/dineshrabara/barcode.git is this repository removed ???

**Comment by snipe** [comment]
We haven't used that library in quite some time. Is this an upgrade? Try running `composer clear-cache`. We haven't used that barcode library in months (because it was taken down via DCMA request), and it hasn't been in our composer dependencies since then.

**Comment by hemantdhonge** [comment]
Thanks I download latest version and issue resolved but I am facing another issue when I install it on centos7 of snipe-it 2.0.6.Mail is not sending giving permission issue but I disable the firewall and I can able to telnet my test  mail server ; even I configure outlook on my server and through outlook its work fine but through PHP it gives 
[2015-11-30 05:31:21] production.ERROR: exception 'Swift_TransportException' with message 'Connection could not be established with host 192.168.2.2 [Permission denied #13]' in /var/www/html/testams/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:269
Stack trace:
#0 /var/www/html/testams/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(62): Swift_Transport_StreamBuffer->_establishSocketConnection()
#1 /var/www/html/testams/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(113): Swift_Transport_StreamBuffer->initialize(Array)
#2 /var/www/html/testams/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#3 /var/www/html/testams/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(329): Swift_Mailer->send(Object(Swift_Message), Array)
#4 /var/www/html/testams/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(151): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#5 /var/www/html/testams/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(214): Illuminate\Mail\Mailer->send('emails.forgot-p...', Array, Object(Closure))
#6 /var/www/html/testams/app/controllers/AuthController.php(306): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#7 /var/www/html/testams/app/controllers/AuthController.php(306): Illuminate\Support\Facades\Mail::send('emails.forgot-p...', Array, Object(Closure))
#8 [internal function]: AuthController->postForgotPassword()
#9 /var/www/html/testams/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#10 /var/www/html/testams/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postForgotPassw...', Array)
#11 /var/www/html/testams/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(AuthController), Object(Illuminate\Routing\Route), 'postForgotPassw...')
#12 /var/www/html/testams/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'AuthController', 'postForgotPassw...')
#13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#14 /var/www/html/testams/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#15 /var/www/html/testams/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#16 /var/www/html/testams/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#17 /var/www/html/testams/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#18 /var/www/html/testams/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#19 /var/www/html/testams/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/html/testams/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#21 /var/www/html/testams/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#22 /var/www/html/testams/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#23 /var/www/html/testams/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/html/testams/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#25 /var/www/html/testams/public/index.php(49): Illuminate\Foundation\Application->run()
#26 {main} [] []

**Comment by hemantdhonge** [comment]
My mail.php is as ;

<?php

return array(

    /*
    |--------------------------------------------------------------------------
    | Mail Driver
    |--------------------------------------------------------------------------
    |
    | Laravel supports both SMTP and PHP's "mail" function as drivers for the
    | sending of e-mail. You may specify which one you're using throughout
    | your application here. By default, Laravel is setup for SMTP mail.
    |
    | Supported: "smtp", "mail", "sendmail"
    |
    */

    'driver' => 'smtp',

    /*
    |--------------------------------------------------------------------------
    | SMTP Host Address
    |--------------------------------------------------------------------------
    |
    | Here you may provide the host address of the SMTP server used by your
    | applications. A default option is provided that is compatible with
    | the Postmark mail service, which will provide reliable delivery.
    |
    */

    'host' => '192.168.2.2',

    /*
    |--------------------------------------------------------------------------
    | SMTP Host Port
    |--------------------------------------------------------------------------
    |
    | This is the SMTP port used by your application to delivery e-mails to
    | users of your application. Like the host we have set this value to
    | stay compatible with the Postmark e-mail application by default.
    |
    */

    'port' => 1125,

    /*
    |--------------------------------------------------------------------------
    | Global "From" Address
    |--------------------------------------------------------------------------
    |
    | You may wish for all e-mails sent by your application to be sent from
    | the same address. Here, you may specify a name and address that is
    | used globally for all e-mails that are sent by your application.
    |
    */

    'from' => array('address' => 'test1@mailtest.com', 'name' => 'hemantdhonge'),

    /*
    |--------------------------------------------------------------------------
    | E-Mail Encryption Protocol
    |--------------------------------------------------------------------------
    |
    | Here you may specify the encryption protocol that should be used when
    | the application send e-mail messages. A sensible default using the
    | transport layer security protocol should provide great security.
    |
    */

    'encryption' => null,

    /*
    |--------------------------------------------------------------------------
    | SMTP Server Username
    |--------------------------------------------------------------------------
    |
    | If your SMTP server requires a username for authentication, you should
    | set it here. This will get used to authenticate with your server on
    | connection. You may also set the "password" value below this one.
    |
    */

    'username' => 'test2',

    /*
    |--------------------------------------------------------------------------
    | SMTP Server Password
    |--------------------------------------------------------------------------
    |
    | Here you may set the password required by your SMTP server to send out
    | messages from your application. This will be given to the server on
    | connection so that the application will be able to send messages.
    |
    */

    'password' => 'test2',

    /*
    |--------------------------------------------------------------------------
    | Sendmail System Path
    |--------------------------------------------------------------------------
    |
    | When using the "sendmail" driver to send e-mails, we will need to know
    | the path to where Sendmail lives on this server. A default path has
    | been provided here, which will work well on most of your systems.
    |
    */

    'sendmail' => '/usr/sbin/sendmail -bs',

    /*
    |--------------------------------------------------------------------------
    | Mail "Pretend"
    |--------------------------------------------------------------------------
    |
    | When this option is enabled, e-mail will not actually be sent over the
    | web and will instead be written to your application's logs files so
    | you may inspect the message. This is great for local development.
    |
    */

    'pretend' => false,

);

**Comment by snipe** [comment]
This is an issue with your mail server configuration. This thread on StackOverflow might help:
http://stackoverflow.com/questions/9973449/sending-email-with-swift-mailer-gmail-and-php-permission-denied-error

Check your port numbers, and check whether you have SELinux enabled.
