### ISSUE TITLE
Bug: General error: 1005 Can't create table 'snipeit.#sql-3626_1c6' (errno: 150)

### ISSUE THREAD

**Issue by rootAmeen** [snipe/snipe-it#1411]
Hello! I'm working on a new installation of the app using the installation script, exactly like my older installations. However, after I fill up my user info, I get the following error: 

------------------------------------

  Step: 2

    Preparing your Application

-------------------------------------

Application key [nemnc7T2cieGvBoVUhSfnsSQGCkW2TmS] set successfully.
Migration table created successfully.
Migrated: 2012_12_06_225921_migration_cartalyst_sentry_install_users
Migrated: 2012_12_06_225929_migration_cartalyst_sentry_install_groups
Migrated: 2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot
Migrated: 2012_12_06_225988_migration_cartalyst_sentry_install_throttle

  [Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1005 Can't create table 'snipeit.#sql-3626_1c6' (errno: 150) (SQL: alter table `users` add constraint users_company
  _id_foreign foreign key (`company_id`) references `companies` (`id`))

  [PDOException]
  SQLSTATE[HY000]: General error: 1005 Can't create table 'snipeit.#sql-3626_1c6' (errno: 150)

Thanks in advance!

**Comment by snipe** [comment]
I'm not sure why you'd be getting that error there, though. We don't try to add any company_id stuff until much later in the migrations. Is this the full error, or are there more "Migrated" entries you didn't include.

**Comment by boreaslaw** [comment]
I've got the same problem when upgrading from version 2.0.3 to 2.0.6. 
Checked around some forums and they said it could be due to duplicated FK name / different FK type. 
However, it has been checked that the system doesn't hit into these 2 cases. 
It would be appreciated if you could provide us some hints. 
Thanks.

**Comment by snipe** [comment]
If I had any hints, I'd be happy to share them. I'm honestly not sure what's happening here.

**Comment by snipe** [comment]
Can you pull from master and see if this is still happening? I've disabled the foreign key checks

**Comment by boreaslaw** [comment]
After searching the net further, I found the reason. 
It's because users table uses `InnoDB` engine, while companies table uses `MyISAM`. 
After runninf
```sql
alter table companies engine = InnoDB;
```
Migration could be completed. 
Hence you may remove the migration and keep the FK relationship. 

Thanks for your active support!

**Comment by snipe** [comment]
Thanks for the research on this, @boreaslaw! What's curious is why those tables would be created differently. All of my tables are InnoDB, and we don't specify to use MyISAM anywhere. InnoDB has been the default for MySQL/MariaDB for quite some time. The users table migration *does* specify InnoDB, and we don't specify an engine in the other tables, but unless this is an old version of MySQL, it shouldn't be defaulting to MyISAM. :-/

**Comment by snipe** [comment]
I've updated the docs with this solution. Thanks again for the legwork here, @boreaslaw. I think we took for granted that MySQL's default engine would be InnoDB, so we didn't specify table types. I've gone back and modified the migrations to specify InnoDB to prevent this issue moving forward, and have updated the docs with this solution. 

http://docs.snipeitapp.com/common-issues.html#during-install-or-running-migrations---sqlstatehy000-general-error-1005-cant-create-table-snipeitsql-3626_1c6-errno-150

**Comment by rootAmeen** [comment]
I tried again using the installation script (which should be pulling from master right now), and still I got the same issue. 

By the way: I noticed that database doesn't get created automatically through the script, even though it asks for a pass and root pass. If it didnt exist before running the script I get:

 [PDOException]
  SQLSTATE[HY000] [1045] Access denied for user 'snipeit'@'localhost' (using password: YES)

So i proceeded and created user and pass as filled in with the script, and I got the error:

 [Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1005 Can't create table 'snipeit.#sql-3626_1fa' (errno: 150) (SQL: alter table `users` add constraint users_company
  _id_foreign foreign key (`company_id`) references `companies` (`id`))






  [PDOException]
  SQLSTATE[HY000]: General error: 1005 Can't create table 'snipeit.#sql-3626_1fa' (errno: 150)

**Comment by snipe** [comment]
@rootAmeen The migration change isn't on master, only develop right now. 

If there is an issue with the installer script not creating a user for the database, please open a separate issue for that.
