### ISSUE TITLE
Unable to Delete Asset Manufacturers

### ISSUE THREAD

**Issue by ACBobby** [snipe/snipe-it#1413]
When trying to delete an asset manufacturer, I am redirected instead to "Locations" with the following error message.

"Error: admin/locations/message.not_found"

**Comment by snipe** [comment]
Can you reproduce on the demo? Also, please tell us what version you're using.

**Comment by ACBobby** [comment]
On the demo, it still takes me to "Locations", but with the following error.

"Error: This location is currently associated with at least one user and cannot be deleted. Please update your users to no longer reference this location and try again."

I am using the latest (2.6). I had actually just upgraded about 20 minutes prior to posting initially, but this occurred in 2.5 as well.

**Comment by snipe** [comment]
This is fixed on master now
