### ISSUE TITLE
Upgrade snipe-it from v2.05 to v2.06 in window server 08 with XAMPP

### ISSUE THREAD

**Issue by SK9413** [snipe/snipe-it#1415]
Hi everyone,

Can anyone show me the proper steps or tell me if I am doing this right when I tried to update snipe-it from v2.05 to v2.06 in window server;

       1) Download the latest version and overwrite all content at "C:\xampp\htdocs\snipe-it"

       2) Right click at "C:\xampp\htdocs\snipe-it" then choose "Composer Options" > " Install prefer-source"

       3) Right click at "C:\xampp\htdocs\snipe-it" then choose "Composer Options" > " Dump-Autoload"

       4) Right click at "C:\xampp\htdocs\snipe-it" then choose "Use Composer here" > " php artisan migrate"

Also after upgrading to 2.06 when I clicked "Admin> Backup> Generate Backup", it will redirect me to "Edit Your Profile" page.

**Comment by kobie-chasehansen** [comment]
Having the same issue when clicking Generate Backup, takes me to the Edit Your Profile page.

**Comment by SK9413** [comment]
![snipeit](https://cloud.githubusercontent.com/assets/15903195/11491067/50859a06-9819-11e5-8b7d-5a3ad9c10d60.jpg)

And the export button became some strange rune symbol after upgraded to v2.06 in Windows Server 08/12 ( CentOS is ok).

**Comment by snipe** [comment]
@SK9413 That's not a rune, that's Japanese Kanji. Can you reproduce that on the demo? I cannot.

**Comment by SK9413** [comment]
@snipe Hi snipe,

Actually it occurs on the demo site too. Maybe it is related to some locale setting in Windows/ Windows Server? It did not happened in v2.05.

I tried the demo site on different machine and had different result;

HK version windows 8 + ie11
![ie11](https://cloud.githubusercontent.com/assets/15903195/11519955/b5a61aa8-98d9-11e5-896e-7f5c51b3a1b0.jpg)

HK version windows 8 + chrome
![chrome](https://cloud.githubusercontent.com/assets/15903195/11519958/b98a56f2-98d9-11e5-8901-b23b87800591.jpg)

US version server 08/12 + ie11
![ie11 server0812](https://cloud.githubusercontent.com/assets/15903195/11519960/bf2a977a-98d9-11e5-9a5b-6e1f5508aa5e.jpg)

**Comment by SK9413** [comment]
And the problem seems fixed after the demo site upgraded to v2.0.6-72 ( just a few minutes ago). I am looking forward to download and test latest version :-)

**Comment by snipe** [comment]
The javascript table library we use (bootstrap-table) has some glyph icons hard-coded in for some reason. I switched them to fa-icons, which is what we use.
