### ISSUE TITLE
Checkout outdated licenses

### ISSUE THREAD

**Issue by NMonst4** [snipe/snipe-it#1416]
Is it possible to integrate that outdated licences where marked as outdated in table view? And outdated licences shoul not be able to checkout.

**Comment by snipe** [comment]
Can you describe what you mean by outdated?

**Comment by NMonst4** [comment]
When a licens run in Termination Date

**Comment by JohKa** [comment]
same problem here, we have licences that are not valid any more because they are outdated, but they are still checkoutable in snipe-it.
Also it would be nice to get an information of outdated lincences to renew them or to uninstall them on a device.
