### ISSUE TITLE
Is there a way to have negative number for the seats of the licenses

### ISSUE THREAD

**Issue by cloiseauj** [snipe/snipe-it#1417]
I would like to know if it possible to have a negative number for the seats.
Like example if I have 2 seats for a license that I buy and I'm checking out another seat for a user, now  i'm am in -1 for the license. it for keeping the track that I need to buy another.

Thnaks for the help

**Comment by kobie-chasehansen** [comment]
What I've done in this case that seems to work well is I create an over issue for that software title and then when we do buy it I convert the over issue into the actual purchase and create a new over issue asset.

![image](https://cloud.githubusercontent.com/assets/10247644/11482261/ed6a3f2a-976f-11e5-9fe0-78d7e7764952.png)

**Comment by cloiseauj** [comment]
Yeah it workaround, but when you said that you convert it you do a transfer.
How you do it
It there another to do it

**Comment by kobie-chasehansen** [comment]
I clone the over issued license and this resets its seat count back to 0 and I then rename the old over issued to just the software title and add my order info.

**Comment by cloiseauj** [comment]
Thanks for the help
