### ISSUE TITLE
API /hardware/:id/checkin with Licenses

### ISSUE THREAD

**Issue by oshvidun** [snipe/snipe-it#14183]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

When an API request for "checkin" is made, the assigned license for an asset remains assigned to the user

### Reproduction steps

1. License checkout to the Asset (screenshot 1)
2. Asset is checkout to an employee (screenshot 2)
3. API request to checkin equipment from employee
url = "https://asset.pharmbills.com/api/v1/hardware/3913/checkin"

payload = {
    "status_id": 2,
    "location_id": "7"
}
headers = {
    "accept": "application/json",
    "Authorization": 'Bearer APIkey
    "content-type": "application/json"
}
response = requests.post(url, json=payload, headers=headers)
5. License remains checkout to the employee
![4](https://github.com/snipe/snipe-it/assets/85619391/33661356-2cb5-4b2a-9cc7-e8810ed2d8d5)

### Expected behavior

The expectation that the license will not be checkout by the employee. How it happens when working with the web interface
![6](https://github.com/snipe/snipe-it/assets/85619391/ac029d4c-7e5f-4bd1-b465-03e4a8f1b4f6)

### Screenshots

![1](https://github.com/snipe/snipe-it/assets/85619391/95f1d5a1-31ea-4527-96ee-eacb981a2a28)
![2](https://github.com/snipe/snipe-it/assets/85619391/1559f744-5e39-4829-a335-6c951a79d85b)
![3](https://github.com/snipe/snipe-it/assets/85619391/37276804-a170-46e2-a6b0-1d3185dbcbc7)
![4](https://github.com/snipe/snipe-it/assets/85619391/f18d4f48-8c4e-497a-8aae-b2382f5d1559)
![5](https://github.com/snipe/snipe-it/assets/85619391/a74e306b-ee33-42c4-b18d-de8cf613ac21)

### Snipe-IT Version

v6.3.0 build 12490 (g9136415bb)

### Operating System

Ubunte

### Web Server

Apache

### PHP Version

8.1.2-1ubuntu2.14

**Comment by marcusmoore** [comment]
Thanks for the detailed report @oshvidun. I'll look into this.
