### ISSUE TITLE
Assign to room

### ISSUE THREAD

**Issue by TOA-OSS** [snipe/snipe-it#142]
Is it possible to add a enhancement to assign a item to a location instead of a user/person 
##

**Comment by rp-tech** [comment]
I would like to add my support for this request as well.

Another idea I had, is rather than assigning to an actual location, the ability to assign assets a 'sub-location' for example, I have a projector in our Vancouver office; let's say I want it to be assigned to a specific person - John Smith for example owns the asset, it's in Vancouver - but it's 'sub-location' is Main Boardroom. Can we add the ability to 'drill down' to sublocations?

**Comment by civicpath** [comment]
+1 To room assignments or "sub locations". 

These can function just like a user that is assigned to a main location. We deal with buildings that have hundreds of rooms. Items are specific to the room and not necessarily assigned to any particular person. Examples are training rooms, conference rooms, labs, libraries, etc. 

I've worked around this by creating user accounts for rooms. The room doesn't need to login, so just seed a CSV file with the basic data and do the bulk user import. 
 * FirstName = Room Number
 * LastName = Location
 * Email = randomString@<organization.tld>
-> Then assign room user(s) to parent Location

See also the discussion in issue #659

**Comment by snipe** [comment]
@rp-tech FYI, sub-locations are finished on the `1.3.0` branch for the next release. (I am not advocating using the `1.3.0` branch yet, as it's not particularly stable, but jus wanted to let you know that it's done.

**Comment by rp-tech** [comment]
Cheers! I will buy you a beer :>

**Comment by snipe** [comment]
Aww, thanks @rp-tech! (People can actually do that right through Github if they have a ChangeTip account. https://www.changetip.com/how-to-send-tips/github )

**Comment by DanSheps** [comment]
This is good news, I am looking forward to seeing it.  Can you check it out to the sub-location?

**Comment by Accedo-Malin** [comment]
Is it possible for non admin users to check in and out assets? Seems it's only can be done when you're an admin.
/Malin

**Comment by snipe** [comment]
@Accedo-Malin Only admins can check assets in or out. That's by design.

**Comment by accedosupport** [comment]
Thanks @snipe ! There are no plans to have check in/out rights for other roles? We're have a lot of devices that people use from time to time. It would be great if everone could check in/out without getting access to everything as admin. / Accedo-Malin

**Comment by RossIV** [comment]
Any update on this? I was just about to start creating locations as people when I came across this feature request. @snipe?

**Comment by Accedo-Malin** [comment]
Hi there,

Haven't heard anything about it. Still need it very much. We have an
organisation where we need people to check in and out devices themselves
without being admins and have access to everything. We need something in
between.

/M


Malin Hultgren

*Director Support & Service Management and Internal IT*
P: +46 8 752 65 40 M: +46 708 87 35 32  •  Skype: malin.hultgren
Magnus Ladulåsgatan 65, 118 27 Stockholm, Sweden, Sweden
www.accedo.tv

**Comment by brianjking** [comment]
@snipe Just put a $20 bounty on this via the link above. Perhaps @Accedo-Malin & @RossIV & @Accedo-Malin will add to it! 

I'm not sure how you the issue tag gets added showing there is a bounty on the issue?

Thanks! Keep up the great work.

**Comment by brianjking** [comment]
@snipe Since this has been removed from all milestones is it no longer planned to be implemented into Snipe-IT?

There's a $35 bounty on it, from myself and others, as seen here: https://www.bountysource.com/issues/2358238-assign-to-room

I hope this is still planned, thanks as always for your hard work and dedication.

**Comment by leesexton** [comment]
Using the web version of this software and would also like to request the deploy to location rather than user feature, especially handy for printers and other items of value that are in communal places!

**Comment by brianjking** [comment]
@snipe Can you update this ticket title when you have a chance to show the $35 bounty on it? Perhaps that will help someone pick it up as a PR. 👍 

Thanks!

**Comment by therealjoshuad** [comment]
+15 from me, this would be a great feature

**Comment by proweb01** [comment]
The ability to assign to a location instead of a user would be most exceptional. Not sure how you would do this, especially in a LDAP authentication type scenario... Perhaps you could tie into "sites" in AD?

**Comment by Oreios** [comment]
After searching for this myself. This is indeed a valuable addition.

It seems it's a duplicate or at least very similar to this issue. [#512](https://github.com/snipe/snipe-it/issues/512)

**Comment by DustinMc** [comment]
Just adding some more wight to this issue. I just upgraded from 2.0.1pre to the latest version and thought it would have been in there by now. Not that I am impatient....but it would be very nice to have ;)

**Comment by rWaddles** [comment]
Did this ever get updated? As a school which is fixed locations and multiple users it would be very valuable.

**Comment by VanillaNinjaD** [comment]
Checking out to a location is supported in the upcoming v4. It still has some bugs to iron out but from what I've tested, it's close.

**Comment by rWaddles** [comment]
Thanks! Now I have to think do I wait for this before we implement it fully. I suppose I can get all the assets in just not check them out...

**Comment by wccwtaylor** [comment]
A previous employee of ours installed Snipe-It (4.1.8) and we are looking at it now to evaluate.  I'm looking for this feature so if anyone could tell me how this is done I'd appreciate it greatly.  I see it in the announcements, https://snipe-it.readme.io/v4.2.0/blog/whats-new-in-snipe-it-v4, yet I can't find out how to do it.  Do we have to turn on an admin setting somewhere?

**Comment by wccwtaylor** [comment]
I'm a fool!!!  I found it in the GUI, but I'm trying to do it with the import feature.  Is there a column I can use to insert the room or a column that I need to "flag" to make it known the asset is checked out to the room?

**Comment by snipe** [comment]
Unfortunately, the importer only supports checking out to users right now.

**Comment by wccwtaylor** [comment]
Thanks for the reply Snipe, I just tried to do an import with it checked out to a location and it is in a "pending" status so I may have broke it.

**Comment by wccwtaylor** [comment]
How about the Bulk Checkout, is it planned on being updated to allow location as an option?
