### ISSUE TITLE
docker with external database?

### ISSUE THREAD

**Issue by kt1024** [snipe/snipe-it#1421]
does the docker version support external database?

**Comment by uberbrady** [comment]
Yes, instead of launching a docker container for your database, just reference your database information in the environment variables. Snipe-IT will work just fine that way.

**Comment by kt1024** [comment]
what environment variables should I use? can't find in document.
thanks.

**Comment by uberbrady** [comment]
Look at: http://docs.snipeitapp.com/installation/server/docker.html - 

specifically, look for:

```sh
MYSQL_DATABASE=snipeit
MYSQL_USER=snipeit
MYSQL_PASSWORD=YOUR_snipeit_USER_PASSWORD
```

Also, when you run the snipe-it docker instance, you won't need the 'link' to your MySQL instance - so you can leave out this part: 

```
--link snipe-mysql:mysql
```

**Comment by kt1024** [comment]
oh, i mean a standalone/external database. (not container database)

**Comment by uberbrady** [comment]
Oh, right - the documentation isn't that clear if you're using standalone, and I don't document which environment variables you'd use for hostnames, etc.

I'll fix that.

**Comment by uberbrady** [comment]
It looks like the relevant portions of the config are here:
```php
            'host'      => $_ENV['MYSQL_PORT_3306_TCP_ADDR'],
            'port'      => $_ENV['MYSQL_PORT_3306_TCP_PORT'],
            'database'  => $_ENV['MYSQL_ENV_MYSQL_DATABASE'],
            'username'  => $_ENV['MYSQL_ENV_MYSQL_USER'],
            'password'  => $_ENV['MYSQL_ENV_MYSQL_PASSWORD'],
```

So I **think** that means that if you use variables like this:

```sh
MYSQL_PORT_3306_TCP_ADDR=
MYSQL_PORT_3306_TCP_PORT=
MYSQL_ENV_MYSQL_DATABASE=
MYSQL_ENV_MYSQL_USER=
MYSQL_ENV_MYSQL_PASSWORD=
```

Then those ought to get picked up by the running Snipe-IT container. The problem is, I'm not sure if you have to say `MYSQL_USER` or `MYSQL_ENV_MYSQL_USER` for it to carry through...if I look at how the documentation goes for the Mail portion, it looks like you have to have the longer name (`MYSQL_ENV_MYSQL_USER`).

If you could try some of these variables and see if they work that would be really helpful. If not, I will try to find some time to get some more thorough testing done.

Once we have something that we are pretty comfortable that it works, we can try to modify the documentation accordingly.

**Comment by kt1024** [comment]
using latest docker image, got 500 error.

Server Error: 500 (Internal Server Error)

---

in env file:
_ # Mysql Parameters
MYSQL_ROOT_PASSWORD=db-password
MYSQL_DATABASE=snipe-it
MYSQL_USER=snipe-it
MYSQL_PASSWORD=user-password

---
docker run command:
docker run -d -p 80:80 --name="snipeit" --env-file=/srv/docker/env/snipeit.env snipe-it

**Comment by swoopdk** [comment]
Did you run the following command after launching the docker container ?
```
docker exec -i -t snipeit php artisan key:generate --env=production
``` 

Also if you create a shell inside your container can you reach the mysql database on the specific port ?

**Comment by kt1024** [comment]
@swoopdk , have tried the command. still got 500 error. url redirected to:  http://ip//auth/signin
tested inside the container, can reach mysql ip/port.

**Comment by swoopdk** [comment]
@kt1024 and you did the install step also ?

```
docker exec -i -t snipeit php artisan app:install
```

**Comment by swoopdk** [comment]
Also try when you are in your snipeit container to enable debug by editing the app/config/production/app.php to set debug = true;

**Comment by kt1024** [comment]
@swoopdk , after execute app:install now everything is ok. thanks.

**Comment by ThailandCat** [comment]
We spent 2 hours with developer finding the solution for latest at the moment (3.4 stable) release docker container. There is wrong names of some variables mentioned above. Please update documentation 

The correct part of env config is:

# Mysql Parameters
MYSQL_PORT_3306_TCP_ADDR=XXX.XXX.XXX.XXX
MYSQL_PORT_3306_TCP_PORT=3306
# MYSQL_ROOT_PASSWORD=No_need_for_remote_db
MYSQL_DATABASE=snipe_it
MYSQL_USER=snipe_it_db_user
MYSQL_PASSWORD=snipe_it_db_user_password

We run now Snipe-IT official docker image connected to MySQL instance in Google Cloud.

**Comment by uberbrady** [comment]
Fair point, @ThailandCat , I've updated the docker documentation to explain how to use an external DB.
