### ISSUE TITLE
Decimal and thousands separator

### ISSUE THREAD

**Issue by mauroaltamura** [snipe/snipe-it#1422]
Hi,

is it possible to change the thousand separator from , to . and the decimal separator from . to ,?

I've set "€" as currency and "de" as locale in app/config/app.php, but the currency format is still US:

I get, for example, 12,000.00, but I'd need 12.000,00 (German format).

Thanks a lot in advance.

**Comment by snipe** [comment]
It is not currently possible at this time.

**Comment by snipe** [comment]
Closing as duplicate of #1422.

**Comment by hameno** [comment]
We kinda need this, too (also German here). I don't see another issue for this (you also mentioned this ticket as a duplicate of itself... :) ) 
Can we re-open this?

**Comment by migaspar** [comment]
we also would like to have a separator matching the language setting :)

**Comment by ArchdukeNavaron** [comment]
We too!
