### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by chsunil** [snipe/snipe-it#1424]
HI 
i am trying to install snipeit latest from the server.

i hope i have gone through all the settings correct but 

i am getting error 500 
my url is http://assetmgmt.ecomr.com/ 

Thanks in advance for your help

bootstrap/start.php
![bootstrap_startphp](https://cloud.githubusercontent.com/assets/16101705/11502793/e5cad132-9862-11e5-97ec-c85f0debf64b.PNG)

Browser error 
![url](https://cloud.githubusercontent.com/assets/16101705/11502794/e5d2c34c-9862-11e5-8f03-8f679e5b7432.PNG)

**Comment by chsunil** [comment]
i jhave followed instructions from this url

http://docs.snipeitapp.com/installation/index.html

**Comment by ddreier** [comment]
Please follow the instructions here to enable debug mode and post the full error message. http://snipe.github.io/snipe-it/getting-help.html

**Comment by chsunil** [comment]
Here is the error from debug file

Class 'PDO' not found

/home/ecomr/public_html/assetmgmt/app/config/production/database.php
    |
    | By default, database results will be returned as instances of the PHP
    | stdClass object; however, you may desire to retrieve records in an
    | array format for simplicity. Here you can tweak the fetch style.
    |
    */
 
    'fetch' => PDO::FETCH_CLASS,
 
    /*

**Comment by brianjking** [comment]
@chsunil http://www.inmotionhosting.com/support/website/website-troubleshooting/fatal-error-class-pdo-not-found possibly?

**Comment by chsunil** [comment]
Thankyou @snipe  its worked i got the login screen 
i tried to login with credentials given at the time of installation.

but when i tried to login i got this error

Call to undefined function ldap_connect()

 $ldaprdn     = Config::get('ldap.username');
        $ldappass    = Config::get('ldap.password');
        $baseDn      = Config::get('ldap.basedn');
        $filterQuery = Config::get('ldap.authentication.filter.query') . $username;
        $ldapversion = Config::get('ldap.version');
 
	    // Connecting to LDAP
        $connection = ldap_connect($ldaphost) or die("Could not connect to {$ldaphost}");
        // Needed for AD
        ldap_set_option($connection, LDAP_OPT_REFERRALS, 0);


but i am not using any  LDAP 

i didt renamed "app/config/production/ldap.example.php" file.

where i have done wrong  :(

**Comment by chsunil** [comment]
installed LDAP 

and now its fixed .
