### ISSUE TITLE
Error 500 when creating new Asset Maintenance

### ISSUE THREAD

**Issue by niutechmx** [snipe/snipe-it#1426]
When creating a new **Asset Maintenance** I receive an **error 500 after** pressing the button SAVE. the snipe-it version is **(v2.0.6-8)** and the apache error log generate the following line:

[:error] [pid 6037] [client 192.168.8.1:50875] PHP Fatal error:  Class 'Controllers\\Admin\\Asset' not found in /var/www/snipe-it/app/controllers/admin/AssetMaintenancesController.php on line 216, referer: http://url.example.com/admin/asset_maintenances/create

Is the Asset maintenance module working? I`ll appreciate any help to fix this.

Thanks.
Alfons.

**Comment by fcpieper** [comment]
Same here. I started debug mode and here is the module that is causing the crash:

Open: C:\www\app\controllers\admin\AssetMaintenancesController.php
 
Seems to be line 216: 

                $asset = Asset::find( e( Input::get( 'asset_id' ) ) );

Further Output  

GET Data empty

POST Data
_token	YisItjvvhtKa5YChBTaUKYG5GQ8dQxBnXz995mj6
asset_id	16
supplier_id	3
asset_maintenance_type	Wartung
title	Qlik Wartung
start_date	2015-12-01
completion_date	
cost	50
notes	

Files empty

**Comment by niutechmx** [comment]
Here it is my output after enabling debug mode (almost the same output as the user above).

Open: /var/www/snipe-it/app/controllers/admin/AssetMaintenancesController.php

Line 216:                 $asset = Asset::find( e( Input::get( 'asset_id' ) ) );

GET Data empty

POST Data
_token	QG915SceoSzX7KqcvbKJFvgOUREUDQ2PWka2H6y8
asset_id	15
supplier_id	10
asset_maintenance_type	Maintenance
title	ste
start_date	2015-12-01
completion_date	
cost	0.00
notes	

Files empty
