### ISSUE TITLE
General error: 1005 Can't create table 'snipeit.#sql-70e_cb3'

### ISSUE THREAD

**Issue by chrisrbmn** [snipe/snipe-it#1430]
Hi all,
I just tried to run the 2.0.6 upgrade, and ran across this error.
![2015-12-02_10-41-55](https://cloud.githubusercontent.com/assets/5017742/11537166/606306ca-98e1-11e5-8ddb-36724e0d653e.png)

Here are the steps I ran, on my centos 6.7 server.
----------
from /var/www/snipeit

git stash

git pull

php composer.phar install

php composer.phar dump-autoload

php artisan migrate
----------

Did I do the upgrade correctly? or something else?
I don't see any visible issue, unless I go edit something on the settings page.. If I try to change the currency option to US Dollar's, (which is defaulted to TWD - Taiwan New Dollars),  I get a 500 error.
![2015-12-02_10-45-49](https://cloud.githubusercontent.com/assets/5017742/11537280/ee460a32-98e1-11e5-983f-3694989ee3a8.png)

Thanks for your help all,
Chris

**Comment by chrisrbmn** [comment]
I am noticing that the storage engine on the tables appears to be InnoDB on some, and MyISAM on others.

**Comment by brianjking** [comment]
@chrisrbmn I know the USD to TWD is a known issue based on them both using the $ symbol. See https://github.com/snipe/snipe-it/issues/1383 regarding the duplicate.

Did you turn on debugging to see if you can get any other details about the issue you're having otherwise? http://docs.snipeitapp.com/getting-help.html

**Comment by chrisrbmn** [comment]
I have not yet. I did however, create a full backup of the database, drop the current tables, and run php artisan app:install, and get a similar issue when reinstalling release.

![snipeit_install](https://cloud.githubusercontent.com/assets/5017742/11542167/a073ec2e-98fb-11e5-900b-ababac94107a.PNG)

I'll go ahead and enable debugging, and post what I'm seeing.

**Comment by chrisrbmn** [comment]
# I enabled debugging, here's the output:

ErrorException thrown with message "Route [admin.custom_fields.index] not defined. (View: /var/www/snipeit/app/views/backend/layouts/default.blade.php) (View: /var/www/snipeit/app/views/backend/layouts/default.blade.php)"

Stacktrace:
#31 ErrorException in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:231
#30 Illuminate\View\Engines\CompilerEngine:handleViewException in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:41
#29 ErrorException in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:231
#28 Illuminate\View\Engines\CompilerEngine:handleViewException in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:41
#27 InvalidArgumentException in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/UrlGenerator.php:231
#26 Illuminate\Routing\UrlGenerator:route in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/helpers.php:717
#25 route in /var/www/snipeit/app/storage/views/ca2de54ab767c93a92a8973048ab1f0c:259
#24 include in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:37
#23 Illuminate\View\Engines\PhpEngine:evaluatePath in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php:56
#22 Illuminate\View\Engines\CompilerEngine:get in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php:134
#21 Illuminate\View\View:getContents in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php:102
#20 Illuminate\View\View:renderContents in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php:76
#19 Illuminate\View\View:render in /var/www/snipeit/app/storage/views/52e179c6165ddba92dc5afa8252e4e6d:124
#18 include in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php:37
#17 Illuminate\View\Engines\PhpEngine:evaluatePath in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php:56
#16 Illuminate\View\Engines\CompilerEngine:get in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php:134
#15 Illuminate\View\View:getContents in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php:102
#14 Illuminate\View\View:renderContents in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php:76
#13 Illuminate\View\View:render in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Http/Response.php:43
#12 Illuminate\Http\Response:setContent in /var/www/snipeit/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php:202
#11 Symfony\Component\HttpFoundation\Response:__construct in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1501
#10 Illuminate\Routing\Router:prepareResponse in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1036
#9 Illuminate\Routing\Router:dispatchToRoute in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1001
#8 Illuminate\Routing\Router:dispatch in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:775
#7 Illuminate\Foundation\Application:dispatch in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:745
#6 Illuminate\Foundation\Application:handle in /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php:34
#5 Barryvdh\Debugbar\Middleware\Stack:handle in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware.php:72
#4 Illuminate\Session\Middleware:handle in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php:47
#3 Illuminate\Cookie\Queue:handle in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php:51
#2 Illuminate\Cookie\Guard:handle in /var/www/snipeit/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23
#1 Stack\StackedHttpKernel:handle in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:641
#0 Illuminate\Foundation\Application:run in /var/www/snipeit/public/index.php:49



XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**And the output for the /app/storage/logs**
[root@merlin logs]# vim log-apache2handler-2015-12-02.txt
[2015-12-02 14:33:17] production.DEBUG: Authenticating user against database. [] []
[2015-12-02 15:31:59] production.ERROR: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ldap_enabled' in 'field list'' in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php:389
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(389): PDO->prepare('update `setting...')
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(617): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'update `setting...', Array)
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('update `setting...', Array, Object(Closure))
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(394): Illuminate\Database\Connection->run('update `setting...', Array, Object(Closure))
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(339): Illuminate\Database\Connection->affectingStatement('update `setting...', Array)
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1925): Illuminate\Database\Connection->update('update `setting...', Array)
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(316): Illuminate\Database\Query\Builder->update(Array)
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1515): Illuminate\Database\Eloquent\Builder->update(Array)
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1448): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder), Array)
#9 /var/www/snipeit/app/controllers/admin/SettingsController.php(180): Illuminate\Database\Eloquent\Model->save()
#10 [internal function]: Controllers\Admin\SettingsController->postEdit()
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postEdit', Array)
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\SettingsController), Object(Illuminate\Routing\Route), 'postEdit')
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\\Adm...', 'postEdit')
#15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#16 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#17 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#19 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#20 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#21 /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
@
"log-apache2handler-2015-12-02.txt" 1555L, 222369C

**Comment by snipe** [comment]
Can you run `show table status;` in mysql please?

**Comment by snipe** [comment]
http://docs.snipeitapp.com/common-issues.html#during-install-or-running-migrations---sqlstatehy000-general-error-1005-cant-create-table-snipeitsql-3626_1c6-errno-150

**Comment by chrisrbmn** [comment]
```
mysql> show table status;
+------------------------------+--------+---------+------------+------+----------------+-------------+------------       ------+--------------+-----------+----------------+---------------------+---------------------+-------------------       --+-----------------+----------+----------------+---------+
| Name                         | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_le       ngth  | Index_length | Data_free | Auto_increment | Create_time         | Update_time         | Check_time                 | Collation       | Checksum | Create_options | Comment |
+------------------------------+--------+---------+------------+------+----------------+-------------+------------       ------+--------------+-----------+----------------+---------------------+---------------------+-------------------       --+-----------------+----------+----------------+---------+
| accessories                  | MyISAM |      10 | Dynamic    |    3 |             62 |         188 |  2814749767       10655 |         3072 |         0 |              4 | 2015-12-02 13:52:35 | 2015-12-02 13:52:35 | 2015-12-02 13:52:3       5 | utf8_unicode_ci |     NULL |                |         |
| accessories_users            | MyISAM |      10 | Fixed      |    1 |             25 |          25 | 70368744177       66399 |         2048 |         0 |              2 | 2015-12-02 13:52:35 | 2015-12-02 13:52:35 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| asset_logs                   | MyISAM |      10 | Dynamic    |   96 |             63 |        6124 |  2814749767       10655 |         3072 |         0 |             97 | 2015-12-02 13:52:35 | 2015-12-02 13:52:35 | 2015-12-02 13:52:3       5 | utf8_unicode_ci |     NULL |                |         |
| asset_maintenances           | MyISAM |      10 | Dynamic    |    3 |             80 |         240 |  2814749767       10655 |         2048 |         0 |              4 | 2015-12-02 13:52:35 | 2015-12-02 13:52:35 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| asset_uploads                | MyISAM |      10 | Dynamic    |    0 |              0 |           0 |  2814749767       10655 |         1024 |         0 |              1 | 2015-12-02 13:52:35 | 2015-12-02 13:52:35 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| assets                       | MyISAM |      10 | Dynamic    |   36 |             97 |        3520 |  2814749767       10655 |         2048 |         0 |             37 | 2015-12-02 13:52:35 | 2015-12-02 13:52:35 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| categories                   | MyISAM |      10 | Dynamic    |   12 |             43 |         520 |  2814749767       10655 |         2048 |         0 |             13 | 2015-12-02 13:52:35 | 2015-12-02 13:52:35 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| companies                    | InnoDB |      10 | Compact    |    7 |           2340 |       16384 |                       0 |        16384 |  11534336 |              8 | 2015-12-02 13:52:35 | NULL                | NULL                       | utf8_unicode_ci |     NULL |                |         |
| consumables                  | MyISAM |      10 | Dynamic    |    0 |              0 |           0 |  2814749767       10655 |         1024 |         0 |              1 | 2015-12-02 13:52:35 | 2015-12-02 13:52:35 | 2015-12-02 13:52:3       5 | utf8_unicode_ci |     NULL |                |         |
| consumables_users            | MyISAM |      10 | Fixed      |    0 |              0 |           0 | 70368744177       66399 |         1024 |         0 |              1 | 2015-12-02 13:52:35 | 2015-12-02 13:52:35 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| custom_field_custom_fieldset | MyISAM |      10 | Fixed      |    1 |             14 |          14 | 39406496739       49183 |         1024 |         0 |           NULL | 2015-12-02 13:52:35 | 2015-12-02 13:52:35 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| custom_fields                | MyISAM |      10 | Dynamic    |    1 |            124 |         124 |  2814749767       10655 |         2048 |         0 |              2 | 2015-12-02 13:52:35 | 2015-12-02 13:52:35 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| custom_fieldsets             | MyISAM |      10 | Dynamic    |    1 |             32 |          32 |  2814749767       10655 |         2048 |         0 |              2 | 2015-12-02 13:52:35 | 2015-12-02 13:52:35 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| depreciations                | MyISAM |      10 | Dynamic    |    4 |             36 |         144 |  2814749767       10655 |         2048 |         0 |              5 | 2015-12-02 13:52:35 | 2015-12-02 13:52:35 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| groups                       | InnoDB |      10 | Compact    |    4 |           4096 |       16384 |                       0 |        16384 |  11534336 |              5 | 2015-12-02 13:52:35 | NULL                | NULL                       | utf8_unicode_ci |     NULL |                |         |
| history                      | MyISAM |      10 | Fixed      |    0 |              0 |           0 | 70368744177       66399 |         1024 |         0 |              1 | 2015-12-02 13:52:35 | 2015-12-02 13:52:35 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| license_seats                | MyISAM |      10 | Dynamic    | 1563 |             32 |       50192 |  2814749767       10655 |        18432 |         0 |           1564 | 2015-12-02 13:52:36 | 2015-12-02 13:52:36 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| licenses                     | MyISAM |      10 | Dynamic    |   17 |            122 |        2080 |  2814749767       10655 |         2048 |         0 |             18 | 2015-12-02 13:52:35 | 2015-12-02 13:52:35 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| locations                    | MyISAM |      10 | Dynamic    |    2 |             68 |         136 |  2814749767       10655 |         2048 |         0 |              3 | 2015-12-02 13:52:36 | 2015-12-02 13:52:36 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| manufacturers                | MyISAM |      10 | Dynamic    |   10 |             32 |         328 |  2814749767       10655 |         2048 |         0 |             11 | 2015-12-02 13:52:36 | 2015-12-02 13:52:36 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| migrations                   | MyISAM |      10 | Dynamic    |  139 |             54 |        7640 |  2814749767       10655 |         1024 |         0 |           NULL | 2015-12-02 13:52:36 | 2015-12-02 13:52:36 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| models                       | MyISAM |      10 | Dynamic    |   12 |             96 |        1152 |  2814749767       10655 |         2048 |         0 |             13 | 2015-12-02 13:52:36 | 2015-12-02 13:52:36 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| requested_assets             | MyISAM |      10 | Dynamic    |    0 |              0 |           0 |  2814749767       10655 |         1024 |         0 |              1 | 2015-12-02 13:52:36 | 2015-12-02 13:52:36 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| requests                     | MyISAM |      10 | Dynamic    |    0 |              0 |           0 |  2814749767       10655 |         1024 |         0 |              1 | 2015-12-02 13:52:36 | 2015-12-02 13:52:36 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| settings                     | MyISAM |      10 | Dynamic    |    1 |             96 |          96 |  2814749767       10655 |         2048 |         0 |              2 | 2015-12-02 13:52:36 | 2015-12-02 13:52:36 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| status_labels                | MyISAM |      10 | Dynamic    |    9 |             47 |         428 |  2814749767       10655 |         2048 |         0 |             10 | 2015-12-02 13:52:36 | 2015-12-02 13:52:36 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| suppliers                    | MyISAM |      10 | Dynamic    |    4 |            119 |         476 |  2814749767       10655 |         2048 |         0 |              5 | 2015-12-02 13:52:36 | 2015-12-02 13:52:36 | NULL                       | utf8_unicode_ci |     NULL |                |         |
| throttle                     | InnoDB |      10 | Compact    |    7 |           2340 |       16384 |                       0 |        16384 |  11534336 |              8 | 2015-12-02 13:52:36 | NULL                | NULL                       | utf8_unicode_ci |     NULL |                |         |
| users                        | InnoDB |      10 | Compact    |   35 |            468 |       16384 |                       0 |        32768 |  11534336 |             36 | 2015-12-02 13:52:36 | NULL                | NULL                       | utf8_unicode_ci |     NULL |                |         |
| users_groups                 | InnoDB |      10 | Compact    |   31 |            528 |       16384 |                       0 |            0 |  11534336 |           NULL | 2015-12-02 13:52:36 | NULL                | NULL                       | utf8_unicode_ci |     NULL |                |         |
+------------------------------+--------+---------+------------+------+----------------+-------------+------------       ------+--------------+-----------+----------------+---------------------+---------------------+-------------------       --+-----------------+----------+----------------+---------+
30 rows in set (0.00 sec)

mysql>
```

**Comment by chrisrbmn** [comment]
Should I convert all of the tables to InnoDB?

**Comment by snipe** [comment]
So, I think the problem is that the migration is trying to assign a foreign key to a table that's MyISAM. 

What's weird is that your companies table looks to be InnoDB (which is good), though I'm not sure why it is, since I think your default stage engine is MyISAM, since so many of the other tables are MyISAM. In a later migration, we remove the FK constraint, but the table type mismatch is donking up the migration so it can't proceed to even get there.

Go ahead and change the table types to InnoDB if you can, and then try running migrations again. 

I've added engine type to the older migrations to hopefully prevent this issue moving forward with folks who have MyISAM as the default table engine.

**Comment by chrisrbmn** [comment]
well, we made it a touch further..
I converted all the tables to InnoDB, and reran migrate.
the first time I ran it, I got a duplicate column. SO I backed up the table, and dropped the duplicate column.
![1stmigrate](https://cloud.githubusercontent.com/assets/5017742/11544353/0f572722-9907-11e5-8079-d15bd8f673ae.PNG)


I then re-ran migrate, and now get a new error.
![2ndmigrate](https://cloud.githubusercontent.com/assets/5017742/11544375/26197f78-9907-11e5-81a3-3ba49054b068.PNG)


It looks like in versions 5.1 MySQL, MyISAM was default. So i'm guessing anyone using 5.1, will definately see this. In my case, I'm on CentOS 6.7, and installed via yum.
http://dev.mysql.com/doc/refman/5.1/en/server-system-variables.html#sysvar_storage_engine

**Comment by chrisrbmn** [comment]
I went ahead into /etc/my.cnf
and added : *default-storage-engine=InnoDB*
under the [mysqld] heading.

**Comment by snipe** [comment]
Seems like you're maybe pulling from develop, instead of a release? Remove the last migration from the migrations directory. Should be `2015_11_30_191504_remove_fk_company_id`

**Comment by snipe** [comment]
I'm sorry for the hassle on this. That foreign key constraint has been nothing but problems. It came in through a pull request, and since my default tables are InnoDB, we didn't catch this issue during testing.

**Comment by chrisrbmn** [comment]
Its only a small hassle, I'm learning so much about snipeit. I can't tell you how invaluable this troubleshooting has been. 

I admit, I was pulling from dev, and decided today, that this was the day, snipe was gonna be the tool I continue to use, so thought it was a good idea, to pull down release, and migrate into it. I see, that may have been a bad idea on my part.

I have to take some responsibility that this is self inflicted, Thank you for the continued help troubleshooting. :)

I apologize for the newbie question, but what is the path to the migrations directory?

**Comment by snipe** [comment]
It's not self-inflicted. This was a cock-up on our end (and develop is usually pretty stable, so trustworthy for folks with a little risk tolerance, but unfortunately since some people have already run those migrations, fixing it in a way that won't break stuff for others is the challenge. :-/

Migrations are in `app/database/migrations`. It should be the last file.

**Comment by snipe** [comment]
Do you have existing data in the database, or is this more or less a fresh install? I'd be curious to see if you reinstall from the latest on develop if you still run into these issues.

**Comment by snipe** [comment]
(This foreign key nonsense is exactly why I never use foreign keys. They always seem like a good idea but always end in tears.)

**Comment by chrisrbmn** [comment]
I have existing data.. I copied the DB into a backup database, and wiped the tables, and still had the issue on the fresh install..

I removed that `2015_11_30_191504_remove_fk_company_id` line, and reran migrate, I now get *Nothing to Migrate*

**Comment by chrisrbmn** [comment]
i'm repulling from dev.  just to see what magic I can cause! Whooppeee!

**Comment by snipe** [comment]
Okay, that's good. You should be all set then, as that was the last migration. 

I'm not sure why you'd run into the same issue on a fresh install, since those tables should all now be specified as InnoDB. 

I need to figure out how to future-proof this for you and others though. What a mess. :(

![update-resume-part-2](https://cloud.githubusercontent.com/assets/197404/11545122/5d563fa6-98fa-11e5-8bc7-39eefb572e5e.gif)

**Comment by chrisrbmn** [comment]
ok, dev, breaks it.  lol

**Comment by snipe** [comment]
Breaks it how?

**Comment by chrisrbmn** [comment]
reran using dev. 

git pull
php composer.phar install
php composer.phar dump-autoload
php artisan migrate

gives me this:
![migrate_dev](https://cloud.githubusercontent.com/assets/5017742/11545175/6befa2f8-990b-11e5-9ca2-82dfc058aabd.PNG)

**Comment by snipe** [comment]
Okay, the pull from dev probably put that migration file back, that's all.

**Comment by chrisrbmn** [comment]
yep. its there. I'm gonna pull it, and leave it alone for now.  HA! :)
![migrations](https://cloud.githubusercontent.com/assets/5017742/11545219/a1577768-990b-11e5-9afd-1b5c5866a23f.PNG)

**Comment by chrisrbmn** [comment]
removed the file, 
reran composer.phar install --no-dev
dump-autoload
migrate.
I get *Nothing to Migrate*.

**Comment by snipe** [comment]
That's what I would expect, since it was just that last migration it's choking on. 

That's still a weird error to get though. If all of the tables are InnoDB now, the foreign keys should have been able to be added (and then removed in that last migration). :-/

**Comment by chrisrbmn** [comment]
Well, I'm happy to try and help out in the future, but you should probably work on that "day drinking".. ;)
