### ISSUE TITLE
ISSUES, if want to move or copy projects snipe-it to another computer.

### ISSUE THREAD

**Issue by rikysyaputra06** [snipe/snipe-it#1431]
I want to move computers to continue snipe-it.
but I had problems with it, I've backup mysql database and I can already backed up files. then I moved to another computer, I copy all project data that is in the folder snipe-it to another computer. when I go to localhost, I can not access it. I want to ask how to do if I want to switch another computer to continue the project-it's snipe. if I reset it will take a very long time, is there a way to move the computer used ?.

as info: xampp and the others, all the same there is no difference. but if I want to access can not view the first login.

**Comment by snipe** [comment]
We need to know specific error messages you're seeing when you're trying to access the app.

**Comment by rikysyaputra06** [comment]
when I installed the first computer I put the project on "xampp / htdocs / snipe-it", then my browser access in "localhost / snipe-it" it directly to the login page. I also tried to fill some of the data into the project.

but I have problems when I want to move the project to another computer. I'm doing just copying all folders snipe-it to another computer and then I also database backup to another computer. but when I access the "localhost / snipe-it" was not directly to the login page, I only view the first entry in the folder browser, if I access "localhost / snipe-it / server.php" I go to the login page but only display text , no graphics display as plain html text. but if I access "localhost / snipe-it / public" there are errors.

#####################
Object not found!

The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.

Error 404

localhost
Apache / 2.4.10 (Win32) OpenSSL / 1.0.1i PHP / 5.6.3
####################

I should know, how the stage if I want to move the project to another computer?
is there any way to move the project to another computer, please give me a tutorial.

**Comment by snipe** [comment]
You'll need to make sure your web server settings are the same on both machines. If you have the files from the other install, and a DB dump, everything should work as expected as long as the two web servers are set up the same.
