### ISSUE TITLE
Unable to sign in with google workspace.

### ISSUE THREAD

**Issue by hotrungtin** [snipe/snipe-it#14313]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

I have set up according to the instructions and logged in step by step, but I still get the error as shown in the picture. I have created and tried many Client IDs and Client Secrets but still without success. Has anyone encountered this situation?

### Reproduction steps

B1 ![z5180884580351_e87d6eb137edf846822d342c4bd5b46b](https://github.com/snipe/snipe-it/assets/159102241/e52b7153-2f24-41f5-9454-dca5fc77652c)
B2:  ![z5180886353835_21a0ccc11270308fe1a91fd77e63ba1b](https://github.com/snipe/snipe-it/assets/159102241/e34ca694-ba34-4608-8880-2b7884017cbd)
B3: ![z5180887483499_d4af944eb5df650f6d423a07034ee8f4](https://github.com/snipe/snipe-it/assets/159102241/a761337e-c9b1-46a1-bcdf-c03464e1f14c)
B4:  ![z5180889036247_a63ad5ef960f0e707bbb301367420e8b](https://github.com/snipe/snipe-it/assets/159102241/d7139e22-722f-4ea0-a95e-0ea22e23f4ae)

Google: ![z5180908909854_50eea2e603be777bd6b5a7b69fbd911f](https://github.com/snipe/snipe-it/assets/159102241/8903fbbd-dca4-4680-b2fb-4711a4085473)

### Expected behavior

No

### Snipe-IT Version

v6.2.2 build 11714

### Operating System

Ubuntu 20.04 LTS

### Web Server

Apache

### PHP Version

7.4.33

### Operating System

Win 11

### Browser

Chorme

### Version

121

**Comment by mauro-miatello** [comment]
in my Google Cloud Console I've only the first URl as redirect URI
which guide have you followed?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
