### ISSUE TITLE
Undo Soft Delete for Manufacturers

### ISSUE THREAD

**Issue by BinghamAdmins** [snipe/snipe-it#1432]
So I'm playing around with version v2.0.6-11 and it looks like I can't undo a soft delete for manufacturers. Unless I'm missing it I am unable to re-create the same manufacturer.

For example:
If I first create Dell for a manufacturer and then delete it I can't re-create it.
The error I get is "The name has already been taken."

Is there a way to undo the soft delete and bring this back?

Thanks for your help.
Ryan

**Comment by snipe** [comment]
We don't have any built-in way to do that, but if you have access to the database via phpMyAdmin or something like that, you can set the `deleted_at` field to null to bring it back.

**Comment by BinghamAdmins** [comment]
Thanks Snipe.
That solved my issue.
