### ISSUE TITLE
Error from LDAP Server:  Bad search filter

### ISSUE THREAD

**Issue by moterpent** [snipe/snipe-it#1434]
**Version:**  2.0.6 (dev)

**OS:** CentOS Linux release 7.1.1503 (Core)

**Process:**

1. From the menu, admin -> settings
2. Change ldap filter field to something more complicated than cn=* (see examples below)
3. From the menu, People -> LDAP Import (button) -> Select a location -> click "Synchronize"

**Error:**  Error from LDAP Server:  Bad search filter

**Examples:**

When working with ldap filters beyond cn=*, I receive the aforementioned message upon import.  For instance:

    (&(objectCategory=person)(objectClass=user))

The query works fine, against the same data source, with tools like ldapsearch.  For example:

    ldapsearch -x -h hostname -D "someuser@example.com" -W -b "ou=Somesite,ou=someou,dc=some,dc=domain" -s sub "(&(objectCategory=person)(objectClass=user))"

...returns the expected records

**Comment by snipe** [comment]
Can anyone else using LDAP integration confirm this behavior?

**Comment by ddreier** [comment]
Remove the outside-most parenthesis. Snipe-IT adds them automatically.

**Comment by snipe** [comment]
@moterpent Does this resolve your issue?

**Comment by moterpent** [comment]
Sorry.  Hadn't looked at this for a few days.  Just to confirm, in order for the following query to function properly...

    (&(objectCategory=person)(objectClass=user))

...it should instead be expressed (in the web form) as...

    &(objectCategory=person)(objectClass=user)

Is this correct?

**Comment by ddreier** [comment]
Yup! For example, mine looks like this:
````
&(objectcategory=person)(objectclass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2))
````

**Comment by moterpent** [comment]
Thanks @ddreier.  Confirmed that this works.  Feel free to close.
