### ISSUE TITLE
Unable to backup information

### ISSUE THREAD

**Issue by LaneZhiyue** [snipe/snipe-it#1436]
Hi. I try to backup my data but I encounter this error after I clicked "generate backup"
![image](https://cloud.githubusercontent.com/assets/8545277/11553038/d1dd5b86-99c5-11e5-90d8-d5740980ed3a.png)

**Comment by LaneZhiyue** [comment]
I upgraded the system and tried again to backup. However, it shows me that I have insufficient permission.

**Comment by snipe** [comment]
Make sure your user has super-admin privileges in the Permissions tab

**Comment by LaneZhiyue** [comment]
I have checked the account authorisation which is admin. The admin setting seems have no problem
![image](https://cloud.githubusercontent.com/assets/8545277/11554837/87f7e0ca-99d6-11e5-8b5d-bd3b131af907.png)

**Comment by snipe** [comment]
Your user, not the group.

**Comment by LaneZhiyue** [comment]
I double checked with the administration panel and database, the account is under this admin group. But I still receive the Permission Error Message

**Comment by snipe** [comment]
I'm not talking about the group. I'm talking about the user's permissions on the permissions tab while editing the user.

**Comment by LaneZhiyue** [comment]
I see, thanks.
