### ISSUE TITLE
Manager Reporting

### ISSUE THREAD

**Issue by RobMSeagate** [snipe/snipe-it#1439]
A feature request - Please can a report or view be added that shows all assets assigned to a manager and their staff. Example, if I have 10 people linked to me as their manager, I would like to see my assets and all assets for those 10 people.
A report would suffice, even better would be a login type or group that allows somebody to see every asset they are ultimately linked to, inc. via their staff.

**Comment by mahesh2471990** [comment]
Hello Snipe. I was about rise new issue.
I was keep checking about this. I got this request before only by @RobMSeagate 
Future Request for reporting Permission or group we can tell. Regarding this I have some blue in my mind.


As if now when we give a user (manager) permission of reporting he is able to see or view all the report of the Assets and history. Which is no use for him. It may be out of focus to a manger to check other assets information. Not required to see the others assets information.

@snipe I prefer as mention above 10 users who linked with their manager. 
When manager Login snipe it. Dashboard will be having information of this Assets ,lic, etc. Checkout. as now. 

My request is there must be information of all 10 users(who has linked to manager)where they had been checkout with assets, lic in dashboard.

Where i have already mention in this ticket  #1610 about fields. same here will be copied also
So if a user is manager. he should have Extra permission that we can set him to view the important fields of his linked users

So we can create manager Group. Give the permission of his own fields as well as USERS Fields (the most important) Permission. So we can manually assign which and all fields of user required to view in manager user dashboard.

For Example i have given some snapshot. To get better idea regarding this

When we come to Reporting section as if now. below snapshot.

this is permission given 
testind is user (having only user permission)
testmanager is manager of testind user (having reporting permission)
Snapshot below
![permission](https://cloud.githubusercontent.com/assets/16305213/12323981/adf240ba-bae5-11e5-97b2-da24aeb6b999.JPG)

Using manager login his dashboard. He should able to see the users information also

![manager](https://cloud.githubusercontent.com/assets/16305213/12324163/cfead802-bae6-11e5-967c-3a019b55df93.JPG)



Reporting Section should be modified
where i mention in before lines. its not require to know all the things to him.

He is able see the all the history when we add the user in reporting group.snapshot below.
![managerff](https://cloud.githubusercontent.com/assets/16305213/12324149/bbf47fe2-bae6-11e5-86da-ef769bdbe6e6.JPG)


Thank you @snipe 
If any info you required let me Known.
