### ISSUE TITLE
Error 500 on admin/custom_fields

### ISSUE THREAD

**Issue by rootAmeen** [snipe/snipe-it#1441]
Hello! 

Just installed the new develop update for custom fields, the system all in all seems to be functioning pretty well. But when I visit admin/custom_fields in order to add new fields I get Error 500, and nothing in my apache logs:
############################

Oh no!

Server Error: 500 (Internal Server Error)

What does this mean?

Something went wrong on our servers while we were processing your request. We're really sorry about this, and will work hard to get this resolved as soon as possible.

Perhaps you would like to go to our home page?

############################

**Comment by snipe** [comment]
Literally the first thing we need you to do any time you're reporting an issue is to turn debugging on. It's why it's the first thing on the Getting Help page. We need specific errors, not generic 500 errors.

**Comment by cantmz** [comment]
Hi snipe,
I got same issue.

![image](https://cloud.githubusercontent.com/assets/15346013/11584673/faaef9d4-9a65-11e5-80ea-2cb45705d07d.png)

**Comment by snipe** [comment]
And without any debugging info, I cannot help you. Just like the OP. Turn on debugging as we ask in the docs.

**Comment by snipe** [comment]
I apologize. The screenshot didn't show up right away. I wil try to investigate. 

In the meantime, have you run composer dump-autoload?

**Comment by cantmz** [comment]
Hi snipe blame on me.
I forgot to run

php composer.phar dump-autoload
php artisan migrate

Apologies

**Comment by rootAmeen** [comment]
Sorry for not posting details earlier.
After running php composer.phar dump-autoload as you suggested, it worked. 

I'm not familiar with composer and laravel :|
