### ISSUE TITLE
Update Snipe to Latest version

### ISSUE THREAD

**Issue by charlesvline** [snipe/snipe-it#1443]
Hi Snipe,

Our environment is using snipe for IT asset management. Thanks for the great product.  Now we plan to update it to latest version. 

Current setup: 
1 Snipe 1.2.8
2 Use MySqL
3 uses PHP 5.4
4 IIS 8 on Server 2008 R2

In your docu, "Simply pull down the newest release, copy the files over, and run whatever commands the release notes specify. Your configuration files won’t be overwritten, since you had to copy them over from the example configs, and your version isn’t in version control."

Could you please guide me through which files I need to replace? 

Thanks

**Comment by brianjking** [comment]
@charlesvline Take a look at the last two comments on https://github.com/snipe/snipe-it/issues/1382 as I just had this question as well.

Thanks!

**Comment by sebnash** [comment]
These are my notes for updating Snipe-IT:

- [ ] Download release from GitHub. e.g.:
```shell
$ curl -LOk https://github.com/snipe/snipe-it/archive/v2.0.6.zip  
$ unzip v2.0.6.zip
```
- [ ] Update application folder (be careful with the trailing `/`s!)
```shell
$ rsync -avut snipe-it-2.0.6/ /path/to/snipe-it
```
- [ ] Check [directory permissions](http://docs.snipeitapp.com/installation/configuration.html#set-directory-permissions)
- [ ] Complete this version's update steps. e.g.:
```shell
$ php composer.phar install
$ php composer.phar dump-autoload
$ php artisan migrate
```

Hope that helps!
