### ISSUE TITLE
Feature Request - New field for external ticket / reference number

### ISSUE THREAD

**Issue by RobMSeagate** [snipe/snipe-it#1445]
Can a new field be added so external reference numbers can be recorded against an asset. We receive purchase requests via a service management tool and we would like to have the request ticket numbers added to the asset details so the history can be tracked across both tools.
Example: Request ABC123 is raised in the service management tool to ask us to order a laptop. Laptop is ordered & received, then added to Snipe-IT with the ABC123 reference added to a specific field. Should we need to lookup the original request, it's logged against the asset.

**Comment by ddreier** [comment]
Custom fields are very close to being released. You can test them out in the demo instance at snipeitapp.com.
