### ISSUE TITLE
Issue when saving records

### ISSUE THREAD

**Issue by spOmes** [snipe/snipe-it#1446]
Hi , 

Snipe is working ok now just unable to save anything , I am click the the save button and nothing happens. 

No Error Messgae
Cheers

**Comment by brianjking** [comment]
@spOmes http://docs.snipeitapp.com/getting-help.html

**Comment by spOmes** [comment]
SNIPE IT Version - v2.0.5-pre-60-g67a5822
PHP Version	5.6.14-0+deb8u1
Laravel Version	4.2.17
Debian Server

**Comment by spOmes** [comment]
It doesn't produce any log files when in debug mode no error page, its on the section where you would select a model or assets the save button just doesn't work.

**Comment by spOmes** [comment]
FIREFOX DEBUGGING Showed me this.


Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://assetdesk.biuk.bi.corp/api/models. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

**Comment by spOmes** [comment]
CHROME DEBUGGING SAYS

**Comment by spOmes** [comment]
create:638 
jquery-latest.js:9631 POST http://assetdesk.biuk.bi.corp/api/models send @ jquery-latest.js:9631jQuery.extend.ajax @ jquery-latest.js:9176jQuery.(anonymous function) @ jquery-latest.js:9322(anonymous function) @ create:730jQuery.event.dispatch @ jquery-latest.js:4641elemData.handle @ jquery-latest.js:4309
create:1 XMLHttpRequest cannot load http://assetdesk.biuk.bi.corp/api/models. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://assetdesk' is therefore not allowed access. The response had HTTP status code 404.
create:743 Uncaught TypeError: Cannot read property 'error' of undefined

**Comment by brianjking** [comment]
@spOmes If it is actually a CORS issue you can fix it here: http://www.webcodegeeks.com/web-servers/cors-and-how-to-enable-it-in-apache-web-server/

**Comment by spOmes** [comment]
Worked this out , 

Still had 000-default.conf file in sites-enabled 

This was pointing to  the wrong default document route . 

Tested now all ok .

**Comment by spOmes** [comment]
Should an *Api* folder exist in
