### ISSUE TITLE
Server Error: 500 when uploading images / taking backup

### ISSUE THREAD

**Issue by chrisrbmn** [snipe/snipe-it#1448]
This is on Release 2.0.6-74, on CentOS.

Recently upgraded from Dev install to Release. When I Attempt to add a new asset model, and upload an image, I receive Error 500 page.
Additionally, when using the Settings -> Backups, I see Error: Insufficient permissions
![error](https://cloud.githubusercontent.com/assets/5017742/11597602/4cafe1fa-9a82-11e5-8e1b-b1e1d2655650.PNG)
I have verified apache owns the following:
/app/storage
/app/private_uploads
/public/uploads
![apacheowns](https://cloud.githubusercontent.com/assets/5017742/11597654/91890770-9a82-11e5-9949-a06048ee19d0.PNG)

I've even gone as far as CHMOD to 777 on the folders and recursing down to everything again.
Still no dice.

**Comment by snipe** [comment]
It's your user permissions, not directory permissions. Edit the user, click on the permissions tab, and make sure super-admin is checked.

**Comment by chrisrbmn** [comment]
ack! ok. yep, that did it..
thank you.
