### ISSUE TITLE
Order Number Leads To 404 Page

### ISSUE THREAD

**Issue by Xipherisroot** [snipe/snipe-it#1449]
I noticed that the links for order numbers seem to be incorrectly generated.

For example:

https://somesite.com/snipe-it/public/hardware?status=Pending

Shows a list of order numbers to the right, highlighting one shows the following link:

https://somesite.com/snipe-it/hardware/?order_number=987698576946

This goes to a 404 page, its missing the reference to "/public/" and has a trailing slash "/" after "hardware", if I manually change the link to the following, it works fine:

https://somesite.com/snipe-it/public/hardware?order_number=987698576946

This is so far the only thing that does not work correctly, the install is right out of the box with nothing changed and just the example data it comes with loaded.

Really spiff software by the way, responsive, slick... this is cool stuff.

**Comment by snipe** [comment]
Looks like something is donked on your end there - `public` should't be in the URL. You should have set your DocumentRoot to public, or set up an Alias if you're running it in a subdirectory.

**Comment by Xipherisroot** [comment]
I'm going to say a set of words that will make you unhappy ;)

"CPanel Server"

But it still is strange, all the other links are generated correctly, but that one is just:

<a href="../hardware/?order_number=987698576946">987698576946</a>

Yet the model link to the left is generated as:

<a href="https://somesite.com/snipe-it/public/hardware/models/1/view">MacBook Pro (13-inch, Mid 2012)</a>

I can understand what you are getting at, but this seems to be a unique behavior in contrast to the expected or observable behavior of all the other links in the software as far as I can tell.
