### ISSUE TITLE
Asset image issues with docker and demo

### ISSUE THREAD

**Issue by swoopdk** [snipe/snipe-it#1453]
I'm having the following issues with attaching images to assets.

On a docker installation i get an error uploading.

1. If the image is too big i seem to be getting one error. 
2. If the image is small enough i get the following error upon upload:

```SQLSTATE[42S22]: Column not found: 1054 Unknown column 'image' in 'field list' (SQL: update `assets` set `purchase_cost` = 0, `updated_at` = 2015-12-07 12:54:15, `image` = VEltVAYy8UzHyAOoROy5Vg8kZ.jpg where `id` = 13)``` 

In the same round i though about the data stored and how it would be better used in Docker scenarios. Stuff like uploaded should be linked to external volume and made sure it's all uploaded to the same bunch of subdirectories so that the container can be killed and replaced with no data loss. 

On the demo one can upload but not delete the image again. If i edit the asset and check the box next to the image and click save it persists.

**Comment by swoopdk** [comment]
Oh forgot to mention. It's the docker_enhancements branch i have been using as i didnt find the SSL additions in any of the other branches anywhere.

**Comment by snipe** [comment]
That's probably an out of date branch. Everything gets merged into develop and then master when it's good to go

**Comment by swoopdk** [comment]
That was my question on Gitter about the merging... if the docker_enhancements branch has been merged with something newer (develop) yet :) Because i would like to test something more up to date :)

**Comment by uberbrady** [comment]
@swoopdk - finally got that branch merged in to develop - when you have a chance to check it out, please do - the other Docker issue with images I'm going to also see if I can do something about; it makes sense that images should live in a separate directory outside of its container.

But I'll try and put that in as a separate issue, presuming we don't already have one for it (and I think we do!)
