### ISSUE TITLE
Unable to create new model while creating asset

### ISSUE THREAD

**Issue by swoopdk** [snipe/snipe-it#1455]
When i try to create an asset (natural flow to try to add asset rather than model ect first) i can add some things directly there. However a required field is model, but the create dialog there doesn't support adding any new manufacturer or categories. Thus unless i previously have created the manufacturer and/or categories i cannot complete adding my asset. 

Better solution would be to let people write free text rather than select from drop down, or give options to do both and/or autocomplete suggestions to keep uniform names. In any case broken workflow that requires me to setup things in advance of adding my particular assets.

**Comment by swoopdk** [comment]
Using the docker_enhancement branch and noted the problem there.

**Comment by snipe** [comment]
I'm not sure that branch is up to date. Can you reproduce this on the demo?

**Comment by snipe** [comment]
Clicking on the plus symbols next to the fields allows you to add them on the fly. This has been part of Snipe-IT for several versions now.

<img width="426" alt="create_asset____snipe_it_asset_management" src="https://cloud.githubusercontent.com/assets/197404/11680831/b245434e-9e0f-11e5-8bec-4cb3bf6e40bd.png">

**Comment by swoopdk** [comment]
I wasnt specific enough. I can find that on the fly part, but we cant add manufacturer in the same way. Might be smaller issue but still annoying to enter an asset and have to abort to enter the manufacturer first. 

So while the model quick add is there, under that quick add i cannot add a new manufacturer that is also a required field. So my required workflow is

1. create manufacturer if new
2. create asset 
2.1 create model through quick add 

Would love thte same quick add feature, or simple a text field you could fill in for manufacturer since it's a required field.

**Comment by snipe** [comment]
It's a little more complicated than that, since you're now talking about nested modals. It's something we have on our radar, but it starts to become a UX nightmare.

**Comment by swoopdk** [comment]
I complete agree. I would much prefer some sort of free text field where i can either choose from the drop down as it is right now, or simpe enter some new text. 

Downside is of course then not all fields get filled in for example a model that i just gave a title and nothing else. 

Personal preference not many fields should be required. But i don't have the overview of  how many things that would break hehe

**Comment by aglasson** [comment]
I have only rarely run into this problem when initially configuring Snipe. As there are only so many possible manufacturers once they are in this won't be an issue. I think it is good how it is, it's not perfect but I don't think this needs changing. Just my 2c.
