### ISSUE TITLE
After checkout asset to user still it showing in users requestable

### ISSUE THREAD

**Issue by hemantdhonge** [snipe/snipe-it#1457]

**Comment by snipe** [comment]
The asset is still requestable, the requestor may just not get it for a while. (For example, QA devices that are being used by another team member, but need to be given to the requestor as soon as they're finished.)

**Comment by yaman2k** [comment]
@snipe It would be good if we can have another field in the Requestable page for Quantity Available per asset.  This would make the user better informed about asset availability.  Kind of like checking out a book at the library.
