### ISSUE TITLE
The MAC is not showing in the asset

### ISSUE THREAD

**Issue by testUAB** [snipe/snipe-it#1458]
Hi,

First I created a Assert Model with the "The MAC is not showing in the asset" option activated, but when I create a new Asset I don't have the option of the MAC, memory or processor...

Anyone can help me please?

I have the version: 2.0.6-11

Thanks!!

**Comment by snipe** [comment]
@testUAB the MAC address field only shows up once you've selected the appropriate model from the asset list while creating/editing assets. If you're not seeing it, we'll need to know if your browser is kicking out any console errors.

**Comment by testUAB** [comment]
Yes, I have this error in the console:
GET https://debianMaster/api/models/5/check net::ERR_CONNECTION_REFUSED

**Comment by testUAB** [comment]
it's running, I had a problem with the url in app.php(SSL). 
Another question, in the demo web I've seen the Custom Field option but i don't have it. It's a problem with the version?

Thanks!

**Comment by ddreier** [comment]
@testUAB The demo represents the current development state of the app. The 2.0.6 *release* does not have custom fields, but a future release will.

**Comment by snipe** [comment]
@testUAB are you actually running your app over SSL? If not, you need to change your url in app/config/production/app.php to not use https

**Comment by testUAB** [comment]
Thanks @snipe and @ddreier, the option off the MAC now it's appearing.
Now, I 'm trying to install the develop version because I need the "custom fields" option. After install snipe I execute this sentences but the option doesn't appear:

php artisan key:generate --env=local
php artisan app:install --env=local

can you help me?

**Comment by ddreier** [comment]
Do you mean the MAC address option? It's been replaced with a custom field. If you upgrade an existing database the asset models with that already have the MAC address option will be given a MAC address custom field automatically. Otherwise you'll have to create the field and fieldset, and then associate that fieldset with the models you want.

**Comment by testUAB** [comment]
I have installed in a new machine the develop version, but for example if I create a new asset model the option of "Show MAC address field in assets in this model"  it's appearing and I don't have the "Custom Fields" option in Admin. It is because I didn't install well the develop version @ddreier ?

**Comment by snipe** [comment]
Yes, custom fields are only on develop right now.
