### ISSUE TITLE
Sort by EOL

### ISSUE THREAD

**Issue by SebastianStuepp** [snipe/snipe-it#1461]
Hi,

since I upgraded from 2.04 to 2.06 I can't sort by "EOL" anymore. This was pretty useful, to see when the next users are up for replacement.

![image](https://cloud.githubusercontent.com/assets/16120414/11651608/6a8fad14-9d92-11e5-8765-e4e5cee0d344.png)

**Comment by snipe** [comment]
This is on the roadmap, but EOL is calculated (versus a date field in the database) and all sorting is now done on the server side instead of the client side, so it's currently not possible without additional data manipulation.

**Comment by schannall** [comment]
You can always just export it as CSV and sort by EOL with Excel/Calc for the time beeing ;).

sC

**Comment by SebastianStuepp** [comment]
That's what's I'm doing in the moment. But the csv export is quite ugly, exporting all Kinds of weird characters and creating empty rows and stuff that I've to remove by hand.  Probably a bug or related to umlauts...or so



Sent from my iPhone


Sebastian Stüpp
IT Systems Administrator

Alpha Trains Europa GmbH
Cäcilienstraße 30, 50667 Köln

Tel:    +49 221-914090-50
Fax:    +49 221-914090-19
Mobile:         +49 173 1747 504

www.alphatrains.eu<http://www.alphatrains.eu>

Firmensitz: Köln – Geschäftsführung: Shaun Mills, Thomas Schmidt, Ingo Wurzer – Amtsgericht Köln; HRB 51575


[BAR]

[Alpha Trains Logo]<http://www.alphatrains.eu>


Am 12.04.2016 um 13:43 schrieb schannall <notifications@github.com<mailto:notifications@github.com>>:


You can always just export it as CSV and sort by EOL with Excel/Calc for the time beeing ;).

sC

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/snipe/snipe-it/issues/1461#issuecomment-208859506>



Click here<https://www.mailcontrol.com/sr/lD4PMRzLFgvGX2PQPOmvUq10po4Wab0lSm49JVIH9bWa5KnoCPJnSO6TTCQvQOyGm!Wtb8ydoXs94h7CChK4GQ==> to report this email as spam.

**Comment by JorisVanEijden** [comment]
Does the closure of this ticket mean the feature is also off the roadmap?
Will a PR to fix this be accepted?
If so, is there a preference for a server-side or client-side solution?
