### ISSUE TITLE
Update Query / Mass update of asset model?

### ISSUE THREAD

**Issue by InternStarz** [snipe/snipe-it#1462]
I noticed a small issue with importing with every asset having a pre populated asset model, so I took that out of my import. I went back in after I imported to do a bulk update model, and I couldn't find the option to do that.

Is there a way to run an update query or do a bulk edit for Asset model types? I can run the bulk update to change location and status, but I don't see an option to update model.

Is this possible? Any help would be nice. Thanks!

**Comment by snipe** [comment]
That is not currently possible. 

What was your issue with the pre-populated asset model? That field is required, so taking it out probably wasn't the best idea. Better to resolve the import issue.

**Comment by InternStarz** [comment]
When I was trying an import of 5 assets to begin with, I first created an asset model. I used that same asset model in all 5 of the devices. After the import, I went into my list of different asset models only to find 5 copies of the "Acer Chromebook 13" asset model, all with 1 device assigned and 0 to the asset model I created myself.

I took out the asset model because I didn't what to have to delete all those individual asset models that had created. I'd be willing to attach a screenshot if you'd like.

**Comment by snipe** [comment]
Did they all have the same model number, category and manufacturer?

**Comment by InternStarz** [comment]
Yup. I've attached an example of one of the uploads I changed up. My first attempt to was to do the top 5 lines of that .csv with the model information in it. It created 5 separate asset models with the same name with 1 asset assigned to it.

**Comment by snipe** [comment]
Nothing was attached.

**Comment by InternStarz** [comment]
Sorry, it wouldn't take the .csv. I changed it to tab delimited .txt file.

**Comment by snipe** [comment]
Does this also happen when the CSV is comma delimited?

**Comment by InternStarz** [comment]
It did not work. You can see what it did to the asset. It put everything inside the Status label, rather than separating out. I just took the exact same txt I uploaded and deleted everything except the top row and the first 5 assets.
![tab txt upload](https://cloud.githubusercontent.com/assets/16209671/11716223/47a372e2-9f16-11e5-9409-83bdd017fff3.png)

**Comment by snipe** [comment]
It's expecting a comma delimited CSV, so not sure what you might have done here. Did you actually export it as comma delimited, or did you just search and replace tabs to commas? Comma-Delimited will need text inside quotes.
