### ISSUE TITLE
Door keys as new Asset Type (like Licenses)

### ISSUE THREAD

**Issue by rokde** [snipe/snipe-it#1463]
We have the need for handling door keys given to employees. Each key has a number and opens different kind of doors. We have a list for handling door access keys and chips for managing which employee has what key.

Could you extend snipe-it for having Keys or something like that in management? The behaviour is like licenses too. We use this feature right now for handling this. But it would be nice if it was implemented.

Thanks in advance, good job!

**Comment by silicon11** [comment]
why can't each key be an asset that is categorized as a key?

**Comment by ddreier** [comment]
Is there anything specific about licenses that doesn't fit your use case other than it being called "licenses"? I think that Accessories would fit the bill as well. Duplicating either of those just to have a section called "Keys" seems like wasted effort to me.

**Comment by rokde** [comment]
Yeah, it could be used as a license. You are right. We use it this way - works fine. In real life a door key is something different than a software license, but yeah, still keep using it this way is agood way.
