### ISSUE TITLE
search in assets Module

### ISSUE THREAD

**Issue by abdullahalasham** [snipe/snipe-it#1464]
Dear Snipe,

when try to search for any pace of information in assets module I enter the word in search box but i did not retrieve any information .

could you help in this

**Comment by snipe** [comment]
What errors does your browsers debugging console show?

**Comment by abdullahalasham** [comment]
indeed the error massage was _snipeit_mac_address is not found when browsing the assets table i found it  mac_address  after renameing it the problem solved

thanks and sorry

**Comment by snipe** [comment]
Wait, what are you renaming? You should never ever rename columns manually in  Snipe-IT. If you saw that, you're running develop, as that's the format of custom fields.

**Comment by abdullahalasham** [comment]
Ok , well noted

**Comment by snipe** [comment]
You should change that field back and we can figure out whaty else you might have done wrong, or all kinds of other things may break and it will be nearly impossible to track them down. Did you run migrations when you upgraded? (Also be aware that you are running a development branch of Snipe-IT, which is by definition occasionally unstable.)
