### ISSUE TITLE
Feature request : request a consumables 

### ISSUE THREAD

**Issue by abdullahalasham** [snipe/snipe-it#1465]
i just don`t know whether the idea has been given before or not i would find it greate if users can request a consumables is it possible to added it to your road map?

kind regards

**Comment by adam-nelson** [comment]
What you want is a Internal IT shop?

**Comment by abdullahalasham** [comment]
indeed it is just to keep track of all consumables we purchased such as inks how they have been distributed and so all other units can request their consumables from the ICT Unit through the system
