### ISSUE TITLE
Default value for Company field

### ISSUE THREAD

**Issue by abdullahalasham** [snipe/snipe-it#1466]
noted in the recent versions that the company has been added in users, assets and other and the default value will be null while dealing with large data it is difficult to update each an every record individually is there a way the you add a company called default with id 1   which can renamed based on different users need and to be a default value for all items the company field has been added to.

kindly advise

**Comment by snipe** [comment]
I don't understand what you're trying to do here. If you only have one company, you don't need to use the company name field. It's not required.

**Comment by abdullahalasham** [comment]
that mean it is only applicable if more than one company that what i care  about thanks

**Comment by reggiejdean** [comment]
Can a company name be set as a default name when the user selects the company drop-down box?
