### ISSUE TITLE
Assets Showing "RTD" Instead Of "Assigned" In "Locations"

### ISSUE THREAD

**Issue by vcsalex** [snipe/snipe-it#1467]
Hello,

I am encountering an issue where assigned devices categorized as "Asset" are tallying under the "Assets RTD" column instead of the "Assets Assigned" column. This issue is not affecting assigned devices categorized as "Accessory". Here are some screenshots to show my situation.

Thanks,

Alex
<img width="724" alt="screen shot 2015-12-09 at 8 11 31 pm" src="https://cloud.githubusercontent.com/assets/16234773/11706835/6dd7e4a8-9eb1-11e5-8ce1-cf03596e7822.png">
<img width="802" alt="screen shot 2015-12-09 at 8 11 22 pm" src="https://cloud.githubusercontent.com/assets/16234773/11706833/6dd3f1f4-9eb1-11e5-9534-a18b9b03aab2.png">
<img width="599" alt="screen shot 2015-12-09 at 8 11 00 pm" src="https://cloud.githubusercontent.com/assets/16234773/11706834/6dd63842-9eb1-11e5-934b-24a33b51be44.png">

**Comment by vcsalex** [comment]
Hello,

This bug has evolved a bit. In v2.1.0-pre, the column header has changed from "ASSETS RTD" to "ASSETS RETIRED".

Thanks,

Alex

**Comment by snipe** [comment]
That was already fixed

**Comment by vcsalex** [comment]
Hello Snipe,

Thank you for fixing the column header. The asset status is still out of sync as I reported above on December 9th.

Thanks,

Alex
