### ISSUE TITLE
Not an issue - How to make a donation?

### ISSUE THREAD

**Issue by cantmz** [snipe/snipe-it#1468]
I had no idea where to post it.
I can't find on snipe-it website any way to make a donation for the great job you are doing.
Go for an hosted solution could be a way to support, but it involves creation of new supplier, invoices managing tasks for finance guys, managing payments and all related stuff my CFO will be more than happy to avoid.
I work for a multinational company and it will be easier to get a very expensive software/hardware/service from an old supplier than having the approval to create a new one in our ERP.
Furthermore an hosted solution will throw away the fun of playing around with snipe-it, lamp and so on.
If you didn't set up donation opportunity because you don't want/need/mind about it please discard my message.
Just to let you know we are appreciating your job not only by words.
I am not talking about a billion donation but even if a small one it would be something to give you a concrete thanks for you job and availabilty.

Many thanks.
Mirko

**Comment by kobie-chasehansen** [comment]
https://pledgie.com/campaigns/22899

**Comment by snipe** [comment]
Yep :)

**Comment by snipe** [comment]
(And thank you for asking, @cantmz - it's always nice to hear good stuff from people here, instead of just bug reports. :) )

![tenant-tyvm](https://cloud.githubusercontent.com/assets/197404/11811449/66cf14a0-a2ea-11e5-8049-6736e41c754b.gif)
