### ISSUE TITLE
page read for deploy is empty.

### ISSUE THREAD

**Issue by nbattista** [snipe/snipe-it#1470]
In the version 2.06, the page read for deploy when i select ,not return data but on the database there are a lot data.
i've activated log query on mariadb and this is the query :
select assets. from assets where assets.deleted_at is null and physical = '1' and assigned_to is null and (select count() from status_labels where assets.status_id = status_labels.id and deployable = '1' and pending = '0' and archived = '0' and status_labels.deleted_at is null) >= 1 order by asset_tag asc limit 100 offset 100
without offset the query show data
with offset the result is 0

the filter search filter not work on this version

**Comment by snipe** [comment]
Does your browser show any debug information?

**Comment by nbattista** [comment]
Here the screenshot in the debug mode : 
![debug mode](https://cloud.githubusercontent.com/assets/15670391/11779374/e7d0782c-a25a-11e5-8785-068a57e96047.png)

**Comment by snipe** [comment]
I'm looking for browser debug info, not the debug bar.

**Comment by snipe** [comment]
Also, how many assets do you have?

**Comment by nbattista** [comment]
I've 419 assets in distributed,20 in ready to deploy
First Screenshot : 
![Uploading first screenshot.png…]()
Second Screenshot : 
![second screenshot](https://cloud.githubusercontent.com/assets/15670391/11817982/f3107c98-a357-11e5-80b6-9ff39a3053e0.png)
with filter search i've result.
i've the same problem in these menu : 
Archived
Requestable


Thanks.

**Comment by snipe** [comment]
And your browser debug info?

**Comment by nbattista** [comment]
debug mode the application or my browser(ex : firefox)?
Actually the my browser isn't in debug mode.

**Comment by snipe** [comment]
Just show the developer tools in your browser, and show me what (if any) errors it shows when you load that page.

**Comment by nbattista** [comment]
screenshot : 
![2015-12-15 18_27_04-pronto per il rilascio asset __ gamenet it asset management](https://cloud.githubusercontent.com/assets/15670391/11818262/9f8eb858-a359-11e5-9f17-e7a4b2b6f455.png)

**Comment by snipe** [comment]
If you click on the sorting headers or the refresh button right above the table in the page when the page is blank, does anything change?

**Comment by nbattista** [comment]
no anything change :-(, with the older version i haven't this problem.

**Comment by snipe** [comment]
If you clear your cookies and load that page, does anything change?

What do you see when you go to `/api/hardware/list/RTD?`

**Comment by snipe** [comment]
Also, did you assign any of those assets (or yourself) to a company?

**Comment by nbattista** [comment]
Screenshot : 
![2015-12-16 09_10_43-whoops there was an error](https://cloud.githubusercontent.com/assets/15670391/11835591/0c44158a-a3d5-11e5-88a9-167b2c2ef6ca.png)
