### ISSUE TITLE
Unable to select Norwegian Krone (NOK) as currency

### ISSUE THREAD

**Issue by raumkraut** [snipe/snipe-it#1471]
In the online demo, I tried to create a new location which used the Norwegian Krone (NOK) as the currency. However, when going to "update location", the drop-down for the currency displays "SEK - Swedish Kronor".

From looking at the HTML, it seems that the currency select-box is indexed by the currency symbol ($, £, ¥, etc.). Since the Norwegian, Danish, and Swedish currencies all share the same symbol ("kr"), all three are marked as `selected="selected"`, and Firefox picks Swedish (being the last one in the list).
I don't know what is actually stored in the database for that location, but there's a 2/3 chance it's not the currency I selected!

Currencies have a pretty much guaranteed globally unique identifier - the three letter code (NOK, SEK, USD, etc.), so that is what should be used for the select-box's option values.

**Comment by ddreier** [comment]
@raumkraut that's a known limitation with the currencies at the moment. I think it's being worked on, but if it's not in the demo (which runs the most bleeding edge code) then it hasn't been implemented yet.

**Comment by raumkraut** [comment]
Good to know it's being looked at, thanks.
When you're evaluating the project for a company which does most of its business in Scandinavia, this issue is somewhat a negative! :)

**Comment by snipe** [comment]
@raumkraut - it doesn't really matter whether one is selected or three are selected. It only displays the currency symbol, it doesn't do any kind of exchange rate calculations.
