### ISSUE TITLE
Dummy data logic reversed?

### ISSUE THREAD

**Issue by nkabir** [snipe/snipe-it#1472]
This logic appears to do the reverse of what is intended:

```
$this->dummyData = ( strstr($dummydata, 'N' ) || empty($dummydata) ) ? true : false;

// Seed the tables with dummy data
if( $this->dummyData === true )
{
        $this->call('db:seed', array('--force'=>true));
}
else
{
        // Seeding Settings table is mandatory
        $this->call('db:seed', array('--class' => 'SettingsSeeder', '--force'=>true));
        // Seeding Statuslabels is strongly recommended
        $this->call('db:seed', array('--class' => 'StatuslabelsSeeder', '--force'=>true));
        // Seeding Categories is good to have
        $this->call('db:seed', array('--class' => 'CategoriesSeeder', '--force'=>true));
}
```

https://github.com/snipe/snipe-it/blob/develop/app/commands/AppCommand.php#L260

**Comment by dmeltzer** [comment]
Should this use stristr instead? "Y"/"Yes" is still a valid answer, correct--Ran into this issue earlier.

**Comment by snipe** [comment]
With default being N, I would assume that anything other than an explicit "y" should default to no. (This was a deliberate choice I made when pushing that update out.) If you make a mistake, you can still manually seed the database easily by running `php artisan db:seed`
