### ISSUE TITLE
Clicking "Generate Backup" from Admin panel directs to user profile 

### ISSUE THREAD

**Issue by brianjking** [snipe/snipe-it#1473]
![backup-snipe-error](https://cloud.githubusercontent.com/assets/6786817/11724084/85511984-9f37-11e5-83e2-0fbd8fdb0d8c.gif)

**Comment by snipe** [comment]
I think that's been fixed on develop already, as of a few weeks ago

**Comment by brianjking** [comment]
@snipe 2.0.6 is the current version. So I should see this fixed in the next release? If so, thanks a ton! Looks like 2.1.0 is coming out quite soon :+1:

**Comment by snipe** [comment]
Yep, this fix will be int he next release :)
