### ISSUE TITLE
License Totals

### ISSUE THREAD

**Issue by IceLitFire** [snipe/snipe-it#1474]
If you are entering multiple license orders for the same type of license, you have to tally them up manually or use Excel to extract totals.  Same-type licenses need a link to each other to provide cumulative totals in the License view and reporting.  Matching the license name could work but might get messy if not entered in uniform.

Perhaps having a simple "License Type" field that accepts a unique text string.  +1 for being able to quick add this on the create license screen and +2 for a typeahead drop-down for previous entries.

**Comment by thwr** [comment]
Facing the same issue. I think it would be a good idea to have a 1:n relationship as in AssetModels<->Assets.
