### ISSUE TITLE
Mysql connection error (500- internal server error)

### ISSUE THREAD

**Issue by brightonhouseholder** [snipe/snipe-it#1475]
When trying to access the application I get a 500 error, screenshot attached. when I tail /var/www/snipeit/app/storage/logs/log-apache2handler-2015-12-10.txt I get the following
'Next exception 'ErrorException' with message 'SQLSTATE[HY000] [2003] Can't connect to MySQL server on 'p1mysqlv0030.body.local' (13) (View: /var/www/snipeit/app/views/backend/layouts/default.blade.php) (View: /var/www/snipeit/app/views/backend/layouts/default.blade.php)' in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:47
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/snipei...', Array)
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/var/www/snipei...', Array)
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#6 /var/www/snipeit/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/snipeit/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /var/www/snipeit/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []'

I am running this on centos 6.7, using httpd as the web server, Php version 5.4.45, Mysql version 5.1.73. 

A little more info:
I am trying to connect this to a seperate mysql server as opposed to one local on the same machine. 
I have already granted the mysql user access to the db from the remote host. I figured it might be iptables causing issues, I have shut it down completely (on the mysql server) and can successfully connect from the machine the app is running on to the mysql server with no problem, I can also connect using telnet on port 3306. All the proper php extensions are installed. I am stumped on this one because when I ran  'php artisan app:install --env=production' it was successfully able to seed the db with external data, yet when I try to view the app in a browser, I have the 500 error and it throws the above error in the logs. Any help appreciated.

<img width="1001" alt="screen shot 2015-12-10 at 4 26 08 pm" src="https://cloud.githubusercontent.com/assets/16247685/11731719/cbac6a5a-9f5a-11e5-8ea4-971f010327c7.png">

**Comment by snipe** [comment]
Are you running SELinux?

**Comment by snipe** [comment]
http://stackoverflow.com/questions/4078205/php-cant-connect-to-mysql-with-error-13-but-command-line-can

**Comment by brightonhouseholder** [comment]
Ah, yes that was the problem. My apologies, I missed that in the setup guide. This issue can be closed, Thank you!
