### ISSUE TITLE
accept asset notification mail issue

### ISSUE THREAD

**Issue by chenboshiun** [snipe/snipe-it#1476]
Hello:

User has received Snipe-IT Confirm asset delivery Mail, To confirm asset, User can clieck "I have read and agree to the terms of use, and have received this item." in Gmail Inbox, but redirect URL address occur error

![screen shot 2015-12-11 at 2 24 20 pm 2](https://cloud.githubusercontent.com/assets/5372796/11737795/c35b815c-a017-11e5-8e4f-01a32a5ddfaf.png)

![screen shot 2015-12-11 at 3 02 37 pm 2](https://cloud.githubusercontent.com/assets/5372796/11737854/4a7a84a8-a018-11e5-86de-1512682923c0.png)

correct redirect URL is https://snipe-it.corp/account/accept-asset/17 

but actual redirect URL is https://snipe-it..corp/account/accept-asset/17 <- this's error URL

How can solve this issue, thanks.

**Comment by snipe** [comment]
Check the URL in app/config/production/app.php. My guess is that you have a typo in the URL there

**Comment by chenboshiun** [comment]
Sorry, typo error in app/config/production/app.php.

thanks.
