### ISSUE TITLE
Barcode error

### ISSUE THREAD

**Issue by egaMage** [snipe/snipe-it#1477]
Please assist, I've been trying to migrate snipeit the entire day, even moved to a new server, deleted the lock file, ran all the composer commands, did everything I could find online, copied across my app.php etc etc but I am stuck at this and can not get passed it :+1:  PHP Fatal error:  Class 'Dinesh\\Barcode\\BarcodeServiceProvider' not found in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 157, referer: http://192.168.0.231/snipeit/public/auth/signin

Please help, I don't know what to do anymore, i've tried uncommenting those lines, but it just breaks more stuff than anything else... 

Where can I find that Class Dinesh Barcode and how do I install it?

**Comment by snipe** [comment]
Did you search the closed issues and clear the composer cache?

**Comment by egaMage** [comment]
Hey , I searched all the issues and people just said they deleted composor.lock and re-ran the composer.phar install / update commands. I did all of it, no matter what I do, it keeps throwing that error. Besides that, it's a brand new install with the installation script, how can it still be complaining about the Barcode when it's supposed to have been fixed / removed in latest version?

The only old thing I have , this is in my app.php | 'Dinesh\Barcode\BarcodeServiceProvider' 
As we use the barcode functionality, however it keeps giving Fatal error because of it.

Any idea if i'm missing a package or module or something?

 [client 192.168.0.138:52146] PHP Fatal error:  Class 'Dinesh\\Barcode\\BarcodeServiceProvider' not found in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 157, referer: http://192.168.0.231/snipeit/public/auth/signin

**Comment by snipe** [comment]
You need to use the updated app.php. That's why there is no example version of it. It contains things that are critical to the app.

**Comment by egaMage** [comment]
The updated app.php doesn't really have much in it, and the old one has
most of my configs, modules. Besides as soon as I use the new app.php it
doesn't allow me to login to Auth and just throws a bunch of different
errors.. Would you like to see those?

**Comment by snipe** [comment]
The app/config/app.php that ships with Snipe-IT only has two config options that matter, timeline and language. You have to use the one that ships with it or the app won't work.

**Comment by snipe** [comment]
*timezone, not timeline

**Comment by egaMage** [comment]
Hey again and thanks for the responses!

So, I copied the app.php from /app/config/app.php to
/app/config/production/app.php...  I get to the auth screen, and after
trying to login just Error 500 - internal server error.

The logs aren't saying anything though. Any ideas?

**Comment by ddreier** [comment]
@egaMage that's not what @snipe was saying to do. You need to get a clean copy of `/app/config/app.php` from the repo (or the zip file you downloaded) and put it in place. Then you can adjust the settings in it. `/app/config/app.php` and `/app/config/production/app.php` are not interchangable.

**Comment by egaMage** [comment]
Great thank you Daniel, I'll definitely try that. Then, just a random
question. Do you guys perhaps know how to change the $ sign into a Rand
sign ( R ) on snipeit as that is our currency in south afirca.

**Comment by egaMage** [comment]
Hey guys,

I finally got the app to work, thank you very much for all the help. What I
did was git checkout snipeit from scratch, then just copied app.example.php
to app.php in config/production/ , edited the site name etc , did the
database.php as well. And restored my old database over this one. Then ran
the following commands :

php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan migrate

Now, my next question is. We are able to download TXT files etc now of
the assets, but the "Download CVS' keeps going to Internal 500 server
Error page.

And when you try to save the admin config it does the same. Any ideas?

**Comment by snipe** [comment]
Where are you seeing the "Download CSV" link? Can you show me a screenshot?

**Comment by snipe** [comment]
Also, you need to turn debugging on if we're to help you. A 500 error doesn't tell us anything. We need detailed error messages.

**Comment by egaMage** [comment]
Hey,

I am seeing the Download CSV when I click on "asset report" under "reports"
( http://puu.sh/lWpdc/2872246206.png ).

Then, the 500 internal server error ACTUAL errors , please click on puuush
link to get error.zip of all the errors when activating debug mode from
config/production/app.php

http://puu.sh/lWpMB/4b163569c1.zip

**Comment by snipe** [comment]
Please just paste the errors here, or include a screenshot. I don't want to download a zip file with HTML in it.

Did you manually delete any locations from the database?

**Comment by DawnTan0321** [comment]
How to solve the problem of timezone when upgrading?
![screenshot from 2017-03-09 17 49 13](https://cloud.githubusercontent.com/assets/25975267/23745599/b906cdaa-04f3-11e7-8c0e-dd24aab34c21.png)
![screenshot from 2017-03-09 17 57 08](https://cloud.githubusercontent.com/assets/25975267/23745605/bc9e0334-04f3-11e7-95ca-6d656c339732.png)

**Comment by DawnTan0321** [comment]
when I check the timezone infomation in app.php,it shows:
![screenshot from 2017-03-09 18 18 14](https://cloud.githubusercontent.com/assets/25975267/23745891/ed0e0e96-04f4-11e7-9bf6-cccee1c6a2a1.png)

**Comment by DawnTan0321** [comment]
I modify the timezone to America/Denver, but it will change to the original value automatically.

**Comment by snipe** [comment]
You should never change the files in the config directory, as they'll only get overwritten when you upgrade. Time zone should be set in your .env file. https://snipe-it.readme.io/docs/configuration#section-required-basic-app-settings

**Comment by snipe** [comment]
You may also need to update your php.ini to include a default system timezone. http://php.net/manual/en/datetime.configuration.php

**Comment by DawnTan0321** [comment]
OK Thanks
