### ISSUE TITLE
LDAP Sync Error.

### ISSUE THREAD

**Issue by JExactly** [snipe/snipe-it#1479]
LDAP Sync has been working fine, All of a sudden I am getting a Sync Error and it's giving me the attached error.
![snipeit_ldap_error](https://cloud.githubusercontent.com/assets/14076881/11751485/bd920670-a007-11e5-9a39-85158848711f.png)

Any Ideas on where I can start to troubleshoot this? I have Checked my LDAP.php Config, nothing has changed. Verified the user account has access to LDAP. I appreciate anyones assistance with this.

**Comment by uberbrady** [comment]
It sounds to me like you're missing the php-ldap extension, I think? Either that or we need to refer to it as:

```@\ldap_connect($url);``` which seems unlikely; we would've heard about that before.

Anything else change recently?

**Comment by JExactly** [comment]
You know, I just went into my PHP extensions and it appears that my ldap module got disabled... I am not sure how that happened. Now I feel like a noob. Thanks for making me think about the PHP extension. Unfortunately I am currently running this is IIS, and I am not a fan.

Again Thanks and This is now working again.
