### ISSUE TITLE
How to handle 1 to 1 licsence tracking

### ISSUE THREAD

**Issue by fjanmohamed** [snipe/snipe-it#1480]
Hi,
First off id like to say I really like the software and am impressed with whats been done so fr with it,
Is there any way to have multiple one use licenses stored under a single entry and be able to link each individual license to a user, so far my temporary solution is to either have multiple entries each storing a single license (which looks very cluttered at first glance, and second glance lol) or have multiple license keys assigned into a single entry and give each license out based on corresponding seat number, but this would just be a visual link and prone to lots of human errors.
Thank you.

**Comment by SylentBobNJ** [comment]
+1 This is similar to a request I was going to put in, but I'll just vote this up instead.  As I'm getting acquainted with the product and how to adopt it into our workflow, one thing that seems unwieldy at the moment is license assignment.  We have several licensed products that we deploy to our users, many of them are deployed to all our users.  It would be handy to 'bundle' licenses into a package, of sorts, perhaps associated with roles or positions, that we could check out to users when installing new hardware.  
For example:  A Staff Accountant might receive one Windows Enterprise, one Office Standard, one CCH Practice Management, one CCH Engagement, one Adobe Acrobat Standard, one PPC Single Audit Tools, one Quickbooks Enterprise, one antivirus and one Labtech Client license.  They wouldn't need to appear as a single package in the licenses page, but they could be 'checked out' as one, then each individual license would be assigned to the user.
I'd imagine this kind of bundling could also be applied to assets and accessories as well, to provide a sort of 'starter kit' for new deployments.

**Comment by afield1235** [comment]
+1 
I used another asset program and recently switched over to this. It had the ability to mass/bulk update licenses to users to make bulk assignment pretty easy and also the ability to add one Software Item like "Adobe Pro 12" and then add the individual licenses underneath. If it was volume you would simply add a volume license and assign it to everyone. If you had 40 licenses, you would add each under the "Adobe Pro 12" Software item and then individually link the licenses to the users.
