### ISSUE TITLE
Does SnipeIT support handheld barcode scanners?

### ISSUE THREAD

**Issue by tmongero** [snipe/snipe-it#1481]
I'm currently migrating an inventory system to SnipeIT and I'm wondering if we would be able to quickly find assets by scanning the barcode of the asset tag using a handheld barcode scanner that plugs into a MacBook via USB.

Is this supported by SnipeIT in its current state?

**Comment by ddreier** [comment]
Snipe-IT has built in support for generating QR codes for each asset. If you enable QR codes in the Settings (Admin->Settings) the barcode will show up on each asset page, and you can generate a sheet of labels by selecting one or more assets in a list and choose the "Generate Labels" option.
![image](https://cloud.githubusercontent.com/assets/82290/11790338/dd879df4-a260-11e5-9010-c02952521c3c.png)

(You can also generate "normal" barcodes, but they're huge)
