### ISSUE TITLE
[Issue] Asset Tag auto-incremental

### ISSUE THREAD

**Issue by Robert-Azelis** [snipe/snipe-it#14829]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

In system is setup Asset Tag format AA-xxxxx  (5 digits) started from 01000.
During create new asset, system auto-increment tag number and provide AA-01000, that is ok.
But, user can use some custom tag number and if use AA-21001, then in system setting is also changed next incremental number to 21002, so it's break numbering, especially if someone will use custom tag number like AA-999999999999999
It also affect for security aspect of system , as regular user is able without admin permission changed system setting of tag numbering.

### Reproduction steps

1. Create new asset, tag number is provided automatically on the base Asset Tag system setting format, like AA-01000, Save new asset.
2. Create new asset, tag number is provided automatically AA-01001, change number to AA-21001, Save new asset.
3. Create new asset, tag number is provided automatically with new number AA-21002, that means system setting of incremental numbering has been changed, Save new asset.

### Expected behavior

System should keep numbering format - incremental and allow to use user custom numbering, but if is detected system format should be pop up error message that cannot change system numbering setting and ask to use other custom tag number or keep tag number generated by system.

### Screenshots

![image](https://github.com/snipe/snipe-it/assets/82208283/d78b7375-76ac-4a60-9b9d-bb2ad3c4e804)

### Snipe-IT Version

6.4.2

### Operating System

Windows

### Web Server

IIS

### PHP Version

8.1

### Operating System

Windows

### Browser

Google Chrome, MS Edge

**Comment by snipe** [comment]
I don't think this is feasible tbh, as it would potentially mangle a lot of people's workflows. Some folks use serial numbers as assets tags (which, hey, I wish they wouldn't, but some people do.) We've tried to mitigate this in https://github.com/snipe/snipe-it/pull/14816 but this seems more like an administrative control versus something that makes sense for us to fix.
