### ISSUE TITLE
Bug when generating backups, most likely due to running on Windows?

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#1483]
Testing latest DEV

After clicking the generate dump button the browser waits a few seconds and then throws this error
![image](https://cloud.githubusercontent.com/assets/10247644/11802299/5a1f9888-a2bd-11e5-9237-b03020581dc3.png)

Confirmed file does exist
![image](https://cloud.githubusercontent.com/assets/10247644/11802345/affb28da-a2bd-11e5-8a99-30f7324aaffe.png)

**Comment by snipe** [comment]
Duplicate? https://github.com/snipe/snipe-it/issues/1337#issuecomment-158143184

**Comment by kobie-chasehansen** [comment]
yeah was looking at that but i'm not sure, I was thinking unrelated due to the fact my dump was actually being created. Will play around with it some more.

**Comment by kobie-chasehansen** [comment]
went thru #1337 and I don't think this error is related.

**Comment by snipe** [comment]
Any updates from your side, @kobie-chasehansen?

**Comment by abdullahalasham** [comment]
i am not  sure but i think the following issue #1436 is some what related ..

**Comment by vabue** [comment]
Similiar issue on windows:
```
C:\xampp\htdocs\snipe>php artisan snipeit:backup
[0;31m
Database backup failed. The filename, directory name, or volume label syntax is incorrect.

[0m



  [InvalidArgumentException]
  The "C:\xampp\htdocs\snipe\app\storage/dumps/2016030984143-db.sql" directory does not exist.



snipeit:backup
```

**Comment by snipe** [comment]
Is this still an issue? Pretty sure at least a few Windows users have gotten this working.
