### ISSUE TITLE
500 error when run wizard

### ISSUE THREAD

**Issue by ruslyislam** [snipe/snipe-it#14837]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

i started installing snipe IT on almalinux. but in last step when need run a wizard  iget 500 server error. why?

### Reproduction steps

1.no steps
2.
3.
...
no steps

### Expected behavior

can install 

### Snipe-IT Version

latest i think

### Operating System

almalinux

### Web Server

httpd

### PHP Version

8.2

### Error messages

```shell
500 server error
```

### Additional context

fresh install

**Comment by snipe** [comment]
Snipe-IT v6 doesn't work on PHP8.2, as mentioned in the requirements documentation. v7 comes out on Monday, and you should be able to run that on 8.2.
