### ISSUE TITLE
Import status labels

### ISSUE THREAD

**Issue by unbkbl** [snipe/snipe-it#1484]
Hi!

I wonder if there is a way to import the Status labels as a column in the CVS file.

Thanks for your time in advance

**Comment by snipe** [comment]
Hi - that's not currently possible. Right now, if there is a user included with the record, it will be deployed to them. If not, it will be set as Ready to Deploy.  You can then use the bulk edit functions to update your Ready to Deploy statuses to something else if needed.

**Comment by unbkbl** [comment]
I'll split my CVS in several pieces and use the bulk edit functions in the meantime. 

Thanks Snipe!
