### ISSUE TITLE
How to Install Snipe IT in Windows Server 2012 by using Xammp and configure

### ISSUE THREAD

**Issue by mahesh2471990** [snipe/snipe-it#1486]
XAMMP instaling and Composer Menu installing i finished by refering below link.
https://github.com/snipe/snipe-it/issues/290.

My question is after above given link setup done. How to host site. I am new newbie in php. I would like to @madd15 help me out from this.

**Comment by mahesh2471990** [comment]
@snipe php artisan app:install --env=production this command is run successfully.
what is next i configure IIS below there is snapshot. after what to do i am stuck @madd15 
![capture](https://cloud.githubusercontent.com/assets/16305213/11832756/e4c3ec9e-a3e1-11e5-866b-6ec413da7c87.JPG)

**Comment by mahesh2471990** [comment]
@snipe @madd15 i dont know how its working now.. But i removed IIS things.. Directly gave locahost.. its working..
Next Plan to Configure LDAP... 
Can any one tell how Change the Homage of Snipe IT. Locally.
For example when we Open localhost. The Snipe Dasboard appears.
I was Planing to add Our Comapany Name in front  xxxx SNIPE IT ASSET MANAGEMENT. xxxx wil be my compnay name. Can we do that

**Comment by remkodalhuisen** [comment]
@snipe @madd15 can you explain in detail what you did to make to IIS part working.
I followed all the steps in the Snipe-IT documentation, trying to get it running on Server 2012-R2 and IIS.
All the steps looked oke. But when browsing the website, I get: "This page can't be displayed"

**Comment by Norwun** [comment]
I had a problem with "The page cannot be displayed" message and fixed it by deleting the first imported rule. See link: https://github.com/snipe/snipe-it/issues/1125

**Comment by mahesh2471990** [comment]
@remkodalhuisen I using Xammp.. Using that i configured. When u use Xammp. there is not need to configure with ISS. Above image which i posted. I did the Configuration as per doc. Later on i came to know by using Xammp. we no need to Configure IIS. So i removed all the configuration. I mean deleted sites which i added. and its working fine.. All about to configure in Xammp directory
@snipe U can close this case. Now i am to access Snipe It assets management local site. Only i asked u how add a name in homage banner. Can we do that.??

**Comment by saopramod** [comment]
Hi Mahesh @mahesh2471990 I am facing problem with Composer Install, I am trying to setup snipe-it on Xampp on Windows 2008 Server. Please help @snipe 

Below is the log I get while I do the command - composer install

C:\xampp\htdocs\snipe-it>composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing symfony/event-dispatcher (2.8.x-dev 0ef7669)
    Downloading: 100%
    Downloading: 100%
    Downloading: 100%
    Failed to download symfony/event-dispatcher from dist: The "https://api.gith
ub.com/repos/symfony/EventDispatcher/zipball/0ef7669c0af9f62752a96a5d43c1b13c5c2
e70e9" file could not be downloaded: SSL operation failed with code 1. OpenSSL E
rror messages:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify faile
d
Failed to enable crypto
failed to open stream: operation failed
    Now trying to download from source
  - Installing symfony/event-dispatcher (2.8.x-dev 0ef7669)
    Cloning 0ef7669c0af9f62752a96a5d43c1b13c5c2e70e9


  [RuntimeException]
  Failed to clone https://github.com/symfony/EventDispatcher.git, git was not
   found, check that it is installed and in your PATH env.
  'git' is not recognized as an internal or external command,
  operable program or batch file.


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-p
lugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress
] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative]
 [--ignore-platform-reqs] [--] [<packages>]...


C:\xampp\htdocs\snipe-it>composer install --prefer-source --no-interaction
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing symfony/event-dispatcher (2.8.x-dev 0ef7669)
    Cloning 0ef7669c0af9f62752a96a5d43c1b13c5c2e70e9
    Failed to download symfony/event-dispatcher from source: Failed to clone htt
ps://github.com/symfony/EventDispatcher.git, git was not found, check that it is
 installed and in your PATH env.

'git' is not recognized as an internal or external command,
operable program or batch file.

    Now trying to download from dist
  - Installing symfony/event-dispatcher (2.8.x-dev 0ef7669)
    Downloading: 100%
    Downloading: 100%
    Downloading: 100%


  [Composer\Downloader\TransportException]
  The "https://api.github.com/repos/symfony/EventDispatcher/zipball/0ef7669c0
  af9f62752a96a5d43c1b13c5c2e70e9" file could not be downloaded: SSL operatio
  n failed with code 1. OpenSSL Error messages:
  error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify
  failed
  Failed to enable crypto
  failed to open stream: operation failed


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-p
lugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress
] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative]
 [--ignore-platform-reqs] [--] [<packages>]...


C:\xampp\htdocs\snipe-it>
