### ISSUE TITLE
[Feature request] Show asset names and add search bar in requestable assets view page.

### ISSUE THREAD

**Issue by laopangzi** [snipe/snipe-it#1487]
Hi, Guys.
I work in an IT company and we have a lot devices to develop.Many of them have different specifications,but same model name,so we need to know their asset name to distinguish them.
Because of device quantity,the requestable assets view page is a bit too long,can you separate them into serveral pages,and add a search bar to search certain ones.
At last,can the accessories be requestable?

**Comment by snipe** [comment]
These are two different requests, and should be filed separately in the future to help us keep track.

Which view are you referring to? /hardware?status=Requestable should show you requestable assets with a search bar and pagination.

**Comment by laopangzi** [comment]
Sorry,I didn't say it clearly,I mean the /acccount/requestable-assets page for normal user.

**Comment by laopangzi** [comment]
Can I got an email when users request an asset?

**Comment by roycepope** [comment]
Sorry to comment on a super old feature request but has there been any enhancements to this? possibly in v3? It would be nice to have more than just Model, Serial, and Location displayed the End User on the Requestable Assets user page.
<img width="469" alt="requestable_assets" src="https://cloud.githubusercontent.com/assets/3598120/15026899/a19237fa-11f5-11e6-95e5-132505a91f71.png">
