### ISSUE TITLE
How to get support custom fields?

### ISSUE THREAD

**Issue by BlackGrizzly** [snipe/snipe-it#1488]
How to get support custom fields?
I get last version (for some reason 2.0.5-pre), but I not see custom fields in administration menu

**Comment by laopangzi** [comment]
Upgrade to 2.0.6

**Comment by BlackGrizzly** [comment]
How? I can understand? 
I run: php composer.phar install
Ans: Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

But in control panel I see v2.0.5-pre version. 
What am I doing wrong?

**Comment by laopangzi** [comment]
When I install with the release package v2.0.6,I got 2.0.5-pre too.
Then I use git clone the master branch and installed, I got 2.0.6.
Sorry about my English,do you understand what I mean?

**Comment by BlackGrizzly** [comment]
If comparering branch there are develop is up to date with all commits from master. 
https://github.com/snipe/snipe-it/compare/develop...master?expand=1

How to clone master branch?

**Comment by laopangzi** [comment]
Sorry,my fault.
I thought it's master branch,but it's not,it's develop.
I just run the command `git clone https://github.com/snipe/snipe-it local-snipe-it-folder`,
then installed step by step.
Didn't see time out on my computer.

**Comment by BlackGrizzly** [comment]
I install 2.0.6-14, but I don't see custom fields

**Comment by BlackGrizzly** [comment]
All was removed. Installed again. Version 2.0.6-14. Custom fields no!
Help!

**Comment by laopangzi** [comment]
Mine is 2.0.6-103,custom field setting is in administrator menu, the one above settings.

**Comment by BlackGrizzly** [comment]
screenshot: http://www.imageup.ru/img108/2304716/shipe-it.png.html
how to get 2.0.6-103?

**Comment by BlackGrizzly** [comment]
I did it!
