### ISSUE TITLE
develop and master branch fails on fresh install

### ISSUE THREAD

**Issue by swoopdk** [snipe/snipe-it#1491]
Today i tried a brand new fresh clone of the master and develop branches. Totally fresh directory and did a clone from each. Did the docker build process and got the following error when running the install script 

```
=====================================

  Step: 2

    Preparing your Application

-------------------------------------

Application key [CrteWPROGAL2nkrpglCZGcKjCRTnef26] set successfully.
Migration table created successfully.
Migrated: 2012_12_06_225921_migration_cartalyst_sentry_install_users
Migrated: 2012_12_06_225929_migration_cartalyst_sentry_install_groups
Migrated: 2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot
Migrated: 2012_12_06_225988_migration_cartalyst_sentry_install_throttle



  [ErrorException]
  Trying to get property of non-object



app:install
``` 

It's a brand new install with an empty database so shouldnt present any problems.

**Comment by swoopdk** [comment]
And with the older docker_enhancements branch i can do a successful fresh install with no trouble. So must be some bug. Either in the Dockerfile build process or some other part of the Develop and Master branches.

**Comment by snipe** [comment]
Can you give us a little more to work with? What's in your app error logs? "Trying to get property of non-object" doesn't help us too much.

**Comment by swoopdk** [comment]
Here is what logs i can find under app/storage/logs

``` 
cat log-cli-2015-12-17.txt
[2015-12-17 14:13:04] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/html/app/database/migrations/2015_11_26_195528_import_ldap_settings.php:21
Stack trace:
#0 /var/www/html/app/database/migrations/2015_11_26_195528_import_ldap_settings.php(21): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/html/a...', 21, Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(135): ImportLdapSettings->up()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(111): Illuminate\Database\Migrations\Migrator->runUp('2015_11_26_1955...', 2, false)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(82): Illuminate\Database\Migrations\Migrator->runMigrationList(Array, false)
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php(70): Illuminate\Database\Migrations\Migrator->run('/var/www/html/a...', false)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(112): Illuminate\Database\Console\Migrations\MigrateCommand->fire()
#6 /var/www/html/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(128): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/app/commands/AppCommand.php(96): Illuminate\Console\Command->call('migrate', Array)
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(112): AppCommand->fire()
#11 /var/www/html/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php(889): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(AppCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/vendor/symfony/console/Symfony/Component/Console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/artisan(59): Symfony\Component\Console\Application->run()
#17 {main} [] []
``` 
cat log-apache2handler-2015-12-17.txt
[2015-12-17 14:12:34] production.ERROR: exception 'ErrorException' with message 'mcrypt_encrypt(): Size of key is too large for this algorithm' in /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:78
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'mcrypt_encrypt(...', '/var/www/html/v...', 78, Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(78): mcrypt_encrypt('rijndael-256', 'Change_this_key...', 's:40:"760758695...', 'cbc', '??`8/?g<??^??>?...')
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(57): Illuminate\Encryption\Encrypter->padAndMcrypt('760758695627f0e...', '??`8/?g<??^??>?...')
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(118): Illuminate\Encryption\Encrypter->encrypt('760758695627f0e...')
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Guard->encrypt(Object(Illuminate\Http\RedirectResponse))
#5 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#7 /var/www/html/public/index.php(49): Illuminate\Foundation\Application->run()
#8 {main} [] []
```

**Comment by swoopdk** [comment]
I tried on multiple combinations including two versions of mysql, and even following instructions on the docker snipeit page verbatim with same result. Seems to be in the installer there is a bug because using an already installed database and simply running a migrate on that worked. However i have only done this once and not with the purposes of testing. 

Discovered the bug while setting up a dev environment for myself so didnt see it in my production environment.

**Comment by swoopdk** [comment]
Okay now that i have fresh eyes and read the logs myself i see the issue is when you have a ENV file with LDAP settings. Don't see why though, but assuming it's something to do with the import of LDAP settings from the config that fails somehow.

Of course in the case of Docker we still need to be able to set the LDAP settings from ENV file to be able to destroy a container and spin up a new one without any trouble and manual config :)

**Comment by swoopdk** [comment]
Just confirmed.. install works just fine if i have no LDAP variables set upon the installer. So thats where to look for the bug ;) Hope that helps :)

**Comment by uberbrady** [comment]
@swoopdk  - the 'new' way that LDAP settings are configured is by the database; the environment variables don't make sense anymore.

What I've done instead is removed the LDAP setting stuff from the env-file - though I'm curious to hear how the new database-powered LDAP settings get along with some of the older LDAP Things that we had in the various config files.

You'll have to check it out and let us know how it looks...
