### ISSUE TITLE
Unable to delete user completely

### ISSUE THREAD

**Issue by swoopdk** [snipe/snipe-it#1493]
I know this might be some design decision but in either case there is a bug. 

If i delete some users they dissapear and of course end up under the "show deleted users" page. 
However here i still have the option of pressing delete.I was expecting this to fully delete the user however it didnt' work. I get a confirmation popup asking if i'm sure and then this error
```
 Error: User [4] does not exist.
``` 

So either it should be possible to delete completely ( i hope this as we are syncing with LDAP and the one way sync apparently does nothing with users deleted and modified in the snipe-it setup thus only good for an initial sync and adding new  users). 
If it's not possible then the delete buttons should be removed from the "show deleted users" view.

I was using the latest image from dockerhub when i found this bug.

**Comment by mahesh2471990** [comment]
@snipe Same issue here if we delete single user from SHOW DELETED USER Bellow error 

![error](https://cloud.githubusercontent.com/assets/16305213/12017131/fbe0b632-ad78-11e5-83de-2c02c7e30ade.JPG)

@snipe. Help us by this issue.. If we process Bulk Delete from Deleted user

![error3](https://cloud.githubusercontent.com/assets/16305213/12017139/136dc8bc-ad79-11e5-8a56-361b141ee655.JPG)



After we click submit also below error

![error4](https://cloud.githubusercontent.com/assets/16305213/12017159/5d41126e-ad79-11e5-87d7-981b984114df.JPG)

all work has been stoped snipe..

**Comment by mahesh2471990** [comment]
Bulk Delete GO error (I did bulk del in Show Deleted User Following error occur

![bulk deljpg](https://cloud.githubusercontent.com/assets/16305213/12051159/57023c68-af25-11e5-9abc-38e9a08a2839.JPG)

**Comment by snipe** [comment]
@swoopdk the delete button has been removed from the deleted users page on develop

**Comment by daften** [comment]
The delete action is there for deleted users in v3.  It now gives a "Whoops, looks like something went wrong." error page. Is this on the roadmap to fix this, or to remove the delete button there too? :)

To explain: in v2 on LDAP import, it didn't update users for us, but created new ones for deleted users. On v3 it seems it does work properly for updating (at least for active users).

**Comment by dmeltzer** [comment]
Where are you seeing the delete button on deleted users? (I can't find it).   Also, there is a now a "purge" command to purge all soft deleted records.  It doesn't support granularity about which type of records to purge at the moment though, so use it with care.

**Comment by daften** [comment]
Go to People -> Show deleted user -> Click on a user's name -> Actions (top left almost) -> Delete :)

I can't see the Purge command in the UI, is it via artisan?

**Comment by dmeltzer** [comment]
I just submitted a PR that should solve this (Hides the delete again).  It's because the same view is used for deleted and non deleted users, and the action wasn't hidden conditionally.

**Comment by daften** [comment]
Thanks @dmeltzer :)
For the users stumbling here, the purge is indeed an artisan command.

**Comment by dmeltzer** [comment]
Purge is available via artisan or via the admin->settings page.
