### ISSUE TITLE
MAC Address Field is not saving

### ISSUE THREAD

**Issue by Norwun** [snipe/snipe-it#1494]
Hello, I am running v2.0.6-11.  When I create or edit an Asset and enter a MAC address in the field, it does not save to the assets table. The field will stay blank when I view or edit the asset.  

If I manually enter the data into the table then the information will show up.

Any help is appreciated.  Thanks.

**Comment by JohKa** [comment]
I can confirm that. We are using the same version.

**Comment by snipe** [comment]
Are you able to reproduce this on the demo?

**Comment by Norwun** [comment]
Yes, I just tried it earlier on the demo.

On Dec 17, 2015, at 6:09 PM, snipe <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you able to reproduce this on the demo?

—
Reply to this email directly or view it on GitHub<https://github.com/snipe/snipe-it/issues/1494#issuecomment-165611124>.



Norman Lee

IT Administrator

200 Varick Street, New York , NY 10014

T:212-805-7705 F:212-805-7445

[cid:image090b0c.PNG@9c6a91c0.4aa13887]<http://www.merkleyandpartners.com>[cid:imaged81822.PNG@ac220bf5.46acd5c0] [cid:image53a5ff.PNG@37143e04.42b88b0f] <https://www.facebook.com/MerkleyandPartners>  [cid:imagedec5e8.PNG@e2da4d32.4eb50e07] <http://twitter.com/merkleypartners>



This email is intended only for the person or entity to which it is addressed and may contain information that is privileged, confidential or otherwise protected from disclosure. Dissemination, distribution or copying of this e-mail or the information herein by anyone other than the intended recipient, or an employee or agent responsible for delivering the message to the intended recipient, is prohibited. If you have received this e-mail in error, please immediately notify us by calling our Help Desk at (212) 805-7400, or e-mail to helpdesk@merkleyandpartners.com.



Please consider the environment before printing this e-mail.

**Comment by snipe** [comment]
Please try on the demo again. We have two demos now, master and develop. 

https://snipeitapp.com/demo

**Comment by snipe** [comment]
demo.snipeitapp.com is the master branch. develop.snipeitapp.com is the develop branch.

**Comment by Norwun** [comment]
Just tried it on the demo again. Same results. The MAC address field is not saving whatever is entered into it through the form. It's as if the form isn't posting what is in the MAC Address field into the database table.

**Comment by snipe** [comment]
Which demo? demo.snipeitapp.com or develop.snipeitapp.com?

**Comment by Norwun** [comment]
The master one. I am having trouble finding the show MAC address checkbox in the Asset Models in develop.snipeitapp.com<http://develop.snipeitapp.com>.

On Dec 17, 2015, at 7:53 PM, snipe <notifications@github.com<mailto:notifications@github.com>> wrote:


Which demo? demo.snipeitapp.com<http://demo.snipeitapp.com> or develop.snipeitapp.com<http://develop.snipeitapp.com>?

—
Reply to this email directly or view it on GitHub<https://github.com/snipe/snipe-it/issues/1494#issuecomment-165627099>.



Norman Lee

IT Administrator

200 Varick Street, New York , NY 10014

T:212-805-7705 F:212-805-7445

[cid:image452e4a.PNG@b13bf18d.429f6f31]<http://www.merkleyandpartners.com>[cid:image7f0d2b.PNG@49f6e1e1.4ba47768] [cid:image190335.PNG@0e8a6a41.4db72eee] <https://www.facebook.com/MerkleyandPartners>  [cid:image7cb1c9.PNG@d9076202.43a43dc6] <http://twitter.com/merkleypartners>



This email is intended only for the person or entity to which it is addressed and may contain information that is privileged, confidential or otherwise protected from disclosure. Dissemination, distribution or copying of this e-mail or the information herein by anyone other than the intended recipient, or an employee or agent responsible for delivering the message to the intended recipient, is prohibited. If you have received this e-mail in error, please immediately notify us by calling our Help Desk at (212) 805-7400, or e-mail to helpdesk@merkleyandpartners.com.



Please consider the environment before printing this e-mail.

**Comment by Norwun** [comment]
Awesome, thanks!

**Comment by snipe** [comment]
Mac address is removed in the develop branch, replaced by custom fields, so don't get too attached to it.

**Comment by Norwun** [comment]
Got it. The Custom Fields would work even better for us.
