### ISSUE TITLE
Coding of log on dashboard 

### ISSUE THREAD

**Issue by BlackGrizzly** [snipe/snipe-it#1495]
Russian language. general.php file in UTF-8. 
But in log on dashboard Action column displays in a wrong encoding (in Russian language).
In all other places the translation is displayed correctly

**Comment by snipe** [comment]
I don't understand what you mean. Can you show a screenshot please.

**Comment by BlackGrizzly** [comment]
English http://www.imageup.ru/img43/2305207/eng.png.html
Russian http://www.imageup.ru/img43/2305209/rus.png.html

**Comment by snipe** [comment]
So not wrong encoding, wrong language?

**Comment by BlackGrizzly** [comment]
what does it mean?

**Comment by snipe** [comment]
...

**Comment by snipe** [comment]
I don't see any encoding issues on those screenshots.

**Comment by BlackGrizzly** [comment]
http://www.imageup.ru/img109/2322936/rus-1.png.html
