### ISSUE TITLE
Can not modify asset model.

### ISSUE THREAD

**Issue by laopangzi** [snipe/snipe-it#1496]
When I modify the asset model,it shows me that the asset model name is already exists.

**Comment by snipe** [comment]
Do you have the very latest from develop?

**Comment by laopangzi** [comment]
Version 2.0.6-103,now I'm going to setup a new Snipe-IT to test.

**Comment by laopangzi** [comment]
This time when I finish installing,it is version 2.0.6-14,and it works correct.
How did I installed v2.0.6-103?

**Comment by laopangzi** [comment]
Installed version 2.0.6-108,when I click the edit icon to modify asset model,it shows me an 'ErrorException'.
Version 2.0.6-14 works correctly.

**Comment by laopangzi** [comment]
My mistake, forgot run `php artisan migrate` after checkout to develop branch.
