### ISSUE TITLE
Error when check-out and expected check-in dates are the same.

### ISSUE THREAD

**Issue by pkutzner** [snipe/snipe-it#1497]
When checking out an asset, if the expected check-in date is set to the same day as the check-out date, saving the checkout throws a 'Undefined variable: expected_checkin' error.

Use case for this: checking out a peripheral to a user that will be returning it later the same day (such as a portable optical drive).

**Comment by snipe** [comment]
http://docs.snipeitapp.com/getting-help.html

Need version of Snipe-IT, specific error messages (that point to line numbers, etc.)

**Comment by dmeltzer** [comment]
I see this issue in 2.0.6, but it is not reproducable in develop.  Looks like it's been fixed along the way.
