### ISSUE TITLE
Character "-" in custom field name

### ISSUE THREAD

**Issue by BlackGrizzly** [snipe/snipe-it#1498]
Why I cannot use the "-" character in custom field name ?
For example, if custom field name is "IP-address", on save I get "500 Internal Server Error"

**Comment by snipe** [comment]
Can you please tell us the specific error message.

**Comment by snipe** [comment]
http://docs.snipeitapp.com/getting-help.html

**Comment by BlackGrizzly** [comment]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-address TEXT)' at line 1 (SQL: ALTER TABLE assets ADD COLUMN (_snipeit_ip-address TEXT))

**Comment by BlackGrizzly** [comment]
You can try it on your demo version on you site

**Comment by snipe** [comment]
This is fixed on develop
