### ISSUE TITLE
Snipe-it to run on my local system

### ISSUE THREAD

**Issue by pradeepneelam** [snipe/snipe-it#1503]
Hi team,
Please provide me the step by step installation of snipe-it on my machine.
I am little confused with the document you provided in http://docs.snipeitapp.com/installation/index.html.

**Comment by snipe** [comment]
If you have specific questions, we can try to help you, but that is the step by step installation.

**Comment by pradeepneelam** [comment]
i followed the steps but stuck up on running the command php artisan key:generate
I am getting 
Warning: require(C:\xampp\htdocs\evassets\bootstrap/../vendor/autoload.php): fai
led to open stream: No such file or directory in C:\xampp\htdocs\evassets\bootst
rap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\evassets\bootst
rap/../vendor/autoload.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htd
ocs\evassets\bootstrap\autoload.php on line 17

The installation guide is little bit confusing for me.
I am trying to install snipe it on xampp,please brief me about the installation

**Comment by pradeepneelam** [comment]
my machine is windows

**Comment by snipe** [comment]
You didn't generate the github token (by following the url it provided you), so composer didn't finish.

**Comment by pradeepneelam** [comment]
Greetings Snipe,i am able to generate the key now...and i modified in c:/xampp/htdocs/evassets/app/config/app.php.

I followed the steps on running the command from c:/xampp/htdocs/evassets
php artisan app:install and the output is

Admin group created successfully.
Reporting group created successfully.
Users group created successfully.
Your user was created successfully.

So,what is the next step now,how to access the snipe locally on my machine....Please help me with the steps

**Comment by pradeepneelam** [comment]
when accessing http://10.0.0.149:82/evassets/public/ it is throwing me an error like
![snipe error](https://cloud.githubusercontent.com/assets/8856809/11911600/aae1b932-a640-11e5-9305-96bf63779992.png)

**Comment by pradeepneelam** [comment]
finally i able to access snipe locally after bypassing the issues.But i am having a small thing ie is it possible to change the default current INR which is the Indian currency...
