### ISSUE TITLE
New install help

### ISSUE THREAD

**Issue by jveach2003** [snipe/snipe-it#1505]
I'm getting the following error when i try to connect to the url of the snipe-it sever:
![server error](https://cloud.githubusercontent.com/assets/16356640/11909336/43228dcc-a59a-11e5-81d9-86f73d59cf63.png)

I used this script to install: https://github.com/snipe/snipe-it/blob/c34c9438da88ab13c0e1dba28e8ee087d93acb93/snipeit.sh

Running Ubuntu 14.04 LTS

If i try to connect to the ip address directly, it shows the default Apache page, so i know Apache is running.

LOGS:
[app-storage-log.txt](https://github.com/snipe/snipe-it/files/67289/app-storage-log.txt)
[apache-error-log.txt](https://github.com/snipe/snipe-it/files/67290/apache-error-log.txt)
CONFIG:
[ap-config-production-app_php.txt](https://github.com/snipe/snipe-it/files/67298/ap-config-production-app_php.txt)

Any help wil be much appreciated.

**Comment by twistedR** [comment]
Are you connecting over https? Try manually changing the URL to http.

**Comment by jveach2003** [comment]
Thanks for the advice, but that did not solve the problem. My attempts at connecting to my server hostname via http or https navigate me to a public website, not my internal server. Connecting via IP address leads me to the apache default webpage of my internal server.

**Comment by HinchK** [comment]
Hello friend!  From the evidence you have provided, it appears like there might be 2 issues going on:

1. there is a problem connecting to the database [app-storage-log] `'SQLSTATE[28000] [1045] Access denied for user 'snipeit'@'localhost' `

2.   `'/var/www/html/snipeit.php' not found or unable to stat` - case sensitivity might be the silver bullet (i.e. if you're using caps in your host - make sure what you're typing into the browser is case-sensitive as well.)

if that doesn't work, it could be a permissions issue on the files (make sure snipe-it files are readable by the apache user.)  

dialing in a virtual-host on the server might be necessary (especially if its a VPS.)   make sure the `/etc/hosts` file on the machine isn't causing any issues or being overwritten.  when all else files, i might work backwards from the configuration i KNOW works (i.e. i can hit the apache default site via IP) and compare the directory owners/locations/paths/etc. to see what might be different and perhaps off with the hostname/vhost configuration.

http://askubuntu.com/questions/509945/script-not-found-or-unable-to-stat-one-page-and-not-others-same-permissions

http://serverfault.com/questions/185954/hosts-file-entries-for-multiple-domains-on-vps

**Comment by jveach2003** [comment]
thanks for the tips. when i went to check the /var/www/html/snipeit.php file for capital letter consistency. i noticed that there was only one file in that directory: 'index.html'. Perhaps something didn't install correctly?

**Comment by HinchK** [comment]
Maybe the install choked on the database connection - try to connect to the mysqldb directly with the user/password being passed in via the script.  'mysql -uUsername -p'.   If you can't connect with that "snipe-it" database login....connect to the database with your own credentials and create the user.

**Comment by jveach2003** [comment]
just successfully tested the mysql connection with the user defined in the '/var/www/snipeit/app/config/production/database.php' file. 

i also changed the url name in '/var/www/snipeit/app/config/production/app.php' from 'Snipe-IT' to 'snipeit' to rule out any typing inconsistencies. 

restarted the apache2 service and still the same situation.

**Comment by HinchK** [comment]
Bummer - I'll walk through an apache installation on a vagrant VM and see if I can catch what might be thwarting you.

**Comment by twistedR** [comment]
Can you post the virtual host config for apache? It would be under `/etc/apache2/sites-enabled/`

**Comment by jveach2003** [comment]
Two files in that directory: 000-default.conf and snipeit.conf, attached is the '000-default'
[000-default.txt](https://github.com/snipe/snipe-it/files/73390/000-default.txt)

**Comment by twistedR** [comment]
What's in the snipteit.conf? That'll tell you what URL it's expecting.

**Comment by jveach2003** [comment]
Not sure what to make of this, looks like conflicting server names?
[snipeit.conf.txt](https://github.com/snipe/snipe-it/files/73532/snipeit.conf.txt)

**Comment by twistedR** [comment]
It seems like the virtual host is duplicated. Either way, it's looking for Snipe-IT as the URL name. Did you add `Snipe-IT` into your hosts file with the correct IP?

**Comment by jveach2003** [comment]
[hosts.txt](https://github.com/snipe/snipe-it/files/73550/hosts.txt)
It used to be Snipe-IT, i changed it to snipeit to eliminate any case related issues.

**Comment by HinchK** [comment]
Try changing this line:
'127.0.1.1       snipeit'
To 
'127.0.0.1       snipeit'

And comment out the bottom two lines in that host file and restart the Apache server

**Comment by HinchK** [comment]
just realized while going through my own installation - commenting out the bottom two lines might not be helpful

**Comment by twistedR** [comment]
If your apache is looking for Snipe-IT then that's what you need in your hosts file

**Comment by jveach2003** [comment]
Edited the hosts.conf file to reflect the changes:

***********************************
127.0.0.1       localhost
127.0.0.1       Snipe-IT

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
127.0.0.1 Snipe-IT SnipeIT
127.0.0.1 Snipe-IT Snipe-IT
************************************
Still no luck.

**Comment by twistedR** [comment]
What happens when you go to localhost? Do you see the apache page?

**Comment by jveach2003** [comment]
no gui on the server, so i have to navigate to the web page from a different machine; when i type the ip address of the server, it gives me the default apache page.

**Comment by twistedR** [comment]
Ohhh. So just so that I understand it correctly. You have installed Snipe-IT on a VPS server and the apache vhosts file you provided were from there. 

You are trying to access the server through your laptop/desktop right? And the /etc/hosts file your provided is your local one and not the one on the server?

**Comment by jveach2003** [comment]
the hosts file is from the server, /etc/hosts, all of your other deductions are correct :)

**Comment by twistedR** [comment]
Okay, that seems to be the issue. You need to edit your local hosts file not the one on the server if you want to access the server without a FQDN. In your local hosts file add `1.2.3.4 Snipe-IT` at the end. Where 1.2.3.4 is the IP address of the server.

Then locally when you goto Snipe-IT in the browser it will go to the server.

**Comment by jveach2003** [comment]
Would it be correct to call this a DNS issue? That, if i add the server's FQDN to my local DNS server, it will point my browse request to the Snipe-IT server?

**Comment by twistedR** [comment]
Yup you can do that as well. If you add an FQDN like snipe-it.mydomain.tld then you'll have to change the apache vhosts file. But if you just add Snipe-IT in your local DNS then no change is required :)
