### ISSUE TITLE
[Feature Request] for 'View Assigned Assets': See currently checked out Accessories in its own table 

### ISSUE THREAD

**Issue by mettke** [snipe/snipe-it#1506]
It would be nice to have a list for currently checked out Accessories like there is one for the currently checked out Assets, so the user can easily see, what is checked out to him. 

https://demo.snipeitapp.com/account/view-assets

**Comment by wilsonlspacheco** [comment]
+1

**Comment by wilsonlspacheco** [comment]
Our employees have many accessories assigned.. 
We need a shared excel to show this to them.. 
Will be a fantastic upgrade to us, dev this feature to Snipe-IT.
