### ISSUE TITLE
Active report error

### ISSUE THREAD

**Issue by chenboshiun** [snipe/snipe-it#1507]
Hello :
while i click Activity Report, show error below:

![screen shot 2015-12-21 at 7 48 45 pm](https://cloud.githubusercontent.com/assets/5372796/11930160/ef526fda-a81b-11e5-8c13-80733d9da8b3.png)

log:
Next exception 'ErrorException' with message 'Trying to get property of non-object (View: /kkcorp/snipe-it.kkcorp/app/views/backend/reports/activity.blade.php)' in /kkcorp/snipe-it.kkcorp/app/storage/views/81f6c4d846a9a7286c9fa155c42d455c:41
Stack trace:
#0 /kkcorp/snipe-it.kkcorp/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /kkcorp/snipe-it.kkcorp/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/kkcorp/snipe-i...', Array)
#2 /kkcorp/snipe-it.kkcorp/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/kkcorp/snipe-i...', Array)
#3 /kkcorp/snipe-it.kkcorp/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#4 /kkcorp/snipe-it.kkcorp/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#5 /kkcorp/snipe-it.kkcorp/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#6 /kkcorp/snipe-it.kkcorp/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /kkcorp/snipe-it.kkcorp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /kkcorp/snipe-it.kkcorp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 /kkcorp/snipe-it.kkcorp/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /kkcorp/snipe-it.kkcorp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /kkcorp/snipe-it.kkcorp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /kkcorp/snipe-it.kkcorp/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /kkcorp/snipe-it.kkcorp/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 /kkcorp/snipe-it.kkcorp/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /kkcorp/snipe-it.kkcorp/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /kkcorp/snipe-it.kkcorp/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /kkcorp/snipe-it.kkcorp/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /kkcorp/snipe-it.kkcorp/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []

is manually manipulate my data at all problem ? How can i solve this issue?

thanks.

**Comment by uberbrady** [comment]
Yes, manually manipulating data can often cause problems like these - the system is expecting certain Activity to be linked to certain Assets, and may be associated with different users - if some of those end up missing, all kinds of things can fail.

**Comment by snipe** [comment]
You'll have to go through the `asset_logs` table and remove any references to people, assets, accessories, locations or consumables that you deleted from the database. 
http://docs.snipeitapp.com/installation/manually-editing-data.html
