### ISSUE TITLE
Invalid default value for 'created_at' - MySQL > 5.6

### ISSUE THREAD

**Issue by twistedR** [snipe/snipe-it#1509]
Hi,
This is just a cross post. There is an issue with Laravel Framework and MySQL > 5.7
I ran into this issue as I am using MySQL 5.7. if you run into a migration issue with `Invalid default value for 'created_at'` it's because the default install has the NO_ZERO_DATE flag enabled.

Check https://github.com/laravel/framework/issues/3602 for futher details.

Since snipe-it is still on laravel 4 the only option is to disable the flag. 

For homebew users this answer helps http://stackoverflow.com/a/8598402

**Comment by snipe** [comment]
Thanks!

![linedmediumacornbarnacle](https://cloud.githubusercontent.com/assets/197404/11941698/52248a84-a7e6-11e5-8d86-8fc0df7ba770.gif)

**Comment by snipe** [comment]
Just a follow up here: to disable the `NO_ZERO_DATE` flag, you'll need to find your `my.cnf` file (usually `/etc/my.cnf` on linux systems) and follow the directions here, only do not include `NO_ZERO_DATE` in your set command. So something like:

`sql_mode=ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`

https://www.interserver.net/tips/kb/disable-mysql-strict-mode/
