### ISSUE TITLE
Consumables - Checkout Multiple at a time

### ISSUE THREAD

**Issue by dmeltzer** [snipe/snipe-it#1511]
This might be related to the discussion about ui for replenishing consumables, but it would be nice if there was a way to check-out or "consume" more than one item at a time to a user.

**Comment by stevecookms** [comment]
Is this still something that is being considered?

**Comment by wessieaa** [comment]
Please this will help a lot

**Comment by Weaksid** [comment]
Looks like #2796 might be the main feature request one at the moment even though this was first. But, I can see how the amount of requests this could get lost. Suggested back in 2015 and still not sure why it's not a feature that was built into the system.

**Comment by wessieaa** [comment]
Is this matter been addressed?

**Comment by snipe** [comment]
> Suggested back in 2015 and still not sure why it's not a feature that was built into the system.

Because there are only so many hours in a day.

**Comment by snipe** [comment]
Closing this as a duplicate of #2796, since it includes accessories.

**Comment by Trog3r** [comment]
Looks like there are three requests for this (#1046, #1511, & #2796), but they were all closed because they were duplicates :) I'm thinking one of these should stay open??

Oh and I also up vote this request as it would be very helpful.
