### ISSUE TITLE
Asset Models page not displaying data

### ISSUE THREAD

**Issue by tzielinskiaptn** [snipe/snipe-it#1515]
I'm running the latest stable release of snipe-it 2.0.6, and when I go to the asset models page, the models are not listed, and I'm unable to edit or delete them.

My site still shows as version 2.0.5 pre, so I'm not sure if I missed a step in the upgrade or how best to resolve this issue.

Thanks

![snipeit](https://cloud.githubusercontent.com/assets/11275891/11962376/fcd3e614-a8a4-11e5-82a8-20bf96b2900c.JPG)

**Comment by snipe** [comment]
http://docs.snipeitapp.com/getting-help.html
