### ISSUE TITLE
Version displayed does not correspond to version downloaded

### ISSUE THREAD

**Issue by vcornil** [snipe/snipe-it#1522]
I've just installed version 2.0.6 on a new server.
After installation, it displays  v2.0.5-pre as version.
There was no prior installation on that machine.
I download that version (from the ZIP file) a second time, but still see that same version.

How can I check I have a correct one (stable) ?

**Comment by dmeltzer** [comment]
As far as I can tell, the 2.0.6 tag has a hash version of 'v2.0.5-pre-191-g948be5c'.  I'm not sure if this is visiblble in the interface anywhere, but you can check in app/config/version.php.

**Comment by brianjking** [comment]
@vcornil Please see #1405 & #1429
