### ISSUE TITLE
missing lang placeholder in \app\views\backend\hardware\edit.blade.php

### ISSUE THREAD

**Issue by A-ROYAL** [snipe/snipe-it#1524]
Hi Snipe,

I've found missing lang placeholder in \app\views\backend\hardware\edit.blade.php on line 258.
I suggest to replace original text with "@lang('admin/hardware/form.eol_help')" and to add an appropriate "eol_help" reference in \app\lang\*\admin\hardware\form.php

Used version 2.0.6

Sorry for possible duplicates. I am not yet familiarized with GitHub env.

**Comment by dmeltzer** [comment]
Line 290 in devel.
