### ISSUE TITLE
Indian Currency

### ISSUE THREAD

**Issue by dahiya81** [snipe/snipe-it#1526]
Indian Currency is missing from the File i.e Rupee how can we add that .

**Comment by mahesh2471990** [comment]
@snipe Is Indian Currency Available.. Please add it. RUPEES

**Comment by dahiya81** [comment]
where to add the same can u tell me sir

**Comment by mahesh2471990** [comment]
@dahiya81  sorry its not available. @snipe: We need Indian Currency to be added.. Please added in GITHUB repo or Future Roadmap. next release..
