### ISSUE TITLE
Report on Depreciation

### ISSUE THREAD

**Issue by dahiya81** [snipe/snipe-it#1527]
The Report is exported in CSV and file name is download same can be added download.csv and the Cost ,value and diff amount are having lots of space in Excel and at last sum can be added in that

**Comment by snipe** [comment]
I have no idea what any of this means. Please see the documentation on getting help: http://docs.snipeitapp.com/getting-help.html

And provide whatever additional information (screenshots, etc) that may help explain your issue.

**Comment by dahiya81** [comment]
dear Sir

Please find the file attached as CSV in which we do any Sum etc at the end
of the file .
