### ISSUE TITLE
SnipeIT tool - Symfony \ Component \ HttpKernel \ Exception \ NotFoundHttpException 

### ISSUE THREAD

**Issue by Balajipss** [snipe/snipe-it#1529]
While Trying to deploy the snipe it tool am  getting this error. I have followed all the steps given in the documentation correctly. But still i dont know why i get this error. 

![image](https://cloud.githubusercontent.com/assets/15668614/12017044/ea1cdf3a-ad77-11e5-81ad-faa2f7852000.png)

**Comment by snipe** [comment]
http://docs.snipeitapp.com/getting-help.html
