### ISSUE TITLE
bulk delete doesnt check for superadmin rights before delete

### ISSUE THREAD

**Issue by swoopdk** [snipe/snipe-it#1530]
I  am able to delete users using bulk delete however i will need to set the superadmin rights before i can delete a single user at a time using the trash icon. 

So assuming that the bulk delete doesn't check this permission before executing. 

On a related not shouldn't the original user created during install by default be given the superadmin rights ? I see no reason why not since that person can grant them to themselves anyhow.

**Comment by dmeltzer** [comment]
I'm not going to make a commit for part 2 at this point, though I agree w/ it. Diff is here though.

```
diff --git a/app/commands/AppCommand.php b/app/commands/AppCommand.php
index 32bb73b..035b454 100755
--- a/app/commands/AppCommand.php
+++ b/app/commands/AppCommand.php
@@ -359,6 +359,7 @@ class AppCommand extends Command
             'permissions' => array(
                 'admin' => 1,
                 'user'  => 1,
+                'superuser' => 1,
             ),
         ));
```

**Comment by mahesh2471990** [comment]
Hello @dmeltzer 

I referred your fix and made the change Fix #1532 But after the changes made in app/controllers/admin/UsersController.php

I logged in to Snipe IT and Clicked on People (snapshot below)
![errro5](https://cloud.githubusercontent.com/assets/16305213/12032720/75a0a7de-ae41-11e5-8d58-4a2fd51451b7.jpg)



I didnt get your previous comment

**Comment by mahesh2471990** [comment]
@dmeltzer @snipe 
I refered and made change in app/views/backend/users/index.blade.php also

After that there is no option of bulk delete or delete icon????

![after changes](https://cloud.githubusercontent.com/assets/16305213/12033118/7af95b00-ae45-11e5-90bd-469c9c6efd04.JPG)

**Comment by dmeltzer** [comment]
Hello,

If you enable debugging in app/config/production/app.php, what is the error when clicking on people?  

Also, the index.blade.php change is doing what I intended it to do (though maybe not what it should do--we'll see what snipe thinks)-- Because there is no support in the code base for permanently deleting users, I hid the delete actions when viewing deleted users.  I'm going to play with creating a restore users action that can be shown instead when looking at the deleted users page, but I haven't had time to dig deeply into that yet.

**Comment by mahesh2471990** [comment]
@dmeltzer Thank you for information

But the thing is User where is imported from LDAP Server. some are not having Good manner name like first name and last name was quite difference..i came to know after i sync. so Then i loggin my Active dir Server and edit all the users with correct first name and last name and Even added the Field of email and planning for employee id also.. then i again i resync in snipe it (LDAP user sync) it will not update the change what i made in Active dir server.. So i wanted to delete all the users and fresherly sync once..So i deleted all the users in Current User (Bulk Delete GO) 

Again i sync it completed but user was in Show Deleted Users itself and not even updated the changes.
I want all users imported from LDAP should be deleted. and again i want resync new one.. SO the all the attribute of user will be available. @snipe is busy in other issue i guess. she didnt respond regrading this.


Can u help me regarding this sir.

**Comment by swoopdk** [comment]
@mahesh2471990 I have been noting the same "issue" about LDAP syncing. 

Really it's kind of a seperate issue since the LDAP is basically a simple import and not a sync/update. However i would like it to do exactly this with updating so that i only have to configure changes in LDAP rather than just have the ldap setting make a copy.

**Comment by snipe** [comment]
@dmeltzer restore is back on develop now
