### ISSUE TITLE
Bug - Checkout date still showing after asset checkin

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#1531]
In latest DEV code

Think this is a bug... noticed when looking at my RTD assets some of them have checkout dates still showing when the asset is actually checked in. I'm not too sure where its getting this date from.

Since the dates aren't matching it makes me think I have something screwed up in my database but I haven't played with the data manually in a long time.

![image](https://cloud.githubusercontent.com/assets/10247644/12020275/7da28d98-ad48-11e5-9efb-0f1795593df6.png)
![image](https://cloud.githubusercontent.com/assets/10247644/12020276/7fdceedc-ad48-11e5-9ced-3852cb3afb82.png)

**Comment by dmeltzer** [comment]
I can reproduce.  It looks like expected checkin isn't cleared when the asset is checked back in.
