### ISSUE TITLE
Issue when Installing from script

### ISSUE THREAD

**Issue by csayre** [snipe/snipe-it#1536]
I am installing from [link](http://docs.snipeitapp.com/installation/downloading.html) on to a centos7 box. I ran the following steps 

Download and run the installer script (centos/redhat and debian/ubuntu)

Note: requires Centos 6 or Ubuntu 14 or greater.

wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh
chmod 744 install.sh
./install.sh

When I go to the IP address of the server I get the following error: 
ErrorException (E_WARNING)
file_put_contents(/var/www/html/snipeit/app/storage/meta/services.json): failed to open stream: Permission denied

Stack trace: 

8. ErrorException
…/­vendor/­laravel/­framework/­src/­Illuminate/­Filesystem/­Filesystem.php70
7. Illuminate\Exception\Handler handleError
<#unknown>0
6. file_put_contents
…/­vendor/­laravel/­framework/­src/­Illuminate/­Filesystem/­Filesystem.php70
5. Illuminate\Filesystem\Filesystem put
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­ProviderRepository.php202
4. Illuminate\Foundation\ProviderRepository writeManifest
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­ProviderRepository.php145
3. Illuminate\Foundation\ProviderRepository compileManifest
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­ProviderRepository.php57
2. Illuminate\Foundation\ProviderRepository load
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­start.php210
1. require
…/­bootstrap/­start.php59
0. require_once
…/­public/­index.php35

**Comment by csayre** [comment]
I looked at the file structure and I do not see the file that the webserver is trying to access.

**Comment by csayre** [comment]
Selinux was causing this issue.

**Comment by drewrowland** [comment]
Can you comment on what you did to fix this issue? I'm having the same issue.

**Comment by snipe** [comment]
http://docs.snipeitapp.com/installation/server/linux-osx.html#notes-on-selinux
