### ISSUE TITLE
Import Users not working

### ISSUE THREAD

**Issue by HelpdeskMakesMeFat** [snipe/snipe-it#1539]
Using csv with very few entries. Tried with header and no header.
It worked fine yesterday with hundreds of entries.

Some of the users in the csv have the same email address. 
Some of the users in the csv have the same email address as users who have already been created.
Would this cause a problem?

Any suggestions?

**Comment by snipe** [comment]
http://docs.snipeitapp.com/getting-help.html

**Comment by snipe** [comment]
"Not working" isn't helpful information. Please provide error log output with debugging mode turned on.

**Comment by dudeincali** [comment]
Hi snipe I just got this too. I successfully imported 100 users to test. However, following the import format it didn't respect my location_id entries and ignored all of them. I then deleted all my users. I modified the header this time removing "_" and just leaving 'location', then imported again. It then said "successful", but didn't show any users imported. Then I went back to the original method, left headers in and tried to import again. Same result. Says, "successful", but no users were imported. Once I get back into work tomorrow I can enable debugging, but to HDMMF above, I experienced this as well. Thx

**Comment by snipe** [comment]
@dudeincali http://docs.snipeitapp.com/getting-help.html

**Comment by snipe** [comment]
@dudeincali (I need version number, etc)

It doesn't care about the column header names, it just looks for column count, etc.

**Comment by dudeincali** [comment]
v2.1.0-pre
Also, I tried the same csv file with the same users/headers/column counts and tried to re-import it (after I had manually deleted all the users) and it will not reload those users on import. Also, I've verified my column count several times (based on FAQ page for import) and it still doesn't populate the location field. I can turn on debugging now, let me know. Thx

**Comment by 08solsticegxp** [comment]
I have found that if you have a column for each of the items: 

firstName | lastName | username | email | location_id | phone | jobtitle | employee_num | company_id
Make sure to check that your file has a header... Everything will work fine. If you don't have the column headers, it appears snipeit doesn't think you have the right file and will just say oops, there was a problem. Even if you don't have Location_ID or Employee_number... Make a column for it in the right order and just leave the reset of the column blank... Works for me.
