### ISSUE TITLE
Update of PHP file from Repo is Recommeded or No?

### ISSUE THREAD

**Issue by mahesh2471990** [snipe/snipe-it#1540]
We can see the changes made in php file in repo..

Manually going through the each and every php copying the code and pasting in our php file is recommended way or can u tell how to upgrade directly to our system so what ever changes you people do will get updated.
I tired all data and some of the pages was not opening.

I am using Server 2012 Xampp php admin. Installed through composer
my current verison is
Where i found it in C:\xampp\htdocs\snipe-it\app\config\version.php
app_version' => 'v2.0.6-14'
hash_version' => 'v2.0.6-14-g74ed75d'

As i have seen the https://github.com/snipe/snipe-it
many php file has been updated with new file or extra code to fix the bug.

@snipe @dmeltzer @uberbrady  Guys please help me Give some Kb how to upload all new fixed php at a time.

my question is Whether can i update automatically from my PC. the latest code and fix has been done..

**Comment by uberbrady** [comment]
If your code on your server is actually a `git clone` of the Snipe-IT repo, you can just do `git pull` to get the latest version, then do `composer install` to make sure you have the latest libraries, then `php artisan migrate` to make the latest changes to the database.

I do that on my **development** system, but I'm not sure how appropriate that is to do in a **production** system. I mean, I guess since the code is open source, having pointers back to the repository in the form of various `.git/` directories probably doesn't matter. Anything wrong with this idea @snipe ?

**Comment by snipe** [comment]
No, that's typically what I recommend doing. None of the private configuration data (database credentials, etc) are stored in the repo, so git directories won't expose any critical info.

**Comment by snipe** [comment]
Just make a copy of your `app/config/app/php`, or be prepared to set your timezone back in the off-chance we update that file.

**Comment by mahesh2471990** [comment]
I want to upgrade to this version (v2.0.6-165)

Is it possible how?
I have make a copy of app/config/app/ (all the php in this).
Where do i get the (v2.0.6-165)
How to upload i am using in production environment @snipe @uberbrady Can u people help me out of this.

**Comment by mahesh2471990** [comment]
![message](https://cloud.githubusercontent.com/assets/16305213/12047527/fd1fdb4c-aef2-11e5-8754-828bafe4bd78.JPG)


I guess this configation file must be copied @snipe what is next procedure

**Comment by mahesh2471990** [comment]
https://develop.snipeitapp.com/auth/signin i am seeing the  (v2.0.6-165).
I tested lots things where all are working almost fyn expect Bulk del in Deteled user not work some errors???
Icon Problem Can anyone tell how to upgrade to that version of snipe IT where i am having v2.0.6-14
Please Do needfull help..

**Comment by mahesh2471990** [comment]
Even i have download the latest code From repo of https://github.com/snipe/snipe-it/tree/develop.
Full zip one..
how to upgrade this with my repo??? Is it possible.. as Per @snipe i have to copy the app/config/app/production(all the php in this). above image!
After that i will copy new one developed version snipe it and replace my old Production/php file. This will ok. never effect data of assets and all r8?

**Comment by mahesh2471990** [comment]
I new version 2.1 pre is better.. I will try to ugrade to that vesrion.
