### ISSUE TITLE
Bug - Cannot edit accessory quantity count

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#1541]
Was able to verify as broken in my two environments but did not break in demo.

![image](https://cloud.githubusercontent.com/assets/10247644/12037301/ac91a8b8-ae1b-11e5-8365-10ea6faebae7.png)

**Comment by dmeltzer** [comment]
I wonder if these accessories predate the addition of location?  Do they have a location id in the db or is it unset?

**Comment by kobie-chasehansen** [comment]
no location is set and it's not set as a mandatory field but that could be an error as well.

![image](https://cloud.githubusercontent.com/assets/10247644/12038217/3cb159ea-ae24-11e5-8715-a01ae3191f42.png)

**Comment by dmeltzer** [comment]
What does `SELECT name,location_id from accessories` show?  I'm especially curious `WHERE `id`=9, but it might be useful to compare to other ids.

**Comment by kobie-chasehansen** [comment]
sure, it does look like its set to null

![image](https://cloud.githubusercontent.com/assets/10247644/12039063/435e663c-ae2b-11e5-801b-5ee8c601c060.png)
