### ISSUE TITLE
Reminder email to IT and employee about check in date?

### ISSUE THREAD

**Issue by seanism** [snipe/snipe-it#1542]
Is it possible to have the option to have Snipe-IT send an email reminding the user to return the item they checked out?  Also a daily/weekly email to admins mentioning what items are due to be returned or are over due?

I love the check in date but I don't see any real benefit at this moment.  Thanks.

**Comment by yaman2k** [comment]
I agree with @seanism.  I have the same request.  We have users who check out items, but want to send them reminders before the due date.  Would be also good to show warnings for overdue items, send notifications to the users/managers and possibly prevent them from doing any further requests until the items are returned.  Being able to report on that would be also important.

**Comment by seanism** [comment]
Ohh I like that last part @yaman2k Have a warning show up if they have past due items whenever you add / remove anything from their user profile.

**Comment by yaman2k** [comment]
Giving this one a bump!

**Comment by matt-goldman** [comment]
Agree, this is a really important feature for us too. As @seanism said without this the expected check in date is a little redundant.

**Comment by snipe** [comment]
It's planned. Need v3 released first.

**Comment by yaman2k** [comment]
I have written a quick code that pulls data from the database and checks due date field, and then sends notifications to user and system admin.  I then did a cronjob and have this file executed on a regular basis.

I modified this so I have it 1) for user overdue item, 2) for admin with complete overdue list and 3) for users with upcoming/soon-to-be-due items.

I posted the files on github:
https://github.com/yaman2k/Overdue-notifications

**Comment by snipe** [comment]
Hi! Thanks for this - is there any way you can put this into a pull request?

**Comment by yaman2k** [comment]
Sure @snipe .   I read the contributors section.  Let me do some reformatting and put that into a pull a request.

**Comment by dannyscarborough** [comment]
Hi!

Did this get incorporated into v3? If so how can I go about using it?

**Comment by dannyscarborough** [comment]
@yaman2k Could you tell me how I can use your script on a Windows Server build?

**Comment by wh0else** [comment]
@dannyscarborough `php /path/to/admin-overdue-list.php`

**Comment by dannyscarborough** [comment]
@wh0else Thanks for your quick reply. If I run the script via command line I always get this error ""Issue sending e-mails. Please contact admin@url.com""

I'd assume it should use the mail server set in Snipe-IT right?

Do I need to enter my database details in the first line too?

"mysql_connect("localhost","username","password")"

**Comment by wh0else** [comment]
[admin-overdue-list-obscured.txt](https://github.com/snipe/snipe-it/files/933358/admin-overdue-list-obscured.txt)
@dannyscarborough I've attached the php file we are using in our environment. Just set different sender and receiver mail addresses and the database/user/password

**Comment by dannyscarborough** [comment]
@wh0else Thank you. I think I've got everything setup alright. Can it be run from anywhere or does it need to be in a particular folder? I'm currently running from "C:\inetpub\wwwroot\snipe-it"

**Comment by wh0else** [comment]
@dannyscarborough Awesome :) I have it in my snipe it directory as well, but you can run it from anywhere I'd guess. And you can probably "cron" it with Windows as well, using Scheduled Tasks

**Comment by dannyscarborough** [comment]
@wh0else Ah I meant it looks setup alright compared to yours but still no dice. Must be something at my end. One last question, Do you use SMTP or sendmail, mail?

> MAIL_DRIVER
Specify the driver you would like to use. On most installations, you can leave this as smtp. Other options include mail to use the system's PHP mail function, or sendmail if you wish to use your server's sendmail.

**Comment by wh0else** [comment]
Aah, I see. In the .env config file?


I use SMTP, as we have a mail server running on default port 25


Sendt fra Outlook<http://aka.ms/weboutlook>


________________________________
Fra: dannyscarborough <notifications@github.com>
Sendt: 19. april 2017 14:52
Til: snipe/snipe-it
Kopi: wh0else; Mention
Emne: Re: [snipe/snipe-it] Reminder email to IT and employee about check in date? (#1542)


@wh0else<https://github.com/wh0else> Ah I meant it looks setup alright compared to yours but still no dice. Must be something at my end. One last question, Do you use SMTP or sendmail, mail?

MAIL_DRIVER
Specify the driver you would like to use. On most installations, you can leave this as smtp. Other options include mail to use the system's PHP mail function, or sendmail if you wish to use your server's sendmail.

**Comment by dannyscarborough** [comment]
@wh0else I've got it working :+1: 

Thanks for your help, I had to set my SMTP server in my PHP.ini otherwise it was trying to send using the localhost.

**Comment by leonmflai** [comment]
hi, I modified some code of the php script for overdue email reminders. However, I cannot run the cronjob as expected. Is there any one can help how to enable "Crontab" of the php scripts?

I tried the dry-run of the scripts and it is function well.

I checked /var/log/syslog, the .php script has been run successfully but there is no email sent

**Comment by bwoiderski** [comment]
We are getting daily email reminders leading up to the expected checkin date for assets. Is there a way to configure the number/frequency of these notifications? One per day in the week leading up to the checkin is excessive for our needs.

**Comment by yaman2k** [comment]
I had a need to send notifications to not just employees but also to their managers with a list of overdue items for all direct employees.  If you populate the manager details in Snipe-IT, you can then run the same cronjob on this php script.  The code is posted here: https://github.com/yaman2k/Overdue-notifications/blob/master/notification-manager
