### ISSUE TITLE
Issue when forcing ssl 

### ISSUE THREAD

**Issue by csayre** [snipe/snipe-it#1543]
Hello,

I am working on getting snipe-it working with an ssl connection. 

Currently I am getting a connection refused message when I try to connect to the webserver. 

I am following the directions here [here](http://docs.snipeitapp.com/installation/configuration.html)

I have setup the redirect by commenting the flowing lines. 

RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

I have also set this value to true

'secure' => true,

Please let me know if you need to see any other files. 

Thanks in advance for your help.

**Comment by csayre** [comment]
Please be sure to go to the link [here](https://wiki.centos.org/HowTos/Https) and follow all the directions. 

Also if you used the script be sure to change the following line `<Directory /var/www/html/public>` to     `<Directory /var/www/html/snipeit/public>`

So your virtual hosts should look like the following

    <VirtualHost *:80>
        <Directory /var/www/html/snipeit/public>
        Allow From All
        AllowOverride All
        Options +Indexes
        </Directory>
        DocumentRoot /var/www/html/snipeit/public
        ServerName www.yourserver.com
        # Other directives here
    </VirtualHost>
    <VirtualHost *:443>
        SSLEngine on
        SSLCertificateFile /etc/pki/tls/certs/ca.crt
        SSLCertificateKeyFile /etc/pki/tls/private/ca.key
        <Directory /var/www/html/snipeit/public>
        Allow From All
        AllowOverride All
        Options +Indexes
        </Directory>
        DocumentRoot /var/www/html/snipeit/public
        ServerName www.yourserver.com
        # Other directives here
    </VirtualHost>

**Comment by snipe** [comment]
![high-five-light](https://cloud.githubusercontent.com/assets/197404/12042711/6df3d560-ae32-11e5-808a-33081193c8a6.gif)

**Comment by csayre** [comment]
I have to admit, I do love your GIFs :smile:

**Comment by snipe** [comment]
![dancing-badger](https://cloud.githubusercontent.com/assets/197404/12042761/e46fb088-ae32-11e5-8976-8092735eaea9.gif)
