### ISSUE TITLE
Uploading too big asset image attachment fails without error message

### ISSUE THREAD

**Issue by swoopdk** [snipe/snipe-it#1549]
Hi

When adding an asset image i get an error. Tried to rescale the image to a nice 1024x768 and it worked. So assuming that the problem is perhaps a missing check for filesize and big files crashes the upload. 

Would be nice to either have a check in place to prevent this error and let people know that image is too large OR better solution is to have the upload resize to maximum allowed filesize/image size. 

Here are the debug logs

```
Intervention \ Image \ Exception \ NotReadableException
HELP
Unable to init from given binary data.
Open: /var/www/html/vendor/intervention/image/src/Intervention/Image/Gd/Decoder.php
     * @return \Intervention\Image\Image
     */
    public function initFromBinary($binary)
    {
        $resource = @imagecreatefromstring($binary);

        if ($resource === false) {
             throw new \Intervention\Image\Exception\NotReadableException(
                "Unable to init from given binary data."
            );
```

![screen shot 2015-12-30 at 08 58 34](https://cloud.githubusercontent.com/assets/5802977/12047925/bf729a06-aed3-11e5-9739-5670433a6e9a.png)

**Comment by swoopdk** [comment]
Also just noticed that i cannot get a "large" version of the image by clicking it in the asset view. Would be awesome to just show a thumbnail and then have people click to see original size or something. In this case it contains a small serial no that i cannot see from the size Snipeit shows :(

**Comment by snipe** [comment]
@swoopdk general speaking, that's coming from a php memory issue, If the image can't be uploaded due to memory constraints, it can't be resized either.

**Comment by swoopdk** [comment]
Sounds resonable. Didn't know where the limit came from as such, but then we should at least do some basic checking and display a good error message. Found this bug after filling out all the information for an asset and then having it all wiped because the image upload was too big :( 

@snipe possible to implement a link to show "full" resolution image when clicked in the asset afterwards ?
