### ISSUE TITLE
Unable to upgrade from V2.05 to V2.06

### ISSUE THREAD

**Issue by Balajipss** [snipe/snipe-it#1550]
Hi,

When i tried to upgrade the tool from V2.05 to V2.06 i got the following error.
Could not open input file: composer.phar
![image](https://cloud.githubusercontent.com/assets/15668614/12049721/050ee8fc-af11-11e5-9101-7928819248b8.png)

PS:
               OS: Windows server 2008 R2 Enterprise
                IIS 7.5

**Comment by csayre** [comment]
Is the composer.phar file in the location that you are currently in?

**Comment by ddreier** [comment]
If you installed Composer the recommended way, you should just right-click in the snipe-it folder and choose "Use Composer Here". Then run `composer install --no-dev --prefer-source`.

**Comment by Balajipss** [comment]
When i tried to run the command i got the following result.

![image](https://cloud.githubusercontent.com/assets/15668614/12064064/854ae6fa-afdf-11e5-947a-8e46830925e9.png)

But when i checked the SnipeIT tool version in the home page, its still V2.05

![image](https://cloud.githubusercontent.com/assets/15668614/12064076/ae8084c6-afdf-11e5-8324-ca4f8b1bc82b.png)

I have installed composer as per the recommended way. you can find the screenshot of the directory from where am trying to execute the "composer install --no-dev --prefer-source" command.

![image](https://cloud.githubusercontent.com/assets/15668614/12064084/e8edd56e-afdf-11e5-8e47-058398f00a85.png)

**Comment by dmeltzer** [comment]
According to http://docs.snipeitapp.com/installation/composer.html#Windows, you should run Composer-Setup.exe on windows, not php composer.phar self blah blah

**Comment by ddreier** [comment]
That version number is fine. There was a bug that caused it to be incorrect.

**Comment by Balajipss** [comment]
@dmeltzer 
I have followed the same steps as mentioned in the below link. But still am not able to update. http://docs.snipeitapp.com/installation/composer.html#Windows . 

I got the following message.
![image](https://cloud.githubusercontent.com/assets/15668614/12116678/9f0d56d0-b3e1-11e5-95f4-a481a5e82bea.png)

@ddreier 
But the features available in the latest version  is not available.

**Comment by ddreier** [comment]
What features are you talking about?

There is nothing wrong with your composer output, it's just telling you that there is "[n]othing to install or update." There might not have been any new packages added for 2.0.6, I can't remember.

**Comment by Balajipss** [comment]
@ddreier @snipe @dmeltzer 
I wanted to update to 2.1.0 Pre-release which has the following features. 
![image](https://cloud.githubusercontent.com/assets/15668614/12118414/4cf3c2ca-b3ec-11e5-8fda-60bc488b60bf.png)

Can you please tell me how to do it ?

**Comment by ddreier** [comment]
The same way you do any upgrade. MAKE A BACKUP OF YOUR Snipe-IT DIRECTORY AND DATABASE FIRST!

Then overwrite the Snipe-IT directory with the new version and run the commands in the image you included.
````
composer install --no-dev --prefer-source
composer dump-autoload
php artisan migrade
````

**Comment by snipe** [comment]
http://docs.snipeitapp.com/upgrading.html
