### ISSUE TITLE
After renaming the website its not working..

### ISSUE THREAD

**Issue by Balajipss** [snipe/snipe-it#1551]
Hi Snipe,

I changed the application name from 'SnipeIT' to 'Inventory' in IIS Manager. But i could see all the files which are generated dynamically still referring to the old name only. I have attached the screenshot of the IIS Manager.

![image](https://cloud.githubusercontent.com/assets/15668614/12049856/df738c5e-af12-11e5-8a24-6cc33e3a068b.png)

When I inspected the element in chrome i could see it is still referring to the old name 'SnipeIT' instead of 'Inventory'. Here is the screenshot of the same.

![image](https://cloud.githubusercontent.com/assets/15668614/12049877/3e3245aa-af13-11e5-89cb-c35110976061.png)

Can you please help us in resolving this issue ?

**Comment by ddreier** [comment]
You need to update the `url` setting in `<snipe-it directory>\app\config\production\app.php`.

**Comment by Balajipss** [comment]
Thanks ddreer :) It Helped to solve the issue. :)
