### ISSUE TITLE
LDAP bind password visible in settings

### ISSUE THREAD

**Issue by dc53000** [snipe/snipe-it#1552]
Under the new GUI-based LDAP settings in /admin/settings/app/edit, any admin user can now view the ldap bind account password. This could be potentially sensitive and should not necessarily be known by anyone assigned to inventory administration duties.

Can this be blocked out with asterisks when viewing? I don't expect admins to not be able to change it, but not having it plainly viewable from the GUI would be very helpful.

**Comment by snipe** [comment]
This is fixed in the upcoming v3
