### ISSUE TITLE
ldap_pword not generated for multi database creation

### ISSUE THREAD

**Issue by vtmragaven** [snipe/snipe-it#1559]
Hi, 
First I thank to snipe-it team to give the well-groomed source. I tried to use single snipe-it package to work with different mysql database based current domain. To create different database for snipe-it, I use the “app:install” command. I commented key-generate code on “app:install” codes (snipe-it-2.0.6\app\commands\AppCommand.php) to make use of same key for all databases. I manually filled app key “c3T0erFU3HX4OMEhPrFaY9GvcHBFfwVa” on “snipe-it-2.0.6\app\config\production\app.php” file. I ensured that above key is loaded on “$this->laravel['config']['app.key']” correctly while “app:install” command executed. So I created some database with updated “app:install” command. All tables has successfully installed on database. After done db installation, I tried to sign-in with credential of corresponding domain. It shows some decrypt exception (Refer Screenshot 1). 

I analyzed the database tables and found the “ldap_pword” field is null on “settings” table.  I can found the other snipe-it database settings table which I installed in default way, “ldap_pword” field is filled with some value (Refer Screenshot 2). Can I have any solution on that why ldap_word value not created in key-generate code commented mode on app:install file? 

Thanks to advance

![error_on_try_to_login](https://cloud.githubusercontent.com/assets/16029908/12074114/87790cce-b168-11e5-81f7-4bd21fe9abcb.jpg)
![screenshot](https://cloud.githubusercontent.com/assets/16029908/12074116/a79396c8-b168-11e5-9595-64e429b6d052.jpg)

**Comment by snipe** [comment]
Pretty sure this was resolved in 2.1.0-pre
