### ISSUE TITLE
docker image auto builded error

### ISSUE THREAD

**Issue by kt1024** [snipe/snipe-it#1564]
latest build was 4 days ago, and was in error state.
https://hub.docker.com/r/snipe/snipe-it/builds/

**Comment by uberbrady** [comment]
The latest few builds have worked OK - when I looked at the error message, it seemed to just be flaking out for no good reason.

We didn't change anything (regarding docker), and now the builds are mysteriously succeeding again. Unless this starts to recur often, I'll close this for now.
