### ISSUE TITLE
Cannot remove custom field at "Update Asset Model> Field Set"  after applying custom field

### ISSUE THREAD

**Issue by SK9413** [snipe/snipe-it#1565]
V2.1

Changing it to other field set works but cannot remove field sets (change to "No custom fields") after applying it.

Thanks!

**Comment by snipe** [comment]
Can I see a screenshot of your custom fields and field sets?

**Comment by snipe** [comment]
(Also, do you get an error, etc? A little more info would be helpful.)

**Comment by SK9413** [comment]
Hi snipe,

![sniper1](https://cloud.githubusercontent.com/assets/15903195/12082237/4fa05fa6-b2ca-11e5-80ca-257a7f9b617f.jpg)

![sniper2](https://cloud.githubusercontent.com/assets/15903195/12082240/54c9316a-b2ca-11e5-9e88-2c276bd33b25.jpg)

No error when I update and save the asset model.(Success: Model updated successfully.)

**Comment by SK9413** [comment]
Also, 

When I tried to click " View Deleted" at "Asset Models" page, it showed me the result as "View Model" and no deleted asset model record is shown.

![asset1](https://cloud.githubusercontent.com/assets/15903195/12084853/bc01033e-b2f3-11e5-9cdd-a72ed7494d17.jpg)

![asset2](https://cloud.githubusercontent.com/assets/15903195/12084858/c2b9fd3e-b2f3-11e5-8b13-77fafce32fe9.jpg)

**Comment by ddreier** [comment]
Can confirm on my instance, setting an Asset Model to "No Custom Fields" does nothing.

**Comment by snipe** [comment]
This should be fixed in https://github.com/snipe/snipe-it/pull/1585
