### ISSUE TITLE
SubDirectory Issue

### ISSUE THREAD

**Issue by rudashi** [snipe/snipe-it#1566]
Hello all,

I have installed snipe-it in subdirectory like in documentation (http://docs.snipeitapp.com/installation/subdirectory.html). It's working almost perfectly. But I have plenty of minor bugs in backend view (missing preview image, broken jquery link etc). 

In every case, there is missing **{{Config::get('app.url')}}** in link, example:
file: **app/views/backend/hardware/edit.blade.php**
line: **377**
edit: **$.get("{{ Config::get('app.url') }}/hardware/models/"+modelid+"/custom_fields",{_token: "{{ csrf_token() }}"},function (data) {**

Where I was able to find errors:
> app/views/backend/suppliers/edit.blade.php
app/views/backend/layouts/default.blade.php
app/views/backend/suppliers/view.blade.php
app/views/backend/hardware/edit.blade.php
app/views/backend/models/edit.blade.php

**Comment by snipe** [comment]
What links are you seeing this in for the other blades?

**Comment by rudashi** [comment]
Mostly with *upload* in link.

**Comment by snipe** [comment]
I don't know what that means. Which links (from which pages) are broken
