### ISSUE TITLE
Warnings when debug mode is enabled

### ISSUE THREAD

**Issue by swift2512** [snipe/snipe-it#15668]
### Debug mode

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

### Describe the bug

![image](https://github.com/user-attachments/assets/68f02ccb-c9dd-4f82-825f-0c79c291d413)
Log is filled with
[13:28:24] LOG.warning: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/DataCollector/QueryCollector.php on line 380
warninglog
[13:28:24] LOG.warning: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/DataCollector/QueryCollector.php on line 380
warninglog[13:28:24] LOG.warning: strpos(): Passing null to parameter #1 ($haystack) of type string is depreca...
warninglog[13:28:24] LOG.warning: strpos(): Passing null to parameter #1 ($haystack) of type string is depreca...
warninglog[13:28:24] LOG.warning: strpos(): Passing null to parameter #1 ($haystack) of type string is depreca...
warninglog[13:28:24] LOG.warning: strpos(): Passing null to parameter #1 ($haystack) of type string is depreca...
warninglog[13:28:24] LOG.warning: strpos(): Passing null to parameter #1 ($haystack) of type string is depreca...
warninglog[13:28:24] LOG.warning: strpos(): Passing null to parameter #1 ($haystack) of type string is depreca...
warninglog[13:28:24] LOG.warning: strpos(): Passing null to parameter #1 ($haystack) of type string is depreca...
warninglog[13:28:24] LOG.warning: strpos(): Passing null to parameter #1 ($haystack) of type string is depreca...
<...>

### Reproduction steps

Debug mode enabled

### Expected behavior

no warnings

### Snipe-IT Version

Latest pull 7.0.13

### Operating System

ubuntu

### Web Server

apache

### PHP Version

8.3

### Additional context

It may got introduced with recent Snipe-IT updates because a month or so ago logs were empty. (Countered on different installs running latest version)

**Comment by snipe** [comment]
That's fine - they're just warnings.
