### ISSUE TITLE
How to upgrade new version 2.1.0-Pre from v2.0.6-14 using Xammp In windows

### ISSUE THREAD

**Issue by mahesh2471990** [snipe/snipe-it#1568]
Hello @snipe @uberbrady 
Happy New Year Guys.

New year special release version 2.1
Congrats @snipe and your teams.
Lots of bug have been resolved. lots of my old queries will close due to this release i guess. 
Hope so.
As you know i am newbie for Snipe it. I wanted to upgrade my snipeit version to new one.

Already i have hosted in Server 2012 R2 with help of Xampp latest release.
Can any of them Help me to upgrade my snipe it. without database lose.

In document they have mention about this following commands
php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan migrate

But as i am using windows in xampp the upgrading may change..
@snipe please help me out of this.

Composer has been installed
1. Should i download new snipeit-master? after download how to replace. without my database lose?
2. I sued third party tools to backup my database mysql. I have one copy also.

Please tell me procedures

Below image will surely help you.. @snipe you can see what and all option do i get in composer?

![ths image](https://cloud.githubusercontent.com/assets/16305213/12090360/405d49d8-b314-11e5-853c-bb9fb1aeda78.jpg)

**Comment by SK9413** [comment]
https://github.com/snipe/snipe-it/issues/1415

I think it is the proper way to do it.

**Comment by mahesh2471990** [comment]
@SK9413 Hello. I refered #1415. You mention to download new Version 2.1 pre overwrite all content at "C:\xampp\htdocs\snipe-it" /* Before that we have Backup our configuration php right?. and replace again*/
There is any other way to restore my setting as it is?
Actually i did. But it home page came. But my its was not login with my installed Credential.
@SK9413 after upgrading does your Login remain same? or have make change after php artisan migrate command.. How to restore.. Please give me step by step details to upgrade @snipe

**Comment by mahesh2471990** [comment]
@SK9413 hello did u try with latest version??

**Comment by mahesh2471990** [comment]
@SK9413 After i replace and run those command i am not able to login using my Admin user.. What to do? please help me out

**Comment by mahesh2471990** [comment]
When i Login i get error (After upgrading to 2.1 pre) Below image
![capture](https://cloud.githubusercontent.com/assets/16305213/12117413/9db8dda4-b3e6-11e5-882c-d48d106eb9b1.JPG)


Can i change my Default username and password in SQL database? @snipe is it recommended. If i do change where should i do.. Please tell me the steps. Please find the image of sql-->>> Mysql--->users---->"mahesh.hegde" user--->edit. Snapshot below. Please Find your information. @madd15 @snipe.
![combine_images](https://cloud.githubusercontent.com/assets/16305213/12117471/f4e61920-b3e6-11e5-9f63-f2ec7a86682c.jpg)



Can anyone help me out

**Comment by snipe** [comment]
No, you cannot change it manually in the database, as the passwords are encrypted. Just clear your `throttles` table or wait for the throttle time to expire (15 minutes after 5 failed attempts.) Then do a forgotten password request if you can't remember your password.

**Comment by mahesh2471990** [comment]
@Snipe but user is generated when I instal its admin users.. about passsword I have not congfigure mailing till now.. due to some issue.. is der any other way

**Comment by snipe** [comment]
I don't understand what you're trying to tell me. When the user is generated on install, you are the one that enters that password, so you had it at one point or another.

**Comment by mahesh2471990** [comment]
@Snipe I am remembering my password... my problem is with correct password its not loggining... forgot password it goes mail. .and all stuff also mail is not configured due to mail server some internal issue. .. the point is I didn't forget the password after upgrading successful it's not logging with correct password

**Comment by snipe** [comment]
There is no way to reset the password directly in the database.

**Comment by mahesh2471990** [comment]
I know the password..@snipe but you see the snapshot above. . Wer I sent previously.. it's username incorrect.. I don't wer it's going wrong.. in debugging mode also I am not getting any error also

**Comment by snipe** [comment]
In the snapshot above, it says the user is suspended, not that the credentials are wrong. If you're using 2.1.0-pre, it's going to update your password with your LDAP password when you login if you're using LDAP auth. Otherwise, there is no reason your password wouldn't work, as long as your `app/config/production/app.php` key is the same as it was before.

**Comment by mahesh2471990** [comment]
@Snipe is there is any other option I can proceed... ! did you refer my first snapshot which I sent

**Comment by snipe** [comment]
You have to empty the throttles table before you can try to login again since your account is suspended. Try using your local password, and if that doesn't work, try your LDAP password.

**Comment by snipe** [comment]
I'm trying to help you, but you're not giving me useful information. I said:


> In the snapshot above, it says the user is suspended, not that the credentials are wrong. If you're using 2.1.0-pre, it's going to update your local password with your LDAP password when you login if you're using LDAP auth. Otherwise, there is no reason your password wouldn't work, as long as your app/config/production/app.php key is the same as it was before.

And you have not confirmed whether you're running 2.1.0-pre, whether you're using LDAP, or whether you tried with your LDAP password after I just told you 2.1.0-pre will try to update your password on login to match the LDAP password.

If you're using LDAP and your LDAP password doesn't work when you try to login, you can try checking the log files to see what it's trying to do. Otherwise you have no choice but to set up mail and do a forgotten password request.

**Comment by mahesh2471990** [comment]
Same admin user is in ldap also.. with same username.. both way password is same in local also ldap also.. if it's fetch from ldap also the same password is same.. even I tried with other ldap use also.. same error with ldap users also... first local user will not get effected after upgrade right.. 
You told check the key in app.pho.. the key must same as old key or wat? But I have replaced with old app.pho that is 2.06version app.php I replaced

**Comment by snipe** [comment]
> But I have replaced with old app.pho that is 2.06version app.php I replaced

Which app.php? `app/config/app.php` or `app/config/production/app.php`? 

What do your logs say? I'm not going to keep asking the same questions over and over.

**Comment by mahesh2471990** [comment]
I was using 2.06 version and upgraded to 2.1 pre.. yesterday. . After upgrade same problem.. check the second snapshot which I sent.. check yellow highlighted marks..snapshot of my database.. two image I joined it.. see it's carefully.. username and notes

**Comment by snipe** [comment]
Those screenshots don't offer any helpful information.

**Comment by mahesh2471990** [comment]
Config/app.php I replaced which older one.. where do I find the logs

**Comment by mahesh2471990** [comment]
I will send you log copy.. where do I get my logs

**Comment by snipe** [comment]
http://docs.snipeitapp.com/getting-help.html

**Comment by mahesh2471990** [comment]
@snipe 
[2016-01-06 11:05:32] production.DEBUG: LDAP is enabled. [] []
[2016-01-06 11:05:32] production.DEBUG: Sentry lookup complete [] []
[2016-01-06 11:05:32] production.DEBUG: Local user mahesh.hegde exists in database. Authenticating existing user against LDAP. [] []
[2016-01-06 11:05:33] production.DEBUG: User did not authenticate correctly against LDAP. Local user was not updated. [] []
[2016-01-06 11:05:33] production.DEBUG: Authenticating user against database. [] []
[2016-01-06 11:05:33] production.DEBUG: Local authentication: User mahesh.hegde not found [] []

**Comment by mahesh2471990** [comment]
Throttles Tables snapshot below. So account is not Suspended

![captured](https://cloud.githubusercontent.com/assets/16305213/12135783/16bea84e-b466-11e5-869d-acfe2e950b4d.JPG)

Local user was not updated???

**Comment by mahesh2471990** [comment]
@snipe @uberbrady Can you please help me out this problem.. The work has been stopped due this..@snipe log which u asked i have posted it.. please the check the problem and get back to me

**Comment by snipe** [comment]
Enable mail and do a password request. That's the only thing I can tell you. I don't know what you managed to do here. Lots of people have upgraded without any issues.

**Comment by mahesh2471990** [comment]
I configured mail.php

but i am getting error

![mailerror](https://cloud.githubusercontent.com/assets/16305213/12165732/79eca0ca-b546-11e5-83ea-e628163e3df1.JPG)


MAIL SERVER is POSTFIX
mail.php code is

<?php

return array(

    /*
    |--------------------------------------------------------------------------
    | Mail Driver
    |--------------------------------------------------------------------------
    |
    | Laravel supports both SMTP and PHP's "mail" function as drivers for the
    | sending of e-mail. You may specify which one you're using throughout
    | your application here. By default, Laravel is setup for SMTP mail.
    |
    | Supported: "smtp", "mail", "sendmail"
    |
    */

    'driver' => 'smtp',

    /*
    |--------------------------------------------------------------------------
    | SMTP Host Address
    |--------------------------------------------------------------------------
    |
    | Here you may provide the host address of the SMTP server used by your
    | applications. A default option is provided that is compatible with
    | the Postmark mail service, which will provide reliable delivery.
    |
    */

    'host' => 'mail',

    /*
    |--------------------------------------------------------------------------
    | SMTP Host Port
    |--------------------------------------------------------------------------
    |
    | This is the SMTP port used by your application to delivery e-mails to
    | users of your application. Like the host we have set this value to
    | stay compatible with the Postmark e-mail application by default.
    |
    */

    'port' => 587,

    /*
    |--------------------------------------------------------------------------
    | Global "From" Address
    |--------------------------------------------------------------------------
    |
    | You may wish for all e-mails sent by your application to be sent from
    | the same address. Here, you may specify a name and address that is
    | used globally for all e-mails that are sent by your application.
    |
    */

    'from' => array('address' => 'mahitest@velankani.com', 'name' => 'mahitest'),

    /*
    |--------------------------------------------------------------------------
    | E-Mail Encryption Protocol
    |--------------------------------------------------------------------------
    |
    | Here you may specify the encryption protocol that should be used when
    | the application send e-mail messages. A sensible default using the
    | transport layer security protocol should provide great security.
    |
    */

    'encryption' => 'tls',

    /*
    |--------------------------------------------------------------------------
    | SMTP Server Username
    |--------------------------------------------------------------------------
    |
    | If your SMTP server requires a username for authentication, you should
    | set it here. This will get used to authenticate with your server on
    | connection. You may also set the "password" value below this one.
    |
    */

    'username' => 'mahitest',

    /*
    |--------------------------------------------------------------------------
    | SMTP Server Password
    |--------------------------------------------------------------------------
    |
    | Here you may set the password required by your SMTP server to send out
    | messages from your application. This will be given to the server on
    | connection so that the application will be able to send messages.
    |
    */

    'password' => 'mahi123',

    /*
    |--------------------------------------------------------------------------
    | Sendmail System Path
    |--------------------------------------------------------------------------
    |
    | When using the "sendmail" driver to send e-mails, we will need to know
    | the path to where Sendmail lives on this server. A default path has
    | been provided here, which will work well on most of your systems.
    |
    */

    'sendmail' => '/usr/sbin/sendmail -bs',

    /*
    |--------------------------------------------------------------------------
    | Mail "Pretend"
    |--------------------------------------------------------------------------
    |
    | When this option is enabled, e-mail will not actually be sent over the
    | web and will instead be written to your application's logs files so
    | you may inspect the message. This is great for local development.
    |
    */

    'pretend' => false,

);


@snipe can you look into this error.

**Comment by snipe** [comment]
`mail` is not a valid hostname.

**Comment by mahesh2471990** [comment]
@snipe i tried with ip address also
10.0.9.95
which is nothing but host-name is mail itself.
dns record is there. i tried with FQDN also. Same  error

**Comment by mahesh2471990** [comment]
@snipe 
In mail.php file i have also put
'host' => 'mail.ind.com', /* that is fQDN*/

@snipe for your refer
This is my Log of postfix Server
Transcript of session follows.

 Out: 220 mail.ind.com ESMTP Postfix (2.6.6)
 In:  EHLO [::1]
 Out: 250-mail.ind.com
 Out: 250-PIPELINING
 Out: 250-SIZE 26214400
 Out: 250-VRFY
 Out: 250-ETRN
 Out: 250-AUTH PLAIN LOGIN
 Out: 250-AUTH=PLAIN LOGIN
 Out: 250-ENHANCEDSTATUSCODES
 Out: 250-8BITMIME
 Out: 250 DSN
 In:  STARTTLS
 Out: 502 5.5.1 Error: command not implemented

Session aborted, reason: lost connection

**Comment by mahesh2471990** [comment]
@snipe I was cross checking in my mail server
'encryption' => 'tls',

tls has been commented in my postfix

can i keep
'encryption' => 'none',  /* or NULL which is perfect syntax for that? @snipe

**Comment by snipe** [comment]
I don't know, as it's not documented in Laravel, but I would try `null`

**Comment by mahesh2471990** [comment]
I tried NULL but 
[2016-01-07 15:34:16] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Maximum execution time of 30 seconds exceeded' in C:\xampp\htdocs\snipe-it\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php:163
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []


![nullerror](https://cloud.githubusercontent.com/assets/16305213/12167853/a95c976c-b554-11e5-98e1-7c09d4654add.JPG)

**Comment by snipe** [comment]
Try using the `mail` driver instead of SMTP

**Comment by mahesh2471990** [comment]
I tried before also with mail driver.
It will successful message.
But i wont receive the mail.
there is no mail flow in mail server

Now again i tried with same. with 'encryption' => 'tls', and 'encryption' => 'NULL, also same result
there is no mail flow. in mail server

@snipe Enabling tls is not recommend way in our Production Mail server i guess?
some setting may change right?

**Comment by mahesh2471990** [comment]
@snipe In this new version is there any changes in password complexity requirements.

I guess.. due to that my old password was not taking. i was of only 6 character.
But it is problem for LDAP user. Some user password may be less then 10 character.
How to revert old password complexity @snipe  we can force users to put minimum 10 character right again?.. So that should be avoided. So anmore ldap user who is having more 10 character only they can login. 

The old mail didnt configure i tried with Gmail and reset password. after login i would see
![error](https://cloud.githubusercontent.com/assets/16305213/12169025/15662de0-b55c-11e5-9894-020d0b34fc33.JPG)


So many quries. What should i do to this

**Comment by snipe** [comment]
If you're using LDAP, the password length shouldn't matter. You shouldn't be changing the user's password locally if they're using LDAP to login.

**Comment by mahesh2471990** [comment]
ya.. i didnt do.. but ldap user must be imported right? to local.
During login it will authenticate with Active directory server. But its not login with Ldap users password.
I trying to login with ldap user and password

**Comment by snipe** [comment]
On 2.1.0-pre, it will try to authenticate with LDAP, and if the credentials for LDAP go through, it will update the user to use the LDAP password they entered. If the user exists in LDAP and doesn't exist locally, it will create them.

**Comment by mahesh2471990** [comment]
I have new issues better i go new tickets.
Thanks for your support
