### ISSUE TITLE
v2.1.0-pre

### ISSUE THREAD

**Issue by sysnoo** [snipe/snipe-it#1569]
Is this version Ok for prod?

**Comment by zmorrow** [comment]
Just updated mine and all looks good so far, really enjoy the new Custom Fields option.

**Comment by ddreier** [comment]
The "pre" in 2.1.0-pre mean pre-release. Run in production at your own risk.

**Comment by sysnoo** [comment]
Thanks..It's kind of Release Candidate.
I will wait for the final stable release.

**Comment by ddreier** [comment]
You should close the issue if your question is answered.
