### ISSUE TITLE
Asset Model Name uniqueness

### ISSUE THREAD

**Issue by ddreier** [snipe/snipe-it#1572]
It was discussed and decided in #948 that Asset Model names should not need to be unique. I'm having an issue where I can not create a new Model with a duplicate name for a specific name. I have a couple sets of Models with duplicate names, and I can create new models for one, but not the other.

![image](https://cloud.githubusercontent.com/assets/82290/12098126/c3706636-b2e5-11e5-9144-315aac193ed5.png)

In the above image, I have 4 "Acer 19" LCD Monitor" three of which existed before 2.1.0 and I created the fourth one ("asdfasdf") after 2.1.0. There are also five "Dev Box" Models, three of which existed before 2.1.0 and two I created after, but had to put a number at the end because I could not create them with the same name.

![image](https://cloud.githubusercontent.com/assets/82290/12098202/38930518-b2e6-11e5-907c-c2b531d759db.png)

The same issue exists when I try to edit one of the existing "Dev Box" models.

**Comment by SK9413** [comment]
+1

**Comment by Jason707** [comment]
+1 Same problem :(

**Comment by snipe** [comment]
The uniqueness prevents the same model name only if it also has the same model number AND manufacturer.

```
$validator = Validator::make(
            // Validator data goes here
            array(
                'unique_fields' => array(Input::get('name'), Input::get('modelno'), Input::get('manufacturer_id'))
            ),
            // Validator rules go here
            array(
                'unique_fields' => 'unique_multiple:models,name,modelno,manufacturer_id'
            )
        );
```

**Comment by snipe** [comment]
In testing this, I can create multiple models of `22-inch T897`, with the manufacturer `Accumsan`, as long as the model number is different.

<img width="785" alt="screen shot 2016-01-12 at 9 40 55 pm" src="https://cloud.githubusercontent.com/assets/197404/12286008/34c51d1e-b975-11e5-9fe4-0af93d5a03d8.png">

<img width="820" alt="screen shot 2016-01-12 at 9 42 29 pm" src="https://cloud.githubusercontent.com/assets/197404/12286039/913b935c-b975-11e5-9cb2-f6d15c81e3e5.png">

<img width="854" alt="screen shot 2016-01-12 at 9 42 40 pm" src="https://cloud.githubusercontent.com/assets/197404/12286040/9c1bba4a-b975-11e5-88c5-8b877077dab9.png">

<img width="865" alt="screen shot 2016-01-12 at 9 42 57 pm" src="https://cloud.githubusercontent.com/assets/197404/12286043/a2c56cec-b975-11e5-8e17-d2390729aad7.png">

**Comment by ddreier** [comment]
I changed all of my "Dev Box" and "Dev Box #" Models to be named "DevBox" successfully (so now I have 5 "DevBox" Models). On trying to set one of them back to "Dev Box" I was unable to do so.

I have two deleted Models that also have the name "Dev Box" which I'm guessing might be related. But why would the validator treat them differently?

**Comment by snipe** [comment]
Do they have the same manufacturer and model ID?

**Comment by ddreier** [comment]
Nope, different manufacturer and model number.

**Comment by snipe** [comment]
Even the deleted ones, nothing in common with the non-deleted ones?

**Comment by ddreier** [comment]
Correct.
![image](https://cloud.githubusercontent.com/assets/82290/12298292/f9af37c0-b9d6-11e5-8e93-107cd7da432a.png)
(Showing you from the database, because viewing deleted Models in the UI isn't working :wink:)

Manufacturer 5 is "IT."

**Comment by ddreier** [comment]
I can repro on the develop demo. Earlier I created a bunch of ASUS "Test Model" Models, then deleted them. Now I cannot create a model named "Test Model" with any manufacturer.

**Comment by snipe** [comment]
So I'm unclear - what is the pattern here?

**Comment by snipe** [comment]
(Also, which demo are you using? demo.snipeitapp.com or develop.snipeitapp.com?)

**Comment by ddreier** [comment]
My current understanding of the issue is that I can't reuse the Model Name of a deleted Asset Model.

I'm on develop.snipeitapp.com.

**Comment by snipe** [comment]
You should just be able to restore the deleted one

**Comment by ddreier** [comment]
That's not the point. I can't make a new Model with the same Model Name, period, if there is a deleted one with the same name.

**Comment by ddreier** [comment]
:+1:

**Comment by Jason707** [comment]
Thank you for getting back to me! I think the problem was because of
deleted items that were interfering. I restored them and renamed them and
then I was able to change the model number as you have described.



Is there a way to clear out all deleted items and such? We have a lot due
to importing errors on our part.



Lastly I have come across something maybe a bug? When I generate labels if
the name is over 26 characters it prints blank QR codes no serial or
truncated name.



Jason







*From:* snipe [mailto:notifications@github.com]
*Sent:* Tuesday, January 12, 2016 9:44 PM
*To:* snipe/snipe-it <snipe-it@noreply.github.com>
*Cc:* Jason707 <jgriswold@uusd.net>
*Subject:* Re: [snipe-it] Asset Model Name uniqueness (#1572)



In testing this, I can create multiple models of 22-inch T897, with the
manufacturer Accumsan, as long as the model number is different.

[image: screen shot 2016-01-12 at 9 40 55 pm]
<https://cloud.githubusercontent.com/assets/197404/12286008/34c51d1e-b975-11e5-9fe4-0af93d5a03d8.png>

[image: screen shot 2016-01-12 at 9 42 29 pm]
<https://cloud.githubusercontent.com/assets/197404/12286039/913b935c-b975-11e5-9cb2-f6d15c81e3e5.png>

[image: screen shot 2016-01-12 at 9 42 40 pm]
<https://cloud.githubusercontent.com/assets/197404/12286040/9c1bba4a-b975-11e5-88c5-8b877077dab9.png>

[image: screen shot 2016-01-12 at 9 42 57 pm]
<https://cloud.githubusercontent.com/assets/197404/12286043/a2c56cec-b975-11e5-8e17-d2390729aad7.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/snipe/snipe-it/issues/1572#issuecomment-171176760>.

**Comment by ddreier** [comment]
> I think the problem was because of deleted items that were interfering. I restored them and renamed them and then I was able to change the model number as you have described.

Did the deleted models collide in any way other than name?

> Is there a way to clear out all deleted items and such? We have a lot due to importing errors on our part.

Not through the UI.

> Lastly I have come across something maybe a bug? When I generate labels if the name is over 26 characters it prints blank QR codes no serial or truncated name.

There's already an issue open for this.

**Comment by Jason707** [comment]
Looking at it more closely I think the deleted item might have had the exact same name. made an item "test" with model 100 deleted it was able to make new item "test" with a model 101 but not able to make test with model 100 (same as deleted item)

**Comment by SK9413** [comment]
Hi I am wondering if you guys can access the "Deleted Assets Model" Page? Because I cannot access it to restore deleted assets model to change its name/ model no. even on the demo site. https://github.com/snipe/snipe-it/issues/1565

**Comment by snipe** [comment]
@SK9413 what do you mean you can't access it?

Also, which demo? demo.snipeitapp.com or develop.snipeitapp.com?

**Comment by SK9413** [comment]
Hi snipe,

I cannot access "Deleted Assets Model" page at demo.snipeitapp.com (Using both IE and Chrome)

**Comment by snipe** [comment]
What does "cannot access" mean? Are you getting a browser error? It's loading fine for me. 

https://demo.snipeitapp.com/hardware/models?status=Deleted

**Comment by SK9413** [comment]
![model1](https://cloud.githubusercontent.com/assets/15903195/12342755/9be46aa0-bb68-11e5-904b-0a842bdc9bd6.jpg)
![model2](https://cloud.githubusercontent.com/assets/15903195/12342757/9ea88b2c-bb68-11e5-9e67-44355ad3e344.jpg)

I created a model called "test model" and deleted it. But i cannot find it and restore it by clicking "View Deleted" at the asset model page. It only shows the normal assets model.

**Comment by snipe** [comment]
This has already been fixed.

**Comment by Jason707** [comment]
I have come across a new problem, I have multiple items with same "asset model name" and I am unable to update any of their information. I am unable to change model numbers or upload model images I get "the name has already been taken"
![capture1](https://cloud.githubusercontent.com/assets/16672977/12360250/b832ad04-bb6b-11e5-8deb-2127c9c06fc5.JPG)
![capture2](https://cloud.githubusercontent.com/assets/16672977/12360256/c0035d3a-bb6b-11e5-984c-546764d5ddf6.JPG)

**Comment by snipe** [comment]
I don't think this is a new issue, I think this is the old issue, and it's already been fixed on develop

**Comment by ddreier** [comment]
@snipe Just tested this on my 2.1.0, and both demos, and it's broken. I thought I tested it after you added the `deleted_at` constraint, but maybe it was between removing the uniqueness requirement altogether and adding `deleted_at`.
