### ISSUE TITLE
Please add currency: CNY (Chinese Yuan)

### ISSUE THREAD

**Issue by kt1024** [snipe/snipe-it#1574]
the symbol for CNY is ¥
thanks.

**Comment by moniruss** [comment]
Is it possible to add currency other than the given ones manually by myself? or by other means?

**Comment by dmeltzer** [comment]
Take a look at the $currencies variable in app/macros.php.  It should be fairly self explanatory.  I'd still recommend opening an issue here if you find a missing currency (so it can be added for everyone else) but you can manually edit the files temporarily if you need to.
