### ISSUE TITLE
Delete Asset Maintenance will delete status label

### ISSUE THREAD

**Issue by wvanhiele** [snipe/snipe-it#1576]
When clicking the delete button under Actions for an Asset Maintenance, it is not deleting the Asset Maintenance entry but a Status Label with that ID.
When i hover with a mouse over the delete button for the first entry the link is:
/admin/settings/statuslabels/1/delete

So please can you also tell me what StatusLabel with ID 1 should be by default so i can recreate it?

**Comment by dmeltzer** [comment]
The good news is that nothing in snipe-it is ever permanently deleted.  The bad news is that currently there isn't a way in the UI to "undelete" items.  It should be simple to do manually in the db though.  Check your status_labels table in the database, there probably is a value in the `deleted_at` field.  Something like the (untested) following should restore the deletedstatus label.
`UPDATE status_labels SET deleted_at = NULL where id = '1'`.  Obviously the asset_maintence shouldn't delete a status label, but this should at least fix it!

**Comment by dmeltzer** [comment]
This bug looks like it's fixed in 2.1-pre as well, commit bb83814

**Comment by wvanhiele** [comment]
Thanks, fixed it manually in my 2.0.6 as well now
