### ISSUE TITLE
Creating supplier on create asset page won't work

### ISSUE THREAD

**Issue by wvanhiele** [snipe/snipe-it#1581]
When on the Create Asset page (/hardware/create) and then creating a new Supplier by using the + sign after supplier, this results in an "undefined undefined" entry in the dropdown list.
When refreshing the page, the new supplier is not added.

**Comment by ddreier** [comment]
What version are you using?

**Comment by wvanhiele** [comment]
version 2.0.6 (which is listed as (v2.0.5-pre) on the page) and running it on Windows IIS (and client on Chrome)

**Comment by dmeltzer** [comment]
I can reproduce on 2.0.6, but it looks like it's been fixed in 2.1-pre
