### ISSUE TITLE
Checkout Assets to Location instead of user in 2.1.0-pre

### ISSUE THREAD

**Issue by brianjking** [snipe/snipe-it#1584]
@snipe @uberbrady 

Is it possible in 2.1.0-pre to checkout assets to a "location" instead of a "user"? I believe this was supposed to be in this milestone, however, I'm not sure if it made it in?

I'm currently using the same _workflow_ as seen in #659 where I create "locations" as "users" and checkout the assets to them.

Thanks! Keep up the awesome work! Very much appreciate it.

**Comment by snipe** [comment]
It did not make it into this release.

**Comment by brianjking** [comment]
@snipe Bummer, thanks for the update. Is it planned under a particular upcoming release I can see on your waffle.io board or milestone tracking here on Github? Thanks again!

**Comment by brianjking** [comment]
Looks like it may be part of 3.0's milestone in #142 showing scheduled for the end of January.

**Comment by snipe** [comment]
Yes, I updated the milestones right before this release.
