### ISSUE TITLE
Feature Request - Universal Search Box

### ISSUE THREAD

**Issue by hansenc0705** [snipe/snipe-it#1586]
Any thoughts on adding a universal search box of some kind? something where you could give it a serial number, asset tag, person's name and it be able to return any and all data it has based off whatever you enter?

would be nice to have this box in the top nav so you can log in and start searching for whatever you are looking for.

**Comment by snipe** [comment]
Lots of thoughts, but it's non-trivial from a backend perspective, and also a UX perspective. What would the results even look like?

**Comment by hoolius** [comment]
What about adding it to the topnav with a dropdown to narrow the search (Asset, License, User)? For our purposes just being able to search assets from the dashboard or topnav would be very useful.

**Comment by kobie-chasehansen** [comment]
that would be cool, some type of box with a button that also has a drop down. enter the search terms, click the button to reveal the options and select the one you want. I know my use case I mostly type in an asset tag, serial number, or search for a person.
