### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by jacp9** [snipe/snipe-it#1589]
Hi,

I am running: 

Snipe-IT version 	v2.0.6-14-g74ed75d
PHP Version 	5.5.9-1ubuntu4.14
Laravel Version 	4.2.17 

I encounter some issues with the latest Snipe IT asset tracking system.

One particular user has got about 400 assets and when I try to view his profile I get the following error (attached a screenshot) - it only happens to this one, I think shortly after deleting some locations (IN GUI, NOT THE DB BACKEND) % (no assets were assigned to these locations) i checked the whole DB for location_id and rtd_location_id if theres anything assigned to these locations but no results:
![capture](https://cloud.githubusercontent.com/assets/16577946/12145802/3d23b052-b488-11e5-9325-9699439f0c23.PNG) 

ErrorException (E_ERROR)
Trying to get property of non-object (View: /usr/local/www/<sitenamehere>/app/views/backend/users/view.blade.php) 
 /usr/local/www/<sitenamehere>/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php 

    		// an exception is thrown. This prevents any partial views from leaking.
    		try
    		{
    			include $__path;
    		}
    		catch (\Exception $e)
    		{
    			$this->handleViewException($e, $obLevel);
    		}
     

Do you know how to fix these issues?

i think this happened after I deleted some locations, although no assets were assigned to these locations.
I can still see them in SQL database, even if I change deleted_at back to (null) it won't make any difference.
I removed every entry from asset_logs table but still no luck.

Here is the content of this error from app/storage/logs

Next exception 'ErrorException' with message 'Trying to get property of non-object (View: /usr/local/www/my_site/app/views/backend/users/view.blade.php)' in /usr/local/www/my_site/app/storage/views/a355dd2f186168b516c4$
Stack trace:
#0 /usr/local/www/my_site/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /usr/local/www/my_site/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/usr/local/www/...', Array)
#2 /usr/local/www/my_site/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/usr/local/www/...', Array)
#3 /usr/local/www/my_site/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#4 /usr/local/www/my_site/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#5 /usr/local/www/my_site/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#6 /usr/local/www/my_site/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /usr/local/www/my_site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /usr/local/www/my_site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 /usr/local/www/my_site/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /usr/local/www/my_site/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /usr/local/www/my_site/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /usr/local/www/my_site/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /usr/local/www/my_site/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 /usr/local/www/my_site/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /usr/local/www/my_site/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /usr/local/www/my_site/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /usr/local/www/my_site/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /usr/local/www/my_site/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main}

**Comment by snipe** [comment]
Did you also check the `asset_logs` table for `location_id` that matches the deleted ones? If you tried manually restoring the locations (by setting their `deleted_at` to `NULL` and it didn't see a difference, than that seems unlikely to help though. 

Can you show me the lines in `/usr/local/www/my_site/app/views/backend/users/view.blade.php` that are actually triggering the error?

**Comment by jacp9** [comment]
Yes, I have checked the whole db for these id's and nothing is assigned to them so this shouldn't be a problem. That's exactly what I did and didn't help unfortunately. 

how can I tell which lines are actually triggering the error? I've attached a screenshot of the error in debug mode. Is it line 40, 41 and 42? This is what is highlighted on the error message?

		{
			$this->handleViewException($e, $obLevel);
		}

**Comment by snipe** [comment]
It's hard to explain. :-/

You have to walk through the stack trace files on the left until you see details related to assets or locations.

**Comment by jacp9** [comment]
Ok I went through all of the stack trace files on the left and the only thing I can see related to assets or locations is this:
![new1](https://cloud.githubusercontent.com/assets/16577946/12169858/d998af90-b533-11e5-905f-212a35710bee.PNG)

All other errors are just some code but nothing related to assets or anything like that

**Comment by snipe** [comment]
Excellent work. I'm glad you figured that out, because I couldn't imagine how I could explain how to find that. :P 

Okay, so it looks like someone must have deleted something from the database. It's looking for an associated asset model that doesn't exist. Check the entries in the `models` table and then check the assets to see if there are any references (via the `model_id` column) to models that don't exist.

**Comment by jacp9** [comment]
Got it! One asset was pointing to the model_id which didn't exist. Recreated the model with new ID, changed the model_in in assets to point to the new one and all is good again. I really don't know how this could have vanished. Anyway, thank you very much! 

Also, do you know the LDAP query so it only pulls users who have a mailbox (mail=*) and home directory homeDirectory=* ?
I tried so many different filters but no luck and ended up with AD query, export to CSV and then import to Snipe. It would be nice to automate it, but no pressure about it.

**Comment by snipe** [comment]
@jacp9 not sure, @ddreier might know

**Comment by ddreier** [comment]
I'm definitely no LDAP query expert, but I think that `(&(mail=*)(homeDirectory=*))` should do what you ask. If you already have a big filter with an AND I think you should be able to stick `(mail=*)(homeDirectory=*)` in there anywhere*.

Here's how I think my filter would look if I added those:
```
&(objectcategory=person)(objectclass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(mail=*)(homeDirectory=*)
```
(Remember that Snipe-IT adds the outer-most parenthesis for you)

\* probably not *anywhere*, but hopefully my example was clear

**Comment by jacp9** [comment]
@ddreier I tried using your LDAP filter and good news - it filters everything correctly and pulls the users! I didn't know that Snipe-IT adds the outer-most parenthesis and this is where I went wrong as I did the outer-most parenthesis too.

Now I have an issue with some things, it doesn't populate e-mail address field for the user (although the user have mail field populated in Active Directory) and it doesn't assign them to 'users' group. 

The LDAP e-mail field in Admin web interface has got 'mail' value which is correct for AD.

Do you know how to fix it @ddreier or @snipe ?

Thanks!

**Comment by ddreier** [comment]
The main attribute issue is fixed in the latest develop version and will be fixed in 2.1.0.

**Comment by jacp9** [comment]
Oh so it is known issue and this is why my LDAP does not pull email field and user group? Do you know when 2.1.0 will be released?

**Comment by ddreier** [comment]
The LDAP importer does not pull in group membership. Only the attributes listed in Settings.

I don't know when 2.1.0 will be released, but it'll probably be soon.

**Comment by abdulrehmanch** [comment]
Hi!! I have the same issue.

Trying to get property of non-object (View: D:\WORK\PHP\snipe-it-2.1.0-pre\app\views\backend\layouts\default.blade.php) (View: D:\WORK\PHP\snipe-it-2.1.0-pre\app\views\backend\layouts\default.blade.php)

`<meta charset="utf-8" />
        <title>
            <?php $__env->startSection('title'); ?>
             <?php echo e(Setting::getSettings()->site_name); ?>

            <?php echo $__env->yieldSection(); ?>
        </title>`

**Comment by ddreier** [comment]
@abdulrehmanch You should open your own issue. Please include all information requested at http://docs.snipeitapp.com/getting-help.html.

**Comment by priyag597** [comment]
Hi,

Laravel Version: 5.7.14
 Voyager Version: 1.1.1 
PHP Version: 7.2

I encounter some issues with the latest voyager setup

I tried to edit user bread i get this following  error 

![image](https://user-images.githubusercontent.com/46341574/50736169-0eca5b80-11e0-11e9-81ae-2b7c7a732409.png)


"Trying to get property 'type' of non-object"  when 
1.I am trying to edit admin user profile
2. there is users nav option when click on it same problem occurring In voyager admin panel.
![image](https://user-images.githubusercontent.com/46341574/50736163-f22e2380-11df-11e9-823b-007eda1b6bf5.png)

Do you know how to fix these issues?
