### ISSUE TITLE
Update Snipe to Latest version

### ISSUE THREAD

**Issue by charlesvline** [snipe/snipe-it#1593]
Hi Snipe,

Our environment is using snipe for IT asset management. Thanks for the great product. Now we plan to update it to latest version.

Current setup: 
1 Snipe 1.2.8
2 Use MySqL
3 uses PHP 5.4
4 IIS 8 on Server 2008 R2

In your docu, "Simply pull down the newest release, copy the files over, and run whatever commands the release notes specify. Your configuration files won’t be overwritten, since you had to copy them over from the example configs, and your version isn’t in version control."

Could you please guide me through which files I need to copy over? I am confused why it wont be overwritten? 

Thanks

**Comment by snipe** [comment]
"Your configuration files won’t be overwritten, since you had to copy them over from the example configs, and your version isn’t in version control." When you installed it, you had to copy the `.example.php` files over, so they don't exist in our version.
