### ISSUE TITLE
LDAP sync does not work

### ISSUE THREAD

**Issue by ltt** [snipe/snipe-it#1594]
It just showed Server Error: 500 (Internal Server Error) after clicking on "synchronize". I had same problem with previous version and I just upgraded to the pre-release today but still no success

**Comment by snipe** [comment]
http://docs.snipeitapp.com/getting-help.html
We need to see log files or error messages.

**Comment by ltt** [comment]
thank you for your prompt feedback

Below is the error message

Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
HELP
Call to undefined function Controllers\Admin\ldap_connect()

and log

production.ERROR: exception 'ErrorException' with message 'stream_socket_enable_crypto(): SSL: crypto enabling timeout' in /opt/snipe-it/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:95
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'stream_socket_e...', '/opt/snipe-it/v...', 95, Array)
#1 /opt/snipe-it/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php(95): stream_socket_enable_crypto(Resource id #333, true, 3)
#2 /opt/snipe-it/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(314): Swift_Transport_StreamBuffer->startTLS()
#3 /opt/snipe-it/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(118): Swift_Transport_EsmtpTransport->_doHeloCommand()
#4 /opt/snipe-it/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#5 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(329): Swift_Mailer->send(Object(Swift_Message), Array)
#6 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(151): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#7 /opt/snipe-it/bootstrap/compiled.php(3271): Illuminate\Mail\Mailer->send('emails.expiring...', Array, Object(Closure))
#8 /opt/snipe-it/app/commands/SendExpirationAlerts.php(98): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#9 /opt/snipe-it/app/commands/SendExpirationAlerts.php(98): Illuminate\Support\Facades\Mail::send('emails.expiring...', Array, Object(Closure))
#10 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Command.php(112): SendExpirationAlerts->fire()
#11 /opt/snipe-it/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /opt/snipe-it/vendor/symfony/console/Symfony/Component/Console/Application.php(889): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /opt/snipe-it/vendor/symfony/console/Symfony/Component/Console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(SendExpirationAlerts), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /opt/snipe-it/vendor/symfony/console/Symfony/Component/Console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /opt/snipe-it/artisan(59): Symfony\Component\Console\Application->run()
#17 {main} [] []

**Comment by snipe** [comment]
http://www.craiglotter.co.za/2012/08/30/php-warning-stream_socket_enable_crypto-this-stream-does-not-support-sslcrypto/
