### ISSUE TITLE
Login + Edit settings break if LDAP password is set and app key is changed

### ISSUE THREAD

**Issue by swoopdk** [snipe/snipe-it#1595]
If we have ldap settings and ldap key set, and then later change the app key two things can break. 

1. if debug is enabled the whole login breaks with a message about
MAC is invalid.

2. If debug=false then we can login but edit settings page breaks with same message. 

Solution i found with @snipe was to clear out the ldap_pword and set ldap_enabled=0 and then re-logging in and setting the values again.

**Comment by snipe** [comment]
The app key should never be changed, but as in your case, that's not always an option for docker if you're going to re-use the same database. We need to patch that docker setup to clear the LDAP password.

**Comment by swoopdk** [comment]
Agreed. 

However i thought up a solution for various docker people. 

If a docker using person makes a Dockerfile and includes a small script that can be included in their variant of the Docker image. This script could perform migrations, set the key to something only they know and perhaps other customizations for them. 
Of course not easy to distribute nor make, but just a solution for other people i think i might adopt. I'm already brewing my docker image from the dockerhub one and adding stuff like my SSL certs ect, so shouldnt't be a big change for me to also have a script to change the key :)

**Comment by tmongero** [comment]
I was receiving the same error message indicating INVALID MAC, and in my case this was caused by changing the app key. Luckily, I had backed up the previous directory and copied the original key into the app.php file, fixing the issue.

**Comment by snipe** [comment]
Yes, as mentioned, the app key should never change. Whenever you see INVALID MAC, it's because your app key has changed so it cannot decrypt the LDAP password you encrypted when you saved it in the settings.

**Comment by tmongero** [comment]
So, I changed the app key back in app.php (under /app/config/production), but now I'm getting a QueryException explaining:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'ldap_server_cert_ignore' in 'field list' (SQL: update `settings` set `updated_at` = 2016-01-07 18:32:32, `ldap_pword` = <Excluded hashed password>, , `ldap_email` = mail, `ldap_server_cert_ignore` = 0 where `id` = 1)

I did a little research and found out that when you run the php artisan key:generate command, it alters the .env file (I'm assuming docker.env), so I went into this file and in fact the mysql password (under DATABASE VARIABLES) was incorrect.

Any insight here?

**Comment by snipe** [comment]
Just looks like you need to run migrations. It's missing a field that was added.

**Comment by tmongero** [comment]
@snipe Thanks so much. Working perfectly now.

**Comment by uberbrady** [comment]
@swoopdk you should be able to mount your directory that has your certificates and use that, making it so that you don't have to tweak the Docker image.

My big concern is this: we can't have an image living on Dockerhub that has an app key burned into it; that's an enormous security risk and tremendously dangerous.

My inclination - on at least one side of the fence, here - is to wrap a `try/catch` block around the decryption of the LDAP password, and then give the user a good error message. We may also be able to modify the `app.php` so that it will respect an environment variable for the app key as well - so that you can discard or upgrade docker containers without breaking LDAP.

But we'd still need to handle file uploads; they need to not live on the container and should instead get mapped somewhere else - another volume, perhaps, or something. Not sure.

**Comment by swoopdk** [comment]
@uberbrady i totally agree. Thats why i customize my local docker image from the docker hub image using the "from" in my Dockerfile to add stuff like certificate and other small options. Also used it to make sure it was running SSL when the dockerimage wasnt SSL enabled. 

It's a little easier for me to have a Dockerimage that rolls all my custom changes into a local image that works rather than having a huge docker run command where i break stuff should anything be missing. 

But i totally agree. The whole docker scenario requires some planning to work alright. Example i add a logo in my Dockerfile since it's also part of the container storage and gets deleted. 

But for now to fix the bug in question if we have a try/catch like you suggest and either give a good error message or possibly even give the user the option of simply clearing out the ldap password from the DB right there at the error screen ?

**Comment by Bhairava123** [comment]
Your app key has changed! Could not decrypt LDAP password using your current app key, so LDAP authentication has been disabled
