### ISSUE TITLE
After Upgrade 2.1 pre. custom field is not available

### ISSUE THREAD

**Issue by mahesh2471990** [snipe/snipe-it#1596]
@snipe 
After i upgraded to v2.1 pre also. But i am not able see the Custom Field
Snapshot below
![custom field](https://cloud.githubusercontent.com/assets/16305213/12170694/75ecd94a-b569-11e5-944c-0411c8bc4d67.JPG)

Any things you needed for reference let me know

**Comment by snipe** [comment]
I couldn't begin to know why this is happening. We're using 2.1.0-pre in production and haven't seen this at all.

When you view source, do you see the Custom Fields link in that nav item?

Honestly don't know how you're having so much trouble.

**Comment by mahesh2471990** [comment]
@snipe ha ha.. I dont know why only me.. lol
Ok where exactly i can find view source?

**Comment by snipe** [comment]
View the source in your web browser.

**Comment by mahesh2471990** [comment]
<a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-wrench fa-fw"></i> Admin                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="http://10.0.9.50/admin/settings/companies">
                                <i class="fa fa-building-o fa-fw"></i> Companies                            </a>
                        </li>
                        <li>
                            <a href="http://10.0.9.50/hardware/models">
                                <i class="fa fa-th fa-fw"></i> Asset Models                            </a>
                        </li>
                        <li>
                            <a href="http://10.0.9.50/admin/settings/categories">
                                <i class="fa fa-check fa-fw"></i> Categories                            </a>
                        </li>
                        <li>
                            <a href="http://10.0.9.50/admin/settings/manufacturers">
                                <i class="fa fa-briefcase fa-fw"></i> Manufacturers                            </a>
                        </li>
                        <li>
                            <a href="http://10.0.9.50/admin/settings/suppliers">
                                <i class="fa fa-credit-card fa-fw"></i> Suppliers                            </a>
                        </li>
                        <li>
                            <a href="http://10.0.9.50/admin/settings/statuslabels">
                                <i class="fa fa-list fa-fw"></i> Status Labels                            </a>
                        </li>
                        <li>
                            <a href="http://10.0.9.50/admin/settings/depreciations">
                                <i class="fa fa-arrow-down fa-fw"></i> Depreciation                            </a>
                        </li>
                        <li>
                            <a href="http://10.0.9.50/admin/settings/locations">
                                <i class="fa fa-globe fa-fw"></i> Locations                            </a>
                        </li>
                        <li>
                            <a href="http://10.0.9.50/admin/groups">
                                <i class="fa fa-group fa-fw"></i> Groups                            </a>
                        </li>
                        <li>
                            <a href="http://10.0.9.50/admin/settings/backups">
                                <i class="fa fa-download fa-fw"></i> Backups                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="http://10.0.9.50/admin/settings/app">
                                <i class="fa fa-cog fa-fw"></i> Settings                            </a>
                        </li>

                    </ul>
                </li>

NO there is not custom field there

**Comment by snipe** [comment]
If you don't see custom fields, you're not running 2.1.0-pre.

**Comment by mahesh2471990** [comment]
<?php
return array (
  'app_version' => 'v2.1.0-pre',
  'hash_version' => 'v2.1.0-pre-g4aa3768',
);

in snapshot above also u can see the version at end

**Comment by snipe** [comment]
I don't know what to tell you. Maybe you only pulled over some files, but 2.1.0-pre has custom fields, and it would be in the nav if that's what you were running.

**Comment by mahesh2471990** [comment]
No snipe i promise.. I downloaded the snipe master 2.1pre replaced with older one..

![view](https://cloud.githubusercontent.com/assets/16305213/12171479/449a6874-b570-11e5-82ff-8b60a142d060.JPG)

**Comment by mahesh2471990** [comment]
I got all other feature i guess like Deleted user there is new icon to restore the user directory.
in setting ldap SSL enabled checkbox.. Only custom field is not appearing i dont know why?
I have been irritating you from hours i guess

**Comment by snipe** [comment]
And I promise you, if all of the files were there, you'd be seeing custom fields. There is literally no logic preventing that from showing up.

Paste in lines 250-300 in `app/views/backend/layout/default.php`.

**Comment by mahesh2471990** [comment]
@if(Sentry::getUser()->hasAccess('admin'))
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-wrench fa-fw"></i> @lang('general.admin')
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li{{ (Request::is('admin/settings/companies*') ? ' class="active"' : '') }}>
                            <a href="{{ URL::to('admin/settings/companies') }}">
                                <i class="fa fa-building-o fa-fw"></i> @lang('general.companies')
                            </a>
                        </li>
                        <li{{ (Request::is('hardware/models*') ? ' class="active"' : '') }}>
                            <a href="{{ URL::to('hardware/models') }}">
                                <i class="fa fa-th fa-fw"></i> @lang('general.asset_models')
                            </a>
                        </li>
                        <li{{ (Request::is('admin/settings/categories*') ? ' class="active"' : '') }}>
                            <a href="{{ URL::to('admin/settings/categories') }}">
                                <i class="fa fa-check fa-fw"></i> @lang('general.categories')
                            </a>
                        </li>
                        <li{{ (Request::is('admin/settings/manufacturers*') ? ' class="active"' : '') }}>
                            <a href="{{ URL::to('admin/settings/manufacturers') }}">
                                <i class="fa fa-briefcase fa-fw"></i> @lang('general.manufacturers')
                            </a>
                        </li>
                        <li{{ (Request::is('admin/settings/suppliers*') ? ' class="active"' : '') }}>
                            <a href="{{ URL::to('admin/settings/suppliers') }}">
                                <i class="fa fa-credit-card fa-fw"></i> @lang('general.suppliers')
                            </a>
                        </li>
                        <li{{ (Request::is('admin/settings/statuslabels*') ? ' class="active"' : '') }}>
                            <a href="{{ URL::to('admin/settings/statuslabels') }}">
                                <i class="fa fa-list fa-fw"></i> @lang('general.status_labels')
                            </a>
                        </li>
                        <li{{ (Request::is('admin/settings/depreciations*') ? ' class="active"' : '') }}>
                            <a href="{{ URL::to('admin/settings/depreciations') }}">
                                <i class="fa fa-arrow-down fa-fw"></i> @lang('general.depreciation')
                            </a>
                        </li>
                        <li{{ (Request::is('admin/settings/locations*') ? ' class="active"' : '') }}>
                            <a href="{{ URL::to('admin/settings/locations') }}">
                                <i class="fa fa-globe fa-fw"></i> @lang('general.locations')
                            </a>
                        </li>
                        <li{{ (Request::is('admin/groups*') ? ' class="active"' : '') }}>
                            <a href="{{ URL::to('admin/groups') }}">
                                <i class="fa fa-group fa-fw"></i> @lang('general.groups')
                            </a>
                        </li>
                        <li{{ (Request::is('admin/settings/backups*') ? ' class="active"' : '') }}>
                            <a href="{{ URL::to('admin/settings/backups') }}">
                                <i class="fa fa-download fa-fw"></i> @lang('admin/settings/general.backups')
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="{{ route('app') }}">
                                <i class="fa fa-cog fa-fw"></i> @lang('general.settings')
                            </a>
                        </li>

                    </ul>
                </li>
                @endif

**Comment by snipe** [comment]
Yeah, that's not what that file looks like in 2.1.0-pre. Somehow not all of the files are current with 2.1.0-pre in your install. You must have accidentally not-replaced some of the files.

**Comment by mahesh2471990** [comment]
Oh let me replace once again with new one again

**Comment by mahesh2471990** [comment]
Thank you so much.. Now its Coming.
I dont how that file didnt replace with new one..

@snipe Please find what is issue with my ldap.php.. Email id not syncing

**Comment by snipe** [comment]
LDAP is no longer handled via ldap.php - it's in the Admin Settings.
