### ISSUE TITLE
E-Mail ID from Ldap is not syncing

### ISSUE THREAD

**Issue by mahesh2471990** [snipe/snipe-it#1597]
For reference i have copy the code pf ldap.php

'result.email' => "mail",
    'result.active.flag' => "active",
    'result.emp.num'  => "",

**Comment by snipe** [comment]
1) Using what method? Login sync or manual LDAP sync?
2) Is your email field actually called `mail`?
3) Are you getting any errors? What exactly is happening. More info is necessary here.

**Comment by mahesh2471990** [comment]
@snipe 
1) Using what method? Login sync or manual LDAP sync?
         
       Manual sync?
 
2) Is your email field actually called mail?
 snapshot below of my active directory attribute editor
![attribute](https://cloud.githubusercontent.com/assets/16305213/12171040/71418a82-b56c-11e5-8a91-4ae3edd241fd.JPG)

3) Are you getting any errors? What exactly is happening. More info is necessary here.
   Nothing error when i sync Manually. sync snapshot below.. in snapshot you can see the email field is blank
 
![sysnc ldap](https://cloud.githubusercontent.com/assets/16305213/12171136/52691d9a-b56d-11e5-8d28-d9e03bb9e2d1.JPG)

**Comment by mahesh2471990** [comment]
@snipe you want any other logs? which will help you to troubleshoot

**Comment by mahesh2471990** [comment]
@snipe i have configured in GUI itself. Please check the snapshot. I am not getting any errors. But its is not syncing my email from user

![ldap in gui](https://cloud.githubusercontent.com/assets/16305213/12171856/2075901a-b573-11e5-8dc1-896570663c51.JPG)

**Comment by mahesh2471990** [comment]
@snipe in view php or js file the Ldap sync happens? can we look into there

**Comment by snipe** [comment]
Neither, it happens in the controller, and the controller looks exactly the way I would expect it to look.

**Comment by mahesh2471990** [comment]
its liitle strange firstname and last name is syncing but why not email.
quite confused.

**Comment by mahesh2471990** [comment]
For testing purpose i put 

In ldap setting 
Lastname     = mail

![testmaile](https://cloud.githubusercontent.com/assets/16305213/12173246/afdf45cc-b57b-11e5-8919-c14ab8a45c71.JPG)




after i sync again

Lastname got field with email id

![mailgotsync](https://cloud.githubusercontent.com/assets/16305213/12173273/d7bef66e-b57b-11e5-9e56-ff0f153fc6e2.jpg)



As per this testing what may be the problem.

**Comment by mahesh2471990** [comment]
@snipe Please refer this

**Comment by ddreier** [comment]
This is unrelated to the email issue. But, @mahesh2471990, the "LDAP Authentication Query" field is incorrect for Active Directory. It should be `samaccountname=` not `uid=`.

On line 1205 of UsersController.php it's looking for `ldap_email_field` in the settings, but the field name is just `ldap_email`. Should be fixed by #1598.

**Comment by mahesh2471990** [comment]
Thank You so much @ddreier  It work.
Even EmployeeNumber is same
$ldap_result_emp_num = Setting::getSettings()->ldap_emp_num;

after i removed field it got sync Up.

@snipe @ddreier Please the changes for EmployeeNumber also.


@thank you for your support @snipe

**Comment by subramanyaHD** [comment]
@mahesh2471990 My snipe-IT unable to fetch email ID even after adding ldap_email_field, Do you have any other resolutions for this issu ?

**Comment by askarbacker** [comment]
Hi @hegdemaahi24  Can I have your contact number please? I am having the same issue with LDAP email

**Comment by volkerp** [comment]
I've the same problem with Univention Corporate Server as ldap server. The field is called _mailPrimaryAddress_ in the ldap server, but it is for some reason inaccessible by snipe.
