### ISSUE TITLE
Issue with bulk deleting a user.

### ISSUE THREAD

**Issue by xtherebellion** [snipe/snipe-it#1599]
Exception Message: Symfony \ Component \ HttpKernel \ Exception \ MethodNotAllowedHttpException

Attempting to permanently delete a user resulted in this error.

Any other information required please let me know and I will add.

**Comment by ddreier** [comment]
http://docs.snipeitapp.com/getting-help.html

**Comment by snipe** [comment]
There is no such thing as a permanent delete in Snipe-IT. All users (and assets, and everything else) are soft-deleted only.
