### ISSUE TITLE
Child assets linked to parent assets (HDD, replacement parts, etc)

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#16]
To keep a running record of maintenance on machines, etc
##

**Comment by icanhazpython** [comment]
Bumping this. Has there been any work done on this feature so far, so that I can possibly take it through to completion and submit a pull request?

**Comment by trapdoor123** [comment]
This would be very useful for us since we have barcode scanning devices that are made up of two components that we purchase separately (in this case an Apple iPod Touch and an Infinite Peripherals Linea Pro 5). We need to issue the device as whole unit, but we need the individual components recorded separately as they sometimes get swapped around due to breakages etc.

**Comment by GuloGuloDesu** [comment]
This would also resolve one of my issues.  A lot of our boxes are either custom builds, or have a lot of custom parts added to them (Video cards, Memory, Custom built cards, etc..)

I read issue #98 and custom fields would be nice.  For now though, I think what I will do is create assets for each part that we add to a computer, and just assign that part to the user.  I will probably ignore the asset tag on each of those smaller parts (memory, motherboard, processor) and just keep a "master" asset, probably the computer case, and assign an actual asset tag to that.  When I say ignore the asset tag, I mean that I will assign a value that means nothing to me to that asset.
That way I will use the user as the parent, and the parts as the child, and I will physically track the case that has all of the parts.

**Comment by Ahimta** [comment]
I'd like to work on this, sometime in the future, if the bounty is still on.

**Comment by PiQuer** [comment]
Hi @snipe, this feature request is now closed, does that mean it will not be implemented? I would like to migrate my data from tracmor, and keeping the parent-child-relationship of some assets would be a really nice thing.

The next best solution could be a custom field of type "asset tag" (converted to a hyperlink when displayed in the user interface), maybe that is easier to implement?

Anyway, keep up the excellent work, looking forward to replacing my tracmor installation.
