### ISSUE TITLE
error 500 if docker commands changed

### ISSUE THREAD

**Issue by kt1024** [snipe/snipe-it#1600]
if i change "docker run" parameters, like add ssl settings in docker run command (after initial setup complete) ,there will be a "error 500" (after login page).

before change docker run parameter (like add port map/ssl cert folder map, or change env file), everything runs fine. 

is it a bug?  

*ps, I did not change DB settings above, i've tried recreate DB and initial the docker several times, but no luck.

**Comment by uberbrady** [comment]
Hrm. It could be. It could also be something where maybe your SSL settings are off, and that's why Apache is 500'ing.

You can try something like this:

```docker exec container_id -t -i /bin/bash```

And take a look at `/var/log/apache2/*` - (I think that's the path?) maybe one of those errors will stick out for you.

I'll go and double-check the code to make sure it can handle SSL being toggled on-and-off without breaking the container.

**Comment by kt1024** [comment]
http & https both failed in error 500. (if nothing change from beginning, https & http both ok)

<code>
<pre>
root@adda6c25a798:/var/log/apache2# cat error.log
[Thu Jan 07 10:22:06.981950 2016] [ssl:warn] [pid 1] AH01909: RSA certificate configured for 172.17.0.20:443 does NOT include an ID which matches the server name
[Thu Jan 07 10:22:07.030780 2016] [ssl:warn] [pid 1] AH01909: RSA certificate configured for 172.17.0.20:443 does NOT include an ID which matches the server name
[Thu Jan 07 10:22:07.034978 2016] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.14 OpenSSL/1.0.1f configured -- resuming normal operations
[Thu Jan 07 10:22:07.035033 2016] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D NO_DETACH'
</pre>
</code>

**Comment by kt1024** [comment]
not only add ssl setting will break the docker, change env file (like ldap settings) will also break it.

ps. is there a way to reuse database (with new docker from different server)?

thanks.

**Comment by uberbrady** [comment]
It *looks* like - if the key and cert are there correctly - that the server will dynamically enable/disable the SSL support on 'run'.

Just because it's *supposed* to be that way - doesn't mean it actually *is*, though.

Those SSL warnings don't seem like they're fatal. Maybe they are? If you can do something like:

```
tail -f /var/log/apache2/*
```

While you try and access the page, I'm curious to see if it will repeat those errors or say something new...we may also end up having to turn on debugging, if the 500-page you're seeing comes from the Snipe-IT app, or if it comes from Apache.

In re: LDAP - it turns out Snipe-IT encrypts the LDAP Password using the App key, so whenever a new app key is generated, the encrypted password is rendered unusable. That's a whole other ball of hurt that I don't yet know how to handle.

**Comment by uberbrady** [comment]
The DB should be portable across any docker container - *except* for the issue with the LDAP password.

**Comment by snipe** [comment]
@uberbrady The simplest way might be to ask the user for their app key as part of the docker install. If they don't enter one, clear the LDAP password in the database. If they do, update the app key in their config to use the one they entered.

**Comment by kt1024** [comment]
the 500 page was from snipeit,
![image](https://cloud.githubusercontent.com/assets/12657496/12189811/87c7b714-b5fc-11e5-8d8a-3f22121f59ed.png)

the last test i did not change the app key. 

tail out output:
<code>
<pre>
==> /var/log/apache2/error.log <==
[Thu Jan 07 10:22:06.981950 2016] [ssl:warn] [pid 1] AH01909: RSA certificate configured for 172.17.0.20:443 does NOT include an ID which matches the server name
[Thu Jan 07 10:22:07.030780 2016] [ssl:warn] [pid 1] AH01909: RSA certificate configured for 172.17.0.20:443 does NOT include an ID which matches the server name
[Thu Jan 07 10:22:07.034978 2016] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.14 OpenSSL/1.0.1f configured -- resuming normal operations
[Thu Jan 07 10:22:07.035033 2016] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D NO_DETACH'
tail: unrecognized file system type 0x794c7630 for '/var/log/apache2/error.log'. please report this to bug-coreutils@gnu.org. reverting to polling

==> /var/log/apache2/other_vhosts_access.log <==
tail: unrecognized file system type 0x794c7630 for '/var/log/apache2/other_vhosts_access.log'. please report this to bug-coreutils@gnu.org. reverting to polling

==> /var/log/apache2/access.log <==
172.16.8.1 - - [08/Jan/2016:03:37:41 +0000] "GET / HTTP/1.1" 302 1131 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
172.16.8.1 - - [08/Jan/2016:03:37:41 +0000] "GET /auth/signin HTTP/1.1" 200 2948 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"
172.16.8.1 - - [08/Jan/2016:03:37:44 +0000] "POST /auth/signin HTTP/1.1" 500 5748 "http://asset.objectretail.com/auth/signin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/47.0.2526.106 Safari/537.36"
</pre>
</code>

**Comment by uberbrady** [comment]
Oh - definitely, I agree - that error message page is from Snipe-IT.

Can you check out your Snipe-IT error log at `app/storage/logs/*` - find the latest. You should see the smoking gun in there. A big giant shiny error with a backtrace.

**Comment by uberbrady** [comment]
Another option that @snipe mentioned is that you can enable debugging - set:

```php
'debug' => true,
```

in your `config/app.php` file.

**Comment by kt1024** [comment]
hi, I've re-download docker image & re-create DB and re-run the test. suddenly everything is OK now.
I have test below scenario several times:
1. change docker run parameters (like add/remove ssl/port map)
2. change env file, like enable/disable LDAP 
3. re-use DB from 2nd docker server.

I'm confidence to put it to production now. thanks guys.

ps.  LDAP settings will not show up in web seetings, i don't know if it should be.
