### ISSUE TITLE
LDAP sync issue repoter

### ISSUE THREAD

**Issue by chenboshiun** [snipe/snipe-it#1603]
Hi Snipe-it:

i found  several  issue in ldap sync function. 

1.After Import User via LDAP Sync , User doesn't receive password notification,so they can't login Snipe-IT and can,t change own password.

2.Can you add Company_field , Location_field , Phone_filed , Manager_filed in LDAP setting? if can do it. would be very convenient for "Create user" this event.

3.While  Import User via LDAP Sync , show "LDAP employeenumber must ba a number " in Notes field
  is it a bug?  
  
  BTW, i try to build older v2.0.3 and upgrade (v.2.0.3 -> V.2.0.4 -> v.2.0.5 -> v2.0.6 -> v.2.1.0-pre),
  but "LDAP employeenumber must ba a number " message still exist....
 
 EmployeeNumber should can be a combine with english and number ?

v.2.0.3:
![2016-01-08 2 44 12 2](https://cloud.githubusercontent.com/assets/5372796/12196497/e7697486-b639-11e5-9b78-378e8a692fe6.png)

v.2.1.0-pre:
![2016-01-08 4 45 52 2](https://cloud.githubusercontent.com/assets/5372796/12197084/e79809b8-b63e-11e5-80ae-7f8431940fae.png)

 Thanks :)

**Comment by snipe** [comment]
"After Import User via LDAP Sync , User doesn't receive password notification,so they can't login Snipe-IT and can,t change own password."

In 2.10-pre and up, if the user's LDAP credentials work when attempting to login, their record is updated with their LDAP password, so if you're using LDAP, just tell them to login with their LDAP password.

Employee number is no longer required to be a number in the `develop` branch, however this was never a bug, just a design decision.

The additional fields for LDAP are something we can consider adding further down the road.
