### ISSUE TITLE
Pass search parameter from external site

### ISSUE THREAD

**Issue by hoolius** [snipe/snipe-it#1605]
Would be ideal if we could pass a search parameter to the "All Assets" page on /hardware. I see it's calling /api/hardware/list?&search=TEXTTOSEARCH, but I'm not sure how to get an external page to send over what I'm looking for. I'd like to pass an asset tag or user to that search field (<input class="form-control" type="text" placeholder="Search">).

**Comment by snipe** [comment]
I'm not sure I understand the question. That's the right url query.

**Comment by hoolius** [comment]
For example I'd like to be search for this serial number (123456) by passing the search parameter to this URL and go straight to the results:

snipe.domain.com/hardware?serial=123456

Similar functionality is already there for the asset's status (ie. snipe.domain.com/hardware?status=RTD)

Does that make sense?

**Comment by snipe** [comment]
It doesn't support that. The search is a global search on all currently searchable fields, not specific fields.

/api/hardware/list?&search=your+search+query&order=asc&limit=50&offset=0

**Comment by hoolius** [comment]
I'm ok with global search. I can use that to get the raw search results, but what I'm trying to do is in a single page load pass a search parameter and display it in a nice formatted view.

Basically I'd like to replicate a user going to the assets page and typing in a search. 

So some way to pass a search parameter to this field - <input class="form-control" type="text" placeholder="Search">

**Comment by snipe** [comment]
You would just need to name the text field in your form "search". Basic HTML, nothing fancy about it.

**Comment by hoolius** [comment]
I got that.

I can pass a parameter to /api/hardware/list?&search=your+search+query&order=asc&limit=50&offset=0

I can't pass a parameter to /hardware&search=your+search+query

The first option gives me a non-user friendly display of the data. I can use that if I have to, but it would be much easier if I could do the same thing to the user-friendly actual page.

**Comment by snipe** [comment]
The search is only performed via Ajax, so there is only a JSON response

**Comment by hoolius** [comment]
That makes sense. I'll see what I can do with the raw search results for now. Appreciate the response.

**Comment by snipe** [comment]
No problem The easiest thing to do will likely be to parse out that JSON via javascript

**Comment by papacucku** [comment]
I want to be able to lookup the hardware by passing a URL variable like is being described here.  I can't get anything to work.  Obviously only if the person is logged into Snipe it would it work, I am doing this with several other systems but it looks like snipe it no longer provides any url based searches? 

v4.4.1 build 3636 (gece916e12)
--
Software License | AGPL3
PHP Version | 7.0.30-0ubuntu0.16.04.1
Laravel Version | 5.4.35

**Comment by snipe** [comment]
>  it looks like snipe it no longer provides any url based searches

Nothing has changed with respect to searches. Unfortunately, you'd need to use the API if you want to perform searches on assets (or anything else), as that data is considered private and requires authentication and authorization. 

Using the API shouldn't be that hard. We provide code samples for multiple coding languages.
