### ISSUE TITLE
Docker Image should have the option to be completely ephemeral

### ISSUE THREAD

**Issue by uberbrady** [snipe/snipe-it#1607]
Right now, certain things are expected to be on the internal docker FS.

The custom header image is one.

Various images people upload for models is another.

Also file uploads for licenses.

I'm pretty sure that we support all of the potential config options in here - but @swoopdk might know a few other things.

What I'd like to at least offer as an option is to mount either a 'storage volume' and have those things live there, or if they can just use `-v` to cross-mount a local directory with that stuff.

We already support mounting a local TLS directory with a key and certificate file for SSL. We should plan out the rest of the filesystem.

**Comment by uberbrady** [comment]
App key in an environment variable too?

**Comment by uberbrady** [comment]
maybe a way to trigger debug support on and off?

**Comment by swoopdk** [comment]
All the above would be something to consider. Currently i'm manually (well using a Dockerfile, but still can be considered a customization of the snipe-it image and hopefully in the future wont be nessary) adding the SSL certs, the logo and would largely appriciate having an external container with these things to make matters much easier.

**Comment by swoopdk** [comment]
Okay asset pictures should also be seperate from the docker container. 

Right now i can solve it by mounting volumes, but i have a gut feeling thats not the complete list  :(

**Comment by swoopdk** [comment]
I agree with @uberbrady that there should be some sort of common volume that contains all the userdata stuff like asset pictures ect for Docker setup. Should however be enough to make 1 mount as more mounts are just messy.

**Comment by timwsuqld** [comment]
@uberbrady I see most of this has been implemented. But the App key as an ENV doesn't appear to be. Was there a better solution to the App Key for upgrades that I've missed?

**Comment by uberbrady** [comment]
@timwsuqld the `APP_KEY` lives in the `.env` file in v3, which is expected Real Soon Now™!
