### ISSUE TITLE
Users of User permission Dashboard Changes Required

### ISSUE THREAD

**Issue by mahesh2471990** [snipe/snipe-it#1610]
Hello 
@snipe @uberbrady 

It may be Possible or No??
When we Login any users with user permission group

1. The dashboard  show Licence Serial Key. I think this is Not required. Because The serial key will    be privacy thing. So user may misuse those lic serial keys. Instead of this we can also use image of Lic. Where we dint have Upload Image Choose File in Licence Creation. (Request has been before)
    * I prefer serial key should be not shown in the user permission dashboard.
    
2. I expect Device image should be shown in the users dashboard. Where it look pretty cool.
The user can see the Particular image of the device.
      *The image where we upload for each model at least it will useful to view  those Images for      
        users who login with user permission group. 
Please see the image below. you may get rough Idea for the roadmap
 ![changes in dasboard](https://cloud.githubusercontent.com/assets/16305213/12227789/fdde3dee-b857-11e5-9c12-d7d27d4b149c.JPG)

@snipe Consider this all things useful or add in road map. OR help me make this change in my code. In future milestone this things will be added iguess. This useful to everyone.

 I guess we have to work a lot on the Permissions. which and all field to be shown in user dashboard.
 I think better we should have Check box after all the Fields of Assets, Licenses, Accessories, Consumables. Like SHOW IN DASHBOARD or relevant word were we can give. 

Not only Image i Prefer. all other Fields also,  So the custom Filed we create Like CPU, RAM, HDD, IP address in assets. That field i refer to be shown in User dashboard so User will come to know the configuration of Assets user have.

I think this request may be good idea for Changes. Take it as High Importance

Thank You

**Comment by snipe** [comment]
Most software will let you go to the About screen and see who it is registered with and the serial key, so I'm not really sure how removing this would be helpful.

**Comment by mahesh2471990** [comment]
No i am not talking about other software.
You please check the snapshot above.

I am asking you
Whether there is Option to remove/Hide the Serial Key in Users dashboard when they login

In Licence section. We create Licence, When we create Licence. For Example: Microsoft Office 2016. Then we have to provided the Serial key also. After we checkout that Licence to any user.
When that user login snipe it.
He will be visible with Serial Key of Microsoft Office 2016. USER must not see the serial key of the Software. because they use that same key for personal use or misuse. I am tell Serial key are privacy things that should not visible for users who ever login using user permission.

@snip @uberbrady @ddreier  Can please refer the Snapshot?

**Comment by snipe** [comment]
@mahesh2471990 please stop tagging people in these tickets. We will help you when we have time.

I have looked at the snapshot, and as I said, that information is usually available to the user when they go to About > in whatever that software is, so it's not secret information. Most desktop applications will show the user the serial if they look for it in the software you've installed.

**Comment by mahesh2471990** [comment]
When you see About> of any  software the Serial key will be Encrypted. not visible for  user. Even depends on which software. I agree with you in some software the serial key will be visible. But standard Software like Microsoft Products. the key will be change to other mode.

In production Environment or company. there is rule not share the serial key.. there will be licence key of 30 activation. the user can see the serial key copy that they can use for there personal use. IN company for system admins Sharing the key serial key is not prefered. I am Requesting you if that key removed. Replace with other Details. It would Be cool.

**Comment by mahesh2471990** [comment]
I agree in different scenario serial key may required. @snipe it Depends on the company. Where we are. How we use your software.
For some people it will be good. view serial key of License in Dashboard. For some People NO.

Better plan i suggest is There must be customized dashboard. Where we can Create new Group. With customized field to view in dashboard.

Feature with Request:
Permissions we have is less options. We have to give customized option to each of the fields in  Assets, Licenses, Accessories, Consumables and even Custom Field (like ip,ram,hdd) where we created manually should be implemented. people may required some fields in dashboard. some not. Make it Custom Snipe where we can select  each and every particular fields. 

And sorry i tag other people. I taught they are also part of it who attend my problem. I taught you may be Busy. So i tag them. Sorry for that.

**Comment by mahesh2471990** [comment]
I have Customize plan Blue print for Permission Improvement where you may get idea and may help  you. Please see the snapshot.

![capture](https://cloud.githubusercontent.com/assets/16305213/12291079/23652af0-ba0b-11e5-923e-4e8263db39cf.png)

@snipe  did You get any plan after you see this above Snapshot.
Just Tell me this BE may good idea or no? We can make it work this way.

In above i have only mention some of fields. Still Important Fields can be added.

When the Field is Checked. That Particular will fields will be available to view In users Dashboard.
So it would pretty cool when user login he will get to see his Asset Checkout, Model Number, Assets Image, IP address, Mac Address, HDD, RAM, CPU e License Information. 

THIS WILL MAKE USE OF ALL THE FIELDS, CUSTOM FIELDS AND IMAGES UPLOADED CAN BE VIEW TO OTHER USER ALSO.


NOTE:
Most Important things is were we Create the custom Fields. All the field mUst be Updated automatically in Permission Field List.

**Comment by mahesh2471990** [comment]
@snipe 
I am having Hash Version  'hash_version' => 'v2.1.0-pre-g4aa3768' not 'hash_version' => 'v2.1.0-pre-34-gb16ea61',

Updating that codes to is recommended?

Did you the Check the latest snapshot which i sent you? What do you tell regarding that idea

**Comment by mahesh2471990** [comment]
I saw in https://develop.snipeitapp.com.
But i didn't upgrade to my Code yet. Waiting to for all the fields where we can select manually.
It was excited to see the Licence allow Block Options.
Thank You so much for that @snipe 
![1236537281_the_it_crowd](https://cloud.githubusercontent.com/assets/16305213/12319989/eacf17e8-bacb-11e5-8c0d-66c880ce665b.gif)

Same Way I accept for all the Fields
In Previous Snapshot I shown. some blue print

**Comment by snipe** [comment]
We're not planning on adding the ability to select each field manually any time soon.

**Comment by mahesh2471990** [comment]
I guess you can add this plan In future coming release or roadmap. It would be needful use for everyone. 


I think you need some vote for this..:-)

**Comment by mahesh2471990** [comment]
Future Request in next release
I am accepting the some of the custom field would have visible in dashboard for users.

I know it is hard to work on Permissions.
But After once we create new the group with following permission for dashboard view or access of particular Fields. that group we can assign to particular user very easily. WORK Reduce.

The Default fields can pull easily to permission screen as below snapshot
The problem with custom Field is that whenever we create a new field that whole entity must be shown the Permission group.. I know there would be a double work in backend code. But it would be useful for every one. who use snipe IT software in different sector.
I am requesting this feature below (Very Useful)

![capture](https://cloud.githubusercontent.com/assets/16305213/12323394/d5781434-bae0-11e5-841b-79a4b4ce5901.png)

Thank YOU In advanced.
