### ISSUE TITLE
Error with the centos/redhat and debian/ubuntu install script 

### ISSUE THREAD

**Issue by Aaranaw** [snipe/snipe-it#1611]
Hi, running Ubuntu 14.04.3 LTS , just ran the install script as described on http://docs.snipeitapp.com/installation/downloading.html ran through the options until I reach the following errors
## Installing and configuring composer

./snipeit.sh: line 236: curl: command not found
mv: cannot stat ‘composer.phar’: No such file or directory
./snipeit.sh: line 239: composer: command not found
PHP Warning:  require(/var/www/snipeit/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/snipeit/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/snipeit/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/snipeit/bootstrap/autoload.php on line 17
## Restarting apache.
- Restarting web server apache2
  AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
  ...done.
  
  **_If you want mail capabilities, open /var/www/snipeit/app/config/production/mail.php and fill out the attributes**_
  
  **_Open http://lin-scag to login to Snipe-IT.**_
## Done!

At this point http://lin-scag gives a server 500 error, and http://127.0.0.1/ loads the Apache2 Ubuntu Default Page.

Any help would be appreciated.

**Comment by mtucker6784** [comment]
Does curl successfully install in your environment if you do the following?

`apt-get install php5-curl`
