### ISSUE TITLE
deployed asset links to error

### ISSUE THREAD

**Issue by kraetsche** [snipe/snipe-it#1612]
hey, i receive an error if i'm at "Assets"->"Deployed"->"Status" and try to get a detailed view about the users, but i can see everything if i "People"->"Users":

error message: 

Not Found
The requested URL /snipe-it/index.php was not found on this server.

my url is /snipeit/index.php not /snipe-it/. 
Where can i change this url?

thanks alot!

**Comment by ddreier** [comment]
`/app/settings/production/app.php` in the Snipe-IT directory is where the URL setting is located.

**Comment by kraetsche** [comment]
ive already set the url at "app/config/production/app.php" to 'http://xx.xxx.xx.xx/snipe-it/public' and dashboard relinks to public with success, but still, it doesnt lead to user and i receive that error.
