### ISSUE TITLE
Reset Data / Start over

### ISSUE THREAD

**Issue by rvasquez151** [snipe/snipe-it#1613]
Is there a way to reset all the data I entered and start over? I would like to start with a clean slate and import data using the .csv file.

**Comment by ddreier** [comment]
Drop all tables in the database and re-run the [install command](http://docs.snipeitapp.com/installation/command-line.html). This will delete and re-create the database.

You can also just create a new, empty, database and point to it instead (then run the install command).

**Comment by mikey-m** [comment]
How do you drop tables and recreate them?

**Comment by nex86** [comment]
> How do you drop tables and recreate them?

exactly what he said, you have to figure out how now :) :) :) :) :)
