### ISSUE TITLE
custom button and custom page with same login session

### ISSUE THREAD

**Issue by moniruss** [snipe/snipe-it#1618]
I have another form page (lets say form.php) which uses separate user database to be accessed. However I want to place a button or something inside snipe-it dashboard somewhere to link it to that form page which can be accessed through snipe-it login session. How to do it? and do i need to place it inside public folder or what?
Would like the help asap if it ain't too much to ask. I like this asset management platform and want to run everything from one point if possible.

**Comment by snipe** [comment]
You can try something like this:
http://www.jacopobeschi.com/post/integrate-laravel-session-in-external-php-application

But it's really out of scope for Snipe-IT support
