### ISSUE TITLE
Deployed and Ready to deploy display nothing unless I refresh

### ISSUE THREAD

**Issue by Smeebs** [snipe/snipe-it#1620]
Hello

I added a new user an then went to sign out an asset and now the page wont display anything unless I hit refresh then the assets show up. This happens in the Deployed and Ready To Deploy tabs as well as Un-deployable Assets. It is possible this is an issue for archived and Requestable but I don't have any assets in this sections.

**Comment by ddreier** [comment]
http://docs.snipeitapp.com/getting-help.html

**Comment by snipe** [comment]
@Smeebs if you try clearing your cache and cookies, does that help?

**Comment by allewell** [comment]
Upgraded my install to v2.10 stable and am getting this issue. Cleared storage/cache and storage/views without avail. 
Typing anything into search produces the list as expected, and just spamming anything into search and then deleting what you typed produces the list as expected. IE: it's just the initial load of the view that displays "No matching records found"

**Comment by snipe** [comment]
Try clearing your browser cache

**Comment by snipe** [comment]
(And cookies)

**Comment by allewell** [comment]
Indeed, clearing cookies fixed the issue. The list also updates correctly after deploying another asset.
