### ISSUE TITLE
Some users click real assets, and land on dummy asset page

### ISSUE THREAD

**Issue by crguerrero1** [snipe/snipe-it#1621]
Environment:
Ubuntu 12.04.5
Apache/2.2.22
Snipe-IT version	v2.0-353-gb6f4080
PHP Version	5.4.45-2+deb.sury.org~precise+2
Laravel Version	4.2.17
___________

Hello,

I have come across a rather strange issue here that is only affecting a select number of users.  Of about 5 people, only two users (IT staff -so they have admin rights) are unable to see the asset page of any new assets we've added (/hardware/\<number\>/view)

If they go to /hardware, they are able to see the [correct] list of our existing inventory, however, any asset tag that these two users click redirects them to one of the asset pages for one of the seeded dummy assets (id 1-12).   For example, selecting the asset tag for an asset with ID=22 will go to `/hardware/1/view` rather than `/hardware/22/view`.

Searching through the existing issues, the closest one I could find was https://github.com/snipe/snipe-it/issues/557.  I did the steps in that ticket (backup db-->re-seed db-->import backup db-->remove seeded assets) but this did not resolve the problem.  I've closely monitored both the webserver logs and the snipe-it logs while one of the users tested this, and the apache logs only show the paths that are being returned, and do not indicate what is incorrectly redirecting these users.  Similarly, the snipe-it logs did not show any messages other than the user logging in, while we tested this.  Debug mode was turned on during all this testing and there were also no additional error messages shown in the browser.

Since I have deleted the seeded dummy assets in the database, these two users now get the "This asset does not exist" error message when they click on any asset in the list.

I've had these two users try on different browsers and computers which made no difference.

The one last thing I need to test is seeing if deleting the user, and re-importing (from LDAP) will fix the issue for them.  But I will do this in the morning since both users have left the office for the day.

Any suggestions or pointers on further troubleshooting this would be appreciated.

Regards.

**Comment by snipe** [comment]
Do you have Full Company Support enabled in the settings, and if so, are your assets assigned to specific companies?

**Comment by snipe** [comment]
"For example, selecting the asset tag for an asset with ID=22 will go to /hardware/1/view rather than /hardware/22/view." <-- if you only have 12 assets, asset 22 won't exist, so it should return you to the listing.

I'm honestly not sure what could be happening here. Try clearing your cache and cookies maybe?

**Comment by crguerrero1** [comment]
Hi snipe,

I don't believe we have Full Company Support enabled.  I don't see this option in the admin settings or the config files, and I also don't see any "Company" fields when looking at assets.

For my example that you quoted, that was after I re-imported the database with our existing list of assets (and then removed the first 12, dummy assets), so asset 22 did exist during this test.

The last thing I've just tried, was to delete the user in the UI, delete the corresponding user's record from the database, re-import from LDAP to sync user, and re-assign admin status to the "new" user.  After doing this, the user no longer see's this issue if logging in on a different computer.

Strangely enough, he still see's the issue if using one of his two work computers (and with full confidence, I can say he cleared browser cookies and cache).  Since I'm able to correctly look at assets under his account using my computer now, this is likely not an app bug.

Thanks.

**Comment by snipe** [comment]
You may also want to upgrade, since the later versions fix a lot of bugs and add new features.
