### ISSUE TITLE
unable to retrieve assets data for specific user 

### ISSUE THREAD

**Issue by abdullahalasham** [snipe/snipe-it#1622]
Hi snipe,

i am facing a strange issue, when i search for all assets assigned to a user named "pastor" the search return empty result ![user pastor](https://cloud.githubusercontent.com/assets/15037482/12291033/eefde0be-b9f5-11e5-96a9-026f1a08cbec.PNG)  , however when i search for the same user in people management  i get the assets assigned to him kindly refer to the below image
![pepole pastor](https://cloud.githubusercontent.com/assets/15037482/12291085/3be2181e-b9f6-11e5-8600-9993808b199e.PNG)

thanks in advance

**Comment by snipe** [comment]
http://docs.snipeitapp.com/getting-help.html

**Comment by abdullahalasham** [comment]
i am really not sure what was the issue yet i checked in the assets and checked it out again and everything works , thanks

**Comment by snipe** [comment]
![aroo-whaa](https://cloud.githubusercontent.com/assets/197404/12292034/8ebc2e8c-b99f-11e5-9f29-14b700612bb5.gif)

Welp, as long as it works, I guess...
