### ISSUE TITLE
Inconsistency with Asset Status and Location

### ISSUE THREAD

**Issue by jimmysnee** [snipe/snipe-it#1627]
I have attached a PDF document with the details of the issue, including screenshots.

[Snipe Asset Location and Status Issue.pdf](https://github.com/snipe/snipe-it/files/89525/Snipe.Asset.Location.and.Status.Issue.pdf)

**Comment by uberbrady** [comment]
Is there any chance you can put it in-line here within the GitHub issue? I know many people are wary of opening random PDF's on the web.

**Comment by jimmysnee** [comment]
Here is a list of assets.  The fist is an asset with default location of Hoboken, but is checked-out to a user in Louisville.  The other two assets have Louisville as default location, but they are not assigned.

 
![image](https://cloud.githubusercontent.com/assets/16559440/12309861/f845c9be-ba1a-11e5-9eae-633fb98dcc45.png)



Dashboard properly represents the three assets, and 2 of them being available.
![image](https://cloud.githubusercontent.com/assets/16559440/12309867/00f6d4a4-ba1b-11e5-9ed5-53619943a6eb.png)










Here is the list of my locations.  The one asset showing for Hoboken (default location) below is assigned to a user that resides in Louisville.  No matter what way I assign or categorize the assets, they are never represented as “ASSETS ASSIGNED”.
![image](https://cloud.githubusercontent.com/assets/16559440/12309875/0b254c44-ba1b-11e5-8b54-523224551efc.png)
 


Here is the Louisville location.  The location properly shows users that are present at (associated with) that location.  However, the assets do now show, regardless of whether they are “assigned” or “ready to deploy”.
![image](https://cloud.githubusercontent.com/assets/16559440/12309884/14d31c76-ba1b-11e5-8b00-498420523f59.png)
 

Clicking on the user link from the Louisville location, this is the user that I have assigned an asset to.  That asset is showing up as expected.
![image](https://cloud.githubusercontent.com/assets/16559440/12309891/1c5d5542-ba1b-11e5-9ead-8e21e251b109.png)

**Comment by jimmysnee** [comment]
I searched through the recent issues prior to posting, but I guess my keywords were too exclusive.  I have found Issue #1467 is similar to part of what I described herein.

**Comment by k-boy** [comment]
I'm experiencing this same issue where a location shows the listed users but not the associated assets , any updates?

**Comment by nbattista** [comment]
any news for this bug?

**Comment by mevere** [comment]
I think I might be having the same issue. I believe it has to do with the person's Location. When an asset has a location, and it is "Checked-Out" by a person, the asset takes on the person's location instead of retaining it's own location.
