### ISSUE TITLE
Error 500 when try access /admin/settings/app/edit page

### ISSUE THREAD

**Issue by aleJohnny** [snipe/snipe-it#1629]
I started my installation with 2.0.5-pre and now I updated to 2.1.0-pre, run php artisan migrate command and everything looked fine until I tried access /admin/settings/app/edit (Edit Settings button).

I turned on debug to see what was going wrong: 
![2016-01-13 2](https://cloud.githubusercontent.com/assets/16123193/12309274/f6bb33de-ba30-11e5-987b-2a90889dce23.png)

Log:
[2016-01-13 19:59:18] production.ERROR: exception 'Illuminate\Encryption\DecryptException' with message 'MAC is invalid.' in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:144
Stack trace:
#0 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(89): Illuminate\Encryption\Encrypter->getJsonPayload('eyJpdiI6IkRCVXJ...')
#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\Encryption\Encrypter->decrypt('eyJpdiI6IkRCVXJ...')
#2 /var/www/html/snipeit/app/controllers/admin/SettingsController.php(53): Illuminate\Support\Facades\Facade::__callStatic('decrypt', Array)
#3 /var/www/html/snipeit/app/controllers/admin/SettingsController.php(53): Illuminate\Support\Facades\Crypt::decrypt('eyJpdiI6IkRCVXJ...')
#4 [internal function]: Controllers\Admin\SettingsController->getEdit()
#5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#6 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('getEdit', Array)
#7 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\SettingsController), Object(Illuminate\Routing\Route), 'getEdit')
#8 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\\Adm...', 'getEdit')
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#10 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#11 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#13 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /var/www/html/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#19 /var/www/html/snipeit/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#21 /var/www/html/snipeit/public/index.php(49): Illuminate\Foundation\Application->run()
#22 {main} [] []

Did I missed something? :(

**Comment by snipe** [comment]
Are you using LDAP?

**Comment by snipe** [comment]
I'm guessing your app key changed. (Your app key shouldn't ever change, as it's how the system encrypts and decrypts things in the database.) Clear your LDAP password in the database and re-enter it in settings.

See also https://github.com/snipe/snipe-it/issues/1595

**Comment by aleJohnny** [comment]
The app key really changed, I looked in the app.php from the old installation (2.0.5) and was different! I put the old key in the new installation and now it's working again. (I made a clean install because the old was running in UniServer for test purposes before put in production).

Answering your first question, no I'm not using LDAP yet. ;)

Thank you very much! :)

**Comment by snipe** [comment]
![toddler-toyko-drift](https://cloud.githubusercontent.com/assets/197404/12312309/4713dc5a-ba13-11e5-8788-51108eb0a53f.gif)
