### ISSUE TITLE
Asset Acceptance

### ISSUE THREAD

**Issue by BHollowell** [snipe/snipe-it#163]
It would be nice to have a feature added to SnipeIT that required end users to "confirm" assets that were deployed to them, and essentially take responsibility for them.

The way I envision this feature working is as such:

1) Tech checks asset out to end user
2) Status changes to "Pending Confirmation" or something similar
3) User receives email indicating that asset has been marked as checked out to them, with a link that they much click to confirm asset deployment.
4) Upon clicking said link, status is then updated to "Deployed"

The email template should be customizable so that companies can structure their "acceptance policy" however they want.

**Comment by BHollowell** [comment]
Can we get an ETA on when this should be included? I'm very anxious for this.

**Comment by snipe** [comment]
@BHollowell Do you typically have one EULA to rule them all, or do you require different EULAs for laptops, keyboards, phones, etc?

**Comment by BHollowell** [comment]
@snipe Just one EULA with broad terms regarding asset rights & responsibilities of the end user. We have this for 2 reasons, really:

1) Transparency for user to know what assets are assigned to them
2) Allows us to enforce responsibility for assets to users, i.e. if it gets damaged or lost.

**Comment by snipe** [comment]
Oh sure, I totally get the WHY - it's the details on the HOW that I'm more curious about. My guess is that I could do this with one standard box for EULA, and then maybe attach whether or not the EULA should be sent to the asset model. I'm not really sure how it will be serve everyone. Waiting to hear back from some more folks in the Gitter chat for their use cases.

**Comment by snipe** [comment]
Or do we send it on user creation as a blanket for all the stuff they end up getting assigned?

**Comment by BHollowell** [comment]
To answer your first response: Since this is an optional feature that can be enabled anyway, it might be best implemented as an option to create one (or more) EULA terms and then after it's created you can select which device types to associate the EULA with. That way those who want different EULA terms depending on the model can still have this.

To your second question: I would assume this would need to be sent on asset assignment rather than user creation, that way they are responsible for "accepting" each and every assign that is assigned to them. If a device is replaced, or they get something new like a tablet or some other device later on, we would need them to accept this as well.

**Comment by BHollowell** [comment]
The biggest reason for this feature (at least for us) would be so that we can search for a specific user at any time and say "X person has A, B and C assets assigned to them" and we can be 100% sure of this because they were required to acknowledge that when it was assigned to them. So if they can't or don't return it we have justification other than "well we show that this was assigned to you"

**Comment by snipe** [comment]
I have a super-rough version of this up on `develop` if you're feeling adventurous. If you're not, I'll try to make sure it's polished up before 1.2.6.

**Comment by snipe** [comment]
(I need to figure out how I want to change the status of pending acceptance assets, but the email and EULA bit is working.)

**Comment by BHollowell** [comment]
Thanks very much for this @snipe! I'll download the latest dev version and give it a shot :)

**Comment by snipe** [comment]
Just added markdown to the EULAs btw

**Comment by parvathikonda** [comment]
how to add custom deployed label
