### ISSUE TITLE
"Delete Image" Checkbox Does Not Remove Image on v2.1.0-pre

### ISSUE THREAD

**Issue by vcsalex** [snipe/snipe-it#1631]
Hello,

I accidentally uploaded an image to the wrong asset. I want to remove the image and not replace it. I tried checking the the "Delete Image" checkbox and then saving the asset. I expected this to remove the image; however, it did not.

Are my expectations incorrect or is the checkbox broken?

Thanks,

Alex

**Comment by snipe** [comment]
Hi Alex - it was broken. It's fixed on master and develop now.
