### ISSUE TITLE
Default columns in view

### ISSUE THREAD

**Issue by cgresser** [snipe/snipe-it#1635]
Hey,

is it possible to set the default selected columns in the views

![image](https://cloud.githubusercontent.com/assets/16030278/12329932/fe6b98f0-bae2-11e5-8050-96db1258dfc7.png)

**Comment by snipe** [comment]
No, but it will remember which ones you have selected. (It will forget them when you upgrade, because we have to bust that cache or weird caching stuff happens, but it will persist through logins)
