### ISSUE TITLE
500 Internal Server error

### ISSUE THREAD

**Issue by jaskegreen** [snipe/snipe-it#1636]
I just did a second install on my Mac Pro server because the first one didn't work. I followed the install process exactly as stated and now getting a 500 error when directed to the login page.

I'm running on OSX 10.8 with Web services on Server.app, Apache 2, and PHP 5.6. Here are my most recent logs:
[log-apache2handler-2016-01-13.txt](https://github.com/snipe/snipe-it/files/90830/log-apache2handler-2016-01-13.txt)

**Comment by uberbrady** [comment]
Permissions in `app/storage` seem wrong.

See: http://docs.snipeitapp.com/installation/configuration.html#set-directory-permissions

**Comment by jaskegreen** [comment]
Yes, I had them set to 755 before and was getting an error. I just reset them to 755 recursively and getting the same error as before:

Error in exception handler: The stream or file "/Library/Server/Web/Data/Sites/Default/dmassets/app/storage/logs/log-apache2handler-2016-01-14.txt" could not be opened: failed to open stream: Permission denied in /Library/Server/Web/Data/Sites/Default/dmassets/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:87

**Comment by uberbrady** [comment]
It's not the 755 thing, it's the who-owns-it and which-group-has-it thing. 

- Find out who Apache is running as (probably 'apache' or 'nobody' or 'httpd') - 
- `chown -R ` those same directories to that same user.
- Then Apache will be able to write to those directories and files in them.

**Comment by jaskegreen** [comment]
Ok, I've switched owner and group to _www recursively on the three folders, but getting same 500 error and no new log files.

Should _www be owner of whole site or just those folders?

**Comment by jaskegreen** [comment]
Just as a side note, it wasn't clear to me what the options were for the environment settings. Here is what I have in my start.php page:

        $env = $app->detectEnvironment( [
            'local'      => [ '', '' ],
            'travis-ci'  =>   'travis-ci',
            'staging'    => [ '' ],
            'production' => [ 'dnhs-arts.pusd.dom' ]
        ] );

Do I need to have variables for local, travis-ci and staging?

**Comment by snipe** [comment]
It will default to production, so you don't need to change that unless you're planning on doing development work (which is mentioned in the Contributing documentation)

**Comment by jaskegreen** [comment]
Ok, so any thoughts on the other issues? I'm still getting a 500 error when hitting the auth page.

**Comment by snipe** [comment]
If your logs still say permission denied, it's still a directory permissions issue. Are you certain Apache is running as `_www`? You can also try `chmod -R 775 app/storage`

**Comment by uberbrady** [comment]
I'd also mention take another look at the log file - take a look at the end and see if you're getting any new errors.

Another possibility is that even though Apache may be running as `_www`, it may be running your PHP app using php-fpm, and that *could* be running as a different user - other than `_www`

**Comment by jaskegreen** [comment]
@snipe All info I've found shows Apache on Mac is _www. How can I find out for sure? Already ran chmod several times.

@uberbrady What do I need to do to confirm use of php-fpm?

I am running the Web Service in Server.app. The directory group for all directories was wheel when I started this whole process. Maybe that's an issue?

**Comment by HinchK** [comment]
@jaskegreen the wheel group is specific to sudoers, i.e. users who who can `sudo service apache2 restart`.   it's usually not used as a service-user in debian but that might be different for a Mac Pro Server.

__Lets grab all the surrounding logged information we can at this point:__

1. take a look at the application-specific logs located in `[snipe-it-root]/app/storage/logs` (may aide in confirming php-fpm usage)
2. web-server logs (`/var/log/apache2/...`)
3. system logs (invoke the 500  error, do a `:/var/log$ ls -ltrah`  (`ls -ltrah` in the `/var/log/` directory) to sort the files by recently_updated-descending.  `/var/log/syslog`, `/var/log/messages`, `/var/log/access`, `/var/log/auth.log`.

**Comment by jaskegreen** [comment]
Just getting back to this. I'm noticing something in the Apache error.log that seems peculiar:

[Mon Feb 01 13:28:38 2016] [error] [client ::1] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

Seems to be a loop somewhere, but I don't know how to use either of the suggested resources mentioned. Nothing I found on the web shows how to implement them.

**Comment by jaskegreen** [comment]
The following is what I get in Terminal after running ls -ltrah in /var/logs:

drwxr-xr-x   12 root             wheel             408B Feb  1 00:00 performance
drwxr-xr-x   12 root             wheel             408B Feb  1 00:00 eventmonitor
drwxrwx---   30 root             admin             1.0K Feb  1 00:00 DiagnosticMessages
-rw-r-----    1 root             admin             412K Feb  1 00:30 system.log.0.bz2
-rw-r-----    1 root             admin             127B Feb  1 00:30 wifi.log.0.bz2
-rw-r--r--    1 root             admin              64B Feb  1 00:30 wifi.log
drwxr-xr-x  185 root             wheel             6.1K Feb  1 00:30 .
-rw-r--r--    1 root             wheel             1.3M Feb  1 01:14 servermgrd.log
-rw-r--r--    1 root             wheel             4.2M Feb  1 03:15 daily.out
-rw-r--r--    1 root             wheel             7.5K Feb  1 05:30 monthly.out
drwxr-xr-x   49 root             wheel             1.6K Feb  1 11:56 asl
-rw-r-----    1 root             admin             392K Feb  1 12:06 install.log
drwx------    4 _postfix         wheel             136B Feb  1 15:57 com.apple.launchd.peruser.27
drwx------    4 root             wheel             136B Feb  1 15:57 com.apple.launchd.peruser.0
-rw-r--r--    1 root             wheel              62K Feb  1 15:57 getsslpassphrase.log
drwxr-xr-x   17 root             wheel             578B Feb  1 15:57 apache2
drwx------    4 _www             wheel             136B Feb  1 15:58 com.apple.launchd.peruser.70
-rw-r-----    1 root             admin             630K Feb  1 15:59 mail.log
-rw-r-----    1 root             admin             8.9M Feb  1 16:00 system.log

 I checked out the getsslpassphrase.log file and found:

2016-02-01 23:57:17 +0000: /Library/Server/Web/Config/apache2/getsslpassphrase: No vhost config found for serverName dnhs-arts.pusd.dom port 443

Don't know if this helps to solve anything, but I'm pretty much stuck at the moment. Thanks in advance for any help.

**Comment by jaskegreen** [comment]
Ok, I've added Snipe-It suggested Vhost info to my vhost config files and now getting the "Whoops! There was an error" page. Here are the latest Snipe-It logs:

[log-apache2handler-2016-02-01.txt](https://github.com/snipe/snipe-it/files/113214/log-apache2handler-2016-02-01.txt)
