### ISSUE TITLE
creating Asset Maintenance causes 500 error

### ISSUE THREAD

**Issue by leobg** [snipe/snipe-it#1638]
I am on 2.0.6 and when I try to add new asset maintenance, I get 500 error. Laravel log says:
<code>
[2016-01-14 22:13:03] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Controllers\Admin\Asset' not found' in /var/www/snipe-it-2.0.6/app/controllers/admin/AssetMaintenancesController.php:216
</code>

<code>
Stack trace:
</code>

<code>
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
</code>

<code>
#1 {main} [] []
</code>
It lets me complete the form for asset maintenance, but when click submit I get the error

**Comment by snipe** [comment]
Which page are you trying to create a maintenance record for?

**Comment by leobg** [comment]
From the dashboard - assets -> asset maintenances then click on "Create New" in the top left corner. (/admin/asset_maintenances).

**Comment by snipe** [comment]
Have you tried running `php composer.phar dump-autoload`? I can't reproduce your error on any of our demos.

**Comment by leobg** [comment]
Yes - that was actually the first thing I tried. Perhaps I need to delete the Laravel cache somehow first? Asset maintenance worked well on the previous release for me too. 

I run the app in a docker container (but with own Docker config - not the one that was added later to the project). I guess I can try to redeploy. Is the next stable release close to get out (I might wait for it if so)?

**Comment by snipe** [comment]
I think the one on dockerhub pulls the latest from master, which should be stable.

**Comment by leobg** [comment]
Thanks - I'll give it a try and report back.

**Comment by snipe** [comment]
Great, thanks. I can get asset maintenances to work on both the demo and the dev demo, so I'm guessing upgrading should solve your issue.

**Comment by leobg** [comment]
Issue resolved - all good now - thanks!
