### ISSUE TITLE
[reopen]  deployed asset links to error #1612 

### ISSUE THREAD

**Issue by kraetsche** [snipe/snipe-it#1641]
hey, i receive an error if i'm at "Assets"->"Deployed"->"Status" and try to get a detailed view about the users, but i can see everything if i "People"->"Users":

error message:

Not Found
The requested URL /snipe-it/index.php was not found on this server.

my url is /snipeit/index.php not /snipe-it/.
Where can i change this url?

thanks alot!
@ddreier
ddreier commented 4 days ago

/app/settings/production/app.php in the Snipe-IT directory is where the URL setting is located.
@snipe snipe closed this 2 days ago
@kraetsche
kraetsche commented 2 minutes ago

ive already set the url at "app/config/production/app.php" to 'http://xx.xxx.xx.xx/snipe-it/public' and dashboard relinks to public with success, but still, it doesnt lead to user and i receive that error.
edit: i changed dirname to /snipe-it/.
its not /snipe-it/index.php, its /snipe-it/public/index.php

**Comment by snipe** [comment]
Your url should not point to the public directory.
http://docs.snipeitapp.com/installation/subdirectory.html
