### ISSUE TITLE
Bug: https links and logo image & dashboard (v2.1.0-pre) in a http instance

### ISSUE THREAD

**Issue by 823Labs** [snipe/snipe-it#1642]
The logo the link on the logo and the dashboard all have https causing the logo image not to load, and css to break when accessing the links when clicked, as my instance is running via http only.... for now at least.

**Comment by snipe** [comment]
I’m not sure how that would be possible. It’s just pulling in the url you set.

`<a href="{{Config::get('app.url')}}"><i class="fa fa-dashboard"></i><span>@lang('general.dashboard')</span></a>`

If I grep for https (or even http) in the main layout file where the nav lives, it has only the links back to the snipe-it website and github pages.

Please make sure your app url is configured correctly in your config file. http://docs.snipeitapp.com/installation/configuration.html#application-settings

**Comment by 823Labs** [comment]
installed via instructions on http://docs.snipeitapp.com/installation/downloading.html

"wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh
chmod 744 install.sh
./install.sh"

Screenshot
http://cl.ly/2B32302B3a41

**Comment by stf675** [comment]
same for 2.1 installed using install..sh
logo and dashboard links are https, while everything else is http.  https is not used causing error when clicking on dashboard.

**Comment by stf675** [comment]
after checking app.php and changing https:// to http:// and restarting httpd everything works correctly
