### ISSUE TITLE
Cannot Edit Assets / Asset Tag already taken??

### ISSUE THREAD

**Issue by rvasquez151** [snipe/snipe-it#1643]
I am trying to edit some assets that I imported.  Adding Asset Name, Purchase Date and Warranty Info. When I save the changes I get an error message: "The asset tag has already been taken"  I am editing an existing asset. Not adding a new one. Any suggestions??

**Comment by rvasquez151** [comment]
I am running version 2.0-175

**Comment by snipe** [comment]
Upgrading will likely fix this issue

**Comment by rvasquez151** [comment]
Ok., I am not sure if I know how to upgrade. :-(

**Comment by snipe** [comment]
http://docs.snipeitapp.com/upgrading.html

**Comment by rvasquez151** [comment]
Thank you. I just upgraded.  Didn't forget to run php artisan migrate  I am able to update Assets now. Thank you!

**Comment by snipe** [comment]
![1162345_o](https://cloud.githubusercontent.com/assets/197404/12366979/a3ceef94-bb93-11e5-99b7-97c5a74425da.gif)
