### ISSUE TITLE
Escape double quotes in CSV export.

### ISSUE THREAD

**Issue by Mooninaut** [snipe/snipe-it#1645]
When I export data with double-quoted contents (usually the Notes field) to CSV, the double quotes are included verbatim. In order to handle double quotes in CSV, they must be escaped by doubling them up.

The field `This is use, "this" is mention.` should be output as `"This is use, ""this"" is mention."` in CSV.

Currently it is output as `"This is use, "this" is mention".` which is incorrect, and becomes garbled when imported into another program, especially when exporting notes that have embedded newlines.

I just got started using it, but I'm finding Snipe-IT very valuable. Thanks!

**Comment by snipe** [comment]
That looks like it might be an issue with the javascript library we use (https://github.com/wenzhixin/bootstrap-table) but I don't see any existing issues related to this problem, and I'm not sure how we'd fix it short of a pull request to their code. Let me dig around a little more.
