### ISSUE TITLE
Checking in an asset

### ISSUE THREAD

**Issue by rmavery** [snipe/snipe-it#1648]
I looked in current issues, and couldn't find this, so please forgive me if this is a duplicate.   
If you have an asset checked out and you want to check it in to move it to another user, the page crashes (Error 500).  Then when you go back, the asset has actually been checked back in (so it works, but the page crashes for some reason in the process).   

Version: (v2.1.0-pre)

**Comment by snipe** [comment]
Please provide us with more info. http://docs.snipeitapp.com/getting-help.html

**Comment by rmavery** [comment]
Sorry.  I will get that done today.   Thanks.

**Comment by rmavery** [comment]
**Version:** (v2.1.0-pre)
installed using install.sh (I guess).  I used the instructions at http://docs.snipeitapp.com/
Error in browser is [Error 500 Internal Server] 
**Console Error:**  Failed to load resource: the server responded with a status of 500 (Internal Server Error)
**SnipeIT Page:**  http://snipeit/hardware/291/checkin
**Stack Trace:**  I don't think this is provided, or I don't know what it means.  
**Reproducable in Demo:**  No.  The demo appears to checkin/out correctly.  
Checking app/storage/logs, I think I may have found something.  I set up a mail server, but it wasn't working.  I didn't think it was a big issue, so I ignored it (wasn't sure if we needed the feature).   The logs, appear to show attempts to send an email **'postCheckin'** 

*#8 [internal function]: Controllers\Admin\AssetsController->postCheckin('257')*

and I see an error later.

*[2016-01-17 00:52:10] production.ERROR: exception 'Swift_TransportException' with message 'Connection could not be established with host mailbox.hercinia.mt [php_network_getaddresses: getaddrinfo failed: Name or service not known #0]' in /home/git/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:269*

**[Ubuntu 14.04]**
me@snipeit:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

**[Web is Apache]** 
root@snipeit:/home/me# apachectl -V
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Oct 14 2015 14:20:21
Server's Module Magic Number: 20120211:27
Server loaded:  APR 1.5.1-dev, APR-UTIL 1.5.3
Compiled using: APR 1.5.1-dev, APR-UTIL 1.5.3
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)
Server compiled with....
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=256
 -D HTTPD_ROOT="/etc/apache2"
 -D SUEXEC_BIN="/usr/lib/apache2/suexec"
 -D DEFAULT_PIDLOG="/var/run/apache2.pid"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="mime.types"
 -D SERVER_CONFIG_FILE="apache2.conf"

**[PHP Version]** 
root@snipeit:/home/git/snipeit/app/storage/logs# php5 --version
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies



I have manually edited a few records in the database, early on, but none recently.   I was trying to import records, and they went to the wrong category, so I tried to remove them.    I probably started over a couple times since then though, so this database may actually not have any manual edits in it.

**Comment by rmavery** [comment]
I learned a bit more, and discovered the untapped world of 'debug = true'.   
From that I have confirmed that the issue has to do with sending the email after the checkin process.   

This is the defining error:  
Swift_TransportException
HELP
Connection could not be established with host mailbox.mydomain.local [php_network_getaddresses: getaddrinfo failed: Name or service not known #0]

I will troubleshoot the mailer portion of the application to see if I can resolve this that way.   I didn't really have an issue with the mail portion not working, but apparently it's needed.

**Comment by snipe** [comment]
Turning on debugging is the first thing we recommend. 
http://docs.snipeitapp.com/getting-help.html

**Comment by rmavery** [comment]
Sorry.   I get in a hurry and skip through directions.  I am trying to do better ;-)

**Comment by rmavery** [comment]
Incidentally, debugging is awesome in this app.   Way more than I expected.  I thought it would just write additional logging to the file.   This is pretty sweet.

**Comment by snipe** [comment]
Any updates on this?

`Connection could not be established with host mailbox.mydomain.local [php_network_getaddresses: getaddrinfo failed: Name or service not known #0]`

Leads me to believe it's a DNS or networking issue.

**Comment by rmavery** [comment]
Sorry Snipe.   I got pulled to another project and haven't had a chance to get back to this.   
You're right.  It's apparently a DNS issue on my Linux server.   I can perform an NSLookup on the name and it returns properly, but ping can't find it.   I am investigating on the Linux side.    Thanks for looking into it.
