### ISSUE TITLE
Email settings issue

### ISSUE THREAD

**Issue by moniruss** [snipe/snipe-it#1649]
I have setup this in my local server using xampp. Everything is running smoothly so far. However no email is generating or not getting any alert. I have used my company email in it using smtp server settings.
'host' => 'mail.mycompany.com',
'port' => '25',  //which is the default port
'from' => array('address' => 'name@mycompany.com', 'name' => 'My Name'),
'encryption' => 'starttls',
'username' => 'name@mycompany.com',
'password' => '**********',
 'sendmail' => '/usr/sbin/sendmail -bs',
'pretend' => false,

how to check if its working or not? and what to do? i have also set my main email in general global settings as alert mail. but no mail so far! let me know. thanks

**Comment by abdullahalasham** [comment]
when creating a user select send a user credentials and see whether you receive any email , you should receive if the above settings are ok.

**Comment by moniruss** [comment]
I did. It shows internal 500 error; though user had been created. I guess its because of that mail settings or something.

**Comment by abdullahalasham** [comment]
you need to provide  more information http://docs.snipeitapp.com/getting-help.html

**Comment by devilsoulblack** [comment]
snipe what if mail not support 'encryption  if correct put none or null ?
