### ISSUE TITLE
Manager Reporting Issue

### ISSUE THREAD

**Issue by mahesh2471990** [snipe/snipe-it#1650]
Hello Snipe. 

Future Request for reporting Permission or group we can tell. Regarding this I have some blue in my mind.

As if now when we give a user (manager) permission of reporting he is able to see or view all the report of the Assets and history. Which is no use for him. It may be out of focus to a manger to check other assets information. Not required to see the others assets information.

@snipe I prefer as mention above 10 users who linked with their manager. 
When manager Login snipe it. Dashboard will be having information of this Assets ,lic, etc. Checkout. as now.

My request is there must be information of all 10 users(who has linked to manager)where they had been checkout with assets, lic in dashboard.

Where i have already mention in this ticket #1610 about fields. same here will be copied also
So if a user is manager. he should have Extra permission that we can set him to view the important fields of his linked users

So we can create manager Group. Give the permission of his own fields as well as USERS Fields (the most important) Permission. So we can manually assign which and all fields of user required to view in manager user dashboard.

For Example i have given some snapshot. To get better idea regarding this

When we come to Reporting section as if now. below snapshot.

this is permission given 
testind is user (having only user permission)
testmanager is manager of testind user (having reporting permission)
Snapshot below
![permission](https://cloud.githubusercontent.com/assets/16305213/12391892/fc392544-be10-11e5-86de-6d12c2cc096a.JPG)

Using manager login his dashboard. He should able to see the users information also
![manager](https://cloud.githubusercontent.com/assets/16305213/12391909/15e097f2-be11-11e5-92a7-756789bdcec9.JPG)

Reporting Section should be modified
where i mention in before lines. its not require to know all the things to him.

He is able see the all the history when we add the user in reporting group.snapshot below.

![managerff](https://cloud.githubusercontent.com/assets/16305213/12391914/266d7518-be11-11e5-874f-3554511111d3.JPG)

**Comment by mahesh2471990** [comment]
@snipe hello snipe how are you

Any update regarding this..
I am waiting for this type of deployment.
So i can implement this on Production. I am waiting for chance,..
Please help me out.. what is status.on this and my previous concern.
MANY QUESTION IN MY HEAD AND EXCITED TOO
When is next release? 
shall i be able to see those stuff which i told in new release

Sorry snipe i am actually excited.

That option is not available in ManageEngine software also, If we has in Snipe ITIT.. it would rock:-)

**Comment by snipe** [comment]
If we decide to implement something like this, it wouldn't be for several months. We have more urgent issues that benefit a larger portion of our user base that take priority.

**Comment by mahesh2471990** [comment]
I guess it must be based on votes
I am looking for to that features soon snipe. Thank you

@snipe when may be next stable release you planned
