### ISSUE TITLE
Error Creating Company

### ISSUE THREAD

**Issue by rvasquez151** [snipe/snipe-it#1651]
I am trying to create a company. Returns error "ReflectionException (-1)  Class Controllers\Admin\CompaniesController does not exist

**Comment by snipe** [comment]
Please see the getting help documentation:

http://docs.snipeitapp.com/getting-help.html

**Comment by rvasquez151** [comment]
Still getting the error when trying to access Companies.  Details below:
SnipeITversion: 2.0.5-pre-191-g948be5c
Windows 7 / WAMP Server version 2.5
Manual Installation


Error:
ReflectionException thrown with message "Class Controllers\Admin\CompaniesController does not exist"

Stacktrace:
#19 ReflectionException in C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php:504
#18 ReflectionClass:__construct in C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php:504
#17 Illuminate\Container\Container:build in C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Container\Container.php:428
#16 Illuminate\Container\Container:make in C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:462
#15 Illuminate\Foundation\Application:make in C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php:78
#14 Illuminate\Routing\ControllerDispatcher:makeController in C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php:51
#13 Illuminate\Routing\ControllerDispatcher:dispatch in C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php:967
#12 Illuminate\Routing\Router:Illuminate\Routing\{closure} in <#unknown>:0
#11 call_user_func_array in C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Route.php:109
#10 Illuminate\Routing\Route:run in C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1033
#9 Illuminate\Routing\Router:dispatchToRoute in C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1001
#8 Illuminate\Routing\Router:dispatch in C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:775
#7 Illuminate\Foundation\Application:dispatch in C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:745
#6 Illuminate\Foundation\Application:handle in C:\wamp\www\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php:34
#5 Barryvdh\Debugbar\Middleware\Stack:handle in C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Session\Middleware.php:72
#4 Illuminate\Session\Middleware:handle in C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php:47
#3 Illuminate\Cookie\Queue:handle in C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php:51
#2 Illuminate\Cookie\Guard:handle in C:\wamp\www\snipe-it\vendor\stack\builder\src\Stack\StackedHttpKernel.php:23
#1 Stack\StackedHttpKernel:handle in C:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:641
#0 Illuminate\Foundation\Application:run in C:\wamp\www\snipe-it\public\index.php:49

**Comment by snipe** [comment]
Try running `composer dump-autoload`
