### ISSUE TITLE
No US Dollars ($) in currency?

### ISSUE THREAD

**Issue by rvasquez151** [snipe/snipe-it#1652]
I noticed that there is not a selection for US Dollars ($) in Default Currency. Am I missing something?

**Comment by snipe** [comment]
Please see the getting help documentation:

http://docs.snipeitapp.com/getting-help.html

**Comment by moniruss** [comment]
you need to set it from admin>>settings>>Edit Settings option. if you want to add another currency that's not in that list, then its different issue.
