### ISSUE TITLE
Anyone using Snipe-It for non-IT asset management?

### ISSUE THREAD

**Issue by ustamills** [snipe/snipe-it#1653]
[If there is an official Snipe-IT forum somewhere, please let me know.  This is the closest I could find. I'd prefer not muddying up Issues with general topics, if possible.]  

I'm VP of Tech at a small company that has stepped just beyond the start-up phase.  We need to track our IT inventory but we also have other inventory we should be tracking for capex and other purposes. These might be things like medical testing equipment, office furniture, conference phones, etc.  I would appreciate it if someone would comment on whether or not the IT focus of this software makes it unsuitable for other asset types.  If you've had good success working around this, I would appreciate any tips there as well.

Thanks!  
Drew

**Comment by snipe** [comment]
Hi @ustamills - no worries, this is the right place to raise issues like this.

There's nothing specific about Snipe-IT that precludes you from using it for non-IT assets. We have some hosted customers who use it for all kinds of things, and especially with the addition to the of custom fields, there's no reason you couldn't extend it out to handle hat ever you needed. The main thing to note as you're doing so is the difference between assets, accessories and consumables. Assets are anything that has a serial number and a unique asset tag. Accessories are things that can be checked out, but do not have an asset tag or serial number (no custom field support for accessories yet either), and consumables are throw-always that you want to track for general inventory purposes but that don't ever get checked back in.

**Comment by zmorrow** [comment]
The custom fields have allowed me to add in contract and lease info, if I was savvy enough I would add in an email reminder on my equipment on lease to email me a couple months before EOL to remind me to get it together.
