### ISSUE TITLE
Search Fields remain cached after extensive periods of inactivity

### ISSUE THREAD

**Issue by tmongero** [snipe/snipe-it#1654]
When you filter 'People' or 'Assets' by a string in the search field, no matter how much time passes by once you load SnipeIT again in the browser, that search filter is still in-place. This can be deceiving, as I opened SnipeIT today and was in a panic for a moment, wondering why my 'Users' page was down from ~700 users to only 9.

I realized this was because on Friday (It's now Monday, and the snipeIT webpage has been closed all weekend), I had performed a search under the Users page, and it seems to remain despite the webpage being re-opened after the weekend.

I think these search filters should reset after leaving the page, or at least after X amount of time (perhaps a configurable setting)?

Let me know if this isn't actually a bug and I can update this on my end.

**Comment by AVenzorSO** [comment]
I would like this as well -- or perhaps a more obvious indicator that results are being filtered.

**Comment by snipe** [comment]
The problem is that the cookie that stores the search filter is also the one that stores which columns you have selected. If we expired that cookie in a short time, you'd have to re-show or re-hide the columns you want every time it expires.

**Comment by tmongero** [comment]
@snipe Gotcha. Well, it isn't breaking anything so it's not mission-critical.

Thanks!
