### ISSUE TITLE
Anyone sourced a weatherproof label compatible with Snipe-IT?

### ISSUE THREAD

**Issue by ustamills** [snipe/snipe-it#1655]
Has anyone sourced a weatherproof label compatible with Snipe-IT?

**Comment by lehtmets4** [comment]
Same question here. Right now we are printing it on the apli.com A4 27 label 3cm*7cm paper. I had to adjust a bit the labels.blade.php to fit the labels in 3 rows and exacly on the stickers. 
But yes, we search the same thing. 

I will post another question down here also: Is there are way to use Snipe-IT to print labels on to Zebra GK420T label machine? Anyone have tried it?

**Comment by chrstmnn** [comment]
We're using Dymo 1976411 labels and that works fine...

**Comment by twok** [comment]
I'm planning to use Herma's No 4222, however I still got issues with borders. Hoping for the generate labels and save as PDF feature! since all browsers seem to mess up anything I input (even with the border settings adjusted)

**Comment by MightyMike13** [comment]
> We're using Dymo 1976411 labels and that works fine...

trying to get it to work with that Labels and a Dymo Labelwriter 450 . i would appreciate it if u can share ur setting to make this work.

**Comment by jaydenrussell** [comment]
I have a Brother PT-2700 printing labels, trial and error to get the sizing to work.

**Comment by memtech3** [comment]
Buy pre printed customized labels from a company like idplate.com and assign them to assets as they come in.

**Comment by davidkillingsworth** [comment]
@memtech3 can you explain the steps to use pre-printed labels and assign them to assets?  I have looked through the documentation, but have not found a way to do that yet.

We are planning to purchase weather proof labels from an online retailer and would like to use them with Snipe-IT.

**Comment by memtech3** [comment]
You can buy pre printed labels and just set the tag of the item to the number on the tag. If you need I can send pictures
