### ISSUE TITLE
Error 500: Backup page 

### ISSUE THREAD

**Issue by Rumblee** [snipe/snipe-it#1656]
![snipeit error500](https://cloud.githubusercontent.com/assets/16761369/12414163/f65ebb24-be93-11e5-9da6-7d8828dce424.PNG)
Hello there,

I'm using a Ubuntu 14.04.3 LTS Server to run SnipeIT and have recently been unable to access the Backups tab on the site. Everytime I try to approach it, it gives me a error 500. (Debug log of the error should be included as a picture.) However, I can manually, via command line, still create backups using php artisan snipeit:backup. The rest of the site is in working condition.

I installed SnipeIT using the install.sh file so I should be running the latest version of SnipeIT I think.

**Comment by abdullahalasham** [comment]
just refer to the following issue and make sure that you configured the backup config file correctly    #1337

**Comment by Rumblee** [comment]
Just to get back on this, It did turn out to be the backup config file. I had it set to /app/storage/dumps/ and it should have been /var/www/snipeit/app/storage/dumps. Thanks for the help!
