### ISSUE TITLE
Calendar not working

### ISSUE THREAD

**Issue by rvasquez151** [snipe/snipe-it#1657]
I upgraded to v2.0.5-pre-191-g948be5c  Used to get a popup calendar when selecting a date. It appears to have vanished.  Any suggestions?

**Comment by abdullahalasham** [comment]
is it working in demo version if so then please provide more information on your issue http://docs.snipeitapp.com/getting-help.html

**Comment by rvasquez151** [comment]
It appears to work in the demo version.  I just upgraded a few days ago. It was working in the previous version.

**Comment by rvasquez151** [comment]
Ok, got it working.  I forgot to clear out the cache in 'apps/storage/cache' and 'apps/storage/views'  After clearing and restarting the Wamp server... appears to be working.
