### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by sundaresanm** [snipe/snipe-it#1658]
Hi all,

  I am trying to install snipe-it in WAMP Server . i couldn't do it in way of official documentation. kindly give me the steps to install.?

 Is that possible to install  it in wamp i,e (APACHE SERVER)?

**Comment by abdullahalasham** [comment]
Hi , 

Yes it is possible to install it in WAMP server and it Almost the same as installing it in any server with following settings :  
 the server setup can be found in this link : http://docs.snipeitapp.com/installation/server/wamp.html
the rest of installation instructions can be found in this link :  http://docs.snipeitapp.com/installation/

and make sure that you enable Apatche Modual :  rewrite-modual  to avoid the link redirect problems as it is not enabled  by default and if you face any issue kindly feel free to ask.

kind regards

**Comment by sundaresanm** [comment]
Thanks @abdullahalasham ...

Now i installed successfully but when i pass this URL #http://localhost/snipe/public/auth/signin getting below page and i couldn't login 

![image](https://cloud.githubusercontent.com/assets/11832747/12513038/70fa6124-c0d0-11e5-879f-b6d1b4e6cca4.png)

**Comment by abdullahalasham** [comment]
hi,

use the username and password you specified during the installation if you don`t remember it then you get one of the below options:

- reinstall complete database and make sure that you write down the username and password OR
- execute the following sql code in the user database and it will create the (user : adminuser with password : 12345678) and make sure that you change it after you get access to the system.

```mysql
INSERT INTO `snipeit_laravel`.`users` (`id`, `email`, `password`, `permissions`, `activated`, `activation_code`, `activated_at`, `last_login`, `persist_code`, `reset_password_code`, `first_name`, `last_name`, `created_at`, `updated_at`, `deleted_at`, `website`, `country`, `gravatar`, `location_id`, `phone`, `jobtitle`, `manager_id`, `employee_num`, `avatar`, `username`, `notes`, `company_id`) VALUES ('265', 'adminuser@localhost', '$2y$08$HzNTYud6RFEDOVZBXQu4FOnlXIYLwT4jWlHcadbhBXTDCS/YbytX2', '{"superuser":1,"admin":1,"user":1,"reports":1}', '1', NULL, NULL, NULL, NULL, NULL, 'admin', 'user', '0000-00-00 00:00:00', '0000-00-00 00:00:00', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'adminuser', NULL, NULL);
```

hope this helps

**Comment by sundaresanm** [comment]
Thank you very much abdullahalasham..

Its working fine
