### ISSUE TITLE
Deprecation report is not proper

### ISSUE THREAD

**Issue by dahiya81** [snipe/snipe-it#1660]
dear Sir,

The Deprecation report is not proper in CSV format, unable to do the sum etc for the amount .

Please find attached report.

**Comment by snipe** [comment]
A) not a sir.
B) there was no attachment to this message.
C) http://docs.snipeitapp.com/getting-help.html

**Comment by dahiya81** [comment]
I am unable to upload the file it says it don't support the file tried ZIP and CSV file

**Comment by snipe** [comment]
Then try taking a screenshot, or pasting it into pastebin. I can't troubleshoot a file I can't see.

**Comment by dahiya81** [comment]
This is how this is appear in the Excel and we can't add the amount and all in Excel

![image](https://cloud.githubusercontent.com/assets/14053556/12634643/5dc44270-c5a1-11e5-8ed4-761e2e1f1133.png)

**Comment by snipe** [comment]
Do you actually have purchase costs for those two assets?

**Comment by snipe** [comment]
(Also try making the money fields wider and see if the values are just hidden)

**Comment by dahiya81** [comment]
i tired and after doing wider i am able to see the amount but can't do any type of calculation on those like other reports

**Comment by dahiya81** [comment]
Any update on this
