### ISSUE TITLE
Time offset?

### ISSUE THREAD

**Issue by seanism** [snipe/snipe-it#1662]
Is there a place to change the time offset?  It shows GMT but I am PST.

**Comment by ddreier** [comment]
You can set the timezone in `<snipe-it directory>/app/config/app.php`.

**Comment by seanism** [comment]
Ahh we have a hosted version so we don't have access to that. I'll submit a
ticket to get this resolved. Thanks.

**Comment by snipe** [comment]
Should be fixed for you, @seanism
