### ISSUE TITLE
Installation Issue "This webpage not available"

### ISSUE THREAD

**Issue by shafrax** [snipe/snipe-it#1664]
i set up "snipe it" windows environment.
when i tried to access the page is shows "This webpage not available"
and also i noticed it automatically change http://snipeit.mydomain.com to https://snipeit.mydomain.com

anyone please help?

**Comment by ddreier** [comment]
In IIS Manager, open URL Rewrite for your Snipe-IT site. Find the rewrite rule for https (it's usually the first one) and disable it.

**Comment by dudeincali** [comment]
I like the security, but I think there's needs to be better notice (or turn it off) for the https. It bricked my install until I had to poke around to correct it. Should be more obvious, we do have novices (myself included) that are trying to setup and use this.

**Comment by snipe** [comment]
Pull requests on our documentation are always welcome.

**Comment by shafrax** [comment]
thanks it work
