### ISSUE TITLE
Importing user via LDAP running into issues

### ISSUE THREAD

**Issue by maxr786** [snipe/snipe-it#1665]
Hi,
Thank you very much for taking the time to take a look at this issue and providing solutions for it. I did my research prior to this port, and I couldn't a solid answer to my question. Anyway, I got snipe-it up and running on a Linux server and pretty excited to be using it. Thank you very much from all the contributors for creating such a masterpiece.
Purpose: Importing users via LDAP so I can assign assets to.
Issue:  Could not bind to the LDAP server. Please check your LDAP server configuration in the LDAP config file. Error from LDAP Server: Can't contact LDAP server
Background info: Snipe-it is installed on a Linux Server, my LDAP server is Windows Server 2012 Domain controller. I have copied the ldap.php and filled in the appropriate information by following snipe-it documentation. I am not sure why i am still getting the error. Please refer to the attachment for LDAP.php configuration.
![ldap1](https://cloud.githubusercontent.com/assets/16676544/12488678/beafebdc-c03a-11e5-89b6-911b1dd85a4c.PNG)
![ldap2](https://cloud.githubusercontent.com/assets/16676544/12488680/beb17ef2-c03a-11e5-92f9-df8b4e0ebb1f.PNG)
![ldap3](https://cloud.githubusercontent.com/assets/16676544/12488679/beb09168-c03a-11e5-8b79-15e6c1478ba4.PNG)

**Comment by ddreier** [comment]
If you're running (IIRC) version 2.0.6 or newer LDAP is configured through the UI, not in ldap.php.

**Comment by maxr786** [comment]
Hi,
Thank you very for your reply: I added the same information under the LDAP settings using the UI. Still getting the same error.

**Comment by snipe** [comment]
"Can't contact LDAP server" - firewall issue perhaps?

**Comment by maxr786** [comment]
Hello Snipe, 
Thanks for your reply. Out of curiosity i turned off firewall completely on the server to see if it will work, but it didn't. I tried testing the LDAP URL i have and i could connect to it using ldp.exe built-in inside windows.

**Comment by maxr786** [comment]
Update: 
I used the IP address of the server instead of the hostname and it worked like a charm. 
Thank you very much for your help. :)

**Comment by snipe** [comment]
:+1:

**Comment by itborn** [comment]
Hi 
Thank you for your previous comments i have worked though the manual to get the LDAP working with version 3 i have disabled the firewall used the ipaddress etc but i stall get a  Could not bind to LDAP: Can't contact LDAP server error on testing LDAP
