### ISSUE TITLE
LDAP Import Issue

### ISSUE THREAD

**Issue by beigemonkey** [snipe/snipe-it#1666]
This is more of a question than an issue.  I have snipe-it 2.10 installed and I was trying to configure it to import users from Windows 2012 Active Directory.  After hours of searching, trial and errors I finally got it working.  I configured the LDAP setting through the UI initially, but it was not working, so I starting searching and almost everyone says you need the ldap.php file in /app/config/production.  So I created the file, input all the values, but it still wouldn't work.  I finally went back to the UI, punch in a few LDAP string variations and voila it works.

So what I noticed is when I compared the values on the UI to the file it looks like the UI is not saving to ldap.php.  So I'm pretty certain the application does not use the settings in the ldap.php file.  So where exactly is the UI saving the settings to?  Also, it would be nice to add this to the documentation.

**Comment by snipe** [comment]
UI settings are saved in the database. `ldap.php` is deprecated. http://docs.snipeitapp.com/manual/user-management/index.html#optional-ldap-configuration
