### ISSUE TITLE
Custom Fields - Delete button doesn't work

### ISSUE THREAD

**Issue by lehtmets4** [snipe/snipe-it#1669]
Hello.

I have a problem, that I can't delete nor edit the custome fields. I just made one custome field and added it to the custome fieldset "Asset with MAC Address". After that I added only one value to one of the assets. After that I realized I want to change the name of the custom field, but I can edit it nor delete it to make a new one with the right name! 
I read that you can not delete custom field which have values, so I went to the only asset I added the value and deleted it. But still no luck with editing or deleting the custom field.

Please help!

I can see delete buttons, but they seem to be unactive. Nothing happens when I try to click on it and I tried IE, Mozilla and Chrome. 

![image](https://cloud.githubusercontent.com/assets/16795054/12505617/40596b02-c0f1-11e5-9f61-2a9d63fb1a2d.png)

**Comment by snipe** [comment]
You can't delete a custom field that belongs to a fieldset or that have a value in the database for any assets.

**Comment by lehtmets4** [comment]
How can I remove it then from the fieldset?

![image](https://cloud.githubusercontent.com/assets/16795054/12505685/c9580350-c0f1-11e5-9df6-1a4924b3efa2.png)

**Comment by lehtmets4** [comment]
Any answer? How can I remove?

**Comment by vabue** [comment]
As I see for 2.10 version there is no possibility to remove custom field from the fieldset in the user interface.
But this feature is very desired.

**Comment by cphames** [comment]
I would also like a way to remove a custom field from a fieldset.

**Comment by uberbrady** [comment]
@snipe fixed this feature on 3.4.alpha, and that fix will be live when that goes into production.
