### ISSUE TITLE
Assumption of FQDN - IP address directly to Snipe

### ISSUE THREAD

**Issue by dudeincali** [snipe/snipe-it#1671]
I would like to know (or would appreciate someone to direct me) to where I can find a simple way to host this off my IP address (it's in a VM) so I don't have to make any entries in DNS for hosting Snipe. I'm on Ubuntu 14. I've dug around here all over and didn't find anything obvious. I'm assuming it's related to mod_rewrite and virtual hosts, but a simple example would be totally appreciated. (I'm a novice, but just dangerous enough) Thx everyone!

**Comment by snipe** [comment]
You might try something like http://www.dnsdynamic.org?

**Comment by snipe** [comment]
I'm not actually sure what you're asking here. You can use an IP address or FQDNm whichever you want. If you're encountering an issue using the IP address, you'll have to give us more information.
