### ISSUE TITLE
New Install - Web Page is not available

### ISSUE THREAD

**Issue by xian1267** [snipe/snipe-it#1672]
New to all this,   Installed on Windows Server 2008,   followed instructions and feel I did those correctly.

I did come across installing  composer installer,  not sure if I need that,  however when I tried to install the program, it prompted for the location of  php.exe  which I did not have or could not find it.

I am not sure if this is the reason the program wont run.

Please any help would be great.

![snipeit error](https://cloud.githubusercontent.com/assets/16842283/12521533/bdeeff40-c110-11e5-93b5-876a2eda4079.jpg)

![image](https://cloud.githubusercontent.com/assets/16842283/12521870/e0ce3cc2-c112-11e5-8681-5892a2010e8f.png)

**Comment by ddreier** [comment]
You need PHP and Composer to run Snipe-IT. Did you install PHP and the PHP Manager from WebPI?

**Comment by xian1267** [comment]
No,   I have the composer downloaded,  where do I find the PHP download?

**Comment by ddreier** [comment]
The easiest way is to use the Web Platform Installer (It's already in IIS, under the Management section).

**Comment by xian1267** [comment]
![image](https://cloud.githubusercontent.com/assets/16842283/12523282/85017ab8-c11b-11e5-85a9-e684b4ab9777.png)


Ok,  both are now installed and error as above.  I feel like I am closer now to getting this fixed

**Comment by ddreier** [comment]
Under URL Rewrite, you need to disable the rule that redirects to HTTPS. It's usually the first rule, and it's the only rule that will explicitly have the text "https" in it.

**Comment by xian1267** [comment]
![image](https://cloud.githubusercontent.com/assets/16842283/12523505/f29bc08c-c11c-11e5-8a13-4462bd799ae2.png)


New error screen,  hopefully getting closer

**Comment by ddreier** [comment]
You probably need to go to the Default Document section in IIS and make index.php first.

**Comment by xian1267** [comment]
![image](https://cloud.githubusercontent.com/assets/16842283/12523680/08690a68-c11e-11e5-85e6-f5f592ca8237.png)


Still same windows as above

**Comment by ddreier** [comment]
What happens if you go to http://cncserver/snipe-it/index.php?

**Comment by ddreier** [comment]
Actually, hang on. What do the Basic Settings look like for the Snipe IT website?

**Comment by xian1267** [comment]
where do I find the basic settings?

**Comment by xian1267** [comment]
![image](https://cloud.githubusercontent.com/assets/16842283/12523944/75df6dde-c11f-11e5-9b95-1f1e39238193.png)

This is what I get trying to go to the site from another PC

**Comment by ddreier** [comment]
Right click on the site, Basic Settings.

And, you appear to be missing index.php. That's a problem. Show the contents of C:\inetpub\wwwroot\snipe-it.

**Comment by xian1267** [comment]
![image](https://cloud.githubusercontent.com/assets/16842283/12524052/11623bf6-c120-11e5-8e34-c5296f90fd5b.png)

**Comment by xian1267** [comment]
![image](https://cloud.githubusercontent.com/assets/16842283/12524075/40c6a616-c120-11e5-8389-66a2d74ed276.png)

**Comment by ddreier** [comment]
Try http://cncserver/snipe-it/public. If that works (and it's how you want to access Snipe-IT), you'll have to set up a virtual directory under the Default Web Site that points to C:\inetpub\wwwroot\snipe-it\public.

**Comment by xian1267** [comment]
![image](https://cloud.githubusercontent.com/assets/16842283/12524181/ebf50bf4-c120-11e5-86be-6347f10b86db.png)


I am sorry this is a pain,  I appreciate your help.

**Comment by ddreier** [comment]
Is that last image from the server itself? I need to know what the actual error code is. Also, check C:\inetpub\wwwroot\snipe-it\storage\logs for the latest message in the latest log file.

**Comment by xian1267** [comment]
![image](https://cloud.githubusercontent.com/assets/16842283/12524300/c45a54d6-c121-11e5-97f6-76a1ff7a2557.png)

Storage was not under  snipe-it/   it was under snipe-it/app/storage
Yes that was the last image from server when going to the  http://cncserver/snipe-it/public

**Comment by ddreier** [comment]
Try setting debug to true in snipe-it\app\settings\production\app.php. Also, make sure that the folder permissions are set up as described in http://docs.snipeitapp.com/installation/server/windows.html.

**Comment by xian1267** [comment]
will do that now

![image](https://cloud.githubusercontent.com/assets/16842283/12524605/d0847be0-c123-11e5-870c-e1b9be99665c.png)

There is no settings folder

**Comment by ddreier** [comment]
snipe-it\app\config\production\app.php, sorry

**Comment by xian1267** [comment]
I found it and made the change,  Security on folders was done as well.  I have to be missing something small,  I hope

**Comment by xian1267** [comment]
no bueno

**Comment by ddreier** [comment]
I would still like to see the Basic Settings and Bindings for the "Snipe IT" site. Because right now, I'm pretty sure that you're still going through the Default Web Site.

**Comment by xian1267** [comment]
![image](https://cloud.githubusercontent.com/assets/16842283/12524786/519aa726-c125-11e5-9637-a582d90eea8b.png)

I still cannot find Basic Settings,  when I right click on the site this is what I get
![image](https://cloud.githubusercontent.com/assets/16842283/12524810/80ef5bb6-c125-11e5-83ca-8afda49a9277.png)

**Comment by ddreier** [comment]
So, what happens when you go to http://assets.portal.local?

**Comment by xian1267** [comment]
same thing,  same screen,  also I have tried with local IP address as well.

**Comment by ddreier** [comment]
My bad, I keep thinking that Basic Settings is in that context menu. But it's in the Actions pane on the right.
![image](https://cloud.githubusercontent.com/assets/82290/12524844/c419eef6-c125-11e5-842d-b38b8dd17122.png)

**Comment by ddreier** [comment]
You should probably test with assets.portal.local from now on. Because anything else is going to use the Default Web Site.

Next up is looking through the IIS access logs to see what HTTP code is actually being returned by IIS. If I had to guess, that log is going to be in C:\inetpub\logs\LogFiles\W3SVC2.

**Comment by xian1267** [comment]
![image](https://cloud.githubusercontent.com/assets/16842283/12524882/0f328560-c126-11e5-866c-e4a564c0e3b0.png)


I always find it right afterward too

**Comment by xian1267** [comment]
![image](https://cloud.githubusercontent.com/assets/16842283/12524933/50cba222-c126-11e5-838d-4791f13c8f4b.png)

**Comment by ddreier** [comment]
I wouldn't worry about that warning. Also I just noticed in the screenshot you posted of Internet Explorer, it says HTTP 500 Error in the title bar.

In IIS Manager, you now have the PHP Manager icon. Open that and post if you get output when clicking on "Check phpinfo()" and what the last few lines of the PHP Errors log are.
![image](https://cloud.githubusercontent.com/assets/82290/12525002/c0325336-c126-11e5-9361-0504710996f3.png)

Also, did you set the key at the bottom of snipe-it\app\config\production\app.php?

**Comment by xian1267** [comment]
![image](https://cloud.githubusercontent.com/assets/16842283/12525080/5dbfe352-c127-11e5-9123-009d446adfbf.png)

This is to my help desk software,  It will not allow me to choose the Snipe IT site.

What key is needed to be set on  app.php?  I did put the True value for logging

**Comment by xian1267** [comment]
![image](https://cloud.githubusercontent.com/assets/16842283/12525126/9c2f87e6-c127-11e5-9fc9-964e410c9613.png)

Sorry had wrong site selected

**Comment by xian1267** [comment]
[PHP70x64_errors.txt](https://github.com/snipe/snipe-it/files/101557/PHP70x64_errors.txt)

**Comment by ddreier** [comment]
````
[22-Jan-2016 14:22:17 America/Los_Angeles] PHP Fatal error:  require(): Failed opening required 'C:\inetpub\wwwroot\snipe-it\bootstrap/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:\inetpub\wwwroot\snipe-it\bootstrap\autoload.php on line 17
````

Did you complete the install process after installing PHP and Composer? You should probably run through all of the install steps again. Or start from step 3 at least.

**Comment by ddreier** [comment]
Also, you click OK on that "Choose Site and URL" dialog to view the actual phpinfo() output. But I don't need to see that any more.

**Comment by xian1267** [comment]
will do

**Comment by xian1267** [comment]
I realized that only did the windows Server install and did not do the first several Steps.

I have installed the mysql database

It is asking for the cli   below.  When i run the command, nothing happens. 


Windows

Open C:\inetpub\wwwroot\snipe-it in Windows Explorer

Right Click and select Use Composer here
Type php artisan app:install --env=production and follow the prompts
When it asks you if you’re sure you want to run the migrations, type in y. You may have to do this a few times.

**Comment by ddreier** [comment]
What do you mean, "when I run the command, nothing happens"? That's practically not possible, you're going to get some kind of output. Please post a screenshot.

**Comment by xian1267** [comment]
Thank you so much for your help.

I uninstalled, reinstalled and still did not get it to work.   I gave up on it.

If you don’t mind helping,  I can give it another shot and send the screen shot.

Thanks for all your help

**Comment by babz777** [comment]
Hi All,  I seem to be stuck at the same point. When i run the comman nothing happens.. see screenshot below...
![cmd](https://cloud.githubusercontent.com/assets/18030139/13985863/13ab7042-f0f7-11e5-8ca7-9bdacca7612e.png)

**Comment by babz777** [comment]
![cmd](https://cloud.githubusercontent.com/assets/18030139/13985884/387ba856-f0f7-11e5-888f-85ddae8a3095.png)

**Comment by babz777** [comment]
ok i need to install composer WITH the SHELL MENUS in order to it to run the command but now some errors...
![cmd](https://cloud.githubusercontent.com/assets/18030139/13987297/caf31578-f0fe-11e5-8ba6-569653636fb1.png)

**Comment by ddreier** [comment]
@babz777 have you run `composer install --no-dev --prefer-source`?

**Comment by babz777** [comment]
Thank you responding...
![cmd](https://cloud.githubusercontent.com/assets/18030139/13992471/27fb39b6-f114-11e5-86ca-b318b4ca9040.png)

**Comment by ddreier** [comment]
Looks like you need to install or enable the PHP MySQL Extension.

**Comment by snipe** [comment]
Also the fileinfo extension.

**Comment by babz777** [comment]
![cmd](https://cloud.githubusercontent.com/assets/18030139/14015766/58184ad6-f1b3-11e5-8d8f-fc5a9ccfa634.png)

Enabled both extensions. Now i'm getting the above. Any ideas?
appreciate the help

**Comment by babz777** [comment]
it was a directory permissions issue now sorted. So i've managed to run composer install --no-dev --prefer-source.

Apologies for the long screenshot i couldnt get the rest of the data in...

![cmd](https://cloud.githubusercontent.com/assets/18030139/14016095/c6eced16-f1b5-11e5-95ea-df701067e200.png)

**Comment by babz777** [comment]
i've decided to run php artisan app:install --env=production and have completed the CLI installer config along with the secret key. Finally just need to get my site to publish correctly now... 'webpage unavailable'. Index.php is at the top of the list. Could you tell me what i'm supposed to enter as the app url in the app.php file? where it says '..production.yourserver.com'

**Comment by ddreier** [comment]
The URL that goes in app.php is the URL that you're going to use to access the app.

You should be able to go to http://127.0.0.1/ (plus a sub-directory, if that's how you've set it up) and get something regardless of the URL setting in app.php.

**Comment by babz777** [comment]
local host ip shows the default website splashscreen. I've added the correct url in app.php. still cannot display webpage :(
![cmd](https://cloud.githubusercontent.com/assets/18030139/14021182/558958fe-f1d2-11e5-9e20-85ccb750b1d5.png)

**Comment by ddreier** [comment]
Ok, so what happens if you go to http://assets.portal.local? Have you set up the DNS yet?

**Comment by babz777** [comment]
i get the common  'IE cannot display this page'. DNS has been setup

![cmd](https://cloud.githubusercontent.com/assets/18030139/14023947/d568a384-f1de-11e5-8603-8b5611b3b939.png)

**Comment by ddreier** [comment]
That's not quite right.

If you want http://assets.portal.local to go to Snipe-IT you need to have an A (or AAAA) or CNAME record for assets.portal.local pointing to the server that's hosting the app.

Or, if you want http://snipeit.assets.portal.local to go to Snipe-IT then the DNS is fine, but the IIS Binding and URL in app.php need to be changed to http://snipeit.assets.portal.local.

**Comment by babz777** [comment]
i've updated the binding and app.php to point to http://snipeit.assets.portal.local. Still no dice...

![cmd](https://cloud.githubusercontent.com/assets/18030139/14105291/9710d8aa-f5a2-11e5-9eda-e458a10634e7.png)

**Comment by ddreier** [comment]
What is the result of `nslookup snipeit.assets.portal.local` (in the command prompt)?

**Comment by babz777** [comment]
![cmd](https://cloud.githubusercontent.com/assets/18030139/14113236/f1de5d6c-f5c9-11e5-87b2-d4deed473b9b.png)

**Comment by ddreier** [comment]
Is that correct? Do you want Snipe-IT accessible via 94.136.40.82? Is there a firewall b/n the server hosting Snipe-IT and the Internet? Does it have the correct ports open?

**Comment by babz777** [comment]
Thanks for all your help. I finally got it working... just one issue though,,,,
browsing to the site via iis fails. see below
![cmd](https://cloud.githubusercontent.com/assets/18030139/14213253/e3a7468e-f82e-11e5-9516-c783261b6ec9.png)

adding index.php to the end of the URL loads the snipe-it login page,

**Comment by ddreier** [comment]
My first guess is that something's wrong with the URL Rewrite rules.
