### ISSUE TITLE
[Feature Request] Off Board User Action with auto check in

### ISSUE THREAD

**Issue by jghanlon** [snipe/snipe-it#1673]
This would be a User Action in the same column as Edit and Delete.

Pressing this button would bring up the Off-Board (OFB) pop up window for that user.
It would confirm that all assets, licenses, etc would be checked back in.  Maybe there could be a line item for every item assigned to that user so that you could control the action of each item or just click a main button for check-in all items.
The user would also be added to the OFB group and be hidden (or grayed out?) from the main People view.

We have a very high rate of Onboard and Offboards every week and this would be a big help.

Thanks,
Jeff

**Comment by snipe** [comment]
Closing this (late), as it was added in v3
