### ISSUE TITLE
Dropdown list and multiple select list custom field

### ISSUE THREAD

**Issue by vabue** [snipe/snipe-it#1676]
Text fields with validation are great, but often it is better to restrict user to certain values. 

Example.
We need to understand what connections support available displays: HDMI, DP, DVI, D-Sub. In text values editor can print DP as "Display Port", "Dispport", "D P", "D. P." and so on. And searching on them would be inconvenient.

[Drupal 7 List module](https://www.drupal.org/documentation/modules/list) can be example for the UI for it.

**Comment by SylentBobNJ** [comment]
+1 this, it would be a nice addition.
