### ISSUE TITLE
Add description for custom fields

### ISSUE THREAD

**Issue by vabue** [snipe/snipe-it#1677]
Every form need to provide some help for editors. Now custom fields have only name for it.

![Alt text](https://monosnap.com/file/CrrDPRuu8UDdbeGRVsxrDnsjJOMPde.png)

![Alt text](https://monosnap.com/file/QYbqEeXtsEiKFDT46PmADhwsaXz0Vl.png)

**Comment by snipe** [comment]
This is in the upcoming v4 release
