### ISSUE TITLE
Locations - Assets Retired & Assets Assigned

### ISSUE THREAD

**Issue by jacp9** [snipe/snipe-it#1678]
Hi All,

System Information:
Snipe-IT version        v2.1.0-47-g39f40a3 
PHP Version     5.5.9-1ubuntu4.14
Laravel Version     4.2.17 

I wonder if anyone had this issue before. We have assets which are assigned to specific locations and checked out to specific users. When we go in to Locations, we can see that all of the assets assigned to the specific locations shows as Retired and when we go into this Location, there are no assets to view although we have number of assets which should show up. Does anybody know why?

Here are 2 screenshots which explain my issue:
1. General 'Locations' tab view:
   ![assets - location view](https://cloud.githubusercontent.com/assets/16577946/12550578/a9d9401c-c35c-11e5-9e57-d666b5b16c30.PNG)
2. View of a specific location, in this case this is the top one which should show 16 assets.

![assets - location view1](https://cloud.githubusercontent.com/assets/16577946/12550601/ce0c2864-c35c-11e5-8535-6c94bbded475.PNG)

All the best!

**Comment by jacp9** [comment]
Anybody? Also do you know why users imported via LDAP do not get assigned to default users group?

**Comment by jacp9** [comment]
I checked users_groups sql table and basically it doesn't create a user_id and group_id entries for any new users imported via LDAP.

**Comment by JonathonReinhart** [comment]
@jacp9 Please refrain from asking multiple questions in a single issue.

Another day, another relevant issue closed by **stale** bot.

@snipe This is still a problem. I'm seeing this problem (v4.6.7) with seemingly random locations, just as @jacp9 described. The counts will be correct on the Locations overview, but browsing some locations shows zero assets.
