### ISSUE TITLE
Problem with LDAP Authentication after Upgrade

### ISSUE THREAD

**Issue by m4rphel** [snipe/snipe-it#1679]
Hi,

I´ve encountered a problem after upgrading from 2.0.6 to the latest version:

With each try to login, while LDAP is enabled I get a message ->

[2016-01-25 15:11:02] production.DEBUG: User did not authenticate correctly against LDAP. Local user was not updated. [] []

* tried different Accounts
* checked the config (was written to DB while migration) in the settings table
* Microsoft Active Directory as LDAP Server
* LDAP itself works fine, as other services could authenticate successfully
* did not try a rollback yet...

What else can I check or try to get this working again?
 
Regards

**Comment by NaurisSadovskis** [comment]
I have a similar issue - the only workaround is to change password through the snipeit. Any ideas? FYI, it was also happening in 2.1.0-pre

**Comment by ddreier** [comment]
I know you said that you checked the config, but would you please post it (redacting the sensitive stuff)?

**Comment by m4rphel** [comment]
Here you go, zip contains an edited settings table.
The security log on the AD Server told me a successful login with the ReadOnly LDAP User credentials

[settings_edited.zip](https://github.com/snipe/snipe-it/files/103608/settings_edited.zip)

**Comment by ddreier** [comment]
Sorry, I'm not gonna download a random zip file. A screenshot of the LDAP settings on the settings page would be great. You can just paste it into the GitHub comment box.

**Comment by NaurisSadovskis** [comment]
Here are my settings, if this helps
![screenshot](https://cloud.githubusercontent.com/assets/15460047/12559383/c80d618c-c38c-11e5-8f6e-955c794e1aa5.png)

**Comment by m4rphel** [comment]
![settings_edited](https://cloud.githubusercontent.com/assets/7916398/12559398/42505d7a-c395-11e5-8b94-9e933851cf11.JPG)

**Comment by ddreier** [comment]
Ok. It looks like the upgrade process messing up the "LDAP Authentication query" which should read `samaccountname=`.

Here's mine (which works), for example:
![image](https://cloud.githubusercontent.com/assets/82290/12559558/74d51f40-c35b-11e5-94e7-f6f24757a4b7.png)

**Comment by m4rphel** [comment]
Yes :) Login successfull

Thx!

**Comment by m4rphel** [comment]
But, in the deprecated.ldap.php its also noted, as uid=

So, I didn´t thought about wrong settings

**Comment by NaurisSadovskis** [comment]
Perfect, thanks! That did it for me too.

**Comment by merid14** [comment]
@ddreier Mine is working fine with out the =. I wonder what the difference is. I'm on a dev version of 2.0.6. I'll update and check it out.

**Comment by snipe** [comment]
I think the UI version uses a more AD-friendly syntax, versus the older generic-LDAP one, no?

**Comment by tolleiv** [comment]
Thanks this helped to fix that issue for me too!
