### ISSUE TITLE
Custom Fields with URL support

### ISSUE THREAD

**Issue by diekmanu** [snipe/snipe-it#1681]
I would like to add fields, which link to service or remote mangement pages. Is this hard to implement?

Also it would be great to have some type of placeholders so you can buid an URL without typing the https://computertname:portnumber over and over again.

Thanks!

**Comment by vabue** [comment]
:+1:

**Comment by snipe** [comment]
How exactly would the placeholders work?

**Comment by diekmanu** [comment]
When you add an URL you can once type something like https://{ASSET-NAME}/admin/logon.php.
{ASSET-NAME} will be referenced or translated by the actual (DNS-) name you set under "Asset Name" in the creation process. Of course all the other fields should be addressable too.The magic happens, when you clone this asset and {ASSET-NAME} gets expanded to the new DNS-/Asset-Name.

Something like Keepass' implementation:
http://keepass.info/help/base/placeholders.html

**Comment by vabue** [comment]
It is important that reference in placeholder can be any custom field and any regular field.

**Comment by GS719** [comment]
Hi,
would be really nice to have this feature. Makes it easy to link other SaaS without the use of an API

**Comment by abvmoose** [comment]
Hi,

I would very much like this feature as well. Is this or something similar to this available in Snipe at the moment?
The closest I've gotten to it is the URL type in custom fields but this Placeholder thing sounds great.

**Comment by SteveMCIW** [comment]
Would be a great addition - could easily link straight to our monitoring platform for that device.

**Comment by mtettke123** [comment]
wonder why this is closed. Looking for a way to include an URL to my DMS like "https://always-the-same-url-to-DMS/search?string=${order_number}" ideally directly beneath the field with the order number. Would be so great!
