### ISSUE TITLE
Too easy to remove custom field in 2.10

### ISSUE THREAD

**Issue by vabue** [snipe/snipe-it#1682]
Just press "delete" button and it's gone. And hundreds of filled fields are gone with it. 

My suggestion - to add confirmation popup "Are you really sure, you want to delete this field?"

**Comment by uberbrady** [comment]
It's *supposed* to only let you delete the field if you don't have it associated with any fieldset.

If the one you deleted was associated with some fieldset, then that's not working right.

That being said, I bet if you are moving around your various custom fields and whatnot and inadvertently leave it unassigned to any fieldset, then you accidentally delete it - that could be awfully destructive. So maybe a prompt there might not be a bad thing.

Is that what happened, or do I have a bug in my logic somewhere?
