### ISSUE TITLE
Asset Images Not Displaying

### ISSUE THREAD

**Issue by dualfever** [snipe/snipe-it#1685]
I have followed the instructions to install snipe-it on XAMPP. 
Everything went well, after configuring and learning whilst doing it.
I ended up with a small hiccup, when I have logged into the system I can upload image no problem but where they are meant to be displayed is just a error box, I noticed the URL is pointing to the wrong place.
The image URL is pointing to
https://127.0.0.1/snipe-it/uploads/assets/WKOWMoP1vihVSdc78n9loIEqP.jpg
when the image is actually located here:
http://127.0.0.1/uploads/assets/WKOWMoP1vihVSdc78n9loIEqP.jpg

My hostname is 'office-pc' and everything else is running fine from http://office-pc

Does something have to be configured to get the images to be displayed? Does anyone know why this might be?

update: this actually occurs on all uploaded images on the site, maybe something needs to be configured in XAMPP under SSL?

**Comment by ddreier** [comment]
Is the `url` setting in <snipe-it>\app\config\production\app.php correct? I don't know this for a fact, but I'd bet that Snipe-IT uses that setting to grab the images.

**Comment by dualfever** [comment]
Found it thanks! although I set the domain correctly, in app.php the url was malformed.
