### ISSUE TITLE
Feature request - Notes not only in assets but in the asset models too

### ISSUE THREAD

**Issue by vabue** [snipe/snipe-it#1686]
Use case:

There is a special printer model with difficult to find drivers and complicated setup procedure. I want not to forget this procedure and driver URL, so write it to the notes of the asset. But it happens that there 10+ of those printers in use, and I have to duplicate notes in every asset or not to use notes and store this information outside of snipe-it.

But if there was special notes field in asset model, contents of which would be displayed in asset model view and in every asset of this model - it would be great.

Desireable asset model notes:
![Alt text](https://monosnap.com/file/FeM9ExEX9V1ZdyP8gHHiEJr0Frzgt7.png)

Displaying these notes in the asset view:
![Alt text](https://monosnap.com/file/LgfYxcXcqd5PDnfecSg4fHI5XANgnX.png)

**Comment by diekmanu** [comment]
Makes sense to me :+1:
