### ISSUE TITLE
Tag docker images with actual version

### ISSUE THREAD

**Issue by pedymaster** [snipe/snipe-it#1688]
Hi,

right now, all your docker images are tagged as 'latest'. This might work well with 'normal' setup, but if you have automated installation process and want to keep the version (until the upgrade/new version is tested on devel and so on) you have a bad luck as you cannot define the concrete version of docker image you want to install.

Would it be possible to tag docker images with the actual version?

**Comment by uberbrady** [comment]
This sounds like a pretty clear and straightforward idea; we really should do this. I'll look in to how to modify our `Dockerfile` or whatever other configuration to allow that to happen.

**Comment by uberbrady** [comment]
Okay, we've finally managed to do this:

As of now we have tags for:

- latest
- develop
- v2.1.2
- v3.0-beta.2

And that will grow over time, as new releases are created, they should automatically be tagged appropriately in Docker Hub.
