### ISSUE TITLE
install in wamp/lamp

### ISSUE THREAD

**Issue by jamhulk** [snipe/snipe-it#169]
Hi Guys,
I have very limited idea in programming, I like the program but I dont how to install this on a machine with LAMP/WAMP installed.

Hope you consider my concern in your next development.

Thank you

**Comment by aamarnath** [comment]
Madd and Snipe, 

Thanks for all your inputs... as slated i have installed WAMP server and as well composer on the snipe-it folder... but no luck i am not able to start the snipe-it home page or configuration page... 

Madd, the link what your have given for configuration does not works as it is been moved... 

Please do help me out....
