### ISSUE TITLE
web is not available in docker implementation

### ISSUE THREAD

**Issue by kabunisaas** [snipe/snipe-it#1691]
I have the same problem; page is not available;
I am using docker over digitalocean.
when I ping [myhostIP] and when I ping my domain . both are working and respond.

I applied below commands:
1) docker run --name snipe-mysql --env-file=/etc/docker.env -d -p [myhostIP]::3306 mysql:5.6
2)without ssl : docker run -d -p [myhostIP]::80 --name="snipeit" --link snipe-mysql:mysql --env-file=/etc/docker.env snipe/snipe-it 
3)  docker port snipeit
Result : 80/tcp -> [myhostIP]:32774
4) docker exec -i -t snipeit php artisan app:install

after creating default user, I have below prompt:

  Step: 2
    Preparing your Application
-------------------------------------
Application key [IAW8ndSDhrBm4S25NTkaTEvHSh90v4y6] set successfully.
                                                                            
  [PDOException]                                                              
  SQLSTATE[HY000] [2003] Can't connect to MySQL server on '172.17.0.2' (113)  
                                                                              
app:install
![screen shot 2016-01-27 at 7 13 39 am](https://cloud.githubusercontent.com/assets/15661443/12617694/a17f8268-c4c5-11e5-9128-a24af481aa48.png)

**Comment by vabue** [comment]
Did you run mysql container before snipe-it container?

**Comment by kabunisaas** [comment]
Yes I run it before snipe-it. they are both up. 
as soon as I run "docker exec -i -t snipeit php artisan app:install" mysql status change from "UP" to "Exited (1) 30 minutes ago"

**Comment by kabunisaas** [comment]
just to add some info, beside all mentioned information: when I run the ip:port in my browser, automatically it reroute to ip:port/auth/signin  with Error code 500
below picture shows it:
![screen shot 2016-01-27 at 11 51 51 pm](https://cloud.githubusercontent.com/assets/15661443/12638367/69de4b14-c551-11e5-8ce0-a97326646747.png)

**Comment by kabunisaas** [comment]
Note: ports are different (in one is 32774 and the other it is 32772) because, I tried several time to run and remove my docker. first picture is for morning, and last picture is for evening after several times try and error. but in all tries , I got the same error.

**Comment by uberbrady** [comment]
Right after running `docker run mysql:5.6` you should be able to see it when doing `docker ps`. If you can't, then that means something is wrong with your MySQL setup. If you do `docker ps -a` and you see that your MySQL container has exited, then that's the issue.

The MySQL container needs to be running for the install procedure to complete.

**Comment by uberbrady** [comment]
Closed due to no response.
