### ISSUE TITLE
List of assets of a model displays deleted assets

### ISSUE THREAD

**Issue by danpospisil** [snipe/snipe-it#1693]
We have deployed Snipe IT v 2.10 to our company and we have noticed that deleted assets are still visible in View Asset Model menu so we are not able to see how many pieces of that model is really deployed in the company. I hope its a bug not a feature :)

**Comment by snipe** [comment]
Can you reproduce this on the demo?

**Comment by danpospisil** [comment]
Yes - select a model, then delete one of the assets in that model, refresh the page with assets and the deleted assets still shows up. 
I tried it on this: 
https://demo.snipeitapp.com/hardware/models/1/view
you can still see asset NNY287958796, but when you click on it, you see it says deleted.
