### ISSUE TITLE
LDAP anonymous Bind

### ISSUE THREAD

**Issue by pjcuadra** [snipe/snipe-it#1694]
I have the case where I use a SSL/TLS certificate and need bind to the LDAP server anonymously, without any bind user nor password. 

I hacked ```app/controllers/AuthController.php``` a little and it's working for me now:

```php
   try {
            if ($connection) {
                // binding to ldap server
                //$ldapbind = ldap_bind($connection, $ldaprdn, $ldappass);
                // Anonymous bind
                $ldapbind = ldap_bind($connection);
                if ( ($results = @ldap_search($connection, $baseDn, $filterQuery)) != false ) {
                    $entry = ldap_first_entry($connection, $results);
                    if ( ($userDn = @ldap_get_dn($connection, $entry)) != false ) {
                        if( ($isBound = ldap_bind($connection, $userDn, $password)) == "true") {
                            return $returnUser ?
                                array_change_key_case(ldap_get_attributes($connection, $entry),CASE_LOWER)
                                : true;
                        }
                    }
                }
            }
        } catch (Exception $e) {
            LOG::error($e->getMessage());
        }
```

**Comment by snipe** [comment]
Your changes will get overwritten the next time you upgrade, if we make any changes to that file.

**Comment by pjcuadra** [comment]
I'm aware of that. Thanks. Are you considering supporting anonymous binding to the LDAP server?

**Comment by snipe** [comment]
It's a pretty unusual use-case, and I would worry that it would encourage less-secure practices by our users, so I'm not sure.

**Comment by asmartin** [comment]
@pjcuadra if I put "anonymous" or another arbitrary string in the `LDAP Bind Username` field and leave `LDAP Bind Password`, I appear to be able to authenticate anonymously without needing the patch (running v3.4)

**Comment by 4nd3r** [comment]
@snipe anonymous access to LDAP server is very common in internal networks

@asmartin thanks for the tip!

**Comment by hidalgo67** [comment]
@pjcuadra I'm using Snipe v3.6.3 build 15 (g1bf34d7) and don’t know where to put your hack. I can’t find app/controllers/AuthController.php
