### ISSUE TITLE
Error 500 when try to checkout accessory 

### ISSUE THREAD

**Issue by tomaszkrzyzanowski** [snipe/snipe-it#1696]
Hi

I found a bug in our snipe-it 2.0.3 
Problem:
Server return 500 http code when try to checkout accessory
Reason:
Database request don't get any data because earlier asset categories are deleted

Example scenario:
Employee A add new accessory and in form add it to category 'Computer Mouse', next other employee B delete category "Computer Mouse" and add own new category "Computer Accessories", next employee A try to checkout new Accessory and get 500 code because SQL query don't get category data from DB. 

After edit asset and add it to "Computer Accessories" category everything work properly. 

I think there are 2 possible solutions:
1. Add exceprion when data are corrupted (something like "we cannot get accesory category from DB, check it) 
2. Constrain firstly rewrite accessories to other categories and now if any accessory not depend on category allow to remove category 

//I don't check newer versions, i don't know when i try to upgrade app 

Kind Regards!

**Comment by snipe** [comment]
This ticket was technically first, but I'm closing this one as the duplicate because the bug report is more thorough on the new one. https://github.com/snipe/snipe-it/issues/1932
