### ISSUE TITLE
LDAP and CSV - Unable to sync/import users.

### ISSUE THREAD

**Issue by ashleyev** [snipe/snipe-it#1699]
We’ve recently updated to v2.1.0 and can’t synchronize LDAP or import via CSV. Before upgrading I was able to import via CSV. Now when I try to do either I get a “Success!” message but the people are not added. Screenshots are attached.

Snipe V2.1
OS: Centos 7.2, Web Server: Apache
Install.sh or manual
Using git to do updates, no errors in console; debug mode is on.
LDAP config screenshot attached
We're using Active Directory

Please let me know if you need any other informaation.

Thanks,
Ashley

![screen shot 2016-01-28 at 12 01 09 pm](https://cloud.githubusercontent.com/assets/16928009/12657177/dd379eac-c5b6-11e5-9d4c-ddafa74bf943.png)

![screen shot 2016-01-26 at 10 11 09 am](https://cloud.githubusercontent.com/assets/16928009/12656963/e0def452-c5b5-11e5-87ab-ca3c9c191b30.png)
![screen shot 2016-01-26 at 10 11 44 am](https://cloud.githubusercontent.com/assets/16928009/12656964/e0e26894-c5b5-11e5-9312-a479b595877d.png)

**Comment by ddreier** [comment]
For the LDAP import, all of the attribute names need to be all lowercase (e.g. samaccountname instead of sAMAccountName). Also, the "LDAP Authentication Query" should be `samaccountname=` for Active Directory, not `uid=`.

**Comment by ddreier** [comment]
CSV import might have changed from the last time I looked at it. I thought there was a page that listed each uploaded CSV file and allowed you to "Process" them. There's also a command line CSV importer : http://docs.snipeitapp.com/manual/importing-assets.html.

**Comment by snipe** [comment]
@ddreier - that was for assets, not people

**Comment by ashleyev** [comment]
I ran the LDAP sync again and had 2 successful imports (we have 500+ employees)
See attached screengrabs. 
The "import errors" shows that 2 users "exists" - I can find Nancy who we added manually but I cant find Ravi when I search.


<img width="914" alt="ldap settings" src="https://cloud.githubusercontent.com/assets/16928009/12662669/e7c6e7ea-c5d6-11e5-8879-27c8efc05579.png">
<img width="1167" alt="import errors" src="https://cloud.githubusercontent.com/assets/16928009/12662673/e9ad8c08-c5d6-11e5-8ceb-21cce24219bc.png">
<img width="1215" alt="successful imports" src="https://cloud.githubusercontent.com/assets/16928009/12662677/edf4cace-c5d6-11e5-8613-5939b95daf01.png">
