### ISSUE TITLE
Adding custom field to fieldset with custom order does not update other fields

### ISSUE THREAD

**Issue by ddreier** [snipe/snipe-it#1701]
v2.1.0-47-g39f40a3
PHP 5.4 on Windows Server 2012 R2 w/ IIS 8.5

I just tried adding an 'out of order' field to an existing fieldset, and the order of the other fields was not updated.

In this example, I added the "Static IP Address" field, and "SCCM Resource ID" was already order number 2.
![image](https://cloud.githubusercontent.com/assets/82290/12660390/28881536-c5d9-11e5-95ea-bb4693c180e5.png)

It doesn't really seem to have broken anything. When editing an asset the fields still show up in the same order that they're listed on the fieldset page.
![image](https://cloud.githubusercontent.com/assets/82290/12660492/96b5df98-c5d9-11e5-9d1b-6fa93950aac7.png)

Live long and prosper.

**Comment by snipe** [comment]
I believe this is fixed in the upcoming v4 release,
