### ISSUE TITLE
Warning: disable Debug mode

### ISSUE THREAD

**Issue by mjaikumar** [snipe/snipe-it#1703]
Hi,

I have installed Snipe IT on my Ubuntu-Mint. It's working fine but the below mentioned errror is coming 

WARNING: This application is running in production mode with debugging enabled. This can expose sensitive data if your application is accessible to the outside world. Disable debug mode by setting the debug value app/config/production/app.php to false.

1.) I have added the 'debug' => false, in app.php and reloaded again after that also it's been same warning showing.

Kindly help it out. how can i fix the same ?

Thanks

**Comment by snipe** [comment]
>  I have added the 'debug' => false, in app.php 

Can you tell me exactly what you did, and which file you changed?

**Comment by mjaikumar** [comment]
Hi,

I have used the following link (http://docs.snipeitapp.com/installation/downloading.html) to install snipe it. and everything which i did without any error over installation.

I have change the 'debug' => false, on this location /var/www/snipeit/app/config/app.php

Kindly let me know if i am correct or not ? Need to resolve the same

**Comment by snipe** [comment]
Did you add that to be file, or change an existing variable?

**Comment by snipe** [comment]
*the file

**Comment by mjaikumar** [comment]
I have added this line  **'debug' => false,** only  to /app/config/app.php manually entered and saved

**Comment by Rumblee** [comment]
You are supposed to change it in "app/config/production/app.php", not in app/config/app.php.
If you go to production/app.php, there will already be a line " 'debug'=> true".
(But i'm not an advanced user, so don't take my word for it)

**Comment by snipe** [comment]
Correct. You should never be adding anything to the config files, just changing their value.

**Comment by mjaikumar** [comment]
Thank you! It works now (y)

**Comment by k-boy** [comment]
I am having the same problem, just installed snipeit and debug mode is set to false in app/config/production/app.php but the warning still appears.

Snipe-IT version 	v2.1.0-8-g1b1a733
