### ISSUE TITLE
Requested assets in location is not showing

### ISSUE THREAD

**Issue by vabue** [snipe/snipe-it#1705]
Found problem which confuses when I try to determine which assets can be in a particular location.

Here we have 52 requested assets in location "Магазин КТС Рівне 1":
![image](https://cloud.githubusercontent.com/assets/670861/12728824/546b0c66-c92c-11e5-8a0f-b13176d9ee5e.png)

But if I open this location - there is no any users with those requested assets:
![image](https://cloud.githubusercontent.com/assets/670861/12728891/a5616ea8-c92c-11e5-8e91-0b3e1abd5383.png)

Sometimes system shows a user, sometimes not. I found this behaviour confusing.

Snipe-It ver. 2.1.0

**Comment by jacp9** [comment]
Hi

I have the same issues which I logged about a week, if not two ago and nobody's got back to me unfortunately. I guess, you'll have to be patient as I am.

https://github.com/snipe/snipe-it/issues/1678

**Comment by snipe** [comment]
@vabue I'm not sure why you're referencing requested assets here. Locations doesn't address whether an asset is requested or not.
