### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by mfullbrook88** [snipe/snipe-it#1706]
Hi All, i had a few issues setting up on windows 2012 but i finally am able to get to 

http://localhost/auth/signin

But what is the login for this page? 

I tried the username and password created in this step php artisan app:install --env=production

but that did not work. What am i doing wrong?

Much appreciated, Thank you

**Comment by snipe** [comment]
The username and password you put in when you set it up via the command line is the login. If you can't remember the login, you can try a forgotten password request to reset it.
