### ISSUE TITLE
No support Traditional Chinese language

### ISSUE THREAD

**Issue by chenboshiun** [snipe/snipe-it#1707]
Hello Snipe-IT:

Snipe-IT currently support various language, like English, Spanish, German, Korean and Brazilian Portuguese....etc

we would like to use Traditional Chinese language, but no support it in snipe-it service.

In the furture, Is there a possibility that support and maintenance Traditional Chinese in snipe-it

thanks. :)

**Comment by snipe** [comment]
https://crowdin.com/project/snipe-it/zh-TW

**Comment by chenboshiun** [comment]
excuse me, that means i have to translate  from English to Traditional Chinese myself or  snipe-it will handle it ?

**Comment by snipe** [comment]
If you want a translation we don't currently provide, you have to translate it yourself, or find someone who will. We do not have a staff of translators to handle translations, and rely on the community to translate for us.

**Comment by chenboshiun** [comment]
OK, so...if i  translate it myself and finished, snipe-it will upgrade to next version ?

**Comment by snipe** [comment]
Yep!

**Comment by chenboshiun** [comment]
thanks you for your answer :)

BTW, in the furture i enable Traditional Chinese in snipe-it service, will not show gibberish issue while export asset reporter csv file formatting ?

because i found  that  CSV file show gibberish if i input Traditional Chinese language in every assets records and export reporter.
