### ISSUE TITLE
Default Asset View

### ISSUE THREAD

**Issue by diekmanu** [snipe/snipe-it#1710]
It would be nice to actually store information regarding selected columns in different views. Currently you login to snipe-it, select the required columns, and are good to go. At least for the day/when the session expires. Next day you have to repeat the whole process of selecting the "right" columns again. This gets frustrating, when you have a lot of custom fields.

**Comment by snipe** [comment]
@diekmanu the selected columns only change when you upgrade, or if you change the view (Ready to Deploy vs Deployed, etc). The cookie is set to last 2 years.
