### ISSUE TITLE
Adding asset with model assigned custom fields causes error

### ISSUE THREAD

**Issue by olivermarshall2** [snipe/snipe-it#1711]
We're running Snipe v2.1.0-8 on Ubuntu. Installed using the install.sh script. 

When we add an asset based on a model that has been assigned a custom field group, we get a debug error. Also, when in the create new asset page, we don't get the custom fields showing after selecting the model. 

This is NOT reproduceable on the demo. It works fine there. 

The install script didn't show any errors when it ran. Any ideas why this might not be working for us?

The debug error is

ErrorException thrown with message "Undefined index: fields"

Stacktrace:
#19 ErrorException in /var/www/snipeit/app/controllers/admin/AssetsController.php:113
#18 Illuminate\Exception\Handler:handleError in /var/www/snipeit/app/controllers/admin/AssetsController.php:113
#17 Controllers\Admin\AssetsController:postCreate in <#unknown>:0
#16 call_user_func_array in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:231
#15 Illuminate\Routing\Controller:callAction in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:93
#14 Illuminate\Routing\ControllerDispatcher:call in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:62
#13 Illuminate\Routing\ControllerDispatcher:dispatch in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php:967
#12 Illuminate\Routing\Router:Illuminate\Routing\{closure} in <#unknown>:0
#11 call_user_func_array in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php:109
#10 Illuminate\Routing\Route:run in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1033
#9 Illuminate\Routing\Router:dispatchToRoute in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1001
#8 Illuminate\Routing\Router:dispatch in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:775
#7 Illuminate\Foundation\Application:dispatch in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:745
#6 Illuminate\Foundation\Application:handle in /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php:34
#5 Barryvdh\Debugbar\Middleware\Stack:handle in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware.php:72
#4 Illuminate\Session\Middleware:handle in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php:47
#3 Illuminate\Cookie\Queue:handle in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php:51
#2 Illuminate\Cookie\Guard:handle in /var/www/snipeit/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23
#1 Stack\StackedHttpKernel:handle in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:641
#0 Illuminate\Foundation\Application:run in /var/www/snipeit/public/index.php:49

**Comment by snipe** [comment]
http://docs.snipeitapp.com/getting-help.html

Please tell us if there are any browser errors

**Comment by olivermarshall2** [comment]
Ahh. This actually relates to a git request I was about to post...The error below shows that it is linking to httpS but we use http (non s). As a result the logo, dashboard, and now it would seem the custom fields, don't work. 

GET https://hppc-snipe-ubuntu/uploads/logo.jpg net::ERR_CONNECTION_REFUSED
jquery-latest.js:9631 GET https://hppc-snipe-ubuntu/hardware/models/3/custom_fields?_token=piM4Swz42uuYxiSWJpFCXRs34k01O5VTWY0TQzs5 net::ERR_CONNECTION_REFUSEDsend @ jquery-latest.js:9631jQuery.extend.ajax @ jquery-latest.js:9176jQuery.(anonymous function) @ jquery-latest.js:9322(anonymous function) @ create:641jQuery.event.dispatch @ jquery-latest.js:4641elemData.handle @ jquery-latest.js:4309jQuery.event.trigger @ jquery-latest.js:4550(anonymous function) @ jquery-latest.js:5260jQuery.extend.each @ jquery-latest.js:383jQuery.fn.jQuery.each @ jquery-latest.js:136jQuery.fn.extend.trigger @ jquery-latest.js:5259clazz.triggerChange @ select2.min.js:1067clazz.onSelect @ select2.min.js:2276clazz.selectHighlighted @ select2.min.js:1723(anonymous function) @ select2.min.js:748(anonymous function) @ select2.min.js:651jQuery.event.dispatch @ jquery-latest.js:4641elemData.handle @ jquery-latest.js:4309

**Comment by snipe** [comment]
That's not a bug. You didn't change the url in the app config.

http://docs.snipeitapp.com/installation/configuration.html#application-settings
