### ISSUE TITLE
Cannot send message without a sender address

### ISSUE THREAD

**Issue by olivermarshall2** [snipe/snipe-it#1712]
Hi

We're running Ubuntu 14 server and Snipe v2.1.0-8-g1b1a733. We installed using the install.sh script.

We're trying to get Snipe to send out emails to users. When we click the box "email this user their credentials" we get the below error. 

What's the mechanism for sending emails in Snipe? We don't see any mail settings for SMTP sending and there's nothing I can see in the manual about configuring email as a requirement in PHP or sendmail. 

Error is;

Swift_TransportException thrown with message "Cannot send message without a sender address"

Stacktrace:
#24 Swift_TransportException in /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:162
#23 Swift_Transport_AbstractSmtpTransport:send in /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php:85
#22 Swift_Mailer:send in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:329
#21 Illuminate\Mail\Mailer:sendSwiftMessage in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php:151
#20 Illuminate\Mail\Mailer:send in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:214
#19 Illuminate\Support\Facades\Facade:__callStatic in /var/www/snipeit/app/controllers/admin/UsersController.php:173
#18 Illuminate\Support\Facades\Mail:send in /var/www/snipeit/app/controllers/admin/UsersController.php:173
#17 Controllers\Admin\UsersController:postCreate in <#unknown>:0
#16 call_user_func_array in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:231
#15 Illuminate\Routing\Controller:callAction in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:93
#14 Illuminate\Routing\ControllerDispatcher:call in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:62
#13 Illuminate\Routing\ControllerDispatcher:dispatch in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php:967
#12 Illuminate\Routing\Router:Illuminate\Routing\{closure} in <#unknown>:0
#11 call_user_func_array in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php:109
#10 Illuminate\Routing\Route:run in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1033
#9 Illuminate\Routing\Router:dispatchToRoute in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1001
#8 Illuminate\Routing\Router:dispatch in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:775
#7 Illuminate\Foundation\Application:dispatch in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:745
#6 Illuminate\Foundation\Application:handle in /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php:34
#5 Barryvdh\Debugbar\Middleware\Stack:handle in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware.php:72
#4 Illuminate\Session\Middleware:handle in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php:47
#3 Illuminate\Cookie\Queue:handle in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php:51
#2 Illuminate\Cookie\Guard:handle in /var/www/snipeit/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23
#1 Stack\StackedHttpKernel:handle in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:641
#0 Illuminate\Foundation\Application:run in /var/www/snipeit/public/index.php:49

**Comment by snipe** [comment]
http://docs.snipeitapp.com/installation/configuration.html#edit-mail-settings
