### ISSUE TITLE
MethodNotAllowedHttpException

### ISSUE THREAD

**Issue by olivermarshall2** [snipe/snipe-it#1713]
Hi

We running v2.1.0-8 on Ubuntu 14 Server LTS. We used the install.sh script to install. 

When we try to delete a deleted user from the deleted user page we get the error below. It doesn't seem to matter whether they have assets checked out or not. 

Olly

Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException thrown with message ""

Stacktrace:
#14 Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:210
#13 Illuminate\Routing\RouteCollection:methodNotAllowed in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:197
#12 Illuminate\Routing\RouteCollection:getOtherMethodsRoute in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php:145
#11 Illuminate\Routing\RouteCollection:match in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1054
#10 Illuminate\Routing\Router:findRoute in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1022
#9 Illuminate\Routing\Router:dispatchToRoute in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1001
#8 Illuminate\Routing\Router:dispatch in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:775
#7 Illuminate\Foundation\Application:dispatch in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:745
#6 Illuminate\Foundation\Application:handle in /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php:34
#5 Barryvdh\Debugbar\Middleware\Stack:handle in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware.php:72
#4 Illuminate\Session\Middleware:handle in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php:47
#3 Illuminate\Cookie\Queue:handle in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php:51
#2 Illuminate\Cookie\Guard:handle in /var/www/snipeit/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23
#1 Stack\StackedHttpKernel:handle in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:641
#0 Illuminate\Foundation\Application:run in /var/www/snipeit/public/index.php:49

**Comment by snipe** [comment]
If you're already looking at the deleted user page, you can't delete them any harder. The delete button has been removed from that page for future releases, since it was a bug for it to be there in the first place.

**Comment by olivermarshall2** [comment]
We still have the bulk delete drop down as an option, which is what we are using. 

That being the case, we have a user on the system who has left, we have deleted their account. However we want to re-assign the email address used to a new user (we use email addresses based on job role). We can't re-use the email address as it's in use by the deleted user....but they are deleted.

Make sense?

A "purge" function in the backend might be useful.

Olly
