### ISSUE TITLE
Editing checkin email template

### ISSUE THREAD

**Issue by olivermarshall2** [snipe/snipe-it#1715]
Hi

Is it possible to edit the email that is sent to an end user when they check in or check out a device? We want to add a disclaimer to each email along with standard legal company information. 

Olly

**Comment by littlekulamonster77** [comment]
We would like this as well. There are some grammatical errors that are in the Check out email as well.

**Comment by snipe** [comment]
@olivermarshall2 Disclaimers would typically be added via the EULA option. No need to edit the template. 

@littlekulamonster77 that typo fix is being pushed out now. :)
