### ISSUE TITLE
Error in CLI Installation step

### ISSUE THREAD

**Issue by mpod555** [snipe/snipe-it#1717]
Dear Dude,

I try to install snipe IT in windows server 2008 64 bit not using xampp, but using seperate apache, mysql, php. I got error in the CLI installation step.

`[ErrorException]
file_put_contents(D:\apache\htdocs\itam\app/config/app): failed to open app:install`

What should I do, is there any problem about the file path configuration?

Thank you.

**Comment by snipe** [comment]
What directory are you running the `php artisan app:install` command in?  Can you show me the entire command with the output?

PS - Not a dude.

**Comment by mpod555** [comment]
Here it is : 
I run in the itam directory, right click, use composer here.
1. D:\apache\htdocs\itam>
I change default folder name to "itam"

2. And I've used virtual host configuration 
`<VirtualHost *:80>
     ServerName itam.pthsi.co.id
     DocumentRoot d:/apache/htdocs/itam/public
<VirtualHost>`

3. app.php : 
`' url ' => 'https://itam.pthsi.co.id',`
`'domain' => 'pthsi.co.id'`

**Comment by snipe** [comment]
Do you get any errors when you run composer install?

**Comment by mpod555** [comment]
Nope, I have some wrong when install because forget to follow instructions, but when I follow the documentation and some community problems solving it, this installation run smoothly, until this one.

**Comment by snipe** [comment]
Can you show me the entire command with the output, as I asked for before?

**Comment by mpod555** [comment]
Nope, I have some wrong when install because forget to follow instructions, but when I follow the documentation and some community problems solving it, this installation run smoothly, until this one.

**Comment by brianjking** [comment]
[OFF-TOPIC]

_All I can say is...wow._ :facepunch: 

![douchebag](https://cloud.githubusercontent.com/assets/6786817/12848088/446b18d4-cbdd-11e5-82cd-ba2aaec0f53e.gif)
