### ISSUE TITLE
Incorrect Column Headings

### ISSUE THREAD

**Issue by Canceltodebug** [snipe/snipe-it#1719]
Some headings are corrupt.
Please see attached.
![1](https://cloud.githubusercontent.com/assets/16987693/12825240/3b2ca21c-cb6d-11e5-863e-adeaa831a1ca.png)
![2](https://cloud.githubusercontent.com/assets/16987693/12825241/407347bc-cb6d-11e5-87c5-8ae024440dcb.png)
Can I fix these myself somehow?

**Comment by snipe** [comment]
It looks like you're missing some of the language files. I would download Snipe-IT again, and copy over everything in `app/lang/en` into your current install's `app/lang/en` directory.

**Comment by Canceltodebug** [comment]
Hi Snipe,
Redownloading and replacing has not worked but changing the language from en-GB to en has resolved this issue.
Cheers
