### ISSUE TITLE
Companies  ???

### ISSUE THREAD

**Issue by sysnoo** [snipe/snipe-it#1720]
Hi, 
I am using the last stable release 2.1.0.
I want to use company features  but I am not sure how to deal with that, the use case and the purpose.
Any rapid explanation is welcome

Thanks

**Comment by abdullahalasham** [comment]
+1

**Comment by vabue** [comment]
IMHO the main use case is for companies which supply outsourcing services of supporting IT hardware. 
They can document in Snipe-it hardware, licenses, maintenances and so on for their customers.

**Comment by snipe** [comment]
@vabue is correct. With full company support, regular admins cannot access assets, etc that have been assigned to other companies.
