### ISSUE TITLE
Error from LDAP Server:Bad search filter

### ISSUE THREAD

**Issue by olivermarshall2** [snipe/snipe-it#1723]
Hi

Ubuntu running Snipe 2.1.0-8-g1b1a733. 

I have a query that works in our LDAP query tool but errors with the error "Error from LDAP Server:Bad search filter" when used in Snipe.

The query is;

(&(objectCategory=person)(objectClass=user)(!userAccountControl:1.2.840.113556.1.4.803:=2)(|(cn=a*)(cn=b*)))

That is, only users who aren't disabled and where their common name starts with a or b.

Any ideas why this wouldn't work in Snipe but would work in a standard LDAP query? I've tried it in our faithful ldap query tool and also dropped it in to a powershell script as well. 

Olly

**Comment by olivermarshall2** [comment]
It appears to be the bit operand....

(!userAccountControl:1.2.840.113556.1.4.803:=2)

If I remove that the query works. Could it be that the ! or the : aren't being escaped?

**Comment by ddreier** [comment]
I have that exact bit in my query. The issue probably has something to do with Snipe-IT adding the outermost parenthesis for you. Try removing those.

**Comment by olivermarshall2** [comment]
Tried that. Still errors;

If I enter the following then I get an error trying an import.

&(objectCategory=person)(objectClass=user)(!userAccountControl:1.2.840.113556.1.4.803:=2)(|(cn=x*)(cn=y*))

Below is my working query which I am currently using and which doesn't
cause an error, but imports disabled users.

&(objectCategory=person)(objectClass=user)(|(cn=x*)(cn=y*))

**Comment by ddreier** [comment]
Checked my filter, and you need an extra set of parenthesis in between the ! and the userAccountControl part. Like so:
````
(!(userAccountControl:1.2.840.113556.1.4.803:=2))
````

**Comment by olivermarshall2** [comment]
Well I'll be. Thanks for that.

In my defense I've been trying it without those brackets and it works fine
in our usual tools here.

Olly

**Comment by ddreier** [comment]
Please close the issue if this is resolved. :)
