### ISSUE TITLE
Request: Checkin reminder email

### ISSUE THREAD

**Issue by olivermarshall2** [snipe/snipe-it#1725]
Hi

I'd like to see an email sent out to end users when the device that they have checked out reaches it's proposed check in date. In this way the users would get a nudge to bring back devices rather than us having to run a report each day and chase users. 

Olly

**Comment by faxesystem** [comment]
I would also really like to see this feature, since we often give out monitors or external hdd. Right now we have a calendar for this but everything is easier with automation ;)

Greetings,

Henry
