### ISSUE TITLE
import issues

### ISSUE THREAD

**Issue by KuddelD** [snipe/snipe-it#1729]
Hello,

I'm testing Snipe-IT v2.1.0-8 (production with install.sh method) on a CentOS 7.3 VM.
When trying to import assets via csv I hit some problems.

- When exporting from source the csv delimiter is a semicolon. The import expects a comma. It would be great if one could choose the delimiter.

- The import accepts no "Umlaut". Assets which contain an "Umlaut" (special characters i.e. german "ö", "ä", "ü") won't get imported. It would be great, if the import feature would support utf8.

Would it possible to add a parameter to the "install.sh" script which let you choose just production or testing or docker so as not to download everything?

Thanks.

**Comment by merid14** [comment]
> Would it possible to add a parameter to the "install.sh" script which let you choose just production or testing or docker so as not to download everything?

What do you mean by not download everything?
