### ISSUE TITLE
Request: Asset status type options

### ISSUE THREAD

**Issue by olivermarshall2** [snipe/snipe-it#1731]
What we've found is that Snipe is really good for tracking devices given to people, where you checkin and checkout. However it doesn't seem to be so rich at tracking static items where a device might be installed, such as a wireless access point, PCs in an IT Suite etc.

What would be good is to be able to add Asset Status Types in the settings so that we can create one for "Installed". 

This could then be used to determine which devices were ready to be deployed, deployed (Snipes term for devices checked out to users) and then structurally installed somewhere throughout the office. 

If a device comes back from an office, say an access point, is refurbished, we can then change the status back to Ready for Deployment. 

If there is a way to handle this already I'd love to know.

Olly

**Comment by ddreier** [comment]
You can already create custom "Status Labels" and those can be Undeployable, Archived, Pending, or Deployable.

For example, I created "Server" and "Printer" status labels that are both Undeployable. So setting servers/printers to their respective status prevents them from being checked out. You can also see how the built-in Status Labels work on the Admin -> Status Labels page.

**Comment by olivermarshall2** [comment]
Oh yep. But I'm talking about the Asset Status *type*, so the Undeployable,
Archived, Pending or Deployable.

The only way you can make something as being in-use, or out-in-the-field,
is to check it out to a user. This doesn't work for assets which aren't
assigned to a user, such as WiFi APs, or PCs in a suite, or security
cameras, servers on remote campuses, etc.

So there needs to be a non-user based "in-use-and-not-deployable" type for
fixed assets. Currently we are trying to use the "undeployable" type but
this doesn't really work as we want those devices to show on the deployed
list, as they are, just not as assigned to a user, which they aren't.

Olly

**Comment by ddreier** [comment]
Checkout to location is planned.

For now you can also create users for your locations and check items out to them.

**Comment by olivermarshall2** [comment]
Any idea where on the roadmap location checking out is? Is it over-here, or over-there?

**Comment by ddreier** [comment]
I can't really speak to the timeline. But there is a Pull Request open for some initial work, so probably sooner rather than later.

**Comment by sysnoo** [comment]
The request is interesting if you consider some cases :

**Comment by sysnoo** [comment]
Suppose a Deployed Device but not used or offline, It is interesting to have the possibility to add status "Offline/Inactive". 
Also changing status is not recorded in the history,
Ex> Changing from Ready to deploy to Undeployable is not shown in the timeline. and you can't add reason for this change.
Important information are lost in this case.
