### ISSUE TITLE
issue with load snipeit

### ISSUE THREAD

**Issue by devilsoulblack** [snipe/snipe-it#1732]
i made install snipeit using install.sh but when try to access i get this load page 11snipe.jpg but when click over item i get 404 not found

any idea how to solved

![11snipe](https://cloud.githubusercontent.com/assets/3916283/12861510/ad3cc384-cc42-11e5-8d3e-21f3aa7303f7.jpg)
![22snipe](https://cloud.githubusercontent.com/assets/3916283/12861511/ad663cbe-cc42-11e5-9634-6bc78efd0635.jpg)

**Comment by snipe** [comment]
Public should not be in your URL. It should be your document root.

**Comment by devilsoulblack** [comment]
i solved i enable mod_rewrite
@snipe like that 
![33snipe](https://cloud.githubusercontent.com/assets/3916283/12861838/f7a981f8-cc44-11e5-80cf-85937f7413a0.jpg)

**Comment by snipe** [comment]
Mod rewrite is required (per the installation documentation), but public should still not be in your url.
