### ISSUE TITLE
{ Bug } - Nothing found. Maybe bad data? - in dashboard after uploading files

### ISSUE THREAD

**Issue by abdullahalasham** [snipe/snipe-it#1735]
Hi @snipe ;

indeed after uploading file for users  i got " Nothing found. Maybe bad data  " in dashboard kindly find the below image:
![upload error](https://cloud.githubusercontent.com/assets/15037482/12871018/7af7367e-cd74-11e5-87f7-7a43345c902d.PNG)

thanks in advance

**Comment by snipe** [comment]
That usually means someone has manually deleted information from the database, so its looking for a relationship to other tables that should exist but does not.

**Comment by abdullahalasham** [comment]
but in my case it appears after i upload a file and actually i have not delete any thing , i test it in demo and got the same
![uploadd error](https://cloud.githubusercontent.com/assets/15037482/12939159/62d0ac6e-cfcd-11e5-9def-f989f434dad8.png)

**Comment by abdullahalasham** [comment]
Hi indeed i modified the code to overcome this bug , you might review the code and change it as required and included in the coming version 

![working upload](https://cloud.githubusercontent.com/assets/15037482/13040647/d318a346-d3bf-11e5-80f5-78664bcd2029.PNG)


Hi indeed i modified the code to overcome this bug:

```php
actionlog.php

 public function uploads()
        {
      return $this->hasMany( 'Actionlog', 'filename' );				                    
        }


```
```php

view.blade.php

@elseif (($log->uploads) && ($log->asset_type=="user"))
<i class="fa fa-certificate"></i>



@elseif (($log->uploads) && ($log->asset_type=="user"))
{{{ $log->note }}}


```

```php

dashboard.blade.php

  @elseif (($activity->uploads) && ($activity->asset_type=="user"))
			            	{{{ $activity->note}}}


  @elseif (($activity->uploads) && ($activity->asset_type=="user"))
			           <a href="{{ route('view/user', $activity->checkedout_to) }}">{{{ $activity->checkedout_to}}}</a>

```
```php
UsersController.php
 //Log the deletion of seats to the log
                        $logaction = new Actionlog();
                        $logaction->asset_id = NULL;
                        $logaction->asset_type = 'user';
                        $logaction->user_id = Sentry::getUser()->id;
                        $logaction->note = e(Input::get('notes'));
                        $logaction->checkedout_to = $user->id;
                        $logaction->created_at = date("Y-m-d h:i:s");
                        $logaction->filename = $filename;
                        $log = $logaction->logaction('uploaded');
                    } else {
                        return Redirect::back()->with('error', Lang::get('admin/users/message.upload.invalidfiles'));
                    }

```

**Comment by JarbyDev** [comment]
@snipe i having the same issue as commented by @abdullahalasham, any update, thx
