### ISSUE TITLE
Cant get this working on Windows

### ISSUE THREAD

**Issue by Jabiros** [snipe/snipe-it#1739]
Hi,

I followed all the steps in the manual but I keep getting 

ERR_CONNECTION_CLOSED

Or

ERR_SSL_PROTOCOL_ERROR

Can someone help me with this? 

I am running this on a Windows Server 2008 with ISS. If you need more details, let me know. 

Cheers

**Comment by ddreier** [comment]
You might need to disable the URL Rewrite rule that forwards to HTTPS. It's the only rule that has "https" in it.

**Comment by Jabiros** [comment]
I already did that. This manual is not really n00b friendly. I have never set up a Website on a windows server with IIS. Would you have time to assist with the installation? 

I started again front he beggining and now I have a problem with step 3 of the manual. 

"Right click and select Composer Install. This will install the dependencies."

It gives me 2 problems. Both are: 

  Problem 1
    - Installation request for intervention/image 2.3.x-dev -> satisfiable by in
tervention/image[2.3.x-dev].
    - intervention/image 2.3.x-dev requires ext-fileinfo * -> the requested PHP
extension fileinfo is missing from your system.
  Problem 2
    - Installation request for intervention/image dev-master -> satisfiable by i
ntervention/image[dev-master].
    - intervention/image dev-master requires ext-fileinfo * -> the requested PHP
 extension fileinfo is missing from your system.

  To enable extensions, verify that they are enabled in those .ini files:
    - C:\Program Files\PHP\v7.0\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PH
P in CLI mode.

**Comment by ddreier** [comment]
Did you install PHP Manager in IIS? If so, you can use it to enable the fileinfo extension. Otherwise you'll have to edit your php.ini and enable it in there.

**Comment by Jabiros** [comment]
Hi ddreider,

You said that and it gave me an idea. I check the phpmanager and I saw that php_fileinfo.dll is disabled. So I enabled it and now it installs perfectly! 

Thank you!

**Comment by Jabiros** [comment]
Can I bug you also for step 4? When I run this command: php artisan app:install --env=production

it doesnt do anything. (Maybe that is good?)

When I go to the next step which is: 

php artisan app:install

it also doesn't do anything.

Is this ok?

**Comment by ddreier** [comment]
What do you mean, doesn't do anything? Does it just immediately return to the prompt?

Are you running the command in the snipe-it directory? What happens if you run `php -i`?

**Comment by Jabiros** [comment]
It returns immediately to the prompt yes.

![untitled](https://cloud.githubusercontent.com/assets/13047121/12942113/ad9b9cbc-cfd8-11e5-8a1e-663180248620.png)

**Comment by ddreier** [comment]
I just wanted to know whether or not `php -i` did or did not work.

What do the contents of C:\inetpub\wwwroot\assetdb look like?

**Comment by Jabiros** [comment]
I thinks it's a problem with PHP connecting to the Database. I am not sure I set that part up correctly. When I open the page now I get this error: 

![capture](https://cloud.githubusercontent.com/assets/13047121/12950398/4218a702-d00d-11e5-9819-9e2ff9dd56eb.PNG)

The contents of that folder look like this:

![capture](https://cloud.githubusercontent.com/assets/13047121/12950423/64f11aa2-d00d-11e5-9d44-76673b331be9.PNG)

**Comment by ddreier** [comment]
No, it's very plainly telling you that it's an error with the web.config file in the snipe-it folder.

Delete the web.config file in C:\inetpub\wwwroot\assetdb\public. You might have to delete the Web Site or Application that you created in IIS.

**Comment by Jabiros** [comment]
I already tried both those things. When I rename the web.config file i get this error.

![capture](https://cloud.githubusercontent.com/assets/13047121/12951569/3a6d9bd8-d013-11e5-94e2-e576861a39a8.PNG)

**Comment by pierreboullionit** [comment]
Hi,
http://docs.snipeitapp.com/common-issues.html

You can maybe test the following:

Alternatively, you can try just copying your config files over into app/config/production and just letting it default to production if you don't plan on doing any code development.

Myself gave up on IIS and went with XAMP.

Regards,
