### ISSUE TITLE
Database creation?

### ISSUE THREAD

**Issue by twindaddy44** [snipe/snipe-it#1740]
Admittedly, I've never worked with mysql before, but I went to the Google and learned how to create a database. I am, however, unsure how exactly my database should look in order for Snipe-IT to accept it. Everytime I try to go to my site I keep getting database errors. I've tried looking throughout all the help documentation, but I don't see any instructions specifically for creating the database. 

Do I need to have a certain number of tables? Should my tables have a certain number of columns? Should the columns have specific labels? The error message I'm getting currently is: ErrorException (E_ERROR)
HELP
Trying to get property of non-object (View: /var/www/snipeit/app/views/backend/layouts/default.blade.php) (View: /var/www/snipeit/app/views/backend/layouts/default.blade.php)

I have Snipe-IT installed on Ubuntu server 14.04 with the most recent versions of PHP, MySQL, and Apache. I have tried accessing the site with both Chrome and Firefox and get the same error. 

Thank you in advance for your help.

**Comment by ddreier** [comment]
There's an installation guide in the Snipe-IT documentation. http://docs.snipeitapp.com/

**Comment by twindaddy44** [comment]
Hello and thank you for your quick response. I used that guide when installing the application, but the only reference to database creation I saw said that I'd have to make my own. I've created a database and table and created my own columns, but I've evidently done something in the database wrong somewhere and I'm unsure what.

**Comment by ddreier** [comment]
Have you run `php artisan app:install --env=production` from step 4? That command sets up the database and creates the first user.

**Comment by ddreier** [comment]
Also, you need an empty database. For no application will you create tables and columns yourself.

**Comment by twindaddy44** [comment]
I did run that command. I will run it again. I didn't know what that did. Thanks, again.
