### ISSUE TITLE
Password Policy

### ISSUE THREAD

**Issue by sphere720** [snipe/snipe-it#1742]
This may not be an issue and correct me if it needs to be elsewhere. I'm new. 

We have a certain password policy in our domain and I'm looking to allow the users to use their same password in Snipe-IT. However, it requires at least 10 characters and our policy only requires 8. Is there somewhere I can change the policy in Snipe-IT to only require 8?

We are on a Windows Server 2012 R2 Snipe-IT installation. Thanks in advance for any input.

**Comment by sphere720** [comment]
Or maybe a better question is if I have LDAP enabled and configured, will it pull the user's current password even if it is not the same policy as Snipe-IT's?

My LDAP settings are as follows (with domain & pw replaced generically):

LDAP Settings (optional)

LDAP Integration  		LDAP enabled
LDAP Server 			ldap://servername.domain.com
LDAP SSL certificate validation Allow invalid SSL Certificate

LDAP Bind Username 		user@domain.com
LDAP Bind Password 		bindpassword
Base Bind DN 			OU=CP Employees,DC=domain,DC=com
LDAP Filter 			!(useraccountcontrol:1.2.840.113556.1.4.803:=2)
Username Field 			samaccountname
Last Name 			sn
LDAP First Name 		givenname
LDAP Authentication query 	uid=samaccountname
LDAP Version 			3
LDAP Active Flag 
LDAP Employee Number 
LDAP Email 			mail

**Comment by ddreier** [comment]
Your "LDAP Authentication query" needs to be changed to `samaccountname=`.

I'm able to sign in as an LDAP user with an 8-character password with no problem.

**Comment by sphere720** [comment]
Absolutely excellent!  That worked perfectly. Thank you ddreier!
