### ISSUE TITLE
Invalid input type for username on login page

### ISSUE THREAD

**Issue by rhopfer** [snipe/snipe-it#1750]
There is no type=username for the input element. See:

https://www.w3.org/html/wg/drafts/html/master/semantics.html#the-input-element

 It should be type=text (otherwise password managers will ignore it).

**Comment by snipe** [comment]
It is indeed incorrect, but password managers don't ignore it. I use two of the most popular ones, and neither have a hard time with it.

**Comment by rhopfer** [comment]
Wow, this was fast. Thank you!

**Comment by snipe** [comment]
![baymax-balalala](https://cloud.githubusercontent.com/assets/197404/12973430/29297268-d061-11e5-9a73-ea7e8958995d.gif)
