### ISSUE TITLE
Header colour not changing

### ISSUE THREAD

**Issue by faxesystem** [snipe/snipe-it#1752]
SnipeIT v2.1.0-8
manual install 
Debian 8.3 
Nginx/PHP-FPM, MySQL
**reproducible in the SnipeIT demo**

Although changing the header colour in the settings it seems that just a frame around the header changes the colour.

![snipeheader](https://cloud.githubusercontent.com/assets/17175964/12974493/acb71c72-d0b4-11e5-8489-946a0f6d0a6c.png)

**Comment by snipe** [comment]
Can you tell me what value you entered for header color?

**Comment by snipe** [comment]
<img width="1257" alt="screen shot 2016-02-11 at 12 17 02 pm" src="https://cloud.githubusercontent.com/assets/197404/12989234/67f286ee-d0b9-11e5-94de-82670a337509.png">

**Comment by faxesystem** [comment]
I entered #FF0000. I already found out, that this problem is related to Firefox. So please try it with Firefox 44.0.2.

![firechrome](https://cloud.githubusercontent.com/assets/17175964/12990180/3013d3ea-d109-11e5-8dcb-2f929f4c3bd8.png)

**Comment by faxesystem** [comment]
![Thank You Snipe](https://raw.githubusercontent.com/snipe/animated-gifs/master/thank-you/woman-thank-you.gif)
