### ISSUE TITLE
Import Assets - Incorrect Username Displayed

### ISSUE THREAD

**Issue by Canceltodebug** [snipe/snipe-it#1753]
Having all kinds of trouble with importing assets (some caused by myself).
The particular issue I'm having at the moment is that despite using a valid Username in the CSV file (user exists in the People list) but the import insists on using a difference name for all imported usernames. It also just so happens that this 'substitute' username is the one next to the admin account within the MySQL database. Not sure if this is a clue.

v2.1.0
Windows 2012 R2

**Comment by Canceltodebug** [comment]
As an update, I have created a brand new database and the first upload completes fine with the correct assigned user but subsequent uploads state the incorrect user for all records.

**Comment by Canceltodebug** [comment]
Update - This only happens with the web-based import tool. Command line seems to be working fine.

**Comment by snipe** [comment]
That doesn't really make any sense, since the web-based too invoked the cli one

**Comment by Canceltodebug** [comment]
It is odd as I'm using the same CSV file with both options.
I've managed to upload just over 800 assets through command line with no issues but was getting random results with the web option where it was selecting 1 particular username for all of the various ones in the file.

**Comment by Canceltodebug** [comment]
Will leave this down to possible user error.
