### ISSUE TITLE
Email Not Working

### ISSUE THREAD

**Issue by bradbakerdx** [snipe/snipe-it#1755]
Email for our SnipeIt application doesn't appear to be working. I haven't gotten a single email from the application yet. 

I've reviewed my email settings under /app/config/production/mail.php and everything appears to be right. 

I saw one other user having issues and there was mention of disabling encryption which I did - but that didn't help. Is there some log I can check somewhere that might give me a clue as to why its not working?

Thanks
Brad

**Comment by snipe** [comment]
Please set `pretend` to true in your mail config and tail the log files to see if any errors are output

**Comment by bradbakerdx** [comment]
Are the mail logs stored in /app/storage/logs or somewhere else?

**Comment by snipe** [comment]
That's where they're stored.

**Comment by bradbakerdx** [comment]
What actions should trigger an email? Since I'm not getting them I'm not sure how to even reproduce the issue.

**Comment by snipe** [comment]
I don't understand. If you're not missing emails, how do you know your email isn't working? 

Forgotten password would trigger them.

**Comment by ddreier** [comment]
Requesting an asset also triggers emails.

**Comment by bradbakerdx** [comment]
I guess email *is* working after all - the app just doesn't generate much of any email. 

I've done lots of things in the app like create assets, delete assets, checkout assets, create users, delete users, edit users. I was expecting at least some of those operations to generate some sort of email but I guess not? 

If I use the forget password link I DO get an email. So disregard - sorry about that.

**Comment by closterfield** [comment]
i am not able to configure forget password link ....like till i entered the correct username...  i don't get emails and error message says whoop something is wrong.... wat do i have to configure in this???
