### ISSUE TITLE
Internal server error 500 on asset checkout

### ISSUE THREAD

**Issue by pradeepneelam** [snipe/snipe-it#1757]
Hi Snipe,

I checked the checkbox in asset settings to get the email notification to the user on asset checkout.but i am getting the error internal server error.
I enabled debug and below is the log 
ErrorException (E_ERROR)
HELP
Undefined variable: item_serial (View: C:\xampp\htdocs\evassets\app\views\emails\accept-asset.blade.php)

Please help me out

**Comment by snipe** [comment]
http://docs.snipeitapp.com/getting-help.html

**Comment by padamesh** [comment]
hello der...

can you plz tell me how to install snipe-it from scrach.

i have installed the xampp.. i read the document ion. but i dont know how to run the app from browser.

thanks in advance

**Comment by pradeepneelam** [comment]
Hi Snipe,Same error Internal server error 500 on accessory checkout 
on debug=true this is the error message i am getting Undefined variable: item_serial (View: C:\xampp\htdocs\evassets\app\views\emails\accept-asset.blade.php)

Please help me on this
