### ISSUE TITLE
Generated admin user is not superadmin

### ISSUE THREAD

**Issue by dankeller** [snipe/snipe-it#1759]
Hi,

I'm on version 2.1.0-8. Using admin user that was generated on install, I cannot delete users. Looking at related issues, discovered I needed to be superadmin, but I am not for some reason, and only superadmins can edit permissions. Seem to be in a catch-22.

Can I edit a database entry to fix this?

**Comment by snipe** [comment]
Can you show me the permissions field in the database for the user that was created on install?

**Comment by snipe** [comment]
The generated user is definitely a super-user, based on the code (and based on me having installed it dozens of times for various customers):

from `app/commands/AppCommand.php`, which handles the initial user creation and migrations:

```
// Prepare the user data array.
        $data = array_merge($this->userData, array(
            'activated'   => 1,
            'manager_id'  => NULL,
            'notes'  => 'Generated on install',
            'permissions' => array(
                'admin' => 1,
                'user'  => 1,
                'superuser' => 1,
                'reports' => 1,
            ),
        ));
```

**Comment by dankeller** [comment]
{"admin":1,"user":1}

I did install this back in August, 2015 and have upgraded it a couple times if that matters. I'll update the permissions array and see if that helps.

**Comment by dankeller** [comment]
```{"admin":1,"user":1,"superuser":1,"reports":1}```

That seems to have done the trick. I can now delete users.

**Comment by reidblomquist** [comment]
@snipe is there a way to make PRs against documentation? might be useful to have a note in FAQ about upgrading and dealing with superuser as it didn't exist as of 1.1. easiest path i found was to just create a throw-away superuser as an admin - elevate perms for users who needed it - and threw it away.

**Comment by snipe** [comment]
@reidblomquist you bet - just fork the repo and open your PR against the documentation branch.

**Comment by reidblomquist** [comment]
@snipe let me know if you need me to change anything with that PR

also, thanks for this awesome piece of open source software!

**Comment by mr-gosh** [comment]
we are facing the same problem after an upgrade from 2.1 to 3.4
