### ISSUE TITLE
500 error in Adding Custom field

### ISSUE THREAD

**Issue by churmi** [snipe/snipe-it#1761]
I run into a problem after I installed snipe-it. Everything seemed fine until I started adding custom fields to the assets.  I was then getting a 500 error saying 

SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at' (SQL: ALTER TABLE assets ADD COLUMN (_snipeit_processor TEXT)

After talking with **uberbrady**, he suggested I try to change the asset table structure on the field "create_at" to Now() or whatever the current syntax would be for the DB( I am running MYSQL so mine was "current_timestamp") That didn't work at first but phpmyadmin said it there was an error with "update_at" when I tried to change "create_at". So, I updated both fields in the table to default "current_timestamp" at the sametime and that fix the problem.

I hope this helps someone if they run into the same problem.

**Comment by tmongero** [comment]
@churmi You're receiving this error because of the SQL mode your server is currently running in. I recommend reading the following article to resolve this issue (change your SQL Server modes):

http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html
