### ISSUE TITLE
Bug: Since upgrade to 2.1.0 the notes field is no longer included in searches

### ISSUE THREAD

**Issue by skleinau** [snipe/snipe-it#1762]
Hello,

we did use 2.0.4 before and were really happy to see the custom fields coming. So I did test the upgrade which worked flawless and decided to upgrade our prod instance.

The only issue identified so far is that the notes field is no longer included in the searches. Is this on purpose or as I expect a wrong merge/bug?

If this is only for us the case, what could be the issue (cache/views were cleaned-up)?

Thanks
Stefan

**Comment by snipe** [comment]
Can you reproduce it in the demo?

**Comment by skleinau** [comment]
Hello,

yes I can. I just modified the asset NNY67567775 with notes and try to search for a tag I put in there: DUS-LAP-B1570

No results are displayed as well.

Thanks
Stefan

**Comment by skleinau** [comment]
Hello,

after some time it seems, it is now included again.

Is there something like an indexing after changes that needs to apply?

Thanks
Stefan

**Comment by snipe** [comment]
No, there's no indexing

**Comment by diekmanu** [comment]
Works for me when altering Asset.php
->orWhere('notes','LIKE','%'.$search.'');
replaced by
->orWhere('notes','LIKE','%'.$search.'%');
