### ISSUE TITLE
Unable to access after upgrading to 2.1.0 from 2.0.1 windows IIS

### ISSUE THREAD

**Issue by lokesh-sg** [snipe/snipe-it#1765]
Hi,

I have replaced all files to upgrade from 2.0.1 to 2.1.0 post doing this, composer wants to upgrade his version. I did that, after that PHP wants to upgrade the version as it had vulnerability on open ssl.

Post doing all these and mapped IIS php, now I am unable to access Snipe IT. Crome throws an err_connection_refused.

Tried all possibilities but no luck, do you have any idea.

Thanks,
Lokesh G

**Comment by ddreier** [comment]
Did you (re-)import the .htaccess file into URL Rewrite? If so you'll need to disable the rule that has "https" in it.

**Comment by lokesh-sg** [comment]
Yes, I did that. But no luck, after 2 days of fighting with IIS moved it to WAMP now everything works fine. I notice 8GB of memory is no sufficient for mysqld.

**Comment by ddreier** [comment]
How big is your database? Mine (~150 assets) runs fine in a VM w/ 8GB of RAM running mariaDB and a bunch of other stuff.

**Comment by lokesh-sg** [comment]
My DB has more than 500 Assets when it was in MariaDB everything was fine. Post moving it to WAMP drastic slow.

**Comment by ddreier** [comment]
You can still use MariaDB as the M in WAMP, FWIW.
