### ISSUE TITLE
LDAP import

### ISSUE THREAD

**Issue by ajaeger23** [snipe/snipe-it#1766]
Hello!

So I had the wrong information in my LDAP import and all the people are missing their email addresses.  I corrected this, imported again.  Now it wont add the email addresses to the existing users, though the email addresses are showing correctly in the import screen.  

Any advice?

Much appreciated.

**Comment by swoopdk** [comment]
I believe that the LDAP is purely import and won't update existing users information.

**Comment by snipe** [comment]
This is fixed in the upcoming v3
