### ISSUE TITLE
XSS on user page

### ISSUE THREAD

**Issue by riceo** [snipe/snipe-it#1768]
Hi,

I've just found an XSS hole on v21.0-pre on Users. I tested injecting JS in to the notes field. It is executed on /admin/users. 

(As an aside, sorry... I tested this on demo.snipeitapp.com while evaluating Snipeit for a business. https://demo.snipeitapp.com/admin/users/83/edit is breaking the user list when rendering that record. I couldn't edit/delete the record afterwards, which I found out a little too late.

Opening this ticket as I feel like a bit of a dick for breaking the demo.)

**Comment by snipe** [comment]
Thanks for the heads up - fixed now. Not sure how we missed that. (You're not the dick for breaking our demo, we're the dick for somehow missing that.)
