### ISSUE TITLE
LDAP Authentication failed. 

### ISSUE THREAD

**Issue by leobg** [snipe/snipe-it#1772]
I am trying to get my snipeit installation to talk to active directory server, I was able to do ldap import (got few missing users,etc), but I can't seem to authenticate against the directory. If I try existing user - it works with the password that's locally assigned, but does not accept the password from AD. I get the following log entry in Laravel:
```
[2016-02-16 17:04:37] production.DEBUG: LDAP is enabled. [] []
[2016-02-16 17:04:37] production.DEBUG: Sentry lookup complete [] []
[2016-02-16 17:04:37] production.DEBUG: Local user testing exists in database. Authenticating existing user against LDAP. [] []
[2016-02-16 17:04:37] production.DEBUG: User did not authenticate correctly against LDAP. Local user was not updated. [] []
[2016-02-16 17:04:37] production.DEBUG: Authenticating user against database. [] []
```
If I try with user that has no local password assigned I get extra log entry:
```
[2016-02-16 17:04:37] production.DEBUG: Local authentication: User testing not found [] []

```
I totally realize the issue is likely with my LDAP Authentication Query in settings which currently is 
```
"samaccountname="
```
(which is based on the default hint "uid=" which I changed to samaccountname since this is Windows AD.

Any suggestions?

**Comment by ddreier** [comment]
`samaccountname=` is the correct LDAP Authentication Query. Would you post a screenshot (redacted appropriately) of your LDAP settings?

**Comment by leobg** [comment]
Should there be any quotes, double or single?                                                                                                                                                                                                                                                                                                                                                                                                                                  From:notifications@github.comSent:February 16, 2016 2:09 PMTo:snipe-it@noreply.github.comReply-to:reply@reply.github.comCc:ivanpetrov@yahoo.comSubject:Re: [snipe-it] LDAP Authentication failed.  (#1772)  samaccountname= is the correct LDAP Authentication Query. Would you post a screenshot (redacted appropriately) of your LDAP settings?

—Reply to this email directly or view it on GitHub.

**Comment by ddreier** [comment]
There shouldn't be any quotes in the LDAP Authentication Query.

**Comment by leobg** [comment]
And that was my problem. The pre-filled box has single quotes which tricked me I guess.. Thanks!
