### ISSUE TITLE
Adding Accessories not working

### ISSUE THREAD

**Issue by faxesystem** [snipe/snipe-it#1775]
It is not possible to add accessories. When trying to do it in the demo one gets immediately
logged out of SnipeIT. On my own installation I get the notification, that the accessory has been added but nothig is shown (manual install, SnipeIT v2.1.0-8, Debian GNU/Linux 8.3, Nginx, PHP-FPM).

![bildschirmfoto vom 2016-02-17 10 19 25](https://cloud.githubusercontent.com/assets/17175964/13104944/abc78698-d560-11e5-88a0-9bee29f84398.png)

**Comment by snipe** [comment]
Can you tell me if you're getting any browser-based errors?

**Comment by KennyIT** [comment]
I'm having the same trouble, and I'm getting this error from chrome. 
![accessory](https://cloud.githubusercontent.com/assets/16316116/13359416/22fef5e8-dc82-11e5-9d17-492421372812.png)

**Comment by KennyIT** [comment]
![accessory-2](https://cloud.githubusercontent.com/assets/16316116/13359452/54033d2a-dc82-11e5-9b16-332b2c594758.png)

**Comment by snipe** [comment]
I need error log output. Please enable debugging, per the Getting Help documentation.

**Comment by KennyIT** [comment]
It's not outputting any errors.

![snipeit-4](https://cloud.githubusercontent.com/assets/16316116/13499188/3ba30622-e12b-11e5-9c6f-b30ee99c28a6.png)

**Comment by snipe** [comment]
You need to copy the URL that's showing a 500 error in the screenshot before, and tell me what the error is there, or pull the errors from your app error logs. http://docs.snipeitapp.com/getting-help.html

**Comment by KennyIT** [comment]
[log-apache2handler-2016-03-03.txt](https://github.com/snipe/snipe-it/files/157743/log-apache2handler-2016-03-03.txt)

**Comment by KennyIT** [comment]
![snipeit-5](https://cloud.githubusercontent.com/assets/16316116/13510731/e9a0fc3c-e15f-11e5-998d-d276bc5d29d2.png)

**Comment by snipe** [comment]
Did you manually delete any data from the database?

**Comment by KennyIT** [comment]
No I have not.

**Comment by faxesystem** [comment]
Hi Snipe,

at first sorry for the delay but a was ill.

I updated to (v2.1.0-55) today. The problem is still there.

My browsers debugger is giving me an Internal Server Error 500 for /api/accesories/list as you can see in the screenshots.

![500second](https://cloud.githubusercontent.com/assets/17175964/13807183/2f05e7ce-eb60-11e5-890f-3d1dc11aeed6.png)
![acessorieslist500](https://cloud.githubusercontent.com/assets/17175964/13807206/460dd396-eb60-11e5-8e9a-ac61ed162bdc.png)

**Comment by faxesystem** [comment]
The error for the URL http://snipeit.berlin.native/api/accessories/list?order=asc&limit=100&offset=0 is

ErrorException thrown with message "Trying to get property of non-object"

Stacktrace:
#19 ErrorException in /srv/www/snipeit/app/controllers/admin/AccessoriesController.php:599
#18 Illuminate\Exception\Handler:handleError in /srv/www/snipeit/app/controllers/admin/AccessoriesController.php:599
#17 Controllers\Admin\AccessoriesController:getDatatable in <#unknown>:0
#16 call_user_func_array in /srv/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:231
#15 Illuminate\Routing\Controller:callAction in /srv/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:93
#14 Illuminate\Routing\ControllerDispatcher:call in /srv/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:62
#13 Illuminate\Routing\ControllerDispatcher:dispatch in /srv/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php:967
#12 Illuminate\Routing\Router:Illuminate\Routing\{closure} in <#unknown>:0
#11 call_user_func_array in /srv/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php:109
#10 Illuminate\Routing\Route:run in /srv/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1033
#9 Illuminate\Routing\Router:dispatchToRoute in /srv/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1001
#8 Illuminate\Routing\Router:dispatch in /srv/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:775
#7 Illuminate\Foundation\Application:dispatch in /srv/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:745
#6 Illuminate\Foundation\Application:handle in /srv/www/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php:34
#5 Barryvdh\Debugbar\Middleware\Stack:handle in /srv/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware.php:72
#4 Illuminate\Session\Middleware:handle in /srv/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php:47
#3 Illuminate\Cookie\Queue:handle in /srv/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php:51
#2 Illuminate\Cookie\Guard:handle in /srv/www/snipeit/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23
#1 Stack\StackedHttpKernel:handle in /srv/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:641
#0 Illuminate\Foundation\Application:run in /srv/www/snipeit/public/index.php:49

**Comment by snipe** [comment]
You never answered my question. Did you manually delete any data from the database?

**Comment by faxesystem** [comment]
Nope I did not.

**Comment by snipe** [comment]
That seems unlikely. That error is always related to bad data. 

What's on line 599 of AccessoriesController.php? (and show me the few lines before and the few lines after)

**Comment by faxesystem** [comment]
I just removed the entries that were in there from the Seed the Database option over the webui.

**Comment by snipe** [comment]
If you didn't remove the entries from the asset logs table, that is bad data.

**Comment by snipe** [comment]
http://docs.snipeitapp.com/installation/manually-editing-data.html

**Comment by faxesystem** [comment]
foreach ($accessories as $accessory) {
                $actions = '<nobr><a href="'.route('checkout/accessory', $accessory->id).'" style="margin-right:5px;" class="btn btn-info btn-sm" '.(($accessory->numRemaining() > 0 ) ? '' : ' disabled').'>'.Lang::get('general.checkout').'</a><a href="'.route('update/accessory', $accessory->id).'" class="btn btn-warning btn-sm" style="margin-right:5px;"><i class="fa fa-pencil icon-white"></i></a><a data-html="false" class="btn delete-asset btn-danger btn-sm" data-toggle="modal" href="'.route('delete/accessory', $accessory->id).'" data-content="'.Lang::get('admin/accessories/message.delete.confirm').'" data-title="'.Lang::get('general.delete').' '.htmlspecialchars($accessory->name).'?" onClick="return false;"><i class="fa fa-trash icon-white"></i></a></nobr>';
                $company = $accessory->company;
     
                $rows[] = array(
                    'name'          => link_to('admin/accessories/'.$accessory->id.'/view', $accessory->name),
                    'category'      => link_to('admin/settings/categories/'.$accessory->category->id.'/view', $accessory->category->name),
                    'qty'           => $accessory->qty,
                    'order_number'  => $accessory->order_number,

**Comment by faxesystem** [comment]
Does this help? :)

**Comment by snipe** [comment]
Not really. I don't know which line is 599, but more importantly, if you deleted assets from the assets table to get rid of the seed data, but didn't delete the corresponding entries in the asset_logs table, that's where your problem lies.

**Comment by faxesystem** [comment]
I did not delete any data manually from tables. I deleted them over the webUI. 
![ee](https://cloud.githubusercontent.com/assets/17175964/13811377/99bf03b0-eb75-11e5-9bbc-dfa85d2e776c.png)

**Comment by krazykenny** [comment]
i'm also having the same problem. i deleted the demo data seeded to the database during install. This was done through the website itself not by manually deleting it from the database directly,
i am using mysql to store the database.
I can add assets, but cannot add accessories. There are also 2 accessories listed that doesn't give me any option to delete or edit so how can i fix this?

**Comment by circuitswitch** [comment]
Good Morning,

I just upgraded from 2.04 to 2.1.0 on a Windows 2012R2 system using MariaDB 10.1.13.  Post upgrade I went to add an Accessory and only filled out the starred mandatory fields:  Accessory Name, Accessory Category, QTY.  I received the error 500 web page after I clicked on submit.

I went back and added data to the non-mandatory field Location as well as the mandatory fields.  The data saved and I received no error.  I never had to add Location before and there is no star indicating that it is a mandatory field. Is Location meant to be mandatory now?

**Comment by snipe** [comment]
@circuitswitch need to know what the 500 error was. Location should not be mandatory, and even if it was, it should reshow the form with a missing field indicator, not present a 500 error.

**Comment by circuitswitch** [comment]
Snipe,
Thank-you for responding.  Very timely, I just tried to add an asset and received the same error, with no work around.  Screen shot
![accessory500](https://cloud.githubusercontent.com/assets/17884059/15023432/6ea7ee4e-11fe-11e6-8a0a-6d098b8a393b.jpg)

 attached.

**Comment by circuitswitch** [comment]
@snipe 

Attaching log from app/storage/logs.  Interesting stuff.
[log-cgi-fcgi-2016-05-04.txt](https://github.com/snipe/snipe-it/files/249302/log-cgi-fcgi-2016-05-04.txt)

**Comment by circuitswitch** [comment]
@snipe 
So, I resolved the problem with the asset (temporarily).  I had attempted to use custom fields on the associated model.  I removed the custom fields from the model and then was able to create the asset.  I wondered why I didn't see the custom fields show up anywhere.

**Comment by snipe** [comment]
@circuitswitch This is almost always caused by the url in your `app/config/production/app.php` not matching your actual url.

**Comment by snipe** [comment]
(This is why we ask for the additional information we ask for in the getting help documentation.)

**Comment by circuitswitch** [comment]
@snipe 
Thank-you for you help and patience.  I hope the log file was helpful. I checked the file you mentioned and made a comparison.
1. The URL we use to access the web page is as follows.
http://sniper.cal
  which then changes to
https://sniper.cal/auth/signin
2. The line in app/config/production/app.php reads as follows.
'url' => 'http://sniper.cal',

I suspect I need to provide you with more information. I appreciate your help and will provide whatever you require.

**Comment by snipe** [comment]
Notice the https vs http. If you're running this over SSL, you should change the url to https://sniper.cal. Protocol mismatches in a browser will prevent javascript from loading from the different protocol.

**Comment by circuitswitch** [comment]
@snipe 
I changed
'url' => 'http://sniper.cal',
to
'url' => 'https://sniper.cal',

But that did not fix the issue.

**Comment by snipe** [comment]
Please tell me if there are any browser errors when you load that page, per the getting help docs:
http://docs.snipeitapp.com/getting-help.html

**Comment by circuitswitch** [comment]
@snipe 
Great, I will capture debug and the error console.  What is the best way to capture it?  Shall Print Screen to a JPG and post here?

**Comment by circuitswitch** [comment]
@snipe 
Attached is the screen capture with debug set to true.
![asset500debug](https://cloud.githubusercontent.com/assets/17884059/15030625/568b10b6-1221-11e6-8b0b-b3e8242a609c.jpg)

**Comment by circuitswitch** [comment]
@snipe 
Any feedback on screenshot provided on May 4?

**Comment by qq17854** [comment]
same problem.
run sql query "delete from accessories where location_id is null;"  .
that's work!
