### ISSUE TITLE
EOL shows Purchase date, can we have this resolved ASAP

### ISSUE THREAD

**Issue by lokesh-sg** [snipe/snipe-it#1776]
Hello,

EOL Column shows Purchase date instead of Expires date.

Thanks,
Lokesh

**Comment by snipe** [comment]
http://docs.snipeitapp.com/getting-help.html

**Comment by lokesh-sg** [comment]
I don't see this issue in the common help section. Is it a know issue?

**Comment by snipe** [comment]
Please see the Getting Help documentation and answer the questions on that page.

**Comment by lokesh-sg** [comment]
There is no answer for this. Could you please help.

**Comment by snipe** [comment]
Did you actually look at the link I gave you?

**Comment by lokesh-sg** [comment]
Yes. I looked into that, I did not find answer for my issue. My issue is I am seeing Purchase Date in EOL column in All Assets instead of Expire Date.

**Comment by snipe** [comment]
The link I gave you does not have answers. It has questions. And without your answers to those questions, I cannot help you. 

This link:
http://docs.snipeitapp.com/getting-help.html

Is not the same as this link:
http://docs.snipeitapp.com/common-issues.html

**Comment by lokesh-sg** [comment]
I am sorry, there is no questions to answer in the page http://docs.snipeitapp.com/getting-help.html it has link to create a new issue and chat room.

**Comment by snipe** [comment]
Pulled directly from that page.

<img width="772" alt="screen shot 2016-02-17 at 2 20 41 am" src="https://cloud.githubusercontent.com/assets/197404/13106445/17084da0-d51d-11e5-82ca-f4bc1571a731.png">

**Comment by lokesh-sg** [comment]
Here is my Answers,
-->2.1.0
-->Windows 2012R2, Wamp (Apache)
-->Manual Installation
-->No Error
-->Not Applicable for this issue
-->Not Applicable for this issue
-->No because demo running on v2.1.0-27, my version is 2.1.0
-->Not Applicable for this issue
-->Not Applicable for this issue
-->No

**Comment by snipe** [comment]
Please try to reproduce this on the demo. If it can't be reproduced on the demo, the issue was already fixed, or your data is faulty.

**Comment by lokesh-sg** [comment]
Demo is running higher version and its not a stable version too. I couldn't reproduce it their, is there a way I can get the same version of demo.

**Comment by snipe** [comment]
Demo pulls from the master branch.
