### ISSUE TITLE
Accessories 'Purchase Cost' Shows Four Decimal Spaces ($)

### ISSUE THREAD

**Issue by SylentBobNJ** [snipe/snipe-it#1777]
In the 'table' view of all added Accessories, the Purchase Cost field displays four decimal spaces. Not sure if this is by design.  If so, could it maybe be configurable to reduce to 2 places?

Running v2.1.0-24 on Ubuntu 14.04/Apache. Installed with the script (install.sh). No error and it is reproducible in the demo.

Also, your blog link on [http://docs.snipeitapp.com/index.html] is 404-ing:  http://snipeitapp.com/news/

Thanks for producing this great product!  We're just getting started with it over here, but it really looks like it'll be a good fit for us.

**Comment by snipe** [comment]
This is fixed in v3
