### ISSUE TITLE
Issues while updating from 1.2.7 to 2.1.0

### ISSUE THREAD

**Issue by rnovo-carecloud** [snipe/snipe-it#1778]
I am getting this error running this line :+1: 

php artisan migrate

#### Actual Behavior

sniper@cc-bl-snipe:/var/www/html$ php artisan migrate
PHP Fatal error:  Class 'Schickling\Backup\BackupServiceProvider' not found in /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 157
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'Schickling\\Backup\\BackupServiceProvider' not found","file":"\/var\/www\/html\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/ProviderRepository.php","line":157}}sniper@cc-bl-snipe:/var/www/html$

#### Before posting this issue, confirm/answer the following:
- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
- [ ] I have read [the Getting Help Documentation](http://docs.snipeitapp.com/getting-help.html)

**Comment by snipe** [comment]
Did you run composer install?

**Comment by rnovo-carecloud** [comment]
I did I got this 

sniper@cc-bl-snipe:/var/www/html$ sudo php composer.phar install --no-dev --prefer-source
[sudo] password for sniper:
Warning: This development build of composer is over 60 days old. It is recommended to update it by running "composer.phar self-update" to get the latest version.
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for guzzle/guzzle 3.9.x-dev -> satisfiable by guzzle/guzzle[3.9.x-dev].
    - guzzle/guzzle 3.9.x-dev requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 2
    - Installation request for guzzle/guzzle dev-master -> satisfiable by guzzle/guzzle[dev-master].
    - guzzle/guzzle dev-master requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 3
    - guzzle/guzzle 3.9.x-dev requires ext-curl * -> the requested PHP extension curl is missing from your system.
    - aws/aws-sdk-php 2.8.x-dev requires guzzle/guzzle ~3.7 -> satisfiable by guzzle/guzzle[3.9.x-dev].
    - Installation request for aws/aws-sdk-php 2.8.x-dev -> satisfiable by aws/aws-sdk-php[2.8.x-dev].

sniper@cc-bl-snipe:/var/www/html$

**Comment by snipe** [comment]
" the requested PHP extension curl is missing from your system"

**Comment by rnovo-carecloud** [comment]
ouch.. something like this 

php5-curl ?

**Comment by snipe** [comment]
Yes. Also, don't run composer as root/sudo. It can cause permission problems later.

**Comment by rnovo-carecloud** [comment]
Thanks, it was fixed.
but, the app site can be reached at http://snipeit.local and clicking over the Dashboard redirect to a 404 error , because is  redirecting to http://snipeit.local/snipeit.local . It was not happening before the upgrade. 

Thanks for the fast response.

**Comment by rnovo-carecloud** [comment]
fixed, bad url on the app.php config file. 

Thanks anyways.
