### ISSUE TITLE
users imported with LDAP don't show up 

### ISSUE THREAD

**Issue by bibawa** [snipe/snipe-it#1779]
#### Expected Behavior
All users imported with LDAP should show up in the "assign asset to user" dropdown list
 
#### Actual Behavior
Currently when I run a sync with LDAP all my users shows up and also when I do a resync the users shown up as exists. 
But when I try to checkout an asset to a user not all my users aren't shown in the dropdownlist.

Somethings it happens that after the user has logged in the first time in his user view the user shows up in the checkout list.

**Comment by snipe** [comment]
Do you have a field listed for `active` in your LDAP settings?

**Comment by bibawa** [comment]
Hi, 

It's set like this, Do i miss something ? 

![snipe](https://cloud.githubusercontent.com/assets/17318623/13351481/2622bf84-dc87-11e5-89d6-179337797bbe.png)

**Comment by snipe** [comment]
"But when I try to checkout an asset to a user not all my users aren't shown in the dropdownlist."

Can you look at your users table in the database and tell me if anything stands out as being different between the ones that show up and the ones that don't?

**Comment by bibawa** [comment]
Issue is resolved, it seems that all users that are note showing up are test users that are deleted in snipeit before we take it into production..
So i removed all users with the deleted_add field filled in and re-run an LDAP import and now it is working fine..

Maybe a feature request: if you remove a user in snipeit hard delete it in the database as wel..

with regards
