### ISSUE TITLE
Installer stops at Setting up LAMP

### ISSUE THREAD

**Issue by bc-csagit** [snipe/snipe-it#1780]
#### Expected Behavior

Automated installer completes as expected, and then I can continue the Snipe-IT setup.
#### Actual Behavior

The installer does not progress, and freezes at Setting up LAMP. I installed all the proper pre-requisites following the docs to a T. I am using the automated installer installing the latest version as of 2.18.2016 10:57am EST. I am running Ubuntu 14.04 LTS x64 in a VMware Workstation 12 Pro VM with the latest VMware tools installed.
#### Before posting this issue, confirm/answer the following:
- [can't, haven't installed Snipe-IT yet ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
- [x ] I have read [the Getting Help Documentation](http://docs.snipeitapp.com/getting-help.html)

Installer log [here](http://pastebin.com/6nq4t26a)

**Comment by snipe** [comment]
Can you give us a little more info? Any error output? At what point in the install does it freeze?
