### ISSUE TITLE
Can you add email notifications for when licenses are checked out to users?

### ISSUE THREAD

**Issue by alexdolney** [snipe/snipe-it#1781]
#### Before posting this issue, confirm/answer the following:
- [x ] I have enabled debug mode
- [ x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
- [x ] I have read [the Getting Help Documentation](http://docs.snipeitapp.com/getting-help.html)

**Comment by SK9413** [comment]
Actually is it possible to have email notifications for when any assets are checked out to users??

**Comment by alexdolney** [comment]
That would be a nice feature as well.  In our business we issue licenses for software daily, it gets used and removed from computer.  It would nice to be able to assign the license and then the user get the key to import into the software.

**Comment by alexdolney** [comment]
To email the admins would be nice feature as well.   But would really like the email of licenses to the user to be an option as we issue licenses frequently and the key could get set directly to the user.

**Comment by kpaonline** [comment]
Bump, it would be awesome to have end user notification on checkout and allow them to confirm the assignment.  Confirmation would log the list and leave a timestamp under their user profile and if they reject their asset list it would then send an email to the company help desk or something like that.  Snipe-IT would be the perfect solution with this feature.

**Comment by ddreier** [comment]
@kpaonline at least half of what you're asking for is already implemented. You can, per Category, require user acceptance before checkout. I know that this sends an email to the user requesting that they accept or reject the asset. But I don't know what emails, if any, are sent back to admins. I don't think that the acceptance date is shown in the UI, but it is logged in the database.

**Comment by kpaonline** [comment]
@ddreier I did not see this before, thanks for the help.  The time stamp is recorded so that is good, but the decline is ambiguous.  It appears to unassigned the asset from the user and it shows on the recent activity list, but beyond that an admin wouldn't know to follow up.  Either something more obvious on the dashboard or preferably and email option would be nice.
