### ISSUE TITLE
cannot upload .txt file to asset

### ISSUE THREAD

**Issue by leobg** [snipe/snipe-it#1782]
#### Expected Behavior
allow file upload
#### Actual Behavior
upload is refused due to size or file type. TXT is supposed to be allowed and file is under 10kb.

#### Before posting this issue, confirm/answer the following:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
- [x] I have read [the Getting Help Documentation](http://docs.snipeitapp.com/getting-help.html)

**Comment by snipe** [comment]
I'm unable to reproduce this on the demo.
https://demo.snipeitapp.com/hardware/15/view

<img width="754" alt="screen shot 2016-02-25 at 5 15 58 pm" src="https://cloud.githubusercontent.com/assets/197404/13340219/7eded9ea-dbe3-11e5-8f51-4c8fcbbe5ee0.png">
