### ISSUE TITLE
Can not able to use export feature inside IE8 ?? what to do????

### ISSUE THREAD

**Issue by ChiragDhangar** [snipe/snipe-it#1783]
#### Before posting this issue, confirm/answer the following:
- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
- [ ] I have read [the Getting Help Documentation](http://docs.snipeitapp.com/getting-help.html)

**Comment by snipe** [comment]
Do not post duplicate issues. Update your previous issue with actual useful information, as requested in the getting help documentation which you clearly simply ignored.
