### ISSUE TITLE
User cannot authenticate against Ldap

### ISSUE THREAD

**Issue by lloydie-t** [snipe/snipe-it#1784]
#### Expected Behavior
Existing or new users authenticate against LDAP before using local database to authenticate

#### Actual Behavior
Authenticaing against LDAP always fails regardless if existing user or new user
Importing users using LDAP works fine, so I know that connecting is not a problem
The following is from the LOG file
[2016-02-19 09:10:38] production.DEBUG: Local user lloyd.tomas exists in database. Authenticating existing user against LDAP. [] []
[2016-02-19 09:10:38] production.DEBUG: User did not authenticate correctly against LDAP. Local user was not updated. [] []
[2016-02-19 09:10:38] production.DEBUG: Authenticating user against database. [] []
[2016-02-19 09:10:38] production.DEBUG: Local authentication: User lloyd.tomas not found [] []

Nothing untoward is showing in debug mode
Is there a setting I may have missed?

**Comment by snipe** [comment]
We'd need to see your LDAP settings. Something is misconfigured.

**Comment by lloydie-t** [comment]
Obviously I have slightly changed some of the parameters.
Ldap Server = ldap://10.100.0.10
Allow invalid SSL cert = true
LDAP Bind Username = moodle.ldapuser
LDAP Bind Password = xxxxxx
Base Bind DN = cn=users,dc=staff,dc=bucks,dc=co,dc=uk
LDAP Filter = &(objectClass=user)(cn=*)
Username Field = sn
LDAP First Name = givenname
LDAP Authentication query = uid=samaccountname
LDAP Version = 3
LDAP Active Flag =
LDAP Employee Number =
LDAP Email = mail

Could the issue be something to do with LDAP Authentication query?

**Comment by lloydie-t** [comment]
Fixed! The default LDAP Authentication query setting is a little confusing as it has the following uid=samaccountname when uid= OR LDAP samaccountname= is required.

**Comment by lloydie-t** [comment]
Next problem I need to search more than one Base Bind DN

**Comment by lloydie-t** [comment]
I am not sure where to post a feature request. I have managed to auth against multiple Base Bind DN's, but it requied some code change to the AuthController->ldap at line 41
`$baseDnArray = explode(';', $baseDn);`

And then at Line 58
`foreach ($baseDnArray as $baseDnArray) {                   
                    if ( ($results = @ldap_search($connection, $baseDnArray, $filterQuery)) != false ) {
                        $entry = ldap_first_entry($connection, $results);
                        if ( ($userDn = @ldap_get_dn($connection, $entry)) != false ) {
                            if( ($isBound = ldap_bind($connection, $userDn, $password)) == "true") {
                                return $returnUser ?
                                    array_change_key_case(ldap_get_attributes($connection, $entry),CASE_LOWER)
                                    : true;
                                break;
                            }
                        }
                    }
                }`
I am sure adding Base Bind DN's delimited by ';' has broken the LDAP import feature and therefore the UsersControler->postLDAP will need some work

**Comment by snipe** [comment]
You can create a new issue requesting the multiple Base Bind DNs

**Comment by ddreier** [comment]
FWIW, I think there's already one or more open Issues requesting multiple Base Bind DNs.
