### ISSUE TITLE
Exporting feature that xml csv and many more not working inside ie

### ISSUE THREAD

**Issue by ChiragDhangar** [snipe/snipe-it#1785]
#### Before posting this issue, confirm/answer the following:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
- [x] I have read [the Getting Help Documentation](http://docs.snipeitapp.com/getting-help.html)

**Comment by snipe** [comment]
Yeah, more info is needed. Please see the links above.

**Comment by ChiragDhangar** [comment]
ok
when we use activity report in snipe it 
corner side have download option in any format like csv xml sql and many more..
which is working fine inside crome,mozilla 
but not working with IE8

**Comment by snipe** [comment]
What does "not working" mean? We need more information. Please see the getting help documentation.

**Comment by ChiragDhangar** [comment]
what is your problem...
its dam simple

**Comment by ChiragDhangar** [comment]
https://demo.snipeitapp.com/reports/activity
goto this link
and try to use export features

**Comment by ChiragDhangar** [comment]
in IE8

**Comment by snipe** [comment]
I don't have IE8. Please describe what you're seeing.

**Comment by ChiragDhangar** [comment]
ok
when you click on any format then it open to new tab and show data:application/json;filename=exportData;base64,W3siaGVhZGVyIjpbWyJESUQiLCJETkFNRSIsIkFQUF9OQU1FIiwiQVBQX09XTkVSX05BTUUiLCJEQl9DUkVBVEUiLCJQRVJDRU5UQUdFIl1dLCJkYXRhIjpbWyJEMDAyIiwiTVlTUUwiLCJDTVMiLCJSS19WRVJNQSIsIjEtOS0yMDE1IiwiNzAiXSxbIkQwMDIiLCJNWVNRTCIsIkNNUyIsIlJLX1ZFUk1BIiwiMS05LTIwMTUiLCI3MCJdLFsiRDAwNSIsIk1PTkdPIiwiUlRQIiwiTEtfU0hBUk1BIiwiMS0xMC0yMDE1IiwiNjAiXSxbIkQwMDYiLCJNWVNRTCIsIkVEVUNBVElPTiIsIlJNX1NBTkdWSSIsIjEtMTAtMjAxNSIsIjcwIl0sWyJEMDA3IiwiT1JBQ0xFIiwiTUFSS0VUSU5HIiwiSktfUEFURUwiLCIxLTEwLTIwMTUiLCI3MCJdLFsiRDAwMyIsIk9SQUNMRSIsIlNBTEVTRk9SQ0UiLCJTS19TSEFSTUEiLCIxLTEwLTIwMTUiLCI2MCJdLFsiRDAwNCIsIk9SQUNMRSIsIk1BUktFVElORyIsIkpLX1BBVEVMIiwiMS0xMC0yMDE1IiwiNzAiXSxbIkQwMDgiLCJPUkFDTEUiLCJTQUxFU0ZPUkNFIiwiU0tfU0hBUk1BIiwiMS0xMC0yMDE1IiwiNjAiXSxbIkQwMDkiLCJPUkFDTEUiLCJTQUxFU0ZPUkNFIiwiU0tfU0hBUk1BIiwiMS0xMC0yMDE1IiwiNjAiXSxbIkQwMDEwIiwiT1JBQ0xFIiwiU0FMRVNGT1JDRSIsIlNLX1NIQVJNQSIsIjEtMTAtMjAxNSIsIjYwIl0sWyJEMDAxMSIsIk9SQUNMRSIsIlNBTEVTRk9SQ0UiLCJTS19TSEFSTUEiLCIxLTEwLTIwMTUiLCI2MCJdXX1d. this in url

**Comment by ChiragDhangar** [comment]
i am having IE11

**Comment by snipe** [comment]
Does it actually download a file though? It would be called something like 'untitled' with no file extension

**Comment by ChiragDhangar** [comment]
no download

**Comment by ChiragDhangar** [comment]
it just open other tab

**Comment by ChiragDhangar** [comment]
give me solution 
what to do

**Comment by snipe** [comment]
Use a different browser.

**Comment by snipe** [comment]
We'll look into this issue, but I don't have a solution for you right now.

**Comment by ChiragDhangar** [comment]
ok....but it should work in any browser

**Comment by snipe** [comment]
Yes, it should. As I said, we'll look into it.

**Comment by ChiragDhangar** [comment]
when it get solved..
inform me...

**Comment by snipe** [comment]
We will update the ticket if we are able to resolve the issue.

**Comment by bruce2004x** [comment]
Hi Snipe, thanks. I've been working just for 2 days I already love this tool. It's exactly what I was looking for. Regarding the IE, definetely you should fix it in addition to add export option to PDF. 

Best
