### ISSUE TITLE
Locations List

### ISSUE THREAD

**Issue by Canceltodebug** [snipe/snipe-it#1787]
Having uploaded a large number of assets (with the command line tool) and their users, the locations page is showing them as Ready to Deploy, rather than Assigned.

![image](https://cloud.githubusercontent.com/assets/16987693/13180871/377fe37a-d722-11e5-83c8-affede34a305.png)

#### Before posting this issue, confirm/answer the following:
- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
- [x] I have read [the Getting Help Documentation](http://docs.snipeitapp.com/getting-help.html)

**Comment by Canceltodebug** [comment]
It appears that the whole Locations section is bugged.
Drilling into a location displays the correct people but the assets section lists the incorrect items.

**Comment by abdullahalasham** [comment]
hi i was able to over come the incorrect assets list by changing the locationscontroller.php as following 

```php

 public function getDataViewAssets($locationID)
  {
    $location = Location::find($locationID);
    $count = $location->assets->count();
    $rows = array();
    foreach ($location->assets as $asset) {
        $rows[] = array(
          'name' => link_to('/hardware/'.$asset->id.'/view', $asset->showAssetName()),
          'asset_tag' => $asset->asset_tag,
          'serial' => $asset->serial,
          'model' => $asset->model->name,
        );
    }
    $data = array('total' => $count, 'rows' => $rows);
    return $data;
  }

```

to 

```php

 public function getDataViewAssets($locationID)
  {
    $location = Location::find($locationID);
    $count = $location->assignedassets->count();

    $rows = array();
// changeing the assets to assignedassets resovle the issue of an inconsisstant data
    foreach ($location->assignedassets as $asset) {
        $rows[] = array(
          'name' => link_to('/hardware/'.$asset->id.'/view', $asset->showAssetName()),
          'asset_tag' => $asset->asset_tag,
          'serial' => $asset->serial,
          'model' => $asset->model->name,
		  'user_id' => $asset->assigned_to,


        );
    }

    $data = array('total' => $count, 'rows' => $rows);
    return $data;

  }

```

**Comment by Canceltodebug** [comment]
Fantastic! Thank you for that.
Would be ideal to be able to view the correct totals on the locations page.
It is odd that the actual assets are showing as RTD on this page but not in the assets RTD section on the left hand side.
