### ISSUE TITLE
[Open Discussion] "One Table to Rule Them All" (really "Some Tables to Rule Them Most")

### ISSUE THREAD

**Issue by uberbrady** [snipe/snipe-it#1789]
It strikes me that we have some hierarchy that we could use to reduce some code duplication, and broaden out and make features available to various chunks of the system - for instance, people have been asking for Custom Fields in Licenses or Accessories or Consumables. And sometimes people want to check things out to Locations instead of People.

My proposal - and it's a super-huge one, not easy - would be to use a lot of single-table-inheritance to start making a lot of different chunks of the system inherit and utilize the same tables.

Specifically - 
- Users are Kinda Like Locations (perhaps both inheriting from `checkoutToAble`)
- Assets are Kinda Like Consumables and Kinda Like Accessories and Kinda Like LicenseSeats
- Licenses are Kinda Like Models.

This makes things like the `AssetLogs` table really simple - it's just an association between an asset-like thing and a checkoutableTo thing.

This also means we can share some functionality between Asset-Like-Things - for instance, custom fields get picked up by consumables and accessories for free.

The migration required to transform to this system, if we magically had it already written, would itself be a nightmare. You'd effectively be renumbering every asset, every location, every user, every consumable and accessory, every license. You'd have to completely re-create the assetLogs table based on the old and new associations. Probably the only way to do it would be to have brand new tables for the new 'unified' concepts and then populate them from the old, maybe even building out giant translation tables in the process (or adding 'oldid' to the new stuff, which I'd rather not, or adding 'newid' to the old stuff, which is better since when the old stuff eventually goes away, so does that association).

I'm not sure about the License = Model thing, but if you think about it, a Model joins to a user through an asset, in the same way a License joins to a user through a LicenseSeat (right?). So that's why I would even consider that one. But another problem with this schema is that Licenses wouldn't get custom fields with this solution, and that's something that people have really asked for. (Strictly speaking, a "LicenseSeat" _could_ have a fieldset to fill out, based on the License's theoretical choosing of a fieldset, but I don't know that that makes any sense at all, whatsoever.)

Anyways, I've been pondering this one for a while - you end up with a few more nullable fields in some of the reduced tables, but fewer tables overall. And some of the very high-activity tables (assetLogs) actually will shrink in width, a lot.

**Comment by uberbrady** [comment]
I think a lot of queries get a lot easier, here, too. And that's nice, right?

**Comment by ddreier** [comment]
Something that's been rolling around in my head, and might not really fit into this discussion, is a 'need' to separate the the Asset "Log" out into relationships and a more traditional audit log. Several people recently have been asking for the app to track deleting and editing of items, and that doesn't really seem to fit into the current AssetLog concept.

**Comment by snipe** [comment]
It would though. The action is what determines what the log shows. We just don't currently add a log entry for delete

**Comment by ddreier** [comment]
Ok, fair enough. However my thought also extends to non-asset-type things. Like create/update/delete for users/manufacturers/suppliers/custom field(set)s/etc. 

Anyway, it's just an idea I had and haven't put any serious thought into.

**Comment by sjlaird** [comment]
As you mentioned the software licenses, how about not thinking of software as a license and treating it as an asset. I'm thinking that you already have gears in place for assets (including custom fields) so hopefully that wouldn't mean too much work.

Software is assigned to a user; a license is just one property of that software, along with the version, serial number (maybe), operating system, etc. Licenses often need to be maintained and thus the software has a history which should be tracked.

**Comment by snipe** [comment]
@sjlaird:

> how about not thinking of software as a license and treating it as an asset

That's literally what this thread is about.

> I'm thinking that you already have gears in place for assets (including custom fields) so hopefully that wouldn't mean too much work.

Unfortunately, it requires a huge amount of work. That's why it hasn't been done yet. We'd need to marge the table into one unified table (or keep weird keys all over the place), and set up all of the models to extend other models so that their business logic stays intact. Each of these elements behaves a little differently, that's why they're not all just assets. 

It's likely next of the big things up on the list, but it's a big task that's fraught with peril, so it will take some time.
