### ISSUE TITLE
To remove the footer saying "Snipe IT is a free open source project by @snipeyhead. Fork it | Documentation | Translate It! | Report a Bug     (v2.1.0-13)"

### ISSUE THREAD

**Issue by pradeepneelam** [snipe/snipe-it#1790]
Hi Snipe,

I just want to remove the footer from all the pages,which is saying "Snipe IT is a free open source project by @snipeyhead. Fork it | Documentation | Translate It! | Report a Bug     (v2.1.0-13)"

Can you please help me giving the path of the file to modify.

Thanks in advance

**Comment by zmorrow** [comment]
Can be found here: \snipe-it\app\views\backend\layouts\default.blade.php Lines 450-461, I just commented them out and it works fine.

**Comment by snipe** [comment]
Why are you looking to remove it?

**Comment by varjen** [comment]
This might be cheeky of me, but if you can't find it and remove it yourself, for whatever reason, maybe you should be doing something else? 
One of the pillars of open source is credit where credit is due...

**Comment by pradeepneelam** [comment]
Thanks a ton @zmorrow

**Comment by CalinB** [comment]
That line shouldn't be removed because it contains those useful links to documentation, bug report and also the version info which might be useful someday.

**Comment by snipe** [comment]
Not to mention that your changes will be blown out any time we update that file.

**Comment by kirankumar0505** [comment]
For snipe-it version 5.3.6, where do we want to change the footer. Kindly let us know path.

**Comment by Mindtunnel** [comment]
> For snipe-it version 5.3.6, where do we want to change the footer. Kindly let us know path.

resources/views/layouts/default.blade.php lines 853-891

**Comment by exo3106** [comment]
Give credit where credit is due. But there must be a flexible point where we allow users to customize some features.
If people cant customize, why are we using open source then?

**Comment by snipe** [comment]
@exo3106 Of course you can customize it, but if you change it, you have to release the changes (AGPL license), and keeping it updated with our newer changes is your responsibility. You'll likely end up with merge conflicts, etc that can be a hassle to manage. (Not to mention it seems a little rude to remove attribution for something you get for free.)

**Comment by exo3106** [comment]
Noted, thanks anyways

**Comment by riobijoy** [comment]
But where we can change in version 6.1.2

**Comment by riobijoy** [comment]
> Can be found here: \snipe-it\app\views\backend\layouts\default.blade.php Lines 450-461, I just commented them out and it works fine.
> 

But in version 6.1.2 where it is

**Comment by snipe** [comment]
In the footer code. But again, it’s a bit shit to do that IMHO.  I’m not going to hold your hand to help you remove credit/attribution. You’re welcome to dig around in the source and change what you wish, but upgrading will be more difficult since you will have to keep your changes and take ours (if you want the latest bug fixes and improvements to the software.)

**Comment by snipe** [comment]
If I may ask to both of you on this thread, what’s the reason for wanting to do this in the first place? I’m trying to understand, but years of work went into this, so I just cannot comprehend why anyone working within the AGPL in good faith would want to do this.

**Comment by riobijoy** [comment]
> If I may ask to both of you on this thread, what’s the reason for wanting to do this in the first place? I’m trying to understand, but years of work went into this, so I just cannot comprehend why anyone working within the AGPL in good faith would want to do this. 

I truely agree with you,i am just editing for R&D purpose only.And for your years of work we all are really greatfull to you and other members for such a beautiful concept.

**Comment by elias-krapf** [comment]
> Can be found here: \snipe-it\app\views\backend\layouts\default.blade.php Lines 450-461, I just commented them out and it works fine.

In the latest version you will find the path to the file under:
<webroot>/resources/views/layouts/default.blade.php

**Comment by snipe** [comment]
@f2pkumar Sure, but, like, don't? We're giving you the software for free - removing attribution, while allowed under the AGPL, is kind of a jerk move.

Also please don't reply to very old, closed threads. When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.

**Comment by ghost** [comment]
> [@f2pkumar](https://github.com/f2pkumar) Sure, but, like, don't? We're giving you the software for free - removing attribution, while allowed under the AGPL, is kind of a jerk move.
> 
> Also please don't reply to very old, closed threads. When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.

ok sorry just was for education purposes.
deleted.
