### ISSUE TITLE
Dashboard link redirects to login

### ISSUE THREAD

**Issue by Aaranaw** [snipe/snipe-it#1791]
#### Expected Behavior
Clicking the dashboard like on the far left menu should redirect to the dashboard menu
#### Actual Behavior
Clicking the dashboard like on the far left menu brings the snipe-it login page
I have noticed one you have ran through the additional dashboard login it does not request further login attempts until the browser has been closed.
#### Before posting this issue, confirm/answer the following:
- [X ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
- [X] I have read [the Getting Help Documentation](http://docs.snipeitapp.com/getting-help.html)

**Comment by ddreier** [comment]
I can't think of anything that would cause this other than cookies being disabled. Are your column selections on the asset lists sticking?

**Comment by Aaranaw** [comment]
Yep they are fine.

**Comment by windclockback** [comment]
Hi - Modify  app/views/backend/layouts/default.blade.php            where the source is like this              <img src = "{{Config::get('app.url')}} uploads  to                                                                                      <img src = "{{Config::get(app.url')}}/../../uploads  or    <img src = "{{Config::get('app.url')}}/../uploads  depending on your server configuration.    This occurs on two lines in the source. So you have to change both lines. Cheers

**Comment by ddreier** [comment]
@windclockback just making changes to the app for yourself is counterproductive. If you have a fix for a known problem, everyone else benefits if you submit a pull request.

**Comment by fyberoptik** [comment]
Thanks windclockback, but unfortunately this hasn't resolved the problem. The fix you have mentioned is affecting the IMG tag rather than the link in the A tag.

I can see a cookie in chromes inspector, the session just seems to end after clicking dashboard link:
`{{ Config::get('app.url') }}`

If you I login once again, this problem doesn't seem to repeat itself, pressing the dashboard link just takes you to the dashboard.

**Comment by fyberoptik** [comment]
This fix is a bit of a hack, but resolves the issue by removing the token and replacing it with a slash. Not knowing the snipeit system extensively I'm unsure what is the best way to resolve this issue.

```
        <ul id="dashboard-menu">
			@if(Sentry::getUser()->hasAccess('admin'))
			<li{{ (Request::is('*/') ? ' class="active"><div class="pointer"><div class="arrow"></div><div class="arrow_border"></div></div>' : '>') }}
                <a href="/"><i class="fa fa-dashboard"></i><span>@lang('general.dashboard')</span></a>
            </li>
```

**Comment by windclockback** [comment]
HI  -  Sorry for my part answer yesterday.   I found that placing the entire snipeit folder in the correct directory was step 1.   so it path is /var/www/html/snipeit     also in the file app/config/production/app.php     edit the line to this  'url' => 'http://localhost/snipeit/public/index.php/',         This then breaks the image logo path as described above but corrects the dashboard click issue.

**Comment by snipe** [comment]
Public should not ever be in your URL.

**Comment by windclockback** [comment]
Ok: - I will go with fyberoptik solution.  I wasn't happy with my workaround but will give this a try on my test server. Cheers
