### ISSUE TITLE
Editing Asset Models

### ISSUE THREAD

**Issue by AWHITE89** [snipe/snipe-it#1792]
#### Actual Behavior - When I edit the depreciation field, it won't let me save the Asset Model under the same name, it wants me to create a new name.

We are using their hosted version (v2.1.0-1-g0896ca6). It does indeed work on the demo version, which is running (v2.1.0-35-g0dfa0d9).  We can't enable a debug mode on the service that I know, only if we had downloaded the app and installed it on our own server. I checked the common issues and it's none of those, they seem to also be for the downloadable version, not the hosted version.

#### Before posting this issue, confirm/answer the following:
- [X ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
- [X ] I have read [the Getting Help Documentation](http://docs.snipeitapp.com/getting-help.html)

**Comment by snipe** [comment]
Please address the issues on the Getting Help page. That's why we include the link in every ticket. What version, can you reproduce on the demo, etc.

**Comment by AWHITE89** [comment]
Updated.

**Comment by snipe** [comment]
Thanks for the additional information, @AWHITE89 - have you opened a support ticket? Hosted customers get email support :) If not, drop us an email and we'll get you sorted out today. (Make sure you let us know your sub domain name so we know which is your account)
