### ISSUE TITLE
LDAP not importing all Users

### ISSUE THREAD

**Issue by w1nst3n** [snipe/snipe-it#1793]
#### Expected Behavior
We want to import our Users from LDAP
#### Actual Behavior
LDAP imports most of the users (about 500 out of 600) but not all, some are missing.
When looking at the Users missing and checking if there are any missing Fields etc. theres no difference  to these imported visible.
#### Before posting this issue, confirm/answer the following:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
- [x] I have read [the Getting Help Documentation](http://docs.snipeitapp.com/getting-help.html)

I checked the mySQL Tables, the Users are missing there too so its no visible bug. Also checked log files and nothing really suspicious. I did some checkings in debug-mode too, but Im not  sure where to look at and what logs are important. 

Theres nothing wrong in the LDAP-Settings, its working for most of the Users. 

Snipe-IT is running on Ubuntu Server 14.04.3 LTS and I got the latest release of Snipe-IT.
Everything works well excpect the LDAP Import.

**Comment by snipe** [comment]
I think this might be related to https://github.com/snipe/snipe-it/issues/1714

**Comment by w1nst3n** [comment]
Thanks for the fast reply. For now I'll just import the missing Users via Script.
