### ISSUE TITLE
Request: Custom report 

### ISSUE THREAD

**Issue by jologska69** [snipe/snipe-it#1794]
#### Expected Behavior
checkout asset to user summary
#### Before posting this issue, confirm/answer the following:
- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
- [ ] I have read [the Getting Help Documentation](http://docs.snipeitapp.com/getting-help.html)

**Comment by snipe** [comment]
I have no idea what this means. Can you elaborate please?

**Comment by jologska69** [comment]
![downloadable report per user](https://cloud.githubusercontent.com/assets/17188070/13280456/1a37e344-db19-11e5-8278-84d5ed5411dd.jpg)

is there a way to generate this kind of report.  asset assigned to user/personnel

**Comment by snipe** [comment]
How would that be different than viewing the asset and seeing the users?
