### ISSUE TITLE
"Error in exception handler" after restoring a backup

### ISSUE THREAD

**Issue by jaricharte** [snipe/snipe-it#1795]
#### Expected Behavior

I tried to update to the latest version of Snipe-IT. Backed up my snipe-it folder on IIS and my mysql with HeidiSQL. Run composer install but it failed because my company blocks github downloads.

#### Actual Behavior

I decided to roll back the changes and I would try to get an authorisation to unblock GitHub. Copied back my files to the IIS folder from the backup. Did nothing with the database because I guess it wasn't modified since I got stuck in the very first step (composer install).

My app won't load. It shows: 

> Error in exception handler: The stream or file "C:\inetpub\wwwroot\snipe-it\app\storage/logs/log-cgi-fcgi-2016-02-24.txt" could not be opened: failed to open stream: Permission denied in C:\inetpub\wwwroot\snipe-it\bootstrap\compiled.php:9104

The file "C:\inetpub\wwwroot\snipe-it\app\storage/logs/log-cgi-fcgi-2016-02-24.txt" does not exist.

app\storage has Full Control permissions for IIS_IUSRS

#### Before posting this issue, confirm/answer the following:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
- [x] I have read [the Getting Help Documentation](http://docs.snipeitapp.com/getting-help.html)

**Comment by ddreier** [comment]
What about the permissions on `C:\inetpub\wwwroot\snipe-it\app\storage\logs`? Compare them to http://docs.snipeitapp.com/installation/server/windows.html.

**Comment by jaricharte** [comment]
Thanks, Daniel. That did the trick. I just had "IIS_IUSRS" with Full Control but no "IUSR" as the guide suggests.
