### ISSUE TITLE
CLI Install - The application has fai led to start because its side-by-side configuration is incorrect. 

### ISSUE THREAD

**Issue by ClockAttack** [snipe/snipe-it#1797]
Hello @snipe ,

Someone help me on below.
#### Expected Behavior
OS:  WIndows Server 2008 R2 Standard
DB: MariaDB 10 X64
PHP: V5.6.16
Composer: V3.0
Snipe: V2.1.0
PHP Extensions and Requirements: Enabled - http://docs.snipeitapp.com/requirements.html
Configuration: Done as per http://docs.snipeitapp.com/installation/configuration.html
Dependencies: Installed - http://docs.snipeitapp.com/installation/composer.html
CLI Install: Failed - php artisan app:install --env=production
#### Actual Behavior

Basic usage: composer <command>
For more information just type "composer".

C:\inetpub\wwwroot\snipe-it>php artisan app:install --env=production
=====================================

  Step: 1

    Please follow the following
    instructions to create your
    default user.

-------------------------------------

Please enter your first name: Killer
Please enter your last name: Bird 
Please enter your username: KBird
Please enter your email: Kb@example.com 
**---After entering the email address---**
Password is invalid. Please try again.
Please enter your user password (at least 8 characters): The application has fai
led to start because its side-by-side configuration is incorrect. Please see the
 application event log or use the command-line sxstrace.exe tool for more detail
.

Please confirm your user password: The application has failed to start because i
ts side-by-side configuration is incorrect. Please see the application event log
 or use the command-line sxstrace.exe tool for more detail.

Password is invalid. Please try again.
Please enter your user password (at least 8 characters): The application has fai
led to start because its side-by-side configuration is incorrect. Please see the
 application event log or use the command-line sxstrace.exe tool for more detail
.

Please confirm your user password: The application has failed to start because i
ts side-by-side configuration is incorrect. Please see the application event log
 or use the command-line sxstrace.exe tool for more detail.

Password is invalid. Please try again.
Please enter your user password (at least 8 characters): The application has fai
led to start because its side-by-side configuration is incorrect. Please see the
 application event log or use the command-line sxstrace.exe tool for more detail
.
#### Before posting this issue, confirm/answer the following:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
- [x] I have read [the Getting Help Documentation](http://docs.snipeitapp.com/getting-help.html)

**Comment by snipe** [comment]
"The application has failed to start because its side-by-side configuration is incorrect."

This makes me think you may be missing some dependencies on the server. That's a Windows errors, not anything Snipe-IT would generate.

**Comment by alixo91** [comment]
Folks,

I am getting the same error, triple checked dependecies, still failing.

The following is error

_Activation context generation failed for "C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Symfony\Component\Console\Resources\bin\hiddeninput.exe". Dependent Assembly Microsoft.VC90.CRT,processorArchitecture="x86",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8" could not be found. Please use sxstrace.exe for detailed diagnosis._

**Comment by snipe** [comment]
@alixo91 Please create a new issue, as this issue has been closed and your error message is different than the OPs.
