### ISSUE TITLE
Accessories Are Broken

### ISSUE THREAD

**Issue by SylentBobNJ** [snipe/snipe-it#1799]
#### Expected Behavior
Clicking on 'Accessories' in the left menu should list all Accessories. Clearing the search box after searching should remove the query and show all Accessories.

#### Actual Behavior
The content area shows the 'No results' message until something is searched that exists in the database. Then, the 'No results' message gets replaced with the results of the search, as expected. However, when the search box is cleared or a new search is made against a string that doesn't exist in the database (ie. ijasubd), it will produce the results of the last successful search instead. Clicking on the 'Accessories' link in the left menu will clear the results and produce the 'No Results' message once again.

#### Before posting this issue, confirm/answer the following:
- [ X] I have enabled debug mode

I can provide whatever output you need to diagnose the issue.  I do notice an exception when the search box is cleared:

`    Trying to get property of non-object/var/www/snipeit/app/controllers/admin/AccessoriesController.php#599ErrorException
                $rows[] = array(
                    'name'          => link_to('admin/accessories/'.$accessory->id.'/view', $accessory->name),
                    'category'      => link_to('admin/settings/categories/'.$accessory->category->id.'/view', $accessory->category->name),
                    'qty'           => $accessory->qty,
                    'order_number'  => $accessory->order_number,
                    'location'      => ($accessory->location) ? $accessory->location->name: '',
`
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
- [X] I have read [the Getting Help Documentation](http://docs.snipeitapp.com/getting-help.html)

Thank you!

**Comment by snipe** [comment]
Need to know the version number and whether it's reproducible on the demo, per the getting help docs.

**Comment by SylentBobNJ** [comment]
My apologies: v2.1.0-24-ge5b2163
It does not appear to happen in the demo

**Comment by snipe** [comment]
If it doesn't happen in the demo, that usually means bad data.

**Comment by SylentBobNJ** [comment]
Ok, I found the offending record, though I'm not sure what the issue was with it??  Here it is:
`5,HP Color Laserjet Printer 4700 CP4005 4730 CM4730 Roller Jam Kit Premium,33,80,2,0,2/17/2016 9:39,2/17/2016 12:26,NULL,2,2/16/2016,24.28,115-8326395-6628217,1`

**Comment by snipe** [comment]
This usually happens when you manually delete a location or category from the database. Check to see if the IDs in that record actually have corresponding records in the other tables.
