### ISSUE TITLE
History for User - Asset Column

### ISSUE THREAD

**Issue by Louuu** [snipe/snipe-it#1802]
#### Expected Behavior

When a license has been checked out to a user and you view their profile. Clicking on the License Asset Name should send you to the details for that license.

eg: **https://url/admin/licenses/6/view**

#### Actual Behavior

Clicking on the License Asset Name directs to **https://url/admin/licenses/%7BlicenseId%7D/view** instead of the expected outcome.

#### Before posting this issue, confirm/answer the following:
- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
- [x] I have read [the Getting Help Documentation](http://docs.snipeitapp.com/getting-help.html)

**Comment by ddreier** [comment]
You haven't specified what version you're running.

I can confirm that this is an issue in v2.1.0-8-g1b1a733. But, it appears to be fixed in the develop branch.

**Comment by Louuu** [comment]
The version I am running is v2.1.0-47-g39f40a3
