### ISSUE TITLE
php artisan app:install --env=production - Windows 2008 R2

### ISSUE THREAD

**Issue by Bo5nian** [snipe/snipe-it#1804]
Hello,I am stuck on windows installation.

    Right Click and select Use Composer here
    Type php artisan app:install --env=production and follow the prompts

I am trying to run this command but nothing is happening at all..

not sure what could be wrong.

I installed composer from ti location : **C:\inetpub\wwwroot\snipe-it**

![untitled](https://cloud.githubusercontent.com/assets/17546597/13394774/cef10e08-deea-11e5-96c5-657a208916f1.jpg)

in manual it said: When it asks you if you’re sure you want to run the migrations, type in y. You may have to do this a few **times.**

but i do not see it. any one can help me with this>

**Comment by ddreier** [comment]
Do you get a bunch of output if you run `php -i` in the "Use Composer here" command prompt?

**Comment by Bo5nian** [comment]
Hello,

Yes I do get a lot of output.

![untitled1](https://cloud.githubusercontent.com/assets/17546597/13421380/6262d7fe-df8e-11e5-8104-bce419d88cff.jpg)

**Comment by Bo5nian** [comment]
does anyone have windows install image.. this waiting for any answer is .........

**Comment by ddreier** [comment]
If you want faster support and can't be bothered to set this up yourself you should probably just pay for the hosted option.

What version of PHP did you install? Try running `php artisan app:install --env=production --verbose` and see if there's any output.

**Comment by Bo5nian** [comment]
C:\inetpub\wwwroot\snipe-it>php artisan app:install --env=production --verbose

C:\inetpub\wwwroot\snipe-it>

It doesnt show nothing.  i tried to run from admin account and normal user. same response.

I believe ill decide to try linux setup.

And for your hosted option - I can not run hosted option because i am not allowed to use outside intranet.

**Comment by ddreier** [comment]
You'll probably have an easier time getting Snipe-IT running on Linux.

Does `php artisan migrate` return anything?

**Comment by Bo5nian** [comment]
no.. sorry but it doesnt return anything..

anyhow even on linux.. it has other issue which i do not know what is the problem

![untitled](https://cloud.githubusercontent.com/assets/17546597/13492335/b4ea86ca-e137-11e5-8505-db5ba5bafb24.jpg)

it seem it can not download ?

**Comment by snipe** [comment]
Well, no. It looks like it cannot unzip, based off the error message

**Comment by Bo5nian** [comment]
but it cant be that he can not unzip. command not found.
**is there any other way..**

i mean already setup the all server with mariadb/mysql apache.. and etc.

is it possible to just thru ftp upload the files and go with configuration normal / similar to windows ?

**Comment by snipe** [comment]
`yum install unzip`

**Comment by Bo5nian** [comment]
both are installed.. yum install unzip and yum install zip  and this is screenshot after..

Run:

wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh
chmod 744 install.sh
./install.sh

and that is what i got.
