### ISSUE TITLE
Installation on Kubuntu 15.04

### ISSUE THREAD

**Issue by CaSmWil** [snipe/snipe-it#1806]
#### Before posting this issue, confirm/answer the following:
- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
- [ ] I have read [the Getting Help Documentation](http://docs.snipeitapp.com/getting-help.html)

**Comment by snipe** [comment]
I have no idea what this ticket is reporting or asking, or even whether it's reporting something or asking something.
