### ISSUE TITLE
User denied -  Installation on Kubuntu 15.04

### ISSUE THREAD

**Issue by CaSmWil** [snipe/snipe-it#1807]
Hello,

I have tried to install Snipeit on kubuntu 15.10 and ubuntu  server 14.04 multiple times and i keep getting this message.

ErrorException (E_ERROR)
HELP
SQLSTATE[28000] [1045] Access denied for user 'snipeit'@'localhost' (using password: YES) (View: /var/www/snipeit/app/views/backend/layouts/default.blade.php) (View: /var/www/snipeit/app/views/backend/layouts/default.blade.php)
Open: /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php
	 */
	public function createConnection($dsn, array $config, array $options)
	{
		$username = array_get($config, 'username');
 
		$password = array_get($config, 'password');
 
		return new PDO($dsn, $username, $password, $options);
	}
 
 Snipeit automatically set its account on, why doesn't it not know its password?
![2016-03-01_8-31-17](https://cloud.githubusercontent.com/assets/10981135/13421981/c4913862-df89-11e5-8ec7-5ab3ccb608d6.png)

**Comment by snipe** [comment]
You need to give us more info. How did you install it? What version did you install?

**Comment by sifalios** [comment]
Hi I have the exact same issue I did a manual installation on CentOS Linux release 7.2.1511 (Core), I have double checked that the credentials inside  app/config/production/database.php are correct and I also checked that I can connect to the database with the above credentials from command line
