### ISSUE TITLE
LDAP filter feature request

### ISSUE THREAD

**Issue by lloydie-t** [snipe/snipe-it#1808]
#### Expected Behavior
Use long LDAP filters to import and authenticate specific users.
#### Actual Behavior
Importing users using long LDAP filters fail be cause the database constricts the length of the filter to 255 characters.
#### Before posting this issue, confirm/answer the following:
Is it possible to set the ldap_filter column to be of type text or mediumtext when installing to enable longer strings.

**Comment by snipe** [comment]
This is fixed in the upcoming V3
