### ISSUE TITLE
WAMP Issue

### ISSUE THREAD

**Issue by Jabiros** [snipe/snipe-it#1809]
Hi,

After several attempts on installing this tool with IIS, I decided to try it with WAMP. I seeded the database succesfully. But I still cant get this running. I enabled debug mode for the error's. This is what I am getting.

![image](https://cloud.githubusercontent.com/assets/13047121/13456918/a745ede8-e065-11e5-87e5-d6f16bfa7dc0.png)

I am running on:

Windows server 2008 R2
WAMP (the latest version)

Someone know what is going wrong here?

Thanks

**Comment by snipe** [comment]
http://docs.snipeitapp.com/common-issues.html#error-message-mcrypt_encrypt-key-size-not-supported-by-this-algorithm-only-keys-of-sizes-16-24-or-32-supported

**Comment by Jabiros** [comment]
Hi Snipe,

Thank you for you response. I should have said that I already saw that part. And also I searched through the other issues and I couldnt find a solution. 

First of all it says: " Find the key on line 43". I dont see this. So I am guessing it's the chipher rule on line 45? I put generated a key and put it in there, and I didnt work. 

I dont know, maybe I am doing something wrong or I am looking at the wrong place? The documentation is not so clear. :(

For example: In windows and linux you need to set the premissions for the folders. But for WAMP you dont explain how to do this? And I already checked the video..it doesnt say it there either. 

Cheers
Jabir

**Comment by ddreier** [comment]
@Jabiros it's on line 56 of `app/config/production/app.php`

**Comment by Jabiros** [comment]
Hi ddreider, 

Thank you, that works. So the documentation needs a little bit of updating. But now I am presented with a different error. 

![image](https://cloud.githubusercontent.com/assets/13047121/13488818/c844fc14-e123-11e5-8eb6-3a384a41472a.png)

Any idea?

**Comment by ddreier** [comment]
@Jabiros well, it looks like you're missing at least one database table. How many steps of the documentation have you gone through? Check out this page: http://docs.snipeitapp.com/installation/command-line.html

**Comment by Jabiros** [comment]
I did those steps but probably something went wrong. I mean it asked for my username password email etc. Also asked if it want to seed the database. I said yes. 

I started over. Clean windows installation and everything. Because the previous one had IIS on it. 

I am still having the same problem. It looks like snipe doenst have acces to the database. To my knowledge I did everything the right way. The credentials are in the database.php file. 

What am I missing here?

**Comment by Jabiros** [comment]
When I try to seed the database again it doenst work. 

![image](https://cloud.githubusercontent.com/assets/13047121/13499616/6b43536c-e15f-11e5-811e-cbc6e7706e73.png)

**Comment by ddreier** [comment]
Try running `php artisan migrate`.

**Comment by Jabiros** [comment]
![image](https://cloud.githubusercontent.com/assets/13047121/13501727/16e6c8ae-e168-11e5-8f7f-94fffb2f2597.png)

Doesnt work...

**Comment by ddreier** [comment]
Ok, try it with the verbose flag: `php artisan migrate --verbose`.

Also, what version of PHP did you install?

**Comment by Jabiros** [comment]
Same error. I have PHP 5.6.16 and 7.0.0. But 5.6.16 is activated

**Comment by Jabiros** [comment]
Sorry, I made a mistake.

When it asked if I am sure that i want to run this command I just pressed enter. Thats why it cancelled. Now I did "y"  and then enter. I get this errors.

![image](https://cloud.githubusercontent.com/assets/13047121/13501972/1dbff1b8-e169-11e5-9aef-307c19845c7e.png)

**Comment by Jabiros** [comment]
Same with php artisan migrate

![image](https://cloud.githubusercontent.com/assets/13047121/13501987/388237b8-e169-11e5-8c9c-c1ec8d31de83.png)

**Comment by snipe** [comment]
If you're missing DB tables, you didn't run the command line installer. You have to run `php artisan app:install`

**Comment by Jabiros** [comment]
Hi Snipe,

But I did. Several times. I fill my name etc. It asks if I want to seed the database. I say yes...then I get this:

![image](https://cloud.githubusercontent.com/assets/13047121/13507184/d572f6b2-e181-11e5-949d-c1bf84d397f2.png)

**Comment by snipe** [comment]
You can't run migrations before running the installer. The installer creates the tables. You only run migrations when upgrading.

**Comment by Jabiros** [comment]
I dont know how that got there. But I dropped that table and runned the command again. It created the migrations table again. But this is the error I get now.

![image](https://cloud.githubusercontent.com/assets/13047121/13507528/39cf0730-e183-11e5-9d8d-4e411671350e.png)

**Comment by snipe** [comment]
That's better. Now you're running into this https://github.com/snipe/snipe-it/issues/1509

**Comment by Jabiros** [comment]
I am sorry snipe. I spend the last hour trying to figure out what to do. I did some changes to some files but nothing seems to be working. Could  you please tell me exactly what I need to do?

Thank you

**Comment by snipe** [comment]
You may disable strict mode in one of two ways:

Open your “my.ini” file within the MySQL installation directory, and look for the text “sql-mode”.
Find:

# Set the SQL mode to strict
sql-mode=”STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION”

and change to

# Set the SQL mode to strict
sql-mode=”NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION”

or you can run the following in phpMyAdmin

SET @@global.sql_mode= ”;

**Comment by Jabiros** [comment]
Thank you snipe. NOW, it's working! I did this change in the 

1. C:\wamp64\bin\mysql\mysql5.7.9\my.ini file
2. Empty the database
3. Run the php artisan app:install --env=production again

And it's good now. I can login. 

Again thank you!

**Comment by snipe** [comment]
![thumbs-up](https://cloud.githubusercontent.com/assets/197404/13512028/0d9108ca-e14d-11e5-8103-6aaf95df4b26.gif)

**Comment by Jabiros** [comment]
I am tempted to write a tutorial for this specially for WAMP on windows. As detailed as possible. Are you interested in help?

**Comment by snipe** [comment]
Always interested in help. You're welcome to fork the documentation branch and submit a PR there.
