### ISSUE TITLE
LDAP Feature Suggestions

### ISSUE THREAD

**Issue by DaddyW123** [snipe/snipe-it#1811]
So I'm new to Github, so forgive me if this isn't the proper place to post this.
I've just loaded Snipe-IT in our environment - Love it, but I have a few LDAP suggestions.

- LDAP checkbox in the user entry rather than requiring "LDAP" to be in the notes field.  Even though the note is auto-populated during import.  We may want to use Notes for something else.

- If a user is an LDAP user, remove the option to "Change Password" in the users dropdown window since it checks ldap first and the internal password doesn't matter, this could confuse users.

- In the LDAP configuration settings window, add a scheduled resync of AD.  Other products like Confluence and Jira auto-sync daily by default.  This way if I create a new user in AD today but forget to manually do the sync, they would be able to get into Snipe tomorrow due to the auto-sync.

- upon resync, instead of just having the existing users report as "existing" and ignored, allow it to update the users entries.  Example, I did my initial import before I had added email addresses in AD.  I added an email address to a user in AD, did the sync again and it did not import the change.  The whole point of AD is centralized management.  It's very rare that you are going to want different information in Snipe-IT than you have in AD.  I would think having your LDAP import overwrite/update your existing users should be the norm.

- Add functionality for AD Security Groups.  This would be a more advanced feature, but it could be taken to so many levels.  From basic access like "Snipe-Admins" security group users are automatically made Admins within Snipe.  Or more detailed like make a "Microsoft Office" security group in Active directory and set up rules in Snipe saying "If a user belongs to "Microsoft Office", automatically deploy a license for Office to that user...

I'm sure I could come up with more but that's all I can think of for right now.

Thanks for listening.  Again, great product.  Wish I had this years ago at one of my previous jobs.

**Comment by ddreier** [comment]
All good ideas.

FWIW, your first point isn't entirely relevant with the last couple versions. LDAP auth works roughly like this on login:
* If LDAP is enabled, check the entered credentials against LDAP. Otherwise, proceed as usual.
* If LDAP returns success, set the Snipe-IT user's password to the entered password and sign them in (needed to "trick" the auth library into working with LDAP). If LDAP returns failure, check the entered password against the database and proceed as usual.

**Comment by snipe** [comment]
Most of these suggestions already have open issues around them and are planned or completed for the next few versions.
