### ISSUE TITLE
Incorrect Assets Listed Under Locations

### ISSUE THREAD

**Issue by veen1981** [snipe/snipe-it#1813]
**Centos 7 Server running Snipe-IT ver. 2.1.0-41**

From the "All Assets" tab, asset locations display correctly whether displaying the default location or the location inherited from the user the asset is checked out to. However, when looking at assets based on location from Admin > Locations > Select location, the assets do not match what is actually assigned to the location.

![screenshot1](https://cloud.githubusercontent.com/assets/14188055/13464322/a39e2c20-e05e-11e5-8018-311371eac0d7.JPG)

For example, I have a location set for our secure storage room which holds all our in-stock, unassigned assets. When I go to that location, I should be able to see only the assets that are in that location. Instead the list is very inconsistent and contains checked-out devices, or other devices even if the default location or user location is different.

![screenshot2](https://cloud.githubusercontent.com/assets/14188055/13464473/6496dba2-e05f-11e5-9d72-29715bf2b022.JPG)
Here are 2 assets listed under our secure storage location. Both assets are checked out to users with locations set different than the storage room, and even the default location is different for each device. Yet these devices are listed under an incorrect location.

![screenshot3](https://cloud.githubusercontent.com/assets/14188055/13464635/17e5ecac-e060-11e5-96fc-d4399f04969c.JPG)
Actual default location.

The same issue occurs no matter what location I am looking under. 
#### Before posting this issue, confirm/answer the following:
- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
- [X] I have read [the Getting Help Documentation](http://docs.snipeitapp.com/getting-help.html)

**Comment by xxtheatrainxx** [comment]
I'm having this same issue.

**Comment by PMarkovski** [comment]
Same issue here too.

**Comment by veen1981** [comment]
So far in testing v3 and importing my database from my production server where this is an issue, this appears to be fixed with v3, but would want to wait to verify once v3 is moved to master and I upgrade to v3 on our production server.
