### ISSUE TITLE
When opeining Snip-IT I receive a basic site without artwork

### ISSUE THREAD

**Issue by qcfourie** [snipe/snipe-it#1814]
#### Actual Behavior
When opeining Snip-IT I receive a basic site without artwork
#### Before posting this issue, confirm/answer the following:
- [ X] I have enabled debug mode
- [ X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
- [ X] I have read [the Getting Help Documentation](http://docs.snipeitapp.com/getting-help.html)
![snipeit](https://cloud.githubusercontent.com/assets/17596511/13465124/fdef1a98-e09c-11e5-9d5f-d1c733a74e2d.png)

**Comment by snipe** [comment]
Please report any browser errors you're getting, per the getting help page. Also please check that your URL is set correctly in `app/config/production/app.php`

**Comment by qcfourie** [comment]
Thank you snipe
After changing the URL I now receive this page. Sorry, I's a bit "greek" to me. This was a flesh install without any errors so I was hoping it's a quick fix.
![untitled](https://cloud.githubusercontent.com/assets/17596511/13600452/95d3b038-e531-11e5-96fd-d9d0f8a73a6f.png)
