### ISSUE TITLE
Accepted EULA, Where is it?

### ISSUE THREAD

**Issue by sphere720** [snipe/snipe-it#1816]
This is not really an issue. I just have a question. Where is the actual accepted EULA after the user accepts it?  Could there be a version of this stored somewhere that could be emailed to both the user the supervisor?  My supervisor gave me a EULA he wants used but is asking for a signed version of it to be stored somewhere. Is this possible?

#### Before posting this issue, confirm/answer the following:
- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
- [X] I have read [the Getting Help Documentation](http://docs.snipeitapp.com/getting-help.html)

**Comment by snipe** [comment]
The EULA is set at the category level (or you can use the default one if you set one in the Admin > Settings), so whatever your EULA is for that asset category, that's your EULA for the asset.

**Comment by sphere720** [comment]
@snipe Thanks for the prompt reply. I've learned a lot and troubleshooted quite a bit of my issues just by reading your answers to issues on here. I've said this before; you rock!

I guess my question is where is the actual accepted EULA *after* it is accepted. I have the EULA all set up and that function works great. It shows up in the user's email as expected *before* accepting. But I'm looking for a copy of it that has the user's name and accepted date *after* acceptance. Is this possible?  Or if it is already stored somewhere, then where?

**Comment by snipe** [comment]
We don't store a copy of the EULA as it is currently with the acceptance, no. It's something we can consider adding.

**Comment by sphere720** [comment]
So I should put in a Pull Request?

**Comment by snipe** [comment]
A pull request or a feature request? If you plan on building it, I'd prefer it if you talked through how you were going to build it before opening a PR.

**Comment by sphere720** [comment]
Understood. Thanks.

**Comment by rafaelsanchezsouza** [comment]
Hi! I have a similar question here but, for now, I'm not concerned with getting the copy of the EULA.
I would like to know if it's possible to verify if the EULA were signed. Which of the assets had EULA's accepted by the _user_.

PS. Thanks for the fantastic tool and excelent documentation!

**Comment by jlaggui-lag** [comment]
Id like an update on Rafaels question as well.
