### ISSUE TITLE
Does Snipe IT support barcode Scanner ?

### ISSUE THREAD

**Issue by Beslinda** [snipe/snipe-it#1817]
I started using Snipe IT but I am interested to integrate my barcode scanner to it. 

I want to check in/check out my assets, with a barcode scanner. I was reading all the documentation and I did not see anything like that.

Is it implemented , is any third-party that works with snipe IT to do this ? Are you planning to integrate it in the future?

**Comment by ddreier** [comment]
Snipe-IT does not specifically integrate with any barcode scanning solutions. The app can generate QR codes that contain the URL for the asset which can be scanned with any 2D barcode scanner.

**Comment by Beslinda** [comment]
What does that mean ? I scan the barcode and then ...? What snipe IT does when I scan a barcode with the scanner ?

**Comment by ddreier** [comment]
The QR codes contain a URL like `http://snipeit/hardware/28/view` that, when opened in a web browser, take you to the page for that asset. Snipe-IT itself only generates the barcode.

**Comment by Beslinda** [comment]
Oh thats great. BTW what scanner do you recommend to be used with Snipe IT, and is there documentation how to make this work? I have snipe IT in ubuntu server, I access it in my machine through web browser. So I am not sure how the scanner will open the link ?

Thank you sooo much for your help

P.S I am new to this

**Comment by ddreier** [comment]
I don't really have any specific recommendations, and there isn't any documentation on this (I think). Any 2D barcode scanner or 2D barcode/QR code scanning app should work. I've used the Android/iOS app "inigma" and it works well. Most PC-based barcode scanners just emulate a keyboard, so you'd have to have a web browser open with focus on the address bar.

The only configuration you need to do is enable QR code generation in Admin -> Settings. 
![image](https://cloud.githubusercontent.com/assets/82290/13477190/c6438590-e090-11e5-8028-83e84bf9425e.png)

**Comment by Beslinda** [comment]
Thank you so much.You saved me days of research. I will try to do this.
