### ISSUE TITLE
Feature Request: Allow Consumables Checkout Quantity to be Specified

### ISSUE THREAD

**Issue by naylma01** [snipe/snipe-it#1820]
FEATURE REQUEST
## Not all consumables (like Ethernet cables) are used one at a time.  A higher quantity of cables may be used or checked out.  If that number is significant, using the "Checkout" feature is a daunting task, requiring the user to either checkout many times or just manually edit the on-hand count.

There is no quantity option.  Therefore; a user must click "Checkout" as many times as they need to reflect the quantity of consumable they are taking.

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running 
  v2.1.0-41
- What OS and web server you're running Snipe-IT on 
  CentOS 6.6 / Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) 
  install.sh
- If you're getting an error in your browser, include that error 
  N/A - Feature Request
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
  /admin/consumables
- If a stacktrace is provided in the error, include that too.
  N/A - Feature Request
- Any errors that appear in your browser's error console.
  N/A - Feature Request
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
  Yes
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
  N/A - Feature Request
- Include what you've done so far in the installation, and if you got any error messages along the way.
  N/A - Feature Request
- Indicate whether or not you've manually edited any data directly in the database
  No

**Comment by ScienceNFaith** [comment]
Seems to me like Ethernet Cables and batteries fit under 'Components' rather than 'Consumables'. If you did re-classify them, there is already the option to specify a quantity to check out. The difficult thing becomes who it gets checked out to, 'cause components get checked out to assets instead of users. But hey, maybe that actually fits your use-case. Is the user using the cable, or the asset(computer)? ¯\_(ツ)_/¯
Hopefully this new perspective might offer some help.

**Comment by naylma01** [comment]
I am not checking out Ethernet cables to a device.  I’m checking them out to a technician to be used in a network closet.  The way this is setup now does not let me bulk-checkout consumables, which do not get checked out to devices or end-users.  I honestly don’t care which end user a consumable is checked out for... I want a current on-hand count and I want technicians to check them out.  When the on-hand count goes under X, I need an email or report to order more.  

Maybe this wasn’t the intention of the software, but I’ve never worked anywhere that checks out consumables or components to end-users or assets.  My assets and consumables/components are managed very much independently of one another.  Assigning cables, monitors, mice and keyboards to assets or end-users sounds great, until you manage 3500 workstations in 20 buildings.

**Comment by vexvoltage** [comment]
@snipe Is this request going to be turned into an action item or would this not be something that we could expect any time soon ?

**Comment by thebigmick** [comment]
Has anyone found a better work around for this?  I am in the same boat for cables and other consumables that wont be coming back to me.

**Comment by lilchancep** [comment]
Please...this is the only thing stopping me from using this software.

**Comment by vexvoltage** [comment]
@thebigmick I know you comment is old, but no, I do not think their is any sort of work around, unless you know someone that would be able to help get it coded in and have her push it to the master.

@lilchancep It was for us too, but then we still found the software has so many great features we end up using it anyways and manually doing consumables. It is not efficient in any way but it is what it.

Also as you can see @snipe is out of town on a family emergency so gotta respect their time and space to get everything back to a normal state before working on any sort of development.

**Comment by maverickvarun** [comment]
Hi, I had tried using Snipe-it a few years back. This is a use case for us as well. Will be good to have a feature, where we can check out cables etc to our users.

**Comment by benoithcc** [comment]
+1 I would be very helpfull to checkout several consumables in one click instead of doing the same task 10 or 20 times.

**Comment by wikilike7** [comment]
+1, wish checkout mutiple consumaables one time

**Comment by norulesatall** [comment]
+1, wish checkout mutiple consumaables one time. very much required still

**Comment by vi4869** [comment]
+1, wish checkout consumable with more than one quantity. Very common case.
