### ISSUE TITLE
install.sh error -  date_default_timezone_set(): Timezone ID '' is invalid

### ISSUE THREAD

**Issue by 0xSheepdog** [snipe/snipe-it#1821]
#### Expected Behavior (or desired behavior if a feature request)
install.sh completes without error or warning.

-----

#### Actual Behavior
install.sh shows error but then indicates it is Done!

Screen shot of webpage:
[screenshot on imgur](http://imgur.com/P1M5HBq)

Last several lines of output from install.sh

`   -  Installing symfony/yaml (v2.8.3)`
`      Cloning 2a4ee40acb880c56f29fb1b8886e7ffe94f3b995`
`   -  Installing tecnickcom/tc-lib-color (1.10.0)`
`      Cloning ff40ca244700c18e1d2d5082d8ecc1034cc720c5`
`   -  Installing tecnickcom/tc-lib-barcode (dev-master bf85ed2)`
`      Cloning bf85ed2ab34e1034ec1cb8229d6c4514f186c909`
` Generating autoload files`
` {"error":{"type":"ErrorException","message":"date_default_timezone_set(): Timezone ID '' is invalid","file":"\/var\/www\/html\/snipeit\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/start.php","line":167}}`
`   ***If you want mail capabilities, open /var/www/html/snipeit/app/config/production/mail.php and fill out the attributes***`
`   ***Open http://snipe-it.spde.local to login to Snipe-IT.***`
` ##  Cleaning up...`
` ##  Done!`

-----

#### Please confirm you have done the following before posting your bug report:

- [ can't enable because installation script contains the bug(?) ] I have enabled debug mode
- [ X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v2.1.0

- What OS and web server you're running Snipe-IT on
CentOS Linux release 7.2.1511 (Core)
httpd (x86_64)  ver: 2.4.6  rel: 40.el7.centos

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh
chmod 744 install.sh
./install.sh

- If you're getting an error in your browser, include that error
` ErrorException (E_NOTICE)`
` date_default_timezone_set(): Timezone ID '' is invalid`
[screenshot on imgur](http://imgur.com/P1M5HBq)

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Error occurs during install.sh execution.

- If a stacktrace is provided in the error, include that too.
N/A

- Any errors that appear in your browser's error console.
N/A

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
N/A

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
/var/www/html/snipeit/app/storage/logs is empty.
/var/log/httpd/snipeIT.error.log exists but is zero-bytes
/var/log/httpd/error_log [error_log.txt](https://github.com/snipe/snipe-it/files/158910/error_log.txt)

- Include what you've done so far in the installation, and if you got any error messages along the way.
Looked at files indicated in various error outputs, no changes made.

- Indicate whether or not you've manually edited any data directly in the database
Did not access records/tables/dbs.

**Comment by 0xSheepdog** [comment]
Additional details: system time & date config:
```
[root@snipe-it logs]# timedatectl
      Local time: Fri 2016-03-04 10:19:44 MST
  Universal time: Fri 2016-03-04 17:19:44 UTC
        RTC time: Fri 2016-03-04 17:19:44
       Time zone: America/Denver (MST, -0700)
     NTP enabled: yes
NTP synchronized: yes
 RTC in local TZ: no
      DST active: no
 Last DST change: DST ended at
                  Sun 2015-11-01 01:59:59 MDT
                  Sun 2015-11-01 01:00:00 MST
 Next DST change: DST begins (the clock jumps one hour forward) at
                  Sun 2016-03-13 01:59:59 MST
                  Sun 2016-03-13 03:00:00 MDT
```

**Comment by snipe** [comment]
When you open `app/config/app.php`, what do you see for the value of the timezone key?

**Comment by JPettorino** [comment]
`'timezone' => 'America/Denver',`

**Comment by JPettorino** [comment]
null. that is to say:
`    'timezone' => '',`

**Comment by 0xSheepdog** [comment]
Aw, crap. I replied / cross posted from my work account. Now everyone on the Interwebz knows who I am. #OhThePrivacy!

Anyway...as I said, the value is null:
`  'timezone' => '',`

**Comment by snipe** [comment]
Try changing that to 

`'timezone' => 'America/Denver',`

The installer script *should* have done that for you, but....

**Comment by snipe** [comment]
(And I deleted the other post with your meatspace name... ;) )

**Comment by 0xSheepdog** [comment]
Thanks A! That was what I presumed, but not being a code wrangler I figured if I messed with stuff I'd just make things worse.

**Comment by snipe** [comment]
![hackers-gunslinger](https://cloud.githubusercontent.com/assets/197404/13654615/38548b84-e60e-11e5-9318-c97a6300fcb8.gif)

No worries :D I'm not sure why the installer didn't figure that out for you, but we'll check into it.

**Comment by DawnTan0321** [comment]
I modify the timezone to America/Denver, but it will change to the original value automatically.
