### ISSUE TITLE
v3 feature request - Add Groups column to License Detail view

### ISSUE THREAD

**Issue by jghanlon** [snipe/snipe-it#1822]
#### Desired Behavior (feature request)

Add Groups column to this page: https://v3.snipeitapp.com/admin/licenses/3/view
To the right of the "Assets" column.

---
#### Actual Behavior

No groups column is visible.  And if it is easier, just add a drop-down to enable or view all pertinant columns.
#### Please confirm you have done the following before posting your bug report:
- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running - 2.1.0
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - NO

**Comment by snipe** [comment]
This sounds like more of a case to add department as a field to users. You can have more than one group per user, since they deal with permissions, not necessarily department.
