### ISSUE TITLE
Feature Request - Auto Incrementing Asset Tag

### ISSUE THREAD

**Issue by ideaman24** [snipe/snipe-it#1823]
Currently, from what I can tell (Snipe Noob), you have to type in an asset tag each time. It would be cool to have an option that auto-increments asset tags. All of my assets will just follow a number scheme starting at say 00094 and each new asset is defaulted as the next available number. Maybe leave it up to the user to leave it or change it, but autfill with an incrementing number? Thanks for the great work!

**Comment by ddreier** [comment]
Check out Admin -> Settings.
![image](https://cloud.githubusercontent.com/assets/82290/13542327/a3a03928-e227-11e5-9c1b-8a22afcfb210.png)

You can't influence the starting number AFAIK.

**Comment by ideaman24** [comment]
Got it. Thanks! Like I said, noob here.

Zak Konway
Customer Experience Specialist
Iddea Group LLC
158 S Napoleon St Suite 220
Valparaiso, IN 46383
zkonway@iddeagroup.com<mailto:zkonway@iddeagroup.com>
(219) 576-7143<tel:(219)%20576-7143>




On Fri, Mar 4, 2016 at 9:15 PM -0800, "Daniel Dreier" <notifications@github.com<mailto:notifications@github.com>> wrote:


Check out Admin -> Settings.
[image]<https://cloud.githubusercontent.com/assets/82290/13542327/a3a03928-e227-11e5-9c1b-8a22afcfb210.png>

You can't influence the starting number AFAIK.
