### ISSUE TITLE
Feature request: barcode scanning on mobile using zxing

### ISSUE THREAD

**Issue by rkantos** [snipe/snipe-it#1827]
**Desired behaviour**
Please enable basic barcode querying via the Zxing app on android / iphone.

Like this: http://zxing.appspot.com/scan

It doesn't look difficult to implement according to this page:
https://github.com/zxing/zxing/wiki/Scanning-From-Web-Pages
A working sample is even posted to stackoverflow:
http://stackoverflow.com/questions/26356626/using-zxing-barcode-scanner-within-a-web-page

Also a feature that would autofill some of the information based on a barcode database would be a nice extra feature. 

Outpan would support this nicely
https://www.outpan.com/developers.php

For example: https://www.outpan.com/view_product.php?barcode=0884343048666

Even https://semantics3.com/pricing could work for majority of self-hosted versions, since it supports 500 API calls per day.

It would be simple to take at least the manufacturer and other basic details from the database and add them to predefined fields or just dump them to a specific text field formatted line by line or listing them comma delimited etc.

**Actual Behavior**
Currently the barcode would need to be typed in to the the serial or asset tag fields, which is ok if using a keyboard that supports inputting directly from a barcode, e.g. has a button for it. Most users will not ever install a custom keyboard, so it is a nuisance.

Of course a bluetooth hand scanner would be the best solution for a fast scanning solution.

---
- Version of Snipe-IT you're running  - The demo from the snipe-it webpage

**Comment by snipe** [comment]
I'm not sure I'm clear on what's needed here. Barcode scanners are already supported.

**Comment by rkantos** [comment]
> I'm not sure I'm clear on what's needed here. Barcode scanners are already supported.

Sure they are supported as a text input.; What I'd want is a button or similar, which I could click to directly go in to the barcode app (Zxing) and then input to Snipe-IT forms..
