### ISSUE TITLE
Feature request: GPS based locations or zones

### ISSUE THREAD

**Issue by rkantos** [snipe/snipe-it#1828]
Desired behaviour

This is my second feature request and I understand it would probably be difficult to implement, but I will post it as an idea of the future anyway.

Add a feature where the location of an asset would be queried when adding it to snipe-it from a mobile device. On android just getting the location coordinates would be the easy part. However what I'm after is a feature where snipe-IT either groups assets based on coordinates listed in the database. 

Two ways to implement that I can think off, without knowing any programming
- have a user changeable accuracy range, where the program would just put items within the same "circle" to the same location. e.g. have items within 100m,500m,1km or 2km distances of each other grouped under the same location. This should be relatively easy to implement by just removing decimals from the coordinates.. As I understand it wouldn't really need any logic.
- Second way is to perhaps still have an accuracy range that is user selectable, but instead of just removing digits from the coordinates, the program would decide and possibly ask and/or confirm whether the location is in a location which already has its coordinates set. 

---

Actual Behavior

**Comment by aaj013** [comment]
This could be a nice enhancement and further geospatial features could be introduced. Why don't just add coordinates to location table or in fact geometry field?
