### ISSUE TITLE
Paying you to install Snipe-it for me

### ISSUE THREAD

**Issue by qcfourie** [snipe/snipe-it#1829]
Hi

I'm willing to pay someone to TeamView to my laptop and install Snipe-IT on a CentoOS 7 and MySQL server on our intranet if the price is reasonable.

Pros only please.
Regards
Quentin

**Comment by vabue** [comment]
If you are interested - skype val.budkin

**Comment by qcfourie** [comment]
Thank you for your reply, I get a few hits on skype, how do I know which one is yours?

**Comment by kashifmoin** [comment]
same here I want to do it on windwos server 2008 and xampp can u help I am adding u in skype

**Comment by techyraga** [comment]
You can contact me on skype id: vtmragaven and also you can email at clicks.by.bgATgmail.com 
You can also contact us if you need any special features or modifications.

**Comment by snipe** [comment]
@techyraga any features or modifications you make will likely get overwritten with future upgrades of Snipe-IT unless they are merged into the core repo.
