### ISSUE TITLE
Importing Multi-Seat Software

### ISSUE THREAD

**Issue by MorrisSean** [snipe/snipe-it#1830]
#### When importing software via a CSV with multiple seats, I'd like the software to appear once with each assigned seat populating within the single software entry.

We have software with 100+ seats, each seat may or may-not have it's own key. The ability to enter this into a CSV and then import that CSV into Snipe-IT would save many hours of manual data entry. If the importer could handle multi-user/multi-key, single software input, that would be ideal.
Example Software#1
Seat1
Seat2
Seat3

---
#### When the CSV is imported, it makes a copy of the software for each seat you entered.

When I import a piece of software with 100 seats. It will make 100 copies of that software, with one seat each. We've tested a few different import methods and can't seem to overcome this issue. This significantly clutters the ability to manage licenses within the software, especially in a multiple-key, multi-user environment.  

Example Software#1
Seat1
Example Software#2
Seat1
Example Software#3
Seat1

---
#### Please confirm you have done the following before posting your bug report:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running 
  *v2.1.0-8-g1b1a733
- What OS and web server you're running Snipe-IT on
  *Linux
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  *install.sh
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
  *This is using the CSV importer in Linux
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).

*Reproducable
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

*What we want to accomplish in the example is doable manually and seems like the intended way the license tracker was meant to be used, but it's incompatible with the importer.

**Comment by alexisskeates** [comment]
This is something that would help us as well. We have this scenario with a lot of the software we use which is single licence and not volume licence. When you have 30/40 keys for a single piece of software and each key needs to be uniquely tracked this would make a big difference to the amount of information being displayed within Snipe-IT

**Comment by bbjarn** [comment]
Any movement on this? We'd love to have this feature :)

**Comment by snipe** [comment]
No movement whatsoever. We're still trying to get v3 shipped, and this won't be addressed until that happens.
