### ISSUE TITLE
V3 Feature Request: Asset Transfer

### ISSUE THREAD

**Issue by veen1981** [snipe/snipe-it#1831]
#### Expected Behavior (or desired behavior if a feature request)

Many times we have assets that are transferred from one employee to another. It would be great if there was an option to transfer an asset vs. having to checkin and then checkout the asset.

---
#### Actual Behavior

Currently any asset needs to be checked-in and then checked-out again if being transferred to another employee. While not a major p.i.t.a., having the ability to simply transfer an asset to another employee would make things a little quicker.

---
#### Please confirm you have done the following before posting your bug report:
- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- (v2.1.0-41) 
- CentOS 7
- install.sh

**Comment by SylentBobNJ** [comment]
+1 this

**Comment by snipe** [comment]
If you could edit the asset and change the assigned user, and have the log history automatically show a checkin and checkout, would that work for you?

**Comment by veen1981** [comment]
Yes, that would be great! Also, thank you so much for all the work you have put into this! This is an amazing project that has really helped our department!
