### ISSUE TITLE
Question/Feature Request: Document upload or multiple image upload.

### ISSUE THREAD

**Issue by ryamdagni** [snipe/snipe-it#1832]
Hi there! The attach images to assets and models is awesome. Any chance we can upload .pdf or other document files as well? Our invoices are rarely in an image format. I can convert each page of the invoice into an image, but we only seem to be able to upload one image per asset or model. 
- Snipe-IT: v2.1.0-41-g6d810a9
- PHP Version: 5.5.9-1ubuntu4.14
- Laravel Version: 4.2.17

Help?

Cheers!
Rav.

**Comment by snipe** [comment]
Yeah, that's not exactly the way we expected people to use the uploads there, more just for images of the model. I'll need to think about how we should handle multiple uploads for asset models. Currently, uploads for everything else are handled in one table (`asset_logs`), because those actions show up in the asset history. Asset models don't really exist in that table, so I have to think about the best way to handle something like this.

**Comment by mkola-greenliff** [comment]
Hi,

Any updates regarding this feature request? I would love to have this feature (upload pdf to accessories, assets and licenses).

Thanks,
Mathias

**Comment by Releng-InventiveDesigners** [comment]
I would like to upload PDF's (invoice) to the assets

**Comment by ISNWAdmin** [comment]
I followed a different feature request that was marked as a duplicate to this feature https://github.com/snipe/snipe-it/issues/4018. The other request specified being able to upload files related to asset models which I think gives a little more focus to this request. 
Being able to add files to Asset Models then lets you add user manuals, guides, and other 'generalized' documents to a model which then would relate it to all assets of that model. This would reduce space required, redundancy, and make it easier to manage keeping that documentation up to date.

**Comment by derrynj** [comment]
I'm interested in this. Any chance it can be revisited?

**Comment by raid1** [comment]
Yes, this seems to be a common feature request.
Is it already on the roadmap somewhere?

**Comment by zombiehoffa** [comment]
I too am curious if this is on the roadmap somewhere as I really would like this feature.
