### ISSUE TITLE
Feature Request: - I would like the ability to change the Company Column title to Business Unit

### ISSUE THREAD

**Issue by windclockback** [snipe/snipe-it#1836]
Hi 

I would like the ability to change the Company column title to Business Unit

Change the Company name column title in SETTINGS to Business Unit to accomodate multiple business units within one company.

Feature Not Available at present that I am aware of.
Please consider for the future.

[ Y] I have enabled debug mode
- [ Y] I have read [checked the Common Issues page]

Version of Snipe-IT you're running (v2.1.0-41)
Ubuntu 15.10
What method you used to install Snipe-IT - install.sh

**Comment by snipe** [comment]
You can change it in your language files, but the next time we update those files, you'll have to change it again.

We don't currently have plans to add that feature at this time.
