### ISSUE TITLE
Administrator>Backups: Error: Insufficient Permission!

### ISSUE THREAD

**Issue by mghiringhelli** [snipe/snipe-it#1837]
#### Expected Behavior (or desired behavior if a feature request)

On the demo version i can access on backups page and generate a new backup.

-----

#### Actual Behavior

When i click on Administrator > Backups i get back an error in the home page: 

 Error: Insufficient permissions!

I think the issue is database related, because i tried to make a fresh install and all was workin'.
When i imported my current db, the section backups doesn't work saying that message error.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipeit: v2.1.0-41
- Running Snipe-IT on Centos 7, httpd

- Installed by install.sh
- Error on browser:  Error: Insufficient permissions!
- I'm on Home going to Administrator>Backups
We moved from older version to the new. We have followed the instruction executing php composer.phar etc.

Thanks
Best regards

**Comment by snipe** [comment]
Do you have access to view the database directly?

**Comment by mghiringhelli** [comment]
Yes I do, i’m root.

Thanks

Michael

Da: snipe [mailto:notifications@github.com]
Inviato: venerdì, 11. marzo 2016 01:42
A: snipe/snipe-it
Cc: Ghiringhelli Michael
Oggetto: Re: [snipe-it] Administrator>Backups: Error: Insufficient Permission! (#1837)


Do you have access to view the database directly?

**Comment by snipe** [comment]
That's not always the same thing, but if you can look at the DB record for your user, tell me what you see in the permissions column

**Comment by snipe** [comment]
Any updates here?

**Comment by muflone** [comment]
Hi

The same issue here.
In the users DB table the main administrator account had the values {"admin":1,"user":1}

Adding "superuser":1 fixed the issue.

**Comment by snipe** [comment]
@muflone Update that to read `{"superadmin: 1,"admin":1,"user":1}`

**Comment by muflone** [comment]
Changing "superuser" to "superadmin" doesn't solve the issue.
