### ISSUE TITLE
Feature Request: Asset checkout

### ISSUE THREAD

**Issue by sousa43** [snipe/snipe-it#1838]
#### Expected Behavior (or desired behavior if a feature request)

Every time i what to checkout a pc or laptop, i have to checkout of the pc/laptop and all hardware.
It would be great if the asset have option to assign to other asset.
Ex: asset ram assign to laptop.

-----

#### Actual Behavior

Actualy i have to checkout all de hardware and pc/laptop.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT: 2.1.0
- OS and web server you're running Snipe-IT: Ubuntu Server 14.10

**Comment by SylentBobNJ** [comment]
In the v3 announcement post:

### New Components Section
Now you can create components, like RAM, HDD, etc, and assign them to assets.

Is that what you're looking for?

**Comment by sousa43** [comment]
Hi, yes it is,  i'm going to find and read the post.
Thanks.
