### ISSUE TITLE
Possible Idea/Feature Request for Consumables/Accessories - 'Add New Order'

### ISSUE THREAD

**Issue by SylentBobNJ** [snipe/snipe-it#1841]
#### Expected Behavior (or desired behavior if a feature request)

Just throwing this out there:  Add an interface for refreshing consumables, accessories, or components that uses an 'Add New Order' form.  The form would include multiple entry fields for different consumables, accessories, or components and the quantity of said item to be added to the system. It could pull from existing items as well as provide an option for the user to add a new item.  It would associate all items entered with a single order number, (supplier?), and purchase date. Per-item detail such as cost, quantity, and location would be entered as well, then refresh the in-stock quantities of each item.

Something like:

```
<Add New Order>
Order Num: ______________  Purchase Date: ______________  Supplier: _____________
1) <Search Box For Any Consumable, Accessory, or Component>   <Button to Add New Item>

(After choosing the item)
1) <item> Cost: _____ Location:________ Quantity: __  <button to add additional locations>
                                Location:________ Quantity: __
<Button to Add Additional Items>
```

Later, clicking on the item would reveal a history of each time the item was restocked, the order numbers, etc.

I'm not trying to get to the level of a complete purchase management system, just a convenient way to 'restock' items and track how often they are restocked.  

---
#### Actual Behavior

Right now, when I receive new toner, for example, I edit the existing item, manually change the quantity (an ever-increasing figure), order number, purchase date, and purchase cost which clears out the previously-entered information and provides no means of tracking how often I'm restocking this particular item.

---
#### Please confirm you have done the following before posting your bug report:
- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---

**Comment by MPIAE-IT** [comment]
+1 
The function @SylentBobNJ described is exactly what we would like to have as well. Right now we do it exactly like described. Which does not really show a History of order numbers, purchasing date or even an invoice for every delivery. 

I would love so see this function in snipe-it!

**Comment by MPIAE-IT** [comment]
Is it maybe in anyway possible to integrate a History of who changed what in an accessory or consumable? Right now someone can just change the quantity and there is no history to see who did what...

Are there any plans yet of integrating this feature? If so, any plans in which Version it could be implemented?
