### ISSUE TITLE
Potential Ldap Issue

### ISSUE THREAD

**Issue by alecwhitworth** [snipe/snipe-it#1842]
First i would like to start i work in IT but when it comes to linux i have knowledge which i'm building on. So please bear with me.

I have installed Snipe IT to utilise its function obviously i have managed to install it successfully via the install.sh scripts provided in the documentation. 

I am running v2.1.0-41
on Centos 7.1

I have connected to my LDAP server i believe sucessfully i will attach screen shots with the current configuration. But unless it's the untidyness of AD i don't seem to be pulling all the Users in AD.

and for the record i haven't touched the database.

I managed to sync ad and pull only 53 users of which some where disabled out of about 1500.

To be pointed in the right direction would be great :D.

Thanks
![ldap 1](https://cloud.githubusercontent.com/assets/17769596/13679754/4ac6f98e-e6ed-11e5-9c3a-f8351b9fd9f5.png)
![ldap 2](https://cloud.githubusercontent.com/assets/17769596/13679755/4ac7ae7e-e6ed-11e5-9496-c12aca68e0e5.png)

**Comment by snipe** [comment]
I think AD wants all lowercase letters

**Comment by alecwhitworth** [comment]
I changed all the settings into lowercase as suggested and it did show alot more  in the results than before but there is still alot of blank records showing, will this be fixed in version 3? if so i will hold out.

**Comment by snipe** [comment]
I don't think this is a bug in the first place. My guess is that your search filter is still not exactly right. Lots of people are using the AD/LDAP features without issue.

**Comment by IxFail** [comment]
Try to change 

`LDAP AUthentication query` from `uid=*` to `samaccountname=`

Hope it helps

**Comment by DavidR-ZA** [comment]
Once your users were in the database did they show up in Snipe? I imported all my users with LDAP, they show in the database, but nothing shows in the people.

**Comment by snipe** [comment]
@DavidR-ZA if they're in your database, unless they're marked as deleted, they will show up in your user list.
