### ISSUE TITLE
Can't export more than 50 users at a time to csv.

### ISSUE THREAD

**Issue by dudeincali** [snipe/snipe-it#1844]
#### Expected Behavior (or desired behavior if a feature request)
Expect to export the WHOLE people list in one click.

I only get 50 per export.

Snipe-IT version 	v2.1.0-pre-37-g33b05b0
PHP Version 	5.5.9-1ubuntu4.14
Laravel Version 	4.2.17

**Comment by vickywhitmore** [comment]
I am experiencing a similar issue.  My page buttons disappear as well after the export.  Is there a fix for this?

**Comment by snipe** [comment]
Upgrade to 3.5.0. There is a server-side CSV export available there.
