### ISSUE TITLE
Question for users: do you need (or do your users use) the Edit Profile/Email address/Password stuff?

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#1845]
What I'm trying to decide is whether I want to remove the ability for users to edit their own information (such as password, name, email address), since that's something superadmins may not want to have overwritten. Do you or your users actually use this, or should I pull it out for v3?

I don't mean the ability for superadmins to edit user info, only the part that allows users to edit their own stuff.

**Comment by veen1981** [comment]
I think most of our users would only need to be able to change their passwords. As long as they were still able to do this through the forgot my password link on the signon screen, I personally would see no issue with scrapping this.

**Comment by jeffreytigch** [comment]
We are using LDAP for users to sign in and to get info, so we don't want our users to be able to edit within Snipe.

**Comment by brianjking** [comment]
In the organizations I use Snipe-IT with most of the users aren't even aware that the system exists. As long as the password reset function stays as @veen1981 referenced I'd say I'd be okay too.

**Comment by ernestasen** [comment]
Same here as @brianjking 
I use Snipe-IT and my users just doesn't know that they are in the system.

**Comment by SylentBobNJ** [comment]
If it frees up resources to work on other awesome features, let it die.  We have no plans to bring users onto the system in my organization so, for us, it's not a needed feature at this time.

**Comment by bailantilles** [comment]
+1 for using LDAP for authentication. No need for password or email changing

**Comment by xxtheatrainxx** [comment]
Personally I would like it if the admin had the ability to allow/restrict users the ability to change their info.  Passwords through the reset password function is good, but I wouldn't want my users to log in to check something out and then decide they were going to be cheeky and change their un/email/notes/etc...

I can see how this would be a welcomed feature in some environments, but it could cause a lot of hassle in others.

**Comment by pramos84** [comment]
Like others here, we use Snipe-IT with LDAP authentication, so we don't want let our users modify their own profile. But, personally, I like the photo in profile, and it's not reasonable that admins upload pictures for each user, so I don't know how is the best way to do this. Maybe the LDAP sync could bring this data from LDAP (using thumbnailPhoto field in AD, for example).

**Comment by rasari03** [comment]
@snipe I am using ver v6.2.3 build 11936 (gb47e734b3) , and I would like to take away permission from users ability to edit their Password and edit their email and take away Edit your Profile from drop down menu from username at the top right corner and main landing page after user logs on.
