### ISSUE TITLE
LDAP Confidentiality Required

### ISSUE THREAD

**Issue by hineios** [snipe/snipe-it#1848]
I've just installed Snipe-IT a while back (last week) and I'm trying to use LDAP to import my users into Snipe-IT. I've configured the service with my server's information (I'm also using it for two or three other applications: Rhodecode for instance) but when I try to import the users I get this error.

`Error: Could not bind to the LDAP server. Please check your LDAP server configuration in the LDAP config file. Error from LDAP Server: Confidentiality required.`

I think I've identified the problem. In my LDAP server I force the use of STARTTLS connections has described [here](https://www.digitalocean.com/community/tutorials/how-to-encrypt-openldap-connections-using-starttls). The thing is that I only provide access to the 389 default port with encryption (I have ldaps:// disabled).

So, the question is: how do I enable the use of a STARTTLS connection on ldap://example.com

Using some command line example:
- What I think it's happening: `ldapsearch -D "cn=ruser,dc=example,dc=com" -x -W -P 3 -b "dc=example,dc=com" -h example.com`
- What I want to do: `ldapsearch -D -ZZ "cn=ruser,dc=example,dc=com" -x -W -P 3 -b "dc=example,dc=com" -h example.com`

For those unfamiliar with `ldapsearch` the `-ZZ` flag enforces the use of StartTLS.

oh and the only error I got from the logs was `[2016-03-11 12:53:06] production.ERROR: 13 [] []`

**Comment by ddreier** [comment]
IIRC, the only way right now to have a secure LDAP connection is to use LDAPS. It looks like [LDAP+STARTTLS is supported by PHP](http://php.net/manual/en/function.ldap-start-tls.php), so you might just have to wait a while for a setting to be added to enable it.

**Comment by hineios** [comment]
Wouldn't mind working on this.
I'll fork and give it a go.

Just to be sure I'm not forgetting anything: Must add a check box to the configuration page, add a field to store it, change how you connect to LDAP both on import and login and it should be done, right?
(just want to be sure if I'm not forgetting any other place).

**Comment by snipe** [comment]
This was added in 3.1
