### ISSUE TITLE
Question: Is there any way to add a field for Currency Type associated for asset purchases?

### ISSUE THREAD

**Issue by ryamdagni** [snipe/snipe-it#1849]
Quick question for you.  I am looking to add a required field for the currency used to purchase an asset, since my company makes these purchases from companies around the world (USA, China, etc...). What would be the best way to do this? Currently I am adding the currency type in the Notes field.

I tried creating a Fieldset, but I only seem to be able to associate one Fieldset with a model?

- Snipe-IT: v2.1.0-41-g6d810a9
- PHP Version: 5.5.9-1ubuntu4.14
- Laravel Version: 4.2.17

Cheers!
-Ravi

**Comment by snipe** [comment]
There isn't at this time, and I'm not sure how we'd manage totals with mixed currencies in the same grid.
