### ISSUE TITLE
Question: What size labels do you use for your assets?

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#1850]
So, I know that the labels we generate in Snipe-IT are big. Bigger than most people want. For v3, I want to tighten up those labels (and hopefully provide some customizable options so people aren't stuck with just the size we force you to use). What size labels (and what Avery number, if you have that available) do you use?

**Comment by willlunniss** [comment]
We use a P-Touch label printer with 24mm tape (set height, variable width). Our current template has a 3mm margin top and bottom to give 18mm of usable height and includes a 14x14mm QR code.

**Comment by SylentBobNJ** [comment]
We (would like to) use 12mmx7mm tape in a Dymo printer for barcodes, though I'm open to suggestions if there is a better option, it's just what we have on-hand at the moment.

**Comment by ddreier** [comment]
I'm not that big on labels, for better or worse, and have just been using my little Brother P-touch to put the Asset Number on things.

If I were to make an effort to label all of our machines, I'd probably want to use the little Dymo USB label printer that I have instead of a 'normal' Avery sheet of labels. Then I'd just do a CSV export and use the Dymo software to print labels from that.

W.r.t. Avery labels, I think that the 8160 (1" x 2-5/8") is the pretty standard address-size label.

**Comment by bailantilles** [comment]
I also use a Dymo Duo printer. They are nice and have linux frameworks for integration into applicaitons

**Comment by jghanlon** [comment]
We order company branded asset/security tags through a 3rd party.  They are 3 color metal adhesive tags with a number and a barcode.  I was thinking about printing out smaller tags for things like accessories or cheaper items since we only use the nice asset tags for items over about $200.

**Comment by DaltLund** [comment]
We use Avery 5520 for labeling our assets. That translates to 1 x 2.62 inch. I think some more barcode sizing options is a fantastic idea.

**Comment by snipe** [comment]
@DaltLund We've got some options built into v3 now. Would love it if folks could give a try (using regular paper and then maybe holding it up against labels to make sure the alignment works correctly.)

<img width="775" alt="screen shot 2016-03-16 at 1 38 37 pm" src="https://cloud.githubusercontent.com/assets/197404/13827977/7d71420c-eb7c-11e5-8730-99859f88f7f7.png">

https://v3.snipeitapp.com

**Comment by DaltLund** [comment]
@snipe 
3.0 looks so damn delicious

**Comment by snipe** [comment]
Haha thanks!

**Comment by DaltLund** [comment]
I actually just gave the label printing a shot in the web based demo of 3.0. Setting it up based on my measurements of my label template made the labels generated in snipe pretty damn close. I think with I won't have much issue getting them to fit. The only thing I can see potentially being an issue is not being able to adjust the scale of the barcode itself. Not a big deal at all though.

**Comment by ddreier** [comment]
I tried printing out a page of labels, where the dimensions should match the sheet of Avery 5630 that I have, and it looks like the label widths aren't quite right. I set them to 2.625" (2-5/8) but they seem to only be ~2.25" wide, which causes an rippling alignment issue. I also had an issue where the leftmost QR code got cut off, but I think that might be our printer enforcing some wider margins than I specified (1/8").

Here are some pictures I took: http://imgur.com/a/ZC8Jl

**Comment by snipe** [comment]
@ddreier can you try reducing the label spacing?

**Comment by aaronchintz** [comment]
Just like willlunniss, we use a Brother P-touch label printer with the 24mm (.94") label tape.  This WAS working just fine after you performed some custom adjustments to the layout for me (rearranging the breaks and changing font size), but now it seems that the labels are generating too large for the tape.  Don't know if some minor updates went through on the managed clients, but I just generated some labels for the first time in about a month, and they no longer print properly.  Custom adjustments would be a godsend, as even when I've gotten the current format to work, it can be finnicky.

**Comment by BrisbaneSHS** [comment]
Trying to set dimensions is a complete and utter nightmare. None of it ever lines up according to the dimensions set within Snipes label section. I spent about 3 hours trying to get this crap to work with the L7162 A4. Matching the dimensions exactly as they were in word and it does not work. 

![s](https://github.com/user-attachments/assets/14974e89-2785-4ed8-9f30-52d5f22c6da6)

**Comment by snipe** [comment]
You.... you're literally replying to a *closed* thread from 2016?

If you have issues with the modern label engine, open a new issue FFS.

**Comment by BrisbaneSHS** [comment]
How dare I! Lord forgive me for I've commited a cardinal sin :O

**Comment by snipe** [comment]
Not at all, just seems like a weird flex and a rather bad choice if you actually want solutions. Open a new issue so we can at least know what version you're on. 

It's also more polite, since people who have had this solved since 2016 don't need to be emailed about this just because you're having trouble.
