### ISSUE TITLE
 Error: Insufficient permissions!

### ISSUE THREAD

**Issue by junixone** [snipe/snipe-it#1853]
Error: Insufficient permissions! while view the user information. please help

**Comment by snipe** [comment]
You have to be a super user to edit users

**Comment by junixone** [comment]
Yes

**Comment by junixone** [comment]
I have already view other users.

**Comment by snipe** [comment]
Can't help you without more information. Specifically, the information you deleted from the form before submitting this ticket. http://docs.snipeitapp.com/getting-help.html
