### ISSUE TITLE
New Snipe-It Install Issues

### ISSUE THREAD

**Issue by flucas6630** [snipe/snipe-it#1854]
Hello, I'm new to Snipe-It and I just completed an install of v2.1 on Windows 2012 R2. I have it up and running but I'm noticing that I get the occasional 404 error when I try to navigate pages. But If I refresh a couple of times the page will come up or if I close my browser and try again it comes up. the most recent page it happened on is http://Servername/hardware/create.

I also get an error if I try and run a backup from the admin > Backup page

I enabled debug and I got the following error The "C:\inetpub\wwwroot\snipe-it\app\storage/dumps/2016031535834-db.sql" directory does not exist

I double checked and the folder is there and the security permissions are correct. so it looks like its a problem with the file path switching slashes.

Also 3rd issue is that if I try and add a new asset I cannot click the save button. 

Full disclosure, i'm not a developer at all i'm a network admin/engineer with a small background in IIS. For the install I followed the documents I found online, so it's possible that I missed a step or didn't understand something clearly. anything help the group can provide would be much appreciated

**Comment by ddreier** [comment]
We need the information you deleted from the input box when you created the Issue. See http://snipe.github.io/snipe-it/getting-help.html.

**Comment by flucas6630** [comment]
*   Version of Snipe-IT you're running. (If you didn't grab an official release, let us know which branch you pulled from.)
     *   v2.1.0-47-g39f40a3
  *   What OS and web server you're running Snipe-IT on
     *   Windows 2012 R2 running IIS
  *   What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
     *   I followed the install guides for windows and ran this command php artisan app:install --env=production
  *   If you're getting an error in your browser, include that error.
     *
Whoops!
Server Error: 500 (Internal Server Error)
  *
  *   What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
     *   http://Servername/index.php/admin/settings/backups<http://snipeit.4moms.local/index.php/admin/settings/backups> then I click the Generate Backup Button
  *   If a stacktrace is provided in the error, include that too.
     *   Sorry I don’t know what a stack trace is, but I would be more than happy to get this if you tell me how to do it.
  *   Any errors that appear in your browser's error console.
     *   Failed to load resource: the server responded with a status of 500 (Internal Server Error)
     *   http://snipeit.4moms.local/index.php/admin/settings/backups Failed to load
  *
  *   Confirm whether the error is reproduceable on the demo<https://snipeitapp.com/demo>.
     *   It appears that creating backups is disabled in the demo, so I cannot try to reproduce the error.
  *   Include any additional information you can find in app/storage/logs and your webserver's logs.
  *
  *   Include what you've done so far in the installation, and if you got any error messages along the way.
     *   Everything seemed to install correctly without errors.
  *   Indicate whether or not you've manually edited any data directly in the database
     *   I have not manually touched the database

________________
Frank Lucas
Network Administrator  + Dad to Robby (9) and Tommy (7)
Flucas@4moms.com<mailto:flucas@4moms.com>
p  412.434.8380 (x276)

Meet the NEW 4moms mamaRoo<http://www.4moms.com/mamaroo>®<http://www.4moms.com/mamaroo> infant seat<http://www.4moms.com/mamaroo>

[cid:B42B34ED-BBE5-4075-9DF3-71329D7E707D]

**Comment by ddreier** [comment]
Enable debug mode and post a screenshot of the error page.

**Comment by flucas6630** [comment]
InvalidArgumentException thrown with message "The "C:\inetpub\wwwroot\snipe-it\app\storage/dumps/2016032133638-db.sql" directory does not exist."

Stacktrace:
#30 InvalidArgumentException in C:\inetpub\wwwroot\snipe-it\vendor\symfony\finder\Symfony\Component\Finder\Finder.php:677
#29 Symfony\Component\Finder\Finder:in in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:285
#28 Illuminate\Filesystem\Filesystem:directories in C:\inetpub\wwwroot\snipe-it\vendor\chumper\zipper\src\Chumper\Zipper\Zipper.php:361
#27 Chumper\Zipper\Zipper:addDir in C:\inetpub\wwwroot\snipe-it\vendor\chumper\zipper\src\Chumper\Zipper\Zipper.php:157
#26 Chumper\Zipper\Zipper:add in C:\inetpub\wwwroot\snipe-it\app\commands\SystemBackup.php:55
#25 SystemBackup:fire in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php:112
#24 Illuminate\Console\Command:execute in C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Symfony\Component\Console\Command\Command.php:253
#23 Symfony\Component\Console\Command\Command:run in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php:100
#22 Illuminate\Console\Command:run in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Application.php:101
#21 Illuminate\Console\Application:call in <#unknown>:0
#20 call_user_func_array in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Artisan.php:57
#19 Illuminate\Foundation\Artisan:__call in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:208
#18 Illuminate\Support\Facades\Facade:__callStatic in C:\inetpub\wwwroot\snipe-it\app\controllers\admin\SettingsController.php:232
#17 Controllers\Admin\SettingsController:postBackups in <#unknown>:0
#16 call_user_func_array in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Controller.php:231
#15 Illuminate\Routing\Controller:callAction in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php:93
#14 Illuminate\Routing\ControllerDispatcher:call in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php:62
#13 Illuminate\Routing\ControllerDispatcher:dispatch in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php:967
#12 Illuminate\Routing\Router:Illuminate\Routing\{closure} in <#unknown>:0
#11 call_user_func_array in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Route.php:109
#10 Illuminate\Routing\Route:run in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1033
#9 Illuminate\Routing\Router:dispatchToRoute in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1001
#8 Illuminate\Routing\Router:dispatch in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:775
#7 Illuminate\Foundation\Application:dispatch in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:745
#6 Illuminate\Foundation\Application:handle in C:\inetpub\wwwroot\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php:34
#5 Barryvdh\Debugbar\Middleware\Stack:handle in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Session\Middleware.php:72
#4 Illuminate\Session\Middleware:handle in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php:47
#3 Illuminate\Cookie\Queue:handle in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php:51
#2 Illuminate\Cookie\Guard:handle in C:\inetpub\wwwroot\snipe-it\vendor\stack\builder\src\Stack\StackedHttpKernel.php:23
#1 Stack\StackedHttpKernel:handle in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:641
#0 Illuminate\Foundation\Application:run in C:\inetpub\wwwroot\snipe-it\public\index.php:49

**Comment by flucas6630** [comment]
![screen shot 2016-03-21 at 3 37 55 pm](https://cloud.githubusercontent.com/assets/17860314/13931722/fd95d842-ef7a-11e5-99e9-63fcaf78f1a3.png)

**Comment by ddreier** [comment]
Read through issues #1483 and #1337 for a solution. It looks like you're having the same issue.
