### ISSUE TITLE
Feature Request - Add EOS/LDOS field to Models table

### ISSUE THREAD

**Issue by jimmysnee** [snipe/snipe-it#1855]
#### Expected Behavior (or desired behavior if a feature request)

For many high cost assets, the replacement (infrastructure refresh) is not driven by the EOL (number of months in use) or the depreciation schedule, but by an EOS (End of Support) or LDOS (Last Day of Support) date.  This date is set by the manufacturer, is specific to by model as part of that model's plotted lifecycle.

As an example, a Cisco Nexus 7000 F1-Series 32-Port 1 and 10 Gigabit Ethernet Module will go EOS on August 31, 2019.

It would be very helpful to have this field in the models table, so that a report can be run to query the database for all assets where the models are EOS as of a certain date.  This would be extremely useful for risk analysis, as well as determining refresh costs during budgeting season!

---
#### Actual Behavior

EOS (or LDOS) field does not currently exist.  The EOL field exists, but represents different attributes about the asset.

---
#### Please confirm you have done the following before posting your bug report:
- [ X ] I have enabled debug mode
- [ X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running -  v2.1.0-47-g39f40a3
- What OS and web server you're running Snipe-IT on - RHEL 6 running Apache
- What method you used to install Snipe-IT - install.sh with minor edits

**Comment by snipe** [comment]
So it doesn't sound like this belongs at the model level, but should maybe be a custom field on the asset? 

> This date is set by the manufacturer, is specific to by model as part of that model's plotted lifecycle.

If you have 10 assets of those asset models, each purchased at different times, would their LDOS still be the same? If not, this doesn't belong at the asset model level, but instead the asset level.

**Comment by jimmysnee** [comment]
Yes, all devices with the same model number have the same LDOS (last date of support). It is how the manufacturers sunset older products (no longer have to make the parts, develop code for older generation equipment, and don’t provide tech support on that old kit).

**Comment by jimmysnee** [comment]
There is no relationship between the LDOS and the purchase date (or depreciation schedule).

**Comment by cwoods131** [comment]
This would be a great feature for our assets as well. In many cases model numbers have an end of service on the same day, this would eliminate the need to enter this information on hundreds of assets of like models. Or the ability to add multiple custom fields which are attached directly to the asset models.
