### ISSUE TITLE
Unable to edit the Existing Fields

### ISSUE THREAD

**Issue by avinash1228** [snipe/snipe-it#1856]
#### Expected Behavior (or desired behavior if a feature request)

(We want to remove some fields from the existing one and need to add somme fields which I want)

-----

#### Actual Behavior

(When I am trying to add any asset like system i want to add all the system details like CPU serial number, Monitor serial number, keyboard,mouse etc...)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode----- yes
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)---- yes

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running----- 2.1.0-41
- What OS and web server you're running Snipe-IT on------ Ubuntu 14.04 server edition
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)-----install.sh
- If you're getting an error in your browser, include that error-----no
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
You have not confirmed whether this is reproducible on the demo. Also, I'm still not clear on what you're trying to do.

**Comment by avinash1228** [comment]
yes we can reproduce the issue in demo page.

**Comment by snipe** [comment]
"Also, I'm still not clear on what you're trying to do."

**Comment by avinash1228** [comment]
can we have any skype call

so that will get u clear idea

**Comment by snipe** [comment]
We do not provide Skype support for free community users. Just explain what you're trying to do.
