### ISSUE TITLE
Manually change Export Licenses Content

### ISSUE THREAD

**Issue by madmax01** [snipe/snipe-it#1859]
Hello,

right now once exporting Licenses only 7 Titles are integrated.

Company,License,Serial,Setas,Remaining Seats, Purchase Date and Actions.

there are more other Fields inside the Licenses.

is there a Way to manually change and export it over commandline?

would love to see if i could choose between all of the Titles.   
Mostly missing Expiration Date, Purchase Date,Purchase Order Number,.....

As it's helpfully for getting customized Content to see these fields inside the csv/txt

thx

max

**Comment by snipe** [comment]
Additional fields have been added in the upcoming v3
