### ISSUE TITLE
Question/FeatureRequest: Sorting users by Group?

### ISSUE THREAD

**Issue by ryamdagni** [snipe/snipe-it#1860]
Hi there! I am attempting to sort users based on their group but am unable to do so.  Every other column I have allows for sorting except for group.  I want to see everyone with Admin privilege, etc... grouped together. :)
- Snipe-IT version  v2.1.0-41-g6d810a9
- PHP Version   5.5.9-1ubuntu4.14
- Laravel Version   4.2.17

Thanks!
Ravi.

**Comment by snipe** [comment]
I'm not sure how you'd do that, since people can be members of multiple groups. Which one comes first in the sorting?
