### ISSUE TITLE
Export feature is Downloading without Extension

### ISSUE THREAD

**Issue by sundaresanm** [snipe/snipe-it#1862]
Hi Team,
         Export Feature in Asset Management solution,its starts downloading without extension.
        Kindly help me to sort this issue..

Thanks,

Sundar M

**Comment by ddreier** [comment]
You need to provide answers to all of the questions that you deleted when you created the ticket.

**Comment by snipe** [comment]
That's a known issue with bootstrap tables, and I believe there is already a ticket open for it. Just rename the file to have a CSV ending
