### ISSUE TITLE
500 Error when clicking companies

### ISSUE THREAD

**Issue by ESWBitto** [snipe/snipe-it#1864]
#### Expected Behavior (or desired behavior if a feature request)

I upgraded from 2.0 to the current version and when I click on companies I get a Server error 500

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
Latest Version v2.1.0-55
- What OS and web server you're running Snipe-IT on
Centos 7
- What method you used to install Snipe-IT 
install.sh
Here is the log associated with it.
[2016-03-17 16:02:34] production.ERROR: exception 'ReflectionException' with message 'Class Controllers\Admin\CompaniesController does not exist' in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:504
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(504): ReflectionClass->__construct('Controllers\\Adm...')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(428): Illuminate\Container\Container->build('Controllers\\Adm...', Array)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(462): Illuminate\Container\Container->make('Controllers\\Adm...', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(78): Illuminate\Foundation\Application->make('Controllers\\Adm...')
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(51): Illuminate\Routing\ControllerDispatcher->makeController('Controllers\\Adm...')
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\\Adm...', 'getIndex')
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /var/www/html/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []

**Comment by snipe** [comment]
Did you run `composer dump autoload`?

**Comment by ESWBitto** [comment]
When I upgraded I did all three of these.

php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan migrate

**Comment by ESWBitto** [comment]
I also tried doing 
<code>
php artisan db:restore /var/www/html/app/storage/dumps/2016031631703-backup.zip
php artisan db:restore /var/www/html/app/storage/dumps/2016031631703.sql
(note: after I unzipped it)

</code>

**Comment by snipe** [comment]
@ESWBitto did we sort this in bitter, or is this still an issue?
