### ISSUE TITLE
mcrypt_encrypt(): Key of size 36 not supported by this algorithm. Only keys of sizes 16, 24 or 32 supported

### ISSUE THREAD

**Issue by saopramod** [snipe/snipe-it#1866]
@snipe please help. I have installed Snipe-IT on Windows with XAMPP. Everything has gone well upto Composer Install and Artisan. Even the database has been successfully created

But the Pages are not displayed. I am attaching a screenshot 

![untitled](https://cloud.githubusercontent.com/assets/5446041/13897763/088e731a-ede3-11e5-9172-a82436655f83.png)

Please help on this

**Comment by snipe** [comment]
http://docs.snipeitapp.com/common-issues.html#error-message-mcrypt_encrypt-key-size-not-supported-by-this-algorithm-only-keys-of-sizes-16-24-or-32-supported

**Comment by saopramod** [comment]
Thanks :+1:  @snipe
