### ISSUE TITLE
Feature Request: Multiple asset maintenance

### ISSUE THREAD

**Issue by Mooninaut** [snipe/snipe-it#1868]
I sometimes send out upwards of 10 devices in need of repair in a single shipment. The repairs are invoiced in batches, and we issue a single Purchase Order per return shipment, which includes return shipping costs. Having to create one "Maintenance" per asset is tedious, and either doesn't capture shipping costs, arbitrarily assigns shipping costs to one asset, or requires me to divide out the shipping costs among them myself. It would be nice if I could create a group "Maintenance" shipment with multiple assets at once.

Now, I can see that this could become a very complicated feature, as stuff that goes out together doesn't always come back together, which could create a giant headache if not handled carefully.

What I'd like is a "Maintenance Shipment" or "Maintenance Event" which could reference multiple assets, would change each of the assets' status in a single operation, and would be reflected on each asset's Maintenance tab. "Outgoing Maintenance Events" and "Incoming Maintenance Events" wouldn't have to be one-to-one, but they could reference the same assets. Each could have a "Maintenance Event Cost" that would be distinct from the cost of maintenance for each asset, and could be automatically divided up among them. That would permit calculation of a lifetime maintenance cost for each asset, including shipping.

If that's too much to ask, which I can see that it very well could be, I'd like a way to bulk-create Maintenance entries for a bunch of assets at once, avoiding the need to create numerous virtually identical Maintenance entries one at a time.

Thanks for all your hard work! I just installed a copy of Snipe-IT version 3 in a VM and it looks great!

**Comment by neokleon** [comment]
any body???
