### ISSUE TITLE
Asset-loading by tag in URL

### ISSUE THREAD

**Issue by TheCodePianist** [snipe/snipe-it#1870]
Hello! I started using Snipe-IT to manage my video equipment (light panels, cables, cameras, lenses, etc.). Even though some parts of snipe-it don't apply 100% to non-IT topics, overall it is perfectly usable for this case!

I wrote an EAN-8 barcode generator, which generated labels in the following style:
04xxxxxN (04 stands for company-internal stuff in EAN8 standard, N is the generated checknumber)
The 5 digits between 04 and N are randomly generated, are unique and are the asset-tag I enter in Snipe-IT.

Now I am missing one thing: When I am going to a filmset, I would love to be able to quickly checkout equipment at home before a job and check it back in afterwards. This way I can easily see whether items get lost.

There are plenty of barcode-scanners in the Android store, and some of them are configurable to do special things with the scanned code like generate a URL from it. So it would be awesome to implement URL-parsing for asset-IDs in Snipe-IT so that scanning the barcode can redirect to the asset-page for checkout/-in. The url could look like this:

Pattern: http://assets.mycompany.com/searchtag/$assettag
Example: http://assets.mycompany.com/searchtag/19627

Hope you like this idea and think about implementing it. And thanks for writing such a great tool!

**Comment by snipe** [comment]
I'm not sure I understand why the asset tag is required in the URL. The labels we generate already pull up the URL based on the asset's ID.

**Comment by TheCodePianist** [comment]
Thanks for reading and replying!

When I setup systems I always do so with "eternity in mind". Therefore I am not feeling comfortable putting hardcoded URLs as barcode onto my stuff - even more if it is an URL containing the internal item ID and page-structure of one particular asset-management software.

I see the asset-tag as a beautifully generalized way of reffering to a particular item, like a system-independent ID. Using an EAN8-barcode makes it readable by all hardware supporting the EAN-standard and parseable by all software I choose to use. Here are some advantages:

1. Generate links for Snipte-IT.
2. Generate links for any other asset-management software/tool without the need to change labels on the items
3. Small Codes (EAN-8) possible, QR or Code128 is simply too big sometimes.

**Comment by snipe** [comment]
You can do that via  http://assets.mycompany.com/hardware/bytag?assetTag=
