### ISSUE TITLE
Feature Request - Separate Clients/Departments

### ISSUE THREAD

**Issue by alexisskeates** [snipe/snipe-it#1871]
We use Snipeit to track assets for our clients and it works great, but one thing we need to do is maintain separate installs for each client.

We would like to request the ability create separate clients within a single install which would also allow us to give account access to our clients directing them only to the asset information for their company. The ability to separate that further into departments would be useful as sometimes our clients have departments which maintain their own asset information and they would like to keep that separate usual case is when the client has multiple offices usually in different countries.

**Comment by ddreier** [comment]
Have you tried using the Multi-Company support? It might not be 100% what you're looking for, but it does allow you to separate assets and users into separate "Companies" where they can only see their own stuff.

**Comment by alexisskeates** [comment]
Thanks for that I’ll give it a go and see how I get on. I’ve not updated my install of snipeit for a while so I might setup a fresh install and test.

**Comment by alexisskeates** [comment]
I've had a play with this now and for the most part it does what I need the only reservation I have is that if I set a user from a company as an admin they are then able to see the Dashboard, Assets Accessories, Consumables, Licences and so fourth for the company they are assigned to which is what I want. They are also able to access the admin menu where they can then see other companies and also delete them as well groups and locations which I would not want.

It's almost like there needs to be another level of user in between Admin and Reporting that gives you access to view all the information related to that company, but does not give you access to view any data that would allow you to see or modify settings outside of your company.
