### ISSUE TITLE
not respond add new model in asset menu and fieldset make error 500

### ISSUE THREAD

**Issue by kajonsakz** [snipe/snipe-it#1874]
Hello Dev

I have trouble about snipeit

1. I can't add new model in asset menu 
when me enter model and press save, snipeit not respond (but demo website is worked)

2. fieldset make error 500
if asset model has fieldset when call that asset model (in create model) and save snipeit will report 
"Whoops!
Server Error: 500 (Internal Server Error)"

Please tell me about troubleshooting 
Thank Dev. 

SnipeIT v2.1.0-55
Ubuntu Server 14.04 
Install.sh
All web Browser

**Comment by snipe** [comment]
http://docs.snipeitapp.com/getting-help.html
