### ISSUE TITLE
CLI installer issue

### ISSUE THREAD

**Issue by djdamith** [snipe/snipe-it#1875]
when i run CLI installer nothing happens with the commands

i have install composer and ran the install command which execute without an issue, however after that i tried to execute " php composer.phar install --no-dev --prefer-source" command but it didnt return anything. not even an error.

Snipe it 2.1.0
running on IIS 10
Php v5.5
and MySQL

**Comment by snipe** [comment]
Please provide the output of your app error logs, as requested in the Getting Help documentation.

**Comment by ddreier** [comment]
@djdamith did you install Composer with the Shell Menu option? It seems like that may be necessary for things to work.
