### ISSUE TITLE
Wrong Serveraddress 

### ISSUE THREAD

**Issue by FSCHARR** [snipe/snipe-it#1877]
Hello together, 

in our company we just added a DNS entry for SNIPE IT Asset Management Version 	v2.1.0-8-g1b1a733.
We are able to access the system through the new entry, but if we are clicking on the icon in the header we have the issue to land on the "old" serveraddress, so we have to sign in again.
Is there a possibillity to change the Webadress for the icon? 

Tanks for a reply!

Greetings Chris

**Comment by snipe** [comment]
Sounds like you didn't update the url in app/config/production/app.php

**Comment by FSCHARR** [comment]
First of all, thanks for your reply.
The file is empty at the moment, can you tell me, which content should be in this file?

**Comment by snipe** [comment]
The file should definitely not be empty. Did you copy app.example.php from the same directory over, per the installation instructions?

**Comment by FSCHARR** [comment]
Yeah sorry, I got the wrong one... 
I changed the url to the new one and restarted the server, but by clicking on the icon 
it´s running to the wrong url...

**Comment by FSCHARR** [comment]
Another issue: If we use the DNS as URL to get to Snipe IT, the Custom Fields dosent work...

**Comment by snipe** [comment]
The URL in the app settings can't be correct then. Can you show me what you have for `app/config/production/app.php`, and tell me what the URL is that you go to to login?

**Comment by FSCHARR** [comment]
I changed the URL to the old one, you can see it on the screenshot:
![image](https://cloud.githubusercontent.com/assets/18027855/14098565/b2d40726-f57d-11e5-88b1-b70ab0782691.png)

For the new URL i changed "'url' => '192.168.239.245'," to "'url' => 'snipeit.scharrnet.de',".
I saved the file and restarted the server, but it wont work...

**Comment by snipe** [comment]
It's asking for a URL, not an IP address. You need http:// in front of your IP.

**Comment by FSCHARR** [comment]
I changed the URL to http://snipeit.scharrnet.de and restarted the server.
But by clicking on the icon the browser leads to the old address...

**Comment by FSCHARR** [comment]
Thats the new configuration: 

![image](https://cloud.githubusercontent.com/assets/18027855/14100992/9b96909c-f591-11e5-9884-35710b18d7d6.png)

**Comment by snipe** [comment]
It's literally not possible, unless you're entering the wrong address, or are editing the wrong file.

If you look at https://github.com/snipe/snipe-it/blob/master/app/views/backend/layouts/default.blade.php#L121, you can see that the logo link is being generated from `{{ Config::get('app.url') }}`, which is the value of that url in the config file.

**Comment by FSCHARR** [comment]
Just I tried to restart Apache, but I got this error: 

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
                                                                                                                                                                                 [ OK ]

Do you have an idea? :)

**Comment by snipe** [comment]
Yes, you need to set a ServerName in your virtualhost. The error is telling you what's wrong. 
http://stackoverflow.com/questions/9541460/httpd-could-not-reliably-determine-the-servers-fully-qualified-domain-name-us

**Comment by FSCHARR** [comment]
Just I created the FQDN, I restarted Apache and the Server, but the URL form the Icon still be wrong... 
And Custom Fieldsets don´t work...

**Comment by FSCHARR** [comment]
Just it works! :) 

Do we have the possibillity to set up a routing that our users land on snipeit.scharrnet.de allthough they used the IP address as URL?

**Comment by snipe** [comment]
"but the URL form the Icon still be wrong... And Custom Fieldsets don´t work..."

This is ALWAYS due to the url in your app config being wrong. Always. It pulls that url directly from the config file.

**Comment by smokedawg26** [comment]
Hello -

I'm getting the same error when trying to start httpd....

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message

You mention updating ServerName in the app.php file located in **app/config/production/**.

My issue is that my app.php file is located in **/var/www/html/snipeit/config**.

Would the location of the app.php file cause the problem that I am having?

**Comment by snipe** [comment]
@smokedawg26 that's an unrelated [server configuration issue](https://askubuntu.com/questions/256013/apache-error-could-not-reliably-determine-the-servers-fully-qualified-domain-n).
