### ISSUE TITLE
Snipe-it install Win 2012 R2

### ISSUE THREAD

**Issue by jbenter** [snipe/snipe-it#1878]
Hello, I've completed all the setup steps and finished adding my Snipe-it site to ISS.

 But I am getting a ERR_NAME_NOT_RESOLVED 

 I try to browse for the site I defined in the app file. 

![snipe-it](https://cloud.githubusercontent.com/assets/13422858/13998153/15ae9c92-f10c-11e5-855b-d432dd5269da.jpg)

System info:
Win 2012 R2
IIS 8.5
MySQL 5.7
Snipe-IT 2.1.0

**Comment by ddreier** [comment]
You have to set up the DNS records for www.sositam.org (assuming that you own the domain) before that URL will work.

You could try browsing to http://localhost to verify that Snipe-IT was set up correctly.

**Comment by jbenter** [comment]
It gives me an error 404 when I try to browse the local host.

**Comment by jbenter** [comment]
When I tried http://127.0.0.1 I got 

http://127.0.0.1/auth/signin

**Comment by uberbrady** [comment]
That means it's working. Type in your username and password you set up while installing.

**Comment by jbenter** [comment]
I get an error 400 though

**Comment by jbenter** [comment]
My mistake I get an error 500 on that page.

**Comment by jbenter** [comment]
![error](https://cloud.githubusercontent.com/assets/13422858/14017726/d33f5cf4-f19f-11e5-9620-9e05a90cfeda.jpg)

This the error page/

**Comment by ddreier** [comment]
You need to enable debug mode. http://docs.snipeitapp.com/getting-help.html

**Comment by jbenter** [comment]
That was a huge help. I had to change the local host info slightly referencing the port number. Now how do I get the URL I created to work? I can only access it from the local host address.

**Comment by ddreier** [comment]
Choose "Edit Bindings" when you right-click on the snipeit site in IIS Manager and add a binding for the URL in there.

You'll also need to set up DNS records for your URL, but that's outside the scope of getting Snipe-IT running.

**Comment by jbenter** [comment]
That did it. Thank you all.
