### ISSUE TITLE
Feature Request: From mobile interface, allow scanning of barcodes for text input

### ISSUE THREAD

**Issue by delize** [snipe/snipe-it#1879]
#### When pulling up the mobile interface, have an option that allows you to use the camera/barcode reader to input serial numbers

So while being completely new to SnipeIT and still learning everything it can do, I really want to push our management to move to this system, as it seems incredibly easy and straightforward, however, I don't see any option on importing serial numbers and licenses using a barcode scanner. 

So on the mobile side, it would prompt for the camera or the barcode reader, and then from there automatically fill out the text from the result. 

I would prefer this on Android, but, either way, this would make the job faster then having to import the serial numbers by hand.

**Comment by misilot** [comment]
I would love to see this added as well. It would improve the workflow, so we don't have to attach a barcode scanner to our phones or laptops.

**Comment by brianrking** [comment]
+1 to this - it would really improve our ability to use Snipe-It in the field and on the fly.

**Comment by derrickchiang** [comment]
+1 would help with support staff when mobile and need to pull up info on an asset or to reassign it to a new location
