### ISSUE TITLE
Add field to License Dashboard.

### ISSUE THREAD

**Issue by hobbit666** [snipe/snipe-it#1880]
Is it possible to have the "Licensed to E-mail" field available on the License overview screen as it will handy for us to see what E-mail address we have used when registering Office 2013/2016 licenses.
![snipelicense](https://cloud.githubusercontent.com/assets/15997517/14020282/654bc028-f1ce-11e5-8711-02e34ad54286.png)

**Comment by snipe** [comment]
This is already fixed in the upcoming v3
