### ISSUE TITLE
E-mails not being sent

### ISSUE THREAD

**Issue by lravelo** [snipe/snipe-it#1882]
#### Expected Behavior (or desired behavior if a feature request)

**I would expect that an email be generated when requesting an asset**

-----

#### Actual Behavior

**I get the following error after enabling debugging:  Expected response code 220 but got code "500", with message "500 #5.5.1 command not recognized " **

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running:  **v2.1.0-55**
- What OS and web server you're running Snipe-IT on:  **Ubuntu Server 14.04 x64**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): **Snipe-IT Installation with Ansible **
- If you're getting an error in your browser, include that error:  **see above**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error:  **http://<servername>/account/requestable-assets**
- If a stacktrace is provided in the error, include that too.: **n/a**
- Any errors that appear in your browser's error console.: **500 Internal Server Error (FireFox)**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).:  **I'm not sure that email works in the demo.**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
[log-apache2handler-2016-03-24.txt](https://github.com/snipe/snipe-it/files/188700/log-apache2handler-2016-03-24.txt) 
[apache.log.txt](https://github.com/snipe/snipe-it/files/188704/apache.log.txt)

- Include what you've done so far in the installation, and if you got any error messages along the way.: **no issues during actual installation process**
- Indicate whether or not you've manually edited any data directly in the database: **no manual edit**

**Comment by snipe** [comment]
Can we see your mail config file (with password obfuscated, of course)

**Comment by snipe** [comment]
```
[2016-03-24 20:32:01] production.INFO: Pretending to mail message to: lazaro.ravelo@me.com [] []

...

exception 'Swift_TransportException' with message 'Connection could not be established with host [172.21.1.40] [Unable to find the socket transport "null" - did you forget to enable it when you configured PHP? #32619]' in /opt/snipe-it/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:265
```

**Comment by lravelo** [comment]
Here's the mail.php file.  That particular error message from before was me testing to see if setting 'null' in the encryption would make a difference but I guess it didn't.  I set it back to tls.

[mail.php.txt](https://github.com/snipe/snipe-it/files/188710/mail.php.txt)

**Comment by snipe** [comment]
Please paste in text, don't upload attachments. 

`'host' => '[172.21.1.40]',`

That is not a valid hostname.

 `'host' => '172.21.1.40',`

And your username and password are set to null. You need to provide credentials there.

**Comment by lravelo** [comment]
Sorry about that.  Let me try.

**Comment by lravelo** [comment]
ok so I removed the brackets but I still get the same error:

Expected response code 220 but got code "500", with message "500 #5.5.1 command not recognized " 

I rebooted apache2, didn't work.  I rebooted the server itself, didn't work.

**Comment by snipe** [comment]
Did you enter a username and password for the email account you're trying to send from?

**Comment by snipe** [comment]
(You don't need to reboot anything, btw.)

**Comment by lravelo** [comment]
I know.  I did it for good measure.  Old Windows habits die hard, I'm afraid lol.  Anywho, I didn't need to add credentials since our smtp doesn't use any authentication.

**Comment by snipe** [comment]
If you're using SMTP, you're logging into an SMTP server as someone (some account). You need to use credentials there. Otherwise you can try using the `mail` driver instead of `smtp`.

**Comment by lravelo** [comment]
would 'anonymous' for both the username and password be the way to go for an smtp server that doesn't require authentication?  in the interim, i'll test the mail driver.

**Comment by snipe** [comment]
Not unless you can actually login to that SMTP server using anonymous/anonymous as credentials.

**Comment by lravelo** [comment]
ok I tried using the `mail` driver and no longer get the message.  However, I'm not receiving any email.  Is the email account set up under the "Send alerts to" field the email that would get that notification.  I'm not seeing any email account associated with the particular test asset I created.

**Comment by lravelo** [comment]
I took a different approach this morning and it looks like it's been resolved.  I installed sendmail and configured it to forward everything to the SMTP server we currently have in house.  I do have one question:  Can sendmail be used in the cron job to notify of expiring contracts/licenses?

**Comment by snipe** [comment]
Glad you got it sorted.

Whatever you configure in your mail.php will be used for all emails sent by the system. You don't have to do anything special to make that happen.

**Comment by lravelo** [comment]
Is there any way to trigger one manually?  Say, perhaps, create maintenance contract that expires tomorrow (I'm not sure of the threshold)?
