### ISSUE TITLE
Unable to open Settings

### ISSUE THREAD

**Issue by sharad9988** [snipe/snipe-it#1883]
Hi,
I am unable to open settings page to change setting for auto increment asset no.
When click on edit setting nothing happened.

Thank
Sharad

**Comment by snipe** [comment]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by sharad9988** [comment]
right now Debug is false and I have checked common issues page.
my version is 2.1.0 , running on Windows server 2008 R2 and manually installed with the help of great documentation provided by Snipe-IT.  I am facing problem with while adding new asset then unable to add new entry for model , status,  supplier by using +  while from by clicking on admin at upper right corner I can able to ass new company, model etc. I have newly installed Snipe-IT.

**Comment by sharad9988** [comment]
Snipe-IT version v2.1.0-47-g39f40a3  
PHP Version 5.4.45 
Laravel Version 4.2.17

**Comment by snipe** [comment]
Turn debug off and tell us what's in your app logs, per the instructions.

**Comment by sharad9988** [comment]
Debug mode is true (ON), still getting same error, unable to add new model while creating asset.
![snipe-it](https://cloud.githubusercontent.com/assets/7130987/14057835/2fe78574-f332-11e5-8f74-5dcaa163236f.jpg)

**Comment by snipe** [comment]
I don't see any error there. I really need you to be more specific. Turning debug mode to on, and then not telling me what the logs say is not helpful. Telling me you're getting an error and posting a screenshot that does not show an error is also not helpful. Also, that screenshot is of the modal in asset creation, not the settings.

**Comment by sharad9988** [comment]
there is nothing in logs, seams that save button is not working.

**Comment by snipe** [comment]
Is there an actual error, or is the save button just not working? And please confirm that there is nothing in your browser's error console. I would be quite surprised if there isn't. Please post a screenshot of the console so I can be sure you're looking in the right place.

**Comment by sharad9988** [comment]
after enableling browser error console i am getting below error .
I Have set  'url'=> 'http://win2008.com', in app.php while in host name in IIS is assets.portal.local

Empty string passed to getElementById(). jquery-latest.js:2798:12
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://win2008.com/api/statuslabels. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

**Comment by sharad9988** [comment]
find screen shot of browser console
![snipe-it2](https://cloud.githubusercontent.com/assets/7130987/14058032/737e7d82-f338-11e5-9570-6842060577a5.jpg)
