### ISSUE TITLE
Feature Request - Asset Maintenance Expiration notifications

### ISSUE THREAD

**Issue by lravelo** [snipe/snipe-it#1884]
I have run `php artisan alerts:expiring` to be able to generate the email notifying me of an expiration.  What I saw, so far, is that it only alerts me of expiring assets (warranty) and expiring licenses.  I would love to have maintenance contracts in there as well.

**Comment by kissit** [comment]
I too would like to see this feature.  We use the maintenance feature in a little different way to notate scheduled maintenance on assets in addition to maintenance contracts.  For instance a quarterly patch  cycle for certain servers.  Being able to receive a notification X amount of days before expiration would be great.

**Comment by snipe** [comment]
I'd be more inclined to hear more about how you use this and add a new feature that makes more sense than to change the way this currently works. Certainly, deleting an asset maintenance is useful (in the case of manual error, etc), but if more people are interested in a feature that fits more along the lines of what you're doing, I'd rather add that.

**Comment by kissit** [comment]
Sorry for hijacking this thread.  I've created #1935 for this.

**Comment by lravelo** [comment]
Hello!  Hoping this is still on the docket.  Would love to be able to receive notifications to let me know my maintenance contracts are due to expire :)

**Comment by jcruzat** [comment]
Most of Asset management have the same features and functions and the deciding factor for our company is the asset maintenance section.  I tried the demo version and I can't see the new created asset for maintenance, asset maintenance report showing errors. Is this features fully functioning? Willing to pay for pro support if I can prove this working to my manager and some additional features like mentioned by other users.

I would also like to see additional features like;
1. Asset maintenance pie chart in the dashboard. 
2. Adding preventive maintenance on the maintenance drop down list.
3. Option for group or individual assets assignment when editing or adding new maintenance 
3. By default an email link and phone no. column for emergency purpose.

**Comment by snipe** [comment]
> I tried the demo version and I can't see the new created asset for maintenance, asset maintenance report showing errors. Is this features fully functioning? 

Yep, just the way it goes with public demos and people junking up the data all the time. I've reset the database now, so you should be able to see new asset maintenances.
