### ISSUE TITLE
Feature Request - License Report Total Amount

### ISSUE THREAD

**Issue by lravelo** [snipe/snipe-it#1885]
Would be nice to see the Total Amount of the licensing report.

**Comment by snipe** [comment]
Total what?

**Comment by lravelo** [comment]
my bad...thought I wrote it.  Total cost.

**Comment by snipe** [comment]
I believe this was already added a few versions back.

<img width="1290" alt="screen shot 2018-04-06 at 4 33 09 pm" src="https://user-images.githubusercontent.com/197404/38448302-38505c44-39b8-11e8-954e-ac9229b76c2b.png">
