### ISSUE TITLE
Feature Request - Barcode as Serial

### ISSUE THREAD

**Issue by davidking727** [snipe/snipe-it#1887]
Custom Asset Tags printable from URL

**Comment by snipe** [comment]
?

**Comment by davidking727** [comment]
Sorry. Instead of just having the QR code that takes it to the Informational page. Being able to create an asset tag like the following. Where the Barcode is the Serial of the device
![tag](https://cloud.githubusercontent.com/assets/5784437/14052270/49a4561a-f29f-11e5-84a7-3fe432edc7a7.jpg)

**Comment by snipe** [comment]
What is the use case here?

**Comment by rezafouladian** [comment]
I would be interested in this as well. The current barcodes are useless to me, since I use multiple systems and look everything up by the asset tag.
