### ISSUE TITLE
permission issue 

### ISSUE THREAD

**Issue by asdarunasd1** [snipe/snipe-it#1890]
Error in exception handler: The stream or file "/var/www/html/snipeit/app/storage/logs/log-apache2handler-2016-03-28.txt" could not be opened: failed to open stream: Permission denied in /var/www/html/snipeit/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:87

getting this error....when i install through installer script... I use centos 7
i use apache webserver ...i changed owner of the file to user of webserver also gave 755 chmod to those files...Still this error?

**Comment by snipe** [comment]
Please check if SElinux is enabled. http://docs.snipeitapp.com/installation/server/linux-osx.html#notes-on-selinux

**Comment by asdarunasd1** [comment]
Great ..THANKS...i had selinux enabled...i disabled it and it worked..THANX A LOT
