### ISSUE TITLE
automatically redirecting to https after a while 

### ISSUE THREAD

**Issue by asdarunasd1** [snipe/snipe-it#1891]
i have hosted snipe IT in production as localhost ...Its deployed in centos  7

i can asses snipeit in http://ipaddress ..it works fine...but after a while maybe 3 or 4 minutes...site automatically goes and the below error shows up and redirects the url to https://localhost ....

This site can’t be reached

localhost unexpectedly closed the connection.
ERR_CONNECTION_CLOSED

**Comment by asdarunasd1** [comment]
also in app/config/production/session.php  in that 'secure' => false,

**Comment by snipe** [comment]
What is your URL in `app/config/production/app.php`?

**Comment by asdarunasd** [comment]
Sry don't confuse with that... I just mentioned I didn't enable https cookies ...

**Comment by snipe** [comment]
I don't know how to be more clear. Go to `app/config/production/app.php` and tell me what you have entered in the `url` section.

**Comment by asdarunasd** [comment]
I can access the application with url http://ipaddress but after a while the url automatically changes to https://localhost and gets that connection closed error

**Comment by snipe** [comment]
Open `app/config/production/app.php` and tell me what you have entered in the `url` section.

I will not be able to help you if you don't do this and answer my question.

**Comment by asdarunasd1** [comment]
Thank you so much...its fine now..the issue was with the URL ..:) ..

You are awesome..Cheers mate..:)
