### ISSUE TITLE
Expiration Notification Thresholds

### ISSUE THREAD

**Issue by lravelo** [snipe/snipe-it#1892]
I wanted to change the threshold from 60 days to 180 days for both assets and licenses.  I was able to change this and have the functionality of it working but I'm trying to change the color coding of the alerts in the emails by adding an additional condition.  Here's what I put for assets:

`if ($difference > 90) {`
                `$asset_data['email_content'] .= '<tr style="background-color: #fcffa3;">';`
            `}`
`else if ($difference > 30 && $difference < 90) {`
                  `$asset_data['email_content'] .= '<tr sylte="background-color: #ff771b;">';`
            `}`
`else {`
                `$asset_data['email_content'] .= '<tr style="background-color: #d9534f;">';`
            `}`

Unfortunately, anything between the 30-90 day threshold just shows up with a white background which makes me thing there may be something wrong with my logic.

**Comment by snipe** [comment]
This will be a configurable option in v3.
