### ISSUE TITLE
Apache 403 error from other computers

### ISSUE THREAD

**Issue by DarthToast** [snipe/snipe-it#1894]
#### Expected Behavior (or desired behavior if a feature request)

trying to reach my website from other pcs in our domain.  i get error 403 access denied on all. if i try locally on the pc it works fine

-----

#### Actual Behavor

apache 403 error saying access denied.  but on actual server its fine

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running latest build from master
- What OS and web server you're running Snipe-IT on  server 2012 2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Wamp server with maria db
- If you're getting an error in your browser, include that error  403
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error, any
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). no
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database; have data in

**Comment by ddreier** [comment]
This isn't really a Snipe-IT problem if the app works. But here's a link I found after a quick Google: http://stackoverflow.com/questions/8204902/wamp-403-forbidden-message-on-windows-7
