### ISSUE TITLE
EOL Calculation errors

### ISSUE THREAD

**Issue by bschmidtepiccreative** [snipe/snipe-it#1895]
#### Expected Behavior (or desired behavior if a feature request)

Hello, we're using v2.0.5 of your inventory app and we're having issues with the End Of Life calculations being incorrect. We have a 60 month EOL policy for our equipment and the EOL Date is showing after 36 months.  I've attached a screenshot of it happening on this single asset, but it's happening on other assets as well, not just of this particular model either. Is it using Warranty to calculate EOL instead of the EOL?  Maybe I'm just mis-understanding the functionality here and it's working as intended, but it threw us off, so I figured I'd post and ask.

![view_asset_a-1616____it_inventory](https://cloud.githubusercontent.com/assets/18146665/14113614/574e8cd4-f599-11e5-87a1-588e9951933a.jpg)

![update_asset_model____it_inventory](https://cloud.githubusercontent.com/assets/18146665/14113694/af108c9c-f599-11e5-8586-1a9175c13744.jpg)

Let me know if there's more info that I can provide here.  Thanks for your inventory app, it's been great to use so far!

**Comment by snipe** [comment]
I believe this was fixed in later versions.
