### ISSUE TITLE
restrict user to create/modify assets of some of locations only (location based asset manager)

### ISSUE THREAD

**Issue by sharad9988** [snipe/snipe-it#1896]
Is it possible to restrict user who is the admin of some of the loaction to add/modify and delete assets belongs to particular  location only.

**Comment by snipe** [comment]
It is not currently possible at this time. There is not even a concept of a an admin of a location.

**Comment by sharad9988** [comment]
Can you please add it for new feature request because if is beneficial if an organization has many location and has location admin so that each location admin can maintain asset belongs to his locations.

**Comment by snipe** [comment]
This ticket *is* the feature request. We'll consider adding it, but it is currently lower priority than other features currently on deck.

**Comment by nlnarayana** [comment]
@sharad9988 @snipe  
HI,

  Can you provide some information on this feature request? Is it available or going to be released in the next version.

**Comment by mistamayor** [comment]
I hope this would be coming in V5
