### ISSUE TITLE
OAuth2 support

### ISSUE THREAD

**Issue by savamane** [snipe/snipe-it#1897]
#### Expected Behavior (or desired behavior if a feature request)

Provide the ability to authenticate via one or more of the supported OAuth2 providers. I'm specifically after the google one, but the more the better I guess. I'm thinking something similar to what [gitlab is doing](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/integration/google.md)

Ideally, an admin should be able to:

1) chose between OAuth and database login
2) allow or disable creation of new users from a specific domain, when using oauth.

**Comment by ddreier** [comment]
There is already at least one other issue open for SAML and/or OAuth-based auth.
