### ISSUE TITLE
"Error: You do not have permission to view this page." displayed at top of home page for account with User or Reporting-level permissions.

### ISSUE THREAD

**Issue by natnix94** [snipe/snipe-it#1899]
#### Expected Behavior (or desired behavior if a feature request)

**Expect not to see the error listed in the title.**

-----

#### Actual Behavior

**The error listed in the title displays in red text contained within a light pink box on the user's home page after a successful login for accounts with User or Reporting level permissions.  Admin is not affected.**

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
        - **Debug mode does not report on this issue.** 
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html) - **The issue is not listed on the page.**

-----
#### Please provide answers to these questions before posting your bug report:

- **Running version 2.1.0**
- **Running on Linux Mint 17.3 and Apache**
- **Installed via install.sh**
- **The error is a function of the Snipe-IT system and not a browser error**
- **Upon logging in from an account with either User or Reporting permissions the error in the title is displayed at the top of the page.  I can't help but think it's something simple that I'm missing, but the fix eludes me.**
- **No errors appear in the browser console.**
- **The error displays on the demo as well when logging in as reporting user.**
- **The only thing showing in the app log that might be related is an entry that says "Not Super-Admin" when a non-admin user logs in.**
- **After a couple trial and error installation runs I installed from the install.sh script from a clean server with no errors by following the documentation.  I seeded the database as instructed and logged in with the admin account.  I used the installed data as a guide to create my own asset entries and deleted the sample data from within the app.  I then set up LDAP to authenticate against Active Directory and Synchronized the users.  Once done, I set up SMTP per the instructions.  Everything works perfectly with the exception of the displayed error at the top of the page.**
- **I have not manually edited any data in the database.**

**Comment by snipe** [comment]
Can you confirm if this is happening on the v3 demo? https://v3.snipeitapp.com

**Comment by natnix94** [comment]
Hmmmmmm... It is not occurring in the v3 demo.

**Comment by snipe** [comment]
I'm going to close this issue then, since v3 is right around the corner and the issue seems to be resolved in v3.
