### ISSUE TITLE
[Feature Request] Asset Maintenance Report not adjusting the "Total" value if filtering

### ISSUE THREAD

**Issue by lravelo** [snipe/snipe-it#1900]
#### Expected Behavior (or desired behavior if a feature request)

I'm not sure if this is by design or not but if I'm trying to filter certain maintenance contracts within the asset maintenance report page using the search box, the "Total" value still shows the amount for all contracts

---
#### Actual Behavior

"Total" value still shows the amount for all contracts

---
#### Please confirm you have done the following before posting your bug report:
- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running **v2.1.0-55**
- What OS and web server you're running Snipe-IT on **Ubuntu Server 14.04 x64**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Snipe-IT Installation with Ansible**
- If you're getting an error in your browser, include that error **n/a**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **Asset Maintenance Report page**
- If a stacktrace is provided in the error, include that too. **n/a**
- Any errors that appear in your browser's error console. **no**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). **yes**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database **no modifications were made**

**Comment by snipe** [comment]
I understand what you're asking for. We'll look into trying to implement this in an upcoming version.

**Comment by lravelo** [comment]
Hello!  I recently upgraded to v3.1 and noticed that this isn't working yet.  Just hoping you didn't forget about me :)

**Comment by snipe** [comment]
We have 400 other feature requests pending right now. No one has forgotten about anyone.
