### ISSUE TITLE
Create Asset model 500 error

### ISSUE THREAD

**Issue by bailantilles** [snipe/snipe-it#1901]
#### Expected Behavior (or desired behavior if a feature request)

Creating a new asset model on the asset model page.

-----

#### Actual Behavior

When creating a new asset model on the asset model page, I receive a 500 error.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version: (v2.1.0-55)
- OS: Red Hat Enterprise Linux Server release 6.5 (Santiago)
- Webserver: nginx/1.8.0
- install method: manual
- page: /hardware/models/create
- reproduceable on the demo: No
- Edited database: No

/app/storage/log:

[2016-03-30 16:16:35] production.ERROR: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'note' in 'field list'' in /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Connection$
Stack trace:
#0 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Connection.php(369): PDO->prepare('insert into `mo...')
#1 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Connection.php(617): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `mo...', Array)
#2 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `mo...', Array, Object(Closure))
#3 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `mo...', Array, Object(Closure))
#4 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `mo...', Array)
#5 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `mo...', Array)
#6 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `mo...', Array, 'id')
#7 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#8 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#9 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1580): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#10 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1580): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#11 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1550): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#12 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1456): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#13 /cdl/www/vhosts/itassets.cdl.ucf.edu/app/controllers/admin/ModelsController.php(139): Illuminate\Database\Eloquent\Model->save()
#14 [internal function]: Controllers\Admin\ModelsController->postCreate()
#15 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#16 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postCreate', Array)
#17 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\ModelsController), Object(Illuminate\Routing\Route), 'postCreate')
#18 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\\Adm...', 'postCreate$
#19 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#20 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#21 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#22 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#23 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#25 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#26 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#27 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#28 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#29 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#30 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#31 /cdl/www/vhosts/itassets.cdl.ucf.edu/public/index.php(49): Illuminate\Foundation\Application->run()
#32 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'note' in 'field list' (SQL: insert into `models` (`depreciation_id`, `eol`, `name`, `modelno`, `manufacturer_id`, `category_id`, `note`$
Stack trace:
#0 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('insert into `mo...', Array, Object(Closure))
#1 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('insert into `mo...', Array, Object(Closure))
#2 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Connection.php(327): Illuminate\Database\Connection->statement('insert into `mo...', Array)
#3 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(30): Illuminate\Database\Connection->insert('insert into `mo...', Array)
#4 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1910): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `mo...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(972): call_user_func_array(Array, Array)
#7 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1580): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1580): Illuminate\Database\Eloquent\Builder->insertGetId(Array, 'id')
#9 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1550): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1456): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /cdl/www/vhosts/itassets.cdl.ucf.edu/app/controllers/admin/ModelsController.php(139): Illuminate\Database\Eloquent\Model->save()
#12 [internal function]: Controllers\Admin\ModelsController->postCreate()
#13 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#14 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postCreate', Array)
#15 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\ModelsController), Object(Illuminate\Routing\Route), 'postCreate')
#16 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\\Adm...', 'postCreate$
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#19 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#21 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#24 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#25 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#26 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#27 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#28 /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#29 /cdl/www/vhosts/itassets.cdl.ucf.edu/public/index.php(49): Illuminate\Foundation\Application->run()
#30 {main} [] []

nginx log:

PHP message: PHP Fatal error:  require(): Failed opening required '/cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/swiftmailer/swiftmailer/lib/swift_required.php' (include_path='/cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/phpseclib/phpseclib/phpseclib:.:/usr/share/pear:/usr/share/php') in /cdl/www/vhosts/itassets.cdl.ucf.edu/vendor/composer/autoload_real.php on line 59" while reading response header from upstream, client: 10.171.155.44, server: itassets.cdl.ucf.edu, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "itassets.cdl.ucf.edu"

Page debug:

Illuminate \ Database \ QueryException (42S22)
HELP
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'note' in 'field list' (SQL: insert into `models` (`depreciation_id`, `eol`, `name`, `modelno`, `manufacturer_id`, `category_id`, `note`, `user_id`, `fieldset_id`, `updated_at`, `created_at`) values (0, 60, Surface Pro 4, , 34, 3, , 145, 7, 2016-03-30 16:23:46, 2016-03-30 16:23:46))

I have reinstalled from the master branch and get the same issue.

**Comment by snipe** [comment]
Do you actually have a `note` field in your `models` table? If not, I'm guessing something went wrong with your migration.

**Comment by bailantilles** [comment]
Thanks! I just figured that out after all the troubleshooting that I missed php artisan migrate.

**Comment by snipe** [comment]
Hah. No worries. Glad you got it sorted.
