### ISSUE TITLE
Problems with expiring assets

### ISSUE THREAD

**Issue by FSCHARR** [snipe/snipe-it#1906]
Hello, 

I tried some things to get an alert for an expiring asset, but neither the end of a Maintenances nor an expected Check In Date throws an alert.. 

What´s the problem?

**Comment by snipe** [comment]
We do not have alerts for that at this time. Just expiring assets and licenses.

**Comment by FSCHARR** [comment]
And what's the way to get an alert for an expiring asset?

**Comment by snipe** [comment]
http://docs.snipeitapp.com/manual/alerts.html

**Comment by FSCHARR** [comment]
Yeah, I configured already the alerts, but I wanted to know, how I have to create an asset in the Browser to get an alert?

**Comment by snipe** [comment]
Have a warranty that expires within 30 days, or a license that expires within 30 days.
