### ISSUE TITLE
Server Error: 500 (Internal Server Error) on the footer of the Licenses page

### ISSUE THREAD

**Issue by xycofryx** [snipe/snipe-it#1907]
#### Actual Behavior

Upon installing the new Snipe-it I have encountered the following error on the footer of "Licenses Page"

`Server Error: 500 (Internal Server Error)`

I immediately turned on the debug mode and got this error in the exceptions:

```
ob_get_clean(): failed to discard buffer of zlib output compression (0)
/srv/ams.panp.gov.ph/public/snipe-it-master/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php#44
ErrorException
```

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Snipe-IT v2.1.0-55
- Ubuntu Server 14.04
- Manual installation
- Server Error: 500 (Internal Server Error)
- Licenses
- No error messages during installation
- No edition done to the database manually

**Comment by snipe** [comment]
Are you able to disable zlib compression?
