### ISSUE TITLE
0 Month Depreciation

### ISSUE THREAD

**Issue by doogieconsulting** [snipe/snipe-it#1909]
I utilize depreciation for taxation purposes and have been using SnipeIt to track this quite well so far. Last year the Australia government introduced an immediate full depreciation of assets >$20,000. 

For this to work in Snipe-it i need to set Number of Months to 0.

-----

When setting Number of Months to 0 and pressing save it triggers an error " The months must be at least 1."

Although not a bug per-se it would be great for this limitation to be either disabled or set as a variable to specify a minimum number of months .

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - 2.1.0
- What OS and web server you're running Snipe-IT on - Debian 8 (Jessie)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - install.sh
- If you're getting an error in your browser, include that error - listed above
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - /admin/settings/depreciations/create
- If a stacktrace is provided in the error, include that too. - nope
- Any errors that appear in your browser's error console. - nope
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). - it is reproducable
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. - N/A
- Include what you've done so far in the installation, and if you got any error messages along the way. N/A
- Indicate whether or not you've manually edited any data directly in the database - No

**Comment by doogieconsulting** [comment]
thank you!

**Comment by HowDoIEvenIT** [comment]
Neco-ing this 9 years later, it appears this change has since been removed. Setting 0 months on a deprecation returns the error "The months field must be greater than 0." It would be great if this is restored, or when a device is broken before its depreciation period is up, we could overwrite that asset deprecation value to 0?
