### ISSUE TITLE
Single data volume in docker image

### ISSUE THREAD

**Issue by balous** [snipe/snipe-it#1911]
#### Expected Behavior (or desired behavior if a feature request)

When using snipe-it as docker image, it is desired to mount directories with persistent data (i.e. file uploads) as external volumes so that the data is retained over container removal (i.e. due to image upgrade). It would be more convenient to have just one volume for data and may be another for logs.

-----

#### Actual Behavior

- data are spread across several directories (private_uploads, public/uploads/*)
- logs are in two directories (apache, snipe-it)

This results in several mounts and pretty long command line. My idea is to symlink those directories to a single directory (/var/lib/snipeit ?) and mark it as volume.

BTW, I've looked into backup command implementation to get the list of directories that need to be persistent. I've found that three directories from public/uploads are zipped, but there is a fourth directory (assets) that is omitted - is not that a mistake?

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
Latest docker image

- What OS and web server you're running Snipe-IT on
That OS and web server in docker image.

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
docker

- If you're getting an error in your browser, include that error
No.

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
No page.

- If a stacktrace is provided in the error, include that too.
No stacktrace.

- Any errors that appear in your browser's error console.
No browser.

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
This is a suggestion.

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

- Include what you've done so far in the installation, and if you got any error messages along the way.

- Indicate whether or not you've manually edited any data directly in the database
No.

**Comment by balous** [comment]
I've prepared a patch for this (just data directories, no logs):

https://github.com/samepage-labs/snipe-it/commit/413e3ffd7ced6aa7aacc26147867d693ea1eade1

**Comment by snipe** [comment]
`public/assets` is just css, javascript, etc. Web assets, not Snipe-IT assets. That's why we don't include them in the backup.

**Comment by balous** [comment]
OK, this renders my patch a bit wrong. What about the idea?

**Comment by snipe** [comment]
Seems like a good plan to me, but @uberbrady is our resident docker nerd, so I'd like him to weigh in.

**Comment by uberbrady** [comment]
This is exactly what I wanted - see #1607 - I think your idea is great.

I think I volume-mount a directory for SSL/TLS support - it lets you mount a directory containing a key and a cert. So if we could instead have One Volume-Mount to Rule Them All, that would be perfect. So for SSL I made it so that you mount on top of `/etc/ssl/private`. If we could make that another symlink or directory in your volume, that'd be awesome.

So your idea seems great; if you can tweak it to skip `public/assets`, and make it integrate the TLS piece I had done already, I think it'll be great!

I'm so glad you did this; it's been something that's been bothering me for ages. Thank you!

**Comment by snipe** [comment]
![lsp-tears](https://cloud.githubusercontent.com/assets/197404/14202345/4244b8ee-f7ac-11e5-8874-203053cfafed.gif)

**Comment by uberbrady** [comment]
This was fixed with that previous merge.

**Comment by DawnTan0321** [comment]
@uberbrady My snipeit version is 3.6.4, sql version is 5.6. I use docker to put up the snipeit ,both snipeit & sql. I want to put up with -v parameter, so that I won't lose data when snipeit goes wrong. I wonder which directory I should relate, /var/www/html/storage/app/backups in sql?
