### ISSUE TITLE
wrong link in asset list

### ISSUE THREAD

**Issue by mkrve** [snipe/snipe-it#1918]
#### Expected Behavior (or desired behavior if a feature request)

Go to the asset list. in the "Status" column it shows the persons who have the assets. When you click on the person, it takes you to this persons detail page.

-----

#### Actual Behavior

I run Snipe-it in a subdirectory "snipe" and when i click on the person name, the sub directory isn't in the url. all other links in the asset list are correct. 
example :
current link is - http://www.mysite.com/admin/users/5/view

link should be - http://www.mysite.com/snipe/admin/users/5/view

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
**v2.1.0-55-g701c16f**
- What OS and web server you're running Snipe-IT on **debian - apache**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **manual installation**
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **page : hardware element : Status column**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. **incorrect link**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). **no, because the demo doesnt run in a sub directory**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database **no**

**Comment by ddreier** [comment]
What is the `url` parameter set to in app/config/production/app.php?

**Comment by mkrve** [comment]
'url' => 'http://www.mysite.com/snipe'

**Comment by ddreier** [comment]
Ok, looks good. Does the "Dashboard" link in the left-hand sidebar work as you'd expect?

**Comment by mkrve** [comment]
yes, the "Dashboard" link in the sidebar works as expected. All links seem to work normaly, just the link in the "status" column on the asset list page seems to be missing the "/snipe" subdir.

**Comment by mkrve** [comment]
hmmm... well... just hope this gets solved in a future release
