### ISSUE TITLE
New Install Error

### ISSUE THREAD

**Issue by jamcity** [snipe/snipe-it#1919]
#### Expected Behavior (or desired behavior if a feature request)

I have followed the step by step guide in setting up the environment and am running in to a problem when I get to this step: 
php artisan app:install --env=production

-----

#### Actual Behavior
I am getting a "Mcrypt PHP extension required." even when I have already enabled that extension.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - snipe-it 2.1.0
- What OS and web server you're running Snipe-IT on - AMPPS stack on OSX
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - CLI method as per guide on docs.snipeitapp.com
- If you're getting an error in your browser, include that error - no error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by ddreier** [comment]
Looks like this might be a solution: http://www.softaculous.com/board/index.php?as=tljkg4nbib1zjewailcjlw8ramiw1els&tid=4501&title=how_to_install_mcrypt_on_ampps#p19785

**Comment by brianjking** [comment]
@jamcity what does `php -m` show for list of compiled modules?

**Comment by jamcity** [comment]
hi @brianjking  it does not show mcrypt. I did check the mcrypt.so option in the ampps control panel but obviously it does not show up when i enter php -m

**Comment by jamcity** [comment]
Ok, basically it was a path issue. All one has to do is set the path like so:
export AMPPS_PHP=/Applications/AMPPS/php/bin 
followed by
export PATH="$AMPPS_PHP:$PATH"
and check it with 
which php
