### ISSUE TITLE
New install difficulty

### ISSUE THREAD

**Issue by Silentjay101** [snipe/snipe-it#1921]
#### Expected Behavior (or desired behavior if a feature request)

Site is supposed to load, bring up the log in page

-----

#### Actual Behavior

"Oh no!

Server Error: 500 (Internal Server Error)"

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running:  2.1.0
- What OS and web server you're running Snipe-IT on: Ubuntu 14.04LTS, Bitnami LAMP stack on an AWS EC2 Micro

- What method you used to install Snipe-IT: install.sh
- If you're getting an error in your browser: Error 500
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Typing in <Public IP> automatically directs me to http://<Public IP>/auth/signin
- Any errors that appear in your browser's error console:  None
- Include any additional information you can find in `app/storage/logs` and your webserver's logs:

Next exception 'ErrorException' with message 'SQLSTATE[28000] [1045] Access denied for user 'snipeit'@'localhost' (using password: YES) (View: /var/www/snipeit/app/views/backend/layouts/default.blade.php) (View: /var/www/snipeit/app/views/backend/layouts/default.blade.php)' in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:47
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/snipei...', Array)
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/var/www/snipei...', Array)
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#6 /var/www/snipeit/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/snipeit/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /var/www/snipeit/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []

- Indicate whether or not you've manually edited any data directly in the database: No

Sorry, I'm quite the novice at this - It took me hours to get to this point as it is :)

**Comment by ddreier** [comment]
Here's the problem: `Access denied for user 'snipeit'@'localhost'`

Looks like you either need to revisit the settings in app/config/production/database.php or the settings for your user in MySQL.

**Comment by Silentjay101** [comment]
I can take a peek at the settings in the database.php file, but how would I go about checking the settings on MySQL?  (Sorry).

**Comment by ddreier** [comment]
I don't know the SQL queries off hand to deal with MySQL users and permissions. If you have a tool like phpMyAdmin or HeidiSQL or MySQL Workbench (something like that) then they each provide GUIs for dealing with MySQL permissions.

**Comment by merid14** [comment]
@Silentjay101 You will need to set the snipeit user password to whatever you have in your `/app/config/production/database.php` file. 
`mysql -u root -p` (if you set one, otherwise it will be blank)
`GRANT ALL PRIVILEGES ON snipeit.* TO snipeit@localhost IDENTIFIED BY 'password';`

@snipe @ddreier This is kind of a bug in the install script, I've already fixed it in the new script. but we might want to make a note of the resolution.

**Comment by Silentjay101** [comment]
Argh - I wiped out the previous install, used the script to install.  I've diddled around and find myself in quite a quandary.  Sorry in advance...

This is what I see in the Apache2handler log file, accompanied by a new error message when I try to navigate to the server IP address:  "Whoops, looks like something went wrong."

I've checked and see that snipeit is still an SQL database.

Next exception 'ErrorException' with message 'SQLSTATE[42000] [1049] Unknown database 'snipeit' (View: /var/www/snipeit/app/views/backend/layouts/default.blade.php) (View: /var/www/snipeit/app/views/backend/layouts/default.blade.php)' in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:47
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/snipei...', Array)
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/var/www/snipei...', Array)
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#6 /var/www/snipeit/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/snipeit/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /var/www/snipeit/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []

**Comment by merid14** [comment]
@Silentjay101 if you hop on gitter we will be able to assist you faster. I'll still try here. look in your app.php file and see if there is a password in there.

**Comment by Silentjay101** [comment]
Resolved, thanks to some timely support from everyone.  The numerous self-caused problems included mysql not having the proper database selected, the wrong timezone specified, and needing to run "php artisan app:install --env=production" after the timezone oversight was corrected.
