### ISSUE TITLE
general.

### ISSUE THREAD

**Issue by mariomasa** [snipe/snipe-it#1923]
I installed snipe-it normally, but all graphic elements (texts) are preceded by " **.genera**l " prefix.
For example: general.software_licenses, general.dashboard, general.admin, and so on

Mario Andrade

**Comment by ddreier** [comment]
You need to provide all of the information that you deleted when you opened this issue. Also, screenshots would be most helpful.

**Comment by snipe** [comment]
My guess would be that you selected a language we don't support in your app.php, or you didn't copy over the language files.

**Comment by mariomasa** [comment]
SOLVED. I changed the value of locale from 'pr-PT' to '**pt-PT**' in app.php file.
C'os in app/lang folder there's no 'pr-PT' and 'pr-BR' folders, but 'pt-PT' and 'pt-BR' folders.

This error is because the website documentation (http://docs.snipeitapp.com/installation/configuration.html ) refers to ' pr-PT' and 'pr-BR' 

Please repair the documentation page
