### ISSUE TITLE
servcer inaccessible

### ISSUE THREAD

**Issue by thomasmosthaf** [snipe/snipe-it#1925]
To whom it may concern,

we are getting the following message when trying to logi at snipeit:

Whoops!
Server Error: 500 (Internal Server Error)
What does this mean?

Something went wrong on our servers while we were processing your request. We're really sorry about this, and will work hard to get this resolved as soon as possible.

Perhaps you would like to go to our home page?

When will this be repaired?

Cheers

Thomas 

#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Hey there - so, I don't really know what to do with this issue, since I have no information about your setup. If you can answer the questions above, that would be a big help. If you're not hosted with us, there is no issue to be repaired, it's a question of a misconfiguratioj on your end. If you are hosted with us, I at least need to know what account you are.

**Comment by thomasmosthaf** [comment]
Dear Servicedesk,

I purchased the monthly hosted solution (29,99.-Dollar), our url is: https://swka.snipeitapp.com/auth/signin, my user name is: thomas.mosthaf@sw-ka.de<mailto:thomas.mosthaf@sw-ka.de>.

I’ve been working in Germany for some days with my paid acoount, but since this week it does not work.
I even tried to connect me from my cell phone to assure that our network hasn’t got a problem, but it didn’t work either.

Since one week approx, I always get that „oops – something went wrong“.

We need so start working now and it would be very nice if you could help us. Can you help me or should I again write to Alison.

Best regards

Thomas

Von: snipe [mailto:notifications@github.com]
Gesendet: Mittwoch, 6. April 2016 11:09
An: snipe/snipe-it
Cc: Mosthaf, Thomas
Betreff: Re: [snipe/snipe-it] servcer inaccessible (#1925)


Hey there - so, I don't really know what to do with this issue, since I have no information about your setup. If you can answer the questions above, that would be a big help. If you're not hosted with us, there is no issue to be repaired, it's a question of a misconfiguratioj on your end. If you are hosted with us, I at least need to know what account you are.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/snipe/snipe-it/issues/1925#issuecomment-206242542>

Mit freundlichen Grüßen

i. A. Thomas Mosthaf
Leiter
Kommunikation / IT

Studierendenwerk Karlsruhe AöR
Adenauerring 7
76131 Karlsruhe
Tel.: +497216909-115
Fax: +497216909-118
E-Mail: Thomas.Mosthaf@sw-ka.de
Internet: www.sw-ka.de
USt-IdNr.: DE154654473
