### ISSUE TITLE
custom_fields folder missing from the en-GB admin folder

### ISSUE THREAD

**Issue by k-boy** [snipe/snipe-it#1929]
custom_fields folder is missing in snipe-it-2.1.0/app/lang/en-GB/admin/ .

Snipe-it v2.1.0 (https://github.com/snipe/snipe-it/archive/v2.1.0.tar.gz)

**Comment by snipe** [comment]
That's a known issue, and is fixed on master.

**Comment by k-boy** [comment]
thank you for the quick reply
