### ISSUE TITLE
Addtitional columns in asset table

### ISSUE THREAD

**Issue by coolboysh** [snipe/snipe-it#1930]
I want to change columns in asset table so can you please suggest me the easiest way to do it
??
and I want import my data from excel which we are currently using for asset management

**Comment by snipe** [comment]
> I want to change columns in asset table so can you please suggest me the easiest way to do it?

Could you be more specific with what you're trying to do?

> and I want import my data from excel which we are currently using for asset management

http://docs.snipeitapp.com/manual/importing-assets.html

**Comment by coolboysh** [comment]
Like i want to change Name of Column "Location Name" to "Site Name" and want to add one more column IP Address

**Comment by snipe** [comment]
You can create custom fields to handle additional fields you want to display, like IP address.

There is currently no good way to change the non-custom headers though, as any changes you make in the language file will be overwritten when you upgrade.

**Comment by coolboysh** [comment]
Thanks for the solution ,But now how can I import my excel sheet in these custom field

**Comment by snipe** [comment]
As noted in the documentation, custom fields cannot be imported at this time.

**Comment by coolboysh** [comment]
Even now we are getting Internal server 500 error while saving the data into these custom fields manually , for example I tried to do one but having error

**Comment by snipe** [comment]
Please provide us with the information requested at the Getting Help documentation: http://docs.snipeitapp.com/getting-help.html

**Comment by coolboysh** [comment]
Error -
Illuminate \ Database \ QueryException (42S22) 

HELP 












  
SQLSTATE[42S22]: Column not found: 1054 Unknown column '_snipeit_ip_address' in 'field list' (SQL: insert into `assets` (`model_id`, `_snipeit_ip_address`, `_snipeit_business`, `_snipeit_contact`, `_snipeit_lob`, `_snipeit_dns_record`, `_snipeit_location`, `_snipeit_other_notes`, `status_id`, `warranty_months`, `purchase_cost`, `purchase_date`, `assigned_to`, `supplier_id`, `requestable`, `rtd_location_id`, `name`, `serial`, `company_id`, `order_number`, `notes`, `asset_tag`, `user_id`, `archived`, `physical`, `depreciate`, `updated_at`, `created_at`) values (8, 12.12.12.12, snipe, cool, HPP, acgs.com, dallas, chkl, 1, , 0, , , 0, 0, , , , , , , check, 1, 0, 1, 0, 2016-04-07 19:33:05, 2016-04-07 19:33:05))

**Comment by coolboysh** [comment]
when I already created a custom field then why my sql is saying column not found
