### ISSUE TITLE
ldap integration

### ISSUE THREAD

**Issue by goth2boss** [snipe/snipe-it#1931]
Hello all,

I am trying to integrate ldap to our snipeit server. The problem happens when I attempt to synchronize. One problem I notice is when I attempt to install php-ldap I get this error

Error: php54w-common conflicts with php-common-5.3.3-46.el6_7.1.x86_64

when I run a php -v on my server

PHP 5.4.45 (cli) (built: Oct 16 2015 11:24:58) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

When I search online I get this suggestion

yum replace php-common --replace-with=php54w-common

This kills my snipeit server and I get a mycript error on my browser

#### Actual Behavior

Symfony\Component\Debug\Exception\FatalErrorException thrown with message "Call to undefined function Controllers\Admin\ldap_connect()"

Stacktrace:
#1 Symfony\Component\Debug\Exception\FatalErrorException in /var/lib/snipe-it/app/controllers/admin/UsersController.php:1200
#0 Illuminate\Exception\Handler:handleShutdown in <#unknown>:0

Open: /var/lib/snipe-it/app/controllers/admin/UsersController.php
        $ldap_result_first_name = Setting::getSettings()->ldap_fname_field;
 
        $ldap_result_active_flag = Setting::getSettings()->ldap_active_flag_field;
        $ldap_result_emp_num = Setting::getSettings()->ldap_emp_num_field;
        $ldap_result_email = Setting::getSettings()->ldap_email_field;
 
        // Connect to LDAP server
        $ldapconn = @ldap_connect($url);
 
        // Needed for AD

-----

CentOS release 6.7
Snipe-IT version	v2.0.5-pre-191-g948be5c
PHP Version	5.4.45
Laravel Version	4.2.17

Any help is greatly appreciated

**Comment by uberbrady** [comment]
maybe install php54w-ldap instead of just php-ldap?

It seems by your php -v that you're already on the php54 train.

try `rpm -qa|grep php ` to see for certain

**Comment by snipe** [comment]
Can you be more specific with respect to it "killing" your server? What actually happens?

@uberbrady Be careful there though - PHP cli and PHP are not the same thing, and that can cause more confusion. :(

Great GH handle, btw!

![it-crowd-goth-2-boss-o](https://cloud.githubusercontent.com/assets/197404/14367260/cdaa689c-fccb-11e5-8926-cc149f395ffb.gif)

**Comment by snipe** [comment]
Re-reading, killing your server means you're getting a fatal PHP error, it's not actually causing Apache to crash or anything like that, correct? (As devs and sysadmins, "killing" the server can mean a lot of different things.)

What server OS are you running? That was one of the questions you omitted above. I'm assuming CentOS or something? Have you looked at this for upgrading? https://www.mojowill.com/geek/howto-install-php-5-4-5-5-or-5-6-on-centos-6-and-centos-7/

**Comment by snipe** [comment]
(I would suggest php 5.6 if you can, since it's a minimum requirement for the next version of Snipe-IT)

**Comment by goth2boss** [comment]
Thanks for the quick response! The error on my browser after I run `yum replace php54w-common --replace-with=php-common`

Mcrypt PHP extension required

**Comment by uberbrady** [comment]
you may also need php54w-mcrypt if there is such a thing.

what does `rpm -qa|grep php` say?

**Comment by goth2boss** [comment]
results

php54w-cli-5.4.45-2.w6.x86_64
php54w-pgsql-5.4.45-2.w6.x86_64
php-tcpdf-dejavu-sans-fonts-6.2.11-1.el6.noarch
php54w-common-5.4.45-2.w6.x86_64
php54w-mbstring-5.4.45-2.w6.x86_64
php54w-pdo-5.4.45-2.w6.x86_64
php54w-mysql-5.4.45-2.w6.x86_64
php54w-tidy-5.4.45-2.w6.x86_64
php54w-mcrypt-5.4.45-2.w6.x86_64
php54w-5.4.45-2.w6.x86_64
php54w-pear-1.10.1-1.w6.noarch
php54w-xml-5.4.45-2.w6.x86_64
php54w-gd-5.4.45-2.w6.x86_64
php-php-gettext-1.0.11-12.el6.noarch
php54w-bcmath-5.4.45-2.w6.x86_64
php54w-process-5.4.45-2.w6.x86_64
php-tcpdf-6.2.11-1.el6.noarch
phpMyAdmin-4.0.10.15-1.el6.noarch

**Comment by uberbrady** [comment]
okay - you're probably on the php54w set of packages.

You'll need php54w-mcrypt and php54w-ldap.

looks like you already have mcrypt.

I'm curious about your web environment - is this apache, or nginx, are you running via fastcgi or something?

**Comment by snipe** [comment]
Any updates?

**Comment by goth2boss** [comment]
Hello All,

I've resolved the error on my OP by installing php54w-ldap. I'm currently trying to see why I get this error when attempting to synchronize my AD.

 Error: Could not bind to the LDAP server. Please check your LDAP server configuration in the LDAP config file. 
Error from LDAP Server: Invalid credentials
