### ISSUE TITLE
Please, Add KRW into currency

### ISSUE THREAD

**Issue by cloim** [snipe/snipe-it#1933]
#### Expected Behavior (or desired behavior if a feature request)

Can Select KRW in default currency

-----

#### Actual Behavior

KRW is missing in default currency

**Comment by snipe** [comment]
V3 will allow you to enter your own currency.

**Comment by cloim** [comment]
Sorry, I can't find where can i do it. I installed V3. There is no options to enter my own currency In Settings Page. It's a combobox.

**Comment by cloim** [comment]
Thanks! I confused I already installed V3.
