### ISSUE TITLE
Problem with ldap(freeipa) conection

### ISSUE THREAD

**Issue by xattab** [snipe/snipe-it#1934]
I have a problem with import user from ldap. Here is my config

![screenshot from 2016-04-08 16 13 25](https://cloud.githubusercontent.com/assets/2870527/14384620/afc4be5c-fda4-11e5-8a24-335e84ba0d25.png)

When i tried  synchronize i had this error:

![screenshot from 2016-04-08 16 15 49](https://cloud.githubusercontent.com/assets/2870527/14384678/fbb8df8c-fda4-11e5-8a55-cc14a270a2af.png)

What is the "location"  and where i need setup this ?
This is my /var/www/snipeit/app/config/production/ldap.php

`<?php

return array(

    /*
    |--------------------------------------------------------------------------
    | URL
    |--------------------------------------------------------------------------
    |
    | URL for the LDAP server. This should start with ldap://, for example:
    | ldap://ldap.yourserver.com
    |
    */
    'url' => "ldap://ldap.sf",

    /*
    |--------------------------------------------------------------------------
    | Username
    |--------------------------------------------------------------------------
    |
    | Username to use to connect authenticate to LDAP, for example:
    | cn=read-only-admin,dc=example,dc=com
    |
    */
	'username' => "uid=snipeit,cn=users,cn=accounts,dc=sf",

	/*
    |--------------------------------------------------------------------------
    | Password
    |--------------------------------------------------------------------------
    |
    | Password to use when authenticating to LDAP.
    |
    */
	'password' => "***********",

	/*
    |--------------------------------------------------------------------------
    | Basedn
    |--------------------------------------------------------------------------
    |
    | The base where the search for users will be executed, for example:
    | dc=example,dc=com
    |
    */
	'basedn'   => "dc=sf",

	/*
    |--------------------------------------------------------------------------
    | Filter
    |--------------------------------------------------------------------------
    |
    | The search filter for the LDAP query. This probably does not have to be
    | changed.
    |
    */
	'filter' => "&(cn=*)",

	/*
    |--------------------------------------------------------------------------
    | LDAP field names that will be retrieved to create a user.
    |
    | Using the username as an example:
    | If I set 'result.username' => 'my-org-username', the code will connect to
    | LDAP as follows (where $results[$i] represents a row in the LDAP query:
    | $username-to-insert-in-snipe-it = $results[$i]["my-org-username"][0]
    |
    |--------------------------------------------------------------------------
    |
    | The search filter for the LDAP query.
    | Note: all these fields are required, and they should all be lowercase.
    |
    */
    'result.username' => "uid",
    'result.last.name'  => "sn",
    'result.first.name' => "givenname",

    /*
    | These fields are optional as not all LDAP directories will have it.  If yours
    | does not have them, just leave these blank and the extra check will
    | be omitted.
    */
    'result.active.flag' => "",
    'result.emp.num'  => "",
    'result.email' => "",

    /*
    |--------------------------------------------------------------------------
    | LDAP filter query for authentication
    |--------------------------------------------------------------------------
    |
    | The LDAP query that we want to execute when authenticating a user. This
    | should not have to be changed.
    |
    */
    'authentication.filter.query' => "uid=",

    /*
    |--------------------------------------------------------------------------
    | LDAP Version
    |--------------------------------------------------------------------------
    |
    | Version of LDAP you are using.
    |
    */
    'version' => 3,

);
`
Os  Debian 8.4
Snipe-IT version 	v2.1.0-55-g701c16f
PHP Version 	5.6.19-0+deb8u1
Laravel Version 	4.2.17

**Comment by snipe** [comment]
2.1 doesnt use the ldap.php file, the values are stored in the DB. Check admin > settings.

**Comment by snipe** [comment]
But also, locations are in admin > locations.

**Comment by ddreier** [comment]
Your LDAP server setting is incorrect in Admin -> Settings. It should be ldap://ldap.sf or ldaps://ldap.sf not https://ldap.sf.

**Comment by xattab** [comment]
Thx. everything work
