### ISSUE TITLE
Feature Request - Asset Maintenance Scheduling

### ISSUE THREAD

**Issue by kissit** [snipe/snipe-it#1935]
#### Desired Behavior (or desired behavior if a feature request)

The current asset maintenances are pretty specific to maintenance contracts.  What we would like to see would be a more general type of maintenance for things such as patching, UPS testing, failover testing, etc.  At least for our use case these are all internal tasks and most often on a scheduled basis (monthly, quarterly, semi-annually, annually).  I could see this being included in the existing maintenances functionality as a separate type or a completely separate function similar to the existing maintenances.

The specific features we'd like to see would be:
- Maintenance creation similar to existing functionality.
- At least a start/end date like is currently there, but having the ability to set a scheduled basis (monthly, quarterly, semi-annually, annually) would be great.
- Email notifications when a maintenance is coming up.  This is important to us.
- Maintenance statuses would be nice.  For example, if I start a quarterly patch cycle I set it to in progress and then when finished I close the maintenance.
- The maintenance entries either being hidden once closed/expired, or the ability to manually delete them once completed.

**Comment by vr1994** [comment]
Is there a feature to send automatic email notifications for an upcoming maintenance?

**Comment by jaybbhb** [comment]
I'd add to have a report about upcoming scheduled maintenances for the upcoming X days/weeks/months.
That would be great!

**Comment by jbayfield** [comment]
We do an annual maintenance cycle - knowing when each asset is due and being notified, say, a month in advance would be amazing. 👍

**Comment by vaxo101** [comment]
@snipe By any chance is there an update for when / if this will be implemented?

**Comment by jbayfield** [comment]
Still interested in this feature - not quite stale yet. :)

**Comment by citykidz** [comment]
We would like to see this feature - exactly as described. We would like to schedule maintenance in advance and get a notification when this maintenance is due.  Thanks for this!

**Comment by gilesytheking** [comment]
Is this a feature that is likely to be released soon? Perhaps with V5? I have over 1000 assets registered on my snipe IT install, 90% of which are subject to regular checks, tests and inspections - PAT Testing, Visual Inspections, Upgrades, Cleaning, Servicing - the list goes on.

Im sure i speak for many snipe IT users that scheduled maintainaces is a key feature required for managing and maintaining our equipment.

**Comment by mortenfirst** [comment]
+1

**Comment by chrisLoPresti** [comment]
This feature has been requested for over 6 years, wondering if it will ever be implemented? I want to pull the plug and use Snipe-IT but I don't think we can without it!

**Comment by fctadena** [comment]
We need this feature.
