### ISSUE TITLE
Feature Request - Consumables Reporting

### ISSUE THREAD

**Issue by schlichter1** [snipe/snipe-it#1937]
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running : 2.1.0.41
- What OS and web server you're running Snipe-IT on : Ubuntu 14.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Install.sh

**Comment by nstratto** [comment]
+1

**Comment by redongh** [comment]
Am I correct assuming that consumable-reports are not available in a current version of snipe-it (at least I could not find it in the online-demo currently featuring v 5.4.35)?
Seeing other consumables related issues being worked (e.g. #1179 / #2534 ) on I wonder if this is really something that receives so little interest by the community as it seems.

I'd definitely also vote +1 on this!
@snipe: do you want to consider this issue for re-opening maybe?

**Comment by memcclellan** [comment]
I would also like to see some reporting for consumables, to be able to see cost per user per time period.

**Comment by kuritsynso** [comment]
+1 i would see it too

**Comment by unisharpUO** [comment]
+1

**Comment by francogp** [comment]
+1

**Comment by IrwanERL** [comment]
+1 i need this report

**Comment by mardoqueo** [comment]
This should be available. It's important.

**Comment by scottsettles** [comment]
+1 Consumable reports would be great.
