### ISSUE TITLE
ERR_CONNECTION_REFUSED for new install on Windows/IIS

### ISSUE THREAD

**Issue by CaptainNapalmSE** [snipe/snipe-it#1938]
#### Expected Behavior (or desired behavior if a feature request)

I've got a new install.  I'm by no means a web administrator, and I've got very limited knowledge of web servers in general, so I apologize if this is a repeat question inadvertently.  I did check the common issues section and, unless I missed it, I haven't seen it.  This may be PHP related, but I can't even get the Snipe IT page to come up.  I have gone through the documentation several times and I think I've done everything.

I confirmed PHP working on the default website.  This appears to be something regarding redirection, but I'm not sure what.
-----

#### Actual Behavior
When accessing the server/website, I get:

ERR_CONNECTION_REFUSED

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Running latest and greatest.
- Windows Server 2012 R2
- Manual Windows installation.
- ERR_CONNECTION_REFUSED
- Trying to get to home page for the application.
- No stacktrace.
- N/A
- N/A 
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- No errors during installation.
- No manually edited database info.

**Comment by ddreier** [comment]
I can't remember if this has made it into the docs or not. You need to disable one of the URL rewrite rules that redirects all requests to HTTPS. It's the only rewrite rule that has "https" in it, and I think that it's usually the first one.

**Comment by CaptainNapalmSE** [comment]
Thanks for the response!  It put me closer - I can at least hit the phpinfo file I created at the root of the website.  When I try to hit the index.php that's part of the website, though, it thinks for a second and then tells me the page can't be displayed.  This time, though, it doesn't say connection refused - it just tells me the website is wrong.  I'll keep digging.  At least I feel like there's progress. lol

**Comment by ddreier** [comment]
Are you trying to run Snipe-IT in a subdirectory, or as its own website? Do you have the Physical Path set to the `public` folder of the Snipe-IT instance?

**Comment by CaptainNapalmSE** [comment]
I ran through the configuration as it is in the documentation online.  The files are in wwwroot\snipe-it and I'm pointing to the "public" folder for the website.  I don't have anything else running on this server (it's something I built out from scratch so I could try to test out the application).  Sorry for the delayed response on my part.

**Comment by ddreier** [comment]
Can you post a screenshot of the Bindings for the IIS site?

**Comment by CaptainNapalmSE** [comment]
I've uploaded the site binding and the rewrite rules.  I had initially disabled the rewrite rule for https, but tried deleting it entirely trying to see if that was the issue.

![4-13-2016 11-19-55 am](https://cloud.githubusercontent.com/assets/18405138/14498937/5cf2a152-016a-11e6-8d4d-4f42e9872b77.jpg)

![4-13-2016 11-26-28 am](https://cloud.githubusercontent.com/assets/18405138/14499023/96128128-016a-11e6-871b-8122e34b2251.jpg)

**Comment by CaptainNapalmSE** [comment]
If it helps at all, this is the website address pointing to the phpinfo.php file I created as a PHP test.


![4-13-2016 11-30-18 am](https://cloud.githubusercontent.com/assets/18405138/14499185/3a58a9d8-016b-11e6-8052-2b1beaec1d26.jpg)

**Comment by ddreier** [comment]
So you created phpinfo.php in C:\inetpub\wwwroot\snipe-it\public?
Please post screenshots of the contents of C:\inetpub\wwwroot\snipe-it, C:\inetpub\wwwroot\snipe-it\public, the Basic Settings for the Site in IIS, and what happens when you just browse to http://assetinv.zic.pri.

Check the Snipe-IT log (C:\inetpub\wwwroot\snipe-it\app\storage\logs) for any errors, and look at the IIS access log to see what HTTP result codes are being returned.

**Comment by CaptainNapalmSE** [comment]
On phpinfo.php, yes, it's in the public folder.  Note, on the Basic Settings piece, I've tried it with pass-through (which was default) and I tried giving it credentials to use, both had the same results.  

Other requested screenshots below:

![4-13-2016 4-23-52 pm](https://cloud.githubusercontent.com/assets/18405138/14508163/2f587562-0194-11e6-9b7e-d0b4f7c0e833.jpg)
![4-13-2016 4-24-46 pm](https://cloud.githubusercontent.com/assets/18405138/14508179/44978698-0194-11e6-9344-0d3124b1433d.jpg)



![4-13-2016 4-21-26 pm](https://cloud.githubusercontent.com/assets/18405138/14508081/e33a08f8-0193-11e6-8277-a46cef07cef4.jpg)

**Comment by CaptainNapalmSE** [comment]
By the way, the only thing in the Snipe-IT logs folder is a .gitkeep file that's empty.  I'm not sure what else to do there, but I'm assuming that if there are no logs there then it's never hitting the actual application, right?

Are the IIS logs you're referring to the ones that are stored in the root logs folder for the site, or is there another log?  I apologize in advance for the question, but I'm just not sure - not a web guy, and I don't deal with it very often.  I do have logs in the inetpub\logs\logfiles folders, but none of them seem to have timestamps that correspond to anything in my reality.

Thanks again for your help in this.

**Comment by krazykenny** [comment]
i had this problem. It just seemed to want to redirect to https which I couldn't seem to disable.
The easiest solution in my case was to create a self-signed SSL certificate and bind it to the Snipe IT website in IIS. I'd suggest doing that.

**Comment by ddreier** [comment]
@CaptainNapalmSE if you notice the URL in the screenshot you uploaded, that browser is still trying to redirect to HTTPS. I guess that IIS was issuing permanent redirects from that URL Rewrite rule.

Try accessing the app from a browser that you haven't used yet. If that browser also gets redirected to HTTPS, then I'd recommend following @krazykenny's suggestion.

IIRC the timestamps in IIS logs are in UTC.

**Comment by CaptainNapalmSE** [comment]
@krazykenny  @ddreier 

Thank you both for your assistance.  Like I said before, I'm not much of a web guy - I've never been one to get involved with those aspects - but I got enough information to run with and that's what matters.  I was able to login and work with it doing the self-signed cert.  Now on to testing.

Thanks again!
