### ISSUE TITLE
Feature Request - EOL reporting

### ISSUE THREAD

**Issue by amorrisPRG** [snipe/snipe-it#1940]
#### Expected Behavior (or desired behavior if a feature request)

EOL reporting options and the ability to export within a selected timeframe. 
eg, EOL date between x and y 

v2.1.0-55

---
#### Actual Behavior

EOL only included in depreciation report

---
#### Please confirm you have done the following before posting your bug report:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by schannall** [comment]
Hi,
have a look at
https://github.com/snipe/snipe-it/issues/1461
(would be nice anyway )

sC
