### ISSUE TITLE
Complete User Deletion

### ISSUE THREAD

**Issue by Taliesin84** [snipe/snipe-it#1942]
Hello there,

I've recently installed Snipe-IT (master.zip, so I assume it's the version 2.1.0) on a CentOS 7, php 5.6. I performed the manual install.

Unfortunately, my first LDAP sync was incorrect and it ended up syncing all Active Directory users (~500). I bulk-deleted them and tried syncing again using a different query based on a Group (~200 users). 
This second query return all the users I wanted, but the sync Notes stated "exists", so I'm guessing it checks for previously deleted users and doesn't add them again to the user database. I'm not a big fan of having to restore about 200 users manually. 

I understand we admins can only soft-delete. Is it OK If I just delete all users directly from the MySQL database? Or should I just delete the whole database and start all over?

**Comment by snipe** [comment]
http://docs.snipeitapp.com/installation/manually-editing-data.html

**Comment by snipe** [comment]
(Also, v3 will have the opportunity to purge deleted items)

**Comment by Taliesin84** [comment]
That's good news. I'll wait for the new release.
