### ISSUE TITLE
500 Error when Uploading a file to asset

### ISSUE THREAD

**Issue by ESWBitto** [snipe/snipe-it#1945]
#### Expected Behavior (or desired behavior if a feature request)

After clicking upload and selecting a file then clicking save the document should be uploaded to the server.

-----

#### Actual Behavior

After selecting a file to upload and then clicking save I get a 500 server error message.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v2.1.0-55
- What OS and web server you're running Snipe-IT on
Centos/Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual Installation
- If you're getting an error in your browser, include that error
"Whoops! Server Error: 500 (Internal Server Error)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
/hardware/1399/edit
- If a stacktrace is provided in the error, include that too.
[2016-04-13 18:54:36] production.ERROR: exception 'Intervention\Image\Exception\NotReadableException' with message 'Unable to read image from file (/tmp/phpBAmNPk).' in /var/www/html/vendor/intervention/image/src/Intervention/Image/Gd/Decoder.php:20
Stack trace:
#0 /var/www/html/vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php(293): Intervention\Image\Gd\Decoder->initFromPath('/tmp/phpBAmNPk')
#1 /var/www/html/vendor/intervention/image/src/Intervention/Image/AbstractDriver.php(64): Intervention\Image\AbstractDecoder->init('/tmp/phpBAmNPk')
#2 /var/www/html/vendor/intervention/image/src/Intervention/Image/ImageManager.php(50): Intervention\Image\AbstractDriver->init('/tmp/phpBAmNPk')
#3 /var/www/html/vendor/intervention/image/src/Intervention/Image/ImageManagerStatic.php(57): Intervention\Image\ImageManager->make('/tmp/phpBAmNPk')
#4 /var/www/html/app/controllers/admin/AssetsController.php(387): Intervention\Image\ImageManagerStatic::make('/tmp/phpBAmNPk')
#5 [internal function]: Controllers\Admin\AssetsController->postEdit('1399')
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postEdit', Array)
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\AssetsController), Object(Illuminate\Routing\Route), 'postEdit')
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'postEdit')
#10 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('1399')
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#16 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#22 /var/www/html/public/index.php(49): Illuminate\Foundation\Application->run()
#23 {main} [] []

**Comment by snipe** [comment]
Looks like a permissions issue with your /tmp directory maybe

**Comment by ESWBitto** [comment]
The /tmp folder is owned by root with the default permission levels. That hasn't changed. In previous versions of snipeit I didn't have any issues with uploading files. I'm not sure how that has changed now.

**Comment by snipe** [comment]
That file upload is not intended for PDFs, only for images of the assets. You can use the files section of the asset view to add non-image files.
