### ISSUE TITLE
Unable to Login After LDAP Integration (AD or local account)

### ISSUE THREAD

**Issue by CaptainNapalmSE** [snipe/snipe-it#1948]
#### Expected Behavior (or desired behavior if a feature request)

I can get to the login page (https://assetinv.zic.pri/auth/signin), but I am unable to login.

-----

#### Actual Behavior

When I put in credentials, I'm not able to login.  It goes to a "Whoops!" internal server error 500 page.  This happened after I tried to do the LDAP integration.

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v2.1.0
- What OS and web server you're running Snipe-IT on - Windows Server 2012 R2 / IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual
- If you're getting an error in your browser, include that error - See screen shots.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Immediately following login.
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. 
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). - Appears to be specific to my install.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.  - See screenshots.
- Include what you've done so far in the installation, and if you got any error messages along the way. - Installed and was working to test after assistance getting it working.  Currently trying to get logged back in after configuring LDAP.
- Indicate whether or not you've manually edited any data directly in the database - Only entered data via the web interface.

![4-14-2016 1-53-55 pm](https://cloud.githubusercontent.com/assets/18405138/14539063/af1cdea6-024c-11e6-8e8b-3d2925409c08.jpg)
![4-14-2016 1-48-54 pm](https://cloud.githubusercontent.com/assets/18405138/14539068/b43b0552-024c-11e6-8083-1bd98b740d60.jpg)

**Comment by snipe** [comment]
Can you tell me what you have set as your LDAP settings?

**Comment by ddreier** [comment]
CMTrace, the best Windows log viewer that nobody has ever heard of. Except for SCCM admins.

**Comment by snipe** [comment]
?

No, I mean what server name, etc are you using in your Admin > Settings > LDAP? If you can't access that because you can't login, you'll have to check the database. Something was entered incorrectly, and it's choking on it.

**Comment by snipe** [comment]
Ugh. Sorry. I'm really off my game today. I didn't realize that was you replying, @ddreier. Clearly, I need caffeine.

**Comment by CaptainNapalmSE** [comment]
I'm not sure if there's more to do, but I did uncomment the php-ldap extension in the ini file.  I didn't see where there was more that needed to be done, so it's possible I'm missing some piece.  The account I'm trying to use to login now is a local, now-AD related account (it's the first account I created during the install process).

**Comment by CaptainNapalmSE** [comment]
Oops, added my comment late.  How do I check in the DB?  I can't get logged in at all.

**Comment by snipe** [comment]
@CaptainNapalmSE I need to know what settings you're trying to use for LDAP in the first place, so we can fix those. In your settings table, turn LDAP off (`ldap_enabled` should be 0). Do you have access to the mysql database?

**Comment by CaptainNapalmSE** [comment]
@ddreier  - and yes, CMtrace is the best.  I mentioned in the other post I'm not a web guy.  Why they have their SCCM admin working on web type stuff is beyond me, but at least I'm learning something.  lol

**Comment by CaptainNapalmSE** [comment]
@snipe  - Yes, it's running on the same test server I built for the main application.  I'm trying to check it out now.

**Comment by CaptainNapalmSE** [comment]
@snipe - Set ldap_enabled to 0 and I could log in again.  What's the best way to test LDAP to verify?  I think I fixed the problem, but I don't want to logout again if I have to tweak something in the DB again to fix.

**Comment by snipe** [comment]
Can you show me your LDAP settings, so I can take a look at them? That's not just a failure to login, that's a hard error, which usually means something more obvious is wrong in the settings.

**Comment by CaptainNapalmSE** [comment]
I had lapd:// instead of ldap:// originally (fumble-fingered it).  I fixed that, but I'm not sure how to test in general.  Should a user be able to use their AD credentials to login to the system, or do I have to import users as local and generate them a password?

The settings are here:

![4-14-2016 3-22-38 pm](https://cloud.githubusercontent.com/assets/18405138/14540817/03ed0ffc-0255-11e6-995b-c51b8c2ff2fa.jpg)

**Comment by snipe** [comment]
Well, the easiest way to test will be to import them. If LDAP can connect, it will import (or at least connect) correctly.

**Comment by ddreier** [comment]
Username field should be just `samaccountname` and the "LDAP Authentication query" should be `samaccountname=` . Also, Active Directory doesn't have an active flag so I'd leave that blank.

**Comment by CaptainNapalmSE** [comment]
Cool, it looks like it's working.  It syncs, anyhow.  Is there a way to get it to let you select what to import, or does it pull in whatever the base bind DN is and every user it can find related to it that?  I set it to a smaller OU for testing purposes, but if I set it to the base of the domain, is there a configuration that allows me to point to a few areas?  I'm not looking for how-to, just that it exists or doesn't.  I'll take it from there.

Thank you both, again, for your time!

**Comment by ddreier** [comment]
Depends on your willingness to fight with LDAP queries. Here's mine, which only returns not-disabled user accounts:
```
&(objectcategory=person)(objectclass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2))
```

(Note that Snipe-IT puts the outermost parenthesis on, so you don't need to)

**Comment by snipe** [comment]
@ddreier One of these days, I'm going to have to ask you to write up some more in-depth docs on your LDAP configs. 

![adventure_time_little_dude](https://cloud.githubusercontent.com/assets/197404/14546907/86f35e76-025d-11e6-8655-074afd785a42.gif)

**Comment by snipe** [comment]
FYI, I just added a utility in v3 to disable LDAP via command line in case people end up locking themselves out. I'll add some better testing stuff for LDAP down the line, but at least this will let you disable LDAP temporarily if it gets donked up.
