### ISSUE TITLE
Unable to un suspend user

### ISSUE THREAD

**Issue by joellobo1234** [snipe/snipe-it#1951]
Un suspend user option is not working
-----

Admin is getting a notification saying "Insufficient Permissions"

**Comment by snipe** [comment]
What are the permissions on the user who is trying to do the unsuspending? Also, do you have full company support enabled?

**Comment by snipe** [comment]
Additionally, please provide us with the information requested at the Getting Help documentation: http://docs.snipeitapp.com/getting-help.html. (There was a reason we have those questions in the ticket template.)
