### ISSUE TITLE
Trouble with the SnipeIT in windows 7 using localhost Wamp.

### ISSUE THREAD

**Issue by alutrolac** [snipe/snipe-it#1952]
Hi Snipe , show me how to install snipe it in my system , teach me step by steps , it so very difficult
i just only install Wamp 3.0, composer . its running.
and the next step i can not install.
thank you so much.

**Comment by snipe** [comment]
The steps are explained in the documentation. If you're having an issue, explain where yo're having the problem.

**Comment by alutrolac** [comment]
Hi snipe, can you upload video to youtube, that way to easy install.

**Comment by snipe** [comment]
@alutrolac I don't have the time to create a video just for you. The steps are explained in the documentation. If you're having an issue, explain where you're having the problem.

**Comment by alutrolac** [comment]
<a href="https://uphinhnhanh.com/view-67402_12_05_2016_11_46_37_AM.png" target="_blank"><img src="https://uphinhnhanh.com/images/67402_12_05_2016_11_46_37_AM_tn.jpg" alt="Up hình, up ảnh tại website Up hinh, up anh, up hinh nhanh, up hinh anh, up hinh online, up anh nhanh, up hinh len dien dan, up hinh len web, up hinh dep, up anh sieu toc"></a>

this is my trouble , Snipe. help me

**Comment by snipe** [comment]
Please provide us with the information requested at the Getting Help documentation: http://docs.snipeitapp.com/getting-help.html
