### ISSUE TITLE
V3 Testing - No Search Option within Locations

### ISSUE THREAD

**Issue by veen1981** [snipe/snipe-it#1955]
I just started testing v3 in a VM, everything looks amazing! The only thing I have come across is when you access locations via the Admin menu > locations > specific location... there is no search option for users or assets here. Could this be added?

![capture](https://cloud.githubusercontent.com/assets/14188055/14599348/cd841014-0524-11e6-8f52-db11888d7620.JPG)

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- v3.0.0-dev
- Centos 7 - 1511
- Upgraded snipe-it from v2.*
- If you're getting an error in your browser, include that error
- https://localhost/admin/settings/locations/2/view

**Comment by snipe** [comment]
That can be added, but it won't make it into v3.

**Comment by snipe** [comment]
Unfortunately this is a little harder than it appears, since a location can be associated in two different ways, either through the user an asset is checked out to OR the default Ready to Deploy location.

For example:

Alison lives in San Diego. She receives a laptop that's normally kept in LA. The asset's default RTD location is still LA, but the user's location (when provided) trumps default location, since it is typically more specific to that particular checkout. 

It's not impossible, but it's not the quick change I wish it was. We'll try to get to it soon.

**Comment by snipe** [comment]
Okay, I just pushed up something I *think* should work, but if you're willing to pull down the latest from v3 and test, that would be a big help. I'm very sleepy and cannot brain today.

![morning struggle](https://cloud.githubusercontent.com/assets/197404/14662623/cc054c28-066c-11e6-8cfc-97e2a3982299.gif)

**Comment by veen1981** [comment]
Coffee does the brain good! 

Just pulled down v3. Everything is working great in my VM! I performed searches in multiple locations where assets are assigned both as a default location and inherited by who they are checked out to. Searched for assets that were not in that location, result came back as expected with nothing. Everything is working great on my end! Thank you for getting on this quickly! I think you can close this! Hope you got some sleep!

On a side note... I would like to get some of my other admins testing, and noticed that rights groups have not been added yet, so all they are seeing is the default request-able assets view, even though I restored the database with a backup from our production server. The permissions tab under users still says permission stuff goes here. Not knowing where you are with dev and what is supposed to be there and what is not... Is this something that will be added soon? I am also happy to keep testing as you develop, I've got v3 installed on a VM at home, at work, and on a test server at work! :) Thanks for all you do!

**Comment by snipe** [comment]
Awesome to hear! Yes, permissions tab is next on the list, so expect that to be working soon!
