### ISSUE TITLE
Customizable side bar with custom saved queries

### ISSUE THREAD

**Issue by ilfrigorifero** [snipe/snipe-it#1956]
#### Actual Behavior

Fixed entries / queries (basic)

---
#### Please confirm you have done the following before posting your bug report:
- [X ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running
  Most recent (checked for updates last week)
- What OS and web server you're running Snipe-IT on
  Windows Server 2012, IIS 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  Composer, rest manual according to documentation

**Comment by snipe** [comment]
Can you be more specific for what you're looking for?

**Comment by ilfrigorifero** [comment]
Hi, sorry for the delay, I was on vacation :)
Well currently, there are fixed entried in the menu on the left so when I click on "Assets", I can navigate them using predefined submenus.
What I'd like to be able to do is to have a certain location or status etc. pinned to that menu to quickly navigate to all entries matching that status/location/... 

The assets being managed are currently 1) local assets used by employees and 2) servers installed at a datacenter. For the latter, I need to track harddrives, power supplies etc. and be able to provide a quick overview of what's currently at the datacenter as well as (ideally) a weekly report on what's happened in the datacenter (which I've mentioned in a feature request, so only the former is relevant to this thread).
Regards,
Martin

**Comment by ilfrigorifero** [comment]
*bump*
Just wanted to bother you guys again ;)
Do you happen to have an update for me on how I might be able to accomplish this?
Best wishes and thanks in advance.

**Comment by snipe** [comment]
You would have to edit the layout blade, and any changes you made would be blown out when you upgrade.

**Comment by ilfrigorifero** [comment]
From what I understand, I'd need to modify the default.blade.php a tad and add a line analogue to this line:
`<li><a href="{{ URL::to('hardware?status=Undeployable') }}" {!! (Request::query('status') == 'Undeployable' ? ' class="active"' : '') !!} >@lang('general.undeployable')</a></li>`

But I would have to query for location instead of status. Now just replacing "status" by "location" and "undeployable" by "datacenter" doesn't work, of course... :smile: 
Could you help me out? 

Btw. Nice new look in alpha2!

**Comment by dmeltzer** [comment]
Hi @ilfrigorifero,

While this isn't terribly hard to modify for your needs, I think the underlying query you're trying to call here is something that ties into the extended api that's kind of in discussion.

Are you able to stop by the snipe-it gitter? http://gitter.im/snipe/snipe-it, I can point you in the right direction for the short term to accomplish what you want, and maybe get a better idea of the long term possibilities.
