### ISSUE TITLE
Weekly Reports

### ISSUE THREAD

**Issue by ilfrigorifero** [snipe/snipe-it#1957]
#### Expected Behavior (or desired behavior if a feature request)

Snipe IT can generate automatic reports that are customizable

---
#### Actual Behavior

Reports are all manual

---
#### Please confirm you have done the following before posting your bug report:
- [ X] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running
  2.1.0
- What OS and web server you're running Snipe-IT on
  Windows Server 2012 / IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  Manual + Composer

What I'd like (need, actually) to do is to generate a weekly report of recent activities (new assets, changed status, changed location). I would be absolutely content if you'd be able to paste me a powershell script or something that can do this ;)

**Comment by erenustun** [comment]
Hi all! Are there any updates on this feature requests? @snipe

**Comment by sedgwick** [comment]
I would love this feature to be able to have an activity report emailed weekly. @snipe

**Comment by GamingSanctum** [comment]
Bump. I wrote a powershell script that takes my chromebook inventory report from SnipeIT and applies changes to specified fields in the Google Admin Console via GAM. I would LOVE if I could automate the .csv report so I do not have to manually run a report before running my script.
