### ISSUE TITLE
Warranty status in maintenance

### ISSUE THREAD

**Issue by D2nnyim** [snipe/snipe-it#1958]
We want to add a maintanance for a device; it is being repaired under warranty.
[http://s4.postimg.org/3roaovh31/warranty2.png](url)
When we press save, it is repaired "out-of-warranty"
[http://s4.postimg.org/nhtjy17wd/warranty1.png](url)

**Comment by adam820** [comment]
If it's being repaired under warranty, you'd want to add the checkbox "Warranty Improvement", to specify that this maintenance (repair, upgrade, etc.) is happening as part of a warranty plan. The "Not Warranty" indicator is correctly showing that the box wasn't checked, thus indicating that the repair that was done as an independent action and not part of warranty.

If you edit that maintenance and check the box, that should fix your issue.
