### ISSUE TITLE
Trying to setting up Snipe-IT

### ISSUE THREAD

**Issue by JulienAerts** [snipe/snipe-it#196]
Hi , 

I'm trying to test your software , i'm on IIS/PHP/mysql . 

I follow the guide post by @madd15 .

When a load the application , it's always giving me an 500 error. 

Thank you for your support , hopefully i will be able to make it work .

**Comment by douxlagithub** [comment]
@sinpe very smart. I did your advice on @jagafirst  then it works great.... thanks

**Comment by readBD** [comment]
Hi snipe...I'm facing below error technical problem.. would you help me about your product install & configuration. My systems version is : Centos 6.7,
Be Noted: i have already configure above your suggested configuration changes.
Error sample:

ErrorException (E_WARNING)
HELP
mcrypt_encrypt(): Size of key is too large for this algorithm

Open: /var/www/html/assets/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php
	 * @param  string  $iv
	 * @return string
	 */
	protected function padAndMcrypt($value, $iv)
	{
		$value = $this->addPadding(serialize($value));
 
		return mcrypt_encrypt($this->cipher, $this->key, $value, $this->mode, $iv);
	}

**Comment by snipe** [comment]
http://docs.snipeitapp.com/common-issues.html#error-message-mcrypt_encrypt-size-of-key-is-too-large-for-this-algorithm

**Comment by snipe** [comment]
(Make it exactly 32 characters)

**Comment by readBD** [comment]
Dear Snipe.
At present configure only 24 characters but same problem showing

**Comment by snipe** [comment]
Make it exactly 32 character

**Comment by readBD** [comment]
Same problem

**Comment by snipe** [comment]
Can you show me that line in your config? (You should change it later once we've sorted this.)

**Comment by snipe** [comment]
(run `php artisan key:generate` and paste that value into the key)

**Comment by snipe** [comment]
Also, can you please show us the information in your `app/storage/logs`?

**Comment by readBD** [comment]
[2015-08-26 13:05:41] local.ERROR: exception 'ErrorException' with message 'mcrypt_encrypt(): Size of key is too large for this algorithm' in /var/www/html/assets/vend$
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'mcrypt_encrypt(...', '/var/www/html/a...', 78, Array)
#1 /var/www/html/assets/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(78): mcrypt_encrypt('rijndael-256', 'Change_this_key...', 's:40:"62863d178...'$
#2 /var/www/html/assets/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(57): Illuminate\Encryption\Encrypter->padAndMcrypt('62863d1783a60e8...', '\x89$
#3 /var/www/html/assets/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(118): Illuminate\Encryption\Encrypter->encrypt('62863d1783a60e8...')
#4 /var/www/html/assets/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Guard->encrypt(Object(Illuminate\Http\RedirectResponse))
#5 /var/www/html/assets/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#6 /var/www/html/assets/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#7 /var/www/html/assets/public/index.php(49): Illuminate\Foundation\Application->run()
#8 {main} [] []



Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'migrations' already exists (SQL: crea$
Stack trace:
#0 /var/www/html/assets/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('create table `m...', Ar$
#1 /var/www/html/assets/vendor/laravel/framework/src/Illuminate/Database/Connection.php(370): Illuminate\Database\Connection->run('create table `m...', Array, Object(C$
#2 /var/www/html/assets/vendor/laravel/framework/src/Illuminate/Database/Schema/Blueprint.php(63): Illuminate\Database\Connection->statement('create table `m...')
#3 /var/www/html/assets/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(169): Illuminate\Database\Schema\Blueprint->build(Object(Illuminate\Databas$
#4 /var/www/html/assets/vendor/laravel/framework/src/Illuminate/Database/Schema/Builder.php(112): Illuminate\Database\Schema\Builder->build(Object(Illuminate\Database\$
#5 /var/www/html/assets/vendor/laravel/framework/src/Illuminate/Database/Migrations/DatabaseMigrationRepository.php(125): Illuminate\Database\Schema\Builder->create('m$
#6 /var/www/html/assets/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/InstallCommand.php(52): Illuminate\Database\Migrations\DatabaseMigrationRep$
#7 /var/www/html/assets/vendor/laravel/framework/src/Illuminate/Console/Command.php(112): Illuminate\Database\Console\Migrations\InstallCommand->fire()
#8 /var/www/html/assets/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console$
#9 /var/www/html/assets/vendor/laravel/framework/src/Illuminate/Console/Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Conso$
#10 /var/www/html/assets/vendor/laravel/framework/src/Illuminate/Console/Command.php(128): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\Array$
#11 /var/www/html/assets/app/commands/AppCommand.php(90): Illuminate\Console\Command->call('migrate:install')
#12 /var/www/html/assets/vendor/laravel/framework/src/Illuminate/Console/Command.php(112): AppCommand->fire()
#13 /var/www/html/assets/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Consol$
#14 /var/www/html/assets/vendor/laravel/framework/src/Illuminate/Console/Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Cons$
#15 /var/www/html/assets/vendor/symfony/console/Symfony/Component/Console/Application.php(889): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\$
#16 /var/www/html/assets/vendor/symfony/console/Symfony/Component/Console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(AppCommand),$
#17 /var/www/html/assets/vendor/symfony/console/Symfony/Component/Console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\C$
#18 /var/www/html/assets/artisan(59): Symfony\Component\Console\Application->run()
#19 {main} [] []

**Comment by snipe** [comment]
Which config file are you editing with the 32-character key?

**Comment by readBD** [comment]
app/config/production/app.php

'key' => 'asdfghjklpoiuytrewqzxcvbnm,kjhgy',

**Comment by snipe** [comment]
Your error logs are showing that you're running this in local mode though. Editing the production config a won't have any any effect. Either switch your all to production mode or edit the `app/config/local/app.php` file instead.
