### ISSUE TITLE
Feature Request: Form Element Variety

### ISSUE THREAD

**Issue by Giantdhk** [snipe/snipe-it#1960]
Would be useful to have some other types of "form elements" available when creating custom fields. Specifically, a simple checkbox form would be a nice addition: active = Yes, inactive = no. 

Use Case: I'd like to track if users need or already have accounts such as Email, Active Directory, Jira, Client VPN Access, etc. and simply indicating yes or no via a checkbox and having that information be sortable or reportable would be helpful. In this case, the username would be the same for all of the accounts tied to an individual.

**Comment by snipe** [comment]
That's always been on the list of things to do, we just haven't gotten around to doing it yet.

**Comment by snipe** [comment]
Upcoming v3 does at least offer more validation options, which is a start.

**Comment by henryp007** [comment]
This would be super useful if you could do it ! thanks for the project by the way - its awesome :-)

**Comment by reverendseverin** [comment]
Still would be a great feature.

**Comment by Oz-el-Ruso** [comment]
I would also need checkboxes as custom field option. Please implement. Still missing in v4.9.3.
