### ISSUE TITLE
Unable to attach documents to an asset

### ISSUE THREAD

**Issue by calessio** [snipe/snipe-it#1962]
#### Expected Behavior (or desired behavior if a feature request)

PDF successfully attached to a New Asset

-----

#### Actual Behavior

I'm in the "New Asset" form and the only button I see to attach a document is "Upload Image".
If I use it to upload a PDF, I get an Error 500.
It seems it accepts only images.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
 	v2.1.0-55-g701c16f 

- What OS and web server you're running Snipe-IT on
        Ubuntu 14.04 - Apache 2.4.7

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
         manual

- If you're getting an error in your browser, include that error
        Oh no!
        Server Error: 500 (Internal Server Error)

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
         hardware/create

- If a stacktrace is provided in the error, include that too.
Intervention \ Image \ Exception \ NotReadableException

Unable to read image from file (/tmp/phpIqb8fA).
Open: /var/www/html/snipe-it/vendor/intervention/image/src/Intervention/Image/Gd/Decoder.php

         * @return \Intervention\Image\Image
         */
        public function initFromPath($path)
        {
            $info = @getimagesize($path);
     
            if ($info === false) {
                throw new \Intervention\Image\Exception\NotReadableException(
                    "Unable to read image from file ({$path})."
                );

GET Data empty 

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
           yes

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
[2016-04-19 10:36:51] production.ERROR: exception 'Intervention\Image\Exception\NotReadableException' with message 'Unable to read image from file (/tmp/phpIqb8fA).' in /var/www/html/snipe-it/vendor/intervention/image/src/Intervention/Image/Gd/Decoder.php:20
Stack trace:
#0 /var/www/html/snipe-it/vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php(293): Intervention\Image\Gd\Decoder->initFromPath('/tmp/phpIqb8fA')
#1 /var/www/html/snipe-it/vendor/intervention/image/src/Intervention/Image/AbstractDriver.php(64): Intervention\Image\AbstractDecoder->init('/tmp/phpIqb8fA')
#2 /var/www/html/snipe-it/vendor/intervention/image/src/Intervention/Image/ImageManager.php(50): Intervention\Image\AbstractDriver->init('/tmp/phpIqb8fA')
#3 /var/www/html/snipe-it/vendor/intervention/image/src/Intervention/Image/ImageManagerStatic.php(57): Intervention\Image\ImageManager->make('/tmp/phpIqb8fA')
#4 /var/www/html/snipe-it/app/controllers/admin/AssetsController.php(201): Intervention\Image\ImageManagerStatic::make('/tmp/phpIqb8fA')
#5 [internal function]: Controllers\Admin\AssetsController->postCreate()
#6 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#7 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postCreate', Array)
#8 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\AssetsController), Object(Illuminate\Routing\Route), 'postCreate')
#9 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'postCreate')
#10 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#11 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#12 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#14 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#15 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#16 /var/www/html/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#19 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/html/snipe-it/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#21 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#22 /var/www/html/snipe-it/public/index.php(49): Illuminate\Foundation\Application->run()
#23 {main} [] []

- Indicate whether or not you've manually edited any data directly in the database
           nope

**Comment by snipe** [comment]
That field is not intended for PDFs, just for images of the asset. You can add other files once the asset has been created.

**Comment by calessio** [comment]
Thank you for the prompt response!

**Comment by VinnyPolar** [comment]
I'm not able to attach a PDF in the additional files field
