### ISSUE TITLE
Error creating new asset from within Asset Models

### ISSUE THREAD

**Issue by Aaranaw** [snipe/snipe-it#1963]
#### Expected Behavior (or desired behavior if a feature request)

Should show the create new asset page with custom fieldset assigned to that asset.

-----

#### Actual Behavior

Shows the create new asset page however it is missing the custom fieldset, throws an error 
"Ouch. Server Error: 500 (Internal Server Error)"

However choosing to create a new asset from the "Deployed" to the "List All" pages will work fine.

The url difference between the two are as follows

From the Deployed menu "/hardware/create"
From the Model menu /hardware/create/35
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
 (v2.1.0)
- What OS and web server you're running Snipe-IT on
Chrome/Firefox/Safari
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual installation,
- If you're getting an error in your browser, include that error
"Ouch. Server Error: 500 (Internal Server Error)"
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
/hardware/models/35/view (Actions button>Create Asset)
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
Works fine on demo

**Comment by snipe** [comment]
Need your stack trace (which you would see if you had enabled debug, instead of the "Ouch" error), and any browser console errors you're getting.

**Comment by Aaranaw** [comment]
/disks/www/sci-invent/app/controllers/admin/AssetsController.php
`        //attempt to validate
        $input=Input::all();
 
        $rules=$asset->validationRules();
        if($asset->model->fieldset)
        {
          foreach($asset->model->fieldset->fields AS $field) {
            $input[$field->db_column_name()]=$input['fields'][$field->db_column_name()];
            $asset->{$field->db_column_name()}=$input[$field->db_column_name()];
          }`
no console errors

**Comment by snipe** [comment]
That's not a stack trace, that's just code. I need a stack trace. At the very least, provide a dump of your error logs, per the Getting Help documentation.

**Comment by snipe** [comment]
(I'd also be surprised if there were no console errors. This usually happens when your url in `app/config/production/app.php` doesn't match your actual URL, so the ajax request for custom fields can't fire. That shows up as a browser error.)

**Comment by Aaranaw** [comment]
Please explain what a stacktrace is as the documentation does not go into any more detail than "If a stacktrace is provided in the error, include that too."

Thanks.

**Comment by snipe** [comment]
http://docs.snipeitapp.com/getting-help.html

> If you get an "Oops!" or "Whoops!" message in the browser when you hit a specific page, that means debug is set to false. Set it to true, and reload for detailed errors.

**Comment by snipe** [comment]
Please tell me what you have set as your url in `app/config/production/app.php`, and what your actual Snipe-IT installation url is.

**Comment by fyberoptik** [comment]
Hi Snipe
Just had a look at this for Aaran, I believe this is what you are looking for?

Thanks!
```
19. ErrorException
…/­app/­controllers/­admin/­AssetsController.php113
18. Illuminate\Exception\Handler handleError
…/­app/­controllers/­admin/­AssetsController.php113
17. Controllers\Admin\AssetsController postCreate
<#unknown>0
16. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Controller.php231
15. Illuminate\Routing\Controller callAction
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­ControllerDispatcher.php93
14. Illuminate\Routing\ControllerDispatcher call
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­ControllerDispatcher.php62
13. Illuminate\Routing\ControllerDispatcher dispatch
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php967
12. Illuminate\Routing\Router Illuminate\Routing\{closure}
<#unknown>0
11. call_user_func_array
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Route.php109
10. Illuminate\Routing\Route run
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php1033
9. Illuminate\Routing\Router dispatchToRoute
…/­vendor/­laravel/­framework/­src/­Illuminate/­Routing/­Router.php1001
8. Illuminate\Routing\Router dispatch
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Application.php775
7. Illuminate\Foundation\Application dispatch
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Application.php745
6. Illuminate\Foundation\Application handle
…/­vendor/­barryvdh/­laravel-debugbar/­src/­Middleware/­Stack.php34
5. Barryvdh\Debugbar\Middleware\Stack handle
…/­vendor/­laravel/­framework/­src/­Illuminate/­Session/­Middleware.php72
4. Illuminate\Session\Middleware handle
…/­vendor/­laravel/­framework/­src/­Illuminate/­Cookie/­Queue.php47
3. Illuminate\Cookie\Queue handle
…/­vendor/­laravel/­framework/­src/­Illuminate/­Cookie/­Guard.php51
2. Illuminate\Cookie\Guard handle
…/­vendor/­stack/­builder/­src/­Stack/­StackedHttpKernel.php23
1. Stack\StackedHttpKernel handle
…/­vendor/­laravel/­framework/­src/­Illuminate/­Foundation/­Application.php641
```

**Comment by snipe** [comment]
@fyberoptik that looks like only a partial though

**Comment by snipe** [comment]
@fyberoptik that looks better.

Please tell me what you have set as your url in `app/config/production/app.php`, and what your actual Snipe-IT installation url is.

**Comment by fyberoptik** [comment]
app.php 
'url' => 'https://sci-invent.lboro.ac.uk',

When you say the installation URL, do you mean the address we use to access the site. If so, this is the same as the URL declared in the app.php file. I didn't originally set this site up I'm afraid I'm not familiar with the structure and layout.

**Comment by snipe** [comment]
Yes, that's what I mean, thanks. I see that's htttps, not http. Are you accessing the install through your browser via https every time? It's a common mistake to not change that URL to http if you're not running SSL.

**Comment by fyberoptik** [comment]
We have apache rules forcing all traffic to https, so I'm unsure what is happening there.

**Comment by snipe** [comment]
Can you open up the developer console in your browser and tell me if you get any errors on the form page right before you get the error?

**Comment by snipe** [comment]
(Try selecting multiple models from the list, etc. it will do an Ajax call on each model to check for custom fields)

**Comment by fyberoptik** [comment]
Console isn't showing any issues, the screen shot shows the difference in the fields that are loading using the different URL's.

Just to clarify, this seems to be a two part problem or two separate problems. Firstly, when using the /hardware/create/35 url, the pre-populated fields don't load correctly. Secondly, when pressing the Save button this is when we see the error page. 

![screen shot 2016-04-21 at 09 08 15](https://cloud.githubusercontent.com/assets/3731693/14702184/019667c0-07a1-11e6-9590-73cca3e10bb0.png)

**Comment by fyberoptik** [comment]
When using the link to /hardware/create/35 this doesn't load the fields the first time, however if you select a different model then switch back to ProBook 6470b, it will then load the fields correctly and the successfully click the save button.

No errors printed to console during these steps.

**Comment by snipe** [comment]
What version are you running? Can you pull the latest from master? The only time that fields error shows up is if the url is set wrong, or on older versions.

**Comment by Karunamon** [comment]
I just encountered this error verbatim on a brand new 2.1.0 install - @snipe 's comment was the key :)

In short, I deployed the application as usual, and then set up a "friendly" cname to the app for my users to access. Most importantly, the cname is *not* the configured address to the application. If a fieldset is defined on the type of asset I'm trying to create, it dies off **exactly** as described by @fyberoptik

I try it again through the properly configured address, and there are no difficulties.

**Comment by martydelaney3** [comment]
I'm experiencing a similar issue where I am unable to add models to the asset when opening the website via http but I am able to add them when opening through https.

**Comment by snipe** [comment]
@martydelaney3 you have to make sure the url in `app/config/production/app.php` is set to your correct URL

**Comment by martydelaney3** [comment]
When set to HTTPS://mywebsite it doesn't work for HTTP and visa versa.

**Comment by snipe** [comment]
> When set to HTTPS://mywebsite it doesn't work for HTTP and visa versa.

@martydelaney3 That's to be expected. Browsers will typically not want to load javascript with a different protocol than the url you're trying to load from. 

You have to make sure the url in `app/config/production/app.php` matches whatever URL you plan on using to access the site.
