### ISSUE TITLE
Error 500 Internal Server Errror

### ISSUE THREAD

**Issue by mghiringhelli** [snipe/snipe-it#1975]
We moved from older version to the new. We have followed the instruction executing php composer.phar etc.

#### Expected Behavior (or desired behavior if a feature request)

Open the page where we can change the data. Or add a new model

-----

#### Actual Behavior

When i go to http://itasset.consulcesi.local/admin/settings/app I receive back an error 500 Internal Server Error. With debug enabled i see:

Illuminate \ Encryption \ DecryptException
HELP
MAC is invalid.
Open: /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php
		if ( ! $payload || $this->invalidPayload($payload))
		{
			throw new DecryptException('Invalid data.');
		}
 
		if ( ! $this->validMac($payload))
		{
			throw new DecryptException('MAC is invalid.');
		}
 

I get back the same error when i try to create a new object model, with debug enabled i see:

Illuminate \ Database \ QueryException (42S22)
HELP
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'note' in 'field list' (SQL: insert into `models` (`depreciation_id`, `eol`, `name`, `modelno`, `manufacturer_id`, `category_id`, `note`, `user_id`, `updated_at`, `created_at`) values (0, 0, test, , 15, 2, test, 1, 2016-04-20 11:36:24, 2016-04-20 11:36:24))

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running **v2.1.0-41-g6d810a9**
- What OS and web server you're running Snipe-IT on **CentOS 7, apache**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Install.sh**
[log-apache2handler-2016-04-20.txt](https://github.com/snipe/snipe-it/files/227757/log-apache2handler-2016-04-20.txt)

**Comment by snipe** [comment]
Make sure your app key is the same as your old one, and make sure you run migrations

**Comment by mghiringhelli** [comment]
Ok i run migration and now the model creation works correctly.

For the app key: i copied the folder "snipeit/app" to the new version when i upgraded, but if i open the "app.php" i dont's see 'key' as parameter.

What's to do?

Thanks

**Comment by snipe** [comment]
I hope you copied more than just the app folder when you upgraded.

The app key is in app/config/production/app.php.

**Comment by mghiringhelli** [comment]
Hello, i want to confirm that i copied all the folder /var/www/html/snipeit/app as suggested on documentation.

So i have overwritten all the files contained in the old app folder, included the app/config/production/app.php in the new version.

What i have to do to solve it?

Thanks

**Comment by mghiringhelli** [comment]
Hello, can i have your help with this job?

thank you
