### ISSUE TITLE
There are no commands defined in the "app" namespace.

### ISSUE THREAD

**Issue by alexisskeates** [snipe/snipe-it#1976]
When trying to install Snipe-IT on my hosted webspace I get the point of running the cli: `php artisan app:install --env=production` which then fails.

The error message I get is:

```
[InvalidArgumentException]                             
There are no commands defined in the "app" namespace.  
                                                  
Content-type: text/html
```

I have PHP Version 5.4.42 active on the hosting and everything went well till this point. I'm not sure it this is a limitation of my hosting provider if so then thats fine, but I just wanted to see if anyone has any ideas before I give up on it.

- Version of Snipe-IT you're running - v2.1.0
- What OS and web server you're running Snipe-IT on - Hosted with TSOHOST linux hosting
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual install

**Comment by snipe** [comment]
Well, this is a new one. It would help if you could give us a little more info:

- what is the path to your snipe-IT install
- what is the path to your PHP?
- what directory are you running the artisan command in?

**Comment by alexisskeates** [comment]
Answers below I’m not 100% about the php question, but I think I put the correct information in. If it’s not an easy fix then not to worry to much it was more out of curiosity why it was not working.
The install is in a subdomain. So it would be clientname.domainname.com <http://clientname.domainname.com/>
info.php file says /usr/local/php56
I’m running the artisan command from the install directory

**Comment by snipe** [comment]
I need the path to your Snipe-IT install, not the domain. `pwd`. To find your cli php version, `php -v`

**Comment by imcint1** [comment]
Hello, I am also having the same issue (figured I would comment here instead of creating a duplicate question).

Snipe-IT verison: 2.1.1
OS and webserver: (hosted by 1and1) Debian 3.14, Zend Engine 2.5, Apache (not sure version), PHP 5.5.35
Install method: manual

install path: /*domain*/snipeit/
php path: usr/lib/php5.6
running artisan command from the /snipeit/ directory over ssh in PuTTY

**Comment by dmeltzer** [comment]
What does `php artisan` show if you don't give it any arguements?

**Comment by imcint1** [comment]
It shows the list of commands (sorry for the small screen shots) 
[
![screenshot_2016-06-01-21-28-09](https://cloud.githubusercontent.com/assets/11221634/15731097/6b1c0762-2840-11e6-8bc2-473a26e5c2f6.png)
![screenshot_2016-06-01-21-28-20](https://cloud.githubusercontent.com/assets/11221634/15731100/6fbd4146-2840-11e6-8a1a-261bc850045c.png)

](url)

**Comment by imcint1** [comment]
Hello,

The issue was with apache configuration and composer exceeding the max transfer size, thus some functions were unavailable. I installed on a server not using shared hosting and had no issues.

Thanks! :)
