### ISSUE TITLE
Edit and Hide Assets Categories and Hide "Accessories, Consumables and Licenses"

### ISSUE THREAD

**Issue by iguy0** [snipe/snipe-it#1977]
Hi, 

I am looking to Change under the "Assets" menu:
Deployed > Loaned Equip
Ready to Deploy > Available Equip
Pending > Printers (or user another item in the menu that better apply to list printers in the organization, any suggestions?)

I'm looking to hide from the "Assets" menu:
Un-deployable
Archived
Requestable

I'm looking to hide "Accessories, Consumables and Licenses" from the menu as well

Thank You.

**Comment by snipe** [comment]
That's not currently possible without you changing the code yourself, and if you do that, your changes will have to be re-done every time you upgrade.

**Comment by iguy0** [comment]
Could you give me pointers to what to look for and where to find it in order to achieve this? By the way this could become a great feature for future versions.

**Comment by snipe** [comment]
It's in `app/views/layouts/default.php`, but again I strongly recommend against doing this. Your changes will be blown out in the next version. You can't simply ignore those nav items?

**Comment by j-ogas** [comment]
I presented Snipe-IT as an asset management solution for a small organization today.

My demo was warmly received, however, this topic dominated our discussion. They really want to be able to edit the “Assets”, “Accessories”, “Components”, etc. labels.

I have have a scheduled task configured to upgrade from git quarterly, so editing these fields myself would not be a viable option.

Have any changes been made to address this feature request?

**Comment by digitalprored** [comment]
Yes I'm in the same situation. 

We are an small Data Center and Snipe-IT solution is perfect for our customers, to provide them an asset management, but in our bussiness there is no "Components", "Accessories", "Consumables"...

It would be very nice to be able to disable theses assets categories.

**Comment by j-ogas** [comment]
@erencross I was not able to find an elegant lasting solution. The organization eventually decided against Snipte-IT in favor of Tyler; they did not want to alter their organizational structure around these labels.

**Comment by mariomare22** [comment]
Was there any change since 11/2018?

**Comment by berilslv** [comment]
Yeap, these pages for example: "Create Consumable" would be cool if we could add or remove lines like location;name; etc. :)

**Comment by mariomare22** [comment]
Used this #7976

**Comment by tony-pinto** [comment]
I too am looking to see if I can hide **Assets**, **Consumables**, **Components**  as I am working on Licenses. I like the security in the Snipe-It product. I find a whole lot of new php scripts but not the one mentioned (app/views/layouts/default.php). Thanks for any pointer you might be able to provide
