### ISSUE TITLE
Scanning and creating assets

### ISSUE THREAD

**Issue by LewiJones** [snipe/snipe-it#1979]
I am looking to use Snipe-IT for an upcoming project I am planning. The software that is present does everything I need it to and I find it very efficient to use. All except for one thing. I was looking for a scanning solution. So that when I scan a parcel or delivery with a USB barcode scanner it will get the product details and then I can use that information for things such as creating new assets. I’m not sure if this feature is in this product. Can anyone enlighten me?

**Comment by snipe** [comment]
That feature is not available at this time.
