### ISSUE TITLE
Server error 500 -> settings -> default.blade

### ISSUE THREAD

**Issue by shairozan** [snipe/snipe-it#1980]
I'm having an issue where after installation, attempting to actually access the page just yields a server 500 error with the following details:
Next exception 'ErrorException' with message 'Trying to get property of non-object (View: /var/www/html/app/views/backend/layouts/default.blade.php) (View: /var/www/html/app/views/backend/layouts/default.blade.php)' in /var/www/html/app/storage/views/58b324d6097f44cc5979b589d74ae250:12
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/a...', Array)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/a...', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#6 /var/www/html/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/html/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /var/www/html/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []

Now, the installer worked fine, picked up the database.php settings, built the table structs and performed the seeding. So I have a database that has settings data, but wherever the getSettings method is being called, it's dying when trying to access a child attribute. 

This is on the most recent tag.

**Comment by ddreier** [comment]
I don't follow how you've concluded that calls to `getSettings` are the culprit. But if it actually is, you should check all of the config files you touched for stray or missing commas, semi-colons, and single- and double-quotes.

**Comment by snipe** [comment]
@shairozan Do you actually have anything in your settings table?

**Comment by shairozan** [comment]
Yes. All migrations and seeds completed correctly, so the default setting
record is in the settings table. This is also happening in the docker image
I used from Docker Hub as well.

**Comment by snipe** [comment]
Can you show me what's on line 12 of /var/www/html/app/storage/views/58b324d6097f44cc5979b589d74ae250 (and a few lines before and after)

**Comment by snipe** [comment]
Also show me what's in your settings table.

**Comment by patrick-othmer** [comment]
I got the same issue.
The first setting id was 3 instead of 1. You can manually solve the problem with updating the first setting id from 3 to 1.
`UPDATE `settings` SET `id` = '1' WHERE `settings`.`id` = 3;`

**Comment by snipe** [comment]
How did you end up with a setting id of 3?

**Comment by patrick-othmer** [comment]
I just did a clean installation. Looks like Autoindex have the wrong start number.

**Comment by benrubson** [comment]
This issue (and #858 too) is due to how MariaDB Galera handles autoindex :
https://mariadb.com/kb/en/library/mariadb-galera-cluster-known-limitations/
_Do not rely on auto-increment values to be sequential. Galera uses a mechanism based on autoincrement increment to produce unique non-conflicting sequences, so on every single node the sequence will have gaps._

Finally, @snipe, when closing this issue, did you implement a fix to not rely on things like `id=1` ?

Thank you 👍
