### ISSUE TITLE
Search by QR Code

### ISSUE THREAD

**Issue by aalsaleh** [snipe/snipe-it#1981]
Would love the ability to search for assets by QR code. Not entirely sure if this is by uploading a pic of the qr code, or using a third party plugin for chrome or something. But the feature would be well received.. Especially if we can use it on the mobile!

**Comment by rkantos** [comment]
Perhaps merge these somehow? #1827

**Comment by DaltLund** [comment]
I generate QR codes with it's data being the URL of the item the QR code is gonna be slapped on to. That way when I scan the QR code, it types the address into my browser and bam, Im right there at the Asset's page.
