### ISSUE TITLE
Barcode printing

### ISSUE THREAD

**Issue by jrodfosheez** [snipe/snipe-it#1982]
Hi there,

First of all I love SnipeIT, great product, fulfulling all of our needs at a very low cost. While I am able to generate QR codes successfully in SnipeIT, I was wondering if anyone has a recommended method to print these out to a label. 

Thanks!

**Comment by snipe** [comment]
Hi @jrodfosheez - you can see out recommendations on generating labels here: http://docs.snipeitapp.com/manual/labels.html

However it should be noted that in the upcoming v3, you can adjust the margins/padding/etc so you will be less restricted to a particular label template.
