### ISSUE TITLE
how to configure in IIS

### ISSUE THREAD

**Issue by murtazamaz** [snipe/snipe-it#1984]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by murtazamaz** [comment]
1: snipe-it-2.1.0
2: Windows 7 default 7.5.6
3: unable to determined what next step (mans need to use (install.sh or manual..)?
4: i want to install in installation phase 

5: i am new and trying to install. i followed following link http://docs.snipeitapp.com/installation/server/windows.html
after followoed i am stuck what next i have to do mean how to proceed installation.


regards
Murtaza

**Comment by snipe** [comment]
The complete installation instructions are on the page you referenced. If you're stuck, you need to tell us where you're stuck, and what you've done so far before you got stuck. You have answered almost none of the questions we ask in order to help you, and no amount of capslock is going to change the fact that until we have more info, we can't help. Give us more information, and we'll try to get you sorted.

**Comment by murtazamaz** [comment]
Thanks for your reply,

http://docs.snipeitapp.com/installation/server/windows.html
as i mention that i followed the following page instruction after completed, how i will access the web page, i followed as same as the link my question still do i need to install any php script or what will be my next step after the above link procedure.

i hope u will get my point.

kind regards
murtaza

**Comment by murtazamaz** [comment]
pls help me i want to install asap when u reply. thanks

**Comment by snipe** [comment]
The Windows server stuff is the last step. You should have done all the steps before that first.
