### ISSUE TITLE
Changing Asset Status on CheckOut

### ISSUE THREAD

**Issue by amorrisPRG** [snipe/snipe-it#1985]
#### Expected Behavior (or desired behavior if a feature request)

If an asset is set as 'Pending' when it is checked out to a user the status does not change. It will stay in the pending list.

-----

#### Actual Behavior

 Status should automatically change to ready to deploy when an asset is checked out. This implies it is ok and ready to deploy. If it stays as Pending then this can cause confusions in the data.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Since there is the possibility of having multiple "deplorable" statuses, I'm not sure how we would make them RTD without you setting them to an RTD stays prior to checkout. We wouldn't know which RTD status is the correct one. It's up to you to set them as RTD prior to checkout.

**Comment by snipe** [comment]
Lol doplorable. Deployable, obviously

**Comment by snipe** [comment]
(Also, if an asset is pending, you shouldn't be checking it out. Pending implies it's not ready to be checked out yet.)

**Comment by amorrisPRG** [comment]
Thanks. Both are good points.
In that case maybe the checkout option should be hidden for all status other than ready to deploy.

**Comment by snipe** [comment]
Where are you seeing the option to check out a pending asset? The checkout button is not provided in the list view when an asset is pending.

**Comment by amorrisPRG** [comment]
Actions menu on the items page allows check-out.

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Jun 2, 2016 at 11:35 AM -0700, "snipe" <notifications@github.com<mailto:notifications@github.com>> wrote:


Where are you seeing the option to check out a pending asset? The checkout button is not provided in the list view when an asset is pending.

-

**Comment by snipe** [comment]
Thanks! We've fixed this in the upcoming v3.
