### ISSUE TITLE
Change User Location

### ISSUE THREAD

**Issue by jebbhb** [snipe/snipe-it#1989]
Hi!
Is there a way to prevent users to change its own location?

I have several companys, and when the user trys to change its profile, it lets him to change its location, but all locations (including the location associated with another companys) are shown.

The idea is that they only change to the locations that belong to their own companys, but if this isn't available, I would like to prevent to let them change their location.

Regards

**Comment by snipe** [comment]
In v3, users (non admins) cannot change their details.
