### ISSUE TITLE
Accessories not displayng in dynamic list

### ISSUE THREAD

**Issue by strevithick** [snipe/snipe-it#1991]
#### Expected Behavior (or desired behavior if a feature request)

After I enter an accessory, I expect it to display in the dynamic list. It shows in the Accessory report but no the dynamic list.

-----

#### Actual Behavior

Dynamic list does not show accessories.

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
newest master branch 

- What OS and web server you're running Snipe-IT on
Debian 8 VM

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
composer/artisan

- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

I have not manually edited any data. Any deletes have been through the UI. However, I had this problem before, and I think it has something to do with the corruption in the history table.

**Comment by snipe** [comment]
Please confirm whether there are any errors in your browser console, per the getting help documentation. 
http://docs.snipeitapp.com/getting-help.html

**Comment by snipe** [comment]
Also tell us if any of your categories have been deleted, as it may relate to https://github.com/snipe/snipe-it/issues/1932

**Comment by strevithick** [comment]
Yes some of the categories were deleted. The user who first used
the system entered some incorrect info into the categories. However all
deletes were via the UI.

Kind regards,

Scott Trevithick | Chief Technology Officer, Asurtec Technology Solutions | strevithick@asurtec.com | Cell: 416.876.0811 | Toll-free: 1-844-278-7832 xt.204 | www.asurtec.com | Help desk: support@asurtec.com


   FROM: snipe
SENT: Tuesday, April 26, 2016 8:19 PM
TO: snipe-it@noreply.github.com
REPLY TO: snipe/snipe-it
CC: strevithick; Author
SUBJECT: Re: [snipe/snipe-it] Accessories not displayng in dynamic list
(#1991)

> Also tell us if any of your categories have been deleted, as it may
> relate to #1932[1]
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub[2]



Links:
------
[1] https://github.com/snipe/snipe-it/issues/1932
[2] https://github.com/snipe/snipe-it/issues/1991#issuecomment-214927445

**Comment by snipe** [comment]
This is likely related to https://github.com/snipe/snipe-it/issues/1932. There is a fix on the upcoming v3, for for v2.1, you'll need to go into the database and un-delete those categories.

**Comment by strevithick** [comment]
I'm not sure if this is the same bug as the categories were deleted 
/before/ the accessories were created.  The accessories belong to a 
category that was never deleted.


On 16-04-26 08:23 PM, snipe wrote:
>
> Closed #1991 <https://github.com/snipe/snipe-it/issues/1991>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/snipe/snipe-it/issues/1991#event-642261862>
>

-- 
*Kind regards,

Scott Trevithick | Chief Technology Officer, Asurtec Technology 
Solutions | strevithick@asurtec.com | Cell: 416.876.0811 | Toll-free: 
1-844-278-7832 xt.204 | www.asurtec.com | Help desk: support@asurtec.com 
<mailto:support@asurtec.com>*
