### ISSUE TITLE
Decrypt Exception MAC is invalid

### ISSUE THREAD

**Issue by mghiringhelli** [snipe/snipe-it#1992]
We moved from older version to the new. We have followed the instruction executing php composer.phar etc.

#### Expected Behavior (or desired behavior if a feature request)

Can modify the application settings. 

-----

#### Actual Behavior

Like other tkt #1975 

When i go to http://itasset.companyname.local/admin/settings/app I receive back an error 500 Internal Server Error. With debug enabled i see:

Illuminate \ Encryption \ DecryptException
 HELP
 MAC is invalid.
 Open: /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php
 if ( ! $payload || $this->invalidPayload($payload))
 {
 throw new DecryptException('Invalid data.');
 }
    if ( ! $this->validMac($payload))
    {
        throw new DecryptException('MAC is invalid.');
    }

-----

#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

•Version of Snipe-IT you're running v2.1.0-41-g6d810a9 
•What OS and web server you're running Snipe-IT on CentOS 7, apache 
•What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Install.sh
-----

I have overwritten all the files contained in the old app folder to the new one, included the app/config/production/app.php in the new version.

**Comment by snipe** [comment]
Try clearing your composer autoload and cache.

```
composer dump-autoload
composer clear-cache
```

The only reason you'll see MAC is invalid is if the key is wrong, or if something is cached.

**Comment by mghiringhelli** [comment]
Hi, solved restoring the old key as you suggested.

Thanks.
