### ISSUE TITLE
[feature] Asset model to require parent

### ISSUE THREAD

**Issue by eduardok** [snipe/snipe-it#1993]
I've created a new asset model KVM (Category Virtual Machines) to be used for VMs I have. There is no way, however, to tell which physical server that VM relates to.
As a generic solution I suggest that when creating a new asset model we have a checkbox "Require parent", that at asset creation time will require pointing to an already-existing asset.
It could also be used for cards that go into servers, switches, etc.

**Comment by snipe** [comment]
Cards and switches would be handled via the upcoming components section.

**Comment by ddreier** [comment]
Also, you can add a custom field for VM Host Server (or something similar) to your VM Asset Model.
