### ISSUE TITLE
Uploading large image files to Asset Models results in 500 error

### ISSUE THREAD

**Issue by Giantdhk** [snipe/snipe-it#1994]
Uploading large image files to Asset Models results in 500 error. The image I attempted to upload when I received the error was a 3.9 MB .JPG file. Reproduced each time I attempted to upload that file and also reproduced when I uploaded a 2.3 MB .PNG file.

Would be helpful to include a note indicating the maximum allowed file size and as well as allowed file types or use a different file uploader which accommodates a larger file size.

**Comment by snipe** [comment]
If you're getting a 500 error, this is likely due to your server not being configured to handle larger files.
