### ISSUE TITLE
Composer install

### ISSUE THREAD

**Issue by manusolano777** [snipe/snipe-it#1999]
![error](https://cloud.githubusercontent.com/assets/18734573/14911113/cf46408a-0e10-11e6-961f-71f386c025c0.png)
![error 2](https://cloud.githubusercontent.com/assets/18734573/14911268/f2ee1200-0e11-11e6-9c2d-d37789b23261.png)

Kindly please help me to solve this issue

**Comment by snipe** [comment]
I have absolutely no idea why you'd be running composer create

**Comment by manusolano777** [comment]
Why this error message comes then?????

**Comment by snipe** [comment]
Nowhere in the installation instructions does it tell you to run composer create. Please follow the directions.
