### ISSUE TITLE
Server Error: 500 (Internal Server Error) after Backup Upload

### ISSUE THREAD

**Issue by pritamkumar13** [snipe/snipe-it#2000]
#### Server Error:500 while clicking edit settings after Backup restore

production.ERROR: exception 'Illuminate\Encryption\DecryptException' with message 'MAC is invalid.' in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:144

-----

#### DecryptException' with message 'MAC is invalid.

I have performed a fresh installation of Snipe-IT at AWS Ubuntu instance. I took backup, deleted instance and performed a fresh installation again at new instance and restored the backup at MySQL (through phpmyadmin). Now I got everything restored, all my previous data (i.e. Model, Employee, Asset, etc) but in Settings, edit settings isn't working. I have attached the log too, looks like I'll have to use old app key, but I don't have that, as I have deleted the old instance. Please suggest what should I do ?

-----
#### Snipe-IT Version detail:

Snipe-IT version 	v2.1.0-55-g701c16f
PHP Version 	5.5.9-1ubuntu4.14
Laravel Version 	4.2.17
OS - AWS Ubuntu

-----
#### Log detail:

[2016-04-29 13:01:42] production.ERROR: exception 'Illuminate\Encryption\DecryptException' with message 'MAC is invalid.' in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:144
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(89): Illuminate\Encryption\Encrypter->getJsonPayload('eyJpdiI6IlBUTlM...')
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\Encryption\Encrypter->decrypt('eyJpdiI6IlBUTlM...')
#2 /var/www/snipeit/app/controllers/admin/SettingsController.php(53): Illuminate\Support\Facades\Facade::__callStatic('decrypt', Array)
#3 /var/www/snipeit/app/controllers/admin/SettingsController.php(53): Illuminate\Support\Facades\Crypt::decrypt('eyJpdiI6IlBUTlM...')
#4 [internal function]: Controllers\Admin\SettingsController->getEdit()
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('getEdit', Array)
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\SettingsController), Object(Illuminate\Routing\Route), 'getEdit')
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'getEdit')
#9 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15 /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#19 /var/www/snipeit/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#20 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#21 /var/www/snipeit/public/index.php(49): Illuminate\Foundation\Application->run()
#22 {main} [] []

**Comment by snipe** [comment]
You need to use the same app key that you had in your original installation.

**Comment by pritamkumar13** [comment]
That's what I thought, But unfortunately I have deleted my old instance. Is there any way to recover the same app key ?

**Comment by snipe** [comment]
No way to recover if you've deleted it. 

Your only option is to go into the database, and manually set the settings for `ldap_enabled`  to `0` and `ldap_pword` to null.

**Comment by shahima** [comment]
Hi snipe
 can you please help me how to import license into snipe-it application

**Comment by shahima** [comment]
hi snipe
