### ISSUE TITLE
page not found when opening the backup page

### ISSUE THREAD

**Issue by abdullahalasham** [snipe/snipe-it#2001]
#### Expected Behavior (or desired behavior if a ture request)

Open the backup page

-----

#### Actual Behavior

Error Page appear : Whoops, looks like something went wrong.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running. **V3**
- What OS and web server you're running Snipe-IT on** windows -WAMP**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)** manual installation**
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).yes
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. 
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
> Confirm whether the error is reproduceable on the demo.yes 

How is this reproducible on the demo?

**Comment by snipe** [comment]
(Also, v3 isn't stable yet, so you shouldn't be using it for production.)
