### ISSUE TITLE
NEED Help in QRCode Generation

### ISSUE THREAD

**Issue by sundaresanm** [snipe/snipe-it#2002]
we have Asset Management Application ,in that using (\Com\Tecnick\Barcode\Barcode()) QRCODE Generator. its working perfectly and produces

**URL : http://xxxxx/xxxx/public/hardware/29/view**

Now we want add new parameter in that URL as below

URL : http://xxxxx/xxxx/public/hardware/29/**345**/view

Kindly do needful...

By

Sundar M

**Comment by snipe** [comment]
This is unlikely to be implemented. The asset ID already exists in the URL, so the second number (that I assume is the asset tag, but I have no idea since you didn't tell us) isn't needed.

**Comment by snipe** [comment]
Also, it's enormously impolite to post a Github issue, post to Gitter AND email us within a few hours. Be clear about what you need, and IF it makes sense for the project, we'll try to work it in.

**Comment by sundaresanm** [comment]
Hi Snipe Team,

Thanks for your valuale reply.I would like to tell our requirements in QR
Code Generator.

Currently Snipe Tool its generate labels its show below

URL :http://localhost/asset_demo/public/hardware/28/qr_code


here 28 -> asset_id

Now i Try to generate QR Code as

URL :http://localhost/asset_demo/public/hardware/28/INDBLRITLAP01/qr_code

here INDBLRITLAP01 -> Asset_tag

For making above changes, checked files  are
app/routes.php,app/controllers/admin/AssetsController.php

IN app/routes.php

Route::get( '{assetId}/{assetTag}/view', [ 'as' => 'view/hardware', 'uses'
=> 'AssetsController@getView' ] );

Route::get( '{assetId}/{assetTag}/qr_code', [ 'as' => 'qr_code/hardware',
'uses' => 'AssetsController@getQrCode' ] );

public function getQrCode($assetId = null,$assetTag =null)
    {
        $settings = Setting::getSettings();

        if ($settings->qr_code == '1') {
            $asset = Asset::find($assetId);
          $assetTag = $asset->asset_tag;



            $size = barcodeDimensions($settings->barcode_type);

            if (!Company::isCurrentUserHasAccess($asset)) {
                return Redirect::to('hardware')->with('error',
Lang::get('general.insufficient_permissions'));
            }

            if (isset($asset->id,$asset->asset_tag)) {
                $barcode = new \Com\Tecnick\Barcode\Barcode();
                $barcode_obj =
 $barcode->getBarcodeObj($settings->barcode_type, route('view/hardware',
$asset->id,$assetTag), $size['height'], $size['width'], 'black', array(-2,
-2, -2, -2));
                return $barcode_obj->getPngData();
            }
        }

    }

public function getView($assetId = null,$assetTag =null)
    {
        $asset = Asset::withTrashed()->find($assetId);
        $assetTag = $asset->asset_tag;


        $settings = Setting::getSettings();

        if (!Company::isCurrentUserHasAccess($asset)) {
            return Redirect::to('hardware')->with('error',
Lang::get('general.insufficient_permissions'));
        }
        else if ($asset->userloc) {
            $use_currency = $asset->userloc->currency;
        } elseif ($asset->assetloc) {
            $use_currency = $asset->assetloc->currency;
        } else {
          $default_currency = Setting::first()->default_currency;

          if ($settings->default_currency!='') {
            $use_currency = $settings->default_currency;
          } else {
            $use_currency = Lang::get('general.currency');
          }

        }

        if (isset($asset->id)) {


            $qr_code = (object) array(
                'display' => $settings->qr_code == '1',
                'url' => route('qr_code/hardware', $asset->id,
$asset->asset_tag)
            );


            return View::make('backend/hardware/view', compact('asset',
'qr_code','settings'))->with('use_currency',$use_currency);
        } else {
            // Prepare the error message
            $error = Lang::get('admin/hardware/message.does_not_exist',
compact('id'));

            // Redirect to the user management page
            return Redirect::route('hardware')->with('error', $error);
        }

    }

I have highlighted changes  with yellow colors are made by myself..

Kindly review it and do needful..

Thanks,

Sundar M

On Fri, Apr 29, 2016 at 11:54 PM, snipe <notifications@github.com> wrote:

> Also, it's enormously impolite to post a Github issue, post to Gitter AND
> email us within a few hours. Be clear about what you need, and IF it makes
> sense for the project, we'll try to work it in.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/snipe/snipe-it/issues/2002#issuecomment-215838509>
>



-- 


Best Regrads

SUNDARESAN M

**Comment by snipe** [comment]
Colors do not display in Github issues. Once again, you have not told me why you need this feature, so it is unlikely to be implemented.
