### ISSUE TITLE
snipeit.sh not working on Ubuntu 16.04

### ISSUE THREAD

**Issue by crutchcorn** [snipe/snipe-it#2003]
First off, FANTASTIC work @snipe. We needed a system just like this for work, and before I started building something small and dumb - I decided to look it up and found this wonderful gem! Thanks for that!

Anywho, it seems as if `snipeit.sh` (what `install.sh` calls) isn't working under Ubuntu 16.04. Firstly, it doesn't install `curl` (which breaks the install of `Composer`).
Secondly; Almost none of your install commands point to a valid installer. On line 272, where you have:
`sudo apt-get install -y git unzip php5 php5-mcrypt php5-curl php5-mysql php5-gd php5-ldap`
Only git and unzip actually have the right location. 

Because of these issues, the installation obviously doesn't follow through. Now, I'm not suggesting that the script should be changed (though, admittedly - `curl` should be added) - but at least on the documentation - you should add a warning for us 16.04 users that the packages in the script might not be available yet.

**Comment by crutchcorn** [comment]
Actually - fair question here: Why don't you just replace that line with:
` sudo apt-get install -y git unzip php php-mcrypt php-curl php-mysql php-gd php-ldap`?
Granted, it's PHP 7.0, not 5.0 - but does that break anything? (I honestly don't know, I don't use PHP often enough)

**Comment by crutchcorn** [comment]
I know a way that these packages can be installed with PHP 5.6 (that you could recommend users to add before running the script, or just have it add them for them in the script for 16.04 users), but the install command would have to change from `php5-pkg` to `php5.6-pkg`

**Comment by crutchcorn** [comment]
Lastly, it seems that PHP is missing the mbstring extension from Ubuntu

**Comment by delize** [comment]
Having the same issue, it fails to install several components, and then cannot launch afterwards.

**Comment by zultralord** [comment]
Exact same issue here.

**Comment by snipe** [comment]
I believe the latest version of Ubuntu has changed some package names. We're working on a fix for the installer script.

**Comment by uberbrady** [comment]
The install script for v3 correctly detects 16.04 and uses the new package names when it's running on there.
