### ISSUE TITLE
admin that belong to a company cannot create a new consumable

### ISSUE THREAD

**Issue by tsvikas** [snipe/snipe-it#2004]
#### Expected Behavior (or desired behavior if a feature request)
1. login as an admin that is assigned to a company
2. Set the setting "Full Multiple Companies Support" to True.
   When using "Create Consumable", 
   i expect a consumable to be created...
   (note that the Company field in "Create Consumable" is hidden, as expected)

---
#### Actual Behavior

whenever i try to add a consumable the cryptic error "Error: Please check the form below for errors" (it appears above the form)

I guess it assign an empty value for the new consumable- company,
than deny it's creation because an admin from a company can't create a empty-company consumable

(BTW, i think an admin from a company can create a empty-company asset/accessory)

---
#### Please confirm you have done the following before posting your bug report:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running

Snipe-IT version v2.1.0-55-g701c16f
PHP Version 5.5.9-1ubuntu4.14
Laravel Version 4.2.17
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

http://subdomain.domain.org/admin/consumables/create
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).

"Full Multiple Companies Support" is not in the demo settings
- Indicate whether or not you've manually edited any data directly in the database

nope
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.

**Comment by crash890** [comment]
It appears I have run into this same error. I've looked some, but can't seem to find why it's occurring.

To echo, it occurs when using companies for an admin and setting "full multiple companies" to true.
