### ISSUE TITLE
SSL not working

### ISSUE THREAD

**Issue by mta101** [snipe/snipe-it#2005]
#### Expected Behavior (or desired behavior if a feature request)

HTTPS to work like HTTP

-----

Any calls made using HTTPS give a recursive redirect into public directly

-----

#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 2.1.0
- What OS and web server you're running Snipe-IT on Linux/Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual installation
- If you're getting an error in your browser, include that error Too many redirects
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error any using https
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
This sounds like it might be an issue with your configuration, not with Snipe-IT. Are you using anything unusual (SSL from Let's Encrypt, passing traffic through Cloudflare, etc?)

**Comment by snipe** [comment]
Any updates here?

**Comment by kt1024** [comment]
@snipe ,I've met same problem, is my site conf incorrect?
http://url is ok, but https://url is not ok.
snipeit 2.1.0-55+apache/ubuntu 14
![image](https://cloud.githubusercontent.com/assets/12657496/15525857/f5deb4d0-225f-11e6-85d6-8a78179371fe.png)
![image](https://cloud.githubusercontent.com/assets/12657496/15525860/f887780c-225f-11e6-800d-910b79ef90d6.png)
![image](https://cloud.githubusercontent.com/assets/12657496/15525862/fc819672-225f-11e6-9bc6-8f06a0138d6b.png)

ken@asset:/etc/apache2/sites-enabled$ apachectl configtest
Syntax OK
ken@asset:/etc/apache2/sites-enabled$ cat /var/log/apache2/snipeIT.error.log
ken@asset:/etc/apache2/sites-enabled$

* debug mode enabled:

snip-it@asset:/var/www/snipeit/app/storage/logs$ cat log-apache2handler-2016-05-25.txt
[2016-05-25 10:13:31] production.DEBUG: Not logged in - admin-auth [] []

thanks.

**Comment by uberbrady** [comment]
I think you need the same 
```xml
<Directory /var/www/snipeitpublic>
    Require all granted
    AllowOverride All
</Directory
```
block in your `*:443` VirtualHost?

You can test by trying to browse, manually, to `https://asset.blah.com/index.php` - if that works, then it sounds like it could be the AllowOverride.

**Comment by snipe** [comment]
Ah, good catch, @uberbrady

**Comment by kt1024** [comment]
that fixed my issue. thanks! @uberbrady
