### ISSUE TITLE
Feature Request: Asset Verification

### ISSUE THREAD

**Issue by d0dman** [snipe/snipe-it#2008]
#### Desired Behavior

Add a verification date and verified by fields to assets
Automatically update verification date and verified by when QR code scanned.
Add "Verification" permission for groups to authorize verification scan.
Add departments and have a department level permission group (allow this group to add and edit assets within that department)

This will departments to have their own people walk around with a QR scanner and verify possession of assets.  Should reduce asset inventory time significantly.

Thanks

**Comment by snipe** [comment]
This was released in a recent version
