### ISSUE TITLE
Emails body translation

### ISSUE THREAD

**Issue by mariomasa** [snipe/snipe-it#2010]
I setup the app to translate to Portuguese ('locale' => 'pt-PT') and it works fine.
But the system is still sending the emails in English language.
Example is the "Confi
![snipe it image](https://cloud.githubusercontent.com/assets/18213858/15044961/18d8f866-12bf-11e6-980f-6446ebf6d19a.png)
rm Asset Checkin" email alert.

How to customize them emails, changing the Subject and the boby of the email to Portuguse language.

BR

**Comment by IxFail** [comment]
I think the email's are hardcoded in English.
You can edit (if you are using a Linux version) the mail at /app/views/emails/checkin-asset.blade.php.
You can change the subject of the checkin email(if you are using a Linux version) at /app/controllers/admin/AssetsController.php Line 659

**Comment by mariomasa** [comment]
Thank you,
Now, I can edit the files and translate them to portuguese.

Where can I change the subject of the email "Confirm asset delivery"

**Comment by IxFail** [comment]
You can change the subject of the email "Confirm asset delivery" at `app/models/Asset.php` @ line 88

Be aware that at every update these files/changes will reset

**Comment by mariomasa** [comment]
Thanks,
It's a suggestion that the translation of the whole application should be extended to the emails.

**Comment by GaoGaoCE** [comment]
> You can change the subject of the email "Confirm asset delivery" at `app/models/Asset.php` @ line 88
> 
> Be aware that at every update, these files/changes will reset

Hello i'm using version 6.3, can you manual how to edit email delivery subject such as : add more username in subject ?
