### ISSUE TITLE
Possible Feature Request: Add Checkin/Checkout Notes to to Deployed Asset List

### ISSUE THREAD

**Issue by CaptainNapalmSE** [snipe/snipe-it#2013]
#### Expected Behavior (or desired behavior if a feature request)

When listing Assets, there is a "Notes" field that is tied to the asset in the list.  When an asset is checked out, there is a separate Notes field that can be filled out during the checkout process.  Is there a way that exists to add the Notes field from the checkout to the Asset list?  

Example:  We have a ticketing system we work with.  If a user puts in a ticket to request a loaner laptop for a trip, when I check out the laptop to the user I can enter the ticket ID in the Notes field.  However, that particular note only shows up as a note on the asset when you click the asset.  We'd like to see the Checkout notes on the asset display page, but don't see a way to achieve that.

---
#### Actual Behavior

N/A

---
#### Please confirm you have done the following before posting your bug report:
- [N/A] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on  Server 2012 R2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)  Manual install
- If you're getting an error in your browser, include that error  N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error  N/A
- If a stacktrace is provided in the error, include that too.  N/A
- Any errors that appear in your browser's error console.  N/A
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database  N/A

**Comment by snipe** [comment]
> However, that particular note only shows up as a note on the asset when you click the asset. We'd like to see the Checkout notes on the asset display page, but don't see a way to achieve that.

I'm not following you. The checkout note shows up in the asset history section at the bottom of the asset detail page.

**Comment by CaptainNapalmSE** [comment]
@snipe - Yeah, I was pretty tired and somewhat incoherent, so sorry for my rambling.  The note you're referring to in the asset history section is the one I'm talking about.  However, the team here wanted to know if there was a way to put that particular note in the main asset list.  So, basically, if I check out a laptop to a user and I put the ticket number in the Notes field at checkout, is there a way for that note to show up in the list when they click on "Deployed" and see all of the deployed assets - they understand they can see it in the asset history list, but wanted to add that as a column next to the checkout/checkin dates.

Does that make sense?
