### ISSUE TITLE
Feature Request: Expiration Notifications 

### ISSUE THREAD

**Issue by bbjarn** [snipe/snipe-it#2014]
We would like to use SnipeIT to track SSL certificate renewal notifications, software license renewal notifications, etc - would it be possible to add a feature that allows for expiration date settings and notifications?

**Comment by adam820** [comment]
You may want to see https://github.com/snipe/snipe-it/issues/280, which covers how to set up a cron job so that it emails you based on your license/warranty expiration. You need to make sure your mail.php file is set up correctly.
