### ISSUE TITLE
QR Code MIME Type not Set

### ISSUE THREAD

**Issue by theonewolf** [snipe/snipe-it#2018]
#### Expected Behavior (or desired behavior if a feature request)

I expect the proper MIME type header being set when QR codes are sent back (via the `/hardware/*/qr_code` path).

-----

#### Actual Behavior

MIME type is set to `text/html` which confuses browsers immensely.  It also makes it difficult to save, copy and paste, and generally work with the QR codes properly.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: **v2.1.0-55**
- What OS and web server you're running Snipe-IT on: **Ubuntu 14.04, Apache**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): **install.sh**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: **`/hardware/*/qr_code` path**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): **Yes, for example: https://demo.snipeitapp.com/hardware/18/qr_code**

**Comment by snipe** [comment]
This is already fixed in the upcoming v3
