### ISSUE TITLE
Updating ubuntu in the background. Please be patient.

### ISSUE THREAD

**Issue by AndreAraujo4** [snipe/snipe-it#2021]
Hello guys!!

I'm having problems installing snipe it in a ubuntu server vm.

The problem is, everytime I run the install.sh, it asks me for the FQDN and the db password, but after those 2 steps, a message appears.

Message:
Updating ubuntu in the background. Please be patient.

I don't know what I'm doing wrong, so any help would be good.

**Comment by kt1024** [comment]
have you try manually update system first? (to see if your internet connection or os repo source is ok or not)

**Comment by AndreAraujo4** [comment]
Yes I did.

It has a static IP, that is been given by DHCP.

**Comment by snipe** [comment]
@mtucker6784 Any ideas here?

**Comment by mtuckerinaz** [comment]
Unfortunately not so much right now, I can look into the script but @merid14 has made a lot of changes since my actually last PR, not passing the buck by any means. 

@AndreAraujo4 , I don't think you're doing anything wrong. the script is set to pigeon hole a lot of the text from the user. Can you tell us what the /var/log/snipeit-install.log file says please?

**Comment by PRNOHFT** [comment]
From my experience of installing Snipe for the first time on a fresh desktop/server, the 'updating ubuntu in the background' thing will take a while. It took me about close to 2 hours installing on a non-live Ubuntu on a 16gb thumbdrive, USB 2.0. Try it over the weekend?

**Comment by merid14** [comment]
@AndreAraujo4, if you could post the install log /var/log/snipeit-install.log that would give us a good direction. also, what version of ubuntu are you running?

**Comment by AndreAraujo4** [comment]
Hello there again!! Sorry for the delay! I've been working day and night, so I only had time to get this going again now.

Unfortunately, my previous setup is gone, because my SSD went nuts, but with all up and running again, i'm trying to install snipe-it.

@mtuckerinaz as I can see from the log file, it seems that ubuntu is updating in the background.
Can't copy that at the moment because I'm waiting for it to end eventually.
@PRNOHFT I'm taking your advice and will wait to see if it installs. 
@merid14 I'm running Ubuntu 14.04.3 LTS

**Comment by mtucker6784** [comment]
@AndreAraujo4 , thanks for letting us know. Are you comfortable editing shell scripts? I'd like to edit the script so that the ubuntu install part doesn't pigeon hole the data, and we can see what you are seeing in your terminal directly.

**Comment by AndreAraujo4** [comment]
I am really not comfortable editing shell scripts. As a matter of fact, I started wandering in Linux a little time ago, so I don´t have that ease. After 3 hours I was able to install it, but I can't access it, so i don't know what is missing right now

**Comment by merid14** [comment]
@AndreAraujo4 so are you able to get into the box? if you can, then open a second shell into your box and run this command 'cat /var/log/snipeit-install.log'. even if its in the middle of updating it will still show you whats going on. Then just copy that from the console and paste it to pastebin or similar. If you need more general help with Linux we are all ears. (not to steer you away from this issue post but the back and forth of gitter might help things go faster)

**Comment by snipe** [comment]
Did this get resolved with any of the recent PRs?

**Comment by merid14** [comment]
I think so. I believe the issue was with PHP not installing.

**Comment by AndreAraujo4** [comment]
Sorry for the late response guys, but we had some problems on the company I work for, and time had been null to me. I'm going to get my hands on Snipe again, next week. Then I will answer to the questions here. Thanks for the quick answers though.
