### ISSUE TITLE
how to limited permission to the user 

### ISSUE THREAD

**Issue by umerafridi** [snipe/snipe-it#2022]
(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

Hi,
 how i give access to the user that they only add the asset in their respective departments not view other assets or other departments assets 

- Version of Snipe-IT you're running     ** (v2.1.0)**
- What OS and web server you're running Snipe-IT on     ** CentOS release 6.6 (Final)**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)  (install.sh)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
We do not currently support departments, only companies. Only superusers can see other company assets within the system.
