### ISSUE TITLE
Server Error: 500 (Internal Server Error)  What does this mean?  Something went wrong on our servers while we were processing your request. We're really sorry about this, and will work hard to get this resolved as soon as possible.  Perhaps you would like to go to our home page?

### ISSUE THREAD

**Issue by umerafridi** [snipe/snipe-it#2023]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running   v2.1.0
- What OS and web server you're running Snipe-IT on   centos 6.5 final
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- If you're getting an error in your browser, include that error
Server Error: 500 (Internal Server Error)

What does this mean?

Something went wrong on our servers while we were processing your request. We're really sorry about this, and will work hard to get this resolved as soon as possible.

Perhaps you would like to go to our home page?

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Need the error logs, per the issue template and the getting help documentation.

**Comment by umerafridi** [comment]
error logs are clear no error are there in error logs.its work fine in previosus version

**Comment by snipe** [comment]
Please turn on debugging, as requested in the getting help documentation. We need the stacktrace.

**Comment by snipe** [comment]
Any updates here?
