### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by tdpdan** [snipe/snipe-it#2025]
Assemblies.

We don't buy pre-built computers, we build our own for our specific needs. It would be nice if I could enter the individual components as assets, and assign them to an assembly, which is itself an asset (the actual pc). This way the PC can still be checked out and kept track of, but individual parts that need to be replaced or changed can be updated. The cost field would be an auto sum of the cost of the other assets used to build the assembly.

**Comment by ddreier** [comment]
A "Components" feature is coming in version 3. The price calculation you're asking for could be considered for future versions past that.

**Comment by tdpdan** [comment]
Fantastic! Any idea on release date?

**Comment by snipe** [comment]
![rotten-miracles](https://cloud.githubusercontent.com/assets/197404/15124538/67ae5604-15dd-11e6-82a5-5471aff61850.gif)

**Comment by tdpdan** [comment]
Touche

**Comment by snipe** [comment]
:P

**Comment by snipe** [comment]
Joking aside, we're hoping for the next week or so. I hesitate to promise that because we've been hoping for a week or so for the past several weeks though.

**Comment by tdpdan** [comment]
I've been in manufacturing for a decade. I understand completely.
