### ISSUE TITLE
LDAP authentication failed

### ISSUE THREAD

**Issue by kt1024** [snipe/snipe-it#2026]
#### Expected Behavior (or desired behavior if a feature request)

- users authentication via active directory

#### Actual Behavior

- users can't login. users already imported via "LDAP import"
![image](https://cloud.githubusercontent.com/assets/12657496/15135172/df030236-16a5-11e6-812a-54650ccb0c83.png)

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
  - 2.1.0-55
- What OS and web server you're running Snipe-IT on
  - ubuntu 14.04.3 lts , apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  - install.sh
- If you're getting an error in your browser, include that error
<pre><code>
[2016-05-10 11:27:39] production.DEBUG: LDAP is enabled. [] []
[2016-05-10 11:27:39] production.DEBUG: Sentry lookup complete [] []
[2016-05-10 11:27:39] production.DEBUG: Local user kt exists in database. Authenticating existing user against LDAP. [] []
[2016-05-10 11:27:39] production.DEBUG: User did not authenticate correctly against LDAP. Local user was not updated. [] []
[2016-05-10 11:27:39] production.DEBUG: Authenticating user against database. [] []
[2016-05-10 11:27:39] production.DEBUG: Local authentication: User kt not found [] []
</code></pre>
 
- Indicate whether or not you've manually edited any data directly in the database
  - no

ldap settings:
<pre><code>
'url' => "ldap://gzpdc.domain.com",
'username' => "CN=service snipe-it,OU=SERVICES ACCT,DC=domain,DC=COM",
'password' => "password",
'basedn'   => "ou=STAFF,dc=domain,dc=com",
'filter' => "&(cn=*)",
'result.username' => "uid",
'result.last.name'  => "sn",
'result.first.name' => "cn",
'result.active.flag' => "",
'result.emp.num'  => "",
'result.email' => "mail",
'authentication.filter.query' => "uid=samaccountname",
'version' => 3,
<code></pre>
![image](https://cloud.githubusercontent.com/assets/12657496/15135094/1ecdd8a6-16a5-11e6-9d00-7784879dcf42.png)

**Comment by IxFail** [comment]
Try change the LDAP Authentication query from `uid=samaccountname` to `samaccountname=`

**Comment by kt1024** [comment]
works now, thanks!

**Comment by snipe** [comment]
Thanks, @IxFail! <3
