### ISSUE TITLE
Can't change admin Password when old password has fewer than 6 characters

### ISSUE THREAD

**Issue by freeman-endlessm** [snipe/snipe-it#2029]
#### Expected Behavior (or desired behavior if a feature request)

changing a password that was set with fewer than 6 characters works

-----

#### Actual Behavior

Upon attempting to change admin's password, I receive the message:

Error message: "The old password must be at least 6 characters"

To Clarify, the new password has greater than 6 characters, this error message is because the old password was set with fewer than 6 characters.
-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v2.1.0-55
- What OS and web server you're running Snipe-IT on

Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

ii  apache2                          2.4.7-1ubuntu4.9                 amd64        Apache HTTP Server

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

install.sh

- If you're getting an error in your browser, include that error

Included above

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

Change password for admin account

**Comment by snipe** [comment]
How does the user have an old password of under 6 characters?

**Comment by freeman-endlessm** [comment]
I don't recall exactly what let me set it up. Perhaps the installer script, or some setup page, post- install?
