### ISSUE TITLE
Allow user creation with one character for last name

### ISSUE THREAD

**Issue by hargov** [snipe/snipe-it#2033]
#### Expected Behavior (or desired behavior if a feature request)

LDAP sync should import all users with one or more characters for surname

-----

#### Actual Behavior

The LDAP sync fails to import values with single character for surname

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [Y] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of SnipeIT  [ 2.1.0 ]
- What OS and web server you're running Snipe-IT on [Windows Server 2012 + Apache ]
- What method you used to install Snipe-IT rmanual installation, docker, etc) [Manual]
- If you're getting an error in your browser, include that error [Validator failed:The lastname must be at least 2 characters]
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error [LDAP -> Synchronize]
- Indicate whether or not you've manually edited any data directly in the database [No]

**Comment by snipe** [comment]
What is the use case here?

**Comment by snipe** [comment]
Actually, it doesn't matter - this is already implemented in the v3 branch for the upcoming version 3 release.

**Comment by hargov** [comment]
​Thank you for the update.

​
