### ISSUE TITLE
Asset Label is not Generating...

### ISSUE THREAD

**Issue by sundaresanm** [snipe/snipe-it#2034]
Hi Snipe Team,

> In asset view list , checked the all select box then click the drop down at the bottom and select generate labels, I get the new page of the asset info but where the **ASSET LABEL** would be presence only for 8 assets out of selected 10 assets

![asset_label](https://cloud.githubusercontent.com/assets/11832747/15213154/08f7e4f8-1863-11e6-89e5-27fcf7692407.png)

Thanks,

**Comment by ddreier** [comment]
You still need to provide all of the information that you removed from the text box when you created this Issue. Please see http://docs.snipeitapp.com/getting-help.html for a list of the information that you need to include.

**Comment by sundaresanm** [comment]
> @ddreier In asset view list,selecting an multiple assets then  selects  **Generate Labels** in below drop-down , that time Asset labels are not generated for all  selected assets...
> 
> I have attached my image in previous post..
> 
> Thanks

**Comment by snipe** [comment]
@sundaresanm you have to include that information in every post. We don't know if the info is still valid from post to post, and frankly it's not our job to track it down within Github issues for each user.

Please right click on the broken image, and try to view that url in a browser, and report back what you see.

**Comment by sundaresanm** [comment]
> @snipe When i right click on the broken image,can able to see **http://127.0.0.1/asset_demo/public/hardware/30/qr_code** then when i hit enter, can able to see some characters..

Attached  image as below...

![asset_label_broken_image](https://cloud.githubusercontent.com/assets/11832747/15243688/d08d1256-191a-11e6-9f4c-e8894279eb41.png)


Thanks,

Sundar

**Comment by sundaresanm** [comment]
@snipe Can i get solution for mentioned issue..?

Kindly help..

**Comment by snipe** [comment]
When you provide us with all of the information we asked for, certainly.

**Comment by sundaresanm** [comment]
When we try to generate Asset Label tag ,its not generating for all assets which i used bulk options....

I have attached below screenshot....

![asset_label](https://cloud.githubusercontent.com/assets/11832747/15895320/48ee4f66-2da8-11e6-871f-e3d819431e88.png)
