### ISSUE TITLE
Feature Request - Allow uploading CSV file.

### ISSUE THREAD

**Issue by nirmalpathak** [snipe/snipe-it#2035]
It would be great to have a feature which allows uploading CSV file for creating new licenses and assets .

**Comment by ddreier** [comment]
There is already a CSV importer for assets and users. http://docs.snipeitapp.com/manual/importing-assets.html

**Comment by snipe** [comment]
There is also a CSV importer for licenses. http://docs.snipeitapp.com/manual/importing-licenses.html
