### ISSUE TITLE
V3 Upload issues

### ISSUE THREAD

**Issue by nervouspotato** [snipe/snipe-it#2037]
Upload without error

-----

Interface is not showing properly
css issue?
errors are attached to this

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode - no
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html) - yes

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v3
- What OS and web server you're running Snipe-IT on - el capitan, apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - the whole thing
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). - not on demo
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
![screen shot 2016-04-20 at 1 58 14 pm](https://cloud.githubusercontent.com/assets/18450192/15225565/f242e322-184c-11e6-9512-c984e67cc95e.png)
![screen shot 2016-04-20 at 11 54 37 am](https://cloud.githubusercontent.com/assets/18450192/15225566/f25c0410-184c-11e6-992d-3c389701a8ff.png)
![screen shot 2016-04-20 at 11 55 24 am](https://cloud.githubusercontent.com/assets/18450192/15225567/f2603756-184c-11e6-8483-395c63d1ddc4.png)

**Comment by snipe** [comment]
In your browser console, please click on the error tab. The CSS declaration warnings don't matter, and just clutter up the debugging.

**Comment by nervouspotato** [comment]
Sorry,
I forgot to attach these.
![screen shot 2016-04-20 at 1 56 43 pm](https://cloud.githubusercontent.com/assets/18450192/15225747/cc7a4a6c-184d-11e6-9a8b-f8b2ae89e9a3.png)
![screen shot 2016-04-20 at 1 57 25 pm](https://cloud.githubusercontent.com/assets/18450192/15225748/cc7ae620-184d-11e6-86bc-413032d4bc05.png)

**Comment by snipe** [comment]
What do you see in your `public/build/assets/css` folder?

**Comment by nervouspotato** [comment]
app-aa4905dc46.css
app.css.map
compiled folder -> app-485a76ec8c.css , app.css.map

**Comment by snipe** [comment]
My guess would be that your URL is incorrect in the .env file. It should be `http://itms.rutgers.edu/assets`, not `http://itms.rutgers.edu`.

**Comment by snipe** [comment]
(Also be aware that v3 is not officially out yet, so it should not be used for production yet.)

**Comment by nervouspotato** [comment]
The URL is correct. We understand that it is not out yet and are just using the software for testing purposes right now till we sort this out.

**Comment by snipe** [comment]
We haven't thoroughly tested v3 running in a sub-directory yet. I've just pushed out a change to the v3 branch that may help with this, but you'll have to let me know.

**Comment by nervouspotato** [comment]
Oh okay, where is the update available? I'll definitely keep you posted :)

**Comment by snipe** [comment]
It's pushed out to the v3 branch, so just pull the latest from there.

**Comment by snipe** [comment]
Hi @nervouspotato - any updates here?
