### ISSUE TITLE
Email Notifications Upon License Expiration

### ISSUE THREAD

**Issue by dystopian1** [snipe/snipe-it#2038]
Firstly I love this app, it works perfectly for a need where I am employed.  If I am not using this correctly for what I have done below for notifications, please let me know.

#### Expected Behavior (or desired behavior if a feature request)

 Email sent to 'Send alerts to' email address in the overall settings

-----

#### Actual Behavior

Running this command on the server completes without error... but no email, no errors in the logs.
/usr/bin/php /var/www/snipeit/artisan alerts:expiring
0 expiring assets
1 expiring licenses

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode  - COMPLETED
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html) - COMPLETED

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 
   Snipe-IT version	v2.1.0-41-g6d810a9
PHP Version	5.5.9-1
Laravel Version	4.2.17

- What OS and web server you're running Snipe-IT on
ubuntu4.14

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh

- If you're getting an error in your browser, include that error
No errors.

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
NA

- If a stacktrace is provided in the error, include that too.
NA

- Any errors that appear in your browser's error console.
NA

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
NA

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
none

- Include what you've done so far in the installation, and if you got any error messages along the way.
No error messages along the way, all works great.

- Indicate whether or not you've manually edited any data directly in the database
none

**Comment by snipe** [comment]
Do you actually have mail configured correctly in your mail.php? (Does it work elsewhere, like forgotten password requests, etc?)

**Comment by dystopian1** [comment]
Mail is hosted at Rackspace Hosted Exchange.

Username and Password omitted:


<?php

return array(

    /*
    |--------------------------------------------------------------------------
    | Mail Driver
    |--------------------------------------------------------------------------
    |
    | Laravel supports both SMTP and PHP's "mail" function as drivers for the
    | sending of e-mail. You may specify which one you're using throughout
    | your application here. By default, Laravel is setup for SMTP mail.
    |
    | Supported: "smtp", "mail", "sendmail"
    |
    */

    'driver' => 'smtp',

    /*
    |--------------------------------------------------------------------------
    | SMTP Host Address
    |--------------------------------------------------------------------------
    |
    | Here you may provide the host address of the SMTP server used by your
    | applications. A default option is provided that is compatible with
    | the Postmark mail service, which will provide reliable delivery.
    |
    */

    'host' => 'smtp.emailsrvr.com',

    /*
    |--------------------------------------------------------------------------
    | SMTP Host Port
    |--------------------------------------------------------------------------
    |
    | This is the SMTP port used by your application to delivery e-mails to
    | users of your application. Like the host we have set this value to
    | stay compatible with the Postmark e-mail application by default.
    |
    */

    'port' => 587,

    /*
    |--------------------------------------------------------------------------
    | Global "From" Address
    |--------------------------------------------------------------------------
    |
    | You may wish for all e-mails sent by your application to be sent from
    | the same address. Here, you may specify a name and address that is
    | used globally for all e-mails that are sent by your application.
    |
    */

    'from' => array('address' => 'mail@domain', 'name' => 'Sys Admin'),

    /*
    |--------------------------------------------------------------------------
    | E-Mail Encryption Protocol
    |--------------------------------------------------------------------------
    |
    | Here you may specify the encryption protocol that should be used when
    | the application send e-mail messages. A sensible default using the
    | transport layer security protocol should provide great security.
    |
    */

    'encryption' => 'tls',

    /*
    |--------------------------------------------------------------------------
    | SMTP Server Username
    |--------------------------------------------------------------------------
    |
    | If your SMTP server requires a username for authentication, you should
    | set it here. This will get used to authenticate with your server on
    | connection. You may also set the "password" value below this one.
    |
    */

    'mail@domain.com' => null,

    /*
    |--------------------------------------------------------------------------
    | SMTP Server Password
    |--------------------------------------------------------------------------
    |
    | Here you may set the password required by your SMTP server to send out
    | messages from your application. This will be given to the server on
    | connection so that the application will be able to send messages.
    |
    */

    'PASSWORD' => null,

    /*
    |--------------------------------------------------------------------------
    | Sendmail System Path
    |--------------------------------------------------------------------------
    |
    | When using the "sendmail" driver to send e-mails, we will need to know
    | the path to where Sendmail lives on this server. A default path has
    | been provided here, which will work well on most of your systems.
    |
    */

    'sendmail' => '/usr/sbin/sendmail -bs',

    /*
    |--------------------------------------------------------------------------
    | Mail "Pretend"
    |--------------------------------------------------------------------------
    |
    | When this option is enabled, e-mail will not actually be sent over the
    | web and will instead be written to your application's logs files so
    | you may inspect the message. This is great for local development.
    |
    */

    'pretend' => false,

);

**Comment by snipe** [comment]
```
/*
|--------------------------------------------------------------------------
| SMTP Server Username
|--------------------------------------------------------------------------
|
| If your SMTP server requires a username for authentication, you should
| set it here. This will get used to authenticate with your server on
| connection. You may also set the "password" value below this one.
|
*/
'mail@domain.com' => null,
```

I think you changed the key instead of the value here. That should be:

```
'username' => 'mail@domain.com',
````

**Comment by dystopian1** [comment]
Yup, super derpy of me indeed.

Snipe, can you tell me what is the proper key for password as well?

**Comment by snipe** [comment]
Should be `password`, al lower case. 

![eyepoke](https://cloud.githubusercontent.com/assets/197404/15228669/338c52ce-1842-11e6-8d4f-8ca2851dbed4.gif)

(j/k - it's a pretty common mistake.)

**Comment by dystopian1** [comment]
Found it.

Snipe, thank you so much I'm passed this hurdle! You rock, and keep it up!  Tested/ Works... and of course 'The Jerk' is one of the greatest movies of all time... I'm honored.

**Comment by snipe** [comment]
Awesome, glad you got everything sorted! 

![high-five-light](https://cloud.githubusercontent.com/assets/197404/15229028/cc33198a-1843-11e6-908f-7669c5a7a726.gif)

(I'm still looking for my Special Purpose)
