### ISSUE TITLE
'MAC is invalid.'  Error

### ISSUE THREAD

**Issue by dystopian1** [snipe/snipe-it#2039]
#### Expected Behavior (or desired behavior if a feature request)

Ability to edit settings results in 500 error

-----

#### Actual Behavior

Error logs show:
[2016-05-12 16:19:04] production.ERROR: exception 'Illuminate\Encryption\DecryptException' with message 'MAC is invalid.' in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:144

Seems I accidentally hit the up in ubuntu and ran the command again:
/usr/bin/php /var/www/snipeit/artisan key:generate 

Problem is, I cannot seem to match the original key that was stored here:

app/config/production/app.php

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode - Yes, this presented the error originally.
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
Yes, which is why I fear I might be SOL here!

**Comment by snipe** [comment]
If you don't have the original app key, you'll want to disable LDAP integration via the database (change the `ldap_enabled` setting to `0`). You'll need to re-enter the LDAP password and re-enabled LDAP.

**Comment by dystopian1** [comment]
Thank you for the quick reply and help.

I do not believe I had LDAP enabled on this config.  I have however attempted your resolution:

UPDATE settings SET ldap_enabled = 0;

with the result:

select ldap_enabled FROM settings;
+--------------+
| ldap_enabled |
+--------------+
| 0            |
+--------------+
1 row in set (0.00 sec)

I did logout and back into Snipe It with the same error. 

Thank you again for your time in this.

**Comment by snipe** [comment]
Try this:

`composer dump-autoload`
`composer clear-cache`

**Comment by snipe** [comment]
(Also clear browser cookies)

**Comment by dystopian1** [comment]
Sorry for bugging you so much today out of nowhere.

I'm not as familiar with composer, but read up on it from where you reference it here:

http://docs.snipeitapp.com/upgrading.html

and here:

https://getcomposer.org/doc/01-basic-usage.md

While I am able to install and run the commands, I do not believe they are doing what they are supposed to.

Any further advice?

**Comment by snipe** [comment]
> I do not believe they are doing what they are supposed to.

Can you explain what you mean? What are you seeing on screen?

**Comment by dystopian1** [comment]
/var/www/snipeit/app/config/production# php composer.phar clear-cache
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Clearing cache (cache-dir): /root/.cache/composer
Clearing cache (cache-files-dir): /root/.cache/composer/files
Clearing cache (cache-repo-dir): /root/.cache/composer/repo
Cache directory does not exist (cache-vcs-dir):
All caches cleared.

My guess is I installed this in the wrong directory, by it referencing /root above.

**Comment by snipe** [comment]
Did you install/run composer as root when you first installed?

**Comment by dystopian1** [comment]
Yes that is correct

**Comment by snipe** [comment]
Okay, you shouldn't have done that. Can you try reinstalling as a regular user? 

http://docs.snipeitapp.com/installation/composer.html
<img width="759" alt="screen shot 2016-05-12 at 3 32 37 pm" src="https://cloud.githubusercontent.com/assets/197404/15232529/ce6f1e84-1856-11e6-9e8f-667a83f8f002.png">

**Comment by dystopian1** [comment]
Thank you again,

Are there certain settings required for 'composer.json?'

"Composer could not find a composer.json file in /var/www/snipeit
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section"

**Comment by snipe** [comment]
What command are you running when you see that?

Also, can you tell me the contents of `/var/www/snipeit`?

**Comment by dystopian1** [comment]
ok I re-ran the installer because I wiped out the vendor folder, this recreated it.  Looks like composer re-installed with the ./install.sh file, and I reconnected the working db.. and im back in.

www-data is the owner of the files, so I'm temporarily su'ing to that user to run the commands.

I am running the following with the results in the install folder:

www-data@ubuntuDemo:~/snipeit$ composer dump-autoload
Generating autoload files
www-data@ubuntuDemo:~/snipeit$ composer clear-cache
Clearing cache (cache-dir): /var/www/.cache/composer
Clearing cache (cache-files-dir): /var/www/.cache/composer/files
Clearing cache (cache-repo-dir): /var/www/.cache/composer/repo
Cache directory does not exist (cache-vcs-dir):
All caches cleared.

Here are the contents:

drwxr-xr-x 13 www-data www-data   4096 May 12 19:27 app
-rwxr-xr-x  1 www-data www-data   2451 May 12 19:27 artisan
drwxr-xr-x  2 www-data www-data   4096 May 12 19:27 bootstrap
-rwxr-xr-x  1 www-data www-data 121120 May 12 19:27 CHANGELOG.md
-rw-r--r--  1 www-data www-data    364 May 12 19:27 codeception.yml
-rw-r--r--  1 www-data www-data   1577 May 12 19:27 CODE_OF_CONDUCT.md
-rwxr-xr-x  1 www-data www-data   1933 May 12 19:27 composer.json
-rw-r--r--  1 www-data www-data 170802 May 12 19:27 composer.lock
-rwxr-xr-x  1 www-data www-data    390 May 12 19:27 CONTRIBUTING.md
drwxr-xr-x  2 www-data www-data   4096 May 12 19:27 docker
-rw-r--r--  1 www-data www-data    506 May 12 19:27 docker.env
-rw-r--r--  1 www-data www-data   2786 May 12 19:27 Dockerfile
-rw-r--r--  1 www-data www-data     67 May 12 19:27 .dockerignore
drwxr-xr-x  5 www-data www-data   4096 May 12 19:27 docs
-rw-r--r--  1 www-data www-data   1711 May 12 19:27 gh-changelog.php
-rwxr-xr-x  1 www-data www-data     11 May 12 19:27 .gitattributes
drwxr-xr-x  2 www-data www-data   4096 May 12 19:27 .github
-rwxr-xr-x  1 www-data www-data    649 May 12 19:27 .gitignore
-rwxr-xr-x  1 www-data www-data  34519 May 12 19:27 LICENSE
-rwxr-xr-x  1 www-data www-data    636 May 12 19:27 phpunit.xml
drwxr-xr-x  6 www-data www-data   4096 May 12 19:27 public
-rwxr-xr-x  1 www-data www-data   4128 May 12 19:27 README.md
-rwxr-xr-x  1 www-data www-data    522 May 12 19:27 server.php
drwxr-xr-x  8 www-data www-data   4096 May 12 19:27 tests
-rwxr-xr-x  1 www-data www-data   1977 May 12 19:27 .travis.yml
drwxr-xr-x 36 www-data www-data   4096 May 12 19:30 vendor

**Comment by snipe** [comment]
Okay, that looks better. 

Are you still getting the Mac is Invalid message?

**Comment by dystopian1** [comment]
Correct:

 production.ERROR: exception 'Illuminate\Encryption\DecryptException' with message 'MAC is invalid.' in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:144

**Comment by snipe** [comment]
Did you ever have LDAP enabled, or did you enter a password for LDAP at any point?

**Comment by dystopian1** [comment]
I really do not believe I enabled that yet.

**Comment by snipe** [comment]
Can you check the settings table to confirm?

**Comment by dystopian1** [comment]
Checked that too still the same there:

mysql> select ldap_enabled FROM settings;
+--------------+
| ldap_enabled |
+--------------+
| 0            |
+--------------+
1 row in set (0.00 sec)

I checked that too.

I also just attempted re-running:
/usr/bin/php /var/www/snipeit/artisan key:generate --env=production

Checked the key matched in app/config/production.app.php

Then ran again:
composer dump-autoload
composer clear-cache

Empty cache in browser.

Re-login to snipeit, still getting error on edit settings

Thank you still for your help :)

**Comment by snipe** [comment]
I don't need that, I need the value of `ldap_pword`

**Comment by snipe** [comment]
Don't re-run the key generator. The problem is that you don't have your old (original) app key, so generating a new one won't help.

**Comment by dystopian1** [comment]
mysql> select ldap_pword FROM settings;
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ldap_pword                                                                                                                                                                                                                                           |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| eyJpdiI6ImN6NVhiZXNrZ

Looks like there was a password set there indeed.  I do have partners that might have set passwords but not enabled LDAP?

**Comment by snipe** [comment]
Okay, clear out that value, and try logging in again. If that works MAKE SURE you store a copy of your app key somewhere so you don't run into this issue again.

**Comment by dystopian1** [comment]
Ah snipe thank you so much! Your dedication has been extremely helpful!!

I'm back in, commands run:

use snipeit;
UPDATE settings SET ldap_pword = NULL WHERE id = 1;

Backing everything up, recording key.. thank you again.

**Comment by snipe** [comment]
Great - now that you're back in (and have a copy of your app key in a safe place for backup), you can re-enable LDAP if you need to. 

The issue is that your LDAP password is encrypted on the server, and Snipe-IT needs that app key to decrypt it. If the app key isn't the same one it was encrypted with, things get very ugly.

That's handled a little more elegantly in v3, and there is a cli utility to disable LDAP in case someone gets stuck, but until v3 is out, the only way around it is to blow out the LDAP settings.

**Comment by dystopian1** [comment]
Makes sense, and thank you for the explanation.

Can't wait till v3 is out, I'll stop breaking this version on my server so you can get more to it ;)
