### ISSUE TITLE
expiring license no alerts / crontab?

### ISSUE THREAD

**Issue by PRNOHFT** [snipe/snipe-it#2040]
#### Expected Behavior (or desired behavior if a feature request)

Basically I expect an email alert stating that my license/warranty is expiring.

-----

#### Actual Behavior

Nothing happens.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

_________________________________________________

Hey snipe,

I've managed to get snipe up, email alerts OK (tested with Forgot Password) and created a few samples to test the alerts. I don't know why I could not get it to work as I wanted. I've narrowed it down to these;

1.) php location
2.) wrong crontab / cronjob

I am running on a fresh Ubuntu 14.04 VM. Installed it using the install.sh script. Snipe is working fine, SMTP is fine. I just can't get it to work though. Here is the crontab command that I used. Note that I'm not an Ubuntu veteran (more like a relearning beginner) and I've Googled all over but to no avail.

crontab -e (non-root)
45 9 * * * /etc/php5 /var/www/snipeit/artisan alerts:expiring
0 10 * * * /usr/bin/php5 /var/www/snipeit/artisan alerts:expiring 
@daily /bin/php /var/www/snipeit/artisan alerts:expiring
@daily /usr/bin/php /var/www/snipeit/artisan alerts:expiring

I did the same with sudo crontab -e but nothing appeared so far. I left it on for 24 hours just to see if I could get anything.

Heres my crontab logs.

sudo grep cron /var/log/syslog

May 12 17:38:09 ubuntu kernel: [169694.045097] init: cron main process (1017) killed by TERM signal
May 12 17:38:09 ubuntu cron[21449]: (CRON) INFO (pidfile fd = 3)
May 12 17:38:09 ubuntu cron[21450]: (CRON) STARTUP (fork ok)
May 12 17:38:09 ubuntu cron[21450]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
May 12 18:17:01 ubuntu CRON[21497]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May 12 18:33:43 ubuntu crontab[21537]: (radius) BEGIN EDIT (radius)
May 12 18:34:06 ubuntu crontab[21537]: (radius) REPLACE (radius)
May 12 18:34:06 ubuntu crontab[21537]: (radius) END EDIT (radius)
May 12 18:34:11 ubuntu kernel: [173054.397494] init: cron main process (21450) killed by TERM signal
May 12 18:34:11 ubuntu cron[21563]: (CRON) INFO (pidfile fd = 3)
May 12 18:34:11 ubuntu cron[21564]: (CRON) STARTUP (fork ok)
May 12 18:34:11 ubuntu cron[21564]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
May 12 19:04:49 ubuntu crontab[21617]: (radius) BEGIN EDIT (radius)
May 12 19:05:16 ubuntu crontab[21631]: (root) BEGIN EDIT (root)
May 12 19:08:28 ubuntu crontab[21631]: (root) REPLACE (root)
May 12 19:08:28 ubuntu crontab[21631]: (root) END EDIT (root)
May 12 19:08:37 ubuntu kernel: [175118.978000] init: cron main process (21564) killed by TERM signal
May 12 19:08:37 ubuntu cron[21651]: (CRON) INFO (pidfile fd = 3)
May 12 19:08:37 ubuntu cron[21652]: (CRON) STARTUP (fork ok)
May 12 19:08:37 ubuntu cron[21652]: (CRON) INFO (Skipping @reboot jobs -- not system startup)
May 12 19:17:01 ubuntu CRON[21672]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May 12 20:17:01 ubuntu CRON[21806]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May 12 21:01:40 ubuntu crontab[21617]: (radius) END EDIT (radius)
May 12 21:17:01 ubuntu CRON[22028]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May 12 22:17:01 ubuntu CRON[22073]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
May 12 23:17:01 ubuntu CRON[22114]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)

Appreciate all the help.

Thanks and keep being awesome!

**Comment by snipe** [comment]
When you run the commands manually (outside of cron), what is the output?

**Comment by PRNOHFT** [comment]
Wow you're fast! Barely enough time to spin my chair 360 degrees!

I got this on my 2nd command.

/usr/bin/php5 /var/www/snipeit/artisan alerts:expiring 
3 expiring assets
1 expiring licenses
Could not send email. No alert email configured in settings. 

Hmmm... Strange that they stated no alert email is configured in settings. Did I miss out anything? Just to check, to ensure that you SMTP is working, you can just run the Forget Password and if you get an email, it means that its working? Sorry for the bother.

**Comment by adam820** [comment]
Under Settings -> General Settings -> "Send alerts to", do you have an email entered and the box checked? Without an email entered you get what you reported. Without the box checked you get "Alerts are disabled in the settings. No mail will be sent."

**Comment by PRNOHFT** [comment]
Thanks for that, @adam820 . Now I feel dumb for not checking that part out. Thanks for the help!
