### ISSUE TITLE
the requested url /auth/signin was not found on this server - Windows/Apache

### ISSUE THREAD

**Issue by Dave-Morton** [snipe/snipe-it#2041]
I know that there are several issues about this, but looking through them did not provide anything beneficial in my case, so here we go again. I've not only provided the requested info, below, but also some additional info that may prove relevant, if not helpful.

#### Expected Behavior (or desired behavior if a feature request)

I expect to see the login page

-----

#### Actual Behavior

I get the "Whoops!" page, with the following message:

^Server Error: 404 (Not Found)
-----

#### Please confirm you have done the following before posting your bug report:

- [**x**] I have enabled debug mode
- [**x**] I have read the [Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

Snipe-IT version: Latest (just installed today, via composer)
OS: Windows 10
Server: Apache 2.4.17
PHP: 5.6.18
Install method: Composer
Specific Snipe-IT page: [base_url]/public/auth/signin
Stack Trace: 
```text
#0 P:\HTTP\RDM\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1054): Illuminate\Routing\RouteCollection->match(Object(Illuminate\Http\Request))
#1 P:\HTTP\RDM\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1022): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 P:\HTTP\RDM\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#3 P:\HTTP\RDM\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#4 P:\HTTP\RDM\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#5 P:\HTTP\RDM\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#6 P:\HTTP\RDM\snipe-it\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#7 P:\HTTP\RDM\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#8 P:\HTTP\RDM\snipe-it\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#9 P:\HTTP\RDM\snipe-it\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#10 P:\HTTP\RDM\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#11 P:\HTTP\RDM\snipe-it\public\index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
```
Browser Console Log:
```text
Timestamp: 5/13/2016 8:21:40 AM
Error: ReferenceError: jQuery is not defined
Source File: http://dmorton.no-ip.info/rdm/snipe-it/public/auth/signin
Line: 1253
```
**Additional Info:**

Apache VHOST data:
```text
<VirtualHost *:80>
    Alias /snipe-it "P:/HTTP/RDM/snipe-it/public"
    <Directory P:/HTTP/RDM/snipe-it/public>
        Require all granted
        AllowOverride All
        Options +Indexes
    </Directory>
    DocumentRoot "P:/HTTP/RDM/snipe-it/public"
    ServerName dmorton.no-ip.info
    # Other directives here
    ErrorLog "P:/logs/snipe-it.error.log"
    CustomLog "P:/logs/snipe-it.access.log" common
</VirtualHost>
```

DocRoot .htaccess file:
```text
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>
    RewriteEngine On
    RewriteBase /RDM/snipe-it
    RewriteRule ^(.*)/$ /$1 [L,R=301]
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
```
*note:* placing garbage in this file "blows up" the server, and removing the file altogether does not change the behavior.

snipe-it/public .htaccess file:

```text
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Uncomment these two lines to force SSL redirect
    # RewriteCond %{HTTPS} off
	# RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
    #RewriteRule ^ foo.php [L]
</IfModule>
```
*note:* Commenting out the reference to index.php and un-commenting the one for foo.php successfully redirects, as expected.

**Environment used and Settings for various config files:**
environment: production
bootstrap/start.php: 'production' => [ 'dmorton' ]

app/config/production/app.php:
'url' => 'http://dmorton.no-ip.info/RDM/snipe-it/public',
'domain' => 'dmorton.no-ip.info',

app/config/production\database.php:
connections['mysql'] is setup correctly (data not provided to keep things safe - gonna have to trust me here)

app/storage/logs: Data is already provided, above.

Install process followed:

composer global require laravel/install
{set vendor dir in Windows path}
{navigate to RDM folder}
git clone https://github.com/snipe/snipe-it snipe-it
{navigate to snipe-it folder}
{configure files to values listed above}
composer install --no-dev --prefer-source
php artisan app:install --env=production
{navigate browser to [base_url]/snipe-it/}

*note:* No error messages were encountered, and no data was altered in the database. Also, I've read several issues that contained the same text as the title of this issue, and none of the suggestions/instructions have lead to a solution, so far.

**Comment by snipe** [comment]
`'url' => 'http://dmorton.no-ip.info/RDM/snipe-it/public',` ,_ the URL should never have `public` in it.

**Comment by Dave-Morton** [comment]
Ok, fair enough. I'd say that I'll correct it, but the boss has decided (after several hours of my time spent) to go another direction. But still, I'll keep this in mind for any future projects. Thanks.
