### ISSUE TITLE
Multiple-Quantity removed and Ability to Add quantities for rotating consumable stock.

### ISSUE THREAD

**Issue by dmccabe-kinex** [snipe/snipe-it#2042]
#### Expected Behavior (or desired behavior if a feature request)

I would like to see a feature where users can check-out quantities of a consumable item, rather than one at a time. I would also like to be able to add quantities so that when I get low on things like RJ45 connectors, or fiber patch panels, rather than receiving it as a duplicate item with another quantity, I can just add it to the quantity remaining.

---
#### Actual Behavior

(what actually happens goes here)

---
#### Please confirm you have done the following before posting your bug report:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running 
  2.1
- What OS and web server you're running Snipe-IT on
  Ubuntu 14.04LTS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  Install.sh
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
  Consumables
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by tsilman-marquette** [comment]
I would like this also.
