### ISSUE TITLE
Unable to get snipe-it interface on browser

### ISSUE THREAD

**Issue by Sakshi-j** [snipe/snipe-it#2046]
When entering URL for snipe-it interface it is generating exceptions.

Getting following errors:
 
![snipe_error](https://cloud.githubusercontent.com/assets/19387598/15319517/d8c6695a-1c48-11e6-8780-408cf2a899fa.png)

ErrorException (E_ERROR)

SQLSTATE[28000] [1045] Access denied for user 'snipeit'@'localhost' (using password: NO) (View: /var/www/html/snipeit/app/views/backend/layouts/default.blade.php) (View: /var/www/html/snipeit/app/views/backend/layouts/default.blade.php)

**Comment by IxFail** [comment]
Please provide us with the information requested at the Getting Help documentation: http://docs.snipeitapp.com/getting-help.html

**Comment by snipe** [comment]
Looks like your database credentials are incorrect

**Comment by Sakshi-j** [comment]
I am able to login into the database CLI using the same credentials.

Please help me correct the credentials if it needs to be reset.

**Comment by snipe** [comment]
@Sakshi-j http://www.cyberciti.biz/faq/mysql-change-user-password/
