### ISSUE TITLE
FYI: I've made a simple API and Android app

### ISSUE THREAD

**Issue by skylarmt** [snipe/snipe-it#2054]
I sat down the other day and made an app and simple JSON API for SnipeIT.  It connects to the database directly and supports basic asset/accessory/consumable search, editing, and creation.  It has support for scanning barcodes for both search and data (serial, asset tag, etc) entry.

I decided to release the code so someone else can maybe use it.

The PHP API (heavily commented, self explanatory) can be found here: https://github.com/skylarmt/SnipeITAPI

The sources for the Cordova/Phonegap/HTML5 user app can be found here: https://github.com/skylarmt/SnipeITMobileApp

The app should run on any modern browser, but barcode scanning won't work (for obvious reasons).  The app will be on Google Play (with scanning) in a few hours at https://play.google.com/store/apps/details?id=com.netsyms.SnipeITMobile.

I just thought you guys might want to know about this!

**Comment by dmeltzer** [comment]
It's cool.  If you wanted to continue this project I'd suggest taking a look at the laravel framework that snipe-it uses already and trying to integrate it a bit more. There already is a decent read-only api (check out routes.php) that returns json. Modifying the database directly could lead to many issues as the app gets developed further, but you could probably add an api that responds to POSTS as well without a terrible amount of work.  I'm sure Snipe will have more opinions though.

**Comment by snipe** [comment]
Hi @skylarmt - thanks for your efforts and your interest! If you're interested in working on something that we could integrate into the official source, let me know and I can probably point you in the right direction. As @dmeltzer mentioned, we already have a JSON endpoint for most of the read-only things, and we're working on a more robust API once v3 is released. For something official, we'd want to make sure we're using the Snipe-IT models, so that the model-level validation and database relationships remain intact.

I also have to ask that you update the description in the Google Play store to note that the app is not officially supported by Snipe-IT. People can't always figure that out, and we'll end up with some very confusing GH issues.

**Comment by skylarmt** [comment]
@snipe Good point about the support, I've updated the app description.

**Comment by elbubar** [comment]
@snipe Hi, I'm very interested in your production, unfortunately, it seems that you restricted the access to the app on a geographical criteria. Could you allow all countries ?
Thanks a lot.

**Comment by skylarmt** [comment]
@elbubar, I unpublished the app because the server-side code for it doesn't work with newer versions of Snipe-IT's database.  You can still install the app from [here](https://github.com/skylarmt/SnipeITMobileApp/raw/master/snipeit-release-1.0-googleplay.apk), and if you want to modify the PHP API I wrote to work with new versions of Snipe-IT, be my guest.

Shameless plug: If you need a mobile inventory app, I've actually written my own open source PHP inventory system that has one.  It doesn't have as many features as Snipe-IT, but it does have the basics.  [Source code](https://source.netsyms.com/Business/BinStack), [website](https://netsyms.biz/apps/binstack/).

**Comment by anhhtz** [comment]
Any React Native source ?

**Comment by anhhtz** [comment]
> @elbubar, I unpublished the app because the server-side code for it doesn't work with newer versions of Snipe-IT's database. You can still install the app from [here](https://github.com/skylarmt/SnipeITMobileApp/raw/master/snipeit-release-1.0-googleplay.apk), and if you want to modify the PHP API I wrote to work with new versions of Snipe-IT, be my guest.
> 
> Shameless plug: If you need a mobile inventory app, I've actually written my own open source PHP inventory system that has one. It doesn't have as many features as Snipe-IT, but it does have the basics. [Source code](https://source.netsyms.com/Business/BinStack), [website](https://netsyms.biz/apps/binstack/).

Why do not use integrated Api snipe-it ? [https://snipe-it.readme.io/reference#api-overview](https://snipe-it.readme.io/reference#api-overview)

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference#api-overview">Overview</a></strong></div><div>Snipe-IT is a free, open source IT asset management system. Features include management of assets, users, licenses, accessories, consumables and components, as well as two-factor authentication, LDAP/AD syncing, and asset acceptance confirmation.</div></blockquote>
