### ISSUE TITLE
SQLSTATE error on migration

### ISSUE THREAD

**Issue by zmorrow** [snipe/snipe-it#2058]
#### Expected Behavior (or desired behavior if a feature request)

Looking for migration to complete successfully.

-----

#### Actual Behavior

This is copied from the command line:

Basic usage: composer <command>
For more information just type "composer".

C:\inetpub\wwwroot\snipe-it>php artisan migrate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

  _**[Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'option_
  name'; check that column/key exists (SQL: alter table `settings` drop `opti
  on_name`)

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'option_
  name'; check that column/key exists**_

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running- Trying to update to 3.0
- What OS and web server you're running Snipe-IT on- Server 2012 R2, IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)- manual installation
- If you're getting an error in your browser, include that error-  I have debug set to true but all that shows is-- Whoops, looks like something went wrong.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error-  trying to access login page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs  LARAVEL.log
.[2016-05-20 13:48:26] production.ERROR: exception 'ErrorException' with message 'mcrypt_encrypt(): Key of size 0 not supported by this algorithm. Only keys of sizes 16, 24 or 32 supported' in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Encryption\McryptEncrypter.php:104
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'mcrypt_encrypt(...', 'C:\\inetpub\\wwwr...', 104, Array)
#1 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Encryption\McryptEncrypter.php(104): mcrypt_encrypt('rijndael-256', '', 's:40:"u3XGLZ8bm...', 'cbc', 'qb\x85\xFD\x89\xB2\x18\x98\xC3\xF6\x18\x9F\xCC\xA6\x1A...')
#2 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Encryption\McryptEncrypter.php(77): Illuminate\Encryption\McryptEncrypter->padAndMcrypt('u3XGLZ8bmRkn1Nd...', 'qb\x85\xFD\x89\xB2\x18\x98\xC3\xF6\x18\x9F\xCC\xA6\x1A...')
#3 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13046): Illuminate\Encryption\McryptEncrypter->encrypt('u3XGLZ8bmRkn1Nd...')
#4 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13010): Illuminate\Cookie\Middleware\EncryptCookies->encrypt(Object(Illuminate\Http\RedirectResponse))
#5 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#6 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9895): call_user_func_array(Array, Array)
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9880): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8161): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8152): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#13 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8142): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#14 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(2400): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#15 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#16 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckForSetup.php(22): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 [internal function]: App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9895): call_user_func_array(Array, Array)
#20 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 [internal function]: App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9895): call_user_func_array(Array, Array)
#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\XssProtectHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9895): call_user_func_array(Array, Array)
#30 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 [internal function]: App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9895): call_user_func_array(Array, Array)
#35 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13334): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9895): call_user_func_array(Array, Array)
#40 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#42 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(11880): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9895): call_user_func_array(Array, Array)
#45 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#47 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(3250): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9895): call_user_func_array(Array, Array)
#50 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#52 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9880): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#54 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(2347): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#55 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(2331): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#56 C:\inetpub\wwwroot\snipe-it\public\index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#57 {main}  

- Include what you've done so far in the installation, and if you got any error messages along the way. -  I am on Step 7 of the upgrade instructions.

 Indicate whether or not you've manually edited any data directly in the database. -- I believe so but I only edited items I didn't add any tables or anything.

**Comment by dmeltzer** [comment]
Hi, 

Are you using sqlite by any chance?

**Comment by zmorrow** [comment]
Hey, no just mysql.

**Comment by dmeltzer** [comment]
Tracked down the problem.  Working on a fix presently.  The code that deleted the option_name and option_value previously was commented out when imported to v3, so the migrations run fine on a new database but not one that has been used for 2.*

**Comment by zmorrow** [comment]
You da man!  Thanks bud!!

**Comment by dmeltzer** [comment]
If you have the chance to test the commit in PR #2060 and see if it makes your life better, that would be great!

**Comment by zmorrow** [comment]
I responded over on #2060 , still not liking it when I un-comment those lines.  Thanks for the help!

**Comment by snipe** [comment]
Are you still having this issue wit the latest off v3 branch?

**Comment by zmorrow** [comment]
Im good, had an issue with importing yesterday but did a fresh pull and all good now.  Thanks again you are awesome!
