### ISSUE TITLE
IIS Error 500 (Internal Server Error) When Checking In/Out Assets

### ISSUE THREAD

**Issue by nclaypool** [snipe/snipe-it#2061]
#### Expected Behavior (or desired behavior if a feature request)

When I check-in or check-out an asset the record should update then return me to the hardware item that was affected or the asset list.

-----

#### Actual Behavior

This only happens on assets when checking in or checking out, all other areas of Snipe are behaving just fine, even checking in/out licenses. The form is displayed I select the user who's checking the asset out then when I click check out I get "Server Error: 500 (Internal Server Error)". When I return to the asset I see that it was still checked out, its just the redirect I would imagine that's failing. I enabled debug mode and received this message when troubleshooting: Expected response code 250 but got code "530", with message "530 5.7.1 Client was not authenticated " This behavior didn't begin until I recently updated to version 2.1.0-47-g39f40a3

-----

#### Please confirm you have done the following before posting your bug report:

- [Yes] I have enabled debug mode
- [Yes] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v2.1.0-47-g39f40a3
- What OS and web server you're running Snipe-IT: Windows Server 2012 R2, IIS 7.0
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual
- If you're getting an error in your browser, include that error: Browser indicates 500, debug indicates 530.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Any asset, checking in or checking out, occurs when "Checkin" button is clicked on the "Checkin Asset" page.
- If a stacktrace is provided in the error, include that too: NA
- Any errors that appear in your browser's error console: NA
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): Not reproduceable.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs: Reference to error not found in app/storage/logs or IIS Logs.
- Include what you've done so far in the installation, and if you got any error messages along the way: Like I said, everything else works, its just this one little thing falling off the rails.
- Indicate whether or not you've manually edited any data directly in the database: Nope

**Comment by snipe** [comment]
This looks like an error in your mail configuration. http://www.servolutions.com/support/articles/exchange2007clientnotauth.htm

**Comment by nclaypool** [comment]
My SMTP Relay on my Exchange server is already set to allow Anonymous connections from that server.  I also fiddled with the mail.php file and changed the server hostname to be null, the same error was presented, don't know if that's telling of anything or not.

**Comment by nclaypool** [comment]
Update: You're on the right track though, when I set "pretend" to true the error messages disappeared.

**Comment by nclaypool** [comment]
Bingo, got it fixed. Not sure why the problem didn't rear itself until the upgrade but the port number was wrong and it was trying to use encryption the server wasn't set to accept. 

Thank you for your guidance.
