### ISSUE TITLE
Unable to edit current user permissions v3.0

### ISSUE THREAD

**Issue by zmorrow** [snipe/snipe-it#2062]
#### Expected Behavior (or desired behavior if a feature request)

Admin user should have super user access to Snipe.

-----

#### Actual Behavior

Admin users are unable to see anything other than their own asset page.  I go to the user and choose the permissions tab and select grant super user and when I save I get these errors.

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running-  v3.0
- What OS and web server you're running Snipe-IT on-  Server 2012 R2, IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)- Manual Install
- If you're getting an error in your browser, include that error--Shows 2 errors

1/2
PDOException in Connection.php line 431:
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`snipeit_laravel`.`users`, CONSTRAINT `users_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`))

2/2
QueryException in Connection.php line 673:
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`snipeit_laravel`.`users`, CONSTRAINT `users_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)) (SQL: update `users` set `permissions` = {"superuser":"1","admin":"0","reports.view":"0","licenses.keys":"0"}, `updated_at` = 2016-05-20 17:54:33, `company_id` = where `id` = 3)

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error-  User>Permissions tab>Save new permission

**Comment by zmorrow** [comment]
This was a migration to v3.0 not a new install.

**Comment by zmorrow** [comment]
The group all of the admin users are in is called Admin, when I go in to edit the group I get an error but all other groups are fine and I am able to create other groups.

**Comment by snipe** [comment]
What version were you upgrading from?

**Comment by zmorrow** [comment]
2.1.0

**Comment by snipe** [comment]
Weird... that company_id foreign key constraint should have been removed in much earlier migrations.

**Comment by zmorrow** [comment]
I think I started at v2.0 so no telling what I may of accidentally messed with at each upgrade.

**Comment by snipe** [comment]
It's not your fault. There was a bad migration in a PR a long time ago (when company scoping was introduced), and it was breaking on some people's machines. I thought I fixed that a while ago (per #1400), so I'm not sure what's going on.

**Comment by zmorrow** [comment]
Weird, it won't let me edit them either, otherwise I would just edit their email address and put them in a new group.  Will try and find a workaround for now.  Thanks!

**Comment by snipe** [comment]
Do you have access to the DB via phpmyadmin or anything?

**Comment by zmorrow** [comment]
Yes ive got workbench on here.

**Comment by snipe** [comment]
Can you show me a screenshot of the structure of your users table?

**Comment by zmorrow** [comment]
![snipe1](https://cloud.githubusercontent.com/assets/14094117/15437563/d1905944-1e95-11e6-98c7-382924f00d62.JPG)

**Comment by snipe** [comment]
Can you disclose the foreign keys section for me?

**Comment by zmorrow** [comment]
![snipe2](https://cloud.githubusercontent.com/assets/14094117/15437584/f0ffe07e-1e95-11e6-9a9b-4d7338f4241d.JPG)

**Comment by zmorrow** [comment]
![snipe3](https://cloud.githubusercontent.com/assets/14094117/15437590/f4f53e68-1e95-11e6-8cbf-aaf8f1bbaee8.JPG)

**Comment by snipe** [comment]
Can you delete that foreign key and try editing the user again?

**Comment by snipe** [comment]
(That foreign key has been the bane of my existence.... sigh.)

**Comment by zmorrow** [comment]
How do I delete, I right click and the only options are to Create Schema.. or Refresh all, weird.

**Comment by snipe** [comment]
`ALTER TABLE users 
DROP FOREIGN KEY users_company_id_foreign;`

**Comment by snipe** [comment]
(I don't use Workbench, so I'm not sure how they want you to do it.)

**Comment by zmorrow** [comment]
I had to do some googling but was able to drop it in workbench and I am able to edit the user now and they can login and see everything permitted.  I created a group called administrators to move every one too, I suspect the one named admin is going to be an issue as I still get an error when I try to edit it but that is an easy fix.  Thanks for your help!

**Comment by snipe** [comment]
What error are you getting now when you try to edit?

**Comment by zmorrow** [comment]
1/2
ErrorException in 2005b09d18fc304313990c437db64393eb516394.php line 71:
Undefined index: superuser

ErrorException in 2005b09d18fc304313990c437db64393eb516394.php line 71:
Undefined index: superuser (View: C:\inetpub\wwwroot\snipe-it\resources\views\groups\edit.blade.php)

**Comment by snipe** [comment]
Using old data, I'm able to reproduce this now. Working on a fix.

**Comment by snipe** [comment]
Can you do a fresh pull and see if that fixes it?

**Comment by zmorrow** [comment]
Sorry, what do you mean by a fresh pull, grab the new zip file and copy over the current install?

**Comment by snipe** [comment]
Yeah, sorry. https://github.com/snipe/snipe-it/archive/v3.zip (That zip will always have the latest from the v3 branch)

**Comment by zmorrow** [comment]
It works now, thanks again!

**Comment by snipe** [comment]
Awesome!
