### ISSUE TITLE
V3 Alpha - Backups from Application are reported to be successful, no files created

### ISSUE THREAD

**Issue by brianjking** [snipe/snipe-it#2064]
####Expected Behavior (or desired behavior if a feature request)

* Backup to be available for download 
-----

#### Actual Behavior

* Success admonition message appears 
* No backup files are available from frontend application nor when navigating to appropriate directory via CLI or FTP
* No messages seen in `laravel.log` or Chrome console reporting issues.
* directory permissions set as per readme.io site instructions.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
What OS are you on?

**Comment by snipe** [comment]
(Server OS, obviously)

**Comment by brianjking** [comment]
CENTOS 6.7 x86_64

**Comment by brianjking** [comment]
Backups were working fine on 2.1.0, just fyi.

**Comment by snipe** [comment]
Yeah, we had to change the backup package to work with Laravel 5.2. 

In your cli, can you type in `which mysqldump`? There was a new .env variable added after v3-alpha was released, called `DB_DUMP_PATH`:
https://snipe-it.readme.io/v3.0/docs/configuration#required-database-settings

Add that to your env and make sure the path there matches whatever your system says for where mysqldump lives.

**Comment by brianjking** [comment]
@snipe 

`$ which mysqldump`
`$ /usr/bin/mysqldump`

Added to `.env`

```
DB_DUMP_PATH='/usr/bin/mysqldump' 
```
Still no files created, same success message shown, no errors seen.

**Comment by snipe** [comment]
It should be the path to the mysqldump directory, not to the binary. 

`DB_DUMP_PATH=/usr/bin'`

**Comment by brianjking** [comment]
Ah, okay. Sorry! I did notice this too (before making this change you've mentioned above)
```
php artisan backup:run
Starting backup...
Dumping database dockbiz_snipeit...
Backup failed because The dump process failed with exitcode 126 : Invoked command cannot execute : sh: /usr/bin/mysqldump/mysqldump: Not a directory
```

**Comment by brianjking** [comment]
Backups work, closing.

Solution: https://github.com/snipe/snipe-it/issues/2064#issuecomment-220686409

Thanks! 👍
