### ISSUE TITLE
V3 Alpha - Users in Admin Group are only shown their assets. Unable to edit some groups permissions.

### ISSUE THREAD

**Issue by brianjking** [snipe/snipe-it#2072]
#### Expected Behavior (or desired behavior if a feature request)

* Users in Admin group can access all assets, settings, etc.

-----

#### Actual Behavior

* Logged in as a user that has "Admin" group assigned and was only shown the assets checked out to her particular account.
* No other permissions were given.
* Did not have this issue in 2.1.0

* Attempted to edit groups and ran into issue that seems to be same as #2062 
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

![image](https://cloud.githubusercontent.com/assets/6786817/15477466/5d099f08-20da-11e6-81fd-0240513242c4.png)

![image](https://cloud.githubusercontent.com/assets/6786817/15477509/a0b4ecc6-20da-11e6-8262-7f0dee8b1ad5.png)

**Comment by brianjking** [comment]
If I attempt to edit the group permissions this is where I run into the issue I believe related to #2062 

![image](https://cloud.githubusercontent.com/assets/6786817/15477587/fbbecd12-20da-11e6-9f5b-3133ff8d3553.png)

**Comment by snipe** [comment]
Editing group permissions should already be fixed, per that previous issue. Admins shouldn't have access to settings, etc - only super users. Grant the group they are a member of rights as superadmin

**Comment by brianjking** [comment]
Once I updated via `git pull` to bring my installation up-to-date with V3 Alpha 2 tag all worked well.

Thanks @snipe
