### ISSUE TITLE
Show other field on "Generate Label"

### ISSUE THREAD

**Issue by kenpachi13** [snipe/snipe-it#2074]
Hi @snipe,
The generate label function is great addition to v3 release!
Good job.
Just would like to request if on the "Label" setting, we can pick "Purchase date" to be displayed on the "Generate Label" function?

**Comment by snipe** [comment]
Generating labels has been available for quite some time. The issue becomes that fitting all that info into a small label becomes really difficult, and predicting how all of that text all wrap (when we have no way of knowing how long asset names, asset tags, etc will be) gets really challenging. We can consider adding it, but it won't make it into v3.0.

**Comment by kenpachi13** [comment]
thanks for considering the request.
will wait for the next major release.
keep it up!
