### ISSUE TITLE
admin view

### ISSUE THREAD

**Issue by kenpachi13** [snipe/snipe-it#2079]
Hi @snipe,
upgraded to v3 with no errors encountered during upgrade.
but when we test to login using previously created "admin" account, the view is not updated.
see file
![image](https://cloud.githubusercontent.com/assets/10649463/15530397/a8f71384-2286-11e6-86fd-82acf1c34143.png)

**Comment by snipe** [comment]
Can you try the latest off of v3 please?

**Comment by kenpachi13** [comment]
fix in new release.
thanks
