### ISSUE TITLE
Adding custom fields to fieldset results in 'Error, Asset does not exist.'

### ISSUE THREAD

**Issue by markjorissen** [snipe/snipe-it#2080]
#### Expected Behavior (or desired behavior if a feature request)

field gets added to custom field set (for example, 'cpu speed' field added to fieldset 'workstations')
-----

#### Actual Behavior

for some reason, page jumps to 'all assets' and displays an message 'Error: Asset does not exist.' when trying to add a field to a fieldset.
This error is reproduceable on de demo site.
-----
I have enabled debug mode
I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----

Snipe-IT version v3.0.0-dev-g6d810a9
OS: Ubuntu Linux 14.04.4
webserver: Apache version 2.4.7	(HTTPS)
php: 5.5.9-1ubuntu4.16
Lavarel 5.2.31
installation: clean install 2.1, after this upgrade to v3 Alpha 2 (manual).

No changes where made to the database, all clean install.

**Comment by snipe** [comment]
Is this still reproducible on the demo?

**Comment by markjorissen** [comment]
Thanks!!! It works!!!

very happy!


Mark
