### ISSUE TITLE
Snipeyheads image on checked out to info

### ISSUE THREAD

**Issue by zmorrow** [snipe/snipe-it#2082]
![store113](https://cloud.githubusercontent.com/assets/14094117/15555091/26b7396c-2295-11e6-859f-fd84d70bbd41.JPG)

Not sure if this is a snipe easter egg haha.  But whenever I click on an asset the check out to user has your picture and I can't figure out how to change or disable.

**Comment by snipe** [comment]
Hah, that's funny. :P Not intentional, I promise! I'll check into it.

**Comment by snipe** [comment]
Can you right click on that image and tell me what the image URL is?

**Comment by zmorrow** [comment]
src="//gravatar.com/avatar/ea5075ac915b019f86eb19756665f20a" class="user-image-inline" alt="User Image"

**Comment by zmorrow** [comment]
No rush, I think I am the only one who see's them, just didn't know if it was an easy fix.

**Comment by snipe** [comment]
This is in v3?

**Comment by zmorrow** [comment]
Yes

**Comment by zmorrow** [comment]
Im logged on Gitter if thats easier to ask questions.

**Comment by snipe** [comment]
Try a fresh pull

**Comment by snipe** [comment]
(What, you don't want me staring at you while you work???)

**Comment by zmorrow** [comment]
Thats not what I was saying!!

**Comment by zmorrow** [comment]
The new pull removed you, thanks I guess??
