### ISSUE TITLE
Labels not matching 5027

### ISSUE THREAD

**Issue by jcoxeup** [snipe/snipe-it#2084]
#### Expected Behavior (or desired behavior if a feature request)

Labels should print on the Avery 5027 labels.

-----

#### Actual Behavior

After row 1, the labels shift up and no longer match up with the label area getting progressively worse with each row.

-----

#### Please confirm you have done the following before posting your bug report:

My site is hosted (bsd).

-----
#### Please provide answers to these questions before posting your bug report:

- v2.1.0-55
- I have tried with multiple browsers and OS's,
- Tried adjusting print options.
- Could accomplish what i need to if i could export label information to CSV (QR code ect.)

**Comment by snipe** [comment]
This is resolved in the upcoming v3.
