### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by rehash07** [snipe/snipe-it#2089]
#### Expected Behavior (or desired behavior if a feature request)

My expectation is to successfully install dependencies from composer

---
#### Actual Behavior

I was prompted:
**[RuntimeException]
/var/www/html/snipeit/vendor/aws/aws-sdk-php does not exist and could not be created.**

---
#### Please confirm you have done the following before posting your bug report:
- [ ] I have enabled debug mode
- [*] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running: **v2.1.1**
- What OS and web server you're running Snipe-IT on: **CentOS 7 / Apache**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): **./install.sh**
- If you're getting an error in your browser, include that error

**Errror in exception handler: The stream or file "/var/www/html/snipeit/app/storage/logs/log-apache2handler-2016-05-27.txt" could not be opened: failed to open stream: Permission denied in /var/www/html/snipeit/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:87**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: **First page**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

**[2016-05-27 16:40:48] production.ERROR: exception 'PDOException' with message 'S                                                                               QLSTATE[28000] [1045] Access denied for user 'snipeit'@'localhost' (using passwo                                                                               rd: YES)' in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Datab                                                                               ase/Connectors/Connector.php:47
Stack trace:
#0 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connec                                                                               tors/Connector.php(47): PDO->__construct('mysql:host=loca...', 'snipeit', 'abHCH                                                                               o1HK8qvAGI...', Array)
#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connec                                                                               tors/MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createCon                                                                               nection('mysql:host=loca...', Array, Array)
#2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connec                                                                               tors/ConnectionFactory.php(57): Illuminate\Database\Connectors\MySqlConnector->c                                                                               onnect(Array)
#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connec                                                                               tors/ConnectionFactory.php(46): Illuminate\Database\Connectors\ConnectionFactory                                                                               ->createSingleConnection(Array)
#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Databa                                                                               seManager.php(176): Illuminate\Database\Connectors\ConnectionFactory->make(Array                                                                               , 'mysql')
#5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Databa                                                                               seManager.php(64): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#6 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Migrat                                                                               ions/DatabaseMigrationRepository.php(167): Illuminate\Database\DatabaseManager->                                                                               connection(NULL)
#7 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Migrat                                                                               ions/DatabaseMigrationRepository.php(115): Illuminate\Database\Migrations\Databa                                                                               seMigrationRepository->getConnection()
#8 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Consol                                                                               e/Migrations/InstallCommand.php(52): Illuminate\Database\Migrations\DatabaseMigr                                                                               ationRepository->createRepository()
#9 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command                                                                               .php(112): Illuminate\Database\Console\Migrations\InstallCommand->fire()
#10 /var/www/html/snipeit/vendor/symfony/console/Symfony/Component/Console/Comma                                                                               nd/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Componen                                                                               t\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutp                                                                               ut))
#11 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Console/Comman                                                                               d.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Compon                                                                               ent\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOu                                                                               tput))
#12 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Console/Comman                                                                               d.php(128): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Inp                                                                               ut\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/snipeit/app/commands/AppCommand.php(90): Illuminate\Console\Co                                                                               mmand->call('migrate:install')
#14 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Console/Comman                                                                               d.php(112): AppCommand->fire()
#15 /var/www/html/snipeit/vendor/symfony/console/Symfony/Component/Console/Comma                                                                               nd/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Componen                                                                               t\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutpu                                                                               t))
#16 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Console/Comman                                                                               d.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Compon                                                                               ent\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOut                                                                               put))
#17 /var/www/html/snipeit/vendor/symfony/console/Symfony/Component/Console/Appli                                                                               cation.php(889): Illuminate\Console\Command->run(Object(Symfony\Component\Consol                                                                               e\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/snipeit/vendor/symfony/console/Symfony/Component/Console/Appli                                                                               cation.php(193): Symfony\Component\Console\Application->doRunCommand(Object(AppC                                                                               ommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Compo                                                                               nent\Console\Output\ConsoleOutput))
#19 /var/www/html/snipeit/vendor/symfony/console/Symfony/Component/Console/Appli                                                                               cation.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Com                                                                               ponent\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Console                                                                               Output))
#20 /var/www/html/snipeit/artisan(59): Symfony\Component\Console\Application->ru                                                                               n()**
- Include what you've done so far in the installation, and if you got any error messages along the way.: **Setup directory permissions as per instructed in Snipe-IT-Configuration-Files**
- Indicate whether or not you've manually edited any data directly in the database: **No**

**Comment by rehash07** [comment]
Okay I got this already. Now my problem is when I'm trying to open it in the browser I always have this error.

Error in exception handler: The stream or file "/var/www/html/snipeit/app/storage/logs/log-apache2handler-2016-05-30.txt" could not be opened: failed to open stream: Permission denied in /var/www/html/snipeit/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:87

Although I tried the permissions from the following directories using 755 and 777:

app/storage
app/private_uploads
public/uploads
vendor

But still not working :(

**Comment by snipe** [comment]
Did you `chmod` or `chmod -R`? Those permissions on`app/storage` have to be recursive to cover the subdirectories.

**Comment by snipe** [comment]
Also please check to see if you have SELinux running. http://docs.snipeitapp.com/installation/server/linux-osx.html#notes-on-selinux

**Comment by rehash07** [comment]
Yeah I figured it that I'm having issues with my SELinux, so I just get back again from the beginning. I have different problem now. I'm having issue with the installation of composer. May I know if I still need to run the composer after I installed the snipeit using ./install.sh?

**Comment by Nubianprince** [comment]
what other issues are you having? You need to post the errors for someone to help.

**Comment by rehash07** [comment]
Hi Snipe/Nubianprince. I'm actually stuck in Step 3. Install Dependencies, when I'm trying to execute this command:

"curl -sS https://getcomposer.org/installer | php" 

I'm only getting this error:

**PHP Warning: file_put_contents(/home/glen/.composer/keys.dev.pub): failed to open stream: Permission denied in - on line 468
PHP Warning: file_put_contents(/home/glen/.composer/keys.dev.pub): failed to open stream: Permission denied in - on line 485
Downloading 1.1.2...
Could not create file /var/www/snipeit/composer.phar: fopen(/var/www/snipeit/composer.phar): failed to open stream: Permission denied
Download failed: fopen(/var/www/snipeit/composer.phar): failed to open stream Permission denied
fwrite() expects parameter 1 to be resource, boolean given**

The way I installed the snipe is by using this command:

./install.sh

And I'm already done with the configuration and permissions in Step 2.

Can you help me how to proceed? There is something I missed I'm sure.

**Comment by Nubianprince** [comment]
Sound like the script doesn't have permissions to write to those directories, the account you use to run the script will need elevated access.

Things to check

- Make sure you change to the install directory (snipeit) before you run curl -sS https://getcomposer.org/installer | php
- snipeit directory is chmod 775
- snipeit directory owned by apache
- what version of php are you running (run php -v)

I've manually installed on both Ubuntu and Centos 7, Centos can be a pain as its possible that some of the needed PHP extensions will need to be installed.

**Comment by snipe** [comment]
Did you maybe install composer as root, but you're running the web server as a regular user? We see composer blow up when it was installed or run the first time as root.
