### ISSUE TITLE
CSS and Javascript presented over HTTP instead of HTTPS.

### ISSUE THREAD

**Issue by allywilson1** [snipe/snipe-it#2090]
#### Expected Behavior (or desired behavior if a feature request)

All content to be presented over HTTPS

-----

#### Actual Behavior

All CSS, Javascript presented over HTTP

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running

> v2.1.0-55-g701c16f

- What OS and web server you're running Snipe-IT on

> Apache 2.4.6 on CentOS 7.2.1511

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

> Manual installation

- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

> Homepage/any page.

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.

> Content blocked due to insecurity.

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).

> Nope

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

> log-apache2handler-2016-05-28.txt: production.DEBUG: Not logged in - admin-auth [] []
> apache and apache ssl error logs showing nothing.

- Include what you've done so far in the installation, and if you got any error messages along the way.

> SSL working for other VirtualHosts just fine. Should be noted that this is using a wildcard certificate.
> Issue sounds the same as this: https://github.com/snipe/snipe-it/issues/239 but I'm not using nginx.
> The app is set to "production" mode, I've tried a number of different VirtualHost configs/settings, I've set the url to HTTPS in app.php, I've set the cookies to https only, and tried the .htaccess redirect as well. Current virtualhost config as follows:
```
<VirtualHost *:443>
RewriteEngine on
ServerName snipe.my.domain.net
DocumentRoot /var/www/html/snipe/public
<Directory /var/www/html/snipe/public>
#Require all granted
Allow From All
AllowOverride All
Options +Indexes
</Directory>
</VirtualHost>
```
Chrome console output:
![chrome-console-errors](https://cloud.githubusercontent.com/assets/16580296/15626093/5bf9d614-24b3-11e6-8199-971c26a15647.png)

- Indicate whether or not you've manually edited any data directly in the database

> nope

**Comment by allywilson1** [comment]
I've tried modifying Laravel and Apache to redirect (as per [this](https://stackoverflow.com/questions/19967788/laravel-redirect-all-requests-to-https) discussion)

The Laravel method results in too many redirects, and the Apache method just appears to get ignored...

**Comment by snipe** [comment]
CSS and JavaScript use whatever URL (including protocol) you specify in app/config/production.app in the URL section

**Comment by allywilson1** [comment]
Changed it to https:// still no difference

**Comment by snipe** [comment]
That's kind of not possible, because the JS and CSS urls use that config variable to determine the URL to pull from. Are the browser errors exactly the same after you changed it to https?

**Comment by snipe** [comment]
Also please tell me what URL you have in your app/config/production.app, and what URL you're accessing the site from. You can obscure the domain, but keep everything else intact.

**Comment by allywilson1** [comment]
https://snipe.my.domain.net

That's the address I'm accessing and what is specified in app/config/production/app.php

There were no errors prior to enabling HTTPS - it works fine over HTTP.

**Comment by snipe** [comment]
If you view the source and try to access one of the JS/CSS urls in the source code, what happens? (Snipe-IT runs fine over SSL, so I'm thinking you may have something misconfigured)

**Comment by allywilson1** [comment]
The source code specifies absolute values when accessed over HTTP or HTTPS:

e.g.  `<link href="http://snipe.my.domain.net/assets/css/bootstrap/bootstrap.css" rel="stylesheet" />`

If I try to access that bootstap.css (or others) over HTTP or HTTPS it loads fine.

Thank you for your help.

**Comment by snipe** [comment]
Can I see your app/config/production.app?

**Comment by snipe** [comment]
Also, are you running HTTPS over a proxy or anything? (Also, you should just uncomment the lines in the htaccess, never change core code, as that will get overwritten the next time you update.)

**Comment by allywilson1** [comment]
Sent it to snipe@snipe.net.

Not over a proxy no. I did just uncomment it in .htaccess, nothing else.

**Comment by allywilson1** [comment]
So after reading [this](http://laravel.io/forum/12-26-2014-routing-with-https) issue, I was able to workaround this, although it's not pretty.

Added the following to the top of app/routes.php (directly under **<?php**):

```
if (App::environment('production')) {
        URL::forceSchema('https');
}
```
and it started presenting everything over HTTPS correctly.

**Comment by indigo423** [comment]
Was able to get it running with Traefik by setting `APP_FORCE_TLS=true` in my .env file.
