### ISSUE TITLE
Creating assets with custom fields fails

### ISSUE THREAD

**Issue by jcnengel** [snipe/snipe-it#2091]
#### Expected Behavior (or desired behavior if a feature request)

Submitting the creation form for an asset based on a model with custom fields (e.g. Asset with MAC address) results in an asset created.

-----

#### Actual Behavior

Submitting the form as above results in an error message (see below)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Running snipe-it: 2.1.1
- What OS and web server you're running Snipe-IT on: openSUSE Leap 42.1, Apache 2.4
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual
- If you're getting an error in your browser, include that error: Just Server error 500
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: /hardware/create
- If a stacktrace is provided in the error, include that too: see below
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): Not reproducable in the demo environment.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way: Fresh installation
- Indicate whether or not you've manually edited any data directly in the database: No manual editing
`[2016-05-29 00:16:53] production.ERROR: exception 'ErrorException' with message 'Undefined index: fields' in /srv/www/snipe-it-2.1.1/app/controllers/admin/AssetsController.php:113
Stack trace:
#0 /srv/www/snipe-it-2.1.1/app/controllers/admin/AssetsController.php(113): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', '/srv/www/snipe-...', 113, Array)
#1 [internal function]: Controllers\Admin\AssetsController->postCreate()
#2 /srv/www/snipe-it-2.1.1/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#3 /srv/www/snipe-it-2.1.1/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postCreate', Array)
#4 /srv/www/snipe-it-2.1.1/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\AssetsController), Object(Illuminate\Routing\Route), 'postCreate')
#5 /srv/www/snipe-it-2.1.1/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\\Adm...', 'postCreate')
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /srv/www/snipe-it-2.1.1/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#8 /srv/www/snipe-it-2.1.1/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /srv/www/snipe-it-2.1.1/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /srv/www/snipe-it-2.1.1/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /srv/www/snipe-it-2.1.1/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /srv/www/snipe-it-2.1.1/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /srv/www/snipe-it-2.1.1/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 /srv/www/snipe-it-2.1.1/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /srv/www/snipe-it-2.1.1/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /srv/www/snipe-it-2.1.1/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /srv/www/snipe-it-2.1.1/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /srv/www/snipe-it-2.1.1/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []`

**Comment by snipe** [comment]
Please provide the browser console errors you see when you select a model from that page. That error typically occurs when the URL you're accessing the page from and the URL listed in app/config/production/app.php's do not match.

**Comment by jcnengel** [comment]
As mentioned before there are no browser errors, just a blank page.
