### ISSUE TITLE
Labels - adding / changing additional fields

### ISSUE THREAD

**Issue by Dan458** [snipe/snipe-it#2094]
Hi,

Is there any way where we can change what fields are displayed on a label? 

I can see currently you can add the asset tag, asset name and serial number but is there a way i could show the depreciation date?

All I want on the Label, is:
1. Asset Tag
2. Serial
3. Depreciation date

Thanks
Dan

**Comment by Profecy** [comment]
Yeah, customizable fields on asset tags would be nice.

+1

**Comment by sonic84** [comment]
Was this feature added?

**Comment by snipe** [comment]
Admin Settings > Labels

<img width="723" alt="screen shot 2019-01-16 at 1 47 58 pm" src="https://user-images.githubusercontent.com/197404/51280759-62ce0080-1995-11e9-8c49-0e3c090ffbda.png">

**Comment by sonic84** [comment]
can custom fields be added?

**Comment by hyph3nx** [comment]
> Admin Settings > Labels
> 
> <img alt="screen shot 2019-01-16 at 1 47 58 pm" width="723" src="https://user-images.githubusercontent.com/197404/51280759-62ce0080-1995-11e9-8c49-0e3c090ffbda.png">

Where is the template located in the code? I would like to modify it to include company logo and change the size of text

**Comment by haeusser** [comment]
+1

**Comment by ajworkman64** [comment]
+1

**Comment by OceusDCrain** [comment]
I would also like custom fields for the labels to be implemented.
