### ISSUE TITLE
path to mysqldump wrong for Ubuntu?

### ISSUE THREAD

**Issue by nrasmus** [snipe/snipe-it#2096]
#### Expected Behavior (or desired behavior if a feature request)

backing up through web GUI or cron works as expected
-----

#### Actual Behavior
Web GUI says it completed, but no file is made or listed.

Cron emails:  Failed to backup  because: The dump process failed with exitcode 127 : Command not found : sh: 1: /usr/local/bin/mysqldump: not found

When I ln -s /usr/bin/mysqldump /usr/local/bin/mysqldump on my Ubutnu 14.04 system, things work smoothly.

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [ x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
V3 dev
- What OS and web server you're running Snipe-IT on
Ubuntu 14.04 i386
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual/git
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/configuration#required-database-settings

Next time you can just update the path to mysqldump in the config.

**Comment by pathros** [comment]
By the way, guys, in Laradock, [how do you tell the workspace container](https://stackoverflow.com/q/64070267/1883256) that the mysqldump's binary path is located at /usr/bin in another container (named mysql)?
