### ISSUE TITLE
Asset Tag should be incremental and read only 

### ISSUE THREAD

**Issue by SynchronGmbH** [snipe/snipe-it#2097]
Hello,

**Actual Behavior**
The user can set an Asset Tag.

**Expected Behavior (or desired behavior if a feature request)**
Is it possible to define the asset tag as a _read only_ field? So the user can´t change the value of the filed. It is also important that this filed is _incremental_. If someone create a new asset the filed Asset Tag should be filled with a new object number (e.g. OBJ123456).

**Please confirm you have done the following before posting your bug report:**
  
- [x] I have enabled debug mode
- [x] I have read checked the Common Issues page

**Please provide answers to these questions before posting your bug report:**

    Version of Snipe-IT you're running: v2.1.0-8-g1b1a733
    What OS and web server you're running Snipe-IT on: Linux 14.04 LTS (Linux 3.13.0-24-generic x86_64), Webserver is Apache2

Thanks in advance ! 

Sam

**Comment by SynchronGmbH** [comment]
Possible solution to set the asset tag incremental to use an Excel sheet which generates the Asset Tag.

**Comment by snipe** [comment]
You can turn on asset incrementing in Admin > Settings, however there is no way currently to make the asset tag read-only.
