### ISSUE TITLE
Metric print settings

### ISSUE THREAD

**Issue by Profecy** [snipe/snipe-it#2098]
Hello everyone,

I would like to submit a feature request, but maybe this falls under the enhancement category.

So on my system I managed to print nicely formatted labels. Setting it up though was alittle bit tricky because I had to convert from metric to imperial.

So my request would be - if its possible with the current "label engine(?)" - to please make it an option to use imperial or metric untis for page marings, sizes, etc.

This would greatly simplify life for us Europeans ;)

**Comment by snipe** [comment]
It definitely won't happen for v3 GM, but maybe in a later release. We're already way behind :(

**Comment by Profecy** [comment]
That's okay, as long as it happens eventually, the settings offer enough precision at the moment :) Until then, google it is ^^

**Comment by Braintelligence** [comment]
This would be awesome, any roadmap on this yet? :)

**Comment by snipe** [comment]
Nope

**Comment by Braintelligence** [comment]
No problem, it's not a big issue for now :). Thanks for the great job!

**Comment by Kaphalor** [comment]
Would be nice if this could be added in a more or less future release.
I am not able to print labels on our labels, even though i converted metrics to imperial, but all the prints are totally off set :(
