### ISSUE TITLE
V3 Alpha - Checkout Asset to user Asset Tag/Name Undefined

### ISSUE THREAD

**Issue by brianjking** [snipe/snipe-it#2100]
#### Expected Behavior (or desired behavior if a feature request)

* Once I select a user from the dropdown I expect that it should list assets already checked out to this user, if any.
* If no assets are checked out to user yet, I expect that the intended behavior would be to display a message "No assets checked out to this user" or possibly just have the table hidden.

-----

#### Actual Behavior

![assets-issue](https://cloud.githubusercontent.com/assets/6786817/15722151/c3fbbe7a-2801-11e6-9640-7634643cb62c.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: V3 Alpha, last commit pulled: a9870db83f9b6ffb343d1a705cac3c9d9a388c70
- What OS and web server you're running Snipe-IT on: CentOS 6.7.x
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Git
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: `hardware/13/checkout`

* No errors shown in Console or Laravel debug bar.

https://github.com/snipe/snipe-it/commit/a9870db83f9b6ffb343d1a705cac3c9d9a388c70 is the latest commit I've pulled down, was previously runing `V3 Alpha 2` tag where this was also present.

**Comment by snipe** [comment]
Are there actually assets checked out to that user? And if there are, do they have names, or just asset tags?
