### ISSUE TITLE
ldap import/sync timing out without errors

### ISSUE THREAD

**Issue by shridharashetty** [snipe/snipe-it#2103]
#### Expected Behavior (or desired behavior if a feature request)
* LDAP synchronize should be able to import users or update user properties.
-----

#### Actual Behavior
* In previous version (v 2.1) i was able to get the ldap import to work. but we imported the users without their email address. So to sync the email address, i had to upgrade the snipeit version to v3.0.

* In the new version, after clicking on synchronize button, the ldap page times out after 120 secs. I had increased the timeout to 300 seconds. It timeout even after that.

-----

#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode
- [yes ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Snipe-IT version: v.3.0.0-dev

- OS and webserver running Snipe-IT on: CentOS 7.2.1511, Apache/2.4.6

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): 
Upgraded from 2.1 , referred https://snipe-it.readme.io/docs/upgrading

- If you're getting an error in your browser, include that error

Whoops, looks like something went wrong.
1/1 FatalErrorException in compiled.php line 5859: Maximum execution time of 300 seconds exceeded

    in compiled.php line 5859

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
https://asset-in.corp.endurance.com/admin/users/ldap
"Synchronize button"

- If a stacktrace is provided in the error, include that too.

- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): Cant check since its an 2.1.35 version
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
* I have tried to increase the timeout. It didnot help.
* Can see snipeit fetching data from ldap server. used tcpdump on the snipeit server to check.
* Could not find any logs related to ldap.

- Indicate whether or not you've manually edited any data directly in the database: No

**Comment by snipe** [comment]
We haven't heard of any reports of this issue. How many users do you have in your LDAP directory that would be matching your filter criteria?

**Comment by shridharashetty** [comment]
thanks for the prompt response :)
It has currently imported around 3000 users with the same filter in the earlier version. 
Let me check by narrowing the search criteria.

**Comment by shridharashetty** [comment]
Worked! 
It was related AD rather than snipeIT. Applying a filter and narrowing user base worked. thanks for the pointer.

I have one more query though. 
I had provided admin privileges to few users. but they seem to logged in as normal users post the upgrade. 
Could you pls assist.

**Comment by snipe** [comment]
You'll just have to be patient. We're still working through some of the permissions stuff.

**Comment by leethanh2112** [comment]
hello snipe,

I have a problem when i run "LDAP User Sync".
![image](https://user-images.githubusercontent.com/33690376/32873898-4e6de908-cac1-11e7-9dab-a7a04d0cbeb2.png)

Help me !!
