### ISSUE TITLE
Feature Request: One Asset, Multiple Users

### ISSUE THREAD

**Issue by roadbl0ck** [snipe/snipe-it#2107]
---
#### Expected Behavior (or desired behavior if a feature request)

If an asset is shared by multiple users, there should be an option to tag it as such so additional users can be selected to own the asset.

---
#### Actual Behavior

Check box for "Shared?" if so, "Shared with" then pick list for userid.
For multiple shifts or more than 2 users are using the same asset, we could have a "+" next to previously added user.id and once clicked, it will provide another pick list for userid.

**Comment by snipe** [comment]
We can put this on the roadmap, but it's unlikely to be implemented soon, as it would require reworking some pretty fundamental database structures and methods. (Also, if multiple people are assigned an asset, who is actually responsible for it?)
