### ISSUE TITLE
Some features to the more efficient management

### ISSUE THREAD

**Issue by secrectvn** [snipe/snipe-it#2109]
I think SnipeIT to add features to the more efficient management:

1. Group user for deparment
2. Custom prefix and subfix in Asset IDs will help better asset classification. Example :
- Company name (shorthand) - Asset IDs (autonumber) - Asset type (custom)
- AAU-01-PC for computer
- AAU-02-MO for Monitor
- AAU-03-PO for phone
3.Custom reporting

**Comment by snipe** [comment]
These feature requests have already been made
