### ISSUE TITLE
Can't get past login screen in v3-master

### ISSUE THREAD

**Issue by vjandrea** [snipe/snipe-it#2114]
#### Expected Behavior (or desired behavior if a feature request)

I should see the dashboard after login

-----

#### Actual Behavior

I see an error: `ErrorException in AuthController.php line 186: Trying to get property of non-object`
The detailed stack trace can be found here: http://laravel.io/bin/BLOr5

-----

#### Please confirm you have done the following before posting your bug report:

- [✔︎] I have enabled debug mode
- [✔︎ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: `v3-master
commit f8ac9a3f77d56804608dd86bed3b9b154ad27b8d
Author: snipe <snipe@snipe.net>
Date:   Fri Jun 3 11:48:20 2016 -0700
Fixes #2110`

- What OS and web server you're running Snipe-IT on: `OSX 10.11.5 (15F34), php 5.6.10, using php's built in webserver through artisan serve`
- What method you used to install Snipe-IT: `manual installation from forked synced repo`
`$ git pull snipe v3-master
$ rm database/database.sqlite
$ touch database/database.sqlite
$ artisan migrate --seed
$ artisan snipeit:create-admin --first_name=John --last_name=Doe --email=john@doe.dev --username=johndoe --password=...
$ artisan serve`
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: `localhost:8000/login, right after clicking "Login"`
- Confirm whether the error is reproduceable on the demo: `it isn't`
- Include what you've done so far in the installation, and if you got any error messages along the way: `other errors arise when i try to do a migrate:refresh or a migrate:reset but they're unrelated to this issue.`
- Indicate whether or not you've manually edited any data directly in the database: `db freshly migrated and seeded`

**Comment by snipe** [comment]
You ran the setup, yes? Is the anything in your settings table?

**Comment by snipe** [comment]
(the setup at /setup, I mean)

**Comment by vjandrea** [comment]
When i visit /setup it jumps directly to /login, i guess because i seeded the db.
I'll try a clean migration without seeding and see what happens.

**Comment by vjandrea** [comment]
Using a clean db and /setup everything works, i will see if using or modifying the command line sequence i can skip the /setup phase and work directly with cli; i'm testing a new feature that i need and i have to destroy and rebuild the db often.

**Comment by snipe** [comment]
Automate which process? You can use the paveit command I wrote, or php artisan migrate:reset (or one of the other migration commands)
