### ISSUE TITLE
Cannot install 2.1.1 - php artisan app:install fails with "Undefined variable: output"

### ISSUE THREAD

**Issue by asmartin** [snipe/snipe-it#2115]
#### Expected Behavior (or desired behavior if a feature request)

I expect `php artisan app:install --env=production` to successfully populate the database, but it exits prematurely with an error

-----

#### Actual Behavior

When I run `php artisan app:install --env=production`, it exits prematurely with an error before I can even enter a password:

````
# php artisan app:install --env=production

=====================================

  Step: 1

    Please follow the following
    instructions to create your
    default user.

-------------------------------------

Please enter your first name: asmartin
Please enter your last name: asmartin
Please enter your username: asmartin
Please enter your email: me@example.com
Please enter your user password (at least 8 characters): 

                              
  [ErrorException]            
  Undefined variable: output  
                              


app:install
````

-----

#### Please confirm you have done the following before posting your bug report:

- [N/A ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - 2.1.1
- What OS and web server you're running Snipe-IT on - Ubuntu 14.04 server amd64
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) extracted tarball into www-root, used composer to install dependencies, etc
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs:

````
[2016-06-03 20:51:12] production.ERROR: exception 'ErrorException' with message 'Undefined variable: output' in /var/www/snipe-it-2.1.1/vendor/symfony/console/Symfony/Component/Console/Helper/QuestionHelper.php:414
Stack trace:
#0 /var/www/snipe-it-2.1.1/vendor/symfony/console/Symfony/Component/Console/Helper/QuestionHelper.php(414): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/var/www/snipe-...', 414, Array)
#1 /var/www/snipe-it-2.1.1/vendor/symfony/console/Symfony/Component/Console/Helper/QuestionHelper.php(312): Symfony\Component\Console\Helper\QuestionHelper->hasSttyAvailable()
#2 /var/www/snipe-it-2.1.1/vendor/symfony/console/Symfony/Component/Console/Helper/QuestionHelper.php(135): Symfony\Component\Console\Helper\QuestionHelper->getHiddenResponse(Object(Symfony\Component\Console\Output\ConsoleOutput), Resource id #1)
#3 /var/www/snipe-it-2.1.1/vendor/symfony/console/Symfony/Component/Console/Helper/QuestionHelper.php(49): Symfony\Component\Console\Helper\QuestionHelper->doAsk(Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Symfony\Component\Console\Question\Question))
#4 /var/www/snipe-it-2.1.1/vendor/laravel/framework/src/Illuminate/Console/Command.php(239): Symfony\Component\Console\Helper\QuestionHelper->ask(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Symfony\Component\Console\Question\Question))
#5 /var/www/snipe-it-2.1.1/app/commands/AppCommand.php(225): Illuminate\Console\Command->secret('Please enter yo...')
#6 /var/www/snipe-it-2.1.1/app/commands/AppCommand.php(71): AppCommand->askUserPassword()
#7 /var/www/snipe-it-2.1.1/vendor/laravel/framework/src/Illuminate/Console/Command.php(112): AppCommand->fire()
#8 /var/www/snipe-it-2.1.1/vendor/symfony/console/Symfony/Component/Console/Command/Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/snipe-it-2.1.1/vendor/laravel/framework/src/Illuminate/Console/Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/snipe-it-2.1.1/vendor/symfony/console/Symfony/Component/Console/Application.php(889): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/snipe-it-2.1.1/vendor/symfony/console/Symfony/Component/Console/Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(AppCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/snipe-it-2.1.1/vendor/symfony/console/Symfony/Component/Console/Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/snipe-it-2.1.1/artisan(59): Symfony\Component\Console\Application->run()
````

The function in `vendor/symfony/console/Symfony/Component/Console/Helper/QuestionHelper.php` is

````
    /**
     * Returns whether Stty is available or not.
     *
     * @return bool
     */
    private function hasSttyAvailable()
    {
        if (null !== self::$stty) {
            return self::$stty;
        }

        exec('stty 2>&1', $output, $exitcode);

        return self::$stty = $exitcode === 0;
    }
}
````
- Indicate whether or not you've manually edited any data directly in the database - no, the database exists but is empty

**Comment by snipe** [comment]
Did you run into any errors when running composer? We haven't updated that app installer script in quite some time.

**Comment by snipe** [comment]
This might be related: http://stackoverflow.com/questions/17142343/undefined-variable-output-in-symfony-component-console-dialoghelper

**Comment by asmartin** [comment]
I re-ran the composer commands:

````
composer install --no-dev --prefer-source
composer dump-autoload
````

Both of these succeeded. I even tried enabling `exec` and `shell-exec` in `php.ini`, re-running the composer commands, and re-running `php artisan ...` but no change in behavior. Do you know which specific version of symfony is known to work with SnipeIT?

**Comment by snipe** [comment]
Did you restart the web server after enabling those directives? Also check that the php.ini you're editing is the one PHP is actually using. The version of Symfony should be fine.

**Comment by asmartin** [comment]
You were correct, invoking the PHP from the command line was using `/etc/php5/cli/php.ini` but I was editing `/etc/php5/apache2/php.ini` - after removing `exec` and `shell_exec` from the `disable_functions` list, it works now. Thanks for the help!
