### ISSUE TITLE
artisan migrate:reset QueryException

### ISSUE THREAD

**Issue by vjandrea** [snipe/snipe-it#2116]
#### Expected Behavior (or desired behavior if a feature request)

$ artisan migrate:reset should rewind all migrations and start over with a clean db

-----

#### Actual Behavior

I see an error message. I'm using SQLite

    $ artisan migrate:reset

    [Illuminate\Database\QueryException]
    SQLSTATE[HY000]: General error: 1 no such column: created_at (SQL: CREATE TEMPORARY TABLE __temp__custom_fieldsets AS SELECT id, name, created_at, updated_at FROM custom_fieldsets)

    [PDOException]
    SQLSTATE[HY000]: General error: 1 no such column: created_at
                                                                
-----

#### Please confirm you have done the following before posting your bug report:

- [✔︎] I have enabled debug mode
- [✔︎] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: `v3-master
commit f8ac9a3f77d56804608dd86bed3b9b154ad27b8d
Author: snipe <snipe@snipe.net>
Date:   Fri Jun 3 11:48:20 2016 -0700
Fixes #2110`

- What OS and web server you're running Snipe-IT on: `OSX 10.11.5 (15F34), php 5.6.10, using php's built in webserver through artisan serve`
- What method you used to install Snipe-IT: `manual installation from forked synced repo`

````sh
$ git pull snipe v3-master
$ rm database/database.sqlite
$ touch database/database.sqlite
$ artisan migrate --seed
$ artisan snipeit:create-admin --first_name=John --last_name=Doe --email=john@doe.dev --username=johndoe --password=...
$ artisan serve
````

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: `working on command line`
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): `nope`
- Include any additional information you can find in `app/storage/logs` and your webserver's logs: `full stack trace here:` http://laravel.io/bin/W4wEa
- Include what you've done so far in the installation, and if you got any error messages along the way: `can't login but this is unrelated`
- Indicate whether or not you've manually edited any data directly in the database: `db freshly migrated and seeded`

**Comment by snipe** [comment]
We don't officially support sqlite

**Comment by dmeltzer** [comment]
I'm going to suggest useing snipeit:pave and then artisan migrate  if you want to get back to a fresh db.  I've spent a few hours working through the migrations and I've only made it through 9 months of them.  Sqlite doesn't support dropping multiple columns at once, so the logic gets much messier and there are a lot of other migrate:reset issues buried in the history as well.

**Comment by vjandrea** [comment]
@dmeltzer I'm not a fan of workarounds like paveit but in this case i agree, migrations are quite messy and probably need a complete refactoring from the ground up. Maybe for v4?
