### ISSUE TITLE
Users should be able to view asset details

### ISSUE THREAD

**Issue by DavidGuder** [snipe/snipe-it#2122]
We just started to implement snipe-it in our Institute and use it to collect any equipment in our laboraties. Usability is very fine so far and we are very happy with it.
One thing could be optimized for our use.
There is a group of users (students) that should be able to view asset details by scanning the QR-Code and check it out to themselves, but should not be able to edit the asset information or delete it.

At the moment the normal user just can view a list of available assets without beeing able to view details. The Admin user can view the asset information but also delete and edit it.

We would be glad if this feature could be implemented soon. Or maybe you can suggest a work around?

We are running snipe-it v2.1.0-55 on ubuntu server 16.04

Regards
David

**Comment by dmeltzer** [comment]
There are plans for much more granular permissions systems.  V3 is close to a release at this point, and has some of the backend scaffolding for such a thing, but the frontend changes to use it properly are probably going to be in a later version.

**Comment by DavidGuder** [comment]
That sounds promising. Thanks for the answer. Is there any prediction to me made about when it might be finalized?

**Comment by snipe** [comment]
Not at this time.

**Comment by centennialdawg** [comment]
I can actually confirm the point that David mentioned. Running into the same needs here:
we have users that should not be able to change the properties of assets but learn about the specs.
Furthermore we use snipe also sort of as a 'rental list' in which every user (standard user) should be allowed to check devices in to himself but not to other people.
Furthermore, I would appreciate the opportunity to define custom fields of multiple lines and include WYSIWYG editor functionality including defining links to other pages (for instance product homepage)

**Comment by snipe** [comment]
So, WYSIWYG is never going to happen. We do support markdown, and if we can ever find a decent WYSIWYG editor that works well and is limited to only markdown. We'll jump all over it. 

V3 sets the framework for more granular permissions, but we don't have all of what you're asking about implemented yet.

**Comment by centennialdawg** [comment]
alright, sounds good.
Nevertheless, markdown apparently only works some of the fields and it does not work in custom fields so far or the notes field for an asset.

**Comment by roycepope** [comment]
Another Snipe-IT user here. We utilize the Notes section of the assets quite a bit and would like to have a normal user be able to scan an asset QR code to see capabilities and read the notes section of assets. 

The only way I know how to make this work right now (And after reading the above) is to make the Users part of the **Assets: View**. But that makes them able to edit all the assets. :(

Love this project, Thanks for making this guys!

**Comment by louisdj** [comment]
+1 for letting users see the details of an asset. 
Maybe it's an option to let the admin decide which field can be seen by users and which not?
I think it would be helpful for users to see themselves it warranty period is past or not for example.
