### ISSUE TITLE
Request: Ubuntu server 14.x VMWare image with webmin, Snipe-It v3 (beta, latest version)

### ISSUE THREAD

**Issue by markjorissen** [snipe/snipe-it#2125]
spending hours and hours doing a clean install with Ubuntu 14.x server and latest version of Snipe-IT... Documentation is relative hard to find. This would help... 
For some reason I can't get a clean install to work properly (when i've solved one problem, the next one appears)...

**Comment by snipe** [comment]
Without specific error messages (or even a specific version number), I'm not sure what you expect us to do with this information.

**Comment by markjorissen** [comment]
Sorry, 

I'm currently trying to get Snipe-It V3 beta to work. But some things are not clear to me, so I was thinking that it could be handy if a VMWare image of (for instance) ubuntu server with Snipe-It already installed would be available.

We could just download the VMWare Image with docs (login, passwords) and get started...

Currently i've installed Ubuntu 14 server with webmin. And then it begins:

- on Git, wich version must i use? V3 or V3 Master?
- how can i install this? Can I use install.sh (looks like it is not up2date), or do I just place the files inside var/www? 

Version 2.1 is running , but i would really want to go to the latest version because it looks great and has many features that we really want to use.

Perhaps it's better to delete this post...

**Comment by IxFail** [comment]
Hey,

Did you tried using http://docs.snipeitapp.com ?
I installed Snipe-IT with the install.sh and it's working fine on ubuntu14.x server which is running in ESXI.

I hope the url I gave you can help you, other wise I like to hear from you.

**Comment by snipe** [comment]
@IxFail I think @markjorissen is trying to install v3. The documentation for v3 is at https://snipe-it.readme.io/docs

@markjorissen 

> on Git, wich version must i use? V3 or V3 Master?

I would use v3-master.

> how can i install this? Can I use install.sh (looks like it is not up2date), or do I just place the files inside var/www?

We just pushed out an update last night that should fix the installer on v3.

**Comment by markjorissen** [comment]
Thanks snipe! We're testing on two servers, and most issue's are solved. I'm going to try the above for the latest version! happy coding!
