### ISSUE TITLE
Upgrade doesn't change version number?

### ISSUE THREAD

**Issue by ipro-bgardner** [snipe/snipe-it#2126]
#### Expected Behavior (or desired behavior if a feature request)

After upgrading to v2.1.2: Log in to site, browse to /admin/settings/app, view Snipe-IT version, should show current version number (v2.1.2-<stuff>)

-----

#### Actual Behavior

Snipe-IT version displayed is v2.1.1-55-g701c16f 

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: 
Trying to upgrade from v2.1.1-55-g701c16f

- What OS and web server you're running Snipe-IT on:  CentOS Linux release 7.2.1511 (Core), Apache v2.4.6-40.el7.centos.1

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Tried to upgrade by following procedure listed at: http://docs.snipeitapp.com/upgrading.html
These instructions say to "run whatever commands the release notes specify."  Could not find release notes.
Downloaded v2.1.2.tar.gz, unpacked in a separate location, backed up original files and DB, copied contents of tar onto original files, ran:
php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan migrate

- If you're getting an error in your browser, include that error
No errors in browser

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

- If a stacktrace is provided in the error, include that too.
no stacktrace

- Any errors that appear in your browser's error console.
no errors

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
unable to confirm as I am unable to upgrade the demo

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
nothing unusual in OS, httpd, or Snipe-IT logs.

- Include what you've done so far in the installation, and if you got any error messages along the way.
(details in the how install question above)

No errors, except composer complains about running with root privileges.

- Indicate whether or not you've manually edited any data directly in the database
no direct data maipulation

**Comment by snipe** [comment]
It's already been released, so we can't go back in time and fix it.
