### ISSUE TITLE
Asset Import - field mis-matches

### ISSUE THREAD

**Issue by mmcleod82** [snipe/snipe-it#2129]
#### Expected Behavior (or desired behavior if a feature request)

Assets should import with the correct fields, as in V2.

Has the format changed in V3 ?

-----

#### Actual Behavior

Wrong data in wrong fields once imported.

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

•Version of Snipe-IT you're running - V3 
•What OS and web server you're running Snipe-IT on - Windows IIS8
•What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual
•If you're getting an error in your browser, include that error - Included above
•What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Any page, when selecting 'Backups' from the Admin drop down menu.
•If a stacktrace is provided in the error, include that too.
•Any errors that appear in your browser's error console.
•Confirm whether the error is reproduceable on the demo.
•Include any additional information you can find in  app/storage/logs  and your webserver's logs.
•Include what you've done so far in the installation, and if you got any error messages along the way.
•Indicate whether or not you've manually edited any data directly in the database - No definitely not.

**Comment by dmeltzer** [comment]
It has changed.  See https://snipe-it-manual.readme.io/docs/importing-assets.  I'll put a link to that on the import page.
