### ISSUE TITLE
Auto Increment In Importer

### ISSUE THREAD

**Issue by crutchcorn** [snipe/snipe-it#2136]
#### Expected Behavior (or desired behavior if a feature request)

Currently, to import, you need to have an ID for an Asset Tag. This feature would allow you to leave out the Asset Tag and have SnipeIT handle it by having it increment for each asset imported

---
#### Actual Behavior

You have to create your own system for Asset Tags.

---
#### Please confirm you have done the following before posting your bug report:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running
  Missing from V3 currently
- What OS and web server you're running Snipe-IT on
  N/A
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  N/A
- If you're getting an error in your browser, include that error
  N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
  N/A
- If a stacktrace is provided in the error, include that too.
  N/A
- Any errors that appear in your browser's error console.
  N/A
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
  N/A
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
  N/A
- Include what you've done so far in the installation, and if you got any error messages along the way.
  N/A
- Indicate whether or not you've manually edited any data directly in the database
  N/A

**Comment by lorenzolewis** [comment]
+1
