### ISSUE TITLE
Upgrade to v3.0-beta2 - windows - Class ActionLog not Found

### ISSUE THREAD

**Issue by Dan458** [snipe/snipe-it#2137]
Hi,

Looking for some assistance. Trying to upgrade our version to V3.0-beta2. have followed all the steps in the upgrade guide however when running php artisan migrate i receive:

Application In Production!     

Do you really wish to run this command? (yes/no) [no]:
yes

 [Symfony\Component\Debug\Exception\FatalErrorException]
 Class 'Actionlog' not found

Any ideas what i need to do to get around this?

Thanks
Dan

**Comment by dmeltzer** [comment]
What happens if you run php artisan migrate --verbose? Looking to see the backtrace of the error.. Alternatively, does storage/logs/laravel.log have any more detailed information?

**Comment by Dan458** [comment]
Hi Dmeltzer,

running php artisan migrate --verbose produces: 

C:\inetpub\wwwroot\HL-Asset>php artisan migrate --verbose

Application In Production!     

Do you really wish to run this command? (yes/no) [no]:
yes

[Symfony\Component\Debug\Exception\FatalErrorException]
Class 'Actionlog' not found

The laravel log has tonnes in it. However looking at log C:\Windows\Temp\PHP56_error.log we see:

PHP Fatal error:  Class 'Actionlog' not found in C:\inetpub\wwwroot\HL-Asset\database\migrations\2015_07_29_230054_add_thread_id_to_asset_logs_table.php on line 189

removing this file and running php artisan migrate works. I don't know what is wrong within this file nor what it does but it has gotten me into the web app and all appears to be working ok. The only thing i had to do was make my old admin user a superuser in the DB, to get the settings menu back in the web app.

**Comment by snipe** [comment]
Never remove migrations. That can screw up your install for years to come.

@dmeltzer might be a namespacing issue - I'll look into it

**Comment by snipe** [comment]
@Dan458 I've pushed out a possible fix for that migration on the v3 and v3-master branches
