### ISSUE TITLE
Incorrect status showing on asset when Checked Out

### ISSUE THREAD

**Issue by mmcleod82** [snipe/snipe-it#2138]
#### Expected Behavior (or desired behavior if a feature request)

When we checkout an asset to a person, the status shows as deployed in the asset list screen and should do on the reports and if you edit the asset.

-----

#### Actual Behavior

It shows the status as deployed in the asset list screen, but when you edit the asset, or look at it in the asset report, it's status is showing as 'Ready to Deploy'.

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - V3
- What OS and web server you're running Snipe-IT on - IIS8
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). - yes
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - No

**Comment by snipe** [comment]
This is not a big. RTD is more of a status state.
