### ISSUE TITLE
Assets by Category view returns no matches

### ISSUE THREAD

**Issue by mmcleod82** [snipe/snipe-it#2139]
#### Expected Behavior (or desired behavior if a feature request)

Assets -> Categories -> Laptops (for example) , should show a list of all assets with the category Laptops.

-----

#### Actual Behavior

It says 'No matches found' and fails to display any.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - V3
- What OS and web server you're running Snipe-IT on - IIS8
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - http://snipeit/admin/settings/categories
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). - No, it works as expected 😕 
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Still need answers to the other questions in the list above.

**Comment by mmcleod82** [comment]
Ok - so it works in the demo. Very odd, I've double checked and there are definitely 600 assets with a category 'laptops'. When you look at the Asset Categories screen it does indeed show 600 in the number of assets against that category. When you then select the category - 'no results displayed'.

**Comment by snipe** [comment]
> Any errors that appear in your browser's error console.
> Include any additional information you can find in app/storage/logs and your webserver's logs.

**Comment by mmcleod82** [comment]
No errors in browser error console but it does log this error in the laravel.log file:

[2016-06-09 11:13:10] production.ERROR: exception 'BadMethodCallException' with message 'Method skip does not exist.' in C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php:6318

Do you want the stack trace?

**Comment by mmcleod82** [comment]
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\app\Http\Controllers\CategoriesController.php(329): Illuminate\Support\Collection->__call('skip', Array)
#1 C:\inetpub\wwwroot\snipe-it\app\Http\Controllers\CategoriesController.php(329): Illuminate\Database\Eloquent\Collection->skip('0')
#2 [internal function]: App\Http\Controllers\CategoriesController->getDataViewAssets('2')
#3 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9361): call_user_func_array(Array, Array)
#4 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9423): Illuminate\Routing\Controller->callAction('getDataViewAsse...', Array)
#5 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9403): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\CategoriesController), Object(Illuminate\Routing\Route), 'getDataViewAsse...')
#6 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#7 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#8 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9880): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#10 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9404): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#11 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9391): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\CategoriesController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'getDataViewAsse...')
#12 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8459): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'getDataViewAsse...')
#13 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8446): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#14 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8160): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\Authenticate.php(45): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9895): call_user_func_array(Array, Array)
#20 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9880): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8161): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#25 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8152): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#26 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8142): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#27 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(2400): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#29 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 C:\inetpub\wwwroot\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\Debugbar.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9895): call_user_func_array(Array, Array)
#33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckForSetup.php(22): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9895): call_user_func_array(Array, Array)
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9895): call_user_func_array(Array, Array)
#43 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\XssProtectHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9895): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 [internal function]: App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9895): call_user_func_array(Array, Array)
#53 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#55 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13334): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9895): call_user_func_array(Array, Array)
#58 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#60 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(11880): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#61 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9895): call_user_func_array(Array, Array)
#63 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#65 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(3250): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9895): call_user_func_array(Array, Array)
#68 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#70 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#71 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9880): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#72 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(2347): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#73 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(2331): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#74 C:\inetpub\wwwroot\snipe-it\public\index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#75 {main}

**Comment by snipe** [comment]
Pretty sure this was already fixed on the latest v3 and v3-master branches.
