### ISSUE TITLE
Rename Serial to "Product Key" for licenses

### ISSUE THREAD

**Issue by alex-rosenberg35** [snipe/snipe-it#2140]
Feature Request:

For management of licenses, please rename "Serial" to "Product Key".

For example, in `app/views/backend/licenses/edit.blade.php`:

>             
            <div class="form-group {{ $errors->has('product_key') ? ' has-error' : '' }}">
                <label for="product_key" class="col-md-3 control-label">@lang('admin/licenses/form.key')
                 <i class='fa fa-asterisk'></i></label>
                 </label>
                    <div class="col-md-7">
                        <textarea class="form-control" type="text" name="product_key" id="product_key">{{{ Input::old('product_key', $license->product_key) }}}</textarea>
                        {{ $errors->first('product_key', '<br><span class="alert-msg"><i class="fa fa-times"></i> :message</span>') }}
                    </div>
            </div>

**Comment by snipe** [comment]
Why? I think just about everyone understands that a license serial is the same as a license key.

**Comment by alex-rosenberg35** [comment]
The term "Key" is far more widely accepted, consistently used, and technically correct.  The "Serial" is often something different entirely, even in the context of licensing.  In some cases, a serial number is used to optionally register a product, whereas the product key is used to verify software licensing.  Microsoft uses the terms "Product Key" and "Activation Key".  Adobe uses the term "Product Key".  SPSS uses the term "License Key".  Compare https://en.wikipedia.org/wiki/Product_key and https://en.wikipedia.org/wiki/Serial_code

Lastly, a server used for licensing purposes is called a "Key Server".  (Has anyone ever heard of a Serial Server?)
