### ISSUE TITLE
Issues with upoaded image url's being used. By default using Https instead of Http

### ISSUE THREAD

**Issue by sry9681** [snipe/snipe-it#2141]
#### Expected Behavior (or desired behavior if a feature request)

I was hoping that the images would get uploaded and displayed correctly

-----

#### Actual Behavior

Images get converted and uploaded to snipeit/public/uploads correctly but I have noticed through Inspect Element that the links Snipe-IT is using is with https and not http which will provide an error. The same thing happens when clicking Dashboard (and only dashboard, every other link works fine).

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

Running v2.1.1 (edited to add version number as per the request below) of Snipe-IT on Ubuntu 14.04. Used install.sh method. I don't think I would need log files unless yall request them.

**Comment by snipe** [comment]
What are you considering latest version? Latest stable (v2.1.2?) or latest v3 beta? (This is why we ask the questions that you deleted before opening the ticket.)

**Comment by vijaydsk** [comment]
Am also having the same issue. My build is latest stable (v2.1.2). After uploading the logo, the url is being redirected to https instead of http and cannot display the page.

**Comment by snipe** [comment]
What do you have in your app/config/app.php for your URL?

**Comment by vijaydsk** [comment]
I have the following for url

Illuminate\Support\Facades\URL

**Comment by vijaydsk** [comment]
I have the following for url

Illuminate\Support\Facades\URL

On Mon, Jun 13, 2016 at 1:38 PM, snipe <notifications@github.com> wrote:

> What do you have in your app/config/app.php for your URL?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/snipe/snipe-it/issues/2141#issuecomment-225514252>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS-p4GCwxH5yVII1aE0uoiVJQhQ1MnBaks5qLRABgaJpZM4Ix_yn>
> .
>



-- 
My blood group always says B+ve

Regards.
Vijay DSK

**Comment by snipe** [comment]
That doesn't make any sense. Please paste your `app/config/production/app.php` file here.

**Comment by vijaydsk** [comment]
Attached app.php after converting that into txt format
[app.txt](https://github.com/snipe/snipe-it/files/311485/app.txt)

**Comment by snipe** [comment]
That's `app/config/app.php`. I need `app/config/production/app.php`.

**Comment by snipe** [comment]
(And please just paste it in, do not attach it as a file.)

**Comment by vijaydsk** [comment]
it is https://10.44.71.130//

**Comment by snipe** [comment]
Are you running this over SSL?

**Comment by vijaydsk** [comment]
no

**Comment by snipe** [comment]
Then change it to `http://10.44.71.130//`. If you're not running it over SSL, you shouldn't be using an SSL protocol. (Also, remove the trailing slashes.)

**Comment by vijaydsk** [comment]
I did exactly what you said. Now it is working fine. But it shouldn't be taking to https/ssl without asking me when I am installing. Am I right?

**Comment by sry9681** [comment]
Thank you. changing `/var/www/snipeit/config/production/app.php` url from https to http worked for me. thank you.

**Comment by vijaydsk** [comment]
@sry9681,
Glad. Your problem is fixed. But the question is unanswered.

**Comment by sry9681** [comment]
@vijaydsk Which question? If you're referring to the Snipe-IT version I am running v2.1.1....

**Comment by vijaydsk** [comment]
@sry9681,
Am using V2.1.2. Installed through install.sh. How this script allowed the application to run on https?

**Comment by sry9681** [comment]
@vijaydsk Well it's just a user made script that @snipe put on the official website. They didn't include options to change every single aspect of the Snipe-IT program. They just included what was needed to make it work correctly. I hope that I understood your question correctly.

**Comment by snipe** [comment]
@mtucker6784 would you mind fixing that on the master branch? It should replace the protocol, not just the `production.yourserver.com`, since the config file defaults to https.

**Comment by sry9681** [comment]
@snipe Thank you so much for your help.

**Comment by mtucker6784** [comment]
I'm knee deep in a few things here; just received a promotion and I have to
learn some other roles. I'll make the change as I can this week, but I
can't swing it today.

Michael Tucker
Tucker Tech Online, LLC
http://www.tuckertechonline.com/
480-620-4506

**Comment by vijaydsk** [comment]
All,
Appreciate your efforts

On Tue, Jun 14, 2016 at 1:40 AM, Michael T <notifications@github.com> wrote:

> I'm knee deep in a few things here; just received a promotion and I have to
> learn some other roles. I'll make the change as I can this week, but I
> can't swing it today.
>
> Michael Tucker
> Tucker Tech Online, LLC
> http://www.tuckertechonline.com/
> 480-620-4506
>
> On Mon, Jun 13, 2016 at 11:25 AM, snipe <notifications@github.com> wrote:
>
> > @mtucker6784 <https://github.com/mtucker6784> would you mind fixing that
> > on the master branch? It should replace the protocol, not just the
> > production.yourserver.com, since the config file defaults to https.
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/snipe/snipe-it/issues/2141#issuecomment-225666531>,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ABiNkonJKiDoGl3RP98mIBGGgQvzJ1MBks5qLaCUgaJpZM4Ix_yn
> >
>
> > .
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/snipe/snipe-it/issues/2141#issuecomment-225693617>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AS-p4JgEXNYiL8fELpaWoufSRGPJcdK4ks5qLbkpgaJpZM4Ix_yn>
> .
>



-- 
My blood group always says B+ve

Regards.
Vijay DSK

**Comment by snipe** [comment]
@mtucker6784 Wow, congrats!! 

![adventure-time-112](https://cloud.githubusercontent.com/assets/197404/16105484/bc96dcd4-333f-11e6-91da-d8d2f4e590e1.gif)

@vijaydsk That last commit should have fixed the issue.
