### ISSUE TITLE
Purge Deleted Records doesn't work for deleted AD Users

### ISSUE THREAD

**Issue by MPIAE-IT** [snipe/snipe-it#2142]
#### Expected Behavior (or desired behavior if a feature request)

After soft deleting users which were synced by the LDAP-Sync, the "Purge Deleted Records" in Settings should delete the old soft deleted users. Purging from command line should work as well.

-----

#### Actual Behavior

It doesn't delete anything
![bildschirmfoto 2016-06-09 um 16 18 34](https://cloud.githubusercontent.com/assets/16922521/15932900/d79a36c0-2e5d-11e6-80da-d8ee7364bbb1.png)

Same for command line:
![bildschirmfoto 2016-06-09 um 16 19 29](https://cloud.githubusercontent.com/assets/16922521/15933114/b0d8ad36-2e5e-11e6-937d-8cb7f17c66ab.png)

Users are still in deleted users (grey blocks is for data protection):
![ohne titel](https://cloud.githubusercontent.com/assets/16922521/15933042/6393c646-2e5e-11e6-83d7-55dee9a4c062.png)

Purging of other data is possible.
![bildschirmfoto 2016-06-09 um 18 58 13](https://cloud.githubusercontent.com/assets/16922521/15938634/3c28bf42-2e74-11e6-9161-96cd29ef77ae.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: 
**v3.0.0-dev-3 (git pull from v3-master (845b182))**
- What OS and web server you're running Snipe-IT on: 
**Ubuntu 14.04 Apache 2**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): 
**manual**
- If you're getting an error in your browser, include that error: 
**no error!**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: 
**Admin -> Settings -> Purge Deleted Records**
- If a stacktrace is provided in the error, include that too. -
- Any errors that appear in your browser's error console. - 
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).: 
**I am not able to try that, I am not allowed to delete users.**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.: **There is only the  laravel.log .There is only the There is no log entry for this error. The last one is 2 hours ago and said:

`[2016-06-09 12:11:54] production.INFO: backups backups: Successfully took a new backup` 
`[2016-06-09 15:04:12] production.ERROR: 0`
`[2016-06-09 15:07:38] production.ERROR: 0`

Also no error logs in my web server logs. Everything is fine.**
- Include what you've done so far in the installation, and if you got any error messages along the way.
**Just installed it and set up the settings. Configured LDAP with too few LDAP filters. Thats the reason to delete users.** 
- Indicate whether or not you've manually edited any data directly in the database
**No i certainly did not and will not do this.**

**Comment by snipe** [comment]
Do you actually see users with `deleted_at` set in your `users` table?

**Comment by snipe** [comment]
Please do a fresh pull of v3 - I believe we've fixed your issue.

**Comment by MPIAE-IT** [comment]
Indeed! Purging of LDAP-Users is possible now!

THANKS
