### ISSUE TITLE
Feature Request: Custom Fields: Drop Down Menu for choosing option

### ISSUE THREAD

**Issue by MPIAE-IT** [snipe/snipe-it#2143]
Hey,

before I start, I just want to say this software is great. I love the idea, the GUI and just everything else.
I don't know if this was already mentioned somewhere else. I've searched for it, but I did not find it as a feature request.

I love the function of custom fields. We use it to specify what kind of hardware is installed inside a computer. For example we order a lot of 13" Macbook Air, but some of them with 256 GB SSD and some with 512 GB SSD also RAM and CPU are different. We could create different asset models, but we want to keep it simple and use the actual Apple model name like "MacBook Air (13-inch Mid 2013)" for all 13" mid 2013 macbook air. For this reason we use the custom fields to specify what components are build it. 
Unfortunately everytime an asset gets created we need to type in the information for that field. For example for SSD size we type 512 GB or 256 GB. It would help a lot if we could just choose the size from a drop down menu, when we create the asset. Just the same like you do it with Asset Model. Also the + next to the drop down menu, to create new options would be great.

Is this possible or even already planned to be released at some point?

Have a great day. And thank you so much for this great piece of software!

Lenny

**Comment by snipe** [comment]
Hi Lenny,

Thanks for the kind words :) Additional form types are definitely planned, and are mentioned at least here: https://github.com/snipe/snipe-it/issues/1960 - and I think are wrapped into a few other tickets as well.
