### ISSUE TITLE
Accessories Category is not showing the list, was working fine before.

### ISSUE THREAD

**Issue by JarbyDev** [snipe/snipe-it#2144]
#### Expected Behavior (or desired behavior if a feature request)
**Was working Fine the accessories category**
-----

#### Actual Behavior

 **i just change the category from Accessory to consumable and after that, accessories list dissappear, i checked the database and the information is there,** 
-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [ x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running **2.1.1**
- What OS and web server you're running Snipe-IT on **Linux Ubuntu** 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **MANUAL**
- If you're getting an error in your browser, include that error ( no error in browser ) 
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error, **/admin/accessories**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. **500 internal server error  - http://www.web.com/api/accessories/list**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
[log.txt](https://github.com/snipe/snipe-it/files/307384/log.txt)

- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
**i didnt touch the database.**

**Comment by snipe** [comment]
Need the actual 500 error

**Comment by JarbyDev** [comment]
i get this in the chrome console
http://www.123.com/api/accessories/list?order=asc&limit=25&offset=0 500 (Internal Server Error)

Was working fine before, 
But that problem happen only after i changed  an accessory category to consumable category

**Comment by snipe** [comment]
Once again, I need the actual 500 error. I need to know what the error is specifically.

**Comment by JarbyDev** [comment]
`[2016-06-09 18:21:40] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/it-assets/app/controllers/admin/AccessoriesController.php:599
Stack trace:
#0 /var/www/it-assets/app/controllers/admin/AccessoriesController.php(599): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/it-ass...', 599, Array)
#1 [internal function]: Controllers\Admin\AccessoriesController->getDatatable()
#2 /var/www/it-assets/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#3 /var/www/it-assets/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('getDatatable', Array)
#4 /var/www/it-assets/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\AccessoriesController), Object(Illuminate\Routing\Route), 'getDatatable')
#5 /var/www/it-assets/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'getDatatable')
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /var/www/it-assets/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#8 /var/www/it-assets/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /var/www/it-assets/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/it-assets/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/it-assets/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/it-assets/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/it-assets/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/it-assets/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/it-assets/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/it-assets/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/it-assets/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /var/www/it-assets/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []`

**Comment by snipe** [comment]
You're not really supposed to change the category type if there are already things in it. The real bug here is that the UI allows you to do that.

**Comment by JarbyDev** [comment]
i didnt know that, how i can fix it?

**Comment by snipe** [comment]
Will likely have to fix it in the DB directly. :(

**Comment by JarbyDev** [comment]
Can you please told me in which table?

**Comment by snipe** [comment]
It will be the `categories` table, but I don't know which record you changed. Change it back to accessory.

**Comment by JarbyDev** [comment]
Thx, i created a new database and  it works again thx
