### ISSUE TITLE
Asset Import: PHP Fatal error 

### ISSUE THREAD

**Issue by SynchronGmbH** [snipe/snipe-it#2153]
Hello

#### Expected Behavior (or desired behavior if a feature request)

1.) Import a csv-file according to the user manuel --> Importing Asset
(http://docs.snipeitapp.com/manual/importing-assets.html)
![screenshot - 14 06 2016 - 13 36 52](https://cloud.githubusercontent.com/assets/18677910/16041384/4973c84e-3235-11e6-8fe8-59bdc57d88d3.png)

2.) Import a csv-file according to the issue #1578 

-----

#### Actual Behavior

1.) When I upload a csv-file it keeps on saying "Process". If I click "Process" I get the follow message: _"Success: Youre file has been imported"_
![screenshot - 14 06 2016 - 13 44 01](https://cloud.githubusercontent.com/assets/18677910/16041562/5166ffca-3236-11e6-9323-48343a60d2f3.png)
Unfortunately I can't find the content assets of the csv-file.

2.) I upload the csv-file and tried to import the csv-file "Test2.csv"
**...**
**root@Snipe-IT01:**/var/www/snipeit/snipe-it-master# php artisan asset-import:csv /var/www/snipeit/snipe-it-master/Test2.csv 

PHP Warning:  require(/var/www/snipeit/snipe-it-master/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/snipeit/snipe-it-master/bootstrap/autoload.php on line 17

PHP Fatal error:  require(): Failed opening required '/var/www/snipeit/snipe-it-master/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/snipeit/snipe-it-master/bootstrap/autoload.php on line 17

So I opened the php-file autoload.php:
![screenshot - 14 06 2016 - 13 55 30](https://cloud.githubusercontent.com/assets/18677910/16041801/c2c5ede2-3237-11e6-832a-c1adcce78330.png)

Please assist. Where is my issue ?

Thanks in advance

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

Version of Snipe-IT you're running: v2.1.0-8-g1b1a733
What OS and web server you're running Snipe-IT on: Linux 14.04 LTS (Linux 3.13.0-24-generic x86_64), Webserver is Apache2, Laravel Version 4.2.17

**Comment by dmeltzer** [comment]
It looks like you didn't run composer install (missing the vendor directory?) but that should have stopped the website from loading at all...

**Comment by SynchronGmbH** [comment]
Composer is installed: 
![screenshot - 14 06 2016 - 14 22 49](https://cloud.githubusercontent.com/assets/18677910/16042532/7a7dcb78-323b-11e6-95d8-0ad14ab661ae.png)

**Comment by snipe** [comment]
If composer didn't run, the page itself wouldn't load. My guess is that that's an older log message that's unrelated to the import. My money is on there being something wrong with the CSV.

**Comment by SynchronGmbH** [comment]
I imported the sample CSV file with the dummy data for v2.1.1. 
(http://docs.snipeitapp.com/manual/importing-assets.html)
![unbenannt](https://cloud.githubusercontent.com/assets/18677910/16070012/f15ee302-32d2-11e6-91d1-bb62562f9ea9.PNG)
But I still can ́t  find the records in SnipeIT.

**Comment by snipe** [comment]
Did this get resolved?

**Comment by SynchronGmbH** [comment]
Unfortunately not. This way doesn't work.

**Comment by snipe** [comment]
I still don't see a vendor directory in that screenshot you posted. I don't understand how your install is running at all without the vendor directory. 

Do you see the records in your database? Are they just not displaying correctly on the assets listing page?
