### ISSUE TITLE
V3 Error when uploading files, images, documents

### ISSUE THREAD

**Issue by veen1981** [snipe/snipe-it#2155]
#### Expected Behavior (or desired behavior if a feature request)

I am unable to upload any images or files in version 3.

-----

#### Actual Behavior

When attempting to upload our logo, add an image to a device model, or upload receipts or vendor information in licenses, we are getting the Whoops! Looks like something went wrong message. I have done a clean install on a VM, created a new supplier and attempted to upload an image and received the same error, however I cannot reproduce on the V3 demo. I have attached my logs at the end of this ticket.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version: v3.0.0-dev-3-g6d810a9
- OS: CentOS 7
- Method of Install: install.sh
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: multiple, any page with an upload option
- Any errors that appear in your browser's error console: Whoops! Looks like something went wrong.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): I am unable to reproduce the error on the V3 demo, however I can reproduce the error on a clean install in a VM with no imported data.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way: This is a fresh install from yesterday. I first dropped my old database and renamed the web directory. Then did a clean install using the install script, setup the .env file, re-imported my database. 
- Indicate whether or not you've manually edited any data directly in the database: nope

[log.txt](https://github.com/snipe/snipe-it/files/314553/log.txt)

**Comment by snipe** [comment]
Are your paths and permissions correct?

**Comment by veen1981** [comment]
I 777'd the web directory so it shouldn't be an issue with permissions. Where do I need to look to check my paths?

**Comment by snipe** [comment]
Well, the error is: `Intervention\Image\Exception\NotReadableException: Unable to read image from file (/tmp/phpV8IBX9)`

So it seems more like the system can't read from your tmp directory.

**Comment by veen1981** [comment]
Ahh, let me change the permissions there once!

**Comment by veen1981** [comment]
![compliment4](https://cloud.githubusercontent.com/assets/14188055/16055557/da4dd0f8-323f-11e6-8097-c07e19763405.gif)

**Comment by snipe** [comment]
![oh-hi](https://cloud.githubusercontent.com/assets/197404/16056343/f25ea9a8-3229-11e6-9aec-76b439139c3f.gif)
