### ISSUE TITLE
Trying to use pgsql but getting an error

### ISSUE THREAD

**Issue by pnelsonsr** [snipe/snipe-it#2156]
#### Expected Behavior (or desired behavior if a feature request)

to configure and seed postgresql database

-----

#### Actual Behavior

when I run 'php artisan app:install --env=production'
i get to the point 'step 2 preparing you Application' where I get the error

[PDOException]
could not find driver

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
 v2.1.0-pre 
- What OS and web server you're running Snipe-IT on
Fedora 23 Server
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual
- If you're getting an error in your browser, include that error
Not gettting to the browser yet
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Not getting past install
- If a stacktrace is provided in the error, include that too.
no stack
- Any errors that appear in your browser's error console.
no browser yet
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
no browser yet
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
no browser yet
- Include what you've done so far in the installation, and if you got any error messages along the way.
looked for pgsql in vendor dir and its not there
- Indicate whether or not you've manually edited any data directly in the database
can not get to the database part of the install

**Comment by snipe** [comment]
Snipe-IT requires MySQL or MariaDB, as mentioned in the requirements.
http://docs.snipeitapp.com/requirements.html

**Comment by pnelsonsr** [comment]
So the driver was removed but the remnants of past configurations still exist in the config files?  Drat...
I know nothing of mysql or mariadb...

**Comment by snipe** [comment]
No drivers were removed.

**Comment by pnelsonsr** [comment]
Then why are there pgsql elements in app/config/production/database.php?

**Comment by snipe** [comment]
That's just the default Laravel database config. Eventually we may support other databases (v3 is closer), but v2.x will never support anything other than MySQL and MariaDB.

**Comment by pnelsonsr** [comment]
Ahh thanks for the info.

**Comment by pnelsonsr** [comment]
Have much experiance with PgSQL over M*SQL but it was fairly easy to get re-acquainted with it (used it years and years ago).  I was able to get the 'php artisan app:install --env=production' to run through creating the db objects it needed without any errors.

**Comment by snipe** [comment]
Yeah, MySQL and pgSQL are pretty similar.

**Comment by snipe** [comment]
It just sounds like you need to setup your port 443 virtual host entry. Something like:

```
<VirtualHost *:443>
  <Directory /var/www/html/public>
    Allow From All
    AllowOverride All
    Options +Indexes
  </Directory>

  DocumentRoot /var/www/html/public
  ServerName www.yourserver.com
  # Other directives here
</VirtualHost>
```

**Comment by snipe** [comment]
(Assuming you actually have an SSL cert setup, etc)

**Comment by pnelsonsr** [comment]
I didn't have the 443 in there but did have the certs.  Once I did that and it worked.  

I've been looking around and its really well done app and it looks nice and it's has an intuitive inteface as well...

It is not allowing me to add a user.  It always says that "The password confirm and password must match." even if I use generate.

**Comment by pnelsonsr** [comment]
I was actually able to get users added.  Sometimes it fails, sometimes it doesn't.

**Comment by snipe** [comment]
Thanks for the kind words. :) 

![believing-intensifies](https://cloud.githubusercontent.com/assets/197404/16136013/16f948a0-33dc-11e6-8605-e9daa03be1bc.gif)

The problem you're describing is pretty weird. Can you reproduce it on the demo? 

Also, I realize you've gone through some effort to get 2.1 installed, but have you looked at v3? It's still in beta, but will release in the next few days, so it might be worth it for you to look at.

**Comment by snipe** [comment]
Here are the changes in v3 from 2.1: https://snipe-it.readme.io/blog/v3-is-coming

**Comment by pnelsonsr** [comment]
I had not tried it on the demo and I'm not sure why it happens, but if I keep the pw small and just do the minimal required fields it goes through every time.  Don't know how to troubleshoot it anymore.

I am definitely interested in at v3 as we are just getting going.  Can one install it yet?  Is it hard to upgrade?
