### ISSUE TITLE
V. 3 Assets Import failed

### ISSUE THREAD

**Issue by SynchronGmbH** [snipe/snipe-it#2157]
Hello

#### Actual Behavior

**A)** I tried to import the sample CSV with dummy data for v2.1.1 from http://docs.snipeitapp.com/manual/importing-assets.html
The upload was succesfull but then I click on "Process"

I got the follow message:
![unbenannt2](https://cloud.githubusercontent.com/assets/18677910/16074852/bd5d6ec4-32ec-11e6-959d-daf92ac2becc.PNG)

**B)** I tried to import Sample asset import CSV. from https://snipe-it-manual.readme.io/docs/importing-assets

The upload succesfull. But after clicking on "Process" I got the the follow message:
![unbenannt3](https://cloud.githubusercontent.com/assets/18677910/16074944/1143e6bc-32ed-11e6-8198-0c4c5625b041.PNG)

Probably a bug ?

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

**Snipe-IT version 	v3.0.0-dev-3-g6d810a9
PHP Version 	        7.0.7
Laravel Version 	5.2.22**

**Comment by dmeltzer** [comment]
Hi,

1) The csv from 2.1 will not work with v3.  

2) When You get the some items did not import correctly, you should see a list of the errors lower on the page.  If you don't see errors, can you take a look at/share your <snipeit>/storage/logs/importer.log ?

**Comment by SynchronGmbH** [comment]
**Thank you for reply**

1) oh yeah of course 

2) I tried to upload the demo at  https://v3.snipeitapp.com. So this SnipeIT doesn't run on my server. Is there still a way to see the errors ? 

3) I only find text files (e.g. log-apache2handler-2016-06-15.txt)   in the folder logs (/../storage/logs/)

**Comment by snipe** [comment]
@SynchronGmbH unfortunately, if you don't have access to the server, you're not going to be able to view the logs. You're using the updated CSV of sample data? 

That code is here:

```
if (!empty($item["purchase_cost"])) {
			$purchase_cost = substr($item["purchase_cost"],0,1) === '$' ? substr($item["purchase_cost"],1) : $item["purchase_cost"];
			$asset->purchase_cost = number_format($purchase_cost,2);
			$this->log("Asset cost parsed: " . $asset->purchase_cost);
		}
```
So it sounds like the data is a string, and it's expecting a number. Can you check the CSV to see if there's any funny stuff in the purchase_cost column?

**Comment by SynchronGmbH** [comment]
We are using Snipe-IT  v2.1.0-8-g1b1a733 and this version run on our servers. 
We are testing  Demo Snipe-IT version v3.0.0-dev-3-g6d810a9.

Yes we are testing the SnipeIT V.3 with CSV of sample data for V. 3:
![screenshot - 16 06 2016 - 08 11 41](https://cloud.githubusercontent.com/assets/18677910/16107055/f779de3c-3399-11e6-93c3-df99c7eb2a83.png)

The purchase_cost column is either empty  or filled with numbers 
![screenshot - 16 06 2016 - 08 23 23](https://cloud.githubusercontent.com/assets/18677910/16107263/99da6b96-339b-11e6-869c-540641c3e3a5.png)
