### ISSUE TITLE
Feature Request: Asset Name is not displayed

### ISSUE THREAD

**Issue by MPIAE-IT** [snipe/snipe-it#2158]
You can type in the Asset Name and it will be displayed in the asset list. But if you click on an asset, the asset name is nowhere to be found.

Is it possible to show the asset name when you are on the detail site of the asset?

**Comment by snipe** [comment]
Can you provide screenshots? And tell us what version you're using.

**Comment by veen1981** [comment]
Same here on v3.0.0-dev-3-g6d810a9

When you click on any asset to view details - only the asset tag number is displayed, it would be extremely helpful if the asset name could be displayed at the top next to the asset tag number...

![capture](https://cloud.githubusercontent.com/assets/14188055/16092702/e508b14e-3306-11e6-958f-008c46a0115b.PNG)

Also, when viewing assets and selecting which columns to display, specifically showing the asset name, the column view settings do not save between session like they did in version 2*, is it possible to add that?

**Comment by MPIAE-IT** [comment]
Its on the demo also... Version is git-clone yesterday v3-master.

![1](https://cloud.githubusercontent.com/assets/16922521/16092864/d47153b2-3339-11e6-9fb4-d9ff4d9f984c.png)

![2](https://cloud.githubusercontent.com/assets/16922521/16092916/001aabc6-333a-11e6-8d99-98b654d635e8.png)

**Comment by snipe** [comment]
<img width="374" alt="slack" src="https://cloud.githubusercontent.com/assets/197404/16092965/c5261032-32ee-11e6-8276-7288a6ce6c49.png">

**Comment by MPIAE-IT** [comment]
No thats the Asset Tag being displayed.

**Comment by snipe** [comment]
Huh. Not sure how we missed that.

**Comment by veen1981** [comment]
@snipe Thank you!

**Comment by MPIAE-IT** [comment]
THANK YOU 👍

**Comment by MPIAE-IT** [comment]
> Also, when viewing assets and selecting which columns to display, specifically showing the asset name, the column view settings do not save between sessions like they did in version 2*, is it possible to add that?

I also noticed that. Would be cool if this can be saved.

**Comment by snipe** [comment]
@MPIAE-IT I can't reproduce that behavior. It saves state for me.

**Comment by MPIAE-IT** [comment]
Correct. On your demo it is saving it. I need to check my system again. Will do tomorrow. Thanks anyway! 👍

**Comment by snipe** [comment]
That state is saved in a cookie via the javascript. Maybe try clearing your browser cookies?

**Comment by MPIAE-IT** [comment]
Sure, I will try that first thing tomorrow! Thanks
