### ISSUE TITLE
New Feature: "Users cannot log in" setting 

### ISSUE THREAD

**Issue by uberbrady** [snipe/snipe-it#2160]
#### Expected Behavior (or desired behavior if a feature request)

When adding users that I do not ever want to be able to log in to the system, I still have to create a username and a password for the users. I don't ever want them to be able to log in in the first place, so I would like it if there was a global setting "End-Users will never log in to the system" which would take those fields away - specifically from the in-line user-creation screen.

---
#### Actual Behavior

When I create users in-line to assign assets to them, I need to come up with usernames and passwords for each. I understand there are password generator functions I could use if I were creating the users from the user-creation screen, but I am creating them in-line. Also, there is a security implication - a potential set of user credentials that might have access to the system. I would rather that not exist at all.

As a further security measure, this global setting could be referenced on any login attempt, and could reject potential logins from non-administrative users when the setting is activated.

---
#### Please confirm you have done the following before posting your bug report:
- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
We'd still need to generate credentials for them, since username and password are required on the User model.

**Comment by uberbrady** [comment]
Could we maybe do something where we modify the validations so that, if the setting were set, it wouldn't require username and password? Or are we worried that would muck up the data model too much? Or is it 'too weird' to have the User model reaching into the Settings to determine how to validate stuff?

**Comment by snipe** [comment]
I think that's basically what "activated" does

**Comment by n-v-o** [comment]
> I think that's basically what "activated" does

Could you confirm what activated is suppose to do?

I am interested in this feature as well.  Apologies, I'm not a developer, so I haven't gone digging into any of the code, but I have been scouring the documentation for the actual purpose of the "Activated" field, and haven't found out.

I'm spinning up a Snipe IT (installed via GIT, running 4.5) and I manually created a test user. I can log in the test account, regardless if Active is set to yes or no.  From the context above, I would think if the activated field was set to no, a user wouldn't be able to login.
