### ISSUE TITLE
Whoops error on debug, no matter what page.

### ISSUE THREAD

**Issue by jtlindro** [snipe/snipe-it#2161]
#### Expected Behavior (or desired behavior if a feature request)

Open a normal page without errors and then be able to use debug mode on an LDAP issue i'm getting. 

-----

#### Actual Behavior

Whenever I enable debug in \app\config\production\app.php all pages now load to a Whoops error page. They load normally if i disable debugging.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running -  **(v2.1.1)**

- What OS and web server you're running Snipe-IT on - **Winodws-IIS**

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - **manual installation**

- If you're getting an error in your browser, include that error

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - **any page**

- If a stacktrace is provided in the error, include that too.
**
Stack trace:
#0 E:\inetpub\wwwroot\snipeIT\vendor\laravel\framework\src\Illuminate\Exception\Handler.php(280): Illuminate\Exception\WhoopsDisplayer->display(Object(ParseError))
#1 E:\inetpub\wwwroot\snipeIT\vendor\laravel\framework\src\Illuminate\Exception\Handler.php(159): Illuminate\Exception\Handler->displayException(Object(ParseError))
#2 E:\inetpub\wwwroot\snipeIT\vendor\laravel\framework\src\Illuminate\Exception\Handler.php(170): Illuminate\Exception\Handler->handleException(Object(ParseError))
#3 [internal function]: Illuminate\Exception\Handler->handleUncaughtException(Object(ParseError))
#4 {main}
  thrown"

#1 Symfony\Component\Debug\Exception\FatalErrorException in E:\inetpub\wwwroot\snipeIT\vendor\laravel\framework\src\Illuminate\Exception\WhoopsDisplayer.php:43
#0 Illuminate\Exception\Handler:handleShutdown in <#unknown>:0**

- Any errors that appear in your browser's error console.
**Symfony\Component\Debug\Exception\FatalErrorException thrown with message "Uncaught TypeError: Argument 1 passed to Illuminate\Exception\WhoopsDisplayer::display() must be an instance of Exception, instance of ParseError given, called in E:\inetpub\wwwroot\snipeIT\vendor\laravel\framework\src\Illuminate\Exception\Handler.php on line 280 and defined in E:\inetpub\wwwroot\snipeIT\vendor\laravel\framework\src\Illuminate\Exception\WhoopsDisplayer.php:43**

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

- Include what you've done so far in the installation, and if you got any error messages along the way.
**Was in the process of enabling LDAP synchronization. I had configured the settings and was trying to do my first sync and I got sent to a browser error page (Server Error: 500 (Internal Server Error)). So I went to enable debugging to try and work it out and now all pages give the error listed above.**

- Indicate whether or not you've manually edited any data directly in the database **No manual edits to database were done**

**Comment by snipe** [comment]
Can you show me how you'e enabling debug? Show me that app.php
