### ISSUE TITLE
Feature Request: Asset Tag field for Licences and Components

### ISSUE THREAD

**Issue by L3nny5** [snipe/snipe-it#2162]
Hey again,

we are from the global sector in Germany and everything we buy over 150 € gets an asset tag. 
Also if it is Software or components. 

It would be very helpful if there would be an asset tag field in components and licenses as well.

Just creating these in the category "Assets", I would not be able to use the check out to asset function (components) or having the correct fields for software (licenses).

Of course this field should be optional.

Thanks again for this great product!

Lenny

**Comment by MPIAE-IT** [comment]
Also having the supplier drop down menu for components, consumables and accessories would be nice.
