### ISSUE TITLE
V3 Feature Request - Link Asset Model Image to Asset Images

### ISSUE THREAD

**Issue by veen1981** [snipe/snipe-it#2163]
Would it be possible, instead of uploading an image for an individual asset, to instead use the image that is uploaded under the asset model? 

So for an example, I have a Lenovo M700 Tiny in my Asset Models with an image of the device. I create two new assets using this model type, after creating and saving the new assets, when I click to view the detail, the image that is uploaded to the asset model appears under the asset details for both the assets using this model...

**Comment by snipe** [comment]
That should already be happening, if there is a model image uploaded and no asset image:

```
'image' => (($asset->image) && ($asset->image!='')) ? '<img src="'.config('app.url').'/uploads/assets/'.$asset->image.'" height=50 width=50>' : ((($asset->model) && ($asset->model->image!='')) ? '<img src="'.config('app.url').'/uploads/models/'.$asset->model->image.'" height=40 width=50>' : ''),
```

**Comment by veen1981** [comment]
The images show fine when I am under Asset models...

![capture1](https://cloud.githubusercontent.com/assets/14188055/16242552/ec20f7e8-37c0-11e6-8567-0b727c6901b0.PNG)

But when I look at the asset details I just get a broken image link placeholder....

![capture2](https://cloud.githubusercontent.com/assets/14188055/16242570/fc80291a-37c0-11e6-9e5a-07bc748c9fb9.PNG)

This is what I see when I inspect element.
<img src="/hardware/11060/qr_code" class="img-thumbnail pull-right" style="height: 100px; width: 100px; margin-right: 10px;">

**Comment by veen1981** [comment]
![capture3](https://cloud.githubusercontent.com/assets/14188055/16242602/34e22ce0-37c1-11e6-9196-bfdd1024e7e9.PNG)

Sorry, meant to comment, not close.

**Comment by snipe** [comment]
That's your QR code, not your asset image.

**Comment by veen1981** [comment]
Ok my bad, sorry about that. I see that now.

**Comment by snipe** [comment]
I don't think this is resolved, per se. I need to check that the model image is even being included on the details page.

**Comment by veen1981** [comment]
ok

**Comment by snipe** [comment]
This should be fixed on v3 and v3 master now

**Comment by veen1981** [comment]
Awesome, I'll check it out when i get back in at work tomorrow! Thank you for all you do!

**Comment by snipe** [comment]
![30-rock-thumbs-up](https://cloud.githubusercontent.com/assets/197404/16243322/8d89eace-37ab-11e6-81c8-3267788c1537.gif)
