### ISSUE TITLE
Snipe IT does not prompt for login when current login times out.

### ISSUE THREAD

**Issue by kksimpkins** [snipe/snipe-it#2167]
#### Expected Behavior (or desired behavior if a feature request)

When trying to perform a search after the current session has expired, I expect to be taken to the Login page to re-authenticate my session.

-----

#### Actual Behavior

When coming back to webpage after the current login session expires and typing in the Search box on the All Assets page, the page only reloads. It is not apparent you need to login to the website again.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v2.1.0-41
- What OS and web server you're running Snipe-IT on - Ubuntu 14.04.4 LTS, Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual install using custom script from https://github.com/snipe/snipe-it/issues/867
- If you're getting an error in your browser, include that error - none
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - All Assets page, the Search box
- If a stacktrace is provided in the error, include that too. - none
- Any errors that appear in your browser's error console. - none
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). - not reproduceable on demo website
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. - none 
- Include what you've done so far in the installation, and if you got any error messages along the way. - none
- Indicate whether or not you've manually edited any data directly in the database - no manual database edits

**Comment by snipe** [comment]
This is in the top search box, or the all assets filter box?

**Comment by kksimpkins** [comment]
Hi,

The “Search” box under the “+ Create New” button.

[cid:image001.png@01D1C7D7.C6E41EF0]

Best Regards,

Kevin K. Simpkins
Senior Technical Analyst, IT Computing Services

**Comment by snipe** [comment]
Can you send a screenshot? There isn't really a search box under the create new button, so I want to clarify what you're asking about. (I assume it's the earth filter under the listing view)

**Comment by kksimpkins** [comment]
Sure. I copied it in my first response, but I think it did not go through. I'm attaching as a file.
![snipe-it_tbsh](https://cloud.githubusercontent.com/assets/17497817/16127960/b05bd180-33cc-11e6-9059-b691b561453a.jpg)

**Comment by kksimpkins** [comment]
One detail I forgot to mention, I'm using LDAP for authentication.

**Comment by snipe** [comment]
Ah, yeah, you can't send images to GH in email messages.

It's a valid bug, but I admit it's a lower priority one on our end.

**Comment by kksimpkins** [comment]
Ok, the issue appears to be with Cyberfox. I left Google Chrome signed in over the weekend. I just tried a search, and it worked. I did not have to sign back in to the website. Thanks.

**Comment by kksimpkins** [comment]
I spoke too soon. Went back to Chrome again and experienced the same issue. Typing in the search box basically did nothing. I refreshed the page, logged back in. Then I was able to search.

**Comment by kksimpkins** [comment]
Ok, the issue seems to be related to Debian/Ubuntu PHP Session handling.

From https://stackoverflow.com/questions/8311320/how-to-change-the-session-timeout-in-php

+++++++
If you use PHP's default session handling, the only way to reliably change the session duration in all platforms is to change php.ini. That's because in some platforms, garbage collection is implemented through a script that runs every certain time (a cron script) that reads directly from php.ini, and therefore any attempts at changing it at run time, e.g. via ini_set(), are unreliable and most likely 
won't work.

For example, in Debian Linux systems, garbage collection is done via /etc/cron.d/php5 which runs at XX:09 and XX:39 (that is, every half hour), and if it finds a session older than the session.gc_maxlifetime specified in php.ini, then that session is deleted without mercy. That also explains why in this question: PHP sessions timing out too quickly, the OP had problems in one host but the problems ceased 
when switching to a different host.
+++++++

So, I decided to upgrade. I'm now running Snipe-IT version 3.4.0-9-g67315d8 on Fedora Server 24. I no longer experience this issue.
