### ISSUE TITLE
Trouble during install

### ISSUE THREAD

**Issue by ozanam** [snipe/snipe-it#2168]
Hello,

I am trying to install snipe-it. I am at the stage of the composer. 

I am in /var/www/snipe-it and i have run curl -sS https://getcomposer.org/installer | php

I get the following error.

-----

myusername@smart-snipe:/var/www/snipeit$ curl -sS https://getcomposer.org/installer | php
All settings correct for using Composer
PHP Warning:  file_put_contents(/home/myusername/.composer/keys.dev.pub): failed to open stream: Permission denied in - on line 466
PHP Warning:  file_put_contents(/home/myusername/.composer/keys.tags.pub): failed to open stream: Permission denied in - on line 483
Downloading 1.1.2...
Could not create file /var/www/snipeit/composer.phar: fopen(/var/www/snipeit/composer.phar): failed to open stream: Permission denied
Download failed: fopen(/var/www/snipeit/composer.phar): failed to open stream: Permission denied
fwrite() expects parameter 1 to be resource, boolean given
Downloading 1.1.2...
Could not create file /var/www/snipeit/composer.phar: fopen(/var/www/snipeit/composer.phar): failed to open stream: Permission denied
Download failed: fopen(/var/www/snipeit/composer.phar): failed to open stream: Permission denied
fwrite() expects parameter 1 to be resource, boolean given
Downloading 1.1.2...
Could not create file /var/www/snipeit/composer.phar: fopen(/var/www/snipeit/composer.phar): failed to open stream: Permission denied
Download failed: fopen(/var/www/snipeit/composer.phar): failed to open stream: Permission denied
fwrite() expects parameter 1 to be resource, boolean given
The download failed repeatedly, aborting.

-----
#### Please provide answers to these questions before posting your bug report:

- the latest master version 
- ubuntu 16.04
- install.sh
- no data manually edited 

any help would be greatly appreciated.

**Comment by snipe** [comment]
That's a permissions issue. Usually happens when your web directory is owned by root.

**Comment by ozanam** [comment]
Hello,

thank you for your response.. i have just run a fresh install and i got the following error at the end of the install

[Illuminate\Database\QueryException]                                                                                
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at' (SQL: create table   
  `users` (`id` int unsigned not null auto_increment primary key, `email` varchar(255) not null, `password` varchar(  
  255) not null, `permissions` text null, `activated` tinyint(1) not null default '0', `activation_code` varchar(255  
  ) null, `activated_at` timestamp null, `last_login` timestamp null, `persist_code` varchar(255) null, `reset_passw  
  ord_code` varchar(255) null, `first_name` varchar(255) null, `last_name` varchar(255) null, `created_at` timestamp  
   default 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicode_ci  
   engine = InnoDB)                                                                                                   
                                                                                                                      




                                                                                                  
  [PDOException]                                                                                  
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at'

**Comment by ozanam** [comment]
Ok so I wiped that server and rolled back to 14.04 and tried again. There was allot more questions during the install and it looked like it ran smoothly. When i goto the webpage i am getting Ouch. Server Error: 500 (Internal Server Error)

![snipe](https://cloud.githubusercontent.com/assets/19982702/16152807/69b9ced8-349b-11e6-8ae4-f0a334357368.PNG)

**Comment by ozanam** [comment]
Resolved it

what i did was i re-ran install.sh from and when asked to autocreate database username and password , i chose to manually set them up and then everything started working fine.
