### ISSUE TITLE
Feature Request: Ability to list user on maintenance, also maintenance log in asset history.

### ISSUE THREAD

**Issue by crsdtech** [snipe/snipe-it#2169]
First, **_LOVE_** Snipe-IT, great work!

One thing I think would be really handy is the ability to list the user in an Asset Maintenance and be able to export a maintenance/damage report. This way when a user abuses an asset, a damage report could be printed off and attached to a bill- or set up the damage report as a bill. Logging the maintenances in asset history and user history (if a user is tagged in a maintenance) would also be very nice. 

Keep up the great work! Thanks!

**Comment by snipe** [comment]
That's definitely something we've got on the roadmap, for exactly the reasons you mentioned :)
