### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by firozhaneef** [snipe/snipe-it#217]
I have installed snipe-it, but i am getting this error message:Error in exception handler. Please help..

**Comment by YCYee912** [comment]
Hi guyz, I am also encountering some similar problem here..
![error on snipe it](https://cloud.githubusercontent.com/assets/10839182/6032324/bc6d37e2-ac42-11e4-95fb-c6aa35f8fd67.png)
How may i solve this error?

**Comment by snipe** [comment]
@YCYee912 Did you actually run the `php composer.phar install` command per the installation instructions?

(Please open a new issue next time, as this issue was closed and isn't related to your current issue.)

**Comment by imie** [comment]
Hi, i got below problem. tried a few things but same error.

snipeit]# php artisan app:install --env=production
PHP Warning:  require(/var/www/html/snipeit/bootstrap../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/snipeit/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/html/snipeit/bootstrap../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipeit/bootstrap/autoload.php on line 17

**Comment by snipe** [comment]
http://docs.snipeitapp.com/common-issues.html#php-warning-requirevarwwwhtmlasset2bootstrapvendorautoloadphp-failed-to-open-stream-no-such-file-or-directory

**Comment by imie** [comment]
html]# php composer.phar install --no-dev --prefer-source
Loading composer repositories with package information
Installing dependencies from lock file
  - Installing symfony/event-dispatcher (2.8.x-dev e79162f)
    Cloning e79162fa079bb559ddad17c58cf8b7ecbaffd9b6

  - Installing guzzle/guzzle (dev-master b3f5050)
    Cloning b3f5050cb6270c7a728a0b74ac2de50a262b3e02

  - Installing aws/aws-sdk-php (2.8.x-dev 92642ca)
    Cloning 92642ca4906e6681a1301971cf41500d7c68581c

  - Installing symfony/finder (2.5.x-dev e527ebf)
    Cloning e527ebf47ff912a45e148b7d0b107b80ec0b3cc2

  - Installing symfony/var-dumper (2.8.x-dev 937f203)
    Cloning 937f203533edfad9d9ca64d199fcecb9b9d81f3c

  - Installing psr/log (dev-master 9e45edc)
    Cloning 9e45edca52cc9c954680072c93e621f8b71fab26

  - Installing maximebf/debugbar (dev-master ab12b6f)
    Cloning ab12b6f57dd33b1fffa875046fd17c34d88388b9

  - Installing symfony/translation (2.5.x-dev 165b534)
    Cloning 165b5348cd20f8c4b2fcf1097c9c8300d1093b90

  - Installing symfony/security-core (2.5.x-dev 3a27d7b)
    Cloning 3a27d7b34ee62cb0fdf5ad970e7777912ef4722f

  - Installing symfony/routing (2.5.x-dev 46142c3)
    Cloning 46142c34ea830f47429df6e15faec3a33292d618

  - Installing symfony/process (2.5.x-dev 00a1308)
    Cloning 00a1308e8b5aec5eba7c8f1708426a78f929be8c

  - Installing symfony/http-foundation (2.5.x-dev 08e7838)
    Cloning 08e783861dd9579bac4092814bbfb0cae6666b65

  - Installing symfony/debug (2.5.x-dev ed30195)
    Cloning ed3019589cdadf32c521d1e181f9d72955645c67

  - Installing symfony/http-kernel (2.5.x-dev 3165238)
    Cloning 31652385d94eafc2103a98435d6d5bd7eea61736

  - Installing symfony/dom-crawler (2.5.x-dev 3860edc)
    Cloning 3860edcf7ff7e173cfe2151f0d425e610e77cc35

  - Installing symfony/css-selector (2.5.x-dev d45b306)
    Cloning d45b306421462295e76b94bcf76b963867450327

  - Installing symfony/console (2.5.x-dev a43e750)
    Cloning a43e750b4c74f3bdfca77c79c343033d35a6cd6e

  - Installing symfony/browser-kit (2.5.x-dev b2b78b8)
    Cloning b2b78b850a32251cbbd9915ab61453302e7ecd72

  - Installing swiftmailer/swiftmailer (5.x-dev 6522539)
    Cloning 6522539daf0a7bdada1cc2dccb7ec37dc0712136

  - Installing stack/builder (dev-master 14afc80)
    Cloning 14afc80a5bd9dc160470e3131b697f7d0c070729

  - Installing predis/predis (0.8.x-dev 192dfd6)
    Cloning 192dfd61e54c3d32c9526bba03365fff818e17e4

  - Installing phpseclib/phpseclib (0.3.10)
    Cloning d15bba1edcc7c89e09cc74c5d961317a8b947bf4

  - Installing patchwork/utf8 (dev-master 927caed)
    Cloning 927caedc65ec4f139e9d43fd2589a19a336babc3

  - Installing nesbot/carbon (1.17.0)
    Cloning a1dd1ad9abfc8b3c4d8768068e6c71d293424e86

  - Installing monolog/monolog (1.17.1)
    Cloning 0524c87587ab85bc4c2d6f5b41253ccb930a5422

  - Installing nikic/php-parser (0.9.x-dev ef70767)
    Cloning ef70767475434bdb3615b43c327e2cae17ef12eb

  - Installing jeremeamia/superclosure (1.0.x-dev 4d89ca7)
    Cloning 4d89ca74994feab128ea46d5b3add92e6cb84554

  - Installing ircmaxell/password-compat (1.0.x-dev 9b99377)
    Cloning 9b99377557a33a4129c9194e60a97a685fab21e0

  - Installing filp/whoops (1.1.7)
    Cloning 72538eeb70bbfb11964412a3d098d109efd012f7

  - Installing d11wtq/boris (v1.0.8)
    Cloning 125dd4e5752639af7678a22ea597115646d89c6e

  - Installing symfony/filesystem (2.8.x-dev 287fc0b)
    Cloning 287fc0b1dcb11ff729eeefc20441c08eaf628f29

  - Installing classpreloader/classpreloader (1.0.2)
    Cloning 2c9f3bcbab329570c57339895bd11b5dd3b00877

  - Installing laravel/framework (v4.2.17)
    Cloning 3359de6d6cd322e8a1b251c2f8d9dd42a3e4e232

  - Installing barryvdh/laravel-debugbar (1.8.x-dev 8833c88)
    Cloning 8833c88c40f840de9bfaf71247ffdfb341c0d390

  - Installing cartalyst/sentry (v2.1.5)
    Cloning 0ae4158353e41cc4061631c86c1cddd67c1f23be

  - Installing chumper/datatable (2.3)
    Cloning cff842783f3f4af60c2be295435b2bd812510ef5

  - Installing chumper/zipper (0.5.1)
    Cloning d1ab536b4de2c313cd1c28ea01f5bcefbad33610

  - Installing doctrine/lexer (dev-master 83893c5)
    Cloning 83893c552fd2045dd78aef794c31e694c37c0b8c

  - Installing doctrine/annotations (dev-master f25c8aa)
    Cloning f25c8aab83e0c3e976fd7d19875f198ccf2f7535

  - Installing doctrine/cache (dev-master dd47003)
    Cloning dd47003641aa5425820c0ec8a6f4a85e7412ffcd

  - Installing doctrine/collections (dev-master 866e100)
    Cloning 866e100a425b8b73d15393fd081c6bf067f05bf9

  - Installing doctrine/inflector (dev-master 3a422c7)
    Cloning 3a422c73f7bc556d39571f436b61fd58ccae0eb0

  - Installing doctrine/common (dev-master 9f35e74)
    Cloning 9f35e74fcbe9011b660e0b423e98c83b7a8699c0

  - Installing doctrine/dbal (v2.4.2)
    Cloning fec965d330c958e175c39e61c3f6751955af32d0

  - Installing erusev/parsedown (dev-master fa005fd)
    Cloning fa005fdb954330ae6dccb3bb59481da0172d397e

  - Installing fideloper/proxy (2.1.1)
    Cloning a0ec0f35c82dceecc0d8975f29e6e8e85acbd419

  - Installing react/promise (v2.2.1)
    Cloning 3b6fca09c7d56321057fa8867c8dbe1abf648627

  - Installing guzzlehttp/streams (dev-master d1f8a6c)
    Cloning d1f8a6c55f0f753cfd6f6755856473eb02cedb19

  - Installing guzzlehttp/ringphp (dev-master 9465032)
    Cloning 9465032ac5d6beaa55f10923403e6e1c36018d9c

  - Installing psr/http-message (dev-master 85d6369)
    Cloning 85d63699f0dbedb190bbd4b0d2b9dc707ea4c298

  - Installing guzzlehttp/psr7 (1.2.0)
    Cloning 4ef919b0cf3b1989523138b60163bbcb7ba1ff7e

  - Installing intervention/image (dev-master 44c9a6b)
    Cloning 44c9a6bb292e50cf8a1e4b5030c7954c2709c089

  - Installing league/csv (dev-master 640f57a)
    Cloning 640f57af7abb41d51673cd860041979623cee423

  - Installing guzzlehttp/guzzle (5.3.0)
    Cloning f3c8c22471cb55475105c14769644a49c3262b93

  - Installing maknz/slack (dev-master c8ed3e4)
    Cloning c8ed3e4f919358af43516e7ab8d7fa39d3d2f736

  - Installing aws/aws-sdk-php-laravel (1.0.x-dev ce9a9b5)
    Cloning ce9a9b5144d16c9bebda23f41c2dfc7f8da38471

  - Installing schickling/backup (0.6.0)
    Cloning 5243dc1d9b11390e1eb58202fd07dc3829b1bbe0

  - Installing symfony/config (2.8.x-dev a1e8e51)
    Cloning a1e8e51ed2d591bb1827d04fd1d320cd4f03e5fe

  - Installing symfony/stopwatch (2.8.x-dev 9eb95ce)
    Cloning 9eb95ce869cf480c0dc3a1891ae70037d50b43ce

  - Installing symfony/yaml (2.8.x-dev d196cb1)
    Cloning d196cb1ac36901bde7d7fbed74ee31fdb85fd119

  - Installing tecnickcom/tc-lib-color (dev-master 3e1268d)
    Cloning 3e1268d4cc95f55bbe81eac5507c02dccafcb370

  - Installing tecnickcom/tc-lib-barcode (dev-master 3d76d63)
    Cloning 3d76d63b8a622a67664ec60a13d9c33189721784

Generating autoload files
html]# php artisan app:install --env=production

PHP Warning:  require(/var/www/html/bootstrap../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/html/bootstrap../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/bootstrap/autoload.php on line 17

**Comment by snipe** [comment]
The only thing I can suggest is that you delete your `composer.lock` file and run `php composer.phar update`.

Also, next time please create a new issue, as your issue is unrelated to the original issue in this ticket.

**Comment by imie** [comment]
owh, thanks... i will create new ticket.
