### ISSUE TITLE
Validation errors on creating asset maintenance

### ISSUE THREAD

**Issue by BrettFagerlund** [snipe/snipe-it#2170]
Version v3.0.0-dev-3
OS: Windows Server 2012 R2
Install Type: manual install
Page: admin/asset_maintenances/create
Fields: Supplier field causes the most issues, but validation doesn't seem to exist on other required fields.
Cannot reproduce on V2 demo
Can reproduce on clean install of v3.0.0-dev-3
Excluded full stack trace as errors can easily be reproduced , but can include if required.

#### Expected Behavior (or desired behavior if a feature request)

Standard field validation on create/edit Maintenance pages, to prevent invalid values going in.

-----

#### Actual Behavior

If you enter without filling required fields "Title" or "Type" it will create maintenance with blanks.
If you enter without entering supplier it will generate a null constraint SQL error in debug mode on the asset_maintenances.supplier_id field.
In addition, if editing the maintenance, you can remove supplier field making all maintenance to dissapear and causing the asset attached to present error when clicked on to open "hardware/{AssetID}/view"
Trying to get property of non-object (View: \resources\views\hardware\view.blade.php)

-----

**Comment by dmeltzer** [comment]
This should be fixed with 5a45ec7
