### ISSUE TITLE
Silent install of php artisan

### ISSUE THREAD

**Issue by cduverne** [snipe/snipe-it#2178]
#### Expected Behavior (or desired behavior if a feature request)

Would it be possible to predefine the answers to the installation script when using docker images ?

We're using ansible to deploy the docker images in a microservice fashion, then constantly deploying and redeploying services.

Therefore having the ability to predefine the answers to ```docker exec -i -t snipeit php artisan app:install``` would be greatly useful.

-----

#### Actual Behavior

Interactive answers to ```docker exec -i -t snipeit php artisan app:install```

-----

#### Please confirm you have done the following before posting your bug report:

- [N/A] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running : 2.1.2
- What OS and web server you're running Snipe-IT on : Ubuntu 12.04 / Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) : Docker, via Ansible
- If you're getting an error in your browser, include that error : N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error : N/A
- If a stacktrace is provided in the error, include that too. : N/A
- Any errors that appear in your browser's error console. : N/A
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). : N/A
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. : N/A
- Include what you've done so far in the installation, and if you got any error messages along the way. : N/A
- Indicate whether or not you've manually edited any data directly in the database : N/A

**Comment by snipe** [comment]
v3 doesn't use the `php artisan app:install` command anymore, so you may want to upgrade.

**Comment by cduverne** [comment]
Thanks for your quick answer.

As far as I can see the docker installation doc is focused on v2.x not on
v3.

What are the changes ?

2016-06-21 2:21 GMT+02:00 snipe <notifications@github.com>:

> v3 doesn't use the php artisan app:install command anymore, so you may
> want to upgrade.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/snipe/snipe-it/issues/2178#issuecomment-227307942>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABZAZITqk16-IRP4z04wsIZsuKUzXTMhks5qNy6lgaJpZM4I5vIu>
> .
>

-- 
♻ Be green, keep it on the screen

**Comment by snipe** [comment]
https://snipe-it.readme.io/blog/v3-is-coming
https://snipe-it.readme.io/docs/docker

**Comment by snipe** [comment]
Did you use the Ansible script that a user created, or the actual official docker release?
