### ISSUE TITLE
Webpage loading laravel framework instead of Snipe Homepage

### ISSUE THREAD

**Issue by matt34533** [snipe/snipe-it#2180]
Expectation
I've fully installed and configured the app so it should be loading the homepage. 

-----

Problem
Site loads php framework instead (index.php)

-----

- What OS and web server you're running Snipe-IT on: centos 7, apache 2
- What method you used to install Snipe-IT: install.sh
![image](https://cloud.githubusercontent.com/assets/20049425/16203327/9556d8c6-36ce-11e6-8c50-2052911a2f75.png)

**Comment by snipe** [comment]
Looks like you don't have PHP installed, or index.php files are not set to parse PHP.

**Comment by matt34533** [comment]
Could've sworn I reinstalled it after uninstalling it to install mcrpyt. 
Now that it is installed, the site only displays: Error in exception handler.

The var/log/httpd/error_log shows this:
[Mon Jun 20 10:42:40.769583 2016] [mpm_prefork:notice] [pid 12301] AH00170: caught SIGWINCH, shutting down gracefully
[Mon Jun 20 10:42:41.912406 2016] [core:notice] [pid 12795] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Mon Jun 20 10:42:41.914340 2016] [suexec:notice] [pid 12795] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Mon Jun 20 10:42:41.964676 2016] [so:warn] [pid 12795] AH01574: module rewrite_module is already loaded, skipping
[Mon Jun 20 10:42:41.966795 2016] [auth_digest:notice] [pid 12795] AH01757: generating secret for digest authentication ...
[Mon Jun 20 10:42:41.968533 2016] [lbmethod_heartbeat:notice] [pid 12795] AH02282: No slotmem from mod_heartmonitor
[Mon Jun 20 10:42:42.027132 2016] [mpm_prefork:notice] [pid 12795] AH00163: Apache/2.4.6 () PHP/7.0.7 configured -- resuming normal operations
[Mon Jun 20 10:42:42.027173 2016] [core:notice] [pid 12795] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'

**Comment by snipe** [comment]
Looks like an SELinux permissions problem. 
v2.x: http://docs.snipeitapp.com/installation/server/linux-osx.html#notes-on-selinux
v3: https://snipe-it.readme.io/docs/linuxosx#notes-on-selinux

**Comment by matt34533** [comment]
I am attempting to use the command example but modified with the proper directory but it is stating every change is an invalid argument. 

Command
chcon -R - -type httpd_sys_rw_content_t /var/www/html/snipeit/

Error
chcon: failed to change context of ‘/var/www/html/snipeit/’ to ‘unconfined_u:object_r:ype:s0’: Invalid argument

I apologize my understanding of Linux is limited.

**Comment by matt34533** [comment]
I got the command to work by editing spacing (It ran without any output so I assume it worked)
but I am still getting the error and errorlog output when I attempt to access the file.

[Mon Jun 20 15:21:53.759168 2016] [mpm_prefork:notice] [pid 16462] AH00170: caught SIGWINCH, shutting down gracefully
[Mon Jun 20 15:21:54.908472 2016] [core:notice] [pid 18952] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Mon Jun 20 15:21:54.910468 2016] [suexec:notice] [pid 18952] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Mon Jun 20 15:21:54.962884 2016] [so:warn] [pid 18952] AH01574: module rewrite_module is already loaded, skipping
[Mon Jun 20 15:21:54.965068 2016] [auth_digest:notice] [pid 18952] AH01757: generating secret for digest authentication ...
[Mon Jun 20 15:21:54.966846 2016] [lbmethod_heartbeat:notice] [pid 18952] AH02282: No slotmem from mod_heartmonitor
[Mon Jun 20 15:21:55.006756 2016] [mpm_prefork:notice] [pid 18952] AH00163: Apache/2.4.6 () PHP/7.0.7 configured -- resuming normal operations
[Mon Jun 20 15:21:55.006801 2016] [core:notice] [pid 18952] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'

**Comment by matt34533** [comment]
I'm going to bump this, I hope this isn't an issue but I've working at this, looking at log files, looking at past threads etc and have gotten nowhere with it.

**Comment by snipe** [comment]
This is not a Snipe-IT issue, this is a SELinux issue.

**Comment by bsiders** [comment]
I have this same issue on Ubuntu. The index.php is being parsed as plain text. PHP is installed 5.5.9

Composer seems to have completed succesfully and the lavarael DB initialize passed successfully

**Comment by snipe** [comment]
@bsiders that's a server configuration issue and is really outside the scope of Snipe-IT support. That said, you might want to check that you have `AddType application/x-httpd-php .php` in your Apache configs. 

More info and some additional suggestions here:
http://stackoverflow.com/questions/3555681/why-are-my-php-files-showing-as-plain-text

**Comment by bsiders** [comment]
@snipe Thanks for the quick input, this did put me down the right path.

I am working on a chef cookbook.

**Comment by snipe** [comment]
@bsiders awesome - would love to see it when you're done. Closing this ticket for now.
