### ISSUE TITLE
Full Support Multiple Companies feature

### ISSUE THREAD

**Issue by fatihbm** [snipe/snipe-it#2181]
#### Expected Behavior (or desired behavior if a feature request)

It is required to "Checkout to" function should not list to another company users. Just the same company users in the list.

-----

#### Actual Behavior

There are separate companies definitions for each user.
Nevertheless, users can see other users of the other company while adding new assets.
How can I prevent it?

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:
- Full Support Multiple Companies feature is active
- Version of Snipe-IT v2.1.1
- Ubuntu

**Comment by snipe** [comment]
We're not adding new features to v2, since v3 is almost out and has a significantly changed codebase. Please check the v3 demo and see if you can reproduce this. https://snipe-it.readme.io/blog/v3-is-coming
