### ISSUE TITLE
error creating Consumable

### ISSUE THREAD

**Issue by brazda** [snipe/snipe-it#2184]
#### Expected Behavior (or desired behavior if a feature request)

When I add consumables and click save it should add it  

-----

#### Actual Behavior

When I add a consumable and click save I get a error 
 Error: Please check the form below for errors

But no actual error appears as all the files are filled out.  This occurred after a upgrade from 2.1.0 to 2.1.2 

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

Debug info

`select * from `users` where `users`.`deleted_at` is null and `users`.`id` = '3' limit 11.25ms
select * from `throttle` where `user_id` = '3' limit 1830μs
select `groups`.*, `users_groups`.`user_id` as `pivot_user_id`, `users_groups`.`group_id` as `pivot_group_id` from `groups` inner join `users_groups` on `groups`.`id` = `users_groups`.`group_id` where `users_groups`.`user_id` = '3'840μs
select `name`, `id` from `categories` where `category_type` = 'consumable' and `deleted_at` is null order by `name` asc870μs
select `name`, `id` from `companies` order by `name` asc580μs
select `name`, `id` from `locations` where `locations`.`deleted_at` is null order by `name` asc980μs
select * from `settings` where `settings`.`id` = '1' limit 11.31ms
select * from `settings` limit 11ms
select * from `throttle` where `user_id` = '3' limit 1760μs
select * from `throttle` where `user_id` = '3' limit 1670μs
select * from `throttle` where `user_id` = '3' limit 1840μs
select * from `throttle` where `user_id` = '3' limit 1710μs`

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
2.1.2

- What OS and web server you're running Snipe-IT on
CentOS Linux release 7.2.1511 (Core)

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh

- If you're getting an error in your browser, include that error
 Error: Please check the form below for errors

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
no

**Comment by kiriach1** [comment]
Yo, got the same problem - but only if u set the user in a company...
After deactivating the multiple company support and remove the user from companies as well, no error message appears... @snipe maybe a bug while creating the tables in database - once there are a table missing in "consumables_users"... kindly find the last log after my last error message.

cheers,
cris

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'company_id' in 'where clause' (SQL: select * from `consumables_users` where `company_id` = 1 and `consumables_users`.`consumable_id` in (4) order by `created_at` desc)' in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(581): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(304): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))

**Comment by dmeltzer** [comment]
Did you run a `php artisan migrate` when updating? I think the db changed some between versions.
