### ISSUE TITLE
Mass checkout of assets

### ISSUE THREAD

**Issue by SimoneTredoux** [snipe/snipe-it#2199]
#### Desired Behavior

We deal with large numbers of assets which come in and go out in bulk (200+ assets at a time). 
We check assets into snipe-it in bulk using the import tool, but is there a way to checkout multiple assets to a single user simultaneously?
i.e all 200 assets being sent to a specific company get checked out to one specific user (the guardian) who then controls the distribution of the assets separately (using their own system).

It would be very useful if there was a way to select multiple assets and edit the user **OR** if you could import a list of the assets to be checked out which would allow you to update the user of already existing assets instead of creating duplicate assets.

-----

#### Actual Behavior

Currently we have to check out each asset individually
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Snipe-IT v2.0.5-pre-57-g5ebb267

**Comment by ddreier** [comment]
Issue #588 already exists for this feature request.
