### ISSUE TITLE
Support for "unlimited" licenses

### ISSUE THREAD

**Issue by oskaremil** [snipe/snipe-it#220]
I have some licences I am allowed to deploy to an unlimited number of machines.

I would like to not have to fill inn the seat-number textbox to indicate that this license can be used on unlimited computers at the same time.
##

**Comment by thwr** [comment]
This is somehow similar to Windows Server Datacenter licenses ("VM flatrate"), NoMagic / IBM floating licenses and Adobe "Concurrent Use". We want to track them, but usage is basically unlimited.
