### ISSUE TITLE
SnipeIT fails to create user after authentication with LDAP

### ISSUE THREAD

**Issue by shafmeister** [snipe/snipe-it#2211]
#### Expected Behavior

SnipeIT verifies user is present in AD via LDAP, creates new user on local database and allows user to sign on. 

-----

#### Actual Behavior

SnipeIT verifies user is present in LDAP, fails to create a new user on local database and does not allow user to sign on. I have verified database permissions for the database and user in the database.php file. Normal user logins, user creations etc work fine. 

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running -> 2.1.2
- What OS and web server you're running Snipe-IT on -> Centos 7 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) -> install.sh 
- If you're getting an error in your browser, include that error. -> no
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error -> login page
- If a stacktrace is provided in the error, include that too. -> no
- Any errors that appear in your browser's error console. -> none
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo) -> not able to test corporate LDAP with public demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. -> logs provide no more information than the debug output shown below.
- Include what you've done so far in the installation, and if you got any error messages along the way. -> no
- Indicate whether or not you've manually edited any data directly in the database -> no

![image](https://cloud.githubusercontent.com/assets/20210683/16461298/bdd1b262-3de0-11e6-92f0-6befd981c04d.png)

**Comment by snipe** [comment]
This is usually due to something wrong with the LDAP settings.

**Comment by shafmeister** [comment]
I figured that because it attempted to create the user the LDAP settings were correct. I will look into them further.

**Comment by IxFail** [comment]
Try the follow settings:
**LDAP Filter:** `cn=*`
**Username Field:** `samaccountname`
**Last Name:** `sn`
**LDAP Firstname:** `givenname`
**LDAP Authentication query:** `samaccountname=`

Let me hear if that works.

**Comment by shafmeister** [comment]
That did it, my manager was setting up the LDAP since I don't have access to our server but changing those settings resolved it.
