### ISSUE TITLE
Cannot find ENV file

### ISSUE THREAD

**Issue by twindaddy44** [snipe/snipe-it#2213]
#### Expected Behavior (or desired behavior if a feature request)

Following the installation instructions for V3 and it says there should be a single .env file in the root of the Snipe IT directory, but the only one I can find in there is docker.env and it doesn't look anything like the picture in the instructions. 

-----

#### Actual Behavior

I'm not sure the docker.env file is the configuration file I'm looking for but it's the only env file I see.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 3.0 beta 3
- What OS and web server you're running Snipe-IT on - Ubuntu Server 15.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error - Whoops, looks like something went wrong.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Just trying to go to the home page
- If a stacktrace is provided in the error, include that too. NA
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). No.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - I have no manually edited the database.

**Comment by jarbro** [comment]
What was the outcome of this?  I only see the docker.env file as well and I'm not running v3 under docker.

**Comment by mergimgj** [comment]
I'm having the same issue. Is Docker.env the file we want to edit?

**Comment by uberbrady** [comment]
First off, the `.env` file is normally invisible unless you use the `-a` argument to ls - e.g. `ls -al`. So that makes it hard to see unless you're careful.

Next off, you shouldn't need to edit that file directly. You should instead be supplying any environment parameters you need as part of the docker run command (usually as part of an `--env-file` option, or else your command-line will get really long).
