### ISSUE TITLE
Cookie expiration for Bootstrap Tables settings too short

### ISSUE THREAD

**Issue by ddreier** [snipe/snipe-it#2214]
#### Expected Behavior (or desired behavior if a feature request)

The cookie expiration for the column selection and search contents is effectively permanent.

---
#### Actual Behavior

The cookies expire after (I think) one hour. So I have to reset my column selection almost every time I use the system. Also, _some_ of the cookies contain the version number (not licenses). Which is slightly annoying because then the settings won't persist across version upgrades.

---
#### Please confirm you have done the following before posting your bug report:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running
  - v3, latest on the dev (v3) branch
- What OS and web server you're running Snipe-IT on
  - Windows Server 2012 R2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  - Manual
- If you're getting an error in your browser, include that error
  - N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
  - All assets page, RTD assets page, Deployed assets page, Pending assets page, Licences page, and probably the rest of the assets pages :).
- If a stacktrace is provided in the error, include that too.
  - N/A
- Any errors that appear in your browser's error console.
  - N/A
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
  - It is.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
  - N/A
- Include what you've done so far in the installation, and if you got any error messages along the way.
  - N/A
- Indicate whether or not you've manually edited any data directly in the database
  - Never have I ever.

**Comment by snipe** [comment]
We tacked on the version number because sometimes when we added/removed columns, the tables would display empty until the user cleared their cookies. It's an issue with bootstrap tables, unfortunately. 

I can increase the length of the cookie, but people complain either way. Too long, too short.

**Comment by ddreier** [comment]
People have complained about it being too long!? Jeez. So maybe it's a good candidate for being configurable?

I get where you're coming from on the version thing, and I can tolerate that. :P
