### ISSUE TITLE
How to add a Manufacturer?

### ISSUE THREAD

**Issue by pnelsonsr** [snipe/snipe-it#2215]
#### Expected Behavior (or desired behavior if a feature request)

ability to add a Manufacturer

-----

#### Actual Behavior

can not figure out how to add a Manufacturer

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running v3.0.0-dev-3
- What OS and web server you're running Snipe-IT on Fedora 23 and Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual
- If you're getting an error in your browser, include that error No error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error Create New asset model
- If a stacktrace is provided in the error, include that too. None
- Any errors that appear in your browser's error console. None
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database No

So it's not a bug, but I need to add new Manufacturer for our Asset Models.  I can not figure out how to do this.  I've look everywhere.  Please help!

**Comment by snipe** [comment]
Admin menu in the top right, click on Manufacturers.

**Comment by pnelsonsr** [comment]
Oh my thank you!  I added myself as a Super Admin and the Admin menu showed up!

**Comment by snipe** [comment]
![ant-man-dance](https://cloud.githubusercontent.com/assets/197404/16473508/a90a10f8-3e22-11e6-9ab4-8bf93f8163e6.gif)

**Comment by ajaydharwa** [comment]
Error in  Manufacturer creating in Snipr-IT

"Whoops, looks like something went wrong."

**Comment by johncave** [comment]
In 2019, this button is now in the left sidebar menu. Go to the single cog menu in the left sidebar and you will see options to add manufacturers, suppliers and similar. 

This design is not very obvious at all as a brand new user.
