### ISSUE TITLE
Feature Request: Licence vs Asset 

### ISSUE THREAD

**Issue by tahagg** [snipe/snipe-it#2216]
You have assets Licences and Accessories but they are not linked especially computers vs. licences must be linked 

You can categorize the assets like; Desktop, Laptop, Server

You can link asset to licence, accessories, users

You can add a barcode system so if anyone want easily print the barcode and it'll make very easy to track back

**Comment by snipe** [comment]
I don't understand what you're asking for here. Just to be able to check out licenses to assets?

**Comment by tahagg** [comment]
Yes firstly I believe it's better to assign licence to assets because whenever the asset gone or change the licence should be available to use again 

Second suggestion is categorizing the assets

Third one is link users with computers after that you will see who use which asset

Last suggestion is the barcode system

I'm really impressed with your quick answer, thank you for developing

**Comment by snipe** [comment]
> Yes firstly I believe it's better to assign licence to assets because whenever the asset gone or change the licence should be available to use again

Assigning licenses to assets is available in v3.

> Second suggestion is categorizing the assets

Categories for assets have existed for ages. Admin > Categories

> Third one is link users with computers after that you will see who use which asset

I don't understand. That's exactly what checking an asset out to a user does. Am I missing something?

> Last suggestion is the barcode system

Barcodes have been available since v1, and are improved in v3.

**Comment by tahagg** [comment]
Lol, I believe I should use long before suggest something
