### ISSUE TITLE
Using the CLI Installer

### ISSUE THREAD

**Issue by bagetsro** [snipe/snipe-it#2217]
i got stuck with the installation of snipe-it specifically on the 

Type "php artisan app:install --env=production" and follow the prompts

part on the cli installer. i have tried re-installing composer and even using different versions of it but i still get this error
![image](https://cloud.githubusercontent.com/assets/20238789/16515641/bebeb26c-3fa5-11e6-83c2-4409d26f92bf.png)

**Comment by snipe** [comment]
Can you show me the output when you run composer install?

**Comment by bagetsro** [comment]
im using the windows installer on windows 7. it just says install complete.

![image](https://cloud.githubusercontent.com/assets/20238789/16516000/db77b762-3fa7-11e6-8f65-7a79e571fe6d.png)

**Comment by snipe** [comment]
That's the installation for composer itself. You still need to run `composer install` to install the dependencies (which is why you installed composer in the first place)

**Comment by bagetsro** [comment]
![image](https://cloud.githubusercontent.com/assets/20238789/16516202/3df751bc-3fa9-11e6-9fe0-db26d779748b.png)

my php.ini
![image](https://cloud.githubusercontent.com/assets/20238789/16516226/689fb648-3fa9-11e6-9a2d-ed9655662b02.png)

**Comment by bagetsro** [comment]
still hoping for answers. :)

**Comment by dmeltzer** [comment]
Reading the composer install output makes it pretty clear that the curl and mbstring php extensions are missing from your install.

**Comment by bagetsro** [comment]
i was able to get passed that. forgot to comment out extensions from php.ini. i was able to install snipe-it. too bad im getting page cannot be displayed. :(

**Comment by bagetsro** [comment]
i was able to solve this by commenting out the extensions from the php.ini file. closing. thanks for the help guys. appreciate it. :)
