### ISSUE TITLE
[v3] Better failures when LDAP is donked

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#2218]
Right now, if your LDAP configuration is donked for some reason (firewall, bad credentials, etc), it fails pretty hard. We should handle that more gracefully, with useful error messages (like we do for importing LDAP users.)

**Comment by jayromems** [comment]
Not sure if you have another thread for this but one thing that weirds me out a bit is how the LDAP BIND Password shows in clear-text. Any thoughts on changing this?
