### ISSUE TITLE
Warrant expire alert through email or any other means

### ISSUE THREAD

**Issue by manusolano777** [snipe/snipe-it#2220]
#### 

Dear Mam,
Am a beginner to use SnipeIT Tool. It sooooo AWESOME. I like it very much.

My issue:
I set up my snipeit locally in my machine and Configured mail too. When a new USER ACCOUNT creates then it will send mail to my MAIL id.

I need to get notifications for WARRANTY EXPIRE, LICENCE EXPIRE etc.. 
1. How can i do that on windows 2008 R2 server  ?
2. I have already gone through your doc part and i have seen this command --->>> @daily /path/to/php /path/to/your/snipe-it/artisan alerts:expiring . I think this can be user in Linux environment(CRON).

Please try to help me how to configure the same in windows???PLEASE....

---

**Comment by snipe** [comment]
Hi there - thanks for the kind words!

The Windows equivalent of cron is scheduled tasks. This article (or one of our windows community users) should be able to help you: 
http://stackoverflow.com/questions/7195503/setting-up-a-cron-job-in-windows

**Comment by manusolano777** [comment]
Thanks for your comment. If you do'nt mind can u please help me to create the VBS script  for shedule the same

schtasks /create /tn "My App" /tr c:\apps\myapp.exe /sc daily /st 08:00

**Comment by snipe** [comment]
I don't know VBS, so can't help you there, but also not sure why you'd need to create a VBS script for this? Just un the `alerts:expiring` artisan task.

1. Make sure you logged on as an administrator or you have the same access as an administrator.
2. Start->Control Panel->System and Security->Administrative Tools->Task Scheduler
3. Action->Create Basic Task->Type a name and Click Next
4. Follow through the wizard.
