### ISSUE TITLE
Feature Request: Input Specifications of Asset.

### ISSUE THREAD

**Issue by jjangmoo** [snipe/snipe-it#2221]
Hello, 
I've started the SnipeIT v3 since a couple of weeks ago. 
This is a GREAT asset management software.

But, I think I need this feature.
When I check-out a PC to somebody, I need to know what specifications it has. (like CPU, memory, disks)
I want to find out these stuffs when I clicked an asset number. 

I made a code as below picture. 
![specification_view](https://cloud.githubusercontent.com/assets/4304132/16552669/d7aa7cac-41fd-11e6-952f-ef54a3e0530e.png)

I tried to make db tables and wrote codes. But it didn't work well.

**Comment by snipe** [comment]
You just need to create custom fields and populate that data. It doesn't show up in specifications, it shows up in the details tab.
