### ISSUE TITLE
How to install to a host

### ISSUE THREAD

**Issue by tahagg** [snipe/snipe-it#2223]
I'm trying to install to a windows server which is a hosting server I want to use this with a domain can I do that ?

Because I'm getting "D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory."

**Comment by snipe** [comment]
Just sounds like your document root is set wrong. Should be set to the public folder

**Comment by tahagg** [comment]
How can I do that ?

**Comment by jayromems** [comment]
Have a look here and see if this helps:

https://www.sitepoint.com/community/t/how-do-i-find-document-root/5231
