### ISSUE TITLE
LDAP Authentication

### ISSUE THREAD

**Issue by elJoeyJojo** [snipe/snipe-it#2224]
#### Expected Behavior (or desired behavior if a feature request)

I want to be able to login using my LDAP credentials

-----

#### Actual Behavior

I get a "The username or password is incorrect"

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode YES
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html) YES

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v2.1.1
- What OS and web server you're running Snipe-IT on - CentOS 6.8
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual Install but I did notice that there is no ldap.php file in the app/config/production folder as the manual installation did not mention anything in it? am I suppose to edit that? 
- If you're getting an error in your browser, include that error (When I enable debug mode, I only ever see my full app.php file at the top of the screen and I never seen any error, even in the browser with Developer Tools, maybe I'm doing it wrong)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Login Page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo) - I have not tried this yet
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. - I get this in my /storage logs 

[2016-07-06 16:54:40] production.DEBUG: Not logged in - admin-auth [] []
[2016-07-06 16:54:43] production.DEBUG: LDAP is enabled. [] []
[2016-07-06 16:54:43] production.DEBUG: Sentry lookup complete [] []
[2016-07-06 16:54:43] production.DEBUG: Local user domain\anthony.delarosa does not exist [] []
[2016-07-06 16:54:48] production.DEBUG: User did not authenticate correctly against LDAP. No local user was created. [] []
[2016-07-06 16:54:48] production.DEBUG: Authenticating user against database. [] []
[2016-07-06 16:54:48] production.DEBUG: Local authentication: User domain\anthony.delarosa not found [] []

- Include what you've done so far in the installation, and if you got any error messages along the way - I have tried 2 different LDAP accounts to authenticate. This is my settings in LDAP Settings in Snipe It within the Web. I have also made sure php56w-ldap is installed on my CentOS 6.8 Server

LDAP Integration  LDAP enabled
LDAP Server ldap://servername.domain.com

LDAP Bind Username admin@domain.com
LDAP Bind Password password
Base Bind DN ou=location,cn=domain,cn=com
LDAP Filter cn=*
Username Field samaccountname
Last Name sn
LDAP First Name givenname 
LDAP Authentication query samaccountname=
LDAP Version 3
LDAP Email admin@domain.com

- Indicate whether or not you've manually edited any data directly in the database - No I have not

**Comment by IxFail** [comment]
Try the follow settings:
**LDAP Filter:** `cn=*`
**Username Field:** `samaccountname`
**Last Name:** `sn`
**LDAP Firstname:** `givenname`
**LDAP Authentication query:** `samaccountname=`

Let me hear if that works.

**Comment by IxFail** [comment]
Try logging in without domain/ infront of it, just the username

**Comment by elJoeyJojo** [comment]
I have tried with both domain\username and just username. No luck

**Comment by IxFail** [comment]
In the LDAP settings change the **LDAP Bind Username** to only the username

**Comment by abinkoshy** [comment]
Try using the full DN for the LDAP Bind Username
ex:  CN=admin,OU=Location,DC=domain,DC=com

Also, under LDAP Email, you want to enter "mail" instead of "admin@domain.com" because it's looking for the field to pull the email address from AD.

Mine actually kept giving me the "User did not authenticate correctly against LDAP" error after the bind finally worked.  But that was because in the LDAP Authentication query I was using the wrong thing.  It looks like yours is correct assuming you're using Active Directory.

**Comment by elJoeyJojo** [comment]
so the issue was TOTALLY MY FAULT! user error: I had 

Base Bind DN ou=location,cn=domain,cn=com

and it's

Base Bind DN OU=location,DC=domain,DC=com

**Comment by elJoeyJojo** [comment]
Thanks for you all your help though! Now I got another issue but I will open a different ticket for that!
