### ISSUE TITLE
create asset goes to 500 error

### ISSUE THREAD

**Issue by kt1024** [snipe/snipe-it#2225]
#### Expected Behavior (or desired behavior if a feature request)

asset can be created

#### Actual Behavior

error 500. 
it was ok before , and suddenly goes wrong.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
 * 2.1.0-55
- What OS and web server you're running Snipe-IT on
 * ubuntu 14.04 LTS
- If you're getting an error in your browser, include that error
 * chrome 51
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
 * /hardware/create
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
![image](https://cloud.githubusercontent.com/assets/12657496/16640696/de7851c2-442c-11e6-9f88-699d130eeaee.png)

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
<code><pre>
snip-it@asset:/var/www/snipeit/app/storage/logs$ cat log-apache2handler-2016-07-07.txt
[2016-07-07 10:13:01] production.ERROR: exception 'ErrorException' with message 'Argument 1 passed to Illuminate\Database\Eloquent\Relations\BelongsTo::associate() must be an instance of Illuminate\Database\Eloquent\Model, null given, called in /var/www/snipeit/app/controllers/admin/AssetsController.php on line 104 and defined' in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php:203
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/BelongsTo.php(203): Illuminate\Exception\Handler->handleError(4096, 'Argument 1 pass...', '/var/www/snipei...', 203, Array)
#1 /var/www/snipeit/app/controllers/admin/AssetsController.php(104): Illuminate\Database\Eloquent\Relations\BelongsTo->associate(NULL)
#2 [internal function]: Controllers\Admin\AssetsController->postCreate()
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postCreate', Array)
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\AssetsController), Object(Illuminate\Routing\Route), 'postCreate')
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'postCreate')
#7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/snipeit/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#19 /var/www/snipeit/public/index.php(49): Illuminate\Foundation\Application->run()
#20 {main} [] []
</pre></code>
- Indicate whether or not you've manually edited any data directly in the database
 * no,

**Comment by cduverne** [comment]
Hi,

Could you add a screenshot of your "Create asset" page ?
It looks like you're not filling the "model" field.

**Comment by kt1024** [comment]
@cduverne model field is mandatory. it can't be missed.
![2016-07-07_182346](https://cloud.githubusercontent.com/assets/12657496/16650513/15c7d884-4471-11e6-80d4-6f544740d2ce.png)

**Comment by snipe** [comment]
> it was ok before , and suddenly goes wrong.

What exactly does that mean? Did you update to a later version or something? We obviously didn't change anything on your system.

**Comment by davideveritt** [comment]
We actually just had the same thing happen. The system was not changed at all.

**Comment by snipe** [comment]
@davideveritt and you can see that we have no control at all over your install, right? So that makes me think there must be a data bug. If the code hasn't changed, the data has. So any info you can give me on your DB tables, etc would be really helpful. It's entirely likely that you've both found a bug that only manifests during certain, specific circumstances, so anything you can tell me about changes you've made to your models and/or throw me some DB output, would be really helpful.

**Comment by davideveritt** [comment]
How can I collect DB output? (Sorry not a DB guru) We didn't change any models but we did add and remove some status labels. We also added some custom fields, which after a little more poking around seem to be the problem. We can create assets of model types that don't contain custom fields but get the 500 error when creating assets of model types that do contain custom fields. Assets that were previously created with model types that contain custom fields are still editable. Hopefully that's coherent. Please let me know what other info you might need.

**Comment by snipe** [comment]
@davideveritt that's definitely useful debugging info, thank you. You're both running an older version of Snipe-IT (v3-beta is latest, and we haven't made any changes at all to v2.x in many months), so I have to assume that data got donked somewhere. That's still on us, since our UI shouldn't allow you to donk up your data like that, but it's obviously hard to track it down when its data versus code. 

Create asset shouldn't care about models other than to grab them and return a list.

Can you check your database and see if you have any assets that don't have a model ID int he assets table? Something has clearly gone wrong here. Maybe some asset models got deleted? I'm not sure.

**Comment by davideveritt** [comment]
Would an upgrade to the beta fix this issue? It looks like all assets have the model and ID fields populated. We restored a couple deleted models (had no assets assigned to them) and it had no affect.

**Comment by snipe** [comment]
Honestly, without knowing what's broken, I have no way of knowing whether it would help :( We do tend to have better controls over deleting important shit in v3, but if its already deleted, it may not solve your issue. 

Do you know enough SQL to query the database to see if there are any assets that have model_id s that are null or point to asset models that were deleted or that don't exist at all?

**Comment by kt1024** [comment]
last action is delete a asset.
![image](https://cloud.githubusercontent.com/assets/12657496/16675044/3ccc8a72-44f0-11e6-8adb-fb5851c12285.png)

**Comment by kt1024** [comment]
@snipe what db output you need? I did not update snip it after install.

**Comment by snipe** [comment]
@kt1024 Can you check your database and see if you have any assets that don't have a model ID set in the assets table, or that point to model IDs for models that have been deleted?

**Comment by kt1024** [comment]
@snipe ,no empty model id.
<code><pre>
mysql> SELECT id, model_id FROM assets;
+-----+----------+
| id  | model_id |
+-----+----------+
|   1 |        9 |
|   2 |        8 |
|   3 |        6 |
|   4 |        6 |
|   5 |        6 |
|   6 |        6 |
|   7 |        6 |
|   8 |        6 |
|   9 |        6 |
|  10 |        6 |
|  11 |        6 |
|  12 |        6 |
|  13 |        6 |
|  14 |        6 |
|  15 |        6 |
|  16 |        6 |
|  17 |        6 |
|  18 |        6 |
|  19 |        6 |
|  20 |        6 |
|  21 |        6 |
|  22 |        6 |
|  23 |        6 |
|  24 |        6 |
|  25 |        6 |
|  26 |        6 |
|  27 |        6 |
|  28 |        6 |
|  29 |        6 |
|  30 |        6 |
|  31 |        6 |
|  32 |        6 |
|  33 |        6 |
|  34 |        6 |
|  35 |        6 |
|  36 |        6 |
|  37 |        6 |
|  38 |        6 |
|  39 |        6 |
|  40 |        6 |
|  41 |        6 |
|  42 |        6 |
|  43 |        6 |
|  44 |        6 |
|  45 |        6 |
|  46 |        6 |
|  47 |        6 |
|  48 |        6 |
|  49 |        6 |
|  50 |        6 |
|  51 |        6 |
|  52 |        6 |
|  53 |        6 |
|  54 |        6 |
|  55 |        6 |
|  56 |        6 |
|  57 |        6 |
|  58 |        6 |
|  59 |        6 |
|  60 |        6 |
|  61 |        6 |
|  62 |        6 |
|  63 |        6 |
|  64 |        6 |
|  65 |        6 |
|  66 |        6 |
|  67 |        6 |
|  68 |        6 |
|  69 |        6 |
|  70 |        6 |
|  71 |        6 |
|  72 |        6 |
|  73 |        6 |
|  74 |        6 |
|  75 |        6 |
|  76 |        6 |
|  77 |        6 |
|  78 |        6 |
|  79 |        6 |
|  80 |        6 |
|  81 |        6 |
|  82 |        6 |
|  83 |        6 |
|  84 |        6 |
|  85 |        6 |
|  86 |        6 |
|  87 |        6 |
|  88 |        6 |
|  89 |        6 |
|  90 |        6 |
|  91 |        6 |
|  92 |        6 |
|  93 |        6 |
|  94 |        6 |
|  95 |        6 |
|  96 |        6 |
|  97 |        6 |
|  98 |        6 |
|  99 |        6 |
| 100 |        6 |
| 101 |        6 |
| 102 |        6 |
| 103 |        6 |
| 104 |        6 |
| 105 |        6 |
| 106 |        6 |
| 107 |        6 |
| 108 |        6 |
| 109 |        6 |
| 110 |        6 |
| 111 |        6 |
| 112 |        6 |
| 113 |        6 |
| 114 |        6 |
| 115 |        6 |
| 116 |        6 |
| 117 |        6 |
| 118 |        6 |
| 119 |        6 |
| 120 |        6 |
| 121 |        6 |
| 122 |        6 |
| 123 |        6 |
| 124 |        6 |
| 125 |        6 |
| 126 |        6 |
| 127 |        6 |
| 128 |        6 |
| 129 |        6 |
| 130 |        6 |
| 131 |        6 |
| 132 |        6 |
| 133 |        6 |
| 134 |        6 |
| 135 |        6 |
| 136 |        6 |
| 137 |        6 |
| 138 |        6 |
| 139 |        6 |
| 140 |        6 |
| 141 |        6 |
| 142 |        6 |
| 143 |        6 |
| 144 |        6 |
| 145 |        6 |
| 146 |        6 |
| 147 |        6 |
| 148 |        6 |
| 149 |        6 |
| 150 |        6 |
| 151 |        6 |
| 152 |        6 |
| 153 |        6 |
| 154 |        6 |
| 155 |        6 |
| 156 |        6 |
| 157 |        6 |
| 158 |        6 |
| 159 |        6 |
| 160 |        6 |
| 161 |        6 |
| 162 |        6 |
| 163 |        6 |
| 164 |        6 |
| 165 |        6 |
| 166 |        6 |
| 167 |        6 |
| 168 |        6 |
| 169 |        6 |
| 170 |        6 |
| 171 |        6 |
| 172 |        6 |
| 173 |        6 |
| 174 |        6 |
| 175 |        6 |
| 176 |        6 |
| 177 |        6 |
| 178 |        6 |
| 179 |        6 |
| 180 |        6 |
| 181 |        6 |
| 182 |        6 |
| 183 |        6 |
| 184 |        6 |
| 185 |        6 |
| 186 |        6 |
| 187 |        6 |
| 188 |        6 |
| 189 |        6 |
| 190 |        6 |
| 191 |        6 |
| 192 |        6 |
| 193 |        6 |
| 194 |        6 |
| 195 |        6 |
| 196 |        6 |
| 197 |        6 |
| 198 |        6 |
| 199 |        6 |
| 200 |        6 |
| 201 |        6 |
| 202 |        6 |
| 203 |        6 |
| 204 |        6 |
| 205 |        6 |
| 206 |        6 |
| 207 |        6 |
| 208 |        6 |
| 209 |        6 |
| 210 |        6 |
| 211 |        6 |
| 212 |        6 |
| 213 |        6 |
| 214 |        6 |
| 215 |        6 |
| 216 |        6 |
| 217 |        6 |
| 218 |        6 |
| 219 |        6 |
| 220 |        6 |
| 221 |        6 |
| 222 |        6 |
| 223 |        6 |
| 224 |        6 |
| 225 |        6 |
| 226 |        6 |
| 227 |        6 |
| 228 |        6 |
| 229 |        6 |
| 230 |        6 |
| 231 |        6 |
| 232 |        6 |
| 233 |        6 |
| 234 |        6 |
| 235 |        6 |
| 236 |        6 |
| 237 |        6 |
| 238 |        6 |
| 239 |        6 |
| 240 |        6 |
| 241 |        6 |
| 242 |        6 |
| 243 |        6 |
| 244 |        6 |
| 245 |        6 |
| 246 |        6 |
| 247 |        6 |
| 248 |        6 |
| 249 |        6 |
| 250 |        6 |
| 251 |        6 |
| 252 |        6 |
| 253 |        6 |
| 254 |        6 |
| 255 |        6 |
| 256 |        6 |
| 257 |        6 |
| 258 |        6 |
| 259 |        6 |
| 260 |        6 |
| 261 |        6 |
| 262 |        6 |
| 263 |        6 |
| 264 |        6 |
| 265 |        6 |
| 266 |        6 |
| 267 |        6 |
| 268 |        6 |
| 269 |        6 |
| 270 |        6 |
| 271 |        6 |
| 272 |        6 |
| 273 |        6 |
| 274 |        6 |
| 275 |        6 |
| 276 |        6 |
| 277 |        6 |
| 278 |        6 |
| 279 |        6 |
| 280 |        6 |
| 281 |        6 |
| 282 |        6 |
| 283 |        6 |
| 284 |        6 |
| 285 |        6 |
| 286 |        6 |
| 287 |        6 |
| 288 |       18 |
| 289 |        5 |
| 290 |       17 |
| 291 |       17 |
| 292 |       11 |
| 293 |       11 |
| 294 |       12 |
| 295 |       10 |
| 296 |       13 |
| 297 |       15 |
| 298 |       20 |
| 299 |        6 |
| 300 |        6 |
| 301 |        6 |
| 302 |        7 |
| 303 |        7 |
| 304 |        7 |
| 305 |        7 |
| 306 |        7 |
| 307 |        7 |
| 308 |       25 |
| 309 |       25 |
| 310 |        7 |
| 311 |        7 |
| 312 |       24 |
| 313 |       24 |
| 314 |       24 |
+-----+----------+
314 rows in set (0.00 sec)
</pre></code>

**Comment by snipe** [comment]
Okay, are any of your asset models marked as deleted in the DB? And if so, do any of the assets in your assets tables refer to them as their model_id?

**Comment by davideveritt** [comment]
@snipe no empty model id here as well. How would I check to see if an asset model has been marked as deleted in the DB?

**Comment by kt1024** [comment]
@snipe model id 19 is deleted, but no assets associate with it.
<code><pre>
mysql> select id, updated_at, deleted_at from models;
+----+---------------------+---------------------+
| id | updated_at          | deleted_at          |
+----+---------------------+---------------------+
|  1 | 2016-05-10 15:11:54 | NULL                |
|  2 | 2016-05-10 15:12:02 | NULL                |
|  3 | 2016-05-10 15:12:09 | NULL                |
|  4 | 2016-05-10 15:12:15 | NULL                |
|  5 | 2016-05-10 15:11:42 | NULL                |
|  6 | 2016-05-10 16:05:33 | NULL                |
|  7 | 2016-05-10 16:08:59 | NULL                |
|  8 | 2016-05-10 16:08:49 | NULL                |
|  9 | 2016-05-10 16:09:24 | NULL                |
| 10 | 2016-05-10 16:10:36 | NULL                |
| 11 | 2016-05-10 16:11:27 | NULL                |
| 12 | 2016-05-10 16:11:51 | NULL                |
| 13 | 2016-05-10 16:12:16 | NULL                |
| 14 | 2016-05-10 16:12:45 | NULL                |
| 15 | 2016-05-10 16:13:11 | NULL                |
| 16 | 2016-05-10 16:13:40 | NULL                |
| 17 | 2016-05-10 16:14:03 | NULL                |
| 18 | 2016-05-19 18:19:25 | NULL                |
| 19 | 2016-05-19 18:19:30 | 2016-05-19 18:19:30 |
| 20 | 2016-05-27 17:56:11 | NULL                |
| 21 | 2016-05-30 18:00:08 | NULL                |
| 22 | 2016-05-30 18:00:38 | NULL                |
| 23 | 2016-05-30 18:00:54 | NULL                |
| 24 | 2016-06-01 09:35:56 | NULL                |
| 25 | 2016-06-07 11:03:06 | NULL                |
| 26 | 2016-06-30 11:32:10 | NULL                |
| 27 | 2016-06-30 11:31:51 | NULL                |
| 28 | 2016-06-30 11:33:10 | NULL                |
+----+---------------------+---------------------+
28 rows in set (0.00 sec)
</pre></code>

**Comment by davideveritt** [comment]
We had no deleted model id's.

**Comment by davideveritt** [comment]
Any luck finding a solution to this problem?

**Comment by kt1024** [comment]
different error today:
<code><pre>
ken@asset:/var/www/snipeit/app/storage/logs$ cat log-apache2handler-2016-07-15.txt
[2016-07-15 16:30:17] production.ERROR: exception 'ErrorException' with message 'Undefined index: fields' in /var/www/snipeit/app/controllers/admin/AssetsController.php:113
Stack trace:
#0 /var/www/snipeit/app/controllers/admin/AssetsController.php(113): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', '/var/www/snipei...', 113, Array)
#1 [internal function]: Controllers\Admin\AssetsController->postCreate()
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('postCreate', Array)
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\Admin\AssetsController), Object(Illuminate\Routing\Route), 'postCreate')
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\Adm...', 'postCreate')
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109): call_user_func_array(Object(Closure), Array)
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/snipeit/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/snipeit/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /var/www/snipeit/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []
</pre></code>

![2016-07-15_163113](https://cloud.githubusercontent.com/assets/12657496/16868731/d572bc04-4aab-11e6-836b-896cd62bdab7.png)

**Comment by snipe** [comment]
Normally when we see that undefined index fields error, it's because the app_url doesn't exactly match the URL you're actually accessing the site from. What's listed as your app url?

**Comment by kt1024** [comment]
@snipe , I've change 'url' in app.php from http:// to http**s**:// , assets can be created now.
many thanks.
