### ISSUE TITLE
New Install: Page cannot be displayed

### ISSUE THREAD

**Issue by bagetsro** [snipe/snipe-it#2226]
i believe i followed the installation instructions completely. i also removed the first rule imported using url rewrite. i made sure all permission access to folders was granted. i am not behind any firewall. installing on windows 7 32 bit professional on a virtual machine. Getting Page cannot be displayed.

**Comment by cduverne** [comment]
Which page ? The login one ?  

Which version are you running ?  

How did you install ?  

The issue template is pretty good to allow us getting all the information needed to better help you, please use it.

**Comment by bagetsro** [comment]
snipe it 2.1.2 running on iis 7. the main page or login page is not loading. or those 2 are different pages?
i installed following this guide for windows. http://docs.snipeitapp.com/installation/configuration.html

![image](https://cloud.githubusercontent.com/assets/20238789/16647324/4b02175e-4461-11e6-9d2c-e08ac2dcd880.png)

**Comment by BrettFagerlund** [comment]
open up that command prompt and try ping fpigcassets.local, make sure it resolves. Otherwise add entry into windows hosts file to point at 127.0.0.1

**Comment by BrettFagerlund** [comment]
127.0.0.1 if local, otherwise ip of server you configured snipe-IT on

**Comment by bagetsro** [comment]
this is where i configured snipe it on.

![image](https://cloud.githubusercontent.com/assets/20238789/16648000/7ca03ebe-4464-11e6-994b-a8b1ecad27d7.png)

**Comment by bagetsro** [comment]
ooooops sorry. forgot to put fpigcassets.local on the 127.0.0.1. i was able to see the login page. would you know what default credentials i can use? :)

![image](https://cloud.githubusercontent.com/assets/20238789/16648081/da7519ce-4464-11e6-87cc-dc4342050061.png)

**Comment by cduverne** [comment]
Normally the one you setup during the setup of the DB :)
You defined a username and a password.



2016-07-07 11:04 GMT+02:00 bagetsro <notifications@github.com>:

> ooooops sorry. forgot to put fpigcassets.local on the 127.0.0.1. i was
> able to see the login page. would you know what default credentials i can
> use? :)
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/20238789/16648081/da7519ce-4464-11e6-87cc-dc4342050061.png>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/snipe/snipe-it/issues/2226#issuecomment-231023315>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABZAZIQJFOt0CNegR87TKSeiizExPSczks5qTMEjgaJpZM4JG0qF>
> .
>

-- 
♻ Be green, keep it on the screen

**Comment by bagetsro** [comment]
whoah! finally its working! thanks a bunch guys! appreciate it!

![image](https://cloud.githubusercontent.com/assets/20238789/16648237/9fe2b9b4-4465-11e6-8532-f8c4ef2c1b2d.png)
