### ISSUE TITLE
V3 - after composer install

### ISSUE THREAD

**Issue by philknab** [snipe/snipe-it#2227]
Hi,

i installed the composer.phar file and now i want to install snipeit.
After php artisan app:install it shows:

root@snipeIT:/var/www/SnipeIT# php artisan app:install --env=production
  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "app:install" is not defined.
  Did you mean one of these?
      migrate:install
      app:name

I am running it on our linux webserver.
Before i installed version 2.1 local on xampp and it worked, now i did the same and the error above keeps showing.

If i write down the IP address of the server it keeps showing the default apache site.

Greets, Phil

**Comment by snipe** [comment]
What version are you trying to install?

**Comment by philknab** [comment]
3.0 beta 3

**Comment by snipe** [comment]
There is no app:install script for v3. https://snipe-it.readme.io

**Comment by snipe** [comment]
If you need to upgrade, follow these directions: 
https://snipe-it.readme.io/docs/upgrading

**Comment by philknab** [comment]
so i need version 2.1 installed and then upgrade to 3.0?

**Comment by snipe** [comment]
Only if you want to upgrade your existing install. Otherwise just follow the installation instructions. https://snipe-it.readme.io/docs/getting-started

**Comment by philknab** [comment]
In a standard Apache virtualhost setup, that might look something like this:
Virtualhost in Linux Apache

<VirtualHost *:80>
  <Directory /var/www/html/public>
    Allow From All
    AllowOverride All
    Options +Indexes
  </Directory>

  DocumentRoot /var/www/html/public
  ServerName www.yourserver.com
  # Other directives here
</VirtualHost>

where do i find this? i am only doing an internship at a company and i am not in touch with linux :(

**Comment by snipe** [comment]
It's typically in your httpd.conf, but you should be careful if there are other things hosted on that server. You could cock up the rest of the sites running there if you make a mistake.

**Comment by philknab** [comment]
yeah i know, they've set up a server only for snipeit. my task is to install it and test it on the server. it's only reachable in the IT network, so only for us guys in the IT. i only need to set the document root to public then it should work right?

**Comment by snipe** [comment]
Assuming all of the other settings are correct, yes.

**Comment by philknab** [comment]
well i can't find the httpd.conf file

**Comment by philknab** [comment]
i found a apache2.conf file - is it the same?

**Comment by snipe** [comment]
http://stackoverflow.com/questions/12202021/where-is-my-httpd-conf-file-located-apache

Configuring your web server is a little outside the scope of Snipe-IT Support. We'll try to help where we can, but you should try to do a little googling as well.

**Comment by philknab** [comment]
i googled every page i guess haha

**Comment by philknab** [comment]
in apache2 it's not called httpd.conf, so in the apache2 folder there are several .conf files and i found the right one, so now it should work - thank you :)

**Comment by DawnTan0321** [comment]
I put up snipeit v3.6.2 by docker. Now I want to upgrade to v3.6.4.
After I execute "php composer.phar install --no-dev --prefer-source",it pops up"Could not open input file: composer.phar"
![screenshot from 2017-03-09 17 49 13](https://cloud.githubusercontent.com/assets/25975267/23744876/f2b13f16-04f0-11e7-8e39-d19948562db7.png)

**Comment by DawnTan0321** [comment]
It seems the timezone is wrong
![screenshot from 2017-03-09 17 57 08](https://cloud.githubusercontent.com/assets/25975267/23745137/1332876c-04f2-11e7-983e-c747ca790cad.png)
