### ISSUE TITLE
You do not have permission to view this page. When logged in

### ISSUE THREAD

**Issue by lloydie-t** [snipe/snipe-it#2228]
#### Expected Behavior (or desired behavior if a feature request)

No login errors when using correct credentials

-----

#### Actual Behavior

The following appears in red when you log in as non-admin
You do not have permission to view this page.

-----

#### Please confirm you have done the following before posting your bug report:

Running debug mode
Not a common issue. Did not happen in previous version

-----
#### Please provide answers to these questions before posting your bug report:

- Version v2.1.0-55
- Centos 6
- (install.sh
- No Browser error
- /account/view-assets
- If a stacktrace is provided in the error, include that too.
- No errors in console
- https://snipeitapp.com/demo reproduced using created basic user
-
[2016-07-07 16:18:30] production.DEBUG: Local user johnny.joku exists in database. Authenticating existing user against LDAP. [] []
[2016-07-07 16:18:30] production.DEBUG: User did not authenticate correctly against LDAP. Local user was not updated. [] []
[2016-07-07 16:18:30] production.DEBUG: Authenticating user against database. [] []
[2016-07-07 16:18:30] production.DEBUG: Not a super admin [] []
[2016-07-07 16:39:19] production.DEBUG: Not a super admin [] []

The Database has not been manually edited.

**Comment by snipe** [comment]
Can you show me the permissions of the user you're logging in as?

**Comment by lloydie-t** [comment]
logged in as medical.user on demo site. I am unable to select user group for some reason.
![snipeit user](https://cloud.githubusercontent.com/assets/5909314/16660314/ae7f8402-4465-11e6-991c-05d99d1ea1f4.PNG)

**Comment by snipe** [comment]
I don't need to see what's on the demo site, I need to see what's on your site. My guess would be that you didn't assign the user to any group that has permissions to do anything.

**Comment by lloydie-t** [comment]
The user is assigned to the default 'Users' group.

**Comment by snipe** [comment]
Not sure what could be wrong here. 2.1.x has been stable and in production for quite some time. Unless you can narrow it down a little, I'm not sure we're going to dig too deep into this, since v3 is just about our and the auth/perms stuff was completely rewritten in v3.

**Comment by lloydie-t** [comment]
Oh OK. I will see if I can fix it then. BTW if you refresh the page the error goes away, but going to the home page returns the error.

**Comment by lloydie-t** [comment]
And if you enter the go put the '/account/view-asset' in the url and then enter username + password the error does not appear. Seems like some weird redirect problem to me.

**Comment by alomanto** [comment]
If it's worth anything, I'm having the same issue and came here to pose the same question. If you happen to figure out what's wrong, feel free to post back here and let me know if you find it. It's not really hurting anything, but a brand new user in the users group shouldn't be seeing an error like that, I think.

**Comment by lloydie-t** [comment]
Fairly sure these errors are related to changes made in filters.php.
I would be inclined to change line 91
from
```php
return Redirect::route('view-assets')->with('error','You do not have permission to view this page.');
```
to
```php
return Redirect::route('view-assets');
```

**Comment by snipe** [comment]
We're not going to be patching 2.1.x for anything other than security issues. v3 is our main focus.
