### ISSUE TITLE
[v3] Creating a new asset with Custom Field, the custom field is empty upon submit

### ISSUE THREAD

**Issue by chrisrbmn** [snipe/snipe-it#2230]
#### Expected Behavior (or desired behavior if a feature request)

I have a custom field to input the express service tag on Dell laptops when selected. on v2, I could enter the code in this field, and it saved successfully. On previously created systems, the express code shows correctly.

---
#### Actual Behavior

when I enter data in the field now, and save, the field displays empty.

---
#### Please confirm you have done the following before posting your bug report:
- [Y] I have enabled debug mode
- [Y] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running v3.0.0-dev-3
- What OS and web server you're running Snipe-IT on CentOS 6.7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) 
  Manual
- If you're getting an error in your browser, include that error 
  none
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. no
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
  nothing indicated in laravel.log
- Include what you've done so far in the installation, and if you got any error messages along the way. none
  upgrade from version 2.1.2
- Indicate whether or not you've manually edited any data directly in the database
  no

**Comment by snipe** [comment]
Is this reproducible on the v3 demo?

**Comment by chrisrbmn** [comment]
no, it saves correctly in the demo.

**Comment by chrisrbmn** [comment]
Additionally, on my upgraded instance: if I create a new custom field, and attach it to the existing fieldset, and assign it to a model, it is blank if I save the asset with data in the field.

If I create an entirely new field, and assign it to a entirely new fieldset, and assign it to a model, still no love.

**Comment by snipe** [comment]
Is there anything in your logs? Without being able to reproduce this, I'm not sure where to start.

**Comment by chrisrbmn** [comment]
I'm not seeing anything in the laravel.log.
I'm looking in the sql "Assets" table and its not adding the data there.
I did perform an upgrade as opposed to a new install, if that helps at all.

**Comment by chrisrbmn** [comment]
if I manually added the data to the mysql field, it shows correctly on the page.

**Comment by chrisrbmn** [comment]
its almost like there is no insert/update query tied to the field.

Has anyone else performed an in-place upgrade from version 2.1.2 to v3.0.0-dev-3 that had custom  fields, and tried using custom fields after upgrading?

**Comment by chrisrbmn** [comment]
here is the output from the laravel.log
`[2016-07-11 00:00:01] production.ERROR: exception 'Symfony\Component\Console\Exception\CommandNotFoundException' with message 'There are no commands defined in the "alerts" namespace.' in /var/www/snipeit/vendor/symfony/console/Application.php:466
Stack trace:
#0 /var/www/snipeit/vendor/symfony/console/Application.php(498): Symfony\Component\Console\Application->findNamespace('alerts')
#1 /var/www/snipeit/vendor/symfony/console/Application.php(183): Symfony\Component\Console\Application->find('alerts:expiring')
#2 /var/www/snipeit/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/snipeit/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main}  `


here's what I have in the access.log
`10.0.4.225 - - [11/Jul/2016:09:35:12 -0500] "GET /favicon.ico HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:36:56 -0500] "GET /hardware HTTP/1.1" 200 54686
10.0.4.225 - - [11/Jul/2016:09:36:57 -0500] "GET /assets/js/bootstrap-table.js HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:36:57 -0500] "GET /assets/js/extensions/cookie/bootstrap-table-cookie.js HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:36:57 -0500] "GET /assets/js/extensions/mobile/bootstrap-table-mobile.js HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:36:57 -0500] "GET /assets/js/extensions/export/bootstrap-table-export.js HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:36:57 -0500] "GET /assets/js/extensions/export/tableExport.js HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:36:57 -0500] "GET /assets/js/extensions/export/jquery.base64.js HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:36:57 -0500] "GET /assets/js/extensions/multiple-sort/bootstrap-table-multiple-sort.js HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:36:57 -0500] "GET /uploads/logo.png HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:36:57 -0500] "GET /api/hardware/list?order_number=&order=asc&limit=100&offset=0 HTTP/1.1" 200 169482
10.0.4.225 - - [11/Jul/2016:09:37:05 -0500] "GET /hardware/76/view HTTP/1.1" 200 83834
10.0.4.225 - - [11/Jul/2016:09:37:05 -0500] "GET /hardware/76/qr_code HTTP/1.1" 200 369
10.0.4.225 - - [11/Jul/2016:09:37:12 -0500] "GET /hardware/76/edit HTTP/1.1" 200 93658
10.0.4.225 - - [11/Jul/2016:09:37:14 -0500] "GET /api/statuslabels/8/deployable HTTP/1.1" 200 1
10.0.4.225 - - [11/Jul/2016:09:37:14 -0500] "GET /_debugbar/open?op=get&id=228472b5902df04f48b05d669dd88ae4 HTTP/1.1" 200 15509
10.0.4.225 - - [11/Jul/2016:09:37:19 -0500] "POST /hardware/76/edit HTTP/1.1" 302 440
10.0.4.225 - - [11/Jul/2016:09:37:19 -0500] "GET /hardware/76/view HTTP/1.1" 200 39679
10.0.4.225 - - [11/Jul/2016:09:37:19 -0500] "GET /hardware/76/edit HTTP/1.1" 200 112000
10.0.4.225 - - [11/Jul/2016:09:37:20 -0500] "GET /assets/css/bootstrap.min.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:37:20 -0500] "GET /assets/js/plugins/select2/select2.min.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:37:20 -0500] "GET /assets/css/font-awesome.min.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:37:20 -0500] "GET /assets/js/plugins/datepicker/bootstrap-datepicker.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:37:20 -0500] "GET /assets/js/plugins/iCheck/all.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:37:20 -0500] "GET /assets/css/skins/skin-blue.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:37:20 -0500] "GET /assets/css/bootstrap-table.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:37:20 -0500] "GET /build/assets/js/all-edd914620a.js HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:37:20 -0500] "GET /build/assets/css/app-ec8e97e7ca.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:37:20 -0500] "GET /assets/js/plugins/iCheck/minimal/_all.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:37:20 -0500] "GET /assets/js/plugins/iCheck/square/_all.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:37:20 -0500] "GET /assets/js/plugins/iCheck/flat/_all.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:37:20 -0500] "GET /assets/js/plugins/iCheck/line/_all.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:37:20 -0500] "GET /assets/js/plugins/iCheck/futurico/futurico.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:37:20 -0500] "GET /assets/js/plugins/iCheck/polaris/polaris.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:37:20 -0500] "GET /_debugbar/assets/stylesheets?v=1464964278 HTTP/1.1" 200 197381
10.0.4.225 - - [11/Jul/2016:09:37:20 -0500] "GET /_debugbar/assets/javascript?v=1464964275 HTTP/1.1" 200 348915
10.0.4.225 - - [11/Jul/2016:09:37:20 -0500] "GET /uploads/logo.png HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:37:20 -0500] "GET /assets/js/plugins/iCheck/minimal/blue.png HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:37:20 -0500] "GET /api/statuslabels/8/deployable HTTP/1.1" 200 1
10.0.4.225 - - [11/Jul/2016:09:37:21 -0500] "GET /_debugbar/open?op=get&id=d191c1cf0e5c9f44d16fe38855d69eb0 HTTP/1.1" 200 15599
10.0.4.225 - - [11/Jul/2016:09:50:48 -0500] "GET /build/assets/css/app.css.map HTTP/1.1" 200 309441
10.0.4.225 - - [11/Jul/2016:09:57:41 -0500] "GET /hardware/76/edit HTTP/1.1" 200 93833
10.0.4.225 - - [11/Jul/2016:09:57:42 -0500] "GET /assets/css/bootstrap.min.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:57:42 -0500] "GET /build/assets/css/app-ec8e97e7ca.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:57:42 -0500] "GET /assets/css/font-awesome.min.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:57:42 -0500] "GET /assets/js/plugins/select2/select2.min.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:57:42 -0500] "GET /assets/js/plugins/datepicker/bootstrap-datepicker.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:57:42 -0500] "GET /assets/js/plugins/iCheck/all.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:57:42 -0500] "GET /assets/css/bootstrap-table.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:57:42 -0500] "GET /build/assets/js/all-edd914620a.js HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:57:42 -0500] "GET /assets/css/skins/skin-blue.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:57:42 -0500] "GET /assets/js/plugins/iCheck/minimal/_all.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:57:42 -0500] "GET /assets/js/plugins/iCheck/square/_all.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:57:42 -0500] "GET /assets/js/plugins/iCheck/flat/_all.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:57:42 -0500] "GET /assets/js/plugins/iCheck/line/_all.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:57:42 -0500] "GET /assets/js/plugins/iCheck/futurico/futurico.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:57:42 -0500] "GET /assets/js/plugins/iCheck/polaris/polaris.css HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:57:42 -0500] "GET /_debugbar/assets/stylesheets?v=1464964278 HTTP/1.1" 200 197381
10.0.4.225 - - [11/Jul/2016:09:57:42 -0500] "GET /_debugbar/assets/javascript?v=1464964275 HTTP/1.1" 200 348915
10.0.4.225 - - [11/Jul/2016:09:57:42 -0500] "GET /uploads/logo.png HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:57:42 -0500] "GET /assets/js/plugins/iCheck/minimal/blue.png HTTP/1.1" 304 -
10.0.4.225 - - [11/Jul/2016:09:57:42 -0500] "GET /build/assets/js/all.js.map HTTP/1.1" 200 1467981
10.0.4.225 - - [11/Jul/2016:09:57:42 -0500] "GET /api/statuslabels/8/deployable HTTP/1.1" 200 1
10.0.4.225 - - [11/Jul/2016:09:57:43 -0500] "GET /_debugbar/open?op=get&id=e38e82f8b95ea86afb845bdcac40cdc4 HTTP/1.1" 200 15668
10.0.4.225 - - [11/Jul/2016:09:57:43 -0500] "GET /build/assets/css/app.css.map HTTP/1.1" 200 309441
`

**Comment by chrisrbmn** [comment]
Interestingly, and just for grins, I downloaded the full tar, and installed an entirely separate instance.
I created a new asset model, with a new custom field.
I then created a new asset, and entered data into the new custom field. 
I then review the asset, and the custom field data is correctly displayed/saved.

So at this point, whatever the issue is, it appears to be only affecting an upgrade. (whether all upgrades, or just mine, are yet to be confirmed.)

**Comment by snipe** [comment]
We've upgraded a bunch of our hosted customers, and haven't had any issues. Have you cleared your composer cache and all that?

**Comment by snipe** [comment]
(`composer dump`)

**Comment by snipe** [comment]
That would explain the difference, since your autoloader for the new install wouldn't have old stuff in there.

**Comment by chrisrbmn** [comment]
When you say you upgraded a bunch of hosted customers, were any of them using custom fields? and have they actually tested inputting data into them to verify?

I didn't have any issue with the upgrade itself either, which I performed over a month ago, I only now noticed this issue, a week ago, while trying to create a new asset.

in terms of the cache, yes, I tried running 
`php composer.phar clear-cache`
which didn't change the result. I tried to go clear the "app/storage/views" and "app/storage/cache"
but these directories don't appear to exist in v3.

**Comment by chrisrbmn** [comment]
Could having duplicate entries pointing to 2 different fieldsets cause this?
![duplicates](https://cloud.githubusercontent.com/assets/5017742/16768791/57179002-480b-11e6-96fa-d74d044e21d3.PNG)

field_id "7" is the ID for my Express Service Code, and its mapped to FieldSet ID "4".
As you can see, there is another field ID 7, mapped to fieldset ID 5

Could these have been created during the migration/upgrade?

**Comment by chrisrbmn** [comment]
I tried truncating the table, and recreating the row, and that didn't have any affect.
I re-enabled debug, here's the queries.
![queries](https://cloud.githubusercontent.com/assets/5017742/16770450/9468a25a-4812-11e6-9c11-15b59ea09f70.PNG)

I don't see anything that stands out..
