### ISSUE TITLE
Asset ID - leading zeros

### ISSUE THREAD

**Issue by ktdmadmin** [snipe/snipe-it#2232]
#### Expected Behavior (or desired behavior if a feature request)

There should be complete automatic asset ID settings. Few options like:
*Prefix (implemented)
Leading zeros: on|off
*Length of ID: 10
Then ID would be like(with leading zeros on): 0012345678, 0000001589
ID format - selectable or draggable (sections, blocks, modules - you call it): PREFIX - YEAR / MONTH - ASSET_ID    or even some custom ones.

---
#### Actual Behavior

Right now we have only option to set Prefix, and number is simply auto incrementing

---
#### Please confirm you have done the following before posting your bug report:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running v3.0.0-dev-3-g6d810a9
- What OS and web server you're running Snipe-IT on Centos 6.8 Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by lorenzolewis** [comment]
As a note this this: it would be really nice if this could be done in the search field, too. Maybe just programmatically removing the 0's before sending the query could work.

Currently if I have asset number 123 in the database and I search for 000123 it does not return results. This should fix the problem.

**Comment by snipe** [comment]
It's unlikely we're going to modify search queries on the fly. That almost always leads to unforeseen consequences. 

> Currently if I have asset number 123 in the database and I search for 000123 it does not return results. This should fix the problem.

If the asset number is 123, why would it ever return results if you search for 000123? Why would you search for that? Seeing the results for the terms that you're actually searching for doesn't see like a "problem" to me.

**Comment by lorenzolewis** [comment]
With the current numbering system set up at our company we have leading zeros on our asset tags. When we scan with a barcode reader it will automatically put in those leading zeros to a search. 

If I need to create a separate issue for this please let me know.

**Comment by snipe** [comment]
Why wouldn't you just add the leading zeros on the asset tag when you create the asset then?

**Comment by lorenzolewis** [comment]
On the asset tag in Snipe-IT? I didn't think it was possible to add leading zeros if using the auto increment feature for when adding new devices. If it is an option then my apologies.

**Comment by snipe** [comment]
It's not possible using the auto-increment (at this time), but you can still modify that field when you create a new asset. It's editable.

**Comment by lorenzolewis** [comment]
Cool. Thanks for the quick reply!
