### ISSUE TITLE
Old Admin Password

### ISSUE THREAD

**Issue by perezstudios** [snipe/snipe-it#2234]
Hello, the person who originally installed SnipeIT is no longer working here and he didn't leave a username and password.  

Is there a default that I can try and if not then is there a way through the Linux Command line that I can change it?  

Thanks,

Manuel 

- Version of Snipe-IT you're running - 2.1.0-55
- What OS and web server you're running Snipe-IT on - Linux
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Not sure
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Easiest solution will be to change his record in MySQL to have your email address as theirs, and then do a forgotten password request

**Comment by perezstudios** [comment]
Thanks for the response.  It seems that the root user doesn't have access to the mysql.  

Any other ideas?  

Thanks again

**Comment by snipe** [comment]
You can look in app/config/production/database.php to find the credentials for your mysql user.

**Comment by perezstudios** [comment]
Ok, so I was able to go in and change the email address to mine but I am not getting any messages.  

Thanks again

**Comment by snipe** [comment]
I'm not sure what you mean that you're not getting any messages. What messages?
