### ISSUE TITLE
Linux Install Steps - Clear

### ISSUE THREAD

**Issue by perezstudios** [snipe/snipe-it#2237]
Hello,

I have been trying to setup Snipe-IT but am stuck.  

I setup a brand new machine with Linux 14 on it.  

I used the LAMP install.

I then downloaded the install.sh file to my /var/www/html folder.  I gave permissions and then ran the ./install.sh.  

It goes through a bunch of install#'s and that is it.  Is there another step that I am missing?  I can't login to the page because it doesn't show up.  It says page not found.  

I know Apache and MySQL are working because I can see the Apache webpage.  

What else do I need?

Thanks again!
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running - Trying to install
- What OS and web server you're running Snipe-IT on - Linux
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - install.sh
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by ch-gz** [comment]
I had similar situation before.
first, remove all your php related packages, mysql packages, apache packages.
then run the install.sh again to see if any other errors appear.

**Comment by snipe** [comment]
Sounds like your document root in apache might not be set correctly. What version are you trying to install? Can you show me your apache virtual host config?

**Comment by perezstudios** [comment]
Ok, so I was able to get it installed, I think.  

I cant get to the website though.  I keep getting page not found.  

Under Sites Available I have, default and snipeit.conf.

Where should my site be?

Thanks
