### ISSUE TITLE
Unable to change assigned company for an asset

### ISSUE THREAD

**Issue by xWyatt** [snipe/snipe-it#2242]
#### Expected Behavior (or desired behavior if a feature request)

Changing an asset's assigned company to another company within the system should update the asset to the new company. 

-----

#### Actual Behavior

The asset retains the original company in existing assets, and defaults to the first company in the list on newly created assets. 

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - latest pull from v3
- What OS and web server you're running Snipe-IT on - Ubuntu - Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual install
- If you're getting an error in your browser, include that error - N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error -  Editing an asset
- If a stacktrace is provided in the error, include that too. - N/A
- Any errors that appear in your browser's error console. - N/A
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). - Yes, when editing an asset (on the V3 demo)
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. - N/A
- Include what you've done so far in the installation, and if you got any error messages along the way. - N/A
- Indicate whether or not you've manually edited any data directly in the database - Nope

**Comment by snipe** [comment]
Latest push to develop now allows superusers to change the company assigned to an asset
