### ISSUE TITLE
Blank Page after deleting a location

### ISSUE THREAD

**Issue by JvrJava** [snipe/snipe-it#2244]
#### Expected Behavior (or desired behavior if a feature request)

Deleting a location in Admin > Locations would delete the location and continue to display non-deleted locations.

-----

#### Actual Behavior

After trying to delete a location, the Locations page does not load anything (blank page). Checking the source of the page shows that the page has no lines of code. All other pages load fine and I am able to add a location to a user fine. I was able to see the locations page the first time I clicked on it but after clicking remove on the first location the page has been only  blank. Tried multiple browsers and clearing cache/history.
-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
      - Did nothing for the locations page, page is still blank.
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
      - Checked through each one and no related issues or ideas found

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v2.1.1-55-g701c16f

- What OS and web server you're running Snipe-IT on
Windows Server 2012 R2 with IIS

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual Install

- If you're getting an error in your browser, include that error
No error (or page) displayed

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Admin > Locations after clicking the remove icon for a location

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
The username and password for the demo doesn't work?

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
Checking IIS logs shows a successful GET /admin/settings/locations and shows no other information besides that. app/storage/logs shows nothing after trying to load the locations page and the only erros listed are:

[2016-07-11 13:33:13] production.ERROR: ErrorException: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in C:\inetpub\wwwroot\snipe-it\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php:95

and
[2016-07-11 13:52:55] production.ERROR: Symfony\Component\HttpKernel\Exception\NotFoundHttpException in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\RouteCollection.php:148

I can provide more of the log if needed.

- Include what you've done so far in the installation, and if you got any error messages along the way.
I had completed the installation some 20 minutes before the issue developed. Had just created the first user and wanted to add an appropriate location for that user. During the installation I resolved several issues related to access rights with public folder, figuring out what bindings are needed for the site in IIS, and removing the first imported rule under URL Rewrite as was suggested in a separate snipe-it GitHub issue. At this point, the snipe-it site works great with the exception of IE that is still trying to resolve the site with HTTPS on one personal workstation.

- Indicate whether or not you've manually edited any data directly in the database
Tried editing, removing and then re-adding the row for the location that I had deleted.

**Comment by snipe** [comment]
Are you running this over SSL? That first error in your stacks trace is a related to OpenSSL, and you definitely shouldn't be seeing that. This might give you some help on resolving it.

http://stackoverflow.com/questions/27088982/warning-stream-socket-enable-crypto-ssl-operation-failed-with-code-1

My guess would be that your issue is related to the above, as 2.x has been stable for quite some time and we've not seen this issue.

**Comment by JvrJava** [comment]
The SSL error may have something to do with trying to set up and send a password recovery via email with incorrect configuration. Have not had a chance to talk with the system administrators about what SMTP settings are needed for mailing. 

As for running the site with SSL, I will be honest and say that I have no idea. I have not tried to set it up any encryption (running on the local intranet at work so the site is secure enough for now), though I am learning as I go so you would have to ask a slightly more specific question if you want me to check a configuration.

**Comment by JvrJava** [comment]
Ok then, nevermind! I just went in to try the Locations page after turning debug off (turned it on while writing the opening post). I was able to bring up the page just fine and even manage to delete, create and edit the locations. Seems to be working fine now though I wonder why it happened in the first place. Thanks for the quick response anyway.
