### ISSUE TITLE
Unable to configure user permitions 

### ISSUE THREAD

**Issue by Polizogo** [snipe/snipe-it#2249]
#### Expected Behavior (or desired behavior if a feature request)

I'd like being able to config what groups of users can see or see and edit.

-----

#### Actual Behavior

The only thing I can get is allow and deny a user to be admin so i cant make a user can see some of the stuff

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by Polizogo** [comment]
I am not getting an error or something like this...this choice simply doesn't exists. The same problem exists on your demo, i would like to be able to configure the admin rights such as read only, read/write, not visible etc. etc.

**Comment by snipe** [comment]
I still need to know what version you're running and what you're seeing. A screenshot, for example. We put those questions there for a reason.

**Comment by Polizogo** [comment]
![untitled](https://cloud.githubusercontent.com/assets/17650662/16800170/9c324960-48fc-11e6-8076-0eb6f798f568.png)

**Comment by Polizogo** [comment]
![untitled](https://cloud.githubusercontent.com/assets/17650662/16800203/cc4ef86e-48fc-11e6-86c8-122b6c555e5d.png)

**Comment by snipe** [comment]
We don't have fine-grained permissions in v2.x. We've only started introducing them in v3, and even then they're not fully fleshed out yet.

**Comment by Polizogo** [comment]
can you sent me a screen shot to see if it worths installing the newer version ?

**Comment by snipe** [comment]
https://snipe-it.readme.io/blog/v3-is-coming

**Comment by Polizogo** [comment]
in v3 can i config whitch groups can see some of the assets or there is only the choice to see all of them or nothing ?

**Comment by Polizogo** [comment]
I would like also to be able to customize a group can see spesific fields of an asset for example I want a group can see the assets but not the field whitch contains a password

**Comment by snipe** [comment]
Thats not currently available and won't be of several months, at best.

**Comment by Polizogo** [comment]
oh ok thank you, for time this dam is not covering the requests of the company i work for, maybe the next year you can manage too add some settings like these...because from all dams it is the one that is the most friendly to users and helpfull for my job...but it have many disadvantages to the security and the right layers fir diferent types of users
