### ISSUE TITLE
Checkout Asset to User - FatalErrorException

### ISSUE THREAD

**Issue by ITNetMan** [snipe/snipe-it#2254]
**Expected Behavior (or desired behavior if a feature request)**
- Attempting to checkout asset that belongs to category where it requires users to accept the check-in and use the default EULA.
- Should checkout the asset to the user, and send acceptance and EULA.

**Actual Behavior**
FatalErrorException in abcdbc8160cc5dd6327fbc7b560ca1cccd96f2af.php line 16:
syntax error, unexpected ':', expecting '('

But the asset does get assigned out to the user.

**Please confirm you have done the following before posting your bug report:**

[x]  I have enabled debug mode
[x]  I have read checked the Common Issues page

**Please provide answers to these questions before posting your bug report:**

**Version of Snipe-IT you're running**
v3.0.0-dev-4-4233c781a

**What OS and web server you're running Snipe-IT on?**
Windows Server 2012 on IIS 8.5

**What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)**
Manual installation following Version 3 install directions and upgrading to v3 branch as of an hour ago

**If you're getting an error in your browser, include that error**
See attached screenshot

**What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error**
Checkout Asset to User when category of asset is set to acceptance and EULA

**If a stacktrace is provided in the error, include that too.**
Stack trace:
#0 {main}

**Any errors that appear in your browser's error console.**
Attached

![checkout](https://cloud.githubusercontent.com/assets/5835906/16861364/958b4e9a-4a05-11e6-9075-4be030a5acee.PNG)

![error](https://cloud.githubusercontent.com/assets/5835906/16861368/9938f970-4a05-11e6-8eba-10f5826b7b23.PNG)

**Confirm whether the error is reproduceable on the demo.**
- Yes I can reproduce on demo.  It gives a much more thorough debug on there as well.  See attached:
  [debug.pdf](https://github.com/snipe/snipe-it/files/365063/debug.pdf)

**Include any additional information you can find in app/storage/logs and your webserver's logs.**
[2016-07-14 20:49:22] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected ':', expecting '('' in C:\inetpub\wwwroot\snipe-it\storage\framework\views\abcdbc8160cc5dd6327fbc7b560ca1cccd96f2af.php:16
Stack trace:
#0 {main}

**Include what you've done so far in the installation, and if you got any error messages along the way.**
Updated to most recent v3 branch, added one deployable asset which is in a category requiring acceptance and EULA, attempted to check it out to a user.  Error page comes up instead.  Asset does get checked out to the user, but error happens & checkout email doesn't send.

**Indicate whether or not you've manually edited any data directly in the database**
No

**Comment by snipe** [comment]
Fresh pull for V3 and try again please.

**Comment by ITNetMan** [comment]
Works!

The only thing I noticed is that after checking the asset out, the system emails the checkout user the email with the EULA and a link to accept the terms.

When clicking this link, it'll rightfully bring up the login page so that the end-user can sign-in and accept.  However, after signing in, instead of directing to the "Accept" page (which was the original link clicked), it just goes to the main home screen for that user.  I then have to click the link or browse to that URL (https://snipe-it.domain.com/account/accept-asset/9) again while signed in in order to get to the "Accept" page and finish the check in procedure.

I'm not sure how it worked from previous versions as my first install was version3-dev3 and I've never tested this stuff before....just trying to walk through things from an admin and end-user perspective.

**Comment by lisaanthony** [comment]
I am encountering the same issue but the only difference here is checkout email is not sent to the user and there is no error message triggered.

I would also like to know what does "fresh pull from v3" exactly mean
