### ISSUE TITLE
Dashboard shows only links

### ISSUE THREAD

**Issue by alexlazer114** [snipe/snipe-it#2256]
#### Expected Behavior (or desired behavior if a feature request)
Dashboard with proper designs

(what you expect to happen goes here)
Showing only links
-----

#### Actual Behavior
Dashboard with proper designs
(what actually happens goes here)
Showing only links
-----

#### Please confirm you have done the following before posting your bug report:

- [*] I have enabled debug mode
- [*] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html) 

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running  : V3.0.beta-3
- What OS and web server you're running Snipe-IT on  : CentOS 6.7 & httpd 2.2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)  : Manual Installation
- If you're getting an error in your browser, include that error  : Call to a member function showAssetName() on a non-object
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error  : Dashboard
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by alexlazer114** [comment]
![1](https://cloud.githubusercontent.com/assets/20485853/16892874/72eff3ae-4b40-11e6-90de-ff3d62a70b06.jpg)

This is what I am facing...

**Comment by snipe** [comment]
Please check your app_url and make sure it matches the URL in your browser, and provide any errors you see in your browser console. This is usually related to your app_url not matching the URL you're accessing the site from

**Comment by alexlazer114** [comment]
The app_url is same as the one i am using it in the browser.This happened when I purged out the deleted records.

Thanks,
Alex L

**Comment by snipe** [comment]
Then I need to see your error logs (which we ask for in the original ticket)

**Comment by alexlazer114** [comment]
Which log you want apache logs or SnipeIT logs?

**Comment by alexlazer114** [comment]
I have attached both app/storage/log and http logs with this. Please help.
[SnipeIT_Logs.zip](https://github.com/snipe/snipe-it/files/367182/SnipeIT_Logs.zip)

Thanks,
Alex L

**Comment by snipe** [comment]
In the future, please just paste in the logs.

**Comment by snipe** [comment]
Please turn on debugging and tell me what you see when you load the page. I can't tell what in your logs is relevant here.
