### ISSUE TITLE
ldap sync blank page 

### ISSUE THREAD

**Issue by ehareef** [snipe/snipe-it#2257]
Dears, 

Good day , 

Kindly try to configure LDAP setting , i already configure ldap.php file and from admin setting ,

Problem is when i press sync i get blank page without any error or source code 

PHP-Ldap installed and running good 

also i enabled debug but no errors at all 
attached files for admin 

and nest is ldap File

`  /*
    |--------------------------------------------------------------------------
    | URL
    |--------------------------------------------------------------------------
    |
    | URL for the LDAP server. This should start with ldap://, for example:
    | ldap://ldap.yourserver.com
    |
    */
    'url' => "LDAP://10.1.30.33:389",

    /*
    |--------------------------------------------------------------------------
    | Username
    |--------------------------------------------------------------------------
    |
    | Username to use to connect authenticate to LDAP, for example:
    | cn=read-only-admin,dc=example,dc=com
    |
    */
	'username' => "CN=FortiGate,OU=Services Accounts,OU=PalmHills,DC=phd,DC=palmhills,DC=local",

	/*
    |--------------------------------------------------------------------------
    | Password
    |--------------------------------------------------------------------------
    |
    | Password to use when authenticating to LDAP.
    |
    */
	'password' => "********",

	/*
    |--------------------------------------------------------------------------
    | Basedn
    |--------------------------------------------------------------------------
    |
    | The base where the search for users will be executed, for example:
    | dc=example,dc=com
    |
    */
	'basedn'   => "DC=phd,DC=palmhills,DC=local",

	/*
    |--------------------------------------------------------------------------
    | Filter
    |--------------------------------------------------------------------------
    |
    | The search filter for the LDAP query. This probably does not have to be
    | changed.
    |
    */
	'filter' => "&(cn=*)",

	/*
    |--------------------------------------------------------------------------
    | LDAP field names that will be retrieved to create a user.
    |
    | Using the username as an example:
    | If I set 'result.username' => 'my-org-username', the code will connect to
    | LDAP as follows (where $results[$i] represents a row in the LDAP query:
    | $username-to-insert-in-snipe-it = $results[$i]["my-org-username"][0]
    |
    |--------------------------------------------------------------------------
    |
    | The search filter for the LDAP query.
    | Note: all these fields are required, and they should all be lowercase.
    |
    */
    'result.username' => "samaccountname",
    'result.last.name'  => "sn",
    'result.first.name' => "givenname",

    /*
    | These fields are optional as not all LDAP directories will have it.  If yours
    | does not have them, just leave these blank and the extra check will
    | be omitted.
    */
    'result.active.flag' => "",
    'result.emp.num'  => "",
    'result.email' => "mail",

    /*
    |--------------------------------------------------------------------------
    | LDAP filter query for authentication
    |--------------------------------------------------------------------------
    |
    | The LDAP query that we want to execute when authenticating a user. This
    | should not have to be changed.
    |
    */
    'authentication.filter.query' => "uid=",

    /*
    |--------------------------------------------------------------------------
    | LDAP Version
    |--------------------------------------------------------------------------
    |
    | Version of LDAP you are using.
    |
    */
    'version' => 3,`

BR,

![snapit ldap](https://cloud.githubusercontent.com/assets/20264703/16899642/76e50f8c-4c0b-11e6-9a84-889d704bc34d.PNG)

**Comment by dmeltzer** [comment]
Which version of snipe-it are you using?

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by ehareef** [comment]
Dear snip, 

sorry for late reply , kindly find below 

Version of Snipe-IT you're running : V2.1.1
What OS and web server you're running Snipe-IT on : Debian Linux 8 and Apache 2.4 
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) : install.sh 
If you're getting an error in your browser, include that error : no
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error : Ldap Sync.
If a stacktrace is provided in the error, include that too. : no error just blank screen 
Any errors that appear in your browser's error console. : no error just blank screen 
Confirm whether the error is reproduceable on the demo. no
Include any additional information you can find in app/storage/logs and your webserver's logs.
Include what you've done so far in the installation, and if you got any error messages along the way.
Indicate whether or not you've manually edited any data directly in the database : no

**Comment by snipe** [comment]
> Include any additional information you can find in app/storage/logs and your webserver's logs.

**Comment by ehareef** [comment]
her we go

[log-apache2handler-2016-07-25.txt](https://github.com/snipe/snipe-it/files/388474/log-apache2handler-2016-07-25.txt)
[log-apache2handler-2016-07-18(1).txt](https://github.com/snipe/snipe-it/files/388475/log-apache2handler-2016-07-18.1.txt)
[log-apache2handler-2016-07-17.txt](https://github.com/snipe/snipe-it/files/388477/log-apache2handler-2016-07-17.txt)
[log-apache2handler-2016-07-16.txt](https://github.com/snipe/snipe-it/files/388476/log-apache2handler-2016-07-16.txt)



[error (2).txt](https://github.com/snipe/snipe-it/files/388480/error.2.txt)
[error.txt](https://github.com/snipe/snipe-it/files/388479/error.txt)

**Comment by snipe** [comment]
My guess would be that your filter or search query is wrong. LDAP support was improved in v3, so you might want to consider upgrading.

**Comment by ehareef** [comment]
i just install it and  V3 still in beta , problem i not get any error code , just blank page

**Comment by snipe** [comment]
v3 is not in beta.
