### ISSUE TITLE
The requested URL /snipeit/public/auth/signin was not found on this server. - Ubuntu 14.04 - Clean build

### ISSUE THREAD

**Issue by Sam-Levene** [snipe/snipe-it#2258]
#### Expected Behavior (or desired behavior if a feature request)

I expect to be directed to the login screen after installing Snipe-IT and following all the steps.

---
#### Actual Behavior

404 - The requested URL /snipeit/public/auth/signin was not found on this server.

---
#### Please confirm you have done the following before posting your bug report:
- [**YES**] I have enabled debug mode
- [**YES**] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running **2.1?**
- What OS and web server you're running Snipe-IT on **Ubuntu 14.04 via AWS EC2 and logging in remotely through Mozilla Firefox 47 and Windows 7**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **install.sh**
- If you're getting an error in your browser, include that error **404 - The requested URL /snipeit/public/auth/signin was not found on this server.**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **[myIP]/snipeit/public/**
- If a stacktrace is provided in the error, include that too. **N/A**
- Any errors that appear in your browser's error console. **The requested URL /snipeit/public/auth/signin was not found on this server**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). **NO**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. **[2016-07-18 11:11:51] production.DEBUG: Not logged in - admin-auth [] []**
- Include what you've done so far in the installation, and if you got any error messages along the way. **Just installed the database, populated with dummy data. Set up my first user using " php artisan app:install"**
- Indicate whether or not you've manually edited any data directly in the database **NO**

**Comment by Sam-Levene** [comment]
Before anybody comments on the fact that mod_rewrite may be off, it's not. and attempting to re-write the vhosts.conf (or 000-default in ubuntu) to the snipe-it public directory does not affect what I see

**Comment by PRNOHFT** [comment]
Question, can you go in Snipe in general? When you type the IP of the Ubuntu, does it go in Apache?
