### ISSUE TITLE
Users don't show up until i press the refresh button

### ISSUE THREAD

**Issue by mergimgj** [snipe/snipe-it#2270]
#### Expected Behavior (or desired behavior if a feature request)

I expect to click on the current user page and have a list of all my users.
-----

#### Actual Behavior

Whenever i click on the people button on the left hand side it takes me to the current user page and it says "No matching records". Once i click on the refresh button all my users show up; however, if I leave the current user page and come back I get the same issue all over again. 

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
2.1.1
- What OS and web server you're running Snipe-IT on
OSX and Windows 7. Always use google chrome
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
No, the demo shows all users right away. My set up initally showed all users after I imported them from AD, but now it only shows them upon refresh. 
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![when i click people](https://cloud.githubusercontent.com/assets/20228050/16964255/6eac1f7c-4dc8-11e6-9759-65db3bf6fbd5.PNG)

![after i click people](https://cloud.githubusercontent.com/assets/20228050/16964256/7256fe9e-4dc8-11e6-87de-0eb35b472f09.PNG)

**Comment by snipe** [comment]
Try clearing your browser cache, and checking for browser errors.

**Comment by mergimgj** [comment]
Thanks! It solved my problem.
