### ISSUE TITLE
Asset Checkout

### ISSUE THREAD

**Issue by stevecookms** [snipe/snipe-it#2271]
I have successfully added an asset and checked it out to a user.  When you view the assets either via "Deployed" or "List All", the Checkout Date is blank.
![ss](https://cloud.githubusercontent.com/assets/20538795/16964409/4e54fc7a-4dc9-11e6-8ef3-f3798e69def3.png)

OS Ubuntu 14.04
![ss](https://cloud.githubusercontent.com/assets/20538795/16964478/8da257ec-4dc9-11e6-8c66-36b496a50e55.png)

**Comment by dmeltzer** [comment]
I'm not seeing that here.  Can you provide any more information?
![screen shot 2016-07-19 at 4 57 42 pm](https://cloud.githubusercontent.com/assets/3803132/16966308/f5872c2c-4dd1-11e6-89cf-d2ddb64cf364.png)

**Comment by stevecookms** [comment]
Repeated the same process and this time it got a date.  Not sure if I did something wrong.

**Comment by stevecookms** [comment]
I reproduced the issue.

It does not get a checkout date when you create a new asset, and while creating it, assign it to a user.

**Comment by stevecookms** [comment]
It also does not send an email to the user.  I have to check-in the asset (which will send an email), then check-out to user in order for it to send an email and to have the checkout-date to show on the UI
