### ISSUE TITLE
Feature Request - Allow Admins to Add Manufacturers and Suppliers

### ISSUE THREAD

**Issue by veen1981** [snipe/snipe-it#2275]
#### Expected Behavior (or desired behavior if a feature request)

I would like to begin using the multiple companies feature for our different I.T. departments, but would prefer not to grant super-user privileges to each of the departments admins. Admins should be able to add new Manufacturers or Suppliers without having super-user privileges as these fields should not affect the way the software is being used or implemented. If an admin from our Media department is adding a new license, they may need to add a new supplier, or if an admin from our infrastructure department is adding a server, they may need to add a new manufacturer, etc. I would think this option could be added under the create new drop-down.

---
#### Actual Behavior

Currently only super-users can add Supplies or Manufacturers from the Admin drop-down.

---
#### Please confirm you have done the following before posting your bug report:
- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running **v3.0-ebc74a65**
- What OS and web server you're running Snipe-IT on **CentOS 7 1511**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **install.sh**

**Comment by veen1981** [comment]
I also noticed while playing around with the multiple companies feature that users from a new company can still see all the assets from the other company, however they cannot see accessories, licenses, components or consumables... is this the intended behavior?

**Comment by dmeltzer** [comment]
The second part is #2206, as far as the first part, I'd agree, though I'm not sure how that would interact in full multiple companies support (was thinking about this earlier) should multiple companies share suppliers or have their own set? Thinking the former is fine, but i can think of situations where that would be a lie
