### ISSUE TITLE
Asset Download

### ISSUE THREAD

**Issue by stevecookms** [snipe/snipe-it#2278]
Snipe-IT version	v3.0-ebc74a65

If I browse to "All Assets" and select download:

If I select "CSV", a file named "download" is downloaded.  There is no file extension.

If I select "MS-Excel", an "XLS" file downloads, but Excel 2016 will not open the file.

A trick I have done in the past with "XLS" files is to save the contents as "CSV", but rename the file extension to "XLS" and Excel will recognize and convert on loading.

I would also recommend writing an XLSX instead of XLS.

It looks like there is an open source product for PHP for writing excel

[https://phpexcel.codeplex.com/](url)

**Comment by snipe** [comment]
This is related to #1785, so closing as duplicate.
