### ISSUE TITLE
View Assigned Assets

### ISSUE THREAD

**Issue by mmcleod82** [snipe/snipe-it#2280]
When I hit 'View Assigned Assets' or when redirected to that page in some other way (after accepting asset), the page displays some raw data with an exception:

![capture](https://cloud.githubusercontent.com/assets/19797176/16989550/8d645154-4e8c-11e6-94fc-03672a635e1a.PNG)

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by mmcleod82** [comment]
•Version of Snipe-IT you're running - V3 latest
•What OS and web server you're running Snipe-IT on - IIS8, Server 2012
•What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual 
•If you're getting an error in your browser, include that error
•What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - from anywhere, clicking on logged in user and selecting 'View Assigned Assets'
•If a stacktrace is provided in the error, include that too.
•Any errors that appear in your browser's error console.
•Confirm whether the error is reproduceable on the demo. No
•Include any additional information you can find in app/storage/logs and your webserver's logs.
[2016-07-21 08:45:09] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function fullName() on null' in C:\inetpub\wwwroot\snipe-it\storage\framework\views\d03d781b83abe12c0cd49d14bcffc62e25173faa.php:316

•Include what you've done so far in the installation, and if you got any error messages along the way.
Upgraded from V3 beta (had same behaviour then).

•Indicate whether or not you've manually edited any data directly in the database - No.

**Comment by snipe** [comment]
Can you look at C:\inetpub\wwwroot\snipe-it\storage\framework\views\d03d781b83abe12c0cd49d14bcffc62e25173faa.php and tell me what's on line 316?

**Comment by mmcleod82** [comment]
`<td><?php echo e($log->adminlog->fullName()); ?></td>`

**Comment by snipe** [comment]
Did you purge any data recently? There should never be an entry in the admin log where it can't find someone's name.

**Comment by mmcleod82** [comment]
Well - I do occasionally purge when / if I've deleted some records... only ever gracefully through settings though...

**Comment by snipe** [comment]
Yeah, which makes me think we're missing something in the purger.

**Comment by mmcleod82** [comment]
Thanks for the fix.

**Comment by snipe** [comment]
Can you confirm it's working?

**Comment by mmcleod82** [comment]
Yes - working perfectly.

**Comment by snipe** [comment]
Great! I'm going to have to try to go back through the purger and figure out what it's missing. Grr.

**Comment by mmcleod82** [comment]
I don't know if it's of any help, but it seemed only to break in that way for me, other users could view their own assigned assets no problem.

**Comment by snipe** [comment]
That is interesting data, for sure. Will be a bitch to try to reproduce, but I'll try.
