### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by stevecookms** [snipe/snipe-it#2281]
#### Expected Behavior (or desired behavior if a feature request)

Trying to backup data

-----

#### Actual Behavior

Says it backs up but does not

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running:	v3.0-ebc74a65
- What OS and web server you're running Snipe-IT on: Ubuntu 14.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- If you're getting an error in your browser, include that error

[2016-07-20 09:42:58] production.ERROR: backups backups : error: Failed to backup  because: The dump process failed with exitcode 127 : Command not found : sh: 1: /usr/local/bin/mysqldump: not found
  
[2016-07-20 09:42:58] production.ERROR: backups backups : error: Failed to backup  because: The dump process failed with exitcode 127 : Command not found : sh: 1: /usr/local/bin/mysqldump: not found
  
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

Admin > Backups > Generate Backup

my "mysqldump" is located at "/usr/bin/mysqldump"

Is there a configuration element I can change?

**Comment by dheer99** [comment]
Hi , are you able to fix backup issue, i am also facing same

**Comment by dmeltzer** [comment]
See DB_DUMP_PATH in .env.example

**Comment by ghost271994** [comment]
Find out mysqldump command associated with which directory using:
which mysqldump
the result should be like /usr/bin/mysqldump or anything else.
then go to snipeit directory and make changes on .env (Hidden file).
DB_DUMP_PATH='/usr/bin'
