### ISSUE TITLE
LDAP import - names with apostrophes

### ISSUE THREAD

**Issue by ghost** [snipe/snipe-it#2282]
The LDAP import of names with apostrophes in fails, saying the email address is invalid.

Apostrophes ARE valid in email addresses.

**Comment by bruce2004x** [comment]
May you give an example of such address?

**Comment by mmcleod82** [comment]
john.o'connell@blah.com

**Comment by snipe** [comment]
One of two issues here:

1) Either the Laravel email validator has a bug and isn't accepting email addresses 

or

2) because we escape characters on the way in, the email address it's actually trying to create is an HTML-ified version of the email address, like john.o&apos;connell@blah.com

**Comment by mmcleod82** [comment]
Well - it also won't let you create the user manually, with an apostrophe in the email address, when hitting save it says invalid email format.

This leans me towards number (1) !

**Comment by snipe** [comment]
Blergh. I posted this already but it somehow got lost. 

The thing is that we escape all data, including manual entries, on the way in. Bad data only needs one place where you forgot to escape it on the way out for it to become a vector. 

We may need to write a custom handler for this.

**Comment by Steven4x4** [comment]
I have the same problem. Was a fix ever released for this issue?

**Comment by davidplatts** [comment]
I am also experiencing this as an issue. I would be very interested in any fixes/handlers that have been posited and/or implemented

**Comment by netman63** [comment]
Also having the same issue.  Any workarounds or fixes available?

**Comment by andrefecto** [comment]
Any update on a fix for this?
