### ISSUE TITLE
No more line breaks in asset notes in v3

### ISSUE THREAD

**Issue by DavidGuder** [snipe/snipe-it#2283]
Hi there,

after migrating to v3 which looks fine now and also has a nice handling, we recognized an issue.

Linebreaks are not possible to do (by clicking enter) any longer in v3 but it worked fine in v2.1

Is there any reason?

the thing is that we have several seperate passages in the notes for additional dokumentation purposes.

Thanks in advance for your comment.

Cheers
David

**Comment by snipe** [comment]
> Linebreaks are not possible to do (by clicking enter) any longer in v3 but it worked fine in v2.1

More context is needed This is on editing an asset, checking an asset out?

**Comment by DavidGuder** [comment]
Sorry for the few information.
It is in both cases, editing and checking out, but i need to be more precise.
When editing the asset you can put it line breaks by hitting enter and they stay persistent when editing the asset again. But on the general info page, the "view asset" page where general parameters are listed, there is just one floating block of text.

Hope this is enough info.

Cheers
David

**Comment by stevecookms** [comment]
When you add/edit the asset it looks like this:

line 1
line 2
line 3

When you view all the assets in table view, you see this:

line 1 line 2 line 3

**Comment by DavidGuder** [comment]
Great, thanks @dmeltzer and @snipe for your effort! That's the solution for our issue!

Cheers
David
