### ISSUE TITLE
Upgrade Issue(s)

### ISSUE THREAD

**Issue by stf675** [snipe/snipe-it#2284]
#### Expected Behavior (or desired behavior if a feature request)
don't know.  No errors I assume
-----

#### Actual Behavior

running php artisan migrate result in

`PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class log does not exist' in /var/www/html/snipeit/bootstrap/cache/compiled.php:1355
Stack trace:
#0 /var/www/html/snipeit/bootstrap/cache/compiled.php(1355): ReflectionClass->__construct('log')
#1 /var/www/html/snipeit/bootstrap/cache/compiled.php(1309): Illuminate\Container\Container->build('log', Array)
#2 /var/www/html/snipeit/bootstrap/cache/compiled.php(1874): Illuminate\Container\Container->make('log', Array)
#3 /var/www/html/snipeit/bootstrap/cache/compiled.php(1410): Illuminate\Foundation\Application->make('Psr\\Log\\LoggerI...')
#4 /var/www/html/snipeit/bootstrap/cache/compiled.php(1387): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /var/www/html/snipeit/bootstrap/cache/compiled.php(1373): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /var/www/html/snipeit/bootstrap/cache/compiled.php(1309): Illuminate\Container\Container->build('App\\Exceptions\\...', Array)
#7 /var/www/html/snipeit/bootstrap/c in /var/www/html/snipeit/bootstrap/cache/compiled.php on line 1355`

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running  
**3.0**
- What OS and web server you're running Snipe-IT on 
**centos 7.2 / apache**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
**following upgrade instruction** 
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
**running php artisan migrate**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
**Browser show empty page, no errors**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Try running `composer dump`

**Comment by stf675** [comment]
tried, did not work.  I reran all the steps again and got past it.
