### ISSUE TITLE
Question: .env file syntax

### ISSUE THREAD

**Issue by stf675** [snipe/snipe-it#2285]
Here is example of .env file from instruction page:

```
# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=ChangeMe
APP_URL=null
APP_TIMEZONE='US/Pacific'
APP_LOCALE=en
```
I am a little confused when do I need to use quotes (like APP_TMEZONE) and when not (like APP_LOCALE)

version 2.x config files had all values in quotes.

**Comment by snipe** [comment]
.env doesn't work the same as a regular PHP file. Generally speaking, if the text has a space in it, or a character that could be considered weird, use quotes. The .env.eample pretty much shows you where you need that stuff.

Otherwise don't. And don't put any extra whitespace after the value.
