### ISSUE TITLE
Asset Update

### ISSUE THREAD

**Issue by stevecookms** [snipe/snipe-it#2286]
#### Expected Behavior (or desired behavior if a feature request)
Asset is marked as "Deployed" on "All Assets" page

-----

#### Actual Behavior

On "Asset Update", it has "Ready to Deploy" in dropdown.

-----

#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.0-ebc74a65
- What OS and web server you're running Snipe-IT on: Ubuntu 14.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): install.sh
- If you're getting an error in your browser, include that error

**Comment by snipe** [comment]
Ready to deploy is a sort of status type. The status label is a more specific version of that. If an asset is Ready to Deploy, it's in a deployable state. If an asset is Ready to Deploy and is ALSO deployed, it shows up on the Deployed page.

**Comment by stevecookms** [comment]
What about on the Reporting side.

If you go to Reporting > Asset Report

The status is "Ready to Deploy" and the assets are checked out to a user?

It just seems like it should be "Deployed" on that report and "Ready to Deploy" if it is not assigned to a user.
