### ISSUE TITLE
V3 upgrade: Whoops, looks like something went wrong

### ISSUE THREAD

**Issue by stf675** [snipe/snipe-it#2287]
#### Expected Behavior (or desired behavior if a feature request)

Successful Login

-----

#### Actual Behavior

Whoops, looks like something went wrong. after entering name and password.  I had LDAP enabled, so I ran

**php artisan snipeit:ldap-disable**

after 1st run I got this

```
****************************************************
This will disable LDAP support. You will not be able
to login with an account that does not exist
locally in the Snipe-IT local database.
****************************************************

Do you wish to continue? [y|N] (yes/no) [no]:
 > y

Unable to disable LDAP.
```

2nd try I got

```
PHP Fatal error:  Uncaught exception 'ReflectionException' with message 'Class App\Console\Kernel does not exist' in /var/www/html/snipeit/bootstrap/cache/compiled.php:1355
Stack trace:
#0 /var/www/html/snipeit/bootstrap/cache/compiled.php(1355): ReflectionClass->__construct('App\\Console\\Ker...')
#1 /var/www/html/snipeit/bootstrap/cache/compiled.php(1309): Illuminate\Container\Container->build('App\\Console\\Ker...', Array)
#2 /var/www/html/snipeit/bootstrap/cache/compiled.php(1874): Illuminate\Container\Container->make('App\\Console\\Ker...', Array)
#3 /var/www/html/snipeit/bootstrap/cache/compiled.php(1137): Illuminate\Foundation\Application->make('App\\Console\\Ker...', Array)
#4 /var/www/html/snipeit/bootstrap/cache/compiled.php(1353): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array)
#5 /var/www/html/snipeit/bootstrap/cache/compiled.php(1309): Illuminate\Container\Container->build(Object(Closure), Array)
#6 /var/www/html/snipeit/bootstrap/cache/compiled.php( in /var/www/html/snipeit/bootstrap/cache/compiled.php on line 1355
```

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----

My server had 2 accounts - I had to run all the steps as root, as other account has no permissions.
at the end I chown all files to apache.

I do not remember if I ran original install under regular user or under root.

(Of course I can rerun upgrade steps agasin, 2.1 version  was not in production)

Meanwhile did I overlooked anything?

**Comment by snipe** [comment]
Please run `composer dump`
