### ISSUE TITLE
FEATURE REQUEST: Asset Confirmation

### ISSUE THREAD

**Issue by stevecookms** [snipe/snipe-it#2294]
It would be nice to be able to "resend" asset delivery emails.

It would be nice when a user logs in, and they have unconfirmed assets,, there would be an option for them to accept or reject the asset.

A good place might be the Assigned Assets views.  If the asset is unconfirmed, place an "accept" and "reject" button inline with each asset.

As of right now, the only way I know to confirm the asset is to have the email with the link in it.

**Comment by snipe** [comment]
Duplicate of #2303

**Comment by snipe** [comment]
Sorry, wrong ticket :(

**Comment by stevecookms** [comment]
Any update on this?

**Comment by mrabbat** [comment]
That's a very good feature to consider in future releases

**Comment by aglasson** [comment]
I think this is a great idea.
To add to this I think it would be great if the checkout screen had a checkbox to "opt-in" in an asset that needs to be accepted.
For example docking stations I would not normally require users to accept. However if they are taking a docking station home to use there I would put that in those notes and ideally check a "Require asset acceptance" to ensure the accept any device leaving the company premises to reduce the risk of "I never took one home" rubbish.

**Comment by aglasson** [comment]
Bad bot, great snipe :)

**Comment by wilsonlspacheco** [comment]
+1

**Comment by goludiaOH** [comment]
+1 on all of this: being able to resend the acceptance emails but also be able to accept/reject from within the tool.  

We've already had so many issues of people "losing" or "missing" the emails, not being notified of their asset acceptance being needed, and not being able to accept their assets.

**Comment by smksar** [comment]
Yes I was also looking for ways to resend/notify the user of their assigned unaccepted assets etc.

To have a button to send acceptance email again to either specific user or to all under the Unaccepted Assets reports and hope to include all others like license and accessories as well.

**Comment by aglasson** [comment]
Bad bot. Yes, still relevant.

**Comment by lokesh-sg** [comment]
Yes

Lokesh G
~Sent from my handheld. Excuse me for typos

________________________________

**Comment by BizToolsCanada** [comment]
+1 for this feature

**Comment by AndersTao** [comment]
Same, this is very important !

**Comment by mmoolchandani** [comment]
Hi Team,
Any update on this as this is quite an important feature

**Comment by snipe** [comment]
If there was an update, we'd have updated this issue.

**Comment by adh1851** [comment]
Any idea of when this feature would possibly be available or if this is something that will not be available?  Just started to use this software and trying to come up with a workflow.  Right now when a new employee starts hardware is checked out to that users sometimes before their email is ever created.  In those cases we would really like the option to be able to resend the email once the account is created.

**Comment by snipe** [comment]
> Any idea of when this feature would possibly be available or if this is something that will not be available?

It will be available, but I'm not sure when. That's the best I can give you right now.

**Comment by mahesh2471990** [comment]
> 
> 
> > Any idea of when this feature would possibly be available or if this is something that will not be available?
> 
> It will be available, but I'm not sure when. That's the best I can give you right now.

Hope the best can be done on this. This is really required. So we resend and remind them.
Can we have the option get the report of Unaccepted assets with the help of php artisan? 
So we can resend to those users

**Comment by victoriawhitmore** [comment]
+1 I would love to see this added as a feature, as well as something when they log in if they have outstanding assets that they have not accepted or rejected it would remind them to do it.

**Comment by TheVakman** [comment]
+1 from me!

**Comment by AndersTao** [comment]
This is stille very relevant!
E-mails is lost for some users, and it is nice to re-send to speed up the accept

**Comment by adh1851** [comment]
Still relevant and would love this option to be available.

**Comment by viclou** [comment]
+1 FD13471

**Comment by twisted3motions** [comment]
I would like to be able to renew confirmation on a yearly basis, so something like that would be great

**Comment by kwoodVisions** [comment]
This would be great for users who don't pay attention to emails and delete the asset acceptance email.

This has been a request for so long - is it something that's even being considered?

**Comment by brichardson-insync** [comment]
I'd love for this feature to be added. It is almost a must have to users who fail to accept be prompted to reaccept

**Comment by nickjmv** [comment]
This is something we are really looking for, employees in our company often read to fast through emails and miss the accept-link.

Is there an update for this feature?

**Comment by victoriawhitmore** [comment]
Hi Yes this is still relevant it would be great to have this feature available.

**Comment by aglasson** [comment]
Can someone please turn off this annoying stale bot? This feature request isn't going stale or away anytime soon.

**Comment by simonshtipelman** [comment]
+1

**Comment by JWK82** [comment]
+1

**Comment by viclou** [comment]
+1 16206

**Comment by Relix360** [comment]
+1

**Comment by drd-dev** [comment]
+1

**Comment by victoriawhitmore** [comment]
Yes still relevant

**Comment by nickjannes101** [comment]
yes, still relevant!

**Comment by JWK82** [comment]
highly relevant

**Comment by Thomer73** [comment]
yes we need this feature too ...

**Comment by ISNWAdmin** [comment]
Very necessary. +1 for resend acceptance, or at least some way for users who "can't find" the email to be able to accept equipment.

**Comment by simonshtipelman** [comment]
Still very interested

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sexydadee** [comment]
+1 still need this feature

**Comment by ResendCheckouts** [comment]
Hoping for this feature. Our workers love not signing out assets.

**Comment by Norjek** [comment]
> 
> 
> I think this is a great idea.
> To add to this I think it would be great if the checkout screen had a checkbox to "opt-in" in an asset that needs to be accepted.
> For example docking stations I would not normally require users to accept. However if they are taking a docking station home to use there I would put that in the checkout notes and ideally check a "Require asset acceptance" checkbox to ensure the user accept any device leaving the company premises to reduce the risk of "I never took one home".

+1 for that

The users can already see assigned assets and as an admin I can find open confirmations in the "unaccepted assets" report. But there is no option to resend the confirmation mail.
For all users logging in, with at least one unaccepted asset, I recommend to show a banner message at the top with a link to the .../account/accept page where they can accept all assets. That might already be enough to get users to confirm their received equipment...

**Comment by ChristophAuch** [comment]
+1

**Comment by trentontrees** [comment]
+1

**Comment by pascal-ts** [comment]
+1

**Comment by mhishamsg** [comment]
+1 - this feature is really needed.

**Comment by lewisstancer** [comment]
+1 This is a must, even if the system did it automatically by reminding the user once a week/month (admin choice?)

**Comment by snipe** [comment]
This is a WIP in #11501

**Comment by snipe** [comment]
This was implemented in the Unaccepted asset report a while ago. `/reports/unaccepted_assets`
