### ISSUE TITLE
FEATURE REQUEST: Consumables Import

### ISSUE THREAD

**Issue by stevecookms** [snipe/snipe-it#2295]
It would be nice to be able to import a csv of consumables assigned to users
## CONSUMABLE_ID, USER_NAME, QUANTITY

1, steve.cook, 10

**Comment by dmeltzer** [comment]
You can in v3.  It's only doable via the command line currently.  See https://snipe-it-manual.readme.io/docs/importing-assets

**Comment by dmeltzer** [comment]
Actually that's not entirely true.  You can import consumables in general, but not the checked out qty/status.  I'll ponder how to combine this..
