### ISSUE TITLE
Asset Delivery (Accept/Reject)

### ISSUE THREAD

**Issue by stevecookms** [snipe/snipe-it#2303]
#### Expected Behavior (or desired behavior if a feature request)

When you click the link in the email to accept/reject the asset, login, accept/reject the asset.

---
#### Actual Behavior

You click the link, login, takes you to the home page.  It doesn't present you with the accept/reject screen.  You have to go back to the email, click the link, and since you are already logged in, it will present you with the accept/reject screen.

---
#### Please confirm you have done the following before posting your bug report:
- [ X] I have enabled debug mode
- [ X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running: v3.0-ebc74a65
- What OS and web server you're running Snipe-IT on: ubuntu 14.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): install.sh

**Comment by rozowykubek** [comment]
I can confirm above behavior 


**Please provide answers to these questions before posting your bug report:**

-  Version of Snipe-IT you're running: v3.0-ebc74a65

- What OS and web server you're running Snipe-IT on: Windows 10, xampp

- What method you used to install Snipe-IT: zipped source, composer

**Comment by rozowykubek** [comment]
@snipe sorry for bothering you but could you take a look at this ? 
I can reproduce this bug every time and we need this feature to work properly if we are to deploy snipe in our corporation -_-


thanks for your effort !

**Comment by stevecookms** [comment]
Any idea on when this will be fixed?

**Comment by stevecookms** [comment]
Like @rozowykubek said, I need this feature to be working in order to deploy this application.

**Comment by rozowykubek** [comment]
@stevecookms unfortunately, it does look like we will have to wait some time before it gets fixed

**Comment by rozowykubek** [comment]
@dmeltzer @snipe 
Hi,
could you please label it as a bug ? this is issue is quite old and was confirmed by couple of people yet it seems stuck -_-

I would have posted error but there is no such thing. When you click on the link it takes you to login screen and after you log in it doesn't ask you for acceptance... 
you have to click on the link once more to get the "acceptance screen"

**Comment by aglasson** [comment]
This was not working in 3.5.2 for me. It is now working perfectly in 3.6.2.

**Comment by stevecookms** [comment]
Just upgraded to 3.6.2..... and still doesn't work for me.

@aglasson Were you already logged in?  Make sure you are logged out of the application.  When you click the link in the email, it should present the login screen.

For me, after you login, it takes me to the dashboard.
It should show the accept/reject screen for the asset.

**Comment by aglasson** [comment]
Hey mate.
Yep I've had staff that have never logged into Snipe before and got the nice Accept/Reject screen bullet options with EULA.
Staff that have logged in before but needed to login after clicking the link also worked fine.
Even watched staff do it from various different web browsers.
Perhaps this issue has an environmental element  to it?
