### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by bruce2004x** [snipe/snipe-it#2305]
#### Expected Behavior (or desired behavior if a feature request)

Open main page after upgrade from 2.2 to 3

-----

#### Actual Behavior

As soon as I open the brower it says "Whoops, looks like something went wrong."

-----

#### Please confirm you have done the following before posting your bug report:

- [No ] I have enabled debug mode
- [ Yes] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: 3
- What OS and web server you're running Snipe-IT on: Win Server 2008 and IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual
- If you're getting an error in your browser, include that error: Whoops, looks like something went wrong.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: trying to open main page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.: no
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).no

I guess that thue error is related to the .env file. Following the instructions, I says that I will find that file, but I didn. So I copy teh original ".env.example" and made the change over it. Here it comes the issue, what name is supossed that file should have? I renamed it as ".env.production" and "production.env" but nothing happens.

May you help me?

**Comment by snipe** [comment]
Should just be called `.env`

**Comment by bruce2004x** [comment]
snipe, thanks for your rapid answer, the thing is that in Windows it is not possible, I mean, if I try to create or save a file just called ".env" the OS says "You must type a file name", 'cause for Windows everything after a period (.) is the extension of the file

**Comment by snipe** [comment]
Are you trying it via command line, or Windows Explorer? Something like this from cli should work:

`copy .env.example .env`

**Comment by bruce2004x** [comment]
f******ing great!!!!! jajaja It works!! Now the GUI opens fine..I really love this app..and your kind help.

Best

**Comment by snipe** [comment]
![dancing-badger](https://cloud.githubusercontent.com/assets/197404/17070545/6258dbd4-5011-11e6-9a8b-4754fa542258.gif)

**Comment by delino12** [comment]
Just burst in. and i tried the code after composing my install on git then BOOM {it worked !} thanks 
![accksnipe](https://cloud.githubusercontent.com/assets/16080657/18666361/4c07595c-7ee0-11e6-8909-d30eac3eacc4.jpg)

**Comment by snipe** [comment]
![congrats](https://cloud.githubusercontent.com/assets/197404/18666408/8f2ac084-7ee0-11e6-8bbf-cd96f9b27cd1.gif)

**Comment by Neangvuth** [comment]
Hi Snipe-it Teams

I got this message too when i click create database table.

Could you tell me how to fix it?

Thanks

**Comment by snipe** [comment]
@Neangvuth  - Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by Neangvuth** [comment]
Dear Snipe,

- I install snipe-IT version 3.6.2
- My OS windows 10 pro 64bit and i user xampp webserver v3.2.2
- I install manual installation.
I got error below while i click create database table
![untitled](https://cloud.githubusercontent.com/assets/24447465/21172666/c926f826-c205-11e6-837d-a3373f85d814.png)

- And before click create database this so page like below
![1](https://cloud.githubusercontent.com/assets/24447465/21172718/1aa477aa-c206-11e6-9d65-5b1bbbd20158.png)

**Comment by snipe** [comment]
@Neangvuth Please enable debugging, as requested. https://snipe-it.readme.io/docs/getting-help#step-1-enable-debug-mode

**Comment by amiteng7** [comment]
Hi Snipe IT,

I have imported the csv into snipe IT, once i m processing that getting error on browser "Whoops, looks like something went wrong snipe it"

And also that is not showing into assets section. can you please help me out.

Details:-
Snipe-IT version	v3.6.3 build 15 (g1bf34d7)
PHP Version	7.0.13-0ubuntu0.16.04.1
Laravel Version	5.2.45

**Comment by snipe** [comment]
@amiteng7 Please enable debugging, as requested. https://snipe-it.readme.io/docs/getting-help#step-1-enable-debug-mode

**Comment by amiteng7** [comment]
That is enabled and successfully imported the csv but during the process of imported file.
getting below error.

Asset	Errors
_empty_	Asset Model "Unknown": The category id field is required. The manufacturer id field is required. 
Asset: The model id field is required. The asset tag field is required. 

And how do i edit labels and generate new labels into All assets fields.

Thanks
Amit

**Comment by amiteng7** [comment]
My CSV format (column)

Sr No-City-Employee Name-Category-id-Center-Asset- Model Asset-Old Tagging No	Charger Sr No	BATTERY Sr. No.	Manufacturer id	Mouse Sr No	Keyboard Sr No	LCD Serial Number	Google Drive Status	PW Status	Admin/User Account Status	OS Type	RAM Status	Processor	Hard Disk		Windows Update	Misc Info	Checked By

**Comment by snipe** [comment]
You have to use the predefined column headers, per the importing documentation. https://snipe-it.readme.io/docs/importing

**Comment by closterfield** [comment]
i get stuck in password reset link. if entered correct password says whoops looks like something went wrong..... i want to know where is the location of url/password/email we have passwords rather than password

**Comment by nandoppt** [comment]
I see this same problem when creating a new computer 
![capturaa](https://user-images.githubusercontent.com/26169254/30124291-50cd8ef0-92fa-11e7-808b-97dd4921cf25.PNG)
Please Help!!!

**Comment by snipe** [comment]
@nandoppt Please create a new issue and include log information. This thread was closed a year ago.
