### ISSUE TITLE
V3 Bug?

### ISSUE THREAD

**Issue by stf675** [snipe/snipe-it#2306]
new install on CentOs 7

At Admin-Manufacturers - Create New

on the right side displayed:

```
Have Some Haiku

Serious error.
All shortcuts have disappeared.
Screen. Mind. Both are blank.
```
Is it by design?  or something is missing there?

**Comment by snipe** [comment]
It's by design. Just a haiku, nothing to be concerned about.

**Comment by snipe** [comment]
(We will be improving the UX on that so that it's still fun, but less confusing for people new to the system.)
