### ISSUE TITLE
Snipe-it mail notification

### ISSUE THREAD

**Issue by Amoodi** [snipe/snipe-it#2308]
Hi there,
I just installed it on ubuntu box and i'm able to access my site. Every things looks fine now I want to check email notification is working or not and I tried forgot my password option but it's giving me error massage "Whoops, looks like something went wrong.l,"  

where can I check email notification delivery logs..

Below is mail.php.....Pls help me..

=================================================
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Mail Driver
    |--------------------------------------------------------------------------
    |
    | Laravel supports both SMTP and PHP's "mail" function as drivers for the
    | sending of e-mail. You may specify which one you're using throughout
    | your application here. By default, Laravel is setup for SMTP mail.
    |
    | Supported: "smtp", "mail", "sendmail", "mailgun", "mandrill", "ses", "log"
    |
    */

    'driver' => env('MAIL_DRIVER', 'smtp'),

    /*
    |--------------------------------------------------------------------------
    | SMTP Host Address
    |--------------------------------------------------------------------------
    |
    | Here you may provide the host address of the SMTP server used by your
    | applications. A default option is provided that is compatible with
    | the Mailgun mail service which will provide reliable deliveries.
    |
    */

    'host' => env('MAIL_HOST', 'smtp.mydomain.com'),

    /*
    |--------------------------------------------------------------------------
    | SMTP Host Port
    |--------------------------------------------------------------------------
    |
    | This is the SMTP port used by your application to deliver e-mails to
    | users of the application. Like the host we have set this value to
    | stay compatible with the Mailgun e-mail application by default.
    |
    */

    'port' => env('MAIL_PORT', 587),

    /*
    |--------------------------------------------------------------------------
    | Global "From" Address
    |--------------------------------------------------------------------------
    |
    | You may wish for all e-mails sent by your application to be sent from
    | the same address. Here, you may specify a name and address that is
    | used globally for all e-mails that are sent by your application.
    |
    */

    'from' => ['address' => env('email@******.com', null), 'name' => env('A R Amoodi', null)],

    /*
    |--------------------------------------------------------------------------
    | E-Mail Encryption Protocol
    |--------------------------------------------------------------------------
    |
    | Here you may specify the encryption protocol that should be used when
    | the application send e-mail messages. A sensible default using the
    | transport layer security protocol should provide great security.
    |
    */

    'encryption' => env('MAIL_ENCRYPTION', 'tls'),

    /*
    |--------------------------------------------------------------------------
    | SMTP Server Username
    |--------------------------------------------------------------------------
    |
    | If your SMTP server requires a username for authentication, you should
    | set it here. This will get used to authenticate with your server on
    | connection. You may also set the "password" value below this one.
    |
    */

    'username' => env('email@******.com'),

    /*
    |--------------------------------------------------------------------------
    | SMTP Server Password
    |--------------------------------------------------------------------------
    |
    | Here you may set the password required by your SMTP server to send out
    | messages from your application. This will be given to the server on
    | connection so that the application will be able to send messages.
    |
    */

    'password' => env('mypwassword'),

    /*
    |--------------------------------------------------------------------------
    | Sendmail System Path
    |--------------------------------------------------------------------------
    |
    | When using the "sendmail" driver to send e-mails, we will need to know
    | the path to where Sendmail lives on this server. A default path has
    | been provided here, which will work well on most of your systems.
    |
    */

    'sendmail' => '/usr/sbin/sendmail -bs',

];

**Comment by snipe** [comment]
You should be setting those variables in your env file, not directly in your mail.php.
https://snipe-it.readme.io/docs/configuration

**Comment by Amoodi** [comment]
**snipe**  Thanks a bunch now email notification is working....Now I have below .env pls suggest if need to add from .env.example.


=====================================
#Created By Snipe-it Installer
APP_TIMEZONE=Asia/Kolkata
DB_HOST=localhost
DB_DATABASE=snipeit
DB_USERNAME=snipeit
DB_PASSWORD=***************
APP_URL=http://snipeit
APP_KEY=***********************
# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=smtp.mydomain.com
MAIL_PORT=587
MAIL_USERNAME=email@mydomain.com
MAIL_PASSWORD=password
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=email@mydomain.com
MAIL_FROM_NAME=Snipe-IT

# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=ChangeMe
APP_URL=null
APP_TIMEZONE='UTC'
APP_LOCALE=en
=====================================

**Comment by snipe** [comment]
I don't know what your question is.

**Comment by Amoodi** [comment]
There are more options available in .env.example I just copied OUTGOING MAIL SERVER SETTINGS, BASIC APP SETTINGS and rest of added the time of installation in .env

I shared .env here for your expert view if anything need to add.

**Comment by snipe** [comment]
You should include all of the settings from .env.example. Even if you leave them as defaults, they need to be included in your .env file.
