### ISSUE TITLE
Exporting CSV, MS-Excel, and TXT files are missing their extensions

### ISSUE THREAD

**Issue by gdhnz** [snipe/snipe-it#2310]
#### Expected Behavior (or desired behavior if a feature request)

When I go to export a CSV, MS_Excel or TXT of all my assets, I should get a correctly named file with an extension.

-----

#### Actual Behavior

When I go to export a TXT of all my assets, a file is downloaded called "Unknown" with no extension.

When I go to export a CSV or MS-Excel of all my assets, two files called "Unknown" and "Unknown-2" are downloaded with no extensions.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- v3.0.0-dev-3
- CentOS Linux release 7.2.1511, Apache v2.4.6, and PHP v7.0.9.
- The error is reproducible on the demo at https://demo.snipeitapp.com/.
- No errors in my laravel.log

**Comment by snipe** [comment]
Just rename them with .csv.

**Comment by gdhnz** [comment]
Really? A default filename couldn't be set?

If they're just CSV files, why have MS-Excel and TXT as export options?

Also doesn't resolve the double download of CSV and MS-Excel files.

**Comment by dmeltzer** [comment]
It looks like we want to switch to using 
https://github.com/hhurz/tableExport.jquery.plugin over https://github.com/kayalshri/tableExport.jquery.plugin, it's a more updated version that comes with better defaults and allows more configuration (and it's been updated recently!)

**Comment by dmeltzer** [comment]
The double download seems to only happen the first time you choose the option on the page, if you choose it again it only downloads things once.  I'll take a closer look later.
