### ISSUE TITLE
Not able to send email through mail relay (No user and pass)

### ISSUE THREAD

**Issue by blortox** [snipe/snipe-it#2313]
#### Expected Behavior (or desired behavior if a feature request)

when all the settings are correct in snipe/app/config/production/mail.php i am able to send an email without specifying a username and password (This is not needed for us), however we don't even see an email being sent out in /var/log/maillog.

- What OS and web server you're running Snipe-IT on
centos 7.2 base
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual
- If you're getting an error in your browser, include that error
none, says that it worked correctly
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
snipe.rtap.net/auth/forgot-password (Snipe.rtap.net is our internal FQDN)

**Comment by stevecookms** [comment]
I was able to get it working without specifying a username/password.

What method are you using to send mail? smtp? sendmail?

**Comment by blortox** [comment]
I believe it's using sendmail (Thats what is specified in the mail.php file.)

I seem to have set everything correct in the config file.

**Comment by stevecookms** [comment]
I believe you need to configure the .env file in the root folder

**Comment by blortox** [comment]
I'm using v2, not v3 @stevecookms.

I believe the .env file is new and exclusive to v3.

**Comment by snipe** [comment]
https://laravel.com/docs/4.2/mail#configuration

Try changing the driver to mail

**Comment by blortox** [comment]
Thanks @snipe this seems to have worked.

Now i need to sort out auth errors on our MX :+1:

**Comment by ajaykools** [comment]
Test mail is not delivering to reception (But mail sent successfully)

config/mail.php:
'driver' = 'mail' # (installed mailutils)
username = '' # (bcoz mail relay)
password = '' # (bcoz mail relay)

1. I installed and running in docker
2. No error browser console & UI
3. I'm testing "Send Test" button in admin/setting page.

![image](https://user-images.githubusercontent.com/757395/57792822-8cd5da80-775d-11e9-953e-9459f21399c4.png)


What am I missing here?
