### ISSUE TITLE
Ldap users get blank page on login

### ISSUE THREAD

**Issue by Alsoongit** [snipe/snipe-it#2314]
#### Expected Behavior (or desired behavior if a feature request)

user is logged in and dashboard is displayed

-----

#### Actual Behavior

user uses active directory credentials and clicks login receives blank screen.
Apache acceess log indicates
"POST /login HTTP/1.1" 200 203 "http://SANATIZED/login" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
Debian/Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Install.sh
- If you're getting an error in your browser, include that error
Blank Page on login with ldap accounts, local accoutns work fine,.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Login
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
unable
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
have not.

**Comment by snipe** [comment]
Have you enabled debug mode? Is this is a fresh install, or an upgrade? Can you confirm that the directory permissions on your `storage` directory are such that those directories are writeable by your web server? 

You'll need to tail the laravel.log file. There is a lot of debugging output for LDAP connections that should help you see what's happening.

**Comment by Alsoongit** [comment]
I have not enabled debug mode yet.  It is a fresh install.  Here is a tail of laravel of a user attempting to login.

[2016-07-25 15:57:27] production.DEBUG: Binding user to LDAP.
[2016-07-25 15:57:27] production.DEBUG: Local user SANATIZED does not exist
[2016-07-25 15:57:27] production.DEBUG: Creating local user SANATIZED
[2016-07-25 15:57:27] production.DEBUG: Could not create user.{"username":["The username has already been taken."]}
[2016-07-25 15:58:00] production.DEBUG: LDAP is enabled.
[2016-07-25 15:58:00] production.DEBUG: Local auth lookup complete
[2016-07-25 15:58:00] production.DEBUG: Binding user to LDAP.
[2016-07-25 15:58:00] production.DEBUG: Local user SANATIZED does not exist
[2016-07-25 15:58:00] production.DEBUG: Creating local user SANATIZED
[2016-07-25 15:58:00] production.DEBUG: Could not create user.{"username":["The username has already been taken."]}

**Comment by snipe** [comment]
Is it possible you have a deleted user with that username already in your database?

**Comment by Alsoongit** [comment]
A show deleted users has no results.

**Comment by Alsoongit** [comment]
Just to check I 777'd the storage folder and had the user retry and still blank.

**Comment by Alsoongit** [comment]
I did not sanitize the last line of the laravel tail has "username" shouldn't that be the users actual username?

**Comment by Alsoongit** [comment]
When I login using my user created at install the laravel log tail shows the following :+1: 
[2016-07-25 16:45:29] production.DEBUG: Local user SANATIZED.USER exists in database. Authenticating existing user against LDAP.
[2016-07-25 16:45:29] production.DEBUG: Valid LDAP login. Updating the local data.
[2016-07-25 16:45:29] production.DEBUG: Authenticating user against database.

**Comment by Alsoongit** [comment]
If I delete the LDAP imported user account and create it via the web gui then the user is able to login and the laravel log shows valid ldap login.

**Comment by Alsoongit** [comment]
Creating the users locally is not really working for me.  Any recommendations on how to further troubleshoot the ldap import?

**Comment by snipe** [comment]
What version of Snipe-IT are you running?

**Comment by Alsoongit** [comment]
System Information

Snipe-IT version	v3.0-ebc74a65
PHP Version	5.6.23-0+deb8u1
Laravel Version	5.2.39

**Comment by snipe** [comment]
Can you try pulling the latest from master?

**Comment by snipe** [comment]
I honestly don't know what's going on here. The query to figure out if the user exists locally is pretty straightforward. 

`$user = User::where('username', '=', Input::get('username'))->whereNull('deleted_at')->first();`

> I tried and failed several times to import ldap user but it failed pulling the usernames, until i changed the admin settings page to have username = userprincipalname and ldap authentication query = samaccountname. Then it imported everyone but the logins came up to blank pages

Did it actually create users though? It shouldn't have allowed users without usernames.

**Comment by Alsoongit** [comment]
It did not create the users until I changed user name field to userprincipalname then it populated a huge list of users but when they attempt to login they get a blank page, apche gives a 200 ok then a 203, and the laravel log shows ldap auth happening but then it attempts to create a local user.  

I think it may have to do with the way AD and the Snipe app views the username.  If in the ldap settings i have username set to samaaccount name it does not pull a username from AD.  If I change it to userprinciaplname it does pull a username and snipe builds users as first.last@domain.com but our AD auth isnt expecting the @domain.com

**Comment by snipe** [comment]
It still shouldn't fail with a blank screen, and it shouldn't fail on trying to create a user is that user doesn't actually exist. How is it that your AD isn't expecting that? That's how AD works. Your LDAP auth query should be `sAMAccountName=`

**Comment by snipe** [comment]
And username is almost always `samaccountname` in AD

**Comment by Alsoongit** [comment]
I just changed it back to samaccountname and with that it will not pull a username from AD.

**Comment by snipe** [comment]
Are you running your AD in any kind of weird environment? samaccountname is pretty standard.

**Comment by Alsoongit** [comment]
I'll give it a shot in the morning.  I left the office for the day.  I have
created quite a few assets already is it safe to pull master into
production.  I could spin up another machine if needed.  If it helps our AD
is older.  Still running on 2003.

**Comment by bruce2004x** [comment]
Hi, my issue is similar. I'm using the latest version, user are imported correctly from AD, but when they try to login in the boroserw says: "Error:  The username or password is incorrect" Checking Laravel log I can see (one example):


[2016-07-27 11:39:01] production.DEBUG: Local user darwin.leguizamon exists in database. Authenticating existing user against LDAP.  
[2016-07-27 11:39:01] production.DEBUG: User darwin.leguizamon did not authenticate correctly against LDAP. Local user was not updated.  
[2016-07-27 11:39:01] production.DEBUG: Authenticating user against database.  
[2016-07-27 11:39:01] production.DEBUG: Local authentication failed.  

Any idea?

**Comment by IxFail** [comment]
If you are using V3 and Active Directory make sure to use the following settings:

Avtive Directory: `Checked`
LDAP Filter: `cn=*`
Username Field: `samaccountname`
Last Name: `sn`
LDAP Firstname: `givenname`
LDAP Authentication query: `samaccountname=`

Let me hear if that works.

**Comment by Alsoongit** [comment]
I was able to correct my issues.  It seems that due to my multiple failed attempts to import users the local database was a little wonky.  I bulk deleted all users, purged deleted records and then did a LDAP import with correct settings and all is well.  Thank you for your time and effort.  

One thing I would like, and perhaps this can be done, is more granular control over the users.  For example a department manager that can only view other users within their department and assets assigned to that department.  I understand there is full company support to restrict views but we already have multiple companies with multiple departments that need tracking for accounting.

Thanks again!  Keep up the good work.

**Comment by snipe** [comment]
Granular control over users is an existing feature request.

**Comment by bruce2004x** [comment]
@IxFail: Thanhs, the LDAP Authentication query parameter did the trick. After changed it as you said, it works inmediately!

Again, thnks..

**Comment by azuercher** [comment]
Hi,
I had similar problem when setting up LDAP against a MicroFocus eDirectory server.   I was getting blank \login page after auth.  the larval logs showed this:

[2016-11-07 10:27:21] production.DEBUG: LDAP is enabled.
[2016-11-07 10:27:21] production.DEBUG: Local auth lookup complete
[2016-11-07 10:27:21] production.DEBUG: Binding user to LDAP.
[2016-11-07 10:27:21] production.DEBUG: Local user testteacher does not exist
[2016-11-07 10:27:21] production.DEBUG: Creating local user testteacher
[2016-11-07 10:27:21] production.DEBUG: Could not create user.{"first_name":["The first name field is required."]}

After reviewing this thread I changed the First Name attribute in my ldap settings from "givenName" to "givenname" and that seems to have fixed the problem.  

Aaron

**Comment by realbreed** [comment]
I can confirm what Aaron found in trying to switch LDAP to use AD UPN instead of samaccountname. In all cases, these attributes need to be lower case. I tried and failed with userPrincipalName and lowering the case both for uid and the query worked.

**Comment by rajeshkumargond** [comment]
==> error_log <==
[Tue Dec 26 15:18:40.477517 2017] [:error] [pid 5487] [client 10.31.32.219:39678] PHP Catchable fatal error:  Argument 1 passed to LAM\\LOGIN\\display_LoginPage() must be an instance of LAMConfig, null given, called in /var/www/html/lam/templates/login.php on line 609 and defined in /var/www/html/lam/templates/login.php on line 178

==> access_log <==
10.31.32.219 - - [26/Dec/2017:15:18:40 +0530] "GET /lam/templates/login.php HTTP/1.1" 500 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36"
10.31.33.237 - - [26/Dec/2017:15:21:04 +0530] "GET /lam/ HTTP/1.1" 200 316 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"

**Comment by rajeshkumargond** [comment]
not able to login ldap account maneger... showing the above arror in error log....please help

**Comment by snipe** [comment]
@rajeshkumargond I have no idea what this means. `/var/www/html/lam/templates/login.php` is not a path used in Snipe-IT. I'm guessing this is a different app.
