### ISSUE TITLE
Asset maintenance type goes blank after saving

### ISSUE THREAD

**Issue by korio77** [snipe/snipe-it#2316]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

---
#### Please confirm you have done the following before posting your bug report:
- [y ] I have enabled debug mode
- [ y] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running v3.0-ebc74a65
- What OS and web server you're running Snipe-IT on Windows Server 2012 with IIS 8
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual
- If you're getting an error in your browser, include that error 
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error /admin/asset_maintenances
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. Just one error on one font load, dont think its related.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. No errors during update
- Indicate whether or not you've manually edited any data directly in the database. No manual edits.

Here you choose the maintenance type
![image](https://cloud.githubusercontent.com/assets/20576635/17132007/2ceccdc2-5320-11e6-9df3-f10689a8eb68.png)

When you hit save, yo go to this view

![image](https://cloud.githubusercontent.com/assets/20576635/17132041/518e6eba-5320-11e6-8a91-c31731a96c77.png)

And if you hit edit in that maintenance

![image](https://cloud.githubusercontent.com/assets/20576635/17132060/634b7148-5320-11e6-95b3-48074b3ee3d8.png)

If you need more info just tell me!

**Comment by dmeltzer** [comment]
This has something to do with how the translations are handled I think, I can't reproduce using english, but I can if I switch to spanish.

**Comment by korio77** [comment]
Just an update, its happening on the latest version of snipeit Version v3.6.2 build 10 (g927a12f)
