### ISSUE TITLE
*Change request* - Include Asset Tag information in Components view

### ISSUE THREAD

**Issue by mmcleod82** [snipe/snipe-it#2317]
When you click on components, it shows you all the assets with this component assigned. However, it only displays asset name and not the asset tag. So unless you give asset names to all assets, which we do not, you can't easily see which asset has it :)

Could you add the information in, much like the change you made on the component assignment drop down ?

![capture](https://cloud.githubusercontent.com/assets/19797176/17135658/be20f68a-5328-11e6-883e-bfbf285a4ff6.PNG)

**Comment by pako-pl** [comment]
+1
