### ISSUE TITLE
One company, two different sets of data

### ISSUE THREAD

**Issue by alomanto** [snipe/snipe-it#2320]
This is not a bug, more of a question to see if this is possible, or will be possible in V3.

 Have separate "groups" of assets that are able to be admin'd by different admin teams, where one team cannot edit the other's assets. For example, one set of assets that are for IT, and another set of assets for a field office. I know that this is probably best handled by using a completely separate instance of Snipe-IT, but I wanted to rule this configuration out if it's not possible first.

A crappy diagram of what i'm trying to convey:

-Snipe-IT Install
   |
   |___ Data Set 1
   |
   |___ Data Set 2

Thank you!

**Comment by snipe** [comment]
Sounds like you want to use something like full company support. https://snipe-it-manual.readme.io/docs/full-company-support
