### ISSUE TITLE
Unable to edit or create new assets

### ISSUE THREAD

**Issue by bioldame** [snipe/snipe-it#2325]
I recently updated to snipe 3 and today I noticed I can't modify existing assets or create new ones. I'm able to check out/check in assets and even other actions.

#### Expected Behavior (or desired behavior if a feature request)

Create new assets

-----

#### Actual Behavior

After clicking the "Save" button it just reloads the create asset form and it doesn't create the asset

-----

#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode
- [ x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: 3.0
- What OS and web server you're running Snipe-IT on: Windows Server 2008 R2 Enterprise
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual
- If you're getting an error in your browser, include that error: No Error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: "/hardware/create"
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Can we please see the most recent contents of your `storage/logs/laravel.log`

**Comment by bioldame** [comment]
[2016-07-26 19:44:07] production.ERROR: exception 'BadMethodCallException'
with message 'Method [validateANY] does not exist.' in
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Validation\Validator.php:3265
Stack trace:
#0
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(485):
Illuminate\Validation\Validator->__call('validateANY', Array)
#1
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(485):
Illuminate\Validation\Validator->validateANY('_snipeit_imei',
'355448072746854', Array, Object(Illuminate\Validation\Validator))
#2
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Validation\Validator.php(425):
Illuminate\Validation\Validator->validate('_snipeit_imei', 'ANY')
#3 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(5516):
Illuminate\Validation\Validator->passes()
#4 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(5695):
Illuminate\Foundation\Http\FormRequest->validate()
#5 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1494):
Illuminate\Foundation\Providers\FoundationServiceProvider->Illuminate\Foundation\Providers\{closure}(Object(App\Http\Requests\AssetRequest),
Object(Illuminate\Foundation\Application))
#6 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1479):
Illuminate\Container\Container->fireCallbackArray(Object(App\Http\Requests\AssetRequest),
Array)
#7 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1319):
Illuminate\Container\Container->fireResolvingCallbacks('App\\Http\\Reques...',
Object(App\Http\Requests\AssetRequest))
#8 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1874):
Illuminate\Container\Container->make('App\\Http\\Reques...', Array)
#9 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(7933):
Illuminate\Foundation\Application->make('App\\Http\\Reques...')
#10 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(7922):
Illuminate\Routing\ControllerDispatcher->transformDependency(Object(ReflectionParameter),
Array, Array)
#11 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(7916):
Illuminate\Routing\ControllerDispatcher->resolveMethodDependencies(Array,
Object(ReflectionMethod))
#12 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9480):
Illuminate\Routing\ControllerDispatcher->resolveClassMethodDependencies(Array,
Object(App\Http\Controllers\AssetsController), 'postCreate')
#13 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9461):
Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\AssetsController),
Object(Illuminate\Routing\Route), 'postCreate')
#14 [internal function]:
Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\Authenticate.php(45):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 [internal function]:
App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request),
Object(Closure))
#18 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9953):
call_user_func_array(Array, Array)
#19 [internal function]:
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 [internal function]:
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9938):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9462):
Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9449):
Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\AssetsController),
Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request),
'postCreate')
#25 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8517):
Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route),
Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'postCreate')
#26 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8504):
Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#27 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8218):
Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#28 [internal function]:
Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30
C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckPermissions.php(27):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]:
App\Http\Middleware\CheckPermissions->handle(Object(Illuminate\Http\Request),
Object(Closure), 'assets.view')
#32 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9953):
call_user_func_array(Array, Array)
#33 [internal function]:
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\Authenticate.php(45):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]:
App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request),
Object(Closure))
#37 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9953):
call_user_func_array(Array, Array)
#38 [internal function]:
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckLocale.php(40):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]:
App\Http\Middleware\CheckLocale->handle(Object(Illuminate\Http\Request),
Object(Closure))
#42 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9953):
call_user_func_array(Array, Array)
#43 [internal function]:
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(3225):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]:
Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request),
Object(Closure))
#47 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9953):
call_user_func_array(Array, Array)
#48 [internal function]:
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13139):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 [internal function]:
Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request),
Object(Closure))
#52 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9953):
call_user_func_array(Array, Array)
#53 [internal function]:
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#55 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13076):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 [internal function]:
Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request),
Object(Closure))
#57 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9953):
call_user_func_array(Array, Array)
#58 [internal function]:
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#60 [internal function]:
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#61 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9938):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#62 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8219):
Illuminate\Pipeline\Pipeline->then(Object(Closure))
#63 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8210):
Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route),
Object(Illuminate\Http\Request))
#64 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8200):
Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#65 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(2419):
Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#66 [internal function]:
Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#67
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#68
C:\inetpub\wwwroot\snipe-it\vendor\barryvdh\laravel-debugbar\src\Middleware\Debugbar.php(49):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 [internal function]:
Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request),
Object(Closure))
#70 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9953):
call_user_func_array(Array, Array)
#71 [internal function]:
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#73
C:\inetpub\wwwroot\snipe-it\vendor\fideloper\proxy\src\TrustProxies.php(46):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#74 [internal function]:
Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request),
Object(Closure))
#75 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9953):
call_user_func_array(Array, Array)
#76 [internal function]:
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#78 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckForSetup.php(22):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#79 [internal function]:
App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request),
Object(Closure))
#80 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9953):
call_user_func_array(Array, Array)
#81 [internal function]:
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#82
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#83 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\NosniffGuard.php(17):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#84 [internal function]:
App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request),
Object(Closure))
#85 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9953):
call_user_func_array(Array, Array)
#86 [internal function]:
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#87
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#88
C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\XssProtectHeader.php(17):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#89 [internal function]:
App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request),
Object(Closure))
#90 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9953):
call_user_func_array(Array, Array)
#91 [internal function]:
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#92
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#93 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\FrameGuard.php(17):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#94 [internal function]:
App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request),
Object(Closure))
#95 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9953):
call_user_func_array(Array, Array)
#96 [internal function]:
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#97
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#98 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13400):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#99 [internal function]:
Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request),
Object(Closure))
#100 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9953):
call_user_func_array(Array, Array)
#101 [internal function]:
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#102
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#103 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(11943):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#104 [internal function]:
Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request),
Object(Closure))
#105 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9953):
call_user_func_array(Array, Array)
#106 [internal function]:
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#107
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#108 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(3286):
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#109 [internal function]:
Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request),
Object(Closure))
#110 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9953):
call_user_func_array(Array, Array)
#111 [internal function]:
Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#112
C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#113 [internal function]:
Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#114 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9938):
call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#115 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(2366):
Illuminate\Pipeline\Pipeline->then(Object(Closure))
#116 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(2350):
Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#117 C:\inetpub\wwwroot\snipe-it\public\index.php(55):
Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#118 {main}

**Comment by snipe** [comment]
Can I see the contents of your custom fields table?

**Comment by bioldame** [comment]
[image: Inline image 1]

**Comment by bioldame** [comment]
![fields](https://cloud.githubusercontent.com/assets/10458507/17154042/5c6465e2-534d-11e6-8a02-cfe58cbf4c13.jpg)

**Comment by snipe** [comment]
I need the contents of the DB table, not the screen

**Comment by bioldame** [comment]
![db2](https://cloud.githubusercontent.com/assets/10458507/17154206/fa943eae-534d-11e6-8045-ca23d34ce17f.jpg)
![db](https://cloud.githubusercontent.com/assets/10458507/17154205/fa936bbe-534d-11e6-908e-532b84b89a01.jpg)

**Comment by snipe** [comment]
Did you grab the release, or latest from master? I think we have migration that should have fixed that out on master.

**Comment by bioldame** [comment]
I just double checked and I downloaded from /snipe/snipe-it/releases 

I believe that was the master

**Comment by snipe** [comment]
Can you grab the latest from master, please? The releases page is a snapshot of when that code was released, and we've made a few changes since then.

Be sure to run `php artisan migrate` after you pull from master.

**Comment by bioldame** [comment]
The format on the custom field were changed to regex:/^ANY$/ after 3.0 update. I updated them myself to ANY on the db

**Comment by snipe** [comment]
The point is that I wanted to see if that migration actually fixed your problem. :-/

**Comment by bioldame** [comment]
All fixed!!!! Downloaded the master and ran php artisan migrate

THANKS A MILLION

**Comment by snipe** [comment]
![dancing-man](https://cloud.githubusercontent.com/assets/197404/17156348/37f53fba-533e-11e6-91f6-ce5f5664ad3c.gif)

**Comment by monikasuneja** [comment]
I am facing the same issue after upgrading to version 3.0. I am running snipeit on ubuntu 14.04. Can you please share the link to download the master setup?

**Comment by dmeltzer** [comment]
Are you on 3.0 or 3.2?  It is fixed in the version 3.2 release found on the download page.

**Comment by woerdehoff** [comment]
Slightly different issue but php artisan migrate worked for me too!
