### ISSUE TITLE
Cloudflare SSL

### ISSUE THREAD

**Issue by Fyb3roptik** [snipe/snipe-it#2328]
#### Expected Behavior (or desired behavior if a feature request)

Content to be served via HTTPS

---
#### Actual Behavior

mixed-content not serving because of the CF reverse proxy

---
#### Please confirm you have done the following before posting your bug report:
- [Y] I have enabled debug mode
- [Y] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running - Latest stable as of this writing (not sure)
- What OS and web server you're running Snipe-IT on - apache2 ubuntu 14.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual

I am unable to use the Cloudflare SSL cert. I still get content served over http. How can I fix this? I added the CF ip's to the proxies list and enabled mod_proxy. Added the needed items in this docu:

https://snipe-it.readme.io/docs/reverse-proxies

**Comment by snipe** [comment]
What are you putting in the `APP_TRUSTED_PROXIES` environmental variables?

**Comment by snipe** [comment]
(If you add all of these, does it still fail? https://www.cloudflare.com/ips-v4 )

**Comment by krm1337** [comment]
Hello. I have almost the same problem. I can't access snipe-it because of CloudFlare's reverse proxy. Installed via github, added cloudflare IP's in the .env, still not able to access snipe it. (URL doesn't serve)I'm on Ubuntu 18x, apache2
Thank you

**Comment by brandon-barnes** [comment]
I am trying to get snipe-it to work using cloudflare tunnels. The webUI loads but I don't see any data. I have added all of cloudflare's IP to my .env file. What am I missing?

**Comment by najirod** [comment]
> I am trying to get snipe-it to work using cloudflare tunnels. The webUI loads but I don't see any data. I have added all of cloudflare's IP to my .env file. What am I missing?

@brandon-barnes - hi, i have the same problem with snipeit and Cloudflare tunnel.. did you resolve it?

**Comment by brandon-barnes** [comment]
> > I am trying to get snipe-it to work using cloudflare tunnels. The webUI loads but I don't see any data. I have added all of cloudflare's IP to my .env file. What am I missing?
> 
> @brandon-barnes - hi, i have the same problem with snipeit and Cloudflare tunnel.. did you resolve it?

Unfortunately not.

**Comment by Mongstaen** [comment]
Can this be reopened? Having the same experience that is mentioned above. Ui and app loads, can store to the database but not load any data from the database. 

Using Cloudflare tunnel, to Ubuntu Server 22.04, and the install script.

**Comment by Scarprovider** [comment]
Hi, same problem here with snipe-IT and Cloudflare Tunnels. @Mongstaen @najirod @brandon-barnes 

I tried with the Debug_Mode=True but returns me no error..this is really weird.

**Comment by Parracite** [comment]
@Scarprovider I ended up needing to put the below in my .env file
 
Name: APP_TRUSTED_PROXIES
Value: REMOTE_ADDR

Note it means exactly "REMOTE_ADDR" the problem I kept running into was replacing that with actual IP addresses.

It works perfectly behind a Cloudflared tunnel due to that.

**Comment by Scarprovider** [comment]
@Parracite  Works, you are the real MVP!  Thank you a lot

**Comment by EngelenH** [comment]
So this is still causing me grief, could someone explain how the working environment file should look? And what to set on the cloudflare side?
