### ISSUE TITLE
i upgrade to v 3 but i face this error in error log of apache (T_VARIABLE) or '{' or '$' in /var/www/html/snipe-it-3.0/public/index.php on line 51

### ISSUE THREAD

**Issue by umerafridi** [snipe/snipe-it#2329]
I crate to separate virtual host of snipeit v 3  but i face the error kindly help me 
(T_VARIABLE) or '{' or '$' in /var/www/html/snipe-it-3.0/public/index.php on line 51

#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Can you paste your index.php file here please?

**Comment by umerafridi** [comment]
Which index.php file .The file which I use in the previous version

**Comment by snipe** [comment]
?

If the error is happening on `/var/www/html/snipe-it-3.0/public/index.php`, that's the one I need to see.

**Comment by umerafridi** [comment]
This is the error in apache log file  PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/html/snipe-it-3.0/public/index.php on line 51

**Comment by umerafridi** [comment]
assetmnmt1.seecs.com is currently unable to handle this request.
500

**Comment by umerafridi** [comment]
i also set the permission but problem is still there please help me

**Comment by snipe** [comment]
I cannot help you until you paste the index.php here

**Comment by umerafridi** [comment]
**
 * Laravel - A PHP Framework For Web Artisans
 *
 * @package  Laravel
 * @author   Taylor Otwell <taylorotwell@gmail.com>
 */

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader for
| our application. We just need to utilize it! We'll simply require it
| into the script here so that we don't have to worry about manual
| loading any of our classes later on. It feels nice to relax.
|
*/

require __DIR__.'/../bootstrap/autoload.php';
include '../c3.php';

/*
|--------------------------------------------------------------------------
| Turn On The Lights
|--------------------------------------------------------------------------
|
| We need to illuminate PHP development, so let us turn on the lights.
| This bootstraps the framework and gets it ready for use, then it
| will load up this application so that we can run it and send
| the responses back to the browser and delight our users.
|
*/

$app = require_once __DIR__.'/../bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run The Application
|--------------------------------------------------------------------------
|
| Once we have the application, we can handle the incoming request
| through the kernel, and send the associated response back to
| the client's browser allowing them to enjoy the creative
| and wonderful application we have prepared for them.
|
*/

$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);

$response->send();

$kernel->terminate($request, $response);

**Comment by snipe** [comment]
What version of php are you using?

**Comment by umerafridi** [comment]
PHP 5.4.45 (cli) (built: Oct 16 2015 11:24:58) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

**Comment by snipe** [comment]
v3 requires PHP 5.5.9 or higher. 
https://snipe-it.readme.io/docs/requirements
https://snipe-it.readme.io/docs/upgrading
https://snipe-it.readme.io/v3.0/docs/common-issues#php-parse-error-syntax-error-unexpected-class-t_cl

**Comment by umerafridi** [comment]
Now I successfully upgrade the PHP to 5.6. Now I face the other error .PHP Fatal error: Class 'Patchwork\Utf8\Bootup' not found in \bootstrap\autoload.php on line 17 .which solutions are also provided in common issue but when I follow these steps I prompt this error Could not open input file: composer.phar

**Comment by umerafridi** [comment]
Please any update ?

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/common-issues#php-fatal-error-class-patchworkutf8bootup-not-foun

**Comment by umerafridi** [comment]
Could not open input file: composer.phar

**Comment by umerafridi** [comment]
Please any help ?

**Comment by umerafridi** [comment]
after entering this command  php composer.phar update --no-dev --prefer-source . i face the following error
PHP Fatal error:  Class 'Illuminate\Foundation\Application' not found in /var/www/html/snipe-it-3.0/bootstrap/app.php on line 14
Script php artisan clear-compiled handling the pre-update-cmd event returned with error code 255

**Comment by umerafridi** [comment]
Please, any help ?

**Comment by umerafridi** [comment]
Please, any help ?

**Comment by snipe** [comment]
@umerafridi Spamming a Github issue makes people not want to help you. It's enormously rude, not to mention that it's 4:30AM my time. 

Everyone here volunteers their time, and you are not owed anything by anyone. 

There are lots of suggestions on Google that exactly meet your query. Rather than spamming the Github Issues, perhaps you could use that time searching for an answer. 

Per some of the google results, you can try running `composer update --no-scripts` (or `composer.phar update --no-scripts`)

**Comment by umerafridi** [comment]
Can't Find any solution on google please help

PHP Fatal error:  Class 'Illuminate\Foundation\Application' not found in /var/www/html/snipe-it-3.0/bootstrap/app.php on line 14
Script php artisan clear-compiled handling the pre-update-cmd event returned with error code 255
