### ISSUE TITLE
Dashboard appearance modification

### ISSUE THREAD

**Issue by alexlazer114** [snipe/snipe-it#2331]
Hi Snipe,

Thanks for a wonderful application which will be handy for the IT administrators to keep track of the Assets & SW license details.

Can you please help me in modifying the appearance of the Dashboard by editing few lines in the code & and also to make few changes in taking the custom asset report.

Thanks,
Alex L

- Version of Snipe-IT you're running : v3.0.0-dev-3-g6d810a9
- What OS and web server you're running Snipe-IT on : CentOS 6.8 & Httpd 2.2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) : manual installation
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
If you'd like to request a specific feature, please do so. I don't know what you're asking for here.
