### ISSUE TITLE
Unable to locate /var/www/snipeit/app/config and login to portal

### ISSUE THREAD

**Issue by chaitanyan123** [snipe/snipe-it#2332]
#### Expected Behavior (or desired behavior if a feature request)

Recently i have installed Snipe-IT in my Ubuntu-14.0 machine, to keep my asset information in our management tool. 

We need to login to the tool to keep our asset information and need to enable mail services in Snipe-IT to send mails to the users.
-----

#### Actual Behavior

After i have installed the tool, followed the steps i.e creating the user and updating database from web browser first time. Then, when i am trying to access the tool from web browser asking to login and provided username & password. But, getting incorrect username/password and i am sure that, i have used correct credentials.

Also, i am trying to configure email configuration followed in the steps given in http://docs.snipeitapp.com/installation/configuration.html. But, as per documentation it is guiding to edit the **"app/config/production/mail.example.php"** and in my machine i am not able to identify the **"config"** directory in **"/var/www/snipeit/app
![login](https://cloud.githubusercontent.com/assets/20687774/17186537/4d66e450-5453-11e6-9fcb-0536e7230e65.jpg)
![config](https://cloud.githubusercontent.com/assets/20687774/17186550/59ba0a70-5453-11e6-9fc2-bbfec685db42.jpg)

"**.
-----

#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode
- [ _/] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on 
 **Ubuntu 14.0**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
**install.sh**
- If you're getting an error in your browser, include that error
 **Error: The username or password is incorrect.** 
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Those are the docs for v2.0. You need the docs at https://snipe-it.readme.io
