### ISSUE TITLE
Offline Upgrade

### ISSUE THREAD

**Issue by DaddyW123** [snipe/snipe-it#2334]
We are currently using a 2.x version.  I want to go to 3 and was successful at updating my test copy.  But my test copy is internet connected.  Our production copy is in a closed lab.  I always try to mimic my closed lab environment so I reverted back my snapshot and did the test upgrade again, only with my NIC disconnected this time.  I had manually downloaded the tar.gz file for 3.0 and I manually downloaded composer.phar beforehand.  

When I try to run "php composer.phar install --no-dev --prefer-source" it attempts to download and install multiple packages from the internet (namely github).

Is there a way of upgrading composer (and ultimately Snipe) completely offline?  I'd hate to have to update my live copy, export the VM, backup my production database, import the new VM into the closed environment, then reconfigure all of the LDAP settings that I have in lab, re-import all of the users from AD, then re-import all of the data from the old VM.  That's a lot of work to do an upgrade.  Or am I over complicating it?

Thanks

**Comment by snipe** [comment]
You might be able to get away with just copying the vendor directory over to the closed system.
