### ISSUE TITLE
Component cannot be unassigned from an asset

### ISSUE THREAD

**Issue by pako-pl** [snipe/snipe-it#2336]
Once I assign a component to an asset, there is no way to change the assigned number or delete the assignment and reassign the component to a different asset. I couldn't find the needed options anywhere.

**Comment by snipe** [comment]
Yes, that's a known issue. We're working on it.

**Comment by mmcleod82** [comment]
Just noticed this ourselves :/

**Comment by nathank1989** [comment]
Along similar lines, I noticed that components value remains at 0 in the Asset page regardless of values

**Comment by uberclokr** [comment]
Any word on this? I've just been trying out the software and hoping to adapt it for use by my employer. The components feature would be immensely useful for us, but only if we are able to reclaim them.

**Comment by arsen0** [comment]
In which stable release will that be included ?
