### ISSUE TITLE
Checkin time is not saved

### ISSUE THREAD

**Issue by zjean** [snipe/snipe-it#2341]
#### Expected Behavior (or desired behavior if a feature request)

When checking in an asset the time of checkin is requested and saved.
When left empty, Now is used.

When an asset is checked in/out multiple times a day, the history is not clear and sorted any more because the check in times are missing.

-----

#### Actual Behavior

Only the date is asked. The time is stored as 00:00:00.
When clearing the date field, the time is today's date and time are stored.

-----

#### Please confirm you have done the following before posting your bug report:

- [V] I have enabled debug mode
- [V] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running master
- What OS and web server you're running Snipe-IT on Windows, PHP 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc). Manual
- If you're getting an error in your browser, include that error.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error. Check in asset.
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). Yes
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by fredno** [comment]
I had the same problem after I upgraded to V3. For me it was a timezone issue in the .env file. There was a problem with the quotation marks. I ended up removing them before i wrote them again. Everything worked fine now.
APP_TIMEZONE='Europe/Oslo'

**Comment by zjean** [comment]
Thanks @fredno , I will try it tonight.
Strange thing is that it also happens on the demo environment. I would expect that to be configured correctly :)

**Comment by snipe** [comment]
How's that? This is from the demo:

<img width="975" alt="screen shot 2016-07-28 at 3 27 37 am" src="https://cloud.githubusercontent.com/assets/197404/17210834/2b6dfe8e-547a-11e6-88fc-053489d82a41.png">

**Comment by jwdhaan** [comment]
No idea ;)
I reproduced it:
Created asset with tag 'my123' on the demo environment.
I checked it out to John Doe without entering an expected check in date.
After that, I did a check in without touching the checkin date field.
this is my result:

![image](https://cloud.githubusercontent.com/assets/12495886/17211258/b166bb40-54c8-11e6-9621-0b9c4fb1ac91.png)

**Comment by snipe** [comment]
If you pick a date, it will default to midnight because it's a date time field, and it needs some value for hours:minutes:seconds

**Comment by mmcleod82** [comment]
same in my environment (V3 final), checkin without changing date - midnight stored as time.

![capture](https://cloud.githubusercontent.com/assets/19797176/17213583/d7de8fb0-54cc-11e6-9e83-c19a26988ac9.PNG)
