### ISSUE TITLE
Licenses empty after upgrade to 3.0

### ISSUE THREAD

**Issue by armandw** [snipe/snipe-it#2342]
After upgrading to 3.0, my licenses are gone. The dashboard shows a number of 409 licenses, but the licenses view is empty. The database migration was succesful and I can see all my assets.

I did not find the answer in the common issues. I'm running on PHP 5.6 for Windows with MySQL (MariaDB).

I can see the licenses directly in the licenses and license_seat tables, so the data is still there.

Error message in laravel.log:
exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function App\Http\Controllers\mb_strimwidth()' in C:\inetpub\wwwroot\snipe-it\app\Http\Controllers\LicensesController.php:991
Stack trace:
#0 {main} 

Thank you in advance for any tips.

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
That's helpful log info. That's a native PHP function, so the only reason I can think of for it not to know that function is if you don't have mbstring installed/enabled: 

http://php.net/manual/en/function.mb-strimwidth.php
http://php.net/manual/en/book.mbstring.php

**Comment by armandw** [comment]
That worked, thank you very much!
