### ISSUE TITLE
Line breaks displayed as HTML tag in licensing product key field

### ISSUE THREAD

**Issue by hoolius** [snipe/snipe-it#2344]
#### Expected Behavior (or desired behavior if a feature request)

Insert a line break in display.

-----

#### Actual Behavior

HTML tag <br /> is shown instead of a line break.

-----

- Snipe v3.0
- localhost/admin/licenses/1/view
- Issue is reproducible in demo as well
![linebreak](https://cloud.githubusercontent.com/assets/6681963/17212523/765bbc9a-5495-11e6-8eed-2c13aad063be.png)

**Comment by dmeltzer** [comment]
This is actually in the product key field, not the notes.
