### ISSUE TITLE
Install Error - ...your DocumentRoot is set incorrectly. It should be set to the public directory."

### ISSUE THREAD

**Issue by cdjudea** [snipe/snipe-it#2348]
#### Expected Behavior (or desired behavior if a feature request)

I did all steps related to installation. I use wamp.

-----

#### Actual Behavior

I create the project in wamp/www. I have also  some other projects in the folder including a wordpress intranet website.

-----

#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode
- [yes ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT 3.0
- Wamp 3.0
- I did a manual installation (prerequisite including create a database ) but cannot access the Snipe-IT installation.
The error i get is 
"**D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory."

My virtual hosts create with wamp look like 

<VirtualHost *:80>
 	DocumentRoot "c:\wamp64\www"
	ServerName snipeit
	ServerAlias www.localhost\snipeit.com
	<Directory "c:\wamp64\www\snipeit\public">
		Allow from all
		Require all granted
        AllowOverride All
		Options +Indexes
 </Directory>
</VirtualHost>

My DocumentRoot in httpd.conf:

DocumentRoot "C:/wamp64/www/"
...
...
`<Directory "C:/wamp64/www/">
    AllowOverride none
    Order deny,allow
</Directory>`

Why www folder is not working and does not let me proceed with the installation?
All other scripts and wordpress sites are working great no issue with my wamp configuration. For my understanding the director is already in public folder. What I did wrong?

**Comment by snipe** [comment]
The title of your issue tells you what the problem is. The document root needs to be the public directory.

**Comment by kishfash** [comment]
Hi @snipe .

I'm having the same issue while upgrading Spine-IT from v2.1.0-41 to version 3.0. I'm using Wamp.

Please i need step to set Documentroot to public on Wamp server. 

Please note, i'm running other application on the wamp server as well.

Thank you
