### ISSUE TITLE
Multiple Company Support - locations not tied to / limited to companies 

### ISSUE THREAD

**Issue by RobMSP** [snipe/snipe-it#2353]
#### Expected Behavior (or desired behavior if a feature request)

When locations are created they are not assigned to companies, without this relationship information regarding multiple companies locations is visible between companies. 

When an asset is edited or created it can be assigned to any location, but locations should be tied to a company. 

A user for company A should not be able to edit an asset and assign it to a location belonging to company B.

A user for company A should not be able to see locations belonging to company B.
#### Actual Behavior

When a user is accessing the system in 'full multiple company support' mode enabled all locations are visible, including locations that have no relationship to the company their account is associated with.

When a asset is edited all locations are visible to all users, locations cannot specify a specific company. 
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running
  v3.0-67-gf31637a
- What OS and web server you're running Snipe-IT on
  Ubuntu 14.04 lts
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  install.sh

**Comment by RobMSP** [comment]
I would be very anxious and would be willing to pay a small reward via paypal for the completion of this feature request. 

Basically  I need to from a Company Screen assign access to 'locations' 

So User at Company A could only see locations for Company A and not any other locations.

From my perspective it would be better if the Company then Tagged Locations as valid, this way locations could be reused across two or more companies but that is not a requirement.

Locations where 'locations' information is exposed to a user: 

https://snipe/hardware/create
https://snipe/hardware/*/edit
https://snipe/admin/components/create 
https://snipe/admin/components/*/edit
https://snipe/admin/consumables/create
https://snipe/admin/consumables/*/edit
https://snipe/admin/accessories/create
https://snipe/admin/accessories/*/edit

My only solution is to not permit the users form company A to have any edit or create permissions.

**Comment by ConvexSERV** [comment]
+1 For this feature as well!

**Comment by schmidiij** [comment]
+1 for this feature!

**Comment by KroonIT** [comment]
+1 for this feature!

**Comment by Hsherif90** [comment]
+1 to this feature!

**Comment by Knightrain0** [comment]
+1 for this feature!

**Comment by namarie23** [comment]
+1 to this feature.

**Comment by MalteKiefer** [comment]
+1

**Comment by Omidoshegy** [comment]
+1 Please 🙏

**Comment by Saad-Samba** [comment]
+1

**Comment by khrishino** [comment]
+1 please

**Comment by catalunyati** [comment]
Absolutely, +1

**Comment by biernattmarcin** [comment]
+1. Needed functionality

**Comment by dreamer2038** [comment]
+1 please

**Comment by Steve-M-C** [comment]
This would be very useful, since at present, although you can restrict a user to only being able to view/edit assets at their assigned company, they are still able to see all the locations on the system - so could accidentally assign assets to the wrong locations.
