### ISSUE TITLE
i am seeing localhost/setup this causes a white screen, because i am not loading the application from local host

### ISSUE THREAD

**Issue by briansouth90** [snipe/snipe-it#2354]
#### Expected Behaviour (or desired behaviour if a feature request)

i was expecting this so use my sub-domain, i am accessing the from a VPN it is hosted on ubuntu 14.04LTS server. i see the link above and a white page.

i installed using the install.sh and migrated the DB using the seeder connection strings are correct and user was made and given privlages. 

it should be noted that the server is a HVM

.htaccess
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On
    RewriteBase /assets/public
    # Uncomment these two lines to force SSL redirect
    # RewriteCond %{HTTPS} off
    # RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
</IfModule>

-----

#### Actual Behaviour

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by briansouth90** [comment]
sorry what i expected to happen was see the main login page, and the address would be my.domain.com/setup

**Comment by briansouth90** [comment]
i have reinstalled the repo managed to run key:generate but i still cannot run app:install this is my output
 [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "app:install" is not defined.
  Did you mean one of these?
      migrate:install
      app:name

**Comment by snipe** [comment]
There is no app:install in v3. Please check the permissions of your `storage` directory and make sure it (and all sub folders) are writable, and provide us your error logs.

**Comment by briansouth90** [comment]
all of storage is chmod - R 777 (this is for testing and doesnt matter as no one outside of our VPN will access this). 

here is apache and laravel logs.

p.s sorry for late reply i dont work weekends and i am also from the UK.

[error.txt](https://github.com/snipe/snipe-it/files/393428/error.txt)
[laravel.txt](https://github.com/snipe/snipe-it/files/393429/laravel.txt)

**Comment by briansouth90** [comment]
from what i can see the my.domain.com/setup here is the error: The requested URL /setup was not found on this server.

s/setup doesnt seem to be able to find the setup.blade.php which is there in views

**Comment by briansouth90** [comment]
Ignore my comment above it looks like its a problem with either how ive done the .env or the .htaccess.
when i do my.domain.uk/index.php/setup it will load the set up page.

**Comment by briansouth90** [comment]
update once index.php was in the link eg /index.php i can navigate around but if i remove it  then its a 404 again

**Comment by snipe** [comment]
You shouldn't need index.php in the link - sounds like mod_reqrite may not be enabled for your web server.
