### ISSUE TITLE
Feature Request - Improve Asset 'order number' function

### ISSUE THREAD

**Issue by RobMSP** [snipe/snipe-it#2355]
#### Expected Behavior (or desired behavior if a feature request)

Feature Request

Create a document repository for order numbers, where orders or invoices can be stored. 
Then permit these to be referenced and tagged into the asset under the order number field. 

This would permit you to store copies of invoices within the asset management system, some vendors require original invoices to be provided for warranty purposes. 

Typically in our usage case when we place orders there is often dozens of assets on a single order. 

---

**Comment by aglasson** [comment]
It would be nice if this system could have the option to manage files in a windows file share. Such that it can track the documents in a directory by copying to and renaming the file name to a specific convention (eg. %ordernumbre%_%date%_%suppliername%.pdf) as to make those files available on a corporate network and not strictly requiring them to be available in Snipe IT.
Expectedly if any files got removed or renamed the link would break.

Just food for thought.
