### ISSUE TITLE
AD login does not work and LDAP import changes local users passwords

### ISSUE THREAD

**Issue by JvrJava** [snipe/snipe-it#2356]
#### Expected Behavior (or desired behavior if a feature request)

Importing with LDAP should allow users to log in with their LDAP credentials as indicated by the "Managed via LDAP" label in user profiles.

-----

#### Actual Behavior

LDAP users have to first send a forgot password email, change their password and then login instead of using their LDAP credentials. Also when LDAP sync is run again, users then have to reset their password again since LDAP import updates all the users passwords.

So this is two problems really:
1. LDAP does not authenticate users for some reason (not sure how to troubleshoot this)
2. Importing LDAP users also re-generates local database password

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.0-ebc74a65
 
- What OS and web server you're running Snipe-IT on
Windows Server 2012 r2

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual Install

- If you're getting an error in your browser, include that error

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
LDAP import, sync button

- If a stacktrace is provided in the error, include that too.

- Any errors that appear in your browser's error console.
None

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
Feature not available in demo

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
Here are some debug lines related to two users who are on LDAP, one that has not reset their password and my personal account that has had password reset (usernames are redacted):

[2016-07-29 09:58:01] production.DEBUG: LDAP is enabled.  
[2016-07-29 09:58:01] production.DEBUG: Local auth lookup complete  
[2016-07-29 09:58:01] production.DEBUG: Binding user to LDAP.  
[2016-07-29 09:58:01] production.DEBUG: Local user JD**** exists in database. Authenticating existing user against LDAP.  
[2016-07-29 09:58:01] production.DEBUG: User JD**** did not authenticate correctly against LDAP. Local user was not updated.  
[2016-07-29 09:58:01] production.DEBUG: Authenticating user against database.  
[2016-07-29 09:58:01] production.DEBUG: Local authentication failed.  
[2016-07-29 09:58:12] production.DEBUG: LDAP is enabled.  
[2016-07-29 09:58:12] production.DEBUG: Local auth lookup complete  
[2016-07-29 09:58:12] production.DEBUG: Binding user to LDAP.  
[2016-07-29 09:58:12] production.DEBUG: Local user JF******* exists in database. Authenticating existing user against LDAP.  
[2016-07-29 09:58:12] production.DEBUG: User JF****** did not authenticate correctly against LDAP. Local user was not updated.  
[2016-07-29 09:58:12] production.DEBUG: Authenticating user against database.  

- Include what you've done so far in the installation, and if you got any error messages along the way.
Originally we were running version 2 and were in the process of importing all the assets we have on campus. Yesterday I noticed that version 3 had been released as stable and has features that are highly valued. We decided to start fresh, so I dropped the Snipe-it database, manually installed snipe-it 3 and recreated a fresh database with the pre-flight and first step after that was to get LDAP functional.

- Indicate whether or not you've manually edited any data directly in the database
I learned my lessons with the first database and have not mucked around with the database since it got recreated.

**Comment by snipe** [comment]
When a user successfully auths against LDAP, their user data is updated locally, so their password is always synced up with the their LDAP password, so it doesn't matter if their password is regenerated when LDAP syncs. It just gets updated when they login anyway. LDAP users never need to use a forgotten password request - that's the whole point of logging in with LDAP.

If LDAP isn't authenticating users correctly, then that's just a matter tweaking your settings. If you can let us know what your LDAP/AD settings are, that would be a big help.

**Comment by JvrJava** [comment]
You are right on the money with asking about LDAP settings. I had to go to the system administrators to ask what settings would be ok for me to share and instead they recommended changing the LDAP authentication query from uid=samaccountname to samaccountname=. So as far as authentication goes everything is working great now.

Thanks for the great update! It looks and works great.
