### ISSUE TITLE
After Upgrade to v3 getting HTTP 500 Error

### ISSUE THREAD

**Issue by madmax01** [snipe/snipe-it#2358]
Hello,

i gone through the Upgrade Path. and after DB migration there where no sightable issues,......

 i tested going onto the webpage. but it didn't worked. HTTP 500 Error

Following INfos inside the SnipeIT.error.log

[client ip] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/html/snipeit/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied' in /var/www/html/snipeit/bootstrap/cache/compiled.php:13832\nStack trace:\n#0 /var/www/html/snipeit/bootstrap/cache/compiled.php(13762): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/snipeit/bootstrap/cache/compiled.php(13522): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/html/snipeit/bootstrap/cache/compiled.php(13620): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)\n#3 /var/www/html/snipeit/bootstrap/cache/compiled.php(13315): Monolog\\Logger->error(Object(UnexpectedValueException), Array)\n#4 /var/www/html/snipeit/bootstrap/cache/compiled.php(13286): Illuminate\\Log\\Writer->writeLog('error', Object(UnexpectedValueException), Array)\n#5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(57): Illuminate\\Log\\Writer->error in /var/www/html/snipeit/bootstrap/cache/compiled.php on line 13832
[Fri Jul 29 21:34:49.814046 2016] [:error] [pid 2894] [client ip] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/html/snipeit/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied' in /var/www/html/snipeit/bootstrap/cache/compiled.php:13832\nStack trace:\n#0 /var/www/html/snipeit/bootstrap/cache/compiled.php(13762): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/snipeit/bootstrap/cache/compiled.php(13522): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/html/snipeit/bootstrap/cache/compiled.php(13620): Monolog\\Logger->addRecord(400, Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#3 /var/www/html/snipeit/bootstrap/cache/compiled.php(13315): Monolog\\Logger->error(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#4 /var/www/html/snipeit/bootstrap/cache/compiled.php(13286): Illuminate\\Log\\Writer->writeLog('error', Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#5 /var/www/html/snipeit/vendor/laravel/frame in /var/www/html/snipeit/bootstrap/cache/compiled.php on line 13832

inside the .env all necessary infos placed.

Something i missed here?

Best regards

Max

**Comment by snipe** [comment]
` 'The stream or file "/var/www/html/snipeit/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied' `

Check the permissions on your storage directory and make sure it and its subdirectories are writable by the web server.

**Comment by madmax01** [comment]
Hi Snipe,

thx. overlocked that.

i did now fixed with:

sudo chown -R apache:apache /var/www/html/snipeit
sudo chmod -R 755 storage/
sudo chmod -R 755 public/uploads

many thx for Fast Hint ;)
