### ISSUE TITLE
Question: About reports

### ISSUE THREAD

**Issue by bruce2004x** [snipe/snipe-it#2360]
I have V3 installed. Some questions about reports:
1. Is there any way to create a report with ALL things (assets+licences+accesories) assigned to an specific user?
2. Is there any way to export reports in PDF format?
3. As happened on V2, when one tryies to export data (CSV, XML,JSON, etc), using Internet Explorer it just opens another tab in blank. I Solve this using mozilla, but I think it should work in IE
4. Is there any way to create a Custom report using a custom template?

I'm sure this questions help to improve this amazing app

Thanks in advance

**Comment by dmeltzer** [comment]
#3. Are you using the released version of v3 or something from git? We updated the js plugin that exports the data a few days ago, I have no idea if it fixes the issue, but it may.

**Comment by bruce2004x** [comment]
hi Dmeltzer, yes I'm using V3! Can you tell me where to find that plugin and how to install it?

**Comment by bruce2004x** [comment]
@dmeltzer , may you read my answer? Pls your help

**Comment by dmeltzer** [comment]
Hi,

It's in v3.2, does upgrading still present the same issues?

**Comment by bruce2004x** [comment]
Well, in fact, they arent issues, they are some kind of requests, again:

1. Is there any way to create a report with ALL things (assets+licences+accesories) assigned to an specific user?

2.Is there any way to export reports in PDF format?

3. Is there any way to create a Custom report using a custom template?

**Comment by dmeltzer** [comment]
I was asking about the #3 issue, the same one I have been talking about throughout.

Does upgraded to v3.2 fix the #3 issue? I don't have an easy way of testing it.
