### ISSUE TITLE
Possible typo in latest code?

### ISSUE THREAD

**Issue by urthecast-ayeung** [snipe/snipe-it#2361]
#### Expected Behavior (or desired behavior if a feature request)

Asset details should appear.

-----

#### Actual Behavior

[Sat Jul 30 16:17:33.416844 2016] [:error] [pid 19479] [client 10.0.150.24:50555] PHP Parse error:  syntax error, unexpected ''): ?>' (T_CONSTANT_ENCAPSED_STRING) in /var/www/html/snipeit/storage/framework/views/d01504e9d46044fae88019f80f1a9dde4862a43f.php on line 281, referer: http://snipe-it/hardware

Line 279 has this:
                   <?php if($asset->created_at!='''): ?>

Changing the triple quote to just two resolves the error, but not sure if that is a typo, I'm not a PHP expert!

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
Version v3.0-79-gfcb1d6a 
- What OS and web server you're running Snipe-IT on

CentOS Linux release 7.2.1511 (Core)

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

install.sh

- If you're getting an error in your browser, include that error
above
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
http://snipe-it/hardware
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by dmeltzer** [comment]
This is line 252 of hardware/view.blade.php

**Comment by snipe** [comment]
Stupid PHPStorm tries to be more clever than the developers :(
