### ISSUE TITLE
Feature request: Asset Accepted > generate to / print to PDF

### ISSUE THREAD

**Issue by rozowykubek** [snipe/snipe-it#2362]
#### Expected Behavior (or desired behavior if a feature request)

Hi,

**Desired behavior**
- it would be great to have a possibility to generate / print to  PDF ( or any other format )  accepted  asset delivery ( what assets, time and date of acceptance ) . I would see it in history tab of user profile ( see below screenshot  )
-  or at least  way to generate a report of given user history including delivered assets,  date of asset acceptance 

**Why**
-  seeing accepted assets only via Admin/user profile  isn't enough in case of lost or damaged equipment due to the fact that  direct supervisor / director has no way of seeing that
- hence  on demand PDF of  accepted asset delivery  or report so that supervisor can see that assets were delivered and accepted by user

![generatepdf](https://cloud.githubusercontent.com/assets/2656187/17276071/bd292d1c-571d-11e6-8508-206f4ba3d623.png)

**Comment by wilsonlspacheco** [comment]
+1 (hosted costumer))

**Comment by viclou** [comment]
+1 FD12850

**Comment by jannisokay** [comment]
+1

Currently we are using a Word template. With this integration this would simplify our workflow, as the user signs digitally for the asset anyway.
**It would be great if the date, the EULA, the delivered devices and the signature could be seen on the PDF document**.
