### ISSUE TITLE
Asset File Uploads Successfully But Not Shown In File List

### ISSUE THREAD

**Issue by rmgau** [snipe/snipe-it#2365]
#### Expected Behavior (or desired behavior if a feature request)
After successfully uploading a file to an asset, the file should be shown in the files list for that asset.

-----

#### Actual Behavior
The file successfully uploads and can be seen in the directory structure when in the host OS, however it isn't listed in Snipe-IT on the asset page.

There are no warnings thrown and the green bar at the top reports the file successfully uploaded (which it did). I can't find any logs anywhere showing any issues.

This is particularly odd as previous device uploads have worked as intended. With further testing, Assets 1-5 still upload fine, where as 6-14 do not. The only difference I am aware of is that I bulk edited 6-14 to update the company they were assigned to.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.0-32-gba25972
- What OS and web server you're running Snipe-IT on: Debian 8, Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Install.sh
- If you're getting an error in your browser, include that error: N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: /hardware/XXX/view
- If a stacktrace is provided in the error, include that too.: N/A
- Any errors that appear in your browser's error console. N/A
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): Cannot replicate
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.: I presume this is now storage/logs. My laravel file is empty.
- Include what you've done so far in the installation, and if you got any error messages along the way.: N/A
- Indicate whether or not you've manually edited any data directly in the database: No.

-----
Any help would be much appreciated.

Thanks

**Comment by rmgau** [comment]
Images of the upload success banner, missing from the list, and ls of the assets folder: https://imgur.com/a/RTvRC

I hope this is an easy one for you.

**Comment by rmgau** [comment]
I've worked out what was going on. My apologies for adding to your bug tracker.

For anyone else experiencing this, check to ensure your user isn't assigned to a company. Whilst I can see all the devices as a super admin, I can't see all the files.

**Comment by dmeltzer** [comment]
Do you have full multiple company support enabled? If not, this would still be an issue.  If so, things are indeed working as intended.

**Comment by rmgau** [comment]
I do.

I didn't understand that global admins were having this setting applied in this way. The fact that I could see all the assets lead me to believe I would be able to see all the files attached to the asset.

I worked it out when I realised all the files that wouldn't attach were from our sub-company.

Thanks for coming back to me.

**Comment by xP0se** [comment]
Hi Snipe,

I have same problem, all item/field under admin menu and all sub menu already filled. I also create many people/user then submit 2 asset. 
But why its not shown in Asset list??

The Snipe installed on my web hosting (i download from softaculous)
No one error during installation. All running normally during submit all data under Admin menu

Regards,
xP0se

**Comment by snipe** [comment]
@xP0se If you're having the same issue, please answer the question we asked of the OP. Do you have full multiple company support enabled?

**Comment by xP0se** [comment]
yes. its enabled now.
But i have tried in two ways..enabled and disabled..., and asset still not shown

**Comment by xP0se** [comment]
yes. its enabled now.
But i have tried in two ways..enabled and disabled..., and asset still not shown

**Comment by snipe** [comment]
I'd need screenshots and error logs to be able to dig deeper on this

**Comment by xP0se** [comment]
Hi Snipe,

I can't find any error on error log in my hosting.
Any error log in snipe?

Thanks

**Comment by xP0se** [comment]
Hi Snipe,

Its solved
I have changed php version in my hosting, after that snipe working fine.

One more question.... how to make a title ..for example "Asset Management
System" on login page?
And how make company logo in login page more bigger?

Thanks for your support

**Comment by xP0se** [comment]
Hi Snipe,

Its happen again...hahaha
Whats wrong with this??
I have submitted 1 asset...and it shown at Asset List
Then i set 1 asset more..and its not shown
I submit same data for  3 times, no error message when i click save but the
data not shown at Asset List

Many thanks in advance for your help

**Comment by snipe** [comment]
Please see the documentation for where to locate your error log and provide the information that we need. https://snipe-it.readme.io/docs/getting-help

**Comment by xP0se** [comment]
Hi Snipe,

I am still confused.
I have looked into the database, all tables (company, category, location,
supplier, user......) have been filled in correctly..Except for the Asset
Tabel (stuu_assets) still EMPTY.
I have tried to fill it with some asset data..But asset data is not
recorded in the table.

Many thanks in advance for your help

**Comment by snipe** [comment]
@xP0se as I have mentioned, we cannot help you without knowing what's in your error log. No one else is having this issue, so we need more information.

**Comment by xP0se** [comment]
Dear snipe,

When first install...
I got error message "PHP version is less than the required 5.5.9"
With checkbox "Do you wish to enable PHP 5.5.38? (Might cause issues with
your existing installation).

To continue installation process i have to check on the check box.
No more error message after that

Thanks

**Comment by snipe** [comment]
I need log info, not UI info. Also, where did you even see that prompt? We don't have any checkboxes like that in our system.

**Comment by xP0se** [comment]
Hi Snipe,

Regarding my email below
I have found that the problem is :
- I have successfully submit record (complete with "Device Image" field)
only on the First Record, but it failed on the next record
- I have successfully submit many record if "Device Image" not included

Thanks

**Comment by xP0se** [comment]
Hi Snipe,

Please ignore my previous email
Now all assets already appeared with device image. It must submit from
asset model.
Sorry to disturb you with this.

Question :

1.  What the function of "upload Image" on Create Asset?
2.  How to put a title on login page? (for example "Asset Management")
3.  How to make logo bigger on login page?

Many thanks for your guidance

**Comment by Todd-H** [comment]
I just started working with Snipe-IT and my test imports showed the assets but after I deleted them and soft purged them now when I import them they do now show up in All Assets. I look in the status under setting and it shows 5 but when I click in there it is not showing the assets, it is saying no matching records found. I have looked under every option and they are not there. Even though there is only one company I have enabled multi-company like above.

•	Version of Snipe-IT you're running: v4.1.10 – build 3249
•	What OS and web server you're running Snipe-IT on: Windows Server 2012 R2
•	What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual installation
•	If you're getting an error in your browser, include that error: N/A
•	What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: 
•	If a stacktrace is provided in the error, include that too.: N/A
•	Any errors that appear in your browser's error console. N/A
•	Confirm whether the error is reproduceable on the demo: 
•	Include any additional information you can find in app/storage/logs and your webserver's logs.: I presume this is now storage/logs.
•	Include what you've done so far in the installation, and if you got any error messages along the way.: N/A
•	Indicate whether or not you've manually edited any data directly in the database: No.
