### ISSUE TITLE
snipeit.sh doesn't recognize between 32-/ and 64-bit CentOS installation

### ISSUE THREAD

**Issue by joelhoisko** [snipe/snipe-it#2369]
#### Expected Behavior (or desired behavior if a feature request)

Installer to install the correct version of MariaDB according to the system.

---
#### Actual Behavior

On line 365 the MariaDB repo is set to:
`echo >> $mariadbRepo "baseurl = http://yum.mariadb.org/10.0/centos6-amd64"`

This won't work on 32-bit machines(sadly I have to use one) as a working repo would be (for CentOS 6 32-bit:
`baseurl = http://yum.mariadb.org/10.1/centos6-x86`

---
#### Please provide answers to these questions before posting your bug report:
- What OS and web server you're running Snipe-IT on
  CentOS 32-bit 6.8 Final running in VirtualBox 5.1.2 on a Windows Server 2003
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  install.sh

**Comment by dmeltzer** [comment]
At this point there's already so many branches and forks and code paths in snipeit.sh that I'm really terrified of adding another one and creating more places to test.  There's been a lot of talk of rewriting the installer to be less bad (it has a lot of warts) and one of the parts of that would hopefully be making it more modular.  

My feeling is that the number of people using the installer to install snipeit3 on centos6 32bit is probably very close to 1.  If a patch appeared snipe may accept it, but I am not going to invest any time in making this work, sorry :(

**Comment by joelhoisko** [comment]
> My feeling is that the number of people using the installer to install snipeit3 on centos6 32bit is probably very close to 1

Yeah, I'm pretty sure that this is one of the most minor things to put your time into and would just increase the testing. Thank you for your answer, I might someday look into this if I'm willing to learn some Bash.

**Comment by RobMSP** [comment]
Perhaps it would be simpler for SnipIT to 'not support' 32-bit os's 
I can't imagine anyone still has any 32-bit hardware in production, at least, I hope not.

**Comment by mtucker6784** [comment]
well, x86 is an arch I didnt focus on for sure, but i understand the concern. i am going to begin a rewrite to make the script a little more friendly, so I'll try to remember the x68 installers as well.
