### ISSUE TITLE
Checking out Assets to non-users

### ISSUE THREAD

**Issue by KessirCTED** [snipe/snipe-it#2371]
#### Expected Behavior (or desired behavior if a feature request)

I want to be able to check out assets to people outside my organization, people who do not have an account (username and password).
In other words, we need to implement a type of user that does not have a username and password.

My organization works with a lot of partners, I would not want to create a SnipeIt account for each of them but I want to ba able to log which partner an asset was given to.

---
#### Please confirm you have done the following before posting your bug report:
- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running: v3.0-32-gba25972
- What OS and web server you're running Snipe-IT on:  Ubuntu, Nginx

**Comment by snipe** [comment]
@KessirCTED that's not currently possible, as all user's require a username and password at the model level. Is it that problematic to just create an account for them and never share the login info?

**Comment by KessirCTED** [comment]
@snipe It is not that problematic. It just feels like clutter.

Is this something you would want to support in the future?
