### ISSUE TITLE
Not able to launch in web browser

### ISSUE THREAD

**Issue by chaitanyan123** [snipe/snipe-it#2372]
Hi., we have installed the snipe-it in Ubuntu 16.04, by followed the documentation available on https://snipe-it.readme.io/docs.

After, we have completed the configuration, tried to launch the Pre-Flight & Setup in browser by using with both FQDN and Localhost in the Server. But, i am getting only black page and not able to find any information.

Please find the attached screenshots and help us.
![not loading](https://cloud.githubusercontent.com/assets/20687774/17298079/2342578c-5826-11e6-830c-b96f11a7941b.png)
![screenshot from 2016-08-01 18-24-18](https://cloud.githubusercontent.com/assets/20687774/17298080/2342e9e0-5826-11e6-93e9-7d27258c1bc6.png)

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by chaitanyan123** [comment]
Hi., please find the details below

-     Version of Snipe-IT you're running

**Snipe-IT version 3.0**
-     What OS and web server you're running Snipe-IT on

**I am using Ubuntu 16.04**
-     What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

**I have used install.sh**
-     If you're getting an error in your browser, include that error

**I am not getting any error and not loading the content on page**
-     What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

**After i have configured the Snipe-IT, i just launched in web browser to get Pre-Flight & Setup. But it is not loading on page.**
-     If a stacktrace is provided in the error, include that too.
-     Any errors that appear in your browser's error console.

**no**
-     Confirm whether the error is reproduceable on the demo.

**no**
-     Include any additional information you can find in app/storage/logs and your webserver's logs.
-     Include what you've done so far in the installation, and if you got any error messages along the way.
-     Indicate whether or not you've manually edited any data directly in the database

**no**

**Comment by snipe** [comment]
Please check the permissions on your `storage` directory and subdirectories:
https://snipe-it.readme.io/docs/common-issues#browser-redirects-to-login-but-page-is-blank-with-
