### ISSUE TITLE
Upgrading to latest SnipeIT issues

### ISSUE THREAD

**Issue by egaMage** [snipe/snipe-it#2373]
Hey there! 

I tried to upgrade to the latest snipeit today, I followed the steps on https://snipe-it.readme.io/docs/upgrading.

I already had snipeit installed, pointing to snipeit database. I made a backup of that and did a fresh git clone of snipe-it. I also made a backup/clone of the database and called it snipeit2. I edited the .env file with all the login deets, the new URL I setup and everything. I seem to be getting stuck at the php artisan migrate step ( last step ). 

Please see server side errors when running the command ( linux, ubuntu ). I am also attaching some images, i am able to get to the login screen, but when clicking login it doesn't work. Please assist if possible :-) 
![php-artisan-migrate](https://cloud.githubusercontent.com/assets/16253029/17296897/9e4e0b1a-5803-11e6-9ab8-a7bf28494468.PNG)
![afterlogin](https://cloud.githubusercontent.com/assets/16253029/17296899/9e4f8bf2-5803-11e6-8655-e19483131eed.PNG)
![login](https://cloud.githubusercontent.com/assets/16253029/17296898/9e4e2a14-5803-11e6-98c5-8bb630734be2.PNG)

 [Illuminate\Database\QueryException]
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'custom_fields' already exists (SQL: create table `custom_fields` (`id` int uns
  igned not null auto_increment primary key, `name` varchar(255) not null, `format` varchar(255) not null, `element` varchar(255) not null, `cre
  ated_at` timestamp null, `updated_at` timestamp null) default character set utf8 collate utf8_unicode_ci)

  [PDOException]
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'custom_fields' already exists

**Comment by snipe** [comment]
Seems like your migrations table might be out of whack. Can you show me the contents?

**Comment by egaMage** [comment]
Hey hey, thanks for the quick response, just going to paste it here : 
+-------------------------------------------------------------------------+-------+
| migration                                                               | batch |
+-------------------------------------------------------------------------+-------+
| 2012_12_06_225921_migration_cartalyst_sentry_install_users              |     1 |
| 2012_12_06_225929_migration_cartalyst_sentry_install_groups             |     1 |
| 2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot |     1 |
| 2012_12_06_225988_migration_cartalyst_sentry_install_throttle           |     1 |
| 2013_03_23_193214_update_users_table                                    |     2 |
| 2013_11_13_075318_create_models_table                                   |     2 |
| 2013_11_13_075335_create_categories_table                               |     2 |
| 2013_11_13_075347_create_manufacturers_table                            |     2 |
| 2013_11_15_015858_add_user_id_to_categories                             |     2 |
| 2013_11_15_112701_add_user_id_to_manufacturers                          |     2 |
| 2013_11_15_190327_create_assets_table                                   |     2 |
| 2013_11_15_190357_create_licenses_table                                 |     2 |
| 2013_11_15_201848_add_license_name_to_licenses                          |     2 |
| 2013_11_16_040323_create_depreciations_table                            |     2 |
| 2013_11_16_042851_add_depreciation_id_to_models                         |     2 |
| 2013_11_16_084923_add_user_id_to_models                                 |     2 |
| 2013_11_16_103258_create_locations_table                                |     2 |
| 2013_11_16_103336_add_location_id_to_assets                             |     2 |
| 2013_11_16_103407_add_checkedout_to_to_assets                           |     2 |
| 2013_11_16_103425_create_history_table                                  |     2 |
| 2013_11_17_054359_drop_licenses_table                                   |     2 |
| 2013_11_17_054526_add_physical_to_assets                                |     2 |
| 2013_11_17_055126_create_settings_table                                 |     2 |
| 2013_11_17_062634_add_license_to_assets                                 |     2 |
| 2013_11_18_134332_add_contacts_to_users                                 |     2 |
| 2013_11_18_142847_add_info_to_locations                                 |     2 |
| 2013_11_18_152942_remove_location_id_from_asset                         |     2 |
| 2013_11_18_164423_set_nullvalues_for_user                               |     2 |
| 2013_11_19_013337_create_asset_logs_table                               |     2 |
| 2013_11_19_061409_edit_added_on_asset_logs_table                        |     2 |
| 2013_11_19_062250_edit_location_id_asset_logs_table                     |     2 |
| 2013_11_20_055822_add_soft_delete_on_assets                             |     2 |
| 2013_11_20_121404_add_soft_delete_on_locations                          |     2 |
| 2013_11_20_123137_add_soft_delete_on_manufacturers                      |     2 |
| 2013_11_20_123725_add_soft_delete_on_categories                         |     2 |
| 2013_11_20_130248_create_status_labels                                  |     2 |
| 2013_11_20_130830_add_status_id_on_assets_table                         |     2 |
| 2013_11_20_131544_add_status_type_on_status_labels                      |     2 |
| 2013_11_20_134103_add_archived_to_assets                                |     2 |
| 2013_11_21_002321_add_uploads_table                                     |     2 |
| 2013_11_21_024531_remove_deployable_boolean_from_status_labels          |     2 |
| 2013_11_22_075308_add_option_label_to_settings_table                    |     2 |
| 2013_11_22_213400_edits_to_settings_table                               |     2 |
| 2013_11_25_013244_create_licenses_table                                 |     2 |
| 2013_11_25_031458_create_license_seats_table                            |     2 |
| 2013_11_25_032022_add_type_to_actionlog_table                           |     2 |
| 2013_11_25_033008_delete_bad_licenses_table                             |     2 |
| 2013_11_25_033131_create_new_licenses_table                             |     2 |
| 2013_11_25_033534_add_licensed_to_licenses_table                        |     2 |
| 2013_11_25_101308_add_warrantee_to_assets_table                         |     2 |
| 2013_11_25_104343_alter_warranty_column_on_assets                       |     2 |
| 2013_11_25_150450_drop_parent_from_categories                           |     2 |
| 2013_11_25_151920_add_depreciate_to_assets                              |     2 |
| 2013_11_25_152903_add_depreciate_to_licenses_table                      |     2 |
| 2013_11_26_211820_drop_license_from_assets_table                        |     2 |
| 2013_11_27_062510_add_note_to_asset_logs_table                          |     2 |
| 2013_12_01_113426_add_filename_to_asset_log                             |     2 |
| 2013_12_06_094618_add_nullable_to_licenses_table                        |     2 |
| 2013_12_10_084038_add_eol_on_models_table                               |     2 |
| 2013_12_12_055218_add_manager_to_users_table                            |     2 |
| 2014_01_28_031200_add_qr_code_to_settings_table                         |     2 |
| 2014_02_13_183016_add_qr_text_to_settings_table                         |     2 |
| 2014_05_24_093839_alter_default_license_depreciation_id                 |     2 |
| 2014_05_27_231658_alter_default_values_licenses                         |     2 |
| 2014_06_19_191508_add_asset_name_to_settings                            |     2 |
| 2014_06_20_004847_make_asset_log_checkedout_to_nullable                 |     2 |
| 2014_06_20_005050_make_asset_log_purchasedate_to_nullable               |     2 |
| 2014_06_24_003011_add_suppliers                                         |     2 |
| 2014_06_24_010742_add_supplier_id_to_asset                              |     2 |
| 2014_06_24_012839_add_zip_to_supplier                                   |     2 |
| 2014_06_24_033908_add_url_to_supplier                                   |     2 |
| 2014_07_08_054116_add_employee_id_to_users                              |     2 |
| 2014_07_09_134316_add_requestable_to_assets                             |     2 |
| 2014_07_17_085822_add_asset_to_software                                 |     2 |
| 2014_07_17_161625_make_asset_id_in_logs_nullable                        |     2 |
| 2014_08_12_053504_alpha_0_4_2_release                                   |     2 |
| 2014_08_17_083523_make_location_id_nullable                             |     2 |
| 2014_10_16_200626_add_rtd_location_to_assets                            |     2 |
| 2014_10_24_000417_alter_supplier_state_to_32                            |     2 |
| 2014_10_24_015641_add_display_checkout_date                             |     2 |
| 2014_10_28_222654_add_avatar_field_to_users_table                       |     2 |
| 2014_10_29_045924_add_image_field_to_models_table                       |     2 |
| 2014_11_01_214955_add_eol_display_to_settings                           |     2 |
| 2014_11_04_231416_update_group_field_for_reporting                      |     2 |
| 2014_11_05_212408_add_fields_to_licenses                                |     2 |
| 2014_11_07_021042_add_image_to_supplier                                 |     2 |
| 2014_11_20_203007_add_username_to_user                                  |     2 |
| 2014_11_20_223947_add_auto_to_settings                                  |     2 |
| 2014_11_20_224421_add_prefix_to_settings                                |     2 |
| 2014_11_21_104401_change_licence_type                                   |     2 |
| 2014_12_09_082500_add_fields_maintained_term_to_licenses                |     2 |
| 2015_02_04_155757_increase_user_field_lengths                           |     3 |
| 2015_02_07_013537_add_soft_deleted_to_log                               |     4 |
| 2015_02_10_040958_fix_bad_assigned_to_ids                               |     4 |
| 2015_02_10_053310_migrate_data_to_new_statuses                          |     4 |
| 2015_02_11_044104_migrate_make_license_assigned_null                    |     4 |
| 2015_02_11_104406_migrate_create_requests_table                         |     4 |
| 2015_02_12_001312_add_mac_address_to_asset                              |     4 |
| 2015_02_12_024100_change_license_notes_type                             |     4 |
| 2015_02_17_231020_add_localonly_to_settings                             |     4 |
| 2015_02_19_222322_add_logo_and_colors_to_settings                       |     4 |
| 2015_02_24_072043_add_alerts_to_settings                                |     4 |
| 2015_02_25_022931_add_eula_fields                                       |     4 |
| 2015_02_25_204513_add_accessories_table                                 |     4 |
| 2015_02_26_091228_add_accessories_user_table                            |     4 |
| 2015_02_26_115128_add_deleted_at_models                                 |     4 |
| 2015_02_26_233005_add_category_type                                     |     4 |
| 2015_03_01_231912_update_accepted_at_to_acceptance_id                   |     4 |
| 2015_03_05_011929_add_qr_type_to_settings                               |     4 |
| 2015_03_18_055327_add_note_to_user                                      |     5 |
| 2015_04_29_234704_add_slack_to_settings                                 |     5 |
| 2015_05_04_085151_add_parent_id_to_locations_table                      |     6 |
| 2015_05_22_124421_add_reassignable_to_licenses                          |     6 |
| 2015_06_10_003314_fix_default_for_user_notes                            |     6 |
| 2015_06_10_003554_create_consumables                                    |     6 |
| 2015_06_15_183253_move_email_to_username                                |     6 |
| 2015_06_23_070346_make_email_nullable                                   |     6 |
| 2015_06_26_213716_create_asset_maintenances_table                       |     6 |
| 2015_07_09_014359_add_currency_to_settings_and_locations                |     6 |
| 2015_07_21_122022_add_expected_checkin_date_to_asset_logs               |     6 |
| 2015_07_24_093845_add_checkin_email_to_category_table                   |     6 |
| 2015_07_25_055415_remove_email_unique_constraint                        |     6 |
| 2015_07_29_230054_add_thread_id_to_asset_logs_table                     |     6 |
| 2015_07_31_015430_add_accepted_to_assets                                |     6 |
+-------------------------------------------------------------------------+-------+
124 rows in set (0.01 sec)

**Comment by snipe** [comment]
Those migrations are pretty old. I don't know how the migrations table wouldn't have been updated, but as of v3.2.0 released today, your migrations table should look like this if all migrations have completed.

2012_12_06_225921_migration_cartalyst_sentry_install_users	1
2012_12_06_225929_migration_cartalyst_sentry_install_groups	1
2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot	1
2012_12_06_225988_migration_cartalyst_sentry_install_throttle	1
2013_03_23_193214_update_users_table	2
2013_11_13_075318_create_models_table	2
2013_11_13_075335_create_categories_table	2
2013_11_13_075347_create_manufacturers_table	2
2013_11_15_015858_add_user_id_to_categories	2
2013_11_15_112701_add_user_id_to_manufacturers	2
2013_11_15_190327_create_assets_table	2
2013_11_15_190357_create_licenses_table	2
2013_11_15_201848_add_license_name_to_licenses	2
2013_11_16_040323_create_depreciations_table	2
2013_11_16_042851_add_depreciation_id_to_models	2
2013_11_16_084923_add_user_id_to_models	2
2013_11_16_103258_create_locations_table	2
2013_11_16_103336_add_location_id_to_assets	2
2013_11_16_103407_add_checkedout_to_to_assets	2
2013_11_16_103425_create_history_table	2
2013_11_17_054359_drop_licenses_table	2
2013_11_17_054526_add_physical_to_assets	2
2013_11_17_055126_create_settings_table	2
2013_11_17_062634_add_license_to_assets	2
2013_11_18_134332_add_contacts_to_users	2
2013_11_18_142847_add_info_to_locations	2
2013_11_18_152942_remove_location_id_from_asset	2
2013_11_18_164423_set_nullvalues_for_user	2
2013_11_19_013337_create_asset_logs_table	2
2013_11_19_061409_edit_added_on_asset_logs_table	2
2013_11_19_062250_edit_location_id_asset_logs_table	2
2013_11_20_055822_add_soft_delete_on_assets	2
2013_11_20_121404_add_soft_delete_on_locations	2
2013_11_20_123137_add_soft_delete_on_manufacturers	2
2013_11_20_123725_add_soft_delete_on_categories	2
2013_11_20_130248_create_status_labels	2
2013_11_20_130830_add_status_id_on_assets_table	2
2013_11_20_131544_add_status_type_on_status_labels	2
2013_11_20_134103_add_archived_to_assets	2
2013_11_21_002321_add_uploads_table	2
2013_11_21_024531_remove_deployable_boolean_from_status_labels	2
2013_11_22_075308_add_option_label_to_settings_table	2
2013_11_22_213400_edits_to_settings_table	2
2013_11_25_013244_create_licenses_table	2
2013_11_25_031458_create_license_seats_table	2
2013_11_25_032022_add_type_to_actionlog_table	2
2013_11_25_033008_delete_bad_licenses_table	2
2013_11_25_033131_create_new_licenses_table	2
2013_11_25_033534_add_licensed_to_licenses_table	2
2013_11_25_101308_add_warrantee_to_assets_table	2
2013_11_25_104343_alter_warranty_column_on_assets	2
2013_11_25_150450_drop_parent_from_categories	2
2013_11_25_151920_add_depreciate_to_assets	2
2013_11_25_152903_add_depreciate_to_licenses_table	2
2013_11_26_211820_drop_license_from_assets_table	2
2013_11_27_062510_add_note_to_asset_logs_table	2
2013_12_01_113426_add_filename_to_asset_log	2
2013_12_06_094618_add_nullable_to_licenses_table	2
2013_12_10_084038_add_eol_on_models_table	2
2013_12_12_055218_add_manager_to_users_table	2
2014_01_28_031200_add_qr_code_to_settings_table	2
2014_02_13_183016_add_qr_text_to_settings_table	2
2014_05_24_093839_alter_default_license_depreciation_id	2
2014_05_27_231658_alter_default_values_licenses	2
2014_06_19_191508_add_asset_name_to_settings	2
2014_06_20_004847_make_asset_log_checkedout_to_nullable	2
2014_06_20_005050_make_asset_log_purchasedate_to_nullable	2
2014_06_24_003011_add_suppliers	2
2014_06_24_010742_add_supplier_id_to_asset	2
2014_06_24_012839_add_zip_to_supplier	2
2014_06_24_033908_add_url_to_supplier	2
2014_07_08_054116_add_employee_id_to_users	2
2014_07_09_134316_add_requestable_to_assets	2
2014_07_17_085822_add_asset_to_software	2
2014_07_17_161625_make_asset_id_in_logs_nullable	2
2014_08_12_053504_alpha_0_4_2_release	2
2014_08_17_083523_make_location_id_nullable	2
2014_10_16_200626_add_rtd_location_to_assets	2
2014_10_24_000417_alter_supplier_state_to_32	2
2014_10_24_015641_add_display_checkout_date	2
2014_10_28_222654_add_avatar_field_to_users_table	2
2014_10_29_045924_add_image_field_to_models_table	2
2014_11_01_214955_add_eol_display_to_settings	2
2014_11_04_231416_update_group_field_for_reporting	2
2014_11_05_212408_add_fields_to_licenses	2
2014_11_07_021042_add_image_to_supplier	2
2014_11_20_203007_add_username_to_user	2
2014_11_20_223947_add_auto_to_settings	2
2014_11_20_224421_add_prefix_to_settings	2
2014_11_21_104401_change_licence_type	2
2014_12_09_082500_add_fields_maintained_term_to_licenses	2
2015_02_04_155757_increase_user_field_lengths	2
2015_02_07_013537_add_soft_deleted_to_log	2
2015_02_10_040958_fix_bad_assigned_to_ids	2
2015_02_10_053310_migrate_data_to_new_statuses	2
2015_02_11_044104_migrate_make_license_assigned_null	2
2015_02_11_104406_migrate_create_requests_table	2
2015_02_12_001312_add_mac_address_to_asset	2
2015_02_12_024100_change_license_notes_type	2
2015_02_17_231020_add_localonly_to_settings	2
2015_02_19_222322_add_logo_and_colors_to_settings	2
2015_02_24_072043_add_alerts_to_settings	2
2015_02_25_022931_add_eula_fields	2
2015_02_25_204513_add_accessories_table	2
2015_02_26_091228_add_accessories_user_table	2
2015_02_26_115128_add_deleted_at_models	2
2015_02_26_233005_add_category_type	2
2015_03_01_231912_update_accepted_at_to_acceptance_id	2
2015_03_05_011929_add_qr_type_to_settings	2
2015_03_18_055327_add_note_to_user	2
2015_04_29_234704_add_slack_to_settings	2
2015_05_04_085151_add_parent_id_to_locations_table	3
2015_05_22_124421_add_reassignable_to_licenses	2
2015_06_10_003314_fix_default_for_user_notes	3
2015_06_10_003554_create_consumables	3
2015_06_15_183253_move_email_to_username	3
2015_06_23_070346_make_email_nullable	3
2015_06_26_213716_create_asset_maintenances_table	3
2015_07_04_212443_create_custom_fields_table	7
2015_07_09_014359_add_currency_to_settings_and_locations	3
2015_07_21_122022_add_expected_checkin_date_to_asset_logs	3
2015_07_24_093845_add_checkin_email_to_category_table	3
2015_07_25_055415_remove_email_unique_constraint	3
2015_07_29_230054_add_thread_id_to_asset_logs_table	4
2015_07_31_015430_add_accepted_to_assets	5
2015_09_09_195301_add_custom_css_to_settings	5
2015_09_21_235926_create_custom_field_custom_fieldset	7
2015_09_22_000104_create_custom_fieldsets	7
2015_09_22_003321_add_fieldset_id_to_assets	7
2015_09_22_003413_migrate_mac_address	7
2015_09_28_003314_fix_default_purchase_order	6
2015_10_01_024551_add_accessory_consumable_price_info	6
2015_10_12_192706_add_brand_to_settings	6
2015_10_22_003314_fix_defaults_accessories	6
2015_10_23_182625_add_checkout_time_and_expected_checkout_date_to_assets	6
2015_11_05_061015_create_companies_table	6
2015_11_05_061115_add_company_id_to_consumables_table	6
2015_11_05_183749_image	6
2015_11_06_092038_add_company_id_to_accessories_table	6
2015_11_06_100045_add_company_id_to_users_table	6
2015_11_06_134742_add_company_id_to_licenses_table	6
2015_11_08_035832_add_company_id_to_assets_table	6
2015_11_08_222305_add_ldap_fields_to_settings	6
2015_11_15_151803_add_full_multiple_companies_support_to_settings_table	6
2015_11_26_195528_import_ldap_settings	7
2015_11_30_191504_remove_fk_company_id	7
2015_12_21_193006_add_ldap_server_cert_ignore_to_settings_table	7
2015_12_30_233509_add_timestamp_and_userId_to_custom_fields	7
2015_12_30_233658_add_timestamp_and_userId_to_custom_fieldsets	7
2016_01_28_041048_add_notes_to_models	8
2016_02_19_070119_add_remember_token_to_users_table	9
2016_02_19_073625_create_password_resets_table	9
2016_03_02_193043_add_ldap_flag_to_users	9
2016_03_02_220517_update_ldap_filter_to_longer_field	9
2016_03_08_225351_create_components_table	9
2016_03_09_024038_add_min_stock_to_tables	9
2016_03_10_133849_add_locale_to_users	9
2016_03_10_135519_add_locale_to_settings	9
2016_03_11_185621_add_label_settings_to_settings	9
2016_03_22_125911_fix_custom_fields_regexes	9
2016_04_28_141554_add_show_to_users	9
2016_05_16_164733_add_model_mfg_to_consumable	9
2016_05_19_180351_add_alt_barcode_settings	9
2016_05_19_191146_add_alter_interval	9
2016_05_19_192226_add_inventory_threshold	9
2016_05_20_024859_remove_option_keys_from_settings_table	9
2016_05_20_143758_remove_option_value_from_settings_table	9
2016_06_01_140218_add_email_domain_and_format_to_settings	9
2016_06_22_160725_add_user_id_to_maintenances	9
2016_07_13_150015_add_is_ad_to_settings	9
2016_07_14_153609_add_ad_domain_to_settings	9
2016_07_22_003348_fix_custom_fields_regex_stuff	9
2016_07_22_054850_one_more_mac_addr_fix	9
2016_07_22_143045_add_port_to_ldap_settings	9
2016_07_22_153432_add_tls_to_ldap_settings	9
2016_07_27_211034_add_zerofill_to_settings	10
2016_08_02_124944_add_color_to_statuslabel	11

**Comment by snipe** [comment]
Try adding a record manually into the migrations table for `2015_07_04_212443_create_custom_fields_table`.

This is really fucked up, and no one should ever have to do this, so not sure what happened here. It's as if your migrations table was manually entered.

Anyway, try adding that record (since it's missing in your migrations, although apparently migrations that came after it are not???) and re-run migrations. This will be a tedious process, trying to figure out which migrations actually ran and which ones didn't, but I don't know what other choice you'd have.

**Comment by egaMage** [comment]
Hey hey,

Thanks for the response, I'm going to give it a try today , create the tables manually as they pop up and see what happens. Otherwise it might be worth installing snipeit3 with a new database and just importing the old tables?

**Comment by egaMage** [comment]
Looks like downloading the latest snipeit and creating a fresh database and importing the previous database tables is working. Not sure which tables to avoid.. Assets / licenses are loading but as soon as I try to click on the hardware 
http://puu.sh/qpNEC/e8c2db323c.png
( Whoops, looks like something went wrong. ) /hardware/number/view. Still importing tables, perhaps it will come right in a bit

**Comment by snipe** [comment]
Would need to see the debugging logs for that whoops error.

**Comment by snipe** [comment]
Also, I don't think you want to try to create tables manually. That sounds like a bad road to go down.

**Comment by egaMage** [comment]
Hey again,

So far so good , I'm importing the tables from the existing old database, just certain tables like Assets, Licenses, users etc. The only thing I can't get to work is when clicking on the hardware. Please see attached screenshots :) 
![hardware4](https://cloud.githubusercontent.com/assets/16253029/17428272/9682936a-5ae7-11e6-8a5f-d564a92f098f.PNG)
![hardware3](https://cloud.githubusercontent.com/assets/16253029/17428271/96818fd8-5ae7-11e6-8eb1-7cc26dbd2b5b.PNG)
![hardware2](https://cloud.githubusercontent.com/assets/16253029/17428270/9680cb02-5ae7-11e6-8540-c3f005b5825a.PNG)
![hardware1](https://cloud.githubusercontent.com/assets/16253029/17428273/968396f2-5ae7-11e6-8e4a-bc29049ac62a.PNG)

**Comment by snipe** [comment]
Did you ever get this resolved?
