### ISSUE TITLE
Editing assets drops image file.

### ISSUE THREAD

**Issue by Alsoongit** [snipe/snipe-it#2374]
#### Expected Behavior (or desired behavior if a feature request)

Edit an asset and have image file remain on asset.

---
#### Actual Behavior

when editing an asset the image file has to be selected again.  

---
#### Please confirm you have done the following before posting your bug report:
- [NO ] I have enabled debug mode
- [ YES] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running
  System Information

Snipe-IT version    v3.0-ebc74a65
PHP Version 5.6.23-0+deb8u1
Laravel Version 5.2.39
- What OS and web server you're running Snipe-IT on
  Debian/Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  Install.sh
- If you're getting an error in your browser, include that error
  No Error documented
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
  Asset Editing
- If a stacktrace is provided in the error, include that too.
  No stack trace 
- Any errors that appear in your browser's error console.
  Browser console errors
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
  Was not reproduceable in demo
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
  Previous issue opened for ldap issues, resolved.
- Indicate whether or not you've manually edited any data directly in the database
  No

**Comment by dmeltzer** [comment]
Is this reproducable with the newly released 3.1 for you? I can't make it happen in my test install or on the demo.  If you still can, can you give more detailed steps of how to reproduce?

Thanks!
