### ISSUE TITLE
Warranty expire E-Mail is not working

### ISSUE THREAD

**Issue by manusolano777** [snipe/snipe-it#2376]
Except email functionality every thing working fine.
Am using _"C:\wamp\bin\php\php5.5.12\php.exe C:\wamp\www\asset\artisan snipeit:expiring-alerts"_ as command in my windows server task sheduler.

Version of Snipe-IT you're running? Snipe-IT version v3.0-ebc74a65 PHP Version 5.5.12 Laravel Version 5.2.39 What OS and web server you're running Snipe-IT on? Windows Server 2008 What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual

**Comment by snipe** [comment]
Does other mail work (forgotten password, for example)

**Comment by manusolano777** [comment]
Yes snipe It will send E-mail when a new users are created...

**Comment by snipe** [comment]
Are you sure you have expiring warranties? If mail is working, there's no reason that alert shouldn't work if you actually have expiring things to alert on.

**Comment by snipe** [comment]
(Also make sure you have a valid email address in the Admin > Settings section for alerts)

**Comment by manusolano777** [comment]
I think this will give more clear picture. Below is my configurations in masters AND ASSET DETAILS.
![error2](https://cloud.githubusercontent.com/assets/18734573/17314671/b185bd06-5883-11e6-8e89-81b15cd49236.png)
![error1](https://cloud.githubusercontent.com/assets/18734573/17314672/b188a494-5883-11e6-8a83-5d16a140d39d.png)

**Comment by snipe** [comment]
Your threshold is 30 days, but that asset doesn't expire for 2 months, no? No alert would be triggered.

**Comment by manusolano777** [comment]
Thanks for your reply. I have changed my "Expiring Alert Threshold" to 90 days. Still i didn't receive any email remainder for this item.

**Comment by manusolano777** [comment]
![error](https://cloud.githubusercontent.com/assets/18734573/17333779/5098d5fa-58f1-11e6-8821-e2296b3d2bc9.png)

**Comment by zchoate** [comment]
Not sure if this is related or not but I am having the same issue but with Inventory Alerts. Expiring Alerts send without issue for me as well other emails via Snipe-IT. When I run php artisan snipeit:inventory-alerts I get no action.
