### ISSUE TITLE
Admin user can grant Super User permissions.

### ISSUE THREAD

**Issue by niallmooney** [snipe/snipe-it#2378]
#### Expected Behavior (Not sure if this by design or not)

User with admin permissions shouldn't be able to adjust permissions above their current admin level (i.e To Super User)

-----

#### Actual Behavior

User with admin permissions is able give themselves and others super user permissions.
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.1.0
- What OS and web server you're running Snipe-IT on: CentOS 6.8/Apache 2.2.15/PHP 5.6.24
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual Installation
- If you're getting an error in your browser, include that error: N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Accept Asset page for unauthenticated users.
- If a stacktrace is provided in the error, include that too: N/A
- Any errors that appear in your browser's error console: N/A
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): Unsure
- Include any additional information you can find in `app/storage/logs` and your webserver's logs: N/A
- Include what you've done so far in the installation, and if you got any error messages along the way: Imported test assets and testing functionality of confirming assets.
- Indicate whether or not you've manually edited any data directly in the database: No

**Comment by snipe** [comment]
Where are you even seeing the edit users option for an admin?

**Comment by niallmooney** [comment]
The buttons are visible when you view the user in the people section.
![viewuser](https://cloud.githubusercontent.com/assets/5770937/17313740/b6991a4a-58a1-11e6-9de5-f205afb51896.jpg)

**Comment by snipe** [comment]
What is the expectation here though? If an admin can create a new user, what's to stop them from just creating a new user with superadmin powers if they can't edit their own user's permissions?

**Comment by niallmooney** [comment]
I wasn't entirely sure whether the ability for an admin to give themselves Super Admin permissions was by design or not.
But my expectation would have been that they shouldn't.

At the end of the day, it isn't too much of a big deal that they can.
