### ISSUE TITLE
ON upgrade with Version v3.1-84-g139325d, Archived Tab grade out 

### ISSUE THREAD

**Issue by dheer99** [snipe/snipe-it#2381]
#### Expected Behavior (or desired behavior if a feature request)

Device moved to Archived category, not able to view on Archived tab, which is grade out on new version 

-----

#### Actual Behavior

ON upgrade with Version v3.1-84-g139325d, Archive Tab grade out 

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running    :-   Version v3.1-84-g139325d
- What OS and web server you're running Snipe-IT on :- Windows 2008, IIS7+
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) :- manual
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Screenshot please

**Comment by dheer99** [comment]
![archived](https://cloud.githubusercontent.com/assets/20639130/17322175/7677ff44-589c-11e6-9da2-155721d42e6f.PNG)

Screenshot

**Comment by fredno** [comment]
![snipeit archived missing 2](https://cloud.githubusercontent.com/assets/13047653/17322167/6847d890-589c-11e6-9203-81a528af7b99.PNG)

It seems like the Archived are not connected to an <a href>

**Comment by dheer99** [comment]
changes has been made on  resources/views/layouts/default.blade.php
, still same issue

**Comment by snipe** [comment]
<img width="289" alt="screen shot 2016-08-02 at 1 50 16 am" src="https://cloud.githubusercontent.com/assets/197404/17322684/7ef96066-5853-11e6-834f-c411adf3bd16.png">

Can't reproduce on the demo. Did you actually upgrade?

**Comment by snipe** [comment]
(Meaning did you do a fresh pull from master?)

**Comment by dheer99** [comment]
yes same issue , dont know what is a fresh pull from master !

[default.blade.txt](https://github.com/snipe/snipe-it/files/396190/default.blade.txt)

Upload default.blade.php with rename as .txt

**Comment by snipe** [comment]
Please grab the latest code from the master branch. You've put the code in the wrong place.

**Comment by dheer99** [comment]
Thanks Start working now :+1
