### ISSUE TITLE
"Purchase cost" input is not interpreted correctly

### ISSUE THREAD

**Issue by molldk** [snipe/snipe-it#2383]
Hi,

When editing an asset, the price will be formatted with comma (,) for thousand seperator and dot for decimals. When this is inputted, it should save it correctly in database, however it replaces the purchase cost with the leading integers. For example the price of 8,975.00 will be converted to 8.

The input works correctly when inputting the cost as integer, 8975 will result in correct behavior. Any assets thats is edited will contain the formatted number, hence be changed to a wrong value.

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:
Version v3.1-84-g139325d
CentOS 7, Apache, PHP5.6 from Remi repository, MariaDB
Manual installation with git clone
No error is shown, just wrong data
Happens on /hardware/XXX/edit - possibly during clone and creation as well (not tested)
Same thing happens on Snipe-IT Demo.
I have not touched the database manually.

Steps to reproduce problem:
1. Edit asset
2. Enter Purchase Cost 1500
3. Save
4. Edit same asset
5. Change something else, or just save
6. Price is now 1

**Comment by molldk** [comment]
Thank you :)

**Comment by laughtingman** [comment]
Snipe,

licenses, components, acessories and consumables has exactly the same bug.
