### ISSUE TITLE
Feature request: way to assign an asset to a location, rather that a user

### ISSUE THREAD

**Issue by pako-pl** [snipe/snipe-it#2384]
Many assets (for example routers, network switches, access points or even computers intended to be used by many people) will be assigned to a specific location, rather than a user. For now we can't check them out without assigning them to a user. Do you plan to add a way to "check out" an asset to a location? Or should we mark the status of such items in a different way?

**Comment by stevecookms** [comment]
I would like to see this as well.

**Comment by dmeltzer** [comment]
See #142.
