### ISSUE TITLE
View Asset:  Comma present for location when not applicable

### ISSUE THREAD

**Issue by pcavagna** [snipe/snipe-it#2387]
#### Expected Behavior (or desired behavior if a feature request)

If only Location Name field is filled out for a Location, comma shouldn't be displayed for absent information when viewing an asset.

-----

#### Actual Behavior

There is a comma present viewing an existing asset with just the Location Name filled.

![comma location](https://cloud.githubusercontent.com/assets/999600/17349211/d3b3bfde-58d0-11e6-913b-820a8fd992ba.jpg)

**Comment by snipe** [comment]
![american-psycho](https://cloud.githubusercontent.com/assets/197404/17349305/6a84c002-58d1-11e6-9f61-8904ddfd4e7d.gif)
