### ISSUE TITLE
Feature Request: Bulk Upload Files for more than one asset

### ISSUE THREAD

**Issue by MPIAE-IT** [snipe/snipe-it#2389]
If you get a large delievery of assets like i.e. displays from the same type, it would be very helpfull if you could bulk upload files to several assets. Or just link one file to several assets. 
We upload the invoices to our assets, so we have them right away if we need them for a certain asset.

**Comment by dmeltzer** [comment]
Is this essentially the same as #2355 or are you looking for the other direction (Multiple files->one asset all at once)

**Comment by MPIAE-IT** [comment]
Actually the proposed way of handling is different, but the goal is the same. So yeah my request is redundant... Thanks for heads up!
