### ISSUE TITLE
Checkin not associated with user

### ISSUE THREAD

**Issue by molldk** [snipe/snipe-it#2390]
When checking in asset, the username is not recorded. This means the history of users can only show checkout actions and not checkin. It is expected to show checkin on history tab for better overview.

---
#### Please confirm you have done the following before posting your bug report:
- [x] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version v3.1-84-g139325d
- CentOS 7, Apache, PHP5.6 from Remi repository, MariaDB
- Manual installation with git clone
- No error is shown, just wrong data
- Happens on /admin/users/XXX/view, history tab - also in the history for each asset, only the checkout shows name
- Same thing happens on Snipe-IT Demo.
- I have not touched the database manually.

**Comment by snipe** [comment]
Whoever the previous checkout was to is the person it was checked in from.

**Comment by sysnoo** [comment]
I just noticed that all checkin associated users are not shown.
This is somehow a regression : 
I have a user with 14 items checkin, records are missing from 
- user history
- activity report
- asset history

It was very comfortable to see any action associated in all timelines.
Now it is very annoying to see all that info gone.

**Comment by snipe** [comment]
I believe this was already fixed in the latest release
