### ISSUE TITLE
Are these current functions in 3.1

### ISSUE THREAD

**Issue by mattgann** [snipe/snipe-it#2393]
recursively search Child OU for new user additions
Scheduled ldap user imports from AD
AD Authenticated user accounts for login to snipe-it

Do any of these items currently function in 3.1

**Comment by mattgann** [comment]
No response

**Comment by snipe** [comment]
These topics have been covered in several other tickets already. 

It searches through whatever base DN you give it. 

There are currently no scheduled LDAP imports possible, but it's something we'll be adding.

AD logins have been supported since v2.
