### ISSUE TITLE
Cannot edit asset for admin/ User with edit rights (v3.2)

### ISSUE THREAD

**Issue by SK9413** [snipe/snipe-it#2395]
#### Please confirm you have done the following before posting your bug report:
- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running
  **Version v3.2.0-53-gfff2bce**
- What OS and web server you're running Snipe-IT on
  **Windows Server 2008 with XAMPP**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  **Manual installation**
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
  **Yes**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
  **No**
- Indicate whether or not you've manually edited any data directly in the database
  **No**

I created a user with the rights below.
1)
![rights1](https://cloud.githubusercontent.com/assets/15903195/17387924/a8673d3c-5a2a-11e6-8d38-6353bdd3a488.jpg)

2)
![rights2](https://cloud.githubusercontent.com/assets/15903195/17388001/6d52c4fe-5a2b-11e6-9901-c5ac3a1c21a7.jpg)

But the user cannot edit asset

"array:4 [
  "ability" => "assets.edit"
  "result" => false
  "user" => 38
  "arguments" => []
]
error"

The assets can be edited if I use a **super user account**.

"array:4 [
  "ability" => "admin"
  "result" => true
  "user" => 39
  "arguments" => []
]
success"

**Comment by JExactly** [comment]
Also experiencing this issue. I am only able to set the admin group as super users to currently allow my admins the ability to edit assets etc
