### ISSUE TITLE
Idiots Guide

### ISSUE THREAD

**Issue by Rossemikka** [snipe/snipe-it#2398]
Hello,

I've been trying fruitlessly to get Snipe-IT installed on a LAMP VM for a few weeks now. This would be a great alternative to our current MS Access share...
Would anyone be kind enough to share a step by step guide to get Snipe-IT up and running from the point of installing Docker.

The current guide doesn't quite join all the dots...

--Ryan
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

---
#### Actual Behavior

(what actually happens goes here)

---
#### Please confirm you have done the following before posting your bug report:
- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running - latest docker pull 
- What OS and web server you're running Snipe-IT on - ubuntu xenial 16.04.1 LTS
- What method you used to install Snipe-IT - Docker
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by stevecookms** [comment]
I could help you setup on a LAMP VM in a non docker environment.

**Comment by Rossemikka** [comment]
Hey Steve,

That would be fantastic! I can revert to an early snapshot without docker.

**Comment by stevecookms** [comment]
I used ubuntu 14.04. Have you tried installing via the install.sh script?

**Comment by Rossemikka** [comment]
Yes, Ive tried all the methods. The documentation is a little thin. I ran the installer - apart from it not showing me the install questions I believe I got it to install. Then, if i remember correctly - artisan wouldnt work, The database was blank.

**Comment by stevecookms** [comment]
Did the install script produce any errors or did it say it was complete?

**Comment by stevecookms** [comment]
wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh

Make it executable.

chmod 744 install.sh ./install.sh

 Run the install script.

./install.sh

It should then walk you through asking for root password and your mysql root password.

**Comment by cduverne** [comment]
Hi, 

I can also share the ansible scripts I created to install snipeIT in docker.

@snipe , I can also share it with you to be integrated in the documentation.

**Comment by Rossemikka** [comment]
Thank you stevecookms. I had previously tried the install script... but then the guides kind of fizzle out... then what?

And cduverne that would be fantastic, could you?

**Comment by cduverne** [comment]
Please find the conf here.
You'll see that you'll have to add some variables, but the container management is there.

Enjoy ! 

[snipeit-obf.tar.gz](https://github.com/snipe/snipe-it/files/407099/snipeit-obf.tar.gz)

**Comment by mtucker6784** [comment]
I'm concerned about the install script then.  what part fizzles out for you, @Rossemikka?

the purpose of it is to make installing snipe it pretty dang painless, not that its extremely difficult as is. if there is a hold up, i would like to know.

thanks

**Comment by Rossemikka** [comment]
@stevecookms - the script reaches the point where it prompts you for a root password (just after you type your FQDN out). After you type it in the script appears to hang at a text prompt.

If you smash enter a few times a number of questions that have all been skipped appear and it moves onto the install. 

After it installs I am unable to access the FQDN in the browser which I defined as kyo-svrv-04.local.
However I am able to access kyo-svrv-04 which takes me to the apache2 default page.

**Comment by delinski111** [comment]
I just wrote up about 10 pages regarding installing snipeit on linux 14.04. It is not completed yet, but should be enough for you to get it up and running.
![screencapture](https://cloud.githubusercontent.com/assets/22087997/19523292/121e0e10-95e8-11e6-8e2c-a6f65430b355.png)

**Comment by snipe** [comment]
Looks great so far - when it's done, can you provide it in markdown format? That's what our documentation site uses.
