### ISSUE TITLE
Afer upgrade to version 3.2, I am not able to browse it. It's unaccessible.

### ISSUE THREAD

**Issue by monikasuneja** [snipe/snipe-it#2401]
#### Please confirm you have done the following before posting your bug report:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running - Version 3.2
- What OS and web server you're running Snipe-IT on - Ubuntu 14.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by monikasuneja** [comment]
I am running snipe-IT version 3.2 on Ubuntu 14.04

**Comment by dmeltzer** [comment]
Can you confirm that storage/logs is writable by the web server ?

**Comment by monikasuneja** [comment]
yes, it's writeable. I was able to login for the first time. but, after restarting the server, it's showing the blank page.

**Comment by snipe** [comment]
Did you get this sorted?
