### ISSUE TITLE
Deleted manufacturer can't be created again with the same name

### ISSUE THREAD

**Issue by zrhpwr** [snipe/snipe-it#2402]
#### Expected Behavior (or desired behavior if a feature request)

Delete Manufacturer that was created, Create new manufacturer with same name

---
#### Actual Behavior

Error message "The name already been taken"

---
#### Please confirm you have done the following before posting your bug report:
- [ ] I have enabled debug mode: No
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running: 3.2.1
- What OS and web server you're running Snipe-IT on: Windows Server 2012 R2, PHP 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual install
- If you're getting an error in your browser, include that error: See Actual behavior
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Create Manufacturer
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).: reproducable

**Comment by dmeltzer** [comment]
This specific issue is actually (kind of) working as intended (tm).  All records in snipe-it are soft-deleted, so in theory you should be able to see deleted manufacturers and restore them.

The bug here is actually that it doesn't look like we allow a way to restore it at present.  I'll see if I can remedy that this evening.

**Comment by Puddl36lum** [comment]
Was this ever remedied?  I'm having the same issue.  Is there a way to undo the soft delete as you can with users?
