### ISSUE TITLE
Unable to merge local user account with LDAP account.

### ISSUE THREAD

**Issue by joliving** [snipe/snipe-it#2403]
#### Expected Behavior (or desired behavior if a feature request)

"When you have LDAP enabled and a user tries to login, it will first query your LDAP server with their credentials. If they authenticate successfully with your LDAP server, their local user record will be updated and they will be logged in."

ldap account syncs with local account by matching mail id

-----

#### Actual Behavior

by syncing with ldap duplicate user gets created rather than updating the local user

-----

#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode
- [ yes] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 3.2.0
- OS and web server you're running Snipe-IT on centos 7 apache
- Manual instalation

**Comment by snipe** [comment]
It matches on whatever the username is (whatever field you have mapped to username) not email address.

**Comment by joliving** [comment]
Thank You it solved my problem.

earlier email id was the username for the local accounts.

changed it to match with AD username, now clients can login with AD account.

Thank's a Lot Snipe!
