### ISSUE TITLE
Question about adding print function in Action drop-down button

### ISSUE THREAD

**Issue by happicamper** [snipe/snipe-it#2405]
#### Expected Behavior (or desired behavior if a feature request)

Hello, how can I add print button/function under /admin/users/#number/view, I can see a drop-down button here named "Action" i want to include the print option under this button, thank you in advance

---
#### Actual Behavior

under /admin/users/#number/view there is an "Action" drop-down button which only have a function of Edit User and Clone User

---
#### Please confirm you have done the following before posting your bug report:
- [/] I have enabled debug mode
- [/] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running

``` bash
Snipe-IT version    v1.2.7-beta-10-g48ccf84
PHP Version         5.5.9-1ubuntu4.9
Laravel Version     4.2.17
```
- What OS and web server you're running Snipe-IT on  
  `Docker Running on Centos 6.6`
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)  
  `Docker`
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by dmeltzer** [comment]
You would need to modify the php to do so (And it would be overwritten on update unless it got merged into the main source).  If you wanted to do the modifications, take a look at resources/views/users/view.blade.php, and app/Http/Controllers/UsersController.php
