### ISSUE TITLE
Asset roles not working as expected in 3.2 (possibly since 3.0)

### ISSUE THREAD

**Issue by mmcleod82** [snipe/snipe-it#2406]
#### Expected Behavior (or desired behavior if a feature request)

Assign Assets:Edit role to a Group - Assign that group to a user 'snipetest' - user 'snipetest' should then be able to edit assets.

-----

#### Actual Behavior

User is unable to edit asset - button not visible - this is via the 'list assets' view, if you try via the other entry point (click on asset, then edit) it fails also with a 403.

Only permission that allows editing of assets is Super Admin.....

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - 3.2
- What OS and web server you're running Snipe-IT on - IIS8 - Win 2012 server
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual
- If you're getting an error in your browser, include that error - no browser errors per se.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error 
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). - cannot test on demo as demo doesn't allow altering of roles.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by SK9413** [comment]
Same

[https://github.com/snipe/snipe-it/issues/2395](url)

**Comment by VanillaNinjaD** [comment]
Same here. Thought I was crazy.

Snipe-IT - 3.2
OS - Ubuntu 14.04.5
Install - Manual

**Comment by snipe** [comment]
Can you confirm that the user you're seeing the issue on is not a member of any other permission groups that deny the Asset: Edit permission?

**Comment by snipe** [comment]
> If I give him superuser permissions her can create labels.

Via the group, or via his own permissions?

Is is just label creation/asset editing, or are there other things that he can't do that he should be able to do?

**Comment by VanillaNinjaD** [comment]
Via the group.

The users have complete "Inherit" permissions

Give me a minute or two to check on the other actions

**Comment by VanillaNinjaD** [comment]
Seems limited to actions considered "editing" which appear to be label generation and actual asset editing

I see your commit, would you like me to pull it down and test?

**Comment by snipe** [comment]
If you wouldn't mind, that would be great. It's only on the develop branch right now

**Comment by VanillaNinjaD** [comment]
I'll report back soon! Thanks!

**Comment by snipe** [comment]
(You may also want to run migrations, as there's a small tweak to the DB on the develop branch)

**Comment by VanillaNinjaD** [comment]
Like a charm!

**Comment by snipe** [comment]
Awesome! I'll get that merged into master then.

**Comment by VanillaNinjaD** [comment]
I simply pasted the assets.edit gate into the AuthServiceProvider.php to test

I think I may stay with this setup until the merge hits master, I like to avoid the testing branch for production.

Thank you for the quick responses

**Comment by VanillaNinjaD** [comment]
pulled master, ran migrations and tested

works perfectly

**Comment by snipe** [comment]
Awesome, thanks!

![boom-shakalaka](https://cloud.githubusercontent.com/assets/197404/17537810/8a6ed596-5e54-11e6-8c03-2d8eefead612.gif)
