### ISSUE TITLE
HTTP 500 Internal Server Error (Windows Server 2012 R2)

### ISSUE THREAD

**Issue by henryp007** [snipe/snipe-it#2408]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

Webpage opens

#### Actual Behavior

 
The website cannot display the page
 
  HTTP 500 
 
    
Most likely causes:
•The website is under maintenance.
•The website has a programming error.
 

-----

#### Please confirm you have done the following before posting your bug report:

- [ yes] I have enabled debug mode
- [ yes] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: Latest Release
- What OS and web server you're running Snipe-IT on Windows Server 2012 R2 Standard (IIS8)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual
- If you're getting an error in your browser, include that error   HTTP 500 
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error any
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. 
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. No logs have been created even though debug is turned on
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by dheer99** [comment]
add the "full control" rights for directory under C:\Inetpub\wwwroot\ "Snipe-IT"  & "Temp"folder under Windows directory
or it's good if you add everyone with full rights

**Comment by henryp007** [comment]
Hi @dheer99 I tried this but I still get the same error message :-(

**Comment by dmeltzer** [comment]
Check storage/logs/laravel.log and see if anything in there is indicative of an issue.

**Comment by henryp007** [comment]
Hi @dmeltzer I've checked the folder and there's only a single file called .gitignore which contains no log.
I think there must be something very wrong here...

**Comment by dmeltzer** [comment]
If you set APP_DEBUG to true in the .env file does it give more information? (You may need to restart IIS, not sure how everything works on windows)

**Comment by henryp007** [comment]
I have set it as true - what should the .env file be called ? I have just called mine config.env @dmeltzer

**Comment by dmeltzer** [comment]
It needs to be just `.env`, I forget how you do that on windows... you may need to do it on the command line.

**Comment by henryp007** [comment]
that may be where i'm going wrong then - windows by default wont let you just call it .env @dmeltzer

**Comment by dmeltzer** [comment]
https://gist.github.com/ozh/4131243 has a few ideas.

**Comment by henryp007** [comment]
Ok just renamed it using the command line (ren config.env .env) and it doesn't seem to have made a difference :-( @dmeltzer

**Comment by dmeltzer** [comment]
Did you restart IIS after renaming it?

**Comment by korio77** [comment]
have you loaded the url rewritte file on the iis server? i had a lot of troubles the first time with that.

**Comment by henryp007** [comment]
Do you mean the .htaccess file? if so I did import it but one of the Rewright rules failed saying "The rule cannot be converted into an equivalent IIS format because of unsupported flags E 

![image](https://cloud.githubusercontent.com/assets/20864879/17484560/6d3f3ac4-5d82-11e6-9da7-7e3f5be4526c.png)

**Comment by henryp007** [comment]
Hi @dmeltzer yes I did

**Comment by korio77** [comment]
mine ended in this and iirc there was one rule that didnt work in iis

![image](https://cloud.githubusercontent.com/assets/20576635/17484618/153c6dfc-5d8b-11e6-8e39-fa59df55bd61.png)

**Comment by henryp007** [comment]
![image](https://cloud.githubusercontent.com/assets/20864879/17484657/da753a6c-5d82-11e6-9c35-d40cff75a11a.png)
Thats mine on the same page @korio77

**Comment by korio77** [comment]
Also check the iis error logs, if there is no log on the lavarel side is probably because the webserver is not even reaching that, probable there is something wrong on your .env file config.

Be sure you have all the php extensions needed too.

**Comment by henryp007** [comment]
I beleive I have all the PHP extensions enabled - I will try and look through the IIS Logs.. @korio77
![image](https://cloud.githubusercontent.com/assets/20864879/17484736/44572a6c-5d83-11e6-9f7a-950fb1c16fb1.png)

**Comment by korio77** [comment]
I have a couple more enabled but cant remember if it was for snipeip or another thing.

Check the iis logs they will tell you where it falls to load.

IIS is a bit tricky to config if you only have one site, but if you have 2 or more on the same its a pain in the a**.

Just in case it helps here is a pic of my loaded php extensions.

![image](https://cloud.githubusercontent.com/assets/20576635/17484860/29787ed6-5d8c-11e6-8edd-c1b8d5af5a9b.png)


Also for the v3 you need php 5.5.9 or more.

**Comment by henryp007** [comment]
Thanks :-) I'm running PHP 5.6.20 with the same extensions enabled.
I found this log - I dont know if it helps:
::1, -, 8/8/2016, 16:35:29, W3SVC5, sycamores-svr, ::1, 15, 407, 210, 500, 0, GET, /, -,
@korio77

**Comment by henryp007** [comment]
@madd15 your a windows genius for this project - would you be able to offer any advice?
Thanks in advance :+1:

**Comment by korio77** [comment]
afaik that error doesnt tell me anything, can u check the php logs and see if there is anything?

**Comment by henryp007** [comment]
Thanks for the help @korio77  :+1: 

[08-Aug-2016 15:28:29 Europe/Minsk] PHP Warning:  require(C:\Web\Snipe-it\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\Web\Snipe-it\bootstrap\autoload.php on line 17
[08-Aug-2016 15:28:29 Europe/Minsk] PHP Fatal error:  require(): Failed opening required 'C:\Web\Snipe-it\bootstrap/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:\Web\Snipe-it\bootstrap\autoload.php on line 17
[08-Aug-2016 15:28:32 Europe/Minsk] PHP Warning:  require(C:\Web\Snipe-it\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\Web\Snipe-it\bootstrap\autoload.php on line 17
[08-Aug-2016 15:28:32 Europe/Minsk] PHP Fatal error:  require(): Failed opening required 'C:\Web\Snipe-it\bootstrap/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:\Web\Snipe-it\bootstrap\autoload.php on line 17
[08-Aug-2016 15:28:45 Europe/Minsk] PHP Warning:  require(C:\Web\Snipe-it\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\Web\Snipe-it\bootstrap\autoload.php on line 17
[08-Aug-2016 15:28:45 Europe/Minsk] PHP Fatal error:  require(): Failed opening required 'C:\Web\Snipe-it\bootstrap/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:\Web\Snipe-it\bootstrap\autoload.php on line 17
[08-Aug-2016 15:28:51 Europe/Minsk] PHP Warning:  require(C:\Web\Snipe-it\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\Web\Snipe-it\bootstrap\autoload.php on line 17
[08-Aug-2016 15:28:51 Europe/Minsk] PHP Fatal error:  require(): Failed opening required 'C:\Web\Snipe-it\bootstrap/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:\Web\Snipe-it\bootstrap\autoload.php on line 17

**Comment by korio77** [comment]
Seeing that i think you have problems with any of the next stuff:

- Permisions on the folders, as you can see in the error its not opening the stuff because for it there is no file in that path.

- Wrong path.

- Wrong install of composer.

I will check first the composer one, if you check the file 'autoload.php' it loads the composer auto loader and for what i see on the error its not opening it.

**Comment by henryp007** [comment]
![image](https://cloud.githubusercontent.com/assets/20864879/17508077/0c650ce0-5e0b-11e6-90c1-734d7cc7a0cf.png)

I have installed the composer file do i then just open the command line in the snipe-it direcrory and do 

> composer install

**Comment by korio77** [comment]
https://snipe-it.readme.io/docs/install-dependencies

Iirc when i tried to do the steps there was no "Composer install" on the windows explorer view so i openned a cmd admin console, went to that folder and run the command.

Again, has been a while since the last time i installed it so i can be wrong.

Overall the windows installation manual needs a bit of tweaking, but you can have it working with a bit of try/error xD

You are welcome mate, lets see if we can get this fixed.

**Comment by henryp007** [comment]
Yea I didn't have the option either for composer install so I opened up a CMD window and navigated to my snipe-IT folder which is C:\Web\Snipe-IT but when i use the command "Composer Install" I get this set of errors:

![image](https://cloud.githubusercontent.com/assets/20864879/17509895/2441d8b2-5e14-11e6-9497-e10ab03c710f.png)

@korio77

**Comment by korio77** [comment]
Enable the php_fileinfo extension on your iis, restart it, and try again.

**Comment by henryp007** [comment]
Sadly its already enabled - I was hoping this was going to be it ;-)

![image](https://cloud.githubusercontent.com/assets/20864879/17510391/929cde18-5e16-11e6-8cbc-4ffae5dcfc87.png)

@korio77

**Comment by korio77** [comment]
And it throws the same errors? have you 2 or more php versions installed?

Check this, select your site on the iis server, go to php manager.

![image](https://cloud.githubusercontent.com/assets/20576635/17510983/85b21c76-5e21-11e6-88af-131e5c51c5dd.png)


On the next window clink on "Check phpinfo()"

![image](https://cloud.githubusercontent.com/assets/20576635/17511005/9bfbb320-5e21-11e6-9ee6-9133a3e00eee.png)

it will prompt you to choose the url for the selected site, "for me is localhost" click ok.

Then it will show you all the info of php_info, scroll down and look for the fileinfo entry, should be something like this.

![image](https://cloud.githubusercontent.com/assets/20576635/17511106/df4262b4-5e21-11e6-8796-afad44664f45.png)


if it says its enabled then is a problem with the intervention/image you can try to execute this too
composer install --no-dev --prefer-source       (im not really sure if this will work on windows but its worth a try)

**Comment by henryp007** [comment]
I've just tried to re-install composer encase it was pointing towards the wrong PHP Install. The server is just restarting and I will try it again @korio77

**Comment by henryp007** [comment]
Sorry for the delay - I now have composer running !! Just letting it execute and then will give it another shot :+1:  @korio77 

![image](https://cloud.githubusercontent.com/assets/20864879/17512239/c2e6a146-5e1e-11e6-9c65-80a9f66418f1.png)

**Comment by henryp007** [comment]
Wow this is the furthest i've gotten so far @korio77 it now loads a web page but displays an error:
![image](https://cloud.githubusercontent.com/assets/20864879/17512442/b9b3a7f8-5e1f-11e6-9f33-e89f43aaca17.png)

**Comment by korio77** [comment]
alright, thats nice, for the new error here you have the solution!

![image](https://cloud.githubusercontent.com/assets/20576635/17512951/9f42b872-5e2a-11e6-8c73-a315387b179d.png)

its on the common issues of the installation manual!

**Comment by henryp007** [comment]
@korio77 You Legend !!! :+1: 

![image](https://cloud.githubusercontent.com/assets/20864879/17513445/f527f0aa-5e24-11e6-8e15-7f0564baf8be.png)

**Comment by korio77** [comment]
Thats nice! Enjoy it!

**Comment by glennbevan** [comment]
Henry! How did you resolve the issue with importing the rules??

**Comment by snipe** [comment]
Hi @glennbevan - just remove the last rule. IIS for some reason doesn't understand the last rule set. It's not required, so just remove it.

**Comment by glennbevan** [comment]
OK thanks!

I'm not presented with "Whoops, looks like something went wrong". Any ideas??

**Comment by snipe** [comment]
When you hit the Whoops error, that's a laravel-level error. (Laravel is the php framework we use.) When you hit an IIS level error, you won't hit laravel errors because the web server layer is erroring. 

Or did you mean you're "now" presented with a Whoops error? In which case please turn on debugging (as specified in the getting help documentation) and reload for a more verbose stack trace.

**Comment by glennbevan** [comment]
That page has now disappeared and I cant even get to there! I'm getting the following come up within IIS now:
![image](https://cloud.githubusercontent.com/assets/21214889/17926284/4adb3f38-69e8-11e6-9871-852d96aa8e31.png)

**Comment by glennbevan** [comment]
I don't know what has changed but if I go directly to http://localhost:8092/index.php it says "This page can't be displayed". I have no idea what I am doing wrong here. Are you able to help? I am on the gitter room
