### ISSUE TITLE
upgrade from v3.0 beta to v3.2.0

### ISSUE THREAD

**Issue by philknab** [snipe/snipe-it#2413]
i don't know if there is an issue of that but how do i upgrade from v3.0 beta to v3.2.0?
are there the same steps as in https://snipe-it.readme.io/docs/upgrading ? (earlier versions to v3)

greetings phil

**Comment by gdeflaux** [comment]
+1
I am running v3.0.beta2 with Docker and would like to upgrade to v3.2.0. Thanks!

**Comment by snipe** [comment]
@philknab Just follow the release notes and run the commands specified there. 

@gdeflaux you should just be able to grab the newer docker version, no?

**Comment by philknab** [comment]
ok thanks, i haven't thought it would be that simple.!

**Comment by snipe** [comment]
@philknab - we try to make it as easy as possible :)

**Comment by philknab** [comment]
@snipe well it couldn't be easier than this :)

**Comment by gdeflaux** [comment]
@snipe I switched containers to the latest version and it worked fine. Thanks.
