### ISSUE TITLE
Asset Components Tab always shows value as 0

### ISSUE THREAD

**Issue by joepitt91** [snipe/snipe-it#2416]
#### Expected Behavior (or desired behavior if a feature request)

When **Components** are checked out to an **Asset**, the value at the bottom right of the **Components tab** of the **Asset** (which looks like it should be the total value of the assigned Components) changes from "GBP0" to the sum of all **Components** checked out to the **Asset**, e.g. "GBP2,499.95".

---
#### Actual Behavior

With 1 or more **Components** checked out to an **Asset** the value still shows GBP0 - if this is not for showing the total value of **Components** then I have no idea of its purpose.

---
#### Please confirm you have done the following before posting your bug report:
- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running v3.2.0-53-gfff2bce & v3.3.0-3-g7ef4f23
- What OS and web server you're running Snipe-IT on Apache/2.4.18 on Ubuntu 16.04.1
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh (slightly modifed to run mysql-secure-installation manually as the prompts were not shown when running from install.sh/snipeit.sh)
- If you're getting an error in your browser, include that error no error shown
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error /hardware/6/view
- If a stacktrace is provided in the error, include that too. no stacktrace as no error thrown
- Any errors that appear in your browser's error console. no error thrown
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). confirmed
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. none
- Include what you've done so far in the installation, and if you got any error messages along the way. as above had to slightly modify snipeit.sh to not run mysql-secure-installation and run manually, but no errors at all.
- Indicate whether or not you've manually edited any data directly in the database no unedited

**Comment by joepitt91** [comment]
FYI this is still present in v3.3.0-3-g7ef4f23

**Comment by grimstoner** [comment]
Still present in v4.1.3-gb6a14d2

**Comment by joepitt91** [comment]
This issue is still present in v4.4.1, could this issue be reopened?

**Comment by joepitt91** [comment]
I'd expect the 0GBP at the bottom of the page to be calculated as followed:
1. QTY*Purchase Cost for each line item
2. Add all line totals together to get total value of components.
