### ISSUE TITLE
Feature request: Ability to grants rights for USERS (operators) to access the dashboard without giving them ADMIN rights

### ISSUE THREAD

**Issue by SK9413** [snipe/snipe-it#2419]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

It would be really nice that if we can choose to let the user/operator to access the dashboard. Because by doing so we can ensure the operators are well aware of what others operators are doing and without giving them ADMIN rights

![dashboard](https://cloud.githubusercontent.com/assets/15903195/17548026/8d500d34-5f1c-11e6-8c61-0bd3c6a0f1db.jpg)

---
#### Actual Behavior

No options to control the dashboard function.

**Comment by mattgann** [comment]
snipe did this ever happen?

**Comment by snipe** [comment]
If it had, this ticket would be closed.

**Comment by mattgann** [comment]
true

**Comment by ericdude101** [comment]
Hopefully we can see some movement on this soon?

**Comment by snipe** [comment]
@ericdude101 It's unlikely to be addressed in the next version or two. It's very complicated to execute with granular permissions.

**Comment by ericdude101** [comment]
Dont want this to fall off the radar...

**Comment by kmain4** [comment]
Still looking to use this feature. Currently I can't give my inventory admin access to a dashboard without super admin rights to a break everything.

**Comment by knorquist** [comment]
+1 for this feature - we have techs that would like to have the dashboard view, but shouldn't have admin privileges.

**Comment by kanocarra** [comment]
+1 also. Would be very useful

**Comment by Knightrain0** [comment]
Is this no longer a thing?

**Comment by IvanKloss** [comment]
1+ my team would greatly appreciate it

**Comment by wfillmer** [comment]
+1, this would be useful for our organization

**Comment by ItsANoBrainer** [comment]
@snipe This should be opened. Bot is closing things it shouldnt be still. I wonder how many issues and requests are closed because of this.

**Comment by wayneleetw** [comment]
looking for dashboard too, i just want to create a monitor account but not admin permission. looking for it too

**Comment by TonyTheDarkLord** [comment]
+1 Here. Maybe at least if Admin also get the other settings to get granularity 

Thanks in advance

**Comment by avpnaim** [comment]
+1
This is a really important feature. I wonder why it's still not reopened.
Should we open another issue for this feature instead?

**Comment by flardryn** [comment]
+1 for this,

any possibility to add this, near future?

thank you

**Comment by adagioajanes** [comment]
When I think of the dashboard, I think of a view of overall operations. For end users, I can only think of the need to see assets directly under your control or responsibility.

As I say that, I guess if you have hundreds of assets that you are responsible for, a dashboard would be useful in some capacity. 

What features would you find most important in a non-admin dashboard?

**Comment by p-vg** [comment]
I would like the same things on the current dashboard. I just want to be
able to delegate that permission to non-admins. Think the IT department
head that wants to get an idea/1000ft view of what assets are out
there/operations but I don’t necessarily want him to have admin rights to
get in there and mess with the data.

**Comment by flardryn** [comment]
Yes,

I would like to use it as delegation also, where i would like some of my support staff to see overall view/breakdown(total assets, pendings) but not have full admin rights.

I think this can be also fixed by not overriding the rest of the group permissions after applying a admin settings to a group.

This way super admins could create sub groups that has admin like permissions including dashboard access but block any other access that they think its not proper for that group.

**Comment by mwmatter** [comment]
Would love this as an option as well. We have clients where we manage their device inventory and only give clients access to their respective group. Having the dashboard view would be great for them to see and track their own assets.

**Comment by jayavman** [comment]
@snipe  Is this on the radar any time soon?

**Comment by devvonmonahan** [comment]
Also would like this. An overview dashboard page as a permission where they can see breakdowns of categories, number of assets, # of assets at locations etc.. This would be for someone who doesn't need to make any changes on SnipeIT but may want to overlook these details/numbers... Say, an IT manager or, at an MSP, account manager.

**Comment by p-vg** [comment]
This has been a request since 2016. It’s very obvious it’s not happening and they don’t care to make it happen.

**Comment by komodin** [comment]
+1 it will be nice if this can be added

**Comment by Veljko4GH** [comment]
+1

**Comment by vi4869** [comment]
+1

**Comment by leitwerk-ag** [comment]
would also appreciate this feature

**Comment by gifxz** [comment]
+1

**Comment by joelscampos** [comment]
I was wondering whether this feature was implemented. It would be a nice one.

**Comment by PatriceGanon** [comment]
+1

**Comment by brianIcke** [comment]
+1 for this

**Comment by PJSmithLife** [comment]
+1
