### ISSUE TITLE
Custom fieldset order not saved

### ISSUE THREAD

**Issue by Sam-Glerum** [snipe/snipe-it#2420]
#### Expected Behavior (or desired behavior if a feature request)

I am trying to change the Field sorting-order in a Custom Fieldset.
I drag the Fields into the right sorting-order I want them in, and check an asset to see that the order has been changed.

---
#### Actual Behavior

(what actually happens goes here)
I drag the Fields into the right sorting-order I want them in, and I check an asset to see if the order of the Fields was changed correctly.
#### Please confirm you have done the following before posting your bug report:
- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)
  I've also tried this in the demo, the same thing happens here.

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running: v3.2.0-53-gfff2bce
- What OS and web server you're running Snipe-IT on: Ubuntu 14.04.05 LTS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): install.sh
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Page: custom_fields/custom_field_id | Element: Custom Field
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). It is reproducable
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. I haven't gotten any error messages- Indicate whether or not you've manually edited any data directly in the database. I have not

**Comment by imie** [comment]
im also having this bug issue. Running on Version v3.6.0-pre-41-ga914dac

**Comment by snipe** [comment]
This is fixed in the new release.
