### ISSUE TITLE
Not able to install Snipe-IT 3 on XAMPP v3.2.2 and Windows 7

### ISSUE THREAD

**Issue by pvhkai** [snipe/snipe-it#2421]
Hi,
first of all I tried to install snipeit locally as a test environment but I think I am wrong with something. Here are the steps I made to get SnipeIT working on my local system:

- Downloaded XAMPP / GIT / Composer (for windows)
- Installed XAMPP and started Apache and MySQL
- Installed GIT
- Downloaded the Git Project by commandline (git clone https://github.com/snipe/snipe-it "c:\xampp\htdocs\snipe-it")
- Installed the Composer (with the PHP Path C:\xampp\php\php.exe) 
- Edited the Apache-server ( C:\xampp\apache\conf\extra\httpd-vhosts.conf) to the following:

<VirtualHost *:80>
    DocumentRoot "C:/xampp/htdocs/snipe-it/public"
    ServerName localhost
    SetEnv LARAVEL_ENV local
</VirtualHost>

- Created a MySQL User and Database (USR/DB/PW is called snipe-it) (it is just a test environment)
- Renamed the .env.example to .env (C:\xampp\htdocs\snipe-it) and filled in the SQL data and Mailing data (using google mail)
- Opened console and tried to create the artisan key. I went to the snipe-it folder and typed the following.. 

C:\xampp\htdocs\snipe-it>php artisan key:generate

Error message:
PHP Warning:  require(C:\xampp\htdocs\snipe-it\bootstrap/../vendor/autoload.php)
: failed to open stream: No such file or directory in C:\xampp\htdocs\snipe-it\b
ootstrap\autoload.php on line 17

Warning: require(C:\xampp\htdocs\snipe-it\bootstrap/../vendor/autoload.php): fai
led to open stream: No such file or directory in C:\xampp\htdocs\snipe-it\bootst
rap\autoload.php on line 17
PHP Fatal error:  require(): Failed opening required 'C:\xampp\htdocs\snipe-it\b
ootstrap/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\
htdocs\snipe-it\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\snipe-it\bootst
rap/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdoc
s\snipe-it\bootstrap\autoload.php on line 17

- By opening the http path http://localhost I get the following error:

Warning: require_once(C:\xampp\htdocs\snipe-it\bootstrap/composer/autoload_real.php): failed to open stream: No such file or directory in C:\xampp\htdocs\snipe-it\bootstrap\autoload.php on line 5

Fatal error: require_once(): Failed opening required 'C:\xampp\htdocs\snipe-it\bootstrap/composer/autoload_real.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\snipe-it\bootstrap\autoload.php on line 5

It is the first time I have to work with the composer (but not the first time I use PHP and SQL...). So here is my question... what did I do wrong... :(

Thanks
Kai

**Comment by xmano** [comment]
After installing code composer, you need to run composer install in the snipe-it base directory. 

If every thing goes well, upon opening the url you should see **Snipe-IT Pre-Flight** page.

**Comment by pvhkai** [comment]
thanks for your quick response. What code does I need to type in if I want to install that composer to the snipe-it folder based on c:\xampp\htdocs\snipe-it\

**Comment by philknab** [comment]
php composer.phar install --no-dev --prefer-source

**Comment by pvhkai** [comment]
I get this error codes after typing in that code line... :(


![untitled](https://cloud.githubusercontent.com/assets/20946690/17554851/395283b0-5f0d-11e6-8c44-30ab15899304.png)

**Comment by pvhkai** [comment]
Hi I get the same error at http..

Warning: require_once(C:\xampp\htdocs\snipe-it\bootstrap/composer/autoload_real.php): failed to open stream: No such file or directory in C:\xampp\htdocs\snipe-it\bootstrap\autoload.php on line 5

Fatal error: require_once(): Failed opening required 'C:\xampp\htdocs\snipe-it\bootstrap/composer/autoload_real.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\snipe-it\bootstrap\autoload.php on line 5

**Comment by philknab** [comment]
https://snipe-it.readme.io/docs/common-issues maybe this will help

**Comment by pvhkai** [comment]
Hi Phil,
thanks for your answer...

I made the workaround from the common issues page but then I get another errormessage... It is really confusing. 

![untitled](https://cloud.githubusercontent.com/assets/20946690/17581911/fad932c2-5fa8-11e6-9038-405324673a60.png)

**Comment by snipe** [comment]
Try updating composer (`composer selfupdate`) to the latest version, and then running:

```
composer clear
composer dump
```

**Comment by pvhkai** [comment]
Thanks.. that worked well! 👍
