### ISSUE TITLE
Feature Request - Bulk Edit Users

### ISSUE THREAD

**Issue by veen1981** [snipe/snipe-it#2422]
#### Expected Behavior (or desired behavior if a feature request)

We are now using the multiple company support option to separate assets maintained by our different IT Departments. This is requiring me to edit the company for all of our users imported by LDAP. Currently I would need to edit over 4500 users one-by-one to change the company as this field was not imported. There should be a bulk edit option for users that would allow for modification of company, manager and location, and possibly group. 

---
#### Actual Behavior

The only bulk option under users is currently "Bulk Checkin & Delete"

---
#### Please confirm you have done the following before posting your bug report:
- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running    v3.2.0-53-gfff2bce
- What OS and web server you're running Snipe-IT on Centos 7 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual
- If you're getting an error in your browser, include that error N/A

**Comment by henryp007** [comment]
This would be super useful - I have the same problem - just imported a load of users and assets but no way to bulk edit the user details such as location.

**Comment by delize** [comment]
Would also like to upvote this. Having the ability to bulk-edit the location field would be awesome, as I just imported about 160 people from our Active Directory system with varying location fields. Editing them by hand won't be a fun process (and I have no intern). :)

**Comment by wezardstark** [comment]
Indeed, i cant work out if its just me or if you can only add users to groups one at a time?

I have over 900 to give varying permissions too, adding users to a group in bulk would be ideal.

**Comment by snipe** [comment]
This will be rolled into the v4 release

**Comment by vstephanou** [comment]
Sorry for replying on a closed issue, but I'm bulk editing several users to change their location, but the change isn't propagated to the assets. However, when I change a single user's location, assets are moved to the new location.
