### ISSUE TITLE
time format

### ISSUE THREAD

**Issue by philknab** [snipe/snipe-it#2423]
is it possible to change the time format from: 

![time](https://cloud.githubusercontent.com/assets/20083949/17552867/c4c3084e-5f02-11e6-8c5a-78537c792ff7.JPG)

to 

10.August.2016 13:39

greets, phil

**Comment by philknab** [comment]
well wasn't that hard, did it by myself. CLOSED

**Comment by wh0else** [comment]
Hi, @philknab 

Mind mentioning how you solved this? In Norway we are used to dd.mm.yy(yy) and would like to change this.

Best regards, 
Jørgen

**Comment by snipe** [comment]
The ability to change date/time formats will be available in v4.

**Comment by gokkstudio** [comment]
Hi, I'm using v4.0.9 build 120 (gf66e222) and cannot change from:
10/18/2017 to 18/10/2017, ideally I would need 18.10.2017

any solution to that?
thanks

**Comment by snipe** [comment]
>  and cannot change from: 10/18/2017 to 18/10/2017

What does this mean? Are you getting an error?

**Comment by gokkstudio** [comment]
No, no errors. 
I just need option (or solution) to display date like this:
18.10.2017 (dd.mm.yyyy)

sorry if I wasn't clear that its date what I'm talking about.
Thanks Snipe

**Comment by ebonweaver** [comment]
Changing the date format in Localization does nothing, or at least has no actual impact on date fields.  Input and display is still yyyy-mm-dd even when Localization is set to mm/dd/yyyy
