### ISSUE TITLE
FEATURE REQUEST - Import users profile pics from AD on LDAP sync

### ISSUE THREAD

**Issue by ghost** [snipe/snipe-it#2424]
It would be awesome if we could pull through the users profile pic / avatar from AD whilst importing via LDAP.

Sounds easy - probably tons of work ;)

**Comment by smccloud** [comment]
While I think this is a nice idea.  From an admin standpoint, adding a pic to a user in AD is a PITA and very few people where I work have it.

**Comment by snipe** [comment]
Yeah, that's why we went the gravatar route ;)
