### ISSUE TITLE
PDOException in Connector.php line 55

### ISSUE THREAD

**Issue by cmkhoury** [snipe/snipe-it#2425]
#### Expected Behavior (or desired behavior if a feature request)
Pre-Flight page loads.

-----

#### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/20669369/17557890/8167b5fa-5ede-11e6-9db2-09f5f1e0a5bc.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [yes] I have enabled debug mode
- [yes] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: V 3.2
- What OS and web server you're running Snipe-IT on: Windows 10, IIS (testing environment)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual installation
- If you're getting an error in your browser, include that error: PDOException in Connector.php line 55:
SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: assets.portal.local
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). :no

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
This is my PHP error log:
>handle(Array)
#2 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13620): Monolog\Logger->addRecord(400, Object(UnexpectedValueException), Array)
#3 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13315): Monolog\Logger->error(Object(UnexpectedValueException), Array)
#4 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13286): Illuminate\Log\Writer->writeLog('error', Object(UnexpectedValueException), Array)
#5 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(57): Illumi in C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php on line 13832
[09-Aug-2016 18:48:21 UTC] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "C:\inetpub\wwwroot\Snipe-IT\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php:13832
Stack trace:
#0 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13762): Monolog\Handler\StreamHandler->write(Array)
#1 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13522): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13620): Monolog\Logger->addRecord(400, Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#3 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13315): Monolog\Logger->error(Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#4 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13286): Illuminate\Log\Writer->writeLog('error', Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#5 C:\inetpub\wwwroot\Snipe-I in C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php on line 13832
[09-Aug-2016 18:49:07 UTC] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "C:\inetpub\wwwroot\Snipe-IT\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php:13832
Stack trace:
#0 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13762): Monolog\Handler\StreamHandler->write(Array)
#1 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13522): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13620): Monolog\Logger->addRecord(400, Object(UnexpectedValueException), Array)
#3 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13315): Monolog\Logger->error(Object(UnexpectedValueException), Array)
#4 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13286): Illuminate\Log\Writer->writeLog('error', Object(UnexpectedValueException), Array)
#5 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(57): Illumi in C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php on line 13832
[09-Aug-2016 18:49:07 UTC] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "C:\inetpub\wwwroot\Snipe-IT\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php:13832
Stack trace:
#0 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13762): Monolog\Handler\StreamHandler->write(Array)
#1 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13522): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13620): Monolog\Logger->addRecord(400, Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#3 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13315): Monolog\Logger->error(Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#4 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13286): Illuminate\Log\Writer->writeLog('error', Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#5 C:\inetpub\wwwroot\Snipe-I in C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php on line 13832
[09-Aug-2016 19:00:26 UTC] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "C:\inetpub\wwwroot\Snipe-IT\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php:13832
Stack trace:
#0 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13762): Monolog\Handler\StreamHandler->write(Array)
#1 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13522): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13620): Monolog\Logger->addRecord(400, Object(UnexpectedValueException), Array)
#3 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13315): Monolog\Logger->error(Object(UnexpectedValueException), Array)
#4 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13286): Illuminate\Log\Writer->writeLog('error', Object(UnexpectedValueException), Array)
#5 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(57): Illumi in C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php on line 13832
[09-Aug-2016 19:00:26 UTC] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "C:\inetpub\wwwroot\Snipe-IT\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php:13832
Stack trace:
#0 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13762): Monolog\Handler\StreamHandler->write(Array)
#1 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13522): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13620): Monolog\Logger->addRecord(400, Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#3 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13315): Monolog\Logger->error(Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#4 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13286): Illuminate\Log\Writer->writeLog('error', Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#5 C:\inetpub\wwwroot\Snipe-I in C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php on line 13832
[09-Aug-2016 19:19:00 UTC] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "C:\inetpub\wwwroot\Snipe-IT\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php:13832
Stack trace:
#0 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13762): Monolog\Handler\StreamHandler->write(Array)
#1 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13522): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13620): Monolog\Logger->addRecord(400, Object(UnexpectedValueException), Array)
#3 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13315): Monolog\Logger->error(Object(UnexpectedValueException), Array)
#4 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13286): Illuminate\Log\Writer->writeLog('error', Object(UnexpectedValueException), Array)
#5 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(57): Illumi in C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php on line 13832
[09-Aug-2016 19:19:00 UTC] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "C:\inetpub\wwwroot\Snipe-IT\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php:13832
Stack trace:
#0 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13762): Monolog\Handler\StreamHandler->write(Array)
#1 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13522): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13620): Monolog\Logger->addRecord(400, Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#3 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13315): Monolog\Logger->error(Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#4 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13286): Illuminate\Log\Writer->writeLog('error', Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#5 C:\inetpub\wwwroot\Snipe-I in C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php on line 13832
[09-Aug-2016 19:41:00 UTC] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "C:\inetpub\wwwroot\Snipe-IT\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php:13832
Stack trace:
#0 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13762): Monolog\Handler\StreamHandler->write(Array)
#1 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13522): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13620): Monolog\Logger->addRecord(400, Object(UnexpectedValueException), Array)
#3 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13315): Monolog\Logger->error(Object(UnexpectedValueException), Array)
#4 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13286): Illuminate\Log\Writer->writeLog('error', Object(UnexpectedValueException), Array)
#5 C:\inetpub\wwwroot\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(57): Illumi in C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php on line 13832
[09-Aug-2016 19:41:00 UTC] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "C:\inetpub\wwwroot\Snipe-IT\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php:13832
Stack trace:
#0 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13762): Monolog\Handler\StreamHandler->write(Array)
#1 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13522): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13620): Monolog\Logger->addRecord(400, Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#3 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13315): Monolog\Logger->error(Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#4 C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php(13286): Illuminate\Log\Writer->writeLog('error', Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#5 C:\inetpub\wwwroot\Snipe-I in C:\inetpub\wwwroot\Snipe-IT\bootstrap\cache\compiled.php on line 13832

- Include what you've done so far in the installation, and if you got any error messages along the way.
I had to enable more PHP extensions which seemed to take care of the beginning of the .log file, and I had to give the IIS user account access to the entire Snipe-IT folder because I was getting user permission errors. I am not sure that I have configured a database correctly for Snipe-IT. I have a database (MYSQL) already on my machine, but it is independent of Snipe-IT

- Indicate whether or not you've manually edited any data directly in the database: I have not manually edited any data.

**Comment by snipe** [comment]
If you get a PDO error on pre-flight, the DB info you set in your .env is wrong.
