### ISSUE TITLE
Component Order Number Truncated

### ISSUE THREAD

**Issue by joepitt91** [snipe/snipe-it#2427]
#### Expected Behavior (or desired behavior if a feature request)

When entering a Order number with hyphens in it, e.g. an Amazon Order Number (xxx-xxxxxxx-xxxxxxx) the full order number is stored. as is done for Assets and Accessories.

---
#### Actual Behavior

When entering a Order number with hyphens in it, e.g. an Amazon Order Number (xxx-xxxxxxx-xxxxxxx) the first components is stored, with the rest being dropped, e.g. stored value ends up as 203.

---
#### Please confirm you have done the following before posting your bug report:
- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running v3.2.0-53-gfff2bce
- What OS and web server you're running Snipe-IT on Ubuntu 16.04.1
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh (slightly modified to run mysql-secure-installation manually as the prompts were not shown when running from install.sh/snipeit.sh)
- If you're getting an error in your browser, include that error no error shown
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error /admin/components/create
- If a stacktrace is provided in the error, include that too. no stacktrace as no error thrown
- Any errors that appear in your browser's error console. no error thrown
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). confirmed (https://demo.snipeitapp.com/admin/components/21/view) entered 203-1234567-7654321 - stored 203
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. none
- Include what you've done so far in the installation, and if you got any error messages along the way. as above had to slightly modify snipeit.sh to not run mysql-secure-installation and run manually, but no errors at all.
- Indicate whether or not you've manually edited any data directly in the database no unedited

**Comment by dmeltzer** [comment]
This is because in the database, the `order_number` field on the components table is an integer, but the `order_number` field on everything else is a varchar.  I'm not sure how easy it is to migrate such a thing.

**Comment by joepitt91** [comment]
I'd agree as I also have some order numbers with Alpha characters in too, e.g. GB123321123
