### ISSUE TITLE
AD Users synchronization issue from LDAP 

### ISSUE THREAD

**Issue by chaitanyan123** [snipe/snipe-it#2430]
#### Expected Behavior (or desired behavior if a feature request)

We have integrated our tool with my A.D and i am expecting from our tool to pull all the User information from my A.D, when i proceed with Synchronize in our tool. 

-----

#### Actual Behavior

But, when i proceed with synchronize option, it giving me the error as attached.

![snipeit ldap](https://cloud.githubusercontent.com/assets/20687774/17587838/67063708-5fe8-11e6-8795-acc9deaec00a.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running **v3.1.0-29-gd6ba0b6** 
- What OS and web server you're running Snipe-IT on **Ubuntu 14.0**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **install.sh**
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **example.com/admin/users/ldap**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Without seeing your AD settings, I'm not sure how you'd expect us to be able to help you. Most likely your base bind DN or search filter is wrong.

**Comment by IxFail** [comment]
Please show us your LDAP settings from the admin  panel.
