### ISSUE TITLE
Feature Request: Scheduled LDAP Sync and Backup

### ISSUE THREAD

**Issue by gsoyka** [snipe/snipe-it#2432]
#### Expected Behavior (or desired behavior if a feature request)
It would be nice to be able to schedule a daily or weekly LDAP sync and backup through the web interface.  If it's possible to do at the command line via cron, that would work as well.
-----

**Comment by stevecookms** [comment]
I second that!

**Comment by mattgann** [comment]
Agreed

**Comment by snipe** [comment]
This is a duplicate of #1348
