### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by mergimgj** [snipe/snipe-it#2433]
#### Expected Behavior (or desired behavior if a feature request)

Upgraded from verison 2 to version 3.2 and i get this error
#### Actual Behavior

(what actually happens goes here)

---
#### Please confirm you have done the following before posting your bug report:
- [ yes] I have enabled debug mode
- [ yes] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running 3.2
- What OS and web server you're running Snipe-IT on ubuntu
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) clone
- If you're getting an error in your browser, include that error
  ErrorException in /var/www/snipeit/app/Models/User.php line 88:
  array_key_exists() expects parameter 2 to be array, null given
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

[error.pdf](https://github.com/snipe/snipe-it/files/414213/error.pdf)

**Comment by snipe** [comment]
Please tell us what specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error, as requested in the Getting Help documentation and the Github issue template. Also please tell us if you use you're looking at (or logged in as?) is a super user and whether they belong to any permission groups.

**Comment by tx7** [comment]
I just updated it today, and I got the same error:

cipher type:
'cipher' => 'rijndael-256',

error:
`RuntimeException in compiled.php line 7771:
No supported encrypter found. The cipher and / or key length are invalid.`

**Comment by tx7** [comment]
I found the issue, my server is missing the mcrypt extension:

`sudo apt-get install php5-mcrypt`

**Comment by snipe** [comment]
@tx7 later versions of Snipe-IT won't require mcrypt (since it's deprecated) but we need to run a migrator to decrypt any encrypted fields before we can move everyone officially over to OpenSSL.
