### ISSUE TITLE
Ready to deploy Checkout to field 

### ISSUE THREAD

**Issue by djdamith** [snipe/snipe-it#2435]
When creating new asset and assign it to a user with ready to deploy.

When a new asset created and i wanted to assign that asset to a user using Ready to Deploy Status, the users selection ( Checkout to field ) field not loading it keeps showing green circle rotating ( Screen shot attached )
![snipe](https://cloud.githubusercontent.com/assets/18014050/17612223/2e45de48-606d-11e6-88fa-0d79833bb9ef.PNG)

I have enabled the debugging

-----

- SnipeIT Version      -    v3.0-ebc74a65
- Running on WAMP Server on Win 10 ENT
- WAMP SERVRER
- feature working on demo
-This Error was on Storage /laravel.log not sure its related

[2016-08-05 10:47:33] production.ERROR: exception 'ErrorException' with message 'mcrypt_encrypt(): Key of size 8 not supported by this algorithm. Only keys of sizes 16, 24 or 32 supported' in C:\wamp64\www\snipe\vendor\laravel\framework\src\Illuminate\Encryption\McryptEncrypter.php:104
Stack trace:

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that errorr
- Any errors that appear in your browser's error console.

**Comment by djdamith** [comment]
HI Snipe,

* I have host the app in WAMP server and did the configuration on .env file for MySQL instances
*In browser i don't get any error  when i select the Ready to deploy status it tries to load the user list but that Check out to field never shows up.
*In browser console i receive the following error ( screen shot attached )

![error browser](https://cloud.githubusercontent.com/assets/18014050/17613619/e686a154-607c-11e6-84e2-f4d80c1d86db.PNG)

**Comment by snipe** [comment]
Why is it trying to grab the setup page in the first place? If you have tables, it shouldn't be looking for setup. Are you sure those aren't old errors?

**Comment by djdamith** [comment]
Hi Snipe,

I have resolved the issue , it was in the  .env APP URL .. it was pointing the localhost:8888/snipe/public/setup . i have change it to snipe/public. now its working fine.. 

Thanks for the trouble. :)

**Comment by dmeltzer** [comment]
You shouldn't need the /public in the app_url either, the mod_rewrite should redirect everything.

**Comment by abdomordy** [comment]
i have the same issue and i need a solution for it and i changed the app_url but it's the same
![asset1](https://user-images.githubusercontent.com/33280308/32267989-d568b168-bef5-11e7-8bbc-abdcb6752bb9.png)
![asset2](https://user-images.githubusercontent.com/33280308/32267990-d589e072-bef5-11e7-8dfd-c6e0cba62ae2.png)

**Comment by snipe** [comment]
@abdomordy https://snipe-it.readme.io/docs/common-issues#section-changes-to-my-env-file-dont-seem-to-be-updating

**Comment by snipe** [comment]
@abdomordy (Also, the URL in that env looks wrong. As mentioned it should not have public in the URL)

**Comment by abdomordy** [comment]
i make it default before but it's the same , my old url is the IP address for my server

**Comment by snipe** [comment]
> i make it default before but it's the same , my old url is the IP address for my server

I don't understand what this means.

**Comment by abdomordy** [comment]
you said this words 
 (Also, the URL in that env looks wrong. As mentioned it should not have public in the URL)
so i said i made it like that APP_URL=http://192.168.1.242 and the same error is found.

**Comment by snipe** [comment]
@abdomordy you haven't actually told me that the error is.

**Comment by abdomordy** [comment]
please review the question above 
![gggg](https://user-images.githubusercontent.com/33280308/32327717-3a987312-bfe0-11e7-899a-c2854657c5a0.png)

**Comment by snipe** [comment]
@abdomordy Yes, and the answer was already provided in my original reply. If you're getting errors (browser or in your app log), you need to provide those to me. Also, I don't even know what version you're running. 

Please provide answers to these questions.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by abdomordy** [comment]
-Snipe-IT version is v4.0.15 build 384.
-OS version  :centos 7 and the server is  httpd .
-installed manually .
-no any error .
-assets , all updeployable .
-i installed fresh version and backed up the old database from my old running verion.
-there is no path in /app/storage/logs

**Comment by abdomordy** [comment]
you can use this teamviewer id now to see you what is the issue. (213 729 547) with password (142nnu)

**Comment by snipe** [comment]
> there is no path in /app/storage/logs

? What does that mean?

> assets , all updeployable .

Does that mean they are showing up in the All Assets list as undeployable? Please provide screenshots. 

Try upgrading to latest and see if that resolves your issue,

**Comment by abdomordy** [comment]
i have the latest version 
![ffff](https://user-images.githubusercontent.com/33280308/32329062-8d07932c-bfe4-11e7-8d06-64a2fb383ae6.png)

**Comment by snipe** [comment]
> Does that mean they are showing up in the All Assets list as undeployable? 

You're not giving me any useful information here.

**Comment by abdomordy** [comment]
when i choose  ready to deploy i can't assign this device to any one because there is no new tap opened

**Comment by abdomordy** [comment]
![ff](https://user-images.githubusercontent.com/33280308/32329693-6c639434-bfe6-11e7-9478-b1e87f97c10f.png)
![ffff](https://user-images.githubusercontent.com/33280308/32329690-69c4c450-bfe6-11e7-9e5b-eac8d1274973.png)

**Comment by snipe** [comment]
Screenshot your status labels listing page please.

**Comment by abdomordy** [comment]
![1](https://user-images.githubusercontent.com/33280308/32330786-db83d556-bfe9-11e7-8dbb-6a2f4255071a.png)
![2](https://user-images.githubusercontent.com/33280308/32330787-dba5f9a6-bfe9-11e7-9ad8-d8104a4a772c.png)

**Comment by snipe** [comment]
Status labels page. Not assets.

**Comment by abdomordy** [comment]
please said what are u need from me specifically to help not to make a big chatting discussion without any benefit.

**Comment by madd15** [comment]
Please provide a screenshot of `Settings -> Status Labels` ([http://192.168.1.242/statuslabels](http://192.168.1.242/statuslabels))

**Comment by abdomordy** [comment]
![dd](https://user-images.githubusercontent.com/33280308/32427228-fd5bd760-c2c7-11e7-97bc-e64bb54a5ee8.png)
