### ISSUE TITLE
Plaintext Password sent

### ISSUE THREAD

**Issue by empwilli** [snipe/snipe-it#2438]
#### Expected Behavior (or desired behavior if a feature request)

After the initial installation there is the possibility to send the credentials for the admin account to the provided e-mail address. The password should _not_ be sent in plain text, or at least, there should be a warning that the password will be sent, as well.

-----

#### Actual Behavior

The password is sent (probably over an insecure connection) thus making this very vulnuable to man-in-the-middle attacks.
-----

#### Please provide answers to these questions before posting your bug report:

- Debug-Mode: No
- Version of Snipe-IT: v3.2.0-53-gfff2bce
- OS: Debian Jessie in a Docker Container
- Manual Installation
- /snipe-it/setup -> Complete setup, admin account generation

**Comment by snipe** [comment]
If you don't want to se d your password, don't click the box to send the password. Also you can change it the moment you login. This is not a bug.
