### ISSUE TITLE
Error when generating Backup

### ISSUE THREAD

**Issue by cduverne** [snipe/snipe-it#2439]
#### Expected Behavior (or desired behavior if a feature request)

Backups to be generated from the webpage

-----

#### Actual Behavior

Webpage answer that the backup is correctly created, but nothing appear in the list and the directory is empty.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running : 3.1
- What OS and web server you're running Snipe-IT on : Snipe IT Docker image on Linux Ubuntu 14.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) : Docker
- If you're getting an error in your browser, include that error : none in the browser
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error : Generate backup button on https://snipeit.euranova.eu/admin/settings/backups
- If a stacktrace is provided in the error, include that too. : 
```[2016-08-12 06:21:58] production.ERROR: backups backups : error: Failed to backup  because: The dump process failed with exitcode 127 : Command not found : sh: 1: /usr/local/bin/mysqldump: not found
```
- Any errors that appear in your browser's error console. None
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). 
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. 
```[2016-08-12 06:21:58] production.ERROR: backups backups : error: Failed to backup  because: The dump process failed with exitcode 127 : Command not found : sh: 1: /usr/local/bin/mysqldump: not found
```
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database : No manual edit

**Comment by cduverne** [comment]
Found a workaround by locating the mysqldump bin and creating a symlink : 

```
root@78e2060d5f9e:/var/www/html/storage/logs# ln -sv /usr/bin/mysqldump /usr/local/bin/mysqldump
'/usr/local/bin/mysqldump' -> '/usr/bin/mysqldump'
```

**Comment by snipe** [comment]
Setting the MySQL dump path in the .env didn't work?

**Comment by cduverne** [comment]
I didn't find this variable in https://snipe-it.readme.io/docs/docker 
But now that you're mentionning I searched it in the global list here https://snipe-it.readme.io/docs/configuration

Being : ```DB_DUMP_PATH='/usr/local/bin'```, right ?

Might be interesting to add it to the Docker conf also, so everybody sees it.

Thanks a lot !

**Comment by snipe** [comment]
Did it work when you added it?

**Comment by roq-messaging** [comment]
Yes it did !

Thanks for your help !

**Comment by cduverne** [comment]
Yes it did !

Thanks a lot.
