### ISSUE TITLE
When using the Slack webhook, getting what seems like buggy behavior when checking out a component to hardware asset.

### ISSUE THREAD

**Issue by dtun** [snipe/snipe-it#2441]
#### Expected Behavior

>Checked Out:
>COMPONENT 30-pin to 30-pin/HDMI checked out to **NameOrDescriptionOfAsset** by Danny

#### Actual Behavior

>Checked Out:
>COMPONENT 30-pin to 30-pin/HDMI checked out to **domain/hardware/94/view** by Danny

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running. v3.2.0-53-gfff2bce
- What OS and web server you're running Snipe-IT on. OS X, Windows
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error. Attempting to check out a component to an asset.
- Indicate whether or not you've manually edited any data directly in the database: No

**Comment by snipe** [comment]
Does the asset actually have a name?

**Comment by dtun** [comment]
Thank you for the quick reply. Yes, it does appear to have a name. However, I also see based on the history there was an update to this asset by another admin. I will find out whether the update was to add a name and report back if it did not have a name at the time this was filed.
