### ISSUE TITLE
Have Some Haiku :)

### ISSUE THREAD

**Issue by tomowaw** [snipe/snipe-it#2444]
Hi,

I've updated version 3.2.0 to beta version 3.3.0 (CentOS7 Core). When I click: Admin -> Manufacturers -> New, on the right side I'm getting

"Have Some Haiku

Serious error.
All shortcuts have disappeared.
Screen. Mind. Both are blank.". This is first thing I have found."

On demo site same problem exists.

Regards
Tomasz

**Comment by snipe** [comment]
That's not a problem, it's a haiku. It was there in 3.0 as well.
