### ISSUE TITLE
Bulk Checkout - Only for Super User?

### ISSUE THREAD

**Issue by syb1234** [snipe/snipe-it#2446]
Hi Snipe,

Thank you for this great inventory system.  I've been testing the "bulk checkout" feature and there seems to be an issue where I can only have this feature working for a "super user".  

I've created a group called "admin" and gave all the permissions except to be "Global: Super User".  I've added a test user to this group then after login in as this new user I go the the menu "Assets" / "Bulk Checkout" then I click in the field "assets" (where the available assets should come up) but instead I get the message "No results found".

Did I missed a permission somewhere?

Thank you for your time,
Sylvain

Sorry, here is the missing info:
- **Version of Snipe-IT you're running:** v3.2.0-53-gfff2bce
- **What OS and web server you're running Snipe-IT on:** CentOS 7 using VMWare Fusion 8
- **What method you used to install Snipe-IT (install.sh, manual installation, docker, etc):** install.sh
- **If you're getting an error in your browser, include that error:** no error
- **What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error:** localhost/hardware/bulkcheckout
- **If a stacktrace is provided in the error, include that too.**
- **Any errors that appear in your browser's error console.:** no error
- **Confirm whether the error is reproduceable on the demo.:** No, I can not create user and assign it to the group "admin-test" that I've created. Not enough permissions on the demo.
- **Include any additional information you can find in app/storage/logs and your webserver's logs.:**
- **Include what you've done so far in the installation, and if you got any error messages along the way.:** I've installed  a new VMWare Fusion machine with CentOS 7 and installed Snipe-It 3.2 using the install.sh script.  After the successful installation I've copied pasted an existing database from a Snipe-it v2.1.2 and followed the instructions from the web page "[Upgrade to v3.0](https://snipe-it.readme.io/docs/upgrading)" from step 4. After the upgrade I was able to use the system without issues. I did not see any error message.
- **Indicate whether or not you've manually edited any data directly in the database:** I've copied and pasted an older database from V2.1.2 onto the new 3.2.0 database then ran the upgrade steps.

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
If it says no results found, there must be a browser error. Please check your browser console.

**Comment by syb1234** [comment]
Ok, I've tested the function on a fresh install and it works.  There's been an issue while upgrading from v2.1.2 to 3.2.0 for me.  I'll try the upgrade again.

Thanks for your quick reply snipe,

Sylvain

**Comment by syb1234** [comment]
After upgrading a second time following carefully the instructions everything works well.

Thank you

**Comment by syb1234** [comment]
I've now upgraded a second time carefully using the upgrade to 3.0 again but I'm still having the same result.  If a non "super user" try to use the "bulk checkout" feature and click in the field "assets" I still get the message "No results found".

I've tried creating a new user and a new group but I still get the same message.  This only happens after upgrading my previous install from v2.1.2. Starting from a clean install works well.

I've checked the browser console but I cannot see any issues.

Thanks

**Comment by snipe** [comment]
Can you provide some screenshots? I can't reproduce this, so I'm not sure if I'm even looking at the right thing.

**Comment by syb1234** [comment]
Yes, I will send them to you tomorrow morning.

Thank you,

Sylvain

**Comment by syb1234** [comment]
Good morning,

Here are screenshots from a super user and regular user.  Even with all the
permissions granted (except for being "super user") I have the same result.

I've included a screenshot of the dashboard so you can see that the regular
user "studior" has access to some assets.

Thanks,

Sylvain

**Comment by snipe** [comment]
Can you show me a screenshot of the permissions for the non-super-user and any groups they're in? I am still unable to reproduce this.

**Comment by snipe** [comment]
Also please confirm whether you're using full company support, and if you are, if the non-super-user is assigned to a company.

**Comment by syb1234** [comment]
Yes,  I use the company as department for our school.  Each company has assets assigned to them and each user are assigned to a company.

**Comment by snipe** [comment]
Only superadmins can see assets across different companies.

**Comment by syb1234** [comment]
Yes, I can confirm this.

**Comment by snipe** [comment]
Right, that's by design. So I'm not sure what the issue is here?

**Comment by syb1234** [comment]
I did a new install from scratch and the system works fine by itself.  When I transferred over the database that I've upgraded from v2.1.2 to the new install and by changing the database key the issue came back.

The issue has to be in the database that I have.

**Comment by snipe** [comment]
Have you tried editing and reserving the permissions on the user/groups the user is in?

**Comment by syb1234** [comment]
I've compared them side by side and can see sections from the older database that do not exists in the fresh database.  I can give you some example if you want.  in the older db I can see that some value are set to 00:00:00..

**Comment by syb1234** [comment]
Yes, I've tried editing the group's permissions and also the user permissions but still not working/

**Comment by snipe** [comment]
This doesn't sound like a permissions issue, it sounds like a company-scoping issue. If the user is assigned to a company, it won't be able to see assets from another company. That's by design.

**Comment by syb1234** [comment]
As an example:

In the working db I have at line 58:
`created_at` timestamp NULL DEFAULT NULL

In the other I have:
`created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',

Is this normal?

**Comment by snipe** [comment]
That doesn't matter, and wouldn't have any impact on anything. This is a company scoping issue.

**Comment by syb1234** [comment]
Ok, there might be something in the user's info in the db that creates the issue.

**Comment by syb1234** [comment]
Sorry, I was confused by the setting "Full Multiple Companies Support".  This is the setting that makes the data appearing or not.

I did create assets and assigned them to each company but this  is another error now.

**Comment by snipe** [comment]
https://snipe-it-manual.readme.io/docs/full-company-support

> I did create assets and assigned them to each company but this is another error now.

? I don't understand what this means. What another error?

**Comment by syb1234** [comment]
Ok, the full company support is what seems to be causing the issue for me. Not the upgrade from 2.1.2.

**Comment by snipe** [comment]
Yes, that's what I said. Company scoping means regular users who are not assigned to that company cannot see that company's assets. Only superadmins can see across companies.

**Comment by syb1234** [comment]
Yes, I do have assets assigned to the company that the user is in and the user can see all these assets in the page localhost/hardware.

The only issue is that these assets don't show in the field "assets" of the page localhost//hardware/bulkcheckout.

**Comment by syb1234** [comment]
I'm not a coder as you can tell.  I think the error is in the JAVA Script: snipeit/public/build/assets/js/all-5ba6978224.js

The line that returns the "No results found" I think is line 22575.

**Comment by snipe** [comment]
The error is not in the javascript

**Comment by testology** [comment]
Hi, we're also having this issue when using the full company support feature.

To clarify: with assets listed in both of the companies that we have set up, the bulk checkout feature doesn't list any assets at all for a restricted user, including any in the company that the user is assigned to. This means only super admins are able to use the bulk checkout feature. 
We would like users to be able to bulk checkout any assets that are assigned to the company they are in.

Thanks,
