### ISSUE TITLE
Feature requests: AD Authenticated user accounts for login to snipe-it

### ISSUE THREAD

**Issue by mattgann** [snipe/snipe-it#2450]
AD Authenticated user accounts for login to snipe-it

also 

recursively search Child OU for new user additions

also

Scheduled ldap user imports from AD

3.2
Windows IIS

**Comment by snipe** [comment]
> AD Authenticated user accounts for login to snipe-it

This already exists.

> recursively search Child OU for new user additions

It will search whatever baseDN you give it.

> Scheduled ldap user imports from AD

There is an existing ticket for this. https://github.com/snipe/snipe-it/issues/1348
