### ISSUE TITLE
exception 'ErrorException' with message 'ldap_control_paged_result_response(): No server controls in result' in /domains/assets.domain.local/app/Models/Ldap.php:261

### ISSUE THREAD

**Issue by setkeh** [snipe/snipe-it#2455]
#### Expected Behavior (or desired behavior if a feature request)
Contacts to import from LDAP

-----

#### Actual Behavior

When Clicking the import from LDAP button it redirects to "Whoops, Looks Like Somthing went Wrong" Page with th Following Error in the Laravel Log.

`
[2016-08-18 01:21:55] production.ERROR: exception 'ErrorException' with message 'ldap_control_paged_result_response(): No server controls in result' in /domains/assets.domain.local/app/Models/Ldap.php:261
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'ldap_control_pa...', '/domains/assets...', 261, Array)
#1 /domains/assets.domain.local/app/Models/Ldap.php(261): ldap_control_paged_result_response(Resource id #11, Resource id #12, '')
#2 /domains/assets.domain.local/app/Http/Controllers/UsersController.php(1191): App\Models\Ldap::findLdapUsers()
#3 [internal function]: App\Http\Controllers\UsersController->postLDAP(Object(Illuminate\Http\Request))
#4 /domains/assets.domain.local/bootstrap/cache/compiled.php(9419): call_user_func_array(Array, Array)
#5 /domains/assets.domain.local/bootstrap/cache/compiled.php(9481): Illuminate\Routing\Controller->callAction('postLDAP', Array)
#6 /domains/assets.domain.local/bootstrap/cache/compiled.php(9461): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\UsersController), Object(Illuminate\Routing\Route), 'postLDAP')
#7 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#8 /domains/assets.domain.local/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /domains/assets.domain.local/bootstrap/cache/compiled.php(9938): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 /domains/assets.domain.local/bootstrap/cache/compiled.php(9462): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 /domains/assets.domain.local/bootstrap/cache/compiled.php(9449): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\UsersController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'postLDAP')
#13 /domains/assets.domain.local/bootstrap/cache/compiled.php(8517): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'postLDAP')
#14 /domains/assets.domain.local/bootstrap/cache/compiled.php(8504): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#15 /domains/assets.domain.local/bootstrap/cache/compiled.php(8218): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /domains/assets.domain.local/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /domains/assets.domain.local/app/Http/Middleware/CheckPermissions.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: App\Http\Middleware\CheckPermissions->handle(Object(Illuminate\Http\Request), Object(Closure), 'users.view')
#20 /domains/assets.domain.local/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#21 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /domains/assets.domain.local/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 /domains/assets.domain.local/app/Http/Middleware/Authenticate.php(45): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /domains/assets.domain.local/bootstrap/cache/compiled.php(9953): call_user_func_array(Array, Array)
#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /domains/assets.domain.local/vendor/laravel/framework/src/Il
`

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - 3.2.0
- What OS and web server you're running Snipe-IT on - Centos 7 Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual
- If you're getting an error in your browser, include that error "Whoops, looks like something went wrong."
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Domain.com/admin/users/ldap and Interacting with the Import from LDAP button
- If a stacktrace is provided in the error, include that too. - See Above.
- Any errors that appear in your browser's error console. - None
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). - Unable to Edit LDAP setting in the Demo App (Not sure if that's by Design or not)
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. - I have Had a Few issues in the update process from v2.1.0-47-g39f40a3 to  	v3.2.0-53-gfff2bce Primarily due to Centos 7 not having the required PHP version in the Repo's and the Remi Repo's layout is somewhat non standard so im fully aware this may be just im missing something that needs to be linked to somewhere else i just cannot find what that may be due to limited Laravel / php Experience.
- Indicate whether or not you've manually edited any data directly in the database
i have Manually re Enable my user access to the admin panel with the following Query,
```UPDATE users
SET permissions='{"admin":1,"user":1,"superuser":1}'
WHERE id=1;```

**Comment by snipe** [comment]
We started this convo in Gitter, but I wanted to follow up. Does your LDAP/AD server allow paged results? (Paging was introduced in LDAP v3, I believe)

**Comment by setkeh** [comment]
Hi Snipe, Thanks for Getting back to me.

After some more investigation into the LDAP Version/Capability's i Discovered that the AD server was not sending information without TLS and in the Current Snipe_it Version we are Using (2.1.0) there is not a "Require TLS Setting" but Checking the "This should be checked only if you are running STARTTLS on your LDAP server." option in the LDAP Configuration Page in Snipe_it v3.2.0-53-gfff2bce Appears to have Resolved the Issue i can see the users Syncing From the AD server with no errors now.

Perhaps the Error page and Exception Could provide some more detail in this instance as it has no mention of TLS being a possible issue or any indication as to what could be the issue aside from "'ldap_control_paged_result_response(): No server controls in result".

Though i hope this does help you and anyone else that runs into this issue :)
Thanks for all your help.

**Comment by snipe** [comment]
Well, the hard part is that we've only ever even seen the "ldap_control_paged_result_response(): No server controls in result" error twice, so we weren't even sure what to put there. :-/ We can try to add a more clear error message moving forward, now that we might have some idea of what's causing it. Good old PHP and their super useful errors.

**Comment by snipe** [comment]
Regardless, I'm glad you got it sorted, and I hope you like v3. Lots and lots of improvements. You can read about them here: http://snipe-it.readme.io/blog/v3-is-coming

**Comment by snipe** [comment]
Also updated the docs: https://snipe-it.readme.io/docs/common-issues#error-when-ldap-syncing-ldap_control_paged_result_

**Comment by setkeh** [comment]
Thanks for the Info Mate were Deploying into Prod on Monday i will keep you posted :D

**Comment by snipe** [comment]
Good luck - let us know if you run into issues. We're always here to help.
