### ISSUE TITLE
"No matching records found" when trying to sort asset listings by Location

### ISSUE THREAD

**Issue by Tsuroerusu** [snipe/snipe-it#2456]
#### Expected Behavior (or desired behavior if a feature request)

Asset listings to be sorted by their location when clicking on the location column header.

---
#### Actual Behavior

Displays "No matching records found" despite the database containing hundreds of assets, and they display fine when clicking ANY other column header.
![1](https://cloud.githubusercontent.com/assets/9139161/17767365/fd7491a2-652f-11e6-80bc-dfc21ad65490.jpg)
![2](https://cloud.githubusercontent.com/assets/9139161/17767366/fd7a0db2-652f-11e6-9bfd-419d99472cf4.jpg)

---
#### Please confirm you have done the following before posting your bug report:
- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Snipe-IT version: 3.2.0
- OS and web server: FreeBSD 9.3 + Apache 2.4.23
- Installation method: Manual installation
- Error: No matching records found
- Problem area: Assets --> List All / Deployed / Ready to Deploy etc. etc., trying to sort by the Location tab.
- Not reproducible with the demo.
- No manual editing at all.

Log files:
[logs.zip](https://github.com/snipe/snipe-it/files/424495/logs.zip)

**Comment by snipe** [comment]
Please provide the error logs, as requested in the Getting Help page and the ticket template.

**Comment by Tsuroerusu** [comment]
@snipe Logs added, sorry about that. I forgot to attach them when creating the post, my mistake.

**Comment by Tsuroerusu** [comment]
@snipe I have been looking at the debug-bar, and I took the SQL query being run when sorting by the Location-column, and tried running it via phpMyAdmin, and I noticed that it returns no results either. So it would appear something is wrong either with the following command or in the database:

select `assets`.* from `assets` inner join `locations` on `locations`.`id` = `assets`.`rtd_location_id` where `physical` = '1' and `assets`.`deleted_at` is null order by `locations`.`name` desc limit 100 offset 0

As I mentioned in my original post, I have not made any manual edits to the database. Also, I guess I ought to have mentioned that this Snipe-IT 3.2.0 instance was upgraded from 1.2.10.

**Comment by delize** [comment]
I would like to add that I experience a similar issue, but, not when attempting to Sort by a specific column.

When it appears for me, I am only selecting "Assets" > "List All". It immediately displays "No matching records found". Clicking the refresh button near the top right of the panel, allows the assets to load back in. At no point, do I attempt to sort by a column.

**Comment by dmeltzer** [comment]
Hmm.. from Asset::scopeOrderLocation:

```
  * TODO: Extend this method out for checked out assets as well. Right now it
  * only checks the location name related to rtd_location_id
```

Bug's been documented for months!
