### ISSUE TITLE
Editing Custom Fields

### ISSUE THREAD

**Issue by philknab** [snipe/snipe-it#2457]
it would be nice if i am able to edit the name of custom fields after i created them.
i would like to change the name from "key" to "product key".
maybe this would be possible for future versions

-Phil

**Comment by grandmamoses** [comment]
Hi

Being able to change the available values of custom fields e.g in a list would be very useful. Also, I ran out of space with varchar(255) when capturing my list.

Thanks!

**Comment by avary69** [comment]
Not only the name should be possible to edit, but also the format, if you choose custom format. You need to be able to edit your regular expression

**Comment by Oreios** [comment]
I would also like this feature. Consider this an upvote.

**Comment by snipe** [comment]
Duplicate of #1684
