### ISSUE TITLE
Accessores Not Loading List

### ISSUE THREAD

**Issue by HirtLocker128** [snipe/snipe-it#2459]
#### Expected Behavior (or desired behavior if a feature request)

When "Accessories" tab is clicked on, list of all accessories is displayed on the table.

---
#### Actual Behavior

No accessories are displayed, instead a message that says "No matching records found". However, if certain accessories are searched for, they show up.

---
#### Please confirm you have done the following before posting your bug report:
- [ x ] I have enabled debug mode
- [ x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running: v2.1.0-24
- What OS and web server you're running Snipe-IT on: Mac OSX
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error: no errors
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Accessories page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database: Have not

**Comment by snipe** [comment]
> Include any additional information you can find in app/storage/logs and your webserver's logs
