### ISSUE TITLE
Asset Bulk Import Feature - Not importing Warranty Date

### ISSUE THREAD

**Issue by niallmooney** [snipe/snipe-it#2462]
#### Expected Behavior (or desired behavior if a feature request)

Warranty Period imports okay using Bulk Import

-----

#### Actual Behavior

Using example Asset CSV File from User's Manual. The Bulk Import isn't importing the warranty period.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.3.0
- What OS and web server you're running Snipe-IT on: CentOS 6.8/Apache 2.2.15/PHP 5.6.24
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual Installation
- If you're getting an error in your browser, include that error: N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Accept Asset page for unauthenticated users.
- If a stacktrace is provided in the error, include that too: N/A
- Any errors that appear in your browser's error console: N/A
- Confirm whether the error is reproduceable on the demo: Unsure
- Include any additional information you can find in app/storage/logs and your webserver's logs: N/A
- Include what you've done so far in the installation, and if you got any error messages along the way: Imported test assets and testing functionality of confirming assets.
- Indicate whether or not you've manually edited any data directly in the database: No

**Comment by dmeltzer** [comment]
The Importer is looking for `warranty months`, not `warranty` like the sample csv shows.  I'm not sure which one is better, and which file we should fix... @snipe?

**Comment by snipe** [comment]
Sample CSV is updated.
