### ISSUE TITLE
Multi Company Bulk Edit Issue / Permissions

### ISSUE THREAD

**Issue by veen1981** [snipe/snipe-it#2463]
#### Expected Behavior (or desired behavior if a feature request)

Admins should be able to use the bulk edit feature by selecting the check-boxes > Edit > Go.

---
#### Actual Behavior

We have different departments set-up as companies. The users in these companies are put in a rights group with all permissions except super-user rights so they can manage whatever assets are assigned to that company. They are able to individually edit assets using the yellow edit link next to the asset, however when selecting the checkbox and clicking Edit > Go, they get Error: Insufficient Permissions.

![capture3](https://cloud.githubusercontent.com/assets/14188055/17808746/c8795ec8-65df-11e6-9d91-d29f51b8bdf0.PNG)

---
#### Please confirm you have done the following before posting your bug report:
- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running **v3.3.0-3-g7ef4f23**
- What OS and web server you're running Snipe-IT on **Centos7**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Manual**
- If you're getting an error in your browser, include that error **No error other than the permissions issue**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **https://our.site.edu/hardware**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). **I attempted to replicate this on the demo but was unable to edit a test users rights** 
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. **Nothing in logs**
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by tonictuna** [comment]
+1
Encountered a similar issue when Admins of a multi-company group cannot Import assets. Our current workaround is having a tech super-user do their bulk imports, but this not efficient.
