### ISSUE TITLE
Customize Asset Labels

### ISSUE THREAD

**Issue by shanakadissanayake** [snipe/snipe-it#2466]
Hi,

Is it possible to customize Asset Labels? I want to display some additional information on Asset label such as location and assigned user. Is it possible?

Thank you

**Comment by snipe** [comment]
We're not averse to the idea, but it starts to get difficult accommodating additional (arbitrary) text while keeping the label sizes consistent.

**Comment by shanakadissanayake** [comment]
I found a way to create any type of Barcode using Excel and word. Easy step by step guide can be found here  [http://www.clearlyinventory.com/how-to-print-barcodes-with-excel-and-word](url)

**Comment by shanakadissanayake** [comment]
My result :smile:
![img_20160828_122247](https://cloud.githubusercontent.com/assets/21030813/18032173/8261fe9e-6d1a-11e6-8523-1c39fb8a1cac.jpg)
