### ISSUE TITLE
XAMPP Installation with Snipe-IT v3.3.0

### ISSUE THREAD

**Issue by RobbyTown** [snipe/snipe-it#2467]
I try for a few weeks to install snipe-it with no success.

Made a clean Server 2012 R2 server

I follow this ticket/steps: https://github.com/snipe/snipe-it/issues/2421

i install composer install command on snipe-it folder 
next is made
C:\xampp\htdocs\snipe-it>php artisan key:generate 

was success generate

I get stuck on composer.

If i enter composer command i still get message file is not found.

What im doing wrong?

![2016-08-21 12_59_23-igo-snipe-it - remote desktop connection](https://cloud.githubusercontent.com/assets/8578299/17836804/1c54d19c-679f-11e6-96fd-5e78543fc022.png)

If i go to the url i dont get the Snipe-IT Pre-Flight

Still get Whoops, looks like something went wrong. on the start page

**Comment by dmeltzer** [comment]
1) I'd suggest reading the messages that appear after running a command, they usually give you a good idea of what is going on.

"Could not open input file: composer.phar"
"Unknown database 'snipe-it'"

If you fix these, things will be much more likely to work.

**Comment by RobbyTown** [comment]
The problem is why i get the error "Could not open input file: composer.phar"

I run `composer install` with success.

Afther that step i could create artisan key

Only if i run the command 
`php composer.phar install --no-dev --prefer-source`

i get the error. Don't know why.

"Unknown database 'snipe-it'" also strange because 100% sure i created.

If i look composer.phar on the pc 0 results, if run composer install it's with succes and composer is up to date.

**Comment by dmeltzer** [comment]
it sounds like composer is installed globally for you, and not locally (in the snipe directory.)  composer install does the same thing as php composer.phar install, depending on where you installed composer.

**Comment by RobbyTown** [comment]
Thanks for the tip. Files are standing in the app data folder from the user.
I copy them to the vendor folder form snipe-it

Also i had need to run these commands
```
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
```

Finaly i get the install page
![2016-08-21 16_27_49-igo-snipe-it - remote desktop connection](https://cloud.githubusercontent.com/assets/8578299/17837764/41b6ce3c-67bc-11e6-80f1-03d537ccf66e.png)

**Comment by hiboucochon** [comment]
I followed the instruction and everything went smooth until the last step, I got "Access forbidden!" page, 
![image](https://cloud.githubusercontent.com/assets/21266193/18014086/37565d00-6b76-11e6-8eca-463a9d27d76a.png)

Could someone help me please? I'm new to this.
