### ISSUE TITLE
Not a bug: How to remove custom fields from model? 

### ISSUE THREAD

**Issue by Aaranaw** [snipe/snipe-it#2468]
Somehow I accidentally added an extra field to a model, I have not used used this field on any assets that use the model, can I remove the fieldset ?

**Comment by snipe** [comment]
To clarify, are you trying to delete a custom field from a fieldset, or a fieldset from a model?

**Comment by Aaranaw** [comment]
Hi that would be a field from a fieldset .

**Comment by snipe** [comment]
This was added for 3.5
