### ISSUE TITLE
QRcode in hardware view

### ISSUE THREAD

**Issue by rudashi** [snipe/snipe-it#2469]
Hello,
I find a little bug in hardware section. The link to QR code generates wrong to me (v3.3.0-3-g7ef4f23).
In file view.blade.php is TYPO in line 278
` <img src="{{ config('get.url') }}/hardware/{{ $asset->id }}/qr_code" class="img-thumbnail pull-right" style="height: 100px; width: 100px; margin-right: 10px;">`

fix:
` <img src="{{ Config::get('app.url') }}/hardware/{{ $asset->id }}/qr_code" class="img-thumbnail pull-right" style="height: 100px; width: 100px; margin-right: 10px;">`

**Comment by snipe** [comment]
I have a fix in for this, just has to be merged.
