### ISSUE TITLE
It redirects to localhost/setup at the very start of the installation 

### ISSUE THREAD

**Issue by charveasna** [snipe/snipe-it#2470]
#### Expected Behavior (or desired behavior if a feature request)

It should show up the setup page whereas it shows a blank screen while the url is pointed to setup.

-----

#### Actual Behavior

Page not found or blank page 

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
   => Lastest release, i try 3.0 and 3.3 from github repository
- What OS and web server you're running Snipe-IT on
   => Both MaxOS El Capitan and Fedora 23 and 24
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
   => Manual installation
- If you're getting an error in your browser, include that error
   => On safari and firefox, it shows blank screen while Chrome throws a page not found error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
   => Initial stage of setup after necessary configuration including server and .env.
- If a stacktrace is provided in the error, include that too.
   => None
- Any errors that appear in your browser's error console.
   => Nothing shows up except the page not found error
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
   => I believe so as I've tried a number of time, just follow the instruction given here - https://snipe-it.readme.io/docs/getting-started 
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
   => No log file is generated
- Include what you've done so far in the installation, and if you got any error messages along the way.
   => I have configured the necessary server configuration including virtual host and php to enable the required module and follow exactly the instruction given on the Snipeitapp installation page.
- Indicate whether or not you've manually edited any data directly in the database
   => No as it is at the very initial stage of setup

**Comment by prash42135** [comment]
Could you find out and tell if there is a .htaccess file in your snipe-it folder.
This file should be inside the snipe-it/public folder, and not in the snipe-it folder for the setup to work.

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/common-issues#browser-redirects-to-login-but-page-is-blank-with-
