### ISSUE TITLE
Feature Request: View of last added Assets in Asset-Create

### ISSUE THREAD

**Issue by philknab** [snipe/snipe-it#2473]
#### Expected Behavior (or desired behavior if a feature request)

It would be really nice and helpful if there is a small view or lets say a field on the side, which shows the last ~10 assets you've created. In my company we use unique pc names like (abcd3506). These names are ongoing so the next one would be (abcd3507) and so on. We do not always remember which name was the last one so it would be really nice if there is a field which shows the last ~10 created assets.
This would help us in so many things and safe a lot of time.
- Best Wishes from Austria!

**Comment by snipe** [comment]
Wouldn't it just be easier to use the auto-incrementing asset tag setting?

**Comment by philknab** [comment]
hi @snipe , sorry for the late response but i was on vacation.

well we use unique numbers for our laptops. those numbers are the asset tags. (31023)
but we also use unique names and those names should always be the old name, plus 1. (abcd1234)

those names are not visible when i create an asset. we often don't know what the last name was so it would be nice if there is a field which shows us the names of the last created assets.
