### ISSUE TITLE
Deployment status not updating

### ISSUE THREAD

**Issue by henryp007** [snipe/snipe-it#2474]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

Select Assets, go to Edit, Change status to "Device Deployed" (custom status label) then click save. Asset should have status "Device Deployed"

#### Actual Behavior
Device status just says "Deployed" and it's status hasn't changed. - I can't even set the other assets back to "Deployed" instead of my custom status of "Device Deployed"

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running;
System Information

Snipe-IT version	v3.3.0-3-g7ef4f23
PHP Version	5.6.20
Laravel Version	5.2.43

- What OS and web server you're running Snipe-IT on:  Server 2012 R2 Standard - IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual
- If you're getting an error in your browser, include that error: No Error message
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error any asset page.
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![image](https://cloud.githubusercontent.com/assets/20864879/17883916/43a9f906-690d-11e6-8e5c-0970bfc1fbd7.png)

![image](https://cloud.githubusercontent.com/assets/20864879/17883928/592fc224-690d-11e6-80f8-8df9ec779aa6.png)

**Comment by henryp007** [comment]
I've just noticed if you edit the individual asset its status is set as "Device Deployed" Which is what I wanted it to be set to, however, this doesn't update on the Dashboard or the list all assets page.
![image](https://cloud.githubusercontent.com/assets/20864879/17884082/297f7a00-690e-11e6-8a35-d04e77d87150.png)

**Comment by dmeltzer** [comment]
Hi,

As it stands, `deployed` is a meta-status that gets applied if the device is assigned to a user.  There is currently no way to make a status label of the "deployed" type.
