### ISSUE TITLE
Can't upload logo

### ISSUE THREAD

**Issue by ilfrigorifero** [snipe/snipe-it#2477]
#### Expected Behavior (or desired behavior if a feature request)

Logo is uploaded, settings are saved.

-----

#### Actual Behavior

Whoops-page appears.

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: 3.3.0-beta-19-g7a0843e
- What OS and web server you're running Snipe-IT on: CentOS 7 / Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Install.sh
- If you're getting an error in your browser, include that error: Whoops...
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Administrative settings > Select logo > Save
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. Attached
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). : This field cannot be edited on this installation
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
Created 3 users manually, since I got a "Whoops" in the previous version (then migrated to Linux)

[error_log.txt](https://github.com/snipe/snipe-it/files/432649/error_log.txt)

**Comment by snipe** [comment]
Have you run migrations after upgrading?

**Comment by ilfrigorifero** [comment]
It seems I did not :( I'm sorry. Doing the artisan migrate fixed the issue.
Thanks a lot!
