### ISSUE TITLE
PHP Composer error upgrading to 3.3.0

### ISSUE THREAD

**Issue by ilfrigorifero** [snipe/snipe-it#2481]
#### Expected Behavior (or desired behavior if a feature request)

Composer works as intended ;) 

-----

#### Actual Behavior

Composer throws error 255:
```
php composer.phar install --no-dev --prefer-source
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating autoload files
> php artisan clear-compiled
PHP Notice:  Undefined variable: factory in /var/www/html/snipeit/config/factories/ModelFactory.php on line 14
PHP Fatal error:  Call to a member function defineAs() on null in /var/www/html/snipeit/config/factories/ModelFactory.php on line 14
Script php artisan clear-compiled handling the post-install-cmd event returned with error code 255
```
-----

#### Please confirm you have done the following before posting your bug report:

N/A
-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
```
Snipe-IT version	3.3.0-beta-19-g7a0843e
PHP Version	5.6.24
Laravel Version	5.2.43
```
- What OS and web server you're running Snipe-IT on CentOS 7/Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh (initial install), then manual c&p from tarball.

**Comment by snipe** [comment]
You're running it as root, and it's telling you not to (as we also tell you not to).

**Comment by ilfrigorifero** [comment]
Yes, I know. I've tried running it as me (added me to apache group to be able to read/partially write the files) but no dice. Also didn't find information on how to run/as whom (maybe didn't check closely enough?). 
I've used Snipe on Windows previously, so I didn't have to bother with composer too much previously

**Comment by ilfrigorifero** [comment]
Hi again,

So uhm I've made myself member of the apache group, made sure that everything's writeable by apache and then could get composer to do my bidding.
Does it make a difference if apache group may write the whole directory? Or are there parts I should revoke the write permission again to be safe? From my understanding, as long as "others" aren't granted rights and nobody's tampering with the Snipe IT page, it's safe enough, right? 
Thanks for pointing me in the right direction and all :D

**Comment by snipe** [comment]
You would still have had to use composer if you ran snipe-it on windows. It's never not needed composer. 

Its generally better to have all of the files owned by whatever user apache runs as (versus screwing around with groups), and then just make sure the storage directory is writable by that apache user (as well as any subdirectories.)
