### ISSUE TITLE
PDOException in Connector.php line 55: could not find driver

### ISSUE THREAD

**Issue by glennbevan** [snipe/snipe-it#2482]
When I open my site http://localhost:8094 it presents me with the following

PDOException in Connector.php line 55: 
could not find driver

1. in Connector.php line 55
2.at PDO->__construct('mysql:host=localhost;dbname=snipe', 'admin', 'Password1', array('0', '2', '0', false, false)) in Connector.php line 55
3.at Connector->createConnection('mysql:host=localhost;dbname=snipe', array('driver' => 'mysql', 'host' => 'localhost', 'database' => 'snipe', 'username' => 'admin', 'password' => 'Password1', 'charset' => 'utf8', 'collation' => 'utf8_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => ''C:\Progra~2\MySQL\MySQLS~1.5\bin'', 'dump_command_timeout' => '300', 'dump_using_single_transaction' => true, 'name' => 'mysql'), array('0', '2', '0', false, false)) in MySqlConnector.php line 24
4.at MySqlConnector->connect(array('driver' => 'mysql', 'host' => 'localhost', 'database' => 'snipe', 'username' => 'admin', 'password' => 'Password1', 'charset' => 'utf8', 'collation' => 'utf8_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => ''C:\Progra~2\MySQL\MySQLS~1.5\bin'', 'dump_command_timeout' => '300', 'dump_using_single_transaction' => true, 'name' => 'mysql')) in compiled.php line 11844
5.at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
6.at call_user_func(object(Closure)) in Connection.php line 924
7.at Connection->getPdo() in Connection.php line 792
8.at Connection->reconnectIfMissingConnection() in Connection.php line 677
9.at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipe', 'users'), object(Closure)) in Connection.php line 349
10.at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipe', 'users')) in MySqlBuilder.php line 21
11.at MySqlBuilder->hasTable('users') in compiled.php line 6325
12.at Facade::__callStatic('hasTable', array('users')) in Setting.php line 61
13.at Schema::hasTable('users') in Setting.php line 61
14.at Setting::setupCompleted() in CheckForSetup.php line 17
15.at CheckForSetup->handle(object(Request), object(Closure))
16.at call_user_func_array(array(object(CheckForSetup), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
17.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
18.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
19.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in NosniffGuard.php line 17
20.at NosniffGuard->handle(object(Request), object(Closure))
21.at call_user_func_array(array(object(NosniffGuard), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
22.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
23.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
24.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in XssProtectHeader.php line 17
25.at XssProtectHeader->handle(object(Request), object(Closure))
26.at call_user_func_array(array(object(XssProtectHeader), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
27.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
28.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
29.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in FrameGuard.php line 17
30.at FrameGuard->handle(object(Request), object(Closure))
31.at call_user_func_array(array(object(FrameGuard), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
32.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
33.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
34.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 13473
35.at ShareErrorsFromSession->handle(object(Request), object(Closure))
36.at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
37.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
38.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
39.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 11963
40.at StartSession->handle(object(Request), object(Closure))
41.at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
42.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
43.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
44.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 145
45.at CheckForMaintenanceMode->handle(object(Request), object(Closure))
46.at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
47.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
48.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
49.at Pipeline->Illuminate\Routing\{closure}(object(Request))
50.at call_user_func(object(Closure), object(Request)) in compiled.php line 9948
51.at Pipeline->then(object(Closure)) in compiled.php line 2366
52.at Kernel->sendRequestThroughRouter(object(Request)) in compiled.php line 2350
53.at Kernel->handle(object(Request)) in index.php line 55

**Comment by glennbevan** [comment]
OK so I enabled the following extension:
 extension=php_pdo_mysql.dll

This has resolved the issue above but now it redirects to http://localhost:8094/setup and says the following:
HTTP Error 404.0 - Not Found

**Comment by snipe** [comment]
That may be because we removed your URL rewrites in trying to resolve some of your other issues. Can probably re-import those and remove the web.config. Sounds like you're awfully close tho.
