### ISSUE TITLE
CSS padding missing from asset view

### ISSUE THREAD

**Issue by nathank1989** [snipe/snipe-it#2488]
#### Expected Behavior (or desired behavior if a feature request)

With imagick set as Image Library in .env, upload image and save asset.

-----

#### Actual Behavior

Error: ImageMagick module not available with this PHP installation.

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running v3.3.0-3-g7ef4f23
- What OS and web server you're running Snipe-IT on CENTOS 6.8 x86_64 virtuozzo Linux 2.6.32-042stab108.1 #1 SMP Thu Apr 23 19:17:11 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual/Git-clone
- If you're getting an error in your browser, include that error: ImageMagick module not available...
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error Asset Edit
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. No
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). Not reproducable
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database No.

I installed imagick.so via this method:
[Install imagick on CentOS](http://www.liaohuqiu.net/posts/install-php-imagick-on-centos/)
But instead I used `echo "extension=imagick.so" >/opt/cpanel/ea-php56/root/etc/php.d/imagick.ini" `
My phpinfo lists:  `/opt/cpanel/ea-php56/root/etc/php.d/imagick.ini `
INI:
`extension=imagick.so`

```
# convert -version
Version: ImageMagick 6.7.2-7 2016-06-16 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2011 ImageMagick Studio LLC
Features: OpenMP
```

What, pray-tell, am I doing wrong?

**Comment by uberbrady** [comment]
huh. That sounds like it should work, I think?

First off - and it's a stupid question, but I have to ask it - can you reboot your webserver to make sure it 'took' the changes?

Next, let's make sure your PHP actually has the imageMagick library working - try: `php -v` and either pipe that through `grep` or just visually page through the results - looking for something where it says it has ImageMagick support enabled. If all you see is that reference to `imagick.ini` that may not be enough.

**Comment by nathank1989** [comment]
Whelp `php -v | grep imagick` yields nothing....

**Comment by snipe** [comment]
It looks like you already have GD support, so why not just switch your driver to gd in the env file?

**Comment by snipe** [comment]
(Also make sure you delete that info file when we're done here)

**Comment by nathank1989** [comment]
Of course I'll be sure to delete that file ;)
But I'd prefer to use IM because I have heard it is more flexible, but if I can't get it working then I will use gd, it works but doesn't seem to resize the images properly.

**Comment by snipe** [comment]
The library we use for image resizing should be pretty agnostic. If it's not resizing images correctly, that's probably something that would happen regardless of imagemagick vs gd, because it's probably a bug on our end.

**Comment by nathank1989** [comment]
Ahhh, I see.
For an Asset image, what are the intended dimensions for an uploaded image?

**Comment by snipe** [comment]
```
Image::make($image)->resize(500, 500, function ($constraint) {
```

So 500x500, it seems

**Comment by nathank1989** [comment]
Oh? Ok, well then I guess everything is working. :) :+1: 
I had uploaded an image and it fits outside the bounds of the asset page.
http://imgur.com/a/X24oF

But, it DID size down from 2560x1440 to 500x281. It just didn't quite fit on the page.

**Comment by snipe** [comment]
That sounds like a CSS issue, not a GD *or* ImageMagick issue
