### ISSUE TITLE
Error in importing Rules thru URL Rewrite

### ISSUE THREAD

**Issue by bagetsro** [snipe/snipe-it#2489]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)
login page shoud appear
-----

#### Actual Behavior

(what actually happens goes here)
http error 403.14 - Forbidden
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - 3.3.0
- What OS and web server you're running Snipe-IT on - windows 7 32bit, IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual
- If you're getting an error in your browser, include that error - HTTP Error 403.14 - Forbidden
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - login page
- If a stacktrace is provided in the error, include that too. -na
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). - no
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. - none
- Include what you've done so far in the installation, and if you got any error messages along the way. - there was an error with importing rules with url rewrite
- Indicate whether or not you've manually edited any data directly in the database - no

i have also added 127.0.0.1 in my host file

My web browser error
![image](https://cloud.githubusercontent.com/assets/20238789/17953656/b6a17114-6aa7-11e6-9d00-0bb8fac9f752.png)

My Rules import error
![image](https://cloud.githubusercontent.com/assets/20238789/17953681/ef5fd5ae-6aa7-11e6-8629-0f26934d71d5.png)

My .htaccessfile
![image](https://cloud.githubusercontent.com/assets/20238789/17953692/0818477a-6aa8-11e6-9a05-73f1cf3630ce.png)

My IIS Settings
![image](https://cloud.githubusercontent.com/assets/20238789/17953706/2fc9cc1c-6aa8-11e6-9458-554b86d7f4c6.png)

My Bindings
![image](https://cloud.githubusercontent.com/assets/20238789/17953714/3eddb02e-6aa8-11e6-9898-2cb913227c32.png)

**Comment by snipe** [comment]
Thanks for the helpful screenshots - do you have index.php set as a default index? I'm no IIS expert, but something like this? 

https://technet.microsoft.com/en-us/library/cc771439(v=ws.10).aspx

**Comment by bagetsro** [comment]
I will study and check the link you gave. Btw just to add, i havent imported any rules yet using the url rewrite as im having errors importing. Like what is show on screenshot above. I also haven't made it to the step "pre-flight and setup" as im having the http error.

**Comment by snipe** [comment]
Yeah, I don't know why those errors happen on IIS. Those are default Laravel rules, and it seems weird that Larval would provide rules that choke IIS up so hard. You can remove the rule that's not importing correctly though, it's not critical.

**Comment by bagetsro** [comment]
after adding index.php as a default document, the error changed. i have restarted the site as well.
![image](https://cloud.githubusercontent.com/assets/20238789/17958522/20753e84-6acd-11e6-9fca-39f92ee1c018.png)

![image](https://cloud.githubusercontent.com/assets/20238789/17958533/2de4fe92-6acd-11e6-99a3-83e54d2758c7.png)

**Comment by bagetsro** [comment]
i also have my APP_URL set to null if that is an issue.

![image](https://cloud.githubusercontent.com/assets/20238789/17958596/a514f986-6acd-11e6-8f6b-810ba32215fe.png)

**Comment by snipe** [comment]
Okay, that seems closer. 

<img width="1143" alt="screen shot 2016-08-24 at 11 10 33 pm" src="https://cloud.githubusercontent.com/assets/197404/17958615/038f02c8-6a50-11e6-9df9-4a1959cd3c3e.png">

You'll need to set your APP_URL and restart the web server tho.

**Comment by bagetsro** [comment]
well the error again changed. i have set my APP_URL to gdcassets.local, added it to the host file, and binding in ISS.
![image](https://cloud.githubusercontent.com/assets/20238789/17958832/2e6cd360-6acf-11e6-93ad-110901157eea.png)

this is my permission settings
![image](https://cloud.githubusercontent.com/assets/20238789/17958932/9ef38f5c-6acf-11e6-8ba4-0ee2ad1fae0e.png)

**Comment by snipe** [comment]
You need to set your storage directory (and all subdirectories) to be writeable by the server.

**Comment by bagetsro** [comment]
yes as shown above, i gave IUSR full control permission. i also gave the IIS_IURS user full control permision then this error came up.
![image](https://cloud.githubusercontent.com/assets/20238789/17959626/1ae64510-6ad4-11e6-99be-ae771e39a966.png)


upon checking my log files, this is the error.
![image](https://cloud.githubusercontent.com/assets/20238789/17959672/7221ddc6-6ad4-11e6-9a91-c6d2cb2b6f56.png)

**Comment by snipe** [comment]
Believe it or not, this is actually more progress. Now it's able to write to the log file, but it looks like the PHP-PDO extension might be missing. 

http://www.iis-aid.com/articles/how_to_guides/working_pdo_extensions_iis
http://www.garrypassarella.co.uk/2011/12/05/uncaught-exception-pdoexception-with-message-could-not-find-driver/

**Comment by bagetsro** [comment]
well, that solved it. thank you so much! this community always responds in time and always resolves issues. thanks again. would be better if there would be a step by step installation guide including the prerequisites for windows (php) to avoid this issues in the future. i would be happy to do it if you wont mind. ;)

![image](https://cloud.githubusercontent.com/assets/20238789/17961230/0d930af2-6add-11e6-8ba9-c50e1cf09cdf.png)

**Comment by snipe** [comment]
We would LOVE it if you could expand on our Windows documentation. I haven't worked on Windows in over 15 years, so a more verbose step-by step would be a great benefit to the community. If you go to the current IIS documentation, there should be an option to "Suggest Edits" in the top right. If you use that, you can write up your changes in markdown and we can approve them when you're done. Thanks!
