### ISSUE TITLE
Question for IIS users

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#2490]
With the new web.config in the v3 install, do you still need to import the htaccess rules via URL Rewrite? I'd love to clarify the docs for that if only one or the other is necessary, especially since the default Laravel htaccess has a rule that IIS can't seem to grok.

**Comment by sjlaird** [comment]
As a dumb Windows user, I just blindly followed the instructions to import the .htaccess file without knowing exactly what it did when I installed v2. I see now that the .htaccess is different for version 3 but I had not re-imported it.  I just tried in IIS 8.5 (Windows 2012 R2) but the file public/.htaccess file cannot actually be imported because of last rule fails. IIS 8.5 is saying it was all rules working or it won't import anything. 

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

Want me to test something specific?

**Comment by henryp007** [comment]
I can confirm that I also have this error - only some of the rules are imported, however it still apears to work for me.

**Comment by snipe** [comment]
I know that last rule doesn't import - that was the premise of my original question :) The question really is, with a web.config, do you even need to import htaccess rules. The web.config looks like it specifies the same rules as the htaccess does (minus the one that IIS can't seem to import), so if we can update the docs to skip importing the htaccess rules and instead use the web.config, I imagine that would save a lot of Windows users some headaches.

**Comment by snipe** [comment]
To clarify, I haven't worked on a windows IIS system in about 15 or so years, which is why I'm asking. I know our IIS documentation is a little less thorough than our Linux documentation, so I'm hoping to clean some of that up.

Laravel 4.2, which is the framework Snipe-IT v2 was built on, didn't provide a web.config, ONLY htaccess to import. My guess is that Laravel added the web.config to make it easier on IIS people (tho they don't *seem* to document that anywhere?), so I'm looking to update the documentation is importing the htaccess rules is redundant now because of the web.config they provided in later versions of the Laravel framework.

**Comment by sjlaird** [comment]
Sorry, I'm not much help but here is what I tried.

I looked through the config of my IIS server and I think I see that the web.config is active (it's pretty well hidden). Anyway, I then removed the URL rewrite rules that were imported with version 2 but the application was not working any more. My browser was giving 404 errors for everything on the side menu bar. First I tried restarting IIS but this didn't change anything.  I then re-imported the URL rewrite rules from version 2 and everything was working again.

I guess what you really need is someone to comment who has performed a direct v3 installation and not an upgrade.

**Comment by madd15** [comment]
@snipe I can confirm you do not need to import the .htaccess into URL Rewrite now that the web.config exists as it creates the URL Rewrite rules for you. URL Rewrite for IIS is still required.

**Comment by Poenskop** [comment]
@madd15 agreed. I have IIS on Server 2012 R2, PHP v5.6, MySQL Server v5.5, and Snipe-IT v3.3.0. I did not need to import the .htaccess into URL Rewrite. Although, I spent ages trying to figure out what I was doing wrong... hahaha

Funny that I only saw this post now...

**Comment by snipe** [comment]
@madd15 Is there anything that's needed in terms of configuration to make IIS grok the web.config? Or does that happen automagically? (As I mentioned, I haven't used IIS in over a decade.)

**Comment by sphere720** [comment]
I got the same as @sjlaird. So I took that part out and I got the green to import. No issues related to it so far.

**Comment by snipe** [comment]
@sphere720 you took what part out?

**Comment by sphere720** [comment]
I'll have to check in the morning when I can get to the machine.

**Comment by avary69** [comment]
When adding the website in IIS (as described in the Windows/IIS documentation) the web.config is automatically read, so given that "URL rewrite" was installed prior to that, the rewrite rules are automatically imported.
So, there is no need to manually import the rules from .htaccess.

**Comment by youssef-chtourou** [comment]
same problem  now
