### ISSUE TITLE
Feature Request: AD asset sync

### ISSUE THREAD

**Issue by henryp007** [snipe/snipe-it#2492]
Feature Request:

Would it be possible for Snipe-IT to grab the computers out of Active Directory instead of manually creating the assets for computers - this could save allot of time for larger companies.
I'm sure it would be quite a bit of work in terms of coding but it would be an awesome feature to have!

Thanks :+1:

**Comment by fltchr** [comment]
Possibly hand in hand with this, has there been any thought to a desktop agent that polls the machine for hardware and software inventory and reports it back to Snipe-IT?

**Comment by henryp007** [comment]
this would also be very useful for people not using a domain - think a lot of programming would be involved. it would be great to have this feature in the future.

**Comment by jghanlon** [comment]
Desktop agent would be cool for Mac, Win and Linux.  Maybe integrate with Puppet Facter or Spiceworks?

**Comment by snipe** [comment]
Desktop agents are covered by #1048. If we integrate with anything, I'd want it to be FOSS if possible, or at least not crazy proprietary. But all of that can be sorted when the REST API is done.

**Comment by Rungea96** [comment]
Is there now a way to import assets into Snipe it via the Active Directory?

**Comment by AW-IT** [comment]
Is there any update on this? Syncing SnipeIT with Active Directory for asset imports / removals, etc. would be incredible!
