### ISSUE TITLE
Non-hosting priority support querries

### ISSUE THREAD

**Issue by jcruzat** [snipe/snipe-it#2493]
After researching for asset management software, I stumbled to Snipe IT website and now our company is planning to purchase a non hosted pro support while I'm testing features via demo. 

Few questions;
Will there be a package installer for a non-hardcore IT?
How can I download a csv file of view license page? 
Is it possible to create individual users with limited access to own department assets and blocking access to licensing, pricing and other confidential information?

Thank you,
John

**Comment by snipe** [comment]
> Will there be a package installer for a non-hardcore IT?

The closest thing we have is a docker image:
https://snipe-it.readme.io/docs/docker

> How can I download a csv file of view license page?  
You should be able to export in the License view

> Is it possible to create individual users with limited access to own department assets and blocking access to licensing, pricing and other confidential information?

>  Not exactly. You can set up [Full Company Support](https://snipe-it-manual.readme.io/docs/full-company-support), using your departments as "companies" which will allow scoping on just their departments though, and you can limit other abilities through the user/group permissions. (I don't believe we give you the ability to hide price if the user in question has the ability to see the assets/license/etc, just license keys.)
