### ISSUE TITLE
Backups in Version v3.3.0

### ISSUE THREAD

**Issue by jayromems** [snipe/snipe-it#2494]
#### Expected Behavior (or desired behavior if a feature request)

produce a backup.zip like in the old version if Snipe-it

-----

#### Actual Behavior

Page says:
" Success: A new backup file was successfully created."
"Backup files are located in: /var/www/snipeit/storage/app/backups"

there is no backup in this location.

If I follow http://snipe-it.readthedocs.io/en/latest/manual/backups/#automated-backups

and run:

sudo /usr/bin/php /var/www/snipeit/artisan snipeit:backup

I get:

Starting backup...
Dumping database snipeit...
Backup failed because The dump process failed with exitcode 127 : Command not found : sh: 1: /usr/local/bin/mysqldump: not found
.
Backup completed!

still cannot find any backup anywhere.
-----

#### Please confirm you have done the following before posting your bug report:

- [yes] I have enabled debug mode
- [yes] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 
Version v3.3.0-3-g7ef4f23 
- What OS and web server you're running Snipe-IT on
Debian 8 and apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
download source.tar.gz and installed manually ($> sudo ./install.sh)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
(see above)

I'm getting the following in storage/logs/laravel.log:

[2016-08-25 09:07:49] production.ERROR: backups backups : error: Failed to backup  because: The dump process failed with exitcode 127 : Command not found : sh: 1: /usr/local/bin/mysqldump: not found

I find this odd because mysqldump IS in my path.

Thanks

**Comment by snipe** [comment]
Did you try specifically setting the DB_DUMP_PATH? 
https://snipe-it.readme.io/docs/configuration#required-database-settings

**Comment by jayromems** [comment]
Thanks for you help I just ended up symlinking /usr/bin/mysqldump to /usr/local/bin/.
fixed it.
I know, gross eh?

**Comment by snipe** [comment]
![passed-out](https://cloud.githubusercontent.com/assets/197404/17975551/ff5a0122-6a9e-11e6-9009-9f6ab5a029f6.gif)

Well, the DB_DUMP_PATH should fix your issue, should you choose to be less gross. :P

**Comment by jayromems** [comment]
This made my day :)
I would think 
http://snipe-it.readthedocs.io/en/latest/manual/backups/
needs to be updated though? I'd be glad to help you with your project, snipe-it is fantastic.

**Comment by jayromems** [comment]
I have it now set up so that cron will take a backup every night at 7:45 PM and copy it to our fileserver where everything get's backed up to tape.

**Comment by snipe** [comment]
I have no idea where you even found that documentation. It hasn't been active or accurate in years. :(

**Comment by jayromems** [comment]
Google found it for me. I couldn't find the document by browsing from the main documentation page 
https://snipe-it-manual.readme.io/docs/

**Comment by snipe** [comment]
Yeah, that's because that page is deprecated lol. All alerts/backups/etc use Laravel's scheduler now:
https://snipe-it.readme.io/docs/configuring-alerts

(It's badly named, since it covers backups too)

**Comment by snipe** [comment]
Thanks for the heads up - I've deleted the docs at readthedocs to prevent any additional confusion. I didn't realize those were even still available. :-/

**Comment by snipe** [comment]
![robot-panic](https://cloud.githubusercontent.com/assets/197404/17976654/388798fc-6aa3-11e6-9bdc-2707ff126eb0.gif)

**Comment by jayromems** [comment]
Many thanks! I'm grateful for your wonderful project! We're replacing our crusty old assetmanage software in my organization with Snipe-it. We're pretty much sold on it here.

**Comment by snipe** [comment]
![scrubs-elmo-dance](https://cloud.githubusercontent.com/assets/197404/17976843/1009d376-6aa4-11e6-8188-7dea738a78b7.gif)
