### ISSUE TITLE
User name format

### ISSUE THREAD

**Issue by fusion3k** [snipe/snipe-it#2495]
HI,

The options for username do not comply with my company's formatting. we user lastnamefirstinital (nameuser) as the format so when importing assets using csv with the username it creates new users rather then assigning to LDAP imported users.

Is there a way to modify or include this 4th option?

**Comment by snipe** [comment]
Are you specifying the username in the asset import CSV? If there is a value for that field, it shouldn't try to create a username at all.

**Comment by fusion3k** [comment]
no as there are over 1000 entries and the old system did not have this field. is that the only way to resolve or can it be added as a feature request for another format type for user names?

Thanks,

**Comment by snipe** [comment]
I think it would have to be a feature request. (Which I guess this is.)

**Comment by fusion3k** [comment]
ok, thank you for your quick replys :+1:

**Comment by TheVakman** [comment]
I would also love to see this feature.

If when I am importing assets, if I specify the usernames in the field and they match up to a user that I imported with LDAP, will it create another user or will it assign to the user.
