### ISSUE TITLE
Not able to update

### ISSUE THREAD

**Issue by brazda** [snipe/snipe-it#2497]
I seem not to be able to upgrade  to any release.

This are the steps I followed found from another post except with the  appropriate paths   

$ curl -LOk https://github.com/snipe/snipe-it/archive/v2.0.6.zip  
$ unzip v2.0.6.zip
 Update application folder (careful with the source directory trailing /!)
$ rsync -avut snipe-it-2.0.6/ /path/to/snipe-it
 Check directory permissions
 Complete this version's update steps. e.g.:
$ php composer.phar install
$ php composer.phar dump-autoload
$ php artisan migrate

-----

#### Actual Behavior

Nothing when when I pull up the page at the bottom of the page it still says version 2.1.1 running during the install it appears nothing happens. I have tried upgrading from every stable version up from  2.1.1 and all are doing the same thing.

Here is my output from the upgrade 

[root@snipeit snipeit]# rsync -avut ../snipe-it-3.3.0/ ../snipeit

chown -R apache:apache *

[root@snipeit snipeit]# php composer.phar install --no-dev --prefer-source
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating autoload files
[root@snipeit snipeit]# php composer.phar dump-autoload
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Generating autoload files
[root@snipeit snipeit]# php artisan migrate
**************************************
*     Application In Production!     *
**************************************

Do you really wish to run this command? yes
Nothing to migrate.

As  you can see I even tried as root

Not sure where to go from here.

-----

- Version of Snipe-IT you're running
2.1.1
- What OS and web server you're running Snipe-IT on
Centos 7

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh

- Indicate whether or not you've manually edited any data directly in the database
No

**Comment by snipe** [comment]
Did you follow the upgrading to v3 directions? https://snipe-it.readme.io/docs/upgrading

Also, why are you running composer as root when we (and it) tells you not to?

**Comment by brazda** [comment]
Well the root thing was frustration when I was out of ideas..

Anyhow I blew it away and started over per the document you sent. Now I am getting something new  

[nfvadmin@snipeit snipeit]$ php artisan migrate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes



  [Illuminate\Database\QueryException]
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'password_resets' already exists (SQL: create table `password_resets` (`email` varchar(255) not null, `
  token` varchar(255) not null, `created_at` timestamp not null) default character set utf8 collate utf8_unicode_ci engine = InnoDB)



  [PDOException]
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'password_resets' already exists

**Comment by brazda** [comment]
Fixed it 
I deleted the database and recreated it from my backup 
by adding 
drop database snipeit;
create database snipeit;
USE snipeit;
to the sql dump and importing it via mysql commandline.
All is well. Thanks for your help!
