### ISSUE TITLE
Alarm of Minimum Quantity Levels not displayed right

### ISSUE THREAD

**Issue by L3nny5** [snipe/snipe-it#2498]
#### Expected Behavior (or desired behavior if a feature request)

Only for components, accessories and consumables which have a min. quantity set, a warning will appear in snipe IT. 

![bildschirmfoto 2016-08-26 um 10 36 16](https://cloud.githubusercontent.com/assets/16922521/17999295/f6780114-6b78-11e6-8ced-a66f4756fcc0.png)

---
#### Actual Behavior

Components, accessories and consumables also appear as a warning if there is no min. quantity set. 

Could happen because if you set no min. quantity, Snipe IT automatically sets a 0 (zero) in the min quantity field. Therefore my setting 
![bildschirmfoto 2016-08-26 um 10 39 04](https://cloud.githubusercontent.com/assets/16922521/17999385/5bc9a810-6b79-11e6-99d5-c8b3db202d4b.png)
checks if the quantity is at least 1. 

Also when it sets the 0 to the min. qty field, I have to delete the entry if I update this entry. Otherwise it throws an error.

![bildschirmfoto 2016-08-26 um 10 49 02](https://cloud.githubusercontent.com/assets/16922521/17999730/cdb32c8e-6b7a-11e6-88d1-370f81b97bce.png)

![bildschirmfoto 2016-08-26 um 10 49 13](https://cloud.githubusercontent.com/assets/16922521/17999740/e1fa08ac-6b7a-11e6-9152-559594523a4c.png)

![bildschirmfoto 2016-08-26 um 10 49 22](https://cloud.githubusercontent.com/assets/16922521/17999742/e61e7594-6b7a-11e6-8b2a-a52af94e58df.png)

---
#### Please confirm you have done the following before posting your bug report:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running **v3.3.0-16-ge52a0f6**
- What OS and web server you're running Snipe-IT on **Ubuntu 14.04 Apache 2**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **manual**
- If you're getting an error in your browser, include that error **NO**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **every page where you can see the warning about min. quantity levels**
- If a stacktrace is provided in the error, include that too. -
- Any errors that appear in your browser's error console. -
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). **YES**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. **No logs**
- Include what you've done so far in the installation, and if you got any error messages along the way. **No error message**
- Indicate whether or not you've manually edited any data directly in the database **NO**

**Comment by aglasson** [comment]
To me the minimum quantity notifications shows all accessories having met the minimum threshold or not.
