### ISSUE TITLE
Profile edit image

### ISSUE THREAD

**Issue by rudashi** [snipe/snipe-it#2501]
Hello,
I found a bug in profile section. The image is not displaying correctly (v3.3.0-3-g7ef4f23).
In file profile.blade.php is TYPO in line 91
`<img src="/uploads/avatars/{{ $user->avatar }}" class="avatar img-circle">`
fix:
`<img src="{{ config('app.url') }}uploads/avatars/{{ $user->avatar }}" class="avatar img-circle">`

In Poland our firstname and lastname have a special chars (ż, ł, ó etc.).
If I upload the image, filename is changed and not match to profile.
example:
lastname: **Żuk** (in Profile)
filename: **Ĺ»uk.png**

**Comment by dmeltzer** [comment]
Just to clarify, are these two separate issues? Or does changing the /uploads/avatars to config(app.url) fix the encoding issues?

**Comment by rudashi** [comment]
Two diffrents issues, unfortunately.

**Comment by snipe** [comment]
Fixed with https://github.com/snipe/snipe-it/commit/04e9ca0942a94aaec0d92ef09de12e2caf213165. (I tagged the wrong ticket. :( )
