### ISSUE TITLE
HTTP500 after Upgrade from 2.2.1 to 3.3 on IIS

### ISSUE THREAD

**Issue by tzielinskiaptn** [snipe/snipe-it#2504]
I'm performing an upgrade from 2.2.1 to version 3.3 on IIS 7.0 under Windows 2012 R2.

I've followed the instructions for the upgrade, but when I get to the point where I need to do an Artisan Migrate, the command doesn't seem to be returning anything.

I am also seeing an error 255 at the end of the composer dependencies install.

Further, it looks like my SnipeIT site isn't currently accepting requests.

I'm sure I've missed a step, or something obvious, and I am hoping someone else that has done this upgrade can provide some Windows Server / IIS specific help.

**Comment by snipe** [comment]
Can you give us any info from your IIS server logs?

**Comment by tzielinskiaptn** [comment]
I just had a look at my logs, and the last entries were from prior to the upgrade, which is odd.

After I posted this issue, I was able to complete the composer and artisan migrates without error.

But when I go to access the site, I'm getting:

This site can’t provide a secure connection

snipeit.aptn.local sent an invalid response.
ERR_SSL_PROTOCOL_ERROR

Instead of the 500 error.

It's weird because I don't think we;ve ever run snipeit over https, it's just on our internal Lan.

**Comment by snipe** [comment]
What's your APP_URL set to in your .env?

**Comment by snipe** [comment]
Also check your rewrite rules and make sure it's not trying to automatically redirect to HTTPS

**Comment by tzielinskiaptn** [comment]
The app_url is set to 'http://snipeit.aptn.local'

There are two rewrite rules.

The first one redirects ^(.*)/$ to /{R:1} 
The second rewrites ^ to index.php

I don't see anything that redirects http to https

**Comment by snipe** [comment]
> I am also seeing an error 255 at the end of the composer dependencies install.

can you give me any more details on that?

**Comment by tzielinskiaptn** [comment]
I was able to re-run the composer dependency install without encountering the issue, and the artisan migrate ran as well.

It's definitely an odd issue. When I access the site with IE 11, there is no redirect to https, it just goes straight to a 500 error.

Both Chrome and Firefox try to redirect to https, and then I see an SSL error, because I'm not running ssl on the snipeit site at all.

Is there a method to create a fresh install and then either import, or connect my existing DB instance to the fresh site? I've obviously messed up somewhere along the line.

**Comment by tzielinskiaptn** [comment]
One more question. Should I have done an upgrade to 3.0 prior to 3.3 or would that have any effect on this process?

**Comment by tzielinskiaptn** [comment]
I think I've corrected my issue.

I went back and overwrote my snipeit directory with the contents of the 3.3 zip file, and I loosened my permissions a bit on the subfolders.

I re-ran the composer install and artisan migrates from a non-admin command prompt, and restarted my site, and I seem to be ready to roll.
