### ISSUE TITLE
Check-in from data is not shown dashboard , assets details or reports

### ISSUE THREAD

**Issue by abdullahalasham** [snipe/snipe-it#2506]
#### Expected Behavior (or desired behavior if a feature request)

when checking an assets the checkin data should be posted and be available in dashboard , assets details and reports.

---
#### Please confirm you have done the following before posting your bug report:
- [No ] I have enabled debug mode
- [YES ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running Version **v3.3.0-3-g7ef4f23**
- What OS and web server you're running Snipe-IT on : **Windows 7**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Manual**
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database **No**

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by abdullahalasham** [comment]
below is the answers for the reaming questions , Yet note that the same issue is present on the Demo  

- If you're getting an error in your browser, include that error  **NO Errors** 
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **Assets checkin page**
- If a stacktrace is provided in the error, include that too. **NA**
- Any errors that appear in your browser's error console. **NO**
- Confirm whether the error is reproduceable on the demo. **NO**
- Include any additional information you can find in app/storage/logs and your webserver's logs. **No Logs** 
- Include what you've done so far in the installation, and if you got any error messages along the way. **No error Found**
- Indicate whether or not you've manually edited any data directly in the database **NO**

**Comment by abdullahalasham** [comment]
Dear Snipe , please note that this is not a new feature for the system  , this was available  and working in version 2 (v2.0.6-73) but in v3 it does not work.

**Comment by snipe** [comment]
If it's not reproducible on the demo, then something is wrong with your installation.

**Comment by abdullahalasham** [comment]
Sorry , But indeed the same issue is appearing in the Demo version please help

**Comment by abdullahalasham** [comment]
any update on this ? as the same issue still appears in all released versions and even in demo

**Comment by abdullahalasham** [comment]
@snipe  any update on this ?
