### ISSUE TITLE
IIS HTTP 500 Internal Server Error on new installation (Windows 2008)

### ISSUE THREAD

**Issue by mikegfried** [snipe/snipe-it#2509]
#### Expected Behavior (or desired behavior if a feature request)

I completed the installation per the instructions, I check the folder permissions, have all the PHP extensions enabled, I ran composer successfully, but when I navigate to the site I get an HTTP 500 Internal Server error.  Based on the browser dev tools it looks like the server isn't responding to the initial GET request.  

-----

#### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/10986236/18039354/1a68734e-6d70-11e6-8ac2-8264963f79f4.png)
-----

#### Please confirm you have done the following before posting your bug report:

I have enabled debug mode and checked the common issues, I also went through the other threads here and tried to solve this myself for hours!!

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
3.3.0
- What OS and web server you're running Snipe-IT on
Windows 2008
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual
- If you're getting an error in your browser, include that error
HTTP 500
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Doesn't load a page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
No
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Without more detailed errors, we're not going to be able to help you. Please check your laravel log and web server logs, and tell us what you see there.

**Comment by mikegfried** [comment]
Hello,

Here is the laravel log (I don't see much in the IIS log but will post what i have):

[2016-08-28 02:33:10] production.ERROR: ErrorException: file_get_contents(C:\inetpub\wwwroot\snipe-it/.env): failed to open stream: No such file or directory in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\KeyGenerateCommand.php:57
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_get_conten...', 'C:\\inetpub\\wwwr...', 57, Array)
#1 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\KeyGenerateCommand.php(57): file_get_contents('C:\\inetpub\\wwwr...')
#2 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\KeyGenerateCommand.php(39): Illuminate\Foundation\Console\KeyGenerateCommand->setKeyInEnvironmentFile('base64:g6w4p9GD...')
#3 [internal function]: Illuminate\Foundation\Console\KeyGenerateCommand->fire()
#4 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1257): call_user_func_array(Array, Array)
#5 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#6 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\KeyGenerateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 C:\inetpub\wwwroot\snipe-it\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main}  
[2016-08-28 02:33:57] production.ERROR: ErrorException: file_get_contents(C:\inetpub\wwwroot\snipe-it/.env): failed to open stream: No such file or directory in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\KeyGenerateCommand.php:57
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_get_conten...', 'C:\\inetpub\\wwwr...', 57, Array)
#1 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\KeyGenerateCommand.php(57): file_get_contents('C:\\inetpub\\wwwr...')
#2 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\KeyGenerateCommand.php(39): Illuminate\Foundation\Console\KeyGenerateCommand->setKeyInEnvironmentFile('base64:WzGJfO/V...')
#3 [internal function]: Illuminate\Foundation\Console\KeyGenerateCommand->fire()
#4 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1257): call_user_func_array(Array, Array)
#5 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#6 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\KeyGenerateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 C:\inetpub\wwwroot\snipe-it\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main}  
[2016-08-28 02:35:22] production.ERROR: Symfony\Component\Console\Exception\RuntimeException: Too many arguments, expected arguments "command". in C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Input\ArgvInput.php:181
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Input\ArgvInput.php(88): Symfony\Component\Console\Input\ArgvInput->parseArgument('?')
#1 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Input\Input.php(62): Symfony\Component\Console\Input\ArgvInput->parse()
#2 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Command\Command.php(221): Symfony\Component\Console\Input\Input->bind(Object(Symfony\Component\Console\Input\InputDefinition))
#3 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\KeyGenerateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 C:\inetpub\wwwroot\snipe-it\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 {main}  
[2016-08-28 02:35:34] production.ERROR: Symfony\Component\Console\Exception\CommandNotFoundException: Command "key" is not defined.
Did you mean this?
    key:generate in C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php:515
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(183): Symfony\Component\Console\Application->find('key')
#1 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\inetpub\wwwroot\snipe-it\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 {main}  
[2016-08-28 02:35:43] production.ERROR: ErrorException: file_get_contents(C:\inetpub\wwwroot\snipe-it/.env): failed to open stream: No such file or directory in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\KeyGenerateCommand.php:57
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_get_conten...', 'C:\\inetpub\\wwwr...', 57, Array)
#1 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\KeyGenerateCommand.php(57): file_get_contents('C:\\inetpub\\wwwr...')
#2 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\KeyGenerateCommand.php(39): Illuminate\Foundation\Console\KeyGenerateCommand->setKeyInEnvironmentFile('base64:9aldf4yn...')
#3 [internal function]: Illuminate\Foundation\Console\KeyGenerateCommand->fire()
#4 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1257): call_user_func_array(Array, Array)
#5 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(169): Illuminate\Container\Container->call(Array)
#6 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Command\Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Console\Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\KeyGenerateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 C:\inetpub\wwwroot\snipe-it\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 {main}

**Comment by mikegfried** [comment]
Based on this I am looking at my .env file for the APP Key.  It is still listed as ChangeMe.  I run php artisan key:generate which runs without error (puts me back to the command line with no feedback) but it doesn't update the .env file

**Comment by xxtheatrainxx** [comment]
Mike,

I believe you have to copy the output of the command and paste it into you .env file.

**Comment by mikegfried** [comment]
It doesn't seem to produce an output.

**Comment by xxtheatrainxx** [comment]
Strange. I just updated, so I haven't run that command in a while it and it wasn't auto-populating when I did.

**Comment by xxtheatrainxx** [comment]
Could it be a permissions issue? What's your .env file name?

I'm sure someone with a bit more know how will comment soon, I'm just trying to help out in the meantime.

**Comment by mikegfried** [comment]
No name just .env

I also tried leaving the key and putting in a manual key but nothing. Also not sure that is the root issue. Would that prevent the server from responding at all?

**Comment by snipe** [comment]
It should definitely update the key, but it may not be able to based on the permissions error in the first stack trace.

`php artisan key:generate --show` should output a key you can paste into your .env file.

**Comment by xxtheatrainxx** [comment]
Change the file name to assets.env or something like that? 

file_get_contents(C:\inetpub\wwwroot\snipe-it/.env)
What's with the random forward slash?

**Comment by snipe** [comment]
No, the name should remain `.env`. The forward slash shouldn't matter.

**Comment by mikegfried** [comment]
I gave the IUSR user full permissions over the snipe-it directory, still no key see below:
![image](https://cloud.githubusercontent.com/assets/10986236/18071891/2984456c-6e27-11e6-85f4-8592152d102d.png)

**Comment by mikegfried** [comment]
Still no key generated. I tried manually entering a key as well and nothing. Any other guidance?

**Comment by mikegfried** [comment]
Ok Here is what I have in my Laravel logs:

[2016-09-02 21:36:10] production.ERROR: Symfony\Component\Console\Exception\CommandNotFoundException: Command "status" is not defined.
Did you mean this?
    migrate:status in C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php:515
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(183): Symfony\Component\Console\Application->find('status')
#1 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\inetpub\wwwroot\snipe-it\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 {main}  

And my PHP Server logs:

[02-Sep-2016 21:47:05 America/New_York] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "C:\inetpub\wwwroot\snipe-it\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\inetpub\wwwroot\snipe-it\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php:107
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\monolog\monolog\src\Monolog\Handler\AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array)
#1 C:\inetpub\wwwroot\snipe-it\vendor\monolog\monolog\src\Monolog\Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 C:\inetpub\wwwroot\snipe-it\vendor\monolog\monolog\src\Monolog\Logger.php(615): Monolog\Logger->addRecord(400, Object(UnexpectedValueException), Array)
#3 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Log\Writer.php(202): Monolog\Logger->error(Object(UnexpectedValueException), Array)
#4 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Log\Writer.php(113): Illuminate\Log\Writer->writeLog('error', Object(U in C:\inetpub\wwwroot\snipe-it\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php on line 107
[02-Sep-2016 21:47:05 America/New_York] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "C:\inetpub\wwwroot\snipe-it\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\inetpub\wwwroot\snipe-it\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php:107
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\monolog\monolog\src\Monolog\Handler\AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array)
#1 C:\inetpub\wwwroot\snipe-it\vendor\monolog\monolog\src\Monolog\Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 C:\inetpub\wwwroot\snipe-it\vendor\monolog\monolog\src\Monolog\Logger.php(615): Monolog\Logger->addRecord(400, Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#3 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Log\Writer.php(202): Monolog\Logger->error(Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#4 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Log\Writer.p in C:\inetpub\wwwroot\snipe-it\vendor\monolog\monolog\src\Monolog\Handler\StreamHandler.php on line 107

**Comment by mikegfried** [comment]
Ok solved.  Seems I had permission issues throughout the Snipe-IT directory.  I gave the IUSR user full access to the entire folder and it looks like we are up and running.
