### ISSUE TITLE
statuslabel fail

### ISSUE THREAD

**Issue by philknab** [snipe/snipe-it#2512]
#### Expected Behavior (or desired behavior if a feature request)

my deployed assets shout be shown as "in usage" (self created statuslabel)

-----

#### Actual Behavior

it shows "deployed" instead of "in usage" in the pie chart.
in the statuslabel view there is no label with the name "deployed" but it keeps showing.

-----

#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v3.3.0-3-g7ef4f23

**Comment by snipe** [comment]
Deployed is a meta label for ready to deploy assets that are assigned. 
https://snipe-it-manual.readme.io/docs

**Comment by philknab** [comment]
is it possible to change that to my self created label?
