### ISSUE TITLE
Notes on File Uploads for Users

### ISSUE THREAD

**Issue by AsimPervez93** [snipe/snipe-it#2513]
#### Expected Behavior (or desired behavior if a feature request)

Firstly, I apologize if this issue has been raised before.

Expected behavior is I type the file note in the text box, select file to upload, the file uploads with the note in the Note column.

---
#### Actual Behavior

When adding a document (PDF) to a user by navigating to User>File Uploads, there is a text field there that I don't know what does, I've tried typing the note in there and then selecting file, the file uploads and I refresh the page.  The file has uploaded successfully but there is nothing in the Note column.

---
#### Please confirm you have done the following before posting your bug report:
- [Y] I have enabled debug mode
- [Y] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running
  v3.3.0-3-g7ef4f23
- What OS and web server you're running Snipe-IT on
  Linux Shared Hosting
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  Manual Installation
- If you're getting an error in your browser, include that error
  No Errors
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
  /admin/users/[user here]/view - File Upload tab
- If a stacktrace is provided in the error, include that too.
  N/A
- Any errors that appear in your browser's error console.
  N/A
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
  No Error but my issues does replicate on the demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
  I have not manually edited any data in the database.

![image](https://cloud.githubusercontent.com/assets/17923501/18047759/5fcd47fa-6dd6-11e6-8979-7f93fbadd36d.png)

![image](https://cloud.githubusercontent.com/assets/17923501/18047788/7d4cc27e-6dd6-11e6-8e56-bb7857d78162.png)

**Comment by Louuu** [comment]
Has there been any update on this, as this is a feature which we use in our organisation on a daily basis.
