### ISSUE TITLE
Dashboard Asset pie chart bug

### ISSUE THREAD

**Issue by B3RN0UT** [snipe/snipe-it#2514]
#### Expected Behavior (or desired behavior if a feature request)

Asset pie chart should stay at the default size.

---
#### Actual Behavior

The pie chart for assets in the Dashboard gets bigger and bigger when clicking the three lines on the top left to enlarge/hide the menu.
After reloading the page the pie chart gets back to default size.

---
#### Please confirm you have done the following before posting your bug report:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running: Version v3.3.0-16-ge52a0f6
- What OS and web server you're running Snipe-IT on: Debian 8 - Apache/2.4.10 (Debian)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Dashboard - Asset pie chart
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).: Also appears in the demo

**Comment by dmeltzer** [comment]
I've been going with calling that an accessibility feature.  What other website allows you to quickly and easily scale graphics? :)

**Comment by dmeltzer** [comment]
@snipe, https://github.com/jtblin/angular-chart.js/issues/84#issuecomment-133928521 might be relevant...
