### ISSUE TITLE
Custom Field - List Box v.3.4.0 fail?

### ISSUE THREAD

**Issue by philknab** [snipe/snipe-it#2516]
#### Expected Behavior (or desired behavior if a feature request)

When i create an asset it should show my asset modell with custom fields. 

-----

#### Actual Behavior

After setting up a custom field list box for my asset modell it doesn't show the custom fields in asset-create. After i deleted my custom field list box it shows the custom fields in asset-create

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running -v.3.4.0 alpha
- What OS and web server you're running Snipe-IT on -Windows 7 / xampp
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)-manual
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - asset create 
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. LOG.error: ErrorException: undefined variable: asset in C:\xampp\htdocs\snipeit\storage\framework\views\957bb22ab9d4f68dff4136ab7edfe68ba9a0d8bb.php:10
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
> LOG.error: ErrorException: undefined variable: asset in C:\xampp\htdocs\snipeit\storage\framework\views\957bb22ab9d4f68dff4136ab7edfe68ba9a0d8bb.php:10

That looks like your laravel logs, not your browser console. Can you please tell me if there are any errors in your browser console?

**Comment by philknab** [comment]
how can i get to my browser console?

**Comment by philknab** [comment]
http://localhost/hardware/models/3/custom_fields?_token=3nnTfmfgM1IOgB3cfuFqJwiVJyjMUfudBAPsPt6L Failed to load resource: the server responded with a status of 500 (Internal Server Error)

this is the error in the console

**Comment by snipe** [comment]
Please paste me the first 20 lines of C:\xampp\htdocs\snipeit\storage\framework\views\957bb22ab9d4f68dff4136ab7edfe68ba9a0d8bb.php

**Comment by philknab** [comment]
<?php if($model->fieldset): ?>
  <?php foreach($model->fieldset->fields AS $field): ?>
    <div class="form-group<?php echo e($errors->has($field->db_column_name()) ? ' has-error' : ''); ?>">
      <label for="<?php echo e($field->db_column_name()); ?>" class="col-md-3 control-label"><?php echo e($field->name); ?> </label>
      <div class="col-md-7 col-sm-12<?php echo e(($field->pivot->required=='1') ? ' required' : ''); ?>">

          <?php if($field->element!='text'): ?>
              
              <?php if($field->element=='listbox'): ?>
                  <?php echo e(Form::select($field->db_column_name(), $field->formatFieldValuesAsArray(), Input::old($field->db_column_name(), $asset->{$field->db_column_name()}), ['class'=>'format select2 form-control'])); ?>


              <?php elseif($field->element=='checkbox'): ?>
                    
                  <?php foreach($field->formatFieldValuesAsArray() as $key => $value): ?>

                      <div>
                          <label>
                              <input type="checkbox" value="1" name="<?php echo e($field->db_column_name()); ?>[]" class="minimal" <?php echo e(Input::old($field->db_column_name()) != '' ? ' checked="checked"' : ''); ?>> key: <?php echo e($key); ?> value: <?php echo e($value); ?>

                          </label>
                      </div>
                  <?php endforeach; ?>

              <?php endif; ?>

**Comment by philknab** [comment]
<?php if($model->fieldset): ?>
  <?php foreach($model->fieldset->fields AS $field): ?>
    <div class="form-group<?php echo e($errors->has($field->db_column_name()) ? ' has-error' : ''); ?>">
      <label for="<?php echo e($field->db_column_name()); ?>" class="col-md-3 control-label"><?php echo e($field->name); ?> </label>
      <div class="col-md-7 col-sm-12<?php echo e(($field->pivot->required=='1') ? ' required' : ''); ?>">

          <?php if($field->element!='text'): ?>
              
              <?php if($field->element=='listbox'): ?>
                  <?php echo e(Form::select($field->db_column_name(), $field->formatFieldValuesAsArray(), Input::old($field->db_column_name(), $asset->{$field->db_column_name()}), ['class'=>'format select2 form-control'])); ?>


              <?php elseif($field->element=='checkbox'): ?>
                    
                  <?php foreach($field->formatFieldValuesAsArray() as $key => $value): ?>

                      <div>
                          <label>
                              <input type="checkbox" value="1" name="<?php echo e($field->db_column_name()); ?>[]" class="minimal" <?php echo e(Input::old($field->db_column_name()) != '' ? ' checked="checked"' : ''); ?>> key: <?php echo e($key); ?> value: <?php echo e($value); ?>

                          </label>
                      </div>
                  <?php endforeach; ?>

              <?php endif; ?>

**Comment by snipe** [comment]
First 20 lines please.

**Comment by snipe** [comment]
Ah, I see - you didn't comment them as code, so they were invisible.

**Comment by snipe** [comment]
What's actually on line 20 in that file?

**Comment by philknab** [comment]
nothing..

**Comment by philknab** [comment]
<input type="checkbox" value="1" name="<?php echo e($field->db_column_name()); ?>[]" class="minimal" <?php echo e(Input::old($field->db_column_name()) != '' ? ' checked="checked"' : ''); ?>> key: <?php echo e($key); ?> value: <?php echo e($value); ?>

this is in line 19

**Comment by philknab** [comment]
`<input type="checkbox" value="1" name="<?php echo e($field->db_column_name()); ?>[]" class="minimal" <?php echo e(Input::old($field->db_column_name()) != '' ? ' checked="checked"' : ''); ?>> key: <?php echo e($key); ?> value: <?php echo e($value); ?>`

this is in line 19

**Comment by snipe** [comment]
Can you show me the value in the `custom_fields` table for that custom field?

**Comment by philknab** [comment]
where can i look for it? sorry i am not so familiar with everything

**Comment by snipe** [comment]
In your database.

**Comment by philknab** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/20083949/18078668/1a5c6f2c-6e8d-11e6-9bab-ec97594c149c.JPG)

this the value of the field?

**Comment by philknab** [comment]
the asdfgghghg thing is just some random name haha because i wanted to test it first

**Comment by snipe** [comment]
If that were true, it shouldn't be erroring on the checkbox code. It would never trigger that branch in the if/else logic.

**Comment by snipe** [comment]
Should be fixed on current dev

**Comment by philknab** [comment]
it's working - nice one
