### ISSUE TITLE
1D barcode taking space on label even when hidden

### ISSUE THREAD

**Issue by samweber** [snipe/snipe-it#2520]
#### Expected Behavior (or desired behavior if a feature request)

When unchecking "Display 1D barcode" in the Barcodes Setting, it should hide the space that the 1D barcode would have taken up when generating asset labels.

---
#### Actual Behavior

Instead, the space where the 1D barcode would have been, there is an empty white space. It hides any text that is underneath it.

---
#### Please confirm you have done the following before posting your bug report:
- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running: **v3.3.0-3-g7ef4f23**
- What OS and web server you're running Snipe-IT on: **Ubuntu 14.04.4**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): **install.sh**
- If you're getting an error in your browser, include that error: **N/A**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: **/hardware/bulkedit**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). **Yes, reproduceable.**
- Indicate whether or not you've manually edited any data directly in the database. **Not edited.**

**Comment by samweber** [comment]
This makes barcodes unusable for me. Any workaround for now? A config file I can recreate? Thank you!

**Comment by samweber** [comment]
Until this is resolved, I manually overrode the CSS in /var/www/snipeit/resources/views/hardware/labels.blade.php to the exact label I will be using.

**Comment by Bingmano** [comment]
I am having this issue as well, is this on track to being resolved?

**Comment by snipe** [comment]
This was fixed in #4354
