### ISSUE TITLE
Error 404 on Create Asset page

### ISSUE THREAD

**Issue by JayLAUK** [snipe/snipe-it#2522]
Hi,

Hopefully you can help me. 

I am having a minor issue with Snipe. I was getting an error 404 which I fixed by updating my DocumentRoot. However the problem has persisted on the Create Asset screen:

![snipe 404 screen](https://cloud.githubusercontent.com/assets/21334416/18085389/e1c00096-6ea2-11e6-8578-3ca23fd9ae69.png)

I am running Version v3.3.0-3-g7ef4f23 on a Windows 7 XAMPP install, I haven't edited any data in the database as this is a clean install.

Any help will be appreciated.

Jay

**Comment by snipe** [comment]
Please check your browser's console for errors.

**Comment by JayLAUK** [comment]
Console is blank.

**Comment by snipe** [comment]
That seems unlikely, if your page is blowing up that hard. What's in your server logs and your laravel log? (There's a reason we ask these questions when you open a ticket. We literally can't help you without those answers.)

**Comment by JayLAUK** [comment]
Laravel Log:

`[2016-08-26 13:00:18] production.ERROR: exception 'PDOException' with message 'SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'forge'' in C:\xampp\htdocs\SnipeIT\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:55
Stack trace:
#0 C:\xampp\htdocs\SnipeIT\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(55): PDO->__construct('mysql:host=loca...', 'forge', '', Array)
#1 C:\xampp\htdocs\SnipeIT\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 C:\xampp\htdocs\SnipeIT\bootstrap\cache\compiled.php(11844): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#4 C:\xampp\htdocs\SnipeIT\vendor\laravel\framework\src\Illuminate\Database\Connection.php(924): call_user_func(Object(Closure))
#5 C:\xampp\htdocs\SnipeIT\vendor\laravel\framework\src\Illuminate\Database\Connection.php(792): Illuminate\Database\Connection->getPdo()
#6 C:\xampp\htdocs\SnipeIT\vendor\laravel\framework\src\Illuminate\Database\Connection.php(677): Illuminate\Database\Connection->reconnectIfMissingConnection()
#7 C:\xampp\htdocs\SnipeIT\vendor\laravel\framework\src\Illuminate\Database\Connection.php(349): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
#8 C:\xampp\htdocs\SnipeIT\vendor\laravel\framework\src\Illuminate\Database\Schema\MySqlBuilder.php(21): Illuminate\Database\Connection->select('select * from i...', Array)
#9 C:\xampp\htdocs\SnipeIT\bootstrap\cache\compiled.php(6325): Illuminate\Database\Schema\MySqlBuilder->hasTable('users')
#10 C:\xampp\htdocs\SnipeIT\app\Models\Setting.php(61): Illuminate\Support\Facades\Facade::__callStatic('hasTable', Array)
#11 C:\xampp\htdocs\SnipeIT\app\Models\Setting.php(61): Illuminate\Support\Facades\Schema::hasTable('users')
#12 C:\xampp\htdocs\SnipeIT\app\Http\Middleware\CheckForSetup.php(17): App\Models\Setting::setupCompleted()
#13 [internal function]: App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 C:\xampp\htdocs\SnipeIT\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#15 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 C:\xampp\htdocs\SnipeIT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 C:\xampp\htdocs\SnipeIT\app\Http\Middleware\NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 [internal function]: App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 C:\xampp\htdocs\SnipeIT\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#20 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 C:\xampp\htdocs\SnipeIT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 C:\xampp\htdocs\SnipeIT\app\Http\Middleware\XssProtectHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 [internal function]: App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 C:\xampp\htdocs\SnipeIT\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\SnipeIT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 C:\xampp\htdocs\SnipeIT\app\Http\Middleware\FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 C:\xampp\htdocs\SnipeIT\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#30 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 C:\xampp\htdocs\SnipeIT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 C:\xampp\htdocs\SnipeIT\bootstrap\cache\compiled.php(13473): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 C:\xampp\htdocs\SnipeIT\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#35 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 C:\xampp\htdocs\SnipeIT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 C:\xampp\htdocs\SnipeIT\bootstrap\cache\compiled.php(11963): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 C:\xampp\htdocs\SnipeIT\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#40 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 C:\xampp\htdocs\SnipeIT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#42 C:\xampp\htdocs\SnipeIT\vendor\misterphilip\maintenance-mode\src\MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode.php(145): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 C:\xampp\htdocs\SnipeIT\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#45 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 C:\xampp\htdocs\SnipeIT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 C:\xampp\htdocs\SnipeIT\bootstrap\cache\compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#49 C:\xampp\htdocs\SnipeIT\bootstrap\cache\compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#50 C:\xampp\htdocs\SnipeIT\bootstrap\cache\compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#51 C:\xampp\htdocs\SnipeIT\public\index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#52 {main}  
[2016-08-26 13:02:40] production.DEBUG: Authenticating user against database.  
`

**Comment by snipe** [comment]
Please repost. I got an email notification with a log in it, but it's not showing for some reason in Github. :-/

**Comment by 777string** [comment]
@snipe 
I am getting this same 404 page when creating a new model/status while on the create asset page. There are no errors when viewing the console when I'm in chrome or Edge. My server is Windows 10 and I have the URL Rewrite installed. 

![image](https://cloud.githubusercontent.com/assets/322276/25674867/72f05902-300a-11e7-9c1f-9f88b8c51d20.png)
