### ISSUE TITLE
Upload Name

### ISSUE THREAD

**Issue by philknab** [snipe/snipe-it#2523]
#### Expected Behavior (or desired behavior if a feature request)
Keep the name of the upload.

-----

#### Actual Behavior

The name gets extended with (i guess) user id and a specific number.
Would be nice if there is only the name of the file what has been uploaded

![unbenannt](https://cloud.githubusercontent.com/assets/20083949/18086795/f828b76a-6eb1-11e6-995d-853d6b8ef8f7.JPG)

Would be nice if the highlighted area is not standing in the file name, so only logo.jpg would be shown.
I speak about the file uploads in the user/view.

Best regards
Phil

**Comment by snipe** [comment]
We do that to avoid conflicting filenames causing files to be overwritten.
