### ISSUE TITLE
/resources/views/licenses/view.blade.php contains extra text

### ISSUE THREAD

**Issue by erik-burgess** [snipe/snipe-it#2525]
#### Expected Behavior (or desired behavior if a feature request)

Extra text should not be displayed. 

-----

#### Actual Behavior

In 3.3 and the 3.4 alpha, /resources/views/licenses/view.blade.php contains the code </div>ey, causing the "ey" to be displayed at the bottom of the page when viewing the license checkout page. On the 3.4 alpha, I believe this is on line 302. 

-----

#### Please confirm you have done the following before posting your bug report:

- [ no ] I have enabled debug mode
- [ yes ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running v3.3.0-3-g7ef4f23
- What OS and web server you're running Snipe-IT on Ubuntu LTS 14.04 / Apache 2.2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- If you're getting an error in your browser, include that error 
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error /admin/licenses/1/view
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). Yes. Screenshot attached. 
<img width="935" alt="screen shot 2016-08-30 at 9 56 14 am" src="https://cloud.githubusercontent.com/assets/20685889/18091894/502243ec-6e98-11e6-9b28-cc7024d55bb1.png">
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
![eyy](https://cloud.githubusercontent.com/assets/197404/18092147/0e47b12c-6e80-11e6-9f75-e8d5f676c78f.gif)

Can't help but think it would have taken less time to open a PR and just fix it ;)

**Comment by erik-burgess** [comment]
Eyyy... sometimes it's early and I don't think about the easy things like that. :/

**Comment by snipe** [comment]
<img src="http://memeguy.com/photos/images/look-at-this-footwork-by-the-fonz-18230.gif">
