### ISSUE TITLE
Assets not updating when a new one is created

### ISSUE THREAD

**Issue by 9hnmai** [snipe/snipe-it#2528]
I tried to add a new computer to our assets and when I submit the form it just seems to reset the page and not update the assets (/hardware/create) , however I am able to update everything but the hardware (components,models,licenses, etc...) 

I enabled debug mode but it doesn't tell me anything. 

Version v3.3.0-16-ge52a0f6
CentOS (3.10.0-327.22.2.el7.x86_64)
Apache/2.4.6 (CentOS)
Installed using Install.sh
I have not edited anything manually and have various Backups

I want to avoid having to restore DB because I haven't set up a chron job yet so they're only backups prior to major changes,

**Comment by snipe** [comment]
Please tell us what's in the error log.

**Comment by 9hnmai** [comment]
XMLHttpRequest cannot load http://prod-inventory/api/statuslabels/5/deployable. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://10.1.1.24' is therefore not allowed access.

is listed in the chrome console. 

I am not sure where the snipe logs are, I couldn't find them in the directory that was listed

**Comment by snipe** [comment]
Your APP_URL doesn't match the URL you're accessing the site from. Fix that, and it will work fine.

**Comment by 9hnmai** [comment]
Alright Ill give it a try, thanks for the quick response.

**Comment by 9hnmai** [comment]
Awesome. Thanks for the help, I figured it out
