### ISSUE TITLE
Import CSV and smtp server setup for email alerts.

### ISSUE THREAD

**Issue by mobeenshaik** [snipe/snipe-it#2531]
Hello All,

OS : CentOS 7
Webserver : not sure, I think apache
Snipe IT Version : v3.3.0-16-ge52a0f6
PHP version : 5.6.24

Issue 1 : Issue with Importing CSV. I think my format is wrong. But I tried to download sample CSV file, but  got following error ( http://docs.snipeitapp.com/sample-assets.csv )

404 - file not found

Issue 2 : About email alerts. While in setup I just entered sender email and to email. And I didn't find any option to configure SMTP server, I think it can't send alerts on email without smtp settings (for sender email ) ,right ? Also I couldn't find any option to Test. 
Can you we customize scheduled reports or custom email alerts other EOL ? if so, how ?

Thank You.

Newbie for Snipe-IT
I am very happy with the interface and features it has.

**Comment by dmeltzer** [comment]
https://snipe-it-manual.readme.io/docs/importing-assets

**Comment by snipe** [comment]
@mobeenshaik Also https://snipe-it.readme.io/docs/configuration#required-outgoing-mail-settings

**Comment by mobeenshaik** [comment]
Thanks about information!

**Comment by mobeenshaik** [comment]
And I was trying to nail into mail things to setup alerts, but I didn't modified any thing and I went back to browser, it has started showing error "HTTP ERROR 500".

Any ideas ?

**Comment by snipe** [comment]
You'd need to enable debugging, as mentioned on the Getting Help page: https://snipe-it.readme.io/docs/getting-help
