### ISSUE TITLE
Database Backup Failure

### ISSUE THREAD

**Issue by howeluck** [snipe/snipe-it#2532]
#### Expected Behavior (or desired behavior if a feature request)

I expected the database backup functionality to work.

-----

#### Actual Behavior

The "Generate Backup" button appears to work but nothing happens. It reads "Success: A new backup file was successfully created." but no database backups appear in the list.

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.2.0-53-gfff2bce

- What OS and web server you're running Snipe-IT on
Windows Server 2012 R2 - IIS web server

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation

- If you're getting an error in your browser, include that error
No error is listed, but when running the backup from a dos prompt I get this error: Backup failed because ZipArchive::close(): Read error: Bad file descriptor.

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Admin > Backups, clicking on the generate backup button.

- If a stacktrace is provided in the error, include that too.
No stacktrace is provided.

- Any errors that appear in your browser's error console.
None that I can see.

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
The generate backup feature is not available in the demo.

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
[2016-08-31 08:16:39] production.ERROR: backups backups : error: Failed to backup  because: The dump process failed with exitcode 1 : General error :

- Include what you've done so far in the installation, and if you got any error messages along the way.
The installation is completed without any errors once I got the Pre-Flight running

- Indicate whether or not you've manually edited any data directly in the database
Only select queries have been run against the database -- no modification of data.

**Comment by snipe** [comment]
Please correct your `DB_DUMP_PATH` in your `.env` file to point to wherever mysqldump lives on your server. https://snipe-it.readme.io/docs/configuration#required-database-settings

**Comment by howeluck** [comment]
It is mapped to the correct path.

![capture](https://cloud.githubusercontent.com/assets/21362610/18145340/6b17b42c-6f90-11e6-81f3-415bf2896859.PNG)

**Comment by snipe** [comment]
Is the storage directory (and all subdirs) writable?

**Comment by JExactly** [comment]
I am also having this issue in IIS8. No backups generate. I have also pointed my DBDumb to point to the Mysql BIN folder in program files. This did not resolve it.

![image](https://cloud.githubusercontent.com/assets/14076881/18146197/64956d40-6f9c-11e6-87d3-f08c5840fe3e.png)

I have also made sure that IUSR and IIUSR have write access as well.

**Comment by howeluck** [comment]
Yes, I have allowed full ACL permissions for IUSR on C:\Windows\Temp as well as c:\inetpub\wwwroot\snipe-it (including all sub folders).

**Comment by howeluck** [comment]
Looks like granting IIS_IUSRS full premissions to everything fixed the issue. 
![capture](https://cloud.githubusercontent.com/assets/21362610/18213301/2c7a2d84-710d-11e6-9ba3-b0edd2a4bfb1.PNG)

You can close this issue again, thank you.

**Comment by JExactly** [comment]
Howeluck,

I have added write/modify permissions for IUSR and IIS_IUSR and I am still unable to runa backup. It fails on the dump.

![image](https://cloud.githubusercontent.com/assets/14076881/18226718/fd7ac292-71dd-11e6-893d-37b107206ad9.png)

What am I missing?

**Comment by sphere720** [comment]
I too am having the same issue as @JExactly . All perms set as directed and DB_DUMP_PATH='C:\\PROGRA~1\\MARIAD~1.0\\bin'. Yet I get the same error as what he posted.

**Comment by sphere720** [comment]
@howeluck , when you say granting IIS_IUSRS full perms to "everything", what do you mean. I have granted full perms for this to the entire snipe-it folder (after reading that) and still had the same issue.

**Comment by howeluck** [comment]
@sphere720 I gave full access to the inet folderpub. Your database dump path needs double slashes (see below).


DB_DUMP_PATH='C:\\PROGRA~1\\MARIAD~1.0\\bin'

**Comment by sphere720** [comment]
@howeluck  Thanks for the prompt response. I went back and gave IIS_IUSRS full access to the inetpub directory. My db dump path did have the double slashes (code snip below). Still coming up with the same error. "The system cannot find the path specified....".

`DB_DUMP_PATH='C:\\PROGRA~1\\MARIAD~1.0\\bin'`

**Comment by sphere720** [comment]
My issue was resolved in Backup #2454.
