### ISSUE TITLE
asset maintenance

### ISSUE THREAD

**Issue by philknab** [snipe/snipe-it#2533]
#### Expected Behavior (or desired behavior if a feature request)

date format should be YYYY.mm.dd

-----

#### Actual Behavior

date format is dd.mm.YYYY and if i want to create a maintenance it fails because the wrong format.
where can i change this?

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - **v3.3.0**
- What OS and web server you're running Snipe-IT on - **linux**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - **manual**
- If you're getting an error in your browser, include that error **no error**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **asset_maintenances/create**

**Comment by snipe** [comment]
You cannot change that at this time. If you're trying to create a maintenance, you need to use YYYY-mm-ddd format. (Or use the date picker that's provided in the maintenance form.)

**Comment by philknab** [comment]
Hey @snipe 
When i use the date picker, it writes the dd.mm.YYYY format?
And is it normal that there are 2 date pickers? One is with arrows up and down and one is with arrow down. So i can use 2 date pickers in my date field. That's confusing
![unbenannt](https://cloud.githubusercontent.com/assets/20083949/18156946/80cf871a-701a-11e6-8663-e31cc2e19ca1.JPG)

**Comment by philknab** [comment]
`  
          <div class="form-group {{ $errors->has('start_date') ? ' has-error' : '' }}">
              <label for="start_date" class="col-md-3 control-label">{{ trans('admin/asset_maintenances/form.start_date') }}
                  </label>
              <div class="input-group col-md-2{{  (\App\Helpers\Helper::checkIfRequired($assetMaintenance, 'start_date')) ? ' required' : '' }}">
                  <input type="date" class="datepicker form-control" data-date-format="yyyy-mm-dd" placeholder="Select Date" name="start_date" id="start_date" value="{{ Input::old('start_date', $assetMaintenance->start_date) }}">
                  <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                  {!! $errors->first('start_date', '<span class="alert-msg"><i class="fa fa-times"></i> :message</span>') !!}
              </div>
          </div>

          
          <div class="form-group {{ $errors->has('completion_date') ? ' has-error' : '' }}">
              <label for="start_date" class="col-md-3 control-label">{{ trans('admin/asset_maintenances/form.completion_date') }}</label>
              <div class="input-group col-md-2">
                  <input type="date" class="datepicker form-control" data-date-format="yyyy-mm-dd" placeholder="Select Date" name="completion_date" id="completion_date" value="{{ Input::old('completion_date', $assetMaintenance->completion_date) }}">
                  <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                  {!! $errors->first('completion_date', '<span class="alert-msg"><i class="fa fa-times"></i> :message</span>') !!}
              </div>
          </div>`

in the asset_maintenance view.blade the format is YYYY-mm-dd but it fails :(

**Comment by snipe** [comment]
Wow, I have no idea. That's super weird. What language are you set to? (I cannot possibly imagine why that would matter, but I have no other ideas right now, so bear with me while I ask a lot of weird questions.)

**Comment by philknab** [comment]
i set it to german, should i set it to english and test it again?

**Comment by philknab** [comment]
Nope still fails. 
Well i never worked with the asset maintenance but now we would need it and then that fail. Hopefully version 3.4.0 will come out soon and let's see if the error is still there.
I don't know why it fails. Other users should have no problem i guess.

**Comment by snipe** [comment]
If this is a bug on our side, it's one I've literally never seen before. I'm afk right now, but will definitely investigate and get this figured out.

**Comment by philknab** [comment]
One more question.

Is there any file where the format can be changed or set up?

**Comment by snipe** [comment]
To clarify, there should be two datepickers. First is start date and the second is completion date. (That's why the first one is required and the second isn't.) But it should absolutely be using the correct date format.

**Comment by philknab** [comment]
I know but in the start date field and completion date field there are two buttons to select the date.
![unbenannt](https://cloud.githubusercontent.com/assets/20083949/18157733/740fc4f4-701f-11e6-9e0a-579c292c4284.JPG)

Don't criticize my paint skills haha.

**Comment by snipe** [comment]
No, you should t be seeing that. Can you tell me what browser you're using, and whether there are any errors in your browser console when you load the page or click into the date picker?

**Comment by philknab** [comment]
Well that is really funny.
Normally i use SnipeIT in Google Chrome, but i also have Firefox installed and tried in in Firefox.

In Chrome it failed - in Firefox it worked.
I don't know why but that is really weird.

**Comment by philknab** [comment]
In the Chrome console there are no errors when i load the page or click into the date picker...

**Comment by snipe** [comment]
That's really helpful info - thank you!

**Comment by philknab** [comment]
This is the Chrome view : 
![unbenannt](https://cloud.githubusercontent.com/assets/20083949/18164235/16581f12-703f-11e6-85ed-ecce528518e5.JPG)

This is the Firefox view: 
![unbenannt1](https://cloud.githubusercontent.com/assets/20083949/18164238/1d62f5fc-703f-11e6-9cfb-28cce6856983.JPG)

And both won't work :(

**Comment by philknab** [comment]
In IE it is the same view as in Firefox  but still no progress..

**Comment by philknab** [comment]
@snipe it's working haha!

I don't know why but the supplier was not listed there. I've set up a new snipeit locally on xampp and compared these two environments. I saw that the supplier was missing. So i copied the supplier part into the asset_maintenance/edit_blade and then it worked.

I don't know why it wasn't there but this was really weird.

<iframe src="//giphy.com/embed/Ld0P4AdeSDjoY" width="480" height="480" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="http://giphy.com/gifs/funny-yes-old-spice-Ld0P4AdeSDjoY">via GIPHY</a></p>

**Comment by philknab** [comment]
` 
          <div class="form-group {{ $errors->has('supplier_id') ? ' has-error' : '' }}">
              <label for="supplier_id" class="col-md-3 control-label">{{ trans('admin/asset_maintenances/table.supplier_name') }}
                 </label>
              <div class="col-md-7{{  (\App\Helpers\Helper::checkIfRequired($assetMaintenance, 'supplier_id')) ? ' required' : '' }}">
                  {{ Form::select('supplier_id', $supplier_list , Input::old('supplier_id', $assetMaintenance->supplier_id), ['class'=>'select2', 'style'=>'min-width:350px']) }}
                  {!! $errors->first('supplier_id', '<span class="alert-msg"><i class="fa fa-times"></i> :message</span>') !!}
              </div>
          </div>`

This part was missing. I really don't know why.
