### ISSUE TITLE
[Feature Request] Product Key Field 252 character limitation - consider raising limitation to 1024 characters

### ISSUE THREAD

**Issue by delize** [snipe/snipe-it#2535]
#### Expected Behavior (or desired behavior if a feature request)

I expect it to allow a serial number (regardless of character limits) to be entered into the Product Key Field on the License Asset Page

-----

#### Actual Behavior

Character count appears to be limited to 252 characters. Causing longer product keys (like those from 3T.io) to discard the remaining product keys in the Web UI.

3T.io/MongoChef's license is ~512 characters. I also expect that there are other license files that could be potentially longer. Please consider raising the character limitation to 1024. I expect that it is limited to 256.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.3.0-3-g7ef4f23
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- If you're getting an error in your browser, include that error
N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
domain.org/admin/licenses/1/edit
- If a stacktrace is provided in the error, include that too.
N/A
- Any errors that appear in your browser's error console.
N/A
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
Created a database of users, imported physical assets and two product license keys.
- Indicate whether or not you've manually edited any data directly in the database
No

**Comment by delize** [comment]
Just to also add, the Notes function does not have this limitation, which allows me to post the full Product Key. This works as a temporary work around, but it would be helpful in any case to increase the character limitation.

**Comment by erik-burgess** [comment]
Would like to second this. I changed the DB field type to mediumtext as a workaround, but that's probably not a good longterm solution.

**Comment by delize** [comment]
I would actually like to make the request to extend it to 2046 characters if possible. That should prevent any future issues with any form of serial or key.

**Comment by delize** [comment]
I may be mistaken but it looks like line 324 of snipe-it/database/2016_02_13_071006_create_snipeit_laravel_database.php

It would need to be changed to:
 $table->varchar('serial', 2048)->nullable();

I think?

**Comment by snipe** [comment]
No, that file can actually be removed. It was a backup for when we switched fro v2 to v3. All of the database migrations are in the `database/migrations` folder, and a new migration would need to be created for this.

**Comment by delize** [comment]
Oh damn, yeah, that was much more complicated then just a single page. :)

Thanks for creating the change @snipe 👍! This application rocks!

**Comment by snipe** [comment]
![kid](https://cloud.githubusercontent.com/assets/197404/19795427/23409664-9c90-11e6-8faa-46b8b12402fb.gif)
