### ISSUE TITLE
How to access Snipe-IT via IP

### ISSUE THREAD

**Issue by Akirien** [snipe/snipe-it#2538]
Hi there,

#### Expected Behavior (or desired behavior if a feature request)

I want to access Snipe-IT website via the machine's IP address instead of its hostname.

#### Actual Behavior

When I use IP address (local IP) to open the webpage, it redirects me to the Apache homepage.

Any help would be much appreciated.

Thank you.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by philknab** [comment]
have you pointed the document root to snipeit/public?

**Comment by Akirien** [comment]
@philknab Which files do I need to edit? Is it apache2/apache2.conf?

**Comment by philknab** [comment]
i configured the **/etc/apache2/sites-available/000-defaul.conf** then it worked
