### ISSUE TITLE
DELIVERY REPORT RECEIPTS / PACKING SLIPS / TRANSFER ORDER FORM

### ISSUE THREAD

**Issue by iamgeneuz** [snipe/snipe-it#2539]
Feature Request Inquiry:

If the system currently supports, packing slips, delivery receipts or transfer order forms.

**Comment by snipe** [comment]
It supports file uploads, so you could probably attach them that way.

**Comment by iamgeneuz** [comment]
Hi Snipe, 

Thanks for the reply.

Apologies, question is supposed to be if the system creates its own delivery reports when transferring assets from 1 location to another?

**Comment by Isotop7** [comment]
This would be greatly appreciated here too. Its the only thing holding us back from using SnipeIT.
Right now we create a document a user has to sign to acknowledge he received the asset.

We could just create an asset report but there is no way to design this report.

Thank you!
