### ISSUE TITLE
RETIREMENT OF ASSETS (HARDWARE, COMPONENTS)

### ISSUE THREAD

**Issue by iamgeneuz** [snipe/snipe-it#2540]
Hi Snipe,

I just wanted to ask if there is a "Retire" asset feature currently in the system?

I am running the 3.0 version of Snipe IT locally.

Thanking for your future reply.

**Comment by snipe** [comment]
I think most people just create a new status label (called "Retired" or something) and give it a status type of "archived"

**Comment by iamgeneuz** [comment]
Yeah! I forgot you have custom status in the system.

Thanks Snipe.
