### ISSUE TITLE
Installation Problem Ubuntu 16.04

### ISSUE THREAD

**Issue by Supsuop** [snipe/snipe-it#2542]
#### No visible text fields

Hello together,

today i have downloaded snipe-it and i am trying to install it.
First of all i thought the installation going to take a long time.
But I noticed when i pressed Enter there was an query.
First a password query.

Then again I have waited some time and nothing happened.
Then again I pressed 3 or 5 times"enter" than out of nothing there appeared this:

```
New password: 

Re-enter new password: 





Securing the MySQL server deployment.

Connecting to MySQL using a blank password.

VALIDATE PASSWORD PLUGIN can be used to test passwords
and improve security. It checks the strength of password
and allows the users to set only those passwords which are
secure enough. Would you like to setup VALIDATE PASSWORD plugin?

Press y|Y for Yes, any other key for No: Please set the password for root here.
By default, a MySQL installation has an anonymous user,
allowing anyone to log into MySQL without having to have
a user account created for them. This is intended only for
testing, and to make the installation go a bit smoother.
You should remove them before moving into a production
environment.

Remove anonymous users? (Press y|Y for Yes, any other key for No) : 
 ... skipping.


Normally, root should only be allowed to connect from
'localhost'. This ensures that someone cannot guess at
the root password from the network.

Disallow root login remotely? (Press y|Y for Yes, any other key for No) : 
 ... skipping.
By default, MySQL comes with a database named 'test' that
anyone can access. This is also intended only for testing,
and should be removed before moving into a production
environment.


Remove test database and access to it? (Press y|Y for Yes, any other key for No) : 
 ... skipping.
Reloading the privilege tables will ensure that all changes
made so far will take effect immediately.

Reload privilege tables now? (Press y|Y for Yes, any other key for No) : 
 ... skipping.
All done! 
##  Creating MySQL Database and user. 
##  Please Input your MySQL/MariaDB root password: 
Enter password: 
##  Securing Mysql
##  Installing and configuring composer
```

**Comment by therealjoshuad** [comment]
I've seen this before to, on 16.04 and 16.04.1. Following these commands in the guide:
`wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh
chmod 744 install.sh
./install.sh`

I figured I'd give it a go in Ubuntu 14.04, and the install script runs fine.

**Comment by bitzend** [comment]
I experienced this same behavior when I try and run the install while SSH'd into a virtual machine.
The last script prompt is related to  ###updating  hostname  ##  and then the script appears to hang.
After hitting return a couple times  I am prompted for a Password and then to repeat it..    From my previous installations it seemed to want the password for the MYSQL root user.  When I entered that and a couple more {returns} I got a stream of text from the  MYSQL secure script and another prompt for the root MYSQL user password.    The  script  continued to completion after that for me and the installation was successful.

**Comment by mtucker6784** [comment]
Pretty sure this has to do with how the script is handling some of the logging messages, as the caret that sends text to the log file seems to eat the first "mysql install introduction" text; this is probably what's making the install process look like it's stuck in stupid.

I'm working on the script and will hopefully have something a bit more U 16 friendly so the installs go more smoothly.

**Comment by Ny0tNy0t** [comment]
i have face this problem until i create 2 version Os of Ubuntu,
until i find pages that show how to install on ubuntu and some modification on ./install.sh scripts

https://mangolassi.it/topic/6967/installing-snipe-it-on-centos-7-and-mariadb/84

maybe this can help for solved the problem

**Comment by ammarmalhotra** [comment]
i had the same issue on Ubuntu 16.04, first time when it ask for root password i put wrong password then it will ask again put the right password it will start without problem.
