### ISSUE TITLE
Feature Request - Request-able Accessories

### ISSUE THREAD

**Issue by rudashi** [snipe/snipe-it#2543]
If it's possible, please add checkbox Requestable to Accessories

**Comment by goneafk** [comment]
I've seen a few comments out there looking for Store-like capabilities.

Something like this where the units and accessories are requestable and could show a price would act in many ways like a store.

I've looked through the code and it /seems/ like adding requestability to accessories should work similarly to adding Model Number to accessories. I just haven't had the time to play with the code to see if I can do it myself.

Does this sound achievable in a realistic way or it could work, but your crazy and go read the code more?

**Comment by pricew826** [comment]
I agree that this would be an ideal feature. We want to use SnipeIT like an intranet where managers can come request a PC for a new employee. We'd like them to be able to request all the software and accessories that they need as well.

**Comment by wilsonlspacheco** [comment]
Our company has a Snipe-IT costumer and have interest on this too . Please Dev this as soon as possible. Thks

**Comment by TylerH22** [comment]
This is an update that our company is anxiously awaiting as well.  Allowing user's to request things such as USB drives, Ink cartridges, paper, etc would allow us better manage our inventory.

**Comment by wilsonlspacheco** [comment]
This is a very important feature. Every day our employees request accessories to IT Dpt. USB Drives to backup files, mouses, keyboards, HDMI/DisplayPort cable adapters, etc. Please do not forget this feature!

**Comment by ReignSol** [comment]
This would be a very nice feature for us as well.

**Comment by litingbin** [comment]
yes,a good feature for our company

**Comment by yanagha** [comment]
+1

**Comment by michelrb** [comment]
+1 for this. 
Would be highly appreciated

Is there any chance to get some sort of release date for such a feature?

**Comment by duel007** [comment]
This hasn't been implemented and shouldn't be closed.

**Comment by viclou** [comment]
Still interest in this, so I'm reopening this one

**Comment by AImXOo0o** [comment]
+1
