### ISSUE TITLE
localhost URL on logo

### ISSUE THREAD

**Issue by diktus** [snipe/snipe-it#2545]
i have upgrade to version v3.3.0-16-ge52a0f6. almost everything work but i found logo or text in the top of the site has wrong URL. When i click it go to localhost. I have setup URL on app config and .ev file but still can not solve

**Comment by snipe** [comment]
Please check the APP_URL variable in your .env file.

**Comment by snipe** [comment]
The logo links to whatever that URL is in your `.env`. It will output whatever you have for your APP_URL.

```
<a class="logo navbar-brand no-hover" href="{{ config('app.url') }}">
```

Also make sure you cleared your compiled cache, if you changed that value after your cached the settings. https://snipe-it.readme.io/docs/common-issues#changes-to-my-env-file-dont-seem-to-be-updating

**Comment by diktus** [comment]
I have change the APP_URL on .env file. Also i have change on the folder /config/app

**Comment by snipe** [comment]
Try clearing your env cache then (as mentioned above). That APP_URL variable is where that URL comes from.

**Comment by snipe** [comment]
> Also i have change on the folder /config/app

What?
