### ISSUE TITLE
Custom Category Types

### ISSUE THREAD

**Issue by aggieflash11** [snipe/snipe-it#2548]
I've done a fair bit of googling, but didn't come across any flashing neon signs, so thought I'd give posting here a shot. 

Is is possible to create custom Category Types? I have to do yearly inventory for my university, and it'd be very helpful to have Inventory Asset and NI Asset, rather than having (say) Inventory Monitors of type Asset and NI Monitors of type Asset. 

Also, has any thought been given to the ability to sort Asset Models by Manufacturer?

Are there any plans on allowing multiple fieldsets per Asset Model?

We just upgraded to v3.3.0-16-ge52a0f6 yesterday. 

Thanks for all of the great work you've put into this project! It's made my life orders of magnitude eaiser!

**Comment by snipe** [comment]
In the future, please create separate issues for each of these. Otherwise it's easy for things to get lost. 

I'm still not clear on what you're asking for with regards to custom category types. What is the actual problem you're trying to solve? (And what does NI Asset mean?)

**Comment by aggieflash11** [comment]
Sorry for the confusion. Do you want me to create a separate request for each, or continue with the one ticket at the moment?

Ultimately, I'm looking for the ability to create custom Category Types. I want more than just Accessory, Asset, Consumable, or Component. (NI Asset would denote a Non-Inventory Asset, as far as the school is concerned.)

**Comment by snipe** [comment]
What would a Non-Inventory asset even be though? I'm trying to understand your use case.

**Comment by aggieflash11** [comment]
Computers under $500. Monitors under $1,000.

**Comment by thanukalpa** [comment]
How to create custom asset category type

**Comment by wmunsell** [comment]
@snipe Is there any update on this? Curious to know the level of effort that would be needed to accomplish this feature addition. the use case that i particularly need is the ability create custom category types as well as sub-types. I wouldn't mind trying to implement a version of this within my own instance, however, merging in new updates would be a nightmare.
