### ISSUE TITLE
snipe-it install error

### ISSUE THREAD

**Issue by kylin39** [snipe/snipe-it#2550]
centos 6.6 
china
version the latest version

when i install them Will use composer, but sources are on github, because access to it is very slow in China, I would like to source locally into China, according to the general method changed or not, to change the method of source request, thank you.

**Comment by rebustillojrev** [comment]
hi, I need help in installing snipe it locally, im using xampp, hope any one can help me please....

if i access this http://localhost/snipet/, the message is ->

D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory.

if i access http://localhost/snipet/public/ i got an error ->


Warning: require(C:\xampp\htdocs\snipet\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\snipet\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\snipet\bootstrap/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\snipet\bootstrap\autoload.php on line 17

please help....

**Comment by snipe** [comment]
@rebustillojrev it's literally telling you that your DocumentRoot should be the public directory. so set the DocumentRoot of your site to the public directory and restart your web server. The second error is because you either didn't run composer, or it failed.

https://snipe-it.readme.io/docs/common-issues

**Comment by ch-gz** [comment]
@kylin39 I know the pain, just buy a VPN then download it.
