### ISSUE TITLE
Feature Request - Printable handover

### ISSUE THREAD

**Issue by B3RN0UT** [snipe/snipe-it#2552]
Would be nice if it's possible in the future to create for each user a PDF (or something else) document with the last added asset/accessories... with a full custom layout. 
Possible document variables could be helpfull:
- Date
- Which asset
- Who added the asset to which employee
- EULA
- Signature field

My request is very similiar to the EULA function of Snipe-IT but it's necessary for us to hand out the employees an acknowledgement with signature fields for how to use the device and what to do in case of any damage and so on.

Thanks in advance.

**Comment by pvhkai** [comment]
Hey B3RN0UT,

I would really like that kind of Handover. I only wold add a Logo and a companyname in your request. :)

**Comment by sphere720** [comment]
I second this request. I know that my supervisor has asked me about it and I brought it up here as more of a question. But never got around to a feature request (hella busy all the time).

**Comment by imie** [comment]
im also seconded this request. now im printing manually using word for assets handover.

**Comment by pvhkai** [comment]
Hey dear all,
what about that request? I plan to create an handover by myself but if you tell me now that this will be in the system with the next update I will not do so :) (makes no sensce if you do the same than I)

**Comment by dominicjaeckelquandoo** [comment]
Hi,

any news about the handover thing?
@pvhkai did you roll out sth like this? If yes how?

Best,

**Comment by pvhkai** [comment]
Hi @dominicjaeckelquandoo,

we created a handover sheet using MS reporting server. We linked the SQL server with the reporting server and indexed the Fullname of the Snipe database. 

So we dont use a php based handover-tool. 

Best,

**Comment by snipe** [comment]
Printable inventory of users is currently on develop.

**Comment by dominicjaeckelquandoo** [comment]
Hey snipe,

any idea when this will be released?

Best Regards

**Comment by nachoguapito** [comment]
can we add some text agreement during printing the assets?

like " I confirm that I have received the above laptop unit with the above configuration and confirm that I am personally responsible for any damage done due to mishandling and I authorize the company to deduct the cost from my salary account.

I agree that I will return the above laptop unit when I leave the company. "

**Comment by user6gh** [comment]
Hi snipe,
You wrote that printable inventory of users is on develop (2 years ago). Do you have any updates? Still in progress?

Regards,

**Comment by zstinnett** [comment]
Any updates? This is a required feature for my use case. 

Thanks for all the work you have done!

**Comment by biorez27** [comment]
+1
Our company would like to have this feature too.
