### ISSUE TITLE
Installation guide...

### ISSUE THREAD

**Issue by rebustillojrev** [snipe/snipe-it#2553]
Hi Snipe, Im new in laravel, I would like to ask help on installing your app, hope u can help me...

I copy it locally in my xampp, I access the path 

http://localhost/snipet/public/ -> the ff. errors appeared :

Warning: require(C:\xampp\htdocs\snipet\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\snipet\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\snipet\bootstrap/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\snipet\bootstrap\autoload.php on line 17

**Comment by snipe** [comment]
Please don't spam the issues with multiple copies of the same question.
