### ISSUE TITLE
LDAP Setup

### ISSUE THREAD

**Issue by Poenskop** [snipe/snipe-it#2556]
Hi all,

Loving Snipe-IT!!! :)

Just would like to get LDAP to work... Would like to know if there is anything on the LDAP page that needs to be changed? Your assistance will be greatly appreciated!

![1](https://cloud.githubusercontent.com/assets/4991715/18215994/5d84bc18-7154-11e6-93d1-ed01e4731bf4.png)

**Comment by snipe** [comment]
Well, are you having any problems with it? If so, what are the problems? Hard to troubleshoot an issue when you don't know what the issue is. The LDAP host should probably be just the server name, tho, without the extra parameters

**Comment by Poenskop** [comment]
Hey @snipe I get the following error:

![image](https://cloud.githubusercontent.com/assets/4991715/18217902/a5b38e28-715f-11e6-8236-a543ea260198.png)

Thanks for the help! :)

**Comment by snipe** [comment]
That's not actually an error. Please check your laravel logs for an actual error, per the Getting Help documentation.

**Comment by snipe** [comment]
Any update?

**Comment by Poenskop** [comment]
I get the following error in laravel.log:

`[2016-09-05 19:35:24] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function App\Models\ldap_connect()' in C:\inetpub\wwwroot\snipe-it\app\Models\Ldap.php:43`

**Comment by snipe** [comment]
Please check the common issues page. You don't have php-ldap installed on your server.

**Comment by Poenskop** [comment]
Thanks for pointing me in the right direction! I enabled **php_ldap.dll** in **IIS Manager** > **PHP Manager**.

![image](https://cloud.githubusercontent.com/assets/4991715/18263074/576e5da6-7407-11e6-99d6-d25821fb1eb4.png)

I then went to **LDAP Bind Username** in **Admin** > **Settings**, and changed the username to DOMAIN\USER. LDAP now syncs!

Once again, thank you for the assistance! :D
