### ISSUE TITLE
[Feature Request] Allow bulk edit of Notes field in Bulk Editor

### ISSUE THREAD

**Issue by delize** [snipe/snipe-it#2558]
#### Desired Behavior

When selecting multiple assets in the hardware field, allow for notes to be bulk edited.

This would be very convenient as I am trying to leave notes in those comments, and right now I have to use database commands to do a bulk edit.

---
## The Notes Field does not show in the bulk editor (/hardware/bulkedit) for "All Assets" (/hardware).

Thanks!

![image](https://cloud.githubusercontent.com/assets/4028612/18220283/376ad834-7125-11e6-9b89-5ec64a5c52ee.png)
(Software)

**Comment by Prodeguerriero** [comment]
For what it is worth, I second this request @snipe
