### ISSUE TITLE
Permission granularity issues

### ISSUE THREAD

**Issue by ebonweaver** [snipe/snipe-it#2559]
Sorry if this is the wrong place, not sure how much this is a bug vs a feature request, but it's a problem for our organization.  The granting of permissions has a lot of issues for us.  The only actual bug for sure is that "Categories" appears for anyone in the nav panel, but clicking it gives them the sad panda.  They shouldn't have the link shown if they don't have access to it.

Past that, we have an inventory manager, and I can't actually given him the rights needed to do his job without giving him super admin which gives him a lot of stuff we don't want him to have access to.  Specifically:

Want access to:
Categories
Manufacturers
Suppliers
Status Labels
Locations
Models

Do NOT want access to:
companies
settings
custom fields
backups
groups
add/mod users

Unsure of depreciations, haven't figure out what those will do yet.

From what I can see right now, the above is impossible, because it's all or nothing under super admin.  Ideally all or most of the above would be granular items just like all the other permissions items for assets, consumables, etc. so access based on job function would be possible.

**Comment by snipe** [comment]
This should be available in the upcoming v4 release
