### ISSUE TITLE
[Feature Request] Print out User's Assigned Asset

### ISSUE THREAD

**Issue by anhdeptraihq** [snipe/snipe-it#2562]
We are using the snipe-it v3.2 with 200 users. Currently, very hard to print out the user's assigned asset list to hardcopy form. Then User sign on it and attach back pdf file back to User profile.

Could you consider a feature function to manage Printing Form of User's assigned asset?

Regards, 
Anhdeptrai

**Comment by dennislittle** [comment]
Check i want this feuture to. Before in version 2.0 we just printed out the page with al the assets but un fortunaly we now have to print a page per categorie.

**Comment by MPIAE-IT** [comment]
We would need this feature as well!

**Comment by Bigben83** [comment]
To be able to print or PDF a page for Assets assigned to users would be fantastic, espically when you are wanting to do an audit on what users have. this also would be good for consumables as well.

**Comment by Bigben83** [comment]
It would be very simple to duplicate the label printing and add a bit more information to it., i.e. image, user.

**Comment by dedeoglumrt** [comment]
+1 very important case i think.

**Comment by snipe** [comment]
@dedeoglumrt - that's why it's been implemented.

**Comment by dedeoglumrt** [comment]
@snipe thank you (:

**Comment by tbradsha** [comment]
Thanks!

**Comment by happicamper** [comment]
Currently pulling the newest docker image and can't wait to test it out!
@snipe thank you so much!
