### ISSUE TITLE
Assets Maintenance displays "No matching records found"

### ISSUE THREAD

**Issue by kishfash** [snipe/snipe-it#2567]
When I open Assets Maintenances page, it show "No matching records found". I just upgrade from version 2.xx to version 3.3.0. I have some records entered while using the old version.

When open the Assets Maintenance Reports page, I can see all the maintenance records.

Please I need help to resolve this.

Thanks @snipe for the great work.

#### Expected Behavior (or desired behavior if a feature request)

List assets maintenance record

-----

#### Actual Behavior

No matching records found

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running:  v3.3.0-16-ge52a0f6
- What OS and web server you're running Snipe-IT on: Windows 2008 , Wamp
- What method you used to install Snipe-IT (install.sh,)
- If you're getting an error in your browser, include that error : NO error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: http://192.168.1.30/ictassets/admin/asset_maintenances
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - NO

**Comment by dmeltzer** [comment]
Hi,

Do you see any errors if you go to <baseurl>/api/asset_maintenances/list ?

**Comment by kishfash** [comment]
Hi @dmeltzer,
Thank for the reply.

No error shown at api/asset_maintenances/list

**Comment by dmeltzer** [comment]
Is anything shown at all there?  Or is it just a blank screen.

**Comment by kishfash** [comment]
Attached are the screenshots for Assets Maintenance and Report Page. It shows "No matching records found".
Asset Maintenances

![asset_maintenances_page](https://cloud.githubusercontent.com/assets/17705741/18275578/85510a6a-743f-11e6-9153-849705125017.JPG)

Asset Maintenance Report

![asset_maintenance_report](https://cloud.githubusercontent.com/assets/17705741/18275585/947b9c9e-743f-11e6-82d1-89ae3a196148.JPG)

**Comment by dmeltzer** [comment]
Hi.  I understand that you are not seeing items on the asset_maintencances page.  Usually that means there is an issue with the ajax request that populates that.  Do you see anything at all if you go to `/api/asset_maintenances/list` ? It should display json.  If it's blank thats one issue, if it shows an error page that's a different issue.

**Comment by kishfash** [comment]
Please, can you give steps to check the /api/asset_maintenances/list . Not sure if i'm getting it right. Because I can't see any json. Please pardon me, I'm not really a php programmer but can always find my way around it. Thank you.

**Comment by kishfash** [comment]
Same thing happening with https://demo.snipeitapp.com/admin/asset_maintenances page after it's upgraded to 3.4.
Any solution pls.

**Comment by kishfash** [comment]
Working fine now after i upgraded to Version v3.4.0-9-g67315d8.

Thank you

**Comment by Allenvh** [comment]
I am having the same issue with version  v3.4.0-9-g67315d8, any idea how to fix it?

**Comment by snipe** [comment]
@Allenvh need logs, etc. We can't troubleshoot anything for you if you don't provide us with information.
