### ISSUE TITLE
Not able to receive emails

### ISSUE THREAD

**Issue by pavan137049** [snipe/snipe-it#2568]
Hi ,
I was successfully able to setup snipe it on Ubuntu 16.04 and able create user and login . But i am not getting user login credentials through mail .
After the setup i edited the Docker.env file with gmail smtp login details.
Any suggestions ? @snipe 

find the attached docker.env file 

Docker Environment File

#Database Variables
MYSQL_ROOT_PASSWORD=XXXXXXX
MYSQL_DATABASE=snipeit
MYSQL_USER=snipeit
MYSQL_PASSWORD=XXXXXXX

#Email Variables
MAIL_PORT_587_TCP_ADDR=smtp.gmail.com
MAIL_PORT_587_TCP_PORT=587
MAIL_ENV_FROM_ADDR=snipeit.num@gmail.com
MAIL_ENV_FROM_NAME=Snipe IT
MAIL_ENV_ENCRYPTION=tls
MAIL_ENV_USERNAME=snipeit.num@gmail.com
MAIL_ENV_PASSWORD=XXXXXXXX

#SNIPE-IT Variables
APP_ENV=production
APP_DEBUG=false
APP_KEY=Y5hJeC7x1i7OxhDrvrQPlB9KvCorvRdO
APP_URL=http://127.0.0.1:32782
APP_TIMEZONE=Asis/Kolkata
APP_LOCALE=en

**Comment by snipe** [comment]
If you're using Gmail, I think you should be using you username, not email address, as the email username. Also there are some additional steps you have to take. Please see the documentation (scroll down to gmail)

https://snipe-it.readme.io/docs/configuration#required-outgoing-mail-settings

**Comment by pavan137049** [comment]
@snipe 
As suggested i copied the .env.example file to .env file and edited with correct gmail smtp settings. After doing this when i tried to login, i am getting error page saying " whoops, looks like something went wrong".

Attaching .env file


# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=ChangeMe
APP_URL=null
APP_TIMEZONE='Asia/Kolkata'
APP_LOCALE=en


# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=null
DB_USERNAME=null
DB_PASSWORD=null
DB_PREFIX=null
DB_DUMP_PATH='/usr/local/bin'

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=snipeit.num
MAIL_PASSWORD=XXXXXXXX
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=snipeit.num@gmail.com
MAIL_FROM_NAME='Snipe-IT'


# --------------------------------------------
# REQUIRED: IMAGE LIBRARY
# This should be gd or imagick
# --------------------------------------------
IMAGE_LIB=gd


# --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME=snipeit_session
COOKIE_DOMAIN=null
SECURE_COOKIES=false


# --------------------------------------------
# OPTIONAL: CACHE SETTINGS
# --------------------------------------------
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync


# --------------------------------------------
# OPTIONAL: AWS S3 SETTINGS
# --------------------------------------------
AWS_SECRET=null
AWS_KEY=null
AWS_REGION=null
AWS_BUCKET=null


# --------------------------------------------
# OPTIONAL: MISC
# --------------------------------------------
APP_LOG=single
APP_LOCKED=false
FILESYSTEM_DISK=local
APP_TRUSTED_PROXIES=192.168.1.1,10.0.0.1
ALLOW_IFRAMING=false

**Comment by snipe** [comment]
Need debugging info, as explained on the Getting Help page.
