### ISSUE TITLE
Checkout Asset Upon Creation Requires Admin Permissions

### ISSUE THREAD

**Issue by elvisatthewheel** [snipe/snipe-it#2569]
#### Expected Behavior (or desired behavior if a feature request)

Login with credentials that do not have inherited Admin permissions, create new asset, select "Ready to Deploy" status label, user field appears, filter user in user field, and save changes.

Asset checked out to user upon creation.

---
#### Actual Behavior

Login with credentials that do not have inherited Admin permissions, create new asset, select "Ready to Deploy" status label, and user field does not appear to select user for checkout upon creation.

Currently must create asset then go back to asset and checkout to a user after creation.

---
#### Please confirm you have done the following before posting your bug report:
- [ X ] I have enabled debug mode
- [ X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running - **v3.2.0-53-gfff2bce**
- What OS and web server you're running Snipe-IT on - **Ubuntu 12 / Apache 2.4.23**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - **install.sh**
- If you're getting an error in your browser, include that error - **N/A**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - **Create Asset page / Ready to Deploy status label**
- If a stacktrace is provided in the error, include that too. - **N/A**
- Any errors that appear in your browser's error console. - **N/A**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). - **Unable to reproduce due to demo login using admin permissions.**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
  **[laravel.txt](https://github.com/snipe/snipe-it/files/457242/laravel.txt)**
- Include what you've done so far in the installation, and if you got any error messages along the way. - **Performed installation instructions using Snipe-IT documentation for install.sh method with no errors. Connect to LDAP and imported users using Snipe-IT GUI successfully. Imported assets via CSV from SCCM active machines report using Snipe-IT GUI successfully. Imported license keys via CSV using terminal tool method described in Snipe-IT documentation successfully.**
- Indicate whether or not you've manually edited any data directly in the database - **No**

**Comment by elvisatthewheel** [comment]
I know there are plenty of other issues superseding this, but just wanted to check in and see if there was any progress. Great product and thank you for all of your help!

**Comment by snipe** [comment]
No progress that this time. When there is, it will be posted to this ticket.
