### ISSUE TITLE
Error using remote database mysql

### ISSUE THREAD

**Issue by diktus** [snipe/snipe-it#2572]
I have migrate my server to use separate web server and database server. At the server i have configure mysql remote access for each user dan database. Also has testing with command to access database on the database server side. Another web app has been sucess migrate with change the database connection to the remote ip address mysql. But when i change the snipe-it configure it does not working.

What i have change it the database connection on .env dan the folder /conf/database.php. I try to use php artisan migrate but it show error that can not access mysql. I Have turn off the mysql service on web server to see it's really  connect to the new database server. 

Please help me with this migration

**Comment by snipe** [comment]
You should not be touching anything within the config directory for any reason. The .env file handles all of those configuration settings now. 

Also, you'll need to turn on debugging and tell me what "not working" means.

**Comment by diktus** [comment]
I have found the problem. The file configuration is not the .env and folder /config but in the /bootstrap/cache/config. Also it solve my URL problem on company logo

it ok to use this folder? if it is not common practise, how to move the config to .env?

**Comment by snipe** [comment]
> it ok to use this folder? if it is not common practise, how to move the config to .env?

I don't understand your question. You should not be touching ANYTHING within the config directory. 

The config IS the .env. As I mentioned in the other thread you opened, you have to clear your env cache when you make changes to the env file. https://snipe-it.readme.io/docs/common-issues#changes-to-my-env-file-dont-seem-to-be-updating

**Comment by diktus** [comment]
Ok, thank you for the information. I will try to remove the cache and configure the new one
