### ISSUE TITLE
Update 3.3.0 -> 3.4.0

### ISSUE THREAD

**Issue by DanielNemanic** [snipe/snipe-it#2574]
If I run "php artisan migrate" I receive the following error:

  [Doctrine\DBAL\DBALException]
  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.

**Comment by Dextro** [comment]
I have the same issue at the moment with an upgrade from 2.1.0 to 3.4.0. No solution so far.

**Comment by dmeltzer** [comment]
There was a fix made after v3.4 was released for this.

You can either switch to the master git branch, or replace `database/migrations/2016_08_30_084634_make_purchase_cost_nullable.php` with the following:

https://raw.githubusercontent.com/snipe/snipe-it/master/database/migrations/2016_08_30_084634_make_purchase_cost_nullable.php

or wait for snipe to release a version with the fix.

**Comment by dmeltzer** [comment]
Diff here:

https://github.com/snipe/snipe-it/commit/0a506120b772649b98f92389cc36c9eb33f885b8#diff-dd0075cafee17757e59897673407ac65

**Comment by Dextro** [comment]
Thx @dmeltzer

**Comment by gdeflaux** [comment]
Hi, I am using the docker container. Can I just replace the container?

Thanks
