### ISSUE TITLE
Purge keyword is wrong in german language

### ISSUE THREAD

**Issue by lostdesign** [snipe/snipe-it#2575]
#### Problem

If you want to purge all items on the administrator page, it tells you to enter 'Löschen'. @mmcleod82 told me that DELETE in caps would be working in the english version. After trying that, i was able to purge deleted items (language still set to german). 

So either change '... enter Löschen...' to '... enter DELETE...' or enable 'Löschen/LÖSCHEN' in the german language as keyword. 

-----

#### Please provide answers to these questions before posting your bug report:

Language set to german
Snipe-IT Version	v3.3.0-16-ge52a0f6
PHP Version	5.5.9-1ubuntu4.19
Laravel Version	5.2.43
manuell installation + upgrade from v2

**Comment by snipe** [comment]
This has been fixed on develop and will be pushed into the next release.
