### ISSUE TITLE
The requested URL /assets/setup was not found on this server.

### ISSUE THREAD

**Issue by rburkholder2305** [snipe/snipe-it#2578]
#### Expected Behavior (or desired behavior if a feature request)

Going to http://webserver/assets begins pre-flight and installation.

-----

#### Actual Behavior

Receive 404: The requested URL /assets/setup was not found on this server.

-----

#### Please confirm you have done the following before posting your bug report:

- [no ] I have enabled debug mode
- [ yes] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: Latest cloned from Git.
- What OS and web server you're running Snipe-IT on: Ubuntu 16.04.1 / Apache 2.4.18
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual installation.
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Setup
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). It is not
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. 
- Include what you've done so far in the installation, and if you got any error messages along the way.
  1. Followed https://snipe-it.readme.io/docs/getting-started using GIT clone to /var/www/assets to install.
  2. Created a new alias /assets pointing to /var/www/assets/public.
  3. Added /var/www/assets/public directory to Apache and set the below directives:
            AllowOverride All
            Options Indexes Multiviews FollowSymlinks
            Order allow,deny
            Allow from all
   4. Added RewriteBase /assets to .htaccess in /public.

- Indicate whether or not you've manually edited any data directly in the database: No

**Comment by rburkholder2305** [comment]
This issue has been resolved.

**Comment by snipe** [comment]
What did you end up doing to solve it?

**Comment by rburkholder2305** [comment]
Setup rewrite but never enabled it in Apache. My bad.

**Comment by snipe** [comment]
Ah, yeah, that happens. Glad you got it sorted.
