### ISSUE TITLE
[Doctrine\DBAL\DBALException]   Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.

### ISSUE THREAD

**Issue by brianjking** [snipe/snipe-it#2580]
#### Expected Behavior (or desired behavior if a feature request)

Migration to succeed.

-----

#### Actual Behavior

````
[Doctrine\DBAL\DBALException]
  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.
````

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - **3.3.0 - Official release, attempting to update to 3.4.0 official release.**
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by brianjking** [comment]
@snipe Now that I look at your commits to master and it looks like perhaps you've fixed this, is this right? https://github.com/snipe/snipe-it/commit/0a506120b772649b98f92389cc36c9eb33f885b8

**Comment by snipe** [comment]
Should be fixed on develop

**Comment by brianjking** [comment]
@snipe How can I fix this? Do I need to `git checkout develop` and then run `php artisan migrate` and `php artisan config:clear`?

The prior two commands listed at the releases page ran successfully when checking out the v3.4 tag.

**Comment by snipe** [comment]
If you want to live dangerously and run the develop branch, sure :P Otherwise just add those two lines to the file (replicate the change you see in that commit.)

**Comment by brianjking** [comment]
Added those lines as per your suggestion and migrations ran successfully, thanks for confirming @snipe!

````
php artisan migrate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

Migrated: 2016_08_30_084634_make_purchase_cost_nullable
dockbiz@dockdogs.biz [~/www]# php artisan config:clear
Configuration cache cleared!
````

Confirmed version is now showing: `Version v3.4.0-9-g67315d8`

**Comment by leobg** [comment]
I am having this same problem while trying to upgrade from 2.1.1 to 3.4. Am I missing something?

**Comment by snipe** [comment]
I explained how to fix above.

**Comment by leobg** [comment]
Thanks - I used the patch and it is all good now, assuming 3.5 would have it once released?

**Comment by snipe** [comment]
That's correct. (And the fix is on the master branch already)

**Comment by brianjking** [comment]
@leobg Just to confirm what @snipe mentioned above I just upgraded to 3.5.0-beta2 successfully after applying this patch. I had to `git stash` the migration that the patch applied before I could checkout the v3.5.0-beta2 tag. After that I simply ran the `composer` commands listed for this release and everything ran successfully!

Thanks @snipe for all your hard work.
