### ISSUE TITLE
how to configure g-mail 

### ISSUE THREAD

**Issue by shahima** [snipe/snipe-it#2581]
#### Expected Behavior (or desired behavior if a feature request)
Hi snipe iam newly install snipe-it aplication can help me to g-mail configuretion on snipe-it

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
That's documented. https://snipe-it.readme.io/docs/configuration 

Cmd+f for gmail. 
https://snipe-it.readme.io/docs/configuration

**Comment by shahima** [comment]
can please tell me how super admin's we can create. for snipe-it

**Comment by snipe** [comment]
I don't understand what you're asking.

**Comment by hemwantrawat** [comment]
Hello,
I have installed snipe-it on my local server, my email feature is not working though i have done the configuration as per the document shared above. Please help.
