### ISSUE TITLE
[Feature Request] Parent-child structure in asset

### ISSUE THREAD

**Issue by croshine** [snipe/snipe-it#2583]
Hello!

In my opinion, **parent-child structure in asset** is very useful.

For example, a module of chassis-type-switch is neither a consumable nor a component.
It's just an asset like any other assets, but only has **dependency**.

At present, I can not recognize dependency between assets.
So unnecessary solution is needed such as using description field.

If there is parent-child structure in asset, this kind of problem can be solved.
User can find the child assets in full asset table or **child asset tab** in specific parent asset details.
This feature need a 'parent' field in asset table like location, you know.

It gonna be a very useful feature.

**Comment by paulhite** [comment]
Would also love to see this. We assign assets to *vehicles* and need to be able to search and see inventories for specific vehicles. We are creating vehicles as users for right now to make it easier, but then we can't have those vehicles "checked out" to specific users. A basic parent-child structure would work.
