### ISSUE TITLE
[FEATURE REQ] user tags

### ISSUE THREAD

**Issue by paprika27** [snipe/snipe-it#2587]
#### Expected Behavior (or desired behavior if a feature request)

For a workshop where everyone needs to be handed a tablet at check-in, I'd like the hostess to scan the qr code next to a user's name, have the system recognize that this is not an asset, next scan the tablet qr code and have the system match both in a new checkout process. And for check-in, simply scan the assets one after the other.

---
#### Actual Behavior

Now, I can have her scan the asset, then type the user name on her smartphone to trigger a new checkout.

---

**Comment by snipe** [comment]
Thanks for the suggestion, @paprika27. An "audit" and/or "bulk action" mode for assets is currently planned, but that's using the 1D barcodes, not the QR codes. I'm not sure whether all QR apps would persist the kind of state that I think we'd need to execute that. As far as the browser is concerned, you're just loading two pages, one after another. If the QR code launches the user's profile page and there was a button like "Check in via QR" to tell the browser that the next URL it gets should be an asset URL and that asset should be checked out to the user that was previously loaded, that might work. My gut says this has the potential for weird behaviors in different QR code readers, but I'd need to play with a few to confirm.
