### ISSUE TITLE
Label Printing

### ISSUE THREAD

**Issue by aggieflash11** [snipe/snipe-it#2589]
I'm having a serious issue printing labels. The columns just aren't matching up properly. I've triple checked all of the setting correspond to the type of labels that I'm using (Avery 5160), but the labels are not lining up with the labels. I've attached a picture of what's going on, with the pencil lines indicating the left boundary of each label. I'm not sure if this is a bug in how the labels are being generated, or what's going on. 

I'm using version v3.3.0-16-ge52a0f6.

![fullsizerender](https://cloud.githubusercontent.com/assets/18000546/18395810/edcc4ddc-7685-11e6-9cc5-9af9f2befe66.jpg)

**Comment by jbstep** [comment]
Yeah, having same issue. Seems to be the same as #2555. Hope someone can get us a workaround.

**Comment by ch-gz** [comment]
@aggieflash11 Yes, I have the same issue. Hope someone can help us.

**Comment by snipe** [comment]
The image that was attached is broken - can you re-upload?

**Comment by aggieflash11** [comment]
![fullsizerender](https://cloud.githubusercontent.com/assets/18000546/18880353/35788716-849d-11e6-9252-f6bc9fe6e1a9.jpg)

Upload attempt #2

**Comment by snipe** [comment]
Can you show me your label settings in the Admin > Settings > Labels section?

**Comment by aggieflash11** [comment]
![screen shot 2016-09-27 at 1 55 01 pm](https://cloud.githubusercontent.com/assets/18000546/18887526/0d58f6f4-84ba-11e6-9eb7-6eca49082806.png)

Labels Section Settings

**Comment by victoriapak** [comment]
Try these settings in Google Chrome print dialog box
![image](https://cloud.githubusercontent.com/assets/20525448/18895653/13d79380-84d0-11e6-9bb8-98779038c163.png)

**Comment by aggieflash11** [comment]
Thanks for the suggestion, but that made things worse. The left column was shifted to the left 1/2", while the middle and right columns were not shifted at all. All row were also 5/16" higher up on the sheet, so now the labels are printed over the top boundary of the label, in addition to the previous left boundary for the middle and left columns. 

I'd post a picture, but I printed it on regular paper and laid it over my sheet of labels. I already blew through enough sheets initially testing that I'm loathe to print it on labels unless I have to.

**Comment by SylentBobNJ** [comment]
@aggieflash11 Excuse me if this is a silly question, but how did you determine the settings for your labels?  Did you have to measure them yourself or is this information provided for you somewhere (ie. Avery's website)?

I've had no luck at all with the labels and have had to manually copy-paste them to PDFs and print multiple 'templates' to get them lined up properly with the label sheet we use and it is seriously aggravating!  Thank you for any help you can provide!

**Comment by Allenvh** [comment]
I did entered the labels dimensions in Snipe IT (I made them a little
smaller). Then in the printing config page (Chrome) remove all margins, set
up paper layout to landscape. That would do it

**Comment by aggieflash11** [comment]
@SylentBobNJ Initially, I used the label dimensions from the label packaging, but over the course of a week, and several boxes of labels, I experimented with the dimensions to try and get it to work, to no avail. At that point, I was sick enough of the project not to proceed with turning them into PDFs and printing them that way.

**Comment by fbe-it** [comment]
I am also having the same issue. Our labels are not lining up correctly within Snipe-IT. Has there been any progress on this issue?

Snipe-IT version	v3.4-14-g2a8ab06
PHP Version	5.6.27
Laravel Version	5.2.45

**Comment by nrasmus** [comment]
Subscribing:  I see this is a dup of https://github.com/snipe/snipe-it/issues/2555

**Comment by sau70networkadmin** [comment]
Take a look at #2555 now, there've been some helpful posts recently!

**Comment by twok** [comment]
Similar issues - tried out all options of borders in chrome.

used labels Herma 4222

First page looks decent enough (still the left/ right border are not equal)
2nd and any further page starts at the top of the page (top border missing)

27 labels per page
label size 2,5*1,6665
left/ right border 0,28386
top/ bottom border 0,59645
space between labels 0,1*0,001

current work-around - print as pdf - use pdf editor to adjust borders manually.

also it would be really nice to use metric dimensions for most of the rest of the world :-)
