### ISSUE TITLE
Page Not Displayed on IIS8 and Windows Server 2012

### ISSUE THREAD

**Issue by Mkazhuka** [snipe/snipe-it#2590]
Hi All,

I am getting the attached screen while trying to access the Snipe IT site from IIS server.

I followed the steps as mentioned the Snipe IT manual Guide.

I am using PHP V7.0 and IIS 8

Any and All Help is appreciated. 

Please see the screen shots below.
![error 2](https://cloud.githubusercontent.com/assets/11966188/18399489/433aa976-769f-11e6-9cda-113293b9ed45.png)
![error 1](https://cloud.githubusercontent.com/assets/11966188/18399490/433ad6c6-769f-11e6-8376-625bf2aa0486.png)
![error 3](https://cloud.githubusercontent.com/assets/11966188/18399488/43397510-769f-11e6-814d-7ccd5f966882.png)

**Comment by ddreier** [comment]
In URL Rewrite there is a rule that redirects all requests to HTTPS. That rule needs to be disabled if you don't want the redirect to happen.

**Comment by Mkazhuka** [comment]
I deleted the rule that redirects HTTP to HTTPS, Restarted the website and the server however the problem still remains.

![error 5](https://cloud.githubusercontent.com/assets/11966188/18401278/c4a76e6a-76a7-11e6-99a4-0cb8034182ce.png)

**Comment by ddreier** [comment]
Clear your cache in IE, or try a different browser. They usually remember redirects.

**Comment by Mkazhuka** [comment]
Clearing Cache didnt work.

**Comment by ddreier** [comment]
Ok, what about trying a different browser or trying to access the site from a different computer? If it's still redirecting, you may have to slog through the Web.config file and make sure that there isn't anything in there that seems like it would be causing the redirect.

**Comment by Mkazhuka** [comment]
Ive tried to access the site both on my work laptop and the VM that the server is hosted on. I tried on both IE and Chrome.

**Comment by korio77** [comment]
Hi Mkazhuka, i have seen the pics and the .env file is a bit weird for me. the one i have its a bit different.

Check the app key, that "base64:" at the beggining seems like a wrong copy paste.

Also check the quotes, on my .env file i have almost everything quoted.

Im using the same setup than you, iis8 and windows server 2012.

I will attach an screen for you so you can check your .env file.

Also, give to us the log files of every part involved (lavarel, iis server, php, browser) so we can se where exactly its broken, my first shot is the .env file.
![image](https://cloud.githubusercontent.com/assets/20576635/18466268/4d42bf68-799b-11e6-86d1-4fad8f1d5428.png)

**Comment by Mkazhuka** [comment]
@korio77 , Thank you for the response, can you tell me the exact locations of the log files. Im not sure where they are.

**Comment by korio77** [comment]
i think the one we need to see is the log from php go to the php manager in your iis.
![image](https://cloud.githubusercontent.com/assets/20576635/18474647/5c94b098-79c3-11e6-8373-d0e20d0df38e.png)

And there you can see the error log, give us a pic.

![image](https://cloud.githubusercontent.com/assets/20576635/18474659/68c5f3e0-79c3-11e6-9fb0-240b590e8692.png)

**Comment by Mkazhuka** [comment]
@korio77 , The main error I see are

 [13-Sep-2016 09:05:40 America/New_York] PHP Warning:  require(C:\inetpub\wwwroot\snipe-it\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\inetpub\wwwroot\snipe-it\bootstrap\autoload.php on line 17
[13-Sep-2016 09:05:40 America/New_York] PHP Fatal error:  require(): Failed opening required 'C:\inetpub\wwwroot\snipe-it\bootstrap/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:\inetpub\wwwroot\snipe-it\bootstrap\autoload.php on line 17

I can upload the whole log file if you would like

**Comment by korio77** [comment]
Thats nice, now we know whats happening.

That error is related to composer, seems like your is not installed or something happened when you installed it.

Check the common issues page

https://snipe-it.readme.io/docs/common-issues

There you can find this error and how to solve it.

![image](https://cloud.githubusercontent.com/assets/20576635/18474899/9a6d6c92-79c4-11e6-9fe4-f93dd4463239.png)


Check it out and tell us when everything works again :D

**Comment by Mkazhuka** [comment]
@korio77 , I followed the guide, Downloaded the composer, Moved the .exe into the C:\inetpub\wwwroot\snipe-it folder and right click and installed. The help files you linked are broken and give me a 404 when trying to get to them.

**Comment by korio77** [comment]
I see.

Check this https://snipe-it.readme.io/docs/install-dependencies at the bottom, once you have done that keep following the documentation to finish the installation.

**Comment by Mkazhuka** [comment]
@korio77 I followed the directions, Please see attached pictures. 

![composer](https://cloud.githubusercontent.com/assets/11966188/18475291/dd73984e-7993-11e6-90b8-f6451c89eb13.png)
![composer2](https://cloud.githubusercontent.com/assets/11966188/18475292/dd75139a-7993-11e6-9601-72201079e9b5.png)

**Comment by korio77** [comment]
The documentation is a bit weird in some places because its made almost entirely for a "linux" enviroment, some things works different in windows.

Having that in mind, and as i can see in the pics, seems like you have composer properly installed, have you used the comand "composer install" in the cmd window before?

**Comment by Mkazhuka** [comment]
@korio77 This what what happens when I try to run composer install after navigating to c:\inetpub\wwwroot\snipe-it.

![composerinstallerror](https://cloud.githubusercontent.com/assets/11966188/18475535/c1659afc-7994-11e6-96d5-4b8c1fd025d1.png)

**Comment by korio77** [comment]
All you need to do is read, see that window, its telling you that you need to enable the php extensions of "curl" and "fileinfo", to do that go to your php manager in the iis server
![image](https://cloud.githubusercontent.com/assets/20576635/18475607/6349a778-79c7-11e6-93fd-771388266ce7.png)

And check if you have it like this
![image](https://cloud.githubusercontent.com/assets/20576635/18475613/708b92d4-79c7-11e6-9d32-1e925768f405.png)

Search the required extensions you dont have enabled in the disabled list, right click them and enable.

Once you finish, restart the iis server (i think restarting the Windows erver is not needed) and then run the comand again.

**Comment by Mkazhuka** [comment]
@korio77 , I have all of those enabled accept php_ldap.dll and php_pdo_sqlsrv.dll

Please see attached.

![php pluggins](https://cloud.githubusercontent.com/assets/11966188/18475848/040b2830-7996-11e6-9069-6fc944307f98.png)

**Comment by korio77** [comment]
Then there is something wrong with your php installation or config.

Check the php.ini file and look for the extensions if they are enabled there too, sometimes you can have multiple php.ini files so use a folder search and check all of them.

**Comment by Mkazhuka** [comment]
@korio77 , I think I found an issue, There were two php install directories here(root and program files). I changed it to the C:\PHP that composer was looking for and changed the IIS Server to look at that php-cgi and the composer was able to be installed.

**Comment by Mkazhuka** [comment]
I generated a new key, restarting the server.

**Comment by korio77** [comment]
Good news, keep going!

**Comment by Mkazhuka** [comment]
@korio77 , I restarted the server and now the errors im getting in the PHP Log are.

[13-Sep-2016 09:53:03 America/New_York] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "C:\inetpub\wwwroot\snipe-it\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php:13906
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13836): Monolog\Handler\StreamHandler->write(Array)
#1 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13596): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13694): Monolog\Logger->addRecord(400, Object(UnexpectedValueException), Array)
#3 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13389): Monolog\Logger->error(Object(UnexpectedValueException), Array)
#4 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13360): Illuminate\Log\Writer->writeLog('error', Object(UnexpectedValueException), Array)
#5 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Exceptions\Handler.php(57): Illumi in C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php on line 13906
[13-Sep-2016 09:53:03 America/New_York] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "C:\inetpub\wwwroot\snipe-it\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php:13906
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13836): Monolog\Handler\StreamHandler->write(Array)
#1 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13596): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13694): Monolog\Logger->addRecord(400, Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#3 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13389): Monolog\Logger->error(Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#4 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13360): Illuminate\Log\Writer->writeLog('error', Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#5 C:\inetpub\wwwroot\snipe-i in C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php on line 13906

**Comment by korio77** [comment]
![image](https://cloud.githubusercontent.com/assets/20576635/18476958/41d9be2a-79cc-11e6-87ae-d81c40fa421e.png)

**Comment by Mkazhuka** [comment]
Permissions were already set like that.

![snipeitpermissions](https://cloud.githubusercontent.com/assets/11966188/18477175/bedd8cb2-799a-11e6-9510-af9ba7c9f40f.png)

**Comment by korio77** [comment]
that error is related to the bootstrap folder permisions, i cant remember this one well (i had this problem a long time ago), but i have 2 iis users on is the one you have, the other one is this one

![image](https://cloud.githubusercontent.com/assets/20576635/18478254/d5f3ac7a-79d0-11e6-801d-74ec53077045.png)


try to check if you have this user too (change "esagprdwsus" with your server name).

In the end you need to grant permisions to the user the iis server is using , in the past i had to check our friend google for more info about that to see which one was the real user the iis server was using.

**Comment by ddreier** [comment]
Judging by `The stream or file "C:\inetpub\wwwroot\snipe-it\storage/logs/laravel.log" could not be opened`, it probably needs to be added to the docs that you need to assign the same permissions to C:\inetpub\wwwroot\snipe-it\storage.

**Comment by Mkazhuka** [comment]
@korio77 @ddreier , I added the permissions to C:\inetpub\wwwroot\snipe-it\storage. Now when I load the website im getting "Whoops, looks like something went wrong."

We're getting somewhere!

**Comment by korio77** [comment]
enable the debug mode in the .env file, restart the iis server and reload the page (deleting cookies) you should get some error logs there, and check the php log again to see if there is anything new!

**Comment by Mkazhuka** [comment]
Here is a screenshot of the debug mode On. There is nothing new in the PHP Log

![debug](https://cloud.githubusercontent.com/assets/11966188/18479141/e46616a0-79a1-11e6-84bd-aca07a57c65a.png)

**Comment by Mkazhuka** [comment]
@ddreier Working on it right now. I will let you know.

**Comment by korio77** [comment]
remember the single quotes ;)

**Comment by Mkazhuka** [comment]
@korio77 @ddreier , Thank you both. Looks like were working now.

![pre flight](https://cloud.githubusercontent.com/assets/11966188/18480669/82072282-79a7-11e6-961d-434b58c4412a.png)

**Comment by Mkazhuka** [comment]
Syntax error or access violation: 1142 CREATE command denied to user 'snipe_user'@'localhost' for table 'migrations'  From the Debug file.

**Comment by ddreier** [comment]
Did you give your Snipe-IT database user permissions to create tables? It's easiest just to give that user all privileges on that database.

**Comment by Mkazhuka** [comment]
@ddreier im having issues guiving the user permissions. "grant all on snipeit to 'snipe_user'@'localhost' identified by 'YOUR_DB_PASSWORD_HERE';" is giving me an error

**Comment by Mkazhuka** [comment]
I got it going Thank you both for all your help

**Comment by ddreier** [comment]
If you're 100% up and running, please close the Issue.

**Comment by irfan-mirza686** [comment]
Hey Everyone I read your discussion.  I had same problem 
require(C:\xampp\htdocs\gs1prod\storage\framework\views\3e36c40b862db769c1426aed7accad244ebf9c6b.php): failed to open stream: No such file or directory (View: C:\xampp\htdocs\gs1prod\resources\views\admin\providers\include\cr_activity.blade.php)
When I open multiple page at the same time I get this problem. sometimes "No such file or directory" sometimes "permissions denied"
