### ISSUE TITLE
Location list returns 0 assets, returns "No matching records found"

### ISSUE THREAD

**Issue by delinski111** [snipe/snipe-it#2592]
#### Expected Behavior (or desired behavior if a feature request)

When you are looking at a location, it would be expected to see all the assets in that location.

---
#### Actual Behavior

I have a location called "Woodbine", and in the main location list, it says "Assets = 7" "Assets assigned = 10". When I click on the location, I am brought to the page where it should list all of those assets, but instead the list is empty, and it returns the text "No matching records found"

---
#### Please confirm you have done the following before posting your bug report:
- [ x] I have enabled debug mode
- [ x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running <br />
  v3.3.0-3-g7ef4f23<br /><br />
- What OS and web server you're running Snipe-IT on<br />
  Ubuntu 14.04<br />
  PHP Version 5.5.9-1ubuntu4.19<br />
  Laravel Version 5.2.43<br /><br />
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)<br />
  install.sh<br /><br />
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).<br />
  Yes ; See following for reproduction details / specific scenario<br />
  User X does not have a location set (in demo I used USER: cgitadmin)<br />
  Asset Y has a default location set (in demo I used LOCATION: auerfort)<br />
  (ASSET: APA0106 was used for testing)<br /><br />

Admin panel > Locations > auerfort > 1 asset checked out is listed > click location > list is empty and returns same message as listed above in behavior text.

**Comment by dmeltzer** [comment]
https://github.com/snipe/snipe-it/blob/master/app/Models/Location.php#L55 is the culprit here, I think.

**Comment by delinski111** [comment]
I think this was due to not having locations set on the users.

We redid our workflow within SnipeIT to something totally different, and everything appears correctly now.
