### ISSUE TITLE
[Feature Request] Store column settings in database

### ISSUE THREAD

**Issue by githubuserx** [snipe/snipe-it#2602]
#### Expected Behavior (or desired behavior if a feature request)

An option where one could choose to store the column settings permanently in the database.

---
#### Actual Behavior

I noticed that currently column settings are stored in a cookie. But since I don't keep cookies any longer than the browser session, I have to set up the columns each time I log on.

I also read other poeple's complaints about cookie expiration times.
So maybe it would be best (in the long term) to store this information in the database.

---
#### Please confirm you have done the following before posting your bug report:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running

latest (dev)
- What OS and web server you're running Snipe-IT on

PhotonOS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

Docker
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
That's a pretty uncommon use-case, and column views would need to be stored for each list view.  I feel that cookies are still the best way to handle this.

**Comment by githubuserx** [comment]
I agree that cookies are a good way to store this, but I still think it would make sense to consider storing it in the database for a future release, since it offers possibilities cookies can't.
I also do understand that this might not be the easiest to implement since now it seems to be handled with "bootstrap-table" js library only.

But until this may change, I'd like to share a simple javascript bookmarklet I made as a workaround:

```javascript
javascript:(function(){document.cookie='assetTable-<VERSION>.bs.table.columns="checkbox","name","asset_tag","model","model_number","status_label","location","category","last_checkout","change","actions"]; max-age=60*60*24*365; domain=<DOMAIN>; path=/'})();
```

Instructions:
- replace `<VERSION>` with the correct Snipe-IT app version string. (see an already set cookie)
- replace `<DOMAIN>` with the domain where your system is hosted
- change any other value like table name and column names according to your needs

Create a new bookmark in your browser and paste the javascript string as URL. Depending on the browser it might be necessary to url-encode the whole string.
