### ISSUE TITLE
[Feature Request] Asset ID/Tag

### ISSUE THREAD

**Issue by githubuserx** [snipe/snipe-it#2603]
#### Expected Behavior (or desired behavior if a feature request)

It would be very nice to be able to choose between a numerical asset ID (like it is now)
or an unique, non case-sensitive, hash-like asset ID/tag.
e.g. http://hashids.org (there are also Laravel packages available)

---
#### Actual Behavior

Integer IDs are sufficient for most use cases but I recently came across a situation where it would be neat to have alphanumerical IDs.

Thank you for your time and effort! -
I really appreciate your work on this awesome asset management system!

---
#### Please confirm you have done the following before posting your bug report:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running

latest (dev)
- What OS and web server you're running Snipe-IT on

PhotonOS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

Docker
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
What's the actual use case here?

**Comment by githubuserx** [comment]
I can imagine a lot of situations where it could be useful, but my use case would be:

- With hash-like IDs I would be able to uniquely identify a larger number of assets (>1000) with a shorter length of the ID needed (since more permutations per digit, but depending on implementation of course)
- If I delete a large set of assets (having sequential IDs), it would create a gap in the sequence. If I'd repeat that over time, the ID's numerical values would be unecessary high if I don't manually correct them (which is time consuming and boring) (#2104 maybe they had a similar problem)
- Numerical IDs always have some kind of semantic meaning like a specific order or sequence, which I want to avoid to prevent false assumptions or questions from other people using the system
- I'm already able to show the internal database row ID which is sufficient for me 
if I want to identify records with a number
- By using not only digits but alphanumerical IDs (only lower- or uppercase letters), one can also better avoid transposed digits

An example including high numbers would be:

| integer ID | hash ID |
| -------- | ----- |
| 00001   | oed1 |
| 00002   | op31 |
| 00003   | o3k1 |
| ...           |          |
| 00895   | 8yxj   |
| ...           |          |
| 10000   | 6lm2 |
| 10001   | e909 |
| 13584   | v0r5 |

generated with hashids.org over a custom alphabet of lowercase letters and digits and a (minimum) length of 4 characters. Ideally this would give 36^4 (=1,679,616) possible combinations. By using hashids.org's algorithm it is reduced to about 14,000 combinations. But still, you need 5 digits in base 10, and only 4 characters when using the mentioned hash function.

The benefits of having such an option are very apparent to me and I figured it wouldn't be _that_ much work to implement.

**Comment by snipe** [comment]
Thanks for the explanation. Seems a little specific and a little paranoid to me. I'd probably merge a PR if someone created one, but it's low priority on the roadmap as far as I'm concerned. Definitely stuff that seems higher priority.
