### ISSUE TITLE
Version Question

### ISSUE THREAD

**Issue by arronrobles** [snipe/snipe-it#2604]
Hello,
Is there a work around to be able to use this product on:
cPanel Version	58.0 (build 27)
Apache Version	2.2.31
PHP Version	5.5.38
MySQL Version	5.6.31
Architecture	x86_64
Operating System	linux
Path to Sendmail	/usr/sbin/sendmail
Path to Perl	/usr/bin/perl
Perl Version	5.10.1
Kernel Version	2.6.32-673.8.1.lve1.4.3.1.el6.x86_64
-------------------------------------------------------

I know the support doc stats PHP >= 5.5.9. Also, any issues with the new composer 1.2.1 (2016-09-12). Has anyone come across any issues?

Thanks in advance,
Arron

**Comment by snipe** [comment]
Unfortunately, the PHP requirement is set by Laravel, not by us.
