### ISSUE TITLE
Error during Pre-Flight

### ISSUE THREAD

**Issue by whiteguts** [snipe/snipe-it#2606]
#### Expected Behavior (or desired behavior if a feature request)

Creating database tables

---
#### Please confirm you have done the following before posting your bug report:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running : 3.2.0
- What OS and web server you're running Snipe-IT on : Windows 7 32-bit, Wamp Server
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) : manual installation
- If you're getting an error in your browser, include that error : Check the attached documents
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error : Snipe IT Pre-Flight, click on the "Create Database Tables" button.
  ![capture1](https://cloud.githubusercontent.com/assets/22194995/18512324/881758a2-7a80-11e6-941e-c745c40808f9.PNG)
  ![capture](https://cloud.githubusercontent.com/assets/22194995/18512414/e73eb51e-7a80-11e6-8a41-1fe91612f215.PNG)
  ![capture2](https://cloud.githubusercontent.com/assets/22194995/18512417/ebabf22e-7a80-11e6-82a6-32eae065a9dd.PNG)

**Comment by dmeltzer** [comment]
Does App\Models\Actionlog.php exist?

**Comment by whiteguts** [comment]
Yes, it does. First thing I checked.

**Comment by whiteguts** [comment]
Any ideas, please ?

**Comment by Sam-R** [comment]
I'm not too sure about a windows setup, but the first thing I'd check are the permissions on the app/models folder and possibly the storage directory.

**Comment by whiteguts** [comment]
Already checked those, everything seems to be working fine. I even took ownership of the folders just to make sure, still the same issue.
