### ISSUE TITLE
Non-encrypted custom fields show as "Encrypted" on a non-admin user

### ISSUE THREAD

**Issue by MysticX0** [snipe/snipe-it#2607]
#### Expected Behavior (or desired behavior if a feature request)
A non-encrypted custom field values should be available for edition to a non-admin user.

-----

#### Actual Behavior
Currently, when creating a non-encrypted custom field, only admin users are able to edit their values (except for lists, which seem to be working correctly)

Values can be correctly seen in the asset list view or when viewing the asset details, but not when editing (field is grayed out and shows "ENCRYPTED").

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: **v3.4.0-9-g67315d8**
- What OS and web server you're running Snipe-IT on: **Ubuntu 14.04, Apache2**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): **Manual Installation**
- If you're getting an error in your browser, include that error: **N/A**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: **Asset editing page**
- If a stacktrace is provided in the error, include that too. **N/A**
- Any errors that appear in your browser's error console.**N/A**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). **Because of demo limitations (can't assign a user to a group), unable to reproduce.**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.**N/A**
- Include what you've done so far in the installation, and if you got any error messages along the way. **Fresh installation**
- Indicate whether or not you've manually edited any data directly in the database **No manual editing of data**

**Comment by snipe** [comment]
Fixed on develop, will be pushed out into the next release.
