### ISSUE TITLE
SnipeIT installation on ubuntu 14.04 using install.sh

### ISSUE THREAD

**Issue by pavan137049** [snipe/snipe-it#2610]
@snipe 
 
For past few days i trying to setup snipeit using install.sh on ubuntu 14.04 . But was unsuccessful to setup with backup and email features. 
Please help me setup snipe-it with step by step method as I am with limited knowledge on Linux and web server. 
I almost gave up on this , but the awesome features and UI makes me to keep trying .

**Comment by Sam-R** [comment]
Have your tried following the official installation documentation? I'm running through it myself now and it looks quite straight foward:
https://snipe-it.readme.io/docs/getting-started

**Comment by pavan137049** [comment]
@Sam-R 

Ya I have followed the installation document . On fresh installation of  Ubuntu 14.04 lts. I have followed these below steps . Please correct me if i am skipping some steps.

step 1:  wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh
            chmod 744 install.sh
            ./install.sh

step 2: FQDN:  snipeit.local
step 3: Manual set the snipeit database user password: XXXXXX
step 4 : Set root password :XXXXXXX
step 5 : Remove anonymous users? YES
step 6 : Disallow root login remotely? YES
step 7 : Remove test database and access to it : YES
step 8 : Reload privilege tables now: YES
step 9 : Please input your mysql/mariadb root password : XXXXXXX

Installation of composer was successsful
setting permissions on web directory.
restarting apache. 
**AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message.**
*** If you want the mail capabilities, edit /var/www/snipeit/ .env and edit based on .env.example****
****Open  http://snipeit.local to login to snipe-IT*****

when I try to login : i am not getting pre-flight page instead i get and error saying  "**Looks like something went wrong"**

**Comment by Sam-R** [comment]
That's Apache just complaining it doesn't know what the server name is, it's normally a warning and shouldn't affect accessing the site. Usually I ignore it, however you can optionally do as it suggests and set the ServerName directive in `/etc/apache2/apache2.conf` (I think). It should be as simple as `ServerName snipeit.local` or `ServerName localhost`.

What does the laravel log contain? You can find it in the installation directory `storage/logs/laravel.log`. From a terminal try cating it `cat storage/logs/laravel.log` and check the last stack trace (normally the useful part of the error is at the top).

**Comment by pavan137049** [comment]
I was able to get the pre-flight after setting the domain main in host file.
$ cat/etc/hosts
127.0.0.1  your domain name
(snipeit localhost)

$ cat/etc/hostname 
your.domain.com

and reload the server.
