### ISSUE TITLE
Getting this Error on new Snipe-IT install Need help

### ISSUE THREAD

**Issue by Krynn7** [snipe/snipe-it#2611]
![image](https://cloud.githubusercontent.com/assets/22204844/18530532/f6350cd4-7a9f-11e6-81e8-90004a7cb122.png)

Ive been following this [guide](http://olivermarshall.net/installing-snipe-it-asset-management-on-ubuntu/) since my knowledge of linux web-servers is limited... Please let me know what info you guys need from me to help me troubleshoot. Thanks! John

**Comment by Sam-R** [comment]
This page is, as it says, the default page which appears after installing Apache on Ubuntu for the first time. It's not pointing to your Snipe-IT installation. The problem likely lies in your /etc/apache2/sites-enabled/ directory. Providing the output of this command may help trouble shoot your existing setup further: `sudo ls -la /etc/apache/sites-enabled/`

I would suggest following the official docs if you can:
https://snipe-it.readme.io/docs/getting-started

Specifically this page may be of benefit to you:
https://snipe-it.readme.io/docs/linuxosx

**Comment by Krynn7** [comment]
![image](https://cloud.githubusercontent.com/assets/22204844/18599255/722b90c0-7c25-11e6-9aba-0b191034f0d1.png)

This is what i'm getting right now...

**Comment by Sam-R** [comment]
Well, since the server is loading the default site, you could try to disable it and see if snipit takes over:
`sudo a2dissite 000-default`
Restart the service to load the configuration changes
`sudo service apache2 restart`
check the site in the browser.

If there's still a problem, can you cat me the snipit.conf?
`cat /etc/apache2/sites-enabled/snipeit.conf`

**Comment by snipe** [comment]
Any luck here, @Krynn7?

**Comment by Krynn7** [comment]
Yes this resolved my issue. 
Now i am running into another problem where i cannot see Categories and Manufacturers that i have created, as i am trying to make new asset models

![image](https://cloud.githubusercontent.com/assets/22204844/18687895/1c7070e6-7f50-11e6-9be1-a87ea77f25ee.png)


![image](https://cloud.githubusercontent.com/assets/22204844/18687876/04e14946-7f50-11e6-80f4-c6fb6d0319f9.png)

Any theory's?

**Comment by delinski111** [comment]
It looks like, based on your screen shots, that you are in fact seeing everything you should. You have things like; Dock, Keyboard, Monitor... as accessories, so you need to be in the accessories screen and be adding accessories to see them. You will not be able to add an accessories as an asset unless you mark it as asset.
