### ISSUE TITLE
Copy License = Copy Assets

### ISSUE THREAD

**Issue by sdieste** [snipe/snipe-it#2612]
When im Try to copy a License, the button is named as "Copy Asset". If i click the button a error appears "Ops something went wrong". If i turn on debugging the message in the screenshot appears. Seems that some code is wrong

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

Snipe IT Version: v3.4.0-9-g67315d8
OS Version: Debian7
![snipe it error](https://cloud.githubusercontent.com/assets/22171736/18543263/36139db8-7b2f-11e6-8f56-3f6954b98cc2.JPG)
![snipe it license](https://cloud.githubusercontent.com/assets/22171736/18543264/36139b24-7b2f-11e6-81ba-1cdd192a7cee.png)

**Comment by snipe** [comment]
Duplicate of #2598
