### ISSUE TITLE
Feature Request / Check

### ISSUE THREAD

**Issue by stf675** [snipe/snipe-it#2613]
Microsoft has a number of products, that allow you to install multiple virtual machines per one physical machine license.

for example, 

MS Server 2012R2
**Datacenter**  unlimited virtual Operating System Environments (CPU+CAL license)
**Standard** two  virtual Operating System Environments (CPU+CAL license)

Server 2008/2008R2 has similar setup but slightly different allowances per edition.

So it would be very useful for proper license allocation to be able somehow allocate qty1 license to multiple assets, and be able to properly account for it for reporting and audit purposes.

**Comment by avary69** [comment]
From a license perspective you have to assign the license to the host and not to the individual VMs. So checking it out to that 1 host is enough. 
Why would you want to assign license to the VMs? VMs can move to different hosts (for example to a host that has a Datacenter license assigned). If you'd assign the license to the VM it potentially could "bring" a Standard license to the host with a Datacenter license. Doesn't that create more confusion than it clarifies?
