### ISSUE TITLE
Error Importing asset.CSV file.

### ISSUE THREAD

**Issue by pavan137049** [snipe/snipe-it#2617]
@snipe 

Not able to Import  Asset/Accessories/consumables CSV files.
Sample asset .csv file downloaded from the below link 
https://snipeitapp.com/assets/downloads/snipe-sample-assets.csv

![image](https://cloud.githubusercontent.com/assets/21337490/18581127/cee5d87e-7c1c-11e6-8a07-77e3046324e6.png)

![image](https://cloud.githubusercontent.com/assets/21337490/18581158/e8eb32b4-7c1c-11e6-9106-f243b182c774.png)

![image](https://cloud.githubusercontent.com/assets/21337490/18581179/04c6dce0-7c1d-11e6-8d69-7a26c16561ef.png)

**Comment by snipe** [comment]
Please provide debugging info, as request in the getting help documentation and the GH template you deleted before posting this.

**Comment by pavan137049** [comment]
Hi ,
I was able to import the file  successfully ,It was the issue with CSV file .
Thank you for response.  
 
As  i am using for the first time  how do i get the debugging info...

**Comment by dmeltzer** [comment]
https://snipe-it.readme.io/docs/getting-help has information on how to enable debug mode.

**Comment by linglongtong** [comment]
I got the same error, the system is always processing, but no data was imported.
In the interface, i couldn't see any errors, so no debugging info showed.

**Comment by snipe** [comment]
Please. Heck the documentation to see how to find debugging output

**Comment by snipe** [comment]
*check
