### ISSUE TITLE
Unable to import assets CSV (Via web gui or command line)

### ISSUE THREAD

**Issue by TheGreatGene** [snipe/snipe-it#2619]
**Error when importing via web gui:** Whoops, looks like something went wrong

**Error when importing from the command line:**  [Symfony\Componet\Debug\Exception\FatalThrowableError] Call to undefined function ForceUTF8\utf8_decode()
-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

**- Version of Snipe-IT you're running:** v3.4.0-9-g67315d8
**- What OS and web server you're running Snipe-IT on:** Ubuntu 16.04.1 LTS
**- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc):** install.sh
**- If you're getting an error in your browser, include that error:**
 FatalThrowableError in Encoding.php line 339:
Call to undefined function ForceUTF8\utf8_decode()
**Full error attached below**
**- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error?:** CSV Import
- If a stacktrace is provided in the error, include that too.
[importer.txt](https://github.com/snipe/snipe-it/files/477221/importer.txt)
[laravel.txt](https://github.com/snipe/snipe-it/files/477220/laravel.txt)
[WebGui Import Debug Output.txt](https://github.com/snipe/snipe-it/files/477222/WebGui.Import.Debug.Output.txt)

**- Any errors that appear in your browser's error console.** See attachement
**- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).** Import is not supported via the demo
**- Include any additional information you can find in `app/storage/logs` and your webserver's logs.** Attached below
**- Include what you've done so far in the installation, and if you got any error messages along the way.** Created asset models, accessories, and custom statues. Imported users via CSV
**- Indicate whether or not you've manually edited any data directly in the database** I have not

**Comment by pavan137049** [comment]
Make sure the file which you are importing in saved as  CSV file before importing . Even I faced the similar issue .

**Comment by TheGreatGene** [comment]
The file I'm using is a CSV. I used this site(http://csvlint.io/) to validate my CSV after the import didn't work.

**Comment by dmeltzer** [comment]
You need to rerun `composer install --no-dev --prefer-source` after ever snipe-it update, you are missing a dependency.

**Comment by TheGreatGene** [comment]
Reran composer install, rebooted, still getting the same error.

**Comment by snipe** [comment]
@TheGreatGene in your composer.json, do you see:

`"neitanod/forceutf8": "dev-master"`

?

**Comment by TheGreatGene** [comment]
Yes. Line 26

**Comment by snipe** [comment]
In your `vendor` directory, do you see a directory called `neitanod`?

**Comment by TheGreatGene** [comment]
Yes.

**Comment by dmeltzer** [comment]
Does a composer dump-autoload do anything for you?

**Comment by TheGreatGene** [comment]
@dmeltzer 

No still getting the same result.

**Comment by TheGreatGene** [comment]
Reinstalled on Ubuntu 14.04 instead of 16.04 and import works fine.

**Comment by dmeltzer** [comment]
For future reference: It appears it's a php7/16.04 issue.  You need to install php-xml (And the install script should depend on it).

**Comment by sydit** [comment]
sudo apt-get install php7.0-xml
