### ISSUE TITLE
url on qr code

### ISSUE THREAD

**Issue by donnieda** [snipe/snipe-it#2627]
Hi,

QR codes gives me quick links to assets with IP address in URL instead of fqdn. I've noticed that this happens if I log in to web interface typing IP address and create an asset. 

Since all of our assets have been created this way I was wondering if is there a way to change this information to FQDN?

Thanks.

Snipe-it version: v3.4.0-9-g67315d8

**Comment by snipe** [comment]
If your `APP_URL` in your `.env` file is a FQDN, the only possibility I can thin of is that when the labels were printed, the `APP_URL` was an IP address. Snipe-IT has no knowledge (or care) about your IP address unless you tell it to use that as your APP_URL.
