### ISSUE TITLE
snipeit.sh on latest CentOS 7 spits out an error (but still works!)

### ISSUE THREAD

**Issue by uberbrady** [snipe/snipe-it#2630]
#### Expected Behavior (or desired behavior if a feature request)

`install.sh` should not throw errors on install.

---
#### Actual Behavior

While installing the database, I get the following message:
#### Please confirm you have done the following before posting your bug report:
- [ n/a ] I have enabled debug mode
- [  n/a ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running
  Latest from HEAD (3.4.0?)
- What OS and web server you're running Snipe-IT on
  Centos 7.7 (1511)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  install.sh (which invokes snipeit.sh)
- If you're getting an error in your browser, include that error
  n/a
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
  install
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by tiagom62** [comment]
The error was fixed in MariaDB-10.0.15. Doesn't look like it was backported into 5.5.x

https://mariadb.atlassian.net/browse/MDEV-4399
