### ISSUE TITLE
Feature Request - images for asset

### ISSUE THREAD

**Issue by ozanam** [snipe/snipe-it#2632]
#### Expected Behavior (or desired behavior if a feature request)

To be able to select an image from public/uploads/images folder for an asset that has already had its picture uploaded. 

also would be sweet to be able to bulk assign an image to an Asset Models and automatically add this image to all new assets added to that asset model. 
-----

#### Actual Behavior

Unless done through an import the asset needs to be re-uploaded for each asset.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Interesting idea, but why. It just use the asset models image and not asset images? If an asset has no asset image but does have an asset model image, the asset model image is displayed by default.

**Comment by ozanam** [comment]
ahh yes

thats basically what I was looking for and that makes sense.. ignore this so 

![image](https://cloud.githubusercontent.com/assets/19982702/18639310/49f8c6be-7e8b-11e6-9a44-cdacce919ea2.png)
