### ISSUE TITLE
Possible to increase size of QR code on labels?

### ISSUE THREAD

**Issue by mikegfried** [snipe/snipe-it#2634]
When I print labels the QR code is too small to be read by a scanner (all QR phone apps cant see the code because it is so small)  I adjusted the label size (I am using 3" x 1" labels see picture below

---
#### Please confirm you have done the following before posting your bug report:
- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:

Snipe-IT version    v3.3.0-16-ge52a0f6
PHP Version 7.0.9
Laravel Version 5.2.43
- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  manual
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
  nonw
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
  I have spent a lot of time adjusting the size setting but cannot get the QR code to be larger
- Indicate whether or not you've manually edited any data directly in the database
  no

**Comment by acerspyro** [comment]
I don't believe this should be closed as it is still a valid feature request.
