### ISSUE TITLE
Enforce Unique Serial Number on Assets

### ISSUE THREAD

**Issue by rmavery** [snipe/snipe-it#2636]
#### Expected Behavior (or desired behavior if a feature request)

`Note: upgraded db from 2.1, so this may be specific to upgrade` 

When someone attempts to add an asset with the same serial number as an existing (even previously deleted asset) it should alert that the serial number is a duplicate or at least prevent it from being added a second time. 

---
#### Actual Behavior

We are able to enter an asset multiple times with the same serial number.  If you enter an asset and then delete it and then re-create it it will add another row to the assets table with the same serial and then present both of the assets in the UI.    

It appears that deleting an asset changes the 'id' field of the asset table to 0.   Then if you create that same asset it will create another entry.   Then when you search (lookup by asset tag will only return one, but regular search will return all of them) 

---
#### Please confirm you have done the following before posting your bug report:
- [x ] I have enabled debug mode  (`it doesn't generate any errors`)
- [x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running
  `v3.4.0-9-g67315d8`
- What OS and web server you're running Snipe-IT on
  `Ubuntu 16.04 LTS Server`
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  `Install from GitHub`
- If you're getting an error in your browser, include that error
  `No Error`
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
  `/hardware`
- If a stacktrace is provided in the error, include that too.
  `n/a`
- Any errors that appear in your browser's error console
  `no`.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
  `I added asset serial D0M00RIGAT0 3 times to the demo site`
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
  `Nothing of relevance`
- Include what you've done so far in the installation, and if you got any error messages along the way.
  `I tried to follow the upgrade steps from the web site.  Some errors, but I don't remember what they were.  I worked through them, but I don't think they are related`
- Indicate whether or not you've manually edited any data directly in the database
  `No`

**Comment by snipe** [comment]
> It appears that deleting an asset changes the 'id' field of the asset table to 0. 

I'm sorry, what?

Deleting an asset simply gives it a date value for `deleted_at`.

**Comment by snipe** [comment]
Changing the ID to 0 would mean you could only ever delete one asset, ever, since IDs are unique and auto-incremented.

**Comment by rmavery** [comment]
I thought it was odd too, but I did a query of the assets table 'SELECT * FROM `assets` WHERE 1 ORDER by created_at desc.   The last 6 entries had an 'id' of 0, and were 3 instances of two different assets.   Of these, two had 'deleted_at' dates which were not null, 2 were status_id = 5 and 2 were status_id = 1.      


![snipe-it-screenshot](https://cloud.githubusercontent.com/assets/622430/18918951/ffcbc446-8561-11e6-8af2-bdf22ea9c7af.png)
