### ISSUE TITLE
NTLMAuthenticator Error.

### ISSUE THREAD

**Issue by Mkazhuka** [snipe/snipe-it#2637]
#### Expected Behavior (or desired behavior if a feature request)

To Send Email from Snipe-IT. When I click on forgot password and enter my password it doesnt sent email. Debug mode gives NTLMAuthenticator.php line 299:

Not sure if my username should be 'domain\username'

-----

#### Actual Behavior

When I go to reset my password via email it tells me ErrorException in NTLMAuthenticator.php line 299:

-----

#### Please confirm you have done the following before posting your bug report:

- [ X ] I have enabled debug mode
- [ X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v3.4.0-9-g67315d8
- What OS and web server you're running Snipe-IT on - Windows Server 2012 with IIS 8
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Windows Installing Wiki
- If you're getting an error in your browser, include that error - NTLMAuthenticator.php line 299:
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - When tryin to reset Password via Email

![email error snipe](https://cloud.githubusercontent.com/assets/11966188/18642515/eac0c56e-7e6e-11e6-89cc-8b79427e3d39.png)

![email error](https://cloud.githubusercontent.com/assets/11966188/18642552/0fd3e750-7e6f-11e6-84c6-40b4720a126b.png)

**Comment by snipe** [comment]
Not sure - have you tried using your email address as your login? Looks like the code from that section of that library is:

```
protected function getDomainAndUsername($name)
    {
        if (strpos($name, '\\') !== false) {
            return explode('\\', $name);
        }

        list($user, $domain) = explode('@', $name);

        return array($domain, $user);
    }
```

This line is line 299:

```
list($user, $domain) = explode('@', $name);
```

**Comment by Mkazhuka** [comment]
@snipe , I did try using my username@domain.org as my login, It didn't work.

![new error](https://cloud.githubusercontent.com/assets/11966188/18671958/17c8824a-7f14-11e6-9351-da0d40e67070.png)

**Comment by snipe** [comment]
Is this a Google Apps domain by any chance?

**Comment by Mkazhuka** [comment]
@snipe , No this is my windows domain at work.

**Comment by snipe** [comment]
I'm honestly not sure then. I've not seen that particular error before. Can you try using `mail` as your mail driver?

**Comment by Mkazhuka** [comment]
@snipe , Changing it to mail for the driver actually gave me the sent message however nothing has came to my email. 

![Uploading Mail Driver.png…]()

**Comment by snipe** [comment]
I assume you checked your SPAM folder, etc?

**Comment by Mkazhuka** [comment]
@snipe Yes I checked spam and also I checked out exchange server and no mail ever went out.

**Comment by Mkazhuka** [comment]
@snipe , We got it figured out. We left the username and password as null and it sent out.

**Comment by snipe** [comment]
Glad you got it sorted!

**Comment by JONDERITU** [comment]
Hello @Mkazhuka could you have been able to use ldap authentication?
