### ISSUE TITLE
EOL column shows purchase date.

### ISSUE THREAD

**Issue by pavan137049** [snipe/snipe-it#2640]
#### Expected Behavior (or desired behavior if a feature request)

(EOL column should show the Expire date)

-----

#### Actual Behavior

(EOL column shows same as purchase date)

-----

#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT :  v3.4.0-9-g67315d8
- What OS and web server you're running Snipe-IT on : Ubuntu 14.04
- What method you used to install Snipe-IT : install.sh

![image](https://cloud.githubusercontent.com/assets/21337490/18665744/4733f708-7f46-11e6-9928-ca11be6db9d9.png)

Please help...

**Comment by snipe** [comment]
We'll need a little more info than that. What is your EOL set to on the asset model?

**Comment by pavan137049** [comment]
EOL is 0 in asset models. But the warranty info when adding new asset should be able to calculate the EOL right ?

**Comment by snipe** [comment]
It uses the EOL info from the model to determine what the old_date should be, not warranty.

```
public function eol_date()
    {

        if (( $this->purchase_date ) && ( $this->model )) {
            $date = date_create($this->purchase_date);
            date_add($date, date_interval_create_from_date_string($this->model->eol . ' months'));
            return date_format($date, 'Y-m-d');
        }

    }
```

**Comment by pavan137049** [comment]
It Worked , thank you for the immediate response.

**Comment by Lingvei** [comment]
> It uses the EOL info from the model to determine what the old_date should be, not warranty.
> 
> ```
> public function eol_date()
>     {
> 
>         if (( $this->purchase_date ) && ( $this->model )) {
>             $date = date_create($this->purchase_date);
>             date_add($date, date_interval_create_from_date_string($this->model->eol . ' months'));
>             return date_format($date, 'Y-m-d');
>         }
> 
>     }
> ```

Hello snipe 
could you help share me which file and line suppose to add that's code to fix EOL 
thank you
