### ISSUE TITLE
Snipe-it crashes when .ENV file is edited and saved.

### ISSUE THREAD

**Issue by pavan137049** [snipe/snipe-it#2641]
@snipe 

Can you please guide me how to edit the .env file and save .

When i edit the .env.example file as suggested in https://snipe-it.readme.io/docs/configuration.
and use  (cp .env.example .env) command to copy the content of env.example file  to .env file  .

I am not able to login again to snipe-it.

**My .env file  before editing.**

```
ubuntu@asset:/var/www/snipeit$ cat .env
#Created By Snipe-it Installer
APP_TIMEZONE=Etc/UTC
DB_HOST=localhost
DB_DATABASE=snipeit
DB_USERNAME=snipeit
DB_PASSWORD=xxxxxxxxx
APP_URL=http://asset.num.com
APP_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

**My .env file after editing**

```
ubuntu@asset:/var/www/snipeit$ cat .env
# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxx
APP_URL=https://asset.num.com
APP_TIMEZONE='UTC'
APP_LOCALE=en


# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=snipeit
DB_USERNAME=snipeit
DB_PASSWORD=xxxxxxxxx
DB_PREFIX=null
DB_DUMP_PATH='/usr/bin'

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=snipeit.num
MAIL_PASSWORD=xxxxxxxxx
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=snipe.it@gmail.com
MAIL_FROM_NAME='Snipe-IT'


# --------------------------------------------
# REQUIRED: IMAGE LIBRARY
# This should be gd or imagick
# --------------------------------------------
IMAGE_LIB=gd


# --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME=snipeit_session
COOKIE_DOMAIN=null
SECURE_COOKIES=false


# --------------------------------------------
# OPTIONAL: CACHE SETTINGS
# --------------------------------------------
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync


# --------------------------------------------
# OPTIONAL: AWS S3 SETTINGS
# --------------------------------------------
AWS_SECRET=null
AWS_KEY=null
AWS_REGION=null
AWS_BUCKET=null


# --------------------------------------------
# OPTIONAL: MISC
# --------------------------------------------
APP_LOG=single
APP_LOCKED=false
FILESYSTEM_DISK=local
APP_TRUSTED_PROXIES=192.168.1.1,10.0.0.1
ALLOW_IFRAMING=false
```

**Comment by snipe** [comment]
Can you tell me what errors you're getting? "I'm not able to login" doesn't explain very much."

**Comment by pavan137049** [comment]
![image](https://cloud.githubusercontent.com/assets/21337490/18679915/27b34a1c-7f7f-11e6-80f1-dffc7fccddcf.png)

**Comment by snipe** [comment]
Please enable debug mode and tell me the specific message you're getting, per the Getting Help documentation. https://snipe-it.readme.io/docs/getting-help#step-1-enable-debug-mode

**Comment by pavan137049** [comment]
![image](https://cloud.githubusercontent.com/assets/21337490/18680303/c0f7146e-7f80-11e6-8b82-0b71ee1565f1.png)

**Comment by snipe** [comment]
Your login information to mysql is wrong.

**Comment by pavan137049** [comment]
But , i just entered the same info which was created by installer in .env  . As mentioned above

**Comment by snipe** [comment]
It is the only possible explanation. You must have missed something in transferring the DB credentials over. (I deleted them from your paste so that all of Github didn't see your DB password, because that wouldn't be good.)

**Comment by snipe** [comment]
The password that worked for the first .env should be the one that works for the new one. It's not encrypted, it's just whatever you would normally use to login to MySQL.

**Comment by pavan137049** [comment]
It worked finally ,Thank you.
I was looking to subscribe for hosted version for our company. Need to check if they can customize for us and does snipe-it support Single Sign On (SSO).

**Comment by snipe** [comment]
Hi @pavan137049 - Snipe-IT supports AD/LDAP login, but not SSO. Customizations would depend on what was being requested.
