### ISSUE TITLE
Problems with comum user view page

### ISSUE THREAD

**Issue by arthurhsm** [snipe/snipe-it#2643]
Hi, may i ask for help? haha
I dont know whats wrong

The problem is my comum user cant see all items located for his name, i mean, if you login Snipe-IT page as normal user you can see all items located, but in my case it show just assets, no licenses, no accessories.

---------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------

**## This is the view from normal user:**
![image](https://cloud.githubusercontent.com/assets/11196463/18685814/006facfe-7f50-11e6-8f22-8e9cd0bc8b01.png)
---------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------

**## He can see all assets check out for his name, but he cant see the licenses, accessories, History, and more.**
![image](https://cloud.githubusercontent.com/assets/11196463/18686159/526450b8-7f51-11e6-94fd-d528706dcb04.png)

---------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------

**## This is my view as admin:**
![image](https://cloud.githubusercontent.com/assets/11196463/18685887/4a874054-7f50-11e6-8a3d-42f82dc6642a.png)

---------------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------------

What can i do for fix it and show all itens for my comum users?
Thanks a lot, and i would like to congratulate for the tool because is F* good

Snipe-IT version	v3.4.0-9-g67315d8
PHP Version	7.0.8-0ubuntu0.16.04.2
Laravel Version	5.2.45

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Any errors that appear in your browser's error console.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by arthurhsm** [comment]
What OS and web server you're running Snipe-IT on
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"

What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Install.sh

Any errors that appear in your browser's error console.
The same problem in others browsers

Include any additional information you can find in app/storage/logs and your webserver's logs.

Include what you've done so far in the installation, and if you got any error messages along the way.
No logs about it

Indicate whether or not you've manually edited any data directly in the database
I edited the basic to work, and translate mensages for Slack on APP, like accessoriescontrolle.php ( 'value' => **'ACESSÓRIO**  <'.config('app.url').'/admin/accessories/'.$accessory->id.'/view'.'|'.$accessory->name.'> **alocado para** <'.config('app.url').'/admin/users/'.$user->id.'/view|'.$user->fullName().'> **por** <'.config('app.url').'/admin/users/'.$admin_user->id.'/view'.'|'.$admin_user->fullName().'>.' )

**Comment by snipe** [comment]
I strongly recommend against editing the controllers directly, unless you plan on contributing those changes back to the source code, otherwise any time you upgrade, you're going to have to re-do those changes. 

Additionally, we use translation files to handle translations for Snipe-IT. If some parts need to have their english strings places by translation placeholders and you don't know how to do that and submit a PR, you can open an issue (a separate one) to ask that those strings get switched into translations. 

> Any errors that appear in your browser's error console.

We're asking specifically for errors that show up in your browser's console. If there are any, we need to know what they are.
https://snipe-it.readme.io/docs/getting-help#step-2-enable-your-browsers-error-console

> No logs about it

Do you have debugging turned on?

**Comment by arthurhsm** [comment]
I tested with a clear version (with out translations) and the same problem.
Return os my browser: (License DIV)
                 <div class="box-header with-border">
              <div class="box-heading">
                <h3 class="box-title"> Software Checked out to teste</h3>
              </div>
            </div>
          
        <div class="box-body">
          
          
          <div class="col-md-12">
              <div class="alert alert-info alert-block">
                  <i class="fa fa-info-circle"></i>
                  No Results.
              </div>
          </div>
                  </div>

It can't find the license by exemple, i mean if assets work well, maybe in somewhere in my php, this page search the info in other file,

**Comment by snipe** [comment]
You changing the controllers has nothing to do with the issue (most likely). I was just mentioning that you should avoid that to save you headaches down the line.

**Comment by arthurhsm** [comment]
I see, sorry, = P
Imade a test now, if i use my admin account, the page mydomain/account/view-assets show me all infos, including history, licenses, etc, is possible a probleme by permission?
![image](https://cloud.githubusercontent.com/assets/11196463/18688303/15b8d9aa-7f5a-11e6-8fec-8347e599f266.png)


Maybe just for normal users they cant see all infos, they can see just the assets infos, but i would like to comum user access their account and see what IT deployed for they.

It help you?

**Comment by snipe** [comment]
Do you have Full Company Support enabled?

**Comment by arthurhsm** [comment]
Yes

**Comment by snipe** [comment]
If you disable full company support, can your test user see their licenses, etc?

**Comment by arthurhsm** [comment]
Fuck, was it ¬¬ Thanks a lot, you are a monster!!!!!!!!!!!!

**Comment by arthurhsm** [comment]
![thanks you](https://cloud.githubusercontent.com/assets/11196463/18688438/d149553c-7f5a-11e6-9b1a-b6c3462077e1.gif)

**Comment by snipe** [comment]
![30-rock-highfiving-angels](https://cloud.githubusercontent.com/assets/197404/18688473/697ec944-7f39-11e6-87d8-1ab0f3764d48.gif)
