### ISSUE TITLE
LDAP auth doesn't work

### ISSUE THREAD

**Issue by palcica** [snipe/snipe-it#2648]
![snip_20160921074030](https://cloud.githubusercontent.com/assets/17080363/18699117/7295a480-7fcf-11e6-9662-f907c5e1940d.png)
![snip_20160921074700](https://cloud.githubusercontent.com/assets/17080363/18699152/9f7cd252-7fcf-11e6-8ecd-c8ec76b68943.png)

As you can see, settings are the same as they are on working examples. I've got users into database but logon into app doesn't work. Any idea?

**Comment by thwr** [comment]
Noticed that too. Can import users, but my users cannot auth against AD (Forest level 2008R2)

**Comment by jpurnhag** [comment]
Having the same problem here trying to connect to OpenLDAP.
![snipe-ldap-settings](https://cloud.githubusercontent.com/assets/18489633/18721190/5b3b2976-7ffd-11e6-8999-23c8b00d5500.png)

**Comment by palcica** [comment]
Any idea?

**Comment by snipe** [comment]
@palcica this is pretty much always an auth query issue. Try using `sAMAccountName=` as your auth query

**Comment by k-boy** [comment]
@snipe , i'm having same issue, users cannot authenticate, I have tried using sAMAccountName= also and no luck. Note: users are already imported from LDAP

**Comment by palcica** [comment]
nop, same problem.

**Comment by TheGreatGene** [comment]
I had a similar issue. My issue was caused by the Base bind setting. I have multiple locations so when importing users from AD I was updating the base bind field.

After I had all of my users imported I found that some could authenticate, but others couldn't. Updating the base bind to an OU one level up fixed the issue.

Ex.
OU=location1,OU=Employees,.........
OU=location2,OU=Employees,.........

After importing my users I updated the the base bind to OU=Employees,......... after that authentication started working for all my users.

**Comment by k-boy** [comment]
@TheGreatGene , i'm not really clear on what is required here, for example can you update how should this Base BIN  DN be updated? OU=all users,OU=ANA TEST,DC=HA,DC=ANA,DC=local

**Comment by TheGreatGene** [comment]
@k-boy 
Open AD, locate the OU, right-click select properties, click the Attribute Editor tab, Scroll down and select the distinguishedName  Attribute, click view.

**Comment by k-boy** [comment]
thank you, will post back, don't just understand why the same base settings work for a Drupal site and doesn't work for Snipe-IT

**Comment by k-boy** [comment]
@TheGreatGene, thank you, will post back, don't just understand why the same base settings work for a Drupal site and doesn't work for Snipe-IT

**Comment by palcica** [comment]
My still doesn't work.

**Comment by k-boy** [comment]
@TheGreatGene, thank you for your time, my problem was the Active Directory domain(example.com), it was empty for me and filling in the domain names works. At least i'm able to login now with my user credentials
