### ISSUE TITLE
Lost admin permissions after upgrading to version 3

### ISSUE THREAD

**Issue by norm-sasson** [snipe/snipe-it#2649]
#### Expected Behavior (or desired behavior if a feature request)

After I upgraded the snipeit all my old admin user lost the admin-settings (Top right corner). I created new admin user from a command line and the new user has all the right permissions. With that user I tried to fix the issue by changing one user to normal user and then back to admin. That didn't work. 

Also is there any settings in version 3 that disables the google-api. Our server is inside of secure network and it doesn't have access to internet.
#### Please confirm you have done the following before posting your bug report:
- [ X] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running 
  3.4
- What OS and web server you're running Snipe-IT on 
  centos 6.8
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  install.sh

**Comment by snipe** [comment]
Can you show me the permissions value for the user and any groups they are associated with?

**Comment by snipe** [comment]
Also, what version were you upgrading from? superadmin permissions haven't changed.

**Comment by dehemke** [comment]
I have a similar issue.  Our admin accounts are still admin, but it seems that some permissions were still unavailable.  

I updated the admin from permissions '{"admin":1,"reports":1} to 
update users set permissions = '{"admin":1,"user":1,"superuser":1,"reports":1}' WHERE id=1;

All good now.
