### ISSUE TITLE
The requested URL /setup was not found on this server.

### ISSUE THREAD

**Issue by josem1975** [snipe/snipe-it#2650]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)
Getting an error after installing 
Not Found

The requested URL /public/setup was not found on this server.

---
#### Actual Behavior

The requested URL /public/setup was not found on this server.
(what actually happens goes here)

---
#### Please confirm you have done the following before posting your bug report:

![error](https://cloud.githubusercontent.com/assets/22009000/18712975/00b690c6-8011-11e6-877d-4dfa43a38578.png)
- [ ] I have enabled debug mode - Yes
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html) Yes

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running - snipe-it-3.4
- What OS and web server you're running Snipe-IT on - Centos 6
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual installation
- If you're getting an error in your browser, include that error - yes
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - install
- If a stacktrace is provided in the error, include that too. - NA
- Any errors that appear in your browser's error console. -NA
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). -NA
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. _NA
- Include what you've done so far in the installation, and if you got any error messages along the way. - NA
- Indicate whether or not you've manually edited any data directly in the database-NA

**Comment by jasonbyatt** [comment]
Hi

I am having the same problem, feel like I'm so close to getting this finally installed. Please help!
