### ISSUE TITLE
Feature Request - Email notifications

### ISSUE THREAD

**Issue by giantsteps1** [snipe/snipe-it#2651]
#### Expected Behavior (or desired behavior if a feature request)

receiving email notifications when a user checks out and checks in.

---
#### Actual Behavior

User receives email notification when something is checked back in.  no email notifications happen when something is checked out.

---
#### Please confirm you have done the following before posting your bug report:
- [x ] I have enabled debug mode
- [ x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running
  v3.4.0-9-g67315d8
- What OS and web server you're running Snipe-IT on
  ubuntu server 14
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  install.sh
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
  i set up smtp in the .env file using google settings
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Are you sure you don't have that backwards? It definitely sends an email to the user when an asset is checked out (if you have that option selected).
