### ISSUE TITLE
Process to duplicate on another system

### ISSUE THREAD

**Issue by pnelsonsr** [snipe/snipe-it#2653]
How would you go about copying a working SnipeITv3 system to another system?  I started working at doing this and then thought maybe someone else has some advise.

**Comment by snipe** [comment]
Hi @pnelsonsr - the easiest thing to do is to run a backup (in Admin > Backups), grab a copy of your .env file (assuming you're running 3.0+), and then just copy all that stuff over.  You'll need to import the DB and move all of the files in the backup (uploaded files, specifically) to the new system but it shouldn't be a difficult task.
