### ISSUE TITLE
Import issue

### ISSUE THREAD

**Issue by githubuserx** [snipe/snipe-it#2654]
#### Expected Behavior (or desired behavior if a feature request)

Viewing the "Import" page.

-----

#### Actual Behavior

Error when loading the page. 
I used the default install with docker as decribed in the docs. My data folder is linked to an external volume. For some reason the folder "imports" in "private_uploads" is missing, hence the error as php tries to create the folder "assets" in it.
If I manually create the folders with the right permissions the problem is resolved.
Setting the recursive flag for `mkdir()` in `AssetsController.php#842` also removes the error message.

https://github.com/snipe/snipe-it/blob/master/app/Http/Controllers/AssetsController.php#L842

```php
if (!file_exists($path)) {
    mkdir($path, 0755, true);
}
```
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running

 v3.5-29-g6dc143d (develop)
- What OS and web server you're running Snipe-IT on

 PhotonOS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

 Docker
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
 `https://<hostname>/hardware/import`
- If a stacktrace is provided in the error, include that too.

 ```
in AssetsController.php line 843
at HandleExceptions->handleError('2', 'mkdir(): No such file or directory', '/var/www/html/app/Http/Controllers/AssetsController.php', '843', array('path' => '/var/www/html/storage/private_uploads/imports/assets', 'files' => array()))
at mkdir('/var/www/html/storage/private_uploads/imports/assets', '493') in AssetsController.php line 843
at AssetsController->getImportUpload()
at call_user_func_array(array(object(AssetsController), 'getImportUpload'), array()) in compiled.php line 9424
at Controller->callAction('getImportUpload', array()) in compiled.php line 9486
```
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).

 Not reproduceable.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

 No

**Comment by snipe** [comment]
There is already a PR for this. https://github.com/snipe/snipe-it/pull/2460
