### ISSUE TITLE
Convert existing local users to LDAP userspahb

### ISSUE THREAD

**Issue by asmartin** [snipe/snipe-it#2655]
#### Expected Behavior (or desired behavior if a feature request)

Local users are mapped to the LDAP user with the same name when LDAP is enabled

-----

#### Actual Behavior

I originally created my SnipeIT database before LDAP authentication was well-supported, thus I have hundreds of local user accounts. Now that LDAP auth works well, I'd like to switch over to using it, but I have thousands of assets checked out to the hundreds of local user accounts. If I enable LDAP auth, a duplicate account with the same username is created when that LDAP user logs in. Is it possible to allow for mapping LDAP authentications to a local user account with the same username (if it exists)?

**Comment by snipe** [comment]
Hi @asmartin - the LDAP sync definitely matches on username (in fact, I don't think the system will allow two users with the same username), so you shouldn't have duplicates. Check the LDAP or DB usernames for trailing spaces, it - anything that might make them different in a string to string comparison.

**Comment by asmartin** [comment]
Confirmed - I had set the usernames to the email address, so simply altering this in the database solved the problem and allowed LDAP users to be authenticated as expected. Thanks!
