### ISSUE TITLE
Creating new Asset Models issue.

### ISSUE THREAD

**Issue by Krynn7** [snipe/snipe-it#2656]
i am running into another problem where i cannot see Categories and Manufacturers that i have created, as i am trying to make new asset models

![image](https://cloud.githubusercontent.com/assets/22204844/18725151/1991f616-800d-11e6-8a30-f0ac791daa47.png)

![image](https://cloud.githubusercontent.com/assets/22204844/18725182/3743584e-800d-11e6-9a2a-d99f4f4884d5.png)

Any theory's?

They say they were created successfully but do not appear in the drop down box... Is there some way i fix this?

**Comment by dmeltzer** [comment]
The only categories for an asset model will be "asset" categories.  The category type of the categories you are not seeing is Accessory.
