### ISSUE TITLE
Question about LDAP and locations

### ISSUE THREAD

**Issue by korio77** [snipe/snipe-it#2665]
I'm gonna explain the situation.

We have a big AD with tons of child OU's segmented in "zones" like stores, QA, administration etc etc.

Currently in the LDAP import view it asks you for a "location" to import your users, right now i have one location for each "zone" in our business so we can keep track of them at first sight.

When i did the first import of the LDAP users i had to change the LDAP sync query for each zone and import it in small "steps" to be sure everything was well placed inside Snipe IT.

I was wondering if there is a way to just import the parent tree of LDAP so we can keep it updated easily, because right now each time we create a new user in the AD we need to modify the sync query and choose the correct "location" for it and then sync it.

Here is a sample pic of our AD so you can see what im talking about.

![image](https://cloud.githubusercontent.com/assets/20576635/18752550/0938c188-80e3-11e6-8e10-89223caad0e5.png)

And in the "location" menu of snipe IT we have this

![image](https://cloud.githubusercontent.com/assets/20576635/18752695/79441ae0-80e3-11e6-8111-51bb17596d8e.png)

This way we can keep track of the people and equipment currently in each department with just a couple mouse clicks but its a really pain to keep it sync with the AD.

Anyone has any suggestions to improve this or any ideas for a possible feature request to improve it?

Thanks!

**Comment by snipe** [comment]
We already have plans to associate an AD/LDAP query to each location - just haven't done it yet.

**Comment by korio77** [comment]
Those are good news, thanks Snipe!

**Comment by subramanyaHD** [comment]
even I had same question @korio77 and thanks @snipe for your update. It will be helpful for larger organisation which has multiple offices.

**Comment by schmidiij** [comment]
is this implement now?
