### ISSUE TITLE
Feature Request - Filter assets prior to export or running reports

### ISSUE THREAD

**Issue by ghost** [snipe/snipe-it#2671]
#### Expected Behavior (or desired behavior if a feature request)

When running asset reports, all assets are displayed

---
#### Actual Behavior

When running asset reports,  I can filter assets prior to export or running reports

---

Would like the ability to filter assets prior to export or running reports. This is the one feature preventing adoption of your product.
Thanks...

**Comment by Aaranaw** [comment]
We would also appreciate this feature.
