### ISSUE TITLE
Pre-Flight face Error 500

### ISSUE THREAD

**Issue by ruslanashaari** [snipe/snipe-it#2678]
Hello there. I've go through all the installation steps until the server configuration as I want to install the apps in subdirectory. I've changed my virtualhost file (/etc/apache2/sites-available/000-default.conf) and .htaccess (snipe-it/public/.htaccess).

After all the configuration, I faced with Error 500, right after I follow the tutorial on how to set up mod_rewrite as been provided in the Linux/OSX Configuration page (https://snipe-it.readme.io/docs/linuxosx). There is no error I encountered.

Where have I done wrong?

Details:
- Ubuntu 16.04, Apache
- Manual Installation
- Browser's error console: Failed to load resource: the server responded with a status of 500 (Internal Server Error)
- I have go through and complete all the installation steps and also for the server configuration. I try to install the apps in subdirectory as I also have other application in the server
- Before this, I face notice to change the DocumentRoot. i change my virtualhost file, and this error 500 appear
- my virtualhost file:

<VirtualHost *:80>
	ServerName 10.101.229.69
	

	ServerAdmin webmaster@localhost
	DocumentRoot /var/www/html/

	Alias /snipe-it "/var/www/html/snipe-it/public"
    	<Directory /var/www/html/snipe-it/public>
	Allow From All
    	AllowOverride All
    	Options +Indexes
	#DocumentRoot /var/www/html/snipe-it/public
    	</Directory>

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>

- My .htaccess file;

<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On
    RewriteBase /snipe-it

    # Uncomment these two lines to force SSL redirect
    # RewriteCond %{HTTPS} off
    # RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
</IfModule>

**Comment by snipe** [comment]
Please provide the contents of your error log and server logs

**Comment by ruslanashaari** [comment]
Oh I solved it. Looking into the error log, looks like I've permission issue for folder snipe-it/storage. so I try chmod -R 777, and it works now. Thanks so much
