### ISSUE TITLE
How to import User ID

### ISSUE THREAD

**Issue by diktus** [snipe/snipe-it#2679]
There is a feature to import asset but i don't see the that feature to import User ID. Is there any fast solution to import user ID?

**Comment by snipe** [comment]
Can you explain what you're looking to do exactly? Just import users? There is a CSV import and LDAP import.

**Comment by diktus** [comment]
i need just import user but i dont find the import menu. could you show me how the menu is? i use vesion 3.3

**Comment by snipe** [comment]
<img width="512" alt="current_users____snipe-it" src="https://cloud.githubusercontent.com/assets/197404/18863934/b325b6e8-8448-11e6-92b5-851953758427.png">
