### ISSUE TITLE
Installation on Cpanel shared hosting

### ISSUE THREAD

**Issue by skoneru** [snipe/snipe-it#2680]
Looking forward for documentation or steps to install on Cpanel or shared hosting. Also the documentation for windows and XAMPP installation seems old. Can you please point me to the right place for installation steps.

**Comment by brianjking** [comment]
@skoneru -- https://snipe-it.readme.io/docs/getting-started

**Comment by kalpeshboghara** [comment]
Any document for install/upgrade into Cpanel?

We need to fresh setup into cPanel with v6.0.12

**Comment by JosephNg07** [comment]
has this been figured out?
