### ISSUE TITLE
Using SQL Developer to access MySQL for SnipeIT

### ISSUE THREAD

**Issue by jmathias59** [snipe/snipe-it#2683]
#### Expected Behavior (or desired behavior if a feature request)

Connect on port 3306 to MySQL database

-----

#### Actual Behavior

Communication link failure

-----

Can I connect to the MySQL backend?  If so, what is the port number?

**Comment by mtucker6784** [comment]
Not sure how you installed it, but the default mysql ports aren't modified by SnipeIt.  You'll have to check your my.cnf to see what the port is so you can connect to the server, and verify that the account you're logging in as has remote connections allowed.

**Comment by tiagom62** [comment]
Also check firewall settings.

**Comment by jmathias59** [comment]
I read the same thing. Can't use do user and pass.  Needs grant all to another account.

Sent from Outlook Mobile<https://aka.ms/qtex0l>

________________________________

**Comment by jmathias59** [comment]
Turned off. Problem was with user acct not having rights

Sent from Outlook Mobile<https://aka.ms/qtex0l>

________________________________
