### ISSUE TITLE
iPad users - can you test?

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#2686]
Getting a report that the dashboard button in the sidenav doesn't work on iPad.

On PC - clicking on either the logo or the dashboard icon works.
On IPad – only clicking on the logo works.

Can anyone confirm?

**Comment by korio77** [comment]
Atleast for me it works.

Clicking on the dashboard logo or text(when the sidenav is not collapsed) works.

Im on an ipad air 2 with iOS 9.3.2

**Comment by snipe** [comment]
Thanks for testing! Can you confirm that it works in both landscape and portrait?

**Comment by korio77** [comment]
In landscape, the dashboard and the assets dont work, its like there is something over them and you cant click on them, logo or text doesnt matter, other options under them work great

**Comment by snipe** [comment]
Ah, thanks for the info!

![tenant-tyvm](https://cloud.githubusercontent.com/assets/197404/18869674/29822b96-8462-11e6-8613-fb63202339cb.gif)
