### ISSUE TITLE
Upgrade from 2.0

### ISSUE THREAD

**Issue by sysnoo** [snipe/snipe-it#2689]
Hi,
I am currently using version 2.0, can I upgrade directly to 3.5 when released?

Thanks

**Comment by brianjking** [comment]
@sysnoo -- https://snipe-it.readme.io/docs/upgrading

**Comment by lingpanda101** [comment]
I'm currently on Snipe-IT version v2.1.0-47-g39f40a3. Attempting to upgrade to v3.0. I initially installed using the installer script 'wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh'. What would be the proper step I take for Step 3 of the following link https://snipe-it.readme.io/docs/upgrading?  Thanks.

**Comment by sysnoo** [comment]
Thanks Brian for the link but my question was : is that procedure valid for 2.0 to 3.5?

**Comment by snipe** [comment]
Yes, but please follow the "Upgrading to 3.0" instructions just the same. Everything there will still apply.
