### ISSUE TITLE
DBALExeption error when migrate

### ISSUE THREAD

**Issue by diktus** [snipe/snipe-it#2690]
Hello,

i have migrate from version 3.3 to 3.4 from VPS to shared hosting. When i run php artisan migrate i got these error:

[Doctrine\DBAL\DBALExeception]
Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.

but i can login to snipeit. I dont found any error just curious what the error and how to fix that

**Comment by snipe** [comment]
Pull the latest from master - that's already been fixed.
