### ISSUE TITLE
Components not showing all Assets it is currently checked out

### ISSUE THREAD

**Issue by elJoeyJojo** [snipe/snipe-it#2691]
#### Expected Behavior (or desired behavior if a feature request)

I created a component called Video Cards (10 of them) and I checked them out to 10 computers but when I check the Video Card Component, i only see 1 of the 10 computers it is currently checked out to. I'd like to be able to see ALL the computers it is currently checked out to.

---
#### Actual Behavior

For some reason I only see 1 of those 10 PCs it is currently checked out to.  I can see that all 10 Video Cards are checked out but I can't see the other computers so there is no way to track them.

---
#### Please confirm you have done the following before posting your bug report:
- [ ] I have enabled debug mode YES
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html) YES

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running - v3.0.0-dev-3-g6d810a9
- What OS and web server you're running Snipe-IT on - CentOS 6.8
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - GIT
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Component
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. - I recreated the components and still same thing. It's odd that it only shows 1 computer out of the 10 which is mine : S
- Indicate whether or not you've manually edited any data directly in the database - No

**Comment by elJoeyJojo** [comment]
![image](https://cloud.githubusercontent.com/assets/17091968/18886710/d7d9a8de-84a5-11e6-8a57-0c53ce204712.png)

i can't see the other 2 PCs : S am I doing something wrong?

**Comment by snipe** [comment]
Is it possible the other two don't have a name? We may have changed the way that display since that version, and it may have just been calling for the name, instead of name/model/etc
