### ISSUE TITLE
Fresh install - apache default page -

### ISSUE THREAD

**Issue by thatrez** [snipe/snipe-it#2692]
#### Expected Behavior (or desired behavior if a feature request)
navigating to host displaying snipe-it website
(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)
navigating to host displays default apache page

checked /etc/apache2/snipeit.conf

seems correct. 

Installed on fresh ubuntu 16.04 from github and ran the included sh file
-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [ x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running latest git clone from repo
- What OS and web server you're running Snipe-IT on ubuntu 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) git clone
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
tried moving the /var/www/snipeit to /var/www/public, got error message about document root. 

 Indicate whether or not you've manually edited any data directly in the database
no

**Comment by therealjoshuad** [comment]
Did you run `a2ensite snipeit.conf`?

**Comment by fltchr** [comment]
I seem to be having the same issue...

I just spun up a DigitalOcean droplet and downloaded and ran just the install.sh and let it do it's thing. Upon completion, it tells me where I should be able to access the site, but I just get the default Apache page.

Output of a2ensite snipeit.com: `Site snipeit already enabled`

**Comment by therealjoshuad** [comment]
This probably isn't the best way, but if you remove the default config file, it loads the snipe page.

I'm not on my PC, but you can rename them file with this:

sudo mv /etc/apache2/sites-enabled/000-default.conf /etc/apache2/sites-enabled/000-default.conf.bak

**Comment by fltchr** [comment]
@therealjoshuad,
I just found an older thread with the same issue and someone recommended disabling the default site and restarting Apache. That seems to have done the trick as well.
