### ISSUE TITLE
https redirect

### ISSUE THREAD

**Issue by lmward** [snipe/snipe-it#2693]
It's been a while since I've dealt with Apache redirects so I may have missed something really stupid. Pretty much, we're trying to use SSL. Certs in place, https is working, for the most part, but some elements are still being called via http. This was discovered when our help desk was trying to do a file upload and nothing happened. I investigated and found that it was being blocked for calling via http instead of https.

I put a Redirect permanent / https://snipeit.domain.com/ into the snipeit.conf. At that time, I verified that going to http://snipeit.domain.com redirected to https://snipeit.domain.com That worked fine. However, it's still pulling http://snipeit.domain.com for elements.

The only snipe-it file I modified was app.php and changed http to https just so see if that did anything. I haven't had a lot of time to start poking around snipe-it and am not the primary user of the program for my company.

#### Expected Behavior (or desired behavior if a feature request)

All elements called via https due to redirect

-----

#### Actual Behavior

https redirect partially works. Several elements still being called via http causing issues.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running

	v3.3.0-16-ge52a0f6

- What OS and web server you're running Snipe-IT on

Ubuntu 16.04 & Apache

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

install.sh

- If you're getting an error in your browser, include that error

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

- Any errors that appear in your browser's error console.

jQuery-2.1.4.min.js:4 Mixed Content: The page at 'https://$address.domain.com/admin/users/12/view' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://$address.domain.com/api/users/12/upload'. This request has been blocked; the content must be served over HTTPS.send @ jQuery-2.1.4.min.js:4ajax @ jQuery-2.1.4.min.js:4send @ jquery.fileupload.js:906_onSend @ jquery.fileupload.js:968(anonymous function) @ jquery.ui.widget.js:126data.submit @ jquery.fileupload.js:674(anonymous function) @ jquery.fileupload.js:218j @ jQuery-2.1.4.min.js:2add @ jQuery-2.1.4.min.js:2add @ jquery.fileupload.js:217_trigger @ jquery.ui.widget.js:518(anonymous function) @ jquery.fileupload.js:1037each @ jQuery-2.1.4.min.js:2_onAdd @ jquery.fileupload.js:1030(anonymous function) @ jquery.ui.widget.js:126(anonymous function) @ jquery.fileupload.js:1229j @ jQuery-2.1.4.min.js:2add @ jQuery-2.1.4.min.js:2always @ jQuery-2.1.4.min.js:2_onChange @ jquery.fileupload.js:1219(anonymous function) @ jquery.ui.widget.js:126handlerProxy @ jquery.ui.widget.js:435dispatch @ jQuery-2.1.4.min.js:3r.handle @ jQuery-2.1.4.min.js:3
jQuery-2.1.4.min.js:4 XMLHttpRequest cannot load http://$address.domain.com/api/users/12/upload. Failed to start loading.

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).

No

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

Nothing in logs

- Include what you've done so far in the installation, and if you got any error messages along the way.

Added redirect permanent to VirtualHost. Confirmed that http://$address.domain.com -> https://$address.domain.com

- Indicate whether or not you've manually edited any data directly in the database
Nope

**Comment by snipe** [comment]
Can you tell me what your APP_URL is in your .env file?

**Comment by snipe** [comment]
(Also, can you try uncommenting the line in the htaccess that forces a redirect)

**Comment by lmward** [comment]
Okay. So, editing the .env was the issue. That was just a facepalm moment for me. I saw .env everywhere and was looking for a file that ended in .env, not realizing it was a dotfile. I've never messed with .env before so...I got a little lost on that. 

It seems to be all working now and gets rid of that error. Thank you, very much, for your help and keep up the tremendous work.

**Comment by snipe** [comment]
Awesome, glad it's sorted!
