### ISSUE TITLE
Scan Barcode to Check in/out

### ISSUE THREAD

**Issue by AsimPervez93** [snipe/snipe-it#2696]
Firstly, I know there are many barcode related threads already so I apologise if mine is repetitive, I don't feel that it is however.

So, I can currently generate barcodes/QR codes and that's excellent!  However, is there any chance of being able to scan the barcode to check the item out, and scan it again to check it back in?

I know that the item's URL is currently encoded to the barcode so scanning the code would take you to the URL, would it be possible to implement the above scenario?

Thanks for your awesome work and I look forward to hearing back from you.

**Comment by snipe** [comment]
Not currently, but its in the works.

**Comment by saadatahmed** [comment]
Has this feature been added to recent releases? It would have been nice to scan multiple devices at once, using a phone or barcode scanner for check in/out.

**Comment by cdewey17** [comment]
Has this feature been revisited? Is it a limitation of the PHP version or something?

**Comment by kekkers23** [comment]
Over 2 years, any updates on this?

**Comment by AsimAJ33** [comment]
Hi Snipe Team,

Just wondering if there's been any progress on this or if it's added to the roadmap for a future release?

**Comment by AsimAJ33** [comment]
Hi @snipe,

Noticed that my last post might have been missed since the issue is marked as closed.  Back in 2016 this was in progress, has there been any update on whether this use case functionality will be implemented or not? :)
