### ISSUE TITLE
Able to sync with LDAP, but ldap users are not able to authenticate

### ISSUE THREAD

**Issue by sainirahul** [snipe/snipe-it#2697]
Hi, I just installed Snipeit and Sync with my LDAP server. I have successfully synced with LDAP( Active Directory ) server and can list user. But when i try to login with any of the LDAP user I am getting the  Error: The username or password is incorrect. 
Please help. 
Please let me know in case any additional information required.

**Comment by jakobii** [comment]
I am also having this problem. ldap for active dirrectory is configured, i use the check ldap button and it give the green "it worked!" then i sync users from ldap successfully. when i try to log in with any of the users i get " Error: The username or password is incorrect."

**Comment by snipe** [comment]
LDAP sync and LDAP auth use two different settings. If your LDAP sync worked but your auth is failing, it's almost always the auth query that's wrong.

**Comment by orygen** [comment]
What's your LDAP Authentication query? I had to change to samaccountname= for it to work.

**Comment by sainirahul** [comment]
I Have tried both   "samaccountname"  and  "sAMAccountName" but no luck.

**Comment by howeluck** [comment]
Do you have the "=" on the end? I had this issue as well. Here's how I fixed it:

![capture](https://cloud.githubusercontent.com/assets/21362610/18967467/ec968a48-864a-11e6-9cb5-613f6da7bf2c.PNG)

**Comment by sainirahul** [comment]
Great It Works!  
Thanks a ton all of you.
