### ISSUE TITLE
License Import -  "There are no commands defined in the "license-import" namespace."

### ISSUE THREAD

**Issue by TheVakman** [snipe/snipe-it#2698]
#### Expected Behavior (or desired behavior if a feature request)

The licences in the .csv file to be imported into the database.

-----

#### Actual Behavior

As per the documentation, when I run the command (php artisan license-import:csv path/to/your/file.csv --domain=yourdomain.com --email_format=firstname.lastname) with my domain set, to import my licenses, it does not import and reports:
 [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "license-import" namespace.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running:
v3.3.0-3
- What OS and web server you're running Snipe-IT on:
CentOS 7 & Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc):
install.sh script.
- Include what you've done so far in the installation, and if you got any error messages along the way:
All has been working OK (assets importing, LDAP sync etc.) The license importing is the only thing causing issues so far. However, assets would not import via GUI but this is not a problem for us as the CLI importer works great.
- Indicate whether or not you've manually edited any data directly in the database:
No.

**Comment by snipe** [comment]
Sorry about that - The command is `snipeit:license-import`. Docs are updated now.
