### ISSUE TITLE
Whoops, looks like something went wrong. Accessorie Snipe-IT

### ISSUE THREAD

**Issue by heizung76** [snipe/snipe-it#2699]
I installed Snipe-IT today and everything is working well except Accessorie. If i click an Accessorie in the dashboard an empty page opens with the message "Whoops, looks like something went wrong.". Anyone knows how to fix that ?
Thanks and Greetings,
Luca

**Comment by delinski111** [comment]
I had the same issue just now and found the solution.

Navigate to the following file
sudo nano /var/www/snipe-it/app/Http/Controllers/AccessoriesController.php
On Line 95 (Control+C gets current cursor position in command line)
at the end of the line, there is an extra character 'P' in the line that should no be. Remove it, and accessories will work again.

**Comment by snipe** [comment]
Should be fixed now.
