### ISSUE TITLE
Import/Restore Server backup

### ISSUE THREAD

**Issue by delinski111** [snipe/snipe-it#2700]
#### Expected Behavior (or desired behavior if a feature request)

Import Backup into new snipe server via following command
php artisan db:restore /media/usb/snipeit.sql

#### Actual Behavior

[Symfony\Componant\Console\Exeption\CommandNotFoundException]
Command "db:restore" is not defined.

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
Snipe 3.4

- What OS and web server you're running Snipe-IT on
Ubuntu 14.04

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
git clone

-Additional Information
I have already exported the zip, extracted the snipeit.sql file, and imported it into a folder in my new server, which is sitting in /var/www/snipeit.sql

**Comment by snipe** [comment]
Where are you seeing documentation for db:restore?

**Comment by delinski111** [comment]
An old ticket. https://github.com/snipe/snipe-it/issues/1292

**Comment by snipe** [comment]
We don't use that backup library anymore, and the currently library doesn't have a restore command. Just import the SQL file manually.

**Comment by delinski111** [comment]
I could not find any .sql files in the directory, Where can i manually drop it?

**Comment by snipe** [comment]
I don't understand the question.

**Comment by delinski111** [comment]
lol, sorry was typing that out while on a support call.

I have the snipeit.sql.

Where do I place that file, or how do i get that file to be the actual Database?

**Comment by snipe** [comment]
Good times :)

You can use PHPMyAdmin if you have that set up already, otherwise mysqlimport via command line. 
http://dev.mysql.com/doc/refman/5.7/en/mysqlimport.html

**Comment by delinski111** [comment]
Ok, thank you. I was not sure if it was to be done via sql based system, or if snipe-it had a built in function., and now I know :D
