### ISSUE TITLE
Error Accessing 'Accessories'

### ISSUE THREAD

**Issue by rnovo-carecloud** [snipe/snipe-it#2704]
#### Expected Behavior (or desired behavior if a feature request)

The apps works just fine in every aspect, I am migrating from 2.1.0 to the latest master repo. Did follow up all steps, linked the app to an RDS, uploaded the .sql database run the db migration, and I have been testing and the app is 99% functional in all places but the 'Accessories'.

-----

#### Actual Behavior

- The application crash when accessing any link that takes you to accessories screen. 
besides that everything works fine. 

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version : v3.4-14-g2a8ab06

- What OS and web server: MACOSX EL CAPITAN

- What method you used to install Snipe-IT (install.sh)

- ERROR: The error it is just an : Whoops, looks like something went wrong.

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
  From any part of the application when executing any link that takes you to 'Accessories' fails. 

- If a stacktrace is provided in the error, include that too.
  Tailing the log 'laravel.log' found this --->

[2016-09-28 22:44:58] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'p' (T_STRING)' in /var/www/snipeit/app/Http/Controllers/AccessoriesController.php:95
Stack trace:
#0 {main}

- Any errors that appear in your browser's error console.
No errors appears in the console 
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
Not sure if possible at all, not sure if it is code problem or related to the db migration. 
 
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
No errors in apache, or in any other place, just the line added before every time you hit a link that takes you to the 'Accessories' screen.
- Include what you've done so far in the installation, and if you got any error messages along the way.

id follow up all steps, linked the app to an RDS, uploaded the .sql database run the db migration, and I have been testing and the app is 99% functional in all places but the 'Accessories'.

- Indicate whether or not you've manually edited any data directly in the database

No data was manually updated in the db, a clean *.sql import and db migration.

**Comment by snipe** [comment]
This is fixed on master and develop.

**Comment by rnovo-carecloud** [comment]
so it was fixed couple of hours ago ?, because I just clone from the master branch

**Comment by snipe** [comment]
https://github.com/snipe/snipe-it/commit/9ecb0e6ca1688b0f7ee7abc72010ed0370fb8f98
