### ISSUE TITLE
Page not found Error

### ISSUE THREAD

**Issue by maxcat88** [snipe/snipe-it#2706]
#### Expected Behavior (or desired behavior if a feature request)

Hi,
i have installed a fresh server with ubuntu server 14.04 (no LAMP)
After i read guide to install snipeit with install.sh, i have ansewered to all questions successfully
snipeit is in /var/www/snipeit/
![snipeit](https://cloud.githubusercontent.com/assets/22517044/18945729/1e0e1f24-862c-11e6-9edb-0ec56c094f2d.png)

(in /etc/apache2/sites-available/snipeit.conf (created automatically) there is a configuration of virtualhost)
I have activate site with a2ensite snipeit OK!

But error page not found 404 appears.
Please help me thanks!
-----

#### Actual Behavior

When i try to load http://ipserver/snipeit/ appears Error 404 Not found

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode NO
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)YES

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running The latest
- What OS and web server you're running Snipe-IT on Ubuntu server 14.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Install.sh
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/common-issues#the-requested-url-setup-was-not-found-on-this-serv
