### ISSUE TITLE
Installation issues - blank /setup page

### ISSUE THREAD

**Issue by Markt85** [snipe/snipe-it#2708]
I have tried to follow the installation guide for snipe it fully, and quite a few times but get nothing!!

-Downloading from GIT
-Creating a mysql database and the snipe user with permissions
(although i get a warning about GRANT becoming depreciated in future versions)
-Edit the .env file
- generate a key - which is loaded into my .env file
- change the windows file permissions as decribed in documentation
- set up assets.mydomain.com as described in documentation 
- I set up initially in a virtual directory but the followed suggestions to set up a site in IIS assets.mydomain.com and before installation I can see a test page successfully at that location publicly and privately, (both http & https - self signed both work for the test page - index.html)

-----

- I have debug mode on in the .env file but no log files are being created.
- I have read the common issues and documentation but cant see to install this application..

-----
- Snipe-IT version 3.4
- Running Snipe IT on Windows Server 2012 R2
- Installed from Git using bash direct to wwwroot\snipeit
- Im either getting a 500 error or other browsers eg. firefox just showing a blank page
- /setup page wont load directly during initial installation 
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Im not seeing and never have any logs in /storage/logs - which is weird...

I have read lots of the help topics on installation but nothing seems to get it working for me.

**Comment by Markt85** [comment]
Ive just sorted it, I had to add 'everyone' full control permission to snipe folder - not sure this is very safe tho?

**Comment by user-name-is-taken** [comment]
For anyone coming to this page late, setting `APP_ENV=production` to `APP_ENV=debug` can help you debug this issue.
