### ISSUE TITLE
Initial Config for httpd.conf

### ISSUE THREAD

**Issue by jasonbyatt** [snipe/snipe-it#2709]
#### Actual Behavior

The 172.26.0.25 page isn’t working
#### Please confirm you have done the following before posting your bug report:
- [X ] I have enabled debug mode
- [ X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---

I thought I would post here because I am currently doing this solo, this being my first ever linux experience I feel like I've done so well and I am so close so please help! I feel like I have done something wrong in the httpd.conf file everything has installed so far this is the last part.

**Comment by jasonbyatt** [comment]
`ServerName localhost

#
# Deny access to the entirety of your server's filesystem. You must
# explicitly permit access to web content directories in other
# <Directory> blocks below.
#
<Directory />
    AllowOverride All
    Require all denied
</Directory>

<VirtualHost localhost:80>
  <Directory /var/www/html/snipeit/public>
    Allow From All
    AllowOverride All
    Options +Indexes
  </Directory>

</VirtualHost>

#
# Note that from this point forward you must specifically allow
# particular features to be enabled - so if something's not working as
# you might expect, make sure that you have specifically enabled it
# below.
#

#
# DocumentRoot: The directory out of which you will serve your
# documents. By default, all requests are taken from this directory, but
# symbolic links and aliases may be used to point to other locations.
#
DocumentRoot "/var/www/html/snipeit/public"

#
# Relax access to content within /var/www.
#


<Directory "/var/www">
    AllowOverride All
    Require all granted
    Allow from All
    Order allow,deny
</Directory>

# Further relax access to the default document root:
<Directory "/var/www/html/snipeit/public">
    #
    # Possible values for the Options directive are "None", "All",
    # or any combination of:
    #   Indexes Includes FollowSymLinks SymLinksifOwnerMatch ExecCGI MultiViews
    #
    # Note that "MultiViews" must be named *explicitly* --- "Options All"
    # doesn't give it to you.
    #

`

**Comment by jasonbyatt** [comment]
[httpd.txt](https://github.com/snipe/snipe-it/files/500566/httpd.txt)

**Comment by langweiler2003** [comment]
If this is your whole httpd.conf than its corrupt
If you are using centos you can try this:
[httpd.txt](https://github.com/snipe/snipe-it/files/500655/httpd.txt)
than you have to put in /etc/httpd/conf.d this:
[snipeit.txt](https://github.com/snipe/snipe-it/files/500662/snipeit.txt)
rename it to snipeit.conf and restart your webserver afterwards

Regards

**Comment by jasonbyatt** [comment]
Still same error
It's redirecting me to http://172.26.0.25/setup I no longer even receive the apache page 

To confirm I am using CentOS

**Comment by jasonbyatt** [comment]
Okay I have the apache screen back, is there somewhere in particular I need to add the snipeit.txt content to on the script?

**Comment by jasonbyatt** [comment]
I have done some further troubleshooting, the webserver is working so the issue must lie with some of the documents in the set up? 

I've changed the document root and its taking me to a localhost/setup folder that it says it can't find?

**Comment by jasonbyatt** [comment]
Okay updated troubleshoot, I've compiled things I have tried 

1. Confirmed access on all folders isnt root
2. Added some garbage into .htaccess and it has chucked up an error
3. Changed document root and created dummy index.php to confirm web server is working as it should

**Comment by snipe** [comment]
```
<IfModule dir_module>
    DirectoryIndex index.html
</IfModule>
```

should probably be 

```
<IfModule dir_module>
    DirectoryIndex index.php index.html
</IfModule>
````

Otherwise nothing looks particularly wrong. When you `ls -al /var/www/html/snipeit/public` what do you see?

**Comment by arthur-thebear** [comment]
Hi,

got the same error - trying to access installation redirecting to url/setup and got the 500 error. Can't find any "setup" in public:

[root@snipeit public]# ls -lah
total 84K
drwxr-xr-x.  6 apache apache 4.0K Nov  2 11:25 .
drwxr-xr-x. 14 root   root   4.0K Nov  2 11:44 ..
drwxr-xr-x.  7 apache apache 4.0K Nov  2 11:25 assets
drwxr-xr-x.  3 apache apache 4.0K Nov  2 11:25 build
drwxr-xr-x.  3 apache apache 4.0K Nov  2 11:25 _debugbar
-rw-r--r--.  1 apache apache  32K Nov  2 11:25 favicon.ico
-rw-r--r--.  1 apache apache  724 Nov  2 12:08 .htaccess
-rw-r--r--.  1 apache apache 1.9K Nov  2 11:25 index.php
-rw-r--r--.  1 apache apache   24 Nov  2 11:25 robots.txt
-rw-r--r--.  1 apache apache  12K Nov  2 11:25 sample.csv
drwxr-xr-x.  7 apache apache 4.0K Nov  2 11:25 uploads
-rw-r--r--.  1 apache apache  914 Nov  2 11:25 web.config
[root@snipeit public]# 

CentOS 6.5 with PHP 5.6 is used..
Thank you.

**Comment by snipe** [comment]
There is no /setup directory.
