### ISSUE TITLE
New Buttons in Asset creation are not working

### ISSUE THREAD

**Issue by langweiler2003** [snipe/snipe-it#2710]
#### Expected Behavior (or desired behavior if a feature request)

When i create an Asset and click on new ( e.g. behind the Model field), the formular for a new Model/Supplier etc. is coming up. 
After filling in the needed data, the new entry is saved and selected in the asset

-----

#### Actual Behavior

After filling the forumlar with all needed fields the save button, seems to have no function. The window isnt closing and the new Model etc. isn't saved.
Test with Chrome and Firefox

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
<?php
return array (
  'app_version' => 'v3.4.0',
  'hash_version' => 'v3.4.0-9-g67315d8',
);

- What OS and web server you're running Snipe-IT on
CentOS 7 with Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- If you're getting an error in your browser, include that error
no error click on save doesnt have any effect
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
"create asset" and "update asset"
- If a stacktrace is provided in the error, include that too.
no stacktrace found
- Any errors that appear in your browser's error console.
no error shown
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
it is working fine in the demo
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
Laravel.log
[2016-09-27 11:34:14] production.DEBUG: Authenticating user against database.
[2016-09-29 12:58:19] production.DEBUG: Authenticating user against database.
[2016-09-29 12:58:19] production.DEBUG: Local authentication failed.
[2016-09-29 12:58:27] production.DEBUG: Authenticating user against database.
apache logs are empty

- Include what you've done so far in the installation, and if you got any error messages along the way.
nothing special, from default just adjusted the email settings
- Indicate whether or not you've manually edited any data directly in the database
no

Edit:
With InternetExplorer it is working perfect

**Comment by snipe** [comment]
> Any errors that appear in your browser's error console. no error shown

You opened up the browser console and checked for errors there, or you mean there are no error alerts showing up? This definitely sounds like a javascript issue, which should give you something in your browsers error console. https://snipe-it.readme.io/docs/getting-help#step-2-enable-your-browsers-error-console

**Comment by langweiler2003** [comment]
Hello,
youre right in the browser console i get errors:

create:1 XMLHttpRequest cannot load http://centauri/api/models. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://centauri' is therefore not allowed access.
create:1090 Uncaught TypeError: Cannot read property 'error' of undefined
create:1 XMLHttpRequest cannot load http://centauri/api/models. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://centauri' is therefore not allowed access.
create:1090 Uncaught TypeError: Cannot read property 'error' of undefined
create:1 XMLHttpRequest cannot load http://centauri/api/models. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://centauri' is therefore not allowed access.
create:1090 Uncaught TypeError: Cannot read property 'error' of undefined
create:1 XMLHttpRequest cannot load http://centauri.autowork.com/api/models. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://centauri' is therefore not allowed access.
create:1090 Uncaught TypeError: Cannot read property 'error' of undefined

**Comment by langweiler2003** [comment]
Ok it doesnt work if i only use the hostname in browser, but perfectly if im using the whole fqdn... 
Thank you

**Comment by snipe** [comment]
Whatever URL you use to access it must be the same as the one you set in your APP_URL in your .env file. Otherwise the javascript, etc won't load properly.
