### ISSUE TITLE
Ability to print asset labels for accessories  

### ISSUE THREAD

**Issue by JordanC12** [snipe/snipe-it#2712]
Is this going to be a planned feature for a future release? I would love to be able to print asset labels for accessories (such as monitor,mice, keyboard). I cannot seem to find the option in the accessories section...

**Comment by leobg** [comment]
I'd love to have this option too!

**Comment by AvnerCohen** [comment]
Is this a planned feature?
Is there an easy workaround? (creating all accessories as assets...)

**Comment by AukeTembrink** [comment]
I am looking for a workaround, too. Would be awesome to have the ability!

**Comment by RichardHerold** [comment]
please do enable this setting!

**Comment by AukeTembrink** [comment]
!up

**Comment by enoughsev** [comment]
Bump. THis would be great.

**Comment by JohnD87** [comment]
up

**Comment by Nicalicious** [comment]
It seems silly that you can only print labels for assets. So what's the alternative? Everything is configured as an asset?
