### ISSUE TITLE
Consumable

### ISSUE THREAD

**Issue by mattgann** [snipe/snipe-it#2722]
How do you replenish Consumables without deleting and making  the Consumables new each time they reach 0

**Comment by mattgann** [comment]
Can the remaining column amount be edited, and can qty amounts removed be changed to random number instead of single deductions

**Comment by TheGreatGene** [comment]
I've also had this problem, currently my solution is to update (increase) the "Quantity\QTY" each time I get new consumables\accessories. I think the solution for this would be to add an input field called restock or replenish to the end of each accessory/consumable items row.  Updating this filed and then clicking restock would update the quantity fields.
