### ISSUE TITLE
Asset maintenances view not rendering any data

### ISSUE THREAD

**Issue by JONDERITU** [snipe/snipe-it#2726]
on the asset maintenance page https://demo.snipeitapp.com/admin/asset_maintenances it returns no matching records. but on the asset maintenance report there are records.

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by cobrien165** [comment]
I'm having the same issue as well. Going to the asset_maintenances page brings up no results. The report lists the results and the asset maintenances are in each of the proper assets. Version v3.4.0-9-g67315d8

**Comment by JONDERITU** [comment]
@cobrien165 just do a git pull to get the latest version that will resolve
