### ISSUE TITLE
[Feature Request] Multi-User License Checkout

### ISSUE THREAD

**Issue by erik-burgess** [snipe/snipe-it#2728]
I would like to be able to check out a license to multiple users at one time. Currently, especially for new users cataloging all of their existing software, it is a painful process to assign licenses one by one. Especially if you have hundreds of users currently using any particular application.

**Comment by chibacityblues** [comment]
I second this. Manual checkout gets tedious with a lot of seats. Ideally, I'd like to be able to assign more licences that I currently own (with a warning) to a group to get an indication of licences to buy (as in Consumables).
