### ISSUE TITLE
Installation on IIS on Server 2008 R2

### ISSUE THREAD

**Issue by studentforever-yahoo** [snipe/snipe-it#2730]
Hi, similar to https://github.com/snipe/snipe-it/issues/1452
I have the same issue or similar issue, where i cant see any page when opened http:\\localhost and http:\\localhost\snipe-it

C:\inetpub\wwwroot\snipe-it>dir
 Volume in drive C is SysVol
 Volume Serial Number is 38DE-C948

 Directory of C:\inetpub\wwwroot\snipe-it

03/10/2016  12:12 PM    <DIR>          .
03/10/2016  12:12 PM    <DIR>          ..
06/09/2016  10:38 AM                67 .dockerignore
03/10/2016  01:18 PM             1,907 .env.example
06/09/2016  10:38 AM             1,764 .env.testing
06/09/2016  10:38 AM             1,758 .env.testing-ci
06/09/2016  10:38 AM                11 .gitattributes
03/10/2016  11:45 AM    <DIR>          .github
06/09/2016  10:38 AM               756 .gitignore
06/09/2016  10:38 AM               251 .htaccess
06/09/2016  10:38 AM             1,895 .travis.yml
03/10/2016  11:45 AM    <DIR>          app
06/09/2016  10:38 AM             1,646 artisan
03/10/2016  11:45 AM    <DIR>          bootstrap
06/09/2016  10:38 AM             9,210 c3.php
06/09/2016  10:38 AM               242 circle.yml
06/09/2016  10:38 AM               511 codeception.yml
03/10/2016  12:11 PM           751,448 Composer-Setup.exe
06/09/2016  10:38 AM             2,149 composer.json
06/09/2016  10:38 AM           185,956 composer.lock
03/10/2016  11:45 AM    <DIR>          config
03/10/2016  11:45 AM    <DIR>          database
03/10/2016  11:45 AM    <DIR>          docker
06/09/2016  10:38 AM               614 docker.env
06/09/2016  10:38 AM             2,897 Dockerfile
06/09/2016  10:38 AM             1,711 gh-changelog.php
06/09/2016  10:38 AM             1,486 gulpfile.js
06/09/2016  10:38 AM             1,064 index.html
06/09/2016  10:38 AM               240 install.sh
06/09/2016  10:38 AM            34,519 LICENSE
06/09/2016  10:38 AM               873 phpunit.xml
03/10/2016  11:45 AM    <DIR>          public
06/09/2016  10:38 AM             3,936 README.md
03/10/2016  11:45 AM    <DIR>          resources
06/09/2016  10:38 AM               567 server.php
06/09/2016  10:38 AM            21,049 snipeit.sh
03/10/2016  11:45 AM    <DIR>          storage
03/10/2016  11:45 AM    <DIR>          tests
              26 File(s)      1,028,527 bytes
              12 Dir(s)   8,208,191,488 bytes free

C:\inetpub\wwwroot\snipe-it>php artisan key:generate

C:\inetpub\wwwroot\snipe-it>composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for intervention/image 2.3.x-dev -> satisfiable by in tervention/image[2.3.x-dev].
    - intervention/image 2.3.x-dev requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
  Problem 2
    - Installation request for intervention/image dev-master -> satisfiable by intervention/image[dev-master].
    - intervention/image dev-master requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.

  To enable extensions, verify that they are enabled in those .ini files:
    - C:\Program Files\PHP\v7.0\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

C:\inetpub\wwwroot\snipe-it>
C:\inetpub\wwwroot\snipe-it>php artisan app:install --env=production
C:\inetpub\wwwroot\snipe-it>

The server is configured to use pass-through authentication with a built-in account to access the specified physical path. However, IIS Manager cannot verify whether the built-in account has access. Make sure that the application pool identity has Read access to the physical path. If this server is joined to a domain, and the application pool identity is NetworkService or LocalSystem, verify that <domain>\<computer_name>$ has Read access to the physical path. Then test these settings again.

file:    .env.example

# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=ChangeMe
APP_URL=http://localhost/snipeit
APP_TIMEZONE='Australia/Melbourne'
APP_LOCALE=en

# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=snipeit
DB_USERNAME=root
DB_PASSWORD=root
DB_PREFIX=null
DB_DUMP_PATH='C:\Program Files\MySQL\MySQL Server 5.5\bin'

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=email-smtp.us-west-2.amazonaws.com
MAIL_PORT=587
MAIL_USERNAME=YOURUSERNAME
MAIL_PASSWORD=YOURPASSWORD
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=you@example.com
MAIL_FROM_NAME='Snipe-IT'

# --------------------------------------------
# REQUIRED: IMAGE LIBRARY
# This should be gd or imagick
# --------------------------------------------
IMAGE_LIB=gd

# --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME=snipeit_session
COOKIE_DOMAIN=null
SECURE_COOKIES=false

# --------------------------------------------
# OPTIONAL: CACHE SETTINGS
# --------------------------------------------
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

# --------------------------------------------
# OPTIONAL: AWS S3 SETTINGS
# --------------------------------------------
AWS_SECRET=null
AWS_KEY=null
AWS_REGION=null
AWS_BUCKET=null

# --------------------------------------------
# OPTIONAL: MISC
# --------------------------------------------
APP_LOG=single
APP_LOCKED=false
FILESYSTEM_DISK=local
APP_TRUSTED_PROXIES=192.168.1.1,10.0.0.1
ALLOW_IFRAMING=false

Environment:
2008 R2
IIS 7.5

![image](https://cloud.githubusercontent.com/assets/22605021/19058787/ec250a1a-8a25-11e6-90ff-ec4c2d3ad31c.png)

![image](https://cloud.githubusercontent.com/assets/22605021/19058814/34b45b28-8a26-11e6-8852-903b6606c8da.png)

![image](https://cloud.githubusercontent.com/assets/22605021/19058828/512c7998-8a26-11e6-96d5-43c50fbe8dcd.png)

**Comment by snipe** [comment]
> - intervention/image 2.3.x-dev requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.

You have to enable the fileinfo extension.

**Comment by studentforever-yahoo** [comment]
Thanks for the info:
I have added the line in php.ini under PHP install

extension=php_fileinfo.dll

then restarted IIS

and now ran composer install again which is giving me following:

![image](https://cloud.githubusercontent.com/assets/22605021/19059651/48aed052-8a2d-11e6-9bd5-7cc2d86ec73b.png)

**Comment by studentforever-yahoo** [comment]
C:\inetpub\wwwroot\snipe-it>composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing codeception/c3 (2.0.7)
    Downloading: 100%

  - Installing vlucas/phpdotenv (v2.3.0)
    Downloading: 100%

  - Installing symfony/polyfill-mbstring (v1.2.0)
    Downloading: 100%

  - Installing symfony/var-dumper (v3.0.9)
    Downloading: 100%

  - Installing symfony/translation (v3.0.9)
    Downloading: 100%

  - Installing symfony/routing (v3.0.9)
    Downloading: 100%

  - Installing symfony/process (v3.0.9)
    Downloading: 100%

  - Installing symfony/polyfill-util (v1.2.0)
    Downloading: 100%

  - Installing symfony/polyfill-php56 (v1.2.0)
    Downloading: 100%

  - Installing symfony/http-foundation (v3.0.9)
    Downloading: 100%

  - Installing symfony/event-dispatcher (v3.1.3)
    Downloading: 100%

  - Installing psr/log (1.0.0)
    Downloading: 100%

  - Installing symfony/debug (v3.0.9)
    Downloading: 100%

  - Installing symfony/http-kernel (v3.0.9)
    Downloading: 100%

  - Installing symfony/finder (v3.0.9)
    Downloading: 100%

  - Installing symfony/console (v3.0.9)
    Downloading: 100%

  - Installing swiftmailer/swiftmailer (v5.4.3)
    Downloading: 100%

  - Installing nikic/php-parser (v2.1.0)
    Downloading: 100%

  - Installing jakub-onderka/php-console-color (0.1)
    Downloading: 100%

  - Installing jakub-onderka/php-console-highlighter (v0.3.2)
    Downloading: 100%

  - Installing dnoegel/php-xdg-base-dir (0.1)
    Downloading: 100%

  - Installing psy/psysh (v0.7.2)
    Downloading: 100%

  - Installing paragonie/random_compat (v1.4.1)
    Downloading: 100%

  - Installing nesbot/carbon (1.21.0)
    Downloading: 100%

  - Installing mtdowling/cron-expression (v1.1.0)
    Downloading: 100%

  - Installing monolog/monolog (1.21.0)
    Downloading: 100%

  - Installing league/flysystem (1.0.27)
    Downloading: 100%

  - Installing jeremeamia/superclosure (2.2.0)
    Downloading: 100%

  - Installing doctrine/inflector (v1.1.0)
    Downloading: 100%

  - Installing classpreloader/classpreloader (3.0.0)
    Downloading: 100%

  - Installing laravel/framework (v5.2.45)
    Downloading: 100%

  - Installing mtdowling/jmespath.php (2.3.0)
    Downloading: 100%

  - Installing psr/http-message (1.0.1)
    Downloading: 100%

  - Installing guzzlehttp/psr7 (1.3.1)
    Downloading: 100%

  - Installing guzzlehttp/promises (1.2.0)
    Downloading: 100%

  - Installing guzzlehttp/guzzle (6.2.1)
    Downloading: 100%

  - Installing aws/aws-sdk-php (3.19.2)
    Downloading: 100%

  - Installing aws/aws-sdk-php-laravel (3.1.0)
    Downloading: 100%

  - Installing maximebf/debugbar (v1.12.0)
    Downloading: 100%

  - Installing barryvdh/laravel-debugbar (V2.2.3)
    Downloading: 100%

  - Installing doctrine/lexer (v1.0.1)
    Downloading: 100%

  - Installing doctrine/annotations (v1.2.7)
    Downloading: 100%

  - Installing doctrine/cache (v1.5.4)
    Downloading: 100%

  - Installing doctrine/collections (v1.3.0)
    Downloading: 100%

  - Installing doctrine/common (v2.5.3)
    Downloading: 100%

  - Installing doctrine/dbal (v2.4.2)
    Downloading: 100%

  - Installing erusev/parsedown (dev-master f671ae7)
    Downloading: 100%

  - Installing fideloper/proxy (3.1.0)
    Downloading: 100%

  - Installing intervention/image (dev-master 45a41a3)
    Downloading: 100%

  - Installing laravelcollective/html (v5.2.4)
    Downloading: 100%

  - Installing league/csv (7.2.0)
    Downloading: 100%

  - Installing maknz/slack (dev-master e9bab77)
    Downloading: 100%

  - Installing misterphilip/maintenance-mode (1.0.2)
    Downloading: 100%

  - Installing neitanod/forceutf8 (dev-master 2c1b21e)
    Downloading: 100%

  - Installing spatie/db-dumper (1.5.1)
    Downloading: 100%

  - Installing spatie/laravel-backup (3.8.1)
    Downloading: 100%

  - Installing tecnickcom/tc-lib-color (1.12.0)
    Downloading: 100%

  - Installing tecnickcom/tc-lib-barcode (dev-master df69541)
    Downloading: 100%

  - Installing watson/validating (2.2.2)
    Downloading: 100%

  - Installing symfony/yaml (v3.1.3)
    Downloading: 100%

  - Installing symfony/dom-crawler (v3.1.3)
    Downloading: 100%

  - Installing symfony/css-selector (v3.1.3)
    Downloading: 100%

  - Installing symfony/browser-kit (v3.1.3)
    Downloading: 100%

  - Installing sebastian/version (1.0.6)
    Downloading: 100%

  - Installing sebastian/global-state (1.1.1)
    Downloading: 100%

  - Installing sebastian/recursion-context (1.0.2)
    Downloading: 100%

  - Installing sebastian/exporter (1.2.2)
    Downloading: 100%

  - Installing sebastian/environment (1.3.8)
    Downloading: 100%

  - Installing sebastian/diff (1.4.1)
    Downloading: 100%

  - Installing sebastian/comparator (1.2.0)
    Downloading: 100%

  - Installing phpunit/php-text-template (1.2.1)
    Downloading: 100%

  - Installing doctrine/instantiator (1.0.5)
    Downloading: 100%

  - Installing phpunit/phpunit-mock-objects (2.3.8)
    Downloading: 100%

  - Installing phpunit/php-timer (1.0.8)
    Downloading: 100%

  - Installing phpunit/php-file-iterator (1.4.1)
    Downloading: 100%

  - Installing phpunit/php-token-stream (1.4.8)
    Downloading: 100%

  - Installing phpunit/php-code-coverage (2.2.4)
    Downloading: 100%

  - Installing webmozart/assert (1.1.0)
    Downloading: 100%

  - Installing phpdocumentor/reflection-common (1.0)
    Downloading: 100%

  - Installing phpdocumentor/type-resolver (0.2)
    Downloading: 100%

  - Installing phpdocumentor/reflection-docblock (3.1.0)
    Downloading: 100%

  - Installing phpspec/prophecy (v1.6.1)
    Downloading: 100%

  - Installing phpunit/phpunit (4.8.27)
    Downloading: 100%

  - Installing facebook/webdriver (1.1.3)
    Downloading: 100%

  - Installing codeception/codeception (2.1.11)
    Downloading: 100%

  - Installing fzaninotto/faker (v1.6.0)
    Downloading: 100%

  - Installing hamcrest/hamcrest-php (v1.2.2)
    Downloading: 100%

  - Installing mockery/mockery (0.9.5)
    Downloading: 100%

  - Installing phpspec/php-diff (v1.0.2)
    Downloading: 100%

  - Installing phpspec/phpspec (2.5.1)
    Downloading: 100%

  - Installing squizlabs/php_codesniffer (2.6.2)
    Downloading: 100%

symfony/var-dumper suggests installing ext-symfony_debug ()
symfony/translation suggests installing symfony/config ()
symfony/routing suggests installing symfony/config (For using the all-in-one router or any loader)
symfony/routing suggests installing symfony/dependency-injection (For loading routes from a service)

symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/event-dispatcher suggests installing symfony/dependency-injection ()
symfony/http-kernel suggests installing symfony/class-loader ()
symfony/http-kernel suggests installing symfony/config ()
symfony/http-kernel suggests installing symfony/dependency-injection ()
psy/psysh suggests installing ext-pcntl (Enabling the PCNTL extension makes PsySH a lot happier :))
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing ext-posix (If you have PCNTL, you'll want the POSIX extension as well.
)
psy/psysh suggests installing ext-readline (Enables support for arrow-key history navigation, and sh
owing and manipulating command history.)
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be
used to generate random bytes.)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server
)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ req
uired))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 serv
er)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server
via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP s
erver using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Ch
rome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search
 server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
league/flysystem suggests installing league/flysystem-aws-s3-v2 (Allows you to use S3 storage with A
WS SDK v2)
league/flysystem suggests installing league/flysystem-aws-s3-v3 (Allows you to use S3 storage with A
WS SDK v3)
league/flysystem suggests installing league/flysystem-azure (Allows you to use Windows Azure Blob st
orage)
league/flysystem suggests installing league/flysystem-cached-adapter (Flysystem adapter decorator fo
r metadata caching)
league/flysystem suggests installing league/flysystem-copy (Allows you to use Copy.com storage)
league/flysystem suggests installing league/flysystem-dropbox (Allows you to use Dropbox storage)
league/flysystem suggests installing league/flysystem-eventable-filesystem (Allows you to use Eventa
bleFilesystem)
league/flysystem suggests installing league/flysystem-rackspace (Allows you to use Rackspace Cloud F
iles)
league/flysystem suggests installing league/flysystem-sftp (Allows you to use SFTP server storage vi
a phpseclib)
league/flysystem suggests installing league/flysystem-webdav (Allows you to use WebDAV storage)
league/flysystem suggests installing league/flysystem-ziparchive (Allows you to use ZipArchive adapt
er)
laravel/framework suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 d
river (~1.0).)
laravel/framework suggests installing league/flysystem-rackspace (Required to use the Flysystem Rack
space driver (~1.0).)
laravel/framework suggests installing pda/pheanstalk (Required to use the beanstalk queue driver (~3
.0).)
laravel/framework suggests installing predis/predis (Required to use the redis cache and queue drive
rs (~1.0).)
laravel/framework suggests installing pusher/pusher-php-server (Required to use the Pusher broadcast
 driver (~2.0).)
laravel/framework suggests installing symfony/psr-http-message-bridge (Required to use psr7 bridging
 features (0.2.*).)
aws/aws-sdk-php suggests installing aws/aws-php-sns-message-validator (To validate incoming SNS noti
fications)
aws/aws-sdk-php-laravel suggests installing laravel/lumen-framework (To test the Lumen bindings)
maximebf/debugbar suggests installing kriswallsmith/assetic (The best way to manage assets)
maximebf/debugbar suggests installing predis/predis (Redis storage)
intervention/image suggests installing ext-imagick (to use Imagick based image processing.)
intervention/image suggests installing intervention/imagecache (Caching extension for the Interventi
on Image library)
maknz/slack suggests installing maknz/slack-laravel (Required for Laravel support)
maknz/slack suggests installing nexylan/slack-bundle (Required for Symfony bundle support)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
facebook/webdriver suggests installing phpdocumentor/phpdocumentor (2.*)
codeception/codeception suggests installing codeception/phpbuiltinserver (Extension to start and sto
p PHP built-in web server for your tests)
codeception/codeception suggests installing codeception/specify (BDD-style code blocks)
codeception/codeception suggests installing codeception/verify (BDD-style assertions)
codeception/codeception suggests installing phpseclib/phpseclib (Extension required to use the SFTP
option in the FTP Module.)
codeception/codeception suggests installing symfony/phpunit-bridge (For phpunit-bridge support)
phpspec/phpspec suggests installing phpspec/nyan-formatters (~1.0 ΓÇô Adds Nyan formatters)
Generating autoload files
[codeception/c3] c3.php is already up-to-date
> php artisan clear-compiled
> php artisan optimize
Generating optimized class loader
Compiling common classes

C:\inetpub\wwwroot\snipe-it>


Do i have to re run the key generation?

**Comment by snipe** [comment]
If you've copied over the .env.example to .env, yes

**Comment by studentforever-yahoo** [comment]
Thanks for the help. Please guide. 

yes, i have copied the .env
I am getting a " waiting for local host " when loading the webpage then it says cannot find.


![image](https://cloud.githubusercontent.com/assets/22605021/19291259/cba5b114-905f-11e6-849d-868dd5319ba6.png)


![image](https://cloud.githubusercontent.com/assets/22605021/19291273/ee889f70-905f-11e6-9ceb-a7d8fd6be1c3.png)

**Comment by studentforever-yahoo** [comment]
I have found one thing which i have fixed in my .env file

changed APP_URL
from APP_URL=http://localhost/snipeit
to APP_URL=null

Restarted IIS and now i can see the Snipe-IT Pre-Flight page, which crashed on the page where we have to create a new user.


![image](https://cloud.githubusercontent.com/assets/22605021/19291499/5445f636-9061-11e6-87c0-c7dd9c80c8e3.png)


But after that it is showing this:

![image](https://cloud.githubusercontent.com/assets/22605021/19291759/e79c9588-9062-11e6-8e57-ebee8c04736e.png)

**Comment by studentforever-yahoo** [comment]
Debugger on IE

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Snipe-IT</title>

    
    <link rel="stylesheet" href="http://localhost/assets/css/bootstrap.min.css">
    
    <link rel="stylesheet" href="http://localhost/assets/css/font-awesome.min.css">

    
    <link rel="stylesheet" href="http://localhost/assets/js/plugins/select2/select2.min.css">

    
    <link rel="stylesheet" href="http://localhost/assets/js/plugins/colorpicker/bootstrap-colorpicker.min.css">

    <link rel="stylesheet" href="http://localhost/assets/js/plugins/datepicker/bootstrap-datepicker.css">

    
    <link rel="stylesheet" href="http://localhost/assets/js/plugins/jvectormap/jquery-jvectormap-1.2.2.css">
    
    <link rel="stylesheet" href="http://localhost/assets/css/AdminLTE.min.css">
    <link rel="stylesheet" href="http://localhost/assets/css/skins/skin-blue.css">

    
    <link rel="stylesheet" href="http://localhost/assets/css/bootstrap-table.css">

    <link rel="stylesheet" href="/build/assets/css/app-de75b6d10a.css">
    <link rel="shortcut icon" type="image/ico" href="http://localhost/favicon.ico">


    
</head>

<body class="hold-transition login-page">

      
  


<div class="row">
  <div class="col-md-12">

    <div class="error-page" style="padding-top: 200px">
      <img src="/assets/img/sad-panda.png" style="width: 200px; height: 200px;" class="pull-left">
            <div class="error-content">
              <h3><i class="fa fa-warning text-yellow"></i> 404 Page not found.</h3>
              <p>
                Sad panda. We could not find the page you were looking for.
                You should maybe <a href="http://localhost">return to the dashboard</a>.
              </p>

    </div>
</div>



</body>

</html>

**Comment by studentforever-yahoo** [comment]
Following is the Chrome debugging and has following when i go to localhost/snipe-it


![image](https://cloud.githubusercontent.com/assets/22605021/19292476/1da8e262-9068-11e6-91d3-f9fea9874ae9.png)


![image](https://cloud.githubusercontent.com/assets/22605021/19292481/271aab1e-9068-11e6-83e9-9a5b72c31e3b.png)

**Comment by studentforever-yahoo** [comment]
@snipe  : please guide. Thanks. Issue ticket has been closed.

**Comment by snipe** [comment]
You cannot set the APP_URL to null. It will break just about everything
