### ISSUE TITLE
Can't select category when creating new asset

### ISSUE THREAD

**Issue by Nunatac** [snipe/snipe-it#2734]
-Expected Behavior (or desired behavior if a feature request)
Hi, when i create a new asset there is no possibility to select the category or to change it after the creation.
![image](https://cloud.githubusercontent.com/assets/22613976/19071358/f810f9ba-8a2f-11e6-822d-f082b7e2451f.png)

 The only way to set a category is to set it in a csv and import the asset.

-Actual Behavior
 Every new asset go into laptop category without the option to choose or edit the category.

-Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
-Please provide answers to these questions before posting your bug report:

Version v3.4.0-9-g67315d8
Windows 2008R2 Datacenter
Manual Install
Same thing happen in the demo

Sorry if i've missed something. Hope someone can help. Thank you

**Comment by therealjoshuad** [comment]
Categories are assigned at the model types, the asset then inherits the category from it's selected model type.

**Comment by Nunatac** [comment]
@therealjoshuad Thank you very much! Found it!
