### ISSUE TITLE
Installing Snipe It on Godaddy Linux server

### ISSUE THREAD

**Issue by thetallguy24** [snipe/snipe-it#2736]
I have setup the .env file per Snipe-It's instructions and uploaded all the files to the /webroot folder.

When I try to go to Snipe, I get the following error:

"D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory."

There is no public_html folder or anything like in this setup, so how should I proceed?

**Comment by thetallguy24** [comment]
After going through the configuration again, I am now getting the following error when entering in the URL to access Snipe

Parse error: syntax error, unexpected T_CLASS, expecting T_STRING or T_VARIABLE or '$' in /home/content/27/8110727/html/public/snipe/public/index.php on line 56

**Comment by snipe** [comment]
What version of PHP are you using?

**Comment by thetallguy24** [comment]
5.3

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/requirements

<img width="772" alt="screen shot 2016-10-05 at 2 49 53 pm" src="https://cloud.githubusercontent.com/assets/197404/19132997/0539ec4c-8b0b-11e6-8dc9-e9e2f31c465e.png">

**Comment by thetallguy24** [comment]
Damn. Godaddy only goes up to 5.4

**Comment by thetallguy24** [comment]
Would there be any issues if I switched to a PHP 7 server?

**Comment by snipe** [comment]
No, Snipe-IT runs fine on PHP7

**Comment by thetallguy24** [comment]
Ok great thanks

**Comment by Cjfrancisco2022** [comment]
hello, guys especially for @thetallguy24 how you solve the issue on this message "D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory."  - we are same setup we using go-daddy shared server
