### ISSUE TITLE
Sort on location removes rows with null values

### ISSUE THREAD

**Issue by Yanzzee** [snipe/snipe-it#2737]
#### Expected Behavior (or desired behavior if a feature request)

When in asset view (all assets etc.), all assets should be listed despite how they are sorted.

---
#### Actual Behavior

When sorting on location, the total number of rows is reduced. Apparently removing rows that have a null value in the sort column. If sorting by id or another column without nulls the entire list is shown again. Assets may have nulls because they were imported from a CSV without location information. Verified that after updating a null value to a legit location id the sort no longer affected whether it would display. Not sure if this is affecting other sort columns, but I suspect so.

---
#### Please confirm you have done the following before posting your bug report:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)*Bad URL

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running
  v3.4-14-g2a8ab06
- What OS and web server you're running Snipe-IT on
  Cent OS 7 Apache 2.4.6
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  install.sh
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
  All assets page, sort by location
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
  importing disabled, but have verified the issue on two instances
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
  Yes, but was having the problem before doing this. Edited the DB to add location information

**Comment by crtfdgk** [comment]
This does not appear to affect any column other than 'Location' - verified on v3.6.6
