### ISSUE TITLE
Asset models list view

### ISSUE THREAD

**Issue by vgsangiuliano** [snipe/snipe-it#2739]
Dear all,
in asset model list view I have this situation:

![image](https://cloud.githubusercontent.com/assets/10364374/19109849/7783fd74-8af7-11e6-8ce6-33e177371948.png)

Model No. are not "clickable" and if I click on first Latitude row it will displays only 9 assets that belong to E7440 model number.
In my opinion it would be more consistent if I click on each of the Latitude rows it will show me the list of all the assets belonging to Latutude model (9 E7440 + 3 E4310 + 3 E4300).
Furthermore if model number would be "clickable" it would be ok clicking on a model number and having the list of only assets belonging to that particular model number.

What do you think about that
Thanks
KR
Mirko

**Comment by therealjoshuad** [comment]
I name my models to match the model number.

Example: 
Asset Model: Latitude E7440
Model No: E7440
Asset Model: Latitude E7430
Model No: E7430
Asset Model: PowerEdge R720
Model No: PER720

I don't think Model No was meant to be a sub of "Asset Model", I think Asset model is how you would identify a specific model number in a more human readable format

**Comment by snipe** [comment]
That's correct @therealjoshuad - there isn't really anything to click on, since it's just a visible attribute of an asset model.
