### ISSUE TITLE
Installing On Windows, On Wamp Server - Error

### ISSUE THREAD

**Issue by vdanelia** [snipe/snipe-it#2741]
Hello.. Can't install it on Windows Wamp server.. it says "D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory."
Can you provide step by step manual of corrctly installing it on WampServer
Thank you in Advanced!

**Comment by snipe** [comment]
It's telling you what the problem is is. "Your DocumentRoot is set incorrectly. It should be set to the public directory."

**Comment by vdanelia** [comment]
Hello Snipe, Thanks for your reply....  Wampserver creates one root directory called "www" so as I guess I have to compy snipe's all directories there (everything), but in that directory I have other cms files too... is it possible to configure snipe in such way that it worked from the directory "snipe" which I copied in the root directory..

Thank You In Advanced!
