### ISSUE TITLE
[Feature Request]: Add custom notes/date-based data to assets

### ISSUE THREAD

**Issue by FREImedia** [snipe/snipe-it#2742]
It would be a very very useful feature to add something like a 'note history' for an asset.
Each note is identified by the date of creation.

Example for an asset (e.g. computer):
2016-10-01: Installed Windows 10
2016-10-03: User complaint about slow performance, upgraded RAM size of PC
2016-11-02:  Installed regular updates

Additionally you could also add (custom) tags to a note. For example "Update", "Problem", ... whatever. So you can sort the notes for an asset by its tag/category.

Thanks for reading!
Matthias

**Comment by therealjoshuad** [comment]
If you're using notes strictly for maintenance notes, have you looked at the Asset Maintenances tab? 

From an Asset, click the Maintenances tab. From there you can add new "tech notes" with each type of action performed. You can select Asset Maintenance Types to define the type of maintenance done.

**Comment by FREImedia** [comment]
Thanks for your quick reply!
Yes, I have noticed the mentioned Maintenances tab and your right, its possible to use this function for my purpose. But it looked more like a function to manage contracts to me. This is why I asked if theres a separated possibility to add "tech notes".

Thank you!
