### ISSUE TITLE
Fatal error autoload.php line 17

### ISSUE THREAD

**Issue by thetallguy24** [snipe/snipe-it#2744]
Moved to a different server. Using PHP 7

Get the following error when trying to open Snipe for the first time.

 Fatal error: require(): Failed opening required '/home/henryh38/public_html/snipe/bootstrap/../vendor/autoload.php' (include_path='.:/usr/local/php70/pear') in /home/henryh38/public_html/snipe/bootstrap/autoload.php on line 17

Any idea what is causing this?

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/common-issues#warning-requirebootstrapvendorautoloadphp-failed-t

**Comment by thetallguy24** [comment]
Ok so I've gone through everything again. I've made sure Composer is properly installed and the key was generated. Now I am just getting a 404.

I've made sure the URL is set to:
.../public_html/snipe/public/

Database settings look correct.

**Comment by snipe** [comment]
>> I've made sure the URL is set to:
>> .../public_html/snipe/public/

The URL, or the Document Root? public should never be in the URL

**Comment by snipe** [comment]
(Neither should `public_html`)

**Comment by thetallguy24** [comment]
But Snipe should be installed within public_html correct? Snipe is currently installed to public_html/snipe.

**Comment by snipe** [comment]
Are you installing this as a subdirectory?

**Comment by thetallguy24** [comment]
Yes. I have a new server, so I wanted to install Snipe first, then install all my other websites. As I said I have installed Snipe to public_html/snipe.

I have updated the .htaccess file under the public file to     RewriteBase /snipe

**Comment by thetallguy24** [comment]
I'm using SiteGround, so I'm not sure if that plays a role in this. It's been awhile since I'd done much with Linux
