### ISSUE TITLE
Windows/Apache The requested URL /setup was not found on this server.

### ISSUE THREAD

**Issue by demazter** [snipe/snipe-it#2747]
#### Expected Behavior (or desired behavior if a feature request)

Start the pre-flight check/installation

---
#### Actual Behavior

404 error in browser

---
#### Please confirm you have done the following before posting your bug report:
- [Y] I have enabled debug mode
- [Y] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running - latest download from site
- What OS and web server you're running Snipe-IT on - Windows Server 2012 Apache2.4
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual
- If you're getting an error in your browser, include that error - The requested URL /setup was not found on this server.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. The requested URL /setup was not found on this server.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). no
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. 
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

I've followed the installation guide as closely as possible but still receive this error when trying to perform a new installation.  I've now rebuilt the server 3 times with the same results.

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/common-issues#the-requested-url-setup-was-not-found-on-this-serv

**Comment by wahash** [comment]
please can you provide more information about this issues . i listed https://snipe-it.readme.io/docs/common-issues#the-requested-url-setup-was-not-found-on-this-serv
this link an tried to find answer but still have a same problem . mod revrite is enebled and worked (sudo a2enmod rewrite) and checked (# apache2ctl -M | grep "rewrite_module")  and i still have problem

**Comment by nobimalik** [comment]
after enabling the rewrite mode it worked for me!. (sudo a2enmod rewrite)
