### ISSUE TITLE
Install Issue (SQLSTATE[HY000] [2002] Permission denied)

### ISSUE THREAD

**Issue by KoshiirRa** [snipe/snipe-it#2748]
#### Expected Behavior (or desired behavior if a feature request)
Pre-Flight should load
-----

#### Actual Behavior

Pre-Flight does not load, instead brings you to the "Whoops, looks like something went wrong" page.  Enabling debug mode gives me the following (plus 53 more lines of chained code detailing exactly where it happened)
PDOException in Connector.php line 55:
SQLSTATE[HY000] [2002] Permission denied
-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: V3
- What OS and web server you're running Snipe-IT on: Centos 7, Apache 2.4.6
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): install.sh
- If you're getting an error in your browser, include that error: see above
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: attempting to load pre-flight

**Comment by snipe** [comment]
Your database settings are incorrect, or the hostname you specified is not reachable by the Snipe-IT application.

**Comment by KoshiirRa** [comment]
The DB server is on the same machine, so it is set as localhost.  The database is mysql, and I've verified that the username and password work by logging in manually with them.  Database settings are configured as

DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=snipeit
DB_USERNAME=<removed>
DB_PASSWORD=<removed>
DB_PREFIX=null
DB_DUMP_PATH='/bin'

mysqldump on this machine is in /bin instead of /usr/bin, as verified via which mysqldump.

**Comment by KoshiirRa** [comment]
Resolved!  The database was running in safe for some reason.

**Comment by snipe** [comment]
Glad you got it sorted!
