### ISSUE TITLE
Search box doesn't clear

### ISSUE THREAD

**Issue by therealjoshuad** [snipe/snipe-it#2749]
#### Expected Behavior (or desired behavior if a feature request)

When using the Search box in the All Assets view, I would expect the text entered in the search box to be cleared after leaving that page.

-----

#### Actual Behavior

Search for something using the search box in the all assets page. Navigate other various pages on the site, and then com back to the All Asset's page, the search box still contains the search text from the previous search.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running **3.4.0**
- What OS and web server you're running Snipe-IT on **Ubuntu 16.04.1, nginx**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **install.sh**
- If you're getting an error in your browser, include that error **N/A**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **http://<siteurl>/hardware**
- If a stacktrace is provided in the error, include that too. **N/A**
- Any errors that appear in your browser's error console. **N/A**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). **Yes**
- Indicate whether or not you've manually edited any data directly in the database **No**

![image](https://cloud.githubusercontent.com/assets/3893036/19171254/6d3540c2-8be1-11e6-9c90-c38706261571.png)

**Comment by snipe** [comment]
That's not really a bug, per se. We've had it both ways, and people seem to have their own preferences, so we're not going to be making changes to that at this time.

**Comment by Iizuki** [comment]
This can be quite unhelpful when sharing links. They may have some local search saved and see something else (often nothing) than the link sender.

**Comment by snipe** [comment]
@lizuki - When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.

And as I said 10 years ago, you can’t make everyone happy all the time. Your own search criteria are saved in local storage, so I don’t even think what you’re complaining about is a thing.
