### ISSUE TITLE
Show asset default location when looking at an asset page

### ISSUE THREAD

**Issue by niutechmx** [snipe/snipe-it#2753]
#### Expected Behavior (or desired behavior if a feature request)

**I'd like to see the Asset default location when looking at an asset page. Currently I have to edit the asset to see where it is.** 
-----

#### Actual Behavior
**Although the user enters the default location when creating or editing an asset, the field is not visible when viewing the asset. To see the default location the user has to edit the asset or export a list of asset to csv**
-----

#### Please confirm you have done the following before posting your bug report:

- [**x**] I have enabled debug mode
- [**x**] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: **v3.4-14-g2a8ab06**
- What OS and web server you're running Snipe-IT on: **CentOS Linux 7.2.1511, Apache**
- What method you used to install Snipe-IT : **GIT**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: **I cannot see the default location when looking at http://localhost/hardware/83/view I CAN see it when in http://localhost/hardware/83/edit. It would be convenient to see it also in the first one**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). **YES**
- Indicate whether or not you've manually edited any data directly in the database: **NO**

**Comment by orygen** [comment]
I second this request.

**Comment by Yanzzee** [comment]
+1
