### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by sirrus** [snipe/snipe-it#2754]
#### Expected Behavior (or desired behavior if a feature request)

Translation should translate the "Create new" button on each page (Assets, Licenses, Accessories, Components, Consumables, People).

-----

#### Actual Behavior

The german translation of "Create new" is "Create Location" - it should be "Neu erstellen" or "Erstellen".

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT 3.4.x
- Debian
- ZIP and git
- Snipe-IT pages Assets, Licenses, Accessories, Components, Consumables, People
- reproduceable on the demo (https://snipeitapp.com/demo)

**Comment by sirrus** [comment]
FIxed in my fork sirrus/snipe-it
commit aa7ce9fffb4767d1edb1630451cafe69cabde3f4

**Comment by dmeltzer** [comment]
Hi!

Snipe uses crowdin to manage translations.  As long as the string is marked to be translated in the source, you should submit translations there.  https://crowdin.com/project/snipe-it
