### ISSUE TITLE
Icons won't show in IE 11

### ISSUE THREAD

**Issue by nizzoball** [snipe/snipe-it#2757]
#### Expected Behavior (or desired behavior if a feature request)

Would like the navigation icons to show up in IE since the default browser in most enterprises is going to be IE.  Chrome displays everything fine.

Edit: 0 icons display, not even the heart at the bottom of the screen.

-----

#### Actual Behavior

None of the icons on the sidebar or top bar show up while using IE 11.  Happens in compatibility mode as well as normal mode.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.4.0-9-g67315d8
- What OS and web server you're running Snipe-IT on
Centos 6 / Apache / PHP 5.6.26
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
All pages
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
Yes, same behavior
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
No errors, just a display issue
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
No, install has only been live for 2 days.  We are in the testing phase to determine if we want to move ahead with Snipe-IT.  I personally don't use IE so I didn't catch the issue at first but one of my users did while adding initial data.  

I love Snipe-IT in my limited use of it.  I am hoping this is something that is easily fixed.

**Comment by nizzoball** [comment]
![snipe_ie_issue](https://cloud.githubusercontent.com/assets/16013140/19238071/68d86c98-8ec5-11e6-8205-7fc81054fdf8.jpg)

**Comment by snipe** [comment]
Thanks for the screenshot - can you please tell me if there are any errors in your browser console?

**Comment by nizzoball** [comment]
There are no errors anywhere, its really weird, ive never experienced
anything like it.

**Comment by snipe** [comment]
I can't reproduce this at all using Browserstack (Win 10, IE11)

<img width="1490" alt="screen shot 2016-10-12 at 1 55 05 pm" src="https://cloud.githubusercontent.com/assets/197404/19327386/9c591ef4-9083-11e6-9d3a-9ac0b2035a47.png">

**Comment by nizzoball** [comment]
Let me check the demo on my home computer, maybe theres a corporate policy
that is blocking the icons on IE which would just be par for the course. I
hate IE.

**Comment by nizzoball** [comment]
I just comfirmed that its a corporate policy that is hemming things up. I
really apologize for putting in the ticket, i will close it. Thank you for
your time.

**Comment by snipe** [comment]
No worries - glad you figured it out.
