### ISSUE TITLE
3.5 beta 2 - missing recent activity in dashboard and blank activity report

### ISSUE THREAD

**Issue by mmcleod82** [snipe/snipe-it#2758]
**mmcleod82 @mmcleod82 10:02** 
has anybody else lost 'activity' data since upgrading to 3.5beta2 ?
recent activity in dashboard is clear, as is the recent activity report

**Daniel Meltzer @dmeltzer 12:05**
@mmcleod82 I'd love to know more
We changed things, but testing didn't show issues
Is your "action _ logs"table in the dB empty? 

**Daniel Meltzer @dmeltzer 12:11** 
and, of course, did you run php artisan migrate? :grinning:

**Daniel Meltzer @dmeltzer 12:45** 
and, finally, what happens if you go to <url>/reports/activity/json ?
Gotta run, I won't be back here for at least 13 hours, but if you can open an issue with the answer to some of these questions I'll take a look at it then
thanks!

**mmcleod82 @mmcleod82 14:11** 
@dmeltzer yes definitely ran php artisan migrate. /reports/activity/json throws an exception:

**FatalErrorException in ReportsController.php line 373:
Call to a member function fullName() on null**

action_logs table is NOT empty (thank god :grinning: )
in fact I'd say no data is missing from that action_log, number of rows is about what I'd expect to see.

**Comment by dmeltzer** [comment]
Do you have any rows in the action_logs table where the target_type is "App\Models\User" but the target_id doesn't exist?

**Comment by mmcleod82** [comment]
Quite possibly - that reminds me, it's probably related to #2480 ...

**Comment by dmeltzer** [comment]
I can add a guard around it as soon as I have a few quiet minutes.  I'll try for tomorrow.

**Comment by mmcleod82** [comment]
This didn't quite fix the issue, see my comments from gitter:

mmcleod82 @mmcleod82 10:04 
@dmeltzer I've applied your fix for the empty activity in dashboard, thanks for that. It is still blank though :expressionless: 
the activity report itself however now displays instead of throwing an exception, but that is also blank.

mmcleod82 @mmcleod82 10:16
Now, checking assets in throws an exception on line 33 of actionlog.php (Trying to get property of non object)
$actionlog->company_id = $actionlog->target->company_id;
I'm no SQL expert, but a select * from asset_logs shows the last entry in that table was 21-09-16.

mmcleod82 @mmcleod82 10:22 
so it's not being populated anymore
I went to 3.5 beta on 20-09.

**Comment by dmeltzer** [comment]
(answered in gitter, but just in case it gets busy).  This should be fixed current `develop` branch, more specifically the part of https://github.com/snipe/snipe-it/commit/e85241af6afe6cf15cebe90c89f9325bbb4ea41e that changes Actionlog.php.  

The `asset_logs` table is not used any more, we use a new action_logs table that all data was migrated to.  The asset_logs table was left for now in case any migrations go poorly.

**Comment by mmcleod82** [comment]
I've applied the fixes in [e85241a](https://github.com/snipe/snipe-it/commit/e85241af6afe6cf15cebe90c89f9325bbb4ea41e) but still the activity is blank. It does fix the checkin exception though.

**Comment by dmeltzer** [comment]
Hi,

If you change line 377 to read `if ($activity->target) {` instead of `if ($activity->target()) {` does it fix the issue?

**Comment by mmcleod82** [comment]
Hi - line 377 of which file ?
