### ISSUE TITLE
Upgrade Error

### ISSUE THREAD

**Issue by elJoeyJojo** [snipe/snipe-it#2765]
#### Expected Behavior (or desired behavior if a feature request)

I want to upgrade to v3.5 beta 2

---
#### Actual Behavior

when i run "php artisan migrate" I get Permission Denied error even though Storage folder has the correct permissions.

---
- ```
  Application In Production!     *
  ```
  ---
  
  Do you really wish to run this command? (yes/no) [no]:
  
  > yes

PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/opt/snipe-it/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied' in /opt/snipe-it/bootstrap/cache/compiled.php:13906
Stack trace:
#0 /opt/snipe-it/bootstrap/cache/compiled.php(13836): Monolog\Handler\StreamHandler->write(Array)
#1 /opt/snipe-it/bootstrap/cache/compiled.php(13596): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /opt/snipe-it/bootstrap/cache/compiled.php(13694): Monolog\Logger->addRecord(400, Object(UnexpectedValueException), Array)
#3 /opt/snipe-it/bootstrap/cache/compiled.php(13389): Monolog\Logger->error(Object(UnexpectedValueException), Array)
#4 /opt/snipe-it/bootstrap/cache/compiled.php(13360): Illuminate\Log\Writer->writeLog('error', Object(UnexpectedValueException), Array)
#5 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(57): Illuminate\Log\Writer->error(Object(UnexpectedValueException))
#6 /opt/snipe-it/app/Exceptio in /opt/snipe-it/bootstrap/cache/compiled.php on line 13906

PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/opt/snipe-it/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied' in /opt/snipe-it/bootstrap/cache/compiled.php:13906
Stack trace:
#0 /opt/snipe-it/bootstrap/cache/compiled.php(13836): Monolog\Handler\StreamHandler->write(Array)
#1 /opt/snipe-it/bootstrap/cache/compiled.php(13596): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /opt/snipe-it/bootstrap/cache/compiled.php(13694): Monolog\Logger->addRecord(400, Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#3 /opt/snipe-it/bootstrap/cache/compiled.php(13389): Monolog\Logger->error(Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#4 /opt/snipe-it/bootstrap/cache/compiled.php(13360): Illuminate\Log\Writer->writeLog('error', Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#5 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(57): Illum in /opt/snipe-it/bootstrap/cache/compiled.php on line 13906

---
#### Please confirm you have done the following before posting your bug report:
- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running - v3
- What OS and web server you're running Snipe-IT on - CentOS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual installation
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by elJoeyJojo** [comment]
i also checked this file "/opt/snipe-it/storage/logs/laravel.log" and it has the correct permissions to apache:apache just like the old configuration of v3.0 was
all the commands: 

php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan migrate
php artisan config:clear

EXCEPT php artisan migrate,

**Comment by snipe** [comment]
Are you running SELinux?

**Comment by elJoeyJojo** [comment]
@snipe i do but it's disabled, it's working just fine at the moment with v3.0

**Comment by snipe** [comment]
Is it disabled system-wide? If you've got the upgrade in a new directory, you may need to set it to permissive for the new directory. I'm 99% sure this is an SELinux issue (since you say the permissions are set correctly)

**Comment by elJoeyJojo** [comment]
i will try that today and see if it works

**Comment by elJoeyJojo** [comment]
same result: 

**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/opt/snipe-it/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied' in /opt/snipe-it/bootstrap/cache/compiled.php:13906
Stack trace:
#0 /opt/snipe-it/bootstrap/cache/compiled.php(13836): Monolog\Handler\StreamHandler->write(Array)
#1 /opt/snipe-it/bootstrap/cache/compiled.php(13596): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /opt/snipe-it/bootstrap/cache/compiled.php(13694): Monolog\Logger->addRecord(400, Object(UnexpectedValueException), Array)
#3 /opt/snipe-it/bootstrap/cache/compiled.php(13389): Monolog\Logger->error(Object(UnexpectedValueException), Array)
#4 /opt/snipe-it/bootstrap/cache/compiled.php(13360): Illuminate\Log\Writer->writeLog('error', Object(UnexpectedValueException), Array)
#5 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(57): Illuminate\Log\Writer->error(Object(UnexpectedValueException))
#6 /opt/snipe-it/app/Exceptio in /opt/snipe-it/bootstrap/cache/compiled.php on line 13906
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/opt/snipe-it/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied' in /opt/snipe-it/bootstrap/cache/compiled.php:13906
Stack trace:
#0 /opt/snipe-it/bootstrap/cache/compiled.php(13836): Monolog\Handler\StreamHandler->write(Array)
#1 /opt/snipe-it/bootstrap/cache/compiled.php(13596): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /opt/snipe-it/bootstrap/cache/compiled.php(13694): Monolog\Logger->addRecord(400, Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#3 /opt/snipe-it/bootstrap/cache/compiled.php(13389): Monolog\Logger->error(Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#4 /opt/snipe-it/bootstrap/cache/compiled.php(13360): Illuminate\Log\Writer->writeLog('error', Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#5 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(57): Illum in /opt/snipe-it/bootstrap/cache/compiled.php on line 13906

this is what the SELINUX file looks like:

$ cat /etc/sysconfig/selinux


# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#     enforcing - SELinux security policy is enforced.
#     permissive - SELinux prints warnings instead of enforcing.
#     disabled - No SELinux policy is loaded.
SELINUX=permissive
# SELINUXTYPE= can take one of these two values:
#     targeted - Targeted processes are protected,
#     mls - Multi Level Security protection.
SELINUXTYPE=targeted

This is what the Storage folder permissions look like

[snipeit@snipeit](Thu Oct 13 13:50:30)/opt/snipe-it/storage $ ls -la
total 28
drwxrwxr-x  7 apache  apache  4096 Oct  4 12:23 .
drwxrwxr-x 13 snipeit snipeit 4096 Oct 13 13:25 ..
drwxrwxr-x  3 apache  apache  4096 Oct  4 12:23 app
drwxrwxr-x  2 apache  apache  4096 Oct  4 12:23 debugbar
drwxrwxr-x  5 apache  apache  4096 Oct  4 12:23 framework
drwxrwxr-x  2 apache  apache  4096 Oct 13 13:44 logs
drwxrwxr-x  7 apache  apache  4096 Oct  4 12:23 private_uploads

**Comment by snipe** [comment]
What happens if you disable it?

**Comment by snipe** [comment]
Any update here?

**Comment by elJoeyJojo** [comment]
@snipe so i thought i would try to upgrade to 3.5 and same issue again, i disabled firewall and selinux and get the same "permission denied"  
Permission denied' in /opt/snipe-it/bootstrap/cache/compiled.php:13906

i'm literally not chaning anything else (N) any idea why this is happening? anyone else having this issue?

**Comment by elJoeyJojo** [comment]
@snipe funny enough, once i rename the folders back to what I have them, Snipe It works without any issue. Does /bootstrap folder need special permissions and what does line :13906 under compiled.php mean that is keeps looking at that?

Thanks
