### ISSUE TITLE
State field for location truncates to two characters

### ISSUE THREAD

**Issue by tullyhansen** [snipe/snipe-it#2766]
#### Expected Behavior (or desired behavior if a feature request)

Use VIC (Australian state) in the State field of a location.

-----

#### Actual Behavior

State field truncates to two characters (VI).

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running

v3.3.0-16-ge52a0f6

- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).

Yes

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
I believe this is fixed in the latest 3.5.0-beta

**Comment by djelusive** [comment]
Hi snipe, I know this is closed however I have the same problem on creating a new location including in the current demo build 3.6.2. I am using build 3.6.3
OS: Redhat Linux 7, Apache (httpd)
Manual installation
Not really an error but notification on trying to use 3 characters: The state may not be greater than 2 characters.
Location: https://demo.snipeitapp.com/admin/settings/locations/create

**Comment by snipe** [comment]
This is fixed in the upcoming v4

**Comment by djelusive** [comment]
Good News, because you have the state field in the database set to varchar(32), all I had to do was update app\Models\Location.php - line 20: 'state' =>'min:0|max:2', to max:3 and accepted the entry straight away. 

Glad to hear it is fixed in v4 though. Thanks Snipe :)
