### ISSUE TITLE
Is there a way to edit the data for a custom asset field

### ISSUE THREAD

**Issue by JordanC12** [snipe/snipe-it#2767]
I have been unsuccessful, in finding where on Snipe-IT I can edit the data for a custom asset field. (for example we have a custom asset field for Notes and Previous users (who used the computer). Every time I receive an asset from a user and am prepping it to be redeployed I have to delete the asset and import an "updated" asset file (for example adding another name to the previous users field) (and any notes on the condition of the computer in the notes section)? Am I missing where In Snipe-IT it lets me edit the data for a custom asset field without having to re-import the asset from my excel sheet?

Jordan

**Comment by snipe** [comment]
You can edit data for custom fields for an asset is in the Edit Asset page.

**Comment by JordanC12** [comment]
@snipe they do not show up for me when I select the asset and click edit...

**Comment by snipe** [comment]
Is the asset model the asset belongs to associated with the fieldset?

**Comment by JordanC12** [comment]
Yes. For example one of our custom asset fields is user's department. when I select edit asset, I dont even see an option to edit that field

**Comment by JordanC12** [comment]
edit. I think I was looking at the wrong thing. Thanks for the help
