### ISSUE TITLE
QR doesn't show on the assets 

### ISSUE THREAD

**Issue by ingandy13** [snipe/snipe-it#2771]
I cant see the qr only in this page.. someone can help me do know why ?

![image](https://cloud.githubusercontent.com/assets/5355719/19331286/d9278130-9098-11e6-8a70-edeac438d698.png)

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Do you have barcodes enabled in Admin > Settings?

**Comment by ingandy13** [comment]
Snipe it v3.3.0-16-ge52a0f6
it's on IIS 7, OS server 2008
I installed manual 
![image](https://cloud.githubusercontent.com/assets/5355719/19331373/7dc2bdcc-9099-11e6-86dd-a43059a2af39.png)

**Comment by snipe** [comment]
> If a stacktrace is provided in the error, include that too.
> Any errors that appear in your browser's error console.
> Include any additional information you can find in app/storage/logs and your webserver's logs.

**Comment by ingandy13** [comment]
this error does not create any error, just i if try to see the QR on new tab it show this.. 

![image](https://cloud.githubusercontent.com/assets/5355719/19331805/92d59ae8-909b-11e6-9f75-824b2f62d9d6.png)

**Comment by snipe** [comment]
> Include any additional information you can find in `app/storage/logs/laravel.log` and your webserver's logs.

**Comment by ingandy13** [comment]
the file it's here
[laravel.txt](https://github.com/snipe/snipe-it/files/525893/laravel.txt)

**Comment by snipe** [comment]
There's a lot in there, and I'm not sure which is relevant for this particular issue. Can you clear that file out and reload the page, and paste anything new that pops up in here?

**Comment by ingandy13** [comment]
I tried with different browser and it the same situation.

**Comment by snipe** [comment]
That's not the question I asked you. I'd like to see what's in your laravel.log, but only the new stiff that gets created when you trigger that error.

**Comment by itisnapanto** [comment]
I have the same Issue . 

cleaned Logfile attached.
[laravel-log.docx](https://github.com/snipe/snipe-it/files/533146/laravel-log.docx)

**Comment by ingandy13** [comment]
![image](https://cloud.githubusercontent.com/assets/5355719/19446227/a9d3c288-944c-11e6-910a-c9a9653f592e.png)

![image](https://cloud.githubusercontent.com/assets/5355719/19446271/e406c996-944c-11e6-9657-444383c0a4f8.png)

**Comment by delinski111** [comment]
During pre-flight, did the section regarding barcode library show as red, yellow or green?
During install, did you manually install a barcode creation library?
Can you also provide who has permissions on these folders?
~/snipe-it/storage/
~/snipe-it/public/uploads/barcodes/

**Comment by itisnapanto** [comment]
> During pre-flight, did the section regarding barcode library show as red, yellow or green?
I had no problems during the upgrade. It was all green


> During install, did you manually install a barcode creation library?
No. Except the mentioned commands during the upgrade

> Can you also provide who has permissions on these folders?
> ~/snipe-it/storage/
> ~/snipe-it/public/uploads/barcodes/
Permissions are the same as before upgrade

regards, 
Michael

**Comment by delinski111** [comment]
Have barcodes ever worked?

Pretty sure you will need to install either _gd_ or _imagick_. I am a linux user, so cannot really help with the how on doing that.

**Comment by itisnapanto** [comment]
Hey,

i had set the permissions again and now it is working . Thanks for your help.

/var/www/snipeit/public/uploads\barcodes

**Comment by ingandy13** [comment]
It had the permissions but it doesn't work yet

**Comment by itisnapanto** [comment]
Can you take a screenshot from your permissions ?

**Comment by snipe** [comment]
> During install, did you manually install a barcode creation library?

That shouldn't be necessary. Snipe-IT comes with a barcode creation library.
