### ISSUE TITLE
Regenerate new label after server migration

### ISSUE THREAD

**Issue by Allenvh** [snipe/snipe-it#2779]
Could you indicate me, if possible, how to regenerate the QR barcodes after a server migration? 

I have update it the .env but  QRs are still pointing to the test server. 

Thanks

**Comment by snipe** [comment]
You'll need to print new ones, or set up an htaccess redirect from the old server to the new,

**Comment by Allenvh** [comment]
I am trying to print new ones but they (the image) are still pointing to the old server. What am I missing ?

**Comment by snipe** [comment]
If you've updated the APP_URL in your .env and cleared your config cache, the URLs will update.
https://snipe-it.readme.io/docs/common-issues#changes-to-my-env-file-dont-seem-to-be-updating

**Comment by Allenvh** [comment]
Thanks, trying now

**Comment by Allenvh** [comment]
Some of the QRs updated but the other ones are some how different, any idea what could be happening? 
I am sorry for the pic, I am doing this from an IPad. It's a long story. 
![image](https://cloud.githubusercontent.com/assets/22819860/19455121/db8f3658-9489-11e6-9de1-cb56d103f504.jpg)

**Comment by Allenvh** [comment]
I also tried deleting the public/uploads/barcodes

**Comment by Allenvh** [comment]
I think I fixed the issue. 

I executed 
`php artisan route:clean`
And 
`php artisan cache:clear`

Restarted WAMP and the stubborn QRs got updated.
