### ISSUE TITLE
Generate Asset reports per user

### ISSUE THREAD

**Issue by StevenH91** [snipe/snipe-it#2780]
Hi Snipe It Community,

I'm wondering if there is a way to generate a report which contains all assets, software, consumables etc per user. The reason behind this is the current asset management method we have in place involves providing a printout to all staff each month to sign off on all the assets in their possession. This way we can keep track of all the assets quite regularly and it becomes the staff members responsibility. It's great that staff are able to sign in using their credentials imported from LDAP to see all the assets assigned to them but from what I can see there is no way for them to verify that all the assets are correct. Plus we have no way of policing if they sign in and verify their assets without collecting the signed form each month.

I know that you can export a CSV with all the information above but it would require someone to manually separate each staff members assets each month which is not ideal. Does anyone have a suggestion or know of a feature/workaround that may help? Any assiatnce is greatly appreciated.

Thanks!
- Version v3.4.0-9-g67315d8

**Comment by Bigben83** [comment]
How long would it take to add this feature to the current system, I'd be happy to donate towards the addition.
