### ISSUE TITLE
Installing Snipe-IT on Windows Server 2012 R2/IIS 8

### ISSUE THREAD

**Issue by proweb01** [snipe/snipe-it#2781]
Hey guys,

Trying to get Snipe-IT installed on IIS and keep running into road blocks... First issue is trying to generate a new key using "php artisan key:generate". The command appears to run, but gives me so success/error message and no key is generated anywhere. My .env file still shows "ChangeMe".
![untitled picture](https://cloud.githubusercontent.com/assets/14204030/19488952/26a4306e-9537-11e6-87be-2d7d3ad090be.png)

Also, when installing Composer, the documentation says to right-click and choose "Install". I don't have an "Install" option, so I just double-clicked and installed, which gave me an option to choose my PHP installation and finished.

I feel like there are some important steps I am missing, but the documentation is not obvious as to what they are since this seems to be aimed at a Linux install. I suspect once I get past this, there will be yet more roadblocks - but this is it for now. Thanks,

Brad

**Comment by korio77** [comment]
just try artisan key:generate without the php

You will hit some more roadblocks in the windows server installation, it took me a couple days of debugging and error solving to get it installed on my server.

But we are here to help :D so ask everytime you need anything.

Regarding the composer install, you did it right, at least is the same way i did it.

**Comment by proweb01** [comment]
I was able to get this working (finally!). I have documented everything perfectly and will be writing a detailed installation setup guide for Windows and publishing in the near future and will link it back to this thread for reference. I have been a Linux engineer my entire career, but unfortunately I am the only person in my company who could maintain and troubleshoot a Linux server - which left me in a bit of a bind with this install

**Comment by webtroter** [comment]
Any news on that guide? It could be useful over here. Thank you.

**Comment by mpb2k** [comment]
hello
@proweb01 I'm just wondering if we can expect the guide anytime soon. I used the old guide (which is no 404) but got stucked and tried again and now even that is gone....

Thanks

**Comment by snipe** [comment]
The URL has changed. That's documented. If you have a specific issue, post it. There is documentation on installing this on windows, so unless you have a specific problem, this thread is closed. If you have a specific problem, please check the github issues, the common issues, and the getting help docs.
