### ISSUE TITLE
`php artisan db:restore foobar.sql` is not defined

### ISSUE THREAD

**Issue by americanhanko** [snipe/snipe-it#2785]
#### Expected Behavior (or desired behavior if a feature request)

According to https://github.com/snipe/snipe-it/issues/1292 we should be able to restore an SQL backup with `php artisan db:restore foobar.sql`

-----

#### Actual Behavior

When we run the command, db:restore is not defined:

`[Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "db:restore" is not defined.
  Did you mean one of these?
      queue:restart
      db:seed`

It seems like the ability to restore a db is due to a PHP dependency that we do not have. I've included the contents of **composer.json** at the bottom in hopes that you might be able to see what is missing. If it is the case that we are missing a dependency, perhaps you might know why the dependency was not installed on our server. We thought we might be missing https://github.com/schickling/laravel-backup but could not run `composer require schickling/backup` as root (since we're running Snipe on a Docker container). When we manually added it to **composer.json** and ran `composer update` it had another dependency requirement (https://github.com/aws/aws-sdk-php-laravel#configuration) -- we decided to stop there...halp.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Snipe-IT version: **v3.4-14-g2a8ab06**
- PHP Version: **5.5.9-1ubuntu4.19**
- Laravel Version: **5.2.45**
- What OS and web server you're running Snipe-IT on: **LAMP server**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): **Docker**

```
{
  "name": "snipe/snipe-it",
  "description": "Open source asset management system built on Laravel.",
  "keywords": ["assets", "asset-management", "laravel"],
  "license": "AGPL-3",
  "type": "project",
      "require": {
      "php": ">=5.5.9",
      "laravel/framework": "5.2.*",
      "intervention/image": "dev-master",
      "league/csv": "~7.0",
      "maknz/slack": "dev-master",
      "erusev/parsedown": "dev-master",
      "fideloper/proxy": "^3.1",
      "guzzlehttp/guzzle": "6.2.1",
      "aws/aws-sdk-php-laravel": "~3.0",
      "tecnickcom/tc-lib-barcode": "dev-master",
      "laravelcollective/html" : "~5.0",
      "watson/validating": "^2.0",
      "doctrine/cache": "v1.5.4",
      "doctrine/common": "v2.5.3",
      "doctrine/dbal": "v2.4.2",
      "barryvdh/laravel-debugbar": "^2.1",
      "spatie/laravel-backup": "3.8.1",
      "misterphilip/maintenance-mode": "1.0.*",
      "neitanod/forceutf8": "dev-master"
    },
    "require-dev": {
      "fzaninotto/faker": "~1.4",
      "mockery/mockery": "0.9.*",
      "phpunit/phpunit": "~4.0",
      "squizlabs/php_codesniffer": "2.*",
      "phpspec/phpspec": "~2.1",
      "codeception/codeception": "2.1.*",
      "symfony/dom-crawler": "~3.0",
      "symfony/css-selector": "~3.0",
      "codeception/c3": "2.*"
    },
    "autoload": {
        "classmap": [
            "database",
            "app/Helpers/Helper.php"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php"
        ]
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "php artisan clear-compiled",
            "php artisan optimize"
        ],
        "pre-update-cmd": [
            "php artisan clear-compiled"
        ],
        "post-update-cmd": [
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist"
    },
    "minimum-stability": "stable"
}
```

**Comment by snipe** [comment]
That's no longer an option. (That thread was from last year, and several versions ago.) You'll need to restore via phpMyAdmin or mysqlimport.

**Comment by americanhanko** [comment]
Fair enough - thanks!
