### ISSUE TITLE
Add Attachments to License Entry

### ISSUE THREAD

**Issue by rmavery** [snipe/snipe-it#2786]
#### Expected Behavior (or desired behavior if a feature request)

`When adding a new software license, it would be very helpful to include an attachment with the entry for something like a copy of the invoice, or a document containing additional information for installing or downloading the software. `

-----

#### Actual Behavior

`There does not appear to be a way to include attachments with the 'License' entry`

-----

#### Please confirm you have done the following before posting your bug report:

- [ `N/A` ] I have enabled debug mode
- [ `YES` ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
`1.2.0-pre`
- What OS and web server you're running Snipe-IT on
`Ubuntu 16.04 LTS`
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
`Manual Install`
- If you're getting an error in your browser, include that error
`No Error`
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
`admin/licenses/xxx/edit`
- If a stacktrace is provided in the error, include that too.
`N/A`
- Any errors that appear in your browser's error console.
`N/A`
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
`N/A`
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
`N/A`
- Include what you've done so far in the installation, and if you got any error messages along the way.
`N/A`
- Indicate whether or not you've manually edited any data directly in the database
`N/A`

**Comment by snipe** [comment]
How is this different than the existing file upload capabilities for licenses?

<img width="790" alt="view_license_-_compatible_multi-state_core____snipe-it" src="https://cloud.githubusercontent.com/assets/197404/19544087/300bcb76-9631-11e6-85c0-3be4b6443093.png">

**Comment by rmavery** [comment]
Wow.    I am sorry for wasting your time.  I don't know how I missed that.   I actually rolled back to 2.1.0-pre, but this is certainly an incentive for us to push forward.    

Thanks for the reply.

**Comment by ovizii** [comment]
As I was just searching for the same I wanted to add that this feature is very non-intuitively placed. 

When creating a new license, I have a field for serial numbers but no upload field. Only after the license is created I can edit it and upload the license file.

**Comment by TroyShaw** [comment]
I'm searching for a similar issue too.

It would be fantastic to be able to upload files when creating things that can have files attached to them.
