### ISSUE TITLE
Label Generating fail

### ISSUE THREAD

**Issue by Allenvh** [snipe/snipe-it#2789]
#### Expected Behavior (or desired behavior if a feature request)

Generate a full page of labels with no errors.

---
#### Actual Behavior

Some labels do not load the QR code, back button takes you to the previous screen but the session is expired, log in necessary.

---
#### Please confirm you have done the following before posting your bug report:
- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running
  **3.4.0.9 g67315d8**
- What OS and web server you're running Snipe-IT on'
  Windows server 2012 R2 (WAMP)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  Manual
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
  Browser Console
  `
  Navigated to http://hwhr-snipe-01/hardware
  Navigated to http://hwhr-snipe-01/hardware/bulkedit
  Navigated to http://hwhr-snipe-01/hardware
  Navigated to http://hwhr-snipe-01/login
  `
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
  Once I got an error PHP 500 Internal Server Error (unable to replicate, no screenshots) 
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).

Unable to reproduce the error in demo, insufficient assets to reproduce error 
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
  Tested under different users, browsers and OS. Error happens 98% of the times, especially with over 25 labels. 
- Indicate whether or not you've manually edited any data directly in the database

No data edited, renamed the public\uploads\barcodes folder to have the program regenerate the QRs again.

**Comment by Allenvh** [comment]
![image](https://cloud.githubusercontent.com/assets/22819860/19571015/5cff6dce-96ca-11e6-9043-e04d6a985bfc.jpg)
Sorry for the pic, long story :)

**Comment by Allenvh** [comment]
I am not sure if you saw this ticket. Please help

**Comment by snipe** [comment]
@Allenvh we see all of the Github issues. Please be patient. As you can see, we have a lot of additional tickets to deal with besides yours. 

You haven't provided us with enough information here. If you try to open the image directly, does it throw an error? If so, what is the error? There is a 500 error in your screenshot, but as we asked in the original Github issue template, we need to know what the 500 error is, by way of your logs.

**Comment by snipe** [comment]
Also please make sure that `public/uploads/barcodes` is writable by the web server.

**Comment by Allenvh** [comment]
It is writable 

I am sorry for impatience. Let me know if I can help with something

**Comment by snipe** [comment]
>  If you try to open the image directly, does it throw an error? If so, what is the error? There is a 500 error in your screenshot, but as we asked in the original Github issue template, we need to know what the 500 error is, by way of your logs.

**Comment by Allenvh** [comment]
![2016-10-27_11-40-40](https://cloud.githubusercontent.com/assets/22819860/19774750/1ac73492-9c3c-11e6-80f3-5ee5dd43d20d.png)
This is exactly what I'm getting if I hit the back button it just logs me off.

**Comment by Allenvh** [comment]
I am checking the logs now to see of there is something to report there

**Comment by nrasmus** [comment]
I am also having this exact issue.  It seems that there is a timeout at play--like the browser times out trying to load the images before they are available to serve.  The weird thing is refreshing or browsing back does seem to kill the active session as described.  I'm on the latest master build (3.62)

**Comment by MineSQL** [comment]
I am having the issue as well.  This is application breaking feature for me and my organization, as we need to track physical assets. 

I tested a theory by removing the middleware for the hardware route group in app/Http/routes.php and I found the culprit. The web and auth middleware need to be thoroughly inspected to see exactly what is causing this bug. I suspect it has more to do with the auth middleware than the web but disabling both gives expected behaviour while just enabling web gives better results. Auth however breaks the functionality.

On the first load not all of the images load completely, however after the second/third all the images are loaded properly. I am also using LDAP authentication, which might play a role in this issue.

To reproduce this issue, I believe you need 50+ assets. This is most definitely a bug.

**Comment by snipe** [comment]
Can anyone using v4 tell me if this is still happening for them? We rewrote a lot of those routes, etc, so not sure if this issue is still valid in v4.
