### ISSUE TITLE
Only admin and superadmin can add accesories

### ISSUE THREAD

**Issue by Allenvh** [snipe/snipe-it#2792]
#### Expected Behavior (or desired behavior if a feature request)

All users without admin or super admin level and Accesories : Create, Grant, should be able to add accesories 
-----

#### Actual Behavior

"Create" Button does not show

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
V3.4.0-9 -g67315d8
- What OS and web server you're running Snipe-IT on
Window server 2012 r2 WAMP
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
Does not work in demo
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
Take the user off the group and assign granular permissions. Tested different users 
- Indicate whether or not you've manually edited any data directly in the database

**Comment by Allenvh** [comment]
I found thi error pointing to accesories.create. I thought it could help
![image](https://cloud.githubusercontent.com/assets/22819860/19599233/c48c932e-976d-11e6-8758-577e4cac96ab.png)

**Comment by Allenvh** [comment]
Any idea what's the fix fo this issue?

**Comment by snipe** [comment]
When we have an update, we'll update the ticket.

**Comment by snipe** [comment]
You'll need to re-save the user's permissions for this fix to work

**Comment by Allenvh** [comment]
Thanks worked like a charm.
