### ISSUE TITLE
[Feature Request] Include Purchase Date in Asset Report 

### ISSUE THREAD

**Issue by delize** [snipe/snipe-it#2794]
It appears that the Asset Report (/reports/assets) does not include the purchase date. It is not a selectable column at all. 

If I go to /hardware it does show purchase date.
Please include the Purchase Date in the Asset Report as this is definitely helpful information to have when downloading an asset report.

**Comment by delinski111** [comment]
You need to select it manually in the column view tab om the right side of the page.

![image](https://cloud.githubusercontent.com/assets/22087997/19621373/629a9a7a-985e-11e6-9715-ba9bc1aeb833.png)

**Comment by delize** [comment]
While this appears for me as a Superadmin, this did not appear for my FInance employee that has read only access to the reports and assets view.

**Comment by snipe** [comment]
There is nothing in the code that gates who can see that particular field. Try having your finance person clear their browser cache.
