### ISSUE TITLE
[Feature Request] Asset Warranty as Date Picker

### ISSUE THREAD

**Issue by fltchr** [snipe/snipe-it#2795]
#### Expected Behavior (or desired behavior if a feature request)

When adding a new asset, it would be ideal to be able to select a warranty end date (as the purchase date is selected now). A dedicated field for a warranty number would be nice as well though we can accomplish this through a custom field or place it in the notes field.

---
#### Actual Behavior

Currently a warranty must be entered as a number of months and is then calculated off of the purchase date.

---

**Comment by snipe** [comment]
This seems like a more confusing UX though. We use months because you usually buy an X-month-warranty, so it's easier than having to calculate what that date is.
