### ISSUE TITLE
Adding-a-user error :  SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO)

### ISSUE THREAD

**Issue by studentforever-yahoo** [snipe/snipe-it#2798]
Hi, i am having this when i try to create the user as per https://snipe-it.readme.io/docs/adding-a-user

![image](https://cloud.githubusercontent.com/assets/22605021/19632006/d9531a94-99ed-11e6-9b5d-62c2f42f83af.png)

after adding the DB username and password in the .env , i am getting this now:

 [Illuminate\Database\QueryException]
 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.users' doesn't exist (SQL: s
 elect count(*) as aggregate from `users` where `username` = username123 and `deleted_at` is null an
 d `id` != 0)

 [PDOException]
 SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.users' doesn't exist

guide. Thanks.

**Comment by snipe** [comment]
Do you actually have a user's table? Did you run through the setup? Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
