### ISSUE TITLE
Can't get a pre-flight page

### ISSUE THREAD

**Issue by studentforever-yahoo** [snipe/snipe-it#2799]
hi, i have started a clean install of following:

snipe-it on IIS Server
MariaDB

all steps here completed:
- https://snipe-it.readme.io/docs/configuration DONE
- https://snipe-it.readme.io/docs/install-dependencies DONE
- .env file rename and edit DONE
- Key created
- composer installed all components
- IIS binding complete
- manual MariaDB database created
  -PHP extension=php_fileinfo.dll added
- folder permissions completed and given to IUSR

![image](https://cloud.githubusercontent.com/assets/22605021/19632069/a98cad1a-99ee-11e6-8e5a-c61f7b6a1fd9.png)

![image](https://cloud.githubusercontent.com/assets/22605021/19632089/c54f45a8-99ee-11e6-8974-f78d0be0f26d.png)
- my smtp server does not require any username and password, this was my other question.

**Comment by snipe** [comment]
That second screenshot is broken - what's the actual error you're running into?

**Comment by studentforever-yahoo** [comment]
Nothing. I don't get any errors
Just blank page


Ignore typo errors. Sent from my mobile device

Thanks

**Comment by snipe** [comment]
Check that the storage directory (and subdirectories) are writable. If they are, check your web server logs - there has to be an error somewhere.

Also that second screenshot doesn't make sense. That looks like the contents of the public directory, not the entire app.
