### ISSUE TITLE
Feature for License & Assets & Warranty

### ISSUE THREAD

**Issue by maradwan** [snipe/snipe-it#280]
The issue I have many servers has warranty expire and software license expire without notice. Also hardware support & warranty  
we add a feature that you need to write when the license expire also it will be good to send email as reminder before 60 days as yellow color in report and 30 days red color.

So we can add new Category as Warranty also Support with expire date
Thanks
Mohamed

**Comment by snipe** [comment]
Warrantee expiration emails are now on the `develop` branch. 

To set up the cron to run every day, set up your crontab as:

`@daily /path/to/php php artisan alerts:expiring`

To set it to run every week, use:

`@weekly /path/to/php php artisan alerts:expiring`
