### ISSUE TITLE
[Bug] Setting DB_PREFIX prevents installation

### ISSUE THREAD

**Issue by bcorcoran** [snipe/snipe-it#2800]
#### Expected Behavior

Configured `.env` file with DB_PREFIX so that snipe-it tables have their own "namespace".

-----

#### Actual Behavior

Installation fails after pre-flight test due to setting DB_PREFIX because it cannot find a hard-coded table. (I'm sorry I don't know which one because I didn't write it down at the time)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.4-14-g2a8ab06
- What OS and web server you're running Snipe-IT on: Ubuntu 16.04 / nginx
- What method you used to install Snipe-IT: manual install

I know for sure that this is an issue with setting DB_PREFIX because I tried the following scenarios:

1. Install with DB_PREFIX set (fail)
2. Deleted DB tables, then installed with `DB_PREFIX=null` (success)
3. Deleted DB tables, then installed with DB_PREFIX set (fail)

Ultimately I installed with DB_PREFIX=null which I did not prefer, but I needed to get the app running.

**Comment by snipe** [comment]
Please check the error log to see if you can find a more specific error.

**Comment by bcorcoran** [comment]
First error: 

PDOException in Connection.php line 333:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'XXXXX_snipeit.asset_logs' doesn't exist

Second error:

QueryException in Connection.php line 729:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'XXXXX_snipeit.asset_logs' doesn't exist (SQL: select invitation.id AS invitation_id, acceptance.id AS acceptance_id FROM asset_logs invitation INNER JOIN asset_logs acceptance ON (invitation.checkedout_to=acceptance.checkedout_to AND invitation.asset_id=acceptance.asset_id) WHERE invitation.action_type="checkout" AND acceptance.action_type="accepted")

Note where it tries to reference `asset_logs` instead of `$DB_PREFIXasset_logs`

The DB tables were created correctly, so I suspect the model or query (without looking into it) is just not applying the prefix.

**Comment by snipe** [comment]
That doesn't really make sense for setup though. We don't write to asset_logs on setup.

**Comment by bcorcoran** [comment]
Unless I misunderstand you, it's trying to select from asset_logs based on the above error. It's reproducible... seeing as it's happened twice on two different servers. 

The steps I use are:

1. `git clone https://github.com/snipe/snipe-it`
2. `cd snipe-it`
3. `cp .env.example .env`
4. *configure .env file* (set DB_PREFIX=someprefix_)
5. `composer install --no-dev --prefer-source`
6. `php artisan key:generate`
7. *go to setup url and try to proceed past pre-flight*

**Comment by snipe** [comment]
What stage in pre-flight can you get to though?

**Comment by bcorcoran** [comment]
I can't get past pre-flight. The error occurs after creating DB tables (as verified by manually checking the database) but before getting to the confirmation page that the tables were created.

**Comment by snipe** [comment]
Okay, so it's getting to migrations.  I think I found it. Hold please for a fix.

**Comment by snipe** [comment]
Please pull the latest from master and see if that resolves your issue.
