### ISSUE TITLE
Asset - List all not working after choosed "showing 100 rows"

### ISSUE THREAD

**Issue by ngochunghvn** [snipe/snipe-it#2801]
#### Expected Behavior (or desired behavior if a feature request)

Showing 100 rows asset/page

---
#### Actual Behavior

Showing page with no data

---
#### Please confirm you have done the following before posting your bug report:
- [v ] I have enabled debug mode
- [v ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT :Version v3.4-14-g2a8ab06
- OS and web server: Centos 7
- Method used to install Snipe-IT: install.sh
  I showed no data in List All Asset
  ![list all asset](https://cloud.githubusercontent.com/assets/23025010/19636754/86a2aa64-99f5-11e6-8a2c-d3ffe4014360.png)

But, i had so many Assets, pls show my Deployed Assets

![deployed asset](https://cloud.githubusercontent.com/assets/23025010/19636766/8ddb3850-99f5-11e6-9273-31ec2d1ebd68.png)

**Comment by delinski111** [comment]
Have you Tried to change it to 50, or 200 per page?
Try clearing Cookies in browser
Restart server? Are all the assets actually in the database, and is it just the web interface, or are they actually gone.
Make sure you do not have a leading space in the search box.

**Comment by snipe** [comment]
We need more information here, including any errors that might be in your error logs (which we asked for in the issue template, but you deleted that part.)

**Comment by ngochunghvn** [comment]
@delinski111 Thanks for your help, but it's page module don't showing in List All page, like you see my attach photo.
@snipe I will try to find it. I deleted it cause i am not developer and so hard to looking for something as snipe template.

**Comment by delize** [comment]
If you click the refresh button near the right hand of the page, do the assets show? This happens to me sometimes, the assets are in the database, but the page just doesn't load them initially. After clicking the refresh button, they appear.

**Comment by ngochunghvn** [comment]
Sorry for along time i don't come back.
This issue has been solved when i click on sorted by any column.
This issue will be closed now.
