### ISSUE TITLE
Problems with configuration of Ldap

### ISSUE THREAD

**Issue by itisnapanto** [snipe/snipe-it#2804]
Hello,

i have unfortunately a problem the users by LDAP to import.
Perhaps someone has an example configuration?

A test with the LDP.exe was successful.

![snipe2](https://cloud.githubusercontent.com/assets/20791870/19649572/a2a9ff94-9a06-11e6-91cb-631f3cbe3fbd.jpg)
![snipe1](https://cloud.githubusercontent.com/assets/20791870/19649571/a2a666b8-9a06-11e6-8c04-6d858772df16.jpg)

regards,
Michael

**Comment by snipe** [comment]
It's saying it cannot contact the LDAP server, so you've either got something wrong with your LDAP hostname, or you've got firewall rules or something preventing the server Snipe-IT is running on from talking to your LDAP server.

**Comment by itisnapanto** [comment]
I had also thought with the firewall. I have no extra installed a firewall on the Ubuntu. The windows friewall is of. The hostname is correct. A test with an LDAP viewer does success.

Generates Snipe-IT a log, where I can run fault analysis? The laravel log is empty.

regards

**Comment by itisnapanto** [comment]
okay i found the problem. it was a missing DNS entry of the DC in the hosts file of ubuntu.
entry set and now it is working.

**Comment by snipe** [comment]
Glad you got it sorted!
