### ISSUE TITLE
Custom-Fields (URL format) and custom protocols

### ISSUE THREAD

**Issue by diekmanu** [snipe/snipe-it#2805]
Hi,

is there a way to specify custom protocols (rdp:// e.g.). Validation only works when entering http(s)/ftp links. ssh:// seems to work too.

Thanks!

**Comment by snipe** [comment]
You would need to specify a regex that would meet your conditions. It's not currently possible to set custom protocols.

**Comment by diekmanu** [comment]
But then I loose the ability to have hyperlinks right?

Can you tell me where I can find the custom field validation in source? Or is this something "hardcoded" in Laravel?

Would be awesome to just click on an assets custom field and launch an rdp-ression.

**Comment by diekmanu** [comment]
Okay, I found it.
Thanks anyways.

**Comment by dmeltzer** [comment]
If you modify it, feel free to submit a pull request.  Extra functionality is always good!
