### ISSUE TITLE
PHP Fatal error:  Class 'Illuminate\Foundation\Application' not found

### ISSUE THREAD

**Issue by IDeyris** [snipe/snipe-it#2806]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

---
#### Actual Behavior

(what actually happens goes here)

---
#### Please confirm you have done the following before posting your bug report:
- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running
  I'm "running" the newest -> v3
- What OS and web server you're running Snipe-IT on
  Ubuntu 14
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  i went for the install.sh
- If you're getting an error in your browser, include that error
  Blank page - no error 
## \- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
  none
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
  no
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

Pls find the Apache Logs here:

[Mon Oct 24 14:00:19.830032 2016] [core:notice] [pid 6913] AH00094: Command line: '/usr/sbin/apache2'
[Mon Oct 24 14:08:33.507605 2016] [:error] [pid 6920] [client 10.1.20.4:63223] script '/var/www/html/snipeit/public/phpinfo.php' not found or unable to stat
[Mon Oct 24 14:08:40.675542 2016] [:error] [pid 6921] [client 10.1.20.4:63222] PHP Fatal error:  Class 'Illuminate\Foundation\Application' not found in /var/www/html/snipeit/bootstrap/app.php on line 14
[Mon Oct 24 14:08:42.550744 2016] [:error] [pid 6917] [client 10.1.20.4:63819] PHP Fatal error:  Class 'Illuminate\Foundation\Application' not found in /var/www/html/snipeit/bootstrap/app.php on line 14
[Mon Oct 24 14:08:47.302182 2016] [:error] [pid 6919] [client 10.1.20.4:63820] PHP Fatal error:  Class 'Illuminate\Foundation\Application' not found in /var/www/html/snipeit/bootstrap/app.php on line 14
[Mon Oct 24 14:08:55.787551 2016] [:error] [pid 6920] [client 10.1.20.4:63822] PHP Fatal error:  Class 'Illuminate\Foundation\Application' not found in /var/www/html/snipeit/bootstrap/app.php on line 14
[Mon Oct 24 14:13:08.056297 2016] [mpm_prefork:notice] [pid 6913] AH00169: caught SIGTERM, shutting down
[Mon Oct 24 14:13:09.046250 2016] [mpm_prefork:notice] [pid 7028] AH00163: Apache/2.4.10 (Ubuntu) PHP/5.5.9-1ubuntu4.20 configured -- resuming normal operations
[Mon Oct 24 14:13:09.046332 2016] [core:notice] [pid 7028] AH00094: Command line: '/usr/sbin/apache2'
[Mon Oct 24 14:13:21.010664 2016] [:error] [pid 7034] [client 10.1.20.4:53183] PHP Fatal error:  Class 'Illuminate\Foundation\Application' not found in /var/www/html/snipeit/bootstrap/app.php on line 14
[Mon Oct 24 14:13:23.389350 2016] [:error] [pid 7033] [client 10.1.20.4:53184] PHP Fatal error:  Class 'Illuminate\Foundation\Application' not found in /var/www/html/snipeit/bootstrap/app.php on line 14
[Mon Oct 24 14:13:23.660403 2016] [:error] [pid 7036] [client 10.1.20.4:53185] PHP Fatal error:  Class 'Illuminate\Foundation\Application' not found in /var/www/html/snipeit/bootstrap/app.php on line 14
[Mon Oct 24 14:13:23.893528 2016] [:error] [pid 7035] [client 10.1.20.4:53186] PHP Fatal error:  Class 'Illuminate\Foundation\Application' not found in /var/www/html/snipeit/bootstrap/app.php on line 14
[Mon Oct 24 14:13:24.120418 2016] [:error] [pid 7032] [client 10.1.20.4:53187] PHP Fatal error:  Class 'Illuminate\Foundation\Application' not found in /var/www/html/snipeit/bootstrap/app.php on line 14
- Include what you've done so far in the installation, and if you got any error messages along the way.
  I did everything, unthil the composer part comes and there i seem to be stucked.
- Indicate whether or not you've manually edited any data directly in the database
  No

Thank you for you time and the efforts for the whole project! 

Dear regards Deyris

**Comment by snipe** [comment]
Try:

```
php artisan clear-compiled
composer dump-autoload
```

**Comment by IDeyris** [comment]
Hey Snipe, thanks for your fast reply
Itryed the following commands and with the first one I end up at the same Error messag

itne@ch-sv02151:/var/www/html/snipeit$ php artisan clear-compiled
PHP Fatal error:  Class 'Illuminate\Foundation\Application' not found in /var/www/html/snipeit/bootstrap/app.php on line 14
--------------------------------------------------------------------------------
itne@ch-sv02151:/var/www/html/snipeit$ php composer.phar dump-autoload
Generating autoload files

**Comment by snipe** [comment]
Very bizarre. I haven't seen this before. Try:

`composer update --no-scripts`

**Comment by IDeyris** [comment]
it is quite strange, that now an ssl error is coming up, but when i check everything it seem to be correct 

itne@ch-sv02151:/var/www/html/snipeit$ php composer.phar update --no-scripts
Loading composer repositories with package information


  [Composer\Downloader\TransportException]
  The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
  error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
  failed to open stream: Cannot connect to HTTPS server through proxy

**Comment by IDeyris** [comment]
drwxrwxrwx 13 www-data root    4096 Oct 27 17:58 .
drwxr-xr-x  3 root     root    4096 Oct 24 13:48 ..
drwxrwxrwx 12 www-data root    4096 Sep 29 20:37 app
-rwxrwxrwx  1 www-data root    1646 Oct 24 17:31 artisan
drwxrwxrwx  3 www-data root    4096 Oct 27 11:43 bootstrap
**-rwxrwxrwx  1 www-data root    9210 Sep 29 20:37 c3.php
-rwxrwxrwx  1 www-data root     242 Sep 29 20:37 circle.yml
-rwxrwxrwx  1 www-data root     511 Sep 29 20:37 codeception.yml**
-rwxrwxrwx  1 www-data root    2082 Oct 27 11:37 composer.json
-rwxrwxrwx  1 www-data root 1704783 Oct 24 13:26 composer.phar
drwxrwxrwx  2 www-data root    4096 Sep 29 20:37 config
drwxrwxrwx  5 www-data root    4096 Oct 24 18:08 database
drwxrwxrwx  2 www-data root    4096 Sep 29 20:37 docker
-rwxrwxrwx  1 www-data root     614 Sep 29 20:37 docker.env
-rwxrwxrwx  1 www-data root    2897 Sep 29 20:37 Dockerfile
-rwxrwxrwx  1 www-data root      67 Sep 29 20:37 .dockerignore
-rwxrwxr-x  1 itne     itne    1892 Oct 24 16:04 .env
-rwxrwxrwx  1 www-data root    1833 Sep 29 20:37 .env.example
-rwxrwxrwx  1 www-data root    1764 Sep 29 20:37 .env.testing
-rwxrwxrwx  1 www-data root    1758 Sep 29 20:37 .env.testing-ci
-rwxrwxrwx  1 www-data root    1711 Sep 29 20:37 gh-changelog.php
-rwxrwxrwx  1 www-data root      11 Sep 29 20:37 .gitattributes
drwxrwxrwx  2 www-data root    4096 Sep 29 20:37 .github
-rwxrwxrwx  1 www-data root     756 Sep 29 20:37 .gitignore
-rwxrwxrwx  1 www-data root    1486 Sep 29 20:37 gulpfile.js
-rwxrwxrwx  1 www-data root     251 Sep 29 20:37 .htaccess
-rwxrwxrwx  1 www-data root    1064 Sep 29 20:37 index.html
-rwxrwxrwx  1 www-data root   34519 Sep 29 20:37 LICENSE
-rw-rw-r--  1 itne     itne       0 Oct 27 11:59 locate
-rwxrwxrwx  1 www-data root     873 Sep 29 20:37 phpunit.xml
drwxrwxrwx  6 www-data root    4096 Oct 24 15:47 public
-rwxrwxrwx  1 www-data root    3936 Sep 29 20:37 README.md
drwxrwxrwx  6 www-data root    4096 Sep 29 20:37 resources
-rwxrwxrwx  1 www-data root     567 Sep 29 20:37 server.php
drwxrwxrwx  7 www-data root    4096 Sep 29 20:37 storage
drwxrwxrwx  9 www-data root    4096 Sep 29 20:37 tests
-rwxrwxrwx  1 www-data root    1895 Sep 29 20:37 .travis.yml
-rw-rw-r--  1 itne     itne       0 Oct 24 16:02 true,
drwxrwxrwx  5 www-data root    4096 Oct 27 10:31 vendor



that is my **/var/www/html/snipeit** Directory...... and i think not all of my dependencies are in place, as i ran the composer installation command he installed codeception(i made it bold in the list) but i think there should be mutch more to install if i look to the **composer.json** file, and thats why the any operation with **artisan**file  or so fails with :
 PHP Fatal error: Class 'Illuminate\Foundation\Application' not found in /var/www/html/snipeit/bootstrap/app.php on line 14

So if i would be able to run `php composer.phar install` correctly, it would be working i think 

And that means i need to fix this first i think : 
itne@ch-sv02151:/var/www/html/snipeit$ php composer.phar update --no-scripts
 Loading composer repositories with package information

 Composer\Downloader\TransportException]
 The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:
 error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
 failed to open stream: Cannot connect to HTTPS server through proxy

**Comment by snipe** [comment]
Can you check your system clock on the server? Mismatched clocks can actually cause all kinds of mess with SSL.

Also check out this link to possibly fix your local SSL:
http://stackoverflow.com/questions/28249081/composer-error14090086ssl-routinesssl3-get-server-certificatecertificat/34192495

If you can apply that fix, the composer install should work normally I think.

**Comment by IDeyris** [comment]
Thank you for your help, I had en issue with the Laravel - so i ensured that the PHP -Framework is getting reinstalled properly und ita running correctly. After that, i was able to run the composer aso.. so I got to the Pre-Flight page.

Everythink looked fine and the boxes where all checked with green maks... everything seemed fine so far... Thank i set up the Superuser for Snipeit(GUI). After that i got redirected to http://example/login 
and there i cant login... When i click on Login it just turns into a bank page ...no error nothing, I dont get redirected to some other page or something. Its still http://example/login, but in blank 

my PHP Debug Bar showed me following: 
Auth:
webarray:2 [ "name" => "Guest" "user" => array:1 [ "guest" => true ] ]
apiarray:2 [ "name" => "Guest" "user" => array:1 [ "guest" => true ] ]
Query:
select * from information_schema.tables where table_schema = 'snipeit' and table_name = 'users'560μs/bootstrap/cache/compiled.php:6325snipeit

select * from information_schema.tables where table_schema = 'snipeit' and table_name = 'settings'340μs/bootstrap/cache/compiled.php:6325snipeit

select count(*) as aggregate from `users`210μs/app/Models/Setting.php:65snipeit
select * from information_schema.tables where table_schema = 'snipeit' and table_name = 'settings'430μs/bootstrap/cache/compiled.php:6325snipeit


APACHE 2 LOGS:

10.1.20.4 - - [04/Nov/2016:17:13:38 +0100] "GET / HTTP/1.1" 302 1273 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:13:38 +0100] "GET /login HTTP/1.1" 200 6943 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:20 +0100] "GET /login HTTP/1.1" 200 5948 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:20 +0100] "GET /assets/css/bootstrap.min.css HTTP/1.1" 200 20221 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:20 +0100] "GET /login HTTP/1.1" 200 5968 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:20 +0100] "GET /assets/css/bootstrap.min.css HTTP/1.1" 200 20221 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:20 +0100] "GET /assets/css/font-awesome.min.css HTTP/1.1" 200 6579 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:20 +0100] "GET /assets/js/plugins/select2/select2.min.css HTTP/1.1" 200 2256 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:20 +0100] "GET /assets/js/plugins/colorpicker/bootstrap-colorpicker.min.css HTTP/1.1" 200 1218 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:20 +0100] "GET /login HTTP/1.1" 200 5977 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:21 +0100] "GET /assets/css/bootstrap.min.css HTTP/1.1" 200 20221 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:21 +0100] "GET /assets/css/font-awesome.min.css HTTP/1.1" 200 6579 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:21 +0100] "GET /assets/js/plugins/select2/select2.min.css HTTP/1.1" 200 2256 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:21 +0100] "GET /assets/js/plugins/colorpicker/bootstrap-colorpicker.min.css HTTP/1.1" 200 1218 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:21 +0100] "GET /assets/js/plugins/datepicker/bootstrap-datepicker.css HTTP/1.1" 200 1840 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:21 +0100] "GET /assets/js/plugins/jvectormap/jquery-jvectormap-1.2.2.css HTTP/1.1" 200 685 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:21 +0100] "GET /assets/css/AdminLTE.min.css HTTP/1.1" 200 14872 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:21 +0100] "GET /login HTTP/1.1" 200 5976 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:21 +0100] "GET /assets/css/bootstrap.min.css HTTP/1.1" 200 20221 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:21 +0100] "GET /assets/css/font-awesome.min.css HTTP/1.1" 200 6579 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:21 +0100] "GET /assets/js/plugins/select2/select2.min.css HTTP/1.1" 200 2256 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:21 +0100] "GET /assets/js/plugins/colorpicker/bootstrap-colorpicker.min.css HTTP/1.1" 200 1218 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:21 +0100] "GET /assets/js/plugins/datepicker/bootstrap-datepicker.css HTTP/1.1" 200 1840 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:21 +0100] "GET /assets/js/plugins/jvectormap/jquery-jvectormap-1.2.2.css HTTP/1.1" 200 685 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:21 +0100] "GET /assets/css/AdminLTE.min.css HTTP/1.1" 200 14872 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:21 +0100] "GET /assets/css/skins/skin-blue.css HTTP/1.1" 200 1151 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:21 +0100] "GET /assets/css/bootstrap-table.css HTTP/1.1" 200 2317 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
10.1.20.4 - - [04/Nov/2016:17:21:21 +0100] "GET /build/assets/css/app-de75b6d10a.css HTTP/1.1" 200 19777 "http://160.219.16.55/login" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"

APACHE 2 ERROR LOG

[Fri Nov 04 18:02:26.792112 2016] [:error] [pid 1557] [client 10.1.20.4:49816] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/html/snipeit/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied' in /var/www/html/snipeit/bootstrap/cache/compiled.php:13906\nStack trace:\n#0 /var/www/html/snipeit/bootstrap/cache/compiled.php(13836): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/snipeit/bootstrap/cache/compiled.php(13596): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/html/snipeit/bootstrap/cache/compiled.php(13694): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)\n#3 /var/www/html/snipeit/bootstrap/cache/compiled.php(13389): Monolog\\Logger->error(Object(UnexpectedValueException), Array)\n#4 /var/www/html/snipeit/bootstrap/cache/compiled.php(13360): Illuminate\\Log\\Writer->writeLog('error', Object(UnexpectedValueException), Array)\n#5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(57): Illuminate\\Log\\Writer->error in /var/www/html/snipeit/bootstrap/cache/compiled.php on line 13906, referer: http://160.219.16.55/login
[Fri Nov 04 18:02:26.792626 2016] [:error] [pid 1557] [client 10.1.20.4:49816] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/html/snipeit/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied' in /var/www/html/snipeit/bootstrap/cache/compiled.php:13906\nStack trace:\n#0 /var/www/html/snipeit/bootstrap/cache/compiled.php(13836): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/snipeit/bootstrap/cache/compiled.php(13596): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/html/snipeit/bootstrap/cache/compiled.php(13694): Monolog\\Logger->addRecord(400, Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#3 /var/www/html/snipeit/bootstrap/cache/compiled.php(13389): Monolog\\Logger->error(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#4 /var/www/html/snipeit/bootstrap/cache/compiled.php(13360): Illuminate\\Log\\Writer->writeLog('error', Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#5 /var/www/html/snipeit/vendor/laravel/frame in /var/www/html/snipeit/bootstrap/cache/compiled.php on line 13906, referer: http://160.219.16.55/login

**Comment by IDeyris** [comment]
I Just tried to Login with my new created User from the Pre-Flight Setup
(I'm sorry about the mess of logs and the time passed sinece the last comment)

**Comment by IDeyris** [comment]
Oh i forgot! I have disabled LDAP over the console to ensure ti is looking for the local user in the Snipe DB to authenticate

**Comment by ajita-asthana** [comment]
I am facing the same problem, can anyone help?

**Comment by benjdiasaad** [comment]
I'm facing the same prblm, someone have solution about that ?

**Comment by truyennhan1121995** [comment]
Fatal error: Uncaught Error: Class 'Illuminate\Foundation\Application' not found in C:\xampp\htdocs\blog\bootstrap\app.php:14 Stack trace: #0 C:\xampp\htdocs\blog\public\index.php(38): require_once() #1 {main} thrown in C:\xampp\htdocs\blog\bootstrap\app.php on line 14

I want to solve this problem

**Comment by praveenrambalu** [comment]
same issue @truyennhan1121995

**Comment by mukesh17mj** [comment]
Class 'Illuminate\Foundation\Application' not found => Same issue, even tried with composer install --no-scripts. Still the same problem.

**Comment by fieryjustice** [comment]
+1 for having the same problem.

**Comment by snipe** [comment]
@mukesh17mj @fieryjustice This is a thread from 2016. I'm quite certain whatever the original issue was no longer applies here, despite having a similar error message. If one of you could open a new issue and include the info from the issues template, that would be a big help in resolving your issue.

**Comment by BR99999** [comment]
I face the same problem, Any help?

**Comment by Artapel** [comment]
Same issue, im on 7.0.11 fresh install using install.sh as per download page on snipe-it website using Rocky9
