### ISSUE TITLE
[Feature Request] Serial Number Field in Components (or custom fields)

### ISSUE THREAD

**Issue by skleinau** [snipe/snipe-it#2809]
#### Expected Behavior (or desired behavior if a feature request)

Behavior is currently as it should be but we need the field set to be extended.

-----

#### Actual Behavior

Behavior is as currently expected but we do track a lot of components like Hardware that is build into other assets and needs to be tracked by serial number to be identified (RAM, GFX, etc.). 

Currently we are registering them as assets themselves and it is hard to keep track and consistency as they are assigned to users instead of assets. Since 3.0 we have now components but can't use it as the serial field is missing.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 
**-> v3.3.0-3-g7ef4f23**

- What OS and web server you're running Snipe-IT on 
**-> Ubuntu 14.04**

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) 
**-> No error**

- If you're getting an error in your browser, include that error
**-> No error**

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
**-> No error**

- If a stacktrace is provided in the error, include that too.
**-> No error**

- Any errors that appear in your browser's error console.
**-> No Error**

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
**-> No error**

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
**-> No error**

- Include what you've done so far in the installation, and if you got any error messages along the way.
**-> No error**

- Indicate whether or not you've manually edited any data directly in the database
**-> Not at all**

**Comment by snipe** [comment]
I think we have some other tickets dealing with custom fields in other parts of the site. It's all in the pipeline.

**Comment by snipe** [comment]
We'll still be extending components out with custom fields but I've added serial number to them for now. The components section is new and still needs a lot of UX and process love.
