### ISSUE TITLE
Licenses: Checkin Permission by Groups

### ISSUE THREAD

**Issue by cgresser** [snipe/snipe-it#2810]
Hey,

i think i found a little issue. In the group view for permssions admin/groups/X/edit it didn't find the License: Checkin permission, all other permissions are working.

Version: 3.5.beta2

Thanks for the great work and system!

**Comment by snipe** [comment]
We rolled checkin into checkout, so if you enable them to checkout, they should be able to checkin.

**Comment by snipe** [comment]
(We could make that clearer in the UI though)

**Comment by blackout1231** [comment]
To add to this, I created a test user as Admin with full permissions down the line, that person can check out a license, but cannot check it back in.

**Comment by snipe** [comment]
Fixed on develop now

**Comment by blackout1231** [comment]
I can verify that without changing this users permissions, I now have the Check-In option, however when I attempt to do so, I get the below error
![image](https://user-images.githubusercontent.com/34345402/33786932-a5cbc802-dc30-11e7-8cb7-14c14aed5eba.png)
![image](https://user-images.githubusercontent.com/34345402/33786949-b3679982-dc30-11e7-96af-4e0edfda50c0.png)

Is there anything I need to do on my end to resolve? Apologies in advance, I am new to this type of thing, and am learning as I go. I am doing my best to do my due diligence prior to posting as I learn the etiquette for posting here =)

**Comment by snipe** [comment]
>  I am doing my best to do my due diligence prior to posting as I learn the etiquette for posting here =)

![raw](https://user-images.githubusercontent.com/197404/33787107-9ef13856-dc20-11e7-8871-8c8611fb6e60.gif)

Seriously, you're doing fine. I do appreciate being concerned about that though - it's more than we often get ;)

Give it a go now please?

**Comment by blackout1231** [comment]
Same issue unfortunately =(
![image](https://user-images.githubusercontent.com/34345402/33787606-a51e670e-dc33-11e7-81ab-eadb9e977036.png)

Maybe I didn't apply the update correctly..

**Comment by snipe** [comment]
Are you on the develop branch or master?

**Comment by snipe** [comment]
Try one more time - I missed a gate on the GET request. (This is on develop.)

**Comment by blackout1231** [comment]
Develop, https://github.com/snipe/snipe-it/tree/develop

The below command is how I am updating:
php upgrade.php

Or is downloading the code and copying it over my existing installation is sufficient?

**Comment by snipe** [comment]
Your upgrade process is fine - I had missed a line - can you grab develop one more time. The change I just pushed through fixed it for me.

**Comment by blackout1231** [comment]
Rrroger

**Comment by blackout1231** [comment]
Pay dirt!!!

You madam, are awesome. Have a good weekend!

**Comment by snipe** [comment]
Awesome - glad that fixed it! 

![trek-nods](https://user-images.githubusercontent.com/197404/33788390-ca54aed2-dc26-11e7-9c9f-abbc3e3fe737.gif)
