### ISSUE TITLE
[Feature Request] Storagemanagement

### ISSUE THREAD

**Issue by BaseJam** [snipe/snipe-it#2815]
We need a feature to manage our storage. E.G. Patchcables
This is not a accessories to check out to a user and not a consumables, because this will be come back to storage.

My wish is an entry that has the following main informations:
- Partname
- maybe custom fields for further details to this part (e.g.: patchcable length)
- storage location / maybe same as location from company
- Manufacturer
- Supplier
- Supplier part number
- Default Purchase Cost

entry storage information:
- current pieces in stock
- minimal pieces in stock for alarm
- default pieces in stock to see how many have to order

entry control features:
- checkout -> number of pieces -> update current pieces in stock
- checkin -> number of pieces to checkin -> update current pieces in stock
- buy new -> number of new pieces, price by piece, order number, supplier -> update current pieces in stock and create info in history-listing with the entered informations.

By Report it will be possible to create a statistic to see all purchases of an entry and see the consumption by week/quarter/year or custom period.

What do you think? Great feature?
Greetings, Stefan

**Comment by korio77** [comment]
I will like something like this too.

Patch cables, power cables, adapters, cd's, dvd's, all that kind of stuff that you need to know you have some to use if you need them, but doesnt really matter to who you give it.

Great post :)

**Comment by BaseJam** [comment]
Hi Snipeyhead, can you give me Feedback if you realize my feature request? I need this :)
Greetings, Stefan
