### ISSUE TITLE
Category Not Showing

### ISSUE THREAD

**Issue by vinotnj21** [snipe/snipe-it#2816]
#### Expected Behavior (or desired behavior if a feature request)

I have requirement to display category page to non admin users.
#### Actual Behavior

Category page displays only to super admin users

---
#### Please confirm you have done the following before posting your bug report:
- [1 ] I have enabled debug mode
- [ 1
  ![untitled](https://cloud.githubusercontent.com/assets/23078482/19728546/e11427d8-9ba4-11e6-8f15-a0d3611f9dca.jpg)
  ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running : ver: 3.4.0.9
- What OS and web server you're running Snipe-IT on : Windows 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual
- If you're getting an error in your browser, include that error : Sad Panda you are not authorised
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error : Menu->Categories.
  ![untitled](https://cloud.githubusercontent.com/assets/23078482/19728467/83e43cf6-9ba4-11e6-8aad-7922cc6e2120.jpg)
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by vinotnj21** [comment]
Please help to solve this i tried a lot. but i cant find a way.

**Comment by snipe** [comment]
Can you show me a screenshot of your user permissions and any groups you're associated with? You'd have to be a superadmin to edit categories.

**Comment by vinotnj21** [comment]
Hi,
    Here i attached the required screen shots and query results. I don't want user to edit the category just want to view the category screen

![user permission screen](https://cloud.githubusercontent.com/assets/23078482/19753596/0c972d52-9c17-11e6-9ef9-bca377ae7a01.jpg)
![group permission](https://cloud.githubusercontent.com/assets/23078482/19753599/1688280c-9c17-11e6-8e1a-dbc7a47dd7b8.jpg)
![category screen](https://cloud.githubusercontent.com/assets/23078482/19753604/1cc75134-9c17-11e6-84fd-feaf02529f35.jpg)

I want the user to see this screen and not to edit the category.

**Query Results**
     Group Permission: Report Viewers :{"superuser":"0","admin":"1","reports.view":"1","assets.view":"1","assets.create":"0","assets.edit":"0","assets.delete":"0","assets.checkin":"0","assets.checkout":"0","assets.view.requestable":"1","accessories.view":"1","accessory.create":"0","accessories.edit":"0","accessories.delete":"0","accessories.checkout":"0","accessories.checkin":"0","consumables.view":"1","consumables.create":"0","consumables.edit":"0","consumables.delete":"0","consumables.checkout":"0","licenses.view":"1","licenses.create":"0","licenses.edit":"0","licenses.delete":"0","licenses.checkout":"0","licenses.keys":"1","components.view":"1","components.create":"0","components.edit":"0","components.delete":"0","components.checkout":"0","components.checkin":"0","users.view":"1","users.create":"0","users.edit":"0","users.delete":"0"} 
      User Permission: 
{"superuser":"0","admin":"1","reports.view":"0","assets.view":"0","assets.create":"0","assets.edit":"0","assets.delete":"0","assets.checkin":"0","assets.checkout":"0","assets.view.requestable":"0","accessories.view":"0","accessory.create":"0","accessories.edit":"0","accessories.delete":"0","accessories.checkout":"0","accessories.checkin":"0","consumables.view":"0","consumables.create":"0","consumables.edit":"0","consumables.delete":"0","consumables.checkout":"0","licenses.view":"0","licenses.create":"0","licenses.edit":"0","licenses.delete":"0","licenses.checkout":"0","licenses.keys":"0","components.view":"0","components.create":"0","components.edit":"0","components.delete":"0","components.checkout":"0","components.checkin":"0","users.view":"0","users.create":"0","users.edit":"0","users.delete":"0"}

Kindly advice how can i achieve this requirement.

**Comment by snipe** [comment]
Category listings are only available to superadmins at this time.

**Comment by vinotnj21** [comment]
Hi Snipe,
      If possible can you add this feature in next release or for time being can you suggest me 
what can be done to achieve this requirement please
