### ISSUE TITLE
asset maintenance report issue

### ISSUE THREAD

**Issue by leobg** [snipe/snipe-it#2820]
#### Expected Behavior (or desired behavior if a feature request)

display asset maintenance report

-----

#### Actual Behavior

few unformatted rows are shown with "Whoops, looks like something went wrong." header on top. 

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 3.5.0
- What OS and web server you're running Snipe-IT on CentOS 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual install
- If you're getting an error in your browser, include that error (all browsers)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error Asset maintenance reports
- If a stacktrace is provided in the error, include that too.

[2016-10-26 12:44:30] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Class 'Carbon' not found' in /var/www/snipe-it-3.5.0/storage/framework/views/767282b8efb9eb0f7b2d3ea1e95002e16b085077.php:55
Stack trace:
#0 {main}

- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by leobg** [comment]
code in the view:
 <?php
                                $assetMaintenanceTime = intval(Carbon::now()->diffInDays(Carbon\Carbon::parse($assetMaintenance->start_d
ate)));
                            ?>

**Comment by snipe** [comment]
Try running 

```
php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan config:clear
```

**Comment by leobg** [comment]
I have done this already, but did it again just in case. Also upgraded to current master branch (v3.5.1-2-gd7222ae) doesn't seem to help - still "No matching records found" message shown on activity report, but few individual assets I tried with show history properly. I noticed action_log table has location_id for some assets set to specific location but for others it is NULL. I recently had related issue - could this be the culprit?

**Comment by snipe** [comment]
It should't matter. 

Try:

```
cd /your/application/dir
rm bootstrap/compiled.php
rm -rf vendor
php composer.phar install --no-dev --prefer-source
```

**Comment by leobg** [comment]
it doesn't seem to be bootstrap/compiled.php - is that normal?

**Comment by leobg** [comment]
I think I figured out what is wrong. I had some maintenance records created with very early version of snipeit, asset maintenance time was blank for few of the records. After opening them and just clicking save, they got the correct maintenance time and now report runs with no error.

**Comment by snipe** [comment]
Hmm... We'll look into that. It should definitely not error on that.

**Comment by snipe** [comment]
When you say asset maintenance time, do you mean start date, end date or both?

**Comment by leobg** [comment]
I have both specified, but I remember there was issue with maintenance period calculation when feature was initially introduced and it wasn't calculating the time property (wasn't at all). I had few records from bacl then.

**Comment by snipe** [comment]
Right, but if the new code was choking on old data, which fields were missing/wrong?

**Comment by leobg** [comment]
"Asset Maintenance Time (in days)" was blank for those records. Upon editing and saving without changing anything field got populated with corresponding value and report stopped crashing.

**Comment by snipe** [comment]
That's a calculated number though, based off start date and end date, it's not something that's stored in the database. I'll experiment with deleting start_date and end_date and see if I can reproduce. Thanks for the extra info!
