### ISSUE TITLE
Only superadmin can check out Components

### ISSUE THREAD

**Issue by Allenvh** [snipe/snipe-it#2822]
#### Expected Behavior (or desired behavior if a feature request)

Show button to check out components when granted to other users other than superadmin

-----

#### Actual Behavior

button only showed under superadmin 

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
3.4 0.9-g67315d8
- What OS and web server you're running Snipe-IT on
Win server 2012 r2 (wamp)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual
- If you're getting an error in your browser, include that error
No errors observed
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Components.index - index.blade.php
Layouts.default - default.blade.php
Notifications - notifications.blade.php

- If a stacktrace is provided in the error, include that too.
No errors observed
- Any errors that appear in your browser's error console.
No errors observed
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
Behavior not observed ( different version)
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

- Include what you've done so far in the installation, and if you got any error messages along the way.
Checked the error under
Admin
Inherit
And specific permissions to user

- Indicate whether or not you've manually edited any data directly in the database
No edits.

**Comment by snipe** [comment]
I can't reproduce this locally. For my test user, I granted only access to components (all of the component permissions).

<img width="1481" alt="screen shot 2016-10-27 at 9 53 30 pm" src="https://cloud.githubusercontent.com/assets/197404/19795382/de6392ee-9c8f-11e6-8c70-bda0d09588b6.png">

**Comment by Allenvh** [comment]
After the update this is not an issue anymore.

**Comment by snipe** [comment]
![3z](https://cloud.githubusercontent.com/assets/197404/19830432/34041732-9dad-11e6-8a60-61ebbc573c39.gif)
