### ISSUE TITLE
Barcodes not Scaled to Size

### ISSUE THREAD

**Issue by mikshepard** [snipe/snipe-it#2824]
#### Expected Behavior (or desired behavior if a feature request)

Under "Settings" --> "Label Settings" --> "Label Dimensions", setting the width to a size of under two inches will cause the barcode to become unusable.  Looking into it further, it seems the barcode does not get scaled and instead gets cut off by the label borders.

The proposed solution that I am using is to edit "resources/views/hardware/labels.blade.php:52" and add the bottom two lines:

```
 img.barcode {
    display: block;
    margin-left: auto;
    margin-right: auto;
    width: 90%;
    height: 100%;
}
```

Adding this CSS scales the barcode to 90% width and 100% height.  This solved the problem for us and I thought I'd share.

Thanks for the great program, working great so far!

-Mike
Ubuntu 14.04
Snipe v3.5.0
php 5.5.9

**Comment by snipe** [comment]
I would probably have put that into the custom CSS in Admin > Settings, versus editing the blade template manually.

**Comment by snipe** [comment]
But thanks for the CSS snippet :)

**Comment by sheppyh** [comment]
Why is this closed rather than made a new default for the application? I have the same issue

**Comment by BrettFagerlund** [comment]
There has been various issues in the past regarding resizing/scaling of barcodes making them unreadable. I would say it's better to let the component determine size and use the custom css to fit individual needs.

**Comment by fracerutti** [comment]
hi snipe and team! is this css (img.barcode) still used in version 7 ? tried some changes but i don't see them in the generated labels. for example i tried modifying the heigh and width of de barcode bellow. don't know if i'm missing something

![image](https://github.com/user-attachments/assets/ba657d84-830f-405d-8bbe-1ea2afc2585b)

currently using snipe it 7.0.11 v14904  running on docker

many thanks!

**Comment by tritonexperiment** [comment]
> hi snipe and team! is this css (img.barcode) still used in version 7 ? tried some changes but i don't see them in the generated labels. for example i tried modifying the heigh and width of de barcode bellow. don't know if i'm missing something
> 
> ![image](https://private-user-images.githubusercontent.com/147278409/362416192-ba657d84-830f-405d-8bbe-1ea2afc2585b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MjQ5MjMsIm5iZiI6MTcyNTUyNDYyMywicGF0aCI6Ii8xNDcyNzg0MDkvMzYyNDE2MTkyLWJhNjU3ZDg0LTgzMGYtNDA1ZC04YmJlLTFlYTJhZmMyNTg1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQwODIzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Zjk0MDY0ZDY2ZWFmOGNjNjhiMDRlYjUxZDM0YjZlNjc4YjdkYWJkYTg4ZmYwMjVjZDljNDdiYWZkM2U0NmUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HIddYrV4YgK3z6QafJLn_OAdjRIeCPjBhrf2oXM5_6k)
> 
> currently using snipe it 7.0.11 v14904 running on docker
> 
> many thanks!

Doesn't looks like the custom css affects the new label engine which kind of makes sense, it's making a PDF page. Revert to old engine and it should be OK.

**Comment by fracerutti** [comment]
> > hi snipe and team! is this css (img.barcode) still used in version 7 ? tried some changes but i don't see them in the generated labels. for example i tried modifying the heigh and width of de barcode bellow. don't know if i'm missing something
> > ![image](https://private-user-images.githubusercontent.com/147278409/362416192-ba657d84-830f-405d-8bbe-1ea2afc2585b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MjQ5MjMsIm5iZiI6MTcyNTUyNDYyMywicGF0aCI6Ii8xNDcyNzg0MDkvMzYyNDE2MTkyLWJhNjU3ZDg0LTgzMGYtNDA1ZC04YmJlLTFlYTJhZmMyNTg1Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQwODIzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Zjk0MDY0ZDY2ZWFmOGNjNjhiMDRlYjUxZDM0YjZlNjc4YjdkYWJkYTg4ZmYwMjVjZDljNDdiYWZkM2U0NmUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HIddYrV4YgK3z6QafJLn_OAdjRIeCPjBhrf2oXM5_6k)
> > currently using snipe it 7.0.11 v14904 running on docker
> > many thanks!
> 
> Doesn't looks like the custom css affects the new label engine which kind of makes sense, it's making a PDF page. Revert to old engine and it should be OK.

oooh, that was it!
many thanks!
