### ISSUE TITLE
Requestable assets

### ISSUE THREAD

**Issue by leobg** [snipe/snipe-it#2825]
#### Expected Behavior (or desired behavior if a feature request)

Requestable asset list properly displayed

-----

#### Actual Behavior

columns missaligned:
For "Model" I get right column - model;
Serial column shows name instead serial number;
Location shows serial number;
Status shows location;
Expected checkin date shows the status;
actions shows the expected check-in date;
and finally the last column has no caption but has the action button.

On the demo site columns appear properly aligned. This issue I am experiencing since the 3.5.0 (and later) update yesterday.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running **v3.5.1-2-gd7222ae**
- What OS and web server you're running Snipe-IT on **CentOS 7**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **manual install**
- If you're getting an error in your browser, include that error **all browsers tested**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **requestable-assets**
- If a stacktrace is provided in the error, include that too. **no error output in laravel.log when page is called**
- Any errors that appear in your browser's error console. **no errors**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). **not happening there**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database **yes - during previous bugfixes related to outdated data - deleted location display issues**

**Comment by snipe** [comment]
The demo is running the same as you are, so I don't know why it would display differently. Exact same code. Can you provide a screenshot?

**Comment by leobg** [comment]
Here is a screenshot (a bit obstructed) 
![snipeit-screenshot](https://cloud.githubusercontent.com/assets/10868370/19752785/d899dc82-9bcd-11e6-9f0d-3c603d779773.png)
