### ISSUE TITLE
Authorization by x-authenticated-user

### ISSUE THREAD

**Issue by trondvh** [snipe/snipe-it#2827]
Have you considered implementing authorization by x-authenticated-user HTTP header? It would allow us to implement SSO with kerberos in front of snipe-it. Especially important to companies using smartcard logon, where the users do not have any passwords.

I've noticed a config parameter named APP_TRUSTED_PROXIES, and if that's implemented already, adding support for  x-authenticated-user should not be that complicated?

**Comment by snipe** [comment]
We have considered it, yes. It will likely be added at some point.

**Comment by trondvh** [comment]
Do you do beerpay, or accept other kinds of donation for features requests?
