### ISSUE TITLE
When editing a accessory the minimum number can't be set to "0"

### ISSUE THREAD

**Issue by mr-gosh** [snipe/snipe-it#2833]
#### Expected Behavior (or desired behavior if a feature request)

an accessory that is edited should be saveable with a minimum required count of "0" to deactivate that feature.

-----

#### Actual Behavior

when editing an accessory and the creation minimum is set to "0" it can't be saved with a "0" in the minimum field. it that says "min amt muss kleiner als 1 sein." which means "min amt has to be smaller than 1" which is quite funny cause 0 is smaller than 1 ;)
in english it says: "The min amt must be at least 1."
if it is changed to "1" for example it can be saved....

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running

Version v3.4.0-9-g67315d8

- What OS and web server you're running Snipe-IT on

ubuntu 16.04 64bit

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

docker

- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).

yes - it is reproducable and can't be set to 0 in the demo too

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by mr-gosh** [comment]
btw. the github issue preset has outdatedx links to manual and demo... ;)

**Comment by Deitsch** [comment]
The german error message is still wrong on ** v4.7.4**. It should say smth like "min amt muss zumindest 1 sein."
