### ISSUE TITLE
Upgrade from 2.1 to 3.5.1 ::: Can't login

### ISSUE THREAD

**Issue by sysnoo** [snipe/snipe-it#2837]
I set a new server with 3.5.1 and migrated data and DB from 2.1

When I try to login, I have this error :
 production.ERROR: Illuminate\Session\TokenMismatchException
Not sure where I can check to fix this

**Comment by snipe** [comment]
Closed as duplicate https://github.com/snipe/snipe-it/issues/2826#issuecomment-257002926
