### ISSUE TITLE
"I forgot my password" re-directs to "mydomain.compassword/reset

### ISSUE THREAD

**Issue by abaltaspike** [snipe/snipe-it#2839]
I enabled https on my snipe-it application and I have configured my /etc/apache2/sites-available/snipeit.conf to the following:
--------------------------------------------------------------
NameVirtualHost *:80
<VirtualHost *:80>
   ServerName mydomain.com
   DocumentRoot /var/www/snipeit/public
   <Directory /var/www/snipeit/public>
        Require all granted
        AllowOverride All
   </Directory>
   ErrorLog /var/log/apache2/snipeIT.error.log
        CustomLog /var/log/apache2/access.log combined
   Redirect permanent / https://mydomain.com/
</VirtualHost>

<VirtualHost _default_:443>
   ServerName mydomain.com
   DocumentRoot /var/www/snipeit/public
 <Directory /var/www/snipeit/public>
        Require all granted
        AllowOverride All
   </Directory>
  SSLEngine On
  SSLCertificateFile /etc/ssl/certs/server.cer
SSLCertificateKeyFile /etc/ssl/private/server.key
  ErrorLog /var/log/apache2/snipeIT.error.log
        CustomLog /var/log/apache2/access.log combined
 </VirtualHost>
-------------------------------------------------------------------------

I am trying to test my email settings and saw that "forgot my password" is be the best way to test it. When i try to browse to it mydomain.com and password are joined to look like https:/mydomain.compassword/reset

OS is ubuntu 14.04

**Comment by abaltaspike** [comment]
FYI, if I manually change the URL to https:/mydomain.com/password/reset it works like intended

**Comment by snipe** [comment]
What's your APP_URL in your .env?

**Comment by snipe** [comment]
(You should not manually change the URL in any blades - they all use the APP_URL)
