### ISSUE TITLE
[Feature Request] Mobile Device assets (cellular phones etc)

### ISSUE THREAD

**Issue by JExactly** [snipe/snipe-it#2843]
I wanted to post this and maybe discuss best practices or a better way to manage mobile devices that have SIM cards or the ability to upgrade the device that is tied to something like a SIM/Phone#

I currently run into an issue where I have 80+ Mobile phones linked to 2 US Cell carriers. They track upgrade status on the devices based on the Phone#(line contract) I am trying to determine the best way that I can make managing our mobile devices easier to track using Snipe-IT.  Essentially, I would like to be able to set an upgrade date tied to the phone#/SIM card and like consumables etc., track when these devices fall within their upgrade window. I am not sure of how many others have to deal with something like this. Maybe I am overlooking an obvious answer. 

I thought about Setting the SIM card as a component of the Mobile Device asset, but there is no way to track the upgrade date and get a report or notification that the upgrade is due soon.

**Comment by snipe** [comment]
Can you have the phone as an asset, the SIM and upgrade date as custom fields? You'd at least be able to sort by them and export them

**Comment by JExactly** [comment]
That's basically the only way i could think of making it work with the current system design. 

I guess what I was toying with was.. "Is it a feature worth having say it's own tracking spot on the dashboard" and it only appears on the dashboard if you have devices that fall within the EOL window.

I suppose this could also be said for all assets, it generates a Quick heads up on the dashboard that shows you your EOL devices and groups them by category.. maybe gives you a 2-5 items preview with a link to a direct search or takes you to a Specific report?

**Comment by aglasson** [comment]
Why would you have that? For plans expiring on one provider and being moved to another?
Personally that is very left field and something less than a small minority might use.
I would just track it in a spread sheet separately?

**Comment by therealjoshuad** [comment]
My last gig wasn't a BYOD shop, so that would have been a great feature for our telecom team. My latest gig is all BYOD, so I see both sides of this argument, when you do manage drvices something like this could be great. I personally would prefer time spent on other things that are more universal to a larger set of users though.

**Comment by JExactly** [comment]
For me, it is not about plans expiring. Now I understand that can correlate. However, I am more interested in making it simpler to manage upgrading a device. The sim is just tied to the phone line. Even if the device is destroyed, the line still continues to move on. What I am trying to achieve here is device EOL for my mobile devices. Essentially, the IMEI for the device is static, The SIM is a component, and I want to easily track my mobile device upgrades. on a Business mobile account in the US, upgrade dates are based upon the date that the line was added to the master account for the carrier, not particularly a contract date per se. Now that I have thought more about the process.. I think with the way that the system is designed, I may be able to achieve this. I just have to test the flow and make sure it works as I laid it out here. 

I suppose, What I was getting at in my first post was I was looking for a field that exists that tracks it automatically without having to go through the process I just stated.

**Comment by aglasson** [comment]
Why not track the mobile service ("line") as an asset so the EOL length sets the date for EOL of the service.
I don't track sim cards as assets, I don't see them as assets, they are piece of plastic with only a temporary tie to a service which can change easily. Just add a custom field to your mobile service asset with the Simcard Number. When you change a service to a different sim just throw the sim in the bin and update that field to the new simcard number.
Simples.

**Comment by blabj** [comment]
I have this requirement as well, and it is a pain, managing physical assets (phones) via snipe-it, and intangible assets (contracts/mobile numbers) in a spreadsheet.  Especially because the phone associated to the number is not necessarily always assigned to the same user as the phone number.  IE. its often the case, that user X needs a new phone, but is not eligible for an upgrade, but user Y is eligible, but doesn't need a new phone.  We order an upgrade on user Y's account, and give phone to user X.

Anyone managing a corporate fleet of mobile devices has these issues.

If we could simply link assets, we could create mobile numbers as assets, and link them to phones.  Phones can be assigned to users, mobile numbers could be assigned to users, and mobile numbers could be linked to phones.

I think alot of use-cases can be solved, just by allowing the linking of assets.

**Comment by JExactly** [comment]
@blabj  I think I agree with your suggestion the most. Linking assets could be a viable solution. The device itself is linked to a SIM/Phone Number. Linking a SIM card to a phone number and then being able to attach the SIM/Phone# to a Device is helpful. I am almost thinking that maybe it would be easier if Mobile assets were managed independently from standard assets, Similar to Licenses or Consumables. You can manage the mobile aspect independently from the rest of the assets and utilize the Standard assets(to inventory mobile hardware) and link a mobile device asset(sim/phone#) to the standard asset. This option feels like a cleaner route to me. I am sure again, there may be simpler solutions. But I am sure that there are more than a few of us that struggle with the carriers terrible site designs and struggles we deal with managing mobile devices/SIM/Phones on an account.

**Comment by JExactly** [comment]
@snipe What if the linking of asset Types seems to be a more universal solution in my mind. What if the feature was to be able to Link assets to each other, But to avoid the abilty to accidentally allowing linking of improper asset types, adding a control like the Custom Fields has that only allows asset linking based on your added asset categories, similar to again, the Custom Fields and what fields are grouped can be linked to each other only.

**Comment by dkmansion** [comment]
I'm sorry I didn't see this thread sooner.  Back in 2007 I built a cellphone database for my company using MSAccess manages details for 3500 cellphones, hundreds of data cards and 3000+ pagers.  This handles department charges backs on a monthly basis in the tune of 200k$US.  We pay one bill for each vendor and charge the cost centers their cut each month after importing the bill and matching to our records for department summation.

After using SnipeIT for other things in our inventory I'm also toying with adding a Services pull request... I will keep this thread posted.
