### ISSUE TITLE
[Feature Request] User Permissions to view only specific category of assets

### ISSUE THREAD

**Issue by delinski111** [snipe/snipe-it#2844]
#### Expected Behavior (or desired behavior if a feature request)

Feature Request is related to a change in the way users see assets.
The ability for a user or user group, to specifically be set to allow the user only to see a specific asset category, instead of all assets.

Use Case:
We have an order clerk in our organization, who handles all of the ordering for remote sites. currently, we use Access for our inventory (in process of moving to SnipeIT). We host an access form hosted to a webserver, so she can view the database (yes is looks as bad as it sounds), so that she can view information regarding printer to order ink without needing us to send her order requests manually every time a remote site makes a request for more items.

I would like her account / group to see assets, but only the ones she would need to see.
for the use case above, we would select her usergroup, and have it limited to only being able to see the "Printers" category (or whatever specific ones the group would need).

I can live without this, just thought it would be beneficial to suggest it, as I am sure others would find this feature useful.

**Comment by B3RN0UT** [comment]
I would really appreciate that. 

We have the need that some person only see asset category for example smartphones to create and edit assets. 
In my opinion asset category based permission handling would be great :)

**Comment by dmeltzer** [comment]
Could use use full company support to mimic this in the short term at least?
