### ISSUE TITLE
Permissions to view assets only, was able to create models & asset maintenance

### ISSUE THREAD

**Issue by delinski111** [snipe/snipe-it#2845]
#### Expected Behavior (or desired behavior if a feature request)

User, with only viewing ability granted, was expected to reach an error page as a result of a lack of permissions.

---
#### Actual Behavior

User, with only viewing ability granted, was able to add new asset models, and add new asset maintenance.

The user group on my end, is set only for;
Assets: View
Assets View Requestable
Consumables View 
Licenses View
Componants View
Accessories View
Reports View

Did verify that there is no section that is set to create, and the group does not have admin or super user.

---
#### Please confirm you have done the following before posting your bug report:
- [ X ] I have enabled debug mode
- [ X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running
  v3.4-14-g2a8ab06
- What OS and web server you're running Snipe-IT on
  Ubuntu  14.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  Manual
- If you're getting an error in your browser, include that error
  N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
  From the sidebar as the user in question, Asset Models, and Asset Maintenances
- If a stacktrace is provided in the error, include that too.
  N/A
- Any errors that appear in your browser's error console.
  N/A
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
  Cannot set a users group in the demo. (I created the user and user group to test this, but could not modify the users group. Called them both test_permissionsbug).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
  N/A
- Include what you've done so far in the installation, and if you got any error messages along the way.
  N/A
- Indicate whether or not you've manually edited any data directly in the database
  N/A

**Comment by snipe** [comment]
How are you getting to the interfaces where you're able to do these things?

**Comment by delinski111** [comment]
As the user, in the left sidebar, the drop down options from;
Assets > Asset Maintences
Assets > Asset Models

They correctly cannot access anything from the admin panel.
