### ISSUE TITLE
need office 365 mail configuration for snipe

### ISSUE THREAD

**Issue by ajock** [snipe/snipe-it#2850]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

Need office 365 mail configuration for snipe it ; latest version.....

From gmail ; mail is going but from office 365 not able to... please help
#### Actual Behavior

(what actually happens goes here)

---
#### Please confirm you have done the following before posting your bug report:
- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

---
#### Please provide answers to these questions before posting your bug report:
- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by therealjoshuad** [comment]
Do you just need the connection info?
https://support.office.com/en-us/article/POP-and-IMAP-settings-for-Outlook-Office-365-for-business-7fc677eb-2491-4cbc-8153-8e7113525f6c

**Comment by ajock** [comment]
I want connection details in code; like tls , ssl , starttls settings for office365 
 
For eg:-mail_startssl_enable=true

**Comment by therealjoshuad** [comment]
Are you talking about in the .env? If so:

```
MAIL_DRIVER=smtp
MAIL_HOST=smtp.office365.com
MAIL_PORT=587
MAIL_USERNAME=YOURUSERNAME
MAIL_PASSWORD=YOURPASSWORD
MAIL_ENCRYPTION=TLS
MAIL_FROM_ADDR=you@example.com
MAIL_FROM_NAME=Snipe-IT
```

**Comment by ajock** [comment]
this settings not working for me .... encryption is tls or starttls ?

**Comment by therealjoshuad** [comment]
TLS should work

Are you using a valid account's full email address for username?

**Comment by therealjoshuad** [comment]
@ajock any luck?

**Comment by MoazzamMuhammadKhan** [comment]
Hello.. I am facing the same issue and unable to send email using Office365. Could you please help.

**Comment by ajock** [comment]
Office 365 mail settings not working for me ....  i have used gmail account for mailing.. 

![image](https://cloud.githubusercontent.com/assets/23152614/21643539/e1a1e006-d299-11e6-80bd-b53be517044b.png)
