### ISSUE TITLE
[FEATURE REQUEST] Remote Computer Control

### ISSUE THREAD

**Issue by pavanagrawal123** [snipe/snipe-it#2851]
Hi! 

I was wondering if this is possible to integrate into Snipe:

An agent based remote monitoring/remote control for computers through VNC. If this can be added, it really puts Snipe IT ahead.

I can help contribute to this, but I am wondering what would be the correct approach to use for this...
If this idea is acceptable, here are some technologies we can use:
**Server side VNC:** https://instantwebp2p.github.io/peer-vnc/
**Frontend:** Will have to be written....
**and then client side agent:** Should just be a simple fork of some sort of VNC.... Doesn't even have to be custom, we can just bundle in any VNC server.
Also, to do a NAT transversal, a STUN server can be bundled in with the server application, or public STUN servers can be used.

Thanks! Let me know and I can help out with the development of this.

**Comment by dmeltzer** [comment]
This feels like it's very separate from the idea of asset inventory management, to me.

**Comment by therealjoshuad** [comment]
Yeah, I feel like that would take away from other more important feature request IMO
