### ISSUE TITLE
Adding extra LDAP fields

### ISSUE THREAD

**Issue by Alystia** [snipe/snipe-it#2853]
#### Expected Behavior (or desired behavior if a feature request)

It would be great if we could add in extra LDAP fields so we could pull more information from Active Directory.  Fields such as the users:
- Manager
- TItle
- Organisation
- Department
- Phone number. 

---
#### Actual Behavior

Currently only the users First and last name, their email address and AD username can be uploaded via LDAP sync. 

---

Thank you for the great work you do.

**Comment by POIP123** [comment]
Vote for this!

**Comment by pvhkai** [comment]
Vote for this! :D

**Comment by JExactly** [comment]
+1 I would also like to see the ability to sync up more ldap/AD fields.

**Comment by SylentBobNJ** [comment]
+1 this, too please

**Comment by thakilla** [comment]
+1

**Comment by nopawel** [comment]
+1

**Comment by Chris-ZA** [comment]
+1

Would love this as well!

**Comment by agentbb** [comment]
+1

an addination;

- Company
- Country
- Adress

**Comment by SantiMorenoSAP** [comment]
+1

- CostCenter

**Comment by jjangmoo** [comment]
+1

**Comment by jnmcfly** [comment]
+1 
physicalDeliveryOfficeName
telephoneNumber
department

**Comment by stevenrathel** [comment]
+1 
employeeid/employeenumber
department

**Comment by meyerf99** [comment]
Hello @snipe 

Is it planned in near future to integrate some more Active Directory fields?

**Comment by snipe** [comment]
Department, company, manager all get a little more complicated, since they would need to create those values if they didn't already exist. (For example, if your LDAP is listed as someone who doesn't exist in Snipe-IT, we have to check if that manager exists, and if not, create them.) That's fine for smaller OUs, but that LDAP sync is already doing a lot of heavy lifting, and the more work we try to do there, the longer it's going to take to process that info, leading to memory and/or timeout issues. It's the primary reason this hasn't been implemented yet.

**Comment by CronKz** [comment]
@snipe What about giving the User the choice? For example - providing all those wanted fields. If the field Manager was let empty, you don't have to check for it if it exists or not. You could go on straight ahead. The Companies with large LDAP OUs can stick to the Fields they already use. They don't have to use the new provided fields if the sync is already that slow. But by providing those fields, samler OUs would benefit from it IMHO.

**Comment by neonGenesis7** [comment]
+1
Company
Country
Adress
telephoneNumber
department

**Comment by jamiepassa** [comment]
+1 lets get this implemented :)

**Comment by mahesh2471990** [comment]
+1 Please Manager is must thing. So we can this snipe it to next level

**Comment by memtech3** [comment]
+1 to allow you to choose LDAP fields to import

**Comment by thanukalpa** [comment]
Please update the above request I also have the same concern in my AD users.
Manager
TItle
Organization
Department
Phone number
TelephoneNumber
Employeeid/Employeenumber

**Comment by thanukalpa** [comment]
@mahesh2471990 Your issue was solved ?

**Comment by neonGenesis7** [comment]
Need this extra LDAP Field.
________________________________

**Comment by Chris-ZA** [comment]
Yes, it’s still relevant. Good bot.

**Comment by kalidreamer** [comment]
+1. I want to import everything... EVERYTHING!

**Comment by snipe** [comment]
@kalidreamer given that we don't don't have custom fields for users yet, I'm not even sure what "everything" means.

Additionally, as I have explained in other threads, each one of the additional built-in fields adds processing time. Want to import a manager? First we have to check if that manager exists, and create them if it doesn't. Same for Department, Location, etc. This means potentially doubling or tripling the amount of work that LDAP import needs to do, which can result in timeouts, exceeding available processing memory, etc.

**Comment by mahesh2471990** [comment]
> 
> 
> @mahesh2471990 Your issue was solved ?

no not yet

**Comment by mahesh2471990** [comment]
> 
> 
> @kalidreamer given that we don't don't have custom fields for users yet, I'm not even sure what "everything" means.
> 
> Additionally, as I have explained in other threads, each one of the additional built-in fields adds processing time. Want to import a manager? First we have to check if that manager exists, and create them if it doesn't. Same for Department, Location, etc. This means potentially doubling or tripling the amount of work that LDAP import needs to do, which can result in timeouts, exceeding available processing memory, etc.

We want the Manager name should be synced by AD via LDAP.
and also during checkout and check-in if notification goes to the manager also it would be great

**Comment by phillipbarton** [comment]
I would also love to be able to import many more fields. It would be great if I could select the fields I want to import. 

Perhaps the system could provide the user with the option to skip any users with null properties in selected fields (this already seems to happen with the fields that are there), and/or put in a warning about potential hangs and timeouts if there are too many null values.

**Comment by congjl2002** [comment]
Need this feature very much,thanks.

**Comment by G13312** [comment]
Yes, it’s still relevant!

**Comment by loganhawker** [comment]
Could we add support for unique fields? That don't need to be checked for? Like a Job Title

**Comment by jrainone** [comment]
Syncing the company from Ldap would be a very needed feature.  Right now any people synced don't automatically have a company so they get excluded from viewing inventory.

**Comment by shinduke** [comment]
Would love to have this feature too.
We have about 2500 Members and managing this entry manually is a pain in the a**

**Comment by dtjn** [comment]
Syncing the company value is pretty much a necessity for larger setups to even be able to use the "Full Multiple Companies Support"... nobody has time to set the company value for multiple hundreds of users.

**Comment by gertz22** [comment]
+1, definetly needed for multiple companies

**Comment by measyberger** [comment]
**+1, still relevant.** :-) Our orginazation could really make good use of...
- Snipe-IT **Company** = LDAP attribute "Company"
- Snipe-IT **Location** = LDAP attribute "Department", "Office" or maybe OU membership 

Thank you so much for your great work!!

**Comment by shinduke** [comment]
Why is this request closed?
Is it already implemented or is it merged into an other request?

**Comment by dtjn** [comment]
There are some that are still open, at least regarding company:
https://github.com/snipe/snipe-it/issues/10698
https://github.com/snipe/snipe-it/issues/10161
https://github.com/snipe/snipe-it/pull/12176

**Comment by akeshell** [comment]
This issue has been raised since 2016. It is now 2025, 9 years later.
There are many requests for this in issues, but there has been no progress.

When multi-company support is enabled, if the user attributes do not have a company name, the asset acceptor and branch administrator cannot see the user.

**Comment by snipe** [comment]
> This issue has been raised since 2016. It is now 2025, 9 years later.
> There are many requests for this in issues, but there has been no progress.

In those nine years, we have added many LDAP fields, and countless additional features have been added. Being rude won't get your feature added any quicker.
