### ISSUE TITLE
Unable to check in components

### ISSUE THREAD

**Issue by matthanley** [snipe/snipe-it#2855]
#### Expected Behavior (or desired behavior if a feature request)

Option to check in components after component assigned to asset.

-----

#### Actual Behavior

No option to check in components on either the asset page or the component page.

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.4-14-g2a8ab06
- What OS and web server you're running Snipe-IT on: Docker
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Docker
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Component/Asset pages
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): Yes
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database: No

**Comment by jakobii** [comment]
I noticed this as well, if you accidentally check a component out to something that you did not intend to, the only way to remove it is by deleting the entire component. great concept though, I'm looking forward to seeing this feature built out a bit more.

**Comment by buck8ochickn** [comment]
Hi
As an inbetween update would you be able, to make it so that we can see how many of each component are checked out to an asset. 
Thanks

**Comment by jaredqpittman** [comment]
Interested in this as well. Awesome project btw, my team is loving it :)

**Comment by Kirkenjerk** [comment]
Has there been any updates for this feature request? Currently, Oct. 2017 and we would love to see the "checkin" feature for components.

**Comment by chzaid** [comment]
i would love to have this feature too. currently using components as assets just because of unavailability of checkin option.

**Comment by Sonn85** [comment]
+1 to this feature request.

**Comment by chzaid** [comment]
i upgraded to v4.1.3 build 48 today but request and most awaited featur is still no available. :(
if there is no plan to roll this out kindly educate us the right way to use this option atleast.

**Comment by PaddyPooskie** [comment]
I see the commit that shows this was fixed in Nov. 2017, but I am on v4.9.3 build 4395 and it looks like this feature still does not exist. Is there an old commit I need to pull to get this functionality?
