### ISSUE TITLE
Status in single asset overview

### ISSUE THREAD

**Issue by pvhkai** [snipe/snipe-it#2856]
Dear Snipe,

last week we switched our asset management to snipe (the migration of 1870 Assets tool two weeks of clearing our mastadata). Now its working very well and I think about switching our stock management also to the system. 

We found out that actually the "Status" (Deployed / Pending/ ...) is not shown in the single asset overview, but if you want to work with it it makes sence to see the status at the first overviewpage.

Is it planned to get this in the future?

Thanks alot for you nice product!
K

**Comment by snipe** [comment]
This is on develop now and should be in the next release.
