### ISSUE TITLE
Email alert for Item Request did not populate which item was requested

### ISSUE THREAD

**Issue by delinski111** [snipe/snipe-it#2858]
#### Expected Behavior (or desired behavior if a feature request)

User requested an asset. The email was sent. In the email, expected to see which user, which asset, what time, with all the related fields hyperlinked to that respective section of the inventory.

-----

#### Actual Behavior

User requested an asset. The email was sent. In the email, the site, and the user were listed and hyperlinked.

The asset/item field did not populate.

A user has requested an item on the website "site1"

User: user1
Item: (asset)
Requested: timehere

In the above, the email returned "Item: (asset)", and did not hook to which asset was requested. 

-----

#### Please confirm you have done the following before posting your bug report:

- [ X ] I have enabled debug mode
- [ X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.5.2-11-g5a835a5 (features/drawn_signatures branch)

- What OS and web server you're running Snipe-IT on
Ubuntu 14.04

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual

- If you're getting an error in your browser, include that error
N/A

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Email Alerts sent invalid/incomplete results

- If a stacktrace is provided in the error, include that too.
N/A

- Any errors that appear in your browser's error console.
N/A

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
N/A

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
N/A

- Include what you've done so far in the installation, and if you got any error messages along the way.
This is a fresh install (manual) than checked out the branch above. No special configurations or changes to the settings.

- Indicate whether or not you've manually edited any data directly in the database
No

**Comment by delinski111** [comment]
Upon checkout of item (one with a EULA) the email DID contain the correct hook to the asset, as all the fields were correctly populated. This seems isolated to the Request email.

**Comment by snipe** [comment]
I believe this was already fixed in recent versions
