### ISSUE TITLE
Can't generate a new APP_KEY

### ISSUE THREAD

**Issue by kfw9257** [snipe/snipe-it#2860]
No APP_Key being generated when I run php artisan key:generate
-----

#### Actual Behavior
-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running : v3.5.2
- What OS and web server you're running Snipe-IT on Windows 7/IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual Install
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error 
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. 
- Include what you've done so far in the installation, and if you got any error messages along the way. 
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
A little more information would be helpful here. What happens when you try to generate an app key? Does it output anything to the screen? Does it cause anything to be added to the error logs?

**Comment by kfw9257** [comment]
Nothing gets outputted to the screen, it just goes back to the prompt. I don't see any error log file being generated. I checked and it's set to true in the .env file.

**Comment by kfw9257** [comment]
One thing I'm concerned about is if I ran the Composer file correctly. I did it with a user account that has local admin rights. I remember seeing a warning about running it an Administrator but what other user account would I run it under? Is there any way to verify the dependencies we're installed?

**Comment by snipe** [comment]
If dependencies were installed, you'll see a bunch of folders in the `vendor` directory. But if composer didn't give you any output at all when you can composer install, it's unlikely that they were. Composer install gives you a lot of output on the command line to show you what it's doing. 

Local admin rights *should* be okay, though I'm not as up on my Windows server stuff as I am for linux. The reason we tell you not to run that as a superadmin is because you'll have to ALWAYS update it as superadmin from there on out, otherwise you'll run into all kinds of weird permissions errors, since the less-priveliged user can't overwrite the composer caches, vendor files, etc.

**Comment by kfw9257** [comment]
Ok, I'm going to try to install it using XAMPP. How would I go about doing that? I see one git issue here: https://github.com/snipe/snipe-it/issues/290 where they go through it but it references a start.php file in the bootstrap folder but I don't see that file.

**Comment by kfw9257** [comment]
OK, I went back through the install instructions and managed to get composer and the dependencies installed properly, at least I'm pretty sure they are. Now when I go to the url I set up in the .env file, it takes me to the Apache main page, not Pre-Flight. Do you know what's happening there?

**Comment by snipe** [comment]
That usually means that either your document root is set wrong in apache, or you still have an entry for the default document root and your virtual host name isn't set

**Comment by kfw9257** [comment]
I got it, just needed to update the document root in httpd.conf. I had only updated it in httpd-vhosts.conf

**Comment by snipe** [comment]
Great! Glad you got it sorted!
