### ISSUE TITLE
asset confirmation notification

### ISSUE THREAD

**Issue by epic990** [snipe/snipe-it#2861]
#### Expected Behavior (or desired behavior if a feature request)

The user confirm checking out but I as admin dont see did he confirmed it.

-----

#### Actual Behavior

Is there a option that admin see the confirmation of the user when he checkout asset to that user and user confirms it

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running Version 
v3.5.2-11-g5a835a5
- What OS and web server you're running Snipe-IT on
 Windows7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) 
manual
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error  
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
I checked out asset to the user. User confirms it but i dont see any confirmation of it so i dont know did he or didnt he accepted the asset.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by aglasson** [comment]
I can confirm I am seeing the same thing.
This was not the case in v3.2. In that version the email link went to an accept page and the history would reflect "accepted" in the action column of the history.
