### ISSUE TITLE
List a status from nav bar

### ISSUE THREAD

**Issue by bjorntk** [snipe/snipe-it#2862]
Not sure if this is a bug.

What I did:
Create Status "Lager" (Deployable and Visible in the nav bar).
Create 2 assets and give them Status "Lager".
Deploy one of them to a user.
Click Lager on the nav bar.

#### Expected Behavior
Only show the asset with Lager status, and not the deployed.

#### Actual Behavior
Both assets show up, one with status Lager and one with "Deployed"

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
 Version v3.5.2-11-g5a835a5 

- What OS and web server you're running Snipe-IT on
Debian / Apache2

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual install

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
Yes, same on demo.

**Comment by snipe** [comment]
What you're really asking is the ability to remove the status label "types" from the sidenav. I guess we could make that an option, but it's not something many users ask about, so I hate to add yet another tiny setting.
