### ISSUE TITLE
[Feature Request] Default supplier for assets models

### ISSUE THREAD

**Issue by POIP123** [snipe/snipe-it#2866]
Hi,

I'm looking for new feature to set default supplier for assets models. For example Macbook Pros default supplier are company X and servers default supplier are company YY. So it's faster to create new asset because you don't have to select the supplier every time.

Thank You :)

**Comment by POIP123** [comment]
Also assets default location would be nice to have feature. In some cases some assets are located always at same place (ex. servers if you have only one server room).

**Comment by snipe** [comment]
We already have a default location for assets.

**Comment by POIP123** [comment]
@snipe : for asset i meant asset models. So when creating new asset model (ex LaserJet 1320) there's no field for default location. It would be really handy to select default supplier and location to base asset model.

![assetmodel](https://cloud.githubusercontent.com/assets/23208424/19921547/0aecd45a-a0e7-11e6-8666-5f3a34d6224f.png)
