### ISSUE TITLE
Activity Search Error

### ISSUE THREAD

**Issue by sysnoo** [snipe/snipe-it#2868]
v3.5.2
All Snipe-it is working well.
Activity report is there but  when searching I got this in the browser console: 
/reports/activity/json?search=mari&order=asc&limit=100&offset=0 500 (Internal Server Error)

 **In the log it says** 
production.ERROR: ErrorException: Undefined variable: activity in /home/web/snipeit/app/Http/Controllers/ReportsController.php:314

/home/web/snipeit/app/Http/Controllers/ReportsController.php(314): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined varia...', '/home/web/_...', 314, Array)

N.B: It is not fresh install but migrated data and db from 2.1

**Comment by sysnoo** [comment]
No Help with this Issue?

**Comment by snipe** [comment]
I am away at a conference. Please be patient.

**Comment by snipe** [comment]
The Activity report currently cannot be searched. We should remove the search box.
