### ISSUE TITLE
[Feature Request] Allow Consumables-Accessories to be 0

### ISSUE THREAD

**Issue by delinski111** [snipe/snipe-it#2869]
#### Expected Behavior (or desired behavior if a feature request)

I would like to use the consumables/Accessories/Components inventory to keep a history of purchases. Things that not necessarily need to be kept in stock, for auditing purposes.

For the UI, I think a straightforward solution to this issue would be to have a checkbox that says something to the effect of "Does not send alerts / can have 0 left in stock" or alternatively by maybe putting in the field "-1" or something odd, that the app could read that as, 0 required or do not send/have alerts.

My issue with these non-asset tables currently, is that, We purchased Server Racks for our equipment. They are just hunks of metal, and do not need an asset tag, but I need to log the purchase, cost, vendor...
I entered it in as an accessory, but now (since I cannot have 0 stock), I have an alert at all times in the top bar menu. (A Server Rack is not something you just keep in stock, and will only purchase when the need arises).

This feature would probably benefit all the other tables, accessories, consumables, and components to have this option.

**Comment by epic990** [comment]
In components you can  input -value in minimal quantity like -20.
Accessories and consumables minimal value to enter is 1 but in  if u dont enter the  minimal quantity value her default is 0.
I dont know is this bugs or not but i solved it in that way.

**Comment by delinski111** [comment]
I just tested this after seeing your comment.

So, I left the min field null, and entered that I have 1 in stock.

If you take a look at the top, to the right of the search bar, you will now see a 1 in the alerts window, I basically do not want particular expendable items to trigger those alerts, as I do not need to keep them in stock, but still need to record them.

**Comment by epic990** [comment]
I got the same problem here and dont know how to solve it, just tryed to help you a bit even i dont know much about it. If anyone else knows and solve it it will help us both.

**Comment by imthatjeremyguy** [comment]
I was annoyed by this and found a solution for me. However, I don't think it will be a universal fix for everyone, if you actually need to track alerts for low stock.

In your settings there is a Inventory Alert Threshold setting. I set that to 0. 

My component quantity 1, in stock 0. No flag.

I agree with your original feature request though as I believe this will mess with anyone that needs to actually track low stock of items. Me, being a lone IT Admin in a small business I can live without it, much larger teams need an alternative.
