### ISSUE TITLE
/setup errors after the installation

### ISSUE THREAD

**Issue by arthur-thebear** [snipe/snipe-it#2872]
Hi,

could you please help me to resolve this

#### Expected Behavior (or desired behavior if a feature request)

initial setup after the installation

-----

#### Actual Behavior

url/setup - gives 500 error or "Whoops, looks like something went wrong."
mod_rewrite is working
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [V] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - latest, just installed via git clone
- What OS and web server you're running Snipe-IT - CentOS6.5 with httpd
- What method you used to install Snipe-IT - git clone
- If you're getting an error in your browser, include that error - either 500 error or 2 x "
Whoops, looks like something went wrong." lines with permissions set to 777 to installation directory.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - url/setup
- Include any additional information you can find in `app/storage/logs` and your webserver's logs -[2016-11-02 17:14:04] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /var/www/snipeit.ludia.local/bootstrap/cache/compiled.php:7771

- Installation procedure until initial setup
- Indicate whether or not you've manually edited any data directly in the database - no

**Comment by arthur-thebear** [comment]
Ok, figured it out:

changed in config/app.php   'cifer' to AES-256-CBC and it's working now.

**Comment by bjorntk** [comment]
I had the same issue, but noticed it was working after I installed phpmyadmin, guess phpmyadmin had some dependencies that made the initial setup work.

**Comment by azuercher** [comment]
I had a similar error (No Supported Encrypter Found) when installing on CENTOS 7 with PHP7.  Based on your comments and some googling it looks like I was missing mcrypt so I installed php70w-mycrpt to fix the error.

**Comment by snipe** [comment]
Yeah, laravel doesn't require mcrypt anymore, but because some people have changed their cipher to something else, we're going to have a nasty migration to get everyone brought up to non-mcrypt stuff now. :(
