### ISSUE TITLE
Uploaded files missing after upgrade to 3.5.2

### ISSUE THREAD

**Issue by lravelo** [snipe/snipe-it#2873]
#### Expected Behavior (or desired behavior if a feature request)

After upgrading, I expected to see the files I've uploaded to each asset.

-----

#### Actual Behavior

There are files in the /opt/snipe-it/storage/private_uploads/assets directory but it doesn't appear that anything is pointing to them from the web gui

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running = 3.5.2
- What OS and web server you're running Snipe-IT on = Ubuntu 14.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) = git pull
- If you're getting an error in your browser, include that error = no error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error = all pages that normally show attached files
- If a stacktrace is provided in the error, include that too. = n/a
- Any errors that appear in your browser's error console. = n/a
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). = can't upgrade demo so can't test
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. = n/a
- Include what you've done so far in the installation, and if you got any error messages along the way. = no errors during installation
- Indicate whether or not you've manually edited any data directly in the database = no manual editing of data in database

**Comment by snipe** [comment]
I. Relieve this is fixed on develop

**Comment by snipe** [comment]
*i believe

**Comment by lravelo** [comment]
not sure I understand.

**Comment by lravelo** [comment]
I got curious, installed phpmyadmin and checked out the asset-uploads table
and it was empty. Looks like this is the issue right here. I'm going to
attempt restoring that table tomorrow to see if that resolves the issue.

**Comment by snipe** [comment]
As I said, there is a fix for this on the develop branch

**Comment by lravelo** [comment]
how can I go about installing that?

**Comment by snipe** [comment]
```
git checkout develop
git pull
php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan migrate
php artisan config:clear
```
