### ISSUE TITLE
Using views in the database

### ISSUE THREAD

**Issue by ttpars** [snipe/snipe-it#2877]
I would like to create some reports out of the Snipe IT Database and want to use views to do so.

I have tested to verify they work and have not had any issues.

I tested performing upgrades with the views in place and everything looks OK.

I wanted to check with the community to see if there was any reason I should not use views with Snipe IT.

**Comment by dmeltzer** [comment]
Can you be a bit more specific? "Views" is a very generic term--what are you modifying (and what doesn't exist currently that you are trying to add?)

**Comment by snipe** [comment]
I think they mean MySQL views. I can't think of any reason it would be an issue.

**Comment by ttpars** [comment]
@dmeltzer @snipe Yes, I meant MySQL views - I apologize for not being more specific.  Thank you for the response.
