### ISSUE TITLE
Allowed file type list in the error message does not mention ZIP or RAR

### ISSUE THREAD

**Issue by pako-pl** [snipe/snipe-it#2880]
The Upload File window says:

```
Allowed filetypes are png, gif, jpg, jpeg, doc, docx, pdf, txt, zip, and rar.
```

But the error message appearing when I try to send a different file does not include "jpeg", "zip" or "rar":

```
Error: One or more of your files is too large or is a filetype that is not allowed. 
Allowed filetypes are png, gif, jpg, doc, docx, pdf, and txt. 
```

Snipe-IT version: 3.4.0

**Comment by snipe** [comment]
Which file upload section are you talking about?

**Comment by pako-pl** [comment]
I did a quick test today and couldn't reproduce the issue on Snipe-IT 3.6.2, so I'm closing the issue.
