### ISSUE TITLE
Pictures vanishing after redeploy

### ISSUE THREAD

**Issue by cduverne** [snipe/snipe-it#2881]
#### Expected Behavior (or desired behavior if a feature request)

Each time I redeploy the front end docker image, the pictures should be persisted

-----

#### Actual Behavior

Each time I redeploy the front end docker image, the pictures vanish

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running : 3.5.1 Dockerized
- What OS and web server you're running Snipe-IT on.   
SnipeIT Docker image
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)  
Docker
- If you're getting an error in your browser, include that error  
image not displayed
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error  
Any page with a user-uploaded picture
- If a stacktrace is provided in the error, include that too.  
No
- Any errors that appear in your browser's error console.  
No  
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).  
N/A
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database  
No

**Comment by snipe** [comment]
I believe this is already fixed on the develop branch

**Comment by cduverne** [comment]
Hello, I tried to migrate from 3.5 to the develop branch with docker, the pictures are still vanishing. 
Maybe a volume I forgot in the dockerfile ?   
To ensure that the pictures are accessible to the new container ?

**Comment by snipe** [comment]
I think this is fixed with a recent commit to develop

**Comment by cduverne** [comment]
Indeed it is now ! When do you plan to push this on a release tag ?  
I love your tool ! You're doing a great job ! Thanks

**Comment by cduverne** [comment]
Hi @snipe do you know in which release this will be on-boarded ?
Thanks a lot
