### ISSUE TITLE
Laravel tries to Encrypt cookie "snipeittest_session" using EncryptCookies::class [SOLVED]

### ISSUE THREAD

**Issue by ole1986** [snipe/snipe-it#2882]
#### Expected Behavior (or desired behavior if a feature request)

Using Windows and PHP 5.6.X mcrypt caused an Exception in BaseEncrypter.php on lin 44 `getJsonPayload() -> throw new DecryptException('The payload is invalid.');` when trying to decrypt snipittest_session cookie.

**Only noted this because of xdebug**

System: Windows 10
PHP Version: 5.6 **WITH XDEBUG**
Database: Mysql

-----

#### Reason

snipeittest_session (name is configurable in .env) cookie does not seem to be encrypted.

#### Solution

The solution is to exclude this cookie from its `Illuminate\Cookie\Middleware\EncryptCookies` class

For this we can use the already overloaded class located in `app\Http\Middleware\EncryptCookies.php` and customize it the following:

```
namespace App\Http\Middleware;

use Illuminate\Cookie\Middleware\EncryptCookies as BaseEncrypter;
use Illuminate\Contracts\Encryption\Encrypter;
use Config;

class EncryptCookies extends BaseEncrypter
{
    /**
     * The names of the cookies that should not be encrypted.
     *
     * @var array
     */
    protected $except = [ 
        //
     ];

    public function __construct(Encrypter $encrypter) {
        $this->except[] = Config::get('session.cookie');
        parent::__construct($encrypter);
    }
}
```

**Comment by snipe** [comment]
I've not heard this issue from anyone else, so I'm not sure why this would be happening.

**Comment by ole1986** [comment]
As I wrote it's possible because of using Windows with php 5.6 using xdebug...  Otherwise I would also not have recognized it.

But one thing is clear, the snipeit session cookie does not become crypted and it tries to decrypt at some cases

**Comment by snipe** [comment]
Can I ask why you're running Xdebug? It's very system intense and wouldn't typically be used on a non-development system.

**Comment by snipe** [comment]
(Closing this for housekeeping)
