### ISSUE TITLE
Snipe-It Installation on IIS (confusing at best)

### ISSUE THREAD

**Issue by brudnicke** [snipe/snipe-it#2883]
Is there a clear, concise, step by step install guide for making Snipe-It work on Windows Server 2012 using IIS?  I'm finding bits and pieces here, but they are referencing PHP, database, etc, and no where does it show where I get these programs, what versions, when/where to install.

The IIS setup document only tells me how to create the site, and adjust permissions.  The dependencies page only states to download and run composer from the snipe-it directory.  That program is asking for some type of PHP command.

**Comment by JExactly** [comment]
@brudnicke you need to install PHP and a database app. These can be installed in IIS from the Micorsoft Web Platform (https://www.microsoft.com/web/downloads/platform.aspx) Install the platform installer so that you can add PHP (PHP 7 should work fine), MySQL 5.5 etc.. additionally, once PHP is installed, you will have PHP Manager appear in your IIS Manager, You can enable there as well as enable additional PHP extensions that are needed as referenced in the install guide.

Hope this helps!

**Comment by brudnicke** [comment]
Thanks!

Where is this installation guide? I’ve seen the one for IIS, but it doesn’t specify needed extensions (unless I’ve missed them).

**Comment by brudnicke** [comment]
Thanks for the information.  Was able to find the step by step requirements.  However, when i try to access the site, it doesn't come up.  Standard "The website cannot display the page".  I've restarted IIS, and the server, but with no luck.

**Comment by JExactly** [comment]
Did you make sure to apply your hostname to the .env file you are accessing from. Also, did you make sure you added a DNS record as well for your server in your DNS entries?
Additionally make sure you set your bind address to the IP for your host server in IIS

**Comment by brudnicke** [comment]
Not sure where I put a host name in the .env file.  Not seeing a reference to it.  As for DNS, I’ve created a record “snipeit” pointing to 10.10.199.12 (IP of website).  I’ve tried accessing the site at http://10.10.199.12 and http://snipeit , but each of them comes up with HTTP ERROR 500.

When I added the hostname snipeit.corp.domain.com to the bindings, when I try to hit the website, it brings up the generic IIS page.

Here is the .env file:

# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=ChangeMe
APP_URL=null
APP_TIMEZONE='UTC'
APP_LOCALE=en


# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=null
DB_USERNAME=root
DB_PASSWORD=password
DB_PREFIX=null
DB_DUMP_PATH='C:\\PROGRA~1\\MARIAD~10.1\\bin'

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=10.10.199.70
MAIL_PORT=587
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=ithelpdesk@domain.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=ithelpdesk@domain.com
MAIL_REPLYTO_NAME='Snipe-IT'


# --------------------------------------------
# REQUIRED: IMAGE LIBRARY
# This should be gd or imagick
# --------------------------------------------
IMAGE_LIB=gd


# --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME=snipeit_session
COOKIE_DOMAIN=null
SECURE_COOKIES=false


# --------------------------------------------
# OPTIONAL: CACHE SETTINGS
# --------------------------------------------
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync


# --------------------------------------------
# OPTIONAL: AWS S3 SETTINGS
# --------------------------------------------
AWS_SECRET=null
AWS_KEY=null
AWS_REGION=null
AWS_BUCKET=null


# --------------------------------------------
# OPTIONAL: MISC
# --------------------------------------------
APP_LOG=single
APP_LOCKED=false
FILESYSTEM_DISK=local
APP_TRUSTED_PROXIES=192.168.1.1,10.0.0.1
ALLOW_IFRAMING=false

The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by JExactly** [comment]
1) Make sure to apply your hostname(APP_URL=yourhostname.com) in the .env file. 

2.) Make sure you added a DNS record as well for your server in your DNS entries.

Additionally make sure you set your bind address to the IP for your host server in IIS.

One other thing. Make sure you have assigned the proper permissions as noted on this page for all the correct folders listed. https://snipe-it.readme.io/v3.0/docs/windowsiis

**Comment by brudnicke** [comment]
1.        I’ve added the hostname per instructions.  I’ve also setup the hostname in DNS, and checked that it’s resolving correctly.  I edited the bindings on IIS, and set the host name.  Bind is set to the IP address on the servers second network card.  I’ve verified the permissions on all the folders as suggested in the document url provided.

Site won’t respond.

The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by JExactly** [comment]
after you made all changes. did you restart IIS?

**Comment by brudnicke** [comment]
Yes.  Using the IISRESET command.

The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by brudnicke** [comment]
Not sure if this makes a difference, but I ran the php artisan key:generate command, but the key is still set to ChangeMe in the .env file.

The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by JExactly** [comment]
that makes a big difference. Yes, that key is important. You have created a copy of .env.example and made your changes and saved it as .env only correct? You should also be able to take the appkey and manually add it to your .env file. I would restart your site after that.

**Comment by brudnicke** [comment]
Yes.  I’m working with a .env file.  I’m using Notepad+++ to edit and save it.

Does it store the key somewhere after you run the command.  I enter the command, and it just goes right back to a command promp.t

The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by JExactly** [comment]
Yes, it is supposed to write the key automatically to the .env file. Are you running `php artisan key:generate` in the command prompt while inside of your snipeit directory?

**Comment by brudnicke** [comment]
Yes.  Should it be run from an elevated command prompt?

The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by JExactly** [comment]
I would, to make sure you have write access to the directory when the command is run.

**Comment by brudnicke** [comment]
I tried using the elevated command prompt, but it did not change the file.

I confirmed the security again.  The file also has everyone with full control.

The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by JExactly** [comment]
manually copy the key it generates on the screen to the .env save and restart IIS

**Comment by brudnicke** [comment]
It’s not generating a key (at least it’s not displaying one on the screen).

**Comment by JExactly** [comment]
I am currently out of ideas, Many someone else has some additional ideas

**Comment by snipe** [comment]
If it's not displaying a key, something else is wrong. Check your laravel log file after you run the key generation and see if anything shows up

**Comment by JExactly** [comment]
@snipe Maybe he didn't get composer installed properly and he is missing some dependencies?

**Comment by brudnicke** [comment]
Where is the laravel log located?

The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by JExactly** [comment]
@brudnicke the laravel log is located in /inetpub/www/%yoursnipeitdirectory%/storage/logs.

i was wondering, did you get composer installed in your snipe-it directory and run the composer commands to install all the dependencies?

**Comment by brudnicke** [comment]
There is no log there.

I did download and run composer from the snipe-it directory.  It went through something (no prompts) and then it was finished.

The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by JExactly** [comment]
Open an administrative command prompt, navigate into your snipe-it directory and run this command: `composer install --no-dev --prefer-source` once that run, it will install all your dependencies

**Comment by brudnicke** [comment]
Result output:

E:\Sites\Snipe-It>composer install --no-dev --prefer-source
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for intervention/image 2.3.x-dev -> satisfiable by in
tervention/image[2.3.x-dev].
    - intervention/image 2.3.x-dev requires ext-fileinfo * -> the requested PHP
extension fileinfo is missing from your system.
  Problem 2
    - Installation request for intervention/image dev-master -> satisfiable by i
ntervention/image[dev-master].
    - intervention/image dev-master requires ext-fileinfo * -> the requested PHP
extension fileinfo is missing from your system.

  To enable extensions, verify that they are enabled in those .ini files:
    - C:\Program Files (x86)\PHP\v7.0\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PH
P in CLI mode.

E:\Sites\Snipe-It>

The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by JExactly** [comment]
You need to make sure any extensions that are required are enabled. 
looks like it's only missing PHP fileinfo extension.

Open IIS Manager, open up  PHP Manager. Under PHP Extensions, enable php_fileinfo.dll. restart IIS for safe measure, rerun the command again.

You need to make sure all PHP extensions that are required are installed and enabled. These were listed under requirements in the hlp documentation here: https://snipe-it.readme.io/docs/requirements
That lists all required PHP extensions that need to be enabled. Also, enable php_gd2, this is the GD Library exttension that is needed as well.

Enable all required that are not already while you are in there, enabling fileinfo.

**Comment by brudnicke** [comment]
Lots of progress.  Thanks.  The extensions in question are installed.  I was able to generate a key and it was placed in the .env file.

When I try to hit the site now, it come ups to /setup with the error 404 – Directory Not Found.

The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by JExactly** [comment]
did you make sure to set your directory permissions for IIS as documented here:  https://snipe-it.readme.io/v3.0/docs/windowsiis ?

**Comment by JExactly** [comment]
Additionally, Make sure that under your sites Advanced settings in IIS, that your public directory is your physical path for exaple: C:\inetpub\wwwroot\%snipeitdirectory%\public

**Comment by brudnicke** [comment]
Yes.  I just re-verified, and the permissions are set as specified in that article.

The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by brudnicke** [comment]
More Info (it’s looking for a setup directory that does not exist under public)

Detailed Error Information:



Module
   IIS Web Core

Notification
   MapRequestHandler

Handler
   StaticFile

Error Code
   0x80070002

Requested URL
   http://snipeit.corp.birkeys.com:80/setup

Physical Path
   E:\Sites\Snipe-It\public\setup

Logon Method
   Anonymous

Logon User
   Anonymous

The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by brudnicke** [comment]
It is set correctly.

The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by JExactly** [comment]
https://snipe-it.readme.io/docs/common-issues#the-requested-url-setup-was-not-found-on-this-serv

Import the .htaccess rules into IIS URL rewrite. all should be good. There will be an error for one of the rules. that is ok

**Comment by JExactly** [comment]
I'm pretty sure this will resolve it for you.

**Comment by brudnicke** [comment]
I tried importing that one before, and I keep getting the rule error.  However, it will not let me save.  It keeps giving me the error (The data is the page is invalid.  Correct the data and try again.).



The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by JExactly** [comment]
I have attached a modified version. Use this for your import
[htaccessSnipeIT.zip](https://github.com/snipe/snipe-it/files/584478/htaccessSnipeIT.zip)

**Comment by JExactly** [comment]
you have to remove the entry that has the issue. it doesn't apply to IIS AFAIK

**Comment by brudnicke** [comment]
It doesn’t identify the offending string.

<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    # Make sure .env files not not browseable if in a sub-directory.
    <FilesMatch "\.env$">
    Deny from all
    </FilesMatch>

</IfModule>


The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by JExactly** [comment]
in the file I attached, I have removed the string already.

**Comment by brudnicke** [comment]
Apologies.  I didn’t see the attachment.  I downloaded and tried to import, but I received same data error.

The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by JExactly** [comment]
all you should have in the .htaccess is 
`<IfModule`` mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    # Make sure .env files not not browseable if in a sub-directory.
    <FilesMatch "\.env$">
    Deny from all
    </FilesMatch>
    
</IfModule>`

I just tested this on my IIS server and I was able to import the file I uploaded without issue.

**Comment by brudnicke** [comment]
In the Rewrite Rules box:

<IfModule mod_rewrite.c>
Options -MultiViews
# Make sure .env files not not browseable if in a sub-directory.
<FilesMatch "\.env$">
Deny from all
</FilesMatch>


Still unable to save.  Same data error.

The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by JExactly** [comment]
Were you able to successfully get this up and going?

**Comment by brudnicke** [comment]
Not yet.  I haven’t been able to get the modified .htaccess to import in to IIS.  It keeps giving me that invalid data error.

The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by JExactly** [comment]
You know, I totally forgot after V3 you no longer need to import the .htaccess as it is all handled with the web.config file in the public directory. I wouldn't worry about importing the url rewrite rules. However, as long as URL Rewrite is a component listed in you site components.. You should be good. The issue seems to me then would be that your default Physical path under your sites advanced settings is not set correctly.. for example: C:\inetpub\wwwroot\SNIPE-IT\public

![image](https://cloud.githubusercontent.com/assets/14076881/20279135/462f6f5e-aa75-11e6-99af-6e8786a25b47.png)

**Comment by brudnicke** [comment]
My physical path is pointing to E:\Sites\Snipe-It\public (which is where the public folder is located).  NOTE:  There is no setup directory located under Public.


When opening the website, I get:

[cid:image001.png@01D23E7A.CAA21DC0]


The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by JExactly** [comment]
Maybe @snipe has a better answer. I am sure there is no \setup directory because URL Rewrite handles the rewrite to the correct location for the setup.

**Comment by JExactly** [comment]
Also, I think what I would reccommend is that your remove and re-add proper permissions for the folders and restart your IIS server and see if anything changes. As well as make sure that your .ENV file has all it's proper settings and that your mysql user has proper rights to make changes to your database

**Comment by brudnicke** [comment]
What should be in the web.config file?  The one I have is blank.

The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by JExactly** [comment]
[web.zip](https://github.com/snipe/snipe-it/files/590428/web.zip)

**Comment by brudnicke** [comment]
Thanks.  The website came up to the config page.  It seems to have passed all the checks, but when I click create database tables, it goes to a “Whoops, something went wrong” page.

The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by JExactly** [comment]
I would check your laravel logs now

**Comment by JExactly** [comment]
Sounds like your database user doesn't have rights to do what it needs to the snipeit database you created.
https://snipe-it.readme.io/v3.0/docs/creating-a-database-and-db-user

**Comment by JExactly** [comment]
Were you able to resolve this @brudnicke ??

**Comment by brudnicke** [comment]
No.  I’ve gone through the permissions again, and checked the database settings, but it still won’t let me continue on to the ‘configure tables’ portion of setup.

**Comment by JExactly** [comment]
I would check your logs and drop them here

**Comment by seanandcara** [comment]
@brudnicke, it sounds like @JExactly is correct that your database user might not have permissions to create the tables. Hopefully, this is resolved and you're using Snipe-IT successfully.

However, if not I may be able to help. At this stage of the install process, a co-worker and I were having all sorts of problems with the URL Rewrite rules:

1. There were already URL Rewrite rules before importing the .htaccess rules, so we cleared those out.
2. After attempting to import the .htaccess file, the last rule was not able to be understood by IIS - per the developer, I removed the last rule (see https://github.com/snipe/snipe-it/issues/2489). 
3. After fighting with it for a while longer, we also figured out that the first rule was forcing HTTPS, so either you can remove that rule or set up SSL on your server (we chose the latter).

I'll attach the Windows Server/IIS install instructions that I made while going through this process. We have been using Snipe-IT successfully for a few months now and I've used the process on multiple test servers, so I think it's ready to be shared - I hope you find it helpful.

[Snipe-IT Install Instructions on IIS - SHARE.pdf](https://github.com/snipe/snipe-it/files/608107/Snipe-IT.Install.Instructions.on.IIS.-.SHARE.pdf)

**Comment by brudnicke** [comment]
Here’s the laravel log.

The information including any attachments contained in this document is confidential and is for the use only of the intended recipient.  If you are not the intended recipient, you should notify the sender and delete this message immediately.  Any distribution, disclosure, or copying of this message, or the taking of any action based on its contents is strictly prohibited.  

Birkey’s Farm Store, Inc.

**Comment by JExactly** [comment]
Nothing is attached, You will likely have to do it through the web.

**Comment by brudnicke** [comment]
Here is the laravel log.

[laravel.TXT](https://github.com/snipe/snipe-it/files/631222/laravel.TXT)

**Comment by JExactly** [comment]
@brudnicke All the errors in the log that I am reading, It appears that a connection to your database is not happening and therefor it cannot complete its steps. I would recommend double checking the database steps listed here: https://snipe-it.readme.io/v3.6.1/docs/creating-a-database-and-db-user
**(maybe start over with them to make sure everything is fresh and set properly)**

Is this a mysql DB? Can you supply what is listed in your .env file under : 
`# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=null
DB_USERNAME=null
DB_PASSWORD=null
DB_PREFIX=null
DB_DUMP_PATH='

**Comment by JExactly** [comment]
@brudnicke Did you get this resolved?

**Comment by brudnicke** [comment]
No.  I re-rant the database setup, but I still get the same “whoops, something went wrong” error.

**Comment by JExactly** [comment]
Is your DB located on your localhost?

**Comment by brudnicke** [comment]
Yes.

**Comment by JExactly** [comment]
have you tried updating to the latest version to see if your issue was a bug that was fixed? I know there was mention of fixes related to Pre-flight issues. Which is where you seem to be having problems.
