### ISSUE TITLE
Report export as CSV problum

### ISSUE THREAD

**Issue by asucrews** [snipe/snipe-it#2889]
#### Expected Behavior (or desired behavior if a feature request)

IE 11 report export as CSV should save has CSV file type.

-----

#### Actual Behavior

IE 11 report as CSV does not save as CSV file type. Only saves as text file or html file. it works in Chrome and Firefox.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

Snipe-IT version	 v3.4.0-9-g67315d8
PHP Version	         7.0.12
Laravel Version	         5.2.45
OS Version                CentOS Linux release 7.2.1511 (Core)
Install Method           manual installation/git
Page                         /reports/licenses
Stacktrace error         none
Brower console error none
Demo evn                 confirmed

**Comment by snipe** [comment]
Just rename the file to end in .csv

**Comment by asucrews** [comment]
Yes, that is option; however not all end user will do that or can do that.  I guess i just suggest end user not to use internet explorer. Thanks!
