### ISSUE TITLE
Logs out when saving or creating new asset

### ISSUE THREAD

**Issue by jackgarratt** [snipe/snipe-it#2890]
#### Expected Behavior (or desired behavior if a feature request)

When saving or creating asset

-----

#### Actual Behavior

Logs out every time you press save or create new asset. It will save thought if you keep logging in. 

-----

#### Please confirm you have done the following before posting your bug report:

- [/] I have enabled debug mode
- [/] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running Version v3.5.1-2-gd7222ae
- What OS and web server you're running Snipe-IT on Win Svr 2012R2 IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual install
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
[2016-11-07 15:34:55] production.DEBUG: Authenticating user against database.  
[2016-11-07 19:46:40] production.DEBUG: LDAP is enabled.  
[2016-11-07 19:46:40] production.DEBUG: Local auth lookup complete  
[2016-11-07 19:46:40] production.DEBUG: Binding user to LDAP.  
[2016-11-07 19:46:40] production.DEBUG: Local user jgarratt exists in database. Authenticating existing user against LDAP.  
[2016-11-07 19:46:40] production.DEBUG: Valid LDAP login. Updating the local data.  
[2016-11-07 19:46:40] production.DEBUG: Authenticating user against database. 
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database no

I've tried increasing session time too.

**Comment by snipe** [comment]
There's nothing built in that would cause that. Check that your APP_URL and your COOKIE_DOMAIN are set correctly in your .env file
