### ISSUE TITLE
[Feature Request] Export Licenses with Seat Assignments + Sort by Name for License Seats

### ISSUE THREAD

**Issue by TheVakman** [snipe/snipe-it#2892]
#### Expected Behavior (or desired behavior if a feature request)

I would like to see a report or some sort of ability to export licenses with their seat assignments. Example: I have a license for Adobe Acrobat with three hundred assignments and I want to export all seats in use.

Additionally, I'd like to be able to sort (within SnipeIT) the seat assignment section by their name versus only by seat number (let me know if I should put in a second feature request). The ability to sort would make it less important to have an export but both would be nice.
#### Actual behavior:
There is only the ability to export how many seats each license has with no user information and within seat assignments in SnipeIT, it can only be ordered by seat number (not by name).

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: 3.6.0-pre + 3.5.2
- What OS and web server you're running Snipe-IT on: CentOS 7 / Apache
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: License Reporting
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): Yes.

**Comment by wilsonlspacheco** [comment]
+1 (hosted costumer)

**Comment by snipe** [comment]
Exporting licenses has been added to the develop branch, however sorting licenses is a bit trickier than it seems, since licenses can be checked out to people *or* assets, so we have to sort across multiple tables.
