### ISSUE TITLE
Cant get working install at all

### ISSUE THREAD

**Issue by EnigmaZA** [snipe/snipe-it#2895]
#### Expected Behavior (or desired behavior if a feature request)

i expected it to work

-----

#### Actual Behavior

didnt work at all

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Latest
- Ubuntu Server 16.04 & ubuntu 15.04 using apache2, also tried IIS with no luck on server 2012 R2
-Both manual and install.sh
- just 403 or takes me to defualt apache2 page
- N/A
- no  stack trace
- Error 403
- N/A
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- I have tried reinstalling many times as well as changing active site directories in apache2
- No manual database editing

**Comment by snipe** [comment]
Sounds like your DocumentRoot is wrong. https://snipe-it.readme.io/docs/linuxosx#using-apache

**Comment by EnigmaZA** [comment]
iv tried that, 

as well as the install script installes the files to 

/var/www/snipeit/public

rather than 

/var/www/html/snipeit/public/

iv tried manually moving installed files across to the correct file structure but with no success.
![document root](https://cloud.githubusercontent.com/assets/12070020/20110939/11b59850-a5ef-11e6-9585-2fac71b24fc2.PNG)
![snipe-it config](https://cloud.githubusercontent.com/assets/12070020/20110938/11a68b44-a5ef-11e6-9757-0a753d405905.PNG)

**Comment by EnigmaZA** [comment]
also if i change fileroot to 

/var/www/snipeit/public/

i get this in browser:
![web error](https://cloud.githubusercontent.com/assets/12070020/20111154/de554950-a5ef-11e6-82ea-e96fb0a93cf6.PNG)

it resolves the name correctly and tries to open correct setup page but loads nothing

**Comment by snipe** [comment]
That's a DNS error. Do you have DNS set up for asset.local?

**Comment by EnigmaZA** [comment]
nope,

it automatically set it to that in the install

**Comment by snipe** [comment]
What's in your APP_URL in your .env file?

**Comment by snipe** [comment]
You need a browseable address, whether that's just localhost, or whatever it is. That name (or IP) needs to be set in the APP_URL section of the .env, per the install directions. You can either set up asset.local as a valid DNS name, or you can try localhost. Depends how you have your server set up.

**Comment by EnigmaZA** [comment]
neither works,

how can i make it just the ip no name resolves at all?

i tried tto just setit to the ip rather than asset.local or local.host or localhost and now can find setup file
![error](https://cloud.githubusercontent.com/assets/12070020/20111838/75932510-a5f2-11e6-8ce3-72b2e7f4bb69.PNG)

**Comment by snipe** [comment]
Not found could mean that your mod_rewrite isn't enabled. If you go to 10.0.0.6/index.php, what do you get?

**Comment by EnigmaZA** [comment]
exact same error,

pulls me back to /setup

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/common-issues#the-requested-url-setup-was-not-found-on-this-serv

**Comment by EnigmaZA** [comment]
rewite is already enabled but a file is missing from the file structure
![rewrite](https://cloud.githubusercontent.com/assets/12070020/20112206/1b39cf68-a5f4-11e6-8f34-28e887ac6af4.PNG)

**Comment by snipe** [comment]
Nothing on our end should be missing

**Comment by EnigmaZA** [comment]
its on apache2 side 
just dont know how to fix it

**Comment by EnigmaZA** [comment]
in gunna try again fresh and see how it goes

**Comment by EnigmaZA** [comment]
i now get this:

![new](https://cloud.githubusercontent.com/assets/12070020/20113272/6c3cce16-a5f8-11e6-9fb4-ffaedde6286e.PNG)

**Comment by snipe** [comment]
You'll have to enable debugging so we can see what the specific error is. Still, that looks a lot closer, since that's a Snipe-IT generated error.

**Comment by EnigmaZA** [comment]
![log1](https://cloud.githubusercontent.com/assets/12070020/20113811/9c9ed660-a5fa-11e6-9aae-a997522f499f.PNG)
![log2](https://cloud.githubusercontent.com/assets/12070020/20113813/9ce2b312-a5fa-11e6-81e0-8b580025205e.PNG)
![log3](https://cloud.githubusercontent.com/assets/12070020/20113849/c945f1e4-a5fa-11e6-8974-2aeb4e8062f6.PNG)
![log4](https://cloud.githubusercontent.com/assets/12070020/20113850/c9828a28-a5fa-11e6-9afc-ba1372e36ee4.PNG)

**Comment by snipe** [comment]
So, looks like your DB credentials are wrong

**Comment by EnigmaZA** [comment]
i cant seem to solve this database issue,

not too proficient in mysql

**Comment by snipe** [comment]
How did you run this install? Manual or install.sh?

**Comment by EnigmaZA** [comment]
install.sh

**Comment by snipe** [comment]
It should have asked you what you want the MySQL password to be somewhere in that install.sh setup. Whatever you gave it there, that's what your DB password should be in .env

**Comment by EnigmaZA** [comment]
still no luck :( 

really want to get this working

is it possible for me to give you remote access and maby you can see whats going on?

**Comment by snipe** [comment]
No.

**Comment by EnigmaZA** [comment]
ok i got it working,

I needed to edit the apache2.conf file to chnge:

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride none
        Require all granted
</Directory>

To:

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride all
        Require all granted
</Directory>

I then restarted apache2 and it all worked

**Comment by TobiasMedia** [comment]
Thank you EnigmaZA, that worked for me!

Installing PHP BCMath Arbitrary Precision Mathematics for FireFly III on Ubuntu 16.04.

Coming from: https://firefly-iii.readthedocs.io/en/latest/installation/server.html and https://www.digitalocean.com/community/tutorials/how-to-install-snipe-it-on-ubuntu-16-0

**Resulting in:** 

Not Found
The requested URL /setup was not found on this server.

**Solution:**

1. open the apache2.conf file with the following command: 

nano /etc/apache2/apache2.conf

2. find  & change **none** to **all**

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride **all**
        Require all granted
</Directory>

3. [crtl] + x + [y] save
4. command: sudo service apache2 reload
5. refresh your browser 🥇
