### ISSUE TITLE
asset checkin

### ISSUE THREAD

**Issue by scott-fed** [snipe/snipe-it#2896]
#### Expected Behavior (or desired behavior if a feature request)

I would expect a user (non admin or non super)  could not check in an asset that is not checked out to them.
-----

#### Actual Behavior

When a user (non admin or non super) checks in an asset not checked out to them, the system allows this behavior.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
   v3.5.2-11-g5a835a5

- What OS and web server you're running Snipe-IT on
   centos-release-7-2.1511.el7.centos.2.10.x86_64
   Server version: Apache/2.4.6 (CentOS)
   Server built:   Jul 18 2016 15:30:14

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
   install.sh
   (https://mangolassi.it/topic/6967/installing-snipe-it-on-centos-7-and-mariadb)

- If you're getting an error in your browser, include that error
  No error is triggered, the action is permitted.

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
 on the checkin page
- If a stacktrace is provided in the error, include that too.

- Any errors that appear in your browser's error console.

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
   This action is reproduceable on the demo site. 
    User = testuser
    Password = testuser 
    Asset = test asset 
    You can checkout to anyone. and then log in as testuser and check it back in.

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
I'm not able to reproduce this locally.

**Comment by scott-fed** [comment]
I've just logged into the demo site and assigned asset "test asset" to user "Oren Beer", If you log in with user "testuser", you can now try to check it back in.

**Comment by scott-fed** [comment]
Where you able to try this with the example I set up on the demo site? Thanks.

**Comment by snipe** [comment]
User testuser has checkin abilities, so this is behaving as expected.

<img width="1025" alt="screen shot 2016-11-11 at 7 58 06 pm" src="https://cloud.githubusercontent.com/assets/197404/20235523/47c8d7f2-a849-11e6-9a62-ea091ccb8182.png">
