### ISSUE TITLE
Missing list box custom field type

### ISSUE THREAD

**Issue by muflone** [snipe/snipe-it#2897]
#### Expected Behavior (or desired behavior if a feature request)

Since version 3.4 the custom fields should allow the use of List Boxes for choosing a field value.

-----

#### Actual Behavior

After upgrading v3.3.0 to 3.5.2 (with upgrading instructions) in the new custom field page I can only select the Text Box field type. There's no way to choose a List Box type.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.5.2-11-g5a835a5

- What OS and web server you're running Snipe-IT on
Ubuntu GNU/Linux 14.04 with Apache 2.4.7

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Downloaded tar.gz file, unzipped and rsync-ed files from untarred folder to /var/www/html

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
Cannot reproduce the issue in the demo

- Include what you've done so far in the installation, and if you got any error messages along the way.
During the upgrade (php composer.phar install --no-dev) my workstations hadn't internet connection so the upgrade process has hang. After I got the internet connection I was able to proceed with the upgrade with no issues.

- Indicate whether or not you've manually edited any data directly in the database
No modifications to the database or any other data

**Comment by muflone** [comment]
![schermata da 2016-11-09 01-32-12](https://cloud.githubusercontent.com/assets/1284163/20122924/c3d3b004-a61b-11e6-8dc3-a367bf977729.png)

**Comment by ttibke** [comment]
I'd be looking for this as well. The company would like the ability to add a "Department" field, but have a dropdown for that available.

**Comment by snipe** [comment]
I can't reproduce this locally or on the demo. 

<img width="940" alt="screen shot 2016-11-11 at 6 37 31 pm" src="https://cloud.githubusercontent.com/assets/197404/20235096/efe78fa2-a83d-11e6-8d42-8c4ab11f46a8.png">

**Comment by muflone** [comment]
I've just installed a fresh copy of snipe 3.5.2 without upgrading and the List box choice now appears.

There was some issue in the upgrade process.
