### ISSUE TITLE
License contracts and license linking for upgrades

### ISSUE THREAD

**Issue by avary69** [snipe/snipe-it#2899]
#2752 speaks about various Microsoft contract types. In order to break that down into more "manageable" pieces I suggest the following features

- separate section for license contracts (they would then be selected in a dropdown inside the license)
- linking of licenses (so that an upgrade or in Microsoft's case Software Assurance could be linked to its base license)

**Contracts** should have at least these fields
- Name
- Company (the one from Admin -> Companies)
- Vendor
- Contract Type (Dropdown with values from a new admin section "contract types" - one field is enough)
- Contract Number
- Start date
- End date
- Notes

The **license linking** would just require an additional dropdown in the license where you could select any of the existing licenses. It might make sense to filter by Manufacturer, if not empty. (Typically upgrades would come from the same manufacturer)
With this feature you could add an upgrade license link it to an existing license. There could be an issue with the seats of the base license as you can't assign more upgrades than you have base licenses, but that is manageable manually. 
In case of Microsoft's Software Assurance you then could create the new license that in the name or notes would state that it is SA only. You would assign the contract (see above) which most likely would be a different one than the contract in the base license. Finally you check-out the new upgrade (or SA) license to the asset and check-in the previous assigned license.

**Summary:**
2 new sections (contracts + contract types) and
2 new fields in licenses (contract + base license) needed

In general as mentioned in other feature requests (sorry I didn't write down the number) custom fields for licenses would be a great (especially if you could sort them whereever you want -> also between the fixed fields).

**Comment by ttibke** [comment]
Agree with all of this as well.
