### ISSUE TITLE
Create a full user asset/component/license/accessory report

### ISSUE THREAD

**Issue by proweb01** [snipe/snipe-it#2903]
This is just a feature request. When a user leaves the company, I would love for there to be an easy way to pull a FULL report about literally everything assigned to a particular user. For example:

John Doe leaves the company. I put John's name in the report and it shows me his:

Assets
  Licenses assigned to that asset
  Components assigned to that asset
Licenses assigned to the user
Accessories assigned to the user
Consumables assigned to the user

It's easy to collect all this info with some clicks, but would be nice to have a report that does it. The custom asset report would be sufficient if it included components, licenses, accessories and consumables.

**Comment by snipe** [comment]
That stuff should show up on their user detail view.
