### ISSUE TITLE
import Assets with username format problem

### ISSUE THREAD

**Issue by chenboshiun** [snipe/snipe-it#2905]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

i import  CSV format for assets, that appear "Checked Out to" field not username, maybe username format problem, Example:

i import brianhuang's asset record(CSV format) to snipe-it, but "Checked Out to" field not brianhuang 

![import image](https://cloud.githubusercontent.com/assets/5372796/20169944/1e6c2cf4-a765-11e6-907f-8c483696298d.png)

but exist brianhuang in people:

![people](https://cloud.githubusercontent.com/assets/5372796/20169983/591d92a2-a765-11e6-856e-ed98589e6d54.png)

i try to set Username Format in backend seeting as blow:
* First Name Last Name
* First Name Initial Last Name

but can't solve this problem

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 
   v3.5.2-11-g5a835a5
- What OS and web server you're running Snipe-IT on 
   Ubuntu 14.04.5 LTS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
   manual installation
- If you're getting an error in your browser, include that error
   No
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
   No
- If a stacktrace is provided in the error, include that too.
   No
- Any errors that appear in your browser's error console.
   No
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
   No
- Include what you've done so far in the installation, and if you got any error messages along the way.
   No
- Indicate whether or not you've manually edited any data directly in the database
   No

**Comment by chenboshiun** [comment]
BTW, I upload csv format
[NB-snipe-it.xlsx](https://github.com/snipe/snipe-it/files/582877/NB-snipe-it.xlsx)

**Comment by chenboshiun** [comment]
Hello

i fixed, username and name require full in in csv format file

**Comment by snipe** [comment]
> i fixed, username and name require full in in csv format file

I don't understand what you mean by this.
