### ISSUE TITLE
Search Manufacturer Field [Feature Request]

### ISSUE THREAD

**Issue by ttibke** [snipe/snipe-it#2906]
#### Expected Behavior (or desired behavior if a feature request)
When performing a search, include the Manufacturer field (and potentially any field) in the search results. Applicable to both the License and Asset section. Without a lot of custom search capability, this will help fill that gap.

(what you expect to happen goes here)
When performing a search, include the Manufacturer field in the search results.

-----

#### Actual Behavior
(what actually happens goes here)
Search will not search the Manufacturer field in the License section. It will return no results of a search term if it is only included in the Manufacturer field.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.4.0-9-g67315d8
- What OS and web server you're running Snipe-IT on: centos 7(1511)
- What method you used to install Snipe-IT: manual installation
- If you're getting an error in your browser, include that error: N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: N/A
- If a stacktrace is provided in the error, include that too: N/A
- Any errors that appear in your browser's error console: N/A
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): Yes
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database: No

**Comment by snipe** [comment]
Manufacturer is already included in Assets

**Comment by ttibke** [comment]
First of all, I was referencing the License section. Second of all, I'm aware the field is available and appreciate that fact. My issue is that the search function won't return any result that's in the Manufacturer field.

**Comment by snipe** [comment]
You said applicable to assets and licenses.  If that's not what you meant, that's fine, but I'm sure you can see how I'd parse it that way. At any rate, this is fixed on develop, per the corresponding commit.
