### ISSUE TITLE
[feature request] Assets sidebar shows Status Labels or even better if it can be customised

### ISSUE THREAD

**Issue by orygen** [snipe/snipe-it#2907]
#### Expected Behavior (or desired behavior if a feature request)

When I click on the Assets sidebar, it will show my Status Labels, rather than 
Pending, Undeployable, Archived etc. as there is possibility that 2 or more status labels share the same Status Type (Deployable, Undeployable, Archived, Pending). 

An even better one is to be able to customised the what views we want for the Assets sidebar.
-----

#### Actual Behavior

When clicking the Assets sidebar, it's showing : List All, Deployed, Ready to Deploy, Pending etc.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
There is already an option to set status labels as visible in the side nav
