### ISSUE TITLE
MAC Address auto-formatting

### ISSUE THREAD

**Issue by webtroter** [snipe/snipe-it#2913]
#### Expected Behavior (or desired behavior if a feature request)

Autoformatting of the MAC Address field.
I'd like to be able to enter multiple MAC Address format in this field.

00:00:00:00:00:00
00-00-00-00-00-00
000000000000

Are the three types that I can think of

-----

#### Actual Behavior

Bad formatting error

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 
3.5.2
- What OS and web server you're running Snipe-IT on
IIS 10 on Windows Server 2016
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual

**Comment by snipe** [comment]
You'd have to write a custom regex for that then.
