### ISSUE TITLE
Asset tag numbers generated by 10 or 20 ie 01520-01530. how can i fix this?

### ISSUE THREAD

**Issue by ronomatic** [snipe/snipe-it#2918]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](http://docs.snipeitapp.com/common-issues.html)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by DWSR** [comment]
Just wanted to confirm that I'm also seeing this issue:
**Snipe-IT Version:** v3.5.1-gd7222ae
**OS Version:** Ubuntu 16.04.3
**Webserver:** Apache2 with PHP 7.0.8
**Installation Method**: Manual
**Specific page:** /hardware/create
**Reproducable on demo:** No
**Browser errors:** N/A
**Relevant log snippets:** N/A
**Manually edited database:** No

**Comment by snipe** [comment]
What do you have for "Length of asset tags, including zerofill" in settings?

**Comment by DWSR** [comment]
I have 5 set, and no prefix.

**Comment by snipe** [comment]
Can you give me an example of a few generated sequences?

**Comment by DWSR** [comment]
02052,02062,02072

**Comment by DWSR** [comment]
I updated to 3.6.2, but the error persists

**Comment by ronomatic** [comment]
Thank you

**Comment by snipe** [comment]
If it were fixed, this issue would have been closed
