### ISSUE TITLE
Feature Request: Assign multiple assets to asset maintenance entry

### ISSUE THREAD

**Issue by tueor** [snipe/snipe-it#2920]
#### Expected Behavior (or desired behavior if a feature request)

Ability to easily assign multiple assets to one maintenance entry, or duplicate maintenance entry, or bulk import maintenance entries

-----

#### Actual Behavior

looks as though I'd need to create the same maintenance entry for each asset, this becomes tedious when you have a maintenance agreement covering hundreds of devices.

-----

**Comment by jeffkimanga** [comment]
Did you get a solution to this? Are we still waiting on the feature?
