### ISSUE TITLE
Assets-Import bug: Chinese characters shows like "???"

### ISSUE THREAD

**Issue by linglongtong** [snipe/snipe-it#2921]
I use import function to import my asset information, just test one item.
I click the process button, then an error shows:

Warning The following Items were not imported because of errors.
Asset	Errors
_empty_	Asset: The asset tag field is required. 

Here is the error snapshot:
![error](https://cloud.githubusercontent.com/assets/23185284/20299724/127648f8-ab57-11e6-9071-3ff46aa765ce.jpg)

Here is my test csv file: 
[test.zip](https://github.com/snipe/snipe-it/files/591472/test.zip)

Please help check the problem.

- Version of Snipe-IT you're running: v 3.4
- What OS and web server you're running Snipe-IT on : SUSE LINUX 11 ENTERPRISE

**Comment by snipe** [comment]
Looks like you have some weird encoding going on in your CSV. 
<img width="1024" alt="screen shot 2016-11-15 at 1 40 15 am" src="https://cloud.githubusercontent.com/assets/197404/20300547/926e75a4-aad4-11e6-9ab2-530595facb0c.png">

**Comment by linglongtong** [comment]
Yes,  the problem is from the weird encoding. 
The weird encoding is Chinese characters which Snipe-IT cannot support.
If I use English characters instead of Chinese characters, it can be imported correctly. 

Can you make Snipe-IT support Chinese characters importing? I think China will have many potential users.

The Chinese characters should be like this:
![image](https://cloud.githubusercontent.com/assets/23185284/20303871/7b904e5e-ab68-11e6-9c66-286226f35040.png)

Here is the CSV without Chinese characters.
[test.zip](https://github.com/snipe/snipe-it/files/591742/test.zip)

**Comment by zdong08** [comment]
When importing the Chinese garbled  @linglongtong  Have you solved the problem
![image](https://cloud.githubusercontent.com/assets/13311479/20384348/6c56f410-acee-11e6-82b0-a89df4da2533.png)

**Comment by linglongtong** [comment]
@zdong08 Not yet. 

@snipe Is it difficult to fix the bug? It is better to support both Simplified Chinese encoding and Traditional Chinese encoding. Thank you in advance.

**Comment by G1Hu6m0n1t0r** [comment]
Hi,I have the same problem too,but i  already fixed it now, hope to be helpful.
change the code in  ObjectImportComman.php  (Folder: snipe-it/app/Console/Comman/), line 299
use toUTF8 instead fixUTF8 .
   ```
public function array_smart_fetch(array $array, $key, $default = '')
    {
        return array_key_exists(trim($key), $array) ? e(Encoding::fixUTF8(trim($array[ $key ]))) : $default;
    }
```
Why, see https://github.com/neitanod/forceutf8/issues/7,as the owner writed:

"But more importantly thing is that if your data includes characters that do not exist in Latin1 (let's say russian or chinese characters), your "fixed UTF8", they would be transliterated or ommited, so beware."

fixUTF8  function seems slower than toUTF8,and shuld not use it in production,i'm not sure,maybe is true.
-------------------------------------------
长话短说，
1. 如果你的乱码不是???，说明服务器语言设置不对，echo $lang或者locale看下是不是zh_cn_UTF8，你需要更改下语言设置。
2 到服务器上面上传文件夹的路径下，我的是storage/private_uploads/imports/assets/，cat一下上传的文件，看是不是正常中文。
3. 如果语言设对了，按我上面说的将fixUTF8改成toUTF8，我测试没乱码问题了。至于原因，那个库的作者也说了。

**Comment by linglongtong** [comment]
@G1Hu6m0n1t0r  It works well. Thank you for your contribution.

**Comment by chenboshiun** [comment]
@G1Hu6m0n1t0r  thanks.

**Comment by Nabeel-Shahid** [comment]
I was having similar issues when trying to import Unicode (Arabic) Asset names.

Thanks for help!
