### ISSUE TITLE
I want to move to a new server

### ISSUE THREAD

**Issue by pvhkai** [snipe/snipe-it#2926]
Dear all,

I want to move from an old server to a new one. 

The old one:
- IIS
- mysql

Do you know if I need something to do that nothing will get lost?

Thanks

**Comment by JExactly** [comment]
I would think it should be an easy transition. The steps I personally would take are as follows:

1. Backup my SQL database if it will be hosted on a new server.
2. Make sure that the new server is currently running no version lower than v3 if your current install is V3 and above.
3. Install Snipe-IT and all dependencies like it was a new install and configure all your server settings.
4. Import your Database back into your SQL server (if it was moved to a new server)
5  Profit $$

( I moved my install from an IIS server to a LAMP setup. was a pretty smooth transition. Only minor issues I had were not related to Snipe-IT or the install instructions)
