### ISSUE TITLE
LDAP Authentication not working

### ISSUE THREAD

**Issue by dankingdon** [snipe/snipe-it#2928]
#### Expected Behavior (or desired behavior if a feature request)

When configuring LDAP integration correctly, users should be able to login by authenticating against LDAP. 

-----

#### Actual Behavior

 At present despite all users syncing ok, ldap users are unable to login and recieve the error "the username or password is incorrect." debug output always returns invalid username or password.  Our LDAP server is also reporting invalid authentication attempt in its log files, again quoting invalid username or password despite using the correct credentials to log in.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - 3.6.0
- What OS and web server you're running Snipe-IT on - Server 2012 R2, IIS with PHP 5.6.24
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - 

> [2016-11-15 16:07:03] production.DEBUG: LDAP is enabled.  
> [2016-11-15 16:07:03] production.DEBUG: Local auth lookup complete  
> [2016-11-15 16:07:03] production.DEBUG: Binding user to LDAP.  
> [2016-11-15 16:07:03] production.DEBUG: Local user dkingdon exists in database. Authenticating existing user against LDAP.  
> [2016-11-15 16:07:03] production.DEBUG: User dkingdon did not authenticate correctly against LDAP. Local user was not updated.  
> [2016-11-15 16:07:03] production.DEBUG: Authenticating user against database.  
> [2016-11-15 16:07:03] production.DEBUG: Local authentication failed.

Windows AD event viewer lists the following error: 
Audit Failure: 
Account For Which Logon Failed:
	Security ID:		NULL SID
	Account Name:		dkingdon
Failure Information:
	Failure Reason:		Unknown user name or bad password.
	Status:			0xC000006D
	Sub Status:		0xC000006A

All other LDAP functionality is working as expected.

**Comment by therealjoshuad** [comment]
Just for grins, could it be this issue? #2648

**Comment by dankingdon** [comment]
Hi,

Apologies for not spotting that issue earlier, I dismissed it as not relevant as the solution was the missing domain name.  In my case I needed "sAMAccountName=" instead of "uid=sAMAccountName" in the LDAP Authentication query field.   I had miss understood the documentation.  

Thanks for the speedy response.
