### ISSUE TITLE
Feature request: Serial Number for each component.

### ISSUE THREAD

**Issue by igloo777** [snipe/snipe-it#2934]
Hello!
Interesting to have possibility to add Components with serial number of each component.
Example: i want to add 10 New Disk into Components, and i want to add serial number to each Disk. Later I want to connect each disk to dedicated asset Server. In "Components" of each Server i want to see exact Disk with it's serial number. The same logic can be applied to other kinds of components - Ram, CPU, Power supplies and so on. 
What do you think about it? Is it difficult to implement such logic?

**Comment by sainirahul** [comment]
Hi Team,
I also fell the same requirement that we can add serial number to component and accessories. 
It would be great to have such a feature.
Thanks

**Comment by dmeltzer** [comment]
There is a serial number field added for components now, but it's one serial number for all instances of that component.  The idea of components is that they are interchangable, and it doesn't matter which one you are using.  The only items tracked individually at this point are licenses and assets.

**Comment by igloo777** [comment]
Simple example: we have good disks in work, good disks in reserve, broken disks in test, broken disks in a boxes, each one should have ID to track it's location and status. Disks a interchangeable, but still uniq.
The same with a RAM modules.

**Comment by snipe** [comment]
@igloo777 that's not currently how compoments are meant to work

**Comment by chriswiggins** [comment]
@snipe is there a usage example for how components are supposed to work? That would be much appreciated 👍

**Comment by igloo777** [comment]
How we can see components in UI (sorry for my english):
- when clicks to 'Components' menu, we enter into the page with a list of components (as it is today), it can be components by types or smth else.. (Component Name, Location, Category, Total, Min. QTY, Remaining, Parent Component, Actions and so on..)
- next when we clicks on exact Component Name, we enter into the page with a list of components of the same type (for example Disk WD - parent component name) - list of fields: Component Name, Location, Category, Serial number, Status (or tag), Asset (connected to asset or blank), Parent Component, Actions
- next, when we clicks to the name of exact component, we enter into the page with a detailed list of component attributes (fields) - same as it's done for assets

**Comment by gremlinuk** [comment]
I agree with @igloo777 - it woudl be great to allocate a serial number per component. You can have lots of components the same, but with different serial numbers (think hard drives etc) but i cant think of any situation where more than one component would have the same serial number (surely they are always unique to that piece of hardware)?

**Comment by Hickory420** [comment]
Hello, so I have a question...
First, an example: Components are: cpu, ram, gpu, psu, and motherboard. Asset is the server chassis (all components combined). Each component technically has a unique serial number....

So what would be the current "workaround" for this this instance? If we switch the components to assets, then we can no longer assign the component (now labelled as an asset) to an actual asset. Any thoughts or suggestions? 

Cheers.

**Comment by kiltain** [comment]
Tracking Components with serial numbers would help; in my company assets are all tagged items such as laptops and desktops, anything over $1000. I would love to be able to have a docking station be  able to  be a component that is assigned to an asset and provide a unique serial number. i have 15+ units of each dock and would like to track them but still have them listed under a single component heading.
Thank you.

**Comment by PhantomPhreak** [comment]
I'm trying to start using Snipe-IT now, but there some things that doesn't meet my requirements: components and accessories management.

As i can see on the Component's creating page, "Components are items that are part of an asset, for example HDD, RAM, etc.", but i want to track these items (HDD, RAM, etc) by serial number and by inventory number, and i want to have serial number (and inventory number too, optionally) assigned to each component. But as i can see there is only one serial number for bunch of components. Honestly, i'm confused how a lot of components may have one serial?

The same for accessory. For example, i have IP-phones, it's accessories, and i want to manage them too, separately, but i can't create SN or inventory number for each device. This problem described in #3408

Also, i'd like to have possibility to group my components/accessories, because flat structure isn't convenient for components managing. For example, i'd like to have group "WD 2TB Black" in HDD category, with a list of components inside.

It would be great to see this features in Snipe-IT.

Thanks a lot!

**Comment by igloo777** [comment]
Hi SnipeIT developers! I'm glad that you are working hard on this product. Still waiting this feature to start to use SnipeIT.

**Comment by PhantomPhreak** [comment]
I agree with igloo777. Components are not consumables (checkout and forgot) and may be really expensive hardware (like network modules in previous example), and may have a warranty (it's important for the disks, for example). Also, components may have different states: ready for use, in test, in maintenance/warranty and so on. At my glance it's more important that for assets. If power supply or hard disk fails in a server (server is an asset), we're not changing whole server (not changing asset state), but changing failed part (component). That's why it's really important feauture to tack each component by serial. And it should be a key feature. Unfortunatelely, without this feature we can't start using Snipe IT.

Still waiting for it. Thanks a lot!

**Comment by cslucian** [comment]
Hello,

Maybe the following workflow will work for you

Create components only with qty.1 so if you have 10 hdd create 10 new components.

Maybe devs. can implement the auto increment feature from Asset Tag to have unique tags for each component.

In this way you can enter the Serial Number for each component and assign them to assets.

Best of luck

**Comment by PhantomPhreak** [comment]
It can work, but it looks like workaround and:
1) We will loose the feature of grouping the components by type. For example, i would like to group disk drives by the model for better organizing. See (https://demo.snipeitapp.com/components)
2) We will loose the feature of tracking amount of components of each type, and set the lower threshold for each type of components.
3) We will have to set some excessive information about the component (company, purchase date, costm etc.)

So, i don't think that it's a good solution of our problem but anyway, thanks for suggestion!

**Comment by Puddl36lum** [comment]
I'm trying to solve a related problem and was wondering if anyone had a suggestion:

In our inventory, components (switches, hard drives, etc) are also tagged with a bar code and linked to assets.  Is there a way to add a field so that i can add the bar code number?  Can i add a custom field to 'components?'

**Comment by mario-tremblay** [comment]
the lack of this feature is a deal breaker for me too.

i want to be able to add multiple ssd harddrives of the same model with all their own serial number but want it to count for the minimum quantity alert..

**Comment by Puddl36lum** [comment]
+1 for a usage example.  
 
We have just purchased 10 internal hard drives,  All the same model (WD10EZEX), each with different serial numbers.  

can't input as assets because we don't have asset tags on most internal components and the asset tag field must be unique.  Would also prefer not to input 10 of the same model drives as individual components.

**Comment by wilsonlspacheco** [comment]
+1 to our company (Snipe-IT Hosted Client)

We bought a lot of accessories and components with S/N, it was important to us be able to manage the serial numbers. Or, in the limit, like the licenses, have a field of notes to put the serial number when we check-in the Accessory / Component to a User/Asset and can see the history of this accessory in a table with the notes field visible. It is also an alternative solution to us.

**Comment by hostbrew** [comment]
This feature is highly desirable. A big deal breaker for me as well.

**Comment by Hickory420** [comment]
A year and a half later, and still no sign of this happening... what a shame. @snipe do you have any plans to listen to your user base/the community? Is this something we can expect, or are we holding our breath?

Cheers.

**Comment by PhantomPhreak** [comment]
I'm tracking snipe-it releases and there are a lot of new fancy features. But all they are useless for me without this simple, but basic feature for hardware accounting.

**Comment by dmeltzer** [comment]
@Hickory420 I'm sure if it were terribly important to someone they would have taken the few hours to contribute the feature to the codebase, it's one of the beautiful things about open source software, after all :)

**Comment by snipe** [comment]
> @snipe do you have any plans to listen to your user base/the community? Is this something we can expect, or are we holding our breath?

@Hickory420 Perhaps you've not been paying attention, but we ship new features constantly - certainly faster than most open source projects. To suggest I don't listen to the community is, frankly, offensive and obnoxious - and certainly not the way to inspire us to work on a feature any faster.

**Comment by Hickory420** [comment]
> To suggest I don't listen to the community is, frankly, offensive and obnoxious - and certainly not the way to inspire us to work on a feature any faster.

@snipe I apologise for coming across as offensive and obnoxious. That was not my intention. I was just a little frustrated when I wrote that. I'm sorry. This is an excellent open source project. I have implemented it a while ago in the company I work for, and everyone who uses it, loves it. So, I thank you very much for all of your efforts, it is very much appreciated. :)

> This is a non-trivial change to the business logic, and it's on the list
Awesome :)

@dmeltzer I think I speak for most of the users when I say, If I could, I would! :P

To everyone who has contributed to this project, we thank you! <3

**Comment by rkantos** [comment]
@Hickory420 Working for a company, using Snipe-IT with it. I hope you have made at least some kinds of calculations on how much Snipe-IT has saved for you? Maybe there would be something you could contribute too.. Perhaps consider Bountysource ;) https://www.bountysource.com/teams/snipe-it/issues

**Comment by Blizzardo1** [comment]
I have a custom Inventory System at work that works the way it should be, every element has a serial number bound using a component item in store. This means each element inherits from the root component.

For Example, the Component (Seagate 1TB HDD) has 30x Elements with their own serial number, that way we can track where the drive is, whether it's currently in a machine, or in our inventory's Available, Re-Inventory, or RMA. The problem with the system I have is that I can't necessarily keep track of other components that are not trackable via serial number such as but not limited to Power Cables, Converter Trays, Keyboards, Mice, etc.

The way I saw SnipeIT is that I can associate a component via serial number to a device, however, it's only an internal serial number and not tracked by the component's true unique number.

Since this Platform is Open Source, My Dev Team would be able to add such a feature, but out of the box, however, I see that other people in this thread are talking on the same page as I am.

**Comment by niteowl099** [comment]
This issue is listed as closed, does that mean it has been implemented or is it something that is no longer being considered for development?

**Comment by nielsentamau** [comment]
> I am still very much interested in this feature.

Same.

**Comment by PhantomPhreak** [comment]
I talk to snipe-it support about it. They said that they won't and have no plans to implement this feature.
That's absolutely incomprehensible for me how they still can do fancy features missing this basic functionality

**Comment by rkantos** [comment]
Wouldn’t the custom fields functionality work here? You could have a text area with any formatting necessary for listing serial numbers: https://youtu.be/AmKc0GuQbAU?t=2m7s

**Comment by PhantomPhreak** [comment]
> Wouldn’t the custom fields functionality work here? You could have a text area with any formatting necessary for listing serial numbers: https://youtu.be/AmKc0GuQbAU?t=2m7s
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/35f2da83879686b0d43e2aa81079009e51d1ecb0/68747470733a2f2f692e7974696d672e636f6d2f76692f416d4b63304775516241552f687164656661756c742e6a7067"><img alt="" height="14" src="/yts/img/favicon_144-vfliLAfaB.png"> YouTube**[Snipe-IT Turbo Tutorial: Custom Fields](https://www.youtube.com/watch?v=AmKc0GuQbAU)**Become an expert in handling custom fields for assets in about 7 minutes with our first-ever user tutorial. Forgive Alison - she's a nerd, not a voiceover ar...

Possibly, it will. But currently custom fields are apllicable for Assets only (see from 5.55 in the video you attached), so here is a feature request (opened since october 2017) https://github.com/snipe/snipe-it/issues/4261

**Comment by bl00d666** [comment]
I think this is a very important feature. We were about to use the system. We had high hope for it, but this is a deal breaker for us. Hey Dev (@snipe), you have done a great job with the system. We really like it. I just don't know how we could manage our inventory without having component with multiple item and serial number in it. Just for the purchase date and warranty alone it's a deal breaker. Having a single component for each serial will also make the asset more complicated to use and will make the threshold irrelevant. I hope you will reconsider the feature.

**Comment by Hickory420** [comment]
Feature request opened on Nov 17, 2016.

Quoting @snipe from May 8, 2018
> This is a non-trivial change to the business logic, and it's on the list, but so are hundreds of other feature requests.

Quoting @PhantomPhreak less than a month ago.
> I talk to snipe-it support about it. They said that they won't and have no plans to implement this feature.

I am so confused... If it's non-trivial, why hasn't it been implemented yet? I'm not having a shot at the devs. It's a genuine question. This is a hugely popular request. Is it a technical issue, or something else?

**Comment by PhantomPhreak** [comment]
> Hi,
> 
> Unfortunately, that is not on our roadmap for the near future, so you may have to go elsewhere to be able to use this feature right away..
> 
> Sorry we're not able to be of more help at this time : /
> 
> Sincerely,
> 
> Victoria Pak
> Operations & Support Engineer
> Grokability, Inc.
> support@snipeitapp.com
> 844-4-SNIPE-IT (844-476-4734)
> 
> 3960 West Point Loma Blvd | Suite H69 | San Diego CA 92110

@Hickory420 just go elsewhere to be able to use this feature right away..

**Comment by Blizzardo1** [comment]
In all honesty that's terrible support.

I would rather use community driven software instead of an enterprise... this is horrible.

**Comment by captains1stm8** [comment]
I would like to see this feature added, as well.  Monitors, for example, are components.  I need to know the total number of each model that we have, but I also need to keep track of serial numbers for warranty purposes.

**Comment by Hickory420** [comment]
Over three years later and still not listening to the community...
And apparently (quoting the project owner here)

@snipe 
> a non-trivial change to the business logic

is too much to ask for...

I've given up on this software. I just like too see how long this will go for. 3 years and counting :P

**Comment by clifforddsouza** [comment]
Another 3 years have past by and still no signs of a non-trivial change to the business logic being implemented.

I've also given up on the software, it's sad that a basic necessity as this is being ignored for so long

hope this gets implemented

**Comment by djmixman** [comment]
Bringing this in for the new year... I don't understand the logic behind having 42 hard drives with the same serial number. It does not make any sense to me what so ever.

**Comment by Hickory420** [comment]
I have been watching this thread for a while. 5 years for a 'non-trival' change. There is some humor in watching an open source project ignore its user base. Also sad to watch. I only follow this issue to see how long it takes before this project dies or this feature gets implemented. I'm betting on the former.

To anyone looking for asset management software, don't waste your time with this.

**Comment by TerraTech** [comment]
(NOTE: I just started using Snipe-IT today, so still learning)

I see the "component" has a place to enter a serial number, but what would make it easier to add multiple HDD/SSD is the ability to **Duplicate** (or Clone) a component and then just paste in the new serial number + Save.  I think this would make for a somewhat quick interim solution, that can be retained even after the above feature request is implemented.

I have not yet explored the API or Import feature yet - however from a GUI standpoint, "Duplicate" would be useful.

If others agree, I could add this as a new feature request.

**Comment by KevinWirth93** [comment]
@snipe you wrote that's not currently how compoments are meant to work.

Could please explain it to me how the componentes are meant to work ?

Right now it makes no sense to me not to have an individual serial number for e.g an HDD for a server.

So is it meant to create one component for each individual serial number ?

best regards

Kevin

**Comment by gabriel-vanca** [comment]
This is still not fixed 6 years later. Shocking.

**Comment by snipe** [comment]
@gabrielv33 I welcome your pull request.

**Comment by Hickory420** [comment]
https://github.com/snipe/snipe-it/issues/2934#issuecomment-890918877
> @snipe you wrote that's not currently how compoments are meant to work.
> 
> Could please explain it to me how the componentes are meant to work ?
> 
> Right now it makes no sense to me not to have an individual serial number for e.g an HDD for a server.
> 
> So is it meant to create one component for each individual serial number ?
> 
> best regards
> 
> Kevin

This person has genuine questions... I wonder what the reply is...

🍿

**Comment by clifforddsouza** [comment]
This thread started on November 17, 2016, some 6.35571412 Years ago

Snipe added the feature request on Nov 18, 2016. 

I gave up on this great software in November 2019 just because of the lack of this feature.

Now 3.3506 years later................ I get a mail from Github and what do I see? Zilch progress...

Maybe the month of Nov 2023 is the destined time for implementing this feature...

**Comment by snipe** [comment]
If you care about serials, they are assets. I have no idea why the fuck this is so hard for you to understand. 

@gabriel-vanca you just said this, and this is my personal invitation to go fuck yourself six ways to Sunday: 

> Apparently they expect free labour from the open source community to fix a basic feature of their commercial product.

This is so off-base it’s laughable. 

Yeah, we’re known for enlisting free labor. We have given you nothing but free labor and put up with your bitching the entire time. 

I’m going to take a moment to be the better person here - which, with the two of you, is legitimately difficult. 

You have benefited off of my free labor for a decade. I’ve asked for nothing in return. Not a single thing. 

So yo have you here in my repo saying this is absurd and laughable. 

If you have a better free solution use it. We would never want you as a customer anyway.

**Comment by snipe** [comment]
@clifforddsouza I guess I’ll see you then.

**Comment by snipe** [comment]
Legit question to everyone on this thread - why is not tracking them as assets not working for you? That was the original answer and will always be that. If your serials are so critical, they’re assets. You don’t need to print a tag, but ffs - just make them assets, check them out to another asset, and we can all sleep at night. This is legit not that hard.

**Comment by snipe** [comment]
@Hickory420 - as I mentioned earlier in this (very long) thread, just track is as an asset. Components are bibs and bobs, where serials don't matter. Just track it as an asset. Make a category for it, track it that way, and move on.
