### ISSUE TITLE
Feature Request: Text QR code instead of URL

### ISSUE THREAD

**Issue by samdotto** [snipe/snipe-it#2936]
Expected Behavior (or desired behavior if a feature request)

I wish i could use QR codes to quickly take note of asset number and serial number (or even any custom field of choice) instead of the URL becouse our mobile phones aren't allowed to access the internal network.

-----

Actual Behavior

QR codes only provides the URL to Snipe-it's registered asset.

-----

**Comment by linglongtong** [comment]
Yes, I agree.
