### ISSUE TITLE
Multi company select for each user

### ISSUE THREAD

**Issue by riaandeyzel** [snipe/snipe-it#2937]
Expected Behavior (or desired behavior if a **_feature request_**)
Would like to be able to select multiple companies per user. Belong to more than one Company
Possible check boxes next to Companies to select more than one.
(what you expect to happen goes here)

I have created 2 companies, 
1. "Furniture PE" (To list All the Furniture of the Staff members in Port Elizabeth)-(1 HR Manager)
2. "IT Equipment PE". (To list All the IT Equipment of the Staff members in Port Elizabeth)-(39 Staff members)
The Same staff members have both Furniture and IT equipment in their offices.
The problem is that if I grant our HR Manager Admin rights for the "Furniture PE" company and he clicks on the users menu he is the only person in that list because he does not have rights to the other company "IT Equipment PE", and they all belong to the "IT Equipment PE" company only.
He can therefore also not click on the User an view the Furniture and his IT Equipment of that staff member at the same time.
I Do not want the HR manager to see all the IT Equipment on the Assets List All menu, only the "Furniture PE" company Items.

Did I 
-----

#### Actual Behavior

(what actually happens goes here)

when I click on the Checked out to user name I get an error message " Error: Insufficient permissions!"
I assume it is because this user only belongs to the other company, and therefore even the Admin user (HR manager) can not view this users info

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - Version v3.4-14-g2a8ab06
- What OS and web server you're running Snipe-IT on - Centos 7 & Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by drcryo** [comment]
+1 I'm waiting for it as well. Exactly for the same purpose (Furniture and IT Equipment).
More system approach would be to have an option of assigning admin rights on Category level though.
