### ISSUE TITLE
Delete Custom Field already assigned to Fieldset (2.1.1-55-g701c16f)

### ISSUE THREAD

**Issue by alomanto** [snipe/snipe-it#2941]
Preamble - We are running an older version of Snipe-IT (listed below) and cannot upgrade to the newest version as it is running on a shared webserver, and our admin does not want to upgrade the dependencies for stability reasons. 

#### Expected Behavior (or desired behavior if a feature request)

**I expect to be able to delete a custom field that is assigned to a fieldset.**

-----

#### Actual Behavior

**Once a custom field is assigned to a fieldset, there is no option to delete it.** 

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - **v2.1.1-55-g701c16f**
- What OS and web server you're running Snipe-IT on - Linux Mint, I believe. I am not the server admin. 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - **Manual Installation**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - **No error.**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - **Admin / Custom Fields**
- If a stacktrace is provided in the error, include that too. - **N/A**
- Any errors that appear in your browser's error console. - **N/A**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). - **We are running an older version. Demo is running v3.**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. - **N/A**
- Include what you've done so far in the installation, and if you got any error messages along the way. - **Been using Snipe-IT for a few months. The database is filled with various assets, asset models, custom fields, etc.**
- Indicate whether or not you've manually edited any data directly in the database - **No.**

**Comment by snipe** [comment]
You would have to go into the database and edit the `custom_field_custom_fieldset` to remove the join record between the custom field and the fieldset. We don't really have the resources to go back and add features to older versions.
