### ISSUE TITLE
Where is the import code

### ISSUE THREAD

**Issue by zdong08** [snipe/snipe-it#2943]
HI，snipeit  I want to modify your code into CSV , I only want to import rtd_location_id not import  locations  name, How to modify this？I want to solve the Chinese garbage problem in this way，Thanks
![image](https://cloud.githubusercontent.com/assets/13311479/20417879/8e3bad88-ad83-11e6-8daf-d722ce30d272.png)

**Comment by zdong08** [comment]
![image](https://cloud.githubusercontent.com/assets/13311479/20417930/f84573c6-ad83-11e6-81aa-4404baefa838.png)
I didn't find out how to define the import field.

**Comment by snipe** [comment]
If you save your Excel file as a Unicode (not UTF-8), does the chinese characters issue still happen?

The import file is in `app/Console/Commands/ObjectImporter.php`, but that file changes often, so your changes will likely be blown out with your next update.

**Comment by zdong08** [comment]
Thank you！

**Comment by zdong08** [comment]
When I use Unicode (not UTF-8) ，import csv Will remind me asset tag Required 

![image](https://cloud.githubusercontent.com/assets/13311479/20418766/d72f0df2-ad8b-11e6-8a36-dc616b9c7367.png)

My csv file
![image](https://cloud.githubusercontent.com/assets/13311479/20418772/e732443a-ad8b-11e6-85fb-80a3958150f8.png)

Convert GBK into Unicode
![image](https://cloud.githubusercontent.com/assets/13311479/20418798/116f7178-ad8c-11e6-8ac9-306573f5e057.png)

**Comment by snipe** [comment]
When you open the Unicode file in a text editor, are there any weird chaacters?
