### ISSUE TITLE
Mass assignment Fillable property not working

### ISSUE THREAD

**Issue by gaurav8k** [snipe/snipe-it#2944]
Instead of 
`protected $fillable = ['name','model_id','status_id','asset_tag'];` 
All fields are getting updated in assets table. Why so?

**Comment by snipe** [comment]
A little more info would be useful here. What are you trying to do, where are you trying to do it, etc.

**Comment by gaurav8k** [comment]
How to disable updating other fields by allowing only those field specified in $fillable property?

**Comment by snipe** [comment]
In what context? What are you trying to do?
