### ISSUE TITLE
import Chinese Traditional CSV to Snipe-IT v3.6, show "???"  character

### ISSUE THREAD

**Issue by chenboshiun** [snipe/snipe-it#2946]
Hello:

i want to report a like bug, as below:
-----

#### Actual Behavior

(what actually happens goes here)

i imported Chinese Traditional CSV to Snipe-IT , show "???"  character, how to fix it？

 Chinese Traditional CSV File:
![chinese_import](https://cloud.githubusercontent.com/assets/5372796/20428276/1df20050-adc3-11e6-8b1a-3d19d48106ee.png)

After imported Chinese Traditional CSV,  show "???"  character
![import_csv_error_code](https://cloud.githubusercontent.com/assets/5372796/20428300/4454036a-adc3-11e6-9a9e-029f0c6ea4c1.png)

whether or not support imported Chinese Traditional in the furture?

Thansks.

-----

#### Please confirm you have done the following before posting your bug report:

- [o] I have enabled debug mode
- [o] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
   Ans:v3.6.0-g91caba0

- What OS and web server you're running Snipe-IT on
   Ans:Ubuntu 14.04.5 LTS

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
   Ans:manual installation

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
   Ans:No

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
   Ans:No

- If a stacktrace is provided in the error, include that too.
   Ans:No

- Any errors that appear in your browser's error console.
   Ans:No

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
   Ans:No

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
   Ans: view laravel.log, No relation error for importing Chinese Traditional CSV 

- Include what you've done so far in the installation, and if you got any error messages along the way.
   Ans:No

- Indicate whether or not you've manually edited any data directly in the database
   Ans:No

**Comment by now163** [comment]
#2938   #2921

**Comment by linglongtong** [comment]
@chenboshiun  Hello, Taiwan friend. I met the same question. I'm trying to solve it.

**Comment by snipe** [comment]
Closing as deuplicate of #2921
