### ISSUE TITLE
[feature request]  add LDAP/AD location filed in LDAP setting

### ISSUE THREAD

**Issue by chenboshiun** [snipe/snipe-it#2947]
Hello

we use LDAP/AD sync feature to update people's base profile(EX: password, mail, Employee Num...etc), but no Location field, so we must select location and update all member profile,
but some member locate in different office, so correct member step by step

because we have location in LDAP , for example:

extended LDIF
LDAPv3
base <dc=xxxx,dc=com> (default) with scope subtree
filter: cn=jackchen
requesting: ALL

jackchen, people, xxxxx.com
dn: cn=jackchen,ou=people,dc=xxxx,dc=com
mobile: 0xxx-xx-xxx
o: xxxxx-xxxxx-xxxxx
givenName: xxxx
sn: jackchen
ou: people
l: Build 9F10

i hope to add LDAP/AD location filed in LDAP setting, Thanks.

**Comment by drcryo** [comment]
Syncing the manager and company property would be useful as well.

**Comment by snipe** [comment]
Again, all this gets tricky, since location and manager fields tie into other fields. If a location or a manager don't exist, for example, we have to create them on the fly during the sync, whoch can slow things down. It's why we haven't done that already. It's not out of the question, but when you're importing thousands and thousands of LDAP users, additional overhead can mean the webpage itself times out before the process is complete.

**Comment by drcryo** [comment]
Thank you for quick answer and totally agree to that. Is there any chance to move this options to env file as setting, so users can choose what to sync depends on size of their directory?

**Comment by snipe** [comment]
Not in the .env, no, we'd probably just add it to the LDAP settings with the other mapped fields.

**Comment by Guenny0488** [comment]
As i also had a look on the Manager Field within AD and Snipe-It. Maybe you can set the requirement that the manager has to be part of the LDAP Focus the user want's to load into Snipe-It. Just to prevent additional functions and processes during import

**Comment by skleinau** [comment]
Hello,

we just upgraded to 3.6.4. 

We do have exact the same issue, we need to adjust the query every time we do a sync. It would already be sufficient if the filter could be defined together with location in the CMD execution as an option.

This would allow us to run two cron jobs and therefore sync by location.

Thanks
Stefan

**Comment by danieldavidson123** [comment]
I believe this may correspond to what I am trying to do currently. 

Is there any way to sync LDAP Field: Office > SnipeIT User Field: Location?

If this is in relation what is the status of this? Is it included in 4.0?
