### ISSUE TITLE
Need to be able to export reports in xls format

### ISSUE THREAD

**Issue by kfw9257** [snipe/snipe-it#2950]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

My primary end-user needs to be able export reports into xls format and doesn't want to have manipulate CSV files. Could this feature be added? Or at least could another report be created that contains all the data fields and exports to xls?
-----

#### Actual Behavior

(what actually happens goes here)

Can only export in xls format on certain reports but not all.

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 3.5.2
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
You can open CSV files in Excel.

**Comment by kfw9257** [comment]
The problem with CSV files is that they don't have the same data that excel files do for creating charts in Excel. 

[link](https://neverbounce.com/help/working-with-csvs/)

**Comment by snipe** [comment]
That doesn't really make any sense. Import it into Excel, save it as an XLS.

**Comment by kfw9257** [comment]
If it were up to me, that's what I'd do but i'm speaking for the end user. She doesn't want CSVs. And I see in a lot of other asset managers, they do allow you to export in xls.

**Comment by snipe** [comment]
That's a lot of development work to do simply because someone doesn't want to take one extra step to save as XLS from CSV. I'd accept a pull request if someone created one, but otherwise I don't see this being a priority for development.

**Comment by kfw9257** [comment]
I may do it myself just for a learning experience. I'll get in touch if I'm able to do it.
