### ISSUE TITLE
assets tag not necessary

### ISSUE THREAD

**Issue by zdong08** [snipe/snipe-it#2951]
hi，snipeit  
How to modify  assets tag not necessary，Because I don't want to import it every time.
it has no meaning to me.
I know that it can be set to automatically increment, but when the import still need to enter，thank you

**Comment by dmeltzer** [comment]
Asset tags are the only unique identifier for an asset.

**Comment by zdong08** [comment]
But I can't use this feature here. I need Id.

**Comment by snipe** [comment]
That's not possible at this time.
