### ISSUE TITLE
Add filed quantity and reason for Checkout function

### ISSUE THREAD

**Issue by vipbk09** [snipe/snipe-it#2952]
Hi All,

Please support me to add 2 filed (quantity and reason) for Checkout (Accessory or Consumable) function.

Currently we only checkout one and can not note a reason.

**Comment by avary69** [comment]
The possibility to checkout multiple licenses to the same asset in one action would also be needed. It is very popular among software vendors to license the cores of a CPU. I have a server that needs 20 core licenses, which currently requires 20 check-out actions.
