### ISSUE TITLE
DB Queries

### ISSUE THREAD

**Issue by vinotnj21** [snipe/snipe-it#2954]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)
Hi Snipe,
      Where I can find query for updating asset. Because I want to add one more DB query to alter my external table whenever update happens to an asset.

#### Please confirm you have done the following before posting your bug report:

- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues):YES
- [x] I have enabled debug mode:Yes

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: 3.5.2
- What OS and web server you're running Snipe-IT on Winodws 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database no manual edit to DB

**Comment by dmeltzer** [comment]
app/Http/Controllers/AssetsController@postEdit() is the method thats called on updating an asset (from the web form).  There is currently no way to hook into events.  You might instead try to hook into the Asset::updating event that Eloquent throws--see https://laravel.com/docs/5.3/eloquent#events.  This method would keep your changes much more self contained and make merging better in the future.

**Comment by vinotnj21** [comment]
Thank you for you email i will try your instructions.
