### ISSUE TITLE
view asset  Permissions

### ISSUE THREAD

**Issue by s41771178** [snipe/snipe-it#2955]
With super administrator privileges can view all the assets, replaced with administrator privileges and have all the other permissions, but prompted No matching records found
![1](https://cloud.githubusercontent.com/assets/23526238/20483264/1468bc34-b02c-11e6-9e7a-b8dad7d95956.png)
![2](https://cloud.githubusercontent.com/assets/23526238/20483271/1968dba6-b02c-11e6-9529-10943e204316.png)
![3](https://cloud.githubusercontent.com/assets/23526238/20483273/1de7f2de-b02c-11e6-9e1b-d0813f3f77da.png)
![4](https://cloud.githubusercontent.com/assets/23526238/20483274/237a5052-b02c-11e6-8c8a-3197df99c685.png)

**Comment by snipe** [comment]
Do you have full company support enabled in Admin > Settings?
