### ISSUE TITLE
Custom Fields not saving on edit asset

### ISSUE THREAD

**Issue by delinski111** [snipe/snipe-it#2959]
#### Expected Behavior (or desired behavior if a feature request)

I set a value in a custom field, and save. When returning to the same asset and selecting edit, the field should remain filled in with the same information as before, and be there when I hit save again if nothing was changed.

-----

#### Actual Behavior

When I enter a value into a custom field, and hit save the info sticks. I can leave/ refresh and it is fine.

Once I click on edit again for that asset, all the custom fields are null, and if I select save (even without clicking into those fields) they all become blank/null.

I have lost ALL of the data in all of my custom fields for every asset due to this issue. (we just went through each asset to fix a value, so each one needed to be edited, which resulted in all custom fields now being blank)

![customfields_blankonedit](https://cloud.githubusercontent.com/assets/22087997/20537503/63ef781c-b0bb-11e6-9c36-617f2b343370.gif)

I have also rerun all the steps for upgrading, and there is nothing to migrate.
Clearing Browser Cookies did not help either.

-----

#### Please confirm you have done the following before posting your bug report:

- [ X ] I have enabled debug mode
- [ X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.6.0-g91caba0

- What OS and web server you're running Snipe-IT on
Linux, Ubuntu 14.04

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Any Asset

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
As far as I can test, no.

- Include what you've done so far in the installation, and if you got any error messages along the way.
Complete install, no issue, been using this DB for weeks without fault.

- Indicate whether or not you've manually edited any data directly in the database
No

**Comment by hbrecht** [comment]
Same issue. Values are blanked out on the form and then consequently saved as empty.

**Comment by asidorenko-nexonia** [comment]
Also having this issue. The values are indeed saved in the database in the assets table, but are never displayed again when editing an asset, which loses the value.

**Comment by snipe** [comment]
This is fixed on dev now. Sorry about that.
