### ISSUE TITLE
SQL State Error

### ISSUE THREAD

**Issue by Ny0tNy0t** [snipe/snipe-it#2960]
Hi,

kindly need advice how to solve the problem, 
after complete installation by option no.3, i takes reference from
(https://mangolassi.it/topic/6967/installing-snipe-it-on-centos-7-and-mariadb/84)

so once reboot, and log to localhost the pages show error

1. PDOException in Connection.php line 333:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.settings' doesn't exist

2. QueryException in Connection.php line 729:

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.settings' doesn't exist (SQL: select * from `settings` limit 1)

regards for your assist. 

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running --> v3.6.0
- What OS and web server you're running Snipe-IT on -->
Ubuntu 16.04
apache2

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
-->install.sh

**Comment by Ny0tNy0t** [comment]
same issue #582,

after i run ,

php artisan app:install ?

is show error 
 [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "app:install" is not defined.
  Did you mean one of these?
      migrate:install
      app:name

**Comment by Ny0tNy0t** [comment]
is solved ..

i run this command,

php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan migrate
php artisan config:clear

**Comment by snipe** [comment]
That documentation is not official documentation, and is quite out of date. Official documentation is always here: https://snipe-it.readme.io

**Comment by Ny0tNy0t** [comment]
Hi Snipe,

thanks for replay,

if i can suggest, at Official Documentations may be can create more detail, mean step by step like the link I 
post before is easy for beginner like me.
