### ISSUE TITLE
Where are LDAP settings and other configs saved?

### ISSUE THREAD

**Issue by absolutejam** [snipe/snipe-it#2967]
Sorry to create an issue for this, but I hope it's just a quicky!

I want to ensure all of my configs are accessible via. a docker volume in case of container recreation - Do you have a more comprehensive list of what needs to be backed up?

Thanks!

**Comment by snipe** [comment]
It deoends on the version. In v3, most configuration options are stored in a .env file at your project root, except for LDAP settings which are stored in the database.
