### ISSUE TITLE
Feature Request - Testting email from UI Web

### ISSUE THREAD

**Issue by Ny0tNy0t** [snipe/snipe-it#2968]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

If possible to have UI to setting the email (pop/smtp/imap) and test the email, maybe part of settings on web menu.

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running -->V3.6.0
- What OS and web server you're running Snipe-IT on --> ubuntu v16.04, apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) --> install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
We have that as part of the preflight

**Comment by Ny0tNy0t** [comment]
Hi snipe,

thanks for replay,

sorry if i want to know, what that mean on preflight ?

**Comment by snipe** [comment]
The pre-flight setup screen: https://snipe-it.readme.io/docs/pre-flight-setup

**Comment by Ny0tNy0t** [comment]
Hi Snipe,

Thanks for update,

That part I already testing, and no notification or feedback from that,
Settings parameter on .env already correct.

maybe can add up like this Snipe ;

![image](https://cloud.githubusercontent.com/assets/23697109/20585582/d9449240-b22e-11e6-9396-93d3ead0e1a2.png)

**Comment by snipe** [comment]
Trying to edit a .env file from a web form is often difficult, depending on your operating system, and the .env shouldn't be writable by the web server anyway.

**Comment by Ny0tNy0t** [comment]
Hi Snipe,

The .env is 1 time setting right before pre-flight ? and when pages load -- only read the parameter at .env file ?, sorry if i wrong :)
so i think once setting done like barcode settings, label, default EULA, it will not writeable the file. (i guest that setting not store on .env file)

**Comment by snipe** [comment]
That's correct, those values are stored in the database. The way Laravek works, pulling mail information out of the database is not that straightforward. It wants to be reading those mail setting values from the .env file, as the app itself loads.

**Comment by Ny0tNy0t** [comment]
Hi Snipe,


Thanks for explanation, and this is an excellent project
