### ISSUE TITLE
Problem to host with Ubuntu Server

### ISSUE THREAD

**Issue by TheAggy** [snipe/snipe-it#2970]
Hello,

i have problems to host the software (V 3.6.0) with ubuntu server.

if i try to open the website i get following error messages in my browser:

1. QueryException in Connection.php line 729: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.settings' doesn't exist (SQL: select * from `settings` limit 1)

2. PDOException in Connection.php line 333: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.settings' doesn't exist

With the command "php artisan db:seed" i get following error messages:

1. [I]Iluminate\Database\QueryException]
SQLSTATE[42S02]: Base Table or view not found: 1446 Table ´snipeit.companies´ doesn't exist (SQL: truncate `companies`)

2. [PDOException]
SQLSTATE[42S02]: Base table or view not found: 1146 Table ´snipeit.companies´ doesn´t exist

After installing Ubuntu Server 16.04 (tried 14.4 too same errors) with LAMP-Server option, i use the wget variant to download snipeit.
i made the chmod command and the i start the install.sh with "sudo .\install.sh"
After Installalation i directly try opening the website

i read the installing guide like 100 times and i dont know how to make it work

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by hbrecht** [comment]
Same issue on Debian 8 with manual install (git clone).

**Comment by snipe** [comment]
Try running: `php artisan migrate`

**Comment by TheAggy** [comment]
Hello Snipe,

thank you that worked! :)

i just do "php artisan migrate" and all worked nice. thank you :)

**Comment by hbrecht** [comment]
Works fine for me as well, however, I expected that this would be one of the major things the web-setup would do :-)
Anyhow, thanks a lot for the quick and helpful response!

**Comment by snipe** [comment]
It's supposed to, but I think a bug was introduced in the middleware that's causing it to bomb out in the middleware if migrations haven't been run yet. The bug is new to 3.6 I think, when we added the google Authenticator two factor middleware

**Comment by snipe** [comment]
This is now fixed on develop
