### ISSUE TITLE
Purchase Cost Maximum value

### ISSUE THREAD

**Issue by ghamerh** [snipe/snipe-it#2971]
how can i change maximum purchase cost values. i have assets worth more than million

**Comment by JONDERITU** [comment]
@ghamer make sure you are running the latest version of snipe-it and run migrations

**Comment by ghamerh** [comment]
i'm running Version v3.6.0-g91caba0
_________________________________________________________________________________________
C:\xampp\htdocs\Snipe-IT>php artisan migrate
[33m**************************************[39m
[33m*     Application In Production!     *[39m
[33m**************************************[39m

 [32mDo you really wish to run this command? (yes/no)[39m [[33mno[39m]:
 > yes

[32mNothing to migrate.[39m

**Comment by ghamerh** [comment]
Finally i found it, Its a databse config problem i changed Decimal (8,2) to (10,2). It's working fine now

ALTER TABLE `assets` CHANGE `purchase_cost` `purchase_cost` DECIMAL(10,2) NULL DEFAULT NULL;
