### ISSUE TITLE
nginx config problems on CentOS 7

### ISSUE THREAD

**Issue by taylordrake** [snipe/snipe-it#2976]
#### Expected Behavior (or desired behavior if a feature request)

nginx will be the webserver and I'll be able to access SnipeIT through forced SSL

-----

#### Actual Behavior

nginx fails to start if I try to point the .conf file towards the snipeit installation

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: **3.6.0**
- What OS and web server you're running Snipe-IT on: **CentOS 7/nginx**
- What method you used to install Snipe-IT: **install.sh**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs: **NA** 
- Include what you've done so far in the installation, and if you got any error messages along the way:

It's been a rollercoaster with this. I had to learn a lot in a short time and I'm still pretty n00b, so forgive me if this is all a stupid line of inquiry.

I installed the current version (3.6.0) on CentOS 7 running nginx because my employer wants forced SSL. I did not set up my server prior to downloading/installing Snipe-IT.

Originally, I attempted to use apache, and after dealing mainly with user permission errors from install.sh and composer downloading the dependences, and after I downloaded and updated PHP to 5.5.21. Installed PHP-FPM and nginx for the server side, because I wanted to run pre-flight, but I cannot for the life of me get nginx to start. As a note here: I did set up all SnipeIT options for SSL (cookies, htaccess).

If I modify the .conf file, it says it failed due to the HTTP and Reverse Proxy server. Again, forgive me if this is a silly question, but I'm not sure what I'm doing wrong.

The server is currently a virtual machine, but I was able to set up regular mysql databases and myphp-admin with Fedora prior to this. I'm just not sure how to configure nginx correctly for this and I've been googling and retrying for like 3 days so far. Any help you have is greatly appreciated.

- Indicate whether or not you've manually edited any data directly in the database: **No**

**Comment by snipe** [comment]
Can you paste the specific error you're getting from Nginx?

**Comment by taylordrake** [comment]
Thank you so much for replying, and I'm sorry I was so vague. I realized my problems, mostly... Still getting an error.

So, I switched my global nginx config back to the default one, and commented out the listening on port 80 but made sure it noted to include conf.d/*.conf for modular configs.

Went to conf.d and added snipeit.conf, which I filled with your pre-made config file from snipe-it website, making sure to set the path for my keys, set the root path to my snipeit project: /var/www/html/snipeit/public

Doing forced SSL. My only problem is that I'm still getting the stock nginx page and it's not auto-redirecting me to https instead of snipeit and/or preflight? I guess I'm more having an issue with nginx than with snipeit, at least at this point.

I will post up my config files from nginx +/- any relevant path names/etc.

Thanks again for your help!

**Comment by snipe** [comment]
If you delete the default site config from nginx, does that help?

**Comment by snipe** [comment]
(The NON-Snipe-IT one)

**Comment by taylordrake** [comment]
Sort of... I've actually got a 502 bad gateway error currently. Which may be my own fault.

**Comment by taylordrake** [comment]
And I figured it out, PHP-FPM was misconfigured, so I've got an error page that says "Whoops, looks like somthing went wrong"...

I _think_ this is a snipe-it error now, so I'm super happy.

**Comment by taylordrake** [comment]
Alright, troubleshot that. My error now is too many redirects.

**Comment by snipe** [comment]
![hugged-with-my-mind](https://cloud.githubusercontent.com/assets/197404/20771546/b5c07652-b6fe-11e6-8b3b-1d553d3f41d8.gif)
