### ISSUE TITLE
File does not exist: /var/www/html/snipeit/api

### ISSUE THREAD

**Issue by remrat** [snipe/snipe-it#2977]
#### Expected Behavior (or desired behavior if a feature request)
Attempting to "Add a new model".  

-----

#### Actual Behavior
Nothing happens.  If I go into Developer Mode in the browser, it reports:

Failed to load resource: the server responded with a status of 404 (Not Found)
create:1089 Uncaught TypeError: Cannot read property 'error' of undefined(…)
http://helios03/snipeit/api/models Failed to load resource: the server responded with a status of 404 (Not Found)

In my /var/log/httpd/error_log file:
[Sun Nov 27 20:45:38 2016] [error] [client 10.10.100.21] File does not exist: /var/www/html/snipeit/api, referer: http://zelios03/snipeit/public/hardware/create
[Sun Nov 27 20:47:43 2016] [error] [client 10.10.100.21] File does not exist: /var/www/html/snipeit/api, referer: http://zelios03/snipeit/public/hardware/create

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
3.6.0
- What OS and web server you're running Snipe-IT on
CentOS / Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Installer script
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No error displayed in the browser
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Trying to add a new asset, then Add A New Model
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
Nope
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
nope

**Comment by snipe** [comment]
This usually happens if the APP_URL doesn't exactly match the URL yuou're trying to access the site from.

**Comment by snipe** [comment]
Try changign your APP_URL from `http://helios03/snipeit` to `http://zelios03/snipeit`.

**Comment by remrat** [comment]
Looks like the problem was in the .env file...  Thanks for the good eyes!

**Comment by snipe** [comment]
![turtle high five](https://cloud.githubusercontent.com/assets/197404/20697392/c9d440da-b5ad-11e6-9562-4552098592f6.gif)
