### ISSUE TITLE
Category/Asset Models menu 

### ISSUE THREAD

**Issue by tx7** [snipe/snipe-it#2981]
Hi,
I would like to thanks you guys for created a beautiful and useful open-source program.
I had used GLPI projects in the past, but it not friendly as Snipe-IT.

Instead populate all the Asset Models when create a new asset, it would be easier and save time if you sort the models base on Category.

i.e: Asset Tag>>Category: laptops>>>Models: Latitude E7440, Latitude E7450, Inspiron 15R....

Is this possible?

Thanks.

**Comment by snipe** [comment]
Hi @tx7 - that's a good suggestion. We'll see if we can add that into a future release.

**Comment by tx7** [comment]
Ok, thanks.
