### ISSUE TITLE
snipeit:license-import not importing, Produce License NOT created message.

### ISSUE THREAD

**Issue by stf675** [snipe/snipe-it#2982]
#### Expected Behavior (or desired behavior if a feature request)

**command line import as described at
https://snipe-it-manual.readme.io/docs/importing-licenses**

-----

#### Actual Behavior

running command 
`php artisan snipeit:license-import /var/tmp/test.csv --domain=test.com --email_format=filastname`

produce

```
======= Importing Licenses from /var/tmp/test.csv =========
No user data provided - skipping user creation, just adding license
Full Name:
First Name:
Last Name:
Username:
Email:
License Name: ACCESS 2010 - APPLICATIONS
Serial No: none
Licensed To Name:
Licensed To Email:
Seats: 1
Reassignable: 1
Supplier: Microsoft
Maintained: 0
Notes:
Purchase Date:
------------- Action Summary ----------------
Supplier Microsoft already exists
Something went wrong! License ACCESS 2010 - APPLICATIONS was NOT created
=====================================
```

CSV file (tried with and without username)

```
User Name, User Email, Username, Software Name, Serial, Licensed to Name, Licensed to Email, Seats, Reassignable, Supplier, Maintained, Notes, Purchase Date

,,Available,ACCESS 2010 - APPLICATIONS,none,,,1,Yes,Microsoft,,,
```

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running   **3.6**
- What OS and web server you're running Snipe-IT on **Centos 7**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **install.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **no**

- Indicate whether or not you've manually edited any data directly in the database **No**

**Comment by dmeltzer** [comment]
Hi.

I think that it is because the serial number is required, with a minimum length of 5 characters (and you have "none" which is four characters.  The item is failing validation at the moment, which leads to that error.

**Comment by stf675** [comment]
Thank you dmeltzer, you were right on the mark.  I made SN longer and it worked perfectly. 

Probably worth mentioning somewhere in documentation.
