### ISSUE TITLE
Access Snipe IT from another computer on the network

### ISSUE THREAD

**Issue by vr1994** [snipe/snipe-it#2984]
I want to access my snipe it application on a different computer on the network but I don't know how.
I can access it on the computer locally by typing http://user-ubuntu in the address bar and i can access my server when i type its ip address but i want to access the application when i type the ip address of the server.

Here's a snapshot of the application

![selection_001](https://cloud.githubusercontent.com/assets/22919161/20689110/b7783aac-b591-11e6-8351-d0f4663b57ee.png)

#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v3.6.0-g91caba0 
- What OS and web server you're running Snipe-IT on - Ubuntu 16.04 LTS and Apache 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh

**Comment by marcusmoore** [comment]
[This] thread might be helpful.

**Comment by vr1994** [comment]
What directory should i set as the DocumentRoot as?. I set it as /var/www/snipeit/public/ but i get the error "The requested URL /login was not found on the server".

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/common-issues#the-requested-url-setup-was-not-found-on-this-serv

**Comment by vr1994** [comment]
Is "/var/www/snipeit/public/" the correct DocumentRoot for the virtual host?

**Comment by vr1994** [comment]
Thanks i fixed it.

**Comment by vr1994** [comment]
Is there another way to access the application without having to change the hosts file.

**Comment by snipe** [comment]
Only if you have an IP address that's reachable on the network. You'd have to access it via the IP address there though. (That's not a limitation of Snipe-IT, that's just how DNS works.) If you want to use a named URL (versus IP), the network needs to know that *that* name maps to that IP address.

**Comment by Kays2023** [comment]
Hi,  I have been following the conversation tightly. I have a similar challenge I have manage to install my Snipe IT on WAMP SERVER and the Challenge I Have is accessing on a Local Area Network. when I access the server remotely I can access it using a Local IP Address but on another client on the same network its not reachable. Please Help

**Comment by marcusmoore** [comment]
Hi @Kays2023. Are you attempting to connect via IP address or url?

**Comment by Kays2023** [comment]
@marcusmoore, I want to connect via IP Address

**Comment by marcusmoore** [comment]
@Kays2023 since this is outside of the scope of the application it's hard to help with the network issues. Since you're running WAMP I would search for more details on allowing an application running in WAMP to be accessible on an internal network.
