### ISSUE TITLE
Unable to create new asset models under local network.

### ISSUE THREAD

**Issue by tx7** [snipe/snipe-it#2985]
#### Expected Behavior (or desired behavior if a feature request)

I tried to create a new asset models  by the following steps:
1. Assets>>List All>>Create New
2. Put in asset tag, click "new" for asset models.
3. Fill out appropriate details.
4. Click "Save"
5. Asset should be save.

-----

#### Actual Behavior

I tried to create a new asset models  by the following steps:
1. Assets>>List All>>Create New
2. Put in asset tag, click "new" from the Asset models drop-down menu.
3. Fill out appropriate details.
4. Click "Save"
5. Nothing happen.

-----

The work around is to create new models under Admin settings.
In addition, after I did the work-around solution, I selected "Ready to Deploy" status, and waiting for the user field to populate, but nothing happened, it just spinning circle next to the R2D status.

It worked if I logged under the URL.

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running:  v3.6.0-g91caba0 
   php:  5.6.27     
   mysql: 5.5.53-0+deb8u1

- What OS and web server you're running Snipe-IT on: Debian Jessie
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): not occured
- Indicate whether or not you've manually edited any data directly in the database: No

**Comment by tx7** [comment]
``#0 [internal function]: Illuminate\Database\Query\Builder->__call('errors', Array)
#1 [internal function]: Illuminate\Database\Query\Builder->errors()
#2 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1426): call_user_func_array(Array, Array)
#3 [internal function]: Illuminate\Database\Eloquent\Builder->__call('errors', Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->errors()
#5 /opt/snipe-it/bootstrap/cache/compiled.php(11663): call_user_func_array(Array, Array)
#6 /opt/snipe-it/app/Http/Controllers/LocationsController.php(144): Illuminate\Database\Eloquent\Model->__call('errors', Array)
#7 /opt/snipe-it/app/Http/Controllers/LocationsController.php(144): App\Models\Location->errors()
#8 [internal function]: App\Http\Controllers\LocationsController->store()
#9 /opt/snipe-it/bootstrap/cache/compiled.php(9424): call_user_func_array(Array, Array)
#10 /opt/snipe-it/bootstrap/cache/compiled.php(9486): Illuminate\Routing\Controller->callAction('store', Array)
#11 /opt/snipe-it/bootstrap/cache/compiled.php(9466): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\LocationsController), Object(Illuminate$
#12 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /opt/snipe-it/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 /opt/snipe-it/bootstrap/cache/compiled.php(9467): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /opt/snipe-it/bootstrap/cache/compiled.php(9454): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\LocationsController), Object$
#18 /opt/snipe-it/bootstrap/cache/compiled.php(8524): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Reques$
#19 /opt/snipe-it/bootstrap/cache/compiled.php(8511): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#20 /opt/snipe-it/bootstrap/cache/compiled.php(8225): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 /opt/snipe-it/app/Http/Middleware/Authenticate.php(45): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /opt/snipe-it/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /opt/snipe-it/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /opt/snipe-it/bootstrap/cache/compiled.php(8226): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 /opt/snipe-it/bootstrap/cache/compiled.php(8217): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#32 /opt/snipe-it/bootstrap/cache/compiled.php(8207): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#33 /opt/snipe-it/bootstrap/cache/compiled.php(2419): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#35 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 /opt/snipe-it/vendor/fideloper/proxy/src/TrustProxies.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /opt/snipe-it/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#39 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 /opt/snipe-it/app/Http/Middleware/CheckForSetup.php(22): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /opt/snipe-it/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#44 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#46 /opt/snipe-it/app/Http/Middleware/NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 [internal function]: App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /opt/snipe-it/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#49 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#51 /opt/snipe-it/app/Http/Middleware/XssProtectHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /opt/snipe-it/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#54 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 /opt/snipe-it/app/Http/Middleware/FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 [internal function]: App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /opt/snipe-it/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#59 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#61 /opt/snipe-it/bootstrap/cache/compiled.php(13474): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /opt/snipe-it/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#64 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#66 /opt/snipe-it/bootstrap/cache/compiled.php(11964): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#67 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /opt/snipe-it/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#69 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#71 /opt/snipe-it/vendor/misterphilip/maintenance-mode/src/MisterPhilip/MaintenanceMode/Http/Middleware/CheckForMaintenanceMode.php(145): Illuminate\Routing\Pipeline->$
#72 [internal function]: MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 /opt/snipe-it/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#74 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#76 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#77 /opt/snipe-it/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#78 /opt/snipe-it/bootstrap/cache/compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#79 /opt/snipe-it/bootstrap/cache/compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#80 /opt/snipe-it/public/index.php(60): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#81 {main}
[2016-11-26 21:49:48] production.ERROR: exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::errors()' in /opt/$
Stack trace:
#0 [internal function]: Illuminate\Database\Query\Builder->__call('errors', Array)
#1 [internal function]: Illuminate\Database\Query\Builder->errors()
#2 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1426): call_user_func_array(Array, Array)
#3 [internal function]: Illuminate\Database\Eloquent\Builder->__call('errors', Array)
#4 [internal function]: Illuminate\Database\Eloquent\Builder->errors()
#5 /opt/snipe-it/bootstrap/cache/compiled.php(11663): call_user_func_array(Array, Array)
#6 /opt/snipe-it/app/Http/Controllers/LocationsController.php(144): Illuminate\Database\Eloquent\Model->__call('errors', Array)
#7 /opt/snipe-it/app/Http/Controllers/LocationsController.php(144): App\Models\Location->errors()
#8 [internal function]: App\Http\Controllers\LocationsController->store()
#9 /opt/snipe-it/bootstrap/cache/compiled.php(9424): call_user_func_array(Array, Array)
#10 /opt/snipe-it/bootstrap/cache/compiled.php(9486): Illuminate\Routing\Controller->callAction('store', Array)
#11 /opt/snipe-it/bootstrap/cache/compiled.php(9466): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\LocationsController), Object(Illuminate$
#12 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /opt/snipe-it/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 /opt/snipe-it/bootstrap/cache/compiled.php(9467): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /opt/snipe-it/bootstrap/cache/compiled.php(9454): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\LocationsController), Object$
#18 /opt/snipe-it/bootstrap/cache/compiled.php(8524): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Reques$
#19 /opt/snipe-it/bootstrap/cache/compiled.php(8511): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#20 /opt/snipe-it/bootstrap/cache/compiled.php(8225): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 /opt/snipe-it/app/Http/Middleware/Authenticate.php(45): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /opt/snipe-it/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /opt/snipe-it/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /opt/snipe-it/bootstrap/cache/compiled.php(8226): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 /opt/snipe-it/bootstrap/cache/compiled.php(8217): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#32 /opt/snipe-it/bootstrap/cache/compiled.php(8207): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#33 /opt/snipe-it/bootstrap/cache/compiled.php(2419): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#35 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 /opt/snipe-it/vendor/fideloper/proxy/src/TrustProxies.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /opt/snipe-it/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#39 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 /opt/snipe-it/app/Http/Middleware/CheckForSetup.php(22): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /opt/snipe-it/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#44 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#46 /opt/snipe-it/app/Http/Middleware/NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 [internal function]: App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /opt/snipe-it/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#49 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#51 /opt/snipe-it/app/Http/Middleware/XssProtectHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /opt/snipe-it/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#54 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 /opt/snipe-it/app/Http/Middleware/FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 [internal function]: App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /opt/snipe-it/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#59 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#61 /opt/snipe-it/bootstrap/cache/compiled.php(13474): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /opt/snipe-it/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#64 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#66 /opt/snipe-it/bootstrap/cache/compiled.php(11964): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#67 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /opt/snipe-it/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#69 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#71 /opt/snipe-it/vendor/misterphilip/maintenance-mode/src/MisterPhilip/MaintenanceMode/Http/Middleware/CheckForMaintenanceMode.php(145): Illuminate\Routing\Pipeline->$
#72 [internal function]: MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 /opt/snipe-it/bootstrap/cache/compiled.php(9963): call_user_func_array(Array, Array)
#74 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#76 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#77 /opt/snipe-it/bootstrap/cache/compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#78 /opt/snipe-it/bootstrap/cache/compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#79 /opt/snipe-it/bootstrap/cache/compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#80 /opt/snipe-it/public/index.php(60): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#81 {main}
[2016-11-26 22:13:45] production.DEBUG: Authenticating user against database.
[2016-11-26 22:14:25] production.DEBUG: Authenticating user against database.
[2016-11-26 22:15:21] production.DEBUG: Authenticating user against database.
[2016-11-27 11:06:52] production.DEBUG: Authenticating user against database.
[2016-11-27 11:06:52] production.DEBUG: Local authentication failed.
[2016-11-27 11:07:11] production.DEBUG: Authenticating user against database.
[2016-11-27 11:07:11] production.DEBUG: Local authentication failed.
[2016-11-27 11:07:29] production.DEBUG: Authenticating user against database.
[2016-11-27 11:07:29] production.DEBUG: Local authentication failed.
[2016-11-27 11:08:42] production.DEBUG: Authenticating user against database.
[2016-11-27 11:08:42] production.DEBUG: Local authentication failed.
[2016-11-27 11:09:33] production.DEBUG: Local authentication failed.
[2016-11-27 12:58:42] production.DEBUG: Authenticating user against database.
[2016-11-27 12:58:42] production.DEBUG: Local authentication failed.
[2016-11-27 14:36:21] production.DEBUG: Authenticating user against database.
[2016-11-27 14:36:21] production.DEBUG: Local authentication failed.
[2016-11-27 17:12:44] production.DEBUG: Authenticating user against database.
[2016-11-27 17:14:21] production.DEBUG: Authenticating user against database.
[2016-11-27 17:19:25] production.DEBUG: Authenticating user against database.
[2016-11-27 19:37:04] production.DEBUG: Authenticating user against database.
[2016-11-27 19:47:40] production.DEBUG: Authenticating user against database.
[2016-11-27 20:12:16] production.DEBUG: Authenticating user against database.
[2016-11-27 20:54:01] production.DEBUG: Authenticating user against database.
[2016-11-27 21:10:22] production.DEBUG: Authenticating user against database.
[2016-11-27 21:12:38] production.DEBUG: Authenticating user against database.
[2016-11-28 16:15:44] production.DEBUG: Authenticating user against database.
[2016-11-28 16:15:44] production.DEBUG: Local authentication failed.
[2016-11-28 16:16:13] production.DEBUG: Authenticating user against database.
[2016-11-28 16:16:13] production.DEBUG: Local authentication failed.
[2016-11-28 18:10:11] production.DEBUG: Authenticating user against database.

**Comment by snipe** [comment]
Does that stack trace happen every time you try to save? Also please check for browser errors, and make sure the APP_URL in your .env is EXACTLY the same as the url you're accessing the site from.

**Comment by tx7** [comment]
I'm not sure about the stack. Should I clear the log, and retry that?
The APP_URL is in the https://my.domain.com:5443
and is working fine if I logged under there.

However, if I logged under my local IP>>http://192.168.1.17:5443
then the error persist.

**Comment by snipe** [comment]
You have to access it via the URL in APP_URL. Browsers prevent loading JS from other domains, which means any JS functions won't work if you use a different domain name.

**Comment by tx7** [comment]
Is JS means Java Script?
What if I change to APP_URL to null?
Will that work for local and external url?

**Comment by snipe** [comment]
No, it won't work.

**Comment by tx7** [comment]
I see.
Is the port # relevant to put in the APP_URL?

**Comment by snipe** [comment]
If it's necessary in the URL. then yes

**Comment by tx7** [comment]
by the way, how do I clear out the log ?
Is the bulk asset deletion available?
I can't find it anywhere.

**Comment by snipe** [comment]
> by the way, how do I clear out the log ?

Open it and delete the contents, or remove the log file. It should create a new one.

> Is the bulk asset deletion available?

Checkboxes in asset listing, then select "Delete" from the dropdown menu.

<img width="938" alt="screen shot 2016-11-28 at 5 58 32 pm" src="https://cloud.githubusercontent.com/assets/197404/20693590/540369bc-b594-11e6-873f-5db7f07f1299.png">

**Comment by tx7** [comment]
Sorry, I meant asset models.

Thanks.

**Comment by snipe** [comment]
No bulk delete for asset models

**Comment by tx7** [comment]
Hi,

I have two issues:

1.  After the upgrade, the cipher keys isn't working due to the invalid cipher keys length from  `config/app.php`. 'cipher' => 'rijndael-256' 
I had to changed it to 'cipher' => 'AES-128-CBC', to able to access Snipe-It.


2.  I just updated to v3.6.1, and problem occurred again.
I can't create Asset Model from the Asset menu, only from the Admin panel.
I even generated new key too.

**Comment by dmeltzer** [comment]
Did you run `php artisan migrate` when upgrading?

**Comment by tx7** [comment]
Yes, I ran all the commands instructed:

`php artisan config:clear
php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan migrate

`

**Comment by dmeltzer** [comment]
Oops, that's actually a bug.  Will be fixed in develop shortly.

**Comment by tx7** [comment]
Thanks for the prompt responses.
You're guys are awesome.

Regarding issue #1, Do I need to change the key type after each upgrade?

**Comment by snipe** [comment]
Any time you edit a file like that, you'lol have to do it every time. It's why we don't recommend editing those files (including changing the cipher type)

**Comment by tx7** [comment]
If I don't change the cipher type, then Snipe-IT will not work.
What's your suggestion?

**Comment by snipe** [comment]
Can you define 'will not work'?

**Comment by snipe** [comment]
It defaults to using an mcrypt cipher. Install mcrypt and the existing cipher should work. But you can't change it from one to the other if you have any encrypted values in the db (encrypted custom fields, LDAP password, etc)

**Comment by tx7** [comment]
Well, Snipe page gave me an error when I did the installation and after the upgrade.
So I did some research, and some users said to change the cipher type, and it worked.
Do I need to install mcrypt to avoid this error in the future?
