### ISSUE TITLE
snipte support api？

### ISSUE THREAD

**Issue by zdong08** [snipe/snipe-it#2986]
Hi，Snipe itself supports API？If you do not support, please tell me where I can modify, I need this feature thank you

**Comment by snipe** [comment]
@zdong08 Snipe-IT does not currenly have an API, but that's in the works. 

Closing as duplicate of #176

**Comment by zdong08** [comment]
Hi, snipe I want to develop their own, because I desperately need this feature, you can tell me to see the code of the document and how I want to write I can see
