### ISSUE TITLE
Error Active Directory

### ISSUE THREAD

**Issue by fromitti** [snipe/snipe-it#2988]
I get this error when trying to link with my Active Directory

 Error: Could not bind to LDAP: Invalid credentials

Any contribution ..?
Thank you!
Flavio

**Comment by snipe** [comment]
It's telling you what's wrong - the credentials are invalid.

**Comment by fromitti** [comment]
If it is logical, the query is because the credentials are fine, but gives that error.

**Comment by therealjoshuad** [comment]
Try using the UPN for the link ldap user. 

user@domain.local

**Comment by fromitti** [comment]
Perfect, thank you very much

Link LDAP user=administrator@domain.local

**Comment by therealjoshuad** [comment]
Also, read this thread, you may need to adjust the userfield #2697

**Comment by fromitti** [comment]
Thank you so much!!
