### ISSUE TITLE
Navigation Bar is not showing selected assets

### ISSUE THREAD

**Issue by RTITUser** [snipe/snipe-it#2989]
#### Expected Behavior (or desired behavior if a feature request)

When I select Un-Deployable from the Nav Bar I expect Snipe-IT to return all systems with a label status of un-deployable

-----
My issue is that I have assigned an asset the status of "Un-deployable" yet when I do a search from the Nav bar for Un-Deployable assets I get the “no matching records found” message. Now if I do a search for "Ready-to-Deploy" assets there I find the Un-deployable asset in the same list. Or with my created label of "Awaiting Re-Imaging" no files come up when I search for these, which has been added to the Nav Bar, but if I search on the asset tags of the Awaiting Re0Imaging assets the systems show. Trying to understand what may be causing this issue, or what it is that I am doing wrong.
![statuslabelissue1](https://cloud.githubusercontent.com/assets/22746746/20719853/6fb194e6-b61a-11e6-990e-22fd8578fe55.png)
![statuslabelissue2](https://cloud.githubusercontent.com/assets/22746746/20719852/6fb177cc-b61a-11e6-8b0f-49d813fc1f39.png)
![statuslabelissue3](https://cloud.githubusercontent.com/assets/22746746/20719851/6faf4e7a-b61a-11e6-9a91-20fb47019519.png)
![statuslabelissue4](https://cloud.githubusercontent.com/assets/22746746/20719854/6fb20e26-b61a-11e6-9af4-e0066566cc70.png)

**Comment by snipe** [comment]
Can I see a screenshot if your status labels page?

**Comment by RTITUser** [comment]
Yes....

![statuslabels](https://cloud.githubusercontent.com/assets/22746746/20720062/1fcb1b18-b61b-11e6-9135-084692e9068a.PNG)

**Comment by snipe** [comment]
If you want Awaiting Re-Imaging to show up in the Undeployable nav, you should change the status label type to Undeployable. Right now it's Pending, so it will show up in the Pending nav.

**Comment by RTITUser** [comment]
Thanks!!

**Comment by snipe** [comment]
![vader-on-dumbo](https://cloud.githubusercontent.com/assets/197404/20720334/960290d4-b613-11e6-9768-861049fc4b7f.gif)
