### ISSUE TITLE
AutoComplete Attribute Not Disabled for Password in Form Based Authentication

### ISSUE THREAD

**Issue by delize** [snipe/snipe-it#2990]
I just wanted to leave this note here for development purposes.

We run Qualsys scanner on our internal network.  When running it against SnipeIT, it spits out the following vulnerability alert.

Vulnerability - level 2	
86729
AutoComplete Attribute Not Disabled for Password in Form Based Authentication	
2 Low Risk (Reader)

Its not a high security vulnerability, but, just wanted to inform you all the same.

**Comment by snipe** [comment]
That's not really a vulnerability, IMHO. We could have a long conversation about security vs usability, but I doubt it would change anything. We'll try to get it resolved in 3.6.2.

**Comment by delize** [comment]
Yeah, I am okay with that to be honest. Just doing what I need to do on my side to close the report for our team.
