### ISSUE TITLE
i facing issue in migrating database to the new version 3.0.6 

### ISSUE THREAD

**Issue by umerafridi** [snipe/snipe-it#2991]
#### Expected Behavior (or desired behavior if a feature request)
Whoops, looks like something went wrong.

in pre flight test when i click on create database tables 
(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Please turn on debugging and/or provide your error logs, per the initial issue template. We need more details in order to help you.

**Comment by umerafridi** [comment]
Thanks for your reply i solve this problem and successfully  upgrade to 3.6.0 version and successful migrate databases also.But now i login to the software i don't have admin writes .before this version i have admin writes .now how i create admin users with full writes please help its very urgent

**Comment by umerafridi** [comment]
Please reply its very urgent

**Comment by snipe** [comment]
@umerafridi it is nearly 3am here. You need to be patient. We reply as quickly as we can for all users, always.

If you don't have super admin rights, use the command line tool to create a new admin and grant yourself super admin rights. It's in the docs.

**Comment by umerafridi** [comment]
Done .Thanks a lot and sorry don't know about timing

**Comment by umerafridi** [comment]
Hi,
    i want to show Quantity list in crating new asset .i add from custom filed but it not shown in creating list form.
