### ISSUE TITLE
Error when clone assets model

### ISSUE THREAD

**Issue by Ny0tNy0t** [snipe/snipe-it#2992]
#### Expected Behavior (or desired behavior if a feature request)

is showing error when do clone for assets model,

![image](https://cloud.githubusercontent.com/assets/23697109/20745447/08902eb2-b714-11e6-8caf-72d163554f12.png)

![image](https://cloud.githubusercontent.com/assets/23697109/20745459/10e8e9b4-b714-11e6-8bf7-b17bf1aab43d.png)

![image](https://cloud.githubusercontent.com/assets/23697109/20745467/174d90ac-b714-11e6-96a4-f78e73ade3c2.png)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running --> v.3.60
- What OS and web server you're running Snipe-IT on --> 7.0.8-0ubuntu0.16.04.3
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) --> install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error --> Yes
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
I believe this is fixed on the develop and master branches already

**Comment by Ny0tNy0t** [comment]
Hi snipe,


can you help me how to fix it ?
