### ISSUE TITLE
Activities Logs for Admin Control Panel [Feature Request]

### ISSUE THREAD

**Issue by tx7** [snipe/snipe-it#2994]
Hi,

I notice that there is no logs such as user authentication, failed authentication, or limit the number of failed login attempts under the Admin settings.
It would be nice to have this feature for a Super Admin.
It not friendly to log via SSH to view the logs from "laravel.log".
I hope this feature implement in the future release.

Thanks.

**Comment by snipe** [comment]
Limiting the number of failed login attempts was released in 3.6.1

**Comment by tx7** [comment]
Can we get an email notification whenever there is a number of failed login attempts?

**Comment by snipe** [comment]
We can consider adding it, but it would have to be a preference, as not everyone would want those alerts.
