### ISSUE TITLE
Warning Bar will not go away even though APP_DEBUG=false

### ISSUE THREAD

**Issue by delinski111** [snipe/snipe-it#2996]
#### Expected Behavior (or desired behavior if a feature request)

Turned off Debug Mode Expected the Warning bar to disappear.

-----

#### Actual Behavior

Bar did not disappear

![snipeit_warningbar](https://cloud.githubusercontent.com/assets/22087997/20754648/f046f58c-b6d9-11e6-800e-eb9893ef4b2e.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [ x ] I have enabled debug mode (and disabled)
- [ x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.6.0-g91caba0

- What OS and web server you're running Snipe-IT on
Ubuntu 14.04

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual/Git

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the 
error
All Pages

- If a stacktrace is provided in the error, include that too.
N/A

- Any errors that appear in your browser's error console.
N/A

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
N/A (cannot mess with these settings on the Demo)

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

- Include what you've done so far in the installation, and if you got any error messages along the way.
N/A

- Indicate whether or not you've manually edited any data directly in the database
N/A

**Comment by delinski111** [comment]
Further Info,
I did; git reset --hard origin/master, so this issue is part of the build, not my local server?

**Comment by snipe** [comment]
Did you clear your configured cache?

**Comment by snipe** [comment]
`php artisan config:clear`

**Comment by delinski111** [comment]
config:clear did not work alone.
I re-ran through all of the upgrade commands (composer install,migrate...) and that did the trick.

Thank You for the help
