### ISSUE TITLE
Asset cost with a comma doesn't parse correctly

### ISSUE THREAD

**Issue by pnelsonsr** [snipe/snipe-it#2998]
#### Expected Behavior (or desired behavior if a feature request)

Parsing of asset purchase cost over 1000 gets done correctly.

-----

#### Actual Behavior

Editing an asset with a purchase cost over $1000, when you submit the purchase cost will revert to $1.00. It looks like it doesn't parse the comma that gets automatically added after the thousands place. If I remove the comma before clicking submit it works fine. Does cause data loss if you forget to remove the comma.

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running v3.0.0-dev-3
- What OS and web server you're running Snipe-IT on Fedora 24 Server
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error No
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error Asset add/edit
- If a stacktrace is provided in the error, include that too. NO
- Any errors that appear in your browser's error console. NO
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). couldn't get to page
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. NONE
- Include what you've done so far in the installation, and if you got any error messages along the way. Worked around by remove comma before save
- Indicate whether or not you've manually edited any data directly in the database NO

**Comment by snipe** [comment]
I believe this has been fixed in later versions.
