### ISSUE TITLE
Unable to view new users

### ISSUE THREAD

**Issue by vr1994** [snipe/snipe-it#3000]
When I create a new user it doesn't show up when I try to view all users but I can login with the user I just created. When I go to to the users page, I would get the message "No matching records found".\

Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v3.6.0-g91caba0
- What OS and web server you're running Snipe-IT on - Ubuntu 16.04 LTS and Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)  install.sh

**Comment by MichaelAlt** [comment]
Got the same problem, try hit the "refresh" button. After that it shows all users.
![image](https://cloud.githubusercontent.com/assets/5499575/20759291/cf1b39de-b71c-11e6-93dd-8b218a7a7225.png)

**Comment by vr1994** [comment]
I've done this several times already and it didn't work. I logged out and back in and still didn't see anything.

**Comment by vr1994** [comment]
I've checked the database and the user is in the table. So it knows the user exists but it just doesn't display in the application.

**Comment by vr1994** [comment]
I'm thinking maybe a value in some field must be changed so it can be visible in application.

**Comment by vr1994** [comment]
The same thing happens when I create an asset or anything else. It would be in the database but it won't show up in application.

**Comment by snipe** [comment]
Check the /api/users/list URL and tell me whether you get JSON, or an error. Also, per the initial issue template, please check your browser console and tell us if there are any javascript errors. Also try clearing your cookies and cache and reloading the page.

**Comment by vr1994** [comment]
It's fixed now. I had to change some things with the database.

**Comment by snipe** [comment]
Could you be more specific, in case anyone else has a similar issue?

**Comment by vr1994** [comment]
I had performed an upgrade on the application and it seems some of the tables weren't properly updated so I had to update some field names and create the action_logs table before anything could show up in the application.

**Comment by snipe** [comment]
Did you run migrations? You should never have to alter data or tables directly, and in fact we strongly recommend against it. Migrations do all that for you.
