### ISSUE TITLE
Increase size of attatchments

### ISSUE THREAD

**Issue by NWADMIN** [snipe/snipe-it#3001]
When i want to upload a 3,5 mb pdf file, the upload fails with  Error: You did not select any files for upload, or the file you are trying to upload is too large . 

The size of attatchments should be greater than 10 mb.

**Comment by mtucker6784** [comment]
I believe this is a PHP setting that you'll have to modify in your PHP settings. Look for post_max_size and upload_max_filesize and adjust the values accordingly (of which IIRC you'll have to restart your web daemon.)
