### ISSUE TITLE
 Error: Could not bind to LDAP: Can't contact LDAP server

### ISSUE THREAD

**Issue by alecwhitworth** [snipe/snipe-it#3002]
#### Expected Behavior (or desired behavior if a feature request)

I have had the Ldap connector working efficiently with our domain controllers in the past importing near 2-3000 records.

-----

#### Actual Behavior

Recently I have been getting the error message as in the title every time i try to do an LDAP user import.
-----

#### Please confirm you have done the following before posting your bug report:

I have tested all credentials allocated for our Ldap servers and checked all connections on our DC and they are all working fine.

-----
#### Please provide answers to these questions before posting your bug report:
System Information

Snipe-IT version	v3.4.0-9-g67315d8
PHP Version	5.6.25
Laravel Version	5.2.45
Centos7.2
Installed via the SH script
Not sure of the debug method.
No Direct Database editing occured.

**Comment by therealjoshuad** [comment]
Was LDAP working before, and it's not anymore?

Can you post the settings you have in the LDAP section? (Obsficated of course)

**Comment by alecwhitworth** [comment]
I think the issue may be the DNS, it cannot find hostnames yet when i use the IP address on the LDAP settings for one of the domain controllers the syncing works absolutely fine.

**Comment by therealjoshuad** [comment]
Awesome, I realized after posting that you said it recently stopped working. I've seen a lot of issues with LDAP settings being off.

**Comment by snipe** [comment]
Any updates?

**Comment by itborn** [comment]
I am getting a "Could not bind to LDAP: Can't contact LDAP server" when testing the ldap connectivity i am running VMWARE 12 Player with centos 7 installed on it with php 5.6 & phpldap Snipe-it Version v3.6.2 build 18 
i have tested connecting via the centos 7 box by using below: 
ldapsearch -h server-ip -b "dc=Domain,dc=local" -D DomainUser@Domain.local -W -x sAMAccountName=DomainUser and i get a return message of:

# extended LDIF
#
# LDAPv3
# base <dc=Domain,dc=local> with scope subtree
# filter: sAMAccountName=DomainUser
# requesting: ALL
#

# DomainUser, Service Accounts, IT Admin, Users, Location, UK, Domain.local
dn: CN=DomainUser,OU=Service Accounts,OU=IT Admin,OU=Users,OU=Location,
 OU=UK,DC=Domain,DC=local
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: user
cn: DomainUser
sn: User
givenName: svc
distinguishedName: CN=DomainUser,OU=Service Accounts,OU=IT Admin,OU=Users
 ,OU=Location,OU=UK,DC=Domain,DC=local
instanceType: 4
whenCreated: 20170104110514.0Z
whenChanged: 20170105143819.0Z
displayName: DomainUser
uSNCreated: 18372271
uSNChanged: 18455266
name: DomainUser
objectGUID:: bu0UC/VflkiLqUkUGTWLGg==
userAccountControl: 66048
badPwdCount: 0
codePage: 0
countryCode: 0
badPasswordTime: 0
lastLogoff: 0
lastLogon: 0
pwdLastSet: 131280015148174589
primaryGroupID: 513
objectSid:: AQUAAAAAAAUVAAAAtVb9Mj6fqO6eBPLkzCUAAA==
accountExpires: 9223372036854775807
logonCount: 0
sAMAccountName: DomainUser
sAMAccountType: 805306368
userPrincipalName: DomainUser@Domain.local
objectCategory: CN=Person,CN=Schema,CN=Configuration,DC=Domain,DC=local
dSCorePropagationData: 16010101000000.0Z
lastLogonTimestamp: 131281006995706405

# search reference
ref: ldap://DomainDnsZones.Domain.local/DC=DomainDnsZones,DC=Domain,DC
 =local

# search reference
ref: ldap://ForestDnsZones.Domain.local/DC=ForestDnsZones,DC=Domain,DC
 =local

# search reference
ref: ldap://Domain.local/CN=Configuration,DC=Domain,DC=local

# search result
search: 2
result: 0 Success

# numResponses: 5
# numEntries: 1
# numReferences: 3
 
But when i use there snipe-it application to test i get the above error "Could not bind to LDAP: Can't contact LDAP server" i have tried to cross reference the details on the installation guided and the information that i have entered into the centos command-line everything seems to be correct please advise in simpleton term what i need to do to get this working?

**Comment by itborn** [comment]
the setting that are used in snipe-it settings are:
![ldapsettings](https://cloud.githubusercontent.com/assets/24934982/22353728/cb9187a8-e419-11e6-9a4a-5af469440907.png)

**Comment by itborn** [comment]
When testing the LDAP connection i get the following error:

Could not bind to LDAP: Can't contact LDAP server

**Comment by VonSchnitzel** [comment]
Did you ever find a resolution for this? 

I'm experiencing the same. Ldapsearch query works fine but 'test ldap' fails with 'can't contact ldap server'. No log files that I can find, even in debug mode. Snipe-IT installed on CentOS 7. Any help would be awesome.
