### ISSUE TITLE
LDAP Multiple OU/DN Sync

### ISSUE THREAD

**Issue by TheJirsh** [snipe/snipe-it#3004]
Not an error just setup questions. Using Windows 2008 R2 AD

1) Is the LDAP sync for users to login with domain creds AND/OR to check in/out to named users?
2) I have multiple root OU's with user OU's inside. How do I sync multiple?
3) How do i filter disabled users from being synced?
4) How do i filter vendor OU's that inside the user OU's that I want to sync?

Thanks in advance. Fantastic product.

**Comment by therealjoshuad** [comment]
1. Login, and you can check assets out to them
2. I think your only option would be to set the base bind dn to the highest level that may contain users.
3. Build an LDAP filter, one of the LDAP fields is the filter field, by default it pulls all objects.
4. Build it into your LDAP filter from question 3

Microsoft has some good resources:
http://social.technet.microsoft.com/wiki/contents/articles/5392.active-directory-ldap-syntax-filters.aspx
https://technet.microsoft.com/en-us/library/aa996205(v=exchg.65).aspx
https://confluence.atlassian.com/plugins/servlet/mobile#content/view/165333

**Comment by snipe** [comment]
We'll be adding the ability to associate an OU to locations, which may help our second issue.

**Comment by michaelc64** [comment]
We would also like the ability to sync/authenticate multiple root ou's - the reason is we have multiple AD domains in the same forest.  For example we have separate domains for our Australian and New Zealand companies:

ou=employees,dc=company,dc=com,dc=au
ou=employees,dc=company,dc=co,dc=nz

Users on both domains can be queried by using the global catalog port on the domain controllers, however cannot find a way to specify multiple base dn's.

Thanks!

**Comment by richardhofman6** [comment]
I have implemented location-specific OU syncing in my local copy of Snipe IT. Happy to submit a PR if input on this functionality is wanted @snipe .

**Comment by snipe** [comment]
Sure, that would be great - it was on the roadmap, so would love to check out a PR. One thing tho, the develop branch is pretty divergent from master at this point, as we prep for v4. Not sure how hard it will be to port forward from master.

**Comment by richardhofman6** [comment]
Sounds good - I have moved the changes I made on top of v3.6.2 to the latest versions in the develop branch (as of a couple of hours ago). None of the functions I modified have been touched, so porting it was a quick job.

I can confirm that my implementation works on 3.6.2, as I pushed it to my employer's asset management system yesterday and users are now syncing into groups based on OU, as expected.

**Comment by sirrus** [comment]
Hi - this function would help a lot - but I would suggest to enable sync multiple LDAP structures too.
I have a system with 2 different AD Structures and 3 Domains.

**Comment by agentbb** [comment]
+1

**Comment by awarre** [comment]
Sorry to poke a closed topic, but I can't find any clear documentation or issues on this. Is syncing multiple OUs possible with the current version of Snipe?

**Comment by uberbrady** [comment]
You can do various OU’s on a per-location basis by setting OU’s per Location within Snipe-IT. You can also run multiple CLI syncs using the `php artisan snipeit:ldap-sync` with the `—base_dn` option (in case GH eats that, it’s “dash dash base underscore dn”). But if you need two separate LDAP servers with separate IP’s or authentication credentials, then, no, we don’t support that.
