### ISSUE TITLE
Custom Fields - Test and Tag Records

### ISSUE THREAD

**Issue by Bigben83** [snipe/snipe-it#3005]
Great Software well done,

I am using it to asset track, tools in the construction industry, lots of the tools need to be electrically tested and tagged.  I have added two custom fields as below

**Test and Tagged Date:**  i.e. 2016/11/22
**Period Required:**   ie 12months

I would like another Field as below

**Retest Due:**  = (Test and Tagged Date) + (period required).

how can I do this? it would be good to have a report that you could get to see what tools are due for re-test.  maybe this needs to be under maintenance tab, it also could then have another field

**Result:** Passed / Failed / Damaged beyond repair / Sent for repair 

I'm sure there are many electrical items that would benefit from this.  As in Australia, anything that plugs into a mains power socket needs to be tagged.

**Comment by qzsoft** [comment]
It would be great to expand the concept of asset maintenance to address this common issue-   Assets have components that need maintenance at regular intervals.   Such as

A UPS needs a new battery every X years.
A first aid kid needs medicines replaced every X months
The emergency food in the emergency kit needs refreshing every X months, etc.

A report showing which components or assets are expired or out of compliance, etc, would be awesome.   Alerts/e-mails could be automatically generated when something exceeds its maintenance period (which could then be sent to a ticketing system for someone to take action).

**Comment by snipe** [comment]
This is handled via the audit feature in v4, I believe
