### ISSUE TITLE
Hi, i want to show Quantity list in crating new asset  .i add from custom filed but it not shown in creating list form.

### ISSUE THREAD

**Issue by umerafridi** [snipe/snipe-it#3006]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Assets are not really meant to support quantities, as they are all unique, with their own serial numbers. Accessories is better suited for that.

To make custom fields for assets work, you have to associate the custom field with a fieldset and then associate the fieldset with an asset model. https://snipe-it-manual.readme.io/docs/custom-fields

**Comment by khaledabdulrahim** [comment]
is it possible to add the quantity and minimum quantity to the assets or in anther way to know how many (pc, screen) still i have?

**Comment by pcsmarts502** [comment]
Google snipe-it  documentation

**Comment by teeble2001** [comment]
Found what I was looking for.  Thank you!
