### ISSUE TITLE
Running on a port other than 80

### ISSUE THREAD

**Issue by half-biscuit** [snipe/snipe-it#3009]
#### Expected Behavior (or desired behavior if a feature request)

Logo (title top left in Header Navbar) should reflect the port number.

-----

#### Actual Behavior

Logo does not have port number whereas other links do. In this case port 8080 as I'm using port 80 for another project.

`       

        
        <nav class="navbar navbar-static-top" role="navigation">
          
          <a href="#" style="color: white" class="sidebar-toggle btn btn-white" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <ul class="nav navbar-nav navbar-left">
              <li class="left-navblock">
                                       <a class="logo no-hover" href="http://pdqassets">
                          PDQ Asset Management
                      </a>
                                </li>
            </ul> 

          
            <div class="navbar-custom-menu">
              <ul class="nav navbar-nav">
                                    <li >
                      <a href="http://pdqassets:8080/hardware">
                          <i class="fa fa-barcode"></i>
                      </a>
                  </li>
                                                      <li >
                      <a href="http://pdqassets:8080/admin/licenses">
                          <i class="fa fa-floppy-o"></i>
                      </a>
                  </li>`

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - 3.6.0
- What OS and web server you're running Snipe-IT on - Windows / WAMP
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual
- Have not altered any code - only Apache files http.conf and http-vhosts.conf

**Comment by dmeltzer** [comment]
What is your APP_URL set to in the .env file?

**Comment by snipe** [comment]
Just make sure you include the port number in your APP_URL.

**Comment by toti-feroy** [comment]
Hi, which file do I have to include the port numbers to link other pages?
