### ISSUE TITLE
Upgrades do not work

### ISSUE THREAD

**Issue by ebonweaver** [snipe/snipe-it#3016]
Attempting upgrade, unfortunately there is no documentation I can find anywhere how to do this properly.
What I did:
Pulled down the 3.6.1 zip file, did a cp -R * (and .* and *.* to ensure all files copied) to the live directory.
Tried to run  php artisan config:clear and got an error that included permission denied.
Tried to run sudo  php artisan config:clear and got this error:
PHP Fatal error:  Class 'PragmaRX\Google2FA\Vendor\Laravel\ServiceProvider' not found in /var/www/snipeit/bootstrap/cache/compiled.php on line 7658
  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'PragmaRX\Google2FA\Vendor\Laravel\ServiceProvider' not found

Old version was either 3.4 I think (maybe 3.3) which was installed with the install.sh method.  This is on Ubuntu 14 server.
At this point the site simply says woops, looks like something went wrong.  Yes it most certainly did.
Because of this error I have not attempted to run the next 3 php commands so as to not break this further.

Please advise how to fix this.  It appears there is a fatal bug in the software given the above error.

**Comment by ebonweaver** [comment]
In an attempt to fix this, I moved the updated snipe directory and made a fresh one from the 3.6.1 download.  I then copied over my .env file and tried the php artisan config:clear again and this time got this error:
PHP Warning:  require(/var/www/snipeit/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/snipeit/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/snipeit/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/snipeit/bootstrap/autoload.php on line 17

Really looks like upgrading simply does not work and this new version has problems.

**Comment by ebonweaver** [comment]
and it was 3.3, finally found my other issue with that listed v3.3.0-3-g7ef4f23
Unfortunately simply restoring a fresh copy of that download does not work either, now the site is simply blank.
Running the php command now says: Could not open input file: artisan

I'm starting to think installs created with install.sh can not be upgraded/ are entirely different than a download, or again there is missing very important documentation on how to upgrade.

**Comment by snipe** [comment]
> PHP Warning: require(/var/www/snipeit/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/snipeit/bootstrap/autoload.php on line 17

That means you have to run composer install

**Comment by ebonweaver** [comment]
Does that mean there is information missing?  Or that the notes at https://github.com/snipe/snipe-it/releases/tag/v3.6.1 are in the wrong order?
Also, composer was already there before I did a full replacement, so is the original error caused by the same problem or something else?

**Comment by snipe** [comment]
Try them in this order:

```
php composer.phar install --no-dev --prefer-source
php artisan config:clear
php composer.phar dump-autoload
php artisan migrate
```

**Comment by macpacadmin** [comment]
I had a problem upgrading and have just been successful see my last post in #3027

potentially you can make use of it

**Comment by ebonweaver** [comment]
This appears to have worked, however I'm concerned that something may now be messed up because the instructions have a very important omission.
When you try to run those php commands they fail due to permission.
The immediate reaction to this of course is to run them with sudo.
When you do that, you get a warning to not run composer with sudo, BUT IT DOES IT ANYWAY.
If you run the commands with sudo -u www-data they seem to work, although errors about being able to cache are given in that case.

So, the release notes saying to run these commands seem to need to clearly state HOW to run the commands to avoid issue.  I understand the user flag will vary by OS distro, but a clear warning is clearly needed.
Now that I already made the mistake, is there any concern for operation, and if so how do I undo what has been done?

The software is running and seems to be working, but given the warning on the composer site I'm concerned.

**Comment by ebonweaver** [comment]
I have suggested edits to https://snipe-it.readme.io/docs/how-to-upgrade such that referencing that article in the release notes may be good for clarity and completion.  Hope that's helpful!

**Comment by macpacadmin** [comment]
By memeory I changed snipe directory owner to my admin account and that allowed me to run without needing to elevate using sudo - Snipe or someone will need to help you with any negative effects from using sudo or to my limited understanding you could make a backup of your current, pull down another copy and run through the install again this time without using sudo
