### ISSUE TITLE
Error 500 (I've read all the 500 related issues and none apply to me)

### ISSUE THREAD

**Issue by AsimPervez93** [snipe/snipe-it#3020]
#### Expected Behavior (or desired behavior if a feature request)

Be taken to the pre-flight check when accessing url

-----

#### Actual Behavior

Error 500

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
latest I assume, I did a git clone this morning

- What OS and web server you're running Snipe-IT on
Red Hat 4.4.7-16

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
git clone

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
n/a

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
subdomain

- If a stacktrace is provided in the error, include that too.
n/a

- Any errors that appear in your browser's error console.
n/a

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
n/a
- Include any additional information you can find in `app/storage/logs` and your webserver's 
/storage/logs/laravel.log is empty

- Include what you've done so far in the installation, and if you got any error messages along the way.
followed instructions in documentation and get error when trying to do the pre-flight check by accessing the URL

- Indicate whether or not you've manually edited any data directly in the database
No

**Comment by snipe** [comment]
Check the permissions on your storage directory, and tell us what the specific 500 error is.

**Comment by AsimPervez93** [comment]
My error was caused because I hadn't installed Composer.

I installed composer in the directory and this resolved the issue.
