### ISSUE TITLE
localhost working from ip and 127.0.0.1 not working

### ISSUE THREAD

**Issue by ammarmalhotra** [snipe/snipe-it#3021]
I have installed snipe-it on Ubuntu 16.04, it is working if i go to http://localhost/ or http://gfdapstrv/ on the same system but not by ip http://192.168.1.194/ or http://127.0.0.1/ or http://127.0.1.1/  ( apache2 default page comes up ). 

i have made change to port.conf file also

Listen 0.0.0.0:80

my hosts file shows

127.0.0.1	localhost
127.0.1.1	GFDAPSTRV

::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
127.0.0.1 GFDAPSTRV gfdapstrv
127.0.0.1 GFDAPSTRV gfdapstrv
127.0.0.1 GFDAPSTRV localhost
127.0.0.1 GFDAPSTRV localhost
127.0.0.1 GFDAPSTRV localhost
127.0.0.1 GFDAPSTRV localhost
127.0.0.1 GFDAPSTRV localhost
127.0.0.1 GFDAPSTRV localhost
127.0.0.1 GFDAPSTRV localhost
127.0.0.1 GFDAPSTRV localhost
127.0.0.1 GFDAPSTRV localhost

**Comment by ammarmalhotra** [comment]
another problem is backup i tried to backup it shows backup file was successfully created but no file is created in /var/www/snipeit/storage/app/backups

**Comment by snipe** [comment]
Your first issue is a web server configuration issue and is outside the scope of Snipe-IT. 

For your second issue, we'll need the app/server logs to know why the backup is failing. Possible reasons are that you don't have mysqldump installed, the path to it is incorrect in your .env, or that the backup directory isn't writeable by the web server.

**Comment by ammarmalhotra** [comment]
Fixed the first issue by adding

VirtualHost 192.168.1.194:80>

now will check the second issue

**Comment by ammarmalhotra** [comment]
[2016-12-08 07:33:08] production.ERROR: backups backups : error: Failed to backup  because: The dump process failed with exitcode 127 : Command not found : sh: 1: /usr/local/bin/mysqldump: not found

**Comment by snipe** [comment]
It can't find mysqldump, so it's either not installed or it's not where the system thinks it is. Update the path in your config when you figure out where it is.
