### ISSUE TITLE
What does different different status_ids mean?

### ISSUE THREAD

**Issue by DhawalS** [snipe/snipe-it#3022]
#### Expected Behavior (or desired behavior if a feature request)

Hi, I have uploaded 700 assets under 1 category. But on checking assets via category, I am seeing only 528 assets on portal. Also, on downloading these 528 assets, I am getting only 450 assets in the csv.

Can you pls help me out with the following:
1. Meaning of different different status_ids like 1, 2,...9, etc
2. Why is this discrepancy in the asset count on portal v/s downloaded csv

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running : **v3.2.0-53-gfff2bce**
- What OS and web server you're running Snipe-IT on: CentOS and nginx
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
> Meaning of different different status_ids like 1, 2,...9, etc

The status_ids describe the status of the asset. They correspond to an id of a status label in the status_labels table.

> Why is this discrepancy in the asset count on portal v/s downloaded csv

No idea. How many do you get when you export them as a custom report?

**Comment by DhawalS** [comment]
Hi @snipe 
Just checked the custom report and found that all the 528 records got downloaded. Also, checked the same via category section but found only 450 records in the downloaded csv.
