### ISSUE TITLE
Error: The asset you have attempted to accept was not checked out to you.

### ISSUE THREAD

**Issue by ovizii** [snipe/snipe-it#3023]
#### Expected Behavior (or desired behavior if a feature request)

Log in as admin, go to accessories, click checkout asset to user, select my user and checkout. 
Receive the email "Confirm accessory delivery." 

Please click on the link at the bottom to confirm that you have received the accessory. 
I have read and agree to the terms of use, and have received this item. (link)

I click the link and then can either decide to accept or deny or the asset is automatically accepted.

-----

#### Actual Behavior

Log in as admin, go to accessories, click checkout asset to user, select my user and checkout. 
Receive the email "Confirm accessory delivery." 

Please click on the link at the bottom to confirm that you have received the accessory. 
I have read and agree to the terms of use, and have received this item. (link)

I click the link and then I see an error message:
 Error: The asset you have attempted to accept was not checked out to you.

If I then go and select my user, the accessory has been checked out by me and I can check it back in without a problem. While testing this I am logged into snipeitapp.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

Version v3.6.2 build 10 (g927a12f)
Ubuntu 15.10 (GNU/Linux 4.2.0-16-generic x86_64)
Docker
Haven't tested the demo yet
This is a brand-new installation. I have done nothing yet except create manufacturers, asset modells, categories and one accessory.

**Comment by aglasson** [comment]
I have had this issue but it was a simple case of the user account (email address) I checkout out to was not the same account I was logged in with.
For instance we have AD accounts "admin*name*" and "*firstinitial**lastname*".
I admin with the admin account, check out the asset to my non-admin user account and click the link hence it uses my admin account as I was already logged in with that.
Same situation maybe?

**Comment by ovizii** [comment]
Thanks for solving the mystery, that is exactly my situation :-)
