### ISSUE TITLE
View Asset | Not showing all filled fields

### ISSUE THREAD

**Issue by delinski111** [snipe/snipe-it#3024]
While Viewing an Asset, the Purchase Order Number is not visable. This IS reproducable in the Demo.

I have verified that the field is populated, and from the Asset List screen, the value is displayed OK, but not from the asset view screen.

![image](https://cloud.githubusercontent.com/assets/22087997/20938452/2b24b048-bbb9-11e6-9d5e-a14950f6afae.png)

![image](https://cloud.githubusercontent.com/assets/22087997/20938464/3743d322-bbb9-11e6-9b3f-c6487894502f.png)

![image](https://cloud.githubusercontent.com/assets/22087997/20938475/416964b6-bbb9-11e6-9e86-bf19bdfd551f.png)

#### Please confirm you have done the following before posting your bug report:

- [ X ] I have enabled debug mode
- [ X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
 v3.6.1 build 5 (g6f9a82f) 

- What OS and web server you're running Snipe-IT on
Ubuntu 14.04

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual / Git (just did a hard reset to Origin/master, and issue is still there)

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
N/A

- If a stacktrace is provided in the error, include that too.
N/A

- Any errors that appear in your browser's error console.
N/A

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
Yes

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
N/A

- Include what you've done so far in the installation, and if you got any error messages along the way.
N/A

- Indicate whether or not you've manually edited any data directly in the database
N/A

**Comment by delinski111** [comment]
Nope, Im just dumb.

It was where it always has been, in the purchase cost field

**Comment by snipe** [comment]
![coffee](https://cloud.githubusercontent.com/assets/197404/20939228/cb0dd0d8-bba2-11e6-8f78-b1aa5be8bdcf.gif)

:)
