### ISSUE TITLE
Asset Model Creation issue

### ISSUE THREAD

**Issue by macpacadmin** [snipe/snipe-it#3026]
When creating a new asset model and selecting save the information is saved accordingly

-----

#### Actual Behavior

Selecting on web front end
Create New/Asset/Model/New/***product info**/Save

After selecting save the window just sits there and asset model is not created

Debug info

Messages
    [22:04:56] LOG.error: exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054...errorlog

Exceptions
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'note' in 'field list' (SQL: insert into `models` (`name`, `manufacturer_id`, `category_id`, `model_number`, `user_id`, `note`, `eol`, `fieldset_id`, `updated_at`, `created_at`) values (Iphone 6S Plus, 1, 6, , 4, , , , 2016-12-06 22:04:56, 2016-12-06 22:04:56))/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php#729Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'note' in 'field list'/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php#457

Queries
select * from information_schema.tables where table_schema = 'snipeit_laravel' and table_name = 'users'
400μs/bootstrap/cache/compiled.php:6325snipeit_laravel
select * from information_schema.tables where table_schema = 'snipeit_laravel' and table_name = 'settings'
280μs/bootstrap/cache/compiled.php:6325snipeit_laravel
select count(*) as aggregate from `users`
210μs/app/Models/Setting.php:69snipeit_laravel
select * from `users` where `users`.`id` = '4' and `users`.`deleted_at` is null limit 1
310μs/bootstrap/cache/compiled.php:1009snipeit_laravel
select `groups`.*, `users_groups`.`user_id` as `pivot_user_id`, `users_groups`.`group_id` as `pivot_group_id` from `groups` inner join `users_groups` on `groups`.`id` = `users_groups`.`group_id` where `users_groups`.`user_id` = '4'

-----

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Snipe-IT version 3.6.1 build 5
- Ubuntu Server 15.04
- Git Installer
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - **As above**
- Asset model creation under new asset option - Save button generates error
- issue is reproducible on the demo. please see screenshot
![snipedemoerror](https://cloud.githubusercontent.com/assets/11169483/20946737/e4075662-bc70-11e6-9dd1-93270b9e64b7.JPG)

- No database modifications have been made

**Comment by snipe** [comment]
This is already fixed in the latest release.
