### ISSUE TITLE
Upgrade from V3.6.1 to V3.6.2

### ISSUE THREAD

**Issue by macpacadmin** [snipe/snipe-it#3027]
Successful upgrade to Version 3.6.2

-----

I have tried 3 methods of upgrading versions 2 of which point me back to version 3.6.1

I have followed both your instructions here - https://snipe-it.readme.io/docs/how-to-upgrade
and on the release notes here - https://github.com/snipe/snipe-it/releases/tag/v3.6.2

Based of the comment " Simply pull down the newest release, copy the files over, and run whatever commands the release notes specify" I have completed the following

Method 1
I have downloaded 3.6.2 and extracted accordingly

I have then copied using *.* from my current install 3.6.1 into my 3.6.2 and renamed root folder accordingly - completed instructions found in release notes successfully with no errors. However 3.6.1 loads again even after completing two extra steps php artisan config:clear and php artisan config:cache

Method 2

I have downloaded 3.6.2 and extracted accordingly

I have then copied using *.* from  3.6.2 into my current install 3.6.1 - completed instructions found in release notes successfully with no errors. However 3.6.1 loads again even after completing two extra steps php artisan config:clear and php artisan config:cache

Method 3

I have download 3.6.2 and extracted and accordingly

Copied the .ENV file over and proceeded with the upgrade instructions which failed after the first one with the error PHP Warning:  require(/var/www/html/snipeit/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/snipeit/bootstrap/autoload.php on line 17

presumably due to it being a fresh install with no database or something?

I feel I maybe going wrong with the method of copying perhaps? if you could help to point me in the right direction where I am going wrong that would be great

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----

- 3.6.1
- Ubuntu 15.04 Apache2
- manual
No DB edits

**Comment by macpacadmin** [comment]
I notice above after the comment _"I have then copied using"_ that star . star is being shown as .

**Comment by macpacadmin** [comment]
Resolved-ish

I completed the following to get this upgraded

Method 3 (above)

used various relevant parts out of the upgrade instructions found here https://snipe-it.readme.io/docs/upgrading - upgrading to 3.0

Renamed my 3.6.1 install
mv snipe-it-backup

I have download 3.6.2 and extracted and accordingly

completed these steps
cd <install-dir>
curl -sS https://getcomposer.org/installer | php

php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload

Copied the .ENV file over out of my backed up 3.6.1 install

Adjusted the folder values to match my previous 3.6.1 install
cp ../snipe-it-backup/storage/app/backups/* snipe-it/storage/app/backups/
cp ../snipe-it-backup/storage/private_uploads/* snipe-it/storage/private_uploads/
cp ../snipe-it-backup/public/uploads/* snipe-it/public/uploads/

changed ownership of storage directory
sudo chown -R www-data snipe-it/storage

Then ran
php artisan migrate


I now have a successful upgrade to 3.6.2


If someone could still point out to me where i was originally going wrong that would be awesome. However this could be classed as resolved now

**Comment by snipe** [comment]
It's hard to say where you were going wrong witout seeing into your filesystem. (For example, in your first two attempts, what did the version say in `config/version.php`? That would tell us whether the copy was bad, or the config values were still being caches for some reason.)

Method 3 should have worked, but the upgrade instructions had the cmposer install second, where it should have been first.

In general, your life will be much easier if you can get the git install/upgrade version working. At that point, your upgrade is literally: `git pull` and then running the commands we tell you to run.

**Comment by macpacadmin** [comment]
first two attempts had both v3.6.1 listed. This would make sense considering I was doing a complete all inclusive copy this would have potentially replaced the v3.6.2 file with v3.6.1 maybe? should I be doing an all inclusive copy or just specific folders/files?

I originally tried the git pull and running the commands however moved to the more manual approach after my first failed attempt incase it was offering the v3.6.1 version instead of v3.6.2 - will do this again for future releases :)

**Comment by snipe** [comment]
I'm not sure what was going on with the first two. In general, when upgrading, you want to overwrite everything EXCEPT the storage and public/uploads directories, so your version file should have been overwritten. Sometimes `php artisan view:clear` helps as well, but if the actual version file still said 3.6.1, that's wouldn't matter.
