### ISSUE TITLE
[Feature Request] Location-specific LDAP import

### ISSUE THREAD

**Issue by richardhofman6** [snipe/snipe-it#3033]
#### Expected Behavior (or desired behavior if a feature request)

This feature request is for location-specific LDAP filters. These would be hugely beneficial for automatic location assignment to imported users. For example, one might have two locations: Australia and UK.

Australia has an LDAP filter `&(objectCategory=person)(objectClass=user)(memberof=CN=Australia Office,OU=Users,DC=example,DC=com)`
UK has a different LDAP filter: `&(objectCategory=person)(objectClass=user)(memberof=CN=UK Office,OU=Users,DC=example,DC=com)`

When the LDAP import is triggered, it could first check if any locations have filters, and iterate through those, importing with location assignment for each new user. Failing that, it could fall back to the current method of having a global LDAP filter.

-----

#### Actual Behavior
Currently, the only import option is to have one filter, and to run the import against a specific location. This means that every imported user is assigned to the selected location at runtime, and as the filter setting is global, importing users to differing locations is a cumbersome process, easily reversible by accident.

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.6.1 build 5 (g6f9a82f
- What OS and web server you're running Snipe-IT on: Apache/2.4.6 (CentOS)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual

**Comment by snipe** [comment]
Pretty sure there is already at least one GH issue for this.

**Comment by richardhofman6** [comment]
@snipe Indeed there are - not sure why I hadn't spotted them until now! I'll close this for now, looking forward to v3.6.2!
