### ISSUE TITLE
Whoops, looks something went wrong !

### ISSUE THREAD

**Issue by mrabbat** [snipe/snipe-it#3034]
#### Expected Behavior (or desired behavior if a feature request)

When a user accepts an asset, it's giving the error "Whoops, looks like something went wrong".
This should not basically happen and the user should get to the assets page

-----

#### Actual Behavior

Getting the error message "Whoops, looks like something went wrong".
I'm running version 3.6.2 now.
This started when I upgraded from version 3.4 to 3.6.2.
Also noticed that for an admin user, I don't receive the error message
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Please provide debugging info and/or error logs, as requested in the original issue template
