### ISSUE TITLE
[Feature Request] Slack Notifications for Stock Near/Below Minimum Quantity

### ISSUE THREAD

**Issue by DannyHolyoake** [snipe/snipe-it#3036]
#### Expected Behavior (or desired behavior if a feature request)

Snipe-IT could send a Slack message when stock reaches below its minimum quantity (or below the notification-threshold as set in Settings).

Bonus points if it could mention the channel or certain users.

**Comment by rkantos** [comment]
My opinion is this should be implemented as a wider system with either IFTTT or Zapier.
