### ISSUE TITLE
Default Status Labels are always in SideNav even if they have been changed.

### ISSUE THREAD

**Issue by grandmamoses** [snipe/snipe-it#3038]
#### Expected Behavior (or desired behavior if a feature request)

We've changed or re-named some of the default status labels. Only those Status labels that exist and are configured to show in the SideNav, should be shown in the SideNav.

-----

#### Actual Behavior

The new names/labels are shown in the SideNav if configured to, however the original default status labels (that now don't exist) are still shown in the SideNav.

#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running -> 3.6.2
- What OS and web server you're running Snipe-IT on -> Ubuntu 16.4, Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Install.sh

Thanks for a wonderful product!

**Comment by snipe** [comment]
The ones that stay there are status label types, not actually status labels. You can have 10 (or however many) status labels with the label type of deployable. All of those assets will show up in the Ready to Deploy status label type in the nav.
