### ISSUE TITLE
Accessoires: multiple buys per accessory

### ISSUE THREAD

**Issue by louisdj** [snipe/snipe-it#3040]
At this moment I need to create a new input for every time I buy a new accessory, but I think it should be useful when I can create for example one time an 'Apple Magic Keyboard Azerty' and when I buy new ones I could update the quantity in stock by adding them (with their purchase date) instead of creating a new accessory.

**Comment by DannyHolyoake** [comment]
100% agreed.

The current accessory/component model does not work for us at all. I don't want to have duplications of accessories and components when they support quantity levels.

Accessories and Components would ideally work similar to (but **not identical to**) Asset Models; I have a Component listing for each component model I have (e.g. Intel i3-6100), and within that Component is a list of our full stock of i3's, with individual serial number and purchase info fields, and each CPU could be checked out to a user or asset. This would allow us to track each PC component we order whilst keeping them clearly separated from the assets list.

**Comment by ced455** [comment]
Hello this could be very helpful !
I order mice and keybord in bach of 3, so having a ebtry per order make it hard.
