### ISSUE TITLE
Syntax error near unexpected token 'newline'

### ISSUE THREAD

**Issue by quietandy** [snipe/snipe-it#3041]
Hi,

I'm having an issue installing snipe-it on Ubuntu 16 LTS. I have been following the guide, but once I have downloaded the installer then chmod it and run, I get the following error.

./install.sh: line 1: syntax error near unexpected token 'newline'
./install.sh: line 1: '!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd"'

I know I am just being stupid and doing something wrong, anyone have a solution.

Thanks

ANdrew

**Comment by mtucker6784** [comment]
Hey there, is it possible you're behind a content filter? At work we have one that if I'm not authenticated through it, I pull down HTML / XML lines instead of the actual file.
