### ISSUE TITLE
Depreciation Report will not run

### ISSUE THREAD

**Issue by ghost** [snipe/snipe-it#3043]
#### Expected Behavior (or desired behavior if a feature request)
Depreciation Report to run

-----

#### Actual Behavior

The snipeit page isn’t working

snipeit is currently unable to handle this request.
HTTP ERROR 500

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 
3.60
- What OS and web server you're running Snipe-IT on:  
Ubuntu 14, Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error:  
Reports - Depreciation
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- If you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by philmatu** [comment]
I can confirm this report... Additional information, this happens with the Docker container image with a large amount of assets.  The solution is to increase the PHP memory limit in php.ini.  

A feature request might be to incorporate an environmental variable into the docker container that directly changes this limit.
