### ISSUE TITLE
Requestable Asset Models includes archived & checked out in count

### ISSUE THREAD

**Issue by thinkl33t** [snipe/snipe-it#3044]
#### Expected Behavior (or desired behavior if a feature request)

In Assets -> Requestable, the count of "Avail" should only include requestable-checked in items.

-----

#### Actual Behavior

The count appears to include all models of that type, including archived ones.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running **v3.6.2 build 10 (g927a12f)**
- What OS and web server you're running Snipe-IT on **Debian Jessie**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Manual Install**
- Indicate whether or not you've manually edited any data directly in the database **Nope**

**Comment by dmeltzer** [comment]
Good catch.  I'll try to fix this tonight.
