### ISSUE TITLE
Multiple Sort by manufacturer

### ISSUE THREAD

**Issue by diekmanu** [snipe/snipe-it#3045]
#### Expected Behavior (or desired behavior if a feature request)

Will sort by the actual name - not the internal ID

-----

#### Actual Behavior

When doing multipe sort the order for manufacturers reflects the internal ID numbering.

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: 3.6.2
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

**Comment by ernestasen** [comment]
I have similar issue on Accessories page. When I click to sort by Manufacturer it sorts by recently created accessories. 
I would expect it to sort alphabetically by manufacturer. This is the result I get:
![screen shot 2016-12-29 at 15 06 52](https://cloud.githubusercontent.com/assets/5003110/21544566/ccf797c4-cdd8-11e6-81f2-b146f77a0d09.png)

Snipe version 3.5.2-11-g5a835a5
