### ISSUE TITLE
Clearly Indicate a Checked-Out Asset in Update Asset Screen ("Checked out to", option to one-click checkin)

### ISSUE THREAD

**Issue by punny13** [snipe/snipe-it#3046]
#### Expected Behavior (or desired behavior if a feature request)

When opening the Asset Update screen (via Edit Asset option) for an asset that has been checked out, the Status field would not be visible.

Note: My impression is that this was addressed over a year ago in issue 833, but it does not appear to be addressed in the Snipe-IT version that I am using.

-----

#### Actual Behavior

When opening the Asset Update screen (via Edit Asset option) for an asset that has been checked out, the Status field is visible showing the value that it was before it was checked out.  This will confuse the user.

-----

#### Please confirm you have done the following before posting your bug report:

- [This is not a bug] I have enabled debug mode
- [YES] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.5.2

- What OS and web server you're running Snipe-IT on
Windows 7, Apache 2.4

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Asset Update (aka Edit Asset)

- If a stacktrace is provided in the error, include that too.
N/A

- Any errors that appear in your browser's error console.
N/A

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
N/A

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
N/A

- Include what you've done so far in the installation, and if you got any error messages along the way.
N/A

- Indicate whether or not you've manually edited any data directly in the database
Yes, MODELS.FIELDSET_ID and ASSETS.LAST_CHECKOUT.

**Comment by snipe** [comment]
I think the better solution here would be to offer a checkbox to let the the user check in the item and then also apply and additional changes they want. Otherwise it's extra clicks to edit and check in.

**Comment by punny13** [comment]
It's not so much an issue with the process of checking in/out an asset, but one of simply editing an asset that is currently checked out.  Say, the user wants to edit this asset to change a custom field value, but then notices that the Status is 'Ready to Deploy'.  That would clash with the fact that the asset is checked out and possibly confuse the user, so wouldn't it be best to hide the Status in this case?

**Comment by snipe** [comment]
The asset status is the asset status. It shouldn't be forgotten (or default to RTD) just because you're editing it.

**Comment by punny13** [comment]
I'm not asking for it to be forgotten or changed to RTD.  Just hidden so it doesn't confuse the user.  I'll give an example:

- An asset is not yet checked out and has the status 'Ready to Deploy'.  When listing this asset, it shows a status of 'Ready to Deploy'.  When opening the edit screen for this asset, the status is also 'Ready to Deploy'.  All good.
- A user now checks out this asset.
- Another user (perhaps a few days later) then lists this asset as sees a status of 'Deployed'.  However, if they go to the edit screen of this asset, the status shows 'Ready to Deploy'.

**Comment by snipe** [comment]
Unfortunately, that will only cause more confusion for users who already use the existing workflow. We could add a note (if it's checked out) that it's checked out to someone, but we cannot remove the field altogether, or the people who use it to change the status will be confused and frustrated.

**Comment by punny13** [comment]
Understood.  I will instead work on making sure the users understand the scenario in the example I gave.

**Comment by snipe** [comment]
I'm going to re-open this and change the title. You definitely bring up some good points here, UX-wise, and I'd still like to make it easier on your users. I think there's a balance we can find so everybody wins.

**Comment by punny13** [comment]
Thank you for your help, and for your prompt responses.
