### ISSUE TITLE
Assets only get partial exported

### ISSUE THREAD

**Issue by thorenhorstmann** [snipe/snipe-it#3047]
#### Expected Behavior (or desired behavior if a feature request)

I want to export all the assets as an excel file from the All Assets view.

-----

#### Actual Behavior

Most of the time only 50 items are in the exported table. This happens also with other file extensions. When i export as CSV, sometimes two files are downloaded. In this case, one is correct.

-----

#### Please confirm you have done the following before posting your bug report:

I tested this on the demo snipe page https://demo.snipeitapp.com/hardware

-----
#### Please provide answers to these questions before posting your bug report:

- OS is OS X El captain

**Comment by snipe** [comment]
The is a known issue that already has issues assigned to it. Just use the custom report and export to CSV.
