### ISSUE TITLE
Link redirect not working correctly

### ISSUE THREAD

**Issue by kabatt** [snipe/snipe-it#3048]
#### Expected Behavior (or desired behavior if a feature request)

Image/data populates error.  Redirects to different web page.  Happens when creating a new asset, when moving around through user data, and when an user accepts the EULA.

-----

#### Actual Behavior

 404 Page not found.
Sad panda. We could not find the page you were looking for. You should maybe return to the dashboard. ....Even worse, the panda does not show up, displays as broken link.

When navigating around I will sometimes notice it will redirect me too a link like this...

http://inventory.domain/hardware/inventory.domain/assets/img/sad-panda.png 

If I manually remove inventory.domain/hardware/ then it will load.  I am thinking this is an IIS issue but would like input first.  Thanks for all of the help!
-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v3.6.0-g91caba0 
- What OS and web server you're running Snipe-IT on - Windows Server 2012 R2, IIS8
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - No errors reporting
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
check your app_url in your .end - what's it say?

**Comment by kabatt** [comment]
I am assuming that you are talking the .env.  If so see below, otherwise where is the .end?

APP_URL=inventory.domain

**Comment by snipe** [comment]
It needs the protocol as well, per the docs. 

![img_0030](https://cloud.githubusercontent.com/assets/197404/21164038/7d60e484-c14b-11e6-82d9-54aec133d070.PNG)

**Comment by mpkr** [comment]
I have the same problem when importing assets, it redirects me to: http://inventory.mydomain/undefined 

APP_URL is set to http://inventory.mydomain
I did run php artisan cache:clear, php artisan config:cache, reset website, reset IIS, clear browser cache and the error still occurs. Please help.
