### ISSUE TITLE
[Authentication Required] When load page Reports

### ISSUE THREAD

**Issue by quainhankid** [snipe/snipe-it#3049]
Hello everyone.
I'm using WInserver
with IIS 7
and Snipe-IT 3.6.2
An error occurred while loading the page report
Running at localhost then normal but when I run in the domain then the error

I have full permission on the folder 
/public
/storage
/cache

![snipe-it](https://cloud.githubusercontent.com/assets/5300644/21175043/0ddbe302-c213-11e6-8c28-43843515da60.jpg)

**Comment by snipe** [comment]
Does that user have permission to view reports?
