### ISSUE TITLE
Language-specfic (utf8) Dashboard problems?

### ISSUE THREAD

**Issue by diekmanu** [snipe/snipe-it#3051]
#### Expected Behavior (or desired behavior if a feature request)

When I add/delete seats to a license the dashboard/activity reports should reflect these changes.

#### Actual Behavior

Dashboard/activity reports will not show up again, when changing the total number of seats assigned to a license.

-----

It seems to be a language-specific problem (special-chars).
Snipe-IT doesn't like "Gelöschte Lizenzen" or "Lizenzen hinzugefügt" in resources/lang/de. I guess this a utf8 conversion problem.

SERVER/reports/activity/json:

`at Response->setContent(array('total' => '6652', 'rows' => array(array('icon' => '<i class="fa fa-floppy-o"></i>', 'created_at' => 'Dec 13, 2016 8:38AM', 'action_type' => 'gel�schte lizenzen', 'admin' => '<a href="http://gll-abc-w7p126:8103/admin/users/1/view">Manuel</a>', 'target' => '', 'item' => '<a href="http://gll-abc-w7p126:8103/admin/licenses/8/view">Adobe Acrobat X Pro </a>`

When changing this to "Geloschte Lizenzen" and "Lizenzen hinzugefugt" (without the dots) it works as expected. Should be reproducible on the Demo pages, when switching to German. Of course there must be a "deleted seats" or "added seats" row in action_logs.

Hope this will be addressed in 3.6.3

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: 3.6.2
- What OS and web server you're running Snipe-IT on: Win32/nginx
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by dmeltzer** [comment]
Hello,

can you provide more of the backtrace from /reports/activity/json?  Trying to track down where the anger comes from.

**Comment by dmeltzer** [comment]
I think I see some of the issues.  Firstly, can you confirm that in the database the utf-8 strings are stored correctly in the action_logs table?

I think some of this is because we are doing string comparisons on the 'action_type' string to the untranslated form, so our giant ugly nested if statement isn't matching any of these logs.  It feels wrong to translate the action_type before we do the comparisons.... I almost wonder if we're better to store it as the english string, and do the translation when it's pulled out of the database.  It's that or move to some sort of less string based method of identifying what the action was.

**Comment by diekmanu** [comment]
Hi,

it's a Windows environment running nginx 1.7.10, php 5.5.6 and mariadb 10.1.3. Something in php.ini, which could cause this?

**Comment by diekmanu** [comment]
Dashboard is also having problems with htmlspecialchars:

![grafik](https://cloud.githubusercontent.com/assets/13235891/21315230/63c6f81a-c5fb-11e6-8423-90df3bd61376.png)
