### ISSUE TITLE
setup page redirects to itself   ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by rronen04** [snipe/snipe-it#3053]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

The setup page needs to show up
-----

#### Actual Behavior

(what actually happens goes here)

The setup page redirects itself to the same setup page
-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: the latests available for docker, I took the latest docker image
- What OS and web server you're running Snipe-IT on: centos 2.6
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error I get nothing, only the redirect. I do see that the Cookie was provided and the browser send the cookie back but I get redirected
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: I am installing, so when I point to the main page I get redirected to the setup.
- If a stacktrace is provided in the error, include that too. noting
- Any errors that appear in your browser's error console. noting
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

from Apache:

- - [14/Dec/2016:17:23:55 +0000] "GET /snipe/setup HTTP/1.1" 302 884 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.21 Safari/537.36"
- - [14/Dec/2016:17:23:55 +0000] "GET /snipe/setup HTTP/1.1" 302 884 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.21 Safari/537.36"
- - [14/Dec/2016:17:23:55 +0000] "GET /snipe/setup HTTP/1.1" 302 884 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.21 Safari/537.36"

error.log

cat ./var/log/apache2/error.log
[Wed Dec 14 17:23:48.207235 2016] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.20 configured -- resuming normal operations
[Wed Dec 14 17:23:48.207269 2016] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D NO_DETACH'

**Comment by snipe** [comment]
@uberbrady can you take a look at this when you get a moment?

**Comment by uberbrady** [comment]
The docker image is supposed to be already set up, you don't have to go to the Set Up page. All you have to do is set the appropriate docker environment variables when you launch, and then it should connect to whatever database you require. See https://snipe-it.readme.io/docs/docker for more details
