### ISSUE TITLE
Unable to receive alerts through e-mail

### ISSUE THREAD

**Issue by itims** [snipe/snipe-it#3055]
Hi,
I didn't get alerts through Email that I given in settings. My mail server is working fine because mail has been received by individual users mail account when we assign asset to that user. Could you please help me to resolve this issue.

#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running -  **v3.6.2**
- What OS and web server you're running Snipe-IT on - **Linux Mint & Apache 2**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - **Manual**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Do you actually have any EOL assets, etc? If there are not alerts to send, nothing will be emailed. Did you set up a cron to actually send the alerts? A little more info would go a login way here.

**Comment by itims** [comment]
We didn't enter any values in EOL field of asset model, and how to setup a cron?
We are getting alert in dashboard as recent activity, is it possible to get this activities through the mail?.

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/configuring-alerts
