### ISSUE TITLE
Adding supplier from create license page is not working

### ISSUE THREAD

**Issue by avary69** [snipe/snipe-it#3070]
#### Expected Behavior (or desired behavior if a feature request)

The create supplier page should open when I click the "New" button  in the create new license page.

-----

#### Actual Behavior

nothing happens

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running **v3.6.2 build 18 (g6f1e0d6)**
- What OS and web server you're running Snipe-IT on **Windows Server 2012 R2**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **git clone**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **no error**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **/admin/licenses/create**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. **none**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). **yes. It is**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database **no changes directly in db**

**Comment by jacksjp** [comment]
I have the same issue

**Comment by skleinau** [comment]
The same issue on 3.6.4 on our side.
