### ISSUE TITLE
[Feature Request] Documentation attachment to license

### ISSUE THREAD

**Issue by dlane2** [snipe/snipe-it#3071]
It would be beneficial to be able to attach scans of license agreements to the actual license entry much like the asset currently does.

**Comment by therealjoshuad** [comment]
I think you can already do that, there should be a files or upload tab?

**Comment by snipe** [comment]
Yes, that feature already exists. 

![Uploading View_License_-_Enterprise-wide_clear-thinking_support____Snipe-IT_Asset_Management_and_Cloud_Player___Audible_com.png…]()

**Comment by dlane2** [comment]
It is not where I thought it would be.  Thanks!
