### ISSUE TITLE
Maintenance error

### ISSUE THREAD

**Issue by rd-persaud** [snipe/snipe-it#3072]
When I try adding a maintenance to an asset I get the following error.

![capture](https://cloud.githubusercontent.com/assets/24591403/21231772/7086a3a8-c2b7-11e6-90d8-1963ea5b9e59.PNG)

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by rd-persaud** [comment]
Version of Snipe-IT you're running
What OS and web server you're running Snipe-IT on (3.6.0)
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) (install.sh)
If you're getting an error in your browser, include that error (Undefined variable: item)
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error (http://myserver/admin/asset_maintenances/create/69)
Any errors that appear in your browser's error console. (Undefined variable: item
/var/www/snipeit/storage/framework/views/63776a03a2fce00afab7dd27f145e409b9f56c58.php#4)
Confirm whether the error is reproduceable on the demo. (No)
Include any additional information you can find in app/storage/logs and your webserver's logs.
Include what you've done so far in the installation, and if you got any error messages along the way. (No)
Indicate whether or not you've manually edited any data directly in the database (No)

**Comment by dmeltzer** [comment]
Can you try a `php artisan view:clear` 

Thanks,

**Comment by rd-persaud** [comment]
I still have the same problem.

**Comment by snipe** [comment]
When you upgrade to the latest, are you still seeing this issue?

**Comment by rd-persaud** [comment]
I started getting the problem when I did the upgrade. It was working fine before the update.
