### ISSUE TITLE
Issue when Searching for assets assigned by user full name.

### ISSUE THREAD

**Issue by JExactly** [snipe/snipe-it#3073]
#### Expected Behavior (or desired behavior if a feature request)

Search to return results for all assets assigned to a user

-----

#### Actual Behavior

If you type a partial name For example: First name only, results are returned, if you type last name only results are returned. if you type first name and last name together, no results are returned.

**(may affect other search queries)**

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running  v3.5.2-11-g5a835a5
- What OS and web server you're running Snipe-IT on Ubuntu 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: ALL Assets page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by aglasson** [comment]
I can confirm having this issue on 3.6.2.

**Comment by JExactly** [comment]
@aglasson Do you not think that it is an issue being able to search by first & last name in the search box?

**Comment by aglasson** [comment]
It's just not something that has a negative impact on me.
I'd say it's definitely a bug.

**Comment by snipe** [comment]
It's not a bug, more just a difference in expectations. If you enter more than one word in the search, we can basically handle that one of two ways: split the phrase and search on each word separately, or search on the phrase. Either way, the first name and last name fields are separate, so we'd have to run an additional search on the concatenation.

**Comment by JExactly** [comment]
That makes sense on why it behaves that way, Will there be plans to add additional functionality to the search feature to allow searching concatenated fields? It would seem adding manual search filtering defeats the purpose of searching all fields at once.

**Comment by JExactly** [comment]
@snipe Any chance there will be the ability to search by names that are concatenated?
