### ISSUE TITLE
Upgrade Snipe-IT v3.4 to latest

### ISSUE THREAD

**Issue by Mkazhuka** [snipe/snipe-it#3074]
Hello,

I have Snipe-IT installed on Windows Server 2012 and IIS 8. I was wondering if someone can give me a link to instructions on how to upgrade to the latest version.

**Comment by JExactly** [comment]
Right here: https://snipe-it.readme.io/docs/how-to-upgrade

**Comment by Mkazhuka** [comment]
Those composer commands do not work for windows.

**Comment by JExactly** [comment]
@Mkazhuka I Apologize, Windows doesn't require you to use the PHP command If i recall when issuing the commands. Try running them without PHP artisan.. etc..

It's been a while since I had snipe running in IIS.

**Comment by Mkazhuka** [comment]
@JExactly ,says windows cannot open composer.phar when I run it in cmd

**Comment by JExactly** [comment]
try just using `composer install --no-dev --prefer-source` etc..

**Comment by JExactly** [comment]
also, make sure you did this : 

`Windows`
Download Composer-Setup.exe from the Composer website.
Move the Composer-Setup.exe file C:\inetpub\wwwroot\snipe-it
Open C:\inetpub\wwwroot\snipe-it in Windows Explorer
Right click and select Composer Install. This will install the dependencies.

**Comment by Mkazhuka** [comment]
@JExactly , Yup that what I did, Thank you. Im assuming I just exclude the following commands?

php artisan migrate
php artisan config:clear
php artisan config:cache

**Comment by JExactly** [comment]
You will still need to run those commands, just remove "PHP" from the command before running

**Comment by Mkazhuka** [comment]
@JExactly Im getting Whoops, looks like something went wrong. when I try to log in now.

**Comment by Mkazhuka** [comment]
@JExactly Nvm, Cleared the Cache on my browser and it works now.

**Comment by JExactly** [comment]
@Mkazhuka Glad you got everything sorted!!

**Comment by Mkazhuka** [comment]
@JExactly Any idea why It wouldnt be able to login after the upgrade? It allows me to login after I reset my password however if I log out I have to reset my password each time.

**Comment by JExactly** [comment]
@Mkazhuka I would check your laravel logs and post them to your new issue you created.
