### ISSUE TITLE
Upgraded from 3.4 to 3.62 Issues (Windows Server/IIS)

### ISSUE THREAD

**Issue by Mkazhuka** [snipe/snipe-it#3078]
Hello,

I recently upgraded from 3.4.0 to 3.6.2 and now whenever I try to login I get the "Whoops, looks like something went wrong.", I can successfully login by clicking forgot my password and resetting it, however if I log out and try to login again I get "Whoops, looks like something went wrong." and I have to reset my password again to login.

Running on Windows Server 2012 and IIS8

I downloaded the latest source from https://github.com/snipe/snipe-it/releases/tag/v3.6.2, Extracted and overwrote the installation directory files. Then I ran all the commands below.

composer install --no-dev --prefer-source
composer dump-autoload
php artisan migrate
php artisan config:clear
php artisan config:cache

When I am logged in it does show that it is running Version v3.6.2 build 10 (g927a12f)

**Comment by snipe** [comment]
Please provide app logs

**Comment by Mkazhuka** [comment]
@snipe , How do I provide the logs? I turned on debug in the .env file however it doesnt seem like it is working,

**Comment by Mkazhuka** [comment]
Still having the issue. Any Help?

**Comment by Mkazhuka** [comment]
Got debug mode working.

FatalThrowableError in Ldap.php line 43:
Call to undefined function App\Models\ldap_connect()

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/common-issues#call-to-undefined-function-controllersadminldap_co
