### ISSUE TITLE
Email notification when license expires

### ISSUE THREAD

**Issue by heizung76** [snipe/snipe-it#3082]
#### Expected Behavior

I want to get a notification when my license expires.
-----

#### Actual Behavior

I enabled Alerts, filled in an email address and set the Expiring Alerts Threshold (in days) to 1 in the admin settings. Now I set up some test Licenses which expires today tomorrow the day after tomorrow and so on but I don’t get any notification that my license expires. If I click on “I forgot my password” the mail server sends out an email and I receive it on my email address so this works. Is there anything else I have to set up for the expiring alerts? 

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running:  v3.6.2 build 18 (g6f1e0d6)
- What OS and web server you're running Snipe-IT on: Ubuntu 16.04.1 LTS, Apache2
- What method you used to install Snipe-IT: install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Licenses page, I created Licenses with expiration date for today tomorrow and so on to trigger an alert
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo: no
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database: no

**Comment by snipe** [comment]
Did you actually set up a cron to trigger the email alerts?

**Comment by reison007** [comment]
Is there any way to configure alerts to remind me about expiring licenses like 6 months, them 3 months  before the end of a license or a contract?
This need comes from the large amount of time that my company take to do a process of renewing a contract.
We had a some problems related to lack of a license/contract management solution, and I am introducing Snipe-IT in here.
