### ISSUE TITLE
Feature Request - Add setting to enable "change password" feature on the user profile page

### ISSUE THREAD

**Issue by mircea-c** [snipe/snipe-it#3085]
#### Expected Behavior (or desired behavior if a feature request)

Setting to enable a "change password" feature for a user with no admin privileges.

-----

#### Actual Behavior

Currently a user can change only their own password if they have administrative rights or through the forgot password link on the login page. 

Only applies to non-ldap integrated installs.
-----

**Comment by snipe** [comment]
This will be in v4
