### ISSUE TITLE
Cannot create assets in asset models view

### ISSUE THREAD

**Issue by diekmanu** [snipe/snipe-it#3086]
#### Expected Behavior (or desired behavior if a feature request)

In asset models view (SVR/hardware/models/[model_id]/view) it should be possible to create assets.
-----

#### Actual Behavior

You click on create asset, enter the specific details, click on save and nothing happens.
No error / the creation page just gets refreshed and there is no new entry.

The default way of using  SVR/hardware/create works when manually choosing the right asset model.
When the model ID gets appended to the URL SVR/hardware/create/[model_id] asset creation won't work.

Reproduceable on the demo pages.

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.6.2
- What OS and web server you're running Snipe-IT on: nginx/win32
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: no error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: s. descripton
- If a stacktrace is provided in the error, include that too: nope
- Any errors that appear in your browser's error console: no. 
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): yes
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
> Version of Snipe-IT you're running: latest

That's not particularly helpful. Please give us an actual version number, so we know if you pulled from a release, or from master/develop branches.

**Comment by diekmanu** [comment]
v3.6.2 release
