### ISSUE TITLE
Feature Request - Create Labels from Asset Detail Page

### ISSUE THREAD

**Issue by VanillaNinjaD** [snipe/snipe-it#3088]
Would it be possible to allow us the ability to generate individual Labels from the Asset Details screen?

I often search for an Asset using the Asset ID quick search box, update the asset information, then would like to print a single label for that Asset. To do this, I have to back out of the asset detail screen, search again using the generic search box, then select the asset, then select "Generate Labels" from the action menu.

For our single labels, we use the built in GNOME screenshot utility on Linux or the free and open-source "Greenshot" screen-shot utility on Windows to draw a box around the labels and have them automatically print out of a Dymo label printer. If the "Generate Labels" action button was available from within this screen or the QR code was replaced with the entire label, it would be a big help for us.

I have prepped a modified screenshot of what I think both of these options might look like.

As always, thanks for such an awesome application!!

![snipe-it_wishlist](https://cloud.githubusercontent.com/assets/7405702/21356066/fa20b752-c695-11e6-8704-a593992b132e.png)

**Comment by snipe** [comment]
If the label appears on that view screen, what does the generate label button do?

**Comment by VanillaNinjaD** [comment]
I prepared the one screenshot to illustrate the way I envisioned both options in my head

I was leaving the choice up to you and the community on what might work the best or be the easiest to implement and maintain.

**Comment by snipe** [comment]
Got it, thanks

**Comment by VanillaNinjaD** [comment]
It is still relevant to me.

Thanks!

**Comment by saschafoerster** [comment]
+1

**Comment by VanillaNinjaD** [comment]
Yep!

**Comment by saschafoerster** [comment]
Relevant

**Comment by VanillaNinjaD** [comment]
It is relevant to me

**Comment by saschafoerster** [comment]
Relevant. Again! :)

**Comment by VanillaNinjaD** [comment]
Yep, still relevant

**Comment by saschafoerster** [comment]
Relefant!

**Comment by Awjvail** [comment]
This has been an open feature request for almost 4 years, y'all still haven't added this button?

**Comment by fumunda** [comment]
This button would be nice to have.  Not entirely sure why it seems so difficult to accomplish.  

Still relevant

**Comment by Awjvail** [comment]
Yes

**Comment by saschafoerster** [comment]
🐘
