### ISSUE TITLE
How to display cutom_field on the checkin Email notification

### ISSUE THREAD

**Issue by sysnoo** [snipe/snipe-it#3089]
Currently in Emails sent for checked in asstes we can see only : 
Asset Name:	
Asset Tag:	
Checkin Date:	
Additional Notes:

How to add custom_fields ?

Thanks

**Comment by snipe** [comment]
That's not currently possible, but we can consider adding the option. It would need to be a setting though, since some custom fields may not be appropriate to email to a user.
