### ISSUE TITLE
Multiple Currencies for Licenses

### ISSUE THREAD

**Issue by samsheriff** [snipe/snipe-it#3094]
#### Expected Behavior (or desired behavior if a feature request)

We use Snipe-IT in Canada and do purchases on both CAD and USD but when changing the default currency to USD, all our purchases will show up in USD.
Can we have different currencies for different purchases (e.g. Licenses)? {License_1 = "55.55 USD", License_2 = "77.55 CAD"}
And as for total, I guess if we could hook up with a legitimate exchange data source, we can use the rate of the purchase date and have a clean total.

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.5.2-11-g5a835a5
- What OS and web server you're running Snipe-IT on
CentOS 7.x
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Localized currencies can be set by location, not by specific purchases. If you have USD as your default currency, assets with a default RTD location of location that has a different currency will inherit the location-based currency.

**Comment by samsheriff** [comment]
​There's no problem for assets for but when it comes to *Licenses*, there's
no default-location field!

**Comment by louisdj** [comment]
+1 Same problem in Europe, default currency is EUR but a lot of licenses we buy are in USD.

**Comment by sashashark** [comment]
+1 on this feature request.  Licenses don't have the location field,  so I can't change the currency.

**Comment by darius-ramanauskas** [comment]
+1 pleae work on this

**Comment by TheMinery** [comment]
+1 on this for me as well.

**Comment by carloshmiranda** [comment]
+1 for me.

**Comment by borort** [comment]
+1 for this multi currencies feature

**Comment by twsit988** [comment]
Not sure how this isn't an option already...
+1

**Comment by Eina61** [comment]
I just signed up for hosted service & this is the first problem I have come up against - all our locations are in Malaysia but most of our software licences are in USD - such as our Snipe-IT licence!

**Comment by syswpit** [comment]
+1

**Comment by k4d1sm0** [comment]
+1 here in Brazil we use multiple currencies for licenses

**Comment by cmarina06** [comment]
Yes, indeed, it will be very helpful to work with multiple currencies. 
A solution will be to define multiple currencies as default in the Settings  - Localization.
Therefore we can choose the one we need depending on the purchase invoices.

**Comment by Relix360** [comment]
+1

**Comment by FukjemiCZ** [comment]
:+1: +1 please reopen issue

**Comment by tbucher** [comment]
+1 working in Germany, we also have many licenses in EUR but some in USD (and from time to time might even need PLN, CHF, ...)

**Comment by chevdor** [comment]
Yep, this is missing...

**Comment by dullage** [comment]
+1 on this. We're based in the UK but purchase many of our licenses in USD.

**Comment by untold-jw** [comment]
+1

**Comment by GCHPX** [comment]
+1 having EUR and RMB

**Comment by kankadev** [comment]
+1

**Comment by EquiemProductTeam** [comment]
Hi, are there any plans to introduce multicurrency in some near future?

**Comment by odddenis** [comment]
+1

**Comment by Dominic-Ouellette** [comment]
+1

**Comment by killianbc** [comment]
+1

**Comment by nbj-nine** [comment]
We use the notes field for all the stuff Snipe-IT for some reason will not add.

i.e. billing=month, budget_scope=central, princing=seat, payment=card, currency=usd

Then we can easily get the info for the licenses, but this is not ideal, and it would be very nice if Snipe-IT would add those fields .
