### ISSUE TITLE
Can't reset Asset tag 

### ISSUE THREAD

**Issue by sydit** [snipe/snipe-it#3104]
#### Expected Behavior (or desired behavior if a feature request)

Asset tag value increment by one

-----

#### Actual Behavior

I have imported 59 assets to snipe using built-in import wizard. The last asset has tag id HCW0059. The auto increment option is also enabled on admin settings page. But when I  create a new asset by Create New>Asset , the tag value created is HCW0275 instead of HCW0060. There are no deleted items in "Deleted Assets" page. Also tried "Purge Deleted Records".
I do not want to edit asset tag manually every time.

All previous assets were removed which was created during the testing phase. The server is in production now.

- Snipe-IT version	v3.6.2 build 18 (g6f1e0d6)
- PHP Version	5.5.9-1ubuntu4.20
- Laravel Version	5.2.45
- Manual Install
- Not performed manual editing on DB

- I have enabled debug mode
- I have read checked the Common Issues page

**Comment by sydit** [comment]
Thanks its works!

**Comment by ebonweaver** [comment]
Sorry I'm missing something here... how does one apply this fix?  Was this in a patch release and not mentioned in the release notes?

**Comment by snipe** [comment]
Upgrade to latest

**Comment by sydit** [comment]
Facing same issue once again. Using 4.0.9. My last asset tag before upgrade is HW0854. However after upgrade when I create asset, the tag reset to HW0001. I tried above solutions but it was not successful this time.

**Comment by snipe** [comment]
Not the same issue. Please see the GH issue you opened.
