### ISSUE TITLE
Hosted question

### ISSUE THREAD

**Issue by ghost** [snipe/snipe-it#3110]
If SnipeIT is hosted, is there anyway to automate the export of data?  Would love APIs but evidently not ready yet.

Also, is Maria DB required for a local windows install or will WAMP be OK?

**Comment by snipe** [comment]
@jmathias59 Do you mean a backup, or a particular dataset export?

**Comment by snipe** [comment]
> Also, is Maria DB required for a local windows install or will WAMP be OK?

MySQL or MariaDB are basically the same, and both will work.

**Comment by jmathias59** [comment]
The backup is a single sql file.  We need the ability to automate an export for an import into another database.  The asset list with all fields exported as csv every day/week/etc, automated perhaps thru cron, email to a specific email account.  I understand API will provide what we need but that is still an upcoming enhancement.

James

**Comment by jmathias59** [comment]
Thanks…

James

**Comment by snipe** [comment]
@jmathias59 Automating a specific export isn't currently possible, but we may be able to squeak it in before v4 (API). If not, v4 should be out by the end of the month.

**Comment by snipe** [comment]
Closing this one, since the API is ready and the export automation isn't :)
