### ISSUE TITLE
[Feature Request?] min_amt to NULL instead of 0 by default

### ISSUE THREAD

**Issue by ghost** [snipe/snipe-it#3113]
#### Expected Behavior (or desired behavior if a feature request)
I want to be able to not have minimum amount for accessory, consumable and component. When I save the item it should have NULL value by default, now it saves as 0.

-----
#### Actual Behavior
When I edit the asset, change the data but if I don't want to set min amount it automatically saves with minimum amount of 0. This behaviour triggers me notifications that my accessory have reached 0 when I assign all accessories to someone. Some accessories are required on demand only, so I don't want to see notifications when everything is assigned.

-----
#### Please provide answers to these questions before posting your bug report:
- Version v3.6.2 build 18 (g6f1e0d6)
- Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-57-generic x86_64)
- manual installation
- I don't get any errors in debug mode.
- Accessories, Components, Consumables. Any item I edit and create.
- This is reproduceable on the demo. I created accessory with amount of 1, assigned it to user and now it shows me notification '0 remaining': https://demo.snipeitapp.com/admin/accessories/16/view

**Comment by aglasson** [comment]
Yeah it should definitely work like this:
NULL = Never shows on the quantity notification
0 = Only shows on the quantity notification when all are checked out
# other than 0 = Only shows on the quantity notification having dropped below (maybe equal to?) this number.

**Comment by Oreios** [comment]
I'd like to +1 this.

**Comment by SylentBobNJ** [comment]
+1 Yes, please!

**Comment by graywoodford** [comment]
+1 to this please

**Comment by OmniTroid** [comment]
+1

**Comment by SylentBobNJ** [comment]
Didn't make it into 4.0 :(

**Comment by snipe** [comment]
Can you pull from develop and see if this resolves your issue?
