### ISSUE TITLE
Issue with asset status

### ISSUE THREAD

**Issue by subramanyad** [snipe/snipe-it#3114]
Team,

We have recently started using Snipe-IT for tracking our asset. We have uploaded the existing asset details using csv import and mapped (Check out) to all users manual. 

The problem here is  checked out assets status is showing "Ready to Deploy" when you open any particular asset. But in the main dash board same asset status is showing deployed. 

Please help me to resolve this issue. 

![image](https://cloud.githubusercontent.com/assets/24840397/21563492/f7f8b93c-cea8-11e6-8987-831c7af26e49.png)

![image](https://cloud.githubusercontent.com/assets/24840397/21563501/0d6ef4a2-cea9-11e6-8ab2-d28447f1a63d.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [V ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.6.2 build 10 (g927a12f)
- What OS and web server you're running Snipe-IT on
ubuntu 14.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Asset status Page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by subramanyad** [comment]
Much appropriated if any one can help me on this,

**Comment by dmeltzer** [comment]
Will take a look at this.  We cleaned up a lot of the display code and logic in the develop/v4 branch, so it may be fixed already.  If not is should be fairly simple to do.
