### ISSUE TITLE
[DUPLICATE] [Feature Request] Deactivate minimum quantity notification

### ISSUE THREAD

**Issue by cduverne** [snipe/snipe-it#3118]
#### Expected Behavior (or desired behavior if a feature request)

When Min QTY is set to 0, I don't want to see "Low stock" notifications on the web UI

-----

#### Actual Behavior

Notifications are displayed when Min QTY is set to 0 and QTY is > 0

-----

#### Please confirm you have done the following before posting your bug report:

- [N/A] I have enabled debug mode
- [*] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running : v3.5.1-2-gd7222ae
- What OS and web server you're running Snipe-IT on : Docker Version
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) : Docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error : N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error : All
- If a stacktrace is provided in the error, include that too. : N/A
- Any errors that appear in your browser's error console. : No
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). : Yes
- Indicate whether or not you've manually edited any data directly in the database : No

**Comment by ernestasen** [comment]
I have already submitted the same here: https://github.com/snipe/snipe-it/issues/3113

**Comment by cduverne** [comment]
Duplicate indeed : #3113
