### ISSUE TITLE
Error: The asset you have attempted to accept was not checked out to you.

### ISSUE THREAD

**Issue by abaalkh** [snipe/snipe-it#3120]
Hi,

Every time i checkout an Accessory, the user receives the email to accept it, but is presented with this error:
**Error: The asset you have attempted to accept was not checked out to you.**
In this case i'm checking out to myself.
Assets work with no issue.

Even though in the user logs it can bee seen that it is checked out to the user in question.

I'm using 3.6.2.
![screenshot_1](https://cloud.githubusercontent.com/assets/2372747/21602531/e428b2ea-d1a5-11e6-8c22-1a8779b72d8b.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/2372747/21602532/e428bea2-d1a5-11e6-9e36-55b31c95ceec.png)

Please have a look at the problem.
Thank you!

**Comment by twaltz** [comment]
I am seeing the same issue. Looks like you did some work on this as it was previously broken - #2529. Any update?
