### ISSUE TITLE
Remaining Seats column on license page not correct

### ISSUE THREAD

**Issue by marcpeiser** [snipe/snipe-it#3121]
When viewing the main software licenses page (/admin/licenses), the values under 'Remaining Seats' are all wrong, they seem to display the same value as 'Seats' regardless how many of the seats are actually checked out. For example, I have a license with 25 seats, only 5 are checked out so would expect 'Remaining Seats' to say 20, instead it still says 25 regardless. If I check out more seats, still says 25 available. When I click the license details page (/admin/licenses/x/view), all checked out seats/users are displayed correctly.

Install details:
- Snipe-IT version v3.6.0-g91caba0 running on Ubuntu 14.04.4 LTS and apache 2
- Installed using install.sh a couple years ago
- Problem does not exist on demo site

**Comment by snipe** [comment]
Please try upgrading to 3.6.2

**Comment by marcpeiser** [comment]
I thought I had already upgraded.. sorry. Works with 3.6.2, thank you!
