### ISSUE TITLE
How to add a custom text to asset delivery email  

### ISSUE THREAD

**Issue by dedeoglumrt** [snipe/snipe-it#3122]
#### Expected Behavior (or desired behavior if a feature request)

We need to add text to delivery email for print out and to get a wet signature from the owner
-----

#### Actual Behavior
(We would like to include it in the following delivery email. which php file we need to edit for it)

Hello Murat,
A new item has been checked out under your name, details are below.
Asset Name: 	Hp EliteDisplay Monitör
Asset Tag: 	00009
Serial: 	3CQ6252PW9
Checkout Date: 	2017-01-03 07:44:53
Expected Checkin Date: 	
Additional Notes: 	

Please click on the link at the bottom to confirm that you have received the asset.

I have read and agree to the terms of use, and have received this item.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by dedeoglumrt** [comment]
We would like to include it in the below delivery email. which php file we need to edit for it?
Thank you

**Comment by IxFail** [comment]
I know you can edit the emails when you check in the item see: https://github.com/snipe/snipe-it/issues/2010

You can probably edit the files in the similar directory, but I'm not sure.

**Comment by dedeoglumrt** [comment]
Hello again,
Firstly thank you for your reply.

Where can i find the 'i have read ...' text i marked in the following screenshot.

![snipeit](https://cloud.githubusercontent.com/assets/24897172/21748797/df8cbbba-d596-11e6-9dd9-ad4602f17a5c.jpg)

**Comment by IxFail** [comment]
That line of text is controlled by the language files

https://github.com/snipe/snipe-it/blob/master/resources/views/emails/accept-accessory.blade.php

**Comment by snipe** [comment]
Also know that if you change that in your language file, it will likely be overwritten in your next update.

**Comment by dedeoglumrt** [comment]
where is the text (i have read and agree ) in thah language file?  
i need to translate it to turkish completely.
@snipe why dont you translate asset emails maybe next update??

**Comment by IxFail** [comment]
The text 

> I have read and agree to the terms of use, and have received this item.

Can be found in /resources/lang/*Your used language*/mail.php
at row 37 'i_have_read'=>

But just as @snipe mentiod, all the edits in the language file wille be reverted back at every update

**Comment by dedeoglumrt** [comment]
Thank you guys
