### ISSUE TITLE
Upgrade from 3.4.0 to 3.6.2

### ISSUE THREAD

**Issue by cdjudea** [snipe/snipe-it#3123]
#### Expected Behavior (or desired behavior if a feature request)

The login page looks OK and I manage to login. Right after login  I receive two ErrorException:

Undefined variable: recent_activity (View: C:\wamp64_2\www\snipeit\resources\views\dashboard.blade.php)C:\wamp64_2\www\snipeit\storage\framework\views\bb0e6435bdc4d50924c1457dba02553abb9162b4.php#109ErrorException
Undefined variable: recent_activityC:\wamp64_2\www\snipeit\storage\framework\views\bb0e6435bdc4d50924c1457dba02553abb9162b4.php#109

[error.txt](https://github.com/snipe/snipe-it/files/682756/error.txt)

Everything is install on wampserver 3 
Apache 2.4.17
PHP 5.6.16
Laravel ver:  5.2.45

Thanks
-----

#### Actual Behavior

No errors during upgrade
I run also the commands with no errors.

php composer.phar install --no-dev --prefer-source
php artisan config:clear
php composer.phar dump-autoload
php artisan migrate
php artisan view:clear

-----

#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode
- [ yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
How did you upgrade? It seems like not all of the files were pulled over correctly. v3.6.2 doesn't have a `$recent_activity` variable in the dashboard.

**Comment by cdjudea** [comment]
I manage to fix the problem. The folder copy was corrupt...missing files. I had a backup for my database so I manage to start again with the correct files and everything went well after. Thanks

**Comment by snipe** [comment]
Great, glad you got it sorted!
