### ISSUE TITLE
Images aren't displaying correctly

### ISSUE THREAD

**Issue by 241indyimaging** [snipe/snipe-it#3128]
#### Expected Behavior (or desired behavior if a feature request)
When viewing any page that  has images they don't display.

http://invtracker.domain.com/hardware/604/view

(what you expect to happen goes here)

It should display a QR code on the right side of the page
-----

#### Actual Behavior

It shows a broken link

(what actually happens goes here)

This is an example of what the actual link to the graphic is http://invtracker.domain.com/hardware/604/invtracker.domain.com/hardware/604/qr_code
and it should be http://invtracker.domain.com/hardware/604/qr_code

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running **3.6.3 build 18** 
- What OS and web server you're running Snipe-IT on **ubuntu 16.04**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc. manual **manual**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **no errors just doesn't show image**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error 
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). **no**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. **Upgraded from 2.x**
- Indicate whether or not you've manually edited any data directly in the database **no manual database edits**

**Comment by dmeltzer** [comment]
What is your APP_URL set to in the `.env` file? Does it start with http://  ?

**Comment by 241indyimaging** [comment]
THANK YOU. I did not include the http:// That fixed it

**Comment by snipe** [comment]
Next time please close the issue if it's resolved.
