### ISSUE TITLE
Custom Asset Report Status not correct

### ISSUE THREAD

**Issue by therealjoshuad** [snipe/snipe-it#3129]
#### Expected Behavior (or desired behavior if a feature request)

When exporting a CSV from the Custom Asset Report page, I select **Asset Tag** and **Status** and export the report. The report should contain the correct Asset Tag and Status.

-----

#### Actual Behavior

When I export the report, the status shows **Ready to Deploy** for assets that are currently **deployed**. Archived assets **do** show the correct status.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running **3.6.2 Build 10**
- What OS and web server you're running Snipe-IT on **Ubuntu 16.04.1, Apache**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Install.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **/reports/custom**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). **yes, is reproduceable**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database **no**

**Comment by snipe** [comment]
This ins't really a bug, more of a side effect of how status labels work. https://snipe-it.readme.io/docs/overview#section-status-labels

**Comment by therealjoshuad** [comment]
Ah got it, so I guess the best way to see only deployed assets would be the **Assets** > **Deployed** from the navigation menu, that should work fine
