### ISSUE TITLE
LDAP Login Fails to Active Directory

### ISSUE THREAD

**Issue by paulhite** [snipe/snipe-it#3131]
#### Expected Behavior
LDAP successfully authenticates a synchronized user.

-----

#### Actual Behavior
User login fails with "Error: The username or password is incorrect."

-----

#### Details
In my case, the LDAP test and synchronization works just fine and the user account is imported with the correct username. I've confirmed that I'm using **sAMAccountName=** for the LDAP query. I've tried a few different accounts, appending UPN suffix or prepending domain on the login screen, confirmed I've got the PW correct, etc. We do use an alternate UPN suffix (ourdomain.com) on user logon names, but I've tried swapping a user to the primary (ourdomain.local) and also changing the Active Directory Domain in the settings to ourdomain.com. Debug log states **"Could not find user in LDAP directory"**, but it's definitely in there.

![image](https://cloud.githubusercontent.com/assets/24923639/21659265/8dcc3cce-d28f-11e6-9a0c-cefa0034204a.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: **v3.6.2 build 18**
- What OS and web server you're running Snipe-IT on: **CentOS/7.2.1511 Apache/2.4.6**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **install.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error:
![image](https://cloud.githubusercontent.com/assets/24923639/21659525/ce7e515c-d290-11e6-9924-19dfbdab6e94.png)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: **Login page**
- If a stacktrace is provided in the error, include that too. **N/A**
- Any errors that appear in your browser's error console.  **N/A**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).  **N/A**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs:
```
[2017-01-04 14:26:11] production.DEBUG: Binding user to LDAP.
[2017-01-04 14:26:11] production.DEBUG: LDAP user ***** not found in LDAP or could not bind
[2017-01-04 14:26:11] production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory
[2017-01-04 14:26:11] production.DEBUG: Authenticating user against database.
[2017-01-04 14:26:11] production.DEBUG: Local authentication failed.
```
- Include what you've done so far in the installation, and if you got any error messages along the way. 
__Set SElinux httpd_can_connect_ldap --> on__
**Changed LDAP Authentication query to __sAMAccountName=__**
- Indicate whether or not you've manually edited any data directly in the database **No**

**Comment by therealjoshuad** [comment]
What happens when you check the box that says "this is an Active Directory Server"?

**Comment by paulhite** [comment]
Oh lord. Don't laugh, but I saw that box, and my brain drew the conclusion that it literally meant "*this* server is an active directory server", as in the Snipe-IT server. Going to cry in the corner now.

**Comment by therealjoshuad** [comment]
:joy: We've all been there. Glad it worked!
