### ISSUE TITLE
CheckOut/Checkin User to input manually

### ISSUE THREAD

**Issue by h0ax123** [snipe/snipe-it#3133]
#### Expected Behavior (or desired behavior if a feature request)

I have successfully installed Snipe-IT version v3.6.2 on my server and everything is running smooth.   I was wondering that is it possible to add users manually just by typing in Check in/Check out field without creating users?  I just need to see where machine is going into.  No need to click on users.  

Another thing am wondering - how to change the name from asset tag to Machine name - or serial to service tag ...no need to change the field...only text

Please let me know.  Thank You

(what you expect to happen goes here)

-----

#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
 v3.6.2 build 18
- What OS and web server you're running Snipe-IT on
 windows
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
>  I was wondering that is it possible to add users manually just by typing in Check in/Check out field without creating users? I just need to see where machine is going into. No need to click on users.

We can try to add that in an upcoming release.

> how to change the name from asset tag to Machine name

That's not currently possible without editing the language files, and if you do that, your changes will likely be overwritten the next time you upgrade.

**Comment by h0ax123** [comment]
Thanks Snipe.  If you can please add this feature to check in and check out user manually by just writing their name then it would be great.   We will be using your source for asset management which will be managed by around 20 users who are handling 6000+ assets so making username for each employee in company is not what we need.   I am also exploring option for SSO login.   Is it possible to reach you directly for some support and little changes in the source and once our project go live we are definitely going to do some donation to your community for making this amazing tool.
