### ISSUE TITLE
Asset List view Shows Purchased date in EOL column

### ISSUE THREAD

**Issue by jarbro** [snipe/snipe-it#3135]
#### Expected Behavior (or desired behavior if a feature request)

In the list all assets view - the EOL column should represent EOL.  It is currently showing the Purchase Date

-----

#### Actual Behavior

EOL shows Purchase Date instead of EOL in asset list view.

-----

Tested on Snipe-It demo and can confirm it happens there.

Also happens on build 3.6.0 build 71 (gd49a1ea)

**Comment by snipe** [comment]
Can you reproduce this on the demo?

**Comment by jarbro** [comment]
Yes. Same thing happens in the demo as per initial ticket. 






On Thu, Jan 5, 2017 at 6:31 PM -0500, "snipe" <notifications@github.com> wrote:












Can you reproduce this on the demo?

**Comment by snipe** [comment]
I can't reproduce this on the demo. 

<img width="1314" alt="screen shot 2017-01-06 at 7 45 28 pm" src="https://cloud.githubusercontent.com/assets/197404/21739185/c7d0a8f0-d448-11e6-9672-9a61110bfd57.png">

<img width="1324" alt="screen shot 2017-01-06 at 7 47 05 pm" src="https://cloud.githubusercontent.com/assets/197404/21739190/f5b8cc48-d448-11e6-95e1-1a4db54743d2.png">

The dates are not the same, and they indicate the correct EOL based on the model-level warranty rules.
