### ISSUE TITLE
[Improvement] Consider using a "native font stack"

### ISSUE THREAD

**Issue by githubuserx** [snipe/snipe-it#3139]
In my opinion it would be nice if the interface would use a native font i.e. like "Segoe UI". I think it adds refreshing touch to the current look. Of course there are also other, more technical reasons besides the appearance. Also, many other websites and even GitHub use it as I just found out.

http://v4-alpha.getbootstrap.com/content/reboot/#native-font-stack

**Comment by snipe** [comment]
We're not using Bootstrap 4 (because it's not out yet). We'll evaluate further once BS4 is released.
