### ISSUE TITLE
cannot upload asset images

### ISSUE THREAD

**Issue by diwanicki** [snipe/snipe-it#314]
getting the following error attempting to upload images:

> ErrorException
>      Class 'Intervention\Image\ImageManagerStatic' not found

just did a git pull against commit 3184c3e03bc2d1c19e20dae73d0440a76c06c61f

are there guidelines for the image type and size?

I did have an issue with composer.lock but was finally able to stash the one on my end and the pull appeared to be successful.

**Comment by wvanhiele** [comment]
perhaps this might help someone else, we are running snipe on Windows IIS. When uploading images (models) we got an error message "Image Source not readable" form same intervention class.

From the error message i noticed it was uploading to c:\windows\temp\ dir on the server
I gave IUSR also write permission to this temp directory and directly started working. :+1: 
I didn't see this in the installation guide so this might save someone else some time
