### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by githubuserx** [snipe/snipe-it#3140]
#### Expected Behavior (or desired behavior if a feature request)

Correct translation

-----

#### Actual Behavior

The corrected translation somehow didn't make it into any of the current builds.
https://crowdin.com/translate/snipe-it/116/enus-de#1040

Actually didn't want to create a ticket for this, but since it seems that this was last changed two years ago it probably just got overlooked.. and as it is a quite frequently used interface element it starts to annoy ;)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
**latest**
- What OS and web server you're running Snipe-IT on
**PhotonOS**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
**Docker**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
**any page where you can create new items and the top navbar**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
**db was not modified**

**Comment by snipe** [comment]
These will be rolled into v4 at the end of the month.
