### ISSUE TITLE
Check in/out permissions

### ISSUE THREAD

**Issue by uprep** [snipe/snipe-it#3142]
#### Expected Behavior (or desired behavior if a feature request)

Want to be able to setup self checkout station for students so they can check out/in equipment. 

Need to be able to limit check in/out privilege to apply only to their user account (ldap). That way when they login they can check assets in or out and not be able to check in/out to anyone else or view what anyone else has checked out.
-----

#### Actual Behavior

Currently if a user has permission to check out/in an asset they can check that asset out/in to anyone. 

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.6.0-53-gb6ffb8b 
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual

- Indicate whether or not you've manually edited any data directly in the database
no

**Comment by snipe** [comment]
That feature is not currently available.

**Comment by hvucpacket** [comment]
I am interested in having this Check in/out permissions feature.  How can I reopen this request since I am new to the community.  Thank you.
