### ISSUE TITLE
Upgrade from 3.4 to 3.6 fails

### ISSUE THREAD

**Issue by ronmarion25** [snipe/snipe-it#3144]
#### Expected Behavior (or desired behavior if a feature request)
Trying to do an upgrade from 3.4 to 3.6 using
git pull

followed by recommended upgrade steps:
php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan migrate
php artisan config:clear
php artisan config:cache

-----

#### Actual Behavior
Did the git pull (had to stash local changes to app.php due to timezone change)
Ran first command in recommended upgrade steps:

php composer.phar install --no-dev --prefer-source

Error message says:
Could not open input file: composer.phar

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 3.4-14
- What OS and web server you're running Snipe-IT on CentOS 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error N/A
- If a stacktrace is provided in the error, include that too.  N/A
- Any errors that appear in your browser's error console.  N/A
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). N/A
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.  N/A
- Include what you've done so far in the installation, and if you got any error messages along the way.  Current installation works just fine...
- Indicate whether or not you've manually edited any data directly in the database No

**Comment by snipe** [comment]
If you installed composer globally, you should call it that way. Otherwise you'll need to dowoad and install composer again
