### ISSUE TITLE
[Bug Report] Creating new USER

### ISSUE THREAD

**Issue by immarkus** [snipe/snipe-it#3145]
#### Expected Behavior (or desired behavior if a feature request)

only the admin (or anyone with appropriate permission) able to add new accounts.

-----

#### Actual Behavior

when any user is checking out he can create new user (even if this option is blocked at the Permissions) by clicking checkout -> NEW

-----

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - 	v3.6.2 build 18 (g6f1e0d6)
- What OS and web server you're running Snipe-IT on- 7.0.8-0ubuntu0.16.04.3
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)- install.sh

**Comment by gregulator85** [comment]
I also have an issue with this behavior, because we do not want just any user creating new users.  Is there a way to disable the 'New' button upon checkout and only offer the drop-down?

**Comment by gregulator85** [comment]
@snipe got this merged in today, the patch is working as expected. Thank you.
