### ISSUE TITLE
[Feature Request] Many features request

### ISSUE THREAD

**Issue by immarkus** [snipe/snipe-it#3146]
Hello,

I'm trying to implement snipe-it at my business,  but I have some features that are necessary for me that are not exist.
My company is using many tools and I need to follow them. If hey are avilable/exist/broken/ and exedra...
My employees need to make a list of what they take with them so im trying to implement snipe-it instead of this paper work.
now here is a list of features I find necessary and do not exist in snipe it:
1.)Bulk checkout print (print a list of assets your are checking out by a click after checkout)
2.)Option to Checkout assets only to user that is logged in. (I don't want that anyone will be able to checkout and checkin for another person. except for the admin).
3.)Bulk checkin assets option ( and again checkin only for the current logged in user only)
4.)Landing Page- I want that anyone who is logging in to snipe it will ve directed to All assets as first        page instead of Dashboard)  
5.) Adding components to assets- i tryed to add some components to an assets but I wasnt able to do it  when u click on asset->components You don't have a option to add components. In addition there needs to be a "cheklist" to check if all the components in the assets are exist. for example if i have a pen pencil and a pair of scissors I need to be able to easily check and sign the components, and make the task of  checking that everything exist in the asset easier). In addition it needs to be logged when the check was.
6.)add an option to check out/check in with qr code/Barcode- it will be nice to just enter to a window where you scan all the barcodes of the assets(you've plrinted on the asset) You checkout/checkin.
7.)An option to delete photo-if you add a photograph to the asset you cant remove it, you can do it just by remove the asset and add it back with no photograph or upload new one.
8.)An option to simple editing the photograph (rotate/crop).
9.)The ability to add/remove fields all over snipe it- for example if I don't to use the "model" or "status" fields but i have to enforce my employees to use the "supplier" and "purchase cost" fields when they are ceating a new asset.
10.)Use another formats for the "custom asset report" file.
11.)Receiving emails about parameters u chose for example: if someone checked out/checked in/edited assets/all the assets/components has been checked in (returned).

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----

**Comment by snipe** [comment]
Please create separate issues for these things. This isn't a tenable request.
