### ISSUE TITLE
[Feature Request] Edit asset Forced Fields

### ISSUE THREAD

**Issue by immarkus** [snipe/snipe-it#3154]
#### Expected Behavior (or desired behavior if a feature request)

The ability to add/remove fields all over snipe it- for example if I don't use the "model" or "status" fields but i have to enforce my employees to use the "supplier" and "purchase cost" fields when they are ceating a new asset.

-----

#### Actual Behavior

when I create a new asset im forced to enter "Asset tag" "model" and "Status".
Even if I don't Really need the Status and Model fields.

-

**Comment by snipe** [comment]
That's part of the business logic behind Snipe-IT. It's unlikely we would change that any time soon.
