### ISSUE TITLE
[Feature Request] Another formats for the "custom asset report" file

### ISSUE THREAD

**Issue by immarkus** [snipe/snipe-it#3155]
#### Expected Behavior (or desired behavior if a feature request)

Use another formats for the "custom asset report" file for example .xlsx
so everyone with excel will be able to open this file.
-----

#### Actual Behavior
I can download only .csv file, but if i dont have any tools to open .csv file I cant see the content.

-----

**Comment by snipe** [comment]
Excel can open CSV files
