### ISSUE TITLE
C128 barcode cannot be read?

### ISSUE THREAD

**Issue by denihanca** [snipe/snipe-it#3157]
#### Expected Behavior (or desired behavior if a feature request)

SNIPE IT generates a QR code of item's URL and a C128 barcode of the asset's ID. An external barcode scanner will then be able to read the data.

-----

#### Actual Behavior

QR code generated and read successfully. C128 barcode was generated, but cannot be read by external barcode scanner.

-----

#### Please confirm you have done the following before posting your bug report:

- [v] I have enabled debug mode
- [v] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.6.2 build 10 (g927a12f) 
- What OS and web server you're running Snipe-IT on: Windows, Apache on XAMPP
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: no error message was trigerred
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: related barcode generation functions, tecnickcom\tc-lib-barcode
- If a stacktrace is provided in the error, include that too: no error
- Any errors that appear in your browser's error console: no error
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): yes confirmed. Try creating new asset and then generating label with setting alt barcode type (1D barcode type) = C128
- Include any additional information you can find in `app/storage/logs` and your webserver's logs: no error
- Include what you've done so far in the installation, and if you got any error messages along the way: no error
- Indicate whether or not you've manually edited any data directly in the database: nothing directly related to barcode generation functions

This here is the barcode generated through the snipe-it demo site. I cannot get a read out of it from my barcode scanner. Can anyone confirm?
![2](https://cloud.githubusercontent.com/assets/10398900/21761494/ee5694a0-d685-11e6-9708-0d76b3368b03.PNG)
)

**Comment by lorenzolewis** [comment]
It seemed to just work perfectly fine for me. I just used my phone's camera and an app to scan both. The 1D went to https://demo.snipeitapp.com/hardware/101/view and the 2D also went to https://demo.snipeitapp.com/hardware/101/view.

**Comment by lorenzolewis** [comment]
Just tried the 1D barcode on my v3.6.2 build 10 (g927a12f) installation (hosted) and it doesn't seem to be working either.
This is the barcode that I tried:
<img width="628" alt="barcode" src="https://cloud.githubusercontent.com/assets/15347255/22937438/3b872454-f29e-11e6-8c28-4226bb04f71c.png">

**Comment by UTAS1** [comment]
We have to use a painful workaround using Excel and a Word mail merge to generate barcodes that work as none of our scanners will read the Snipe generated label. 

![image](https://cloud.githubusercontent.com/assets/26127466/23488043/3ced75b2-ff3e-11e6-9018-bd5550c5a17d.png)
 
Other parts of the university are also interested in hosted Snipe but this issue would be a killer if it can't be resolved.

**Comment by GeorgeBarkley** [comment]
Had the same problem.  It seems to be a scaling issue.  Solution mentioned by Bret Fagerlund in [https://github.com/snipe/snipe-it/issues/3425](https://github.com/snipe/snipe-it/issues/3425) takes care of the problem for me.
