### ISSUE TITLE
Import from Linux to Windows - images lost

### ISSUE THREAD

**Issue by jmathias59** [snipe/snipe-it#3158]
#### Expected Behavior (or desired behavior if a feature request)

Copied public/uploads/models from Ubintu linux to Windows.  Ran artisan config:clear and cache.
I assume images would be available but are not.  Same behavior with logo.

Deleted and uploaded image to an asset model and no image. Same with logo

-----

#### Actual Behavior

IIS 10.0 error
Requested URL	   http://localhost:80/uploads/models/2Ik2WjrsDyQwDoeRxFkr2j0YV.png
Physical Path	   C:\inetpub\wwwroot\uploads\models\2Ik2WjrsDyQwDoeRxFkr2j0YV.png

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 3.6.2
- What OS and web server you're running Snipe-IT on Windows WAMP

**Comment by snipe** [comment]
I'm not really sure what to tell you here. Either the images are in that directory or they're not. There's nothing in the process of upgrading that would move them or delete them.

**Comment by jmathias59** [comment]
This is not an upgrade but rather a hardware move. I did a sql backup of the linux server (3.6.2), install 3.6.2 on Windows (WAMP server), restored the backup.

If I am moving the snipe-it database/web structure from one server (Linux) to another (Windows), other than importing the database, are there other directories that need to be moved?  Is there documentation?  If not, if I figure it out with your help, I can provide the documentation.

James

**Comment by snipe** [comment]
The only things you should have to move are the public/uploads directory and storage/private_uploads

**Comment by jmathias59** [comment]
I only moved the models folder. I will try moving  the directories mention

James

Get Outlook for iOS<https://aka.ms/o0ukef>

_____________________________

**Comment by jmathias59** [comment]
Moving both directories solved the problem.

Do you want a document providing step by step directions for migrating SnipeIT from Linux to Windows?

James

**Comment by snipe** [comment]
I don't ever want anyone to move anything from Linux to Windows. :)

**Comment by jmathias59** [comment]
I understand ;)
