### ISSUE TITLE
[Feature Request] Non Assets | More robust system

### ISSUE THREAD

**Issue by delinski111** [snipe/snipe-it#3159]
Sorry for crappy title, couldn't think of anything better.

Pertaining to the accessories, consumables, components sections.

Currently, I can set an item to have a min quantity. This is fine, but if the price, vendor and/or PO# changes, I am required to either remove and update the fields for the last item to match the new purchase (removing the old info from history) or create a new record entirely, set the old record to min 0, and set the new record to the actual min.

The feature request, is that these sections have a new workflow built to be similar to how the "Asset Maintenance" is.

Example.

Make a single record;

`Company - XX`
`Consumable Name - 62XL Tri-Color High Yield`
`Category - Ink`
`(default) Location - XX` _-- (added word default for constancy with other pages)_
`Quantity - 12`
`Min Quantity - 10`
`Notes - For HP 7640 Printers` _--(not a real field, but should be for this type of system if you like this idea)_

Than within the record you have more options.
obviously, keep the check-in and check-out stuff.
Add a new button or tab; called something to the effect of "add order". In that page have the rest of the field that I left out above:

`Manufacturer - HP`
`Supplier - Newegg`
`Model No. - 62XL Tri-Color High Yield`
`Order Number - 0001`
`Purchase Date - 01/01/1970`
`Purchase Cost - 67.99`
`Quantity - 5` _--(adding this number would auto-update the main quantity value?)_

This will be made as a part of the original record (similar to how you handle asset maintenance).

Than you can have another tab called history, or past transactions or something.

Doing it this way, will mean you can have one record to track the quantities, but have a history for all the purchases of that product. This would improve the usability of the database, and could help keep better track of spending for audits.

The only thing I cannot work out, is how you be able to generate a report of all this data should you need it. You could export it per record, but say you needed to get a report for all consumable spending in 2016. It would not be ideal to export each record independently than manually work with all those files.

**Comment by VanillaNinjaD** [comment]
I think there are some other very similar feature requests that already exist. I know my company and some others are extremely interested in this feature as well.

**Comment by Braintelligence** [comment]
I've read some issues that are close or even duplicates of this and I really hope that better non-asset management hits SnipeIT soon 😸 
I don't even know how to take back a test-checkout of a consumable I did ^^.

**Comment by osa-ko** [comment]
This is so much needed feature. It is especially critical for accessories as we would check out and check in some of them back an forth and it is critical to keep to total number available at one place. Accessories stocks are refilled all the time and it is so cumbersome to have separate buckets or rewrite the history every time.
