### ISSUE TITLE
Adding new custom fieldsets to people/users and run asset report with it.

### ISSUE THREAD

**Issue by EMELZ3** [snipe/snipe-it#3161]
#### Feature Request I think

I'm wondering if there's a way to create a custom user field (users hire date) that can then be cross-referenced with the existing assets they have checked out.  Basically wanted to find a way to generate a custom report or search list that will list out employees eligible for laptop upgrades if they've been with the company for x years/ and or their warranty has expired on the asset., etc.

-----

#### Actual Behavior

I wasn't able to find a way to create a custom field in users, like adding each employee's hire date.  

-----

#### Please confirm you have done the following before posting your bug report:
Went thru admin--> custom fields--->and created a new field call hire date.  
Then went to field sets and created a new fieldset that required hire date custom field. and added hire date field.  But unable to add this custom field to people, user or groups.  Only able to add this to the asset models.

The only other way i can think of doing this is to add custom field of the employee hire date to all laptop asset models and require it to be updated everytime i switch the ownership of the user but this seems it can get messy over time.  

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 2.1.1
- What OS and web server you're running Snipe-IT on CentOS 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
That's not currently possible, but it's on the roadmap.

**Comment by snipe** [comment]
Duplicate of #4261

**Comment by Omidoshegy** [comment]
+1

**Comment by Hypl3x** [comment]
+1

**Comment by sivar89** [comment]
+1

**Comment by UtecoABee** [comment]
It has ben a while since this was requested. I still can't today add custome fields anywhere besides to assets. Anything I have missed?

**Comment by snipe** [comment]
@UtecoABee That is correct. For updates, please follow the original issue. [#4261](https://github.com/snipe/snipe-it/issues/4261)

**Comment by chriscul** [comment]
i would like this too. and also , i have another question. In the custom fields, can it be fixed that you can use a checkbox in combo with a textbox or even assign an asset.
example : 
let's say i have a switch with 24 ports and 4 sfp ports
i want to have this in snipe-it but also i want to add what is connected to which port, example : port1 printer A

running  Version v7.1.15 of snipe-it
