### ISSUE TITLE
Requestable section not working

### ISSUE THREAD

**Issue by siekee** [snipe/snipe-it#3162]
I configure a couple of items as requestable, but when i go to requestable menu and click the button request, it bring me to an error page showing "Whoops, looks like something went wrong." 

- Version of Snipe-IT you're running v3.6.2 build 10 (g927a12f)
- What OS and web server you're running Snipe-IT on centOS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh

**Comment by snipe** [comment]
Please enable debugging so we can get a more useful error message.

**Comment by siekee** [comment]
Thanks for replying. 
Not sure if i did enable it correctly. I do still getting "Whoops, looks like something went wrong." without further error after i enable it

![screen shot 2017-01-10 at 4 14 53 pm](https://cloud.githubusercontent.com/assets/24662033/21798558/11d0fe1e-d750-11e6-9d11-20a10529417a.png)

**Comment by snipe** [comment]
If you're running this on Centos via install.sh, why are you editing the docker.env?

**Comment by siekee** [comment]
Thanks for the respond. Sorry for my bad understanding, i do not get what you are trying to say, can you elaborate further?

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/getting-help#section-step-1-enable-debug-mode

According to your screenshot, you're editing the docker.env file, but according to your bug report, you installed via install.sh, which doesn't use docker, changing that file would have no effect.

**Comment by siekee** [comment]
Thank you for spending time explaining to me. These are the log that i get the log from laravel.log. Is that correct?

![screen shot 2017-01-10 at 6 07 18 pm](https://cloud.githubusercontent.com/assets/24662033/21802257/dbdab6c8-d75f-11e6-9d4b-1e296f2a0162.png)

**Comment by snipe** [comment]
Looks like something is wrong with your email settings.

**Comment by siekee** [comment]
Thank you for your help. It is working now

**Comment by snipe** [comment]
>
