### ISSUE TITLE
Filter assets based on cell values

### ISSUE THREAD

**Issue by deadpoint** [snipe/snipe-it#3163]
#### Expected Behavior (or desired behavior if a feature request)
When viewing the inventory it would be ideal to be able to filter based on the data of each column, which would allow you to quickly filter what is the available Stock of X item(s) at a given location(s). Because columns can only be sorted in ascending/descending order, on a single column, one needs to export the data to CSV/Excel in order to filter the data in such a manner which is less than ideal, or query to database directly (even worse).

I would exclude certain any column which has unique values from the filter, e.g serial number, asset tag, etc, or perhaps make the the values to filter on configurable since every installation is different.

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
I'm pretty sure there is already an open request for this.

**Comment by deadpoint** [comment]
Hmm, I search the open requests but didn't see anything. If it's a dup link and close the request ;-)

**Comment by SotoDucani** [comment]
Erm, #1256 #1728 and #2888? Pretty much all the same if I'm not mistaken.
