### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by rukshrulz** [snipe/snipe-it#3164]
I need someone's step-by-step assistance for installing Snipe-IT on a Go-Daddy web server.

**Comment by snipe** [comment]
There's not really anything different about GoDaddy (although they tend to have older versions of software, so you'll want to check the requirements). Just [set up the subdomain](https://za.godaddy.com/help/manage-your-hosting-account-subdomains-4652) and then follow the [normal Snipe-IT installation instructions](https://snipe-it.readme.io/docs/installation).
