### ISSUE TITLE
artisan snipeit:backup failed with mysql as socket

### ISSUE THREAD

**Issue by noizo** [snipe/snipe-it#3165]
SnipeIT 3.6.3
MySQL is running on socket
`DB_SOCKET='/cloudsql/gcloud-project:us-central:data'`
OS Ubuntu 16.04

When i run

```
/var/www/html$ sudo php artisan snipeit:backup
Starting backup...
Dumping database snipeit...
Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Got error: 2002: Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2) when trying to connect
.
Backup completed!
```

**Comment by snipe** [comment]
I'm honestly not sure what to tell you here. According to the backup library, that issue was already fixed.
https://github.com/spatie/laravel-backup/pull/25/files

**Comment by noizo** [comment]
Socket path is hardcoded, and not taken from snipeitapp .env file in this case.
Thats an issue i think.
