### ISSUE TITLE
Importing users from csv file not working correctly

### ISSUE THREAD

**Issue by ado120** [snipe/snipe-it#3166]
#### Expected Behavior (or desired behavior if a feature request)

I am trying to import a csv file with two test users to see if they will import successfully into Snipe-IT.

-----

#### Actual Behavior

The system gives me a "Success!" prompt in green, but the users in the csv are not added.

I am running the docker without a mounted file-system as indicated in the instructions..could this be why?

#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: Latest Docker release pull of SnipeIT
- What OS and web server you're running Snipe-IT on: CentOS Linux release 7.2.1511
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Docker running with no
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): It also does not work in the demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

After seeing that it does not import successfully in the demo, most likely something wrong with my csv file.. Can someone let me know what's wrong with it?

http://imgur.com/a/joI72

**Comment by snipe** [comment]
First off, you need column headers, per the import documentation. It definitely won't work without those. https://snipe-it.readme.io/docs/importing

**Comment by ado120** [comment]
Works now, muchos gracias :)

**Comment by snipe** [comment]
![83710-it-crowd-excited-clapping-appl-io5u](https://cloud.githubusercontent.com/assets/197404/21830766/e68ff2f6-d753-11e6-9d10-f73f7c966f06.gif)

**Comment by BlueNoob** [comment]
> * 
> * Indicate whether or not you've manually edited any data directly in the database

**Comment by BlueNoob** [comment]
> First off, you need column headers, per the import documentation. It definitely won't work without those. https://snipe-it.readme.io/docs/importing

https://snipeitapp.com/assets/downloads/sample-users.csv
I can not import users via using your sample-users.csv

The following Errors were encountered.
Error: Item:  failed validation: {"Asset \"\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/importing">Importing Assets and More</a></strong></div><div>There is a Web GUI importer available in the Import section that will allow you to upload and process and import a comma-delimited CSV through the web interface. The importer may choke on larger imports, so if you have more than several hundred records to import, you may wish to use the command-line...</div></blockquote>
<blockquote></blockquote>

**Comment by BlueNoob** [comment]
> > First off, you need column headers, per the import documentation. It definitely won't work without those. https://snipe-it.readme.io/docs/importing
> 
> https://snipeitapp.com/assets/downloads/sample-users.csv I can not import users via using your sample-users.csv
> 
> The following Errors were encountered. Error: Item: failed validation: {"Asset """:{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
> 
> > <img alt="" width="48" src="/favicon.ico">Snipe-IT Documentation**[Importing Assets and More](https://snipe-it.readme.io/docs/importing)**There is a Web GUI importer available in the Import section that will allow you to upload and process and import a comma-delimited CSV through the web interface. The importer may choke on larger imports, so if you have more than several hundred records to import, you may wish to use the command-line...

@snipe I fixed just now, "proc_open not installed" caused by this, but "proc_open," is not checked when processing the environment checking of installaton.

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/importing">Importing Assets and More</a></strong></div><div>There is a Web GUI importer available in the Import section that will allow you to upload and process and import a comma-delimited CSV through the web interface. The importer may choke on larger imports, so if you have more than several hundred records to import, you may wish to use the command-line...</div></blockquote>
<blockquote></blockquote>
