### ISSUE TITLE
REQUEST button in REQUESTABLE items doesn't change back after successful loan

### ISSUE THREAD

**Issue by ZechClar** [snipe/snipe-it#3169]
#### Expected Behavior (or desired behavior if a feature request)

items checked out should be removed from requestable items page after assigning it to a user.

-----

#### Actual Behavior

User clicked on request button to request an item in requestable item page
![1](https://cloud.githubusercontent.com/assets/20469279/21839391/7b0606e6-d812-11e6-8e99-be88928b45e4.JPG)
Admin finds a request notification in the dashboard and checks out the item to the requestor
![2](https://cloud.githubusercontent.com/assets/20469279/21839402/9355a9e0-d812-11e6-9a54-e565662f2632.JPG)
tried to login to the users account and found that the item requested is still there
![1](https://cloud.githubusercontent.com/assets/20469279/21839417/a4d2d152-d812-11e6-8b9c-aa7ce6cdc815.JPG)
I am able to cancel it and click request again. The item requested should disappear from the requestable items page once admin checks out the item to the requestor and should only be viewable again once item has been returned and admin changes back the status to "ready to deploy"

-----

#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode
- [yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - 3.6.2 Build 10
- What OS and web server you're running Snipe-IT on 
         Windows Server 2012 R2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) 
         Xampp
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error 
         no error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
That's not really a bug, it's just kinda how it works. The idea being that even if an asset is checked out to someone, another user can still request it, they'll just have to wait until the asset is checked back in.

**Comment by ZechClar** [comment]
I see. thanks for replying back fast Snipe. Appreciate it.

**Comment by ZechClar** [comment]
Hi Snipe,

Just needed to follow up coz I think it is something that needs to be checked. Here's the scenario. 

USER1 logs in and clicks on the request button to request the item
    - REQUEST button changes to CANCEL button
![1](https://cloud.githubusercontent.com/assets/20469279/21916456/c67f0c16-d97b-11e6-9e12-d79332f41842.JPG)
Admin receives an email notification about the request
Admin logs in and assigns the item to USER1
USER2 logs in and wanted to request the same item (this is what i understood in your reply. That other users can still request it in requestable items but will just have to wait when items have been returned)
![2](https://cloud.githubusercontent.com/assets/20469279/21916504/11bc16ec-d97c-11e6-8603-aa8badd4e090.JPG)
USER1 receives the item and returns it after a few days
Admin changed the status back to Ready for Deploy after user 1 returned it.
USER1 logs in to snipe IT again and decided to loan the item again but finds that the REQUEST button still shows CANCEL. The button did not change to REQUEST button after USER1 returned the item
![1](https://cloud.githubusercontent.com/assets/20469279/21916592/aa8a2daa-d97c-11e6-91b3-fffa41c91d2c.JPG)
USER2 logs can request it this time since the items shows that it can now be requested.
![3](https://cloud.githubusercontent.com/assets/20469279/21916684/2906abc2-d97d-11e6-8f73-742d8d933dc2.JPG)
USER1 can only request it back if USER1 clicks on the CANCEL button (making the button change to REQUEST button again). This will send a notification email saying that the request has been cancelled even though the item back then was loaned and returned back successfully.
This is the part where it becomes confusing to USER1 because the button never changes after a successful loan out.

**Comment by ZechClar** [comment]
Hi,

Just wanted to ask if you were able to check this out?

**Comment by snipe** [comment]
If we had, we'd have posted a comment to this thread.

**Comment by NaveenQLI** [comment]
Hi Snipe,

I also face the same issue what was reported earlier by ZechClar. Request you to help us resolving the issue.

Thanks

**Comment by froid-san** [comment]
I know this is an old tread but I'm also having the same issue. The Documentation does not mention or explain clearly how this process should go and why other user can still request a deployed asset  an the one requested can still cancel it even if it is deployed to them and accepted the asset via email verification.
