### ISSUE TITLE
The installation directory "/var/www/html/snipe-it" is not writable

### ISSUE THREAD

**Issue by Oreios** [snipe/snipe-it#3170]
#### Expected Behavior (or desired behavior if a feature request)
I've had a couple of issues but with following the provided documentation and looking up missing stuff from existing issues & google. I now got to this point where I'm stuck.

Correctly get composed installed when running 
`curl -sS https://getcomposer.org/installer | php`

-----

#### Actual Behavior
Get an error
`All settings correct for using Composer
The installation directory "/var/www/html/snipe-it" is not writable`

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running (v3.6.3)
- What OS and web server you're running Snipe-IT on (Ubuntu 16.04 & Apache2)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) (copy git)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error (Whoops, looks like something went wrong. (this is what I get now after fixing documentroot in the default virtualhost config))
- If a stacktrace is provided in the error, include that too. (I don't know what this means)
- Any errors that appear in your browser's error console.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.

1.  I followed the documentation fully and am finally arrived at the install dependencies part.
2. I've given my user www-data (apache user) the permissions as told in the previous page.

- Indicate whether or not you've manually edited any data directly in the database (No)

**Comment by snipe** [comment]
That's a permissions issue, not a Snipe-IT issue. The user you're trying to execute the cURL command as does not have permission to write to the directory you're trying to install it in. Either add your current user to whatever group your directory is owned by, or correct the permissions.
