### ISSUE TITLE
[Feature Request] Check for disable state in LDAP

### ISSUE THREAD

**Issue by delize** [snipe/snipe-it#3173]
#### Expected Behavior (or desired behavior if a feature request)
Disable a user in AD/LDAP 
Import/Sync LDAP
Set Active flag to No in snipeit user list

-----

#### Actual Behavior

Disable a user in AD/LDAP
Import/Sync LDAP
Active Flag is set to Yes (no change)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
3.6.2

- What OS and web server you're running Snipe-IT on
Ubuntu 16.04.1 LTS Apache2

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
https://domain.net/admin/users

- If a stacktrace is provided in the error, include that too.
N/A

- Any errors that appear in your browser's error console.
N/A

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
Unable to do so

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

- Include what you've done so far in the installation, and if you got any error messages along the way.
No error message

- Indicate whether or not you've manually edited any data directly in the database
No
-----

As far as I can tell, this is intended behavior - but would like to submit a feature request for that when a user is disabled in LDAP/AD the state of their account is checked and also subsequently disabled as well.

In theory, I suppose if they are disabled in AD/LDAP and they attempt to login in SnipeIT, they would have access denied, but better to be on the safe side and just disable their account outright.

**Comment by korio77** [comment]
This would be very time saving if just with one click you can have the user disabled and all their assets changed to ready to deploy for example.

Or maybe add some kind of "fast accept" window in the dashboard (like the flag for alerts) where you can  confirm the return of an item from a disabled in ldap user with just one click without the need to search for the user or the item itself.

**Comment by ernestasen** [comment]
+1 for this

**Comment by delize** [comment]
Please remove the stale label, this is an active suggestion.

**Comment by snipe** [comment]
@delize [that code already exists](https://github.com/snipe/snipe-it/blob/master/app/Console/Commands/LdapSync.php#L159) (and this ticket was for 3.6.2, we’re at 4.1.10 now). Is it sill mot working for you?

**Comment by delize** [comment]
It wasn't working in 3.6.2, and I am currently trying to deploy the latest version via docker but have been running into a problem where I will open a PR to fix the issue. 

Let me get back to you on it.

**Comment by MobileNerf** [comment]
This doesn't seem to work for me either. I'm on Version v4.0.15. When I perform an LDAP sync, the users that we're disabled in AD are not being marked as Disabled in Snipe. Is there a specific setting that needs to be checked?

**Comment by delize** [comment]
This is working for me now in 4.1.10, though I was expecting a different result I guess. Though I believe I understand the reasoning for what is occuring. 

If a user is deactivated, I would expect them to not show up under the checkout user field. Since they are now marked as deactivated - there is not any reason for them to appear there to assign new assets too.
