### ISSUE TITLE
Upgrade v1.2.7 to 3.6.x

### ISSUE THREAD

**Issue by PulseSJ** [snipe/snipe-it#3174]
Hi,

I just started my new position, and have become responsible for Snip-IT.  I noticed that we are currently running version 1.2.7beta.  Is there any viable upgrade path to the current version, without destroying any of our existing data?

Thank you.

Murias

**Comment by snipe** [comment]
You should be able to use the directions here and it should work: https://snipe-it.readme.io/docs/upgrading-to-v3

There is no reason that you should lose any data, but I obviously recommend you run a backup first.
