### ISSUE TITLE
Enable Debugging Mode not working?

### ISSUE THREAD

**Issue by ado120** [snipe/snipe-it#3175]
#### Expected Behavior (or desired behavior if a feature request)

On a "Whoops, looks like something went wrong!" page after turning on debug mode in the my_env_file should show an error output

-----

#### Actual Behavior

After changing the my_env_file value of APP_DEBUG to true, still getting a Whoops, looks like something went wrong on the page.

After doing this I stopped and started the docker, also restarted the container.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode: yes
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: Latest docker pull
- What OS and web server you're running Snipe-IT on: CentOS 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: don't see an error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/common-issues#section-changes-to-my-env-file-dont-seem-to-be-updating

**Comment by ado120** [comment]
Hello Snipe,

Appreciate the documentation. I actually went ahead and restarted Apache as well as the docker container for snipeit.

More context on the issue, I am trying to see exactly why LDAP sync isn't working.. After setting the debug mode to true, restarting apache and the docker container.. I'm still getting a "Whoops, something went wrong." error after hitting the Synchronize button of the LDAP sync.

**Comment by snipe** [comment]
Latest docker pull of what branch? Check the config/version.php file and tell me what specifc version you're running.

**Comment by ado120** [comment]
return array (
  'app_version' => 'v3.6.2',
  'build_version' => '18',

**Comment by snipe** [comment]
I'm not sure why debugging isn't working for you, but you should be able to tail the error log at storage/logs/laravel.log and get the same info.

**Comment by ado120** [comment]
I went ahead and recreated the error in snipe, but a laravel.log file
doesnt exist in that directory, in fact it's empty. Any ideas?

**Comment by ado120** [comment]
I could recreate the issue, except this time with the actual problem I'm
trying to fix which is LDAP sync if that is easier for you snipe

**Comment by snipe** [comment]
Check the permissions on your storage directory. It needs to ne writable by the server. If there is no logs/laravel.log, it cannot write to that directory.

**Comment by ado120** [comment]
Did a 766 on the storage directory, restarted apache, stop and started the
docker container, and re-ran the ldap sync.. still getting a "Whoops,
something went wrong page" with no laravel.log file in the logs folder..

My Debug mode is set to true in the env file, but the app_env is still set
to production, do I need to change that to anything?

**Comment by ado120** [comment]
Hello Snipe,

Can we change this issue back to open for better visibility? Maybe I'm missing something obvious :(

**Comment by ado120** [comment]
Hello Snipe,

I got it working by removing the container all together and
re-downloading/re-running it..

A docker stop and then start did not work. Just a fyi!

-Alex
