### ISSUE TITLE
Software Licenses (No matching records found) & Licenses report (error)

### ISSUE THREAD

**Issue by Oreios** [snipe/snipe-it#3180]
#### Expected Behavior (or desired behavior if a feature request)

To see my added licenses listed in the license view.
Create a license report.

-----

#### Actual Behavior

I don't see any and get (No matching records found). 
Receive error (whoops looks like something went wrong.

Picture 1
![snipeit assets license page](https://cloud.githubusercontent.com/assets/17301577/21882093/41245d8c-d8a9-11e6-9ffc-a3a2e9b36dbb.png)
Picture 2
![snipeit asset activity](https://cloud.githubusercontent.com/assets/17301577/21882094/4124e658-d8a9-11e6-8d2e-2e9eb351b4be.png)

I can see and interact with the licenses trough the recent activity. (even check-out)
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 
v3.6.3.
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Git copy
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
`2/2 ErrorException in 5265c9fda04c0b3eb2097e80f993e7f4e5bc2056.php line 46:
Call to undefined function mb_strimwidth() (View: /var/www/html/snipe-it/resources/views/reports/licenses.blade.php)`
`1/2 FatalThrowableError in 5265c9fda04c0b3eb2097e80f993e7f4e5bc2056.php line 46:
Call to undefined function mb_strimwidth()`
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Licenses view (no interaction yet)
License Report
- If a stacktrace is provided in the error, include that too.
n/a
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
Not reproducable
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
I see the same error exception as the debug mode
- Include what you've done so far in the installation, and if you got any error messages along the way.
GD or imagick were installed but didn't recognize.
The .env file warning didn't validate but when checked the .env was hidden.
- Indicate whether or not you've manually edited any data directly in the database
no

**Comment by snipe** [comment]
http://php.net/manual/en/mbstring.installation.php - You need to either enable or install the mbstring PHP extension to use that function.
