### ISSUE TITLE
Missing field for slack_botname in settings screen

### ISSUE THREAD

**Issue by morph027** [snipe/snipe-it#3181]
#### Expected Behavior (or desired behavior if a feature request)

See a field for the setting ```slack_botname```

-----

#### Actual Behavior

No visible field

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: ```v3.6.3 build 15 (g1bf34d7)```
- What OS and web server you're running Snipe-IT on: Ubuntu 16.04, Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): ```install.sh```
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): It is ;)

![snipe-slack](https://cloud.githubusercontent.com/assets/600106/21884167/739c3ccc-d8b2-11e6-8a37-cbb80f559b90.png)

**Comment by snipe** [comment]
Yeah, you can just set that in your Slack integration settings now. 

<img width="582" alt="screen shot 2017-01-12 at 7 24 07 am" src="https://cloud.githubusercontent.com/assets/197404/21895607/30ab2cbc-d898-11e6-8a42-a7620b124b57.png">

**Comment by morph027** [comment]
Thank you!

**Comment by snipe** [comment]
![4110401-0707616809-tumbl](https://cloud.githubusercontent.com/assets/197404/21896717/2eb0fc30-d89c-11e6-849d-c73f92fe37bf.gif)
