### ISSUE TITLE
How do we create and print labels / How do we use AD login ?

### ISSUE THREAD

**Issue by kms31786** [snipe/snipe-it#3185]
Hey hi,

My System Information

Snipe-IT version	v3.6.3 build 15 (g1bf34d7)
PHP Version	5.6.29
Laravel Version	5.2.45
OS : Centos 7.1
Database : Maria DB

We linked our AD using LDAP Integration and its passed on Test Ldap, now we are unable to pull the user's information and unable to login using AD credentials.

Thanks

**Comment by abaalkh** [comment]
What information do you get when syncing users? 
Please provide a screenshot as i have stumbled on a similar issue.
![image](https://cloud.githubusercontent.com/assets/2372747/21960835/6bc7791e-db08-11e6-9cc7-d594b30ab477.png)
![image](https://cloud.githubusercontent.com/assets/2372747/21960836/7a1c3216-db08-11e6-8d50-92a0136cc004.png)


What do you get after you synced?

**Comment by kms31786** [comment]
Hello abaalkh,

Thanks for your quicker response and support.

 When i initiated LDAP Sync  it will show **Success: LDAP Import successful.** there is no issue with config and syncing, only thing is im unable to login with LDAP credentials and unable to assign any asset to ldap user where im able to login and assign asset to local database user.
![image](https://cloud.githubusercontent.com/assets/25099412/21972040/91956ac8-dbdc-11e6-8e34-48927f51dc27.png)


May be im not following proper process are missing some thing as im very new to this application.

 Thanks,
Mohiddin.

**Comment by Guenny0488** [comment]
Do you see the people you imported via LDAP in Peoples Area (Current Users)  of Snip-it?

Is the LDAP Password Sync Function checked in the LDAP Settings?

![ldap-snipe-it](https://cloud.githubusercontent.com/assets/18172313/22055211/5932bd82-dd5a-11e6-827c-6efa7e04f0ae.PNG)
