### ISSUE TITLE
Migrate from Windows to CentOS 7

### ISSUE THREAD

**Issue by Dan458** [snipe/snipe-it#3186]
Has anyone migrated from a Windows Installation to a CentOS 7 installation, that could provide me a guide of how I can export the database data and import it CentOS side?

Thanks
Dan

**Comment by abaalkh** [comment]
You can use the Snipe-IT 'backup' feature located in the 'Admin' drop down.

**Comment by Dan458** [comment]
Thanks. Actually I hadn't ran - 

php composer.phar dump-autoload
php artisan migrate
php artisan view:clear

After running this the applications started to work again :)
