### ISSUE TITLE
Unable to login via HTTPS

### ISSUE THREAD

**Issue by Shadow00Caster** [snipe/snipe-it#3188]
#### Expected Behavior (or desired behavior if a feature request)

I expect to be logged in

-----

#### Actual Behavior

I get redirected to login page

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
++ v3.6.3 build 15 (g1bf34d7) 

- What OS and web server you're running Snipe-IT on
++ Debian 7.11 (wheezy) 64bit, Apache 2

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
++ Fresh git checkout, upgrade to 3.0 from 2.11 in new directory

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
++ No error messages or logs

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
++ Login, login button

- If a stacktrace is provided in the error, include that too.
++ N/A

- Any errors that appear in your browser's error console.
++ Warnings for page trying to load elements over non-secure

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
++ Not reproducable

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
++ N/A

- Include what you've done so far in the installation, and if you got any error messages along the way.
++ I am able to login by not going through HTTPS sucessfull

- Indicate whether or not you've manually edited any data directly in the database
++ No

#### Notes
HTTPS is forced through load balancer, which also supplies cert, through a fron-end.  URL in .env is set to https://myurl.  When accessing https://myurl and attempting to login, I simply get re-directed to the login page.  If I bypass the LB and access the site through HTTP, it works fine.  This was working prior to the 3.x upgrade.

**Comment by snipe** [comment]
Can I see your session settings from your .env?

**Comment by Shadow00Caster** [comment]
# --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME=snipeit_session
COOKIE_DOMAIN=null
SECURE_COOKIES=false

I have tried setting SECURE_COOKIES to true and setting the COOKIE_DOMAIN
to sub.mydomain.tld

Kind regards,
*Matt Rhoades*

**Comment by snipe** [comment]
And you've got the correct values in the TRUSTED_PROXIES section?

**Comment by Shadow00Caster** [comment]
I did not, I tried adding all necessary IPs (specifically the IPs of the LB which is the endpoint) and still same issue.

**Comment by snipe** [comment]
What proxy are you using? Also have you tried enforcing https via web server or htaccess?

**Comment by Shadow00Caster** [comment]
It's just HAProxy, web server does not serve HTTPS, only serves HTTP.  HTTPS is done through HAProxy.  It looks like the problem is that Snipe-IT is not sticking to HTTPS, even though it's set as the app URL, given that all the elements (CSS, JS, etc) are being accessed over HTTP

![img](https://cloud.githubusercontent.com/assets/13611109/21952073/b3eb5a5e-d9c7-11e6-99eb-b0bc815f8250.png)

**Comment by snipe** [comment]
I'm not suggesting that it does, just that if you force the traffic over https (via htaccess, for example), you may be able to get around this issue. This is related to the Symfony Http handlers, and TRUSTED_PROXIES is supposed to handle that for you. Not sure why it's not here.

**Comment by Shadow00Caster** [comment]
Tried forcing via htaccess, less Mixed Content errors, but still same issue:

RewriteEngine On 
RewriteCond %{SERVER_PORT} 80 
RewriteRule ^(.*)$ https://sub.domain.tls/$1 [R,L]

**Comment by snipe** [comment]
Try something like:

```
RewriteCond %{HTTP:X-Forwarded-Proto} !https
RewriteCond %{HTTPS} off
RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
```

**Comment by Shadow00Caster** [comment]
Same result as from what I had before.

You can see the mixed content at https://asset.sortech.io, I can DM you credentials if you would like to test, though you can put it in credentials and it just reloads the login page, doesn't appear to even attempt login.  I enabled debug as well.

**Comment by snipe** [comment]
If you set TRUSTED_PROXIES to *, does that help?

**Comment by Shadow00Caster** [comment]
Nope :(

**Comment by snipe** [comment]
And you cleared your config cache, right? 
https://snipe-it.readme.io/v3.6.2/docs/clearing-the-config-cache

**Comment by Shadow00Caster** [comment]
I was not, but I just tried and not change, also restart apache for good measure.
