### ISSUE TITLE
Gravatar issue

### ISSUE THREAD

**Issue by noizo** [snipe/snipe-it#3189]
Latest git clone version
There is no gravatar picture in upper bar
![edit your profile 3a 3a growbots inventory 2017-01-14 22-39-52](https://cloud.githubusercontent.com/assets/1682474/21958267/ef2ce54a-daaa-11e6-88a5-2d62abfc40e9.png)

**Comment by snipe** [comment]
Which branch?

**Comment by noizo** [comment]
v3.6.3 build 15 (g1bf34d7)

**Comment by psywhale** [comment]
still happening on 

Version v4.1.14 - build 3408 (master)

**Comment by ghost** [comment]
This is still an issue with v4.9.0 build 4210 (g8b2f8ef3c). The gravatar loads fine unter the gravatar email field, but not anywhere else, as seen in the screenshot in the opening post.

Can this issue be reopened (@snipe)?
