### ISSUE TITLE
Backup & Restore

### ISSUE THREAD

**Issue by itims** [snipe/snipe-it#3193]
If once backup done, how can i restore it?
My backup file directory is **/var/www/snipeit/storage/app/backups**

# Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - **3.6.3 build 15**
- What OS and web server you're running Snipe-IT on - **Ubuntu 14.04.1 LTS** & **Apache 2**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - **install.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by jmathias59** [comment]
Importing a backup is done thru MySQL .  Search for import MySQL in a search engine to see how it is done.  Is the install Linux or Windows?

Get Outlook for iOS<https://aka.ms/o0ukef>

_____________________________

**Comment by itims** [comment]
Linux

**Comment by snipe** [comment]
https://www.cyberciti.biz/faq/import-mysql-dumpfile-sql-datafile-into-my-database/
