### ISSUE TITLE
Export as CSV exports only 50 rows

### ISSUE THREAD

**Issue by noizo** [snipe/snipe-it#3194]
SnipeIT v3.6.3 build 15 (g1bf34d7)
Ubuntu 16.04
Manual install

#### Expected Behavior (or desired behavior if a feature request)

Export all users

-----

#### Actual Behavior

It Exports only 50 rows

**Comment by noizo** [comment]
update: sometimes it export two files, one is 50 rows and second is OK

**Comment by noizo** [comment]
And one more thing about export.
It export firstName and LastName in one column, wich makes it impossible to import same file after making changes on it.

**Comment by snipe** [comment]
Just use the export button above the table.

**Comment by snipe** [comment]
Also, user import doesn't update, it just skips existing users at this time.
