### ISSUE TITLE
Reports not working from navigation, gives server error HTTP 503

### ISSUE THREAD

**Issue by Nabeel-Shahid** [snipe/snipe-it#3195]
#### Expected Behavior (or desired behavior if a feature request)

Installed on Windows 2012 R2 x64 server with IIS 8 on my local server and finally got it working after resolving all errors, but when I open any REPORTS from navigation menu it gives me (Service Unavailable - HTTP Error 503. The service is unavailable.) error which seems to be routing issue to me.

I also reviewed the route configuration file and couldn' t find any issue with it as reports routing entries are mentioned in that file.

Kindly help with this issue.

Thanks,

-----

#### Actual Behavior

**It should open REPORTS from navigation menu.**

-----

#### Please confirm you have done the following before posting your bug report:

- [ **YES** ] I have enabled debug mode
- [ **YES** ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running   **v3.6.3 build 15 (g1bf34d7)**
- What OS and web server you're running Snipe-IT on  **Windows 2012 R2 Standard Edition x64 with IIS 8**
- What method you used to install Snipe-IT **manual installation**
- WITH DEBUG TURNED ON, **Service Unavailable. HTTP Error 503. The service is unavailable. on opening mydomain.com/reports/activity**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **REPORTS, this is happening with all reports in navigation **
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. **Just one fontawesome.woff2 issue since I'm using Chrome browser**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). **No**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. **No information related to this error in logs, Log is clear for today. There were few issues during installation 2 days back which are mentioned in log file and those were resolved already**
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database **No**

**Comment by Nabeel-Shahid** [comment]
Just wanted to add that this behavior is happening with all reports:

../reports/activity
../reports/depreciation
../reports/licenses
../reports/asset_maintenances
../reports/assets
../reports/unaccepted_assets
../
../
../

**Comment by snipe** [comment]
> HTTP Error 503. The service is unavailable.) error which seems to be routing issue to me

That's not a routing issue. Try making sure that your APP_URL in your .env exactly matches the url you use to access the site.

**Comment by Nabeel-Shahid** [comment]
APP_URL in  .env exactly matches to url being used..

Not sure why does this happen to reports navigation ONLY and all other pages and navigation are working fine.

**Comment by snipe** [comment]
What is the url you see in the URL bar when you click on one of the reports?

**Comment by Nabeel-Shahid** [comment]
mydomain.com/reports/activity
Or
mydomain.com/reports/depreciation

**Comment by snipe** [comment]
And the protocols (http vs https) also match in the env file?

I'm honestly not sure why you'd be getting that, but a 503 error usually has something to do with the server config and not with the application.

**Comment by Nabeel-Shahid** [comment]
Yes, I have protocol mentioned with address in APP_URL

**Comment by Nabeel-Shahid** [comment]
503 is Webster very related but why does it only happens with reports navigation and rest of pages in application works fine. 

That's why I thought it would be relate do to url routing or something.

**Comment by snipe** [comment]
> 503 is Webster very related 

I don't know what that means

> That's why I thought it would be related to url routing or something.

No, you'd get a 404 or possibly Method Not Allowed. The routes are pretty standard, and we haven't heard of anyone else having this issue. 

How many records do you have in your database? (Assets, etc)

**Comment by Nabeel-Shahid** [comment]
I meant "503 Is webserver related"

And I only have 6 assets added to database as this was new installation done. I have traversed all pages are working except reports. 

Also recycled application pool and restarted website from IIS Web server, but reports navigation doesn't work.

**Comment by snipe** [comment]
What version of PHP are you running?

**Comment by Nabeel-Shahid** [comment]
I'm running PHP 5.6

**Comment by snipe** [comment]
Yeah, I'm out of ideas then. I'm not really an IIS person though, so perhaps another community member can help you troubleshoot further.

**Comment by Nabeel-Shahid** [comment]
I have got into more details and fixed the issue myself; it was application routing issue which I fixed by changing following files. 


1- Added a prefix to route:: group of reports section of  app/http/routes/php file (after which reports starts working using URL) 

```
Route::group([ **'prefix' => 'rpt'**, 'middleware' => ['web','auth','authorize:reports.view']], function () {
    Route::get(
        'reports/depreciation',
        [ 'as' => 'reports/depreciation', 'uses' => 'ReportsController@getDeprecationReport' ]
    );
route::group([ 'prefix' => 'rpt', 'middleware' => ['web','auth','authorize:reports.view']], function () {    Route::get(        'reports/depreciation',        [ 'as' => 'reports/depreciation', 'uses' => 'ReportsController@getDeprecationReport' ]    );
```

2- Then changed \resources\views\layouts\default.blade.php file by adding prefix for treeview-menu navigation list index.

```
<ul class="treeview-menu">
    <li><a href="{{ URL::to('**rpt/**reports/activity') }}" {{ (Request::is('**rpt/**reports/activity') ? ' class="active"' : '') }} >@lang('general.activity_report')</a></li>
```

Thanks a bunch

**Comment by snipe** [comment]
That should absolutely not be necessary, and will be overwritten the next time you update. (Literally no one but you is having this issue...)

**Comment by Nabeel-Shahid** [comment]
Can't say anything about others having same issue as It depends how many users are using same version of Snipe-IT/PHP/Windows OS/IIS etc.

Anyhow, it was necessary for me to open Snipe-IT reports as there was no other solution available.

I wouldn't have got into much details of this issue and applied this fix if other navigation pages were not working perfectly, but it was strange that all other navigation & pages were working fine and just reports were not opening!

Thanks

**Comment by tramperdk** [comment]
Hi, I just felt like contributing a bit to this conversation. I installed Snipe-IT on a server that already was hosting misc. tools for my org. on this particular server we had SQL already installed (Note this server instance had Reporting tools installed as well.) 

I faced the same issue regarding reports not working, but everything else was (Thanks for the installation guide ! 👍 ). 

After uninstalling SQL Reporting services the problem went away and all reporting from Snipe-IT worked flawlessly. My guess is that Nabeel made it work with the routing because the reporting services already hooks onto `http(s)://server/Reports.` 
But I haven't looked into it a whole lot.

Thanks for a great product.

**Comment by snipe** [comment]
@tramperdkthats really interesting - thank you got the info and follow up!

**Comment by snipe** [comment]
Maybe the solution here is to rename the reports section in the next release, so it doesn't conflict. (That's super-annoying behavior, that they would effectively highjack a URL, instead of putting the reporting on a separate port number or something.) We'll try to come up with something to work around this for you folks.

**Comment by Nabeel-Shahid** [comment]
Just wanted to clarify that SSRS is not configured or used on my server.
When I open http(s)://server-name/reports  nothing is hooked to this URL on IIS server.

Thanks for considering to fix this in next release.

**Comment by snipe** [comment]
@Nabeel-Shahid it has to be something similar though, since the reports URL works fine for everyone else.

**Comment by FillmoreB0** [comment]
As much as I hate to resurrect a closed thread, We had this exact same issue with the current version (V.6.3.0).  The actual fix is to run "netsh http delete urlacl url=http://+:80/Reports" in an Admin command window to get rid of the SSRS configuration that is left behind even after uninstalling all thinjgs MSSQL.

This can be avoided in future builds of SniPe-IT by changing the reports folder name.

Thanks for a great product!
