### ISSUE TITLE
[Feature Request] - LDAP Syncing for Super Users Only

### ISSUE THREAD

**Issue by veen1981** [snipe/snipe-it#3196]
#### Expected Behavior (or desired behavior if a feature request)

I am currently going through over 1000 user accounts and updating locations because someone ran an LDAP sync and selected a location, which in turn updated all synced users to that location. I believe that the LDAP syncing feature should only be available to super-users. If that is not the appropriate route, then there should be a permissions setting in groups to enable or disable this feature.

-----

#### Actual Behavior

Admins are able to perform LDAP syncs.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by grandmamoses** [comment]
Agree with this, we had the exact same issue. Maybe there should be a setting to use a location from an LDAP field when syncing, or not use location when syncing at all.
