### ISSUE TITLE
Settings Logo Upload option not working - Image Source not readable

### ISSUE THREAD

**Issue by Nabeel-Shahid** [snipe/snipe-it#3197]
#### Expected Behavior (or desired behavior if a feature request)

When I try to select / upload LOGO and save settings it gives me this error on http://mydomain.com/admin/settings/app/edit

Just wanted to add that I'm able to upload and view Asset images from "Edit Asset" option and it works all fine, also bar-code images are generated and view able in application without any issue.

Below error I get when press save in ADMIN > SETTINGS > EDIT SETTINGS page after selecting logo file.

**Whoops, looks like something went wrong. NotReadableException in AbstractDecoder.php line 302: Image source not readable**
-----

#### Actual Behavior

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

Version of Snipe-IT you're running **v3.6.3 build 15 (g1bf34d7)**
What OS and web server you're running Snipe-IT on **Windows 2012 R2 Standard Edition x64 with IIS 8**
What method you used to install Snipe-IT **manual installation**
WITH DEBUG TURNED ON, **Whoops, looks like something went wrong. NotReadableException in AbstractDecoder.php line 302: Image source not readable**
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error  **ADMIN > SETTINGS > EDIT SETTINGS page after selecting logo file.**

If a stacktrace is provided in the error, include that too. **added below**
Any errors that appear in your browser's error console. **Just one fontawesome.woff2 issue since I'm using Chrome browser**
Confirm whether the error is reproduceable on the demo. **Cannot change this on demo**
Include any additional information you can find in app/storage/logs and your webserver's logs. 
**NotReadableException in AbstractDecoder.php line 302:
Image source not readable
in AbstractDecoder.php line 302
at AbstractDecoder->init(false) in AbstractDriver.php line 64
at AbstractDriver->init(false) in ImageManager.php line 50
at ImageManager->make(false) in compiled.php line 6325
at Facade::__callStatic('make', array(false)) in SettingsController.php line 311
at Image::make(false) in SettingsController.php line 311
at SettingsController->postEdit()
at call_user_func_array(array(object(SettingsController), 'postEdit'), array()) in compiled.php line 9424
at Controller->callAction('postEdit', array()) in compiled.php line 9486
goes on...
**
Include what you've done so far in the installation, and if you got any error messages along the way. **read and configured permissions as specified in documentation common errors**
Indicate whether or not you've manually edited any data directly in the database **No**

**Comment by Nabeel-Shahid** [comment]
any updates on this issue?

**Comment by reison007** [comment]
Hi,

I have changed the issue title to [Feature Request]

First off, I want to express my appreciation for your work.



I work for the Ministry of Culture of Brazil and we have a need of a
license management solution.

Perhaps I did not understand how to configure expiring notifications
properly.

2017-01-20 9:45 GMT-02:00 NABEEL <notifications@github.com>:

**Comment by dmeltzer** [comment]
@Nabeel-Shahid : What type of file are you trying to upload?  If you were to test uploading that file to an asset, does it work there?

**Comment by Nabeel-Shahid** [comment]
.png and .jpeg and yes it works on assets.

**Comment by snipe** [comment]
Is your entire `public/uploads` directory writable by the web server? How big is the file you're trying to upload?

**Comment by ambarishrh** [comment]
I have a similar issue. As soon as I try to upload a logo (PNG file), the browser gives me the error "This site can’t be reached

The webpage at http://SITE_URL/admin/settings/app/edit might be temporarily down or it may have moved permanently to a new web address.
ERR_CONNECTION_ABORTED

Enabled Debug mode, but still I am only getting the above error, nothing on laravel log file either

**Comment by snipe** [comment]
@ambarishrh what is your APP_URL in your .env?

**Comment by ambarishrh** [comment]
Hello

This is fixed now. It was a local machine upload block. Thanks!
