### ISSUE TITLE
[Feature Request] Search field at the Top "Lookup by Asset Tag"

### ISSUE THREAD

**Issue by B3RN0UT** [snipe/snipe-it#3198]
#### desired behavior if a feature request

The function of the search field at the top of the page "Lookup by Asset Tag" should in my opinion work as the search field in assets/licenses etc. This means the results should show every item which begin for example with "The". 
I often want to use this field cause it's the first option to search quickly at the dashboard.

-----

#### Actual Behavior

Search field even accept the exact name of the Asset Tag and will only result the identical match.

-----

**Comment by noizo** [comment]
+1

**Comment by Nabeel-Shahid** [comment]
yes, it will help adding this as feature on top of page "Lookup by Asset Tag"


@B3RN0UT For now as workaround you can use bootstrap table search with wild card character % and it will display result with identical match on any record that starts with characters "The"

_**Note:** One issue with this approach is; it always search for data in all columns of table._ 

For example:   **The%**

Hope this helps.

**Comment by snipe** [comment]
They're not meant to work the same. The Look up by Asset Tag search is optimized for barcode scanners, and you should never have multiple results. If it find a match, it takes you directly to the asset, without an interstitial search results page. 

@Nabeel-Shahid you don't need the wildcard character.

**Comment by aditya6190** [comment]
Can it be modified to lookup by Asset Name? if yes, then how?

**Comment by tharple** [comment]
The **Lookup by Asset Tag** limitations make the main search area useless for us without barcode scanners (everyone where I work). 
It also makes the dashboard landing page all but useless for the individuals that just want to search for available assets which may or may not have asset tags.
I was going to suggest that we use custom prefixes in our asset tags IDs to get around it until I found out that the search only finds exact matches. No very inflexible. :^(
