### ISSUE TITLE
asset_tag not from small to large sort

### ISSUE THREAD

**Issue by zdong08** [snipe/snipe-it#3199]
hello,snipe, asset_tag not from small to large sort，this is bug
![image](https://cloud.githubusercontent.com/assets/13311479/22005253/966603bc-dc9c-11e6-9700-7d9e0d0196b2.png)

**Comment by zdong08** [comment]
I modified the field type to int directly

**Comment by snipe** [comment]
The asset tag shouldn't really be an int field though. Lots of folks have asset tags that include letters, symbols, etc. If this works for you, that's fine, but be aware that it could bite you later on.

**Comment by zdong08** [comment]
ok,thank you!
