### ISSUE TITLE
Save and Print Label button feature for new assets

### ISSUE THREAD

**Issue by viclou** [snipe/snipe-it#3200]
#### Expected Behavior (or desired behavior if a feature request)

Save and Print Label button feature available when creating new assets (FD: 1352)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by VanillaNinjaD** [comment]
This would be a wonderful feature!

We rarely purchase enough assets to make the bulk label printing worthwhile. We simply generate the labels 1 by 1, print them on a Dymo label printer, then cover them with a vinyl protector made for protecting the labels on the spine of library books.

The individual labels work very well for us and this would make them easier to generate
