### ISSUE TITLE
docker app routing to http://127.0.0.1:8080/setup

### ISSUE THREAD

**Issue by shyamjos** [snipe/snipe-it#3201]
#### Expected Behavior (or desired behavior if a feature request)

it should redirect to example.com:8080/setup

-----

#### Actual Behavior

docker app routing to http://127.0.0.1:8080/setup when accessing example.com:8080 url

-----

my docker run command: sudo docker run -d -p 8080:8080 --name="snipeit" --link snipe-mysql:mysql -v /home/docker/snipe-it/snipe-data:/var/lib/snipeit --env-file=/home/docker/snipe-it/snipe_env snipe/snipe-it

my docker env 
-------------------

```
# Email Parameters
# - the hostname/IP address of your mailserver
MAIL_PORT_587_TCP_ADDR=smtp.whatever.com
#the port for the mailserver (probably 587, could be another)
MAIL_PORT_587_TCP_PORT=587
# the default from address, and from name for emails
MAIL_ENV_FROM_ADDR=youremail@yourdomain.com
MAIL_ENV_FROM_NAME=Your Full Email Name
# - pick 'tls' for SMTP-over-SSL, 'tcp' for unencrypted
MAIL_ENV_ENCRYPTION=tcp
# SMTP username and password
MAIL_ENV_USERNAME=your_email_username
MAIL_ENV_PASSWORD=your_email_password

# Snipe-IT Settings
APP_ENV=production
APP_DEBUG=false
APP_KEY=
APP_URL=http://127.0.0.1:8080
APP_TIMEZONE=Asia/Kolkata
APP_LOCALE=en
```

**Comment by snipe** [comment]
Change the APP_URL in your docker env to whatever the site URL should be

**Comment by shyamjos** [comment]
worked like charm! 
thanks
