### ISSUE TITLE
(docker) ErrorException in McryptEncrypter.php line 104

### ISSUE THREAD

**Issue by shyamjos** [snipe/snipe-it#3202]
#### Expected Behavior (or desired behavior if a feature request)

snipe-it should load without any error

-----

#### Actual Behavior

throwing this error 
```
ErrorException in McryptEncrypter.php line 104:
mcrypt_encrypt(): Key of size 44 not supported by this algorithm. Only keys of sizes 16, 24 or 32 supported
```

sudo docker run --rm snipe/snipe-it
Please re-run this container with an environment variable $APP_KEY
An example APP_KEY you could use is: 
[redacted]
I am using above key

**Comment by snipe** [comment]
Your APP_KEY should never be made public. I suggest you regenerate yours immediately, using the `php artisan key:generate` command.

**Comment by shyamjos** [comment]
that's just an example , we are using another one

**Comment by snipe** [comment]
Regardless, it's not sound advice to offer an APP_KEY for users to use. It's enormously insecure. Running the key generating on your system should provide a secure, unique key.

**Comment by shyamjos** [comment]
manually trimmed it to 12 and it worked !
