### ISSUE TITLE
[Bug?] Accepted assets by 'Deleted Admin'

### ISSUE THREAD

**Issue by abaalkh** [snipe/snipe-it#3205]
Hello,

I think there is a bug in the asset acceptance from users.

When accepting assets, the history returns the 'accepted by' column empty for the users and displays 'Deleted Admin' for admins when viewing the user.
However, when looking at the Acticity Report, it displays the username with no issue.

Admin > people > history view:
![image](https://cloud.githubusercontent.com/assets/2372747/22057080/2da24c72-dd74-11e6-8a3a-c60dcfe66a25.png)

Activity Report from an admin account:
![image](https://cloud.githubusercontent.com/assets/2372747/22057197/b08fb3f4-dd74-11e6-81b5-135e4145b5a7.png)

Is this a permission problem?
Keep in mind that the user has 0 permissions on the system (all deny).

Version of Snipe-IT you're running: 3.6.3 build 15
What OS and web server you're running Snipe-IT on Centos 7
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
Indicate whether or not you've manually edited any data directly in the database: Yes, mass modification for user locale.

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Indicate whether or not you've manually edited any data directly in the database

The only way you should see that is if you (or someone else) deleted the admin and then purged them.

**Comment by abaalkh** [comment]
Hi @snipe thanks for the prompt reply.
 I am the only Admin on the system and haven't deleted or purged myself.
Edited the OP with the information requested.

**Comment by kenfrancisadams** [comment]
I am experiencing the same issue.

If I look at a users 'History' tab the 'Action' column shows 'Deleted Admin' when an asset is accepted instead of the username of the person who signed for it.

I am running version Version v3.6.4 build 12 (gf7e4fca), it's running on Ubuntu 16.04.2 and I installed Snipe-IT with install.sh so I assume it's using apache as that's what the installer uses, right? I have not manually edited any data directly in the database.
