### ISSUE TITLE
[Feature Request] Accept asset from dashboard.

### ISSUE THREAD

**Issue by abaalkh** [snipe/snipe-it#3207]
Hi there,

It would be great if users could accept assets from the dashboard as well as emails.
If the user lost their check-in email, there is no easy way to 'accept' the asset.

So i suggest having the accept button/link on a new column in the 'checked out to you' section.

**Comment by VanillaNinjaD** [comment]
These are both awesome ideas!

I think another welcome addition would be a button next to each asset in the "Unaccepted Assets" report to "Re-notify User" that just sends the acceptance email to them again so the users don't have to dig through their email inboxes to find the original email.

**Comment by abaalkh** [comment]
@VanillaNinjaD That would also be amazing.
I just deployed the system today to users and i have no clue who is left to accept the asset so i can hunt them down!

**Comment by VanillaNinjaD** [comment]
Have you seen the "Unaccepted Assets" report?

that report is built-in and available now

**Comment by abaalkh** [comment]
Thank you, i haven't seen it!

**Comment by grimstoner** [comment]
Shouldn't the "Re-Notify button on the Unaccepted Assets Report" be a separate Feature Request?

**Comment by goludiaOH** [comment]
100% agree - would love it if users didn't have to hunt for their email to accept an asset.  If they lost it, or if they received many assets, this is difficult to manage without being able to accept from within the tool.

**Comment by omyno** [comment]
This is still a much-needed feature
