### ISSUE TITLE
Asset models Notes

### ISSUE THREAD

**Issue by rumpeltizkin** [snipe/snipe-it#3215]
#### Expected Behavior (or desired behavior if a feature request)

Everytime I fill notes field for a Asset Model it does not show in the notes field in the table. I have to go to edit to read the specifications of the asset (because I write the technical specs inside Notes).

-----

#### Actual Behavior

It would have to show all the text written inside Notes textbox.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

Version v3.6.3 build 15 (g1bf34d7)
Debian 8.6
Manual installation. Everything installed correctly following the website manual.

**Comment by abaalkh** [comment]
You can choose which columns to show (including notes) in the table view top left of the table.
