### ISSUE TITLE
Search on Serial

### ISSUE THREAD

**Issue by cduverne** [snipe/snipe-it#3216]
#### Expected Behavior (or desired behavior if a feature request)

In the search bar on the main page, I'd like to be able to search for a serial number

-----

#### Actual Behavior

Only asset numbers are supported

-----

#### Please confirm you have done the following before posting your bug report:

- [N/A] I have enabled debug mode
- [*] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running -> 3.6.3
- What OS and web server you're running Snipe-IT on -> Docker version
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) -> Docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error -> N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error -> Main page
- If a stacktrace is provided in the error, include that too. -> N/A
- Any errors that appear in your browser's error console. -> N/A
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). -> N/A
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. -> N/A
- Include what you've done so far in the installation, and if you got any error messages along the way. -> N/A
- Indicate whether or not you've manually edited any data directly in the database -> N/A

**Comment by snipe** [comment]
That creates a weird UX in those fringe cases where one asset's asset tag is the same as another asset's serial, though. That top bar is meant to only search on asset tag, specifically to work with barcode scanners, so people can quickly scan, get to the page, scan, get to the page, etc.

**Comment by cduverne** [comment]
I understand and allow me to challenge this.
Maintaining asset tags for a little organisation is a burden, especially when all assets are already wearing a barcode to indicate their serial number.

Therefore, could it be envisioned to choose the field we want to search in, in the search bar.
Using a configuration parameter for example in the organisation's settings ?

I would be happy to help, if you'd like to guide me a bit in the codebase.

**Comment by vjandrea** [comment]
+1 for a more flexible search field in the navbar, with a dropdown that allows to choose the field you are looking for, and an option to search anywhere. By default it would be asset id, so it shows directly the item page, but choosing another field not unique it would show an aggregate list of results grouped by type: x assets, y accessories, Z components. Possibly, if the result is just one, it would show directly the item page.

**Comment by tjgruber** [comment]
Yes this would definitely be a welcomed feature I and others would love to see.

**Comment by wRx7MSTi** [comment]
I would love this to be an optional change from the settings page.

**Comment by jamescapen** [comment]
Agreed, the option to change the default behavior of that search bar would be helpful.

**Comment by k8s-gpubuilder-markus** [comment]
For our use case, the search is completely useless without being able to actually search for what you want. We don't maintain asset tags, it is not necessary, as somebody mentioned before: Everything already carries serial numbers. I have to say that I'm not impressed by the Snipeit GUI and this and your unwillingness to make it more user friendly solidifies this impression. Luckily, the browser search is more useful and works to find everything in a list.

**Comment by snipe** [comment]
@k8s-gpubuilder-markus Most people in that situation simply use their serial numbers as their asset tags
