### ISSUE TITLE
Alerts not sending since setup

### ISSUE THREAD

**Issue by JExactly** [snipe/snipe-it#3219]
#### Expected Behavior (or desired behavior if a feature request)

I expect alerts to send via email. I have Set an alert email address, I have enabled alerts. I have set a threshold for Days and Quantity. Nothing Sent. I have additionally added a Cron job as well to run the command, no alerts are sent. When I manually run the commands: `php artisan alerts:expiring` I get the error below

![image](https://cloud.githubusercontent.com/assets/14076881/22164165/15dca5cc-df24-11e6-8387-c0ab5c1220c0.png)

-----

#### Actual Behavior

Nothing is sent.

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running : v3.5.2-11-g5a835a5
- What OS and web server you're running Snipe-IT on: Ubuntu Server 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: N/A
- If a stacktrace is provided in the error, include that too.: N/A
- Any errors that appear in your browser's error console.: N/A
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).: N/A
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.: None, Been running since V2
- Indicate whether or not you've manually edited any data directly in the database: None

**Comment by snipe** [comment]
Please see the documentation on the correct commands to us: https://snipe-it.readme.io/v3.6.2/docs/configuring-alerts-backups

**Comment by JExactly** [comment]
Yes, I also have that command added to My Cron Job. The string I tried was for testing. But it appears that was from an old post and it is no longer functions.

The proper command from the documentation gives this: 
![image](https://cloud.githubusercontent.com/assets/14076881/22175755/93a83408-dfc9-11e6-9c89-895d474b5c76.png)

But I definitely have consumables that have expired I see the notifications in the web app, But I expected that they would send email alerts for consumables etc.. as well.  Is this how it is designed to work?
