### ISSUE TITLE
[Feature Suggestion] Adding an "Event" to a device

### ISSUE THREAD

**Issue by AlexEmmins** [snipe/snipe-it#3220]
Be able to add an event to a device. EG if a cable was changed on an asset, you could add that as an event with date/time and who did it

**Comment by JExactly** [comment]
@AlexEmmins This seems to me that this feature is almost identical to asset maintenance. You can do the same thing with a note of what was completed when and the time started and completed. You would just have to add the person who is completing the maintenance as the supplier.

**Comment by Guenny0488** [comment]
Think so. To only thing i see - you have to add your IT Personal as an Supplier too
