### ISSUE TITLE
Pre-flight not loading

### ISSUE THREAD

**Issue by gitshanif** [snipe/snipe-it#3223]
#### Expected Behavior (or desired behavior if a feature request)
**After the successful installation i should be able to get pre-flight page**
(what you expect to happen goes here)

-----

#### Actual Behavior
**Loading nothing**
(what actually happens goes here)

**[Mon Jan 23 00:02:55.016812 2017] [:error] [pid 46081] [client 127.0.0.1:42960] PHP Fatal error:  require(): Failed opening required '/var/www/snipeit/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/snipeit/bootstrap/autoload.php on line 17**
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running

- What OS and web server you're running Snipe-IT on
**3.6.3**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
**have not done**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
No page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
 nclude any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
**No errors apart from i specified above**.
- Indicate whether or not you've manually edited any data directly in the database
**No**

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/common-issues

**Comment by EmersonDavi** [comment]
HI, we can not use your system on host because that?

**Comment by snipe** [comment]
Please read the link I posted. Your issue is covered there. You have not run the composer install commands.
