### ISSUE TITLE
Installation: error when executing php composer.phar install

### ISSUE THREAD

**Issue by gmb07** [snipe/snipe-it#3225]
#### Expected Behavior (or desired behavior if a feature request)

Smooth installation of composer

-----

#### Actual Behavior

Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laravel/framework v5.2.45 -> satisfiable by laravel/framework[v5.2.45].
    - laravel/framework v5.2.45 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 2
    - Installation request for league/csv 7.2.0 -> satisfiable by league/csv[7.2.0].
    - league/csv 7.2.0 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 3
    - Installation request for maknz/slack dev-master -> satisfiable by maknz/slack[dev-master].
    - maknz/slack dev-master requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 4
    - laravel/framework v5.2.45 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - watson/validating 2.2.2 requires illuminate/contracts ~5.0 <5.3 -> satisfiable by laravel/framework[v5.2.45].
    - Installation request for watson/validating 2.2.2 -> satisfiable by watson/validating[2.2.2].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.0/cli/php.ini
    - /etc/php/7.0/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.0/cli/conf.d/10-opcache.ini
    - /etc/php/7.0/cli/conf.d/10-pdo.ini
    - /etc/php/7.0/cli/conf.d/20-calendar.ini
    - /etc/php/7.0/cli/conf.d/20-ctype.ini
    - /etc/php/7.0/cli/conf.d/20-curl.ini
    - /etc/php/7.0/cli/conf.d/20-exif.ini
    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.0/cli/conf.d/20-ftp.ini
    - /etc/php/7.0/cli/conf.d/20-gd.ini
    - /etc/php/7.0/cli/conf.d/20-gettext.ini
    - /etc/php/7.0/cli/conf.d/20-iconv.ini
    - /etc/php/7.0/cli/conf.d/20-json.ini
    - /etc/php/7.0/cli/conf.d/20-mysqli.ini
    - /etc/php/7.0/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.0/cli/conf.d/20-phar.ini
    - /etc/php/7.0/cli/conf.d/20-posix.ini
    - /etc/php/7.0/cli/conf.d/20-readline.ini
    - /etc/php/7.0/cli/conf.d/20-shmop.ini
    - /etc/php/7.0/cli/conf.d/20-sockets.ini
    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

-----

#### Please confirm you have done the following before posting your bug report:

- [*] I have enabled debug mode
- [*] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
> I assume it is the latest version
- What OS and web server you're running Snipe-IT on
> Ubuntu 16.10
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
> install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
> N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
> N/A
- If a stacktrace is provided in the error, include that too.
> N/A
- Any errors that appear in your browser's error console.
> N/A
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
> N/A
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
> N/A
- Include what you've done so far in the installation, and if you got any error messages along the way.
> N/A
- Indicate whether or not you've manually edited any data directly in the database
> No

**Comment by snipe** [comment]
The first error told you what was wrong. Install mbstrings

**Comment by gmb07** [comment]
Thanks snipe! :D
