### ISSUE TITLE
Best restore option

### ISSUE THREAD

**Issue by tanguyngoy** [snipe/snipe-it#3226]
Hi Snipe Community,

Just wondering if you could help me on a minor problem.

We've been using version 2 for almost a year but unfortunately the system crashed due to hardware failure. I do have a zip backup though, but it's a few months back. I have no choice but to do a fresh install on another machine.

What do you think is my best and easiest course of action?
a. ) restore the database with a different name and just edit the .env
      or
b. ) import the backup into the current database

What are the implications of both approach? (both are installed using the install.sh method)

Sorry for the newbie question. :-) Still familiarizing on the system.

Thanks in advance.

**Comment by jmathias59** [comment]
My answers are based upon an hardware move from 3.6 to 3.6 but may be helpful.

After a complete new install, I did a sql import after creating the database.  There is no restore feature within SnipeIT.  Be sure to copy the public/uploads directory and storage/private_uploads because these are not included in the sql zip file.

James

**Comment by tanguyngoy** [comment]
Thanks @jmathias59!

But I'm afraid I can't copy those folders back because it's the disk that crashed. What's in those folders anyway? If I remember it right we didn't upload any significant files (except for the logo). Would there be errors after import even if those folders are empty?

Thanks again.

**Comment by jmathias59** [comment]
I found that the logo would not load, even if I uploaded a new logo, when I did an import but did not move the two directories.  Must be something in the sql database.  We had a logo as well as images of all our asset models so restoring the images was important.  I did a complete re-install, moved the directories, than imported the sql.zip file.

Anyway to mount the hard drive in another system?

James

**Comment by tanguyngoy** [comment]
Unfortunately the data is unrecoverable, not to mention it's in RAID 5. Do you think we can still salvage any data left in the zip backup without retyping everything?

**Comment by jmathias59** [comment]
The zip backup, once extracted, is a single file designed for import into MySQL.  After import, everything should be restored with the exception on the images/logo.  SnipeIT support might be able to assist with the modification of sql files to correct the missing logo file.

BTW – is this install Linux or Windows?

James

**Comment by tanguyngoy** [comment]
The previous installation is on CentOS 7, now it's on Ubuntu 16.04. 
Aside from the logo, is there any other files that could affect the migration? We didn't upload asset images before and I think we could do without the logo for now. One of our top priorities is the asset movement history.

**Comment by snipe** [comment]
Only if you uploaded any license files. V3 backup includes uploaded files. IIRC, so hopefully next time this happens, you'll have everything. You should probably also set up the cron to automate the backups.

**Comment by tanguyngoy** [comment]
Thanks, @snipe!

We did input licenses and assigned them to users accordingly, but when you say license 'files' do you mean images, like jpg, or the information itself? When I browsed the private_uploads folder I do see assetmodels, assets,imports, licenses, signatures and users folders inside. Correct me if I'm wrong, but my hunch is that the system won't run even if I restore the old database because references to these folders were missing.

**Comment by snipe** [comment]
I mean uploaded files. 

>  When I browsed the private_uploads folder I do see assetmodels, assets,imports, licenses, signatures and users folders inside.

On the old system, or the new system? 

> Correct me if I'm wrong, but my hunch is that the system won't run even if I restore the old database because references to these folders were missing.

It should run fine, but if you're using an older database (v2), you'll want to make sure you walk through the upgrade guide to make sure everything is where it needs to be.

https://snipe-it.readme.io/docs/upgrading-to-v3

**Comment by tanguyngoy** [comment]
On the new system, I mean.

I've read the guide, but I think it tackles more about the move from v2 to v3, assuming all files and references are intact. Unfortunately for me, all I have is the single .sql file from the zip backup. That is why I'm hesitant to restore the database file.

By the way, is the Import option in the GUI a viable option? I guess that won't include the history though.

**Comment by snipe** [comment]
If you installed v3 from scratch, you should have the necessary directories already. Just import your SQL, and then run migrations.

**Comment by tanguyngoy** [comment]
Oh, I see...
Would that be step #7 on the guide?

**Comment by snipe** [comment]
Yep

**Comment by tanguyngoy** [comment]
Alright. Will try today (fingers-crossed) :-)

Thanks!

**Comment by snipe** [comment]
No problem. If you get stuck, just let us know. As long as you have your database dump from the old install, you'll be fine. Upgrading the database is handled through migrations, which means you can't really break it too badly.

**Comment by tanguyngoy** [comment]
Whew! That went well!

Thanks for all the help...

**Comment by snipe** [comment]
Great!

**Comment by DawnTan0321** [comment]
@snipe Could you tell me, how can I restore images in backup.zip to mysql? I restored the records but without images. I backup data via clicking Generate Backup icon on Backups page.

**Comment by jmathias59** [comment]
Two directories need to be manually copied: public/uploads and storage/private_uploads. These are not included in the sql zip file.

**Comment by DawnTan0321** [comment]
It works! Thanks very much!
My steps:
1. docker exec -it [mysql] bash
2. copy snipeit.sql(in backup.zip) to mysql docker bash
3. mysql -u root -p snipeit < ./snipeit.sql
4. copy var/lib & var/www(in backup.zip) to mysql docker 
5. docker exec -it [snipeit_destination] bash
6. copy public/uploads & storage/private_uploads in the source of snipeit docker bash to the destination of snipeit docker bash
7. restart the snipeit & mysql docker container
8. refresh the snipeit page

**Comment by DawnTan0321** [comment]
Maybe the step 4 & step 5 are redundant.
