### ISSUE TITLE
[Feature Request] Print users inventory

### ISSUE THREAD

**Issue by HaikoHertes** [snipe/snipe-it#3229]
#### Expected Behavior (or desired behavior if a feature request)

I want to print out the full Inventory of all assets, licenses, accessories and other stuff, that is currently checkd out to a user. In our old 2.x version this was quite easy. We need this for our employees to sign when the get new hardware. Thanks!

-----

#### Actual Behavior

Currently, I would need to print a few pages. One for assets, one for licenses and so on. On top, the pages don't show the users name. My current workaround is to print the history (at least, it shows all checkouts) and use the page header from the browser for the username.) But that is far away from what we used to do in the old version.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode (does not apply)
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: 3.6.3 b15
- What OS and web server you're running Snipe-IT on: Debian 8 / Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by Guenny0488** [comment]
Sounds like a really useful Feature Request to me.

 

Rgds

Sebastian

**Comment by abaalkh** [comment]
+1 On this feature, I like the idea.

**Comment by mlehtmets** [comment]
+1 to this request.

**Comment by grandmamoses** [comment]
+1 to this please :-)

**Comment by JExactly** [comment]
Excellent Idea! +1

**Comment by rozowykubek** [comment]
I like the idea of printing summary of everything that has been checked out to user +1: 

> We need this for our employees to sign when the get new hardware. Thanks!
hm what are you trying to achieve  ? it does sound like you aren't using user acceptance feature

**Comment by dedeoglumrt** [comment]
+1 to this request. 
We also need to this for our employees to sign when the get new hardware.

**Comment by dedeoglumrt** [comment]
up up up please

**Comment by snipe** [comment]
This is on develop now.
