### ISSUE TITLE
Problem with images after domain change

### ISSUE THREAD

**Issue by pawel1615** [snipe/snipe-it#3232]
#### Expected Behavior (or desired behavior if a feature request)

If I change a server domain, all pictures should be still visible

-----

#### Actual Behavior

I can't see any pictures or logo on login page

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 3.4.14
- What OS and web server you're running Snipe-IT on Centos 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Hi everyone, 
I've been using Snipe IT installed on a server with IP X.X.X.X under domain domain1.com but last days, I've change IP of this server into Y.Y.Y.Y which is under other domain: domain2.com. After this operation all pictures in snipeIT are invisible( I mostly mean pictures of Assets). I suppose each picture in Snipe IT is described by a link generated by php. This link contain domainname or base domain. After we change domain all links are invalid. How can I change it? Is it saved in database? Do I need to change each record or can I change one field?
Thanks for any help
Pawel

**Comment by snipe** [comment]
Did you remember to update your APP_URL in your env? What's the URL to an example image that's showing up broken?

**Comment by pawel1615** [comment]
That's exactly what I needed. Thank You. Now works like a charm.
