### ISSUE TITLE
Configure E-Mails when Check Out Assets to a user

### ISSUE THREAD

**Issue by Guenny0488** [snipe/snipe-it#3233]
Hi Team,
where can i configure the emails sent to a user when they gets and asset assigned? 
I have configured email during installation and the test was successful - but now i don't see any further setup to manage the email topic.

Rgds
Sebastian

**Comment by snipe** [comment]
You'll need to add an email address for the users you wish to receive an email confirmation when an asset is checked out to them.

**Comment by snipe** [comment]
Or, wait, are you asking how you can configure the emails themselves? That's not currently possible through the web UI.

**Comment by Guenny0488** [comment]
The users have all an Email address. Synced with LDAP. But i don't get any notifications.

**Comment by snipe** [comment]
Do you have those options enabled at the category level?

**Comment by Guenny0488** [comment]
ah - this options i looked for :+1: 
i will try

**Comment by Guenny0488** [comment]
it works. 
Is there a way to Customize this E-Mail a bit?
