### ISSUE TITLE
Set default columns manually in Assets view

### ISSUE THREAD

**Issue by pawel1615** [snipe/snipe-it#3237]
#### Expected Behavior (or desired behavior if a feature request)
Set default columns for all users in Assets section. When users enter section Assets or any else, they see fields, which admin wants e.x. Device Image and Asset Name

-----

#### Actual Behavior

Each time user log in, see some default fields,which are not so interesting for him. 

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running  **v3.4-14**
- What OS and web server you're running Snipe-IT on   **Centos 7**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual isntallation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
I don't understand what you're saying. Can you provide screenshots?

**Comment by pawel1615** [comment]
![columns](https://cloud.githubusercontent.com/assets/19408004/22327951/171fc0d2-e3ba-11e6-82cd-ce81b9edfc97.png)
So this is a view, when I enter view Assets. But after I log in once again or on other PC, I will see other columns in this view, like ID, Company. But I would like to always see this columns. Keep them as default.

**Comment by snipe** [comment]
The cookie is browser-based, so it will remember the state on the same machine, but not across multiple machines. Most people are only accessing it from a handful of machines, and once their preferences are set in their browser cookie, they don't have to worry about it again.  I'm not sure this will end up being a priority for us.

**Comment by pawel1615** [comment]
Thanks for an answer. It is fully satisfying me. 
I am really impressed, how quickly You answer for issues :)
Pawel

**Comment by snipe** [comment]
Thanks for the kind words :)

If it were trivial, we'd actually try to get that handled for you, but it's actually a bit more complex than it looks, because of the javascript library we use to display the table data. :-/ If only things were as easy as they should be, right?

![computer-hates-me](https://cloud.githubusercontent.com/assets/197404/22328681/554b9d88-e372-11e6-8021-f5f5b98bbbec.gif)

**Comment by digitalprored** [comment]
In our case this feature would be very nice to have.
We create users for customers. If we can select which columns to display by default, we will do it easy for our users.

**Comment by opericgithub** [comment]
bump. 
should we hope to see this feature any time soon?

**Comment by GermanKiwi** [comment]
I'd also love to have the column preferences saved in the database, rather than in a cookie. For some reason I frequently find that my column preferences have been lost/reset, and it's super annoying to have to set them again all the time.

@snipe is there any chance to have this issue reopened?

**Comment by jmoldstad** [comment]
@snipe This would be greatly beneficial as things reset anytime we clear cookies, use another machine, or update Snipe it. Curious if we can get this opened up again as we have so many columns to adjust. Thanks for putting so much into this great tool, we really appreciate it!

**Comment by seederp2p** [comment]
I also would like to have this...

**Comment by snipe** [comment]
It’s much more difficult than it seems, so it’s not really on the short term roadmap at this time.

**Comment by seederp2p** [comment]
> It’s much more difficult than it seems, so it’s not really on the short term roadmap at this time.

I understand! :)

And what about setting the default columns for ALL the users? :)

**Comment by Brad-Watts** [comment]
Bump - we have a large company using this software with many users, on many computers, almost no one uses the same computer twice.
it would be amazing to be able to set this per user, or at least across all users.

Interesting to see this has been a request for 7 years

**Comment by MasterCakeX5** [comment]
I would like to bump this as well. Having more flexibility to:

- save views on the server (cookie settings dont work here for whatever reason with multiple users)
- change column positions
- do all of this per user/category/etc

would be very appreciated

**Comment by BSKilglass** [comment]
+1

**Comment by byebb** [comment]
+1

**Comment by Kvoo** [comment]
+1

**Comment by WADPH** [comment]
+1

**Comment by AsimAJ33** [comment]
+1

**Comment by FILINSI** [comment]
+1
