### ISSUE TITLE
Service Tag case is sensitive

### ISSUE THREAD

**Issue by tx7** [snipe/snipe-it#3242]
Hello,

I just found an issue in Snipe-It 3.6.2 yesterday at work that service tag is case sensitive.
The system is differentiate the two entries with same service tag but one with lower case and the other one is upper case as two entries. Therefore, it should be non-case sensitive.

version 3.6.2.
Not sure if this is fix in v3.6.3.

Thanks.

**Comment by snipe** [comment]
I'm not sure how that's possible, since MySQL isn't case sensitive against searches.

**Comment by tx7** [comment]
Not in searching, but in asset creation.
