### ISSUE TITLE
apache2 core dump getting generated during checkin and checkout of assets

### ISSUE THREAD

**Issue by tushu1232** [snipe/snipe-it#3244]
#### Expected Behavior (or desired behavior if a feature request)
Checkin and Checkout of asset should send a mail to the user and come out clean without any errors
(what you expect to happen goes here)

-----

#### Actual Behavior

The apache2 server is core dumping during checkin and checkout of asset.We were able to capture the core dump during this activity and gdb debug of the dump is available below
root@snipeit:/tmp/apache2dump# gdb apache2 -core /tmp/apache2dump/core
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from apache2...Reading symbols from /usr/lib/debug//usr/sbin/apache2...done.
done.
[New LWP 63291]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

warning: the debug information found in "/usr/lib/debug//usr/lib/php5/20121212/mysql.so" does not match "/usr/lib/php5/20121212/mysql.so" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug/usr/lib/php5/20121212/mysql.so" does not match "/usr/lib/php5/20121212/mysql.so" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib/php5/20121212/mysqli.so" does not match "/usr/lib/php5/20121212/mysqli.so" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug/usr/lib/php5/20121212/mysqli.so" does not match "/usr/lib/php5/20121212/mysqli.so" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib/php5/20121212/pdo_mysql.so" does not match "/usr/lib/php5/20121212/pdo_mysql.so" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug/usr/lib/php5/20121212/pdo_mysql.so" does not match "/usr/lib/php5/20121212/pdo_mysql.so" (CRC mismatch).

Core was generated by `/usr/sbin/apache2 -k start'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  zval_delref_p (pz=<optimized out>) at /build/php5-vefi3m/php5-5.5.9+dfsg/Zend/zend.h:409
409	/build/php5-vefi3m/php5-5.5.9+dfsg/Zend/zend.h: No such file or directory.
(gdb) exit

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 

- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
   v3.6.3 build 15 (g1bf34d7)
- What OS and web server you're running Snipe-IT on
    14.04.1-Ubuntu
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
    No error it just goes blank
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
   http://IP-addrr/hardware/21/checkin
- If a stacktrace is provided in the error, include that too.
     Yes Please check above.
- Any errors that appear in your browser's error console.
   No
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
  No
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
    [Mon Jan 30 11:14:41.377973 2017] [core:notice] [pid 63420] AH00051: child pid 63425 exit signal Segmentation fault (11), possible coredump in /tmp/apache2dump

- Include what you've done so far in the installation, and if you got any error messages along the way.
  No
- Indicate whether or not you've manually edited any data directly in the database
 No

**Comment by snipe** [comment]
Is there anything in your laravel log?
