### ISSUE TITLE
Issues While Importing Bulk Assets

### ISSUE THREAD

**Issue by irahul91** [snipe/snipe-it#3247]
i have recently started using Snipe IT and i am facing issues while importing bulk Assets.

I imported the file in .csv format and every thing seems to be fine but when i check the assets tab, few of the columns seems to be missing\empty.

Is there any fix for this as it would be a big headache entering values for the missing columns manually.

**Comment by snipe** [comment]
You're going to have to give us a little more detail. What field are missing? What were their values in the CSV, etc

**Comment by irahul91** [comment]
So i have entered  the values in **Asset Name** and **Serial** column in the psv file that i imported but it is not showing in the Asset list of the SnipeIT application.

Please see the attached screenshot of both the psv file and the application with missing data.

Also the **model** field is showing Unknown even after entering the value.

![csv file with data](https://cloud.githubusercontent.com/assets/25456487/22497074/58939144-e868-11e6-9a6d-d6659f014dc5.PNG)
![snipeit asset values missing](https://cloud.githubusercontent.com/assets/25456487/22497088/6fe2d1b6-e868-11e6-9131-ca296bfa215e.PNG)

**Comment by snipe** [comment]
You have to use the fields specified in the importing assets documentation (or use the CSV template there). https://snipe-it.readme.io/docs/importing
