### ISSUE TITLE
Upgrade v.3.0 to v.3.6.3

### ISSUE THREAD

**Issue by elJoeyJojo** [snipe/snipe-it#3248]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

I'd like to upgrade Snipe-It
-----

#### Actual Behavior

(what actually happens goes here)

I follow all instructions and everything works well, (though I did need to make changes to the database.php as it was using some 'forge' account/database and mine is clearly using 'snipeit' for both database name and user

When I ran php artisan migrate, it seemed to have migrated just fine: 
 Do you really wish to run this command? (yes/no) [no]:
 > yes

Couldn't find matching Action log row when trying to migrate  filename from asset log:
LogDate2016-08-18 10:56:09 LogForAsset:2524LogNote:
Migrated: 2016_07_13_150015_add_is_ad_to_settings
Migrated: 2016_07_14_153609_add_ad_domain_to_settings
Migrated: 2016_07_22_003348_fix_custom_fields_regex_stuff
Migrated: 2016_07_22_054850_one_more_mac_addr_fix
Migrated: 2016_07_22_143045_add_port_to_ldap_settings
Migrated: 2016_07_22_153432_add_tls_to_ldap_settings
Migrated: 2016_07_27_211034_add_zerofill_to_settings
Migrated: 2016_08_02_124944_add_color_to_statuslabel
Migrated: 2016_08_04_134500_add_disallow_ldap_pw_sync_to_settings
Migrated: 2016_08_09_002225_add_manufacturer_to_licenses
Migrated: 2016_08_12_121613_add_manufacturer_to_accessories_table
Migrated: 2016_08_23_143353_add_new_fields_to_custom_fields
Migrated: 2016_08_23_145619_add_show_in_nav_to_status_labels
Migrated: 2016_08_30_084634_make_purchase_cost_nullable
Migrated: 2016_09_01_141051_add_requestable_to_asset_model
Migrated: 2016_09_02_001448_create_checkout_requests_table
Migrated: 2016_09_04_180400_create_actionlog_table
Migrated: 2016_09_04_182149_migrate_asset_log_to_action_log
Migrated: 2016_09_19_235935_fix_fieldtype_for_target_type
Migrated: 2016_09_23_140722_fix_modelno_in_consumables_to_string
Migrated: 2016_09_28_231359_add_company_to_logs
Migrated: 2016_10_14_130709_fix_order_number_to_varchar
Migrated: 2016_10_16_015024_rename_modelno_to_model_number
Migrated: 2016_10_16_015211_rename_consumable_modelno_to_model_number
Migrated: 2016_10_16_143235_rename_model_note_to_notes
Migrated: 2016_10_16_165052_rename_component_total_qty_to_qty
Migrated: 2016_10_19_145520_fix_order_number_in_components_to_string
Migrated: 2016_10_27_151715_add_serial_to_components
Migrated: 2016_10_27_213251_increase_serial_field_capacity
Migrated: 2016_10_29_002724_enable_2fa_fields
Migrated: 2016_10_29_082408_add_signature_to_acceptance
Migrated: 2016_11_01_030818_fix_forgotten_filename_in_action_logs
Migrated: 2016_11_13_020954_rename_component_serial_number_to_serial
Migrated: 2016_11_16_172119_increase_purchase_cost_size
Migrated: 2016_11_17_161317_longer_state_field_in_location
Migrated: 2016_11_17_193706_add_model_number_to_accessories
Migrated: 2016_11_24_160405_add_missing_target_type_to_logs_table
Migrated: 2016_12_07_173720_increase_size_of_state_in_suppliers

so then I cleared php artisan config:clear config:cache and it clears just fine.

My /etc/httpd/conf.d/snipeit.conf file is as follows: (new Snipe-It folder is under /opt and it was renamed snipe-it-new so I change it here but when I restart nginx I get a http 500 error.

<VirtualHost *:80>
    <Directory /opt/snipe-it-new/public>
        Allow From All
        AllowOverride All
        Options +Indexes
    </Directory>
    DocumentRoot /opt/snipe-it-new/public
    ServerName snipeit.dhxmedia.com
</VirtualHost>

If I switch the Document Root and Directory to /opt/snipe-it/public then Snipe It works instantly so there is something I'm missing.

Also my folder under /opt/snipe-it-new has the following permissions and ownership (same as /opt/snipe-it)

drwxr-xr-x  7 apache  apache  4096 Jan 31 09:00 .
drwxr-xr-x 14 snipeit snipeit 4096 Jan 31 09:17 ..
drwxr-xr-x  3 apache  apache  4096 Jan 31 09:00 app
drwxr-xr-x  2 apache  apache  4096 Jan 31 09:00 debugbar
drwxr-xr-x  5 apache  apache  4096 Jan 31 09:00 framework
drwxr-xr-x  2 apache  apache  4096 Jan 31 09:31 logs
drwxr-xr-x  8 apache  apache  4096 Jan 31 09:00 private_uploads

but doesn't seem to work. What am I doing wrong? 
----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v.3.0
- What OS and web server you're running Snipe-IT on - CentOS 6.8
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - 
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. HTTP ERROR 500
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by elJoeyJojo** [comment]
i got this from the httpd error log

[Tue Jan 31 10:19:50 2017] [error] [client 10.12.8.195] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/opt/snipe-it-new/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied' in /opt/snipe-it-new/bootstrap/cache/compiled.php:13906\nStack trace:\n#0 /opt/snipe-it-new/bootstrap/cache/compiled.php(13836): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /opt/snipe-it-new/bootstrap/cache/compiled.php(13596): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /opt/snipe-it-new/bootstrap/cache/compiled.php(13694): Monolog\\Logger->addRecord(400, Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#3 /opt/snipe-it-new/bootstrap/cache/compiled.php(13389): Monolog\\Logger->error(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#4 /opt/snipe-it-new/bootstrap/cache/compiled.php(13360): Illuminate\\Log\\Writer->writeLog('error', Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#5 /opt/snipe-it-new/vendor/laravel/framework/src/Illuminate/Foundation/E in /opt/snipe-it-new/bootstrap/cache/compiled.php on line 13906

**Comment by elJoeyJojo** [comment]
I changed that file "laravel.log" to have apache:apache ownership and I don't get that HTTP ERROR 500 anymore but it goes to "whoops something went wrong" : S

**Comment by VanillaNinjaD** [comment]
Have you update your "APP_URL" to the new directory inside your .env file in the Snipe-IT directory?

**Comment by elJoeyJojo** [comment]
@VanillaNinjaD hey, thanks! where is this file? sorry I didn't even know i had to make a change anywhere else.

**Comment by elJoeyJojo** [comment]
@VanillaNinjaD I see the docker.env file so let me try to change that and see if that works

**Comment by VanillaNinjaD** [comment]
copy the .env file from your old Snipe-IT install directory to the new one and update the "APP_URL" inside that file

**Comment by VanillaNinjaD** [comment]
Here is more detail on the .env file

https://snipe-it.readme.io/docs/configuration

**Comment by elJoeyJojo** [comment]
@VanillaNinjaD found that hidden .env file and copied it to the new Snipe-IT directory the APP_URL inside the file is set to null, tried localhost, tried http://servername.domain.com and, restarted nginx and same thing. I get a "whoops, looks like something went wrong". The hidden file .env has same permissions too

**Comment by elJoeyJojo** [comment]
# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=f2QOYFnYsr9CqPiJ9ovno2HgKm5smTzO
APP_URL=null
APP_TIMEZONE='America/Vancouver'
APP_LOCALE=en


# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=snipeit
DB_USERNAME=snipeit
DB_PASSWORD=comemything
DB_PREFIX=null
DB_DUMP_PATH='/usr/bin'

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=outlook.domain.com
MAIL_PORT=587
MAIL_USERNAME=admin
MAIL_PASSWORD=*******
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=snipe.it@domain.com
MAIL_FROM_NAME=Snipe-IT


# --------------------------------------------
# REQUIRED: IMAGE LIBRARY
# This should be gd or imagick
# --------------------------------------------
IMAGE_LIB=gd


# --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME=snipeit_session
COOKIE_DOMAIN=null
SECURE_COOKIES=false


# --------------------------------------------
# OPTIONAL: CACHE SETTINGS
# --------------------------------------------
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

**Comment by snipe** [comment]
We need the output in the error logs to see what the whoops error is

**Comment by elJoeyJojo** [comment]
nginx show no error logs since i changed that laravel.log to apache ownership, now that log file laravel.log file is showing this error:

[2017-01-31 19:27:32] production.ERROR: exception 'ErrorException' with message 'mcrypt_encrypt(): Key of size 0 not supported by this algorithm. Only keys of sizes 16, 24 or 32 supported' in /opt/snipe-it-new/vendor/laravel/framework/src/Illuminate/Encryption/McryptEncrypter.php:104
Stack trace:

Any other place for Snipe-IT logs? I don't see anything on nginx ever since I changed that laravel.log file to the correct ownership

**Comment by elJoeyJojo** [comment]
this is line 104 on both Snipe IT directories both identical, 
return mcrypt_encrypt($this->cipher, $this->key, $value, MCRYPT_MODE_CBC, $iv);
return mcrypt_encrypt($this->cipher, $this->key, $value, MCRYPT_MODE_CBC, $iv);

**Comment by snipe** [comment]
Does your .env have an APP_KEY?

**Comment by elJoeyJojo** [comment]
@snipe I do have an APP_KEY and it matches the same .env file in the new Snipe IT Directory

**Comment by elJoeyJojo** [comment]
@snipe is there a way to import the database into a new installation of Snipe-IT? I've been trying to upgrade for a while and every time I try I seem to get stuck somewhere. This is the furthest I made it though but it would be nice to get the latest version and I don't mind setting up another server for Snipe It if I can import all of the data somehow.

**Comment by jmathias59** [comment]
Backup utility is under Admin menu.  Restore is done with sql commands, search web for instructions.
Two directories need to be manually copied: public/uploads and storage/private_uploads. These are not included in the sql zip file.

James

**Comment by ITNetMan** [comment]
Not that it helps you out in doing the 3.0 to 3.6.3 update, but I actually ran into the same issue when I tried doing a straight through update with the 500 Error just a few days ago running Snipe-IT on a Windows Server 2012 box.

Instead of trying to figure it out, I instead rolled back my instance to pre-update, and then I did all the incremental stable updates going up to 3.6.3.  Updating this way worked fine with no 500 Error that came through at any step of the way.  Of course it is a bunch of time to recursively keep doing the small updates, but that will probably work if you want to get up to date.

**Comment by snipe** [comment]
It shouldn't be necessary to do incremental updates like that though. What was your previous 500 error?

**Comment by ITNetMan** [comment]
I unfortunately didn't do any tracing or capture any extra logs before I just went through incrementals, but here's the little that's in the IIS logs below.  It shows a 500.19 error which is just some invalid configuration data.

2017-01-27 21:55:05 10.x.x.x GET /login - 443 - 10.x.x.x Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/55.0.2883.87+Safari/537.36 - **500 19** 3 1645

2017-01-27 21:55:05 10.x.x.x GET /favicon.ico - 443 - 10.x.x.x Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/55.0.2883.87+Safari/537.36 https://snipe-it.xxxxxxx.xxxx/login **500 19** 3 54

**Comment by elJoeyJojo** [comment]
So @ITNetMan gave me an idea, I thought I would upgrade PHP in my CentOS vm, and it worked like a charm! : S I'm still using php5.6 though, now the only thing that stopped working was LDAP, trying to figure that out

**Comment by elJoeyJojo** [comment]
so this new upgrade caused my LDAP not to work, settings are the same and when you click "test LDAP" it works so not sure what I have to change

![image](https://cloud.githubusercontent.com/assets/17091968/22527316/8cfa7cde-e883-11e6-97a1-8c1e36d23566.png)

**Comment by VanillaNinjaD** [comment]
@elJoeyJojo it appears that you are LDAP authenticating to Active Directory. If that is true, click the "This is an Active Directory server" box at the top of the LDAP settings

**Comment by elJoeyJojo** [comment]
@VanillaNinjaD right you are!!! it was confusing 'cause it saids, "this is" an AD Server, I thought it was talking about SnipeIT itself :P

**Comment by elJoeyJojo** [comment]
thank you everyone! @snipe THANKS SNIPE! you guys are awesome

**Comment by snipe** [comment]
![adventure-time-dance-party](https://cloud.githubusercontent.com/assets/197404/22529589/e09207c8-e88c-11e6-931f-6e819861d9bd.gif)
