### ISSUE TITLE
Searching Assets/Hardware etc..

### ISSUE THREAD

**Issue by elJoeyJojo** [snipe/snipe-it#3249]
#### Expected Behavior (or desired behavior if a feature request)

I want to be able to search by username, asset, model etc...
-----

#### Actual Behavior

I can't seem to search all assets anymore, anything I type just resets to all assets. I used to be able to search by username, model, vendor etc...

If I go to categories then I can find all laptops but typing it in the search bar in "all assets" doesn't search anymore. I did try to upgrade to v.3.8.3 and ran the migrate commands but haven't been successful, would that have anything to do with the issues I am seeing in v.3.0 now? I have to 2 folders in /opt
snipe-it and snipe-it-new but my nginx snipeit.conf file is pointing to snipe-it

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v.3.0
- What OS and web server you're running Snipe-IT on - CentOS 6.8
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual Installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Please provide error logs from storage/logs/laravel.log

**Comment by elJoeyJojo** [comment]
this is what i see in the log when I try to search "Anthony" based on a user

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'models.modelno' in 'where clause' (SQL: select count(*) as aggregate from `assets` inner join `models` on `assets`.`model_id` = `models`.`id` inner join `categories` on `models`.`category_id` = `categories`.`id` where `physical` = 1 and (exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `categories` where `models`.`category_id` = `categories`.`id` and (`categories`.`name` LIKE %Anthony% or `models`.`name` LIKE %Anthony% or `models`.`modelno` LIKE %Anthony%) and `categories`.`deleted_at` is null)) or exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `manufacturers` where `models`.`manufacturer_id` = `manufacturers`.`id` and (`manufacturers`.`name` LIKE %Anthony%) and `manufacturers`.`deleted_at` is null)) or (exists (select * from `status_labels` where `assets`.`status_id` = `status_labels`.`id` and `status_labels`.`name` LIKE %Anthony% and `status_labels`.`deleted_at` is null)) or (exists (select * from `companies` where `assets`.`company_id` = `companies`.`id` and `companies`.`name` LIKE %Anthony%)) or (exists (select * from `locations` where `assets`.`rtd_location_id` = `locations`.`id` and `locations`.`name` LIKE %Anthony% and `locations`.`deleted_at` is null)) or (exists (select * from `users` where `assets`.`assigned_to` = `users`.`id` and (`users`.`first_name` LIKE %Anthony% or `users`.`last_name` LIKE %Anthony% or (exists (select * from `locations` where `users`.`location_id` = `locations`.`id` and `locations`.`name` LIKE %Anthony%))))) or `assets`.`name` LIKE %Anthony% or `assets`.`asset_tag` LIKE %Anthony% or `assets`.`serial` LIKE %Anthony% or `assets`.`order_number` LIKE %Anthony% or `assets`.`notes` LIKE %Anthony% or `_snipeit_mac_address` LIKE %Anthony%) and `assets`.`deleted_at` is null order by `categories`.`name` asc)' in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php:713
Stack trace:

**Comment by elJoeyJojo** [comment]
since i managed to upgrade to v3.6 I no longer have this issue! basically after you run the php artisan migrate, it causes the search to stop working on the current snipe-it directory! once i moved the nginx config/document root to the new Snipe It directory the search now works flawlessly
