### ISSUE TITLE
Automatic backups on windows installation

### ISSUE THREAD

**Issue by bagetsro** [snipe/snipe-it#3250]
i have read a thread on how to make automatic backups using cron jobs https://github.com/snipe/snipe-it/issues/2453
and found this on the documentation https://snipe-it.readme.io/docs/configuring-alerts-backups
but it may be a little confusing for me as i dont have knowledge on cron jobs in windows. would someone educated me on how to do automatic backups in windows? thanks.

**Comment by jmathias59** [comment]
What server OS are you running?  You might need to add the Windows Server Backup feature.  The GUI interface allows a scheduled backup either Once a Day or Multiple time per Day.  If you want to schedule backups once a week –
Configure Automatic Backups with Task Scheduler
http://technet.microsoft.com/en-us/library/dd834883.aspx

**Comment by huyem83** [comment]
Use task scheduler

![1](https://cloud.githubusercontent.com/assets/6405334/22525025/74fd35da-e87a-11e6-886d-941b8d00599c.jpg)

![2](https://cloud.githubusercontent.com/assets/6405334/22525030/77c67fc4-e87a-11e6-8c76-1eecaedd5143.jpg)

**Comment by bagetsro** [comment]
@jmathias59 
im using windows 7. would appreciate it if you could include what to put in the parameters to backup specifically my snipe IT.

@huyem83 
im using iis 7. is my setting for the action correct?
![image](https://cloud.githubusercontent.com/assets/20238789/22532775/5bd79f5a-e924-11e6-93e0-41d9f74d1ca9.png)

my "Start in" parameters is C:\inetpub\wwwroot\snipe-it\storage\app\backups

**Comment by huyem83** [comment]
Make sure that you can backup from the admin menu first.  Your start in should be C:\inetpub\wwwroot\snipe-it\

**Comment by bagetsro** [comment]
@huyem83 
yes i can backup from the admin menu.
after changing the start in to what you gave, it worked! thank you so much!
