### ISSUE TITLE
Export Assets to CSV

### ISSUE THREAD

**Issue by Dreadles** [snipe/snipe-it#3255]
#### Expected Behavior (or desired behavior if a feature request)

Reports > Asset Report

Expect to be able to filter or add columns to the view, then click Download > Export to CSV Excel etc...
If the filter or view on the webpage contained more than 1 page of assets (200 is the most), expect that file to contain all items that were displayed in the view

-----

#### Actual Behavior

Exported file contains just the first page from the view that you had on the webpage. In my case only 200 assets are shown in the exported CSV even though there were over 1000 in the webpage view.
Webpage then renders again and the "Next Page" button is no longer there.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.6.3 build 15 (g1bf34d7)

- What OS and web server you're running Snipe-IT on
Centos 7

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Use the custom asset report.

**Comment by Mizuuuuuuu** [comment]
> Use the custom asset report.

I would like to export a complete export of all Snipe IT assets as a csv file. As described in the linked problem, I have the same problem. Now unfortunately the Custom Asset Report does not help because I have over 1000 assets and with Custom Assets Report only 450 are exported. So that's not all of them. Can you please help me?

Greetings,
Mizu

**Comment by timurkun** [comment]
+1 for this issue. Some workaround would be great (via artisan command maybe)
