### ISSUE TITLE
Export snipe-it user data (username + email + password) to another database 

### ISSUE THREAD

**Issue by Beslinda** [snipe/snipe-it#3256]
#### Expected Behavior (or desired behavior if a feature request)

#Question: 
Is there a way to export snipe-it user data (username + email + password  ..etc) to another database that will be used by the RADIUS since I want make users to use the same credentials to authenticate to the network too.

**Comment by snipe** [comment]
Passwords are hashed in the database, so you can't really use them that way. A better idea would be to wait until v4 is out, where you can use the API.
