### ISSUE TITLE
Could not bind to LDAP

### ISSUE THREAD

**Issue by zempm** [snipe/snipe-it#3257]
#### Expected Behavior (or desired behavior if a feature request)
Expected 

-----

#### Actual Behavior
If I test the LDAP Connection I get the following error:
Could not bind to LDAP: Can't contact LDAP server 

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.6.3
- What OS and web server you're running Snipe-IT on: 
CentOS 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): 
manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: 
Could not bind to LDAP: Can't contact LDAP server 
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: 
Settings --> General Settings --> Test LDAP 
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
[2017-02-02 15:55:50] production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory  
[2017-02-02 15:56:16] production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory  

- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
No

<img src="http://www2.pic-upload.de/img/32605272/02-02-201715-58-19.jpg" >

We can connect to our Active Directory Server with ldapsearch on our server. (works)
With the Snipe-IT Webinterface the following error:
Could not bind to LDAP: Can't contact LDAP server  --> doesn't work 
Tried to use the IP instead of the hostname --> doesn't work
Enable / Disable "This is an Active Directory server" --> doesn't work
Enable / Disable "LDAP Password Sync " --> doesn't work

Any Ideas?

**Comment by miiccka** [comment]
Hello Zempm,

For the LDAP Bind Username, did you test "username@your.domain" ?

**Comment by zempm** [comment]
I tested this now. Same error: Could not bind to LDAP: Can't contact LDAP server

**Comment by miiccka** [comment]
My working config :

![image](https://cloud.githubusercontent.com/assets/25509300/22559228/c76b7a7e-e970-11e6-8853-81d1083e95a3.png)

**Comment by zempm** [comment]
I tried to connect with the ip (LDAP Server) --> doesn't work
Rest is similar to you. Doesn't work :(

But thanks for your infos!

**Comment by snipe** [comment]
If it can't contact the LDAP server but you're sure the name/IP is correct, this usually means that there is a firewall rule preventing the Snipe-IT server from being able to reach the LDAP server. Talk to your LDAP/network admin and ask them to whitelist the Snipe-IT server IP.

**Comment by zempm** [comment]
Problem solved.

I unblocked it with:
``setsebool -P httpd_can_network_connect 1``
