### ISSUE TITLE
Unable to bind Active Directory

### ISSUE THREAD

**Issue by cptkelevra** [snipe/snipe-it#3259]
#### Expected Behavior (or desired behavior if a feature request)

Enter ldap settings and bind/sync with ad
-----

#### Actual Behavior

Test connection fails and login screen brings up an error of, "Whoops! Looks like Something went wrong."

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ *] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - 3.6.3 build 15 (g1bf34d7)
- What OS and web server you're running Snipe-IT on - Centos7, apache 2.4
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - yum
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - no

**Comment by snipe** [comment]
Please enable debug, or provide us with the error logs, per the getting help documentation.

**Comment by cptkelevra** [comment]
So, have since fixed this and gotten pass the bind issue, but am curious about authentication. Once it has imported our active directory users, should they or should they not be able to log in with their ad credentials?

-- Brandon Jeanpierre
1568 S. 900 W.
Salt Lake City, UT 84104
brandon.jeanpierre@hotmail.com<mailto:Brandon.jeanpierre@hotmail.com>
(209) 324-0431

**Comment by snipe** [comment]
If your LDAP Auth query is correct, they should be able to login using their AD credentials.

**Comment by cptkelevra** [comment]
Ok, so now have managed to fix the auth query, was able to import users from active directory, but purged the records that were imported. When trying to import again, it shows that it succeeded, but I can not see any other users beside myself and the other person working on this. Is there some sort of cache that needs to be refreshed in order for us to get a fresh start on importing users?

-- Brandon Jeanpierre
1568 S. 900 W.
Salt Lake City, UT 84104
brandon.jeanpierre@hotmail.com<mailto:Brandon.jeanpierre@hotmail.com>
(209) 324-0431

**Comment by cptkelevra** [comment]
Starting with a fresh install, we are able to bind to AD with no issue, but when trying to import users, it returns no errors and shows a successful import, but does not show any users in the list of people. Any suggestions?

**Comment by cptkelevra** [comment]
also, where are error logs located?

**Comment by brianjking** [comment]
@cptkelevra [Read the docs](https://snipe-it.readme.io/docs/getting-help#section-step-3-check-your-app-and-server-logs) re: logs.

**Comment by cptkelevra** [comment]
Got it. Thanks. You can makred this as resolved.

-- Brandon Jeanpierre
1568 S. 900 W.
Salt Lake City, UT 84104
brandon.jeanpierre@hotmail.com<mailto:Brandon.jeanpierre@hotmail.com>
(209) 324-0431
