### ISSUE TITLE
uploaded images not loading plus error with webfonts

### ISSUE THREAD

**Issue by dooley1023** [snipe/snipe-it#3260]
#### Expected Behavior (or desired behavior if a feature request)
upload image and for the image to be used as logo or asset picture etc...

-----

#### Actual Behavior
getting the normal image not found depiction of square box with an x through it.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v3.6.3 build 15 (g1bf34d7) 
- What OS and web server you're running Snipe-IT on -  Windows 7 Running IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual install following documented instructions on the installation documentation.
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - no errors shown - none
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - any of them
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

any page that would show an uploaded image does not display.
console shows these errors below 
i have commented in internal ip for the actual ip below.
index.php:610 GET http://"internal ip"/assets/fonts/fontawesome-webfont.woff2?v=4.5.0 
index.php:610 GET http://"internal ip"/assets/fonts/fontawesome-webfont.woff?v=4.5.0 
index.php:207 GET http://gravatar.com/avatar/f9ac02120ef4d8b4fbd0169710a7f038 304 (Not Modified).
no errors during installation. 
i did look at app.php to ensure that app url is correct and it is set to http://"internal ip".
IIS is set to c$\inetpub\wwwroot\snipeit\public as the root. 
i have checked the the folder public/uploads does have write access provided to iusr
when i specifically inspect an element that should be displaying i receive the follow (from the company logo for example)<img class="navbar-brand-img" src="http://"internal-ip"/index.php/uploads/logo.jpg">

​

**Comment by snipe** [comment]
`http://"internal-ip"/index.php/uploads/logo.jpg` <-- that is incorrect. Shoud not have an index.php at the end

**Comment by dooley1023** [comment]
huh odd i wonder why i hadnt seen that as that is very obvious :(. 
but i am not seeing where index.php has been indicated in any of the files.

**Comment by snipe** [comment]
What's your APP_URL in your .env?

**Comment by dooley1023** [comment]
and that was it

**Comment by dooley1023** [comment]
thank you so much, wonderful product btw!!!

**Comment by snipe** [comment]
![birthday-excited](https://cloud.githubusercontent.com/assets/197404/22571453/a375c258-e954-11e6-806e-fb087af3160d.gif)
