### ISSUE TITLE
Licenses Tab not showing any licenses

### ISSUE THREAD

**Issue by jacksjp** [snipe/snipe-it#3263]
#### Expected Behavior (or desired behavior if a feature request)

When I click on the license Tab, I am expecting it would list all the licenses that is updated. The license show up on Dashboard.

-----

#### Actual Behavior

It shows no Licenses. 

![snipe it dashboard](https://cloud.githubusercontent.com/assets/25318303/22578721/e14aa0ca-e9f0-11e6-8d33-d0f92f7fcfcd.JPG)

![snipe it software tab](https://cloud.githubusercontent.com/assets/25318303/22578719/dc1c3c26-e9f0-11e6-8a4b-e09a74e966e9.JPG)

-----

#### Please confirm you have done the following before posting your bug report:

- [Y] I have enabled debug mode
- [Y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v3.6.3 
- What OS and web server you're running Snipe-IT on - Ubuntu 16.04, PHP 5.6
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - No Error on browser
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Licenses TAB
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. - No
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). - Yes
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. - None
- Include what you've done so far in the installation, and if you got any error messages along the way. - I have installed the app, installed PHP-Ldap and intergrated with AD. there were few redirection issues, fixed those manually. 
- Indicate whether or not you've manually edited any data directly in the database - No

**Comment by snipe** [comment]
You have a search term ("Tableau") in your search box. There are no matching results. If you clear the search term, you will see it.

**Comment by jacksjp** [comment]
I have cleared the term, still nothing is showing up. 

![snipe it software tab](https://cloud.githubusercontent.com/assets/25318303/22580831/b07d1660-ea01-11e6-8388-34472656b7a1.JPG)
