### ISSUE TITLE
Incorrect QR Code displayed on asset details webpage.

### ISSUE THREAD

**Issue by sydit** [snipe/snipe-it#3264]
#### Expected Behavior (or desired behavior if a feature request)

QR Code scanning gives correct  web link
-----

#### Actual Behavior

When I scan the QR Code on "view asset" page or printed labels incorrect link is generated.

For example

Web Link for my first asset is _https://snipeit.xxxx.com/hardware/427/view_

But if I scan my first asset's QR Code I am getting  _https://snipeit.xxxx.com/hardware/41/view_ which doesnt exist.

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT - Version v3.6.3 build 15 (g1bf34d7)
- OS and web server- Ubuntu 14.04.5 LTS, NGINX
- Manual Snipe Install
-Not performed any manual DB editing.

**Comment by snipe** [comment]
Try deleting the contents of your public/uploads/barcodes directory

**Comment by sydit** [comment]
Thank you. It's working fine now :+1:
