### ISSUE TITLE
Updating from 3.3 to 3.6. access denied after update

### ISSUE THREAD

**Issue by bagetsro** [snipe/snipe-it#3265]
windows 7
IIS7
update from 3.3 - 3.6.3

Steps Taken to update
1. replaced everything of my current version (3.3) with 3.6 files.
2. run the commands
- composer install --no-dev --prefer-source
- php artisan config:clear
- composer dump-autoload
- php artisan migrate
- php artisan view:clear
3. everything went fine execpt when i ran the first command i got this error on the end
![image](https://cloud.githubusercontent.com/assets/20238789/22585629/a4282a9e-ea33-11e6-8a57-93392c91cd36.png)

4. i decided it was not of a big deal and proceed with the other commands.
5. after updating i get this error upon logging in
![image](https://cloud.githubusercontent.com/assets/20238789/22585693/02b4c310-ea34-11e6-98be-9820fcea065c.png)

6. i have ldap enabled and connected with our active directory.

**Comment by snipe** [comment]
c3 error can be ignored. 

Forbidden error is because your document root is wrong and it's trying to list files int he directory.

**Comment by bagetsro** [comment]
how can i correct it? working fine before the update.

**Comment by snipe** [comment]
Set the document root to the public directory.

**Comment by bagetsro** [comment]
@snipe sorry for being dumb regarding this, but how will i be able to do that? document root in IIS?

the login page works but upon logging in i get that error.
![image](https://cloud.githubusercontent.com/assets/20238789/22586165/367c95b8-ea36-11e6-9f18-d90b705cfaef.png)

**Comment by snipe** [comment]
What's the URL of the page you get to when you login?

**Comment by snipe** [comment]
Nevermind, I see it in the other screenshot.

**Comment by snipe** [comment]
Is it possible you left out some files when upgrading? Can you check that index.php is set as a default directory index?

**Comment by snipe** [comment]
(That's a server-level forbidden error, not from Snipe-IT, so something with your server config must be wrong, or there are some files missing, I think.)

**Comment by snipe** [comment]
Possible insights here:
https://laracasts.com/discuss/channels/servers/iis-8-laravel-webconfig

**Comment by bagetsro** [comment]
@snipe im pretty sure i copied everything. It's just the main url that cannot be access. if i put something like /admin (http://gdcasset.fpi.sea.css.fujitsu.com/admin) on the url, it will work. it's just the http://gdcasset.fpi.sea.css.fujitsu.com main url that is having the error. 

i have this set on my physical path in IIS7 just like before i updated.
![image](https://cloud.githubusercontent.com/assets/20238789/22586537/4291781c-ea38-11e6-9796-6529c67e2c41.png)

**Comment by snipe** [comment]
I'm honestly not sure then. Maybe someone with more IIS experience can help.

**Comment by avary69** [comment]
I had a similar issue upgrading from 3.6.2 to 3.6.3.
Running composer install --no-dev --prefer-source gives me the c3 error too, which in my opinion can't be ignored. The composer install removes a lot of directories first, but does not re-install them before it tries to access c3.php. So it is actually not exisiting at that moment. Hence the error.

My output was like this: 
C:\inetpub\wwwroot\snipe36>composer install --no-dev --prefer-source
Loading composer repositories with package information
Installing dependencies from lock file
  - Removing squizlabs/php_codesniffer (2.6.2)
  - Removing phpspec/phpspec (2.5.1)
  - Removing phpspec/php-diff (v1.0.2)
  - Removing mockery/mockery (0.9.5)
  - Removing hamcrest/hamcrest-php (v1.2.2)
  - Removing fzaninotto/faker (v1.6.0)
  - Removing codeception/codeception (2.1.11)
  - Removing facebook/webdriver (1.1.3)
  - Removing phpunit/phpunit (4.8.27)
  - Removing phpspec/prophecy (v1.6.1)
  - Removing phpdocumentor/reflection-docblock (3.1.0)
  - Removing phpdocumentor/type-resolver (0.2)
  - Removing phpdocumentor/reflection-common (1.0)
  - Removing webmozart/assert (1.1.0)
  - Removing phpunit/php-code-coverage (2.2.4)
  - Removing phpunit/php-token-stream (1.4.8)
  - Removing phpunit/php-file-iterator (1.4.1)
  - Removing phpunit/php-timer (1.0.8)
  - Removing phpunit/phpunit-mock-objects (2.3.8)
  - Removing doctrine/instantiator (1.0.5)
  - Removing phpunit/php-text-template (1.2.1)
  - Removing sebastian/comparator (1.2.0)
  - Removing sebastian/diff (1.4.1)
  - Removing sebastian/environment (1.3.8)
  - Removing sebastian/exporter (1.2.2)
  - Removing sebastian/recursion-context (1.0.2)
  - Removing sebastian/global-state (1.1.1)
  - Removing sebastian/version (1.0.6)
  - Removing symfony/browser-kit (v3.1.3)
  - Removing symfony/css-selector (v3.1.3)
  - Removing symfony/dom-crawler (v3.1.3)
  - Removing symfony/yaml (v3.1.3)
  - Removing codeception/c3 (2.0.7)
Generating autoload files

  [ErrorException]
  md5_file(C:\inetpub\wwwroot\snipe36\vendor\codeception\c3\c3.php): failed to open stream: No such file or directory
You can see that codeception/c3 was removed.
I ran "composer install" with no parameters. After that everything worked fine.

Just 1 question to @snipe: From 3.6.2 to 3.6.3 the migrate command told me nothing to migrate. Is that ok?
