### ISSUE TITLE
License tab - doesn't show any license

### ISSUE THREAD

**Issue by jacksjp** [snipe/snipe-it#3267]
Expected Behavior (or desired behavior if a feature request)

When I click on the license Tab, I am expecting it would list all the licenses that is updated. The license show up on Dashboard.

![screenshot from 2017-02-04 12-17-38](https://cloud.githubusercontent.com/assets/25318303/22616497/1652bc88-ead4-11e6-95b9-19da69bdc7c4.png)

Actual Behavior

License tab shows there is no licenses.

![screenshot from 2017-02-04 12-18-24](https://cloud.githubusercontent.com/assets/25318303/22616503/2d057574-ead4-11e6-9ee5-45728e73beb2.png)

snipe it software tab
Please confirm you have done the following before posting your bug report:

    [X] I have enabled debug mode
    [X] I have read checked the Common Issues page

Please provide answers to these questions before posting your bug report:

    Version of Snipe-IT you're running - v3.6.3
    What OS and web server you're running Snipe-IT on - Ubuntu 16.04, PHP 5.6, apache 2
    What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual
    WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - No Error on browser
    What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - 
    When I click on the License page, the page displays no information, Below is the log

   [2017-02-04 09:44:52] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function App\Http\Controllers\mb_strimwidth()' in /var/www/html/app/Http/Controllers/LicensesController.php:1008
Stack trace: #0 {main}  

    If a stacktrace is provided in the error, include that too.
    Any errors that appear in your browser's error console. - No
    Confirm whether the error is reproduceable on the demo. - Yes
    Include any additional information you can find in app/storage/logs and your webserver's logs. - None
    Include what you've done so far in the installation, and if you got any error messages along the way. - I have installed the app, installed PHP-Ldap and intergrated with AD. there were few redirection issues, fixed those manually.
    Indicate whether or not you've manually edited any data directly in the database - No

**Comment by snipe** [comment]
Install `mbstring`

http://php.net/manual/en/book.mbstring.php
