### ISSUE TITLE
How to change FQDN

### ISSUE THREAD

**Issue by StevenCeres** [snipe/snipe-it#3269]
I'm sorry for the n00b question,

I'm running snipe-it 3.6.3 on ubuntu 14.04, I need to change the server's FQDN, where do I have to look besides the .env config file?
I gave a look under /etc/apache2/sites-available but no luck, even trying to edit apache config files the sites doesnt respond anymore.
Someone can tell me which files need to be edited?
Thank you

**Comment by snipe** [comment]
Are you asking how to change it in Snipe-IT, or in Apache? Remember that you have to restart apache if you make any changes to the config there.

**Comment by StevenCeres** [comment]
Right, sorry, it worked!
