### ISSUE TITLE
Database import not importing in users

### ISSUE THREAD

**Issue by Drtrider** [snipe/snipe-it#3271]
#### Expected Behavior (or desired behavior if a feature request)
Imported SQL DB and expected users, assets, statues, etc to be imported form SQL backup.

-----

#### Actual Behavior

All was imported with the DB except my users.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
3.6.3
- What OS and web server you're running Snipe-IT on
CentOS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Users page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
I have not. I backed up the DB via the web GUI. I then moved the .zip to a new SnipeIT install on a different machine, and extracted the snipteit.sql and followed this guide: https://www.cyberciti.biz/faq/import-mysql-dumpfile-sql-datafile-into-my-database/

It seems all items are here but my users and some pictures.

**Comment by snipe** [comment]
Is the users data actually in the SQL dump?

**Comment by Drtrider** [comment]
Not sure. I'm pretty new to working with SQL databases, so excuse my ignorance here. 

How would one go about checking? Is there a config option somewhere for SnipeIT to control what is exported when backing up the DB?

**Comment by snipe** [comment]
No, it literally does a mysqldump and dumps the whole database. We don't offer any options and including or excluding tables. If you look in the SQL backup file, you should see (in amongst a whole bunch of noisy data) the SQL trying to create a users table and insert data. (You can try command+f'ing for 'users')

**Comment by Drtrider** [comment]
It seems like it's there, from what I can tell. The backup file has the following lines:
`LOCK TABLES `users` WRITE;
/*!40000 ALTER TABLE `users` DISABLE KEYS */;`

Follow by what looks like all of my users. Thoughts?

**Comment by Drtrider** [comment]
Just to mention, this is a DB transfer from one machine to another. I did some reading, and from what I understand the migration process is a bit different than just simply importing the DB on the new machine. 

Does anyone have any resources that can point me in the right direction? We were testing SnipeIT on a machine, and we need to move it to a different one on a different network. What sort of changes/items need to be brought over? Any guides on how to do something like this?
