### ISSUE TITLE
[Feature Request] Scheduled Backups

### ISSUE THREAD

**Issue by roycepope** [snipe/snipe-it#3272]
#### Expected Behavior (or desired behavior if a feature request)

It would be really nice to have a GUI front end that allows scheduled backups of my databases. This would basically automate the manual click of creating a backup. I wouldn't have to worry about remembering to click "Generate Backup" every month.

I suppose a workaround would be to just rsync the databases (heck even the whole /var/www/snipeit dir).

-----

Below is an example from another web application to give an idea of what I am looking for.
![backups](https://cloud.githubusercontent.com/assets/3598120/22667684/be50b4b8-ec72-11e6-9d5a-0558b68432bf.png)

**Comment by snipe** [comment]
We don't have permission to write to your cron tab or scheduled tasks, nor should we. If you just set up a cron job for it, it handles itself.

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/configuring-alerts-backups
