### ISSUE TITLE
Ready to Deploy is not loading user list, stuck on moving green circle

### ISSUE THREAD

**Issue by ado120** [snipe/snipe-it#3273]
#### Expected Behavior (or desired behavior if a feature request)

After putting asset details and setting Status to "Ready to Deploy" user checkout list should populate and allow me to choose a user

-----

#### Actual Behavior

I'm getting a green loading circle that stays moving indefinitely, not letting me check out to a user from the create new asset screen. Instead I have to save the asset without checking out, then go back into the edit asset screen later and check out from there. 
Screen shot of error here: 
![screen shot 2017-02-06 at 3 04 39 pm](https://cloud.githubusercontent.com/assets/24661977/22671698/884d9bb2-ec84-11e6-8ff0-fc829c755f3d.png)

What's funny is that everything was working about two days ago. Got the error, redid a ldap sync, went away for a day and now came back.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode: yes
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues): yes

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: Version v3.6.3 build 15 (g1bf34d7)
- What OS and web server you're running Snipe-IT on: Centos 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: Even with debug mode turned on I am not getting an error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Create new Asset, choosing Ready to Deploy for the status
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database: have not

**Comment by snipe** [comment]
> Any errors that appear in your browser's error console.

My guess is that your APP_URL is wrong, so the Ajax  isn't able to fire correctly

**Comment by abaalkh** [comment]
Can you check the browser console? What does it say?
Its probably what Snipe said.

**Comment by ado120** [comment]
Thank you both,

I changed the app_url and it seems to be working correctly now!
