### ISSUE TITLE
Exclude absolute paths from .zip backup file

### ISSUE THREAD

**Issue by ghost** [snipe/snipe-it#3277]
#### Expected Behavior (or desired behavior if a feature request)
I guess it's not a bug, just inconvenient behaviour.
After unzipping the backup in Ubuntu it makes sense to have this structure:
snipe-it.sql  
config
public
storage

Then I can just do:
`unzip snipe-latest.zip -d /var/www/snipe-it`

-----
#### Actual Behavior

After unzipping the backup in Ubuntu I get this structure:
snipe-it.sql  
/var/www/snipe-it/config
/var/www/snipe-it/public
/var/www/snipe-it/storage

This kind of `.zip` structure has aboslute paths inside and not relative ones. When I do unzip 
`unzip snipe-latest.zip -d /var/www/snipe-it` I get warning messages `warning:  stripped absolute path spec from /var/www/snipe-it/var/www/snipe-it/public/uploads/` for every file. This fails with Ansible because `unzip` can't strip the absolute directories and expects them to be relative.

Also this directory structure just doesn't make sense. If I made this: `unzip snipe-latest.zip -d /` I would end up with `snipeit.sql` inside my `/` directory.

Any chance I can change the backup structure and exclude `/var/www/snipe-it` prefix from it?

-----

#### Please confirm you have done the following before posting your bug report:
- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: **v3.6.2 build 18 (g6f1e0d6)**
- What OS and web server you're running Snipe-IT on: **Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-31-generic x86_64)**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): **manual**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: **no errors**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: **Backups page generates such zip files**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): **Yes**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by HinchK** [comment]
I ran into this issue as well; with regards to it's "fixability":

From a bash prompt and given a `/path/to/a/folder`,  fixing this behavior to relative-path style would mean `cd /path/to/a`  and `zip folder`.  This may be difficult as running commands through artisan (which is what we do for backups) we have to pass a reference to a non location-aware (e.g. pwd/popd aware) command handler and passing in the entire path to a resource makes all that a lot easier.

I'll see what I can do because, well, absolute paths are evil.
