### ISSUE TITLE
Label Template

### ISSUE THREAD

**Issue by miiccka** [snipe/snipe-it#3279]
Hello Community.
Is it possible to create our own label template?
I would like to add my company logo on it.

Thanks,

Michaël

**Comment by louisdj** [comment]
I don't think it is possible, I save the barcode and put it's into our Dymo label software so our logo is on it. But it should be easier when I could just print it from the asset manager.

**Comment by 3ter** [comment]
@louisdj Why do you think so? Has it been tried before?
I would love to have that feature too. Also to add some more fields than the three currently available.

**Comment by 3ter** [comment]
Oh, I understood this issue as a feature request.
Thanks for the clarification.
