### ISSUE TITLE
After creating an asset, page goes back to asset list showing empty

### ISSUE THREAD

**Issue by ado120** [snipe/snipe-it#3280]
#### Expected Behavior (or desired behavior if a feature request)

After creating an asset, it should go back to the asset list showing all assets without any of the columns filtered

-----

#### Actual Behavior

After creating an asset, it goes back to the list all view showing no assets with the "Expected Check In Date" column filtered, after clicking it again all assets will show. 

Screenshot attached:
![screen shot 2017-02-07 at 10 17 13 am](https://cloud.githubusercontent.com/assets/24661977/22706596/bda97d1c-ed24-11e6-852e-a516a67f2170.png)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: 3.6.3 build 15
- What OS and web server you're running Snipe-IT on: CentOS 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: Nothing shows in debug or browser console
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: List All View in Assets
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console: none
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): works as it should in the demo
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by ado120** [comment]
In fact,

Anytime I do a list all of the assets from whatever page I am on I will get the same error.

**Comment by snipe** [comment]
> Include any additional information you can find in app/storage/logs and your webserver's logs.

**Comment by ado120** [comment]
Can seem to find anything pertaining to the issue im getting in both of
those unfortunately

**Comment by ado120** [comment]
So when I switched to debug mode, restarted the docker container, problem went away. Switching back to Prod now the assets are not showing again with the filter screenshotted above. If I refresh the page everything loads up again..

**Comment by ernestasen** [comment]
I can confirm this is also happening for me. I will provide more info later.
