### ISSUE TITLE
Feature Request: Import Locations, Models, etc.

### ISSUE THREAD

**Issue by EQPShedrick** [snipe/snipe-it#3284]
currently transferring everything over from my current Asset Tracker and this would make life a million times easier!

**Comment by snipe** [comment]
If you use the asset importer, it will create locations, models, etc on the fly. https://snipe-it.readme.io/docs/importing

**Comment by EQPShedrick** [comment]
WOOT! Amazing stuff will work on that now then! Thanks a ton! Loving this so far cannot wait to dive deeper and start helping out more!
