### ISSUE TITLE
Enabling SSL

### ISSUE THREAD

**Issue by wicknet** [snipe/snipe-it#3287]
#### Expected Behavior (or desired behavior if a feature request)
Enabling SSL with user-supplied cert, key and chain certs

(what you expect to happen goes here)
There doesn't appear to be any clear, step-by-step documentation on how to do this on Apache on a plain vanilla ubuntu 16.04 install. Plain vanilla http works fine out of the box (after modifying DocumentRoot in Apache's 000-default.conf file) but after trying out suggestions from various sites on additng <VirtualHost *:443> section in the 000-default.conf file, changing the default-ssl.conf file with DocumentRoot and location of user-supplied certs and keys, nothing works.
-----

#### Actual Behavior
Any changes to files mentioned above results in breaking Apache and failure to reload 
(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
3.6.3 build 15
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04 and Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
https://snipeit.mydomain.com

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
no. Can the config files of the demo be made available?
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
No

This is a wonderful project with great potential. However, the lack of clear step-by-step instructions and lack of sample config files leave a lot to be desired.

**Comment by shoutinblues** [comment]
This sounds like an Apache problem, so I wouldn't expect Snipe-IT documentation to necessarily cover it.  Apache2 doesn't seem to allow more than one virtual host per .conf file.  You may need to concentrate on modifying default-ssl.conf if your server name and Snipe-IT site name are the same.

If your Snipe-IT site has a different name in DNS than the server itself, you will need separate .conf files for it, one for http and one for https.  Something like snipe-it.mydomain.com.conf and snipe-it.mydomain.ssl.conf.  Once those are in place in /etc/apache2/sites-available, you will use "a2ensite snipe-it.mydomain" and "a2ensite snipe-it.mydomain.ssl" to enable the sites.  To create the conf files, copy the default files and change the appropriate entries.

Here's what my ssl site conf file looks like:

#
# $Id: snipe-it.mydomain.com.ssl 2017-01-31 $
#

<VirtualHost *:443>
        <Directory /opt/www/snipe-it.mydomain.com/public>
                Options +Indexes
        </Directory>

        DocumentRoot /opt/www/snipe-it.mydomain.com/public
        ServerName snipe-it.mydomain.com

        SSLEngine on

       SSLCertificateFile      /etc/ssl/certs/server.crt
       SSLCertificateKeyFile /etc/ssl/private/server.key

</VirtualHost>

**Comment by shoutinblues** [comment]
`<VirtualHost *:443>
        <Directory /opt/www/snipe-it.mydomain.com/public>
                Options +Indexes
        </Directory>

        DocumentRoot /opt/www/snipe-it.mydomain.com/public
        ServerName snipe-it.mydomain.com

        SSLEngine on

       SSLCertificateFile      /etc/ssl/certs/server.crt
       SSLCertificateKeyFile /etc/ssl/private/server.key

</VirtualHost>


`

**Comment by wicknet** [comment]
@shoutinblues Thank you SO much for your suggestions. 

Our setup is as follows:

Ubuntu 16.04 server with all updates. Standard snipe-it install performed with one host on Apache. Site works fine on http://snipeit.mydomain.org. Server's hostname is "snipeit" and internal DNS resolves the site (http://snipeit.mydomain.org) to the server IP. I have other Ubuntu LAMP servers running secure websites with user-supplied SSL certs/keys with no problems - I think the issue here is the conf and env files for snipe-it are interacting with the Apache confs in ways that are unusual (at least to me), which is why I'm surprised at the lack of clear documentation dealing with enabling SSL on Apache FOR snipe-it installs. 

If it helps you to troubleshoot, here are the outputs of my 000-default.conf and snipeit.conf files as well the .env file. I have played extensively with changing the ports to https, adding SSLEngine and SSLCertficateFile/Key pointers to my files but to no avail.  ANY help you can provide to get this site working with SSL would be deeply appreciated.

root@snipeit:/etc/apache2/sites-available# cat 000-default.conf

<VirtualHost *:80>
ServerAdmin webmaster@localhost
<Directory /var/www/snipeit/public>
        Require all granted
        AllowOverride All
   </Directory>
    DocumentRoot /var/www/snipeit/public
    ServerName snipeit.xxxx.org
        ErrorLog /var/log/apache2/snipeIT.error.log
        CustomLog /var/log/apache2/access.log combined
</VirtualHost>

- - - - - - - - - - - 
root@snipeit:/etc/apache2/sites-available# cat snipeit.conf

<VirtualHost *:80>
ServerAdmin webmaster@localhost
<Directory /var/www/snipeit/public>
        Require all granted
        AllowOverride All
   </Directory>
    DocumentRoot /var/www/snipeit/public
    ServerName snipeit.xxxx.org
        ErrorLog /var/log/apache2/snipeIT.error.log
        CustomLog /var/log/apache2/access.log combined
</VirtualHost>
<VirtualHost *:80>
ServerAdmin webmaster@localhost

        Require all granted
        AllowOverride All
   </Directory>
    DocumentRoot /var/www/snipeit/public
    ServerName snipeit.brunswickschool.org
        ErrorLog /var/log/apache2/snipeIT.error.log
        CustomLog /var/log/apache2/access.log combined
</VirtualHost>

- - - - - - - - - - - 

root@snipeit:/var/www/snipeit# cat .env

#Created By Snipe-it Installer
APP_TIMEZONE=America/New_York
DB_HOST=localhost
DB_DATABASE=snipeit
DB_USERNAME=snipeit
DB_PASSWORD=xxxxxx
APP_URL=http://snipeit.xxxx.org
APP_KEY=xxxxx
# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=10.1.0.8
MAIL_PORT=25
#MAIL_USERNAME=
#MAIL_PASSWORD=
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=snipeit@xxxx.org
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=snipeit@xxxx.org
MAIL_REPLYTO_NAME='Snipe-IT'

root@snipeit:/var/www/snipeit#

**Comment by wicknet** [comment]
Figured it out myself. Anyone running into same issue - feel free to contact me.

**Comment by misterhoots** [comment]
@wicknet - could you explain how you got this working? 
I'm having the same issue.

**Comment by koolk** [comment]
@misterhoots @wicknet to get SSL working watch this video from around 17:22. Even though this is an ownCloud server setup I used the same  instructions to setup ssl on my snipe-it server.

**Comment by misterhoots** [comment]
Thanks for that @koolk I managed to get it working by referencing link you posted.

**Comment by knorquist** [comment]
@wicknet could you provide what steps you took? We're implementing Snipe IT and we'd like to have SSL going too.

**Comment by wicknet** [comment]
Happy to help. It's all in the Apache setup... see below. Remember to change hostname and yourdomain.com to your FQDN instance and myssl cert and key files to their proper names.

cd /etc/apache2/sites-available/

Make backup of Apache config
cp 000-default.conf 000-default.conf.old

Paste the following in 000-default.conf 

<VirtualHost *:80>
ServerAdmin webmaster@localhost
<Directory /var/www/snipeit/public>
        Require all granted
        AllowOverride All
   </Directory>
    DocumentRoot /var/www/snipeit/public
    ServerName snipeit.yourdomain.com
   Redirect permanent / https://snipeit.yourdomain.com/
        ErrorLog /var/log/apache2/snipeIT.error.log
        CustomLog /var/log/apache2/access.log combined
</VirtualHost>
<VirtualHost *:443>
ServerAdmin webmaster@localhost
<Directory /var/www/snipeit/public>
        Require all granted
        AllowOverride All
   </Directory>
    DocumentRoot /var/www/snipeit/public
    ServerName snipeit.yourdomain.com
	SSLEngine on
	SSLCertificateFile /etc/ssl/certs/myssl.crt
	SSLCertificateKeyFile /etc/ssl/private/myssl.key
        ErrorLog /var/log/apache2/snipeIT.error.log
        CustomLog /var/log/apache2/access.log combined
</VirtualHost>

Copy myssl.cert and key file you already have into /etc/ssl folders

Run following commands to enable all the required modules for apache and restart the service

a2enmod rewrite
a2dismod autoindex -f
a2enmod speling 
a2enmod ssl
service apache2 restart

Give permissions to Apache 
chown -R www-data:www-data /var/www/snipeit/

Done. Reboot and enjoy Snipe with your own SSL certs.

**Comment by wicknet** [comment]
Happy to help. It's all in the Apache config. Remember to change domain and host name in FQDN below.

cd /etc/apache2/sites-available/

Make backup of Apache config
cp 000-default.conf 000-default.conf.old

Paste the following in 000-default.conf 

<VirtualHost *:80>
ServerAdmin webmaster@localhost
<Directory /var/www/snipeit/public>
        Require all granted
        AllowOverride All
   </Directory>
    DocumentRoot /var/www/snipeit/public
    ServerName snipeit.yourdomain.com
   Redirect permanent / https://snipeit.yourdomain.com/
        ErrorLog /var/log/apache2/snipeIT.error.log
        CustomLog /var/log/apache2/access.log combined
</VirtualHost>
<VirtualHost *:443>
ServerAdmin webmaster@localhost
<Directory /var/www/snipeit/public>
        Require all granted
        AllowOverride All
   </Directory>
    DocumentRoot /var/www/snipeit/public
    ServerName snipeit.yourdomain.com
	SSLEngine on
	SSLCertificateFile /etc/ssl/certs/MySSL.crt
	SSLCertificateKeyFile /etc/ssl/private/MySSL.key
        ErrorLog /var/log/apache2/snipeIT.error.log
        CustomLog /var/log/apache2/access.log combined
</VirtualHost>

Copy your SSL cert and key files into /etc/ssl folders and edit config to match names.

Run following commands to enable all the required modules for apache and restart the service

a2enmod rewrite
a2dismod autoindex -f
a2enmod speling 
a2enmod ssl
service apache2 restart

Give permissions to Apache 
chown -R www-data:www-data /var/www/snipeit/

Done. Reboot and enjoy Snipe with your own SSL certs.

**Comment by knorquist** [comment]
Awesome, thanks so much!

**Comment by knorquist** [comment]
For posterity, we ended up using certbot and it was basically just a drop-in installation, no extra configuration required: https://certbot.eff.org/
