### ISSUE TITLE
Unable to add new model from New-Asset window

### ISSUE THREAD

**Issue by Drtrider** [snipe/snipe-it#3290]
#### Expected Behavior (or desired behavior if a feature request)
Click on the "New" button next to model and create new model of asset.

-----

#### Actual Behavior

Nothing happens. 

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

Here's a screenshot of the errors from the web page: http://i.imgur.com/nlQj39A.png

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
My guess would be that your APP_URL protocol is wrong in your .env (http if you're accessing from https, or vice versa.)

**Comment by Drtrider** [comment]
Interesting. Do you know what it's supposed to be? Or does that vary based on the install/machine?

**Comment by snipe** [comment]
It would depend on your installation. The APP_URL must exactly match the URL you're accessing the app from. https://snipe-it.readme.io/docs/configuration#section-required-basic-app-settings

**Comment by Drtrider** [comment]
Thanks for the help there @snipe 
We have our URL pointing to the main URL with a sub-domain. Got it corrected, and seemed to fix the issue. Thanks for the prompt support, and assistance. 


This project has allowed our small-scale consulting company to get our stuff organized without a huge price requirement. Thanks again, and for the great tool and hard work you've put into it.

**Comment by snipe** [comment]
Awesome - glad you're sorted! 

![high-five-light](https://cloud.githubusercontent.com/assets/197404/22850162/f8cf7422-efb9-11e6-8150-c797959a4a81.gif)
