### ISSUE TITLE
Users menu missing in Admin Interface

### ISSUE THREAD

**Issue by RustyDust** [snipe/snipe-it#3294]
#### Expected Behavior (or desired behavior if a feature request)

After installation I expect to be able to manage user accounts.

-----

#### Actual Behavior

"Users" menu entry isn't shown in the "Admin" drop down menu
PATCH ATTACHED.

-----

[snipeit_admin_users.patch.txt](https://github.com/snipe/snipe-it/files/769231/snipeit_admin_users.patch.txt)
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
   Master from GitHub

- What OS and web server you're running Snipe-IT on
  Debian 8.7.1 / Apache 2.4

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  install.sh and manual

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
  See above

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
  didn't check

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
  Normal install, no error messages

- Indicate whether or not you've manually edited any data directly in the database
   No

**Comment by snipe** [comment]
That's not a bug. People are managed through the left side menu, not the admin menu.
