### ISSUE TITLE
Custom report generating error

### ISSUE THREAD

**Issue by umerafridi** [snipe/snipe-it#3299]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [  ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
 3.6.0

- What OS and web server you're running Snipe-IT on
CentOS 6.5
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
 Manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Whoops, looks like something went wrong.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
 Generating Custom Report 
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
Whoops, looks like something went wrong.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
> WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
> Whoops, looks like something went wrong.

Debug is not turned on. Please turn on debug, and tell us what the stack trace is.

**Comment by umerafridi** [comment]
how to turned on Debug. it's on from httpd.conf file?

**Comment by umerafridi** [comment]
after turn on debug mode following error are shown in browser
ErrorException in 5019ec894e6f8bb4f811e3a4a23a325c2c719ddc.php line 66:
Trying to get property of non-object (View: /var/www/html/snipe-it-3.6.0/resources/views/reports/depreciation.blade.php)

**Comment by umerafridi** [comment]
please i need your reply
