### ISSUE TITLE
Software License "Index View" doesn't order well

### ISSUE THREAD

**Issue by diwanicki** [snipe/snipe-it#330]
The main view (/admin/licenses) of the Software Licenses lists detailed info for all licenses in the database. This does not deal with numerical order very well (i.e.: seats 1, 10, 100 are listed next to each other) and I'm guessing is very DB expensive. I've only got 3 products entered so far, and only 212 total licenses and it seems quite overwhelming.

Would it be better for this first page to be an overview list of licenses, showing just the name, quantity total/available, and maybe purchase date (to differentiate between different purchases of same product)?

(or get real fancy, and list by manufacturer, expand to product?)

Then when user clicks on the license name, it opens the history page for that product, which currently presents the seat numbers in the proper order.

Checkin/Out and edits can be done on the history page, so repeating them on the index page is not necessary?

**Comment by DanielNemanic** [comment]
Do you have information about that?

It would be nice to show the licenses like the license report.
After selection open the seats.
Maybe an option from Bootstrap: Accordion
