### ISSUE TITLE
Anonymous LDAP bind

### ISSUE THREAD

**Issue by hidalgo67** [snipe/snipe-it#3300]
#### Expected Behavior (or desired behavior if a feature request)

I would like to bind snipe-it anonymous to my OpenLDAP server.

#### Actual Behavior

I get an error if I leave username and password empty or if I put "anonymous" into it.

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:
Snipe-IT version	v3.6.3 build 15 (g1bf34d7)
PHP Version	7.0.13-0ubuntu0.16.04.1
Laravel Version	5.2.45

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
LDAP Bind Username and password is required for searching the LDAP directory to sync.
