### ISSUE TITLE
Snipe-IT using WAMP

### ISSUE THREAD

**Issue by jonathan555** [snipe/snipe-it#3301]
My first time at trying something like this.

I have just installed Snipe-IT is WAMP on a Server 2012 environment, followed the guide and the installation went well with no errors.

However when I browse to the URL in IE I get this page cannot be displayed message. Have I missed something obvious?

Thanks
Jonathan

**Comment by huyem83** [comment]
Is your windows firewall off?

**Comment by jonathan555** [comment]
Many thanks for the reply, I can confirm that the Windows Firewall is off.

**Comment by jonathan555** [comment]
Please disregard the previous. had a play this afternoon and all is working.
