### ISSUE TITLE
Feature Request: Single email on bulk checkout

### ISSUE THREAD

**Issue by fatgeek** [snipe/snipe-it#3302]
#### Expected Behavior (or desired behavior if a feature request)

It would be a huge benefit to be able to have a user receive one email when checking multiple items out to them instead of the current one email per asset. 
-----

#### Actual Behavior

The user receives one confirmation email per item. 
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.6.3 build 15 (g1bf34d7)
- What OS and web server you're running Snipe-IT on: Hosted
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Hosted
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by gilesytheking** [comment]
I know this is an old request, but I think this is definitely a much needed feature.

Often we checkin/checkout 20-30 tools/assets to our employees at one time. This would then trigger 20-30 emails being sent at one time. Our employees are getting rather annoyed with receiving multiple emails when assets are checked out to them.

Ideally when using the bulk checkout feature 1 email should be sent with a list of all the assets formatted in a table. 

![bulk-email](https://user-images.githubusercontent.com/15634270/55145652-0cbacd80-513b-11e9-9308-bb3735583d0f.jpg)
