### ISSUE TITLE
Importing Assets from CSV files

### ISSUE THREAD

**Issue by agebremariam** [snipe/snipe-it#3304]
I tried to import a file based on SNIPEIT's CSV file format but I was not successful. I even tried to import the sample file which was on website (https://snipe-it.readme.io/docs/importing) still not successful.

Does anyone know hot to import from CSV files to SnipeIT?

Please send me the format or send me the steps I should follow to import files.

Thanks,

Abiy

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by agebremariam** [comment]
Hello Snipe,

I am using SNIPEIT version 3.5.2-11-g5a835a5 and Cento OS 7. 
From Asset - Import - Select Import File to import the csv file. Tried to import the attached file.
No error messages while importing but it shows 0% status. Tied to break down the number of entries but still the same.

I tried also Asset - Import History - brows and select CSV file (which is attached on this comment) but it says that 200 error messages


Asset 970882174-8: Asset does not exist so no match was attempted. 
Asset 544574073-0: Asset does not exist so no match was attempted. 
Asset 710141467-2: Asset does not exist so no match was attempted. 
Asset 103538064-1: Asset does not exist so no match was attempted. 
Asset 118753405-6: Asset does not exist so no match was attempted. 
Asset 998233705-X: Asset does not exist so no match was attempted. 
[snipe-sample-assets.zip](https://github.com/snipe/snipe-it/files/781086/snipe-sample-assets.zip)


![asset management error message](https://cloud.githubusercontent.com/assets/25803657/23034352/8cf049a4-f449-11e6-90df-9f5d392167d0.jpg)

**Comment by lorenzolewis** [comment]
Make sure that you are trying to import the asset and not the asset history. 
<img width="230" alt="asset" src="https://cloud.githubusercontent.com/assets/15347255/23136910/b926c606-f764-11e6-98d1-098444ac5b82.png">

**Comment by agebremariam** [comment]
Dello Lorenzo,

I tried to import the attached file as the steps you indicated but I was not successful.

Please check the attached files

Thanks,

Abiy
[snipe-sample-assets (2).zip](https://github.com/snipe/snipe-it/files/790587/snipe-sample-assets.2.zip)

**Comment by lorenzolewis** [comment]
Are you getting any errors when you attempt to import? It should be fine and I have used that same file myself when I first started testing. I'm honestly shooting in the dark here. It's a lot easier to troubleshoot if you are able to provide all of the files that @snipe asked earlier. That way you can more easily trace the error back to a specific problem.

**Comment by jmathias59** [comment]
I have also found that importing with the command line worked when the GUI did not.

James

**Comment by agebremariam** [comment]
Please find the attached zipped files to import and error message from SNIPE-IT while importing.
[asset management error message.zip](https://github.com/snipe/snipe-it/files/794495/asset.management.error.message.zip)
[Sample asset to import.zip](https://github.com/snipe/snipe-it/files/794496/Sample.asset.to.import.zip)

**Comment by lorenzolewis** [comment]
@agebremariam Referenced from @snipe 's original comment:

> Version of Snipe-IT you're running
What OS and web server you're running Snipe-IT on
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
If you're getting an error in your browser, include that error
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
If a stacktrace is provided in the error, include that too.
Any errors that appear in your browser's error console.
Confirm whether the error is reproduceable on the demo.
Include any additional information you can find in app/storage/logs and your webserver's logs.
Include what you've done so far in the installation, and if you got any error messages along the way.
Indicate whether or not you've manually edited any data directly in the database

Namely those console errors and log files would be most useful. The screenshots that you attached are not very helpful as they do not contain very much information. The logs files will have more information.

**Comment by rizkymusthofa0509** [comment]
![11111](https://user-images.githubusercontent.com/34386217/60067070-61b6b180-9733-11e9-9ed6-8c2c874e92bb.png)

**Comment by JasonGreenC** [comment]
I can confirm I'm getting the same error with both my own CSV and the sample inventory CSV. 
![Screen Shot 2019-07-05 at 11 20 16 AM](https://user-images.githubusercontent.com/18202469/60739490-02b52180-9f17-11e9-88f4-03eb247533a9.png)

**Comment by snipe** [comment]
Please do not resurrect threads from two years and twenty versions ago. This was closed then because the issue was resolved. If you're having a new issue with a current version, please open a new ticket and include the information requested in the issue template. There is literally nothing we can do with "a 500 error". We need log info, etc, which the ticket issue template will prompt you for.
