### ISSUE TITLE
[Feature Request] Ability to update a listbox item in custom fields

### ISSUE THREAD

**Issue by cduverne** [snipe/snipe-it#3307]
#### Expected Behavior (or desired behavior if a feature request)

I would like to be able to update a listbox type custom field

-----

#### Actual Behavior

I can only delete a listbox item.  
If I want to update one, I have to remove it and recreate it witht the new values

-----

#### Please confirm you have done the following before posting your bug report:

- [N/A] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running : 3.6.3
- What OS and web server you're running Snipe-IT on : Docker version
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Docker version
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error : N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error ```/admin/custom_fields```
- If a stacktrace is provided in the error, include that too. N/A
- Any errors that appear in your browser's error console. N/A
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). YES
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. N/A
- Include what you've done so far in the installation, and if you got any error messages along the way. Nothing
- Indicate whether or not you've manually edited any data directly in the database NO

**Comment by StevenCeres** [comment]
I agree with cduverne, this feature would be really appreciated!
