### ISSUE TITLE
Consumables notification

### ISSUE THREAD

**Issue by helltiger12** [snipe/snipe-it#3310]
#### Expected Behavior (or desired behavior if a feature request)

Have added 21 Consumables with the 'Min Qty' set to 1. Not to show 21 notification about low consumables.

-----

#### Actual Behavior

All of my consumables are classed as being low but only one i have no stock of.

-----

#### Please confirm you have done the following before posting your bug report:

- [Y] I have enabled debug mode
- [Y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- v3.6.2 build 10 (g927a12f)
- Debian 8
- install.sh
- No errors
- Any

I can see that on the demo version it is doing the same. I would had thought that this would have only been triggered if the remaining stock number was at the Min. Qty number. Please let me know if i am thinking of this feature wrongly.
![snipe-it notifications](https://cloud.githubusercontent.com/assets/8352061/23046074/78943492-f49f-11e6-977b-2a6c22a124a7.png)

**Comment by ernestasen** [comment]
It's already submitted here: https://github.com/snipe/snipe-it/issues/3113
