### ISSUE TITLE
TravisCI builds fail

### ISSUE THREAD

**Issue by vjandrea** [snipe/snipe-it#3312]
#### Expected Behavior (or desired behavior if a feature request)

I expect TravisCI builds to succeed
-----

#### Actual Behavior

https://travis-ci.org/snipe/snipe-it/jobs/202159632

[Illuminate\Database\QueryException]                                       
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add unique `users_email_unique`(`email`))                                              

[PDOException]                                                             
SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
                            
-----

#### Please confirm you have done the following before posting your bug report:

- [✔︎] I have enabled debug mode
- [✔︎] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v4.0-develop build 10 (g76344a8)
- What OS and web server you're running Snipe-IT on: Valet on OSX El Capitan 10.11.6
- What method you used to install Snipe-IT: (install.sh, manual installation, docker, etc) manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: not relevant
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: not relevant
- If a stacktrace is provided in the error, include that too: not relevant
- Any errors that appear in your browser's error console: not relevant
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): general builds fail.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs: not relevant
- Include what you've done so far in the installation, and if you got any error messages along the way: didn't change any migration file in my PRs
- Indicate whether or not you've manually edited any data directly in the database: nope

**Comment by snipe** [comment]
I think this should be fixed already, per https://laravel-news.com/laravel-5-4-key-too-long-error
