### ISSUE TITLE
LDAP Filter not working

### ISSUE THREAD

**Issue by JarrodR87** [snipe/snipe-it#3314]
#### Expected Behavior (or desired behavior if a feature request)

I expect SnipeIT/AD to not allow Login to users not in a Specific Group and Users who are Dsiabled even if they are in the Group

-----

#### Actual Behavior

All AD Users are currently able to Login

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v3.6.3 build 15 (g1bf34d7) 
- What OS and web server you're running Snipe-IT on - CentOS 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Screenshot of LDAP Settings:
![image](https://cloud.githubusercontent.com/assets/25852225/23080757/0a674744-f520-11e6-9b21-0c06be390cce.png)

Filter String
`&(memberOf=CN=<Group Name>,OU=<Sub OU>,OU=<Sub OU>,OU=<Sub OU>,DC=<Domain>,DC=com) (!(userAccountControl:1.2.840.113556.1.4.803:=2))`

**Comment by markkeller** [comment]
Having a near identical issue.  We have a delegated OU within my organization's AD forest.  We're hoping to limit access to only department employees that are members of a security group within our OU.  

When I sync LDAP (either through the web interface or composer) it correctly grabs all members of the security group and creates user accounts for them.  However, any active user within Active Directory (and not a member of the security group) is still able to log in and Snipe-IT creates an account upon first login.  

Is there a way to set a reject login by default if the filter has not been met, regardless of whether or not the user has provided valid credentials?

**Comment by sduensin** [comment]
Issue may be stale but it's not fixed!

**Comment by snipe** [comment]
The issue was created referencing v3 of Snipe-IT. Can you tell me what version you’re using?

**Comment by RTodorov** [comment]
Same issue here with v4.....
