### ISSUE TITLE
Customizations

### ISSUE THREAD

**Issue by vinothr72** [snipe/snipe-it#3316]
Hi There,

I want to customize the application by adding additional screens & reports, how to do that? Any documentations?

Thanks in advance.

Regards,
Vinoth

**Comment by snipe** [comment]
The application is written in [Laravel](http://laravel.com). The code itself is pretty well documented inline. Otherwise, please see the contributing docs [here](https://snipe-it.readme.io/docs/contributing) and [here](https://snipe-it.readme.io/v4.0/docs/contributing-overview).
