### ISSUE TITLE
Employee ID search in checkout.

### ISSUE THREAD

**Issue by aldervall** [snipe/snipe-it#3318]
#### Expected Behavior (or desired behavior if a feature request)

Scan/type Employee ID number in checkout asset. Example: 121258 Should result in finding the person when i checkout an asset.

-----

#### Actual Behavior

If i go in to people tab and make a search for their employee number iam able to find that person.
But not when i do a asset checkout. 

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version v3.6.3 build 15 (g1bf34d7)
- Windows 7 (wampserver 6.0.3)
- manual installation
- /checkout

**Comment by snipe** [comment]
This is already in the upcoming v4
