### ISSUE TITLE
Ldap connection

### ISSUE THREAD

**Issue by JackPippe** [snipe/snipe-it#3319]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

When try to configure connection ldap on Ubutu i have always same error:

FatalErrorException in Ldap.php line 43:
Call to undefined function App\Models\ldap_connect()
in Ldap.php line 43

The laravel.log are below:

 production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function App\Models\ldap_connect()' in /var/www/snipeit/app/Models/Ldap.php:43
Stack trace:

Ldap.so is correctly enable in ldap.ini

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running:  

> v3.6.3 build 15 (g1bf34d7)

- What OS and web server you're running Snipe-IT on: 

> Ubuntu 16.10
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): 

> install.sh

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. 

> Yes

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).

> No because Ldap is not present
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the 

> database: No

**Comment by shoutinblues** [comment]
See if you have php-ldap installed:
dpkg -l | grep ldap
If not, display your version of php:
php -v
Install php-ldap, for example for php 5.6:
sudo apt-get install php5.6-ldap

**Comment by JackPippe** [comment]
dpkg -l | grep ldap: 


ii  ldap-auth-client                           0.5.3                                            all          meta-package for LDAP authentication
ii  ldap-auth-config                           0.5.3                                            all          Config package for LDAP authentication
ii  ldap-utils                                 2.4.42+dfsg-2ubuntu4                             amd64        OpenLDAP utilities
ii  libaprutil1-ldap:amd64                     1.5.4-2                                          amd64        Apache Portable Runtime Utility Library - LDAP Driver
ii  libldap-2.4-2:amd64                        2.4.42+dfsg-2ubuntu4                             amd64        OpenLDAP libraries
ii  libnss-ldapd:amd64                         0.9.7-1                                          amd64        NSS module for using LDAP as a naming service
ii  libpam-ldap:amd64                          184-8.7ubuntu1                                   amd64        Pluggable Authentication Module for LDAP
ii  php-ldap                                   1:7.1+49+deb.sury.org~yakkety+4                  all          LDAP module for PHP [default]
ii  php7.0-ldap                                7.0.15-1+deb.sury.org~yakkety+1                  amd64        LDAP module for PHP
ii  php7.1-ldap                                7.1.1-1+deb.sury.org~yakkety+1                   amd64        LDAP module for PHP
ii  phpldapadmin                               1.2.2-5.2ubuntu2                                 all          web based interface for administering LDAP servers

php -v:
PHP 7.1.1-1+deb.sury.org~yakkety+1 (cli) (built: Jan 20 2017 09:20:56) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.1-1+deb.sury.org~yakkety+1, Copyright (c) 1999-2017, by Zend Technologies

The problem is the php is correctly installed. One dubt there should be in php.ini the extension=ldap.so

**Comment by JackPippe** [comment]
Thanks one thousand

I resolved through the installation of the "apt-get install php5.6-ldap"

**Comment by shoutinblues** [comment]
I am using php5.6 because I found 7.0 did not work with some other apps we were using.  Did not test Snipe-It on 7.0.  Interesting that 7.1 does not appear to work with Snipe-It.
