### ISSUE TITLE
Importing assets stucks at 100%

### ISSUE THREAD

**Issue by serkansentuna** [snipe/snipe-it#3320]
Hello.

This is my early day using Snipe-IT and I'm trying to import an asset for a test. I do not see any error because it stucks at 100%. I've used the Excel file which mentioned in the link (https://snipe-it.readme.io/docs/importing#section-importing-custom-fields) and saved it as csv.

Could you please inform me how I can solve this issue and proceed on importing? You can find a screen shot below.

Thanks in advance
![image](https://cloud.githubusercontent.com/assets/25905641/23131596/3df49ed4-f793-11e6-91a8-4cfe3228f46f.png)
![image](https://cloud.githubusercontent.com/assets/25905641/23131988/ca4648b4-f794-11e6-805d-10769575d88f.png)

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - **v3.6.2 build 18 (g6f1e0d6) **
- What OS and web server you're running Snipe-IT on **Windows Server 2012 R2 Std x64**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **hardware/import**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by lorenzolewis** [comment]
I'm not sure if this would help but have you tried to import them with commas instead of semicolons as separators? I also had an issue at first when after I exported the file it would have empty columns and that would cause the uploader to hang.

**Comment by serkansentuna** [comment]
I have tried three more different way as below; with only commas and empty coulmns; without commas and with empty coulmns, without commas and empty coulmns. Unfortunately the result is same and I do not know how I can solve it..

![image](https://cloud.githubusercontent.com/assets/25905641/23152545/6c8dd882-f80b-11e6-9bb3-e92d0bfee96a.png)

**Comment by lorenzolewis** [comment]
@serkansentuna Can you post those as text and I'll try to upload them to see if it works for me?

**Comment by snipe** [comment]
The import being stuck won't have anything to do with the delimiters, since the app doesn't try to process the file at that point, it's just uploading. This is usually related to the storage directory (and subdirectories) not being writable by the file server.

**Comment by firmank** [comment]
hi snipe, i have similar case, the upload process status was "success!", but import process heven't finish yet until now (already took more than 5 hours), data only 159 KB, i have checked Asset Tag is unique, i checked the folder C:\wamp\www\snipe-it\storage\private_uploads\imports confirmed not readonly.
