### ISSUE TITLE
Adjusting Time Stamp in Snipe

### ISSUE THREAD

**Issue by brosevelt** [snipe/snipe-it#3322]
Hello,

Somewhat new to Snipe, but I've gotta say I'm really loving its capabilities so far and am enjoying using it.  I have it running on an Ubuntu server VM.  I'm no expert when it comes to Linux, but it's been fun playing with it and setting up a snipe environment and getting back in touch with it.

I've got snipe built out to pretty much exactly what I want, however I'm having some trouble adjusting time stamp settings for when things are added/imported into snipe.  It's exactly 6 hours ahead in Snipe vs when the action actually takes place, so I imagine it's just a time zone setting or just maybe the time is off itself.  What is the best way to make the change in Snipe?  Is there a setting to easily change it in the web interface that I'm missing or does a file need to be edited on the server?  Any help is much appreciated.

Thanks!

**Comment by snipe** [comment]
The time zone is handled via your .env: https://snipe-it.readme.io/docs/configuration#section-required-basic-app-settings

**Comment by User417714** [comment]
I was able to successfully change my timezone in the .env file but now it's showing the correct time and the incorrect date.  Is there something else I need to check?  Thanks in advance!
