### ISSUE TITLE
Custom Field enhancements

### ISSUE THREAD

**Issue by ebonweaver** [snipe/snipe-it#3326]
May already be in the dev timeline, but some thoughts on custom fields:

When you delete a field from a set, don't bounce back out to the main screen, just refresh and stay in the edit of that set.  When you add a field to a set it just refreshes.

When adding a field to a set, you can duplicate an order value, but that will never happen again once you drag them around to order them.  I haven't tested if having duplicate order values causes issues, but the behavior seems off.  Expectation would be if I add a new one at 5, the old 5 becomes 6 and the rest below bump one as well.

Editing fields would be nice.  Right now renaming is impossible, you'd have to delete it, lose all the data, and make a new one.  Not ideal.  Same problem if you need to edit the custom formatting of a field.  
Once in the theoretical edit screen for a field, it would also be nice to have a list of checkboxes of sets that you can associate or remove from.

Being able to change if a field is required in a set would be nice, rather than having to delete and re-add it to set that flag.  Unclear if data is lost in that dis and re association process (untested).

And of course, it would be nice if sets could be linked in more places than just asset models so that somehow other types (consumables, components, etc) could have custom fields added.  If linked properly through models, you would then have a relation between say Asset: Campaign Printer of Model: Designjet z3200 and the consumables that it uses.  That starts going outside fields to consumables enhancements obviously, but once things start getting inter-relational that happens  :)

**Comment by snipe** [comment]
Editing custom fields will be in v4. I believe there are already tickets open for the other points.
