### ISSUE TITLE
Mssing admin menu with granted admin

### ISSUE THREAD

**Issue by Patrock** [snipe/snipe-it#3329]
#### Expected Behavior (or desired behavior if a feature request)

When i give a group admin (not super-user) privileges i should see a reduced admin menu (e.g. adding/editing models, manufacturers, etc.). 

-----

#### Actual Behavior

I don'T see a admin menu, i don't see a difference between admin and non-admin interface

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.6.3 build 15 (g1bf34d7)
- What OS and web server you're running Snipe-IT on
Coreos, webserver from docker image
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
no
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
each page, its a missing menu item

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
That's not currently how it works. The admin menu is for superadmins only. This behavior will change in the upcoming v4 though.
