### ISSUE TITLE
Signatures

### ISSUE THREAD

**Issue by fixinputers** [snipe/snipe-it#3330]
#### Expected Behavior (or desired behavior if a feature request)

I expected a signature page to load after checking asset out to user for immediate signing. some of my users don't have immediate access to email. signing out stuff like keys and gas cards should happen at time of delivery best case scenario

-----

#### Actual Behavior

an email gets sent to the user for signature and declares they have already received the asset. 

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
System Information
Snipe-IT version v3.6.3 build 15 (g1bf34d7)  
PHP Version 5.6.30 
Laravel Version 5.2.45

**Comment by nbiz2017** [comment]
Can you include function signatures in tab Maintenance?  
Some assets non-IT and it was assigned to the group (use/maintenance). Sometime our technical are cheating in task.
He log in and create maintenance work (eg, asset cleaning) but he have not actually done 100%. When the supervisor finds out, he says someone logs in and creates it and he does not have time to do so, so Leader can not punish him. If there are signature features when maintenance, it will be fair, clear.
Some assets non-IT and it was assigned to the group (use/maintenance)
Thanks.
