### ISSUE TITLE
Display Navigation Buttons at the top and bottom of the page

### ISSUE THREAD

**Issue by ttpars** [snipe/snipe-it#3335]
#### Expected Behavior (or desired behavior if a feature request)

On each page where assets or other items are listed:  If the number of items available is greater than the number of items on the page there is a navigation bar on the bottom of the page (First, Previous, 1, 2, 3 4...., Next, Last).

We would like to request that there be an option to display this navigation bar at the top of the page as well, perhaps beside the search bar+buttons

-----

#### Actual Behavior

The navigation bar is only visible at the bottom of the page

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: 3.5.2
- What OS and web server you're running Snipe-IT on: Ubuntu w/ Nginx
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): Yes
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database: No

**Comment by VanillaNinjaD** [comment]
My company seconds this exact issue, thanks for bringing this up!

**Comment by snipe** [comment]
This will be released in the upcoming v4

**Comment by VanillaNinjaD** [comment]
Thanks Snipe
