### ISSUE TITLE
About Generate Asset Labels

### ISSUE THREAD

**Issue by senlion** [snipe/snipe-it#3339]
#### Expected Behavior (or desired behavior if a feature request)

Hi~
I want to show more infomation when generate assets labels. I need it contains Asset Name , Asset Tag , Asset Model Name , Asset Location and Purchase Date , When i am modifying the file  snipeit\resources\views\hardware\labels.blade.php like this 

` _<div class="pull-left">
        @if (($settings->labels_display_name=='1') && ($asset->name!=''))
            Assetname: {{ $asset->name }}
        @endif
        </div>
        <div class="pull-left">
        @if (($settings->labels_display_tag=='1') && ($asset->asset_tag!=''))
            Number: {{ $asset->asset_tag }}
        @endif
        </div>
        <div class="pull-left">
        @if (($settings->labels_display_model=='1') && ($asset->model_id!=''))
            Type: {{ $asset->model_id }}
        @endif
         </div>
        <div class="pull-left">
        @if (($settings->labels_display_location=='1') && ($asset->rtd_location_id!=''))
            Location: {{ $asset->rtd_location_id }}
        @endif
         </div>
		         <div class="pull-left">
   		@if (($settings->labels_display_date=='1') && ($asset->purchase_date!=''))
            Purchase Date: {{ $asset->purchase_date }}	
        @endif
         </div>_`
![code](https://cloud.githubusercontent.com/assets/1390559/23253732/8ec695ba-f9f0-11e6-92f6-6e0f1d5f47b2.jpg)

when generate asset labels , it shows Asset Model Name , Asset Location with id numbers like 242(The corresponding model of the device is 242) , 10(The corresponding location of the device is 10),
I do not know how to get the name of the model/location through id numbers .
Waiting for your reply, thank you.
-----
![lables](https://cloud.githubusercontent.com/assets/1390559/23253433/7acb90f2-f9ef-11e6-9b76-e1f807f7fa3e.jpg)
![assets](https://cloud.githubusercontent.com/assets/1390559/23253435/7acf85ae-f9ef-11e6-9682-f15c7627f819.jpg)
![models](https://cloud.githubusercontent.com/assets/1390559/23253434/7acc1afe-f9ef-11e6-98b0-cf266e4226c5.jpg)
![location](https://cloud.githubusercontent.com/assets/1390559/23253490/b6ad73ba-f9ef-11e6-88cc-2880f4f47761.jpg)
-----

I want this effect to the label
![w](https://cloud.githubusercontent.com/assets/1390559/23253556/fbae3076-f9ef-11e6-8a29-03fb47908c8d.jpg)

**Comment by renieroivas** [comment]
why was this closed? I would like to second the feature request, that "Models" can be shown on the generated Labels.
