### ISSUE TITLE
Multi-Filter and Custom Views

### ISSUE THREAD

**Issue by Louis-Kre** [snipe/snipe-it#3340]
#### Expected Behavior (or desired behavior if a feature request)

Hello guys,

I have a problem/request regarding filters in the asset-view.
Now we have to download the view and add filters in Excel. Is this possible to integrate multiple-filter, so that you can filter the column category like “notebook” and the column “EOL” like “March 2017”?
Another idea would be to integrate custom SQL-Queries, so that we can build our custom query and show the results in Snipe-IT?

-----

#### Actual Behavior

We have to download the data from the view and filter them in Excel.
Or we have to connect to the server and use custom SQL-Queries.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: 3.6.3
- What OS and web server you're running Snipe-IT on: Ubuntu-Server and Apache
- What method you used to install Snipe-IT: install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: -
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: -
- If a stacktrace is provided in the error, include that too.: -
- Any errors that appear in your browser's error console.: -
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).: -
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.: -
- Include what you've done so far in the installation, and if you got any error messages along the way.: -
- Indicate whether or not you've manually edited any data directly in the database: -

**Comment by cduverne** [comment]
+1, when listing assets we can select the fields we want to display.
I'd like to be able to save the layout in a custom view.

**Comment by snipe** [comment]
@cduverne The column show/hide selection is already stored in a cookie in the browser.

**Comment by cduverne** [comment]
Hi @snipe !
Indeed, and that's great, what would be greater would be the availability to save the filters in a custom view so we can share it.

**Comment by osa-ko** [comment]
+1 - this is huge. it would make the tool so much more effective.

**Comment by Louis-Kre** [comment]
Hi @snipe,
is there a progress?

Thanks for your help

**Comment by fastaemc** [comment]
Hi could this feature request come alive again it would be very helpfull

**Comment by malidule** [comment]
Custom view +1

We need something like this ! ! !   [from ServiceDesk Plus] (https://store.manageengine.com/service-desk/)

![Snimak ekrana 2023-11-29 165349](https://github.com/snipe/snipe-it/assets/42606889/fd5a4c7b-38a4-47fc-8252-a19c39b2fff6)

**Comment by Jaydengoul2003** [comment]
> Custom view +1 ![Snimak ekrana 2023-11-29 165349](https://private-user-images.githubusercontent.com/42606889/286656294-fd5a4c7b-38a4-47fc-8252-a19c39b2fff6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NzM3ODUsIm5iZiI6MTcwNDQ3MzQ4NSwicGF0aCI6Ii80MjYwNjg4OS8yODY2NTYyOTQtZmQ1YTRjN2ItMzhhNC00N2ZjLTgyNTItYTE5YzM5YjJmZmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDE2NTEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkODU4NTM0ZGZiN2RmMTM2ODE4YzViMDk1NDAwZjM3MjY1YzRiYWQyODViZWNjNzA2ZWY5NmVlNzZhMjY1YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z_9cwp-0LkvUjKWEc4UQyUT7Jr1HdzurL-4wjdhYU3U)

How did you set that up ive been looking everywhere?

**Comment by marius-96** [comment]
> Custom view +1 ![Snimak ekrana 2023-11-29 165349](https://private-user-images.githubusercontent.com/42606889/286656294-fd5a4c7b-38a4-47fc-8252-a19c39b2fff6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwOTM5MzEsIm5iZiI6MTcwNjA5MzYzMSwicGF0aCI6Ii80MjYwNjg4OS8yODY2NTYyOTQtZmQ1YTRjN2ItMzhhNC00N2ZjLTgyNTItYTE5YzM5YjJmZmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDEwNTM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NGQ5ZmViMDU3NGU4NmY1NTMxNTdiNDVlZDEzMDg2ODcyOTMxZTE1MTg4ZjQyMDA5OWEyZGQxZjc2NmI1YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TVmwRlaDxVDu-mPST5MjsXDT6Njo8pNehVEvcmPYOog)

Hi @malidule ! How did you get this set-up, looks super nice. Custom code?

**Comment by malidule** [comment]
> > Custom view +1 ![Snimak ekrana 2023-11-29 165349](https://private-user-images.githubusercontent.com/42606889/286656294-fd5a4c7b-38a4-47fc-8252-a19c39b2fff6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwOTM5MzEsIm5iZiI6MTcwNjA5MzYzMSwicGF0aCI6Ii80MjYwNjg4OS8yODY2NTYyOTQtZmQ1YTRjN2ItMzhhNC00N2ZjLTgyNTItYTE5YzM5YjJmZmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDEwNTM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NGQ5ZmViMDU3NGU4NmY1NTMxNTdiNDVlZDEzMDg2ODcyOTMxZTE1MTg4ZjQyMDA5OWEyZGQxZjc2NmI1YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TVmwRlaDxVDu-mPST5MjsXDT6Njo8pNehVEvcmPYOog)
> 
> Hi @malidule ! How did you get this set-up, looks super nice. Custom code?

Unfortunately, this is from ServiceDesk Plus (https://store.manageengine.com/service-desk/) that we use at work.
The most usable layout possible. Not available with Snipe-IT. :(
I'm just voting here for something like that.

**Comment by marius-96** [comment]
> > > Custom view +1 ![Snimak ekrana 2023-11-29 165349](https://private-user-images.githubusercontent.com/42606889/286656294-fd5a4c7b-38a4-47fc-8252-a19c39b2fff6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwOTM5MzEsIm5iZiI6MTcwNjA5MzYzMSwicGF0aCI6Ii80MjYwNjg4OS8yODY2NTYyOTQtZmQ1YTRjN2ItMzhhNC00N2ZjLTgyNTItYTE5YzM5YjJmZmY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDEwNTM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NGQ5ZmViMDU3NGU4NmY1NTMxNTdiNDVlZDEzMDg2ODcyOTMxZTE1MTg4ZjQyMDA5OWEyZGQxZjc2NmI1YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TVmwRlaDxVDu-mPST5MjsXDT6Njo8pNehVEvcmPYOog)
> > 
> > 
> > Hi @malidule ! How did you get this set-up, looks super nice. Custom code?
> 
> Unfortunately, this is from ServiceDesk Plus (https://store.manageengine.com/service-desk/) that we use at work. The most usable layout possible. Not available with Snipe-IT. :( I'm just voting here for something like that.

Understand, thanks for the reply @malidule!

--

@snipe Something like this UI would be fantastic, being able to have asset types listed like this would make it more functional.
