### ISSUE TITLE
Deployed Item shows Ready to deploy (deployable) in Asset detail view.

### ISSUE THREAD

**Issue by MoazzamMuhammadKhan** [snipe/snipe-it#3342]
#### Expected Behavior (or desired behavior if a feature request)

In the Asset view, when we click any deployed asset to check its details, it must be shown as deployed item too in the asset detail view.

-----

#### Actual Behavior

In Asset details view, the Asset which is already deployed, display as deploy able.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - Version v3.6.2 build 10 (g927a12f)
- What OS and web server you're running Snipe-IT on - Windows Server 2012 R2 and IIS 8.5
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
That's not really a bug, that's just how it works. Deployable refers to the status label *type*, which in that case would be deployable. An asset with a deployable status type that is assigned is considered to be deployed. The right-side column provides information on who it's checked out to, if it is checked out.
