### ISSUE TITLE
404 WHen Opening User profile

### ISSUE THREAD

**Issue by realironman** [snipe/snipe-it#3346]
#### Expected Behavior (or desired behavior if a feature request)

When clicking on a imported LDAP user to see the assets checked out to the user

-----

#### Actual Behavior

I get redirected to the 404 page not found error, users were imported from LDAP, but even wwhen I try to view my manually created user's profile I get the error

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- v3.6.4 build 12 (gf7e4fca
- Centos 7 Apache
- install.sh
- User Profile triggers 404 error not found
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

- Indicate whether or not you've manually edited any data directly in the database
1 admin user created manually

**Comment by vjandrea** [comment]
@realironman please [enable debug mode](https://snipe-it.readme.io/docs/getting-help), retry and post here what you find in `app/storage/logs/laravel.log`

**Comment by realironman** [comment]
[2017-02-27 11:46:11] production.DEBUG: LDAP is enabled.  
[2017-02-27 11:46:11] production.DEBUG: Binding user to LDAP.  
[2017-02-27 11:46:11] production.DEBUG: LDAP user sebastian.erasmus not found in LDAP or could not bind  
[2017-02-27 11:46:11] production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory  
[2017-02-27 11:46:11] production.DEBUG: Authenticating user against database.  
[2017-02-27 11:46:11] production.DEBUG: Local authentication failed.

But I am looking at the exact user in my "People's" group 

I have managed to get to view the user, but still cannot log in as a user imported from ldap, that has admin permissions

**Comment by snipe** [comment]
Are you still having this issue?

**Comment by ashutoshvct** [comment]
I'm also facing the same issue. I will post the logs after the reproducing the error.
Can anyone help on this case?

**Comment by snipe** [comment]
Where are you clicking on the user from? Which screen? Also can anyone reproduce it on the demo?
