### ISSUE TITLE
HTTP ERROR 500, Failed opening required '/var/www/html/snipe/public/index.php' (include_path='.:/usr/share/pear:/usr/share/php')

### ISSUE THREAD

**Issue by rronen04** [snipe/snipe-it#3347]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)
Unable to get to the setup page
-----

#### Actual Behavior

(what actually happens goes here)
I get a server error 500
-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
3.6.4
- What OS and web server you're running Snipe-IT on
Oracle Linux Server release 7.3
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
I am just pointing to the initial address
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
HTTP ERROR 500

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

[Fri Feb 24 10:43:07.151172 2017] [:error] [pid 7490] [client 192.168.56.1:63480] PHP Warning:  Unknown: failed to open stream: Permission denied in Unknown on line 0
[Fri Feb 24 10:43:07.151219 2017] [:error] [pid 7490] [client 192.168.56.1:63480] PHP Fatal error:  Unknown: Failed opening required '/var/www/html/snipe/public/index.php' (include_path='.:/usr/share/pear:/usr/share/php') in Unknown on line 0

- Include what you've done so far in the installation, and if you got any error messages along the way.

I ran the composer as root since otherwise was complaining about file permissions.

root@localhost snipe-it-3.6.4]# php composer.phar install --no-dev --prefer-source
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating autoload files
> php artisan clear-compiled
> php artisan optimize
Generating optimized class loader

changed the owner of everything to apache

[root@localhost snipe-it-3.6.4]# chown -R apache:apache *

- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
I'm guessing that's a permission error. Please make sure the snipe-IT directory (and all sub-dirs and files) are readable by the webserver, and that the storage directory (and all subdirs) are writable by the web server.
