### ISSUE TITLE
403 Forbidden for non admins when clicking locations or categories

### ISSUE THREAD

**Issue by ebonweaver** [snipe/snipe-it#3368]
#### Expected Behavior (or desired behavior if a feature request)

When you click on a location or category item in the asset list, it should take you to a result of assets of that location or category.  This works for admins, but not a view group.  The group in question has everything set to Deny except: Reports: view, Assets:view, Consumables:view

-----

#### Actual Behavior

403 sad panda

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode (did not show more info on 403)
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running:  v3.6.2 build 10 (g927a12f)
- What OS and web server you're running Snipe-IT on: Ubuntu 14 LTS Server
- What method you used to install Snipe-IT: install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: 403
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Assets -> List all -> click a location or category on an asset line
- If a stacktrace is provided in the error, include that too: nope
- Any errors that appear in your browser's error console: none
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): Unable to attempt, need super user to edit groups and assign membership to a new user
- Indicate whether or not you've manually edited any data directly in the database: NO

**Comment by ebonweaver** [comment]
Just tested permissions in more detail.  This is broken for anyone who isn't a super admin apparently.  Adding admin to the group did not help.  Adding the various other Asset; permissions did not help.  Only adding super admin made it work.

**Comment by R4mzy** [comment]
I'm seeing permissions/403 issues as well - it seems for permissions to work correctly, they must be defined at the user level. Group permissions result in a sad panda whenever any permission-dependant operations occur, and the group membership is stripped from the user.

In my case, I wanted one of our IT techs to set his own password by editing his user account. I created an admins group with Super User denied, and Admin & everything below granted. I add the user to the group, but if he tries to change any user info (specifically his own) he gets the 403/sad panda and his group membership is stripped. If I assign Admin permissions at the user level (Super User denied, everything else inherited) with no groups, he can set his own info without errors.
