### ISSUE TITLE
Not recognized Asian (Korean) utf8 for import

### ISSUE THREAD

**Issue by fofwisdom** [snipe/snipe-it#3369]
#### Expected Behavior

Imported Korean is showing good.
ex) 백상기업
-----

#### Actual Behavior

Imported Korean is showing broken.
ex) ???? or ¹é»ó±â¾÷

This problem is similar Chinese issue - https://github.com/snipe/snipe-it/issues/2921

![snipeit-utf-asian-01](https://cloud.githubusercontent.com/assets/205521/23386288/d8bd98b6-fd98-11e6-948e-d96c78ddf301.jpg)
![snipeit-utf-asian-02](https://cloud.githubusercontent.com/assets/205521/23387909/ade0ae80-fda2-11e6-8cad-d2bf404de29a.jpg)

-----

#### Please confirm you have done the following before posting your bug report:

- [] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- v3.6.4 build 12 (gf7e4fca)
- Ubuntu Server 16.10.2
- install.sh
- No error. Successful imported.
- No printed error.
- Not any errors that appear in browser.
- http://snipe-its/hardware/import
- 'app/storage/logs' is nowhere. Only showing 'storage/logs/laravel.log'
- No customized database.
- [csv.zip](https://github.com/snipe/snipe-it/files/805456/csv.zip)

**Comment by fofwisdom** [comment]
Where is going ./app/Importer/ ?

**Comment by fofwisdom** [comment]
"app/Console/Commands/ObjectImportCommand.php"
Need 'toUTF8'

Still not applying UTF fix commit to stable - https://github.com/snipe/snipe-it/commit/80da0f801cff00e8d91469fa23d2dbe140dfa493

**Comment by snipe** [comment]
That fix will be in the upcoming v4, per the commit.
