### ISSUE TITLE
Rearranging of columns

### ISSUE THREAD

**Issue by sambrish2** [snipe/snipe-it#3371]
I have create some custom fields, wana rearrange the columns. can some help me, 

![image]

I m not much in to coding.

**Comment by snipe** [comment]
That's not currently possible. We're looking into adding this feature, however there seems to be a conflict in the version of the table javascript library we use. Reordering columns is an available extension, however it's never worked properly in our testing.

**Comment by Metal0gic** [comment]
would also like this feature added

**Comment by xwu33** [comment]
I could rearrange the customized field when I create an new asset. Then I am working on rearranging the non-customized field columns and trying to change the columns sequence when I view all assets. I changed some variables at snipeit mvc file and still testing and researching. Will this feature be available for next version?

**Comment by jpierre-mm** [comment]
As a paying hosted customer, I'd love this feature too!
