### ISSUE TITLE
Always needing a restart

### ISSUE THREAD

**Issue by tanguyngoy** [snipe/snipe-it#3372]
Hi,

Sorry for the newbie question, but I would just like to ask a concern regarding my system.

My system is running fine after installation, but I always get the 'Whoops, looks like something went wrong' page after a period of time. What I would do is reboot the machine and it will run as usual.

Is there a setting I may have missed (timeout perhaps) on the installation? I don't know  if its database or OS issue. I'ts on Ubuntu 16.04.1 LTS and Snipe-IT version v3.6.3 build 15.

Thanks in advance.

**Comment by snipe** [comment]
Is this after a long idle time, or after you do something specific? Also, what's the specific Whoops message?

**Comment by tanguyngoy** [comment]
Sorry for the late reply.

This is after a long idle time. Usually we would input 1 or 2 assets, logout, then we will get the Whoops message the day after. There are no other error message, just the plain 'Whoops' at the top of the page.

I don't experienced it before in CentOS. Is it possible that this is an OS issue?

Thanks in advance.

**Comment by tanguyngoy** [comment]
Hi,

Still having this problem. Any form of help will be much appreciated.

Thanks in advance.
