### ISSUE TITLE
Additional LDAP Fields

### ISSUE THREAD

**Issue by Horst-R** [snipe/snipe-it#3373]
Hi,

currently only few fields are synchronized from LDAP.
What I really miss isthe synchronization of fields like Company, Location or Phone.
As Company is required for "Full Multiple Companies Support".
Is there a way to fill these fields with a command line utility? 

Thanks.

**Comment by ericdude101** [comment]
Has there been any progress on this issue or changes made?

**Comment by agentbb** [comment]
+1

**Comment by ericdude101** [comment]
Any progress to this issue?

**Comment by snipe** [comment]
If there were, we'd have updated this issue.

**Comment by ericdude101** [comment]
Im aware, however if nobody talks or asks updates, the reaiest gets closed by your bot and dissipears to never get acomplished... im not trying to stir up problems here, just request features.

**Comment by snipe** [comment]
This ticket is actually older than the original, #2853, so closing this as duplicate. Please subscribe to that thread if you want to follow the issue.
