### ISSUE TITLE
Generate app key not working

### ISSUE THREAD

**Issue by Koen-ilvo** [snipe/snipe-it#3377]
#### Expected Behavior (or desired behavior if a feature request)

according to https://snipe-it.readme.io/docs/generate-your-app-key the following command should generate a key and set the APP_KEY value in the .env file:

php artisan key:generate
-----

#### Actual Behavior

Nothing happens. The command produces no output and .env is not altered. This is the content of PHP71x64_errors.log

[02-Mar-2017 12:19:34 UTC] PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\Program Files\PHP\v7.1\ext\php_mysql.dll' - The specified module could not be found.
 in Unknown on line 0
[02-Mar-2017 13:19:34 Europe/Belgrade] PHP Warning:  require(C:\inetpub\wwwroot\snipe-it\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\inetpub\wwwroot\snipe-it\bootstrap\autoload.php on line 17
[02-Mar-2017 13:19:34 Europe/Belgrade] PHP Fatal error:  require(): Failed opening required 'C:\inetpub\wwwroot\snipe-it\bootstrap/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:\inetpub\wwwroot\snipe-it\bootstrap\autoload.php on line 17

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
3.6.4
- What OS and web server you're running Snipe-IT on
Windows Server 2012 R2 - IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
A quick google search returns this:
http://stackoverflow.com/questions/34903896/what-happened-to-php-mysql-dll
http://stackoverflow.com/questions/25415339/running-php-in-windows-how-to-fix-php-startup-unable-to-load-dynamic-library

**Comment by Koen-ilvo** [comment]
Thank you very much for your answer, it is much appreciated. 
The php_mysql.dll warning is gone after adapting php.ini. However, I keep running into the no file found error:

'C:\inetpub\wwwroot\snipe-it\bootstrap/../vendor/autoload.php'

in all variations of forward and back slashes, depending on changing the value of require __DIR__."/../vendor/autolaod.php in line 17 of autoload.php. Shouldn't there be a 'vendor' directory in the snipe-it root in order for this to work?
