### ISSUE TITLE
[Feature Request] Licenses: status field and ability to categorise licenses.

### ISSUE THREAD

**Issue by DinoPipeManager** [snipe/snipe-it#3380]
Adding a status field for software licenses like in assets so that licenses can be sorted/ viewed according to their status (archived, expired, disposed, pending renewal, trial etc.).

Additionally, having the ability to categorise software licenses (os, cad, graphics, etc) to make them more manageable.

Regards

DinoPipeManager

**Comment by DanPrs** [comment]
This sounds good!
