### ISSUE TITLE
Recieving PHP error when trying to access snipe-it

### ISSUE THREAD

**Issue by jasonbyatt** [snipe/snipe-it#3381]
#### Expected Behaviour (or desired behaviour if a feature request)

Loading the main page, would like to mention a restart fixes this issue. It also appears that snipe it has installed in the www directory and not the HTML directory is this correct?

#### Actual Behaviour

Receive the following error

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on - Ubuntu - 16.04 LTS 
- What method you used to install Snipe-IT - install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

1/1

PDOException in Connector.php line 55:

SQLSTATE[HY000] [2002] No such file or directory

1. in Connector.php line 55
2.at PDO->__construct('mysql:host=localhost;dbname=snipeit', 'snipeit', 'tuVdrKdySCrx6hWB', array('0', '2', '0', false, false)) in Connector.php line 55
3.at Connector->createConnection('mysql:host=localhost;dbname=snipeit', array('driver' => 'mysql', 'host' => 'localhost', 'database' => 'snipeit', 'username' => 'snipeit', 'password' => 'tuVdrKdySCrx6hWB', 'charset' => 'utf8', 'collation' => 'utf8_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => '/usr/local/bin', 'dump_command_timeout' => '300', 'dump_using_single_transaction' => true, 'options' => array(), 'name' => 'mysql'), array('0', '2', '0', false, false)) in MySqlConnector.php line 24
4.at MySqlConnector->connect(array('driver' => 'mysql', 'host' => 'localhost', 'database' => 'snipeit', 'username' => 'snipeit', 'password' => 'tuVdrKdySCrx6hWB', 'charset' => 'utf8', 'collation' => 'utf8_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => '/usr/local/bin', 'dump_command_timeout' => '300', 'dump_using_single_transaction' => true, 'options' => array(), 'name' => 'mysql')) in compiled.php line 11845
5.at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
6.at call_user_func(object(Closure)) in Connection.php line 924
7.at Connection->getPdo() in Connection.php line 792
8.at Connection->reconnectIfMissingConnection() in Connection.php line 677
9.at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure)) in Connection.php line 349
10.at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users')) in MySqlBuilder.php line 21
11.at MySqlBuilder->hasTable('users') in compiled.php line 6325
12.at Facade::__callStatic('hasTable', array('users')) in Setting.php line 65
13.at Setting::setupCompleted() in CheckForSetup.php line 22
14.at CheckForSetup->handle(object(Request), object(Closure))
15.at call_user_func_array(array(object(CheckForSetup), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
16.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
17.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
18.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in NosniffGuard.php line 17
19.at NosniffGuard->handle(object(Request), object(Closure))
20.at call_user_func_array(array(object(NosniffGuard), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
21.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
22.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
23.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in XssProtectHeader.php line 17
24.at XssProtectHeader->handle(object(Request), object(Closure))
25.at call_user_func_array(array(object(XssProtectHeader), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
26.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
27.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
28.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in FrameGuard.php line 17
29.at FrameGuard->handle(object(Request), object(Closure))
30.at call_user_func_array(array(object(FrameGuard), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
31.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
32.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
33.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 13474
34.at ShareErrorsFromSession->handle(object(Request), object(Closure))
35.at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
36.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
37.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
38.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 11964
39.at StartSession->handle(object(Request), object(Closure))
40.at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
41.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
42.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
43.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 145
44.at CheckForMaintenanceMode->handle(object(Request), object(Closure))
45.at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
46.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
47.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
48.at Pipeline->Illuminate\Routing\{closure}(object(Request))
49.at call_user_func(object(Closure), object(Request)) in compiled.php line 9948
50.at Pipeline->then(object(Closure)) in compiled.php line 2366
51.at Kernel->sendRequestThroughRouter(object(Request)) in compiled.php line 2350
52.at Kernel->handle(object(Request)) in index.php line 59

**Comment by snipe** [comment]
A quick google search turns up this:
http://stackoverflow.com/a/22927341/200021

(Do not change the line in your `config/database.php` though. It will inherit the environmental variable from your .env)
