### ISSUE TITLE
Importing assets does not work

### ISSUE THREAD

**Issue by ilealex** [snipe/snipe-it#3390]
#### Expected Behavior

Importing assets in snipe-it using .csv, as described here( https://snipe-it.readme.io/docs/importing ), does not work. I also used the example files provided to test.

This issue should be easily reproducible. You just need a Snipe-IT 3.6.3-3.6.4 installation, and try to import the example file from the documentation https://snipe-it.readme.io/docs/importing . 

-----

#### Actual Behavior

Error: The asset tag field is required. 
Error from log: {"":{"Asset":{"asset_tag":["The asset tag field is required."]}}}

![image](https://cloud.githubusercontent.com/assets/17266692/23651901/af26a320-032f-11e7-881b-a7a70a4fd93e.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode, but did not help me.
- [yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 3.6.4
- What OS and web server you're running Snipe-IT on Windows Server 2012 R2, IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual instalation.
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error <snipe-it>/hardware/import . I upload the file, than press the process buton. Also tried to import using php artisan snipeit:import but I get the same error: The asset tag field is required. 
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). Import feature is disabled on the demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. Cheked, but nothing helpful.
- Include what you've done so far in the installation, and if you got any error messages along the way. No errors.
- Indicate whether or not you've manually edited any data directly in the database. I didn't edit any data manually in the database.

**Comment by snipe** [comment]
Importing definitely works in all recent versions of Snipe-IT. (We have this version running on 500 or so customer systems and run imports every day.) Is there an asset tag in your data?  Can you show me your data, with sensitive info redacted?

**Comment by snipe** [comment]
(Also check for extra empty lines in the CSV. You won't be able to see them in Excel)

**Comment by ilealex** [comment]
I'm getting the errors using the sample CSV files from Snipe-IT documentation (https://snipe-it.readme.io/docs/importing).
My assets have some extra custom fields I use, some of them are set as required. Could that be the source of the problem?

**Comment by snipe** [comment]
That's certainly possible. If a custom field is required and it's not provided in the CSV, validation will fail.
