### ISSUE TITLE
REQUEST- Full Purchase Order Integration

### ISSUE THREAD

**Issue by DanPrs** [snipe/snipe-it#3394]
#### Expected Behavior (or desired behavior if a feature request)

I'd like to be able to attached a purchase order document and view it. But even more than that, it'd be great to be able to generate POs right from SnipeIT. With the option for send it off to user(s) to sign off on them for approval. 

Maybe if we could upload an xls/pdf with the totals, and then have it forward to recipients for approval. We'd like to see the signature on the actual document. That way we could print it and see approved by *user name, *signature. That'd be great. 

-----

**Comment by lcudmore** [comment]
I'd be happy with even PO document referrals.  Purchase Orders are done by our Purchasing department but we have copies of the documents for reference in our IT department for warranty info.
It would be nice to attach the documents to a single PO record that could be referenced from the Asset as a single PO could have many assets and components on it.
