### ISSUE TITLE
User Hyperlinks not respecting custom server port

### ISSUE THREAD

**Issue by tzielinskiaptn** [snipe/snipe-it#3395]
#### Expected Behavior (or desired behavior if a feature request)

When I click on a user link from either the assets or people pages, I expect to be shown the correct user page, as an example:

http://snipeit.domain.local:8080/admin/users/49/view 

#### Actual Behavior

I get sent to http://snipeit.domain.local/admin/users/49/view, which triggers a 404 error, because that resource does not exist on my server.

I'm currently able to get around it by clicking on users from asset property pages, because those links seem to respect the custom port I have set up.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Stable Build 3.6.4 
- Server 2012 R2 with IIS 8
- Manual installation
- No error beyond the 404 error
- This occurs on the /hardware and /admin/users pages, when I click on any username in the checked out to column
- This error doesn't occur in the demo, but it does not appear to use a custom port
- My installation is complete and has been running well for quite some time. This is the only bug I've noticed so far in my day to day use
- I have not manually edited the database

**Comment by snipe** [comment]
Pretty sure this has been fixed in the upcoming v4
