### ISSUE TITLE
Unable to Rename the file to .env

### ISSUE THREAD

**Issue by balaji040890** [snipe/snipe-it#3396]
Hi 

i'm trying to configure the snipe-it using xampp in windows and i have followed  below step  as per your suggestion 

but i'm unable to rename .env  file .is it possible in windows  

Step 1 : i have configure the Apache ( virtual host ) 
Step 2 :  Install the composer using xampp shell 
Step 3  : i'm trying to  run mention cmd " **php artisan key:generate** " and i'm getting the error  " file not found " . 

![image](https://cloud.githubusercontent.com/assets/26299527/23781437/55b3e384-0573-11e7-829e-fdb6258b924d.png)

**Comment by therealjoshuad** [comment]
I've found using the command line will allow you to rename the file to .env, using the GUI won't let you create it.

**Comment by therealjoshuad** [comment]
https://superuser.com/questions/64471/create-rename-a-file-folder-that-begins-with-a-dot-in-windows

**Comment by snipe** [comment]
That's not really a Snipe-IT issue, that's a Windows Explorer issue. We don't recommend using the GUI for renaming files.
