### ISSUE TITLE
GUI not updating Checkin/Checkout button

### ISSUE THREAD

**Issue by sphere720** [snipe/snipe-it#3397]
#### Expected Behavior (or desired behavior if a feature request)

Checking in an asset should switch the button to Checkout in the GUI line.
Checking out an asset should switch the button to Checkin in the GUI line.

-----

#### Actual Behavior

Checkin the asset and the 'Checkin' button remains on that asset line. I get the "this asset was already checked in if I try to repeat the checking in process.
The opposite effect for those assets Checked Out.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
Version v3.6.4 build 12 (gf7e4fca)
- What OS and web server you're running Snipe-IT on
Windows Server 2012 Standard
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No error in browser
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
All Assets list
- If a stacktrace is provided in the error, include that too.
None
- Any errors that appear in your browser's error console.
None
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
Yes. It appears to be [reproduceable on the demo]
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
None
- Include what you've done so far in the installation, and if you got any error messages along the way.
None
- Indicate whether or not you've manually edited any data directly in the database
No direct manual editing to the database

**Comment by snipe** [comment]
Where are you seeing this reproducable on the demo?

**Comment by sphere720** [comment]
Same page. The asset list. After I checked in an asset, and it took me back
to the listing; the button remained as Checkin when it should've then been
Checkout.

Donald Counts

On Mar 10, 2017 6:23 PM, "snipe" <notifications@github.com> wrote:

Where are you seeing this reproducable on the demo?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/snipe/snipe-it/issues/3397#issuecomment-285821167>, or mute
the thread

**Comment by snipe** [comment]
I'm not able to reproduce this.

<img width="1296" alt="screen shot 2017-03-10 at 6 49 48 pm" src="https://cloud.githubusercontent.com/assets/197404/23819914/a5426c50-05c2-11e7-9b4c-5cc660370c97.png">
<img width="1300" alt="screen shot 2017-03-10 at 6 50 00 pm" src="https://cloud.githubusercontent.com/assets/197404/23819915/a5434de6-05c2-11e7-98ad-93c21d7c579b.png">
<img width="1304" alt="screen shot 2017-03-10 at 6 50 14 pm" src="https://cloud.githubusercontent.com/assets/197404/23819916/a5440ac4-05c2-11e7-9721-b9810a11d3b9.png">
<img width="1295" alt="screen shot 2017-03-10 at 6 50 34 pm" src="https://cloud.githubusercontent.com/assets/197404/23819917/a5564e28-05c2-11e7-9aab-97c034b932e8.png">

**Comment by sphere720** [comment]
Strange. Which browser are you using?  I've only tried this on Chrome and
when I first noticed it was while training one of our TX location office
managers. She was on Firefox. When I submitted the bug ticket, I was
reproducing it while using Chrome as well. I'll try in Firefox and IE when
I get back to work on Monday and report back (with screenshots). Thanks.

Donald Counts
Exent Studio Productions Co.
Audio Engineer/Artist
405-638-8922

**Comment by snipe** [comment]
Chrome. I'm more interested in specific ID numbers of assets. It's not likely to be a browser issue.

**Comment by sphere720** [comment]
Ok. I will gather that info for you Monday. Thanks Snipe!

Donald Counts
Exent Studio Productions Co.
Audio Engineer/Artist
405-638-8922

**Comment by sphere720** [comment]
Well. Now I'm unable to reproduce it
[image: Inline image 1]

Donald Counts
Exent Studio Productions Co.
Audio Engineer/Artist
405-638-8922

**Comment by sphere720** [comment]
Everything seems to be working fine again. Not sure what the deal was. Except maybe just on a particular asset that I will have to pin down the next time it rears it's head. Sorry for the confusion. Closing this.

**Comment by snipe** [comment]
Maybe take a look at the specific status label the asset is assigned to, if you find that error again. If the status label *type* isn't deployable, it won't ever let you deploy it (since the type is considered undeployable.)

**Comment by sphere720** [comment]
Ah. That makes a lot of sense. They were part of a large asset import and I
probably just missed a couple when I was manually switching them to "Ready
to Deploy". Thanks for the tip. Sorry for the false alarm.

Donald Counts
Exent Studio Productions Co.
Audio Engineer/Artist
405-638-8922
