### ISSUE TITLE
New Asset Input - Drop Down Menu Model - Sort - Feature Request

### ISSUE THREAD

**Issue by linnearh** [snipe/snipe-it#3398]
#### Expected Behavior (or desired behavior if a feature request)

When I go to add a new asset and I use the drop down menu for 'Model'  I would expect there to be a sort on this drop down.   By 1st: Manufacturer   2nd: Model Name  3rd: Model Number

I like that you can type and it will filter but not all users use this option and it would be nice if there was a sort as well. 

Thanks
Linnea

-----

#### Actual Behavior

It seems to populate this drop down by the order entered into the database.

-----

#### Please confirm you have done the following before posting your bug report:

n/a - [ ] I have enabled debug mode
n/a - [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

V 3.6.3 build 15 - Version of Snipe-IT you're running
Linux - What OS and web server you're running Snipe-IT on
manual - What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
No error - Feature Request - WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

**Comment by snipe** [comment]
It's unlikely that we would develop that feature, as the use case would be pretty small. I would consider accepting a pull request if someone put one together though.
