### ISSUE TITLE
REQUEST: Checkout request date / comments

### ISSUE THREAD

**Issue by Choeoqe** [snipe/snipe-it#3399]
Hi, it would be great if when requesting the checkout of an asset, users could enter the date they require it; alternatively maybe a comments field or other custom fields could be added to the request page.

This is with a view to users being able to fill in why they need something, or where they need it and when (eg Location: Conference room A, Date: 3/14/17, Time: 4pm).

**Comment by bwerst** [comment]
I second this request, but would want even more information.

Why - memo
Needed - Date/Time
Expected Return - Date / Time
Approved by User - user_id (This does open whole issue of who can approve which assets being checked out)

Once this functionality is in the forms and database it would be awesome to pull up a calendar/timeline that shows when "selected" assets are reserved and/or actually checked out.

In our case I would love a user to be be able to make a list of assets they will need for an upcoming event.  Enter the date range and then be able check availability and then turn it into a bulk request / reservation.  Later they can only check out assets that have been approved.

**Comment by Cobra1978** [comment]
Hi.

In addition to this, it whould be great if is possible to select the user (the Area Manager for us) who can approve the item reservation requests.

Thanks.

**Comment by grifu** [comment]
I agree with bwerst. The request could be addressed by mail to a specific User to be approved. This user (ie. professor) could analyse the reason why the equipment is being requested, and aprove the request. Then the request could be addressed to the managers to check the dates.
A time field is also important, someone could checkin the equipment in a specific hour, allowing others to checkout the same equipment in a known time.
