### ISSUE TITLE
Unable to generate key Windows server

### ISSUE THREAD

**Issue by ahart8786** [snipe/snipe-it#3405]
#### Expected Behavior (or desired behavior if a feature request)

php artisan key:generate command brings up errors
-----

#### Actual Behavior
This is the output I get;

`C:\inetpub\wwwroot\Snipe-IT>php artisan key:generate
PHP Warning:  require(C:\inetpub\wwwroot\Snipe-IT\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\inetpub\wwwroot\Snipe-IT\bootstrap\autoload.php on line 17

Warning: require(C:\inetpub\wwwroot\Snipe-IT\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\inetpub\wwwroot\Snipe-IT\bootstrap\autoload.php on line 17
PHP Fatal error:  require(): Failed opening required 'C:\inetpub\wwwroot\Snipe-IT\bootstrap/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\inetpub\wwwroot\Snipe-IT\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\inetpub\wwwroot\Snipe-IT\bootstrap/../vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\inetpub\wwwroot\Snipe-IT\bootstrap\autoload.php on line 17`
-----

#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 3.6.4
- What OS and web server you're running Snipe-IT on Windows Server 2016 IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Git Clone/manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error artisan key generation
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. No issues up to this point
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/common-issues#section-warning-requirebootstrapvendorautoloadphp-failed-to-open-stream-no-such-file-or-directory

**Comment by ahart8786** [comment]
I can't believe I missed that looking over the issues before. Thank you
very much for your response!

**Comment by snipe** [comment]
It happens :) There's a lot of info to digest. Did that resolve your issue?

**Comment by ahart8786** [comment]
Yes! I was able to get the key generated. Still can't get the site to show
up but I'll poke around and figure out what went wrong. Thank you again!
