### ISSUE TITLE
FEATURE REQUEST - Add Serial # for Accessories

### ISSUE THREAD

**Issue by veilig2000** [snipe/snipe-it#3408]
This is similiar to #2934.  I have accessories that have serial #'s and I would like to be able to store that info w/ the record.

**Comment by veilig2000** [comment]
It would also be ideal to be able to print a label for accessories as well.

**Comment by hamzab900** [comment]
We have headsets that we give to users. Headsets dont have asset tags but are tracked via Serial # so it would be nice to have this feature.

**Comment by chansinshan** [comment]
I hope accessorise can input serial number in version 4.

**Comment by martinduoit** [comment]
Just adding that I'd very much like to see this feature as well!

**Comment by wilsonlspacheco** [comment]
+1 to our company (Snipe-IT Hosted Client)

We bought a lot of accessories and components with S/N, it was important to us be able to manage the serial numbers. Or, in the limit, like the licenses, have a field of notes to put the serial number when we check-in the Accessory / Component to a User/Asset and can see the history of this accessory in a table with the notes field visible. It is also an alternative solution to us.

**Comment by wilsonlspacheco** [comment]
I understand that is a difficult thing to dev, but.. this is important feature too. 👍

**Comment by memtech3** [comment]
you could try custom fields

**Comment by chansinshan** [comment]
@memtech3 
no custom fields in accessory

**Comment by memtech3** [comment]
No Stale! BOOO!

**Comment by xarou** [comment]
yes please ! we would also like to recored accessories Serial #, and if they have no Serial, give them one !

**Comment by supafly69** [comment]
This is still a wanted feature....  Thank you in advance :)

**Comment by jbeyus** [comment]
ADD THIS FEATURE!

**Comment by aquapixie** [comment]
Bumping!!!!!! Deffo would love this feature... and assigning accessories to assets

**Comment by wildeep** [comment]
We treat computer monitors as accessories, and we'd love to be able to track them by serial number.

**Comment by ssmithsj** [comment]
would love this too!!!

**Comment by mr-kiou** [comment]
still needed

**Comment by prokoba** [comment]
+1
Still needed

**Comment by mardoqueo** [comment]
+1

**Comment by rasari03** [comment]
Hi, Still waiting for feature to add serial number to accessories, Please

**Comment by Godmartinz** [comment]
Best way I would go about tracking serial numbers for accessories right now is to write the serial number in the notes section upon checkout. You are able to search text in the notes field. 
Hope this helps.
<img width="810" alt="image" src="https://github.com/snipe/snipe-it/assets/47435081/d1f5fd03-4adc-4401-93b8-6cf24a229448">
<img width="810" alt="image" src="https://github.com/snipe/snipe-it/assets/47435081/da223a06-13cd-4a2a-ba08-e5e114677e15">
