### ISSUE TITLE
Internal server: 500 when trying to launch Snipe-IT website.

### ISSUE THREAD

**Issue by petrus2014** [snipe/snipe-it#341]
Hello all

I have installed and configured Snipe-IT on a Windows Server 2008 R2 server with IIS. However when I try to browse the website or launch it from a browser I keep getting an internal server error 500. Could someone please help me solve this issue?

TIA
Pierre

**Comment by rajithabi3** [comment]
Hi ,

I was struggling this for long time and be able to fix this issue by giving approproate permisions for the folders and by entering the correct application key in the app.php file which generated during the installation process. Always check you r logs which will give you an idea on what's causing the problem which can be found in the directory app/storage/logs.

**Comment by yekski** [comment]
Hello Snipe
Im on my 2nd day of installing and trying to figure out how to run snipe-it.
using just IP is fine with me so as to isolate the issue. I managed to install everything and was able to display up to http://192.168.100.100/snipe-it/ (showing content of the folder) but when i clicked the public Im still getting the page not found error.

pls help. what i else do i need to check.

thanks in advance

**Comment by snipe** [comment]
@yekski please see the first section in http://snipeitapp.com/documentation/common-issues/

**Comment by snipe** [comment]
Also, please open a new issue in the future, versus commenting on an unrelated closed issue. Everyone who has contributed to this thread gets notified on replies, and your issue has nothing to do with their issue.

**Comment by MoVill** [comment]
Hello Snipe,
I discovered Snipe-IT (2) days ago and decided to try it out and setup the host for it. I'm writing on this thread because I'm experiencing http 500 error as well when trying to launch Snipe-IT. I've look unto logs and didn't find any error there. I have a MySQL DB that's it connected and running fine. I couldn't get into the PHP log because I couldn't find it. Do you have any other suggestions for to be able to traced the issue? Thanks.

**Comment by snipe** [comment]
@MoVill - as mentioned above, please do not resurrect old, unrelated threads. Create a new thread with your issue. (There are endless reasons why one might get a 500 error.)

Please start a new issue and include the information in the ticket template and we'll see if we can help you.
