### ISSUE TITLE
Ability to change email description when system emails user

### ISSUE THREAD

**Issue by viclou** [snipe/snipe-it#3413]
#### Expected Behavior (or desired behavior if a feature request)

create a way we can change the following:
 
1.  When system sends an email it is sending as following, is there a way we can change this.
2.  Is there a way for different companies defined in system, uses a different title of the “from” email address?
a.       For example: from below:
b.       Users get an email from ID 2 with the company name of ID 2 as the incoming email address, if they are part of this company.

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
I don't understand what's being asked in part 1. Part 2 (using company-specific info in FROM: field in emails) is not currently possible but we can consider it.

**Comment by TMIsnipeIT** [comment]
I have checked the "Asset acceptance" in my super admin Settings.
But on Assigning the asset to the user, there is no response through email that asset was assigned to particular user.
Please inform further settings what should do for the email processing to the user and also asset acceptance signature by the user.
please inform this as soon as possible.
Thank you.
