### ISSUE TITLE
Ability to hide user profile

### ISSUE THREAD

**Issue by viclou** [snipe/snipe-it#3415]
#### Expected Behavior (or desired behavior if a feature request)

One of the typical use-cases we need to support is: someone wants to transfer software to a different person at the same location.
If they change the first and last name it gives the appearance that the software is transferred; but, the email address remains unchanged. 
So, I was thinking: If they didn't have access to the profile, that it would help the user to ask for assistance with that use-case.

Hence, my thought that it would reduce confusion and support cost for us if we were able to hide the profile.

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
I don't understand what's being asked here. The checkin/checkout process should be used for licenses being checked in and checked out. The licensed_to name is only for licenses where the license granter requires a name to be associated with the license.
