### ISSUE TITLE
Bulk deletion of asset models

### ISSUE THREAD

**Issue by viclou** [snipe/snipe-it#3416]
#### Expected Behavior (or desired behavior if a feature request)

“select all” to perform a large scale deletion of asset models

-----

#### Actual Behavior

We had attempted an import that wasn’t quite right and deleted the assets.  However this auto created 400 some asset models.  Unlike assets there is no “select all” to perform a large scale deletion of these items.  Is there anyway to delete all of them quickly?  (one at a time with two clicks each is not ideal!)
 

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by SylentBobNJ** [comment]
+1 ability to delete assets from the asset model view

**Comment by snipe** [comment]
@SylentBobNJ I don't think that's what this ticket refers to. Just bulk deleting asset models. not bulk deleting assets within those asset models.

**Comment by SylentBobNJ** [comment]
@snipe whoop, sorry about that.  I'll try and find the right issue to +1, then (or open a new one).  

Thanks!

**Comment by snipe** [comment]
@SylentBobNJ FYI, I just pushed out some updates to allow bulk editing/deleting of assets from the models asset listing page. 

<img width="1429" alt="screen shot 2017-12-12 at 7 16 52 am" src="https://user-images.githubusercontent.com/197404/33892023-8c5e360a-df0c-11e7-968b-88bdd6da854d.png">

(This doesn't affect the OP's original request, but thought you'd like to know.)

**Comment by farizazmi** [comment]
@snipe , Sorry to bugging here, but i think the bulk delete function should be everywhere in the listing page. I've the same issue with import earlier which causing unexpected "status label" created out of 400++ records. Guess what am i supposed to do right now? Mouse > delete button > click yes > wait > then repeat. btw, that is where am i coming from, hopefully there will be consideration for this. Snipe is a great tools. I really like it  +1

**Comment by snipe** [comment]
> Sorry to bugging here, but i think the bulk delete function should be everywhere in the listing page

I don't understand what you mean here.

Bulk deleting models is already in the the upcoming v5.

**Comment by BrainHurts** [comment]
You can only delete models with no inventory assigned to them. Is it possible to delete assets in bulk? We uploaded a test batch of inventory and want to make some changes before we dump the rest in so we have to roll back the server to purge these test records out efficiently since it looks like you can only do this from the Asset list 20 at a time.
