### ISSUE TITLE
Ability to allocate individual assets to a category - for EULA purposes

### ISSUE THREAD

**Issue by Stev-e** [snipe/snipe-it#3423]
#### Expected Behavior (or desired behavior if a feature request)

Ability to assign assets themselves to categories 

-----

#### Actual Behavior

Can only assign models to categories

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running **3.6.4**
- What OS and web server you're running Snipe-IT on **Centos7 Nginx latest**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Manual - Git**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
That's a pretty big architectural change, so it's unlikely to be done. What's the reasoning behind it?

**Comment by Stev-e** [comment]
Fair enough! For where I work (a school) we have some assets that can be checked out for use around the site or off site. However the models that are used for this are also used on site either in a facility that isn't booked out (say a trolley full of laptops, of the same model that can be taken home)

It's a unique situation and one most probably won't encounter especially with the upcoming ability to check assets to locations etc

Sorry if I wasted your time :)

**Comment by snipe** [comment]
Hmm.. how would your use case affect categories though? Categories+models are meant to describe the type of asset it is (laptop, desktop, etc) and that doesn't really change regardless of where something is assigned. A 13" Macbook Pro doesn't stop being a 13" Macbook Pro just because it's on a trolly. I'm curious to better understand the problem you're trying to solve.

**Comment by Stev-e** [comment]
You have highlighted the flaws in my thoughts to be honest, though my thought process was along the lines of;

We have staff and students borrowing kit, some of the terms we impose on students differs to those imposed on staff. 

This is a non-issue now really I think whatever went through my mind when I posted this has gone

Really sorry for wasting time!
