### ISSUE TITLE
Snipe URL loads It Works! page

### ISSUE THREAD

**Issue by furby** [snipe/snipe-it#3424]
#### Expected Behavior (or desired behavior if a feature request)

When I go to the Snipe-IT URL it starts the preflight pages.

-----

#### Actual Behavior

It takes me to a page that says "It Works!"

-----

#### Please confirm you have done the following before posting your bug report:

- [ Yes] I have enabled debug mode
- [ Yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running

3.6.4

- What OS and web server you're running Snipe-IT on

MacOS 10.12.3
Server version: Apache/2.4.23 (Unix)

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

Manual Install

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

I don't get any error, I just can't access the web server pages.

- If a stacktrace is provided in the error, include that too.
N/A
- Any errors that appear in your browser's error console.
N/A
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).

No, not really applicable
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
Apache doesn't show any error logs. 

- Include what you've done so far in the installation, and if you got any error messages along the way.

I followed the MacOS/Unix instructions. The last successful step was generating my App Key.
I have not seen any errors
- Indicate whether or not you've manually edited any data directly in the database

No

**Comment by snipe** [comment]
Are you sure you're using apache? That looks like a valet error.

**Comment by furby** [comment]
Hi Snipe, yes, I'm using Apache. I think it is going to 
`/Library/WebServer/Documents`
When I load the url rather than the snipe pages.

My vhosts file is:

`<FilesMatch ".+\.html$">
  SetHandler application/x-httpd-php
</FilesMatch>

<Directory "/usr/local/snipe/public/">
	Allow From All
	AllowOverride All
	Options +Indexes
</Directory>

<VirtualHost *:80>
	ServerName "snipe.localhost"
	DocumentRoot "/usr/local/snipe/public/"
</VirtualHost>`

Which I think is correct. Could I be missing something?

**Comment by furby** [comment]
A bit of progress. I realised I hadn't uncommented 

```
# Virtual hosts
#Include /private/etc/apache2/extra/httpd-vhosts.conf
```
from my httpd.conf file.

Now when I run httpd -S I get 
```
mbp02:~ furby$ httpd -S
VirtualHost configuration:
*:80                   snipe.localhost (/private/etc/apache2/extra/httpd-vhosts.conf:33)
ServerRoot: "/usr"
Main DocumentRoot: "/Library/WebServer/Documents"
Main ErrorLog: "/private/var/log/apache2/error_log"
Mutex default: dir="/private/var/run/" mechanism=default 
Mutex mpm-accept: using_defaults
Mutex rewrite-map: using_defaults
PidFile: "/private/var/run/httpd.pid"
Define: DUMP_VHOSTS
Define: DUMP_RUN_CFG
User: name="_www" id=70 not_used
Group: name="_www" id=70 not_used
```
Which looks broadly correct. Still doesn't work but perhaps a little closer

**Comment by furby** [comment]
After I restarted Apache and cleared the artisan cache I got a permission denied message.
I made sure permissions were correct and then add
my vhosts <Directory>
 **Require all granted** to 
</Directory>

No permissions error but when I go to http://snipe.locahost I just get a blank page and Apache access.log just gives a 500 note.

**Comment by furby** [comment]
If there's someone who's successfully managed to install on MacOS I'd be grateful if they could post. Just so I know if I should keep trying or not. 

I still can't get it to load :(

**Comment by roycepope** [comment]
@furby Take a look at issue #3321
