### ISSUE TITLE
non-QR Barcodes on lables not scannable

### ISSUE THREAD

**Issue by leobg** [snipe/snipe-it#3425]
#### Expected Behavior (or desired behavior if a feature request)
non-QR barcodes to be generated in black and white (no gray scale gradations just like QR codes)
-----

#### Actual Behavior
non-QR (C39/C128....) barcode lines are not sharp (instead B/W it uses gray scale/smudging) which makes them pretty much non-scannable. QR codes are OK.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running *Version v3.6.3 build 15 (g1bf34d7)*
- What OS and web server you're running Snipe-IT on *CENTOS 7*
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) *manual install*
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). *YES - same there*
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by Jason-Weber-UC** [comment]
I can confirm this; arguing with the same issue myself

**Comment by Jason-Weber-UC** [comment]
I can also confirm that switching from GD to imagemagick makes no difference.

**Comment by snipe** [comment]
Can you show me an example of an affected barcode?

**Comment by snipe** [comment]
(We are able to scan the barcodes on the demo, using a bluetooth barcoce scanner, so we cannot really reproduce this issue.)

**Comment by i5rov** [comment]
If you print it on a label most scanners won't read it.

**Comment by Jason-Weber-UC** [comment]
Admittedly I'm currently printing to a laser printer; still waiting for my proper label printer to arrive.
Am about to try printing to a normal Dymo label printer in a little while.
Once ive done that, I'll try and post up some sample, although it's hard when its on paper :)

**Comment by leobg** [comment]
As I reported originally, QR codes look and work perfect. Non-QR codes are generated with grayscale gradations which makes print output especially on a low resolution bar code printer looking fuzzy and unreadable by a common barcode scanner (such as older Motorola symbols). I ended up generating the labels in dedicated barcode software until snipeit is fixed.

**Comment by snipe** [comment]
This may sound dumb, but maybe post a photo of the printed result? Every time we modify the barcodes, we print out several pages of them and make sure that they still scan properly, so it's hard for me to reproduce this. (Our printer is nothing fancy, B&W HP Laserjet P 1102W.)

**Comment by Jason-Weber-UC** [comment]
I gotta say, it *looks* fine, but zooming on the photos it does kinda look fuzzy.
I should also point out that the scanner works fine on any other barcode I can find kicking around my office.

![20170510_143012](https://cloud.githubusercontent.com/assets/28076245/25883389/95fb767e-358d-11e7-90b6-077eb1c5b756.jpg)

**Comment by Jason-Weber-UC** [comment]
Just for giggles, I tried from Safari (instead of FFox), thinking it may be the browsers print engine - nada.

**Comment by Jason-Weber-UC** [comment]
if its helpful; its running on a Debian 8 server. Installed using install.sh
Attached is the phpinfo (its not publicly accessible.)
[phpinfo.pdf](https://github.com/snipe/snipe-it/files/989533/phpinfo.pdf)

**Comment by Jason-Weber-UC** [comment]
@snipe - just to lay one other possibility to rest - what browser are you using for your testing? Mac/PC?
Just so I can try and replicate your 'working' situation.

**Comment by snipe** [comment]
I've used Chrome and Safari on OSX

**Comment by Jason-Weber-UC** [comment]
Nut's - there goes that theory.
Although it does take one possibility (the client end) out of the equation.

**Comment by Jason-Weber-UC** [comment]
Got my label printer.
Issue is more obvious

![20170511_132343](https://cloud.githubusercontent.com/assets/28076245/25932626/c03407bc-3655-11e7-9be9-58f1a0ae45d0.jpg)

**Comment by Jason-Weber-UC** [comment]
@snipe - I really am sorry for spamming this thread, but I *kinda* figured more info is better than none.

For the sake of it, I File --> Print --> Save as PDF.
You can *really* see the grey edges now.

![screen shot 2017-05-11 at 3 14 24 pm](https://cloud.githubusercontent.com/assets/28076245/25933741/b90aaaac-365c-11e7-864f-eaa4b9fb88bd.jpg)

**Comment by leobg** [comment]
@jason - thanks for posting all pics. This is exactly the issue I reported. QR codes are not affected, only linear ones. When you print this on a 200dpi BW label printer on a 1 inch wide label result is unscannable​ barcode.

**Comment by BrettFagerlund** [comment]
The easiest way to check is just pick an asset, hit generate labels with a 1D, and zoom to 500% on browser. The 1D barcode image gets very fuzzy as oppose to the text or the label border. 

Or access directly via /hardware/[ID]/barcode then zoom 500%.

**Comment by Jason-Weber-UC** [comment]
I wonder if it could php-GD doing some kind of anti-aliasing?

**Comment by BrettFagerlund** [comment]
Just did a bit more testing and there appears to be a hard coded width of 250px which is stretching out the bars causing the difficulty reading on some devices, if i remove this limit and let the width generate dynamically the barcodes are reading almost instantaneously across all our devices.

There is a risk that a very long name will stretch over the label though.

**Comment by Jason-Weber-UC** [comment]
@BrettFagerlund  How did you do this? I'd like to give it a go?

**Comment by BrettFagerlund** [comment]
@Jason-Weber-UC
first go into the public/uploads/barcodes folder and clean out the existing barcodes, it will use the existing images if they already exist so you need to clear it to regenerate.

Then go to app\http\controllers\assetscontroller.php 
Find the function getBarCode
Inside that function there will be a line

`$barcode_obj = $barcode->getBarcodeObj($settings->alt_barcode, $asset->asset_tag, 250, 20);`

replace the 250 with ''  (2 apostrophes) so it will be like 

`$barcode_obj = $barcode->getBarcodeObj($settings->alt_barcode, $asset->asset_tag, '', 20);`

**Comment by Jason-Weber-UC** [comment]
*DING*!!!
Brilliant.

**Comment by leobg** [comment]
@jason does this patch solve the 2d barcodes fuzziness?

**Comment by BrettFagerlund** [comment]
@leobg I still have a bit of fuzziness on the barcodes, but the readability is a lot better since the bars are not being stretched out.

Not sure how much more can be done without switching over to svg. I've also added in custom css to fix the zooming and make it look cleaner but it seems to always print a bit fuzzy regardless of how it looks on screen.

**Comment by Jason-Weber-UC** [comment]
Put it this way -  can now scan them. SO for me at least - Problem solved.

Whats this CSS file?

**Comment by BrettFagerlund** [comment]
its kinda unncessary, but once logged in I went to options and added the following into the custom css box

```
img.barcode {
      image-rendering: pixelated;
}
```

It will just stop the browser messing with the image on zoom (well for chrome anyway)

**Comment by leobg** [comment]
I just tried with the resize hack Brett suggested, but I can't say it really addresses the problem. Bar code is no longer stretched along the length of the label, but rather on the middle. Still fuzzy. I am no programmer, but I am curious if possible to use the same approach as for QR codes (which are drawn perfectly) for line bar codes?
