### ISSUE TITLE
Feature Request: Email notification to admins when asset checkout is declined. 

### ISSUE THREAD

**Issue by fatgeek** [snipe/snipe-it#3427]
#### Expected Behavior (or desired behavior if a feature request)

An email be sent to admins that an asset checkout has been declined. 
-----

#### Actual Behavior

No notification is sent. The information is only available by seeking it out via the asset history, user history, or activity report. 
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running:  v3.6.3 build 15 (g1bf34d7)
- What OS and web server you're running Snipe-IT on: Hosted
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): N/A
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by golebiewsky** [comment]
Please repoen this!
