### ISSUE TITLE
Custom Field cannot be creation when exist same number of non-latin characters

### ISSUE THREAD

**Issue by fofwisdom** [snipe/snipe-it#3428]
#### Expected Behavior (or desired behavior if a feature request)

Created Custom Filed for 임대원가
-----

#### Actual Behavior

> CustomField {#750 ▼
>   +guarded: array:1 [▼
>     0 => "id"
>   ]
>   +rules: array:1 [▼
>     "name" => "required|unique:custom_fields"
>   ]
>   #connection: null
>   #table: null
>   #primaryKey: "id"
>   #keyType: "int"
>   #perPage: 15
>   +incrementing: true
>   +timestamps: true
>   #attributes: array:6 [▼
>     "name" => "임대원가"
>     "element" => "text"
>     "field_values" => ""
>     "field_encrypted" => "0"
>     "user_id" => 1
>     "format" => ""
>   ]
>   #original: []
>   #relations: []
>   #hidden: []
>   #visible: []
>   #appends: []
>   #fillable: []
>   #dates: []
>   #dateFormat: null
>   #casts: []
>   #touches: []
>   #observables: []
>   #with: []
>   #morphClass: null
>   +exists: false
>   +wasRecentlyCreated: false
> }

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- v3.6.4 build 12 (gf7e4fca)
- Ubunutu 16.10 (Linux ams 4.8.0-22-generic #24-Ubuntu)
- install.sh
- WITH DEBUG TURNED ON, No error logs.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- Confirm whether the error is reproduceable on the demo (https://snipeitapp.com/demo).
- https://www.youtube.com/watch?v=Qs5eLBtdeMk

**Comment by fofwisdom** [comment]
Root Cause: Snipe-IT is not converting to latin field name.
![2017-03-15 17 29 38](https://cloud.githubusercontent.com/assets/205521/23939784/9bc2bab8-09a5-11e7-9e10-c689b14ae2b2.png)

**Comment by fofwisdom** [comment]
BUMP

**Comment by snipe** [comment]
I believe this should be fixed in the upcoming v4
