### ISSUE TITLE
Bulk Check-In (Feature or inquiry)

### ISSUE THREAD

**Issue by mechanicalsheep** [snipe/snipe-it#3429]
#### Expected Behavior (or desired behavior if a feature request)
I don't know if i'm in the right place to post this, and please correct me if i'm not.
I have recently installed Snipe-IT and it's pretty sweet! However, I had an inquiry I was hoping you could answer:
I currently have some assets that get borrowed (tablets that I need to keep track of) quite frequently, I am able to bulk check-out a few tablets to a user, however I am unable to check them back in without either checking them in one by one, or using Bulk Check-In Assets and deleting the user, is there any other way to check in multiple selected assets from the "Deployed" view?

Thank you so much for your ongoing support
-----

#### Actual Behavior

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running : v3.6.4 build 12 (gf7e4fca) 
- What OS and web server you're running Snipe-IT on: Xampp on Windows
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by SylentBobNJ** [comment]
I believe the ability to bulk check-in/check-out of assets/software licenses, etc has been requested and is in development under issue #1835

**Comment by mechanicalsheep** [comment]
SylentBobNJ, thank you for your response, however it seems the issue #1835 relates to bulk checkouts instead of checkins.  That feature has already been implemented.
