### ISSUE TITLE
Regular Expression in Custom Fields

### ISSUE THREAD

**Issue by Horst-R** [snipe/snipe-it#3430]
Hello

I assume it's a simple topic, but I'm really struggling with it.
I created a custom field with the field type custom format an now I try to define a regular expression to allow only the one character "Y" or "y" or "N" or "n".

Many thanks.

**Comment by snipe** [comment]
Hi - custom field regexes are documented here: https://snipe-it.readme.io/docs/custom-fields#section-custom-field-validation
