### ISSUE TITLE
Error when checking in asset

### ISSUE THREAD

**Issue by mattgann** [snipe/snipe-it#3434]
#### Expected Behavior (or desired behavior if a feature request)

Expect after checkin button is pushed to go back to dashboard

-----

#### Actual Behavior

Whoops, looks like something went wrong.

-
#### Please provide answers to these questions before posting your bug report:

- Version v3.6.3 build 15 (g1bf34d7) 
- 2012 R2
-  manual installation

- checkin button is pushed then get Whoops, looks like something went wrong.
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- not reproduceable on the demo

I dont have permission to use an SMTP server and they won't give me one EVER
Larvel:

2017-03-17 07:48:07] production.ERROR: exception 'Swift_TransportException' with message 'Connection could not be established with host ironport.ga.com [No connection could be made because the target machine actively refused it.
 #10061]' in C:\inetpub\wwwroot\snipe-it\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php:269
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php(62): Swift_Transport_StreamBuffer->_establishSocketConnection()
#1 C:\inetpub\wwwroot\snipe-it\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(113): Swift_Transport_StreamBuffer->initialize(Array)
#2 C:\inetpub\wwwroot\snipe-it\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#3 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(385): Swift_Mailer->send(Object(Swift_Message), Array)
#4 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(171): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#5 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(6329): Illuminate\Mail\Mailer->send('emails.checkin-...', Array, Object(Closure))
#6 C:\inetpub\wwwroot\snipe-it\app\Http\Controllers\AssetsController.php(691): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#7 C:\inetpub\wwwroot\snipe-it\app\Http\Controllers\AssetsController.php(691): Illuminate\Support\Facades\Mail::send('emails.checkin-...', Array, Object(Closure))
#8 [internal function]: App\Http\Controllers\AssetsController->postCheckin(Object(App\Http\Requests\AssetCheckinRequest), '1021')
#9 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9424): call_user_func_array(Array, Array)
#10 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9486): Illuminate\Routing\Controller->callAction('postCheckin', Array)
#11 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9466): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\AssetsController), Object(Illuminate\Routing\Route), 'postCheckin')
#12 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\Authenticate.php(45): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#17 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9467): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9454): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\AssetsController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'postCheckin')
#23 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8524): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'postCheckin')
#24 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8511): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#25 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8225): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#26 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckPermissions.php(28): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 [internal function]: App\Http\Middleware\CheckPermissions->handle(Object(Illuminate\Http\Request), Object(Closure), 'assets.checkin')
#30 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#31 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\Authenticate.php(45): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckForTwoFactor.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: App\Http\Middleware\CheckForTwoFactor->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#41 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#43 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckLocale.php(42): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 [internal function]: App\Http\Middleware\CheckLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#46 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#48 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(3225): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#51 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#53 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13213): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#56 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#58 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13150): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#61 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#63 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#64 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#65 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8226): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#66 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8217): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#67 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8207): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#68 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(2419): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#69 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#70 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#71 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#72 [internal function]: App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#74 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#76 C:\inetpub\wwwroot\snipe-it\vendor\fideloper\proxy\src\TrustProxies.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#77 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#78 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#79 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#80 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#81 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckForSetup.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#82 [internal function]: App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#83 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#84 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#85 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#86 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#87 [internal function]: App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#88 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#89 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#90 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#91 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\XssProtectHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#92 [internal function]: App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#93 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#94 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#95 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#96 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#97 [internal function]: App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#98 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#99 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#100 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#101 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13474): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#102 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#103 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#104 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#105 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#106 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(11964): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#107 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#108 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#109 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#110 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#111 C:\inetpub\wwwroot\snipe-it\vendor\misterphilip\maintenance-mode\src\MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode.php(145): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#112 [internal function]: MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#113 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#114 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#115 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#116 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#117 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#118 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#119 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#120 C:\inetpub\wwwroot\snipe-it\public\index.php(60): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#121 {main}

**Comment by snipe** [comment]
> 'Connection could not be established with host ironport.ga.com [No connection could be made because the target machine actively refused it.

Looks like your mail settings are incorrect. It's trying to send a notification email and is failing.
