### ISSUE TITLE
Feature Request : Link Fieldsets to Categories and Universal Custom Fields

### ISSUE THREAD

**Issue by skoonin** [snipe/snipe-it#3435]
#### Expected Behavior (or desired behavior if a feature request)

(tl;dr - would be great to link custom fieldsets to categories in addition to models and to be able to make some custom fields universally visible.)

I'm just testing out Snipe to replace our super over-priced system at my company. So far it's pretty great! I did notice one thing that would be a potential problem for us: the inability to link Fieldsets to Categories. 

I work at a tech company, so we have lots of different models of mobile phones.  The way fieldsets and categories are setup currently means that I would have to create each model in Snipe and then add a custom fieldset to each model.  Since they are all mobile phones, it would be way more helpful to be able to ensure that all mobile phones, regardless of model, get the same custom fieldsets. 

Also, I do like the fact that custom fields don't show up unless you select a asset with those fields assigned, but it would be great for custom fields to be able to show up for all assets when creating them.  That is, when creating a custom field to make it "always visible" or "only visible when it is part of a fieldset attached to a specific type of asset (category)"  For example, creating a custom field of "Condition" and that field being able to be assigned to all assets in the system regardless of category or model. 

It's possible these are all possible and I haven't figured out how to do it yet! If so, please point me in the direction of getting it to work this way, thanks! 

-----

#### Actual Behavior

Currently fieldsets have to manually linked to each model.  Also custom fields don't show up unless linked to a fieldset and then linked to a specific model.

-----

#### Please confirm you have done the following before posting your bug report:

- [No ] I have enabled debug mode
- [Yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: Version v3.6.4 build 12 (gf7e4fca)
- What OS and web server you're running Snipe-IT on: Ubuntu 14.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh

**Comment by SylentBobNJ** [comment]
+1 ability to use custom fields in other areas of the program (ie. asset model view)

**Comment by snipe** [comment]
> Since they are all mobile phones, it would be way more helpful to be able to ensure that all mobile phones, regardless of model, get the same custom fieldsets.

We might consider setting a "default custom fieldset for models in this category" option on the category level".

> Also, I do like the fact that custom fields don't show up unless you select a asset with those fields assigned, but it would be great for custom fields to be able to show up for all assets when creating them.

People already complain that the new asset form is too long for many of their needs. Additionally, it would lead to confusion where a user remembers that they entered a value for the field, but they're not seeing it in the item display because the field wasn't enabled on the asset model via custom fields. And also, custom fields have validation rules, including requiredness. If we made them available for all new assets, the requiredness would cause issues on assets that never intended to use those fields.

**Comment by skoonin** [comment]
Honestly anything you can do to help make custom fields more simple would be great.  But, primarily, allowing for a custom field to be set for an entire asset category like, say, Mobile Phones, would be amazing. 

Maybe you can also allow for asset fields to be hidden from view on the New Asset form (or just make things non-required)? That way people that complain about it being too long can shorten it.

**Comment by roborobs1023** [comment]
Has this feature been added?

**Comment by Shadowfita** [comment]
+1. Having fieldsets tied to entire categories would be fantastic.

**Comment by TinaMccray** [comment]
Yes we need custom fields for everything. Even locations so we can track the type of locations.

**Comment by andre-vanrensburg** [comment]
+1. This would allow for custom fieldsets to be used as specification forms, e.g. laptops all have the same components e.g. storage, memory, resolution, etc.

**Comment by TinaMccray** [comment]
What we are wanting is to be able to identify say a location as a classroom or office, and we want to track certain information per asset model. For instance max ram, ram slots available, or max ram per slot. This will be different for each model. It would be nice to be able to associate that information with the model so it would auto populate inside each asset.

**Comment by Kleimre** [comment]
This would make life so much easier +1

**Comment by MatthewDietrich** [comment]
+1 this would be a very useful feature.

**Comment by chili-fe** [comment]
+1

**Comment by mattytr2** [comment]
+1

**Comment by SandroZZattoo** [comment]
+1

**Comment by realSZone** [comment]
+1

**Comment by iamsumesh** [comment]
+1

**Comment by phynias** [comment]
wild custom fields still aren't tied to categories. 
+1
