### ISSUE TITLE
Asset acceptance through email 

### ISSUE THREAD

**Issue by TMIsnipeIT** [snipe/snipe-it#3440]
I have checked the "Asset acceptance" in my super admin Settings.
But on Assigning the asset to the user, there is no response through email that asset was assigned to particular user.
Please inform further settings what should do for the email processing to the user and also asset acceptance signature by the user.
please inform this as soon as possible.
Thank you.

#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by umerafridi** [comment]
Any update on this issue ?

**Comment by snipe** [comment]
If there was an update, we would have updated this ticket.

**Comment by snipe** [comment]
Do you have email notifications enabled at the category level? 

<img width="459" alt="update_category____snipe-it_asset_management" src="https://cloud.githubusercontent.com/assets/197404/24569325/713d08e4-161a-11e7-9374-eb8c4b360414.png">

**Comment by umerafridi** [comment]
yes i enabled forgot password not working also

**Comment by TMIsnipeIT** [comment]
Thank you.. Very Much. 
The emails are getting to the users.
But where can i see whether the user has signed or not for the asset assigned to the user.
