### ISSUE TITLE
while exporting Assets reports, assets assigned to users are coming as 'Ready to Deploy"

### ISSUE THREAD

**Issue by DhawalS** [snipe/snipe-it#3441]
#### Expected Behavior (or desired behavior if a feature request)

The assigned(checked-out) assets should have status as DEPLOYED in the asset report
-----

#### Actual Behavior

while exporting Assets reports, assets assigned to users are coming as 'Ready to Deploy"
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v3.2.0-53-gfff2bce
- What OS and web server you're running Snipe-IT on - CentOS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - NO
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - ASSET REPORT
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by DhawalS** [comment]
@snipe 
pls suggest!

**Comment by kenfrancisadams** [comment]
I am also experiencing this issue. I can reproduce it on the demo and have attached a screenshot of the demo. Checkout an asset to a user and the status is still 'Ready to Deploy' when you view the asset details:

![demo](https://cloud.githubusercontent.com/assets/18148599/24609704/b4b7432c-1873-11e7-8c60-1356e40f5d5f.PNG)

As you can see the item is checked out to a user but is still classed as 'Ready to Deploy' rather than 'Deployed'.

**Comment by DhawalS** [comment]
@snipe pls suggest

**Comment by tbradsha** [comment]
Deployed is not a true status. The actual status is "Ready to deploy", though in many places it shows a meta-status of "deployed" if the asset is assigned to someone as well as "ready to deploy".
