### ISSUE TITLE
Unable to Configure E-mail alerts on IIS

### ISSUE THREAD

**Issue by AquaGoat** [snipe/snipe-it#3442]
#### Expected Behavior (or desired behavior if a feature request)

I expect to receive alerts when assets or licenses are expiring within the value set in the Admin settings.

-----

#### Actual Behavior

No alerts arrive, no errors found anywhere.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - **3.6.3**
- What OS and web server you're running Snipe-IT on - **Windows Server 2012 R2, IIS 8**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - **Manual**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

I've got the alerts settings enabled in the Admin settings. E-mail sending does work, as I get requests for request-able objects, and the test email works from pre-flight with no problems. I've created items within the notification period, and I've had items age into the notification period, and am not receiving any notifications at all.

In the documentation for Snipe-It it does say "Starting from Snipe-IT v3.0, all automated tasks are handled via the scheduler." Is there something I need to configure in the Task Scheduler for this feature to work?

**Comment by snipe** [comment]
Yes, you need to set up a scheduled task to run the app scheduler.
