### ISSUE TITLE
Security Group doesn't allow asset deletion

### ISSUE THREAD

**Issue by rjkantor** [snipe/snipe-it#3443]
#### Expected Behavior (or desired behavior if a feature request)

The user has the ability to delete assets.

-----

#### Actual Behavior
I have a group that I have created and add users to this group.
Asset: Delete is enabled although when the user tries to delete the get the sad panda, invalid permissions mesage.
How do I fix?  I tried adding admin permission, did not help. 
Other ideas?

-----

#### Please confirm you have done the following before posting your bug report:

- [ XX] I have enabled debug mode
- [ XX ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running : 5.2.45
- What OS and web server you're running Snipe-IT on : Ubuntu / Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. no
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). no
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by Winthrop-Josh** [comment]
I too am experiencing the same issue. I have tried assigning the group permissions both the granular permissions without Admin selected, and with Admin selected and neither allows users in that group to delete assets. (Assets are delete-able as a Super Admin) 

Version: 3.6.6
OS: Windows Server 2012\IIS 7
Debug: Enabled - Errors attached
<img width="919" alt="queries" src="https://cloud.githubusercontent.com/assets/23202557/26565177/9b5fda18-451b-11e7-8c13-50c0a51342cf.png">
<img width="762" alt="gate" src="https://cloud.githubusercontent.com/assets/23202557/26565178/9b6acb08-451b-11e7-8784-f7efce84669c.png">
