### ISSUE TITLE
Install stuck during Setting Up LAMP in the background

### ISSUE THREAD

**Issue by 3DPixel** [snipe/snipe-it#3444]
#### Expected Behavior (or desired behavior if a feature request)

Ububtu Server:
During fresh install, LAMP server and default settings installed.

1) During snipe-it install, setup asks for FQDN and MariaDB password.
2) Adds MariaDB in background
3) Updates via apg-get
4) Upgrading packages in the background.
5) Install completes.

-----

#### Actual Behavior

Ubuntu Server:
Steps 1-4 complete.
Step 5 'Stuck Setting Up LAMP in the background'. Left it going for 90 minutes and still nothing.

Ubuntu Desktop:
Steps 1-5 completed successfully

-----

#### Please confirm you have done the following before posting your bug report:

- [N ] I have enabled debug mode - No because I can't enable anything until the install completes
- [Y ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - 3.6.2
- What OS and web server you're running Snipe-IT on - Ubuntu Desktop and Server 16
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Git and wget
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. - No
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by nashbrydges** [comment]
I actually ran into the same issue the first time I tried to install so I walked through the install script and discovered that if I got my LAMP install done manually and removed everything that wasn't related to Ubuntu, I could get the script to work. I had to modify the script and also noticed the composer install was running as root, but composer won't install as root. It has to be installed as a regular user so I documented my steps and posted this how-to. It was posted a few months ago but I tried this yesterday again and it still works with the most current version of Snipe-IT. Feel free to take a look and give it a try. (despite the title, my how-to is in fact for Ubuntu 16.04 - someone else had started the post and I added the Ubuntu steps to get past the issues I was having).

https://www.mangolassi.it/topic/6967/installing-snipe-it-on-centos-7-and-mariadb/84

**Comment by othyn** [comment]
I've just run into this issue and checked the log at `cat /var/log/snipeit-install.log`.

It's one of the packages prompting an interface requiring user input to complete.

More specifically `sudo dpkg --configure -a` from an update to grub.
