### ISSUE TITLE
Installation Windows 10 , WAMP server3.0.6 Snipe-it version   v3.6.4

### ISSUE THREAD

**Issue by aypdev** [snipe/snipe-it#3445]
I followed all the steps given at https://snipe-it.readme.io/docs/wamp.
It seems there is problem in setting up APP_URL & virtual hosts in Wamp (Last step of the guide).

.env file config:
[test.env.txt](https://github.com/snipe/snipe-it/files/858101/test.env.txt)

httpd.conf
[httpd.conf.txt](https://github.com/snipe/snipe-it/files/858106/httpd.conf.txt)

httpd-vhosts.conf

[httpd-vhosts.conf.txt](https://github.com/snipe/snipe-it/files/858109/httpd-vhosts.conf.txt)

Kindly help me resolve the issue.

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode - Yes
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) - Yes

**Comment by huyem83** [comment]
Replace yours with these and see if it work.

[httpd-vhosts.conf.txt](https://github.com/snipe/snipe-it/files/858412/httpd-vhosts.conf.txt)
[httpd.conf.txt](https://github.com/snipe/snipe-it/files/858413/httpd.conf.txt)

**Comment by huyem83** [comment]
Try changing APP_URL=http://assets.local

to 

APP_URL=http://assets.local:8095

**Comment by aypdev** [comment]
Yipeeee....It worked. Thanks you so much. 

Now i could see the preflight setup.

By the way...now i am using my original httpd.conf & httpd.vhosts with your suggested APP_URL change.
