### ISSUE TITLE
Export from Snipe v1.2.7-beta-10-g48ccf84 to v3.6.3 build 15 (g1bf34d7)

### ISSUE THREAD

**Issue by MscCroniereNA** [snipe/snipe-it#3449]
Good Morning

I need the necessity of export all data from snipe's version indicated on object.

I'have tried to export/import through phpadmin but with bad results.

Exist another method for do this?

Thanks

GS

**Comment by snipe** [comment]
> I'have tried to export/import through phpadmin but with bad results.

Can you explain what you mean by bad results?

**Comment by MscCroniereNA** [comment]
Could be that the table "asset" in Snipe v1.2.7-beta-10-g48ccf84 have a different name. In fact it is not present.
Have you any idea?

**Comment by snipe** [comment]
There is no table named `asset`, just `assets`.
