### ISSUE TITLE
print labels with more fields to choose from

### ISSUE THREAD

**Issue by 3ter** [snipe/snipe-it#3451]
#### Desired behavior

There are only three possible fields to choose from at the moment.

![image](https://cloud.githubusercontent.com/assets/11499929/24208195/43e5fad4-0f23-11e7-9962-6d3f257c3b3b.png)

Make different fields available. In the best case any field the user chooses.

#### Difficulty

I believe it could be done quite fast, if one knows where to find the relevant code.

#### Related to
#3279 which is the wish for using a logo on a label directly from snipe-it.

**Comment by 3ter** [comment]
@victoriapak Hi Victoria, would you be so kind to label this as a feature request? Thanks 👍

**Comment by snipe** [comment]
Closing as duplicate of #2094, #2466, #2074.
