### ISSUE TITLE
Supplier list problem

### ISSUE THREAD

**Issue by bilgisayarcicocuk** [snipe/snipe-it#3453]
Hello Snipe,

I have a problem with my app. When I created new supplier on new asset page, If the page is not refreshed, new suppliers are not listed. I also experienced this in demo mode. Thanks for your help. 

Cheers,
Erdem

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
(Additionally, any screenshots you can provide would be helpful. We have not seen anyone reporting this issue before, and I am unable to reproduce this on the demo.)

<img width="1299" alt="screen shot 2017-04-06 at 1 57 29 am" src="https://cloud.githubusercontent.com/assets/197404/24746019/88461b38-1a6c-11e7-9c66-d5cceca1d731.png">
<img width="1302" alt="screen shot 2017-04-06 at 1 57 41 am" src="https://cloud.githubusercontent.com/assets/197404/24746020/884b5120-1a6c-11e7-82eb-1bb7723826c2.png">
<img width="1303" alt="screen shot 2017-04-06 at 1 57 53 am" src="https://cloud.githubusercontent.com/assets/197404/24746018/883cbafc-1a6c-11e7-8d67-9a0d03afc0db.png">
