### ISSUE TITLE
Capability to over-license  

### ISSUE THREAD

**Issue by uknzaeinozpas** [snipe/snipe-it#3454]
## Feature request

If you are in [server-url]/admin/licenses view and want to checkout more license-seats than you got, this would not be possible.
It would be nice to track over-licensing in the same license object, something like this:
![software_licenses__snipe-it_asset_management](https://cloud.githubusercontent.com/assets/22473767/24290885/04f3c76a-1087-11e7-9061-bcf888d307de.png)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running | v3.6.4 build 12 (gf7e4fca)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error | /admin/licenses

**Comment by snipe** [comment]
Why wouldn't you just increase the number of licenses? This seems like an anti-pattern that we wouldn't want to encourage.

**Comment by uknzaeinozpas** [comment]
If I would increase the licenses it would be hard to track where I have to buy new ones.
I would be constantly lie to myself as I would just increase the number of seats but do not have the time to buy new licenses.
For example: Some of the licenses I've got can only be adjusted once a year.

A.T.M. I workaround this by adding a second license with the appendix "- overlicensed"

**Comment by uknzaeinozpas** [comment]
Just want to give this a gentle push ;)
