### ISSUE TITLE
URL redirects by repeating itself before adding /setup

### ISSUE THREAD

**Issue by NateV** [snipe/snipe-it#3455]
#### Expected Behavior (or desired behavior if a feature request)

I'm testing Snipe Locally, and I've configured by hosts file at .htaccess so that Snipe is running at snipeit.local.

I expect to go to snipeit.local in my browser and find the preflight and setup for SnipeIT.

-----

#### Actual Behavior

Instead, when I navigate to `snipeit.local`, I am redirected to `snipeit.local/snipeit.local/setup`. 

I also see these two errors:

```
`Warning:  include(../c3.php): failed to open stream: No such file or directory in /Users/[username]/code/php/snipe-it/public/index.php on line 23

Warning:  include(): Failed opening '../c3.php' for inclusion (include_path='.:') in /Users/[username]/code/php/snipe-it/public/index.php on line 23`
```

-----

#### Please confirm you have done the following before posting your bug report:

- [yep ] I have enabled debug mode
- [yep ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running

3.6.4

- What OS and web server you're running Snipe-IT on

Mac OSX 10.12.3

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

Manual installation

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

```
Warning:  include(../c3.php): failed to open stream: No such file or directory in /Users/[username]/code/php/snipe-it/public/index.php on line 23

Warning:  include(): Failed opening '../c3.php' for inclusion (include_path='.:') in /Users/[username]/code/php/snipe-it/public/index.php on line 23

Redirecting to http://snipe.local/snipe.local/setup
```

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

Navigating to the app's base url, `snipeit.local` 

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).

No, since I'm getting this error when trying to install.

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.

I've got a vhost that looks like this:

    <VirtualHost *:80>
        DocumentRoot "/Users/[username]/code/php/snipe-it/public"
        ServerName snipeit.local
        ErrorLog "/private/var/log/apache2/snipeit.local-error_log"
        CustomLog "/private/var/log/apache2/snipeit.local-access_log" common

    <Directory "/Users/[username]/code/php/snipe-it/public">
        AllowOverride All
        Require all granted
        Allow From All
        Options +Indexes
    </Directory>
    </VirtualHost>`

In my `.env` file, I have the line:

`APP_URL=snipeit.local`

- Indicate whether or not you've manually edited any data directly in the database
Nope.

**Thanks for your help!**

**Comment by NateV** [comment]
I'm not sure what I did, but I'm no longer getting this error.

**Comment by arippe93** [comment]
put "http://" or "https://" infront of app URL in the .env file. Apologize for being a few years late but I just want to leave this here in case someone else comes here looking for answers.
You can find the explanation from Snipe on this issue from the below link.

https://github.com/snipe/snipe-it/issues/8559#issuecomment-713814158
