### ISSUE TITLE
Oracle Database

### ISSUE THREAD

**Issue by punny13** [snipe/snipe-it#3459]
I know the documentation says that this requires MySQL or MariaDB database, but is it somehow possible to get Snipe-IT running against an Oracle database?

#### Expected Behavior (or desired behavior if a feature request)
Snipe-IT to work with an Oracle database instead of a MySQL database.
-----

#### Actual Behavior

-----

#### Please confirm you have done the following before posting your bug report:

- [This is not a bug ] I have enabled debug mode
- [YES ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.5.2

- What OS and web server you're running Snipe-IT on
Windows 7, Apache 2.4
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
N/A
- If a stacktrace is provided in the error, include that too.
N/A
- Any errors that appear in your browser's error console.
N/A
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
N/A
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
N/A
- Include what you've done so far in the installation, and if you got any error messages along the way.
N/A
- Indicate whether or not you've manually edited any data directly in the database
N/A

**Comment by snipe** [comment]
In theory it should work because of the ORM, but we don't have the ability right now to test on Oracle, and it's not a priority to do so.
