### ISSUE TITLE
Bulk-Manage Assets from the Asset Model View

### ISSUE THREAD

**Issue by SylentBobNJ** [snipe/snipe-it#3463]
I would like the ability to bulk-manage assets from the Asset Model view.  Currently, the only action available in this view is the Checkin/Checkout. Anything else requires opening each individual asset.
This is particularly problematic during scheduled hardware replacement cycles where all of one model of asset is being replaced (ie. a model of laptop or printer).  It would be much easier to call up the model in the Asset Model view and have the ability to bulk change their status, checkin/checkout delete them right from that view.

![suggestion](https://cloud.githubusercontent.com/assets/17278649/24413715/51860dec-13aa-11e7-8016-14da08cc9635.PNG)

**Comment by lsikora735** [comment]
I second this request! Please and thank you!
