### ISSUE TITLE
Feature Request: Teams and Kits

### ISSUE THREAD

**Issue by SylentBobNJ** [snipe/snipe-it#3464]
Just throwing this one out there:

Could we create 'Teams' from our 'People' in order to assign assets? Could we also create 'kits' out of groups of objects to easily check in or out a bunch of assets, accessories and licenses at once?

Use cases:

Teams: We have Field Kits comprised of printers, routers, scanners, etc. that are grouped together in bags and assigned to teams.  Right now, we are creating a user for the team and assigning the individual assets to it, but it would be great to have the team members associated with the assets they have checked out in their kit.

Kits: Besides the field kits, it would be great to bundle several assets/licenses together in order to make it easier to assign them to a user or team.   For example, by role:  If we could create an "Associate" kit, it would include a laptop (provide a list of 'Ready to Deploy' laptops to choose from, for example), keyboard/mouse accessories, Office license, Acrobat license, docking station, phone, and monitor.

Thank you for your consideration!

**Comment by snipe** [comment]
Is this not already covered in #563?

**Comment by SylentBobNJ** [comment]
Doh, it sure is. Not sure why that didn't come up in my searches.  Thanks!

**Comment by snipe** [comment]
No problem :)
