### ISSUE TITLE
Error Decrypting: The payload is invalid.

### ISSUE THREAD

**Issue by ricnic89** [snipe/snipe-it#3465]
#### Expected Behavior (or desired behavior if a feature request)

I created an custom field and activated the encrypt option. When I add this field to an asset and input some data I cannot decrypt it.
With an admin account it should be possible to see encrypted custom fields in plain text.

-----

#### Actual Behavior

I see only an error message: Error Decrypting: The payload is invalid.
(same on the demo page https://demo.snipeitapp.com)

-----

#### Please confirm you have done the following before posting your bug report:

- [+] I have enabled debug mode
- [+] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: Version 3.6.3
- What OS and web server you're running Snipe-IT on: Ubuntu 16.04.1 Apache 2.4 PHP 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: no
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: asset view
- If a stacktrace is provided in the error, include that too.:
- Any errors that appear in your browser's error console. :
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).: yes
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.: no errors during the installation
- Indicate whether or not you've manually edited any data directly in the database: no

**Comment by snipe** [comment]
Can you point me to where in the demo you're seeing this?

**Comment by ricnic89** [comment]
Hi snipe,
I created an example in the demo. Asset tag "Testasset01". In the custom field "test encrypt" the entered data cannot decrypted. "Error Decrypting: The payload is invalid."

**Comment by dakolta** [comment]
I to have come across this issue.

Version of Snipe-IT you're running: v3.6.4 build 12 (gf7e4fca)
What OS and web server you're running Snipe-IT on: Ubuntu 16.04.2 LTS Apache 2.4 PHP 7
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual install.sh
WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: no
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: asset view
If a stacktrace is provided in the error, include that too.:
Any errors that appear in your browser's error console. :
Confirm whether the error is reproduceable on the demo.: yes
Include any additional information you can find in app/storage/logs and your webserver's logs.
Include what you've done so far in the installation, and if you got any error messages along the way.: no errors during the installation
Indicate whether or not you've manually edited any data directly in the database: no

There are no errors in any log file or in the console.
I was able to reproduce on the demo page, I am attaching a screen shot of the demo page and my asset page.
![screenshot 2017-07-09 12 11 22](https://user-images.githubusercontent.com/18648939/27996833-cb7d7dc4-649f-11e7-8151-028cba387e79.png)
![screenshot 2017-07-09 11 55 08](https://user-images.githubusercontent.com/18648939/27996834-cb9e64da-649f-11e7-87a7-633f76bd1e0b.png)

**Comment by ernestasen** [comment]
Why this was closed? I can't see any solution.. I am having the same issue. Out of the blue, some fields doesn't show me encrypted values but just the message: Error Decrypting: The payload is invalid.

**Comment by snipe** [comment]
@ernestasen because version v3.6.4 is very old, and the only reason why you'd see a payload error is if your app key has changed.
