### ISSUE TITLE
i want to bulk delete how i do this if i deleted user the item assign also be deleted ?

### ISSUE THREAD

**Issue by umerafridi** [snipe/snipe-it#3467]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
 3.6.0
- What OS and web server you're running Snipe-IT on
Centos apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  manual istallation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Bulk delete what? Assets? Users?

**Comment by umerafridi** [comment]
Assets .actually we clear our database there is some entry with fake serial number i want to delete these items .

**Comment by umerafridi** [comment]
when i  click on list all the enter in search for desktop it show me almost 1239 figure most of them are not correct with serial number i want to delete almost 800 desktop how i do this which not affected the rest of items and users

**Comment by snipe** [comment]
If you use the bulk asset delete tool, it will not affect users in the system.

![Uploading Screen Shot 2017-03-29 at 10.38.37 PM.png…]()

**Comment by umerafridi** [comment]
Ok Thanks for support .one thing more if i assign assets to staff  email alert goes to the staff and he can verify through email or some digital sing there

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/requiring-acceptance

**Comment by umerafridi** [comment]
Hi Sorry for  disturbing again and again my forgot password is not working when i enter email for forgot password it redirect to this URL HTTP://192.x.x.x/password/email with browser message 

Whoops, looks like something went wrong.

**Comment by umerafridi** [comment]
After enabling debug mode
Swift_TransportException in AbstractSmtpTransport.php line 162:
Cannot send message without a sender address

**Comment by umerafridi** [comment]
i already have set my mail account details in .env and mail.php both.

**Comment by umerafridi** [comment]
Please update me
