### ISSUE TITLE
LDAP Large directory support

### ISSUE THREAD

**Issue by ANewFlame** [snipe/snipe-it#3474]
#### Expected Behavior 

LDAP queries should return the full result set, not just the first 1000 records.

-----

#### Actual Behavior

Only the first 1000 records for a given LDAP query are returned, resulting in missing users during synchronisation.

-----

#### Notes

Hi there,

We have a large directory (more than 1000 users). 

Active Directory limits LDAP queries to 1000 results (without an unsafe `MaxPageSize` hack) so attempting to perform synchronisation via LDAP results in missing users.

To resolve this it's necessary to use the pagination function of LDAP to query the full result set.

I've made the necessary changes in-house for our use-case, and wanted to share them with you: 
```diff
-        // Perform the search
-        $search_results = @ldap_search($ldapconn, $base_dn, '('.$filter.')');
-        if (!$search_results) {
-            return Redirect::route('users')->with('error', Lang::get('admin/users/message.error.ldap_could_not_search').ldap_error($ldapconn));
-        }
-
-        // Get results
-        $results = @ldap_get_entries($ldapconn, $search_results);
-        if (!$results) {
-            return Redirect::route('users')->with('error', Lang::get('admin/users/message.error.ldap_could_not_get_entries').ldap_error($ldapconn));
-        }
+        // AD limits records to 1000 per query.  Perform the search and get the results but using LDAP pagination to break the queries into sets of 1000
+        $pagingCookie = "";
+        ldap_set_option($ldapconn, LDAP_OPT_SIZELIMIT, 1000);
+        $results = array();
+        do {
+            ldap_control_paged_result($ldapconn, 1000, true, $pagingCookie);
+            $ldap_result = @ldap_search($ldapconn, $base_dn, '('.$filter.')');
+            $ldap_entries = ldap_get_entries($ldapconn, $ldap_result);
+            ldap_control_paged_result_response($ldapconn, $ldap_result, $pagingCookie);
+            $results = array_merge($results, $ldap_entries);
+        } while ( $pagingCookie !== null & $pagingCookie != "");
```

Further it seems when iterating the results that the `count` value from the server response is being used instead of the actual size of the array (note, this is unsafe).  This means the pagination approach above won't work because the `count` attribute will be set at the number of records for the last page of the query, not the total.  

Easily fixed with:

```diff
-        for ($i = 0; $i < $results["count"]; $i++) {
+        /** Use the real size of the array!! **/
+        for ($i = 0; $i < count($results)-1; $i++) {
```

Hope this helps in some way and thanks for your work on the product.

:)

**Comment by snipe** [comment]
I believe we had to limit this to 1000 for AD users (and also users with very large data sets, where the browser would time out because retrieving the data took too long.) We instead recommend using the upcoming Location-specific OUs to return smaller data sets.

**Comment by snipe** [comment]
(But if you'd like to put this into a pull request I can try to run some tests on my end. I'm almost certain we had to do it the way we did for compatibility among multiple directory servers tho.)
