### ISSUE TITLE
not able to open on the browser the snipe it page pre-flight 

### ISSUE THREAD

**Issue by thekingofboys** [snipe/snipe-it#3475]
this is the snipeit folders
![image](https://cloud.githubusercontent.com/assets/19243313/24613557/ed041650-1888-11e7-841e-6c7dc69b15aa.png)

![image](https://cloud.githubusercontent.com/assets/19243313/24613572/f8176862-1888-11e7-9c86-f594a0ec8564.png)

but when i go to browser and try to access it doesnt work
i use this link to make the easy installation. https://community.spiceworks.com/how_to/132545-install-snipe-it-asset-management-on-ubuntu-14-04v
can someone tells me where did i go wrong 

#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by kenfrancisadams** [comment]
Can you post a screenshot of the browser when you try and load Snipe-IT?

**Comment by thekingofboys** [comment]
when i put the apache default path to here its give me the error that is perfect fine
![image](https://cloud.githubusercontent.com/assets/19243313/24644423/cab5ca0e-1913-11e7-8672-9bd948b23def.png)
in browser
![image](https://cloud.githubusercontent.com/assets/19243313/24644430/dad51b74-1913-11e7-982a-9389b59b409d.png)

but when i change to the public folder
![image](https://cloud.githubusercontent.com/assets/19243313/24644445/ec901968-1913-11e7-8390-4e117e6f8a99.png)

i have the nothing 
![image](https://cloud.githubusercontent.com/assets/19243313/24644476/0a04b8f0-1914-11e7-9e87-ce84e946ca5d.png)

**Comment by kenfrancisadams** [comment]
This is what my /etc/apache2/sites-available/000-default.conf looks like:

`<VirtualHost *:80>
ServerAdmin webmaster@localhost
<Directory /var/www/snipeit/public>
Require all granted
AllowOverride All
</Directory>
DocumentRoot /var/www/snipeit/public
ServerName mydomain.com
ErrorLog /var/log/apache2/snipeIT.error.log
CustomLog /var/log/apache2/access.log combined
</VirtualHost>`

Obviously change mydomain.com to whatever you're using

**Comment by snipe** [comment]
That's an apache level 500 error, which means a misconfiguration in your httpd conf. Can you show us the contents of the Apache``error.log`?

**Comment by kojaq** [comment]
I'm having an exactly same issue. Regardless of the configuration changes in apache and file locations, I'm getting either an error that the DocumentRoot is set incorrectly, or the HTTP 500 error. 

Using default installed apache2 from ubuntu server 17.04

SnipeIT located in /var/www/html/snipeit/
The Directory and DocumentRoot path in snipeit.conf: /var/www/html/snipeit/public
The Directory and DocumentRoot path in 000-default.conf: /var/www/html/snipeit/public

Getting error 500 whenever I try to open SnipeIT by typing in either just the IP of the VM holding SnipeIT. Same for trying to open http://<VM_IP>/index.php 

Any ideas what might be done better? 
Thanks.

**Comment by kojaq** [comment]
I've been trying to get this working for a good while with a few setups but
eventually agreed that I must be delayed and went with a different
solution.
Pity, as its decent software.

**Comment by Metal-Frog** [comment]
Has anyone an idea what I can do to narrow the problem (URL is redirected to /setup but pre-flight dos not show up, server error 500)?
The laraval.log is empty.

**Comment by snipe** [comment]
@Metal-Frog A 500 error could be caused by nearly endless things. 

- What kind of 500 is it? 
- Do you get a "Whoops" page or a default internal service error page? 
- What's in your server logs when you try to access the /setup page? 

Also, what web server are you using? (Next time you should probably create a new issue, since this one is closed. Can be helpful so that we can get all of the info we ask for in the ticket template.)
