### ISSUE TITLE
Feature Request - Default Group

### ISSUE THREAD

**Issue by simsjdf** [snipe/snipe-it#3476]
#### Expected Behavior (or desired behavior if a feature request)

When a new user is created or imported from LDAP the new user is assigned to a default group.

-----

#### Actual Behavior

New users do not get assigned to any group(s) at present.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v3.6.2 build 10 (g927a12f)
- What OS and web server you're running Snipe-IT on - Ubuntu 14.04.4 / Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - NA
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - NA
- If a stacktrace is provided in the error, include that too. - NA
- Any errors that appear in your browser's error console. - NA
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). - NA
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. - NA
- Include what you've done so far in the installation, and if you got any error messages along the way. - NA
- Indicate whether or not you've manually edited any data directly in the database - NA

**Comment by louisdj** [comment]
Would be nice if in case of Active-Directory the OU of AD could be used as group.

**Comment by wvolz** [comment]
👍
