### ISSUE TITLE
Text Wrapping

### ISSUE THREAD

**Issue by therealjoshuad** [snipe/snipe-it#3482]
#### Expected Behavior (or desired behavior if a feature request)

All rows would be the same height

-----

#### Actual Behavior

When some data in a field is too long, the field gets wrapped and the row height changes. Is that just a product of the responsive design? Is there anything that would be written in to help with columns that don't fit in the window's size?

![image](https://cloud.githubusercontent.com/assets/3893036/24720230/f2ac2906-1a01-11e7-8ea5-a7cc44f2f982.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
The only real solution is to hide a few other columns to give the rest of the text space (allow the columns to be wider, for example). We can't really predict how long a field is going to be, and in general, the wrapping isn't a behavior that is unexpected in a really wide table. We could enclose text in a CSS no-wrap, but if someone has an entry that's genuinely really long, that would result in undesirable displays for them, so I'm not sure there's much we can do here.

**Comment by therealjoshuad** [comment]
I knew it wasn't unexpected. just wanted to put it out there and see if there were any solutions that I wasn't aware of. Is there any way to change the default columns, and if not, would that be something every considered to add?
