### ISSUE TITLE
Feature request: sync assets to customers installation of snipeit

### ISSUE THREAD

**Issue by it-world** [snipe/snipe-it#3484]
I would like to sync assets to my customers snipeit installation.

For example:
Lets say one customer have 10 companies.
So he hosts an installation of snipeit in his it environment to keep on track.

The customers installation is read only.
Customer gets a sync key / user / password for his snipeit installation.
He adds his key/user/password his snipeit admin interface including the upstreams FQN or ip.

On my side i choose which companies belong to this combination of sync key/user/password and one time a day the customers snipeit installation sync its assets from my installation.

I hope this will this make sense for others too (a friend asked me for this feature, and now a customer would like to have this too).

**Comment by snipe** [comment]
The upcoming API addresses this issue, so that you can build your own syncing scripts to pass data back and forth.
