### ISSUE TITLE
Feature Request: User Items Report 

### ISSUE THREAD

**Issue by dwestonjr** [snipe/snipe-it#3487]
#### Expected Behavior (or desired behavior if a feature request)
Request
Looking to get a Report based of User for all Items, not just assets, attached to a User
--------------------------------------------------------------
User:
Assets:
Licenses:
Accessories:
Consumables:
Components:
Requestables: (If applicable)

-----

#### Actual Behavior

None Exist

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:
System Information
Snipe-IT version v3.6.4 build 12 (gf7e4fca)
PHP Version 5.6.28
Laravel Version 5.2.45
Windows Server 2012R2
XAMPP Apache Web Server with MYSQL.

**Comment by snipe** [comment]
How is that different than what's on the detail view of the user's page?

**Comment by dwestonjr** [comment]
I guess it is not too different if you select People, highlight a user, then go to their History.  I guess I was looking for a printable/Exportable report that would list all users that have items and what they actually have.  I could probably write a module to add in.

**Comment by snipe** [comment]
(This feature was added in a recent release)
