### ISSUE TITLE
Feature Request: License Models

### ISSUE THREAD

**Issue by ryanesizemore** [snipe/snipe-it#3488]
Currently the Licenses have to be entered manually for each new license, including the license software name, developer, etc. This creates the possibility for errors when different admins use different naming conventions and it also clutters the license page.

I suggest have a common Software title and description in which one can assign licenses to the software suite and assign under the license key, either to an individual users or to multiple users with license seats like what is done now. This way under licenses, a company can have only one entry for say Microsoft Office 2012 with all the license keys under it instead of a new instance for each key.

**Comment by NickTaylorAS** [comment]
I'd love to see something like this. Having to create a unique license for each key instead of being able to assign keys to seats is quite messy.

**Comment by cipnt** [comment]
Indeed, the current option is not ideal.
I ended up creating one license with multiple seats and added multiple license keys to the product key field

**Comment by afield1235** [comment]
This functionality would be ideal, I used to have it in another software I used and it adds a huge advantage for organization. Right now, most of my licenses are volume so I only need to create one license with multiple seats. Other software though does not offer volume so I have about 30+ entries of the same software but each one has a different key and owner.

**Comment by grantemsley** [comment]
I would love to see this too.

Having each license being a container for multiple individual licenses (with different product keys, number of seats, purchase and expiration dates, etc.), but still assign them from the container would be great.

**Comment by thwr** [comment]
Same here. Would be way easier to see the amount of licenses left.
