### ISSUE TITLE
HTTPS security is compromised by use of logo

### ISSUE THREAD

**Issue by nashbrydges** [snipe/snipe-it#3489]
#### Expected Behavior (or desired behavior if a feature request)
When changing settings to use logo or logo + text for branding should not affect HTTPS.
(what you expect to happen goes here)

-----

#### Actual Behavior
Browser console shows error that reads "SEC7111: HTTPS security is compromised by http://domain.com/uploads/logo.png" and disables HTTPS
(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode YES
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) YES

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 
v3.6.4 build 12 
- What OS and web server you're running Snipe-IT on 
Ubuntu 16.04.2 Apache2 (all updated)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) 
Manual installation because automated script would hang every time.
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
This browser error appears whether debug is turned on or not...
SEC7111: HTTPS security is compromised by http://domain.com/uploads/logo.png
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
All pages
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
SEC7111: HTTPS security is compromised by http://domain.com/uploads/logo.png
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
No it's not...cannot upload logo to demo
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
Nothing more than the mixed content HTTPS error
- Include what you've done so far in the installation, and if you got any error messages along the way.
This error appeared as soon as I uploaded and enabled use of a logo.
- Indicate whether or not you've manually edited any data directly in the database
No db edits
![logo_branding](https://cloud.githubusercontent.com/assets/25962967/24833145/4618d510-1c8e-11e7-8849-70561ab8f56f.png)
![text_only_branding](https://cloud.githubusercontent.com/assets/25962967/24833144/461886f0-1c8e-11e7-9b13-7b7cda262b6d.png)

**Comment by nashbrydges** [comment]
UPDATE: It appears that anytime I am on a page with an image, I get a mixed content warning and HTTPS is broken. For example, I uploaded a photo to attach to an asset, when I view the page for the asset with the photo, HTTPS is broken. However if I view a different asset with no photo, HTTPS is good.

**Comment by BrettFagerlund** [comment]
Check on your app_url in env file, make sure it's set with https:// not http://

**Comment by snipe** [comment]
Thanks, @BrettFagerlund - came here to say exactly that :)
