### ISSUE TITLE
WEB ui isn't working when internet is off

### ISSUE THREAD

**Issue by muteb** [snipe/snipe-it#3490]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

I want to use snipeit inside an isolated network that has no internet connection whatsoever and when I deploy it inside that network, the whole design of Snipe-IT goes without bootstrap affects as well as the css&js.

Is there anyway we can solve this issue?
![issue](https://cloud.githubusercontent.com/assets/5000589/24892759/9eed338e-1e87-11e7-9555-425df6469bbf.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [* ] I have enabled debug mode
- [ *] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running  v3.6.4
- What OS and web server you're running Snipe-IT on apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: nothing
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error : Main page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Thanks

**Comment by muteb** [comment]
![issue](https://cloud.githubusercontent.com/assets/5000589/24892746/8804446e-1e87-11e7-9e6d-861f2a9ed512.png)

**Comment by snipe** [comment]
Did you uncheck the "This Snipe-IT install can load scripts from the outside world."  checkbox in the settings?
