### ISSUE TITLE
[Feature Request] Supplier Field in Asset List

### ISSUE THREAD

**Issue by delinski111** [snipe/snipe-it#3491]
In All assets list

![image](https://cloud.githubusercontent.com/assets/22087997/24871910/51af29a4-1de9-11e7-91f1-b01908cfbabe.png)

Supplier is not a display field.

Snipe-IT version	v3.6.1 build 5 (g6f9a82f)
PHP Version	5.5.9-1ubuntu4.20
Laravel Version	5.2.45

**Comment by snipe** [comment]
This will be in the 4.0 release
