### ISSUE TITLE
Second site possible on same server where snipe it is installed?

### ISSUE THREAD

**Issue by RG-035** [snipe/snipe-it#3496]
After many (MANY!) trials and errors i finally installed Snipe IT onto a Ubuntu server. I tried installing it on a ubuntu 16.04 server with the latest stable versions of mysql, php and apache. I tried installing it with the install script but it wouldn't work in any way. It hangs at setting up LAMP in the background, log shows it fails on root user. Root was setup right and with a working password. Finally i gave up and installed it with 14.04, first try and everything works great. 

The above doesn't contribute to my question but i wanted to let you know. Maybe it's my fault maybe it isn't. Great piece of software by the way.. 

Now back to my question: Is it possible to install a second website onto the same ubuntu server? I can't find any information regarding this. The only info i found is that snipe-it kills any other running site on the same server when installing it fresh. I'm pretty new to ubuntu (only pro to installing it over and over again is getting familiar with ubuntu) so i hope it's not a weird question. I created a second website, with a new database, and placed it in the html folder. When i enter the url http://0.0.0.0/newwebsite it gives me a sad panda :( I also checked in /apache2/sites-available at the DocumentRoot which still is set to /var/www/html

What am i missing here? Or is it just not possible.

Thanks!

**Comment by snipe** [comment]
It's definitely possible, you just need to configure the server for additional virtual hosts. That has nothing to do with Snipe-IT, and is just sorta how web servers work. 

https://www.digitalocean.com/community/tutorials/how-to-set-up-apache-virtual-hosts-on-ubuntu-12-04-lts (start at Step One - Create Directory, since you already have PHP, MySql, etc set up)

**Comment by RG-035** [comment]
Like i said, new to ubuntu. Thanks for posting the link!
