### ISSUE TITLE
Unable to get to Pre-Flight

### ISSUE THREAD

**Issue by PCSM78** [snipe/snipe-it#3497]
#### Expected Behavior (or desired behavior if a feature request)

I expect the Pre-Flight Page to be shown
-----

#### Actual Behavior

What I'm actually seeing is the following:
![image](https://cloud.githubusercontent.com/assets/27426368/25006223/5cdce4fe-205c-11e7-8dc9-fe9ff1c7ea8d.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
=>> 3.6.4
- What OS and web server you're running Snipe-IT on
=>> Ubuntu 16.04 LTS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
=>> Manual as I recall...
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
=>> No Error shown...
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
=>> None...
- If a stacktrace is provided in the error, include that too.
=>> None...
- Any errors that appear in your browser's error console.
=>> None as I can see, but maybe I'm wrong here:
![image](https://cloud.githubusercontent.com/assets/27426368/25006424/1c3ff5fc-205d-11e7-8d68-a2fbe55400b9.png)

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
=>> Nope for obvious reasons^^
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
==> .../snipe-it/storage/logs:
![image](https://cloud.githubusercontent.com/assets/27426368/25006535/9248b932-205d-11e7-982a-79d28c9e680b.png)

=>> /var/log/apache2
![image](https://cloud.githubusercontent.com/assets/27426368/25006873/e024bc04-205e-11e7-8224-965a372a151d.png)

![image](https://cloud.githubusercontent.com/assets/27426368/25006910/f77e26ce-205e-11e7-91ec-eabdc4d7bccf.png)

- Include what you've done so far in the installation, and if you got any error messages along the way.
=>> Well I went through all steps in here:
https://snipe-it.readme.io/docs/installation
Had no real problems I can 'brag' about.
But as this is my first Ubuntu and first Linux Installation, I had to struggle a bit with some steps.
Although nothing to mention here so far I think...

- Indicate whether or not you've manually edited any data directly in the database
=>> In the database I didn't

**PS: I'm out till Tuesday so be patiant with me.**
**And of course many many thanks in advance :)**

**PSS: If you think the .env or the 000-default could be helpful,**
**I can upload them after the Weekend as well**

**Comment by snipe** [comment]
Server not found indicates a network issue. Does `www.snipe.local` have a DNS entry anywhere in your network?

**Comment by PCSM78** [comment]
Do I really need to set a DNS Entry when I'm opening the site via the server it is installed and hopefully running on?

**Comment by PCSM78** [comment]
As promised, here are the two files: /etc/apache2/sites-enabled/000-default.conf
[000-default.conf.zip](https://github.com/snipe/snipe-it/files/933614/000-default.conf.zip)

And: /var/www/html/snipe-it/.env
[env (copy).zip](https://github.com/snipe/snipe-it/files/933487/env.copy.zip)

Maybe theres something wrong as well...

**Comment by PCSM78** [comment]
**Alright after some modifications and shooting myself several times**
**in the knee I now get this screen, when opening http://snipe.local**

**Can you tell what is left to do from here on?**
**Btw. I didn't modify the DNS, but the /etc/hosts File**

![image](https://cloud.githubusercontent.com/assets/27426368/25189385/47d6c8aa-2529-11e7-917a-7e75cb761141.png)

**Comment by robblehead** [comment]
I do know DNS entry is a must from experience but it looks like it is trying to get there.
For some reason it's loading the index file located in the public folder instead of the site
Have you tried going to snipe.local/setup by chance?

**Comment by snipe** [comment]
> For some reason it's loading the index file located in the public folder instead of the site

That is the correct file to load, but if PHP code is being displayed in the browser, it looks like PHP isn't installed. You should never see PHP  in the browser.

**Comment by PCSM78** [comment]
Well I now reinstalled everything and got it going!
Yeah! 👍 

But I now have another question.
When accessing snipe from another LAN PC I get the message:
> Whoops, looks like something went wrong.

What could possibly go wrong here?

**Comment by PCSM78** [comment]
Good Morning everybody!

Found out MariaDB wasn't starting somehow.
After cheking some files without any result reinstalled MariaDB and somehow got it running.

**So Snipe-IT is now running, I'm happy and just want to thank you for your time
Great piece of art you got there! ;)**

**Comment by suyal** [comment]
Hello snipe,
Thanks for your help and support every from last 2 years i am using snipe-it and its .
recently i install snipe-it in ubuntu 14.0 and its installed successfully after that i install ppmyadmin and snipeit page is not opening its error 500 but phpmyadmin is working fine could you please help me to resolve this issue i search a lot in google but i am not able to find any slution

**Comment by suyal** [comment]
![screenshot from 2018-02-25 13 13 31](https://user-images.githubusercontent.com/36809971/36639214-c84b8904-1a2d-11e8-8eb8-4a1b0d18e4b0.png)

**Comment by suyal** [comment]
![screenshot from 2018-02-25 13 13 52](https://user-images.githubusercontent.com/36809971/36639216-d2397f84-1a2d-11e8-8901-a4710ec8ddc1.png)
