### ISSUE TITLE
Suggestion：make snipe-it support dynamic custom field

### ISSUE THREAD

**Issue by linglongtong** [snipe/snipe-it#3499]
Snipe-IT version:  3.6.3

Now one model can only support one custom field, it is not convenient if I need more.
For example, our servers have many attributes, I need to add about 30 custom field.
Is it possible to make the number of custom field dynamic?  Users can add or reduce the number of custom field of one model as needed.

**Comment by rbxue** [comment]
Maybe fieldset? @linglongtong

**Comment by snipe** [comment]
> Now one model can only support one custom field, it is not convenient if I need more.

That is not correct. Models support one *fieldset*, which is a collection of whatever custom fields you group together. 

https://snipe-it.readme.io/docs/custom-fields
