### ISSUE TITLE
Review of all available (unassigned) assets on a single screen

### ISSUE THREAD

**Issue by itims** [snipe/snipe-it#3500]
Is there any option for the review of all available(unassigned) assets(Assets, Accessories, Consumables and Components) on a single screen?

#### Please provide answers to these questions before posting your bug report:

- Version of Snipe- **3.6.3**
- What OS and web server you're running Snipe-IT on **Ubuntu Server 14**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)  **install.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
That view does not currently exist in Snipe-IT.
