### ISSUE TITLE
Sorting asset tag by decending does not return true asset tag maximum.

### ISSUE THREAD

**Issue by snug** [snipe/snipe-it#3502]
#### Expected Behavior (or desired behavior if a feature request)

When sorting the assets via asset tag, if sorted by descending the largest asset number should come first. The opposite should be true when reversed.

After looking at the example in the actual behavior section, I believe it should look like this when sorting descending.

2312
2311
...
(Asset numbers from 2310 - 1009)
...
1008
1007
...
(Asset numbers from 955 - 0)
-----

#### Actual Behavior

When sorting the asset tag as descending, numbers are sorted like so:
1007
1008
...
(Asset numbers climbing from 1009 to 2310)
...
2311
**2312**
**516**
517
(Assets from 518 - 995 range.)

![chrome_2017-04-19_12-20-08](https://cloud.githubusercontent.com/assets/27174028/25163402/adbe5016-24fc-11e7-85ae-07279fcb1d54.png)

Please note, the smallest asset number in our database is 516, and the largest is 2312. There is a dropoff between 2312 and 516.
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.6.4 build 12 (gf7e4fca)

- What OS and web server you're running Snipe-IT on
XAMMP on Windows 10

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh (I think?)

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
/hardware

- If a stacktrace is provided in the error, include that too.
N/A

- Any errors that appear in your browser's error console.
N/A

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
Reproducible. (I deleted all of the assets currently in there as well...)

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
Folder doesn't seem to exist

- Include what you've done so far in the installation, and if you got any error messages along the way.
Full installation, I've imported assets using CSV import.

- Indicate whether or not you've manually edited any data directly in the database
I haven't manually edited the database, unless CSV import counts somehow.

Not really relevant to the issue, but I'd just like to thank you for creating this. I'm migrating from an awful Access database that was built completely by forms and really weird things by the previous admin.

**Comment by snug** [comment]
Thinking about it now after having lunch, it seems that the datatype must be a string or something and is sorting it alphabetically. How can I change it to a number / integer? All of our assets (apart from two for some reason, but these can be easily changed) are numbers.

**Comment by broman42** [comment]
I too would like the ability to sort assets numerically. Our asset tags are only numbers. 1-5000 (roughly).
