### ISSUE TITLE
SQLSTATE[HY000] [1044] Access denied for user 'snipe_user'@'localhost' to database 'snipeit'

### ISSUE THREAD

**Issue by cyberjack007** [snipe/snipe-it#3503]
#### Expected Behavior (or desired behavior if a feature request)

Would like to be able to access the Pre-Flight and set up.  I have made it through a lot of the issues and downloaded all the dependencies.  I set all the folder permissions so the IUSR, IIS_USR, and Everyone has Full Control.  I have attached the php, env, and htaccess files if those help.

-----

#### Actual Behavior

in Connector.php line 55
2.at PDO->__construct('mysql:host=localhost;dbname=snipeit', 'snipe_user', 'Bubba1040', array('0', '2', '0', false, false)) in Connector.php line 55
3.at Connector->createConnection('mysql:host=localhost;dbname=snipeit', array('driver' => 'mysql', 'host' => 'localhost', 'database' => 'snipeit', 'username' => 'snipe_user', 'password' => 'Bubba1040', 'charset' => 'utf8', 'collation' => 'utf8_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => ''C:\Program Files\MariaDB 10.1\bin'', 'dump_command_timeout' => '300', 'dump_using_single_transaction' => true, 'options' => array(), 'name' => 'mysql'), array('0', '2', '0', false, false)) in MySqlConnector.php line 24
4.at MySqlConnector->connect(array('driver' => 'mysql', 'host' => 'localhost', 'database' => 'snipeit', 'username' => 'snipe_user', 'password' => 'Bubba1040', 'charset' => 'utf8', 'collation' => 'utf8_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => ''C:\Program Files\MariaDB 10.1\bin'', 'dump_command_timeout' => '300', 'dump_using_single_transaction' => true, 'options' => array(), 'name' => 'mysql')) in ConnectionFactory.php line 61
5.at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
6.at call_user_func(object(Closure)) in Connection.php line 924
7.at Connection->getPdo() in Connection.php line 792
8.at Connection->reconnectIfMissingConnection() in Connection.php line 677
9.at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure)) in Connection.php line 349
10.at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users')) in MySqlBuilder.php line 21
11.at MySqlBuilder->hasTable('users') in Facade.php line 217
12.at Facade::__callStatic('hasTable', array('users')) in Setting.php line 65
13.at Setting::setupCompleted() in CheckForSetup.php line 22
14.at CheckForSetup->handle(object(Request), object(Closure))
15.at call_user_func_array(array(object(CheckForSetup), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
16.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
17.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
18.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in NosniffGuard.php line 17
19.at NosniffGuard->handle(object(Request), object(Closure))
20.at call_user_func_array(array(object(NosniffGuard), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
21.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
22.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
23.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in XssProtectHeader.php line 17
24.at XssProtectHeader->handle(object(Request), object(Closure))
25.at call_user_func_array(array(object(XssProtectHeader), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
26.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
27.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
28.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in FrameGuard.php line 17
29.at FrameGuard->handle(object(Request), object(Closure))
30.at call_user_func_array(array(object(FrameGuard), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
31.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
32.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
33.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
34.at ShareErrorsFromSession->handle(object(Request), object(Closure))
35.at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
36.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
37.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
38.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in StartSession.php line 64
39.at StartSession->handle(object(Request), object(Closure))
40.at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
41.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
42.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
43.at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 145
44.at CheckForMaintenanceMode->handle(object(Request), object(Closure))
45.at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 136
46.at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
47.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
48.at Pipeline->Illuminate\Routing\{closure}(object(Request))
49.at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
50.at Pipeline->then(object(Closure)) in Kernel.php line 132
51.at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 99
52.at Kernel->handle(object(Request)) in index.php line 59

-----

#### Please confirm you have done the following before posting your bug report:

- [Y ] I have enabled debug mode
- [Y ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - 
- What OS and web server you're running Snipe-IT on v3.6.4 on IIS 6.2/ WIN SVR 2012 R2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - All of the above
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error 
SQLSTATE[HY000] [1044] Access denied for user 'snipe_user'@'localhost' to database 'snipeit'

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.  There were many errors, I was able to resolve most of them.  

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

- Include what you've done so far in the installation, and if you got any error messages along the way.  _Everything up to Pre-Flight.  I was able to generate the key successfully and it did transfer into the .env file._  
[env.txt](https://github.com/snipe/snipe-it/files/935677/env.txt)

[htacess.txt](https://github.com/snipe/snipe-it/files/935678/htacess.txt)

[u_ex170419.txt](https://github.com/snipe/snipe-it/files/935679/u_ex170419.txt)

[php.txt](https://github.com/snipe/snipe-it/files/935707/php.txt)

Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 7
Server version: 10.1.22-MariaDB mariadb.org binary distribution

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> create database snipeit;
Query OK, 1 row affected (0.03 sec)

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| snipeit            |
| test               |
+--------------------+
5 rows in set (0.05 sec)

MariaDB [(none)]> create user snipe_user;
Query OK, 0 rows affected (0.02 sec)

MariaDB [(none)]> grant all on db_name.* to 'snipe_user'@'localhost' identified
by 'Bubba1040';
Query OK, 0 rows affected (0.03 sec)

MariaDB [(none)]> grant all on db_name.* to 'Administrator'@'localhost' identifi
ed by 'Bubba1040';
Query OK, 0 rows affected (0.00 sec)

MariaDB [(none)]>

- Indicate whether or not you've manually edited any data directly in the database.  I have not manually entered any data into the database.

**Comment by cyberjack007** [comment]
Solved!

**Comment by thuekx** [comment]
How do you solved this?

**Comment by snipe** [comment]
@thuekx Use a working username and password combination in your .env

**Comment by thuekx** [comment]
hi @snipe i dont know what happen, but i already make sure twice the username and password also grant all priviledges and it still happen, today i will try to install it again from scratch

**Comment by thuekx** [comment]
Hi, 
Just for info, check selinux if this happen to you, i already success after set selinux for sql port and set permissive

**Comment by shakkeert** [comment]
How do you guys solved this?

**Comment by thuekx** [comment]
hi if yo're using a centos 7 maybe you can try to disable selinux or you can setup selinux for sql port and set permissive

**Comment by vishalunjha** [comment]
STEP 9: Migrating database:
--------------------------------------------------------


   Illuminate\Database\QueryException

  SQLSTATE[HY000] [1045] Access denied for user 'root'@'10.18.1.66' (using password: YES) (SQL: select * from information_schema.tables where table_schema = snipeit and table_name = migrations and table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:712
    708▕         // If an exception occurs when attempting to run a query, we'll format the error
    709▕         // message to include the bindings with SQL, which will make this exception a
    710▕         // lot more helpful to the developer instead of just the database's errors.
    711▕         catch (Exception $e) {
  ➜ 712▕             throw new QueryException(
    713▕                 $query, $this->prepareBindings($bindings), $e
    714▕             );
    715▕         }
    716▕     }

      +33 vendor frames
  34  artisan:35
      Illuminate\Foundation\Console\Kernel::handle()
