### ISSUE TITLE
Cant backup on ver v2.0.5-pre-191-g948be5c

### ISSUE THREAD

**Issue by brandonsnipe** [snipe/snipe-it#3505]
Anybody have issue with this? I would like to export the data then import it to the new version 3.
After i click into Admin option and click backups, this happen.

#### Actual Behavior

**Oh no!

Server Error: 500 (Internal Server Error)

What does this mean?

Something went wrong on our servers while we were processing your request. We're really sorry about this, and will work hard to get this resolved as soon as possible.

Perhaps you would like to go to our home page?**
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running v2.0.5-pre-191-g948be5c
- What OS and web server you're running Snipe-IT on Windows Vista & Wamp Server

**Comment by brandonsnipe** [comment]
![capture](https://cloud.githubusercontent.com/assets/27260953/25222046/dce2b1f0-25e9-11e7-9ef3-51e6c2873af2.PNG)
Anybody have any idea on this as well? It seems when I want to install this always have this error. And PHP Artisan Key:Generate functions all not working

**Comment by snipe** [comment]
You'll have to enable debug mode in order for us to help figure out what the "whoops" error is. 

Additionally, without seeing what's on line 57 of your config/mail.php, we can't tell you what the second issue is. 

Version 2.0.* is pretty old, but we'll try to help you out.
