### ISSUE TITLE
QUESTION: How is the userid persisted throughout the session?

### ISSUE THREAD

**Issue by cnstanley** [snipe/snipe-it#3506]
Hey snipe!

Just a quick question... I am trying to implement some reports in our system, and I need to pass the currently logged in user's ID to the SQL statement. How are you persisting the user id throughout the session?

Thanks!

**Comment by snipe** [comment]
I'm not sure I understand the question - are you adding functionality to the Snipe-IT core? If so, you can use `Auth::user()->id`

**Comment by cnstanley** [comment]
Basically I am wanting to run a query: SELECT * FROM assets WHERE assigned_to = [logged in user ID], so that my end users can easily run a report that shows all assets assigned to them. So is the logged-in user ID stored in Auth::user()->id?

**Comment by snipe** [comment]
I understand that, but from where are you running this? Are you writing code for Snipe-IT, or trying to run something outside of the Snipe-IT core?

**Comment by snipe** [comment]
> So is the logged-in user ID stored in Auth::user()->id?

If you're running the code within the Snipe-IT core, `Auth::user()->id` will return the currently logged in user's ID

**Comment by cnstanley** [comment]
perfect! I'll give that a shot and see if I can get it to work! Thanks!
