### ISSUE TITLE
FR: Enhance Consumables with Toner in Mind - Be able to assign to Asset Models, Assets for install, track usage, add color.

### ISSUE THREAD

**Issue by apizz** [snipe/snipe-it#3507]
#### Expected Behavior (or desired behavior if a feature request)

Currently, consumables cannot be assigned to individual assets or models.  As such, a toner consumable cannot be assigned to its corresponding printer model for easier assigning / deploying.

Additionally, if you want to add information (like toner color) you have to create a custom field dropdown menu to accomplish this, rather than have this be a built-in option.

![screenshot 2017-04-20 22 00 53](https://cloud.githubusercontent.com/assets/11789931/25259720/d162fcb4-2615-11e7-8404-c0704d75d47b.png)

Use case example: 
1. Create new consumable (toner) with pertinent information and has the additional default fields:
- Color
- Printer asset model for which the consumable is assigned.

2. When installing toner consumable in printer, go to asset list and find the printer which the toner is to be installed.  
3. Click "Checkout" button and have an overlay window appear with a checkbox list of the toner models / colors assigned to the printer asset.
4. With the applicable checkboxes selected, click an "Install" button to install one or more consumables.  Doing this would do a number of things:

- Subtract one quantity from each of the consumable models / colors selected
- Add history entries for each consumable model / color installed to the printer: the date and time, the consumable itself, and who installed it.
- Add history entries to each consumable model / color themselves that includes: the date and time installed and the printer asset it was installed in

05. Alternatively, could go into consumables list, click "Checkout" adjacent to the individual toner consumable / color and have an overlay window appear with checkboxes for each printer asset name & model for which the consumable is assigned.

We currently use a tool called [printmaster](https://github.com/craigrodway/printmaster) for managing our printers and toner and this kind of workflow is very quick and fluid.  Not as much in Snipe-IT.

This would also have the benefit of being able to (ideally) generate reports on A) how often toner is installed in a particular printer asset B) how quickly we go through a particular toner consumable and C) what percentage of each toner consumable get installed in which assets.

**Comment by snipe** [comment]
Duplicate of #1538. (I'm using #1538 as the original reference since it seems to be the first time this feature was suggested.)
