### ISSUE TITLE
additional modules for admins only

### ISSUE THREAD

**Issue by pkurtis** [snipe/snipe-it#3508]
What file do I need to change to add table names (access, departments) and the new table data. Im getting the below attached. i have created tables access and departments. In my access table. I have the following fields. 
 
Id, account_user, password, account_name,type. 

This module is separate from the users module. As I need it to store site logins for example. Once these modules are complete I would like it to be apart of your standard package as long as my contributions count or more than happy for you to do it.

![access module](https://cloud.githubusercontent.com/assets/18567621/25264114/1633d326-26a8-11e7-8aa5-5b0baaea16a9.jpg)

ontop of that i have modified the fields to 

th data-searchable="false" data-sortable="false" data-field="id" data-visible="false">{{ trans('general.id') }}</th>
                <th data-searchable="true" data-sortable="true" data-field="Account">{{ trans('admin/access/table.account_name') }}</th>
                <th data-searchable="false" data-sortable="false" data-field="account_user">{{ trans('admin/access/table.account_user')}}</th>
                <th data-searchable="false" data-sortable="false" data-field="password">{{ trans('admin/access/table.password') }}</th>
                <th data-searchable="false" data-sortable="false" data-field="type">{{ trans('admin/access/table.type') }}</th>
                <th data-switchable="false" data-searchable="false" data-sortable="false" data-field="actions">{{ trans('table.actions') }}</th>

**Comment by snipe** [comment]
Translation files are found in `resources/lang/en`

**Comment by pkurtis** [comment]
ok cool that sorted now to show table content from database, where would that be?
