### ISSUE TITLE
Generate app key not working

### ISSUE THREAD

**Issue by Koen-ilvo** [snipe/snipe-it#3509]
#### Expected Behavior (or desired behavior if a feature request)

according to https://snipe-it.readme.io/docs/generate-your-app-key the following command should generate a key and set the APP_KEY value in the .env file:
php artisan key:generate
-----

#### Actual Behavior

Nothing happens. The command produces no output and .env is not altered. This is the content of PHP71x64_errors.log
I refer to issue 3377. Accoring to the answer I tried several changes.
The php_mysql.dll warning is gone after adapting php.ini. However, I keep running into the no file found error:
'C:\inetpub\wwwroot\snipe-it\bootstrap/../vendor/autoload.php'
in all variations of forward and back slashes, depending on changing the value of require DIR."/../vendor/autolaod.php in line 17 of autoload.php. Shouldn't there be a 'vendor' directory in the snipe-it root in order for this to work?

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
3.6.4
- What OS and web server you're running Snipe-IT on
Windows Server 2012 R2 - IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by Koen-ilvo** [comment]
I (finally) figured out how to get the key. Thanks for all the help.

**Comment by eldashjay** [comment]
> I (finally) figured out how to get the key. Thanks for all the help.

So you ask for help. Then don't provide help for anyone else once you figured it out. Nice.
