### ISSUE TITLE
Upgrade Snipe-it 2.1 to 3.6.4

### ISSUE THREAD

**Issue by jaquelino** [snipe/snipe-it#3510]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior
I used this link;
https://snipe-it.readme.io/docs/upgrading-to-v3
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 
      **3.6.4**
- What OS and web server you're running Snipe-IT on
       **OS Debian 7, Apache 2**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
     **install.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that erro

**When trying to run Step 7: Migrate the database (php artisan migrate) gave the error:
Php parse error: syntax error, unexpected ‘class’ (T_CLASS), expecting identifier (T_STRING) or variable T_VARIABLE) or  ‘{‘ or ‘$’ in /var/www/snipeit/artisan on line 31**

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
What version of PHP are you running?

**Comment by jaquelino** [comment]
PHP 5

2017-04-22 22:51 GMT-01:00 snipe <notifications@github.com>:

**Comment by snipe** [comment]
Snipe-IT requires PHP version 5.5.9 or higher, per the requirements page:
https://snipe-it.readme.io/docs/requirements
