### ISSUE TITLE
Snipe-IT directory problem

### ISSUE THREAD

**Issue by asherifdeen** [snipe/snipe-it#3512]
I get a this message "D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory." when I try to install Snipe-IT

![snipeit_error](https://cloud.githubusercontent.com/assets/9882986/25303063/18f1cec2-273b-11e7-9a00-bb5f84f96d60.jpg)

**Comment by snipe** [comment]
Then you should probably set your DocumentRoot to the public directory.
