### ISSUE TITLE
PDOException in Connector.php line 55:

### ISSUE THREAD

**Issue by Raag786** [snipe/snipe-it#3513]
i used all .env files which are given on net meanse on git hub on snipe support also currently i
am using that file which described on git hub some one to use.that code is.
Docker Environment File
Database Variables

MYSQL_ROOT_PASSWORD=supersecuresecretthing
MYSQL_DATABASE=snipeit
MYSQL_USER=root
MYSQL_PASSWORD=
Email Variables

MAIL_PORT_587_TCP_ADDR=smtp.mandrillapp.com
MAIL_PORT_587_TCP_PORT=587
MAIL_ENV_FROM_ADDR=uberbrady@gmail.com
MAIL_ENV_FROM_NAME=Brady Wetherington
MAIL_ENV_ENCRYPTION=tcp
MAIL_ENV_USERNAME=uberbrady@gmail.com
MAIL_ENV_PASSWORD=N7AqLufTZMULWHWYwJ0ZCw
MAIL_ENV_REPLYTO_ADDR=you@example.com
MAIL_ENV_REPLYTO_NAME='Snipe-IT'
SNIPE-IT Variables

APP_ENV=develop
APP_DEBUG=true
APP_KEY=Y5hJeC7x1i7OxhDrvrQPlB9KvCorvRdO
APP_URL=http://localhost:8000/
APP_TIMEZONE=US/Pacific
APP_LOCALE=en

ALLOW_IFRAMING=false

This is i am using.
i chekd my mysql that is working
For credentials

DB DTEAILS:
db name=> snipeit
user => root
pass => null

1 important point which i want to tell you is.
normally for worpress,core php,codeigniter,etc i am using localhost and
above cred,which is http://127.0.0.1/ or you can say simple localhost.

But for this i am using that command and below local host

[root@Anurag:confused:opt/lampp/htdocs/snipeit# php artisan serve]

[Laravel development server started on http://localhost:8000/]
and above db cred

All info which i have about that i give you

after that i will wait for your Precious reply
i hope this time it will be start and it will be good for me.
Thanks..

**Comment by HinchK** [comment]
`php artisan serve` directly serves the application from the php pool; there's no nginx/apache in the middle and what you see is what you get. I recommend using a very simple lamp configuration or using laravel/homestead for local development.

**Comment by snipe** [comment]
@Raag786 Using a real webserver, are you having any luck?
