### ISSUE TITLE
attaching database tables to snipeitapp

### ISSUE THREAD

**Issue by pkurtis** [snipe/snipe-it#3517]
thanks for the previous issue resolution, but i am having issue obtaining data from the tables i have created which are called ' access' and 'departments' . all i want to have the ability to do is add edit and delete. Just need abit of guidance on this one.

[snipeit.zip](https://github.com/snipe/snipe-it/files/957572/snipeit.zip)

**Comment by snipe** [comment]
@pkurtis Your best bet will be to look at the Laravel documentation. https://laravel.com/ - You'll need to create models, views and controllers to make everything work.
