### ISSUE TITLE
Cannot launch the pre-flight (setup)- WAMP on Windows 10

### ISSUE THREAD

**Issue by Nosc1234** [snipe/snipe-it#3519]
#### Expected Behavior (or desired behavior if a feature request)

(Launch the pre-flight - setup)

-----

#### Actual Behavior

(what actually happens goes here)
When I go to the URL : localhost/snipe-it

it directs me to http://localhost/snipe-it/setup

but it is waiting too long and then shows me that :

[ This page isn’t working

localhost redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS ]

-----

#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode
- [yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
3.6.4
- What OS and web server you're running Snipe-IT on
windows 10 - wampserver 3.0.6
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

manual installation

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

no error , just the messege : This page isn’t working

localhost redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
This page isn’t working

localhost redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
no

----------------

Hi , Please help me with this , I spent 12 hours trying to dig in the old issues and try to apply every possible way to just get to the pre-flight stage

I've done all the following :
-installed wampserver
-created the database and user from the mysql console and granted the previliges
-installed snipe-it manually : unzipped the file and place it in this dir (C:\wamp64\www\snipe-it )
-ran the composer installer(windows) and then ran it from the cmd ( composer install ) then ( composer clear) then ( composer dump )
- changed the DocumentRoot in the httpd.conf in the root : C:\wamp64\bin\apache\apache2.4.23\conf
by adding the following : 
 <VirtualHost *:80>
	ServerName http://localhost
	DocumentRoot c:/wamp64/www/snipe-it/public/
	<Directory  "c:/wamp64/www/snipe-it/public/">
		Allow From All
		Options +Indexes 
		AllowOverride All
		Require all granted
	</Directory>
</VirtualHost>

now when I go to the url it waits and then tells me that  This page isn’t working

localhost redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

please share ideas if possible

**Comment by HinchK** [comment]
@Nosc1234 - I just performed the steps here without a hitch: https://snipe-it.readme.io/v3.6.2/docs/wamp

A `<VirtualHost *:> ` directive can't be read in the httpd.conf file.  
The only thing we do in  `c:\wamp\bin\apache\apache2.4.9\conf\httpd.conf` is un-comment `LoadModule vhost_alias_module modules/mod_vhost_alias.so` in `c:\wamp\bin\apache\apache2.4.9\conf\httpd.conf`. 

Add your virtualhost directive to: `C:\wamp\bin\apache\apache2.4.9\conf\extra\httpd-vhosts.conf` and restart the server.
Here's mine:
```conf
<VirtualHost *:80>
    DocumentRoot "c:/wamp/www/snipe-it/public"
    ServerName "http://wamp-it.local"
    <Directory  "c:/wamp/www/snipe-it">
        Allow From All
		AllowOverride All
		Options +Indexes
        Require all granted
    </Directory>
</VirtualHost>
```
On MAMP, I wouldn't use localhost as it's used by wamp for a WAMP server management page.  On that page there is even a tool that will get your virtual-host set-up & update your hostfile:
![image](https://cloud.githubusercontent.com/assets/1509456/25509365/3099159a-2b6d-11e7-8ddb-83fc00482d20.png)

Hope that helps!

**Comment by dindin97** [comment]
Please help... fresh install on Wamp64. When i tried to List All Assets. 

**Whoops, looks like something went wrong.**
(2/2) ErrorExceptioncompact(): Undefined variable: operator (View: C:\wamp64\www\snipe-it\resources\views\hardware\index.blade.php)
--
in Builder.php line 1229
at CompilerEngine->handleViewException(object(ErrorException), 1)in PhpEngine.php line 44
at PhpEngine->evaluatePath('C:\\wamp64\\www\\snipe-it\\storage\\framework\\views/e2362a87f3b6775ae86d161760c87aef55dfe297.php', array('__env' =>object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => true, 'signedIn' => true, 'user' => object(User), 'company' => null, 'snipeSettings' => object(Setting)))in CompilerEngine.php line 59
at CompilerEngine->get('C:\\wamp64\\www\\snipe-it\\resources\\views/hardware/index.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => true, 'signedIn' => true, 'user' => object(User), 'company' => null, 'snipeSettings' => object(Setting)))in View.php line 137
at View->getContents()in View.php line 120
at View->renderContents()in View.php line 85
at View->render()in Response.php line 38
at Response->setContent(object(View))in Response.php line 206
at Response->__construct(object(View))in Router.php line 615
at Router->prepareResponse(object(Request), object(View))in Router.php line 572
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php line 43
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php line 49
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php line 49
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php line 42
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Router.php line 574
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 533
at Router->dispatchToRoute(object(Request))in Router.php line 511
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php line 51
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php line 25
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php line 27
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58
