### ISSUE TITLE
Feature Request - Depreciation Method

### ISSUE THREAD

**Issue by petrus2014** [snipe/snipe-it#352]
Hi. Any chance of being able to choose the type of depreciation method in a future release? Here, we use reducing balance method.

Thanks
Pierre
##

**Comment by kobie-chasehansen** [comment]
throw my vote in for this feature. learned today that while we use straight-line for software purchases we do 5 and 7 year 200DB accelerated depreciation on hardware and long-term hardware assets.

**Comment by snipe** [comment]
@kobie-chasehansen you'll need to explain WTF that means before I can do anything about it.. lol

**Comment by joyd86** [comment]
We can edit the Depreciable.php file under /app/Models to accommodate WDV - hopefully, the method of calculating is correct.

$purdate=date_create($this->purchase_date);
$now=date_create(date("Y-m-d"));
$datediff=date_diff($purdate,$now);
$inyear=$datediff->format("%R%Y");
$powcal = pow(1-(10/100), $inyear);
$current_value = ($this->purchase_cost * $powcal)

replacing the line:
//$current_value = round(($months_remaining/ $this->get_depreciation()->months) * $this->purchase_cost, 2);

It would be really nice if someone can explain how WDV is calculated. While searching I can across a term called "Salvage Value" - but could not understand what it is all about.

**Comment by markdueck** [comment]
I am very interested in getting this working for Reducing Balance Depreciation.  Can someone confirm if you got it working and how to do it?
