### ISSUE TITLE
Multiple Company mangement

### ISSUE THREAD

**Issue by Jason-Weber-UC** [snipe/snipe-it#3520]
#### Expected Behavior (or desired behavior if a feature request)

Is it possible to have a User be a manager (via permissions?) across multiple companies?
*Or* can a single Company have 'sub-divisions' within it?

-----

#### Actual Behavior

A person can only be a member/manager of one Company

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v3.6.4 build 12 (gf7e4fca)
- What OS and web server you're running Snipe-IT on - Debian 8
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - No
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - N/A
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. - No
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - No

**Comment by calebsutton** [comment]
This is something I am also interested in.  

Possible solution would be to have users that are not assigned to any company be available to all companies.

My use case:  I want IT and facilities to be able to use the same Snipe install.  The easiest way to accomplish this is to have IT and Facilities be separate companies and have the appropriate managers assigned to the appropriate "company" and then the end users would be able to have assets from either company assigned to them.

**Comment by ebonweaver** [comment]
Throwing in a me too here.  The new permissions are great except they are still useless for my inventory manager.  I have to make him super admin because otherwise he can't see the list of companies in the drop down when making an asset, it says "results could not be loaded".  This would be fixed for us if the new "Departments" field was actually available for assets.  As is we use Companies for departments because Departments didn't exist until now, but since they still aren't available anywhere but People it's not useful and we can't migrate fields (as I'd like to).

**Comment by ebonweaver** [comment]
Stalebot is on a rampage!  Stop it before it shuts down all the feature requests!

**Comment by macmandr197** [comment]
Has this been addressed?

**Comment by rhybvan** [comment]
I would also like this feature.
I look after 4 companies, I have a colleague who serves 2 of them and needs access to just those two, and then others who are involved with just one.  But in future, this will become even more complex and I would like to retain privacy between the companies.

**Comment by Sprizzle** [comment]
I would also like this. Would be nice for our manufacturing team to have their own inventory without it being confused with the IT department inventory.

**Comment by rbuzzell** [comment]
I have multiple different departments I'd like to have manage their own inventories.
Mine handles IT needs, one handles AV needs, and one handles musical instruments.

All of us service the same user base, all have loanable equipment, and all should be in the same tool.

**Comment by DerGemeine** [comment]
Would be a nice addition.

**Comment by jornim** [comment]
Same here.  We need a way to limit visibility for users who are part of a company (read: department) to only assets that are also in that company (department), without having to make all our help desk users Super Admins to be able to see those cross-company assets.

**Comment by Mckovsky** [comment]
Is there any chance for implemeting it? Big please!

**Comment by petersanta** [comment]
Please reopen this issue, this would be a nice feature! :) This was closed automatically by a bot without implementing the feature.

**Comment by namarie23** [comment]
+1 to this, would this be doable?? Also have multiple departments that don't need to see each others data but share users.

**Comment by Relix360** [comment]
+1

**Comment by mrphefo01** [comment]
+1

**Comment by nghia-dang** [comment]
I don't understand the logic that a user cannot be part of multiple companies, especially when there is only 1 import method via ldap..

Eg. Parent Company A-> Sub Companies B, C, D, E

If a user is employed by a parent company .. they might potentially need access to some but not all sub companies. eg If I wanted a user to be part of the parent company A, and also be part of C and E but no access or visibility or B and D how is this accomplished in snipeit without a lot of headaches ?

**Comment by poandlsl** [comment]
+1 for this feature.  It would be great to have users do LDAP authentication to manage assets in multiple companies.  The current workaround is create multiple local accounts per user, which is quite inconvenient and not scalable.

**Comment by Robert-Azelis** [comment]
Hi, if you would like to manage multi company access from permission groups, yes it is possible. I have unofficial solution, but you implement on your risk :) First of all please make a copy of orginal files:
.\snipe-it\config\permissions.php
.\snipe-it\app\Models\User.php
.\snipe-it\app\Models\Company.php
Changes relates to version 1.4.x and 1.5.x , not tested on older.
then replace by these attached:
[Multicompany mod.zip](https://github.com/snipe/snipe-it/files/6553744/Multicompany.mod.zip)

In result you should get option to manage multi company access directly in permision groups, superuser permision is not requaired.  
![Multi Company access](https://user-images.githubusercontent.com/82208283/119822062-899c8a00-bef3-11eb-9b43-d2520011f618.png)

**Comment by JonathonReinhart** [comment]
(Speaking as an outside user, not in any capacity on behalf of the project)

@Robert-Azelis Thanks a lot for your contributions! I'll point out that it might be easier for people to review and consume your work if you instead fork `snipe-it`, commit your changes to a branch (e.g. `multi-company-access`), and then post the link to your fork/branch here. One of the main reasons is that we can see the exact revision of the code on which your changes are based. If it's *really* polished, you might submit a pull request for inclusion into the codebase.

**Comment by jcookatlas** [comment]
Please re-open.  This feature is absolutely desired by the community.

**Comment by joelbreton** [comment]
Please re-open. This would be very useful.

**Comment by Robert-Azelis** [comment]
> Please re-open. This would be very useful.

it's continue under **[WIP] Add multicompany access permission #10383**

**Comment by Zack01235** [comment]
Please re-open

**Comment by tepajc** [comment]
This would be very useful, please re-open.

**Comment by BBYStudios** [comment]
+1 this would be super helpful for us as well. We would very much like to be able to permission users access to companies(departments) rather than give users super admin access. Which is a security risk.

**Comment by anthony-it-nr** [comment]
+1 - we have tier 1 helpdesk that do not need super admin to the inventory management system. We support multi-tenancy/companies so this is critical for us as well.

**Comment by thasleemnazeer** [comment]
+1
Please add this feature.

**Comment by starloopstudios** [comment]
Please add this feature.

**Comment by starloopstudios** [comment]
Bump here, We need it!

**Comment by SteeleCQ** [comment]
The community really needs this as a new feature for more granular control for assets at locations and assigned to departments without giving everyone super user access. 
We have staff that may be responsible for managing assets at either:

- Location 1
- Location 1 & 3
- Location 2 & 3 & 5
- All Locations
- Only assets assigned to a department at locations 1 & 2 & 4 & 5
- Only assets assigned to a department at all locations

**Comment by michaellenhart** [comment]
+1 I realy need this feature.
Why can't a member be part of two companies or more, by adding a multiple choice menu where you can select as a Superadmin the companies of the member.

**Comment by investlab** [comment]
+1 I realy need this feature.

**Comment by starloopstudios** [comment]
We really need this. We are a big group and all companies are on the snipe-it instance and we have troubles letting some heads of department see things assigned to people.

**Comment by JasonZhang0320** [comment]
+1 I’d love to see this feature added! It’s super important and would help a lot.
