### ISSUE TITLE
Duplicate DEPLOYED link in ASSETS tab

### ISSUE THREAD

**Issue by mfahmi37** [snipe/snipe-it#3521]
#### Expected Behavior (or desired behavior if a feature request)

ASSET TAB should only show 1 DEPLOYED status instead of twice. Check screenshot.

-----

#### Actual Behavior

duplicate DEPLOYED button in ASSET tab.
![capture_duplicate_deployed_status](https://cloud.githubusercontent.com/assets/25362203/25521265/8041b010-2c31-11e7-8bca-d0c43a6e11fa.jpg)

-----

#### Please confirm you have done the following before posting your bug report:

- [ YES ] I have enabled debug mode YES
- [ YES] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) YES

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 
3.6.3
- What OS and web server you're running Snipe-IT on
Centos 6
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
It's not actually a duplicate - it's the difference between the "magical" deployed status of Deployed (An asset is deployable AND is checked out to someone), versus a regular status label that someone on your end named "Deployable". https://snipe-it.readme.io/docs/overview#section-status-labels
