### ISSUE TITLE
Feature Request : assign asset to another asset or trackable component

### ISSUE THREAD

**Issue by xudaiqing** [snipe/snipe-it#3522]
#### desired behavior

an asset or component can be assign to another asset but still can track individually.

-----

I recently test another software called Asset Tracker for JIRA (https://marketplace.atlassian.com/plugins/com.spartez.jira.plugins.ephor-for-jira/server/overview)
one thing i like is it's every thing as asset and tree like ownership model. which solved my need nicely and allow even more flex operation. Through i am not sure that kind of feature is possible in snipeit

**Comment by snipe** [comment]
Assets can now be checked out to other assets, as of v4.
