### ISSUE TITLE
Feature Request: Notify user of license checkout/details

### ISSUE THREAD

**Issue by Git-Rajkumar** [snipe/snipe-it#3523]
Hello, snipeit can sent external emails?, I need to sent email, when added new licenses then sent email to customer(based on license email field) or any other way to sent our license to customer via snipeit.

**Comment by g33kphr33k** [comment]
Snipe will use the email as it's configured in the .env configuration file.  If your mail server can send externally then so can Snipe if you configure it correctly.

**Comment by snipe** [comment]
> I need to sent email, when added new licenses then sent email to customer (based on license email field) or any other way to sent our license to customer via snipeit.

We do not currently have a way to send license information to a customer (and the licensed to field is not always the actual person who is using the license anyway.)
