### ISSUE TITLE
V4 : ADDED (Experimental) Ability to check assets out to users, locations and other assets

### ISSUE THREAD

**Issue by sysnoo** [snipe/snipe-it#3525]
Hi,
I just installed v4.0-alpha-2 but I can't find the feature listed in the change log.
ADDED (Experimental) Ability to check assets out to users, locations and other assets

**Comment by dmeltzer** [comment]
When you go to checkout an asset you should now see dropdowns for assets and locations as well as users.

**Comment by sysnoo** [comment]
Nope, I see only checkout to a user.
In the footer I see the version : Version v3.6.4 build 12 (gf7e4fca).
The source I downloaded is v4.0-alpha-2.tar.gz

**Comment by chibacityblues** [comment]
Same problem. I'm using Docker image snipe/snipe-it:v4.0-alpha-2

**Comment by jasonspriggs** [comment]
Small bug:

It appears that checking out an asset to a Location...
<img width="1220" alt="screen shot 2017-07-08 at 12 36 11 pm" src="https://user-images.githubusercontent.com/16108587/27987471-38e5782c-63dc-11e7-9b91-9811ba5adc3c.png">
...does not allow you to check it back in from the Asset Listing view.
<img width="1221" alt="screen shot 2017-07-08 at 12 36 38 pm" src="https://user-images.githubusercontent.com/16108587/27987470-38dea43e-63dc-11e7-92bc-fb9d502119ed.png">

**Comment by jasonspriggs** [comment]
Another thing:

Checking an asset out to a Location, checking it back in, checking it out to a user, checking it back in, and then attempting to check it out to a Location again will not clear the last user it was checked out to and will show it being checked out to both a location and a user when it should only be a location.
