### ISSUE TITLE
Get full Asset excel report

### ISSUE THREAD

**Issue by ifoyil** [snipe/snipe-it#3527]
We couldn't get full report on excel file; We have about 2577 asset inside but software is just giving 50 or maximum 200 digest excel columns asset report; How to solve it, We're just getting "Showing page rows" (50/100/150/200) report on excel; we can't get all assets report into the same excel; Snipe-it version 3.6.4
do you have any command about it,

**Comment by louisdj** [comment]
Can you try through the 'Custom report' function? I have the same problem, if you use the default export function, you only export what's displayed on your screen.

**Comment by ifoyil** [comment]
Hi louis, Custom report is giving to us CSV format; is there any possibility to get full Excel format report,

**Comment by louisdj** [comment]
You can open the .csv in excel and use the text to columns function to change the format from csv to Excel.

**Comment by ifoyil** [comment]
Hi, a bit disappointed for me, we couldn't think that we can't get full asset file on excel file, Can I any chance to extend maximum row display, it's showing maximum 200 rows is there any options to show all of rows into same page, after that I can get full report I'm supposing, maybe I need to change some code php file about it, I need this function absolutely, waiting your assists about it or I hope new 4.0 version will be supported with this function.

**Comment by ifoyil** [comment]
![2343](https://cloud.githubusercontent.com/assets/26713563/25649195/13ea91f8-2fdc-11e7-8945-92d0a5d0c717.JPG)

**Comment by ifoyil** [comment]
I found temporarily way I changed per_page database settings number; I is started display more rows I got my report on excel :)

**Comment by ifoyil** [comment]
![345](https://cloud.githubusercontent.com/assets/26713563/25650700/6d734bc4-2fe7-11e7-99c5-6f63a93ca7ff.JPG)

**Comment by snipe** [comment]
It's much better to must use the custom asset report under Reports. The listings pages can get slow loading thousands of items on a page load. It's stuffing a lot of info into the DOM.

**Comment by ragnarcx** [comment]
Hi @ifoyil can you explain for me how to change the number per_page to 2000? Thank you so much.

**Comment by ifoyil** [comment]
Hi @ragnarcx You should change to "per_page" settings in mysql, When you enter to the mysql you can display settings you can see there; 
But When you get full report just change this settings otherwise it will be display very huge assets all time into the same page and also it will be more slowly and within the display problems
If it be use just full report it will be better after that you can change to same settings 50 number

![resim](https://user-images.githubusercontent.com/26713563/28704158-6e00d30e-7371-11e7-8221-7e50ebf42610.png)

**Comment by ragnarcx** [comment]
@ifoyil I can't find "per_page" setting in mysql like you. Sorry, my level in mysql very low :(

**Comment by ifoyil** [comment]
install to heidisql tool you can easily enter to your sql
