### ISSUE TITLE
Moving 3.6.2 to new server

### ISSUE THREAD

**Issue by bitmadmax** [snipe/snipe-it#3530]
Hi all,

I have Snipe 3.6.2 in our org running on a test server (Ubuntu). Now that we have finished tinkering and testing I would like to move this to another server which hosts a number of web applications and as such already runs apache/mysql etc. I am worried about running the installer that comes bundled with Snipe incase it conflicts with the already existing setup. Is there a very high level process I can follow to simply migrate my existing snipe setup to the new server (Ubuntu)?

Many thanks and more!

**Comment by snipe** [comment]
If you know how to set up a VirtualHost on your new Ubuntu server, the easiest way to handle the move will be to do that and just follow the directions for the Git install method (preferred).

**Comment by bitmadmax** [comment]
OK, thanks. Unfortunately we can't use virtual hosts, so I've setup an alias on the default virtual instance to point to the /snipeit directory. I pulled the git files to this directory, installed all the prerequisites and modified the .env file with my settings and app key. I've attached my database.At first when I was browsing to the site I was getting the "whoops.. looks like something went wrong".. so I enabled debug to see what the issue was and I am getting runtime exception in compiled.php line 7771: No supported encrypter found. the cipher and / or key length are invalid. in my .env APP_KEY='same32characterkeyasoldinstallation' The cipher in the app.php is rijndael-256.

I have tried regenerate the key using artisan but this seems to prefix the key with BASE64 and still gives the same error ?

BTW< forgot to mention I am running php7

**Comment by bitmadmax** [comment]
Apologies, forgot to set the cipher to AES-256-CBC in config/app.php and that's fixed that little problem.

However I have a new issue - I am getting 404 not found (requested URL /snipeit/login was not found). The only way around this appears to be to use the address <servername>/snipeit/index.php/login which seems to work OK after logging in but leaves the slightly elongated address.

As I say, i'm rather limited by using an alias and my 000-default.conf in sites-enabled has the entry `Alias /snipeit aliasing to /var/www/html/snipeit/public`. What do I need to check so I get the "natural" URL's e.g <servername>/snipeit/login? Thanks :)

**Comment by snipe** [comment]
Are you running this in a sub-directory or a subdomain?

**Comment by bitmadmax** [comment]
Hi, It's running in a subdirectory (/var/www/html/snipeit/public) with the URL being http://servername/snipeit

Just realised I've been really helpful and not included the Apache/php log, I'll have a look at them for anything glaringly obvious when I'm back in the office and get back to you. Thanks for your help :)

**Comment by bitmadmax** [comment]
Hi,

This is resolved after I followed your "subdirectory" guide with the alias and mod rewrite instructions. Thanks !!!
