### ISSUE TITLE
Importing Assets

### ISSUE THREAD

**Issue by elJoeyJojo** [snipe/snipe-it#3533]
#### Expected Behavior (or desired behavior if a feature request)

I would like to change the "asset tag"s for a few hundred PCs by exporting the the selected PCs, changing the "asset tag"s on the assets and then importing that file back in. I'd also like it to remember who it was checked out to.
-----

#### Actual Behavior

From the Web Console I try to Import a file that has the necessary fields of Asset Tag, Category, Model name and Manufacturer but I keep getting an error "File(s) not uploaded. Please try again"

![image](https://cloud.githubusercontent.com/assets/17091968/25684110/773c9aac-3014-11e7-9412-e3b6d28f4558.png)

I have tried .csv .txt and even added more fields but no luck
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v3.6.3 build 15
- What OS and web server you're running Snipe-IT on - CentOS 6.8
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - GIT
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - 
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - snipeit.com/hardware/import
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. "File not uploaded. Please try again.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by elJoeyJojo** [comment]
@snipe any idea? thanks

**Comment by snipe** [comment]
Asset tags are the unique identifier that the system uses to determine whether the asset is an update or a new insertion, so I'm not sure how you'd do that.
