### ISSUE TITLE
Feature Request:  IP Tracking and Assignment

### ISSUE THREAD

**Issue by g33kphr33k** [snipe/snipe-it#3536]
We're moving from using a different asset database to Snipe-IT (Well done, awesome software).  Is there any chance of adding an additional section like you have with consumables but for IP addresses?

We have a mixture of static and DHCP addresses listed in a Spreadsheet and it would be great to be able to assign those directly to servers/PCs/Switches and see what is and isn't available in a list view.  Right now I've added an additional field to machines that we can fill this in to but having it as it's own table structure would be amazing.

We're more than happy to pay for this development.

**Comment by jasonspriggs** [comment]
Would this be implementing IPAM inside of Snipe IT or trying to make some form of integration with an existing IPAM software?

**Comment by tioan** [comment]
Integration with https://github.com/digitalocean/netbox would be awesome

**Comment by rungej** [comment]
+1

**Comment by Pimmetje** [comment]
If u need any idea's for a ipam module u can look at https://phpipam.net/

**Comment by bishu05** [comment]
+1

**Comment by load-nikon** [comment]
+1

**Comment by phsmichael** [comment]
+1

**Comment by xkx** [comment]
+1

**Comment by Orfeous** [comment]
+1
