### ISSUE TITLE
[QUESTION] - Can SnipeIT send mail when EOL of a model is expired?

### ISSUE THREAD

**Issue by richardsith** [snipe/snipe-it#3539]
Hi I want to know if SnipeIt can inform us when the EOL Rate or the Warranty  of a model are expired . 
Thanks

**Comment by richardsith** [comment]
is it possible that? thanks

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/configuring-alerts
https://snipe-it.readme.io/docs/configuring-alerts-backups
