### ISSUE TITLE
receive a mail of confirm for Admin

### ISSUE THREAD

**Issue by richardsith** [snipe/snipe-it#3540]
Hi Team,
I'd like that also admin, after have made a Check Out/in of an item, receive an email of confirm for a item that has been received or not from user. Is it possible to set that?

thanks

**Comment by snipe** [comment]
@richardsith you set that up at the category level. 

<img width="433" alt="update_category____snipe-it_asset_management" src="https://cloud.githubusercontent.com/assets/197404/25833665/e88eaae4-3427-11e7-9b84-57444191d73c.png">

**Comment by richardsith** [comment]
yes that has already done, but it sends email only to user who receives the item and not to admin. I'd like that more than user also of admin receive that, to have a track of all actions of that item.
