### ISSUE TITLE
Windows Platform, Admin-backups, wrong backup path and slash

### ISSUE THREAD

**Issue by az0522** [snipe/snipe-it#3541]
Hello there,
i'm running Snipe-it on windows2012 with IIS and php7.

Version v3.6.2 build 10 (g927a12f)

the backup function under "Admin" --- "backups" does not work, and the backup path shows:

Backup files are located in: 
C:\inetpub\snipe\storage/app/backups 

seems wrong slash "/" here before "app" and "backups", 

And not able to create the backup files.

could you please tell me how to change the slash to correct one "\" ?

thank you.

here's the screenshot.
http://bbs.sjtu.edu.cn/file/PhD/1494056106224970.jpg

**Comment by BrettFagerlund** [comment]
That slash shouldn't matter and won't usually cause any problems.

Please confirm the DB_DUMP_PATH in env file, and also IIS_IUSRS write permissions on the storage/laravel-backups folder.
Also, is there anything in the laravel log regarding the failure?

**Comment by az0522** [comment]
thank you for the reply, Brett :)

issue is when I click the "generate backup" button, no new backup files are created under "C:\inetpub\snipe\storage\app\backups", 
but the notification message shows " Success: A new backup file was successfully created."

the db_dump_path is here:
DB_DUMP_PATH='C:\\PROGRA~1\\MySQL\\MYSQLS~1.7\\bin'

yep, the iis_iusrs has modify permission on storage/laravel-backups folder.

the laravel log shows:
 
[2017-05-09 13:15:34] production.ERROR: backups backups : error: Failed to backup  because: The dump process failed with exitcode 1 : General error :

**Comment by BrettFagerlund** [comment]
Please also check your C:\Windows\Temp folder for IIS_IUSRS modify perms, both these IIS_IUSRS permissions are in addition to the IUSR perm's listed in setup documentation.

This access in particular though, will cause that exact error without anything beyond General error :

**Comment by az0522** [comment]
@BrettFagerlund 
yep, that's it, now the new backup file is in the path.
thank you very much. :)
