### ISSUE TITLE
Change access URL

### ISSUE THREAD

**Issue by bsurensoy** [snipe/snipe-it#3542]
Hi
Thats maybe very funny problem but im very new about web apps . I wanted to change my access url to app to server's IP. Can you help me about how can i change it. And pls tell me that like a dummy.

Kind Regards.

#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

**Comment by bsurensoy** [comment]
You can find my answers following bellow.


  *   Version of Snipe-IT you're running Version v3.6.4 build 12 (gf7e4fca)
  *   What OS and web server you're running Snipe-IT on Ubuntu 16.04.2 LTS
  *   What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Download the Installer

**Comment by snipe** [comment]
You would just change your APP_URL in your .env (but I assume you already figured that out)

**Comment by zzzzMinde** [comment]
but that means when i connect to it from an external IP, it directs the browser to its internal IP which I don't have access to?
