### ISSUE TITLE
Feature request - Consumables, assign to asset, account for deliveries and reporting

### ISSUE THREAD

**Issue by graywoodford** [snipe/snipe-it#3543]
#### Expected Behavior (or desired behavior if a feature request)
Would it be possible to get consumables to have the option to assign to an asset the same as you can with components?  For example I have checked out a toner to a printer and it is tracked where and when rather than to a user?

With the consumable can you all so take in to account for deliveries? For example I have used all my toner up and have had a delivery of more, can I just check in a delivery that takes in to account a new price? 

With is it possible to get reporting on consumables too? There are fantastic reports for assets but none I can see for consumables?

-----

#### Actual Behavior

Consumables are able to be checked out to a user only, no reporting

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode - no, feature request
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) - yes, feature request

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - **3.6.4 build 12**
- What OS and web server you're running Snipe-IT on - **Ubuntu 16.04**

**Comment by graywoodford** [comment]
thank you

**Comment by victoriapak** [comment]
A suggestion from user RE consumable inventory: What it needs is easy to use button to add replacement inventory. I think its too easy to mistake that lets say I get 4 new toner cartridges because I am low, I cant just go make it 4, I have to add 4 to whatever is on the box.  It's very confusing and too easy to mess up.

**Comment by MeklonDramicus** [comment]
Would love to see consumables being allocated to assets! +1
