### ISSUE TITLE
SMTP Server Error

### ISSUE THREAD

**Issue by firatnemis** [snipe/snipe-it#3544]
Hello, 

I know you are not supporting except your hosts but i made research a lot over the google but i could not find any solution please try to help me ... 

I setup my smtp configuration as you seen in below : 

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=sfn@sfn.me
MAIL_PASSWORD=*******
MAIL_ENCRYPTION=TLS
MAIL_FROM_ADDR=sfn@sfn.me
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=sfn@sfn.me
MAIL_REPLYTO_NAME='Snipe-IT'

But when i create users and select send e-mail credentials to the user it gets me an error " Whopps something wrong ". 

Note : I checked my google apps configuration and i made all steps as you explained on your webpage app permission etc... 

Thank you,

#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by MiBaDK** [comment]
1) The email notification on the issue shows password in clear text. You might wanna change that now :)

2) Do you have 2FA enabled on the account? If so then you need to create an application specific password for the SMTP. That's done on you Google account.

**Comment by snipe** [comment]
> WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

We cannot help you without detailed error information.
