### ISSUE TITLE
List Box Custom Fields are limited to 255 characters 

### ISSUE THREAD

**Issue by cwindus** [snipe/snipe-it#3546]
#### Expected Behavior (or desired behavior if a feature request)
When creating a list box custom field, expected behaviour is to be able to create a list of "infinite" length.

-----

#### Actual Behavior
When a list box is created and the total length of characters exceeds 255, the list is truncated.
See attached screenshots.
![screen shot 2017-05-09 at 8 02 46 am](https://cloud.githubusercontent.com/assets/17076873/25827345/1ea7c870-348e-11e7-9565-f7063a3bed55.png)
![screen shot 2017-05-09 at 8 03 15 am](https://cloud.githubusercontent.com/assets/17076873/25827346/1ee95ff6-348e-11e7-9635-256692ee1569.png)

-----

#### Suggested Change
Currently there is a field `field_values` in the `custom_fields` table that is `varchar(255)` - this stores exactly what was provided in the web UI form, capped at 255 char.
Rather than store the custom field contents in the one field, each entry should be stored in their own row.

I also suggest that the web UI shouldn't be a single text field for when creating a list box custom field - instead, switch to single input values, with a mechanism to "add" additional items to the list, similar to the screenshot below.
![screen shot 2017-05-09 at 8 27 46 am](https://cloud.githubusercontent.com/assets/17076873/25828036/73bf76ac-3491-11e7-926c-532725f41531.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
Version v3.6.4 build 12 (gf7e4fca)

- What OS and web server you're running Snipe-IT on
Debian Jessie, Apache 2.4.something

- Indicate whether or not you've manually edited any data directly in the database
No modifications to the schema relating to this field have been made.

**Comment by snipe** [comment]
This will be fixed in v4
