### ISSUE TITLE
Change host name

### ISSUE THREAD

**Issue by Sharoni-il** [snipe/snipe-it#3550]
Hello SnipeIT support
After install snipe with the script on ubuntu server i'v changed the host name manually , for some pages its ok but still if i press for example on SNIPEIT logo or username i'm getting the old host name on the URL bar and page error "This site can’t be reached",  i couldnt find which files can i change the host name inside the snipeit folders, is it possible? 
Thanks in advance (great software)
Sharoni

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/configuration#section-required-basic-app-settings

`APP_URL`

**Comment by Sharoni-il** [comment]
Hi snipe and thanks for answer, still have the same problem, i'v attached screenshot of the error i have if it is possible for you to inspect

thanks!

![snipeiterror](https://cloud.githubusercontent.com/assets/28565006/25907932/87528472-35b1-11e7-8334-fec67bf1b702.jpg)

**Comment by snipe** [comment]
That uses the `APP_URL` in your `.env`:

```
  @if ($snipeSettings->brand == '3')
                      <a class="logo navbar-brand no-hover" href="{{ config('app.url') }}">
                          <img class="navbar-brand-img" src="{{ config('app.url') }}/uploads/{{ $snipeSettings->logo }}">
                          {{ $snipeSettings->site_name }}
                      </a>
                  @elseif ($snipeSettings->brand == '2')
                      <a class="logo navbar-brand no-hover" href="{{ config('app.url') }}">
                          <img class="navbar-brand-img" src="{{ config('app.url') }}/uploads/{{ $snipeSettings->logo }}">
                      </a>
                  @else
                      <a class="logo no-hover" href="{{ config('app.url') }}">
                          {{ $snipeSettings->site_name }}
                      </a>
                  @endif
``` 

Try [clearing your config cache](https://snipe-it.readme.io/docs/common-issues#section-changes-to-my-env-file-dont-seem-to-be-updating), and deleting cached views:

```
php artisan view:clear
php artisan config:clear
```

**Comment by Sharoni-il** [comment]
very weird problem, i'v changed the host name in every file i can think of inside the snipeit and apache2 folders but with no success, i gave up and reinstall,
thanks for help!

**Comment by regjonh** [comment]
Your fix might be here: https://github.com/snipe/snipe-it/issues/4530#issuecomment-584852623
