### ISSUE TITLE
Pages slow to load referencing external content

### ISSUE THREAD

**Issue by bitmadmax** [snipe/snipe-it#3551]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ Y] I have enabled debug mode
- [Y ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - 3.6.4
- What OS and web server you're running Snipe-IT on - Ubuntu 16.04/Apache 2.4.18
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual

Despite having the remote scripts option disabled in the admin configuration, when viewing pages within the application the browser is making requests for fonts.googleapis.com. As we are on a secure network physically airgapped from the internet, this delays the loading of pages until the request times out and slows down a little the general user experience.

**Comment by snipe** [comment]
This is already fixed in 4.0
