### ISSUE TITLE
Alert e-mails not being sent to multiple recipients

### ISSUE THREAD

**Issue by rmhst5** [snipe/snipe-it#3552]
#### Expected Behavior (or desired behavior if a feature request)

E-mail alerts are sent to all recipients in the comma-separated "Send Alerts To" field.
-----

#### Actual Behavior

Alert is sent to the first recipient. Other users in list do not receive the e-mail. However, e-mail headers list all e-mail addresses listed in "Send Alerts To" field of Snipe-IT in "To:" field of e-mail.

-----

#### Please confirm you have done the following before posting your bug report:

- [ X ] I have enabled debug mode
- [ X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
   v3.6.3 build 15 (g1bf34d7)
- What OS and web server you're running Snipe-IT on
Ubuntu 12 & Apache2 in a docker container. Host system is SLES 12.
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Docker (1.12.6-90.1)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No errors in browser
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
No specific page. Alerts are triggered manually by sending "php artisan snipeit:inventory-alerts" command to snipeit container. Cron job is set up to perform the same functionality each night. Job fails to execute (separate issue which I plan to resolve myself).
- If a stacktrace is provided in the error, include that too.
No error message
- Any errors that appear in your browser's error console.
None
- Confirm whether the error is [reproducible on the demo](https://snipeitapp.com/demo).
No. E-mail functionality is disabled on the demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
No relevant issues in:
/var/www/html/storage/logs/laravel.log
/var/log/dmesg (both host and docker container)
/var/log/apache2/error.log
- Include what you've done so far in the installation, and if you got any error messages along the way.
Installed Snipe-IT via Docker container using the procedure outlined on https://snipe-it.readme.io/docs/docker , successfully completing installation without error. Have successfully populated database and have been using Snipe-IT for several months.
- Indicate whether or not you've manually edited any data directly in the database
No.

Adding additional users on alert list is a new request by management. While a mailing list has been created, there are additional users who need to be added, prompting me to add them manually to the alert list. While it would be possible to add my users to the mailing list, my thoughts are that this issue may affect other Snipe-IT users, as this is relatively new functionality.

**Comment by snipe** [comment]
This functionality really isn't that new though, and we haven't had reports of it being broken from anyone else. What's in your laravel log?

**Comment by rmhst5** [comment]
root@e76e4d8ff19b:/var/www/html/storage/logs# cat laravel.log
[2017-05-09 11:12:00] production.DEBUG: LDAP is enabled.  
[2017-05-09 11:12:00] production.DEBUG: Binding user to LDAP.  
[2017-05-09 11:12:03] production.DEBUG: LDAP user rmhst5 not found in LDAP or could not bind  
[2017-05-09 11:12:03] production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory  
[2017-05-09 11:12:03] production.DEBUG: Authenticating user against database.

**Comment by snipe** [comment]
Change the mail driver to log in the .env and re-trigger the alert, and tell me what new stuff shows up in the log.

**Comment by rmhst5** [comment]
root@e76e4d8ff19b:/var/www/html/storage/logs# cat laravel.log 
[2017-05-09 11:12:00] production.DEBUG: LDAP is enabled.  
[2017-05-09 11:12:00] production.DEBUG: Binding user to LDAP.  
[2017-05-09 11:12:03] production.DEBUG: LDAP user rmhst5 not found in LDAP or could not bind  
[2017-05-09 11:12:03] production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory  
[2017-05-09 11:12:03] production.DEBUG: Authenticating user against database.  
[2017-05-09 14:09:41] production.ERROR: exception 'Symfony\Component\Console\Exception\CommandNotFoundException' with message 'Command "dump-autoloads" is not defined.' in /var/www/html/vendor/symfony/console/Application.php:515
Stack trace:
#0 /var/www/html/vendor/symfony/console/Application.php(183): Symfony\Component\Console\Application->find('dump-autoloads')
#1 /var/www/html/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 {main}  
[2017-05-09 14:23:13] production.ERROR: exception 'Symfony\Component\Console\Exception\CommandNotFoundException' with message 'There are no commands defined in the "snipeit:expiring" namespace.

Did you mean this?
    snipeit' in /var/www/html/vendor/symfony/console/Application.php:469
Stack trace:
#0 /var/www/html/vendor/symfony/console/Application.php(501): Symfony\Component\Console\Application->findNamespace('snipeit:expirin...')
#1 /var/www/html/vendor/symfony/console/Application.php(183): Symfony\Component\Console\Application->find('snipeit:expirin...')
#2 /var/www/html/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main}  
[2017-05-09 14:23:31] production.ERROR: exception 'Symfony\Component\Console\Exception\CommandNotFoundException' with message 'Command "snipeit:expiration-alerts" is not defined.

Did you mean one of these?
    snipeit:expiring-alerts
    snipeit:ldap-disable
    snipeit:purge
    snipeit:backup
    snipeit:ldap-sync
    snipeit:license-import
    snipeit:create-admin
    snipeit:inventory-alerts
    snipeit:pave
    snipeit:import' in /var/www/html/vendor/symfony/console/Application.php:515
Stack trace:
#0 /var/www/html/vendor/symfony/console/Application.php(183): Symfony\Component\Console\Application->find('snipeit:expirat...')
#1 /var/www/html/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 {main}  
[2017-05-09 14:27:27] production.ERROR: exception 'Symfony\Component\Console\Exception\RuntimeException' with message 'Not enough arguments (missing: "filename").' in /var/www/html/vendor/symfony/console/Input/Input.php:83
Stack trace:
#0 /var/www/html/vendor/symfony/console/Command/Command.php(251): Symfony\Component\Console\Input\Input->validate()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /var/www/html/vendor/symfony/console/Application.php(794): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/html/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\ObjectImportCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/html/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/html/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 {main}  
root@e76e4d8ff19b:/var/www/html/storage/logs# 

There is no change related to this issue in the logs. This is with both "mail" and "sendmail" specified as the driver in the MAIL_DRIVER setting of the env file.

**Comment by rmhst5** [comment]
Additional testing has revealed that I am able to send an e-mail alert to multiple groups, who each receive an alert message (I didn't test for users who are in both groups). However, I cannot send to a mixed list of individuals and groups, or to multiple individuals (only the first address specified will receive the message).

**Comment by snipe** [comment]
Snipe-IT has no way of knowing whether an email address is a role/group email or a singular one. That sounds like there's something amiss on the email server's end.

**Comment by snipe** [comment]
(Also make sure you test with no spaces between the email addresses, and test if it matters which email address you put first.)

**Comment by rmhst5** [comment]
The thought that Snipe-IT would not be able to discern between individuals and groups was actually what lead to testing whether mixed lists of groups and individuals were affected, which lead to testing multiple groups. I have no idea why the issue does not affect multiple groups, whereas multiple individuals are affected.

I have tested this issue with an e-mail list which does not contain spaces between addresses such as jsmith@company.com,jjones@company.com ). Whoever is listed first in the e-mail will receive the message, but the second, third, etc. person will not receive the message. In this example, jsmith would receive the message, but jjones would not. However, as mentioned previously, if multiple groups are specified (such as ticket@company.com,itdept@company.com ) then Snipe-IT is able to send the message to all individuals in both groups (although testing individuals who are part of both groups has not been tested).

I agree with your assessment that this is likely a mailserver issue. Unless you have any further suggestions for testing Snipe-IT, I will close this ticket and open one with my mail provider. As a workaround, I will use multiple groups and lump any "outliers" into a general snipe-it group until this issue can be resolved.

**Comment by snipe** [comment]
Unfortunately, I have no idea what could be happening here. I know @uberbrady works with mail servers a lot, so I've tagged him in this issue just in case he can think of anything that could be responsible for this behavior. I wish I had more suggestions for you. :-/

**Comment by uberbrady** [comment]
I don't think it's a mailserver issue, I think it's more of a SwiftMailer one. I think you'd need to add code in Snipe-IT to detect a space (or maybe comma? But probably space is better), and, in that case, split and then put the resulting array as the `"to" => ...` element.

(reason: SMTP recipients have to get broken out into their own `RCPT TO:` lines, e.g.)

```
...
RCPT TO: "Firstname Lastname" <first.last@domain.blah>
RCPT TO: "First2 Last2" <f.last2@otherdomain.blerg>
...
```
(And I don't think Laravel's Mail driver or Swiftmailer will do that unless you explicitly give them an array of recipients?)

**Comment by yogeshredhat** [comment]
hi
