### ISSUE TITLE
LDAP Import Failing

### ISSUE THREAD

**Issue by ericdude101** [snipe/snipe-it#3553]
#### Expected Behavior (or desired behavior if a feature request)

Querying LDAP to pull down all active users in in given scope.

-----

#### Actual Behavior

Due to my environment having 5,800 accounts (more than 1,000) the query fails. When attempting to run the import, the page crashed and returned a 500 error in client browser after about 15 seconds. If I adjust the query to a smaller scope it runs fine.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: **3.6.4**
- What OS and web server you're running Snipe-IT: **CentOS 7, Apache.**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): **install.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: **None, browser just displays 500 error**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: **After setting LDAP query to large scope, site crashed upon import and any new logins to the site fail with site 500 error.**
- If a stacktrace is provided in the error, include that too: **None**
- Any errors that appear in your browser's error console: **500**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): **N/A**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs: **Log directory doesnt exist**
- Include what you've done so far in the installation, and if you got any error messages along the way: **I know this is an issue with the query, but not sure how to modify it to be paged or acceptable**
- Indicate whether or not you've manually edited any data directly in the database: **None**

If someone could help me modify the LDAP settings to support large queries, we are using active directory and LDAP v3.

**Comment by ericdude101** [comment]
Still trying to locate error specific logs on the server, I was able to verify the paging settings existed in the LDAP.php file to support large queries.

**Comment by ericdude101** [comment]
What can I do to log the output of the LDAP import process to see whats causing the crash?

**Comment by snipe** [comment]
Check the server logs and app log

**Comment by ericdude101** [comment]
Stood up a windows box with IIS 8 & PHP 7.1, and the import works fine. so this is an issue specific to my previous build on CentOS 7 running apache.
