### ISSUE TITLE
Feature Request - Double Depreciation

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#3554]
#### Desired Behavior

Additional depreciation formula for expensive, short lived assets. MacBook Pro's for example. 

Here is an [explanation of the math](http://www.investopedia.com/terms/d/double-declining-balance-depreciation-method.asp)

"Using the double declining balance method, however, it would deduct 20% (double 10%) of $30,000 in year one ($6,000), 20% of $24,000 ($30,000 minus $6,000) in year two ($4,800), and so on."

-----

#### Actual Behavior

Straight-line Depreciation is the only available option.

**Comment by Jarli01** [comment]
Because the double declining balance method results in larger depreciation expenses near the beginning of an asset’s life and smaller depreciation expenses later on, it makes sense to use this method with assets that lose value quickly.

**Comment by uberbrady** [comment]
And, yes, this method would require a custom salvage value to be settable for it to work properly, I think (the auto-closed associated issue of #3562). We could potentially make that be a 'custom field' - which also ties into Model - but it feels weird to be doing Proper Math on what is effectively just a 'custom field' - so I'm not sure that's the correct thing to be doing here.
