### ISSUE TITLE
"Generate Labels" permissions

### ISSUE THREAD

**Issue by Jason-Weber-UC** [snipe/snipe-it#3558]
Other than making someone a super-admin, I cant seem give permissions to generate labels?
![screen shot 2017-05-10 at 2 40 20 pm](https://cloud.githubusercontent.com/assets/28076245/25883510/a21a4218-358e-11e7-8159-0f2b5d2cc42b.jpg)

**Comment by Jason-Weber-UC** [comment]
I've just tried to create a user within the Demo (Jason Test) and give "Admin" permissions (as opposed to super-admin) and assign to a company. Also assigned a few assets to said company.
*Seems* to be disabled.....

**Comment by Jason-Weber-UC** [comment]
Any help on this?
It's kinda my last stumbling block (now that the fuzzy barcodes are sorted)

**Comment by Jason-Weber-UC** [comment]
Ok... digging through the code (remember: I'm NOT a programmer...)

It looks like the barcode generation uses getQrCode?
Within getQrCode there is: if (!Company::isCurrentUserHasAccess($asset))
I cant seem to find any 'label specific' permissions, so I assume its just "Is the user allocated to the Company?"

**Comment by snipe** [comment]
`getQrCode()` just gets an individual QR code for browser display/caching. I think this section is what's triggering your error. https://github.com/snipe/snipe-it/blob/master/app/Http/Controllers/AssetsController.php#L1418-L1420

That method calls:

```
public static function isCurrentUserAuthorized()
{
        return ((!static::isFullMultipleCompanySupportEnabled()) || (Auth::user()->isSuperUser()));
}
```

So yes, it looks like only superusers can generate labels IF full company support is enabled. I believe this has been resolved in the upcoming v4.

**Comment by Jason-Weber-UC** [comment]
Is there any fix/hack I can apply to v3?

**Comment by Jason-Weber-UC** [comment]
will ->isAdmin() work?

**Comment by snipe** [comment]
Don't change the `isCurrentUserAuthorized()` method - that's an authorization method that could have much further-reaching impact than just labels, and could open things up to people being allowed to do things they're not supposed to be able to do. 

If you have to make this work for v3, change:

 ```
if (!Company::isCurrentUserAuthorized()) {
   return redirect()->to('hardware')->with('error', trans('general.insufficient_permissions'));
} elseif (!Input::has('edit_asset')) {
    return redirect()->back()->with('error', 'No assets selected');
} else {
   $asset_raw_array = Input::get('edit_asset');
   
   foreach ($asset_raw_array as $asset_id => $value) {
       $asset_ids[] = $asset_id;
   }
}
```

location here: https://github.com/snipe/snipe-it/blob/master/app/Http/Controllers/AssetsController.php#L1418-L1431

to:

```
if (!Input::has('edit_asset')) {
    return redirect()->back()->with('error', 'No assets selected');
} else {
   $asset_raw_array = Input::get('edit_asset');
   
   foreach ($asset_raw_array as $asset_id => $value) {
       $asset_ids[] = $asset_id;
   }
}
```

**Comment by Jason-Weber-UC** [comment]
BEAUTIFUL!!
THANK YOU  so much

**Comment by snipe** [comment]
No problem - glad that got you sorted.

![hackers-gunslinger](https://cloud.githubusercontent.com/assets/197404/26090732/ae557332-39bb-11e7-9ddb-f8647e250bd8.gif)

**Comment by Jason-Weber-UC** [comment]
Gotta hack the Gibson
