### ISSUE TITLE
Import - Asset Model Unknown

### ISSUE THREAD

**Issue by SALEncompass** [snipe/snipe-it#3560]
Hi, 

I'm new to snipeit so looking for some advice. 

We are using v3.6.4 build 12 on Linux. 

Actual Behavior

Trying to import assets. Have set up a file with the following columns :
Name 
Email
Username
Item Name
Category
Model Name
Manufacturer
Asset Model
Asset Tag
Location
Deployed.

When I import, it sets the asset model field to unknown and therefore I have to go in manually and edit for every Asset Model. 

Have I left a column out?

Thank you in advance. 

Salma

**Comment by snipe** [comment]
Can you check the CSV in a text edit and make sure you don't have any weird characters (or empty spaces) before or after the "Model Name" column heading?

**Comment by SALEncompass** [comment]
Thank you so much. That worked. 

You're a star!

**Comment by SALEncompass** [comment]
There was space after the heading. Never would have noticed it unless you'd mentioned to check.

**Comment by snipe** [comment]
Glad you got it sorted! 

![4110401-0707616809-tumbl](https://cloud.githubusercontent.com/assets/197404/25926952/6a55b02e-35a7-11e7-975d-5089c6e31dfb.gif)
