### ISSUE TITLE
Approver Workflow in snipe-it

### ISSUE THREAD

**Issue by nonubebo** [snipe/snipe-it#3565]
@snipe @jakemcgraw @uberbrady  ### Expected Behavior (or desired behavior if a feature request)

How we make a approver workflow means first user request for an asset then that request goes to approver/user manager for approving,after that request approved by approver then go to asset creator for asset checkout.  

-----

#### Actual Behavior

In current scenario,I am able to do user request for an asset and that request goes to asset creator for checkout

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Is the approver/manager always the same person?

**Comment by nonubebo** [comment]
@snipe Yes It always a same person

**Comment by nonubebo** [comment]
Yes approver and manager always the same person.
