### ISSUE TITLE
Inventory Email Alerting

### ISSUE THREAD

**Issue by ericdude101** [snipe/snipe-it#3568]
#### Expected Behavior (or desired behavior if a feature request)

When an item goes below the set threshold, a visual notification is displayed in the web GUI and an email alert is sent out.

-----

#### Actual Behavior

When an item goes below my set threshold, an alert is displayed in the GUI but an email is not sent out. All other email functions work fine that I know of, so not sure if this is by design for inventory alerting. There is also not errors that I can find in any error logs.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: **3.6.5**
- What OS and web server you're running Snipe-IT on: **Windows Server 2012R2, IIS 8.**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): **Manual Installation**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: **No Errors**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: **No Error**
- If a stacktrace is provided in the error, include that too: **N/A**
- Any errors that appear in your browser's error console: **No Errors**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). **Email doesnt appear to be working in demo**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. **No Errors**
- Include what you've done so far in the installation, and if you got any error messages along the way. **Verified email server settings in my .env file and email.php file, also generated new user and was able to have the credentials sent via email to test account without error**
- Indicate whether or not you've manually edited any data directly in the database **None**

**Comment by snipe** [comment]
Did you set up a cron job to send those alerts?

**Comment by snipe** [comment]
(Or whatever the windows equiv is, I forget)

**Comment by ericdude101** [comment]
Yes I have a scheduled task in place. I did notice that even if I disable the task and manually run "PHP.exe artisan schedule:run" right after I generate an alert in the GUI, the output returns "No scheduled commands are ready to run."

**Comment by ericdude101** [comment]
Its almost like the email alert isn't being created for some reason, I did verify that it is marked as enabled on the settings page with a valid email address populated.

**Comment by ericdude101** [comment]
Is there any other artisan commands I can use to test specifics?

**Comment by ericdude101** [comment]
Was able to resolve issue, will note that reports seem to go out once every day at midnight regardless of how frequently I run the "schedule:run" command.
