### ISSUE TITLE
[feature request] PDF export for reports

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#357]
Possibility using an HTML template with logo, etc.
##

**Comment by digitaltara** [comment]
I know this is marked as ready, but #1 from the comment on Nov 13, 2014 (https://github.com/snipe/snipe-it/issues/357#issuecomment-62982443) seems to be a different request, and exactly what I'm looking for. Should it be put in as a separate feature request, or is it available and I'm missing it? Thanks!

**Comment by umerafridi** [comment]
is it   possible to Export Report for single user.or any other feature similarly this

**Comment by dbierspb** [comment]
@umerafridi Not sure when this will be implemented; in the mean time I have made my own using a separate read-only user to the asset database (something for HR/Finance to pull if they need).

**Comment by snipe** [comment]
We have a print-friendly style-sheet for the user's view, so it's unlikely we'd focus on single user PDF reports any time soon.
