### ISSUE TITLE
Error 404 when trying to run the pre flight

### ISSUE THREAD

**Issue by daniel-alvarado** [snipe/snipe-it#3571]
#### Expected Behavior (or desired behavior if a feature request)

It should run the pre-flight setup.

#### Actual Behavior

It's showing a 404 error.

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
3.6.5

- What OS and web server you're running Snipe-IT on
Windows Server 2008 R2, with Apache 2.4.25

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Error 404, not found when trying to run the pre flight.

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Snipeit/public – preflight.

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
I installed Apache Server, Mysql as well as composer. Then I used the guide provided in the website. The .env file is also configured, I downloaded the resources

- Indicate whether or not you've manually edited any data directly in the database
None. Only the .env file.

This is what I have in my .env file header:

# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=true
APP_KEY=base64:XIuRBK8DUHzpM6C9ATJMM9ITeA9PJeOTt+C8S8TOyg0=
APP_URL=http://the-ip-of-my-server/snipeit/public
APP_TIMEZONE='America/Santiago'
APP_LOCALE=es-ES

# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=snipeit
DB_USERNAME=snipe_user
DB_PASSWORD=root
DB_PREFIX=null
DB_DUMP_PATH='/usr/bin'

Thanks in advance for your help.

**Comment by daniel-alvarado** [comment]
Just to clarify I have read the common issues, checked the mod_rewrite and it's working.

**Comment by snipe** [comment]
Your APP_URL is wrong. `public` should never be in the URL.

**Comment by snipe** [comment]
(Also, you'll want to regenerate your APP_KEY now that you've posted it publicly.)

**Comment by daniel-alvarado** [comment]
I didn't know about the public in the URL, thank you. I have solved the problem today, it was the mod_rewrite module, I was missing several lines in the conf file of the Apache Server. It's now working, however I'll remove the public from the URL. Thank you.
