### ISSUE TITLE
How to change limited character on state field?

### ISSUE THREAD

**Issue by penjurumedia** [snipe/snipe-it#3575]
Hello,
How to change limited character on state field? we need more than 2 character for state field http://www.awesomescreenshot.com/image/2494301/6f2e3e93c6003a8366684478834aa9a8

#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
This is fixed in the upcoming 4.0 release.

**Comment by dhayc17** [comment]
Hi - sorry to reply to this - do we know when the 4.0 release is due to come out.

I just signed up and wondering if I should hold out until 4.0 comes out before putting in our data.

Appreciate all the help !

**Comment by snipe** [comment]
@dhayc17 we're still testing 4.0, and don't want to release until it's fully tested, as I'm sure you can understand. Our users use Snipe-IT in all kinds of weird and interesting ways, so we like to give ample time to make sure we didn't miss anything. We're hoping for the next few weeks, but it depends how things go. 

Either way though, the upgrade should go pretty seamlessly, so no need to wait for 4.0 to start adding stuff.  The database migrations will take care of any database changes between versions.

**Comment by penjurumedia** [comment]
Hello thanks for your answer. 
We need some customization, do you provide services to custom? we need to add some taxonomy, for example duplicate assets module to other function (land assets, asset vehicles, stock assets, etc).
