### ISSUE TITLE
Request: Supplier not listed in overview

### ISSUE THREAD

**Issue by sdieste** [snipe/snipe-it#3576]
#### Expected Behavior (or desired behavior if a feature request)

I want to filter different suppliers but i cannot add the column (It is not displayed to me)

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: 3.6.4
-

**Comment by snipe** [comment]
On what page? A *little* more info would be helpful here.

**Comment by snipe** [comment]
If this is on the assets listing page, this is already fixed in the upcoming 4.0
