### ISSUE TITLE
Feature Request: Asset Model Inventory Tracking

### ISSUE THREAD

**Issue by ericdude101** [snipe/snipe-it#3578]
#### Expected Behavior (or desired behavior if a feature request)

Set a minimum quantity of asset devices available per model, which monitors certain device statuses such as "In-Stock" or "Ready to deploy" for counts to notify team if more devices need to be ordered for stock on hand. There could be a check box when creating a category to specify if a category represents an "Stock on hand" status.

-----

#### Actual Behavior

This functionality is only available for accessories and consumables.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: **3.6.5**
- What OS and web server you're running Snipe-IT on: **Server 2012 R2, IIS 8.5**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): **Manual Installation**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: **N/A**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: **N/A**
- If a stacktrace is provided in the error, include that too: **N/A**
- Any errors that appear in your browser's error console: **N/A**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): **Yes**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs: **N/A**
- Include what you've done so far in the installation, and if you got any error messages along the way: **N/A**
- Indicate whether or not you've manually edited any data directly in the database: **None**

**Comment by nogears** [comment]
Could you please reopen this feature request? 
It is very strange that we have this feature on consumables but not on Assets. 

Asset minimum stock alerts is an amazing feature for those who need to consistantly monitor laptop and desktop stock in diferent locations to purchase where necessary. 

Please can you implement this?

**Comment by apbutle** [comment]
+1

**Comment by Granddave** [comment]
+1
