### ISSUE TITLE
Pre-Flight "Config File" warning

### ISSUE THREAD

**Issue by arrayown** [snipe/snipe-it#3579]
#### Expected Behavior (or desired behavior if a feature request)

1. A more understandable warning.
2. A non-error visual representation. Right now it shows the content in red with an "x", which is usually used to describe an error. Maybe an orange-colored icon instead of red?

-----

#### Actual Behavior

This is shown as an error in "Config File" item:
```
Please make sure your .env. You don't ever want anyone able to see that file. Ever. Ever ever. Click here to check now (This should return a file not found or forbidden error.)
```
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: **v3.6.5 build 1 (gee2c67a)**
- What OS and web server you're running Snipe-IT on: **Ubuntu 16.04 (64-bit) + Nginx 1.12.0**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): **Manual install**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: **N/A**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: **Pre-Flight, Step 1**
- If a stacktrace is provided in the error, include that too: **N/A**
- Any errors that appear in your browser's error console: **None**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): **N/A**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs: **N/A**
- Include what you've done so far in the installation, and if you got any error messages along the way: **No other errors, this is purely cosmetic in that it looks incomplete and not informational.**
- Indicate whether or not you've manually edited any data directly in the database: **No**

**Comment by snipe** [comment]
> A more understandable warning.

The language string for "Please make sure your .env. " was (obviously) cut off.

> A non-error visual representation. Right now it shows the content in red with an "x", which is usually used to describe an error. Maybe an orange-colored icon instead of red?

A non-visual representation? I'm not sure what you mean there. It's in a red because that *is* an error. An .env file that's readable to the outside world is a huge security issue.
