### ISSUE TITLE
[Feature Request] username length to one character

### ISSUE THREAD

**Issue by ernestasen** [snipe/snipe-it#3580]
#### Expected Behavior (or desired behavior if a feature request)
Import all users from AD, even when length is one character.

-----
#### Actual Behavior
During LDAP sync I get this error message: username:  a was not imported: The username must be at least 2 characters.
Is there any workaround for that?

-----
Snipe-IT version: v3.6.2 build 18 (g6f1e0d6)
OS version: Ubuntu 16.04.2 LTS

**Comment by snipe** [comment]
This will be fixed in the upcoming v4
