### ISSUE TITLE
Locations List Blank. 

### ISSUE THREAD

**Issue by SALEncompass** [snipe/snipe-it#3588]
Snipe Version : v3.6.4 build 12 
Linux Operating system. 

I have successfully managed to upload a number of assets to snipeit. 

When I go to locations it tell me the number of assets that exist at each location. 
However, If I try to expand the location it does not bring back the associated assets that should exist at that location. 

Any advise would be really appreciated.

**Comment by ericdude101** [comment]
I just checked and i'm having the same issue. When on the list of locations each has a count, but if I click on the specific location for more details both the user section and asset section say "No matching records found."

**Comment by snipe** [comment]
Can you please tell me if going to that page triggers anything in your app logs, per the original issue template?

**Comment by snipe** [comment]
Closing for now, will reopen if you can provide more info
