### ISSUE TITLE
Feature Request: Location Dynamic Dropdown

### ISSUE THREAD

**Issue by ericdude101** [snipe/snipe-it#3589]
#### Expected Behavior (or desired behavior if a feature request)

When selecting a location for a new asset, the location would be selected from a tree of dynamic drop-down lists.

-----

#### Actual Behavior

Currently the Location drop down is a single list with out any indication as to where in the tree it is. The problem this create for me is that I have more than one same name locations such as "1st floor" depending on building or site which is not easily identifiable from the locations drop-down. Being that the parent location is already collected and defined when creating locations, I don't think it would be hard to map this to a multi level drop down tree.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running **3.6.5**
- What OS and web server you're running Snipe-IT on **Server 2012R2, IIS 8.5**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Manual Install**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). **Yes**

**Comment by ericdude101** [comment]
Is this not a viable feature request?

**Comment by snipe** [comment]
It's a valid feature request

**Comment by ericdude101** [comment]
Any updates on this?

**Comment by snipe** [comment]
No.
