### ISSUE TITLE
LDAP login with non standard filter

### ISSUE THREAD

**Issue by jstoja** [snipe/snipe-it#3592]
#### Expected Behavior (or desired behavior if a feature request)

The user should be able to connect to SnipeIT through LDAP authentication on an AD server using email address as username.

-----

#### Actual Behavior

The users are fetched correctly, both from UI and CLI, but users can't login.

Active directory checkbox is checked, using LDAPs.

LDAP Bind Username = cn=WebAuthenticator,cn=Users,cn=XXXXXXX,dc=domain,dc=local

Base Bind DN: cn=Employees,cn=Users,cn=XXXXXXX,dc=domain,dc=local
LDAP Filter: &(cn=*)
Username Field: mail
 Last Name: sn
 LDAP First Name: givenname
 LDAP Authentication query: mail=

The field sAMAccountName doesn't seem to exist on our instance and we want users to login with their email address.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.6.5-2-g5a3816c
- What OS and web server you're running Snipe-IT on
Debian Jessie
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
no error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Login page, try to login.
- If a stacktrace is provided in the error, include that too.
```
[2017-05-18 08:34:11] production.DEBUG: LDAP is enabled.
[2017-05-18 08:34:11] production.DEBUG: Binding user to LDAP.
[2017-05-18 08:34:11] production.DEBUG: LDAP user XXXXX not found in LDAP or could not bind
[2017-05-18 08:34:11] production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory
[2017-05-18 08:34:11] production.DEBUG: Authenticating user against database.
[2017-05-18 08:34:11] production.DEBUG: Local authentication failed.
```
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
Specific to Company's environment.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Login is done using usernames, because not every user has an email address associated. (We used to log people in using email addresses, but it caused problems for too many people.)

The whole point of logging in via LDAP is that the login will be the same as they're using to using elsewhere. Having an LDAP login that doesn't work the same as other LDAP logins doesn't really make sense. If your LDAP usernames are in email format, your users can login that way. We do an actual LDAP authentication attempt against your LDAP server when we try to log a user in via LDAP, so it has to match what you would use to login to LDAP.

**Comment by jstoja** [comment]
What I mean is that I specified the username field to `mail`, so the usernames are the emails. So putting the authentication query to `mail=` should work no ?
I just tried using the `cn` (which is the username) and it still doesn't work....

**Comment by snipe** [comment]
Does LDAP allow you to authenticate using an email address instead of a username? If not, then changing that to mail won't work. It's literally binding with LDAP using the username and password the user provides.

**Comment by jstoja** [comment]
Yes it does. The company has already around 10 softwares doing so.
Like I told you, I even tried to use the `cn` field and nothing seems to work...
When binding with the username, you still do it with the `Base Bind DN` right ?

**Comment by jstoja** [comment]
Hummm I think that after reading the code here: https://github.com/snipe/snipe-it/blob/e7ac860f77603c4b296a48dbff664c3d0f2ecc7e/app/Models/Ldap.php#L74
I got that the bind is actually using the username that logs in and not the `LDAP Bind Username` setting.
With some tests, it seems that the users can bind but not search on the BaseDN...
It is not related to SnipeIT, but if you have any idea why...

Anyway, thank your for answering!
