### ISSUE TITLE
Installing Snipe-IT v4 Alpha 2 in Windows

### ISSUE THREAD

**Issue by vader860** [snipe/snipe-it#3593]
I attempted a fresh install of Snipe-IT on Windows using the v4 Alpha 2 zip file and when I log into the system for the first time it does not show the version as v4.x ...

Is the alpha package linux only or should it be able to work in Windows? Thanks.

**Comment by BrettFagerlund** [comment]
I've successfully run the V4 alpha 2 file on windows, btu it does look like the alpha2 release has a old version number written into config/version.php but it is infact version 4

To confirm this, you can check under the admin menu in settings -> it should list laravel 5.4 at the bottom (version 3 would show 5.2 )

**Comment by snipe** [comment]
I'm pretty sure that's been fixed already
