### ISSUE TITLE
New install error : Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by sunilvarma72** [snipe/snipe-it#3594]
i installed snipe IT on ubuntu using install.sh
#### Expected Behavior (or desired behavior if a feature request)

----- i am not able to go to pre flight page.

#### Actual Behavior

-----when i enter the url im getting the following error

![screenshot from 2017-05-22 11-27-28](https://cloud.githubusercontent.com/assets/28032681/26291555/ab748cd6-3ee1-11e7-921b-b2fb97e54bb1.png)

#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode
- [yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
latest Version from wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04.2 Desktop & Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh
chmod 744 install.sh
./install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

![screenshot from 2017-05-22 11-27-28](https://cloud.githubusercontent.com/assets/28032681/26291561/b75bbc0e-3ee1-11e7-826b-387cd0c53812.png)

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Looks like your mysql username and/or password are not correct in your .env file

**Comment by sunilvarma72** [comment]
hey got it sorted, thank you.
