### ISSUE TITLE
V4 - Missing route import history

### ISSUE THREAD

**Issue by BrettFagerlund** [snipe/snipe-it#3600]
Version 4 -alpha2 build alpha2 (13)

Under the Assets menu ->  Import History returns route not defined error.

URL = http://snipe.local/hardware/history

**Comment by snipe** [comment]
![crying-thank-you](https://cloud.githubusercontent.com/assets/197404/26709731/b89cb07a-4709-11e7-85f8-b149b4a768cd.gif)
