### ISSUE TITLE
V4 - Depreciation Report crashes

### ISSUE THREAD

**Issue by BrettFagerlund** [snipe/snipe-it#3603]
Version v4.0-alpha2 build alpha2 (13)

Depreciation report generates error
url = snipe.local/reports/depreciation

ErrorException in ManagesLayouts.php line 84:
Cannot end a section without first starting one. (View: ...\resources\views\reports\depreciation.blade.php)

Can provide full stack if needed, but removing the extra `@stop` at the bottom of the depreciation blade fixes it

**Comment by snipe** [comment]
Fixed on dev - thanks!
![655223_thank-you-high-five-scott-disick-hand-hug-bruce-jenner](https://cloud.githubusercontent.com/assets/197404/26709694/679cac3e-4709-11e7-97cc-4df4f5569919.gif)
