### ISSUE TITLE
V4 - company page doesn't display asset tab data by default

### ISSUE THREAD

**Issue by BrettFagerlund** [snipe/snipe-it#3604]
Version v4.0-alpha2 build alpha2 (13)

When selecting a company from the company listing page, it will display the company page such as 
url - snipe.local/companies/1

The assets tab is selected in table but no data is populated, to populate the assets under that company I need to select another tab and then click back to the assets tab.

there are no errors appearing

**Comment by snipe** [comment]
Another good catch, thanks! Fixed on develop. (Develop is a little weird right now as we're trying to work through a new graph on the dashboard and fix some webpack issues.)
