### ISSUE TITLE
V4 - Locations not displaying any associated assets/users 

### ISSUE THREAD

**Issue by BrettFagerlund** [snipe/snipe-it#3606]
Version v4.0-alpha2 build alpha2 (13)

Server 2012 R2 IIS, client using chrome 59

When accessing a location with users/assets associated no data will display and message "No matching records found" appears under both users/assets, the correct location name appears as the title/header

url - snipe.local/locations/5

no errors appearing in log

**Comment by BrettFagerlund** [comment]
Yes, both users and assets assigned to that location. Under the locations list, there is both assets and assets assigned columns, assigned has a count where as assets shows 0. I may be misunderstanding what should show here, but what's the difference between the "assets" and "assets assigned" columns?

**Comment by snipe** [comment]
Assets assigned are assets that are in that location by way of inheriting their location from the user they're assigned to, versus the default location

**Comment by BrettFagerlund** [comment]
in that case the users exist in the location and assets are assigned to those users, so both counts should be equal? Data is based off single location at the moment, but neither users or assets appear in the location listing.

**Comment by dmeltzer** [comment]
#3599 fixes this, 04a2d55 in specific... I can rebase when I have some time.
