### ISSUE TITLE
LDAP-User - Password Reset functionality has not been disabled - seems to result in two passwords associated with a user

### ISSUE THREAD

**Issue by MrFishFinger** [snipe/snipe-it#3607]
version: `snipe/snipe-it:v3.6.4` (docker)

This is related to https://github.com/snipe/snipe-it/issues/1882

It seems that a password reset is possible when using an email address associated with an LDAP account (when I assume this should not be the case).

What's more, it appears that this password functionality works partially - resulting in a user account that can be logged into with 2 different passwords -> the LDAP password + the  NEW password created via the reset page. It seems that after logging in with the LDAP password once, the NEW password stops working...

steps to reproduce:

01. goto login page
02. click "I forgot my password" button
03. enter an email address that is for an LDAP account (eg firstname.lastname@domain.com)
04. Message "Success: Your password link has been sent!" is displayed
05. Email titled: "Your Password Reset Link" is received at that address
06. Open the link in browser
07. enter NEW password twice
08. password appears to have changed and we are automatically logged into SnipeIT
09. log out
11. log in, using firstname.lastname + NEW password -> success!
12. log out
13. log in, using firstname.lastname + LDAP password -> success!

**Comment by MrFishFinger** [comment]
Hi Snipe. thanks for your response.
I just checked, and i have "LDAP Password Sync" set to "Yes".

Is SnipeIT aware of which accounts are synced LDAP?
wouldn't it be more sane for Snipe-IT to prevent password-resets for accounts that it knows are LDAP-sourced? or am I missing something here?

_as an aside:_
What does Password Sync mean exactly and how is it secure? are the passwords copied/synced from LDAP and stored in the SnipeIT database? are these passwords stored in some kind of 1-way-non-reversible-hashed form or in cleartext?

**Comment by snipe** [comment]
@MrFishFinger Snipe-IT knows which users have been synced via LDAP, however when the user successfully logs in via LDAP,  if password syncing is enabled, it updates the local Snipe-IT user's password to whatever the LDAP password was. There isn't really the ability for there to be two passwords, just that the local might get out of sync with LDAP. If that happens, LDAP is considered the authority and the user can still login if they enter valid LDAP credentials. 

> What does Password Sync mean exactly and how is it secure? are the passwords copied/synced from LDAP and stored in the SnipeIT database? are these passwords stored in some kind of 1-way-non-reversible-hashed form or in cleartext?

They are of course stored in a bcrypted hash, same as normal Snipe-IT passwords are.
