### ISSUE TITLE
Ability to write plugins?

### ISSUE THREAD

**Issue by qmnonic** [snipe/snipe-it#3609]
Is there a way to write a plugin for snipe-it?  That is, a way to add features/functionality, but the code is isolated?

Matt.

**Comment by snipe** [comment]
Not yet, but switching to a plugin infrastructure us definitely something we're looking into.

**Comment by nataliiao** [comment]
Any updates on this? Is it still unavailable?

**Comment by msauto** [comment]
+1 on plugins/addons

**Comment by snipe** [comment]
Still unavailable. It's a pretty tough problem to solve.

**Comment by msauto** [comment]
Wow! That's a fast Reply! And thanks so much for what you already offer for free. I looked at asset tiger before going the route of snipe-it and i am just getting started but really happy so far. Keep up the great work PLEASE!

**Comment by grufocom** [comment]
Hi, we would like to integrate some features we used in our self programmed asset management system which will be replaced with snipe-it. We would like to query some data from our Unifi management server based on the MAC address from snipe-it assets. The easiest way would be to integrate just a link (html-get request sent to our tool) into snipe-it.
Best way would be a plugin infrastructure :-)
But until there is, any other solution would be fine - any ideas or tips on how to integrate this so we don't have problems with updates/upgrades?
Thank you for your great work!

**Comment by snipe** [comment]
@grufocom I'd suggest looking into the Snipe-IT API
