### ISSUE TITLE
Rework database migrations

### ISSUE THREAD

**Issue by balticer** [snipe/snipe-it#3610]
#### Expected Behavior (or desired behavior if a feature request)

Database migrations should working on any database systems (including MS SQL) supported by laravel.

-----

#### Actual Behavior

Currently migrations are not working on MS SQL.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
I tryed an installation of the latest version from git on Windows Server 2016 + IIS + MS SQL Server 2014 + PHP 7.1. It went well so far, but stucked at the database migration. I think this are mostly compatibility issues and they can fixed by reworking the migrations a little bit.

**An example:**
2015_02_10_040958_fix_bad_assigned_to_ids.php fails because of the line 25 to 26. MS SQL does not understand the "" string enclosures. Instead of using

`DB::statement('INSERT into ' . DB::getTablePrefix() . 'status_labels (user_id, name, deployable, pending, archived, notes) VALUES (1,"Pending",0,1,0,"These assets are not yet ready to be deployed, usually because of configuration or waiting on parts.")');`

a better approach (with laravel 5.4) should be

`DB::insert('INSERT into ' . DB::getTablePrefix() . 'status_labels (user_id, name, deployable, pending, archived, notes) VALUES (:user_id, :name, :deployable, :pending, :archived, :notes)', ['user_id' => 1, 'name' => 'Pending', 'deployable' => 0, 'pending' => 1, 'archived' => 0, 'notes' => 'These assets are not yet ready to be deployed, usually because of configuration or waiting on parts.']);`
.
/edit
With Laravel 5.2:
```
DB::table(DB::getTablePrefix() . 'status_labels)->insert(
    ['user_id' => 1, 'name' => 'Pending', 'deployable' => 0, 'pending' => 1, 'archived' => 0, 'notes' => 'These assets are not yet ready to be deployed, usually because of configuration or waiting on parts.']
);
```
What do you think? When you aggree with this, i could start working carefully on this.

regards
Kai

**Comment by snipe** [comment]
We don't have any way to test MSSQL. You're welcome to put together a pull request for it if you think you can get it to work, but it will also have to work with SQLite, since some devs use that for testing

**Comment by balticer** [comment]
Fine! I will start working on it and also I will test everything against MYSQL, SQLite and MSSQL. It will take a little bit.

**Comment by balticer** [comment]
Well, i think i cant fix it so easily as i want...pity.

**Reason:**
One of the problem is, that MSSQL needs to drop constraints (on columns) for certain operations (or use MSSQL internal stored procedures, which is not supported oob by Eloquent/DBAL). For dropping a constraint its name must be known somehow. DBALs solution is to make unique constraint names based on database/table/column etc. on creation of such. that leads into that every database change, especially defining default values, MUST be made with DBAL from the beginning of the database lifecycle. Otherwise some changes in a migration (via DBAL) will fail. In one way or another that means a change to existing databases and/or a overwhelming migration script to handle all the cases. Also for the future a developer has to make sure to not using raw queries, using the query builder everytime and think about schema changes before implementing it.

Another problem is the sql syntax in data updates, while migrating. some of the raw sql is not working against MSSQL. As an example take a "SELECT * FROM [TABLE] LIMIT 1" query. The MSSQL equivalent is "SELECT * TOP(1) FROM [TABLE]". This can be done by using the query builder for simple queries, but on complex queries...it is a mess...

Any ideas? You're welcome! For now i don't have a clue to realize it without a huge amount of work. It is not done with some small changes here and there. It need changes in the ModelFactory and then step by step in any migration script. I dont know how many, beside me, want to run snipe-it with MSSQL. But i think it is not worth to put effort in it, when only one of thousands need this.

regards
Kai

**Comment by snipe** [comment]
Yeah, there's a reason we don't support MSSQL. It's a boatload of work, and some of our queries end up being pretty complex. :(
