### ISSUE TITLE
Accents not showing up properly in database

### ISSUE THREAD

**Issue by therrienr** [snipe/snipe-it#3611]
I'm having some issues with french accents in snipe it, it allows me to insert it no problem and shows up correctly in snipe it but in the database i see

>  `&eacute;`

![image](https://cloud.githubusercontent.com/assets/19953742/26408016/b00614e2-406a-11e7-8a10-f07bc2f61c3a.png)

![image](https://cloud.githubusercontent.com/assets/19953742/26408083/da0797de-406a-11e7-98ac-56a3773517d9.png)

Have any idea what can be causing this the language setting for the snipeit database is utf8-unicode-ci

**Comment by snipe** [comment]
It's double-escaping. I believe this was fixed in the upcoming v4.
