### ISSUE TITLE
Please add Australian Dollar (AUD) to currency drop down.

### ISSUE THREAD

**Issue by ak2766** [snipe/snipe-it#3615]
#### Expected Behavior (or desired behavior if a feature request)

Expected to see Australian Dollar (AUD) in the currency dropdown when creating a location.
-----

#### Actual Behavior

There is a limited list of currencies of which the Australian Dollar (AUD) is not one of.
-----

#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v2.1.0-8

- What OS and web server you're running Snipe-IT on
Ubuntu 14.04.3 LTS

**Comment by snipe** [comment]
Please upgrade your install. We no longer use a currency dropdown, and you can instead use whatever currency symbol you need.

**Comment by ak2766** [comment]
Upgraded.  I like the new look.
