### ISSUE TITLE
Restore backup (from ZIP) to new Install.

### ISSUE THREAD

**Issue by jayromems** [snipe/snipe-it#3617]
#### Expected Behavior (or desired behavior if a feature request)

I have a prod version of Snipe-IT running but it's an old installation. Ideally I want to upgrade it without too much headeache. So, for testing purposes, I've done a new install of the current version and am attempting to do a restore from ZIP from my prod environment. I can't seem to find current documentation on how one would go about this.
Previously, it was unzip backup.zip
then copy config/  public/  storage/ to /var/www/snipeit

and then

sudo php artisan db:restore yourdumpfilename.sql

This no longer works.

-----

#### Actual Behavior

Errors, as per 
https://github.com/snipe/snipe-it/issues/2785

----

#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode
- [ yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running

Version v3.3.0-3-g7ef4f23

- What OS and web server you're running Snipe-IT on
Debian 8 + Apache

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh

**Comment by snipe** [comment]
We had to change the db backup package we were using, and the new one doesn't offer a restore option. You'll need to use something like mysqimport or PhpMyAdmin to import the old database dump.
