### ISSUE TITLE
This page can’t be displayed - After Updating

### ISSUE THREAD

**Issue by Choeoqe** [snipe/snipe-it#3619]
#### Expected Behavior (or desired behavior if a feature request)

I have tried to update my install to the latest version and seem to have killed it. I may have made an obvious mistake - I am fairly new to Linux - or overlooked something simple.

I wish I had made a note of the old version, but I am trying to update to 3.6.6. 

First I ran a yum update to get the system up to date. My update method was as follows:

wget https://github.com/snipe/snipe-it/archive/v3.6.6.zip
unzip v3.6.6.zip
rsync -avut snipe-it-3.6.6/ /var/www/html/snipeit
/var/www/html/snipeit
php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan migrate
php artisan config:clear
php artisan config:cache

-----

#### Actual Behavior

Once I had done this I just get an error of "This page can’t be displayed" in the browser. I have restarted the server.

I have looked at the common issues, and enabled debugging, but because it doesn;t seem to even connect I get nothing back. I am wondering if it is a file permissions issue, maybe because of how the new files were copied over, but I haven't been able to find anything on how the permissions should be set. 

If this seems like the problem and there is a resource someone please point me in the right direction and I will read up on it and see if I can resolve it myself!

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
3.6.6
- What OS and web server you're running Snipe-IT on
CentOS 7.3.1611
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh (I believe...)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Only the "This page cannot be displayed"
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
None
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
I can't find app/storage/logs?
- Include what you've done so far in the installation, and if you got any error messages along the way.
All as above
- Indicate whether or not you've manually edited any data directly in the database
Nope

Thanks for any help with this, I would rather not start all over again! I did do a sql backup, but not sure if that will help anything, especially as I stupidly can't remember what version I was running before...

**Comment by Choeoqe** [comment]
I have done a bit more digging and it looks like Apache isn't started...

I have no idea why it is having problems now, or why I can't start it, but this is obviously not a Snipe-IT issue so I will head over to the CentOS boards instead!

**Comment by snipe** [comment]
Heh, came here to ask if Apache was running :D Sorry you're having a hard time, but it looks like you're closer to a solution now.  Did you get it sorted?

**Comment by Choeoqe** [comment]
Thanks for checking in - yes I got Apache sorted in the end, it's been a learning experience! Now just having a problem getting back into Snipe-IT. I opened a difference thread though to avoid confusion so will pick up in there.

Thanks!
