### ISSUE TITLE
Bulk check in/out on Dashboard

### ISSUE THREAD

**Issue by jbc91** [snipe/snipe-it#3622]
# Expected Behavior (or desired behavior if a feature request)

The bulk check out feature is very useful, but it would be great if there could be a way of bulk checking in and out on the dashboard as you sign in. If multiple items come back to you at the same time you can check them all in together.

-----

#### Actual Behavior

Only seem to be able to do a bulk check out. 

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running **3.6.6**
- What OS and web server you're running Snipe-IT on **Linux cPanel 64.0** 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **via cPanel Softaculous** 
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **N/A**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **N/A**
- If a stacktrace is provided in the error, include that too. **N/A**
- Any errors that appear in your browser's error console. **N/A**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). **N/A**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. **N/A**
- Include what you've done so far in the installation, and if you got any error messages along the way. **N/A**
- Indicate whether or not you've manually edited any data directly in the database **N/A**

**Comment by snipe** [comment]
I'm not really clear on how that UI would work. Can you be more specific?

**Comment by jbc91** [comment]
It doesn't have to be on the Dashboard page, that was just a suggestion. The bulk check-out option is good, but the same for checking-in would just be useful. Whether that's a combined check-out/in page or just a separate page for checking in.

**Comment by P4R4NORM4L** [comment]
Bump
