### ISSUE TITLE
Unable to Log In after Update

### ISSUE THREAD

**Issue by Choeoqe** [snipe/snipe-it#3623]
#### Expected Behavior (or desired behavior if a feature request)

I have updated to version 3.6.6, and I am no longer able to log in. At the login page I get the "Whoops, looks like something went wrong." error straight away, and trying to login effectively just reloads the page.

I have enabled debugging but get no further information, other than that screen.

-----

#### Actual Behavior

Error: "Whoops, looks like something went wrong." on the login page, and unable to login.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
3.6.6
- What OS and web server you're running Snipe-IT on
CentOS 7.3.1611
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh I think
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Only the "Whoops" error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
The login page. Going to the forgot my password page is the same.
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
No
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
From the SnipeIT Error Log:
[authz_core:debug] [pid 2484] mod_authz_corec(809): [client <<IP>>] AH01626: authorization result of <RequireAny>: granted, referer: <<URL>>
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
No
![untitled](https://cloud.githubusercontent.com/assets/26336004/26702398/6b0b6d34-46ea-11e7-9314-b46bbf3f3b30.png)

**Comment by snipe** [comment]
> WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
>> Only the "Whoops" error

Then debug isn't turned on. Please enable debugging and/are check the app's log file

**Comment by Choeoqe** [comment]
That's what I thought, and I noticed in the help documentation it says sometimes Apache needs to be restarted after changes are made to .env but it still doesn't seem to have made any difference...

Just to confirm, within /var/www/html/snipeit I have edited the .env file to the following:

`# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=true
APP_LOCALE=en
`

I have just gone to check the logs again and I don't have a storage directory within app, so not sure if this is an issue. The log text I posted previously was from /va/log/httpd/snipeIT.error.log

**Comment by snipe** [comment]
You cleared your config cache as well?

App logs are in `storage/logs/laravel.log`

**Comment by Choeoqe** [comment]
Ah, I had done but not after changing the debug mode, thanks!

That's given me a permissions error on the login page:

ErrorException in compiled.php line 7364: file_put_contents(/var/www/html/snipeit/storage/framework/sessions/219acc2b9c8cae559a08fa8b07ed1b9b9743e628): failed to open stream: Permission denied

although as I mentioned I don't have a storage directory in that location. I tried creating one and setting permissions but that hasn't helped.

**Comment by Choeoqe** [comment]
Ignore the above, I was looking in the wrong place, for storage in app, not in snipeit!

Found the sessions folder, changed the permissions and all is working.

Thanks for the pointers in the right direction!
