### ISSUE TITLE
PDOException Error

### ISSUE THREAD

**Issue by DRIFTER016** [snipe/snipe-it#3625]
Working on install and config and after much work (new to this sort of thing) have managed to get the app running. But am not able to get past an error on the home directory when connecting to the site.
I have added the laravel log detailing the issue below. Any insight you could provide on rectifying this problem would be much appreciated.

Thanks in advance
Dave

#### Expected Behavior (Connect To Site)

(Open Pre-Flight Web Page)

-----

#### Actual Behavior

(Whoops, looks like something went wrong)

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 3.6.6
- What OS and web server you're running Snipe-IT on Windows Server 2012 R2 on IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual 
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error NA
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error Main Page
- If a stacktrace is provided in the error, include that too.  See Below
- Any errors that appear in your browser's error console. NA
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database  NO

Laravel Log
I hashed out the password in #0.
As a quick question, where does it pick up the DB connection information as I think this may be the issue.

[2017-06-02 15:04:46] production.ERROR: PDOException: could not find driver in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:55
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(55): PDO->__construct('mysql:host=loca...', 'root', '########', Array)
#1 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(11845): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#4 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(924): call_user_func(Object(Closure))
#5 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(792): Illuminate\Database\Connection->getPdo()
#6 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(677): Illuminate\Database\Connection->reconnectIfMissingConnection()
#7 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php(349): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
#8 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Schema\MySqlBuilder.php(21): Illuminate\Database\Connection->select('select * from i...', Array)
#9 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(6325): Illuminate\Database\Schema\MySqlBuilder->hasTable('users')
#10 C:\inetpub\wwwroot\snipe-it\app\Models\Setting.php(65): Illuminate\Support\Facades\Facade::__callStatic('hasTable', Array)
#11 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckForSetup.php(22): App\Models\Setting::setupCompleted()
#12 [internal function]: App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 [internal function]: App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\XssProtectHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#24 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 [internal function]: App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#29 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13474): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#34 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(11964): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#39 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 C:\inetpub\wwwroot\snipe-it\vendor\misterphilip\maintenance-mode\src\MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode.php(145): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#44 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#48 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#49 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#50 C:\inetpub\wwwroot\snipe-it\public\index.php(59): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#51 {main}

**Comment by snipe** [comment]
That usually means you're missing the PHP PDO extention

https://snipe-it.readme.io/docs/requirements
http://php.net/manual/en/pdo.installation.php

**Comment by DRIFTER016** [comment]
Yup, missed a couple in there.
It's getting closer but now I get two errors.
At least it's now trying to redirect me to the setup page.

Here's the latest from the log.

[2017-06-05 14:38:39] production.ERROR: ErrorException: Function mcrypt_get_iv_size() is deprecated in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Encryption\McryptEncrypter.php:46
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Encryption\McryptEncrypter.php(46): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8192, 'Function mcrypt...', 'C:\\inetpub\\wwwr...', 46, Array)
#1 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(7769): Illuminate\Encryption\McryptEncrypter->__construct('\x9E\x86\xC4\x85\x05\xF1\x83\xCA\xA9\xF7\xF2q&\t"...', 'rijndael-256')
#2 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(7761): Illuminate\Encryption\EncryptionServiceProvider->getEncrypterForKeyAndCipher('\x9E\x86\xC4\x85\x05\xF1\x83\xCA\xA9\xF7\xF2q&\t"...', 'rijndael-256')
#3 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1353): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#4 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1309): Illuminate\Container\Container->build(Object(Closure), Array)
#5 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1874): Illuminate\Container\Container->make('encrypter', Array)
#6 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1410): Illuminate\Foundation\Application->make('encrypter')
#7 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1387): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#8 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1373): Illuminate\Container\Container->getDependencies(Array, Array)
#9 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1309): Illuminate\Container\Container->build('App\\Http\\Middle...', Array)
#10 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1874): Illuminate\Container\Container->make('App\\Http\\Middle...', Array)
#11 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9958): Illuminate\Foundation\Application->make('App\\Http\\Middle...')
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8226): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8217): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#18 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(8207): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#19 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(2419): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#21 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 [internal function]: App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 C:\inetpub\wwwroot\snipe-it\vendor\fideloper\proxy\src\TrustProxies.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#30 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\CheckForSetup.php(35): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 [internal function]: App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#35 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#40 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#42 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\XssProtectHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#45 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#47 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#50 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#52 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(13474): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#55 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#57 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(11964): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#58 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#60 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#62 C:\inetpub\wwwroot\snipe-it\vendor\misterphilip\maintenance-mode\src\MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode.php(145): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 [internal function]: MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#65 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#67 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#68 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#69 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#70 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#71 C:\inetpub\wwwroot\snipe-it\public\index.php(59): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#72 {main}  
[2017-06-05 14:38:39] production.ERROR: ErrorException: Function mcrypt_get_iv_size() is deprecated in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Encryption\McryptEncrypter.php:46
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Encryption\McryptEncrypter.php(46): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8192, 'Function mcrypt...', 'C:\\inetpub\\wwwr...', 46, Array)
#1 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(7769): Illuminate\Encryption\McryptEncrypter->__construct('\x9E\x86\xC4\x85\x05\xF1\x83\xCA\xA9\xF7\xF2q&\t"...', 'rijndael-256')
#2 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(7761): Illuminate\Encryption\EncryptionServiceProvider->getEncrypterForKeyAndCipher('\x9E\x86\xC4\x85\x05\xF1\x83\xCA\xA9\xF7\xF2q&\t"...', 'rijndael-256')
#3 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1353): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#4 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1309): Illuminate\Container\Container->build(Object(Closure), Array)
#5 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1874): Illuminate\Container\Container->make('encrypter', Array)
#6 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1410): Illuminate\Foundation\Application->make('encrypter')
#7 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1387): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#8 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1373): Illuminate\Container\Container->getDependencies(Array, Array)
#9 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1309): Illuminate\Container\Container->build('App\\Http\\Middle...', Array)
#10 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(1874): Illuminate\Container\Container->make('App\\Http\\Middle...', Array)
#11 C:\inetpub\wwwroot\snipe-it\bootstrap\cache\compiled.php(2373): Illuminate\Foundation\Application->make('App\\Http\\Middle...')
#12 C:\inetpub\wwwroot\snipe-it\public\index.php(64): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#13 {main}

**Comment by Neltharionx** [comment]
He/she closed so nobody gonna look at it and your problem is not solve. He did the same to me.
