### ISSUE TITLE
How to put Snipe-IT with another Web Project in one WampServer?

### ISSUE THREAD

**Issue by purnadika** [snipe/snipe-it#3627]
I've followed all tutorial about installing Snipe-IT and it succeed. Snipe-IT program run well with my computer name in address bar.
But, how can I access it from network? (if it using my pc name, but i can access it if it changed to my ip address)
I have another web project in Wamp server and access it like "http://192.168.0.2/anotherProject".
And now I want to run Snipe-IT like another projects do. ie : "http://192.168.0.2/snipeit"
How?
Thanks
![tes](https://cloud.githubusercontent.com/assets/9426610/26770303/9bbbc68e-49df-11e7-9277-93b9e7d799f4.jpg)
![tes2](https://cloud.githubusercontent.com/assets/9426610/26770304/a06fa8a8-49df-11e7-8203-b5d94441568f.jpg)

**Comment by dualfever** [comment]
I am currently using XAMMP, but I assume Wamp would work the same.
You could use the vhosts file, here I've found this article:
https://john-dugan.com/wamp-vhost-setup/
