### ISSUE TITLE
Windows 2012 PreFlight Create DB Table Issue

### ISSUE THREAD

**Issue by meitalan** [snipe/snipe-it#3629]
#### Expected Behavior (or desired behavior if a feature request)
When clicking on button create database tables nothing occur.
we have confirmed that db settings on .env file are ok.
(what you expect to happen goes here)

-----

#### Actual Behavior
I have checked in MySQL client to query db tables and it is empty.
(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [v ] I have enabled debug mode
- [ v] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - last available version
- What OS and web server you're running Snipe-IT on - windows server 2012R2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Try running migrations manually - `php artisan migrate`. Check the error log to see if there are any errors logged.
