### ISSUE TITLE
Unaccepted Reports results incomplete view

### ISSUE THREAD

**Issue by mfahmi37** [snipe/snipe-it#3630]
#### Expected Behavior (or desired behavior if a feature request)

When I clicked REPORTS>UNACCEPTED ASSETS, the page seems incomplete, please refer attachment

-----
![unaccepted-asset](https://cloud.githubusercontent.com/assets/25362203/26811422/53028980-4aa4-11e7-9059-1dcc99489620.jpg)

#### Actual Behavior

REPORT result should be exportable not incomplete page.

-----

Please confirm you have done the following before posting your bug report:

[ YES ] I have enabled debug mode YES
[ YES] I have read checked the Common Issues page YES
Please provide answers to these questions before posting your bug report:

Version of Snipe-IT you're running
3.6.3
What OS and web server you're running Snipe-IT on
Centos 6
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
If a stacktrace is provided in the error, include that too.
Any errors that appear in your browser's error console.
Confirm whether the error is reproduceable on the demo.
Include any additional information you can find in app/storage/logs and your webserver's logs.
Include what you've done so far in the installation, and if you got any error messages along the way.
Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Please turn debugging on, or provide a stack trace from your logs, per the initial Github issue template. Something on that page is crashing, which is why it looks incomplete, but we can't tell you what that might be without a stacktrace.

**Comment by mfahmi37** [comment]
Sorry, please refer debugged mode log below.

##from browser
FatalErrorException in 6f8502deb6c7fc8ea5a45b5cfa89aece9d046d54.php line 47:
Call to a member function fullName() on null

##from laravel.log
[2017-06-06 12:54:34] production.DEBUG: Authenticating user against database.
[2017-06-06 12:54:39] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function fullName() on null' in /usr/local/apache2425/htdocs/snipeit/storage/framework/views/6f8502deb6c7fc8ea5a45b5cfa89aece9d046d54.php:47
Stack trace:

**Comment by snipe** [comment]
Is it possible you have a user that didn't accept their asset and has since been deleted?

**Comment by mfahmi37** [comment]
yes since the users haven't clicked the acceptance link yet.. this is to monitor which users haven't clicked yet.

**Comment by snipe** [comment]
Of course, but is it possible one of those users was deleted?

**Comment by mfahmi37** [comment]
By right no user should be deleted. 
Does it cause the prob? 


Regards,
Muhamad Fahmi Aya
