### ISSUE TITLE
Edit check out mail template

### ISSUE THREAD

**Issue by midhunpmj** [snipe/snipe-it#3631]
When an item is checked out in snipe-it, the check out mail is shown as below.
![capture](https://cloud.githubusercontent.com/assets/29221910/26815762/cf05d616-4aab-11e7-9967-deec767a942f.JPG)

Instead of the current values like "Asset Name, Asset Tag, etc..", I want to display "Model, category etc.". How can I achieve this? I want to know the location of files to be edited.

**Comment by snipe** [comment]
@midhunpmj `resources/views/emails`

**Comment by itsenaf** [comment]
Changing the files at this location don't work.
I edited the accept-asset.blade.php heavy and the Mail looks like the same.

Any ideas?

**Comment by haupt-pascal** [comment]
Is there a new way to change it? There's no "views/emails" path in version 5. 

:)

**Comment by maelkira** [comment]
@haupt-pascal , they seem to be moved to resources/views/notifications/markdown/
anyone can confirm? thank you!

**Comment by szega07** [comment]
We've found a file that we could modify if we want to add Category. (see below)
c:\wamp64\www\snipe-it\resources\views\notifications\markdown\checkout-asset.blade.php
Can you help us if it's that how to add Category variable?
