### ISSUE TITLE
No Alerting email for import records through CSV file

### ISSUE THREAD

**Issue by chetanarora3** [snipe/snipe-it#3632]
#### Expected Behavior (or desired behavior if a feature request)
Alerting for import records through CSV file are not getting generated. Although they are showing fine asset records

#### Actual Behavior
It just show the alerting for the records which are added through GUI. Record added by duplicating the import record through GUI also shows alerting

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode No
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)Yes

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running Version v3.4
- What OS and web server you're running Snipe-IT on RedHat 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Not Known
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error NA
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error NA
- If a stacktrace is provided in the error, include that too. NA
- Any errors that appear in your browser's error console. NA
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). 
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
What do you mean by "no alerting"?

**Comment by chetanarora3** [comment]
By alerting i mean warranty expiring alerts which we have set for 5 mins interval for testing for assets for which warranty is getting expired in a month. We imported two records and added one through GUI keeping parameters like 'Purchase Date' and 'Warranty Months' similar but we are getting email notification only for the asset which is added through GUI. Imported records are showing up perfectly fine in asset table as well as in reporting with all the parameters matching up fine but alerting is something which is not happening with them. Can you please suggest what could be the issue here?

**Comment by snipe** [comment]
That doesn’t really make sense though. The system can’t tell the difference between an asset created through the importer or an asset created through the GUI. Can you check that the dates imported correctly, and that depreciation is set on the asset model?

**Comment by chetanarora3** [comment]
We are actually not using Depreciation field and it is still giving the warranty expiring alerts for the GUI one. Purchase date as well as warranty are set similar for the all the records: one imported through csv and and that of GUI. Below is the backup taken in JSON for all the entries which are showing similar for your reference.
{"header":[["Company","Asset Tag","Manufacturer","Model","Model No.","Serial","Status","Purchased","Cost","Order Number","Supplier","Checked Out","Location"]],"data":[{"Company":"MMT","Asset Tag":"RTR-Tata-Delhi","Manufacturer":"Cisco","Model":"1921","Model No.":"","Serial":"","Status":"Available","Purchased":"2017-05-16","Cost":"INR 111.00","Order Number":"","Supplier":"DiData","Checked Out":"","Location":"Delhi Rajouri"},{"Company":"MMT","Asset Tag":"RTR-Bharti-Delhi","Manufacturer":"Cisco","Model":"1921","Model No.":"","Serial":"FGL1521207Z","Status":"Available","Purchased":"2017-05-16","Cost":"INR 111.00","Order Number":"","Supplier":"DiData","Checked Out":"","Location":"Delhi Rajouri"},{"Company":"MMT","Asset Tag":"MMT-SW-Delhi","Manufacturer":"Cisco","Model":"WS-C2960S-48TC-L","Model No.":"","Serial":"FOC1128ZBLS","Status":"Available","Purchased":"2017-05-23","Cost":"INR 222.00","Order Number":"","Supplier":"DiData","Checked Out":"","Location":"Delhi Rajouri"}]}

**Comment by arvage** [comment]
We do have the same issue only with imported assets and all the manually added ones through GUI are working fine and alerts are going out.
Unfortunately, I opened another issue request before finding this one.
[https://github.com/snipe/snipe-it/issues/3817](https://github.com/snipe/snipe-it/issues/3817
)

**Comment by arvage** [comment]
I found the issue. all you need is to go to your DB and assets table. then set the archived value to 0 for all the imported assets. it was showing NULL on mine and alert got fixed when updated the values to 0

MySQL Query:
UPDATE assets SET archived = 0 WHERE archived IS NULL

**Comment by chetanarora3** [comment]
Thank you Armin! It worked for me too. Did you find any way through which this value can be fixed in the system itself so that not all imported records need go to through the same treatment?

**Comment by snipe** [comment]
This is fixed in v4

**Comment by chetanarora3** [comment]
Thank you!!
