### ISSUE TITLE
How to Edit a custom field list box

### ISSUE THREAD

**Issue by korio77** [snipe/snipe-it#3633]
Good afternoon,

I created in the past a listbox custom field with some options, now, i need to add a new option to that list, but i cant find where should i do it.

Is there any way to do this in the snipe IT interface or should i do it by hand in the database?( i know its not good to touch directly the database)

Currently im using the SnipeIT version: v3.6.2 build 10 (g927a12f)

I have deleted all the other preset question because this is not a bug report itself, just a simple question.

If you need any more info just let me now.

**Comment by snipe** [comment]
Editing custom fields isn't available in 3.6.2, but will be available in the upcoming v4.

**Comment by wwke** [comment]
i can't update the custom field listbox with the version (v7.0.2 build 13978), 
![image](https://github.com/user-attachments/assets/8d5d86be-dfc9-499c-af0d-90a04656da71)
