### ISSUE TITLE
Issues with artisan file on IIS

### ISSUE THREAD

**Issue by tekk45** [snipe/snipe-it#3635]
#### Expected Behavior (or desired behavior if a feature request)

Successful completion of "composer install" and "php artisan key:generate"

I've been unable to get to the "pre-flight" page as of yet.

-----

#### Actual Behavior

When I run "composer install" I receive the error:
![image](https://user-images.githubusercontent.com/25079656/26837163-b946b1f2-4aaa-11e7-9edb-cb9c92a4df36.png)
Line 3 being: `define('LARAVEL_START', microtime(true));`

If I comment out line 3 composer runs until it calls artisan, at which point artisan memory leaks until close. 
![image](https://user-images.githubusercontent.com/25079656/26837471-7c990b14-4aab-11e7-92fa-6c4a261e35f1.png)
So now the dependencies are installed, because composer has run until failing at calling artisan.

I've tried other commands calling artisan, they all memory leak until close.
![image](https://user-images.githubusercontent.com/25079656/26839305-9e828e4e-4ab0-11e7-9d53-b1fad5903a97.png)

I've looked through some other issue reports and have looked in Notepad++ and Atom.IO but haven't seen any syntax errors such as wrong quotes, extra spaces, etc.

I've tried reinstalling PHP and re-importing the snipe it files to no avail. I'm using PHP v7.0.15 as installed by the Web Platform Installer.

I'm able to successfully launch phpinfo.php and see the installed dependencies.

-----

#### Please confirm you have done the following before posting your bug report:

- [y] I have enabled debug mode
- [y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
**I saw the memory related common issue, recommending to increase the allocated memory to 256M or 512M, but I've seen no change in the symptom and have allocated up to 3G of memory via php.ini. It just takes longer before leaking until close.**

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running; **v3.6.6**
- What OS and web server you're running Snipe-IT on; **Win Server 2012R2, IIS 8.5**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc); **Manual**
... N/A ...
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.; **None in storage\logs and nothing I find helpful in IIS logs. The application hasn't been actually launched before. If there's something specific you want to see let me know.**
- Include what you've done so far in the installation, and if you got any error messages along the way.; **I've followed the windows installation guide, step by step, and re-read over them again several times. I was initially just getting the composer error until I commented line 3. Though I'm unsure if commenting line 3 is what's causing the artisan memory leak.**
- Indicate whether or not you've manually edited any data directly in the database; **no**

**Comment by snipe** [comment]
The laravel_start error probably doesn't matter, since it's just a notice level, not an actual error level notification, though you may want to change your PHP error reporting level to ERROR instead of notice or warning.

I'm not sure what `php artisan app:install` is supposed to do? Are you maybe looking at older documentation?

**Comment by tekk45** [comment]
> laravel_start error
It repeats indefinitely until I ctrl+C terminate it, never moving to the rest of the installation. So, before commenting it out it would never install.

> looking at older documentation
You're probably right. I spent the better part of a day and a half digging through countless bug reports looking for something similar. My intent with that was to show that more than one thing, not just what was being called by composer, was leaking. Things I definitely will need eventually also do too, such as: migrate, config:clear, and config:cache.
![image](https://user-images.githubusercontent.com/25079656/26929432-b2852bfe-4c27-11e7-95a2-2eae7cee0f4d.png)

**Comment by snipe** [comment]
> It repeats indefinitely until I ctrl+C terminate it, never moving to the rest of the installation. So, before commenting it out it would never install.

Right, so change your PHP error reporting level to ERROR and increase PHP's memory alllocation

**Comment by tekk45** [comment]
Logged this:
![image](https://user-images.githubusercontent.com/25079656/26978340-35457b62-4cf9-11e7-8f7f-0bd5d9e3ae15.png)
Line 35 in autoload.php was a blank line; deleted it.

Re-ran `composer install` and got "post-install-cmd event returned with error code 255". Found a thread on laracasts ([https://laracasts.com/discuss/channels/general-discussion/composer-update-script-php-artisan-clear-compiled-handling-the-pre-update-cmd-event-returned-with-an-error?page=2](url) directing to update composer.

Ran `composer update --no-scripts`
![image](https://user-images.githubusercontent.com/25079656/26978578-fe631e82-4cf9-11e7-9f87-b2cc4141b77f.png)
Went to php.ini and uncommented `extension=php_gd2.dll`

Ran `composer dump-autoload -o` then re-ran `composer update --no-scripts` no error this time.
Ran `composer install` again with 'memory_limit = 1G' and it's now pointing to line 34 in autoload.
![image](https://user-images.githubusercontent.com/25079656/26978978-5308a618-4cfb-11e7-8ee9-92e4c517a3d5.png)
There are no extra spaces or anything after the bracket, so I'm not sure from here...

Re-ran again with `memory_limit = 3G` and it got to 2.9G used in task manager then timed out.
![image](https://user-images.githubusercontent.com/25079656/26979441-c3e1376e-4cfc-11e7-83a7-c03e4f318708.png)
There is no log event correlating to the timeout.

**Comment by tekk45** [comment]
Also tried uncommenting `define('LARAVEL_START', microtime(true));` again after doing the things I've done today and still got the same endless wall of LARAVEL_START notices.
