### ISSUE TITLE
Failed to open page , Server unexpectedly dropped connection

### ISSUE THREAD

**Issue by evoviiisean** [snipe/snipe-it#3643]
#### Expected Behavior (or desired behavior if a feature request)

Access to SnipeIT database via webbroswer
-----

#### Actual Behavior

Unable to connect.

-----

#### Please confirm you have done the following before posting your bug report:

- [ Not sure how ] I have enabled debug mode
- [ X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
Not exactly sure.  Installed 4-5 Months ago.
- What OS and web server you're running Snipe-IT on
Ubuntu 14.05 Server
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Main Page / Dashboard / Login
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
Checked to ensure Apache was running. 
Checked IP
- Indicate whether or not you've manually edited any data directly in the database

The server has been running flawlessly for months now.  Last Friday we did some server room upgrades which required the system be taken offline shortly.  It was put back up and no errors on reboot.  Apache was restarted, However, I am now unable to connect to SnipeIT at all.  Just says "Failed to open page.  The server unexpectedly dropped the connection."  Not overly knowledgable on how the backend of this program works.  It is however an amazingly useful program and has made my life here lightyears easier.  Hopefully can get this resolved quickly.

**Comment by snipe** [comment]
That doesn't sound like anything to do with Snipe-IT though, that's a server-level issue. Have you tried clearing your browser cookies, trying another browser, etc? Otherwise the only thing I can think of is maybe a change to DNS/Firewall/etc is causing the issue.

**Comment by evoviiisean** [comment]
Thanks for the reply.  I agree, but really out of ideas at this point.  Was hoping maybe was something that has been seen before.  

I know there have been no changes to the firewall or network setup.  The network was only taken down to install new UPS.  Nothing was even un-cabled aside from the power.  All systems were cleanly shutdown.  I was actually using the database about 30min prior entering in the UPS information into assets.

I have also tried from (4) different machines (3 OS's - W7/Server2012/OSX) as well as Edge, IE, Firefox, Chrome, Safari to access the database.  Also can confirm I have tried clearing cookies as well. No luck.  

Im pretty sure its something really simple im overlooking at this point thinking its a deeper root cause.

Just to confirm, Once the system is retarted, and Apache is started, there should be nothing else that needs to be done in terms of starting services for Snipe correct?  Not sure I have had to bring the server down since it was put up.  So double checking im not forgetting anything there. 

Thank you for your help and the great program!

**Comment by snipe** [comment]
Apache and MySQL will both need to be running for the system to work.

**Comment by evoviiisean** [comment]
Thanks for your help.  Nailed it with network related.  Despite _ifconfig_ showing the correct IP,  The box was , for whatever reason, not the right IP.  Ended up just having to re-configure the network settings for the right IP.  Why that changed by removing power is beyond me.  Even tried to replicate the issue, with no luck.

All is well now.  Back up and running.  

Thank you again.

**Comment by snipe** [comment]
![13815199381780222131](https://user-images.githubusercontent.com/197404/27099447-d50bcd8e-502f-11e7-9622-40e90e99b2ab.gif)
