### ISSUE TITLE
Export only works once

### ISSUE THREAD

**Issue by ebonweaver** [snipe/snipe-it#3645]
#### Expected Behavior (or desired behavior if a feature request)

You could export as many times as you want

#### Actual Behavior

You can only export once (Assets), then it does nothing until you close the page and reopen it.  You can't even reload the site to make it work, but at least you don't have to close the browser, just the tab with snipe.

#### Please provide answers to these questions before posting your bug report:

Snipe 3.6.2 on Ubuntu 14, installed with install.sh, updated manually
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
Yes, confirmed in demo

**Comment by dvkesarwani** [comment]
even i m getting the same issue
