### ISSUE TITLE
Import really does not work

### ISSUE THREAD

**Issue by ebonweaver** [snipe/snipe-it#3646]
### Expected Behavior (or desired behavior if a feature request)

Everything in the CSV is imported as it appears in the CSV, and as per the documentation

#### Actual Behavior

Almost nothing is imported.
Serial is not imported
Asset Name is not imported
No custom field is imported
No models are created
All assets are imported with the manufacturer of the first row instead of the one listed in their row
Even if these things DID import, given custom fields are attached to sets, and sets are attached to models, and there is nothing in the import to handle linking of sets, that means even if it made the models it wouldn't import all the custom data as the new model has no way to be linked at import to a set.
In the end, import is not at all helpful as it can't actually do anything.

I even confirmed this by:
purge all assets
make a new one with all info filled in, of model desired, etc
Export, so I have a csv that has all the headers and all the fields of that item
delete that asset
Import the exported file
Just as mentioned above, most of the data is ignored, it fails to link to the model properly (which in this case even existed before import given these steps...), so this would seem to show that import is pretty much broken.

#### Please provide answers to these questions before posting your bug report:

- version 3.6.2, Ubuntu 14, Apache, installed with install.sh
- No errors, this is all results based
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
I would have to create dummy data to attempt this, so I have not tried
- Indicate whether or not you've manually edited any data directly in the database
No

**Comment by ebonweaver** [comment]
Just tried to reproduce in demo, but it's disabled there so can't.

**Comment by ebonweaver** [comment]
It appears that this is largely a bug in the export giving bad headers.  The following headers in export need to be fixed so they are accurate:
Asset Name changed to Item Name
Serial changed to Serial Number
Model changed to Model Name
Model No. changed to Model Number
This is important to ensure easy data in and out without having to manipulate the default headers.  Also, since an export is the primary way to get an import template, the headers kinda need to be correct to avoid exactly this issue.

I'm still not seeing a way to have models created on asset import with a fieldset attached to them.  Adding a Fieldset column to the import did not work.  This again is important to not have to manually edit dozens of models after import.  It does seem however that the initial impression that fieldsets added custom fields to asset records (and therefore all the custom data did not import) was wrong.  It appears that all custom fields exist for all assets, and you can see them in the list view in those columns, you just can't edit them in the asset record.  So fieldsets are actually a mask apparently that reveals hidden fields?  Perhaps a good bit of clarity to add to the documentation so it's understood how things operate, and even more important that there be an option for setting a fieldset on a newly created model on import.

**Comment by snipe** [comment]
Import absolutely does work, but you have to use the correct headers, as mentioned in the documentation. https://snipe-it.readme.io/docs/importing

**Comment by snipe** [comment]
> I'm still not seeing a way to have models created on asset import with a fieldset attached to them. Adding a Fieldset column to the import did not work.

This is not currently possible, however bulk editing models will hopefully be in an upcoming release.

**Comment by ebonweaver** [comment]
Can you explain why you don't think this is a bug or at least something that can be made better instead of being disregarded?  I'm not understanding why you wouldn't make the export headers correct to match what is needed for import.  The mismatch seems to be (really it is) a functional issue, and basically a couple typos that should be easy to correct.

Additionally, the feature request of adding fieldset as an import column for assets seems to make a lot of sense.  However, if that is programmatically difficult due to the relations of the tables, and therefore the bulk edit of models is the desired compensation, I can understand that.

**Comment by shivu01** [comment]
Import option is working fine from the csv file, but company_id and location_id is not working
