### ISSUE TITLE
the variable "codename" not asigned before use in snipeit.sh

### ISSUE THREAD

**Issue by gohilurvish** [snipe/snipe-it#3649]
#### Expected Behavior (or desired behavior if a feature request)

The following should be run in the file `snipeit.sh` along with fetching `distro` and `version`.
`codename="$(lsb_release -c -s)"`

-----

#### Actual Behavior

variable `codename `is not at all assigned any value

-----

#### Please confirm you have done the following before posting your bug report:

- [No ] I have enabled debug mode
- [ Yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running : 3.6.6
- What OS and web server you're running Snipe-IT on : Ubuntu 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) : install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error : Installation issue
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error : Installation issue
- If a stacktrace is provided in the error, include that too. : No
- Any errors that appear in your browser's error console. : No
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). : No
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. : No
- Include what you've done so far in the installation, and if you got any error messages along the way. : Yes
- Indicate whether or not you've manually edited any data directly in the database : No

**Comment by othyn** [comment]
Thank you, I can confirm I am also having this issue on Ubuntu 16.04 LTS clean AWS instance.

**Comment by gohilurvish** [comment]
That was quick guys. Thanks.
I see there are some other issues/needed improvements in `snipeit.sh` script.
Shall I report all under one or separate each one?
