### ISSUE TITLE
V4 - Assign Users to Groups

### ISSUE THREAD

**Issue by VanillaNinjaD** [snipe/snipe-it#3652]
I cant figure out how to add a user to a group since my upgrade to v4

I have checked the "people" area and selected the user to edit but cant find anything there. I also cant find a way through the "groups" area either.

I know I have to be missing something stupid simple 🤦‍

OS: Ubuntu Server 16.04 LTS
Apache: 2.4.18 (Ubuntu)
Snipe-IT: v4.0-latest develop
PHP: 7.0.18-0ubuntu0.16.04.1
Laravel: 5.4.20

Install Method: Manually upgraded since 2.1.0-pre

**Comment by snipe** [comment]
Fixed - thanks!

**Comment by wallacengene** [comment]
Please help me wit this I don't understand where or how to run the script..
