### ISSUE TITLE
Asset Tag autoincrement stopped working after update to 3.6.6

### ISSUE THREAD

**Issue by aglasson** [snipe/snipe-it#3657]
#### Expected Behavior (or desired behavior if a feature request)

The next available asset tag number should be entered in the asset tag field on any create or clone windows. https://serveraddress/hardware/create or https://serveraddress/hardware/298/clone.
000298 is the latest asset tag number so 000299 should be the automatically populated asset tag.

-----

#### Actual Behavior

The asset tag 000001 is always populated in the asset tag field. If I turn off the auto increment setting no asset tag is populated at all. It is working just not producing the correct number.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

## **Important:**
There is another issue open similar but I do not think it applies.
https://github.com/snipe/snipe-it/issues/3203

Snipe writes:
> I'm pretty sure many of these problems are due to inconsistent asset tag lengths in the database.

However all our asset tags are the same length at 6 digits, no prefixes or variations on the tagging scheme have ever been applied. If I look through the full list of tags in the asset list they all have a the same format sequentially incrementing tags.
This issue did not exist before updating to 3.6.6 from I think 3.6.3?

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
  - v3.6.6 build 1 (gee2c67a) previously running (I think) 3.6.3 with no issues.
- What OS and web server you're running Snipe-IT on
  - CentOS, Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  - install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
  - No error and it seems to be trying to get the correct value but I'm guessing the wrong value is returned?
Image of the debug mode query:
![image](https://user-images.githubusercontent.com/11340849/27027137-92ae4a8e-4fa3-11e7-8c20-192f854edbb3.png)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
  - https://serveraddress/hardware/create or https://serveraddress/hardware/298/clone
- If a stacktrace is provided in the error, include that too.
  - No errors identified
- Any errors that appear in your browser's error console.
  - No errors identified
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
  - Issue not present in demo. Demo version is older.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
  - Only some backup error logs regarding file or directory not found.
- Include what you've done so far in the installation, and if you got any error messages along the way.
  - Turned on/off the increment asset tag option. Restarted HTTPD. Looked for errors. Searched for known issues or similar in github.
- Indicate whether or not you've manually edited any data directly in the database
  - Definitely not.

**Comment by VanillaNinjaD** [comment]
https://github.com/snipe/snipe-it/issues/3203

**Comment by aglasson** [comment]
Hi Team
Can you review my section "Important" that I discussed why I think #3203 is not related. I'm pretty sure I was last on 3.2.3 and I had no issues with this.
