### ISSUE TITLE
Some links are hard-coded so break use with apache proxypass frontend

### ISSUE THREAD

**Issue by pynixadm** [snipe/snipe-it#3659]
#### Expected Behavior (or desired behavior if a feature request)

We are running this in docker containers with apache working as a proxy to port 80:32769 with vhosts (as there are multiple apps running in docker here). Most of the application works like a dream. 

-----

#### Actual Behavior

Most of the links within the application work fine, but some (like dashboard and view user profile from users page) seem to be hard-coded links directly to <ip>:32769 where others direct properly to the url cname we are using (inventory.domain/admin, etc)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
**Unneeded as this isn't really an error report, nor would there be errors logged?**

- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
**v3.6.6 build 1 (gee2c67a)**

- What OS and web server you're running Snipe-IT on
**Docker on CentOS 7 with instructions from install page. Apache with extremely basic proxypass/reverse to internal port**

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
**direct from [docker  install](https://snipe-it.readme.io/docs/docker) page**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
**Noted above, dashboard link from any page, and user profile access from users adm page**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
**none**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
**As far as I know this setup is unique and wouldn't be reproducible**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
**basic install, ldap sync to group, apache proxypass front-end**
- Indicate whether or not you've manually edited any data directly in the database
**nope**

**Comment by snipe** [comment]
I believe all of these issues are fixed in the upcoming v4
