### ISSUE TITLE
[feature request] file upload, notes for accessories,parts etc

### ISSUE THREAD

**Issue by samatkiss** [snipe/snipe-it#3661]
It would be very good if i could attach file and write note to every type of stuff. There are specifications in different file formats for accessories and for others what is very important.

Thanks

**Comment by osa-ko** [comment]
+1 Absolutely agree. Every item type may have some remarks to it, having no custom fields and no notes makes it impossible to track such remarks.

**Comment by jszaszvari** [comment]
+1 

Need to upload a scan of the invoices when we purchase accessories 

@snipe Any chance this is in the works?

**Comment by mtausig** [comment]
I would vote to reopen this issue. Notes for accessories and consumables would be very welcome in my opinion.
