### ISSUE TITLE
Error While Save on admin Configuration

### ISSUE THREAD

**Issue by eduardjazz** [snipe/snipe-it#3662]
Hi, 

Need some help. I got some error while trying to save on admin settiing. here is the view of error :

![screenshot-asset esta co id-2017-06-13-14-19-54](https://user-images.githubusercontent.com/29395696/27070500-7ba45e28-5043-11e7-80c7-054c4baffbda.png)

i didn't do anything change, only trying to save but still got this error. i just want to change this language to indonesia and view a barcode but not success.

Anyway, Thank you Snipe IT for this awesome Apps

#### Expected Behavior (or desired behavior if a feature request)

Can Configure on admin, change anything and save it successfully

-----

#### Actual Behavior

Show Error and nothing change while save configuration admin.

-----

#### Please confirm you have done the following before posting your bug report:

- [Y] I have enabled debug mode
- [Y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version v3.6.6 build 1 (gee2c67a)
- CENTOS 7 and web server you're running Snipe-IT on
- Install.sh

**Comment by snipe** [comment]
Is this reproducible on the demo?

**Comment by eduardjazz** [comment]
No, everything fine when i test it on demo version

**Comment by HinchK** [comment]
Any chance you switched branches to develop?  ImageUploadRequest doesn't exist in 3.6.6 ... can you do a `git status` from the snipe-it directory?

**Comment by eduardjazz** [comment]
I dont know how to switched branches to develop. can you show me?
