### ISSUE TITLE
Editing Fieldsets

### ISSUE THREAD

**Issue by jmochnick** [snipe/snipe-it#3664]
#### Expected Behavior (or desired behavior if a feature request)

We should be able to edit fieldsets. 

-----

#### Actual Behavior

There is no option to edit fieldsets. If we need to change what fields are available to a model, we have to create a new fieldset and erase all of the data the asset contains.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- v3.6.4 build 12 (gf7e4fca)
- RHEL 6.7, Apache
- install.sh

**Comment by snipe** [comment]
This is already handled in the upcoming v4
