### ISSUE TITLE
Bug Report: Create Asset Error Tag Asset

### ISSUE THREAD

**Issue by penjurumedia** [snipe/snipe-it#3669]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:
When we creating asset and We get an error that asset tags must be unique, whereas previously there is no such data. At the time of the error, the data remains in the database.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by penjurumedia** [comment]
Hi, 
Version of Snipe-IT you're running
**v3.6.6 build 1 (gee2c67a)**

What OS and web server you're running Snipe-IT on
**CentOS with Litespeed Webserver + cpanel**

What method you used to install Snipe-IT
**Using softaculous**

If you're getting an error in your browser, include that error
**Data stored, but still appears notification error tag asset must be unique**

What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
**snipeit.domain.com/public/hardware/create**

Confirm whether the error is reproduceable on the demo.
**No, demo work properly**

**Comment by penjurumedia** [comment]
I don't know why when I try to click submit button on create asset page, still getting error **"Error: Please check the form below for errors"** but my data have been stored into database. Screenshot error https://www.awesomescreenshot.com/image/2583974/76d576681025a0bd3de1cfbdbd8e9456

**Comment by HinchK** [comment]
From your picture the validation error is saying "The Asset Tag must be unique."

**Comment by penjurumedia** [comment]
I can make sure before there is no data with the asset tags, but after submitting for the first time immediately appear the error. And I check, the data is indeed stored. Why the first time submit an error occurred? It's like a double action when saving.
