### ISSUE TITLE
database/app mismatch? errors on login

### ISSUE THREAD

**Issue by sheikhyerbouti** [snipe/snipe-it#3672]
#### Expected Behavior (or desired behavior if a feature request)

Expect the application to log me in.

-----

#### Actual Behavior

login page loads > enter credentials > get a whoops something went wrong.  Debug on and its a mysql query error.

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'min_amt' in 'where clause' (SQL: select * from `consumables` where `min_amt` is not null and `consumables`.`deleted_at` is null) (View: /var/www/snipe-it-master/resources/views/layouts/default.blade.php) (View: /var/www/snipe-it-master/resources/views/layouts/default.blade.php)

The consumables table doesn't have a min_amt column.

select * from consumables;
+----+--------------------+-------------+-------------+---------+-----+-------------+---------------------+---------------------+------------+
| id | name               | category_id | location_id | user_id | qty | requestable | created_at          | updated_at          | deleted_at |
+----+--------------------+-------------+-------------+---------+-----+-------------+---------------------+---------------------+------------+

-----

#### Please confirm you have done the following before posting your bug report:

- [ *] I have enabled debug mode
- [* ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - 'app_version' => 'v3.6.6', 'build_version' => '1',
- What OS and web server you're running Snipe-IT on - Ubuntu 14.04LTS and apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - see above
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - vendor/laravel/framework/src/Illuminate/Database/Connection.php
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). No
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.  I had snipe installed on a different debian system.  I want to move it to a new box.  I took a mysql database dump and a copy of the www snipe directory.  I ran install.sh from the snipe directory and once completed restored the database.  
- Indicate whether or not you've manually edited any data directly in the database - Not yet

**Comment by sheikhyerbouti** [comment]
"php artisan migrate" had to be run to update the database.  The original version was v2.
So it looks like a newer version of the application was installed but upgrade process not followed.

https://snipe-it.readme.io/v3.6.2/docs/upgrading-to-v3

**Comment by snipe** [comment]
Glad you got it sorted :)
