### ISSUE TITLE
Slow application load times

### ISSUE THREAD

**Issue by amNavertech** [snipe/snipe-it#3673]
#### Expected Behavior (or desired behavior if a feature request)

Expected/Desired, application should be more responsive than what it is, ie. without the sleep/wait times after login.

-----

#### Actual Behavior

The page takes a while to load. (note the table items per page is set to 10). Here is some additional information.

Tried these commands to resolve the situation:
php artisan cache:clear
php artisan config:clear
php artisan view:clear
php artisan optimize --force
composer dump-autoload –optimize

DB is – mysql  Ver 15.1 Distrib 10.1.24-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Additional information:
There appears to be a sleep…
![sleep](https://user-images.githubusercontent.com/29454118/27178805-9b9d54a6-51c3-11e7-9b9d-06028012d625.png)

However the speed of the database queries remain speedy. However the overall duration is high.
![breakdown](https://user-images.githubusercontent.com/29454118/27178838-be09a1d4-51c3-11e7-896d-5bbd4bd50877.JPG)
![summary](https://user-images.githubusercontent.com/29454118/27178837-be073c3c-51c3-11e7-8c36-0277acf867d7.JPG)

While using a laravel debug bar, I’ve noticed that, Application (34.46s). That's an average but it can go up to a minute plus. It doesn’t matter what page you are on, past logging in

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

Version of Snipe-IT you're running. (If you didn't grab an official release, let us know which branch you pulled from.) - 3.3.0-3-g7ef4f23 (Laravel 5.2.43) grabbed from the official release channel

What OS and web server you're running Snipe-IT on - Debian 8.8 (Jessie), Apache/2.4.10, PHP 7.0.19-1\~dotdeb+8.1 with Zend Engine v3.0.0 with with Zend OPcache v7.0.19-1~dotdeb+8.1 also tried PHP 5.6.30-0+deb8u1 with Zend Engine v2.6.0 with Zend OPcache v7.0.6-dev. Nginx used to sit in front of Apache but I removed it to see if it was the issue.

What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual

If you're getting an error in your browser, include that error. - None

What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error. - Everything but the login page

If a stacktrace is provided in the error, include that too. – N/A

Any errors that appear in your browser's error console. – None

Confirm whether the error is reproduceable on the demo. – N/A

Include any additional information you can find in storage/logs and your webserver's logs. – N/A

Include what you've done so far in the installation, and if you got any error messages along the way. – N/A

Indicate whether or not you've manually edited any data directly in the database. – No

**Comment by HinchK** [comment]
Is this running on a Virtual Machine?  If so what are the specs on it (i.e. how much cpu, RAM is allocated to it) and what type of VM (hyper-v, vitrualbox, etc.) is it?

**Comment by amNavertech** [comment]
It's running on a VPS just hosting only Snipe IT.
Virtualsation is KVM
4 vCPUs
4GB RAM
75GB SSD

**Comment by HinchK** [comment]
OK - thanks for that!  How about if you disable debug mode?  Any noticeable performance change?

**Comment by amNavertech** [comment]
No performance change.

**Comment by snipe** [comment]
Can your instance retrieve scripts from the outside world? Does disabling remote scripts in the Admin > Settings help?

**Comment by amNavertech** [comment]
Disabling the remote scripts doesn't help.

**Comment by snipe** [comment]
Honestly not sure then. We run hundreds of instances of Snipe-IT and haven’t run into speed issues. Are you running xdebug or anything memory heavy like that?

**Comment by amNavertech** [comment]
Nope not using that, just to mention the slowness started to happen before any debugging was put into place. There appears to be a sleep occurring, not sure if that's anything to go off of, view screenshot in the brief.

**Comment by vinkeljern** [comment]
I have the same issue. Looks like "css?family=source.." hangs for 12 sek. I've tested with enableing and disableing "Remote Scripts" - and there is no difference.

I'm running 3.6.6 build 1 (gee2c67a) on a "dark net" / offline network

**Comment by dmeltzer** [comment]
This is the googlefonts issue, fixed in 4.0.  See #3230 .

**Comment by amNavertech** [comment]
While this issue was related it still hasn't completely solved our problem. While it is similar in symptom there seems to be something else. Anything else worth trying?

Note: Removed all the google fonts and their css references.
