### ISSUE TITLE
custom_fields, accessories, consumables, components creates a http 500

### ISSUE THREAD

**Issue by jenmesh** [snipe/snipe-it#3675]
#### Expected Behavior (or desired behavior if a feature request)

The custom_fields, accessories, consumables, components pages to open

-----

#### Actual Behavior

HTTP 500 page cannot be displayed

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode : Yes however no information displayed
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 3.6.6
- What OS and web server you're running Snipe-IT on Windows Server 2012 R2 / IIS 7.0
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manuel
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error opening the page causes the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). NO
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Please provide your app and webserver error logs, per the issue template.

**Comment by jenmesh** [comment]
[laravel.txt](https://github.com/snipe/snipe-it/files/1082237/laravel.txt)
This is the only file  in my /storage/logs directory

**Comment by jenmesh** [comment]
Here are the IIS logs

[u_ex170615.txt](https://github.com/snipe/snipe-it/files/1082247/u_ex170615.txt)
[u_ex170616.txt](https://github.com/snipe/snipe-it/files/1082248/u_ex170616.txt)
[u_ex170617.txt](https://github.com/snipe/snipe-it/files/1082249/u_ex170617.txt)

**Comment by snipe** [comment]
I can't tell what from this log is relevant to your current issue. Please turn on debugging and tell us what the stack trace is on the screen when you try to access those pages.

**Comment by jenmesh** [comment]
I did turn on debugging (image attached) I don't get any information, just the 500 error
![2017_06_17_06_20_55_10 10 7 46_remote_desktop_connection](https://user-images.githubusercontent.com/29467020/27252174-5f272d0e-5325-11e7-83fb-fc5db2d872a1.png)

**Comment by jenmesh** [comment]
I am really stuck. I have kept searching, I am having no luck getting Debug to show data. Most of the other screens work, is it possible my URL Rewrite is not working? Does anyone know how to test.
I am new at this and am asking for any assitance

![url_rewrite](https://user-images.githubusercontent.com/29467020/27256871-526d4370-5391-11e7-83e8-59b94c1af7e5.png)

**Comment by snipe** [comment]
Have you had any luck with this?
