### ISSUE TITLE
All assets viewed in deployed status

### ISSUE THREAD

**Issue by mmoz77** [snipe/snipe-it#3678]
#### Expected Behavior (or desired behavior if a feature request)
When I view the assets list I'm expecting that the deployed ones are shown as deployed, the undeployable as undeployable and so on...
-----

#### Actual Behavior

any asset is shown as deployed independently by his status

-----

#### Please confirm you have done the following before posting your bug report:

- [YES ] I have enabled debug mode
- [YES] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
Version v3.6.6 build 1
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04, Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
git + this guide https://hostpresto.com/community/tutorials/how-to-install-snipe-it-on-ubuntu-16-04/
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No error

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
Yes, I inserted a new item in demo and changed his status from deployed to broken, but the list shows always the deployed status

**Comment by tbradsha** [comment]
Is the asset assigned to someone? If the status label is of type "deployable", and the asset is assigned to someone, it will be listed as "deployed". This is the expected behaviour. See also feature request #4538.
