### ISSUE TITLE
Status Label chart color

### ISSUE THREAD

**Issue by mmoz77** [snipe/snipe-it#3679]
#### Expected Behavior (or desired behavior if a feature request)
I expect to visualize status label chart color in the asset list, or in a field, or as a color line
(what you expect to happen goes here)

-----

#### Actual Behavior

Chart color is not shown in any case

-----

#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode
- [yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
Version of Snipe-IT you're running
Version v3.6.6 build 1

What OS and web server you're running Snipe-IT on
Ubuntu 16.04, Apache

What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
git + this guide https://hostpresto.com/community/tutorials/how-to-install-snipe-it-on-ubuntu-16-04/

WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No error

**Comment by snipe** [comment]
> I expect to visualize status label chart color in the asset list, or in a field, or as a color line

Not sure what you're asking for here - can you clarify?
