### ISSUE TITLE
Bulk License Checkout

### ISSUE THREAD

**Issue by AzureusNation** [snipe/snipe-it#3680]
Feature Request:

We have over 2000 desktops/laptops and want to put our volume licensing keys on here so we can keep track of seats. Going to be a lengthy job assigning 2000 windows 10 licenses and 2000 office licensed...

This is similar to issue #588 but instead of assets its for licenses instead. I cant see this being a big job... maybe it is I don't know but bulk checkout of licenses would be a HUGE help for it admins like myself.

**Comment by hamzab900** [comment]
We would love this too, checking out an Office/Windows license to each user is a lengthy redundant process that can easily be solved if there was a csv import option for checking out licenses to users/assets

**Comment by sk33z3r** [comment]
Would love to open this one back up. I'm doing an initial import from an old system to Snipe IT, and having to individually checkout licenses to each user is not something I have the bandwidth for.

**Comment by snipe** [comment]
How would you see this working?

**Comment by sk33z3r** [comment]
Silly, I should have posted up a use case initially.

My particular use case:
- Company A, runs on O365, ~400 users
- Company B, runs on GSuite (we acquired someone), ~200 users
- License for O365 with 400 seats
- License for GSuite with 200 seats

I know that all users that have an email address domain of companya.com need to have an O365 license checked out, and all users with companyb.com need a GSuite license checked out. The process to do this would be something like:

1. Go to **People**
2. Sort by email (or search for companya.com)
3. Select all people in companya.com
4. Choose **Bulk License Checkout** from the drop-down in top-left
5. It allows me to choose an existing license from the list

When I choose O365 and hit go, I would expect the system to enumerate the license seats, and assign empty seats to each user I have selected. Naturally skipping over seats that are already taken, users that already have the license, and possibly an error message if you run out of seats.

This goes hand in hand with the other feature request I commented on (#4925). Our HR department wants to keep track of not only the asset cost per user, but also the monthly license cost. Having to checkout the licenses individually (which I've already done, took a few hours) is a major pain. I'm sure future users would appreciate an easier solution.

**Comment by Joshuaharry120** [comment]
Is still a thing? - i really need it on my end.

**Comment by jbewing-bzam** [comment]
Definitely would be interested in this.

**Comment by syoung-quizlet** [comment]
plus 1

**Comment by syoung-quizlet** [comment]
Anyone have any success with the universal importer for this?

**Comment by klaveczky** [comment]
I think we have been left behind fellas. I'd need a bulk checkout licenses function too, but seems like we aren't getting one anytime soon

**Comment by snipe** [comment]
@klaveczky Seriously? You took time out of your day to write this, thinking either that it will somehow propel your cause forward or just to be obnoxious. 

We have been pushing code non-stop. Sometimes this means your features can’t be accomplished until we do other things to lay a better foundation on which we can grow.

If you think we’re taking too long, open a PR or keep your passive aggressive bullshit to yourself.

**Comment by klaveczky** [comment]
Yea sure, I took time out of my day to write it, just as you did to respond.
I spent half of yesterday writing code to convert data into your proprietary format, so I can import licenses WITH their users, just to find out, that even if you format it correctly, it won't import users anyway.
So it think I'm understandably frustrated.

This feature is not complicated to implement at all, so your second paragraph is bullshit in it's entirety, and you know it too.

At least you replied to me, not like the other people, who asked questions in a polite manner, so seems like you are more comfortable communicating when you get butthurt, so I'd recommend my method to others, asshole.

**Comment by snipe** [comment]
> Yea sure, I took time out of my day to write it, just as you did to respond.

It's... uhh... my job to.

> I spent half of yesterday writing code to convert data into your proprietary format

I don't think that word means what you think it means. 

And you want to talk to me about time spent? I've been maintaining this project for 7 years, building new features all the time for people like you, who seem to want to spend more time complaining than helping. 

> This feature is not complicated to implement at all, so your second paragraph is bullshit in it's entirety, and you know it too.

Complicated isn't the issue - there are literally hundreds upon hundreds of other feature requests and bugfixes in the queue. If you'd like to fix it to get this ahead of the queue, I welcome your PR. 

> At least you replied to me, not like the other people, who asked questions in a polite manner, 

We get a lot of feature requests - while I try to be responsive, real life doesn't always allow for that.

> so seems like you are more comfortable communicating when you get butthurt, 

So you admit you were being a jerk then? Great! That's an excellent place to start. Acknowledging a problem is the first step to fixing it. 

> so I'd recommend my method to others, asshole.

You must be great fun at parties. 

It's the sense of entitlement that I responded to. It's not making me work on it any faster - again, because we have higher priority issues right now, not out of spite for you personally. 

It's not appropriate for you to call any maintainer of any open source software (or any software at all for that matter) an asshole when they call you out for being a jerk. It *is* appropriate for you to reconsider how you speak to people who spend a lot of time building something they give away for free.

**Comment by snipe** [comment]
@N0odlez - FYI, I *think* we already implemented this (if I'm understanding the question correctly) a while back, just not though the UI. Check out the https://github.com/snipe/snipe-it/blob/master/app/Console/Commands/CheckoutLicenseToAllUsers.php console command. 

The web UI version is still on the list, but probably won't be handled in the next minor version or two.

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it">snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - snipe/snipe-it</div></blockquote>

**Comment by AmberHarding** [comment]
Good morning!! Any idea on the ETA for this feature on web UI?

**Comment by snipe** [comment]
Nope.

**Comment by AmberHarding** [comment]
> Nope.

Thanks!

**Comment by the-original-jellytree** [comment]
I am also looking for some work on bulk checking in and out assets. The current bulk license procedure does not cover the use case for things like Server CAL's. For example, we have 150  CAL to assign to one server. The way it works now is that I have to manually assign each license 150 times to the same device.  My poor carpel tunnel!  Plus doing it all over again when needing to remove the CAL's from the device.  And this is just one of our servers. It would be nice to have a way to allocate X number of licenses to a device (or user, I guess) in one shot. Thanks for reading and considering this request!
