### ISSUE TITLE
V4 - Bulk Delete Does Nothing

### ISSUE THREAD

**Issue by VanillaNinjaD** [snipe/snipe-it#3681]
#### Expected Behavior (or desired behavior if a feature request)

A bulk of assets to be deleted

-----

#### Actual Behavior

No items are deleted and a message comes across the top of the asset screen that says

" Info: admin/hardware/message.delete.nothing_updated "

![2017-06-20 14_59_43-all assets __ inventory manager](https://user-images.githubusercontent.com/7405702/27353355-53beb652-55c9-11e7-9f8f-ec7e3f1ba6c9.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

OS: Ubuntu Server 16.04 LTS
Apache: 2.4.18 (Ubuntu)
Snipe-IT: v4.0-latest develop
PHP: 7.0.18-0ubuntu0.16.04.1
Laravel: 5.4.20

Install Method: Manually upgraded since 2.1.0-pre

**Comment by snipe** [comment]
Thanks! Should be fixed on develop now
