### ISSUE TITLE
Getting D'oh .. DocumentRoot error despite changing the Apache settings

### ISSUE THREAD

**Issue by kojaq** [snipe/snipe-it#3684]
#### Expected Behavior (or desired behavior if a feature request)
After trying the installation on a set of VirtualBox virtual machines Lubuntu 17.04/ Ubuntu Server 16.04/ CentOS 7 using the install.sh script from [here](https://snipe-it.readme.io/docs/downloading#section-3-download-the-installer) and using default recommended installation values I was able to complete the installation. 
Edited the snipeit.conf in Apache / Httpd (CentOS) to make sure it's pointing to the /snipeit/public/ as per documentation.
Opening a browser on a different PC and navigating to the http://<the_IP_of_the_VM> and/or http://<the_IP_of_the_VM>/snipeit

-----

#### Actual Behavior
After error-free installation it's time to open Snipe-IT in a browser to complete the pre-flight setup.
Opening a browser on a different PC and navigating to the http://<the_IP_of_the_VM> and/or http://<the_IP_of_the_VM>/snipeit (and also Opening a browser on a different PC and navigating to the http://<the_IP_of_the_VM> and/or http://<the_IP_of_the_VM>/snipeit/index.php) and any variation of thereof results in either getting the D'oh DocumentRoot error or http 500 - empty response (when I add the /index.php at the end).

-----

#### Please confirm you have done the following before posting your bug report:

- [ x ] I have enabled debug mode
- [ x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
Whatever is the one installed by script on 21/06/2017
Presume 3.6.5
- What OS and web server you're running Snipe-IT on 
Tried multiple VirtualBox VMs:
CentOS 7 / httpd
Ubuntu Server 17.04 / Apache2
Lubuntu 17.04 / Apache 2
All systems were deployed with automatic install/default settings to increase compatibility.

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh, as per instructions from https://snipe-it.readme.io/docs/downloading#section-3-download-the-installer
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
n/a, can't open the snipeit website at all
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Trying to open the pre-flight page, literally first page to open after installation.
- If a stacktrace is provided in the error, include that too.
n/a
- Any errors that appear in your browser's error console.
n/a
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
Not reproducable, as the demo is already installed and configured.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
Deployed a vanilla installation of SnipeIT uising the scripted install with install.sh from the official documentation, googled for solutions on both project github, spiceworks, and a few attached blogs. 
Amended the Apache/httpd configuration to try both having SnipeIT as a standalone website running on the server (editing the 000-default.conf), and to have it as a subpage/subfolder http://<whatever>/snipeit (editing both the 000-default.conf and snipeit.conf) all without luck. Either document root error or http500 error. 
- Indicate whether or not you've manually edited any data directly in the database
I didn't touch the database

**Comment by kojaq** [comment]
Nothing? Not even a single line?

**Comment by snipe** [comment]
> Nothing? Not even a single line?

A single line of what?

Did you restart apache after you edited the conf file? If you're going to run Snipe-IT in a subdirectory, [you need to configure it appropriately](https://snipe-it.readme.io/docs/subdirectories) - it really wants to be top level or subdomain.

**Comment by kojaq** [comment]
Followed both variants. 
vanilla centOS 7 + installation from script => no go
subdirectory configuration as per guide on the same system => no go

What am I missing? Plenty of people have reported back that the scripted install on CentOS worked pretty much out of the box.

**Comment by kojaq** [comment]
Installed again, this time manually installing and configuring all components - getting error 500
