### ISSUE TITLE
V4 - Opening Locations from Asset History View has Wrong URL

### ISSUE THREAD

**Issue by VanillaNinjaD** [snipe/snipe-it#3685]
#### Expected Behavior (or desired behavior if a feature request)

STEPS TO REPRODUCE

1. Check out an item to a Location
2. Open the Asset
3. Switch to the History Tab
4. Click on "Target -> Location"

it should open the "View by Location" screen

https://snipe-it-url/locations/1

![2017-06-22 12_08_48-view asset 2081 __ inventory manager](https://user-images.githubusercontent.com/7405702/27446740-4438c57a-5744-11e7-848f-7c12ef71985b.png)

-----

#### Actual Behavior

Sad Panda and URL is missing "locations" between the slashes

https://snipe-it-url//1

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

-----
OS: Ubuntu Server 16.04 LTS
Apache: 2.4.18 (Ubuntu)
Snipe-IT: v4.0-latest develop
PHP: 7.0.18-0ubuntu0.16.04.1
Laravel: 5.4.20

Install Method: Manually upgraded since 2.1.0-pre

**Comment by dmeltzer** [comment]
This specific bug is fixed with #3923.  One thing I notice while testing it though is that we currently don't show on the location page a list of items checked out to that location.  I wonder how to differentiate between items that "live" in that location and items checked out to it--or if we should?
