### ISSUE TITLE
V4 - Clone Option Missing??

### ISSUE THREAD

**Issue by VanillaNinjaD** [snipe/snipe-it#3688]
#### Expected Behavior (or desired behavior if a feature request)

Clone option be available. Maybe I've managed to screw up some permissions?

Not even my Super Admins can see the option

-----

#### Actual Behavior

Clone option missing in V4?

![2017-06-22 12_30_57-all assets __ inventory manager](https://user-images.githubusercontent.com/7405702/27447490-bd3a55ae-5746-11e7-83d4-4f6958af08dd.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

OS: Ubuntu Server 16.04 LTS
Apache: 2.4.18 (Ubuntu)
Snipe-IT: v4.0-latest develop
PHP: 7.0.18-0ubuntu0.16.04.1
Laravel: 5.4.20

Install Method: Manually upgraded since 2.1.0-pre

**Comment by snipe** [comment]
What page are you looking at?

**Comment by VanillaNinjaD** [comment]
The main assets screen

https://URL/hardware

**Comment by VanillaNinjaD** [comment]
That's IF my memory serves me correctly. It's not sitting right in front of me.

**Comment by snipe** [comment]
Should be fixed on develop now - thanks!
