### ISSUE TITLE
Error decrypting values after restoring backup in different server

### ISSUE THREAD

**Issue by ernestasen** [snipe/snipe-it#3690]
#### Expected Behavior (or desired behavior if a feature request)

Restore database and files on another server and still be able to access decrypted values.

-----

#### Actual Behavior

Decryption Error: MAC is invalid.

What exactly needs to be done so I can restore from backup on another system? Maybe I need to backup something additionaly or I need to skip some parts of installation?

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.6.6 build 1 (gee2c67a)
- What OS and web server you're running Snipe-IT on: Debian 8
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: no errors in debug, only in the encrypted value field.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Asset page.
- If a stacktrace is provided in the error, include that too. - n/a
- Any errors that appear in your browser's error console. - n/a
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). - no, because it always sits in the same server.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. - I have tried changing new app key to the old one, but this didn't help. 
- Indicate whether or not you've manually edited any data directly in the database - not edited
[laravel.log.zip](https://github.com/snipe/snipe-it/files/1097060/laravel.log.zip)

**Comment by snipe** [comment]
You need to make sure your APP_KEY is the same in the new server as on the old.
