### ISSUE TITLE
Admin unable to view encrypted custom field data.

### ISSUE THREAD

**Issue by dkmansion** [snipe/snipe-it#3693]
#### Expected Behavior (or desired behavior if a feature request)
**"Admin" should be able to view encrypted custom field data.**

-----

#### Actual Behavior

**See Pad lock and only a tool tip stating** 
![image](https://user-images.githubusercontent.com/5826629/27497320-d906c40c-580e-11e7-93dd-208430ca5516.png)

-----
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode **No as no "error" is occurring**
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT **3.6.3**
- What OS and web server **RHEL 7 / Apache 2.4**
- What method you used to install Snipe-IT **install.sh**
- WITH DEBUG TURNED ON, - **No error**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error   - **Asset View  Details, and Asset All list with column visible**
![image](https://user-images.githubusercontent.com/5826629/27497381-26f2092e-580f-11e7-8af7-9142827538d6.png)

**What permissions are needed to satisfy the "Admin" requirement.  User account testing has Super User, and Admin set to GRANT.**
![image](https://user-images.githubusercontent.com/5826629/27497420-60f66dcc-580f-11e7-94a9-da85968ff028.png)

Thanks for reviewing.  I was unable to identify any other issues in the tracker specific to this item.

**Comment by snipe** [comment]
Is this only happening on the listing page, or on the asset details page as well?

**Comment by dkmansion** [comment]
Both.  If I drill into the asset details we also only see the padlock regardless of permissions.  Sorry I only included the one screen shot from the listing.

**Comment by snipe** [comment]
I'm not sure if that's something we may have already fixed. Can you try upgrading to the latest stable?

**Comment by dkmansion** [comment]
Hi I was able to get around to pulling 3.6.6.  This is fixed there.

I see this as a "non-admin"
![image](https://user-images.githubusercontent.com/5826629/28287930-5067d5a4-6af2-11e7-8f27-fe5cc49d0a3c.png)

and this as an "admin"
![image](https://user-images.githubusercontent.com/5826629/28287965-70cdee28-6af2-11e7-888d-e1d97d05aa03.png)
