### ISSUE TITLE
What is the .env URL value?

### ISSUE THREAD

**Issue by el-ahrairah** [snipe/snipe-it#3695]
The installation instructions say:

APP_URL

This is the url to your application, beginning with http:// or https:// (if you're running Snipe-IT over SSL). Images and javascript will not load correctly if this is not set to EXACTLY the URL you access your Snipe-IT app from.

Does anyone have an example of how I determine what this is?  I'm guessing it has to be hooked up with something inside my apache server, but I don't know where to do that.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
3.6.6
- What OS and web server you're running Snipe-IT on
Ubuntu server 16, apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
downloaded .gz file
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
It would be the IP address or domain name that you use to access the Snipe-IT application. `http://localhost`, `http://assets.mydomain.com`, etc.

**Comment by logeshr413** [comment]
If I have a custom port should I add it in the URL like http://assets.mydomain.com:10443
