### ISSUE TITLE
issue on Document root

### ISSUE THREAD

**Issue by kajal-alpha** [snipe/snipe-it#3698]
i have complete the setup following link: https://snipe-it.readme.io/docs/wamp
but it gives 

> D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory.

--> http.conf like as

<virtualHost *:80>
<Directory "C:/wamp/www/snipe-it/public/">
	Allow From All
	AllowOverride All
	Options +Indexes
	Require all granted
</Directory>
	DocumentRoot "C:/wamp/www/snipe-it/public/"
	ServerName "http://localhost/snipe-it"
</virtualHost>

what is solution for this ?

**Comment by snipe** [comment]
Snipe-IT really doesn't want to be run in a sub-directory, but if you're going to do that, you have to set it up that way: https://snipe-it.readme.io/docs/subdirectories

**Comment by ooteron** [comment]
I know this is an old issue but... In my case I don't have access to the httpd.conf file because I am using a shared hosting server. Is there a way to achieve this only via the .htaccess file?

**Comment by msghani** [comment]
Is there any simple or easy solution to migrate snipe-IT one shared server to another shared hosting server.....

Regards,
Sohail
