### ISSUE TITLE
Request optional LDAP Bind Username

### ISSUE THREAD

**Issue by hmmmonteiro** [snipe/snipe-it#3699]
#### Expected Behavior (or desired behavior if a feature request)

Application should not require LDAP Bind Username to work. You shouldn't need any special user binding to allow authenticating users using LDAP's binding mechanism. Only if there is sensitive/private information in the users' ldap entry, that you don't wish to disclosure, then you should use the LDAP Bind Username, but it should be optional.

-----

#### Actual Behavior

The application expects the definition of an LDAP user with high privilege read access.

-----

#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Snipe-IT version 3.6.6
- Debian Jessie 8.6
- installation using install.sh

**Comment by snipe** [comment]
The application uses the LDAP Bind Username only to search the directory for syncing. It does not use it for authenticating users.
