### ISSUE TITLE
Search doesn't accept &, needs to be &amp;

### ISSUE THREAD

**Issue by LupusUmbrae** [snipe/snipe-it#3702]
#### Expected Behavior (or desired behavior if a feature request)

Search for `Office Home & Business` and get a listing of those licenses

-----

#### Actual Behavior

No results

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: 

      v3.6.4
- What OS and web server you're running Snipe-IT on: 

      Ubuntu (16.04.2 LTS), via installer script (Apache 2 I believe)
- What method you used to install Snipe-IT (install.sh)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: 

      /admin/licenses Search bar
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). 

      Yes. Created a license called `A & B`, then did a search for `A & B` 
      nothing showed up until I changed it to `A &amp; B`
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database. No

**Comment by snipe** [comment]
Can you check in the database to see whether it's stored as `&` or `&amp;`?
