### ISSUE TITLE
Custom fixed EOL on Asset model

### ISSUE THREAD

**Issue by NiklasNord** [snipe/snipe-it#3703]
#### Expected Behavior (or desired behavior if a feature request)

I would like to set a fixed custom date as EOL on an Asset model.
For example, when managing Chromebooks that have a fixed EOL date ([Dell Chromebook 3120 February 2020 - 2020-02-01](https://support.google.com/chrome/a/answer/6220366?hl=en)) I would like to set this for all devices.

-----

#### Actual Behavior

EOL is calculated by setting a # of months in the field 'EOL' which is added to the value 'Purchase date' for each asset belongin to that asset model.

-----

**Comment by NiklasNord** [comment]
@snipe 
Any chance this can be considered? :)

**Comment by Forusim** [comment]
At the current state, I don´t see the purpose of EOL, when you have warranty covering the months from purchase date.
If EOL would be a fixed date, this could be used to prohibit to request a model or to create an asset with that model.
What do you think about this?

**Comment by NiklasNord** [comment]
> At the current state, I don´t see the purpose of EOL, when you have warranty covering the months from purchase date.
> If EOL would be a fixed date, this could be used to prohibit to request a model or to create an asset with that model.
> What do you think about this?

The problem for me is that purchase date is dynamic and changes from batch to batch and machine to machine and EOL is fixed from Googles side. I could fake a fixed purchase date for all machines of the same model and set EOL by months but then I wouldn't be able to use the pyrchase date to identify machines bought in the same batch.

**Comment by rcmcdonald91** [comment]
@NiklasNord how are you currently handling Google EOL for Chrome devices?

**Comment by NiklasNord** [comment]
> @NiklasNord how are you currently handling Google EOL for Chrome devices?

@theonemcdonald Not in Snipe-IT. Sorting devices on manufacturer and model and comparing with the official AUE https://support.google.com/chrome/a/answer/6220366?hl=en

<blockquote><div><strong><a href="https://support.google.com/chrome/a/answer/6220366?hl=en">Auto Update policy - Google Chrome Enterprise Help</a></strong></div><div>Overview
Chrome devices (e.g. Chromebook, Chromebox, Chromebase, Chromebit) receive automatic updates that enhance both the device and its software. Device updates provide the latest features and kee</div></blockquote>
