### ISSUE TITLE
Trying to import assets but Models colums is showing unknown.

### ISSUE THREAD

**Issue by joelKamdem** [snipe/snipe-it#3704]
#### Expected Behavior (or desired behavior if a feature request)
I created a all  the different models that i have in my inventory into snipe-it so that it will recognize them during the import. 
Therefore i expected to see those appears in the columns models of the assets i'm importing through the csv file.
(what you expect to happen goes here)

-----

#### Actual Behavior
However, when I'm importing with the exact names that are in the system, with no extra characters in the cells, i still see "unknown" in that column at the end of the importation. Moreover, the assets names are  not even showing, but most of the other columns are importing properly
(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode
- [ yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running -( Version 3)
- What OS and web server you're running Snipe-IT on - (Ubuntu 16, Apache2 Webserver)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)-(Manual and snipeit.sh)

- Indicate whether or not you've manually edited any data directly in the database (never)

**Comment by snipe** [comment]
Can you show me your import headers?
