### ISSUE TITLE
Cannot search users in people section

### ISSUE THREAD

**Issue by kosithuhein** [snipe/snipe-it#3706]
#### Expected Behavior (or desired behavior if a feature request)

Smooth search users under "People" section.

-----

#### Actual Behavior

I couldn't search users in People - only result all users and assumes freeze in first page.

In my database, there is "DB_Prefix" like "myasset2017_" and my db name is "sthasset".
So there is a message -
`LOG.error: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sthasset.users' doesn't exist in C:\wamp\www\asset\vendor\laravel\framework\src\Illuminate\Database\Connection.php:333`

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - `v3.6.6 build 1 (gee2c67a)`
- What OS and web server you're running Snipe-IT on - `Windows 7 & WAMP`
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - `manual installation`
- Any errors that appear in your browser's error console. - `no error shows but also cannot calculate search result`
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). - `smooth search in demo`

**Comment by rmavery** [comment]
We appear to  be having the same issue.   The one difference is that under 'All Assets' it returns EVERYTHING, but under the other categories, e.g, 'Users' it returns nothing.

**Comment by kosithuhein** [comment]
This is caused by the table prefix. When i removed the prefix and reinstalled Snipe, it worked very fine.
