### ISSUE TITLE
FEATURE REQUEST: Keep hamburger left justified when expanding menu.

### ISSUE THREAD

**Issue by ak2766** [snipe/snipe-it#3707]
Currently, when the left hand side menu is collapsed and one clicks the hamburger to expand it, the hamburger moves to the right meaning it is right justified to the menu window.  This means that to collapse the menu again, one has to move the mouse to the right.

Although one might argue that no one clicks the menu just to then collapse, it sometimes could just be someone exploring the different features of the application.  In such a situation, the experiencing is subpar and would be improved by ensuring the hamburger is left justfied.

Enough verbiage; make it so, snipeyhead - :)!

Cheers,
ak.

PS:  Awesome application this!

**Comment by cipnt** [comment]
I agree

**Comment by cipnt** [comment]
That would be a nice.
It's a very subtle change, I agree, but one that would make sense in my opinion.

On the same topic, the Assets and Settings menu items are not clickable when the menu is collapsed.
I understand they are expandable menus, but if I can click on all the other why can't I click on these as well and be taken to the top item in that sub-menu.
This for me is an issue with the Assets menu – I always want to access the Assets -> List All submenu and rarely need the other submenu items.
