### ISSUE TITLE
Trying out Snipe It 4.0 Alpha on New VM

### ISSUE THREAD

**Issue by elJoeyJojo** [snipe/snipe-it#3708]
#### Expected Behavior (or desired behavior if a feature request)

I just want to see the new version of Snipe It but getting errors when trying to run artisan app:install --env=production

-----

#### Actual Behavior

This is the error I get: 

[snipeit@snipeitnew snipe-it-4.0]$ php artisan app:install --env=production
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/opt/snipe-it-4.0/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied' in /opt/snipe-it-4.0/bootstrap/cache/compiled.php:13906
Stack trace:
#0 /opt/snipe-it-4.0/bootstrap/cache/compiled.php(13836): Monolog\Handler\StreamHandler->write(Array)
#1 /opt/snipe-it-4.0/bootstrap/cache/compiled.php(13596): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /opt/snipe-it-4.0/bootstrap/cache/compiled.php(13694): Monolog\Logger->addRecord(400, Object(UnexpectedValueException), Array)
#3 /opt/snipe-it-4.0/bootstrap/cache/compiled.php(13389): Monolog\Logger->error(Object(UnexpectedValueException), Array)
#4 /opt/snipe-it-4.0/bootstrap/cache/compiled.php(13360): Illuminate\Log\Writer->writeLog('error', Object(UnexpectedValueException), Array)
#5 /opt/snipe-it-4.0/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(57): Illuminate\Log\Writer->error(Object(UnexpectedValueException in /opt/snipe-it-4.0/bootstrap/cache/compiled.php on line 13906
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/opt/snipe-it-4.0/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied' in /opt/snipe-it-4.0/bootstrap/cache/compiled.php:13906
Stack trace:
#0 /opt/snipe-it-4.0/bootstrap/cache/compiled.php(13836): Monolog\Handler\StreamHandler->write(Array)
#1 /opt/snipe-it-4.0/bootstrap/cache/compiled.php(13596): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /opt/snipe-it-4.0/bootstrap/cache/compiled.php(13694): Monolog\Logger->addRecord(400, Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#3 /opt/snipe-it-4.0/bootstrap/cache/compiled.php(13389): Monolog\Logger->error(Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#4 /opt/snipe-it-4.0/bootstrap/cache/compiled.php(13360): Illuminate\Log\Writer->writeLog('error', Object(Symfony\Component\Debug\Exception\FatalErrorException), Array)
#5 /opt/snipe-it-4.0/vendor/laravel/framework/src/Illuminate/Foundation/E in /opt/snipe-it-4.0/bootstrap/cache/compiled.php on line 13906

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - Version 4.0 Alpha
- What OS and web server you're running Snipe-IT on - CentOS 7.3 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual Installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
@elJoeyJojo we haven't use the `app:install` command since 2.x.  Follow the 4.0 installation instructions. https://snipe-it.readme.io/v4.0/docs/installation

**Comment by elJoeyJojo** [comment]
thanks @snipe my bad lol
