### ISSUE TITLE
Whoops, something went wrong

### ISSUE THREAD

**Issue by elJoeyJojo** [snipe/snipe-it#3709]
#### Expected Behavior (or desired behavior if a feature request)

Getting the "Whoops something went wrong" error

-----

#### Actual Behavior

Built a new VM for Snipe It 4.0 and followed all instructions.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - 4.0 Alpha2
- What OS and web server you're running Snipe-IT on - CentOS 7.3
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual Installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - snipeit.domain.com
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

[Thu Jun 29 12:39:40.250320 2017] [:error] [pid 1991] [client 192.168.1.219:54824] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/opt/snipe-it-4.0/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied' in /opt/snipe-it-4.0/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /opt/snipe-it-4.0/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /opt/snipe-it-4.0/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /opt/snipe-it-4.0/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\\Logger->addRecord(400, Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#3 /opt/snipe-it-4.0/vendor/laravel/framework/src/Illuminate/Log/Writer.php(202): Monolog\\Logger->error(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#4 /opt/snipe-it-4.0/vendor/laravel/framework/src/Illuminate/Log/Writer.php(113): Illuminate\\Log\\Writer->writeLog('er in /opt/snipe-it-4.0/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107

- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by elJoeyJojo** [comment]
I used MariaDB instead of MySQL and I used: 

# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mariadb
DB_HOST=localhost
DB_DATABASE=snipeit
DB_USERNAME=snipeit
DB_PASSWORD=password
DB_PREFIX=null
DB_DUMP_PATH='/usr/bin'

in my .env file, do I have to use mysql?

**Comment by bharrison-it** [comment]
I just ran into this about 20 minutes ago; Looks like permissions for "/opt/snipe-it-4.0/storage/logs/laravel.log" are hosed sir; chmod 755 the storage folder and contents with:

chmod -R 755 /opt/snipe-it-4.0/storage

Also, make sure your webserver user can access the same folder.

Rinse, Repeat.

mariadb should be drop-in compatible.

**Comment by elJoeyJojo** [comment]
@bharrison-it hey thanks for that info! i am sure i had ran that same permissions command last time but i guess i missed the -R perhaps, although I followed the instructions to the T. after that it still didn't work but that's because i used a DB_Connection=mariadb, once I changed it to mysql and rebooted it, it worked.

Thanks

**Comment by bharrison-it** [comment]
Hey, happy to help.

So just to clarify, you're using mariadb but had to use the environment variable mysql to connect to it, right?

My experience with maria is limited but since it's replaced mysql in Debian 9 I assume it to function as a drop-in replacement.

**Comment by elJoeyJojo** [comment]
hey so i downloaded https://github.com/snipe/snipe-it/archive/v4.0-alpha.tar.gz and somehow i ended up with v3.6.4 :S

**Comment by elJoeyJojo** [comment]
though when I run: php artisan passport:install at /opt/snipe-it-4.0/ i get a: 

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  There are no commands defined in the "passport" namespace.

**Comment by elJoeyJojo** [comment]
yup, looked at my history and this is what i downloaded: 

sudo wget https://github.com/snipe/snipe-it/archive/v4.0-alpha-2.tar.gz 

So how the heck did I end up with v 3.6.4 ??

**Comment by elJoeyJojo** [comment]
anybody? how do i get v 4.0?

**Comment by elJoeyJojo** [comment]
@snipe hey sorry to bother you but can you help me out?
