### ISSUE TITLE
Google SMTP Not Working

### ISSUE THREAD

**Issue by robblehead** [snipe/snipe-it#3710]
#### Expected Behavior (or desired behavior if a feature request)

Use email with google client

-----

#### Actual Behavior

error message
-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 
3.6.6 build 1
- What OS and web server you're running Snipe-IT on
CentOS 7 
PHP Version 5.6.30
Laravel Version 5.2.45
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Whoops, looks like something went wrong.

Swift_TransportException in StreamBuffer.php line 269:
Connection could not be established with host smtp.gmail.com [permission denied #13]

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
when trying to send an email
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
Followed through all instructions about setting up Gmail properly.  Attempted searching Google for assistance.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
What are your mail settings in your `.env`? (Redact username and password)

**Comment by robblehead** [comment]
sorry playing catch up, will update in here ASAP.

**Comment by venchron** [comment]
Make sure you log into the gmail account you are using and enable access for less secure apps. You can do that here once you're logged in:

[Enable Less Secure Apps](https://www.google.com/settings/u/2/security/lesssecureapps)

**Comment by snipe** [comment]
@venchron that's already documented in the configuration documentation: https://snipe-it.readme.io/docs/configuration#section-using-gmail
