### ISSUE TITLE
Default encryption algorithm inoperable, Or: Whoops, Something went wrong (really).

### ISSUE THREAD

**Issue by bharrison-it** [snipe/snipe-it#3713]
#### Expected Behavior (or desired behavior if a feature request)

Following a clone from git and the setup instructions results in a workable pre-flight scenario.

-----

#### Actual Behavior

After a git clone and non-global composer installation laravel starts balking and reports it's taken issue with the encryption cipher / key length, as it is wont to do in my experience. Specifically:

"...
[2017-07-03 21:07:20] production.ERROR: exception 'RuntimeException' with message 'No supported encrypter found. The cipher and / or key length are invalid.' in /var/www/html/snipeit/bootstrap/cache/compiled.php:7771
..."

So I figure in my wisdom I've neglected to generate the key correctly, or .env isn't updating, so I regenerate via:

php artisan key:generate

Verify the correct key is in .env, then reload the cache with:

php artisan config:cache

The same error persists.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Snipe-IT v3.6.6 build 1 (gee2c67a)
- Debian Jessie, Apache 2.4.10-10+deb8u1
- Cloned git, local composer install
- Somewhat infuriatingly the browser renders two "Whoops..." and nothing else...
- redirecting to /setup for initial install and pre-flight fun.
- Stacktrace attached!
[20170704_SNIPE-IT_LARAVEL_STACKTRACE.txt](https://github.com/snipe/snipe-it/files/1121003/20170704_SNIPE-IT_LARAVEL_STACKTRACE.txt)

.------

Also, I've found and fixed the problem:

The original config/app.php includes:

'key' => env('APP_KEY'),
'cipher' => 'rijndael-256',

The generated key was in format:

base64:mygeneratedkeywhichisover32bits

Since I confirmed .env was getting the new key, I plugged it into config/app.php directly, replacing the line with:

'key' => 'base64:mygeneratedkeywhichisover32bits',

The same behavior was produced and the same error was logged.

Replacing the cipher in config/app.php a la:

'cipher' => 'AES-256-CBC',

Manually trimming the generated key (laziness) to 32bits and reloading the cache results in expected operation and pizza all around.

This smells like a debian thing, especially since Jessie is recently oldstable. What I can't find regarding rijndael-256 support just about fits into the Grand Canyon.

Please let me know if you need any additional info.

**Comment by snipe** [comment]
This has been covered a few times in previous issues. #3668 #3637 #3584 (etc).

**Comment by snipe** [comment]
You should NOT add your key to `config/app.php` directly. When you upgrade, your key will be overwritten, and any encrypted fields you have will be forever lost. You can change the cipher in  `config/app.php` (since future versions allow you to specify your cipher in the `.env`, but NOT your key. Never, ever your key.
