### ISSUE TITLE
No logs when running docker snipeit 

### ISSUE THREAD

**Issue by volatilemolotov12** [snipe/snipe-it#3714]
Logs should be in storage/logs
-----
storage/logs is empty
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v3.6.6 Docker
- What OS and web server you're running Snipe-IT on - Centos 7 - Docker-CE
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - No error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error -ANY
- If a stacktrace is provided in the error, include that too. -NO
- Any errors that appear in your browser's error console. -NO
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). -N/A
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.-NO
- Include what you've done so far in the installation, and if you got any error messages along the way. 
- Indicate whether or not you've manually edited any data directly in the database - NO

**Comment by kolob4all** [comment]
I have the same issue even without using Docker. I'm trying to debug LDAP connection and logs are not updating at all. app/storage/logs

**Comment by sashasimkin** [comment]
I've caught the same problem on `6.1.0`.
After some trial and error, I learned that you also need to set `LOG_LEVEL=debug`.
I was able to see the logs under `/var/www/html/storage/logs/laravel.log` after that.
