### ISSUE TITLE
Cant create a new asset

### ISSUE THREAD

**Issue by flogadob** [snipe/snipe-it#3715]
#### Expected Behavior (or desired behavior if a feature request)

I want to be able to add assets to snipe-it

-----

#### Actual Behavior

From the dashboard, i click on the total assets box, create new asset, add the details for the new asset and click save.  The screen refreshes and all the fields are empty again, i go back to the dashboard and no new asset has been added

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode - yes
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) - yes

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - version 3.6.2
- What OS and web server you're running Snipe-IT on - windows server 2016 and WAMP32
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual install following the instructions for a WAMP install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - no error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error- dashboard>total assets>create new asset
- If a stacktrace is provided in the error, include that too.- N/A
- Any errors that appear in your browser's error console.- no error
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). - the demo works as expected
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. - ive looked through the logs and nothing jumps out at me, but i have very limited developer experience, so if you guys need me to post the logs on here, just let me know 
- Include what you've done so far in the installation, and if you got any error messages along the way. -i had no errors during installation 
- Indicate whether or not you've manually edited any data directly in the database - havent touched the database

**Comment by xWyatt** [comment]
Do you happen to be using a custom REGEX validation for a custom field for this asset?

**Comment by flogadob** [comment]
Hi,

ive no clue what that is lol, i was asked to set this software up by my manager, i have pretty much no developer experience.

Im trying to add netbooks, so ive created a small list of models.  I enter an asset tag, add one of the models i created and choose a status, thats it, then click save, and nothing

**Comment by xWyatt** [comment]
Do you have an error in the debug console (in Chrome - F12) when you attempt to create the asset?
That, and/or any errors on the server in `storage/logs/laravel.log`? If so, can you post them here? 

It also might help to upgrade to the lastest 'release' version 3.6.6 if you haven't already. Just some thoughts.

**Comment by flogadob** [comment]
ok, let me try the upgrade first and ill let you know if that fixed the issue not :)

**Comment by flogadob** [comment]
OK upgraded to the latest version and it now works :)
