### ISSUE TITLE
Feature request: Return time

### ISSUE THREAD

**Issue by pantheonw** [snipe/snipe-it#3716]
#### Expected Behavior (or desired behavior if a feature request)

Time and date for asset and accessory return (and checkout)

-----

#### Actual Behavior

has expected return date, no time

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
I'm not sure what you're asking for here. Can you prpvide screenshots?

**Comment by pantheonw** [comment]
On bulk checkout it only shows the dates. In the activity log it defaults to the current time for out which is fine for my purposes but the check in lets you pick a date in the past and then defaults the time to midnight that date.

![screen shot 2017-07-17 at 1 51 09 pm](https://user-images.githubusercontent.com/677541/28284671-67482828-6af7-11e7-98ee-e01d887fb6ef.png)
