### ISSUE TITLE
Feature request: Bulk checkout accessories

### ISSUE THREAD

**Issue by pantheonw** [snipe/snipe-it#3717]
#### Expected Behavior (or desired behavior if a feature request)

accessories included as items for bulk checkout

-----

#### Actual Behavior

only assets appear in bulk checkout

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by smksar** [comment]
Yes the bulk checkout is only asset at the moment as of Apr 2018. 

Looking to have this function as well when possible.

The other place I can think of is right under the user's profile view:
![checkout](https://user-images.githubusercontent.com/38576928/39080138-5699d7bc-455b-11e8-91ab-c6db32982848.PNG)
Maybe a button "Check Out" at the bottom.

**Comment by webyxdesign** [comment]
any news or workarounds for this? :)
