### ISSUE TITLE
http Inernal Server 500 error when launching snipe-it from \inetpub\wwwroot\snipe-it\public

### ISSUE THREAD

**Issue by MoVill** [snipe/snipe-it#3718]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

Launching snipe-it for the first time after carefully following all the setup requirements and installation

#### Actual Behavior

upon launching the webapp, either directly on the browser or from IIS manager I get the same error. If I change the path to \inetpub\wwwroot\ , I only get the IIS page.

-----

#### Please confirm you have done the following before posting your bug report:

- [Yes ] I have enabled debug mode
- [Yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running = 3.6.6
- What OS and web server you're running Snipe-IT on = 2012 R2 / IIS 8
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) = Manual Installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error = HTTP 500 Internal Serve error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too. = I don't see anything about that on the page
- Any errors that appear in your browser's error console. = nothing just a regular page info with http 500
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo) = demo site is working properly
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. = 
No log file on /storage/logs. Only one file which is .gitignore and same contents when pening the file with notepad++
Web Serve log:
#Software: Microsoft Internet Information Services 8.5
#Version: 1.0
#Date: 2017-07-05 20:01:57
#Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) cs(Referer) sc-status sc-substatus sc-win32-status time-taken
2017-07-05 20:01:57 ::1 GET / - 80 - ::1 Mozilla/5.0+(Windows+NT+6.3;+WOW64;+Trident/7.0;+rv:11.0)+like+Gecko - 500 0 0 3593
2017-07-05 20:01:57 ::1 GET / - 80 - ::1 Mozilla/5.0+(Windows+NT+6.3;+WOW64;+Trident/7.0;+rv:11.0)+like+Gecko - 500 0 0 5392
2017-07-05 20:11:15 ::1 GET / - 80 - ::1 Mozilla/5.0+(Windows+NT+6.3;+WOW64;+Trident/7.0;+rv:11.0)+like+Gecko - 500 0 0 15
2017-07-05 20:26:09 ::1 GET / - 80 - ::1 Mozilla/5.0+(Windows+NT+6.3;+WOW64;+Trident/7.0;+rv:11.0)+like+Gecko - 500 0 0 31
- Include what you've done so far in the installation, and if you got any error messages along the way.= I Just followed snipe-it guide from the website. I had to redo artisan command prompt twice.
- Indicate whether or not you've manually edited any data directly in the database = I did not edit the DB manually.

**Comment by snipe** [comment]
Is the `storage` directory (and all subdirectories) writable? I'm guessing not, if there's no log file at all.

**Comment by MoVill** [comment]
The folder is writable and IUSR has full control over "storage folder" and subdirectories. I keep reverting to all the guidelines and I couldn't figure out where I miss. This is the first php website I created on IIS , so I'm really trying to learn it. Hope you can enlighten me more what I need to do. Thanks.

**Comment by MoVill** [comment]
I recreated the vm with Server 2016 Standard, IIS 10, PHP 7 x86/x64, MySQL 5.5, and reinstalled all the required utilities/roles/features. Still no luck. same error.

**Comment by BrettFagerlund** [comment]
Do you have PHP Manager installed? If so check that you can run phpinfo from your SnipeIT website, and also check if there is anything in the PHP log file specified, it will usually default to C:\Windows\Temp\PHP....

Also if you enable detailed errors via, inetmgr -> Error pages -> edit feature settings, does that give you any additional info?

**Comment by MoVill** [comment]
Yes I installed PHP Manager. I run php manager from the IIS snipe-it website and was able to open phpinfo.

The error is: 
[13-Jul-2017 13:07:30 America/New_York] PHP Warning:  require(C:\inetpub\wwwroot\snipeIT\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\inetpub\wwwroot\snipeIT\bootstrap\autoload.php on line 17
[13-Jul-2017 13:07:30 America/New_York] PHP Fatal error:  require(): Failed opening required 'C:\inetpub\wwwroot\snipeIT\bootstrap/../vendor/autoload.php' (include_path='.;C:\php\pear') 
in C:\inetpub\wwwroot\snipeIT\bootstrap\autoload.php on line 17.

I then went to the directory and open autoload.php and examine line 17. 
This is what it display on the line.
require __DIR__.'/../vendor/autoload.php';

when I go to error pages, select status code; ie. 500 and click edit features edit settings, nothing on the popup window show any additional info except how you want responses and where should it be path but the path is empty and you can't redirect it.

**Comment by MoVill** [comment]
autoload.php:
<?php

define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| Register The Composer Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader
| for our application. We just need to utilize it! We'll require it
| into the script here so that we do not have to worry about the
| loading of any our classes "manually". Feels great to relax.
|
*/

require __DIR__.'/../vendor/autoload.php';

/*
|--------------------------------------------------------------------------
| Include The Compiled Class File
|--------------------------------------------------------------------------
|
| To dramatically increase your application's performance, you may use a
| compiled class file which contains all of the classes commonly used
| by a request. The Artisan "optimize" is used to create this file.
|
*/

$compiledPath = __DIR__.'/cache/compiled.php';

if (file_exists($compiledPath)) {
    require $compiledPath;
}

**Comment by MoVill** [comment]
here is autoload.php contents
<?php

define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| Register The Composer Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader
| for our application. We just need to utilize it! We'll require it
| into the script here so that we do not have to worry about the
| loading of any our classes "manually". Feels great to relax.
|
*/

require __DIR__.'/../vendor/autoload.php';

/*
|--------------------------------------------------------------------------
| Include The Compiled Class File
|--------------------------------------------------------------------------
|
| To dramatically increase your application's performance, you may use a
| compiled class file which contains all of the classes commonly used
| by a request. The Artisan "optimize" is used to create this file.
|
*/

$compiledPath = __DIR__.'/cache/compiled.php';

if (file_exists($compiledPath)) {
    require $compiledPath;
}

**Comment by MoVill** [comment]
compiled.php also doesn't exist on the path where the code is saying it to look for:

$compiledPath = __DIR__.'/cache/compiled.php';
if (file_exists($compiledPath)) {
    require $compiledPath;

**Comment by BrettFagerlund** [comment]
can you double check your have IUSR write permission on that bootstrap\cache folder?

Also was everything successful when you ran the composer commands?

**Comment by MoVill** [comment]
yes IUSR was write permission on the folder. actually full rights.
I didn't have any errors running the composer. do you think this has to do with the composer not installed properly? since compiled.php could not be found on that folder?

**Comment by MoVill** [comment]
I again ran composer install and notice this error at then end if this help:
Script php artisan clear-compiled handling the post-install-cmd event returned with error code 255
I still have the same php error:
[18-Jul-2017 16:15:10 America/New_York] PHP Fatal error:  require(): Failed opening required 'C:\inetpub\wwwroot\snipeIT\bootstrap/../autoload.php' (include_path='.;C:\php\pear') in C:\inetpub\wwwroot\snipeIT\bootstrap\autoload.php on line 17

**Comment by kdake** [comment]
I'm pretty much the exact same issue. I'll be watching this closely because it's very frustrating. I'm attempting to install the same version, too.

**Comment by kdake** [comment]
Okay, I got a little further! Out of frustration, I uninstalled Composer from server. Then I:

1. Moved Composer-Setup.exe to the root of my website (in the example above it'd be C:\inetpub\wwwroot\snipeIT - I use custom web paths so mine is different)
2. Double-clicked on Composer-Setup.exe and installed via the wizard.
3. Logged off Windows on the server. Logged back on.
4. Opened a cmd prompt in the root (see #1) and ran 'composer install'
5. It actually ran this time, something it hadn't done before. 
6. I then ran 'php artisan key:generate' which did what it was supposed to and updated my 
'.env' fi;e
5. Now, it's actually giving me a "Whoops, something went wrong" for the Pre-Flight page, which is better than the 500 error! Still stuck here though...

**Comment by kdake** [comment]
So I'm still having two issues:
1.) https://snipe-it.readme.io/docs/windowsiis says to edit permissions on the C:\inetpub\wwwroot\snipe-it\storage\laravel-backups folder, but that folder does not exist; 
2.) I'm getting the attached error. https://snipe-it.readme.io/docs/pre-flight-setup says "If you see a "Whoops" error or some other error, check the Common Issues page to see where you might have gone wrong." but https://snipe-it.readme.io/docs/common-issues doesn't have any applicable errors.
![capture](https://user-images.githubusercontent.com/16481198/28640877-2422f638-721b-11e7-9988-6c4e0ab6a661.PNG)

**Comment by MoVill** [comment]
kdake, I got that error too and was able to get around it by doing the following:
on IIS Manager of the Application Site, IIS section, click on Documents icon,  click on the index.php, then on the right side of the window, you'll see the up and down arrow, click move up until index.php is all at the top. close and reopen IIS Manager.
Hope it helps. I'm still stuck with mine. I'm taking of redoing the steps under Srv2012 r2.

**Comment by kdake** [comment]
Hi MoVill,

I tried the steps you suggested - unfortunately didn't help. 

When you say "close and reopen IIS Manager" - do you mean resetting IIS? Because closing and reopening IIS Manager doesn't do anything to the website (doesn't reset them or anything).

**Comment by MoVill** [comment]
kdake,
I just meant  for you to close and reopen IIS Manager. But you can also click "stop" and "start" on the right panel. But, you said it didn't work anyway.
iisreset from elevated command prompt will do it for all web apps on IIS Manager.
have you tried opening php manager from IIS Manger? you can actually click the error log from there too.
I'm still working on my snipe-it.
Try this http://www.kwoksys.com/wiki/index.php?title=Users%2C_Groups 
It's "Similar and easy to configure". I got it done faster and running.

**Comment by kdake** [comment]
I do get the error when I open php manager:

[26-Jul-2017 14:48:41 America/New_York] PHP Warning:  require(E:\snipe-it-3.6.6\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in E:\snipe-it-3.6.6\bootstrap\autoload.php on line 17

And I have no idea how to fix it. I'm about ready to go back to spreadsheets, I don't think this program is built out enough to work well on IIS and I don't have the skills to fix it.

**Comment by MoVill** [comment]
I get that error too. The process is looking for that particular file but it's nowhere on the app folder or sub folder. I wonder if it's generated.
I got this up and running in a day http://www.kwoksys.com/wiki/index.php?title=Users%2C_Groups
This is what I'm using now. similar functions and easy to setup. try it. It's also an open source.

**Comment by kdake** [comment]
Thanks for the link, but there's not enough information on that system for me to determine if it'll work for us, nor does there seem to be IIS/Windows instructions. I think it's just back to the drawing board for us to find a more user-friendly service then Snipe IT that doesn't require Linux! :)

**Comment by MoVill** [comment]
It uses Apache-Tomcat and PostgressSQL (I'm new to this protocols as well). Everything is provided on the zip file including the instruction (which is very simple) when you download it. I find kwok more useful to utilize than using excel because you can query and search. Reports are easy to understand as well.

**Comment by kdake** [comment]
MoVill - if it helps, I figured out my issue with SnipeIT. I had to change PHP from 7.1.7 to 5.6.0. Worked then and I'm on to the the preflight page.

**Comment by MoVill** [comment]
oh that cool. I'll try downloading my php.
