### ISSUE TITLE
Unable to add Model

### ISSUE THREAD

**Issue by hlastimosa** [snipe/snipe-it#3719]
#### Adding Model when creating assets

1. Created Assets 
2. Select under Model , select New 
3. Entered the required fields in Model 

-----

#### Actual Behavior
1. Created Assets 
2. Select Model --> New 
3. Entered the required fields in model 
4. Hitting Save does not save the newly created model

-----

#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
######
Related information below : 

1. Specific page on Snipe-IT - hardware/create?model 
2. System Information : 
Snipe-IT version | v3.6.6 build 1 (gee2c67a)
PHP Version | 5.6.30
Laravel Version | 5.2.45
OS : CentOS 7.3 64 bit 
Apache 2.4.6
MariaDB : 5.5.52
3. Turned on Debugging - yes
4. Errors related to Query - none shown 
5. Reproduced in Demo Site - unable to reproduce 
6. Edited .env file to show debug mode and restarted HTTPD 
7. App/storage logs - no logs found 
8. SnipeIT.error.log - 0 bytes
9. No relevant error_logs under httpd

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Please check the following:

- Is the `storage` directory writable?
- Are there any [errors in your browser console](https://snipe-it.readme.io/v3.6.2/docs/getting-help#section-step-2-enable-your-browsers-error-console) when you click "save" on the model modal? 
- Does the `APP_URL` in your `.env` match the base URL in the browser bar?

**Comment by hlastimosa** [comment]
1. Storage directory set to 755 
2. Screenshots attached after selecting new 
![screen shot 2017-07-17 at 1 44 35 pm](https://user-images.githubusercontent.com/29910580/28256582-75646eb8-6af6-11e7-9de1-d90d5b85325b.png)
![screen shot 2017-07-17 at 1 44 53 pm](https://user-images.githubusercontent.com/29910580/28256583-756636ee-6af6-11e7-80a4-21cb48cbd9fb.png)
![screen shot 2017-07-17 at 1 45 06 pm](https://user-images.githubusercontent.com/29910580/28256584-75677342-6af6-11e7-9edc-30062fd7965f.png)
![screen shot 2017-07-17 at 1 45 21 pm](https://user-images.githubusercontent.com/29910580/28256586-7568a244-6af6-11e7-898b-08fd598615cc.png)
![screen shot 2017-07-17 at 1 46 05 pm](https://user-images.githubusercontent.com/29910580/28256585-7567e75a-6af6-11e7-8f48-5165e032cf17.png)

**Comment by hlastimosa** [comment]
found out what the issue is , need to create an asset model first to be tied up to asset
