### ISSUE TITLE
Cannot Rename nor Delete Company 

### ISSUE THREAD

**Issue by jasonspriggs** [snipe/snipe-it#3724]
#### Expected Behavior (or desired behavior if a feature request)

I would expect edit and delete buttons would exist in the Company listing page where I could do these actions.

-----

#### Actual Behavior

Neither button exists, though the functions exist in the API to do these actions.
![companylisting](https://user-images.githubusercontent.com/16108587/27941718-0bc3798a-62a0-11e7-92bd-b21c922890f9.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - develop v4 latest

**Comment by snipe** [comment]
Thanks! Should be fixed on develop now!
