### ISSUE TITLE
Cannot Create Asset from Asset Models View

### ISSUE THREAD

**Issue by jasonspriggs** [snipe/snipe-it#3725]
#### Expected Behavior (or desired behavior if a feature request)

There should be a button that shows me a create asset model modal from the Asset Models listing view.

-----

#### Actual Behavior

No such button exists.
![chrome_2017-07-06_23-17-17](https://user-images.githubusercontent.com/16108587/27941973-9900fda8-62a1-11e7-9630-f4a567105005.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - develop v4 latest

**Comment by snipe** [comment]
Fixed on develop
