### ISSUE TITLE
(Feature Request) Admin Panel

### ISSUE THREAD

**Issue by fordster78** [snipe/snipe-it#3727]
#### Expected Behavior (or desired behavior if a feature request)

Have an Admin panel, where are settings will be based.
The Links are separated by category. e.g. Categories, assets models, suppliers fall under assets and departments, location and people fall under users.

Please see example image below. This is from an open source helpdesk which I thought the concept would work well with snipeit.

![image](https://user-images.githubusercontent.com/27958330/27960660-06678f88-6324-11e7-9d4e-a5461c538453.png)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
I'm not really sure what you're looking for here. We have that, the difference is that instead of a page with icons, all of the admin settings are under the admin dropdown menu.

**Comment by snipe** [comment]
(And actually, most of those settings have been moved out of the admin in the upcoming v4)
