### ISSUE TITLE
Snipe-IT installation ads a deprecated repo for MariaDB

### ISSUE THREAD

**Issue by TheElectroclassics** [snipe/snipe-it#3730]
I'm on my third try to install Snipe-IT. Everytime I run the install script, it ads a deprecated repo for MariaDB, which renders apt-get unusable until the correct repo is added.

**Comment by snipe** [comment]
@mtucker6784 - I know you're pretty busy these days, but can you check into this? Or @uberbrady?

**Comment by mtucker6784** [comment]
Yep. I don't think I'll be able to today, but I can take a bat to it
Monday.

**Comment by snipe** [comment]
Awesome, thanks!

**Comment by mtucker6784** [comment]
Sorry, not ignoring this. We've had most of our staff come back in the last week and it has just inundated me with a ton of issues. I'm still planning on getting this corrected "soon", hopefully this weekend >.>

**Comment by mtucker6784** [comment]
@TheElectroclassics , are you on 16.10 or 17.04?

**Comment by mtucker6784** [comment]
@TheElectroclassics --bump--

**Comment by TheElectroclassics** [comment]
16.04.2 LTS

**Comment by mtucker6784** [comment]
great, thank you
