### ISSUE TITLE
Snipe Installation - Newbie Edition

### ISSUE THREAD

**Issue by TheElectroclassics** [snipe/snipe-it#3731]
I've seen that the Install Script is pretty straight forward, but at the time to install the dependencies (obviously, before running the script) I'm having trouble adding them to my system (Ubuntu Server 16.04.2). Does anyone have a list of sources where I can pull the dependencies? or a "newbie" oriented installation guide?

Thanks in advice.

**Comment by inakigoicolea** [comment]
Bsically follow steps 1 - 4 of [this guide](https://www.vultr.com/docs/how-to-install-snipe-it-on-ubuntu-16-10)

and then run the script
