### ISSUE TITLE
Custom password reset link

### ISSUE THREAD

**Issue by danpospisil** [snipe/snipe-it#3735]
#### Expected Behavior (or desired behavior if a feature request)

We have enabled LDAP sync and we want users to sign in only through it. When a user clicks "I forgot my password" it sends him a reset token with a link to reset internal snipe it password. We would rather send a link to our LDAP reset password system - now we have to manually edit "resources/views/auth/emails/password.blade.php" file to do that which will be overwritten with every update. 

-----

#### Please confirm you have done the following before posting your bug report:

- [NO] I have enabled debug mode
- [YES] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - 3.6.6

**Comment by snipe** [comment]
I think the solution that would be more extensible for the community is to optionally disable password resets if LDAP is enabled. You can add the password reset instructions using the new login note feature coming in v4.
