### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by rWaddles** [snipe/snipe-it#3737]
Gone through a second attempt for installing snipe-it, ran through the whole guide got to the stage of actually entering the address for Pre checks.

I am currently getting a 403 I do not have access to /
I cannot access any files within public even a /phpinfo.php
I have checked I am directed to the public folder, I have put random gumf in .htaccess which returned a internal server error so that is doing its job. Permissions wise www-data has full r/w/x to public.

At a loss of what else to check

**Comment by snipe** [comment]
Check and make sure that .php is set as a directory index type in your httpd.conf. 

`DirectoryIndex index.php`

**Comment by rWaddles** [comment]
Now what would cause me not to have a httpd.conf?

**Comment by rWaddles** [comment]
Sorry, commented before research - so this should be my site available conf for this virtual site. Currently:
DocumentRoot /var/www/snipe/public
<Directory /var/www/snipe/public>
Require all granted
AllowOverride All
Options None
</Directory>

If  change the directory to either /var/www/snipe/public/index.php or /index.php it throws a 500 error.

**Comment by rWaddles** [comment]
As an update,

I can access all the other files in public via  IP:8080 such as /phpinfo.php and robots.txt
phpinfo runs as it should but index.php (which is there) nothing 
"This page isn’t working

10.1.105.3 didn’t send any data.
ERR_EMPTY_RESPONSE"

**Comment by rWaddles** [comment]
Believe this was an issue with turnkey I was using, I wasn't using SSL but it was installed for other parts. Did a barebones install and it works fine.
