### ISSUE TITLE
 There was an error authenticating the LDAP user: Could not find user in LDAP directory

### ISSUE THREAD

**Issue by ChristopherM87** [snipe/snipe-it#3738]
#### Expected Behavior (or desired behavior if a feature request)

SnipeIT LDAP login should work

-----

#### Actual Behavior

I added the follow settings to SnipeIT LDAP:

- LDAP enabled = Yes
- LDAP Password Sync = Yes
- LDAP server = ldaps://***.company.local
- Allow invalid SSL Certificate = Yes
- LDAP Bind Username = cn=user,dc=company,dc=local
- LDAP Bind Password = ***
- Base Bind DN = ou=department,dc=company,dc=local
- LDAP Filter = &(cn=admin)
- Username Field = uid
- Last Name = sn
- LDAP First Name = firstname
- LDAP Authentication query = uid=
- LDAP Version = 3
- LDAP email = mail

The LDAP test completed successfully. I imported the admin user into Snipeit in the People page and activated it.

When I try to login, an error message appears saying incorrect username or password.

-----

#### Please confirm you have done the following before posting your bug report:

- [Yes ] I have enabled debug mode
- [Yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.6.6 build 1 (gee2c67a)
- What method you used to install Snipe-IT: Docker on Ubuntu

Error in logs:

[2017-07-12 13:32:38] production.DEBUG: LDAP is enabled.  
[2017-07-12 13:32:38] production.DEBUG: Binding user to LDAP.  
[2017-07-12 13:32:38] production.DEBUG: LDAP user admin not found in LDAP or could not bind  
[2017-07-12 13:32:38] production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory

**Comment by slinkoff** [comment]
Is this AD?

Assuming yes then "LDAP Authentication query" should say "sAMAccountName=" and username field should be "samaccountname".   Also "LDAP bind user" should be a username not a DN.  If not AD, I think it's just your LDAP bind user not being a username which is the problem.

**Comment by ChristopherM87** [comment]
This is not AD. I changed the LDAP bind username to "user". But when I test LDAP it says "Could not bind to LDAP: Invalid DN syntax".

**Comment by ReeceYoung98** [comment]
This is the exact same issue that I'm having.

All users (700 of which) are imported on LDAP sync although ending up not being able to login. Same errors as OP.

**Comment by snipe** [comment]
If users are importing but not able to login, it’s aalmost always the auth filter that’s incorrect
