### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by ruzzetto** [snipe/snipe-it#3739]
#### Expected Behavior (or desired behavior if a feature request)
Run for the first time after download and configuration steps - Pre-Flight & Setup -
(what you expect to happen goes here)

-----

#### Actual Behavior
The requested URL /setup was not found on this server.
(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [Yes] I have enabled debug mode
- [Yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: latest one (pull from git)
- What OS and web server you're running Snipe-IT on (Ubuntu 17.04 - Apache 2.4)
- What method you used to install Snipe-IT (Git Clone)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error 
"Not Found
The requested URL /setup was not found on this server."

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/common-issues#section-the-requested-url-setup-was-not-found-on-this-server

**Comment by jmontoya1974** [comment]
I had the same problem on a Ubuntu Server (LAMP), and what I did in apache was to add:

<Directory “/var/www/html”>
AllowOverride All
</Directory>

not only in the virtual site file
I had to add to the general Apache Conf:

/etc/apache2/sites-enabled/000-default.conf 

This to be sure mod_rewrite works along the entire apache sites.
restart apache.
Worked!

**Comment by tydonk** [comment]
Where did you add that line in your Apache.conf file?

**Comment by jmontoya1974** [comment]
just below the custom log sentence

<Directory “var/www/html”>
AllowOverride All
</Directory>

**Comment by ebonweaver** [comment]
Thanks for that answer Montoya.  This really needs to be added to the installation instructions, especially because contrary to the above response, it's NOT in the common issues.

**Comment by snipe** [comment]
@ebonweaver While we try to be as helpful as possible with Linux troubleshooting, this is web based software, so we expect a certain level of knowledge of webservers if you're hosting it on a Linux platform. There are over a dozen reasons that mod_rewrite might not be working (or might look like it's not), and none of of them have anything to do with Snipe-IT itself.

It's not a Snipe-IT issue, it's a server configuration issue, and we certainly can't document every thing that someone could run into while running a Linux web server in our application documentation. That's what their documentation and stackoverflow is for.

**Comment by mohitkamboj2799** [comment]
can any help me am also have same problem when we use ip/setup it show The requested URL /setup was not found on this server. while i check i found the file setup is missing in var/www/html/snipe.

**Comment by marcusmoore** [comment]
@mohitkamboj2799 [this section](https://snipe-it.readme.io/docs/installation-issues#the-requested-url-setup-was-not-found-on-this-server) of the docs may help.
