### ISSUE TITLE
Application is not accessible configured in Windows IIS

### ISSUE THREAD

**Issue by sureshdotbits** [snipe/snipe-it#3740]
#### Expected Behavior (or desired behavior if a feature request)
Home page should come while accessing http://localhost/
(what you expect to happen goes here)
getting error

-----

#### Actual Behavior

(what actually happens goes here)
Hi, I have installed snipe it of version 3.0.0 and configured to work on IIS.  Have installed on dependencies successfully but even then i am getting below error when I tried to open home page.  Have attached web.config file with this issue.
HTTP Error 500.19 - Internal Server Error
The requested page cannot be accessed because the related configuration data for the page is invalid.
Detailed Error Information:
Module
   IIS Web Core
Notification
   Unknown
Handler
   Not yet determined
Error Code
   0x8007000d
Config Error
   
Config File
   \\?\C:\inetpub\wwwroot\snipeit\public\web.config
Requested URL
   http://localhost:80/
Physical Path
   
Logon Method
   Not yet determined
Logon User
   Not yet determined

Config Source:
   -1: 
    0: 
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running --> 3.6.2
- What OS and web server you're running Snipe-IT on --> Windows 10, IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) --> Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error --> Included above
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error --> Home page itself is not coming
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). --> No
[web-config.txt](https://github.com/snipe/snipe-it/files/1142984/web-config.txt)

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by BrettFagerlund** [comment]
Could you please confirm that URL Rewrite is installed, and appears under IIS Manager for the Snipe-IT website?

**Comment by sureshdotbits** [comment]
Hi Brett,
Thank you very much for the quick response, I have not installed URL Rewrite, please can provide me the installation instructions?
		

		Thanks and Regards
Suresh Raja
	





On Wed, Jul 12, 2017 at 7:27 PM -0400, "Brett" <notifications@github.com> wrote:












Could you please confirm that URL Rewrite is installed, and appears under IIS Manager for the Snipe-IT website?

**Comment by BrettFagerlund** [comment]
Generally you can just install via WPI, but here's a link to it.

https://www.iis.net/downloads/microsoft/url-rewrite

**Comment by sureshdotbits** [comment]
Hi Brett,

 

Thanks for the quick response, I am getting below error after installing URL Rewrite.  Please help me with the solution.

 

HTTP Error 403.14 - Forbidden

The Web server is configured to not list the contents of this directory.

Most likely causes:

A default document is not configured for the requested URL, and directory browsing is not enabled on the server.

Things you can try:

If you do not want to enable directory browsing, ensure that a default document is configured and that the file exists. 

Enable directory browsing using IIS Manager. 
Open IIS Manager.
In the Features view, double-click Directory Browsing.
On the Directory Browsing page, in the Actions pane, click Enable.
Verify that the configuration/system.webServer/directoryBrowse@enabled attribute is set to true in the site or application configuration file.

Detailed Error Information:

ModuleDirectoryListingModule
NotificationExecuteRequestHandler
HandlerStaticFile
Error Code0x00000000

 

Requested URLhttp://localhost:80/
Physical PathC:\inetpub\wwwroot\snipeit\public
Logon MethodAnonymous
Logon UserAnonymous

More Information:

This error occurs when a document is not specified in the URL, no default document is specified for the Web site or application, and directory listing is not enabled for the Web site or application. This setting may be disabled on purpose to secure the contents of the server. 

View more information »

 

 

Thanks

Suresh Raja

**Comment by sureshdotbits** [comment]
Please help me

**Comment by snipe** [comment]
@sureshdotbits Please be patient. People help when they can.

What happens when you go to http://localhost/index.php?

**Comment by snipe** [comment]
Make sure index.php is set as a directory index in your configuration:
https://support.microsoft.com/en-us/help/320051/how-to-configure-the-default-document-in-internet-information-services

**Comment by sureshdotbits** [comment]
Hi,

 

I am getting below error, after making index.php as my directory index.  Please help me I am depending on this solution a very lot.

 

HTTP Error 404.3 - Not Found

The page you are requesting cannot be served because of the extension configuration. If the page is a script, add a handler. If the file should be downloaded, add a MIME map.

Most likely causes:

It is possible that a handler mapping is missing. By default, the static file handler processes all content. 

The feature you are trying to use may not be installed. 

The appropriate MIME map is not enabled for the Web site or application. (Warning: Do not create a MIME map for content that users should not download, such as .ASPX pages or .config files.) 

If ASP.NET is not installed.

Things you can try:

In system.webServer/handlers: 

Ensure that the expected handler for the current page is mapped. 

Pay extra attention to preconditions (for example, runtimeVersion, pipelineMode, bitness) and compare them to the settings for your application pool. 

Pay extra attention to typographical errors in the expected handler line.

Please verify that the feature you are trying to use is installed. 

Verify that the MIME map is enabled or add the MIME map for the Web site using the command-line tool appcmd.exe. 
To set a MIME type, use the following syntax: %SystemRoot%\windows\system32\inetsrv\appcmd set config /section:staticContent /+[fileExtension='string',mimeType='string']
The variable fileExtension string is the file name extension and the variable mimeType string is the file type description.
For example, to add a MIME map for a file which has the extension ".xyz": appcmd set config /section:staticContent /+[fileExtension='.xyz',mimeType='text/plain']
Warning: Ensure that this MIME mapping is needed for your Web server before adding it to the list. Configuration files such as .CONFIG or dynamic scripting pages such as .ASP or .ASPX, should not be downloaded directly and should always be processed through a handler. Other files such as database files or those used to store configuration, like .XML or .MDF, are sometimes used to store configuration information. Determine if clients can download these file types before enabling them. 

Install ASP.NET. 

Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click here. 

Detailed Error Information:

ModuleStaticFileModule
NotificationExecuteRequestHandler
HandlerStaticFile
Error Code0x80070032

 

Requested URLhttp://localhost:80/index.php
Physical PathC:\inetpub\wwwroot\snipeit\public\index.php
Logon MethodAnonymous
Logon UserAnonymous

 

 

 

Thanks

Suresh Raja
