### ISSUE TITLE
Installation issue on Ubuntu

### ISSUE THREAD

**Issue by sureshdotbits** [snipe/snipe-it#3744]
#### Expected Behavior (or desired behavior if a feature request)
Snipe IT should be installed successfully
(what you expect to happen goes here)
login successfully
-----

#### Actual Behavior
Installation failed and application is not accessible
(what actually happens goes here)
Welcome to Snipe-IT Inventory Installer for Centos, Debian and Ubuntu!

  The installer has detected Ubuntu version 17.04 as the OS.
  Q. What is the FQDN of your server? (sargaha.c.extreme-battery-169306.internal): sargaha.c.extreme-battery-169306.internal
     Setting to sargaha.c.extreme-battery-169306.internal

  Q. Do you want me to automatically create the snipe database user password? (y/n) n
  Q. What do you want your snipeit user password to be?

* Adding MariaDB repo in the background... -
* Updating with apt-get update in the background... -

* Upgrading packages with apt-get upgrade in the background... \

* Setting up LAMP in the background... -
\
\
* Cloning Snipeit, extracting to /var/www/snipeit... \
* Create Virtual host for apache.
./snipeit.sh: line 57: /etc/apache2/sites-available/snipeit.conf: No such file or dir
ectory
* MySQL Phase next.
Unit mysql.service could not be found.
Failed to start mysql.service: Unit mysql.service not found.
./snipeit.sh: line 291: /usr/bin/mysql_secure_installation: No such file or directory
* Creating MySQL Database and user.
* Please Input your MySQL/MariaDB root password created in the previous step.: 
./snipeit.sh: line 293: mysql: command not found
* Securing Mysql
* Installing and configuring composer
./snipeit.sh: line 296: php: command not found
curl: (23) Failed writing body (0 != 16133)
./snipeit.sh: line 297: php: command not found
Failed to restart apache2.service: Unit apache2.service not found.
  ***If you want mail capabilities, edit /var/www/snipeit/.env and edit based on .env
.example***
  ***Open http://sargaha.c.extreme-battery-169306.internal to login to Snipe-IT.***
* Cleaning up...
* Finished!
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on  -->  The installer has detected Ubuntu version 17.04 as the OS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by sureshdotbits** [comment]
Please help me with the solution, practically i am stuck

**Comment by inakigoicolea** [comment]
It looks as if you don't have LAMP installed (apache2, MySQL and PHP) on your Ubuntu. Follow any of the many manuals that you easily find on internet on how to do that:

sudo apt-get update
sudo apt-get -y install apache2
sudo systemctl start apache2
sudo systemctl enable apache2
sudo apt-get -y install php php-pdo php-mbstring php-tokenizer php-curl php-mysql php-ldap php-zip php-fileinfo php-gd php-dom php-mcrypt
sudo apt-get -y install mariadb-server
sudo systemctl start mysql
sudo systemctl enable mysql

Let's take it from here
