### ISSUE TITLE
LDAP Authentication not working - can login with any password.

### ISSUE THREAD

**Issue by asmiah** [snipe/snipe-it#3745]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

Hi,

We have been running SnipeIT for a number of years, we recently discovered when logging in "LDAP" authenticated users can login with ANY password.

We have checked our ldap.php file located in **/var/www/html/app/config/production/ldap.php**

This does contain **'authentication.filter.query' => "samAccountName=",** as most people have complained about this - and saw this to be the solution.

When commenting out **'authentication.filter.query' => "samAccountName=",** Snipe doesn't allow the "LDAP" user to login (error username or password incorrect)- which indicates it's working - to some extent. A local Snipe account user however is able to login.

To note, when I log in with my "LDAP" username which in Active Directory is firstname.lastname in Snipe I'm having to use firstname.lastname@domain.com

When I comment out 

'result.username' => "samaccountname=",
'result.last.name'  => "sn=",
'result.first.name' => "givenname="

I am still able to login with the "LDAP" user.

LDAP is definitely working as our users which we check out our assets to is being picked up from Active Directory without any issue what so ever.

When I change the password for the "LDAP" user(s) in People->Search User->Edit Button->Generate

This password still doesn't work.

The version of Snipe is: (v2.0-175) running on Centos 6.7 (does this version support LDAP auth login? I have read here where mention is made that LDAP auth was not introduced until 2.4?? - https://github.com/snipe/snipe-it/issues/551)

Thank you for your time looking at my issue.

**Comment by snipe** [comment]
2.0 is pretty old, and a lot of things have changed with LDAP implementation. I would suggest upgrading your Snipe-IT instance.

**Comment by asmiah** [comment]
Hi Snipe,

Thank you for your prompt response - most appreciated.

Do you know what could be the cause of the issue/have you experienced something like this before?

**Comment by snipe** [comment]
I really couldn't say, unfortunately.
