### ISSUE TITLE
Number in Servername

### ISSUE THREAD

**Issue by Louis-Kre** [snipe/snipe-it#3746]
Hey guys,

we have an issue in the configuration.
Our new LDAP-Server has a number in his name, like "new-ldap1" and we get a error-message "The ldap server format is invalid."

If I change the dns name in the database manual, it works, but i can't save the configuration any more.

Is there a possibility to change that? We don't want to use ip-adresses in our system.

Thanks for your help.

**Comment by snipe** [comment]
I don't think the number should matter, but it *is* looking for a value URL. There's no currently any way around that.

**Comment by snipe** [comment]
Haven't heard back, so I'm going to close this ticket for now, but will re-open it if you're still having issues

**Comment by Louis-Kre** [comment]
Hey,
I found a solution just now. The message dissappears if you add your domain-name.
Thanks for you answers
