### ISSUE TITLE
Application is not accessible configured in Windows IIS

### ISSUE THREAD

**Issue by sureshdotbits** [snipe/snipe-it#3748]
Expected Behavior (or desired behavior if a feature request)

Home page should come while accessing http://localhost/
(what you expect to happen goes here)
getting error

Actual Behavior

(what actually happens goes here)
Hi, I have installed snipe it of version 3.0.0 and configured to work on IIS. Have installed on dependencies successfully but even then i am getting below error when I tried to open home page. Have attached web.config file with this issue.
HTTP Error 500.19 - Internal Server Error
The requested page cannot be accessed because the related configuration data for the page is invalid.
Detailed Error Information:
Module
   IIS Web Core
Notification
   Unknown
Handler
   Not yet determined
Error Code
   0x8007000d
Config Error
   
Config File
   \?\C:\inetpub\wwwroot\snipeit\public\web.config
Requested URL
   http://localhost:80/
Physical Path
   
Logon Method
   Not yet determined
Logon User
   Not yet determined

Config Source:
-1:
0:

Please confirm you have done the following before posting your bug report:

 I have enabled debug mode
 I have read checked the Common Issues page
Please provide answers to these questions before posting your bug report:

Version of Snipe-IT you're running --> 3.6.2

What OS and web server you're running Snipe-IT on --> Windows 10, IIS

What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) --> Manual

WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error --> Included above

What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error --> Home page itself is not coming

If a stacktrace is provided in the error, include that too.

Any errors that appear in your browser's error console.

Confirm whether the error is reproduceable on the demo. --> No
web-config.txt

Include any additional information you can find in app/storage/logs and your webserver's logs.

Include what you've done so far in the installation, and if you got any error messages along the way.

Indicate whether or not you've manually edited any data directly in the database

HTTP Error 403.14 - Forbidden

The Web server is configured to not list the contents of this directory.

Most likely causes:

A default document is not configured for the requested URL, and directory browsing is not enabled on the server.

Things you can try:

If you do not want to enable directory browsing, ensure that a default document is configured and that the file exists.

Enable directory browsing using IIS Manager.
Open IIS Manager.
In the Features view, double-click Directory Browsing.
On the Directory Browsing page, in the Actions pane, click Enable.
Verify that the configuration/system.webServer/directoryBrowse@enabled attribute is set to true in the site or application configuration file.

Detailed Error Information:

ModuleDirectoryListingModule
NotificationExecuteRequestHandler
HandlerStaticFile
Error Code0x00000000

Requested URLhttp://localhost:80/
Physical PathC:\inetpub\wwwroot\snipeit\public
Logon MethodAnonymous
Logon UserAnonymous

**Comment by YanKer1980** [comment]
I had the same problem...

**Comment by sureshdotbits** [comment]
@YanKer1980 what steps did you run to resolve the issue.
