### ISSUE TITLE
Auto Delete Users not in LDAP Source

### ISSUE THREAD

**Issue by worthy92** [snipe/snipe-it#3749]
#### Automatically delete users not in LDAP source
Hello,

This is a fantastic bit of software so just want to start off by saying thanks! :)

I was wondering if it's possible to automatically delete people in Snipe-IT as part of the LDAP sync. For example I work in education and we obviously have a huge turnover of students and staff every year and I would like to have the system automatically delete people that no longer appear in the LDAP source. The people would get deleted automatically if they don't have any assets assigned to them. Otherwise, they would get flagged as deleted but with assets still checked out.

I am hoping that this makes sense.

Thanks! :)

**Comment by rWaddles** [comment]
That is an interesting idea, personally I would rather it flagged only and not completed automated but we are only working with staff assets. 
I haven't tested what happens when a account is removed, have you?

**Comment by worthy92** [comment]
If you manually delete a person it it still visible by clicking "Show deleted users". That way audit trails/logs are still valid.

**Comment by wsidl** [comment]
Is this still an option? We deal with a lot of users starting and leaving and will need to know which assets have been assigned to users that have recently left. Since our process involves moving the AD accounts to a different group, the user accounts in SnipeIT should be removed if the source user account doesn't exist.

**Comment by chndler** [comment]
+1 I would like to see this feature, when people are gone from our LDAP server I would like to be able to prune accounts that are no longer present.

**Comment by stonehellway** [comment]
+1 It would be helpful if there were an indicator that the user was not in the AD anymore.

**Comment by triple-HA** [comment]
+1 It would be helpful if I delete a user from AD, after LDAP sync that account will be disabled - it shouldn't be deleted because of assign assets etc ;)

**Comment by RedhaIdrus** [comment]
+1 Delete or flag, anything would be great to facilitate in auto deletion of users that are deleted from LDAP source.

**Comment by SonGokussj4** [comment]
+1 Just looking for this functionality and found this thread. The same with departments would be awesome.

**Comment by sier** [comment]
+1 Still would really like this feature.
The whole point of using a separate account service is to not have to manage users for every application used.

**Comment by Mike-NP** [comment]
+1

**Comment by snipe** [comment]
Most folks are transitioning to SAML/SCIM, away from LDAP. This is a surprisingly challenging problem to solve via LDAP, since whatever behavior we choose, some subset of users will be expecting the opposite or different behavior.

**Comment by Zoran-Jankov** [comment]
It would be great if you implement automatic deletion of deleted users not found in the Active Directory.

**Comment by Zoran-Jankov** [comment]
> Most folks are transitioning to SAML/SCIM, away from LDAP. This is a surprisingly challenging problem to solve via LDAP, since whatever behavior we choose, some subset of users will be expecting the opposite or different behavior.

Yet lot of companies are still relining on LDAP and Active Directory.

**Comment by dcacija** [comment]
Hi all,
Thanks for the update. Echoing others, automatic user deletion via LDAP sync is crucial for us too. While SAML/SCIM is gaining traction, LDAP remains vital for many. Configurable auto-deletion with safeguards would be amazing! Happy to test/contribute.

**Comment by yetanothersys-admin** [comment]
+1 was just making a list of the users that recently left the company - the "auto-delete" would be a good feature (a script or command that can be used manually / via scheduled task would suffice as well)

**Comment by conceptualcontinuity** [comment]
Considering that Snipe-IT has an API :
should it be possible to create a cron job that checks LDAP/AD users with the same LDAP filter used in Snipe-IT, compares with users in Snipe-IT and removes/disables/tags or whatever the users that are misssing or disabled in LDAP/AD ?
Anyone who has tried this?

**Comment by jeramifrost** [comment]
I am down for a cron job if someone knows how to do it. I was hoping by now this would have been something that could be left off for those who didn't want it or turned on/configured for those who did. However, i do not know anything about how thats all done on the backend or how feasible this request is, but it would be great to not have to always delete users out, but instead have that automated like our other systems that sync with AD.

**Comment by goni-Seoul** [comment]
Any update about this??
This is really essential

**Comment by jamoritch** [comment]
+1 if this is ever available

**Comment by uberbrady** [comment]
The only way we can really do this is with a full refactor of the LDAP functionality. It's definitely something we're talking about. But the problem arises where if you are doing multiple CLI-syncs, a user might show up in one sync, and not in another - we might try to incorrectly delete them.

**Comment by rfpg1** [comment]
updates?

**Comment by snipe** [comment]
@rfpg1 If there were, you'd have seen them here.
