### ISSUE TITLE
Snipe-it agent for windows/linux/mac

### ISSUE THREAD

**Issue by rechinu007** [snipe/snipe-it#3751]
Hi everyone,

Is there any agent which can be installed on windows/linux/mac to autoinvetory the hardware and software of computers or each asset should be inserted manually into snipe-it web interface?

Thanks

**Comment by snipe** [comment]
Currently assets are all added manually. While we do not have plans to create an agent, the upcoming API should be able to work with existing agents that allow API integration with third party systems.

**Comment by passboltUser** [comment]
Yeah, having an API with which other Agents can be tested is good and maybe you won't need to code your own agent. Maybe you could mention/recommend some agents. Would `OCS Inventory NG` work? Can a CMD- / PowerShell-script be used as an agent and access the new API? At our company I use a `.bat` script through GPO to scan for installed software, now if I could access the API and import the data within the `.bat` into Snipe-IT, instead to a file or manually importing it, that would be cool.
(Showing the installed software is easy BTW: `wmic product get Name,Version`. Now one only needs to be able to use the API and import this data to Snipe-IT.)

**Comment by mfestrada** [comment]
@snipe was this rolled out in v4?  My company would like to start using Snipe-IT but since inventorying like posed OP's post is missing, we're playing with integration ideas before deploying it.  Not sure what the api looked like before the last release, so forgive me if this is an obtuse question. -_-;

**Comment by tgferreira3** [comment]
This is something that I'd really like to see! And it would make SnipeIT as an even better alternative to GLPI + FusionInventory, etc!

**Comment by modist** [comment]
any progress of this ? - currently considering implementing Snipe-it - but not with out an agent.

**Comment by ander-san** [comment]
> any progress of this ? - currently considering implementing Snipe-it - but not with out an agent.

We're on the same boat. I would like to use snipe-it, but I need an agent or, at least, find a way to integrate it to existing agents (OCS, Fusion, etc...)

**Comment by ciroiriarte** [comment]
Best route would be a connector that receives FusionInventory data a pushes it to SnipeIT using the API

**Comment by hdrkhls** [comment]
@ciroiriarte how i can using fusioninventory for agent snipe-it ?
