### ISSUE TITLE
Request: Asset tag generation on CSV import

### ISSUE THREAD

**Issue by rWaddles** [snipe/snipe-it#3752]
When importing a Asset list in bulk (say from an old system or a new bulk buy) would be nice for those who are auto generating tag IDs for it to do so instead of doing it one by one.

-----

#### Actual Behavior

"Error: Some items did not import correctly."
The asset tag field is required.
-----

**Comment by snipe** [comment]
Closing as duplicate of #3559 and #2521. Per the comments there, generating them in Excel is the easiest workaround.
