### ISSUE TITLE
Snipe-IT on one sub folder for IP based web server

### ISSUE THREAD

**Issue by rajah7** [snipe/snipe-it#3755]
Hi,

Thanks snipe for such a useful app. 

My situation is taht i'm trying to install Snipe-It on a internal network(LAN). The existing server is accessed by IP address, no domain. It already hosted some web-based application.

I'm planning to install Snipe-IT as sub folder of the server such as http://192.168.0.1/snipeIT/

Until this moment, i would end up getting error "D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory."

However, i did managed to installed it as a single application on the server. I also managed to installed in with virtual IP or port based virtual hosting.

Please help me in installing it as the sub folder http://192.168.0.1/snipeIT/

**Comment by snipe** [comment]
Please see the documentation for installing Snipe-IT ina  subdirectory here: https://snipe-it.readme.io/docs/subdirectories
