### ISSUE TITLE
Feature Request - License Exipery Dates

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#3757]
#### Desired Behavior (or desired behavior if a feature request)

Expired licenses to not have to be discarded from the system, rather have the license report sort "expired" and "to be expired" licenses with custom statuses "expired" and "active"

-----

#### Actual Behavior

All licenses, expired or not show up on the license report, which is usable, but is difficult to "at a glance" determine what licenses if any are coming due for renewal or are past. 

To hide expired licenses (or licenses renewed with pack licensing) the original license asset must be deleted from the system. 

#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
3.6.6
- What OS and web server you're running Snipe-IT on
CentOS7 - Used the installation script, updated using GIT with recent change. 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/a
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
N/A
- If a stacktrace is provided in the error, include that too.
N/A
- Any errors that appear in your browser's error console.
N/A
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
N/A
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
N/A
- Include what you've done so far in the installation, and if you got any error messages along the way.
N/A
- Indicate whether or not you've manually edited any data directly in the database
I haven't

**Comment by Jarli01** [comment]
Any possibility of getting this rolled out, or even a simple "Expired" option for licenses that are expired.

**Comment by captain-hack** [comment]
Or even if we had an email notification that went out a certain time frame before the license expired.

**Comment by snipe** [comment]
@captain-hack License expiration alerts already exist. https://snipe-it.readme.io/docs/notifications#section-email-alerts-enabled

**Comment by captain-hack** [comment]
Then i'm having other issues that I will need to investigate. Thanks!

**Comment by mfsid** [comment]
Just to bombard you all with the same content as mentioned in #8799 here are my few suggestions on the matter.

*It would be easier to Archive licenses when the Current date has passed without user Intervention.
*License count on the main dashboard should only display count for active licenses.
*Current option that says Maintained can be used to deduce whether the license is active or not. Not maintained license = inactive.
*A tag or color code can be assigned to the license. Green = active, yellow/orange = expiring in 1 month, red = inactive
