### ISSUE TITLE
Cannot Download Asset Reports in Microsoft EDGE

### ISSUE THREAD

**Issue by jarbro** [snipe/snipe-it#3758]
#### Expected Behavior (or desired behavior if a feature request)

Click on the download icon to the left of the search box in an Asset Report and select CSV.  Report should download based on visible columns. 

-----

#### Actual Behavior

EDGE Browser just stalls - nothing happens.

-----

#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.6.6 build 1 (gee2c67a)
- Ubuntu 14.04.5 LTS
- GIT Pull
- WITH DEBUG TURNED ON: N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: reports/assets Download Icons > CSV
- Any errors that appear in your browser's error console: HTML1527: DOCTYPE expected. Consider adding a valid HTML5 doctype: "<!DOCTYPE html>".
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): YES
- Indicate whether or not you've manually edited any data directly in the database: NO

FYI Client OS is Edge on Windows 10 1607 & Windows 10 1703.

**Comment by snipe** [comment]
Can you see if this issue exists on the development demo? https://develop.snipeitapp.com (`admin`/`password`)

**Comment by jarbro** [comment]
Not sure if it's the developer site or not, but I cannot load the Asset page (multiple browsers.) It just spins with Loading... please wait...  I was able to download a CSV from the license page on developer.snipeitapp.com via EDGE which did not work on 3.6.6 b 1 (gee2c67a)

**Comment by snipe** [comment]
@jarbro great - looks like this issue is fixed then - thanks!
