### ISSUE TITLE
Feature Request - Search assets based on multiple search criteria

### ISSUE THREAD

**Issue by ntollison** [snipe/snipe-it#3759]
#### Expected Behavior (or desired behavior if a feature request)

I need to be able to search assets based on multiple search criteria at once to get reports based on things like location+model or location+category or model+order number.
-----

#### Actual Behavior

Currently I can only search one at a time. This limits granular reporting and forces you to pull everything from on location or model and then open the exported file in Excel to further sort the specific assets you need in the report.
-----

#### Please confirm you have done the following before posting your bug report:

- [ N/A] I have enabled debug mode
- [Yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
3.6.6
- What OS and web server you're running Snipe-IT on
Debian
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Multi search for assets is already available in the upcoming v4
