### ISSUE TITLE
Can't do backups

### ISSUE THREAD

**Issue by earanaus** [snipe/snipe-it#3761]
#### Expected Behavior (or desired behavior if a feature request)

When I do backup, I get error: Whoops, looks like something went wrong.

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

-  v3.6.6 build 1  
- Linux Ubuntu
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
FatalErrorException in Zip.php line 38:
 Class 'ZipArchive' not found
in /var/www/snipeit/vendor/spatie/laravel-backup/src/tasks/backup/zipphp:38

**Comment by snipe** [comment]
PHP needs to have the zip extension installed/enabled. http://www.php.net/manual/en/book.zip.php

**Comment by earanaus** [comment]
I do it, install, php with imap extension, but not working, error left..

**Comment by earanaus** [comment]
Hm.. I install php-zip extension, but still get error:
**FatalErrorException in Zip.php line 38:
 Class 'ZipArchive' not found**

**Comment by snipe** [comment]
Did you restart the web server?

**Comment by earanaus** [comment]
Yes, afcourse restart many time



Išsiųsta iš „Samsung Galaxy“ išmaniojo telefono.


-------- Originali žinutė --------
Iš: snipe <notifications@github.com>
Data: 2017-07-30 02:00 (GMT+02:00)
Kam: snipe/snipe-it <snipe-it@noreply.github.com>
Kopija: Egidijus Aranauskas <earanaus@intercars.eu>, Author <author@noreply.github.com>
Tema: Re: [snipe/snipe-it] Can't do backups (#3761)


Did you restart the web server?
