### ISSUE TITLE
Update Translations

### ISSUE THREAD

**Issue by jfwiebe** [snipe/snipe-it#3762]
Hi! Is it possible to review current translation changes and merge them into the project? Especially in the German translation, there are many good translations waiting to be reviewed and merged into master branch which would massively improve the translation quality.

Thank you!
Jan Felix

**Comment by snipe** [comment]
We update and merge all translations periodically, however we will not be merging any into the current master branch, as they could potentially conflict with the develop branch, which contains the upcoming v4 code.  In the future, we hope to be able to manage widely varying branches branches more efficiently in CrowdIn
