### ISSUE TITLE
Update from 3.0 to latest - Hangs on Compiling common classes

### ISSUE THREAD

**Issue by RichrdJ** [snipe/snipe-it#3764]
#### Expected Behavior (or desired behavior if a feature request)

Entering the commands like written on the releases, update succeeded?

-----

#### Actual Behavior

First i copied over the files from snipe-it-3.6.6.zip over to the install directory /var/www/snipeit

After this is send the command first: `php composer.phar install --no-dev --prefer-source`
And this is the output:

```
/var/www/snipeit$ php composer.phar install --no-dev --prefer-source
Cannot create cache directory /home/administrator/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/administrator/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating autoload files
> php artisan clear-compiled
> php artisan optimize
Generating optimized class loader
Compiling common classes
```
I've copied the files over with WINSCP on Windows 

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version 3.0, can't check, snipe IT is dead
- Ubuntu 14.04.4 LTS with Apache 5 
- What upgrade method https://snipe-it.readme.io/v3.6.2/docs/upgrading

**Comment by snipe** [comment]
My guess would be permissions issues, based on the error messages.

> I've copied the files over with WINSCP on Windows

Copied over which files, exactly?
