### ISSUE TITLE
Something went wrong. The server returned an error. Check your mail settings in your .env file, and check your storage/logs for additional information..

### ISSUE THREAD

**Issue by devgnu9** [snipe/snipe-it#3766]
#### Send an email for testing the service
I have an internal mail server and i want to send mails inside my network so I put the values on the .env file ../snipeit/.env but still sending me an error
I already check the /storage/log/laravel.log file and I don't understand what does it means, it says
"#106 {main}"
MAIL_DRIVER=smtp
MAIL_HOST= the name of my email server
MAIL_PORT=25
MAIL_USERNAME=the user name of my email server
MAIL_PASSWORD=the password of that account 
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=the user name of my email server
MAIL_FROM_NAME='Snipe-It'
MAIL_REPLYTO_ADDR=the user name of my email server
MAIL_REPLYTO_NAME='Snipe-IT'

would you please tell me if that info is correct?

[] I have enabled debug mode
[*] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Comment by snipe** [comment]
`MAIL_REPLYTO_ADDR=the user name of my email server`

This should be an email address, not a username. 

Additionally, please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
