### ISSUE TITLE
[v4] Button to save own profile does not work

### ISSUE THREAD

**Issue by jasonspriggs** [snipe/snipe-it#3770]
#### Expected Behavior (or desired behavior if a feature request)

Hitting either the Save button or Enter/Return should save your profile.

-----

#### Actual Behavior

Both the Save button and hitting Enter/Return do not post the information to the save endpoint.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - develop latest
- What OS and web server you're running Snipe-IT on - CentOS 6.7, Apache 2.4, PHP 5.6.30
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Install.sh w/ upgrade via git
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - no error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - The Save button on /account/profile
- Any errors that appear in your browser's error console. - No error. No request made to any endpoint
- Confirm whether the error is [reproduceable on the demo] - Yes, the develop demo

**Comment by snipe** [comment]
Fixed on dev - thanks!
