### ISSUE TITLE
Request for assigned_to 'username' attribute in asset search API response  

### ISSUE THREAD

**Issue by matc** [snipe/snipe-it#3771]
#### Expected Behavior (or desired behavior if a feature request)

In 4.0 API when making an asset search, it would be great for the `assigned_to` response block to also include `username`.  I am requesting this so we can leverage our LDAP/AD integrations in  SnipeIT, Jamf and BigFix with username as a common attribute.

-----

#### Actual Behavior

Currently `assigned_to` returns first_name/last_name/id/name attributes.  

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 4.0
- What OS and web server you're running Snipe-IT on Debian
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Fix is on dev :)

**Comment by matc** [comment]
suuuper fast! that's great news 🥇 
thanks snipe!
