### ISSUE TITLE
[v4 API] Data Type Discrepancies

### ISSUE THREAD

**Issue by jasonspriggs** [snipe/snipe-it#3774]
Hello! I have done a fairly thorough run through of the known API endpoints and have found a number of fields that either return a blank string when a field is empty instead of null, or contain an integer value inside of quotes (as if a string) instead of as an integer.

- accessories
- [x] company (when empty: returns "", should return null)
- [x] manufacturer (when empty: returns "", should return null)
- [x] location (when empty: returns "", should return null)
- [x] min_qty (when has a value: returns string, should return an int)

- components
- [x] qty (when has a value: returns string, should return an int)
- [x] min_qty (when has a value: returns string, should return an int)

- licenses
- [x] total_seats (when has a value: returns string, should return an int)

- locations
- [x] parent_id (when empty: returns "", should return null)
- [x] parent_id (when has a value: returns string, should return an int)

- manufacturer
- [x] assets_count/licenses_count/accessories_count/consumables_count (returns string, should return an int)

- users
- [x] manager (when empty: returns "", should return null)
- [x] assets_count/licenses_count/accessories_count/consumables_count (when empty: returns null, should return 0, this only happens when you go to /users/<id>)

**Comment by snipe** [comment]
Great work on this - thanks! (I was going to go through all of this and test for consistency as well, and add some tests for this stuff - much appreciated.)

**Comment by snipe** [comment]
Re: components `qty`, we're doing `number_format` on that before returning it, so it shouldn't be a string. Can you double check?

**Comment by jasonspriggs** [comment]
Appears to still be so 
<img width="290" alt="screen shot 2017-07-26 at 2 11 58 am" src="https://user-images.githubusercontent.com/16108587/28607014-e281c9b6-71a7-11e7-8bf6-5e035e10a0aa.png">

**Comment by snipe** [comment]
Fixes are on dev
