### ISSUE TITLE
[v4 API] created_time and updated_time are not displayed

### ISSUE THREAD

**Issue by jasonspriggs** [snipe/snipe-it#3775]
On a number of functions inside of the api, the created_at and updated_at fields are returning null instead of a datetime object on other objects.

The endpoints that do this are:
- [ ] suppliers
- [ ] groups
- [ ] departments

Additionally, the created_at and updated_at fields are completely missing from:
- [ ] field
- [ ] fieldset
- [ ] asset models

**Comment by snipe** [comment]
Is this something you actually need?

**Comment by jasonspriggs** [comment]
Yes, the SDK is extending a basic object that contains the object's ID, a name, created_at, and updated_at times.

Field and fieldset don't need a created_at time, but do need an updated_at time. Asset models need both.

**Comment by jasonspriggs** [comment]
Also the database has fields for these, so no reason not to? If you'd like, i can do the code for it, seems straightforward.

**Comment by snipe** [comment]
Fixed on dev
