### ISSUE TITLE
User file upload not working

### ISSUE THREAD

**Issue by oli415** [snipe/snipe-it#3782]
#### Expected Behavior (or desired behavior if a feature request)

When clicking on a user and choosing a file to be uploaded, it should actually be uploaded.

-----

#### Actual Behavior

The file upload is stuck at 0% complete.

-----

#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.6.6 build 1 (gee2c67a)
- What OS and web server you're running Snipe-IT on: Debian/Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: no error shown
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: /admin/users/x/view: files_tab: Select File...
- Any errors that appear in your browser's error console:

view:100 Mixed Content: The page at 'https://x/admin/users/349/view' was loaded over HTTPS, but requested an insecure image 'http://x/uploads/logo.jpg'. This content should also be served over HTTPS.
jQuery-2.1.4.min.js:4 Mixed Content: The page at 'https://x/admin/users/349/view' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://x/api/users/349/upload'. This request has been blocked; the content must be served over HTTPS.
send @ jQuery-2.1.4.min.js:4
ajax @ jQuery-2.1.4.min.js:4
send @ jquery.fileupload.js:906
_onSend @ jquery.fileupload.js:968
(anonymous) @ jquery.ui.widget.js:126
data.submit @ jquery.fileupload.js:674
(anonymous) @ jquery.fileupload.js:218
j @ jQuery-2.1.4.min.js:2
add @ jQuery-2.1.4.min.js:2
add @ jquery.fileupload.js:217
_trigger @ jquery.ui.widget.js:518
(anonymous) @ jquery.fileupload.js:1037
each @ jQuery-2.1.4.min.js:2
_onAdd @ jquery.fileupload.js:1030
(anonymous) @ jquery.ui.widget.js:126
(anonymous) @ jquery.fileupload.js:1229
j @ jQuery-2.1.4.min.js:2
add @ jQuery-2.1.4.min.js:2
always @ jQuery-2.1.4.min.js:2
_onChange @ jquery.fileupload.js:1219
(anonymous) @ jquery.ui.widget.js:126
handlerProxy @ jquery.ui.widget.js:435
dispatch @ jQuery-2.1.4.min.js:3
r.handle @ jQuery-2.1.4.min.js:3

Note that Uploads/logo.jpg is NOT the file i tried to upload.

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo):
On the demo the bar goes to 100% but no file is shown, idk if this is because it's only the demo or if it's not working for me.
- Include what you've done so far in the installation, and if you got any error messages along the way:
updated Version to 3.6.6
- Indicate whether or not you've manually edited any data directly in the database: no

**Comment by snipe** [comment]
Check that your APP_URL is set to https in your .env file

**Comment by oli415** [comment]
Thank you very much! :)
Another question: Is it somehow not permitted to upload a txt file containing html Code? Just for testing purposes I noticed that it wouldn't actually upload it if it contained sth like "<table>".

**Comment by oli415** [comment]
/<table/>

**Comment by snipe** [comment]
Only certain file types are permitted for security purposes
