### ISSUE TITLE
Snipe-IT not logging out after PC Restart, forced Browser Closed.

### ISSUE THREAD

**Issue by JacquesM7** [snipe/snipe-it#3783]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

**Once new browser is open for the first time, it will ask you for log in credentials**

#### Actual Behavior

System does not ask for user credentials and remembers last user even after PC restart, new google chrome browser opening or new tab.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running = **v3.6.6 build 1**
- What OS and web server you're running Snipe-IT on = **Ubuntu 16, hosted on Digital Ocean**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) = **Manual Install**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
= **dashboard (resources/views/dashboard.blade.php)
2
blade
layouts.default (resources/views/layouts/default.blade.php)
12
blade
notifications (resources/views/notifications.blade.php)
15
blade**

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
What do you have for your session config?
https://snipe-it.readme.io/docs/configuration#section-optional-session-settings

**Comment by JacquesM7** [comment]
Hello,

Apologies for the delay. Here are the settings.

# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_LIFETIME=5400
EXPIRE_ON_CLOSE=true
ENCRYPT=false
COOKIE_NAME=snipeit_session
COOKIE_DOMAIN=
SECURE_COOKIES=true

**Comment by snipe** [comment]
What browser(s) are you able to reproduce this on? If it's only Chrome, this may be a Chrome "feature". https://stackoverflow.com/questions/22713483/laravel-expire-session-on-browser-close-not-working-in-chrome

**Comment by snipe** [comment]
Haven't heard back, so I'm going to close this ticket for now, but will re-open it if you're still having issues
