### ISSUE TITLE
DropDown option for Purchase Cost or how to define different country prices

### ISSUE THREAD

**Issue by knspradeep** [snipe/snipe-it#3785]
#### Expected Behavior (or desired behavior if a feature request)
DropDown option for Purchase Cost 
(what you expect to happen goes here)
Expecting i can select price option whether i have purchased assets in dollars or Indian rupee (USD,INR,EUR)
-----

#### Actual Behavior
Currently, it is taking by default USD too diffcult to track if we add with numbers when they are in INR.
(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode
- [yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 
  Version v3.6.3 build 15 (g1bf34d7)
- What OS and web server you're running Snipe-IT on
Ubuntu 16.10
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
 install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
 yes
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
It's Feature not a bug
- Any errors that appear in your browser's error console.
Nothing
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Currency is managed in Admin > Settings and can be override by Locations by assigning a currency to a specific location
