### ISSUE TITLE
[v4 UI] Cannot checkout components via web interface

### ISSUE THREAD

**Issue by jasonspriggs** [snipe/snipe-it#3786]
Currently, the web interface does not have a button to checkout a component to an asset. This should get added in.

<img width="1220" alt="screen shot 2017-07-26 at 9 35 46 am" src="https://user-images.githubusercontent.com/16108587/28624081-f080d988-71e5-11e7-8557-bfd0ee4f2117.png">

**Comment by snipe** [comment]
Fixed on dev - thanks!
