### ISSUE TITLE
[v4 UI] Location parent is not displayed in Location Listing

### ISSUE THREAD

**Issue by jasonspriggs** [snipe/snipe-it#3790]
Inside of the web interface, when a location has a parent location, it does not get displayed in the listing.

<img width="1217" alt="screen shot 2017-07-26 at 1 59 03 pm" src="https://user-images.githubusercontent.com/16108587/28636417-0cba7192-720c-11e7-9cf0-d0430ebf51e1.png">

**Comment by snipe** [comment]
Fixed on dev - thanks!
