### ISSUE TITLE
Can't do backup

### ISSUE THREAD

**Issue by earanaus** [snipe/snipe-it#3793]
When I try generate backup I get error: 
Whoops, looks like something went wrong.
1/1 
**FatalErrorException in Zip.php line 38:**
 
**Class 'ZipArchive' not found**
-----

**I already install php-zip, libzip, zlib..**

after command php --ri zip 
I get:

zip
Zip => enabled
Zip version => 1.13.5
libzip version => 1.1.2

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version:  
Snipe-IT version v3.6.6 build 1 (gee2c67a)  
PHP Version 5.6.31-1~ubuntu16.04.1+deb.sury.org+1 
Laravel Version 5.2.45  

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
**FatalErrorException in Zip.php line 38:**
 
**Class 'ZipArchive' not found**

**Comment by snipe** [comment]
https://stackoverflow.com/a/3872578/200021
