### ISSUE TITLE
Customizing code

### ISSUE THREAD

**Issue by oli415** [snipe/snipe-it#3795]
#### Expected Behavior (or desired behavior if a feature request)

I would like to modify certain files (for example translations that I would like to adapt) and keep those changes when doing an upgrade. Is this somehow possible already or would it be possible to add this feature?

-----

#### Actual Behavior

If I just change a file and do an update (replacing all files), the changes are lost and I would have to implement them every time I make an update.

**Comment by jasonspriggs** [comment]
Your best bet is to fork the repository and make your changes in your fork. When a new version comes out, you pull from upstream (the snipe/snipe-it repo) into your fork. If there are conflicting changes, you'll need to merge it in manually.
