### ISSUE TITLE
How to add eula text to the print form

### ISSUE THREAD

**Issue by dedeoglumrt** [snipe/snipe-it#3798]
**We would like to add eula text to the print form for singnin by the user.

And it is possible to remove the following entry from the print form
Snipe-IT (https://snipeitapp.com) is an open source project, made with  by @snipeyhead (https://twitter.com/snipeyhead).

Regards**

**Comment by raakhtar** [comment]
Yes you can, goto Resources > View > Layout > default.blade...php file

Comment the <footer></footer> part

**Comment by snipe** [comment]
@dedeoglumrt The EULA text appears on the digital signing page if you have it enabled in the category.

<img width="864" alt="screen shot 2017-08-22 at 3 07 10 pm" src="https://user-images.githubusercontent.com/197404/29589818-a385967a-874b-11e7-8ea9-08f64eb19bc8.png">


@raakhtar - while it's certainly possible to remove the credit from the app, we would obviously prefer folks leave credit in where credit is due. (Additionally, those changes will have to be re-applied every time the app is updated.)
