### ISSUE TITLE
[v4 API] Invalid datetime response for calls

### ISSUE THREAD

**Issue by jasonspriggs** [snipe/snipe-it#3799]
Calls to companies, suppliers, and manufacturers, return created_at and updated_at strings, for example:

`"created_at": "2017-07-25 12:26:44",`

when they should return objects such as:

`"created_at": {
  "datetime": "2017-07-25 12:26:44",
  "formatted": "2017-07-25 12:26PM"
},`

Note: this only happens when querying a single object, not if you do a listing.

**Comment by jasonspriggs** [comment]
I've done a bit of digging and this rabbit hole seems to keep getting bigger.

While ManufacturersTransformer calls `'created_at' => Helper::getFormattedDateObject($manufacturer->created_at, 'datetime'),`, just like every other <Type>Transformer, it appears that it is not actually calling the App\Helpers\Helper class. Confirmed by commenting out the `$settings = Setting::getSettings();` line in the Helper::getFormattedDateObject function and then making the api call to both a working function (/hardware), which throws an error about $settings missing, and the broken function (/manufacturers), which still returns the incorrect value.

**Comment by snipe** [comment]
Is this for the listing pages or an individual?

This is my API response for companies listing:

```
{
    "total": 4,
    "rows": [
        {
            "id": "4",
            "name": "Kozey Ltd",
            "created_at": {
                "datetime": "2017-04-27 04:24:15",
                "formatted": "Thu Apr 27, 2017 4:24AM"
            },
            "updated_at": {
                "datetime": "2017-04-27 04:24:15",
                "formatted": "Thu Apr 27, 2017 4:24AM"
            },
            "assets_count": 106,
            "licenses_count": 129,
            "accessories_count": 112,
            "consumables_count": 140,
            "components_count": 102,
            "users_count": 16,
            "available_actions": {
                "update": true,
                "delete": true
            }
        }
    ]
}
```

Can confirm the issue on suppliers, but manufacturers looks like:

```
{
    "total": 10,
    "rows": [
        {
            "id": 1,
            "name": "Roberts LLC",
            "url": "",
            "support_url": "",
            "support_phone": "",
            "support_email": "",
            "assets_count": 0,
            "licenses_count": 0,
            "consumables_count": 0,
            "accessories_count": 37,
            "created_at": {
                "datetime": "2017-04-27 04:24:15",
                "formatted": "Thu Apr 27, 2017 4:24AM"
            },
            "updated_at": {
                "datetime": "2017-04-27 04:24:15",
                "formatted": "Thu Apr 27, 2017 4:24AM"
            },
            "available_actions": {
                "update": true,
                "delete": true
            }
        }
    ]
}
```

**Comment by snipe** [comment]
Never mind - I should learn to read. Sorry.

**Comment by snipe** [comment]
Fixed on dev - good catch, as always!

**Comment by jasonspriggs** [comment]
Just realized in my tests that this also applies to categories. Should be reopened
