### ISSUE TITLE
[v4 API] Creating a new asset returns a non-standard payload

### ISSUE THREAD

**Issue by jasonspriggs** [snipe/snipe-it#3803]
When POSTing to /hardware to create an asset, the response is `{
    "status": "success",
    "payload": 8,
    "messages": "Asset created successfully. :)"
}`.

Most, if not all, other API responses return an object in the payload instead (which should probably be the case): 

`{
    "status": "success",
    "payload": {
        "name": "Test",
        "updated_at": "2017-07-31 01:07:38",
        "created_at": "2017-07-31 01:07:38",
        "id": 6
    },
    "messages": "Company created successfully."
}`

**Comment by carlashley** [comment]
@jasonspriggs - I'm curious how you're successfully creating an asset with the API, I've had no luck.
Trying to get it working within a python script and with the `requests` module.
