### ISSUE TITLE
[v4 API] Creating a API object does not return an ID

### ISSUE THREAD

**Issue by jasonspriggs** [snipe/snipe-it#3808]
When creating an API object, the API returns `{"status":"success","payload":{"name":"Test","updated_at":"2017-07-31 06:11:05","created_at":"2017-07-31 06:11:05","id":7},"messages":"Company created successfully."}` which does not include an `id` field.

This happens for:

- [ ] categories
- [ ] companies

**Comment by snipe** [comment]
`{"name":"Test","updated_at":"2017-07-31 06:11:05","created_at":"2017-07-31 06:11:05","id":7}`

Isn't the last field the id field? In this case, `7`?

**Comment by jasonspriggs** [comment]
I appear to be blind. :P SDK didn't like one thing i did, but it's fixed now. My bad.
