### ISSUE TITLE
Has anyone been able to connect to an Azure AD based ldap? 

### ISSUE THREAD

**Issue by maxr786** [snipe/snipe-it#3810]
#### Expected Behavior (or desired behavior if a feature request)
I am trying to connect snipe-it currently running on a Linux VM hosted on MS Azure to an Azure based AD LDAP service. Based on the information (verified using ldp.exe on a windows machine) it should connect right away, but It doesn't. 

-----

#### Actual Behavior

After filling in all the information in the LDAP section of the settings. When I click "Test LDAP" I get an error, "Could Not Bind to LDAP: Can't contact LDAP Server" 

-----

#### Please confirm you have done the following before posting your bug report:

- [] I have enabled debug mode
- [C ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running ---> I am running Version 3.6.6 build 1
- What OS and web server you're running Snipe-IT on ----> Linux Ubuntu 14.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) ---> Install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error ----> I am just using TEST LDAP button on the settings page to test the LDAP connection.
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

More info: 
I am using the public IP for the LDAP server. I am using LDAPS with port 636. Below are two images that show the information I put in LDAP settings. 

Image 1: http://imgur.com/a/uiCUP
Image 2: http://imgur.com/a/uiCUP

**Comment by jasonspriggs** [comment]
Try checking the Use TLS checkbox then attempt reconnection to see if that works.

**Comment by maxr786** [comment]
@jasonspriggs thanks for your reply. I tried that, and it didn't work.

**Comment by maxr786** [comment]
Just an update: I figured it out. 
For anyone who wants to connect to Azure AD to snipe-it, they must follow the instructions below: 
Enable LDAP: Check 
This is an Active Directory Server: Check 
LDAP Password Sync Yes: Check 
Active Directory Domain: Put Domain Here
LDAP Server: Should exactly be like this: LDAP://PrivateIP:389 (Do not use LDAPS, Port 636, or Public IP)
USE TLS: Do Not Check 
LDAP Bind Username: Just username such as "Admin" (NO CN, OU, DC needed) 
LDAP Bind Password: provide password here 
Base Bind DN: DC = Domain, DC = Com
Leave everything else as default.

**Comment by snipe** [comment]
Awesome, thanks!

**Comment by shandorcoachman** [comment]
This is confusing a bit:
"Should exactly be like this: LDAP://PrivateIP:389 (Do not use LDAPS, Port 636, or Public IP)"

Azure AD is a public service, what do you mean by do not use its public IP? I need to integrate a hosted Snipe-IT with Azure AD, is this possible the same way as described above?

**Comment by AMG-90** [comment]
anyone can share a snapshot of his ldap int with azure AD ? 
having some troubles with this one

**Comment by AMG-90** [comment]
my SnipeIT is in amazon and i use Azure AD
