### ISSUE TITLE
LDAP authentication issue 

### ISSUE THREAD

**Issue by cb72egh** [snipe/snipe-it#3812]
#### Expected Behavior (or desired behavior if a feature request)

I'd like to be able to log in using AD credentials 

-----

#### Actual Behavior

error:   LDAP user (valid user id here)  not found in LDAP or could not bind
[2017-08-01 14:08:59] production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running    v3.6.6 build 1
- What OS and web server you're running Snipe-IT on   OEL 7.3  apache 2.4.6-45
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error    I do not get an error , i fall back to a local user account 
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error   Login page 
- If a stacktrace is provided in the error, include that too.   No stack trace, just a message in the log 
- Any errors that appear in your browser's error console.   no errors in console
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).  n/a
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
[2017-08-01 14:08:11] production.DEBUG: Authenticating user against database.
[2017-08-01 14:08:59] production.DEBUG: LDAP is enabled.
[2017-08-01 14:08:59] production.DEBUG: Binding user to LDAP.
[2017-08-01 14:08:59] production.DEBUG: LDAP user (redacted) not found in LDAP or could not bind
[2017-08-01 14:08:59] production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory

- Include what you've done so far in the installation, and if you got any error messages along the way.
tried https://github.com/snipe/snipe-it/issues/3234 suggested fix 
tried reproducing ldap connection using ldapsearch in the os .. I can connect using the same values listed in the ldap config panel  at the command line successfully 

- Indicate whether or not you've manually edited any data directly in the database   no 
![issue_1](https://user-images.githubusercontent.com/29634811/28840566-663760d2-76c5-11e7-96df-6f54a2ba30b3.png)

**Comment by thurban** [comment]
Hi,

I had the very same issue but was able to solve it by setting the "LDAP Authentication query" to "sAMAccountName=".  So try removing the asterisk (*) after the equal sign

**Comment by cb72egh** [comment]
Tried the suggestion listed above .. I do not see the expected authentication
