### ISSUE TITLE
Is it possible to use a Honeywell Xenon 1900 scanner to do bulk check-in or check-out?

### ISSUE THREAD

**Issue by davidkillingsworth** [snipe/snipe-it#3813]
#### Expected Behavior (or desired behavior if a feature request)

We have an IT equipment rental shop that frequently needs to check out 50 or 100 devices at a time.

We would like to do a bulk check out and bulk check in multiple devices all at once.

Is there a way that we can quickly check-in a device just by scanning it with a Honeywell Xenon 1900 USB scanner?  We can scan with a mobile phone, but all it does it open the URL of the device on the mobile phone.

What about bulk check-out?  We see the bulk check-out option in the menu and we see that we can select user, check out date, and Assets field.  Is there a way to populate the assets field by scanning the devices with the QR code scanner?

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Bulk-scanning functionality is not yet available but it's on the roadmap.

**Comment by SteTwin** [comment]
Has such functionality become available yet?
