### ISSUE TITLE
Apache2 error AH00558 with Docker image

### ISSUE THREAD

**Issue by jstoja** [snipe/snipe-it#3814]
#### Expected Behavior (or desired behavior if a feature request)

Launch Docker image with no issues.

-----

#### Actual Behavior

When launching a basic command I get this:
```
bordel@lu-lux-etix-1:~$ docker run -p80:80 -ti --rm -e "APP_KEY=yolo" -e APP_URL="http://127.0.0.1:80" snipe/snipe-it
Module ssl disabled.
To activate the new configuration, you need to run:
  service apache2 restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.7. Set the 'ServerName' directive globally to suppress this message
```

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
The Docker image used is latest, I tested this on OSX and Debian. I guess the fix is very simple by adding a ServerName field in the apache2 configuration.

**Comment by snipe** [comment]
I think that's a warning level message - Apache should still start

**Comment by jstoja** [comment]
Sadly, the apache service restarts again and again and never serve requests. Never had this issue?

**Comment by uberbrady** [comment]
No, but it's certainly possible that something broke somewhere.

I found that I could run the line you put up there just fine if I remove the `--rm` argument. I have no idea why that might be, though.

Of course, when I then curl localhost, I get a big giant "whoops" screen, because just about all of the important variables you should be setting aren't there. See: https://snipe-it.readme.io/docs/docker if you're missing which ones need to be set.

What exactly are you trying to do here? If it's just "get Snipe-IT running" then definitely do check out those docs, they should put you on the right track. If it's something else, let me know!

And if it turns out I'm doing something weird or wrong in the Docker setup, I'm definitely open to suggestions.

**Comment by jstoja** [comment]
Tried without the `--rm` arg and it seems to help.
I know for the arguments, I was just posting a minimal failing command.

(btw, one might want to fix the docker images build: https://hub.docker.com/r/snipe/snipe-it/builds/)

**Comment by uberbrady** [comment]
Cool, if that helps then good. Open up a new issue if you have another problem as you're exploring Snipe-IT, and we'll try to help you with that. I'll close this for now.

(And thanks for the heads-up on the docker build; I'm trying to fix it now.)

**Comment by nav-nith** [comment]
I am facing this issue now. Getting the same error message with new images:
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.7. Set the 'ServerName' directive globally to suppress this message.

**Comment by amnya** [comment]
Any solution for this? I have pulled a new container / image, first it gave an error regarding a KEY, then after setting a key, i get the same AH00558 error and then if i try to access the terminal, the container crashes, please help.

**Comment by charan432** [comment]
I am having similar issue. I am getting error AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message.

Can somebody please help?

**Comment by EarlRamirez** [comment]
@charan432, can you create a new issue for this, since the original issue was already closed? You can also try updating your hosts file with the server name and Apache should stop whining.

**Comment by nativetodevops** [comment]
Having similar issue, anyone got a solution?

**Comment by ghost** [comment]
Hi 

I was getting below error while running the apache container in my centos OS.

Docker file:
FROM centos
RUN yum -y install httpd
EXPOSE 80
RUN echo "ServerName localhost" >> /etc/httpd/httpd.conf
CMD ["apachectl", "-DFOREGROUND"]



AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message


Solution:

Add below instruction (RUN echo "ServerName localhost" >> /etc/httpd/conf/httpd.conf) in your Dockerfile, this should resolve the issue.

FROM centos
RUN yum -y install httpd
EXPOSE 80
RUN echo "ServerName localhost" >> /etc/httpd/conf/httpd.conf
CMD ["apachectl", "-DFOREGROUND"]


Thanks.
