### ISSUE TITLE
expiring alert not working on imported assets

### ISSUE THREAD

**Issue by arvage** [snipe/snipe-it#3817]
#### Expected Behavior (or desired behavior if a feature request)

When running artisan snipeit:expiring-alerts it should send a complete list of expiring assets
-----

#### Actual Behavior

it is only sending alerts on assets that were manually created and it doesn't work on imported assets
-----

#### Please confirm you have done the following before posting your bug report:

I have updated the asset purchase date but it didn't fix it but when I deleted the imported asset and manually create it then alert on that asset started working

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- v3.6.6 build 1 (gee2c67a)
- Ubuntu Server 16, Apache, MySQL, PHP
- Used install.sh

**Comment by arvage** [comment]
I found the problem. when importing assets it doesn't set the archived to 0 and it stays as NULL so your query didn't pick up those imported assets. 
can I add a column in my csv and call it archived and set the value to 0 for the import?

**Comment by snipe** [comment]
No, it won't pick that up just by adding the column - but we'll push out a fix for v4.

**Comment by snipe** [comment]
This is fixed in v4
