### ISSUE TITLE
Can't open people profile because of IP Address

### ISSUE THREAD

**Issue by SirajQu** [snipe/snipe-it#3818]
I'm facing issue when open any profile for person, the IP Address of the profile duplicates itself so the page wouldn't load unless the I delete the duplicate,
so how can I make that direct loading to the correct page address?

See the screen shoots:
![2017-08-03_11-36-26](https://user-images.githubusercontent.com/30687897/28913835-16909f84-7842-11e7-8609-edc0c1ae00b0.jpg)
![1](https://user-images.githubusercontent.com/30687897/28913769-dc4daaba-7841-11e7-8a33-9782d02ed78b.jpg)
![2](https://user-images.githubusercontent.com/30687897/28913802-f7049d96-7841-11e7-81ef-0d2b1574616f.jpg)

**Comment by snipe** [comment]
What's your APP_URL in your .env?

**Comment by SirajQu** [comment]
Thanks for replying, this the URL I put inside .env:
`APP_URL=192.168.1.8`

And this inside virtual host inside ( /etc/apache2/sites-available/snipeit.conf ):

`<VirtualHost *:80>

    ServerName 192.168.1.8

    DocumentRoot /var/www/snipe-it/public

    <Directory /var/www/snipe-it/public>

        Options Indexes FollowSymLinks MultiViews

        AllowOverride All

        Order allow,deny

        allow from all

    </Directory>

</VirtualHost>
`

**Comment by SirajQu** [comment]
The problem has been solved, thank you dear snipe.
