### ISSUE TITLE
Supplier dropdown with new added data doesnt refreshes

### ISSUE THREAD

**Issue by adriahn** [snipe/snipe-it#3823]
#### Actual Behavior

Creating a new supplier while creating asset, dropdown doesn't refreshes with new data, as other dropdowns such model and status does.

-----

#### Please confirm you have done the following before posting your bug report:

- [ y] I have enabled debug mode
- [ y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - Version v3.6.6 build 1 (gee2c67a)
- What OS and web server you're running Snipe-IT on - debian-wheezy  raspberry-pi
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - no error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - New asset addition
- If a stacktrace is provided in the error, include that too. - nope
- Any errors that appear in your browser's error console. - nope
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). - yes it does, same result.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. no errors were given.
- Include what you've done so far in the installation, and if you got any error messages along the way. no errors during installation
- Indicate whether or not you've manually edited any data directly in the database - nope.
![image](https://user-images.githubusercontent.com/30721466/28963833-de7c0506-790a-11e7-805a-e0b6028c6570.png)
![image](https://user-images.githubusercontent.com/30721466/28963848-e7da6610-790a-11e7-982f-3355984c1ce4.png)
**TEST222 doesnt appear lately, data doesnt re-load under dropdown.

Kind regards,

**Comment by snipe** [comment]
This is fixed in the upcoming v4
