### ISSUE TITLE
[v4 API] Creating a new Location will not accept parameters aside from name

### ISSUE THREAD

**Issue by jasonspriggs** [snipe/snipe-it#3825]
When POSTing to create a new Location, I attempt to post three parameters: name, parent_id, and address. In both the return payload and when subsequently GETing the new location object, I get returned either no address field (for the return payload) or a blank string or null (for GETing the location object).

<img width="499" alt="screen shot 2017-08-04 at 10 39 22 pm" src="https://user-images.githubusercontent.com/16108587/28992286-de055482-7965-11e7-8da6-85adbc8b9e96.png">

<img width="464" alt="screen shot 2017-08-04 at 10 39 48 pm" src="https://user-images.githubusercontent.com/16108587/28992285-de047c2e-7965-11e7-9a11-71705ac7d2e2.png">

<img width="842" alt="screen shot 2017-08-04 at 10 45 10 pm" src="https://user-images.githubusercontent.com/16108587/28992321-a14eecb4-7966-11e7-8044-019904b25f04.png">

**Comment by snipe** [comment]
Fixed on dev
