### ISSUE TITLE
Snipe IT 3.6.6 with Wamp, Apache 2.4.23 / PHP 7.0.10 Installation issue

### ISSUE THREAD

**Issue by forester143** [snipe/snipe-it#3826]
Dear Support,
![snipe-it page not displayed](https://user-images.githubusercontent.com/30769301/29002050-1f87305a-7aa2-11e7-9219-0e0c05f690e5.jpg)
![snipe-it your projects](https://user-images.githubusercontent.com/30769301/29002051-1f880a5c-7aa2-11e7-9eeb-1c9baec1a56a.jpg)
![snipe-it homepage](https://user-images.githubusercontent.com/30769301/29002052-1f88e0da-7aa2-11e7-9f24-450d92802ae2.jpg)

 I was installing Snipe IT on Windows 2008 R2 , I was having an issue with the Project. After installation  (followed as per-  https://snipe-it.readme.io/v3.6.2/docs/wamp  )
The only step i cannot perform here is step: 5 Generate your app key
leaving that step , i moved further and after following all steps, I can open the page, when opening the page for localhost, I click on snipe-IT under Your projects , which redirects to http://snipe-it  . the page is not opening and just "This page cant be displayed".
kindly let me know what i am missing..

Regards,
ZAHED

![snipe-it homepage](https://user-images.githubusercontent.com/30769301/29002042-fa3c191e-7aa1-11e7-9470-2148bdd8b217.jpg)
![snipe-it page not displayed](https://user-images.githubusercontent.com/30769301/29002043-fa3c5aaa-7aa1-11e7-8f85-8152e0574443.jpg)
![snipe-it your projects](https://user-images.githubusercontent.com/30769301/29002044-fa3e0418-7aa1-11e7-9bb7-c8e21d2efee2.jpg)

#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by forester143** [comment]
Dear Support,
  Find below the requested Filled-In details: I am installing on Wamp
Server 3.0.6 , MYSQL 5.7.14 , PHP 7.0.10

Awawiting your reply to toubleshoot, as I am troubleshooting since 2 weeks
and filing.

Regards,
ZAHED

**Comment by snipe** [comment]
> one of the Wamp service is getting down and could not move further)

I don't really know what this means.

Did you restart the web server? What specific errors are in the server logs? (If it's failing to start or is crashing, it should tell you why.)

**Comment by forester143** [comment]
When I follow the steps as per the below url on Windows 7 32 bit, it works
fine, but when I am installing on Windows Server 2008 R2, it fails, it says
document root is set incorrectly, or page not found.

https://snipe-it.readme.io/v3.6.2/docs/wamp

**Comment by forester143** [comment]
closed, unable to solve issue and didnt installed Snipe IT .
