### ISSUE TITLE
All uploaded image aren't showing because of "Wrong URL"

### ISSUE THREAD

**Issue by SirajQu** [snipe/snipe-it#3827]
I'm facing issue with all uploaded images which direct to a wrong URL

![3](https://user-images.githubusercontent.com/30687897/29005359-6f257e74-7ae2-11e7-91a6-7fa4e880b557.png)

Also in Avatars:
![1](https://user-images.githubusercontent.com/30687897/29005358-529bb3ea-7ae2-11e7-9422-04ea51a83fe3.png)

When I try to open the avatar image it's directing me to "http://192.168.1.8/account/192.168.1.8/uploads/avatars/user.jpg"
instead of the correct URL "http://192.168.1.8/uploads/avatars/user.jpg"

More over the clicking on the dashboard:
![2](https://user-images.githubusercontent.com/30687897/29005380-0d069b78-7ae3-11e7-8c54-b2ff33cfaefa.png)

**I hope someone help me to fix it,
and this is what's inside the file (.env)**

> APP_ENV=production
APP_DEBUG=false
APP_KEY=**********************************
APP_URL=192.168.1.8
APP_TIMEZONE=
APP_LOCALE=en

# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=snipeit_db
DB_USERNAME=snipeit
DB_PASSWORD=**********
DB_PREFIX=null
DB_DUMP_PATH='/usr/bin'

**And this is inside virtual host that located in ( /etc/apache2/sites-available/snipeit.conf ):**

> <VirtualHost *:80>

ServerName 192.168.1.8

DocumentRoot /var/www/snipe-it/public

<Directory /var/www/snipe-it/public>

    Options Indexes FollowSymLinks MultiViews

    AllowOverride All

    Order allow,deny

    allow from all

</Directory>

**Comment by BrettFagerlund** [comment]
Please update your App URL in env file as below

APP_URL=http://192.168.1.8

**Comment by SirajQu** [comment]
Thank you so much dear, I didn't notice it was a simple solution  :)

**Comment by akhilptz** [comment]
I have been facing the same issue. I have changed the APP_URL as per the solution provided. But didn't works. Anyone, can you please help?
![2018-08-10_125844](https://user-images.githubusercontent.com/25217439/43944643-3cc3ea50-9c9d-11e8-9aa5-72ebe2464b99.jpg)
