### ISSUE TITLE
Asset granted permissions = nothing listed

### ISSUE THREAD

**Issue by tomse** [snipe/snipe-it#3828]
#### Expected Behavior (or desired behavior if a feature request)

People with granted permission can view/edit etc. Assets

-----

#### Actual Behavior

All buttons for Assets are there, list views are ready.
but no assets are listed.

Getting Permission denied when searching for an asset

I've created a group that grants all permissions to Assets (Asset admin if you like)
I've added a LDAP user to this group. (it shows in the userlist under groups column)
Logged in as the user, and assets shows no data (whereas my admin user there's plenty of assets)

I've tried forcing permissions, editing the user --> permissions - move Assets (all) to grant rather than inherited.

All buttons are there on the interface, but no data accessible.

-----

#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running : 
3.6.6 Build 1
- What OS and web server you're running Snipe-IT on : 
Ubuntu 1604, apache24
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Insufficient permissions
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
List Assets

- If a stacktrace is provided in the error, include that too.
N/A
- Any errors that appear in your browser's error console.
N/A
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
N/A (Using LDAP backend for users)
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
N/A no errors has occured when trying to do this
- Include what you've done so far in the installation, and if you got any error messages along the way.
N/A
- Indicate whether or not you've manually edited any data directly in the database
No manually edited data

**Comment by snipe** [comment]
Are you using full company support?

**Comment by tomse** [comment]
I did, and now that you pointed that out, I turned it off and it works as expected :-)
thanks alot
