### ISSUE TITLE
facing issue in CSV import in snipe it stucking after 100 % 

### ISSUE THREAD

**Issue by amitchobdar** [snipe/snipe-it#3829]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
![snipeit](https://user-images.githubusercontent.com/30799349/29026392-2cb3be5e-7b99-11e7-8834-a6b357db4bb2.png)
![snipeit](https://user-images.githubusercontent.com/30799349/29026404-3872d842-7b99-11e7-8a07-465fbeef706a.png)

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by amitchobdar** [comment]
1. Snipe-IT version | v3.6.6  build 1 
2. Ubuntu 17.04
3. Manual installation
4. Not getting any error only CSV import stucking on 100%.
5.There is no error message on browser.
6. I have not edited anything manually in database.

Please provide the solution asap and mail us on "amitchobdar@gmail.com"

Thanks
Amit Chobdar
[Uploading assets-export-2017-08-05.csv

**Comment by snipe** [comment]
@amitchobdar we don't email support solutions. That's what these issues are for. 

> Not getting any error only CSV import stucking on 100%.

Meaning any error in the browser, or in the error log? There has to be an error somewhere. 

Issues related to uploading files are usually related to folder permissions.  Check that your `storage` directory and all subdirectories are writable.

**Comment by amitchobdar** [comment]
I have assigned 755 permission to storage directory and its subdirectory, we have configured below ownership.
chmod -R 755 storage 
chmod -R 755 public/uploads
chown -R www-data:www-data storage public/uploads  

But still we are facing import issue in CSV still stucking at 100% after that there is no movement,error.

**Comment by aditya6190** [comment]
@amitchobdar It should be a large CSV. chunk the CSV file into small sizes and try to upload.

**Comment by snipe** [comment]
Haven't heard back, so I'm going to close this ticket for now, but will re-open it if you're still having issues

**Comment by amitchobdar** [comment]
Still m unable to import csv in system we have given permissions to storage
folder.

Amit
