### ISSUE TITLE
Using Base64 images in email php templates

### ISSUE THREAD

**Issue by ericdude101** [snipe/snipe-it#3831]
#### Expected Behavior (or desired behavior if a feature request)

Inserting an image into an email gets blocked and users have to allow external images to load so im 
trying to embed our company logo in the header of all emails using the following code:

`<img src="data:image/png;base64, iVBORw0KGgoAAAANSUAAAI..." alt="Logo" />`

-----

#### Actual Behavior

Doing so outputs nothing, I can directly insert an image using a URL but that causes the blocked images message which i'm trying to avoid: 

`<img src="https://imageurl">`

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 3.6.6
- What OS and web server you're running Snipe-IT on Server 2012R2 W/ IIS 8
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Composer
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error None
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error, no error, just missing functionality.

**Comment by snipe** [comment]
Base64 encoding images is fine for the web, but doesn't work reliably in emails (thanks, porn spammers). You'll want to include the image as an attachment and then reference it via cid.

https://stackoverflow.com/a/9110167/200021
https://stackoverflow.com/questions/9110091/base64-encoded-images-in-email-signatures/9110164#9110164

**Comment by ericdude101** [comment]
Would I put that code into the PHP template? HTML and PHP are definitely not my realm of knowledge

**Comment by ericdude101** [comment]
Here is a copy of my default blade, how can I make this work?

<!DOCTYPE HTML>
<html lang="en-US">
<head>
    <meta charset="UTF-8">
    <title></title>
    <style>
    body, p {
        font-family: Arial, Helvetica, sans-serif;
        font-size: 13px;
    }

    td {
        background-color:#d2d6de;
        font-size: 13px;
    }

    p {
        padding-top: 10px;
    }

--boundary
Content-Type: image/png; name="PCH.png"
Content-Disposition: inline; filename="PCH.png"
Content-Location: PCH.png
Content-ID: <0123456789>
Content-Transfer-Encoding: base64

iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAYAAACNMs+9AAAABGdBTUEAALGP
C/xhBQAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9YGARc5KB0XV+IA
AAAddEVYdENvbW1lbnQAQ3JlYXRlZCB3aXRoIFRoZSBHSU1Q72QlbgAAAF1J
REFUGNO9zL0NglAAxPEfdLTs4BZM4DIO4C7OwQg2JoQ9LE1exdlYvBBeZ7jq
ch9//q1uH4TLzw4d6+ErXMMcXuHWxId3KOETnnXXV6MJpcq2MLaI97CER3N0
vr4MkhoXe0rZigAAAABJRU5ErkJggg==


--boundary
	
	
    </style>
</head>
<body>

<img src="cid:0123456789">

<hr width="30%" size="6" align="left" color="D3D3D3">


    @yield('content')
</body>
</html>

**Comment by ericdude101** [comment]
Those links seem to reference HTML code, but plugging it into the php email template like I did above seems to just insert the text, it doesn't recognize it as code.

**Comment by snipe** [comment]
This feature will be in Snipe-IT v5
