### ISSUE TITLE
Internal Server Error - upon Installing Snipe-IT

### ISSUE THREAD

**Issue by ggnavisa** [snipe/snipe-it#3832]
#### Expected Behavior (or desired behavior if a feature request)

Expectation is upon installation in google cloud server, following the directions here on how to install snipe-it:
https://www.vultr.com/docs/how-to-install-snipe-it-on-centos-7
https://www.tecmint.com/install-snipe-it-asset-management-on-centos-ubuntu-debian/

-----

#### Actual Behavior

for the last step should be redirected to Snipe-IT Web Installation. But i encountered Internal Server Error:

![internal server error](https://user-images.githubusercontent.com/30823013/29059186-e7aff422-7c46-11e7-8a23-048adcdf5b06.PNG)

-----

#### Please confirm you have done the following before posting your bug report:

[Tue Aug 08 06:30:40.932868 2017] [:error] [pid 24155] [client 58.69.197.248:34282] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/snipe-it/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied' in /var/www/snipe-it/bootstrap/cache/compiled.php:13906\nStack trace:\n#0 /var/www/snipe-it/bootstrap/cache/compiled.php(13836): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/snipe-it/bootstrap/cache/compiled.php(13596): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/snipe-it/bootstrap/cache/compiled.php(13694): Monolog\\Logger->addRecord(400, Object(ErrorException), Array)\n#3 /var/www/snipe-it/bootstrap/cache/compiled.php(13389): Monolog\\Logger->error(Object(ErrorException), Array)\n#4 /var/www/snipe-it/bootstrap/cache/compiled.php(13360): Illuminate\\Log\\Writer->writeLog('error', Object(ErrorException), Array)\n#5 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(57): Illuminate\\Log\\Writer->error(Object(ErrorException))\n#6 /var/www/snipe-it/app/Exceptions/H in /var/www/snipe-it/bootstrap/cache/compiled.php on line 13906
[Tue Aug 08 06:30:40.933461 2017] [:error] [pid 24155] [client 58.69.197.248:34282] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/snipe-it/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied' in /var/www/snipe-it/bootstrap/cache/compiled.php:13906\nStack trace:\n#0 /var/www/snipe-it/bootstrap/cache/compiled.php(13836): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/snipe-it/bootstrap/cache/compiled.php(13596): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/snipe-it/bootstrap/cache/compiled.php(13694): Monolog\\Logger->addRecord(400, Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#3 /var/www/snipe-it/bootstrap/cache/compiled.php(13389): Monolog\\Logger->error(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#4 /var/www/snipe-it/bootstrap/cache/compiled.php(13360): Illuminate\\Log\\Writer->writeLog('error', Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#5 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/E in /var/www/snipe-it/bootstrap/cache/compiled.php on line 13906

-----
#### Please provide answers to these questions before posting your bug report:

- What OS and web server you're running Snipe-IT on:
Centos 7 / Google cloud Server

CentOS Linux release 7.3.1611 (Core)

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation using the ff. directions:

https://www.vultr.com/docs/how-to-install-snipe-it-on-centos-7
https://www.tecmint.com/install-snipe-it-asset-management-on-centos-ubuntu-debian/

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error;

Web set-up Installation

- Any errors that appear in your browser's error console.
_"Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, support@one.com and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log."_
    2  cd /var/www/snipe-it/storage/
    3  ls -ltr
    4  cd ..
    5  ls -ltr
    6  chmod 775 storage
    7  ls -ltr
    8  tail -f /var/log/httpd/snipeIT.error.log
    9  cd /var/www/snipe-it/bootstrap/
   10  cd ..
   11  ls -ltr
   12  chmod 775 bootstrap
   13  cd bootstrap/
   14  ls -ltr
   15  cd ..
   16  chmod 775 bootstrap storage *
   17  ls -ltr
   18  cd bootstrap/
   19  ls -ltr
   20  chmod 775 *
   21  ls -ltr
   22  cd ..
   23  ls -ltr
   24  cd storage/
   25  ls -ltr
   26  chmod 775 *

**Comment by snipe** [comment]
> PHP Fatal error: Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/snipe-it/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied' 

Storage directory is not writable. Check for SELinux restrictions or mismatching owner/group membership for the storage dir.
