### ISSUE TITLE
Feature Request (Monitoring | UI Features)

### ISSUE THREAD

**Issue by raakhtar** [snipe/snipe-it#3833]
- [ ] **Monitoring Feature** 

1)Query Generator 
a) Finding how many users own multiple assets
b) Assets that are retired but users have not returned the assets
2) Warranty Expiring Alerts (Licenses | Assets)

- [ ] **Backend**

- .env file to allow to add a different DB port
- Backup screen to check if 7.0+ Php version is being used
- Database.php under config to take into account DB Port from .env file

- [ ] **UI Feature**
-Dashboard to show user's created Status:Label Count
-Allowing icons upload for user created labels on Status:Label Creation screen
-Assets Listing to allow Images thumbnail to be shown on the main listing screen in the row.(option to be available in filter)
- Adding more System status:Labels e.g "Temporary Assigned" to be checked-in by user themselves
-Allowing Vendor Contracts & invoicing as per the milestone deliveries to be added to the system (perhaps under component)
- Allowing multiple contacts to be added in the supplier, assigning them the priority for admin to know in which escalation matrix to contact supplier.
- Taking away the 20 char limits from phone field, or ability to allow to add multiple numbers
- Allowing multiple emails to be added under supplier for each supplier
- Delete cache feature in settings screen
- Setting screen to allow user to select the panel to display instead of activity table e.g List All Assets, Consumables, Licenses,Component.
- Add another field under Asset: "Condition of the Asset"
- Add warranty checking url field in Asset

**Comment by snipe** [comment]
> 2) Warranty Expiring Alerts (Licenses | Assets) 
This [already exists](https://snipe-it.readme.io/v3.6.2/docs/configuring-alerts)

> Backup screen to check if 7.0+ Php version is being used
This is not necessary. Snipe-IT works with PHP 5.6+. 

> Dashboard to show user's created Status:Label Count
It already does this

> Allowing icons upload for user created labels on Status:Label Creation screen
I don't know what this means.

> Assets Listing to allow Images thumbnail to be shown on the main listing screen in the row.(option to be available in filter)
This is already available

> Adding more System status:Labels e.g "Temporary Assigned" to be checked-in by user themselves
This is unlikely to be implemented. More likely is the additional permisson of allowing specific users to check in their own items

> Allowing Vendor Contracts & invoicing as per the milestone deliveries to be added to the system (perhaps under component)
There are existing tickets requesting this feature

> Allowing multiple contacts to be added in the supplier, assigning them the priority for admin to know in which escalation matrix to contact supplier.
This is not a priority for development at this time. The notes field can be used for that purpose.

> Taking away the 20 char limits from phone field, or ability to allow to add multiple numbers
Phone numbers are wrapped in the HTML that easily enables mobile devices to utilize them as phone numbers, so allowing multiple would break that functionality. Again, we suggest using the notes field.

> Delete cache feature in settings screen
The cache only needs to be deleting when performing upgrades, which requires command line access anyway. This is unlikely to be implemented. 

> Add another field under Asset: "Condition of the Asset"
Custom fields can be used for this

> Add warranty checking url field in Asset
I don't know what this means.

**Comment by raakhtar** [comment]
Backup screen to check if 7.0+ Php version is being used
This is not necessary. Snipe-IT works with PHP 5.6+.
[Raheal] The Laravel Backup does not work if PHP is set to a version lower than 7.0

Add warranty checking url field in Asset
I don't know what this means.
[Raheal] There are urls where warranty status can be checked dependent on the asset type e.g HP warranty site, Lenovo warranty site, etc

Add another field under Asset: "Condition of the Asset"
Custom fields can be used for this
[Raheal] Custom fields do not appear in the edit, only allowed through file upload to modify the custom fields

Checkout to another user without needing to checkin first, or auto check-in once it gets reassigned to another user.
