### ISSUE TITLE
NFC reader/writer feature request

### ISSUE THREAD

**Issue by lategreat** [snipe/snipe-it#3834]
This is a feature request for compatibility with IFRD/NFC reader writer. so NFC can be used to scan items, in addition to barcodes.

thanks

**Comment by rkantos** [comment]
You mean RFID? It would be awesome to get some addon for Snipe-IT where you could for example monitor check in and check out of assets using RFID. This could include a system where one could setup rfid-readers all over their offices, and then the addon would change the location setting if items based on preconfigured locations of the RFID-readers. 

Probably the most easiest "lean-friendly" implementation method would be to have a gate, where assets would be scanned, and then the user would verify them being taken out or in to a location or storage.

See for example: https://www.youtube.com/watch?v=xr6_Gn8bcJ8

**Comment by memtech3** [comment]
Also UHF RFID please

**Comment by memtech3** [comment]
Use electron and add support for serial devices

**Comment by snipe** [comment]
People already use NFC/RFID readers with Snipe-IT. I'm not sure of the specifics tho.

**Comment by memtech3** [comment]
They use HID readers

**Comment by memtech3** [comment]
The electron app is to supplement the web app

**Comment by memtech3** [comment]
maybe I could find someway to bulk audit with rfid with the api

**Comment by memtech3** [comment]
those uhf rfid readers can read 100s of tags in seconds

**Comment by memtech3** [comment]
can this be reopened

**Comment by aliuysal60** [comment]
I have a solution for UHF RFID and Barcode reading, asset counting and reporting.
You can count assets by reading QRCode with CM900 RFID reader or any mobile device.

Reports missing and lost,
It lists the assets that do not belong to the location and updates the location with one click.
https://cilico1.en.alibaba.com/product/62291791791-801824987/CM900_UHF_Reader.html

With the special API, you can integrate with mobile applications you have developed yourself.

![image](https://user-images.githubusercontent.com/6507261/83979489-6e69f080-a917-11ea-8667-2fc3f40b1f53.png)

![image](https://user-images.githubusercontent.com/6507261/83979508-96595400-a917-11ea-8dfd-539a319bf144.png)


<blockquote><img src="//sc02.alicdn.com/kf/Hbe9f98c769cb4b3e8fc9bb28fdc74027P.jpg" width="48" align="right"><div>www.alibaba.com</div><div><strong><a href="//www.alibaba.com/product-detail/CM900-UHF-Reader_62291791791.html">CM900 UHF Reader, View CM900 UHF Reader, CILICO Product Details from China Cilico Microelectronics Co., Ltd. on Alibaba.com</a></strong></div><div>CM900 UHF Reader, US $ 1180.00 - 1180.00 / Set, Stock, CILICO.Source from China Cilico Microelectronics Co., Ltd. on Alibaba.com.</div></blockquote>
