### ISSUE TITLE
Feature to disable all fetches to other sites. i.e. gravatar, google etc

### ISSUE THREAD

**Issue by tomse** [snipe/snipe-it#3837]
#### Expected Behavior (or desired behavior if a feature request)
while the snipe-it server might be located with internet access,
all operations wait for a timeout before continuing, when the server
does not have internet access.

It would be very nice to disable all calls to the outside world from the server.
so far I've found Gravatar and Google api's.
As a workaround I've added those sites to my internal DNS server, and no hosts. Which made the application fast again.

now that gravatar cannot display an image, I see the alt text "image" instead at some locations (sorry I don't remember which places at this time), which can be inconvenient at times.

The following should probably be added as a new bug, but as the above affects the below, I'll just keep this here.
In the edit profile page, the gravatar image location that should have been fetched from gravatar, just shows a "broken image" placeholder. This is of course when there is no internet access. probably and alt text would be useful here?

cheers
/Carsten

**Comment by snipe** [comment]
That option is in the settings. "This Snipe-IT install can load scripts from the outside world."

**Comment by tomse** [comment]
I've just had time to check the feature, and regardless of the setting I can see that Snipe-IT wants to access gravatar and fonts.googleapis no matter what.

**Comment by snipe** [comment]
This is fixed in v4, per previous threads.

**Comment by MilchreisMitZimt** [comment]
i cant find this Setting in Version 5.1.4
