### ISSUE TITLE
Login with username OR email address

### ISSUE THREAD

**Issue by cipnt** [snipe/snipe-it#3838]
Hi,

I would recommend that the login page should accept either the username (current behaviour) **OR** the email address of the account, similar to what other online services are doing (eg https://facebook.com/login/ https://twitter.com/login).

We discovered the current behaviour to be an issue when we were resetting the password for some users and 1Password would offer to save the new login details but would use the email address instead of the username.
Trying to then login using the details from 1Password would never work and repeatedly had to reset the password.

Thanks!

**Comment by snipe** [comment]
That's not really that easy to do, unfortunately. What happens if your *username* is bob@awesome.com and my *email* is bob@awesome.com. Two different accounts, so how does the system know which one you really are?

**Comment by cipnt** [comment]
Indeed, but that would be an extremely unlikely scenario. There could be an additional prompt to select from two accounts matching those credentials (Google has a similar thing with [G Suite conflicting accounts](https://youtu.be/BNR2mLxxIg8?t=1m5s) where you get asked which account you want to login to until you resolve the conflict)

Our company setup had username bob and email bob@awesome.com for all the accounts and because the **password reset procedure** didn't involve the username at all, the user expected to login with their email address instead of their username. 
Also the password manager automatically saved the login as email + password rather than username + password.

Maybe renaming the input fields so that password managers like 1Password better understand which fields are required for login would solve some of the confusion

**Comment by snipe** [comment]
> Indeed, but that would be an extremely unlikely scenario. 

You would be surprised. We've worked with companies that started small and grew quickly, and didn't really have their naming conventions well-established yet.

> There could be an additional prompt to select from two accounts matching those credentials

I would consider that a poor security practice by way of information disclosure. We could potentially make it an option that superadmins can decide whether to use email or username, but I don't see both being an option soon. (If we required email addresses now like we used to - until people complained - that would be one thing.)

**Comment by pbrink231** [comment]
So I did this on a different laravel app I made.  I think it could work well here.

You could have a setting to allow email login.

If that setting is checked, then if the login contains '@', you use email column instead of the username column for the login logic.

I get your situation about @ but I would guess 80-95% of companies do not use the email as the username.  username would be the beginning part of the email or something else.  If they do have this issue then they just dont allow the setting and now it works as it does now.
