### ISSUE TITLE
Column "Groups" in hardware table

### ISSUE THREAD

**Issue by oli415** [snipe/snipe-it#3839]
#### Desired behavior

I would like to have a column for "Groups" in the Hardware table (file snipe-it/resources/views/hardware/index.blade.php), showing the group of the user to whom (if any) the asset is assigned. I managed to add the column by adding the "th" tag with data-field="groups" but the actual rows do not contain any data. I figured out that "groups" is a part of the 'api.users.list' and not the here used 'api.hardware.list'. I guess that is the reason why I don't get any Information on Groups.

How can I adapt the code for this to work?

Thanks

-----

#### Actual Behavior

does not exist yet

-----

**Comment by snipe** [comment]
You would need to return the groups in the hardware listing if there is a user associated
