### ISSUE TITLE
Has anyone ever imported assets / licences from SQL database?

### ISSUE THREAD

**Issue by dannyscarborough** [snipe/snipe-it#3842]
Hi,

I'm just looking into importing assets and licence data from our SCCM server and wondered if anyone has ever done this or something similar?

Thanks,
Danny.

**Comment by snipe** [comment]
Not that I know of. Generally speaking, that sounds like it could be pretty hellish and I wouldn't recommend it. Better to export as CSV and import into the system as the importer makes all of the model/category/etc connections for you based off of your CSV
