### ISSUE TITLE
Changing Name

### ISSUE THREAD

**Issue by shiasurprise** [snipe/snipe-it#3844]
I erased the template thinking this wasn't necessary, if needed I can put it in: I have a request from my manager to change the name of the database. When I click on "sitename" on the dashboard I receive this fellow:
![image](https://user-images.githubusercontent.com/30155524/29231227-064d4b8e-7eac-11e7-9b82-ee1f1761c8e6.png)

I am very new to the situation and would like some assistance if that is possible.

**Comment by snipe** [comment]
That's a DNS issue, not a database issue. You'll need to figure out what broke with your DNS.
