### ISSUE TITLE
Full Company Support migration

### ISSUE THREAD

**Issue by oli415** [snipe/snipe-it#3847]
#### Expected Behavior (or desired behavior if a feature request)

I enabled Full Company Support and now I would like to quickly assign all exisiting users to a Company.

If there is no Feature for this built in, is it safe to update the underlying database manually?

Thanks

-----

#### Actual Behavior

Could not find anything like this. One has to edit each user separately I believe.

-----
- Version of Snipe-IT you're running: v3.6.6 build 1 (gee2c67a)

**Comment by snipe** [comment]
The upcoming v4 has the ability to bulk edit attributes like that, but v3x does not. As long as you're careful, you should be able to update manually. Do a backup first tho ;)
