### ISSUE TITLE
[v4 API] Cannot create accessory with attributes

### ISSUE THREAD

**Issue by jasonspriggs** [snipe/snipe-it#3849]
POSTing to /accessories with attributes `manufacturer_id` or `notes` does not assign the posted values to the newly created accessory.

<img width="545" alt="screen shot 2017-08-14 at 11 16 29 pm" src="https://user-images.githubusercontent.com/16108587/29300916-a71b7026-8146-11e7-9bfa-63fb2eb92e31.png">

**Comment by jasonspriggs** [comment]
Also, just noticed that qty in the payload response is a string and not an int.

**Comment by snipe** [comment]
Fixed on develop
