### ISSUE TITLE
Dashboard appearance modification

### ISSUE THREAD

**Issue by smaloba1** [snipe/snipe-it#3850]
Hello Snipe, i would like to know if there's a way to modify the appearance of the dashboard so that it can display an extra tab with the total value of asset right on the pop-up. Like in the image below: 
![capture](https://user-images.githubusercontent.com/12434671/29307605-3c26384a-81ab-11e7-9046-7978f14b7699.JPG)

If it is possible then which files should I modify in order to achieve this. Am good at php but not so conversant with Laravel file structure. 

Thanks.
-----
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode--Yes
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)--Yes

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running-:  3.6.6
- What OS and web server you're running Snipe-IT on Shared Hosting running linux

**Comment by smaloba1** [comment]
Hello friends and @snipe I found a way of displaying the total asset value on the dashboard. If there's anyone interested, i will be happy to post here. Of course if our dear @snipe doesn't mind.

**Comment by snipe** [comment]
Hi @smaloba1 - there's not currently a way to do that, but we would definitely take a look at a pull request if you put one together.
