### ISSUE TITLE
Missing Checkout to line when creating a new assets

### ISSUE THREAD

**Issue by Youssefibrahim10** [snipe/snipe-it#3851]
when we create a new asset, the checkout line is missing when we choose one the status filed. seems as its load something but it is keeping like below picture.

![image](https://user-images.githubusercontent.com/31034820/29312529-16a60bbc-81b6-11e7-9846-c3f092ea57c2.png)

all what we did is creating a status labels as appear in the following picture.
![image](https://user-images.githubusercontent.com/31034820/29312575-570703e6-81b6-11e7-9268-32a8f1cf8257.png)

Snipe-IT version | v3.6.6 build 1 (gee2c67a), deployed on centos7.
your assistance in that will be highly appreciated.

**Comment by snipe** [comment]
The status type you selected in your screenshot is one that is not deployable, so it cannot be checked out.

**Comment by snipe** [comment]
(Also check for browser errors, per the initial Issue template.)

**Comment by Youssefibrahim10** [comment]
Thank you for your respond, I understand your point , but this happen with all the status type such as Handed Over and Missing that has status type as " Deployable" . Any status name  that have Deployable as asset type must the checkout appear but in my case whatever status type i choose the checkout not appear, it is just give the small icon for loading as i show you in my last post.

**Comment by snipe** [comment]
Then  check for browser errors, per the initial Issue template

**Comment by Youssefibrahim10** [comment]
Thank you so much for your positive response.

**Comment by snipe** [comment]
My guess is that your APP_URL is incorrect, so you'll see a browser error warning about mismatching domains. If you fix your APP_URL, your ajax should load.
