### ISSUE TITLE
V4 Beta: Table 'db.oauth_clients' doesn't exist

### ISSUE THREAD

**Issue by Cornelious11** [snipe/snipe-it#3852]
#### Expected Behavior (or desired behavior if a feature request)

Pre-flight setup finishes normally and Snipe-IT functions as intended

-----

#### Actual Behavior

After user creation during pre-flight setup, page displays `Whoops, looks like something went wrong.` (DEBUG error is below) refreshing the page will bring user to the Snipe-IT UI however all form submissions will result in an error being thrown `please ensure everything is correct`

This is a fresh install of the Beta in an empty database which I drop and rebuild everytime I reinstall the application in dev.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Required Answers:

*Version* 4.0 Beta (pulled from develop branch)
*OS* RHEL 7.3
*Installation Method* Manual (followed v4.0 installation instructions)
*Error Message*
```SQLSTATE[42S02]: Base table or view not found: 1146 Table 'BETA.oauth_clients' doesn't exist (SQL: insert into `oauth_clients` (`user_id`, `name`, `secret`, `redirect`, `personal_access_client`, `password_client`, `revoked`, `updated_at`, `created_at`) values (, Snipe-IT Personal Access Client, oeRjOO4JdbwpzBZoBhkV1UsZ8BG6KKUgm8SmX70z, http://localhost, 1, 0, 0, 2017-08-15 13:18:52, 2017-08-15 13:18:52))```
*Specific Page* https://\<internal snipe-it URL\>/setup
*Errors in console*
`Failed to load resource: the server responded with a status of 500 (Internal Server Error)`
*Reproducable in Demo* N/A.
*Manually Edit Database* No

**Comment by snipe** [comment]
Did you run the `php artisan passport install` command?

**Comment by Cornelious11** [comment]
I did not as it was not in the installation guide for v4.0. At what point during the installation should this command be run?

**Comment by snipe** [comment]
You can try running it now. We try to run it on the dashboard when you first load it, but it's possible we have the order of operations wrong there.

**Comment by snipe** [comment]
If you're feeling adventurous, try adding:

```
if ((!file_exists(storage_path().'/oauth-private.key')) || (!file_exists(storage_path().'/oauth-public.key'))) {
            \Artisan::call('passport:install');
            \Artisan::call('migrate', ['--force' => true]);
        }
```

in `app\Http\Controllers\SettingsController.php`, around line 263, just *below* this part:

```
Artisan::call('migrate', ['--force' => true]);

$output = Artisan::output();
```
(after this bit here: https://github.com/snipe/snipe-it/blob/develop/app/Http/Controllers/SettingsController.php#L261) 

If you can try to start that install again (you might need to drop tables, start from the beginning) - if that addition works, I'll add it to the core.

**Comment by Cornelious11** [comment]
Sorry to re-open this issue, but the issue seems to persist and not allow `php artisan passport:install` to execute because either:
a. there is insufficient permissions to access `storage/logs` (even with chmod 777)
OR
b. the table `db.oauth_clients` doesn't exist. 

I tried to install snipe-it fresh on a new Debian based VM but ran in to the exact same issues with the install. During the pre-flight database creation it will display the same `whoops something went wrong` error message and cause ongoing issues with the rest of the install that I cannot seem to fix. Is there a package I may be missing prior to install that is preventing this from working properly?
