### ISSUE TITLE
[v4 API] Creating a supplier disregards all fields

### ISSUE THREAD

**Issue by jasonspriggs** [snipe/snipe-it#3854]
When creating a supplier in the API, all fields except for name are disregarded and not saved in the API.
<img width="525" alt="screen shot 2017-08-15 at 10 33 44 am" src="https://user-images.githubusercontent.com/16108587/29320455-3e5b55b0-81a5-11e7-8da9-fef6766cfb63.png">
<img width="641" alt="screen shot 2017-08-15 at 10 34 14 am" src="https://user-images.githubusercontent.com/16108587/29320480-5200c3e8-81a5-11e7-83c4-0259878daff8.png">

**Comment by snipe** [comment]
Fixed on dev - thanks!
