### ISSUE TITLE
Can't install version 4

### ISSUE THREAD

**Issue by dedeoglumrt** [snipe/snipe-it#3855]
When I try to install 4 version with downloaded package, I installed Version v3.6.6 build 1 (gee2c67a) instead of 4 what is the reason for this.
How can i install v4.0 beta?

Regards

**Comment by Cornelious11** [comment]
If you are using CLI, use the following command

`git clone -b develop https://github.com/snipe/snipe-it/ $INSTALL_DIR>`

**Comment by dedeoglumrt** [comment]
doesn't work.
is there any other way to install the latest beta (4.0) version

**Comment by Cornelious11** [comment]
What OS are you using?
what are the exact steps you use to install?

**Comment by tomse** [comment]
you fail to describe any errors occuring.  I take it you get an error similar to this:
Command/File not found.

press the green button that says Clone or Download on this page:
https://github.com/snipe/snipe-it/tree/develop

**Comment by snipe** [comment]
Closed as not-constructive
