### ISSUE TITLE
V4 Beta - Asset list loading forever if customfieldset exists against a model

### ISSUE THREAD

**Issue by BrettFagerlund** [snipe/snipe-it#3857]
#### Expected Behavior (or desired behavior if a feature request)

Asset list loads

-----

#### Actual Behavior

If a customfieldset is linked to a model in the database, the asset list says loading please wait and never loads in the situation where the table displays an asset with model which doesn't have a customfieldset

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running -  v4.0-beta build 1 (gcb1e3b7)
- What OS and web server you're running Snipe-IT on - win server 2012 R2 / IIS / MariaDB
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - no errors appearing
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - snipe.local/hardware 

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). - on beta

I can reproduce with following steps, 
1) create minimal dummy data - asset/model/manufacturer etc ( need 2 asset models minimum)
2) create a new customfield ( format alpha, not requried)
3) create new fieldset and link the new customfield
4) add customfield to one model
5) go to all asset page with an asset that **doesn't** have the customfieldset model

**Comment by snipe** [comment]
Hm, I'm not able to reproduce this. Can you double check the browser console and error logs? It will justr hang if there's a 500 error or a javascript error. I have ~500 assets in my test database with multiple custom fields, and I'm not able to reproduce locally.

**Comment by snipe** [comment]
I was finally able to reproduce it. Pull down the latest from dev and let me know if that works for you.

**Comment by BrettFagerlund** [comment]
Thanks, new dev pull has fixed it. Did manage to find error in console too.

Uncaught TypeError: Cannot read property '_snipeit_test_6' of undefined
    at getItemField (bootstrap-table.js:222)
    at String.<anonymous> (bootstrap-table.js:1460)
    at Function.each (all.js:1)
    at BootstrapTable.initBody (bootstrap-table.js:1458)
    at BootstrapTable.toggleView (bootstrap-table.js:2526)
    at changeTableView (bootstrap-table-mobile.js:61)
    at conditionFullView (bootstrap-table-mobile.js:55)
    at changeView (bootstrap-table-mobile.js:42)
    at bootstrap-table-mobile.js:113
    at later (bootstrap-table-mobile.js:71)
