### ISSUE TITLE
[v4 API] Discrepancy between listing categories verses getting single category object

### ISSUE THREAD

**Issue by jasonspriggs** [snipe/snipe-it#3858]
Getting a list of category objects returns 
<img width="328" alt="screen shot 2017-08-15 at 11 13 26 pm" src="https://user-images.githubusercontent.com/16108587/29345856-858ecd80-820f-11e7-81fc-c2f7fdb2053f.png">
Whereas getting a single object returns
<img width="327" alt="screen shot 2017-08-15 at 11 13 54 pm" src="https://user-images.githubusercontent.com/16108587/29345857-8792221c-820f-11e7-9d89-4a5ccedb4ad6.png">

Key notes:
- [x] EULA/Acceptance are 0/1 instead of false/true for single listing
- [x] Created/Updated time does not exist on listing, formatting is incorrect (should include both standard object and then formatted time using Helper function.
- [x] Counts/Available actions are not listed in single object
- [x] eula_text is not returned for listing

**Comment by snipe** [comment]
Fixed on dev - thanks!
