### ISSUE TITLE
Snipe-IT Localhost Host Name issue need to set as IT-Assets but it allows only IP Address

### ISSUE THREAD

**Issue by IT-FOR-MG** [snipe/snipe-it#3859]
#### Host Name with desired name and not with server ip only 
I want to access my asset Management Site as http://SERVER_IP/it_assets

-----

#### Actual Behavior

As per configuration of .env App_URL='SERVER-IP' and Vertual host (snipeit.conf) ServerName SERVER-IP

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version- 3.6.2
- OS- Linux Ubuntu 17.10
- Manual Installation Method

**Comment by snipe** [comment]
The `APP_URL` should be whatever the web address is in the browser. It doesn't have to be an IP (nor do we say it has to be an IP anywhere)
