### ISSUE TITLE
[v4 API] Deleting a department results in a redirect

### ISSUE THREAD

**Issue by jasonspriggs** [snipe/snipe-it#3860]
When deleting a department `{{host}}/api/v1/departments/{{id}}`, the API returns a 302 redirect with contents

`<!DOCTYPE html><html>    <head>        <meta charset="UTF-8" />        <meta http-equiv="refresh" content="1;url={{host}}/departments" />        <title>Redirecting to {{host}}/departments</title>    </head>    <body>        Redirecting to <a href="{{host}}/departments">{{host}}/departments</a>.    </body></html>`

It does delete the resource though, just an invalid response.

**Comment by snipe** [comment]
Fixed on dev - thanks!
