### ISSUE TITLE
email is configured correctly but still not working!!!

### ISSUE THREAD

**Issue by nrj00engineer00** [snipe/snipe-it#3862]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by nrj00engineer00** [comment]
this is my .env file

APP_TIMEZONE=Asia/Kolkata
DB_HOST=localhost
DB_DATABASE=snipeit
DB_USERNAME=snipeit
DB_PASSWORD=neeraj@1995
APP_URL=http://neeraj.bansal.com
APP_KEY=aAzZc4ZeN4WRFYevPymXKVRu7YtHxctO
DB_DUMP_PATH='/usr/bin'

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER='smtp'
MAIL_HOST='smtp.gmail.com'
MAIL_PORT='587'
MAIL_USERNAME='nrj.engineer@gmail.com'
MAIL_PASSWORD='****************'
MAIL_ENCRYPTION='tls'
MAIL_FROM_ADDR='nrj.engineer@gmail.com'
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR='nrj.engineer@gmail.com'
MAIL_REPLYTO_NAME='Snipe-IT'

**Comment by snipe** [comment]
Do not ever give out your app key. Ever. You should change it now.

If you want to use Gmail, please see our documentation on configuring Snipe-IT using Gmail: https://snipe-it.readme.io/docs/configuration#section-using-gmail
