### ISSUE TITLE
4.0 Beta Upgrade Issue

### ISSUE THREAD

**Issue by raakhtar** [snipe/snipe-it#3863]
when running snipe-it for the 1st time
Oops Error
Class 'MisterPhilip\MaintenanceMode\MaintenanceModeServiceProvider' not found
--
1. Have deleted the compile.php
2. updated the cipher key rijndael-256
3. Tried the upgrade process twice, same result

**Comment by snipe** [comment]
Try blowing out your vendors directory and doing a composer install again
