### ISSUE TITLE
Actions column under assets incorrectly arranged

### ISSUE THREAD

**Issue by raakhtar** [snipe/snipe-it#3865]
Actions column is not positioned correctly

![image](https://user-images.githubusercontent.com/1447175/29456406-8a2a83a2-8426-11e7-87a3-a868022d0e78.png)

**Comment by snipe** [comment]
@raakhtar 
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by raakhtar** [comment]
Version of Snipe-IT you're running - 4.0 Beta 1 
What OS and web server you're running Snipe-IT on Windows / Apache
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) / Manual Installation
If you're getting an error in your browser, include that error
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Any Type of Assets (List All, Deployable, Deployed, etc)
If a stacktrace is provided in the error, include that too. - No
Any errors that appear in your browser's error console. (No)
Confirm whether the error is reproduceable on the demo. - No
Include any additional information you can find in app/storage/logs and your webserver's logs.
Include what you've done so far in the installation, and if you got any error messages along the way.
Indicate whether or not you've manually edited any data directly in the database - No

**Comment by snipe** [comment]
If you show the employee number field in your columns selector, does it resolve?

**Comment by snipe** [comment]
This should be fixed on develop
