### ISSUE TITLE
[v4 API] Statuslabel Mega-ticket

### ISSUE THREAD

**Issue by jasonspriggs** [snipe/snipe-it#3866]
Currently the way that the API handles status labels is kind of odd. When doing a listing of labels, you get a `type` field with options (undeployable, deployable, pending, archived) whereas with a single object get, you get three boolean fields `deployable, archived, and pending`. Additionally, when doing a listing of a single object, these are returned as 0/1 int values instead of false/true bool values. When creating an object, the color, show_in_nav, and notes fields appear to also be disregarded in the creation of the status label. Additionally, when creating an object, the true/false fields that are returned are strings instead of booleans.

**Comment by jasonspriggs** [comment]
Additionally, you can create an object that is both deployable, archived, and pending?

**Comment by snipe** [comment]
> When creating an object, the color, show_in_nav, and notes fields appear to also be disregarded in the creation of the status label

That's only used in the piue chart on the dashboard - otherwise we would have to account for font colors that may not show up on light labels

**Comment by snipe** [comment]
Fixed on dev - pass a status `type` of `pending`, `archived`, or `deployable`

**Comment by jasonspriggs** [comment]
Undeployable should probably also be included

Thank you for taking care of this!
