### ISSUE TITLE
Feature Request: Attach Document to Asset Maintenances

### ISSUE THREAD

**Issue by worthy92** [snipe/snipe-it#3870]
Please could a feature to allow the attaching of documents to Asset Maintenances be added. For example, we have a Dell laptop that gets repaired, the Dell Engineer supplies us with a paper copy detailing the repair etc. I scan this in and currently attach it to the "Files" part of the asset, but it would make sense to have it attached to the asset maintenance entry.

Thanks.

**Comment by sheppyh** [comment]
This would be really useful! Currently attaching the documents to the assets but it's a bit of a mess

**Comment by sheppyh** [comment]
Perhaps we could make this simpler by using the asset Files upload section, but just reference an upload to an "Asset Maintenance"?

**Comment by KFH-IT** [comment]
Just recently started to use SnipeIT and would really like to see this Issue reopened as we're in need of this feature as well.

Either directly attach the Document to the Maintenance or at least create a link to the uploaded File.
