### ISSUE TITLE
[v4 beta] Groups do not display correctly on users page

### ISSUE THREAD

**Issue by james-geiger** [snipe/snipe-it#3873]
#### Expected Behavior (or desired behavior if a feature request)

A user's groups display correctly on the user's table.

-----

#### Actual Behavior

No groups display

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Along with the change to the groups transformer in #3841 ... 

Updating line 94 of /resources/views/users/index.blade.php to read:

`groups += '<a href="#" class="label label-default"> ' + value.rows[index].name + '</a> ';`

Seems to fix this issue for me.

Sorry, this should have been a pull request, but my Git experience is delayed at best.

**Comment by snipe** [comment]
That fix does not work for me.

**Comment by snipe** [comment]
This is now fixed on develop
