### ISSUE TITLE
Show asset tag or asset name in requestable list

### ISSUE THREAD

**Issue by adamcathersides** [snipe/snipe-it#3876]
#### Expected Behavior (or desired behavior if a feature request)

Show the name or tag of the actual asset to request.  

-----

#### Actual Behavior

Currently it seems to only show the model.
I currently have multiple assets that are based on the same model, but I would like to distinguish between them by name.  Is this possible?
Perhaps I am using this incorrectly?

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.6.6 build 1 (gee2c67a)

- What OS and web server you're running Snipe-IT on
Ubuntu 14.04

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Docker

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No notable messages, as far as i can see

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Requestable page

- If a stacktrace is provided in the error, include that too.
n/a

- Any errors that appear in your browser's error console.
none

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
If you have access to the database, you can flip a flag that isn't used anymore. In the `settings` table, change `display_asset_name` to `1`.

**Comment by adamcathersides** [comment]
Thanks for this.

Im using the the snipe-mysql docker, do you know if there is a way to edit the database in the docker?

**Comment by adamcathersides** [comment]
Thanks for your help, this did the trick
