### ISSUE TITLE
Update stable docs to cover Nginx serving from a subdirectory

### ISSUE THREAD

**Issue by alasdaircr** [snipe/snipe-it#3879]
#### Expected Behavior (or desired behavior if a feature request)

Stable documentation covers a working config for Nginx when serving from a subdirectory

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
Stable - v3.6.6

- What OS and web server you're running Snipe-IT on
Debian Jessie / Nginx 1.12.1

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual
-----

Hello. Could you update the documentation to include a working Nginx config for serving from a subdirectory. I've tried a lots of configs for Laravel serving from a subfolder and none work.

**Comment by alasdaircr** [comment]
I've seen this of course: https://snipe-it.readme.io/docs/subdirectories but it's only helpful for Apache users.

**Comment by IronWolve** [comment]
If using centos with nginx+remi php, the default nginx config in the documentation works, just make sure the php+nginx uses the same sock file name and php uses nginx instead of apache for user/group.   Php php-fpm.conf and www.conf.
Example updates.
user = nginx
group = nginx
listen = /var/run/php5-fpm.sock

**Comment by alasdaircr** [comment]
The sample documentation does not cover the case of hosting snipe-it in a subdirectory, which is the point of creating this issue.

**Comment by Rapsoulis** [comment]
I believe your Nginx configuration should look something like this (currently not working for me at least). Although my if I type in my browser "X.X.X.X/snipeit" I get the page about having set the wrong directory, the configuration file isn't working properly.
Posting it so we can find a solution - if I find one I'll post it.

This file should be located in: 

> /etc/nginx/conf.d/snipeit.conf

```
server {
    listen 80;
    server_name snipe-it.domain.xyz;

    root /usr/share/nginx/html/snipe-it/public/;
    index index.php index.html index.htm;

	access_log /var/log/nginx/snipe.access.log;
	error_log /var/log/nginx/snipe.error.log;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        try_files $uri $uri/ =404;
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_index  index.php;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        include        fastcgi_params;
    }
}
```

**Comment by alasdaircr** [comment]
Not sure how that would work - that configuration requires that the snipe `index.php` script is stored in the root folder, something I wanted to avoid.

I can probably resolve this by using NGINX as a proxy but was hoping for something straightforward.

**Comment by Rapsoulis** [comment]
The document root points to the /public folder as stated in the installation. What am I missing?

**Comment by alasdaircr** [comment]
That configuration file is for an install of snipe-it which would be accessed via `https://snipe-it.domain.xyz/`. I'm looking for an nginx config example where I can access via a subfolder. E.g. `https://www.domain.com/snipe-it/`.

**Comment by Rapsoulis** [comment]
@alasdaircr can you try this configuration in your nginx config file?

`location /snipeit {
    root /usr/share/nginx/html/snipeit/public/;
}

location ~ /snipeit/.+\.php$ {
    fastcgi_pass   127.0.0.1:9000;
    fastcgi_param  SCRIPT_FILENAME /usr/share/nginx/html/snipeit/public$fastcgi_script_name;
}`

**Comment by ElDavoo** [comment]
> @alasdaircr can you try this configuration in your nginx config file?
> 
> ```
> location /snipeit {
>     root /usr/share/nginx/html/snipeit/public/;
> }
> 
> location ~ /snipeit/.+\.php$ {
>     fastcgi_pass   127.0.0.1:9000;
>     fastcgi_param  SCRIPT_FILENAME /usr/share/nginx/html/snipeit/public$fastcgi_script_name;
> }
> ```



i'm getting 404 with this one 🤔

**Comment by Mistic92** [comment]
Any update on that? I'm running snipeit on Cloud Run (docker) and wanted to route traffic through GCP loadbalancer for let's say `https://www.domain.com/snipe-it/`. I have changed .htaccess in docker but now I'm getting 500 error 
```
[Wed Jun 22 21:33:59.250868 2022] [core:error] [pid 71] [client 169.254.1.1:33565] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
```

**Comment by uberbrady** [comment]
The only way I can think of it running is having a reverse-proxy server/service in front of Docker that strips the subdirectory out, then passes the request back to the docker container with the directory stripped. Then setting your `APP_URL` to include the subdirectory.

I'll admit I was trying to do something similar to that myself to better troubleshoot issues with subdirectory-based installs. I wasn't able to get it going though.

If anyone had a config for this that actually worked, I'd be happy to update the documentation accordingly. Or, if there were a relatively non-destructive way to add that to the docker image without breaking the 'normal' base-URL stuff that we use, I'd at least consider that.

**Comment by druexmachina** [comment]
Sorry to resurrect this stale issue, but I've made some progress on it! The config below gets the app ~90% there. I'll be honest, I have a decent understanding of nginx configs, but no experience in PHP/FPM..._why_ this config gets them to play nice and resolves the bulk of the issues is beyond me.

After fruitlessly messing with alias and rewrite, the breakthrough changes that solved most of the issues was setting the REQUEST_URI fastcgi_param and turning off gzip. With this config, the navigation issues are fixed, but there's still something going on with the page loads. About 1 in every 5 loads will correctly load the tables on the page and the other attempts will time out. Increasing the various fastcgi timeout settings in nginx didn't resolve it. I don't see anything in nginx/FPM/laravel logs that gives any helpful indicators.

If anyone has any guidance about where to go from here, I'd appreciate it!

Debian 12 (bookworm)
Snipe-IT Build v7.0.9
PHP 8.2 (default FPM `[www]` pool config)
nginx/1.22.1
APP_URL in .env: https://server.name/snipe-it

```
server {
    listen 443 ssl;
    location /snipe-it {
        root /path/to/snipe-it/public;
        index index.php;
        return 301 /snipe-it/;

        location /snipe-it/ {
            rewrite ^/snipe-it(/.*)$ $1 break;
            try_files $uri /snipe-it/index.php$is_args$args;
        }

        location ~ \.php$ {
            gzip off;
            include snippets/fastcgi-php.conf;
            set $saved_request_uri $request_uri;
            if ($request_uri ~ ^/snipe-it(/.*)$) {
                set $saved_request_uri $1;
            }
            fastcgi_param REQUEST_URI $saved_request_uri;
            fastcgi_param SCRIPT_FILENAME $document_root/index.php;
            fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        }
    }
}
```

**Comment by druexmachina** [comment]
Ahhhhh got it! Just needed to have nginx make FPM keep the connection alive (also resolving the gzip issue). Final working config:

```
server {
    listen 443 ssl;
    location /snipe-it {
        root /home/snipeit/snipe-it/public;

        location = /snipe-it {
            return 301 /snipe-it/;
        }

        location /snipe-it/ {
            rewrite ^/snipe-it/(.*)$ /$1 break;
            try_files $uri /snipe-it/index.php$is_args$args;
        }

        location ~ \.php$ {
            set $script_name $fastcgi_script_name;
            if ($fastcgi_script_name ~ ^/snipe-it/(.*)$) {
                set $script_name /$1;
            }
            fastcgi_pass unix:/run/php/php8.2-fpm.sock;
            include fastcgi_params;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$script_name;
            fastcgi_keep_conn on;
        }
    }
}
```
