### ISSUE TITLE
PHP tab not available in WAMP Menu

### ISSUE THREAD

**Issue by mzrt2010** [snipe/snipe-it#3881]
![snipeit](https://user-images.githubusercontent.com/25608022/29650835-73438b48-88ae-11e7-8570-b30c959ab9a6.jpg)
 i started installation of SnipeIT on windows 10 64 and after WAMP 32  installation I Am unable to Select the version of PHP in WAMP ,The PHP not available as per the above screenshot 

please help

**Comment by snipe** [comment]
Unfortunately, that's a WAMP issue and not a Snipe-IT issue. You might try [asking on their forums](http://forum.wampserver.com/list.php?2).
