### ISSUE TITLE
504 Gateway Time-out on new setup

### ISSUE THREAD

**Issue by nopawel** [snipe/snipe-it#3882]
I try to install snipe it on Ubuntu an PHP 7.x. I try to follow the instruction. I had only one problem with No supported encrypter found. The cipher and / or key length are invalid. but i changed to AES and it works. 
But now  i have another problem in Pre-Flight & Setup with 504 Gateway and a i haven't got idea where can i find a problem issue. 

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by nopawel** [comment]
Version of Snipe-IT you're running - 3.6.6 
    What OS and web server you're running Snipe-IT on - Ubuntu 15.10, PHP Version => 5.6.11-1ubuntu3.4
    What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual with git
    If you're getting an error in your browser, include that error - 504 gateway
    What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Pre-Flight & Setup 
    If a stacktrace is provided in the error, include that too.
    Any errors that appear in your browser's error console. - no
    Confirm whether the error is reproduceable on the demo. - no
    Include any additional information you can find in app/storage/logs and your webserver's logs. - no logs
    Include what you've done so far in the installation, and if you got any error messages along the way.
I begining instaltion step by step. Only problem i had with enryption.
    Indicate whether or not you've manually edited any data directly in the database - no

**Comment by nopawel** [comment]
O i resolved my problem. That was problem with premissions
