### ISSUE TITLE
[QUESTION] What kind of alerts does Snipe-IT send?

### ISSUE THREAD

**Issue by uussaammaahh** [snipe/snipe-it#3883]
I am sorry, this is just a question, I did not know how to contact you. It would be really appreciated if you answer my questions:
1. Will Snipe-IT be applicable if I have computers/laptops as assets and I want to know when their warranty date arrives in a few days.
2. If I have software licenses and I wish to know their expiration date before it arrives.
3. If I have AMCs for air conditioners etc. and their date is arriving.

It would be really appreciated if you answer all these in points.

Regards

**Comment by snipe** [comment]
Hi @uussaammaahh - warranty and license expirations are included in Snipe-IT.
https://snipe-it.readme.io/docs/configuring-alerts
https://snipe-it.readme.io/docs/configuring-alerts-backups

**Comment by uussaammaahh** [comment]
Thank you, just 1 last question,
If 'Expiring Alerts Threshold (in days)' is kept to 7 does this mean that if my warranty is ending on 25th September 2017, the system will send me an alert email 7 days from warranty expiring date?

Thank you!
