### ISSUE TITLE
SQL Issues

### ISSUE THREAD

**Issue by ericdude101** [snipe/snipe-it#389]
I use SQL Server 2008 in my network and I updated the database .php file to reflect this, but when I run "php artisan app:install" it returns: 

"Application key [HIDDEN] set successfully.

  [InvalidArgumentException]
  Database [] not configured.

app:install
C:\inetpub\techweb\snipe-it> "

================================
Here is my database php file:
================================
 /*
    |--------------------------------------------------------------------------
    | Default Database Connection Name
    |--------------------------------------------------------------------------
    |
    | Here you may specify which of the database connections below you wish
    | to use as your default connection for all database work. Of course
    | you may use many connections at once using the Database library.
    |
    */

    'default' => 'sqlsrv',

    /*
    |--------------------------------------------------------------------------
    | Database Connections
    |--------------------------------------------------------------------------
    |
    | Here are each of the database connections setup for your application.
    | Of course, examples of configuring each database platform that is
    | supported by Laravel is shown below to make development simple.
    |
    |
    | All database work in Laravel is done through the PHP PDO facilities
    | so make sure you have the driver for your particular database of
    | choice installed on your machine before you begin development.
    |
    */

    'connections' => array(

        'sqlite' => array(
            'driver'   => 'sqlite',
            'database' => __DIR__.'/../database/production.sqlite',
            'prefix'   => '',
        ),

        'mysql' => array(
            'driver'    => 'mysql',
            'host'      => 'localhost',
            'database'  => 'snipeit_laravel',
            'username'  => 'snipeit_laravel',
            'password'  => '',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ),

        'pgsql' => array(
            'driver'   => 'pgsql',
            'host'     => 'localhost',
            'database' => 'database',
            'username' => 'root',
            'password' => '',
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
        ),

        'sqlsrv' => array(
            'driver'   => 'sqlsrv',
            'host'     => 'HIDDEN',
            'database' => 'snipeit',
            'username' => 'snipeit',
            'password' => 'HIDDEN',
            'prefix'   => '',
        ),

What do I need to do to get things working here?

**Comment by snipe** [comment]
Not sure this will work with SQL Server. The `MODIFY` syntax doesn't exist in SQL server.

**Comment by deln2403** [comment]
Hello. Has this been fixed? If sql server is not supported it would be nice if the documentation would say so. That way we wouldn't waste time attempting. Alternatively, it would be great if it worked...

**Comment by snipe** [comment]
The requirements specify MySQL or MariaDB

**Comment by deln2403** [comment]
The sqlsrv connection info inside of database.php is a little misleading. I ended up using MySQL. Thanks for the quick response. The site is great.
