### ISSUE TITLE
[HELP] No emails working

### ISSUE THREAD

**Issue by uussaammaahh** [snipe/snipe-it#3890]
#### Expected Behavior (or desired behavior if a feature request)

1. When clicking forgot password link and entering the email the user should reset link
2. Adding new user, the new user should get the email with all the details

-----

#### Actual Behavior

None of the above points are working with me, I tried everything I could understand to solve this, I would really appreciate it if you would help me with this. No emails are getting sent from the server.

I only get this "Whoops, looks like something went wrong." [http://i.imgur.com/WVRIPft.png](url)

-----

#### Please confirm you have done the following before posting your bug report:

- [yes] I have enabled debug mode
- [yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running v3.6.6 build 1
- What OS and web server you're running Snipe-IT on Linux
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Softaculous
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error [http://i.imgur.com/QUEsK43.jpg](url)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error Any page where sending emails function is required
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). No it's working on the demo
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database None

**Comment by snipe** [comment]
The debugging message is telling you what's wrong. The SSL certificates don't match.

**Comment by uussaammaahh** [comment]
Could you kindly elaborate a little more please. Because I do not understand anything related to this. The server which I am using is using Zoho mail as the mail exchanger. I don't know how to overcome this. Any hint would be helpful.

**Comment by snipe** [comment]
It means you're probably using the wrong hostname for the email server. You should get in touch with Zoho to find out what you should be using to send mail from an application.
