### ISSUE TITLE
Bad link for manager in people list

### ISSUE THREAD

**Issue by benunter** [snipe/snipe-it#3892]
On people page (/admin/users), the link for manager for each people is missing /admin/users/ in the URL, then a 404 page appears when clicking on link. 

The error is also present on the demo (https://snipeitapp.com/demo).

I get this with this deployment:
- Version of Snipe-IT: v3.6.6 build 1 (gee2c67a)
- OS: Debian 9; web server: apache2 2.4.25-3+deb9u2 with docker
- Nothing with DEBUG mode

**Comment by snipe** [comment]
This is fixed in the upcoming v4 (on develop)
