### ISSUE TITLE
  Command "app:install" is not defined.

### ISSUE THREAD

**Issue by rakecurray** [snipe/snipe-it#3893]
I have been following the guide below to install snipe-it on CentOS 7 i can get to the end of the install but the app:install command doesnt work.
https://mangolassi.it/topic/6967/installing-snipe-it-on-centos-7-and-mariadb/2

Website shows "Whoops, looks like something went wrong."

[root@Snipe-IT snipeit]# php artisan app:install

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "app:install" is not defined.
  Did you mean one of these?
      migrate:install
      app:name

**Comment by snipe** [comment]
That command no longer exists. Please see [the official documentation on installing Snipe-IT](https://snipe-it.readme.io/docs).

**Comment by rakecurray** [comment]
Is there a command to replace this? I am not very experienced with this
