### ISSUE TITLE
V4 install Stuck at Pre-Flight user Creation

### ISSUE THREAD

**Issue by Bishop200** [snipe/snipe-it#3894]
#### Expected Behavior (or desired behavior if a feature request)

That the user gets created and then finish the install

-----

#### Actual Behavior

It's just refresh the page, the password field got emptied.
-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running : 
Should be 4 beta 2
- What OS and web server you're running Snipe-IT on 
Centos 7 with apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) 
Manual install with Git clone
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
snipe/setup/user?
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
I got that, but it's been 2 hours since the last time it's log it.

[2017-08-25 11:52:39] production.ERROR: exception 'ErrorException' with message 'file_put_contents(/var/www/html/snipeit/storage/framework/sessions/a2NINKaahz2R69n0RnU4LleYBqEMZqwzmdX2yH1y): failed to open stream: Permission denied' in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:111
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/s...', 111, Array)
#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(111): file_put_contents('/var/www/html/s...', 'a:2:{s:6:"_toke...', 2)
#2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php(83): Illuminate\Filesystem\Filesystem->put('/var/www/html/s...', 'a:2:{s:6:"_toke...', true)
#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Session/Store.php(129): Illuminate\Session\FileSessionHandler->write('JweDY0vrnyHnsWk...', 'a:2:{s:6:"_toke...')
#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(88): Illuminate\Session\Store->save()
#5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(216): Illuminate\Session\Middleware\StartSession->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#6 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(187): Illuminate\Foundation\Http\Kernel->terminateMiddleware(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#7 /var/www/html/snipeit/public/index.php(63): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#8 {main}  
error

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
No
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
No error in apache log. Laravel log have those, but no new one for the last 2 hours there too.

[2017-08-25 11:52:39] production.ERROR: exception 'ErrorException' with message 'file_put_contents(/var/www/html/snipeit/storage/framework/sessions/a2NINKaahz2R69n0RnU4LleYBqEMZqwzmdX2yH1y): failed to open stream: Permission denied' in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:111
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/s...', 111, Array)
#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(111): file_put_contents('/var/www/html/s...', 'a:3:{s:6:"_toke...', 2)
#2 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php(83): Illuminate\Filesystem\Filesystem->put('/var/www/html/s...', 'a:3:{s:6:"_toke...', true)
#3 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Session/Store.php(129): Illuminate\Session\FileSessionHandler->write('a2NINKaahz2R69n...', 'a:3:{s:6:"_toke...')
#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(88): Illuminate\Session\Store->save()
#5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(216): Illuminate\Session\Middleware\StartSession->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#6 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(187): Illuminate\Foundation\Http\Kernel->terminateMiddleware(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#7 /var/www/html/snipeit/public/index.php(63): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#8 {main}

- Include what you've done so far in the installation, and if you got any error messages along the way.
Got some error that i have fixed caused by selinux. I have also try with setenforce 0 
I have been able to create a user with php artisan as explain there https://snipe-it.readme.io/v4.0/docs/create-an-admin

- Indicate whether or not you've manually edited any data directly in the database
Nope

**Comment by snipe** [comment]
Permissions on your storage directory are wrong. That dir and all subsdirectories within it need to be writable by the webs server.

**Comment by Bishop200** [comment]
So i have try again after doing those command :

chown -R apache:apache storage public/uploads
chmod -R 755 storage
chmod -R 755 public/uploads

Still the same result.
Any idea ?

**Comment by snipe** [comment]
Try checking if SELinux is installed. https://snipe-it.readme.io/docs/linuxosx#section-notes-on-selinux

**Comment by Bishop200** [comment]
It's installed but disabled for now with setenforce 0

**Comment by Bishop200** [comment]
sestatus result 

SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      28

**Comment by DC1LEX** [comment]
Bishop200: did you ever get this resolved? I am at the same point...

Thanks
Alex

**Comment by Bishop200** [comment]
No, i ended up doing a fresh install.
