### ISSUE TITLE
DNS reroute

### ISSUE THREAD

**Issue by ImmortalMasterC** [snipe/snipe-it#3895]
When I reroute the local host (192.168.120.86) on my DNS to snipeit.mysite.com i get the following Error 

Not Found

The requested URL /login was not found on this server.

Apache/2.4.18 (Ubuntu) Server at snipeit.kabafusion.com Port 80

Not sure what extra steps i need to take

**Comment by KeenRivals** [comment]
Sounds like your Apache configuration needs work. Check your access/error logs in ``/var/log/apache2`` for hints as to what is wrong. My guess is it's something with your [VirtualHost config](https://httpd.apache.org/docs/current/vhosts/examples.html).

**Comment by ImmortalMasterC** [comment]
I was able to resolve this can now be closed
