### ISSUE TITLE
Dashboard landing page for non admin users

### ISSUE THREAD

**Issue by imomair** [snipe/snipe-it#3896]
Dear Snipe,
Now when a normal user logs in it land to page having Assets assigned to user ...etc

is it possible that after login user (non admin) lands on the same dashboard as admin or other user as attached 
<img width="1279" alt="screen shot 2017-08-26 at 1 44 34 pm" src="https://user-images.githubusercontent.com/31367397/29740688-bf1a8d02-8a64-11e7-974b-b97dfccbd4cd.png">

**Comment by snipe** [comment]
We do it the way we do because not all users do (or should) have access to that information
