### ISSUE TITLE
Notify user with checked out asset that someone has requested it

### ISSUE THREAD

**Issue by adamcathersides** [snipe/snipe-it#3904]
#### Expected Behavior (or desired behavior if a feature request)

When requesting an asset, is it possible to notify the user that currently the asset checked out that some one has requested it? 

-----

#### Actual Behavior

----

#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
Docker  v3.6.6 build 1 (gee2c67a)
- What OS and web server you're running Snipe-IT on
Ubuntu 14.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
That's not currently possible, and I'm not sure how helpful that would be to most users. In our experience, the way most people use Snipe-IT, it would be more disruptive than helpful, since most end-users aren't even aware of Snipe-IT, and IT managers would handle all that. 

I'd be willing to entertain some use-cases and would consider merging a pull request if someone built this though.
