### ISSUE TITLE
[Dashboard] Asset Status - Deployed shown twice

### ISSUE THREAD

**Issue by jeroenbrussich** [snipe/snipe-it#3905]
#### Expected Behavior (or desired behavior if a feature request)

I would like to see the 3 most common statusses on the Dashboard: ready to deploy, pending and deployed

-----

#### Actual Behavior

I do not see pending but I see deployed twice - http://imgur.com/9ysh5Si
I can confirm the default statusses are still there, if I change the status of one of my devices to pending, I get a similar problem -> http://imgur.com/a/of3bX

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
Version v3.6.6 build 1 (gee2c67a)
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
not applicable
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
dashboard
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
no
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
no
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
no

**Comment by linglongtong** [comment]
![image](https://user-images.githubusercontent.com/23185284/29954211-caac8000-8f08-11e7-9fea-46084a701f76.png)

![image](https://user-images.githubusercontent.com/23185284/29954232-e649d5ec-8f08-11e7-996d-72a5c5910c7e.png)

I met the same problem.

**Comment by snipe** [comment]
That's not a bug, it's just how it works, since you have a status label of "Deployed", and there is the meta-status type of "Deployed" (Ready to Deploy + Deployed to someone). https://snipe-it.readme.io/docs/overview#section-status-labels
