### ISSUE TITLE
V4 Beta 3 LDAP AD auth

### ISSUE THREAD

**Issue by Bishop200** [snipe/snipe-it#3907]
When configuring LDAP with AD, the test button keep showing a red triangle, but going under people and using sync his working. I can log in with a domain user but i can't edit them in snipeIT. I get the error

Error: Please check the form below for errors
The username field is required.

But the username field his : (Managed via LDAP)

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v4.0 build beta3 (22)
- What OS and web server you're running Snipe-IT on
Centos 7 and apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual Inatall with Git clone
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
 Error: Please check the form below for errors
The username field is required.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
http://snipeit4/users/19/edit
Trying to save any modification to user
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
No

**Comment by Bishop200** [comment]
Adding my LDAP config just in case i have made a mistake there.

![config snipe](https://user-images.githubusercontent.com/27506705/29886560-7c389c5a-8d88-11e7-9ede-ab7009374efc.PNG)

**Comment by Samgarr** [comment]
Same issue here.

**Comment by snipe** [comment]
Do a fresh pull from the develop branch and tell me if this issue is resolved please.

**Comment by Bishop200** [comment]
Same problem, but now it's writing "validation.required_unless" instead of "The username field is required".

**Comment by snipe** [comment]
Give it another try please.

**Comment by azmcnutt** [comment]
The latest dev pull fixed the issue with saving a user.  However, I still get a red triangle whenever I click test within the LDAP screen.  However, importing users, ldap user logon, and editing users works now.
![image](https://user-images.githubusercontent.com/31522486/29946534-9cf2661a-8e5a-11e7-9195-ceccebc6bd0d.png)

**Comment by snipe** [comment]
Without info from your error logs, I wouldn't be able to determine what's causing that.

**Comment by azmcnutt** [comment]
Hi Snipe. I only posted because it was part of the OP's issue. 

I'm more than happy to provide logs or I could start a new issue to cover only the Test LDAP button issue. 

Which would you  prefer?

**Comment by snipe** [comment]
New issue please - thanks :) (The two issues are unrelated)

**Comment by Bishop200** [comment]
It's working, i can edit the user now :)
