### ISSUE TITLE
LDAP crendetials issues

### ISSUE THREAD

**Issue by Samgarr** [snipe/snipe-it#3910]
#### Expected Behavior (or desired behavior if a feature request)

I expect working LDAP authetication with provided credentials.

If i provide LDAP credentials (eg givenName), snipeit cannot create/login user because function parseAndMapLdapAttributes cannot match right array key because all array keys was lowercased in findAndBindUserLdap function.
Also if LDAP mail field is left empty, LDAP auth not working because $user array is malformed.
Let me know if more information is needed.

-----

#### Actual Behavior

User from LDAP isn't created, login not working.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
Debian 8, Version v4.0 build beta 2 (46)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
specific error isn't provided
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
> If i provide LDAP credentials (eg givenName), snipeit cannot create/login user because function parseAndMapLdapAttributes cannot match right array key because all array keys was lowercased in findAndBindUserLdap function.

We document the required caseing here: https://snipe-it.readme.io/docs/ldap-sync-login

> Also if LDAP mail field is left empty, LDAP auth not working because $user array is malformed.

So, don't leave it empty? What specific error are you getting?

**Comment by Samgarr** [comment]
Ah, i misslook thant caseing tip, sorry. Anyway, thanks for fixing this.

> So, don't leave it empty? What specific error are you getting?
Strange, i cannot simulate that issue again. You can close this issue for now.
