### ISSUE TITLE
[HELP] Show all columns always / open image in new tab

### ISSUE THREAD

**Issue by uussaammaahh** [snipe/snipe-it#3913]
@snipe I really appreciate this application, it has cut my work in half. I want to thank you for all the hard work put into this.

1. **Whenever I login to my system after a reboot the columns selection goes back to the original one**

<a href="http://i.imgur.com/GBn9QK9.png" target="_blank"><img src="http://i.imgur.com/GBn9QK9.png" /></a>

Can I keep all of them _selected always_, or my _desired choice_ which I wish to select by editing the code so that it always opens to those columns only? (if yes could you guide me to the right path in all of the variations - assets, licenses, accessories and consumables)

2. **If clicked on the Device Image in the table, it would _open the image in a new tab_**

<a href="http://i.imgur.com/q4MFbX7.png" target="_blank"><img src="http://i.imgur.com/q4MFbX7.png" /></a>

Regards

**Comment by snipe** [comment]
The selections are handled via cookie, so I'm guessing you have a setting somewhere that deletes your cookies when you restart.

**Comment by uussaammaahh** [comment]
@snipe Alright. Got it and fixed it. Thank you 😊.  And the 2nd point about the image opening in new tab?

**Comment by snipe** [comment]
It's supposed to open in a modal, but in a new window (I think?) We'll try to get that fixed for final v4 release, but if not we'll get it fixed soon after.

**Comment by snipe** [comment]
Should be in a modal again as of the latest version.
