### ISSUE TITLE
Question: is there a way to limit access to group of people to some assets?

### ISSUE THREAD

**Issue by mkola-greenliff** [snipe/snipe-it#3915]
Hi,

Can I limit access to some (not all) assets to group of people?
For example I have two groups: A and B. Group A should see only three of assets, and group B the rest of them. I don't think it is currently supported - but maybe it is on the feature list?

Thanks for any answer,
Mathias

**Comment by Bishop200** [comment]
You could cheat it by enabling Full Multiple Companies Support in General setting and putting the 3 asset in one compagnie and the rest in the other.

Could be nice to have a control by group or department.

**Comment by mkola-greenliff** [comment]
Hi,

Many thanks for answer - last question - I don't see a way to assign whole group to company - only users. Can I kindly request such feature? I have ~100 users in my company, all of them from ldap database. Clicking on each to assign proper company seems to be bad idea.

Mathias
