### ISSUE TITLE
Test LDAP button indicates failure, but LDAP import works

### ISSUE THREAD

**Issue by azmcnutt** [snipe/snipe-it#3918]
#### Expected Behavior (or desired behavior if a feature request)

When clicking test on the LDAP settings screen and settings are correct, a success message is expected.

-----

#### Actual Behavior

When clicking test on the LDAP settings screen, a red triangle is displayed without any error message.  Indicating something is wrong.  However, when going to People --> LDAP --> Import, users are imported.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: **v4.0 build beta3 (22) - Pulled from Dev branch on 8/31/17**
- What OS and web server you're running Snipe-IT on:  **Windows Server 2008R2 with IIS 7**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): **Manual**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: **No errors with debug turned on**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: **/admin/ldap**
- If a stacktrace is provided in the error, include that too.: **None**
- Any errors that appear in your browser's error console.:  **A red triangle near the Test LDAP button**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).:  **No - I suspect because the demo is not on V4**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.:  **No logs were generated**
- Include what you've done so far in the installation, and if you got any error messages along the way.:  **Setup has been running for a few months and is working perfectly after v4 update otherwise.**
- Indicate whether or not you've manually edited any data directly in the database:  **No**

Red Triangle near Test LDAP Button:
![ldap1](https://user-images.githubusercontent.com/31522486/29974482-dc0aa3ca-8ee7-11e7-914b-ead642c072b5.PNG)

However, here is a screen capture of LDAP records importing:
![ldap2](https://user-images.githubusercontent.com/31522486/29974560-22d32192-8ee8-11e7-8e87-f329cc049607.PNG)

LDAP settings (with some specific server info removed:
LDAP enabled: **Checked**
Active Directory: **Checked**
LDAP Password Sync: **Unchecked**
Active Directory domain: **[my internal fqdn] (xx.crsk12.org**
LDAP Server: **ldaps://[server].xx.crsk12.org**
Use TLS:  **Uncheck**
LDAP Bind Username:  **[DN of my LDAP user] -
 CN=[username],OU=[org unit],DC=xx,DC=crsk12,DC=org**
LDAP Bind Password: **confirmed correct password**
Base Bind DN: **OU=[org unit],DC=xx,DC=crsk12,DC=org**
LDAP Filter: **&(cn=*)**
Username Field:  **samaccountname**
Last Name: **sn**
LDAP First Name:  **givenname**
LDAP Authentication query:  **samaccountname=**
LDAP Version:  **3**
LDAP Active Flag:  **[blank]**
LDAP Employee Number:  **[blank]**
LDAP Email:  **mail**

Snipe: I know you asked for logs, but I did not see any logs being generated.  Perhaps there is something I missed when reading the Getting Help section.  Please let me know what logs you need.
No logs were generated in snipe/storage/logs (I did delete the existing log file before I started - so perhaps I broke something in the process)
Web logs generated by IIS did not indicate any failure

Thank you.

**Comment by snipe** [comment]
Without logs, there's honestly not going to be a way I can troubleshoot this for you. I have no way of knowing what the server is doing, where it's failing, etc. As long as your import is working, I wouldn't worry about the button too much tho.
