### ISSUE TITLE
Incorrect URL Preflight Check

### ISSUE THREAD

**Issue by timjcraig** [snipe/snipe-it#3920]
Set URL  in .env to https://<server url> when run Pre Flight check gives following result:

URL |   | Uh oh! Snipe-IT thinks your URL is https://<server url>, but your real URL is http://<server url>:443/setup Please update your APP_URL settings in your  .env file. 

Checked .env is getting read ok by changing APP_URL to different url. 

- Version of Snipe-IT you're running  
**Cloned from master** 
- What OS and web server you're running Snipe-IT on
**Ubuntu 16.04 and Apache2**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
**Manual installation** 
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
**No debug error in browser**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
**Pre-Flight Setup**

**Comment by snipe** [comment]
I believe that's already been fixed in the upcoming v4
