### ISSUE TITLE
Pre Flight Test - Can't send test e-mail - Either CSF or is blocking or doesn't work with Office 365

### ISSUE THREAD

**Issue by haynes11** [snipe/snipe-it#3921]
#### Expected Behavior (or desired behavior if a feature request)

Test e-mail goes through fine
-----

#### Actual Behavior

(what actually happens goes here)
Hi,

I'm installing SNIPE-IT using the "git-clone" method. All is going well up until the point of running the setup. The Pre-flight setup verifies all is well except when I try to run a test e-mail which fails. I'll post the log file shortly.

The e-mail is hosted on office 365 and all settings I believe to be correct. This is running on a private Cpanel server that I manage and all e-mail MX records point to Office 365. The server also has Config Server Firewall Installed. After a lot of investigation I've worked out that if I disable CSF the "Test E-mail" button works and turns green. The second I turn it back on it stops. So something on the CSF end is stopping this from functioning.

I've looked through allowed ports etc and 587 is definetely on there so I'm a little stuck on where to look in CSF that may be blocking it from talking to office 365 properly. The logs suggest that it can't hit the office 365 server at all...

Any ideas?

Here's a screenshot of the logs... 
![image](https://user-images.githubusercontent.com/19718532/30007540-ffacc786-9108-11e7-9f7c-d8308222c33f.png)

Here is a screenshot of my .env settings...

![image](https://user-images.githubusercontent.com/19718532/30007551-54b4df34-9109-11e7-8b23-69ba2453b4b8.png)

 
-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - Latest 
- What OS and web server you're running Snipe-IT on - Cent OS 6/CLOUD Linux
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Via github so manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - Not web page related
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Pre-Flight Setup Page - E-mail test

**Comment by snipe** [comment]
That looks like a possible firewall issue - it's not related to Snipe-IT itself.

**Comment by haynes11** [comment]
You were right. CSF has an option called "SMTP Block" which by default is set to on. However in the hundreds of settings if you don't know about SMTP block you would have no idea to search for it and wonder why mysteriously even though outbound traffic to the right ports are open why SMTP isn't working but anything else that wants to talk out of that port is!

**Comment by snipe** [comment]
Glad you got it figured out!
