### ISSUE TITLE
V4-Beta3 - Missing en lang values

### ISSUE THREAD

**Issue by BrettFagerlund** [snipe/snipe-it#3924]
When viewing a deleted user from URL such as 
snipeit.local/users/1 

There will be a message displayed like
"general.user_deleted_text Click_here general.to_restore_them"
There is no values for user_deleted_text and to_restore_them in the en lang files

Version v4.0 build beta3 (22)

**Comment by snipe** [comment]
Should be fixed on dev now - thanks!
