### ISSUE TITLE
Domain Name [feature request]

### ISSUE THREAD

**Issue by haynes11** [snipe/snipe-it#3925]
#### Expected Behavior (or desired behavior if a feature request)

I expect it wouldn't be difficult to add > Can we have a list/asset/license type (Whichever is the best way of doing it) for Domain names?

So we can have a list of domain names > Who supplied them- So it could link with the supplied list (EG: Go Daddy)

It would simply be a list of domain names, their registered date/renewal date, notes and who it's registered to or something?

Best,
Jerome Haynes
#

**Comment by PhilipWith1L** [comment]
Have there been any other similar requests to this? Using Licenses or other models to track domain name registrations? It might also apply to IP blocks, since they work similarly with expiration dates.

**Comment by hreid1978** [comment]
I see that this is closed but was wondering if it has maybe been done or opened in another feature request?

**Comment by altkraft** [comment]
Hopefully someone will pay attention to this request.

**Comment by jrdwiz** [comment]
I think this would be a great addition.

**Comment by snipe** [comment]
Licenses sort of already does this. Just create a license category for "Domain names"
