### ISSUE TITLE
unable to checkout licenses

### ISSUE THREAD

**Issue by roadhowse** [snipe/snipe-it#3926]
#### Expected Behavior (or desired behavior if a feature request)
Click check out and fill out boxes accordingly to assign a license to a user
(what you expect to happen goes here)
Click check out and fill out boxes accordingly to assign a license to a user
-----

#### Actual Behavior
an entirely different record opens. i click checkout on pagerduty and adobe record comes up.
(what actually happens goes here)
an entirely different record opens. i click checkout on pagerduty and adobe record comes up.
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running v3.6.6
- What OS and web server you're running Snipe-IT on Windows 7, self hosted
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database, no

**Comment by roadhowse** [comment]
i am new here, please excuse my lack of protocol

**Comment by snipe** [comment]
This sounds like your data might be messed up somehow. If it's not throwing an error, there's not much I can do to help you though, since no one else has reported this issue.
