### ISSUE TITLE
v4.0 expected release date

### ISSUE THREAD

**Issue by oli415** [snipe/snipe-it#3931]
Hi,

Can you by any chance estimate when the new 4.0 version will be released as a stable latest release?

Would love to install it in September :).

Thanks,
Oliver

**Comment by snipe** [comment]
Our milestone deadline for 4.0 is mid-Sept (the 17th). I wish I could give you a harder guarantee than that, but we also will not release software if we're not pretty sure we're not going to create issues with it. This release will be the one that took the longest in the entire lifetime of the project, and no one wants it released more than us, so I promise you that we will release the moment we're sure it's ready. Tons of moving parts in a project this big, and hundreds of kinds of data sets, so testing takes time.

**Comment by oli415** [comment]
Great, I understand :). Thanks for the reply!
