### ISSUE TITLE
Suggestion for making the MAC Address format multi-valued. 

### ISSUE THREAD

**Issue by beb-bang** [snipe/snipe-it#3935]
#### Expected Behavior (or desired behavior if a feature request)

Just started using snip-it about two weeks ago to create a consolidated asset management system from many sources and love it! Since many sources feed our system, I need unique IDs that can be used to match assets across systems. SMBIOS GUID (custom filed) is great for computer assets, but for network equipment and appliances I've been using the MAC address. It's imperfect, but close enough. 

This is just a minor suggestion to make the MAC address format validation multi-valued. 

The expected behavior was that I could enter multiple MAC addresses in a custom field with MAC address format validation. 

-----

#### Actual Behavior

When I selected the MAC format, the regex limits me to one address. Some assets (like storage arrays, VMWare hosts, hosts with multiple NICs) have more than one MAC address that I'm tracking. I was attempting to reconcile assets in snipe-it to our network discovery and vulnerability management system. 

I created a custom field with the following regex that permits one or more MAC addresses separated by a comma. Changing the out-of-box MAC address format to something like this would permit multiple values when selecting "MAC Address" format. 

`regex:/^([0-9a-fA-F]{2}[:-]){5}[0-9a-fA-F]{2}|([0-9a-fA-F]{2}[:-]){5}[0-9a-fA-F]{2}(,([0-9a-fA-F]{2}[:-]){5}[0-9a-fA-F]{2})*/`

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v3.6.6 build 1 (gee2c67a)

- What OS and web server you're running Snipe-IT on
4.9.43-17.38.amzn1.x86_64

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual installation

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
NA

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Custom field configuration, new asset

- If a stacktrace is provided in the error, include that too.
NA

- Any errors that appear in your browser's error console.
NA

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
NA

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
NA

- Include what you've done so far in the installation, and if you got any error messages along the way.
NA

- Indicate whether or not you've manually edited any data directly in the database
Oh, definitely. We've integrated System Center Configuration Manager, Office 365 (for ActiveSync Assets), and nmap data for network equipment, printers and more. Currently working on a status update from the vulnerability management system. Very excited about the new API! :-) 

Thx!
Bryan

**Comment by snipe** [comment]
Rather thank junking up the code with a field folks may or may not need, we've started a ["Regex Recipes" section of the docs](https://snipe-it.readme.io/v4.1.6/docs/custom-fields#section-common-custom-fields-regexes) that folks can use with the custom regex type.
