### ISSUE TITLE
Asset labels not printing correctly on small format individual labels

### ISSUE THREAD

**Issue by pepsin92** [snipe/snipe-it#3942]
#### Expected Behavior (or desired behavior if a feature request)

I would like to print labels on 62x29 mm labels (2-3/7''x1-1/7''). Size settings in snipe-it are following:
![Snipe-it settings](https://user-images.githubusercontent.com/7819599/30270668-b139fb7e-96ed-11e7-944e-d4da8b40d852.png)

-----

#### Actual Behavior

The labels are split onto multiple labels, misaligned and/or rotated.
![Using Chrome print dialog](https://user-images.githubusercontent.com/7819599/30270957-c7d73eea-96ee-11e7-87be-38633b47bbab.jpg)
![Using system dialog](https://user-images.githubusercontent.com/7819599/30270959-cbbb768e-96ee-11e7-9569-e5f5c2dcf4a4.jpg)

System dialog produced margins even though margins were disabled. Printing to PDF produces the same results.

-----

#### Suggested solution

I realize the issue is in the printing of HTML. Having and option to generate PDFs directly would more than likely solve this issue, as it provides better compatibility with printer driveers and portability.

I would like to implement this, if it had a chance of getting merged into upstream.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:
- What OS and web server you're running Snipe-IT on
  - *Manjaro Linux, Apache2*
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  - *Docker, following official documentation.*
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
  - *Yes*

**Comment by vasilisrac** [comment]
Same problem Here. 
Im using the following printer: Brother QL-720NW and 29mm x 90.3mm (1.1 x 3.5) labels but i can't print them at all. I have already adjust the label's size from the admin panel. I think that if we can change the output paper size of the labels would be solve the problem.
