### ISSUE TITLE
How to upgrade to v4 via git

### ISSUE THREAD

**Issue by haynes11** [snipe/snipe-it#3943]
Hi,

Probably a silly question as I'm not so used to git. I've attempted a few times to work out how to do this and am not getting anywhere after some research.

I have Snipe-IT version 3 installed.

How do I upgrade to the latest v4 beta via git?

Best,
Jerome Haynes

**Comment by IrisDande** [comment]
Read this release note
https://github.com/snipe/snipe-it/releases/tag/v4.0-beta5

**Comment by haynes11** [comment]
Hi,

This is for when you've already pulled down the files and doesn't mention anything to do with git?

Obviously git pull just pulls down the master branch files. But when I try switching branches to develop and pulling down this version I run into errors/issues. So just wanted to know the 100% correct process off pulling down the files off git so I know I'm not doing it wrong.

Best,
Jerome Haynes

**Comment by snipe** [comment]
> This is for when you've already pulled down the files and doesn't mention anything to do with git?

That's what you do right after you've pulled the new files from git.

What errors are you seeing?

**Comment by haynes11** [comment]
Sorry no - I realised a bunch of stuff had corrupted on my server and that's why git and everything was freaking out. I've restored from backup to v3 and all looks good.

However I have been unsuccessful in pulling down from the develop branch - that as far as I can tell is the branch your latest beta is on? Can you just verify to me what the steps are to pull the latest develop version of Snipe-IT via git?

Best,
Jerome

**Comment by snipe** [comment]
> However I have been unsuccessful in pulling down from the develop branch

```
git checkout develop
git pull
```

That should do it.

**Comment by haynes11** [comment]
Same thing appearing, only changed a few files which doesn't seem right to me?

```
root@webhost assettracker]# git checkout develop
warning: refname 'develop' is ambiguous.
error: Your local changes to the following files would be overwritten by checkou                                                                                                                                                                                                                                             t:
        resources/views/hardware/view.blade.php
Please commit your changes or stash them before you switch branches.
Aborting
[root@webhost assettracker]# git pull
From https://github.com/snipe/snipe-it
   81e358a0..ed4ea7f1  master     -> origin/master
   6c283de6..e7d72beb  develop    -> origin/develop
Updating fd515654..ed4ea7f1
error: Your local changes to the following files would be overwritten by merge:
        app/Http/Controllers/GroupsController.php
        resources/views/hardware/view.blade.php
Please commit your changes or stash them before you merge.
Aborting
[root@webhost assettracker]# git stash
Saved working directory and index state WIP on master: fd515654 Fix broken user'                                                                                                                                                                                                                                             s manual link (#3902)
[root@webhost assettracker]# git pull
Updating fd515654..ed4ea7f1
Fast-forward
 app/Http/Controllers/AssetMaintenancesController.php |  2 +-
 app/Http/Controllers/GroupsController.php            | 14 ++++++--------
 resources/views/hardware/view.blade.php              |  6 +++++-
 3 files changed, 12 insertions(+), 10 deletions(-)

```

**Comment by snipe** [comment]
Do you have local changes?

**Comment by haynes11** [comment]
To be honest, this probably isn't worth investigating as I was going to setup a new install with the latest develop version anyway. Though isn't the new version due out in a few days? I may just wait and update/re-install then

**Comment by snipe** [comment]
It's been "due out in a few days" for a few months lol.

We're trying to wrap up a few inconsistencies with the importer and potential cipher issues that will affect community users and hosted customers, but that's all that's left now.

**Comment by haynes11** [comment]
Ah always the way with development! I'm no developer myself but I know exactly what it's like. Thanks for your help on this, really great software and I'd love to donate once I get it working! I'm really looking forward to the new version, that's really going to sell it for me.

**Comment by snipe** [comment]
Thanks! There are SO many changes, we've been trying to detail them all (at least partially) here: https://snipe-it.readme.io/blog/whats-new-in-snipe-it-v4

I'm going to close this for now, but if you change your mind and want to fight through it, reply and I'll re-open :)
