### ISSUE TITLE
Checkin asset produces error

### ISSUE THREAD

**Issue by ybilleh** [snipe/snipe-it#3946]
#### Expected Behavior (or desired behavior if a feature request)

I expect the checkin function to checkin the asset and return to the list of assets

-----

#### Actual Behavior

Produces an error which reads "Whoops, looks like something went wrong"

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.6.6 build 1 (gee2c67a)
- What OS and web server you're running Snipe-IT on: Ubuntu Server 14.04.5 amd64
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error:
---
Whoops, looks like something went wrong.
1/1 Swift_RfcComplianceException in MailboxHeader.php line 347: Address in mailbox given [] does not comply with RFC 2822, 3.6.2. 
1.	in MailboxHeader.php line 347
2.	at Swift_Mime_Headers_MailboxHeader->_assertValidAddress('') in MailboxHeader.php line 263
3.	at Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(array('' => null)) in MailboxHeader.php line 106
4.	at Swift_Mime_Headers_MailboxHeader->setNameAddresses(array('' => null)) in MailboxHeader.php line 63
5.	at Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(array('' => null)) in SimpleHeaderFactory.php line 58
6.	at Swift_Mime_SimpleHeaderFactory->createMailboxHeader('Reply-To', array('' => null)) in SimpleHeaderSet.php line 68
7.	at Swift_Mime_SimpleHeaderSet->addMailboxHeader('Reply-To', array('' => null)) in SimpleMessage.php line 268
8.	at Swift_Mime_SimpleMessage->setReplyTo(array('' => null)) in SimpleMessage.php line 245
9.	at Swift_Mime_SimpleMessage->addReplyTo(null, null) in Message.php line 137
10.	at Message->addAddresses(null, null, 'ReplyTo') in Message.php line 121
11.	at Message->replyTo(null, null) in AssetsController.php line 709
12.	at AssetsController->App\Http\Controllers\{closure}(object(Message))
13.	at call_user_func(object(Closure), object(Message)) in Mailer.php line 403
14.	at Mailer->callMessageBuilder(object(Closure), object(Message)) in Mailer.php line 163
15.	at Mailer->send('emails.checkin-asset', array('log_id' => '240', 'first_name' => 'Yazan', 'item_name' => 'MQIT-L0118', 'checkin_date' => object(Carbon), 'item_tag' => 'INF-LOAN05', 'item_serial' => '829DLX1', 'note' => 'Test'), object(Closure)) in compiled.php line 6329
16.	at Facade::__callStatic('send', array('emails.checkin-asset', array('log_id' => '240', 'first_name' => 'Yazan', 'item_name' => 'MQIT-L0118', 'checkin_date' => object(Carbon), 'item_tag' => 'INF-LOAN05', 'item_serial' => '829DLX1', 'note' => 'Test'), object(Closure))) in AssetsController.php line 711
17.	at Mail::send('emails.checkin-asset', array('log_id' => '240', 'first_name' => 'Yazan', 'item_name' => 'MQIT-L0118', 'checkin_date' => object(Carbon), 'item_tag' => 'INF-LOAN05', 'item_serial' => '829DLX1', 'note' => 'Test'), object(Closure)) in AssetsController.php line 711
18.	at AssetsController->postCheckin(object(AssetCheckinRequest), '5')
19.	at call_user_func_array(array(object(AssetsController), 'postCheckin'), array(object(AssetCheckinRequest), 'assetId' => '5')) in compiled.php line 9424
20.	at Controller->callAction('postCheckin', array(object(AssetCheckinRequest), 'assetId' => '5')) in compiled.php line 9486
21.	at ControllerDispatcher->call(object(AssetsController), object(Route), 'postCheckin') in compiled.php line 9466
22.	at ControllerDispatcher->Illuminate\Routing\{closure}(object(Request))
23.	at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
24.	at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Authenticate.php line 45
25.	at Authenticate->handle(object(Request), object(Closure))
26.	at call_user_func_array(array(object(Authenticate), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
27.	at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
28.	at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
29.	at Pipeline->Illuminate\Routing\{closure}(object(Request))
30.	at call_user_func(object(Closure), object(Request)) in compiled.php line 9948
31.	at Pipeline->then(object(Closure)) in compiled.php line 9467
32.	at ControllerDispatcher->callWithinStack(object(AssetsController), object(Route), object(Request), 'postCheckin') in compiled.php line 9454
33.	at ControllerDispatcher->dispatch(object(Route), object(Request), 'App\Http\Controllers\AssetsController', 'postCheckin') in compiled.php line 8524
34.	at Route->runController(object(Request)) in compiled.php line 8511
35.	at Route->run(object(Request)) in compiled.php line 8225
36.	at Router->Illuminate\Routing\{closure}(object(Request))
37.	at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
38.	at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckPermissions.php line 28
39.	at CheckPermissions->handle(object(Request), object(Closure), 'assets.checkin')
40.	at call_user_func_array(array(object(CheckPermissions), 'handle'), array(object(Request), object(Closure), 'assets.checkin')) in compiled.php line 9963
41.	at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
42.	at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
43.	at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Authenticate.php line 45
44.	at Authenticate->handle(object(Request), object(Closure))
45.	at call_user_func_array(array(object(Authenticate), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
46.	at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
47.	at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
48.	at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForTwoFactor.php line 49
49.	at CheckForTwoFactor->handle(object(Request), object(Closure))
50.	at call_user_func_array(array(object(CheckForTwoFactor), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
51.	at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
52.	at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
53.	at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckLocale.php line 42
54.	at CheckLocale->handle(object(Request), object(Closure))
55.	at call_user_func_array(array(object(CheckLocale), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
56.	at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
57.	at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
58.	at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 3225
59.	at VerifyCsrfToken->handle(object(Request), object(Closure))
60.	at call_user_func_array(array(object(VerifyCsrfToken), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
61.	at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
62.	at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
63.	at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 13213
64.	at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))
65.	at call_user_func_array(array(object(AddQueuedCookiesToResponse), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
66.	at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
67.	at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
68.	at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 13150
69.	at EncryptCookies->handle(object(Request), object(Closure))
70.	at call_user_func_array(array(object(EncryptCookies), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
71.	at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
72.	at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
73.	at Pipeline->Illuminate\Routing\{closure}(object(Request))
74.	at call_user_func(object(Closure), object(Request)) in compiled.php line 9948
75.	at Pipeline->then(object(Closure)) in compiled.php line 8226
76.	at Router->runRouteWithinStack(object(Route), object(Request)) in compiled.php line 8217
77.	at Router->dispatchToRoute(object(Request)) in compiled.php line 8207
78.	at Router->dispatch(object(Request)) in compiled.php line 2419
79.	at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
80.	at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
81.	at Pipeline->Illuminate\Routing\{closure}(object(Request)) in Debugbar.php line 49
82.	at Debugbar->handle(object(Request), object(Closure))
83.	at call_user_func_array(array(object(Debugbar), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
84.	at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
85.	at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
86.	at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForDebug.php line 25
87.	at CheckForDebug->handle(object(Request), object(Closure))
88.	at call_user_func_array(array(object(CheckForDebug), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
89.	at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
90.	at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
91.	at Pipeline->Illuminate\Routing\{closure}(object(Request)) in TrustProxies.php line 46
92.	at TrustProxies->handle(object(Request), object(Closure))
93.	at call_user_func_array(array(object(TrustProxies), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
94.	at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
95.	at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
96.	at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForSetup.php line 27
97.	at CheckForSetup->handle(object(Request), object(Closure))
98.	at call_user_func_array(array(object(CheckForSetup), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
99.	at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
100.	at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
101.	at Pipeline->Illuminate\Routing\{closure}(object(Request)) in NosniffGuard.php line 17
102.	at NosniffGuard->handle(object(Request), object(Closure))
103.	at call_user_func_array(array(object(NosniffGuard), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
104.	at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
105.	at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
106.	at Pipeline->Illuminate\Routing\{closure}(object(Request)) in XssProtectHeader.php line 17
107.	at XssProtectHeader->handle(object(Request), object(Closure))
108.	at call_user_func_array(array(object(XssProtectHeader), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
109.	at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
110.	at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
111.	at Pipeline->Illuminate\Routing\{closure}(object(Request)) in FrameGuard.php line 17
112.	at FrameGuard->handle(object(Request), object(Closure))
113.	at call_user_func_array(array(object(FrameGuard), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
114.	at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
115.	at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
116.	at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 13474
117.	at ShareErrorsFromSession->handle(object(Request), object(Closure))
118.	at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
119.	at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
120.	at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
121.	at Pipeline->Illuminate\Routing\{closure}(object(Request)) in compiled.php line 11964
122.	at StartSession->handle(object(Request), object(Closure))
123.	at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
124.	at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
125.	at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
126.	at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 145
127.	at CheckForMaintenanceMode->handle(object(Request), object(Closure))
128.	at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in compiled.php line 9963
129.	at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
130.	at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
131.	at Pipeline->Illuminate\Routing\{closure}(object(Request))
132.	at call_user_func(object(Closure), object(Request)) in compiled.php line 9948
133.	at Pipeline->then(object(Closure)) in compiled.php line 2366
134.	at Kernel->sendRequestThroughRouter(object(Request)) in compiled.php line 2350
135.	at Kernel->handle(object(Request)) in index.php line 60
Messages1TimelineExceptions1Views2RouteQueries15MailsAuthGate1SessionRequest
64.05ms9.75MBPOST hardware/{assetId}/checkin/{backto?}

---
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: http://10.45.30.200/hardware/5/checkin
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by ybilleh** [comment]
Attached is my .env file
![env_file](https://user-images.githubusercontent.com/31872839/30305562-e3e3a862-97b6-11e7-90e3-321ce6ab595a.png)

**Comment by snipe** [comment]
You most likely have "checkin email alerts" enabled on the category, but no email address was provided for the user. You should provide an email address for your users, or disable that checkbox on the category.
