### ISSUE TITLE
Restore backup file one server to another server 

### ISSUE THREAD

**Issue by techie8881** [snipe/snipe-it#3948]
#### I want to restore the taken backup from snipeit to another snipeit server 

note: Using windows env and wamp server

-----

#### please show with steps 

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v3.6
- What OS and web server you're running Snipe-IT on - WAMP and windows 7 pro
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)- Manual Installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
-No more errors

**Comment by snipe** [comment]
Copy over the .env from the old server and import the old database using something like phpMyAdmin.
