### ISSUE TITLE
How to fix: "It looks like your files are owned by root, which might be a root/admin account. It's never a good idea to run a website with escalated priveliges."

### ISSUE THREAD

**Issue by passboltUser** [snipe/snipe-it#3950]
#### Expected Behavior (or desired behavior if a feature request)

When Snipe-IT is freshly set-up, one then goes to WEBSITE/setup. 
At 
```
Step 1

Configuration Check
```

it shows me this with a red background: 
`File Owner                 It looks like your files are owned by root, which might be a root/admin account. It's never a good idea to run a website with escalated priveliges. `

-----

#### Actual Behavior

Having the correct permissions so the background is green.

-----

#### Please confirm you have done the following before posting your bug report:

- [how] I have enabled debug mode
- [yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
`git clone https://github.com/snipe/snipe-it`
- What OS and web server you're running Snipe-IT on
Ubuntu Server 16.04
- Include what you've done so far in the installation, and if you got any error messages along the way.
Did the usual: https://snipe-it.readme.io/docs/installation
- Indicate whether or not you've manually edited any data directly in the database
No, it has been a fresh install.

**Comment by snipe** [comment]
Create a non-root user (for example, `snipeit`) and chown the files to that user, or have them owned by the web server's user.

**Comment by GeorgeBarkley** [comment]
Could you be more specific about which files should have the ownership changed?  is it everything in /var/www/snipe-it   ?

**Comment by snipe** [comment]
Yes. Nothing within snipe-it should be owned by root, ever.
