### ISSUE TITLE
Importing .csv. "Whoops, looks like something went wrong."

### ISSUE THREAD

**Issue by demondestructor** [snipe/snipe-it#3951]
#### Expected Behavior (or desired behavior if a feature request)

I want to import an existing hardware inventory asset list as a .csv file from Google docs. I want it to populate my SnipeIT in OneLogin.

-----

#### Actual Behavior

Every time I try to import, I get the "Whoops, looks like something went wrong" error.

-----

#### Please confirm you have done the following before posting your bug report:

I cannot figure where to enable debug mode. I have looked all over! Any help finding this would be greatly appreciated.
- [**x**] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- I am running Version v3.6.5 build 1 
- Running on OS X 10.12.6 on Google Chrome
- Unsure of how it was installed, as I am just the IT guy and it was already here. We use OneLogin to access it
- I have tried to edit the column's in my .csv file, trying to follow the "Asset-Only Fields" per https://snipe-it.readme.io/docs/importing , but unsure if I am doing this correctly or not.

**Comment by snipe** [comment]
Please provide a stack trace, per the [Getting Help documentation](https://snipe-it.readme.io/docs/getting-help#section-step-1-enable-debug-mode).

**Comment by snipe** [comment]
Haven't heard back, so I'm going to close this ticket for now, but will re-open it if you're still having issues
