### ISSUE TITLE
Feature request: Custom Fields for Users

### ISSUE THREAD

**Issue by oli415** [snipe/snipe-it#3955]
#### Desired Behavior

It would be great to be able to add custom fields to users, so that for example the date of joining the Company and other user-related stuff could be stored. Right now I believe only notes can be used for that purpose.

Thanks

**Comment by 08solsticegxp** [comment]
I would like to add to this and just say, Ability to add custom fields on everything.

**Comment by scraane** [comment]
+1

**Comment by Diniver** [comment]
Would be great feature and it will make it really flexible.

**Comment by snipe** [comment]
Duplicate of #4261
