### ISSUE TITLE
Whops something went wrong, after day of installation.

### ISSUE THREAD

**Issue by techie8881** [snipe/snipe-it#3960]
#### Whops something went wrong 

Day before yesterday Application was installed, and till yesterday night i had worked on it. today morning when I open application suddenly throwing an error "whops something went wrong" 

#### Please help me on this.
[snipeit-erro.docx](https://github.com/snipe/snipe-it/files/1302110/snipeit-erro.docx)

using windows 7 machine.

**Comment by snipe** [comment]
Please paste your stack trace in the GH issue. We do not open doc files from here.

**Comment by snipe** [comment]
Haven't heard back, so I'm going to close this ticket for now, but will re-open it if you're still having issues
