### ISSUE TITLE
Feature Request: Containers to keep assets/accessories/components in

### ISSUE THREAD

**Issue by gigabit942007** [snipe/snipe-it#3961]
#### Expected Behavior (or desired behavior if a feature request)
Would it be possible to add containers to keep objects? As for example i have a named box in which i store keyboards or any other objects.
Similarly i think it could be implemented for components to be assigned to a tower, like a CPU, RAM, Motherboard could be the logic as if stored in a box, just different naming?
-----

#### Actual Behavior
I have a set of assets which can be assigned to a box/container/storage room
Asset01 ->is in Box01 -> is in Storage Room 01/Cabinet 01
For the Components:
Tower 01 has: CPU X, RAM N, Motherboard etc. (Assigned from the components list)

Would this be something suited for this? I know we could use this feature in our inventory.

**Comment by snipe** [comment]
This is already on the dev roadmap, with barcodes for each container.

**Comment by gigabit942007** [comment]
I understand, then this can be closed from my perspective.

**Comment by victornpb** [comment]
Is this already on the product, because I can't find it
