### ISSUE TITLE
Snipe-IT Issue

### ISSUE THREAD

**Issue by Karnauday** [snipe/snipe-it#3966]
Hello Snipe,
I am not able to run ' composer install --no-dev --prefer-source'. When i put this:
Problem 1:
installation request for intervention/image 2.3. x-dev->satisfiable by intervention/image
intervention/image dev requires ext-fileinfo -> the requested php extension is missing from your system
 What shall i do? 
I am using WAMP/Windows Server 2012.
Thank You

**Comment by snipe** [comment]
> installation request for intervention/image 2.3. x-dev->satisfiable by intervention/image
intervention/image dev requires ext-fileinfo

Install `ext-fileinfo`, per the requirements documentation.
