### ISSUE TITLE
Snipe-IT Installation

### ISSUE THREAD

**Issue by Karnauday** [snipe/snipe-it#3971]
Key has been generated on .env file but when I try to use URL I put on env and httpd. it's not taking me to pre-flight.

Any suggestions, please.

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by Karnauday** [comment]
@snipe 
Snipe-IT Ver. - v4.0-beta 5
OS - Windows Server 2012
WAMP
Manual Installation
Error:
The Page cannot be displayed

Key has been generated on .env file. When i try to open url i wrote on .env and httpd, its not letting me for pre-flight. just the page cannot be displayed.
Also there is an error on basic binding setting. When i test connection, there is exlamation mark says "cannot verify access to path"

Thank You

**Comment by snipe** [comment]
Unfortunately, we don't support Bitnami's installer (as we don't have any idea how it works). If you're getting an error that the page cannot be displayed, that sounds like maybe DNS wasn't set up for it, but there's no way for us to know. You'll want to contact your hosting company or whoever you get your Bitnami stuff through.
