### ISSUE TITLE
When looking up asset by asset tag number fails

### ISSUE THREAD

**Issue by azmcnutt** [snipe/snipe-it#3972]
#### Expected Behavior (or desired behavior if a feature request)

When entering an asset tag number in the Lookup by asset tag field and pressing enter the asset should be displayed.

-----

#### Actual Behavior

Receive the whoops something went wrong

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running **4.0 beta 5**
- What OS and web server you're running Snipe-IT on **Windows Server 2008 R2 IIS 7.5**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Manual Install**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

**(1/1) FatalThrowableError
Call to a member function userLoc() on null**

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
**https://snipeit.crsk12.org/hardware/1298**
- If a stacktrace is provided in the error, include that too.

**(1/1) FatalThrowableErrorCall to a member function userLoc() on null
--
in Asset.php (line 263)
at Asset->assetLoc()in HasAttributes.php (line 400)
at Model->getRelationshipFromMethod('assetloc')in HasAttributes.php (line 386)
at Model->getRelationValue('assetloc')in HasAttributes.php (line 316)
at Model->getAttribute('assetloc')in Model.php (line 1237)
at Model->__get('assetloc')in AssetsController.php (line 608)
at AssetsController->show('1298')
at call_user_func_array(array(object(AssetsController), 'show'), array('hardware' => '1298'))in Controller.php (line 55)
at Controller->callAction('show', array('hardware' => '1298'))in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(AssetsController), 'show')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 559)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php (line 43)
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php (line 49)
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php (line 38)
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php (line 42)
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 561)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 520)
at Router->dispatchToRoute(object(Request))in Router.php (line 498)
at Router->dispatch(object(Request))in Kernel.php (line 174)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php (line 51)
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php (line 25)
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php (line 56)
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php (line 27)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 17)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 149)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)**

- Any errors that appear in your browser's error console. **Only what is above**
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). **Error does not seem reproducable at the demo site**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
[laravel.log.txt](https://github.com/snipe/snipe-it/files/1312278/laravel.log.txt)

- Include what you've done so far in the installation, and if you got any error messages along the way.
**Upgraded to Beta 5**
- Indicate whether or not you've manually edited any data directly in the database
**I have not made any changes to the database**
-----
Looking up other items (even items in the same model number) seem to work.  This is just a few items that we have discovered do far.

**Comment by azmcnutt** [comment]
After submitting the ticket, I looked up a few devices directly from the database.

The devices that were causing the problems have 'App\Models\User' in the assigned_type field but assigned_to as null.  Other devices that are not checked out have the assigned_type field as null.  Updating a device to null in the field seems to resolve the issue.

This could have been caused from when I was running on the dev branch between beta3 and beta 5.  Perhaps the specific version of the code that downloaded from the dev branch at the time was not clearing this field.

I have determined that checking in an asset no longer leaves the assigned_type field set as 'App\Models\User'.

If you agree; then this issue can be closed - I'll manually clear this field on all not-checked out assets.

Thanks,
James

**Comment by snipe** [comment]
Hmm... I'm not sure why it would show as 'App\Models\User' if assigned_to is null though. This is in the activity logs table that you're seeing this, or in the API response?

**Comment by azmcnutt** [comment]
I was seeing that in the database itself (using MySQL workbench to directly access the table).  I didn't notice it anywhere else.

**Comment by snipe** [comment]
@azmcnutt we just added a migration that should hopefully fix this issue.

**Comment by makpith** [comment]
how to add migration
