### ISSUE TITLE
Can't import assets

### ISSUE THREAD

**Issue by rshevitski** [snipe/snipe-it#3974]
#### Expected Behavior (or desired behavior if a feature request)

Trying to import assets via a csv file.

-----

#### Actual Behavior

I upload the file and the progress bar just hangs at 100% and is orange.

-----

#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - 
3.6.6 build 1
- What OS and web server you're running Snipe-IT on - 
Windows Server 2008 R2 IIS 7.5
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - 
Manual Install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Under assets > import
- If a stacktrace is provided in the error, include that too.

- Any errors that appear in your browser's error console.
As soon as I select the file to upload I get:
POST https://WEBSITEDOMAIN/api/hardware/import 404 (Not Found)
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
And `https://WEBSITEDOMAIN` is the correct address for your Snipe-IT instance?

**Comment by rshevitski** [comment]
I just put that to hide the domain address.  It is correct on my end.

**Comment by snipe** [comment]
That route definitely exists. https://github.com/snipe/snipe-it/blob/master/app/Http/routes.php#L13

Is there anything more useful in your app logs?

**Comment by snipe** [comment]
Also, what do you see when you go to https://WEBSITEDOMAIN/api/hardware/import directly in your browser?

**Comment by rshevitski** [comment]
Ill just type the domain.  
If I go to https://webapps.indians.k12.pa.us/api/hardware/import I get 404 Not Found.

Technically shouldn't it be going to https://webapps.indians.k12.pa.us/snipe/public/api/hardware/import
When I go to this I get:
Something went wrong
MethodNotAllowedHttpException in compiled.php line 8936:

**Comment by snipe** [comment]
> Technically shouldn't it be going to https://webapps.indians.k12.pa.us/snipe/public/api/hardware/import

You can see how I have no way of knowing the answer to that question, since I didn't set up your system. It sounds like maybe you have Snipe-IT running in a subdirectory, so you need to make sure your APP_URL in your .env includes the subdirectory.

**Comment by rshevitski** [comment]
Thank you sooo much.  Just caught onto that as you responded.  That was my issue.

**Comment by snipe** [comment]
Glad you got it sorted :)
