### ISSUE TITLE
Mail notification when due asset expected checkin time 

### ISSUE THREAD

**Issue by pratosh448** [snipe/snipe-it#3975]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by Diniver** [comment]
Hello,

Can we add a notification for license expiration date in the future. This will be useful as well.

Many thanks,

**Comment by snipe** [comment]
@Diniver license expiration alerts have existed since v3.x: https://snipe-it.readme.io/docs/configuring-alerts-backups

**Comment by snipe** [comment]
`php artisan snipeit:expected-checkin` sends expect checkin alerts in v4

**Comment by VitorinoDF** [comment]
Hello all,
Can i report on this same thread that the expected check-in date email notifications is not working?
It just doesn't send an email. I have email working, I use the test send button and it works, i receive the standard email notification
"This is a test from the Snipe-IT Asset Management System. If you got this, mail is working :)
Thanks,"
Also if i use the php command php artisan snipeit:expected-checkin, it says
2018-03-29 11:56:46 is deadline

No emails though

Please let me know what configurations shall I post here,

Thanks
