### ISSUE TITLE
LDAP Not Authenticating

### ISSUE THREAD

**Issue by jeremyw24** [snipe/snipe-it#3976]
#### Expected Behavior (or desired behavior if a feature request)

I have connected SnipeIt to our OpenLDAP Server and was able to successfully sync users from the LDAP. After allowing an imported LDAP User access from the Users menu, the user is unable to login. 

-----

#### Actual Behavior

User login displays message "Error: The username or password is incorrect."

I have enabled debug but do not see any useful messages in storage/log aside from user authentication failed. 
`[2017-09-19 20:34:35] production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory`

-----
#### Please provide answers to these questions before posting your bug report:

-  v3.6.6 build 1 (gee2c67a) 
- Ubuntu Server 16.04
- Ubuntu Installer

**Comment by jeremyw24** [comment]
Further log messages:
`#146 {main}
[2017-09-19 17:44:30] production.DEBUG: LDAP is enabled.
[2017-09-19 17:44:30] production.DEBUG: Binding user to LDAP.
[2017-09-19 17:44:30] production.DEBUG: LDAP user jeremy.west not found in LDAP or could not bind
[2017-09-19 17:44:30] production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory
[2017-09-19 17:44:30] production.DEBUG: Authenticating user against database.
[2017-09-19 17:44:30] production.DEBUG: Local authentication failed.`

I have filters in-place to check users are active:
LDAP Filter: `&(objectclass=zimbraAccount)(uid=*)(zimbraAccountStatus=Active)`
Authentication Query: `&(&(objectclass=zimbraAccount)(uid=*)(zimbraAccountStatus=Active))(uid=%uid)`

As above, SnipeIT was able to sync and import users from LDAP.

**Comment by richardhofman6** [comment]
Hi, under LDAP settings, what do you have in the "LDAP Authentication Query" field? It should be in the form: "uid=" or "samaccountname=" or something equivalent. It's *not* LDAP filter syntax, if you're using that.

**Comment by jeremyw24** [comment]
Yes, I had a LDAP Filter Syntax Query in there, I have removed this and put 'uid=' which is our Username field, but still receive the same error and am unable to login with LDAP Credentials.

**Comment by jeremyw24** [comment]
All good now, I filtered deeper on the tree and I am getting successful authentication.

**Comment by snipe** [comment]
Great - glad you got it sorted!
