### ISSUE TITLE
Custom Field Listbox element is limited to only 20 items

### ISSUE THREAD

**Issue by elpserversadministrators** [snipe/snipe-it#3978]
#### Expected Behavior (or desired behavior if a feature request)

I figured with the list box customer field I could add a user department field to add the drop down and list a huge number of entries

-----

#### Actual Behavior

when I create the custom field listbox, it limits the amount of fields to 20.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v3.6.6 build 1 (gee2c67a) 
- What OS and web server you're running Snipe-IT on: Windows Server 2012 R2, IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): git-install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: custom fields
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). : Confirmed in demo that the listbox element is also limited to a small amount of items
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
First off, departments is coming in v4, so you may not want to do that. The text field size of the custom fields is also increased in v4.
