### ISSUE TITLE
Starting custom development 

### ISSUE THREAD

**Issue by JZomerlei** [snipe/snipe-it#3979]
Alright so I don't really know where to post this. I'm currently working on the asset management and one of the things I was initially trying to do was changing some basic text in the screen. I found the Language I'm on and changed the relevant array entry. I then submitted the changes to my local server but the changes aren't seen. I then realized that the change isn't in the public/ so I don't think that the changes would be deployed. So my question is how do I get my code that I changed minorly - to actually show up? My files are definitely being uploaded to the server so it's not the lack of any change at all, just the wrong ones. 

Also one of the changes I'd like to make is a two deep menu of locations within the license page, so the user would upload Michigan and then the Michigan link would have a bunch of cities. I have an idea of how it would be done in my head but I just want to make sure some one else hasn't already done it but I haven't found their branch. 

Thank you for any and all help.

**Comment by JZomerleiHC** [comment]
Or just a feature - not necessarily custom development but I do need to change some text.

**Comment by snipe** [comment]
I don't have any idea why your language edits wouldn't be reflected on the screen, unless you're editing the wrong one. You'll need to check the blades to make sure you're looking at the right language file.
