### ISSUE TITLE
Feature requests for improving Snipe-IT in a school environment

### ISSUE THREAD

**Issue by Tsuroerusu** [snipe/snipe-it#398]
I work at a fairly big public school here in Denmark. The school allows 4th year students and above to bring their own laptops or tablets, and if they do not have any, they can borrow one from the school. The current system for managing this is a total mess, but luckily I have convinced the headmaster to authorize deployment of Snipe-IT to replace this old and messy system.

I began the deployment process today, it will be a smooth and gradual process, however so far I would like to note a few things as to how we intend to use the system, and make a few feature requests that would improve the experience for us.

In our scenario, the user system will be used to internally keep track of which laptops are borrowed by which students. It will be be a purely internal system, so we will not be having users access it directly. I have decided to use the "Locations" to designate the school classes. So for example, today I have worked on the 4th year students, so there are three locations "4.A", "4.B" and "4.C" to indicate each class in the 4th year. I have then entered all the students into the user database, and assigned the relevant location.

As I mentioned, no person, other than administrators, will interact with this system. Therefore the following aspects make things more time-consuming or cumbersome:

1. The fact that inputting an email address is a requirement to create a new user is a problem. Since the purpose is to not have users interact with Snipe-IT, they obviously will not need to have emails sent to them either. I would propose that it be possible to create a user with no email address, and when the system wants to send an email notification to a certain, it could check if there is no email address available for that user, and if not, it says "I am not supposed to send emails to this user". My solution so far was to put fake-emails into each user profile like firstname@lastname.noemail, which took up some time.

2. Having to enter passwords for 67 users, when user access is not intended, was also a bit troublesome. I "solved" this by entering 123456 twice in each case. For us, the user system is an excellent way to manage where things are, but we do not intend to interact with students through this. I would like to propose that it be possible to disable login for a user, and thus make it possible to not require a password. This would be akin to on a UNIX system where login can be disabled, and a password be "NULL", so to speak. Perhaps this could be handled similarly to what I mentioned for email addresses. If there is not password, then login is disabled automatically (Of course, it would also be useful to be able to disable login for users WITH a password for other scenarios, I could imagine).

3. I use Locations to denominate the classes at the school, therefore it was unnecessary for me to have address information in the Location "profile", so to speak. It would be useful for me to be able to create a location that relies merely on its name, and not carrying any address information.

4. A very important thing which I would like to see is this. Since I use Locations to categorize users, it would be extremely useful to be able to view lists of users by their Location, similar to how I can view assets by model. I could imagine it being implemented as follows:
Under the "People"-menu on the left, "Locations" could be added like there is "Asset Models" under the "Asset"-menu to enable viewing users by location in a similar fashion. Also, in this case it would be relevant to be able to see the number of users per Location, including a sortable column on the full people list.

5. Last, but not least, since we have about 700 students at our school, inputting each one by hand is a lot of manual labour, so bulk addition of users from, say a spreadsheet or a CSV-file, would be VERY useful. My earlier suggestions of email- and password-less users (With email and login functionality disabled) could potentially be elements to allow a straight-forward way to bulk-add users, so that one could feed the system just the first name, last name and location and have a whole pile of users created.

If clarification on any of my suggestions is needed, I will gladly do so.

To all developers and contributors, we really appreciate Snipe-IT and the efforts put into it. :)

**Comment by snipe** [comment]
I just pushed out a rough user import tool to develop. Still need to handle localization (language strings) and put in some failsafes for bad files, but it should be working. I also added the ability to email users their credentials on creation for individual user creation.

**Comment by Tsuroerusu** [comment]
@snipe That sounds great. :-) Are there any plans or progress concerning the fourth point I mentioned above regarding browsing users by location?

**Comment by snipe** [comment]
I think most of these improvements have already been done, or are coming in 2.0
