### ISSUE TITLE
When enabling LDAP, we cannot log in and get 500 error

### ISSUE THREAD

**Issue by JoshNansoz** [snipe/snipe-it#3982]
#### Expected Behavior (or desired behavior if a feature request)

When you enable LDAP, test LDAP and then import users, this is all successful. 

When you login with the correct user/pass you would expect to get logged in without issue.

Equally we'd expect that if using the incorrect user/pass you would get the usual "incorrect user/pass" message.

-----

#### Actual Behavior

When you have LDAP enabled, whether you use the correct password or incorrect password, you receive an error 500 message.

We have successfully setup LDAP and the users have been imported via LDAP, but doesn't allow you to login. 

-----

httpd Logs from Centos box running Snipe:

===============

[Wed Sep 20 13:16:27.005046 2017] [:error] [pid 14052] [client 172.19.0.27:49979] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/html/snipeit/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied' in /var/www/html/snipeit/bootstrap/cache/compiled.php:13906\nStack trace:\n#0 /var/www/html/snipeit/bootstrap/cache/compiled.php(13836): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/snipeit/bootstrap/cache/compiled.php(13596): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/html/snipeit/bootstrap/cache/compiled.php(13694): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)\n#3 /var/www/html/snipeit/bootstrap/cache/compiled.php(13389): Monolog\\Logger->error(Object(UnexpectedValueException), Array)\n#4 /var/www/html/snipeit/bootstrap/cache/compiled.php(13360): Illuminate\\Log\\Writer->writeLog('error', Object(UnexpectedValueException), Array)\n#5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(57): Illuminate\\Log\\Writer->error in /var/www/html/snipeit/bootstrap/cache/compiled.php on line 13906, referer: http://emea-inv-mgmt-01/login
[Wed Sep 20 13:16:27.005573 2017] [:error] [pid 14052] [client 172.19.0.27:49979] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/html/snipeit/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied' in /var/www/html/snipeit/bootstrap/cache/compiled.php:13906\nStack trace:\n#0 /var/www/html/snipeit/bootstrap/cache/compiled.php(13836): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/snipeit/bootstrap/cache/compiled.php(13596): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/html/snipeit/bootstrap/cache/compiled.php(13694): Monolog\\Logger->addRecord(400, Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#3 /var/www/html/snipeit/bootstrap/cache/compiled.php(13389): Monolog\\Logger->error(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#4 /var/www/html/snipeit/bootstrap/cache/compiled.php(13360): Illuminate\\Log\\Writer->writeLog('error', Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#5 /var/www/html/snipeit/vendor/laravel/frame in /var/www/html/snipeit/bootstrap/cache/compiled.php on line 13906, referer: http://emea-inv-mgmt-01/login

===============

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - v3.6.6 build 1 (gee2c67a
- What OS and web server you're running Snipe-IT on - Centos 7, install .sh provided by SnipeIT
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - login page, logging in with any correct/incorrect credentials results in 500 error 
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo) - don't want to put company LDAP stuff on a demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - yes - I imported the database from online cloud version to on-site server

**Comment by snipe** [comment]
> 'The stream or file "/var/www/html/snipeit/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied

Make the storage directory and all sub-directories writable by the web server, per the install instructions.

**Comment by JoshNansoz** [comment]
Well don't I feel stupid now! 

Thanks for the info - all working

**Comment by snipe** [comment]
:) Glad you got it sorted!
