### ISSUE TITLE
Fatal error: class symfony \component\finder\iterator issue

### ISSUE THREAD

**Issue by techie8881** [snipe/snipe-it#3985]
#### while login in this page is throwing 
Snipe it application was working fine, suddenly the attached error came, then I restarted the WAMP server, then it started working fine. 
-----

#### Kindly suggest, if this error comes in future.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode- No
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
Yes
-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running-3.6
- What OS and web server you're running Snipe-IT on- windows 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)Manual 
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
![image](https://user-images.githubusercontent.com/31619548/30685480-a98e3420-9ed2-11e7-8a8a-21a515ee0653.png)
[Doc1.docx](https://github.com/snipe/snipe-it/files/1320401/Doc1.docx)

- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
No idea - I would try a composer dump and composer dump-autoload next time.
