### ISSUE TITLE
Can't LDAP User Sync 

### ISSUE THREAD

**Issue by namsudtho** [snipe/snipe-it#3987]
I'm test LDAP connection success!
![image](https://user-images.githubusercontent.com/15089720/30729270-9a219340-9f88-11e7-93fd-fac37a49ceee.png)

and LDAP Settings is:
![image](https://user-images.githubusercontent.com/15089720/30729358-214b9e9c-9f89-11e7-8219-4c0851e05e13.png)

**but i'm can't LDAP user sync!**

and this is error:
![image](https://user-images.githubusercontent.com/15089720/30729482-1a2f80dc-9f8a-11e7-8245-53710f526e99.png)

**Comment by snipe** [comment]
That typically means your base object doesn't exist the way you've specified in in your LDAP settings. More info here: https://stackoverflow.com/questions/15108969/php-ldap-search-no-such-object
