### ISSUE TITLE
Default Checkout user and permissions.

### ISSUE THREAD

**Issue by JoshNansoz** [snipe/snipe-it#3990]
Hey,

Currently when a user goes to check out a device it seems to just provide a list of all the users and by default they are not selected.

Would it make more sense to have either:

1: The user that selected the device for checkout to be the default choice. 
Because I don't see me or anyone else really needing to check out something on somebody else's behalf that often.

Or

2: Have a new permission to assign to groups that give people in that group the ability to check out/in devices that belong to other users.

As a "standard user" I have the ability to check out devices to other users, and indeed check out devices that belong to other users.

**Comment by snipe** [comment]
> Because I don't see me or anyone else really needing to check out something on somebody else's behalf that often.

That's not the way the majority of our users interact with the system though. Most are IT departments who are constantly checking out assets on behalf of the end-users in their company.

**Comment by testology** [comment]
I stumbled across this ticket, and wanted to add that we have a similar issue in our use case.
For our setup we require users to be able to check out equipment to themselves, but don't want them to be able to check out equipment to others for security/tracking reasons.

The second option Josh mentioned would be preferable for us, with the ability to check out assets to others controlled by toggling a permission to stop "standard" users from doing so.

Thanks,
