### ISSUE TITLE
Create new anything form display is incorrect

### ISSUE THREAD

**Issue by abdi9x** [snipe/snipe-it#3994]
I just installed Snipe-IT, 
i try to find out all of the features, and i found some problem.
if i create new Asset or anything form display is incorrect.
This is 2 sample of my issue
![capture2](https://user-images.githubusercontent.com/12828643/30769823-1732927c-a04b-11e7-8d78-3c10d10a0162.PNG)

![capture](https://user-images.githubusercontent.com/12828643/30769820-ee300850-a04a-11e7-9898-bf72f708d4f9.PNG)

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by abdi9x** [comment]
Oops Sorry....
here, I download latest version of Snipe-IT (4.0). I deploy to my IIS10 Windows server 2012 using manual installation, and of course  I follow the installation guide step by step and everything is fine. nothing error with Pre-Flight setup, all is marked with green checkmark. and I didn't modify any code or database.

**Comment by snipe** [comment]
Please tell me what errors you're seeing in your browser's debug bar. 
https://snipe-it.readme.io/docs/getting-help#section-step-2-enable-your-browsers-error-console
