### ISSUE TITLE
v4 - Possible CSS/JS path issues in subdirectories

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#3995]
According to [this](https://stackoverflow.com/questions/15232600/laravel-stylesheets-and-javascript-dont-load-for-non-base-routes#comment68150732_16565640) stackoverflow article (and lots of Mix GH issues), using the `asset()` facade in blades should allow Laravel mix to figure out the correct URL for CSS and JS files if the Snipe-IT install is in a subdirectory, but we're getting early reports that that *might* not be true. Would love feedback from anyone who has tried the upgrade in a subdirectory.

**Comment by benmartel** [comment]
I think this issue is happening with me on the upgrade. I am getting the exact same behavior as #3490. I can't get any CSS OR JS to load properly.

**Comment by snipe** [comment]
Sigh. Laravel tries to be too smart for its own good sometimes, and really hates being run in a subdirectory. (That issue isn't related to this one though - that was an external scripts issue.)

Okay, we're looking for a fix for this.

**Comment by benmartel** [comment]
Is there anything I can do in the meantime to manually fix this?

**Comment by snipe** [comment]
Can you try a fresh pull from master?

**Comment by benmartel** [comment]
On it now. I will report back.

**Comment by benmartel** [comment]
that worked like a dream!

**Comment by snipe** [comment]
Excellent! (Man I wish Laravel would document some of this stuff better. Grr.)

**Comment by benmartel** [comment]
Not sure if this is related but everything looks good except for I am getting 3 checkout fields on checkout and the middle one Checkout to Select an asset only works when you select a blank tiny line. This did not happen before the upgrade.
