### ISSUE TITLE
Symfony\Component\Debug\Exception\FatalErrorException Class 'MisterPhilip error

### ISSUE THREAD

**Issue by sjelle** [snipe/snipe-it#3996]
Hi,
We have been succesfully using Snipe-It on our Centos 6.x server for quite a long time (since version 2).
We would like to upgrade to version 4 but it is not working as planned...
-----

#### Actual Behavior
All instructions were followed as written in the documentation. We have already tried git pull and manually copying the files, but the end result is the same.
Applying php composer.phar install --no-dev --prefer-source works fine - no errors.
Applying php composer.phar dump -autoload works fine - no errors.
Applying every php artisan xxxxx produces error : 

PHP Fatal error : Class 'MisterPhilip\MaintenanceMode\MaintenanceModeServiceProvider' not found in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 612

[Symfony\Component\Debug\Exception\FatalErrorException]
Class 'MisterPhilip\MaintenanceMode\MaintenanceModeServiceProvider' not found

----

- [X] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
- V:ersion of Snipe-IT you're running : Version v3.6.4 build 12 (gf7e4fca)
- What OS and web server you're running Snipe-IT on : Centos 6.9 (Final) Kernel 2.6.32-696.10.2.el6.x86_64
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) : Manual, git pull 

We have also tried to clear the vendors directory and rerun the php composer install, rebuilding the vendor dir. But after that also no luck.

So I ran out of options. Would anyone be so kind to help us out or give some advice ?
Thanks !

**Comment by uberbrady** [comment]
`git Branch` to confirm you’re on master?

Maybe try blowing away your vendors directory, and rerunning composer install? Are you sure it ran correctly?

The reason I ask is your problem sounds like composer deps aren’t there

**Comment by sjelle** [comment]
Hi,
git branch returns * master so we're good there.

I already tried removing / renaming the vendors directory and then rerunning composer. It nicely refeeds the vendor dir and ends without any error.
However, same error afterwards....

Thanks for helping me out

**Comment by therealjoshuad** [comment]
I’m not on my computer at the moment, but I’m seeing a similar issue, subscribing to see where this goes

**Comment by snipe** [comment]
Did you remove the bootstrap/compiled file per the upgrade instructions? `If it exists, you may delete the bootstrap/cache/compiled.php file. It is no longer used.`

**Comment by sjelle** [comment]
Hi Snipe,

Yes, I did remove this. I tried this over and over , no success (bare metal restoring the machine since after the upgrade fails - nothing works anymore)

Thx

**Comment by reneski** [comment]
I had the same problem and was able to resolve it by also deleting the other 2 files in the bootstrap/cache/ directory (not sure if one of them would be enough)
`bootstrap/cache/config.php`
`bootstrap/cache/services.php`

followed by
`php composer.phar install --no-dev --prefer-source`
and the other upgrade steps, i was able to successfully finish the upgrade to v4.

**Comment by sjelle** [comment]
Hi there,
I can confirm the solution proposed by reneski works !!! Thanks a lot man

@uberbrady @snipe : Maybe include this on your doc page additional to the /bootstrap/cache/compiled.php comment ?

Thanks !!

**Comment by snipe** [comment]
Thanks - will update the docs!
