### ISSUE TITLE
feature request for working with secure Content-Security-Policy Header

### ISSUE THREAD

**Issue by it-world** [snipe/snipe-it#3998]
#### Expected Behavior (or desired behavior if a feature request)

I suggest adding random nonce's to scripts and styles and dynamically create the csp header includig this nonce's.
-----

#### Actual Behavior
Runing snipe-it app with an enabled secure-content-policy header only works with 'unsafe-inline' option added.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running 
4.0 & 3.6.6
- What OS and web server you're running Snipe-IT on
CentOS 7 x64 / CentOS 6 x64 / FreeBSD 11 x64 |  all with apache 2.4
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual

**Comment by snipe** [comment]
We do have some (lots) of scripts inline though, and those won't run without 'unsafe-inline' added, so I'm not sure how we'd address that.

**Comment by snipe** [comment]
(Other than trying to remember to add a new nonce every single time we change any of the inline javascript, which seems pretty hellish and prone to issues.)

**Comment by snipe** [comment]
I was actually working on some CSP middleware right now and was experimenting using the CSRF token as a nonce. The only thing I'm worried about is whether that might conflict with server-based CSP stuff.

**Comment by snipe** [comment]
I just pushed that branch (asp-middleware) if you want to take a look.

**Comment by it-world** [comment]
ive setup a test host from scratch today and tested it.

Below the response header (via curl):
########################################
root@webtest:/ # curl -i -k https://192.168.8.185:443
HTTP/2 302
date: Fri, 29 Sep 2017 07:48:22 GMT
server: Apache/2.4.27 (FreeBSD) OpenSSL/1.0.2j-freebsd PHP/7.1.9
x-powered-by: PHP/7.1.9
cache-control: no-cache, private
location: https://192.168.8.185/login
x-clockwork-id: d4abf956c83c22cb4b76cfec89bb8440
x-clockwork-version: 1
x-clockwork-path: _debugbar/clockwork/
x-content-type-options: nosniff
content-security-policy: default-src 'self';style-src 'self' 'unsafe-inline' oss.maxcdn.com;script-src 'self' oss.mafxcdn.com cdnjs.cloudflare.com 'nonce-p37Nt1VHo3TvSuIODJaRg6cC8WEp72QohJADV6I4';connect-src 'self';object-src 'none';font-src 'self' data:;img-src 'self' data: gravatar.com
referrer-policy: strict-origin
x-xss-protection: 1; mode=block
x-frame-options: SAMEORIGIN
set-cookie: XSRF-TOKEN=eyJpdiI6Imp3dEF0djBteGw3R3ZDMUg4S09jUEE9PSIsInZhbHVlIjoiNUx5UE41ZWNJZWx0Q09qXC94NkJJano3bzQ2bythM2FkR05JUmFJWWRYNGM2cXRST3VjUlEraFZSVWZtMnFCdmxHUm40MkZkZm12bEtLTjc5M3V1RFdBPT0iLCJtYWMiOiI5YTRiMzQwNjZjYWQzN2E2YzVhYzg0ZmQ0YjUzYjY4NjJhNjczZTMzOTE4MGIwYTc5OGIxNzZmNmFhNzQ1MWUyIn0%3D; expires=Sat, 07-Oct-2017 15:48:23 GMT; Max-Age=720000; path=/
set-cookie: snipeit_session=OKp0Ghp9yZCIZDebIMNsWJbC4gHxCvIWEWmdZqc3; expires=Sat, 07-Oct-2017 15:48:23 GMT; Max-Age=720000; path=/; HttpOnly
strict-transport-security: max-age=2592000
x-permitted-cross-domain-policies: master-only
content-length: 352
content-type: text/html; charset=UTF-8

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url=https://192.168.8.185/login" />

        <title>Redirecting to https://192.168.8.185/login</title>
    </head>
    <body>
        Redirecting to <a href="https://192.168.8.185/login">https://192.168.8.185/login</a>.
    </body>
########################################

Afterwards i evaluated the csp header via : https://csp-evaluator.withgoogle.com/

Below the output:
########################################
error
script-src 

    Host whitelists can frequently be bypassed. Consider using 'strict-dynamic' in combination with CSP nonces or hashes.
    Consider adding 'unsafe-inline' (ignored by browsers supporting nonces/hashes) to be backward compatible with older browsers.
'self'

    'self' can be problematic if you host JSONP, Angular or user uploaded files.

help_outline
oss.mafxcdn.com

    No bypass found; make sure that this URL doesn't serve JSONP replies or Angular libraries.

error
cdnjs.cloudflare.com

    cdnjs.cloudflare.com is known to host Angular libraries which allow to bypass this CSP.


base-uri [missing]

    Missing base-uri allows the injection of base tags. They can be used to set the base URL for all relative (script) URLs to an attacker controlled domain. Can you set it to 'none' or 'self'?

########################################

**Comment by snipe** [comment]
So I'm not sure what my takeaway is here - is that branch a viable workaround, or no?

**Comment by it-world** [comment]
Its much better than before. :)
It just needs a little bit improvement.
Ive played around with the header settings myself, and tested as much as possible in my local environment.

This CSP header worked in the end, except some images/styles which where loaded via http.
When CSP header is set, loading stuff via http should be avoided. :)

#################################
Header set Content-Security-Policy: "default-src 'self';   style-src 'self'  'nonce-MjXiLvF4ua4xRXZWtfVlDOncq8HHJiz9HhNjWJgk' https://oss.maxcdn.com;   script-src 'self' 'nonce-MjXiLvF4ua4xRXZWtfVlDOncq8HHJiz9HhNjWJgk' 'nonce-p37Nt1VHo3TvSuIODJaRg6cC8WEp72QohJADV6I4' https://cdnjs.cloudflare.com ;connect-src 'self'  ;object-src 'none';font-src 'self' data:;img-src 'self'  data: https://gravatar.com; base-uri 'self'; child-src 'self' ;"
########################

**Comment by snipe** [comment]
Huh - what was loading via http? There shouldn't be any http calls.

**Comment by it-world** [comment]
firefox says: from self (.env is set to https) an from cdn

**Comment by snipe** [comment]
`*blink*`

The browser shouldn't be reading the .env at all though

**Comment by snipe** [comment]
I'm also not entirely sure that this method honors the purpose of the nonce, since the CSRF token that we're using is session-based, not request-based. In other words, a new CSRF only gets generated once per session, not one per request. This is a deliberate choice on Laravel's part, as request-based CSRF tokens can cause some weird UI issues, but I'm not sure if that's something that would be considered "bad" for CSP purposes.

**Comment by it-world** [comment]
regarding .env, i just wanted to point out that ive set it to https. :)
firefox tried to load some stuff via http from the webserver itself.

Iam not a guru,  but i don't think that the CSRF token would be considered bad for CSP.
The best way to test CSP/SSL/base security stuff i've found is https://observatory.mozilla.org

**Comment by snipe** [comment]
> regarding .env, i just wanted to point out that ive set it to https. :)

Oh thank heavens. I was about to get REALLY worried lol

> firefox tried to load some stuff via http from the webserver itself.

So, nothing I need to worry about?

**Comment by it-world** [comment]
You "only" need to change your code to load all gravatar images (and all local styles) via https.

**Comment by snipe** [comment]
If the .env is set to https as the protocol, it should be loading them via https. And gravitar is set to load using whatever protocol the site is using:

```
     /**
     * Returns the user Gravatar image url.
     *
     * @return string
     */
    public function gravatar()
    {

        if ($this->avatar) {
            return config('app.url').'/uploads/avatars/'.$this->avatar;
        }

        if ((Setting::getSettings()->load_remote=='1') && ($this->email!='')) {
            $gravatar = md5(strtolower(trim($this->email)));
            return "//gravatar.com/avatar/".$gravatar;
        }

        return false;

    }
```

**Comment by it-world** [comment]
my fault, ive not cleared the config cache. :/

ive done now, but not all errors are gone.

This and some other style related errors still persist:
#########################################
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src https://192.168.8.185 'nonce-MjXiLvF4ua4xRXZWtfVlDOncq8HHJiz9HhNjWJgk' https://oss.maxcdn.com”). Source: color: white.
#########################################

**Comment by snipe** [comment]
Are you in debug mode? I'm seeing debugbar errors that I'm not sure how I'll fix, since that JS gets scooped in automatically.

**Comment by it-world** [comment]
no iam not in debug mode anymore since the app itself is working.

i will switch it on

**Comment by snipe** [comment]
Hm. Not sure how to figure out what files are still causing problems then.

**Comment by snipe** [comment]
(And honestly don't know what to do about the debugbar....)

**Comment by it-world** [comment]
i see, the debugbar is gone because script cant be loaded.
do the debugbar script come from the framework itself?

**Comment by snipe** [comment]
It doesn't, it's a library we include for optimizing queries, helping users troubleshoot, etc.

I think if debug is set to true, we have to disable CSP. There just isn't an easy way for me to modify that JS that gets inserted into every page.

**Comment by it-world** [comment]
yes i think this will be a good idea. :)

**Comment by snipe** [comment]
Can we consider this issue closed now?

**Comment by it-world** [comment]
yes, and thanks your support is awesome. :)

**Comment by snipe** [comment]
Thanks! I appreciate all the help with debugging and testing!

**Comment by it-world** [comment]
Sorry for reopening.
Forgot to mention that you first need to unset the servers header before you set your header. :)
like:      Header always unset Content-Security-Policy
Without this your header will not apply if the webserver had setup a CSP before.

**Comment by minhnq64** [comment]
because it violates the following Content Security Policy directive: "style-src 'self' 'unsafe-inline'". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

https://snipe-it.readme.io/docs/reverse-proxies Fix it

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/reverse-proxies">Reverse Proxies</a></strong></div><div>If you wish to use a Reverse Proxy in front of your web server, you'll need to take a few extra steps to make it work. A typical Reverse Proxy scenario looks like this: Internet Reverse Proxy Server (Public &amp; Private IPs) Web Server (Private IPs) The Reverse Proxy Server is functioning as a reve...</div></blockquote>
