### ISSUE TITLE
artisan migrate to 4.0

### ISSUE THREAD

**Issue by andreaconsadoriw** [snipe/snipe-it#3999]
when i try to Migrate i've this error:
  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'locale' (SQL: ALTER TABLE users CHANGE locale loc
  ale VARCHAR(10) DEFAULT 'en_US.UTF-8')

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'locale' 

if i disable strict mode in config/database.php i've this new error

 [Illuminate\Database\QueryException]
  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'locale' at row 1 (SQL: ALTER TABLE users CHANGE locale
   locale VARCHAR(10) DEFAULT 'en_US.UTF-8')

  [PDOException]
  SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'locale' at row 1

**Comment by dawsonbessinger** [comment]
Having the same issue here. Where is that default value being generated? It's 11 characters so it is definitely not going to fit into VARCHAR(10).

**Comment by snipe** [comment]
In your .env, what do you have for `APP_LOCALE`?

**Comment by dawsonbessinger** [comment]
So I actually didn't have an APP_LOCALE in my .env. I added that variable in and set it to "en" - this made the QueryException go away and the migrate went through successful. However, browsing out to the web app now I get "Whoops, looks like something went wrong." so something is still amiss.

**Comment by snipe** [comment]
I need a stack trace to be able to help debug that

**Comment by dawsonbessinger** [comment]
It was my cipher - I had to use your recrypt instructions. Speaking of instructions I noticed under your "Important note on upgrading" heading you have:
`run php artisan config:cache to clear your config cache`

Pretty sure that should be:
`run php artisan config:clear to clear your config cache`

Thanks again - v4 looks sweet!

**Comment by snipe** [comment]
Derp. Thanks for the heads up - I'll fix it now :)

![60-percent](https://user-images.githubusercontent.com/197404/30837255-6af21940-a218-11e7-8e5e-2337bb55f4ab.gif)
