### ISSUE TITLE
Error in exception handler: The stream or file "/var/www/html/snipeit/app/storage/logs/log-apache2handler-2014-11-28.txt" could not be opened: failed to open stream: Permission denied in /var/www/html/snipeit/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:84

### ISSUE THREAD

**Issue by apollon8888** [snipe/snipe-it#400]
I get this error Error in exception handler: The stream or file "/var/www/html/snipeit/app/storage/logs/log-apache2handler-2014-11-28.txt" could not be opened: failed to open stream: Permission denied in /var/www/html/snipeit/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:84

I am using ubuntu 14.04.1 LTS and latest version of snipeit.

I followed the tutorial. Can someone help me with this error?

**Comment by ironheartbj18** [comment]
Were you using the FTP (FileZilla) ssh root@ipaddress and trying to connect the web server and does not see the var/www/html on list? I thought it was just chmod -R 777(laravel's group folder)/app/storage, so I decided try by this  sudo chmod -R 777 /var/www/html/(laravel's group folder)/app/storage. check the web server it went through the permission and it works. Also, make sure  security using as 775

**Comment by snipe** [comment]
@ironheartbj18 this ticket was closed back in Dec

**Comment by fromitti** [comment]
Hello, I resolved error Error in exception handler with permits but when trying to enter me throws Server Error 500 (Internal Server Error) any idea.

**Comment by wer8956741** [comment]
thanks ~~ I have same problem, now it workd!

**Comment by creamosdavid** [comment]
when I was trying to change the user and the group forgot to update the permissions of the "storage" directory.

With sudo chmod -R 777 /var7www/html/<directory>/storage works fine

thanks a lot

**Comment by arungupta999** [comment]
thanks Problem Solved.!
but then an error....

Not Found

The requested URL /user/login was not found on this server.
Apache/2.4.18 (Ubuntu) Server at www.laravel123.com Port 80

**Comment by alincota** [comment]
> try this ..
> 
> sudo chmod -R 777 /var/www/html/snipeit/app/storage

Don't do that! Try to give as little access as needed for the task at hand. Usually, you need write access more than anything so assuming directory ownership is root:root, you can assign it 443 perm (recursively to apply same to the files). YMMV but that for me works OK.

LE: the execute permission is needed for the streamhandler to chmod() it with your filePermissions (if given).

**Comment by Zidane12985** [comment]
kesalahan Snipe IT : Kesalahan dalam pengguna #15118

**Comment by snipe** [comment]
@Zidane12985 - Hi there - this issue is closed and doesn't seem directly related to your issue. Please create a new issue and fill in all of the questions in the new issue form. (When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.)
