### ISSUE TITLE
Unable to check out licenses

### ISSUE THREAD

**Issue by Diniver** [snipe/snipe-it#4001]
Hello all,

Well done to everyone bringing v4.0 live.
I have managed to upgrade my 3.6 but now I am not able to check out licenses. An error message appears _admin/licenses/message.not_found_.  It seems to work on assets, accessories, consumables and components.

#### Expected Behavior (or desired behavior if a feature request)

Check out license

-----

#### Actual Behavior

 Error: admin/licenses/message.not_found

-----

#### Please confirm you have done the following before posting your bug report:

- [yes] I have enabled debug mode
- [yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - 
**v4.0**

- What OS and web server you're running Snipe-IT on
**Ubuntu 16.04 with Apache**

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
**Manual**

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
 **Error: admin/licenses/message.not_found**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
**http://WEBSITE/index.php/licenses**

- If a stacktrace is provided in the error, include that too.

- Any errors that appear in your browser's error console.

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
**Not really. It might be another bug**
Checkout page is opening. After I choose a user it and click checkout -  shows _Whoops, looks like something went wrong._
Checking out for assets works.
```
1/1) BadMethodCallExceptionCall to undefined method Illuminate\Database\Query\Builder::present()
--
in Builder.php (line 2443)
at Builder->__call('present', array())in Builder.php (line 1239)
at Builder->__call('present', array())in Model.php (line 1332)
at Model->__call('present', array())in CheckoutNotification.php (line 91)
at CheckoutNotification->toMail(object(User))in MailChannel.php (line 52)
at MailChannel->send(object(User), object(CheckoutNotification))in NotificationSender.php (line 113)
at NotificationSender->sendToNotifiable(object(User), 'aee08072-c18f-45fb-8c9c-84b3f1d37d08', object(CheckoutNotification), 'mail')in NotificationSender.php (line 89)
at NotificationSender->sendNow(object(Collection), object(CheckoutNotification))in NotificationSender.php (line 64)
at NotificationSender->send(object(Collection), object(CheckoutNotification))in ChannelManager.php (line 36)
at ChannelManager->send(object(User), object(CheckoutNotification))in RoutesNotifications.php (line 18)
at User->notify(object(CheckoutNotification))in Loggable.php (line 71)
at LicenseSeat->logCheckout('', object(User))in LicensesController.php (line 335)
at LicensesController->postCheckout(object(Request), '13')
at call_user_func_array(array(object(LicensesController), 'postCheckout'), array(object(Request), 'licenseId' => '13'))in Controller.php (line 55)
at Controller->callAction('postCheckout', array(object(Request), 'licenseId' => '13'))in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(LicensesController), 'postCheckout')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 559)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php (line 43)
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php (line 49)
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php (line 49)
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php (line 42)
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 561)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 520)
at Router->dispatchToRoute(object(Request))in Router.php (line 498)
at Router->dispatch(object(Request))in Kernel.php (line 174)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php (line 51)
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php (line 25)
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php (line 56)
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php (line 27)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 17)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 149)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)
```

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
**SMTP errors which are not related**
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
**No**

**Comment by TheVakman** [comment]
I can confirm, I have the same issue on v4.0.1 with the same trace.

**Comment by snipe** [comment]
Can you tell me if it's an issue when checking a license out to users, assets, or both?

**Comment by TheVakman** [comment]
As we discussed on Gitter, I guess this question is answered.

I'll add your comment here on the issue so you can close without much update when you're finished.

> snipe

> @snipe 23:56
> @TheVakman Okay, I think I’ve got a solution - testing now
> There’s a freeSeat() method we skipped in the API, and the Web UI uses the API for those listing pages

**Comment by snipe** [comment]
Can you pull from develop and see if it's fixed? You don't need to run composer or migrations or anything, just pull latest.

**Comment by TheVakman** [comment]
`
(1/1) BadMethodCallExceptionCall to undefined method Illuminate\Database\Query\Builder::requireAcceptance()
--
in Builder.php (line 2443)
at Builder->__call('requireAcceptance', array())in Builder.php (line 1239)
at Builder->__call('requireAcceptance', array())in Model.php (line 1332)
at Model->__call('requireAcceptance', array())in CheckoutNotification.php (line 97)
at CheckoutNotification->toMail(object(User))in MailChannel.php (line 52)
at MailChannel->send(object(User), object(CheckoutNotification))in NotificationSender.php (line 113)
at NotificationSender->sendToNotifiable(object(User), 'ed11b6e6-77e7-433e-9f78-76a1a819b72c', object(CheckoutNotification), 'mail')in NotificationSender.php (line 89)
at NotificationSender->sendNow(object(Collection), object(CheckoutNotification))in NotificationSender.php (line 64)
at NotificationSender->send(object(Collection), object(CheckoutNotification))in ChannelManager.php (line 36)
at ChannelManager->send(object(User), object(CheckoutNotification))in RoutesNotifications.php (line 18)
at User->notify(object(CheckoutNotification))in Loggable.php (line 74)
at LicenseSeat->logCheckout('', object(User))in LicensesController.php (line 335)
at LicensesController->postCheckout(object(Request), '1003')
at call_user_func_array(array(object(LicensesController), 'postCheckout'), array(object(Request), 'licenseId' => '1003'))in Controller.php (line 55)
at Controller->callAction('postCheckout', array(object(Request), 'licenseId' => '1003'))in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(LicensesController), 'postCheckout')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 559)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php (line 43)
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php (line 49)
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php (line 49)
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php (line 42)
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 561)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 520)
at Router->dispatchToRoute(object(Request))in Router.php (line 498)
at Router->dispatch(object(Request))in Kernel.php (line 174)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php (line 51)
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php (line 25)
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php (line 56)
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php (line 27)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 17)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 149)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

`
