### ISSUE TITLE
Snipe-IT 

### ISSUE THREAD

**Issue by Karnauday** [snipe/snipe-it#4005]
Hello 
I have successfully installed Snipe-IT. I am looking to add some logo and text on the login page like this. 
![snipe2](https://user-images.githubusercontent.com/31669674/30818551-74a8c3ee-a1e1-11e7-81ea-39c6dbf0f093.png)

Is there any way to do this.

Will highly appreciate.

Thank You

**Comment by snipe** [comment]
If you add a logo in your settings, it will appear on the login page in v4. (Otherwise, you'll have to edit the login blade.)

**Comment by Karnauday** [comment]
@snipe 
When i try to add logo through setting - an error is coming
"Whoops, looks like something went wrong."
