### ISSUE TITLE
Asset import issues

### ISSUE THREAD

**Issue by lockbucket** [snipe/snipe-it#4006]
#### Expected Behavior (or desired behavior if a feature request)

Ability to import Assets through importer

I have used the spreadsheet located here (https://snipe-it.readme.io/docs/importing) and filled out the appropriate fields.  When I try uploading the csv I receive the Actual Behavior notated below.  I do not see any where in the spreadsheet for model id?

-----

#### Actual Behavior

"Warning some errors occured while importing"
Asset'':The model id is required. The asset tag is required

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running  v4.0 stable
- What OS and web server you're running Snipe-IT on   Windows 2016 Server IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error ""Warning some errors occured while importing"
Asset'':The model id is required. The asset tag is required
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Import asset
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).   Demo won't allow import
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

[2017-09-25 10:35:01] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function userLoc() on null' in C:\inetpub\wwwroot\snipe-it\app\Models\Asset.php:265
Stack trace:

- Include what you've done so far in the installation, and if you got any error messages along the way. No errors
- Indicate whether or not you've manually edited any data directly in the database 
No data edited in database.

**Comment by snipe** [comment]
@dmeltzer - can you take a look?

**Comment by gizzmojr** [comment]
Getting the same error on viewing an asset, which just went through an audit update. The asset (server) does not have a user associated with it, just a location.

**Comment by snipe** [comment]
@gizzmojr - great, thanks for the update!
