### ISSUE TITLE
SnipeIT application latest stable source code

### ISSUE THREAD

**Issue by nilesh-shah** [snipe/snipe-it#401]
Hi,

We would like to know to install and configure latest stable codebase of SnipeIT, which branch should be considered? Develop/Documentation/master?

Thanks

**Comment by snipe** [comment]
Hi @nilesh-shah - we've just uploaded some docs on WAMP/XAMPP : http://snipeitapp.com/documentation/installing-on-xampp/

(Really, the install directions are the same for WAMP/XAMPP as they are for Linux, we just included the a video for getting WAMP/XAMPP set up)
