### ISSUE TITLE
V4 - persistence of oauth keys in docker

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#4013]
We need to figure out how to persist the oauth public and private keys in the docker setup, else API bearer tokens will be reset each time.

**Comment by snipe** [comment]
@uberbrady can you confirm if this is still something we need to handle? We'll want to release v4.3.0 soon, and I'd like to close this out if it's not needed anymore.

**Comment by Dramaretchi** [comment]
https://github.com/snipe/snipe-it/issues/5366

**Comment by Dramaretchi** [comment]
looks like this is the issue we have, right? https://github.com/snipe/snipe-it/issues/5366

**Comment by uberbrady** [comment]
@Dramaretchi yes, it's the same thing, for sure. I'll give you some pointers for your particular problem in that issue.

**Comment by uberbrady** [comment]
This was fixed with that commit.
