### ISSUE TITLE
Snipe-IT on Shared Hosting

### ISSUE THREAD

**Issue by akbardwi** [snipe/snipe-it#4014]
Please make a feature ticket support and knowledge base, and make the easy installation of this project

**Comment by it-world** [comment]
you could install osticket its a ticketsystem with knowledge base.

@easy:
snipe-it was and still is very easy to install..

**Comment by akbardwi** [comment]
this installation is error on my server, you have a tutorial install snipe-it on shared hosting ???
if  you have, give me a tutorial

**Comment by it-world** [comment]
without providing your error logs no one will be able to help you.
I don't think that there is an tutorial for shared hosting.

Have you thought about using snipe-it as a service: https://snipeitapp.com/hosting

**Comment by snipe** [comment]
Shared hosting works the same as dedicated hosting, you just need to set your document root correctly. And as @it-world mentions, we need error logs. 

Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Additionally, please try to keep issue topics isolated. It helps us manage our fixes and allows us to separate feature requests from bugs.

**Comment by akbardwi** [comment]
1. I use Snipe-IT on version 4.0
2. I'm using Centos OS and hiawatha web server with Kloxo-mr Control Panel
3. Manual Installation
4. I'm not getting an error on my browser but I can not access the setup link after setting in the .env file

**Comment by snipe** [comment]
>  I can not access the setup link after setting in the .env file

Can you be specific? What is the message you're seeing in the browser? Do you have DNS set up for whatever the URL is that you used for your APP_URL?

**Comment by akbardwi** [comment]
this is my web http://v2.license.indomedia.cf

**Comment by akbardwi** [comment]
this is my web http://v2.license.indomedia.cf

**Comment by snipe** [comment]
@akbardwi 

If I go to http://v2.license.indomedia.cf/index.php, I can see PHP code, which means you don't have PHP installed. Additionally, once you install PHP, you'll want to make sure that index.php is an accepted DirectoryIndex.
