### ISSUE TITLE
Change Asset status to "Ready to deploy" the checkout Not Appear

### ISSUE THREAD

**Issue by Youssefibrahim10** [snipe/snipe-it#4015]
Hello Snipeit team,

Today we are try to assign one of our " In stock" assets to a new users But we we going to change the assets status from " In Stock" TO " Ready to deploy" the checkout Not appear so there is no way to reasign the assets to the new user. the below picture show what i mean:

![image](https://user-images.githubusercontent.com/31034820/30849173-bfcd7bd8-a2a1-11e7-8ccb-509b894958ac.png)

#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running:   v3.6.6 build 1 (gee2c67a)
- What OS and web server you're running Snipe-IT on:  Linux Centos 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: There is no any error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: 
- If a stacktrace is provided in the error, include that too.: NO
- Any errors that appear in your browser's error console.: No
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. NO, Installation with a straight forward
- Indicate whether or not you've manually edited any data directly in the database: No we do not

**Comment by snipe** [comment]
Please check that your Ready to Deploy status is actually deployable (via admin > status labels). Also, I might suggest upgrading to the latest version - it has a lot of bugfixes and improvements.

**Comment by snipe** [comment]
Additionally...

>Include any additional information you can find in app/storage/logs and your webserver's logs.

**Comment by Youssefibrahim10** [comment]
Thank you for you quick response, I have checked the Ready to deploy status is already deployable. I will try to upgrade to the latest version and i will let you know.

**Comment by snipe** [comment]
We don't currently allow checkout on edit - only create. That's by design currently, but we can consider making this a feature request for unassigned, deployable assets.

**Comment by williamsant** [comment]
I believe this definitely needs to be revisited. Editing assets becomes a hassle to re-assign status, then re-enter and re-assign user.
