### ISSUE TITLE
View accepted users signature

### ISSUE THREAD

**Issue by Expada** [snipe/snipe-it#4016]
hi snipe,

currently im using v4.0.3 which is such an amazing updates.
i can no longer see the signature from asset->history
the .png file is still can be found in directory but not view-able in snipe-it
has it been removed or located elsewhere?

**Comment by snipe** [comment]
Hi @Expada - thanks for the kind words :) What happens when you try to view the sig? Broken image, or nothing at all?

**Comment by Expada** [comment]
@snipe,  nothing there. supposed there's a sig next to notes.

**Comment by snipe** [comment]
Anything in your logs? We didn't change much there for v4, but we might have missed something.

**Comment by Expada** [comment]
sorry for the late reply but there is nothing in the log. all good except the sig is missing :(

**Comment by Expada** [comment]
![capture](https://user-images.githubusercontent.com/32293464/30892792-1f63282e-a36d-11e7-82cf-5131081effdf.PNG)

something like this

**Comment by snipe** [comment]
Can you grab the latest from the `develop` branch and let me know if that fixes it?

**Comment by Expada** [comment]
yes the column is there but it shows broken image with error "failed to load image: undefined"
none of the assets successfully load the sig
