### ISSUE TITLE
DocumentRoot is set incorrectly. IPage

### ISSUE THREAD

**Issue by rodiali** [snipe/snipe-it#4019]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)
D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory.
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running = V4.0
- What OS and web server you're running Snipe-IT on = Ipage Hosting
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) = I think it is install.sh, but i get this error message as soon as i open my link 
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

All the files are located on main root. I followed the instruction "Subdirectories"
please help me to fix this problem, i'm not an PHP developer but i wanted to test this soluiton so i can use it in my company.
I googled a lot before i post here and tested every articel and solution you have posted before but i couldn't fix it

Reagrds

**Comment by snipe** [comment]
You'll need to contact support over at IPage and ask them how to change your DocumentRoot to `public` in your snipe-it directory

**Comment by vitorneto** [comment]
did you manage to have this working, i have the same problem
