### ISSUE TITLE
issue faced installing on wamp

### ISSUE THREAD

**Issue by khalidanwar123** [snipe/snipe-it#402]
Hi mad15,

trying to configure snipe-it on wamp:

followed :https://github.com/snipe/snipe-it/issues/169

stuck on step 6:

i am getting following error at step 6 :

C:\wamp\www\snipe-it>composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.jso
n. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for intervention/image dev-master -> satisfiable by i
ntervention/image[dev-master].
- intervention/image dev-master requires ext-fileinfo * -> the requested PHP
extension fileinfo is missing from your system.

and while updating get following error :+1:

C:\wamp\www\snipe-it>composer update
Loading composer repositories with package information
The "https://packagist.org/packages.json" file could not be downloaded: failed t
o open stream: A connection attempt failed because the connected party did not p
roperly respond after a period of time, or established connection failed because
connected host has failed to respond.

https://packagist.org could not be fully loaded, package information was loaded
from the local cache and may be out of date
Updating dependencies (including require-dev)
PHP Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to all
ocate 33554432 bytes) in phar://C:/ProgramData/ComposerSetup/bin/composer.phar/s
rc/Composer/DependencyResolver/Solver.php on line 177
PHP Stack trace:
PHP 1. {main}() C:\ProgramData\ComposerSetup\bin\composer.phar:0
PHP 2. require() C:\ProgramData\ComposerSetup\bin\composer.phar:15
PHP 3. Composer\Console\Application->run() phar://C:/ProgramData/ComposerSetup
/bin/composer.phar/bin/composer:43
PHP 4. Symfony\Component\Console\Application->run() phar://C:/ProgramData/Comp
oserSetup/bin/composer.phar/src/Composer/Console/Application.php:83
PHP 5. Composer\Console\Application->doRun() phar://C:/ProgramData/ComposerSet
up/bin/composer.phar/vendor/symfony/console/Symfony/Component/Console/Applicatio
n.php:124
PHP 6. Symfony\Component\Console\Application->doRun() phar://C:/ProgramData/Co
mposerSetup/bin/composer.phar/src/Composer/Console/Application.php:145
PHP 7. Symfony\Component\Console\Application->doRunCommand() phar://C:/Program
Data/ComposerSetup/bin/composer.phar/vendor/symfony/console/Symfony/Component/Co
nsole/Application.php:193
PHP 8. Symfony\Component\Console\Command\Command->run() phar://C:/ProgramData/
ComposerSetup/bin/composer.phar/vendor/symfony/console/Symfony/Component/Console
/Application.php:889
PHP 9. Composer\Command\UpdateCommand->execute() phar://C:/ProgramData/Compose
rSetup/bin/composer.phar/vendor/symfony/console/Symfony/Component/Console/Comman
d/Command.php:252
PHP 10. Composer\Installer->run() phar://C:/ProgramData/ComposerSetup/bin/compo
ser.phar/src/Composer/Command/UpdateCommand.php:130
PHP 11. Composer\Installer->doInstall() phar://C:/ProgramData/ComposerSetup/bin
/composer.phar/src/Composer/Installer.php:219
PHP 12. Composer\DependencyResolver\Solver->solve() phar://C:/ProgramData/Compo
serSetup/bin/composer.phar/src/Composer/Installer.php:494 ...........

**Comment by kameshveera** [comment]
Hi every one. 
I have installed pyrocms laravel.
I got some 500 internal error when after login .

i mean http://myserver/public/admin/login is display fine.
Then after submit email and password redirect to this page http://myserver/public/admin/dashboard
any one please help me.

**Comment by snipe** [comment]
Are you asking for support for PyroCMS here? We don't support other people's software for them. You should head over to the PyroCMS project and ask them for help.
