### ISSUE TITLE
Cannot search by username (checked out to) in 4.0.3

### ISSUE THREAD

**Issue by diekmanu** [snipe/snipe-it#4020]
#### Expected Behavior (or desired behavior if a feature request)

When I enter a well-known username in 'All assets' or in other views I would like to see all the assets checked out to this particular user.

-----

#### Actual Behavior

The query results in 'No matching records found'

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running:  v4.0.3 build 8 (gb354ca8) 
- What OS and web server you're running Snipe-IT on: nginx, win7x64
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo): YES
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by diekmanu** [comment]
**Old working v3 query:**
`select count(*) as aggregate from `assets` inner join `models` on `assets`.`model_id` = `models`.`id` where `physical` = '1' and (exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `categories` where `models`.`category_id` = `categories`.`id` and (`categories`.`name` LIKE '%diekmanu%' or `models`.`name` LIKE '%diekmanu%' or `models`.`model_number` LIKE '%diekmanu%') and `categories`.`deleted_at` is null)) or exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `manufacturers` where `models`.`manufacturer_id` = `manufacturers`.`id` and (`manufacturers`.`name` LIKE '%diekmanu%') and `manufacturers`.`deleted_at` is null)) or (exists (select * from `status_labels` where `assets`.`status_id` = `status_labels`.`id` and `status_labels`.`name` LIKE '%diekmanu%' and `status_labels`.`deleted_at` is null)) or (exists (select * from `companies` where `assets`.`company_id` = `companies`.`id` and `companies`.`name` LIKE '%diekmanu%')) or (exists (select * from `locations` where `assets`.`rtd_location_id` = `locations`.`id` and `locations`.`name` LIKE '%diekmanu%' and `locations`.`deleted_at` is null)) or (exists (select * from `users` where `assets`.`assigned_to` = `users`.`id` and (`users`.`first_name` LIKE '%diekmanu%' or `users`.`last_name` LIKE '%diekmanu%' or (exists (select * from `locations` where `users`.`location_id` = `locations`.`id` and `locations`.`name` LIKE '%diekmanu%'))))) or `assets`.`name` LIKE '%diekmanu%' or `assets`.`asset_tag` LIKE '%diekmanu%' or `assets`.`serial` LIKE '%diekmanu%' or `assets`.`order_number` LIKE '%diekmanu%' or `assets`.`notes` LIKE '%diekmanu%' or `_snipeit_mac_address` LIKE '%diekmanu%' or `_snipeit_ip_adresse` LIKE '%diekmanu%' or `_snipeit_lan_port` LIKE '%diekmanu%' or `_snipeit_raum` LIKE '%diekmanu%' or `_snipeit_dsm_rc_viewer` LIKE '%diekmanu%') and `assets`.`deleted_at` is null order by `models`.`name` asc

select `assets`.* from `assets` inner join `models` on `assets`.`model_id` = `models`.`id` where `physical` = '1' and (exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `categories` where `models`.`category_id` = `categories`.`id` and (`categories`.`name` LIKE '%diekmanu%' or `models`.`name` LIKE '%diekmanu%' or `models`.`model_number` LIKE '%diekmanu%') and `categories`.`deleted_at` is null)) or exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `manufacturers` where `models`.`manufacturer_id` = `manufacturers`.`id` and (`manufacturers`.`name` LIKE '%diekmanu%') and `manufacturers`.`deleted_at` is null)) or (exists (select * from `status_labels` where `assets`.`status_id` = `status_labels`.`id` and `status_labels`.`name` LIKE '%diekmanu%' and `status_labels`.`deleted_at` is null)) or (exists (select * from `companies` where `assets`.`company_id` = `companies`.`id` and `companies`.`name` LIKE '%diekmanu%')) or (exists (select * from `locations` where `assets`.`rtd_location_id` = `locations`.`id` and `locations`.`name` LIKE '%diekmanu%' and `locations`.`deleted_at` is null)) or (exists (select * from `users` where `assets`.`assigned_to` = `users`.`id` and (`users`.`first_name` LIKE '%diekmanu%' or `users`.`last_name` LIKE '%diekmanu%' or (exists (select * from `locations` where `users`.`location_id` = `locations`.`id` and `locations`.`name` LIKE '%diekmanu%'))))) or `assets`.`name` LIKE '%diekmanu%' or `assets`.`asset_tag` LIKE '%diekmanu%' or `assets`.`serial` LIKE '%diekmanu%' or `assets`.`order_number` LIKE '%diekmanu%' or `assets`.`notes` LIKE '%diekmanu%' or `_snipeit_mac_address` LIKE '%diekmanu%' or `_snipeit_ip_adresse` LIKE '%diekmanu%' or `_snipeit_lan_port` LIKE '%diekmanu%' or `_snipeit_raum` LIKE '%diekmanu%' or `_snipeit_dsm_rc_viewer` LIKE '%diekmanu%') and `assets`.`deleted_at` is null order by `models`.`name` asc limit 200 offset 0`

**Non-working v4 query:**
`select count(*) as aggregate from `assets` where (exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `categories` where `models`.`category_id` = `categories`.`id` and (`categories`.`name` LIKE '%diekmanu%' or `models`.`name` LIKE '%diekmanu%' or `models`.`model_number` LIKE '%diekmanu%') and `categories`.`deleted_at` is null)) or exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `manufacturers` where `models`.`manufacturer_id` = `manufacturers`.`id` and (`manufacturers`.`name` LIKE '%diekmanu%') and `manufacturers`.`deleted_at` is null)) or (exists (select * from `status_labels` where `assets`.`status_id` = `status_labels`.`id` and `status_labels`.`name` LIKE '%diekmanu%' and `status_labels`.`deleted_at` is null)) or (exists (select * from `suppliers` where `assets`.`supplier_id` = `suppliers`.`id` and `suppliers`.`name` LIKE '%diekmanu%' and `suppliers`.`deleted_at` is null)) or (exists (select * from `companies` where `assets`.`company_id` = `companies`.`id` and `companies`.`name` LIKE '%diekmanu%')) or (exists (select * from `locations` where `assets`.`rtd_location_id` = `locations`.`id` and `locations`.`name` LIKE '%diekmanu%' and `locations`.`deleted_at` is null)) or `assets`.`name` LIKE '%diekmanu%' or `assets`.`asset_tag` LIKE '%diekmanu%' or `assets`.`serial` LIKE '%diekmanu%' or `assets`.`order_number` LIKE '%diekmanu%' or `assets`.`notes` LIKE '%diekmanu%' or `_snipeit_mac_address_1` LIKE '%diekmanu%' or `_snipeit_ip_adresse_2` LIKE '%diekmanu%' or `_snipeit_lan_port_3` LIKE '%diekmanu%' or `_snipeit_raum_6` LIKE '%diekmanu%' or `_snipeit_dsm_rc_viewer_7` LIKE '%diekmanu%') and `assets`.`deleted_at` is null order by `assets`.`created_at` asc

select `assets`.* from `assets` where (exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `categories` where `models`.`category_id` = `categories`.`id` and (`categories`.`name` LIKE '%diekmanu%' or `models`.`name` LIKE '%diekmanu%' or `models`.`model_number` LIKE '%diekmanu%') and `categories`.`deleted_at` is null)) or exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `manufacturers` where `models`.`manufacturer_id` = `manufacturers`.`id` and (`manufacturers`.`name` LIKE '%diekmanu%') and `manufacturers`.`deleted_at` is null)) or (exists (select * from `status_labels` where `assets`.`status_id` = `status_labels`.`id` and `status_labels`.`name` LIKE '%diekmanu%' and `status_labels`.`deleted_at` is null)) or (exists (select * from `suppliers` where `assets`.`supplier_id` = `suppliers`.`id` and `suppliers`.`name` LIKE '%diekmanu%' and `suppliers`.`deleted_at` is null)) or (exists (select * from `companies` where `assets`.`company_id` = `companies`.`id` and `companies`.`name` LIKE '%diekmanu%')) or (exists (select * from `locations` where `assets`.`rtd_location_id` = `locations`.`id` and `locations`.`name` LIKE '%diekmanu%' and `locations`.`deleted_at` is null)) or `assets`.`name` LIKE '%diekmanu%' or `assets`.`asset_tag` LIKE '%diekmanu%' or `assets`.`serial` LIKE '%diekmanu%' or `assets`.`order_number` LIKE '%diekmanu%' or `assets`.`notes` LIKE '%diekmanu%' or `_snipeit_mac_address_1` LIKE '%diekmanu%' or `_snipeit_ip_adresse_2` LIKE '%diekmanu%' or `_snipeit_lan_port_3` LIKE '%diekmanu%' or `_snipeit_raum_6` LIKE '%diekmanu%' or `_snipeit_dsm_rc_viewer_7` LIKE '%diekmanu%') and `assets`.`deleted_at` is null order by `assets`.`created_at` asc limit 200 offset 0`

--- 

So I guess the whole part starting with **select * from `users` where `assets`.`assigned_to` = `users`.`id` and (`users`.`first_name` LIKE '%diekmanu%' or `users`.`last_name` LIKE '%diekmanu%' or** is missing in v4.

**Comment by diekmanu** [comment]
Anyone? Is this adressed in 4.0.5/develop?
#4021

**Comment by snipe** [comment]
Please be patient. When this is resolved, the issue will be updated.

**Comment by snipe** [comment]
Can you pull the latest from the develop branch and tell me if this fixes your issue?

**Comment by diekmanu** [comment]
Works for me now. Thanks so much @snipe

**Comment by MPIAE-IT** [comment]
Hey. I just updated to 4.0.6 and it is still not possible to search by user name. Cache etc was cleaned.
