### ISSUE TITLE
Search Asset filtering for name or lastname 

### ISSUE THREAD

**Issue by nbattista89** [snipe/snipe-it#4021]
I've done the upgrade from version 3.6.6 to 4.0.3 we don't have problem for upgrade but now in the tab Asset -> all asset.
we can't search asset using filter like name or lastname of user.
In the version 3.6.6 the search for name or lastname it works.

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running : **4.0.3** 
- What OS and web server you're running Snipe-IT on : **CentOS 6**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) : install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). : **YES**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Are you getting any errors in your app logs?

**Comment by nbattista89** [comment]
[laravel.log](https://github.com/snipe/snipe-it/files/1342178/laravel.log)
Hi,
I've uploaded the log file.

**Comment by snipe** [comment]
I think this is fixed in develop/master
