### ISSUE TITLE
LDAP test fails but LDAP sync succeeds 

### ISSUE THREAD

**Issue by tiagom62** [snipe/snipe-it#4023]
#### Expected Behavior (or desired behavior if a feature request)

The test should succeed. 

-----

#### Actual Behavior

Testing LDAP in the "Update LDAP/AD Settings" fails with a red triangle. Chrome debug console shows "GET http://snipeit/api/v1/settings/ldaptest 401 (Unauthorized)"

I have tried saving and going back in and it fails with the same error.

When i go to People > LDAP Sync it does sync properly. It pulled in a new user I created.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running v4.0.3 build 8 (gb354ca8)
- What OS and web server you're running Snipe-IT on CentOS 7, apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error Admin > Update LDAP/AD Settings page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
"GET http://snipeit/api/v1/settings/ldaptest 401 (Unauthorized)"

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
LDAP is disabled in the demo enviroment.

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by TheVakman** [comment]
I can confirm this one as well.

**Comment by pvhkai** [comment]
I can also confirm on this one

**Comment by leobg** [comment]
I can confirm exact same behavior too.

**Comment by therealjoshuad** [comment]
As redundant as this is, I'm getting this as well

**Comment by tiagom62** [comment]
Continues in v4.0.9 build 120 (gf66e222). laravel.log is empty. Running debug just give me Unauthenticated./var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php#66

**Comment by tiagom62** [comment]
This is fixed. Tested latest master and its working great.
