### ISSUE TITLE
I forgot my password  page error with sad panda 

### ISSUE THREAD

**Issue by pratosh448** [snipe/snipe-it#4025]
![image](https://user-images.githubusercontent.com/31343768/30876146-6139ce38-a313-11e7-9456-a73379b26097.png)

**Comment by pratosh448** [comment]
In your demo also why ?
![image](https://user-images.githubusercontent.com/31343768/30876282-bfe21198-a313-11e7-8d6d-265146e3666c.png)

**Comment by snipe** [comment]
Please grab the latest - we've fixed this issue. (No idea how it happened in the first place - possibly a bad merge). Just git pull, no composer or migrations necessary.
