### ISSUE TITLE
Error Upgrading from v3.6.6 to V4.0.3

### ISSUE THREAD

**Issue by JExactly** [snipe/snipe-it#4026]
#### Expected Behavior (or desired behavior if a feature request)

Runs fine
Running Composer install --no-dev --prefer-source
-----

#### Actual Behavior
I am getting the below error when running the composer command, Unable to complete upgrade and now in a broken state. Need to access the inventory site. Any suggestions on why my discard of changes fails? 

![image](https://user-images.githubusercontent.com/14076881/30876115-a5e45f9e-a2c3-11e7-9412-80f248ed2d36.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running V3.6.6
- What OS and web server you're running Snipe-IT on Ubuntu 16.04 Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) GIT pull
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
That looks like a permissions issue? Did you run composer as root?

**Comment by snipe** [comment]
Do you have composer installed globally or locally? (Do you use `composer blah` or `php composer.phar blah`?)

**Comment by snipe** [comment]
At the very least, you'll need to `chown -R` your entire vendor directory, to change the owner to non-root/sudo.

**Comment by JExactly** [comment]
I have it installed locally, new error with php artisan migrate 
![image](https://user-images.githubusercontent.com/14076881/30877290-394d6dae-a2c7-11e7-91b1-49f909a62e27.png)

**Comment by snipe** [comment]
What version of PHP are you running?

**Comment by JExactly** [comment]
I have 7.0 & 7.1 installed. I believe it is using 7.1

Jeff Nero
Systems Operations Engineer
T:216-369-2200 Ext. 5661
F:216-369-2201
JNero@ExactCarePharmacy.com




On Tue, Sep 26, 2017 at 2:34 PM -0400, "snipe" <notifications@github.com<mailto:notifications@github.com>> wrote:


What version of PHP are you running?

-

**Comment by JExactly** [comment]
I have 7.0 and 7.1 installed. It appears to be using 7.0 from the missing dependency notice I received

**Comment by snipe** [comment]
Have you tried doing all the usual cache clearing stuff?

```
php artisan cache:clear
php artisan route:clear
php artisan view:clear
composer dump
```

And removing the contents of the `bootstrap/cache` directory?

**Comment by JExactly** [comment]
ok! getting somewhere! Got past all that, migrated the database, ran 
open your .env file and add a new field called LEGACY_APP_KEY= and add your v3.x Snipe-IT APP_KEY value there.
run php artisan config:clear to clear your config cache
run php artisan snipeit:legacy-recrypt to decrypt and re-encrypt any encrypted custom fields
run php artisan key:generate to generate a new, non-mcrypt APP_KEY
clear your browser cookies

However, now I am getting an http error 500

**Comment by snipe** [comment]
Turn on debugging please and tell me what the stacktrace is.

**Comment by JExactly** [comment]
Turned on debugging in my env file, no stacktrace. still a http 500 error

**Comment by snipe** [comment]
Anything in your app log file?

**Comment by JExactly** [comment]
Refresh me again on where the app logs are located?

**Comment by JExactly** [comment]
Nevermind, found it. as long it is in the storage/logs folder and you are looking for the laravel.log

Then there is nothing from today in the laravel logs that indicate any kind of error

**Comment by JExactly** [comment]
Determined my user permissions got messed up now getting : 


(1/1) ExceptionThe bootstrap/cache directory must be present and writable.
--
in ProviderRepository.php (line 190)
at ProviderRepository->writeManifest(array('providers' => array('Illuminate\\Auth\\AuthServiceProvider', 'Illuminate\\Broadcasting\\BroadcastServiceProvider', 'Illuminate\\Bus\\BusServiceProvider', 'Illuminate\\Cache\\CacheServiceProvider', 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'Illuminate\\Cookie\\CookieServiceProvider', 'Illuminate\\Database\\DatabaseServiceProvider', 'Illuminate\\Encryption\\EncryptionServiceProvider', 'Illuminate\\Filesystem\\FilesystemServiceProvider', 'Illuminate\\Foundation\\Providers\\FoundationServiceProvider', 'Illuminate\\Hashing\\HashServiceProvider', 'Illuminate\\Mail\\MailServiceProvider', 'Illuminate\\Notifications\\NotificationServiceProvider', 'Illuminate\\Pagination\\PaginationServiceProvider', 'Illuminate\\Pipeline\\PipelineServiceProvider', 'Illuminate\\Queue\\QueueServiceProvider', 'Illuminate\\Redis\\RedisServiceProvider', 'Illuminate\\Auth\\Passwords\\PasswordResetServiceProvider', 'Illuminate\\Session\\SessionServiceProvider', 'Illuminate\\Translation\\TranslationServiceProvider', 'Illuminate\\Validation\\ValidationServiceProvider', 'Illuminate\\View\\ViewServiceProvider', 'Barryvdh\\Debugbar\\ServiceProvider', 'Aws\\Laravel\\AwsServiceProvider', 'Intervention\\Image\\ImageServiceProvider', 'Collective\\Html\\HtmlServiceProvider', 'Spatie\\Backup\\BackupServiceProvider', 'Fideloper\\Proxy\\TrustedProxyServiceProvider', 'PragmaRX\\Google2FA\\Vendor\\Laravel\\ServiceProvider', 'Laravel\\Passport\\PassportServiceProvider', 'Laravel\\Tinker\\TinkerServiceProvider', 'Unicodeveloper\\DumbPassword\\DumbPasswordServiceProvider', 'Schuppo\\PasswordStrength\\PasswordStrengthServiceProvider', 'App\\Providers\\AppServiceProvider', 'App\\Providers\\AuthServiceProvider', 'App\\Providers\\EventServiceProvider', 'App\\Providers\\RouteServiceProvider', 'App\\Providers\\MacroServiceProvider'), 'eager' =>array('Illuminate\\Auth\\AuthServiceProvider', 'Illuminate\\Cookie\\CookieServiceProvider', 'Illuminate\\Database\\DatabaseServiceProvider', 'Illuminate\\Encryption\\EncryptionServiceProvider', 'Illuminate\\Filesystem\\FilesystemServiceProvider', 'Illuminate\\Foundation\\Providers\\FoundationServiceProvider', 'Illuminate\\Notifications\\NotificationServiceProvider', 'Illuminate\\Pagination\\PaginationServiceProvider', 'Illuminate\\Session\\SessionServiceProvider', 'Illuminate\\View\\ViewServiceProvider', 'Barryvdh\\Debugbar\\ServiceProvider', 'Intervention\\Image\\ImageServiceProvider', 'Spatie\\Backup\\BackupServiceProvider', 'Fideloper\\Proxy\\TrustedProxyServiceProvider', 'Laravel\\Passport\\PassportServiceProvider', 'Unicodeveloper\\DumbPassword\\DumbPasswordServiceProvider', 'Schuppo\\PasswordStrength\\PasswordStrengthServiceProvider', 'App\\Providers\\AppServiceProvider', 'App\\Providers\\AuthServiceProvider', 'App\\Providers\\EventServiceProvider', 'App\\Providers\\RouteServiceProvider', 'App\\Providers\\MacroServiceProvider'), 'deferred' => array('Illuminate\Broadcasting\BroadcastManager' => 'Illuminate\\Broadcasting\\BroadcastServiceProvider', 'Illuminate\Contracts\Broadcasting\Factory' => 'Illuminate\\Broadcasting\\BroadcastServiceProvider', 'Illuminate\Contracts\Broadcasting\Broadcaster' => 'Illuminate\\Broadcasting\\BroadcastServiceProvider', 'Illuminate\Bus\Dispatcher' => 'Illuminate\\Bus\\BusServiceProvider', 'Illuminate\Contracts\Bus\Dispatcher' => 'Illuminate\\Bus\\BusServiceProvider', 'Illuminate\Contracts\Bus\QueueingDispatcher' => 'Illuminate\\Bus\\BusServiceProvider', 'cache' => 'Illuminate\\Cache\\CacheServiceProvider', 'cache.store' => 'Illuminate\\Cache\\CacheServiceProvider', 'memcached.connector' => 'Illuminate\\Cache\\CacheServiceProvider', 'command.cache.clear' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.cache.forget' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.clear-compiled' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.auth.resets.clear' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.config.cache' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.config.clear' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.down' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.environment' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.key.generate' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.migrate' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.migrate.install' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.migrate.refresh' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.migrate.reset' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.migrate.rollback' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.migrate.status' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.optimize' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.queue.failed' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.queue.flush' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.queue.forget' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.queue.listen' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.queue.restart' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.queue.retry' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.queue.work' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.route.cache' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.route.clear' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.route.list' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.seed' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'Illuminate\Console\Scheduling\ScheduleFinishCommand' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'Illuminate\Console\Scheduling\ScheduleRunCommand' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.storage.link' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.up' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.view.clear' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.app.name' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.auth.make' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.cache.table' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.console.make' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.controller.make' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.event.generate' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.event.make' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.job.make' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.listener.make' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.mail.make' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.middleware.make' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.migrate.make' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.model.make' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.notification.make' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.notification.table' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.policy.make' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.provider.make' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.queue.failed-table' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.queue.table' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.request.make' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.seeder.make' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.session.table' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.serve' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.test.make' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'command.vendor.publish' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'migrator' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'migration.repository' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'migration.creator' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'composer' => 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'hash' => 'Illuminate\\Hashing\\HashServiceProvider', 'mailer' => 'Illuminate\\Mail\\MailServiceProvider', 'swift.mailer' => 'Illuminate\\Mail\\MailServiceProvider', 'swift.transport' => 'Illuminate\\Mail\\MailServiceProvider', 'Illuminate\Mail\Markdown' => 'Illuminate\\Mail\\MailServiceProvider', 'Illuminate\Contracts\Pipeline\Hub' => 'Illuminate\\Pipeline\\PipelineServiceProvider', 'queue' => 'Illuminate\\Queue\\QueueServiceProvider', 'queue.worker' => 'Illuminate\\Queue\\QueueServiceProvider', 'queue.listener' => 'Illuminate\\Queue\\QueueServiceProvider', 'queue.failer' => 'Illuminate\\Queue\\QueueServiceProvider', 'queue.connection' => 'Illuminate\\Queue\\QueueServiceProvider', 'redis' => 'Illuminate\\Redis\\RedisServiceProvider', 'redis.connection' => 'Illuminate\\Redis\\RedisServiceProvider', 'auth.password' => 'Illuminate\\Auth\\Passwords\\PasswordResetServiceProvider', 'auth.password.broker' => 'Illuminate\\Auth\\Passwords\\PasswordResetServiceProvider', 'translator' => 'Illuminate\\Translation\\TranslationServiceProvider', 'translation.loader' => 'Illuminate\\Translation\\TranslationServiceProvider', 'validator' => 'Illuminate\\Validation\\ValidationServiceProvider', 'validation.presence' => 'Illuminate\\Validation\\ValidationServiceProvider', 'aws' => 'Aws\\Laravel\\AwsServiceProvider', 'Aws\Sdk' => 'Aws\\Laravel\\AwsServiceProvider', 'html' => 'Collective\\Html\\HtmlServiceProvider', 'form' => 'Collective\\Html\\HtmlServiceProvider', 'Collective\Html\HtmlBuilder' => 'Collective\\Html\\HtmlServiceProvider', 'Collective\Html\FormBuilder' => 'Collective\\Html\\HtmlServiceProvider', 'PragmaRX\Google2FA\Contracts\Google2FA' => 'PragmaRX\\Google2FA\\Vendor\\Laravel\\ServiceProvider', 'command.tinker' => 'Laravel\\Tinker\\TinkerServiceProvider'), 'when' =>array('Illuminate\Broadcasting\BroadcastServiceProvider' => array(), 'Illuminate\Bus\BusServiceProvider' => array(), 'Illuminate\Cache\CacheServiceProvider' =>array(), 'Illuminate\Foundation\Providers\ConsoleSupportServiceProvider' => array(), 'Illuminate\Hashing\HashServiceProvider' => array(), 'Illuminate\Mail\MailServiceProvider' => array(), 'Illuminate\Pipeline\PipelineServiceProvider' => array(), 'Illuminate\Queue\QueueServiceProvider' => array(), 'Illuminate\Redis\RedisServiceProvider' => array(), 'Illuminate\Auth\Passwords\PasswordResetServiceProvider' => array(), 'Illuminate\Translation\TranslationServiceProvider' => array(), 'Illuminate\Validation\ValidationServiceProvider' => array(), 'Aws\Laravel\AwsServiceProvider' =>array(), 'Collective\Html\HtmlServiceProvider' => array(), 'PragmaRX\Google2FA\Vendor\Laravel\ServiceProvider' => array(), 'Laravel\Tinker\TinkerServiceProvider' => array())))in ProviderRepository.php (line 165)
at ProviderRepository->compileManifest(array('Illuminate\\Auth\\AuthServiceProvider', 'Illuminate\\Broadcasting\\BroadcastServiceProvider', 'Illuminate\\Bus\\BusServiceProvider', 'Illuminate\\Cache\\CacheServiceProvider', 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'Illuminate\\Cookie\\CookieServiceProvider', 'Illuminate\\Database\\DatabaseServiceProvider', 'Illuminate\\Encryption\\EncryptionServiceProvider', 'Illuminate\\Filesystem\\FilesystemServiceProvider', 'Illuminate\\Foundation\\Providers\\FoundationServiceProvider', 'Illuminate\\Hashing\\HashServiceProvider', 'Illuminate\\Mail\\MailServiceProvider', 'Illuminate\\Notifications\\NotificationServiceProvider', 'Illuminate\\Pagination\\PaginationServiceProvider', 'Illuminate\\Pipeline\\PipelineServiceProvider', 'Illuminate\\Queue\\QueueServiceProvider', 'Illuminate\\Redis\\RedisServiceProvider', 'Illuminate\\Auth\\Passwords\\PasswordResetServiceProvider', 'Illuminate\\Session\\SessionServiceProvider', 'Illuminate\\Translation\\TranslationServiceProvider', 'Illuminate\\Validation\\ValidationServiceProvider', 'Illuminate\\View\\ViewServiceProvider', 'Barryvdh\\Debugbar\\ServiceProvider', 'Aws\\Laravel\\AwsServiceProvider', 'Intervention\\Image\\ImageServiceProvider', 'Collective\\Html\\HtmlServiceProvider', 'Spatie\\Backup\\BackupServiceProvider', 'Fideloper\\Proxy\\TrustedProxyServiceProvider', 'PragmaRX\\Google2FA\\Vendor\\Laravel\\ServiceProvider', 'Laravel\\Passport\\PassportServiceProvider', 'Laravel\\Tinker\\TinkerServiceProvider', 'Unicodeveloper\\DumbPassword\\DumbPasswordServiceProvider', 'Schuppo\\PasswordStrength\\PasswordStrengthServiceProvider', 'App\\Providers\\AppServiceProvider', 'App\\Providers\\AuthServiceProvider', 'App\\Providers\\EventServiceProvider', 'App\\Providers\\RouteServiceProvider', 'App\\Providers\\MacroServiceProvider'))in ProviderRepository.php (line 61)
at ProviderRepository->load(array('Illuminate\\Auth\\AuthServiceProvider', 'Illuminate\\Broadcasting\\BroadcastServiceProvider', 'Illuminate\\Bus\\BusServiceProvider', 'Illuminate\\Cache\\CacheServiceProvider', 'Illuminate\\Foundation\\Providers\\ConsoleSupportServiceProvider', 'Illuminate\\Cookie\\CookieServiceProvider', 'Illuminate\\Database\\DatabaseServiceProvider', 'Illuminate\\Encryption\\EncryptionServiceProvider', 'Illuminate\\Filesystem\\FilesystemServiceProvider', 'Illuminate\\Foundation\\Providers\\FoundationServiceProvider', 'Illuminate\\Hashing\\HashServiceProvider', 'Illuminate\\Mail\\MailServiceProvider', 'Illuminate\\Notifications\\NotificationServiceProvider', 'Illuminate\\Pagination\\PaginationServiceProvider', 'Illuminate\\Pipeline\\PipelineServiceProvider', 'Illuminate\\Queue\\QueueServiceProvider', 'Illuminate\\Redis\\RedisServiceProvider', 'Illuminate\\Auth\\Passwords\\PasswordResetServiceProvider', 'Illuminate\\Session\\SessionServiceProvider', 'Illuminate\\Translation\\TranslationServiceProvider', 'Illuminate\\Validation\\ValidationServiceProvider', 'Illuminate\\View\\ViewServiceProvider', 'Barryvdh\\Debugbar\\ServiceProvider', 'Aws\\Laravel\\AwsServiceProvider', 'Intervention\\Image\\ImageServiceProvider', 'Collective\\Html\\HtmlServiceProvider', 'Spatie\\Backup\\BackupServiceProvider', 'Fideloper\\Proxy\\TrustedProxyServiceProvider', 'PragmaRX\\Google2FA\\Vendor\\Laravel\\ServiceProvider', 'Laravel\\Passport\\PassportServiceProvider', 'Laravel\\Tinker\\TinkerServiceProvider', 'Unicodeveloper\\DumbPassword\\DumbPasswordServiceProvider', 'Schuppo\\PasswordStrength\\PasswordStrengthServiceProvider', 'App\\Providers\\AppServiceProvider', 'App\\Providers\\AuthServiceProvider', 'App\\Providers\\EventServiceProvider', 'App\\Providers\\RouteServiceProvider', 'App\\Providers\\MacroServiceProvider'))in Application.php (line 549)
at Application->registerConfiguredProviders()in RegisterProviders.php (line 17)
at RegisterProviders->bootstrap(object(Application))in Application.php (line 208)
at Application->bootstrapWith(array('Illuminate\\Foundation\\Bootstrap\\LoadEnvironmentVariables', 'Illuminate\\Foundation\\Bootstrap\\LoadConfiguration', 'Illuminate\\Foundation\\Bootstrap\\HandleExceptions', 'Illuminate\\Foundation\\Bootstrap\\RegisterFacades', 'Illuminate\\Foundation\\Bootstrap\\RegisterProviders', 'Illuminate\\Foundation\\Bootstrap\\BootProviders'))in Kernel.php (line 160)
at Kernel->bootstrap()in Kernel.php (line 144)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

**Comment by JExactly** [comment]
gave permission back to the apache server to the entire snipeit directory not getting Sad Panda System Unavailable display

![image](https://user-images.githubusercontent.com/14076881/30885089-02851d6c-a2e0-11e7-99c4-55b759295f4a.png)

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/getting-help#section-step-3-check-your-app-and-server-logs

**Comment by snipe** [comment]
That's not a 404 or a 500 tho. What happens if you do `php artisan up`?

**Comment by snipe** [comment]
(Sorry, Github didn't refresh with your updates. Grr.) Try `php artisan up` tho

**Comment by JExactly** [comment]
Yea, i thought that too, Thinking that I left it in maintenance mode. Alas, same error :/

**Comment by JExactly** [comment]
This was the last entry in my log file after i Started updating permissions: 

[2017-09-26 17:24:10] production.ERROR: Exception: The bootstrap/cache directory must be present and writable. in /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php:190
Stack trace:
#0 /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(165): Illuminate\Foundation\ProviderRepository->writeManifest(Array)
#1 /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php(61): Illuminate\Foundation\ProviderRepository->compileManifest(Array)
#2 /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(549): Illuminate\Foundation\ProviderRepository->load(Array)
#3 /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
#4 /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(208): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#5 /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(160): Illuminate\Foundation\Application->bootstrapWith(Array)
#6 /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->bootstrap()
#7 /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#8 /var/www/Inventory/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#9 {main}  
[2017-09-26 17:24:10] production.ERROR: ReflectionException: Class session does not exist in /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Container/Container.php:719
Stack trace:
#0 /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Container/Container.php(719): ReflectionClass->__construct('session')
#1 /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Container/Container.php(598): Illuminate\Container\Container->build('session')
#2 /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Container/Container.php(567): Illuminate\Container\Container->resolve('session')
#3 /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(708): Illuminate\Container\Container->make('session')
#4 /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Container/Container.php(840): Illuminate\Foundation\Application->make('session')
#5 /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Container/Container.php(780): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#6 /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Container/Container.php(747): Illuminate\Container\Container->resolveDependencies(Array)
#7 /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Container/Container.php(598): Illuminate\Container\Container->build('Illuminate\\Sess...')
#8 /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Container/Container.php(567): Illuminate\Container\Container->resolve('Illuminate\\Sess...')
#9 /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(708): Illuminate\Container\Container->make('Illuminate\\Sess...')
#10 /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(213): Illuminate\Foundation\Application->make('Illuminate\\Sess...')
#11 /var/www/Inventory/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(187): Illuminate\Foundation\Http\Kernel->terminateMiddleware(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#12 /var/www/Inventory/public/index.php(63): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#13 {main}

**Comment by JExactly** [comment]
Which is why I thought I would give permissions to my apache user for the entire snipeit folder

**Comment by snipe** [comment]
The storage dir still needs to be writable though, and `bootstrap/cache` has to be present and writable. (You were meant to delete the content of the cache dir, not the dir itself)

**Comment by JExactly** [comment]
The directory still exists...I only deleted the contents in the cache directory
![image](https://user-images.githubusercontent.com/14076881/30886379-c68d7b60-a2e4-11e7-8593-54ba3b8da19e.png)

**Comment by JExactly** [comment]
Question, after running all of the commands can I just copy my directory back over and start again?

**Comment by snipe** [comment]
I'm not sure I understand what you mean.

**Comment by JExactly** [comment]
I mean, Could I just restore the original folder I backed up, even though I ran the recrypt command(which I assume runs on the database) and start over again?

**Comment by snipe** [comment]
Probably, but you'd need to make sure you use the app key that was your APP_KEY when you recrypted (not your LEGACY_APP_KEY), or else the encrypted fields will be un-decrptable.

**Comment by JExactly** [comment]
@snipe I would like to try to fix it, but if not, I have a backup of the server that I can restore from last night. as well.
Any ideas on something I could try from the post above with the screenshot?

**Comment by JExactly** [comment]
I restored from a backup, I will attempt the upgrade again tomorrow.
Thanks for all your help @snipe

**Comment by JExactly** [comment]
tried one more time Because, upgrade. Running into the exact same issues.
Issue #1 git pull runs fine as sudo. but when tyrying to run 
`php composer.phar install --no-dev --prefer-source` 
it gives a permissions error and I am forced to run it with sudo as it states i do not have permission.

I think this is the start of all of my problems. that it cannot run this command without sudo, even though it tells me to explicitly not run it as root/sudo. if you can give me some insight here. I would really like to upgrade to V4. Has some features I have requested/been waiting for!!

**Comment by snipe** [comment]
I would probably try it again in a free directory from the beginning if you can. I'm not sure what might have gotten screwed up here, but if you start in a new dir, you can move your .env into the new dir, and move over uploaded files so you don't lose anything.

**Comment by JExactly** [comment]
Redid everything, Seems everything went smooth. Created a new folder and re-cloned git and walked through the steps again! All is working. Thanks again @snipe

**Comment by mahathir83** [comment]
Can you guys help me on step by step upgrade for v3 to v4? I'm trying to follow the manual but fail.

**Comment by snipe** [comment]
@mahathir83 

Please provide us with the information requested at the Getting Help documentation: 
https://snipe-it.readme.io/docs/getting-help
