### ISSUE TITLE
Whoops, looks like something went wrong - fresh new install

### ISSUE THREAD

**Issue by jistar** [snipe/snipe-it#4032]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

after new install of snipe-it, i keep getting this error when i browse to the server:

Whoops, looks like something went wrong.

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running -3.6.6
- What OS and web server you're running Snipe-IT on - ubuntu server 16
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Whoops, looks like something went wrong.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
error i get from apache logs:

[Wed Sep 27 11:59:47.852111 2017] [:error] [pid 15179] [client 172.16.8.10:56173] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/snipe-it/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Logger.php(616): Monolog\\Logger->addRecord(400, Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#3 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Log/Writer.php(203): Monolog\\Logger->error(Object(Symfony\\Component\\Debug\\Exception\\FatalErrorException), Array)\n#4 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Log/Writer.php(114): Illuminate\\Log\\Writer->writeLog('error', Object(Symfony\\Compo in /var/www/snipe-it/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo). no
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by GeoffYoung** [comment]
That "failed to open stream: Permission denied "error means that it can't write to the log file. Whichever user is running the web server doesn't have write permission in the storage directory.

See https://snipe-it.readme.io/docs/upgrading-to-v4#section-step-8-check-permissions
