### ISSUE TITLE
Login not uploading issue V4.0.4

### ISSUE THREAD

**Issue by pratosh448** [snipe/snipe-it#4034]
When i upload login note text and save then it redirect to blank and default text

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by pratosh448** [comment]
Text is not saving in database, when i paste text in database under login_note field then login note showing 
No error showing may be database table not fetching

**Comment by snipe** [comment]
@pratosh448 Please answer the questions we're asking you. We cannot help you unless you do. We need to see a stack trace to see if there's an error being thrown.
