### ISSUE TITLE
Test E-mail from within Settings [Feature Request]

### ISSUE THREAD

**Issue by haynes11** [snipe/snipe-it#4036]
#### Expected Behavior (or desired behavior if a feature request)

The installer has a test e-mail setting but the settings page doesn't. It would also be useful to have the ability to change from one type of e-mail to another or or to be able to change credentials for this in the settings menu rather than having to modify in the .env

#### Actual Behavior

Only happens on installer

**Comment by Jarli01** [comment]
This would be very useful, being able to edit the mail settings without having to go in and edit the .env each and every time.

**Comment by snipe** [comment]
@Jarli01 How often are you really changing these settings though? 

Putting these into the database creates some challenges on our end for hosted customers. If they enter incorrect mail server info (overriding the ones we use for them) and mail stops working, that's an additional support load.

**Comment by haynes11** [comment]
It's a nightmare when it turns out that mail settings aren't working. Like when I switched to Office 365 I didn't realise you couldn't do certain things under certain mailbox types. So it took quite a bit of changing and provisioning till I figured out what worked/didn't and it was quite a bit of hassle having to edit the .env file every single time I wanted to test something.

It would make sense to have a page where you can;

Edit the mail settings
Test the mail settings - so they will immediately know if it's working or not

For your hosted environment - perhaps a revert to default button that inputs the values for your mailservers?

Just some suggestions?

**Comment by Jarli01** [comment]
@snipe it's not an extremely common thing to have to change these settings, but I'm also in a bit of a different boat we're I'm not in control of our email system. 

These settings could be changed at any moment, and I'd then have to go in and update the .env file to reflect those changes. 

Just having the ability to toggle email on or off and to send test emails would be a great feature.

**Comment by snipe** [comment]
I've added a test button. If still want the ability to override env options for mail settings in the settings, please open another issue.

**Comment by Jarli01** [comment]
@snipe awesome

**Comment by johnbchron** [comment]
Looks like the email testing button sends a test email to the from address specified in the .env. Not a huge deal but we're sending from a no-reply, so I can't see the test emails.
