### ISSUE TITLE
Settings/Locations not showing number of assets 

### ISSUE THREAD

**Issue by scottdmay** [snipe/snipe-it#4039]
#### Expected Behavior (or desired behavior if a feature request)

When selecting "Locations" from the settings menu, the different locations should show the number of "assets" and the number of "assets assigned" for each location.

-----

#### Actual Behavior

When selecting "Locations" from the settings menu, the different locations all show "0" for the number of "assets".  The number of "assets assigned" shows the number of assets that have been "checked out" to that location.

-----

#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
v4.0 build 1 (g998c4a5)

- What OS and web server you're running Snipe-IT on
Raspbian Jessie 
Apache2 Web Server

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual Installation

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Locations Page

- If a stacktrace is provided in the error, include that too.
NA

- Any errors that appear in your browser's error console.
NO

- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
It is reproducible in the demo

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

It appears that either the /app/Http/Transformers/LocationTransformers.php 
"$location->assets()->count()" statement does not work or the /App/Models/Location.php "assets()" function is not returning any value.

It also appears that the following may be backwards, though changing it around does not fix the $location->assets()->count() statement:
/app/Http/Transformers/LocationTransformers.php
            'assets_checkedout' => $location->assets()->count(),
            'assets_default'    => $location->assignedassets()->count(),

- Include what you've done so far in the installation, and if you got any error messages along the way.
Fully installed, no errors

- Indicate whether or not you've manually edited any data directly in the database
I have not manually edited the database

![image](https://user-images.githubusercontent.com/22482231/30928887-d33aa328-a38a-11e7-8aa7-0e66ce18937e.png)
![image](https://user-images.githubusercontent.com/22482231/30928916-df87ef8c-a38a-11e7-8eed-134bb8417a30.png)

**Comment by Rbuttow** [comment]
I have the same problem, Whats the solution?
