### ISSUE TITLE
Create Locations Top Level parent_id being set to "0" instead of null in database

### ISSUE THREAD

**Issue by scottdmay** [snipe/snipe-it#4040]
#### Expected Behavior (or desired behavior if a feature request)

Create a new location with the parent = Top Level. The database should list the new location with a parent_id = null

-----

#### Actual Behavior

Create a new location with the parent = Top Level. The database inputs the locations parent_id = 0

If creating a location from the pop up instead, I do get a null value for the parent_id

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

Version of Snipe-IT you're running
v4.0 build 1 (g998c4a5)

What OS and web server you're running Snipe-IT on
Raspbian Jessie
Apache2 Web Server

What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual Installation

WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No

What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Create Locations Page

If a stacktrace is provided in the error, include that too.
NA

Any errors that appear in your browser's error console.
NO

Confirm whether the error is reproduceable on the demo.
It is not

Include any additional information you can find in app/storage/logs and your webserver's logs.
NA

Include what you've done so far in the installation, and if you got any error messages along the way.
Fully installed, no errors

Indicate whether or not you've manually edited any data directly in the database
I have not manually edited the database

**Comment by snipe** [comment]
Can you pull from develop and see if this resolves your issue?

**Comment by scottdmay** [comment]
Pulled from the develop branch. Fix worked! You are awesome, thank you!
