### ISSUE TITLE
Create token Error V4.0.4

### ISSUE THREAD

**Issue by pratosh448** [snipe/snipe-it#4041]
1-OAuth API Settings create new client error 
2-Create New token under Personal API keys also error

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by dmeltzer** [comment]
Probably fixed by #4090 ? Hard to know without knowing what the bug is.

**Comment by pratosh448** [comment]
Install manual
PHP 7.22
In oAauth nothing to so in console 
But in api key console showing error
