### ISSUE TITLE
1D Barcode Generated off page

### ISSUE THREAD

**Issue by scottdmay** [snipe/snipe-it#4042]
#### Expected Behavior (or desired behavior if a feature request)

Generate a 1D barcode to fit a standard 2.625" x 1" label

-----

#### Actual Behavior

Barcode gets generated but is too wide and too low. See attached picture. This is true for any barcode type as well as any label size. Also tried adjusting the font size to the smallest size possible with no luck.

<img width="461" alt="screen shot 2017-09-27 at 5 07 56 pm" src="https://user-images.githubusercontent.com/22482231/30938070-d1932588-a3a6-11e7-917f-c41833a9373c.png">

<img width="276" alt="screen shot 2017-09-27 at 5 11 49 pm" src="https://user-images.githubusercontent.com/22482231/30938122-0ab81382-a3a7-11e7-8d71-d2e09a802780.png">

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
Please provide answers to these questions before posting your bug report:

Version of Snipe-IT you're running
v4.0 build 1 (g998c4a5)

What OS and web server you're running Snipe-IT on
Raspbian Jessie
Apache2 Web Server

What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual Installation

WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No

What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Assets page when generating a barcode label 

If a stacktrace is provided in the error, include that too.
NA

Any errors that appear in your browser's error console.
NO

Confirm whether the error is reproduceable on the demo.
It is reproducible on the demo

Include any additional information you can find in app/storage/logs and your webserver's logs.
NA

Include what you've done so far in the installation, and if you got any error messages along the way.
Fully installed, no errors

Indicate whether or not you've manually edited any data directly in the database
I have not manually edited the database

**Comment by thakilla** [comment]
@scottdmay i made a pull request for that and fixed the barcode for small labels
https://github.com/snipe/snipe-it/pull/4258
