### ISSUE TITLE
API 'groups' endpoint inconsistent JSON output

### ISSUE THREAD

**Issue by ghaberek** [snipe/snipe-it#4043]
#### Expected Behavior

Calls to `/api/v1/groups` should produce an array of `rows` containing the same JSON structure as request for a single group, e.g. `/api/v1/groups/1`.

-----

#### Actual Behavior

Structure varies between the two calls.

    /api/v1/groups/1
    {
        "created_at": "2016-06-07 16:43:46",
        "id": 1,
        "name": "Admin",
        "permissions": "{\"admin\":1,\"users\":1,\"reports\":1,\"license_keys\":1}",
        "updated_at": "2016-06-08 14:53:09"
    }

    /api/v1/groups?limit=1&offset=0
    {
        "rows": [
            {
                "available_actions": {
                    "delete": true,
                    "update": true
                },
                "created_at": {
                    "datetime": "2016-06-07 16:43:46",
                    "formatted": "2016-06-07 04:43 PM"
                },
                "id": 1,
                "name": "Admin",
                "permissions": "{\"admin\":1,\"users\":1,\"reports\":1,\"license_keys\":1}",
                "updated_at": {
                    "datetime": "2016-06-08 14:53:09",
                    "formatted": "2016-06-08 02:53 PM"
                },
                "users_count": 6
            }
        ],
        "total": 1
    }

-----

#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running *v4.0 build 1 (g998c4a5)*
- What OS and web server you're running Snipe-IT on *CentOS 7.4.1708*, *Apache/2.4.6*

-----

> This documentation (and the API itself) is still under development, so some things may not work exactly as expected, or we may not have code examples and sample responses for everything just yet. Please be patient. As we continue to develop the API, we are updating the documentation.

Also, while I understand that the API is still in flux, I have a lot of questions and suggestions for it. What is the proper venue for this discussion and contribution? When I try to visit the [contributing](https://snipe-it.readme.io/docs/contributing) page, I get a **404 Page Not Found** error.

**Comment by snipe** [comment]
GH issues is the place to discuss improvements/feature requests, etc. Contributing docs are here: https://snipe-it.readme.io/docs/contributing-overview
