### ISSUE TITLE
Users seem to require admin permissions to scan barcodes

### ISSUE THREAD

**Issue by simonc21** [snipe/snipe-it#4047]
#### Expected Behavior (or desired behavior if a feature request)

I have delegated a selection of users to view, check in and check out assets. They can manually go into the asset and check it in or out successfully. However, scanning the (1D) barcode of the asset does nothing, it does not bring up the assets' page. This only works if I delegate the user full admin permissions, which is not desirable.

-----

#### Actual Behavior

Scanning a barcode does absolutely nothing unless the user is granted full admin permissions.

-----

#### Please confirm you have done the following before posting your bug report:

- [y] I have enabled debug mode
- [y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

Snipe v3.6.6 build 1 - fresh manual install
Windows Server 2016
No errors evident in the browser with debug mode enabled
User only has access to view assets and users screens, scanning a barcode does nothing in either
Apart from this issue, everything else appears to be working fine

**Comment by snipe** [comment]
Scanning a barcode only opens the view URL, so I'm not really sure how that's happening. Scanning the 1D barcode is meant to be used with the top search bar (so that top search bar should have focus).

**Comment by simonc21** [comment]
Thanks for the quick reply. With my non-admin account I have to click into the search box so the cursor is flashing and then scanning works fine. I don't need to do that as an admin, it works from anywhere on the screen. I'll just have to train the users. Happy to close.

As an aside, our users would love to have the ability to just scan items in and out without assigning to users as per feature request #3152, putting in a +1 vote for that feature please!
