### ISSUE TITLE
Could use some install help - using install.sh on Ubuntu 16.04

### ISSUE THREAD

**Issue by Cryovenom** [snipe/snipe-it#4058]
I'm following [this](https://community.spiceworks.com/how_to/132545-install-snipe-it-asset-management-on-ubuntu-14-04) relatively simple guide for installing on Ubuntu 16.04 and I'm running into an issue.

Here's my process from scratch:

**OS Setup**
* Create a new blank Virtual Machine (I'm on vSphere 6.0, creating a new Ubuntu x64 VM, hardware version 8)
* Mount ISO : ubuntu-16.04.3-server-amd64.iso
* Boot VM, run Ubuntu install, entirely default settings except that I add "LAMP" and "OpenSSH" at the package selection screen
* After reboot log in as my non-root user (I called it "administrator") and set the static IPv4 and IPv6 settings on the interface (make edits to /etc/network/interfaces and then sudo service networking restart... make sure I can ping google)

**Attempted Snipe-IT Setup**

* sudo wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh
* sudo chmod 744 install.sh ./install.sh
* ./install.sh

The install asks for my FQDN, no problem. Then it asks if I want it to auto create the snipe DB user password. I say no and enter the one I want. So far, so good.

Then, right after it says "MySQL Phase next." it prompts me to "Enter password for user root:" 

I've tried the password for my "administrator" account. I've tried the password for the snipe DB. I've tried the root password for MySQL that I set during OS install. I've tried first running "sudo su -" to get a shell running as root before running the install.sh . I've even tried setting the root password using sudo passwd root before running install.sh and providing the actual root password for the box. 

Every time without fail I get "Error: Access denied for user 'root'@'localhost' (using password: YES)" , or in rare cases I get it just sitting there blinking a cursor at me.

If it gives me Access Denied the installer just continues with "Creating MySql Database and User" where it asks for my MySQL roto password, but I don't know what broke in that step where it didn't accept my password.

If it just blinks at me I can hit enter a half dozen or so times, then it seems to suddenly jump to the bottom of the installer with a whole bunch of questions having been answered with their defaults. 

I've tried the install multiple times and I'm just not sure where I'm going wrong. Which root password is it looking for, and why won't it accept anything I'm putting in?

I'm not too bad with Ubuntu/Linux but it's definitely a secondary skill for me. The vast majority of my environment is Microsoft-based. So that's why I opted for the pre-rolled install script instead of a manual install. Sorry if I've missed anything really small or obvious.

**Comment by Cryovenom** [comment]
Okay, so after making this post I made a bit of a breakthrough. Hopefully this will help others, or maybe some change to the script can be made to fix it.

The difference between "Access Denied" and just a blinking cursor is that when I enter the password it's looking for I get the blinking cursor. For reference, it's looking for the MySQL root user password that you set during OS install (assuming you've selected LAMP during install)

I opened up the script and figured out that the step where the problem is happening is where it runs "/usr/bin/mysql_secure_installation"

If I just run that myself from the shell it will ask me a variety of questions:
* Would you like to setup VALIDATE PASSWORD Plugin?
* Change the password for root?
* Remove anonymous users?
* Disallow root login remotely?
* Remove test database and access?
* Reload privilege tables?

However, when install.sh runs it, the output is being directed somewhere other than the screen. So it accepts my password and waits for my answer to the first question, but it hasn't displayed anything on screen so I don't know what it's waiting for.

That's why when I "hit enter half a dozen or so times" it suddenly shows all the questions and the default answers I provided! 

So what I've done now is I refreshed my environment, then re-ran install.sh . When it got to the root password question I entered the MySQL root password, then pressed enter. It sat there blinking at me so I answered the five questions blind (enter, enter, Y enter, Y enter, Y enter, Y enter) and was able to proceed!

Hopefully this info enables someone else to recreate the issue and figure out how to make the questions appear on screen during the script. OR at the very least if someone else if having this problem hopefully it will save them the day's worth of troubleshooting it took me to figure out.

Cheers

**Comment by Cryovenom** [comment]
Hm, now I've edited apache's 000-default.conf to set DocumentRoot to /var/www/snipeit/public as per the tutorial and rebooted... but when I visit the server's FQDN in a browser I just get a blank white page. 

I'm assuming I'm missing some plugins or dependencies? I was kind of hoping the install script would take care of those - as I said, I'm more of a windows sysadmin than a linux one and didn't want to spend a lot of time installing extensions to php/apache... 

Can anyone point me in the right direction for troubleshooting this?

**Comment by Cryovenom** [comment]
I used php -m to see all the modules that were installed. The ones missing (according to the [requirements](https://snipe-it.readme.io/v3.6.2/docs/requirements) in the Snipe-IT Documentation) were mysql and phpzip. 

It looks like mysql was deprecated/removed and mysqli is the replacement? And while I don't see phpzip I do see just "zip", is that equivalent?

To (hopefully) make things easier I downloaded Ubuntu 14.04 to try instead of 16.04. It has mysql listed in its modules (still no phpzip, just zip), AND it doesn't have that blind-question-answering problem from before... but I still just get a blank white page with no source behind it when I try to visit the FQDN of the server in a web browser.

I could REALLY use some help here, this thing is starting to be a bit frustrating...

**Comment by tiagom62** [comment]
Please try again with the current install script.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
