### ISSUE TITLE
Incorrect Assets by Status

### ISSUE THREAD

**Issue by tx7** [snipe/snipe-it#4060]
Hello,
First, I would like to say thanks for version 4.0.4.
It looks good and running smooth.

However, my assets by status display incorrect.
Deployed and Broken - Not Fixable are labeling as 'Deployed' in the dashboard.

My status labels are like this: 

Status Name     Status type
Pending         Pending  
Ready to Deploy | deployable .     #00914b

Archived | archived 
Out for Repair | undeployable |   |   |  
Broken - Not Fixable | archived | #e82121 |   |  
Lost/Stolen | undeployable |   |   |  
Never Returned | undeployable |   |   |  
Deployed | undeployable | #2f00b5

**Comment by snipe** [comment]
Can you add a screenshot to explain what you mean?

**Comment by tx7** [comment]
![screen shot 2017-09-29 at 7 28 56 pm](https://user-images.githubusercontent.com/13337620/31039543-7d0cbf18-a54c-11e7-88a8-24cbcb749e2f.png)

**Comment by snipe** [comment]
Why is your Deployed status undeployable?

**Comment by snipe** [comment]
I think this might be an issue if the meta status being confusing. https://snipe-it.readme.io/docs/overview#section-status-labels

**Comment by tx7** [comment]
If the the asset already deployed, then it'll not be available to deploy.

**Comment by snipe** [comment]
If an asset is already assigned, the status type is still ready to deploy. The status type describes the physical state of the asset (is it working and deployable, is it broken, etc) not whether or not it's checked out. The meta status describes whether or not it's checked out.

**Comment by tx7** [comment]
But the graph is confusing b/c there are two deployed status.

**Comment by snipe** [comment]
You can rename your Deployed status label then. As I said, status labels are meant to describe the physical condition of the asset, not whether or not it's assigned to anyone.
