### ISSUE TITLE
Upgrade from v3.6.6 to v4.0.5 | I'm trying to execute "php artisan migrate" I got error class not defined. 

### ISSUE THREAD

**Issue by itims** [snipe/snipe-it#4062]
Hi,
I'm trying to execute "php artisan migrate" I got error class not defined. "

[Symfony\Component\Debug\Exception\FatalThrowableError] Class 'Illuminate\Notifications\NotificationServiceProvider' not found" 

Could you please help me?

![image](https://user-images.githubusercontent.com/23715217/31003133-9aad37d2-a50b-11e7-808e-55b2f480793a.png)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running - **3.6.6**
- What OS and web server you're running Snipe-IT on - **Ubuntu 14 server & Apache2**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - **install.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
[Remove the contents of the `bootstrap/cache` directory](https://snipe-it.readme.io/docs/upgrading-to-v4#section-step-4-remove-old-cache-files).

Then run:

```
composer dump
php artisan cache:clear
php artisan route:clear
php artisan view:clear
```

**Comment by itims** [comment]
I removed the contents of the "bootstrap/cache" then run composer dump. But I couldn't run the following commands, getting the same error as previous has happened.
php artisan cache:clear
php artisan route:clear
php artisan view:clear
![image](https://user-images.githubusercontent.com/23715217/31013491-f8d6233c-a533-11e7-99a9-2f92c436112f.png)

**Comment by snipe** [comment]
Did your `composer install --no-dev --prefer-source` give you any errors when you ran it?

**Comment by itims** [comment]
I didn't get any errors.

**Comment by itims** [comment]
![image](https://user-images.githubusercontent.com/23715217/31014958-2d71acc2-a53b-11e7-864a-c3a70afd183b.png)

**Comment by snipe** [comment]
Try deleting your vendor directory and re-running the composer install command

**Comment by itims** [comment]
I deleted the contents of vendor directory and executed the composer install command. Then I'm trying to execute "php artisan migrate" I got error like this.

root@ashir:/var/www/snipeit# php artisan migrate
PHP Fatal error:  Class 'Illuminate\Foundation\Application' not found in /var/www/snipeit/bootstrap/app.php on line 14

**Comment by dmeltzer** [comment]
The log you pasted makes it look like you're missing some php extensions.. look further up in that.

**Comment by itims** [comment]
Could you please help me?
