### ISSUE TITLE
Checked out accessory details not showing since upgrade from v3.x to v4.0.4 build 1 (geca5a05)

### ISSUE THREAD

**Issue by rich678** [snipe/snipe-it#4064]
#### Expected Behavior (or desired behavior if a feature request)

When i click on "accessories" and click an accessory i should be able to view checked out details.

-----

#### Actual Behavior

"No matching records found" when i click on an accessory that should be displaying checked out details. The "total" and "avail" are showing the correct numbers. This started occurring after upgrading from v3.x to v4.0.4 build 1 (geca5a05).

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v4.0.4 build 1 (geca5a05)
- What OS and web server you're running Snipe-IT on: Ubuntu 16.04.3 LTS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: /accessories/1
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).: Demo has the same behavior.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.: This started occurring after upgrading from v3.x to v4.0.4 build 1 (geca5a05). This was done by following your upgrade instructions (seemed to go seamlessly)
- Indicate whether or not you've manually edited any data directly in the database: no

**Comment by rich678** [comment]
Exact steps followed: https://snipe-it.readme.io/v4.0/docs/upgrading-to-v4
The only thing i was unsure about was "Step 8: Check permissions". What permissions do these directories need? I'm by no means a Linux pro, more of an intermediate user.

Thanks again,

Ryan

**Comment by snipe** [comment]
This was fixed in the latest release.

**Comment by rich678** [comment]
Working perfectly now! Thanks!
