### ISSUE TITLE
Optional custom fields not optional

### ISSUE THREAD

**Issue by diekmanu** [snipe/snipe-it#4067]
#### Expected Behavior (or desired behavior if a feature request)

Leave optional custom fields blank.

![2017-09-29_12h06_12](https://user-images.githubusercontent.com/13235891/31011979-7938b450-a510-11e7-8248-3b886544e465.png)

-----

#### Actual Behavior

Error message:
![2017-09-29_12h13_56](https://user-images.githubusercontent.com/13235891/31011926-4e77cf30-a510-11e7-89f2-309bb8541222.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running: v4.0.5 build 40 (g42c2a66) 
- What OS and web server you're running Snipe-IT on: nginx, win7x64
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Can you do a pull from develop and let me know if that fixes it?

**Comment by snipe** [comment]
(Laravel 5.4 changed the way nullable fields are handled, so that you have to specify them as nullable, whereas before you could just leave them as *not* required. I thought we corrected that everywhere, but apparently not.)

**Comment by diekmanu** [comment]
Superb! Develop works for me. Thanks again @snipe

**Comment by snipe** [comment]
Try one more time - I just refactored that a tiny bit and want to make sure I didn't break anything :P

**Comment by diekmanu** [comment]
Commit 2e76620cf8e3647a93db4e3713260294c21ced9b still works for me.

**Comment by snipe** [comment]
Awesome, thanks for testing so quickly!
