### ISSUE TITLE
Migrating issue

### ISSUE THREAD

**Issue by rWaddles** [snipe/snipe-it#4071]
#### Expected Behavior (or desired behavior if a feature request)

Run command php artisan migrate
To get nothing to migrate

-----

#### Actual Behavior

PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string                                                               in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Exceptio                                                              ns/Handler.php:96
Stack trace:
#0 [internal function]: Illuminate\Foundation\Exceptions\Handler->Illuminate\Fou                                                              ndation\Exceptions\{closure}(0, 'Illuminate\\Auth...')
#1 /var/www/snipe-it/bootstrap/cache/compiled.php(6449): call_user_func(Object(C                                                              losure), 0, 'Illuminate\\Auth...')
#2 /var/www/snipe-it/bootstrap/cache/compiled.php(12660): Illuminate\Support\Arr                                                              ::first(Array, Object(Closure), NULL)
#3 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Exceptio                                                              ns/Handler.php(97): Illuminate\Support\Collection->first(Object(Closure))
#4 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Exceptio                                                              ns/Handler.php(61): Illuminate\Foundation\Exceptions\Handler->shouldntReport(Obj                                                              ect(Symfony\Component\Debug\Exception\FatalThrowableError))
#5 /var/www/snipe-it/app/Exceptions/Handler.php(37): Illuminate\Foundation\Excep                                                              tions\Handler->report(Object( in /var/www/snipe-it/vendor/laravel/framework/src/                                                              Illuminate/Foundation/Exceptions/Handler.php on line 96

-----

#### Please confirm you have done the following before posting your bug report:

- [Y ] I have enabled debug mode - though obviously this stage doesn't show anything
- [Y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

Going through the upgrade procedure everything seems to be running fine until this error. If it plainly looks like User error just shout

**Comment by snipe** [comment]
I'd start by re-doing this part: https://snipe-it.readme.io/docs/upgrading-to-v4#section-step-4-remove-old-cache-files

**Comment by rWaddles** [comment]
Re-ran through that part and I had missed services it had seemed. Thank you!
