### ISSUE TITLE
Hello Snipe Please add default time when select previous and next date on Mail It's showing 00:00:00

### ISSUE THREAD

**Issue by pratosh448** [snipe/snipe-it#4074]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
On *which* mail? You keep opening tickets and not providing any details. Please take the time to include screenshots and additional information (and answers to the questions you keep deleting.) By creating partial tickets, you waste our time having to come back and ask you (again) to answer the questions we need to be able to understand your problem.

![helpme-helpyou](https://user-images.githubusercontent.com/197404/31039239-fc70e75a-a530-11e7-841f-d6d71f8c9886.gif)

**Comment by pratosh448** [comment]
![issues](https://user-images.githubusercontent.com/31343768/31073049-f55b5398-a787-11e7-9bee-76d7e8f9b60f.jpg)
