### ISSUE TITLE
New 4.04 installation (upgraded to 4.06)

### ISSUE THREAD

**Issue by stf675** [snipe/snipe-it#4076]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Please provide answers to these questions before posting your bug report:

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is [reproduceable on the demo](https://snipeitapp.com/demo).
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Brand new install of CentOS 6.9 minimal Desktop
used wget to get install.sh
run install.sh, accepted defaults, created db password
pasted from example and modified .env file

Logged in OK

Issues out of the box:

LDAP - test never complete but sync worked (show users)
LDAP login not working 
When create a group it says group created OK, but not visible after.  when try to create new user then groups are visible.
Creating new location - clicking save button  does nothing.

I did not test further but it looked like there are major issues.

At this point what would be recommended steps?  Start from scratch?

**Comment by snipe** [comment]
Install.sh is still buggy with this latest release. We recommend you install via git (like we always recommend)

**Comment by stf675** [comment]
trying with 4.06, something changed with composer setup?

**running**

`php composer.phar install --no-dev --prefer-source`


**results in**

```
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/inflector v1.2.0 -> satisfiable by doctrine/inflector[v1.2.0].
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.31) does not satisfy that requirement.
  Problem 2
    - doctrine/inflector v1.2.0 requires php ^7.0 -> your PHP version (5.6.31) does not satisfy that requirement.
    - doctrine/common v2.7.3 requires doctrine/inflector 1.* -> satisfiable by doctrine/inflector[v1.2.0].
    - Installation request for doctrine/common v2.7.3 -> satisfiable by doctrine/common[v2.7.3].

```

**Comment by snipe** [comment]
Are you pulling this from a tagged release or a branch? (If branch which one?)

**Comment by stf675** [comment]
4.07 fixed the issue with installation and saving (the one I had with 4.04)

Thank you
