### ISSUE TITLE
Checkin License in v4.0.6 takes me to base url of server

### ISSUE THREAD

**Issue by raakhtar** [snipe/snipe-it#4081]
I am running snipe-it under a subdirectory in 4.0.6 and upon Licence checkin I am redirected to base url of server without the "snipe-it" in it. e.g redirected to http://10.xx.xx.xx:81/ instead of http://xx.xx.xx.xx:81/snipe-it/

Sub-directory is really messy at the moment in v4.0+ @snipe 

please fix this issue urgently

**Comment by dmeltzer** [comment]
Where are you checking in from?  Is this related to your other license checkin bug?

**Comment by raakhtar** [comment]
I am not sure if this is related to other licence bug. But when running snipe it under subdirectory. Any licence check in takes me to the base url of the server which shows the default IIS page.

**Comment by snipe** [comment]
@raakhtar please try latest from the develop branch.

We're aware that subdirectories are very messy right now. This is why we recommend against running it in a subdirectory in the documentation, and always have.

**Comment by raakhtar** [comment]
Its fixed in v4.0.8 build 102. The subdirectory had been perfectly working fine with v3.6.6.

But i belive you guys are almlost there with fixing the subdirectory issue completely, ur massive effort and support is greatly appreciated @snipe

Kudos
