### ISSUE TITLE
Feature Request for History permission 

### ISSUE THREAD

**Issue by pratosh448** [snipe/snipe-it#4082]
add history in Permissions only permit user can see history not all

**Comment by yoda84** [comment]
100% agree.
At this moment there are no restrictions - a (standard) user can see the whole History. An absolute minimum would be limitation based on Company. Of course it would be better if from default a user can't see the History logs (maybe besides Assets, Software etc. assigned to him/her) and only adding an additionally check mark would give him/her this permission.
I think this should ba an "Actual Behaviour" in a software that supports a multi-tenancy model.

Additionally what I've observe a user start to see the History logs after an (first) asset is assigned to him/her. 

@snipe is this a planned behaviour?
