### ISSUE TITLE
Consumable error upon accepting 

### ISSUE THREAD

**Issue by Expada** [snipe/snipe-it#4086]
hi snipe,

basically i would do the same way checking out consumable items just like i did checking out assets but the thing is after user receive acceptance email and when they logged in this error shows up.  

![capture](https://user-images.githubusercontent.com/32293464/31045780-b988fdf4-a61d-11e7-8b01-7c22c45eeffd.JPG)

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Haven't heard back, so I'm going to close this ticket for now, but will re-open it if you're still having issues

**Comment by Expada** [comment]
sorry for leaving this thread abandoned quite a long time. regarding the issue i here attached the logs from laravel and those details you required

Provide answers to these questions:
Is this a fresh install or an upgrade? - upgrade
Version of Snipe-IT you're running - 4.18
Version of PHP you're running - v7.19
Version of MySQL/MariaDB you're running - 5.7.19
What OS and web server you're running Snipe-IT on - Win7 / wamp
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual now git
WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - cant enter debug mode
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - checkout and checkin
If a stacktrace is provided in the error, include that too.
Any errors that appear in your browser's error console.
Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - nope
Include any additional information you can find in app/storage/logs and your webserver's logs. -
Include what you've done so far in the installation, and if you got any error messages along the way.
Indicate whether or not you've manually edited any data directly in the database - nope
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

[laravel.log](https://github.com/snipe/snipe-it/files/1599549/laravel.log)
