### ISSUE TITLE
Manage Api Keys Display nothing on the page v4.0.6

### ISSUE THREAD

**Issue by raakhtar** [snipe/snipe-it#4087]
Empty Screen

"Personal Api Key" text is only displayed

**Comment by dmeltzer** [comment]
What is the difference between this and #4089 ?

**Comment by dmeltzer** [comment]
If this is a subdirectory, it should also be fixed in #4090

**Comment by raakhtar** [comment]
its a subdirectory. and yes a fix for this should certainly fix #4090 too

**Comment by ellisgeek** [comment]
@snipe Any idea when this will be merged into master? I'd like to be able to create tokens to start work on a Powershell script to inventory machines directly into Snipe-IT. This also appears to effect the Import page.

**Comment by snipe** [comment]
Master is up to date with develop

**Comment by raakhtar** [comment]
Fixed in build v4.0.8 build 102
