### ISSUE TITLE
Image broken on  Change your avatar at Gravatar.com under "Edit Your profile" v4.0.6

### ISSUE THREAD

**Issue by raakhtar** [snipe/snipe-it#4088]
Image broken for  "Change your avatar at Gravatar.com"

**Comment by dmeltzer** [comment]
![spectacle k10293](https://user-images.githubusercontent.com/3803132/31057007-6301c83a-a6a9-11e7-8831-f3f27353a42a.png)

Seems to work here... Is this what you are talking about?

**Comment by raakhtar** [comment]
yes.. again its a subdirectory

**Comment by snipe** [comment]
That image pulls directly from gravitar. Do you have your install isolated from the outside world?

**Comment by raakhtar** [comment]
It is fixed after updating to build 4.0.8 build 102

**Comment by snipe** [comment]
Please close issues if they've been resolved.
