### ISSUE TITLE
OAuth API Setting Page empty on v4.0.6

### ISSUE THREAD

**Issue by raakhtar** [snipe/snipe-it#4089]
Empty Page 

Settings ->OAuth -> Results in Empty Page

**Comment by pratosh448** [comment]
oAuth create but not showing 
User API key create also error

**Comment by dmeltzer** [comment]
@raakhtar This works for me locally.  This is rendered via javascript, can you see if there is anything in your javascript debug console when trying to load that page?

@pratosh448 Please open an issue for different bugs, that way we can track them (Also please use the template when reporting bugs, to provide all of the information necessary to understand what is going on)

**Comment by dmeltzer** [comment]
Can you clarify if this is in a subdirectory?

**Comment by raakhtar** [comment]
yes its a subdirectory

**Comment by pratosh448** [comment]
![error](https://user-images.githubusercontent.com/31343768/31068951-e3c43dee-a777-11e7-8e7c-87fddb4ac56c.jpg)

**Comment by raakhtar** [comment]
Fixed now in 4.0.8 build 102
