### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by ericdude101** [snipe/snipe-it#409]
Two things that I would love to see are the ability to export the data so I could be able to integrate it with other systems, also a bulk create/edit. Currently using this system in a school environment, I come across a lab where I just bought say 100 of the same exact model computer, it would be nice to be able to enter all the base info and just hit each machines serial barcode and have it added rather than having to create a new asset and fill out the form individually for each machine. Even just more predefined information based on a model of computer would be great. Like a quick add I guess.

**Comment by thatguychrisw** [comment]
I didn't see the export to csv as a feature request in Waffle.io.  I forked the project to take a look at possibly implementing this feature, but I don't want to step on anyone's toes.

**Comment by snipe** [comment]
Would the export you get with reports not work for your purposes?
