### ISSUE TITLE
Filtering not working on different views except all

### ISSUE THREAD

**Issue by diekmanu** [snipe/snipe-it#4097]
#### Expected Behavior (or desired behavior if a feature request)

When I enter different search strings in the search box filtering should work in all views including "Pending", "Deployed", "RTD", "Activity Report', etc.

Advanced search works in these views, but not all the expected results are displayed.

-----

#### Actual Behavior

When I enter different search strings in the search box filtering is only working in the "ALL" view.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running: v4.0.9 build 189 (g907b909) / develop
- Version of PHP you're running: 5.6.29
- Version of MySQL/MariaDB you're running: MariaDB 10.1.3
- What OS and web server you're running Snipe-IT on: win7x64, nginx
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by diekmanu** [comment]
**laravel.log:**
`Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'status_id' in where clause is ambiguous (SQL: select count(*) as aggregate from `assets` left join `users` on `users`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\Models\User left join `locations` on `locations`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\Models\Location left join `assets` as `assigned_assets` on `assigned_assets`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\Models\Asset where (exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `categories` where `models`.`category_id` = `categories`.`id` and (`categories`.`name` LIKE %diekmanu% or `models`.`name` LIKE %diekmanu% or `models`.`model_number` LIKE %diekmanu%) and `categories`.`deleted_at` is null)) or exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `manufacturers` where `models`.`manufacturer_id` = `manufacturers`.`id` and (`manufacturers`.`name` LIKE %diekmanu%) and `manufacturers`.`deleted_at` is null)) or (exists (select * from `status_labels` where `assets`.`status_id` = `status_labels`.`id` and `status_labels`.`name` LIKE %diekmanu% and `status_labels`.`deleted_at` is null)) or (exists (select * from `suppliers` where `assets`.`supplier_id` = `suppliers`.`id` and `suppliers`.`name` LIKE %diekmanu% and `suppliers`.`deleted_at` is null)) or (exists (select * from `companies` where `assets`.`company_id` = `companies`.`id` and `companies`.`name` LIKE %diekmanu%)) or (exists (select * from `locations` where `assets`.`rtd_location_id` = `locations`.`id` and `locations`.`name` LIKE %diekmanu% and `locations`.`deleted_at` is null)) or (exists (select * from `assets` as `laravel_reserved_0` where `laravel_reserved_0`.`id` = `laravel_reserved_0`.`assigned_to` and (`users`.`first_name` LIKE %diekmanu% or `users`.`last_name` LIKE %diekmanu% or `users`.`username` LIKE %diekmanu% or `locations`.`name` LIKE %diekmanu% or `assigned_assets`.`name` LIKE %diekmanu%) and `laravel_reserved_0`.`deleted_at` is null)) or `assets`.`name` LIKE %diekmanu% or `assets`.`asset_tag` LIKE %diekmanu% or `assets`.`serial` LIKE %diekmanu% or `assets`.`order_number` LIKE %diekmanu% or `assets`.`notes` LIKE %diekmanu% or `assets`.`_snipeit_mac_address_1` LIKE %diekmanu% or `assets`.`_snipeit_ip_adresse_2` LIKE %diekmanu% or `assets`.`_snipeit_lan_port_3` LIKE %diekmanu% or `assets`.`_snipeit_raum_6` LIKE %diekmanu% or `assets`.`_snipeit_dsm_rc_viewer_7` LIKE %diekmanu%) and `assets`.`deleted_at` is null and `status_id` = 1)' in D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Database\Connection.php:647
Stack trace:
#0 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Database\Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
#1 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Database\Connection.php(326): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#2 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1706): Illuminate\Database\Connection->select('select count(*)...', Array, true)
#3 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1690): Illuminate\Database\Query\Builder->runSelect()
#4 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2025): Illuminate\Database\Query\Builder->get(Array)
#5 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1953): Illuminate\Database\Query\Builder->aggregate('count', Array)
#6 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(1251): Illuminate\Database\Query\Builder->count()
#7 D:\SYSTEM\WPN-XM\www\snipe-it_v4\app\Http\Controllers\Api\AssetsController.php(198): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#8 D:\SYSTEM\WPN-XM\www\snipe-it_v4\app\Http\Controllers\Api\AssetsController.php(198): Illuminate\Database\Eloquent\Builder->count()
#9 [internal function]: App\Http\Controllers\Api\AssetsController->index(Object(Illuminate\Http\Request))
#10 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(55): call_user_func_array(Array, Array)
#11 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('index', Array)
#12 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Route.php(204): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\AssetsController), 'index')
#13 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Route.php(160): Illuminate\Routing\Route->runController()
#14 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Router.php(572): Illuminate\Routing\Route->run()
#15 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#18 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#21 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#22 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#23 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#24 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#25 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\barryvdh\laravel-debugbar\src\Middleware\Debugbar.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 D:\SYSTEM\WPN-XM\www\snipe-it_v4\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\fideloper\proxy\src\TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 D:\SYSTEM\WPN-XM\www\snipe-it_v4\app\Http\Middleware\CheckForSetup.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 D:\SYSTEM\WPN-XM\www\snipe-it_v4\app\Http\Middleware\NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 D:\SYSTEM\WPN-XM\www\snipe-it_v4\app\Http\Middleware\ContentSecurityPolicyHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\ContentSecurityPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 D:\SYSTEM\WPN-XM\www\snipe-it_v4\app\Http\Middleware\ReferrerPolicyHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\ReferrerPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 D:\SYSTEM\WPN-XM\www\snipe-it_v4\app\Http\Middleware\XssProtectHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 D:\SYSTEM\WPN-XM\www\snipe-it_v4\app\Http\Middleware\FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#63 D:\SYSTEM\WPN-XM\www\snipe-it_v4\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#64 D:\SYSTEM\WPN-XM\www\snipe-it_v4\public\index.php(59): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#65 {main}  `

Same exception on the demo pages

**Comment by diekmanu** [comment]
Seems to be related to #4198

**Comment by snipe** [comment]
Can you see if the latest release fixes this?

**Comment by diekmanu** [comment]
This is working now in all views (v4.0.15)

**Comment by snipe** [comment]
👍 thanks for confirming!
