### ISSUE TITLE
Asset status issues

### ISSUE THREAD

**Issue by Ramchak** [snipe/snipe-it#410]
I recently upgraded to 1.1 and am having a bit of trouble with new assets. When I Look at the Deployed assets from the Navigation menu on the left, I see all of my deployed assets as I should. However, when I look at the Pending or Ready to Deploy assets, the list is empty, even when there are several dozen pending or undeployed assets. All assets are listed under the List All option as they should be and Un-Deployable appears to be working as well. 

Have you seen this before? Do you have any idea what I can do to troubleshoot this?

Thanks in advance for your assistance

**Comment by snipe** [comment]
Hi @Ramchak - do you have the same problem with the latest development branch? (Sorry for the delay, I somehow missed this issue report)

**Comment by snipe** [comment]
The upcoming 1.2.4 release should solve this issue for you.
