### ISSUE TITLE
New Installation - "Invalid default value..."

### ISSUE THREAD

**Issue by rwwest7** [snipe/snipe-it#4102]
#### Expected Behavior (or desired behavior if a feature request)

Install to succeed.

-----

#### Actual Behavior

Fails with SQL error.

-----

#### Please confirm you have done the following before posting your bug report:

- [Y ] I have enabled debug mode 
- [Y ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Yes
- Version of Snipe-IT you're running
Latest
- Version of PHP you're running
7.1.10
- Version of MySQL/MariaDB you're running
15.1
- What OS and web server you're running Snipe-IT on
Ubuntu 14 / Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Can't get to browser page, white page (error 500)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
N/A
- If a stacktrace is provided in the error, include that too.
N/A
- Any errors that appear in your browser's error console.
Nothing
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
N/A
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
Nothing, doesn't make it that far
- Include what you've done so far in the installation, and if you got any error messages along the way.
Tried Ubuntu 16. Tried many different MySQL version.
- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

I'm trying to do a fresh, clean install on a fresh install of Linux. Followed directions EXACTLY on Debian, tried several times with no luck. Found the Install.sh method and tried it on a fresh Ubuntu install, no luck there either.

I have it narrowed down to an SQL issue. It wants to create "en-US.utf8" as the default value for locale in a new table, but MySQL is refusing...so it gives up and stops. 

This is the command that fails: "alter table `users` add `local
  e` varchar(5) null default 'en_US.UTF-8'" 

If I alter the command and run it manually against the DB it works as this: "alter table `users` add `local
  e` varchar(5) null default 'UTF-8' "

But then the installer / migrate fails saying the table already exists. I'm in  a catch 22.

Strict mode is off.

**Comment by rwwest7** [comment]
So the installer is trying to run  "alter table users add local e varchar(5) null default 'en_US.UTF-8'"

The key is "varchar(5)" and "en_US.UTF-8"....

It's trying to stuff 11 characters in a field it's creating to only support 5 characters.

**Comment by rwwest7** [comment]
Had been trying Ubuntu, thought maybe that was an issue. 

Loaded up a fresh CentOS 6 VM, exact same error. Something is definitely wrong with the installation script.

**Comment by rwwest7** [comment]
Semi-success. I edited three files in database/migrations and can now get to web interface!

Replaced varchar(5) with varchar(12) in the three "locale" files and the install actually finished.

**Comment by snipe** [comment]
Never edit migration files. 

We normally see that error when users skip the part where they add `APP_LOCALE=en` to the env file before running migrations.

**Comment by rwwest7** [comment]
I'm only running the migrate because the install.sh always fails to create the database. I didn't "skip" anything, had to troubleshoot the installation process.

**Comment by cagcak** [comment]
If you edit the default value `APP_LOCALE=en` as something else, like `APP_LOCALE=tr`, you probably see the error. Like @snipe  said, don't edit the `APP_LOCALE` before.

**Comment by rwwest7** [comment]
The problem turned out to be the install.sh script wasn't creating the .env file properly. It didn't even have APP_LOCALE in it. Only had a few basic settings, like DB stuff.

It must've been fixed though, running it a few days later and it worked properly.
