### ISSUE TITLE
Unable to create user

### ISSUE THREAD

**Issue by tomasaberg** [snipe/snipe-it#4104]
#### Expected Behavior (or desired behavior if a feature request)

Go to People => Create New and fill in required fields. 
First Name, Username and Password (tried both generated and set a simple password)

-----

#### Actual Behavior
 
I get a error stating Error: Please check the form below for errors

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
This is a fresh install. Running as a service in Docker Swarm.

- Version of Snipe-IT you're running
v4.0.6 build 47 (g2e76620)

- Version of PHP you're running
7.0.22-0ubuntu0.16.04.1

- Version of MySQL/MariaDB you're running
MySQL 5.6

- What OS and web server you're running Snipe-IT on
Ubuntu 16.04

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Docker Swarm

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
/users/create. When clicking Save I get directed to Dashboard.

- If a stacktrace is provided in the error, include that too.
N/A

- Any errors that appear in your browser's error console.
N/A

- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
Not able to reproduce.

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
Attached
[laravel.log](https://github.com/snipe/snipe-it/files/1348721/laravel.log)
[docker-compose.yml.txt](https://github.com/snipe/snipe-it/files/1348724/docker-compose.yml.txt)
[snipeit.env.txt](https://github.com/snipe/snipe-it/files/1348727/snipeit.env.txt)

- Include what you've done so far in the installation, and if you got any error messages along the way.

1. Run docker `stack deploy -c docker-compose.yml snipeit`
2. Somehow the application won't start unless I enter the container and run `php artisan migrate` 

- Indicate whether or not you've manually edited any data directly in the database
No, unless step 2 above counts.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by tomasaberg** [comment]
I did som further digging. First of all I enabled the 2FA 

I was then able to create a user A with the password `changeme2plz`.
However, I wasn't able to create user B with the same exact same password. 
User B was successfully created if I set the password to `changeme2plz!` 

I could then create a third user C with the password `changeme2plz!`

**Comment by snipe** [comment]
Can you clear out your log and try again? There's too much in there, I can't see what's directly related to this issue.

**Comment by snipe** [comment]
(Also please just paste the app log here, so we don't have to download files.)

**Comment by snipe** [comment]
Do you have password policy enforcement turned on in Settings?

**Comment by tomasaberg** [comment]
I cleared out laravel.log (echo "" > laravel.log) and tried to create a new user with the password "changeme". It failed but with no error output other than 
*Error: Please check the form below for errors.*

**Facepalm!** 
You pointed me in the right direction. The password must contain 10 characters. 
What was confusing for me was that I was able to create the first user. 

**Sugestion**
- Since 10 characters is set as default, this should also enforce the initial user.
- I think that the logging and error output might need some love <3

Thank you for your help!
