### ISSUE TITLE
Question about Upgrade from V4.04 to V4.06

### ISSUE THREAD

**Issue by JExactly** [snipe/snipe-it#4109]
Are there any procedures/commands that need to be run after a pull to the new version with V4+?
or is this only with the prior V3+?

Thank you

**Comment by ellisgeek** [comment]
You should give the Upgrade guide a read.
https://snipe-it.readme.io/docs/upgrading-to-v4

**Comment by JExactly** [comment]
@ellisgeek I did, I just wanted to confirm what commands needed to be run since the upgrade guide is wrtten for upgrade from V3 > V4. I was looking for a straightforward "these are the things you must do" i saw that they were somewhat mixed into the upgrade guide. Just wanted to confirm I didn't miss/break my install again. I followed old procedures and upgraded. Thanks for the reply
Thanks.
