### ISSUE TITLE
Unable to recrypt fields after upgrading

### ISSUE THREAD

**Issue by ellisgeek** [snipe/snipe-it#4110]
#### Expected Behavior (or desired behavior if a feature request)

Recrypting of an encrypted field should succeed with no issues.

-----

#### Actual Behavior

Recrypting  the field results in the following error:

    INFO: No LDAP password found. Skipping...
    INFO: Retrieving encrypted custom fields...
    FIELD TO RECRYPT:  Management - Password (_snipeit_management_password_11)
     172/172 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
    
    
    The decrypter encountered some errors:
    
     - ERROR: Could not decrypt field [Management - Password]: The payload is invalid.

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **`Upgrade`**
- Version of Snipe-IT you're running **`4.0.6`**
- Version of PHP you're running **`7.0.22`**
- Version of MySQL/MariaDB you're running **`10.0.33`**
- What OS and web server you're running Snipe-IT on **`Ubuntu 16.04 and Nginx 1.10.3`**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **`Manual Install`**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error `sudo -u www-data php artisan snipeit:legacy-recrypt`
- If a stacktrace is provided in the error, include that too. `None`
- Any errors that appear in your browser's error console. `N/A`
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. `N/A`
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. Nothing in `storage/logs' or `/var/log/php7.0-fpm.log`
- Include what you've done so far in the installation, and if you got any error messages along the way. 
    - Backed up Database and old install
    - Entered Maintenance Mode
    - Cleared Caches by Deleting Files and using artisan
    - pulled the new version via Git
    - Installed BCMath and updated Deps. with Composer.
    - Copied old `.env` file from 3x (**Would this break things?**)
    - Migrated Database with `artisan migrate`
    - Added `LEGACY_APP_KEY=base64:xxxx=` to `.env`
    - Generated new App Key using `artisan key:generate`
    - Cleared config cache with `artisan config:clear`

- Indicate whether or not you've manually edited any data directly in the database `No`

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
> Copied old .env file from 3x (Would this break things?)

No, as long as you changed the APP_KEY in your v3 env to LEGACY_APP_KEY and generated a new app key.

**Comment by stillru** [comment]
Same to me but without eny errors.
try to `sudo -u www-data php artisan snipeit:ldap-disable` getting `Unable to disable LDAP`
