### ISSUE TITLE
label sizes with comma instead of dot

### ISSUE THREAD

**Issue by PascalOuimet** [snipe/snipe-it#4112]
#### Expected Behavior (or desired behavior if a feature request)

The label size should contain a dot for the css width and length.
The size is not right for this reason.

-----

#### Actual Behavior

The label size should contain a comma instead.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? : upgrade
- Version of Snipe-IT you're running : 4.06
- Version of PHP you're running : 5.6.16
- Version of MySQL/MariaDB you're running : 5.7
- What OS and web server you're running Snipe-IT on : Windows server 2012 R2 / IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) : Manual install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error : none
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error : hardware/bulkedit when a label is generated
- If a stacktrace is provided in the error, include that too. : none
- Any errors that appear in your browser's error console. : none
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. : no
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. : it's a french server. I think it's the reason.
- Include what you've done so far in the installation, and if you got any error messages along the way. : no
- Indicate whether or not you've manually edited any data directly in the database : no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Not sure what you mean

**Comment by PascalOuimet** [comment]
This is what I get :
![capture](https://user-images.githubusercontent.com/6087772/31126057-86cfa55a-a818-11e7-94a9-b09857e90f6f.PNG)

**Comment by snipe** [comment]
Perhaps that's a localization issue? In the US, we use periods to denote decimals....

**Comment by PascalOuimet** [comment]
Yes in FR-CA, the comma is used
