### ISSUE TITLE
Issue with advanced search (experimental)

### ISSUE THREAD

**Issue by JExactly** [snipe/snipe-it#4115]
Expected Behavior (or desired behavior if a feature request)

Search to return results for typed name in additional search fields or in the quick search box

Actual Behavior

**Note: I understand the feature is experimental; It's just one I was waiting for and excited about**

If you type a partial name For example: First name only, results are returned, if you type last name only results are returned. if you type first name and last name together, no results are returned. This seems to only be certain users and I haven't identified the common denominator yet. Additionally, it appears the more items I add to the search with values, the less likely it returns results if any. I have had some full names searched for and work properly in the advanced search "Checked Out to" field. Other names of assets I know are checked out to a person return no results when using the same field and their name.

Please confirm you have done the following before posting your bug report:

 I have enabled debug mode
[X ] I have read checked the Common Issues page
Please provide answers to these questions before posting your bug report:

Version of Snipe-IT you're running  v4.0.6 build 47
What OS and web server you're running Snipe-IT on Ubuntu 16.04
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual
WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: ALL Assets page
If a stacktrace is provided in the error, include that too. None
Any errors that appear in your browser's error console. None
Confirm whether the error is reproducible on the demo.
Include any additional information you can find in app/storage/logs and your webserver's logs.
Include what you've done so far in the installation, and if you got any error messages along the way.
Indicate whether or not you've manually edited any data directly in the database. None

**Comment by snipe** [comment]
>  if you type first name and last name together, no results are returned

That's to be expected though, as it's searching on first_name and last_name. There isn't a notion of full name in the database.

> Additionally, it appears the more items I add to the search with values, the less likely it returns results if any

That's also to be expected - you're narrowing down when you use additional constraints.

**Comment by JExactly** [comment]
So maybe I am misunderstanding the Checked out to field and what should be typed in here. It displays as the full users name. But when I search for the first name lastname in the field nothing is returned. When I use the active directory username no results from the check out to search box. 

Can someone clarify what the fields are for if the content I am searching for should be a value but nothing is returned? I am sure it is something I am doing on my end. But, I need clarity

![image](https://user-images.githubusercontent.com/14076881/33131590-027776ce-cf65-11e7-8869-9b94f56bd0ec.png)

![image](https://user-images.githubusercontent.com/14076881/33131651-42705958-cf65-11e7-9e22-50647f899fb2.png)
