### ISSUE TITLE
License Import - Only last item imported

### ISSUE THREAD

**Issue by Tommoh** [snipe/snipe-it#4120]
#### Expected Behavior (or desired behavior if a feature request)

Import licenses through the UI, I have around 100 Office licenses that I import. Each product key has a single seat and I expect each item to be added to the database and listed in the license section. Each license is invididual so only 1 seat per license is added.

The item names are all the same and only difference is the product/serial key.

I only import the following fields:

- Item name (not unique)
- Serial number (unique)
- Manufacturer (not unique)
- Maintained 
- Reassignable

-----

#### Actual Behavior

Once I import, only a single instance of the license is being imported. It appears only the last item from the CSV is added. When adding the licenses manually, with the same item name but unique product key, the item gets added and shown in the list.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh Install

- Version of Snipe-IT you're running
V4.0.4

- Version of PHP you're running
V7

- Version of MySQL/MariaDB you're running
10.1.26-MariaDB-0+deb9u1

- What OS and web server you're running Snipe-IT on
Debian 9

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual Install

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No errors. Import proceeds.

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Import license using the UI import tool, selecting License as import.

- Include what you've done so far in the installation, and if you got any error messages along the way.
Added license with the same name but different product key. This showed up a second license with no issues.

- Indicate whether or not you've manually edited any data directly in the database
No

**Comment by snipe** [comment]
@dmeltzer any thoughts?

**Comment by dmeltzer** [comment]
Yeah, looks like we are using the name as a unique key... Will look.
