### ISSUE TITLE
Give permission to admin user for show asset by category on dashboard

### ISSUE THREAD

**Issue by pratosh448** [snipe/snipe-it#4126]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

admin user can't view asset by category 

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
> admin user can't view asset by category

What does this mean? What are you actually seeing?

**Comment by pratosh448** [comment]
Only super admin can view asset category on dashboard but not admin

**Comment by snipe** [comment]
**What are you actually seeing?**

What does it physically look like. PLEASE be more specific. Include screenshots if you have to.

**Comment by pratosh448** [comment]
This user is with admin privileges but this category is empty
![img_20171004_020209](https://user-images.githubusercontent.com/31343768/31147679-3e59e4da-a8a8-11e7-9081-0de3389e4337.png)

**Comment by snipe** [comment]
Thank you for the screenshot. We're more or less phasing out the admin role, since we have much more granular permissions for users now. Not sure what the "admin" dashboard will look like, but it's unlikely that role will have much meaning moving forward.
