### ISSUE TITLE
Debug mode enabled, but debug log(s) not filling with data

### ISSUE THREAD

**Issue by nevaus** [snipe/snipe-it#4129]
#### Expected Behavior (or desired behavior if a feature request)

Having problems with getting LDAP/AD to work, so trying to enable debugging. Have enabled debugging, and the web UI even reports that debug mode is enabled (ie with red "debug is enabled" warning). Log(s) should now be filling up with debug data.

-----

#### Actual Behavior

No logs under storage\logs\ folder (or anywhere else on the file system) are having any new logging written to them. The last time data was written to laravel.log was 2 days ago when SnipeIT was installed. There are no other files in that folder, except for ".gitignore".
(Have tried restarting services, as well as rebooting the server without any change in behaviour).

-----

#### Please confirm you have done the following before posting your bug report:

- [YES] I have enabled debug mode 
- [YES] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  : FRESH
- Version of Snipe-IT you're running  : v4.0.6 build 47 
- Version of PHP you're running  : 7.0.23
- Version of MySQL/MariaDB you're running  : 10.2.8
- What OS and web server you're running Snipe-IT on  : Windows Server 2012 R2 ; WAMP64
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)  : manual installation as per https://github.com/snipe/snipe-it/issues/2530 , but used Wamp64 (instead of Wamp32)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error  : wanting to debug LDAP, but no debug logging data being generated
- Indicate whether or not you've manually edited any data directly in the database   : No, have not

**Comment by snipe** [comment]
Check the permissions on your storage directory. That directory and all subdirectories should be writable by the web server. Also check your server and PHP logs to see if that provides any additional insight, for example permissions errors.

**Comment by nevaus** [comment]
hi snipe, thanks for your response.
I have given the "Everyone" group Modify access to the C:\wamp64\www\snipe-it\storage\logs\ folder. This gets inherited down to all files and subfolders. Has not helped.
Neither php_error.log nor apache_error.log have anything useful in them.
I ran procmon against the server to see any permission issues.
- the Apache process (httpd.exe) has attempted (successfully) to read the C:\wamp64\www\snipe-it\storage\logs\laravel.log file, but at no time does it attempt to write to it.
- httpd.exe tries to see if the file C:\wamp64\www\snipe-it\storage\logs\laravel-2017-10-04.log exists.
- httpd.exe has no access denied to any files

**Comment by nevaus** [comment]
Hello, I am happy to close this issue, and try again from scratch with 32-bit WAMP or Linux instead. However I am also happy to keep diagnosing this one if a resolution would help others. Should I persist with this, or close it? (PS is there an already set up Snipe IT linux virtual appliance by any chance, that one could simply add to the existing VMware insfrastructure?) Cheers.

**Comment by nevaus** [comment]
Well I instead installed the 32-bit version of WAMP, and having the exact same problem. Have also tried setting the wampapache system service so that it runs under the context of an administrator login. Still no good. I'm quite sure it isn't a permissions issue.

**Comment by snipe** [comment]
Try pulling the latest from master and see if that resolves your issue.

Alsol in your .env, make sure the following settings are set:

```
APP_ENV=develop
APP_DEBUG=true
APP_LOG_LEVEL=info
```

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
