### ISSUE TITLE
"All Assets" page is blank

### ISSUE THREAD

**Issue by app-reroute** [snipe/snipe-it#4131]
#### Expected Behavior (or desired behavior if a feature request)

In the menu, go to "List All" under the "Assets" menu and see all assets.

-----

#### Actual Behavior

No assets are listing. Instead "No matching records found" is displayed. The search box is empty.

If I place my cursor in the empty search box and press the Enter key, then all assets are shown.

This is using the latest version of Chrome. It works fine in an Incognito window, and it works fine on Chrome on another computer (using Chrome's sync tool to sync my settings/extensions, but not cookies/cache obviously).

This leads me to believe that something set in my cookies or in my session is causing this issue.

#### More info:

Comparing requests in my normal browser window (broken) vs. the Incognito window (works), there is a discrepancy that may help troubleshoot this.

The normal (broken) browser window makes a call to `/api/v1/hardware?status=&order_number=&company_id=&status_id=&order=asc&limit=200&offset=200` and this is returned:

    {"total":171,"rows":[]}

Note the lack of data in the rows and that the offset is 200.

The Incognito window makes a call to `/api/v1/hardware?status=&order_number=&company_id=&status_id=&order=asc&limit=20&offset=0` and this is returned:

    {"total":171,"rows":[(actual data here)]}

So I'm not sure what steps got me to the point of, by default, having it try to pull records that don't exist.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
This is an upgrade from the original release of 4.0.
- Version of Snipe-IT you're running
4.0.8 build 102
- Version of PHP you're running
7.0.22
- Version of MySQL/MariaDB you're running
MySQL 5.7.19
- What OS and web server you're running Snipe-IT on
Ubuntu Server 16.04 and Apache 2.4.18
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation, clone from git
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No error in the browser.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
This is on Assets >> List All. The route is /hardware.
- If a stacktrace is provided in the error, include that too.
There is no stack trace
- Any errors that appear in your browser's error console.
No errors appear in the browsers error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
No, it is not reproduceable on the demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
There are no errors in the logs (in fact, using `tail` to follow the logs as I reproduce the bug shows that nothing is being written to the logs during this)
- Include what you've done so far in the installation, and if you got any error messages along the way.
Successful installation with no errors.
- Indicate whether or not you've manually edited any data directly in the database
I have not modified any data in the database directly.

**Comment by snipe** [comment]
Does clearing your browser cookies help?

**Comment by furby** [comment]
I am getting the same thing, the All Assets is blank

Provide answers to these questions:

Is this a fresh install or an upgrade?
This is an upgrade from 3.6.6
Version of Snipe-IT you're running
v4.0.9 build 120 (gf66e222)
Version of PHP you're running
7.0.22-0ubuntu0.16.04.1
Version of MySQL/MariaDB you're running
MySQL 5.6
What OS and web server you're running Snipe-IT on
MacOS
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Docker
WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No error in the browser.
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
This is on Assets >> List All. The route is /hardware.
If a stacktrace is provided in the error, include that too.
There is no stack trace
Any errors that appear in your browser's error console.
No errors appear in the browsers error console.
Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
No, it is not reproduceable on the demo.
Include any additional information you can find in app/storage/logs and your webserver's logs.


Include what you've done so far in the installation, and if you got any error messages along the way.
Successful installation with no errors.
Indicate whether or not you've manually edited any data directly in the database
I have not modified any data in the database directly.

Not related but my People page is also empty of users and when I go to create new

"SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.departments' doesn't exist (SQL: select `name`, `id` from `departments` where `deleted_at` is null order by `name` asc, `name` asc)"

is the error message

**Comment by furby** [comment]
You know what, I must have missed something. I ran the upgrade process again and it's all working :)

https://snipe-it.readme.io/docs/upgrading-to-v4

**Comment by app-reroute** [comment]
I upgraded to 4.0.9 this morning, and am no longer having this issue.

**Comment by talenmhm** [comment]
Hi Guys,
I have same the issue, 
SnipeIT v4
Yesterday I imported assets to SnipeIT and it was working, 
then today is not working and showing in All Assets page s blank:
" No matching records found "
Even though, dashboard is showing the total asset is 10,

Please advise
Thanks

**Comment by snipe** [comment]
@talenmhm - Hi there - this issue is closed. Please create a new issue and fill in all of the questions in the new issue form. (When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.)
