### ISSUE TITLE
Create Model asset error Integrity constraint violation by deprecation_id

### ISSUE THREAD

**Issue by nbattista89** [snipe/snipe-it#4136]
Hello,
When i create an asset model without to specify a Depreciation (default value Do not Depreciate), the creation model failed because there is an Integrity constraint violation:
SQLSTATE[23000]: : 1048 Column 'depreciation_id' cannot be null (SQL: insert into `models` (`eol`, `depreciation_id`, `name`, `model_number`, `manufacturer_id`, `category_id`, `notes`, `user_id`, `requestable`, `updated_at`, `created_at`) values (0, , rtrytr, , 17, 41, , 1325, 0, 2017-10-04 10:04:41, 2017-10-04 10:04:41))  
- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? upgrade
- Version of Snipe-IT you're running : 4.0.9
- Version of PHP you're running : 7.0.9
- Version of MySQL/MariaDB you're running : 10.1.26
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) : install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error : Yes
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by nbattista89** [comment]
[laravel.log](https://github.com/snipe/snipe-it/files/1355214/laravel.log)
I've uploaded the log file.

**Comment by nbattista89** [comment]
Hi,
Any news?

**Comment by jimmysnee** [comment]
I have experienced the same issue.  First time adding a model since upgrade from 3.6.2 to 4.0.x. I got a SQL integrity constraint violation saying "depreciation_id cannot be null". I had selected the default option for 'Do Not Depreciate' when I recieved that error. I tried changing the manufacturer, category, and fieldset and got the same result. However, if I select any other value for depreciation, it allows me to create the model successfully.  Interestingly, I have five options in the dropdown for the depreciation field, but in the actual SQL table, I have only four records...none of which are "Do Not Depreciate"

**Comment by jimmysnee** [comment]
The models.depreciation_id is marked to prohibit a NULL value.

**Comment by nbattista89** [comment]
I think there are two possible solution : 
1: Disable constraint (not recommended)
2: Add row in the table deprecation :+1: 
Example insert on the deprecations table : 
insert into depreciations (0,'Do Not Depreciate',0,'0000-00-00 00:00:00','0000-00-00 00:00:00',1)
And modify the code for to write 0  instead null when we created a model.
Thanks,
Regards.
Nicola Battista

**Comment by snipe** [comment]
@nbattista89 disabling the null constraint is the better idea here. Otherwise you have to provide  business logic for 0-id that isn't the same as a real id. Bad practice, IMHO.

Are either/both of you in strict mode? It should not be preventing nullable here.

**Comment by snipe** [comment]
This was built as nullable. See the migration to create the field, in database/migrations/2013_11_16_042851_add_depreciation_id_to_models.php.

```
 Schema::table('models', function ($table) {
     $table->integer('depreciation_id')->nullable();
});
```

I think only in mysql strict mode should it fail because it wasn't specified as `default->(null)` in addition to the field being nullable.
