### ISSUE TITLE
Asset, Department, Locaton list did not show after creating new information

### ISSUE THREAD

**Issue by thanhnhankmt** [snipe/snipe-it#4137]
#### Expected Behavior (or desired behavior if a feature request)

All asset, Department, Localtion list need to be showed after creating new information

-----

#### Actual Behavior

All lists showed after creating new information

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Fresh Install** 
- Version of Snipe-IT you're running: **v4.0.7 build 89 (g7a27fda)**
- Version of PHP you're running: **7.1.9**
- Version of MySQL/MariaDB you're running: 5.4.36
- What OS and web server you're running Snipe-IT on: **CentOS release 6.9 (Final)**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): **by install.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: No errot
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: 
   **+ **Settings -> Assets, Departments, Locations page - Just view page and expect to see those lists****
![snipe-it](https://user-images.githubusercontent.com/25977973/31169880-547fd400-a924-11e7-8026-5cad60b727bb.PNG)

   **+ When i try to clisk on some buttons like: Menu (with 3 lines on upper left corner) or Account Setting button -> No any actions are occured**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. - **No**, just information like 
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by furby** [comment]
You know what, I must have missed something. I ran the upgrade process again and it's all working :)

https://snipe-it.readme.io/docs/upgrading-to-v4

**Comment by thanhnhankmt** [comment]
I just guest problem originate from JS browsers but when i try to access your demo site, everything is showed all. So problem must not from JS browsers.
Please help to check issue. Thanks your great team so much

**Comment by snipe** [comment]
> I just guess problem originate from JS browsers

I don't know what this means.

> Any errors that appear in your browser's error console. - No, just information like

I don't know what this means either.

Try upgrading to the latest version (or pull from master) and let me know if that resolves your issues.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
