### ISSUE TITLE
Checkout Redirect is not working

### ISSUE THREAD

**Issue by GAD0815** [snipe/snipe-it#4138]
Hi there,

i´m experiencing the issue stated below since the upgrade to v4.
In addition to that, i am not able to search the users with the build in search. Yes, I have a Database Prefix configured. Is there a way to make it work?

Thank you very much in advance and for the great work on this product!

#### Expected Behavior

After asset checkout, a redirect to the hardware page should occur.

-----

#### Actual Behavior

After asset checkout, a Whoops, looks like something went wrong page is displayed (url/hardware/886/checkout)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - Upgrade from 4.0.6, initially from 3.6.6
- Version of Snipe-IT you're running - v4.0.9 build 120 (gf66e222)
- Version of PHP you're running - 7.1.7
- Version of MySQL/MariaDB you're running - Maria DB 10.0.14
- What OS and web server you're running Snipe-IT on - Windows Server 2016, IIS 10
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - yes, see attachment
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - all deloyable assets page -> checkout to user
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. - not on this page, i get an internal server error on the dashboard: GET https://uri/api/v1/reports/activity?limit=25&order=desc 500 (Internal Server Error)
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. - No, the demo works fine
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. - see attachment
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - no db editing

[Checkout_Error.pdf](https://github.com/snipe/snipe-it/files/1355419/Checkout_Error.pdf)
[laravel.log](https://github.com/snipe/snipe-it/files/1355421/laravel.log)

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Can you try pulling from the latest and see if that resolves your checkout issue? 

There is a known issue with DB prefixes at this time. We're working on it, but there are a lot of places to change it. :(

**Comment by GAD0815** [comment]
Pulling from the latest worked, thank you vm!
