### ISSUE TITLE
Error in New installation v4.0.9 

### ISSUE THREAD

**Issue by itims** [snipe/snipe-it#4140]
Hi,
I'm trying to install v4.0.9 (Fresh installation) in ubuntu 14.04 server, I got an error like this. Please have a look on this issue. How to resolve this issue? Could you please help me?

![image](https://user-images.githubusercontent.com/23715217/31172742-6685de4e-a922-11e7-90bd-6c3d09ef8cfa.png)

PHP Version
![image](https://user-images.githubusercontent.com/23715217/31172799-a36204fa-a922-11e7-8020-84ca3b88e83a.png)
Apache Version
![image](https://user-images.githubusercontent.com/23715217/31172825-be8c5a96-a922-11e7-9bfe-f5a340918790.png)
The following php modules are enabled in ubuntu 14.4
admin@ams:/$ php -m
[PHP Modules]
calendar
Core
ctype
curl
date
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
Zend OPcache
zip
zlib

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - **Fresh install**
- Version of Snipe-IT you're running - **4.0.9**
- Version of PHP you're running - **7.0.24**
- Version of MySQL/MariaDB you're running - **5.6**
- What OS and web server you're running Snipe-IT on - **Ubuntu Server 14.04**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - **snipeit.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by itims** [comment]
Apache error log file
![image](https://user-images.githubusercontent.com/23715217/31173937-2d39dc3a-a927-11e7-9d70-4683e58ab97d.png)

**Comment by tiagom62** [comment]
Curious how you have php7.0 as master installs php5 and my changes in PR #4133  installs php7.1.

Can you try the install in PR #4133? https://github.com/tiagom62/snipe-it/blob/02dfc5320db4e352431e829b0e5af7a128c65799/snipeit.sh

**Comment by itims** [comment]
Hi Team,
I just reinstalled new version [Version v4.0.9 build 120 (gf66e222)] of application in Ubuntu server 14.04. Now it's working good. But I had faced some issues when I restored MySQL database backup of the old version (3.6.3).

My issues listed below -

1. I'm not able to view all assets and cannot create a new asset. But I can see all accessories, consumables and components. Even I can create a new item under these categories.

Dashboard shows 706 total assets
![image](https://user-images.githubusercontent.com/23715217/31266278-a39e3c6c-aa90-11e7-83a7-31c6fe999b37.png)

2. I'm not able to view users list and cannot create a new user.
 
Could you please help me to resolve this issues?

**Comment by itims** [comment]
![image](https://user-images.githubusercontent.com/23715217/31266585-19e20a56-aa92-11e7-8dbb-ce20310b1515.png)
![image](https://user-images.githubusercontent.com/23715217/31266598-27162c8e-aa92-11e7-8516-850f85ffe5a5.png)

**Comment by tiagom62** [comment]
Did you run migrations? https://snipe-it.readme.io/v4.0/docs/upgrading-to-v4

**Comment by snipe** [comment]
Also please provide logs, as mentioned int he getting help documentation.

**Comment by itims** [comment]
I just executed "php artisan migrate" after I restored mysql db. But I got an error like this
![image](https://user-images.githubusercontent.com/23715217/31315352-a936a1a0-ac34-11e7-8628-aa924f755fe2.png)

**Comment by itims** [comment]
Dear Team,
How to fix this issue? 
Could you please suggest me a solution?
:-)

**Comment by snipe** [comment]
Try running this in mysql directly.

```
INSERT INTO `migrations` (`migration`, `batch`) VALUES ('2016_06_01_000001_create_oauth_auth_codes_table', 1), ('2016_06_01_000002_create_oauth_access_tokens_table', 1),
('2016_06_01_000003_create_oauth_refresh_tokens_table', 1),
('2016_06_01_000004_create_oauth_clients_table', 1),
('2016_06_01_000005_create_oauth_personal_access_clients_table', 1);
```

**Comment by itims** [comment]
I did it, but now i got an error like this
![image](https://user-images.githubusercontent.com/23715217/31503680-ef0c8aa8-af8d-11e7-8f55-c7e1ac840c4e.png)

**Comment by snipe** [comment]
Not sure how your migrations managed to get messed up. You might try dropping your database tables and running migrations again.

**Comment by snipe** [comment]
Haven't heard back, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
