### ISSUE TITLE
How to minor-update Snipe-IT

### ISSUE THREAD

**Issue by passboltUser** [snipe/snipe-it#4141]
Hello,
I have installed Snipe-IT through `git clone https://github.com/snipe/snipe-it snipe-it`. How would I update it when you release a new minor version? Say I have 4.0.9 now and you release 4.0.10.

**Comment by TheULi** [comment]
Go to the snipt-it directory and use the git pull command. this updates your code to the newest of the master branch

**Comment by tbradsha** [comment]
You might also reference this page:

https://snipe-it.readme.io/docs/upgrading

**Comment by raakhtar** [comment]
These steps are valid when github clone snipe-it repo has used. The best and recommended approach as updates appears to be brief with this. Estimated Time ~1 Minute

> git pull
> php composer.phar install --no-dev --prefer-source
> php composer.phar dump-autoload
> php artisan migrate
> php artisan config:clear
> php artisan config:cache
> php artisan cache:clear
> php artisan view:clear
> php artisan route:clear

Clear browser cache (optional) but good to do.

**Comment by passboltUser** [comment]
Thanks everyone :)
