### ISSUE TITLE
Javascript error creating/editing licenses

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#4150]
A user (@raphandowski) shared this screenshot in Gitter.

![blob](https://user-images.githubusercontent.com/197404/31213813-3b3a50ea-a95d-11e7-873c-cb069a43d53a.png)

I'm getting a diff error in safari  (v4.0.9).

<img width="819" alt="screen shot 2017-10-04 at 11 38 36 pm" src="https://user-images.githubusercontent.com/197404/31213831-4e00b75a-a95d-11e7-8bfe-42c6515aaed0.png">

Can you take a peek, @uberbrady?

**Comment by dmeltzer** [comment]
The first one is related to subdirectory support.  Probably needs to use the route() bits (or our own TBD solution.)

**Comment by snipe** [comment]
*pokes @uberbrady *
