### ISSUE TITLE
cli LDAP import

### ISSUE THREAD

**Issue by stillru** [snipe/snipe-it#4151]
#### Expected Behavior (or desired behavior if a feature request)

Importing users from AD

-----

#### Actual Behavior

```
 php artisan snipeit:ldap-sync --summary -vvv


  [ErrorException]
  Undefined index: samaccountname

Exception trace:
 () at /var/www/html/snipeit/app/Console/Commands/LdapSync.php:112
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at /var/www/html/snipeit/app/Console/Commands/LdapSync.php:112
 App\Console\Commands\LdapSync->handle() at n/a:n/a
 call_user_func_array() at /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php:539
 Illuminate\Container\Container->call() at /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php:182
 Illuminate\Console\Command->execute() at /var/www/html/snipeit/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php:167
 Illuminate\Console\Command->run() at /var/www/html/snipeit/vendor/symfony/console/Application.php:888
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/snipeit/vendor/symfony/console/Application.php:224
 Symfony\Component\Console\Application->doRun() at /var/www/html/snipeit/vendor/symfony/console/Application.php:125
 Symfony\Component\Console\Application->run() at /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122
 Illuminate\Foundation\Console\Kernel->handle() at /var/www/html/snipeit/artisan:35
```

-----

#### Please confirm you have done the following before posting your bug report:

- [ * ] I have enabled debug mode 
- [ * ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade - **Upgrade** 
- Version of Snipe-IT you're running - **4.0.9**
- Version of PHP you're running - **PHP 7.0.22-0ubuntu0.16.04.1 (cli)**
- Version of MySQL/MariaDB you're running - **Ver 15.1 Distrib 10.0.31-MariaDB, for debian-linux-gnu (x86_64)**
- What OS and web server you're running Snipe-IT on - **Ubuntu 16.04.3 LTS with nginx/1.10.3 (Ubuntu)**
- What method you used to install Snipe-IT (install.sh, **manual installation 3.6.6 with upgrade to 4.0.6 and automatic upgrade to 4.0.9 thru php script**, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - **500 error with LDAP sync**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - **Trying sync LDAP users**
- If a stacktrace is provided in the error, include that too. - **Above**
- Any errors that appear in your browser's error console. **Same behavior as #4110 #4030 , "Update LDAP/AD Settings" fails with a red triangle. Chrome debug console shows "GET http://snipeit/api/v1/settings/ldaptest 401 (Unauthorized)" #4023  
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by stillru** [comment]
may be useful    Adldap2-Laravel#387

**Comment by snipe** [comment]
If you pull from the latest, are you still having this issue?

**Comment by stillru** [comment]
Updated today.
```

 php artisan snipeit:ldap-sync --summary -vvv


  [ErrorException]
  Undefined index: samaccountname


Exception trace:
 () at /var/www/html/snipe-it-v4/app/Console/Commands/LdapSync.php:115
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at /var/www/html/snipe-it-v4/app/Console/Commands/LdapSync.php:115
 App\Console\Commands\LdapSync->handle() at n/a:n/a
 call_user_func_array() at /var/www/html/snipe-it-v4/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /var/www/html/snipe-it-v4/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /var/www/html/snipe-it-v4/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /var/www/html/snipe-it-v4/vendor/laravel/framework/src/Illuminate/Container/Container.php:539
 Illuminate\Container\Container->call() at /var/www/html/snipe-it-v4/vendor/laravel/framework/src/Illuminate/Console/Command.php:182
 Illuminate\Console\Command->execute() at /var/www/html/snipe-it-v4/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at /var/www/html/snipe-it-v4/vendor/laravel/framework/src/Illuminate/Console/Command.php:167
 Illuminate\Console\Command->run() at /var/www/html/snipe-it-v4/vendor/symfony/console/Application.php:888
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/snipe-it-v4/vendor/symfony/console/Application.php:224
 Symfony\Component\Console\Application->doRun() at /var/www/html/snipe-it-v4/vendor/symfony/console/Application.php:125
 Symfony\Component\Console\Application->run() at /var/www/html/snipe-it-v4/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122
 Illuminate\Foundation\Console\Kernel->handle() at /var/www/html/snipe-it-v4/artisan:35
```

**Comment by stillru** [comment]
Version **v4.0.13 build 323 (gc1f8db3)**

**Comment by grimstoner** [comment]
Experiencing the same issue. 

Running v4.1.3 build 94 (gb6a14d2)

When running the command @stillru uses (`php artisan snipeit:ldap-sync --summary -vvv`):

`  [ErrorException]
  Undefined index: sAMAccountName


Exception trace:
 () at /var/www/html/snipeit/app/Console/Commands/LdapSync.php:115
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at /var/www/html/snipeit/app/Console/Commands/LdapSync.php:115
 App\Console\Commands\LdapSync->handle() at n/a:n/a
 call_user_func_array() at /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php:539
 Illuminate\Container\Container->call() at /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php:182
 Illuminate\Console\Command->execute() at /var/www/html/snipeit/vendor/symfony/console/Command/Command.php:262
 Symfony\Component\Console\Command\Command->run() at /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php:167
 Illuminate\Console\Command->run() at /var/www/html/snipeit/vendor/symfony/console/Application.php:888
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/snipeit/vendor/symfony/console/Application.php:224
 Symfony\Component\Console\Application->doRun() at /var/www/html/snipeit/vendor/symfony/console/Application.php:125
 Symfony\Component\Console\Application->run() at /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122
 Illuminate\Foundation\Console\Kernel->handle() at /var/www/html/snipeit/artisan:35`

**Comment by grimstoner** [comment]
After reading the code and playing around with it a little, what helped in my instance was to change my **Username field** property from _sAMAccountName_ to _samaccountname_ (i.e. lower case). Seems that PHP is a little more sensitive to case.

**Comment by snipe** [comment]
That's noted in the documentation. 

<img width="760" alt="screen shot 2017-11-07 at 11 02 44 am" src="https://user-images.githubusercontent.com/197404/32512239-3ce77022-c3ab-11e7-889c-eb6efe124d6c.png">

**Comment by snipe** [comment]
So the line in question is:

`$usernames[] = $location_users[$i][$ldap_result_username][0];`

where `$ldap_result_username` is `samaccountname `

Is it possible that you have some folks in your OU that don't have a samaccountname value? I've never been able to reproduce this issue despite endless LDAP testing, and it could be because we don't have any resource, non-user entities in our directory. 

CCing @hertel204

**Comment by snipe** [comment]
Can you (or anyone else still affected by this) do me a favor and testing something for me?

In `app/Console/LdapSync.php`, find the bit around line 133 that looks like this:

```
$location_users[$i]["ldap_location_override"] = true;
$location_users[$i]["location_id"] = $ldap_loc["id"];
$usernames[] = $location_users[$i][$ldap_result_username][0];
```

And change that block to wrap it in an if statement, like this:
```
if (array_key_exists($ldap_result_username, $location_users[$i])) {
    $location_users[$i]["ldap_location_override"] = true;
    $location_users[$i]["location_id"] = $ldap_loc["id"];
    $usernames[] = $location_users[$i][$ldap_result_username][0];
}
```

and try rerunning it.

My theory here is that it's fatally erroring out when it hits a record that's a resource or otherwise doesn't have a value for samaccountname, but would otherwise be working.

This is just a theory, since I can't reproduce this locally, but if someone wants to give this a try and report back, that would help me troubleshoot.

**Comment by hertel204** [comment]
This might be an possibility as there are User, Groups and another OU in the destination OU

let u know @snipe

**Comment by snipe** [comment]
Looks like you typo-ed it maybe? The method is `array_key_exists` not `arrey_key_exists`

**Comment by hertel204** [comment]
that's right fixed this and got the same "samaccount error"

**Comment by snipe** [comment]
Hm. Same line number?

**Comment by hertel204** [comment]
nop now on 140

**Comment by snipe** [comment]
Is line 140 the `$usernames[] = $location_users[$i][$ldap_result_username][0];` line?

**Comment by hertel204** [comment]
![image](https://user-images.githubusercontent.com/33985951/46178174-25c9eb00-c28c-11e8-80c0-89d5ffa8aa15.png)

**Comment by snipe** [comment]
Okay, change that block to:

```
// Delete located users from the general group.
if (array_key_exists($ldap_result_username, $generic_entry)) {
    foreach ($results as $key => $generic_entry) {
        if (in_array($generic_entry[$ldap_result_username][0], $usernames)) {
            unset($results[$key]);
        }
    }
}
```

**Comment by snipe** [comment]
Actually no that's wrong

sec

**Comment by snipe** [comment]
This one:

```
// Delete located users from the general group.
foreach ($results as $key => $generic_entry) {
   if (array_key_exists($ldap_result_username, $generic_entry)) {
        if (in_array($generic_entry[$ldap_result_username][0], $usernames)) {
            unset($results[$key]);
        }
    }
}
```

Sorry for the mistake - I'm kinda coding this blind right now.

**Comment by hertel204** [comment]
no problem you are doing much more then I could ever do by myself, thanks for that.

got this now:
(1/1) ErrorException
array_key_exists() expects parameter 2 to be array, integer given

**Comment by hertel204** [comment]
![image](https://user-images.githubusercontent.com/33985951/46178722-5a3ea680-c28e-11e8-8170-d8bacb15686f.png)

**Comment by snipe** [comment]
Alright, try this instead:

```
// Delete located users from the general group.
foreach ($results as $key => $generic_entry) {
   if ((is_array($generic_entry)) && (array_key_exists($ldap_result_username, $generic_entry))) {
        if (in_array($generic_entry[$ldap_result_username][0], $usernames)) {
            unset($results[$key]);
        }
    }
}
```

**Comment by hertel204** [comment]
@snipe it seems to be working now! 

thank you so much

**Comment by snipe** [comment]
@hertel204 - awesome - I've pushed that out to master. Thanks for your help debugging!
