### ISSUE TITLE
mySQL error on new install using docker

### ISSUE THREAD

**Issue by cringer** [snipe/snipe-it#4152]
#### Expected Behavior (or desired behavior if a feature request)

Setup should complete

-----

#### Actual Behavior

Application bombs out when going to step 2 of the installation wizard.

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
fresh

- Version of Snipe-IT you're running
latest

- Version of PHP you're running
7.0.22 (from your docker image)

- Version of MySQL/MariaDB you're running
MySQL 5.6

- What OS and web server you're running Snipe-IT on
Not sure it's your docker image.

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
docker

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.oauth_clients' doesn't exist (SQL: insert into `oauth_clients` (`user_id`, `name`, `secret`, `redirect`, `personal_access_client`, `password_client`, `revoked`, `updated_at`, `created_at`) values (, Snipe-IT Personal Access Client, 1zuGrEKoaGgYS5YkWWPF2phpP8jIVLUgVTYahsXw, http://localhost, 1, 0, 0, 2017-10-04 23:50:57, 2017-10-04 23:50:57))

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
It's the second page of the setup.  Should populate the database.

**Comment by snipe** [comment]
Try manually running migrations: `php artisan migrate`
