### ISSUE TITLE
Extend expected check-in / bulk check-in

### ISSUE THREAD

**Issue by dannyscarborough** [snipe/snipe-it#4153]
#### Expected Behavior (or desired behavior if a feature request)
Hi,

I've had a quick look at previously logged issues but I couldn't find anything related to this.

How do I extend the expected check-in date for an asset? 

The only way I can see to do this is by checking it back in and back out again but this triggers the notification emails again and is a bit cumbersome. 

Also is there a way to bulk check-in items or is this something that is coming in v4?

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
- Version of Snipe-IT you're running
v3.6.4 build 12
- Version of PHP you're running
5.3
- Version of MySQL/MariaDB you're running
8.3.0.4694

- What OS and web server you're running Snipe-IT on
Windows Server 2012
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
> How do I extend the expected check-in date for an asset?

That's not currently possible, but can be considered a feature request.

> Also is there a way to bulk check-in items or is this something that is coming in v4?

It's on the roadmap but not implemented yet.

**Comment by dannyscarborough** [comment]
@snipe Thanks for the reply. We would find it useful if it could be considered as a feature :+1:

**Comment by viclou** [comment]
+1 FD13886
