### ISSUE TITLE
License View Error Display

### ISSUE THREAD

**Issue by MacoWong** [snipe/snipe-it#4160]
Please help. Thanks.

![image](https://user-images.githubusercontent.com/32317020/31258252-7aa3e174-aa70-11e7-90fb-7364f1c59277.png)

[2017-10-06 08:27:56] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function fullName() on null' in C:\xampp\htdocs\snipe-it\storage\framework\views\53b6cb84a2c133f52c408395b6881523aa0cf6b1.php:400
Stack trace:
#0 {main}

**Comment by MacoWong** [comment]
Line 400:

 <a href="<?php echo e(route('view/user', $log->user_id)); ?>"><?php echo e($log->user->fullName()); ?></a>

**Comment by MacoWong** [comment]
" <a href="<?php echo e(route('view/user', $log->user_id)); ?>"><?php echo e($log->user->fullName()); ?></a> "

**Comment by MacoWong** [comment]
Line 400:

'   <a href="<?php echo e(route('view/user', $log->user_id)); ?>"><?php echo e($log->user->fullName()); ?></a>   '

**Comment by MacoWong** [comment]
Line 400: 

  href="<?php echo e(route('view/user', $log->user_id)); ?>"><?php echo e($log->user->fullName()); ?>

**Comment by MacoWong** [comment]
a href="<?php echo e(route('view/user', $log->user_id)); ?>"><?php echo e($log->user->fullName()); ?></a

**Comment by MacoWong** [comment]
Line 400:

#
 <a href="<?php echo e(route('view/user', $log->user_id)); ?>"><?php echo e($log->user->fullName()); ?></a>

#

**Comment by MacoWong** [comment]
Line 400: 

``  <a href="<?php echo e(route('view/user', $log->user_id)); ?>"><?php echo e($log->user->fullName()); ?></a> ``

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Haven't heard back, so I'm going to close this ticket for now, but will re-open it if you're still having issues
