### ISSUE TITLE
Issue - can not checkout existing asset to location in 4.0.9

### ISSUE THREAD

**Issue by jimmysnee** [snipe/snipe-it#4162]
#### Expected Behavior (or desired behavior if a feature request)

I have many existing assets in the system that I would like to checkout to a location.  However, the checkout to location option is only available upon creating new assets.

-----

#### Actual Behavior

When editing an EXISTING asset, the only option for checkout is to assign to a user.  The options checking out to a location or another asset are not presented.  When I compare this to the DEMO, I can not recreate the situation.

![snipe1](https://user-images.githubusercontent.com/16559440/31261707-c586f642-aa23-11e7-8c3e-bf8fbf0774ac.PNG)
![snipe2](https://user-images.githubusercontent.com/16559440/31261701-b76ef988-aa23-11e7-8236-20b9638e49c2.PNG)

When adding a NEW asset, the option for checking out does not appear until the status is defined.  

![snipe3](https://user-images.githubusercontent.com/16559440/31261677-ac376a00-aa23-11e7-9cd2-b4eb48b1f6e3.PNG)

Once the status is defined, it allows for checkout to user, asset, or location.  At that time, if I checkout to location, it properly displays as such in the asset views.  

![snipe4](https://user-images.githubusercontent.com/16559440/31261657-a27b12e6-aa23-11e7-9bb5-cc2182032368.PNG)

However, if I check that newly created asset in (was checked out to location on initial creation), then try to check it out again, the only option presented is to checkout to user. (same as 1st & 2nd images above)

There are no errors presented, whether in standard or debug mode.

I am wondering if this has something to do with the presence of custom fieldsets that is causing the code to block those options from being presented..

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- **Is this a fresh install or an upgrade?**  Running 4.0.9 (upgraded from 3.6.2, 4.0.4, 4.0.5, 4.0.6, 4.0.8)
- **Version of Snipe-IT you're running** - 4.0.9
- **Version of PHP you're running** - 7.0.23
- **Version of MySQL/MariaDB you're running** - 15.1 Distrib 10.0.31-MariaDB
- **What OS and web server you're running Snipe-IT on** - RHEL6
- **What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)** - Originally installed from install.sh. Currently running on fresh install GIT install using existing database that was migrated from 3.6.2 to 4.0.4.
- **WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error** - No errors present.
- **What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error** - Assets - creating new assets, editing existing assets.
- **If a stacktrace is provided in the error, include that too.** - Not provided.
- **Any errors that appear in your browser's error console.** - No errors present.
- **Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.**  - Could not reproduce on demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by madd15** [comment]
@jimmysnee check the category of the asset for a checkbox with `Require users to confirm acceptance of assets in this category.` as in the image below.

![req-acceptance](https://user-images.githubusercontent.com/3274937/31306130-f30e7b62-ab90-11e7-975b-c636a5561667.PNG)

If this is the case then when creating a new asset that given a model in a category that requires users to confirm then you should on be able to check out to a user.

**Comment by jimmysnee** [comment]
@madd15 - That did it - I can now checkout all of the assets to locations.

Thanks so much for the help!!
