### ISSUE TITLE
v4 Bug: Disable checkout emails

### ISSUE THREAD

**Issue by tbradsha** [snipe/snipe-it#4165]
#### Expected Behavior (or desired behavior if a feature request)

Can you please allow a system-wide setting (or category-level setting) to disable email notifications when an item is checked out?

-----

#### Actual Behavior

I see in categories there is a setting to disable check-in email notifications, but not check-out email notifications.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

-Fresh install
-Snipe-IT v4.0.9 build 120 (gf66e222)
-PHP 5.6.28
-MySQL 5.7.15
-Windows Server 2012 R2 + Apache 2.4 (XAMPP)
-Manual installation

**Comment by tiagom62** [comment]
+1

I currently set MAIL_DRIVER=log to work around this so the app doesn't complain when it fails to send the email.

**Comment by tbradsha** [comment]
In my case, I want to allow for the email system to be in place (e.g. reset passwords, etc.), but have more control over when the users are emailed. I've removed the other users' emails for the time being, but it's less than ideal.

**Comment by Jarli01** [comment]
I can confirm this as well, it used to not send checkout confirmations to users, this started as of this morning (10-11-2017) after I updated to with this: https://github.com/snipe/snipe-it/commit/c15c082fb4c33ea8fbd019498ed051a83e75230d

Version Details
v4.0.9 build 189 (g907b909)

**Comment by snipe** [comment]
Please pull latest from develop or master and see if this is now fixed.

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/getting-help#section-step-2-enable-your-browsers-error-console

**Comment by tbradsha** [comment]
I can confirm that for me! Check-ins and checkouts are no longer sending emails, which is expected. Enabling the check-in email in the categories section sends an email on check-in and not checkout, which also would be expected.

It doesn't look like there's an option in the categories section to send/not send checkout emails (only check-in emails), so this altogether disables checkout emails, which other users might not like...

**Comment by Jarli01** [comment]
I've just updated to v4.0.9 build 215 (g36cbffa) and this issue appears to be resolved.
