### ISSUE TITLE
[Feature Request]: Email a changed password to a user

### ISSUE THREAD

**Issue by tbradsha** [snipe/snipe-it#4166]
#### Expected Behavior (or desired behavior if a feature request)

When an admin changes an existing user's password, there's no way to send that to said user's email.

-----

#### Actual Behavior

Creating a new user has an option to send the password to the user, but not changing an existing user's password.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

-Fresh install
-Snipe-IT v4.0.9 build 120 (gf66e222)
-PHP 5.6.28
-MySQL 5.7.15
-Windows Server 2012 R2 + Apache 2.4 (XAMPP)
-Manual installation

**Comment by snipe** [comment]
Wouldn't it be more secure to let the user change their own password via the forgotten password request?

**Comment by tbradsha** [comment]
You and I prefer that method (and yes, it'd be more secure), but you'd be surprised how difficult a non-technical person finds it to locate a reset password link, put their email in, check their email, click the link from their email, then go and set a new password.

Often they instead find it easier to walk over to me and have me reset the password right then and there, receiving notification of what it was set it to.

**Comment by snipe** [comment]
I wonder if a compromise might be a way for an admin to trigger the reset password email on behalf of a user. That will then email them a link where they can reset their password.

**Comment by tbradsha** [comment]
That'd definitely work, yes!
