### ISSUE TITLE
Close: Update Docker Issue

### ISSUE THREAD

**Issue by meyerf99** [snipe/snipe-it#4167]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

I have a problem with Snipe IT Update
-----

#### Actual Behavior

(what actually happens goes here)

How can i upgrade my docker container from version 4.0.6 to the latest 4.0.9 version?
---

#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **fresh install**
- Version of Snipe-IT you're running **4.0.6**
- Version of PHP you're running **7.0.22 Ubuntu 16.04.1**
- Version of MySQL/MariaDB you're running **MySQL 5.7**
- What OS and web server you're running Snipe-IT on **We use docker installation**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **docker**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
@uberbrady can you help?

**Comment by snipe** [comment]
@uberbrady can you update the docker documentation to reflect how people should be upgrading, please? 

![katniss-thank-you-gif](https://user-images.githubusercontent.com/197404/31699832-060465e2-b37a-11e7-9134-63416bf2118e.gif)

**Comment by ovizii** [comment]
THANKS! I've got my own issue upgrading via Docker so I'm linking it here: https://github.com/snipe/snipe-it/issues/4197 in case on of these two threads gets a solution.
