### ISSUE TITLE
api - null payload using post method

### ISSUE THREAD

**Issue by manassesferreira** [snipe/snipe-it#4168]
#### Expected Behavior (or desired behavior if a feature request)

We wish to make full use of the new awesome api.
Following the reference (https://snipe-it.readme.io/v4.0/reference) 
we expected to be able to create, read, update and delete data.

-----

#### Actual Behavior

For the "companies" api, for instance, only the get and delete methods are working. 
The post method returns payload is null, although we pass the values...

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - fresh - docker setup.
- Version of Snipe-IT you're running - v4.09
- Version of PHP you're running -  7.0.22
- Version of MySQL/MariaDB you're running - 5.6
- What OS and web server you're running Snipe-IT on - linux and apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - not applicable. error in api.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - not applicable. 
- If a stacktrace is provided in the error, include that too. - below.
- Any errors that appear in your browser's error console. - not applicable.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. - on the api demo (https://snipe-it.readme.io/v4.0/reference#companies-1) the error does not occur.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. - below.
- Include what you've done so far in the installation, and if you got any error messages along the way. - below.
- Indicate whether or not you've manually edited any data directly in the database. - we do not edit data directly.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

OUR SETUP STEPS:

docker run --name snipe-mysql --env-file=issue.env -d -P mysql:5.6
docker run --rm snipe/snipe-it:v4.0.9
 -->get APP_KEY and insert at issue.env
docker run -d -p 80:80 --name="snipeit" --link snipe-mysql:mysql --env-file=issue.env snipe/snipe-it:v4.0.9

docker exec -ti snipeit bash
su docker
php artisan migrate

--> open the browser and perform the setup.
--> after create a token at /account/api, we reproduce our issue with the following python script:

============================================================================
import requests
token = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjRjODMyZTY3NzI5ZjAzMjhmYzQ2NWY3ZWNlNmQ4MWY0ZDM5MTc2ZjA1NjMzMmFkMzExNGNjMzlmOWVjZjUwZTY0OWRlZGE1MDQzZTEzNWY3In0.eyJhdWQiOiIxIiwianRpIjoiNGM4MzJlNjc3MjlmMDMyOGZjNDY1ZjdlY2U2ZDgxZjRkMzkxNzZmMDU2MzMyYWQzMTE0Y2MzOWY5ZWNmNTBlNjQ5ZGVkYTUwNDNlMTM1ZjciLCJpYXQiOjE1MDcxMTgxODAsIm5iZiI6MTUwNzExODE4MCwiZXhwIjoxODIyNjUwOTc5LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.lseYncMZqJn5fnei9oZrOK3fIFLXwdryop5uP1HtZts_cX4G_LIbuyS_zQ8MhB-KUE657UrIXGd0-P8aV2U_ZrUJak9uKcziRwkdsuqRh8Rp0IG7zrb1LEiiZkLHnIzRwU8LdYD00xa_aY_gc33L9aUoxdo6CWJe15TCqC804Cv0Gw90YTZ45jBIA9me2kDlk-ICyJ2Jt9adx2Qn6d9gYU-SOZxqf32ap5fp_ohOAPAO21TEhHAswc_a0bshmhl2Zxg2uek2EQFUWZqmgp6ZW1YhDKawb_RIMFGvETmKNUYpHUu1n1OJKmjTehhQWZz67GF3Hd5Oym3g6KkphnQIopNCUu5IZtBYue6CChrSe5OhcdoE1Xs_FzdY71VxkM_iB0LgMfQtdMJulIokIvhn7X56yUayRWIEqvWxQDC7apcwsAPxmb1Yb1qejET_YgSGn0sDTK6MEqjZEJA0pG-x5Lsx4fBhEOQ_LFxK6TB_i2fzWHjXwXjNPOIFY81tnxZTFiEWbm_mHHUXAjsb88gB0hgMp6UERydB9Vgpb7QQniRafKq3j5M4N5Bz4BBYVGL3DRtEqqcA0j9IU2Sos4yOPJC6tQseSOqxWJWQBClc5qcusWGOWUIWL6knOcVxWx5YqAQdivsmkB7JnqkBp-Lq9ztzn3iFnMTBbvp_38QiO6U'
headers = {'content-type': 'application/js', 'Authorization': 'Bearer '+token}

print("POST\n")
post_url="http://localhost/api/v1/companies"
payload = "{\"name\":\"com1\"}"
r=requests.post(post_url,headers=headers,data=payload)
print(r.text+"\n")

print("GET\n")
get_url="http://localhost/api/v1/companies"
r=requests.get(get_url, headers=headers)
print(r.text+"\n")

print("DELETE\n")
delete_url="http://localhost/api/v1/companies/2"
r=requests.delete(delete_url,headers=headers)
print(r.text+"\n")

============================================================================

which has the following output:

============================================================================

POST

{"status":"error","messages":{"name":["The name field is required."]},"payload":null}

GET

{"total":0,"rows":[]}

DELETE

{"status":"error","messages":"Asset does not exist.","payload":null}

============================================================================

We also configure an apache module to log post requests which registered the following:

============================================================================
--9448f706-A--
[06/Oct/2017:14:24:40 +0000] WdeSKKwRAAMAAADHFUoAAAAJ 172.17.0.1 41818 172.17.0.3 80
--9448f706-B--
POST /api/v1/companies HTTP/1.1
Host: localhost
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.18.4
content-type: application/js
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjRjODMyZTY3NzI5ZjAzMjhmYzQ2NWY3ZWNlNmQ4MWY0ZDM5MTc2ZjA1NjMzMmFkMzExNGNjMzlmOWVjZjUwZTY0OWRlZGE1MDQzZTEzNWY3In0.eyJhdWQiOiIxIiwianRpIjoiNGM4MzJlNjc3MjlmMDMyOGZjNDY1ZjdlY2U2ZDgxZjRkMzkxNzZmMDU2MzMyYWQzMTE0Y2MzOWY5ZWNmNTBlNjQ5ZGVkYTUwNDNlMTM1ZjciLCJpYXQiOjE1MDcxMTgxODAsIm5iZiI6MTUwNzExODE4MCwiZXhwIjoxODIyNjUwOTc5LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.lseYncMZqJn5fnei9oZrOK3fIFLXwdryop5uP1HtZts_cX4G_LIbuyS_zQ8MhB-KUE657UrIXGd0-P8aV2U_ZrUJak9uKcziRwkdsuqRh8Rp0IG7zrb1LEiiZkLHnIzRwU8LdYD00xa_aY_gc33L9aUoxdo6CWJe15TCqC804Cv0Gw90YTZ45jBIA9me2kDlk-ICyJ2Jt9adx2Qn6d9gYU-SOZxqf32ap5fp_ohOAPAO21TEhHAswc_a0bshmhl2Zxg2uek2EQFUWZqmgp6ZW1YhDKawb_RIMFGvETmKNUYpHUu1n1OJKmjTehhQWZz67GF3Hd5Oym3g6KkphnQIopNCUu5IZtBYue6CChrSe5OhcdoE1Xs_FzdY71VxkM_iB0LgMfQtdMJulIokIvhn7X56yUayRWIEqvWxQDC7apcwsAPxmb1Yb1qejET_YgSGn0sDTK6MEqjZEJA0pG-x5Lsx4fBhEOQ_LFxK6TB_i2fzWHjXwXjNPOIFY81tnxZTFiEWbm_mHHUXAjsb88gB0hgMp6UERydB9Vgpb7QQniRafKq3j5M4N5Bz4BBYVGL3DRtEqqcA0j9IU2Sos4yOPJC6tQseSOqxWJWQBClc5qcusWGOWUIWL6knOcVxWx5YqAQdivsmkB7JnqkBp-Lq9ztzn3iFnMTBbvp_38QiO6U
Content-Length: 15

--9448f706-C--
{"name":"com1"}
--9448f706-F--
HTTP/1.1 200 OK
Vary: Authorization
Cache-Control: no-cache, private
X-Clockwork-Id: dc2d3d634c42c02d4ad4460e2c207640
X-Clockwork-Version: 1
X-Clockwork-Path: _debugbar/clockwork/
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
X-XSS-Protection: 1;mode=block
X-Frame-Options: SAMEORIGIN
Set-Cookie: snipeit_session=eUOZMJ2MejoyaMnBVmzoRW0NTPkp2MDX1vcTvbXX; expires=Sat, 14-Oct-2017 22:24:40 GMT; Max-Age=720000; path=/; HttpOnly
Content-Length: 85
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: application/json

============================================================================

Are we doing something wrong? We believe not. So we ask for your help! Thank you!

**Comment by ghaberek** [comment]
The `Content-Type` header should be set to `application/json` not `application/js`. Also, you can pass your payload data to the requests library as a dictionary using the `json` parameter. Doing that, you can also leave out the `Content-Type` header altogether.

    post_url = 'http://localhost/api/v1/companies'
    headers = { 'Authorization': 'Bearer '+token }
    payload = { 'name': 'com1' }
    r = requests.post( post_url, headers=headers, json=payload )

**Comment by manassesferreira** [comment]
In fact! It is working this way!
Maybe we will suggest editions at https://dash.readme.io/to/snipe-it. 
Thanks!

**Comment by snipe** [comment]
@manassesferreira We already specify `application/json` [in the documentation](https://snipe-it.readme.io/v4.0/reference#authenticating-with-the-api).

<img width="783" alt="screen shot 2017-10-06 at 1 12 02 pm" src="https://user-images.githubusercontent.com/197404/31296670-0a61cad4-aa98-11e7-9e7a-9708118c47e6.png">
