### ISSUE TITLE
Column Widths for Assets Display

### ISSUE THREAD

**Issue by blissfulgifts** [snipe/snipe-it#417]
Hi,
Wanted to change the widths for the columns displayed in the Assets list. I can see in the code an inline style width is added to the columns. Is this a set percentage of the screen width and can it be altered? At the moment, the asset tags can flow onto 2 lines where as the model and serial number values are small but the column width is much large for these.

Thanks in advance.

John

**Comment by snipe** [comment]
We're using server side data tables for assets now, with toggle-able column visibility (on the develop branch). I think that's as close as we're going to be able to get to this for now.
