### ISSUE TITLE
403 error on locations page as non super user

### ISSUE THREAD

**Issue by JZomerlei** [snipe/snipe-it#4175]
#### Expected Behavior (or desired behavior if a feature request)
Clicking on a location from the assets page should list the location's information. 

-----

#### Actual Behavior

As non superuser with all other permissions I cannot navigate to locations without a 403 sad panda error occurring

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
(some of them- i at least checked for this error)
-----
#### Provide answers to these questions:

- Version of Snipe-IT you're running
3.6.6

As a global super admin I can access the locations page without a 403 error, on an account with every permission granted but super admin, I get a 403 error when clicking on a specific location from the assets page.  This functionality is something that I would like some users who aren't admins to have when they're operating on the snipe-it installation for them.

If there is a permission I'm missing that'd be great. I glanced over the open source material and I see snippets of "licenses.can" and "assets.can" in regards to permissions but there isn't a "locations.can" but that's as far as I got when it comes to poking my nose around.

**Comment by snipe** [comment]
We'll look into it for v4, but I doubt we'd go back and update v3.6.6 at this point since v4 is out.

**Comment by JZomerlei** [comment]
That's okay, I'm going to be upgrading to v4 soon but I either wanted this ability to be explained or for some one to let me know the process of just activating it to every user.

The way we use our Snipe-It is a few users that create and control phony users for management sake, the users outside of my and the team don't know about snipe-it. I do not wish to elevate every user or snipe-it to a superadmin to use the functionality that the locations page brings. 

The way the company I'm working for uses snipe-it is with 3 pages.

**Comment by snipe** [comment]
This should all be handled via the more granular permissions of v4 already.

**Comment by JZomerlei** [comment]
Forgot to comment: I found a way around it for our use case. I combined the conditions for locations for licenses. Seems to work just fine. I just had to figure it out :)
