### ISSUE TITLE
Asset Import Feature not working v4.0.9

### ISSUE THREAD

**Issue by cschuks** [snipe/snipe-it#4176]
#### Expected Behavior (or desired behavior if a feature request)

On click import and upload it ought to import the assets as expected

-----

#### Actual Behavior
It gets to 10% and stops...does not go further and does not upload successfully.

-----

#### Please confirm you have done the following before posting your bug report:

- [ Yes ] I have enabled debug mode 
- [ Yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
It is a fresh Install 
- Version of Snipe-IT you're running
V4.0.9
- Version of PHP you're running
7.0.10
- Version of MySQL/MariaDB you're running
MySQL 5.7.14
- What OS and web server you're running Snipe-IT on
Windows 10 on Wamp server
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
I am not getting any error in my browser with debug mode
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
importing asset csv file on /public/import
- If a stacktrace is provided in the error, include that too.
No stacktrace
- Any errors that appear in your browser's error console.
No error appears the file just does not upload
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
The import feature on the demo is not enabled.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
Nil
- Include what you've done so far in the installation, and if you got any error messages along the way.
There has not been any error message so far.
- Indicate whether or not you've manually edited any data directly in the database
No I have not.
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by raakhtar** [comment]
Issue still not fixed, has been lingering on since v4 for the "subdirectory". 

Have even tested it with v4.0.9 build 189. same thing as you have mentioned stops at 10% and shows console messages.

**Comment by snipe** [comment]
@cschuks are you running snipe-it in a subdirectory or top level domain?

**Comment by cschuks** [comment]
@snipe Top I actually have been trying to test it on my wamp server localhost before I host it online...although I intend using a subdirectory online but at the moment I am experiencing the issue on my wamp server.

**Comment by oks1998** [comment]
my snipeit also same, first time i try is stuck 10% and after refresh, the % not even show up.

**and my debug mode cannot enable**
version: v4.0.9 build 189 (g907b909)
install location: /var/www/snipe-it

**Comment by greenbushlabs** [comment]
... Same issue as @cschuks  here, we are running V4.0.9 ... upload stops at 10%  ... only difference is our server OS is FreeBSD 8.2

**Comment by snipe** [comment]
@greenbushlabs @cschuks And you've both checked the permissions on your `storage` directory, to confirm that it (and all subdirectories) are writable?

**Comment by greenbushlabs** [comment]
I just ran `chmod -R 777 storage` to make sure I did not miss any sub-directories - then attempted upload again, however am still getting the "10% Complete" complete message ... I am attempting to upload the "MOCK_ASSETS.csv" sample from the [sample_csvs] directory.

**Comment by raakhtar** [comment]
same issue, has not been fixed since 4.0.x for subdirectories @snipe . Kindly prioritize fixing of this particular issue.

**Comment by snipe** [comment]
@raakhtar we make it pretty clear that Snipe-IT wants to be run as a subdomain or top-level domain. We're trying to work through the sub-directory issues, but they are a lower priority for us than other issues.

**Comment by greenbushlabs** [comment]
got this working ... created a subdomain and all works well ... inventory.whatever.whatever and walla !

**Comment by raakhtar** [comment]
@greenbushlabs How did you make it work in sub-directory ?
It began to work on the server (browser), however when being accessed from another computer. it gets stuck @ 10%. any thoughts ?

**Comment by raakhtar** [comment]
@ok this is to confirm, that is fixed in v4.0.10. I just deleted the browser cache and it began to work like a charm ... Awesome work team @snipe @dmeltzer

**Comment by live-motion** [comment]
Same problem in 4.6.6
10% and stops
i change domain, subdomain, open by ip - only 10% and stop

**Comment by snipe** [comment]
@live-motion Hi there - the importer definitely works in v4.6.6, and this thread has been closed for quite some time. 

If you're having trouble, please create a new issue and fill in all of the questions in the new issue form. (When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.)
