### ISSUE TITLE
[Feature Request] Ability to add virtual machines & hypervisors

### ISSUE THREAD

**Issue by haynes11** [snipe/snipe-it#4177]
#### Expected Behavior (or desired behavior if a feature request)

Hi,

This concept would be best served by adding the ability to add a "Dedicated server" as an asset type. Under the creation page you would have the ability to specify whether that dedicated server is a hypervisor. If so there's another page that you can create virtual machines under that "hypervisor" with the ability to add fieldsets/licenses/all the other features that we all love linked to it.

Best,
J

**Comment by snug** [comment]
Shouldn't you be able to do this already with custom fields?

**Comment by haynes11** [comment]
As far as I know not quite. Seeing as virtual machines have no asset number/service tag so they have to be faked. Additionally custom fields to my understanding wouldn't allow you to "attach" those virtual machines to a physical asset/server. So no "Parent/child" relationship. Seeing as virtual machines can specifically have their own licensing as well as the dedicated server itself having other licensing without the proper model in place things can get messy especially with no real asset tags or differentiation.

I could be wrong though?

**Comment by BrettFagerlund** [comment]
While i probably wouldn't categorise a VM as an asset in inventory registers as such(it would live outside in orchestration/config management tools). If you did want to go that way you could just create the VM's as assets then checkout to the host Asset. Use a model called "virtual machine" so you can easily identify which assets are VM's and to which host they belong. Also add a custom field to the physical machine if you want to put a hypervisor flag on it.

That would allow licence/custom fields on both host/guest machine.

**Comment by Jarli01** [comment]
This functionality would fall under #3566 with nested modules.

**Comment by haynes11** [comment]
@BrettFagerlund I'll give that a go, thanks! :) Would be great to have the above implemented natively ^
