### ISSUE TITLE
 LDAP user xxx not found in LDAP or could not bind

### ISSUE THREAD

**Issue by madhuj4** [snipe/snipe-it#4179]
#### Expected Behavior (or desired behavior if a feature request)
Login to user account
(what you expect to happen goes here)

-----

#### Actual Behavior
throws an error "There was an error authenticating the LDAP user: Could not find user in LDAP directory"
(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
Yes
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
Yes
-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh installation
- Version of Snipe-IT you're running
v4.0.9 build 120 (gf66e222) 
- Version of PHP you're running
7.0.24-1+ubuntu14.04.1+deb.sury.org+1
- Version of MySQL/MariaDB you're running
MariaDB
- What OS and web server you're running Snipe-IT on
ubuntu 14.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by madhuj4** [comment]
My Configuration looks like this
AD xxx.xx.com
ldap server
ldap://xxx.xxx.com
ldap bind username
xxx@xxx.com
Base Bind DN = dc=xxx,dc=com
LDAP Filter =&(objectcategory=person)(objectclass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2))
Username Field samaccountname
Last Name sn
LDAP First Name givenname
LDAP Authentication query samaccountname=
reset is default

**Comment by stf675** [comment]
tried to add "mail" for email field?

Also test would fail, but you wil be able to sync users and login

**Comment by snipe** [comment]
Auth query should be: `sAMAccountName=`

https://snipe-it.readme.io/v4.0/docs/ldap-sync-login#section-configuration

**Comment by snipe** [comment]
(If you pull latest from master, we added an LDAP test tool on the LDAP settings page.)
