### ISSUE TITLE
3.x and 4.x import asset behaviour

### ISSUE THREAD

**Issue by stf675** [snipe/snipe-it#4184]
#### Expected Behavior (or desired behavior if a feature request)

**Import Assets,  Added new column to CSV file and import again.  Column Asset Name same data as Asset Tag** 

(what you expect to happen goes here)

**Same number of Assets with updated info**
-----

#### Actual Behavior

(what actually happens goes here)

**Duplicate Assets, additional Asset Tag not not updated**

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a **fresh** install or an upgrade? fresh
- Version of Snipe-IT you're running **4.09**
- Version of PHP you're running 7.1
- Version of MySQL/MariaDB you're running installed by script
- What OS and web server you're running Snipe-IT on centod 6.9
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
@dmeltzer any thoughts?

**Comment by stf675** [comment]
Update:
partially user fault :)  I mistype additional column name.
so chain of event was
(all via CLI, GUI was giving "Error" without much info)
1. Import assets - success
2. realized that Asset Name missing,  added "Asset Name" column
3. re-upload file, rerun import, result was each record imported as new, no Asset Name
4. Realized that CSV header name should be Item Name, not Asset Name, changed - half items got updated.
5. Delete all records
6. Import again - All good.

so line item 2 - mismatch between Header name in Asset screen and what it should be called in CSV
and line item 3 - duplicate entries created, probably triggered by additional wrongly named column.
