### ISSUE TITLE
Asset Delete Bug

### ISSUE THREAD

**Issue by stf675** [snipe/snipe-it#4185]
#### Expected Behavior (or desired behavior if a feature request)

When I select 1000 records to delete

(what you expect to happen goes here)

I espect they being deleted

-----

#### Actual Behavior

Works with 500 and less, but not 1000.  1000 errors out

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  fresh
- Version of Snipe-IT you're running 4.09
- Version of PHP you're running  7.1 
- Version of MySQL/MariaDB you're running installed by install.sh
- What OS and web server you're running Snipe-IT on centos 6.9
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)  install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by stf675** [comment]
additional info for 500 records - it always say

"You are about to delete 498 assets."  instead of 500

**Comment by snipe** [comment]
>  1000 errors out

What is the specific error?

**Comment by snipe** [comment]
(Also, this is most likely a server memory / php.ini max posted fields issue.)

**Comment by stf675** [comment]
Ahh, I will adjust it tomorrow and try again

**Comment by stf675** [comment]
for 500 is minor bug I think, as it is actually show 498 records not 500

**Comment by snipe** [comment]
Haven't heard back, so I'm going to close this ticket for now, but will re-open it if you're still having issues
