### ISSUE TITLE
Documentation on how to implement SSL on a SnipeIT 4 instance using WAMP

### ISSUE THREAD

**Issue by AstiStewart** [snipe/snipe-it#4188]
Currently have a SnipeIT 4 instance running on Server 2016 with WAMP installed running HTTP,  looking to move the instance to use SSL/HTTPS and was looking for a step by step guide on how to do this (which files need editing etc.)

Any help would be appreciated

**Comment by snipe** [comment]
That's out of scope for the Snipe-IT documentation, but you can [find a tutorial here](https://stackoverflow.com/questions/5065281/how-to-enable-ssl-in-wamp-server).
