### ISSUE TITLE
Upgrade via cPanel

### ISSUE THREAD

**Issue by jbc91** [snipe/snipe-it#4189]
Just wondering if the version 4.0.9 will be available as an update in cPanel rather than a fresh installation soon?

#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
> Just wondering if the version 4.0.9 will be available as an update in cPanel 

I don't understand what you mean here. An update in cPanel? We don't have anything to do with cPanel.

**Comment by jbc91** [comment]
Sorry, misunderstanding here. Snipe-IT is available as an app within cPanel. 

At the moment the current version to install download is shown, but usually when an update is available, it will notify you and you can simply click update. I was under the impression you pushed that software to cPanel.

**Comment by snipe** [comment]
I think I know what you're talking about. A company called Softaculous packages up Snipe-IT for (I think) cPanel-based web hosts. According to their Twitter, they pushed out the 4.0.9 version - maybe your web host hasn't updated from them? They're not affiliated with us in any way, but you may want to contact your hosting company to see if there's something they need to do on their end. 

https://twitter.com/softaculous/status/915553665812803584
