### ISSUE TITLE
All Assets: Search by name of user not possible

### ISSUE THREAD

**Issue by MPIAE-IT** [snipe/snipe-it#4191]
#### Expected Behavior (or desired behavior if a feature request)

When I type in the name of a user which an asset is deployed to, all assets which are deployed to this user should appear. This was working fine in V2 and V3 (Never used V1) of Snipe IT. Since V4 Update it is not possible anymore.

![1](https://user-images.githubusercontent.com/16922521/31391412-c04a7454-add6-11e7-8f55-bafc7023c10e.png)

![2](https://user-images.githubusercontent.com/16922521/31391418-c56af95e-add6-11e7-88cb-305c853050b9.png)

-----

#### Actual Behavior

Nothing appears after typing in the name 
Result: "No matching records found"

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Upgrade from 3.6.6 to 4.0.6 to 4.0.9**
- Version of Snipe-IT you're running **v4.0.9 build 189 (g907b909)**
- Version of PHP you're running **7.0**
- Version of MySQL/MariaDB you're running **5.5.57-0ubuntu0.14.04.1**
- What OS and web server you're running Snipe-IT on **Ubuntu 14.04.5 LTS**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **manual**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **No error**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **All Assets -> Search Field**
- If a stacktrace is provided in the error, include that too. **NO**
- Any errors that appear in your browser's error console. **NO**
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. 
**Same thing is happening in the demo**
- Include what you've done so far in the installation, and if you got any error messages along the way. **Updated to the recent version on GitHub master**
- Indicate whether or not you've manually edited any data directly in the database
**Never touched it**

**Comment by rjdeclute** [comment]
I'm also having this issue.  I can also duplicate this issue in the Demo.

**Comment by diekmanu** [comment]
Strange. Works for me, but only in 'All assets' view. Also upgraded from 3.6.6.

**Comment by JExactly** [comment]
Same here

**Comment by MPIAE-IT** [comment]
What is also weird is that if I use advanced search it actually finds assets. But only one. This user has assigned 8 assets. 

![bildschirmfoto 2017-10-12 um 14 49 04](https://user-images.githubusercontent.com/16922521/31496702-bb25fab6-af5c-11e7-81b5-8cfdfed74949.png)

**Comment by MPIAE-IT** [comment]
#4198 Seems to be the same issue

**Comment by MPIAE-IT** [comment]
I can confirm. With update to 4.0.13 the search by user is possible again.

**Comment by JExactly** [comment]
I can say, I am able to search by a single name, But not by a " Checked Out To" user with the full name, is this portion still broken?

**Comment by diekmanu** [comment]
I guess the query is not combining the first_name and last_name fields. Can you search by username?
