### ISSUE TITLE
db.oauth_clients does not exist

### ISSUE THREAD

**Issue by Cornelious11** [snipe/snipe-it#4192]
Referring back to closed issue: #3852 
---------------------------------------------------
### Expected Behaviour

Same as #3852 (closed)

-----

### Actual Behaviour

Same as #3852 (closed)

-----

#### Confirmations

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----

#### Answers to basic questions

*Snipe-IT version* 4.0.9
*Operating System* Debian 9 / RHEL 7.4
the rest is the same as #3852 (closed)

----------------------------------------------------
Sorry to re-open this issue, but the issue seems to persist and not allow `php artisan passport:install` to execute because either:
a. there is insufficient permissions to access `storage/logs` (even with chmod 777)
OR
b. the table `db.oauth_clients` doesn't exist. when I run the same command with `sudo`

I tried to install snipe-it fresh on a new Debian based VM but ran in to the exact same issues with the install. During the pre-flight database creation it will display the same whoops something went wrong error message and cause ongoing issues with the rest of the install that I cannot seem to fix. Is there a package I may be missing prior to install that is preventing this from working properly?

**Comment by tiagom62** [comment]
`php artisan passport:install` is run by the web setup, you shouldn't need to run it manually.

Can you test using the current snipeit.sh master branch? If you are still having trouble please provide /var/log/snipeit-install.log and i will be gladly to help.

**Comment by Cornelious11** [comment]
that file doesn't seem to exist on my system. I tried using `find / -name snipeit-install.log` but search results returned nothing. If I navigate to the FQDN I have given the application it brings me to the dashboard. However with the failed table creation it causes lingering issues. Could this be caused by not having the mail setting configured properly?

**Comment by tiagom62** [comment]
The log file should exist. We log every step.

I will check my test system later to confirm that the file is being created. We are dealing with Debian 9 correct?

**Comment by Cornelious11** [comment]
```
corn@SnipeIT:~$ uname -a
Linux SnipeIT 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux
```
Did you want more system information?

**Comment by tiagom62** [comment]
Tested on `Linux debian9 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux` with snipeit.sh from master and it installed successfully. `/var/log/snipeit-install.log` exists in my install as well.

**Comment by Cornelious11** [comment]
Maybe I'm missing some critical package on my system, but neither `composer` nor `php artisan` are picking up on it during install. After running `apt-mark showmanual` I get the following list of user installed packages (236), with (1740 packages total)

```
adduser
apache2
apache2-utils
apt
apt-listchanges
apt-utils
base-files
base-passwd
bash
bash-completion
bind9-host
bsdmainutils
bsdutils
busybox
bzip2
console-setup
coreutils
cpio
cron
curl
dash
dbus
debconf
debconf-i18n
debian-archive-keyring
debian-faq
debianutils
diffutils
discover
dmidecode
dmsetup
doc-debian
dpkg
e2fslibs
e2fsprogs
eject
file
findutils
gcc-6-base
gettext-base
git
gnupg
gnupg-agent
gpgv
grep
groff-base
grub-common
grub-pc
gzip
hdparm
hostname
ifupdown
init
init-system-helpers
initramfs-tools
installation-report
iproute2
iptables
iputils-ping
isc-dhcp-client
isc-dhcp-common
keyboard-configuration
kmod
krb5-locales
laptop-detect
less
libacl1
libapache2-mod-php
libapparmor1
libapt-inst2.0
libapt-pkg5.0
libassuan0
libattr1
libaudit-common
libaudit1
libblkid1
libbsd0
libbz2-1.0
libc-bin
libc6
libcap-ng0
libcap2
libclass-isa-perl
libcomerr2
libcryptsetup4
libdb5.3
libdebconfclient0
libdevmapper1.02.1
libdns-export162
libelf1
libestr0
libfastjson4
libfdisk1
libffi6
libgcc1
libgcrypt20
libgdbm3
libgmp10
libgnutls30
libgpg-error0
libhogweed4
libidn11
libidn2-0
libip4tc0
libip6tc0
libiptc0
libisc-export160
libkmod2
libksba8
liblocale-gettext-perl
liblockfile-bin
liblogging-stdlog0
liblognorm5
liblz4-1
liblzma5
libmnl0
libmount1
libncurses5
libncursesw5
libnetfilter-conntrack3
libnettle6
libnewt0.52
libnfnetlink0
libnpth0
libp11-kit0
libpam-modules
libpam-modules-bin
libpam-runtime
libpam-systemd
libpam0g
libpcre3
libpipeline1
libpopt0
libprocps6
libpsl5
libreadline7
libseccomp2
libselinux1
libsemanage-common
libsemanage1
libsepol1
libslang2
libsmartcols1
libsqlite3-0
libss2
libssl1.0.2
libssl1.1
libstdc++6
libswitch-perl
libsystemd0
libtasn1-6
libtext-charwidth-perl
libtext-iconv-perl
libtext-wrapi18n-perl
libtinfo5
libudev1
libunistring0
libustr-1.0-1
libuuid1
libxapian30
libxtables12
linux-image-amd64
locales
login
logrotate
lsb-base
lsof
man-db
manpages
mariadb-client
mariadb-server
mawk
mime-support
moreutils
mount
multiarch-support
nano
ncurses-base
ncurses-bin
ncurses-term
net-tools
netbase
netcat-traditional
openssh-client
passwd
pciutils
perl
perl-base
perl-modules-5.24
php
php-bcmath
php-curl
php-gd
php-ldap
php-mbstring
php-mysql
php-zip
php7.0-common
php7.0-xml
pinentry-curses
procps
python
python-minimal
python2.7
python3-reportbug
readline-common
reportbug
rsyslog
sed
sensible-utils
sudo
systemd
systemd-sysv
sysvinit-utils
tar
task-desktop
task-english
task-print-server
task-ssh-server
tasksel
tasksel-data
telnet
traceroute
tzdata
ucf
udev
util-linux
vim-common
vim-tiny
wamerican
wget
whiptail
wmifinfo
xxd
xz-utils
zlib1g
```

**Comment by tiagom62** [comment]
Whats the perms on `oauth-private.key` and `oauth-public.key` in `/var/www/snipeit/storage`

**Comment by Cornelious11** [comment]
```
-rw-r--r--  1 www-data www-data 3292 Oct  6 11:22 oauth-private.key
-rw-------  1 www-data www-data  812 Oct  6 11:22 oauth-public.key
```
I did run `chmod -R 755 storage/` before pre-flight

**Comment by tiagom62** [comment]
Perms should be 
```
-rw-r--r-- 1 www-data www-data 3292 Oct 10 23:46 oauth-private.key
-rw-r--r-- 1 www-data www-data  812 Oct 10 23:46 oauth-public.key
```
So it sounds like you did a manual install.

I would recommend installing with the script provided if you continue to have issues.
```
wget https://raw.githubusercontent.com/snipe/snipe-it/master/snipeit.sh
chmod 744 snipeit.sh
./snipeit.sh
```
