### ISSUE TITLE
Error with using "Do Not Depreciate" option when adding a new asset model

### ISSUE THREAD

**Issue by JExactly** [snipe/snipe-it#4193]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running  v4.0.9 build 120 (gf66e222)
- Version of PHP you're running 7.0
- Version of MySQL/MariaDB you're running 
- What OS and web server you're running Snipe-IT on: Ubuntu 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. : No
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database: NO

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

![image](https://user-images.githubusercontent.com/14076881/31405355-ce13ccc0-adcc-11e7-8f11-60d79ffd0156.png)

(3/3) QueryExceptionSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'depreciation_id' cannot be null (SQL: insert into `models` (`eol`, `depreciation_id`, `name`, `model_number`, `manufacturer_id`, `category_id`, `notes`, `user_id`, `requestable`, `updated_at`, `created_at`) values (0, , 12345, 123455, 8, 4, , 2, 0, 2017-10-10 15:19:17, 2017-10-10 15:19:17))
--
in Connection.php (line 647)
at Connection->runQueryCallback('insert into `models` (`eol`, `depreciation_id`, `name`, `model_number`, `manufacturer_id`, `category_id`, `notes`, `user_id`, `requestable`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', array(0, null, '12345', '123455', '8', '4', '', 2, false, '2017-10-10 15:19:17', '2017-10-10 15:19:17'), object(Closure))in Connection.php (line 607)
at Connection->run('insert into `models` (`eol`, `depreciation_id`, `name`, `model_number`, `manufacturer_id`, `category_id`, `notes`, `user_id`, `requestable`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', array(0, null, '12345', '123455', '8', '4', '', 2, false, '2017-10-10 15:19:17', '2017-10-10 15:19:17'),object(Closure))in Connection.php (line 450)
at Connection->statement('insert into `models` (`eol`, `depreciation_id`, `name`, `model_number`, `manufacturer_id`, `category_id`, `notes`, `user_id`, `requestable`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', array(0, null, '12345', '123455', '8', '4', '', 2, false, '2017-10-10 15:19:17', '2017-10-10 15:19:17'))in Connection.php (line 404)
at Connection->insert('insert into `models` (`eol`, `depreciation_id`, `name`, `model_number`, `manufacturer_id`, `category_id`, `notes`, `user_id`, `requestable`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', array(0, null, '12345', '123455', '8', '4', '', 2, false, '2017-10-10 15:19:17', '2017-10-10 15:19:17'))in Processor.php (line 32)
at Processor->processInsertGetId(object(Builder), 'insert into `models` (`eol`, `depreciation_id`, `name`, `model_number`, `manufacturer_id`, `category_id`, `notes`, `user_id`, `requestable`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', array(0, null, '12345', '123455', '8', '4', '', 2, false, '2017-10-10 15:19:17', '2017-10-10 15:19:17'), 'id')in Builder.php (line 2133)
at Builder->insertGetId(array(0, null, '12345', '123455', '8', '4', '', 2, false, '2017-10-10 15:19:17', '2017-10-10 15:19:17'), 'id')in Builder.php (line 1251)
at Builder->__call('insertGetId', array(array('eol' => 0, 'depreciation_id' => null, 'name' => '12345', 'model_number' => '123455', 'manufacturer_id' => '8', 'category_id' => '4', 'notes' => '', 'user_id' => 2, 'requestable' => false, 'updated_at' => '2017-10-10 15:19:17', 'created_at' => '2017-10-10 15:19:17'), 'id'))in Model.php (line 688)
at Model->insertAndSetId(object(Builder), array('eol' => 0, 'depreciation_id' => null, 'name' => '12345', 'model_number' => '123455', 'manufacturer_id' => '8', 'category_id' => '4', 'notes' => '', 'user_id' => 2, 'requestable' => false, 'updated_at' => '2017-10-10 15:19:17', 'created_at' => '2017-10-10 15:19:17'))in Model.php (line 653)
at Model->performInsert(object(Builder))in Model.php (line 522)
at Model->save()in AssetModelsController.php (line 104)
at AssetModelsController->store(object(Request))
at call_user_func_array(array(object(AssetModelsController), 'store'), array(object(Request)))in Controller.php (line 55)
at Controller->callAction('store', array(object(Request)))in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(AssetModelsController), 'store')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 572)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php (line 43)
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php (line 49)
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php (line 49)
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php (line 42)
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 574)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 533)
at Router->dispatchToRoute(object(Request))in Router.php (line 511)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php (line 51)
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php (line 25)
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php (line 56)
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php (line 27)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

**Comment by nbattista89** [comment]
We have the same problem.
Maybe this can help you: https://github.com/snipe/snipe-it/issues/4136#issuecomment-335584188

**Comment by snipe** [comment]
This is already fixed on master.

**Comment by JExactly** [comment]
Awesome! Thanks!!
