### ISSUE TITLE
Asset tag reset to 1 after upgrade to 4.0.9. Incorrect autoincrement

### ISSUE THREAD

**Issue by sydit** [snipe/snipe-it#4196]
#3104  Expected Behavior (or desired behavior if a feature request)

Create asset with next auto increment value.

-----

#### Actual Behavior

My total assets are 850. After upgrading to 4.0.9 when I create asset , the tag reset to 1. However I can see all myprevious assets on dashboard and also its possible to set asset tag manually. I had this issue earlier( #3104 ) which was solved by editing _app/Models/Asset.php_ But this time it doesn't work. I also tried fresh install with imported data but the issue remains.

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Tried both fresh install and upgrade with imported DB
- 4.0.9
- PHP 7.0
- MariaDB 10.1.28
- OS Ubuntu 16.04, manual install with Debug ON

**Comment by snipe** [comment]
Did you set the auto-increment number in Settings > Asset Tags?

**Comment by sydit** [comment]
Yes currently auto increment value is 1. I can set manually on create asset page with last tag but next time when I create asset incremented value is  HW0002 instead of HW0852.

**Comment by snipe** [comment]
You have to set the auto-increment in Admin > Settings > Asset Tags.

**Comment by sydit** [comment]
![image](https://user-images.githubusercontent.com/24789532/31429924-f6afcbf0-ae8c-11e7-8943-0352081c4841.png)

Yep its all set. Total assets are 850.
![image](https://user-images.githubusercontent.com/24789532/31430034-51a7a1a4-ae8d-11e7-8019-32cb96df5345.png)

**Comment by snipe** [comment]
Then your next auto-increment shouldn't be set to 1, it should be whatever your next number is.

**Comment by sydit** [comment]
Sorry I'll try it now and let you know.....

**Comment by sydit** [comment]
Yes it's working. :+1: So simple setup which I missed.  I'm closing the issue. Thanks snipe for your help
