### ISSUE TITLE
Audit Log - Empty

### ISSUE THREAD

**Issue by eyetataks** [snipe/snipe-it#4200]
#### Expected Behavior (or desired behavior if a feature request)

i assumed when i did a bulk edit the results would show under reports Audit Log but nothing populates there is there a bug?

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by GeoffYoung** [comment]
That log is a list of results from asset auditing.

https://snipe-it.readme.io/blog/whats-new-in-snipe-it-v4#section-new-auditinginventory-feature

**Comment by eyetataks** [comment]
my apologies.  type o on my part.  Bulk AUDIT  not edit.   so yes exactly what you linked me to is what I am doing but nothing shows in the log.

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by eyetataks** [comment]
4.09 build 120
ubuntu 16 apache (used your install script)
install script
no error in browser
i do an audit of my items using bulk audit, seems to work fine, gives green success for each one, i can see the audits in activity log, but then go to report, audit log and that is blank
no stack trace
no errors
seems to work fine in your demo
no manual editing of database

**Comment by snipe** [comment]
@eyetataks without some sort of an error, I don't know how we're going to be able to help you.

**Comment by eyetataks** [comment]
is there some logging to turn on that will help?  again no error but it doesnt work

**Comment by eyetataks** [comment]
<img width="1333" alt="screen shot 2017-10-11 at 2 45 24 pm" src="https://user-images.githubusercontent.com/32716108/31468520-edd30802-ae92-11e7-9c30-a98069edfd0a.png">

**Comment by eyetataks** [comment]
<img width="1353" alt="screen shot 2017-10-11 at 2 45 44 pm" src="https://user-images.githubusercontent.com/32716108/31468534-f80dae26-ae92-11e7-9651-12258ed55146.png">

**Comment by snipe** [comment]
@eyetataks https://snipe-it.readme.io/docs/getting-help#section-step-2-enable-your-browsers-error-console

**Comment by eyetataks** [comment]
no errors.  could my db or tables be messed up?  is there a way to reinitialize those?  I only have test data in the system,  just got it going last week.

**Comment by eyetataks** [comment]
i dunno, i guess I can try one more time from a fresh OS install.  I dumped all the tables, ran the installer again and started over and now i create an asset and it doesn't show in all assets but if I drill down to 'ready to deploy' there it is.  and still if I audit it, nothing in audit log.

**Comment by snipe** [comment]
If your DB tables were messed up, you’d be seeing something in your `storage/logs/latavel.log` to that affect. 

When you click on the audited asset, do you see the audit in the history tab?

Also do you get any errors when you do a singular audit from the asset detail view?

**Comment by snipe** [comment]
If you run `php artisan migrate`, what happens?

**Comment by eyetataks** [comment]
maybe this is a clue?  happy to upload whole log if it helps.

Next Illuminate\Database\QueryException: SQLSTATE[42000]: Syntax error or access violation: 1066 Not unique table/alias: 'locations' (SQL: select coun
t(*) as aggregate from `assets` left join `users` on `users`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\Models\User left join `l
ocations` on `locations`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\Models\Location left join `assets` as `assigned_assets` on `
assigned_assets`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\Models\Asset inner join `locations` on `locations`.`id` = `assets`.`
rtd_location_id` where (exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `categories` where `models`
.`category_id` = `categories`.`id` and (`categories`.`name` LIKE %0000001% or `models`.`name` LIKE %0000001% or `models`.`model_number` LIKE %0000001%
) and `categories`.`deleted_at` is null)) or exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `manuf
acturers` where `models`.`manufacturer_id` = `manufacturers`.`id` and (`manufacturers`.`name` LIKE %0000001%) and `manufacturers`.`deleted_at` is null
)) or (exists (select * from `status_labels` where `assets`.`status_id` = `status_labels`.`id` and `status_labels`.`name` LIKE %0000001% and `status_l
abels`.`deleted_at` is null)) or (exists (select * from `suppliers` where `assets`.`supplier_id` = `suppliers`.`id` and `suppliers`.`name` LIKE %00000
01% and `suppliers`.`deleted_at` is null)) or (exists (select * from `companies` where `assets`.`company_id` = `companies`.`id` and `companies`.`name`
 LIKE %0000001%)) or (exists (select * from `locations` where `assets`.`rtd_location_id` = `locations`.`id` and `locations`.`name` LIKE %0000001% and 
`locations`.`deleted_at` is null)) or (exists (select * from `assets` as `laravel_reserved_0` where `laravel_reserved_0`.`id` = `laravel_reserved_0`.`
assigned_to` and (`users`.`first_name` LIKE %0000001% or `users`.`last_name` LIKE %0000001% or `users`.`username` LIKE %0000001% or `locations`.`name`
 LIKE %0000001% or `assigned_assets`.`name` LIKE %0000001%) and `laravel_reserved_0`.`deleted_at` is null)) or `assets`.`name` LIKE %0000001% or `asse
ts`.`asset_tag` LIKE %0000001% or `assets`.`serial` LIKE %0000001% or `assets`.`order_number` LIKE %0000001% or `assets`.`notes` LIKE %0000001% or `as
sets`.`_snipeit_mac_address_1` LIKE %0000001%) and `assets`.`deleted_at` is null) in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database
/Connection.php:647

**Comment by eyetataks** [comment]
also php artisan migrate says nothing to migrate
yes I see the audit in history
no, no error when I audit one asset, says successful.

**Comment by eyetataks** [comment]
mucked around redoing install steps / updating packages / changing permissions here and there and it seems to be working now!  i don't know enough linux to know what fixed it but i think i am up and running with full functionality, will keep testing.
