### ISSUE TITLE
Confirm asset delivery emails being sent with categories disabled

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#4203]
The issue is even with categories being set to not email "Confirm asset delivery" notifications they are still being sent. 

Workaround 
Change (.env) to be

vi /var/www/html/snipeit/.env 
MAIL_DRIVER=smtp
to
MAIL_DRIVER=log

and reload cache

php artisan config:clear

**Comment by snipe** [comment]
Duplicate of #4165
