### ISSUE TITLE
Feature request: Scrolling behavior in large lists

### ISSUE THREAD

**Issue by Mateopato** [snipe/snipe-it#4207]
#### Expected Behavior (or desired behavior if a feature request)

I'd like to request three improvements to scrolling behavior on large lists. 

1. The site navigation bar on the far left side of the web site should remain in the same position as you scroll so it is available from any position within a large list. 

2. The column titles for lists should remain static as you scroll through a list (this is also described in issue #3336). 

3. The horizontal scroll bar at the bottom of tables should remain static at the bottom of the table display as you scroll so you can scroll side-to-side from any position in a large list rather than only at the bottom of the list.

Embedding table displays in some type of frame or container seems like it would be the easiest way to solve 1 and 3. Implementing 2 may require some CSS hacking. 

-----

#### Actual Behavior

1. The site navigation bar scrolls off the screen after scrolling down 5 or 6 items in the asset list, leaving it inaccessible until you scroll back to the top of the screen.

2. The headers scroll off the screen nearly immediately when scrolling, so you can't tell what the columns are without scrolling all the way back to the top. 

3. The horizontal scrollbar is only accessible at the very bottom of a large list. If you have a lot of columns displayed on a long list, you can only see the right columns if you scroll all the way down and then back to where you want to look. 

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Both
- Version of Snipe-IT you're running: v3 before, just updated to v4.0.9 build 215 with same issues
- Version of PHP you're running: 7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running: mysql Ver 14.14 Distrib 5.5.54
- What OS and web server you're running Snipe-IT on: Ubuntu 16.04.1 LTS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: asset list, people list, etc. 
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. It is.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by mw-christensen** [comment]
Yes please for all of this. Trying to navigate without being able to view column headers is super painful. The more custom fields you have the more painful this is.

**Comment by pogovault** [comment]
Agree with above, please consider adding this. It is very painful to navigate large list this way.
