### ISSUE TITLE
Upgrade from v3.6.6 to 4.0.9 results in Whoops Error / 500 Error

### ISSUE THREAD

**Issue by tzielinskiaptn** [snipe/snipe-it#4208]
#### Expected Behavior (or desired behavior if a feature request)

I expect to get the login page

-----

#### Actual Behavior

I get a whoops error/server 500 error

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade 
- Version of Snipe-IT you're running - 4.0.9
- Version of PHP you're running - 5.6.24
- Version of MySQL/MariaDB you're running - 10.0
- What OS and web server you're running Snipe-IT on Server 2012 R2 / IIS 8.5
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - 500 Error

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

I see this in my log:

[2017-10-12 17:57:27] production.ERROR: exception 'RuntimeException' with message 'The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.' in C:\inetpub\wwwroot\SnipeIT\vendor\laravel\framework\src\Illuminate\Encryption\Encrypter.php:43
Stack trace:
#0 C:\inetpub\wwwroot\SnipeIT\vendor\laravel\framework\src\Illuminate\Encryption\EncryptionServiceProvider.php(27): Illuminate\Encryption\Encrypter->__construct('APTNSecret54321...', 'AES-256-CBC')
#1 C:\inetpub\wwwroot\SnipeIT\vendor\laravel\framework\src\Illuminate\Container\Container.php(726): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#2 C:\inetpub\wwwroot\SnipeIT\vendor\laravel\framework\src\Illuminate\Container\Container.php(608): Illuminate\Container\Container->build(Object(Closure))
#3 C:\inetpub\wwwroot\SnipeIT\vendor\laravel\framework\src\Illuminate\Container\Container.php(575): Illuminate\Container\Container->resolve('encrypter')
#4 C:\inetpub\wwwroot\SnipeIT\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(728): Illuminate\Container\Container->make('encrypter')
#5 C:\inetpub\wwwroot\SnipeIT\vendor\laravel\framework\src\Illuminate\Container\Container.php(862): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#6 C:\inetpub\wwwroot\SnipeIT\vendor\laravel\framework\src\Illuminate\Container\Container.php(790): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#7 C:\inetpub\wwwroot\SnipeIT\vendor\laravel\framework\src\Illuminate\Container\Container.php(758): Illuminate\Container\Container->resolveDependencies(Array)
#8 C:\inetpub\wwwroot\SnipeIT\vendor\laravel\framework\src\Illuminate\Container\Container.php(608): Illuminate\Container\Container->build('App\\Http\\Middle...')
#9 C:\inetpub\wwwroot\SnipeIT\vendor\laravel\framework\src\Illuminate\Container\Container.php(575): Illuminate\Container\Container->resolve('App\\Http\\Middle...')
#10 C:\inetpub\wwwroot\SnipeIT\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(728): Illuminate\Container\Container->make('App\\Http\\Middle...')
#11 C:\inetpub\wwwroot\SnipeIT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(215): Illuminate\Foundation\Application->make('App\\Http\\Middle...')
#12 C:\inetpub\wwwroot\SnipeIT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(189): Illuminate\Foundation\Http\Kernel->terminateMiddleware(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#13 C:\inetpub\wwwroot\SnipeIT\public\index.php(63): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#14 {main}  

- Include what you've done so far in the installation, and if you got any error messages along the way.

I followed the upgrade instructions, step by step, and I generated the new app_key as per the instructions. I also copied the app_key value from my backup .env file into the Legacy_app_key of the new 4.0.9 .env file, and when I run the recrypt command I get:

ERROR: Your LEGACY_APP_KEY is not the correct length (32 characters or base64 followed by 44 characters for later versions). Please locate your old APP_KEY and use that as your LEGACY_APP_KEY in your .env file to continue.

I feel like I've missed a step, or buggered something up.

- Indicate whether or not you've manually edited any data directly in the database

I haven't manually updated any data directly in the database.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by tzielinskiaptn** [comment]
I have also cleared my browser cache, and tested it in a couple of different browsers on various machines.

**Comment by noizo** [comment]
https://snipe-it.readme.io/docs/upgrading-to-v4
You have to generate new app key

**Comment by tzielinskiaptn** [comment]
I did run the php artisan key:generate command and it returns a set successfully. When I do the recrypt command of my old app key I get that error about it not being the right length.

After I generate the key, do I need to put the new app key into my .env?

I apologize if this is a question that's already been asked. I don't think there are a lot of people running snipe-it in a Windows environment.

**Comment by snipe** [comment]
This doesn't really have anything to do with windows or not windows. You have to set your old env key as your APP_LEGACY_KEY. When you re-run `php artisan key:generate`, it *should* automatically update your APP_KEY to the newly generated value, but if it doesn't, you should put the new value in as your APP_KEY, and then run the recrypter.

**Comment by tzielinskiaptn** [comment]
Thank you for the help, putting the newly generated key value into the App_Key in the .env appears to have us up and running.

I did put our previous app key in the Legacy_App_Key but when I run the recrypter, I still get an error about incorrect key length, which leads me to believe that I had the wrong value in my app_key under the previous build.

Is there a way to test my upgraded deployment to ensure I won't get errors during future upgrades?

**Comment by snipe** [comment]
If your app loads successfully now, you should be fine.
