### ISSUE TITLE
After signing for an asset where does the record of that go?

### ISSUE THREAD

**Issue by eyetataks** [snipe/snipe-it#4209]
#### Expected Behavior (or desired behavior if a feature request)

how do you bring up a history of the signatures to show yes indeed person A signed for this asset?
neat feature but for the life of me I can't find where it stores those events.

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by madd15** [comment]
You can see if someone has accepted an asset by click on the asset and going to the history tab
![assetview](https://user-images.githubusercontent.com/3274937/31547331-75285e10-b06e-11e7-8dbe-3462e91bef6e.PNG)

also you can see unaccepted assets under reports
![unacceptedassets](https://user-images.githubusercontent.com/3274937/31547387-ae3c19bc-b06e-11e7-8113-74e3d4e3a970.png)
