### ISSUE TITLE
LDAP settings revert after saving changes

### ISSUE THREAD

**Issue by wonkasan** [snipe/snipe-it#4210]
#### Expected Behavior (or desired behavior if a feature request)

My LDAP settings do not revert

-----

#### Actual Behavior

Any entries I save appear to be reverted when I next open the LDAP settings page. I made some changes and was able to successfully sync ~ 2300 users over LDAP, but I was unable to log in with my AD password (it simply timed out). When I checked the LDAP settings page, all of my changes were reverted to what they were previously when LDAP was failing.

To make changes, I have been entering items and hitting "save." 

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
  - git pull upgrade
- Version of Snipe-IT you're running
  - Version v4.0.9 build 215 (g36cbffa)
- Version of PHP you're running
  - 7.0.22-0ubuntu0.17.04.1
- Version of MySQL/MariaDB you're running
  - mysql-5.7.19-0ubuntu0.17.04.1
- What OS and web server you're running Snipe-IT on
  - Ubuntu 17.04, apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  - git clone
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
  - no errors seen
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
  - /admin/ldap
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
  - not available
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
  - no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Can you tell me how many records you have in your Settings table?

**Comment by wonkasan** [comment]
| settings                     | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |            0 |         0 |              2 | 2017-09-26 15:08:40 | 2017-10-12 14:44:39 | NULL       | utf8mb4_unicode_ci |     NULL |  

Is that what you were looking for?

**Comment by snipe** [comment]
I’n Not sure what those columns translate to. Try `select count(*) from settings` and tell me what it says.

**Comment by wonkasan** [comment]
mysql> select count(*) from settings;
+----------+
| count(*) |
+----------+
|        1 |
+----------+
1 row in set (0.00 sec)

**Comment by snipe** [comment]
That’s helpful, thank you :) I wasn’t sure if maybe it was pulling from a duplicate record. One record is the correct number of records, so that’s good. I’ll take a look and see if I can reproduce this locally. I can’t think of any reason why this would be happening, but I can check it out when I get back in front of my laptop.

**Comment by snipe** [comment]
Question - prior to the sync, when you hit save, if you navigate away from the LDAP settings page and then try to edit them again, are they reverting there? Or only when you sync?

**Comment by wonkasan** [comment]
They were reverting before we had a successful sync. I had one of our IT folks sitting with me crafting an LDAP filter and we had to constantly re-enter all of our information until the sync worked. As a side note, "Test LDAP" always returned a red triangle with an exclamation even when the sync actually worked.

**Comment by wonkasan** [comment]
To be clear, even after the successful sync, they're still reverting. I opened this ticket because I suspect that's the reason nobody can log in using their domain password.

**Comment by snipe** [comment]
I can't reproduce this locally. Is it all of the LDAP settings, or just a particular one that's reverting?

**Comment by wonkasan** [comment]
All settings are reverting. The changed settings appear briefly on the page before they revert to the previous settings. 

Is there some instrumentation or debug code I can enable to create logs?

**Comment by pvhkai** [comment]
Hi,

I have the same issue - no test is possible (also see the red triangle since the update to Ver.4). I opened another thread about the issue a few days ago. (https://github.com/snipe/snipe-it/issues/4050) I got the error also by scripting the LDAP sync... :(

Best regards

**Comment by snipe** [comment]
@wonkasan Are you sure there isn't a browser plugin that's storing the form details. The fact that the updated info appear briefly sounds like the symptom of some browser/plugin based autocomplete functionality.

**Comment by wonkasan** [comment]
Good point. I will check, although this was happening across multiple systems. If so, then I still have an issue where synced users cannot log in with their domain information. If that's the case, I'll open a different ticket.

**Comment by wonkasan** [comment]
@snipe good call. I checked on IE, which I never use, and the results are as I expect. I apologize for not realizing this sooner. I'll open a new ticket for login failures through ldap.

**Comment by snipe** [comment]
@wonkasan I just added an `autocomplete=off` field to the forms in the settings section - let me know if that helps.

**Comment by wonkasan** [comment]
Doesn't seem to make a difference for me on Chrome, latest release. I have no idea what tool is doing the autocomplete; I'll need to investigate that.

**Comment by snipe** [comment]
Harumpf.

**Comment by snipe** [comment]
You know what... I wonder if [this](https://stackoverflow.com/questions/15738259/disabling-chrome-autofill) might be related. We *do* have a password on that page, so Chrome might be trying to be clever there.
