### ISSUE TITLE
/admin/backups not working if on socket?

### ISSUE THREAD

**Issue by noizo** [snipe/snipe-it#4211]
Hi.

I'm on latest `Version v4.0.9 build 215 (g36cbffa)` of snipeitapp.

I'm connecting to db through socket.
My connections string in `.env` is
`DB_SOCKET='/cloudsql/gcp-inventory:europe-west1:inventory-db'`
&
`DB_DUMP_PATH='/usr/bin/'` where `mysqldump` is located.

Backups won't create any DB dump files, as well as `.env`
`ll /var/www/html/storage`
```
drwxr-xr-x  8 www-data www-data 4096 Oct 13 09:12 ./
drwxr-xr-x 18 www-data www-data 4096 Oct 13 09:16 ../
drwxr-xr-x  3 www-data www-data 4096 Oct 13 08:59 app/
drwxr-xr-x  2 www-data www-data 4096 Oct 13 08:59 debugbar/
drwxr-xr-x  5 www-data www-data 4096 Oct 13 08:59 framework/
drwxr-xr-x  3 www-data www-data 4096 Oct 13 09:12 laravel-backups/
drwxr-xr-x  2 www-data www-data 4096 Oct 13 09:06 logs/
-rw-r--r--  1 www-data www-data 3292 Oct 13 09:08 oauth-private.key
-rw-r--r--  1 www-data www-data  812 Oct 13 09:08 oauth-public.key
drwxr-xr-x  8 www-data www-data 4096 Oct 13 08:59 private_uploads/
```
`ll /var/www/html/storage/app/`
```drwxr-xr-x 3 www-data www-data 4096 Oct 13 08:59 backups/```

If i will run `mysqldump` manually, i can backup DB as expected.
`mysqldump --set-gtid-purged=OFF -u snipeit -psomestrongpass -S /cloudsql/gcp-inventory\:europe-west1\:inventory-db snipeit > /opt/snipeit.sql`

Any suggestions?

**Comment by snipe** [comment]
No idea. Sounds like maybe an issue with the backup package (spatie/laravel-backups)

**Comment by snipe** [comment]
This looks like this issue was fixed a long time ago in spatie/laravel-backup.

https://github.com/spatie/laravel-backup/issues/24

What's the output on the screen when you try to run the backup via cli?

**Comment by snipe** [comment]
Haven't heard back, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
