### ISSUE TITLE
3 "Check Out" Fields when create an assets after Upgrade to 4.0.9

### ISSUE THREAD

**Issue by ArcheNoah77** [snipe/snipe-it#4212]
#### Expected Behavior (or desired behavior if a feature request)

Create a new Asset:
chance the status to "einsetzbar".
One Field appears, where I select a User, who should get the asset

-----

#### Actual Behavior

Create a new Asset
chance the status to "einsetzbar"
Three Fields appears... in the second "Check Out" Field, I can select nothing, in the thrid field, i can select "LDAP1"

![2](https://user-images.githubusercontent.com/25475591/31543624-45cff08a-b017-11e7-87e7-18004ed6a2bd.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade from 3.6.6 -> 4.0.9
- Version of Snipe-IT you're running # 4.0.9
- Version of PHP you're running # 5.6
- Version of MySQL/MariaDB you're running # MySQL 5.5
- What OS and web server you're running Snipe-IT on # Ubuntu and Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I don't really understand the issue here. Sounds like the user selection dropdown is being presented...
