### ISSUE TITLE
v4 small bug? checkin button says check out

### ISSUE THREAD

**Issue by calebs1** [snipe/snipe-it#4214]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)
checking asset back in. button should say check in.
-----

#### Actual Behavior

(what actually happens goes here)
button says check out
-----

#### Please confirm you have done the following before posting your bug report:

- [no ] I have enabled debug mode 
- [yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
upgrade
- Version of Snipe-IT you're running
4.09
- Version of PHP you're running
7.0.22
- Version of MySQL/MariaDB you're running
10.0.31
- What OS and web server you're running Snipe-IT on
ubuntu 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
from asset page, edit asset, check in, the checkin screen where you can set the new status the button says check out.
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
no
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
attached
- Include what you've done so far in the installation, and if you got any error messages along the way.
i didnt do the initial install. trying to contact them to get some specifics
- Indicate whether or not you've manually edited any data directly in the database
no

here is a screen shot of what i am seeing.

![image](https://user-images.githubusercontent.com/26014066/31557826-3e6b5af4-afff-11e7-8dc4-b1e2aa444073.png)
[laravel.log](https://github.com/snipe/snipe-it/files/1383415/laravel.log)

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by madd15** [comment]
This should be fix soon as it was part of #4213 which was applied to the develop branch
