### ISSUE TITLE
404 error when trying to delete category

### ISSUE THREAD

**Issue by cis4smack** [snipe/snipe-it#4216]
#### Expected Behavior (or desired behavior if a feature request)
I am trying to delete a category that has no assets associated with. 

-----

#### Actual Behavior

When I try to delete the category it gives me a 404 error message.

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Upgrade from 3.6.4
- Version 4.0.9
- Version PHP 5.6.31
-  5.5.56-MariaDB
- Centos 7 and Apache
- Before upgrade install.sh then git clone upgrade path to new version.
- WITH DEBUG TURNED ON, just 404 error

I see this as an exception

`
/var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php#179
Symfony\Component\HttpKernel\Exception\NotFoundHttpException`

**Comment by madd15** [comment]
Possible old route deleting a categories takes you to `/admin/settings/categories`

**Comment by dmeltzer** [comment]
Where are you deleting it from?

**Comment by cis4smack** [comment]
I am do it from the browser. Go to setting -> Categories and then trying to delete.

If I create a category and delete it, it doesn’t give me an error.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
