### ISSUE TITLE
"No matching records found" on Recent Activity

### ISSUE THREAD

**Issue by User330022** [snipe/snipe-it#4219]
#### Actual Behavior

No matching records found on Recent Activity. This problem occurs after upgrading from 3.6.2 to 3.6.6. Now after upgrading from 3.6.6 to 4.09 still the same problem exist.
-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? --> 3.6.6 to 4.0.9 upgrade
- Version of Snipe-IT you're running  --> 4.0.9
- Version of PHP you're running --> 5.6.24
- Version of MySQL/MariaDB you're running --> 10.1.8.0
- What OS and web server you're running Snipe-IT on --> Windows Server 2008 R2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) --> Manual

Same error on debug console and laravel.log -->
production.ERROR: exception 'UnexpectedValueException' with message 'The Response content must be a string or object implementing __toString(), "boolean" given.' in C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php:15996
Stack trace:
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(16407): Symfony\Component\HttpFoundation\Response->setContent(false)
#1 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(15901): Illuminate\Http\Response->setContent(Array)
#2 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(8373): Symfony\Component\HttpFoundation\Response->__construct(Array)
#3 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9466): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Array)
#4 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#5 C:\inetpub\wwwroot\snipe-it-master\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#6 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#7 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#8 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9467): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#9 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9454): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\ReportsController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'getActivityRepo...')
#10 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(8524): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'getActivityRepo...')
#11 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(8511): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))
#12 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(8225): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#13 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 C:\inetpub\wwwroot\snipe-it-master\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#15 C:\inetpub\wwwroot\snipe-it-master\app\Http\Middleware\CheckPermissions.php(28): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 [internal function]: App\Http\Middleware\CheckPermissions->handle(Object(Illuminate\Http\Request), Object(Closure), 'reports.view')
#17 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#18 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 C:\inetpub\wwwroot\snipe-it-master\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 C:\inetpub\wwwroot\snipe-it-master\app\Http\Middleware\Authenticate.php(45): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 [internal function]: App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#23 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 C:\inetpub\wwwroot\snipe-it-master\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 C:\inetpub\wwwroot\snipe-it-master\app\Http\Middleware\CheckForTwoFactor.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 [internal function]: App\Http\Middleware\CheckForTwoFactor->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 C:\inetpub\wwwroot\snipe-it-master\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 C:\inetpub\wwwroot\snipe-it-master\app\Http\Middleware\CheckLocale.php(42): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 [internal function]: App\Http\Middleware\CheckLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 C:\inetpub\wwwroot\snipe-it-master\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(3225): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#38 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 C:\inetpub\wwwroot\snipe-it-master\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(13213): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#43 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 C:\inetpub\wwwroot\snipe-it-master\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(13150): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 C:\inetpub\wwwroot\snipe-it-master\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#52 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(8226): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#53 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(8217): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#54 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(8207): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#55 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(2419): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#56 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#57 C:\inetpub\wwwroot\snipe-it-master\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#58 C:\inetpub\wwwroot\snipe-it-master\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 [internal function]: App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#61 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 C:\inetpub\wwwroot\snipe-it-master\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#63 C:\inetpub\wwwroot\snipe-it-master\vendor\fideloper\proxy\src\TrustProxies.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#64 [internal function]: Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#66 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 C:\inetpub\wwwroot\snipe-it-master\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#68 C:\inetpub\wwwroot\snipe-it-master\app\Http\Middleware\CheckForSetup.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 [internal function]: App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#71 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 C:\inetpub\wwwroot\snipe-it-master\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#73 C:\inetpub\wwwroot\snipe-it-master\app\Http\Middleware\NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#74 [internal function]: App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#75 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#76 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 C:\inetpub\wwwroot\snipe-it-master\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#78 C:\inetpub\wwwroot\snipe-it-master\app\Http\Middleware\XssProtectHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#79 [internal function]: App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#80 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#81 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#82 C:\inetpub\wwwroot\snipe-it-master\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#83 C:\inetpub\wwwroot\snipe-it-master\app\Http\Middleware\FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#84 [internal function]: App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#85 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#86 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#87 C:\inetpub\wwwroot\snipe-it-master\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#88 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(13474): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#89 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#90 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#91 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#92 C:\inetpub\wwwroot\snipe-it-master\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#93 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(11964): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#94 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#95 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#96 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#97 C:\inetpub\wwwroot\snipe-it-master\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#98 C:\inetpub\wwwroot\snipe-it-master\vendor\misterphilip\maintenance-mode\src\MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode.php(145): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#99 [internal function]: MisterPhilip\MaintenanceMode\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#100 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9963): call_user_func_array(Array, Array)
#101 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#102 C:\inetpub\wwwroot\snipe-it-master\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#103 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#104 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(9948): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#105 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(2366): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#106 C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php(2350): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#107 C:\inetpub\wwwroot\snipe-it-master\public\index.php(60): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#108 {main}

**Comment by User330022** [comment]
![image](https://user-images.githubusercontent.com/15626677/31608584-6dc35ec4-b279-11e7-9b24-ea34eb592925.png)

**Comment by snipe** [comment]
What happens if you remove `C:\inetpub\wwwroot\snipe-it-master\bootstrap\cache\compiled.php`?

**Comment by User330022** [comment]
Hi,
Actually there aren't any compiled.php on that location. For test purposes I copied old compiled.php file from backup to that folder and then i got the HTTP ERROR 500.

**Comment by snipe** [comment]
You shouldn't ever copy over old compiled files.

**Comment by snipe** [comment]
I still can't reproduce this. Can you try upgrading to latest?

**Comment by User330022** [comment]
I just upgraded to the latest (v4.0.13 build 273 (gab3f5f4)) and still the same problem and still same errors on laravel log -> **[2017-10-19 13:59:26] production.ERROR: exception 'UnexpectedValueException' with message 'The Response content must be a string or object implementing __toString(), "boolean" given.' in C:\inetpub\wwwroot\snipe-it-master\vendor\symfony\http-foundation\Response.php:409**

I got this problem first time when updated to 3.6.6 and on that version there's "Asset Tag autoincrement stopped working after update to 3.6.6" bug. I had to disable the asset id autogeneration. Now i tried to disable/enable autogeneration, change Next auto-increment value, Prefix (optional) velue and Length of asset tags, including zerofill value, but always the same problem: "No matching records found" on Recent Activity

**Comment by snipe** [comment]
Try running `php upgrade.php` - it will clear out some old cached files. That's the only thing I can think of. I've never seen this error before.

**Comment by User330022** [comment]
Tried that but still the same problem :(

**Comment by User330022** [comment]
What!? Everything is working fine now! (No errors on laravel.log)
I just cleaned (deleted) some old software licenses and after that everything started to work again. I don't know what happened, but it is ok to close this case now :)
