### ISSUE TITLE
Upon log on getting error "The requested URL /admin/components was not found on this server." after trying to get to any page from Dashboard. 

### ISSUE THREAD

**Issue by saviressej** [snipe/snipe-it#4221]
Logging on is ok. Once trying to get to any other page I get the following 404 Not Found error: "The requested URL /admin/components was not found on this server." This is on an instance that has been working for months

I have enabled debug mode. No error code. I did check the Common issues but didn't see anything related to this.

This isn't a fresh install or upgrade. Running v3.6.4 build 12 (gf7e4fca)
Any ideas?

**Comment by snipe** [comment]
I have no idea. I don't think that URL should be pointing to /admin/components, probably just /components, but I don't know why that would have changed for you if you haven't changed anything. 

You can always try the trust artisan clearing stuff:

```
php artisan config:clear
php artisan cache:clear
php artisan route:clear
php artisan view:clear
```

**Comment by saviressej** [comment]
I will try that It is strange. Every page I try to go to I get the 404 not
found. Here are some examples:

The requested URL /hardware was not found on this server.
The requested URL /admin/licenses was not found on this server.

On the Dashboard the Recent Activity section is empty.

**Comment by saviressej** [comment]
More info. None of the pages work. Even the /login and /logout pages

**Comment by snipe** [comment]
Is it possible you managed to stomp on the htaccess or something? Something must have changed on your end, since you haven't updated anything.

**Comment by snipe** [comment]
Haven't heard back, so I'm going to close this ticket for now, but will re-open it if you're still having issues
