### ISSUE TITLE
Logrotate laravel.log (in Windows)

### ISSUE THREAD

**Issue by diekmanu** [snipe/snipe-it#4226]
Laravel.log grows pretty large over time. I know in Linux syslog / systemd-journal can take care of rotating the file. Is there any equivalent in Windows. Some Laravel option perhaps?

Thanks.

**Comment by madd15** [comment]
@diekmanu you can set the logs to daily in the `.env` file
```
# --------------------------------------------
# OPTIONAL: MISC
# --------------------------------------------
APP_LOG=daily
```

**Comment by diekmanu** [comment]
This is so much more convenient. Thanks @madd15 @snipe
