### ISSUE TITLE
Archived Assets Appearing in Asset List

### ISSUE THREAD

**Issue by PixelDJ** [snipe/snipe-it#4228]
#### Expected Behavior (or desired behavior if a feature request)

When going to the List All asset list, I expect to see all assets except for Archived assets. The documentation states for Archived assets: "These assets cannot be assigned to people, and will only show up in the Archived view"

There used to be a fix for this by editing the AssetsController.php file and adding a default entry to be "NotArchived", but I can't seem to find where to do this now. Is there a setting somewhere that I'm missing?

-----

#### Actual Behavior

All assets, even archived, are showing up on the asset list.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running: v4.0.10 build 235 (gcbe008d)
- Version of PHP you're running: 7.0.22
- Version of MySQL/MariaDB you're running: 10.0.31
- What OS and web server you're running Snipe-IT on: Ubuntu 16.04.3 with Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: /hardware
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. Yes
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
This should be fixed on develop and master now

**Comment by snipe** [comment]
The option to include or exclude Archived assets in the List All/Search is now on the develop branch, in the Settings > General UI.

**Comment by RussellLeVasseur** [comment]
It looks like this might potentially be happening again with the new SnipeIT version 6.0.0
