### ISSUE TITLE
Create Asset/Update Asset has different options under Model section

### ISSUE THREAD

**Issue by joseph707** [snipe/snipe-it#423]
hi snipe

good morning. I have come across this and not sure if this is an issue.

When I create a new asset, under the Model Section, I see the model as well as the corresponding model number. Screenshot below
![capture1](https://cloud.githubusercontent.com/assets/9422649/5483667/039f7950-8690-11e4-848c-3305874a7854.JPG)

But when I try to edit the Model with another model, I don't seem to find the corresponding value. Screenshot below. Is this by design?

![2](https://cloud.githubusercontent.com/assets/9422649/5483712/0f88d120-8691-11e4-9e7c-fbcdac1421e2.JPG)

Thanks for your support and good work.

regards

jo

**Comment by joseph707** [comment]
hi snipe

good morning. I am sure the process to report this issue is not right but I hope you consider this as an update for your next release. Didn't mention this previously and I closed this way in December.

regards

joseph

**Comment by snipe** [comment]
Hi @joseph707 - we'll definitely try to get that in for Friday's release. In the future, a pull request would have made this a lot easier, and it would have been merged in back in December. :)

**Comment by joseph707** [comment]
Hi snipe

Yeah, I should have done that. But will ensure this next time. Learning a lot.

Excellent product.
Regards

Sent from my Windows Phone




Joseph Varghese
ICT Administrator


Telephone (Direct) :+971 6 5993 202 |Mobile :+971 50 789 5163 |E-mail :varghese.joseph@viss.ae

Switchboard : +971 6 577 1999; Fax: +971 6 577 1888 | PO Box 68600, Al Mamzar, Sharjah, UAE | Web: www.viss.ae
Victoria International School of Sharjah

-----Original Message-----

**Comment by snipe** [comment]
No worries :)
