### ISSUE TITLE
Feature request: Shifting from Laravel to Go Framework 

### ISSUE THREAD

**Issue by raakhtar** [snipe/snipe-it#4233]
feature label:"feature request"
@snipe would you be considering moving away from Laravel framework to Go Framework due to massive performance increase

<img width="725" alt="screen shot 2017-10-18 at 12 40 34 am" src="https://user-images.githubusercontent.com/1447175/31688308-0948d120-b39d-11e7-9f8d-916d006a18cd.png">

Reference
https://dannyvankooten.com/laravel-to-golang/

**Comment by snipe** [comment]
I would not consider that at this time.

**Comment by snipe** [comment]
(That sounds like a server tuning issue. We run plenty of people on the same box without issues.)
