### ISSUE TITLE
Error Exception when syncing ldap by location OU

### ISSUE THREAD

**Issue by rjdeclute** [snipe/snipe-it#4247]
#### Expected Behavior (or desired behavior if a feature request)
Import users by location OU
(what you expect to happen goes here)
Import users by location OU
-----

#### Actual Behavior

(what actually happens goes here)

(1/1) ErrorException 

ldap_search(): Search: Invalid DN syntax
 
in Ldap.php (line 262) 

at HandleExceptions->handleError(2, 'ldap_search(): Search: Invalid DN  syntax', 'C:\\inetpub\\wwwroot\\inventory\\app\\Models\\Ldap.php', 262, array('base_dn' => 'sunnybrook', 'ldapconn' => resource, 'ldap_bind' => null, 'filter' => '&(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))', 'page_size' => 500, 'cookie' => '', 'result_set' => array(), 'global_count' => 0, 'ldap_paging' => true)) 

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode - yes
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) - yes

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running 4.13
- Version of PHP you're running 7.1.7
- Version of MySQL/MariaDB you're running  MySQL 5.7.19
- What OS and web server you're running Snipe-IT on Windows Server 2012
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Git Clone
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

(1/1) ErrorException 
ldap_search(): Search: Invalid DN syntax
 in Ldap.php (line 262) 
at HandleExceptions->handleError(2, 'ldap_search(): Search: Invalid DN syntax', 'C:\\inetpub\\wwwroot\\inventory\\app\\Models\\Ldap.php', 262, array('base_dn' => 'sunnybrook', 'ldapconn' => resource, 'ldap_bind' => null, 'filter' => '&(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))', 'page_size' => 500, 'cookie' => '', 'result_set' => array(), 'global_count' => 0, 'ldap_paging' => true)) 

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. - no
- Indicate whether or not you've manually edited any data directly in the database - no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I'm not sure what you're asking here. It's telling you what's wrong - the DN syntax is incorrect. 

DN's represent the full path to the object - so should be something like this:

"cn=username,ou=domain users,dc=sunnybrook,dc=com"

Depending on how your LDAP is set up.

**Comment by snipe** [comment]
Haven't heard back, so I'm going to close this ticket for now, but will re-open it if you're still having issues
