### ISSUE TITLE
Asset list shows default location under location column

### ISSUE THREAD

**Issue by PixelDJ** [snipe/snipe-it#4249]
#### Expected Behavior (or desired behavior if a feature request)
I expect the asset list to show the actual location of the asset as shown on the individual asset page.

-----

#### Actual Behavior
The asset page shows the default location of the asset under the location column.
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running: v4.0.13 build 273 (gab3f5f4)
- Version of PHP you're running: PHP 7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running: 10.1.28-MariaDB
- What OS and web server you're running Snipe-IT on: Ubuntu 16.04.3/Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc). install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error. /hardware
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. Not sure. Demo is in another language right now and doesn't seem to want to change back.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
> I expect the asset list to show the actual location of the asset as shown on the individual asset page.

How are you defining the "actual" location?

**Comment by snipe** [comment]
So, it already does that. See https://demo.snipeitapp.com/hardware/3

The user's location is West Emmanual, the default asset location is Vilmaborough.

<img width="281" alt="screen shot 2017-10-18 at 4 03 59 pm" src="https://user-images.githubusercontent.com/197404/31746785-fdb97586-b41d-11e7-91e3-5e4c073fe1e1.png">

<img width="449" alt="screen shot 2017-10-18 at 4 03 38 pm" src="https://user-images.githubusercontent.com/197404/31746773-f126dfde-b41d-11e7-9bc0-67a7fbaaec44.png">
