### ISSUE TITLE
FEATURE REQUEST: don't display encrypted fields by default

### ISSUE THREAD

**Issue by TonisOrmisson** [snipe/snipe-it#4251]
I wish the encrypted fields would not show up on screen as plain text by default. 

Encrypted fields often hold sensitive information and I think it would be a good idea to have them hidden by default and have a button "Show value" or something to display the content after clicking on it (JS?)

Maybe this could be turned on-off via global settings. And/or custom field settings?

**Comment by snipe** [comment]
@TonisOrmisson Only super admins can see the contents of encrypted fields.

**Comment by TonisOrmisson** [comment]
Yes, sure. But I would prefer an encrypted field to be visible only if you specifically request it. 

Right now Let's say I store some asset passwords. While searching assets I get listed a bunch of passwords on the screen. Also any time I open an asset to do something (whatever) the encrypted fields are displayed on screen. And now put yourself in an open office. Or an office layout where visibility to your screen is accessible to any other users. 

I still think it would be better to have an option at least not to display encrypted stuff just by default in various places where you actually might not wan to use the encrypted field.
