### ISSUE TITLE
FEATURE REQUEST: return asset search if no asset is found by tag

### ISSUE THREAD

**Issue by TonisOrmisson** [snipe/snipe-it#4253]
If the asset is not found by the tag and direct match. It would be convenient if the system would respond with an asset search instead.

**Comment by snipe** [comment]
Not sure what you mean by "respond with an asset search". The "no results" page shows you the asset search at the top of the table.

**Comment by TonisOrmisson** [comment]
I mean: it the asset is not found by direct tag match, a search would be executed and the search by the entered tag would be returned. Currently yes I get a the search view but not with the tag I just submitted (and did not find). Th search view uses some last used search (session?) but it would be convenient to use the searched tag as the search string.
