### ISSUE TITLE
FEATURE REQUEST: Checkout asset-to-asset dropdown show tags

### ISSUE THREAD

**Issue by TonisOrmisson** [snipe/snipe-it#4254]
The dropdown selection asset-top-asset checkout should also display (and search) by asset tag name since tag is the main identifier for assets.

**Comment by TonisOrmisson** [comment]
I mean eg create-asset view

**Comment by TonisOrmisson** [comment]
Like its in the general checkout form, the same way

**Comment by snipe** [comment]
This has been pushed into the last release or two.
