### ISSUE TITLE
Visual bug in bulk checkin & delete

### ISSUE THREAD

**Issue by Diniver** [snipe/snipe-it#4256]
Hello all,

I found small visual bug: 
![image](https://user-images.githubusercontent.com/31882138/31762414-fe34b058-b4b2-11e7-90ec-10cd744ae5ef.png)

Version v4.0.13 build 273 (gab3f5f4)

**Comment by snipe** [comment]
What page are you on where you see this?

**Comment by Diniver** [comment]
When i open Current users, select few and choose bulk checkin & delete
/users/bulkedit
