### ISSUE TITLE
error running php composer.phar install

### ISSUE THREAD

**Issue by ralphsclub** [snipe/snipe-it#426]
I'm installing this on OS X running apache
Snipe-IT version 1.1

Script php artisan debugbar:publish handling the post-install-cmd event returned with an error
[RuntimeException]                                                                                                      
  Error Output: PHP Parse error:  parse error, expecting `')'' in /Library/Server/Web/Data/Sites/SnipeIT/bootstrap/start  
  .php on line 58

Line 58
$framework = $app['path.base'].'/vendor/laravel/framework/src';

Lines 47 - 73
/*
|--------------------------------------------------------------------------
| Load The Application
|--------------------------------------------------------------------------
|
| Here we will load the Illuminate application. Well keep this is in a
| separate location so we can isolate the creation of an application
| from the actual running of the application with a given request.
|
*/

$framework = $app['path.base'].'/vendor/laravel/framework/src';

require $framework.'/Illuminate/Foundation/start.php';

/*
|--------------------------------------------------------------------------
| Return The Application
|--------------------------------------------------------------------------
|
| This script returns the application instance. The instance is given to
| the calling script so we can separate the building of the instances
| from the actual running of the application and sending responses.
|
*/

return $app;

**Comment by snipe** [comment]
@ralphsclub Are you still having this issue with later versions of Snipe-IT?
