### ISSUE TITLE
Feature Request: Bulk checkout only availble for users

### ISSUE THREAD

**Issue by TonisOrmisson** [snipe/snipe-it#4263]
Checking assets out to other assets/locations etc has been made available. But is not implemented for bulk checkout.

related to #3343

**Comment by kagashe** [comment]
+1 For this I sometimes checkout 30 assets at a time, and this will make it waaaaaay easier.

**Comment by MSTigers** [comment]
+1 we do a lot of location-based checkouts as opposed to user. Prime example being classroom Chromebooks. Teachers move around, we'll not have assets follow them. While we can bulk update the default locations (YAY!) it does make it difficult to checkout many assets to a location.

Thankfully the checkout process is very streamlined so I can breeze through them. But still there's approx. 320 devices I'm working on in this batch which increases the chance of human error in this process when handling each one individually.

**Comment by tantonw** [comment]
Another +1 for this feature.  We're an EDU and this would make checking out assets to lab spaces much easier.

**Comment by snipe** [comment]
This feature is now on master.
