### ISSUE TITLE
Strange error on Import that is not preventing Import from working (I am not the admin)

### ISSUE THREAD

**Issue by psychomagi** [snipe/snipe-it#4264]
#### Expected Behavior (or desired behavior if a feature request)

I go to click Process on Import File and a Header Field and Import Field section appears. The Import Section has drop downs. I make them match up and click Import. It imports successfully without error. (I assume these drop downs and new steps on import are new and intentional?)

-----

#### Actual Behavior

The items ARE being imported and nothing looks incorrect, but I am still getting an error of:
Item     Errors 
            Asset "": The model id field is required.The asset tag field is required. 

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode (I do not know how)
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions: (I am not the admin, just a 3rd party user)

- Is this a fresh install or an upgrade? Assuming its an upgrade as it wasn't importing this way prior.
- Version of Snipe-IT you're running - Version v4.0.13 build 273 (gab3f5f4)
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on - Firefox on Windows 10
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - In the past, yes.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
@dmeltzer can you take a look?

**Comment by dmeltzer** [comment]
Do you have a blank line in your csv?

**Comment by psychomagi** [comment]
No, I always have titles (Header Field) in Row 1 and all data streaming down from row two with no gaps.

Also just to add it here, I mentioned in chat also that Locations which are still present when adding an asset are not loading in settings>Locations (nothing is appearing and it is empty), and at one point while trying to load Locations I got a 504 gateway error and the site timed out. Not sure it is linked to this or not but wanted it brought to your attention.
