### ISSUE TITLE
Record timestamp with expected checkin

### ISSUE THREAD

**Issue by ciasaboark** [snipe/snipe-it#4265]
#### Expected Behavior (or desired behavior if a feature request)

It would be nice if snipe-it accepted a datetime value for the expected_checkin field instead of just a date when checking out assets.  Currently the REST API discards the time part.

We use snipeit (and an android app using the new 4.0 REST API) to handle checking out equipment to a large number of warehouse associates.  The associates only need the assets for the length of their shift, so the expected_checkin values are set as now + 24 hours.

Since snipe-it discards the time part of the expected_checkin this can result in an associate checking out an asset at 11PM, then snipe-it recording the expected checkin as one hour from then.

Looking at the database schema this would require a change to (at least) the assets table.

-----

#### Actual Behavior

REST API discards time part of expected_checkin field.
Database schema assets.expected_checkin uses date data type instead of datetime

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running 4.09 (also 3.6.6)
- Version of PHP you're running 
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Try and pull the latest version - we've made some changes to how expected_checkin date is handled.

**Comment by ciasaboark** [comment]
No luck.

I upgraded to version v4.1.6 - build 2939 using the upgrade.php method and tested checking out an asset.

The asset is checked out using params `user_id=1&checkout_at=2017-11-22 19:35:28&expected_checkin=2017-11-23 19:35:28` (url encoding stripped here).

When I pull the data the expected checkin field for that asset only has a date field, no time associated

```json
{
      ...snip
      "expected_checkin": {
        "date": "2017-11-23",
        "formatted": "2017-11-23"
      },
      "id": 3,
      ...snip
    }
```

I checked the database to make sure the information was not being stripped, but it looks like the schema still uses a date field instead of a datetime.

```bash
MariaDB [snipeit4]> select id, expected_checkin from assets where id = 3;
+----+------------------+
| id | expected_checkin |
+----+------------------+
|  3 | 2017-11-23       |
+----+------------------+
1 row in set (0.00 sec)

MariaDB [snipeit4]> SELECT DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS    WHERE table_name = 'assets' AND COLUMN_NAME = 'expected_checkin';
+-----------+
| DATA_TYPE |
+-----------+
| date      |
| date      |
+-----------+
2 rows in set (0.01 sec)

MariaDB [snipeit4]> 
```

**Comment by snipe** [comment]
I wasn't proposing that we'd add a time, just that we better handle the dates as actual dates (instead of a a date time that isn't really a datetime, leading to the weird 00:00:00 timestamps.)

**Comment by ciasaboark** [comment]
If the datatype is not going to change that's fine.  I'll find a way to work around that.

Closing bug.
