### ISSUE TITLE
EOL For Models

### ISSUE THREAD

**Issue by MattMarchy** [snipe/snipe-it#4269]
Expected Behavior (or desired behavior if a feature request)

Would be great if we could put actual dates in the EOL field for models instead of giving the actual EOL in months.

Actual Behavior

EOL Can only be used from the months the devices is put on the system and not the recorded date by the developer.

Please confirm you have done the following before posting your bug report:

 I have enabled debug mode
 I have read checked the Common Issues page
Provide answers to these questions:

Is this a fresh install or an upgrade?
Version of Snipe-IT you're running 4.09 (also 3.6.6)
Version of PHP you're running
Version of MySQL/MariaDB you're running
What OS and web server you're running Snipe-IT on
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
If a stacktrace is provided in the error, include that too.
Any errors that appear in your browser's error console.
Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
Include any additional information you can find in app/storage/logs and your webserver's logs.
Include what you've done so far in the installation, and if you got any error messages along the way.
Indicate whether or not you've manually edited any data directly in the database
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
So the reason we went with months instead of a specific date is just because most common hardware has an n-month warranty, and I didn’t ever want to be stuck doing the math as I was entering assets. If I have an invoice in my hand for aN MBP, and I know we always but extended Apple care, all I need to care about is the purchase date on the invoice. That was the reasoning

**Comment by MattMarchy** [comment]
But warranty is covered when you're creating the asset is it not? 

We've basically got a couple old iPhone's and I'm looking to put the date of when production was stopped for them, just for audit purposes.

Any other work arounds for this that you can think of?

**Comment by Gelob** [comment]
@MattMarchy you can ignore the EOL field and create a custom field to apply to that asset model.

**Comment by jessehazen** [comment]
Ran across this today & I agree with the original post that this should be a date, not a number of months. For example, Apple has discontinued support for the iPhone 5s on 2018-10-28, but an iPhone purchased on 2018-10-27 will not show as EOL, even though it will be shortly after purchase.

To clarify:

There is a warranty (months) field, on each asset, which covers any number of months. This is sufficient for every purchase I have seen..

There is a depreciation field on each model. This is a number of months, which helps us divide a purchase over time, and plan for scheduled replacement.

There is an EOL field on each model, however EOL in my experience points to a date - typically when a vendor stops providing hardware or software support for a product. An example of this is Apple, when they stop providing software updates to iPhones. Whenever Apple does this, it effectively makes the device EOL, regardless of purchase date. I could purchase any number iPhones of the same model, months or apart, and all should be able to share the same EOL date.

**Comment by asmith0176** [comment]
I want to request a change to this feature as well. The warranty field should suffice for warranty purposes as the date in months matters most as related to the purchase date. When I enter the EOL it addes a EOL date field to the Assest but I can only modify the EOL Months field. This is a problem for me as we are trying to create reports for rotating Chromebooks which all have hard EOL dates which you can see at this link (https://support.google.com/chrome/a/answer/6220366?hl=en) it makes much more since to me to be able to enter the date.

<blockquote><div><strong><a href="https://support.google.com/chrome/a/answer/6220366?hl=en">Auto Update policy - Google Chrome Enterprise Help</a></strong></div><div>Overview
Chrome devices (e.g. Chromebook, Chromebox, Chromebase, Chromebit) receive automatic updates that enhance both the device and its software. Device updates provide the latest features and kee</div></blockquote>

**Comment by Krejar** [comment]
I am going to be the person that is on the side of Snipe-IT and say I actually like how it is now. My company has an EOL of 72 months for assets regardless of when it was purchased or manufactured. Maybe in the future a Cycle Date can be added where that uses months and EOL can be changed to a date? Would that be better?

**Comment by andrewplotner** [comment]
Just came across this as well. Current company is HORRENDOUS at asset management and doing my best to get them up to snuff. They will buy equipment that has already had its EOL announced and is now encroaching on its End Of Service. While I completely understand and agree with the reasoning for making the EOL a set number of months. What i would like to see is an EOS field added to the asset model sheet and that field be a date, and include a notification feature associated with that. 

EDIT: A work around exists by creating a new fieldset that is added to the models. That field set needs to be associated with a field, you can do date or text. If you choose to do date, be aware that you then have to set the form element to textarea(multiline). The reason for this is that if you do text box and have a date, any default value you associate with the model doesn't autofill when you create an asset. The same is true with the listbox. If you wish to be able to set default values then create a fieldset End Of Life, associate it with a field "End of Life" make that field have a form element of textarea(multiline) with a format of date. When you create a model associate that field set with it and click the box next to use default value. This will allow you to place a date that will autofill whenever an asset is created with that model.  Be aware that this method does NOT apply the default setting to assets already created.  While this is a work around for new assets it would be nice if there were a more robust solution.

**Comment by ocstech** [comment]
I am coming across this as well. It would be nice to be able to set a date or month that is a hard line for the EOL for devices. This will be critical going forward where the devices are purchased in the middle of their expected EOL and do not have an EOL date that is accurate.

**Comment by ghost** [comment]
I have a large number of Chromebooks and I need to enter an EoL/Deprecation date for every device of that specific model, regardless of warranty period or purchase date. ChromeOS end-of-support (meaning no more OS updates) occurs simultaneously for all devices of a particular model regardless of purchase and warranty end date, even if the warranty continues beyond that date and realistically some devices may still be in use beyond the warranty period. I need to track firm replacement dates for them model-by-model for hundreds of devices.

See: https://support.google.com/chrome/a/answer/6220366?hl=en

Please add this support to allow setting an EoL date for every device of a particular model that is not tied to the warranty period or allow adding deprecations with firm dates that are not tied to asset purchase date or warranty period.
