### ISSUE TITLE
404 endpoint not found when creating new user while checking out asset

### ISSUE THREAD

**Issue by jeroen-track** [snipe/snipe-it#4271]
#### Expected Behavior (or desired behavior if a feature request)

When you checkout an asset you have the option to create a new user on the fly.
I expect a successful completion of the user form and the newly created user selected in the "Checkout to" field of the asset checkout form. 

-----

#### Actual Behavior

When clicking the save button on the create user popup form an error stating "404 endpoint not found" appears and the new user is not created. I can only leave this popup by cancelling the action.

-----

#### Please confirm you have done the following before posting your bug report:

- [ x ] I have enabled debug mode 
- [ x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? => fresh install
- Version of Snipe-IT you're running => v4.0.13 build 273 (gab3f5f4)
- Version of PHP you're running => 7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running => mariadb 10.1.28+maria-1~xenial
- What OS and web server you're running Snipe-IT on => ubuntu 16.04 (vagrant box bento/ubuntu-16.04) with apache 2.4.18-2ubuntu3.5
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) => install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error => Server error: 4040 endpoint not found
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error => expected and actual behaviour description
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. =>
POST http://vagrant.vm:8888/hardware/api/v1/users 404 (Not Found)
(anonymous)
  | send | @ | all.js:3
  | ajax | @ | all.js:3
  | (anonymous) | @ | all.js:26
  | dispatch | @ | all.js:2
  | m.handle | @ | all.js:2

- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. => yes
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. => nothing special added a few assets added a few user no errors seen.
- Indicate whether or not you've manually edited any data directly in the database => no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help
<img width="1090" alt="screen shot 2017-10-20 at 14 26 29" src="https://user-images.githubusercontent.com/17066422/31822982-de820c4e-b5aa-11e7-8852-42b3faf5e4dd.png">

**Comment by mylanch** [comment]
I have the same problem.

**Comment by snipe** [comment]
This is fixed on develop, not merged to master yet though.
