### ISSUE TITLE
Calendar date format (not a bug)

### ISSUE THREAD

**Issue by gokkstudio** [snipe/snipe-it#4274]
hi, 
how can I globally change date format in calendar from YYYY-MM-DD > DD.MM.YYYY
please see image attached.

![calendar](https://user-images.githubusercontent.com/19394068/31829286-1ad137ee-b5bd-11e7-8902-d3cc5bc34172.jpg)

Thanks

**Comment by snipe** [comment]
That's not possible at this time. (The date field is expecting YYYY-mm-dd per MySQL's date field format)

**Comment by ebonweaver** [comment]
Looks like this is a feature request going all the way back to #1141 but that was closed also  :(

**Comment by kaeser49** [comment]
Hi,
unfortunately snipe-it disregards the most common date formats like e.g. dd-mm-year.
This is usually a nobrainer for a software supplier.

**Comment by kaeser49** [comment]
Time stamps are saved as a number und used following a desierd format from the localisation settings.
Seems to be rather a gimmy.

**Comment by snipe** [comment]
Time stamps are saved in mysql date/dateline format. 

I welcome your pull request.
