### ISSUE TITLE
Asset Categories are showing all consumables, accessories and the assets and displaying zero results

### ISSUE THREAD

**Issue by raakhtar** [snipe/snipe-it#4280]
v4.0.13 build 323 (gc1f8db3)

Displaying 0 results under Asset Categories widget

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by raakhtar** [comment]
Version of Snipe-IT you're running (Error Appeared in v14.0.13 and is still there in 4.0.15)
What OS and web server you're running Snipe-IT on       (WinAmp & Windows 10)
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)  (Git Pull)
If you're getting an error in your browser, include that error (No Error)
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error (Main Dashboard, no interaction)
If a stacktrace is provided in the error, include that too. (No Error)
Any errors that appear in your browser's error console.   (No Error)
Confirm whether the error is reproduceable on the demo.  (Not Sure)
Include any additional information you can find in app/storage/logs and your webserver's logs.
Include what you've done so far in the installation, and if you got any error messages along the way.
Indicate whether or not you've manually edited any data directly in the database (No)

I think this got messed up in 4.0.13, where on previous versions categories for Accessories were not part of this list and just the Assets categories was part of the list.

**Comment by raakhtar** [comment]
Well i think it is a not a bug, but a way of representing data. However, kindly sort the list based on 'Assets' CategoryType for its details and count to appear first in route > Api > CategoriesController.php
