### ISSUE TITLE
Not able to access admin settings

### ISSUE THREAD

**Issue by shubham2011** [snipe/snipe-it#4281]
#### Expected Behavior (or desired behavior if a feature request)
Hi, I am not able to see the admin menu. I have done a fresh install. 
My snipe_it version is v4.0.10 build 235 (gcbe008d)
PHP 7.0.23
Laravel 5.4.36
I have installed it by using Xampp and my first user looks like this {"admin":1,"user":1,"superuser":1,"reports":1}
I have also created another admin but I am not sure where to upgrade it from admin to superadmin to access the admin menu. I need admin menu to add new models, manufactures etc.
Thanks in advance, 
--

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by Diniver** [comment]
Hi shubham2011,

Please install the latest version: v4.0.13 build 323 (gc1f8db3)

This issue has been fixed.

**Comment by shubham2011** [comment]
Thanks for your reply, It works :)
