### ISSUE TITLE
Only Super users can see details for components.

### ISSUE THREAD

**Issue by rodeff** [snipe/snipe-it#4282]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here) - Should show the asset that a component is checked out to.

-----

#### Actual Behavior
If you are not a Global: Super User, you can't see the assets when you click on component.

(what actually happens goes here)
When you open a component, the list of assets that this component is checked out to is not there. Only if you are Global: Super User you can see them. 

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode - Yes
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) - Yes

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - Upgrade
- Version of Snipe-IT you're running - 4.0.13
- Version of PHP you're running - 7.1.9
- Version of MySQL/MariaDB you're running - 10.0.14
- What OS and web server you're running Snipe-IT on - Windows 2016 - IIS10
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - No error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Domain.com/components/2
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. - No, it is not.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - Yes, but the issue is present after the upgrade. 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
@dmeltzer did your policy PR address this?

**Comment by rodeff** [comment]
Hi, I am not sure if I got your question. No policy, I just have a lot of components checked out to assets and several groups of users that are not able to see the assets  once they click on the component.

**Comment by dmeltzer** [comment]
Not intentionally.  I'll look closer

**Comment by rodeff** [comment]
Thanks :)

**Comment by snipe** [comment]
@rodeff I just pushed out a few fixed - I can now only reproduce this if the use doesn't have the ability to see assets - which I would guess kinda makes sense? Seems weird to let folks see assets in the components view and not anywhere else.

**Comment by snipe** [comment]
@rodeff What branch did you try?

**Comment by rodeff** [comment]
@snipe since v4.0.x
We are currently on 4.1.5

**Comment by snipe** [comment]
> The users (including me) are member of a group that have full rights expect super admin and still having the issue.

If you're still on 4.1.5, you couldn't have tested my fix then.

**Comment by rodeff** [comment]
@snipe Yep, I am updating tomorrow and will let you know. Didn't get you right that this is fixed with the latest. 
Thanks much.

**Comment by rodeff** [comment]
@snipe It works great.
Thanks for looking into this.
Also issue #4509 is fixed as well.
Wish you all the best and thank you for your hard work.
