### ISSUE TITLE
Feature Request: Email user a list of assigned items

### ISSUE THREAD

**Issue by tbradsha** [snipe/snipe-it#4289]
#### Expected Behavior (or desired behavior if a feature request)

It'd be nice to email a user a list of all their assigned items (assets, licenses, accessories, etc.) via the user page.

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by TheArtistCoder** [comment]
I have a similar request. In our previous system we could send a mass email to everyone for hardware acknowledgment. The current asset acceptance is too granular because I don't think users will like to accept a PC, a monitor and a phone separately.

**Comment by Raykongstar** [comment]
+1, How did we let this go stale? This is a much needed feature.

**Comment by ghost** [comment]
it will be usefull for us too

**Comment by tfremlev** [comment]
Bump. This is still very relevant.
As mail is already an option to enter into users, I assume it could be quickly integrated, that an approved e-mail (from an admin) is used to send mails to the user with assets etc.
