### ISSUE TITLE
Uploaded image path wrong

### ISSUE THREAD

**Issue by gt7810** [snipe/snipe-it#429]
When I upload an image file to an asset the path is set to: /uploads/models/pYNmoN2mvZUv8GnBK0AuVjmPy.jpg 
the real path is:
/snipe-it/uploads/models/pYNmoN2mvZUv8GnBK0AuVjmPy.jpg 
I have installed the application in a directory that in a layer down from webroot.  
This means the image path is broken. Any ideas on how to fix this?

Thanks George

**Comment by snipe** [comment]
Hi @gt7810 - did you get this sorted? (I'd like to close this issue if you have)

**Comment by gt7810** [comment]
Yes. I updated the path in the blades. Temp fix but works for now.
Thanks

**Comment by snipe** [comment]
Hm, that's going to screw you up when you upgrade tho. What OS is your server? If your webroot is still `apps`, that's going to be a problem. Should be `public` within the snipe-it app directory.

**Comment by gt7810** [comment]
Server is OS X 10.6. It is also running railo so  config  is a little
delicate. I am thinking of moving snipe to a new server which will solve
the webroot issue.

**Comment by snipe** [comment]
Ahh, yeah, that's a bit sticky. I guess the temp fix will work until you move it, but remember to change that  path when you upgrade on the OS X server or you'll run into the same problem again.
