### ISSUE TITLE
Filtering assets by status (bug-ish)

### ISSUE THREAD

**Issue by Diniver** [snipe/snipe-it#4295]
Hi all,

I found few links which are a bit weird and might make mess in the future. 

So this is the result when I try to filter assets by status from all asset list. When I choose deployed I should get only assets which are deployed. But unfortunately I am getting also "ready to deploy". The link is http://bla.bla/statuslabels/2
![image](https://user-images.githubusercontent.com/31882138/31935701-698589e8-b8a7-11e7-90b9-8e052b72e685.png)

If I filter them from sidebar it is working properly: http://bla.bla/hardware?status=Deployed
![image](https://user-images.githubusercontent.com/31882138/31935642-3df51186-b8a7-11e7-822c-7f396f46b46c.png)
![image](https://user-images.githubusercontent.com/31882138/31936615-fea7b094-b8a9-11e7-8bd4-978ec925b217.png)

For pending items is working but the difference in the urls is the same

/statuslabels/1 - when filtered from all assets

/hardware?status=Pending - when filtered from left side panel

running version  v4.0.15 build 339 (g17b2719)
Reproducible in online demo

Regards,
Diniver

**Comment by snipe** [comment]
How do I reproduce this in the demo?
When I go to https://demo.snipeitapp.com/hardware?status=Deployed, I only see deployed items.

**Comment by Diniver** [comment]
But if you go in "list all" and after that click on status to filter it, it goes to /statuslabel/x

**Comment by snipe** [comment]
That's not really a bug though, that's how the meta status of "Deployed" works. (Deployed is deployable + checked out)

**Comment by Diniver** [comment]
I see. If that's the way how it works that's ok. I just thought this might not be the case.

Thanks

**Comment by snipe** [comment]
Yeah, it's a little confusing, but I'm not sure how else to handle/explain it. We need the ability to support multiple kinds of deployable statuses, but the business logic changes if they are deployable and are also checked out. :-/
