### ISSUE TITLE
Debug Mode didnt show debug bar / console log bar

### ISSUE THREAD

**Issue by oks1998** [snipe/snipe-it#4296]
#### Expected Behavior (or desired behavior if a feature request)

After enable debug mode, the bottom bar should be visible / accessible.

-----

#### Actual Behavior

cannot see the bottom bar (console bar/ debug bar)
error log:
[2017-10-24 17:52:14] production.ERROR: Debugbar exception: Route [debugbar.openhandler] not defined.
[2017-10-24 17:52:20] production.ERROR: Debugbar exception: Route [debugbar.openhandler] not defined.
[2017-10-24 17:52:27] production.ERROR: Debugbar exception: Route [debugbar.openhandler] not defined.
[2017-10-24 17:52:49] production.ERROR: Debugbar exception: Route [debugbar.openhandler] not defined.
[2017-10-24 17:52:54] production.ERROR: Debugbar exception: Route [debugbar.openhandler] not defined.
[2017-10-24 17:52:56] production.ERROR: Debugbar exception: Route [debugbar.openhandler] not defined.
[2017-10-24 17:54:40] production.ERROR: Debugbar exception: Route [debugbar.openhandler] not defined.

-----

#### Please confirm you have done the following before posting your bug report:

- [ v] I have enabled debug mode 
- [ v] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
https://github.com/barryvdh/laravel-debugbar/issues/270

Try clearing your caches/configs.

```
php artisan clear
php artisan cache:clear
php artisan view:clear
php artisan route:clear
php artisan config:clear
```
