### ISSUE TITLE
Feature Request: Asset & Accessory Workflow (menu changes)

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#4298]
#### Desired Behavior

Currently when creating an asset or accessory, the workflow is a bit cumbersome as the process, generally starts with "Create new Asset" but often it is needed to start with a new manufacturer, supplier and then model. 

My idea is to simply move the menu items around, so they are in a workflow process that when creating a new asset or accessory would make the most workflow sense. 

As it is now, I'm constantly canceling what I was adding and going back to add a manufacturer or supplier, model, and then finally creating the asset.

**Comment by snipe** [comment]
@Jarli01 the "new" button next to those fields allows you to create new ones on the fly, so you shouldn't need to cancel your submission to add things.

<img width="677" alt="screen shot 2017-10-24 at 9 17 39 am" src="https://user-images.githubusercontent.com/197404/31955122-49cd578a-b89c-11e7-9328-197a932da051.png">

**Comment by snipe** [comment]
Unless you mean the dependent fields like Manufacturer/Category within the (for example) new Asset Model modal screen.

Moving the menu items around is a workflow that might be better for you, but for a lot of folks who are working with a finite number of combinations, that could be really disruptive to change.

When you say "move the menu items around", what exactly do you mean?

**Comment by Jarli01** [comment]
Sorry I wasn't very clear in my description. 

https://i.imgur.com/3r90mwH.png

This process here, of creating asset models, categories, manufacturers and suppliers etc is essentially reversed from what would be expected. (at least by me)

The order I believe should be Manufacturers > Category > Suppliers > Asset Model, and if creating a new asset from the default asset or accessories screen this process could be broken down to or rearranged in a way that ensures you always have the required details (manufacturer, category, supplier, model) before you're actually entering things such as Serial numbers. 

When going through and adding a new asset or accessory type (of some new manufacturer or type etc) I always find myself cancelling out of the New <type creation> menu as none of this information has been created in the database.
