### ISSUE TITLE
History list empty, logged error on lavarel.log

### ISSUE THREAD

**Issue by korio77** [snipe/snipe-it#4300]
After updating to version 4.0.13 i have noticed that the history list on assets is empty, i have looked around to see if i can figure out what the problem was but i dont really know what is the root cause of the error.

attached in the end of this issue is the full stack trace, here is the header:

[2017-10-24 15:35:25] production.ERROR: UnexpectedValueException: The Response content must be a string or object implementing __toString(), "boolean" given. in C:\inetpub\wwwroot\inventario\vendor\symfony\http-foundation\Response.php:409

No errors shown on the web with the debug mode enabled.

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running 4.0.13 build 273 (gab3f5f4)
- Version of PHP you're running 7.1.7
- Version of MySQL/MariaDB you're running mysql 5.5
- What OS and web server you're running Snipe-IT on windows server 2012 R2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error Any history of user or assets
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. One error related to a font and another error 500 of /api/v1/reports/activity.......
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. no
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database no

Stack trace:
#0 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Http\Response.php(41): Symfony\Component\HttpFoundation\Response->setContent(false)
#1 C:\inetpub\wwwroot\inventario\vendor\symfony\http-foundation\Response.php(201): Illuminate\Http\Response->setContent(false)
#2 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Routing\Router.php(615): Symfony\Component\HttpFoundation\Response->__construct(Array)
#3 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Routing\Router.php(572): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Array)
#4 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#5 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#6 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#7 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Routing\Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#10 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Routing\Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#11 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Routing\Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#12 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#13 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#14 C:\inetpub\wwwroot\inventario\vendor\barryvdh\laravel-debugbar\src\Middleware\Debugbar.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 C:\inetpub\wwwroot\inventario\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 C:\inetpub\wwwroot\inventario\vendor\fideloper\proxy\src\TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 C:\inetpub\wwwroot\inventario\app\Http\Middleware\CheckForSetup.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 C:\inetpub\wwwroot\inventario\app\Http\Middleware\NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 C:\inetpub\wwwroot\inventario\app\Http\Middleware\ContentSecurityPolicyHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\ContentSecurityPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 C:\inetpub\wwwroot\inventario\app\Http\Middleware\ReferrerPolicyHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\ReferrerPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 C:\inetpub\wwwroot\inventario\app\Http\Middleware\XssProtectHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 C:\inetpub\wwwroot\inventario\app\Http\Middleware\FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#53 C:\inetpub\wwwroot\inventario\public\index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#54 {main}

**Comment by snipe** [comment]
Can you try upgrading to the latest and tell me if you're still seeing this?

**Comment by snipe** [comment]
(If you installed via git, you can just run `php upgrade.php`)

**Comment by korio77** [comment]
i installed it manually, anyway give me a couple minutes and i post back the results

**Comment by snipe** [comment]
Okay - we definitely recommend installing via git if you can. Makes upgrading 100 times easier.

**Comment by korio77** [comment]
well, update done, everything seems to work fine but!

History is still empty, other users who had history are empty, i have been able to find a few with one or two history lines but not more, my user should have 8+ and have none.

Still the same error being logged in lavarel.log, i just hope i havent lost the history info.

Any clues of whats going on?

**Comment by snipe** [comment]
I doubt you've lost anything, unless you went out of your way to delete things. 

Is it possible you have some weird characters in your data anywhere? I'm seeing this which is kinda related. https://github.com/statamic/v2-hub/issues/909

Also maybe try running:

```
php artisan cache:clear
php artisan clear-compiled
composer dump-autoload
php artisan optimize
```

**Comment by korio77** [comment]
well, im spanish so probably some accents and the "Ñ" letter can be around.

php artisan cache:clear
composer dump-autoload

those two commands where already used in the update, i will run them all again in the order you posted them right now

**Comment by snipe** [comment]
That still shouldn't be an issue - we have lots of users from all over. It's not usually characters like an enyay, more like weird hidden characters that sometimes exist from weird spreadsheets.

**Comment by snipe** [comment]
(Also delete `bootstrap/cache/compiled.php`)

**Comment by korio77** [comment]
launched all of the comands without problems, there was no compiled.php file in the folder you pointed out.

Still the same, blank history list and the same errors.

**Comment by snipe** [comment]
What's the full url of the API call that the browser is making?

**Comment by korio77** [comment]
im not really sure of what you are asking, i have seen that the error is shown on the activity report also.

Tell me where i can see the api call and i will post it, i have the debug mode enabled currently

**Comment by snipe** [comment]
@korio77 you'd have to look at the network tab in your browser's debugging console.

**Comment by snipe** [comment]
Try this:

On line `55` of `app/Http/Controllers/Api/ReportsController.php`, change:

```
return (new ActionlogsTransformer)->transformActionlogs($actionlogs, $total);
```

to

```
$header = array (
            'Content-Type' => 'application/json; charset=UTF-8',
            'charset' => 'utf-8'
        );

        return response()->json((new ActionlogsTransformer)->transformActionlogs($actionlogs, $total), 200, $header, JSON_UNESCAPED_UNICODE);
```

I don't know if that will help, but it looks like some folks are seeing this with [UTF-8 issues](https://laracasts.com/discuss/channels/general-discussion/laravel-5-problem-with-utf-8-in-a-json-response).

**Comment by korio77** [comment]
this one from the activity report
![image](https://user-images.githubusercontent.com/20576635/31952597-4630a3d0-b8e1-11e7-868a-e808e01b3360.png)

this one at loading my user view
![image](https://user-images.githubusercontent.com/20576635/31952677-749ead84-b8e1-11e7-8019-1d99ef37dd74.png)

and this are the errors at loading my user view

![image](https://user-images.githubusercontent.com/20576635/31952769-a99066ea-b8e1-11e7-8c07-9916b5a47d63.png)

**Comment by snipe** [comment]
Click on the XHR tab (you're currently on JS) to see the full URL of the API call

**Comment by korio77** [comment]
here you have it, 

![image](https://user-images.githubusercontent.com/20576635/32040062-c06f7ce4-ba2f-11e7-930f-7e41f549255b.png)


I will try as soon as i can the code edit you posted and post here the results.

Thanks for your help.

**Comment by korio77** [comment]
i have just changed the code, still not working but a diferent error now.

[2017-10-26 09:45:18] production.ERROR: InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded in C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Http\JsonResponse.php:71
Stack trace:
#0 C:\inetpub\wwwroot\inventario\vendor\symfony\http-foundation\JsonResponse.php(50): Illuminate\Http\JsonResponse->setData(Array)
#1 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Http\JsonResponse.php(27): Symfony\Component\HttpFoundation\JsonResponse->__construct(Array, 200, Array)
#2 C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(83): Illuminate\Http\JsonResponse->__construct(Array, 200, Array, 256)
#3 C:\inetpub\wwwroot\inventario\app\Http\Controllers\Api\ReportsController.php(60): Illuminate\Routing\ResponseFactory->json(Array, 200, Array, 256)
#4 [internal function]: App\Http\Controllers\Api\ReportsController->index(Object(Illuminate\Http\Request))


I can post the full log if needed.

**Comment by korio77** [comment]
Hi again @snipe 

Just adding more stuff in case this makes easier for u to solve this.

I have updated right now to the last version Version v4.1.5 build 187 (gc0293a7) and the error is still here.

Im looking at the logs and the error header is this.

[2017-11-22 11:34:09] production.ERROR: UnexpectedValueException: The Response content must be a string or object implementing __toString(), "boolean" given. in C:\inetpub\wwwroot\inventario\vendor\symfony\http-foundation\Response.php:407
Stack trace:

I can provide full stack traces if needed.

Then im checking the chrome errors.
![image](https://user-images.githubusercontent.com/20576635/33123172-bbc90d5e-cf79-11e7-945b-9e4392772b26.png)

Here is the url of the api call
![image](https://user-images.githubusercontent.com/20576635/33123523-c05bd044-cf7a-11e7-99b9-970c69a9e202.png)


After changing the little piece of code you suggested this is the result

[2017-11-22 11:50:27] production.ERROR: InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded in C:\inetpub\wwwroot\inventario\vendor\laravel\framework\src\Illuminate\Http\JsonResponse.php:71
Stack trace:

And in chrome

![image](https://user-images.githubusercontent.com/20576635/33123887-b3719a3e-cf7b-11e7-94a3-3942df48f7e6.png)


Tell me if you need any more testing from my side.

Thanks for the help!

**Comment by korio77** [comment]
Hi again @snipe !

Im trying to solve or atleast know why this is happening, so i want to check directly the output of the report activity query.

Do you know the query or if its easy to get the sql query this report uses to extract the list from the database?

Regards.

**Comment by snipe** [comment]
If you enable debug mode and click on the queries tab, you'll be able to see the specific query that it's trying to do. https://snipe-it.readme.io/docs/advanced-debugging

**Comment by kacedali** [comment]
hi korio
try change database collation to utf8mb4_unicode_ci
clear all action_log table data

**Comment by korio77** [comment]
hi @kacedali and thanks for the suggestion.

i will try it if @snipe agrees to it, but i dont change stuff like that just to "try" if it works.

Im hoping @snipe will be able to fix this for the 4.2 release.

**Comment by snipe** [comment]
Problem is, I can't reproduce it at all :(

**Comment by kacedali** [comment]
hi @korio77 
i get this error and i fixed this by changing database collation utf8mb4_unicode_ci and converting data

**Comment by korio77** [comment]
Hi @kacedali those are good news!

@snipe any recomended procedure for changing the database collation of the snipe database?

Thanks for the help.

**Comment by kacedali** [comment]
hi @snipe 
the probleme are in ActionlogPresenter in
    public function actionType() {
        return strtolower(trans('general.'.str_replace(' ', '_', $this->action_type)));
    }
when the translation have caractere with accent like in frensh translation
    'uploaded'              => 'Téléversement réussi',
i get : Malformed UTF-8 characters, possibly incorrectly encoded

when i remove all accent the probleme gone
    'uploaded'              => 'Televersement reussi',

**Comment by snipe** [comment]
@kacedali Huh... okay, that's very helpful, thanks for tracking that down! I
l'll have to think about how to fix...

**Comment by kacedali** [comment]
hi @snipe 
i replaced strtolower to mb_strtolower and its work

**Comment by korio77** [comment]
@snipe @kacedali Just tried it, changed that little piece of code, restarted the IIS server.

Everything working fine apparently, thank you so much for this workaround, i will keep using it untill a fix is released.

Thank you both again.
