### ISSUE TITLE
Upgrade from v4.0.4 to v4.0.15

### ISSUE THREAD

**Issue by Myrskyvaris** [snipe/snipe-it#4302]
Last time I upgraded from v4.0.4 to v4.0.7, I lost access to the assets screen. I stopped SnipeIT, copied the contents of the .zip over,  did a php artisan config:clear and php artisan config:cache, and restarted the service. I also cleared the cookies on my browser. 

When I reinstalled v4.0.4 from scratch, to try get the assets screen back, and tried to restore my Db, I got all sorts of permission errors, despite being the Db admin. 

My question is, what is the correct way of upgrading v4.0.4 to v4.0.15?

Is there a good way to back up & restore the Db without running into permissions errors?

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)
