### ISSUE TITLE
3 QUESTIONS in V4

### ISSUE THREAD

**Issue by linglongtong** [snipe/snipe-it#4308]
QUESTION 1:

I upgrade Snipe-IT from v3.4.3 to v4, in v3.4.3 all assets page I can search Chinese name, but in v4 all assets page I can't search Chinese name. 

![image](https://user-images.githubusercontent.com/23185284/31978360-9869a7a4-b973-11e7-9ab2-387b8957e28e.png)

![image](https://user-images.githubusercontent.com/23185284/31978400-d3c9d94a-b973-11e7-9889-2de8c039fee5.png)

QUESTION 2:

If someone has resigned, the "Checkin & Delete User" button is useless, shows error "No users selected".

![image](https://user-images.githubusercontent.com/23185284/31978676-136a8558-b975-11e7-93b9-2634af613a45.png)

QUESTION 3:

I defined some custom fields in v3.4.3 which should be showed depending on models, but v4 custom fields are all showed no matter what kind of models.

![image](https://user-images.githubusercontent.com/23185284/31978921-81d00990-b976-11e7-9418-aa53f3dea095.png)

![image](https://user-images.githubusercontent.com/23185284/31978946-a1745882-b976-11e7-9014-feeac8d9b536.png)

My Snipe-IT version: v4 build beta5 (7)

**Comment by snipe** [comment]
> I defined some custom fields in v3.4.3 which should be showed depending on models, but v4 custom fields are all showed no matter what kind of models.

That's because the all assets page shows all assets, so it must show all of the custom fields that have been applied to any model.

**Comment by linglongtong** [comment]
@snipe OK. Thank you. 

Any advice about QUESTION 1 and 2?
