### ISSUE TITLE
Feature Request - Custom Warning/Alert Fields

### ISSUE THREAD

**Issue by FOOSAYS** [snipe/snipe-it#4309]
#### Expected Behavior (or desired behavior if a feature request)

We have recently been asked to clamp down on PAT testing our assets (currently annual, but could be more or less frequent).

Would be good if we could add this as a custom field (ie Date) to field-sets that also follow the Alerts Threshold in settings, such that x-days before this set date an alert email is sent to remind us of the upcoming PAT for this asset.
As far as PAT testing goes, it would also be good to be auditable, so changes (pass/failure/rescheduling) would also appear in the History tab of the asset.

If the custom date field could be alerted, this function could be extended to any scheduled maintenance, upgrades, updates or replacements required on asset or any other frequency/safety tests.

Many thanks,

Lachy

**Comment by snipe** [comment]
Couldn't you use the audit feature for that?

**Comment by FOOSAYS** [comment]
Possibly, I didn't realise our deployment was so far out of date, I will update to v4.0 and check.

Thanks,

**Comment by FOOSAYS** [comment]
After upgrading and having a look at the Bulk Audit, it might work for us as suggested.

Is there a way of cancelling or amending an audit?

Is there documentation somewhere that has further information on all features and how they (and their fields) work?
For instance, does the "Next Audit Date" send an alert email to user? to admin? Does it follow the same timings as the Alerts Threshold? or none of these?

Many thanks,
