### ISSUE TITLE
Installation on LAMP stack

### ISSUE THREAD

**Issue by ghost** [snipe/snipe-it#431]
Trying to install this on Ubuntu 14.04 LTS

Installed the LAMP package. Got everything set up as far as getting the Apache set up. I modified my sites-available and sites-enabled to point to the new location /home/user/snipeit/public but when I got to the IP address it still appears to be looking at /var/www

Any help would be appreacited.

**Comment by SHoar** [comment]
@hiiambo What did you move to /var/www/ ?  I've done the mod_rewrite, but found that changing /etc/apache2/apache2.conf 
<code> <Directory /home/********/snipe-it/public >
	Options Indexes FollowSymLinks
	AllowOverride all
	Require all granted
</Directory>
</code>
