### ISSUE TITLE
Another installation issue - docker

### ISSUE THREAD

**Issue by GeorgelT** [snipe/snipe-it#4312]
I've been trying to install snipe-it for the better part of 3 days and still can't get it to work. After multiple attempts at manual install, one server crash and restoring from backup later, I decided to just f-it and try the pre-configured docker build. How wrong I was even with this one.

#### Expected Behavior (or desired behavior if a feature request)

I followed the steps in the guide, made a mysql container as instructed. The mysql container started without issue. Gave the same info inside the config file, it seems to work just fine.

-----

#### Actual Behavior

When I go to my ip I get to /setup where I am greeted with 2 whoops red bars.
Turned on debug mode(confirming the config file works) and am getting: (1/1) RuntimeException
The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 

This is a fresh install attempt

- Version of Snipe-IT you're running

latest version downloaded from the official website/docker repo

- Version of PHP you're running

whatever is inside the container

- Version of MySQL/MariaDB you're running

I'm guessing the latest version available through docker

- What OS and web server you're running Snipe-IT on

Base OS is Ubuntu 16.04LTS acting as host for docker.

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

All 3 of them

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

(1/1) RuntimeExceptionThe only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.
--
in Encrypter.php (line 43)

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

ip:port/setup

- If a stacktrace is provided in the error, include that too.

in Encrypter.php (line 43)
--
at Encrypter->__construct('nwe9caaPfrdutoGV10ds1OKmOf3lTq/nC/Qr8m2Y0qI=', 'AES-256-CBC')in EncryptionServiceProvider.php (line 27)
at EncryptionServiceProvider->Illuminate\Encryption\{closure}(object(Application), array())in Container.php (line 726)
at Container->build(object(Closure))in Container.php (line 608)
at Container->resolve('encrypter')in Container.php (line 575)
at Container->make('encrypter')in Application.php (line 728)
at Application->make('encrypter')in Container.php (line 862)
at Container->resolveClass(object(ReflectionParameter))in Container.php (line 790)
at Container->resolveDependencies(array(object(ReflectionParameter)))in Container.php (line 757)
at Container->build('App\\Http\\Middleware\\EncryptCookies')in Container.php (line 608)
at Container->resolve('App\\Http\\Middleware\\EncryptCookies')in Container.php (line 575)
at Container->make('App\\Http\\Middleware\\EncryptCookies')in Application.php (line 728)
at Application->make('App\\Http\\Middleware\\EncryptCookies')in Pipeline.php (line 138)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 576)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 535)
at Router->dispatchToRoute(object(Request))in Router.php (line 513)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php (line 51)
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php (line 25)
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php (line 56)
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php (line 35)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

- Any errors that appear in your browser's error console.

No errors in console

- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.

not able to get past install, can't preproduce on running system.

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

dumps directory is empty

- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

docker command line used to start:

sudo docker pull mysql

sudo docker run --name snipe-mysql2 --env-file=my_env_file -d -P mysql

sudo docker run -d -p 85:80 --link snipe-mysql2:mysql -v /home/user/snipe:/var/lib/snipeit --env-file=./my_env_file snipe/snipe-it

(btw. you  need to update the docker tutorial to include snipe/ before the snipe-it image name)

Everything in my docker repo right now:
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
snipe/snipe-it      latest              405825720421        26 hours ago        568MB
mysql               latest              5fac85ee2c68        8 days ago          408MB
hello-world         latest              05a3bd381fc2        6 weeks ago         1.84kB

EDIT: Forgot to mention, did the docker run --rm snipe/snipe-it and added the APP_KEY to the config file, without prefix.

**Comment by AuraMatt** [comment]
Make sure this is set at the bottom of your .env file.

![5375c23c85d7c4b089a880ae919d0cd5](https://user-images.githubusercontent.com/32943004/32005302-d32cf47c-b99b-11e7-910f-465167af24cc.png)

I believe there's another thread on here about a similar issue as I fixed it myself.

All the best

**Comment by snipe** [comment]
@AuraMatt that shouldn't be necessary though. It defaults to that in the app.config.

`'cipher' =>  env('APP_CIPHER', 'AES-256-CBC'),`

**Comment by snipe** [comment]
Try running `php artisan key:generate`

**Comment by GeorgelT** [comment]
Ok, for update. I fired up a fresh ubuntu server VM to eliminate any settings I might have allready had on the main server.

Here are my steps so far:

- Installed docker, pulled snipe/snipe-it .
sudo docker pull snipe/snipe-it

- edited my_env_file to have desired root password and settings for DB
# Mysql Parameters
MYSQL_ROOT_PASSWORD=123qweasd
MYSQL_DATABASE=snipeit
MYSQL_USER=snipeit
MYSQL_PASSWORD=123qweasd
....
# Snipe-IT Settings
APP_ENV=production
APP_DEBUG=true
APP_KEY=kZ/zdER9pz91FsFxYnH2YUgxKVwDgIMahzZcF+vuS4g=
APP_URL=http://10.1.0.72:85
APP_TIMEZONE=US/Pacific
APP_LOCALE=en


- Made the database as instructed, with the exact command to ensure same version of mysql
sudo docker run --name snipe-mysql --env-file=my_env_file -d -p $(docker-machine ip b2d)::3306 mysql:5.6

-ran the appkey generation command:
sudo docker run --rm snipe/snipe-it
Please re-run this container with an environment variable $APP_KEY
An example APP_KEY you could use is: 
base64:kZ/zdER9pz91FsFxYnH2YUgxKVwDgIMahzZcF+vuS4g=

- added the APP_KEY to the env file, see above

- stated snipe-it container as such:
sudo docker run -d -p 85:80 --link snipe-mysql:mysql --env-file=my_env_file snipe/snipe-it

- went to my address 10.1.0.72:85
got same double red bands with whoops.
After turning on debug I get the same errors:

(1/1) RuntimeExceptionThe only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.
--
in Encrypter.php (line 43)
at Encrypter->__construct('kZ/zdER9pz91FsFxYnH2YUgxKVwDgIMahzZcF+vuS4g=', 'AES-256-CBC')in EncryptionServiceProvider.php (line 27)

From the line above I'm understanding that the provided APP_KEY is somehow invalid eventhough its the one the container provided. Please advise further.

**Comment by GeorgelT** [comment]
Am I going insane? Was the mysql command the one I used in my previous post or did you just switch it to:
`docker run --name snipe-mysql --env-file=my_env_file -d -P mysql:5.6`

I'd like to confirm that after doing this, and creating and starting the DB this way, I have now been able to complete the installation. I am now inside the admin panel.
