### ISSUE TITLE
Update Asset numbers.  I created the original 1300 assets as a test and just labeled assets 1-1300.  Now I got the asset numbers. I noticed that running an import creates new assets.  do I have to hit the database directly at this point? What is the best tool or an example of that.  I have a list of associated serials and assets I can use. Just not sure 

### ISSUE THREAD

**Issue by papacucku** [snipe/snipe-it#4313]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I don't understand the question - can you clarify please?

Also, please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by papacucku** [comment]
Sorry I didn’t mean to delete anything.

The question is how do I update asset tag numbers for existing assets.  I tried importing an updated file and instead of updating the existing asset it created a NEW asset with the new asset number.

Snipe-IT version

v3.6.4 build 12 (gf7e4fca)

PHP Version

7.0.15-0ubuntu0.16.04.4

Laravel Version

5.2.45


I didn’t install snipe it so I don’t know most of those questions below but we just started using it and I know it is version

**Comment by papacucku** [comment]
I apologize for being so uniformed. Its all running on  Ubuntu 16.04.2 LTS and I am not too great in Linux.  I found that after importing the same csv file with updated info in new columns "added" the info to asset.  At least that is what  appeared to have happened.  So I got the extra ones deleted and appear to be back to square.  So when I got the actual asset tag numbers I was hoping to update that so I took the same csv file and added the associated asset tag numbers replacing the basic 1,2,3,4,5 etc. I put in there when I originally created the assets on the first import.   I really appreciate the responses to these insanely newbie questions.  I can probably use my asset info and do some kind of update sql from linux assuming its my sql or something.  I have not done that but done similar things many times on other systems. 

My colleague already started using the darn thing and has history and changed status etc or I would just delete everything and reimport with the file with the actual asset tags.  make sense?

**Comment by snipe** [comment]
@papacucku There isn't a way to bulk update asset tags, since asset tags are the only unique constraint we have on assets. When you do an import, it looks up assets based on asset tag, so uploading something with a bunch of new asset tags will create a bunch of new assets, since it can't find a match within the system.

**Comment by papacucku** [comment]
OK thanks so much.  We are a school district and have student helpers, just the kind of project for students (updating assets).  We have tons of chromebooks that the students are allowed to take home, they are getting broken and we are gonna use snipe it to help keep track of all that.  Snipe it was highly recommended. Take Care.

**Comment by snipe** [comment]
@papacucku Glad to hear it's helpful. If you're not already using it, you might want to look into the EULA features when you check assets out to students. Sometimes just knowing that there *could* be consequences can affect the care folks take with your stuff. (We actually created that feature specifically for schools.)
