### ISSUE TITLE
New sticky header and ajaxy, rich menus on checkout

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#4314]
I added an experimental ajax rich menu on checkout (develop branch) that solves a few problems:

- Pulls users 100 at a time (or does a live search using the select search option), which should make page loads more manageable for Snipe-IT users with tens of thousands of users
- Hopefully adds a little more life to the checkout options, showing you the user's picture as you check them out 

 (I know that seems stupid, but we try very hard to make software that's not just useful, but even sorta fun to use, so it matters to me.)

![fancy-checkout-menu](https://user-images.githubusercontent.com/197404/32016335-85688616-b978-11e7-80ab-667e0b2a86a3.gif)

We'd love some help kicking the tires on these features - if we can confirm the ajax select2 dropdowns are working well there, we'll extrapolate that out to more areas (assets, suppliers, etc)

You can test this on the develop demo:
https://develop.snipeitapp.com
`admin` / `password`

Or by grabbing the develop branch from github.

**Comment by harrykantas** [comment]
tested this on a docker instance with our LDAP of about ~15K users and it works well, and looks very pretty! 

I'd love to see it implemented on more fields on the checkout asset page, especially the detailed asset field, where we also have ~15K items, that only get fetched on that call, causing slow page loads.

**Comment by snipe** [comment]
@harrykantas thanks for testing! I've been working on implementing it across more fields, so check back on develop shortly. I've got it working for many more fields now, just running into a few issues getting it to populate correctly if there is existing data (on a validation failure, or an edit, for example), and also making sure it correctly populates the New menu if something is being created on the fly.

**Comment by snipe** [comment]
@harrykantas I just added a bunch more of the ajax menus (tho not done just yet). Do a fresh pull from develop when you get a moment and let me know what you think.

**Comment by harrykantas** [comment]
this is perfect, it has effectively reduced the checkout page's initial loading time from 3mins down to 1sec! :)
Definitely a winner, thanks for implementing that.

No noticeable lag on the AJAX pre-caching, either. I'm guessing the 100 items at a time was a conservative initial value, I believe you could safely double that, judging from our docker instance.

let me know if there's anything in particular you'd like me to test while I'm at it.

**Comment by tbradsha** [comment]
On the develop demo, it doesn't look like sort works when the sticky header is active (e.g. when you're scrolled down a bit). This is probably just a matter of attaching an event to the second header set. Otherwise looks great!

**Comment by snipe** [comment]
@tbradsha It looks like you can sort and then scroll, but not sort once the sticky header has been activated.

**Comment by tbradsha** [comment]
Correct, after scrolling down and activating the sticky header you have to scroll up to the top to deactivate the sticky header and sort again.

**Comment by matc** [comment]
Hey @snipe, just wanted to give you an fyi that yesterday we deployed 4.1.6 master version to production and have seen major performance improvements in selecting users from the drop down during asset assignments workflow. We previously were running 4.0.15.

**Comment by snipe** [comment]
@matc - great, thanks for letting me know!
