### ISSUE TITLE
Reporting / CSV - Checked Out To Not Displaying Users

### ISSUE THREAD

**Issue by TheVakman** [snipe/snipe-it#4317]
#### Expected Behavior (or desired behavior if a feature request)
When I download a CSV, it should display the "Checked Out To" user in the "Checked Out To" column. 

The same issue occurs on "Custom Report" and checking off "Assigned To".

-----

#### Actual Behavior
The "Checked Out To" column is blank on the report. This occurs on the demo as well.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:
Version of Snipe-IT you're running
4.0.15. This also occurred on 4.0.13.
Version of PHP you're running
7.0.23
Version of MySQL/MariaDB you're running
5.5.56-MariaDB
What OS and web server you're running Snipe-IT on
CentOS 7.4.1708
WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No errors.
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
All Assets > Download CSV
OR
Custom Asset Report > Assigned To > Generate
Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
Yes, it is.

**Comment by snipe** [comment]
This is via the server-side CSV export, or the one that's parti of the table menu?

**Comment by TheVakman** [comment]
This would have been with the table menu or via Custom Asset Report.

However, I think we can close this now as it seems fixed in 4.1.3!
