### ISSUE TITLE
Feature request - license page - additional asset detail during checkout

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#432]
When checking out a license asset it would be nice to see along with the asset tag and name also the model of the asset. We do not assign names to assets as we just use the model and feel that would be redundant but we do have cases where people are assigned multiple workstation assets and would be nice to see the model of that workstation asset to assign the right license.

Thank you

**Comment by snipe** [comment]
@kobie-chasehansen this is on the checkout form itself?

**Comment by kobie-chasehansen** [comment]
yes, noticed it on the license checkout, think it was on the equipment checkout as well.

http://i.imgur.com/OqZWxcj.png
