### ISSUE TITLE
Audit Log incorrect Next Date values

### ISSUE THREAD

**Issue by FOOSAYS** [snipe/snipe-it#4321]
#### Expected Behavior (or desired behavior if a feature request)

Audit report "Next Audit Date" to show date of most recent Next Audit

-----

#### Actual Behavior

I created an audit for asset A, but entered date in wrong, when creating a new audit for this on the correct date, it still shows the next audit as the original set.
eg:

Audit                            | Item       | Next Audit Date | Days to Next Audit | 
2017-10-26 10:55 AM  | Asset A  | 2018-10-26        | 2
2017-10-26 10:44 AM  | Asset A  | 2018-10-26        | 2

The bottom audit on this list was created first, Next Audit date is correct, but Days to Next is incorrect.
The top audit on this list was created second, Next Audit date is incorret, but Days to Nest is correct.

-----

#### Please confirm you have done the following before posting your bug report:

- [ Y ] I have enabled debug mode 
- [ Y ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Upgrade**
- Version of Snipe-IT you're running **v4.0 build 1 (g998c4a5)**
- Version of PHP you're running **7.1.7**
- Version of MySQL/MariaDB you're running **Maria 10.1.25.0**
- What OS and web server you're running Snipe-IT on **Windows Server 2012 R2 IIS 6.2**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **manual**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **https://assets.readcasedhole.com/reports/audit**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. **Yes, Asset= "Asset A"**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database **No**

**Comment by snipe** [comment]
Are you still seeing this issue?

**Comment by FOOSAYS** [comment]
Yes, I am.
Tested in your online demo again (seems to no longer be in English)

Created Asset A
Audited Asset A - next audit date 20-12-2018
Audit Log reads (incorrect date, correct days to next):
Next check date | Date to review next
Thu Dec 13, 2018 | 378

I then created a new audit for Asset A - next audit date 13-12-2018
and then again - next audit date 20-12-2018
and then again - next audit date 27-12-2018

The Audit log now reads (note all "next check dates" are wrong, bar the second from bottom, and all the "days to next" are wrong, except the top):
Next check date | Date to review next
Thu Dec 13, 2018 | 378
Thu Dec 13, 2018 | 378
Thu Dec 13, 2018 | 378
Thu Dec 13, 2018 | 378

I created a new Asset B to double check what the initial audit log result would be. Auditing this Asset B for next date = 27-12-2018, it still shows next audit date of 13-12-2018 (this does not seem to change ever)

It still seems to show the wrong next audit date, and still updates ALL audit logs' "days to next audit" with the same value. I don't suppose this second part of the issue is disastrous as you don't really need to know how many days there are until the next audit of an audit that has already been carried out in the past (perhaps these should read as zero, or freeze at the number of days remaining when the next audit was completed?).
However, the first part of this issue shows the wrong date for the next audit on assets. It might also be beneficial for audit logging to see when the audit was carried out with respect to the previous audit's due date (ie was it early/on-time/late)

Many thanks,

**Comment by FOOSAYS** [comment]
I am still seeing this issue on the online Demo.

Creating Asset A
Auditing asset, SET next audit date = 22/01/2018 (Today)
Run Audit Report, GET days until next audit = 0
Run Audit Report, GET next audit date = 22/01/2019

Re-Auditing asset, SET next audit date = 29/01/2018 (Today)
Run Audit Report, GET days until next audit = 6
Run Audit Report, GET next audit date = 22/01/2019

The next audit date does not change.

**Comment by snipe** [comment]
This should be fixed on master now
