### ISSUE TITLE
Only Superuser can create models

### ISSUE THREAD

**Issue by jorgearagon37** [snipe/snipe-it#4326]
[edited to update debug error seen]
#### Expected Behavior (or desired behavior if a feature request)

I've added a group of users.  The group has been granted all permissions except superuser.  I expected them to also be able to create new models for assets.

-----

#### Actual Behavior

The group cannot view previously created models or even new models under <url>/models.  They can create a new one, and upon creation, the list stays empty, but the "successful creation of models" display pops up.  New models can only be seen when logged in as superuser.  I have granted one of the users superuser access, and they were able to see the gear icon on the left menu, the models listed under <url>/model, and were able to create new assets with new models.

Users who have all permissions except for superuser can create new assets with pre-existing models.

-----

#### Please confirm you have done the following before posting your bug report:

- [ X ] I have enabled debug mode 
- [ X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  --Fresh
- Version of Snipe-IT you're running --V4.0.9 Build 189 (g907b909
- Version of PHP you're running --Version 7.1.9
- Version of MySQL/MariaDB you're running  --MariaDB Version 5.5.56
- What OS and web server you're running Snipe-IT on  -- Centos 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) --install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

array:4[
      "ability" => "view"
      "result"  => "false"
      "user"    => 7
      "arguments" => "[0 => App\Models\Asset]"

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

<url>/models  

My guess if you want a specific web element, the submit button on the footer of the div "box-body"

- If a stacktrace is provided in the error, include that too.

Not sure about this part.

- Any errors that appear in your browser's error console.

No errors in browser console

- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.

Error is reproducible in demo when creating a user, adding all permissions except superuser.  <url>/models is accessible, and user can create new model, but no previously created models or newly created models show up.

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

None

- Include what you've done so far in the installation, and if you got any error messages along the way.

No errors in the installation.

- Indicate whether or not you've manually edited any data directly in the database

Have not manually edited data directly in database.  

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by dmeltzer** [comment]
I think this is fixed in develop with https://github.com/snipe/snipe-it/commit/3cea12565b2cd3c00e27dcaa53f7f37caac92940
