### ISSUE TITLE
Importing Assets Error - Model & Asset ID required.

### ISSUE THREAD

**Issue by JayRad11** [snipe/snipe-it#4328]
#### Expected Behavior (or desired behavior if a feature request)

Would like to import an Assets CSV that I tailored from the Snipe-IT Demo Asset CSV. I simply copied and pasted into the existing CSV columns. I've generated the Asset tags values via excel prior to importing. (I've referenced other support tickets but couldn't resolve from them)

Otherwise I am loving the system and interface. I'm new to Snipe-It, and the community :)

Thank you

-----

#### Actual Behavior

**Item | Errors
-- | --
  | Asset "": The model id field is required.The asset tag field is required.**

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
Fresh 
- Version of Snipe-IT you're running
snipe-it-4.0.10
- Version of PHP you're running
php 7.1.9
- Version of MySQL/MariaDB you're running
5.7.19
- What OS and web server you're running Snipe-IT on
Windows Server 2012 / WAMP
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual Installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Did you map the fields correctly in the field mapper GUI?

**Comment by JayRad11** [comment]
Hey Snipe, thanks for the response.

Yep I've been using the import mapper to align the headers and fields, which I thought I was using correctly.. apparently I may not be after all. I've been drilling through the knowledge base and other similar support tickets, but I continue to receive the same error. 

Update: After renaming a couple headers a few fields to match the import fields, I now have a **category id error** as well. Not sure what I am doing wrong. Please find the attached snapshot.


![error-snipe-it-import](https://user-images.githubusercontent.com/33159919/32175010-e0c9f316-bd59-11e7-8513-41ccbcda031d.PNG)


Thanks

**Comment by JayRad11** [comment]
UPDATE:
Okay so I guess I didn't read enough.. After adding some model names in my CSV, things begin to cross over. 

My current model name fields in my CSV are empty - My situation is that I am basically starting our inventory FRESH from scratch. I was going to import everything in our inventory in, except without any model names or numbers. (I was going to assign those within Snipe-IT)

I assume that filling these model fields are a complete must when preparing your CSV.

**Comment by hamilhsys** [comment]
I am having the same issue.  I installed Snipe It from the master script on Ubuntu 16.04 LTS yesterday.  I have verified that my column reads Modelid on my CVS.  I am even trying to import a model that I have already created in snipeit.

I am new to Github.  I wanted to first off say that @snipe, you are awesome and thanks so much for a great program!  I work in IT and have implemented snipeit at another client of mine.  It is great!

**Comment by snipe** [comment]
Thanks for the kind words :)

Is it ignoring ALL of the models, or just a few? Are you mapping the field correctly to Model Name and Asset Tag in the field mapper? Any additional info you can give us would be really helpful.

**Comment by JayRad11** [comment]
In my case, everything imported successfully with the exception of the **Asset Name**. (This is after I manually assigned model names to all assets in the CSV prior to import) Any idea what may cause the **Asset Name** to not cross over @snipe ?  (You can find my import mapper fields in the snapshot above)

Thanks a bunch :)

**Comment by hamilhsys** [comment]
@JayRad11 I am experiencing the same thing.  I got the model to import by changing my column name on the csv file to "Model Name" the only thing that I cannot get to import now is Asset Name.  There does not seem to be a corresponding Import Field for Asset Name.  Did you ever figure it out?

**Comment by JayRad11** [comment]
Unfortunately, I never figured out the issue @hamilhsys 

Luckily our organization isn't too large, so I've had one of our temps take the reins in manually adding our Asset's names. You are correct though; as I could not find or create a corresponding field that would facilitate my CSV **Asset Name** column data either. (I must have tried every field and spelling combination)

**Comment by aRiflip** [comment]
Sorry, for bringing this post back up. I tried to use "Item Name" where "Asset Name" was asked. I think I have total balls'd up my configuration. I can no longer see Assets in the "List All" tab. The faulty asset can be seen in the recent activity and the Assets by Status but can't be searched for. Luckily I only have 6 assets on the system so far. I don't think I'll be using the importer tool after I rebuild the server.

**Comment by toehold** [comment]
Encountered the same issue, running Version v4.8.0 - build 4186 (master); I changed the Name: Asset Name to Items Name and the import worked.

**Comment by Excalibur025** [comment]
Yup, encountered the same issue v6.0.14 build - 9715 (master). Changing 'Asset' to 'Item' works temporarily but issues is still present.

Side note: LOVE this program. Saved our IT dept from a real nightmare.
