### ISSUE TITLE
Check Asset Availability by Date

### ISSUE THREAD

**Issue by bisongde** [snipe/snipe-it#4337]
Is there any current or planned means of checking availability of an asset by date? Extra points for a calendar visualization for this so we can quickly see stock availability across a range of dates. I'm aware of issue #49 but not certain if what it's requesting matches what I have in mind.

In basic terms:

**-if we assign an expected check-in date to each item as checked out
-then we should be able to calculate future asset availability (in a macro sense, so models) based on when items are due to return**

Possible usage scenario: 

A large project is coming up on 12/18 and we'll be hiring a freelance team to work on it. We know that 50 new users are incoming, and based on current statistics we only have 20 systems available to deploy. 

This feature would allow us to see that despite not having enough stock currently, a project is due to wrap and return equipment on 11/17 and thus we'll have more than enough equipment to cover the project starting 12/18 without needing to buy additional.

**Here's an example of how this is implemented in a sales/rental focused inventory management system as a frame of reference:**

![asset tracking](https://user-images.githubusercontent.com/32623193/32140346-c420a366-bc34-11e7-9e3a-27d7a116f5b6.JPG)

This is probably possible by generating a report for expected check-in and manually adding assets due for check-in prior to the upcoming project start date to the current availability numbers, but it would be nice if the system could do this for us and provide a number of available assets/asset models on a future date, or a range of future dates.

This could also be useful for facilities management: offices have a finite number of seats and need to be able to forecast when they'll be over capacity based on upcoming staffing needs. For this date we need X additional, but we only have Y available, we have a deficit of Z. 

This is the last piece of the puzzle for me in terms of getting Snipe to fit our needs and would solve a number of issues for us if it could be implemented, even if it's just a simple list of dates with available asset quantities for each date.

**Comment by bisongde** [comment]
Hey @snipe, I remember you mentioned on Twitter that you guys were working on a prototype for this, any updates? Thanks!

**Comment by DrDaleks** [comment]
Hi. I'd like to bump this issue up. We'd like to indicate an asset due date during check-out (let's say manually for now). Is that something available or in the works? @snipe Should this be re-opened?

**Comment by snipe** [comment]
It's not currently being worked on and we have bigger fish to fry before we can consider working on it :(
