### ISSUE TITLE
Cant generate key with artisan

### ISSUE THREAD

**Issue by thuekx** [snipe/snipe-it#4341]
#### Expected Behavior (or desired behavior if a feature request)

i wanna generate Key for snipe it .env

-----

#### Actual Behavior

when i do php artisan key:generate i've got an error
---------------------------------------------------
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/html/artisan on line 31
---------------------------------------------------

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? fresh install
- Version of Snipe-IT you're running (i'm using git clone not sure, actually the last one)
- Version of PHP you're running (5.4.16)
- Version of MySQL/MariaDB you're running (5.5.56 mariadb)
- What OS and web server you're running Snipe-IT on (Apache On Centos 7)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) (git clone)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error 
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by thuekx** [comment]
Sorry my bad, 
i think is about php issue, i just miss using old php version, but after i installed php 5.6 
i got this
----------------------------------------------------------------------------------------------
php artisan key:generate 
PHP Warning:  require(/var/www/html/vendor/composer/../aws/aws-sdk-php/src/functions.php): failed to open stream: No such file or directory in /var/www/html/vendor/composer/autoload_real.php on line 66
PHP Fatal error:  require(): Failed opening required '/var/www/html/vendor/composer/../aws/aws-sdk-php/src/functions.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/vendor/composer/autoload_real.php on line 66
---------------------------------------------------------------------------------------------------

**Comment by madd15** [comment]
have you run `php composer.phar install --no-dev --prefer-source` ?

**Comment by thuekx** [comment]
thank you for the answered madd15,

i already install that, and install 88 repositories so far i now...

but after that i try to run key generate and face that error

**Comment by madd15** [comment]
maybe give this comment a read and see if it helps at all https://github.com/snipe/snipe-it/issues/3032#issuecomment-266476641

**Comment by thuekx** [comment]
yeah i already read that but no luck

this is mine
------------------------------------------------------------
drwxr-xr-x.  8 apache apache    4096 Oct 30 11:46 public
drwxr-xr-x.  7 apache apache      80 Oct 30 11:46 storage

and this for upload
drwxr-xr-x.  8 apache apache  4096 Oct 30 11:46 uploads
------------------------------------------------------------

still face that error

**Comment by madd15** [comment]
was there any errors whilst running `php composer.phar install --no-dev --prefer-source`?
does the file `/var/www/html/vendor/aws/aws-sdk-php/src/functions.php` exist?

have you tried to rerun the composer install?

**Comment by thuekx** [comment]
i'll try to re run composer install,
i'll be back with the result, thanks by the way for the support madd

**Comment by thuekx** [comment]
hi i'm back, the result is aws is not installed and cant be installed with --prefer-source,

it solved when i using --prefer-dist

thank you for your help all
