### ISSUE TITLE
multiple checkout labels while creating new asset

### ISSUE THREAD

**Issue by ctacay** [snipe/snipe-it#4342]
multiple checkout labels while creating new asset
using the following:
  
Snipe IT:  v4.0.11  build 264 (gc776fa4)

PHP Version | 7.1.9
-- | --
Laravel Version | 5.4.36
![image](https://user-images.githubusercontent.com/32893706/32167518-833a9c68-bd82-11e7-8159-c787dfc423e5.png)

**Comment by madd15** [comment]
@ctacay This is a feature as you can checkout to a user, asset or location

**Comment by snipe** [comment]
Yes, we have to improve the UI of that, but I'm honestly not sure how to do that where it makes the most sense but doesn't increase the number of clicks someone has to go through to check something out. Maybe default to checkout to user, and let people toggle the other ones on (turning the non-selected ones off)

**Comment by tbradsha** [comment]
+1

**Comment by snipe** [comment]
This UI has been fixed in more recent versions
