### ISSUE TITLE
Bulk Checkout - displays model names instead of Asset names

### ISSUE THREAD

**Issue by syb1234** [snipe/snipe-it#4344]
#### Expected Behavior (or desired behavior if a feature request)

While using bulk checkout page, I expect to see Assets names in the "Assets" field.

-----

#### Actual Behavior

Only the asset's model is displayed.
<img width="1109" alt="screen shot 2017-10-30 at 11 53 36 am" src="https://user-images.githubusercontent.com/21043402/32181214-340dd320-bd6a-11e7-8406-12df6a052d07.png">

I've changed one of the asset name to see if it would display properly: 
<img width="877" alt="screen shot 2017-10-30 at 11 58 02 am" src="https://user-images.githubusercontent.com/21043402/32181270-54210dbc-bd6a-11e7-865c-8e9718c77268.png">

but only the model is displayed:
<img width="706" alt="screen shot 2017-10-30 at 12 05 35 pm" src="https://user-images.githubusercontent.com/21043402/32181462-c9ac4254-bd6a-11e7-8c9e-7f78906cff90.png">

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode - Yes
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) - Yes

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh install, also tried on the Demo site (https://demo.snipeitapp.com) and same issue.
- Version of Snipe-IT you're running: v4.0.15 build 384
- Version of PHP you're running: v7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running: mysql 5.6.29
- What OS and web server you're running Snipe-IT on: Docker ubuntu0.16.04.1
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error:  No error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: http://localhost:32770/hardware/bulkcheckout, and on demo: https://demo.snipeitapp.com/hardware/bulkcheckout. I'm in the body of the page in Assets field (ul.select2-selection_rendered).
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. Yes
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. Created Companies, Groups, Manufacturers, Locations,  Assets Models, Assets and tested the builk checkout function.
- Indicate whether or not you've manually edited any data directly in the database: No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
This should be fixed on develop

**Comment by syb1234** [comment]
Thanks
