### ISSUE TITLE
500 Error On Custom Asset Report - Only above 20,000 Assets

### ISSUE THREAD

**Issue by barrycarey** [snipe/snipe-it#4347]
#### Expected Behavior (or desired behavior if a feature request)

Generate a custom asset report

-----

#### Actual Behavior

500 Server Error

Issues started once we exceeded approximately 20,000 assets.  Report worked when around 15k.  

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Same issue on Fresh or Upgrade
- Version of Snipe-IT you're running 4.0.15
- Version of PHP you're running 5.6.30
- Version of MySQL/MariaDB you're running  5.7
- What OS and web server you're running Snipe-IT on Windows Server 2008 R2 with IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Git Clone
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Custom Asset Report
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo - That URL is a 404
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. - Standard install per guide
- Indicate whether or not you've manually edited any data directly in the database - No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
> Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo - That URL is a 404

That doesn't 404. Where are you seeing it 404?

My guess is that it's running out of memory or timing out, but would need your app/server logs to confirm that. You'd have to allocate more memory/increase script execution time for PHP.
