### ISSUE TITLE
Checkout License Seat to a specific asset serial number or asset tag 

### ISSUE THREAD

**Issue by luisaped131** [snipe/snipe-it#4348]
#### Expected Behavior (or desired behavior if a feature request)

When checking out a license i dont have an option to assign/checkout license to a specific asset, i dont see serial numbers, only the asset model name multiple times, how would i know if i am assigning it to the correct asset?
Checkout to user is not an option as we mostly want to have control over the assets and not who is using it at the moment.

-----

#### Actual Behavior

Need to be able to assign to the specific asset based on serial number or asset tag. 

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? yes
- Version of Snipe-IT you're running Latest clone as of 10/27/2017
- Version of PHP you're running 7.0.22
- Version of MySQL/MariaDB you're running mysql 14.14
- What OS and web server you're running Snipe-IT on ubuntu 16.04.1
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
> Is this a fresh install or an upgrade? yes

That isn't a yes or no question. Is it a fresh install, or is it an upgrade?

> Version of Snipe-IT you're running Latest clone as of 10/27/2017

Which branch?

I believe this has already been resolved on develop.

<img width="783" alt="screen shot 2017-10-30 at 6 14 13 pm" src="https://user-images.githubusercontent.com/197404/32203092-49e2d41e-bd9e-11e7-8143-98300c1dd8da.png">

**Comment by luisaped131** [comment]
Oops sorry on that... it is a fresh install.

Not sure what branch i downloaded via command:
git clone https://github.com/snipe/snipe-it

I see on your pic it works, for me is not displaying that way.

**Comment by snipe** [comment]
You're on master, the fix is on develop.

**Comment by luisaped131** [comment]
Thank you but can you please tell me the issue# or title of it for the fix? i cant find it, the only one i see somewhat related is #432 but there is no link to a fix.

**Comment by snipe** [comment]
It's been merged into master, so just do a fresh pull from master and run migrations.

**Comment by luisaped131** [comment]
That worked for me, thank you!
