### ISSUE TITLE
Feature Request: Modify values of custom fields through the API

### ISSUE THREAD

**Issue by atinsley** [snipe/snipe-it#4349]
Hello,

I was experimenting with writing a PowerShell script for our PCs to interact with the Snipe-IT API to automagically update our asset database with relevant information like its current IP address, OS version, etc but unfortunately was unable to modify the values of a custom field.  I was able to modify the standard fields without issue, but attempting to modify a custom field's value has no effect.

#### Expected Behavior (or desired behavior if a feature request)

Desired behavior: Passing in something like {"_snipeit_mac_address_1":"FF:FF:FF:FF:FF:FF"} in an HTTP PATCH request to a URL like "https://demo.snipeitapp.com/api/v1/hardware/1" will modify the current value of a custom field in the database.

-----

#### Actual Behavior

The API responds with HTTP 200 {"status":"success","messages":"Asset updated successfully.","payload":{\<payload here\>}} without actually making the update.  The value of the custom field has the exact same value as it did before the API request was made.

-----
#### Provide answers to these questions:
-Current version of Snipe-IT:  Hosted installation of v4.0.15 build 384

**Comment by snipe** [comment]
That's definitely on the list, it just didn't make it into 4.0. 4.0 was taking long enough already.

**Comment by atinsley** [comment]
Thanks for replying, Snipe.  I'll just encode these details into the Notes section until the custom fields functionality is available.

**Comment by snipe** [comment]
This should be fixed on develop now, if you're feeling adventurous :)

**Comment by chadnielsen** [comment]
Looking forward to this change in the master!
