### ISSUE TITLE
qrcode path repeated path when viewing assets

### ISSUE THREAD

**Issue by ctacay** [snipe/snipe-it#4352]
#### Expected Behavior (or desired behavior if a feature request)

qrcode path repeated path when viewing assets.
When opening an asset to view it seems that the image for qrcode is not showing. and the path is doubled.

-----

<img width="409" alt="snipe1" src="https://user-images.githubusercontent.com/32893706/32222648-89e38256-be53-11e7-8722-dc4f550b14a2.PNG">
<img width="651" alt="snipe" src="https://user-images.githubusercontent.com/32893706/32222649-8a11f596-be53-11e7-9f33-6e66be445f92.PNG">

**Comment by snipe** [comment]
What's your APP_URL in your .env?

**Comment by ctacay** [comment]
App Url= pchost


________________________________

**Comment by snipe** [comment]
You need to include the protocol as well, per the configuration docs. https://snipe-it.readme.io/docs/configuration#section-required-basic-app-settings
