### ISSUE TITLE
403 Forbitten

### ISSUE THREAD

**Issue by IKSMaurizio** [snipe/snipe-it#4353]
#### Expected Behavior (or desired behavior if a feature request)
Good morning.

When I try to import the asset, I get the following error:

 403 Forbidden
Sad panda. You are not authorized to do the thing.Maybe return to the dashboard, or contact your administrator
(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
 It is fresh install

- Version of Snipe-IT you're running
SNIPE-IT: Version v4.0.15 build 339 (g17b2719)

- Version of PHP you're running
PHP Version =>7.1.10

- Version of MySQL/MariaDB you're running
mysqlnd: Version =>  5.0.12-dev -20150407

- What OS and web server you're running Snipe-IT on
Linux: CentOS Linux release 7.4.1708
APACHE =>2.4

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Used=> install.sh for install SNIPE-IT

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
What are your user permissions?

**Comment by IKSMaurizio** [comment]
Administrator

Thank you



Da: snipe [mailto:notifications@github.com]
Inviato: martedì 31 ottobre 2017 16:41
A: snipe/snipe-it
Cc: Maurizio Finocchiaro; Author
Oggetto: Re: [snipe/snipe-it] 403 Forbitten (#4353)


What are your user permissions?

**Comment by snipe** [comment]
What are your specific permissions though? Let me see a screenshot or the JSON in your database. Is possible you belong to a permission group where creating assets is denied?

The gate on that just needs you to have the ability create assets:

`$this->authorize('create', Asset::class);`

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by SashaankPandey** [comment]
> Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.
> 
> ![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif) [ ![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif) ](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif) [ ](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

![image](https://user-images.githubusercontent.com/91901535/194313234-102fdd3a-d625-4426-913e-d5ad06e84f2a.png)
