### ISSUE TITLE
QR code generation

### ISSUE THREAD

**Issue by D-Nordin** [snipe/snipe-it#4355]
#### Expected Behavior (or desired behavior if a feature request)

When creating a new asset it is supposed to generate a QR or Barcode to go with the asset.

-----

#### Actual Behavior

When generating a new asset the QR/Barcode is not generated. When inspecting the element or trying to open it in a new tab it gives me a 404 error

![image](https://user-images.githubusercontent.com/22399852/32246927-0086ae80-be57-11e7-8a76-a1299b8fac75.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [Y] I have enabled debug mode 
- [Y ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  
fresh install

- Version of Snipe-IT you're running
Version v4.0.15 build 339 (g17b2719

- Version of PHP you're running
7.1.10

- Version of MySQL/MariaDB you're running
10.0

- What OS and web server you're running Snipe-IT on
Windows 7 using iis

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual install

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
no error

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the 
View Asset "computer name" page
happens with all assets

- If a stacktrace is provided in the error, include that too.

- Any errors that appear in your browser's error console.
qr_code Failed to load resource: the server responded with a status of 404 (Not Found)

- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
no. QR code shows up fine in demo

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
couldn't find anything useful. 

- Include what you've done so far in the installation, and if you got any error messages along the way.
no errors so far

- Indicate whether or not you've manually edited any data directly in the database
no data manualy entered

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by D-Nordin** [comment]
Fixed the problem by switching the app-url to the url of the website. whoops

**Comment by jeyanthinatarajan** [comment]
Hi Snipe

When creating a new asset the QR code is not generating with the asset.
