### ISSUE TITLE
When generating labels the asset tag number is is not aligned right.

### ISSUE THREAD

**Issue by luisaped131** [snipe/snipe-it#4357]
![at](https://user-images.githubusercontent.com/33237911/32252864-f5c51862-be54-11e7-9227-07da1b9c13b6.JPG)

#### Expected Behavior (or desired behavior if a feature request)

-----

#### Actual Behavior

-----

#### Please confirm you have done the following before posting your bug report:

- [y ] I have enabled debug mode 
- [y ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? fresh install with a pull today.
- Version of Snipe-IT you're running Version v4.1.0 build beta2 (g3b498ef)
- Version of PHP you're running 7.0.22
- Version of MySQL/MariaDB you're running mysql 14.14
- What OS and web server you're running Snipe-IT on ubuntu 16.04.1
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. 
    Works on demo
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database 
   no edit

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I don't really understand what you're saying here. Can you clarify?

**Comment by luisaped131** [comment]
before when printing the labels would display like this
N: assetname
T: asset tag number
S: serialnumber

now when printing it displays like this
N:assetnameT:asset tag number
S:serialnumber

not sure if you can see the picture i originally attached.

**Comment by snipe** [comment]
Can you pull the latest from master and let me know if you're still seeing this?
