### ISSUE TITLE
Feature request: Permission to allow users to view only assets assigned to them

### ISSUE THREAD

**Issue by tnewton1** [snipe/snipe-it#4358]
#### Expected Behavior (or desired behavior if a feature request)

I'd like to have a permission option to allow users to only view assets assigned to them. For example, John Doe logs in and can only view assets assigned to him, not the entire company, including any software licenses. There should also be permission to allow this user to check in any assets assigned to them.

-----

#### Actual Behavior

Currently, there is only an "Assets: View" permission so a user with restrictions can view every asset, license, etc. assigned to their company including the ability to check in assets not assigned to them.

-----

#### Please confirm you have done the following before posting your bug report:

- [N/A ] I have enabled debug mode 
- [Y ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

Version v4.0.15 build 339 (g17b2719)

**Comment by snipe** [comment]
This already exists. Jut deny them all other privileges, and when they login, they will only see their own assets.

**Comment by dheche** [comment]
But if we deny them in "Assets: View" permission, they can't see detail asset that already assigned to them. They only can see Model, Asset Tag, Serial and Name.
