### ISSUE TITLE
create asset model with Empty String model NO. will not match when import custom fields csv file without 'Model Number' column 

### ISSUE THREAD

**Issue by dovefi** [snipe/snipe-it#4359]
i use snipeit v4.0.15
 i have created a asset model which has no model number, and create a custom field name 'inner_ip',
 when i import custom field csv file, i did not gave a model number culumn in this file , it import success, but the inner_ip column  never show a value. only if i add model number column and gave it an empty string ,import angin ,the inner_ip show.
to solve this question,i check the databases ,i found out what is going on , when i created asset model and did not gave a model NO . it insert database model NO. with empty string. but when i import custom fields whitout 'Mode Number' column  i will insert model NO. with null .they did not match . so is this a bug ?? because i have read the document https://snipe-it.readme.io/docs/importing  , the Model Number column is not necessary。

**Comment by snipe** [comment]
@dmeltzer can you take a look at this?

**Comment by dovefi** [comment]
i use PHP 5.6.x and mysql 5.6

**Comment by snipe** [comment]
@dmeltzer ping? (I know you're busy - I'm just hesitant to mess with the importer too much when you're not around.)

**Comment by dmeltzer** [comment]
Hi I tried to reproduce this in a few different ways and failed.  How are you creating the asset model initially, through the ui or importing?  I did PR a related fix, so it might have fixed this too..
