### ISSUE TITLE
Web UI says "backup created ok" when mysqldump binary is missing

### ISSUE THREAD

**Issue by lukebigum** [snipe/snipe-it#4360]
#### Expected Behavior (or desired behavior if a feature request)

A very minor UI bug. When creating a manual backup, if you don't have a MySQL installed or the path to mysqldump is wrong, the Web UI pops up a "backup created successfully" message when it fails. The logs contain the right error:

`production.ERROR: backups backups : error: Failed to backup  because: The dump process failed with exitcode 127 : Command not found : sh: /usr/bin/mysqldump: No such file or directory
`

-----

#### Actual Behavior

The UI should return some sort of red "failed" message instead.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
Upgrade from v2.0.5 -> v4, but moved server so mysqldump was missing
- Version of Snipe-IT you're running
v4.0.15
- Version of PHP you're running
5.6
- Version of MySQL/MariaDB you're running
5.1
- What OS and web server you're running Snipe-IT on
CentOS 6 with SCL
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
https://SERVER/admin/backups
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
See above in the Laravel log
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
> if you don't have a MySQL installed

If you don't have Maria/MySQL installed, you wouldn't be using the system in the first place, so I'm not sure how this is an issue.

**Comment by lukebigum** [comment]
You can have PHP's MySQL client installed without the actual MySQL binaries on a server. I have snipe-it on a server separate to where the database runs. It's how I noticed this issue.

**Comment by snipe** [comment]
Ah, right - that makes sense. It's an uncommon use case, but it's a valid one, for sure. I'm not 100% sure that's something we can fix, since the library we use to generate those backups usually throws an error if you try to call mysqldump and mysqldump isn't installed (or the config is pointing to the wrong place for it.) I'm honestly not sure why it would fail silently there.

**Comment by linglongtong** [comment]
I have similar question. 

My application server and database server are not the same one, so I can not use snipe backup function, the error shows like:

![image](https://user-images.githubusercontent.com/23185284/34026438-112f2610-e191-11e7-8509-0625b3e23cb4.png)

@snipe

**Comment by snipe** [comment]
@linglongtong I don't believe the backup package we use supports remote databases - but if it did, you'd still need mysqldump to be installed.
