### ISSUE TITLE
Importing via GUI stuck at Processing

### ISSUE THREAD

**Issue by robmorin** [snipe/snipe-it#4361]
#### Expected Behavior (or desired behavior if a feature request)

Expected to import csv file of Assets. Csv file format is copied from sample_csvs/MOCK_ASSETS

-----

#### Actual Behavior

After clicking on import, it just hangs at Processing....

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh install(got latest from git today)
- Version of Snipe-IT you're running   v4.1.0 build beta2 (g3b498ef)
- Version of PHP you're running  5.6.31-6+ubuntu16.04.1+deb.sury.org+1
- Version of MySQL/MariaDB you're running   5.7
- What OS and web server you're running Snipe-IT on  Linux Ubuntu 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Git clone
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error   On the import page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.  None
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. Not aloud to import files on demo site 
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
Nothing
- Include what you've done so far in the installation, and if you got any error messages along the way.
Nothing
- Indicate whether or not you've manually edited any data directly in the database 
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Please make sure the storage directory and all subdirectories are writable, and make sure your APP_URL exactly matches your Snipe-IT install URL. 

Without logs, there's no much we can help with, since we can't tell what's happening.

**Comment by robmorin** [comment]
Storage directory is ok, i can see file in the dir after its uploaded. I fixed the APP_URL. 
Now it uploads & processes but only shows 1 line out of 114 lines and says Success Your file has been imported. I guess I'm gettign closer. Please find below my csv file sample.

Name,Email,Username,item Name,Category,Model name,Manufacturer,Model Number,Serial number,Asset Tag,Location,Notes,Purchase Date,Purchase Cost,Company,Status,Warranty,Supplier,MAC Address,IP Address,OS,OS Version
Adrien-PC,rmorin@hardent.com,Adrien,Item Name,Put Something Here,Put Something Here,Dell Inc.,1234567,1234567,1234567,Montreal,Notes go here,Date of purchase,Cost,Hardent,Deployed,Oct-17,Where did we get it,B8:CA:3A:CC:01:AE,192.168.2.138,Windows,Windows 7

And I do not see my 3 custom fields that are in the csv file in that one imported record.

What now? Nothing show in debug mode

Thanks..

**Comment by robmorin** [comment]
Update, its the last line of the file that gets imported...

Which is this:

zion.domain.com,user@domain.com,,,Put Something Here last line,Put Something Here last line,Super Micro Computer,1234567,1234567,1234567,Montreal,Notes go here,Date of purchase,Cost,Company,Deployed,Oct-17,Where did we get it,0C:C4:7A:CD:2C:C2,192.168.2.253,Windows,Windows 7

**Comment by robmorin** [comment]
FYI, I WAS able to import your test file MOCK_ASSETS. SO i guess my file structure is not correct. I will copy my info into your test file and see how that goes.

**Comment by robmorin** [comment]
SO now i can upload ok, and it does not complain, but i only see 2 assets out of 114?? I made sure the asset tag and model number have something there, some fields are blank though. Also the categories were populated as well as Models.  This is getting too confusing  now....

**Comment by snipe** [comment]
@dmeltzer - can you take a look when you get a moment?

**Comment by dmeltzer** [comment]
This usually is related to line endings I think.  the csv processor isn't detecting them properly and losing lines.  Make sure they are saved with windows line endings, or alternatively that auto_detect_line_endings is on in the ini.  Can you check into this?

**Comment by robmorin** [comment]
I enabled it, but get same result... :(

Anything else I should try?

auto_detect_line_endings 	1 	1

Rob Morin
Montreal, Quebec
HTTP://TheLoungeSound.ca
