### ISSUE TITLE
Ready to deploy bug

### ISSUE THREAD

**Issue by wesleytb13** [snipe/snipe-it#4362]
#### Expected Behavior (or desired behavior if a feature request)

When I go to Assets -> All Ready to Deploy it use to show all assets that were ready to deploy. 

-----

#### Actual Behavior

It shows no assets in "All Ready to Deploy". It use to, but I went to the All Ready to Deploy section (from the Assets -> All Ready to Deploy in the sidebar) and then selected all devices to download to a CSV file to see if I could then import this list to another instance of Snipe-IT but then I thought I remembered it would only import users so while all the items were still selected (boxes checked) I clicked on the Import option (from the sidebar) to verify this. Now when I go back to Assets -> All Ready to Deploy there are no assets listed at all. All assets are still listed in the "List All" section though so it did not delete them. I have tried cloning and existing asset and creating a new asset and neither put an entry in the "All Ready to Deploy" section. I have gone to status labels and changed the Status type for Ready to Deploy and then changed it back and that did not fix the issue. I have restarted the server as well as the machine it is running on and it still does not work. 

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? fresh install
- Version of Snipe-IT you're running Version v4.0.15 build 339 (g17b2719)
- Version of PHP you're running PHP 7.1.9
- Version of MySQL/MariaDB you're running MySQL 5.7.19
- What OS and web server you're running Snipe-IT on Windows 10, WAMP
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) WAMP
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
This error was there before the problem so I don't believe it's related (I have someone else working on the LDAP issue). "[2017-11-01 09:03:29] production.ERROR: There was an error authenticating the LDAP user: ldap_start_..."
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
I am experiencing the issue when I highlight Assets and click on All Ready to Deploy from the sidebar
- If a stacktrace is provided in the error, include that too. 
- Any errors that appear in your browser's error console. No errors
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. I could not get this to reproduce on the demo server
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
I've just added 68 assets, 7 users. Set up a few groups. Played around checking in and out assets. The issue that caused the error I'm reporting was the only thing I have done during this current session. 
- Indicate whether or not you've manually edited any data directly in the database - I have not

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Without an error log of some kind, I don't have any way of knowing why you'd be seeing this, especially since it can't be reproduced on the demo. Try clearing your cookies maybe.

**Comment by wesleytb13** [comment]
I was afraid of that. There were no errors generated in an error log other than the LDAP error. I will see what else I can figure out. This was just a test install before we implemented it on an actual server so not a huge issue - thank you.

**Comment by snipe** [comment]
Have you tried clearing your cookies as well? Sometimes that helps.
