### ISSUE TITLE
Feature Request: Integration with Dell Warranty API

### ISSUE THREAD

**Issue by connor2337** [snipe/snipe-it#4363]
#### Expected Behavior (or desired behavior if a feature request)

When Manufacturer = 'Dell', then use the string in the asset tag field to call info from the Dell Warranty API, and display asset info from Dell (warrantyEndDate, warrantyStartDate, purchaseDate, etc.)

An option to disable/enable this function entirely on a per asset/asset model basis, and a field in settings to set your Dell Warranty API Key (they require auth to call to the server)

Choices of the given fields from dell would be nice as well. e.g. "We don't want X, but we want Y."

-----

#### Actual Behavior

No dell api integ. #sadface

-----

#### Please confirm you have done the following before posting your bug report:

- [] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
We don't currently have any plans to do manufacturer/supplier API integrations, but our long-term plan is to make Snipe-IT mode modular so folks can create their own plugins that could supplement this kind of functionality.

**Comment by VanillaNinjaD** [comment]
I like the question and the response. This is something I have looked at in the past but got bogged down and forgot about.

Right now we are using a pretty quick and dirty integration with their support website just via URL crafting.

**Comment by connor2337** [comment]
It would be pretty awesome to have a modular-type mode, because its a sweet api and having the ability to integrate that as well as other apis would be nice. Google maps API integration with GPS enabled devices would be literal heaven, too. See an active location of assets, and up to date warranty and service info straight from dell? *faints*

**Comment by JustinGGoodwin** [comment]
> We don't currently have any plans to do manufacturer/supplier-specific API integrations, but our long-term plan is to make Snipe-IT mode modular so folks can create their own plugins that could supplement this kind of functionality.

We are using Snipe-IT temporarily and are setting up budgeting for future years for a solution that actually does this and integrates with the API.   You should reconsider adding this to the system.  These are the types of integrations that large companies look for when choosing an asset inventory program.   You're losing sales by not having this available.
