### ISSUE TITLE
Document for installation on Raspberry PI

### ISSUE THREAD

**Issue by DillonLeeRECF** [snipe/snipe-it#4364]
I was wondering if anyone has had any luck on finding documents for installing on a raspberry pi for testing deployment? This would be for fresh installs of Snipe-IT of any version. Any documents or systems that are currently being looked at using these would love to hear some insight.

**Comment by snipe** [comment]
I believe at least @scottdmay is running this on a Pi. Not sure if he has time to put together some docs, but I hope so. That would be pretty cool. :)

**Comment by Jhamende** [comment]
Didn't try it yet on my pi but would the linux installation docs not be the same for pi ?

**Comment by DillonLeeRECF** [comment]
I will try later today, the main concerns I have are:
First will the architecture need to be something different other then ARM.
Second how slow will it be?
Third setting up a backup on our server. (Well this is a me problem I guess)
Fourth can I just use lamp for half of the setting it up phase.

**Comment by Jhamende** [comment]
1. I'm not an expert in the area but I don't think the architecture does really matter here. I already ran Laravel applications on my pi without any problem. 
2. If the main task of your pi will be running snipe it, I think it will run smoothly. 
3. For your backups you can use crontab. 
4. Didn't use lamp, but I suppose you can. in my case I installed apache2, PHP7, mariadb, and phpmysql individually.
