### ISSUE TITLE
Feature Request: AzureAD & InTune Integration 

### ISSUE THREAD

**Issue by nathank1989** [snipe/snipe-it#4365]
Hello,
First off I have to say how awesome this system is. Used it for my last job, worked wonders and want to deploy it in my new job.  We’re using cloud-only AzureAD for identity and InTune for our devices. InTune reports a lot of useful information (serial number, make/model, disk space, etc). It would be so helpful if there were a way to sync certain InTune devices as assets and monitor their deployment to AzureAD accounts. Probably not a highly requested feature, but would be cool if it was possible.

**Comment by snipe** [comment]
Hi @nathank1989 - thanks for the kind words :)

Re: AzureAD, I believe this is already possible. See https://github.com/snipe/snipe-it/issues/3810

Re: InTune, it's unlikely we'd build for a specific vendor like that, but we do have a REST API in the 4.x versions that should allow someone with some dev chops to be able to rig together some scripts to push data from InTune into Snipe-IT. 

What I'd expect or hope, moving forward, is that someone might add some artisan commands to handle importing from different vendor agents so users can easily cron those - but that may not work, depending on how each agent works.

**Comment by JemTaylorUHI** [comment]
I would like this to be a real thing :)

**Comment by AustinHarisch** [comment]
This would be an awesome feature! I work in a school and we use Intune to manage all of our Windows devices, so being able to bring data over into Snipe-IT from there would be so helpful.

**Comment by wiffelwicht** [comment]
As Intunes and Azure AD are getting more and more dominant in the Industry this would be really awesome to be able to link those systems together.

**Comment by joshopdev** [comment]
Would it not be possible to extend the AzureAD module to include the devices that are assigned to them?
