### ISSUE TITLE
Superadmin cant see companies licence

### ISSUE THREAD

**Issue by afeliciotto** [snipe/snipe-it#4367]
Hi all my enviroment info:

Snipe-IT version | v4.0.13 build 323 (gc1f8db3)
PHP Version | 7.0.22-0ubuntu0.16.04.1
Laravel Version | 5.4.36

When logged as superadmin go under Settings->companies->"mycompanyname" under "licence" i cant see the mycompanyname's licence.

In licence i see all license of "mycompanyname" and others companies

Can you help me?

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
