### ISSUE TITLE
asset status deployable

### ISSUE THREAD

**Issue by cotosss** [snipe/snipe-it#4368]
in the status deployable or ready to deploy
3 equal fields appear "checkout to" !

supposedly the first field should be the user who created the asset
the second field to whom the asset is deployed and the third where the asset is deployed
right?

If a asset is created with the status archived 

if an asset is created with the archived status and then we edit the asset status to deployable the checkout to fields do not appear so that they can be edited

can anyone help me with this issues

**Comment by snipe** [comment]
I don't understand what you're saying. Can you provide a screenshot or something?

**Comment by cotosss** [comment]
when i create a new asset if selected asset status to ready to deploy i got 3 fields labeled chekout status
1st field is the users
2nd ???
3rd its the location
how can i edit or create in the second field the person that the asset is deployed
![screenshot-2017-11-3 create asset ulht](https://user-images.githubusercontent.com/26629044/32368413-9dda5c22-c07d-11e7-8be4-086a2ace6939.png)

BUG
in a already asset created with the status archived when i edit this archived asset
![screenshot-2017-11-3 archived assets ulht](https://user-images.githubusercontent.com/26629044/32368389-8c4618c0-c07d-11e7-9c14-738e3f9c5484.png)
and change the status to ready to deploy
![screenshot-2017-11-3 asset update ulht](https://user-images.githubusercontent.com/26629044/32368466-ab0a74e0-c07d-11e7-9a74-f7f050ba206a.png)
the fields chekout to don't appear
![screenshot-2017-11-3 asset update ulht 1](https://user-images.githubusercontent.com/26629044/32368473-b4759c94-c07d-11e7-8456-5ccd9da7732e.png)
can anyone help?

**Comment by cotosss** [comment]
version 
https://screenshots.firefox.com/suWt3XLOtM50N0Hq/snipe-it.wpool.ulht.gl.pt

**Comment by snipe** [comment]
> 1st field is the users
> 2nd ???
> 3rd its the location

You are to pick ONE of those three. You can checkout an asset to a person, a location, or another asset.
