### ISSUE TITLE
Issues with sorting assets

### ISSUE THREAD

**Issue by tbradsha** [snipe/snipe-it#4369]
#### Expected Behavior (or desired behavior if a feature request)

Clicking on a column in the assets table at any time will sort the column in question

-----

#### Actual Behavior

Columns sort only if the sticky header is not activated.

Also, the "Status" column does not clump "deployed" (meta-)status items, but instead jumbles them in with the "ready to deploy" status (its actual status in the DB, but not its apparent status in the table).

Can be reproduced on the Snipe-IT's demo site.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

-Snipe-IT v4.1.0 build 37 (g48207fc)
-Fresh install
-PHP 5.6.28
-MySQL 5.7.15
-Windows Server 2012 R2 + Apache 2.4 (XAMPP)
-Manual installation

**Comment by snipe** [comment]
Pull the latest from master and let me know if you're still having trouble.

**Comment by tbradsha** [comment]
I'm still having the same issue with the latest master.

**Comment by snipe** [comment]
> Also, the "Status" column does not clump "deployed" (meta-)status items, but instead jumbles them in with the "ready to deploy" status (its actual status in the DB, but not its apparent status in the table).

I'm not sure what this means exactly - can you screenshot?

**Comment by tbradsha** [comment]
As you can see below, the table is sorted by the Status column. However, the "deployed" and "ready to deploy" statuses are not alphabetically sorted. I do understand that all of them are technically in "ready to deploy" status, and that "deployed" is a pseudo-status based on whether or not the asset is checked out, but since they have different labels in the table, the natural expectation on sort would be that the "deployed" would all be listed prior to the "ready to deploy". Hopefully that makes sense.

Also, the activated sticky header still does not allow sorting.

![image](https://user-images.githubusercontent.com/32492176/32390979-66420a64-c09e-11e7-8fb0-c48b246841c7.png)

**Comment by snipe** [comment]
Again, that's the meta status that you're seeing. Deployed isn't a real status label, it's the meta status label. It does group correctly if all of the assets within the status label are checked out or not checked out. 

We do this so that folks who use confusing status label names can see what's actually happening. We've tried doing it the other way (not using the meta status), but it was more confusing for most users. Otherwise a status like Ready to Deploy still looks available, even after it's checked out.

**Comment by tbradsha** [comment]
Yes, I understand it's the meta status, but when sorting one expects everything in the column to sort on face value (e.g. "Deployed"), not based on underlying value (e.g. "Ready to Deploy").

To me the big problem is inconsistency. In some places it splits the status into two statuses (this case) but doesn't behave as two statuses (doesn't sort like two categories), and in other places it is treated as one status (e.g. the pie chart on the dashboard). At the end of the day I'd just prefer a consistent treatment of the status ;^)

The two ways I'd do it is to either split them into two actual statuses in the database, or else have a consistent conversion on all queries ("ready to deploy" + unassigned = "ready to deploy" vs. "ready to deploy + assigned = "deployed").

Just my opinion of the quirk, and I can deal with no change if that's the decision!

**Comment by tbradsha** [comment]
Alternatively, maybe a preference to choose to treat them consistently (throughout the entire program) as either two separate statuses or as one single status?
