### ISSUE TITLE
Users page is not properly populating

### ISSUE THREAD

**Issue by tbradsha** [snipe/snipe-it#4370]
#### Expected Behavior (or desired behavior if a feature request)

Users should be listed in the users section on initial load.

-----

#### Actual Behavior

Going to the Users section via the sidebar, the list does not properly populate. It flashes some results then immediately shows "No matching records found". Using Chrome 61 on Windows 10. Refreshing and clearing cache/cookies does not solve the problem.

Going to page 2 lists results, and then going back to page 1 shows the expected results.

Can reproduce on the demo site.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

-Snipe-IT v4.1.0 build 37 (g48207fc)
-Fresh install
-PHP 5.6.28
-MySQL 5.7.15
-Windows Server 2012 R2 + Apache 2.4 (XAMPP)
-Manual installation

**Comment by snipe** [comment]
I can reproduce this (tho I can just hit refresh and get the users list). Not sure what's causing it though.

**Comment by snipe** [comment]
I'm also noticing that if I select 50 or 100 per page from the table menu and reload, it loads right away.

**Comment by tbradsha** [comment]
It appears to be resolved for me!
