### ISSUE TITLE
Feature Request: Company name on labels

### ISSUE THREAD

**Issue by danielr34** [snipe/snipe-it#4374]
#### Expected Behavior (or desired behavior if a feature request)

Currently we can select asset name, serial & asset tag but not company. I know with the QR code you can enter text for it but that doesn't help when asset tagging for multiple companies (I look after 4 different companies in a single office). Adding the company field would make life much easier being able to see which company owns a device at a glance.

thanks

-----

**Comment by Jhamende** [comment]
in the meantime you can add it yourselve in /resources/views/hardware/labels.blade.php and add follwing where you want in your label within div with class=label

`<div class="pull-left">
	        @if ($asset->company)
		          {{ $asset->company->name }}
	        @endif
    	</div>`

This needs to be done on every update until feature is added, if so.
