### ISSUE TITLE
Cannot Create User

### ISSUE THREAD

**Issue by thuekx** [snipe/snipe-it#4375]
#### Expected Behavior (or desired behavior if a feature request)

Create User With Assign Manager

-----

#### Actual Behavior

Error id (the manager id and id must be different) , i try this too for demo mode but i face the same error
![error id](https://user-images.githubusercontent.com/17924888/32362419-c3034806-c09b-11e7-9ece-e236a31ac455.PNG)
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? _fresh install_
- Version of Snipe-IT you're running _Version v4.1.0 build beta2 (g3b498ef)_
- Version of PHP you're running _PHP 5.6.32_ 
- Version of MySQL/MariaDB you're running _mysql  Ver 15.1 Distrib 5.5.56-MariaDB_
- What OS and web server you're running Snipe-IT _on Centos 7_
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) _git clone with manual config_
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error location/user/create (the manager id and id must be different)
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. (this confirm the same error)
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
This should be fixed on latest.

**Comment by thuekx** [comment]
Thank you snipe for a great support and a great program, You're rocks....
