### ISSUE TITLE
snipeit.sh script stucked | New installation v4.1.2 | Ubuntu 14.04 Server

### ISSUE THREAD

**Issue by itims** [snipe/snipe-it#4377]
I'm trying to install new version (v4.1.2) of snipe-it in Ubuntu 14.04 server by using script **snipeit.sh**. But unfortunately script got stuck at the installation state. I have no idea what to do on this situation.
![image](https://user-images.githubusercontent.com/23715217/32371121-a3371538-c0b5-11e7-9d19-8ce627a9ef03.png)

I have installed the following packages before I start run **snipeit.sh**
**sudo apt-get update
sudo apt-get install apache2
sudo apt-get update
sudo apt-get install python-software-properties
sudo apt-get update
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get install php7.0-common
sudo apt-get install php7.0-cli
sudo apt-get install libapache2-mod-php7.0
sudo apt-get install php7.0-mbstring
sudo apt-get install php7.0-curl
sudo apt-get install php7.0-mysql
sudo apt-get install php7.0-ldap
sudo apt-get install php7.0-zip
sudo apt-get install mysql-server-5.5
sudo a2dismod php7.0
sudo service apache2 restart
sudo apt-get install git**

And I used git for downloading Snipe-IT.

Could you please help me?

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Fresh Install**
- Version of Snipe-IT you're running - **v4.1.2**
- Version of PHP you're running - **7.0**
- Version of MySQL/MariaDB you're running - **MySql 5.5**
- What OS and web server you're running Snipe-IT on - **Ubuntu 14.04 server & Apache2**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - **snipeit.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by tiagom62** [comment]
snipeit.sh handles dependencies for you. It will install apache, php 7.1 and mariadb 10.1. I'm confident you are running into package conflicts.

Can you provide the contents of /var/log/snipeit-install.log. I will see if i can patch it so it doesn't just silently fail.

**Comment by itims** [comment]
Hi,
Thank you for your response :-)
Below the content of **snipeit-install.log**

Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  python3-software-properties
The following packages will be upgraded:
  python3-software-properties software-properties-common
2 upgraded, 0 newly installed, 0 to remove and 212 not upgraded.
Need to get 28.6 kB of archives.
After this operation, 1,024 B of additional disk space will be used.
Do you want to continue? [Y/n] Get:1 http://in.archive.ubuntu.com/ubuntu/ trusty-updates/main software-properties-common all 0.92.37.8 [9,384 B]
Get:2 http://in.archive.ubuntu.com/ubuntu/ trusty-updates/main python3-software-properties all 0.92.37.8 [19.2 kB]
Fetched 28.6 kB in 0s (54.9 kB/s)

**Comment by itims** [comment]
Earlier I had configured snipeit v3 using script **snipeit.sh** without much complication. At that time I have installed the following packages before I start to run the script **snipeit.sh** . And installation completed successfully without errors.
**_sudo apt-get install php5-common 
sudo apt-get install libapache2-mod-php5 
sudo apt-get install php5-cli
sudo apt-get install php5-mysql 
sudo apt-get install php5-curl
sudo apt-get install mysql-server-5.5
sudo a2enmod rewrite
sudo service apache2 restart
sudo apt-get install git_**

Could you please guide me how to configure (step by step commands need to be run for the installation) snipeit version 4 in ubuntu server 14.04?

**Comment by HinchK** [comment]
Running `snipeit.sh`, without bailing out and trying to re-run it, and provided you have a name service that will point to that server's FQDN, will get you up and running on a clean ubuntu server 14.04 on master, which is currently v4.1.3.  Just verified on a Vagrant Ubuntu/Trusty box.

The documentation on installing outside of the snipe-it.sh script has the answers to the vast majority of potential questions.  I highly recommend following it step-by-step (vs running the snipe-it.sh installer) as the experience gain will make troubleshooting issues down the road that much easier:

 https://snipe-it.readme.io/docs/installation

Upgrading an existing installation? https://snipe-it.readme.io/docs/upgrading

or just run `php upgrade.php` from the application root directory following a `git pull`.

**Comment by itims** [comment]
I'm following the installation documentation (https://snipe-it.readme.io/docs/installation), I got an error at **_Step 5 Generate Your App Key_** while running **php artisan key:generate**
![image](https://user-images.githubusercontent.com/23715217/33072413-75c8219e-cee5-11e7-92a5-68b281b65b4b.png)
Could you please help me to resolve this issue?

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/common-issues#section-php-parse-error-syntax-error-unexpected-expecting-or-variable-t_variable
