### ISSUE TITLE
asset you have attempted to accept was not checked out to you

### ISSUE THREAD

**Issue by honeyprep** [snipe/snipe-it#4382]
#### Expected Behavior (or desired behavior if a feature request)

(When a link is send to user email ID to accept an asset or accesories and when the user is clicking on the link, the user should get the option to either accept or denying the asset.)

-----

#### Actual Behavior

(Actual Behavior = when any user trying to accept or decline the asset, they are getting the the following error

Error: The asset you have attempted to accept was not checked out to you.)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh Install 
- Version of Snipe-IT you're running
v4.0.15 build 339
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

It's working fine for assets but getting error while accepting an accessories "asset you have attempted to accept was not checked out to you"

**Comment by Q-Nimbus** [comment]
Hi Guys seeing exactly the same issue

**Comment by woerdehoff** [comment]
Same here! Anyone find a fix? I'm on 

Snipe-IT version | v4.1.10-pre build 3185 (g5b15a2f)
PHP Version | 7.0.27-1+ubuntu16.04.1+deb.sury.org+1
Laravel Version | 5.4.35
