### ISSUE TITLE
Bulk-checkout not possible

### ISSUE THREAD

**Issue by diekmanu** [snipe/snipe-it#4384]
#### Expected Behavior (or desired behavior if a feature request)

Checkout multiple assets in the bulkcheckout view.

-----

#### Actual Behavior

Error message  "Error: Please check the form below for errors". 

The given data failed to pass validation./srv/users/serverpilot/apps/laravel5/vendor/laravel/framework/src/Illuminate/Foundation/Validation/ValidatesRequests.php#105

Reproducible on the demo pages.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  upgrade
- Version of Snipe-IT you're running: v4.1.3 build 94 (gb6a14d2)
- Version of PHP you're running: 5.6.23
- Version of MySQL/MariaDB you're running; MariaDB
- What OS and web server you're running Snipe-IT on: win7x64
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. yes
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. no error
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I can reproduce bulk assignment not working, but I'm not seeing that error message. Is there any additional info you can provide?
