### ISSUE TITLE
LDAP User Sync problem

### ISSUE THREAD

**Issue by chansinshan** [snipe/snipe-it#4385]
#### Expected Behavior (or desired behavior if a feature request)
After config LDAP Active Directory and connect successfully.  And go to LDAP User Sync.  The screen display "Whoops, looks like something went wrong."  I had enable the debug mode.  But no use.

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install
- Version of Snipe-IT you're running
v4.1.3 build 94 (gb6a14d2)
- Version of PHP you're running
7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running

- What OS and web server you're running Snipe-IT on
Ubuntu + Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Turned on debug but not active
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by madd15** [comment]
Once you set `APP_DEBUG=true` in `.env`, did you run `php artisan config:clear`?

**Comment by chansinshan** [comment]
yes, I run php artisan config:clear, but no use.

**Comment by madd15** [comment]
are you able to share your ldap settings? i suggest changing any confidential settings to something default

**Comment by chansinshan** [comment]
Finally, I found my typing mistake in LDAP Filter.  Everything going fine now.  Thanks madd15.

**Comment by madd15** [comment]
Glad its working for you

@snipe
