### ISSUE TITLE
Problems with Image Upload

### ISSUE THREAD

**Issue by masterofdesaster300** [snipe/snipe-it#4387]
#### Expected Behavior (or desired behavior if a feature request)

Upload Image files should be possible in all Fields(Categorys, Locations etc.) with the Updates.

#### Actual Behavior
No complte Write-access in all subdirectories.

Fixed the Problem by Hand with chmod for all concerning subdirectories in uploads.

Maybe it was forget in the update, to change permissions for these specific directories.

**Comment by snipe** [comment]
The storage directory and all sub-directories must always be writable by the web server.

**Comment by mink-adao-duy** [comment]
Hi,

If users are trying to install Snipe-IT with the Dockerfile provided, they will be facing a problem (upload images) with the following entities:
- companies
- locations
- departments
- manufacturers
- categories

These entities are missing in the `docker/entrypoint.sh` file (line 20).

I will try to create a pull request.

Best regards
