### ISSUE TITLE
LDAP Sync

### ISSUE THREAD

**Issue by townie83** [snipe/snipe-it#4389]
#### Expected Behavior (or desired behavior if a feature request)
LDAP Sync

-----

#### Actual Behavior

I can Test and Verify LDAP sync in settings, once saved, I can test and sucessfully verify using a username and password, but on doing LDAP sync in People, it bombs out with 500 Server Error. Trying this via command line, it shows the following:

[root@itam snipe-it]# php artisan snipeit:ldap-sync --summary
PHP Fatal error:  Allowed memory size of 524288000 bytes exhausted (tried to allocate 72 bytes) in /var/www/html/snipe-it/app/Models/Ldap.php on line 269
[root@itam snipe-it]#

Looks like it's somewhat running out of memory?

Any ideas? The server has 2GB of RAM, it's a VM so I can allocate more to it if needed.

-----
#### Provide answers to these questions:

Fresh
Snipe = v4.1.2 build 48 (gd21c92f)
PHP = 5.6.32
CentOS 7 x4

**Comment by snipe** [comment]
Based on that error you'll want to allocate more memory to PHP (via php.ini)
