### ISSUE TITLE
Slow loading of the snipeIT website - vanilla installation

### ISSUE THREAD

**Issue by SantoshNB** [snipe/snipe-it#439]
Hello Folks,

I have installed snipe-it on RHEL 6.6 64bit.

Following is the version details of the components
PHP 5.4.36 
Apache/2.2.15 (Unix)
mySql - 5.5

The website loads quite slowly and I am unable to edit/delete default entries which comes with vanilla installation.

I am at my wits end on how to troubleshoot this slowness issue.

Any pointers would be really  helpful.

**Comment by snipe** [comment]
I honestly don't know. We run the demo on a micro at AWS, which is the smallest thing they have, and run the DB off of it too, with no problems.

**Comment by SantoshNB** [comment]
Sorry for the delayed reply.

Well, I somehow missed or overlooked your previous response in the first place. 

In fact, it's not a bug.

I have installed snipe-it in an "secure" environment where there is no Internet available.

When webpage loads, it looks for different connections such such code.jquery.com, cdn.datatables.com and google APIs etc...Since these URLs are not reachable it's taking huge time to load.

Is there anyway, I can bypass google fonts, jquery etc?

**Comment by snipe** [comment]
Ahhhhh.... that certainly explains it. Let me see if I can set that up as a configurable option or something.

**Comment by SantoshNB** [comment]
Thank you :)

**Comment by snipe** [comment]
Okay, I put something out on dev for you. The javascript and CSS now loads locally, but there is a new setting option that lets you check off whether the install can talk to the outside world. If it can, it will load the google font, if it cannot, it won't, and you'll just get the default arial font. It looks less sexy, but it should work.

**Comment by uberbrady** [comment]
can you download the font too. and then use it locally?

**Comment by snipe** [comment]
I can, there are a bunch of them and the paths in the CSS would need to be updated though. I at least wanted to get @SantoshNB to a place where the thing will actually load for him/her. 

Pull request are welcome ;)
![fycfc jpg](https://cloud.githubusercontent.com/assets/197404/6239696/1150aa82-b6bb-11e4-8732-17d816b7d79e.gif)

**Comment by SantoshNB** [comment]
@snipe, you are awesome! Thanks so much, appreciated :+1:
