### ISSUE TITLE
"The result could not be loaded"

### ISSUE THREAD

**Issue by tomasaberg** [snipe/snipe-it#4390]
#### Expected Behavior (or desired behavior if a feature request)

When creating an asset the form should be able to fetch data (such as company, model or location)

-----

#### Actual Behavior

I get "The result could not be loaded."

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
Upgrade (Docker) 

- Version of Snipe-IT you're running
4.1.3

- Version of PHP you're running
PHP 7.0.22-0ubuntu0.16.04.1

- Version of MySQL/MariaDB you're running
MySQL5.6

- What OS and web server you're running Snipe-IT on
Ubuntu 16.04 and Apache2 (As the docker image use it)

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Docker

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Exception : /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php#179 
on that line it says `throw new NotFoundHttpException;`

```
         return $this->getRouteForMethods($request, $others);
        }

        throw new NotFoundHttpException;
    }
```

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Create Asset

- If a stacktrace is provided in the error, include that too.
N/A

- Any errors that appear in your browser's error console.
N/A

- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
Not able to reproduce it

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
N/A

- Include what you've done so far in the installation, and if you got any error messages along the way.
1. Updated docker-compose.yml to use 4.1.3 image.
2. Tried creating a asset
3. Following upgrading steps
4. Clear browser cache

- Indicate whether or not you've manually edited any data directly in the database
No, I did not.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Can you give me a more detailed stacktrace from your logs? That doesn't tell me very much.

**Comment by tomasaberg** [comment]
Thank you for taking your time!

I'm not sure how to get more detailed stacktrace. I have no logs in /var/www/html/storage/logs, only a gitignore. Everything looks fine in the debug console until I use the dropdown were it tries to do a lookup (such as the company dropdown). Then it'll give me the exception I mentioned, that's also the full output I get. Other than that I don't have much more to give you, sorry.

I did manage to provoke an error when I tried to create a model from the Create Asset view.
`Server Error: 404 Endpoint not found.`
Didn't create any logs though.

**Comment by snipe** [comment]
>  I have no logs in /var/www/html/storage/logs

That's definitely a problem. Can you check the permissions on your `storage` directory and all subdirectories? (Specifically `storage/logs/laravel.log`.

Also are you running this in a sub-directory?

**Comment by tomasaberg** [comment]
`drwxr-xr-x  2 docker root   4096 Nov  6 21:52 logs`
If I provoke an error it'll create a log. I could create a log by trying to email something. That caused an error because I haven't specified any email server settings.

I run it as a docker swarm service. I use the 4.1.3 docker image, no custom build or anything.
4.1.2 worked but 4.1.3 broke it for me.

The way I upgrade the service is changing the docker-compose.yml to use the tag I wish to use and then run `docker stack deploy -c docker-compose.yml snipeit`. I have run it this way since 4.0.7.

**Comment by snipe** [comment]
Okay, in the network tab in your browser, can you check and see what URL it's hitting for the dropdown menu call?

**Comment by tomasaberg** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found)
//api/v1/companies/selectlist?page=1

```
all.js?id=45f8944e6ec45cec9861:3 
GET http://snipeit.example.com//api/v1/companies/selectlist?page=1 404 (Not Found)
send @ all.js?id=45f8944e6ec45cec9861:3
ajax @ all.js?id=45f8944e6ec45cec9861:3
transport @ all.js?id=45f8944e6ec45cec9861:20
n @ all.js?id=45f8944e6ec45cec9861:20
n.query @ all.js?id=45f8944e6ec45cec9861:20
(anonymous) @ all.js?id=45f8944e6ec45cec9861:21
n.invoke @ all.js?id=45f8944e6ec45cec9861:19
n.trigger @ all.js?id=45f8944e6ec45cec9861:19
s.trigger @ all.js?id=45f8944e6ec45cec9861:21
s.open @ all.js?id=45f8944e6ec45cec9861:21
s.toggleDropdown @ all.js?id=45f8944e6ec45cec9861:21
(anonymous) @ all.js?id=45f8944e6ec45cec9861:21
n.invoke @ all.js?id=45f8944e6ec45cec9861:19
n.trigger @ all.js?id=45f8944e6ec45cec9861:19
(anonymous) @ all.js?id=45f8944e6ec45cec9861:20
dispatch @ all.js?id=45f8944e6ec45cec9861:2
m.handle @ all.js?id=45f8944e6ec45cec9861:2
```

The double // in the URL looks odd. I haven't changed any apache settings.

Note: I changed my domain to example.com in the output.

**Comment by tomasaberg** [comment]
OK, I tried a chrome add-on, requestly were I modify the request.
By changing http://snipeit.example.com//api/v1/companies/selectlist?page=1 to http://snipeit.example.com/api/v1/companies/selectlist?page=1 (removing the extra forward slash) it started to work.

**Comment by pvhkai** [comment]
@snipe @tomasaberg 
I got the same issue but only if the user is not in a superadmin-group

**Comment by tomasaberg** [comment]
@pvhkai The user I've tested with is superadmin (and in fact the initial user)

**Comment by snipe** [comment]
@tomasaberg what's your APP_URL in your .env?

**Comment by tomasaberg** [comment]
APP_URL=http://snipeit.example.com

Again, I've changed the domain to example.com

**Comment by snipe** [comment]
I think I see where the issue is. I should have a fix for you shortly.

**Comment by jmontoya1974** [comment]
Tomasaberg Did you find the solution? I have the problem now , same behavior.  Best regards

**Comment by Flheart2k20** [comment]
Hello,

Same issue there on a fresh installation. Everything else is working as expected.
When I get the "results could not be loaded" error, all other information in the website is not available for a minute or so (and 405 method not allowed errors on every page are displayed in the browser's debug network tab).
Strangely, when I activate debug mode this does not happen...
Is there a fix for that ? Thank you in advance.

**Comment by Flheart2k20** [comment]
Guys,
Nice workaround provided here by Coaxke fyi: #8035
