### ISSUE TITLE
Selects (dropdowns) not working on iPad

### ISSUE THREAD

**Issue by frasersdev** [snipe/snipe-it#4392]
#### Expected Behavior (or desired behavior if a feature request)

tapping a select control should show the options

-----

#### Actual Behaviour

nothing happens

-----

#### Please confirm you have done the following before posting your bug report:

- [✓] I have enabled debug mode 
- [✓] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh

- Version of Snipe-IT you're running
v4.1.3 build 94 (gb6a14d2)

- Version of PHP you're running
7.0.22-0ubuntu0.16.04.1

- Version of MySQL/MariaDB you're running
Mysql
5.7.20-0ubuntu0.16.04.1

- What OS and web server you're running Snipe-IT on
ubuntu 16.04.3
apache 2.4.18

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual installation

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
no error

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
http://transmitter.frasersdev.net/hardware/1/checkout
All pages with a select control are affected the same way.

- If a stacktrace is provided in the error, include that too.
no error

- Any errors that appear in your browser's error console.
no error or any other clues in console

- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
yes same issue

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
no server-side errors found. 

- Include what you've done so far in the installation, and if you got any error messages along the way.
fresh install, created 1 asset, 1 accessory, 2 locations, 1 custom field set, 1 user, 1 model, 2 categories, 1 company

- Indicate whether or not you've manually edited any data directly in the database
no

- some additional information for you

tried chrome, safari and firefox on the tablet - all behave the same way
no issues at all with desktops (mac / windows)
tablet is running ios11.1
appears to be a client side problem

as you can imagine this is pretty much show stopper as far as iPads are concerned...

**Comment by snipe** [comment]
Is it not selectable, or does it react in any way?

**Comment by frasersdev** [comment]
does not react at all, like it is not an interactive control.

**Comment by snipe** [comment]
Looks like this might be an issue in select2 + fastclick. (See https://github.com/select2/select2/issues/3064) In my tests, it does work, but you have to hold down on the select box a little longer than normal.

**Comment by frasersdev** [comment]
I can press for 30s + and nothing happens.

**Comment by snipe** [comment]
I can't reproduce that at all. If I tap and hold for 2 seconds, it's pops the menu down. Can you pull latest from master and tell me if it works better?

**Comment by frasersdev** [comment]
ok I'll try that.
I have a video of it if you'd like to see

**Comment by snipe** [comment]
I believe you :) No need for video.

**Comment by frasersdev** [comment]
Hi @snipe 

The version from GitHub showed some improvement.
the selects open now but the options within stubbornly refuse to be selected. its like safari has the z-index confused.

tried a few other tablets too:

iPad Air - not working
iPad Air2 - not working
Nexus 7 - working

Another thing I've noticed is the select controls on the iPad don't close if you tap outside of them - might be related somehow

cheers,
F

**Comment by snipe** [comment]
I can confirm this behavior as well. If you can pull the latest from the develop branch, I've disabled fastclick there. (I am seeing some select2 PRs that address the fastclick conflicts, but they've been open for quite some time, so I don't have any idea when they'll be merged.)

Can you let me know if latest from develop works for you?

**Comment by snipe** [comment]
(You may need to do a composer install as well - I switched the roller libraries out.)

**Comment by frasersdev** [comment]
sure, will do.

**Comment by snipe** [comment]
Thanks - I appreciate you helping test this :) Hopefully we can get you sorted ASAP.

**Comment by frasersdev** [comment]
its working :)

many thanks!

**Comment by snipe** [comment]
Hooray! Thanks for your patience!

![yaaaaaaaas](https://user-images.githubusercontent.com/197404/32479516-01e1a25c-c33f-11e7-99ce-0670766fa849.gif)

**Comment by snipe** [comment]
I'll get that merged into master as soon as I'm done with a few things here on my end.

**Comment by snipe** [comment]
Merged to master and will be in the next release

**Comment by frasersdev** [comment]
again thank you!
