### ISSUE TITLE
Question about LDAP and avoiding sync of a selected ou

### ISSUE THREAD

**Issue by korio77** [snipe/snipe-it#4393]
Hi again!

I have just updated to the latest version (v4.1.3) and i i wanted to know if there is a way to sync an AD OU but avoiding to sync all the children OU's.

What i mean is, i have an OU lets say its called "Office". Inside it, i have multiple OU's for each department, and one for "old users". It's, there a way to sync the full "Office" OU but avoiding to sync the children "old users" OU?

I have already a query that only sync active users, but in the "old users" OU we still have some active users that i dont want to sync.

Any suggestions?

**Comment by snipe** [comment]
Hi @korio77 we don't currently support that, but it seems like a reasonable feature request.

**Comment by madd15** [comment]
My only suggestion would be to add a new group that only users in the 'old users' OU are members of and exclude that in your query.

Example:
`&(objectclass=user)(memberof=cn=staff,cn=users,dc=company,dc=local)(!(memberof=cn=old_staff,cn=users,dc=company,dc=local))(!(userAccountControl:1.2.840.113556.1.4.803:=2))`
