### ISSUE TITLE
Users cannot see License Keys

### ISSUE THREAD

**Issue by flyfloh** [snipe/snipe-it#4396]
#### Expected Behavior (or desired behavior if a feature request)

Users that belong to a group with the Permission "Licenses: View License Keys" set to "Granted" can see the license keys for Software Licenses that are checked out to them.

The affected users have all permissions set to inherit and belong to only one group.

-----

#### Actual Behavior

The users cannot see their license keys, but instead see three dashes (---).

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade

- Version of Snipe-IT you're running
v4.1.3 build 94 (gb6a14d2) (Docker)

- Version of PHP you're running
 7.0.22-0ubuntu0.16.04.1

- Version of MySQL/MariaDB you're running
MySQL 5.6 (Docker)

- What OS and web server you're running Snipe-IT on
Ubuntu 16.04 (Docker)

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Docker

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
None

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Licenses -- User's (non-admin) dashboard

- If a stacktrace is provided in the error, include that too.
None

- Any errors that appear in your browser's error console.
None

- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
No

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
None

- Include what you've done so far in the installation, and if you got any error messages along the way.
Configuration of user groups and LDAP, imported users through LDAP and assigned them to a group.

- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
If you apply the permission to the user directly, can they see them?

**Comment by uknzaeinozpas** [comment]
Mine is working correctly, I'm using the same Snipe and MySQL version but on Windows with Apache.

**Comment by snipe** [comment]
I'm having a hard time reproducing this... :-/

**Comment by flyfloh** [comment]
> If you apply the permission to the user directly, can they see them?

That works. Interestingly now that I did this they can see the license keys fine.

**Comment by JoKneeMo** [comment]
@snipe I've reproduced this on the demo site.

I made a test user **lictest**.

I gave it permission deny on all licensing options, but when I browse to [Asset: 712507813](https://demo.snipeitapp.com/hardware/1) I could see the Photoshop License.

The Office license was also applied to the asset but I could not see it.
I then changed the Office licenses quantity to 10 and It then showed up for the lictest user.

Right now, I've assigned [Asset: 796253890](https://demo.snipeitapp.com/hardware/2) an InDesign license. The license tab appears for lictest but it shows "No Results.".
If you open the InDesign license and hit save, what ever is modified in the db allows it to be seen by the user. I think this is related.

**Comment by JoKneeMo** [comment]
Any update on this? Anything I can do to assist?

**Comment by viclou** [comment]
FD 13074

**Comment by b12e** [comment]
We experience the same bug unfortunately.

When a user has individual permission to see the license key, they can see it,  but if it's a group permission they can't.

**Comment by b12e** [comment]
Yes it is

Op zo 8 mrt. 2020 om 16:00 schreef stale[bot] <notifications@github.com>

**Comment by b12e** [comment]
Think so 😊

Op do 7 mei 2020 om 18:10 schreef stale[bot] <notifications@github.com>

**Comment by robinjoh90** [comment]
Same problem here, running v4.9.2. It works when setting the permission on user level but not if it's assigned on the group.

**Comment by Mistic92** [comment]
When I grant `View License Keys` to group users see all licences in system instead of only assigned to their software. How should it be done?
