### ISSUE TITLE
Assets Checked Out to Locations do not show in Locations Assets list.

### ISSUE THREAD

**Issue by MeklonDramicus** [snipe/snipe-it#4397]
#### Expected Behavior (or desired behavior if a feature request)

When deploying asset to a Location, I'm expecting the asset to show up on the location information page.

-----

#### Actual Behavior

Asset get's deployed to the location, but the asset doesn't appear on the locations assets in the location information page.

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Upgrade**
- Version of Snipe-IT you're running **4.1.3**
- Version of PHP you're running **7.1.9**
- Version of MySQL you're running **5.7.19**
- What OS and web server you're running Snipe-IT on **Win10 / Apache 2.4.27**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Manual**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **None**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **https://demo.snipeitapp.com/locations/8**   //\\    **https://demo.snipeitapp.com/hardware/3**
- If a stacktrace is provided in the error, include that too. **None**
- Any errors that appear in your browser's error console. **None**
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. **Yes - Follow above links**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. **None**
- Include what you've done so far in the installation, and if you got any error messages along the way. **Standard install, no errors**
- Indicate whether or not you've manually edited any data directly in the database **No**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by MeklonDramicus** [comment]
Both. On my local install and the demo site.

**Comment by snipe** [comment]
The demo site's info is programmatically generated, so it's not unusual to have small bits mismatching.

If you're looking at older checkouts, you have to run the artisan command mentioned in the [release notes](https://github.com/snipe/snipe-it/releases/tag/v4.1.3). We de-normalized locations in the last release to make pages load a little faster.

If it's happening on new checkouts (since your upgrade), that's a different issue.

**Comment by MeklonDramicus** [comment]
I just made a new checkout on the demo and the same issue is appearing.

Will create another test asset when I get back to the office in the morning and try it again on the live site.

**Comment by MeklonDramicus** [comment]
**FYI the demo checkout was using a freshly created asset and location

**Comment by snipe** [comment]
Wait, I think that's actually expected behavior. The assets listing in Locations is meant to show assets that live in a particular place, it doesn't look at checkouts. We can add another list on locations for assets checked out to a particular location, but a it is right now, that's expected behavior.

**Comment by frasersdev** [comment]
I noticed this too. I found it slightly counter-intuitive 

- asset ready to deploy at location -> listed on the location page
- asset deployed to a user who is at the location ->  listed on the location page
- asset deployed to location -> is not listed on the location page

the other way of look at this is "How do I list the assets deployed to a location" - I couldn't find a way

> We can add another list on locations for assets checked out to a particular location

that would work well for me

**Comment by MeklonDramicus** [comment]
Would be highly appreciated, thanks @snipe !

**Comment by snipe** [comment]
Well because of the way we've flattened the assets table to use location_ids, assets checked out to locations will now be listed in the main "assets" listing on the locations detail page. That might end up being confusing for some folks, but I guess we'll see how it goes.

**Comment by hamzab900** [comment]
I ran the SQL command below to get it to show default location which was imported from csv in the location field. So now, the assets I imported show up under each location.

`UPDATE `assets` SET `location_id` = `rtd_location_id``

**Comment by gab696** [comment]
Hi,
With version 7.1.16 Going to Settings / Locations and selecting a location where assets are assigned don't display anything in the Assigned Assets Tab despite the black round icon deiplaying the total.
Printing assigned button produce a correct output displaying assigned assets.

<img width="1039" alt="Image" src="https://github.com/user-attachments/assets/f5f8c2a3-9b94-45e0-9550-42cebc278132" />

**Comment by lgofibre** [comment]
Hi there,

I have exactly the same issue, any help on this would be greatly appreciated. I can't see anything odd in the laravel logs or in the browser console.

Here you can see a bunch of assets checked out to the location:
![Image](https://github.com/user-attachments/assets/1aa61c99-62a2-4de4-9e8c-93d33b6adcc2)

However, there is nothing listed under the assets in that location:
![Image](https://github.com/user-attachments/assets/90047a64-1964-449a-a233-8d3c051edc49)

But I click print then I can see the devices:

![Image](https://github.com/user-attachments/assets/2db34ab5-efa4-4f86-ac8d-5a09adb34edb)

I've checked these records in the database and they have a location and location rtd id, I've also run this command but no luck:
 php artisan snipeit:sync-asset-locations --output=all

If someone could let me know how to troubleshoot this or where to start it'd be great.

Regards,
Luis
