### ISSUE TITLE
Azure Active Directory Integration

### ISSUE THREAD

**Issue by evando646** [snipe/snipe-it#4399]
Hi!

can Snipe-IT be used with Azure Active Directory?

**Comment by snipe** [comment]
You can use the LDAP functionality of Azure Active Directory, but not the SSO hooks.

**Comment by shandorcoachman** [comment]
Hey,

what happens with the locally configured users if we connect our hosted snipe-it instance with our Azure AD in case we're using the same username/e-mails?

Also, which user information will be synced down from Azure AD to our Snipe-IT instance?

Thanks!
Sandor
