### ISSUE TITLE
Serial has constraint on uniqueness among all assets

### ISSUE THREAD

**Issue by captainlaw** [snipe/snipe-it#440]
The system has constraint on the serial  uniqueness among all assets. But in the real world, different kind of assets , serial  might be the same.

**Comment by snipe** [comment]
I'm not sure how to get around that, from a business rules perspective. The goal is to disallow duplicate assets from being created, since that's a common mistake people make, and it can really throw off your data, making it a bit of a nightmare.

**Comment by dkd-schaffstein** [comment]
How about checking for uniqueness in one "asset category" only. So no two laptops could have the same serial number, but still there could be a laptop and an iphone with a matching serial number.

**Comment by leobg** [comment]
I am thinking uniqueness of asset tag label would be sufficient to avoid duplicate assets. After all, it is the company assigned serial number to any company asset and it is what will matter.
