### ISSUE TITLE
Object not found! Error 404 Only when clicking on the "new license" button in the Dashboard.

### ISSUE THREAD

**Issue by masseehg** [snipe/snipe-it#4407]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh Install
- Version of Snipe-IT you're running: 4.1.1
- Version of PHP you're running : Xampp
- Version of MySQL/MariaDB you're running 
- What OS and web server you're running Snipe-IT on: Windows 2012 R2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Duplicate of #4031

**Comment by masseehg** [comment]
Still having the issue. After clearing the route and cache. 

![capture](https://user-images.githubusercontent.com/33504510/32624620-9ad33b0a-c53e-11e7-8a63-c9d6e873e4b8.JPG)

![capture1](https://user-images.githubusercontent.com/33504510/32624658-bfc333ca-c53e-11e7-9bfa-6f8f7678e073.JPG)

**Comment by snipe** [comment]
This has nothing to do with caches, or with Snipe-IT. It's a XAMPP issue. https://github.com/snipe/snipe-it/issues/4031#issuecomment-332676078

**Comment by masseehg** [comment]
Ok understood. Would you happen to know of a work around?

**Comment by passionzia** [comment]
HI,
even i am facing the exact same issue if you would have solved the issue.please let me know the steps...thanks

**Comment by masseehg** [comment]
I started over and used Wamp instead of Xampp

**Comment by snipe** [comment]
We have attempted to put together some XAMPP documentation here: https://snipe-it.readme.io/v4.0/docs/xampp

But we don't use Windows or XAMPP, so I don't know how useful it will be.

**Comment by brijeshdave** [comment]
On XAMPP i did commented #ScriptAlias /licenses/ "C:\xampp\htdocs\snipe-it\public" in C:\xampp\apache\conf\extra\httpd-vhosts.conf and restarted Apache service and it started to work both License index page and create page. Before this only index page was working and create page was giving the same error of Object Not found.

**Comment by PhoenixC46** [comment]
Thanks @brijeshdave, commenting the line in httpd-vhosts.conf worked for me 👍
