### ISSUE TITLE
Help, php artisan key:generate

### ISSUE THREAD

**Issue by pos1234** [snipe/snipe-it#441]
Hi there i'm following the Windows ISS (Install Snipe-IT Windows 2008 R2 With IIS)

I have so far gone through with minimal problems i'm on step "Configuring Snipe IT" under chapter 3 iii i'm trying to run the command "php artisan key:generate"  and the follwing error appears in the terminal:

Command: composer install

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for intervention/image dev-master -> satisfiable by i
ntervention/image[dev-master].
    - intervention/image dev-master requires ext-fileinfo * -> the requested PHP
 extension fileinfo is missing from your system.

C:\inetpub\wwwroot\snipe-it\snipe-it-1.1>php artisan key:generate
PHP Warning:  require(C:\inetpub\wwwroot\snipe-it\snipe-it-1.1\bootstrap/../vend
or/autoload.php): failed to open stream: No such file or directory in C:\inetpub
\wwwroot\snipe-it\snipe-it-1.1\bootstrap\autoload.php on line 17

Warning: require(C:\inetpub\wwwroot\snipe-it\snipe-it-1.1\bootstrap/../vendor/au
toload.php): failed to open stream: No such file or directory in C:\inetpub\wwwr
oot\snipe-it\snipe-it-1.1\bootstrap\autoload.php on line 17
PHP Fatal error:  require(): Failed opening required 'C:\inetpub\wwwroot\snipe-i
t\snipe-it-1.1\bootstrap/../vendor/autoload.php' (include_path='.;C:\php\pear')
in C:\inetpub\wwwroot\snipe-it\snipe-it-1.1\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\inetpub\wwwroot\snipe-it\sni
pe-it-1.1\bootstrap/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:
\inetpub\wwwroot\snipe-it\snipe-it-1.1\bootstrap\autoload.php on line 17

C:\inetpub\wwwroot\snipe-it\snipe-it-1.1>

Could someone also confirm to me that the 'url' => 'http://assets.portal.local' can be used, i'm trying to install on windows seven. 

If someone could please help me, I'd greatly appreciate it :-)

**Comment by pos1234** [comment]
Hey aahmed,

Thanks for your advice, i did what you said and it worked a treat. I also needed to change permissions which helped. I've installed everything correctly or so I think. The problem I'm having now due to lack of knowledge on my part is how to actually get the URL up, originally I had stuck with the instructions and kept "assets.portal.local:8888" as my url but nothing seemed to be happening when i tried to navigate to it. 

Below is the contents of my database.php file excluding passwords:

'connections' => array(

        'sqlite' => array(
            'driver'   => 'sqlite',
            'database' => __DIR__.'/../database/production.sqlite',
            'prefix'   => '',
        ),

        'mysql' => array(
            'driver'    => 'mysql',
            'host'      => 'POS_ACER_TOUCH',
            'database'  => 'snipeit_laravel',
            'username'  => 'snipeit_laravel',
            'password'  => '',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ),

        'pgsql' => array(
            'driver'   => 'pgsql',
            'host'     => 'POS_ACER_TOUCH',
            'database' => 'database',
            'username' => 'root',
            'password' => '',
            'charset'  => 'utf8',
            'prefix'   => '',
            'schema'   => 'public',
        ),

        'sqlsrv' => array(
            'driver'   => 'sqlsrv',
            'host'     => 'POS_ACER_TOUCH',
            'database' => 'database',
            'username' => 'root',
            'password' => '',
            'prefix'   => '',
        ),

    ),

    /*
    |--------------------------------------------------------------------------
    | Migration Repository Table
    |--------------------------------------------------------------------------
    |
    | This table keeps track of all the migrations that have already run for
    | your application. Using this information, we can determine which of
    | the migrations on disk have not actually be run in the databases.
    |
    */

    'migrations' => 'migrations',

    /*
    |--------------------------------------------------------------------------
    | Redis Databases
    |--------------------------------------------------------------------------
    |
    | Redis is an open source, fast, and advanced key-value store that also
    | provides a richer set of commands than a typical key-value systems
    | such as APC or Memcached. Laravel makes it easy to dig right in.
    |
    */

    'redis' => array(

        'cluster' => true,

        'default' => array(
            'host'     => '127.0.0.1',
            'port'     => 6379,
            'database' => 0,
        ),

    ),

);


Here is my app.php file:

<?php

return array(

    /*
    |--------------------------------------------------------------------------
    | Application Debug Mode
    |--------------------------------------------------------------------------
    |
    | When your application is in debug mode, detailed error messages with
    | stack traces will be shown on every error that occurs within your
    | application. If disabled, a simple generic error page is shown.
    |
    */

    'debug' => true,

    /*
    |--------------------------------------------------------------------------
    | Application URL
    |--------------------------------------------------------------------------
    |
    | This URL is used by the console to properly generate URLs when using
    | the Artisan command line tool. You should set this to the root of
    | your application so that it is used when running Artisan tasks.
    |
    */

    'url' => 'assets.portal.local:8888',

    /*
    |--------------------------------------------------------------------------
    | Encryption Key
    |--------------------------------------------------------------------------
    |
    | This key is used by the Illuminate encrypter service and should be set
    | to a random, 32 character string, otherwise these encrypted strings
    | will not be safe. Please do this before deploying an application!
    |
    | Run a php artisan key:generate --env=staging to create a random one
    */

    'key' => 'yMWICUcjRvtZeSweTTgpQHyU3RZ0zv8s',

);


The ISS manager is set up right from what i have read within other issues , please see screen shot

![image](https://cloud.githubusercontent.com/assets/10423056/5644607/5efeb342-965d-11e4-8ca9-610ef124bd1f.png)


Windows 7 
MariaDb 10.0.15 64 bit 
PHPManagerForIIS-1.2.0-x64
rewrite_2.0_rtw_x64
EasyPHP-DevServer-14.1VC11

Look forward to anyone lending a hand :-)

**Comment by snipe** [comment]
@pos1234 not sure what you mean by "nothing seems to be happening" on the main URL. Can you be more specific?

**Comment by aahmed2015** [comment]
Did you set up a DNS entry for your Snipe-IT URL? The better question to ask is that how do you want to access this URL? Through other PC's in the network? If so, then you will need to create a DNS entry for your IIS Snipe-IT website.

Alternatively what I did was manually created a entry in my hosts file on Windows 7 and gave it a URL much like yours but with a loopback address to it (127.0.0.1), so it looks up this address on the PC instead of my DNS server who has no idea what URL that is.

You can then add another localhost binding on your IIS website, also judging from your screenshot you have a Default Web Site in IIS is using the localhost binding, you should delete this site so localhost can be used on Snipe-IT instead.

Does that make sense?

**Comment by pos1234** [comment]
@snipe Sure when i type "asset.portal.local" into a web browser the page does not load

**Comment by pos1234** [comment]
@aahmed2015 Thanks for your reply again :-) Yes i did set up a DNS entry for the Snipe-IT URL. Your correct i need to be able to access this from multiple machines across my network. I'll delete the Default Website and create an entry in my hosts file, i'll post the results when this is complete.

**Comment by pos1234** [comment]
Hey guys, so what I have done now is add my url to the host file and pointed it back to the loopback address. I changed the port from 8888 to 80 which worked :-) below is a screenshot of my next error, sorry to be such a pain I am a total amateur.

![image](https://cloud.githubusercontent.com/assets/10423056/5660288/7bac5486-9716-11e4-94d0-da53a3e2c6b9.png)

**Comment by pos1234** [comment]
Here is the text for easier reading:

HTTP Error 403.14 - Forbidden
The Web server is configured to not list the contents of this directory.
Detailed Error Information
Module	DirectoryListingModule
Notification	ExecuteRequestHandler
Handler	StaticFile
Error Code	0x00000000
Requested URL	http://assets.portal.local:80/
Physical Path	C:\inetpub\wwwroot\snipe-it\snipe-it-1.1\public
Logon Method	Anonymous
Logon User	Anonymous
Most likely causes:
A default document is not configured for the requested URL, and directory browsing is not enabled on the server.
Things you can try:
If you do not want to enable directory browsing, ensure that a default document is configured and that the file exists.
Enable directory browsing using IIS Manager.
Open IIS Manager.
In the Features view, double-click Directory Browsing.
On the Directory Browsing page, in the Actions pane, click Enable.
Verify that the configuration/system.webServer/directoryBrowse@enabled attribute is set to true in the site or application configuration file.
Links and More Information
This error occurs when a document is not specified in the URL, no default document is specified for the Web site or application, and directory listing is not enabled for the Web site or application. This setting may be disabled on purpose to secure the contents of the server.
View more information »

**Comment by pos1234** [comment]
I have enabled directory browsing and below is my next error, I wasn't sure if I was meant to do this but hopefully it'll give you more information:

HTTP Error 404.3 - Not Found
The page you are requesting cannot be served because of the extension configuration. If the page is a script, add a handler. If the file should be downloaded, add a MIME map.
Detailed Error Information
Module	StaticFileModule
Notification	ExecuteRequestHandler
Handler	StaticFile
Error Code	0x80070032
Requested URL	http://assets.portal.local:80/index.php
Physical Path	C:\inetpub\wwwroot\snipe-it\snipe-it-1.1\public\index.php
Logon Method	Anonymous
Logon User	Anonymous
Most likely causes:
It is possible that a handler mapping is missing. By default, the static file handler processes all content.
The feature you are trying to use may not be installed.
The appropriate MIME map is not enabled for the Web site or application. (Warning: Do not create a MIME map for content that users should not download, such as .ASPX pages or .config files.)
If ASP.NET is not installed.
Things you can try:
In system.webServer/handlers:
Ensure that the expected handler for the current page is mapped.
Pay extra attention to preconditions (for example, runtimeVersion, pipelineMode, bitness) and compare them to the settings for your application pool.
Pay extra attention to typographical errors in the expected handler line.
Please verify that the feature you are trying to use is installed.
Verify that the MIME map is enabled or add the MIME map for the Web site using the command-line tool appcmd.exe.
To set a MIME type, use the following syntax: %SystemRoot%\windows\system32\inetsrv\appcmd set config /section:staticContent /+[fileExtension='string',mimeType='string']
The variable fileExtension string is the file name extension and the variable mimeType string is the file type description.
For example, to add a MIME map for a file which has the extension ".xyz": appcmd set config /section:staticContent /+[fileExtension='.xyz',mimeType='text/plain']
Warning: Ensure that this MIME mapping is needed for your Web server before adding it to the list. Configuration files such as .CONFIG or dynamic scripting pages such as .ASP or .ASPX, should not be downloaded directly and should always be processed through a handler. Other files such as database files or those used to store configuration, like .XML or .MDF, are sometimes used to store configuration information. Determine if clients can download these file types before enabling them.
Install ASP.NET.
Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click here.
Links and More Information
This error occurs when the file extension of the requested URL is for a MIME type that is not configured on the server. You can add a MIME type for the file extension for files that are not dynamic scripting pages, database, or configuration files. Process those file types using a handler. You should not allows direct downloads of dynamic scripting pages, database or configuration files.
View more information »

**Comment by snipe** [comment]
If you type in assets.portal.local/index.php into the browser, what do you see?

**Comment by aahmed2015** [comment]
Hi Buddy,

Apologies for not being able to reply sooner, work has been getting crazy for me!

In IIS can you confirm by expanding your Snipe-IT branch that it shows only the following folders?

-Snipe-IT
+Assets
+IMG
+Packages
+Uploads

If you don't see this, then I'm afraid your IIS isn't set up properly, also I noticed you added another folder to your location.

I only have the following folders in my Snipe-IT installation:

![capture](https://cloud.githubusercontent.com/assets/10409566/5676761/66e3f8fc-97d3-11e4-814a-ac511c8a4216.JPG)

Because you added another folder to your root directory, I am wondering if this is the root cause of it, since the URL rewrite is definitely meant to redirect to pick up the index.php and here it cannot perform this because it's complaining about file permissions.

Try cut/paste your folder: 'snipe-it-1.1' to 'wwwroot' then deleting your 'snipe-it' folder, then map it up with IIS again and see if that works.

**Comment by pos1234** [comment]
@snipe when I type assets.portal.local/index.php i get the following message:

Server Error in Application "SNIPE IT"
Internet Information Services 7.5
Error Summary
HTTP Error 404.3 - Not Found
The page you are requesting cannot be served because of the extension configuration. If the page is a script, add a handler. If the file should be downloaded, add a MIME map.
Detailed Error Information
Module	StaticFileModule
Notification	ExecuteRequestHandler
Handler	StaticFile
Error Code	0x80070032
Requested URL	http://assets.portal.local:80/index.php
Physical Path	C:\inetpub\wwwroot\snipe-it-1.1\public\index.php
Logon Method	Anonymous
Logon User	Anonymous
Most likely causes:
It is possible that a handler mapping is missing. By default, the static file handler processes all content.
The feature you are trying to use may not be installed.
The appropriate MIME map is not enabled for the Web site or application. (Warning: Do not create a MIME map for content that users should not download, such as .ASPX pages or .config files.)
If ASP.NET is not installed.
Things you can try:
In system.webServer/handlers:
Ensure that the expected handler for the current page is mapped.
Pay extra attention to preconditions (for example, runtimeVersion, pipelineMode, bitness) and compare them to the settings for your application pool.
Pay extra attention to typographical errors in the expected handler line.
Please verify that the feature you are trying to use is installed.
Verify that the MIME map is enabled or add the MIME map for the Web site using the command-line tool appcmd.exe.
To set a MIME type, use the following syntax: %SystemRoot%\windows\system32\inetsrv\appcmd set config /section:staticContent /+[fileExtension='string',mimeType='string']
The variable fileExtension string is the file name extension and the variable mimeType string is the file type description.
For example, to add a MIME map for a file which has the extension ".xyz": appcmd set config /section:staticContent /+[fileExtension='.xyz',mimeType='text/plain']
Warning: Ensure that this MIME mapping is needed for your Web server before adding it to the list. Configuration files such as .CONFIG or dynamic scripting pages such as .ASP or .ASPX, should not be downloaded directly and should always be processed through a handler. Other files such as database files or those used to store configuration, like .XML or .MDF, are sometimes used to store configuration information. Determine if clients can download these file types before enabling them.
Install ASP.NET.
Create a tracing rule to track failed requests for this HTTP status code. For more information about creating a tracing rule for failed requests, click here.
Links and More Information
This error occurs when the file extension of the requested URL is for a MIME type that is not configured on the server. You can add a MIME type for the file extension for files that are not dynamic scripting pages, database, or configuration files. Process those file types using a handler. You should not allows direct downloads of dynamic scripting pages, database or configuration files.
View more information »

**Comment by pos1234** [comment]
@aahmed2015 

Hey mate,

Thanks agin for your reply, your right I did have an extra Snipe-It folder, however it wasn't me that created this this happened during the install. I have done what you said and copied the contents of that directory into the /wwwroot i've also remapped ISS to point to this new location, please see screen shot below:

![image](https://cloud.githubusercontent.com/assets/10423056/5678178/8bd4bb4c-97e7-11e4-8975-883a41b88bdb.png)


I have exactly the same contents as you in my snipe-it folder:

![image](https://cloud.githubusercontent.com/assets/10423056/5678198/b720e78a-97e7-11e4-9ae7-202347149dad.png)

But still I get the same error message as reported to @snipe :-/

**Comment by pos1234** [comment]
I've also gone to edit site in IIS and selected "test settings":

![image](https://cloud.githubusercontent.com/assets/10423056/5678269/895f8026-97e8-11e4-9df8-458356dca9e6.png)

When i select this this is the following message I get:

![image](https://cloud.githubusercontent.com/assets/10423056/5678279/9f34fa52-97e8-11e4-9cab-439d839dcf77.png)

All the permissions are correct i've double checked and double checked again :-p

**Comment by pos1234** [comment]
Here are the permissons on the snipe-it folder:

![image](https://cloud.githubusercontent.com/assets/10423056/5678336/2f010bda-97e9-11e4-99c0-a9a9446cc602.png)

**Comment by pos1234** [comment]
Here is a blog i've found on this error message.... seems its nothing to worry about:

http://blogs.msmvps.com/bernard/2009/11/04/warning-authorization-cannot-verify-access-to-path-c-inetpub-wwwroot/

**Comment by pos1234** [comment]
Is anyone available to provide any further guidance?

**Comment by snipe** [comment]
@pos1234 where did you leave off on this?

**Comment by pos1234** [comment]
@snipe Hey thanks for the reply, I got to the point that i've last described. Hopefully someone can advise on what to do next :-/

**Comment by snipe** [comment]
This looks like it might be a windows specific configuration issue. @madd15, do you have any insight here?

**Comment by madd15** [comment]
@pos1234  In terms of IIS claiming it can't see the public folder that can be ignored.

Have you imported the .htaccess file from the public directory in to URL Rewrite?

**Comment by snipe** [comment]
Hi @pos1234 - any updates on this?

**Comment by 13ruce1337** [comment]
Hey @snipe I first want to thank you for this awesome web app. I'm resurrecting this because I'm currently running into this same issue of getting a 403 error. I have given permissions to "everyone" to try and get this working and it doesn't seem to be the issue.

![image](https://cloud.githubusercontent.com/assets/5588408/9552650/c33e67ee-4d87-11e5-9226-dedf12fefcd0.png)

Below is my URL Rewrite:

![image](https://cloud.githubusercontent.com/assets/5588408/9552683/fa7672f6-4d87-11e5-8c73-7330732a89e2.png)

I have debug mode on and I'm getting nothing to the logs in the <code>snipe-it\app\storage\logs</code> folder.

I'm using the following site bindings:

![image](https://cloud.githubusercontent.com/assets/5588408/9552787/a5a739e4-4d88-11e5-8023-abb6ad132eae.png)

Any direction would be greatly appreciated.

Thanks!

**Comment by madd15** [comment]
Is the physical path set to the public directory?

**Comment by 13ruce1337** [comment]
Sorry for the delay, eventful weekend with my g/f's bday. The physical path is set:

![image](https://cloud.githubusercontent.com/assets/5588408/9578719/6192b0ce-4fba-11e5-86d3-4ec48376b7af.png)

For the records, I'm using Windows Server 2008 R2 Standard

**Comment by madd15** [comment]
In the IIS manager under `Default Document` is index.php at the top?

Assume you have place Snipe-IT folder at that path.

One thing I'm not 100% sure on is that i have noticed that some zip file are blocked when downloaded which i think is inherited by the files with in the zip, could you check the properties of any of the file in your snipe it directory and see if they have an unblock button at the bottom.

**Comment by 13ruce1337** [comment]
That's exactly what it was, thanks madd15!

I'm now getting a 500 error but I think i'll manage it by the time you read this.

![image](https://cloud.githubusercontent.com/assets/5588408/9605810/d2279d3a-508d-11e5-92ef-097687eeb878.png)

**Comment by glennbevan** [comment]
Hi

I am having this exact same issue! (Prior to the Server Error: 500)

When I try to import the rules from the .htaccess I get the following error:

![weeoe](https://cloud.githubusercontent.com/assets/21214889/17923645/06b72782-69dd-11e6-9dd3-1b28d2258dab.PNG)

How do I over come this?

**Comment by glennbevan** [comment]
This guy also had the issue but not sure how he resolved this one specifically:

https://github.com/snipe/snipe-it/issues/2408

**Comment by snipe** [comment]
@glennbevan - the version of Snipe-IT that they were installing was much older, so this isn't really that related anymore, but as I mentioned in the other thread, you can safely remove that one. I have no idea why IIS cannot parse it, but it's not required.
