### ISSUE TITLE
It looks like your files are owned by root, which might be a root/admin account. It's never a good idea to run a website with escalated priveliges. 

### ISSUE THREAD

**Issue by passboltUser** [snipe/snipe-it#4410]
#### Expected Behavior (or desired behavior if a feature request)

Having a green background / no problem.

-----

#### Actual Behavior

Under `/setup` I have one red row:

`File Owner | x | It looks like your files are owned by root, which might be a root/admin account. It's never a good idea to run a website with escalated priveliges.`

Files are owned by `root:root`. I suppose I need to create a new user or can I do a `chown www-data:www-data`

**Comment by HinchK** [comment]
@passboltUser, please do not create an issue for an installation question that is covered in documentation, and definitely don't submit the issue if you solved your own issue while typing it out in the last sentence!

The snipe-it gitter channel is a terrific place to get your first-time installation questions answered by the community.    https://gitter.im/snipe/snipe-it  I promise your question will be answered much faster there.

Quoting the documentation:
https://snipe-it.readme.io/docs/server-configuration --
```
IMPORTANT:
You should never run Snipe-IT (or any website, ever) as a root (Linux) or Administrator (Windows). Create an unprivileged user and make them the owner of the files
```

You supposed correctly!  
`chown -R www-data:www-data ../snipe-it`.

**Comment by passboltUser** [comment]
Calm down @HinchK.. . I browsed https://snipe-it.readme.io/docs/server-configuration but can't find it. 
I wasn't sure but I just checked and asked it already -- ok: https://github.com/snipe/snipe-it/issues/3950

**Comment by HinchK** [comment]
All good @passboltUser!   Didn't mean to come down on you, just trying to lead your to our Gitter chatroom https://gitter.im/snipe/snipe-it where raising an issue as a question will be served within minutes.  Issues turnaround time can be days++.

Best of luck!
