### ISSUE TITLE
all report options are not listing (only "Depreciation Report" is showing)

### ISSUE THREAD

**Issue by shahandas** [snipe/snipe-it#442]
I have installed Snipeit V1.1 on a linux box and in reports tab only "Depreciation Report" is showing.

the followings reports are not showing 
License Report
Asset Report
Custom Asset Report

please help..

**Comment by wvanhiele** [comment]
I have exactly the same problem with the reports, however on a Windows2012R2/IIS installation. Everything else works. Any news?

**Comment by snipe** [comment]
Custom reports were not in v1.1, as indicated by the commits since v1.1 was released. https://github.com/snipe/snipe-it/compare/v1.1...master

You could have grabbed the latest from develop, but I've made v1.2 available now. https://github.com/snipe/snipe-it/releases/tag/v1.2

**Comment by shahandas** [comment]
Thanks :)
