### ISSUE TITLE
Licensing to AssetTag 

### ISSUE THREAD

**Issue by antikilahdjs** [snipe/snipe-it#4420]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

Hi there, 

Before updated my SnipeIT to latest version was possible to link licensing information to asset name but now is no more possible to me . I have my pc names in asset tag . Someone know if it is possible fix or change this problem? I am so sorry but my English is worst.

![chrome_2017-11-10_17-13-06](https://user-images.githubusercontent.com/33559260/32681267-a463073c-c63c-11e7-91b3-39ad07ff506c.png)

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Confirm whether the error is reproduceable on the demo.


![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by antikilahdjs** [comment]
Hi thanks  and I am so sorry . The version is 4.0.15 .
My OS Server is Centos 7 with Apache
I already install my SnipeIT from sh. script , before that's error I used v3 version and I update to v4 .
In demo appears perfect and working likes good .

See the attach , the demo is ok show the assets to link a licensing .
![chrome_2017-11-11_18-30-02](https://user-images.githubusercontent.com/33559260/32694468-78f2ed92-c70e-11e7-8fce-c498f554cb47.png)

Thank you

**Comment by snipe** [comment]
> In demo appears perfect and working likes good .

You should upgrade your version then. The demo reflects the latest on the master branch.
