### ISSUE TITLE
Status (Or Report Status) Should Change to Reflect User Assignment

### ISSUE THREAD

**Issue by TheVakman** [snipe/snipe-it#4422]
#### Expected Behavior (or desired behavior if a feature request)
When an asset is assigned to a user, in SnipeIT, it shows as "Deployed". 
This is good but this should either become the actual status or the at least the reports should show this in the status column.

I understand that the status is irrelevant when there is an assignee but when the report is handled to those that don't know SnipeIT, it is confusing for them. This is because they need to ignore the status column if a user is assigned and pay attention to it if a user is not. Ex. Ready to Deploy with a user assigned does not mean it's Ready to Deploy but Ready to Deploy with no user assignment is important.

This would be more of a feature request.

-----

#### Actual Behavior
If an asset is "Ready to Deploy", when deployed, just adds a label of "Deployed" in SnipeIT but in the asset report, there is no column to report on this. This means users viewing the report need to ignore the status column if they see a user in the "Assigned To" column or pay attention to the status column if no user is assigned. Unless, one goes back to manually edit the status each time an asset is assigned.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:
Version of Snipe-IT you're running
4.1.3.
Version of PHP you're running
7.0.23
Version of MySQL/MariaDB you're running
5.5.56-MariaDB
What OS and web server you're running Snipe-IT on
CentOS 7.4.1708

**Comment by snipe** [comment]
This is the intended behavior for now. We explain the meta status on the status labels page and the documentation. https://snipe-it.readme.io/v4.0/docs/overview#section-status-labels

**Comment by TheVakman** [comment]
@snipe I don't disagree with that but there isn't a way to report on those labels (at least, that I see) when I run a report.
