### ISSUE TITLE
Auto-increment tags does not work after upgrade

### ISSUE THREAD

**Issue by ebonweaver** [snipe/snipe-it#4424]
#### Expected Behavior (or desired behavior if a feature request)

New Assets would increment as they did in v3

-----

#### Actual Behavior

It tries to start over at 1 instead of using unused tag numbers

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
Upgrade
- Version of Snipe-IT you're running
4.1.3
- Version of PHP you're running
7.0.22
- Version of MySQL/MariaDB you're running
5.7.20
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04 LTS with Apache 2.4.18
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
NA
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
NA, just making a new asset
- If a stacktrace is provided in the error, include that too.
NA
- Any errors that appear in your browser's error console.
NA
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
Maybe?  The demo seems to have been set to a high number for next tag, but it also seems to be WAY above the current number of assets, so yes it seems to not be using the next available, or reusing deleted numbers?  Unclear if this means we have to figure out what number to tell it to start at with v4, where v3 just knew, in which case if this is by design it needs to be in the release notes
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
That's asking WAY too much at this point... 
- Indicate whether or not you've manually edited any data directly in the database
NO

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Update the auto-incremented in the Settings page.

(Additionally, please try to check this repo for closed issues prior to posting - this has been mentioned a few times now.)

**Comment by ebonweaver** [comment]
If that may people are getting tripped up by a significant behavioral change, seems it's worth noting in the upgrade notes.
