### ISSUE TITLE
Rename Admin permission

### ISSUE THREAD

**Issue by ebonweaver** [snipe/snipe-it#4431]
#### Expected Behavior (or desired behavior if a feature request)

Admins are admins

-----

#### Actual Behavior

Admins are NOT admins

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade
- Version of Snipe-IT you're running
4.1.3

I eliminated all the rest because this isn't a bug, it's a confusing design that I'm suggesting be clarified.  The fact that the documentation clearly states admins aren't admins indicates a design issue to me.  If I'm decoding this correctly, "Admin" should actually say "Global Grant", because it's an override to keep you from having to click Grant on every single permission.  If it does MORE than that, it really needs to specifically state what else it does so this is clear.  There is a lack of consistency between the UI and the documentation right now that confuses this.  The UI says "Determines whether the user has access to most aspects of the admin." which one assumes means it DOES grant access to the admin screen, but it's unclear which items can be controlled and which would require super user.  However, the documentation states "Can NOT access Admin Settings" which contradicts the UI.  So again, totally unclear what it does, and seems it has a name contradicting its implications, so likely needs a rename, and clear documentation is definitely needed.

**Comment by ebonweaver** [comment]
Hey stalebot, how about you check to see if this was resolved before trying to shut it down?

**Comment by snipe** [comment]
The admin role doesn't really do anything anymore, since we made the permissions more granular.
