### ISSUE TITLE
All assets doesn't show all assets

### ISSUE THREAD

**Issue by ebonweaver** [snipe/snipe-it#4432]
#### Expected Behavior (or desired behavior if a feature request)

When you select All Assets, you will see ALL assets.

-----

#### Actual Behavior

You don't see all assets.  Several categories like archived are missing.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade
- Version of Snipe-IT you're running
4.1.3
- Version of PHP you're running
7.0.22
- Version of MySQL/MariaDB you're running

- What OS and web server you're running Snipe-IT on
Ubuntu 16 server w/ Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh

I believe this is by design in v4, but it creates a downgrade condition from v3.  Previously, you could use the search to find ANYTHING, regardless of the status of the asset.  Now that's not possible, which means you have to perform 8 different searches if you have that many statuses instead of just one search as before.  Not ideal.  The main issue seems to be that the All Assets option does NOT show you ALL assets, but only certain statuses.  We need a way to search everything, in every status, just like v3 did.

**Comment by ebonweaver** [comment]
For completeness, and upon more testing, the main issue as stated is List All shows only all non-archived statuses.  It needs to list ALL.  A good addition after fixing that based on the new operation would be All Active, which would be all non-archived, and a good counterpart to the existing All Archived.

**Comment by snipe** [comment]
This is by design - in the documentation, we specify that Archived assets will not show up in All Assets.

**Comment by ebonweaver** [comment]
This may be by design, but it's against the meaning of the words, and a downgrade in ability (for our operations) from the previous version.  I understand you don't want to call this a bug.  Please do not close and disregard however, please call this a feature request or enhancement.
1. Make All Assets actually be ALL assets.
2. Add All Active which would do what All Assets does currently.
This allows for your intended functionality as well as our needed (and previously had) functionality.  We see the merit in your intent, but the implementation is misleading and limiting.

**Comment by snipe** [comment]
The option to include Archived assets in the List All/Search is now on the develop branch.
