### ISSUE TITLE
API Use Questions

### ISSUE THREAD

**Issue by therealjoshuad** [snipe/snipe-it#4433]
#### Expected Behavior (or desired behavior if a feature request)

Invoking a GET request to the API returns more than 50 result.

-----

#### Actual Behavior

When using the 'http://servername/api/v1/hardware' URI in a request, I only get 50 objects returned. I can grab more objects using the **limit** parameter in the URI, but that could mean that if I specify a limit that's too low, I might miss object. Is that the only way to change the size of the result set that's returned? I'm pretty novice when it comes to working with APIs, so maybe I'm just missing something?

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?: Upgrade
- Version of Snipe-IT you're running: Latest
- Version of PHP you're running: 7
- Version of MySQL/MariaDB you're running: MySQL 14.14
- What OS and web server you're running Snipe-IT on: Ubuntu 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: none
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: API (See URI above)
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo: also experienced in demo, using the API explorer in the docs
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.: I can throw "limit=xxx" in the URI to grab more results
- Indicate whether or not you've manually edited any data directly in the database: no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
The `limit` parameter dictates the result set size, `offset` tells it how many to skip.
