### ISSUE TITLE
Location status not updating on checkout

### ISSUE THREAD

**Issue by techweasel** [snipe/snipe-it#4434]
#### Expected Behavior (or desired behavior if a feature request)

In v4 checking out an item now gives the option to specify a location (Checkout to: "Select a Location"). Setting this field during checkout should update the items location status to the location specified. 

-----

#### Actual Behavior

The asset maintains either it's prior location status, or the default location of the user being assigned. Have tested with assets with existing location, default location preferences, and no location information whatsoever, and users with and without default location preferences. 

The asset is set to the default location of the user (if one exists), or maintains it's the location status it had prior to Checkout. In either case any location specified during checkout is ignored. 

By comparison - setting a location on Checkin *does* update the location as I would expect. 

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - Recent upgrade. 
- Version of Snipe-IT you're running - v4.1.3 build 48
- Version of PHP you're running - 5.6.31
- Version of MySQL/MariaDB you're running - 14.14
- What OS and web server you're running Snipe-IT on CentOS 7.4.1708 / Apache 2.4.27
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) git
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - /hardware/##/checkout
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. Yes, reproducible - Created a new user with no default location. Assigned an asset to them and specified a new location during checkout. Asset was checked out, but continued to show the original location the asset had prior to checkout.

**Comment by adambowen** [comment]
I hit this the other day, I think @snipe already fixed it in 5aee5a3f3d97da9b8e0f0e3555a67b1d8ea8bb1f
