### ISSUE TITLE
Licence Checkout: Qty not decrease

### ISSUE THREAD

**Issue by vipin2079** [snipe/snipe-it#4436]
I  add Symantec Licence with 150 seat but during checkput it's decrease only one seat not other.Trying to put other seat but name replace on seat 1.

**Comment by Diniver** [comment]
I am not able to reproduce it on my site. On demo site only _Photoshop_ licence is having this problem but others are ok.  Download the latest version and try again.
Can you also provide version which you are using and logs if you have any.

**Comment by vipin2079** [comment]
I  already installed latest version v4.1.3 build 94
[laravel-2017-11-14.log](https://github.com/snipe/snipe-it/files/1471915/laravel-2017-11-14.log)

**Comment by Diniver** [comment]
You have quite a lot of: `Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'forge' in C:\xampp\htdocs\snipe-it\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:47
`

Are you sure you set all permissions correctly? 
https://snipe-it.readme.io/docs/windowsiis 
After you apply changes, clear the log and try again. If you still have the problem then someone more knowledgeable from me has to help you.

**Comment by vipin2079** [comment]
I am using xampp is xampp same step need

**Comment by vipin2079** [comment]
Thanks this is windows permission issue .Issue resolve now.
