### ISSUE TITLE
Asset maintenance list doesn't paginate correctly

### ISSUE THREAD

**Issue by adambowen** [snipe/snipe-it#4437]
#### Expected Behavior (or desired behavior if a feature request)

When you have more than 20 (or whatever the page size is set to) maintenance records, you can page through them.

-----

#### Actual Behavior

If you have more than 20 maintenance entries, only the first 20 show.

This is basically a bug in how the asset maintenance API returns the total count, it is returning the count after limiting the number of rows rather than before. I've patched this in our fork:

https://github.com/BiositeSystems/snipe-it/commit/c6c720183e078d57c5022afedb040fcb527cb703

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? It's on the demo site.
- Version of Snipe-IT you're running. v4.1.3 build 48 (g74aa562)
- Version of PHP you're running 7.0.25
- Version of MySQL/MariaDB you're running. ???
- What OS and web server you're running Snipe-IT on. ???
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc). ???
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error. No error.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error. https://demo.snipeitapp.com/hardware/maintenances
- If a stacktrace is provided in the error, include that too. No error.
- Any errors that appear in your browser's error console. No errors.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. Yup.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. Nothing relevant.
- Include what you've done so far in the installation, and if you got any error messages along the way. Nothing relevant.
- Indicate whether or not you've manually edited any data directly in the database. Not relevant.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Hi @adambowen  - thanks for this - would you be willing top put together a PR against the develop branch?

**Comment by snipe** [comment]
Actually, never mind - it's a small enough change, I'll just patch it.
