### ISSUE TITLE
Can anyone help with the correct process to upgrade/switch branches

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#444]
Running on Windows, IIS 7.5. Installation was working fine, switched to the development branch to add some features we were looking for. Seemed to work and found/pieced together some of the process, only issue is with the reports section.

Now I want to try another pull from the dev branch but this time try to go about it the right way.

Any help would be greatly appreciated.

**Comment by snipe** [comment]
Hi @kobie-chasehansen - I'm not 100% sure I understand what you're asking. You would fork the repo, create a new feature branch from the develop branch, make your changes, and then submit a pull request to the original repo. More info is here: http://docs.snipeitapp.com/contributing/README.html

Does that answer your question?

**Comment by kobie-chasehansen** [comment]
Sorry, no knowledge in development. I mean how do I go about updating my windows installation that's already been installed. I originally installed the stable branch and attempted to switch to the development branch. Was able to get my install back up and running but pretty sure I did a lot of things wrong. I work in operations and really love the product just lack a lot of the knowledge to get the code running. For instance when I attempted to switch to the development code I did seem to get things running but broke the reporting section.

**Comment by snipe** [comment]
Hey @kobie-chasehansen - if you're not as comfy with development stuff, you should probably stick with `master` or official releases. Nothing gets released without being tested, and the release notes always tell you what you need to do (run migrations, etc) to upgrade so nothing blows up.

**Comment by kobie-chasehansen** [comment]
think i'm learning my away around the upgrade cycle. at least the last one went smooth for me. closing this issue out. thank you
