### ISSUE TITLE
License Checkout to asset: not able to search for user anymore

### ISSUE THREAD

**Issue by MPIAE-IT** [snipe/snipe-it#4440]
#### Expected Behavior (or desired behavior if a feature request)

Checking out a license to an asset: It was possible to search for an asset by username, the asset is assigned to

-----

#### Actual Behavior

no users are visible - no users are found

![bildschirmfoto 2017-11-14 um 16 38 06](https://user-images.githubusercontent.com/16922521/32788726-4d5bbb3e-c95a-11e7-8954-2d8f5924b382.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Upgrade**
- Version of Snipe-IT you're running **v4.1.3 build 48 (g74aa562)** 
- Version of PHP you're running **7.0**
- Version of MySQL/MariaDB you're running **5.5.57-0ubuntu0.14.04.1**
- What OS and web server you're running Snipe-IT on **Ubuntu 14.04.5 LTS**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **manual**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **No error**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **Licenses -> Checkout License**
- If a stacktrace is provided in the error, include that too. **NO**
- Any errors that appear in your browser's error console. **NO**
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. **Same thing is happening in the demo**
- Include what you've done so far in the installation, and if you got any error messages along the way. **Updated to the recent version on GitHub master**
- Indicate whether or not you've manually edited any data directly in the database
**Never touched it**

**Comment by snipe** [comment]
@MPIAE-IT so I'm clear, it is loading the list of user's correctly and you can search on name just not username, right?

**Comment by MPIAE-IT** [comment]
I can checkout to an user just fine. Checking out to an asset is where no user is displayed. Before this upgrade to 4.1.3 (was on 4.0.9) it was possible to checkout to an asset, but I was able to search for this asset by the username. I cannot search for user or username. In the demo it is not working either.

**Comment by snipe** [comment]
I pushed out a possible fix for this on the develop branch - can you give it a try?

**Comment by MPIAE-IT** [comment]
Indeed the issue is fixed. Thank you!
