### ISSUE TITLE
Create Asset page forget selected picture if a mandatory field is detected as empty while saving

### ISSUE THREAD

**Issue by SkinnyV** [snipe/snipe-it#4441]
If you create an asset and choose a picture but forgot to fill a field while saving, snipe-it remind you of the missing field but remove the previously selected asset picture. It would be nice if it would keep the selection in memory.

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - Fresh Install
- Version of Snipe-IT you're running - 4.1.3 build 48
- Version of PHP you're running - php 7.0.22
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on - ubuntu 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - no eror
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Create asset page
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. - Reproduceable on demo

**Comment by snipe** [comment]
That's sort of to be expected though. The asset doesn't exist yet so there's no asset to attach a picture to. There are convoluted ways we could code around it, but I don't think I want to introduce the additional complexity to solve this issue.
