### ISSUE TITLE
SW Licence not display user portal

### ISSUE THREAD

**Issue by vipin2079** [snipe/snipe-it#4442]
I checked out licence and assign to particular user .Now I open respective user portal see Asset display only Not Software even  SW Checkout.

Version:Latest

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by vipin2079** [comment]
Hello  Team,
Sorry for late rrsponse.Regarding your query:

Version of Snipe-IT you're running:v4.1.9 - build 3128
What OS and web server you're running Snipe-IT on:Windows 7 Profeestional and WAMP
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc):Manual
If you're getting an error in your browser, include that error:No Eoor
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error:I checkedout licence to particular user and login with user  Licence not appear in SW Section
If a stacktrace is provided in the error, include that too.
Any errors that appear in your browser's error console.
Confirm whether the error is reproduceable on the demo.
Include any additional information you can find in app/storage/logs and your webserver's logs.
Include what you've done so far in the installation, and if you got any error messages along the way.
Indicate whether or not you've manually edited any data directly in the database
enlkq1k
