### ISSUE TITLE
Groups data not visible via v1 API for non-superusers

### ISSUE THREAD

**Issue by ciasaboark** [snipe/snipe-it#4443]
#### Expected Behavior (or desired behavior if a feature request)

Group information should be visible to admin users via the v1 API:
`/api/v1/groups?limit=9999`

Permissions to view/create/edit/delete groups should be controlled in the same manner as permissions for users, assets, locations, etc...

-----

#### Actual Behavior

API call returns status code 500 unless the token's owner has superuser privileges.  This is true of users marked as 'admin' as well.

The API call works if the token belongs to a superuser, but that token would also carry extra permissions.  Furthermore, superusers can view assets/users for every company, so there is no way to pull group information without giving access to every company.

Permissions page does not have any permissions to manage access to group data.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
upgrade

- Version of Snipe-IT you're running
v4.0.9 build 215 (also 4.1.3 build 94)

- Version of PHP you're running

- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
The admin role doesn't really have much purpose any more, since the more granular permissions in v4.  The admin settings don't have a notion of company, so they really belong only to superadmins, especially since they can change permissions for any user that belongs to them.

**Comment by ciasaboark** [comment]
Can the v1 API be updated to allow access to `/api/v1/groups` for any user that also has access to view users?

A user with permission to view users can already pull group information in aggregate by viewing all user records, there isn't much reason to restrict access to the groups API call.

This would have the added benefit of not requiring an admin or superuser token for REST calls.
