### ISSUE TITLE
Force IP?

### ISSUE THREAD

**Issue by Eric072691** [snipe/snipe-it#4446]
#### Expected Behavior (or desired behavior if a feature request)

When I login to Snipe-IT, I reach inventory.domain.com, once logged in, it should continue to use inventory.domain.com as the URL allowing me to access the install from off-site.

My .env is set properly with APP_URL=http://inventory.domain.com

Please note, my install is behind a firewall. Is there a way to force an address instead of the IP? Or is there a change I should be making in another file?

-----

#### Actual Behavior

When I login to Snipe-IT, I reach inventory.domain.com, once logged in, it uses the server's internal IP, 10.0.20.15 as the URL.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install.
- Version of Snipe-IT you're running
v4.1.3 build 48 (g74aa562)
- Version of PHP you're running
7.0.18-0ubuntu0.16.10.1
- Version of MySQL/MariaDB you're running
5.7
- What OS and web server you're running Snipe-IT on
Ubuntu, apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Did you try clearing your config cache? Snipe-IT uses the APP_URL in your env to determine what the URL should be.

`php artisan config:clear`

**Comment by Eric072691** [comment]
I just did that and restarted the server for good measure. 

Looks like there URL is still coming up as the local.

In fact, when I did the initial install, my browser history says it used the IP rather than fqdn.

**Comment by snipe** [comment]
What do you have as the `SERVER_NAME` in your web server configuration?

**Comment by Eric072691** [comment]
inventory.domain.com

I'll post the contents of my site config file when I get home; stepped out for dinner.

I may try a reinstall, what's the best method? Just removing the snipe-it folder from www and cloning a new one from git?

**Comment by Eric072691** [comment]
Sorry, didn't mean to close issue.

**Comment by snipe** [comment]
I don't think a reinstall will help here, but you're welcome to try. You can remove the old directory, but make sure any uploads are backed up, if you have any.

**Comment by Eric072691** [comment]
Contents of site config file..

<VirtualHost *:80>
    ServerName inventory.domain.com
    ServerAlias inventory.domain.com
    DocumentRoot /var/www/snipe-it/public
    <Directory /var/www/snipe-it/public>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
    </Directory>
</VirtualHost>

**Comment by snipe** [comment]
What do you have in your .env for APP_TRUSTED_PROXIES?

**Comment by snipe** [comment]
Try using:

`APP_TRUSTED_PROXIES =10.0.20.15`

in your .env.

(Be sure to clear your config cache)

**Comment by Eric072691** [comment]
That did it!

I don't think I was using a reverse proxy, but I guess it was.

**Comment by snipe** [comment]
Great! It may not be a reverse proxy, but the end result is the same - we're telling the system to use specific header overrides that Snipe-IT is allowed to trust. I'll make a note in the documentation.
