### ISSUE TITLE
Failed upgrade from 4.1.3 to 4.1.4

### ISSUE THREAD

**Issue by tx7** [snipe/snipe-it#4447]
`Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 1 install, 5 updates, 4 removals
  - Removing aws/aws-sdk-php (3.36.32)
  - Removing aws/aws-sdk-php-laravel (3.1.0)
  - Removing mtdowling/jmespath.php (2.4.0)
  - Removing jenssegers/rollbar (v1.5.1)
  - Updating mtdowling/cron-expression (v1.2.0 => v1.2.1):  Checking out 9504fa9ea6
  - Updating nikic/php-parser (v3.1.1 => v3.1.2):  Checking out 08131e7ff2
  - Updating psy/psysh (v0.8.13 => v0.8.14):  Checking out 91e53c1656
  - Updating watson/validating (3.1.1 => 3.1.2):  Checking out 22edd06d45
  - Updating rollbar/rollbar (v0.18.2 => v1.3.3):  Checking out 2e092656f4
  - Installing rollbar/rollbar-laravel (v2.2.1): Cloning 8d46138367
Generating optimized autoload files
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Generating optimized autoload files
PHP Fatal error:  Class 'Aws\Laravel\AwsServiceProvider' not found in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 683

                                                           
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Aws\Laravel\AwsServiceProvider' not found         
                                                           

PHP Fatal error:  Class 'Aws\Laravel\AwsServiceProvider' not found in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 683

                                                           
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Aws\Laravel\AwsServiceProvider' not found         
                                                           

PHP Fatal error:  Class 'Aws\Laravel\AwsServiceProvider' not found in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php on line 683

                                                           
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Class 'Aws\Laravel\AwsServiceProvider' not found         
                                                           
`

**Comment by snipe** [comment]
Per the upgrade notes, did you delete the files in `bootstrap/cache`?

**Comment by tx7** [comment]
Yes, I just did, and the php-curl already installed.

`Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Generating optimized autoload files
PHP Fatal error:  Class 'Aws\Laravel\AwsServiceProvider' not found in /opt/snipe-it/config/aws.php on line 23
PHP Fatal error:  Class 'Aws\Laravel\AwsServiceProvider' not found in /opt/snipe-it/config/aws.php on line 23
PHP Fatal error:  Class 'Aws\Laravel\AwsServiceProvider' not found in /opt/snipe-it/config/aws.php on line 23`

**Comment by tx7** [comment]
By the waym I'm using Debian 7 with Nginx.

**Comment by snipe** [comment]
Try `composer dump` and `composer dump-autoload`

**Comment by snipe** [comment]
(It's a caching issue - we just need to figure out where it's being cached on your system)

**Comment by tx7** [comment]
On my system, I've to ran: 
`php composer.phar dump
php composer.phar dump-autoload`

but same errors.

**Comment by tx7** [comment]
Should I remove an entire Snipe-It, and re-install it?

**Comment by snipe** [comment]
No, definitely not. How about `composer clear`?

**Comment by tx7** [comment]
no luck.

**Comment by tx7** [comment]
I'm looking at this link: [,](https://github.com/aws/aws-sdk-php-laravel) and it says: ```
'providers' => array(
        // ...
        Aws\Laravel\AwsServiceProvider::class,
```

is need for config/app.php

Not sure if it applies for Snipe-IT.

**Comment by snipe** [comment]
@tx7 we removed that package, so it's not in the app provider anymore. It's being cached somewhere by composer though, which is why you're seeing that error.

**Comment by snipe** [comment]
Try `artisan config:cache`

**Comment by snipe** [comment]
(Additionally, you probably shouldn't be running composer as root, FYI.)

**Comment by tx7** [comment]
`Cannot create cache directory /home/tx7/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/tx7/.composer/cache/files/, or directory is not writable. Proceeding without cache

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "artisan" is not defined.                               
                                                                  `

**Comment by snipe** [comment]
> Cannot create cache directory /home/tx7/.composer/cache/repo/https---packagist.org/, or directory is not writable

This is one of the things that happens when you run composer as root.  It's why we always recommend never running composer as root. It puts cache directories and configs in odd places and you will invariably run into permissions issues later.

The command is `php artisan config:cache` - I left off the php part in my previous comment.

**Comment by tx7** [comment]
I see. Some of the commands wouldn't work if I don't run as root.

**Comment by snipe** [comment]
That should never be the case. What won't run?

**Comment by tx7** [comment]
Changing ownership of files.

**Comment by snipe** [comment]
Please be more specific.

**Comment by tx7** [comment]
`REQUIRED: Set Directory Permissions
You’ll need to make sure that the storage directory and its subdirectories, as well as the uploads directory within public are writable by your web server, since caches, log files, and uploaded files get written there. You should use the minimum permissions available for writing, based on how you’ve got your web server configured. You also need to change permissions for your uploads directory for user avatars and model images.

First, you'll need to figure out which user your webserver is running under. On Linux/OS X systems, it's usually something like "nobody", "apache", "httpd", "www", or "_www" Determine that by using ps auxwww - then you can see who the server is running as.

Once you've determined your webserver's user, you will want to make sure your webserver has ownership of the appropriate directories:

Shell
 chown -R that_username storage public/uploads
Next, you'll want to ensure that this user has write permissions to those directories.

On Linux/OS X, you would do something like this:

Shell
 chmod -R 755 storage
chmod -R 755 public/uploads`

**Comment by snipe** [comment]
I don't understand what this is supposed to mean. What specific errors are you getting?

You want ALL of your snipe-it project directory (and all subdirectories) to be owned by a non-root user.

**Comment by tx7** [comment]
The entire directory is own by non-root.

**Comment by snipe** [comment]
When I asked about what commands you couldn't run, you said:

> Changing ownership of files.

If the entire snipe-it project root is owned by non-root, and that non-root user is the one you're logged in as, there shouldn't be any issues changing ownership of files. Please give me a specific error message you're seeing.

**Comment by raakhtar** [comment]
if the pull out was from GIT try using >php upgrade.php (works like a charm) @tx7

**Comment by tx7** [comment]
I've edit my update script, but same errors:

`Cannot create cache directory /home/tx7/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/tx7/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update

                                                                                                             
  [ErrorException]                                                                                           
  file_put_contents(/opt/snipe-it/vendor/composer/installed.json): failed to open stream: Permission denied  
                                                                                                             

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

Cannot create cache directory /home/tx7/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/tx7.composer/cache/files/, or directory is not writable. Proceeding without cache
Generating optimized autoload files

                                                                                                                      
  [ErrorException]                                                                                                    
  file_put_contents(/opt/snipe-it/vendor/composer/autoload_namespaces.php): failed to open stream: Permission denied  
                                                                                                                      

dump-autoload [--no-scripts] [-o|--optimize] [-a|--classmap-authoritative] [--apcu] [--no-dev]

PHP Fatal error:  Class 'Aws\Laravel\AwsServiceProvider' not found in /opt/snipe-it/config/aws.php on line 23
PHP Fatal error:  Class 'Aws\Laravel\AwsServiceProvider' not found in /opt/snipe-it/config/aws.php on line 23
PHP Fatal error:  Class 'Aws\Laravel\AwsServiceProvider' not found in /opt/snipe-it/config/aws.php on line 23`

**Comment by snipe** [comment]
Again, these are permissions issues. 

`ls -al  /home/tx7/`

**Comment by snipe** [comment]
This may also be useful. https://snipe.net/2017/11/15/so-you-ran-composer-as-root/

**Comment by tx7** [comment]
I read your guide.
I deleted the .composer from root home directory.
I deleted entire snipe-it folder.

I git clone it again.
I gave snipe-it ownership as: snipeit:snipeit.

I got error when I ran this: `curl -sS https://getcomposer.org/installer | php
All settings correct for using Composer
The installation directory "/opt/snipe-it" is not writable
`

**Comment by snipe** [comment]
Once again, please run `ls -al /home/tx7/` and `ls al /opt/snipe-it` so I can see your permissions/owners.

**Comment by MacoWong** [comment]
I have the same problem also.

**Comment by pvhkai** [comment]
I am facing the same issue. 

I tried to update from version 4.1.3 to version 4.1.4 

For windows, use:
Typed in
-> composer install --no-dev --prefer-source
--> NO ERROR

composer dump-autoload
--> NO ERROR

php artisan migrate
--> AWS\Laravel\AwsServiceProvider” not found

php artisan config:clear
--> AWS\Laravel\AwsServiceProvider” not found

php artisan config:cache
--> AWS\Laravel\AwsServiceProvider” not found

**Comment by snipe** [comment]
@MacoWong @pvhkai did you delete the contents of the `bootstrap/cache` directory?

**Comment by tx7** [comment]
snipe-it directory:
`ls -la snipe-it
total 2336
drwxrwxr-x 16 snipeit  snipeit     4096 Nov 15 20:35 .
drwxr-xr-x  7 root     root        4096 Nov 15 19:50 ..
-rw-r--r--  1 snipeit  snipeit    21549 Nov 15 20:28 .all-contributorsrc
drwxr-xr-x 17 snipeit  snipeit     4096 Nov 15 20:28 app
-rw-r--r--  1 snipeit  snipeit     1646 Nov 15 20:28 artisan
drwxr-xr-x  3 snipeit  snipeit     4096 Nov 15 20:28 bootstrap
drwxr-xr-x 22 snipeit  snipeit     4096 Nov 15 20:28 bower_components
-rw-r--r--  1 snipeit  snipeit      875 Nov 15 20:28 bower.json
-rw-r--r--  1 snipeit  snipeit     9210 Nov 15 20:28 c3.php
-rw-r--r--  1 snipeit  snipeit      373 Nov 15 20:28 codeception.yml
-rw-r--r--  1 snipeit  snipeit     3228 Nov 15 20:28 CODE_OF_CONDUCT.md
-rw-r--r--  1 snipeit  snipeit     2273 Nov 15 20:28 composer.json
-rw-r--r--  1 snipeit  snipeit   224703 Nov 15 20:28 composer.lock
-rwxr-xr-x  1 snipeit  snipeit  1852323 Nov 15 20:35 composer.phar
drwxr-xr-x  2 snipeit  snipeit     4096 Nov 15 20:28 config
-rw-r--r--  1 snipeit  snipeit      317 Nov 15 20:28 CONTRIBUTING.md
-rw-r--r--  1 snipeit  snipeit       90 Nov 15 20:28 crowdin.yml
drwxr-xr-x  5 snipeit  snipeit     4096 Nov 15 20:28 database
drwxr-xr-x  2 snipeit  snipeit     4096 Nov 15 20:28 docker
-rw-r--r--  1 snipeit  snipeit      667 Nov 15 20:28 docker.env
-rw-r--r--  1 snipeit  snipeit     2898 Nov 15 20:28 Dockerfile
-rw-r--r--  1 snipeit  snipeit       67 Nov 15 20:28 .dockerignore
-rwxr-xr-x  1 snipeit  snipeit     2122 Nov 15 20:29 .env
-rw-r--r--  1 snipeit  snipeit     2731 Nov 15 20:28 .env.example
-rw-r--r--  1 snipeit  snipeit     1826 Nov 15 20:28 .env.testing
-rw-r--r--  1 snipeit  snipeit     1755 Nov 15 20:28 .env.testing-ci
-rw-r--r--  1 snipeit  snipeit      554 Nov 15 20:28 .env.tests
-rw-r--r--  1 snipeit  snipeit     1711 Nov 15 20:28 gh-changelog.php
drwxr-xr-x  8 snipeit  snipeit     4096 Nov 15 20:28 .git
-rwxr-xr-x  1 snipeit  snipeit       11 Nov 15 20:28 .gitattributes
drwxr-xr-x  2 snipeit  snipeit     4096 Nov 15 20:28 .github
-rwxr-xr-x  1 snipeit  snipeit     1061 Nov 15 20:28 .gitignore
-rw-r--r--  1 snipeit  snipeit      251 Nov 15 20:28 .htaccess
-rw-r--r--  1 snipeit  snipeit      956 Nov 15 20:28 index.html
-rwxr-xr-x  1 snipeit  snipeit      371 Nov 15 20:28 install.sh
-rwxr-xr-x  1 snipeit  snipeit    34519 Nov 15 20:28 LICENSE
-rw-r--r--  1 snipeit  snipeit     1686 Nov 15 20:28 package.json
-rw-r--r--  1 snipeit  snipeit      934 Nov 15 20:28 phpunit.xml
drwxr-xr-x  8 snipeit  snipeit     4096 Nov 15 20:28 public
-rw-r--r--  1 snipeit  snipeit    25646 Nov 15 20:28 README.md
drwxr-xr-x  6 snipeit  snipeit     4096 Nov 15 20:28 resources
drwxr-xr-x  3 snipeit  snipeit     4096 Nov 15 20:28 routes
drwxr-xr-x  2 snipeit  snipeit     4096 Nov 15 20:28 sample_csvs
-rw-r--r--  1 snipeit  snipeit      567 Nov 15 20:28 server.php
-rw-r--r--  1 snipeit  snipeit    24622 Nov 15 20:28 snipeit.sh
drwxr-xr-x  8 www-data www-data    4096 Nov 15 20:30 storage
drwxr-xr-x 10 snipeit  snipeit     4096 Nov 15 20:28 tests
-rw-r--r--  1 snipeit  snipeit     2379 Nov 15 20:28 .travis.yml
-rw-r--r--  1 snipeit  snipeit     6083 Nov 15 20:28 upgrade.php
-rw-r--r--  1 snipeit  snipeit     2130 Nov 15 20:28 webpack.mix.js`


All my files (mostly scripts) in /home/tx7 are own by root:root.

**Comment by snipe** [comment]
@pvhkai Did you delete the contents of `bootstrap/cache`?

**Comment by snipe** [comment]
@tx7 Are you trying to run composer as the `snipeit` user? If so, `chown -R snipeit.snipeit /home/tx7/.composer`

**Comment by tx7** [comment]
Yes, but I don't have .composer at my home directory.

**Comment by tx7** [comment]
I just restore my server, and I'm looking at the .composer at the root directory, it doesn't have 'vendor' folder at all.

`~/.composer# ls -la
total 24
drwxr-xr-x 3 root root 4096 Nov 26  2016 .
drwx------ 7 root root 4096 Mar 20  2017 ..
drwxr-xr-x 4 root root 4096 Nov 26  2016 cache
-rw-r--r-- 1 root root   13 Nov 26  2016 .htaccess
-rw-r--r-- 1 root root  799 Sep 24 21:27 keys.dev.pub
-rw-r--r-- 1 root root  799 Sep 24 21:27 keys.tags.pub`

**Comment by snipe** [comment]
Why are these things owned by root? Stuff being owned by root is literally the problem we've been trying to solve this whole time. You shouldn't have had to create a composer directory.

`chown -R snipeit.snipeit /home/tx7/.composer`

If you're running composer install as snipeit:

```
chown -R snipeit.snipeit /home/snipeit/.composer
chown -R snipeit.snipeit /opt/snipe-it
```

Everything should be owned by the user you're running composer as - which should not be root.

**Comment by tx7** [comment]
So I copied the .composer directory from root's home to /home/tx7.
And chown like you showing, but I don't have  `/home/snipeit/.composer`

I'm confused, why we need two .composer directories?

**Comment by snipe** [comment]
STOP copying composer directories. Composer handles that, and I don't know what weird stuff will happen if you copy those directories. 

We do not need more than one composer directory. I'm trying to figure out where yours lives, so we can get your permissions handled.

```
chown -R snipeit.snipeit /opt/snipe-it
```
than AS `snipeit`, run `composer install --no-dev --prefer-source` from the `/opt/snipe-it`.

And paste the results here.

Do NOTHING as root unless I specifically tell you.

**Comment by tx7** [comment]
You meant run like this: `su -u snipeit -c "composer install --no-dev --prefer-source"` ?

**Comment by snipe** [comment]
> su snipeit -c 'composer.phar install --no-dev --prefer-source'`

When we say composer, we mean "run it however you installed it - either globally (composer blah) or locally (composer.phar blah)"

Remove the `config/aws.php` file if it exists.

**Comment by tx7** [comment]
Same error.
I don't know why this version is difficult to upgrade than the previous versions.

**Comment by tx7** [comment]
Good news, I just re-tried with v4.1.5 and it worked!
Even though I receveid an error: `Cannot create cache directory /home/snipeit/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/snipeit/.composer/cache/files/, or directory is not writable. Proceeding without cache`, but it upgraded from 4.1.3 to 4.1.5.

**Comment by pvhkai** [comment]
Workaround in the update worked perfectly! Thanks a lot! Now on Version 4.1.15

`If you get a composer error about AWS, like PHP Fatal error: Class 'Aws\Laravel\AwsServiceProvider' not found [Symfony\Component\Debug\Exception\FatalErrorException]:

    delete the files (not the directory) in bootstrap/cache
    run composer dump-autoload
    remove config/aws.php if it exists

`

**Comment by snipe** [comment]
@tx7 I don't believe your update proceeded correctly. I think it will work this time, since no composer packages were changed, but this error `Cannot create cache directory /home/snipeit/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache Cannot create cache directory /home/snipeit/.composer/cache/files/, or directory is not writable. Proceeding without cache`

... means that your composer directory permissions are still not writable and that will be a problem for you down the line.

**Comment by tx7** [comment]
I've created a snipeit directory in the root directory  and chowned it as: `snipeit:users`

**Comment by allewell** [comment]
@snipe Coming v3.6 i had to delete aws.php as per your suggestion. Thanks! I was getting the 'Aws\Laravel\AwsServiceProvider' aws.php on line 23 PHP fatal error, so there is some good to come from this madness. 

I then had to go back and re-run the upgrade commands since php commandline silently executed (but was actually crashing lol!!)
