### ISSUE TITLE
User has deleted license associated so cannot delete user

### ISSUE THREAD

**Issue by wvanhiele** [snipe/snipe-it#445]
Running version 1.2. I wanted to delete user but error that 1 license was associated.
I forgot to checkin license and just deleted the license.
Now user still has 1 license associated but cannot checkin because license is deleted.
So cannot delete the user anymore, or the license.
Please help?

**Comment by snipe** [comment]
You may need to manually fix that in the database right now. :( The upcoming 1.2.4 release does a better job of handling that, but it doesn't go back in time and fix previously deleted users/licenses.
