### ISSUE TITLE
Issue upgrading - probably my fault

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#4453]
Per our discussion @snipe I ran through the process you found

Below is the output from ssh.

Snipe-IT version v4.1.3 build 94 (gb6a14d2)

```
cd /var/www/html/snipeit

chmod -R 777 vendor

php artisan serve

ctrl + c

php upgrade.php install

Welcome to the Snipe-IT upgrader.

Please note that this script will not download the latest Snipe-IT
files for you unless you have git installed.
It simply runs the standard composer and artisan
commands needed to finalize the upgrade after

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! If you have any encrypted custom fields, BE SURE TO run the recrypter.
!! See the Snipe-IT documentation for help:
!! https://snipe-it.readme.io/docs/upgrading-to-v4
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--------------------------------------------------------
STEP 1: Backing up database:
--------------------------------------------------------

-- Starting backup...
Dumping database snipeit...
Backup failed because The dump process failed with exitcode 1 : General error : sh: /var/www/html/snipeit/storage/laravel-backups/temp//snipeit.sql: Permission denied
.
Backup failed because: The stream or file "/var/www/html/snipeit/storage/logs/laravel-2017-11-15.log" could not be opened: failed to open stream: Permission denied.


  [UnexpectedValueException]
  The stream or file "/var/www/html/snipeit/storage/logs/laravel-2017-11-15.log" could not be opened: failed to op
  en stream: Permission denied




--------------------------------------------------------
STEP 2: Putting application into maintenance mode:
--------------------------------------------------------

--

  [UnexpectedValueException]
  The stream or file "/var/www/html/snipeit/storage/logs/laravel-2017-11-15.log" could not be opened: failed to op
  en stream: Permission denied




--------------------------------------------------------
STEP 3: Pulling latest from Git (install branch):
--------------------------------------------------------

Git is installed.
fatal: Unable to create '/var/www/html/snipeit/.git/index.lock': Permission denied
fatal: Unable to create '/var/www/html/snipeit/.git/index.lock': Permission denied
Cannot save the current index state
error: cannot open .git/FETCH_HEAD: Permission denied

-- -- -- --------------------------------------------------------
Step 4: Cleaning up old cached files:
--------------------------------------------------------

-- No bootstrap/cache/compiled.php, so nothing to delete.
-- Deleting bootstrap/cache/services.php. It it no longer used.
-- Deleting bootstrap/cache/config.php. It it no longer used.
-- Configuration cache cleared!
-- Cache cleared successfully.
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
Step 5: Updating composer dependencies:
(This may take an moment.)
--------------------------------------------------------

-- Local composer.phar detected, so we'll use that.

Generating optimized autoload files
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 23 installs, 5 updates, 0 removals
  - Updating aws/aws-sdk-php (3.38.1 => 3.36.32):     The package has modified files:
    M .changes/3.22.10
    M .changes/3.22.11
    M .changes/3.22.9
    M .changes/3.23.0
    M .changes/3.23.2
    M .changes/3.23.3
    M .changes/3.24.0
    M .changes/3.24.1
    M .changes/3.24.2
    M .changes/3.24.3
    1926 more files modified, choose "v" to view the full list
    Discard changes [y,n,v,d,s,?]? y
 Checking out 7ba49dbd24
  - Updating mtdowling/cron-expression (v1.2.1 => v1.2.0):     The package has modified files:
    M .editorconfig
    M .gitattributes
    M .gitignore
    M .php_cs
    M .styleci.yml
    M .travis.yml
    M CHANGELOG.md
    M LICENSE
    M README.md
    M composer.json
    20 more files modified, choose "v" to view the full list
    Discard changes [y,n,v,d,s,?]? y
 Checking out 9504fa9ea6
  - Updating nikic/php-parser (v3.1.2 => v3.1.1):     The package has modified files:
    M .gitignore
    M .travis.yml
    M CHANGELOG.md
    M LICENSE
    M README.md
    M UPGRADE-1.0.md
    M UPGRADE-2.0.md
    M UPGRADE-3.0.md
    M composer.json
    M doc/0_Introduction.markdown
    420 more files modified, choose "v" to view the full list
    Discard changes [y,n,v,d,s,?]? y
 Checking out a1e8e1a30e
  - Updating psy/psysh (v0.8.14 => v0.8.13):     The package has modified files:
    M .editorconfig
    M .gitignore
    M .phan/config.php
    M .php_cs
    M .styleci.yml
    M .travis.yml
    M CONTRIBUTING.md
    M LICENSE
    M README.md
    M composer.json
    197 more files modified, choose "v" to view the full list
    Discard changes [y,n,v,d,s,?]? y
 Checking out cdb5593c36
  - Updating watson/validating (3.1.2 => 3.1.1):     The package has modified files:
    M .editorconfig
    M .gitattributes
    M .gitignore
    M .travis.yml
    M LICENSE.txt
    M README.md
    M composer.json
    M phpunit.xml
    M src/Injectors/UniqueInjector.php
    M src/Injectors/UniqueWithInjector.php
    11 more files modified, choose "v" to view the full list
    Discard changes [y,n,v,d,s,?]? y
 Checking out ade13078bf
  - Installing symfony/yaml (v3.3.10): Cloning 8c7bf1e7d5
  - Installing symfony/dom-crawler (v3.1.10): Cloning 7eede2a901
  - Installing symfony/browser-kit (v3.3.10): Cloning 317d5bdf01
  - Installing stecman/symfony-console-completion (0.7.0): Cloning 5461d43e53
  - Installing phpunit/php-text-template (1.2.1): Cloning 31f8b717e5
  - Installing phpunit/phpunit-mock-objects (3.4.4): Cloning a23b761686
  - Installing sebastian/version (2.0.1): Cloning 99732be0dd
  - Installing sebastian/resource-operations (1.0.0): Cloning ce990bb217
  - Installing sebastian/object-enumerator (2.0.1): Cloning 1311872ac8
  - Installing sebastian/global-state (1.1.1): Cloning bc37d50fea
  - Installing sebastian/environment (2.0.0): Cloning 5795ffe5dc
  - Installing phpunit/php-timer (1.0.9): Cloning 3dcf38ca72
  - Installing phpunit/php-file-iterator (1.4.2): Cloning 3cc8f69b30
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Cloning 4419fcdb5e
  - Installing phpunit/php-token-stream (1.4.11): Cloning e03f8f6753
  - Installing phpunit/php-code-coverage (4.0.8): Cloning ef7b2f5681
  - Installing myclabs/deep-copy (1.7.0): Cloning 3b8a3a99ba
  - Installing phpunit/phpunit (5.7.23): Cloning 78532d5269
  - Installing facebook/webdriver (1.4.1): Cloning eadb0b7a7c
  - Installing behat/gherkin (v4.4.5): Cloning 5c14cff4f9
  - Installing codeception/codeception (2.3.6): Cloning c3dd3b5d9e
  - Installing fzaninotto/faker (v1.7.1): Cloning d3ed4cc370
  - Installing squizlabs/php_codesniffer (3.1.1): Cloning d667e245d5
phpunit/phpunit-mock-objects suggests installing ext-soap (*)
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (^2.5.1)
phpunit/phpunit suggests installing ext-xdebug (*)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
codeception/codeception suggests installing codeception/specify (BDD-style code blocks)
codeception/codeception suggests installing codeception/verify (BDD-style assertions)
codeception/codeception suggests installing flow/jsonpath (For using JSONPath in REST module)
codeception/codeception suggests installing league/factory-muffin (For DataFactory module)
codeception/codeception suggests installing league/factory-muffin-faker (For Faker support in DataFactory module)
codeception/codeception suggests installing symfony/phpunit-bridge (For phpunit-bridge support)
Generating optimized autoload files




--------------------------------------------------------
Step 6: Migrating database:
--------------------------------------------------------

-- Nothing to migrate.


--------------------------------------------------------
Step 7: Checking for OAuth keys:
--------------------------------------------------------

- OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 8: Caching routes and config:
--------------------------------------------------------

-- Configuration cache cleared!


  [UnexpectedValueException]
  The stream or file "/var/www/html/snipeit/storage/logs/laravel-2017-11-15.log" could not be opened: failed to op
  en stream: Permission denied


-- Route cache cleared!


  [UnexpectedValueException]
  The stream or file "/var/www/html/snipeit/storage/logs/laravel-2017-11-15.log" could not be opened: failed to op
  en stream: Permission denied



--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is now live.


--------------------------------------------------------
FINISHED! Clear your browser cookies and re-login to use :
your upgraded Snipe-IT.
--------------------------------------------------------


```

**Comment by Jarli01** [comment]
After running the upgrade, there is no change in the version run. 

If I perform a `sudo git pull` I get a lot of changes, but I end up with a "whoops" page. 

Looking for advice to remedy this.

**Comment by snipe** [comment]
```
Backup failed because The dump process failed with exitcode 1 : General error : sh: /var/www/html/snipeit/storage/laravel-backups/temp//snipeit.sql: Permission denied
```
and 

```
[UnexpectedValueException]
  The stream or file "/var/www/html/snipeit/storage/logs/laravel-2017-11-15.log" could not be opened: failed to op
  en stream: Permission denied
```

Looks like bad permissions on your logs directory. Try changing `APP_LOG=single` in your .env and double-check that `storage` and all subdirectories are writable by the user you're logged into the command line as.

**Comment by Jarli01** [comment]
I've added the APP_LOG=single into my .env file as it didn't exist and then I've added my user to the apache group. 

The permissions on the storage folder are now

`snipeit storage]$ ls -la
total 12
drwxr-xr-x.  8 apache apache  157 Oct  2 13:32 .
drwxr-xr-x. 17 apache apache 4096 Nov 16 08:15 ..
drwxr-xr-x.  3 apache apache   39 Jul 17 11:19 app
drwxr-xr-x.  2 apache apache   24 Jul 17 11:19 debugbar
drwxr-xr-x.  5 apache apache   66 Jul 17 11:19 framework
drwxr-xr-x.  3 apache apache   18 Nov 13 09:46 laravel-backups
drwxr-xr-x.  2 apache apache   73 Nov 15 08:55 logs
-rw-r--r--.  1 apache apache 3292 Oct  2 13:32 oauth-private.key
-rw-------.  1 apache apache  812 Oct  2 13:32 oauth-public.key
drwxr-xr-x.  8 apache apache  101 May  9  2017 private_uploads
`

With my user account being apart of the apache group. 

Will test momentarily.

**Comment by Jarli01** [comment]
I'm still getting permission denied even though I'm a part of the apache group, which owns the storage folder and everything else under it.

**Comment by Jarli01** [comment]
Ok so it appears to be resolved (as I'm on gba38b84) when I run `sudo -u apache php upgrade.php install
`

I still get some permission issues near the top about the logs.

**Comment by Jarli01** [comment]
Just realized the proper command is `sudo -u apache php upgrade.php`

Below is the output after getting that permission issue resolved. 

`snipeit snipeit]$ sudo -u apache php upgrade.php
PHP Notice:  Undefined offset: 1 in /var/www/html/snipeit/upgrade.php on line 16
Welcome to the Snipe-IT upgrader.

Please note that this script will not download the latest Snipe-IT
files for you unless you have git installed.
It simply runs the standard composer and artisan
commands needed to finalize the upgrade after

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! If you have any encrypted custom fields, BE SURE TO run the recrypter.
!! See the Snipe-IT documentation for help:
!! https://snipe-it.readme.io/docs/upgrading-to-v4
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--------------------------------------------------------
STEP 1: Backing up database:
--------------------------------------------------------

-- Starting backup...
Dumping database snipeit...
Backup failed because The dump process failed with exitcode 1 : General error : sh: /var/www/html/snipeit/storage/laravel-backups/temp//snipeit.sql: Permission denied
.
Backup completed!


--------------------------------------------------------
STEP 2: Putting application into maintenance mode:
--------------------------------------------------------

-- Application is now in maintenance mode.


--------------------------------------------------------
STEP 3: Pulling latest from Git (master branch):
--------------------------------------------------------

Git is installed.
Already on 'master'
-- No local changes to save
-- -- Already up-to-date.
--------------------------------------------------------
Step 4: Cleaning up old cached files:
--------------------------------------------------------

-- No bootstrap/cache/compiled.php, so nothing to delete.
-- Deleting bootstrap/cache/services.php. It it no longer used.
-- Deleting bootstrap/cache/config.php. It it no longer used.
-- Configuration cache cleared!
-- Cache cleared successfully.
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
Step 5: Updating composer dependencies:
(This may take an moment.)
--------------------------------------------------------

-- Local composer.phar detected, so we'll use that.

Cannot create cache directory /usr/share/httpd/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /usr/share/httpd/.composer/cache/files/, or directory is not writable. Proceeding without cache
Generating optimized autoload files
Cannot create cache directory /usr/share/httpd/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /usr/share/httpd/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 0 installs, 0 updates, 23 removals
  - Removing squizlabs/php_codesniffer (3.1.1)


  [RuntimeException]
  Could not delete /var/www/html/snipeit/vendor/squizlabs/php_codesniffer/.git/refs/heads/master: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setti
  ng or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set
   date.timezone to select your timezone.


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...





--------------------------------------------------------
Step 6: Migrating database:
--------------------------------------------------------

-- Nothing to migrate.


--------------------------------------------------------
Step 7: Checking for OAuth keys:
--------------------------------------------------------

- OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 8: Caching routes and config:
--------------------------------------------------------

-- Configuration cache cleared!
Configuration cached successfully!
-- Route cache cleared!
Routes cached successfully!

--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is now live.


--------------------------------------------------------
FINISHED! Clear your browser cookies and re-login to use :
your upgraded Snipe-IT.
--------------------------------------------------------

`

**Comment by snipe** [comment]
Looks like you have some permissions issues there though. 

> Backup failed because The dump process failed with exitcode 1 : General error : sh: /var/www/html/snipeit/storage/laravel-backups/temp//snipeit.sql: Permission denied
> Cannot create cache directory /usr/share/httpd/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache

Additionally, you should set your timezone in your php.ini.

> Could not delete /var/www/html/snipeit/vendor/squizlabs/php_codesniffer/.git/refs/heads/master: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are required to use the date.timezone setting or the date_default_timezone_set() function

(That's a PHP error, not a Snipe-IT error.)

**Comment by Jarli01** [comment]
Sorry can you help me to explain where I should make these changes? My user account has access to apache group, which owns storage (and so I should have access as well). 

As for the timezone, I should be able to look that up

**Comment by Jarli01** [comment]
Apache own's `drwxr-xr-x. 2 apache apache  6 Nov 16 09:44 https---packagist.org`

(my user account is a part of that group). So not sure what else is wrong there. 

As for the default time zone my .env file has 

```
#Created By Snipe-it Installer
APP_TIMEZONE=America/New_York
```
Is there something else I'm missing here?
