### ISSUE TITLE
QR Codes are not Generating

### ISSUE THREAD

**Issue by JayRad11** [snipe/snipe-it#4454]
#### Expected Behavior (or desired behavior if a feature request)

Assets have been loaded into the database and QR generation has been enabled in the admin panel.

-----

#### Actual Behavior

QR codes do not appear under any of the asset's details; instead I only see a broken link picture. (as shown below)

![error](https://user-images.githubusercontent.com/33159919/32840932-0f89b04e-c9e7-11e7-925a-1c9bdb2af764.PNG)

APP_URL is set to **http://mywebsite**

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

Is this a fresh install or an upgrade?
**Fresh**
Version of Snipe-IT you're running
**snipe-it-4.0.10**
Version of PHP you're running
**php 7.1.9**
Version of MySQL/MariaDB you're running
**5.7.19**
What OS and web server you're running Snipe-IT on
**Windows Server 2012 / WAMP**
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
**Manual Installation**
WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
If a stacktrace is provided in the error, include that too.
Any errors that appear in your browser's error console.
Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
Include any additional information you can find in app/storage/logs and your webserver's logs.
Include what you've done so far in the installation, and if you got any error messages along the way.
Indicate whether or not you've manually edited any data directly in the database
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
> Include any additional information you can find in app/storage/logs and your webserver's logs.

**Comment by JayRad11** [comment]
WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
**I do not see an error in the debug.**

What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
**Asset Details**

If a stacktrace is provided in the error, include that too.
**None**

Any errors that appear in your browser's error console.
**When I inspect broken QR element, this is what it drills down too. It looks to be defaulting to port 80, and our Snipe-it runs on a separate 8000 port. 
<img src="http://myserver/hardware/78/qr_code" class="img-thumbnail pull-right" style="height: 100px; width: 100px; margin-right: 10px;">**

Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
**Cannot reproduce in the demo.**

Include any additional information you can find in app/storage/logs and your webserver's logs.
**Couldn't seem to find an error related to QR other than in the browser image element.**

Include what you've done so far in the installation, and if you got any error messages along the way.
**Populated Assets and just the other day upgraded to 4.1.4 via manual update.**

Indicate whether or not you've manually edited any data directly in the database
**I have not.**

**Comment by snipe** [comment]
What is your APP_URL in your .env?

**Comment by JayRad11** [comment]
It is "http://myserver"

Port number required?

**Comment by snipe** [comment]
The APP_URL must match your URL exactly.

**Comment by JayRad11** [comment]
Dammit @snipe , you and that big sexy brain of yours! XD

Worked like a charm. I thought everything was okay in the ENV considering our images of assets pulled okay.
Thank you so much 👍

**Comment by Grimmbly** [comment]
I also had this issue. This fixed the issue for me as well. my APP_URL was my IP address. I had to but http:// in front of it to work. Thank you @snipe

**Comment by Raffudeen** [comment]
I have the same issue i have tried changing the APP_URL but still its generating QR Codes. Please advise
