### ISSUE TITLE
Type any query into Asset Search Bar; Returns All Assets

### ISSUE THREAD

**Issue by JayRad11** [snipe/snipe-it#4455]
#### Expected Behavior (or desired behavior if a feature request)

I would like to use the Asset quick search bar to type in a name, location, model etc (anything) and have it return all relevant information to the query string. 

-----

#### Actual Behavior

I can type in "Supercalifragilisticexpialidocious" and the query will return a list of all assets in my database. When I was first building the asset database, I remember this quick search bar running queries accurately. If I typed in "Nancy", I had a list of all assets assigned to Nancy. Somewhere along the way something has stopped this search box?

I understand that there is the advanced search tool; but if I could get the quick search running as it was and eliminate the need for extra clicks, it makes a world the difference over the course of a day.

![error2](https://user-images.githubusercontent.com/33159919/32842673-ac688b84-c9eb-11e7-8ada-a5646d0765de.PNG)

Cheers

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

Is this a fresh install or an upgrade?
**Fresh**
Version of Snipe-IT you're running
**snipe-it-4.0.10**
Version of PHP you're running
**php 7.1.9**
Version of MySQL/MariaDB you're running
**5.7.19**
What OS and web server you're running Snipe-IT on
**Windows Server 2012 / WAMP**
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
**Manual Installation**
WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
If a stacktrace is provided in the error, include that too.
Any errors that appear in your browser's error console.
Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
Include any additional information you can find in app/storage/logs and your webserver's logs.
Include what you've done so far in the installation, and if you got any error messages along the way.
Indicate whether or not you've manually edited any data directly in the database
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by JayRad11** [comment]
@snipe 

If you're getting an error in your browser, include that error
**None**
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
**No Error Produced; Search Simply does not return correct Results**
If a stacktrace is provided in the error, include that too.
**None**
Any errors that appear in your browser's error console.
**Located in "Exceptions"**
[Exceptions Error Connection.php#647.txt](https://github.com/snipe/snipe-it/files/1476421/Exceptions.Error.Connection.php.647.txt)
Confirm whether the error is reproduceable on the demo.
**I able to search all individual fields successfully in the online demo. (Notes, Assets, Users, etc)**
Include any additional information you can find in app/storage/logs and your webserver's logs.
**None**
Include what you've done so far in the installation, and if you got any error messages along the way.
**So far I have only added assets to the database and have been populating all relevant fields. (Adding Models, Pictures, Owners, Locations, etc)**

**Comment by snipe** [comment]
I believe this had already been fixed in the latest version.
