### ISSUE TITLE
Start app with PHP embedded |  built-in server

### ISSUE THREAD

**Issue by pedrommuller** [snipe/snipe-it#4456]
I'd like to run the app using the embedded |  built-in  server that comes with PHP
when I do 
`php -S localhost:8000 `
on the public directory, I'm able to run the app, but I'm always getting a server error and sometimes I get

> Invalid request (Unexpected EOF)

I know this could be related to the web server and not the app, but have anybody tried to run the app in this way?

Any direction will be appreciated,
thanks.

for reference:
http://php.net/manual/en/features.commandline.webserver.php

**Comment by snipe** [comment]
We don't really support or test using PHP's built in server, as it's not intended for production use and is meant for development only. You can try `php artisan serve` (which is Laravel's built in web server), but we don't support that in any official capacity either.

**Comment by GeoffYoung** [comment]
You can specify a document root with the `-t` flag if you really want to by running `php -S localhost:8000 -t public`, but I was under the impression that's what `php artisan serve` is an alias for.
