### ISSUE TITLE
branding settings in Admin

### ISSUE THREAD

**Issue by arsenal818** [snipe/snipe-it#4461]
Hi, I'm unable to change Site Name in the app settings section. After typing a new name and clicking save, I get red error bar on tap with "Error:Please check the form below for errors."  
However, there are no errors displaying and the branding name will not change. I'm also not able to upload logo. The file gets uploaded but not able to save the settings. I get the same error. The other issue (similar) i can't change password minimum characters settings. I get the same error as above. 

thank you for support. 
-----
#### Provide answers to these questions:

- This is a fresh install on Mac OSx
- Version 4.1.3
-

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Please enabled debug and check the Request > session_attributes section to see if there is anything in the error message bag.

**Comment by arsenal818** [comment]
hi, debug is turned on. However, not sure where the log files are saved. Sorry, I'm new to snipeit. 
forgot to add that i'm using ampps as my dev webhost.

**Comment by snipe** [comment]
>However, not sure where the log files are saved

https://snipe-it.readme.io/v4.0/docs/getting-help#section-step-3-check-your-app-and-server-logs

That said, I'm not asking for log files, I'm asking you to check the debugbar at the bottom of the screen. There are multiple tabs - one of which is Request (looks like a tag, for some reason).

<img width="674" alt="update_branding_settings____snipe-it_demo" src="https://user-images.githubusercontent.com/197404/32864939-e3185b6c-ca15-11e7-9e15-81e2811edf07.png">

**Comment by arsenal818** [comment]
I have the "app_debug=ture" but I don't get that section below the page load. Are those tabs included in the app or I have to open up browser developer tools to see it?

**Comment by snipe** [comment]
> I have the "app_debug=ture"

Hopefully you mean `true`. Try setting the APP_ENV to `develop` and [clearing your config cache](https://snipe-it.readme.io/v4.0/docs/clearing-the-config-cache).

**Comment by arsenal818** [comment]
Hi again, thanks for all your assistance. 

I'm still stuck in the enabling debug mode. I have been making changes in the docker.env file trying to turn "app_debug=true" and it appears what ever changes I make to that file it is not effecting the application. Is there another .env file that I need to edit?

**Comment by arsenal818** [comment]
disregard  my previews post. Apparently on apple OS .env file was hidden. Now i'm able to enable debug mode.

**Comment by arsenal818** [comment]
Here is what the error message bag had:

![debug-report](https://user-images.githubusercontent.com/29581178/32922143-a6e12e46-cae5-11e7-867b-3adf32b35eec.PNG)

**Comment by snipe** [comment]
Thanks, that's both helpful and unhelpful at the same time. It's catching on the validation for the `alert_email` field but that field isn't on that page - and it's nullable. :-/ 

How did you install this? - manual or git pull?

I don't see anything in the code that would be triggering this error.

**Comment by arsenal818** [comment]
I used this http://www.ampps.com/apps/projectman/Snipe-IT   it installed the localhost web server and added Snipe-it

**Comment by arsenal818** [comment]
just an FYI I can't make any changes in the Admin config page of the app. Branding, general settings, security, localization... I get the same error.   At first I was thinking it might be permissions are not set correctly. What do you think?

**Comment by snipe** [comment]
I'm wondering if Softaculous botched something in the v4.1.3 packaging. Does Softaculous allow you to upgrade using their tools or is it install only?

**Comment by arsenal818** [comment]
No, I think I can update manually. Don't have to use their tool.

**Comment by snipe** [comment]
If they offer an update, go ahead and update it. We're on 4.1.4 now, an I see that's available. Just to rule anything weird out.

**Comment by arsenal818** [comment]
will do, thank you very much. Will get back to you tomorrow with any status.

**Comment by arsenal818** [comment]
Hi, just wanted to give you an update. I was able to figure out what the error was happening. 
I did update to 4.1.4 and the issue was still there. Then looking at the bug report, like you mentioned that it was referencing an email notification. So in the Admin System settings I had the email alerts enabled and send alerts to email address (i had it set to admin@127.0.0.1)  I took the email address out and unchecked the alert option.  That fixed it. 

Hope this helps.

**Comment by snipe** [comment]
I still don’t really understand why you’d be seeing that though. I can’t reproduce it at all. 🧐

**Comment by closterfield** [comment]
i am totally confused do we have to import just the data of the database or the sql .... ???
I am getting error in just Updating the Brand Settings after migrating to new server .... Error says whops cant find

**Comment by closterfield** [comment]
after importing the database

**Comment by closterfield** [comment]
in sql

**Comment by closterfield** [comment]
everything is working out but just the branding, says Whoops, looks like something went wrong.
