### ISSUE TITLE
Error LDAP User Sync

### ISSUE THREAD

**Issue by leethanh2112** [snipe/snipe-it#4462]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

Hello everybody

I have a issue when i run "LDAP User SYNC"
![image](https://user-images.githubusercontent.com/33690376/32874000-0201d0b0-cac2-11e7-9fcb-0c9fd8ff51b2.png)

I configured LDAP Settings successfull and test connect OK.

![image](https://user-images.githubusercontent.com/33690376/32874031-2f07a6de-cac2-11e7-91d6-c35922b61cdc.png)

Help me!! Sorry for my English.

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by Gelob** [comment]
@leethanh2112 I've found out that test LDAP sync and and test ldap login doesn't test the LDAP Filter field on the LDAP settings page. I would verify you have a valid filter. Snipe-it automatically prefixes and appends parentheses to your query.

If you run `php artisan snipeit:ldap-sync --summary` from command line you should see an error if its wrong.

More so if your wondering if its a syntax problem that snipe-it doesn't like because of the above parentheses issues you can test this on linux using the following command:

ldapsearch -x -H 'ldap://yourldapserverhere' -D "LDAP Bind Username goes here" -w 'yourbindpassword' -b yourbaseDNgoeshere "yourldapsearchfiltergoeshere"
