### ISSUE TITLE
Feature request: Management of inactive users

### ISSUE THREAD

**Issue by gt-nyc** [snipe/snipe-it#4463]
#### Expected Behavior (or desired behavior if a feature request)
* when viewing a user, we should see its status (user.activated) so that we can make sure no asset are still assigned to the person
* if a user is deactivated, we should not be able to assign anything
* A report listing assets that are still assigned to inactive users
 
#### Actual Behavior
* when opening the user view, there is no info about user status.
* User status can only prevent from logging in but we cannot use it to stop assigning assets to the user.
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Inactive users are still valid users - they just cannot login.

**Comment by gt-nyc** [comment]
so how do we mark a user as "departed"?

**Comment by snipe** [comment]
You can delete them. You won't lose any if their history unless you purge them.
