### ISSUE TITLE
Image "breaks" dropdown if the image doesn't match max thumbnail height

### ISSUE THREAD

**Issue by tomasaberg** [snipe/snipe-it#4466]
#### Expected Behavior (or desired behavior if a feature request)

When creating a new asset, if a image is associated with a model and the image height is lower than what max thumbnail height is set to, the _width_ of the image should still be scaled to fit in the dropdown menu.

-----

#### Actual Behavior

![snipeit-sort](https://user-images.githubusercontent.com/5165061/32885152-ecff3aae-cabc-11e7-9ed1-ed996ce69746.png)

Here's the image that cause the issue
![netapp-solidfire-sf](https://user-images.githubusercontent.com/5165061/32885086-c219cc96-cabc-11e7-8c55-5b5a06c969ea.png)

Since the Max thumbnail height is set to 50px and this image hight is lower than that, this image isn't resized to match the other images. 

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade
- Version of Snipe-IT you're running 
4.1.4
- Version of PHP you're running 
7
- Version of MySQL/MariaDB you're running 
5.6
- What OS and web server you're running Snipe-IT on 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
/hardware/create
- If a stacktrace is provided in the error, include that too.
N/A
- Any errors that appear in your browser's error console.
N/A
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
Yes
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
N/A

- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I'm not really sure what the solve here is, though. If we scale that image by width as well, it will be so small you won't be able to see it.

**Comment by snipe** [comment]
(Also that doesn't really look broken, it just looks odd.)

**Comment by tomasaberg** [comment]
You're right! I guess this isn't the normal proportions of an image.
Is there a way to add transparent "whitespace" to force an image to appear as a square?

Something like this?
http://image.intervention.io/api/fit

(Not an expert on this kind of things :) )
