### ISSUE TITLE
Page models : click on Fieldset = broken link

### ISSUE THREAD

**Issue by glureau** [snipe/snipe-it#4469]
#### Expected Behavior (or desired behavior if a feature request)
Go on the asset models page, and click on the fieldset link of an entry: it should open the selected fieldset.

-----

#### Actual Behavior
Open /fieldsets/3 instead of /fields/fieldsets/3, leading to a **404 Page not found.**

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install
- Version of Snipe-IT you're running
v4.1.3 build 48 (g74aa562)

Unfortunately I cannot give much more information as the sysadmin is in vacation, but it looks a straightforward issue so I hope easily fixable.

**Comment by snazy2000** [comment]
I have also noticed this issue today
