### ISSUE TITLE
Import CSV assets - Model duplicated

### ISSUE THREAD

**Issue by glureau** [snipe/snipe-it#4475]
#### Expected Behavior (or desired behavior if a feature request)

Added custom fields on the assets, import via the UI, map manually the columns with the custom fields.
I expect to have values in these fields.

-----

#### Actual Behavior

Fields remains empty after the import (no error in the UI).

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install
- Version of Snipe-IT you're running
v4.1.3 build 48 (g74aa562)
- Version of PHP you're running
5.6.30-0+deb8u1
- Version of MySQL/MariaDB you're running
10.0.32-MariaDB-0+deb8u1
- What OS and web server you're running Snipe-IT on
Debian GNU/Linux 8 (jessie)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
http://inventaire.dronisos.com/import
- If a stacktrace is provided in the error, include that too.
No
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by glureau** [comment]
Well... actually the fields exist, but they're not visible in UI because the asset model is duplicated (even if all fields are the same).
I suspect it could be ok if I used the Model ID instead of the Model name (+ Manufacturer).

Workaround (for future users with a similar issue):
- go in Settings > Asset Models
- select the new asset model created during the import and set the Fieldset you want to
(- remove the previous asset model if not used anymore)

Not sure if you want to change this ticket to avoid duplicated asset model or if it's ok for you (didn't read all the documentation, not sure if it was mentioned somewhere), anyway I'm ok to close this ticket.

Good work!

**Comment by snipe** [comment]
@dmeltzer can you take a look at this?
