### ISSUE TITLE
Password reset email link shows IP address twice

### ISSUE THREAD

**Issue by vizax** [snipe/snipe-it#4478]
#### Expected Behavior (or desired behavior if a feature request)

Click link from Password reset email, open web page to reset password.

-----

#### Actual Behavior

404 error. The IP address is listed twice in the URL, both for the button and for the 'trouble link' below.

Truncated screenshot of trouble link for ref.
![image](https://user-images.githubusercontent.com/1894549/32953808-f9b34f78-cb76-11e7-8253-e37146e7cd39.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? fresh
- Version of Snipe-IT you're running:  v4.1.4 build 173 (gba38b84)
- Version of PHP you're running: 7.0.21
- Version of MySQL/MariaDB you're running: 10.0.14
- What OS and web server you're running Snipe-IT on: Win Server 2012 R2, IIS 8.5.9600.16384
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Password reset email
- If a stacktrace is provided in the error, include that too.: N/A
- Any errors that appear in your browser's error console.: N/A
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. : it does not happen on the demo site
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.: N/A
- Include what you've done so far in the installation, and if you got any error messages along the way.: N/A
- Indicate whether or not you've manually edited any data directly in the database:  No manual editing

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
What do you have set as your APP_URL in your env?

**Comment by vizax** [comment]
just the IP address.

**Comment by vizax** [comment]
Just the ip. No "http://".

**Comment by vizax** [comment]
Aaaaaand that answers my problem. I didn't read close enough. Config page says to use http....  Sigh, my apologies for not reading closely enough.

**Comment by snipe** [comment]
It happens. Glad you got it sorted. :)

![prismo-jake](https://user-images.githubusercontent.com/197404/33093054-c26115e0-ceb0-11e7-85fa-a4b22196054b.gif)

(Also please try to remember to close issues if they've been resolved - thanks!)

**Comment by vizax** [comment]
Yup, sorry was scrambling out the door. Will keep in mind for the future.
