### ISSUE TITLE
Shyam 

### ISSUE THREAD

**Issue by 5hyam** [snipe/snipe-it#448]
HI 
am getting the below error when am trying the below - 

Open C:\inetpub\wwwroot\snipe-it in Windows Explorer

    Right Click and select Composer Install. This will install the dependencies. Once completed move to next step
    Right Click and select Use Composer here
    Type php artisan app:install and follow the prompts

==============================================================
C:\inetpub\wwwroot\snipit>php artisan app:install
PHP Warning:  require(C:\inetpub\wwwroot\snipit\bootstrap/../vendor/autoload.php
): failed to open stream: No such file or directory in C:\inetpub\wwwroot\snipit
\bootstrap\autoload.php on line 17

Warning: require(C:\inetpub\wwwroot\snipit\bootstrap/../vendor/autoload.php): fa
iled to open stream: No such file or directory in C:\inetpub\wwwroot\snipit\boot
strap\autoload.php on line 17
PHP Fatal error:  require(): Failed opening required 'C:\inetpub\wwwroot\snipit\
bootstrap/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:\inetpub\w
wwroot\snipit\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\inetpub\wwwroot\snipit\boots
trap/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:\inetpub\wwwroo
t\snipit\bootstrap\autoload.php on line 17

C:\inetpub\wwwroot\snipit>

**Comment by snipe** [comment]
Did you actually install composer first, per the directions?
