### ISSUE TITLE
FatalErrorException on Install

### ISSUE THREAD

**Issue by nslatter-hmh** [snipe/snipe-it#4481]
#### Expected Behavior (or desired behavior if a feature request)

Installation completion.

-----

#### Actual Behavior

After clicking "Create Database Tables" on preflight page, I get the "Whoops" screen.

-----

#### Please confirm you have done the following before posting your bug report:

- [ x ] I have enabled debug mode 
- [ x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh
- Version of Snipe-IT you're running
4.1.4
- Version of PHP you're running
5.6 (but I've also attempted the install with 7.0)
- Version of MySQL/MariaDB you're running
10.0.31
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04 / Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Git Clone
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
(1/1) FatalErrorExceptionCall to undefined function Patchwork\utf8_encode()
in Utf8.php (line 704)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
./setup/migrate?
- If a stacktrace is provided in the error, include that too.
[2017-11-17 21:56:36] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function Patchwork\utf8_encode()' in /var/www/html/vendor/patchwork/utf8/src/Patchwork/Utf8.php:704
- Any errors that appear in your browser's error console.
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function Patchwork\utf8_encode()' in /var/www/html/vendor/patchwork/utf8/src/Patchwork/Utf8.php:704
- Include what you've done so far in the installation, and if you got any error messages along the way.
I've completed all steps.
- Indicate whether or not you've manually edited any data directly in the database
I have not.
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Please make sure you have the php-xml and mbstring extensions installed and enabled.

**Comment by nslatter-hmh** [comment]
That did it.  Thanks!

**Comment by nguyennv94** [comment]
hi, i'm installed php-xml and mbstring but not run
