### ISSUE TITLE
Asset bulk edit function does not update location

### ISSUE THREAD

**Issue by niallmooney** [snipe/snipe-it#4482]
#### Expected Behavior (or desired behavior if a feature request)

When setting a location in the location field on the bulk asset edit page expect for the location to be updated.

-----

#### Actual Behavior

When setting updated location and selecting save the following message displays and the location of the assets are not updated.

"No fields were selected, so nothing was updated."

Issue occurs in demo install as well.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
Upgrade
- Version of Snipe-IT you're running
4.1.4
- Version of PHP you're running
5.6
- Version of MySQL/MariaDB you're running
MariaDB 10.1
- What OS and web server you're running Snipe-IT on
CentOS 6.8/Apache 2.2.15
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual Install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
https://demo.snipeitapp.com/hardware/bulkedit
- If a stacktrace is provided in the error, include that too.
N/A
- Any errors that appear in your browser's error console.
N/A
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
Yes
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
N/A
- Include what you've done so far in the installation, and if you got any error messages along the way.
N/A
- Indicate whether or not you've manually edited any data directly in the database
N/A

**Comment by snipe** [comment]
I believe this was already fixed in later versions and on master/develop
