### ISSUE TITLE
Assignment fields showing by default

### ISSUE THREAD

**Issue by ericdude101** [snipe/snipe-it#4483]
#### Expected Behavior (or desired behavior if a feature request)

on the new asset creation screen, the "Checkout to" list boxed should only display after a deployable status is selected from the status list box.

-----

#### Actual Behavior

The "checkout to" list boxes are visible upon landing on the create asset screen, they do disappear if you select a non-deployable status.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Upgrade**
- Version of Snipe-IT you're running **4.1.4**
- Version of PHP you're running **7.1.9**
- Version of MySQL/MariaDB you're running **MariaDB 10.2**
- What OS and web server you're running Snipe-IT on **Windows Server 2012 IIS 8.5**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Manual**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **None**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **New Asset Creation Screen**
- If a stacktrace is provided in the error, include that too. **None**
- Any errors that appear in your browser's error console. **None**
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. **Yes it is**
- Indicate whether or not you've manually edited any data directly in the database **No**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
This PR should fix this issue.
https://github.com/snipe/snipe-it/pull/4501

You can also view it on the develop site: https://develop.snipeitapp.com `admin`/`password`

**Comment by snipe** [comment]
Derp. I lied, it's not merged yet. :P You can check it out locally though if you want to pull down the `features/improved_checkout_ui_and_4491_fix` branch :D

**Comment by snipe** [comment]
Now it's merged and on the develop demo. :)
