### ISSUE TITLE
Feature Request - Bulk Checkout/Checkin drop down menu option in assets list

### ISSUE THREAD

**Issue by carlashley** [snipe/snipe-it#4487]
#### Desired Behavior (or desired behavior if a feature request)
The drop down menu at the top of an assets list page should include the options to bulk check-in, and bulk check-out. This will make it easier to select assets that should be checked out/in rather than going through the current bulk check out process via the `Assets > Bulk Checkout` left hand menu pane.

![screen shot 2017-11-20 at 10 02 06 am](https://user-images.githubusercontent.com/9841187/32997307-fa498ab4-cdd9-11e7-9b66-47c2c56088cd.png)

**Comment by MFernAruba** [comment]
+1 for this feature request.  The current workflow for adding multiple assets one-by-one to a bulk checkout is cumbersome and time-consuming.
