### ISSUE TITLE
Test API unauthorized

### ISSUE THREAD

**Issue by giovannifiore85** [snipe/snipe-it#4489]
#### Expected Behavior (or desired behavior if a feature request)

After create API token, I want to use SoapUI to test API system

-----

#### Actual Behavior

Json respond {"error": "Unauthorized."}

-----

#### Please confirm you have done the following before posting your bug report:

- [ x ] I have enabled debug mode 
- [ x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Is an upgrade from 3.6.4 to 4.1.4
- Version of Snipe-IT you're running
4.1.4
- Version of PHP you're running
5.6.32
- Version of MySQL/MariaDB you're running
5.5.52
- What OS and web server you're running Snipe-IT on
Centos 7.2.1511
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
{"error": "Unauthorized."}
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
API request
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
is not possible to test api from https://snipeitapp.com/demo
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
Nothing was edit

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
How are you passing the token?

**Comment by giovannifiore85** [comment]
By GET request with Authorization and Accept headers.
Authorization: username token
Accept: application/json

but now json respond:
{
   "status": "error",
   "messages": "An Error has occured! Unauthenticated.",
   "payload": null
}

I'm trying to list the stored hardware through http://mydomain/api/v1/hardware

**Comment by snipe** [comment]
You need to format the `Authorization` header correctly, using `Bearer YOUR-APP-TOKEN`, [per the documentation](https://snipe-it.readme.io/v4.0/reference#authenticating-with-the-api).
