### ISSUE TITLE
Installed on Windows but no format/design to site

### ISSUE THREAD

**Issue by MrTantrum** [snipe/snipe-it#449]
I just finished the install on a Windows environment, and after overcoming a variety of challenges it now seems to be working with one giant exception - the format of the site.  It is all text based.  What do I need to do to resolve?
![screenshot](https://cloud.githubusercontent.com/assets/8970604/5688285/eef79cca-981a-11e4-9864-0426077faa0a.png)

**Comment by MrTantrum** [comment]
My own fault.  After retracing my install steps, my IIS site was pointing to the snipe-IT folder instead of the snipe-IT\public folder.

**Comment by snipe** [comment]
Glad you got it sorted!
