### ISSUE TITLE
Feature Request - Visibility of assets checked out to another asset

### ISSUE THREAD

**Issue by naphta** [snipe/snipe-it#4490]
#### Desired Behavior

Click on an asset (`www.example.com/hardware/1`)
In the table see a column for assets
See all available

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  N/A
- Version of Snipe-IT you're running v4.1.4
- Version of PHP you're running 7.1
- Version of MySQL/MariaDB you're running MariaDB 10.0
- What OS and web server you're running Snipe-IT on Ubuntu
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual

---

To explain a little bit further we've hit an interesting point when importing data into snipe-it. We have a SAN which will then have individual HDD/SSD assigned to it which each have their own warranties and are semi-regularly moved between other SAN's too. 

A colleague has been creating them as components (as they are indeed a specific component) however it also makes a lot of sense to create them as assets so they have a full audit over lifetime including warranties etc.

The issue is there is no visibility of what assets an asset has checked out you instead would need to investigate each individual (in this case HDD) asset to see where it has been assigned.

**Comment by OprSysAdm** [comment]
I have the same issue. My hard drives are assigned to their respective servers and are themselves individual assets (to have the full audit as above) but when go to the server to look for the assigned hard drive there is no way to see this. We really would love this feature.

**Comment by snipe** [comment]
I believe this change is on master/develop now
