### ISSUE TITLE
Web UI Imports asset CSV, but hangs on processing

### ISSUE THREAD

**Issue by MSTigers** [snipe/snipe-it#4492]
#### Expected Behavior (or desired behavior if a feature request)

Import CSV, process CSV, match fields, import success.

-----

#### Actual Behavior

CSV successfully imports, I process it, and try to import but it sits on "Processing" indefinitely. I have imported, even just a couple hours ago, successfully. Any time there was an error with formatting such as a required field, the browser would show the specific error. 

- Uploads document correctly file appears in `storage/private_uploads/imports`
- Match fields and click PROCESS 
- Hangs with "Processing" no errors

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade. I didn't notice until now, but 3-4 days ago I had ran an update from v4.1.0 to the latest using `php upgrade.php ` everything appeared to be successful at that time. Pulled all of the files, no errors during the upgrade process. However, the version history still indicates it's not the newer version. Browser cache was cleared (tried two different browsers).  **Everything has functioned up until reporting this bug, including importing and processing other CSV files** for a few days after the "upgrade."

Headers of my CSV 

`Item Name | Asset Tag | Category | Manufacturer | Model Name | Model Number | Serial Number | Username | Email`

- Version of Snipe-IT you're running
v4.1.0 build beta2
- Version of PHP you're running
7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running
5.4.29
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04.1  /  Apache2.4.18
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No errors generated with debug mode.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
webpage/import
- If a stacktrace is provided in the error, include that too.
n/a
- Any errors that appear in your browser's error console.
Chrome > Inspect > Console
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
api/v1/imports/process/14 
```
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
n/a
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
Checked the logs, nothing there with today's date.
- Include what you've done so far in the installation, and if you got any error messages along the way.
This morning I was able to successfully import and process two different CSV asset docs.
- Indicate whether or not you've manually edited any data directly in the database
No I have not

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
>  However, the version history still indicates it's not the newer version

Something didn't go right then, as the upgrade.php clears your config cache. When you open `config/version.php` what do you see?

Without a specific error message, this is going to be pretty hard to troubleshoot.

**Comment by MSTigers** [comment]
'app_version' => 'v4.1.0',
  'build_version' => 'beta2',
  'hash_version' => 'g3b498ef',
  'full_hash' => 'v4.1.0-beta2-3-g3b498ef',

**Comment by snipe** [comment]
That's the old version config file, so something didn't get updated.

**Comment by MSTigers** [comment]
I can open a separate bug for that as it's outside the scope of the CSV/import if you would like me to. Whatever you'd prefer.

Just noting that the CSV import was working fine (as is pretty much everything else) even after the botched upgrade, so in my uneducated opinion I don't think they're directly related. I get the feeling I'm screwing up the CSV somehow, but since I can't get any errors I can't troubleshoot it.

I imported a bunch of phones, and imported username email and it successfully assigned those devices to those pre-existing users. Using the same format for these laptops I'm trying to import. It successfully created models (for the phones) even though they didn't exist in Snipe-IT already.

**Comment by MSTigers** [comment]
Wait a sec, I just noticed something. So in the CSV that isn't working, when I import it there's a ton of 'blank' fields. Looking into it now.

![importbug1](https://user-images.githubusercontent.com/33290254/33039624-311b01de-cdfe-11e7-9276-cb64fafaed0b.jpg)

![importbug2](https://user-images.githubusercontent.com/33290254/33039626-32a0adc4-cdfe-11e7-80c9-4042036a1978.jpg)

**Comment by MSTigers** [comment]
I'm using excel to create the CSVs. Everything looks good there. I don't see any blank spots. Opened in notepad.

Item Name,Asset Tag,Category,Manufacturer,Model Name,Model Number,Serial Number,Username,Email
ASSET1,ASSET1,Laptop,HP,HP Laptop Probook,MODELNO123,SN1234,jsmith,jsmith@domain.net

The formatting _appears_ correct.

**Comment by MSTigers** [comment]
Closing this. The issue was somehow related to the CSV creation in excel. If you notice empty fields during the PROCESS stage of importing your assets in Snipe-IT, I would recommend verifying (even if visually you don't see any issues) that your CSV is formatted correctly. It appeared to be correct in both excel view and txt editor view (notepad), however when saved in notepad it reduces any hidden formatting that may cause an issue with Snipe-IT during the import process.
