### ISSUE TITLE
New Setup, Page won't load

### ISSUE THREAD

**Issue by mram2410** [snipe/snipe-it#4493]
#### Expected Behavior (or desired behavior if a feature request)

Pre-Flight and Setup

-----

#### Actual Behavior

.env and IIS have the same URL, test.domain.com. IIS is pointing to the static IP assigned to the server. 

When I browse to the site via hostname, I receive a page stating "Sorry!", and that there is a misconfiguraiton. When I browse to the site via IP, I receive a 404 error. I receive these errors on the local and remote machine. 

-----

#### Please confirm you have done the following before posting your bug report:

- [y ] I have enabled debug mode 
- [ y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? y
- Version of Snipe-IT you're running 4.1.4
- Version of PHP you're running 7.1.11
- Version of MySQL/MariaDB you're running 10.2
- What OS and web server you're running Snipe-IT on Win 2012 R2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
This sounds like a server config issue, not a Snipe-IT issue. Are you using the web.config? I'm not as familiar with IIS, so perhaps one of our IIS community members can be of more help.

**Comment by madd15** [comment]
I have a couple of questions.

- Do you have your physical path set to the public directory?
- Do you have URL rewrite installed?

**Comment by mram2410** [comment]
@snipe No, I didn't touch the web.config. 
@madd15 The default web site is pointing to its default path, wwwroot. The 2nd site I created is pointing to Snipe's public path. URL Rewrite is installed. In the 2nd site, there are 2 imported rules that were created.

**Comment by mram2410** [comment]
Here's a screenshot of the imported rules under the second site. 

![image](https://user-images.githubusercontent.com/33847752/33086519-a71bbe98-ce9c-11e7-8b78-f37e15ecb570.png)

**Comment by madd15** [comment]
are you able to screenshot the error page and show me please?

**Comment by mram2410** [comment]
Sure. Here you go.

![image](https://user-images.githubusercontent.com/33847752/33102478-d8d7b60a-ced1-11e7-8913-20924b680564.png)

**Comment by madd15** [comment]
what do you have in the Bindings for both the default and snipe sites?

**Comment by mram2410** [comment]
Default: Type: http; IP: All Unassigned; Port 8080; Hostname: Blank. I've also disabled this site, and left Snipe enabled. Also tried it with port 80.
Snipe: Type: http; IP: Server's IP; Port 80; Hostname: assets.domain.com (this also matches .env).

**Comment by madd15** [comment]
as you specified a hostname you cant use `localhost` you must use that hostname even on the server

**Comment by mram2410** [comment]
I tried that too, and still receive the error.

**Comment by madd15** [comment]
still a 404 error? general means that is cant find the files double check that the site is pointed at the correct directory

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
