### ISSUE TITLE
Audit

### ISSUE THREAD

**Issue by andrescarrion** [snipe/snipe-it#4494]
#### Expected Behavior (or desired behavior if a feature request)

I'cant change the months for the audit, I need every 6 months

-----

#### Actual Behavior

actually have 12 months

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
This is a upgrade
- Version of Snipe-IT you're running
v4.1.4
- Version of PHP you're running
5.6.24
- Version of MySQL/MariaDB you're running

- What OS and web server you're running Snipe-IT on
IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manually

I tried change the months on \app\Models\Actionlog.php
but it doesn't work.

how can change that ??

**Comment by snipe** [comment]
Please revert your changes in Actionlog.

Did you change the setting in `/admin/notifications`?

**Comment by andrescarrion** [comment]
okay I reverted the changes and I changed where you told me but the date is the same, if I put 6 months it doesn't change the 12 months

**Comment by snipe** [comment]
What specific page are you seeing 12 months on?

**Comment by andrescarrion** [comment]
over here 

![screen shot 2017-11-21 at 11 54 07 am](https://user-images.githubusercontent.com/33849743/33093884-1ae218de-ceb3-11e7-88eb-7c5c6aae63e3.png)
![screen shot 2017-11-21 at 11 55 02 am](https://user-images.githubusercontent.com/33849743/33093901-1f336e4c-ceb3-11e7-93e8-89d67bac8950.png)
