### ISSUE TITLE
/var/www/snipe-it/storage/logs/laravel.log" could not be opened

### ISSUE THREAD

**Issue by Choeoqe** [snipe/snipe-it#4499]
#### Expected Behavior (or desired behavior if a feature request)

Fresh install and attempting to connect via browser

-----

#### Actual Behavior

After enabling debugging I get:

 (1/1) UnexpectedValueException

The stream or file "/var/www/snipe-it/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install

- Version of Snipe-IT you're running
v4.1.5

- Version of PHP you're running
7.1.11 

- Version of MySQL/MariaDB you're running
5.5.56

- What OS and web server you're running Snipe-IT on
CentOS 7 4.1708
Apache

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Git

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
 (1/1) UnexpectedValueException
The stream or file "/var/www/snipe-it/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Homepage

- If a stacktrace is provided in the error, include that too.

- Any errors that appear in your browser's error console.

- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
No

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

- Include what you've done so far in the installation, and if you got any error messages along the way.
I had an issue I missed that composer didn't complete due to the PHP install not working. I then removed PHP and installed PHP 7. 

It looks like a straightforward permissions issue with the storage folder, however I have tried the following:

chown -R apache:apache /var/www/snipe-it/storage
chmod -R 777 /var/www/snipe-it/storage
chmod -R g+rwX storage
chmod g+s 

and had no luck.

I am not sure if this is really a Snipe-IT issue or more just a linux issue, so please let me know if I should direct this elsewhere. I have researched online and everything points to permissions but however I try and change them I still can't seem to get it to work correctly.

- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
It's not a Snipe-IT issue, but maybe an SELinux issue? Check out https://snipe-it.readme.io/docs/linuxosx#section-notes-on-selinux

**Comment by Choeoqe** [comment]
Ah yes, that was it - changed the SELinux context (and changed my .env DB_HOST from IP to localhost) and got the Snipe-IT Pre-Flight page. Thanks so much for pointing me in the right direction!

**Comment by snipe** [comment]
![high-fives](https://user-images.githubusercontent.com/197404/33092346-c2068320-ceae-11e7-84e2-0db2ed287b00.gif)

**Comment by bibin786** [comment]
Hi all iam getting this error please any one knows kindly 
The stream or file "/var/www/snipe-it/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied

**Comment by bibin786** [comment]
NOW GETTING THIS ERROR KINDLY CHECK
SQLSTATE[HY000] [2002] Permission denied (SQL: select * from information_schema.tables where table_schema = snipeit_db and table_name = users)

**Comment by EarlRamirez** [comment]
You will need to modify the permissions on the storage director as described in the docs. This issue was already resolved so I would recommend creating a new issue and completing the template, e.g. The OS that you are running, create a new issue and I will be happy to help you resolve it

**Comment by EarlRamirez** [comment]
@bibin786 sure, create the new issue and I'll be able to help, or you can hop over to gitter and we chat

**Comment by omer-jan** [comment]
The stream or file "/var/www/myproject/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied

**Comment by EarlRamirez** [comment]
@omer-jan, please create a new issue for this since this one has been closed for a while. Complete the template and we will be happy to assist

**Comment by bibin786** [comment]
Getting same issue please help

**Comment by bibin786** [comment]
now getting this issue
SQLSTATE[HY000] [2002] Connection refused (SQL: select * from
information_schema.tables where table_schema = snipeit_db and table_name =
users)

**Comment by EarlRamirez** [comment]
Please create a new issue for this?
