### ISSUE TITLE
License report not showing properly  

### ISSUE THREAD

**Issue by shahandas** [snipe/snipe-it#450]
Eg: 1) we  have 10 application  licence, mapped 6 to users but  license report showing total seats 10 and remaining seats -2 

2) 5 Desktop OS licensces all mapped to users but in licensceing report itis showing total seats 5 and remaining seats -5

Note : recently upgraded to 1.2 version (for advanced reporting features)

**Comment by SeanLebeau** [comment]
I noticed something like this as well. In my case if I have a licence mapped both to a user and an asset it counts it twice so I get and negative number in remaining seats.

**Comment by shahandas** [comment]
Thanks Sean ,
our issue is same as what you mentioned.
