### ISSUE TITLE
Documentation of directory ownership for upgrades

### ISSUE THREAD

**Issue by Mooninaut** [snipe/snipe-it#4503]
#### Expected Behavior (or desired behavior if a feature request)

The documentation recommends having the snipeit/ directory owned by an unprivileged user, and the snipeit/public/uploads/ and snipeit/storage/ directories owned by the web server user.

The documentation does not mention that this configuration will cause upgrades to fail. The server administrator must change the ownership of these directories before and after every upgrade for the upgrade to succeed.

Example: Let's say I have the /var/www/snipeit/storage and /var/www/snipeit/public/uploads directories owned by user www-data, and the rest of the /var/www/snipeit directory tree owned by user snipeit.

In order to perform an upgrade, I must first run
`cd /var/www/snipeit; sudo chown -R snipeit:snipeit storage public/uploads`

Then, as user 'snipeit', I can run
`php upgrade.php`

After the upgrade, I must then run
`cd /var/www/snipeit; sudo chown -R www-data:www-data storage public/uploads`
to restore access to those directories by the web server.

-----

#### Actual Behavior

If I don't change the permissions, I get permission errors and the upgrade fails. I did not find instructions for avoiding this failure in the documentation.

-----

#### Please confirm you have done the following before posting your bug report:

- [n/a] I have enabled debug mode 
- [Yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running: v4.1.6 - build 2939 (master)
- Version of PHP you're running: 7.0.22
- Version of MySQL/MariaDB you're running: 5.7.20
- What OS and web server you're running Snipe-IT on: Ubuntu 16.04.3 LTS, Apache/2.4.18
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: n/a
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: n/a
- If a stacktrace is provided in the error, include that too. n/a
- Any errors that appear in your browser's error console. n/a
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. n/a
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. n/a
- Include what you've done so far in the installation, and if you got any error messages along the way.

`$ php upgrade.php`

```
PHP Notice:  Undefined offset: 1 in /var/www/snipeit/upgrade.php on line 12
Welcome to the Snipe-IT upgrader.

Please note that this script will not download the latest Snipe-IT
files for you unless you have git installed.
It simply runs the standard composer and artisan
commands needed to finalize the upgrade after

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! If you have any encrypted custom fields, BE SURE TO run the recrypter.
!! See the Snipe-IT documentation for help:
!! https://snipe-it.readme.io/docs/upgrading-to-v4
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--------------------------------------------------------
STEP 1: Backing up database:
--------------------------------------------------------

-- Starting backup...
Dumping database snipeit...
Backup failed because The dump process failed with exitcode 2 : Misuse of shell 
builtins : sh: 1: cannot create /var/www/snipeit/storage/laravel-backups/temp//snipeit.sql: 
Directory nonexistent
.
Backup failed because: The stream or file "/var/www/snipeit/storage/logs/laravel.log" 
could not be opened: failed to open stream: Permission denied.

  [UnexpectedValueException]
  The stream or file "/var/www/snipeit/storage/logs/laravel.log" could not be 
opened: failed to open stream: Permission denied

--------------------------------------------------------
STEP 2: Putting application into maintenance mode:
--------------------------------------------------------

--
  [UnexpectedValueException]
  The stream or file "/var/www/snipeit/storage/logs/laravel.log" could not be 
opened: failed to open stream: Permission denied

--------------------------------------------------------
STEP 3: Pulling latest from Git (master branch):
--------------------------------------------------------

Git is installed.
warning: unable to unlink storage/app/backups/env-backups/.gitignore: Permission denied
error: unable to unlink old 'storage/app/backups/.gitignore' (Permission denied)
Previous HEAD position was 2562eb2... Merge branch 'develop'
Switched to branch 'master'
error: unable to unlink old 'storage/app/backups/.gitignore' (Permission denied)
fatal: Could not reset index file to revision 'HEAD'.
remote: Counting objects: 7228, done.
remote: Compressing objects: 100% (51/51), done.
Receiving objects: 100% (7228/7228), 6.39 MiB | 640.00 KiB/s, done.
remote: Total 7228 (delta 2559), reused 2593 (delta 2555), pack-reused 4622
Resolving deltas: 100% (4537/4537), completed with 762 local objects.
From https://github.com/snipe/snipe-it
   2562eb2..0910587  master     -> origin/master
 * [new branch]      assets_search_companyable_fix -> origin/assets_search_companyable_fix
 * [new branch]      assets_search_companyable_fix_develop -> origin/assets_search_companyable_fix_develop
   85da308..09f2087  develop    -> origin/develop
 * [new branch]      features/dusk -> origin/features/dusk
 * [new branch]      features/fix_eager_loading_on_licenses -> origin/features/fix_eager_loading_on_licenses
 * [new branch]      features/fix_locations_detail -> origin/features/fix_locations_detail
 * [new branch]      features/flatten-locations -> origin/features/flatten-locations
 * [new branch]      features/improve_unlinking_images -> origin/features/improve_unlinking_images
 * [new tag]         v4.0.10    -> v4.0.10
 * [new tag]         v4.0.11    -> v4.0.11
 * [new tag]         v4.0.12    -> v4.0.12
 * [new tag]         v4.0.13    -> v4.0.13
 * [new tag]         v4.0.14    -> v4.0.14
 * [new tag]         v4.0.15    -> v4.0.15
 * [new tag]         v4.1.0     -> v4.1.0
 * [new tag]         v4.1.0-beta -> v4.1.0-beta
 * [new tag]         v4.1.0-beta2 -> v4.1.0-beta2
 * [new tag]         v4.1.1     -> v4.1.1
 * [new tag]         v4.1.2     -> v4.1.2
 * [new tag]         v4.1.3     -> v4.1.3
 * [new tag]         v4.1.4     -> v4.1.4
 * [new tag]         v4.1.5     -> v4.1.5
error: Your local changes to the following files would be overwritten by merge:
        storage/app/backups/.gitignore 
Please, commit your changes or stash them before you can merge.
error: The following untracked working tree files would be overwritten by merge:
        storage/app/backups/env-backups/.gitignore
Please move or remove them before you can merge.
Aborting
-- Saved working directory and index state WIP on master: fd51565 Fix broken user's manual link (#3902)
-- M    storage/app/backups/.gitignore
Your branch is behind 'origin/master' by 1061 commits, and can be fast-forwarded. 
  (use "git pull" to update your local branch)
-- Updating fd51565..0910587
--------------------------------------------------------
Step 4: Cleaning up old cached files:
--------------------------------------------------------

-- No bootstrap/cache/compiled.php, so nothing to delete.
-- Deleting bootstrap/cache/services.php. It it no longer used.
-- No bootstrap/cache/config.php, so nothing to delete.
--
  [UnexpectedValueException]
  The stream or file "/var/www/snipeit/storage/logs/laravel.log" could not be 
opened: failed to open stream: Permission denied

--

  [UnexpectedValueException]
  The stream or file "/var/www/snipeit/storage/logs/laravel.log" could not be 
opened: failed to open stream: Permission denied

--

  [UnexpectedValueException]
  The stream or file "/var/www/snipeit/storage/logs/laravel.log" could not be 
opened: failed to open stream: Permission denied

--

  [UnexpectedValueException]
  The stream or file "/var/www/snipeit/storage/logs/laravel.log" could not be 
opened: failed to open stream: Permission denied

--------------------------------------------------------
Step 5: Updating composer dependencies:
(This may take an moment.)
--------------------------------------------------------

-- Local composer.phar detected, so we'll use that.

Generating autoload files
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 25 installs, 57 updates, 19 removals
  - Removing unicodeveloper/laravel-password (1.0.2)
  - Removing schuppo/password-strength (v1.9)
  - Removing patchwork/utf8 (v1.3.1)
^C
```
I killed the upgrade at this point, changed the directory permissions, ran `git fetch -p`, then `git reset --hard origin/master`, then ran `php upgrade.php` successfully.

- Indicate whether or not you've manually edited any data directly in the database

No.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
> The documentation recommends having the snipeit/ directory owned by an unprivileged user, and the snipeit/public/uploads/ and snipeit/storage/ directories owned by the web server user

That's not exactly right.

<img width="806" alt="screen shot 2017-11-22 at 5 35 37 am" src="https://user-images.githubusercontent.com/197404/33130092-07f9359c-cf47-11e7-8800-ae995640142b.png">

Writable by the web server does not necessarily mean owned by the web server. The easiest way to handle this is by making your snipeit user part of the web server's group. That's pretty standard for Linux webservers. I can see how the previous docs could be a little confusing though. I've updated them with more clarification.
