### ISSUE TITLE
LDAP OK LDAPS Not so much

### ISSUE THREAD

**Issue by Malakianite** [snipe/snipe-it#4504]
#### Expected Behavior (or desired behavior if a feature request)

LDAP Auth Test to Pass

-----

#### Actual Behavior

Could not bind to LDAP: Can't contact LDAP server

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  **Fresh Install**
- Version of Snipe-IT you're running **3.6.6**
- Version of PHP you're running **5.6.32**
- Version of MySQL/MariaDB you're running **10.1.28-MariaDB**
- What OS and web server you're running Snipe-IT on **Windows Server 2012 - Apache**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Manual - XAMPP**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error 
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

Hi,

I am getting the 'Could not bind to LDAP: Can't contact LDAP Server' message when I am clicking the 'Test LDAP' button within settings.
I don't see any browser errors or anything within the laravel log.   Interestingly when I use the same details (except the port for secure connection) with LDAP it connect successfully.

 LDAP enabled   TICKED

Active Directory  

 This is an Active Directory server   TICKED

LDAP Password Sync 

 Yes  TICKED

  

Active Directory domain  domain.local

This is sometimes the same as your email domain, but not always.
  

LDAP Server ldaps://domaincontroller.domain.local:636/ (have tried without :636 and /)

  

Use TLS  Unchecked

LDAP SSL certificate validation  

 Allow invalid SSL Certificate Ticked

 

LDAP Bind Username CN=service account,OU=Ops,OU=People,DC=domain,DC=local

 

LDAP Bind Password password

 

Base Bind DN dc=domain,dc=local

 

LDAP Filter cn

 

Username Field samaccountname

 

Last Name sn

 

LDAP First Name givenname

 

LDAP Authentication query samaccountName=

 

LDAP Version 3

 

LDAP Active Flag 

 

LDAP Employee Number 

 

LDAP Email mail

I have LDAPS working on a different application so I don't believe it to be a firewall issue.

Let me know if I've missed anything out!

Thanks.

**Comment by snipe** [comment]
> I have LDAPS working on a different application so I don't believe it to be a firewall issue.

A different application on the same server?

**Comment by Malakianite** [comment]
Good question, no the working application is on a different server.  
Ps thanks for an amazing piece of software.

**Comment by madd15** [comment]
is you filter just `cn` or is it `&(cn=*)`?

**Comment by Malakianite** [comment]
just cn at the time of writing.  Have amended to @(cn=*) thanks.  No change to my issue unfortunately.

**Comment by snipe** [comment]
@Malakianite do you know how to use ldapsearch? I would rule stuff out first by running ldapsearch from the server your Snipe-IT is installed on, just to make sure the LDAP server can even talk to that box and vice versa. 

Something like:

```
LDAPTLS_REQCERT=never ldapsearch -H ldaps://ldap.yourhost.com:636 -x -b "cn=users,dc=ad,dc=yourdomain,dc=com" -D "tester@ldap.yourhost.com" -w "PASSWORD" "(&(cn=*))" -Z -v
```

**Comment by Malakianite** [comment]
Hi,  I haven't used ldapsearch before.  Is it Linux based?  We're on windows server so I'm not sure where to run the command.

Thanks

**Comment by snipe** [comment]
Okay, I think this windows client should work for you then. https://technet.microsoft.com/en-us/library/cc961564.aspx

**Comment by Malakianite** [comment]
Not ignoring you just trying to get it to work :) will post results when I have them - appreciate the help

**Comment by Malakianite** [comment]
I used the windows LDAP Client 'LdapADmin' and was able to connect successfully via both LDAP and LDAPS from the snipe server.
Let me know if you need anything else

**Comment by morrows00** [comment]
I don't know if this will help you. But after recently upgrading I lost the same functionality with connecting to LDAPS. Previously I had my **LDAP Bind Username** set to ads\_username_ or maybe it was ads/_username_. Either way, after doing some playing with it, simply just having the _username_ in the field by itself worked for me. Hope this helps.
