### ISSUE TITLE
Impossible to create an API token

### ISSUE THREAD

**Issue by glureau** [snipe/snipe-it#4505]
#### Expected Behavior (or desired behavior if a feature request)

Go in /account/api, click on Create Token, fill the name and select enter => a token has been created

-----

#### Actual Behavior

Go in /account/api, click on Create Token, fill the name and select enter => 
```
Whoops! Something went wrong!
Something went wrong. Please try again.
```
Go in the snipe-it directory and use `php artisan passport:client` => Error because the _Base table or view not found: 1146 Table 'snipeit_db.oauth_clients' doesn't exist_

Not sure if it's an installation issue or something code related, I'll keep you updated if I find install issues...

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
fresh install
- Version of Snipe-IT you're running
v4.1.3 build 48 (g74aa562)

**Comment by snipe** [comment]
Check the permissions on your oauth tokens in `storage`

**Comment by snipe** [comment]
>  Error because the Base table or view not found: 1146 Table 'snipeit_db.oauth_clients' doesn't exist

Whoops - I missed that part. Run `php artisan migrate`.

**Comment by barrycarey** [comment]
Just to add to this, I did 2 fresh installs this week and had this same issue on both.  For both of them I had to run migrations then install passport.  Thought it might be environment related so I didn't bother posting an issue.  The migration created the Oauth tables both times.

**Comment by glureau** [comment]
Thanks @snipe , I wrongly presumed the fresh installation was on the latest version. So it's not a bug.
Best Regards
