### ISSUE TITLE
*The state may only contain letters

### ISSUE THREAD

**Issue by bioldame** [snipe/snipe-it#451]
![image](https://cloud.githubusercontent.com/assets/10458507/5712781/5ae011d2-9a83-11e4-8394-9ef87ddc4f26.png)
Even if the United States is selected as the country, the state field cannot contain spaces.

**Comment by snipe** [comment]
Which form is this? Using an abbreviation instead of the whole word would work around this, but I can change it to allow spaces.

**Comment by bioldame** [comment]
This is the locations form.

**Comment by snipe** [comment]
I just pushed a fix to the `develop` branch. Let me know if that works for you.
