### ISSUE TITLE
Expiring Licenses Alerts E-Mail: Wrong threshold and wrong German translation

### ISSUE THREAD

**Issue by qrioniclabs** [snipe/snipe-it#4511]
#### Expected Behavior

Correct German Translation:
"Es gibt [amount] Lizenzen, die in den nächsten [Threshold] Tagen ablaufen:"

-----

#### Actual Behavior

At the moment, the mail goes like this:
"[2, Inf] Da sind 3 [2, Inf] Lizenzen laufen in den nächsten 60 Tagen ab."

- The [2, Inf] part seems to be wrongly interpreted from the mail.php translation. Don't know if this is a global issue or just occurs for the German version of the mail

- Grammar is wrong, the 2 language components "Da sind 3" and "Lizenzen laufen..." are not fitted to each other

- The threshold is hard-coded to "60 Tagen" within the translation and does not recognized the custom threshold set in Alert Settings.

I am now heading over to crowdin to try and optimize the mail.php translation, but I think some of these issues originate elsewhere...

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
This regards the automatic expiring license alert mail.
Snipe-IT version: v4.1.4 build 173 (gba38b84)

**Comment by glureau** [comment]
I've read somewhere that SnipeIT translation can be updated via [crowndin](https://crowdin.com/project/snipe-it)

**Comment by qrioniclabs** [comment]
Well yes, and I have already submitted updates to the translation over at crowdin.

Still, the hard-coded threshold remains as well as the [2, inf] part within the mail.

**Comment by CronKz** [comment]
I've approved your translation. I'll ajust it again, when the threshold can be set as variable.
