### ISSUE TITLE
tagsLinkFormatter creation problem 

### ISSUE THREAD

**Issue by amarbhanu** [snipe/snipe-it#4512]
snipe-it version 4.14

CategoryPresenter  have           "formatter" => 'categoriesLinkFormatter', is working

but when create

TagsPresenter  have           "formatter" => 'tagsLinkFormatter',  is not working 

Please suggest if any have info.

**Comment by snipe** [comment]
Can you provide more information here? What exactly are you trying to do?

**Comment by JamLaMin** [comment]
When i create a user i need to privide or generate a password.

What i need...
A function like: Force the user to change their password at first login

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
