### ISSUE TITLE
Question Or Issue: How to generate the JWT based on the API key?

### ISSUE THREAD

**Issue by glureau** [snipe/snipe-it#4514]
#### Expected Behavior (or desired behavior if a feature request)

Generate an API token via `php artisan passport:client --personal` or  `php artisan passport:client` is generating a string of 40 characters in [a-zA-Z0-9].
Use a curl command to hit the API :

`curl -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: Bearer <TOKEN_40_CHAR>" -i http://foobar.com/api/v1/hardware`

Expected a list of assets.

-----

#### Actual Behavior

Get `{"error":"unauthorized"}`

I've searched in logs, the exception happens in: snipe-it/vendor/league/oauth2-server/src/AuthorizationValidators/BearerTokenValidator.php(93)
In the source code I saw the parsing was expecting a JWT: it's a string with 2 points (`.`) to delimite the 3 fields but the token generated is not JWT compliant.

Should I generate the JWT myself? If yes, do we have some documentation on this process?

-----

**Edit : Searchin on my own...**

Thanks to https://jwt.io/, I tried to understand how it's used in web interface, and from my local cookies I found an interesting one `laravel_token` with these fields:
```
header = {
  "iv": "a_iv==",
  "value": "a_very_long_value==",
  "mac": "a_long_mac"
}
```
Unfortunately, I don't know if it's the same structure than for API, and if yes, what I should put in these 3 fields. Also note that this JWT in web part doesn't have payload nor signature parts, so it doesn't look good to me (I don't know much about JWT, so maybe I'm totally wrong).

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
fresh install
- Version of Snipe-IT you're running
v4.1.3 build 48 (g74aa562)

**Comment by snipe** [comment]
I can't reproduce this...

When I run this locally:

```
curl -i https://snipe-it.dev:1337/api/v1/hardware -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImI0MTI1YWRjY2JhNjE2NzBmZmFjMDljMGIwZmMjliZTNkYWQ0ZmQ1OWY2In0.eyJhdWQiOiIxOCIsImp0aSI6ImI0MTI1YWRjY2JhNjE2NzBmZmFjMDljMGIwZmMwMTk3NjY2NTQ5MzU0N2UwNWJhZjMwYzIxOWE5YWU3OTAzM2M4ZjliZTNkYWQ0ZmQ1OWY2IiwiaWF0IjoxNDk1NTQ3Mzg3LCJuYmYiOjE0OTU1NDczODcsImV4cCI6MTgxMTA4MDE4Nywic3ViIjoiMSIsInNjb3BlcyI6W119.PWYT6Ovaw9f8H-YEfressUb6Mfn7Mts3Ks6d_aqr-M-iApoyhoDybe9QuU_9HMcdHecTuExYIfYUGRl0Uz-WI64bI1SPpbYWH8Mlzs6OAwJWXfKlUqoTsOtGOPNSdYZ_Ye2Fnmf0sFUS6QmXtBe9OIF2MUbPRr_IEk9oayuCmS4iFT-jZna2nt126BDVOjNLs8CB718DDfYN-Le5wZ_FmnD1vFXf6M1CLtmOXZ-bq460MOAKov00Nd2i94oXFNfVsw6yAkaeXuqGO1PCdCFTAHCJudJpXnNsfCEAqw534kJeh5y4jCP04mRocrM8EZbIwoOEcrsrxpJ-1q_97_C3M0gq0MNqTNI8bLQ82zOqY2LBuX9PbbzaVbgqz8tnNwjnOxBj42pEg8PDQCmqPCIjsU_1V6AyzpueC6ul0kUkhb3J93XE1VTRngCpbsHY-MwBB0KAaVaW9PBctsz3Ivi61xbupMsIoEZo8ISs5QjKU-C8_IZtnTXCm0g3MrHSHP-6BeNCV3UMkGsPgW6l1mqCO35h36jvQQuPRSbqfivnGX0dCbyqXdjiEWq6Gxl8awnGJVuFIk2d8tah7YdBZwUsj0PgZywqHYcO1kwEp7lYkRTcxhdMyC_TsXoB9TFyv1RwTbdeOOgb5CbSqxxbB49xOPfK1fU8KDiHZgBHrUigGFs" -H "Content-Type: application/json" -k
```

I get the expected JSON response.

(It's a local API token, so not worried about sharing it here ;)

**Comment by snipe** [comment]
(That bearer token was created via Account > API Token)

**Comment by glureau** [comment]
Token generated via Account > API Token si fine, but the one generated via `php artisan` looks incomplete:

```
/var/www/html/snipe-it$ php artisan passport:client

 Which user ID should the client be assigned to?:
 > 1

 What should we name the client?:
 > foo

 Where should we redirect the request after authorization? [http://<MY_IP>/auth/callback]:
 > <ENTER>

New client created successfully.
Client ID: 3
Client secret: Lo2X4DnwLdRtOM2WXeuETz2ighnqWOZPnzhvw3Qr
```

Maybe usage of artisan for this is deprecated now?

**Comment by snipe** [comment]
`php artisan passport:client` is meant to create an OAuth *client*, not an access token for API access. This would be used if you wanted to use Snipe-IT as an OAuth server - which frankly, we haven't tested at all. It comes out of the box with Passport, but we haven't tried it, and aren't even sure there's a good use-case for it.

This tutorial might help clear things up a little? https://blog.shameerc.com/2016/08/set-up-oauth2-server-using-laravel-passport

**Comment by glureau** [comment]
Great, thanks for the explanation @snipe, I'm fine with JWT for now ;)
The documentation confuses me, maybe worth mentioning the JWT vs OAuth bit [here](https://snipe-it.readme.io/v4.0/reference#generating-api-tokens)?

**Comment by snipe** [comment]
To be honest, it's pretty poorly documented by Laravel itself, which is why we don't explain it particularly well. There's just not a ton of info out there on how it actually works. :(
