### ISSUE TITLE
Feature Request - Update Custom Fields API with PATCH or PUT.

### ISSUE THREAD

**Issue by barrycarey** [snipe/snipe-it#4518]
The ability to update custom fields via the API would be extremely useful. 

For me personally we use custom fields to track a lot of details such as OS, RAM, Image Dates, ect. Without the option in the API I have to issue updates directly to the database. 

Possibly by passing the custom field name directly in the post body during an asset Put or patch. 

![capture](https://user-images.githubusercontent.com/3161456/33222758-8bc836ca-d127-11e7-8ca2-49a028afbd2d.PNG)

**Comment by snipe** [comment]
There ability to update the custom fields of an asset should already be in the API.

```
 if ($request->has('model_id')) {
                if (($model = AssetModel::find($request->get('model_id'))) && (isset($model->fieldset))) {
                    foreach ($model->fieldset->fields as $field) {
                        if ($request->has($field->convertUnicodeDbSlug())) {
                            $asset->{$field->convertUnicodeDbSlug()} = e($request->input($field->convertUnicodeDbSlug()));
                        }
                    }
                }
            }
```

Try passing the model ID with the request?
