### ISSUE TITLE
API Improvement - Specific Errors For Checkout With Invalid Data

### ISSUE THREAD

**Issue by barrycarey** [snipe/snipe-it#4522]
Currently if you provide an invalid user_id or location_id during checkout you recieve "An Error has occured! Trying to get property of non-object"

This is inconsistent with other areas of the API where they tell you which field caused the issue. 

Invalid User Id: 

![image](https://user-images.githubusercontent.com/3161456/33233656-53e8c0ec-d1e7-11e7-8ad6-c30e8d1770bd.png)

Invalid Fields When Creating an Asset: 

![image](https://user-images.githubusercontent.com/3161456/33233669-8c516790-d1e7-11e7-94af-be9bc75da4c5.png)

**Comment by snipe** [comment]
That "An error has occurred" means the script crashed. What we have to do is figure out what's it's trying to get a property on and fix the crash. Can you give me the output from your logs when you reproduce that?

**Comment by barrycarey** [comment]
![image](https://user-images.githubusercontent.com/3161456/33300726-da36c4bc-d3bf-11e7-9f29-cc07668a4df4.png)


[laravel.log](https://github.com/snipe/snipe-it/files/1508372/laravel.log)

**Comment by snipe** [comment]
> Can you give me the output from your logs when you reproduce that?

**Comment by snipe** [comment]
Oops, sorry, I didn't see it was attached. (FYI, I hate downloading log files - much prefer inline.)

**Comment by snipe** [comment]
Also, what version are you running? Line 520 on the AssetsController doesn't correspond to anything useful on develop

**Comment by barrycarey** [comment]
4.1.4 at the moment.

**Comment by snipe** [comment]
Additionally, I don't think you should be passing user_id and asset_id there.

```
if ($request->has('user_id')) {
            $target = User::find($request->input('user_id'));
            $location = $target->location_id;
            $error_payload['target_id'] = $request->input('user_id');
            $error_payload['target_type'] = User::class;
        // Don't let the user check an asset out to itself
} elseif ($request->has('asset_id')) {
            $target = Asset::where('id','!=',$asset_id)->find($request->input('asset_id'));
            $location = $target->location_id;
            $error_payload['target_id'] = $request->input('asset_id');
            $error_payload['target_type'] = Asset::class;
} elseif ($request->has('location_id')) {
            $target = Location::find($request->input('location_id'));
            $location = $target->id;
            $target = Location::find($request->input('location_id'));
            $error_payload['target_id'] = $request->input('location_id');
            $error_payload['target_type'] = Location::class;
        }
```

It will pick user first, then asset, then location if more than one is passed. 

That said, we'll probably be making that method behave a little more like the regular checkout, which looks like this:

```
 // This item is checked out to a location
 if (request('checkout_to_type')=='location') {
            $target = Location::find(request('assigned_location'));
            $asset->location_id = ($target) ? $target->id : '';
} elseif (request('checkout_to_type')=='asset') {
            $target = Asset::where('id','!=',$assetId)->find(request('assigned_asset'));
            $asset->location_id = $target->rtd_location_id;
            // Override with the asset's location_id if it has one
            if ($target->location_id!='') {
                $asset->location_id = ($target) ? $target->location_id : '';
            }
} else {
            // Fetch the target and set the asset's new location_id
            $target = User::find(request('assigned_user'));
            $asset->location_id = ($target) ? $target->location_id : '';
}


        // No valid target was found - error out
        if (!$target) {
            return redirect()->to("hardware/$assetId/checkout")->with('error', trans('admin/hardware/message.checkout.error'))->withErrors($asset->getErrors());
        }
```

**Comment by snipe** [comment]
Can you try pulling from latest master, and trying again, so I can see what the current line number is where you're seeing that?

**Comment by barrycarey** [comment]
Sure.  Give me a minute to update

**Comment by barrycarey** [comment]
After the update: 

> [2017-11-27 22:52:08] production.ERROR: ErrorException: Trying to get property of non-object in C:\inetpub\wwwroot\snipe\app\Http\Controllers\Api\AssetsController.php:527
Stack trace:
#0 C:\inetpub\wwwroot\snipe\app\Http\Controllers\Api\AssetsController.php(527): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', 'C:\\inetpub\\wwwr...', 527, Array)
#1 [internal function]: App\Http\Controllers\Api\AssetsController->checkout(Object(Illuminate\Http\Request), '1')
#2 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(55): call_user_func_array(Array, Array)
#3 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('checkout', Array)
#4 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\AssetsController), 'checkout')
#5 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Route.php(160): Illuminate\Routing\Route->runController()
#6 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Router.php(574): Illuminate\Routing\Route->run()
#7 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#8 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#10 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Router.php(576): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Router.php(535): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#14 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Router.php(513): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#15 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#17 C:\inetpub\wwwroot\snipe\vendor\barryvdh\laravel-debugbar\src\Middleware\Debugbar.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 C:\inetpub\wwwroot\snipe\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 C:\inetpub\wwwroot\snipe\vendor\fideloper\proxy\src\TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 C:\inetpub\wwwroot\snipe\app\Http\Middleware\CheckForSetup.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 C:\inetpub\wwwroot\snipe\app\Http\Middleware\NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 C:\inetpub\wwwroot\snipe\app\Http\Middleware\ContentSecurityPolicyHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\ContentSecurityPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 C:\inetpub\wwwroot\snipe\app\Http\Middleware\ReferrerPolicyHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\ReferrerPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 C:\inetpub\wwwroot\snipe\app\Http\Middleware\XssProtectHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 C:\inetpub\wwwroot\snipe\app\Http\Middleware\FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#55 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#56 C:\inetpub\wwwroot\snipe\public\index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#57 {main}  
[2017-11-27 22:52:08] production.ERROR: ErrorException: Trying to get property of non-object in C:\inetpub\wwwroot\snipe\app\Http\Controllers\Api\AssetsController.php:527
Stack trace:
#0 C:\inetpub\wwwroot\snipe\app\Http\Controllers\Api\AssetsController.php(527): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', 'C:\\inetpub\\wwwr...', 527, Array)
#1 [internal function]: App\Http\Controllers\Api\AssetsController->checkout(Object(Illuminate\Http\Request), '1')
#2 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(55): call_user_func_array(Array, Array)
#3 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('checkout', Array)
#4 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\AssetsController), 'checkout')
#5 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Route.php(160): Illuminate\Routing\Route->runController()
#6 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Router.php(574): Illuminate\Routing\Route->run()
#7 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#8 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#10 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Router.php(576): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#13 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Router.php(535): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#14 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Router.php(513): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#15 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#16 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#17 C:\inetpub\wwwroot\snipe\vendor\barryvdh\laravel-debugbar\src\Middleware\Debugbar.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 C:\inetpub\wwwroot\snipe\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 C:\inetpub\wwwroot\snipe\vendor\fideloper\proxy\src\TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 C:\inetpub\wwwroot\snipe\app\Http\Middleware\CheckForSetup.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 C:\inetpub\wwwroot\snipe\app\Http\Middleware\NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 C:\inetpub\wwwroot\snipe\app\Http\Middleware\ContentSecurityPolicyHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\ContentSecurityPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 C:\inetpub\wwwroot\snipe\app\Http\Middleware\ReferrerPolicyHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\ReferrerPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 C:\inetpub\wwwroot\snipe\app\Http\Middleware\XssProtectHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 C:\inetpub\wwwroot\snipe\app\Http\Middleware\FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#55 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#56 C:\inetpub\wwwroot\snipe\public\index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#57 {main}

**Comment by snipe** [comment]
Is it possible that that user_id belongs to an invalid or deleted user?

**Comment by barrycarey** [comment]
That user ID doesn't belong to anyone.  It works as expected if you pass a valid user ID. 

With an invalid ID I would expect a clean 200 response with an error message saying the user ID is invalid.  Similar to how passing an invalid ID elsewhere responds with a clear error and 200 code.

**Comment by snipe** [comment]
Can you pull from develop and see if this is resolved?

Asset is unavailable for checkout:
<img width="1120" alt="screen shot 2017-11-27 at 9 21 18 pm" src="https://user-images.githubusercontent.com/197404/33303607-f69db46e-d3b8-11e7-8220-43efbaa9ecff.png">

Missing `checkout_to_type`:
<img width="1116" alt="screen shot 2017-11-27 at 9 22 52 pm" src="https://user-images.githubusercontent.com/197404/33303637-287d1b28-d3b9-11e7-8218-b7a3740143fa.png">

 `checkout_to_type` is present, but no checkout target provided:
<img width="1113" alt="screen shot 2017-11-27 at 9 23 28 pm" src="https://user-images.githubusercontent.com/197404/33303655-3e9fb8a2-d3b9-11e7-9eaf-46955b194f9b.png">

 `checkout_to_type` and target are provided, but target is invalid:
<img width="1118" alt="screen shot 2017-11-27 at 9 24 08 pm" src="https://user-images.githubusercontent.com/197404/33303667-59175d48-d3b9-11e7-85ff-2ee46bff4ee8.png">

<img width="1118" alt="screen shot 2017-11-27 at 9 24 59 pm" src="https://user-images.githubusercontent.com/197404/33303677-73d8bdf2-d3b9-11e7-9ba6-fe1c6afe3011.png">

 `checkout_to_type` is invalid:
<img width="1115" alt="screen shot 2017-11-27 at 9 26 26 pm" src="https://user-images.githubusercontent.com/197404/33303720-aecaeeee-d3b9-11e7-90b7-1a442a72381e.png">


Asset checked out:
<img width="1112" alt="screen shot 2017-11-27 at 9 22 10 pm" src="https://user-images.githubusercontent.com/197404/33303622-11610f62-d3b9-11e7-91a9-a4e4376b85ea.png">

### Note: Some fields have changed

- You must pass  `checkout_to_type`, and it must be `asset`, `location`, or `user`.
- For target you will pass: `assigned_user`, `assigned_location`, or `assigned_asset`

**Comment by barrycarey** [comment]
Looks good now.   Quickly tested it and it looks to respond as you said.
