### ISSUE TITLE
Illuminate\Database\QueryException

### ISSUE THREAD

**Issue by jaricharte** [snipe/snipe-it#453]
Hi guys,

I am trying to install Snipe IT 1.1 in my local machine to propose it as the company official ITAM. I follow the instructions provided but I got stuck trying to install Artisan (php artisan app:install). It seems the database seeding doesn't complete, I get the following error:

 [Illuminate\Database\QueryException]
 SQLSTATE[HY000]: General error: 1364 Field 'purchase_order' doesn't have a
 default value (SQL: insert into `licenses` (`created_at`, `deleted_at`, `de
 preciate`, `depreciation_id`, `license_email`, `license_name`, `name`, `not
 es`, `order_number`, `purchase_cost`, `purchase_date`, `seats`, `serial`, `
 updated_at`, `user_id`) values (2014-12-18 12:16:23, , 0, 2, , , Adobe Phot
 oshop CS6, , 987698576946, 2435.99, 2013-10-02, 5, ZOMG-WtF-BBQ-SRSLY, 2014
 -12-18 12:16:23, 1), (2014-12-18 12:16:23, , 0, 2, snipe@snipe.net, Alison
 Gianotto, Git Tower, , 987698576946, 2435.99, 2013-10-02, 2, 98049890394-34
 0485934, 2014-12-18 12:16:23, 1))

Any ideas of how to proceed?

The environment is Windows with IIS.

Thank you!

**Comment by snipe** [comment]
Sounds like maybe mysql is running in strict mode?

**Comment by snipe** [comment]
If you try running `SET sql_mode = '';` in your MySQL prompt, does that resolve it?

**Comment by jaricharte** [comment]
My MySQL is not running in strict mode, as far as I know. Actually, I was able to setup the "old" Alpha in the same database. Let me try the command you suggest and I will let you know the outcome.

**Comment by jaricharte** [comment]
Issue resolved by installing it on Ubuntu Server with an automatic script :)
