### ISSUE TITLE
 When I change the IP address of the snipe-It server, In the asset when labels generate the ip address it's identified the previous IP of the server not the current IP when scanning the Qr code.

### ISSUE THREAD

**Issue by paulo1624** [snipe/snipe-it#4530]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
You'll need to clear out your cached barcodes (delete contents of `public/uploads/barcodes`) and clear your config cache. `php artisan config:cache`.

**Comment by paulo1624** [comment]
I tried your suggestions, but still the same issue. QRcode recognized the previous IP of the server.

**Comment by snipe** [comment]
Did you change the APP_URL in your .env before doing any of those things?

**Comment by paulo1624** [comment]
I didn't changed. 
![image](https://user-images.githubusercontent.com/32555803/33293664-863c97bc-d408-11e7-8f36-3f2731cbe3c5.png)

**Comment by snipe** [comment]
You have to change that. The APP_URL is literally what defines what URL you're using for the app.

**Comment by paulo1624** [comment]
I already did to change the APP_URL to IP address of the server.
![image](https://user-images.githubusercontent.com/32555803/33294017-c5ab5270-d409-11e7-96b8-e312261f0233.png)

**Comment by paulo1624** [comment]
but still the same.

**Comment by snipe** [comment]
Once you c change that, you have to clear your config cache and delete the contents of your barcodes directory as I said above.

**Comment by snipe** [comment]
(Also, never post your APP_KEY publicly.)

**Comment by paulo1624** [comment]
I had been clear the config cache and delete the content of barcode directory. but its still recognized the previous IP of the server, and then QRcode image its disappear on asset. Please see below image. 
![image](https://user-images.githubusercontent.com/32555803/33348253-a50c22e8-d4d0-11e7-8b09-0ef755f46ac0.png)

**Comment by paulo1624** [comment]
Only 2 files inside barcodes directory. Done deleting the previous content, and already did config cache clear.
![image](https://user-images.githubusercontent.com/32555803/33348448-7049b6c8-d4d1-11e7-826c-809a4f0419e6.png)

![image](https://user-images.githubusercontent.com/32555803/33348466-7ff0cada-d4d1-11e7-85ee-8338ddef6837.png)

**Comment by JSCMP** [comment]
Same problem here. Brand new installation. APP_URL has the correct domain to access the website from the Internet, I can manually open it and test that it works, yet when I scan the QR codes it opens the internal IP address.:
http://10.0.1.254/hardware/2

My env. file showing the APP_URL:

Why is Snipe-IT generating QR codes with internal IP, where nowhere I have put the Internal IP for it.
Using 4.2.0

# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=
APP_URL=http://XXXXXXXX.com
APP_TIMEZONE='UTC'
APP_LOCALE=en

**Comment by adylimmo** [comment]
![capture](https://user-images.githubusercontent.com/22222644/39879631-92c1f432-54a5-11e8-8918-704f9ddf2931.PNG)

make sure permision 777 in public/uploads/barcodes

**Comment by imaginethatca** [comment]
I am new to Linux and Snipe-IT, and has the Linux server still using DHCP, and I had used that IP address in .env.
I finally fixed the IP address and lost all the Avatar images, all pointing to old IP. I updated .env with new IP, and still no joy.
running the `php artisan config:cache` command fixed my issue with the Peoples avatar images.
Thanks for this post, it helped.

**Comment by regjonh** [comment]
You might be overlooking the section "OPTIONAL: SESSION SETTINGS". Under this section, if you had set the value for "COOKIE_DOMAIN=" to match the APP_URL, you must update the COOKIE_DOMAIN value accordingly or set it to null.
I struggled for hours before I find out this. Then, you may need to run the command to clear the cache: config:clear, cache:clear, view:clear, route:clear. After these commands, restart Apache2, then run php artisan config:cache.
I am not certain all these commands help, but I used them in that order, and it worked for me: I was able to run Snipe-IT with a different name.
Hope this helps.
