### ISSUE TITLE
Feature Request - Audit Report

### ISSUE THREAD

**Issue by fillorkill** [snipe/snipe-it#4533]
A full audit report listing what have been audited and what have not would be helpful.

At the moment Last Audit Date cannot be displayed in the list view. Would be helpful if we can display this column in the list page as well as in custom reports.

**Comment by asuman1179** [comment]
+1 for this so it can be exports from the list view would be great!  Thanks Chris

**Comment by snipe** [comment]
Last audit date was included in the All Assets listing a version or two ago. (Sorry, I didn't close this at the time.)
