### ISSUE TITLE
API inconsistency: custom_fields

### ISSUE THREAD

**Issue by glureau** [snipe/snipe-it#4534]
Actually the API v1 is inconsistent regarding to the `custom_fields` field:
When a custom field has been set, it's an object:
```
"custom_fields":{
	"ShortSerial":{"field":"_snipeit_shortserial_4","value":"123456789"},
	"Firmware":{"field":"_snipeit_firmware_2","value":"0.0.0"}
}
```
when there is no data, it's an empty array:

`"custom_fields":[]`

To be consistent, it should probably returns null instead of an empty array.

As comparison:
`"updated_at":{"datetime":"2017-11-22 13:59:38","formatted":"2017-11-22 13:59"},"deleted_at":null`

Alternative, define custom_fields as an "array" (a map) instead:

```
"custom_fields":[
	"ShortSerial":{"field":"_snipeit_shortserial_4","value":"123456789"},
	"Firmware":{"field":"_snipeit_firmware_2","value":"0.0.0"}
]
```

## Motivation
A lot of languages could use a defined structure to retrieve these fields, for example with gson. Even in lenient, gson will not parse an empty array as a null object and will simply throw an exception.

I'd love to have this feature asap so I can prepare a PR, but I'd have a confirmation first on the resolution. Not sure if some other fields have a similar strategy, and not sure where to start in the source code, so if you have any input ;)

**Comment by snipe** [comment]
We cannot return null there, as it breaks the JavaScript tables on the GUI. This is a known behavior and right now I think the only course for developers is to know what it returns and handle accordingly. It’s not something we can fix right now.

**Comment by glureau** [comment]
Alright, thanks for the quick response.

### Workaround for Java/Kotlin developers using gson

```
object MapAdapter : JsonSerializer<Map<*, *>> {
    override fun serialize(src: Map<*, *>?, typeOfSrc: Type, context: JsonSerializationContext): JsonElement? {
        if (src == null || src.isEmpty())
            return null
        val obj = JsonObject()
        for ((key, value) in src) {
            obj.add(key.toString(), context.serialize(value))
        }
        return obj
    }
}
```

`val gson = GsonBuilder().registerTypeHierarchyAdapter(Map::class.java, MapAdapter).create()`

### And if used with retrofit:

`Retrofit.Builder().addConverterFactory(GsonConverterFactory.create(gson))`
