### ISSUE TITLE
Method not allowed show  when new method add in snipe-it useing LARAVEL 5.4.29

### ISSUE THREAD

**Issue by amarbhanu** [snipe/snipe-it#4536]
form action is /tags/uploadexcelfile

Controller/Api/TagController.php
Method create uploadexcelfile()
and 

routes/api.php

 /*--- Tags API ---*/

    Route::group(['prefix' => 'tags'], function () {

        Route::get('{item_type}/selectlist',
            [
                'as' => 'api.tags.selectlist',
                'uses' => 'TagsController@selectlist'
            ]

        );

        Route::post(
        'uploadexcelfile',
            [
            'as'  => 'api.tags.uploadExcelsheet',
            'uses' => 'TagsController@uploadExcelsheet'
            ]
        );
    }); // Tags group

    Route::resource('tags', 'TagsController',
        [
            'names' =>
                [   'uploader'=> 'api.tags.uploader',
                   'uploadexcelfile'=>'api.tags.uploadexcelfile',
                    'index' => 'api.tags.index',
                    'show' => 'api.tags.show',
                    'store' => 'api.tags.store',
                    'update' => 'api.tags.update',
                    'destroy' => 'api.tags.destroy'
                ],
            'except' => ['edit', 'create'],
            'parameters' => ['tag' => 'tag_id']
        ]
    );// Tags Resource
   
then got network response check then error 
{"status":"error","messages":"Method not allowed","payload":null}
any have idea to why show this types of message

**Comment by snipe** [comment]
What exactly are you trying to do here?

**Comment by amarbhanu** [comment]
Add new page for upload excel sheet for assets reference and tags data for on new tables.

then show method not allowed

**Comment by snipe** [comment]
> Add new page for upload excel sheet for assets reference and tags data for on new tables.

I don't really understand - we already have an asset importer. 

Anyway, you're using resource routes incorrectly. You'd need to use a route group there.
