### ISSUE TITLE
Detail Search Field "Status" does not work

### ISSUE THREAD

**Issue by chrstmnn** [snipe/snipe-it#4537]
#### Expected Behavior (or desired behavior if a feature request)

If I enter in Demo-Version the status "Deployed" into the search field "Status" of the detailed search in order to search for an asset, I should get all assets with status "Deployed".
-----

#### Actual Behavior

Actually Snipe IT finds no matching records. Searching for "Ready to deploy" works fine.
-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Comment by tbradsha** [comment]
This is the current expected behaviour. "Deployed" is not a real status, even though that's what's visually displayed. Everything under "deployed" is actually a "ready to deploy" status and also assigned to someone.
