### ISSUE TITLE
Feature request: Make the "Deployed" meta-status more intuitive

### ISSUE THREAD

**Issue by tbradsha** [snipe/snipe-it#4538]
#### Expected Behavior (or desired behavior if a feature request)

Have status functionality consistently based on "apparent" status (the one that appears on the front-end) instead of actual underlying status.

-----

#### Actual Behavior

Sorting and searching can only be done on the underlying status "Ready to Deploy".

-----

In the assets table the assets are visually displayed as if there are two statuses (the status column could be either "Ready to Deploy" or "Deployed"), but they behave as the underlying same status ("Ready to Deploy".

When one sees both statuses in the table, it is a natural assumption (from a UX/UI point of view) that one can manipulate the data as two separate statuses. The end user shouldn't have to worry about knowing that there is an underlying shared status.

This affects sorting and searching (#4369, #4238, #4537, #4295), the dashboard pie chart (#4486), and reporting (#4422, #3441, #3129) and is confusing plenty of users (#4060, #3905, #3342, #2933, #2512).

Yes, it's documented, but still not intuitive (as evidenced by the number of tickets created by confused users), and it's not consistent (using the sidebar to chose "deployed" only shows deployed items (thus treating it as two statuses), yet the dashboard pie chart lumps all "ready to deploy" in one). I'll survive if nothing changes, but there's a clear underlying issue that probably should be addressed.

I'd suggest any of the following as a potential solution:

1. Split them into two actual statuses in the database, or
2. Have a consistent conversion on all queries ("ready to deploy" + unassigned = "ready to deploy" vs. "ready to deploy + assigned = "deployed"), or
3. Remove the "deployed" meta-status completely and change "ready to deploy" to "deployable".

As a bonus, perhaps you could even add a preference to choose how to treat them consistently (throughout the entire program) as either two separate statuses or as one single status? :^)

**Comment by CronKz** [comment]
You have my vote for that 👍

**Comment by jmartins1** [comment]
This might be the case but it throws off the inventory. For example, my reports and status graph indicated I have over 400 items ready to deploy when in actuality I only had 43.

Thank you

**Comment by aidanbroadbridge** [comment]
We have exactly the same thoughts and issue  - any progress on this front?

**Comment by jmartins1** [comment]
I don't believe they will or can fix this. My workaround is to edit the item first (set it to deployed) then checkout normally. It's a pain especially if you bulk check out.

⁣Get BlueMail for Android ​

**Comment by randalldurham** [comment]
jmartins1 can you explain your workaround? Please

**Comment by jmartins1** [comment]
In version 5.1.4 when you check out an item, you have the ability at that time to also set the status. In earlier versions, you had to first check out the item then look up the asset, edit the item and set it to deployed. Unfortunately this is still the case when checking out items in bulk, but at least in single check-outs it's a big improvement.

**Comment by randalldurham** [comment]
Do i have to create the deployed option? I don't see it in the dropdown menu

**Comment by jmartins1** [comment]
Correct. Under the Settings option, select Status Labels.  There as you may be aware, you are able to create various labels that can be assigned to an asset. I've created a status label with the status name of Deployed and status type of Deployable, but you can call it whatever makes sense to you. Any status label you create will appear on the dashboard graph (Assets by Status) and will be available as a filter option in your reports.

**Comment by randalldurham** [comment]
Awesome thanks

**Comment by kaeser49** [comment]
it would be really nice, if the developper would solve the mess with a management graph who only confuses everbody.

**Comment by kaeser49** [comment]
ready to deploy obviously is not deployed as the graph suggest. So management is asking why we show 800+ units as ready to deploy but if in fact, the most of them are deployed to users.

It would only take a few hours to sort this out. Why is there no will to correct such little bugs on the top level of the software.

**Comment by jmartins1** [comment]
Create a "Deployed" status and assign it to the graph. When you check out an item set it to Deployed.

Joe

⁣Get BlueMail for Android ​

**Comment by jmartins1** [comment]
Agreed, but now that you have to correct this situation create a status label assign it to the graph and moving forward assign it to the deployed status that you created. Also if you are aware of which items are actually deployed you can book update their status to the new status label.

Joe

⁣Get BlueMail for Android ​

**Comment by jmartins1** [comment]
In addition, if you are unsure of which items are actually deployed you will need to go to each user and set the status label for each of the items that they have been issued to the new status label deployed.

Joe
⁣Get BlueMail for Android ​

**Comment by jmartins1** [comment]
Or, you can run a custom report that lists who the item was assigned to. This will show that they own was checked out ( and get your boss off your back :) ). Then you can use that list to bulk update the status label to deployed.

Joe

⁣Get BlueMail for Android ​

On Aug 14, 2022, 10:31 AM, at 10:31 AM, Jose Martins ***@***.***> wrote:
>
>In addition, if you are unsure of which items are actually deployed you
>will need to go to each user and set the status label for each of the
>items that they have been issued to the new status label deployed.
>
>Joe
>⁣Get BlueMail for Android ​
>
>On Aug 14, 2022, 9:41 AM, at 9:41 AM, Werner Kaeser

**Comment by jmartins1** [comment]
You can certainly create a new label for the graph called “staged” for example. Staging being ideas that are ready to deploy but haven’t yet. Then instead of assigning them as deployed, assign them as staged. These items will then appear on your graph under staged and not deployed.
