### ISSUE TITLE
Asset Categories

### ISSUE THREAD

**Issue by bioldame** [snipe/snipe-it#454]
Is there a way to add a quick shortcut to see all the assets categories and see what's in them right away. I know there is a way to search for Asset Models, but adding the functionality to search by asset categories would be a huge plus.
![image](https://cloud.githubusercontent.com/assets/10458507/5723970/2fa13724-9b16-11e4-9456-7da4a3c4907d.png)

**Comment by cparmar** [comment]
+1 for this.

**Comment by citizenkepler** [comment]
I believe this has been implemented.  Poke @snipe, close this issue as implemented?

**Comment by snipe** [comment]
Yep, thanks
