### ISSUE TITLE
V4.1.5 ISSUE 1: Checkin Error

### ISSUE THREAD

**Issue by linglongtong** [snipe/snipe-it#4541]
In v4.1.5 when I check in an asset, an error will show like this: Whoops, looks something went wrong.
But in fact, the asset has been checked in.

![image](https://user-images.githubusercontent.com/23185284/33415865-759fd694-d5d4-11e7-93d7-7d3ce2b84bef.png)

![image](https://user-images.githubusercontent.com/23185284/33415890-aba150e2-d5d4-11e7-9681-ebecd3266de2.png)

**Comment by MPIAE-IT** [comment]
Same thing here. Turning debug on I get these error messages:

`(1/1) Swift_RfcComplianceExceptionAddress in mailbox given [] does not comply with RFC 2822, 3.6.2.
--
in MailboxHeader.php (line 345)
at Swift_Mime_Headers_MailboxHeader->_assertValidAddress('')in MailboxHeader.php (line 261)
at Swift_Mime_Headers_MailboxHeader->normalizeMailboxes(array('' => null))in MailboxHeader.php (line 106)
at Swift_Mime_Headers_MailboxHeader->setNameAddresses(array('' => null))in MailboxHeader.php (line 63)
at Swift_Mime_Headers_MailboxHeader->setFieldBodyModel(array('' => null))in SimpleHeaderFactory.php (line 58)
at Swift_Mime_SimpleHeaderFactory->createMailboxHeader('Reply-To', array('' => null))in SimpleHeaderSet.php (line 68)
at Swift_Mime_SimpleHeaderSet->addMailboxHeader('Reply-To', array('' => null))in SimpleMessage.php (line 274)
at Swift_Mime_SimpleMessage->setReplyTo(array('' => null))in SimpleMessage.php (line 251)
at Swift_Mime_SimpleMessage->addReplyTo(null, null)in Message.php (line 158)
at Message->addAddresses(null, null, 'ReplyTo')in Message.php (line 142)
at Message->replyTo(null, null)in AssetsController.php (line 594)
at AssetsController->App\Http\Controllers\{closure}(object(Message))
at call_user_func(object(Closure), object(Message))in Mailer.php (line 202)
at Mailer->send('emails.checkin-asset', array('log_id' => 4321, 'first_name' => '***', 'item_name' => '24 Zoll Monitor EV2455 (***)', 'checkin_date' => object(Carbon), 'item_tag' => '***', 'item_serial' => '***', 'note' => '', 'manufacturer_name' => 'Eizo', 'model_name' => '24 Zoll Monitor EV2455', 'model_number' => 'EV2455-BK', 'message' => object(Message)), object(Closure))in Facade.php (line 221)
at Facade::__callStatic('send', array('emails.checkin-asset', array('log_id' => 4321, 'first_name' => '***', 'item_name' => '24 Zoll Monitor EV2455 (***)', 'checkin_date' => object(Carbon), 'item_tag' => '***', 'item_serial' => '***', 'note' => '', 'manufacturer_name' => 'Eizo', 'model_name' => '24 Zoll Monitor EV2455', 'model_number' => 'EV2455-BK'), object(Closure)))in AssetsController.php (line 596)
at AssetsController->postCheckin(object(AssetCheckinRequest), '701', 'user')
at call_user_func_array(array(object(AssetsController), 'postCheckin'), array(object(AssetCheckinRequest), 'assetId' => '701', 'backto' => 'user'))in Controller.php (line 55)
at Controller->callAction('postCheckin', array(object(AssetCheckinRequest), 'assetId' => '701', 'backto' => 'user'))in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(AssetsController), 'postCheckin')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 574)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php (line 43)
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php (line 49)
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php (line 49)
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php (line 42)
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 576)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 535)
at Router->dispatchToRoute(object(Request))in Router.php (line 513)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php (line 51)
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php (line 25)
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php (line 56)
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php (line 27)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)`

Be aware: I changed some informations in the log to ***

**Comment by snipe** [comment]
Do you have:

```
MAIL_REPLYTO_ADDR=you@example.com
MAIL_REPLYTO_NAME='Snipe-IT'
```

in your .env?

**Comment by MPIAE-IT** [comment]
No these lines are missing in my .env file. Must I add it?

**Comment by MPIAE-IT** [comment]
OK. Just added it. Error is gone! THANKS snipe!
