### ISSUE TITLE
Error when upgrading from 3.6.4 to 4.1.5

### ISSUE THREAD

**Issue by Pablitus** [snipe/snipe-it#4544]
#### Expected Behavior (or desired behavior if a feature request)

Upgrade flawless :)

-----

#### Actual Behavior

when running php artisan migrate
PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/snipeit/app/Exceptions/Handler.php:39
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(320): App\Exceptions\Handler->report(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(132): Illuminate\Foundation\Console\Kernel->reportException(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#2 /var/www/snipeit/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 {main}
  thrown in /var/www/snipeit/app/Exceptions/Handler.php on line 39

Same error happens at rollback

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade
- Version of Snipe-IT you're running
4.1.5
- Version of PHP you're running
Php7

- What OS and web server you're running Snipe-IT on
Ubuntu 16.04 LTS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh

**Comment by Pablitus** [comment]
Fixed...a git clone, composer update and a bit of magic did the trick

**Comment by snipe** [comment]
I think you probably ran into [this](https://snipe-it.readme.io/docs/common-issues#section-class-awslaravelawsserviceprovider-not-found-or-class-log-not-found) :)
