### ISSUE TITLE
Expected Check-in Date / Alerts

### ISSUE THREAD

**Issue by bioldame** [snipe/snipe-it#455]
Is there a way to add an expected check-in date when checking out an asset?

![image](https://cloud.githubusercontent.com/assets/10458507/5724024/9684f70a-9b16-11e4-96ca-24659a3e9eae.png)

It would be awesome to be able to enter this information when checking out an asset and be able to get alerts for over due assets and also being able to see it under Deployed assets
##

**Comment by madd15** [comment]
Expected check-in date will be in 2.0, alerts for overdue assets still needs doing.

**Comment by CLOZADA16** [comment]
Hi, Is there an update in the alerts for check in date? Just wondering coz I am using Snipe IT 2.1.1 and can't find it there.
