### ISSUE TITLE
Bad asset data causing "Trying to get property of non-object"

### ISSUE THREAD

**Issue by lukebigum** [snipe/snipe-it#4552]
#### Expected Behavior (or desired behavior if a feature request)

Viewing a certain location displays all assets in that location.

-----

#### Actual Behavior

No assets are displayed because an exception is thrown for one of our locations. We think this problem first appeared when moving from 2.x -> 4.0.25. Upgrading again to 4.1.16 and running the the Artisan job snipeit:sync-asset-locations has helped a little.

It appears that the availableForCheckout() method is being called on an object that doesn't exist, but I'm not sure how that's happening.  Looking in the database, there should be 66 assets with this location:

```
mysql> select count(*) from assets where rtd_location_id = 19;
+----------+
| count(*) |
+----------+
|       66 |
+----------+
```

However the Snipe-IT UI says there's only 19 - in fact many of the counts on the /locations page don't match the counts in the database.

I've run this:

```
php artisan snipeit:sync-asset-locations --output=all
```

And it has fixed some things but not everything.

Digging into the queries more I've found something else that's a bit odd. This query is running:

```
select * from `action_logs` where `item_type` = 'App\Models\Asset' and `action_logs`.`item_id` in ('1899', '1911', '1931', '1933', '1939', '1943', '1945', '1947','1949', '1951', '1953', '1955', '1957', '1959', '1961', '1963', '1965', '1967', '1969', '1971') order by `created_at` desc;
```

... and those assets are in Location ID 19, but that's only a small subset of what should be in Location 19.  I can't figure out why it's only looking at the logs for those assets and not others.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade
- Version of Snipe-IT you're running
4.1.6
- Version of PHP you're running
PHP 5.6.25
- Version of MySQL/MariaDB you're running
MySQL 5.1
- What OS and web server you're running Snipe-IT on
CentOS 6 (with HTTPD 2.4)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual extract of tarball
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

> [2017-12-01 13:26:07] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /opt/snipe-it-4.1.6/app/Models/Asset.php:131
> Stack trace:
> #0 /opt/snipe-it-4.1.6/app/Models/Asset.php(131): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/opt/snipe-it-4...', 131, Array)
> #1 /opt/snipe-it-4.1.6/app/Http/Transformers/AssetsTransformer.php(76): App\Models\Asset->availableForCheckout()
> #2 /opt/snipe-it-4.1.6/app/Http/Transformers/AssetsTransformer.php(16): App\Http\Transformers\AssetsTransformer->transformAsset(Object(App\Models\Asset))
> #3 /opt/snipe-it-4.1.6/app/Http/Controllers/Api/AssetsController.php(247): App\Http\Transformers\AssetsTransformer->transformAssets(Object(Illuminate\Database\Eloquent\Collection), 64)
> #4 [internal function]: App\Http\Controllers\Api\AssetsController->index(Object(Illuminate\Http\Request))
> #5 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
> #6 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('index', Array)
> #7 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\AssetsController), 'index')
> #8 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
> #9 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Routing\Route->run()
> #10 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #11 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #12 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
> #13 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #14 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #15 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Router.php(576): Illuminate\Pipeline\Pipeline->then(Object(Closure))
> #16 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Router.php(535): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
> #17 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Router.php(513): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
> #18 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
> #19 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
> #20 /opt/snipe-it-4.1.6/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #21 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
> #22 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #23 /opt/snipe-it-4.1.6/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #24 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
> #25 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #26 /opt/snipe-it-4.1.6/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #27 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
> #28 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #29 /opt/snipe-it-4.1.6/app/Http/Middleware/CheckForSetup.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #30 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
> #31 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #32 /opt/snipe-it-4.1.6/app/Http/Middleware/NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #33 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
> #34 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #35 /opt/snipe-it-4.1.6/app/Http/Middleware/ContentSecurityPolicyHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #36 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\ContentSecurityPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
> #37 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #38 /opt/snipe-it-4.1.6/app/Http/Middleware/ReferrerPolicyHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #39 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\ReferrerPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
> #40 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #41 /opt/snipe-it-4.1.6/app/Http/Middleware/XssProtectHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #42 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
> #43 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #44 /opt/snipe-it-4.1.6/app/Http/Middleware/FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #45 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
> #46 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #47 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #48 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
> #49 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #50 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #51 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
> #52 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #53 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #54 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
> #55 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
> #56 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
> #57 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
> #58 /opt/snipe-it-4.1.6/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
> #59 /opt/snipe-it-4.1.6/public/index.php(59): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
> #60 {main}  

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

https://HOSTNAME/locations/19

- If a stacktrace is provided in the error, include that too.

See above

- Any errors that appear in your browser's error console.

Error 500, backend problem.

- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.

Nope, data problem.

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

Exception is above.

- Include what you've done so far in the installation, and if you got any error messages along the way.

See troubleshooting I've done above.

- Indicate whether or not you've manually edited any data directly in the database

Not to fix this problem, as I don't know what to edit.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Is there anything unusual about the assets that belong to location 19? Are any of them deleted, etc?

**Comment by lukebigum** [comment]
I've figured it out . They've got status IDs that have been deleted.  Looks like something went and marked certain status labels we had as deleted, but it set the deleted_at flag to the same value as updated_at (I'm fairly certain we didn't create and delete four asset labels in the same second):

```
+----+----------------------+---------+---------------------+---------------------+---------------------+------------+---------+----------+------------------------------------------------------------------------------------------------------+-------+-------------+
| id | name                 | user_id | created_at          | updated_at          | deleted_at          | deployable | pending | archived | notes                                                                                                | color | show_in_nav |
+----+----------------------+---------+---------------------+---------------------+---------------------+------------+---------+----------+------------------------------------------------------------------------------------------------------+-------+-------------+
|  1 | Out for Diagnostics  |       1 | 2014-09-28 15:19:26 | 2014-11-19 17:24:35 | 2014-11-19 17:24:35 |          0 |       0 |        0 | NULL                                                                                                 | NULL  |           0 |
|  3 | Out for Repair       |       1 | 2014-09-28 15:19:26 | 2014-11-19 17:24:37 | 2014-11-19 17:24:37 |          0 |       0 |        0 | NULL                                                                                                 | NULL  |           0 |
|  5 | Broken - Not Fixable |       1 | 2014-09-28 15:19:26 | 2014-11-19 17:24:29 | 2014-11-19 17:24:29 |          0 |       0 |        0 | NULL                                                                                                 | NULL  |           0 |
|  7 | Lost/Stolen          |       1 | 2014-09-28 15:19:26 | 2014-11-19 17:24:32 | 2014-11-19 17:24:32 |          0 |       0 |        0 | NULL                                                                                                 | NULL  |           0 |
```

I've mass updated all the assets to not use those statuses, and I've un-deleted them for good measure.
