### ISSUE TITLE
Asset import stuck in "processing" with no import output once clicking on import button

### ISSUE THREAD

**Issue by amitchobdar** [snipe/snipe-it#4554]
![screenshot from 2017-12-02 12-37-14](https://user-images.githubusercontent.com/30799349/33512987-1868a1da-d760-11e7-9d48-856daf4f5d49.png)
![screenshot from 2017-12-02 12-37-40](https://user-images.githubusercontent.com/30799349/33512988-18a9309c-d760-11e7-8ad0-262770875a32.png)
![screenshot from 2017-12-02 12-38-05](https://user-images.githubusercontent.com/30799349/33512989-18ec92ba-d760-11e7-9da7-9e682404477e.png)
![screenshot from 2017-12-02 12-38-19](https://user-images.githubusercontent.com/30799349/33512990-196035a8-d760-11e7-8468-a49574557767.png)
![screenshot from 2017-12-02 12-38-42](https://user-images.githubusercontent.com/30799349/33512991-1b1838aa-d760-11e7-8280-33c5ff6ba6af.png)
![Uploading Screenshot from 2017-12-02 12-38-45.png…]()

#### Expected Behavior (or desired behavior if a feature request)

Asset should be import once CSV added successfully

-----

#### Actual Behavior
After added csv sucessfully we clicked on process but then import button but it is stucking in "Processing" from since last 2 hours with a single file entry.

-----

#### Please confirm you have done the following before posting your bug report:

- [ yes] I have enabled debug mode 
- [ yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- This is the fresh Installation
- v4.1.6 build 2963 (g83c8449) 
- 7.1.11-0ubuntu0.17.10.1
- Mysql Ver 14.14 Distrib 5.7.20
- Ubuntu Linux 17.10
- Manual Installation
- DEBUG - ON

Error: LOG.error: Symfony\Component\Debug\Exception\FatalThrowableError: Cannot instantiate abstract class App\Importer\Importer in /var/www/snipeit/app/Http/Requests/ItemImportRequest.php:41
Stack trace:
#0 /var/www/snipeit/app/Http/Controllers/Api/ImportController.php(100): App\Http\Requests\ItemImportRequest->import(Object(App\Models\Import))
#1 [internal function]: App\Http\Controllers\Api\ImportController->process(Object(App\Http\Requests\ItemImportRequest), '11')
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('process', Array)
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\ImportController), 'process')
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Routing\Route->run()
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))

Error: LOG.error: Symfony\Component\Debug\Exception\FatalThrowableError: Cannot instantiate abstract class App\Importer\Importer in /var/www/snipeit/app/Http/Requests/ItemImportRequest.php:41
Stack trace:
#0 /var/www/snipeit/app/Http/Controllers/Api/ImportController.php(100): App\Http\Requests\ItemImportRequest->import(Object(App\Models\Import))
#1 [internal function]: App\Http\Controllers\Api\ImportController->process(Object(App\Http\Requests\ItemImportRequest), '11')
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('process', Array)
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\ImportController), 'process')
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Routing\Route->run()
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))

- We are getting error on "Asset Import" page
- If a stacktrace is provided in the error, include that too.
- NS_ERROR_NOT_IMPLEMENTED: Component returned failure code: 0x80004001 (NS_ERROR_NOT_IMPLEMENTED) [nsIMIMEInfo.appendExtension]

- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo--- Import not allowed on demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs ---

- Include what you've done so far in the installation, and if you got any error messages along the way.
No error at installation time.
- Indicate whether or not you've manually edited any data directly in the database
No 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by EarlRamirez** [comment]
Are you able to import from CLI using the following command from the snipe-it directory
php artisan snipeit:import --verbose --item-type Asset path/to/your/file.csv, if it is an update add "--update."

**Comment by amitchobdar** [comment]
Dear Sir,

We are getting below error at the time of importing CSV from command line.

php artisan snipeit:import --verbose --item-type Asset
/home/snipeit/Downloads/assets-export-2017-12-02.csv
*Could not open input file: artisan*

*Rg*
*Amit*

**Comment by EarlRamirez** [comment]
you must be in the snipeit directory; it is usually located in /var/www/html/snipeit, the commands will only work in the directory

**Comment by amitchobdar** [comment]
Dear Sir,

Now file is imported, but still data is not visible.

/var/www/snipeit$ php artisan snipeit:import --verbose --item-type Asset
/home/snipeit/Downloads/assets-export-2017-12-04.csv
======= Importing Items from
/home/snipeit/Downloads/assets-export-2017-12-04.csv =========
All Items imported successfully!

Rg

**Comment by EarlRamirez** [comment]
I had a "similar" issue and the header was not the same as what was expected, e.g. I had model and it supposed to be Model Name, I am not saying that it may be the case with you but it's worth checking

**Comment by dpgatewood** [comment]
Your screenshots don't show you selecting 'Import Type' That helps the importer know what type of items you are importing. You are required to provide a Model Name, Category, Manufacturer and an Asset Tag for importing assets at minimum to avoid duplicate collision. You can designate a column header that might be not properly named by using the drop downs to assign the right value type. You're options on this drop down also are dependent on 'Import Type'.

**Comment by Technical-Angel** [comment]
I have the same issue with importing. I have been testing with a CSV that only contains the header row and one line of data. I've tried using the sample import CSV and I have tried creating a test device, exporting the data out (for the "correct" headers), changing the asset tag and importing it, and that hasn't helped. I verified I was selecting the import type and matching all column names (which the system couldn't match even though the names are the same).

**Comment by amitchobdar** [comment]
Dear Earl,

But why it is not working from front end, and is there any impact of space
in asset value.

Rg

On Dec 4, 2017 5:16 AM, "Earl Ramirez" <notifications@github.com> wrote:

Are you able to import from CLI using the following command from the
snipe-it directory
php artisan snipeit:import --verbose --item-type Asset
path/to/your/file.csv, if it is an update add "--update."

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/snipe/snipe-it/issues/4554#issuecomment-348830600>, or mute
the thread

**Comment by EarlRamirez** [comment]
I will have to see your CSV to give you a proper answer, I was reading the docs and it mentioned that large files can potentially cause an issue and it was recommended to use CLI for those large files. Based on your response, I will "assume" that the import was successful using the CLI.
