### ISSUE TITLE
I'm not able to see some fields in Consumables & Components after upgraded from Version v3.6.3 build 15 to Version v4.1.6

### ISSUE THREAD

**Issue by itims** [snipe/snipe-it#4557]
Hi,

I'm not able to see some fields in Consumables & Components after upgraded from Version v3.6.3 build 15 to Version v4.1.6 - build 2963. Below are the details.

Not able to see **Manufacturer, Model No.& Location** fields in Consumables
Not able to see **Serial & Location** fields in Components

Could you please help me to overcome the issue.

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - **Upgraded from Version v3.6.3 build 15 to Version v4.1.6 - build 2963**
- Version of Snipe-IT you're running - **v4.1.6**
- Version of PHP you're running - **5.6.32-1+ubuntu14.04.1+deb.sury.org+1**
- Version of MySQL/MariaDB you're running - **MySQL Server 5.5**
- What OS and web server you're running Snipe-IT on - **Ubuntu Server 14.04**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - **snipeit.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by abaalkh** [comment]
![screenshot_3](https://user-images.githubusercontent.com/2372747/33538272-5a0d47c2-d8d1-11e7-9a29-51417b74ae2e.png)

Have you selected them from the columns button?

**Comment by itims** [comment]
These fields are not listed in drop down list. 
But I can see these fields while creating new item.

**Comment by abaalkh** [comment]
I can confirm this as well. They do not appear in the components and consumables sections.
I thought you meant the Assets page.

**Comment by snipe** [comment]
Thanks for reporting this - I can confirm this issue. Working on a fix now.
