### ISSUE TITLE
Feature request: css improvement

### ISSUE THREAD

**Issue by ufficioIT** [snipe/snipe-it#4559]
#### Desired Behavior 
Hello! 
I would like to suggest a couple of css improvements , I think they would give a "less messy" and "more readable" sensation in the Asset table list.

1 - Add a `min-width:90px` to the checkin/checkout buttons in asset list (having buttons with different sizes looks a bit messy/confusing), i wrote 90px but it could be 75 or 80 or whatever you think it's better.

To test this just add `min-width:90px` to the  `btn.bg-maroon` and  `btn.bg-purple` class
```
.btn.bg-maroon, .btn.bg-purple{
 min-width:90px;
}
```
![snipe_min_width_screenshot](https://user-images.githubusercontent.com/33057507/33542517-a67c5c68-d8d3-11e7-80ac-9d2f5dd7a90c.jpg)

2 - Add a  `vertical-align:middle` to every td of asset list (when you add assets pictures the row gets bigger and the text goes to the top)

To test this just add 
```
.table > tbody > tr > td{
 vertical-align:middle;
}
```
![snipe_verticla_align_screenshot](https://user-images.githubusercontent.com/33057507/33542520-a9438d72-d8d3-11e7-8a6a-e8e2e10c7724.jpg)
-----
#### Both Combined
![snipe_both_screenshot](https://user-images.githubusercontent.com/33057507/33542524-ab317b08-d8d3-11e7-8676-79824370788b.jpg)

Maybe would be better to create some specific classes for affected buttons and tables just to have more control over where the style get applied.

-----

#### Actual Behavior
This is how it looks now

![snipe_orig_screenshot](https://user-images.githubusercontent.com/33057507/33542602-0d1852a6-d8d4-11e7-84ca-455d154ebb3c.jpg)

**Comment by snipe** [comment]
I think it looks cleaner with the top-alignment (versus middle aligned), but I'll add the button min-width. I agree that one looks better.
