### ISSUE TITLE
Installing snipe it in ubuntu shows Symfony \ Component \ HttpKernel \ Exception \ NotFoundHttpException

### ISSUE THREAD

**Issue by gauthamrajd** [snipe/snipe-it#456]
![image](https://cloud.githubusercontent.com/assets/8874602/5738922/4fbdab98-9c18-11e4-8dc4-166be9cb92fa.png) 

I installed snipeit successfully and changed the permission but when i try to access the application it is throwing the above mentioned error (for reference see the image).

I use ubuntu 12.04,apache2.2,php 5.4,phpmyadmin and i have enabled rewrite module and php mcrypt.

Is there anything i need to run anymore.....

**Comment by HinchK** [comment]
does it work if you add /index.php to the end (e.g. http://localhost:8000/index.php)?   the error suggests a route-matching error.  unless you've customized some of the laravel stuff, it could be a  web server or .htaccess setting issue

**Comment by snipe** [comment]
Hi @gauthamrajd - if you open the `.htaccess` and add some junk text into it, does the error change to a 500 internal server error? If it doesnt, that usually means that your `mod_rewrite` in Apache isn't configured correctly.
