### ISSUE TITLE
Add Support to Sync any kind of user information from LDAP

### ISSUE THREAD

**Issue by larsuhartmann** [snipe/snipe-it#4562]
#### Expected Behavior (or desired behavior if a feature request)

It would be nice to be able to sync all the various user info from LDAP for Example:

- manager
- Employee ID
- Phone Number

i guess you could just implement a "mapping" function where you can map snipe-it userfields to LDAP attributes.

**Comment by CronKz** [comment]
+1
An "Optional Section" which expands down on clicking. This Section could also include the exsisting fields which are NOT required based on the docs [https://snipe-it.readme.io/docs/ldap-sync-login](url)
A Button "Add Custom Flied" which then shows:
EditBox1("LDAP Attribute") + Text " map to field " + EditBox2("Any 'Person' Field")

**Comment by asuman1179** [comment]
+1 This is a great idea for sure!

**Comment by snazy2000** [comment]
Would be nice to sync Department and Manager otherwise its all manual and will never get filled in..

**Comment by snazy2000** [comment]
also profile pic would be goood

**Comment by jjangmoo** [comment]
+1 
This is what I need. 
I'd also like to sync department and title.

**Comment by snazy2000** [comment]
I did some work on this today, got it in a working state for the department, and i also wanted to sync location based on the physical office name not a OU.

https://github.com/snazy2000/snipe-it/commit/01aaed68743b0a781e8c88ed5fa5734b5db4943f

Let me know what you think @snipe

**Comment by stevenrathel** [comment]
+1 Would be a huge help.

**Comment by xarly** [comment]
+1, at least the fields that already has Snipe in user profile:

Title - title
Department - department
Phone - telephoneNumber
Employee No. - employeeNumber

**Comment by snipe** [comment]
Duplicate of #4562

**Comment by CronKz** [comment]
@snipe You marked this Issue as duplicate... of itself 😄
