### ISSUE TITLE
CSV import - no location_ID

### ISSUE THREAD

**Issue by schmidiij** [snipe/snipe-it#4563]
#### Expected Behavior (or desired behavior if a feature request)

If i import a .csv with all attributes, the import works. **BUT** the location will be not set correctly.
in the DB: it's say about the asset: location_ID NULL

---------------------
Location:
![grafik](https://user-images.githubusercontent.com/29889802/33553304-77c0f896-d8f8-11e7-8370-b70ee35330b9.png)

---------------------

Import-View:
![grafik](https://user-images.githubusercontent.com/29889802/33553328-912d72c8-d8f8-11e7-8708-6d2033b67fd2.png)

---------------------
After Import:
![grafik](https://user-images.githubusercontent.com/29889802/33553371-b950149a-d8f8-11e7-83fe-45df313090cd.png)

---------------------
it's see correctly but if i click the location: it's empty
![grafik](https://user-images.githubusercontent.com/29889802/33553390-d6a36a7e-d8f8-11e7-9a6a-d6daf4919319.png)

---------------------
and the DB:
![grafik](https://user-images.githubusercontent.com/29889802/33553434-055e1ba2-d8f9-11e7-85fc-366566addaec.png)

---------------------

and when i make a export it's say:
![grafik](https://user-images.githubusercontent.com/29889802/33553671-f1ef7132-d8f9-11e7-981b-db4c34111ae5.png)

is this normal?
-----

#### Actual Behavior

Not a correctly (?) import

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 

New: Installation is from 04.12

- Version of Snipe-IT you're running
4.1.6

- Version of PHP you're running
7.1.9

- Version of MySQL/MariaDB you're running
MySQL - 5.7.19

- What OS and web server you're running Snipe-IT on
Windows Server 2012 R2 - WAMP64

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
WAMP Installation-Guide

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

[Test-Import.xlsx](https://github.com/snipe/snipe-it/files/1527060/Test-Import.xlsx)

**Comment by dpgatewood** [comment]
Use literal location variable, not the DB/programs 'id'
Say I have a location that is "San Francisco Office"
That is the value the importer is looking for.

**Comment by dpgatewood** [comment]
And also 'Default Location' and 'Location' are two different settings. 'Default Location' is the fall back variable anytime asset is not assigned or deployed, whilst the Location can dictate its current location.

**Comment by schmidiij** [comment]
Sorry but i don't understand the problem?
i have in the .csv under "Location" --> "Lagerraum"
after the import, under Settings -> the Location is empty

is the import "location" not the this setting?
![grafik](https://user-images.githubusercontent.com/29889802/33593549-2d713768-d990-11e7-9b8f-1b68e4565c49.png)

**Comment by schmidiij** [comment]
ahh ok, i see the problem...

Can i import a asset directly to a location?

Like this:
![grafik](https://user-images.githubusercontent.com/29889802/33601558-e6cb219e-d9ac-11e7-8de2-1a2ff2d9f4dd.png)

**Comment by dpgatewood** [comment]
CSV example
Asset Tag, Model Name, Serial Number, Location, Category
2127809, PSC67N845, DP676-7654, San Francisco Office, Printer
2127810, LJ4560, AF65Z-244, New York Distribution Center, Printer
2127811, 2359LCD, VS5556178, San Francisco Office, Monitor

**Comment by schmidiij** [comment]
[Test.xlsx](https://github.com/snipe/snipe-it/files/1534176/Test.xlsx)

i create a test.csv (attachment) and this is the same;
![grafik](https://user-images.githubusercontent.com/29889802/33648563-d5695764-da5a-11e7-8424-14464cdc88c1.png)

after the import i click of San Francisco Office and this is emtpy;
![grafik](https://user-images.githubusercontent.com/29889802/33648599-f4dd20d0-da5a-11e7-8f2a-87ad662a7a59.png)

How i can import a asset directly to a location?
