### ISSUE TITLE
Hi Snipe-IT Support, may i request to enable the search method if i need to find the purchase date with the specific date purchase of the items. I tried on your demo website but its not working to search the date of items on purchase date.

### ISSUE THREAD

**Issue by paulo1624** [snipe/snipe-it#4566]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help
![image](https://user-images.githubusercontent.com/32555803/33559687-9510a9e6-d948-11e7-9b90-5a2ed4b47c0f.png)

No matching records found. But the date i searching is on the list of assets. Thank You and will appreciate your help.

**Comment by snipe** [comment]
Dates are stored as YYYY-MM-DD, so you have to search for them that way

**Comment by paulo1624** [comment]
I already used that way. but there is no matching records if i looking for the date of item on purchase date.
![image](https://user-images.githubusercontent.com/32555803/33576121-c6ba3c4c-d979-11e7-87bd-c006b29ae3db.png)

**Comment by paulo1624** [comment]
![image](https://user-images.githubusercontent.com/32555803/33576160-ea4e9928-d979-11e7-96ff-804dc2c72775.png)

**Comment by snipe** [comment]
Yep, seems you're right - that did get left out somehow. Fix is coming.

**Comment by Chris-2515** [comment]
It looks like this is happening to me as well. I was running 4.1.16, but I upgraded to v4.2.0. If I type the year directly in the search box it doesn't bring back any results, but if I do an advanced search with the year it will filter it properly.
