### ISSUE TITLE
Force: Change password on first login

### ISSUE THREAD

**Issue by JamLaMin** [snipe/snipe-it#4567]
When i create a user i need to privide or generate a password.

What i need...
A function like: Force the user to change their password at first login

**Comment by redeuxx** [comment]
I was just about to request this. This would be great. As a sys admin, I like creating an easy password then forcing users to change the password to something I don't know.

**Comment by JamLaMin** [comment]
Hello,
Can you tell me whats the status of this change?

**Comment by redeuxx** [comment]
Still waiting on this. It's a pretty standard feature in many apps and systems.

**Comment by snipe** [comment]
@redeuxx no one is currently working on this feature, that I'm aware of.
