### ISSUE TITLE
Custom Asset Report Converts Some Characters to HTML Entities in CSV

### ISSUE THREAD

**Issue by KeenRivals** [snipe/snipe-it#4568]
#### Expected Behavior (or desired behavior if a feature request)

1. Create user, ``First Mc'Name``.
2. Checkout asset to ``First Mc'Name``.
3. Run custom asset report, which includes "Assigned To" field.
4. See ``First Mc'Name`` in the resulting CSV report.

-----

#### Actual Behavior

1. Create user, ``First Mc'Name`.
2. Checkout asset to ``First Mc'Name``.
3. Run custom asset report, which includes "Assigned To" field.
4. See ``First Mc&#039;Name`` in the resulting CSV report.

I'd bet that other "dangerous" characters are escaped as well as part of export. I can confirm that ``Amper& Ampersand`` becomes ``Amper&amp; Ampersand``.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:
- Upgraded snipe, 4.1.6.
- PHP 7.0.19-1/Debian 9
- Issue is reproducible in demo.

**Comment by snipe** [comment]
Run a backup and then run `php artisan snipeit:unescape`

**Comment by KeenRivals** [comment]
I ran ``php artisan snipeit:unescape`` and it didn't complain about anything, but the Custom Asset Report is still showing the escaped characters. I ran a fresh backup and I can see in the sql export that they're escaped there too.

I re-checked the demo since it's 4.1.7 now and it looks like the behavior is still reproducible there.

**Comment by KeenRivals** [comment]
I can still reproduce this issue in the demo site, which is 4.6.6. ``php artisan snipeit:unescape`` doesn't seem to fix the data in the DB, and escaped data still ends up in the DB. Reproduction steps for the demo site:

1. Create new user, first name *Person*, last name *O'Namey*, username ponamey.
1. Checkout asset to ponamey.
1. Run custom asset export with all assets. 
1. Observe that ponamey's name in the export's *Checked Out* field is Person *O\&#039;Namey*

Interestingly, I found that this only happens if you use the custom export function. If you hit the download CSV button from the asset list, you get *O'Namey* in your export as you should.

I can "fix" the Custom Export CSV if I go into app/Http/Controllers/ReportsController.php and change line 606 from:

```php
$row[] = ($asset->checkedOutToUser() && $asset->assigned) ? e($asset->assigned->getFullNameAttribute()) : ($asset->assigned ? e($asset->assigned->display_name) : '');
```

to:

```php 
$row[] = ($asset->checkedOutToUser() && $asset->assigned) ? htmlspecialchars_decode($asset->assigned->getFullNameAttribute(),ENT_QUOTES) : ($asset->assigned ? e($asset->assigned->display_name) : '');
```

I'm not confident that's the ideal place to do it (or if doing so is even a good idea), or I'd consider making a PR. If the data *should* be escaped in the DB, then we probably need to unescape it somewhere when dumping to CSV. If it should not be escaped in the DB, then ``snipeit:unescape`` might need to be fixed, along with figuring out how the escaped data got into the db.

**Comment by snipe** [comment]
The data isn't being stored encoded in the database, which is why the unescape command isn't working - there's nothing for it to do.

<img width="205" alt="screen shot 2018-12-12 at 7 09 28 pm" src="https://user-images.githubusercontent.com/197404/49913177-81465680-fe41-11e8-959f-dc0718b8b931.png">

**Comment by KeenRivals** [comment]
I have HTML entities (single quotes) in my DB (some portions censored with **):

	MariaDB [snipeit]> select first_name,last_name from users where first_name like '%&%' or last_name like '%&%';
	+-----------------+----------------+
	| first_name      | last_name      |
	+-----------------+----------------+
	| *************** | O&#039;Hara    |
	| *************** | O&#039;Connor  |
	| D&#039;Andre    | ************** |
	|  -some snipped- | -some snipped- |
	+-----------------+----------------+
	24 rows in set (0.00 sec)



If I add Person O'Namey via the Create User flow in the webapp I see that it's not escaped in the DB. These problematic users were all created via Active Directory LDAP sync. The ``snipeit:unescape`` command isn't fixing them because [html_entity_decode](https://secure.php.net/manual/en/function.html-entity-decode.php) doesn't touch quotes by default and needs the ``ENT_QUOTES`` flag to do so. After fixing that (#6506 ), when I run ``snipeit:unescape``, the DB is clean. The next problem is that when LDAP sync runs again, it pushes escaped data into the DB.

I looked around in app/Console/Commands/LdapSync.php but I'm not seeing an escape function jump out at me. I'm not sure where the escaping could be performed. I'm wondering if this could be related to #2282 but I'm not sure.

**Comment by KeenRivals** [comment]
I installed v5 beta 1.0 on a test server today. After running an LDAP sync I don't see any escaped data in the DB anymore. Looks like it is fixed in v5. 👌
