### ISSUE TITLE
Request: Bulk Actions

### ISSUE THREAD

**Issue by mdench** [snipe/snipe-it#457]
I did have a look through but didn't seem to find anything related to this but feel free to point me in the right direction.

Are there any plans to add multiple select options to assets?

We tend to install and recycle around 200 pcs a year. It would be nice if you could create a model or location which when viewed it listed all the assets linked to that item and then you could perform a bulk action such as change location or change the status of the item from deployed to recycled?

Hope that makes sense

**Comment by rp-tech** [comment]
+1 for bulk actions

**Comment by snipe** [comment]
That does make sense, and we'll definitely consider it.

**Comment by rp-tech** [comment]
bulk options for users would be nice as well - e.g. the ability to mass activate / de-activate, as well as mass delete users and mass reset passwords.
