### ISSUE TITLE
Updating from version 3.0 to version 4.1.6 on Windows

### ISSUE THREAD

**Issue by nfc2512** [snipe/snipe-it#4573]
I am looking for clarification on what I need to do in order to upgrade the Snipe files.  I have downloaded and extracted the Zip File.  When I look at the instructions below, it only references what to do for Linux users.  Do you basically copy the contents of the zip into the program directory overwriting the current files?

Step 5: Download/clone the new release 
Do this the same way you did when you originally set Snipe-IT up. If you used git clone, you can simply do a git pull to grab the latest from the master branch.

Thank you very much for your help,

Galen

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  Upgrade
- Version of Snipe-IT you're running:  Currently 3.0 trying to upgrade to 4.1.6
- Version of PHP you're running: Currently 5.6.24 - Upgrading to 7.2.0
- Version of MySQL/MariaDB you're running: MySQL 5.5
- What OS and web server you're running Snipe-IT on: Server2012R2  IIS7.0
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Install.sh originally
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
> Do you basically copy the contents of the zip into the program directory overwriting the current files?

Yes. Though we really recommend switching to a Git setup instead.
