### ISSUE TITLE
Location (custom fields)

### ISSUE THREAD

**Issue by gabegibson** [snipe/snipe-it#4574]
#### Expected Behavior (or desired behavior if a feature request)
We have a unique "location code" assigned to each location and the owner is not a person but an organization.  Would like to add common attributes to Location to address these requirements.  

-----

#### Actual Behavior
Custom Fields seems to only apply to assets.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
So I’m clear, you’re looking for custom fields on locations, is that right? That’s definitely not on our short term roadmap at this time.

**Comment by gabegibson** [comment]
Yes, I'm looking for custom fields on location and I now see the feature request but a bummer it is not on the short term roadmap.

**Comment by snipe** [comment]
Can you just include the location code in the location name?

**Comment by gabegibson** [comment]
My current plan is to use the zip code field for location code, address for the description (office, closet, classroom, etc.), and city as the "company". 

Unless I'm missing something the only way I see to batch upload locations is via the API, no?

**Comment by snipe** [comment]
@gabegibson that's correct - only batching for locations (currently) is via API

**Comment by pkmnct** [comment]
I could really use this feature as well.

We have several layers of locations:
1. Physical Location (Address)
2. Room
3. Storage Rack
4. Storage Bin

Being able to store extra data, such as room number, storage bin type/color/number, and other attributes would be very nice!

**Comment by SonGokussj4** [comment]
Is there any progress with this issue? We are starting to use snipe-it and we would love to have more fields for additional info. Right now we are thinking to input our info into Address2 field because where else.

**Comment by pkmnct** [comment]
Noticed this was closed, was there any resolution to this?
