### ISSUE TITLE
upgrade frome Snipe-IT v2.1.0-55 to latest version

### ISSUE THREAD

**Issue by mariomasa** [snipe/snipe-it#4575]
I follow the steps, but I'm stuck here;

**git clone https://github.com/snipe/snipe-it your-folder**

I set the username and the password and I get this error
_error: The requested URL returned error: 403 while accessing https://github.com/snipe/snipeit/info/refs
-bash: error:: command not found_

**Comment by snipe** [comment]
When you type `git version` at the command line, what does it say?

**Comment by mariomasa** [comment]
git version 1.7.10.4

**Comment by mariomasa** [comment]
running this commands;
wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh
chmod 744 install.sh
./install.sh

I have this answer;
Unsupported version. Version found: 7.11

**Comment by snipe** [comment]
You should probably not use install.sh to upgrade - instead use `php upgrade.php`

**Comment by snipe** [comment]
Ah, wait, sorry - you're upgrading from 2.x (yikes!). What's your upgrade plan here? Create a new Snipe-IT directory and pull uploads over, or...?
