### ISSUE TITLE
Licenses Check-Out

### ISSUE THREAD

**Issue by kd2067** [snipe/snipe-it#4576]
#### Expected Behavior (or desired behavior if a feature request)
Non super user with permissions to check out licenses to be able to check out
(what you expect to happen goes here)
I expect user with permissions to check out licenses to be able to do so
-----

#### Actual Behavior
Unable to check out licenses
(what actually happens goes here)
Clicking on the check out button results in "Sad Panda". Going into the software you want the check out button is not present on the seat line levels
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running - tried both 4.1.6 and 4.1.7
- Version of PHP you're running - latest
- Version of MySQL/MariaDB you're running - latest
- What OS and web server you're running Snipe-IT on - Ubuntu Xenial - Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - licenses
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. - no just sad panda
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo. - no
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. - No errors, it was a base install creted 2 users and 1 group and 1 software with 45 seats
- Indicate whether or not you've manually edited any data directly in the database - no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
This should be fixed on develop now

**Comment by kd2067** [comment]
Pardon?  Is this fixed or in development?  If it is fixed why do I still have this issue.  Is there something I need to do?  If so what is it?

**Comment by snipe** [comment]
> This should be fixed on develop now

That means it's on the develop branch and will be in the next release.

**Comment by Jarli01** [comment]
@kd2067 you would have to switch to the develop branch and upgrade your installation to pull down these changes. 

Otherwise, just wait until they are in "master" and update then.
