### ISSUE TITLE
Feature Request: Bulk Asset Creation

### ISSUE THREAD

**Issue by faxesystem** [snipe/snipe-it#4579]
#### Expected Behavior (or desired behavior if a feature request)

We are often getting ten monitors or laptops of the same model at once. So it would be nice to create like 10 assets at once with the same Model, Manufacturer, Supplier, Order Number etc. and just change the serial number afterwards. This would save useless mouse work ;)

-----

#### Actual Behavior

For every asset you have to click on "New Asset" and fill in Model, Supplier, Manufacturer etc. This is time consuming when it's always the same device just with a different serial number.

-----

**Comment by CronKz** [comment]
In addition a list where you can add the Serials while creating for example 10 Assets, would result in 10 fields for the serials if you want to add them straightaway while creating them.

**Comment by Diniver** [comment]
That would be nice. But currently _clone_ is doing the same thing.

**Comment by CronKz** [comment]
@Diniver Well not really... Cloning only gives you one clone. But what if you need 20?

**Comment by grimstoner** [comment]
This would be useful in one of the use cases in #3 of https://github.com/snipe/snipe-it/issues/4488

**Comment by 08solsticegxp** [comment]
Just a thought on this one. You could possibly have a way to where you can start with a template so everything except the serial number is filled out. (maybe a save button with normal function, and a save&add button that will save and reload the page with everything still populated except the serial number.)

**Comment by ThaSherm** [comment]
I would love to see a Purchase Order integration as @DanPrs mentioned in #3394 , especially @grimstoner suggestions in #4488 and @faxesystem  mentioned here as well! Currently migrating from an ancient version of ASAP Passport to Snipe-IT and loving it, but I need the ability to enter large quantities of assets within Snipe along with their Purchase Order Number, PDF of the Invoice, and all relevant information about the assets.

**Comment by xv01dx** [comment]
What ThaSherm says is also what we desperately need in order to move over to Snipe-IT from my current homebrew Access database.

**Comment by grimstoner** [comment]
+1

**Comment by faxesystem** [comment]
Bad stale bot.

**Comment by esspeecy410** [comment]
+1 for this - we use Snipe to track POS terminals which can be allocated and configured in batches of 20 or 30 at a time, so either bulk asset creation with lines of serial numbers as noted above or some sort of template would be great.

**Comment by Techno11** [comment]
+1 for this. I work for a school where currently we use google sheets (ugh) to manage inventory. We routinely receive bulk orders of items such as Chromebooks and Chromeboxes, and would be tedious to have to add each one manually. I would love to present this to my team, but with no effective way to bulk add, and bulk adding is pretty much all we do, they would decline it in an instant.  Something along the lines of being able to continuously scan barcodes, while the app creates new items for each.

**Comment by snipe** [comment]
The way we're going to be handling this in v5 is to treat asset models a little more like accessory "models", where you'll be able to create X number of a model at one time.

**Comment by darkpixel** [comment]
Bump.  This is still an issue.

**Comment by xv01dx** [comment]
^

**Comment by Techno11** [comment]
Still a request from me

**Comment by acerspyro** [comment]
Stale bot needs to be way more lenient.

**Comment by migaspar** [comment]
Bump. Would be an awesome feature. Adding $x items which differ on the serial number only sucks a lot. (Yes, I'm using the clone function already.)

**Comment by snipe** [comment]
As I mentioned earlier in this thread, this is already in the upcoming v5.

**Comment by esinglet** [comment]
Wow. I can't believe this feature isn't yet added. This is "stop taking advice from the people I have consulted who recommended this software" level of deal breaker. The database I threw together in an evening could handle this.

**Comment by esinglet** [comment]
Which will come when? 

I don't understand how a single serious organization could be using this. Adding a single order of new technology would take hours...

**Comment by jhilgenberg** [comment]
I still cannot find this feature but it's still a thing we would appreciate.

**Comment by mikeroq** [comment]
When creating a new asset:
![image](https://user-images.githubusercontent.com/55674383/181509905-6b63e2a9-4739-4b2a-9f21-ed931648cf0f.png)
Click on the plus next to asset tag. It will give you additional asset tag / serial numbers to enter.
![image](https://user-images.githubusercontent.com/55674383/181510010-e044f2fa-7cb6-45ef-a232-15aa3baca371.png)
