### ISSUE TITLE
Permission denied in ~/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:84

### ISSUE THREAD

**Issue by jamesonp** [snipe/snipe-it#458]
Hello,

I'm getting this error:

    Error in exception handler: The stream or file "/var/www/assets.vms.internal.jamesonp.com/app/storage/logs/log-apache2handler-2015-01-15.txt" could not be opened: failed to open stream: Permission denied in /var/www/assets.vms.internal.jamesonp.com/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:84

My permissions:

![permissions](http://i.imgur.com/MwwzRkl.jpg)

Apache service ps aux:

![apache](http://i.imgur.com/JGOP5co.jpg)

Permissions on ~/app/storage/:

![storage](http://i.imgur.com/2al4dyJ.jpg)

Any ideas?

**Comment by uberbrady** [comment]
The ```app/storage/``` directory **itself** needs to be writable by apache - apache is trying to create a 'logs' directory under it, and then a file in that new directory.

**Comment by jamesonp** [comment]
It was.

So the solution was to disable selinux.  So for anybody running CentOS 7..disable selinux and save yourself from hours of frustration.

**Comment by snipe** [comment]
You shouldn't have to disable SElinux. I don't know what distro you're using, but something like `httpd_sys_rw_content_t` should enable apache to write to that directory. 

http://www.serverlab.ca/tutorials/linux/web-servers-linux/configuring-selinux-policies-for-apache-web-servers/
