### ISSUE TITLE
Feature Request - The ability to assign Consumables to assets

### ISSUE THREAD

**Issue by cslucian** [snipe/snipe-it#4582]
#### Expected Behavior (or desired behavior if a feature request)

In our company we order print cartridges for 5 shared printers. I would be great if I could check-out cartridges to printers ( assets) not to a user.

-----

#### Actual Behavior

Consumables can be assigned only to users

-----

Thank You,

**Comment by TonisOrmisson** [comment]
Or eg batteries to various devices ....

**Comment by amferreira** [comment]
+1 👍

**Comment by wilsonlspacheco** [comment]
+1 👍

**Comment by Mynty100** [comment]
+1 (y)

**Comment by snipe** [comment]
Duplicate of #1538. (I'm using #1538 as the reference since it seems to be the first time this feature was suggested.)
