### ISSUE TITLE
Import isssue

### ISSUE THREAD

**Issue by aminaabdi** [snipe/snipe-it#4587]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)
I have tried to import asset list but i get the 100% sign with an orange color instead of green and nothing gets imported. Why??
![import](https://user-images.githubusercontent.com/33921541/33701904-14dd1638-db32-11e7-839f-6e5d8571bfbf.JPG)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
yes, and i have got no error message.
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
yup
-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
its not fresh neither upgraded version.
- Version of Snipe-IT you're running
all i know is its last year version
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Asset import option is the problem
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
500 (Internal Server Error)
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by glureau** [comment]
> all i know is its last year version

You can see the version on the bottom right of every pages.

**Comment by aminaabdi** [comment]
Version of Snipe-IT you're running
- v4.0.3
What OS and web server you're running Snipe-IT on
-Apache
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
-manual installation
If you're getting an error in your browser, include that error
-no error message
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
-the import page and when uploading excel file.
If a stacktrace is provided in the error, include that too.
-nope
Any errors that appear in your browser's error console.
-500 (Internal Server Error)
Confirm whether the error is reproduceable on the demo.
-did not understand
Include any additional information you can find in app/storage/logs and your webserver's logs.
Include what you've done so far in the installation, and if you got any error messages along the way.
-well, i have followed the instruction during the setup and got the "Whoops!! something went wrong" error but was able to solve it.
Indicate whether or not you've manually edited any data directly in the database
-nope

**Comment by aminaabdi** [comment]
still waiting for an answer

**Comment by EarlRamirez** [comment]
@aminaabdi for @snipe or any member of the community to help you, you will need to provide details so that you can get the support you require, taking into consideration that @snipe is busy with numerous issues, bug fixes, feature requests and most importantly, Snipe-IT paid customers. 

Did you try importing from CLI, how big is the file that you are trying to import?

**Comment by aminaabdi** [comment]
@EarlRamirez the file size is not big at all as only one row was filled with information.
Can u tell me how can i import using cli??

**Comment by glureau** [comment]
ONE row 👍 
That could be the kind of super interesting information.
Usually we expect a csv to have a header line with the column names, and the following line contains data. For sure it should not stuck, so it's a bug, but in your case, you should probably add a header line in your file and retry the import. (If you don't know how, or even if you do, please share the file.)

**Comment by aminaabdi** [comment]
@glureau wat do u mean by u need to add header line??The excel sample csv already has the header title.

**Comment by glureau** [comment]
@aminaabdi please **share your CSV file**

**Comment by aminaabdi** [comment]
![csv](https://user-images.githubusercontent.com/33921541/33923700-a75109c4-dfe3-11e7-92c6-1bacfe666bca.JPG)

**Comment by aminaabdi** [comment]
@glureau couldn't upload the csv file because the upload doesn't support the csv file format

**Comment by glureau** [comment]
You could copy paste the content, especially for 3 lines of text ;) (if you still can, it can be interesting to reproduce the case, thanks)

So here I'm seeing 3 lines, not juste one, and the first row, which contains 'Name", 'Email', etc. is what I referred as header previously, so I presume the data is ok.
Can you get the server error logs?

**Comment by dmeltzer** [comment]
This usually means that the file was unable to be uploaded, not an issue with the contents of the file itself.  I'd check the javascript console to see if you see any errors, and make sure storage/private_uploads/imports/ is writable and that your file exists in there.
