### ISSUE TITLE
add to documentation: send email from redhat  based OS, selinux configuration

### ISSUE THREAD

**Issue by alejojo** [snipe/snipe-it#4588]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

send email

#### Actual Behavior

while trying to send email I got rejected. Checking the logs I saw this:

```
...
[2017-12-07 15:34:32] production.ERROR: Swift_TransportException: Connection could not be established with host masked_ip [Permission denied #13] in /var/www/html/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:268
...
```
#### Solution:

I installed `policycoreutils-python` and ran `audit2allow -w -a` which thrown:

```
type=AVC msg=audit(1512628596.912:279): avc:  denied  { name_connect } for  pid=1607 comm="httpd" dest=25 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:smtp_port_t:s0 tclass=tcp_socket
	Was caused by:
	One of the following booleans was set incorrectly.
	Description:
	Allow httpd to can network connect

	Allow access by executing:
	# setsebool -P httpd_can_network_connect 1
	Description:
	Allow httpd to can sendmail

	Allow access by executing:
	# setsebool -P httpd_can_sendmail 1
	Description:
	Allow nis to enabled

	Allow access by executing:
	# setsebool -P nis_enabled 1
```

After I ran this I was able to send email and keep selinux enforced:
```
setsebool -P httpd_can_network_connect 1
setsebool -P httpd_can_sendmail 1
```

**Comment by snipe** [comment]
Hi @alejojo - do you think you could use the `suggest an edit` link on the docs to propose that change? https://snipe-it.readme.io/docs/linuxosx#section-notes-on-selinux

**Comment by alejojo** [comment]
done, cheers.

**Comment by snipe** [comment]
Merged - thanks! 
![community-thankyou](https://user-images.githubusercontent.com/197404/33709761-461eba42-daf3-11e7-8d4a-7690c20e2dfe.gif)
