### ISSUE TITLE
error when I search Chinese key word

### ISSUE THREAD

**Issue by zsy5172** [snipe/snipe-it#4590]
#### Expected Behavior (or desired behavior if a feature request)
I searched for Chinese keyword in the asset page,
(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)
No matching records found，and return error 500 in browser's error console

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
v4.1.8-pre - build 3034 (master) 
- Version of PHP you're running
7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running
5.7.20-0ubuntu0.16.04.1
- What OS and web server you're running Snipe-IT on
ubuntu 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
git
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
`{"status":"error","messages":"An Error has occured! SQLSTATE[HY000]: General error: 1271 Illegal mix of collations for operation 'like' (SQL: select count(*) as aggregate from `assets` left join `users` as `assets_users` on `assets_users`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\\Models\\User left join `locations` as `assets_locations` on `assets_locations`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\\Models\\Location left join `assets` as `assigned_assets` on `assigned_assets`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\\Models\\Asset inner join `status_labels` as `status_alias` on `status_alias`.`id` = `assets`.`status_id` and `status_alias`.`archived` = 0 where (exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `categories` where `models`.`category_id` = `categories`.`id` and (`categories`.`name` LIKE %\u670d\u52a1\u5668% or `models`.`name` LIKE %\u670d\u52a1\u5668% or `models`.`model_number` LIKE %\u670d\u52a1\u5668%) and `categories`.`deleted_at` is null)) or exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `manufacturers` where `models`.`manufacturer_id` = `manufacturers`.`id` and (`manufacturers`.`name` LIKE %\u670d\u52a1\u5668%) and `manufacturers`.`deleted_at` is null)) or (exists (select * from `status_labels` where `assets`.`status_id` = `status_labels`.`id` and `status_labels`.`name` LIKE %\u670d\u52a1\u5668% and `status_labels`.`deleted_at` is null)) or (exists (select * from `suppliers` where `assets`.`supplier_id` = `suppliers`.`id` and `suppliers`.`name` LIKE %\u670d\u52a1\u5668% and `suppliers`.`deleted_at` is null)) or (exists (select * from `companies` where `assets`.`company_id` = `companies`.`id` and `companies`.`name` LIKE %\u670d\u52a1\u5668%)) or (exists (select * from `locations` where `assets`.`rtd_location_id` = `locations`.`id` and `locations`.`name` LIKE %\u670d\u52a1\u5668% and `locations`.`deleted_at` is null)) or (`assets_users`.`first_name` LIKE %\u670d\u52a1\u5668% or `assets_users`.`last_name` LIKE %\u670d\u52a1\u5668% or `assets_users`.`username` LIKE %\u670d\u52a1\u5668% or `assets_locations`.`name` LIKE %\u670d\u52a1\u5668% or `assigned_assets`.`name` LIKE %\u670d\u52a1\u5668%) or `assets`.`name` LIKE %\u670d\u52a1\u5668% or `assets`.`asset_tag` LIKE %\u670d\u52a1\u5668% or `assets`.`serial` LIKE %\u670d\u52a1\u5668% or `assets`.`order_number` LIKE %\u670d\u52a1\u5668% or `assets`.`purchase_date` LIKE %\u670d\u52a1\u5668% or `assets`.`purchase_cost` LIKE %\u670d\u52a1\u5668% or `assets`.`notes` LIKE %\u670d\u52a1\u5668% or `assets`.`_snipeit_mac_address_1` LIKE %\u670d\u52a1\u5668%) and `assets`.`deleted_at` is null)","payload":null}`
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
/hardware
search Chinese keyword
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
Yes, It can reproduce in the demo site
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by Gelob** [comment]
Can you provide an example character? I tried this on the demo with 漢字 and 汉字 and got no errors.

**Comment by zsy5172** [comment]
@Gelob That's weird, I can reproduce it. By the way, I use chrome 62.0.3202.94 x64.
![123](https://user-images.githubusercontent.com/4435992/33802597-aed602ce-ddb5-11e7-9a92-d0e62db96ee6.gif)

**Comment by linglongtong** [comment]
@snipe I met the same error when I tested in the demo, please help.
I set first name as "张晓晖", last name as "Zhang Xiaohui".
When I searched "张晓晖", it returned "No matching records found"; and when I searched "Zhang Xiaohui", it is OK.

![image](https://user-images.githubusercontent.com/23185284/34357456-49672948-ea82-11e7-8f25-c32e303e01cc.png)

![image](https://user-images.githubusercontent.com/23185284/34357474-6f06f7fa-ea82-11e7-878b-16b9c691cfef.png)

the error code:

SQLSTATE[HY000]: General error: 1271 Illegal mix of collations for operation 'like' (SQL: select count(*) as aggregate from `assets` left join `users` as `assets_users` on `assets_users`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\Models\User left join `locations` as `assets_locations` on `assets_locations`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\Models\Location left join `assets` as `assigned_assets` on `assigned_assets`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\Models\Asset inner join `status_labels` as `status_alias` on `status_alias`.`id` = `assets`.`status_id` and `status_alias`.`archived` = 0 inner join `models` as `asset_models` on `assets`.`model_id` = `asset_models`.`id` where (exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `categories` where `models`.`category_id` = `categories`.`id` and (`categories`.`name` LIKE %张晓晖% or `models`.`name` LIKE %张晓晖% or `models`.`model_number` LIKE %张晓晖%) and `categories`.`deleted_at` is null)) or exists (select * from `models` where `assets`.`model_id` = `models`.`id` and exists (select * from `manufacturers` where `models`.`manufacturer_id` = `manufacturers`.`id` and (`manufacturers`.`name` LIKE %张晓晖%) and `manufacturers`.`deleted_at` is null)) or (exists (select * from `status_labels` where `assets`.`status_id` = `status_labels`.`id` and `status_labels`.`name` LIKE %张晓晖% and `status_labels`.`deleted_at` is null)) or (exists (select * from `suppliers` where `assets`.`supplier_id` = `suppliers`.`id` and `suppliers`.`name` LIKE %张晓晖% and `suppliers`.`deleted_at` is null)) or (exists (select * from `companies` where `assets`.`company_id` = `companies`.`id` and `companies`.`name` LIKE %张晓晖%)) or (exists (select * from `locations` where `assets`.`rtd_location_id` = `locations`.`id` and `locations`.`name` LIKE %张晓晖% and `locations`.`deleted_at` is null)) or (`assets_users`.`first_name` LIKE %张晓晖% or `assets_users`.`last_name` LIKE %张晓晖% or CONCAT(assets_users.first_name," ",assets_users.last_name) LIKE %张晓晖% or `assets_users`.`username` LIKE %张晓晖% or `assets_locations`.`name` LIKE %张晓晖% or `assigned_assets`.`name` LIKE %张晓晖%) or `assets`.`name` LIKE %张晓晖% or `assets`.`asset_tag` LIKE %张晓晖% or `assets`.`serial` LIKE %张晓晖% or `assets`.`order_number` LIKE %张晓晖% or `assets`.`purchase_date` LIKE %张晓晖% or `assets`.`purchase_cost` LIKE %张晓晖% or `assets`.`notes` LIKE %张晓晖% or `assets`.`_snipeit_networked_impactful_architecture_1` LIKE %张晓晖% or `assets`.`_snipeit_optimized_6thgeneration_toolset_2` LIKE %张晓晖% or `assets`.`_snipeit_reduced_methodical_functionalities_3` LIKE %张晓晖% or `assets`.`_snipeit_enhanced_needs_based_capability_4` LIKE %张晓晖% or `assets`.`_snipeit_admin_passwort_5` LIKE %张晓晖%) and `assets`.`deleted_at` is null)
/srv/users/serverpilot/apps/laravel5/vendor/laravel/framework/src/Illuminate/Database/Connection.php#647

**Comment by snipe** [comment]
This should be fixed on develop now.
