### ISSUE TITLE
API : Update custom fields

### ISSUE THREAD

**Issue by glureau** [snipe/snipe-it#4593]
#### Expected Behavior (or desired behavior if a feature request)

Use the API to update a custom field.
Method: PATCH 
URL: /api/v1/hardware/123
Payload:
```
{
	"id":123,
	"name":"AName",
	"custom_fields":{
		"Firmware":{"field":"_snipeit_firmware_2","value":"1.2.3"},
	}
}
```
or:
```
{
	"id":123,
	"name":"AName",
	"_snipeit_firmware_2":"1.2.3"
}
```

Expectation: the name and the custom field are updated.

-----

#### Actual Behavior

Only the name is updated.
Response from the API:
```
{
    "status": "success",
    "messages": "Asset updated successfully.",
    "payload": {
        "id": 123,
        "name": "AName",
        [...]
        "_snipeit_firmware_2": "0.0.0"
    }
}
```
-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
upgrade
- Version of Snipe-IT you're running
v4.1.3 build 48 (g74aa562)
- Version of PHP you're running
5.6.30-0+deb8u1

**Comment by snipe** [comment]
Just specify the custom field name, it's not in its own object/array.

<img width="1118" alt="screen-shot-2017-11-24-at-1 12 36-pm" src="https://user-images.githubusercontent.com/197404/33751800-31e13f6a-db92-11e7-9efd-5d5276484a14.png">
<img width="643" alt="screen-shot-2017-11-24-at-1 13 16-pm" src="https://user-images.githubusercontent.com/197404/33751801-320141c0-db92-11e7-8433-473c10d04141.png">

https://gitter.im/snipe/snipe-it?at=5a188a060cef4fed2ebda89e

**Comment by glureau** [comment]
I was using json sent in body, and it doesn't work as I expect. @snipe Do you see an issue in the screens below?

![image](https://user-images.githubusercontent.com/7968075/33773904-d024e260-dc39-11e7-8148-89ff33394799.png)

![image](https://user-images.githubusercontent.com/7968075/33773941-e7ceb8f0-dc39-11e7-958b-5ab0210533cc.png)

**Comment by glureau** [comment]
I reproduced a correct behaviour with x-www-form-urlencoded, but I have to re-send the model_id even if it hasn't changed (not obvious but ok).

It's still an issue from my point of view unless the json in body is simply not supported?

**Comment by snipe** [comment]
> but I have to re-send the model_id even if it hasn't changed 

That's a bug then - shouldn't need to repost that. What happens when you submit without?

**Comment by glureau** [comment]
It says `Asset updated successfully.`, the name is updated, but the custom field isn't.
Also in the response, when there is no model_id, the response doesn't contain the model json object, when you send it, it's returned:

![Response with the model_id](https://user-images.githubusercontent.com/7968075/33825255-6054258e-de61-11e7-97d0-08f3477b440c.png)

**Comment by therealjoshuad** [comment]
Huh, interesting enough seeing that same behavior myself. I was able to update the serial number, but not a custom field. Added model_id to the body and it updated the custom field

**Comment by jbloomer** [comment]
I am also seeing a similar issue except I cannot get any custom fields to update no matter what. 

I have the following device
{
  "total": 1,
  "rows": [
    {
      "id": 2654,
      "name": "",
      "asset_tag": "thisisunique17",
      "serial": "",
      "model": {
        "id": 5,
        "name": "YongTest"
      },
      "model_number": "1",
      "eol": null,
      "status_label": {
        "id": 1,
        "name": "Pending",
        "status_meta": "pending"
      },
      "category": {
        "id": 7,
        "name": "Yong Cat"
      },
      "manufacturer": {
        "id": 1,
        "name": "VMWare"
      },
      "supplier": null,
      "notes": null,
      "order_number": null,
      "company": null,
      "location": null,
      "rtd_location": null,
      "image": null,
      "assigned_to": null,
      "warranty_months": null,
      "warranty_expires": null,
      "created_at": {
        "datetime": "2018-01-16 13:02:33",
        "formatted": "2018-01-16 01:02 PM"
      },
      "updated_at": {
        "datetime": "2018-01-16 13:02:33",
        "formatted": "2018-01-16 01:02 PM"
      },
      "last_audit_date": null,
      "next_audit_date": null,
      "deleted_at": null,
      "purchase_date": null,
      "last_checkout": null,
      "expected_checkin": null,
      "purchase_cost": null,
      "user_can_checkout": false,
      "custom_fields": {
        "Yong Field Name": {
          "field": "_snipeit_yong_field_name_14",
          "value": "",
          "field_format": "ANY"
        }
      },
      "available_actions": {
        "checkout": true,
        "checkin": true,
        "clone": true,
        "restore": false,
        "update": true,
        "delete": true
      }
    }
  ]
}

I am sending the following payload to do a patch update 

{"asset_tag":"thisisunique17","model_id": 5,**"_snipeit_application_3": "Test Application"**}

I am getting the following response

{
  "status": "success",
  "messages": "Asset updated successfully.",
  "payload": {
    "id": 2654,
    "name": null,
    "asset_tag": "thisisunique17",
    "model_id": 5,
    "serial": null,
    "purchase_date": null,
    "purchase_cost": null,
    "order_number": null,
    "assigned_to": null,
    "notes": null,
    "image": null,
    "user_id": 2346,
    "created_at": "2018-01-16 13:02:33",
    "updated_at": "2018-01-16 13:02:33",
    "physical": 1,
    "deleted_at": null,
    "status_id": 1,
    "archived": 0,
    "warranty_months": null,
    "depreciate": 0,
    "supplier_id": null,
    "requestable": 0,
    "rtd_location_id": null,
    "_snipeit_mac_address_1": null,
    "accepted": null,
    "last_checkout": null,
    "expected_checkin": null,
    "company_id": 0,
    "assigned_type": null,
    "last_audit_date": null,
    "next_audit_date": null,
    "location_id": null,
    "_snipeit_application_team_2": null,
    **"_snipeit_application_3": null,**
    "_snipeit_application_owner_4": null,
    "_snipeit_team_distribution_list_5": null,
    "_snipeit_environment_6": null,
    "_snipeit_vcenter_7": null,
    "_snipeit_cpu_cores_8": null,
    "_snipeit_memory_mb_9": null,
    "_snipeit_vlan_id_10": null,
    "_snipeit_os_11": null,
    "_snipeit_support_team_12": null,
    "_snipeit_bu_13": null,
    "_snipeit_yong_field_name_14": "",
    "model": {
      "id": 5,
      "name": "YongTest",
      "model_number": "1",
      "manufacturer_id": 1,
      "category_id": 7,
      "created_at": "2018-01-05 19:53:57",
      "updated_at": "2018-01-08 17:02:24",
      "depreciation_id": null,
      "eol": 0,
      "image": null,
      "deprecated_mac_address": 0,
      "fieldset_id": 6,
      "notes": "yong",
      "requestable": 0
    }
  }
}

**Comment by menemat** [comment]
I have the same problem. Anybody has fixed it?

Thanks in advance!

**Comment by gdepeyrot** [comment]
I am having the same problem. Is there any workaround to update custom fields via patch or put ?

**Comment by snipe** [comment]
This was closed in this patch: https://github.com/snipe/snipe-it/commit/d920d917860775d9be0e683b505d6fd715c43e58
