### ISSUE TITLE
Sidenav links to category

### ISSUE THREAD

**Issue by WouterVerlaar** [snipe/snipe-it#4594]
#### Expected Behavior (or desired behavior if a feature request)

I would like to create a 'map' in Categories. At my work they have a map Tools and then under tools they have Measurement Tools, Electrical etc. and I would like to seperate those of all the tools we got. Is it possible to make some kind of map in a category?

-----

#### Actual Behavior

Making new maps in a category is what I would like to have

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  Upgrade.
- Version of Snipe-IT you're running: V 3.6.4
- Version of PHP you're running   N/A
- Version of MySQL/MariaDB you're running   N/A
- What OS and web server you're running Snipe-IT on:  Windows 10
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)  Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I'm afraid I don't really understand what you mean. Can you clarify?

**Comment by WouterVerlaar** [comment]
> I'm afraid I don't really understand what you mean. Can you clarify? 

Well, we have the list Materials then we have Categories and in that one we have Tools, Mobile phones etc. but for example; I wanna make a map iPhone and Samsung in the Mobile Phones category to seperate those 2. Is that possible?

![screenshot_2](https://user-images.githubusercontent.com/34133310/33756837-91a6205e-dbf7-11e7-8e6f-ac94a3356cd1.png)

**Comment by snipe** [comment]
>  I wanna make a map iPhone and Samsung in the Mobile Phones category to seperate those 2

I'm so sorry, I'm still not getting it. :(

**Comment by CronKz** [comment]
Pretty simple - he wants the feature to create your own custom categories in the sidemenu like this:

- Mobile Phones (Parent)
-             iPhone (Child)
-             Samsung (Child)

By the way i think he means "folders" - thats the translation for "map" in dutch.

**Comment by WouterVerlaar** [comment]
> Pretty simple - he wants the feature to create your own custom categories in the sidemenu like this:

Mobile Phones (Parent)
Apple (Child)
Samsung (Child)
By the way i think he means "folders" - thats the translation for "map" in dutch.


Correct.

Is that possible to do? To make new folders in the category folder itself?
