### ISSUE TITLE
Feature Request - Checkout Consumable to Asset

### ISSUE THREAD

**Issue by rojjin** [snipe/snipe-it#4597]
This is not an issue, but a feature request. It would helpful to be able to check a consumable out to an asset or be able to select a consumable when adding an asset maintenance.

Example situation:
You have a printer that requires the replacement of a paper feed roller. You keep them in stock under consumables. When creating an asset maintenance for replacing the roller you could sellect it from consumables and have it reduce the count or you could goto consumables and check one out to the printer asset.

Thanks

**Comment by rojjin** [comment]
Duplicate request

**Comment by wilsonlspacheco** [comment]
+1 👍

**Comment by snipe** [comment]
Duplicate of #1538. (I'm using #1538 as the reference since it seems to be the first time this feature was suggested.)
