### ISSUE TITLE
Not viewing the location map

### ISSUE THREAD

**Issue by itims** [snipe/snipe-it#4599]
Hi,

After upgrading to latest version, not viewing the location map.
I have created API key and added same to .env file as you specified.
![image](https://user-images.githubusercontent.com/23715217/33752829-017e20cc-dc0a-11e7-9056-959d1d124d1e.png)

-----
#### Provide answers to these questions:

Provide answers to these questions:

Is this a fresh install or an upgrade? - **Upgraded from Version v3.6.3  to Version v4.1.7**
Version of Snipe-IT you're running - v4.1.6
Version of PHP you're running - 5.6.32-1+ubuntu14.04.1+deb.sury.org+1
Version of MySQL/MariaDB you're running - MySQL Server 5.5
What OS and web server you're running Snipe-IT on - Ubuntu Server 14.04
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - snipeit.sh
WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
If a stacktrace is provided in the error, include that too.
Any errors that appear in your browser's error console.
Confirm whether the error is reproduceable on the demo: https://snipeitapp.com/demo.
Include any additional information you can find in app/storage/logs and your webserver's logs.
Include what you've done so far in the installation, and if you got any error messages along the way.
Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Hi @itims - this usually means you haven't authorized your Google API key to use the Maps APIs. (It's a long, convoluted process that Google makes far more confusing than it should be.)

The easiest way to verify if this is what's happening is to view the map image url in a browser directly. You'll probably see something like "The Google Maps API server rejected your request. This API project is not authorized to use this API. Please ensure this API is activated in the Google Developers Console: https://console.developers.google.com/apis/api/static_maps_backend?project=_"

In the [Google Developers console](https://console.developers.google.com), go to Library, search for Maps and enable the Maps APIs. (If you want to limit it to just the ones we need, I think it's the Maps Simple Embed API.)

It can take a minute or two after enabling those APIs for google to recognize that it’s authorized now.
