### ISSUE TITLE
After going through Windows installation steps -  update composer throws this:

### ISSUE THREAD

**Issue by MViste** [snipe/snipe-it#460]
Command: composer update

Loading composer repositories with package information
Updating dependencies (including require-dev)
Generating autoload files
{"error":{"type":"ErrorException","message":"Undefined index: aliases","file":"C
:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foun
dation\\start.php","line":180}}{"error":{"type":"ErrorException","message":"Unde
fined index: aliases","file":"C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\f
ramework\\src\\Illuminate\\Foundation\\start.php","line":180}}
C:\inetpub\wwwroot\snipe-it>

I also had to set the timezone in this same file. Any ideas are welcome!

**Comment by HinchK** [comment]
Undefined index: aliases can be due to an alias in the app/config/app.php 'aliases' array being referenced before the vendor package has been installed.

Try this:

comment out the 3rd party aliases in app.php (anything not starting with Illuminate; 
run composer update, 
uncomment after the vendor package is installed.

app/config/app.php:

    'aliases' => array(

            'App'             => 'Illuminate\Support\Facades\App',
            'Artisan'         => 'Illuminate\Support\Facades\Artisan',
            'Auth'            => 'Illuminate\Support\Facades\Auth',
            'Blade'           => 'Illuminate\Support\Facades\Blade',
            'Cache'           => 'Illuminate\Support\Facades\Cache',
            'ClassLoader'     => 'Illuminate\Support\ClassLoader',
            'Config'          => 'Illuminate\Support\Facades\Config',
            'Controller'      => 'Illuminate\Routing\Controller',
            'Cookie'          => 'Illuminate\Support\Facades\Cookie',
            'Crypt'           => 'Illuminate\Support\Facades\Crypt',
            'DB'              => 'Illuminate\Support\Facades\DB',
            // 'Datatable' => 'Chumper\Datatable\Facades\DatatableFacade',
            'Eloquent'        => 'Illuminate\Database\Eloquent\Model',
            'Event'           => 'Illuminate\Support\Facades\Event',
            'File'            => 'Illuminate\Support\Facades\File',
            'Form'            => 'Illuminate\Support\Facades\Form',
            'Hash'            => 'Illuminate\Support\Facades\Hash',
            'HTML'            => 'Illuminate\Support\Facades\HTML',
			// 'Image'           => 'Intervention\Image\ImageManagerStatic',
            'Input'           => 'Illuminate\Support\Facades\Input',
            'Lang'            => 'Illuminate\Support\Facades\Lang',
            'Log'             => 'Illuminate\Support\Facades\Log',
            'Mail'            => 'Illuminate\Support\Facades\Mail',
            'Paginator'       => 'Illuminate\Support\Facades\Paginator',
            'Password'        => 'Illuminate\Support\Facades\Password',
            'Queue'           => 'Illuminate\Support\Facades\Queue',
            'Redirect'        => 'Illuminate\Support\Facades\Redirect',
            'Redis'           => 'Illuminate\Support\Facades\Redis',
            'Request'         => 'Illuminate\Support\Facades\Request',
            'Response'        => 'Illuminate\Support\Facades\Response',
            'Route'           => 'Illuminate\Support\Facades\Route',
            'Schema'          => 'Illuminate\Support\Facades\Schema',
            'Seeder'          => 'Illuminate\Database\Seeder',
            // 'Sentry'          => 'Cartalyst\Sentry\Facades\Laravel\Sentry',
            'Session'         => 'Illuminate\Support\Facades\Session',
            'SSH'             => 'Illuminate\Support\Facades\SSH',
            'Str'             => 'Illuminate\Support\Str',
            'URL'             => 'Illuminate\Support\Facades\URL',
            'Validator'       => 'Illuminate\Support\Facades\Validator',
            'View'            => 'Illuminate\Support\Facades\View'

    ),

**Comment by snipe** [comment]
Did you actually run composer install first?

**Comment by snipe** [comment]
@MViste I've seen errors like this when some of the config files are missing from `app/config`. Can you tell me what files you've got in that directory?
