### ISSUE TITLE
Advances search not searching in all assets

### ISSUE THREAD

**Issue by CBeIT** [snipe/snipe-it#4600]
#### Expected Behavior (or desired behavior if a feature request)

Advanced Search should search through all assets.

-----

#### Actual Behavior

Advanced Search only searches the 20 (or 30 or 50) assets displayed in the asset list.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Hosted
- Version of Snipe-IT you're running 4.1.6 pre
- Version of PHP you're running Don't know
- Version of MySQL/MariaDB you're running Don't know
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
That's not correct. It searches through all of the assets. We need more information here.

**Comment by EarlRamirez** [comment]
Can you provide additional information so that we can help?
