### ISSUE TITLE
Custom Asset Report doesn't show sub locations

### ISSUE THREAD

**Issue by hamzab900** [snipe/snipe-it#4601]
Lets say I have the setup below.

    Company 1
       |
       --- Location A (Parent)
               |
               --- Location A1 (Child of Location A)
               |
               --- Location A2 (Child of Location A)

When I generate a custom report, is it possible to have an option to include all sub locations? For example selecting Location A would include A1 and A2 as they are part of A.

A real life scenario is that we have a department called Client Services. Under that we have sub departments such as Accounting, Sales, Tech etc.

I would like to be able to see everything in Client Services from report rather than printing out like 5.

Another example is that we have a server room, in it we have different racks. I have a location called "Server Room" under it I have different locations named after the racks. I want to be able to run a report on "Server Room" and it would include all the rack locations under it in one big report.

Any thoughts?

**Comment by lbogdans** [comment]
Report per location including sublocations will be really required in the future for us. 
Please consider to include such report as a standard.

**Comment by alachance001** [comment]
We are new snipeit users, This feature really interests us and need it

**Comment by jonnyiompo** [comment]
Yes we would also like this feature as well
