### ISSUE TITLE
Help configuring automatic LDAP sync with Cron

### ISSUE THREAD

**Issue by MSTigers** [snipe/snipe-it#4602]
#### Expected Behavior (or desired behavior if a feature request)

Schedule a cronjob to sync LDAP using the same settings in the /admin/ldap page.

On the web UI I click the "LDAP Sync" button on the /users page. (People)
![ldap pic](https://user-images.githubusercontent.com/33290254/33780582-e0b3286c-dc16-11e7-815f-dabc606e0309.jpg)

This works great!

The cronjob / scheduled task needs to replicate the same actions as the web UI button does.

-----

#### Actual Behavior

**NOT A BUG.** 
Nothing yet. Haven't quite figured out the right way to do it.  Just need some help!

REFERENCES:  #3962 , #4127  &  [User Manual](https://snipe-it.readme.io/v4.1.6/docs/ldap-sync-login#section-ldap-command-line-sync)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade
- Version of Snipe-IT you're running
Version v4.1.6 - build 2994 (master)
- Version of PHP you're running
7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running
5.4.29
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04.3 / Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- Indicate whether or not you've manually edited any data directly in the database
No modifications

-----
#### Summary of my question / what I know so far:

Not much! We are using active directory to sync. The web UI works great in pulling users, passwords, emails, usernames, etc. All of that works as desired.

In the help page it indicates I can setup a cron to automatically sync the LDAP, though it doesn't clarify the exact steps. I am assuming this implies that the user will need an existing knowledge of setting up a cronjob to do this. This I don't have, but below is my best attempt.

**1.) Setting up the cronjob**

This is what I have so far:

```
crontab -e

#Snipe-IT LDAP Sync job 
00 22 * * Mon,Tue,Wed,Thu,Fri /usr/bin/php /var/www/snipeit artisan snipeit:ldap-sync

```

**2.) What user should the cronjob be ran as?**

When I'm in the /var/www/snipeit directory, my user account has all of the privileges (should) to run the ldap. Do you recommend setting up a cronjob as a different user? Should it be the same user that runs apache (`www-data`) Without checking, I'm not sure if www-data is allowed to run cron jobs anyways.

3.) Do you suggest I have `> /dev/null 2>&1` in the command as well as indicated in #3962 ? I read up on that line [here](https://stackoverflow.com/questions/10508843/what-is-dev-null-21) to get some more information on it but it seems it may not be something I want or need.

**4.) Can I utilize Snipe to send out email notifications for LDAP, or does it require a different tool?**

Alternatively, if I was wanting a log report and email notification (I like receiving a notification for both success and failure). The `> /dev/null 2>&1` may be counterproductive. 

Something like?
`
00 22 * * Mon,Tue,Wed,Thu,Fri /usr/bin/php /var/www/snipeit artisan snipeit:ldap-sync 2>&1 ; mailx -s "Snipe LDAP Sync notification"  email@domain.com,email2@domain.com
`

I was hoping since Snipe already has the ability to mail out that I could utilize that, but I'm not sure. Above the mailx was an example, though currently I do not have any [mail packages installed](https://packages.ubuntu.com/xenial/mailx) if I can't use Snipe to do it.

**5.) What is being synced when I do it from the CLI?**

Lastly, #4127 indicates a difference in CLI vs. web UI LDAP syncs. We don't have multiple LDAP locations. Following the examples above, assuming any of them are usable, will it utilize the LDAP settings configured on the /admin/ldap page of the web UI?

**Comment by MSTigers** [comment]
If it wasn't for #3962  I would have went with:  `00 22 * * Mon,Tue,Wed,Thu,Fri /var/www/snipeit php artisan snipeit:ldap-sync`  because that seems more in line with what the help page suggested.

Instead of:

`00 22 * * Mon,Tue,Wed,Thu,Fri /usr/bin/php /var/www/snipeit artisan snipeit:ldap-sync`

**Comment by EarlRamirez** [comment]
I will try and answer a few of the questions based on  some experience with cron jobs

(1) Create a script in the language of your choice, bash will be easiest (this depends on you), the script will change into your Snipe-IT directory and then run the sync. You can then copy/move the script to /etc/cron.daily, it usually runs the script as root unless specified.

(2) For email notification, you can also use a script that will parse the output of the sync and have the output sent to your inbox,  I have only used --verbose with import, maybe that option exists for the sync.

**Comment by MSTigers** [comment]
Do you mind explaining why you recommend using a script file and putting it in the /etc/cron.daily instead of modifying the crontab file directly?

**Comment by EarlRamirez** [comment]
I only recommended this because you asked what user is required to run these cron jobs and generating emails with success/fail sync. I just saw it as a simple solution compared.

Doesn't mean that it is the best way thought.
