### ISSUE TITLE
Feature: Generic assets to make for specific awesomeness

### ISSUE THREAD

**Issue by richarddb** [snipe/snipe-it#4604]
#### Nudging Snipe to Cover More

Snipe-IT is one of the most beautiful and well thought out pieces of OSS I've ever used, especially compared to the proprietary competition. There's one element of flexibility, though, that makes Snipe a tough sell in my organization, because there's a few core use cases I cannot achieve in it.

Some of these use cases include:

* Depreciating warranties. It's common to purchase infrastructure that has an expected EOL that's different from the warranty period. Technically, we should then depreciate the warranty with a specific "purchase price" for a different period than the underlying asset.

* Depreciating installations. Similarly, we are allowed in some circumstances to depreciate the installation of a piece of technology; and very typically the accountants need to see that element separately from the asset itself.

* Trademarks and domain names. These are also depreciated, but also a little like licenses in that they may need to be "renewed" before expiring.

In other words, I think Snipe is very close to tracking many more asset types... All I would need is to be able to configure an "asset" from scratch. A trademark, for example, has an expiry date that needs notification, but it doesn't have a manufacturer or model number etc. If every element of the main entities in the current data model were set up by configuration, this would greatly increase the flexibility of the system. Users could then centralize all asset lifecycle management, including depreciation, in one place.

-----

#### Actual Behavior

Probably the easiest way to handle this is to adapt the "Field sets" functionality. Insert pre-configured ones for the standard types, but allow even those to be modified.

Also allow specification of the icon for that type, and whether it should be included in the top shortcut bar.

One potential concern of this approach: Because every field is configurable, performance potentially could become an issue. Would we have to also be able to indicate search indices on particular fields? If not indexed, search over that field may then be slow; but that's okay if such a search is rare.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh install.
- Version of Snipe-IT you're running. v4.17
- Version of PHP you're running. 7.0.26.
- Version of MySQL/MariaDB you're running. MySQL 5.7.2.
- What OS and web server you're running Snipe-IT on. Ubuntu LTS, Apache.
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc). Docker.
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error. N/A.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error. N/A.
- If a stacktrace is provided in the error, include that too. N/A.
- Any errors that appear in your browser's error console. N/A.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.  N/A.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. N/A.
- Include what you've done so far in the installation, and if you got any error messages along the way. N/A.
- Indicate whether or not you've manually edited any data directly in the database N/A.

**Comment by richarddb** [comment]
Another few use cases:

-- Why not asset tag some accessories, like keyboards?
-- Or capture more detail on components, like the JEDEC specs on RAM?

**Comment by snipe** [comment]
> Why not asset tag some accessories, like keyboards?

Because that makes them assets. Asset tags are literally what determines whether something is considered an asset or not. 

> Or capture more detail on components, like the JEDEC specs on RAM?

There are already tickets open for custom fields on non-assets.

> Licenses need attachments—sometimes they're sent as files, not as a product key.

Licenses have file uploads.

**Comment by snipe** [comment]
> Depreciating warranties. It's common to purchase infrastructure that has an expected EOL that's different from the warranty period. 

I believe there is already a ticket open related to that.

> Trademarks and domain names. 

Ticket for domain name exists (I think - I think I opened it a long time ago). Not for trademarks, but it's an interesting thought. Not sure if that starts to creep outside the scope of what we're trying to do here though.

**Comment by richarddb** [comment]
Hey, thanks for responding to each element I raised! I did see some of the open tickets; the reason I raised these together is because I'm suggesting the generic capability that would address many issues in one fell swoop.

I guess I do see a really generic flow: You have something of value, for which you may have paid an acquisition price. That thing of value may depreciate. You want to track static information on that thing, and load files against it. Finally, you want to track statuses on the thing to control your workflow, and what actions are available to different users. It should eventually terminate in disposal of that asset, perhaps for some residual value (that also has tax implications).

So I know it sounds _really_ generic, but in this view things like trademarks are not actually scope creep. And for me, it would be awesome to have such a beautiful system that will handle all of my depreciating, controlled assets. Otherwise I'm pulling depreciation out of Snipe, but trying to marry it to deprecation calculated for other things, elsewhere.

**Comment by snipe** [comment]
@richarddb there is different business logic around all of these things though. That's why it's set up the way it is. We've toyed with the idea of merging everything into a "one table to rule them all" type of thing but ended up with a polymorphic compromise for now.

**Comment by richarddb** [comment]
Ah, that's the danger of not looking at the code before suggesting "a quick fix" :) I can also see how OTT-RTA would quickly have knock impacts almost everywhere. Makes for a lot of indirection around the business logic too, I guess.

**Comment by snipe** [comment]
I mean, you're not *wrong*. We've been through this before, that's all. (There is a longish thread about it [here](https://github.com/snipe/snipe-it/issues/1789).) There's also some stuff in there that I *do not want* (people as items, for example).

Our direction will likely be in this direction (a SnipeItem which all other models inherit from, which carry the custom field traits, etc). Where it gets tricksy is allowing the flexibility while keeping the system relatively simple for more standard uses. My head already hurts thinking about all of the new settings we'd need to add so that the overall behavior for "normal" folks doesn't change away from what they know and love. One of Snipe-IT's strengths (or so people tell us, anyway) is that it's powerful without being too confusing/overwhelming. 

In general, most of our models are very similar, but have just enough differences to make executing this a massive pain in the ass. That doesn't mean it won't happen, just that it's going to suck to get us there.
