### ISSUE TITLE
Customize Login Page... is it possible? 

### ISSUE THREAD

**Issue by fileadda** [snipe/snipe-it#4606]
is it possible to customize login page design? mean... want to change/Add Own Logo, Background Image. 

i had searched for login page, but i can't find, where it was located. 

can any one help me. 

where is login page located? (index.php or index.html or login.php or login.html)

**Comment by jimmysnee** [comment]
Go to the admin page (look for the gears icon on the menu bar - top right) then click on 'branding'

**Comment by dedeoglumrt** [comment]
+1

**Comment by dedeoglumrt** [comment]
custom logo size on login page?

**Comment by snipe** [comment]
@dedeoglumrt You can customize the CSS in that branding page as well, which will let you customize the logo size.
