### ISSUE TITLE
Check Out Time Mail

### ISSUE THREAD

**Issue by vipin2079** [snipe/snipe-it#4607]
Team,

I have seen  checkin and checkout notification  come in GST Time but I need  notification in IST  Time & EST Time.Please let me know how can we achieve

**Comment by tbradsha** [comment]
This is usually controlled by setting/changing the timezone in your php.ini using the date.timezone key:

http://php.net/manual/en/datetime.configuration.php#ini.date.timezone
http://php.net/manual/en/timezones.php
