### ISSUE TITLE
Changing currency to £ doesnt show in website

### ISSUE THREAD

**Issue by rattys** [snipe/snipe-it#461]
I've changed tha language file en to £ from $ but the website is still showing $.  Do I need to do anything else?  I've restarted the website.

**Comment by snipe** [comment]
Can you point to specific instances where that's the case?

**Comment by rattys** [comment]
When creating an asset, creating a license, looking at depreciation report
Its like the setting just hasn't take effect

**Comment by snipe** [comment]
Did you maybe update the version and the language file was blown out? I'm looking at the templates, and they definitely use `@lang('general.currency')`.

To solve the issue of potentially overwriting the currency, I've created a GB language file, which ships with £ as the currency. If you grab the latest version off of develop, and change your language preference in `app/config/app.php` from `'locale' => 'en',` to `'locale' => 'en-GB',`, that may work for you.

**Comment by rattys** [comment]
That worked perfectly.  Thanks ☺
