### ISSUE TITLE
Searching Users resolves everyone.

### ISSUE THREAD

**Issue by Mynty100** [snipe/snipe-it#4613]
#### Expected Behavior (or desired behavior if a feature request)
When in the People section and searching for a specific user in the search ei: John
The page loads and would expect to fin all users with name John in it.

-----

#### Actual Behavior
When in the People section and searching for a specific user in the search ei: John
The page loads and Shows all uses and DOES NOT load anything related to any search.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh
- Version of Snipe-IT you're running
v4.1.5 build 187 (gc0293a7) 
- Version of PHP you're running
7.0.16
- Version of MySQL/MariaDB you're running
MySQL v5.6.36 
- What OS and web server you're running Snipe-IT on
Linux Mint 18.2/Apache 2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
AMPPS
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
NULL
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
People
- If a stacktrace is provided in the error, include that too.
NULL
- Any errors that appear in your browser's error console.
NULL
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Tested on Demo and Demo works normally.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
No errors. everything works wonders except being able to search for users.
- Indicate whether or not you've manually edited any data directly in the database
Havn't touch anything yet.

**Comment by snipe** [comment]
> Include any additional information you can find in app/storage/logs and your webserver's logs.

**Comment by Mynty100** [comment]
Next Illuminate\Database\QueryException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snip534.users' doesn't exist (SQL: select count(*) as aggregate from `stly_users` where (`stly_users`.`first_name` LIKE %John% or `stly_users`.`last_name` LIKE %John% or `stly_users`.`email` LIKE %John% or `stly_users`.`username` LIKE %John% or `stly_users`.`notes` LIKE %John% or `stly_users`.`phone` LIKE %John% or `stly_users`.`jobtitle` LIKE %John% or `stly_users`.`employee_num` LIKE %John% or (exists (select * from `stly_locations` where `stly_users`.`location_id` = `stly_locations`.`id` and `stly_locations`.`name` LIKE %John%)) or (exists (select * from `stly_departments` where `stly_users`.`department_id` = `stly_departments`.`id` and `stly_departments`.`name` LIKE %John%)) or (exists (select * from `stly_groups` inner join `stly_users_groups` on `stly_groups`.`id` = `stly_users_groups`.`group_id` where `stly_users`.`id` = `stly_users_groups`.`user_id` and `stly_groups`.`name` LIKE %John%)) or (users.manager_id IN (select id from users where first_name LIKE %John% OR last_name LIKE %John%))) and `stly_users`.`deleted_at` is null) in /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Database/Connection.php:647
Stack trace:
#0 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select count(*)...', Array, Object(Closure))
#1 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#2 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1710): Illuminate\Database\Connection->select('select count(*)...', Array, true)
#3 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1695): Illuminate\Database\Query\Builder->runSelect()
#4 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2030): Illuminate\Database\Query\Builder->get(Array)
#5 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1958): Illuminate\Database\Query\Builder->aggregate('count', Array)
#6 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1251): Illuminate\Database\Query\Builder->count()
#7 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/app/Http/Controllers/Api/UsersController.php(114): Illuminate\Database\Eloquent\Builder->__call('count', Array)
#8 [internal function]: App\Http\Controllers\Api\UsersController->index(Object(Illuminate\Http\Request))
#9 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#10 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('index', Array)
#11 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\UsersController), 'index')
#12 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#13 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Routing\Route->run()
#14 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#17 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/Router.php(576): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#20 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/Router.php(535): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#21 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/Router.php(513): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#22 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#24 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/app/Http/Middleware/CheckForSetup.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/app/Http/Middleware/NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/app/Http/Middleware/ContentSecurityPolicyHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\ContentSecurityPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/app/Http/Middleware/ReferrerPolicyHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#40 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\ReferrerPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/app/Http/Middleware/XssProtectHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#43 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/app/Http/Middleware/FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#46 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#55 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#58 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#59 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#60 /usr/local/ampps/www/assetmgt.cvxmck.edu.au/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#61 {main}

**Comment by snipe** [comment]
Sounds like it's your table prefixes.

**Comment by Mynty100** [comment]
Hmmm not sure how to fix this as v3 install works fine on this system.
Any advice what where I should look. We have phpmyadmin so iv been looking through the tables.

**Comment by snipe** [comment]
I just pushed a change through to the develop branch that should fix your issue.
