### ISSUE TITLE
The best way to import this into snipe

### ISSUE THREAD

**Issue by WouterVerlaar** [snipe/snipe-it#4618]
#### Expected Behavior (or desired behavior if a feature request)

Get advise to what the easiest way of importing the Excel files is

-----

#### Actual Behavior

I have a lot of Excel files and I need to import these in to snipe-it for my work. What is the easiest way? I have an example but we have way more tools etc. in 1 excel file and I don't want to manually put these in to Snipe-IT. What is the easiest way?
-----

![screenshot_1](https://user-images.githubusercontent.com/34133310/33880137-ef71d872-df30-11e7-8fb4-3a8b058de3d7.png)

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
The easiest will be to start with the CSV samples we provide in the documentation and then modify your import CSVs to match those headers - then just import the files using the importer.

**Comment by WouterVerlaar** [comment]
> CSV samples we provide in the documentation

Can I just make a own sample with "Name, serialnumber" etc and add everything that I need?

**Comment by snipe** [comment]
Yes, just be sure to map the headers correctly. If you're using custom fields, they have to created first before you can import data into them.
