### ISSUE TITLE
Emails not importing from CSV

### ISSUE THREAD

**Issue by ohayondotio** [snipe/snipe-it#4619]
#### Expected Behavior (or desired behavior if a feature request)

Import the CSV full over users, including their emails. 

-----

#### Actual Behavior

Everything imports perfectly except for the emails. See pictures in link below.

https://imgur.com/a/hB8KF

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh install
- Version of Snipe-IT you're running 4.1.8 3034
- Version of PHP you're running 7.1
- Version of MySQL/MariaDB you're running 5.5.56-MariaDB
- What OS and web server you're running Snipe-IT on CentOS 7 and Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error N/A
- If a stacktrace is provided in the error, include that too. N/A
- Any errors that appear in your browser's error console. N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. N/A, can not import CSV in demo. 
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. Reinstalled Snipe-IT on another CentOS 7 VM with LAMP stack, imported DB, problem persists. 
- Indicate whether or not you've manually edited any data directly in the database Have not manually edited data. 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by EarlRamirez** [comment]
I am experiencing the same issue, I was about to file a bug for it.

**Comment by EarlRamirez** [comment]
@lohayon5 I tried using the following example and it worked; however, I did not use the general imported and I used the imported that is on the people page. Below is a sample of the CSV

firstName,lastName, username, email, location_id, phone, jobtitle, employee_num, company_id
Jane,Doe,jdoe,jdoe@test.com,,2222,Engineer,1234,1

The image can be found of the successful import, I will try it with a couple hundred of users and report back.

![image](https://user-images.githubusercontent.com/12306859/34073454-643c0f3a-e268-11e7-84a0-c56d96cc9bda.png)

**Comment by EarlRamirez** [comment]
@lohayon5, I was able to successfully import 300+ users with the email address using the above format that is recommended when you perform the import from the "people" page. I downloaded the sample users import using the "general" importer and even that did not import the emails, looks this can be a bug. I just started preparing developer instance so that I can contribute to the project as much as I can so, for now, you can try using the method that has been successful for me and let us know.

**Comment by lohayon5** [comment]
Unfortunately, that isn't working for me either. Here's a screenshot of my sample CSV. I'm doing this with debug mode enabled but not getting any type of error. 

<img src='https://i.imgur.com/cC0tpmR.png' />

And here's the result. 

<img src='https://i.imgur.com/Au3LX9I.png' />

**Comment by EarlRamirez** [comment]
@lohayon5 was it imported from the importer that is on the people page? Do you see "imported user" under the notes column? I used the text CSV and don't know if this can be part of the problem or not.

**Comment by dmeltzer** [comment]
Assume this was done using the new UserImpoter.  There was a bug when looking up emails.  Will be fixed shortly.

**Comment by dmeltzer** [comment]
Should be fixed in current develop.
