### ISSUE TITLE
When installing to Windows, can't download RunPHP Helper

### ISSUE THREAD

**Issue by duncanmchale** [snipe/snipe-it#462]
I click on this link: http://www.microsoft.com/web/gallery/install.aspx?appid=PHP54
This downloads PHP54.exe. I execute that, and pretty quickly I get this:
![screenshot](https://cloud.githubusercontent.com/assets/10566922/5784722/f537860e-9d9c-11e4-91b2-2bb827ae84f3.png)

**Comment by snipe** [comment]
That is an issue with your PHP install, not with Snipe-IT. Not really sure what to suggest, other than googling for some RunPHPHelper error messages:

http://forums.iis.net/p/1217874/2088282.aspx?RunPHP+Helper+Error+during+PHP+installation+with+WPI+

Possibly some funky firewall settings on your company network?

**Comment by duncanmchale** [comment]
Thanks for the prompt reply. I agree, it must be a firewall setting. I'm at a US Government site. I'll get a hand from the network people at my end.
