### ISSUE TITLE
Error creating User API Token

### ISSUE THREAD

**Issue by zone11** [snipe/snipe-it#4620]
#### Expected Behavior (or desired behavior if a feature request)

Add a new personal API key to the users account

-----

#### Actual Behavior

Adding a new Token to a users account stops with an error: "An Error has occured! Trying to get property of non-object"

More detailed in the console:
Trying to get property of non-object
/srv/snipeit/vendor/laravel/passport/src/ClientRepository.php#81

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running  v4.1.8-pre - build 3068 (master)
- Version of PHP you're running 7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running: MariaDB 10.0.31
- What OS and web server you're running Snipe-IT on: Apache 2.4 on Ubuntu 16.04.03
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Github pull
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - DONE
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: /account/api
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.: This feature has been disabled for the demo installation.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database: NO

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Run `php artisan passport:install`

**Comment by zone11** [comment]
Solves the problem!
Now found it the common issues page
