### ISSUE TITLE
Search Field "Checked Out To" does not work with Person

### ISSUE THREAD

**Issue by chrstmnn** [snipe/snipe-it#4622]
#### Expected Behavior (or desired behavior if a feature request)

If I enter a name in the search field "Checked Out To", I should get all assets checked out to that person.
-----

#### Actual Behavior

Snipe IT does not find any matching.
I just can view assets checked out to locations but not to users.

**Comment by chrstmnn** [comment]
Hi,

sorry for that.
Tested on your demo ;-)

**Comment by chrstmnn** [comment]
I tried to search for assets checked out to "James Bond" by entering "James Bond" in advanced search into field "Checked out to".
Also tested with "Adrienne Bode", "Adrienne", "Bode". But there are no matches.

<img width="1377" alt="1" src="https://user-images.githubusercontent.com/23477080/33902656-0b15fbd6-df76-11e7-8cfb-b2f48aea96ff.png">
<img width="591" alt="2" src="https://user-images.githubusercontent.com/23477080/33902657-0b31bccc-df76-11e7-88df-b1e19ffd52d9.png">
<img width="1377" alt="3" src="https://user-images.githubusercontent.com/23477080/33902658-0b4c82b4-df76-11e7-8bc4-99ab8e1fefbe.png">

**Comment by snipe** [comment]
(fix is on develop)

**Comment by snipe** [comment]
Check out the develop branch - we've pushed out a few changes that should address this.
