### ISSUE TITLE
[Feature request] Links from '/account/view-assets' to individual assets pages

### ISSUE THREAD

**Issue by s4kr4** [snipe/snipe-it#4624]
#### Expected Behavior (or desired behavior if a feature request)

Currently, we can see the list of assets on '/account/view-assets' but cannot access to individual assets pages directly.
I want to access to each of them from this page.
As an example, I made [this commit](https://github.com/s4kr4/snipe-it/commit/eafd49012c53d973352c3466c2ea2b9591779299) to implement that.

**Comment by CronKz** [comment]
I don't know why this hasn't been there... The only thing I can think of is that if the User has absolutely no rights, it would throw 403s by clicking on the links.
But in my opinion, I would like this change.

In addition the ability to set the rights of the user to "assets - read only - only see assigned assets to them" would be even better, to prevent any possible 403s.

**Comment by snipe** [comment]
Its not a unreasonable request, but with the mire granular permissions, this is a non-trivial task.
