### ISSUE TITLE
Asset search with location by url 

### ISSUE THREAD

**Issue by amarbhanu** [snipe/snipe-it#4625]
I want to search asset list by location .

So i create a list of location with link, but url is not working properly, if any have idea then suggest me.

http://localhost/hardware/second_floor

Second_floor is Location

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by amarbhanu** [comment]
Snipe IT Version v4.1.4 
Now window
install.sh

brower hit url http://localhost/hardware/second_floor  (Second_floor is Location)

i got  Error: Asset does not exist.


objective of url hit:
I want to search asset list by location .

So i create a list of location with link, but url is not working properly, if any have idea then suggest me.

**Comment by snipe** [comment]
I kind of don't understand why you you would create that link in the first place. That's not how Snipe-IT handles locations. Why would you think that would work?

**Comment by amarbhanu** [comment]
Ok can you suggest me snipe-IT URL for asset list by location.

**Comment by amarbhanu** [comment]
snipe-IT have only to http://xxxxxxxx.com/locations/1 for some info of asset on location page but asset List not found on asset List Page. If any have idea then share with me

**Comment by snipe** [comment]
> snipe-IT have only to http://xxxxxxxx.com/locations/1 for some info of asset on location page but asset List not found with location by url hit on asset List Page

I'm sorry, I really don't understand what you're saying here.

**Comment by amarbhanu** [comment]
now i am make a new api for get data by  location `LocationbyController.php` as related to AssetController.php is working, i got data by LocationbyController.php but LocationbyPresenter.php also make by view have not show data. 

Can use suggested me what will be reason for not data map with LocationbyPresenter.php

**Comment by amarbhanu** [comment]
bug found one field was missing. got  by console, fixed
