### ISSUE TITLE
All assets view doesn't show some Custom fields values + Asset modification changes not saved

### ISSUE THREAD

**Issue by sydit** [snipe/snipe-it#4626]
#### Expected Behavior (or desired behavior if a feature request)

1. **"All assets"** view displays all details of an asset. 
2.  Any changes made to an asset are saved and displayed. 

-----

#### Actual Behavior

1. Some details are missing on List All>All assets view
2. Changes made to an asset are shown as saved but missing on View asset page and "All Assets"

Sometime back I updated Snipeit to 4.0.9 from 3.6.6. Few custom fields were missing in DB after the upgrade. So manually added to DB. Only recently noticed that when new assets are created/or edit existing asset containing manually added db fields, the details are shown as successfully created or edited but entered information is missing on asset view details page. All assets created before snipeit upgrade containing those db fields are shown on view asset page but not shown in "All Assets".

Also tried updating to latest build but issue remains.
-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running - 4.0.9
- Version of PHP you're running- 
- Version of MySQL/MariaDB you're running- 
- What OS and web server you're running Snipe-IT on - Ubuntu 14.04.5 LTS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)- Github
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - No error shown in browser and log
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - All assets/ Asset view page
- Performed DB edit after upgrade.

![image](https://user-images.githubusercontent.com/24789532/33931146-2725e5bc-e015-11e7-8325-3b0494324c35.png)
![image](https://user-images.githubusercontent.com/24789532/33931389-d69d74ec-e015-11e7-9936-d57a96fa60db.png)

**Comment by snipe** [comment]
Try upgrading to latest

**Comment by sydit** [comment]
Tried upgrade to latest git pull. Still no success :(

**Comment by snipe** [comment]
> Some details are missing on List All>All assets view

That list gets pulled programmatically, so I'm not really sure how fields could be missing unless they're not assigned to any fieldset. I assume you used the column-selector to show additional columns in the All Assets page?

**Comment by sydit** [comment]
Yes I used column-selector. Lost details of few assets but somehow got it **working**. Deleted 3 custom fields which caused the issue and fresh installed snipeit to another location. And then recreated those custom fields and imported assets("update existing values" option) from CSV.  Luckily I had few old CSV files which I used for importing initially.

**Comment by snipe** [comment]
There *was* an issue a few versions back where custom fields weren't being properly renamed on the asset table, which meant that there was a mismatch between the DB column name the DB *thought* you should have and the DB column the assets table *actually* had. I suspect that might have been what happened there. That bug was fixed a bunch of versions ago, but any custom fields that had been edited prior could possibly have run into that mismatch, which could cause some weird side effects.

**Comment by sydit** [comment]
Yes exactly. I noticed that in my asset table. For example 
**_snipeit_hdd_sn_26** changed to **_snipeit_hdd_sn_2_6** after upgrade. I was not able to create new assets containing those fields. This was in fact the reason for manually editing DB.

**Comment by snipe** [comment]
Yeah - sorry about that. That bug's been fixed, so you shouldn't have issues moving forward.

**Comment by sydit** [comment]
No problem. Now its working fine :100: %
