### ISSUE TITLE
Feature request: Location change

### ISSUE THREAD

**Issue by D2nnyim** [snipe/snipe-it#463]
We install all our assets in our main HQ, but then we send them off to other locations of our company. We would like to be able to track on what location the asset has been.
##

**Comment by snipe** [comment]
@D2nnyim are you saying you'd like the ability to have a log of all of the locations an asset has been? Or something else?

**Comment by D2nnyim** [comment]
Yes, that we can see in a log, when a device has changed to a different location.
(if send/ship is an option, that would be a nice feature, but not really necessary)
