### ISSUE TITLE
"Create New" button still available even when denied in permissions

### ISSUE THREAD

**Issue by Rodiloo** [snipe/snipe-it#4633]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

When creating a new user and define the rights, the Create New button are still available. Like it's not reacting at all to what i choose in permissions
-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running? Version v4.1.7
- Version of PHP you're running? PHP Version 5.6.31
- Version of MySQL/MariaDB you're running? Serverversion: 5.7.19
- What OS and web server you're running Snipe-IT on? Windows Server 2008 R2 Standarad, Apache/2.4.27 (Win64) mod_authnz_sspi/0.1.

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) ? install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error? No error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error? All pages that should be affected by permissions
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. No error
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. Can't check here because of no users to test on
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. No logs
- Include what you've done so far in the installation, and if you got any error messages along the way. I followed all steps as mentiond on snipeit website, no error during installation
- Indicate whether or not you've manually edited any data directly in the database? No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Please provide permissions/group screenshots and screenshots of an example of where you see this.

**Comment by Rodiloo** [comment]
![snipeit_error1](https://user-images.githubusercontent.com/33754316/34033895-7d221bbc-e17c-11e7-9bb2-f5e519eef798.png)
![snipeit_error2](https://user-images.githubusercontent.com/33754316/34033896-7d3d0d32-e17c-11e7-833f-b310d03797ab.png)

First picture is permissions for test2 user
And you can see in the second picture that the Create New button is still available even that test2 has just view access

**Comment by snipe** [comment]
This user is not an admin or a superadmin right?

**Comment by Rodiloo** [comment]
Nope he is not.
I actually noticed more problems with the Access Levels.

I tried to install a clean version on another server and had the same problems.

**Comment by snipe** [comment]
Are you still seeing this issue with the latest version?

**Comment by Rodiloo** [comment]
I'm on v4.1.11 and still seeing it unfortunately
