### ISSUE TITLE
Feature Request: Single user AD/LDAP Sync

### ISSUE THREAD

**Issue by lostmydog** [snipe/snipe-it#4634]
#### Expected Behavior (or desired behavior if a feature request)

Hey Snipe-IT! We just configured the AD/LDAP settings and it's fantastic! However, we can not rely on this feature in the future until there is an option to add a single user. What I suggest, is an option to search for a user by fname, lname, username etc. So, if I used this search feature and looked for 'Smith', Collin Smith, Jane Smith, and Bob Smith would return. I would then have a checkbox option to select which users I want to import. Or even better, the system could search and see that Collin and Jane are already in our database and automatically suggest we add Bob. As it currently stands, I can not simply 'sync' each time because we have many entities in our AD that our not real people, but instead special accounts for events and test cases and such.

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by CronKz** [comment]
Don't get me wrong, but in this case you are just having a bad LDAP/AD structure. A very simple solution would be to have all special accounts in a separate OU.

**Comment by lostmydog** [comment]
Just looked and we have 3 OU for our users, the other accounts are in a different OU. I have ours setup to sync the container OU for the 3 User OU. Is there a way that I can specify to sync only the 3 OU with actual users? Wasn't sure how to do this. Ours is setup like this:

Members:
          Location1
          Location2
          Location3
          Test

Currently I have Base Bind DN: OU=members, DC=test, DC=this, DC=site, DC=us
