### ISSUE TITLE
"Whoops" upon checkin and checkout

### ISSUE THREAD

**Issue by Expada** [snipe/snipe-it#4636]
#### Expected Behavior (or desired behavior if a feature request)

Upon checkout asset to user and send acceptance email, page show success: item checked out successfully

-----

#### Actual Behavior

Whoops, looks like something went wrong. cant view debug mode as well after changed to TRUE in .ENV

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode - debug mode not working
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - <b>upgrade</b>
- Version of Snipe-IT you're running - <b>4.18</b>
- Version of PHP you're running - <b>v7.19</b>
- Version of MySQL/MariaDB you're running - <b>5.7.19</b>
- What OS and web server you're running Snipe-IT on - <b>Win7 / wamp</b>
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - <b>manual now git</b>
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - <b>cant enter debug mode</b>
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - <b>checkout and checkin</b>
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - <b>nope</b>
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. - 
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - <b>nope</b>

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by Expada** [comment]
attached log file from storage

[laravel.log](https://github.com/snipe/snipe-it/files/1561488/laravel.log)

**Comment by snipe** [comment]
> [2017-12-15 11:06:15] production.ERROR: ErrorException: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in C:\wamp64\www\snipe-it\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php:94

Looks like the SSL for your mail server or the Snipe-IT server isn't configured properly.

**Comment by Expada** [comment]
hi snipe

i still haven't fix the issue regarding gmail.
there are 3 thing i would like to highlight after recent upgrade

1. for accepted assets, sig column is missing again. checked at the demo site and its the same no sig next to notes

2. is there a reason why i cant access debug mode? i was able before by modifying from .env to true but nothing happened unless i perform the git upgrade.php. i have to run that again to change it to false to make it work. any ideas?

3. gmail was working fine before. now i even cant send test from setting. logs as follows

Error: An Error has occured! stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

yes i have turned on the less secure app from google. have not make any changes except upgrading via git. thanks snipe. merry x'mas to you

**Comment by snipe** [comment]
> for accepted assets, sig column is missing again. checked at the demo site and its the same no sig next to notes

The signature column is not missing on the demo. You simply have to use the column selector. 

<img width="1384" alt="screen shot 2017-12-26 at 3 06 32 pm" src="https://user-images.githubusercontent.com/197404/34366286-71507cd6-ea4e-11e7-9a84-b1eb2cee788a.png">

> is there a reason why i cant access debug mode? 

My guess would be that you have to [clear your config cache](https://snipe-it.readme.io/docs/common-issues#section-changes-to-my-env-file-dont-seem-to-be-updating). 

> gmail was working fine before. now i even cant send test from setting

This is an SSL configuration issue, not a Snipe-IT issue. Try [this](https://laracasts.com/discuss/channels/laravel/error-sendmail-using-laravel-xampp-php-7-windows) maybe.

**Comment by Expada** [comment]
bout the signature is definitely my bad. how could i missed that. as well for config:clear, works like a charm
many thanks for that. SSL config that u suggested does not work. somehow i goggled and found that by changing in .env from `smtp` to `mail` do the trick

**Comment by Expada** [comment]
hi snipe, really need your help on this one, due to windows 7 license upgrade issue i have to perform system restore on the server pc. somehow after successful restore i was got this error. do i have to restore db from the backup in SQL?

`SQLSTATE[HY000]: General error: 1812 Tablespace is missing for table `snipeit`.`assets`. (SQL: select count(*) as aggregate from `assets` where `assets`.`deleted_at` is null`

**Comment by snipe** [comment]
Looks like your database got corrupted somehow. If you have any backups generated from the backup tool, I would use that. Otherwise you'll need to google for how to resolve your database issue (if it can even be fixed.)

Here are a few places to start:
https://superuser.com/questions/675445/mysql-innodb-lost-tables-but-files-exist
https://dba.stackexchange.com/questions/56849/innodb-tablespace-is-missing-for-table

**Comment by Expada** [comment]
finally i manage to resolve by creating new db and import those backup from myphpadmin. many thanks for that. as for gmail issue i changed from gmail to outlook then its all good. thanks again

**Comment by maverick85** [comment]
> bout the signature is definitely my bad. how could i missed that. as well for config:clear, works like a charm
> many thanks for that. SSL config that u suggested does not work. somehow i goggled and found that by changing in .env from `smtp` to `mail` do the trick

This did the trick.
