### ISSUE TITLE
Feature Request - printable inventory sheet improvement

### ISSUE THREAD

**Issue by rodeff** [snipe/snipe-it#4637]
#### Expected Behavior (or desired behavior if a feature request)
Great work with the printable inventory sheet. We are really appreciate it.

We were hoping if you can add checkboxes, so we can choose what information should be printed out.
Example: we would like to be able to add the purchase cost as well.
Also, if you can just select a date in a calendar, so it will display the assets checked out on this date or after that day.
This way, it can be used as Delivery acceptance form.

-----

#### Actual Behavior
Printable inventory sheet shows only the predefined fields.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Version of Snipe-IT you're running: 4.1.7 - updated 13.12.2017
Version of PHP you're running 7.1.9
Version of MySQL/MariaDB you're running 10.0.14
What OS and web server you're running Snipe-IT on - Windows 2016 - IIS10
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by jaybbhb** [comment]
Agree to what rodeff wrote.

I'd also suggest

- Logo company and some free text could also be added to the printing.
- Accessories could also be added (in same table, or a different one, doesn't matter)

I have to admit, it is a great improvement, thanks for that!

**Comment by rodeff** [comment]
Up
