### ISSUE TITLE
Feature Request: Customizable Dashboard Widget / or a blanco widget we can fill with information

### ISSUE THREAD

**Issue by pvhkai** [snipe/snipe-it#4638]
Dear SNIPE Team,

thanks a lot for all your work with the asset management system. 

From my point of view it would be nice to have blanco widget or a customizable widget in the dashboard, where I can put links in or just information for the colleagues. At the moment I always edit the footer part to add links - what is not very handy :)

Best regards,
pvhkai

**Comment by snipe** [comment]
This feature is on develop/master now. Go to Settings > Dashboard Text

**Comment by tutankh** [comment]
Can this be used to display alternative widgets? For example, breakdown of assets by category or model instead of by Status?

**Comment by snipe** [comment]
@tutankh No, it cannot do that at this time.

**Comment by nogears** [comment]
Will this be a feature in the near future?

**Comment by YourLastChance** [comment]
Is there a way to modify the "assets by status" widget so you can see other status? (i.e Ready to Deploy - Deployed)

**Comment by nitinraavi-atmecs** [comment]
Is there a way to modify the "assets by status" widget so you can see other status? (i.e Ready to Deploy - Deployed)
