### ISSUE TITLE
LDAP/AD Sync not working after upgrade to 4.1.6

### ISSUE THREAD

**Issue by yaman2k** [snipe/snipe-it#4641]
#### Expected Behavior (or desired behavior if a feature request)

LDAP login working after upgrade to 4.1.6
-----

#### Actual Behavior

Users cannot login into SnipeIT app after upgrading from 3.3.0 to 4.1.6.

-----

#### Please confirm you have done the following before posting your bug report:

- [YES ] I have enabled debug mode 
- [YES] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  UPGRADE
- Version of Snipe-IT you're running.  v4.1.6
- Version of PHP you're running.  5.6.15
- Version of MySQL/MariaDB you're running.  10.1.9
- What OS and web server you're running Snipe-IT on.  Windows/Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc).  Manual.
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error:  Error message:  **production.ERROR: There was an error authenticating the LDAP user: Could not c... error**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error:  Login page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. No
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.  N/A
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.  Same error message
- Include what you've done so far in the installation, and if you got any error messages along the way.  Upgrade went fine. All other functions are working perfectly.
- Indicate whether or not you've manually edited any data directly in the database.  No

I just upgraded from v3.3.0 to v4.1.6.  Everything works except LDAP sync.  I disabled that and re-enabled it, but it still doesn't work.   The only error message I am seeing is:
[2017-12-18 01:59:54] production.ERROR: There was an error authenticating the LDAP user: Could not create local user  
[2017-12-18 02:02:42] production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory 

I still kept a VM backup on v3.3.0 and that one has LDAP/AD integration working without any issues.

Attached is a screencapture of LDAP config.  Both LDAP sync and login show as successful.

![snipeit-ldap](https://user-images.githubusercontent.com/16481735/34094486-6cf5327e-e3de-11e7-92b8-b05d40391835.png)

**Comment by cordeosdev** [comment]
change your LDAP filter to 
&(cn=*)
try disabling LDAP sync
also - username field is case SENSITIVE on the LINUX server side if you installed on default case sensitive LINUX distro...   i.e. sAMAccountName != samaccountname

**Comment by yaman2k** [comment]
Thanks cordeosdev.  I tried change the LDAP filter to &(cn=*) and unchecked/checked LDAP sync.   
 Tested LDAP sync/bind for user and both are successful.  But still getting the same error when I try to long:  a local user cannot be created.

This is running Windows OS, and it's working fine on v3.3.0 with the same parameters posted above.

Still cannot understand why it won't work.

**Comment by yaman2k** [comment]
Appreciate feedback on this

**Comment by cordeosdev** [comment]
Please try create new/test AD account, ensure you can logon normally to AD from a standard computer then logon to SNIPE-IT web app to see if works.  This is to test if there is problem with sync account stored in web application but not affecting new AD account logon.  Make sure sync LDAP is NOT selected in settings.

**Comment by yaman2k** [comment]
I created a new user and made sure that I verified its credentials.  I then did the following:
- unchecked LDAP password sync
- unchecked/re-checked LDAP enabled box

I then tried to login with the newly created user and I keep getting the same error message:
production.ERROR: There was an error authenticating the LDAP user: Could not create local user 

I could do LDAP bind and test LDAP login, but for whatever reason the system won't let me create a local user.

**Comment by yaman2k** [comment]
I appreciate if I can have any pointers on this.

**Comment by sidrulz** [comment]
i have the same issue , after upgrading to v4. I cannot login with a new LDAP user on v4. Old users who were migrated works fine.

**Comment by tavitas** [comment]
I'm having the same issue with this on version 4.2 Did anyone manage to get this working? Thanks in advance

**Comment by omatsei** [comment]
I'm having the same problem. We upgraded from 3.6 to 4.1.11 a couple months ago, and just realized that new users can't log in.

**Comment by omatsei** [comment]
Scratch that. We ended up fixing it by changing the LDAP filter to the following:

&(objectcategory=person)(objectclass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2))
