### ISSUE TITLE
import Asset

### ISSUE THREAD

**Issue by ahmadsss** [snipe/snipe-it#4642]
#### Expected Behavior (or desired behavior if a feature request)

when i import asset from csv file (created from the sample csv files) in the dashboard it should show deployed in the asset status graph but instead it shows pending, i changed the status in the csv file to deployed and import it again, now its showing deployed with orange color
also, when i go to any location it shows now users nor assets
-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ yes] I have enabled debug mode 
- [ yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? FRESH
- Version of Snipe-IT you're running - v4.1.8 - build 3106 (master)
- Version of PHP you're running - PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
- Version of MySQL/MariaDB you're running - Server version: 5.7.20-0ubuntu0.16.04.1 (Ubuntu)
- What OS and web server you're running Snipe-IT on - Ubuntu 16.0.4 Server version: Apache/2.4.18 (Ubuntu)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. no errors in installation
- Indicate whether or not you've manually edited any data directly in the database - none

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help
![2](https://user-images.githubusercontent.com/7396167/34098878-e545d02a-e3ee-11e7-96e2-3264cc33a555.PNG)
![3](https://user-images.githubusercontent.com/7396167/34098883-e64ae03c-e3ee-11e7-871a-174cfd0400b6.PNG)
![4](https://user-images.githubusercontent.com/7396167/34098884-e6955234-e3ee-11e7-88f6-1830bad15c7e.PNG)
![1](https://user-images.githubusercontent.com/7396167/34098885-e6b313d2-e3ee-11e7-8cca-f908333243b2.PNG)

**Comment by ahmadsss** [comment]
as i test, i cleaned my data and purged deleted records, then i imported the same data on the demo site. same issue, the import is not doing it right. i also noticed that the import is not mapping most of the fields even when using the sample or when using the demo site exported data.

**Comment by snipe** [comment]
@dmeltzer can you take a look?

**Comment by ahmadsss** [comment]
updates:
i fresh installed 4.1.9 which seems to have the same issue, what i do understand so far, the importer is fulfilling the deployment process cause i did check-in then check-out for an asset and it showed in location page, bulk edit for assets is not working when changing status.

**Comment by ahmadsss** [comment]
there is a field titled "type" in the csv file exported from the Demo site, that field is not having a match when importing. 
![image](https://user-images.githubusercontent.com/7396167/34401438-5a9c6cb6-ebac-11e7-8c0a-529615caa166.png)

**Comment by snipe** [comment]
@ahmadsss the importer does not currently support importing assets assigned to anything other than users.

**Comment by ahmadsss** [comment]
so by default, it will auto assign the asset to the corresponding user as per the csv ?
i will try the hosted version.

**Comment by dmeltzer** [comment]
I'm a bit confused about what the issue your experiencing is.  Are you saying that if the status label isn't deployed then the items do not show up as deployed?  If not, can you clarify a bit more?

**Comment by ahmadsss** [comment]
@dmeltzer I did fresh installation, I want to import my assets. when I do it works but neither the assets nor the users are showing when I browse a location. to make sure my CV file is not the issue I exported the assets from the demo site and imported it into my fresh installed site. same issue appears.

**Comment by dmeltzer** [comment]
Is this the same as #4563 then?

**Comment by ahmadsss** [comment]
Yes, its the same. But i added the status issue its giving orange color even when import it as deployed. Add to that when i bulk edit the assets to change the status it dont change unless i manually chekin checkout each asset
