### ISSUE TITLE
archived Assets are not changeable

### ISSUE THREAD

**Issue by masterofdesaster300** [snipe/snipe-it#4643]
I am working on version 4.19-pre
It is not possible to change the status of an archived asset and because 
of that, there is no possibility to change something in the asset. 
There is only the error message asset status ist not deploayble, asset can not be checkout when i try to save changes.
This problem is only in this version. In v4.18 there is all good.

**Comment by snipe** [comment]
I'm not sure I understand - you can't check out an archived asset (by design). Can you tell me if there's anything in your app error logs? Screenshots would be helpful here too.

**Comment by masterofdesaster300** [comment]
The asset is not editable because of the status because on all other status labels there is no problem to edit the title of the items but when i try to edit the title of an archived asset i get this error?! I only want to change the title, not the status lable.

![screenshot snipe it fehler](https://user-images.githubusercontent.com/32192839/34206657-bfbc6c66-e587-11e7-8f2a-7625aa17984a.PNG)

**Comment by snipe** [comment]
Does it actually prevent you from editing anything though? That message just lets you know that you couldn't check it out if you wanted to.

**Comment by masterofdesaster300** [comment]
Yes it prevent me from editing anything. You can change nothing but if i create a new asset with a different status label all is editable like normal.

**Comment by masterofdesaster300** [comment]
But in the actual version v4.19 it works. Thank you whatever youve done;)
