### ISSUE TITLE
Upgraded to 4.1.9 - cannot view signatures

### ISSUE THREAD

**Issue by worthy92** [snipe/snipe-it#4645]
#### Expected Behavior (or desired behavior if a feature request)

When looking at the asset history we used to be able to see users signatures when they accepted an asset.

-----

#### Actual Behavior

Since upgrading to 4.1.9 the History tab on an asset does not show the signature.

-----

#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **UPGRADE**
- Version of Snipe-IT you're running **4.1.9**
- Version of PHP you're running **7.1.1**
- Version of MySQL/MariaDB you're running **5.6.23**
- What OS and web server you're running Snipe-IT on **Server 2012 R2 - IIS 8.5**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Git**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **N/A**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **Asset History**
- If a stacktrace is provided in the error, include that too. **N/A**
- Any errors that appear in your browser's error console. **NONE**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. **Appears so but can't test for sure**
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. **None**
- Include what you've done so far in the installation, and if you got any error messages along the way. **Cleared browser history, checked signatures are in the appropriate folder**
- Indicate whether or not you've manually edited any data directly in the database **No**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Did you select the signature column from the history table? 

<img width="370" alt="screen shot 2017-12-19 at 1 39 27 pm" src="https://user-images.githubusercontent.com/197404/34180047-12bdb008-e4c2-11e7-8e53-84620c1b3b70.png">

**Comment by worthy92** [comment]
Thanks Snipe!! No I hadn't selected the signature column from history. Have now! ;)

Thanks again - keep up the great work. It's really a fantastic platform! 👍 :)

**Comment by sanilsfo** [comment]
Signature is not listed in column selection.
SnipeIT Version 4.7.7
