### ISSUE TITLE
LDAP Sync not working with Active Directory  ldap_search(): Search: Bad search filter

### ISSUE THREAD

**Issue by hdev-moliver** [snipe/snipe-it#4646]
#### Expected Behavior (or desired behavior if a feature request)

Expect to be able to test ldap to AD server and have it work

-----

#### Actual Behavior

Test LDAP sync says success.  Test LDAP Login looks like it auths properly but says " ldap_search(): Search: Bad search filter"

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
fresh

- Version of Snipe-IT you're running 
Version v4.1.8 - build 3106 (master)

- Version of PHP you're running
5.6.32

- Version of MySQL/MariaDB you're running
mariadb-5.5.56

- What OS and web server you're running Snipe-IT on
centos / apache

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

[2017-12-18 18:20:18] production.ERROR: exception 'ErrorException' with message 'ldap_search(): Search: Bad search filter' in /var/www/html/snipeit/app/Models/Ldap.php:262
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'ldap_search(): ...', '/var/www/html/s...', 262, Array)
#1 /var/www/html/snipeit/app/Models/Ldap.php(262): ldap_search(Resource id #523, 'DC=halonlan, DC...', '()')
#2 /var/www/html/snipeit/app/Console/Commands/LdapSync.php(71): App\Models\Ldap::findLdapUsers()
#3 [internal function]: App\Console\Commands\LdapSync->handle()
#4 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(30): call_user_func_array(Array, Array)
#5 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#7 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#8 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#9 /var/www/html/snipeit/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#10 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(168): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#11 /var/www/html/snipeit/vendor/symfony/console/Application.php(936): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/snipeit/vendor/symfony/console/Application.php(240): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\LdapSync), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/snipeit/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/snipeit/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 {main}  
error

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
http://snipeit.halon.com/admin/ldap

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.

Just using a the basic &(cn=*) filter.  
Base Bind DN is just a really basic dc=domain,dc=local

 php artisan snipeit:ldap-sync --summary executes but returns nothing

- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by cordeosdev** [comment]
Here are LDAP settings that work for us...

![image](https://user-images.githubusercontent.com/34620515/34142821-34c22146-e4c4-11e7-9ba7-544233c22811.png)

![image](https://user-images.githubusercontent.com/34620515/34142838-6be7f088-e4c4-11e7-8052-238ea314cfb8.png)

**Comment by ahmadsss** [comment]
@cordeosdev  LDAP Bind Username should be in binduser@example.com format, right ?

**Comment by hdev-moliver** [comment]
Thanks @cordeosdev!  The LDAP Authentication query of  sAMAccountName= seems to have fixed it.  Perhaps make that the default?  @ahmadsss LDAP Bind username I used was username@domain.com

**Comment by nguyentadat** [comment]
hi bro
Please help me: It doesn't look like the LDAP extension is installed or enabled on this server. :(

**Comment by malte200900** [comment]
@nguyentadat mine also says "It doesn't look like the LDAP extension is installed or enabled on this server. :("

Anyone that can tell me where to enable it?

**Comment by nguyentadat** [comment]
Im sorry . Because i dont help you.I dont fix itTrân trọng, Đạt Nguyễn ------------****-------------  Thank you & Best regards,Nguyễn Tá Đạt (Mr.)Đ/c: 320 Lê Lai, Ngô Quyền, Hải Phòng Phone: 0935.598.895Email:dat.nguyen@alotech.com.vn              Website: https://alotech.com.vnVào 15 Th8, 2018 19:41, malte200900 <notifications@github.com> đã viết:@nguyentadat mine also says "It doesn't look like the LDAP extension is installed or enabled on this server. :("
Anyone that can tell me where to enable it?
