### ISSUE TITLE
Print All Assigned not work for all users

### ISSUE THREAD

**Issue by miguelpalma81** [snipe/snipe-it#4648]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

Print All Assigned
-----

#### Actual Behavior
Whoops, looks like something went wrong

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade
- Version of Snipe-IT you're running
v4.1.8
- Version of PHP you're running
V7.1.11
- Version of MySQL/MariaDB you're running
Mariadb
- What OS and web server you're running Snipe-IT on
Centos7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

ErrorException
Trying to get property of non-object (View: /var/www/snipe-it/resources/views/users/print.blade.php)

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I need a more complete stack trace here.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
