### ISSUE TITLE
Server Error: 500 (Internal Server Error)

### ISSUE THREAD

**Issue by bthurtson** [snipe/snipe-it#465]
Need guidance, I just finished the install script provided by GR360RY. Everything seems to have installed fine. When trying to connect to the machine I receive a server 500 error. The machine is a freshly rebuilt ubuntu server 14.04. It was a bare install with no LAMP stack. I ran the  script provided (wget --no-check-certificate https://raw.github.com/GR360RY/snipeit-ansible/master/scripts/snipeit.sh -O - | sh).

**Comment by bthurtson** [comment]
from debug

ErrorException
Trying to get property of non-object (View: /opt/snipe-it/app/views/backend/layouts/default.blade.php) (View: /opt/snipe-it/app/views/backend/layouts/default.blade.php) (View: /opt/snipe-it/app/views/backend/layouts/default.blade.php)

**Comment by HinchK** [comment]
hey bthurtson!  

If there is no LAMP stack, that's a problem.....I'm assuming this is not the case and that you indeed have PHP >= 4.5.0, MySQL, and maybe Apache.

Let's rundown each piece of the system+application:

#### System Environment

Make sure the storage and upload folders are writable

    chmod -R 755 app/storage
    chmod -R 755 public/uploads

Make sure mcrypt is installed for PHP.

    sudo apt-get install php5-mcrypt
    sudo php5enmod mcrypt

####Web Server

snipe-it's documentation under [5) Setting up your web server](http://docs.snipeitapp.com/linuxosx/README.html) is pretty bulletproot...if you have exhausted all the available documentation and you are still having an issue - i would change tack with your VM.

The Laravel team recently released a virtualized dev environment using vagrant that is as quick and painless as they come.  I highly recommend checking it out: [Laravel Homestead][http://laravel.com/docs/4.2/homestead)

Clone the repository, run `composer install`, and then run through the snipe-it installation documentation: http://docs.snipeitapp.com/linuxosx/README.html.

Don't stress about the nginx configuration part....to serve the application in Homestead, run `serve localhost /vagrant/home/path/to/snipe-it/public`

I can't stress enough how easy Laravel/Homestead made it for me.  Even if you have no interest in working with Laravel, it might be the most cut and dry virtualized php web application environment in existence.

**Comment by bthurtson** [comment]
I just blew it away and started over not doing the script. Got it running now.
