### ISSUE TITLE
Wrong chart color

### ISSUE THREAD

**Issue by ufficioIT** [snipe/snipe-it#4655]
#### Expected Behavior (or desired behavior if a feature request)

Changing the Chart color setting of a custom status in the "Status Labels" page should reflect the color of the same status in the Dashboard Chart.

-----

#### Actual Behavior

Changing the Chart color setting of a custom status (in my case) in the "Status Labels" page changes the color of another status (in my case the "Ready to Deploy" status) in the Dashboard Chart.

Here some screenshots:

Changing the chart color in blue for my custom status:
![cattura](https://user-images.githubusercontent.com/33057507/34201630-68fa2178-e575-11e7-9a6c-c0097f94b99e.PNG)

And here the result:
![cattura2](https://user-images.githubusercontent.com/33057507/34201631-69128da8-e575-11e7-893c-9e619e117b18.PNG)

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

_- Is this a fresh install or an upgrade?_ 
This is an upgrade from 4.1.8 to 4.1.9pre.

_- Version of Snipe-IT you're running_
4.1.9pre

_- Version of PHP you're running_
7.0.22

_- Version of MySQL/MariaDB you're running_
5.7.20

_- What OS and web server you're running Snipe-IT on_
Ubuntu 16.04.3 LTS with Apache/2.4.18

_- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)_
GIT

_- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error_
There are no errors in debug mode.

_- Any errors that appear in your browser's error console._
There are no errors in the Browser Console (Chrome 63).

_- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo._
Yes, same behavior in the demo.

_- Include any additional information you can find in `app/storage/logs` and your webserver's logs._
There are no info about my issue in the logs.

_- Include what you've done so far in the installation, and if you got any error messages along the way._
php upgrade.php, no errors during the upgrade.

_- Indicate whether or not you've manually edited any data directly in the database_
No editing.

**Comment by inietov** [comment]
This is an old issue and I couldn't replicate it. Can you @ufficioIT try to update your Snipe-IT install and got back to reopen this if that was enough to fix it? (I hide a piece of the cake so the color got shown)

![image](https://user-images.githubusercontent.com/653557/235810899-d6f55a25-65a2-4c7c-8413-e4265e6a5ba0.png)

![image](https://user-images.githubusercontent.com/653557/235810999-cf4bdbfe-c044-4d80-af8b-fcaf8d23153c.png)
