### ISSUE TITLE
custom mail send on action log when got status missing

### ISSUE THREAD

**Issue by amarbhanu** [snipe/snipe-it#4656]
Snipe IT Version v4.1.4
Now window
install.sh

Can you suggest me what is code for custom mail send easily and as custom requirement when action log got Missing status.

**Comment by snipe** [comment]
I don't understand what you're asking for.

Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by amarbhanu** [comment]
Only send mail as define by your structure on my condition and place

**Comment by snipe** [comment]
Again, I don't know what you're asking for here.

**Comment by amarbhanu** [comment]
I am sending a mail every user so as provided snipeIT code toMail function. but here not mention `To` and `From`   So i asked you if snipeIT have any function for mail we use any place for mail then i will use it, if you know then please suggest, otherwise i will use to Laravel mail code.

**Comment by snipe** [comment]
Snipe-IT uses Laravel notifications and Swiftmailer.
