### ISSUE TITLE
License History not updated

### ISSUE THREAD

**Issue by kenpachi13** [snipe/snipe-it#466]
License is already "check in" See image 1 

Image 1
![image](https://cloud.githubusercontent.com/assets/10649463/5851806/4cdb1f66-a247-11e4-94c4-c6c7bced36f4.png)

but when you edit the entry, then save, it is back to "check out"

Image 2
![image](https://cloud.githubusercontent.com/assets/10649463/5851821/98fd897e-a247-11e4-9f3f-f57ec792032b.png)

**Comment by snipe** [comment]
What version of Snipe-IT are you running?

**Comment by kenpachi13** [comment]
this is OK now.
Closing ticket
