### ISSUE TITLE
LDAP not authenticating from subgroups

### ISSUE THREAD

**Issue by shindelhu** [snipe/snipe-it#4660]
#### Expected Behavior (or desired behavior if a feature request)

LDAP authentication to work.

-----

#### Actual Behavior

if I set People as the base bind DN in our ldap, users can't authenticate with their LDAP password. There are serveral subgroups under People, if I set any of them as Base Bind DN, then the users in it are able to authenticate. So it looks like your ldap query doesn't "dig" further down to the subgroups.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
upgarde
- Version of Snipe-IT you're running
4.1.6
- Version of PHP you're running
7
- Version of MySQL/MariaDB you're running
5.6.38
- What OS and web server you're running Snipe-IT on
RHEL7, apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual upgrade
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
no
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
LDAP
- If a stacktrace is provided in the error, include that too.
no
- Any errors that appear in your browser's error console.

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
no
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

[2017-12-20 16:04:29] production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory

- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by CronKz** [comment]
There is an open pull-request for that... #4572 
But it still wasn't merged yet.
