### ISSUE TITLE
Manage Custom Fields Bug

### ISSUE THREAD

**Issue by Tzvetelin88** [snipe/snipe-it#4662]
#### Expected Behavior (or desired behavior if a feature request)

Using new Custom Fields in Assets.

-----

#### Actual Behavior

When I create new Custom Fields in "Manage Custom Fields" and then add them to the "FiledSets" I expect to see those new fileds when editing or creating new Asset. But unfortunately this not work. I don't see my new Fieldset when creating or editing assets. 

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? -> Fresh install
- Version of Snipe-IT you're running  -> v4.1.9-pre - build 3117 (master)
- Version of PHP you're running        -> PHP7
- Version of MySQL/MariaDB you're running ->5.5.58
- What OS and web server you're running Snipe-IT on ->Debian GNU/Linux 8, Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) -> Git Clone
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error -> 
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error -> No error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. -> Yes in the Demo is the same.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database -> No data has been edited directly in the db.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
How are you testing that on the demo? There aren't any field sets associated with models that have any fields in them.

Please give me the url of a specific asset w/an expected fieldset.

<img width="1381" alt="screen shot 2017-12-20 at 9 26 24 am" src="https://user-images.githubusercontent.com/197404/34220021-e284704c-e567-11e7-8c11-7ab3d3552135.png">

**Comment by Tzvetelin88** [comment]
Oh my, I'm so sorry. I didn't get the configuration right.  Closing that ticket. Please excuse me

**Comment by snipe** [comment]
No worries. It can be a little confusing - if there are updates you can suggest for [our documentation on custom fields and fieldsets](https://snipe-it.readme.io/docs/custom-fields) that might make it clearer, please let us know.
