### ISSUE TITLE
missing components icon on left sidebar (non-superadmin users)

### ISSUE THREAD

**Issue by nikmohdaiman** [snipe/snipe-it#4670]
#### Expected Behavior (or desired behavior if a feature request)

can see components icon on left sidebar

-----

#### Actual Behavior

components icon is missing on left sidebar

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
  **an upgrade**
- Version of Snipe-IT you're running
   **v4.1.8 - build 3106**
- Version of PHP you're running
   **7.0.22**
- Version of MySQL/MariaDB you're running
   **MySQL 5.7.20**
- What OS and web server you're running Snipe-IT on
  **Ubuntu Server 16.04.3**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  **manual installation**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
   **all pages**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by nikmohdaiman** [comment]
below are given permissions
 Components: view -yes
 Components: create -yes
 Components: edit -yes
 Components: delete -no
 Components: checkout -yes
 Components: checkin -yes

**Comment by snipe** [comment]
> Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo
