### ISSUE TITLE
Cannot edit info on asset

### ISSUE THREAD

**Issue by S0lidARRAY** [snipe/snipe-it#4672]
When i try to edit any asset the data cannot be saved. Recent logging show that column is not found. Is this related? Thanks.

Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'log_meta' in 'field list' (SQL: insert into `action_logs` (`item_type`, `item_id`, `created_at`, `user_id`, `log_meta`, `action_type`, `company_id`, `updated_at`) values (App\Models\Asset, 359, 2017-12-21 18:39:24, 1, {"serial":{"old":"5CD62596JW","new":"5CD62596JWasd"}}, update, 3, 2017-12-21 18:39:24)) in E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Database\Connection.php:647
Stack trace:
#0 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Database\Connection.php(607): Illuminate\Database\Connection->runQueryCallback('insert into `ac...', Array, Object(Closure))
#1 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Database\Connection.php(450): Illuminate\Database\Connection->run('insert into `ac...', Array, Object(Closure))
#2 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Database\Connection.php(404): Illuminate\Database\Connection->statement('insert into `ac...', Array)
#3 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Database\Query\Processors\Processor.php(32): Illuminate\Database\Connection->insert('insert into `ac...', Array)
#4 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(2133): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ac...', Array, 'id')
#5 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php(1251): Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(688): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#7 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(653): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#8 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(522): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#9 E:\xampp\htdocs\snipeit\app\Models\Actionlog.php(150): Illuminate\Database\Eloquent\Model->save()
#10 E:\xampp\htdocs\snipeit\app\Observers\AssetObserver.php(43): App\Models\Actionlog->logaction('update')
#11 [internal function]: App\Observers\AssetObserver->updating(Object(App\Models\Asset))
#12 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(367): call_user_func_array(Array, Array)
#13 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(199): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('eloquent.updati...', Array)
#14 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(159): Illuminate\Events\Dispatcher->dispatch('eloquent.updati...', Array, true)
#15 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasEvents.php(148): Illuminate\Events\Dispatcher->until('eloquent.updati...', Object(App\Models\Asset))
#16 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(578): Illuminate\Database\Eloquent\Model->fireModelEvent('updating')
#17 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(515): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder))
#18 E:\xampp\htdocs\snipeit\app\Http\Controllers\AssetsController.php(371): Illuminate\Database\Eloquent\Model->save()
#19 [internal function]: App\Http\Controllers\AssetsController->update(Object(App\Http\Requests\AssetRequest), '359')
#20 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(55): call_user_func_array(Array, Array)
#21 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('update', Array)
#22 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\AssetsController), 'update')
#23 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Route.php(160): Illuminate\Routing\Route->runController()
#24 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(572): Illuminate\Routing\Route->run()
#25 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 E:\xampp\htdocs\snipeit\vendor\laravel\passport\src\Http\Middleware\CreateFreshApiToken.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 E:\xampp\htdocs\snipeit\app\Http\Middleware\CheckForTwoFactor.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckForTwoFactor->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 E:\xampp\htdocs\snipeit\app\Http\Middleware\CheckLocale.php(42): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#42 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#49 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#50 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#51 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#52 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#53 E:\xampp\htdocs\snipeit\vendor\barryvdh\laravel-debugbar\src\Middleware\Debugbar.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 E:\xampp\htdocs\snipeit\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 E:\xampp\htdocs\snipeit\vendor\fideloper\proxy\src\TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 E:\xampp\htdocs\snipeit\app\Http\Middleware\CheckForSetup.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 E:\xampp\htdocs\snipeit\app\Http\Middleware\NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 E:\xampp\htdocs\snipeit\app\Http\Middleware\ContentSecurityPolicyHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\ContentSecurityPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 E:\xampp\htdocs\snipeit\app\Http\Middleware\ReferrerPolicyHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#72 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\ReferrerPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#74 E:\xampp\htdocs\snipeit\app\Http\Middleware\XssProtectHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#75 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 E:\xampp\htdocs\snipeit\app\Http\Middleware\FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#78 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#79 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#80 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#81 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#82 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#83 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#84 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#85 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#86 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#87 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#88 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#89 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#90 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#91 E:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#92 E:\xampp\htdocs\snipeit\public\index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#93 {main}

**Comment by snipe** [comment]
Did you run migrations when you upgraded?

**Comment by S0lidARRAY** [comment]
I use "php upgrade.php" method because i install snipe-it by pulling from git. Also v4.1.8 is working just fine before.

**Comment by snipe** [comment]
Migrations didn't run though - or they did, and something failed. Can you try tailing your app log file and running `php artisan migrate`?

**Comment by S0lidARRAY** [comment]
After running "php artisan migrate" the following log is show.

In Connection.php line 647:

  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'last_audit_date' (SQL: alter table `assets` add `last_audit_date` datetime null after `assigned_type`)

In PDOStatement.php line 107:

  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'last_audit_date'

In PDOStatement.php line 105:

  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'last_audit_date'

**Comment by S0lidARRAY** [comment]
Figure it out myself. After manually deleteing "last_audit_date" column in the snipe-it database and running migration again. I was able to edit and update assets info.
