### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Log' not found in When upgrading from v3 to v4

### ISSUE THREAD

**Issue by DanielBadri** [snipe/snipe-it#4673]
#### Expected Behavior (or desired behavior if a feature request)

Following this guide: https://snipe-it.readme.io/v4.0/docs/upgrading-to-v4
running php artisan migrate should run successfully

-----

#### Actual Behavior

When running php artisan migrate, the following error accours

`PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/html/app/Exceptions/Handler.php:39
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(320): App\Exceptions\Handler->report(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(132): Illuminate\Foundation\Console\Kernel->reportException(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#2 /var/www/html/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 {main}
  thrown in /var/www/html/app/Exceptions/Handler.php on line 39
`

-----

#### Please confirm you have done the following before posting your bug report:

- [Y] I have enabled debug mode 
- [Y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
upgrade
- Version of Snipe-IT you're running
3.6.3
- Version of PHP you're running
7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running
5.7.20-0ubuntu0.16.04.1
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Following this guide: https://snipe-it.readme.io/v4.0/docs/upgrading-to-v4
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
No folder named storage under app
- Include what you've done so far in the installation, and if you got any error messages along the way.
Followed the guide
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/common-issues#section-class-awslaravelawsserviceprovider-not-found-or-class-log-not-found

**Comment by hixair** [comment]
Getting the same issues with "Class 'Log' not found in /var/www/snipeit/app/Exceptions/Handler.php:39" (I used the sh installer) and your link to a common issue section seems dead :(
Thanks !

**Comment by snipe** [comment]
@hixair the page moved to a specific page about install/upgrade issues. You could also have used the search in the documentation site. https://snipe-it.readme.io/docs/installation-issues#section-fatal-error-uncaught-exception-reflectionexception-with-message-class-log-does-not-exist

**Comment by barkermn01** [comment]
This Error is present on windows with a fresh install.

```
PHP Fatal error:  Uncaught Error: Class 'Log' not found in C:\inetpub\wwwroot\snipe-it\app\Exceptions\Handler.php:39
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(314): App\Exceptions\Handler->report(Object(Dotenv\Exception\InvalidFileException))
#1 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(118): Illuminate\Foundation\Http\Kernel->reportException(Object(Dotenv\Exception\InvalidFileException))
#2 C:\inetpub\wwwroot\snipe-it\public\index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#3 {main}
  thrown in C:\inetpub\wwwroot\snipe-it\app\Exceptions\Handler.php on line 39
```

i have tried 

```
composer dump-autoload
composer clear-compiled
php artisan config:clear
php artisan view:clear
php artisan cache:clear
php artisan route:clear
```

Composer reports `[Symfony\Component\Console\Exception\CommandNotFoundException]
Command "clear-compiled" is not defined.` for command `composer clear-compiled` 

All others work,

checked https://snipe-it.readme.io/docs/installation-issues#section-fatal-error-uncaught-exception-reflectionexception-with-message-class-log-does-not-exist

And my Values are
```
MAIL_FROM_ADDR=assets@xxx.com
MAIL_FROM_NAME='Asset Managment System'
MAIL_REPLYTO_ADDR=assets@xxx.com
MAIL_REPLYTO_NAME='Asset Manaagment'
```

**Comment by gradinar** [comment]
Can not make it work 
[Fri Feb 01 15:05:44.090787 2019] [php7:error] [pid 12614] [client 10.15.34.34:52214] PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/snipeit/app/Exceptions/Handler.php:39\nStack trace:\n#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Dotenv\\Exception\\InvalidFileException))\n#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Dotenv\\Exception\\InvalidFileException))\n#2 /var/www/snipeit/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))\n#3 {main}\n  thrown in /var/www/snipeit/app/Exceptions/Handler.php on line 39

I have already tried the links above

**Comment by gradinar** [comment]
Hi, 
The setup was done, but this is what I have when I try to access the system:
![snipeit](https://user-images.githubusercontent.com/47244658/52135899-cd8e6580-263e-11e9-9962-323d435cd386.jpg)

**Comment by chasse20** [comment]
This issue persists on Ubuntu 18.04 if you use a fresh install and follow the instructions about copying the .env.example file. It seemed to work after commenting out the default "GOOGLE_MAPS_API=" line entirely.

**Comment by tavinus** [comment]
Thanks for this! Lost a few hours on it...
> 
> 
> This issue persists on Ubuntu 18.04 if you use a fresh install and follow the instructions about copying the .env.example file. It seemed to work after commenting out the default "GOOGLE_MAPS_API=" line entirely.

Just installed on a Debian9 LXC container using the install script and got a blank page.  
  
**Commenting the mentioned line at the end of `/var/www/snipeit/.env` solved it!**  
Thanks!
```
#GOOGLE_MAPS_API=
```
![image](https://user-images.githubusercontent.com/8039413/71332902-c30ae200-2516-11ea-8a1d-de8b4d4a8387.png)

**Comment by morrismichaelc** [comment]
This did not help me... BUT, probably just adding "null" to the end of the line would work too, when this line is the problem. Note that there are no other valueless assignments in the file...
