### ISSUE TITLE
OpenSSL for outgoing mails

### ISSUE THREAD

**Issue by Canem** [snipe/snipe-it#4674]
#### Expected Behavior (or desired behavior if a feature request)

Email a user there credentials when creating new user

-----

#### Actual Behavior

The user does get created. But the mails fails and i get this error:

ErrorException in StreamBuffer.php line 94:
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
Running  v3.6.6

- Version of PHP you're running
php version 7.1.7

- Version of MySQL/MariaDB you're running
mysql  Ver 15.1 Distrib 10.1.25-MariaDB, for Win32 (AMD64)

- What OS and web server you're running Snipe-IT on
Windows 10 using xampp

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual installation

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
In admin/users/create trying to create user en mailing credentials

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
ErrorException in StreamBuffer.php line 94:
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
It is not

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
We have not

How i have my settings in .env for outgoing mail

```
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=snipeit.zelfstroom@gmail.com
MAIL_PASSWORD=REDACTED
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=snipeit.zelfstroom@gmail.com
MAIL_FROM_NAME='Zelfstroom Beheer'
MAIL_REPLYTO_ADDR=support@zelfstroom.nl
MAIL_REPLYTO_NAME='Snipe-IT'
```

First few lines from logs

`[2017-12-21 13:22:34] production.ERROR: ErrorException: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in C:\xampp\htdocs\snipeit\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php:94
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'stream_socket_e...', 'C:\\xampp\\htdocs...', 94, Array)
#1 C:\xampp\htdocs\snipeit\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php(94): stream_socket_enable_crypto(Resource id #481, true, 9)
#2 C:\xampp\htdocs\snipeit\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\EsmtpTransport.php(313): Swift_Transport_StreamBuffer->startTLS()
#3 C:\xampp\htdocs\snipeit\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\AbstractSmtpTransport.php(118): Swift_Transport_EsmtpTransport->_doHeloCommand()
#4 C:\xampp\htdocs\snipeit\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#5 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(385): Swift_Mailer->send(Object(Swift_Message), Array)
#6 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Mail\Mailer.php(171): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#7 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(221): Illuminate\Mail\Mailer->send('emails.send-log...', Array, Object(Closure))
#8 C:\xampp\htdocs\snipeit\app\Http\Controllers\UsersController.php(173): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#9 [internal function]: App\Http\Controllers\UsersController->postCreate(Object(App\Http\Requests\SaveUserRequest))
#10 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(80): call_user_func_array(Array, Array)
#11 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(146): Illuminate\Routing\Controller->callAction('postCreate', Array)
#12 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(94): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\UsersController), Object(Illuminate\Routing\Route), 'postCreate')
#13 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#14 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#15 [internal function]: Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(96): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#18 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(54): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(App\Http\Controllers\UsersController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'postCreate')
#19 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Route.php(174): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'App\\Http\\Contro...', 'postCreate')
#20 C:\xampp\htdocs\snipeit\vendor\laravel\framework\src\Illuminate\Routing\Route.php(140): Illuminate\Routing\Route->runController(Object(Illuminate\Http\Request))`

**Comment by snipe** [comment]
Did you do the additional things that were outlined in the Using Gmail section of the docs? https://snipe-it.readme.io/docs/configuration#section-using-gmail

**Comment by Canem** [comment]
yes i did those. Still no luck

**Comment by Canem** [comment]
Also just update updated to v4.1.9

**Comment by Canem** [comment]
Hey Snipe,

I tried the new section in common issues. https://snipe-it.readme.io/docs/common-issues#section-unable-to-send-email-using-gmail

But keep getting the same error
![mail error](https://user-images.githubusercontent.com/7311197/35044766-dfd4c582-fb91-11e7-91e4-616252459d59.png)

When i set the mail-driver to 'mail' it will say the email is send but i will never actually receive the email.

**Comment by sidiabale** [comment]
Hi @snipe,

We're facing this problem as well. Do you have any update for us on how to proceed as this is blocking at the moment. Thanks in advance for your support!

**Comment by snipe** [comment]
This isn't really a Snipe-IT issue, it's a PHP/SSL configuration issue. You can try using port 465 instead of 587, and/or confirm that OpenSSL is installed and the `php_openssl` extension is enabled. 

Some other possible solutions:
https://stackoverflow.com/a/48131493/200021
https://stackoverflow.com/questions/31460941/php-5-6-ssl-certificate-verify
