### ISSUE TITLE
Question: Editing existing fields?

### ISSUE THREAD

**Issue by blackout1231** [snipe/snipe-it#4677]
#### Expected Behavior (or desired behavior if a feature request)
I am not sure what the current behavior should be, I've researched briefly, this is more of a general question. It's possible I am just going about this the wrong way.
(what you expect to happen goes here)

-----

#### Actual Behavior
I am curious if we are able to edit the existing fields, for example:

I would like to change Status to Lifecycle Status as it applies to assets, I can always create a custom field, called Lifecycle Status and apply it to Assets, however I have already created a custom field to help sort equipment located at specific Sites, and you can only assign one Custom Fieldset at a time to any one asset.
![image](https://user-images.githubusercontent.com/34345402/34273730-34163410-e65b-11e7-889e-5d941f61c9cb.png)

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [N ] I have enabled debug mode 
- [N] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running v4.1.8-pre build 3068 (gceca76b)
- Version of PHP you're running 7.0.23
- Version of MySQL/MariaDB you're running 5.4.29
- What OS and web server you're running Snipe-IT on WAMP via Windows Server 2012R2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) installl.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - NO ERRORS, General Question
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
That's not possible at this time and is not on the short term roadmap. You can create your own language files and potentially customize and use those to handle field labels.
