### ISSUE TITLE
Error upgrading from v3 to v4

### ISSUE THREAD

**Issue by bagetsro** [snipe/snipe-it#4679]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)
im doing the step "php artisan migrate"
-----

#### Actual Behavior

(what actually happens goes here)
In aws.php line23:
    Class 'Aws\Laravel\AwsServiceProvider' not found
![image](https://user-images.githubusercontent.com/20238789/34287590-21ca52a0-e723-11e7-84b9-673807fceece.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  -upgrade
- Version of Snipe-IT you're running -3.6.3
- Version of PHP you're running -PHP 7.0.8
- Version of MySQL/MariaDB you're running -10.1
- What OS and web server you're running Snipe-IT on -windows 7, IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) -manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error -na
- If a stacktrace is provided in the error, include that too. -na
- Any errors that appear in your browser's error console. -na
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. -na
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. -na
- Include what you've done so far in the installation, and if you got any error messages along the way. -na
- Indicate whether or not you've manually edited any data directly in the database -no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

here is my aws.php
```
<?php

use Aws\Laravel\AwsServiceProvider;

return [

    /*
    |--------------------------------------------------------------------------
    | AWS SDK Configuration
    |--------------------------------------------------------------------------
    |
    | The configuration options set in this file will be passed directly to the
    | `Aws\Sdk` object, from which all client objects are created. The minimum
    | required options are declared here, but the full set of possible options
    | are documented at:
    | http://docs.aws.amazon.com/aws-sdk-php/v3/guide/guide/configuration.html
    |
    */

    'region' => env('AWS_REGION', 'us-east-1'),
    'version' => 'latest',
    'ua_append' => [
        'L5MOD/' . AwsServiceProvider::VERSION,
    ],
];
```

here is my env
```
# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=base64:ADiszsCZQe8om9UagACUD3Ek7cJ8RNzJEg/qWxGzkbc=
LEGACY_APP_KEY=base64:ADiszsCZQe8om9UagACUD3Ek7cJ8RNzJEg/qWxGzkbc=
LEGACY_CIPHER=rijndael-256
APP_URL=***
APP_TIMEZONE='Asia/Manila'
APP_LOCALE=en

# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=***
DB_USERNAME=***
DB_PASSWORD=***
DB_PREFIX=null
DB_DUMP_PATH='C:\\PROGRA~1\\MARIAD~1.1\\bin'
DB_CHARSET=utf8mb4
DB_COLLATION=utf8mb4_unicode_ci

# --------------------------------------------
# OPTIONAL: SSL DATABASE SETTINGS
# --------------------------------------------
DB_SSL=false
DB_SSL_KEY_PATH=null
DB_SSL_CERT_PATH=null
DB_SSL_CA_PATH=null
DB_SSL_CIPHER=null

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=fpigchcas03.fpi.sea.css.fujitsu.com
MAIL_PORT=587
MAIL_USERNAME=fpiassets@fpi.sea.css.fujitsu.com
MAIL_PASSWORD=Fujitsu.123
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=fpiassets@ph.fujitsu.com
MAIL_FROM_NAME=FPI-Assets
MAIL_REPLYTO_ADDR=fpiassets@ph.fujitsu.com
MAIL_REPLYTO_NAME=FPI-Assets

# --------------------------------------------
# REQUIRED: IMAGE LIBRARY
# This should be gd or imagick
# --------------------------------------------
IMAGE_LIB=gd

# --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME=snipeit_session
COOKIE_DOMAIN=null
SECURE_COOKIES=false

# --------------------------------------------
# OPTIONAL: SECURITY HEADER SETTINGS
# --------------------------------------------
REFERRER_POLICY=same-origin
ENABLE_CSP=false

# --------------------------------------------
# OPTIONAL: CACHE SETTINGS
# --------------------------------------------
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

# --------------------------------------------
# OPTIONAL: REDIS SETTINGS
# --------------------------------------------
REDIS_HOST=null
REDIS_PASSWORD=null
REDIS_PORT-null

# --------------------------------------------
# OPTIONAL: AWS S3 SETTINGS
# --------------------------------------------
AWS_SECRET=null
AWS_KEY=null
AWS_REGION=null
AWS_BUCKET=null

# --------------------------------------------
# OPTIONAL: LOGIN THROTTLING
# --------------------------------------------
LOGIN_MAX_ATTEMPTS=5
LOGIN_LOCKOUT_DURATION=60

# --------------------------------------------
# OPTIONAL: MISC
# --------------------------------------------
APP_LOG=daily
APP_LOG_MAX_FILES=10
APP_LOCKED=false
FILESYSTEM_DISK=local
APP_TRUSTED_PROXIES=192.168.1.1,10.0.0.1
ALLOW_IFRAMING=false
APP_CIPHER=AES-256-CBC
```

**Comment by agentbb** [comment]
- delete the files (not the directory) in bootstrap/cache
- run composer dump-autoload
- remove config/aws.php if it exists
