### ISSUE TITLE
blank / white page during setup / pre-flight

### ISSUE THREAD

**Issue by MamoulianDelacroix** [snipe/snipe-it#4681]
#### Expected Behavior (or desired behavior if a feature request)

I want to install snipe-it.

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
freh installation
- Version of Snipe-IT you're running
current
- Version of PHP you're running
PHP 7.0.22
- Version of MySQL/MariaDB you're running
10.0.31-MariaDB-
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04.3 LTS  / Apache/2.4.18
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
I just get this error in my browser's consol.
`Uncaught TypeError: Cannot read property 'style' of undefined
    at Ja (http://tlinux.dsb.nsu/_debugbar/assets/javascript?v=1500638208:4:24833)
    at Function.css (http://tlinux.dsb.nsu/_debugbar/assets/javascript?v=1500638208:4:30287)
    at Ea (http://tlinux.dsb.nsu/_debugbar/assets/javascript?v=1500638208:4:23639)
    at Fa (http://tlinux.dsb.nsu/_debugbar/assets/javascript?v=1500638208:4:23723)
    at Va (http://tlinux.dsb.nsu/_debugbar/assets/javascript?v=1500638208:4:28273)
    at m.fn.init.show (http://tlinux.dsb.nsu/_debugbar/assets/javascript?v=1500638208:4:31805)
    at m.fn.init.m.fn.(anonymous function) [as show] (http://tlinux.dsb.nsu/_debugbar/assets/javascript?v=1500638208:5:6831)
    at child.setOpenHandler (http://tlinux.dsb.nsu/_debugbar/assets/javascript?v=1500638208:987:31)
    at http://tlinux.dsb.nsu/setup:58:13`

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
the setup page / pre-flight page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
> Include any additional information you can find in app/storage/logs and your webserver's logs.

**Comment by MamoulianDelacroix** [comment]
@snipe : Do you mean the laravel.log from snipe-it/storage/logs/ ?
At the moment when I access the website, there are no new entries written down in it.
These are the last entries:
`[2017-12-22 10:18:38] production.ERROR: ErrorException: file_put_contents(/var/www/html/snipe-it/storage/framework/sessions/kYwMjFmNu2uIAnmvIo8BMnWrGEk6odkQiFgx9l0i): failed to open stream: Permission denied in /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/s...', 122, Array)
#1 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/var/www/html/s...', 'a:4:{s:6:"_flas...', 2)
#2 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php(83): Illuminate\Filesystem\Filesystem->put('/var/www/html/s...', 'a:4:{s:6:"_flas...', true)
#3 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Store.php(128): Illuminate\Session\FileSessionHandler->write('kYwMjFmNu2uIAnm...', 'a:4:{s:6:"_flas...')
#4 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(88): Illuminate\Session\Store->save()
#5 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(218): Illuminate\Session\Middleware\StartSession->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#6 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(189): Illuminate\Foundation\Http\Kernel->terminateMiddleware(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#7 /var/www/html/snipe-it/public/index.php(63): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#8 {main}
[2017-12-22 10:18:38] production.ERROR: ErrorException: file_put_contents(/var/www/html/snipe-it/storage/framework/sessions/kYwMjFmNu2uIAnmvIo8BMnWrGEk6odkQiFgx9l0i): failed to open stream: Permission denied in /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/s...', 122, Array)
#1 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/var/www/html/s...', 'a:4:{s:6:"_flas...', 2)
#2 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php(83): Illuminate\Filesystem\Filesystem->put('/var/www/html/s...', 'a:4:{s:6:"_flas...', true)
#3 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Store.php(128): Illuminate\Session\FileSessionHandler->write('kYwMjFmNu2uIAnm...', 'a:4:{s:6:"_flas...')
#4 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(88): Illuminate\Session\Store->save()
#5 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(218): Illuminate\Session\Middleware\StartSession->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#6 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(189): Illuminate\Foundation\Http\Kernel->terminateMiddleware(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#7 /var/www/html/snipe-it/public/index.php(63): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#8 {main}
[2017-12-22 10:18:38] production.ERROR: ErrorException: file_put_contents(/var/www/html/snipe-it/storage/framework/sessions/kYwMjFmNu2uIAnmvIo8BMnWrGEk6odkQiFgx9l0i): failed to open stream: Permission denied in /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/s...', 122, Array)
#1 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/var/www/html/s...', 'a:4:{s:6:"_flas...', 2)
#2 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php(83): Illuminate\Filesystem\Filesystem->put('/var/www/html/s...', 'a:4:{s:6:"_flas...', true)
#3 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Store.php(128): Illuminate\Session\FileSessionHandler->write('kYwMjFmNu2uIAnm...', 'a:4:{s:6:"_flas...')
#4 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(88): Illuminate\Session\Store->save()
#5 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(218): Illuminate\Session\Middleware\StartSession->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#6 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(189): Illuminate\Foundation\Http\Kernel->terminateMiddleware(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#7 /var/www/html/snipe-it/public/index.php(63): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#8 {main}
[2017-12-22 10:18:38] production.ERROR: ErrorException: file_put_contents(/var/www/html/snipe-it/storage/framework/sessions/kYwMjFmNu2uIAnmvIo8BMnWrGEk6odkQiFgx9l0i): failed to open stream: Permission denied in /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/var/www/html/s...', 122, Array)
#1 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(122): file_put_contents('/var/www/html/s...', 'a:4:{s:6:"_flas...', 2)
#2 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Session/FileSessionHandler.php(83): Illuminate\Filesystem\Filesystem->put('/var/www/html/s...', 'a:4:{s:6:"_flas...', true)
#3 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Store.php(128): Illuminate\Session\FileSessionHandler->write('kYwMjFmNu2uIAnm...', 'a:4:{s:6:"_flas...')
#4 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(88): Illuminate\Session\Store->save()
#5 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(218): Illuminate\Session\Middleware\StartSession->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#6 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(189): Illuminate\Foundation\Http\Kernel->terminateMiddleware(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#7 /var/www/html/snipe-it/public/index.php(63): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#8 {main}
`

**Comment by snipe** [comment]
Looks like your [storage directory permissions](https://snipe-it.readme.io/docs/common-issues#section-browser-redirects-to-login-but-page-is-blank-with-a-500-error) might not be correct.  The entire storage directory and subdirectories must be writable.

**Comment by MamoulianDelacroix** [comment]
I've got the problem fixed.
I re-downloaded the whole snipe-it again and then I had some permission problems with my apache2.
But now everything is running.
😃 Thanks for the support 👍
