### ISSUE TITLE
Feature Request: Improvement to asset search

### ISSUE THREAD

**Issue by rodeff** [snipe/snipe-it#4684]
#### Expected Behavior (or desired behavior if a feature request)
Currently if you search for asset that is archived it is not showing on all assets page. 

It would be good when you are on all asset page and search for asset that is either archived, Un-deployable, or any other status the search to show it. 
Currently if you are on asset page and search for asset that is in status Archived search result returns empty result, which is leading to confusion that this asset is not in the database.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running: 4.1.7 - updated 13.12.2017
- Version of PHP you're running 7.1.9
- Version of MySQL/MariaDB you're running 10.0.14
- What OS and web server you're running Snipe-IT on - Windows 2016 - IIS10
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by agentbb** [comment]
+1

**Comment by snipe** [comment]
It is documented that archived assets do not appear in All Assets. This is by design, as archived assets are not in circulation anymore.

**Comment by snipe** [comment]
The option to include Archived assets in the List All/Search is now on the develop branch.
