### ISSUE TITLE
APP_URL set to `https://domain:443` but the assets still using `https://domain:80`

### ISSUE THREAD

**Issue by donnykurnia** [snipe/snipe-it#4685]
#### Expected Behavior (or desired behavior if a feature request)

I tried to run snipe-it docker behind nginx-proxy. I already have the letsencrypt companion container up and running, so I set to redirect all HTTP traffic to https. I also use Cloudflare for my domain.

-----

#### Actual Behavior

Uh oh! Snipe-IT thinks your URL is https://domain:80, but your real URL is http://domain/setup Please update your APP_URL settings in your .env file

Also, no assets loaded, because the assets url become https://domain:80/js/dist/all.js?id=88f08e0103b14f7949b3
-----

#### Please confirm you have done the following before posting your bug report:

- [v] I have enabled debug mode 
- [v] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install using latest docker image

- Version of Snipe-IT you're running
latest docker image per Dec 23rd, 2017

- Version of PHP you're running
Come with docker image

- Version of MySQL/MariaDB you're running
mysql:56 docker

- What OS and web server you're running Snipe-IT on
ubuntu server 16.04

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
docker

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Loading failed for the <script> with source “https://domain:80/_debugbar/assets/javascript?v=1513802908”

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
setup page

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

-----

I have already set `APP_URL` in `my_env_file` into `https://domain:443` but the assets still using `https://domain:80`

**Comment by snipe** [comment]
Please see the proxy documentation [here](https://snipe-it.readme.io/docs#section-snipe-it-configurations) and set the correct values  in the .env settings, in this case, APP_TRUSTED_PROXIES:
https://snipe-it.readme.io/docs/configuration#section-optional-misc

**Comment by donnykurnia** [comment]
@snipe  DONE. I have set the `APP_TRUSTED_PROXIES` with the container name of the nginx-proxy.

Now in setup page, it shows:

URL |   | That URL looks right! Good job!
--|--|--

However, all the assets still loaded using HTTP:

`http://domain/js/plugins/select2/select2.min.css`

I have set Cloudflare to use full instead of flexible SSL. the nginx-proxy setting has been set correctly to redirect the HTTP request to https.

I also track the code into laravel and eventually into Symfony package https://github.com/symfony/http-foundation/blob/8961ef9554af1dfc77ce71e1a34e4953f790dc45/Request.php#L1102

Somehow, the request still treated as non-secure, even when it comes from the trusted proxy. I'm still trying to debug this issue.

here is the nginx setting generated by nginx-proxy docker:
```
# If we receive X-Forwarded-Proto, pass it through; otherwise, pass along the
# scheme used to connect to this server
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}
# If we receive X-Forwarded-Port, pass it through; otherwise, pass along the
# server port the client connected to
map $http_x_forwarded_port $proxy_x_forwarded_port {
  default $http_x_forwarded_port;
  ''      $server_port;
}
# If we receive Upgrade, set Connection to "upgrade"; otherwise, delete any
# Connection header that may have been passed to this server
map $http_upgrade $proxy_connection {
  default upgrade;
  '' close;
}
# Apply fix for very long server names
server_names_hash_bucket_size 128;
# Default dhparam
ssl_dhparam /etc/nginx/dhparam/dhparam.pem;
# Set appropriate X-Forwarded-Ssl header
map $scheme $proxy_x_forwarded_ssl {
  default off;
  https on;
}
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack (see README for details)
proxy_set_header Proxy "";
server {
        server_name _; # This is just an invalid value which will never trigger on a real hostname.
        listen 80;
        access_log /var/log/nginx/access.log vhost;
        return 503;
}
# domain
upstream domain {
                                ## Can be connect with "docker_default" network
                        # snipeit_snipe-it_1
                        server 172.19.0.2:80;
}
server {
        server_name domain;
        listen 80 ;
        access_log /var/log/nginx/access.log vhost;
        return 301 https://$host$request_uri;
}
server {
        server_name domain;
        listen 443 ssl http2 ;
        access_log /var/log/nginx/access.log vhost;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:!DSS';
        ssl_prefer_server_ciphers on;
        ssl_session_timeout 5m;
        ssl_session_cache shared:SSL:50m;
        ssl_session_tickets off;
        ssl_certificate /etc/nginx/certs/domain.crt;
        ssl_certificate_key /etc/nginx/certs/domain.key;
        ssl_dhparam /etc/nginx/certs/domain.dhparam.pem;
        add_header Strict-Transport-Security "max-age=31536000";
        include /etc/nginx/vhost.d/default;
        location / {
                proxy_pass http://domain;
        }
}
```

**Comment by donnykurnia** [comment]
This fixed this issue:

https://snipe-it.readme.io/docs/docker#section-ssl-enabled-and-or-using-a-file-storage-volume

I also use this:

https://github.com/jwilder/nginx-proxy#ssl-backends

Thanks
