### ISSUE TITLE
Multitenancy enabled - Create new asset - all companies visible

### ISSUE THREAD

**Issue by DiLag** [snipe/snipe-it#4687]
#### Expected Behavior (or desired behavior if a feature request)

create new asset as non-admin user.
select company -> only the users company should be visible.

-----

#### Actual Behavior

create new asset as non-admin user.
select company -> all companies configured in the system are visible & selectable
-----

#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? fresh 
- Version of Snipe-IT you're running   v4.1.9 - build 3128 (master)
- Version of PHP you're running  7.0.22
- Version of MySQL/MariaDB you're running mysqld 10.1.30-MariaDB-1~xenial
- What OS and web server you're running Snipe-IT on Apache/2.4.18 (Ubuntu)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) installsh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - no error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error create asset
- If a stacktrace is provided in the error, include that too. no
- Any errors that appear in your browser's error console. no
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. yes
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by DiLag** [comment]
![image](https://user-images.githubusercontent.com/34798115/34385717-e12f77ba-eb24-11e7-9967-c89b21580bb8.png)
This is a normal users view. 
He can see the names of the other companies.
Is this normal behavior ?

thank you !

**Comment by SunilParisi123** [comment]
I am also seeing this issue. Need to address this issue quickly

**Comment by bcsdan** [comment]
I am seeing the same issue. While it's not a big deal for the one client to see my others it may be in the future.

**Comment by snipe** [comment]
This is fixed in the upcoming v5

**Comment by bcsdan** [comment]
And the award for fastest response I have ever received goes to you good sir!!!! Thank you!!! Please let me know if I can be of any assistance in the future with checking new versions out or whatever it might be.

**Comment by snipe** [comment]
Not a sir, but you're welcome ;)

![i-am-no-man](https://user-images.githubusercontent.com/197404/57198615-d2ff9280-6f42-11e9-964d-407eee01b8a5.gif)

You can always pull down the develop branch, which is where v5 lives. We're still testing it and tightening up a few things, but it's pretty close.
