### ISSUE TITLE
checkin by Import  csv?

### ISSUE THREAD

**Issue by amarbhanu** [snipe/snipe-it#4695]
Snipe IT Version v4.1.4
Now window
install.sh

Please suggest me Sample CSV for by csv Import automatic checkin process complete

**Comment by dmeltzer** [comment]
This is not currently possible.

**Comment by amarbhanu** [comment]
I did customize, in app\Importer\AssetImporter.php in Save process and update assigned_to field in assets Table then checkin button convert to pink checkout button.

Can you suggest me this will be work or any thing missing.
