### ISSUE TITLE
Path problem in Laravel Mix vue.js concatenation task 

### ISSUE THREAD

**Issue by cordeosdev** [snipe/snipe-it#4697]
Seems to be small path mismatch in Laravel MIX task for vue.js concatenation into all.js file.  Any vue.js updates are not updated in application.

**## root [webpack.mix.js]**
// for later concatenation in the scripts() section below.
.js(
    'resources/assets/js/vue.js', // Snipe-IT's initializer for Vue.js
    '.**_/public/js/build_**'
).sourceMaps()
.scripts([
    './node_modules/jquery-ui/jquery-ui.js',
    '.**_/public/build_**/vue.js', //this is the modularized nifty Vue.js thing we just built, above!

**Comment by dmeltzer** [comment]
Thanks.  I chased this down earlier as well.  Fixed as part of #4702

**Comment by cordeosdev** [comment]
Thanks.  We have quite a few problems with import process, especially for components, and like to help for this.  Maybe we have good understanding now how you using VUE js integrated to Laravel controllers and combine all together with Laravel MIX for production deployment.
