### ISSUE TITLE
Can Snipe-it data be recovered from LVM

### ISSUE THREAD

**Issue by SOLS-Tech** [snipe/snipe-it#4704]
#### Expected Behavior (or desired behavior if a feature request)
**not relevant**
(what you expect to happen goes here)

-----

#### Actual Behavior
**not relevant**
(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:
Not relevant.

-----
**## Our problem:**
First of all CONGRATULATIONS FOR SUCH AN AMAZING JOB!!!
Hats-off for you and yout Team.

Problem is not applicable to the above criteria.
We had a previous Snipe-it running fine, version 3.x.
It was deployed on a single hard disk, old machine by previous IT dude.
HDD went down but we manage to save MBR, so we can still access and decrypt LVM partition, where all the /var etc are stored.
We have now an independent server, 4.1.9 version runnning more than fine on a RAID (to avoid issue happening again).
Can we somehow extract the Assets database from the old LVM to dump it to our new version?
All help much appreciated depite the fact we understand you are busy and get lots of help queries.
All the best

**Comment by cordeosdev** [comment]
If you can recover the .env setup text file and MySQL database from the previous server, you should be able to import these to a new 4.1.9 installation server, then run the normal upgrade laravel/artisan db migration and cache clear.  You will need to research how to move a MySQL db file from one MySQL server to another, this can be tricky sometimes and you should use the same MySQL version.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
