### ISSUE TITLE
CSS and JS issue after v3 -> v4 upgrade

### ISSUE THREAD

**Issue by jrdalrymple** [snipe/snipe-it#4707]
#### Expected Behavior (or desired behavior if a feature request)

Page to load with appropriate style

-----

#### Actual Behavior

Page loads without style. Looks like garbage. Content is there though.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
upgrade
- Version of Snipe-IT you're running
v4.1.9
- Version of PHP you're running
7.1.12
- Version of MySQL/MariaDB you're running
10.1.25
- What OS and web server you're running Snipe-IT on
Fedora 26 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
index.php - just loading the page
- If a stacktrace is provided in the error, include that too.
N/A
- Any errors that appear in your browser's error console.
GET http://myhostname/index.php/css/dist/all.css?id=3a8aa974e7b09b52b18c net::ERR_ABORTED
- Confirm whether the error is reproducible on the demo: .
No
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
./access_log:172.40.0.77 - - [29/Dec/2017:19:17:51 -0600] "GET /index.php/css/dist/all.css?id=3a8aa974e7b09b52b18c HTTP/1.1" 404 113384 "http://myhostname/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
- Include what you've done so far in the installation, and if you got any error messages along the way.
Followed instructions for upgrading v3 to v4, that went very smoothly.
- Indicate whether or not you've manually edited any data directly in the database
No

I'm guessing this is something wrong with my mod-rewrite config or something, but it always worked before and I validated that the .htaccess file matches that in the v4.1.9 source. If I drop the "index.php/" from the request the CSS loads in my browser. I'm not sure what to look at next. 
![2017-12-29 19_26_27](https://user-images.githubusercontent.com/5749568/34450455-9f17dcfe-ecce-11e7-98de-1b8db2b44a6b.png)

**Comment by snipe** [comment]
index.php shouldn't be in your URL. My guess would be either you don't have mod_rewrite working, or your APP_URL is wrong.

**Comment by jrdalrymple** [comment]
For sure mod_rewrite is *working*, although maybe it's not working correctly. Like I said, the .htaccess file is identical to the one [in the v4.1.9 source code](https://github.com/snipe/snipe-it/blob/master/public/.htaccess). To validate that .htaccess is being read and interpreted by mod_rewrite I uncommented the https lines, that redirected properly.

As for APP_URL, it's this:
`APP_URL=http://my.host.local`
Where "my.host.local" is actually my servers fqdn. I could see where this might be the problem as I can put in alternative URLs that make no sense and the site doesn't change behavior. My question is what *should* this be? As well as I can interpret the documentation, what I've entered is correct. Moreover, what I've entered worked before the upgrade. The site is accessed through the URL http://my.host.local/index.php, based upon that information what should I set APP_URL to?

The documentation reads _Images and javascript will not load correctly if this is not set to EXACTLY the URL you access your Snipe-IT app from._ however setting it to `http://my.host.local/index.php` didn't have any effect either.

Thanks for any help in debugging this.

**Comment by workbykiran** [comment]
Is your issue resolved? I have the same issue and couldnt get any solution yet.

Thanks.

**Comment by jrdalrymple** [comment]
Nope. No idea how to proceed with this product. My customer is learning the value of "paying rent" for cloud solutions because of this upgrade gone wrong as well as some other stuff breaking in their environment. 

The sucky part for me is that I was forced to upgrade snipe because of updated mcrypt libraries in the OS, so no real option to roll-back. I'm lost.

**Comment by snipe** [comment]
>  The site is accessed through the URL http://my.host.local/index.php

Your APP_URL should be set as `http://my.host.local`, and you should access it through `http://my.host.local` - index.php should never even be seen in any URLs in the app. Using index.php in the URL will result in the 404 you're seeing for `/index.php/css/dist/all.css?id=3a8aa974e7b09b52b18c`, since that's not a valid URL. The path should be ``/index.php/css/dist/all.css?id=3a8aa974e7b09b52b18c`. That path is set via the APP_URL. If it's still appending the index.php, you might try [clearing your config cache](https://snipe-it.readme.io/docs/clearing-the-config-cache).

**Comment by vedkabirr** [comment]
Is your issue resolved? I have the same issue!!
![Screen Shot 2019-09-27 at 12 25 08 PM](https://user-images.githubusercontent.com/10011395/65748600-fa3d4300-e121-11e9-9f30-ad2a26b9e01f.png)
