### ISSUE TITLE
Assets/Users import fields not found

### ISSUE THREAD

**Issue by Tzvetelin88** [snipe/snipe-it#4709]
Expected Behavior (or desired behavior if a feature request)
Using Import for Assets and Users. Should list all "Import Field"

Actual Behavior
I did an export to CSV file of already added users. On that CSV file I add 50 more users following each column. When I upload the file I need to choose "Import Field" for each "Header Field". Unfortunately some of the "Import Field" are not found. Example: Import Field "Groups" not showing and information for Groups is not imported. 
Also the information for field "email" is not imported  although it's showing.
Screenshot:
https://drive.google.com/open?id=1UhoxV3FyYzdIPws9LlNvpJX0es-mobu1

Please confirm you have done the following before posting your bug report:
 I have enabled debug mode
[yes ] I have read checked the Common Issues page
Provide answers to these questions:
Is this a fresh install or an upgrade? -> Fresh install
Version of Snipe-IT you're running -> v4.1.9-pre - build 3117 (master)
Version of PHP you're running -> PHP7
Version of MySQL/MariaDB you're running ->5.5.58
What OS and web server you're running Snipe-IT on ->Debian GNU/Linux 8, Apache2
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) -> Git Clone
WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error ->
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error -> No error
If a stacktrace is provided in the error, include that too.
Any errors that appear in your browser's error console.
Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. -> Not available in the demo.
Include any additional information you can find in app/storage/logs and your webserver's logs.
Include what you've done so far in the installation, and if you got any error messages along the way.
Indicate whether or not you've manually edited any data directly in the database -> No data has been edited directly in the db.
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
@dmeltzer can you take a look when you get a chance?

**Comment by Tzvetelin88** [comment]
This issue is also observed when addint users.csv . In *.csv file I have values for "department"; "Manager"; "Groups" and "Activated", but on import it says "No results found", but on the right hand side, it's showing the value:
https://drive.google.com/file/d/1wwO4h4-CQoEWhfoo89wkF7xAC4sLYd-_/view?usp=sharing

What I found is there is strange behavior when creating *.CSV files with Microsoft Office 2013 and Google Docs. When I create CSV file with Google sheets, some of the fileds are showing, but still not all of them. (maybe encoding problem). Thanks

**Comment by dmeltzer** [comment]
Hi,

Can you replace the semi-colons with commas? That should solve at least some of your problems

Thanks,

**Comment by Tzvetelin88** [comment]
Yes, that's right. I'm using comma delimiter in the CSV file. ","

**Comment by dmeltzer** [comment]
Ah, yes.  Sorry.  Currently we don't support importing groups/manager via that importer.  I'll try to look at adding that support in the future.
