### ISSUE TITLE
Upgrade fails on migrate

### ISSUE THREAD

**Issue by ebonweaver** [snipe/snipe-it#4710]
When updating from 4.1.3 to 4.1.9 it fails when doing the artisan migrate:

php artisan migrate
PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/snipeit/app/Exceptions/Handler.php:39
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(320): App\Exceptions\Handler->report(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(132): Illuminate\Foundation\Console\Kernel->reportException(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#2 /var/www/snipeit/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 {main}
  thrown in /var/www/snipeit/app/Exceptions/Handler.php on line 39

 php --version
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

 mysql --version
mysql  Ver 14.14 Distrib 5.7.20, for Linux (x86_64) using  EditLine wrapper

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

 apache2 -v
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-09-18T15:09:02

Originally installed with install.sh, upgraded manually as converting to git seems problematic given permissions issues.
php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
Completed without issue, then migrate fails as noted above.  Errors seems to indicate there are errors in the snipe files that need to be fixed.  Please advise.  It appears based on other bugs that this issue was introduced in 4.1.4 and has not been corrected?

**Comment by tiagom62** [comment]
I ran into this issue in the past. I was missing some php extensions.

**Comment by ebonweaver** [comment]
There are no new extensions required since 4.1.3 based on the release notes, and I see nothing new in the requirements.

I'll also note that having seen something about this added to the FAQ recently:
- No changes have been made to the .env file since the last upgrade
- Removing the .env file does not remedy this error
- Using the .env.example as the .env does not remedy this error
These facts indicate this is not an issue with the .env, there is a code bug.  That is, unless the syntax of the .env has been changed with no notice, and the .env.example has not been changed to reflect this either, so we have no information on a working .env.  That seems unlikely since the example has been updated with the Google API string.

**Comment by snipe** [comment]
> These facts indicate this is not an issue with the .env, there is a code bug

If that were true, we'd be seeing it a lot more often. In your `config` dir, do you have an `aws.php` file?

**Comment by ebonweaver** [comment]
Yes, that file exists.

**Comment by snipe** [comment]
This is addressed in the [Common Issues](https://snipe-it.readme.io/docs#section-class-awslaravelawsserviceprovider-not-found-or-class-log-not-found) (and many of the upgrade notes for each release).

**Comment by ebonweaver** [comment]
There is nothing saying to delete that file at https://github.com/snipe/snipe-it/releases/tag/v4.1.9 or https://snipe-it.readme.io/docs/upgrading and the info in the common issues references a distinctly different error.  I'm a little confused how a file that is part of the code that cause it to not work is not a bug.  If it's not used anymore, I'm even more confused how it can cause an issue, as the only way that's not a Snipe bug is if it's a defect in the foundation technologies used for the product.  If this issue can't be addressed on your end, stating what must be done to compensate in documentation is rather vital.  Are there any other gotchas like this that have been introduced since v4?  A list of any files that are now discontinued and need to be manually deleted seems very prudent.  If these updates are otherwise cumulative and incremental is not required, cumulative upgrade notes since version x would help avoid these pitfalls.  The assumption from the upgrade page is that other than from v3 to v4 there are no such concerns, which seems not entirely true.

**Comment by snipe** [comment]
> There is nothing saying to delete that file at https://github.com/snipe/snipe-it/releases/tag/v4.1.9 or https://snipe-it.readme.io/docs/upgrading

> and the info in the common issues references a distinctly different error

It's exactly the same error:

<img width="778" alt="screen shot 2018-01-10 at 6 49 28 am" src="https://user-images.githubusercontent.com/197404/34778556-7ca1a18e-f5d2-11e7-9506-87ee87673c02.png">

It's in multiple releases prior to that. Since we can't know what version folks are upgrading from, we have to move those things into Common Issues after multiple releases, or else our Upgrade Notes in the releases would be a mile long.

>  I'm a little confused how a file that is part of the code that cause it to not work is not a bug. 

It's complicated to explain, but it's a combination of the way the underlying framework works in the version we're using, and the caching that composer does. 

> If this issue can't be addressed on your end, stating what must be done to compensate in documentation is rather vital. 

It has already been addressed - in the Common Issues page. 

> Are there any other gotchas like this that have been introduced since v4?

None that are not mentioned in multiple release notes and/or Common Issues. 

Updates are typically incremental, however you should always review the release notes of versions in between. That goes for any software, not just ours. We included the deletion note in 5 previous releases. 

We mention several times throughout the documentation that Git is the preferred installation method, and Snipe-IT installs done using Git did not have to delete the file, as Git takes care of that for you.

**Comment by ebonweaver** [comment]
I was just about to hit send asking how Apple = Orange when I re-re-read with a fine tooth comb for the 8th time and I think I see the problem.

Class 'Aws\Laravel\AwsServiceProvider' not found or Class 'Log' not found
is NOT the same as
PHP Fatal error: Uncaught Error: Class 'Log' not found in /var/www/snipeit/app/Exceptions/Handler.php:39

However, the section of those statements "Class 'Log' not found" IS the same.  This is where the clarity issue and oversight came in.  May I humbly suggest the header for this in the Common Issues be changed to say:
**You receive an error during artisan migrate that contains "Class 'Aws\Laravel\AwsServiceProvider' not found" or "Class 'Log' not found".** 

May seem trivial to you, but from the non coder layman side I was looking to match an entire string as it were and passed by that as not relevant.  Stated as I suggest, this thread would never have happened.

**Comment by snipe** [comment]
It won't always happen just during migrate though. In this case, being less specific is better, since there are a number of things one could do to trigger that error.
