### ISSUE TITLE
LDAP login

### ISSUE THREAD

**Issue by amannb** [snipe/snipe-it#4715]
#### Expected Behavior (or desired behavior if a feature request)

Login using LDAP and Import users from LDAP

-----

#### Actual Behavior

Test LDAP login fails. Error "Login Failed. username did not successfully bind to LDAP.

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install
- Version of Snipe-IT you're running
Version v4.1.9 - build 3128 (master)
- Version of PHP you're running
7.1.11-0ubuntu0.17.10.1
- Version of MySQL/MariaDB you're running
5.7.20-0ubuntu0.17.10.1
- What OS and web server you're running Snipe-IT on
Ubuntu Linux 17.10
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation using git
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Failed to load resource: the server responded with a status of 400 (Bad Request)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
LDAP settings . Test LDAP login
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
Failed to load resource: the server responded with a status of 400 (Bad Request)
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
no
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.

- Include what you've done so far in the installation, and if you got any error messages along the way.
There was no error in application installation

- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snazy2000** [comment]
If you are using Active Directory do you have 

LDAP Authentication query

Set to 

sAMAccountName=

I ran in to this issue the other day and this resolved my problem, i believe default is uid=

**Comment by amannb** [comment]
Thanks snazy2000, 
That solved my issue. 
![image](https://user-images.githubusercontent.com/34069020/34661860-82a43090-f45d-11e7-9df7-b42f000e3c0f.png)

**Comment by wynandbecker** [comment]
I have:
uid=samaccountname
Not sure how to implement your solution snazy2000?

**Comment by snazy2000** [comment]
change it from uid=samaccountname to just samaccountname=

**Comment by wynandbecker** [comment]
Ok thanks man. Still dead though :/

**Comment by jpaolosy** [comment]
@snazy2000 
many thanks! finally have it working for me!

**Comment by Liel4494** [comment]
no works for me :(
i can see all active directory users but they can't login...
