### ISSUE TITLE
LDAP:User can not view consumable and accessories only asset display

### ISSUE THREAD

**Issue by vipin2079** [snipe/snipe-it#4717]
I installed latest version and integrate with ldap.it's sucessfully integrate with ldap but when i assign accessories/licence to ldap user item not shows to ldap user however only asset display.
With Snipe-IT console local user i am able to see the licence.

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by abhirhel7** [comment]
I also have the same issue, as with locally created user its showing checked out peripherals but not with the LDAP synced user.

**Comment by snipe** [comment]
@abhirhel7 this would have to be a permissions/group error, or your usernames are different so it's creating two users. There is functionally no difference between LDAP synced users and regular users.
