### ISSUE TITLE
LDAP Sync for Devices?

### ISSUE THREAD

**Issue by paulod1982** [snipe/snipe-it#4720]
Hi Guys,

I have just set up Snipe IT on a windows 2016 server. All seems to be working fine, I have set up LDAP sync for my users, which is working fine.
I was wondering if there is a way to Sync our PC's/Laptops/Servers with Snipe via AD/LDAP, rather than having to import via a CSV, or manually entries going forward?

Kind Regards,
Paul

**Comment by snipe** [comment]
Hi @paulod1982 - that's not currently possible, but you could probably write a script to use the Snipe-IT REST API + your LDAP.
