### ISSUE TITLE
Problems Checking out Assets to users during Asset Creation

### ISSUE THREAD

**Issue by RendingTempest** [snipe/snipe-it#4721]
Hello,
Bit of context for you.
We have a backlog of devices that we have given out to users and these are being added onto Snipe IT.
Yesterday I upgraded the system from V4.1.3 to V4.1.9.
Prior to the upgrade we could checkout the asset when we created it, however now we have to create it, go to the list of assets and then check it out afterwards.

#### Expected Behavior (or desired behavior if a feature request)
When creating an asset like this:
![image](https://user-images.githubusercontent.com/25364008/34531039-df48d8fe-f0a8-11e7-81df-16dee29bef33.png)

It used to show up in the list like this:
![image](https://user-images.githubusercontent.com/25364008/34531271-a793b7de-f0a9-11e7-8426-d02624288ad3.png)

-----

#### Actual Behavior

However when going to the list it now shows up like this:
![image](https://user-images.githubusercontent.com/25364008/34531207-7bea9422-f0a9-11e7-90bf-d627d8a8cddf.png)

And we have to manually check it out

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
_Upgrade from V4.1.3 to V4.1.9_
- Version of Snipe-IT you're running
_Version v4.1.9 - build 3128_
- Version of PHP you're running
_7.1.11_
- Version of MySQL/MariaDB you're running
_10.1.28-MariaDB_ 
- What OS and web server you're running Snipe-IT on
_Windows Server 2016 using XAMPP_
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
_Git + Manual_
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
_N\A_
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
_Webpage = http://SERVERNAME/hardware/create_

_User dropdown:_
`<span title="Select a User" class="select2-selection__rendered needsclick" id="select2-assigned_user_select-container">Select a User</span>`

_Save Button:_
`<button class="btn btn-success" type="submit"><i class="fa fa-check icon-white"></i> Save</button>`

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
_Works fine in the Demo_
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
`[2018-01-03 17:13:27] production.ERROR: ErrorException: Undefined index: next_audit_date in D:\xampp\htdocs\Snipe-IT\app\Observers\AssetObserver.php:49
Stack trace:
#0 D:\xampp\htdocs\Snipe-IT\app\Observers\AssetObserver.php(49): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', 'D:\\xampp\\htdocs...', 49, Array)
#1 [internal function]: App\Observers\AssetObserver->updating(Object(App\Models\Asset))
#2 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(367): call_user_func_array(Array, Array)
#3 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(199): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('eloquent.updati...', Array)
#4 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Events\Dispatcher.php(159): Illuminate\Events\Dispatcher->dispatch('eloquent.updati...', Array, true)
#5 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasEvents.php(148): Illuminate\Events\Dispatcher->until('eloquent.updati...', Object(App\Models\Asset))
#6 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(578): Illuminate\Database\Eloquent\Model->fireModelEvent('updating')
#7 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(515): Illuminate\Database\Eloquent\Model->performUpdate(Object(Illuminate\Database\Eloquent\Builder))
#8 D:\xampp\htdocs\Snipe-IT\app\Models\Asset.php(185): Illuminate\Database\Eloquent\Model->save()
#9 D:\xampp\htdocs\Snipe-IT\app\Http\Controllers\AssetsController.php(236): App\Models\Asset->checkOut(Object(App\Models\User), Object(App\Models\User), '2018-01-03 17:1...', '', 'Checked out on ...', '999999', 2)
#10 [internal function]: App\Http\Controllers\AssetsController->store(Object(App\Http\Requests\AssetRequest))
#11 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(55): call_user_func_array(Array, Array)
#12 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('store', Array)
#13 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\AssetsController), 'store')
#14 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Route.php(160): Illuminate\Routing\Route->runController()
#15 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(572): Illuminate\Routing\Route->run()
#16 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 D:\xampp\htdocs\Snipe-IT\vendor\laravel\passport\src\Http\Middleware\CreateFreshApiToken.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 D:\xampp\htdocs\Snipe-IT\app\Http\Middleware\CheckForTwoFactor.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckForTwoFactor->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 D:\xampp\htdocs\Snipe-IT\app\Http\Middleware\CheckLocale.php(42): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#30 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#33 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#39 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#40 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#41 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#42 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#43 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#44 D:\xampp\htdocs\Snipe-IT\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#45 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 D:\xampp\htdocs\Snipe-IT\vendor\fideloper\proxy\src\TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#48 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 D:\xampp\htdocs\Snipe-IT\app\Http\Middleware\CheckForSetup.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#51 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 D:\xampp\htdocs\Snipe-IT\app\Http\Middleware\NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#54 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 D:\xampp\htdocs\Snipe-IT\app\Http\Middleware\ContentSecurityPolicyHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#57 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\ContentSecurityPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 D:\xampp\htdocs\Snipe-IT\app\Http\Middleware\ReferrerPolicyHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\ReferrerPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 D:\xampp\htdocs\Snipe-IT\app\Http\Middleware\XssProtectHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 D:\xampp\htdocs\Snipe-IT\app\Http\Middleware\FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#72 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#74 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#75 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#78 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#79 D:\xampp\htdocs\Snipe-IT\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#80 D:\xampp\htdocs\Snipe-IT\public\index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#81 {main}  `
- Include what you've done so far in the installation, and if you got any error messages along the way.
_N\A_
- Indicate whether or not you've manually edited any data directly in the database
_I have done no manual editing_

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

I can see in the logs that it mentions an error within the AssetObserver.php file on line 49, here is the entry on that line however there is no Audit date on the creation page on our install or the demo:
`           \Log::debug($asset->getOriginal()['next_audit_date'].' == '.$asset->getAttributes()['next_audit_date']);`

I'm not too savvy with web apps so any help will be greatly appreciated.

**Comment by snipe** [comment]
This should be fixed on master/develop
