### ISSUE TITLE
Minor update to API docs: required Checkout Asset parameter

### ISSUE THREAD

**Issue by matc** [snipe/snipe-it#4722]
#### Expected Behavior (or desired behavior if a feature request)

The Checkout Asset API method was recently upgraded to  require a "checkout_to_type" parameter based on user, location or asset. 
-----

#### Actual Behavior

Without this "checkout_to_type" parameter, the checkout call with fail with the message: {u'assigned_user': [u'The assigned user field is required when none of assigned asset / assigned location are present.'], u'assigned_location': [u'The assigned location field is required when none of assigned user / assigned asset are present.'], u'assigned_asset': [u'The assigned asset field is required when none of assigned user / assigned location are present.']}, u'payload': None}

This PR is just to update the API docs so new people writing a client know this is a required parameter:
- https://snipe-it.readme.io/v4.1.6/reference#hardwareidcheckout
-----

#### Please confirm you have done the following before posting your bug report:

- [√ ] I have enabled debug mode 
- [√ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgraded Docker image
- Version of Snipe-IT you're running; v4.1.9 - build 3128 (master
- Version of PHP you're running; 7
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on; Debian
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc); Docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: NA
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error:  NA
- If a stacktrace is provided in the error, include that too. NA
- Any errors that appear in your browser's error console. NA
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. NA
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. 
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

Thanks!

**Comment by snipe** [comment]
Docs are updated - thanks!

**Comment by matc** [comment]
Awesome thanks Snipe!
