### ISSUE TITLE
How to Allow permission for  API

### ISSUE THREAD

**Issue by amarbhanu** [snipe/snipe-it#4725]
Snipe IT Version v4.1.4
Now window
install.sh

Please suggest me how to Allow permission for new API Controller and menu assess to User

Admin have working every thing fine but when login User permission level then Show Error in API

> {"status":"error","messages":"An Error has occured! This action is unauthorized.","payload":null}

**Comment by amarbhanu** [comment]
any have idea ..

**Comment by snipe** [comment]
I don't understand what you're asking for here.
