### ISSUE TITLE
PHP Fatal error: upgrade.php on CentOS 7

### ISSUE THREAD

**Issue by black3dynamite** [snipe/snipe-it#4726]
OS: CentOS 7.4.1708 Minimal
SnipeIT Installer: install.sh

The following error shows up when using upgrade.php:

PHP Fatal error: Call to undefined function posix_getpwuid() in /var/www/html/snipeit/upgrade.php on line 7

Solution: php71u-process provides php71u-posix

**Comment by tiagom62** [comment]
I will add this to the installer.

**Comment by christopher-paul-shaw** [comment]
when running update.php using latest version I am getting the following

-bash-4.2$ php upgrade.php
PHP Fatal error:  Call to undefined function posix_getpwuid() in /var/www/vhosts/snipe/httpdocs/upgrade.php on line 7

**Comment by galaris** [comment]
This is still happening on the [latest version](https://github.com/snipe/snipe-it/commit/31c5350941c7330aed01652b0670b61f6660b15b) on CentOS 8.

[root@localhost snipe]# git pull
Already up to date.
[root@localhost snipe]# php upgrade.php
PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpwuid() in /var/www/html/snipe/upgrade.php:7
Stack trace:
#0 {main}
  thrown in /var/www/html/snipe/upgrade.php on line 7

**yum install php-process** solves it
