### ISSUE TITLE
Feature Request: Request items and specify date needed at "request" asset screen

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#4727]
#### desired behavior

If an item is requestable, a user who has view requestable rights can simply request the asset immediately, even if they don't need the asset for 3 days. 

Add calendar selection feature specifying what date the asset(s) are needed menu as a required field. 

-----

#### Actual Behavior

Requesting the asset sends an email to the administrator (possible the user manager as well) asking to request the item, without any details of when they need the asset, for what duration etc. 

#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running 4.1.9 build 3128 (ge5a7e66)
- Version of PHP you're running 5.6.32
- Version of MySQL/MariaDB you're running 5.4.29
- What OS and web server you're running Snipe-IT on CentOS 7 google chrome
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error (N/A)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error (Requestable Assets view under Assets)
- If a stacktrace is provided in the error, include that too. N/A
- Any errors that appear in your browser's error console. N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. No due to Admin user credentials
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. N/A
- Include what you've done so far in the installation, and if you got any error messages along the way. N/A
- Indicate whether or not you've manually edited any data directly in the database No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by Cabe** [comment]
+1 for this

Still the behaviour as of version v4.6.15 build 4011 (gd1e9fbfa2).

**Comment by usernet-vm** [comment]
+1 for this. Great feature!

**Comment by Akhun-Delar** [comment]
+1

**Comment by viclou** [comment]
+1 FD ticket 40661
