### ISSUE TITLE
Feature Request : Allow departments to own assets

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#4728]
#### Desired behavior

Allow assets to be owned by a department. This way users can be assigned to a department, and individuals in that department can check out assets to users within their department. 

-----

#### Actual Behavior

Departments appear to be just for labels. As it is now, a user has to have checkout permissions company wide or you have to create a separate company within a company to have specific assets for that group of users. 

Changing the arrangement so assets can belong to departments, and then assigning users to the department would allow users in that department to request or checkin or checkout assets without being able to see all assets organization wide. 

----

**Comment by Jarli01** [comment]
The department or user manager would check out the asset to the user or this could be handled within the existing permissions (possibly) by having department managers and authorized users who can check in and out assets.

**Comment by snazy2000** [comment]
Was thinking this was be a very useful feature and was about to raise a FR for this! so +1

**Comment by eangulus** [comment]
+1 here too.
We have a Single Location but with 3 Sheds and Offices. Would be great to be able to set an Asset like the location but also include the department. Maybe allowing us to Set the location then select the departments in that location.

**Comment by snipe** [comment]
We've already made things complicated enough by allowing folks to check out to locations. It's unlikely we'd want to add this new layer of complexity any time soon.

**Comment by eangulus** [comment]
How is that complicated? Whats the point of departments then if you cannot checkout to a department?

How are we suppose to know where at one location is the asset? Our main location is 3 Large sheds and a 2 story office building.

**Comment by Jarli01** [comment]
I can understand that the system is complicated, yet creating a separate department to assign assets that would be checked in and out by a separate person when the department and employee are all a part of the same team makes even less sense then having the ability to check assets into a department, assign people to the department and then have department heads (IE ability to manage assets) to check in and check out the assets under the parent organization.

**Comment by snipe** [comment]
> How is that complicated? 

It's complicated because we already have a lot of targets you can check assets out to. Each time we add one, it adds a layer of complexity to the code itself, to testing, to checkout validation, and so on.

> Whats the point of departments then if you cannot checkout to a department?

Right now, it's just a reference field. People asked to track that information, so we provided that.


> How are we suppose to know where at one location is the asset?

By using sub-locations - that;'s why they exist. Parent location could be the building, child location floor w/room number, etc.

**Comment by eangulus** [comment]
Still makes no sense.

So whats the difference between a sub location and a department then? Why have both? why not just call sublocations departments and merge them?

If I were to setup mine according to your definitions, ours still won't work. We have 3 total buildings in 1 location. Shed 1, has Showroom, Reception, Office, Lunch Room and Factory Floor (which is then functionally divided), then upstairs 3 offices, Server room and a meeting room. SHed 2 has General Storage Area, Lunch Room, and a Utility Room. Shed 3 has Factory Floor (again divided functionally), LunchRoom, Upstairs office.

We don't have room numbers. They are defined by their purpose (department).

BTW I am a new user here, and still getting my head around the system. I simply don't understand why have both sublocations and departments, or why I can't check out the printer to the accounting department?

**Comment by snipe** [comment]
@eangulus Because people asked for Department. That's it. Some people have Departments that are not bound by the same physical locations - remote workers, folks with cross-reporting, etc. We have to accommodate a lot of different use-cases here.

I'm not sure why you think it wouldn't work. 

- Shed 1 
   - Showroom
   - Reception
   - Office
   - Lunch Room
   - Factory Floor 
      - Area A
      - Area B
      - Area C

Checkout the asset to Area C.

**Comment by Jarli01** [comment]
@snipe the goal (at least in my case) is to physically have the assets setup in different locations or departments (the term is almost interchangeable in my case). 

Assets in this department are to be managed by people in that department (or location). At the moment there is no way for me to limit what they are able to see short of changing their permissions with "checkin/out assets" which is company wide. 

Rather than for the individual department. 

I think the question is really one of is it possible to change the permission scheme so assets can be held in departments (like companies) that are children of a parent company and then have individuals be managers of that departments assets?

**Comment by Jarli01** [comment]
Checking the asset out to an area is only so useful "static-deployments" is what I call this. 

These are computers or TV's that get put on walls that will never move. But mostly everything else is mobile and that "static-deployment" term isn't an option as multiple users will need to use the equipment, move it around, take it on travel to client sites etc.

**Comment by snipe** [comment]
So you're not actually asking for assets to be assigned to departments, you're asking for the ability to limit the scope of what users can see based on what location/department they are in - like we do with Company when full company support is turned on. 

That's unfortunately even more complicated.

**Comment by Jarli01** [comment]
Well there are different ways to skin a cat. Either allow departments to have their own permissions and assets or allow companies to have departments that users can see only what is in that department.

**Comment by snipe** [comment]
@Jarli01 either way you're talking about scoping on department, which is enormously complicated.

**Comment by eangulus** [comment]
> @eangulus Because people asked for Department. That's it. Some people have Departments that are not bound by the same physical locations - remote workers, folks with cross-reporting, etc. We have to accommodate a lot of different use-cases here.

I'm not sure why you think it wouldn't work.

Shed 1
Showroom
Reception
Office
Lunch Room
Factory Floor
Area A
Area B
Area C
Checkout the asset to Area C.


Just tried this and it is a nightmare. When adding or editing an asset I see for example Office. But which one is it? Is it the one in Shed 1 or Shed 2 or in City 1 or City 2...

Why doesn't it show the heirachy? Do I have to put the names in like: City1>Shed 1>Factory Floor>Assembly Area?

**Comment by britto89** [comment]
While it adds a layer of complexity I do agree that departments could benefit from similar features as locations. In my environment (Health industry with about 6000 computers) we use locations for the physical sites and departments to record the cost center the asset is allocated to. 

Since cost centers have managers it would be good to give them visibility to everything under them and be able to check things in and out (essentially give them the ability to manage their own assets). The reason locations wouldn't work in this instance is that cost centers/department can span multiple sites.

**Comment by tutankh** [comment]
What about using 'Locations' as your Departments and create a separate custom field to track the physical location.

**Comment by acrespo1001** [comment]
Hello,

Is there any way to make users see assets of a specificied department?
