### ISSUE TITLE
Asset Report Bug

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#473]
When viewing the asset report the status for deployed assets is not displayed.

![image](https://cloud.githubusercontent.com/assets/10247644/5876437/22b37bfe-a2e5-11e4-8708-cc33aed51893.png)

**Comment by snipe** [comment]
This should be fixed in the beta candidate for 1.2.4 - https://github.com/snipe/snipe-it/releases/tag/v1.2.4-beta

**Comment by kobie-chasehansen** [comment]
Thanks, will give it a try.

**Comment by snipe** [comment]
The official release should be out soon, if you'd rather wait for that. We're still working out some bugs.

**Comment by kobie-chasehansen** [comment]
eh too late, who doesn't love a beta anyways! 

Confirmed this is fixed for me. Thanks!

**Comment by snipe** [comment]
Hah, okay :P
