### ISSUE TITLE
The stream or file "/var/www/snipe-it/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied

### ISSUE THREAD

**Issue by gtechman** [snipe/snipe-it#4736]
#### Expected Behavior (or desired behavior if a feature request)

Fresh install/pre-flight checklist

-----

#### Actual Behavior

I am receiving the following permission error:

The stream or file "/var/www/snipe-it/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied

NOTE: I have changed the apache user permission to r/w/x for the www folder and am still getting the error. I have also tried setting the permissions to 777 for the entire directory. To verify the permissions I logged in as apache via bash and wrote to all the storage directories without an issue. Thanks in advance!

-----

#### Please confirm you have done the following before posting your bug report:

- [ YES ] I have enabled debug mode 
- [ YES ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
YES
- Version of Snipe-IT you're running
- Version of PHP you're running
7
- Version of MySQL/MariaDB you're running
latest stable
- What OS and web server you're running Snipe-IT on
CentOS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
The stream or file "/var/www/snipe-it/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
NO
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by gtechman** [comment]
I'm currently able to write both in the storage directory and in the log file when I'm logged in as apache so I'm at a complete loss as to why I'm getting a stream error/permission denied.

**Comment by snipe** [comment]
Are you running SELinux maybe? https://snipe-it.readme.io/v4.1.6/docs/linuxosx#section-notes-on-selinux

**Comment by gtechman** [comment]
Figured it out, I thought I had disabled SELinux but apparently I had not. Thanks a bunch for the help!! Now our organization can utilize this awesome system!

**Comment by snipe** [comment]
@gtechman glad to hear it!
