### ISSUE TITLE
FatalErrorException when querying large users table

### ISSUE THREAD

**Issue by bbrennan825** [snipe/snipe-it#474]
I've run into a bit of a problem. 

I have an installation of SnipeIT running in LUbuntu 14.04, virtualized in Vitrualbox with 2 processor cores and 1.5GB of RAM allocated. I followed all instructions in the installation guide at http://docs.snipeitapp.com/, so I'm not set up in any weird configuration. Everything is up and running and accessible from external addresses.

It seems that I'm running into an error when trying to load the "People" page. I work for an educational institution and have 1889 faculty, staff and students in my users table in my database. I believe the problem has to do with the size of the table as it works fine with a lower number of entries.

The error that shows up says: Symfony \ Component \ Debug \ Exception \ FatalErrorException Allowed memory size of 134217728 bytes exhausted (tried to allocate 3381792 bytes)

If you need additional information from the error page, I'd be more than happy to provide it.

At first I thought my allocated memory was too low, but I've monitored it while the query is happening and it doesn't seem to even get above 500MB. I still have 851MB free on my virtual drive.

Is this maybe a cache size setting that needs to be changed somewhere? It doesn't seem to be an issue with MySQL as I can query the database and retrieve all records without issue.

The really weird thing is that I was able to load this page successfully yesterday with the same amount of users. However, when I booted it up this morning, I'm not able to.

Any help you could provide would be much appreciated.

**Comment by bbrennan825** [comment]
Nevermind, I just had to increase the memory limit in PHP. Great app, by the way.

**Comment by snipe** [comment]
Great, glad you got it sorted!
