### ISSUE TITLE
License Notes - 255 character limit

### ISSUE THREAD

**Issue by cparmar** [snipe/snipe-it#475]
Can the notes section character limit for a license be upped at all?

The notes for an asset allowed me to enter a string longer than 255 characters.

**Comment by kobie-chasehansen** [comment]
What version are you using? Think this was fixed already

https://github.com/snipe/snipe-it/issues/386

**Comment by cparmar** [comment]
v1.1.2, I upgraded this morning for yesterday's bug fixes.

Is it meant to show the point release version number in the bottom right
corner? or just v1.1?

**Comment by cparmar** [comment]
It was updated for the serial number field, not the Notes.

**Comment by kobie-chasehansen** [comment]
ah sorry about that...

**Comment by cparmar** [comment]
np
