### ISSUE TITLE
LDAP password not syncing

### ISSUE THREAD

**Issue by jmartins1** [snipe/snipe-it#4762]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)
Logon issue using LDAP: V 4.1.9
-----
I'd expect that while syncing with Active Directory that members should be able to login to inventory using their network login.

#### Actual Behavior
Except for my account, if a member does not have a local account they are unable to access the inventory.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
This usually means something is off with your LDAP auth query or username fields in your LDAP settings. Username for AD should be `samaccountname` (lower case), and the auth query should be `sAMAccountName=`

**Comment by jmartins1** [comment]
That was it. Thank you. I had the sAMAccountName= all in lowercase without the =. I wish the email was that issue to resolve. Still scratching my head even after all the suggestions.

 

 

 

Jose Martins, M.Ed.

IT Administration

  <https://docs.google.com/uc?export=download&id=0BxOTzhkULnX0NkRNeUFLRC1OZm8&revid=0BxOTzhkULnX0MTF2dnp1VEdIdWVMbStNbmJOcXBCVVdvR0JNPQ> 

 

JMartins@ARPrep.org

 <javascript:void(0)> 303-362-1266  Ext. #419

705 Austin Ave. Erie, CO 80516

 

 

Statement of Confidentiality

The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.

**Comment by snipe** [comment]
@jmartins1 which one is your email ticket?

**Comment by jmartins1** [comment]
#4763

 

 

 

Jose Martins, M.Ed.

IT Administration

  <https://docs.google.com/uc?export=download&id=0BxOTzhkULnX0NkRNeUFLRC1OZm8&revid=0BxOTzhkULnX0MTF2dnp1VEdIdWVMbStNbmJOcXBCVVdvR0JNPQ> 

 

JMartins@ARPrep.org

 <javascript:void(0)> 303-362-1266  Ext. #419

705 Austin Ave. Erie, CO 80516

 

 

Statement of Confidentiality

The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.

**Comment by snipe** [comment]
Ah - can you provide more info to that ticket? The STMP settings are in your .env file, as mentioned there. If you're still having problems, update that ticket with what you've tried, any new errors, etc.

**Comment by jmartins1** [comment]
Below are my .env settings

 



 

What I’ve tried

 

1.	Changing the port numbers between 587, 465 and 25. I use 465 with ssl/tls in Outlook and it works fine.
2.	Changed the username field between the username and the domain and just the username
3.	Verified the login username and password
4.	Swtiched encryption between: tls, null, ssl/tls, tls/ssl
5.	Used “ and ‘ around the From Name and Replyto Name
6.	Used ‘ around all entries after the =
7.	Ensured no spaces existed between the = and the setting
8.	Ensured Google was setup to accept “unsafe” application connections.
9.	Tried verious combinations of these settings

 

Jose Martins, M.Ed.

IT Administration

  <https://docs.google.com/uc?export=download&id=0BxOTzhkULnX0NkRNeUFLRC1OZm8&revid=0BxOTzhkULnX0MTF2dnp1VEdIdWVMbStNbmJOcXBCVVdvR0JNPQ> 

 

JMartins@ARPrep.org

 <javascript:void(0)> 303-362-1266  Ext. #419

705 Austin Ave. Erie, CO 80516

 

 

Statement of Confidentiality

The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.

**Comment by snipe** [comment]
Please post your additional information to the *other* ticket - the one related to mail settings. 

We'll still need more information though, such as what specific errors you're getting, etc. Are you trying to use gmail as your outgoing server? (Please do not reply to this ticket, reply to #4763)

Also you may want to trim your email replies a little better - I keep having to delete your work email address, since Github takes your entire reply, including the `from <you@example.com>` bits.

**Comment by jmartins1** [comment]
I’ve update #4763. Please note that that ticket is closed.

 

Jose
