### ISSUE TITLE
Email not working (Password reset, etc.)

### ISSUE THREAD

**Issue by jmartins1** [snipe/snipe-it#4763]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)
V 4.1.9

I've been attempting to use the email system within 4.1.9, for things like forgot my password or send member password. I'd expect that I'd be able to utilize this system to send temp password when selecting forgot password etc.
-----

#### Actual Behavior
Unable to send and email in any case. Not surprised however, I could not find a single place for smtp settings; how is it supposed to send out email with this configuration?

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by tiagom62** [comment]
Its in .env

**Comment by snipe** [comment]
Please see the [mail .env configuration documentation](https://snipe-it.readme.io/docs/configuration#section-required-outgoing-mail-settings).

**Comment by jmartins1** [comment]
Are you trying to use gmail as your outgoing server? YES

Below are my .env settings

![2018-01-10_10-10-12](https://user-images.githubusercontent.com/31219479/34799253-5d2a6ff8-f61c-11e7-8323-3be48251ce08.jpg)

What I’ve tried

1.	Changing the port numbers between 587, 465 and 25. I use 465 with ssl/tls in Outlook and it works fine.
2.	Changed the username field between the username and the domain and just the username
3.	Verified the login username and password
4.	Swtiched encryption between: tls, null, ssl/tls, tls/ssl
5.	Used “ and ‘ around the From Name and Replyto Name
6.	Used ‘ around all entries after the =
7.	Ensured no spaces existed between the = and the setting
8.	Ensured Google was setup to accept “unsafe” application connections.
9.	Tried verious combinations of these settings

If you require additional information please provide the steps to logs etc.

**Comment by tiagom62** [comment]
Since you ignored the questions in the template I’ll ask here.

What os? If you have selinux enabled you may need to allow smtp.

**Comment by jmartins1** [comment]
I’m using Server 2012r2. I do not have selinux

 

 

 

 

Jose Martins, M.Ed.

IT Administration

  <https://docs.google.com/uc?export=download&id=0BxOTzhkULnX0NkRNeUFLRC1OZm8&revid=0BxOTzhkULnX0MTF2dnp1VEdIdWVMbStNbmJOcXBCVVdvR0JNPQ> 

 

JMartins@ARPrep.org

 <javascript:void(0)> 303-362-1266  Ext. #419

705 Austin Ave. Erie, CO 80516

 

 

Statement of Confidentiality

The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.

**Comment by tiagom62** [comment]
Any firewall in play that blocks smtp?

**Comment by jmartins1** [comment]
No, I’ve disabled the server firewall. Our web filter is not blocking this content; I have other applications that utilize Google smtp without issue.

 

Jose

**Comment by jbloomer** [comment]
Confirmed. I have tried various settings with our company smtp relay server and no matter what I configure I cannot send emails. Here is a sample steralizing version of my settings

```
# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=smtp.mydomain.com
MAIL_PORT=25
MAIL_USERNAME=ldapuser@mydomain.com
MAIL_PASSWORD=myLDAPPassword
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=snipe-it@mydomain.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=myDistributionList@mydomain.com
MAIL_REPLYTO_NAME=DL Friendly Name
```

**Comment by snipe** [comment]
@jmartins1 did you go through the [additional steps](https://snipe-it.readme.io/docs/configuration#section-using-gmail) mentioned for using Gmail? 

There's nothing wrong with the email system in Snipe-IT. The issue is definitely on the server/mail server side. If there are no error logs though, I'm not sure how to help troubleshoot this further.

**Comment by jmartins1** [comment]
I set it up using the “additional steps” link provided and have set this up on various other systems without problems. Maybe you guys can attempt connecting to Gmail for yourselves? It’s not working.

 

 

 

 

Jose Martins

**Comment by snipe** [comment]
We have already tested Gmail. I just used these settings and immediately received the lost password email.

```
# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=phpchick@gmail.com
MAIL_PASSWORD='MYPASSWORD'
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=phpchick+from@gmail.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=phpchick+replyto@gmail.com
MAIL_REPLYTO_NAME='Snipe-IT'
```

<img width="755" alt="screen shot 2018-01-20 at 7 31 40 am" src="https://user-images.githubusercontent.com/197404/35185135-1fc8bda0-fdb4-11e7-9a54-045ecfbcfb34.png">

**Comment by jmartins1** [comment]
Can you tell me how to provide you with log files? It doesn't seem that I'm the only user experiencing this issue. Thank you.

⁣Sent from BlueMail ​

**Comment by jmartins1** [comment]
I never got this feature to work. Sorry, but no matter the configuration, I was not able to even send a test message. Email is not that difficult to setup but I met my match here.

⁣Sent from BlueMail ​

**Comment by darshanawijesinghe** [comment]
Email not working for Office 365

**Comment by rafapascual** [comment]
The solution for me was to submit my username instead of my email address in the reset password form, which in my case are different. The reset link arrived immediately after using the username.

Hope this helps anyone.
