### ISSUE TITLE
Feture Request: API call to get the asset ID from asset_tag

### ISSUE THREAD

**Issue by pietrogb** [snipe/snipe-it#4767]
#### Desired Behavior
I'd like to do a lookup by asset search using the APIs, in a similar way of the searck bar inside the UI.
Giving the asset_tag, that is an unique field, I'd like to have the asset ID, otherwise the only way seems to get all the assets, and parse that to get the ID.

I'd like to do something like:
"https://your-server/api/v1/hardware/asset_tag/7575222087" 
Then get "1377" for result, or all the details of the specific asset.

-----

#### Actual Behavior
What currently happens is Snipe-IT returns a 404 Page not found error.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
    Upgrade
- Version of Snipe-IT you're running 
    v4.1.9 build 3128
- Version of PHP you're running  
    5.6.30
- Version of MySQL/MariaDB you're running  
    Ver 15.1
- What OS and web server you're running 
    Snipe-IT CentOS Linux 7 on Ovirt VM
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) 
    Manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
     I'm interacting using cURL with the console of a remote host.
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
     I've upgraded it, and moved to a git installation.
- Indicate whether or not you've manually edited any data directly in the database
    I have not.

**Comment by jlevy-wishfarms** [comment]
+1 for this request.  My boss has charged me with completely revamping our asset management system.  His goal is to be able to scan one of our asset tags with his phone and see relevant info.  Seems feasible through the API with this feature

**Comment by snipe** [comment]
This was already implemented in [4.3.0](https://github.com/snipe/snipe-it/releases/tag/v4.3.0). See the documentation. https://snipe-it.readme.io/v4.4.0/reference#hardware-by-asset-tag

@cornwella - that's incorrect. [Per the docs](https://snipe-it.readme.io/v4.4.0/reference#hardware-by-id), you can search for an asset, or you can pass it an explicit ID.

**Comment by pietrogb** [comment]
Thank you for the fantastic work and for this feature!
