### ISSUE TITLE
Calendar shows wrong language and dateformat

### ISSUE THREAD

**Issue by atuc2** [snipe/snipe-it#4769]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

While adding new device, clicking calendar for a date, it should show Europe/Helsinki, it shows months in English,

Settings in are localization.

![image](https://user-images.githubusercontent.com/30864603/34699896-ac7e8c0e-f4e8-11e7-909d-549a1b0b6d47.png)

But it still shows this.
 
![image](https://user-images.githubusercontent.com/30864603/34699884-90c4a016-f4e8-11e7-984a-093c7cdd19fc.png)

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  YES
- Version of Snipe-IT you're running v4.1.9 - build 3128 
- Version of PHP you're running 7.0.22
- Version of MySQL/MariaDB you're running  Ver 15.1 Distrib 10.1.30-MariaDB
- What OS and web server you're running Snipe-IT on Ubuntu 16.04.3
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) I used install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error All pages are effected, where is calendar for dates. 
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. Yes, problem is there to.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. No errors messages so far.
- Indicate whether or not you've manually edited any data directly in the database No, i havent.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
That format is the format the database is expecting - YYYY-MM-DD. The localization settings are only for displaying saved output.

**Comment by xxMarekxx** [comment]
Hello. 
Is there a chance to change the calendar date to Polish for example?
i mean the name of months.
we have couple old users and they can not speak english.
