### ISSUE TITLE
When viewing asset its reported as undeployable, editing asset shows ready to deploy

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#477]
This is in the DEV branch.

![image](https://cloud.githubusercontent.com/assets/10247644/5900959/6b018dc0-a53c-11e4-94d6-13e8415be646.png)

![image](https://cloud.githubusercontent.com/assets/10247644/5900962/6dbf2900-a53c-11e4-8f77-32cd541c1c77.png)

**Comment by snipe** [comment]
In this example, which is the correct one? RTD?

**Comment by kobie-chasehansen** [comment]
Yes RTD is correct

**Comment by snipe** [comment]
Hrm, I can't reproduce locally. When you first created it, did you set the status to RTD to start with? Or was it something else and then switched to RTD?

**Comment by snipe** [comment]
Can you check out what I just pushed to develop? I can't reproduce the issue locally, but I think my change may fix it for you.

**Comment by kobie-chasehansen** [comment]
Looks good, thanks.

**Comment by roncsak** [comment]
I also have this issue, I installed snipe-it 2 days ago. Should I check develop branch, also ?

**Comment by snipe** [comment]
@roncsak yes, please
