### ISSUE TITLE
License/Accessories/Consumables does not show up in "Companies" Tab

### ISSUE THREAD

**Issue by jassonxp** [snipe/snipe-it#4770]
Hi,

Under Settings -> Companies -> we have company list and from there, once we list to any company in the list, we go to the new page where show up the statistic of:
- Assets -> OK
- Licenses -> Show NOTHING
- Accessories -> NOTHING
- Consumables -> NOTHING

This is should be a bug as I did test on 3 differences servers, and get the same result. 
Hope that this report helping to figure out the issue.

cheers,l

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by jassonxp** [comment]
Hi, please find below the answers

* Version of Snipe-IT you're running    **Version v4.1.9-pre - build 3128 (master)**
* What OS and web server you're running Snipe-IT on  **CentOS 7 + Apache/2.4.6**
* What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)  **install.sh**
* If you're getting an error in your browser, include that error  **there is no error in browser**
* What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **Setting ->Companies -> Select a company -> choose "License" Tab**
* If a stacktrace is provided in the error, include that too. **may you show me where I can get it**
* Any errors that appear in your browser's error console. **no error in web browser**
* Confirm whether the error is reproduceable on the demo. **seems error on Snipe-IT Demo page: https://demo.snipeitapp.com/companies/1**
* Onclude any additional information you can find in app/storage/logs and your webserver's logs.
* Include what you've done so far in the installation, and if you got any error messages along the way.
* Indicate whether or not you've manually edited any data directly in the database  **-->This is created manually by myself**

**Comment by jassonxp** [comment]
Please refer to the Links and pictures where I get from Demo Snipe-IT, this indicate that License also does not show up in Demo version, please advise:

https://demo.snipeitapp.com/licenses
![image](https://user-images.githubusercontent.com/34444186/34754855-ffe9c042-f5f2-11e7-9370-d3eccc474603.png)

https://demo.snipeitapp.com/companies/8
![image](https://user-images.githubusercontent.com/34444186/34754864-158d097c-f5f3-11e7-85d4-62f09dd0d4b1.png)

**Comment by snipe** [comment]
Fixed on develop

**Comment by jassonxp** [comment]
What did you mean? so it can't fix now?
