### ISSUE TITLE
Install.sh - Missing .env?

### ISSUE THREAD

**Issue by schmidiij** [snipe/snipe-it#4771]
#### Expected Behavior (or desired behavior if a feature request)

Is there no .env-File?

-----

#### Actual Behavior

When i install Snipe-IT with the install.sh - script for Ubuntu, so i didn't found the .env-file....

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
 Fresh installation with the install.sh - Script

**Comment by ahmadsss** [comment]
cp .env.example .env

**Comment by schmidiij** [comment]
... no sorry. it doesn't exist

What i did:
git clone https://github.com/snipe/snipe-it snipeit
cd snipeit
./install.sh

in the snipeit - folder (clone from github) is this:
![grafik](https://user-images.githubusercontent.com/29889802/34715698-c251a0b2-f52d-11e7-822e-84bb97550144.png)

After the installation in the /var/www/snipeit :
![grafik](https://user-images.githubusercontent.com/29889802/34715731-dfc5ff1c-f52d-11e7-9684-13c472b28c7c.png)

... i didn't understand this?

**Comment by schmidiij** [comment]
... the file is hidden

With WinSCP, i found it
![grafik](https://user-images.githubusercontent.com/29889802/34719363-d76ecc9c-f53a-11e7-850b-c5c872263e9d.png)

**Comment by ahmadsss** [comment]
i was going to tell you use ls -a
great you found it
