### ISSUE TITLE
API Json Limitations

### ISSUE THREAD

**Issue by Robin38219733** [snipe/snipe-it#4772]
#### Expected Behavior (or desired behavior if a feature request)

I Was writing an Python script to get data from my Munki-Report System and import it into Snipe-IT via the API. The API Request should give out all Assets.

#### Actual Behavior

I only get 49 Items in the json Ouput but i got 103 Assets. The Web Interfaces shows me 103 Entrys but the json only gives me 49.
I inserted sucessfully the 103 entrys via the API but i can only get 49 back.
Headers:
Authorization: Bearer XXX
Content-Type: application/json
I also tried doing this with other rested Applications but i get also only 49 Entrys.

![image](https://user-images.githubusercontent.com/22550782/34714378-9314ac26-f529-11e7-8f74-29de74ec89e2.png)

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
Fresh Installation
- Version of Snipe-IT you're running
v4.1.9 build 3128 (ge5a7e66)
- Version of PHP you're running
7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running
5.6
- What OS and web server you're running Snipe-IT on
Docker version 17.09.1-ce, build 19e2cf6
Debian 4.9.65-3 (2017-12-03) x86_64 GNU/Linux
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Docker / Docker-Compose
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
---
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
https://snipeit.example.com/api/v1/hardware
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Cant create API Key.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
I cant find any Errors in the Webserver log. The app/storage/logs Directory don't exists.
- Include what you've done so far in the installation, and if you got any error messages along the way.
I installed it with `docker-compose up --force-recreate -d`

My compose File:
`version: '3.3'
services:
  snipeit:
    container_name: snipeit-base
    image: snipe/snipe-it:latest
    expose:
      - "80"
      - "443"
    environment:
      APP_URL: "example.com/snipeit"
      APP_KEY: "XXX"
      DB_HOST: "snipeit-mysql"
      MYSQL_USER: "snipeit"
      MYSQL_DATABASE: "snipeit"
      MYSQL_USER: "snipeit"
      MYSQL_PASSWORD: "snipeit"
      APP_ENV: "production"
      APP_DEBUG: "false"
      APP_TIMEZONE: "Europe/Berlin"
      APP_LOCALE: "de"
      APP_URL: "http://snipeit.example.com"
    networks:
      - snipeit-net
      - reverse-proxy-net
    volumes:
    - volume_snipe-it_data:/var/lib/snipeit
  mysql:
    container_name: snipeit-mysql
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "snipeit"
      MYSQL_USER: "snipeit"
      MYSQL_PASSWORD: "snipeit"
    networks:
      - snipeit-net
    volumes:
    - volume_snipe-it_database:/var/lib/mysql

networks:
  snipeit-net:
    driver: bridge
  reverse-proxy-net:
    external:
      name: reverse-proxy-net
volumes:
  volume_snipe-it_data:
    external: true
  volume_snipe-it_database:
    external: true`
- Indicate whether or not you've manually edited any data directly in the database
I haven't edited any Data in the Database directly.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by amarbhanu** [comment]
I thing you have 50 row and your API URL limit will be increase only, because default API limit is 50. 

http://localhost/api/v1/hardwareassets?status=&order_number=&company_id=&status_id=&sort=updated_at&order=desc&limit=30&offset=0

Please check it is working.

**Comment by therealjoshuad** [comment]
Yes, default API calls limit to 50, you need to add the limit parameter to your url as the previous poster posted. He put 30 on his example, but you just need to put a higher number than the number of assets that you have.

**Comment by mduesi** [comment]
I tried to use the limit parameter for the manufacturers endpoint, but with no luck. Any ideas?
