### ISSUE TITLE
Supplier Page: Username/Password Field [feature request]

### ISSUE THREAD

**Issue by 08solsticegxp** [snipe/snipe-it#4773]
#### Expected Behavior (or desired behavior if a feature request)

Everything works as expected
-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Version of Snipe-IT you're running
**v4.1.9 - build 3128 (master)**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
**<snipeitURL>/suppliers/create**

Feature:
I find there are a lot of supplier portals now that you can log into. I'm thinking having a username and password field on the suppliers page would be great to have all contact and login information in one place.

**Comment by ckinsler** [comment]
Could the current notes field not be used for this purpose?

**Comment by snipe** [comment]
I'm not really keen on this super specific level of modification that will likely not be of use to the vast majority of users. I would agree with @ckinsler and suggest using the notes section for this.
