### ISSUE TITLE
Feature Requets: Categories and notes on Licenses (and Components)

### ISSUE THREAD

**Issue by seanmcilvenna** [snipe/snipe-it#4775]
I would like to have a Categories field on Licenses and Components.
Examples of License categories:
* Web Application
* Server Software
* Desktop Productivity
* Developer Tool

I would also like to have a Notes field that would allow the user to add additional information. For example, in cases where I am tracking the installation of a product on a server, it might be important to track where the application (associated with the license) is installed, where its database is installed, config files, etc. Beyond my use-case, I think notes are always a good thing to have on any type of information.

**Comment by duel007** [comment]
I am also interested in this. It would be great to be able to add a note when checking out an accessory to a user, IE if a user has two display adapters, one for desk use attached to a monitor and one for portable presentation use. It would be good to have the note on the user page in the list of components checked out to the user.

**Comment by seanmcilvenna** [comment]
Can we keep this open? Still interested in having this functionality...
