### ISSUE TITLE
Feature Request: Filtering searches

### ISSUE THREAD

**Issue by seanmcilvenna** [snipe/snipe-it#4776]
I would like to be able to filter on specific columns within the various listing screens. For example, I'd like to see all licenses by a specific vendor, or all "laptop" categoried assets.
We have 100s-1000s of assets and licenses, and although the "search" feature is helpful, it is still challenging to get a specific list of assets, licenses and components that I'm looking for.

**Comment by snipe** [comment]
Duplicate of #3340
