### ISSUE TITLE
File upload picker type not consistent - Does not show filename selected

### ISSUE THREAD

**Issue by ckinsler** [snipe/snipe-it#4779]
#### Expected Behavior (or desired behavior if a feature request)
In the following areas, when you click on "Select File.." next to Upload Image and make your file selection, the file name should immediately be shown next to this box to show that a file was actually selected.  By not doing so, the user is confused as to if they actually made their selection, and if it will do anything upon save

- New Model screen (https://[URL]models/create]
- New Categories Screen (https://[URL]/categories/create
- New Manufacturer Screen (https://[URL]/manufacturers/create) 
- New Suppliers Screen (https://[URL]/suppliers/create)
- New Department Screen (https://[URL]/departments/create)
- New Locations Screen (https://[URL]/locations/create)
- New Companies Screen (https://[URL]/companies/create)
- New Accessories Screen (https://[URL]/accessories/create)
- New Component Screen (https://[URL]/components/create)

Note:  Correcting this would make the system mirror the current behavior of the new Hardware Creation (https://[URL]/hardware/create), which seems to have a **different** file picker (by default it says Choose File, along with No file chosen, and then displays the file name upon selection).  I believe this would be the desired experience system wide.

Not sure if this is a bug, or that you may just be moving to the new file picker that is in the majority of the screens?  However, I would recommend to help eliminate user confusion that you standardize on the use of the one currently on the Hardware Screen.  Thanks!

-----

#### Actual Behavior

See above

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh

- Version of Snipe-IT you're running
 v4.1.9 - build 3128 (master)

- Version of PHP you're running
PHP 7.0.22

- Version of MySQL/MariaDB you're running
mysql  Ver 15.1 Distrib 10.1.30-MariaDB

- What OS and web server you're running Snipe-IT on
Ubuntu 16.04.3 x64, Apache2

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
See Above

- If a stacktrace is provided in the error, include that too.
N/A

- Any errors that appear in your browser's error console.
N/A

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Yes, all confirmed via demo URL's

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
N/A

- Include what you've done so far in the installation, and if you got any error messages along the way.
N/A

- Indicate whether or not you've manually edited any data directly in the database
N/A

**Comment by snipe** [comment]
The assets file picker was optimized for uploading directly from a mobile device, that's why it uses a different file picker.
