### ISSUE TITLE
Lookup by Asset Tag from the Create new asset page

### ISSUE THREAD

**Issue by BrettFagerlund** [snipe/snipe-it#4780]
#### Expected Behavior (or desired behavior if a feature request)

Searching for Asset from create asset page should search for asset and not submit asset save. Or maybe prompt to not save and then search.

-----

#### Actual Behavior

Asset tag search box submits the create asset save when used from the asset create page instead of searching, while create licence page will abandon create and search for the asset tag.

-----

-----
#### Provide answers to these questions:  

- Version v4.1.9 - build 3128
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - /hardware/create -> then enter an asset tag in the search box at top(valid tag)
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - yes it is

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.
- ignoring majority the questions as its more of a functionality bug and easily reproduced via demo but i'll be happy to provide more info if needed.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
@BrettFagerlund I... have no idea why that's happening. :-/

**Comment by d1l1** [comment]
I think changing [this](https://github.com/snipe/snipe-it/blob/3566f37981184120a5e38df2381eda8fdb51ea30/resources/views/hardware/edit.blade.php#L193) line should fix this.

`$("form").submit(function (event) {`
to
`$("#create-form").submit(function (event) {`
