### ISSUE TITLE
Request for new language: zh-HK 

### ISSUE THREAD

**Issue by lifehome** [snipe/snipe-it#4782]
Hello there,

I would like to contribute for zh-HK translation, as well as the approval right for the translated strings.

I have been constantly contributing zh-HK translations on Gitea the self hosted git service, and the Mini Metro game, and also opt for some cross-localization tasks such as reputable login plugin for Minecraft server "AuthMe reloaded" for all Chinese translations.

Looking forward to meet snipe-it in the "zh-HK" way! ;)

**Comment by snipe** [comment]
@lifehome great! I've added zh-HK: https://crowdin.com/project/snipe-it/zh-HK

If you let me know what your username is on the Crowdin platform, I'll add you as a proofreader.

**Comment by lifehome** [comment]
@snipe My username is lifehome on Crowdin too!

**Comment by Ericwonne** [comment]
Does it mean then I could use Simplified Chinese as my default language...? And how? Please give a brief introduction? Previously appreciated.
