### ISSUE TITLE
License cannot edit but showing a lot of license on report....

### ISSUE THREAD

**Issue by rolandaero360** [snipe/snipe-it#4783]
I'm having this problem. When I click the license tab it shows like this...
![licence](https://user-images.githubusercontent.com/35290902/34764854-c6077e4a-f62a-11e7-996d-b7647134d394.PNG)

And then the license showing this....
![total license](https://user-images.githubusercontent.com/35290902/34764903-d7c4e370-f62a-11e7-9953-9f0b51e12fbe.PNG)

I'm using Xampp
![xampp](https://user-images.githubusercontent.com/35290902/34764926-edfc5114-f62a-11e7-8711-071ae0b9f8a7.PNG)

And I'm Using Snipe It 4.1.9... Thanks!

**Comment by snipe** [comment]
Please see the [XAMPP documentation](https://snipe-it.readme.io/v4.1.6/docs/xampp#section-remove-built-in-aliases).

<img width="863" alt="screen shot 2018-01-10 at 2 13 29 am" src="https://user-images.githubusercontent.com/197404/34767066-f54a5c6a-f5ab-11e7-992e-823632aae45b.png">

**Comment by rolandaero360** [comment]
Thanks for the reply... Can I transfer it to WAMP?

**Comment by snipe** [comment]
Sure - XAMPP is our least recommended way to run Snipe-IT specifically because of this /licenses issue that's built into the XAMPP config. Any other server we have docs on will work fine.

**Comment by rolandaero360** [comment]
How can I transfer the files to Wamp? Can you help me pls? Thank you!

**Comment by rolandaero360** [comment]
Right now, I'm testing the Snipe It and I'm looking forward to it and use in web. Thank you for your awesome app.

**Comment by snipe** [comment]
It will probably just be easier to reinstall on WAMP versus trying to move files around. If you have already added data, just export your database (using phpMyAdmin, or the built-in Snipe-IT admin backup tool) and then import it into your WAMP database.

**Comment by rolandaero360** [comment]
That's my another issue. I can't backup my work. It says, Error: Backup failed because The dump process failed with exitcode 1 : General error : The system cannot find the path specified. .

**Comment by snipe** [comment]
That usually means you don't have mysqldump installed, or the path to it is wrong in your .env. Probably easier to just use phpMyAdmin or another free MySQL tool that will let you export.

**Comment by rolandaero360** [comment]
How can I do that? Can you please help me with that? I'm not really an IT expert nor a coder. Thanks!
