### ISSUE TITLE
Can't change default language

### ISSUE THREAD

**Issue by enmostafaeissa** [snipe/snipe-it#4786]
#### Expected Behavior (or desired behavior if a feature request)

when i change the Default Language from English us to arabic it should change all the app to arabic

-----

#### Actual Behavior

Nothing changes

-----

#### Please confirm you have done the following before posting your bug report:

- [ no] I have enabled debug mode 
- [ yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? a fresh install
- Version of Snipe-IT you're running snipe-it-4.1.9
- Version of PHP you're running wamp php7.1.9
- Version of MySQL/MariaDB you're running MariaDB 10.2.8
- What OS and web server you're running Snipe-IT on windows 2008 x64 and WampServer Version 3.1.0 64bit
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)  manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.  no
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. yes 
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. no errors and the system work fine except for language
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
We already discussed this in Gitter. Individual user languages in their profile will override language settings in Settings > Localization.
