### ISSUE TITLE
Accessory Checkout

### ISSUE THREAD

**Issue by awstechnologies** [snipe/snipe-it#4787]
[snipe.aws.pdf](https://github.com/snipe/snipe-it/files/1619138/snipe.aws.pdf)
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)
I tried to checkout an accessory; after clicking the 'Checkout' button I am presented with a 'Whoops, looks like something went wrong.' page. Debug is turned on and I got the below error.

(2/2) ErrorExceptionTrying to get property of non-object (View: /var/www/snipe-it/resources/views/accessories/checkout.blade.php)
--
in 86481cee0c61cc7f555cd3f3a86098e450e59a48.php (line 40)

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode - YES
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) - YES

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - Existing Install
- Version of Snipe-IT you're running - v4.1.9 build 3128 (ge5a7e66)
- Version of PHP you're running - 7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running - Not Sure ( How Can I find this out? )
- What OS and web server you're running Snipe-IT on - Unbuntu 16.x and Latest Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
(2/2) ErrorExceptionTrying to get property of non-object (View: /var/www/snipe-it/resources/views/accessories/checkout.blade.php)
--
in 86481cee0c61cc7f555cd3f3a86098e450e59a48.php (line 40)

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
http://snipe.aws.local/accessories/1/checkout

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. - No JS Console Output ( Chrome )
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - Works fine in the demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
Restart of services, cleared cache of browser, tried chrome incognito mode. Tried deleting accessory and creating a new one. Issue still persists.
[snipe.aws.pdf](https://github.com/snipe/snipe-it/files/1619136/snipe.aws.pdf)

- Indicate whether or not you've manually edited any data directly in the database
NO - Only interacted using web GUI

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
What is on `86481cee0c61cc7f555cd3f3a86098e450e59a48.php` on line 40?

**Comment by awstechnologies** [comment]
the file does not appear to exist

**Comment by snipe** [comment]
It will be in your `storage/framework/views/` directory

**Comment by awstechnologies** [comment]
Somereason 'locate' couldn't find it but I have looked at the file ' /var/www/snipe-it/resources/views/accessories/checkout.blade.php' line 40 and got the below.
![image](https://user-images.githubusercontent.com/35299622/34777375-112bcda4-f612-11e7-8678-3cd62ee09fd5.png)

**Comment by snipe** [comment]
`storage/framework/views/86481cee0c61cc7f555cd3f3a86098e450e59a48.php`

**Comment by awstechnologies** [comment]
storage/framework/views/86481cee0c61cc7f555cd3f3a86098e450e59a48.php
![image](https://user-images.githubusercontent.com/35299622/34777468-53033f96-f612-11e7-9b1b-f0b5a9825277.png)

**Comment by awstechnologies** [comment]
I just found this; when listing the Accessories no category info is shown; but is present in the 'Edit' accessory page.
![image](https://user-images.githubusercontent.com/35299622/34777544-8e421afa-f612-11e7-8606-c99d302e8c20.png)

![image](https://user-images.githubusercontent.com/35299622/34777561-9b8157c6-f612-11e7-953a-0a0a1e4ad6bf.png)

**Comment by snipe** [comment]
It's erroring because the category it's associated with is likely invalid. Is it possible that category got deleted?

**Comment by awstechnologies** [comment]
The category is present but when opening that category I can see the accessory association is not present. Should I delete the category and asset and try from scratch?

![image](https://user-images.githubusercontent.com/35299622/34777721-1f8c433c-f613-11e7-9e88-281cbb497057.png)

**Comment by snipe** [comment]
Can you look at that accessory record in the database directly and confirm that the category:

1) exists in the database
2) has a `deleted_at value` of NULL?

You can try creating a new category and assigning that accessory to it and see if that resolves the issue.

**Comment by awstechnologies** [comment]
@snipe I deleted the accessory and category and entered them again. This appears to have fixed the issue. I can comment and state the originally I created the category from within the 'Create Accessory' page; using the 'New' button to the right of the category drop down. This time I created the category from the Categories Page. I found that the original category type field was set to Asset rather than Accessory. Hope this helps someone.

Apologies for bothering you with such a trivial subject that is a delete and try again thing

**Comment by awstechnologies** [comment]
Oh and thank you for your help @snipe !!!!!
Snipe-IT is a fantastic product.

**Comment by snipe** [comment]
Huh. When you create a category using the New button, does the new category show up in the Categories listing? And is it correctly attributed as an accessory category?

**Comment by awstechnologies** [comment]
Hi Snipe; apologies for the delay. Yes when registering a accessory; creating the category during this process doe provide the result of presenting the newly created category within the list of all the existing category. It issue is that the newly created category gets registered with a type of 'asset' and not accessory. They creating a new accessory, the drop-down box for 'Category Type' will only allow me to select Asset.

![image](https://user-images.githubusercontent.com/35299622/34877635-bba38a14-f79e-11e7-9b5c-c7caeac9f6e9.png)

**Comment by awstechnologies** [comment]
You can also see the field labels not being correct; surely it would be 'Name' and 'Type'?
