### ISSUE TITLE
Duplicate db column on splash screen

### ISSUE THREAD

**Issue by trollersovpw2** [snipe/snipe-it#4789]
#### Expected Behavior (or desired behavior if a feature request)

When clicking next on next on pre-flight, it goes into creating database tables section

-----

#### Actual Behavior

Says "Oops, something went wrong" I enabled debugging and says "SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'db_column' (SQL: alter table `custom_fields` add `db_column` varchar(191) null, add `help_text` text null)"

-----

#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode 
- [yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh install
- Version of Snipe-IT you're running - 4.1.9
- Version of PHP you're running - 7.0.27
- Version of MySQL/MariaDB you're running - MariaDB 10.1.26
- What OS and web server you're running Snipe-IT on Debian 9.3.0 with apache 2.4.25
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual installation using https://hostpresto.com/community/tutorials/how-to-install-snipe-it-on-ubuntu-16-04/
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - included above
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - http://192.168.7.36/setup/migrate?
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
The guide made me do this to the db:
"MariaDB [(none)]>CREATE DATABASE snipeit; Query OK, 1 row affected (0.00 sec)
Next, create a username and password for Snipeit with the following command:

MariaDB [(none)]>CREATE USER 'snipeit'@'localhost' IDENTIFIED BY 'password'; Query OK, 1 row affected (0.00 sec)
Next, grant privileges to the Snipeit database with the following command:

MariaDB [(none)]>GRANT ALL PRIVILEGES ON snipeit.* TO 'snipeit'@'localhost'; Query OK, 1 row affected (0.00 sec)
Next, you will need to run the FLUSH PRIVILEGES command so that the privileges table will be reloaded by MariaDB and we can use new credential:

MariaDB [(none)]>FLUSH PRIVILEGES; Query OK, 1 row affected (0.00 sec)"

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by Shuyinsama** [comment]
I am experiencing the same issue.

I am running locally on OSX 10.13.2
Laravel Valet 2.0.5.
MariaDB version 10.2.8

**Comment by snipe** [comment]
Can you pull the latest from master and tell me if you're still seeing this error?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
