### ISSUE TITLE
Feature request: Spare status

### ISSUE THREAD

**Issue by D2nnyim** [snipe/snipe-it#479]
If we create a device with the status Spare (which I created myself), is there a possibility to change it, that this isn't 'undeployable'?

**Comment by snipe** [comment]
What's the use case here? all ready-to-deploy assets are spares until they're assigned to someone.

**Comment by D2nnyim** [comment]
When new devices are delivered, we have them as 'Pending'
When I installed new devices (I already name them), I set them as 'Ready to Deploy'. (The computername has already been changed to the username)
When I install a new device, not for a specific user, I want it to be a spare device.
Also, when we run a report of all our devices, we want to see how many 'spares' we have in stock.

**Comment by snipe** [comment]
Hi @D2nnyim - we recently changed the way asset statuses work, so you should be able to create a new  deployable status (called Spares, for example). If you pull the latest off of develop, you should be able to check it out.

**Comment by D2nnyim** [comment]
Hi @snipe, thanks for the update.
This worked out great!

**Comment by snipe** [comment]
Awesome, glad it worked out!

![follow_your_dreams](https://cloud.githubusercontent.com/assets/197404/6245408/4a3b06fa-b713-11e4-9f9e-19f8be28a4ff.gif)
