### ISSUE TITLE
File type must be CSV when importing

### ISSUE THREAD

**Issue by jandresg** [snipe/snipe-it#4790]
#### Expected Behavior (or desired behavior if a feature request)

the csv to upload
-----

#### Actual Behavior

![screen shot 2018-01-10 at 10 58 27 am](https://user-images.githubusercontent.com/2886152/34781975-4b84fb46-f5f5-11e7-9161-c1134ebb069b.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
updating assets 

- Version of Snipe-IT you're running
n v4.1.9 - build 3128 (master)

- Version of PHP you're running
PHP 7.1.11-0ubuntu0.17.10.1
- Version of MySQL/MariaDB you're running
10.1.30-MariaDB-1~artful

- What OS and web server you're running Snipe-IT on
Apache Ubuntu

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
isntall.sh

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
import > import csv

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

I've tried multiple ways of creating the csv to import, I recently updated the csv that i imported in order to show everyone's assignments in my Org. but now cant import. I tried creating it from scratch using the import sample, I also tried editing the old successful import but nothing. ALSO, it works in CLI but not in the browser

**Comment by snipe** [comment]
The only thing I can suggest is to check the mime type of the file. The validator checks for any of the following:

- 'application/vnd.ms-excel',
- 'text/csv',
- 'text/plain',
- 'text/comma-separated-values',
- 'text/tsv'

If you're running this on a linux server, for example, you can try `file --mime-type -b filename`
