### ISSUE TITLE
checkout consumables and accessories to assets or locations

### ISSUE THREAD

**Issue by ppestime** [snipe/snipe-it#4791]
Hey, Thanks for such a great software but i am wondering if i can checkout consumables and accessories to assets or locations. This would be great for me !

SnipeIT 

Snipe-IT version | v4.1.9 build 3128
PHP Version | 7.0.21
Laravel Version | 5.4.35

**Comment by snipe** [comment]
That's not possible at this time.

**Comment by ppestime** [comment]
I think i would be great if these features were added to the next version. 

This would help for toner usage tracking, by checking out toners to the printer using them as an exemple. 

Your app is amazing!

**Comment by eldhom92** [comment]
Hey,
How can I check- in back the accessories like keyboards and mice back to inventory,

Thanks,
Eldhose
