### ISSUE TITLE
Feature Request:  Full Field List available in the Bottom Asset section of the Locations Tab

### ISSUE THREAD

**Issue by ckinsler** [snipe/snipe-it#4796]
#### Expected Behavior (or desired behavior if a feature request)
Would it be possible to expand out the available fields\columns displayed (and available in the picker box) on the bottom assets section of the locations detail screen (https://[URL]/locations/ID) ?

Currently this section only shows a very small subset of the asset fields, and does not include a critical field such as "Checked Out To", or any of the custom fields that are available under the normal "All Assets" view (https://[URL]/hardware)

Thanks!

![locations screenshot](https://user-images.githubusercontent.com/10969819/34833413-f07f019a-f6b4-11e7-9c3c-cfe6e21ac809.png)

-----

#### Actual Behavior

See above

-----

#### Please confirm you have done the following before posting your bug report:

N/A
-----
#### Provide answers to these questions:
N/A - Feature Request.  Confirmed functionality not available on demo system

**Comment by snipe** [comment]
This should be on the develop branch now.
