### ISSUE TITLE
Feature Request: Option for subdomain

### ISSUE THREAD

**Issue by cipnt** [snipe/snipe-it#4799]
Would be nice to have the option to use custom subdomains for the hosted version of SnipeIT.

For example change the domain name from mycompany.snipe-it.io to assets.mycompany.com 

The admin would have to add a CNAME or A record in their domain DNS for that to work.
In terms of SSL you could easily deploy [Letsencrypt](https://letsencrypt.org/) or the user could provide the SSL certificate and key for that subdomain.

**Comment by snipe** [comment]
@cipnt You can do that :) Just send us an email to support@snipeitapp.com (let us know your subdomain) and we'll get you set up. Just make sure you have a CNAME set up to point to your hosted IP. (We use Let's Encrypt.)
