### ISSUE TITLE
OAuth settings

### ISSUE THREAD

**Issue by cipnt** [snipe/snipe-it#4800]
I see there is a new section added in the admin Settings page – OAuth
I can't find any [documentation](https://snipe-it.readme.io/docs/admin-settings) on it...

It looks to me as this will allow SnipeIT to act as an authentication provider for third party applications.
It would be nice to add the reverse of that as well – support for third party OAuth authentication providers.

This will partly satisfy the need for [Google Apps/G Suite integration](https://github.com/snipe/snipe-it/issues/238) as well as other [requests](https://github.com/snipe/snipe-it/issues/1897)

Thanks!

**Comment by snipe** [comment]
@cipnt it's a feature that comes built-into the framework, but we haven't tested it at all (and the framework's documentation is poor) which is why it's not documented.

**Comment by chais0n** [comment]
OAuth would be better as it allows us to use authorization settings for group restrictions. At least in Keycloak, SAML doesn't allow fine grained authorization control. 

Please implement OAuth

**Comment by triple-HA** [comment]
According to MS article about [Deprecation of Basic authentication in Exchange Online](https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online) i have a question what can be done with OAuth in near future?

**Comment by ccalby** [comment]
Trying to get this to work now. Got a custom Laravel application which acts as the OAuth provider and generates a valid access token. 
Any suggestions on how to best implement this so Snipe-IT will be a client?

**Comment by Mikko21** [comment]
Hello Guys! someone can tell me if it's works now ?
