### ISSUE TITLE
how to change email config for docker on windows install

### ISSUE THREAD

**Issue by Metal0gic** [snipe/snipe-it#4801]
#### Expected Behavior (or desired behavior if a feature request)
change email settings, username and password
do i modify my docker env file and rebuild the docker image?
will deleting and rebuilding the docker image lose keep my data as long as i keep the same mysql container?
i understand you're not supposed to edit files inside docker.

-----

#### Actual Behavior

not sure how to in docker, 

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode (i dont know how in docker)
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh
- Version of Snipe-IT you're running
v4.1.9 build 3128 (ge5a7e66) 
- Version of PHP you're running
  | 7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running
mysql 5.6
- What OS and web server you're running Snipe-IT on
pulled docker container on windows server 2016
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
send mail failed
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
built docker with incorrect email information in my docker env file
- Indicate whether or not you've manually edited any data directly in the database
no

**Comment by uberbrady** [comment]
This is less of a Snipe-IT question and more of a general Docker question. But still, happy to try and help - 

The general idea is that Docker images should be relatively disposable. We aren't perfect at that yet, but we're pretty close, and we try as hard as we can.

If you've used the Volume option, then it should mostly be disposable and you can just re-run the docker container with the corrected environment file settings. Always safest, though, to be sure and not discard your old container in case you need something from it.
