### ISSUE TITLE
What is the archived field for?

### ISSUE THREAD

**Issue by therealjoshuad** [snipe/snipe-it#4804]
What is the archived field for? I don't have a single asset that is not false, but several asset's that are archived (status_id of 3). Working on some scripts with the API, do I need to worry about this field when archiving assets, or do I just set the status_id? Before asking this question, I set it the archived bit to 1, and the asset didn't appear to be archived.

(sorry for deleting the questions, but I figured they weren't needed on this one)

**Comment by snipe** [comment]
TBH, I'm not sure how much that's used anymore. It may be an artifact from before we had an archived status label type. You can just use the status label.
