### ISSUE TITLE
php artisan migrate error

### ISSUE THREAD

**Issue by gertje1978** [snipe/snipe-it#4807]
I upgrade my version from 3.5 to 4.19
Since I ran my last commands 'php artisan migrate' I get errors:

C:\xampp\htdocs\snipe-it>php artisan migrate
PHP Fatal error:  Uncaught Error: Class 'Log' not found in C:\xampp\htdocs\
-it\app\Exceptions\Handler.php:39
Stack trace:
#0 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Foundat
onsole\Kernel.php(320): App\Exceptions\Handler->report(Object(Symfony\Compo
Debug\Exception\FatalThrowableError))
#1 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Foundat
onsole\Kernel.php(132): Illuminate\Foundation\Console\Kernel->reportExcepti
ject(Symfony\Component\Debug\Exception\FatalThrowableError))
#2 C:\xampp\htdocs\snipe-it\artisan(35): Illuminate\Foundation\Console\Kern
andle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Com
t\Console\Output\ConsoleOutput))
#3 {main}
  thrown in C:\xampp\htdocs\snipe-it\app\Exceptions\Handler.php on line 39

Fatal error: Uncaught Error: Class 'Log' not found in C:\xampp\htdocs\snipe
pp\Exceptions\Handler.php:39
Stack trace:
#0 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Foundat
onsole\Kernel.php(320): App\Exceptions\Handler->report(Object(Symfony\Compo
Debug\Exception\FatalThrowableError))
#1 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Foundat
onsole\Kernel.php(132): Illuminate\Foundation\Console\Kernel->reportExcepti
ject(Symfony\Component\Debug\Exception\FatalThrowableError))
#2 C:\xampp\htdocs\snipe-it\artisan(35): Illuminate\Foundation\Console\Kern
andle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Com
t\Console\Output\ConsoleOutput))
#3 {main}
  thrown in C:\xampp\htdocs\snipe-it\app\Exceptions\Handler.php on line 39

Also in my browser, I have almost the same error:
 
Fatal error: Uncaught Error: Class 'Log' not found in C:\xampp\htdocs\snipe-it\app\Exceptions\Handler.php:39 Stack trace: #0 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(314): App\Exceptions\Handler->report(Object(Symfony\Component\Debug\Exception\FatalThrowableError)) #1 C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(122): Illuminate\Foundation\Http\Kernel->reportException(Object(Symfony\Component\Debug\Exception\FatalThrowableError)) #2 C:\xampp\htdocs\snipe-it\public\index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request)) #3 {main} thrown in C:\xampp\htdocs\snipe-it\app\Exceptions\Handler.php on line 39

Thanks for helping!

**Comment by imie** [comment]
try do these..

delete the files (not the directory) in bootstrap/cache
run composer dump-autoload
remove config/aws.php if it exists

**Comment by snipe** [comment]
See the [common issues](https://snipe-it.readme.io/docs/common-issues#section-class-awslaravelawsserviceprovider-not-found-or-class-log-not-found).

**Comment by gertje1978** [comment]
Thanks for your answer...The big fault was, that I forgot the use the new ENV file!
Now it's up and running!
Thanks for your help
GertBelgium
    On Tuesday, January 16, 2018, 8:25:38 AM GMT+1, snipe <notifications@github.com> wrote:  
 
 
Closed #4807.

**Comment by snipe** [comment]
Glad you got it sorted!

**Comment by ElectroArmy** [comment]
Please Help 
$php artisan migrate
PHP Fatal error:  Uncaught Error: Class 'Illuminate\Foundation\Application' not found in C:\xampp\htdocs\laravelapp\
openlaravel\bootstrap\app.php:14
Stack trace:
#0 C:\xampp\htdocs\laravelapp\openlaravel\artisan(18): require_once()
#1 {main}
  thrown in C:\xampp\htdocs\laravelapp\openlaravel\bootstrap\app.php on line 14


Fatal error: Uncaught Error: Class 'Illuminate\Foundation\Application' not found in C:\xampp\htdocs\laravelapp\openl
aravel\bootstrap\app.php:14
Stack trace:
#0 C:\xampp\htdocs\laravelapp\openlaravel\artisan(18): require_once()
#1 {main}
  thrown in C:\xampp\htdocs\laravelapp\openlaravel\bootstrap\app.php on line 14

**Comment by snipe** [comment]
Hi there - this issue is closed and doesn't seem directly related to your issue. Please create a new issue and fill in all of the questions in the new issue form. (When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.)
