### ISSUE TITLE
Information Request: Locations -> LDAP Search OU

### ISSUE THREAD

**Issue by agentbb** [snipe/snipe-it#4808]
Dear All,

How to use the "LDAP Search OU" field under Locations? What is the format? I have not found how to use it in documents.

Are you explaining by example?

Thanks

![2018-01-12 14_22_48-update location __ it asset management](https://user-images.githubusercontent.com/25081678/34873088-c83973dc-f7a4-11e7-9db6-25439a0dfabd.jpg)

**Comment by snazy2000** [comment]
You put the OU which contains users that are in that location and when the sync is done it will search that OU and then mark then in that location (I believe) someone correct me if I’m wrong :)

**Comment by agentbb** [comment]
Thanks but its not clear. In which format should I type? The distinguishedName? object canonical?

1- domain.com/ouTURKEY
2- OU=ouTURKEY,DC=domain,DC=com

Which format?

**Comment by agentbb** [comment]
Hello @snipe, do you have any idea about this?

**Comment by TheVakman** [comment]
@agentbb OU=Users,OU=Location1,OU=Locations,DC=domain,DC=contoso,DC=com

This seems to work for us.

**Comment by agentbb** [comment]
@TheVakman unfortunately does not working. Can you share the settings in more detail?

**Comment by CJChristensen** [comment]
Resurrecting this one as there isn't any information on how to properly utilize this in the documentation. This needs to be addressed for people utilizing ldap sync. Currently I am having to adjust the filter each time I want to bring in new users and usually that requires clean-up after the fact most times unfortunately.

**Comment by davtay** [comment]
Just to add to this, the LDAP Sync to location works.  In the drop down, the location that is selected syncs ALL objects based on your settings.  To remedy this, all locations will want to be created with their distinguishedName set.  Then on the next sync, the appropriate object will update their locations.
