### ISSUE TITLE
User Asset Acceptance

### ISSUE THREAD

**Issue by maxidonati** [snipe/snipe-it#481]
first sorry for my english...

i should be good permit user to accept or confirm that an asset is really in their hand.

What i mean is:

Asset Assignment Flow

as Admin i create an Asset
As Admin i assign an asset to User X
User X confirm that Asset is really in his hands

Asset Unassignment Flow

User Ask to Check In The Asset
When i receive the asset i confirm that asset is really in my hand

maybe should seem stupid but that way i have a double check of asset assigment and User can confirm that all is ok

Max
##

**Comment by kobie-chasehansen** [comment]
Maybe as a first step for this feature the user is just emailed when a piece of equipment is assigned to them? giving some kind of option to prevent the user notification would be ideal for bulk imports of data as well.

for my use case we were having users sign a piece of paper when a projector is checked out to them. I could see getting rid of that step if the user is at least notified when they are assigned an asset.

**Comment by snipe** [comment]
Asset acceptance is up on develop, but I haven't yet built in asset checkin confirmation.
