### ISSUE TITLE
Feature Request: Disabling of quantity level alert

### ISSUE THREAD

**Issue by MarkusGehrig** [snipe/snipe-it#4814]
#### Expected Behavior (or desired behavior if a feature request)

We have some items in storage, which are not longer produce from the manufacture (such as old harddrives) and we don't like to buy new items of this version. (as an example Magic Mouse 1 and 2) So we don't want a quantity alert from this kind of items. 

Is it possible to add a checkbox to the item which disabling the alert or if the min. amount is -1 ? 

#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
upgrade
- Version of Snipe-IT you're running
v4.1.9 build 3128 (ge5a7e66)

- Version of PHP you're running
7.0.22-0ubuntu0.16.04.1

- Version of MySQL/MariaDB you're running
--

- What OS and web server you're running Snipe-IT on
ubuntu 16.04.1

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual installation

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
--

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
All Sites

- If a stacktrace is provided in the error, include that too.
--

- Any errors that appear in your browser's error console.
--

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
--

- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
--

- Include what you've done so far in the installation, and if you got any error messages along the way.
--

- Indicate whether or not you've manually edited any data directly in the database
--

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I think probably a better way to handle this (versus magic numbers) is to add a flag on the accessories to include or exempt them from alerts.
