### ISSUE TITLE
"All Assets" page is blank  - " No matching records found "

### ISSUE THREAD

**Issue by talenmhm** [snipe/snipe-it#4822]
Yesterday I imported assets to SnipeIT and it was working and showing all assets in the asset page
then today showing in All Assets page s blank:
" No matching records found "
Even though, dashboard is showing the total asset is 10,

#### Expected Behavior (or desired behavior if a feature request)

All Assets" page list all my assets 
-----

#### Actual Behavior

"All Assets" page is blank

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode  no
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)  yes

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running: latest V4
- Version of PHP you're running latest php 7
- Version of MySQL/MariaDB you're running: Mysql
- What OS and web server you're running Snipe-IT on  Ubuntu 16.4
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) GIT 
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. 
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.


- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by snazy2000** [comment]
I’ve seen this before I believe, try hitting the reload button on the asset table on the right

I saw this when was on page 2 and deleted a record and then only 1 page was left but the call was still offsetting so was trying to load page 2 :( 

Think I increased the how many on a page account and this then reset it.

**Comment by DoubleZed** [comment]
I have been experiencing the same issue and also our staff has had it on different workstations and the temporary workaround typically has been to clear the browser cookies. Then it works again for some time.
