### ISSUE TITLE
Apache2 home page / Register The Auto Loader

### ISSUE THREAD

**Issue by aRiflip** [snipe/snipe-it#4824]
#### Expected Behavior (or desired behavior if a feature request)

WebGUI Installation

-----

#### Actual Behavior

If I input the URL I get the apache2 page
If I input the IP address I get the "Register The Auto Loader"

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode (I think)
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - Fresh install
- Version of Snipe-IT you're running - Not sure
- Version of PHP you're running - Not sure
- Version of MySQL/MariaDB you're running - Not sure
- What OS and web server you're running Snipe-IT on - Ubuntu Desktop 16.04 & Ubuntu Server 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual

I have had snipeit up and running before following these tutorials

https://www.vultr.com/docs/how-to-install-snipe-it-on-ubuntu-16-10

https://www.youtube.com/watch?v=SvcYwU_1kmc

But now both tutorials bring up the same issues explained above.

**Comment by aRiflip** [comment]
Think I may have solved it when following this tutorial 

https://www.ceos3c.com/2017/11/30/how-to-install-snipeit-on-ubuntu-16-04-on-aws-free-tier/

When I done the key:generate there was some text explaining 'en-GB' in the .env is not a value in the laravel framework. Reverting this back to 'UTC' appears to have solved it.

You may want to add that in your issues.

**Comment by snipe** [comment]
@aRiflip without a specific error message, I'm not sure what we'd add. Did you maybe set the timezone wrong, using the locale (language) value instead of a valid timezone?

**Comment by aRiflip** [comment]
@snipe Sorry, 

"PHP Notice: date_default_timezone_set(): Timezone ID 'en-GB is invalid in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php on line 49"

**Comment by snipe** [comment]
Yeah, `en-GB` isn't a valid timezone. That's a valid locale, but not a valid timezone. See the [documentation](https://snipe-it.readme.io/docs/configuration#section-required-basic-app-settings) for more info.

**Comment by aRiflip** [comment]
Aaaand now I look like a fool for not reading correctly :) Thanks for clearing that up

**Comment by snipe** [comment]
Happens to the best of us :)
