### ISSUE TITLE
Why is the manufacturer field on asset models mandatory?

### ISSUE THREAD

**Issue by vcordes79** [snipe/snipe-it#4827]
Hello,

I don't quite understand why the manufacturer is part of the asset model, I would prefer it with the asset data. I wanted to create a model for laptops and use it for different manufacturers. If I understand it correctly I need to define a fieldset for Laptops and than a model for each manufacturer. So if there are 10 manufacturers I end up with 10 models.

I imagine there are companies that only buy laptops of a single brand, so the existing structure makes sense. I would prefer if the manufacturer field in the model could be left empty and a manufacturer field would be added to the asset to override the value supplied by the model. Of course I could add the manufacturer field to the fieldset and create a manufacturer called "various" but that does not feel right.

Thanks,
Volker

**Comment by snipe** [comment]
@vcordes79 I don't understand what you mean. Manufacturer is a mandatory field on asset models, but manufacturers can be used across as many models as you like. Asset models tend to be be things like `MacBook Pro 13`, which would only be made by Apple. Or `Inspiron` which would be made by Dell. The asset model is meant to be specific.

**Comment by vcordes79** [comment]
That's my point I don't need to distinguish between Apple and DELL, I'd only like one model for laptop. But there are rare cases when I need to supply the laptop manufacturer - I would like to be able to do that on asset level not the model.

**Comment by rWaddles** [comment]
Trying to get my head round what you mean @vcordes79 , it sounds you simply want a 'Misc' laptop no matter the brand?

**Comment by snipe** [comment]
@rWaddles - same

@vcordes79 If I understand your use-case correctly, you'd need to set a manufacturer of "Misc" and then set up your laptop model as "Laptop 13-inch" and then your exceptional "Dell Laptop 13-inch" for the few times that you need to track the manufacturer. Modifying the models to not requirement a manufacturer is not something we have on the roadmap at this time.
