### ISSUE TITLE
MERGE REQUEST: Python API Interface

### ISSUE THREAD

**Issue by jbloomer** [snipe/snipe-it#4828]
I did not see anywhere in the project to include a Python Module to interface with the API. As such I created a raw Repo to build in. I would like to have it merged/included into your current repo. 

My Project is in development and currently only supports Hardware (Assets) and Company Support. I am working on adding to this module to try to fully support the API as is. 

You can find my repo at https://github.com/jbloomer/SnipeIT-PythonAPI

**Comment by snipe** [comment]
If it's just a library that Python users can use to interface with the Snipe-IT JSON REST API, it wouldn't be merged. It doesn't make sense to merge a project like that - however once you're further along, we'd be happy to link to it to help out folks who are writing Python scripts to interface with Snipe-IT.

**Comment by jbloomer** [comment]
OK Awesome. Yea I think there is a demand for it.

**Comment by jbloomer** [comment]
Currently now have support for 

Assets
Companies
Locations
Accessories

**Comment by jbloomer** [comment]
Update

Python package supports 53% of the REST API. Features covered are 

Hardware
Companies
Locations
Accessories
Consumables
Components
Users

**Comment by jbloomer** [comment]
## API Features
  - [X] Hardware
  - [X] Companies
  - [X] Locations
  - [X] Accessories
  - [X] Consumables
  - [X] Components
  - [X] Users
  - [X] Status Labels
  - [X] Models
  - [ ] Licenses
  - [ ] Categories
  - [ ] Manufacturers
  - [ ] Custom Fieldsets

  ![Completed](http://progressed.io/bar/69?title=completed)
