### ISSUE TITLE
API: Custom fields

### ISSUE THREAD

**Issue by vcordes79** [snipe/snipe-it#4829]
Is there an api for updating custom fields? Can I post the fields data with the fieldset or how do I update fields?

Thanks,
Volker

**Comment by therealjoshuad** [comment]
Yup, check out #4593 it has some of the resources you probably need, let me know if you still need help after that thread.

**Comment by vcordes79** [comment]
Sorry, seems I wasn't quite clear. I want to create custom fields and assign them to a fieldset via api. #4593 is about assigning values for custom fields to assets.

**Comment by snipe** [comment]
That's not currently supported via the API, but it's on the roadmap.
