### ISSUE TITLE
issue in upgrading from 3.6.6 to 4..1.9

### ISSUE THREAD

**Issue by umerafridi** [snipe/snipe-it#4830]
#### Expected Behavior (or desired behavior if a feature request)

I try to upgrade from 3.6.6 to version 4 through git i follow the steps mention in up gradation documents 
after run the command php upgrade.php than following error shown on screen

Step 6: Migrating database:
--------------------------------------------------------

PHP Warning:  require(/var/www/html/snipe-it-4.6/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/snipe-it-4.6/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/html/snipe-it-4.6/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipe-it-4.6/bootstrap/autoload.php on line 17
-- 

--------------------------------------------------------
Step 7: Checking for OAuth keys:
--------------------------------------------------------

- No OAuth keys detected. Running passport install now.

PHP Warning:  require(/var/www/html/snipe-it-4.6/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/snipe-it-4.6/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/html/snipe-it-4.6/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipe-it-4.6/bootstrap/autoload.php on line 17
--------------------------------------------------------
Step 8: Caching routes and config:
--------------------------------------------------------

PHP Warning:  require(/var/www/html/snipe-it-4.6/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/snipe-it-4.6/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/html/snipe-it-4.6/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipe-it-4.6/bootstrap/autoload.php on line 17
PHP Warning:  require(/var/www/html/snipe-it-4.6/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/snipe-it-4.6/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/html/snipe-it-4.6/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipe-it-4.6/bootstrap/autoload.php on line 17
-- -- 
--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

PHP Warning:  require(/var/www/html/snipe-it-4.6/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/snipe-it-4.6/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/html/snipe-it-4.6/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipe-it-4.6/bootstrap/autoload.php on line 17
-- 

--------------------------------------------------------
FINISHED! Clear your browser cookies and re-login to use :
your upgraded Snipe-IT.

(what you expect to happen goes here)

-----
when i try to access from browser blank page display i also set the storage folder permission 
#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [  ] I have enabled debug mode 
      Yes i have enabled
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
   I have read Common Issues

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
 Upgrade
- Version of Snipe-IT you're running
3.6.6
- Version of PHP you're running
PHP 5.6.32
- Version of MySQL/MariaDB you're running
Mysql 5.5
- What OS and web server you're running Snipe-IT on
CentOS Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual Installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
YES Debug mode on
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
no error blank page error 500 
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Please see the [common issues](https://snipe-it.readme.io/docs/common-issues#section-warning-requirebootstrapvendorautoloadphp-failed-to-open-stream-no-such-file-or-directory). It looks like you didn't run composer install, or an error was encountered when installing the dependencies.

**Comment by snipe** [comment]
Additionally, you shouldn't use upgrade.php to upgrade from v3.x to v4.x, you should use the [upgrade guide](https://snipe-it.readme.io/docs/upgrading-to-v4).

**Comment by umerafridi** [comment]
I also check from common issue and follow the upgrade guide also but i still face the same issue i install composer properly when i run upgrade.php script using non root user its prompt the following error 
PHP Warning:  require(/var/www/html/snipe-it-4/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/snipe-it-4/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/html/snipe-it-4/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipe-it-4/bootstrap/autoload.php on line 17
-- 

--------------------------------------------------------
Step 7: Checking for OAuth keys:
--------------------------------------------------------

- No OAuth keys detected. Running passport install now.

PHP Warning:  require(/var/www/html/snipe-it-4/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/snipe-it-4/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/html/snipe-it-4/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipe-it-4/bootstrap/autoload.php on line 17
--------------------------------------------------------
Step 8: Caching routes and config:
--------------------------------------------------------

PHP Warning:  require(/var/www/html/snipe-it-4/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/snipe-it-4/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/html/snipe-it-4/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipe-it-4/bootstrap/autoload.php on line 17
PHP Warning:  require(/var/www/html/snipe-it-4/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/snipe-it-4/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/html/snipe-it-4/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipe-it-4/bootstrap/autoload.php on line 17
-- -- 
--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

PHP Warning:  require(/var/www/html/snipe-it-4/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/snipe-it-4/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/html/snipe-it-4/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipe-it-4/bootstrap/autoload.php on line 17
--

**Comment by snipe** [comment]
Composer did not install dependencies properly. When you run `php composer install`, what does it output?

**Comment by umerafridi** [comment]
output is this
Could not open input file: composer
but i follow these steps to install composer
cd <install-dir>
curl -sS https://getcomposer.org/installer | php
php composer.phar install --no-dev --prefer-source
