### ISSUE TITLE
upgrade.php doesn't check whether backup was successful

### ISSUE THREAD

**Issue by Nothing4You** [snipe/snipe-it#4831]
#### Expected Behavior (or desired behavior if a feature request)

`upgrade.php` should verify that the backup was successfully created before continuing with the next step.

-----

#### Actual Behavior

`$ php upgrade.php`
```
Welcome to the Snipe-IT upgrader.

Please note that this script will not download the latest Snipe-IT
files for you unless you have git installed.
It simply runs the standard composer and artisan
commands needed to finalize the upgrade after.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! If you have any encrypted custom fields, BE SURE TO run the recrypter if upgrading from v3 to v4.
!! See the Snipe-IT documentation for help:
!! https://snipe-it.readme.io/docs/upgrading-to-v4
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--------------------------------------------------------
STEP 1: Backing up database:
--------------------------------------------------------

-- Starting backup...
Dumping database test_snipeit...
Determining files to backup...
Backup failed because ZipArchive::close(): Can't open file: Permission denied.
Backup completed!


--------------------------------------------------------
STEP 2: Putting application into maintenance mode:
--------------------------------------------------------

-- Application is now in maintenance mode.
```

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running 4.1.9
- Version of PHP you're running 7.1.7
- What OS and web server you're running Snipe-IT on - osx
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual

**Comment by snipe** [comment]
The automated backup part is just really just a convenience. All documentation tells you to do a manual backup before upgrading. (Also, the upgrade script itself is really just a convenience. We still recommend using Git methods to upgrade if you have trouble with the upgrade script. There are lots of variables it has to account for - weird permissions, etc - that we just can't figure out on every conceivable system.)

When you run `php artisan snipeit:backup` outside of upgrade.php, what does it say?

**Comment by Nothing4You** [comment]
```
$ php artisan snipeit:backup
Starting backup...
Dumping database test_snipeit...
Determining files to backup...
Backup failed because ZipArchive::close(): Can't open file: Permission denied.
Backup completed!
```

This setup isn't fully configured regarding permissions to allow creating backups since it's just for local testing, I'm not expecting it to work, it should be properly detected though.

**Comment by snipe** [comment]
That's easier said than done unfortunately, since we use a third-party library. It doesn't show an exception if it fails that way, it just outputs the error, and there could be a variety of reasons why it might fail, so not an easy thing to grep for either. The "Backup completed!" bit is from the backup library, not from us.

```
echo "--------------------------------------------------------\n";
echo "STEP 1: Backing up database: \n";
echo "--------------------------------------------------------\n\n";
$backup = shell_exec('php artisan snipeit:backup');
echo '-- '.$backup."\n\n";
```
