### ISSUE TITLE
Stuck in Debugging?

### ISSUE THREAD

**Issue by rWaddles** [snipe/snipe-it#4832]
#### Expected Behavior (or desired behavior if a feature request)

No banner saying I am in debugging in production environment 

-----

#### Actual Behavior

Currently have the normal banner when in debugging:

WARNING!: This application is running in production mode with debugging enabled. This can expose sensitive data if your application is accessible to the outside world. Disable debug mode by setting the APP_DEBUG value in your .env file to false.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? No
- Version of Snipe-IT you're running 4.1.10
- Version of PHP you're running  7.0
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on Debian 4.9.30
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error all pages
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
... and... is debug set to false in your `.env`? A little more info here would be helpful.

**Comment by rWaddles** [comment]
Well that is embarrassing, was set to false but it was cache related. Home time needed!
Thanks Snipe!
