### ISSUE TITLE
Preauth to enable a trusted third party

### ISSUE THREAD

**Issue by fastfire** [snipe/snipe-it#4833]
Hi Snipe-IT team,

it is possible to add a preauth feature to do an auto login in Snipe-IT from a user already logged in an external applications? An example of this feature is preauth login of Zimbra (https://wiki.zimbra.com/wiki/Preauth).

Thank you!

**Comment by snipe** [comment]
Sounds like you're looking for SAML/OAuth. We do not currently support that at this time, unfortunately.
