### ISSUE TITLE
Modification: can mandatory and optional fields on asset forms be modified?

### ISSUE THREAD

**Issue by chris-neu** [snipe/snipe-it#4835]
I would like to customize our asset manager to make it relevant to our business needs as much as possible. For that, I am trying to figure out if the mandatory and optional fields on asset forms can be modified. For instance, I would like to -
1. Change the names of some field labels
2. Change the order of the fields in which they are presented on the form
3. Get rid of some fields completely, such as Supplier, Order Number, Purchase Cost, and Warranty.

I also would like to change what Model drop-down list is showing: I want the Model lists to show models only, the way they were entered into the model field, without any extra information being added, such as asset type or brand, and the list should be sorted.

**Comment by snipe** [comment]
That's not currently possible at this time.
