### ISSUE TITLE
Change time from default UTC to Australia/Brisbane

### ISSUE THREAD

**Issue by Mynty100** [snipe/snipe-it#4838]
#### Expected Behavior (or desired behavior if a feature request)

In app/.env change UTC to Australia/Brisbane. Then when checking an asset in or out etc the time should be set to my local time.

-----

#### Actual Behavior

Changes to the /app/.env from UTC to Australia/Brisbane made no change. Time still seems to be UTC.
I have edited php.ini and mysql as well from default to Australia/Brisbane

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? = Clean with minor changed to search function
- Version of Snipe-IT you're running = 4.1.5
- Version of PHP you're running = 7.0
- Version of MySQL/MariaDB you're running = MySQL 5.4
- What OS and web server you're running Snipe-IT on = Linux Mint
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) = AMPPS
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error = NO
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error = Just when looking at the date and time of the check in or out is UTC
- If a stacktrace is provided in the error, include that too. = N/A
- Any errors that appear in your browser's error console. = N/A

**Comment by EarlRamirez** [comment]
@Mynty100, you will need to clear the config that is currently cached, this should work. **php artisan config:clear** and try again.

**Comment by Mynty100** [comment]
This worked cheers.

**Comment by snipe** [comment]
Awesome! Glad to hear you're all sorted. In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
