### ISSUE TITLE
Whoops, look like something went wrong error after doing a docker upgrade to v4

### ISSUE THREAD

**Issue by ado120** [snipe/snipe-it#4839]
#### Expected Behavior (or desired behavior if a feature request)

Docker pull of the latest snipeit container should have run without any issues

#### Actual Behavior

I am getting a "Whoops, looks like something went wrong" error
https://imgur.com/a/AMJEU

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running? latest
- Version of PHP you're running? php v.7.1
- Version of MySQL/MariaDB you're running? mysql  Ver 15.1 Distrib 5.5.47-MariaDB, for Linux (x86_64) using readline 5.1
- What OS and web server you're running Snipe-IT on? CentOS 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)? Docker rm snipeit, docker pull snipe/snipe-it, docker run
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error? No errors, same page still
- Include any additional information you can find in `app/storage/logs` and your webserver's logs. 
Nothing in storage/logs
- Include what you've done so far in the installation, and if you got any error messages along the way.
I had to upgrade from PHP 5.4 to PHP 7.1, could this be why?
- Indicate whether or not you've manually edited any data directly in the database? No

https://snipe-it.readme.io/docs/getting-help

**Comment by ado120** [comment]
Also when deleting the docker container and doing a pull snipeit/snipe-it:v3.6.5 I am getting the same error unfortunately :(

**Comment by snipe** [comment]
If you're seeing a whoops error, there has to be something in your error logs, OR the system can't writing to the error logs directory, which is why you're seeing the whoops.

**Comment by ado120** [comment]
My mistake.. clearing cache and cookies solved the issue :)

**Comment by snipe** [comment]
Awesome! Glad to hear you're all sorted. In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
