### ISSUE TITLE
FatalErrorException when trying to view newly created assets

### ISSUE THREAD

**Issue by Tsuroerusu** [snipe/snipe-it#484]
Earlier today I added several laptops into Snipe-IT, however when I wanted to view them just now, I get this error message:

![error](https://cloud.githubusercontent.com/assets/9139161/5993900/e6e57438-aa5f-11e4-8176-bce3e19dd224.png)

When I click the edit-button for the same asset, it displays as expected:

![edit](https://cloud.githubusercontent.com/assets/9139161/5993901/049ad3b0-aa60-11e4-8e03-a351e792e927.png)

I updated to version 1.2.2 the other day, I do not get this problem when viewing assets created under version 1.1.

**Comment by snipe** [comment]
Were the new laptops checked out to anyone yet?

**Comment by Tsuroerusu** [comment]
@snipe Nope, they were not. They were created with the status "Pending". I just tried changing it to "Ready to Deploy", but the problem remains. I have several dousin other laptops in the system, which are also marked "Ready to Deploy", but none of them results in this issue.

**Comment by snipe** [comment]
That's very helpful, thank you. We've been trying to track down this bug for a bit, so the additional info is helpful. It's definitely something that was introduced in 1.2.2. I'll try to figure it out as soon as possible.

**Comment by Tsuroerusu** [comment]
@snipe No problem, if you need further information, or would like me to test something, just let me know, and I will be happy to assist further.

**Comment by snipe** [comment]
Thank you :) Does this happen on licenses too? Or just physical assets?

**Comment by Tsuroerusu** [comment]
@snipe I normally do not use Licenses, however I just tried creating one, and the problem does NOT appear to affect licenses, as I am able to view the one I just created without any issue.

**Comment by snipe** [comment]
I just pushed out a small tweak to develop - can you pull that down and see if it works?

**Comment by Tsuroerusu** [comment]
@snipe I just tested your fix, and it does indeed resolve the issue. :-)

I also experimented a little bit, and I think I can pin-point the issue even further.
Try to compare the version of view.blade.php from v1.2.2 and pre-fix develop. Even between those there is a difference.

v1.2.2 has this on line 202:
@if (isset($log->checkedout_to))

pre-fix develop has this on line 203:
@if ((isset($log->checkedout_to)) && ($log->checkedout_to!=0))
(Which is the line your fix alters)

Just to see, I tried putting the pre-fix line into my view.blade.php file, and then the problem also went away! So the problem seems to be located in this:

@if (isset($log->checkedout_to))

**Comment by snipe** [comment]
Yeah, that much I had figured out :) The question is why it broke though. The fix I put in is basically a front-end fix, but some data is getting mangled somewhere on the save, I think.

**Comment by Tsuroerusu** [comment]
@snipe Fair enough. :) Yeah, that could indicate a deeper problem. Any idea whether this issue was in v1.2 also, or is this just v1.2.2 ?

**Comment by snipe** [comment]
I suspect 1.2.1, since that's when the reports started to come in.

**Comment by Tsuroerusu** [comment]
@snipe I just noticed something very odd. On the newly created assets, which exhibited the problem we talked about yesterday, take a look at the log after just creating it:

![log](https://cloud.githubusercontent.com/assets/9139161/6001357/2ef878b8-aae9-11e4-9641-400efde8d583.png)

When I created, I left the status at "Pending", and I did not select any user, and yet it says it has been checked out. Also, when I then change it to "Ready to Deploy", it still appears as "Pending", but when I go to edit it, the status is set to "Ready to Deploy".

Is it me or is something seriously out of wack?

**Comment by jotafurtado** [comment]
Hi @snipe , same problem here. The error does not happen if in the creation form of the asset you set the status " ready to implement " and checkout to a user.

**Comment by snipe** [comment]
@Tsuroerusu - Yeah, I think that's actually at the heart of it. I think an erroneous record is being created, which is why it was puking on `fulsome()`, since there was no actual person assigned.

**Comment by Tsuroerusu** [comment]
@snipe I see that you just released v1.2.3, did you manage to fully hunt down this problem?

**Comment by snipe** [comment]
Not all the way, but it shouldn't throw errors anymore. Will have a more complete fix in 1.2.4
