### ISSUE TITLE
API:Hardware:POST Cannot create asset if fieldset requires any custom fields

### ISSUE THREAD

**Issue by jbloomer** [snipe/snipe-it#4848]
#### Expected Behavior (or desired behavior if a feature request)
Send POST with JSON body and asset is created

-----

#### Actual Behavior
If model_id matches a fieldset that requires certain fields, even if they are provided, asset is not created even though POST replies with success 

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Tried with Fresh and existing
- Version of Snipe-IT you're running 4.1.9
- Version of PHP you're running 5.6
- Version of MySQL/MariaDB you're running Amazon Aurora (MySQL 5.9 compatible)
- What OS and web server you're running Snipe-IT on CentOS 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Git install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Can you give me an example JSON POST payload please?

**Comment by snipe** [comment]
I'm unable to reproduce this with the latest from dev/master.

<img width="749" alt="screen shot 2018-01-17 at 1 46 06 pm" src="https://user-images.githubusercontent.com/197404/35068777-f445b058-fb8c-11e7-88c9-a2a1d6242cc8.png">

```
{
    "status": "success",
    "messages": "Asset created successfully. :)",
    "payload": {
        "model_id": "1",
        "name": null,
        "serial": null,
        "company_id": "",
        "order_number": null,
        "notes": null,
        "asset_tag": "45679450879405807",
        "user_id": 2,
        "archived": "0",
        "physical": "1",
        "depreciate": "0",
        "status_id": "1",
        "warranty_months": null,
        "purchase_cost": null,
        "purchase_date": null,
        "assigned_to": null,
        "supplier_id": null,
        "requestable": 0,
        "rtd_location_id": null,
        "_snipeit_profit_focused_tertiary_matrix_1": "Custom field updated via API",
        "_snipeit_synergistic_encompassing_graphicinterface_3": "",
        "_snipeit_integrated_scalable_circuit_4": "",
        "updated_at": "2018-01-17 13:45:35",
        "created_at": "2018-01-17 13:45:35",
        "id": 1376,
        "model": {
            "id": 1,
            "name": "Macbook Pro 13\"",
            "model_number": "4532276816715",
            "manufacturer_id": 1,
            "category_id": 1,
            "created_at": "2017-12-20 13:35:46",
            "updated_at": "2018-01-16 08:23:58",
            "depreciation_id": 1,
            "eol": 36,
            "image": "mbp.jpg",
            "deprecated_mac_address": 0,
            "fieldset_id": 1,
            "notes": "Created by demo seeder",
            "requestable": 0
        }
    }
}
```

**Comment by jbloomer** [comment]
Note if you have a custom fieldset assigned to the model_id and all fields are optional, the asset will be added

**Comment by snipe** [comment]
I still can't reproduce this.

<img width="1372" alt="screen shot 2018-01-17 at 1 53 28 pm" src="https://user-images.githubusercontent.com/197404/35069041-d186c696-fb8d-11e7-8b39-3643b1404012.png">

<img width="672" alt="screen shot 2018-01-17 at 1 53 53 pm" src="https://user-images.githubusercontent.com/197404/35069068-e78e6d36-fb8d-11e7-9440-a35d987eea60.png">

(`_snipeit_progressive_high_level_model_2` is required)

```
{
    "status": "success",
    "messages": "Asset created successfully. :)",
    "payload": {
        "model_id": "1",
        "name": null,
        "serial": null,
        "company_id": "",
        "order_number": null,
        "notes": null,
        "asset_tag": "45679450879405809",
        "user_id": 2,
        "archived": "0",
        "physical": "1",
        "depreciate": "0",
        "status_id": "1",
        "warranty_months": null,
        "purchase_cost": null,
        "purchase_date": null,
        "assigned_to": null,
        "supplier_id": null,
        "requestable": 0,
        "rtd_location_id": null,
        "_snipeit_profit_focused_tertiary_matrix_1": "Custom field updated via API",
        "_snipeit_progressive_high_level_model_2": "Also updated via API",
        "_snipeit_synergistic_encompassing_graphicinterface_3": "",
        "_snipeit_integrated_scalable_circuit_4": "",
        "updated_at": "2018-01-17 13:53:05",
        "created_at": "2018-01-17 13:53:05",
        "id": 1377,
        "model": {
            "id": 1,
            "name": "Macbook Pro 13\"",
            "model_number": "4532276816715",
            "manufacturer_id": 1,
            "category_id": 1,
            "created_at": "2017-12-20 13:35:46",
            "updated_at": "2018-01-16 08:23:58",
            "depreciation_id": 1,
            "eol": 36,
            "image": "mbp.jpg",
            "deprecated_mac_address": 0,
            "fieldset_id": 1,
            "notes": "Created by demo seeder",
            "requestable": 0
        }
    }
}
```

**Comment by jbloomer** [comment]
If you check to see if the Asset has been created in the Web UI, Is it there? I get a success message too but the Asset is not found in the UI

**Comment by jbloomer** [comment]
Here is a detailed break down of our installation

Models
![image](https://user-images.githubusercontent.com/6685035/35104396-b597e0d8-fc36-11e7-8523-d90293dcdbab.png)

Fieldset
![image](https://user-images.githubusercontent.com/6685035/35104456-e234a194-fc36-11e7-9ef6-b0c392ed0198.png)

Asset Inventory before API Call
![image](https://user-images.githubusercontent.com/6685035/35104495-074158e2-fc37-11e7-8e3b-a9118efc1902.png)

POSTMAN POST Request Body
{"asset_tag":"thisisunique2","status_id":1,"model_id": 5, "_snipeit_application_team_2":"Test Team"}

API Reponse
{
    "status": "success",
    "messages": "Asset created successfully. :)",
    "payload": {
        "model_id": 5,
        "name": null,
        "serial": null,
        "company_id": "",
        "order_number": null,
        "notes": null,
        "asset_tag": "thisisunique2",
        "user_id": 2346,
        "archived": "0",
        "physical": "1",
        "depreciate": "0",
        "status_id": 1,
        "warranty_months": null,
        "purchase_cost": null,
        "purchase_date": null,
        "assigned_to": null,
        "supplier_id": null,
        "requestable": 0,
        "rtd_location_id": null,
        "_snipeit_yong_field_name_14": "",
        "_snipeit_application_team_2": "Test Team",
        "updated_at": "2018-01-18 15:09:10",
        "created_at": "2018-01-18 15:09:10",
        "id": 2655,
        "model": {
            "id": 5,
            "name": "YongTest",
            "model_number": "1",
            "manufacturer_id": 1,
            "category_id": 7,
            "created_at": "2018-01-05 19:53:57",
            "updated_at": "2018-01-08 17:02:24",
            "depreciation_id": null,
            "eol": 0,
            "image": null,
            "deprecated_mac_address": 0,
            "fieldset_id": 6,
            "notes": "yong",
            "requestable": 0
        }
    }
}

Asset in UI after API Call
![image](https://user-images.githubusercontent.com/6685035/35104779-e03afe32-fc37-11e7-908a-b4e94a243325.png)

Ironically It worked for me. 

If I update the Fieldset to have only a REQUIRED field and re-run the call
![image](https://user-images.githubusercontent.com/6685035/35104829-0a1a28d6-fc38-11e7-9cdb-519c9fbed4b3.png)

It still worked. 

Guess I was mistaken in this request. Please close this out as a false report.
