### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found

### ISSUE THREAD

**Issue by ambarishrh** [snipe/snipe-it#485]
I am getting an error on my installation, but couldn't figure out how to fix it.

[root@snipeit snipeit]# php artisan db:seed

[Illuminate\Database\QueryException]

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit

_www.assets' doesn't exist (SQL: truncate assets)

db:seed [--class[="..."]] [--database[="..."]]

**Comment by snipe** [comment]
Looks like your DB configuration is messed up. Can you paste the part in your `database.php` without the password visible? There shouldn't be any tables called snipeit - a database perhaps, but not a table.

Also would probably be helpful if you told me what kind of database you're using, and the other info here:
http://docs.snipeitapp.com/installation/getting_help.html

**Comment by snipe** [comment]
Scratch that last message. The line breaks confused me and I misread. It looks like it's not seeing your `database.php` file. Can you make sure your `database.php` file lives in `app/config/production`?

**Comment by ambarishrh** [comment]
I fixed that manually, but will try another installation and see if that
works.

Thanks!

On Wed, Feb 18, 2015 at 1:47 AM, snipe <notifications@github.com> wrote:

> Scratch that last message. The line breaks confused me and I misread. It
> looks like it's not seeing your database.php file. Can you make sure your
> database.php file lives in app/config/production?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snipe/snipe-it/issues/485#issuecomment-74761191>.
>



-- 
Ambarish.....
http://ambarishrh.com/

**Comment by scottalanmiller** [comment]
Just need to run this command to fix the above error:

php artisan app:install

Instructions here:

http://mangolassi.it/topic/6967/installing-snipe-it-on-centos-7-and-mariadb

**Comment by snipe** [comment]
@scottalanmiller The Snipe-IT documentation covers running the installer pretty thoroughly already. http://docs.snipeitapp.com

**Comment by scottalanmiller** [comment]
But it was the missing step above.  The installation directions are spread over many pages making it easy to miss and this went unanswered.  Yes, it is there if you know to look into specifically the CLI Installation section.

**Comment by scottalanmiller** [comment]
Here is a user who could not get through the directions this morning.  We were making new instructions specific to the OS to ensure that it all worked as intended for him:

http://mangolassi.it/topic/6965/bloody-linux-just-install-the-program-software

**Comment by snipe** [comment]
@scottalanmiller The step above is just running the CLI installer - there is a whole page dedicated to that. http://docs.snipeitapp.com/installation/command-line.html

If our docs could use improvement, we welcome contributions, but pointing our users to your documentation will only end in tears, as we are constantly updating the app (and therefore the docs), and your version will almost certainly fall out of sync with what's current.
