### ISSUE TITLE
Import test CSV, no longer see "all assetts"

### ISSUE THREAD

**Issue by aRiflip** [snipe/snipe-it#4854]
I performed an export on one asset in my system. I then changed the text and reimported it back into snipeit. I received an error saying it worked with issues. Now I can no long see or search for assets using the asset number.

Also if I make a new assett with the assett number I put in the csv, it says its unique, but there is no way of searching for the asset.

Is it possible to go into the database backend and remove the flaky asset.

"Asset name" wouldnt appear in the import field, so I tried "item name" instead.

**Comment by aRiflip** [comment]
So instead I am trying to restore to a backed up .sql file but db:restore is not recognised.

**Comment by aRiflip** [comment]
Upon checking the dashboard it says I have 6 assets, 5 ready to deploy and 1 pending. It also shows the created/imported asset in the Recent Activity. When clicking on the "pending" asset tab, nothing appears.

**Comment by EarlRamirez** [comment]
@aRiflip can you enable debugging and paste the errors here?

**Comment by aRiflip** [comment]
@EarlRamirez before I start posting random code, is it the laravel.log you’re after?
