### ISSUE TITLE
Error in setting up Snipe-IT via Docker

### ISSUE THREAD

**Issue by itims** [snipe/snipe-it#4859]
Hi,
I'm trying to install snipe-it via Docker by using the steps provided by the following URL
https://snipe-it.readme.io/docs/docker
But, now I'm stuck with an error at the final stage.
![image](https://user-images.githubusercontent.com/23715217/35141892-92c1a304-fd22-11e7-925f-26472ba77304.png)
Please have a look at this issue. How to resolve this issue? 
-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by meyerf99** [comment]
HI @itims 

Before you create the Snipe-IT docker container pull the image.

`docker pull snipe/snipe-it`

Greetings Flavio

**Comment by itims** [comment]
Hi,
My issue has been resolved :-)
I used  **snipe/snipe-it** instead of **snipe-it** with below command.
sudo docker run -d -p 4001:80 --name="snipeit" --link snipe-mysql:mysql --env-file=my_env_file **snipe/snipe-it**
