### ISSUE TITLE
INSTALLING ON WAMP SERVER

### ISSUE THREAD

**Issue by mbsarino** [snipe/snipe-it#486]
I would like to install snipe-it on my server which runs on Windows 2008 R2 but we use WAMP as our internet server.  How would I go about doing this?

**Comment by snipe** [comment]
Please see this tutorial on setting up Laravel on WAMP. (You want to start at number 2, Composer Install)
http://www.onlinekurukshetra.com/install-laravel-in-10-steps-wamp-server-windows/
