### ISSUE TITLE
Feature Request: Customize Reports

### ISSUE THREAD

**Issue by meyerf99** [snipe/snipe-it#4860]
#### Expected Behavior (or desired behavior if a feature request)

Hi snipeit devs, 

Is it possible to create custom reports like which asset or which user has installed software xy (License)?

-----

#### Actual Behavior

At the moment i can't see this option to generate new custom reports with licenses.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by bakerbuds** [comment]
I just ran into this as well and would like to back this request! It would be very helpful to be able to export a report say "all user who have 'license' X"

I love Snipe-IT and thank you for all your hard work.

**Comment by cslucian** [comment]
This option would be great for me too.

Thank You,

**Comment by meyerf99** [comment]
@snipe Is it planned to implement this feature?

**Comment by ksimms** [comment]
A Report to see Licenses assigned to individual Users would be great.  
IE User A has license Z,Y ( Company Has X amount of Licenses)

**Comment by ziyaul121** [comment]
This option would be great for me too. could you please update how long it will take to implement this feature? Thank you Snipe for all your hard work and effort. We love Snipe IT

**Comment by SupersecretIT** [comment]
+1
