### ISSUE TITLE
Feature Request: Include Components in Asset History

### ISSUE THREAD

**Issue by MSTigers** [snipe/snipe-it#4863]
Would be great if when you check a component out/in from an asset that it shows up in the history of that asset. Additionally, this feature would require an optional "Notes" section during the checkin/out process.

**Comment by MSTigers** [comment]
**Discussion:**
We added 20 Chromebook screens to our inventory and are pulling from that count. I check a replacement part out to the Asset. Helps keep track of quantities of parts, as well as where we put them. The `/components` page looks great, though if the above feature was implemented the "Notes" section should show up there as well.

It is nice to have an overview of "OK we have these parts, here's a full list of what you have done with these parts and when you did it."  But when looking an asset, it's easy to see if it has a component linked with it by just clicking the components tab. With some investigation I can figure out the history, so this feature is 100% necessary. Depending on the situation, if someone checks in and out components frequently (I don't know why, but maybe they do) it could flood the history. 

As it stands now it gives an at-a-glance view of what is CURRENTLY there. If you want the history, you will need to review that component and check the information. If the component is no longer attached to the asset, the only 'trace' of it is in the components info page itself, as opposed to showing up in the asset information.

Just wanting to discuss IF this feature would actually be needed. If anyone else has thoughts for or against it, or other ideas, feel free to mention them.

**Comment by MSTigers** [comment]
Further Activity

**Comment by MSTigers** [comment]
Bumping as it was flagged ready for dev.

**Comment by MSTigers** [comment]
Shoo

**Comment by sinichi19** [comment]
+1 For this 
It's great if everything Check out or Check in to the asset are recorded to history
(component,licenses)

**Comment by MSTigers** [comment]
Still very interested in this. Depending on funding sources at times means I am only able to use item A at Location A. Audits may result in needing to know this type of information.

**Comment by MSTigers** [comment]
Aye sir, 'tis.
