### ISSUE TITLE
Asset Search not Displaying by location keyword

### ISSUE THREAD

**Issue by MSTigers** [snipe/snipe-it#4864]
#### Expected Behavior (or desired behavior if a feature request)

Search for Assets by name of `Location` in `/hardware`, display all assets that are currently at that location.

When an asset is checked out to a user, and when that user is assigned to a location, that asset will adopt the temporary location of the user.

Expected to see both Assets that are checked out to that user, and to see Assets that are checked out to that location.

-----

#### Actual Behavior

When searching Assets by name of `Location` in `/hardware` page, it will only display results of assets that are specifically assigned to that location.

**Screenshot from Hardware (Assets > List All)**
![location search1](https://user-images.githubusercontent.com/33290254/35173604-9c42c8b8-fd31-11e7-95b4-c885b9c89393.jpg)

_____________________________________________

**Screenshot from Location view**
![location search2](https://user-images.githubusercontent.com/33290254/35173606-a0075f9a-fd31-11e7-910a-874fe72d944c.jpg)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running
v4.1.6 build 2994 (g83c8449)
- Version of PHP you're running
7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running
5.4.29
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04.1 / Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
n/a
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
/hardware (Assets > List All)
- If a stacktrace is provided in the error, include that too.
n/a
- Any errors that appear in your browser's error console.
n/a
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Yes reproducable
- Include any additional information you can find in `app/storage/logs` and your webserver's logs.
n/a
- Include what you've done so far in the installation, and if you got any error messages along the way.
n/a
- Indicate whether or not you've manually edited any data directly in the database
No

**Comment by snipe** [comment]
I believe that was already fixed in later versions.

**Comment by MSTigers** [comment]
I reproduced on the demo as well, if that's a factor.
