### ISSUE TITLE
SORRY!

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#4865]
Hi all,

I'm really sorry for the email spam some of you got today. :( I installed a stale issue bot to try to handle older issues, and they didn't document when/how often it would run. I'm sure none of you were hoping for 800 emails from this repo on your Friday night. :(

![i-made-everything-weird](https://user-images.githubusercontent.com/197404/35180415-0e7b58a4-fd65-11e7-81f8-a8a916972817.gif)

**Comment by therealjoshuad** [comment]
https://media1.giphy.com/media/3oEjHJiBwj8GEMxDRm/giphy.gif
