### ISSUE TITLE
Improvements to Asset Maintenance

### ISSUE THREAD

**Issue by fordster78** [snipe/snipe-it#4867]
To improve the Asset Maintenance section in terms of work flow, GUI and what information you can log as part of the maintenance
This will add the feature mentioned in #1803 and possibly add any images associated with the maintenance.

**Comment by fordster78** [comment]
Generally the first thing I am thinking is resolve issue #1803. This will allow end users to create custom maintenance tags, very similar to how status labels are done.

Then Once that is done, I can possibly start changing the work flow so that it changes the status of the asset when maintenance is created and changes it back when it is completed?

@snipe any suggestions

**Comment by snipe** [comment]
The only part where it maybe gets tricky is if there is different business logic around the different maintenance types.

**Comment by fordster78** [comment]
In terms of what?
