### ISSUE TITLE
Asset History After Upgrade

### ISSUE THREAD

**Issue by vinotnj21** [snipe/snipe-it#4869]
#### Expected Behavior (or desired behavior if a feature request)

Old Asset Logs has to be displayed after upgrade

-----

#### Actual Behavior

Old Logs are not found. but in assetlogs table i can find them.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode - Yes
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running - 4.1.7
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on Windows
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual Installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error No
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error. View Assets
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. No
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by vinotnj21** [comment]
I have upgraded from Ver 3.4.0

**Comment by snipe** [comment]
Please try upgrading - I believe this issue was fixed in 4.1.10.
