### ISSUE TITLE
Issue adding a new license

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#487]
Figured screenshots can do all the talking here, lmk if more detail is needed

Release is the dev branch

![image](https://cloud.githubusercontent.com/assets/10247644/6002761/286214b6-aac4-11e4-87f2-5fdbf6caa4a2.png)

![image](https://cloud.githubusercontent.com/assets/10247644/6002766/2f79ad0e-aac4-11e4-8337-f37f4c8338c3.png)

**Comment by snipe** [comment]
This is due to MySQL strict mode being on. I've pushed out an update to `develop`.

**Comment by kobie-chasehansen** [comment]
thank you
