### ISSUE TITLE
API: Transformer issue

### ISSUE THREAD

**Issue by vcordes79** [snipe/snipe-it#4870]
Hello,

using the api, I found that all queries return objects with html-encoded entities, because the model transformers use the e helper function on strings. I don't expect this behavior in a json-response and therefore would classify this as a bug. Is there a reason for encoding the strings?

Thanks,
Volker

**Comment by therealjoshuad** [comment]
Hi @vcordes79 I get JSON back just fine, unless i’m thinking of something different?

Do you specify JSON in the header? (I’ll get to a computer in a sec to show you what I’m referring to)

**Comment by snipe** [comment]
@vcordes79 yes, we encode those entities to prevent XSS attacks. We consume the API internally, so we have to encode them on the way out.
