### ISSUE TITLE
Pdf create for all assets 

### ISSUE THREAD

**Issue by amarbhanu** [snipe/snipe-it#4873]
Snipe IT Version v4.1.4
Now window
install.sh

Please Suggest How to create a Pdf for All Assets on Snipe-IT Like CSV/xls generate  for all assets.

**Comment by snipe** [comment]
<img width="308" alt="all_assets____snipe-it_demo" src="https://user-images.githubusercontent.com/197404/35333800-f3a0ea9a-00c4-11e8-8a52-1184af2d4b32.png">

If you need the full listing of assets, not just what's visible, you should convert your exported CSV to a PDF using whatever software your desktop operating system supports for that.

**Comment by amarbhanu** [comment]
We need to create pdf with all asset rows

**Comment by snipe** [comment]
@amarbhanu See above.
