### ISSUE TITLE
No asset history / bulk editing problem / php 7.2 problem

### ISSUE THREAD

**Issue by mandelbrotmedia** [snipe/snipe-it#4874]
#### Expected Behavior (or desired behavior if a feature request)

if i checkout or checkin different assets there should be some entrys in the asset history

-----

#### Actual Behavior

i cant see any entrys in the asset history. it is empty. but if i look in people - history there are entrys

-----

#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
fresh
- Version of Snipe-IT you're running
v4.1.9 build 3128
- Version of PHP you're running
7.2.0
- Version of MySQL/MariaDB you're running
10.1.29-MariaDB
- What OS and web server you're running Snipe-IT on
Windows Server 2012R2; xampp, apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
[2018-01-22 07:39:59] production.ERROR: InvalidArgumentException: Malformed UTF-8 characters, possibly incorrectly encoded in C:\xampp\htdocs\snipe-it\vendor\laravel\framework\src\Illuminate\Http\JsonResponse.php:71
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
assets - history
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
nope
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
got an error page with DEBUG-mode on when looking at settings- php info:

Function create_function() is deprecated (View: C:\xampp\htdocs\snipe-it\resources\views\settings\phpinfo.blade.php)
--
in e5f8753c0de2c7994dfd3f8ddd0dd894e494bcde.php (line 37)
at CompilerEngine->handleViewException(object(ErrorException), 1)in PhpEngine.php (line 44)
at PhpEngine->evaluatePath('C:\\xampp\\htdocs\\snipe-it\\storage\\framework\\views/e5f8753c0de2c7994dfd3f8ddd0dd894e494bcde.php', array('__env' =>object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => true, 'signedIn' => true, 'user' => object(User), 'snipeSettings' => object(Setting)))in CompilerEngine.php (line 59)
at CompilerEngine->get('C:\\xampp\\htdocs\\snipe-it\\resources\\views/settings/phpinfo.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => true, 'signedIn' => true, 'user' => object(User), 'snipeSettings' => object(Setting)))in View.php (line 137)

- Indicate whether or not you've manually edited any data directly in the database
no
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by mandelbrotmedia** [comment]
just found a workaround which fixes my history problem: https://github.com/snipe/snipe-it/issues/4300
But i still have the php-info error remaining

**Comment by mandelbrotmedia** [comment]
i am also getting errors when bulk editing users:
`
(1/1) ErrorExceptioncount(): Parameter must be an array or an object that implements Countable
--
in UsersController.php (line 434)
at HandleExceptions->handleError(2, 'count(): Parameter must be an array or an object that implements Countable', 'C:\\xampp\\htdocs\\snipe-it\\app\\Http\\Controllers\\UsersController.php', 434, array('request' => object(Request)))
at count(true)in UsersController.php (line 434)
at UsersController->postBulkEdit(object(Request))
at call_user_func_array(array(object(UsersController), 'postBulkEdit'), array(object(Request)))in Controller.php (line 55)
at Controller->callAction('postBulkEdit', array(object(Request)))in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(UsersController), 'postBulkEdit')in Route.php (line 203)
`

i think i make a fresh install. are there any settings in xampp / mysql / database i should care about? UTF8 german and so on?

**Comment by mandelbrotmedia** [comment]
found a solutin in https://github.com/snipe/snipe-it/issues/4844

but i also had to edit line 464 in usercontorller.php: 

        if ((!Input::has('ids')) || (count(Input::**input**('ids')) == 0)) {

**Comment by mandelbrotmedia** [comment]
Bulk editing is now working.

Bulk deleting has the same issue:

at HandleExceptions->handleError(2, 'count(): Parameter must be an array or an object that implements Countable', 'C:\\xampp\\htdocs\\snipe-it\\app\\Http\\Controllers\\UsersController.php', 540, array())

But i cant solve ist with editing Line 538 and 540 with replacing _has_ to _input_

**Comment by mandelbrotmedia** [comment]
seems like there is a problem with php 7.2

**Comment by snipe** [comment]
This is fixed on develop
