### ISSUE TITLE
Change in asset model listing

### ISSUE THREAD

**Issue by gueeme** [snipe/snipe-it#4879]
![issue](https://user-images.githubusercontent.com/19538568/35229109-b0c4c3e6-ff79-11e7-86fe-df69d161f82f.png)

#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh install
- Version of Snipe-IT you're running: V4.1.9
- Version of PHP you're running: 7.0.23
- Version of MySQL/MariaDB you're running: MySQL 5.7.19
- What OS and web server you're running Snipe-IT on: Windows Server 2012R2

How can I change the code so that only the asset model is displayed, not the manufacturer?

**Comment by snipe** [comment]
You can change it in the API/AssetModels controller, in the select list method, but you'll need to apply that patch every time you update. What's the reason you want to hide the manufacturer?

**Comment by gueeme** [comment]
It would only be to clean the selection. But I'm going to leave it the way it is.
Thanks for listening.

**Comment by snipe** [comment]
We can consider making that a setting maybe, for folks with very long asset/model/mfg names.

**Comment by snipe** [comment]
This is now on master/develop. You can find it in the Snipe-IT UI by going to Admin Settings > General.

<img width="384" alt="screen shot 2018-01-24 at 11 05 50 am" src="https://user-images.githubusercontent.com/197404/35351720-9c99fd22-00f6-11e8-8784-4cbe34923732.png">

**Comment by gueeme** [comment]
Thank you very much for the quick solution.

![issue](https://user-images.githubusercontent.com/19538568/35396845-f4d4adfa-01d4-11e8-9786-52e47c0b1658.png)
