### ISSUE TITLE
Mixed content warnings behind HAproxy

### ISSUE THREAD

**Issue by kitzy** [snipe/snipe-it#4883]
We're getting mixed content warnings running SnipeIT behind HAproxy. We have other services running behind the same HAproxy instance, so I believe the issue does not originate from the HAproxy side.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install

- Version of Snipe-IT you're running
v4.1.10

- Version of PHP you're running
7.0.22-0ubuntu0.16.04.1

- Version of MySQL/MariaDB you're running
Amazon RDS
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04 (Amazon EC2)

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Git

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Mixed content warnings in browser

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
This happens on every page

- If a stacktrace is provided in the error, include that too.
n/a

- Any errors that appear in your browser's error console.
Mixed Content: The page at 'https://snipeit.example.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://snipeit.example.com/js/plugins/select2/select2.min.css'. This request has been blocked; the content must be served over HTTPS.
(index):18 Mixed Content: The page at 'https://snipeit.example.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://snipeit.example.com/js/plugins/iCheck/all.css'. This request has been blocked; the content must be served over HTTPS.
(index):21 Mixed Content: The page at 'https://snipeit.example.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://snipeit.example.com/css/bootstrap-table.css'. This request has been blocked; the content must be served over HTTPS.
(index):23 Mixed Content: The page at 'https://snipeit.example.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://snipeit.example.com/css/dist/all.css?id=3a8aa974e7b09b52b18c'. This request has been blocked; the content must be served over HTTPS.
(index):207 Mixed Content: The page at 'https://snipeit.example.com/' was loaded over HTTPS, but requested an insecure image 'http://snipeit.example.com/uploads/logo.png'. This content should also be served over HTTPS.
(index):242 Mixed Content: The page at 'https://snipeit.example.com/' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://snipeit.example.com/hardware/bytag'. This endpoint should be made available over a secure connection.
(index):1 Mixed Content: The page at 'https://snipeit.example.com/' was loaded over HTTPS, but requested an insecure script 'http://snipeit.example.com/js/dist/all.js?id=3e9a0821dc9154d68a26'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://snipeit.example.com/' was loaded over HTTPS, but requested an insecure script 'http://snipeit.example.com/js/bootstrap-table.min.js'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://snipeit.example.com/' was loaded over HTTPS, but requested an insecure script 'http://snipeit.example.com/js/extensions/mobile/bootstrap-table-mobile.js'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://snipeit.example.com/' was loaded over HTTPS, but requested an insecure script 'http://snipeit.example.com/js/extensions/cookie/bootstrap-table-cookie.min.js?v=1'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://snipeit.example.com/' was loaded over HTTPS, but requested an insecure script 'http://snipeit.example.com/js/extensions/export/bootstrap-table-export.js?v=1'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://snipeit.example.com/' was loaded over HTTPS, but requested an insecure script 'http://snipeit.example.com/js/extensions/export/jquery.base64.js'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://snipeit.example.com/' was loaded over HTTPS, but requested an insecure script 'http://snipeit.example.com/js/FileSaver.min.js'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://snipeit.example.com/' was loaded over HTTPS, but requested an insecure script 'http://snipeit.example.com/js/xlsx.core.min.js'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://snipeit.example.com/' was loaded over HTTPS, but requested an insecure script 'http://snipeit.example.com/js/jspdf.min.js'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://snipeit.example.com/' was loaded over HTTPS, but requested an insecure script 'http://snipeit.example.com/js/jspdf.plugin.autotable.js'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://snipeit.example.com/' was loaded over HTTPS, but requested an insecure script 'http://snipeit.example.com/js/extensions/export/tableExport.min.js'. This request has been blocked; the content must be served over HTTPS.
(index):921 Uncaught ReferenceError: $ is not defined
    at (index):921
/uploads/logo.png Failed to load resource: the server responded with a status of 404 (Not Found)
(index):1471 Uncaught ReferenceError: $ is not defined
    at (index):1471
(index):1505 Uncaught ReferenceError: $ is not defined
    at (index):1505
(index):1540 Uncaught ReferenceError: $ is not defined
    at (index):1540
(index):1 Mixed Content: The page at 'https://snipeit.example.com/' was loaded over HTTPS, but requested an insecure favicon 'http://snipeit.example.com/favicon.ico'. This content should also be served over HTTPS.
(index):1 Mixed Content: The page at 'https://snipeit.example.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://snipeit.example.com/js/plugins/select2/select2.min.css'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://snipeit.example.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://snipeit.example.com/js/plugins/iCheck/all.css'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://snipeit.example.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://snipeit.example.com/css/bootstrap-table.css'. This request has been blocked; the content must be served over HTTPS.
(index):1 Mixed Content: The page at 'https://snipeit.example.com/' was loaded over HTTPS, but requested an insecure stylesheet 'http://snipeit.example.com/css/dist/all.css?id=3a8aa974e7b09b52b18c'. This request has been blocked; the content must be served over HTTPS.

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
n/a

- Include any additional information you can find in `storage/logs` and your webserver's logs.
We're seeing a lot of errors like this in laravel.log:
[2018-01-22 19:04:01] sandbox.ERROR: ErrorException: file_put_contents(/var/www/html/snipeit/bootstrap/cache/routes.php): failed to open stream: Permission denied in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:122

- Include what you've done so far in the installation, and if you got any error messages along the way.
We've followed the installation all the way through, including taking the steps listed in https://snipe-it.readme.io/docs/reverse-proxies

- Indicate whether or not you've manually edited any data directly in the database
No.

**Comment by kitzy** [comment]
We had this issue before (https://github.com/snipe/snipe-it/issues/3495), however this time the workaround I used previously doesn't work for us.

**Comment by snipe** [comment]
> We're seeing a lot of errors like this in laravel.log:
> [2018-01-22 19:04:01] sandbox.ERROR: ErrorException: file_put_contents(/var/www/html/snipeit/bootstrap/cache/routes.php): failed to open stream:  Permission denied

It looks like you have a permissions issue which could be interfering with things. Check the permissions on the `/var/www/html/snipeit/bootstrap` and `/var/www/html/snipeit/bootstrap/cache` directories and make sure they're writable.

**Comment by kitzy** [comment]
Permissions on bootstrap and cache directories:

> drwxr-xr-x  3 www-data www-data    4096 Jan 17 21:43 bootstrap
> drwxr-xr-x 2 www-data www-data 4096 Jan 18 20:12 cache

Also of note, when trying to run `php artisan config:cache`, we see the following error:

> In StreamHandler.php line 107:
> 
>   The stream or file "/var/www/html/snipeit/storage/logs/laravel.log" could n
>   ot be opened: failed to open stream: Permission denied

Looking at the permissions on laravel.log, we see this:

> -rwxr-xr-x 1 www-data www-data 552090 Jan 24 16:00 laravel.log

Those permissions all look correct to me. Am I missing something?

**Comment by snipe** [comment]
Yeah, you definitely have some permission problems somehow. Did you check for SElinux?

**Comment by kitzy** [comment]
Doesn't look like SElinux is enabled or installed:

> $ cat /etc/selinux/config
> cat: /etc/selinux/config: No such file or directory

**Comment by snipe** [comment]
I'm honestly not sure - you've clearly got a permissions problem, but I'm not sure why it would be an issue. Apache runs as www-data, you're sure?

**Comment by kitzy** [comment]
That does seem to be the case.

> $ ps aux | egrep '(apache|httpd)'
> kitzy     2405  0.0  0.0  12944   936 pts/0    S+   16:45   0:00 grep -E --color=auto (apache|httpd)
> root     29389  0.0  0.8 410644 32876 ?        Ss   16:05   0:00 /usr/sbin/apache2 -k start
> www-data 29392  0.0  0.9 420108 39932 ?        S    16:05   0:00 /usr/sbin/apache2 -k start
> www-data 29393  0.0  0.2 410676  9624 ?        S    16:05   0:00 /usr/sbin/apache2 -k start
> www-data 29394  0.0  0.2 410676  9624 ?        S    16:05   0:00 /usr/sbin/apache2 -k start
> www-data 29395  0.0  0.2 410676  9624 ?        S    16:05   0:00 /usr/sbin/apache2 -k start
> www-data 29396  0.0  0.2 410676  9624 ?        S    16:05   0:00 /usr/sbin/apache2 -k start

**Comment by kitzy** [comment]
I think at this point I'm going to nuke and pave and start fresh. I'll report back if I have the same issue.

**Comment by snipe** [comment]
Gah - that seems extreme.... Can you check out all of the steps here and just confirm? 
https://stackoverflow.com/a/35102519/200021

Sometimes some systems have a funny bit operator, etc.

**Comment by kitzy** [comment]
Tried that, and I'm still getting the same results.

**Comment by snipe** [comment]
:( I'm out of guesses then, I'm sorry

**Comment by kitzy** [comment]
No worries, I'm building a new box now. I'll report back.

**Comment by raitech-arquivei** [comment]
Hello!

@kitzy have you resolved this?

I have got the same issue while running v4.5.0 and v4.4.1 behind HA Proxy. Running RackTables within the same server without issues.

I have spent a day on this. Any light would be apreciated! :)

Thank you!

PS: If needed, I can open another issue.

**Comment by ridhamdave** [comment]
Facing this issue as well.
Running Snipe it inside a container, and exposing it using HA proxy

**Comment by aman3103** [comment]
this can be solved by updating  App\Providers\AppServiceProvider.php  public function boot()

use Illuminate\Support\Facades\URL;

if (env('APP_FORCE_TLS')) 
{
     if (strpos(env('APP_URL'), 'https') === 0) {
                URL::forceScheme('https');
} else {
                \Log::debug("'APP_FORCE_TLS' is set to true, but 'APP_URL' does not start with 'https://'. Will not force TLS on connections.");
 }
