### ISSUE TITLE
Re-work Departments/Locations

### ISSUE THREAD

**Issue by tutankh** [snipe/snipe-it#4885]
#### Expected Behavior (or desired behavior if a feature request)
Allow assets to be checked out to departments in addition to locations/users. 
Allow department nesting - similar to locations.

-We have several departments (higher ed) that are broken out across multiple locations.

**Comment by snipe** [comment]
@tutankh It's honestly unlikely that we'd implement this. The easier workaround would be to use sub-locations as departments.
