### ISSUE TITLE
Can't add "Microsoft" as manufacturer, says exists already but it doesnt

### ISSUE THREAD

**Issue by gr8scottw** [snipe/snipe-it#4886]
#### Expected Behavior (or desired behavior if a feature request)

I should be able to add the manufacturer "Microsoft" successfully in the manufacturer list.

-----

#### Actual Behavior

When adding a hardware manufacturer "Microsoft", I get an error that says "The name has already been taken".  I have no other manufacturers named Microsoft in the manufacturers list. 

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  Fresh Install
- Version of Snipe-IT you're running  3.6.6 build 1
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by therealjoshuad** [comment]
Do you have the ability to check the database table to see if there is a  record with that name?

**Comment by gr8scottw** [comment]
Do you know which table I would look at?

Thanks!

[image: adams state logo]
*Scott White*
IT Support Coordinator
Adams State University | Computing Services
208 Edgemont Boulevard | Alamosa, CO 81101 |
719-587-7873 (phone) |
                               Computing Services
<http://www.adams.edu/administration/computing/index.php> | Like Us on
Facebook <http://www.facebook.com/AdamsState>

**Comment by snipe** [comment]
`manufacturers`
