### ISSUE TITLE
can't import to asset if CVS with chinese language, always10% Complete

### ISSUE THREAD

**Issue by jintongqiao** [snipe/snipe-it#4889]
Thinks snipe-it,
I'm from china , Thinks that you give us snipe-it. now , I have build snipe site, v4.1.10, I also set the web site language to chinese . I Record some asset to the site with chinese language, then ,donwload and open the cvs is OK, and the Record in the download cvs is chinese. All these looks like OK. BUT:

1. I trid to modify one number in the CVS, for example, Serial 4403 change to 4404 ,and Preservation the cvs, import it to site, it says:'An Error has occured! Unable to encode attribute [header_row] for model [App\Models\Import] to JSON: Malformed UTF-8 characters, possibly incorrectly encoded.' (For I have set site language to chinese language,so the header_row will be chinese langusge)
2. I change the web site language to english(header_ row will be english), asset information still chinese language, donwload and open the cvs is OK,modify one number in the CVS, import it to site, no encode error,but always 10% Complete,can't continu.
3. I change the site language to english, and ecord some asset  in english, without chinese language, it works.
I'm so puzzled, if the cvs with chinese language,I can't import into site,hope you can Solve this iusse.
Think you  very much.

**Comment by jintongqiao** [comment]
Thinks snipe-it,
I'm from china , Thinks that you give us snipe-it. now , I have build snipe site, v4.1.10, I also set the language to chinese . I Record some asset to the site with chinese language, then ,donwload and open the cvs is OK, and the Record in the download cvs is chinese. All these looks like OK. BUT:

1. I trid to modify one number in the CVS, for example, Serial 4403 change to 4404 ,and Preservation the cvs, import it to site, it says:'An Error has occured! Unable to encode attribute [header_row] for model [App\Models\Import] to JSON: Malformed UTF-8 characters, possibly incorrectly encoded.'
2. I change the site language to english, donwload and open the cvs is OK,modify one number in the CVS, import it to site, the same iusse happend(some assets are still use chinese language).
3. I change the site language to english, and ecord some asset  in english, without chinese language, it works.
I'm so puzzled, if the cvs with chinese language,I can't import into site,hope you can Solve this iusse.
Think you  very much.

**Comment by snipe** [comment]
@dmeltzer - can you take a look at this when you get a chance? I think we *may* have solved this elsewhere using a manual charset and additional parameter on the return, like:

`return response()->json((new ActionlogsTransformer)->transformActionlogs($actionlogs, $total), 200, ['Content-Type' => 'application/json;charset=utf8'], JSON_UNESCAPED_UNICODE);`
