### ISSUE TITLE
Page cannot be displayed

### ISSUE THREAD

**Issue by jayp72** [snipe/snipe-it#489]
I just followed the instructions on setting up Snipe-IT on Windows with IIS and when I enter the URL http://assets.portal.local i get  a page cannot be displayed error. Need some help. Thanks

**Comment by snipe** [comment]
Please see the Getting Help documentation: http://docs.snipeitapp.com/installation/getting_help.html

I honestly can't even begin to troubleshoot this for you, as I don't know anything about how your web server is configured, whether you even have a DNS name set up, etc. Need more info.

**Comment by jayp72** [comment]
apologies for not providing all the relevant information. I have Snipe IT 1.1 installed on Windows 7 64-BIT with IIS 7. I followed the instructions as best I could, sorry, new to this so may need some guidance .I also added the file info.dll extension to the php.ini file .There are no logs in the /app/storage/logs folder, only a file called .gitkeep.

**Comment by snipe** [comment]
Did you set assets.portal.local up in your DNS anywhere?

**Comment by jayp72** [comment]
I have not set it up in DNS anywhere yet .I added an entry to the host file on the machine where Snipe IT is installed. I also tried to got the http://assets.portal.local/index.php and get the page cannot be displayed error. Possibly I don't have something setup correctly in IIS?

**Comment by snipe** [comment]
I'm not that familiar with how to set up IIS. Maybe @madd15 can help?

**Comment by madd15** [comment]
Did you point the sets the physical path to the public directory?

Have you imported the .htaccess into URLS Rewrite?

**Comment by snipe** [comment]
Hi @jayp72 - just checking in. Have you had any luck?

**Comment by joseph707** [comment]
Hi @jayp72 

If you are getting a page cannot be displayed error using IE, can you uncheck the option under Internet Options > Advanced > Browsing > uncheck the option --> show friendly HTTP error messages.  Try to take a screenshot, if possible.

Regards

Joseph

**Comment by jayp72** [comment]
Thanks for the responses, I uninstalled the program and am looking for
other options since I had a lot of issues setting it up.

**Comment by kobie-chasehansen** [comment]
Check out http://snipeitapp.com/hosting

eliminate some of the setup frustrations

**Comment by Rossberdido** [comment]
i face error now 

The website cannot display the page


  | Most likely causes:The website is under maintenance.The website has a programming error.


i check all m setting and IIS is correct, why snipeit webpage not loading? 

Please help
