### ISSUE TITLE
No search field for custom fileds

### ISSUE THREAD

**Issue by Tzvetelin88** [snipe/snipe-it#4891]
#### Expected Behavior (or desired behavior if a feature request)

to have search filed for custom fieleds, when adding new asset.

-----

#### Actual Behavior

on drop down (list) for custom filed, there is no search. After I add the asset, and go to edit, search filed is ok and available.

see here: 
![no_search](https://user-images.githubusercontent.com/36335/38449454-2edcb962-39c4-11e8-994c-867e5cd904f4.png)

after adding the asset, search is ok:
![ok_search](https://user-images.githubusercontent.com/36335/38449457-34a0cdd4-39c4-11e8-9871-68fb624cd59a.png)

What could be the problem?

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ok ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

Is this a fresh install or an upgrade? -> Fresh install
Version of Snipe-IT you're running -> v4.1.9-pre - build 3117 (master)
Version of PHP you're running -> PHP7
Version of MySQL/MariaDB you're running ->5.5.58
What OS and web server you're running Snipe-IT on ->Debian GNU/Linux 8, Apache2
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) -> Git Clone
WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error ->
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error -> No error
If a stacktrace is provided in the error, include that too.
Any errors that appear in your browser's error console.
Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. -> In the demo this is working, no issues.
Include any additional information you can find in app/storage/logs and your webserver's logs.
Include what you've done so far in the installation, and if you got any error messages along the way.
Indicate whether or not you've manually edited any data directly in the database -> No data has been edited directly in the db.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I don't understand what you're asking for here. Can you supplement with screenshots please?

**Comment by snipe** [comment]
Ah, just caught your screenshots. (I was expecting them inline.)

@uberbrady - I believe this is related to having to reinitialize select2?

**Comment by uberbrady** [comment]
Yeah, I suspect so. (Also, I inlined the screenshots to make it easier to read).
