### ISSUE TITLE
Feature Request: Bulk User Audit Report

### ISSUE THREAD

**Issue by albelem** [snipe/snipe-it#4892]
It would be very welcome to be able to extract a full report on everything each user has checked out, mainly each individual accessory.

**Comment by Jarli01** [comment]
I could really use this as well. A simple way to run multiple (or even as a single report) that List the User at the top of it, and then list what items, assets, accessories, licenses and anything else out in their name.

**Comment by Jarli01** [comment]
For example:

John Doe
     Assets
          asset-1
          asset-17
      Accessories
          accessory-5
          Keyboard
          Mouse
       Licenses
           Office 2016 Standalone

**Comment by snipe** [comment]
How is that different than the "Print all assigned" option?

**Comment by Jarli01** [comment]
@snipe this would allow an Admin to audit an entire department of people at once, rather than one by one.

**Comment by snipe** [comment]
Can you clarify what this would look like, though? If this is an excel/CSV export, how would you envision we handle breaking user sections up?

**Comment by Jarli01** [comment]
Let me draw something up and I'll post it onto gitter.

**Comment by Jarli01** [comment]
Actually, I don't think I'd even need to draw something up. The print all assigned format would work well. 

Simply add additional people after an employee record is completed and a carriage return or two to space them apart. 

Sweet and simple.

**Comment by Jarli01** [comment]
Maybe, and just maybe add a column for "Confirmed" or "Has Asset" just some simply way to check off if this were going to be going to an HR department for their records (for whatever reason)

**Comment by snipe** [comment]
That's likely to get very long with thousands of users/assets/etc, and possibly time out in the browser as it tried to render.

**Comment by Jarli01** [comment]
Wouldn't it be based on the underlying hardware available to snipe-it? I get that it can take a long time (having used crystal reports in the past i'm familiar with waiting lol).

Maybe add a declaration at the top of this "bulk audit report" not to exceed some arbitrary number without testing.

**Comment by Jarli01** [comment]
To clarify the "confirmed" or "has asset" would be for manual check off, not the system doing it. IE "Hey john do you have this laptop, yes, ok great" Checked.

**Comment by snipe** [comment]
> Wouldn't it be based on the underlying hardware available to snipe-it? 

Yes and no - trying to load a page that long can easily lock up browsers. It's just a lot of data to be stuffing into the browser window, no way around that, regardless of what hardware you're running.

> To clarify the "confirmed" or "has asset" would be for manual check off, not the system doing it.

Wouldn't it be easier to use the audit feature for that?

**Comment by Jarli01** [comment]
I personally (maybe we need a vote on it) see the Audit feature as a means of confirming what is in a closet or warehouse (that isn't checked out to someone/some place). 

The Print All Assigned (if working in a bulk approach) would allow IT or the department managers to make sure that people have what they need to do the job.

The document doesn't need to load into the browser, it could easily go into a PDF (not sure of the logistics - tell me if I'm insane). Much like the backup feature creates a zip file and be printed later. 

Or maybe even some queue'd reporting feature to make something like this happen.

**Comment by sys-adm90** [comment]
Please reopen this feature request. Would be great to generate a report for multiple user with 1 click.
