### ISSUE TITLE
Information Request: Dynamic Locations

### ISSUE THREAD

**Issue by busy86** [snipe/snipe-it#4893]
Populating locations appears to either a manual task or a CSV import (which is fine), however as an educational establishment, we have a very good database of our rooms, buildings etc. Is there any way to have a dynamic link from Snipe-it over to a view of the rooms database to keep it constantly up-to-date?

-----
New Install of 4.1.10-pre build 3185

**Comment by snipe** [comment]
> Is there any way to have a dynamic link from Snipe-it over to a view of the rooms database

I'm not sure what you mean here. Can you clarify?

**Comment by busy86** [comment]
Sure, sorry for not being clearer.

I'm looking for a way to avoid manually importing a CSV of rooms when these change (eg new buildings or rooms being re-numbered) Can we use an existing database/table of rooms and link this to Snipe-IT? Maybe present a table to the Snipe-IT database and schedule a task in mysql to import this information on a daily basis. Would this be supported?

**Comment by busy86** [comment]
Or a scheduled CSV import of rooms perhaps if we can't do the above?

**Comment by busy86** [comment]
Actually, I don't appear to be able to do a manual import of locations? I get "Could not open input file: artisan"

The GUI uploader in the GUI just sticks at 10%. Is importing locations supported?

**Comment by busy86** [comment]
@snipe is it possible to import locations?

**Comment by busy86** [comment]
Closing as the scope has changed since raising the initial issue.
