### ISSUE TITLE
Unable to access the Licenses Menu .

### ISSUE THREAD

**Issue by jnaroz** [snipe/snipe-it#4897]
#### Unable to access the Licenses Menu .

I get an index screen see screen shot below 
![image](https://user-images.githubusercontent.com/35574274/35292635-1d99e7ba-003f-11e8-864c-1198ffbde58c.png)

-----

#### Actual Behavior

i wanted to be able to enter the license codes i have 

-----

#### Please confirm you have done the following before posting your bug report:
i have not enabled them but will do that now 
- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
**Fresh install** 
- Version of Snipe-IT you're running

**Snipe-IT version | v4.1.9  build 3128 (ge5a7e66)

PHP Version | 7.2.0

Laravel Version | 5.4.35**

- Version of MySQL/MariaDB you're running

- What OS and web server you're running Snipe-IT on
**VM Windows 7 with Xampp running on Virtual Box**

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
**Manual**

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
**when i click on the License option on the top menu or the side bar . i get the same page** 
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by jnaroz** [comment]
i also wanted to add the following 👍 

Apache/2.4.29 (Win32) OpenSSL/1.1.0g PHP/7.2.0 Server at 172.16.1.220 Port 80

**Comment by snipe** [comment]
Please see the [Snipe-IT XAMPP documentation](https://snipe-it.readme.io/docs/xampp#section-remove-built-in-aliases). You have to remove the built-in alias.
