### ISSUE TITLE
Calendar view(s) for asset check out/in, due date, etc.  [$5]

### ISSUE THREAD

**Issue by peelman** [snipe/snipe-it#49]
Definitely not a priority, but some people think in terms of dates better when looking at a calendar-ish view. 
##

**Comment by HinchK** [comment]
Currently I'm playing the utility of a [heatmap](https://githb.com/kamisama/cal-heatmap) and other non-conventional cal stuff.   TBQH i'm up to my elbows in calendars and calendaring at the moment so if this is something you would like, i'd be happy to take a stab at another calendar branch.

**Comment by snipe** [comment]
@HinchK would love that :)

**Comment by joeykhan** [comment]
Google Apps calendar integration?
