### ISSUE TITLE
Cannot sort by location in Assets

### ISSUE THREAD

**Issue by kbarryde** [snipe/snipe-it#4900]
#### Expected Behavior (or desired behavior if a feature request)

Sort by Asset Location sorts by alphabetical location

-----

#### Actual Behavior

Sort by location sorts by asset tag number

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running v4.1.9 build 3128
- Version of PHP you're running 5.6.31
- Version of MySQL/MariaDB you're running 10.2.8
- What OS and web server you're running Snipe-IT on 2008 WAMP
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Assets page, all assests
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. NO
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. NO
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database NO
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Is there anything in your app error logs? If it can't be reproduced on the demo, and there are no errors, I'm not sure how to help troubleshoot. You might also try upgrading.

**Comment by Jarli01** [comment]
I can also confirm that this works as intended on v4.1.10 build 3249 (g8d3a214). 

Maybe a browser cache issue?

**Comment by kbarryde** [comment]
thanks i will look

**Comment by kbarryde** [comment]
I upgraded to 4.1.10, I also switched php to 7.1.9 from 5.6.31...it happens from all locations and different browsers not a browser cache issue...any ideas at all?

**Comment by kbarryde** [comment]
this is on wamp 64

**Comment by kbarryde** [comment]
Also noticed that even Asset tag sort is not working correctly, instead of 1,2,3,4...it is 1,10, 100, 101, 102 etc
