### ISSUE TITLE
Consumables: Alert when total is equal or less than Min. QTY

### ISSUE THREAD

**Issue by benbauters** [snipe/snipe-it#4901]
#### Expected Behavior (or desired behavior if a feature request)

Dear,

I expect to get an alert when the **remaining** of a consumable is equal or less than Min. QTY

-----

#### Actual Behavior

Now we get an alert when **Total** is equal or less than Min. QTY.
This is not logical cause Total does not decreases when you checkout a consumable. 

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running: v4.1.10 - build 3249 (master)
- Version of PHP you're running: 7.1.9
- Version of MySQL/MariaDB you're running: MySQL 5.7.19 / MariaDB 10.2.8
- What OS and web server you're running Snipe-IT on: Windows Server 2016 64bit WAMP
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Consumables
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.: YES
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database. NO

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by benbauters** [comment]
I have found this piece of code:

`$avail = $consumable->qty - $consumable->consumable_assignment_count;  //$consumable->numRemaining();`

I guess $consumable->consumable_assignment_count; is not known and therefore the QTY is the output number.
I have edited this line of code to:

`$avail = $consumable->numRemaining();`

And now all is working well as i want to, i don't know if this is the way it should be. Please check, thanks!

Ben

**Comment by Keronmat** [comment]
> I have found this piece of code:
> 
> `$avail = $consumable->qty - $consumable->consumable_assignment_count; //$consumable->numRemaining();`
> 
> I guess $consumable->consumable_assignment_count; is not known and therefore the QTY is the output number.
> I have edited this line of code to:
> 
> `$avail = $consumable->numRemaining();`
> 
> And now all is working well as i want to, i don't know if this is the way it should be. Please check, thanks!
> 
> Ben

Where do you go edit this code? I have the same problem where notifications shows up even though the stocks is above the minimum quantity.

**Comment by benbauters** [comment]
> > I have found this piece of code:
> > `$avail = $consumable->qty - $consumable->consumable_assignment_count; //$consumable->numRemaining();`
> > I guess $consumable->consumable_assignment_count; is not known and therefore the QTY is the output number.
> > I have edited this line of code to:
> > `$avail = $consumable->numRemaining();`
> > And now all is working well as i want to, i don't know if this is the way it should be. Please check, thanks!
> > Ben
> 
> Where do you go edit this code? I have the same problem where notifications shows up even though the stocks is above the minimum quantity.

Dear Keron,

I have found this piece of code in the Helper.php file on C:\wamp\www\snipe-it\app\Helpers\
Snipe-it has solved this issue in newer releases.

Regards,

Ben

**Comment by Keronmat** [comment]
> > > I have found this piece of code:
> > > `$avail = $consumable->qty - $consumable->consumable_assignment_count; //$consumable->numRemaining();`
> > > I guess $consumable->consumable_assignment_count; is not known and therefore the QTY is the output number.
> > > I have edited this line of code to:
> > > `$avail = $consumable->numRemaining();`
> > > And now all is working well as i want to, i don't know if this is the way it should be. Please check, thanks!
> > > Ben
> > 
> > 
> > Where do you go edit this code? I have the same problem where notifications shows up even though the stocks is above the minimum quantity.
> 
> Dear Keron,
> 
> I have found this piece of code in the Helper.php file on C:\wamp\www\snipe-it\app\Helpers
> Snipe-it has solved this issue in newer releases.
> 
> Regards,
> 
> Ben

Thank you for responding. I am currently using version 4.9.4 and I am getting the same error. But I did notice the code was already fix in the helper file.
