### ISSUE TITLE
different header/salutation in email when checkin or checkout

### ISSUE THREAD

**Issue by mandelbrotmedia** [snipe/snipe-it#4902]
#### Expected Behavior (or desired behavior if a feature request)

when a user is receving an email for asset checkin or checkout the salutation should be "Hallo Thomas Muster" 

#### Actual Behavior

Checkout: "Hallo Thomas Muster"  --thats OK
Checkin: "Hallo Thomas"   --thats not OK; Lastname is missing

I tried to play around with the email-templates. but there is only 1 variable: $first_name
it seeams that when ckeckout the variable $first_name is filled with firstname AND lastname,
but when checkin the variable ist only filled with firstname
-----

#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
fresh install
- Version of Snipe-IT you're running
v4.1.10
- Version of PHP you're running
7.1.13
- Version of MySQL/MariaDB you're running
10.1.30-MariaDB
- What OS and web server you're running Snipe-IT on
Windows Server 2012R2; xampp, apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual installation with git
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
no, because the demo doesnt send emails when checkin an asset (also when enabling in the category)
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
@mandelbrotmedia - is last name actually required in that email? Would't people know their own last name?

**Comment by mandelbrotmedia** [comment]
Yes its absolutly required! Here in austria (and germany to) its very impolite to call people only by there first name. Specially if he is your boss or someone in the higher management

**Comment by mandelbrotmedia** [comment]
Great! Thanks a lot!!

**Comment by snipe** [comment]
Glad to help! We try really hard to accommodate lots of different languages in Snipe-IT, but many times we need users' help understanding the cultural nuances, so thanks for letting us know!
