### ISSUE TITLE
Best practice LDAP

### ISSUE THREAD

**Issue by Tristantarrieux** [snipe/snipe-it#4903]
#### Hello,
i would like to know if user LDAP sync is an import of Active Directory users in snipe-it or if it's only a link between both software.
When i do a user LDAP sync, i dont't have any user imported, but if i create an asset, i can associate it with an AD user

Thank's for all, your software is really nice and useful

**Comment by snipe** [comment]
[LDAP sync](https://snipe-it.readme.io/docs/ldap-sync-login) syncs users. That's why we call it a sync.

**Comment by Tristantarrieux** [comment]
Thank you
