### ISSUE TITLE
FYI - AFK

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#4905]
Hi all - just a heads up that I'll be out of town on my honeymoon for about 11 days starting tonight, with (hopefully) very limited access to the internet. As such, I won't be on Gitter or handling Github issues until I return. 

Folks like @HinchK, @fordster78 and @dmeltzer *may* be able to assist you, __if their schedules allow__. Please be nice to them while I'm gone. 

Thanks for your patience!

![the-it-crowd-imgonepoof](https://user-images.githubusercontent.com/197404/35345324-32399260-00e4-11e8-931c-771a4c0c3d32.gif)

**Comment by Jarli01** [comment]
Got it, beat @HinchK @fordster78 and @dmeltzer with a rubber hose for the answers we need. 

Have a good trip

**Comment by snipe** [comment]
Just an update - we loved it so much here that we added a few extra days onto our trip. I'll be back Thursday morning :)

There are monkeys here and I never want to leave. :)

**Comment by dmeltzer** [comment]
![monkey](https://user-images.githubusercontent.com/3803132/35835041-72497ff2-0aa6-11e8-9e61-84c2d702a3b6.gif)

**Comment by snipe** [comment]
That is not even a monkey. :anger:

![ehrmantrauttired](https://user-images.githubusercontent.com/197404/35835482-9b98a35c-0aa0-11e8-993c-3cd2f95b67d9.gif)
