### ISSUE TITLE
Unexpected Character Input When Generating App Key

### ISSUE THREAD

**Issue by ooteron** [snipe/snipe-it#4907]
Hello,

I'm just trying to generate the app key from SSH with the `php artisan key:generate` command and is bringing me this error:

`X-Powered-By: PHP/4.4.9
Content-type: text/html

<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>/homepages/8/d605909532/htdocs/asset/artisan</b> on line <b>31</b><br />
<br />
<b>Parse error</b>:  syntax error, unexpected T_STRING in <b>/homepages/8/d605909532/htdocs/asset/artisan</b> on line <b>31</b><br />
`

I already did:

1. The upload to my 1and1 root
2. Created the database
3. Set the configuration file (.env)
4. Check permissions
5. And installed Composer

My PHP version is 5.6.33. What could be the problem?

**Comment by snipe** [comment]
Web server's PHP and command line PHP are sometimes different. What's the output of `php -v`?

**Comment by ooteron** [comment]
Thanks for your reply. When I echo phpversion(); it saids is 5.6.33.

**Comment by snipe** [comment]
That's not what I'm asking. `phpversion()` will use the web server's PHP, not the command line PHP. Run the command I gave you via command line. `php -v`

**Comment by ooteron** [comment]
Sorry. It saids is the 4.4.9. Do I have to change it?

**Comment by snipe** [comment]
Yeah, both your web version and your command line version of PHP must be [5.6.4 or higher](https://snipe-it.readme.io/docs/requirements).

**Comment by ooteron** [comment]
Sadly, I cannot change this in my 1and1 hosting :(

Well, thanks a lot anyway.

**Comment by snipe** [comment]
You actually might be able to, you just may have to use the full path to the specific version of PHP you want. Based on this info, it looks like [they support PHP7](https://help.1and1.com/hosting-c37630/scripts-and-programming-languages-c85099/php-c37728/change-the-default-version-of-php-in-the-control-panel-a792330.html), so you'd probably need to try something like:

```
/usr/bin/php7.1-cli composer install
/usr/bin/php7.1-cli artisan key:generate
```

**Comment by ooteron** [comment]
Snipe I did it and it works! I got the application key. Thanks a lot for your help!
