### ISSUE TITLE
Feature Request - Allow multiple values for custom fields

### ISSUE THREAD

**Issue by tutankh** [snipe/snipe-it#4908]
#### Expected Behavior (or desired behavior if a feature request)

Ability to create and maintain custom fields which have multiple values. For example, a device's IP addresses, or software packages installed.

-----

**Comment by snipe** [comment]
I don't really understand what you mean here. You can select the tex format and enter whatever you like, single values or more. For pieces of data that are not directly related to each other, you should create multiple custom fields instead.

**Comment by tutankh** [comment]
I'm just thinking it would make it easier to view, add to, or report on the data without having to delimit it somehow via scripting.

**Comment by snipe** [comment]
You wouldn't delimit via scripting, you would just create multiple fields to separate the data, no?

**Comment by tutankh** [comment]
Some machines have multiple answers to the same query, like IP addresses. Some machines owned by IT staff have upwards of 8 IPs on a single machine, and there isn’t really a way to predict how many it’s going to have. It seems a bit redundant to create 8 custom fields for “IP 1... 2 ...etc “ or “app 1 ... 2... etc.” When instead, I think it would be helpful to add info as an instance of the same field.

**Comment by snipe** [comment]
That's a level of complexity for edge cases that we're honestly not likely to address any time soon. It's an edge case, and a comma-separated list of IPs in a text field works just fine for most people.

**Comment by patrice-geo** [comment]
I support this too! Something in the likes of [this](http://demo.sqlmaestro.com/feature_demo/editors_multiple_select.php): Selecting multiple values from a list or a table with a listbox.

I would use it to store information about different video outputs on an asset.

**Comment by ShamikhI** [comment]
+1

> I support this too! Something in the likes of [this](http://demo.sqlmaestro.com/feature_demo/editors_multiple_select.php): Selecting multiple values from a list or a table with a listbox.
> 
> I would use it to store information about different video outputs on an asset.

**Comment by DerKiLLa** [comment]
+1

We have our Access-Keys in Snipe-IT and we would like to link all rooms, where key X has access. So i need a custom field "List" where i can select multiple rooms.

**Comment by heikoboehme** [comment]
+1 please reopen..  It would be nice if we had the posibillity to annotate more than one meta data to an asset in one user defined field. i have an metadata cataloge with more than 100 elements. it is not applicable to create for each element an own definied field.

**Comment by Smithx10** [comment]
I ran into this when adding a "Switch" Model.   The switch has 32 Ports,  and I was hoping to be able to have a "SwitchPort"
 custom field that would iterate.   I wound up just using the API to create the Custom fieldset with 32 custom fields.
