### ISSUE TITLE
Optional: SSL Database Settings

### ISSUE THREAD

**Issue by brownac25** [snipe/snipe-it#4909]
Hi,

I am just wondering if there is a guide anywhere to explain how the optional SSL Databse settings should be formatted and the available options.

E.G. 
DB_SSL=true
DB_SSL_KEY_PATH=/path/to/key
DB_SSL_CERT_PATH=/path/to/cert
DB_SSL_CA_PATH=/path/to/ca
DB_SSL_CIPHER=RSA-AES

vs

DB_SSL=true
DB_SSL_KEY_PATH="/path/to/key"
DB_SSL_CERT_PATH="/path/to/cert"
DB_SSL_CA_PATH="/path/to/ca"
DB_SSL_CIPHER="RSA-AES"

**Comment by snipe** [comment]
Generally speaking, if you see any characters that could be parsed funny in the .env, enclose the ext in quotes. I usually do single quotes, but it shouldn't matter.

```
DB_SSL=true
DB_SSL_KEY_PATH='/path/to/key'
DB_SSL_CERT_PATH="'path/to/cert'
DB_SSL_CA_PATH='/path/to/ca'
DB_SSL_CIPHER='RSA-AES'
```

**Comment by brownac25** [comment]
Awsome! Thank you for your quick response!

**Comment by snipe** [comment]
My pleasure!
