### ISSUE TITLE
picture and modelnumber missing in asset-list

### ISSUE THREAD

**Issue by mandelbrotmedia** [snipe/snipe-it#4910]
#### Expected Behavior (or desired behavior if a feature request)

if i add a new asset i should see a picture, model, and modelnumber in the list

-----

#### Actual Behavior

i only see model. picture and modelnumber are missing

![image](https://user-images.githubusercontent.com/11631505/35374161-0017784c-01a2-11e8-8d09-6ed7cc138c96.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
fresh
- Version of Snipe-IT you're running
v4.1.10
- Version of PHP you're running
7.1.13
- Version of MySQL/MariaDB you're running
10.1.30-MariaDB
- What OS and web server you're running Snipe-IT on
Windows Server 2012R2; xampp, apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
in the demo everything works well
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
You sure you're running v4.1.10? Check Settings > General and see if there is an asset model lists setting there at the bottom of the screen. If there is, you're not on v4.1.10, and you just have to select wha you want to be visible there.

**Comment by mandelbrotmedia** [comment]
oooh, i'm sorry, i'm on v4.1.11-pre build 3288 (i did "git pull" this morning)

if i check one of the settings i get the following error:


`
(3/3) QueryExceptionSQLSTATE[42S22]: Column not found: 1054 Unknown column 'modellist_displays' in 'field list' (SQL: update `settings` set `updated_at` = 2018-01-25 06:48:36, `require_accept_signature` = , `modellist_displays` = image,model_number where `id` = 1)
--
in Connection.php (line 647)
at Connection->runQueryCallback('update `settings` set `updated_at` = ?, `require_accept_signature` = ?, `modellist_displays` = ? where `id` = ?', array('2018-01-25 06:48:36', null, 'image,model_number', 1), object(Closure))in Connection.php (line 607)

`

**Comment by snipe** [comment]
You have to run migrations when you upgrade. `php artisan migrate`

**Comment by mandelbrotmedia** [comment]
Woooohaaa! Didn't know that. 
Now i works like a charm

Thank you soooo much!

**Comment by snipe** [comment]
You should always be running migrations when you upgrade. It's what keep the DB structure in sync with the rest of the app. See [upgrading documentation here](https://snipe-it.readme.io/docs/upgrading).
