### ISSUE TITLE
 Change in asset maintenance

### ISSUE THREAD

**Issue by gueeme** [snipe/snipe-it#4914]
Hello,

I know absolutely nothing programming.
I would like some help from you so that I can make the changes below so that the system can better serve me.
Is it possible for you to help me?

Thank you.

![snipe-it](https://user-images.githubusercontent.com/19538568/35398661-a113b0bc-01d9-11e8-9dc9-8812f1a016d7.jpg)

**Comment by snipe** [comment]
That’s a pretty complex thing to ask for help on if you know “absolutely nothing about programming”. Maybe better to leave this as a feature request and work on something a little easier to start with? If you’re interested in learning to program, checking out the laravel docs on laravel.com and the PHP docs at php.net would be a good place to start. I wouldn’t rate this request as beginner level.

I know additional maintenance types are being worked on by @fordster78, but I can tell you i’m not enthusiastic about custom fields there. It’s a lot of complexity for a feature not everyone uses, especially when we don’t even have custom fields for accessories, etc, yet which more people would benefit from.
