### ISSUE TITLE
Feature Request/Discussion - Assigning [Floating] Licenses to a Location

### ISSUE THREAD

**Issue by MSTigers** [snipe/snipe-it#4917]
I would like to discuss the concept and ideas for being able to assign software to a location. For example, we may have a subscription with 400 licenses that is assigned to a campus. These licenses are not assigned to a specific user but are just an available pool.

It would be really handy if there was some way to assign 'floating' seats out to a location.

My idea: When creating a software license, have a checkbox "Is this a floating license?" If checked Yes, then you are allowed to assign multiple licenses to a location. This way we can utilize "seats" in a non-conventional way.

For example, if we have 1,000 licenses I want to allocate 400 licenses to **Campus1**, 300 licenses to **Campus2**, and 200 licenses to **Campus3**. Remaining seats available would be 100 on the Software Licenses view.

It might be hard to include from the `/licenses` page what locations are currently seat holders, so maybe just add a column that is a clickable link "Floating Locations" and how many locations it's assigned to, that takes you to the details page of the specific license. Then it can be included in full on the right panel.

In this situation, we would need to be able to separate software licenses from assets when counting totals as that could start getting confusing. I'd be fine if for quantity-purposes, when viewing a location that it'd be its own section: in addition to "Users" and "Assets" sections, have a "Licenses" section or something.

My current workaround is to just give it a Single Seat and document in the Notes of that Software License how many floating licenses we have allocated and where they are allocated to. In the `/licenses` page it remains "Available" with a QTY of 1, ready to be checked out.

It's not vital of course, but boy would that be a handy feature. Thoughts? Suggestions? Issues? Discuss!

**Comment by MSTigers** [comment]
Bump

**Comment by MSTigers** [comment]
Bump. Still very useful if could assign Licenses to locations.

**Comment by MSTigers** [comment]
I won't let you die

**Comment by uknzaeinozpas** [comment]
I'm on your side ;-)

**Comment by MSTigers** [comment]
Yes, yes it is.

**Comment by MSTigers** [comment]
Round and round we go, when stalebot will shush up, nobody knows!

**Comment by MSTigers** [comment]
OK so as much as I love my own ideas, I've thought more on this. Considering #5140  is in development the fact that FLOATING LICENSES are licenses, technically speaking, these could be managed as I have proposed by, by creating an Accessory with a manually created category of "Floating License."

Again, given 5140's progression I believe this is unnecessary and I will be able to accomplish 100% of what I want to do by Accessory > License > Bulk Check-Out to location.

**Comment by KSameer7** [comment]
@MSTigers is this feature implemented?

**Comment by MSWork79** [comment]
@KSameer7 as of Version v4.7.7 I can still only check out accessories to users, not locations so my work around isn't implemented yet. So unless #5140 which still appears to be open, has been implemented, I'd say no. I can checkout Licenses to users or assets only.

**Comment by rbeckerproxess** [comment]
Would love that feature.

**Comment by PatriceGanon** [comment]
+1 need somthing to manage flotting licence

I need to know the reaal number of licence and also need to know where it's installed, so something in the lines of a checkmark for foltting and when it's on you can overcommit the licence seats
