### ISSUE TITLE
Enhancements to Requestable Assets

### ISSUE THREAD

**Issue by mehrdadbehroozi** [snipe/snipe-it#4918]
#### Expected Behavior (or desired behavior if a feature request)

1. Enable Snipe to send an email to the person who currently has a requestable asset checked out when that asset is requested by another user. 

2. Allow the user making a request for an asset to view who the asset is currently checked out by.

3. Allow users to checkin requestable assets that they have checked out. 

4. Allow users to checkout requestable items that they have requested and are available.

-----

#### Actual Behavior

Users can view requestable assets and request them. No alert is sent to anyone to alert that a request has been made for an asset.

-----

#### Please confirm you have done the following before posting your bug report:

(This section is not applicable as this is a feature request)

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Not Sure.

- Version of Snipe-IT you're running
v4.1.11-pre build 3288 (g426bf38)

- Version of PHP you're running
Not sure.

- Version of MySQL/MariaDB you're running 
MySQL 5.5

- What OS and web server you're running Snipe-IT on
Debian

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Not sure.

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Not Applicable.

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
https://snipe.companyx.nz/account/requestable-assets

- If a stacktrace is provided in the error, include that too. 
Not Applicable.

- Any errors that appear in your browser's error console.
No.

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Yes

- Include any additional information you can find in `storage/logs` and your webserver's logs.
Not Applicable

- Include what you've done so far in the installation, and if you got any error messages along the way.
Not Applicable

- Indicate whether or not you've manually edited any data directly in the database
Not Applicable

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by nmmclwhitehead** [comment]
hey i would also like the ability for the user to check out and in the requestable items

**Comment by mehrdadbehroozi** [comment]
hey, @nmmclwhitehead I do believe that you should be able to do this if the asset is marked as requestable. Is that not the case for you?

**Comment by nmmclwhitehead** [comment]
hey @mehrdadbehroozi thanks for the reply , the only option i have is to request the item not the ability to checkout.

**Comment by mehrdadbehroozi** [comment]
@nmmclwhitehead , Ahh yes, I remember now. First the user makes the request, the asset manager then sorts out the request. Is there a particular reason why you want a Staff member to checkout an item without it being inspected by the asset manager? In our case it was because I wanted staff to be able to check out the our test mobile phone without having to wait for me to approve it. But then we found that far too often the phones are returned without charge so we then found the Snipe way of doing it more effective.

**Comment by edgar-1** [comment]
I agree some sort of alert would be nice to the admin when an asset is requested as well as the ability for an end user to check-in the asset instead of just canceling or physically giving it to an admin and have the admin check it in. I realize if they cancel, the asset is still checked out to them but it would be nice to have an alert when an end user checks in an asset and the admin would need to confirm and approve it. Or make an asset not available status instead of still requestable when it's currently deployed.
