### ISSUE TITLE
Error creating the users table

### ISSUE THREAD

**Issue by mikesoule** [snipe/snipe-it#492]
`php artisan app:install`

Produces the following error:

```
  [Illuminate\Database\QueryException]                                                                                                      
  SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at' (SQL: create table `users` (`id` int unsi  
  gned not null auto_increment primary key, `email` varchar(255) not null, `password` varchar(255) not null, `permissions` text null, `act  
  ivated` tinyint(1) not null default '0', `activation_code` varchar(255) null, `activated_at` timestamp null, `last_login` timestamp null  
  , `persist_code` varchar(255) null, `reset_password_code` varchar(255) null, `first_name` varchar(255) null, `last_name` varchar(255) nu  
  ll, `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) default character set utf8 collate utf8_unicod  
  e_ci engine = InnoDB) 
```

Running PHP 5.6.5 on CentOS 7 with MySQL 5.5.39-36.0 on CentOS 6.

**Comment by uberbrady** [comment]
That sounds like MySQL is running in strict mode. Any chance you can turn that off?

**Comment by snipe** [comment]
Agreed, it sounds like strict mode.

You may disable strict mode in one of two ways:

Open your `my.ini` file within the MySQL installation directory, and look for the text `sql-mode`.

Find:

`sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"`

and change to

`sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"`

or you can run the following in phpMyAdmin

`SET @@global.sql_mode='';`

**Comment by mikesoule** [comment]
Thanks for the quick replies. There are several other applications running on the MySQL cluster so I'd rather not change the sql mode. Instead, I'm going to try changing the blueprint for these columns to make them nullable and re-try the install. I'll report my results but if you already know that this will cause problems with Snipe, please let me know.

**Comment by Esya** [comment]
Same thing for me I get this kind of errors, why not just do an sql query to set the sql_mode to not strict for this session only during the install task?

```
SET SESSION sql_mode = '';
```

**Comment by mikesoule** [comment]
Here's how I solved it. Would love to get a better suggestion that doesn't involve modifying Laravel.

In vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php, I changed...
```
if (isset($config['strict']) && $config['strict'])
{
    $connection->prepare("set session sql_mode='STRICT_ALL_TABLES'")->execute();
}
```
to...
```
if (isset($config['strict']) && $config['strict'])
{
    $connection->prepare("set session sql_mode='STRICT_ALL_TABLES'")->execute();
} else {
    $connection->prepare("set session sql_mode=''")->execute();
}
```

I think it would be fantastic if sql-mode was a configurable option in Snipe's database config.

On a side note, the seeding tool is a great idea but it will not work on a multi-master cluster. In multi-master, auto-increment IDs must start at pre-defined offsets and increment by a number great than or equal to the number of database nodes. Since the seeder depends on IDs starting at 1 and incrementing by 1, it results in broken foreign key relationships and then Snipe throws exceptions because it expects there to be a model or asset with ID=1. To fix this, the seeder would need to query IDs before creating dependent records.

That said, it's a beautiful project so thank you for all the hard work that must have gone into it!

**Comment by snipe** [comment]
@mikesoule Yeah, it's a REALLY bad idea to be changing Laravel core, especially when the problem is with a vendor, not the core itself. 

It looks like it might be a bug/issue with Laravel/Eloquent/Schema Builder itself and the way it handles timestamps. There is a GH Issue here about it: https://github.com/laravel/framework/issues/5903

I have followed up with them on that thread, so will hopefully know more soon.

**Comment by mikesoule** [comment]
I failed to mention, table creation is not the only sticking point. Several queries throughout the application use double quotes which also causes breakage. My understanding is that MySQL, and other DB vendors, are moving toward strict ansi compliance so it would be best to replace double quotes in SQL queries in the long-term.

**Comment by snipe** [comment]
I don't believe double vs single quotes are a problem here, even in strict mode. All of our code is handled through the Schema Builder and all queries use prepared statements, to be as safe and as DB-agnostic as possible.

**Comment by mikesoule** [comment]
I can't remember now if I had trouble with the double quotes only in the migration scripts or not but I definitely hit errors at some point due to double quotes.

**Comment by snipe** [comment]
Without more information, I'm not sure how that's going to help, unfortunately. As I said, we use the schema builder, which abstracts all of that away. If you ran into issues, it may be because of something else. I just ran through the installer 10 or so times this morning with strict mode turned on.

**Comment by mikesoule** [comment]
Going to close this issue for now since I got it working and there aren't any immediate actions to be taken.

**Comment by snipe** [comment]
Ok, if you end up being able to reproduce those original errors, let me know. We are never querying the database outside of the builder (with the exception of a few DB::raw commands because the builder didn't have the functionality we needed)

**Comment by snipe** [comment]
Looks like Laravel 4.2+ introduced a strict option in the database config. 
https://github.com/laravel/laravel/commit/88b90c7218c4b2a6c98d410078059f994d1a9356#diff-0

Investigating.

**Comment by sektonic** [comment]
The best way to fix this issue, first run 
> php artisan migrate --package=cartalyst/sentry

before php artisan migrate

**Comment by kingpabel** [comment]
This is due to MySQL not accepting zero as a valid defalt date and thus the table creation fails a constraint check on creation.

You probably have NO_ZERO_DATE enabled in your MySQL configuration. Setting this to off will allow you to create the table (or alternatively remove the default 0 value or change it to CURRENT_TIMESTAMP.

**Comment by sebaggro** [comment]
tengo un error .

 [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: Invalid default value for 'created_at' (SQL: create table `users` (`id` int
  unsigned not null auto_increment primary key, `email` varchar(255) not null, `password` varchar(255) not null, `permissions` te
  xt null, `activated` tinyint(1) not null default '0', `activation_code` varchar(255) null, `activated_at` timestamp null, `last
  _login` timestamp null, `persist_code` varchar(255) null, `reset_password_code` varchar(255) null, `first_name` varchar(255) nu
  ll, `last_name` varchar(255) null, `created_at` timestamp default 0 not null, `updated_at` timestamp default 0 not null) defaul
  t character set utf8 collate utf8_unicode_ci engine = InnoDB)

[PDOException]
  SQLSTATE[42000]: Syntax error or access violation: Invalid default value for 'created_at'

alguna ayuda ?

**Comment by snipe** [comment]
@sebaggro see the answer above
