### ISSUE TITLE
Error when trying to access setup page from install

### ISSUE THREAD

**Issue by dos1313** [snipe/snipe-it#4921]
#### Expected Behavior (or desired behavior if a feature request)

Setup Page

-----

#### Actual Behavior
ErrorException
file_put_contents(/var/www/snipe-it/storage/framework/views/a44d2bed1b6a8060e7f47158e9c6fd970ed3fb53.php): failed to open stream: Permission denied

and

ErrorException
file_put_contents(/var/www/snipe-it/storage/framework/sessions/7qVBlZLBIbbpTw02IsGdD7sTolQ3VmIEhQcWYIlF): failed to open stream: Permission denied

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install
- Version of Snipe-IT you're running
Latest version
- Version of PHP you're running
5,6
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
CentOS7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Setup page (errors listed at top of post)
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Issue does not occur in demo
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
I have not tried any fixes
- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by sarzali07** [comment]
edited .env file delete wrong variables in the script, work perfect then correct it afterwards.

**Comment by sarzali07** [comment]
chown -R apache:apache storage public/uploads
chmod -R 755 storage
chmod -R 755 public/uploads

**Comment by dos1313** [comment]
Can you please clarify which variables in the .env file I could change?

and do I run those commands after editing my .env file?

**Comment by sarzali07** [comment]
https://snipe-it.readme.io/docs/configuration check configuration file and variable. remove extra one.

**Comment by dos1313** [comment]
I can't see anything wrong in my .env file. Which variable do you think is at fault?

I ran those commands but they don't seem to have made a difference.
