### ISSUE TITLE
Custom "Print All Assigned" page 

### ISSUE THREAD

**Issue by ppestime** [snipe/snipe-it#4925]
Is it possible to customize my "Print All Assigned" page to include a header with company logo and name, and additional place for supervisor signature and inventory keeper signature?

Thanks for such a great software!

**Comment by sk33z3r** [comment]
I would love to open this feature request back up. Would be a huge help to implement Snipe at my company, as we don't use individual Asset Names and want to display the asset cost (and possibly a total user cost) on this page. Having the ability to customize what the page looks like would cover a ton of use cases and give more customization.

Please let me know if you'd like any extra info!

**Comment by snipe** [comment]
> perhaps if possible to use a template file perhaps a Word document set by the admin

That's unlikely to happen to be honest. It would require additional libraries to import the Word template, and that road is fraught with peril.

**Comment by sk33z3r** [comment]
For anyone else looking to customize their page, it can be done right now with a couple of caveats:

- You have to understand a bit of PHP, and edit this file directly: `./resources/views/users/print.blade.php`
- If you don't keep track of it, updating your instance will _revert your changes_

I can't give any tutorials or examples for what your situation may be, but if you know HTML and PHP, then you can dig in and add/remove variables and columns as you need until a decision is made on this feature. To avoid it getting overwritten on future releases, since I run Docker, I have bind mounted the individual file so it is persistent on container upgrades.

Here's an example of what I have put together, including a cost print out for assets, and a monthly cost for licenses.

**Added this to the top to define 0 for each cost variable:**

```php
@php
    $cost = 0;
    $monthly = 0;
@endphp
```

**I adjusted my assets table like this (note the cost variable in front of the counter):**

```php
@if ($snipeSettings->logo_print_assets=='1')
    @if ($snipeSettings->brand == '3')

        <h3>
        @if ($snipeSettings->logo!='')
            <img class="print-logo" src="{{ url('/') }}/uploads/{{ $snipeSettings->logo }}">
        @endif
        {{ $snipeSettings->site_name }}
        </h3>
    @elseif ($snipeSettings->brand == '2')
        @if ($snipeSettings->logo!='')
            <img class="print-logo" src="{{ url('/') }}/uploads/{{ $snipeSettings->logo }}">
        @endif
    @else
      <h3>{{ $snipeSettings->site_name }}</h3>
    @endif
@endif

<h4>Assigned to {{ $show_user->present()->fullName() }}</h4>

@if ($assets->count() > 0)
    @php
        $counter = 1;
    @endphp
    <table class="inventory">
        <thead>
        <tr>
            <th colspan="8">{{ trans('general.assets') }}</th>
        </tr>
        </thead>
        <thead>
            <tr>
                <th style="width: 5%;"></th>
                <th style="width: 5%;">Asset Tag</th>
                <th style="width: 20%;">Model</th>
                <th style="width: 10%;">Category</th>
                <th style="width: 30%;">Serial</th>
                <th style="width: 10%;">Supplier</th>
                <th style="width: 10%;">Cost</th>
                <!-- <th style="width: 10%;">Checked Out</th> -->
            </tr>
        </thead>

    @foreach ($assets as $asset)

        <tr>
            <td>{{ $counter }}</td>
            <td>{{ $asset->asset_tag }}</td>
            <td>{{ $asset->model->manufacturer->name }} {{ $asset->model->name }} {{ $asset->model->model_number }}</td>
            <td>{{ $asset->model->category->name }}</td>
            <td>{{ $asset->serial }}</td>
            <td>{{ $asset->supplier->name }}</td>
            <td>{{ $asset->purchase_cost }}</td>
            <!-- <td>{{ $asset->last_checkout }}</td> -->
        </tr>
            @php
                $cost = $cost + $asset->purchase_cost;
                $counter++
            @endphp
    @endforeach
    </table>
@endif
```

**And adjusted my license table like this (note the monthly variable before the lcounter):**

```php
@if ($licenses->count() > 0)
    <br><br>
    <table class="inventory">
        <thead>
        <tr>
            <th colspan="4">{{ trans('general.licenses') }}</th>
        </tr>
        </thead>
        <thead>
            <tr>
                <th style="width: 5%;"></th>
                <th style="width: 70%;">Software</th>
                <th style="width: 25%;">Monthly Cost</th>
                <!-- <th style="width: 10%;">Checked Out</th> -->
            </tr>
        </thead>
        @php
        $lcounter = 1;
        @endphp

        @foreach ($licenses as $license)

            <tr>
                <td>{{ $lcounter }}</td>
                <td>{{ $license->name }}</td>
                <td>{{ $license->purchase_cost }}</td>
                <!-- <td>{{  $license->assetlog->first()->created_at }}</td> -->
            </tr>
            @php
                $monthly = $monthly + $license->purchase_cost;
                $lcounter++
            @endphp
        @endforeach
    </table>
@endif
```

**Then I removed the signed off portion (my company doesn't care, we like the email system as a confirmation) and added the cost calculations:**

```php
<h3 style="text-align: right; margin-right: 50px;">Total Asset Cost - ${{ $cost }} USD</h3>
<h3 style="text-align: right; margin-right: 50px;">Total Monthly Cost - ${{ $monthly }} USD</h3>
```

**Here's what it looks like when I use the button, now:**

![snipe](https://user-images.githubusercontent.com/20587571/47925568-e5661a00-de94-11e8-8791-a469a7da7f7d.png)

**Comment by CoMPaTech** [comment]
@snipe using blade shouldn't this be possible using childs and sections?

**Comment by kaeser49** [comment]
Thank you sk33z3r,
your work helps me a lot.
it would be a great thing to have a small form editor or a possibility to assign a form editor.

**Comment by kruzikruz** [comment]
Hi,

Do you know how I can edit the header and footer? When I save the file to PDF I have a visible header and footer where I would like to put other data.

<img width="290" alt="Zrzut ekranu 2022-11-16 o 10 27 31" src="https://user-images.githubusercontent.com/28232236/202142036-f9bc31a2-1201-464f-b6cf-b4be4531bdea.png">

<img width="468" alt="Zrzut ekranu 2022-11-16 o 10 27 22" src="https://user-images.githubusercontent.com/28232236/202142143-1e799104-2a34-4f60-b7fb-1147712cb91a.png">

**Comment by JMH-Jarbydev** [comment]
@sk33z3r  I customized the template to suit our needs, but there is an important issue we are facing. The report does not include any child assets. For instance, in cases where we have a parent asset with three child assets assigned to it, the report only shows the parent asset. Could you please provide assistance with this matter?
