### ISSUE TITLE
Feature request/Question: Notification for all CheckIn/CheckOuts

### ISSUE THREAD

**Issue by rodeff** [snipe/snipe-it#4929]
Hello Snipe,

I couldn't find anything related to this, so I am opening new feature request.

Is it possible to setup one or more emails to receive notification emails for all asset movements - CheckIn/CheckOuts?

Thanks in advance.

**Comment by cslucian** [comment]
That would be great for my environment also.

I do not use the acceptance option but a notification to the user on check-out and check-in would be awesome.

**Comment by Raj22223** [comment]
Even we are looking for the same instead of acceptance for check out assets , it would be good to notify users on assets that are checked out .

**Comment by Raykongstar** [comment]
+1, Any good news coming soon?
