### ISSUE TITLE
Multiple errors after fresh install

### ISSUE THREAD

**Issue by Esya** [snipe/snipe-it#493]
Hi,

After a fresh install based off master (Also tried using the latest tag 1.2.2) I get multiple errors when trying to use the application.

The first error I get after successfully logging-in is a `Trying to get property on a non-object` because I have some assets that have a `model_id` set to 2 (Created by the `db:seed` task) but there is no model of id 2 in the database.

Doing an `INSERT` to manually create a model so that the foreign keys does not fail fixes this error but then some other parts of the application fail in a similar manner, like licenses for example

![Error](https://d1zjcuqflbd5k.cloudfront.net/files/acc_42229/1fFG8?response-content-disposition=inline;%20filename=Screenshot%20on%202015-02-04%20at%2015%3A49%3A51.png&Expires=1423045265&Signature=MdWZWVWqOFuX~dna8DjpXMkA1MNJ7bVwz6RyRPrwXZ0hbWzlg1x5G1I-1DxDQtU4sjX2eFLzhMkXrvwOp7h2W68buMBYKxWua~MArOR-xRtDWNTp5LBJalzElLU62ew2upYctXxK2JP56gU3OM8sG6t4WG8UK2PoIPgnCMf5EIU_&Key-Pair-Id=APKAJTEIOJM3LSMN33SA)

Same thing here the foreign keys are failing.

I did not get any error when running the artisan install task nor when running the seed task. 

I'm running `PHP 5.5.21` and `MySQL 5.6.19` on top of Apache.

**Comment by snipe** [comment]
So you're saying the DB seed data is incorrect?

**Comment by Esya** [comment]
Well, either it is incorrect, or it is failing silently.

**Comment by Esya** [comment]
I found the issue.

```
mysql> SHOW VARIABLES LIKE 'auto_inc%';
+--------------------------+-------+
| Variable_name            | Value |
+--------------------------+-------+
| auto_increment_increment | 2     |
| auto_increment_offset    | 1     |
+--------------------------+-------+
```

We use an autoincrement of 2 because of our master/master replication and it seems like snipe-it cannot handle it. We can force an increment of 1 for the session then, can you point me to a file where I could set raw mysql queries to do that, for the db:seed, for the install task, and also when in regular use?

I also had to turn off our strict mode globally, but it'd be nice to be able to set it off per-session as well.

**Comment by Esya** [comment]
#492 has good elements of response although as he says it would be nice to have a way to do it without hacking vendor sources!

Thanks for your support

**Comment by snipe** [comment]
It looks like it might be a bug/issue with Laravel/Eloquent/Schema Builder itself and the way it handles timestamps. There is a GH Issue open about it. 

I have followed up with them on that thread, so will hopefully know more soon.

**Comment by snipe** [comment]
@Esya that actually looks like a different issue. That issue you just referenced is related to mysql being in strict mode, whereas your incrementing issue as a master/master issue.

**Comment by Esya** [comment]
True, but my fix for both of them was the one mentioned in #492 , I hardcoded a prepare('set session..') query for now

**Comment by snipe** [comment]
Yeah, but that's a pretty awful solution. (I mean, that's not your fault, Laravel should be handling timestamps in strict mode better, but it's pretty awful for future upgrades, etc.)

I'll add a config option to the config file to specify what increment to use for the seeder. That's the only place where we force IDs, so that should solve the issue. 

(You could also always just not seed the database - it's not required, just there to be helpful to illustrate how stuff works.)
