### ISSUE TITLE
Problem with decimal costs in EUR

### ISSUE THREAD

**Issue by mandelbrotmedia** [snipe/snipe-it#4930]
#### Expected Behavior (or desired behavior if a feature request)

when setting "514.40" costs for an asset, costs should be "514.40"

-----

#### Actual Behavior

after hitting "save" costs transform from "514.40" to "5144.00"

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
fresh
- Version of Snipe-IT you're running
v4.1.11
- Version of PHP you're running
7.1.13
- Version of MySQL/MariaDB you're running
10.1.30-MariaDB
- What OS and web server you're running Snipe-IT on
Windows Server 2012R2; xampp, apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual installation with git
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
at demo everthing works fine
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

--------------------------------------
set costs to 514.40:
![image](https://user-images.githubusercontent.com/11631505/35512992-dab1727a-0501-11e8-9ddd-42723d6117bb.png)

after hitting save:
![image](https://user-images.githubusercontent.com/11631505/35513005-ea4b72c6-0501-11e8-80cd-25324446d726.png)

**Comment by chibacityblues** [comment]
Tried to reproduce - doesn't happen to me neither in our 4.10 or 4.11-pre instance. A xampp / PHP locale problem maybe?

**Comment by mandelbrotmedia** [comment]
i figured out that it only happend when APP_LOCALE is set to "de".
when set to "en" it works

**Comment by mandelbrotmedia** [comment]
additionally i have to say in austira or germany we use a comma (514,40) and not a point (514.40) for typing money amounts. But typing a comma in the cost-field results in an error: 
`The purchase cost must be a number.`

**Comment by ginculia** [comment]
Hi, Snipe,
I have exactly same issue as mentioned mandelbrotmedia. Then I enter price e.g. 12 Euros ant 23 cents (12.13) the program covers it to 1213. This issue is in assets ant consumables only. Components, Accessories and Licenses is fine.
And Yes mandelbrotmedia is correct in Europe we use "," instead of "." to separate decimals (e.g. 12,13) but it is not an big issue for me.
I'd tried to switch snipe-it in varies languages but no positive effect.

My Snipe-it version 4.1.14. 
Fresh install on XAMPP
PHP Version | 7.1.11
Laravel Version | 5.4.35
Maria DB 10.1.28

**Comment by ginculia** [comment]
Looks like it is not an issue. It is just weird behavior because of bad installation and/or update. I just vanished off all installations of snipe it and did completely new install (including XAMPP also) and know everything is OK.

**Comment by balticer** [comment]
Hello,

i (still) have this issue also. Any solutions for this?

regards
Kai
