### ISSUE TITLE
Error 500 When Going to Admin > Backups

### ISSUE THREAD

**Issue by thejlowe** [snipe/snipe-it#4931]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here) **I would like to get my organization upgraded to the newest Snipe-IT so I am trying to do a backup first but get an Error 500. I didn't install Snipe-IT for my workplace but am trying to pick up where someone else left off.** 

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Will be doing an upgrade soon
- Version of Snipe-IT you're running: **v3.6.6**
- Version of PHP you're running **5.6.15**
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on **Windows Server 2012 R2**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **I didn't install Snipe-IT, how could I tell?**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: **Admin > Backups**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by chibacityblues** [comment]
> WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No one will be able to help without doing this.

**Comment by thejlowe** [comment]
Glad you said that because I was struggling with this when reading other tickets. How exactly would I turn this on?

**Comment by thejlowe** [comment]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>

    <head>
        <link rel="stylesheet" type="text/css" href="ErrorPageTemplate.css" >

        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

        <title>HTTP 500 Internal Server Error</title>

        <script src="errorPageStrings.js" language="javascript" type="text/javascript">
        </script>
        <script src="httpErrorPagesScripts.js" language="javascript" type="text/javascript">
        </script>
    </head>

    <body onLoad="javascript:expandCollapse('infoBlockID', true); initGoBack(); navCancelInit(); initMoreInfo('infoBlockID');">

        <table width="730" cellpadding="0" cellspacing="0" border="0">

        
            <tr>
                <td id="infoIconAlign" width="60" align="left" valign="top" rowspan="2">
                    <img src="info_48.png" id="infoIcon" alt="Info icon">
                </td>
                <td id="mainTitleAlign" valign="middle" align="left" width="*">
                    <h1 id="mainTitle">The website cannot display the page</h1>
                </td>
            </tr>



            <tr>
                
                <td id="http500Align" class="errorCodeAndDivider" align="right"><ID id="http500">&nbsp;HTTP 500</ID>
                    <div class="divider"></div>
                </td>
            </tr>


        
            <tr>
                <td>
                    &nbsp;
                </td>
                <td id="likelyCausesAlign" valign="top" align="left">
                    <h3 id="likelyCauses">Most likely causes:</h3>
                    <ul>
                        <li id="causeSiteMaintenance">The website is under maintenance.</li>
                        <li id="causeSiteError">The website has a programming error.</li>
                    </ul>
                </td>
            </tr>

        
            <tr>
                <td>
                    &nbsp;
                </td>
                <td id="whatToTryAlign" valign="top" align="left">
                    <h2 id="whatToTry">What you can try:</h2>
                </td>
            </tr>

        
            <tr>
                <td>
                    &nbsp;
                </td>
                <td id="refreshPageAlign" align="left" valign="middle">
                    <h4>
                        <table>
                          <tr>
                              <td valign="top">
                                  <img src="bullet.png" border="0" alt="" class="actionIcon">
                              </td>
                              <td valign="top">
                                  <span id="navCancelContainer"></span><noscript id="refreshPage">Refresh the page.</noscript>
                              </td>
                          </tr>
                        </table>
                    </h4>
                </td>
            </tr>


        
            <tr>
                <td >
                    &nbsp;
                </td>
                <td id="goBackAlign" align="left" valign="middle">
                    <h4>
                        <table>
                          <tr>
                              <td valign="top">
                                  <img src="bullet.png" border="0" alt="" class="actionIcon">
                              </td>
                              <td valign="top">
                                  <span id="goBackContainer"></span><noscript id="goBack">Go back to the previous page.</noscript>
                              </td>
                          </tr>
                        </table>
                    </h4>
                </td>
            </tr>


        
            <tr>
                <td id="infoBlockAlign" align="right" valign="top">
                    &nbsp;
                </td>
                <td id="moreInfoAlign" align="left" valign="center">
                    <h4>
                        <table>
                            <tr>
                                <td valign="top">
                                    <a href="#" onclick="javascript:expandCollapse('infoBlockID', true); return false;"><img src="down.png" id="infoBlockIDImage" border="0" class="actionIcon" alt="More information"></a>
                                </td>
                                <td valign="top">
                                    <span id="moreInfoContainer"></span>
                                    <noscript><ID id="moreInformation">More information</ID></noscript>
                                </td>
                            </tr>
                        </table>
                    </h4>

                    <div id="infoBlockID" class="infoBlock">
                        <p id="errorExplanation">This error (HTTP 500 Internal Server Error) means that the website you are visiting had a server problem which prevented  the webpage from displaying.</p>
                        <p id="moreInfoSeeHelp">For more information about HTTP errors, see Help.</p>
                    </div>

                </td>
            </tr>


        </table>
    </body>
</html>

**Comment by thejlowe** [comment]
Is that what is needed?

**Comment by snipe** [comment]
That’s a server level error,  not a Snipe-IT level error. Try checking your web server logs.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
