### ISSUE TITLE
File required for SSL, symlink not possible - could you explain reasoning?

### ISSUE THREAD

**Issue by delize** [snipe/snipe-it#4932]
#### Expected Behavior (or desired behavior if a feature request)
 Using a symlink to place the .crt file in the location that you have specified would allow the software to launch an SSL capable instance of the application.

-----

#### Actual Behavior
https://github.com/snipe/snipe-it/blob/master/docker/entrypoint.sh#L12-L17
```
if [ -f /var/lib/snipeit/ssl/snipeit-ssl.crt -a -f /var/lib/snipeit/ssl/snipeit-ssl.key ]
then
  a2enmod ssl
else
  a2dismod ssl
fi
```
Causes the check to fail because the "file" is a symlink and not a hard link/file. 

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

_Specifically related to docker instances_

This is not a bug issue, so much as it is an open call to understand why requiring the hard file is necessary. Usually you see the .crt file in `/etc/ssl/private` and then symlinked or specify the location in the config file from there. Which is what our company currently does. 

I have no issue opening up a PR, fixing it so that it doesn't require a hard file, but I would like to understand your reason for requiring the `-f` switch before I go about doing that. As I am struggling to understand the reason for that flag. As well as causing me many hours of pain trying to figure out why I couldn't get SSL enabled even though the file was in the proper location.

**Comment by delize** [comment]
@uberbrady Any idea why this is the case?

Otherwise, I will attempt a pull request to fix this feature.

**Comment by delize** [comment]
@uberbrady bump?

**Comment by uberbrady** [comment]
I don't think there's any good reason for 'requiring' that the existing entity be a file. I think I was just trying to do a naive "if this file exists" and inadvertently made it into "if this thing exists and is a file."

A PR fixing it sounds fine by me.

I know some people like to combine their key files and their cert files into one file, it'd be neat if we could support that too. But I'd be happy enough with just the "any type of file, not just a 'regular file'" fix alone, too.

**Comment by uberbrady** [comment]
I'm poking around on the Docker integration today, and I fear that the symlink thing might not even work. I'm worried that the symlink will be resolved relative to the *container*'s filesystem, not the host's. As such, it won't end up resolving correctly.

If you're on a POSIX system of some sort, a hard-link would work (and would correctly be read as a 'regular file').

If you get a chance to play around with this I'd love to hear how it ends up working out. I certainly agree that it 'feels' better to permit a symlink, perhaps to some wildcard cert that has a 'home' that is somewhere else on the system.

**Comment by delize** [comment]
It's now been too long since I remember how we were originally setting this up. But I can try to answer this the best way I was doing it.

I am not sure what you mean by doing mounted volumes is terrible and messy? 

Mounting volumes in a specific location, and then from there symlinking to the necessary directory/path is a preferred way of doing things when having to use files outside of the docker container. 

I think the `-a` would be fine, as long as it checks for a file that exists.

**Comment by uberbrady** [comment]
In my head I was thinking that the file lived on your Docker host machine, so, like - 

`docker_host:/etc/ssl/whatever`

But then, your container would do the volume mount thing - 

`snipeit:/var/lib/snipeit/ssl/snipeit-ssl.crt`

But if that were a symlink back to something at the `docker_host` level, then your symlink would break unless you also mounted the host drive somewhere? And I thought that seemed a little yucky.

So to be clear, I would imagine it looking like this:

Cert "for real" lives at `docker_host:/etc/ssl/whatever.crt`. Then we have to make the Snipe-IT storage container symlinks, which would be something like: `/var/lib/snipeit/ssl/snipeit-ssl.crt -> /mnt/etc/ssl/whatever.crt` - and then the last thing we'd have to do is also make sure that we mount the entire host's filesystem under `/mnt` in our snipeit container.

Does that make sense? If I am misunderstanding something, please let me know. To me, that particular solution seems a little weird, but if you think it's OK and is a common thing that people do - then maybe I just need to re-evaluate my thoughts on what 'yucky' means :)

Let me know, and I will certainly get those `-a` checks in there for you if that would work for you. (or you could give us a PR and I would approve it; depends on if you want to boost your open-source cred or not :) )
