### ISSUE TITLE
Creating an asset is assigned a location, where can I change it?

### ISSUE THREAD

**Issue by ado120** [snipe/snipe-it#4933]
#### Expected Behavior (or desired behavior if a feature request)

When creating an asset, I'd like to be able to choose and change the location of an item.
-----

#### Actual Behavior

Everytime I create an asset, it is assigned to a default location called "SCA IT Storage Room" I have no idea where to change this or where the setting is to change it to something else?
https://imgur.com/a/MtR5v

When I click on the asset and try to change the location, I only get the option to change the default location and not the location itself

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running? Version v4.1.10-pre - build 3185 (master)
- Version of PHP you're running? 7.1
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on? CentOS 7

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Location is inherited through assignment. It should also update based on default location when that’s edited and the asset is unassigned. Try updating your instance to the latest.

**Comment by ado120** [comment]
Hello snipe, 

So are you saying it is getting the location after it is assigned(checked out) to a user? If so, how can I change that? I can't seem to find the setting to set the location to something else after assignment to a user.

I will also try updating my instance.

**Comment by snipe** [comment]
You can’t. If it’s assigned, the location is that if whatever or whoever it’s assigned to. That’s by design.

**Comment by ado120** [comment]
Hello snipe,

I guess my question is, (if you look in my screenshot). The asset is assigned to Chris and got a location of SCA IT Storage Room. The thing is, where did it get the location then? From AD? I believe SCA IT Storage Room was something I manually put into Snipe..
