### ISSUE TITLE
Recent Activity shows oldest records first.  in 4.1.11

### ISSUE THREAD

**Issue by raakhtar** [snipe/snipe-it#4938]
In 4.1.11 the Recent activity on the dashboard started to show the oldest Records first, whereas it should show the latest created records at the top

**Comment by jbije** [comment]
same issue

**Comment by cslucian** [comment]
I have found the fix searching in the code

Inthe folder /resources/views

file "dashboard.blade.php" at line 170 "data-sort-order="desc" " set to "asc"


And now the recent activity works.

**Comment by snipe** [comment]
@cslucian that's incorrect. Ascending means oldest first, as smaller number are listed first when in ascending order, and earlier dates are smaller.
