### ISSUE TITLE
Feature Request - Import locations

### ISSUE THREAD

**Issue by busy86** [snipe/snipe-it#4940]
#### Expected Behavior (or desired behavior if a feature request)

It would be great if it were possible to just import locations. I don't have any asset data to import yet, but have 200 locations that I need to populate.
-----

#### Actual Behavior

Importer (GUI and cli) won't accept locations

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode **N/A**
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) **Yes**

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **fresh**
- Version of Snipe-IT you're running **14.1.11-pre**
- Version of PHP you're running **7.07**
- Version of MySQL/MariaDB you're running **15.01**
- What OS and web server you're running Snipe-IT on **SLES and Apache**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **git**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **N/A**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **import**
- If a stacktrace is provided in the error, include that too. **N/A**
- Any errors that appear in your browser's error console. **N/A**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. **can't import on the demo site**
- Include any additional information you can find in `storage/logs` and your webserver's logs. **N/A**
- Include what you've done so far in the installation, and if you got any error messages along the way. **N/A**
- Indicate whether or not you've manually edited any data directly in the database **no**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by viclou** [comment]
+++
