### ISSUE TITLE
 Import from CLI Yields: [ErrorException] Trying to get property of non-object

### ISSUE THREAD

**Issue by amg4110** [snipe/snipe-it#4942]
#### Expected Behavior (or desired behavior if a feature request)

Import is successful and all assets appear in the dashboard of the web GUI with proper fields (specifically "name" of user, which is supposed to be parsed as "firstname lastname")

-----

#### Actual Behavior

Import is not successful. I get the following error:
user@snipe:/var/www/inventory# php artisan snipe:import Revised_Assets_csv_list.csv --verbose
======= Importing Items from Revised_Assets_csv_list.csv =========
Found a match in our custom map: category is category
Custom Key: category
A matching category: Laptops already exists
Found a match in our custom map: company is company
Custom Key: company
Found a match in our custom map: location is location
Custom Key: location
Found a match in our custom map: manufacturer is manufacturer
Custom Key: manufacturer
Manufacturer Apple already exists
Found a match in our custom map: status is status
Custom Key: status
A matching Status Assigned already exists
Found a match in our custom map: supplier is supplier
Custom Key: supplier
Found a match in our custom map: item_name is item name
Custom Key: item name
Found a match in our custom map: notes is notes
Custom Key: notes
Found a match in our custom map: order_number is order number
Custom Key: order number
Found a match in our custom map: purchase_cost is purchase cost
Custom Key: purchase cost
Found a match in our custom map: purchase_date is purchase date
Custom Key: purchase date
Custom Key: quantity
Found a match in our custom map: requestable is requestable
Custom Key: requestable
Custom Key: serial
Found a match in our custom map: name is name
Custom Key: name
Found a match in our custom map: email is email
Custom Key: email
Found a match in our custom map: username is username
Custom Key: username
User Kim created
Found a match in our custom map: asset_tag is asset tag
Custom Key: asset tag
No Matching Asset, Creating a new one
Found a match in our custom map: image is image
Custom Key: image
Found a match in our custom map: warranty_months is warranty
Custom Key: warranty
Found a match in our custom map: asset_model is model name
Custom Key: model name
Found a match in our custom map: model_number is model number
Custom Key: model number
A matching model already exists, returning it.
Asset  with serial number  was created

In Loggable.php line 37:

  [ErrorException]
  Trying to get property of non-object

Exception trace:
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at /var/www/inventory/app/Models/Loggable.php:37
 App\Models\Asset->logCheckout() at /var/www/inventory/app/Models/Asset.php:191
 App\Models\Asset->checkOut() at /var/www/inventory/app/Importer/AssetImporter.php:117
 App\Importer\AssetImporter->createAssetIfNotExists() at /var/www/inventory/app/Importer/AssetImporter.php:42
 App\Importer\AssetImporter->handle() at /var/www/inventory/app/Importer/Importer.php:125
 App\Importer\Importer->App\Importer\{closure}() at /var/www/inventory/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:29
 Illuminate\Database\Connection->transaction() at /var/www/inventory/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:327
 Illuminate\Database\DatabaseManager->__call() at /var/www/inventory/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221
 Illuminate\Support\Facades\Facade::__callStatic() at /var/www/inventory/app/Importer/Importer.php:132
 App\Importer\Importer->import() at /var/www/inventory/app/Console/Commands/ObjectImportCommand.php:82
 App\Console\Commands\ObjectImportCommand->fire() at n/a:n/a
 call_user_func_array() at /var/www/inventory/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /var/www/inventory/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /var/www/inventory/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /var/www/inventory/vendor/laravel/framework/src/Illuminate/Container/Container.php:539
 Illuminate\Container\Container->call() at /var/www/inventory/vendor/laravel/framework/src/Illuminate/Console/Command.php:182
 Illuminate\Console\Command->execute() at /var/www/inventory/vendor/symfony/console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /var/www/inventory/vendor/laravel/framework/src/Illuminate/Console/Command.php:167
 Illuminate\Console\Command->run() at /var/www/inventory/vendor/symfony/console/Application.php:936
 Symfony\Component\Console\Application->doRunCommand() at /var/www/inventory/vendor/symfony/console/Application.php:240
 Symfony\Component\Console\Application->doRun() at /var/www/inventory/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/inventory/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122
 Illuminate\Foundation\Console\Kernel->handle() at /var/www/inventory/artisan:35

HOWEVER...if I change the header in the csv to "Full Name" rather than just "Name" and then run the import on this same csv again, it imports most everything except the "Name" and Serial. It's almost as if it's ignoring it, even though I'm pretty certain that I have the right syntax.

Here's what my csv headers look like:

![assets_csv](https://user-images.githubusercontent.com/7771109/35593448-ed69dd08-05dd-11e8-9a26-8b6c115c83f1.png)

I made sure that there were no trailing spaces at the end of the headers and I made sure that there were no blank lines at the end of the csv.
-----

#### Please confirm you have done the following before posting your bug report:

- [y] I have enabled debug mode 
- [y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh install
- Version of Snipe-IT you're running: v4.1.11-pre - build 3299 (master)
- Version of PHP you're running: PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
- Version of MySQL/MariaDB you're running: MySQL 5.6.37 
- What OS and web server you're running Snipe-IT on: Ubuntu 16.04 / Apache 2.4.18
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) git
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: N/A
- If a stacktrace is provided in the error, include that too.: Included above.
- Any errors that appear in your browser's error console.: N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.: N/A
- Include any additional information you can find in `storage/logs` and your webserver's logs.: Everything in here is the same info as posted above.
- Include what you've done so far in the installation, and if you got any error messages along the way.: Nothing out of the ordinary. The install is working fine and I am actually able to import csvs, just not with all of the fields that are expected.
- Indicate whether or not you've manually edited any data directly in the database: Other than truncate the snipe_assets table to clear the assets, no. 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by blackrandom** [comment]
I'm having the same issues, although I've gotten a few assets imported before it just doesn't seem to be working anymore.

**Comment by DudeNamedBenFranklin** [comment]
As am I

**Comment by DudeNamedBenFranklin** [comment]
Oh, I didn't realize that if you are going to use the script to auto generate first/last/and/e-mail you need to call the header row on the name column "FULL NAME" 

Changed mine from "name" to "Full Name" and it worked.

**Comment by blackrandom** [comment]
I tried changing it to Full Name too but it doesn't checkout the device and does not import the serial number to the device.

**Comment by DudeNamedBenFranklin** [comment]
You are correct, on 2nd look it doesn't check out or attach serial.

**Comment by blackrandom** [comment]
Looks like it will take the serial if you change the header 'Serial number' to just 'Serial' but I still can't get the 'Full Name' header to work. I get the errors above with 'Full Name' and it ignores the data when I change it to 'Name'

**Comment by blackrandom** [comment]
Okay so I tried something out not sure if you guys will get the same results or not. I think the issue has to do with the outgoing mail settings in the .env file. It's trying to send an outgoing checkout notification but fails to authenticate and produces the error above. Here's my modified settings working with gmail:

MAIL_DRIVER=log
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=email@contoso.org
MAIL_PASSWORD=YOURPASSWORD
MAIL_ENCRYPTION=TLS
MAIL_FROM_ADDR=email@contoso.org
MAIL_FROM_NAME='IT Dept.'
MAIL_REPLYTO_ADDR=email@contoso.org
MAIL_REPLYTO_NAME='IT Dept.'

I just changed MAIL_DRIVER from 'smtp' to 'log' as shown above, that way I wouldn't have to re-enter my settings again. This stops it from sending it to an outgoing email address. I don't want to send mass emails when I'm trying to import and checkout assets to the users so this works for me. Please let me know if you guys have any questions as this seems to have cleared up my issues. Don't forget to run "php artisan config:clear" and restart the service so it applies the .env changes.

**Comment by tekkitan** [comment]
This issue seems to have gotten hijacked (which seems to happen a lot around here) and the issue never was resolved. I am having this same problem that OP described all the same troubleshooting steps and everything. Any help would be appreciated...

**Comment by snipe** [comment]
@tekkitan - this issue was related to an older version. If you're still having problems with the current version, please provide a stack trace.

**Comment by tekkitan** [comment]
```/var/www/snipe-it# php artisan snipeit:import --update --verbose Assets_csv_list_snipeit-format.csv
======= Importing Items from Assets_csv_list_snipeit-format.csv =========
Custom Key: category
A matching category: Laptops already exists
Custom Key: company
Custom Key: location
Custom Key: manufacturer
Manufacturer Apple already exists
Custom Key: status
A matching Status Assigned already exists
Custom Key: supplier
Custom Key: item name
Custom Key: notes
Custom Key: order number
Custom Key: purchase cost
Custom Key: purchase date
Custom Key: quantity
Custom Key: requestable
Custom Key: serial
Custom Key: checkout type
Custom Key: full name
Custom Key: email
Custom Key: username
User does not appear to be an id with number: Kim R.  Continuing through our processes
User kr already exists
Custom Key: asset tag
Updating Asset
Custom Key: image
Custom Key: warranty
Custom Key: model name
Custom Key: model number
No Matching Model, Creating a new one
Asset Model Macbook Pro with model number  was created
Asset MacBook Pro Retina 15-inch with serial number  was created

In Loggable.php line 44:

  [ErrorException]
  Trying to get property of non-object


Exception trace:
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at /var/www/snipe-it/app/Models/Loggable.php:44
 App\Models\Asset->logCheckout() at /var/www/snipe-it/app/Models/Asset.php:249
 App\Models\Asset->checkOut() at /var/www/snipe-it/app/Importer/AssetImporter.php:117
 App\Importer\AssetImporter->createAssetIfNotExists() at /var/www/snipe-it/app/Importer/AssetImporter.php:41
 App\Importer\AssetImporter->handle() at /var/www/snipe-it/app/Importer/Importer.php:126
 App\Importer\Importer->App\Importer\{closure}() at /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:29
 Illuminate\Database\Connection->transaction() at /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:327
 Illuminate\Database\DatabaseManager->__call() at /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221
 Illuminate\Support\Facades\Facade::__callStatic() at /var/www/snipe-it/app/Importer/Importer.php:133
 App\Importer\Importer->import() at /var/www/snipe-it/app/Console/Commands/ObjectImportCommand.php:82
 App\Console\Commands\ObjectImportCommand->fire() at n/a:n/a
 call_user_func_array() at /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php:539
 Illuminate\Container\Container->call() at /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Command.php:182
 Illuminate\Console\Command->execute() at /var/www/snipe-it/vendor/symfony/console/Command/Command.php:251
 Symfony\Component\Console\Command\Command->run() at /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Command.php:167
 Illuminate\Console\Command->run() at /var/www/snipe-it/vendor/symfony/console/Application.php:946
 Symfony\Component\Console\Application->doRunCommand() at /var/www/snipe-it/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /var/www/snipe-it/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122
 Illuminate\Foundation\Console\Kernel->handle() at /var/www/snipe-it/artisan:35```

**Comment by ReignSol** [comment]
I have the same issue
