### ISSUE TITLE
Columns display look at he "screen"column attached

### ISSUE THREAD

**Issue by israeljacobsen** [snipe/snipe-it#4947]
#### Expected Behavior (or desired behavior if a feature request)

the data need to be more spread out

-----

#### Actual Behavior
in one column all the data shown in details above detail so every asset take triple the space

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? upgrade 
- Version of Snipe-IT you're running 4.1.11
- Version of PHP you're running  7.0.22
- Version of MySQL/MariaDB you're running MySQL 5.7.21
- What OS and web server you're running Snipe-IT on ubunto16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) git reet --hard then php upgrade.php
![screen](https://user-images.githubusercontent.com/28049544/35624790-b6cd3748-0698-11e8-9a44-816551d2cb38.JPG)

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Your best bet will be to hide the columns you don't need, which will make more screen real estate for your longer columns.
