### ISSUE TITLE
Feature Request: Display custom data on individual asset page

### ISSUE THREAD

**Issue by carlashley** [snipe/snipe-it#4948]
I use a software deployment system (munki) to manage the Mac hardware within my environment. Part of the management tools used includes [munkireport](https://github.com/munkireport/munkireport-php) (a dashboard that allows you to view various specific details about a device, including software installed, etc.
What I'd like to be able to do, is to include a custom data field on each asset page for a given model type that displays that information.

What I was thinking is that you could use keyword replacement techniques along with markdown (or other mechanism) that allow you to include information about the asset itself form snipe.

For example, a custom URL field that allows you to have a base URL plus the asset serial number:
```
[URL Text](http://example.org/foo?serial={asset_serial})
```
which would then result in the following displayed on the asset page:
```
URL Text
```
and the URL being `http://example.org/foo?serial=C0123456`

![example](https://user-images.githubusercontent.com/9841187/35650568-46a9842c-0728-11e8-8530-a1f0306d56c8.png)

**Comment by rodchristiansen** [comment]
Did you or snipe ever implement a solution for this @carlashley ?

**Comment by carlashley** [comment]
No we didn't. Not sure about Snipe-IT.
