### ISSUE TITLE
Menu item "Import" shown for users without access for doing import

### ISSUE THREAD

**Issue by johan162** [snipe/snipe-it#4949]
#### Expected Behavior (or desired behavior if a feature request)

For users without admin rights the menu item "Import" should not be visible.

-----

#### Actual Behavior
In the left hand menu the item "Import" is shown even for users without sufficient rights. Clicking on "Import"  results in a "403 - Forbidden" for such a user

The menu item shouldn't be shown at all.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
**Fresh install**

- Version of Snipe-IT you're running
**v4.1.7 - build 3031** 

- Version of PHP you're running
- Version of MySQL/MariaDB you're running

- What OS and web server you're running Snipe-IT on
**Linux**

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
**Docker**

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
**"/import"**

- Indicate whether or not you've manually edited any data directly in the database
**No**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by chaaza** [comment]
I have the same issue for admin. Only super admin can import. @snipe

**Comment by snipe** [comment]
I believe this has already been fixed in later releases.
