### ISSUE TITLE
Intervention \ Image \ Exception \ NotReadableException

### ISSUE THREAD

**Issue by ttorres91** [snipe/snipe-it#495]
I am getting a NotReadableException error whenever uploading an image file to an asset model while using SnipeIT v1.1 on Windows 7 IIS Server.  I have tried using both Imagemagick and GD image libraries but both return the same error code.  Any help with this would be greatly appreciated.  Thank you.

**Comment by ttorres91** [comment]
![capture](https://cloud.githubusercontent.com/assets/10871367/6068007/cf7a03e2-ad46-11e4-9345-d53726ea382a.PNG)

**Comment by snipe** [comment]
Please provide the information requested here: http://docs.snipeitapp.com/installation/getting_help.html

**Comment by snipe** [comment]
Hm. I see the same error on the demo but not on my local version. What version go PHP and Snipe-IT are you running?

**Comment by snipe** [comment]
I see what's happening here. Check that your `public/uploads` directory is writable by the web server, per step 4 of the docs: http://docs.snipeitapp.com/linuxosx/README.html

**Comment by ttorres91** [comment]
Thank you for the response.  I am running V5.6.5 of PHP,V1.1 of SnipeIT on Windows 7 IIS Server V6.1.  I just made a few changes to the permissions including allowing read/write permissions to all files/directories within snipe-it directory (only for testing purposes of course), but still no luck.

**Comment by snipe** [comment]
I honestly don't know then, to be honest. Does it happen with every image you try, or just one?

**Comment by ttorres91** [comment]
Yes I've tried multiple image types as well.  I may attempt running it on a Linux Apache server instead thanks for your help

**Comment by ttorres91** [comment]
I was able to get it working with Apache.  Thanks for the help!

**Comment by madd15** [comment]
I know I'm a bit late but the error is possibly because IIS doesn't have read access to `C:\Windows\Temp` 

IUSR requires read access to the folder above for the upload to work.

**Comment by snipe** [comment]
Ahh, good point, @madd15, thanks! (It's been a while since I've used IIS)

**Comment by ttorres91** [comment]
I was able to get it to work in IIS by granting read only access to the Windows Users group (Computer Name\Users).  Apparently granting IIS access alone is not enough for the Windows security model lol.  
Thanks again guys for all the help, my department is really excited about this app so we can get rid of all the spreadsheets we have.
