### ISSUE TITLE
After all installation and configuration I can't open Pre-flight in browser

### ISSUE THREAD

**Issue by earanaus** [snipe/snipe-it#4950]
Step by step I had install  all dependencies, make configuration, and generate my app key. By instruction now I will  see Pre-flight in my browser, but I see just  white window .

-----

#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode 
- [yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
fresh
- Version of Snipe-IT you're running
newest
- Version of PHP you're running
php 7.0
- Version of MySQL/MariaDB you're running
Mysql
- What OS and web server you're running Snipe-IT on
Linux Ubuntu 16.04 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh/manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
nothing (white window)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
(localhost or my host name)

- Include any additional information you can find in `storage/logs` and your webserver's logs.
folder empty

**Comment by snipe** [comment]
Please see the common issues page. https://snipe-it.readme.io/docs/common-issues

A blank/white page is usually a permissions issue on your storage directory and/or subdirectories.
