### ISSUE TITLE
"No matching records" when viewing specific custom status with 'Archived' type.

### ISSUE THREAD

**Issue by jjmuelle-bhk** [snipe/snipe-it#4952]
#### Expected Behavior (or desired behavior if a feature request)

I have status labels that are `Archived` type, like `Retired` , `Disposed`, `Donated`, etc.

I want to see all assets that have been disposed.

I go to that status label (either by going to `Settings` > `Status Labels` > `Disposed`, or by clicking on `Disposed` from the list of asset under `All Archived`) I get a list of all of the assets with the `Disposed` status.

-----

#### Actual Behavior

I can see all of these devices that have the `Archived` type when going to `Assets` > `All Archived`, but when I view a specific status label, like `Disposed`, I get `No matching records found` when there should be.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
**Upgrade**
- Version of Snipe-IT you're running
**v4.1.10 build 3249 (g8d3a214)**
- Version of PHP you're running
**7.0.22-0ubuntu0.16.04.1**
- Version of MySQL/MariaDB you're running
**10.0.33-MariaDB-0ubuntu0.16.04.1**
- What OS and web server you're running Snipe-IT on
**Ubuntu 16.04.3 LTS
Apache/2.4.18 (Ubuntu)**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
**git clone**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
**../hardware?status=Archived 
then clicking on any status label**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
**No.**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
**This can be replicated on the demo site. As of writing this, there are 50 assets with the 'Archived' status. When you go directly to that status, "No matching records found". https://demo.snipeitapp.com/statuslabels/3**
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
**No.**

**Comment by snipe** [comment]
This was caused by a logic bug in the new setting to "show archived assets in list all". When that setting is enabled, the status label drill down in the "All Archived" menu works as expected. When it's not enabled, it would show as empty. This fix is now on master.
