### ISSUE TITLE
Feature Request: Custom Fields common to all the assets

### ISSUE THREAD

**Issue by juanfont** [snipe/snipe-it#4956]
#### Expected Behavior (or desired behavior if a feature request)

Be able to declare custom fields that are common to all the assets (regardless of model). Or perhaps declare a Fieldset that is associated by default to all the models that are created.

-----

#### Actual Behavior

At this moment, when you create a custom field for an asset you have to assign it to a Fieldset and then assign this Fieldset to a specific asset model. This implies that if you have a custom field that is common to all the assets (e.g. service desk ticket id, mac address...) you have to manually associate it to the all the models - and do this process every time you add a new model.

-----

Thanks! :-)

Juan

**Comment by snipe** [comment]
Duplicate of #4261

**Comment by snipe** [comment]
Sorry, that’d not a duplicate. I misread. 

I’m not sure which would be better here - allowing “universal” fields or default fieldsets. My worry would be that exceptions would start to pile up for “universal” fields. For example, when someone first sets up their inventory system, the field “MAC address” gets set as a universal required field.... fast forward a year, when that person has decided that they want to track office furniture as well. That could get frustrating.

I think this is a good idea, I just want to be sure we execute it in a way that won’t screw people up as the way they use Snipe-IT grows and changes over time.

**Comment by juanfont** [comment]
Thanks!!

I reckon that it is up to the user to understand that if they define a "universal" field they will find it in all the assets.

(I totally support the idea of adding MAC addresses to chairs.)

**Comment by snipe** [comment]
Its definitely up to the user, but part of our job is always to make the user experience good, and that we accommodate for as many foreseeable use cases as possible. (Unlike many other open source projects, UX is pretty important to us). Many times, the feature itself isn’t that hard, but building it in a way that will make sense to the user is the challenge :)

**Comment by kejones999** [comment]
Hi Folks,

 I'm just in the progress of trying Snipe-IT out and had just got to the point of working out that my asset information had a "make" field that'd be nice to add universally to electronic assets but then thought I might not want to add that for all types of assets too!

 How about allowing custom models to specify multiple fieldsets ? If the fieldsets are uniquely named and handled, then it should theoretically mean people can add/remove fieldsets that can be applied across multiple models without necessary being applied to all. That seems simpler to make implement in the UX front.

Regards,

Keith

**Comment by juanfont** [comment]
Noooo :(

**Comment by llecerf** [comment]
Hi,

Is this feature ever going to be implemented (either that or the solution that kejones999 proposed) ? It would be really useful for the structure i'm working on.

Cheers,

Louis

**Comment by denhyde** [comment]
Hi. I have created 12 custom fields that should be applicable to all assets without exception. E.g. default owner, funding body, account code, date disposed of, method of disposal etc. Do I manually add these 12 custom fields to every single model? Wouldn't it be easier to create a custom fieldset and add it by default to all assets or at least allow multiple custom fieldsets for each model? This functionality is really needed.

**Comment by snipe** [comment]
> Do I manually add these 12 custom fields to every single model?

Yes, you can do that very easily via the Bulk Edit on Asset Models.

**Comment by llecerf** [comment]
Would it be possible to add global custom fields or multiple fieldsets per asset model in the future ?

**Comment by pvnick** [comment]
In our organization we defined a "Universal Fieldset" which has custom fields that should be common to all models, and added a database trigger that automatically associates that fieldset with new models that get created without being associated with a fieldset:

`/* this allows automatically setting the fieldset to the universal fieldset on model creation. allows for universal custom fields */

DELIMITER ;;
CREATE TRIGGER
    set_default_fieldset
BEFORE INSERT
    ON models FOR EACH ROW IF NEW.fieldset_id is null THEN
        SET NEW.fieldset_id = (
            select id from custom_fieldsets where name = 'Universal Fieldset (do not delete)'
        );
    END IF ;;
DELIMITER ;
`

**Comment by lucidheart** [comment]
It's too bad this is closed and never received attention.  This actually is a deal breaker for me when I was evaluating whether to use the SaaS from snipe IT.   I need to add "account numbers" to make this software also work for our accounting department.  It makes no sense to duplicate the efforts of tracking and the financial aspects with two different pieces of software.  So I was looking to add the fields necessary for accounting to all assets.

The system is too complex to make this work for us.

**Comment by Timetrapper** [comment]
This is a feature we're looking for as well. My organization has already integrated SNIPE-IT in our logistics. But for reporting purposes all are assets fall into one of three groups. We'd like to be able to select which group a model belongs to whenever a new model is created.

**Comment by siliconghost** [comment]
I'm pretty amazed that this isn't a feature already implemented. It seems like an absolute requirement for us to be able to add custom fields that apply to any and all assets without having to jump through hoops to do it through some other way that seems like a hack.

**Comment by have-no-clue-what-im-doing** [comment]
Yeah, it's not deal breaker for me. But it would make life so much easier if there was just a way to set custom fields that apply to all assets by default.

**Comment by snipe** [comment]
You can use the Asset Model bulk edit to change the field sets associated with all of your models, which should speed things up quite a bit.

**Comment by have-no-clue-what-im-doing** [comment]
Oh wow, didn't see that before. Thanks!

**Comment by Karl-at-Work** [comment]
edit: It's already possible to add fieldsets when creating models via the API.

I would love to have this feature. Today I've been working on the code for SnipeAgent and I can automatically upload data to custom fields "CPU, RAM, OS, MAC". But this only works on devices where the model already have the the fieldset applied. Meaning that I can't fully automate this with intune. (I would have to run it on all computers once, apply the fieldsets and then run it again) 

It would be cool to have universal custom fields, or being able to apply a fieldset to new models.
