### ISSUE TITLE
Feature Request - Sign out hardware

### ISSUE THREAD

**Issue by bjorntk** [snipe/snipe-it#4958]
#### Desired Behavior
I know this function is available when emailing users, but that is not something I am able to implement in our orginazation.

When we click "Checkout" on a asset it would be amazing if we could have the ability to let the user sign on the screen when they get the asset.
We have a helpdesk handling the assets, so then we could just have a surface there handling checkouts. 

Example: (just like when you get a package from the post office)
1. User comes to helpdesk to get the asset.
2. Helpdesk personell gets the asset and click "checkout" in Snipe-IT on a tablet.
3. Finds the user in Snipe-IT, and check a box with "User sign" (or similar).
4. Helpdesk personell hands the tablet to the user and the user can sign (with a pen on the touch screen).
5. User get the device.

We are experiencing that users don't handle the assets with respect, and I hope this could be a way to get them to understand that they are responsible for the assets.

Thanks for the great work you are doing with Snipe-IT! :)

**Comment by snipe** [comment]
I think there is an issue for this already - #3750
