### ISSUE TITLE
Can't find a standard database scheme

### ISSUE THREAD

**Issue by nioidai** [snipe/snipe-it#496]
Hi all, i just started using Linux since this week. so im kind of a newbie..
In the SnipeIT docs im at this step:

6) Seed the Database

Loading up the sample data will give you an idea of how this should look, how your info should be structured, etc. It only pre-loads a handful of items, so you won't have to spend an hour deleting sample data.

php artisan db:seed

If you run this command on a database that already has your own asset data in it, it will over-write your database. ALL of your data will be gone. NEVER run the db seeder on production after on your initial install.

so when i try to run php artisan db:seed i get the following output:

 [Illuminate\Database\QueryException]                                         
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.assets'   
  doesn't exist (SQL: truncate `assets`)                                       
                                         

I was wondering if there is a standard scheme for this? :)

**Comment by snipe** [comment]
Did you run the installer? Sounds like the base table migration was never run.

**Comment by nioidai** [comment]
wow, ur fast.


how do i do that?

**Comment by snipe** [comment]
Step 3 in the docs: http://docs.snipeitapp.com/linuxosx/README.html

**Comment by nioidai** [comment]
I'm going to check it brb! :)

**Comment by nioidai** [comment]
[Illuminate\Database\QueryException]                                         
  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'migrations'  
   already exists (SQL: create table `migrations` (`migration` varchar(255) n  
  ot null, `batch` int not null) default character set utf8 collate utf8_unic  
  ode_ci)

**Comment by nioidai** [comment]
thats what i get when i run the php artisan app:install

**Comment by snipe** [comment]
Please provide the information specified here: http://docs.snipeitapp.com/installation/getting_help.html

Can you tell me what you've done so far and any errors you ran into? 

The artisan install is what creates your tables for you, so unless something bombed out in the install, it should work. It sounds like the tables were created, but not all of them, as if it were interrupted halfway through. Can you drop the tables and re-run the installer?

**Comment by nioidai** [comment]
Hi, i'm sorry for this late responding. Just wanted to let you know that snipe it is up and running now. The problem was that the database already had a table. When i deleted the table the php artisan db:seed command functioned ^^

thanks for your help Snipe

**Comment by snipe** [comment]
Thanks so much for letting us know!  Glad it's all sorted now.
