### ISSUE TITLE
Mobile view truncating maintenance view of asset

### ISSUE THREAD

**Issue by billbr23** [snipe/snipe-it#4961]
#### Expected Behavior (or desired behavior if a feature request)

Maintenance tab for asset when viewed on mobile should allow left to right scrolling to view full maintenance information.

-----

#### Actual Behavior

Currently maintenance tab is truncated and cut off when viewed on a mobile device.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  fresh
- Version of Snipe-IT you're running  v4.1.10 build 3249 (g8d3a214) 
- Version of PHP you're running  7.0.27
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Can you provide screenshots, and more information about what mobile browser you're using?
