### ISSUE TITLE
Feature request: reject button for requests

### ISSUE THREAD

**Issue by Zorlin** [snipe/snipe-it#4963]
#### Expected Behavior (or desired behavior if a feature request)

When looking at the Requested Assets page (for avoidance of doubt - http://foo.com/hardware/requested ) there should be an option to reject or delete an Asset Request.

-----

#### Actual Behavior

There is not a reject option.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running - v4.1.11-pre - build 3307 (master)
- Version of PHP you're running - PHP 5.6.33-1+ubuntu16.04.1+deb.sury.org+1
- Version of MySQL/MariaDB you're running - mysqld  Ver 5.7.21-0ubuntu0.16.04.1 for Linux on x86_64 ((Ubuntu))
- What OS and web server you're running Snipe-IT on - Google Chrome latest stable, nginx + php5.6-fpm
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - git
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - /hardware/requested
- If a stacktrace is provided in the error, include that too. - N/A
- Any errors that appear in your browser's error console. - N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo - yes
- Include any additional information you can find in `storage/logs` and your webserver's logs. - N/A
- Include what you've done so far in the installation, and if you got any error messages along the way. - N/A
- Indicate whether or not you've manually edited any data directly in the database - No, have not

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by chzaid** [comment]
This is a must have feature. i second to request   this feature.

**Comment by Zorlin** [comment]
Still a must have

**Comment by GeoLiefery** [comment]
Agree - **a must have**

**Comment by Zorlin** [comment]
This is still super important to us.

**Comment by Zorlin** [comment]
Yes, this is still relevant.

**Comment by Paralda** [comment]
Yes this is important

**Comment by CTNC** [comment]
This issue is still important! Please re-open

**Comment by bricekh2** [comment]
REOPEN!

**Comment by cookierun22** [comment]
Hi, may  I know is this request is possible to be done? Please reopen the request

**Comment by Zorlin** [comment]
I've changed jobs like 3 times since originally making this request. Anywhere I'd seriously consider implementing Snipe-IT would basically require this feature if it was to be at all user-facing. 100% still needed.
