### ISSUE TITLE
Login Link points to local IP

### ISSUE THREAD

**Issue by theoc131** [snipe/snipe-it#4964]
#### Expected Behavior (or desired behavior if a feature request)
Expected to login successfully http://asset.xxx.xxx.com/asset/login using the domain name rother than IP.
I am able to view the login screen but when I am directed to the local IP and receive Error: Your form session has expired. Please try again. 
(what you expect to happen goes here)
#### Actual Behavior
The system redirects to login to http://10.0.1.20/asset/public/login and receive an error  Error: Your form session has expired. Please try again. 
I use also reverse proxy and dont seem to receive any errors
(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade
- Version of Snipe-IT you're running
v4.1.9 build 3128 (ge5a7e66)
- Version of PHP you're running
7.0.10
- Version of MySQL/MariaDB you're running
Mysql
- What OS and web server you're running Snipe-IT on
Windows 2008 R2 Server, WAMP , Apache 2.4.23 and also using reverse proxy
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual Install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by CronKz** [comment]
Does the line `APP_URL=` in .env File match "http://asset.xxx.xxx.com"?
Ensure that in your Apache Config the Servername is also set to "asset.xxx.xxx.com".

**Comment by theoc131** [comment]
Does the line APP_URL= in .env File match "http://asset.xxx.xxx.com"?
Yes the .env file has the domain name. It is very strange because  I can see the Login page by entering the host name on the web browser, but If I hover my mouse over the login button, it points to the local IP address. This must be within the snipe it, rather than the reverse proxy setup, right? 
![capture](https://user-images.githubusercontent.com/36155139/35804961-d88eb032-0a71-11e8-808f-88fd631fbb70.PNG)

**Comment by snipe** [comment]
When we see this (assuming you’ve cleared your config cache), it’s usually due to the reverse proxy.  Have you looked at the [documentation on using a reverse proxy](https://snipe-it.readme.io/docs/reverse-proxies)? 

Another quick note though, your URL should never have `public` in it. That can cause some issues. If you’re using Snipe-IT in a sub directory (versus TLD or sub domain, which tends to go smoother), make sure you have the [correct alias](https://snipe-it.readme.io/docs/subdirectories) set up in your web server’s virtual host config.

**Comment by theoc131** [comment]
I have moved from sub directory to sub domain and also I have added 
ProxyPreserveHost On on the apache server and that seemed to fixed the issue.
I am a happy man. Thank you for your help!
