### ISSUE TITLE
Check-in/out script? 

### ISSUE THREAD

**Issue by mlozevski** [snipe/snipe-it#4967]
Is it possible to have snipe-it run a script every time an asset is checked-in/out?

- Version of Snipe-IT you're running
v4.1.10
- Version of PHP you're running
7.1.9
- Version of MySQL/MariaDB you're running
5.7.19
- What OS and web server you're running Snipe-IT on
Win Server 2012 and Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual

**Comment by snipe** [comment]
That's not currently possible at this time.

**Comment by snazy2000** [comment]
Would be nice to be able to send a post request to another website or run a script to then be able to do that as well
