### ISSUE TITLE
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'remember_token' 

### ISSUE THREAD

**Issue by TylerH22** [snipe/snipe-it#4969]
#### Please confirm you have done the following before posting your bug report:

- [Yes] I have enabled debug mode 
- [Yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh install
- Version of Snipe-IT you're running - Not sure which version.  I installed Git and ran the following command: git clone https://github.com/snipe/snipe-it
- Version of PHP you're running - 5.6.33
- Version of MySQL/MariaDB you're running - MySQL Server 5.7
- What OS and web server you're running Snipe-IT on - Windows Server 2008 R2 and IIS
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

We are able to get the pre-flight & setup page to load.  However, when we click to go to the next page we get the "whoops, looks like something went wrong" error.

I turned on debug mode and tried again and I get the following error:  

(1/3) PDOException 

SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'remember_token'

(2/3) PDOException 

SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'remember_token'

(3/3) QueryException 

SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'remember_token' (SQL: alter table `users` add `remember_token` text null)

- Include what you've done so far in the installation, and if you got any error messages along the way. - 

I've successfully completed all of the steps in the installation steps.  Only errors I recall during the installation was when trying to generate the app key.  I forget what the exact error message is now but from doing some Googling I was able to mitigate the error by disabling the below 2 lines in my php.ini file.
    1. ;extension=php_pdo_oci.dll
    2. ;extension=php_pdo_firebird.dll

- Indicate whether or not you've manually edited any data directly in the database - No I have not

I have done lots of google searches and have found things that are very similar but haven't found anyone with this exact error.   Any help would be greatly appreciated.  

[Snipe-IT_Errors.txt](https://github.com/snipe/snipe-it/files/1696998/Snipe-IT_Errors.txt)

**Comment by snipe** [comment]
Snipe-IT requires PHP 45.6.4 or greater, per the [requirements](https://snipe-it.readme.io/docs/requirements).
