### ISSUE TITLE
How Do You Deal With Equipment That Has Been Disposed Of

### ISSUE THREAD

**Issue by FazzaGBR** [snipe/snipe-it#497]
When a computer has reached the end of it's life and you have to throw it away how do you deal with it with this software?

At the moment we have a large spreadsheet for our assets and when we dispose of any equipment we remove it from one tab and put it in one called 'Disposed Of' so it's still on record but not shown on our normal screen.  Can something similar be done with this software?

**Comment by madd15** [comment]
You could set a Status label that says 'Disposed Of' and set any that are disposed to that label

**Comment by snipe** [comment]
Yep, what @madd15 said :)
