### ISSUE TITLE
people list is empty but there are still users in snipe

### ISSUE THREAD

**Issue by kevinouw** [snipe/snipe-it#4975]
#### Expected Behavior (or desired behavior if a feature request)

To see a list of people that are in snipe at : "People"
-----

I have updated today to lasted version it seems that the list of people is not been showed.

(what actually happens goes here)

-----

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by kevinouw** [comment]
Snipe-IT version | v4.1.11-pre build 3307 (gf06852f)
-- | --
Software License | AGPL3
PHP Version | 7.0.22-0ubuntu0.16.04.1
Laravel Version | 5.4.29

Version is git the recommended
Install is the install.sh
No error in the browser
I have not edited any data in the database

**Comment by kevinouw** [comment]
we went from 

v4.0.10 | stable | Oct 16, 2017
-- | -- | --
to the V4.1.11 

The way we did it:
git pull
php upgrade.php

**Comment by kevinouw** [comment]
The search also does not display the people anymore

**Comment by snipe** [comment]
Without error logs, there's not going to be any way for us to troubleshoot this for you.

**Comment by kevinouw** [comment]
Oke is there a good why to place the back up back on new server then I just going for new install see if that works I tried to look it up the best way to do it but I could not find much info about it.

**Comment by snipe** [comment]
Rather than do that, why not just provide us with the logs that we're asking for?

**Comment by kevinouw** [comment]
[laravel-2018-02-15.log](https://github.com/snipe/snipe-it/files/1726691/laravel-2018-02-15.log)

**Comment by snipe** [comment]
Did you modify the user's table?

`Column not found: 1054 Unknown column 'users.address' in 'field list' (SQL: select `users`.`id`, `users`.`employee_num`, `users`.`two_factor_enrolled`, `users`.`jobtitle`, `users`.`email`, `users`.`phone`, `users`.`address`, `users`.`city`, `users`.`state`, `users`.`country`, `users`.`zip`, `users`.`username`, `users`.`location_id`, `users`.`manager_id`, `users`.`first_name`, `users`.`last_name`, `users`.`created_at`, `users`.`notes`, `users`.`company_id`, `users`.`last_login`, `users`.`deleted_at`, `users`.`department_id`, `users`.`activated`, `users`.`avatar`, (select count(*) from `assets` where `users`.`id` = `assets`.`assigned_to` and `assets`.`assigned_type` = App\Models\User) as `assets_count`, (select count(*) from `licenses` inner join `license_seats` on `licenses`.`id` = `license_seats`.`license_id` where `users`.`id` = `license_seats`.`assigned_to` and `licenses`.`deleted_at` is null) as `licenses_count`, (select count(*) from `accessories` inner join `accessories_users` on `accessories`.`id` = `accessories_users`.`accessory_id` where `users`.`id` = `accessories_users`.`assigned_to`) as `accessories_count`, (select count(*) from `consumables` inner join `consumables_users` on `consumables`.`id` = `consumables_users`.`consumable_id` where `users`.`id` = `consumables_users`.`assigned_to`) as `consumables_count` from `users` where `users`.`deleted_at` is null order by `first_name` desc limit 20 offset 0) `

**Comment by kevinouw** [comment]
I did not modify the user table.

**Comment by kevinouw** [comment]
I only have imported the usin the import in snipe the License Accessories and Asets but before the update all where working fine

**Comment by snipe** [comment]
Well somehow you address field in the users table is missing. What happens when you run `php artisan migrate`?

**Comment by kevinouw** [comment]
That seemsto have fixed it thank you so much!! :)

**Comment by bluenevus** [comment]
I'm having the same issue but when I try to do php artisan migrate it doesn't work.  It errors out because the imports table already exists.  What we did was do the export from the snipe-it utility.  I then imported using mysql.  I then went into the system and everything shows except users though the users are there given when exported, they show up on the spreadsheet

**Comment by snipe** [comment]
Hi there - Please create a new issue and fill in all of the questions in the new issue form. (When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.)

**Comment by XeusLEE** [comment]
FYI i had the exact same problem and its cause was search filter text was not empty :)
