### ISSUE TITLE
Snipe is asking for authentification 

### ISSUE THREAD

**Issue by pvhkai** [snipe/snipe-it#4978]
Hi Snipe,

after my last update (currently installed version: v4.1.11-pre build 3307 (gf06852f)) I we are facing a strange thing. Everytime I press on "People" I get an "Please Authentificate" window. I tried with my normal User / Service Account (LDAP) and with my local admin, but the windows pops up again. 

Is there anything where I can see what the script wants to get access to?

Thanks,
Kai
![screen shot 2018-02-07 at 8 34 47 am](https://user-images.githubusercontent.com/20946690/35904199-835e9a2e-0be2-11e8-93e3-9f605270ee6b.png)

**Comment by snipe** [comment]
There's nothing in our code that would do that. We don't use Basic Auth for anything.

**Comment by snipe** [comment]
What web server are you using? Is it possible there are configured urls specific to that?
