### ISSUE TITLE
sudo php artisan key:generate error

### ISSUE THREAD

**Issue by momaydopod** [snipe/snipe-it#4980]
I use CentOS 7 updated.

when i running `sudo php artisan key:generate`  have error below

Image
http://images.temppic.com/07-02-2018/images_vertis/1518003876_0.42367500.png

http://images.temppic.com/07-02-2018/images_vertis/1518003876_0.82538500.png

**Comment by GeoffYoung** [comment]
It looks like the backslash in your timezone ID should be a forward slash.
Try setting `APP_TIMEZONE='Asia/Bangkok'` in your `.env` file.

**Comment by momaydopod** [comment]
Thanks, I got key alredy , After that how to use key .

**Comment by snipe** [comment]
You should not be using sudo for ANY of the composer or artisan commands. Please see the install documentation.
