### ISSUE TITLE
SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'remember_token' 

### ISSUE THREAD

**Issue by TylerH22** [snipe/snipe-it#4983]
Please confirm you have done the following before posting your bug report:
•[Yes] I have enabled debug mode
•[Yes] I have read checked the Common Issues page

Provide answers to these questions:
•Is this a fresh install or an upgrade? Fresh install
•Version of Snipe-IT you're running - Not sure which version. I installed Git and ran the following command: git clone https://github.com/snipe/snipe-it
•Version of PHP you're running - 7.2
•Version of MySQL/MariaDB you're running - MySQL Server 5.7
•What OS and web server you're running Snipe-IT on - Windows Server 2008 R2 and IIS
•WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
•What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

We are able to get the pre-flight & setup page to load. However, when we click to go to the next page we get the "whoops, looks like something went wrong" error.

I turned on debug mode and tried again and I get the following error:

(1/3) PDOException

SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'remember_token'

(2/3) PDOException

SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'remember_token'

(3/3) QueryException

SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'remember_token' (SQL: alter table users add remember_token text null)
•Include what you've done so far in the installation, and if you got any error messages along the way. -

I've successfully completed all of the steps in the installation steps. Only errors I recall during the installation was when trying to generate the app key. I forget what the exact error message is now but from doing some Googling I was able to mitigate the error by disabling the below 2 lines in my php.ini file.
 1. ;extension=php_pdo_oci.dll
 2. ;extension=php_pdo_firebird.dll
•Indicate whether or not you've manually edited any data directly in the database - No I have not

I have done lots of google searches and have found things that are very similar but haven't found anyone with this exact error. Any help would be greatly appreciated.
[Snipe-IT_Errors.txt](https://github.com/snipe/snipe-it/files/1704907/Snipe-IT_Errors.txt)

**Comment by TylerH22** [comment]
Here are some additional screenshots that might be helpful:

![capture1](https://user-images.githubusercontent.com/36174267/35944605-eba72296-0c54-11e8-9884-f2987adfb436.PNG)
![capture2](https://user-images.githubusercontent.com/36174267/35944615-f3d71eda-0c54-11e8-8be8-afdbea0e3524.PNG)

**Comment by TylerH22** [comment]
I ran the "php artisan migrate:status" command and it appears to be failing on the following step:

2016_2_19_070119_add_remember_token_to_users_table

![capture3](https://user-images.githubusercontent.com/36174267/36034030-9887656a-0daa-11e8-9b59-096061feccfe.PNG)

**Comment by TylerH22** [comment]
So I went ahead and deleted and reinstalled everything on my web server and I now get the following error: Base table or view already exists: 1050 Table 'password_resets' already exists

Everything during the install seems to go perfectly until I get to this point.  It looks like I'm getting one step further than I was before as now when I run the "php artisan migrate:status" command it fails on
create_password_resets_table.
![capture5](https://user-images.githubusercontent.com/36174267/36045417-8cfab6b6-0dcd-11e8-8ea5-ead3cf26fb16.PNG)
![capture6](https://user-images.githubusercontent.com/36174267/36045418-8d1d58ce-0dcd-11e8-847c-2bf3e49d3eb4.PNG)

**Comment by snipe** [comment]
This doesn't really make sense though. The whole point of migrations is that they don't run twice, so you don't run into those "column/table already exists" errors. 

When you deleted and reinstalled everything, did you start with a fresh database as well? Seems like some tables might not have been deleted or something?

**Comment by TylerH22** [comment]
I was able to get this fixed yesterday!  I manually went in and deleted all of the tables and I was then able to migrate successfully.  Apparently not everything was getting deleted, although I’m not sure how since I completely removed MySQL from my machine and made a new database.

Thanks for reaching out,
Tyler

**Comment by snipe** [comment]
Awesome! Glad to hear you're all sorted. In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)

**Comment by JonathonReinhart** [comment]
FWIW I hit this just now.

- Click `Next: Create Database Tables`
- It took too long and I hit an NGINX `504 Gateway Timeout` error
- When I went back through the setup, I got a similar error:
  `SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'company_id' (SQL: alter table `action_logs` add `company_id` int null)`

Just trying to explain how this might happen.

**Comment by d3llconn** [comment]
> 
> 
> FWIW I hit this just now.
> 
>     * Click `Next: Create Database Tables`
> 
>     * It took too long and I hit an NGINX `504 Gateway Timeout` error
> 
>     * When I went back through the setup, I got a similar error:
>       `SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'company_id' (SQL: alter table `action_logs`add`company_id` int null)`
> 
> 
> Just trying to explain how this might happen.

I also get this error when trying to install snipe-it with docker container, it happen when first page of snipe-it web page (when installing) and click next to create database.  

SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'provider'

My solution is:
1. get into container bash 
`docker exec -it containerName bash`

2. login to mysql as root or snipe user
`mysql -uroot -h snipe-mysql -p `

3.  and then execute drop column to the duplicate column.
`alter table oauth_clients drop column `provider`; `

Hope this helps anybody that having headache when installing with docker.

**Comment by sellerie98** [comment]
I can confirm this issue in the same situation as @d3llconn. Their Workaround works for me too.

**Comment by blazer2x** [comment]
same issue with the latest docker image. using @d3llconn's solution fixed it

**Comment by JonathonReinhart** [comment]
I run an [`nginx-proxy`](https://github.com/nginx-proxy/nginx-proxy) container in front of my services, and mange everything with `docker-compose`.

To avoid the timeout in the first place, in my `docker-compose.yml` file, I have (among other things):
```yml
version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - ./nginx/custom-settings.conf:/etc/nginx/conf.d/custom-settings.conf:ro
      ...
    ...
  ...
```

**`nginx/custom-settings.conf`**
```
# JRR 2020-10-24
# Need this for initial DB creation...
# https://github.com/snipe/snipe-it/issues/4983#issuecomment-715667310
proxy_read_timeout 3600;
```

**Comment by jhgehrs** [comment]
> My solution is:
> 
>     1. get into container bash
>        `docker exec -it containerName bash`
> 
>     2. login to mysql as root or snipe user
>        `mysql -uroot -h snipe-mysql -p `
> 
>     3. and then execute drop column to the duplicate column.
>        `use databasename alter table oauth_clients drop column `provider`; `

thanks a lot for this! @d3llcon

But I have to mention, that i had to select the database first (my changes in **bold**):

3. and then execute drop column to the duplicate column.
**use databasename** alter table oauth_clients drop column `provider`;

**Comment by snipe** [comment]
@Godmartinz Can you please do a back-in-time migration to check if the column exists first? I don't know why this would be happening, but checking for the column first would circumvent this. HMU on slack if you have additional questions. Danke!

**Comment by snipe** [comment]
@d3llconn @jhgehrs latest on master checks for the provider column and makes a change to the field if it exists, creates it if it doesn't
