### ISSUE TITLE
Integrating Socialite for openAuth - how do I mimic the login process?

### ISSUE THREAD

**Issue by secureli** [snipe/snipe-it#4984]
#### Expected Behavior (or desired behavior if a feature request)

Hi there. I've fully integrated socialite into SnipeIT using https://laravel.com/docs/5.4/socialite, so I'm getting Google to hit back to a route I've set up. All of my users have e-mails that are the same as the usernames, and we want to openAuth them into SnipeIT.

I know this has been a well-requested feature, and I wish to submit a PR when I can get this resolved.

-----

#### Actual Behavior

I'm getting a blank page when Google redirects me back to the route. How do I mimic the behavior of the login process using Google's openAuth?

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----

**Comment by snipe** [comment]
Without seeing your code, I have no way of knowing what’s happening here.

**Comment by secureli** [comment]
LoginController.php: https://gist.github.com/secureli/6ec4ad6247c8420497edadb699a80969
web.php: https://gist.github.com/secureli/3dfc5c5474bcc3dde1f393c68b416ae2
app.php: https://gist.github.com/secureli/226e37145bad9a60cc1ecb7b7fbb308a

My 'google' environment variables for client_id, client_secret, and redirect (which is to /social/handle/google) as defined in my routes in web.php.

I'm simply getting the e-mail address back from Google and wish to log the user in via public function handleProviderCallback() (line 335) if an account already exists. I'm not familiar with Laravel and am unsure how to handle this data being pushed back to SnipeIT.
