### ISSUE TITLE
I following step install Snipe-It on CentOS7

### ISSUE THREAD

**Issue by momaydopod** [snipe/snipe-it#4985]
I following this https://www.vultr.com/docs/how-to-install-snipe-it-on-centos-7

when i try to access the web has error.

<img width="340" alt="2018-02-08 10_18_54-10 50 21 12 - vsphere client" src="https://user-images.githubusercontent.com/36228338/35954005-00d132b4-0cba-11e8-9242-e8d4ac4cd96d.png">
<img width="408" alt="2018-02-08 10_19_09-10 50 21 12 - vsphere client" src="https://user-images.githubusercontent.com/36228338/35954006-0133f7aa-0cba-11e8-8dd5-055617fa4538.png">
<img width="608" alt="2018-02-08 10_20_40-10 50 21 12 - vsphere client" src="https://user-images.githubusercontent.com/36228338/35954009-019ebf90-0cba-11e8-9ecb-408e1e327b4f.png">

**Comment by momaydopod** [comment]
After i open debug mode . It's showing
<img width="400" alt="2018-02-08 10_41_49-10 50 21 12 - vsphere client" src="https://user-images.githubusercontent.com/36228338/35954523-ca65deb6-0cbc-11e8-9a13-3912d7f93997.png">
<img width="401" alt="2018-02-08 10_42_00-10 50 21 12 - vsphere client" src="https://user-images.githubusercontent.com/36228338/35954524-cac5f99a-0cbc-11e8-9cbb-dc811d0410b6.png">
<img width="401" alt="2018-02-08 10_42_07-10 50 21 12 - vsphere client" src="https://user-images.githubusercontent.com/36228338/35954525-cb0edf5c-0cbc-11e8-98fb-8ad433851f71.png">
<img width="403" alt="2018-02-08 10_42_12-10 50 21 12 - vsphere client" src="https://user-images.githubusercontent.com/36228338/35954526-cb5b6eda-0cbc-11e8-8019-796fe18ea4fa.png">

**Comment by bishu05** [comment]
Just change the virtual host setting, here is my settings:



<VirtualHost *:80>
        ServerName localhost
        DocumentRoot /var/www/html


        <Directory /var/www/html/>
                AllowOverride All
                Options Indexes Multiviews FollowSymlinks
                Order allow,deny
                Allow from all
        </Directory>


# For Snipe-IT Asset management
Alias /snipe-it "/var/www/html/snipe-it/public"
        <Directory /var/www/html/snipe-it/public>
        Options Indexes FollowSymLinks
        AllowOverride All
        Order allow,deny
        allow from all
        Require all granted
        </Directory>
</VirtualHost>

**Comment by snipe** [comment]
@momaydopod according to the error message in the debug mode, the permissions are not set correctly on the storage directory. Please see the [install instructions](https://snipe-it.readme.io/docs/configuration#section-required-set-directory-permissions).
