### ISSUE TITLE
Feature | Add process field to an asset

### ISSUE THREAD

**Issue by rockthisworld** [snipe/snipe-it#4986]
Hi,

I'd would like to know if it is possible to add an extra field ("Process") when adding an asset. The purpose is that we want to know which assets is in use for which process of the company. 

We will use a self-hosted version. Before getting it in house I would like to fix this. 

-----
I tried the following in the DEMO:

By adding a custom field I wasnt able to fix this.  I'm not sure if thats the way you need to it. If yes, I may not be able to do it in right way. 

-----

- [ ] I have enabled debug mode 
- [ V ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----

**Comment by snipe** [comment]
Custom fields would be the correct solution here.
