### ISSUE TITLE
New asset category drop down empty

### ISSUE THREAD

**Issue by MikeVB13** [snipe/snipe-it#4987]
#### Expected Behavior (or desired behavior if a feature request)

**Brand new Snipe-It database, create new asset, assign category**

-----

#### Actual Behavior

**created new categories for new assets, while adding new asset no category selections display in the drop down.**

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Fresh install**
- Version of Snipe-IT you're running. **v4.1.11**
- Version of PHP you're running. **7.0.22-0ubuntu0.16.04.1**
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on. **Unbuntu LTS 16.04.3**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc). **install.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

There isn't any reason for those categories to be blank, so we need browser/app/server logs to see if there is a database issue that's happening that you can't see on the frontend. 

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by MikeVB13** [comment]
Issue Resolved. Thanks.
