### ISSUE TITLE
0000-00-00 00:00:00 timestamps in asset_logs table

### ISSUE THREAD

**Issue by poolski** [snipe/snipe-it#499]
When I try to check in/check out assets in v1.2.3, the `created_at` field in the `asset_logs` table gets set to `0000-00-00 00:00:00`. 

Any ideas?

**Comment by snipe** [comment]
I'll take a look. Way back when I created that table, I hadn't used the built-in time stamps, and 1.2.3 brought with it a migratin that renamed the (former) added_on table to created_at. It could be I left off a characteristic to make the timestaps work right. Weirdly though, I tested the checkin and checkout locally and it did give me timestamps as expected.

**Comment by poolski** [comment]
I upgraded from 1.2.2 and it stopped assigning timestamps, if that's of any help?

**Comment by snipe** [comment]
You ran the database migration from 1.2.2 to 1.2.3, right?

**Comment by poolski** [comment]
Yeah I ran
```
php composer.phar dump-autoload
php artisan migrate
```

**Comment by bondo05** [comment]
I'm having the same issue with 1.2.3 and I also ran the db migration process.

**Comment by snipe** [comment]
If you guys don't want to run a full-on update, you can just change line 9 in `app/models/Actionlog` from:

    public $timestamps = false;

to

    public $timestamps = true;

and that should fix it. It's already pushed out to develop.

**Comment by kobie-chasehansen** [comment]
Will changing from false to true fix any existing checkouts?

**Comment by madd15** [comment]
No
