### ISSUE TITLE
Changing asset model purges all data

### ISSUE THREAD

**Issue by ebonweaver** [snipe/snipe-it#4993]
#### Expected Behavior (or desired behavior if a feature request)

If you change the model of an asset (i.e. correcting a selection, cleaning up duplicates from mass import, etc), the other fields should not be in any way affected, UNLESS you choose a model that does not share the same fieldset, in which case any fields not in the new model would obviously be removed.

-----

#### Actual Behavior

All data is cleared in all fields and has to be re-entered

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade
- Version of Snipe-IT you're running
v4.1.9 build 3128 (ge5a7e66) 
- Version of PHP you're running
7.0.22-0ubuntu0.16.04.1
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Install.sh with manual updates
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
No, which is very curious as I don't see any mention of this in the release notes being fixed, unless it's just been fixed in the test version in the demo?
- Indicate whether or not you've manually edited any data directly in the database
No

**Comment by snipe** [comment]
I believe this was already fixed in https://github.com/snipe/snipe-it/pull/4866
