### ISSUE TITLE
Upgrade Issue v3 > v4

### ISSUE THREAD

**Issue by madmax01** [snipe/snipe-it#4995]
Hello,

i have an strange Issue and i don't find the Clue to fix it.

i fight since hours  to get the 3.6.6 installation to latest 4.x

i followed this instructions :  https://snipe-it.readme.io/docs/upgrading-to-v4

at the end once i done migration and the artisan up again > it's still pointing to the old installation.

i don't find the info how to point the new Installer in the 2nd folder to get it up.  DB migrated without issues

i pushed also this

php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan migrate
php artisan config:clear
php artisan config:cache

But no luck.  

what i'am doing wrong?

thx

Max

**Comment by snipe** [comment]
I'm not really sure I understand - do you have now two snipe-it folders, one with the old install and one with the upgraded version? If so, you probably just have to change your virtual host to point to the new one.
