### ISSUE TITLE
[Feature request] Restore function for backup files

### ISSUE THREAD

**Issue by kallaics** [snipe/snipe-it#4996]
#### Expected Behavior (or desired behavior if a feature request)

as a user who use the snipe-it in docker the import is a bit complicated. I would be happy if the software can manage the Restore function from any backups or uploaded backups.

- I would like to change name of Backup to Backup/Restore
- I would like to a new button before every "backup delete" button on backup screen in the settings and it can restore any backup to the system.
- I would like to Import button, where I can upload an old backups and it possible to import it now.   
Reason: If I am running the software on the could I haven't possibility to run exact command on my container and I don't want to create a more copies.

#### Actual Behavior

It have possibility only manually restore and I need to run some command manually.
On the cloud is still not possible at the moment on the fly.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install
- Version of Snipe-IT you're running
v4.1.10
- Version of PHP you're running
Deployed from you prepared Docker container (7.0.22-0ubuntu0.16.04.1)
- Version of MySQL/MariaDB you're running
Deployed from your guide: Mysql 5.6
- What OS and web server you're running Snipe-IT on
Deployed from your Docker container (Ubuntu 16.04)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
NO
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Not relevant, new feature
- If a stacktrace is provided in the error, include that too.
Not relevant, new feature
- Any errors that appear in your browser's error console.
Not relevant, new feature
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Not relevant, new feature
- Include any additional information you can find in `storage/logs` and your webserver's logs.
Not relevant, new feature
- Include what you've done so far in the installation, and if you got any error messages along the way.
Not relevant, new feature
- Indicate whether or not you've manually edited any data directly in the database
Not relevant, new feature, the database not touched.
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
This is unfortunately more complicated than it seems, especially as zip backups can have a wide variety of internal paths within the zip itself.

**Comment by kallaics** [comment]
I have another suggestions. I add my backup to special folder and I start my docker container with that and snipe-it can build up itself from scratch. How about it?

**Comment by santacruzlp** [comment]
> Eu tenho outra sugestão. Eu adiciono meu backup à pasta especial e inicio meu contêiner docker com isso e snipe-ele pode se construir do zero. Como sobre isso?

For me it worked like this:
#mysql -u root -p -h localhost snipeit_db <snipeit.sql
Then copy the folders:
config
public
storage
For the relevant folders.

Follow the url of reference:
https://stackoverflow.com/questions/17666249/how-to-import-an-sql-file-using-the-command-line-in-mysql

**Comment by dominikborkowski** [comment]
Being able to restore backup from the UI would be amazingly useful, even if it meant just restoring of the database portion. This would simplify restoring backups taken before imports, bulk updates, and other events that may affect large number of records. Another use case is ability to easily copy data between dev/test/prod instances.

Having it available from the UI would also make it easier for folks who use snipe-it running in containers or restricted services, where direct access to mysql client may not be feasible.

Thanks!
