### ISSUE TITLE
New email settings are not read from .env

### ISSUE THREAD

**Issue by jbloomer** [snipe/snipe-it#4997]
#### Expected Behavior (or desired behavior if a feature request)

I updated my mail settings in .env and restarted apache. New settings should be read

-----

#### Actual Behavior

Mail is still routing to old smtp server using old .env settings

Steralized copy of mail settings in .env

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=mycompany-com.mail.protection.outlook.com
#MAIL_PORT=25
MAIL_PORT=587
#MAIL_USERNAME=
#MAIL_PASSWORD=
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=departmentinventory@mycompany.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=department@mycompany.com
MAIL_REPLYTO_NAME=TEMS

Using TCPdump I can see the traffic is routed to an internal IP on our LAN for an internal SMTP server on port 25 that was previously configured. 

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? github install
- Version of Snipe-IT you're running 4.1.9 build 3128
- Version of PHP you're running 5.6.33
- Version of MySQL/MariaDB you're running Amazon Aurora RDS
- What OS and web server you're running Snipe-IT on CentOS 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by LukeTowers** [comment]
@jbloomer Did you run `php artisan config:clear`? https://snipe-it.readme.io/docs/configuration

**Comment by jbloomer** [comment]
I did not. I will try that now

**Comment by jbloomer** [comment]
ok, looks like that was the missing  step I needed. Thanks. It still doesnt work but I think that is a configuration problem on my end. I can see the traffic is at least being routed to the correct location.
