### ISSUE TITLE
Issues with NAXSI

### ISSUE THREAD

**Issue by cwhittl** [snipe/snipe-it#500]
First off I know this isn't going to be high on your list and I have a work around but thought you would want to know.

We are using a NGINX, PHP5.5, mySQL stack.
We are also using NAXSI (https://github.com/nbs-system/naxsi) to firewall issues with XSS and SQL injections for all our apps.

If I enable NAXSI, use the default rules, and turn off learning mode when I try to access snipe-it I get errors and a white page.

These are not generated by snipe-it but are from NAXSI having issues with snipe-it.

Here are the errors generated (scrubbed for obvious reasons)
>2015/02/09 15:41:27 [error] 8458#0: *37 NAXSI_FMT: ip=**IP REMOVED**&server=mydomain.com&uri=/assets/js/snipeit.js&learning=1&vers=0.52&total_processed=23&total_blocked=23&block=1&cscore0=$XSS&score0=16&zone0=HEADERS&id0=1315&var_name0=cookie, client: **IP REMOVED**, server: mydomain.com, request: "GET /assets/js/snipeit.js HTTP/1.1", host: "mydomain.com", referrer: "https://mydomain.com/"
2015/02/09 15:41:28 [error] 8458#0: *71 NAXSI_FMT: ip=**IP REMOVED**&server=mydomain.com&uri=/assets/img/datatables/sort_both.png&learning=1&vers=0.52&total_processed=24&total_blocked=24&block=1&cscore0=$XSS&score0=16&cscore1=$SQL&score1=4&zone0=HEADERS&id0=1315&var_name0=cookie&zone1=URL&id1=1000&var_name1=, client: **IP REMOVED**, server: mydomain.com, request: "GET /assets/img/datatables/sort_both.png HTTP/1.1", host: "mydomain.com", referrer: "https://mydomain.com/assets/css/lib/jquery.dataTables.css"
2015/02/09 15:41:28 [error] 8458#0: *71 NAXSI_FMT: ip=**IP REMOVED**&server=mydomain.com&uri=/assets/img/datatables/sort_asc.png&learning=1&vers=0.52&total_processed=25&total_blocked=25&block=1&cscore0=$XSS&score0=16&cscore1=$SQL&score1=4&zone0=HEADERS&id0=1315&var_name0=cookie&zone1=URL&id1=1000&var_name1=, client: **IP REMOVED**, server: mydomain.com, request: "GET /assets/img/datatables/sort_asc.png HTTP/1.1", host: "mydomain.com", referrer: "https://mydomain.com/assets/css/lib/jquery.dataTables.css"

Here is an explanation of the errors being reported from NAXSI https://github.com/nbs-system/naxsi/wiki/naxsilogs

Here is a link to the core_rules https://github.com/nbs-system/naxsi/blob/master/naxsi_config/naxsi_core.rules

I went ahead and made sure we were on the latest version of snipe-it because the issue started on the alpha but it's happening on the latest also.

Thanks again for an awesome application!

**Comment by snipe** [comment]
The latest version is actually 1.2.3, but it shouldn't matter. Is there any chance NAXSI updated something? Looks like all of those issues are with DataTables, and we haven't made any changes to DataTables in several versions. It looks like it thinks (erroneously) tat there is a potential SQL injection attack happening.


> 2015/02/09 15:41:28 [error] 8458#0: 71 NAXSI_FMT: ip=IP REMOVED&server=mydomain.com&uri=/assets/img/datatables/sort_asc.png&learning=1&vers=0.52&total_processed=25&total_blocked=25&block=1&cscore0=$XSS&score0=16&cscore1=$SQL&score1=4&zone0=HEADERS&id0=1315&var_name0=cookie&zone1=URL&id1=1000&var_name1=, client: *IP REMOVED**, server: mydomain.com, request: "GET /assets/img/datatables/sort_asc.png HTTP/1.1", host: "mydomain.com", referrer: "https://mydomain.com/assets/css/lib/jquery.dataTables.css"

In the rules:
>MainRule "rx:select|union|update|delete|insert|table|from|ascii|hex|unhex|drop" "msg:sql keywords" "mz:BODY|URL|ARGS|$HEADERS_VAR:Cookie" "s:$SQL:4" id:1000;

I'm not sure where it would be getting the other error (double-encoding), since there aren't even any GET or POST values being passed to the pngs and css files.
