### ISSUE TITLE
Feature Request: Mass-Checkin (analogue to Mass-Checkout)

### ISSUE THREAD

**Issue by kineese** [snipe/snipe-it#5000]
- Current version: v4.1.10 build 3249 
Currently there is a feature that you can checkout multiple assets at once.
Can you add the mass-checkin as well?

As usage example: We are giving out hardware to users who are going to a convention. At this point we simply use the mass-checkout function. When the person comes back we need to do the checkin individually.

**Comment by goludiaOH** [comment]
Agree - would love this feature.  Currently when an employee exits the company and we need to recover their assets, we have to check-in one by one.  Would be great to be able to mass check-in.

**Comment by snipe** [comment]
@goludiaOH The bulk checkin and delete in the users listing is made specifically for this. 

<img width="1026" alt="screen shot 2018-04-11 at 10 38 51 am" src="https://user-images.githubusercontent.com/197404/38633475-a4d8b270-3d74-11e8-810c-685d87aa43de.png">

**Comment by goludiaOH** [comment]
Thanks but I don't want to delete the user, I just want to check in all their assets.  We need to keep that user's history tracking in the tool for legal purposes for a while if they have exited the company.  Or if they are only able to check-in some portion of their assets, I'd like to check-in the ones they find and leave the others for disposition later.

**Comment by snipe** [comment]
@goludiaOH the users are soft-deleted for exactly that reason. Their history isn't removed, but they are pulled out of the "assignable" lists when you need to check things out to people.

**Comment by snipe** [comment]
> or solved by being able to accept assets through the snipe UI rather than email (would rather have that second option)

There are already a few tickets open for that

**Comment by goludiaOH** [comment]
> There are already a few tickets open for that
Yep, I've already +1'ed them :)

**Comment by Shane81** [comment]
I just wanted to comment, as I didn't follow up back in 2016 with #827 which is closed.

As a school I check-in and check-out about 300 (many schools do 1,000s) chromebooks to students. I used a user barcode (generated from their ID in the Library system) and the device Serial Number as the asset tag. I utilize a cheap Amazon purchased barcode scanner for these.

I generate the barcode in Word (Library system can make them...but they are ugly) and use a Free 3 of 9 font and Avery 5160 labels.

With our Library system (Koha Community) I just click "Check-In" and scan away on the barcodes. When I check-out you scan the users barcode and then scan the asset barcode. 

You appear to have the check-out process done, but the Bulk Check In & Delete isn't relevant for such a use. Once the units are checked in, I check and clean the units, note damage, put some aside for repairs, mark others as broken, create damages costs tickets, then I bulk check-out to the same students once more (just updating their due back date to June XX the following year).

The other reason it is important to get that done fast, I have 1 week before student leave for summer to verify my inventory and have the office and admins make calls about loss/damages. With the way the scanner works with our check-in process I can checkin every computer in the building in about 2 hours.

I hope I explained it clear...while I like the Library solution, it isn't designed to handle damages and repairs very well...your system is designed far better and has reporting...but it lacks that one crucial and massively time saving check-in/check-out that our Library system has...so I chose time over features.

**Comment by IMS-IT-Subscriptions** [comment]
Can this be revisited?  I really want this!

**Comment by hglasscock** [comment]
Bulk Checkin an option yet??

**Comment by mamayer** [comment]
See #6057
