### ISSUE TITLE
Feature Request - New asset: Option to add multiple assets of one model

### ISSUE THREAD

**Issue by xarly** [snipe/snipe-it#5006]
#### Expected Behavior (or desired behavior if a feature request)

When need to buy some assets, we buy several of them. For example monitors, each time we receive 10. Would be really time saving a option to select the model and write several serial numbers, creating an asset with same options for each SN at once.

-----

#### Actual Behavior

I could not find a way to do what I say, so each time you have to select:

Model
Status
Company
Supplier
....

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:
I am testing DEMO version

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running 4.1.11-pre - build 3307
- Version of PHP you're running 
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error https://demo.snipeitapp.com/hardware -> Create New
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. YES
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by Ombre007** [comment]
You can use the CSV import to do this. Create an excel sheet with your information, save it as a csv, change the delimiter to comma and you are good to go.
Here is a how to: https://snipe-it.readme.io/docs/importing

**Comment by xarly** [comment]
Thanks,
I see that option as a workaround, not a solution. 
With CSV many things can go wrong. First you have to take exactly from the web all the info, if you have a typo in the model the importer will create that model, etc

That's not a option for such high quality project. IMHO

**Comment by xarly** [comment]
A nice option would be add another button like:
![image](https://user-images.githubusercontent.com/152981/36261462-bda53f70-1264-11e8-9fcc-4be4f45d1ead.png)

**Comment by cepacs** [comment]
An add more would be a great option for times when you have between 3 an 10 and don't feel like going through the CSV way.  I created a small asset program years ago and that was one of the first enhancements people wanted too.. :)

**Comment by xarly** [comment]
Any comment or opinion from devs? :)

**Comment by snipe** [comment]
I think it's a good feature - just working through the UX

**Comment by Marlon-Wessel** [comment]
Would love to have this since most hardware is bought in batches so it shares most features (like optional and order related information) and differs in only serial number and asset tag. Like our company buys 10x Dell 16 Pro and 20x the same monitor.

**Comment by snipe** [comment]
@Marlon-Wessel I'd think your particular issue would be handled via the plus symbols, no?

https://github.com/user-attachments/assets/00bf6dd5-51f2-49b1-8501-2c24ae5bf287

**Comment by Marlon-Wessel** [comment]
You're right...
I genuinely didn't know this existed, sorry! 🤦‍♂️

**Comment by snipe** [comment]
@Marlon-Wessel No worries :) The plus shortcut on models was a newer addition (last few months) so you might not have it if you didn't update recently.
