### ISSUE TITLE
Add file upload functionality to REST API

### ISSUE THREAD

**Issue by andersziv** [snipe/snipe-it#5007]
#### Feature Request
It would be very nice to be able to upload files to assets through the REST API. Doesn't seem that difficult since the webpage-interface already have all the functionality needed.

**Comment by snipe** [comment]
I'd be willing to entertain a PR with this feature, but it's not a high priority for us right now. 

>  Doesn't seem that difficult since the webpage-interface already have all the functionality needed.

The webpage interface doesn't use the API for saving items, so it would still need to be built.
