### ISSUE TITLE
Updating Asset Not Working

### ISSUE THREAD

**Issue by mileper2nd** [snipe/snipe-it#5008]
#### Expected Behavior (or desired behavior if a feature request)

I want to update an asset and change some fields (serial number, asset tag).

-----

#### Actual Behavior

After I click the Save button, the page refresh itself and the initial values are restored. Also if I click the Back or Cancel button on Edit Asset Page, the page refresh itself and nothing happens.

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  UPGRADE
- Version of Snipe-IT you're running v4.1.11-pre - build 3307 (master)
- Version of PHP you're running 7.0.10
- Version of MySQL/MariaDB you're running MySql 5.7.14
- What OS and web server you're running Snipe-IT on Windows 7 and Wamp Server
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual in the beginning and just upgraded to Git Install.
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: I am on Asset Update Page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. NO, in demo editing is OK.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
[laravel.txt](https://github.com/snipe/snipe-it/files/1720677/laravel.txt)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database I do not edited manually.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
[2018-02-13 15:09:19] production.ERROR: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'log_meta' in 'field list' in C:\wamp\www\snipeit\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:77`

You have to run migrations.

`php artisan migrate`
