### ISSUE TITLE
Page not found 

### ISSUE THREAD

**Issue by chreichwein** [snipe/snipe-it#5009]
- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

- Is this a fresh install or an upgrade? Fresh install
- Version of Snipe-IT you're running:   snipe-it-4.1.10
- Version of PHP you're running: php-7.2.2
- Version of MySQL/MariaDB you're running: mariadb-10.2.12-winx64
- What OS and web server you're running Snipe-IT on: Windows Server 2012 R2 IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: Website not found HTTP 404
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: default site

- Include any additional information you can find in `storage/logs` and your webserver's logs.: Nothing special
-I did all the installation steps from the manual with no errors

I also read all the helpful topics and the common issues, I also installed the URL Rewrite to the IIS.
I build up everything from the scratch again, but still don't know why the site don't show up in the browser. 

Please help me.

**Comment by snipe** [comment]
You'd need to provide us with more information on your web server configuration before we can assist you. Screenshots would be preferred. I'm not sure what you missed in your install, and there's no way for us to figure that out without details of your specific installation.

**Comment by chreichwein** [comment]
Hi, I reinstalled PHP thru IIS Webplattform Installer and re-run composer. Now the Site loads with debug mode enabled. I get this error:

(3/3)                                         QueryException                                     SQLSTATE[HY000] [1044] Access denied for user 'snipe_user'@'localhost' to database 'snipeit' (SQL: select * from information_schema.tables where table_schema = snipeit and table_name = users)
--

I'am not so familiar with sql, could you tell me step by step what I need to do. I can understand that something with the rights is not working correct.

**Comment by chreichwein** [comment]
How ever there where 2 snipe_user in Heide SQL, 1 snipe_user had no db rights, so I deleted them. And now everything works. 
You should fix a lil' but your install manual for windows users.
1st failure I made, i downloaded php from the official website.
The solution was: Download/install php thru IIS Webplattform Installer and rund composer from this php.exe
