### ISSUE TITLE
Bug: False "Updated At" information being displayed for assets

### ISSUE THREAD

**Issue by lostmydog** [snipe/snipe-it#5010]
#### Expected Behavior (or desired behavior if a feature request)
Doing a full audit on our assets right now and have come across this a couple times. I am on:
Version v4.1.11-pre - build 3307 (master)

How my workflow has been throughout the audit has been: Type each asset in snipeit and verify it is checked out to the correct user, if not, assign to user/location. After I complete an entire room, I used the bulk audit feature to audit all assets in the room.
-----

#### Actual Behavior
After typing in an asset that has not been entered in the system yet (in this example 20332) I noticed that snipeit told me the item was updated, and only about an hour ago. I checked the history of the item to make sure I'm not crazy, and the history confirms that no change has happened since November when the item was first imported. Why is this item showing as updated? As you can see, the item has not had any changes nor has it been audited.

PICS FOR EXAMPLE:
https://imgur.com/a/CbaV0

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Those updated timestamps automatically update when the record changes in some way, we don't manually populate those anywhere, so I'm not sure what event might be triggering that time stamp update. We have a lot of de-normalized fields (for speed and searchability) that could potentially be the culprit, but I'm not sure. Can you look in the database table directly and see if the updated_at field matches the date in the updated field in the display? (Trying to determine if this is a data issue or a display issue.)

**Comment by snipe** [comment]
Huh. That's... curious. I can't seem to reproduce that at all. 

<img width="830" alt="ready_to_deploy_assets____snipe-it_demo 2" src="https://user-images.githubusercontent.com/197404/36177458-860724f2-10ca-11e8-970e-53f95c5207d5.png">

<img width="831" alt="view_asset_test_on_checkout____snipe-it_demo" src="https://user-images.githubusercontent.com/197404/36177462-8c14d470-10ca-11e8-983f-373c3603d5f5.png">

<img width="829" alt="view_asset_test_on_checkout_-_edited____snipe-it_demo" src="https://user-images.githubusercontent.com/197404/36177465-90758e6a-10ca-11e8-942c-138893d16b1b.png">

What do you have set in Settings > Localization for Date and Time Display? Does changing that affect anything in your asset view?

**Comment by lostmydog** [comment]
I have it set for the default, so thats: 2018-02-14. I changed it to several others but its still displaying wrong 'updated' date.

**Comment by snipe** [comment]
That's so bizarre. I'm honestly not even sure why or how that would be happening.

**Comment by lostmydog** [comment]
@snipe great news, I figured it out!! The reason "Updated at" is being updated is because I updated whomever the asset was checked out to's location! So if I assigned them a laptop on march 10th and then update their location on may 20th, the updated at is changing because the location of the item has changed since the user has since moved! I guess I could make a new thread, the next step would be a feature request to show that "User: Moved from room 105 to room 210" or something similar should show up in the history of the asset

**Comment by snipe** [comment]
Ah, excellent sleuthing!
