### ISSUE TITLE
Table Column Cookies are set to expire on browser close

### ISSUE THREAD

**Issue by mrlove72** [snipe/snipe-it#5014]
#### Expected Behavior (or desired behavior if a feature request)

When selecting/deselecting column preferences, the options set are stored in a cookie. When the browser closes, Snipe reads the cookie and restores column preferences.

-----

#### Actual Behavior

The cookie is set during the current browser session, but is set to expire once that browsing session ends. Upon closing and reopening any browser, the column preferences are reverted back to defaults.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Upgrade (3.6.2 -> 4.1.10)**
- Version of Snipe-IT you're running **v4.1.10**
- Version of PHP you're running **7.0.22-0ubuntu0.16.04.1**
- Version of MySQL/MariaDB you're running **MySQL 5.7.19**
- What OS and web server you're running Snipe-IT on **Ubuntu 16.04.3 / nginx/1.10.3**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Docker**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **No errors**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **Reproducible on any table that has modifiable columns** 
- If a stacktrace is provided in the error, include that too. **No errors**
- Any errors that appear in your browser's error console. **No errors**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. **Yes, reproducible on Demo page**
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database **No**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Screenshot of cookie in Google Chrome (Note expiry date at the bottom)** 
<img width="1401" alt="screen shot 2018-02-14 at 7 02 54 am" src="https://user-images.githubusercontent.com/36475426/36203605-181e22ec-1156-11e8-92e8-baed8cbf4a0f.png">

**Comment by snipe** [comment]
The expiration date is set to 2 years

**Comment by mrlove72** [comment]
Yes, that seems to be the expected behavior. However as you can see in my screenshot, the cookie that is set does not expire in two years. Rather, it expires once the browser session has ended.

**Comment by snipe** [comment]
I don't even see that cookie in my Chrome session. :-/

<img width="686" alt="screen shot 2018-02-14 at 7 26 44 am" src="https://user-images.githubusercontent.com/197404/36212670-67c2db46-1159-11e8-8ee2-c5ee068a79c1.png">

**Comment by mrlove72** [comment]
In my brief testing, it appears that the cookie is only set if you make a change to the columns.

For example, if you go to https://demo.snipeitapp.com/hardware and add/remove any of the options, the "hardware.index.bs.table.columns" cookie is then set. If you go to /users, the "users.index.bs.table.columns" cookie is set. It appears to set one for every table that is modified, all of which expire once the browser closes.

**Comment by snipe** [comment]
Yeah, I was testing locally by turning columns off and on. 

I did see [this](https://github.com/wenzhixin/bootstrap-table/commit/efa66f044a7fff314e5a3b542802ee72cd2c251c) issue in the bootstrap tables library, but I haven't seen others complaining about this on their repo.

**Comment by snipe** [comment]
Okay, I *think* I have this working locally. Still testing. Will check back.

**Comment by snipe** [comment]
<img width="675" alt="screen shot 2018-02-14 at 8 51 20 am" src="https://user-images.githubusercontent.com/197404/36216662-40de906e-1164-11e8-88ca-907c70957e68.png">

**Comment by mrlove72** [comment]
That's strange. I just got finished standing up a fresh install of the most recent build on a Vagrant box and  have the same table preferences problem.

Is there anything else I might be doing wrong?

![image](https://user-images.githubusercontent.com/36475426/36219954-0aff5c58-1187-11e8-9baa-33a898a6d8ec.png)

**Comment by snipe** [comment]
No, as I said, I almost have a fix for it. Was a bug in the JS library, I think
