### ISSUE TITLE
Feature Request: Update emails to use Laravel's Notifications system

### ISSUE THREAD

**Issue by fordster78** [snipe/snipe-it#5016]
As per the project.
To integrate the Laravel Notification system into snipe-it.
Below is an image of the test email that is now using the new system.
![image](https://user-images.githubusercontent.com/27958330/36222942-c5ef2e8e-11ba-11e8-89f9-e1a13fce5cee.png)

if anyone has any suggestions on what they would like implementing into the system. Pending @snipe's approval, I will have a look at adding it in once the main foundations are in place.
The email uses both the site name and any logo that you upload.

**Comment by fordster78** [comment]
Just an additional note to the above. I am also implementing Slack at the same time.

**Comment by snipe** [comment]
Awesome!!! I don't know if you're going to be monkeying around with the checkout methods or not (they're pretty messy right now, and I'd love to clean those up too), but if you HAPPEN to be poking around in there, I found another bug that relates to that.

Looks like checkout_at is no longer being honored. It’s updating the last_checkedout value in the asset, but the date in action_logs isn’t being reflected anymore. TBH, I’d prefer to add a field to the action_logs table, so we can still record the time the record was created, but reflect the checked out date as well.

If you're not poking around there, don't sweat it. I'll create another issue for it at some point.
