### ISSUE TITLE
Consumable Quantity, Total, and Remaining not seemingly lining up.

### ISSUE THREAD

**Issue by marcilla707** [snipe/snipe-it#5017]
#### Expected Behavior (or desired behavior if a feature request)

Trying to update quantities for Consumable items along with checkouts.

-----

#### Actual Behavior

Checkouts reduce Remaining quantity as expected, but trying to add more stock to an item does not seem to increase it properly. 

This issue was encountered on my installation, but just so you can look at the logs yourself and since the behavior is consistent with demo, I'm demonstrating the behavior on your demo server.

Sample item (on Demo server):

Item created, Qty 6, Min Qty 2:
Columns are as follows:
**Name / Category / Model No. / Item No. / Total / Remaining / Min. QTY**

![image](https://user-images.githubusercontent.com/36482926/36225627-22efaedc-1180-11e8-8a58-ed46fe87f430.png)

Checked out 1 item:
![image](https://user-images.githubusercontent.com/36482926/36225648-357574ba-1180-11e8-8183-1bc39d8763e6.png)

Checked out remaining stock:
![image](https://user-images.githubusercontent.com/36482926/36225705-587a4fda-1180-11e8-8898-147febc4e0b5.png)

Edited Quantity to 0 to match actual stock:
![image](https://user-images.githubusercontent.com/36482926/36225717-675aa18a-1180-11e8-8216-7e78539ef40e.png)

Result of Quantity edit:
![image](https://user-images.githubusercontent.com/36482926/36225730-726a3a40-1180-11e8-8600-e20a465cb9ca.png)

Edited Quantity to 10 (result):
![image](https://user-images.githubusercontent.com/36482926/36225773-99a74ec2-1180-11e8-8b80-dd2cb48e87be.png)

It seems like the total and remaining are separate variables and aren't quite behaving the way I expected them to. Not sure how I should be adding additional stock when we get more of any given consumable. I don't want to have to create multiple items for the same model. 

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
_Fresh Install_
- Version of Snipe-IT you're running
_v4.1.11-pre - build 3307 (master)_
- Version of PHP you're running
_PHP 7.2.1_
- Version of MySQL/MariaDB you're running
_10.1.30-MariaDB_
- What OS and web server you're running Snipe-IT on
_Win7, XAMPP 7.2.1-0_
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
_Composer install_
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
_../consumables_
- If a stacktrace is provided in the error, include that too.
N/A
- Any errors that appear in your browser's error console.
_No errors_
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
_Behavior is the same on demo (just did it with the Cardstock)_
- Include any additional information you can find in `storage/logs` and your webserver's logs.
N/A
- Include what you've done so far in the installation, and if you got any error messages along the way.
_Created consumable. Checked out all stock until 0. Updated Quantity to 0 to match, went into negative. Added Quantity which adjusts both Total and Remaining, but these values do not match._
- Indicate whether or not you've manually edited any data directly in the database
_No_

Is this the intended functionality and behavior for consumables (like if we should be adding stock via purchase orders or something)? In any case, the behavior appears to be consistent with the demo.

How am I supposed to add quantity to a consumable when we deplete and resupply a given item (eg: toner)? Deleting depleted items and adding new items for the exact same product seems odd to me, unless that's how it's supposed to work.... 

Please advise. Thanks in advance!

**Comment by Arapacana** [comment]
uhh, not stale; this is still happening and makes tracking consumables essentially impossible, because the "remaining" count seems to be generated by subtracting the TOTAL ACCUMULATED "checked-out" quantity from whatever the current total is.  Since you can't check-in a consumable, if you EVER check out a consumable, the Remaining quantity will always subtract that from the Total... which means you end up generating false alerts for low stock.  Cumulatively adding stock to the Total seems counterintuitive -- the Total shouldn't be a historical, cumulative number, but a momentary total.

**Comment by jconklin92** [comment]
> uhh, not stale; this is still happening and makes tracking consumables essentially impossible, because the "remaining" count seems to be generated by subtracting the TOTAL ACCUMULATED "checked-out" quantity from whatever the current total is. Since you can't check-in a consumable, if you EVER check out a consumable, the Remaining quantity will always subtract that from the Total... which means you end up generating false alerts for low stock. Cumulatively adding stock to the Total seems counterintuitive -- the Total shouldn't be a historical, cumulative number, but a momentary total.

100% agree with this.
