### ISSUE TITLE
Upgrading when using docker-compose

### ISSUE THREAD

**Issue by chiva** [snipe/snipe-it#5024]
I have been running snipeit from a docker-compose file for several months without any issues, but everytime I upgrade the version I'm afraid that there can be a database schema modification and the one I'm running is not updated to follow these changes.

Is it necessary to run any upgrade script when using snipeit with docker-compose to keep up to date the database schema?

I have reviewed the upgrade manual form here:
https://snipe-it.readme.io/docs/upgrading

The Git upgrade path fails due to not being able to run the `upgrade.php` file as `root`.
The manual upgrade path tells me there is nothing to upgrade when running `php artisan migrate`.

For the time being I just do the following:

- `$ docker-compose down`
- Modify the tag version at the `docker-compose.yml`
- `$ docker-compose up -d`

Is this correct? Should I run any migration/upgrading script to keep the database schema up to date?

Thanks

**Comment by uberbrady** [comment]
Yes, you should be running migrations after every update. There haven't been a lot of schema changes in the past few months which is probably why you're not seeing anything change when you run `php artisan migrate`.
