### ISSUE TITLE
Filtering issue with Special Characters

### ISSUE THREAD

**Issue by cepacs** [snipe/snipe-it#5025]
#### Expected Behavior (or desired behavior if a feature request)

Under Assets I wanted to filter for the string O&M or Mike's

-----

#### Actual Behavior

When I type in O&M in the filter box I get no results.
![image](https://user-images.githubusercontent.com/36515590/36274062-8bbf940c-1254-11e8-8015-0f2534df49e4.png)

If I only type O& I do get results
![image](https://user-images.githubusercontent.com/36515590/36274099-a6aa3c0e-1254-11e8-84db-ccd2bd897165.png)

Same with Mike's if I search for Mike I see results but Mike' gets no results..
![image](https://user-images.githubusercontent.com/36515590/36274308-4929382c-1255-11e8-8f4e-2fb64b83e88f.png)

![image](https://user-images.githubusercontent.com/36515590/36274327-5ad67d96-1255-11e8-84f9-d368d77d6460.png)

Just wondering if special characters are not being escaped during the search maybe or if this is by design.  I test this with imported records and records created within the website and got the same results.

Thanks :)
-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode **Though I am not getting any errors**
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Fresh**
- Version of Snipe-IT you're running **Version v4.1.11-pre - build 3299 (master)**
- Version of PHP you're running **PHP version: 7.1.14 **
- Version of MySQL/MariaDB you're running **Server version: 5.7.21**
- What OS and web server you're running Snipe-IT on **Windows Server 2016 / IIS**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **git clone https://github.com/snipe/snipe-it  C:/inetpub/wwwroot/snipe-it**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by cepacs** [comment]
Just wanted to add to this.. I just popped into the tables to take a look and I see that after my import my O&M had populated in the locations table as "O&amp;M", instead of just "O&M".  I updated the location from the GUI and then check and it updated to "O&M". 

I updated the Asset names for the "Mike's" through the GUI and it went from "Mike&#039;s" to "Mike's" like normal.

I guess my question is how do I need to format my import file in order to process the single quotes and ampersand so they come in with looking like HTML?  I tried a CSV that had no quotes and one with quotes but I got the same results in the table.

Thanks..

**Comment by sid8000** [comment]
+1 from me... Just checked 
![image](https://user-images.githubusercontent.com/30995759/36308753-f601d8fe-1347-11e8-811c-4ada3ac5cf34.png)
![image](https://user-images.githubusercontent.com/30995759/36308785-1179bb42-1348-11e8-8acc-f530f6228797.png)

**Comment by snipe** [comment]
If you (backup first) run `php artisan snipeit:unescape`, does that improve things?

**Comment by cepacs** [comment]
I didn't think of that but no luck.. :/

C:\inetpub\wwwroot\snipe-it>php.exe artisan snipeit:unescape
Updating name for \App\Models\Asset
Updating name for \App\Models\Asset
Updating name for \App\Models\Asset
Updating name for \App\Models\Asset
Updating name for \App\Models\Asset
Updating name for \App\Models\Asset
Updating name for \App\Models\Asset
Updating name for \App\Models\Asset
Updating name for \App\Models\Asset
Updating name for \App\Models\Asset
Updating name for \App\Models\Supplier
Updating name for \App\Models\Location
Updating name for \App\Models\Location
Updating name for \App\Models\Location
Update complete

Assets table stayed the same..
![image](https://user-images.githubusercontent.com/36515590/36328395-e531f850-132f-11e8-8b2b-a18474ddb2c3.png)

**Comment by snipe** [comment]
I don't even know how that's possible... 

```
foreach($classname::where("$field",'LIKE','%&%')->get() as $row) {
    $this->info('Updating '.$field.' for '.$classname);
    $row->{$field} = html_entity_decode($row->{$field});
    $row->save();
    $count[$classname][$field]++;
}
```

Try running this MySQL command (backup first):

`UPDATE assets SET name=REPLACE(name,'&#039;',"'") WHERE name LIKE '%&#039;%'`

**Comment by cepacs** [comment]
The Update statement does work, not sure why it didn't work with the other method but I can script something now to fix it when it happens after an import for now.

Thanks :)

**Comment by snipe** [comment]
Awesome! Glad to hear you're all sorted. In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)

**Comment by jobymathaikseb** [comment]
This issue is still there in the latest releases.

eg:    I have a custom ecnrypted text field and when I input <, it is appearing as &lt; in the web page. Please fix this urgently.
