### ISSUE TITLE
Unable to Bind LDAP users

### ISSUE THREAD

**Issue by bdunigan80** [snipe/snipe-it#5026]
#### Expected Behavior (or desired behavior if a feature request)

I am expecting my LDAP users to have the ability to use their LDAP accounts to log into our self hosted Snipe IT instance.

-----

#### Actual Behavior

The LDAP users are not able to log in using their credentials. They enter in their user name and password. Pressing enter comes back with  Error: The username or password is incorrect 

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh Install
- Version of Snipe-IT you're running? Version v4.1.11-pre - build 3307 (master)
- Version of PHP you're running? PHP 7.0.25-0
- Version of MySQL/MariaDB you're running? mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64)
- What OS and web server you're running Snipe-IT on? Ubuntu 16.04 , nginx/1.10.3 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual Install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error.

 [2018-02-15 19:20:51] production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory 

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error? Working on the LDAP settings page. Using the test button we are able to make a successful connection to the LDAP server with the settings.
- If a stacktrace is provided in the error, include that too. N/A
- Any errors that appear in your browser's error console.  None
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. No, your demo doesn't allow for LDAP testing.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. No errors were encountered during the installation. Only action done after installation and local admin account setup was to input the LDAP info.
- Indicate whether or not you've manually edited any data directly in the database. No

Other Info:
We have been able to successfully do an ldap search on the host. Using this command, 

ldapsearch -W -D 'cn=admin,dc=cyc,dc=com' -b "ou=People,dc=cyc,dc=com" "uid=rfelder" .

We are able to gleam data from the LDAP server and retrieve correct user data. We have also verified that other systems with in our network leveraging LDAP authentication work using the same data used in the LDAP configuration page. 

Can you explain as to what is being done on the back end to connect and gleam info from the LDAP server? Are there different methods being used between the test to verify LDAP connectivity and the test for User bind? 

I'd also like to make note that we are able to do an LDAP Sync and do see users populating the Users area.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

![snipeit-ldap](https://user-images.githubusercontent.com/12648619/36278425-6dc8df62-1259-11e8-9914-9de28dfc8ac5.jpeg)

**Comment by Mynty100** [comment]
Hi,

We use the follow the following LDAP filter. Keep in mind if edited it to reflect as an example.

&(objectClass=user)(|(memberof= CN=SECUIRTY GROUP,OU=Security Groups,OU=Clients,DC=test,DC=test,DC=test,DC=test))

You can search for multiple security groups.

**Comment by Mynty100** [comment]
![image](https://user-images.githubusercontent.com/34461276/36294844-361f88f0-132f-11e8-83e1-106456abf3b1.png)

I recommand using these setting if LDAPing into a Windows Server AD

**Comment by bdunigan80** [comment]
Hi and thank you for your response.

We are actually using OpenLDAP in our network. Can you provide info
regarding that platform ? We have tried to use the recommended setting you
have posted on your install instructions.
The instructions are not providing the desired out come.

**Comment by Mynty100** [comment]
Aww yes. Not familiar with OpenLDAP. Quick google I see its free AD for Linix. Interesting. 

You will need to look at the documentation for this. Id say say it does not use samaccoutname at all as this is Microsoft AD variable. 

I suspect uid and uid= are used. and last name is not sn. I would change this back to default as well.

![image](https://user-images.githubusercontent.com/34461276/36357904-98e899f4-1550-11e8-8130-f712ff5a4b49.png)

Try with and with out the password sync option. But i have mine ticked. Again Im LDAPing into a MS AD.

Could be permissions on the service account your using to LDAP into your server as well. Look at OpenLDAP to see if there is any specific security groups the service account must be apart of. Process of elimination. 

Hope this helps. I am very interested to know how you go and what ends up solving this issue.

**Comment by bdunigan80** [comment]
You are correct on all points. We have set all variables accordingly to
your documentation. The issue seams to be an issue with the under pinnings
of your software and how its trying to query the ldap server. At this time
the mechanism if failing to "bind". When we do a ldap search on the system
running your software we can query to info regarding our ldqp users. When
we do a test via the software UI it fails. This tells me the function
making the query is not working properly.

**Comment by Mynty100** [comment]
I suspect that its able to connect to the sever with your chosen service account.

&(CN=*,OU=People,DC=CYC,DC=COM)

Im am assuming in the above 
![image](https://user-images.githubusercontent.com/34461276/36358361-fe116cf4-1558-11e8-8405-a6c339e1e41d.png)

Let me know if that helps. 
Cheers.

**Comment by Mynty100** [comment]
How did you go with this. Any luck??
