### ISSUE TITLE
Abusing "Reports" can lead to a 404

### ISSUE THREAD

**Issue by Zorlin** [snipe/snipe-it#5027]
#### Expected Behavior (or desired behavior if a feature request)

When clicking "Reports", it should open or close the reports panel and never lead anywhere.

-----

#### Actual Behavior

If you click a subheading of Reports (such as Activity Report or Audit Log), then rapidly left-click on Reports, you are directed to /reports and a 404

-----

#### Please confirm you have done the following before posting your bug report:

- Checked on my machine (Ubuntu 16.04)
- Checked on a different one (MacOS)
- Then checked both of those against the current master Snipe-IT demo and reproduced successfully on both

-----

Demo of the bug: https://imgur.com/a/QQ9s5
Longer demo of the bug: https://imgur.com/a/nRs1a

**Comment by snipe** [comment]
Fixed on dev, changes will be in next release. Thanks!
