### ISSUE TITLE
Does it no longer supports custom field section in next versions?

### ISSUE THREAD

**Issue by ifoyil** [snipe/snipe-it#5028]
Hi;
I reinstalled debian 9 version also I installed snipe-it v4.1.10 but I realized that it doesn't have custom field section; I have had backup my database when we use snipe-it 3.64 version; How to add my custom fields into the new version of it; is there any way to add previous versions custom fields to new 4.1.10 version. 

![1](https://user-images.githubusercontent.com/26713563/36298394-f291c0c4-1308-11e8-928b-7ed5a448a76d.JPG)
![2](https://user-images.githubusercontent.com/26713563/36298413-12cebdc4-1309-11e8-94e6-81a447669073.JPG)

**Comment by snipe** [comment]
Custom fields were moved to the gear menu in the right side

**Comment by ifoyil** [comment]
Sorry We couldn't display custom fields in gear menu section; İf it possible could you write in which menu is it including or title name something

**Comment by snipe** [comment]
I don't understand what you're asking for. The link is there.

<img width="258" alt="dashboard____snipe-it_demo" src="https://user-images.githubusercontent.com/197404/36406879-e2435fc2-15ae-11e8-8735-30d3f7e4aebd.png">
