### ISSUE TITLE
Sticky tables filtering don't work?

### ISSUE THREAD

**Issue by protocorenet** [snipe/snipe-it#5029]
Sticky tables 

-----

filtering don't work
-----

#### Please confirm you have done the following before posting your bug report:

 Enabled debug mode - no errors?

-----
#### Provide answers to these questions:

 Upgrade from v4.1.3 to v4.1.10
- v4.1.10
- PHP 7
- MySQL 5.4
- Windows 2012 R2 Server

**Comment by protocorenet** [comment]
None of it works the checkbox doesn't select all asset that is viewed.

**Comment by snipe** [comment]
This was addressed already here: https://github.com/snipe/snipe-it/issues/4314#issuecomment-340209525

Ultimately, I think that's a bug with the table library. Not sure we'll be able to fix it.

**Comment by protocorenet** [comment]
it looks to me like it been fixed in the new update but now every time I do a search then get rid of the search the table shrinks and I'm having to refresh to get it back to big?
