### ISSUE TITLE
Error when updating to 1.2.3

### ISSUE THREAD

**Issue by kylevitale** [snipe/snipe-it#503]
When I run php composer.phar update I get the following errors:

[RuntimeException]
  Could not load package phpspec/prophecy in http://packagist.org: [UnexpectedValueException] Could not parse version constraint ^1.0.2: Invalid version string "^1.
  0.2"

and

UnexpectedValueException]
  Could not parse version constraint ^1.0.2: Invalid version string "^1.0.2"

Also, running php artisan migrate gives this:

PHP Fatal error:  Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found in /media/vault/snipe-it/vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php on line 59

Any ideas?

When I try to load the site now I get this error:

Class 'Illuminate\Database\Eloquent\SoftDeletingTrait' not found

**Comment by snipe** [comment]
Try running `php composer.par self-update` first

**Comment by snipe** [comment]
(The second error is because the first bit - the composer update - failed, so it didn't get the new vendor libraries it needed to run the migrations and such)

**Comment by kylevitale** [comment]
Yes! Thanks.

**Comment by snipe** [comment]
No problem :)
