### ISSUE TITLE
Importer History Issue 

### ISSUE THREAD

**Issue by danr12** [snipe/snipe-it#5031]
#### Expected Behavior (or desired behavior if a feature request)
I'm using the Importer History and running a test import on 4 assets using the asset tag, name and date which says it's successful and no errors. I expected this to then populate my existing four assets with "Checked Out To" *user* and also the "Check Out Date" *date*

-----

#### Actual Behavior

When going to view the assets the checked out to and check out date is blank. I'm looking for a way to populate all my assets to users and dates as we are migrating over from a spreadsheet. Is this possible? It's my understanding this is what the importer history is specifically for? I have googled and tested but not finding much on this subject so any help will be much appreciated.

-----

#### Please confirm you have done the following before posting your bug report:

- [yes] I have enabled debug mode 
- [yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh
- Version of Snipe-IT you're running
v4.1.11-pre - build 3307
- Version of PHP you're running
7.1.13
- Version of MySQL/MariaDB you're running
mysql ver 15.1 Distrib MariaDB 5.5.56
- What OS and web server you're running Snipe-IT on
CentOS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No error as it claims it's successful!
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by danr12** [comment]
Following this I stumbled across https://github.com/snipe/snipe-it/issues/4890 - is this relevant to my issue ? It describes what happens to me, imported data cannot be checked in.

**Comment by snipe** [comment]
What do you have set as your username format in your General Settings?

**Comment by danr12** [comment]
firstname lastname and I am importing the csv with the username tag populated with the AD usernames (so firstname.lastname). I've got LDAP synced so figured snipe would match it with my import usernames and then check out the asset to the user.

**Comment by snipe** [comment]
Can you pull from the latest release (just released tonight) and see if that helps? We fixed a bug in username creation

**Comment by snipe** [comment]
`php upgrade.php` should do it if you installed via git an your permissions are okay

**Comment by danr12** [comment]
Okay so I've ran the pull successfully and reimported via the importer history but it just kept giving my whoops page. I turned on debugging and got this:


(1/1)                                         ErrorException                                                                          Undefined offset: 1
--
in User.php (line 333)
at HandleExceptions->handleError(8, 'Undefined offset: 1', '/var/www/html/snipeit/app/Models/User.php', 333, array('format' => 'firstname.lastname', 'users_name' => 'joe.bloggs', 'first_name' => 'joe.bloggs'))in User.php (line 333)

Any ideas ?

**Comment by danr12** [comment]
Hi. 

Sorry ignore above. I tinkered about some more and I think it's now working. Will continue to test some sample data. I've also used your sample asset import csv file which seems to work well. Thanks for your help @snipe

**Comment by snipe** [comment]
Awesome! Glad to hear you're all sorted. In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
