### ISSUE TITLE
Image size cap not respecting PHP and webserver validation rulles

### ISSUE THREAD

**Issue by zack6849** [snipe/snipe-it#5033]
#### Expected Behavior (or desired behavior if a feature request)

Increasing max upload size, and max post size to 10MB should allow a10MB image to be uploaded

-----

#### Actual Behavior

I get an error that it can't be more than 2000 kilobytes.

-----

#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh 
- Version of Snipe-IT you're running 4.1.11-pre build 3007
- Version of PHP you're running 7.0.25

Most of this is irrelevant, because I know it's a code issue.

I fixed it by modifying the numbers in `app/Http/Requests/ImageUploadRequest`, but you probably  shouldn't enforce arbitrary upload limits in source code, respect the PHP and webserver configuration for that.

**Comment by snipe** [comment]
This is on master and develop now.

![screenflow](https://user-images.githubusercontent.com/197404/36339049-753c3762-1371-11e8-9b0c-0ab4cdaf1547.gif)
