### ISSUE TITLE
snipeitapp.com site is pointing to the old doc under menu

### ISSUE THREAD

**Issue by radhe** [snipe/snipe-it#5035]
#### Menu should point to the updated/latest documentation 

docs should point to https://snipe-it.readme.io/v4.1.6/docs/importing

-----

#### Docs are pointed to old link

when I click on documentation I am pointed to https://snipe-it.readme.io/docs

**Comment by snipe** [comment]
The documentation system defaults to whatever the current version is. The /docs URL is intentional, so that it’s always linking to the latest.
