### ISSUE TITLE
[Request] Show maintenance notes with line breaks (in table or view page)

### ISSUE THREAD

**Issue by quacktacular** [snipe/snipe-it#5037]
#### Expected Behavior (or desired behavior if a feature request)

If I paste in notes from an external repair work order, or if I copy in notes from my own diagnostics script--displaying the lines breaks as they appear in the "notes" text area makes it much more legible. 

This could be achieved by allowing line breaks in the maintenances table (instead of wrapping), or by creating a "view" page for the individual maintenances that does :)

Example notes with line breaks...
```
=============================================== 
DEVICE REPORT - Fri 16 Feb 2018 09:14:43 PST

=============================================== 
Storage: 251.0 GB 
Battery Cycles: 199 
Battery Health: 42.283 
macOS Version: 10.13.3+17D47 
FileVault: Off 
Employee username: johndoe 
===============================================
```

-----

#### Actual Behavior

Currently the above report displays as this in the Assets "maintenances" tab, as well as the all maintenances page. 

Above example:

```
=============================================== DEVICE REPORT - Fri 16 Feb 2018 09:14:43 PST =============================================== Storage: 251.0 GB Battery Cycles: 199 Battery Health: 42.283 macOS Version: 10.13.3+17D47 FileVault: Off Employee username: johndoe ===============================================
```

Example work order:

Apple Fake Street 15-Feb-18 (778) 555-5555 Genius Bar Work Confirmation Repair No: R200000000 Customer Information Product Information Some Guy	Warranty Status: In Warranty (W) CAN	Model: MacBook Pro (13-inch, 2017, 2 TBT3) Date of Purchase: 27-Aug-17 Serial No: NEWSERIALNUMBER IMEI: Parts and Services Item Number	Description	Price	Amount Due	Customer KBB 661-07572	Logic Board, i5, 2.30GHz, 16GB, FCC Replacement Serial No: NEWSERIALNUMBER	$ 516.00	$ 0.00	661-07971	Display Assembly, Silver Replacement Serial No: NEWSERIALNUMBER	$ 516.00	$ 0.00	S1490LL/A Hardware Repair Labor	$ 109.00	$ 0.00	Tax	$ 0.00 Total	$ 1,141.00	$ 0.00

**Comment by liviuzaharia3** [comment]
Hi 

This is still an issue on version 7

New lines are not visible in notes in asset maintenance
