### ISSUE TITLE
Upgrade from 3.6.6 to 4.1.10 Fails with artisan migrate

### ISSUE THREAD

**Issue by misilot** [snipe/snipe-it#5038]
#### Expected Behavior 

Database gets migrated to latest version

-----

#### Actual Behavior
```php artisan migrate```
```PHP Fatal error:  Call to undefined method Illuminate\Foundation\Application::resourcePath() in /var/www/vhosts/production/inventory.lib.fit.edu/inventory.lib.fit.edu/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 673```

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode  -- not in browser
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running - 3.6.6 -> 4.1.10
- Version of PHP you're running 5.6.33
- Version of MySQL/MariaDB you're running 10.0.33-MariaDB-wsrep 
- What OS and web server you're running Snipe-IT on CentOS7 / Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual -> converting to git
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error ... not in browser

**Comment by snipe** [comment]
Try deleting the contents of the `bootstrap/caches directory

**Comment by misilot** [comment]
Thank you that solved the issue. I thought I had deleted those files already, must have been in the pre conversion to git folder.
