### ISSUE TITLE
Ubuntu 14.04 Installation Issue

### ISSUE THREAD

**Issue by baggar11** [snipe/snipe-it#504]
How to install fileinfo on ubuntu? I get to the part where I run "php artisan key:generate --env=production" but get the following error.

PHP Warning:  require(/var/www/snipe-it/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/snipe-it/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/snipe-it/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/snipe-it/bootstrap/autoload.php on line 17

I believe this indicates that I don't have the fileinfo extension installed.

**Comment by madd15** [comment]
Hi baggar11,

What version of php are you using?

**Comment by baggar11** [comment]
PHP 5.5.9

**Comment by madd15** [comment]
Have you run `composer install`?

**Comment by baggar11** [comment]
I'm only at the bottom of step 1 on this page --> http://snipeitapp.com/documentation/installing-on-linuxosx/

Do you suggest I skip ahead?

**Comment by snipe** [comment]
@baggar11 No, you can't skip ahead, unfortunately. Each step is important for the next step.

Fileinfo is installed by default with PHP versions higher than 5.3, but you do sometimes need to enabled it. 

You'll want to find your `php.ini` file and search for `fileinfo`. If you find something that looks like:

`extension=fileinfo.so`

but it's commented out, uncomment it and restart the web server.

If you don't find anything like that, add it to your ini and then restart the webserver.

**Comment by madd15** [comment]
@baggar11 Please leave `php artisan key:generate --env=production` until after step 4 as stated in the documentation.

> You should also change your secret key here. If you prefer to have your key randomly generated, run the artisan key:generate command from the application root.

> php artisan key:generate --env=production

> **after** step 4 below.

**Comment by baggar11** [comment]
Ah, duh. I didn't even see that "after step 4 below"

Thanks, I was able to get through the rest of the installation instructions.

**Comment by baggar11** [comment]
Upon first page load, I got an mcrypt error, so I went back to step 2 and ran the 'php artisan key:generate --env-production' without issue. Now when the page loads, it gives me an error after redirecting me to http://sitename/auth/signin.

Any ideas?

**Comment by snipe** [comment]
That's what's expected, no? It's prompting you to sign in.

**Comment by snipe** [comment]
Make sure the `url` value in your `app/config/production/app.php` is set to whatever your domain name should be.

**Comment by baggar11** [comment]
I have that set correctly. I can ping it from the snipeit machine and other machines on the network.

**Comment by snipe** [comment]
So what is the issue then?

**Comment by baggar11** [comment]
Not Found

The requested URL /auth/signin was not found on this server.

Apache/2.4.7 (Ubuntu) Server at 172.16.21.153 Port 80

**Comment by snipe** [comment]
Sounds like you don't have mod_rewrite enabled. Please see the 404 section in the Common Issues docs: http://snipeitapp.com/documentation/common-issues/

**Comment by baggar11** [comment]
I do have it enabled. That was my first suspect but had already checked it.

build@snipeit:~$ sudo a2enmod rewrite
Module rewrite already enabled

**Comment by snipe** [comment]
Again, please see the documentation. It is installed, but it may not be configured correctly.

**Comment by snipe** [comment]
Specifically this link in the docs: http://askubuntu.com/questions/423514/how-to-enable-mod-rewrite-for-virtual-host

**Comment by baggar11** [comment]
Sorry I was a bother. I had to edit the /var/www directory portion of /etc/apache2/apache2.conf to AllowOverride All instead of none. Thanks for your help!

**Comment by snipe** [comment]
I figured that's what it was. Glad you got it sorted.
