### ISSUE TITLE
Entering asset model in a full company setup failed

### ISSUE THREAD

**Issue by stolz1982** [snipe/snipe-it#5040]
#### Expected Behavior (or desired behavior if a feature request)

Enabled "Full company support" Setup
1 User with all rights denied, except "Super Sser" rights (see Screenshot)
The user has been assigned to a company .

The system should allow to create an asset. During the Process the of creating an asset, user should has permissions also to create an none existing asset model.

-----

#### Actual Behavior

During the process of creating the asset, the user creates a new model and cannot save it.

-----

#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
fresh install

- Version of Snipe-IT you're running
v4.0.13 build 323 (gc1f8db3) 

- Version of PHP you're running
7.0.22-0ubuntu0.16.04.1

- Version of MySQL/MariaDB you're running
10.1.28+maria-1~xenial

- What OS and web server you're running Snipe-IT on
Linux IT01 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
apache2 2.4.18-2ubuntu3.5

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
"Server Error. An Error has occured! This action is unauthorized"

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
https://sub.domain.com/hardware/create

- If a stacktrace is provided in the error, include that too.
No stacktrace was provided.

- Any errors that appear in your browser's error console.
unauthorized./var/www/snipeit/vendor/laravel/framework/src/Illuminate/Auth/Access/HandlesAuthorization.php#28

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
No, the scenario I am dealing with cannot being setup accordingly.

- Include any additional information you can find in `storage/logs` and your webserver's logs.
No log entries will be produced for this error in storage/logs.

- Include what you've done so far in the installation, and if you got any error messages along the way.
No

- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by stolz1982** [comment]
<img width="409" alt="screen shot 2018-02-18 at 20 14 21" src="https://user-images.githubusercontent.com/12507015/36354810-da189656-14ea-11e8-9716-2e0964d34041.png">

<img width="485" alt="screen shot 2018-02-18 at 20 32 54" src="https://user-images.githubusercontent.com/12507015/36354822-f0600188-14ea-11e8-8615-c51383f11baf.png">

**Comment by snipe** [comment]
That doesn’t really make sense though. The super admin right overrides everything else, always. (On a basic, unnuanced level.)

Please see if you can reproduce this on the demo. You can create a new test user with your specific permissions to try. 

Also, for what reason are you denying rights on a super admin? That seems like a use case that wouldn’t happen.

**Comment by stolz1982** [comment]
Hi snipe,

many thanks for your quick reply and it seems that my use case has not been reported properly. Hence, let me describe the use case in more details because it is possible that snipe-it doesn't support the use case yet I am looking for it.

My intention is to setup 3 User and 3 Companies. In the settings I have enabled the "Full company support". Each User will be assigned to its appropriate company. In addition, I have create a new group where each user is assigned to. This group has been described already with first post and also a screenshot has been attached previously. Each User should be able to create new Assets and also new Models but if the user has missing "Super admin" access rights user cannot save the new model during the process of creation of assets. BUT I don't want to give the users "super admin" rights in order to maintain the related assets, licenses,etc. of the assigned company.

User A is assigned to Company A
User B is assigned to Company B
User C is assigned to Company C

User A is allow to maintain (create,edit, delete,etc.) all assets, licenses, etc. of Company A only.
User B is allow to maintain (create,edit, delete,etc.) all assets, licenses, etc. of Company B only.
User C is allow to maintain (create,edit, delete,etc.) all assets, licenses, etc. of Company C only.

Only the "super user" should be able to maintain (create,edit, delete,etc.) all assets, licenses, etc. of **all** Companies.

I hope it helps a bit to explain my problem I am facing.

I am really looking forward to hear from you.

Thanks and best regards,
Steffen

BTW, many thanks for this great tool. Which I use currently for Company A but I want to gain the usage to B and C.

**Comment by stolz1982** [comment]
Hi, 

I wanted to re-produce the behavior on the Demo Site but after creating the group, setting up the user and assign the previously created group. Unfortunately, assigning a group is for superuser only. 

![Uploading Screen Shot 2018-02-19 at 23.14.16.png…]()

Probably someone can guide me to a solution for my problem. Any feedback is highly appreciated.

Thanks and kind regards

**Comment by stolz1982** [comment]
<img width="925" alt="screen shot 2018-02-19 at 23 14 16" src="https://user-images.githubusercontent.com/12507015/36443247-48543cca-1689-11e8-9e0c-c759499ff498.png">

**Comment by snipe** [comment]
Have you tried upgrading your version? Some things related to groups were changed in later versions.

**Comment by stolz1982** [comment]
Good morning,

the upgrade to 4.1.14 solved the issue. 

<img width="558" alt="image" src="https://user-images.githubusercontent.com/12507015/36716237-d7f3d754-1b99-11e8-98a5-9b154cd20607.png">
