### ISSUE TITLE
Feature Request: Adding to Common Issues Documentation

### ISSUE THREAD

**Issue by gen1e** [snipe/snipe-it#5041]
#### Expected Behavior (or desired behavior if a feature request)

While I was installing snipeit I came across an issue when trying to run the composer install command, I noticed someone else had this issue and would like to add the solution I used to the common issues documentation. I didn't see any docs about contributing to the documentation and would add to this also after learning the process. I noticed that the docs are on readme.io and that I can "suggest edits" using it, is that how I should submit the documentation alterations?

As for the actual error I get the same error as [here](https://github.com/snipe/snipe-it/issues/1258) but I fixed it using `composer update` before 'composer install'. After finding the common issues section about it ["While running composer: intervention/image dev-master requires ext-fileinfo * -> the requested PHP extension fileinfo is missing or not enabled on your system."](https://snipe-it.readme.io/v4.1.6/docs/installation-issues#section-while-running-composer-interventionimage-dev-master-requires-ext-fileinfo-the-requested-php-extension-fileinfo-is-missing-or-not-enabled-on-your-system), I found the other solution. I was wondering if adding the composer update before composer install command would be helpful.

-----

#### Actual Behavior

See above

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh
- Version of Snipe-IT you're running 
4.1.10
- Version of PHP you're running 
7.0
- Version of MySQL/MariaDB you're running
10.0
- What OS and web server you're running Snipe-IT on
Ubuntu LTS 16.04.3
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
N/A
- If a stacktrace is provided in the error, include that too.
N/A
- Any errors that appear in your browser's error console.
N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
N/A
- Include any additional information you can find in `storage/logs` and your webserver's logs.
N/A
- Include what you've done so far in the installation, and if you got any error messages along the way.
composer install --no-dev --prefer-source

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for intervention/image 2.3.x-dev -> satisfiable by in
tervention/image[2.3.x-dev].
- intervention/image 2.3.x-dev requires ext-fileinfo * -> the requested PHP
extension fileinfo is missing from your system.
Problem 2
- Installation request for intervention/image dev-master -> satisfiable by i
ntervention/image[dev-master].
- intervention/image dev-master requires ext-fileinfo * -> the requested PHP
extension fileinfo is missing from your system.

- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
We never recommend running `composer update` if there is any other option, and we'd much rather try to troubleshoot with folks than have them do that. The developers (us) are the only ones who really should be running that, and then we commit our lock file so that we can be sure that all users are using the same versions of the dependent libraries. If a user's lock file an ours gets out of sync, it could cause unpredictable errors that can be nearly impossible to troubleshoot.

**Comment by gen1e** [comment]
Cool thanks for explaining.
