### ISSUE TITLE
Import process keeping saying Processing event more than 2 hours

### ISSUE THREAD

**Issue by firmank** [snipe/snipe-it#5042]
#### Expected Behavior (or desired behavior if a feature request)
Hi snipe it

i was trying to import data thru CSV (100 rows, size 15.83KB), but import process keeping saying Processing event more than 2 hours. previously i have tried to import csvwith 1000 rows and i cancelled since already take 1 days no any luck.  i have checked the folder C:\wamp\www\snipe-it\storage\private_uploads\imports no-read-only (i can see the import file on this folder)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? upgrade from snipe-it-4.1.6
- Version of Snipe-IT you're running? snipe-it-4.1.10
- Version of PHP you're running ? PHP 7.1.9 (cli) (built: Aug 30 2017 18:37:35)
- Version of MySQL/MariaDB you're running ? 5.7.19 MySQL
- What OS and web server you're running Snipe-IT on ? Windows 2012
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) ? manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
> Include any additional information you can find in storage/logs and your webserver's logs.

A CSV with 100 assets should process instantaneously.
