### ISSUE TITLE
Error setup page

### ISSUE THREAD

**Issue by momaydopod** [snipe/snipe-it#5043]
I use CentOS 7   and Following install by https://www.vultr.com/docs/how-to-install-snipe-it-on-centos-7

I grant folder
`sudo chown -R apache:apache storage public/uploads
sudo chmod -R 755 storage
sudo chmod -R 755 public/uploads`

this Virtual host
`<VirtualHost *:80>
    ServerName snipeit.example.com
    DocumentRoot /var/www/snipe-it/public
    <Directory /var/www/snipe-it/public>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
    </Directory>
</VirtualHost>
<img width="400" alt="2018-02-08 10_41_49-10 50 21 12 - vsphere client" src="https://user-images.githubusercontent.com/36228338/36366350-550f896a-1580-11e8-8fd2-b16a5676600b.png">
<img width="401" alt="2018-02-08 10_42_00-10 50 21 12 - vsphere client" src="https://user-images.githubusercontent.com/36228338/36366351-55f05a8a-1580-11e8-8028-0e09caf60ec4.png">
<img width="401" alt="2018-02-08 10_42_07-10 50 21 12 - vsphere client" src="https://user-images.githubusercontent.com/36228338/36366352-5654e1c6-1580-11e8-8970-bf058836b775.png">
<img width="403" alt="2018-02-08 10_42_12-10 50 21 12 - vsphere client" src="https://user-images.githubusercontent.com/36228338/36366354-56b0f47a-1580-11e8-8e6c-e444eb441e6f.png">

`

**Comment by snipe** [comment]
@momaydopod Check whether or not you're running [SELinux](https://snipe-it.readme.io/docs/linuxosx#section-notes-on-selinux).

**Comment by momaydopod** [comment]
This is status


<img width="327" alt="2018-02-21 09_04_03-10 50 21 12 - vsphere client" src="https://user-images.githubusercontent.com/36228338/36459404-4619c878-16e6-11e8-9c66-4cdb56eface4.png">

**Comment by snipe** [comment]
Please follow the directions at the link I already gave you, to enable SELinux to work with Snipe-IT.
