### ISSUE TITLE
MariaDB + SSL = error SQLSTATE[HY000] [2002]

### ISSUE THREAD

**Issue by jelockwood** [snipe/snipe-it#5044]
#### Expected Behavior (or desired behavior if a feature request)
I have a MariaDB server configured to support SSL connections and this works with another different php project. I can connect using SnipeIT to this MariaDB server without SSL by editing my .env to say DB_SSL=false, and I can connect with SSL via the command line using mysql -u snipeit -p -h snipeit
Note: My /etc/mysql/my.cnf is configured to use the same SSL cert etc.

However if I have DB_SSL=true I get the error messages as listed below.
(what you expect to happen goes here)
I expect to see snipeit successfully connect to the MariaDB server when configured to use DB_SSL=true
-----

#### Actual Behavior

(what actually happens goes here)
Connection fails immediately, full error report is below.
-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running 5.4.35
- Version of PHP you're running 
PHP 7.0.25-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.25-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
- Version of MySQL/MariaDB you're running
mysql  Ver 15.1 Distrib 10.1.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04
Linux snipe-it 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-09-18T15:09:02
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

(4/4) QueryExceptionSQLSTATE[HY000] [2002] (SQL: select * from information_schema.tables where table_schema = snipeit and table_name = users)
--
in Connection.php (line 647)
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php (line 607)
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php (line 326)
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in MySqlBuilder.php (line 18)
at MySqlBuilder->hasTable('users')in Facade.php (line 221)
at Facade::__callStatic('hasTable', array('users'))in Setting.php (line 63)
at Setting::setupCompleted()in CheckForSetup.php (line 22)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

(3/4) PDOExceptionSQLSTATE[HY000] [2002]
--
in PDOConnection.php (line 47)
at PDOConnection->__construct('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', 'snipeit', 'snipeit', array(0, 2, 0, false, false, null, null, null, null))in Connector.php (line 65)
at Connector->createPdoConnection('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', 'snipeit', 'snipeit', array(0, 2, 0, false, false, null, null, null, null))in Connector.php (line 44)
at Connector->createConnection('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', array('driver' => 'mysql', 'host' => 'it-db.internal.yoti.com', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipeit', 'password' => 'snipeit', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array(null, null, null, null), 'name' => 'mysql'), array(0, 2, 0, false, false, null, null, null, null))in MySqlConnector.php (line 24)
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => 'it-db.internal.yoti.com', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipeit', 'password' => 'snipeit', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array(null, null, null, null), 'name' => 'mysql'))in ConnectionFactory.php (line 183)
at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
at call_user_func(object(Closure))in Connection.php (line 883)
at Connection->getPdo()in Connection.php (line 904)
at Connection->getReadPdo()in Connection.php (line 392)
at Connection->getPdoForSelect(true)in Connection.php (line 318)
at Connection->Illuminate\Database\{closure}('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in Connection.php (line 640)
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php (line 607)
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php (line 326)
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in MySqlBuilder.php (line 18)
at MySqlBuilder->hasTable('users')in Facade.php (line 221)
at Facade::__callStatic('hasTable', array('users'))in Setting.php (line 63)
at Setting::setupCompleted()in CheckForSetup.php (line 22)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

(2/4) PDOExceptionSQLSTATE[HY000] [2002]
--
in PDOConnection.php (line 43)
at PDO->__construct('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', 'snipeit', 'snipeit', array(0, 2, 0, false, false, null, null, null, null))in PDOConnection.php (line 43)
at PDOConnection->__construct('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', 'snipeit', 'snipeit', array(0, 2, 0, false, false, null, null, null, null))in Connector.php (line 65)
at Connector->createPdoConnection('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', 'snipeit', 'snipeit', array(0, 2, 0, false, false, null, null, null, null))in Connector.php (line 44)
at Connector->createConnection('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', array('driver' => 'mysql', 'host' => 'it-db.internal.yoti.com', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipeit', 'password' => 'snipeit', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array(null, null, null, null), 'name' => 'mysql'), array(0, 2, 0, false, false, null, null, null, null))in MySqlConnector.php (line 24)
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => 'it-db.internal.yoti.com', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipeit', 'password' => 'snipeit', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array(null, null, null, null), 'name' => 'mysql'))in ConnectionFactory.php (line 183)
at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
at call_user_func(object(Closure))in Connection.php (line 883)
at Connection->getPdo()in Connection.php (line 904)
at Connection->getReadPdo()in Connection.php (line 392)
at Connection->getPdoForSelect(true)in Connection.php (line 318)
at Connection->Illuminate\Database\{closure}('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in Connection.php (line 640)
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php (line 607)
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php (line 326)
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in MySqlBuilder.php (line 18)
at MySqlBuilder->hasTable('users')in Facade.php (line 221)
at Facade::__callStatic('hasTable', array('users'))in Setting.php (line 63)
at Setting::setupCompleted()in CheckForSetup.php (line 22)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

(1/4) PDOExceptionPDO::__construct(): Filename cannot be empty
--
in PDOConnection.php (line 43)
at PDO->__construct('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', 'snipeit', 'snipeit', array(0, 2, 0, false, false, null, null, null, null))in PDOConnection.php (line 43)
at PDOConnection->__construct('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', 'snipeit', 'snipeit', array(0, 2, 0, false, false, null, null, null, null))in Connector.php (line 65)
at Connector->createPdoConnection('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', 'snipeit', 'snipeit', array(0, 2, 0, false, false, null, null, null, null))in Connector.php (line 44)
at Connector->createConnection('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', array('driver' => 'mysql', 'host' => 'it-db.internal.yoti.com', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipeit', 'password' => 'snipeit', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array(null, null, null, null), 'name' => 'mysql'), array(0, 2, 0, false, false, null, null, null, null))in MySqlConnector.php (line 24)
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => 'it-db.internal.yoti.com', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipeit', 'password' => 'snipeit', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array(null, null, null, null), 'name' => 'mysql'))in ConnectionFactory.php (line 183)
at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
at call_user_func(object(Closure))in Connection.php (line 883)
at Connection->getPdo()in Connection.php (line 904)
at Connection->getReadPdo()in Connection.php (line 392)
at Connection->getPdoForSelect(true)in Connection.php (line 318)
at Connection->Illuminate\Database\{closure}('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in Connection.php (line 640)
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php (line 607)
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php (line 326)
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in MySqlBuilder.php (line 18)
at MySqlBuilder->hasTable('users')in Facade.php (line 221)
at Facade::__callStatic('hasTable', array('users'))in Setting.php (line 63)
at Setting::setupCompleted()in CheckForSetup.php (line 22)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Setup page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
As mentioned snipeit is able to connect to the MariaDB server if I set DB_SSL=false
Also as mentioned with my /etc/mysql/my.cnf set to use SSL I can do mysql -u snipeit -p -h snipeit
Also as mentioned another different php project is able to do a PDO Mysql connection with SSL successfully.
If I set DB_SSL=false then I get the following from the setup page

Setting | Valid | Notes
-- | -- | --
URL |   | That URL looks right! Good job!
Database |   | Great work! Connected to snipeit
Config File |   | Sweet. It doesn't look like your .env file is exposed to the outside world. (You should double check this in a browser though. You don't ever want anyone able to see that file. Ever. Ever ever.) Click here to check now (This should return a file not found or forbidden error.)
Environment |   | Your app is set to production mode. Rock on!
File Owner |   | Your app files are owned by www-data. That doesn't look like a default root/admin account. Nice!
Permissions |   | Yippee! Your app storage directory seems writable.
Debug |   | Yikes! You should turn off debug mode unless you encounter any issues. Please update your APP_DEBUG settings in your  .env file
Image Library |   | GD is installed. Go you!
Email | Send Test | This will attempt to send a test mail to you@example.com.

- Indicate whether or not you've manually edited any data directly in the database
No
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by jelockwood** [comment]
Oops!

Turned out to be a subtle but stupid typo in my .env file. Closing ticket.

**Comment by jelockwood** [comment]
The problem (typo) was that /var/www/snipeit/config/database.php uses env variable names of

DB_SSL_KEY
DB_SSL_CERT
DB_SSL_CA

But https://github.com/snipe/snipe-it/issues/3479 and other sources say

DB_SSL_KEY_PATH
DB_SSL_CERT_PATH
DB_SSL_CA_PATH

Since the official SnipeIT documentation does _not_ cover this it was hard to judge where to point the finger at as which is wrong. I am therefore re-opening the ticket as either the provided database.php file needs 'fixing', or the documentation does.

**Comment by snipe** [comment]
You're absolutely correct - thank you. Since the `.env.example` uses the longer phrasing, we've pushed out a change to to the `config/database.php`. So the correct `.env` settings should be:

```
DB_SSL_KEY_PATH
DB_SSL_CERT_PATH
DB_SSL_CA_PATH
```

Thanks for catching that.
