### ISSUE TITLE
Authorization Required for /statuslabels

### ISSUE THREAD

**Issue by getschools** [snipe/snipe-it#5045]
#### Expected Behavior (or desired behavior if a feature request)

Click or go to /statuslabels and get to the Status Labels admin page.

-----

#### Actual Behavior

Authorization required message with username and password fields, then 401 Authorization Required message on Cancel

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Fresh**
- Version of Snipe-IT you're running **Version v4.1.11-pre - build 3307 (master)**
- Version of PHP you're running **5.6.33-3**
- Version of MySQL/MariaDB you're running **mysql  Ver 15.1 Distrib 10.1.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2**
- What OS and web server you're running Snipe-IT on **Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-101-generic x86_64), NGINX**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Git**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **None**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **/statuslabels**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. **None**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. **No**
- Include any additional information you can find in `storage/logs` and your webserver's logs. **Authorization errors on /statuslabels**
- Include what you've done so far in the installation, and if you got any error messages along the way. **Checked permissions on the htdocs folders**
- Indicate whether or not you've manually edited any data directly in the database **No**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
We do not have anything in place that would prompt you for a password for that section.

**Comment by getschools** [comment]
That's what I figured. It really doesn't make sense. There isn't anything in the nginx config that requires auth for that path.

**Comment by snipe** [comment]
This is pretty weird, TBH. I don't have any idea why this would be happening. :-/

**Comment by snipe** [comment]
I'm going to close this, since I honestly don't have any idea why this would be happening. I'm sorry :(
