### ISSUE TITLE
Feature Request: send acceptance to manager of location when assigning asset to location

### ISSUE THREAD

**Issue by jeffclay** [snipe/snipe-it#5047]
#### Expected Behavior (or desired behavior if a feature request)

With require acceptance enabled for an asset category, an asset should be assignable to a location.
The acceptance e-mail would be sent to the manager configured for that location.

-----

#### Actual Behavior

With require acceptance enabled for an asset category, an asset is not assignable to a location or other asset. 
The following message is shown: "Because this asset category requires acceptance, it cannot be checked out to another asset or to a location. "

-----

- Is this a fresh install or an upgrade? _upgraded last week_
- Version of Snipe-IT you're running  _v4.1.11-pre - build 3307 (master)_
- Version of PHP you're running  _7.1_
- Version of MySQL/MariaDB you're running  _1:5.5.56-2.el7_
- What OS and web server you're running Snipe-IT on  _CentOS 7_
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)  _manual installation, updated with update.php_
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error       hardware/ID#/checkout

**Comment by wilsonlspacheco** [comment]
+1 interested (hosted company)

**Comment by goludiaOH** [comment]
We have display devices within the office that we want to track with location managers who maintain those assets
+1, would like this functionality

**Comment by jeffclay** [comment]
Don't close this. please implement this feature.

**Comment by megastary** [comment]
Has anything changed in this regard? This would be greatly appreciated.

**Comment by RicardoDeLaFunta** [comment]
Please reopen this feature. Or is any other way to force acceptance while assign assets to location by manager or while assigned to asset which is checked out would be accepted by owner of parental asset
