### ISSUE TITLE
Companies feature treats company_id 0 and NULL differently for asset viewing

### ISSUE THREAD

**Issue by tantonw** [snipe/snipe-it#5049]
#### Expected Behavior (or desired behavior if a feature request)

With Full Multiple Companies Support enabled, when logged in with a user without a company assigned (company_id 0), either all or none of the assets without a company assigned should be visible. (not sure what the by-design behavior is for this)

-----

#### Actual Behavior

Users with company_id 0 can see assets with no company that were created via the "create asset" page, as that page assigns company_id 0 to new assets.  However, they can not see assets with no company that were imported via CSV, as the importer assigns company_id NULL to new assets.  

Not sure if the fix should be to make the importer assign "0", alter the "multiple companies support" code to treat 0 and NULL the same, or both.

MariaDB [snipeit]> select name,asset_tag,company_id from assets;
+-------------+-----------+------------+
| name        | asset_tag | company_id |
+-------------+-----------+------------+
| WebCreated1 | 555001    |          0 |
| Imported1   | 555002    |       NULL |
+-------------+-----------+------------+
2 rows in set (0.00 sec)

MariaDB [snipeit]> select username,company_id from users where username='wes';
+----------+------------+
| username | company_id |
+----------+------------+
| wes      |          0 |
+----------+------------+
1 row in set (0.01 sec)

Super Admin view:
![image](https://user-images.githubusercontent.com/16965100/36399755-37f58e4a-1582-11e8-8425-1ce2e3298365.png)

User view (wes):
![image](https://user-images.githubusercontent.com/16965100/36399794-64a77db8-1582-11e8-8178-4e1815f8bb8d.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running Version v4.1.11-pre - build 3307 (master)
- Version of PHP you're running 5.6.33
- Version of MySQL/MariaDB you're running MariaDB 5.5.56
- What OS and web server you're running Snipe-IT on Centos 7 - Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) GIT
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error "Create Asset", "Import", and "List All Assets"
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Can you tell me how you created those users? Company ID should never be 0 - that's a leftover from old (bad) behavior.

**Comment by tantonw** [comment]
LDAP import, I’ll see if I can reproduce that tomorrow.



On Feb 19, 2018, at 5:56 PM, snipe <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you tell me how you created those users? Company ID should never be 0 - that's a leftover from old (bad) behavior.

**Comment by tantonw** [comment]
OK, I reproduced the user company_id=0 result.  After LDAP import the company_id is properly NULL, but adding the user to a group using People -> Click on user -> Edit User button causes company_id to be set to 0.  The "Select Company" field on the edit user page was left at its default setting of "Select Company".

**Comment by tantonw** [comment]
More correctly... hitting the "Save" button on the Edit User page sets company_id to 0, the adding to group part I mentioned above is actually irrelevant -- it's just what I happened to be testing.

**Comment by tantonw** [comment]
Editing/saving an asset without picking a Company also sets the asset's company_id to 0, even if it was already NULL.  The "Remove Company Association" selection on the hardware/bulkedit page sets company_id to NULL.
