### ISSUE TITLE
Change FrontEnd

### ISSUE THREAD

**Issue by devgnu9** [snipe/snipe-it#5050]
Hi guys.
I want to modify the text that is displayed in the part of the administrator's dashboard (Navbar Right Menu) that says "Create Location". I go to the dashboard.blade.php view to modify it but I can not find the section corresponding to this part of the HTML. Can someone tell me what file to modify to achieve my goal?

**Comment by snipe** [comment]
`resources/views/layout/default.blade.php` - however you should know that you'll have to re-apply those changes every time you upgrade.
