### ISSUE TITLE
MariaDB + SSL = error SQLSTATE[HY000] [2002] second different issue

### ISSUE THREAD

**Issue by jelockwood** [snipe/snipe-it#5053]
#### Expected Behavior (or desired behavior if a feature request)
Whilst the title and error are very similar to my last (valid and fixed) ticket the details are slightly different and it is still not working. Hence this new ticket.

I have modified my /var/www/snipeit/config/database.php file to incorporate the fix for my last ticket, and my .env DB_SSL_CERT_PATH etc. matches the new fixed database.php file. Therefore as you will see below the error messages _do_ now correctly include the certificate, private key etc. unlike before.

As before I am able to connect to the database using the mysql command line also as before SnipeIT works with SSL turned off i.e. DB_SSL=false unfortunately I still get errors when trying to use SSL.
(what you expect to happen goes here)
I expect to be able to connect via SSL to the MariaDB server.
-----

#### Actual Behavior
With DB_SSL=true set and the correct variables and paths defined for the SSL certs I get the following error messages.
(what actually happens goes here)

(4/4) QueryExceptionSQLSTATE[HY000] [2002] (SQL: select * from information_schema.tables where table_schema = snipeit and table_name = users)
--
in Connection.php (line 647)
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php (line 607)
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php (line 326)
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in MySqlBuilder.php (line 18)
at MySqlBuilder->hasTable('users')in Facade.php (line 221)
at Facade::__callStatic('hasTable', array('users'))in Setting.php (line 63)
at Setting::setupCompleted()in CheckForSetup.php (line 22)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

(3/4) PDOExceptionSQLSTATE[HY000] [2002]
--
in PDOConnection.php (line 47)
at PDOConnection->__construct('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', 'snipeit', 'snipeit', array(0, 2, 0, false, false, '/etc/mysql/ssl/snipe-it.internal.yoti.com.key', '/etc/mysql/ssl/snipe-it.internal.yoti.com.crt', '/etc/mysql/ssl/YotiCA.crt', null))in Connector.php (line 65)
at Connector->createPdoConnection('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', 'snipeit', 'snipeit', array(0, 2, 0, false, false, '/etc/mysql/ssl/snipe-it.internal.yoti.com.key', '/etc/mysql/ssl/snipe-it.internal.yoti.com.crt', '/etc/mysql/ssl/YotiCA.crt', null))in Connector.php (line 44)
at Connector->createConnection('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', array('driver' => 'mysql', 'host' => 'it-db.internal.yoti.com', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipeit', 'password' => 'snipeit', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array('/etc/mysql/ssl/snipe-it.internal.yoti.com.key', '/etc/mysql/ssl/snipe-it.internal.yoti.com.crt', '/etc/mysql/ssl/YotiCA.crt', null), 'name' => 'mysql'), array(0, 2, 0, false, false, '/etc/mysql/ssl/snipe-it.internal.yoti.com.key', '/etc/mysql/ssl/snipe-it.internal.yoti.com.crt', '/etc/mysql/ssl/YotiCA.crt', null))in MySqlConnector.php (line 24)
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => 'it-db.internal.yoti.com', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipeit', 'password' => 'snipeit', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array('/etc/mysql/ssl/snipe-it.internal.yoti.com.key', '/etc/mysql/ssl/snipe-it.internal.yoti.com.crt', '/etc/mysql/ssl/YotiCA.crt', null), 'name' => 'mysql'))in ConnectionFactory.php (line 183)
at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
at call_user_func(object(Closure))in Connection.php (line 883)
at Connection->getPdo()in Connection.php (line 904)
at Connection->getReadPdo()in Connection.php (line 392)
at Connection->getPdoForSelect(true)in Connection.php (line 318)
at Connection->Illuminate\Database\{closure}('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in Connection.php (line 640)
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php (line 607)
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php (line 326)
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in MySqlBuilder.php (line 18)
at MySqlBuilder->hasTable('users')in Facade.php (line 221)
at Facade::__callStatic('hasTable', array('users'))in Setting.php (line 63)
at Setting::setupCompleted()in CheckForSetup.php (line 22)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

(2/4) PDOExceptionSQLSTATE[HY000] [2002]
--
in PDOConnection.php (line 43)
at PDO->__construct('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', 'snipeit', 'snipeit', array(0, 2, 0, false, false, '/etc/mysql/ssl/snipe-it.internal.yoti.com.key', '/etc/mysql/ssl/snipe-it.internal.yoti.com.crt', '/etc/mysql/ssl/YotiCA.crt', null))in PDOConnection.php (line 43)
at PDOConnection->__construct('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', 'snipeit', 'snipeit', array(0, 2, 0, false, false, '/etc/mysql/ssl/snipe-it.internal.yoti.com.key', '/etc/mysql/ssl/snipe-it.internal.yoti.com.crt', '/etc/mysql/ssl/YotiCA.crt', null))in Connector.php (line 65)
at Connector->createPdoConnection('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', 'snipeit', 'snipeit', array(0, 2, 0, false, false, '/etc/mysql/ssl/snipe-it.internal.yoti.com.key', '/etc/mysql/ssl/snipe-it.internal.yoti.com.crt', '/etc/mysql/ssl/YotiCA.crt', null))in Connector.php (line 44)
at Connector->createConnection('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', array('driver' => 'mysql', 'host' => 'it-db.internal.yoti.com', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipeit', 'password' => 'snipeit', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array('/etc/mysql/ssl/snipe-it.internal.yoti.com.key', '/etc/mysql/ssl/snipe-it.internal.yoti.com.crt', '/etc/mysql/ssl/YotiCA.crt', null), 'name' => 'mysql'), array(0, 2, 0, false, false, '/etc/mysql/ssl/snipe-it.internal.yoti.com.key', '/etc/mysql/ssl/snipe-it.internal.yoti.com.crt', '/etc/mysql/ssl/YotiCA.crt', null))in MySqlConnector.php (line 24)
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => 'it-db.internal.yoti.com', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipeit', 'password' => 'snipeit', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array('/etc/mysql/ssl/snipe-it.internal.yoti.com.key', '/etc/mysql/ssl/snipe-it.internal.yoti.com.crt', '/etc/mysql/ssl/YotiCA.crt', null), 'name' => 'mysql'))in ConnectionFactory.php (line 183)
at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
at call_user_func(object(Closure))in Connection.php (line 883)
at Connection->getPdo()in Connection.php (line 904)
at Connection->getReadPdo()in Connection.php (line 392)
at Connection->getPdoForSelect(true)in Connection.php (line 318)
at Connection->Illuminate\Database\{closure}('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in Connection.php (line 640)
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php (line 607)
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php (line 326)
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in MySqlBuilder.php (line 18)
at MySqlBuilder->hasTable('users')in Facade.php (line 221)
at Facade::__callStatic('hasTable', array('users'))in Setting.php (line 63)
at Setting::setupCompleted()in CheckForSetup.php (line 22)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

(1/4) PDOExceptionPDO::__construct(): Cannot connect to MySQL by using SSL
--
in PDOConnection.php (line 43)
at PDO->__construct('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', 'snipeit', 'snipeit', array(0, 2, 0, false, false, '/etc/mysql/ssl/snipe-it.internal.yoti.com.key', '/etc/mysql/ssl/snipe-it.internal.yoti.com.crt', '/etc/mysql/ssl/YotiCA.crt', null))in PDOConnection.php (line 43)
at PDOConnection->__construct('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', 'snipeit', 'snipeit', array(0, 2, 0, false, false, '/etc/mysql/ssl/snipe-it.internal.yoti.com.key', '/etc/mysql/ssl/snipe-it.internal.yoti.com.crt', '/etc/mysql/ssl/YotiCA.crt', null))in Connector.php (line 65)
at Connector->createPdoConnection('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', 'snipeit', 'snipeit', array(0, 2, 0, false, false, '/etc/mysql/ssl/snipe-it.internal.yoti.com.key', '/etc/mysql/ssl/snipe-it.internal.yoti.com.crt', '/etc/mysql/ssl/YotiCA.crt', null))in Connector.php (line 44)
at Connector->createConnection('mysql:host=it-db.internal.yoti.com;port=3306;dbname=snipeit', array('driver' => 'mysql', 'host' => 'it-db.internal.yoti.com', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipeit', 'password' => 'snipeit', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array('/etc/mysql/ssl/snipe-it.internal.yoti.com.key', '/etc/mysql/ssl/snipe-it.internal.yoti.com.crt', '/etc/mysql/ssl/YotiCA.crt', null), 'name' => 'mysql'), array(0, 2, 0, false, false, '/etc/mysql/ssl/snipe-it.internal.yoti.com.key', '/etc/mysql/ssl/snipe-it.internal.yoti.com.crt', '/etc/mysql/ssl/YotiCA.crt', null))in MySqlConnector.php (line 24)
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => 'it-db.internal.yoti.com', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipeit', 'password' => 'snipeit', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array('/etc/mysql/ssl/snipe-it.internal.yoti.com.key', '/etc/mysql/ssl/snipe-it.internal.yoti.com.crt', '/etc/mysql/ssl/YotiCA.crt', null), 'name' => 'mysql'))in ConnectionFactory.php (line 183)
at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
at call_user_func(object(Closure))in Connection.php (line 883)
at Connection->getPdo()in Connection.php (line 904)
at Connection->getReadPdo()in Connection.php (line 392)
at Connection->getPdoForSelect(true)in Connection.php (line 318)
at Connection->Illuminate\Database\{closure}('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in Connection.php (line 640)
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php (line 607)
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php (line 326)
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in MySqlBuilder.php (line 18)
at MySqlBuilder->hasTable('users')in Facade.php (line 221)
at Facade::__callStatic('hasTable', array('users'))in Setting.php (line 63)
at Setting::setupCompleted()in CheckForSetup.php (line 22)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

-----

#### Please confirm you have done the following before posting your bug report:

- [ X ] I have enabled debug mode 
- [ X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  Fresh install
- Version of Snipe-IT you're running 5.4.35
- Version of PHP you're running 
PHP 7.0.25-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.25-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
- Version of MySQL/MariaDB you're running
mysql  Ver 15.1 Distrib 10.1.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-09-18T15:09:02
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
(see above)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
initial setup page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by jelockwood** [comment]
Problem solved. It turns out SnipeIT is very fussy about the value of the DB_SSL_CIPHER.

**Comment by dkmansion** [comment]
@jelockwood Can you provide What the DB_SSL_CIPHER value was before and after resolution?  I am having this issue also and can't seem to identify what needs to be changed.  Thanks greatly!

**Comment by jelockwood** [comment]
@dkmansion 
I cannot be 100% certain what it was originally but I believe the commented line below is the default (original) value and the uncommented line is the current and working line.

```
DB_SSL_CIPHER='DHE-RSA-AES256-SHA:AES128-SHA'
#DB_SSL_CIPHER=DHE-RSA-AES256-GCM-SHA384
```

**Comment by dkmansion** [comment]
I will give this a try.  Using the resulting string from this command in Mysql
 `SHOW SESSION STATUS LIKE 'Ssl_cipher'; `
didn't help

Will give this a further try... Thanks greatly for the quick response!

**Comment by jelockwood** [comment]
Its probably a matter of either looking at the my.cnf config file on the MariaDB server to see what setting it is using or on the server locally accessing via the mysql command and doing as follows -

`show session status like '%cipher';`
