### ISSUE TITLE
Sort Within Snipe-It Licenses

### ISSUE THREAD

**Issue by abarrineau** [snipe/snipe-it#5055]
#### Expected Behavior (or desired behavior if a feature request)

(Within licenses, be able to sort taken seats by alphabetical order)

-----

#### Actual Behavior

(No sortable features within licenses)

**Comment by snipe** [comment]
That's unfortunately a little trickier than it seems, since licenses can be checked out to users or assets, which means we have to order across two different tables.

**Comment by snipe** [comment]
Duplicate of #2892
