### ISSUE TITLE
Using Snipe-IT on mobile?

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#5056]
I have a question for those of you that use the mobile-friendly UI on your phones, tablets, etc. 

We use an extension of Bootstrap Table that displays table data in a [mobile-friendly card view](https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions/mobile), so it's easier to scroll through. 

Normal:

<img width="1287" alt="screen shot 2018-02-20 at 3 44 37 pm" src="https://user-images.githubusercontent.com/197404/36455478-0c374c0c-1655-11e8-993f-135cd602c144.png">

Mobile responsive extension:

<img width="502" alt="screen shot 2018-02-20 at 3 44 18 pm" src="https://user-images.githubusercontent.com/197404/36455474-061f6f7a-1655-11e8-9456-4093e250ccc8.png">

The challenge here is that there isn't an easy way to sort in the mobile UI - at least none that I can see.  While we love the[ bootstrap table](https://github.com/wenzhixin/bootstrap-table/tree/develop/src/extensions) library, the documentation can be a bit sparse, so if anyone knows of a way to keep the card view but also enable sorting, I'd love to hear it. 

Would it be more useful to skip the card view? The tables are still responsive, you scroll across in the table content to view info that is further right than your screen canvas can display.

<img width="501" alt="screen shot 2018-02-20 at 3 46 39 pm" src="https://user-images.githubusercontent.com/197404/36455541-681c810e-1655-11e8-9d28-197c21644ff8.png">

**Comment by snipe** [comment]
Anyone have any thoughts here?

**Comment by snipe** [comment]
![crickets-chirp](https://user-images.githubusercontent.com/197404/36506668-2214bb06-170c-11e8-81d4-740cd77ec81d.gif)

**Comment by EarlRamirez** [comment]
@snipe I would try this out in a few days and provide some feedback

**Comment by k2trf** [comment]
I've not used the mobile interface myself, but looking at the bootstrap-table issues board, somebody had a similar thought. Its still marked open but sounds like they were able to make tables sort.

https://github.com/wenzhixin/bootstrap-table/issues/3602

**Comment by lostmydog** [comment]
I like the way it is. One feature however that would make a huge difference would be the ability to scan assets with a mobile device. Currently I scan the assets with an app, then go back and type them all in at my desk.

**Comment by k2trf** [comment]
That would be a new issue/request, so it doesn't get lost. But I'm pretty sure that will already work if you have a scanner/reader that will activate in your browser.
