### ISSUE TITLE
Feature Request: Check-in/ Check-out mail notification sent to more than 1 email address

### ISSUE THREAD

**Issue by cslucian** [snipe/snipe-it#5057]
#### Expected Behavior (or desired behavior if a feature request)

It would be great if there was an option so the Check-in/ Check-out mail notification can be sent to the actual user and to another specific address eg: inventory@company.com.

In our company we have a specific workflow and more than 1 person should be notified by inventory movement

-----

#### Actual Behavior

Check-in/ Check-out mail notification is sent only to the actual user than the asset was Check-in/ Check-out.

------

**Comment by Jhamende** [comment]
Was looking for that option too. Tried to brute force the destination within the Controllers but didn't manage to do it. 
I need to add Human Ressources Dep into the destinations or Cc so they are able to act when necessary.

**Comment by mahesh2471990** [comment]
There must be an option we can enable mail to a manager. If that is enabled, the manager will also get the notification mail of the same check-in/check-out.

Please do add this feature it's very helpful and needful. This will take the product to the next level.

This doesn't need much time I guess.  @snipe Please consider this as my vote.
I have heard from many other customers is looking for this feature

**Comment by berilslv** [comment]
It would be very usefull, as you can change email template  as check-in/out act with evidence in your servicedesk email. 
Lets bring this feature up! (y)
