### ISSUE TITLE
Snipe-IT Interface

### ISSUE THREAD

**Issue by alalialiahmad** [snipe/snipe-it#5058]
Hi everybody,

I just install the Snipe-IT on an Ubuntu server.

But the web interface seems not loading properly!!

Any help?

![interface](https://user-images.githubusercontent.com/25143763/36469129-a3508dce-16ff-11e8-95fc-75ed53368d64.jpg)

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by smyap3** [comment]
Hi,

I hope you don't mind me piggybacking on this as I am experiencing the exact same issue and do not want to spam the threads with a duplicate question.

Version of Snipe-IT you're running - version 4.1.14 build 3382
What OS and web server you're running Snipe-IT on - Ubuntu 16.04 running apache
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - github and then install.sh
If you're getting an error in your browser, include that error - no errors
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - from index.php to any other links like "New Asset"
If a stacktrace is provided in the error, include that too.
Any errors that appear in your browser's error console. - just the error for the Cert being invalid which I usually just bypass and say "go to site" 
Confirm whether the error is reproduceable on the demo.
Include any additional information you can find in app/storage/logs and your webserver's logs.
Include what you've done so far in the installation, and if you got any error messages along the way. - had some errors regarding SSL which thanks to this forum, i was able to resolve by setting up SSL and fixing my directoryroot.
Indicate whether or not you've manually edited any data directly in the database - no

thanks in advance.

**Comment by smyap3** [comment]
woo.. sorry spoke to soon.. 
the page loads nicely when i am on https://ipaddress
as soon as I click on any option e.g. New Asset which points to 


> https://ipaddress/hardware/create

I get `Not Found, The requested URL /hardware/create was not found on this server.`

If i change that URL to
> https://ipaddress/index.php/hardware/create

I see the page but the interface has no formatting or not the fancy one as per the op posted originally

**Comment by snipe** [comment]
Sounds like maybe mod_rewrite isn't enabled?

**Comment by smyap3** [comment]
thanks for your swift response.
All looks good on that front.

`Module rewrite already enabled`

i see the symlink and also have `AllowedOverride All` in `/etc/apache2/sites-available/snipeit.conf`

**Comment by smyap3** [comment]
Found the issue!
It was enabled in .htaccess and snipeit.conf but not in /etc/apache2/apache.conf

Thanks!

**Comment by snipe** [comment]
Woot!
