### ISSUE TITLE
Localisation setting not respected when doing LDAP sync to import new accounts

### ISSUE THREAD

**Issue by jelockwood** [snipe/snipe-it#5059]
#### Expected Behavior (or desired behavior if a feature request)
SnipeIT has a setting to define the localisation setting for the installed copy of SnipeIT, this defines the language preference and it is presumed might have an influence on the data format a user sees.

However when an LDAP sync is done the imported accounts all are imported as English, US despite the fact that I have set the server setting to English, UK.
(what you expect to happen goes here)
Localisation preference of new or imported users to be set to the server defined setting. However if edited they should save and respect any change made to an edited account.
-----

#### Actual Behavior
All accounts imported via LDAP sync default to English, US regardless of server setting.
(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ X ] I have enabled debug mode 
- [ X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running v4.1.11-pre - build 3307 (master)
- Version of PHP you're running
PHP 7.0.25-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.25-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
- Version of MySQL/MariaDB you're running
mysql  Ver 15.1 Distrib 10.1.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-09-18T15:09:02
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I'm not sure that's necessarily expected behavior though. We have the settings separately to be able to facilitate companies that use multiple languages across multiple companies. If I were working in the China office, I'm not sure I'd want to import people in the UK with Chinese as the default. I suppose it could be assumed that's what would happen, but not sure if that's going to mess people up.

(Also, there's not really much difference between US English and UK English, since currency settings were moved to the database.)
