### ISSUE TITLE
Item seems to be marked RTD but not showing up in RTD list

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#506]
Searched in all the Asset views, only one it shows up in is List All.

Let me know what other info I can provide or if you see where we've done something wrong.

![image](https://cloud.githubusercontent.com/assets/10247644/6140904/f9d613f0-b16b-11e4-9f56-71eed1b33d10.png)
![image](https://cloud.githubusercontent.com/assets/10247644/6140916/1a5823ca-b16c-11e4-93d4-a25364bd8ed6.png)

**Comment by snipe** [comment]
You ran the migrations, correct?

**Comment by kobie-chasehansen** [comment]
Yes, ran when I went to beta. even grabbed the dev code and ran all of it again.

**Comment by snipe** [comment]
Do you have access to query your database? I'm curious what the values are for that record (barring anything secret, of course).

**Comment by kobie-chasehansen** [comment]
Yes if you can help with the right query to run

**Comment by snipe** [comment]
Specifically curious about `status_id` and `assigned_to`.

**Comment by snipe** [comment]
Just do `select * from assets where id=<WHATEVERTHEIDOFTHATASSETID>;`

**Comment by snipe** [comment]
So if the url if the asset is http://demo.snipeitapp.com/hardware/3/view, you would query:

`select * from assets where id=3;`

**Comment by kobie-chasehansen** [comment]
![image](https://cloud.githubusercontent.com/assets/10247644/6140983/28e90034-b16d-11e4-963a-1d0a2d608ece.png)

**Comment by snipe** [comment]
Hrm. That migration should have taken care of that.

There is a line that says 

`DB::statement('update ' . DB::getTablePrefix() . 'assets SET assigned_to=NULL where assigned_to=0');`

Which should have updated all of your assigned_to 0 values to null.

Can you run this

`update assets SET assigned_to=NULL where assigned_to=0`

And tell me if that's any better?

**Comment by kobie-chasehansen** [comment]
Yep good now.

So this should have been picked up when I ran "php artisan migrate"?

When switched to the beta I remember seeing two things that were processed when I ran that command.

**Comment by snipe** [comment]
Yeah, I think maybe it didn't run because I may have used the wrong language for DB::. I used `DB::statement` versus `DB::update`. I just pushed out a fix that I hope should fix the issue for people moving forward.

**Comment by snipe** [comment]
You can see the new stuff in this version here, btw: http://snipeitapp.com/2015/02/1-2-4-beta-now-available-new-status-labels/

It's a minor update, but cleans up some less than awesome data structures that were leftover from the very beginning. 

(When I originally wrote this thing, I had NO idea that actual people would want to use it, so I wrote with only myself and my use-cases in mind.)

**Comment by kobie-chasehansen** [comment]
great, thanks.

You've made a great product and so far we are loving it. It has caused a lot of work for our desktop team because we've started down the road of one of the most detailed inventories in our history to get things setup right. They needed something to do anyways... Thanks for keeping the project active.

**Comment by snipe** [comment]
Haha yeah. The initial setup can be horrible if you've never used an asset manager. Lots of data entry. but it's also really beneficial, I think. When I first created this software, going through the inventory forced me to realize just how many of our assets were missing. I think by the time I was done, there were almost 20 laptops that we simply couldn't locate. All Macbook Pros or Airs. Tough thing to face, but better to realize it and quantify (and fix it moving forward) it than not know. :-/
