### ISSUE TITLE
Import CSV with username will not check it out

### ISSUE THREAD

**Issue by xarly** [snipe/snipe-it#5061]
#### Expected Behavior (or desired behavior if a feature request)

I have imported users from ActiveDirectory. Also I have populated first Model Names, Manufacturers, and Categories. 

Import a assets csv with these fields
Asset Tag,Status,Model Name,Manufacturer,Serial Number,Category,Username

For example:
```
Asset Tag,Status,Model Name,Manufacturer,Serial Number,Category,Username
COMWSPT0122,Ready to Deploy,HP EliteBook 850,Hewlett-Packard,2RO06543462,Workstation,ABC1234Z
```
(If I search ABC1234Z in People, I can find the user exactly with that username)

So it should create a new asset, assign tag, sn, model, manufacturer,category and **check it out to username**, changing also _Ready to Deploy_ to _Deployed_

-----

#### Actual Behavior

It creates a new asset, assign tag, sn, model, manufacturer,category but **no username**, also it leaves the asset in Ready to Deploy

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Fresh**
- Version of Snipe-IT you're running  **v4.1.10 - build 3249 (master)**
- Version of PHP you're running **PHP 7.0.25**
- Version of MySQL/MariaDB you're running  **mysql  Ver 15.1 Distrib 10.2.13-MariaDB**
- What OS and web server you're running Snipe-IT on **Ubuntu 16.0.4 / nginx 1.10.3**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **install.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **Importer**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database **NO**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by danr12** [comment]
I'm experiencing the same issue, I posted a few days ago https://github.com/snipe/snipe-it/issues/5031

**Comment by xarly** [comment]
I have captured mysql querys of import process, I see fields filled (well, only Model number, but manufacturer and category depend on it) but no reference to user.

Log here
https://gist.github.com/xarly/066aaa9a0a9183064ddb25cfb0dde7a6

**Comment by snipe** [comment]
> Version of Snipe-IT you're running 5.4.35

That can't be true, since Snipe-IT v4.1.14 is the latest. Can you try updating and see if you're still having this issue?

**Comment by xarly** [comment]
Yes sorry, it was Laravel version I think

Snipe Version: v4.1.10 - build 3249 (master)

**Comment by xarly** [comment]
Still not checking out in 4.1.14

**Comment by wastingaeons** [comment]
I am experiencing this same issue on 4.1.14

**Comment by getschools** [comment]
Chiming in with the same issue. Imported assets will not check out to their associated username.
Version v4.1.14 - build 3391 (master)

**Comment by blackrandom** [comment]
I'm also experiencing this issue, also on v4.1.14 but on running Windows Server 2012.
My issue is closer to #4942 but if I can get it to work this way that would be fine as well.

**Comment by cornwella** [comment]
Same issue here on 4.1.14. Leaving `Status` blank and designating a `Username` causes it to be created with the "Pending" status. Entering a `Status` updates it properly, but still doesn't check it out to the designated user.
