### ISSUE TITLE
Supplier location maps via Google Maps API not working

### ISSUE THREAD

**Issue by jelockwood** [snipe/snipe-it#5062]
Please update the SnipeIT documentation to indicate that you need to manually enable your Google Maps API project/key to support the Google Static Maps API.

This API is _not_ enabled by default, you have to browse the Maps API catalogue and manually enable it.

Until I found and did this maps did not work within SnipeIT even though I have a valid API key entered in to my .env

**Comment by snipe** [comment]
That is [already documented here](https://snipe-it.readme.io/docs/common-issues#section-google-maps-not-loading).
