### ISSUE TITLE
Unable to sync users from Active Directory

### ISSUE THREAD

**Issue by patit72** [snipe/snipe-it#5063]
#### Expected Behavior (or desired behavior if a feature request)

Import users from Active Directory

-----

#### Actual Behavior

LDAP configuration and login test work fine. When I try to sync users from AD I get "The username field is required." Same error  with `php artisan snipeit:ldap-sync --summary`. Connection and query work fine with `ldapsearch`

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Fresh install**
- Version of Snipe-IT you're running  **v4.1.11-pre  build 3344 (g99205bf)**
- Version of PHP you're running **7.0.27-0+deb9u1**
- Version of MySQL/MariaDB you're running **10.1.26-0+deb9u1**
- What OS and web server you're running Snipe-IT on **Debian 9**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **git**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **No error**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs. **No additional info**
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Sounds like the field you have for your LDAP username is incorrect. What do you have?

**Comment by patit72** [comment]
![2018-02-22 08_28_03-update ldap_ad settings __ sama asset managment](https://user-images.githubusercontent.com/16647912/36525456-63c320a8-17aa-11e8-9791-fd6ef603d281.png)

**Comment by patit72** [comment]
![2018-02-22 08_41_27-samsrvgc3 - connessione desktop remoto](https://user-images.githubusercontent.com/16647912/36525951-827b5964-17ac-11e8-84f5-040a15fe9bc1.png)

**Comment by patit72** [comment]
![2018-02-22 08_41_27-samsrvgc3 - connessione desktop remoto](https://user-images.githubusercontent.com/16647912/36525994-a8e16cec-17ac-11e8-971a-32ce1359e061.png)

**Comment by CronKz** [comment]
Try this - works for me:
´Username field´ = ´samaccountname´ => NOT ´sAMAccountName=´

**Comment by patit72** [comment]
Already tried, I'm afraid it doesn't work either

**Comment by CronKz** [comment]
My LDAP Filter also differs from yours:
`&(sAMAccountType=805306368)(objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2))`

**Comment by patit72** [comment]
Same error. Actually, your addition seems redundant to me, as (sAMAccountType=805306368) already filters users objects and according to MS: _the filter (sAMAccountType=805306368) for user objects is more efficient than the more usual filter, but is harder to remember._ 
[https://social.technet.microsoft.com/wiki/contents/articles/5392.active-directory-ldap-syntax-filters.aspx?Sort=MostRecent](url)

**Comment by patit72** [comment]
As you can see users are filtered correctly, it seems that it doesn't know what to use to fill the username field
![2018-02-22 12_17_35-ldap user sync __ sama asset managment](https://user-images.githubusercontent.com/16647912/36535572-743ee85c-17ca-11e8-8aee-fd8d003a5e25.png)

**Comment by CronKz** [comment]
@patit72 Oh well you're right, thanks for that 😄
But again, are you sure that you have set "Username Field" to "samaccountname" and NOT TO "samaccountname=" ?
Because if I use "samaccountname=" I get the exact same error as you. Removing the "=" is essential in this case!

**Comment by patit72** [comment]
Shame on me! That was it! Thank you very much for your patience!

**Comment by CronKz** [comment]
I'm glad I could help 😄 cheers.
