### ISSUE TITLE
Added asset but it does not get listed under assets

### ISSUE THREAD

**Issue by jelockwood** [snipe/snipe-it#5065]
#### Expected Behavior (or desired behavior if a feature request)
I have created a model, a manufacturer, categories, and suppliers. It seems some of these are compulsory in order to create assets.
I then added a new first ever asset, this SnipeIT claimed was successful. The dashboard does indeed reflect this, also if I search for the asset number it is found. However no matter how I try I cannot get the Asset section to list this new asset.
I am attaching some screen captures to illustrate this.
Note: Turning on debug did not provide any useful information.
(what you expect to happen goes here)
I expect the newly added asset to be listed under assets.
-----

#### Actual Behavior
The newly added asset is not listed under asset of any type, nor under accessories or any other entry. The only way to find the asset is to do a global search for the asset number.
(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ X ] I have enabled debug mode 
- [ X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running v4.1.11-pre - build 3307 (master)
- Version of PHP you're running
PHP 7.0.25-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.25-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
- Version of MySQL/MariaDB you're running
mysql  Ver 15.1 Distrib 10.1.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-09-18T15:09:02
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
No
![asset tab of an asset](https://user-images.githubusercontent.com/4300786/36483031-efeee5f6-170c-11e8-97da-d2e9fecca6cd.png)
![filter for all types of asset and all records](https://user-images.githubusercontent.com/4300786/36483033-f01a6d02-170c-11e8-9afe-efe034ed49b2.png)
![filter for asset number of all types of asset](https://user-images.githubusercontent.com/4300786/36483034-f03b47c0-170c-11e8-8ce1-c681417f9fab.png)
![asset via global search](https://user-images.githubusercontent.com/4300786/36483035-f0623f42-170c-11e8-962b-d220dacdfd94.png)

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.


- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Include any additional information you can find in storage/logs and your webserver's logs.

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by jelockwood** [comment]
I didn't delete them but did not answer (some) of those.

I as I did indicate I did have debug turned on, no errors were reported _at all_ in the browser
Hence no stack trace to report either.
No errors appear in the browser - with or without debug on
/var/log/apache2/snipeIT.error.log is empty (it is working because I can see an archived copy of this log from the past which did have different errors in it)
/var/log/apache2/access.log does seem to have some relevant entries as below


10.222.1.50 - - [21/Feb/2018:15:08:10 +0000] "GET /hardware/7/edit HTTP/1.1" 200 18549 "https://snipe-it.internal.yoti.com/hardware/7" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
10.222.1.50 - - [21/Feb/2018:15:08:10 +0000] "GET /api/v1/statuslabels/2/deployable HTTP/1.1" 200 562 "https://snipe-it.internal.yoti.com/hardware/7/edit" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
10.222.1.50 - - [21/Feb/2018:15:08:14 +0000] "GET /api/v1/locations/selectlist?page=1 HTTP/1.1" 200 729 "https://snipe-it.internal.yoti.com/hardware/7/edit" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
10.222.1.50 - - [21/Feb/2018:15:08:32 +0000] "POST /hardware/7 HTTP/1.1" 200 1124 "https://snipe-it.internal.yoti.com/hardware/7/edit" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
10.222.1.50 - - [21/Feb/2018:15:08:32 +0000] "GET /hardware/7 HTTP/1.1" 200 19455 "https://snipe-it.internal.yoti.com/hardware/7/edit" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
10.222.1.50 - - [21/Feb/2018:15:08:33 +0000] "GET /api/v1/hardware?assigned_to=7&assigned_type=App%5CModels%5CAsset&order=asc&offset=0&limit=20 HTTP/1.1" 500 21463 "https://snipe-it.internal.yoti.com/hardware/7" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
10.222.1.50 - - [21/Feb/2018:15:08:33 +0000] "GET /api/v1/reports/activity?item_id=7&item_type=asset&order=desc&offset=0&limit=20 HTTP/1.1" 200 5471 "https://snipe-it.internal.yoti.com/hardware/7" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
10.222.1.50 - - [21/Feb/2018:16:06:09 +0000] "GET /hardware HTTP/1.1" 200 20200 "https://snipe-it.internal.yoti.com/hardware/7" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
10.222.1.50 - - [21/Feb/2018:16:06:09 +0000] "GET /uploads/logo.jpg HTTP/1.1" 304 210 "https://snipe-it.internal.yoti.com/hardware" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
10.222.1.50 - - [21/Feb/2018:16:06:09 +0000] "GET /api/v1/hardware?status=&order_number=&company_id=&status_id=&order=name&offset=0&limit=20 HTTP/1.1" 500 21463 "https://snipe-it.internal.yoti.com/hardware" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
10.222.1.50 - - [21/Feb/2018:16:06:30 +0000] "GET /api/v1/hardware?status=&order_number=&company_id=&status_id=&order=name&offset=0&limit=20 HTTP/1.1" 500 21600 "https://snipe-it.internal.yoti.com/hardware" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
10.222.1.50 - - [21/Feb/2018:16:06:30 +0000] "GET /hardware HTTP/1.1" 200 17520 "https://snipe-it.internal.yoti.com/hardware/7" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
10.222.1.50 - - [21/Feb/2018:16:06:30 +0000] "GET /api/v1/hardware?status=&order_number=&company_id=&status_id=&order=name&offset=0&limit=20 HTTP/1.1" 500 21463 "https://snipe-it.internal.yoti.com/hardware" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
10.222.1.50 - - [21/Feb/2018:16:06:40 +0000] "GET /uploads/assets/c61j76WaELTBxs3m01SKMQqBz.png HTTP/1.1" 304 349 "https://snipe-it.internal.yoti.com/hardware/11" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
10.222.1.50 - - [21/Feb/2018:16:06:40 +0000] "GET /hardware/bytag?assetTag=Y01692&topsearch=true HTTP/1.1" 302 1556 "https://snipe-it.internal.yoti.com/hardware" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
10.222.1.50 - - [21/Feb/2018:16:06:40 +0000] "GET /hardware/11 HTTP/1.1" 200 19435 "https://snipe-it.internal.yoti.com/hardware" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
10.222.1.50 - - [21/Feb/2018:16:06:40 +0000] "GET /uploads/assets/c61j76WaELTBxs3m01SKMQqBz.png HTTP/1.1" 304 211 "https://snipe-it.internal.yoti.com/hardware/11" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
10.222.1.50 - - [21/Feb/2018:16:06:40 +0000] "GET /hardware/11/qr_code HTTP/1.1" 200 1371 "https://snipe-it.internal.yoti.com/hardware/11" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
10.222.1.50 - - [21/Feb/2018:16:06:40 +0000] "GET /api/v1/reports/activity?item_id=11&item_type=asset&order=desc&offset=0&limit=20 HTTP/1.1" 200 1233 "https://snipe-it.internal.yoti.com/hardware/11" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
10.222.1.50 - - [21/Feb/2018:16:06:40 +0000] "GET /api/v1/hardware?assigned_to=11&assigned_type=App%5CModels%5CAsset&order=asc&offset=0&limit=20 HTTP/1.1" 500 21463 "https://snipe-it.internal.yoti.com/hardware/11" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"

Ah! Some really interesting stuff in /var/www/snipeit/storage/logs/laravel.log

[laravel.log](https://github.com/snipe/snipe-it/files/1744691/laravel.log)

I did try with debug enabled again and still got nothing in the browser itself. However as you can see there seems to be a problem as shown in the laravel.log

**Comment by jelockwood** [comment]
Is this possibly related to 

Known Issues

Users running MariaDB 10.2.7 and later may have an issue upgrading or installing, due to a change in the way MariaDB stores null defaults. This issue will be fixed once the open pull request in the Doctrine repo is merged and a new version of Doctrine is released with these fixes. You can read more about that issue here https://github.com/doctrine/dbal/pull/2825 .

**Comment by snipe** [comment]
```
[2018-02-21 16:08:25] production.ERROR: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'order clause' in /var/www/snipeit/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77
```

That's pretty unusual. Do you have any custom fields created?

**Comment by snipe** [comment]
Additionally, if you sort by any of the other columns, do you see results and/or any new errors in the laravel.log? (Please just paste them here - do not attach a file)

**Comment by jelockwood** [comment]
Yes I had started defining some custom fields. I tried do delete them within SnipeIT and got errors and the delete failed, I was however able to delete them directly within MariaDB. After I did this SnipeIT did then correctly list the assets.

Now we know it was to do with custom fields what sort of test do you want me to do specific to that? Or is this as I suggested to do with the 'known issue' to do with Doctrine. (Which is not listed in the Common Issues document.)

**Comment by jelockwood** [comment]
The asset tab of an asset is still empty which does not seem to make sense. Other than that having deleted the custom fields everything seems to be working. (Except LDAP and active accounts which is a different ticket.)

**Comment by snipe** [comment]
Making manual changes to the database is generally never a good idea. There are complex relationships between fields, and deleting something in one place manually often leaves a references to it in other places that will break things. 

If you deleted custom fields manually, make sure you delete them from the `custom_fields` table, remove the relationships from the `custom_field_custom_fieldset` table, and drop the `__snipeit__` columns in your assets table.

**Comment by jelockwood** [comment]
Yes, I only manually edited the database because I could not use or not use or delete the custom fields within SnipeIT itself. Once I deleted them from custom_fields and custom_field_custom_fieldset manually SnipeIt resumed working.

I have not tried re-adding any custom fields since, as I mentioned earlier in this issue, is there specific tests for custom fields you would like me to try?

**Comment by snipe** [comment]
Custom fields works as intended, so I do wish you’d have opened an issue when you ran into a problem the first time if you didn’t, as this error is basically erroneous.

Did you drop the columns from the assets table as well?

Try creating custom fields normally and see if you can reproduce the original issue.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
