### ISSUE TITLE
Import History match username option

### ISSUE THREAD

**Issue by xarly** [snipe/snipe-it#5067]
#### Expected Behavior (or desired behavior if a feature request)

I use a custom username normalization like ABC1234Z.

Since Import does not get username, I was going to try Import History, and map usernames(uid/samaccountname) with usernames(snipe synced).

-----

#### Actual Behavior

Import Hitory only allows:

-  Try to match users by firstname.lastname (jane.smith) format
-  Try to match users by first initial last name (jsmith) format
-  Try to match users by first name (jane) format
-  Try to match users by email as username

So, I feel it misses the obvious option:
-  Try to match users by **username** as username

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Fresh**
- Version of Snipe-IT you're running  **5.4.35**
- Version of PHP you're running **PHP 7.0.25**
- Version of MySQL/MariaDB you're running  **mysql  Ver 15.1 Distrib 10.2.13-MariaDB**
- What OS and web server you're running Snipe-IT on **Ubuntu 16.0.4 / nginx 1.10.3**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **install.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **Importer**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database **NO**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
You should just be able to use the "first name" format then. Since it's not adding a user, it will just take whatever that value is and do nothing with it.

```
public static function generateFormattedNameFromFullName($format = 'filastname', $users_name)
    {
        list($first_name, $last_name) = explode(" ", $users_name, 2);

        // Assume filastname by default
        $username = str_slug(substr($first_name, 0, 1).$last_name);
        
        if ($format=='firstname.lastname') {
            $username = str_slug($first_name).'.'.str_slug($last_name);

        } elseif ($format=='firstname_lastname') {
            $username = str_slug($first_name).'_'.str_slug($last_name);

        } elseif ($format=='firstname') {
            $username = str_slug($first_name);
        }

        $user['first_name'] = $first_name;
        $user['last_name'] = $last_name;
        $user['username'] = strtolower($username);
        return $user;
    }
```

**Comment by xarly** [comment]
Looks like it does not work very well.....

I have imported assets with Importer, and ownership with Import History.

Import History reported success in all lines, but after that there is no associations in asset list, Check out to is still blank, but Asset History shows:

![image](https://user-images.githubusercontent.com/152981/36494982-10442cae-1734-11e8-8839-928358158e18.png)

Also, Asset is bugged and cannot be checkout or checked in any more
![image](https://user-images.githubusercontent.com/152981/36495025-3326ac42-1734-11e8-8512-56b795481c09.png)

Completely bugged :(

**Comment by snipe** [comment]
If you edit `app/Http/Controllers/AssetsController.php` line 854 from:

```
$asset->assigned_to = $user->id;
```

to 

```
$asset->assigned_to = $user->id;
$asset->assigned_type = User::class;
 $asset->last_checkout = $item[$asset_tag][$batch_counter]['checkout_date'];
```

And run the import again, does that have any effect?

**Comment by xarly** [comment]
Yes, looks good!

![image](https://user-images.githubusercontent.com/152981/36528327-fa91a1f8-17b4-11e8-831f-e05b5c2ce529.png)

**Comment by xarly** [comment]
BUT, after that I have upgraded to 4.1.14, and then, with the same csv headers but other assets:
```

(1/1) ErrorExceptionUndefined offset: 1
--
in User.php (line 333)
at HandleExceptions->handleError(8, 'Undefined offset: 1', '/opt/snipe-it/app/Models/User.php', 333, array('format' => 'filastname', 'users_name' => 'ABC1234Z', 'first_name' => 'MPM8377L'))in User.php (line 333)
at User::generateFormattedNameFromFullName('filastname', 'ABC1234Z')in AssetsController.php (line 807)
at AssetsController->postImportHistory(object(Request))
at call_user_func_array(array(object(AssetsController), 'postImportHistory'), array(object(Request)))in Controller.php (line 55)
at Controller->callAction('postImportHistory', array(object(Request)))in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(AssetsController), 'postImportHistory')in Route.php (line 203)
```
![image](https://user-images.githubusercontent.com/152981/36533050-b9c332aa-17c2-11e8-93cb-2c3fd35717e1.png)

**Comment by xarly** [comment]
I have reverted https://github.com/snipe/snipe-it/commit/62edf14893844b53ebb51a107be6007d3a19a3c9
and worked again

**Comment by snipe** [comment]
I’ll get that fixed for you today

**Comment by snipe** [comment]
I have a fix on develop for you, will merge shortly. (The method wasn't accounting for single names, in your example, ABC1234Z.
