### ISSUE TITLE
Can Not create Read-only group for assets

### ISSUE THREAD

**Issue by jbloomer** [snipe/snipe-it#5068]
#### Expected Behavior (or desired behavior if a feature request)

Create a group that has view only permissions for Assets. User assigned to that role will be able to view all Assets in the system. 

-----

#### Actual Behavior

Create group with the following Asset permissions

 Allow Assets: view
 Deny Assets: create
 Deny Assets: edit
 Deny Assets: delete
 Allow Assets: checkin
 Allow Assets: checkout
 Allow Assets: audit
 Allow Assets: view: requestable

Users assigned to this group are only able to see Assets they created. 

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Git upgrade
- Version of Snipe-IT you're running v4.1.13 build 3374
- Version of PHP you're running 5.6.33
- Version of MySQL/MariaDB you're running AWS Aurora RDS
- What OS and web server you're running Snipe-IT on Centos 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
> Users assigned to this group are only able to see Assets they created.

We don't have any mechanism within the system to do that. In fact, it's a feature request people ask for. 

Check and see if you have full company support enabled. If you do, users will only be able to see assets that belong to the same company they belong to.

**Comment by jbloomer** [comment]
Got it. The Full Company Support was hosing me up. Unchecking that box gave me what I was looking for.

**Comment by snipe** [comment]
Awesome! Glad to hear you're all sorted. In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
