### ISSUE TITLE
Request for Filipino Translation

### ISSUE THREAD

**Issue by vinzruzell** [snipe/snipe-it#5069]
Hi. I would like to request for filipino and tagalog Translations.

**Comment by snipe** [comment]
We've created those target languages in CrowdIn for you:

https://crowdin.com/project/snipe-it/fil
https://crowdin.com/project/snipe-it/tl

**Comment by vinzruzell** [comment]
Hi sir, Thank you for you response. This is a very important project for me
sir and I will make good translation for this.

May I request also to enable me as PROOFREADER for this project sir? I
promise to give you the best translation as I can.
I have proofreaded and contributed translation in different projects.

Thank you.

**Comment by snipe** [comment]
I am not a sir, but if you tell me your CrowdIn name, I can add you as a proofreader.

**Comment by vinzruzell** [comment]
Hi my crowdin name is vinzruzell thank you. :)

**Comment by vinzruzell** [comment]
Hi.I would like to ask. Since. Im am still translator in my profile. :)
