### ISSUE TITLE
Help need to develop as like as snipe-it using dot net

### ISSUE THREAD

**Issue by kajal-alpha** [snipe/snipe-it#5071]
anyone can you help me to develop ats project using dotnet. i want to develop asset management portal like as snipe-it. i have create some model class following snipe-it database. now i need help to complete it. 

my project link -> [https://gitlab.com/touristbd/dev-ats](https://gitlab.com/touristbd/dev-ats)

it will be web based application. i am using ASP.NET MVC, EF, Razor 

Thanks

**Comment by snipe** [comment]
This topic isn't really relevant (and is far too involved) for this repo. You might try asking on Bountysource or [CodeTriage](https://www.codetriage.com).
