### ISSUE TITLE
Unable to get Docker container to work- Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by nnolan** [snipe/snipe-it#5074]
#### Expected Behavior (or desired behavior if a feature request)

Two containers on my local - 
1.) the snipe-it container provided on kitematic
2.) a mysql container on local to work with the snipe-it container

-----

#### Actual Behavior

Both containers are running and the mysql container is associated to the snipe-it container. Receiving the oh so frustrating, "Whoops, looks like something went wrong." 

-----

#### Please confirm you have done the following before posting your bug report:

- [yes] I have enabled debug mode 
- [yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
Fresh Install
- Version of Snipe-IT you're running
4.1.10
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
5.6
- What OS and web server you're running Snipe-IT on
n/a
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

(4/4) QueryExceptionSQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (SQL: select * from information_schema.tables where table_schema = ${MYSQL_DATABASE} and table_name = users)
--
in Connection.php (line 647)
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('${MYSQL_DATABASE}', 'users'), object(Closure))in Connection.php (line 607)
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('${MYSQL_DATABASE}', 'users'),object(Closure))in Connection.php (line 326)
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('${MYSQL_DATABASE}', 'users'))in MySqlBuilder.php (line 18)
at MySqlBuilder->hasTable('users')in Facade.php (line 221)
at Facade::__callStatic('hasTable', array('users'))in Setting.php (line 63)
at Setting::setupCompleted()in CheckForSetup.php (line 22)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

(3/4) PDOExceptionSQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known
--
in PDOConnection.php (line 47)
at PDOConnection->__construct('mysql:host=${MYSQL_PORT_3306_TCP_ADDR};port=3306;dbname=${MYSQL_DATABASE}', '${MYSQL_USER}', '${MYSQL_PASSWORD}', array(0, 2, 0, false, false))in Connector.php (line 65)
at Connector->createPdoConnection('mysql:host=${MYSQL_PORT_3306_TCP_ADDR};port=3306;dbname=${MYSQL_DATABASE}', '${MYSQL_USER}', '${MYSQL_PASSWORD}', array(0, 2, 0, false, false))in Connector.php (line 44)
at Connector->createConnection('mysql:host=${MYSQL_PORT_3306_TCP_ADDR};port=3306;dbname=${MYSQL_DATABASE}', array('driver' => 'mysql', 'host' => '${MYSQL_PORT_3306_TCP_ADDR}', 'port' => '3306', 'database' => '${MYSQL_DATABASE}', 'username' => '${MYSQL_USER}', 'password' => '${MYSQL_PASSWORD}', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array(), 'name' => 'mysql'), array(0, 2, 0, false, false))in MySqlConnector.php (line 24)
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => '${MYSQL_PORT_3306_TCP_ADDR}', 'port' => '3306', 'database' => '${MYSQL_DATABASE}', 'username' => '${MYSQL_USER}', 'password' => '${MYSQL_PASSWORD}', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' =>false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array(), 'name' => 'mysql'))in ConnectionFactory.php (line 183)
at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
at call_user_func(object(Closure))in Connection.php (line 883)
at Connection->getPdo()in Connection.php (line 904)
at Connection->getReadPdo()in Connection.php (line 392)
at Connection->getPdoForSelect(true)in Connection.php (line 318)
at Connection->Illuminate\Database\{closure}('select * from information_schema.tables where table_schema = ? and table_name = ?',array('${MYSQL_DATABASE}', 'users'))in Connection.php (line 640)
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('${MYSQL_DATABASE}', 'users'), object(Closure))in Connection.php (line 607)
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('${MYSQL_DATABASE}', 'users'),object(Closure))in Connection.php (line 326)
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('${MYSQL_DATABASE}', 'users'))in MySqlBuilder.php (line 18)
at MySqlBuilder->hasTable('users')in Facade.php (line 221)
at Facade::__callStatic('hasTable', array('users'))in Setting.php (line 63)
at Setting::setupCompleted()in CheckForSetup.php (line 22)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

(2/4) PDOExceptionSQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known
--
in PDOConnection.php (line 43)
at PDO->__construct('mysql:host=${MYSQL_PORT_3306_TCP_ADDR};port=3306;dbname=${MYSQL_DATABASE}', '${MYSQL_USER}', '${MYSQL_PASSWORD}', array(0, 2, 0, false, false))in PDOConnection.php (line 43)
at PDOConnection->__construct('mysql:host=${MYSQL_PORT_3306_TCP_ADDR};port=3306;dbname=${MYSQL_DATABASE}', '${MYSQL_USER}', '${MYSQL_PASSWORD}', array(0, 2, 0, false, false))in Connector.php (line 65)
at Connector->createPdoConnection('mysql:host=${MYSQL_PORT_3306_TCP_ADDR};port=3306;dbname=${MYSQL_DATABASE}', '${MYSQL_USER}', '${MYSQL_PASSWORD}', array(0, 2, 0, false, false))in Connector.php (line 44)
at Connector->createConnection('mysql:host=${MYSQL_PORT_3306_TCP_ADDR};port=3306;dbname=${MYSQL_DATABASE}', array('driver' => 'mysql', 'host' => '${MYSQL_PORT_3306_TCP_ADDR}', 'port' => '3306', 'database' => '${MYSQL_DATABASE}', 'username' => '${MYSQL_USER}', 'password' => '${MYSQL_PASSWORD}', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array(), 'name' => 'mysql'), array(0, 2, 0, false, false))in MySqlConnector.php (line 24)
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => '${MYSQL_PORT_3306_TCP_ADDR}', 'port' => '3306', 'database' => '${MYSQL_DATABASE}', 'username' => '${MYSQL_USER}', 'password' => '${MYSQL_PASSWORD}', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' =>false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array(), 'name' => 'mysql'))in ConnectionFactory.php (line 183)
at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
at call_user_func(object(Closure))in Connection.php (line 883)
at Connection->getPdo()in Connection.php (line 904)
at Connection->getReadPdo()in Connection.php (line 392)
at Connection->getPdoForSelect(true)in Connection.php (line 318)
at Connection->Illuminate\Database\{closure}('select * from information_schema.tables where table_schema = ? and table_name = ?',array('${MYSQL_DATABASE}', 'users'))in Connection.php (line 640)
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('${MYSQL_DATABASE}', 'users'), object(Closure))in Connection.php (line 607)
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('${MYSQL_DATABASE}', 'users'),object(Closure))in Connection.php (line 326)
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('${MYSQL_DATABASE}', 'users'))in MySqlBuilder.php (line 18)
at MySqlBuilder->hasTable('users')in Facade.php (line 221)
at Facade::__callStatic('hasTable', array('users'))in Setting.php (line 63)
at Setting::setupCompleted()in CheckForSetup.php (line 22)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

(1/4) PDOExceptionPDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known
--
in PDOConnection.php (line 43)
at PDO->__construct('mysql:host=${MYSQL_PORT_3306_TCP_ADDR};port=3306;dbname=${MYSQL_DATABASE}', '${MYSQL_USER}', '${MYSQL_PASSWORD}', array(0, 2, 0, false, false))in PDOConnection.php (line 43)
at PDOConnection->__construct('mysql:host=${MYSQL_PORT_3306_TCP_ADDR};port=3306;dbname=${MYSQL_DATABASE}', '${MYSQL_USER}', '${MYSQL_PASSWORD}', array(0, 2, 0, false, false))in Connector.php (line 65)
at Connector->createPdoConnection('mysql:host=${MYSQL_PORT_3306_TCP_ADDR};port=3306;dbname=${MYSQL_DATABASE}', '${MYSQL_USER}', '${MYSQL_PASSWORD}', array(0, 2, 0, false, false))in Connector.php (line 44)
at Connector->createConnection('mysql:host=${MYSQL_PORT_3306_TCP_ADDR};port=3306;dbname=${MYSQL_DATABASE}', array('driver' => 'mysql', 'host' => '${MYSQL_PORT_3306_TCP_ADDR}', 'port' => '3306', 'database' => '${MYSQL_DATABASE}', 'username' => '${MYSQL_USER}', 'password' => '${MYSQL_PASSWORD}', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array(), 'name' => 'mysql'), array(0, 2, 0, false, false))in MySqlConnector.php (line 24)
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => '${MYSQL_PORT_3306_TCP_ADDR}', 'port' => '3306', 'database' => '${MYSQL_DATABASE}', 'username' => '${MYSQL_USER}', 'password' => '${MYSQL_PASSWORD}', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' =>false, 'engine' => null, 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array(), 'name' => 'mysql'))in ConnectionFactory.php (line 183)
at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
at call_user_func(object(Closure))in Connection.php (line 883)
at Connection->getPdo()in Connection.php (line 904)
at Connection->getReadPdo()in Connection.php (line 392)
at Connection->getPdoForSelect(true)in Connection.php (line 318)
at Connection->Illuminate\Database\{closure}('select * from information_schema.tables where table_schema = ? and table_name = ?',array('${MYSQL_DATABASE}', 'users'))in Connection.php (line 640)
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('${MYSQL_DATABASE}', 'users'), object(Closure))in Connection.php (line 607)
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('${MYSQL_DATABASE}', 'users'),object(Closure))in Connection.php (line 326)
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('${MYSQL_DATABASE}', 'users'))in MySqlBuilder.php (line 18)
at MySqlBuilder->hasTable('users')in Facade.php (line 221)
at Facade::__callStatic('hasTable', array('users'))in Setting.php (line 63)
at Setting::setupCompleted()in CheckForSetup.php (line 22)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
I attempted to follow all of the installation steps for setting up the docker container
- Indicate whether or not you've manually edited any data directly in the database
The database was spun using the snipe-it container
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

PLEASE HELP

**Comment by nnolan** [comment]
@uberbrady 
Hey Brady, did you get a chance to review this? 

Thank you

**Comment by uberbrady** [comment]
It looks like some of your environment variables might be missing - `MYSQL_DATABASE` and maybe `MYSQL_PORT_3306_TCP_ADDR`.

Unfortunately, I'm not that well-versed in how Kitematic works; I use the docker CLI. But is there a way where you can get to a list of environment variables that you're loading, screenshot it - blurring out anything sensitive - maybe we'll be able to see what's going wrong from there?

**Comment by nnolan** [comment]
Hello Brady,

I apologize for the delay. I have gone ahead and just implemented this via
the docker CLI. I was able to successfully get the container up and running
locally. I am now attempting to run this service on an AWS EC2 instance,
simply by pulling the container down from the Docker Hub repository. I was
able to do this and get the container running, but I am unsure where to
point to IP address. Should this be the private IP of the EC2 instance?


Thank you,
-Nathan

**Comment by jnmcfly** [comment]
Hello folks,

had the same issue when deploying via docker-compose. In my case i didn't set the `MYSQL_PORT_3306_TCP_ADDR`.

Its a bit curious..
The documentation on (https://snipe-it.readme.io/docs/docker) says:
`docker run -d -p YOUR_PORT_NUMBER:80 --name="snipeit" --link snipe-mysql:mysql --env-file=my_env_file snipe/snipe-it` so I thought the APP-Container assume the internal hostname for dbhost as "mysql" (because of the alias set in ` --link` option)

But I failed with this configuration in my docker-compose.yml. Im not using the `env_file` as documented. 

So i figgured out that I have to set the `MYSQL_PORT_3306_TCP_ADDR` in the `environment` section 

Here is my currently working Snipe-It docker-compose file: https://github.com/jnmcfly/Snipe-ITcompose

-Jan

**Comment by uberbrady** [comment]
Hrm. Weird. 

Maybe the latest Docker changes no longer handle the 'link' business properly - I know they had started to move away from that option, but perhaps now they're no longer setting the environment variables? That weird, funky name - `MYSQL_PORT_3306_TCP_ADDR` - that was Docker-generated, not me.

I'm going to have to go through a new Docker setup locally and see what I can find.

**Comment by NetZero** [comment]
As far as I remember, I know this as an error that is typical when localhost is not mapped to 127.0.0.1 in /etc/hosts anymore. Just a guess.

**Comment by uberbrady** [comment]
@nnolan the `APP_URL` should match what your web browser puts in the URL bar to browse to the site. Unless you have a weird VPN setup, it probably shouldn't be the private IP, it should be the public IP (or public hostname if you have a DNS name set up for the site).

**Comment by josephsmartinez** [comment]
> Hello folks,
> 
> had the same issue when deploying via docker-compose. In my case i didn't set the `MYSQL_PORT_3306_TCP_ADDR`.
> 
> Its a bit curious..
> The documentation on (https://snipe-it.readme.io/docs/docker) says:
> `docker run -d -p YOUR_PORT_NUMBER:80 --name="snipeit" --link snipe-mysql:mysql --env-file=my_env_file snipe/snipe-it` so I thought the APP-Container assume the internal hostname for dbhost as "mysql" (because of the alias set in ` --link` option)
> 
> But I failed with this configuration in my docker-compose.yml. Im not using the `env_file` as documented.
> 
> So i figgured out that I have to set the `MYSQL_PORT_3306_TCP_ADDR` in the `environment` section
> 
> Here is my currently working Snipe-It docker-compose file: https://github.com/jnmcfly/Snipe-ITcompose
> 
> -Jan

Thank you
