### ISSUE TITLE
Ready to deploy and Deployed asset listing empty

### ISSUE THREAD

**Issue by paulo1624** [snipe/snipe-it#5075]
I noticed there is no updated list of assets on Ready to deploy and Deployed tab under Assets dropdown list. But if you look on my All assets there is a number of assets have assigned status deployed and ready to Deploy. Kindly help me to solve this problem. Thank You

#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help
List of all assets.
![image](https://user-images.githubusercontent.com/32555803/36514190-4bc449ba-17ae-11e8-9130-b50a781564ae.png)

Under ready to deploy assets
![image](https://user-images.githubusercontent.com/32555803/36514213-6735e622-17ae-11e8-8b36-9b77ef1fb822.png)

Under Deployed Assets
![image](https://user-images.githubusercontent.com/32555803/36514230-7e450816-17ae-11e8-8649-663d2a1d2f7a.png)

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by paulo1624** [comment]
I'am using Centos 7.4.1708 (core), server version: apache/2.4.6, snipe-it version 4.1.13.

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by paulo1624** [comment]
still not updated the deployed assets.
![image](https://user-images.githubusercontent.com/32555803/36573183-916776be-187a-11e8-859d-36c7841ffda5.png)

**Comment by snipe** [comment]
@paulo1624 until you answer our questions, we're not going to be able to help you.
