### ISSUE TITLE
LDAP AD doesn't sync selected OU

### ISSUE THREAD

**Issue by korio77** [snipe/snipe-it#5078]
When trying to sync an OU from our LDAP AD snipeit is syncing random users from other OU's

A bit of pics to explin a bit better:

This is our current LDAP AD in the AD server:
![image](https://user-images.githubusercontent.com/20576635/36540729-bf9981e8-17db-11e8-9f75-f40018b66128.png)

We have users from the OU's "ES - Art" and "ES - Tec", in the past i just went to the admin config for LDAP, change the Base Bind DN and select the corresponding location while syncing and it worked.

Now this is what is going on, if i set the Base Bind DN to sync from "ES - Art" it syncs a lot of users from there, but not all.

If i set the Base Bind DN to sync from "ES - Tec" it syncs random users from "ES - Art" and none from "ES - Tec", but if i try to log with any user from "ES - Art" they cant, and users from "ES - Tec" are able to log.

Here is a pic of AD users of "ES - Tec"
![image](https://user-images.githubusercontent.com/20576635/36540894-690a9f6e-17dc-11e8-9ef4-df982d7993aa.png)

And here is a pic of what Snipeit is syncing:

![image](https://user-images.githubusercontent.com/20576635/36540929-819fdf76-17dc-11e8-8af4-07d2c31e61dc.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [ Y] I have enabled debug mode 
- [ y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Bit of both, fresh git install with old manual install data
- Version of Snipe-IT you're running Latest master Version v4.1.14 - build 3382 (master)
- Version of PHP you're running 7.1.7
- Version of MySQL/MariaDB you're running Mysql
- What OS and web server you're running Snipe-IT on Windows Server 2012 with IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Git
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error No errors
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. No errors
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs. Nothing in the php or lavarel logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database No manual edits

**Comment by CronKz** [comment]
In the LDAP Settings => Set "Base bind Dn" to
"OU=ES - Domain,OU=WhatEverYouUse,DC=companyName,DC=com"
Then for each individual Location:
Edit the Location in Snipe-IT - for example the "Es - Tec" Location
and set "LDAP OU Search" to
"OU=ES - Tec,OU=ES - Domain,OU=WhatEverYouUse,DC=companyName,DC=com"

Then on Persons => LDAP Sync => Now choose the Location => And snyc

**Comment by korio77** [comment]
If i do that, it will sync all the folders of the first pic, i just want 2.

Thats why i was changing it by hand, on the "ES - Art" i have subfolders with their LDAP Search OU correctly adjusted.

In the "ES - Tec" folder are just users, there are not subfolders and the location has the LDAP OU Search too.

I dont want the other folders to sync anything, thats why i dont have the parent folder directly on the LDAP config.

**Comment by Mynty100** [comment]
It may help to know you can search by security group.
Fill in to suit your AD, OU and DC structures. you can search for 1, 2 3+ groups as you see fit.

Your base DN should aim at the root DC=Test,DC=com,DC=au

TEST-SG = Name of the security group that users are apart of that you would like to import.
LDAP Filer:

&(objectClass=user)(|(memberof=CN=TEST-SG1,OU=Security Groups,OU=TEST,DC=TEST,DC=com,DC=au)(memberof=CN=TEST_SG2,OU=Security Groups,OU=TEST,DC=test,DC=com,DC=au))

Let us know if this was any help. This is how we import users and works.

**Comment by korio77** [comment]
Thanks for that @Mynty100 

I combined it with my LDAP filter and it works, if i test it on my LDAP server it works and shows the users on the group.


But, when i go and try it on snipeit, i am getting a new error message.

Here is a little pic.

![image](https://user-images.githubusercontent.com/20576635/36676785-de789f7a-1b0c-11e8-90ac-00916cf92159.png)


I dont really know why and im doing a little testing, i have not seen an error like this regarding LDAP here and i dont know if its only related to the latest version of snipeit, @snipe any clues?

**Comment by snipe** [comment]
@korio77 I believe that issue was already fixed. See #4923.

**Comment by korio77** [comment]
@snipe i have checked the issue you linked and my installation of snipe already have that change.

Having in mind this picture:

![image](https://user-images.githubusercontent.com/20576635/36725952-4caab68a-1bb8-11e8-929a-e932eb6b6076.png)


If i set the base DN to the "ES - Domain" OU, it shows the error.

If i set the base DN to one of the children of the "ES - Domain" OU, for example, "ES - Art" it works.

Any clue?

**Comment by Mynty100** [comment]
My gut feels like permissions on your LDAP Bind User is not allowed search in that OU

Back only see if this helps.

![image](https://user-images.githubusercontent.com/34461276/36763074-27c52b24-1c72-11e8-8a95-9806ebcaa67a.png)

change to suit your setup. But this should work.

Keep in mind I don't assume you have TLS setup etc so uptick or tick appropriately :)

Cheers.

**Comment by korio77** [comment]
I had thought that too, privilege stuff.

But if i set the Base bind DN to the one giving the error, and use the snipeit test of login and binding, everything works fine.

I have also checked the privileges of the user in both OU's and are identical.

As soon as i have time i will try to change the user to LDAP syntax, right now we are using domain\user syntax in that field.

Regards.

**Comment by korio77** [comment]
Hi again @snipe @Mynty100 

I have changed the user to use the AD syntax, connection to LDAP is successfull.

But, when i test an user it works, if i remove it from the group of the LDAP filter, it's successfull too.

I dont know what is going on, does the test button on the LDAP config have in mind the Filter?

**Comment by Mynty100** [comment]
@korio77 I believe, but unsure. The test simple checks that the service account can successfully search AD. 
Can you now perform the LDAP Sync??

**Comment by korio77** [comment]
Hi @Mynty100 

unfortunately the same error.

**Comment by Mynty100** [comment]
![image](https://user-images.githubusercontent.com/34461276/36951372-b3f38426-204e-11e8-842c-afb52d0cac1a.png)
If you haven't already tried this fix. cant install or copy the file off server and edit it with Notepad++ this will enable you to find and edit line 192. 
Other wise seems strange that is work when searching in Specific OU over the Base. This just tells me is permission issue. or Settings on the base OU preventing search. 

Like said earlier you can set locations to search only those OU's. When creating a Location there is an option to put the 'distinguishedName' of the OU you wish to search. Think of Locations like departments. Then when creating the department in Snipe IT link its location to that Location.

Hope this helps and makes sense. 
Cheers.

**Comment by korio77** [comment]
Hi @Mynty100 

I have also the feeling that is something about permisions of the user, im going to do a couple test and see if with other user or aplications it works.

OU's in locations are correctly assigned, but i have some locations without OU's, this shouldn't be a problem.

That piece of code snipe pointed out was already on my installation of snipe, i am in the latest production version and its already implemented.

**Comment by pompushko** [comment]
Hehe
I think i have same issue after upgrading from 10 to 14 version

`In LdapSync.php line 193:

  Trying to get property of non-object`

**Comment by korio77** [comment]
I have tried with the same config we have in another app that is working, and with snipeit i get the same error as before.

@snipe i think there is something not working properly, can you give it a look?

Regards

**Comment by samotelf** [comment]
I have solved it by following other user instructions in gitter.im by editing the file LdapSync.php like this:

elseif ((isset($location)) && (!empty($location))) {
                    $user->location_id = e($location['id']);

and then editing memory size = -1 in php.ini.

Cheers! And thank you who helped me.

**Comment by pompushko** [comment]
Hehe, it help me too.06.03.2018, 02:30, "samotelf" <notifications@github.com>:I have solved it by following other user instructions in gitter.im by editing the file LdapSync.php like this:
elseif ((isset($location)) && (!empty($location))) {
$user->location_id = e($location['id']);
and then editing memory size = -1 in php.ini.
Cheers! And thank you who helped me.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




-- С уважением,Артём Рощеня+375(44)772-00-70

**Comment by korio77** [comment]
After adding that commit @snipe  everything is working like a charm.

Thank you and everyone for the help!
