### ISSUE TITLE
No such file or directory in /var/www/html/snipeit/bootstrap/autoload.php on line 17

### ISSUE THREAD

**Issue by anmohamed** [snipe/snipe-it#5079]
php artisan config:clear
PHP Warning:  require(/var/www/html/snipeit/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/snipeit/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/html/snipeit/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipeit/bootstrap/autoload.php on line 17

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/installation-issues
