### ISSUE TITLE
Interface Improvement - Software Licenses Screen

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#508]
When viewing the software licenses where multiple seats exists it doesn't list the licenses in order considering the seat count.

![image](https://cloud.githubusercontent.com/assets/10247644/6141373/845d4e5c-b172-11e4-98ac-2d95c01ae155.png)

**Comment by snipe** [comment]
Now you're just looking for things to bug me with :P

**Comment by kobie-chasehansen** [comment]
You know, I almost didn't post this one lol. Was going to wait a few weeks but figured why not get it in the queue. :)

**Comment by snipe** [comment]
LOL it's all good. :)

**Comment by snipe** [comment]
Huh... that actually orders correctly for me... 
![screen shot 2015-02-10 at 7 25 35 pm](https://cloud.githubusercontent.com/assets/197404/6141455/a8771984-b15a-11e4-9709-ea73951611ec.png)

I'll try to figure it out.

**Comment by snipe** [comment]
Ohh, I see - that's on the overview page, not the details view.

**Comment by kobie-chasehansen** [comment]
Yeah, wish I had some ideas on improving that view. I've loaded a bulk of our licenses in and the list view is pretty useless, end up having to search them out anyways. 

Maybe some kind of way to list all of the products with a how many seats available status without actually listing all the seats?

**Comment by snipe** [comment]
I've been trying to crack that nut for a while myself. If I only show how many seats, it means it takes one more click to actually check a seat out to someone. :(

**Comment by kobie-chasehansen** [comment]
Think that extra click may be worth it... at least with our use case. As it stands right now we are either paging thru or searching out the software titles. If the seats werent shown we would only have 5-8 licenses and could click right into it. I wonder how many users would actually have more than one page worth of licenses if they are displaying 50 or even 25 items at a time.

**Comment by snipe** [comment]
And that's a fair point. Anyone else want to weigh in?

**Comment by kobie-chasehansen** [comment]
Looks great, thanks!

**Comment by diwanicki** [comment]
issue #330?
