### ISSUE TITLE
Feature Request: Ability to add multiple Custom Fieldsets to Assets, Components, Licenses etc

### ISSUE THREAD

**Issue by blackout1231** [snipe/snipe-it#5083]
#### Expected Behavior (or desired behavior if a feature request)
Currently you can only add one Custom Fieldset to (example) Assets
(what you expect to happen goes here)
The ability to add multiple Custom Fieldsets to Assets, Components, Accessories etc
-----

#### Actual Behavior
Currently you can only add one Custom Fieldset to (example) Assets
(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're runningv 4.1.10 build 3249 (g8d3a214)
- Version of PHP you're running 7.0.23
--
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
What's the use case here? You can add as many fields to field sets as you need, so I'm wondering what problem this would solve.

**Comment by blackout1231** [comment]
Currently (and this may just be that I need to do more testing/training) the only way I can see the fieldsets I create is by attaching them to (in this case) Assets. Is there another way to get my Custom Fieldsets to show in that drop down menu so they are visible?

![image](https://user-images.githubusercontent.com/34345402/36611608-b18dd27a-1899-11e8-860b-ef18cac6e759.png)

![image](https://user-images.githubusercontent.com/34345402/36611583-9b188daa-1899-11e8-9cd8-f763b28fdfe3.png)

![image](https://user-images.githubusercontent.com/34345402/36611543-77b7662e-1899-11e8-9c26-9f7d0a2b57d0.png)

**Comment by snipe** [comment]
Custom fieldsets are assigned at the asset model level.

**Comment by blackout1231** [comment]
Gotcha, I guess I would like to see the ability to add more than one. In my particular environment, we got some mavericks that want to deviate from what is available on the static fields.

The ability to add additional custom fieldsets would be extremely helpful.

I hope I'm explaining it correctly=/

**Comment by snipe** [comment]
I still don't really understand the use case here though. You can just create multiple custom field sets as needed.

**Comment by blackout1231** [comment]
Well, if I add a custom fieldset to an Asset, I can only add one. 

In my case, we need to be able to look up the location of in stock inventory at each site we manage.

This custom fieldset is for example:

"Additional Description"

I can add that to an Asset and now have that field available. However, I may need to add another custom fieldset that shows other information, for example: a description of that that asset is, does etc. and call that "Equipment Description" and assign it to that Asset.

Currently (from my understanding and testing), I can only add one custom fieldset to an Asset.

I tried to help paint that picture with those screenshots I posted. Sorry If I'm not explaining myself correctly.

**Comment by snipe** [comment]
You an add one fieldset to an asset, but you can add unlimited fields to a fieldset, and fields can exist is multiple fieldsets.

So, for example, you could have one fieldset, which gets applied to call computer models, called "Computers", which has the following fields:
- RAM
- CPU
- Additional Notes
- FooBar

And then another fieldset called "Mobile Phones" which has the following:
- IMEI
- Additional Notes
- FooBar

**Comment by blackout1231** [comment]
I think I got you. I'll mess around with this a little more.

Thank you!

**Comment by blackout1231** [comment]
Okay, I got exactly what you're saying, I'm good from here!

Thank you!!!

**Comment by snipe** [comment]
![miyakai-party](https://user-images.githubusercontent.com/197404/36618072-99e3f88e-189e-11e8-8911-b50fbeeaac9a.gif)

Awesome! Glad to hear you're all sorted. In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)

**Comment by follet-git** [comment]
Hmm... today I become need more than one fieldset too. The main reason is to use one fieldset for ALL asset models and another for specific asset models (cpu/gpu/ram/ssd)... It will be good to improve this feature.

**Comment by EncyclopediaRed** [comment]
There's definitely an advantage and use case for multiple custom fieldsets for asset models. Even though you can add as many fields as you want to a fieldset, the point of the set is to categorize the fields contained within. The ability to set a custom fieldset to say all models and then have additional sets for groups of models, as mentioned above, like sets for mobile devices, desktops, etc., would be hugely helpful.

Additionally, the ability to add to existing default fieldsets could alleviate this request.

Also, being able to set the custom fieldsets' position on the asset's or model's page would help to keep like items together better. For example, a Leasing custom fieldset that allows the user to set leased or purchased status, lease end dates, etc., would likely want to be placed near the Purchase Info default fieldset.

**Comment by EncyclopediaRed** [comment]
There's definitely an advantage and use case for multiple custom fieldsets for asset models. Even though you can add as many fields as you want to a fieldset, the point of the set is to categorize the fields contained within. The ability to set a custom fieldset to say all models and then have additional sets for groups of models, as mentioned above, like sets for mobile devices, desktops, etc., would be hugely helpful.

Additionally, the ability to add to existing default fieldsets could alleviate this request.

Also, being able to set the custom fieldsets' position on the asset's or model's page would help to keep like items together better. For example, a Leasing custom fieldset that allows the user to set leased or purchased status, lease end dates, etc., would likely want to be placed near the Purchase Info default fieldset.

**Comment by snipe** [comment]
> There's definitely an advantage and use case for multiple custom fieldsets for asset models. Even though you can add as many fields as you want to a fieldset, the point of the set is to categorize the fields contained within. 

That's not on the short term roadmap. By carefully laying out your fieldsets and models, this shouldn't really be needed.

> Additionally, the ability to add to existing default fieldsets could alleviate this request.

That is already possible and has been for quite some time.

**Comment by EncyclopediaRed** [comment]
Missing the adding to existing fieldsets is on me. I found it right after I posted, apologies for that. 

No worries about it not being on the short term roadmap. It seemed like something that could be useful in the future and cut down on having carefully curate one large fieldset however. Thanks!
