### ISSUE TITLE
Custom field for Assets question

### ISSUE THREAD

**Issue by cepacs** [snipe/snipe-it#5094]
I see that we can add a custom field set to Asset Models, but is it possible to add a custom field set to the Asset level, or even Asset Category level? 

We have extra information that we would like to record on every asset or possibly on every category without having to put in a custom field set on every model since that field contains hundreds of different models so it would make it easier at the Asset level or at least at the category level since it would be much smaller a list.

Thanks :)

**Comment by snipe** [comment]
That's not currently possible, but you should be able to easily bulk edit your models to update them all with your field sets in one shot.

**Comment by cepacs** [comment]
OK.. I'll give that a try then..  Thanks
