### ISSUE TITLE
No such file or directory in autoload.php on line 17

### ISSUE THREAD

**Issue by okkhalid** [snipe/snipe-it#5097]
Hi, I know you have addressed the issue here: https://snipe-it.readme.io/docs/install-dependencies

my hosting company is using: https://docs.plesk.com/en-US/12.5/administrator-guide/website-management/websites-and-domains/web-applications/managing-php-project-dependencies-with-composer.74969/

So they mentioned that The Composer utility is available as part of Plesk

I'm getting the following:
I have installed the latest version of v4.1.14
The project for our non for profit charity organization, I have trying to solve this issue since the morning now its 8 pm.

I got the following errors.

No such file or directory in /var/www/vhosts/mysite.ca/mysite.mysite.ca/bootstrap/autoload.php on line 17
Warning: require(/var/www/vhosts/mysite.ca/mysite.mysite.ca/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/mysite.ca/mysite.mysite.ca/bootstrap/autoload.php on line 17

Fatal error: require(): Failed opening required '/var/www/vhosts/mysite.ca/mysite.mysite.ca/bootstrap/../vendor/autoload.php' (include_path='.:/opt/plesk/php/5.6/share/pear') in /var/www/vhosts/mysite.ca/mysite.mysite.ca/bootstrap/autoload.php on line 17

Please help and guide me.

**Comment by snipe** [comment]
What is the output when you run composer?

**Comment by okkhalid** [comment]
Kindly find below I have used on browser composer.php  because my site is in shared drive. so I got the php file from this link: https://gist.github.com/odan/3f5b2748f516398e93cb36716d38b6b5

The result in my site:

Run: composer install
<info>Loading composer repositories with package information</info>
<info>Installing dependencies from lock file</info>
<info>Package operations: 86 installs, 0 updates, 0 removals</info>
- Installing <info>symfony/finder</info> (<comment>v3.4.4</comment>): Downloading (<comment>100%</comment>)
- Installing <info>symfony/polyfill-mbstring</info> (<comment>v1.7.0</comment>): Downloading (<comment>100%</comment>)
- Installing <info>symfony/var-dumper</info> (<comment>v3.4.4</comment>): Downloading (<comment>100%</comment>)
- Installing <info>psr/log</info> (<comment>1.0.2</comment>): Downloading (<comment>100%</comment>)
- Installing <info>maximebf/debugbar</info> (<comment>1.13.1</comment>): Downloading (<comment>100%</comment>)
- Installing <info>vlucas/phpdotenv</info> (<comment>v2.4.0</comment>): Downloading (<comment>100%</comment>)
- Installing <info>symfony/css-selector</info> (<comment>v3.1.10</comment>): Downloading (<comment>100%</comment>)
- Installing <info>tijsverkoyen/css-to-inline-styles</info> (<comment>2.2.1</comment>): Downloading (<comment>100%</comment>)
- Installing <info>symfony/routing</info> (<comment>v3.4.4</comment>): Downloading (<comment>100%</comment>)
- Installing <info>symfony/process</info> (<comment>v3.4.4</comment>): Downloading (<comment>100%</comment>)
- Installing <info>paragonie/random_compat</info> (<comment>v2.0.11</comment>): Downloading (<comment>100%</comment>)
- Installing <info>symfony/polyfill-php70</info> (<comment>v1.7.0</comment>): Downloading (<comment>100%</comment>)
- Installing <info>symfony/http-foundation</info> (<comment>v3.4.4</comment>): Downloading (<comment>100%</comment>)
- Installing <info>symfony/event-dispatcher</info> (<comment>v3.4.4</comment>): Downloading (<comment>100%</comment>)
- Installing <info>symfony/debug</info> (<comment>v3.4.4</comment>): Downloading (<comment>100%</comment>)
- Installing <info>symfony/http-kernel</info> (<comment>v3.4.4</comment>): Downloading (<comment>100%</comment>)
- Installing <info>symfony/console</info> (<comment>v3.4.4</comment>): Downloading (<comment>100%</comment>)
- Installing <info>swiftmailer/swiftmailer</info> (<comment>v5.4.9</comment>): Downloading (<comment>100%</comment>)
- Installing <info>ramsey/uuid</info> (<comment>3.7.3</comment>): Downloading (<comment>100%</comment>)
- Installing <info>symfony/translation</info> (<comment>v3.4.4</comment>): Downloading (<comment>100%</comment>)
- Installing <info>nesbot/carbon</info> (<comment>1.22.1</comment>): Downloading (<comment>100%</comment>)
- Installing <info>mtdowling/cron-expression</info> (<comment>v1.2.1</comment>): Downloading (<comment>100%</comment>)
- Installing <info>monolog/monolog</info> (<comment>1.23.0</comment>): Downloading (<comment>100%</comment>)
- Installing <info>league/flysystem</info> (<comment>1.0.42</comment>): Downloading (<comment>100%</comment>)
- Installing <info>erusev/parsedown</info> (<comment>1.6.4</comment>): Downloading (<comment>100%</comment>)
- Installing <info>doctrine/inflector</info> (<comment>v1.1.0</comment>): Downloading (<comment>100%</comment>)
- Installing <info>laravel/framework</info> (<comment>v5.4.35</comment>): Downloading (<comment>100%</comment>)
- Installing <info>barryvdh/laravel-debugbar</info> (<comment>v2.4.3</comment>): Downloading (<comment>100%</comment>)
- Installing <info>doctrine/lexer</info> (<comment>v1.0.1</comment>): Downloading (<comment>100%</comment>)
- Installing <info>doctrine/annotations</info> (<comment>v1.4.0</comment>): Downloading (<comment>100%</comment>)
- Installing <info>doctrine/cache</info> (<comment>v1.6.2</comment>): Downloading (<comment>100%</comment>)
- Installing <info>doctrine/collections</info> (<comment>v1.4.0</comment>): Downloading (<comment>100%</comment>)
- Installing <info>doctrine/common</info> (<comment>v2.7.3</comment>): Downloading (<comment>100%</comment>)
- Installing <info>doctrine/dbal</info> (<comment>v2.5.13</comment>): Downloading (<comment>100%</comment>)
- Installing <info>fideloper/proxy</info> (<comment>3.3.4</comment>): Downloading (<comment>100%</comment>)
- Installing <info>guzzlehttp/promises</info> (<comment>v1.3.1</comment>): Downloading (<comment>100%</comment>)
- Installing <info>psr/http-message</info> (<comment>1.0.1</comment>): Downloading (<comment>100%</comment>)
- Installing <info>guzzlehttp/psr7</info> (<comment>1.4.2</comment>): Downloading (<comment>100%</comment>)
- Installing <info>intervention/image</info> (<comment>2.4.1</comment>): Downloading (<comment>100%</comment>)
- Installing <info>jakub-onderka/php-console-color</info> (<comment>0.1</comment>): Downloading (<comment>100%</comment>)
- Installing <info>javiereguiluz/easyslugger</info> (<comment>v1.0.0</comment>): Downloading (<comment>100%</comment>)
- Installing <info>zendframework/zend-diactoros</info> (<comment>1.7.0</comment>): Downloading (<comment>100%</comment>)
- Installing <info>symfony/psr-http-message-bridge</info> (<comment>v1.0.2</comment>): Downloading (<comment>100%</comment>)
- Installing <info>phpseclib/phpseclib</info> (<comment>2.0.9</comment>): Downloading (<comment>100%</comment>)
- Installing <info>league/event</info> (<comment>2.1.2</comment>): Downloading (<comment>100%</comment>)
- Installing <info>lcobucci/jwt</info> (<comment>3.2.2</comment>): Downloading (<comment>100%</comment>)
- Installing <info>defuse/php-encryption</info> (<comment>v2.1.0</comment>): Downloading (<comment>100%</comment>)
- Installing <info>league/oauth2-server</info> (<comment>6.1.1</comment>): Downloading (<comment>100%</comment>)
- Installing <info>guzzlehttp/guzzle</info> (<comment>6.3.0</comment>): Downloading (<comment>100%</comment>)
- Installing <info>firebase/php-jwt</info> (<comment>v4.0.0</comment>): Downloading (<comment>100%</comment>)
- Installing <info>laravel/passport</info> (<comment>v3.0.2</comment>): Downloading (<comment>100%</comment>)
- Installing <info>nikic/php-parser</info> (<comment>v3.1.4</comment>): Downloading (<comment>100%</comment>)
- Installing <info>jakub-onderka/php-console-highlighter</info> (<comment>v0.3.2</comment>): Downloading (<comment>100%</comment>)
- Installing <info>dnoegel/php-xdg-base-dir</info> (<comment>0.1</comment>): Downloading (<comment>100%</comment>)
- Installing <info>psy/psysh</info> (<comment>v0.8.17</comment>): Downloading (<comment>100%</comment>)
- Installing <info>laravel/tinker</info> (<comment>v1.0.3</comment>): Downloading (<comment>100%</comment>)
- Installing <info>laravelcollective/html</info> (<comment>v5.4.9</comment>): Downloading (<comment>100%</comment>)
- Installing <info>league/csv</info> (<comment>8.2.2</comment>): Downloading (<comment>100%</comment>)
- Installing <info>maknz/slack</info> (<comment>1.7.0</comment>): Downloading (<comment>100%</comment>)
- Installing <info>neitanod/forceutf8</info> (<comment>v2.0.1</comment>): Downloading (<comment>100%</comment>)
- Installing <info>patchwork/utf8</info> (<comment>v1.3.1</comment>): Downloading (<comment>100%</comment>)
- Installing <info>phpdocumentor/reflection-common</info> (<comment>1.0.1</comment>): Downloading (<comment>100%</comment>)
- Installing <info>phpdocumentor/type-resolver</info> (<comment>0.3.0</comment>): Downloading (<comment>100%</comment>)
- Installing <info>sebastian/recursion-context</info> (<comment>2.0.0</comment>): Downloading (<comment>100%</comment>)
- Installing <info>sebastian/exporter</info> (<comment>2.0.0</comment>): Downloading (<comment>100%</comment>)
- Installing <info>sebastian/diff</info> (<comment>1.4.3</comment>): Downloading (<comment>100%</comment>)
- Installing <info>sebastian/comparator</info> (<comment>1.2.4</comment>): Downloading (<comment>100%</comment>)
- Installing <info>webmozart/assert</info> (<comment>1.3.0</comment>): Downloading (<comment>100%</comment>)
- Installing <info>phpdocumentor/reflection-docblock</info> (<comment>3.2.2</comment>): Downloading (<comment>100%</comment>)
- Installing <info>doctrine/instantiator</info> (<comment>1.0.5</comment>): Downloading (<comment>100%</comment>)
- Installing <info>phpspec/prophecy</info> (<comment>v1.6.2</comment>): Downloading (<comment>100%</comment>)
- Installing <info>symfony/polyfill-util</info> (<comment>v1.7.0</comment>): Downloading (<comment>100%</comment>)
- Installing <info>symfony/polyfill-php56</info> (<comment>v1.7.0</comment>): Downloading (<comment>100%</comment>)
- Installing <info>christian-riesen/base32</info> (<comment>1.3.1</comment>): Downloading (<comment>100%</comment>)
- Installing <info>pragmarx/google2fa</info> (<comment>v1.0.1</comment>): Downloading (<comment>100%</comment>)
- Installing <info>predis/predis</info> (<comment>v1.1.1</comment>): Downloading (<comment>100%</comment>)
- Installing <info>rollbar/rollbar</info> (<comment>v1.3.6</comment>): Downloading (<comment>100%</comment>)
- Installing <info>rollbar/rollbar-laravel</info> (<comment>v2.2.2</comment>): Downloading (<comment>100%</comment>)
- Installing <info>schuppo/password-strength</info> (<comment>v1.10</comment>): Downloading (<comment>100%</comment>)
- Installing <info>spatie/db-dumper</info> (<comment>1.5.1</comment>): Downloading (<comment>100%</comment>)
- Installing <info>spatie/laravel-backup</info> (<comment>3.11.0</comment>): Downloading (<comment>100%</comment>)
- Installing <info>tecnickcom/tc-lib-color</info> (<comment>1.12.8</comment>): Downloading (<comment>100%</comment>)
- Installing <info>tecnickcom/tc-lib-barcode</info> (<comment>1.15.7</comment>): Downloading (<comment>100%</comment>)
- Installing <info>tightenco/ziggy</info> (<comment>v0.4.1</comment>): Downloading (<comment>100%</comment>)
- Installing <info>unicodeveloper/laravel-password</info> (<comment>1.0.3</comment>): Downloading (<comment>100%</comment>)
- Installing <info>watson/validating</info> (<comment>3.1.2</comment>): Downloading (<comment>100%</comment>)
<info>Generating optimized autoload files</info>
Done.

**Comment by dmeltzer** [comment]
'/var/www/vhosts/mysite.ca/mysite.mysite.ca/bootstrap/../vendor/autoload.php' 

It looks like you have an extra level of nesting in there.. it should probably be /var/www/vhosts/mysite.ca/bootstrap, right?

Not sure why it's doing that, but it looks wrong to me.

**Comment by okkhalid** [comment]
I'm using sub domain, so I created a folder in the root, then I added to .htaccess

<IfModule mod_alias.c>
RedirectMatch 301 ^/$ http://mysite.mysite.ca/public
</IfModule>

and I added to .env

APP_ENV=production
APP_DEBUG=false
APP_KEY=4535242ljk2l34kj2lk34j243
APP_URL=http://mysite.mysite.ca/public
APP_TIMEZONE='UTC'
APP_LOCALE=en

**Comment by okkhalid** [comment]
Do I need to add something else to any files other than: .env and .htaccess?

**Comment by okkhalid** [comment]
for 2 days, not able to install it, I think I have give up.

**Comment by snipe** [comment]
public should never be in your APP_URL. I'm not sure what the problem is, exactly, since it looks like composer ran without an issue. You can try deleting the contents of the `bootstrap/cache` directory, and try running `composer dump-autoload` to try to clear any cached files.

**Comment by damianwayne7** [comment]
> What is the output when you run composer?

Same issue for me also

 Problem 1
    - Installation request for tecnickcom/tc-lib-barcode 1.15.20 -> satisfiable by tecnickcom/tc-lib-barcode[1.15.20].
    - tecnickcom/tc-lib-barcode 1.15.20 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.4/cli/php.ini
    - /etc/php/7.4/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.4/cli/conf.d/10-opcache.ini
    - /etc/php/7.4/cli/conf.d/10-pdo.ini
    - /etc/php/7.4/cli/conf.d/15-xml.ini
    - /etc/php/7.4/cli/conf.d/20-bz2.ini
    - /etc/php/7.4/cli/conf.d/20-calendar.ini
    - /etc/php/7.4/cli/conf.d/20-ctype.ini
    - /etc/php/7.4/cli/conf.d/20-curl.ini
    - /etc/php/7.4/cli/conf.d/20-dom.ini
    - /etc/php/7.4/cli/conf.d/20-exif.ini
    - /etc/php/7.4/cli/conf.d/20-ffi.ini
    - /etc/php/7.4/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.4/cli/conf.d/20-ftp.ini
    - /etc/php/7.4/cli/conf.d/20-gd.ini
    - /etc/php/7.4/cli/conf.d/20-gettext.ini
    - /etc/php/7.4/cli/conf.d/20-iconv.ini
    - /etc/php/7.4/cli/conf.d/20-json.ini
    - /etc/php/7.4/cli/conf.d/20-mbstring.ini
    - /etc/php/7.4/cli/conf.d/20-mysqli.ini
    - /etc/php/7.4/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.4/cli/conf.d/20-phar.ini
    - /etc/php/7.4/cli/conf.d/20-posix.ini
    - /etc/php/7.4/cli/conf.d/20-readline.ini
    - /etc/php/7.4/cli/conf.d/20-shmop.ini
    - /etc/php/7.4/cli/conf.d/20-simplexml.ini
    - /etc/php/7.4/cli/conf.d/20-sockets.ini
    - /etc/php/7.4/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.4/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.4/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.4/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.4/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.4/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.4/cli/conf.d/20-xsl.ini
    - /etc/php/7.4/cli/conf.d/20-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.





Above is the error when i try to install composer,

**Comment by snipe** [comment]
Install bcmath.

**Comment by anvar88at** [comment]
Warning: require(/home/vin3337506/viniks.net/docs/../controllers/bootstrap/autoload.php): failed to open stream: No such file or directory in /home/vin3337506/viniks.net/docs/index.php on line 22

Fatal error: require(): Failed opening required '/home/vin3337506/viniks.net/docs/../controllers/bootstrap/autoload.php' (include_path='.:/home/vin3337506/viniks.net/php') in /home/vin3337506/viniks.net/docs/index.php on line 22


I have problem with it. How to solve

**Comment by anvar88at** [comment]
<?php
require __DIR__.'/../controllers/bootstrap/autoload.php';
$app = require_once __DIR__.'/../controllers/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);

$response->send();

$kernel->terminate($request, $response);

**Comment by anvar88at** [comment]
<?php

require __DIR__.'/../controllers/bootstrap/autoload.php';


$app = require_once __DIR__.'/../bootstrap/app.php';

$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);

$response->send();

$kernel->terminate($request, $response);
