### ISSUE TITLE
Stuck for three weeks trying to get snipe IT to work.

### ISSUE THREAD

**Issue by sbenoit89** [snipe/snipe-it#5099]
I have been stuck three weeks trying to get a new Snipe-IT working please help me. My hair is totally pulled out this week and I am closed to balding. I have little experience with Centos and Snipe IT. Please help me.
When Launching Snipe-IT I am getting Uh-oh. Your /var/www/html/snipeit/storage directory (or sub-directories within) are not writable by the web-server. Those directories need to be writable by the web server in order for the app to work. 
I researched and use this command

sudo chmod -R 777 /var/www/html/snipeit/app/storage but still nothing.

I don't know how to do everything you requested; So bear with me. I tried to use your install guide from your website but it is convoluted. I decided to use this website https://www.mangolassi.it/topic/6967/installing-snipe-it-on-centos-7-and-mariadb/3

This is the command I used

setenforce 0 && mkdir -p /var/www/html; cd /var/www/html/; wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh && chmod 744 install.sh && ./install.sh && cd snipeit; sed -i "s/'timezone' => '',/'timezone' => 'UTC',/" app/config/app.php; php artisan app:install

I did get an error for app:install saving command not found can you please explain this and not reference the convoluted guide.

-----

- [ x] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh Install
- Version of Snipe-IT you're running Newest
- Version of PHP you're running referenced above
- Version of MySQL/MariaDB you're running referenced above
- What OS and web server you're running Snipe-IT on centos 7 on hyper v virtual machine
- manual installation
start up page triggered error for first time setting up.

**Comment by k2trf** [comment]
You need to make sure the user www-data owns the storage directory. You're also missing the public directory permissions.

```
chown -R www-data storage public/uploads
chmod -R 755 storage
chmod -R 755 public/uploads
```

Taken from https://snipe-it.readme.io/docs/configuration

Personally I did my install on an Ubuntu install, but CentOS shouldn't be any different here -- the differences would be in some install commands, but the permission commands will be the same.

After you run these commands, make sure you restart apache.

On Ubuntu, that would be `sudo service apache2 restart`, and as long as your CentOS install is using upstart or systemd, that should work the same.

Disclaimer: I'm not part of the project. I'm just an established user passing through. Lemmie know if that produces further output though, as I can try to assist further.

**Comment by sbenoit89** [comment]
Leave a commentphp artisan cache:clear
chmod -R 777 /var/www/html/snipeit/app/storage
Then
setenforce 0
Upon reboot 'setenforce 0' has to be entered into the console again

I just did this and it worked

**Comment by sbenoit89** [comment]
I hate how life works sometimes as soon as I ask I find it.

**Comment by k2trf** [comment]
Hehe, glad it's sorted! Although I don't claim asset tagging to be particularly fun, it's definitely better than being stuck installing the asset tagger! ;)

Make sure you close the issue and append [Solved] to the front of your issue title (I can't, as I'm not part of the project, but since you opened the issue, you should be able to). That way people know it's been settled, and if anyone else searches for this issue, they'll find the solution. :D

**Comment by sbenoit89** [comment]
Thanks man.
