### ISSUE TITLE
Snipe-IT 4.1.14 on XAMPP license page error

### ISSUE THREAD

**Issue by chaaza** [snipe/snipe-it#5102]
I have install Snipe-IT 4.1.14 on XAMPP server. The license page cannot show properly and list out folders and files only. Please help, thank you.

![image](https://user-images.githubusercontent.com/36837603/36658055-eacc3ff0-1b09-11e8-8762-2c7146b4de0b.png)

**Comment by chaaza** [comment]
And, when I try to create license, it shows:

# Object not found!
The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

If you think this is a server error, please contact the webmaster.

Error 404

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/xampp#section-remove-built-in-aliases

**Comment by chaaza** [comment]
Thanks!
