### ISSUE TITLE
Importer bugs

### ISSUE THREAD

**Issue by xarly** [snipe/snipe-it#5104]
#### Expected Behavior (or desired behavior if a feature request)

Import more assets of an existing Model with with custom fields assigned from csv

-----

#### Actual Behavior

CSV with 573 assets with these headers
Asset Tag,Category,manufacturer,Status,Model Name,CustomField1,CustomField2,CustomField3,CustomField4,CustomField5

Three problems that were not happening two weeks ago:
- Importer creates 406 assets, no error about the other 167
- Importer creates a new Asset Model, ignoring the existing one (same name, manufacturer, etc)
- Importer does not import Custom Fields, not sure if previous point related, since new asset model has no custom fields assigned

No logs in laravel.log

I think Importer is a critial feature, since it's what people see and work with firstly when migrating from our current cmbd. If this does not work smoothly, what will we face on day-to-day? This is not a critic, I'm trying to help giving a real business view.

 Thanks for your job and efforts

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Fresh**
- Version of Snipe-IT you're running  **v4.1.14 - build 3391 (master)**
- Version of PHP you're running **PHP 7.0.25**
- Version of MySQL/MariaDB you're running  **mysql  Ver 15.1 Distrib 10.2.13-MariaDB**
- What OS and web server you're running Snipe-IT on **Ubuntu 16.0.4 / nginx 1.10.3**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **install.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **Importer**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database **NO**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by xarly** [comment]
I have tried cli and I have to say that importer by command line works pretty well

**Comment by SSOHPG** [comment]
for a import we did yesterday we had to remove any custom fields linked to asset models, also we had to use both the model and model number in our csv so that the import wouldn't create new models.
if we imported custom fields and later linked the custom fields to the asset model again the info showed up correctly.

**Comment by xarly** [comment]
Using command line it imported all fields, custom included, but no check out... close enough

**Comment by SSOHPG** [comment]
we used the following fields in our csv and we got them all checked out to the right users.

Category,Manufacturer,Model Name,Asset Tag,Extensie,MAC Address,checked out to,model number,status,username,Full Name

MAC adress and Extensie are two custom fields which are not needed but using all the others made sure the items where checked out to the right users instead of assets that defaulted to a status of pending.

**Comment by skifanatech** [comment]
I had the same problem.  Imported asset Models were created as "new" models, and then custom fields were ignored.  The solution was that the model number had to exist and match even though it's not a required field.  I just used bogus model numbers 999999 for everything....then the models matched up and the custom fields were mapped.
