### ISSUE TITLE
New Installation Problem - Website Not Showing

### ISSUE THREAD

**Issue by FazzaGBR** [snipe/snipe-it#5106]
#### Expected Behavior (or desired behavior if a feature request)

I've just finished installing Snipe-IT on Ubuntu Server 16.04.3 using the guide here:

https://www.vultr.com/docs/how-to-install-snipe-it-on-ubuntu-16-10

but when i browse to the IP address of the server using a web browser Snipe-IT is not displayed.

-----

#### Actual Behavior

The Apache2 Ubuntu Default Page is displayed.

If I delete the index.html file then I just get a Not Found message instead.

-----

#### Please confirm you have done the following before posting your bug report:

I've turned the server off and back on again but I'm new to Linux and Snipe-IT so no idea what I've done wrong or missed in the configuration of this server.

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - Fresh Install
- Version of Snipe-IT you're running 4.1.14
- Version of PHP you're running 7.0.25
- Version of MySQL/MariaDB you're running 10.0.33
- What OS and web server you're running Snipe-IT on Ubuntu Server 16.04.3
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) followed the aforementioned guide
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - cant get the home page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by GeoffYoung** [comment]
When you request the server's IP address it will load the default VirtualHost (`/etc/apache2/sites-available/000-default.conf`). That VirtualHost is loading the default Apache landing page.

In step 8 of the guide you used, you created a VirtualHost for snipe-it and set the server name by adding `ServerName snipeit.example.com` to the configuration.  You should change `snipeit.example.com` to whatever domain you have pointed at that server. Then reload the Apache configuration with `service apache2 reload` and navigate to that domain name in your browser.

If you plan on accessing snipe-it using only your server's IP address then you could disable the default Apache VirtualHost by running `sudo a2dissite  000-default.conf`. Then the `snipeit.example.com.conf` file you created would become the default. I wouldn't really recommend that unless snipe-it is the only thing this server is being used for.

There's some more about VirtualHosts [here](https://httpd.apache.org/docs/2.4/vhosts/examples.html).

**Comment by FazzaGBR** [comment]
Thanks for the reply! :)

The server is only going to have Snipe-IT on it so I have run the sudo a2dissite command above and now I get a screen full of text when I open it in a web browser.  This is the first part of what I get on screen:

<?php

/**
 * Laravel - A PHP Framework For Web Artisans
 *
 * @package  Laravel
 * @author   Taylor Otwell <taylor@laravel.com>
 */

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader for
| our application. We just need to utilize it! We'll simply require it
| into the script here so that we don't have to worry about manual
| loading any of our classes later on. It feels nice to relax.
|
*/

require __DIR__.'/../bootstrap/autoload.php';

/*
|-------------------------

**Comment by snipe** [comment]
You don't have PHP installed. PHP is required to run Snipe-IT.

**Comment by FazzaGBR** [comment]
That's frustrating then as the guide I followed claimed to work!  I'm new to Linux so needed a step by step guide to follow and I simply copied and pasted each line in so I have no idea how they got their install to work.  I'm going to have to try and find another guide then I guess.

**Comment by FazzaGBR** [comment]
ALL SORTED!  Someone on SpiceWorks knows how to write simple step-by-step instructions on getting the automatic script to work - lots of things it doesnt do that you need to do manually to get it up and running.

All I've got to do now is rearrange our very large spreadsheet so I can import it in to Snipe-IT.  It may sound a bit sad, but I'm really looking forward to getting our data in to Snipe-IT as from our test over the last 4 months has proved to be very successful :)

**Comment by spencerdahua** [comment]
@FazzaGBR would you mind sharing the spiceworks thread? im pretty stuck.
