### ISSUE TITLE
Synology and Docker, what container do the Email Parameters need to be applied to?

### ISSUE THREAD

**Issue by pdumigan** [snipe/snipe-it#5107]
#### Expected Behavior (or desired behavior if a feature request)

determine what container needs the email env parameters on a Synology running Docker.

Synology/Docker applies the env variables to each container using the gui interface.  Do the email parameters need to apply to the sql container or the Snipe-it container?

-----

#### Actual Behavior

Snipe-it documentation has all of the env variables in one env file and does not reference which container they apply to.

-----

#### Please confirm you have done the following before posting your bug report:

- [N/A] I have enabled debug mode 
- [Y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? yes
- Version of Snipe-IT you're running Attempting latest 
- Version of PHP you're running  Snipe-it container
- Version of MySQL/MariaDB you're running mysql 5.6.39
- What OS and web server you're running Snipe-IT on Synology 6.1.5 w/Docker
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by uberbrady** [comment]
The email parameters are used by the Snipe-IT application container; the MySQL container ignores them.
