### ISSUE TITLE
Feature Request: Upload file to multiple assets

### ISSUE THREAD

**Issue by connor2337** [snipe/snipe-it#5109]
#### Expected Behavior (or desired behavior if a feature request)

(Also mentioned #2647) 

I would like to be able to add a single file to multiple assets, for example:

We order 12 computers, and want to add the invoice as an attached file to each computer. Search by order number, tick all the boxes, click edit, and be able to upload the file to all selected assets.

Running v4.1.11-pre - build 3307 (master) in docker on CentOS

-----

#### Actual Behavior

Add your desired files asset by asset.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
How exactly would you see this working? We could build something to associate an image to multiple files, but what happens when someone deletes that file from one asset? Does it get deleted from the server and become broken for all the others? Does it get removed from all of them? 

Seems a purchasing/invoice section would make more sense here.

**Comment by connor2337** [comment]
That's a good point. I think a purchasing section would be great. An order number, supplier, and other purchase info that's already associated with an asset can link back to an order in that section. Orders stored as objects with properties like "Total Price", "Tax", "PO Number"; sorta similar to assets?

Is a purchasing section something you've considered?

**Comment by AuXDubz** [comment]
> How exactly would you see this working? We could build something to associate a file to multiple assets, but what happens when someone deletes that file from _one_ asset? Does it get deleted from the server and become broken for all the others? Does it get removed from all of them?
> 
> Seems a purchasing/invoice section would make more sense here.

Is there a PO/Invoice section in v5? and if so what is the current ETA for v5 release?

**Comment by uFojun** [comment]
Is there a PO/Invoice section in v5? and if so what is the current ETA for v5 release?

**Comment by FelixPWG** [comment]
> How exactly would you see this working? We could build something to associate a file to multiple assets, but what happens when someone deletes that file from _one_ asset? Does it get deleted from the server and become broken for all the others? Does it get removed from all of them?
> 
> Seems a purchasing/invoice section would make more sense here.

Dear @snipe, 

Is this an upcoming feature or is more feasible that we work around the issue?

**Comment by KommunistGangsta** [comment]
an invoice section would be gold! It makes warranty managemente way easier.

Hope it will be an upcoming feature 😄
