### ISSUE TITLE
fully depreciated calculation is wrong when viewing software license history

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#511]
When looking at a license where we back dated a lot of the data the fully depreciated calculation isn't valid.

![image](https://cloud.githubusercontent.com/assets/10247644/6149884/c8c0cc6a-b1d9-11e4-8d22-05b506090ee6.png)

**Comment by snipe** [comment]
Hm... I'm getting different results. 
![screen shot 2015-02-11 at 2 00 14 pm](https://cloud.githubusercontent.com/assets/197404/6157466/6861e35a-b1f6-11e4-90d4-fd89041b70cd.png)

**Comment by snipe** [comment]
Same result for licenses. 
![screen shot 2015-02-11 at 2 05 21 pm](https://cloud.githubusercontent.com/assets/197404/6157537/0ed01040-b1f7-11e4-8161-ccd745065571.png)

**Comment by uberbrady** [comment]
I think there's some real cleanup I can do here - 

In Asset, there's:

```php
    public function depreciate()
```

And:
```php
    public function depreciation()
    {
        return $this->model->belongsTo('Depreciation','depreciation_id');
    }
```
(which actually creates the relation)

And a few others like:

```php
     public function months_until_depreciated()
```

which probably belongs in the Depreciation class.

```php
     public function depreciated_date()
```

And similar methods in License.

I think those - if they should exist at all - probably ought to live in Depreciation instead so there's less duplication.

**Comment by uberbrady** [comment]
Nope, I misunderstood - Depreciation is a 'type' of depreciation. I'll keep looking.

**Comment by uberbrady** [comment]
![screen shot 2015-02-17 at 5 22 10 pm](https://cloud.githubusercontent.com/assets/36335/6240887/ac032dee-b6c9-11e4-802b-a4ad9bc10521.png)
I think I've got it. Going to push momentarily.

**Comment by kobie-chasehansen** [comment]
looks good. Thanks @uberbrady!
