### ISSUE TITLE
I made a Dark Theme with CSS; where should it be shared?

### ISSUE THREAD

**Issue by k2trf** [snipe/snipe-it#5111]
I pasted it over at https://gist.github.com/k2trf/1a8c5ad235521fc0c97e7d54d1987bec 

Its far from perfect, and still has one or two things that bug me, but its close enough to an adjustable "theme" setting as I cared to get, as I desperately wanted a decent dark theme.

Figured others would want it, but while I don't think this is exactly the right spot, I figured I should share it somewhere for the time being. Its the simplest CSS I could manage to compile all the elements into 6 colors.

You just have to paste it all in, and adjust the colors under the top `:root` item as you want for your theme. One of them (marked with a comment) should be made the same color as your header selector, supposing you want a continuity between the items.

**Comment by snipe** [comment]
Couldn't folks just paste this into the Custom CSS box?

**Comment by k2trf** [comment]
Yes, I misspoke -- the question was where I should put this so that others can find it. Normally I'd share it on reddit, but there doesn't seem to be a subreddit for this project. There are people talking about it on /r/DataHorder and /r/SysAdmin, but that didn't seem quite appropriate.

**Comment by rjboer** [comment]
why don't you make a pull request?

**Comment by k2trf** [comment]
https://media.giphy.com/media/1M9fmo1WAFVK0/giphy.gif

This isn't code that should be added to the project; as snipe said, it just gets pasted in the Custom CSS box under Branding. The question was just where to share this, as the project doesn't seem to have a forum outside of github.

**Comment by snipe** [comment]
I wonder if adding the ability to use themes would make sense here. Default is default, but adding overriding CSS files to the repos perhaps, to make it easier for folks who don't want to muck with CSS.

**Comment by k2trf** [comment]
If I'm right, I've plucked all the strings that need to be modified. Maybe just a bit of javascript? It could take the 6 values from pickers, just like the header color (because one of my values has a comment to be the same as that so it doesn't contrast), and just paste the custom CSS in? It could be included as a separate CSS file altogether, and just have UI pickers instead. 

I'm not sure what would be easier there, nor am I sure this is what the custom CSS field was for. I suppose its intention was for businesses that wanna do something simple like shoving their logo in the background of each page, or similar. I just kinda took that and said: "*I NEED A DARK THEME*".

To be fair, I didn't actually bother until a friend basically said: "why haven't you done this?" So it's his fault.

But if you think this would help people who don't know CSS, by all means -- for now I've gone back to actually adding items (I'm not coming from anything prior, not even an excel sheet, so no import for me). I may mess with the Branding page and see how difficult it would be to do something like UI pickers with my code in another CSS file.

**Comment by snipe** [comment]
Most people, I have found, don't have a great sense for the aesthetic ;) Colors can be hard. I think offering additional theme CSS files could take care of some of the heavier lifting, while still letting users override specific elements using the custom CSS box. 

Can you create a PR adding this CSS file as `public/assets/css/themes/dark.css`? I'd do it myself, but I'd prefer you get the GH PR credit for it. I can handle the rest.

**Comment by k2trf** [comment]
I think that had an extra step I didn't need somehow... but that should be right. Never made a PR before, so thanks :)

I called it dark-green.css, as that's really what it is. Will be helpful to tell things apart if this does find usage as a theme manager.
