### ISSUE TITLE
Can't see pages in licenses section

### ISSUE THREAD

**Issue by beilinder** [snipe/snipe-it#5112]
#### Expected Behavior (or desired behavior if a feature request)
I have something like 80 licenses, over 8 pages I think. I used to be able to see the them but now I can't for some reason.
Works fine when going into Edge, or opening Chrome in cognito mode.
-----

#### Actual Behavior
Looks like this: https://i.imgur.com/0UzV1Pu.png
When actually should look like this: https://i.imgur.com/ihPsELa.png

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? fresh
- Version of Snipe-IT you're running v4.1.11-pre - build 3307 (master)
- Version of PHP you're running : 7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running: Don't know, new to this, sorry, running on Centos 6.5
- What OS and web server you're running Snipe-IT on CentOS 6.5
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Licenses
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. No
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. Yes, exactly same thing
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

Thanks in advance, sorry for newbie thread, I barely know linux and code and whatnot.

**Comment by k2trf** [comment]
In that first screenshot, you're filtering your license list with `win`. Try blanking the filter/search field, and seeing if the other items don't come back.

**Comment by beilinder** [comment]
I feel so stupid, thanks!

**Comment by k2trf** [comment]
Not a problem -- an extra set of eyes always helps!
