### ISSUE TITLE
Best Practices Advice

### ISSUE THREAD

**Issue by kabatt** [snipe/snipe-it#5114]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running: 3.6.6
- Version of PHP you're running: 7.2.2
- Version of MySQL/MariaDB you're running: 10.1
- What OS and web server you're running Snipe-IT on: Windows Server 2012
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Error when going to page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

************************************************************

Too start:

I have a really nice backup solution in place that normally saves me from problems like this.  Unfortunately, you actually have to backup the machine for it to work.  When upgrading too the latest version of SnipeIt I thought I was all set to go, of course didn't check and now that I messed it up I am kicking myself.

Where I am at:

At this point I have no idea where I am.  Would it be better trying to recover on 3.6.6 or on the latest version?  Can I recover?  I still have the database with the thousands of devices in it.  

Currently: 

I am receiving this error when going to my login page:

(1/1) FatalThrowableErrorClass 'Aws\Laravel\AwsServiceProvider' not found
--
in aws.php (line 23)
at require()in LoadConfiguration.php (line 71)
at LoadConfiguration->loadConfigurationFiles(object(Application), object(Repository))in LoadConfiguration.php (line 39)
at LoadConfiguration->bootstrap(object(Application))in Application.php (line 208)
at Application->bootstrapWith(array('Illuminate\\Foundation\\Bootstrap\\LoadEnvironmentVariables', 'Illuminate\\Foundation\\Bootstrap\\LoadConfiguration', 'Illuminate\\Foundation\\Bootstrap\\HandleExceptions', 'Illuminate\\Foundation\\Bootstrap\\RegisterFacades', 'Illuminate\\Foundation\\Bootstrap\\RegisterProviders', 'Illuminate\\Foundation\\Bootstrap\\BootProviders'))in Kernel.php (line 162)
at Kernel->bootstrap()in Kernel.php (line 146)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 59)

Any help/thoughts/comments are appreciated!

**Comment by snipe** [comment]
Hi @kabatt - don't worry - your data is fine. This issue is [addressed in the documentation](https://snipe-it.readme.io/docs/installation-issues#section-class-awslaravelawsserviceprovider-not-found).

**Comment by kabatt** [comment]
Hi @snipe, Thanks for the reply!  I have a new machine up and running with everything up to date.  I migrated the sql database to the new setup.  I did a php artisan migrate, if that is right?  Right now I am still seeing:

Call to undefined function App\Models\ldap_connect()

**Comment by kabatt** [comment]
Thanks for your help, I realized I needed to enable ldap in php manager.  Hopefully I am all set, a lot of messing around for something easily preventable by maintaining backups.

**Comment by snipe** [comment]
Awesome! Glad to hear you're all sorted. In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
