### ISSUE TITLE
FatalThrowableError Call to undefined function Patchwork\utf8_encode()

### ISSUE THREAD

**Issue by mitchya1** [snipe/snipe-it#5120]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

Clicking 'Create Database Tables' proceeds to next step
-----

#### Actual Behavior

(what actually happens goes here)

FatalThrowableError after clicking 'Create Database Tables'. However, when I log into the database using the same account as Snipe-IT, the tables have been created. I've `php artisan config:clear`
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
Fresh install 
- Version of Snipe-IT you're running
The latest. I cloned it today.
- Version of PHP you're running
7.2.2
- Version of MySQL/MariaDB you're running
MariaDB 10.2.11
- What OS and web server you're running Snipe-IT on
Apache 2.4 on Ubuntu 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

FatalThrowableError
Call to undefined function Patchwork\utf8_encode()
in Utf8.php (line 704)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
This occurs immediately after clicking 'Create Database Tables' in pre-flight
- If a stacktrace is provided in the error, include that too.

> Stack trace:
> #0 /var/www-sites/asset-int/app/Models/CustomField.php(255): Patchwork\Utf8::utf8_encode('MAC Address')
> #1 /var/www-sites/asset-int/database/migrations/2017_01_25_063357_fix_utf8_custom_field_column_names.php(64): App\Models\CustomField->convertUnicodeDbSlug()
> #2 /var/www-sites/asset-int/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(359): FixUtf8CustomFieldColumnNames->up()
> #3 /var/www-sites/asset-int/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(365): Illuminate\Database\Migrations\Migrator->Illuminate\Database\Migrations\{closure}()
> 

- Any errors that appear in your browser's error console.
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
No.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
`cat storage/logs/laravel.log | grep tf8`:

> production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined function Patchwork\utf8_encode() in /var/www-sites/asset-int/vendor/patchwork/utf8/src/Patchwork/Utf8.php:704
> #0 /var/www-sites/asset-int/app/Models/CustomField.php(255): Patchwork\Utf8::utf8_encode('MAC Address')
> #1 /var/www-sites/asset-int/database/migrations/2017_01_25_063357_fix_utf8_custom_field_column_names.php(64): App\Models\CustomField->convertUnicodeDbSlug()
> #2 /var/www-sites/asset-int/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(359): FixUtf8CustomFieldColumnNames->up()
> #4 /var/www-sites/asset-int/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php(177): Illuminate\Database\Migrations\Migrator->runMigration(Object(FixUtf8CustomFieldColumnNames), 'up')

- Include what you've done so far in the installation, and if you got any error messages along the way.
Aside from outdated Apache syntax on my end, no. 
- Indicate whether or not you've manually edited any data directly in the database
No.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/installation-issues#section-php-fatal-error-class-patchworkutf8bootup-not-found-in-bootstrapautoloadphp-on-line-43
