### ISSUE TITLE
Location missing when exported via Custom Export

### ISSUE THREAD

**Issue by sid8000** [snipe/snipe-it#5123]
#### Expected Behavior (or desired behavior if a feature request)

Location for all assets should be included when assets are exported via custom asset report.
-----

#### Actual Behavior

Location missing from most of the assets when exported via custom assets report.

But if assets exported from All Assets page then exported file does have location for all assets.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
Upgrade
- Version of Snipe-IT you're running
4.1.14
- Version of PHP you're running
7.1.9
- Version of MySQL/MariaDB you're running
MySQL 5.7.19
- What OS and web server you're running Snipe-IT on
Windows 7 with WAMP
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
MANUAL INSTALLATION
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
NA
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
NA
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
No it is not reproducible.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Please run the location sync tool. https://snipe-it.readme.io/docs/asset-location-sync

**Comment by sid8000** [comment]
Yes. Thanks. Sorry didn't read documentation thoroughly. ;)
