### ISSUE TITLE
Email Notificaton - Redirect link sets twice the domain.

### ISSUE THREAD

**Issue by cslucian** [snipe/snipe-it#5124]
I Have an issue with password reset mail template it dowbles the domain name:

As you can see bellow at the copyright is ok, In the check-out templates is ok but not in the password reset template.

![error](https://user-images.githubusercontent.com/879352/36784931-d11b1cf8-1c89-11e8-92c3-80e66fbd9c73.png)

#### Expected Behavior (or desired behavior if a feature request)
http://inventory.geminisols.ro/password/reset/6b04fd866eb531e1b28195680a8a857229114ea71a8a530173a4d36d81450227

(what you expect to happen goes here)

-----

#### Actual Behavior
http://inventory.geminisols.ro/inventory.geminisols.ro/password/reset/6b04fd866eb531e1b28195680a8a857229114ea71a8a530173a4d36d81450227
(what actually happens goes here)

-----

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Additionally, please tell us what your APP_URL is in your .env

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by cslucian** [comment]
Version of Snipe-IT you're running - **Version v4.1.14 - build 3391 (master)** 

What OS and web server you're running Snipe-IT on - **Ubuntu 16.04 , Apache2**

What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - **install.sh**

If you're getting an error in your browser, include that error - **No browser errors are shown**

What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - **mail sent for password reset**

Confirm whether the error is reproduceable on the demo. - **not sure, there no way I can reset a user password in demo and receive the password reset e-mail**

Indicate whether or not you've manually edited any data directly in the database - **No data was modified directly in the database**
Additionally, please tell us what your APP_URL is in your .env - **APP_URL=inventory.geminisols.ro**

**Comment by snipe** [comment]
The APP_URL requires the protocol as well, as [outlined in the docs](https://snipe-it.readme.io/docs/configuration#section-required-basic-app-settings). 

![screen shot 2018-03-02 at 7 37 43 pm](https://user-images.githubusercontent.com/197404/36930208-3d7e8196-1e51-11e8-911d-028f34777ea1.png)

**Comment by cslucian** [comment]
hello,

I have changed the url in my .env;

![image](https://user-images.githubusercontent.com/879352/36944862-f06724dc-1fac-11e8-93c9-66c869f0907e.png)


but the reset password link still is not correct;

![image](https://user-images.githubusercontent.com/879352/36944867-065c9876-1fad-11e8-8624-0612bc5893cd.png)


the link sent by e-mail is:

http://inventory.geminisols.ro/inventory.geminisols.ro/password/reset/7a9f8e404e45336f00a3a4aa7305dcc9cc99250715f03771dda3d7e36fbb8f4b


should be:

http://inventory.geminisols.ro/password/reset/7a9f8e404e45336f00a3a4aa7305dcc9cc99250715f03771dda3d7e36fbb8f4b

any other links from check in/check out mails are ok.
