### ISSUE TITLE
Can You Merge Two Snipe-IT Servers In To One

### ISSUE THREAD

**Issue by FazzaGBR** [snipe/snipe-it#5125]
Hi!

I've got 2 Snipe-IT servers now.  One we we're using as a 'live test' for a single departments assets to see if Snipe-IT would work for us (and it most definitely does) and I now have a fresh new install that I am slowly importing our old Asset Register (AKA Excel Spreadsheet).

OldServer: Windows Server with XAMP - v3.6.6 build 1 (gee2c67a)
NewServer: CentOS - Installed Using Install.sh - v4.1.14 - build 3408 (master)

Is it possible to export all the assets (including their history) from my OldServer to my NewServer?  If so is it easy to do?

Thanks.

#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running - 7.1.14
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
Are you actually trying to merge them, or simply swap one out for another?

**Comment by FazzaGBR** [comment]
Merge them.  I know I can export all the assets (25 of them) from the old server and import them as a csv file to the new server, but that wont bring with it the history of the assets (i.e. when and whom book them out etc).

**Comment by lostmydog** [comment]
When you import them, (as long as you have users already imported), the assets will be checked to to whomever they are currently checked out to in your old inventory system. AFAIK you can not import the date as a date, however you could just import that field as "notes" for your reference.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
