### ISSUE TITLE
Manufacturer name double in DD list when creating new asset

### ISSUE THREAD

**Issue by johan162** [snipe/snipe-it#5127]
#### Expected Behavior (or desired behavior if a feature request)
When creating a new asset the model field dropdown correctly shows the available models

-----

#### Actual Behavior
In the drop down list the name of the incorrectly adds the Manufacturer name twice in the string, se screenshot

<img width="291" alt="screen shot 2018-02-28 at 15 25 18" src="https://user-images.githubusercontent.com/1390967/36793070-a8ff0c8a-1c9c-11e8-9c66-7422d803ef50.png">

#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install

- Version of Snipe-IT you're running
Snipe-IT version | v4.1.7 build 3031 (g4f3c932)

- Version of PHP you're running
PHP Version | 7.0.22-0ubuntu0.16.04.1
Laravel Version | 5.4.29

**Comment by snipe** [comment]
This was fixed several versions ago
