### ISSUE TITLE
Pre-Flight/Setup/User - Unable to create user

### ISSUE THREAD

**Issue by mitchya1** [snipe/snipe-it#5128]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

After filling out 'Create Admin User' info, Pre-Flight should move to 'Finished!' step.
-----

#### Actual Behavior

(what actually happens goes here)

All forms clear and I'm taken back to 'Create Admin User'. `storage` and subdirectories are owned by `snipeit:www-data` with 775 permissions. SELinux is not enabled. I have cleared the config and cache with Artisan. 
-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install
- Version of Snipe-IT you're running
Latest. Cloned onto brand-new server this morning.
- Version of PHP you're running
7.0
- Version of MySQL/MariaDB you're running
10.1.31
- What OS and web server you're running Snipe-IT on
Apache 2.4 on Ubuntu 16.04.
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
/setup/user
- If a stacktrace is provided in the error, include that too.
N/A
- Any errors that appear in your browser's error console.
N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
It is not. 
- Include any additional information you can find in `storage/logs` and your webserver's logs.
No relevant errors in any logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
Issues creating database tables in Pre-Flight step 2. `php artisan migrate` errored out with permissions issue for 'forge'@'localhost' but the tables were created and I was able to move to step 3.
- Indicate whether or not you've manually edited any data directly in the database
No.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Do the protocols match in your APP_URL? http vs https? We enforce https-only cookies by default, so the only thing I can think of that might cause failure with no errors is that the session can't proceed because of protocol mismatch.

Also turn on debugging and see if there is anything in the debugbar under the Request tab.

**Comment by mitchya1** [comment]
Ah, thanks for getting me going in the right direction! The protocols matched, but the COOKIE_DOMAIN was the issue. I set it to `null` and it worked. 
What's an example of a correct COOKIE_DOMAIN, just for the sake of my sanity?

**Comment by snipe** [comment]
Well, for example, if your Snipe-IT was hosted at `assets.myawesomedomain.com`, you could set the cookie domain to be `assets.myawesomedomain.com` for ONLY that domain, or `myawesomedomain.com` (which is more permissive and handles subdomains)

**Comment by mitchya1** [comment]
Gotcha, that makes sense. Thanks again

**Comment by snipe** [comment]
No problem! Glad to hear you're all sorted. In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
