### ISSUE TITLE
FEATURE REQUEST: Endpoint Mapping Repository

### ISSUE THREAD

**Issue by jbloomer** [snipe/snipe-it#5129]
#### Expected Behavior (or desired behavior if a feature request)

It would be nice to have a section in SnipeIT to map application Endpoints. This maybe an API endpoint, Protocol (http, ftp, etc.) endpoints. 

I would think right off it would be nice to have the following columns 

Source
Destination
Envrionment
Type of EndPoint
Support Contact
Active Status

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I don't really understand what you mean.

**Comment by jbloomer** [comment]
Here is an example of the type of information I would like to be able to track

|Source|EndPoint|Destination|EndPoint|Type of EndPoint|Envrionment|Active Status|
|-------|---------|-----------|---------|-----------------|-------------|-------------|
|Application A|10.103.77.64|Application B|/api/HealthCheck|REST|Production|Active|
|Application A|10.98.22.76|Application C|77.23.17.32|Network|Pre-Production|Active|

**Comment by k2trf** [comment]
I have to concur. This is data worth tracking, but I'm not sure it's in the project's scope. Even if you had something like 10k entries to track, a spreadsheet would be apter than a database. Your relations are all straight, primary keys.

Unless you wanted a way to lookup an endpoint, and see sources coming to it, etc. But that assumes your connections aren't 1:1, which most API calls are.

**Comment by snipe** [comment]
I guess what I mean is I don't understand the context you're talking about. Are you suggesting a different section where you can add that data in, similar to assets, etc?

**Comment by jbloomer** [comment]
@snipe Yes I was wanting a new section in the UI for this data. Just Like Assets, Consumables, Accessories, etc.
