### ISSUE TITLE
Issue: Assets with default locations assigned do not reflect under the Location Settings

### ISSUE THREAD

**Issue by blackout1231** [snipe/snipe-it#5130]
#### Expected Behavior (or desired behavior if a feature request)
When I assign Assets to a Location, I go look up that location under Location Settings and see total number of assets assigned
(what you expect to happen goes here)
When I assign an asset to a specific location, I do not see the numbers of total assets assigned under the Location Settings field
-----

#### Actual Behavior
Under Location Settings I do not see total number of assets assigned to a location.
(what actually happens goes here)
I am having to go under each individual Asset and save it to get the numbers to reflect under Location settings (even though when I uploaded these assets there was a location field). I've checked tried looking up this issue, but have not seen a definitive fix.
-----

#### Please confirm you have done the following before posting your bug report:

- [N ] I have enabled debug mode 
- [ Y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Yes
- Version of Snipe-IT you're running v4.1.10 build 3249 (g8d3a214)
--
- Version of PHP you're running 7.0.23
- Version of MySQL/MariaDB you're running 5.7.19
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by blackout1231** [comment]
I've tried doing a bulk update of location, but the only was I can see to get the numbers to reflect was going into individual assets and saving it ( I don't even have to make changes).

=(

**Comment by snipe** [comment]
I believe this is already fixed in later versions.
