### ISSUE TITLE
I was not able to log in.

### ISSUE THREAD

**Issue by t-haru0325** [snipe/snipe-it#5133]
While doing data input work on the premise that Snipe-it was used in the company,
I can not log in again after logging out once.
I checked the support case, but I could not find a similar case.
I have been in trouble very much.
Thank you for your support.

#### Assumed behavior (or desired behavior in the case of function request)

Regardless of the registered users, "User name or password is invalid" is displayed at login.

-----

#### Actual behavior

The related operation that I thought is that I created a group.

-----

#### Before submitting your bug report, please confirm the following:

 - [] Debug mode enabled
 - I confirmed the page of [*] common problem (https://snipe-it.readme.io/docs/common-issues)

-----
#### Please answer these questions:

 - Is this a new installation, upgrade?
It is a new installation.
 - Version of running snipe-IT
V 4.1.14
 - The version of PHP you are running
 - MySQL / MariaDB version you are running
 - OS and Web server running Snipe-IT
CentOS Linux release 7.4.1708 (Core)
 - The method used to install Snipe-IT (install.sh, manual installation, docker etc)
Install.sh
 - If debugging is turned on and errors occurred in the browser, please include that error
I can not log in.
 - What are the specific pages of Snipe-IT and what elements are used to cause errors?
 - Include the stack trace if it is included in the error.
 - Error displayed in browser error console.
 - Please check if the error can be reproduced in the demo: https: //snipeitapp.com/demo.
 - Include `storage / logs` and additional information in the web server's log.
 - Include when error message appears on the way including work done in previous work.
 - Indicates whether all data in the database was manually edited

Please do not post the problem without answering the related questions above. If you open another issue and have already answered these questions, please reply to the ticket again. It will be impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I would suggest you use the forgotten password request. There's nothing we can specifically do to help you. If you have access to the server itself, you can try creating another admin and logging in as them. https://snipe-it.readme.io/docs/create-an-admin

**Comment by t-haru0325** [comment]
Thank you.
I successfully logged in with the newly created user.
That was a really big help!
