### ISSUE TITLE
Asset "Status" change option at "Check out"

### ISSUE THREAD

**Issue by Raj22223** [snipe/snipe-it#5134]
#### Expected Behavior (or desired behavior if a feature request)

When I am trying to check out an asset to user , it would be really help full  if " status" change option can display at "check out" page.

Note: I checked other issue, where i found one user requested for 'Status' change option at 'Check in' page not check out page.

![1](https://user-images.githubusercontent.com/34770213/36843908-7d6133c0-1d76-11e8-80f7-cf31556bff6d.png)

-----

#### Actual Behavior

At "check out" page as of now there is no option to change asset "Status" option.

-----

#### Please confirm you have done the following before posting your bug report:

- [] I have enabled debug mode 
- [] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Yes
- Version of Snipe-IT you're running
Version v4.1.14 - build 3408 (master)
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by techweasel** [comment]
Yes - this would be a big help. I'm almost sure this was a feature in prior versions, as I don't remember having to look up items after checkouts in order to change between status settings.

**Comment by snipe** [comment]
> . I believe this was how checkout function behaved in earlier versions, prior to "deployed" being a tag independent of status.

Deployed has always worked the same way, as it's a special meta status. This is how it's intended, so that people don't have to have specific "Deployed" status labels. Once it's deployed, it's deployed. Period.

**Comment by techweasel** [comment]
Apologies Snipe, I did a terrible job of phrasing that. 

Aware that's the case for "deployed" and why it functions as it does - but prior to v4 wasn't there an option to bulk set custom status during checkout (could be completely wrong, we only transitioned to Snipe late in v3 so I'm cloudy on exact details)? We use custom status flags to categorize some items that needs to be adjusted during checkout and checkin - and would be nice to not have to check in asset, then access to set status flag as two separate actions.

**Comment by Raj22223** [comment]
Agreed @techweasel , as you mentioned.
"We use custom status flags to categorize some items that needs to be adjusted during checkout and checkin - and would be nice to not have to check in asset, then access to set status flag as two separate actions"

We do have custom status, and need to perform 2 actions to update the status. 

@snipe if we can provide the status update option at check out, it really helps.

Please do consider. Thanks

**Comment by Raj22223** [comment]
@snipe for better understanding i am attaching the history of asset where we did 2 actions for updating the status 1. Asset checked out 2. Asset updated to change the status.

![image](https://user-images.githubusercontent.com/34770213/37283725-f75263ba-261e-11e8-821d-14680176339c.png)

Note:  Image is edited to remove the original data

**Comment by bricelabelle** [comment]
I would also LOVE to see this feature added. We upgrade full-time employee computers every 5 years, labs every 6, and Adjunct faculty every 7. We do this based on status labels. (Employee, Adj, Lab...) so right now we have to remember to change the status prior to checking something out. If that gets missed, an employee may not get an upgrade when they are due. In addition, having something marked as "Deployed" is confusing if it still shows up when searching the status label "storage", so whether it happens at checkout or not I imagine many users are changing status labels manually in a  separate step like us. This feature would be huge addition for us. Thanks!

**Comment by ars3nic** [comment]
Necro bump to voice my support as well.  We use custom statuses to categorize how an asset is being used (test, loan, demo, etc), so being able to go from Ready To Deploy to 'checked out as a Loaner' in one action would be ideal.
