### ISSUE TITLE
Sort status options when adding/editing asset?

### ISSUE THREAD

**Issue by grantemsley** [snipe/snipe-it#5138]
#### Expected Behavior (or desired behavior if a feature request)

Statuses should be in alphabetical order, or have a way to change the order after entering them.

Other dropdowns like supplier and default location area already alphabetically sorted.

-----

#### Actual Behavior

Statuses are ordered by ID, which makes it hard to find the one you want.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? fresh
- Version of Snipe-IT you're running v4.1.14 build 3408
- Version of PHP you're running 7.0.25
- Version of MySQL/MariaDB you're running mysql 5.7.21
- What OS and web server you're running Snipe-IT on Ubuntu Apache2.4
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) git
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error asset edit page
- If a stacktrace is provided in the error, include that too. N/A
- Any errors that appear in your browser's error console. N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. Yes
- Include any additional information you can find in `storage/logs` and your webserver's logs. N/A
- Include what you've done so far in the installation, and if you got any error messages along the way. N/A
- Indicate whether or not you've manually edited any data directly in the database Nope

**Comment by snipe** [comment]
TBH, we do that because the way we seed the status labels puts Ready to Deploy first, which is generally a more often used status label. If we were to alphabetize, that would put Archived first, and that's an uncommon status label to use. 

I suppose we could allow folks to sort the labels, but it seems like a lot of extra UI to build for something like this.

**Comment by grantemsley** [comment]
Makes sense.  Unfortunately I didn't know that when I was creating custom ones, so mine are in a very much less than ideal order.  It's not a show stopper, but the easier it is to use, the more likely my team is to use it consistently. I guess I will see if I can edit the DB manually without breaking anything or patch it myself to add some sorting options.

**Comment by snipe** [comment]
Okay, I've got something up on develop for you. While it's not exactly a status label sorting UI, it should now alphabetize, after it's checked to see if the `default_label` field is 0 or 1. (If it's 1, it will run through those first, alphabetizing the ones marked as defaults, and then move on to the non-defaults. Let me know if this works for your purposes.

![screen shot 2018-03-05 at 10 04 21 pm](https://user-images.githubusercontent.com/197404/37016470-3bdf8976-20c1-11e8-8218-d9bb2cccfb06.png)

**Comment by grantemsley** [comment]
That will work perfectly.  Thank you!
