### ISSUE TITLE
Modification

### ISSUE THREAD

**Issue by YCYee912** [snipe/snipe-it#514]
May i know how to change the currency from "$" to our local currency? Thanks

**Comment by snipe** [comment]
Simply use the library for your local language/location. There is a currency value in `app/lang/<your-localization>/general.php`:

'currency'  			=> '$',

What is your local currency/location?

**Comment by YCYee912** [comment]
RM = Ringgit Malaysia

So i just change into 'currency' => 'RM',

Thats all?

**Comment by snipe** [comment]
You shouldn't actually even have to do that, since our Malay language file is largely translated already.

Find `'locale' => 'en',` in your `app/config/app.php`

and change it to:

`'locale' => 'ms',`

That will tell the app you want to use the Malay language files, and RM is already set as the current there.

**Comment by snipe** [comment]
(If you change it in the english language files, it will just be overwritten the next time we update language strings for the app)

**Comment by YCYee912** [comment]
I see..most of us understand english so i just change it..thats fine =)

is that possible to add in other website address or contact at every page footer?

**Comment by snipe** [comment]
It's not currently possible, but we can consider adding it.

**Comment by imie** [comment]
Hi, please add the RM symbol under default currency also. 

most of use use english but we like to use RM symbol in english.

thanks btw.

**Comment by snipe** [comment]
@imie a literal RM, or a symbol?

**Comment by imie** [comment]
literal RM

our RM sysmbol also is RM we dont have specific symbol like $

thank you so much.

**Comment by iskandarzh** [comment]
Dear Snipe,

Could you add Indonesia Currency to next update?

Thanks in Advance.

**Comment by snipe** [comment]
@iskandarzh upcoming v3 will allow you to input your own symbols.
