### ISSUE TITLE
Question more than Issue

### ISSUE THREAD

**Issue by jmartins1** [snipe/snipe-it#5145]
I'm on the latest version of the inventory system. I have used MySQL and even MySQL Workbench to backup the database to a "playground; if you will" version installation where staff can learn how to use the application. The issue is NOT carrying of the entries or schema but rather the attachments. None of the attachments carry over. They display as if they exist but are not accessible. Are attachments not uploaded to the database but stored elsewhere and linked to to the DB? Do I need to more over a folder to the other installation to make them available? Thank you.

**Comment by snipe** [comment]
Uploads are not stored in the database, they are stored in the filesystem, in `public/uploads` and `storage/private_uploads`. (If you use the Backup tool in the Admin Settings, they will back those up as well.)
