### ISSUE TITLE
502 Bad Gateway (New installation)

### ISSUE THREAD

**Issue by tx7** [snipe/snipe-it#5148]
Hello,

I'm just update my server to Debian 9.
Running Nginx; php7.

I had setup everything, but couldn't launch the setup page.
Couldn't reach to the step : Pre-Flight & Setup

Nginx config:

` # Auto-Redirect HTTP to non-standard port HTTPS.
    error_page  497 https://$host:5443$request_uri;

    # Disable Nginx version viewing to the public
    server_tokens off;

    # Only allow these request methods
     if ($request_method !~ ^(GET|HEAD|POST)$ ) {
         return 444;
     }

    ssl_protocols SSLv3 TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-RC4-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:RC4-SHA:!aNULL:!eNULL:!EXPORT:!DES:!3DES:!MD5:!DSS:!PKS;
    ssl_session_timeout 5m;
    ssl_session_cache builtin:1000 shared:SSL:10m;

   
    root /opt/snipe-it/public/;
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ ^/install/(.+\.php)$ {
 		allow 127.0.0.1;
 		allow ::1;
 		deny all;
    }

    location ~ \.php$ {
        try_files $uri $uri/ =404;
        fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        
    }`

**Comment by tx7** [comment]
I found the issue: `Access denied for user 'snipeit'@'localhost' (using password: YES) (SQL: select * from information_schema.tables where table_schema = snipeit and table_name = users)`

**Comment by tx7** [comment]
I've granted access to snipeit user, but still have the same issue.

**Comment by snipe** [comment]
Awesome! Glad to hear you're all sorted. In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
