### ISSUE TITLE
Building SnipeIT Server, need some advise. 

### ISSUE THREAD

**Issue by mrmcox** [snipe/snipe-it#5149]
Hi All,

First time posting here, I saw the issues template which I think is great but doesn't fit with what I need.

I dont have a server built yet, I am just planning and wanted to ask some questions before I begin.

1. How much HDD space will SnipeIT need for a 1000+ assets setup
2. I want to use a Linux VM to host the server, can I still use a barcode reader? maybe a wireless one?

thanks and sorry if I have broken a posting rule.

**Comment by haneesibm** [comment]
Hi, 
with my experience, I would say 20 to 30 GB of HDD will be more than enough to RUN the Linux VM for snipeIT. for the safer side, keep around minimum 50 to 80 GB.
of course, you can use the barcode reader.
