### ISSUE TITLE
Ok so I am a N00b here.  Composer error:  can't find Json 

### ISSUE THREAD

**Issue by gramstead** [snipe/snipe-it#5152]
#### Expected Behavior (or desired behavior if a feature request)
I have been trying to get composer to install per the instructions on the site, I goto initpub/wwwroot/snipe-it in the command window.  When I try to run Composer Install, I get "could not find composer.json".  I cannot find the file anywhere.  I am obviously missing something.  Please assist.

-----

#### Actual Behavior
Error Message:  Composer could not find a composer.json file in H:\
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  Yes
- Version of Snipe-IT you're running  still working on build out
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on  Windows SErver 2012
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)  install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Are you sure you're in the project root? The [composer.json](https://github.com/snipe/snipe-it/blob/master/composer.json) is at the top level of the project directory.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
