### ISSUE TITLE
Unable to sign into Snipe-IT with LDAP users

### ISSUE THREAD

**Issue by nnolan** [snipe/snipe-it#5153]
When attempting to sign into the Snipe-It console using an LDAP user, we are getting the following error:
There was an error authenticating the LDAP user: Could not find user in LDAP directory

We have been able to successfully sync JumpCloud with Snipe-It, as we were able to import or directory. 

My configuration is below:

<img width="820" alt="screen shot 2018-03-05 at 3 59 23 pm" src="https://user-images.githubusercontent.com/36713193/37002138-4ff00f40-208e-11e8-96c0-63207bcbc9ef.png">

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Additionally, please tell us what the result is in using the login test option in the LDAP settings screen.

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by seattlespicybite** [comment]
Similar issue (AD environment), but not a big deal at this moment. I am able to sync users and import them from AD, but users not able to login in with AD credentials. When I Test LDAP Login-> Login Failed. testuser did not successfully bind to LDAP . (Verified the username and password). I capture the LDAP packets with with Wireshark and server returns [success] response. Test LDAP Sync successfull.
    Version of Snipe-IT you're running : v4.1.14  build 3382 (g0f23462)
    What OS and web server you're running Snipe-IT on: XAMP , Windows 7 x64 Ent
    What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual
    If you're getting an error in your browser, include that error: no error
    What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: /admin/ldap -> Test LDAP Login
    If a stacktrace is provided in the error, include that too. : nope
    Any errors that appear in your browser's error console. : no
    Confirm whether the error is reproduceable on the demo. : yes
    Include any additional information you can find in app/storage/logs and your webserver's logs. 
    Include what you've done so far in the installation, and if you got any error messages along the way. : see above
    Indicate whether or not you've manually edited any data directly in the database: no

**Comment by snipe** [comment]
@seattlespicybite LDAP login definitely works - we have customers using it every day. When we see this, it's usually an issue of the LDAP Auth Query being slightly off.

**Comment by seattlespicybite** [comment]
Thank you. After many retries, this configuration seems to be operational
![snipe-it](https://user-images.githubusercontent.com/35437032/37170444-aee2131c-22bf-11e8-8a08-62bfd26c0446.png)
