### ISSUE TITLE
For a category choose fields to display 

### ISSUE THREAD

**Issue by vikaskedia** [snipe/snipe-it#5157]
Great piece of software.

Maybe this obvious feature is already there and i am not looking for it at the right place.

As I move from one category to another I have to choose a different set of columns.

![image](https://user-images.githubusercontent.com/6703876/37023852-08c9f66e-20dc-11e8-8a8e-15938538102e.png)

For a category can i set the columns that should be visible when i go to:
/categories/ID

<img width="1436" alt="fields-to-display" src="https://user-images.githubusercontent.com/6703876/37023787-d65404d6-20db-11e8-978e-d4eb71a2f4a2.png">

**If this feature is not there .. i would be happy to code it.**

**Comment by snipe** [comment]
Column visibility is handled via the bootstrap table cookie

**Comment by vikaskedia** [comment]
> Column visibility is handled via the bootstrap table cookie

But this has a BIG disadvantage that column visibility across all categories is the same.

# Why is it a big disadvantage?

We have a column called IP address. I want to see this column when looking at the category of Desktops but I do not want to see this column when looking at the category of Monitors.

@snipe would you be interested in merging a PR where for each category I will allow setting a list of Default columns and during display of the category use those columns ?

**Comment by snipe** [comment]
@vikaskedia I literally just UN-did that with the latest release, as people were complaining that they had to keep selecting the same columns across multiple categories

**Comment by vikaskedia** [comment]
@snipe I am using this software in a 100 person company and I can confirm that when looking at the category of Servers vs the category of Motherboards vs the category of Monitors the columns that we want the report are very different.

> I literally just UN-did 

Can you PLEASE put it behind a option? Instead of undoing it?

>  As people were complaining that they had to keep selecting the same columns across multiple categories

I do not understand this. If the category admin screen just allows a user to choose which columns they want to use as default columns. Why will they need to select the same columns across multiple categories? If the default columns are not selected below a category in the admin screen then the behavior can remain.

![image](https://user-images.githubusercontent.com/6703876/37068351-1832a74a-2163-11e8-9bcc-1c9e82131d50.png)

I would be happy to get on a zoom/skype call to show my implementation.

**Comment by snipe** [comment]
I'm not really interested in keeping column selections in the database. That's a lot of overhead and additional testing that would need to be supported over time. I might consider adding the option to persist column selections across columns or not in the Settings, but I don't think I want the overhead of starting to store column selections in the database. That's more UI, more things that need to keep being updated as we expand out section, etc.

**Comment by vikaskedia** [comment]
> I'm not really interested in keeping column selections in the database. That's a lot of overhead and additional testing that would need to be supported over time

Understood

> I might consider adding the option to persist column selections across columns or not in the Settings, 

@snipe Did you mean "adding the option to persist column selections across categories" ?

>I don't think I want the overhead of starting to store column selections in the database. That's more UI, more things that need to keep being updated as we expand out sections, etc.

Can I write it as a plugin. I do not want to loose compatibility with the mother code base ..

I really want our organization to use snipe-it for asset management. But the man above usually browses categories to make sure all the data is correct. And when he is browsing categories he does not like it that the reports do not make sense to him. Since monitors  show up with the column IP address. And Chairs show up with the column resolution.

I can also write the code such that the DB load will not increase for those who do not use this feature ..
