### ISSUE TITLE
LDAP Login not considered

### ISSUE THREAD

**Issue by stolz1982** [snipe/snipe-it#5158]
#### Expected Behavior (or desired behavior if a feature request)
The correct LDAP configuratin should allow an existing user to login by verifying the password to the configured LDAP server. If the LDAP password is not correct the system should check the password against the local database password.

-----

#### Actual Behavior

The system replies an "Error: The username or password is incorrect.", after entering the username and LDAP password. By entering the local DB password of the user, system will login the user.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
Upgrade and also tested on a fresh installation
- Version of Snipe-IT you're running?
v4.1.14 build 3391 (g0f23462)  
- Version of PHP you're running
7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running
mysql  Ver 15.1 Distrib 10.1.28-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- What OS and web server you're running Snipe-IT on
Linux IT01 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
apache2 2.4.18-2ubuntu3.5
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
GIT
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Just from the system --> "Error: The username or password is incorrect."

<img width="242" alt="image" src="https://user-images.githubusercontent.com/12507015/37025892-284363bc-212d-11e8-87dd-ed399a8d3a18.png">

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
https://it01.xxxxxxxxx.eu/login
- If a stacktrace is provided in the error, include that too.
N/A
- Any errors that appear in your browser's error console.
N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
N/A (LDAP settings cannot being testes)
- Include any additional information you can find in `storage/logs` and your webserver's logs.

[2018-03-06 10:43:45] production.ERROR: There was an error authenticating the LDAP user: Could not create user: {"first_name":["The first name field is required."],"username":["The username must be unique."]}  

- Include what you've done so far in the installation, and if you got any error messages along the way.
Double checked the LDAP settings:

<img width="754" alt="image" src="https://user-images.githubusercontent.com/12507015/37025970-5c3f52ac-212d-11e8-9e96-244e252cd009.png">

Tested the LDAP settings:
<img width="694" alt="image" src="https://user-images.githubusercontent.com/12507015/37025992-6caac694-212d-11e8-8e87-4c256adbfb81.png">

- Indicate whether or not you've manually edited any data directly in the database
NO

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
That's not actually the current behavior. It will first check the LDAP login using the LDAP password, and will fail down to local user. If you're unable to authenticate with the LDAP user/password, there is usually an issue with your LDAP Auth Query or Filter.

**Comment by stolz1982** [comment]
Hi Snipe,
many thanks for your quick reply. For me is not clear why the user can authenticate against the LDAP in the LDAP settings but not at the Login. As you can see the user test.sk has been authenticate successfully in the LDAP settings pate but the same user brings the error at the login page!?

**Comment by Ethanb00** [comment]
I had this too. 

my LDAP filter needed to be:

&(cn=*)

**Comment by stolz1982** [comment]
@Ethanb00: many thanks for your advice which I've tested immediately but unfortunately without success. Using  samaccountName for LDAP Authentication query will bring an error by the "Test LDAP Login" function at the LDAP settings page and brings an error at the login page.

**Comment by stolz1982** [comment]
@snipe is there any way of extending the log during the login process in order to evaluate the error I have described above besides activation of debug level? In addition, where can I find the source code to check the login process, especially the place where the output of the log will be produced?

Are any other steps I can try in order to solve my problem?

I am really looking forward to hear from you.
