### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by EdZaza** [snipe/snipe-it#5165]
Hi @snipe 
I'm very new to Github and Linux, I have created a GitHub account solemnly because of Snipe-IT. To, first of all, thank you so much for this amazing initiative and to bring forth some minor "amateur" concerns.
I successfully managed to install snipe-IT on Ubuntu 16.04.3 server (with MySQL server) running on Oracle VM VirtualBox. All installation run successfully and I was able to access Snipe-IT with a browser and created a user and made some changes to it. After an hour or so of inactivity, I wasn't able to access it anymore. It popped up an Error 500. I read this (https://github.com/snipe/snipe-it/issues/192) article but honestly, I got lost in the following process. Could you please help me find a way through this? I'm studying this application to be able to deploy it to companies that I consult for.

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)
