### ISSUE TITLE
Error when viewing assets assigned to me

### ISSUE THREAD

**Issue by mikesoule** [snipe/snipe-it#517]
Upgraded to latest release last night. Now when I click Welcome, [NAME] -> View assigned assets, the left menu disappears and is replaced by a link named "Requestable". Clicking that link causes an exception with the following details.

```
Open: /var/www/html/snipe/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php
		if (starts_with($method, 'where'))
		{
			return $this->dynamicWhere($method, $parameters);
		}
 
		$className = get_class($this);
 
		throw new \BadMethodCallException("Call to undefined method {$className}::{$method}()");
	}
 ```

**Comment by snipe** [comment]
That sounds like your account is a user account, not an admin account. Are you logged in as an admin?
