### ISSUE TITLE
Issue with Authentication : Could not create local user

### ISSUE THREAD

**Issue by osnala** [snipe/snipe-it#5174]
#### Expected Behavior (or desired behavior if a feature request)

AD/LDAP users authenticated and be able to login

-----

#### Actual Behavior
When I import users, ldap sync works, users are imported without issue and I am able to login with an imported user

With no users imported yet
When logging in with AD user, i get error _production.ERROR:  There was an error authenticating the LDAP user: Could not create local user_

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh Install
- Version of Snipe-IT you're running v4.1.14
- Version of PHP you're running 7.0.10
- Version of MySQL/MariaDB you're running MySQL 5.7.21
- What OS and web server you're running Snipe-IT on Redhat 7.4 Apache 2.4
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) git clone
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: 
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. 
production.ERROR:  There was an error authenticating the LDAP user: Could not create local user
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by omatsei** [comment]
I'm having the same problem. All the LDAP tests on the LDAP config page work successfully. If I enter something wrong, it says it fails, as expected. But I can't log in with new users. I have tried importing via CSV, and manually creating a new user with the same username, but still nothing.

Is this a fresh install or an upgrade? - Upgrade from 3.6
Version of Snipe-IT you're running: - v4.1.11
Version of PHP you're running - 7.1.15
Version of MySQL/MariaDB you're running - MariaDB 5.5.56
What OS and web server you're running Snipe-IT on - CentOS 7.4.1708, Apache 2.4.6-67
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - don't remember
WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error:
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Login page
If a stacktrace is provided in the error, include that too.
Any errors that appear in your browser's error console - 
production.ERROR: There was an error authenticating the LDAP user: Could not create local user
Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo - N/A (no AD there)
Include any additional information you can find in storage/logs and your webserver's logs. - none
Include what you've done so far in the installation, and if you got any error messages along the way.
Indicate whether or not you've manually edited any data directly in the database - No

**Comment by steven3721** [comment]
see my issue report #5420 , I think it's a bug.

**Comment by snipe** [comment]
@steven3721 I don't believe this is a bug - we have users that use AD/LDAP login all the time, and it's working for them.

**Comment by snipe** [comment]
(Additionally, if you're running 4.1.14, I would suggest upgrading.)
