### ISSUE TITLE
API: Asset_Tag - how to get an auto incremented Tag (like in webinterface on create)

### ISSUE THREAD

**Issue by m4rphel** [snipe/snipe-it#5175]
#### Expected Behavior (or desired behavior if a feature request)

Using the API to create an Asset should incorporate the automatic Asset_Tag functionality
Or, an api call to get the next Asset_Tag, which would be used.

-----

#### Actual Behavior

One has to set an Asset_Tag - with the hassle to get all hardware/etc., get highest ID, self increment, and use the value

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by m4rphel** [comment]
I found #4013 which holds me back from using Docker for Production use...
Also, i tried my code on the demosystem, which runs fine. (Learned, that if the Asset_Tag is not send, it will be created automatically...the docu don´t reveals this information - just tried it and it works)

So, the App is fine, but die Docker Setup needs some love. Can be closed...as this belongs just to Docker - I think!?

nevertheless here the answers:

- Version of Snipe-IT you're running
4.1.13 - current docker image (no 4.1.14 build available)
- What OS and web server you're running Snipe-IT on
as defined in Dockerfile - Ubuntu 16.04.3 and Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
docker
- If you're getting an error in your browser, include that error
no error in Browser, can´t create asset via api as it states that a field Asset_Tag is needed - messages: { asset_tag: [ 'asset tag Feld muss ausgefüllt sein.' ] } (sry, for German error message) - cant reproduce as I get now Error 500 and the API Keys are gone :/
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
No Page, API
- If a stacktrace is provided in the error, include that too.
no
- Any errors that appear in your browser's error console.
no
- Confirm whether the error is reproduceable on the demo.
No, not reproduceable
- Include any additional information you can find in app/storage/logs and your webserver's logs.
no logs available in the docker container - just laravel.log which shows no errors
- Include what you've done so far in the installation, and if you got any error messages along the way.
no errors, just used the docker image
- Indicate whether or not you've manually edited any data directly in the database
no edits

**Comment by m4rphel** [comment]
Looking at the Dockerfile: Why do you use the single Folder Links and not the whole Storage Folder?
So everything, including Logs, would be persistent.

**Comment by m4rphel** [comment]
Solution (for me):
Change Dockerfile -> just use one persistant Storage folder
Copy Data in Running container to new folder
Build Docker Image
Run
Done ;)
Had a mysql error regarding 'serial' can´t be NULL. Migrations were done with nothing to do. So I changed the field in DB to accept NULL.

Now I can create Assets directly from our Order Workflow in Ticketsystem: Thanks for this API introduced in v4 - good work :)
