### ISSUE TITLE
Create Hardware Error: Trying to get Property of Non-Object

### ISSUE THREAD

**Issue by ss-dsheets** [snipe/snipe-it#518]
Howdy!

When clicking "Create New" on the assets page (as I currently have none) I get the following error:

![screen shot 2015-02-12 at 11 14 23 am](https://cloud.githubusercontent.com/assets/10777192/6171346/5a74b1ac-b2a8-11e4-9ff2-c4ab03cd271c.png)

**Comment by snipe** [comment]
Hi there - when you grab the latest off of develop, do you still get this error?

**Comment by ss-dsheets** [comment]
Eeeh... git noob here, hold on.

I initially did 
git clone https://github.com/snipe/snipe-it.git

to get the version I'm using. How do I convert to the develop branch?

Did a "git pull" this morning at about 9:30 AM EST and it updated a few files, when I do that now it says I'm already up to date.


This could also be an artifact from a change I made earlier...
   I was having an issue deleting the default content from Licenses and Assets due to it saying that the Licenses were checked out to a user, but checking them in/and out to a different user still didn't allow me to remove the default licenses that were attached (Git Tower and Adobe WTFBBQ)

So I went in and removed the default assets directly in mysql, the tables are still there for asset and license and whatnot, but it won't let me add anything to them from the website.

**Comment by snipe** [comment]
Hmm... Well, first thing, you probably shouldn't delete stuff right from the database, as it can cause weird data which can cause unpredictable results. 

If you go to Settings and uncheck the auto-increment asset tags option, do you still get the error?

Can you re-seed the database? Run `php artisan db:seed`, which will re-add those deleted entries. Then you can just check them in and delete them normally. 

I honestly don't think I've ever seen that particular error before.

**Comment by ss-dsheets** [comment]
Un-checking Auto-increment did it for me! Thanks a bunch!

**Comment by snipe** [comment]
Hrm, the auto-increment should work tho. I'll take a look and see if I can reproduce on my end.

**Comment by ss-dsheets** [comment]
I think I kinda crafted the issue by deleting all rows from the assets table, then when it tried to auto increment, it couldn't increment from nothing.

I could be wrong. This web server was the first full blown bare install to production that I've ever configured over the course of the last like, three days. So don't take my thoughts too seriously :-P

**Comment by ss-dsheets** [comment]
Hmm. Re-seeding the database did dump the defaults back in though. Lets see if I can remove the default licenses and whatnot this time.

**Comment by snipe** [comment]
Well, yes, that's what seeding a database does :)

**Comment by ss-dsheets** [comment]
Ooh, when trying to click on the asset tag for the second default item in the list:
NNY2878796 - MacBook Pro (13-inch, Mid 2012) - WS90585666669

I get this error:
![screen shot 2015-02-12 at 2 31 55 pm](https://cloud.githubusercontent.com/assets/10777192/6175364/14b020fe-b2c4-11e4-8175-01125b651f14.png)

**Comment by snipe** [comment]
This is from what view? List All?

**Comment by snipe** [comment]
(Also, did you manually delete any users from the DB? Re-seeding doesn't replace those)

**Comment by ss-dsheets** [comment]
Same happens for:
NNY67567775 - MacBook Pro (Retina, 13-inch, Late 2012) - WS89080890
and a few others.

This is from the login screen, when "All Assets" are showing, same issue shows up when clicking on that model, then trying to click on the asset tags from there.

Yeah... I went in and removed all the default users, assets, models, licenses, from each table

**Comment by ss-dsheets** [comment]
Do I need to go trash the database entirely and re-run php artisan app:install ?

**Comment by snipe** [comment]
It probably wouldn't hurt. Manually mucking with data in the DB can always do weird things. The auto-increment issue is a real bug, and I'll fix that, but everything else should work out of the box.

**Comment by ss-dsheets** [comment]
So in the default load out, there are 7 licenses, two of which are available. After clicking "Checkin" on all licenses that had that option, the toolbar at the top still says there are 7 total and only two available. When attempting to delete either the Git Tower or Photoshop CS6 license seats it will say that it can't because they're currently checked out to a user.

And this is why I went and deleted the assets manually beforehand.

Is there a log or some further info that would be helpful?

**Comment by snipe** [comment]
Did you check in the license seats?

**Comment by ss-dsheets** [comment]
Yup. Says "Check Out" for all of them

![screen shot 2015-02-12 at 3 02 10 pm](https://cloud.githubusercontent.com/assets/10777192/6175857/37cb8c82-b2c8-11e4-9c1c-fc499c1f284f.png)

**Comment by snipe** [comment]
Aha - I can reproduce. I'm getting the same result here. 

![screen shot 2015-02-12 at 12 02 35 pm](https://cloud.githubusercontent.com/assets/197404/6175867/21e6eace-b2af-11e4-9adc-518bd462b95f.png)
![screen shot 2015-02-12 at 12 02 40 pm](https://cloud.githubusercontent.com/assets/197404/6175868/21ec08a6-b2af-11e4-96dc-6c144fd6eab4.png)

Give me a few to look at the DB to see what's happening

**Comment by snipe** [comment]
Can you do a git pull on develop and see if what I just pushed through fixes your issue?

**Comment by ss-dsheets** [comment]
So to, I guess, "re-calibrate" where it knew where the licenses were, I checked all 7 of them out to John Doe, checked them back in, and was able to delete them successfully.

As I did that, with each license the Licenses Available tag updated appropriately.

Any log files or info you need me to dump to look at?

**Comment by snipe** [comment]
So, it sounds like it's working now?

**Comment by ss-dsheets** [comment]
Yup! Thanks for the speedy help with it. Now I'm off to convert a spreadsheet into SnipeIT! :D

**Comment by snipe** [comment]
Ah, excellent. Sorry about the bug, but I'm glad we got it sorted quickly! Thanks for the troubleshooting help!
