### ISSUE TITLE
Time to Upgrade to PHP7

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#5183]
Hi all,

This is just an advanced heads up that we'll be requiring PHP7 in the next major release of Snipe-IT. While that won't be for another few months, I wanted to give everyone adequate time to get their systems upgraded, as Snipe-IT version 5 will require at least PHP7.1.3.

PHP7 has been out for quite some time (Dec 2015), so I'm hoping this won't cause too many issues for our users. We've kept the requirement down to 5.6.4 for as long as we could, but newer versions of the libraries we use are requiring PHP7, security requirements demand that we update, and we can't stand still forever. 

Please consider this your official warning :)

![buttons](https://user-images.githubusercontent.com/197404/37258408-e7f6531c-2534-11e8-904d-597c2f46007d.gif)

**Comment by tiagom62** [comment]
snipeit.sh already installs php7. Wooo!

**Comment by snipe** [comment]
@tiagom62 do you know what version of PHP7 it installs by default? Laravel 5.6 (latest) requires PHP >= 7.1.3

**Comment by tiagom62** [comment]
From memory they are all at least 7.1.x.

I will try to confirm with specific versions by end of week.

**Comment by snipe** [comment]
@tiagom62 Thank you!

![mask-thank-you](https://user-images.githubusercontent.com/197404/38642227-4d2ca9e0-3d8e-11e8-8a71-faa21fc18fba.gif)

**Comment by snipe** [comment]
Thanks!

**Comment by benrubson** [comment]
Unfortunately, as time of writing, **Debian stable** (9 / Stretch), uses PHP 7.0 :
https://packages.debian.org/stretch/php/php

Perhaps it would be nice to keep compatible with PHP 7.0, so that Debian stable, mainly used in hosting environments, will still be supported ?

Many thanks 👍

**Comment by lb1f** [comment]
Great! Just looking to setup Snipe-IT now and was looking at which version of PHP it supports. Saw in the documentation it referenced PHP 5.6.4 but did a little more digging (google) and found this issues post. Thanks, I'll ensure the server is setup using the latest PHP for future support.
