### ISSUE TITLE
Import Not Working Either Via GUI or Command Line

### ISSUE THREAD

**Issue by FazzaGBR** [snipe/snipe-it#5189]
#### Expected Behavior (or desired behavior if a feature request)

When you import a CSV file it should then be in Snipe-IT.

-----

#### Actual Behavior

When I enter php artisan snipeit:import ./csvdump/100.csv --verbose

It says: All Items imported successfully!

Yet when I go in to Snipe-IT there are no assets listed!

-----

#### Please confirm you have done the following before posting your bug report:

- [N ] I have enabled debug mode 
- [ Y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

Is this a fresh install or an upgrade? - Fresh Install
Version of Snipe-IT you're running 4.1.14 build 3408
Version of PHP you're running 7.1.14
Version of MySQL/MariaDB you're running 10.0.33
What OS and web server you're running Snipe-IT on Centos 7
What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - install.sh
WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Assets page showing no assets
If a stacktrace is provided in the error, include that too.
Any errors that appear in your browser's error console.
Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Include any additional information you can find in storage/logs and your webserver's logs.
Include what you've done so far in the installation, and if you got any error messages along the way.
Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by blackrandom** [comment]
could you show your csv file?
