### ISSUE TITLE
Import process keeping saying "Processing" 

### ISSUE THREAD

**Issue by Humsawani** [snipe/snipe-it#5190]
#### Expected Behavior (or desired behavior if a feature request)

Bulk asset import through CSV file

-----

#### Actual Behavior

keep on saying "processing". Not getting imported.
-----

#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode 
- [yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? fresh one
- Version of Snipe-IT you're running v4.1.14 build 3408 
- Version of PHP you're running 7.0.27-1
- Version of MySQL/MariaDB you're running Mysql 5.7.19
- What OS and web server you're running Snipe-IT on ubuntu-16.04.1
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error no
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error import page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by Humsawani** [comment]
@snipe Please help me to resolve this issue

**Comment by blackrandom** [comment]
what does your csv file look like?

**Comment by Humsawani** [comment]
I just try to import the same asset CSV file(sample_assets.csv) which is given in the documentation of snipe it page.

**Comment by Humsawani** [comment]
link of the documentation import page: https://snipe-it.readme.io/docs/importing

**Comment by blackrandom** [comment]
Did you set up your .env file? If so, can you post is here? Just make generalize any sensitive information.

**Comment by Humsawani** [comment]
please find the .env fie: [env.txt](https://github.com/snipe/snipe-it/files/1810292/env.txt)

**Comment by Humsawani** [comment]
I enabled a debug mode and I tried to create a new asset, it is throwing an exception as attached
![error](https://user-images.githubusercontent.com/37297710/37395197-b2ea39e0-279b-11e8-889d-75bf7e60c298.PNG)

**Comment by Humsawani** [comment]
@snipe Please help me to resolve

**Comment by afzalyusufi** [comment]
i am facing same issue, please help me.

i have done fresh installation on ubuntu 18 server php 7.2 and snipeit v4.7.4  Laravel Version 5.5.45.
