### ISSUE TITLE
It look's like css/js missing. But I don't know how to fix it 

### ISSUE THREAD

**Issue by guulyfox** [snipe/snipe-it#5193]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
   2.21

- Version of PHP you're running
   7.01
- Version of MySQL/MariaDB you're running
   5.7
- What OS and web server you're running Snipe-IT on
   CentOS 7  lnmp
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
   manual install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
    no I don't see any error in my debug mode
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
   before I setup my page , then I get this error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help
![attachment](https://user-images.githubusercontent.com/30172602/37320559-3e1374ac-26af-11e8-89c0-7cfa7b0fab30.jpg)

So how do i fix it?

**Comment by snipe** [comment]
What is the URL you access the app? And what do you have in your APP_URL in your .env?
