### ISSUE TITLE
LICENSE CREATED BUT NOT SHOWING

### ISSUE THREAD

**Issue by chaaza** [snipe/snipe-it#5194]
#### Expected Behavior (or desired behavior if a feature request)

List of licenses showed in the license view page.

-----

#### Actual Behavior

It shows nothing.
![capture1](https://user-images.githubusercontent.com/36837603/37331327-9e4f240e-26de-11e8-8266-12acecc70df7.PNG)
![capture2](https://user-images.githubusercontent.com/36837603/37331328-9e8552ea-26de-11e8-9156-ade893efbde1.PNG)

**Comment by hofnarrr** [comment]
I've experienced this issue too. Try refreshing the table using the button next to the search box, it should fetch the licenses.

**Comment by chaaza** [comment]
Great, I got it thanks!
