### ISSUE TITLE
The results could not be loaded

### ISSUE THREAD

**Issue by Stanivdc** [snipe/snipe-it#5196]
#### Expected Behavior (or desired behavior if a feature request)

When I chekout a component I need to have the list of all assets in the section select asset.

-----

#### Actual Behavior

When I want to assign a component to an asset I get the following message "The results could not be loaded".

-----

#### Please confirm you have done the following before posting your bug report:

- [*] I have enabled debug mode 
- [*] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
Fresh install
- Version of Snipe-IT you're running
v4.1.5 build 187 (gc0293a7)
- Version of PHP you're running
PHP 7.0
- Version of MySQL/MariaDB you're running
MariaDB 10.2
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
LOG.error: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getFullNameAttribute() on null in /var/www/assets.int.actility.com/app/Http/Controllers/Api/AssetsController.php:306
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![2018-03-13_11h50_48](https://user-images.githubusercontent.com/37299011/37337509-cac64488-26b4-11e8-8cd4-16f5f1c7230e.png)

**Comment by snipe** [comment]
I can't reproduce this at all. Please try upgrading to the latest version.
