### ISSUE TITLE
Feature Request: RMA Tracking

### ISSUE THREAD

**Issue by tylerhammer** [snipe/snipe-it#5197]
#### Expected Behavior (or desired behavior if a feature request)

RMA Tracking. It would be nice if there was a way to track items that are out for RMA. Things that would be useful for tracking would be : 

- Date RMA'd
- Date Returned
- New Serial Number

This is something that could be added to the asset, accessory, component level as another tab that can track the 

-----

#### Actual Behavior

As far as I can tell, to some extent this exists on the asset level, where you can maintain repairs and what not, but not replacements of actual items. 

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Yes
- Version of Snipe-IT you're running
v4.1.14 build 3446 (g90bff709a)
- Version of PHP you're running
7.0.25-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running
MariaDB 10.2
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04 Server
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual Installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
N/A
- If a stacktrace is provided in the error, include that too.
N/A
- Any errors that appear in your browser's error console.
N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
N/A
- Include any additional information you can find in `storage/logs` and your webserver's logs.
N/A
- Include what you've done so far in the installation, and if you got any error messages along the way.
N/A
- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by BHollowell** [comment]
You could do this via custom status and custom field options today, but I agree that it would be a useful option to have by default

**Comment by michaeloconnor1717** [comment]
I want to +1 this request. 
I need support for this specific use case, but it would also be helpful if the custom fields allowed easier linking of assets to other assets, such as allowing the "New Serial Number" to be a drop-down menu from which you can select from already entered assets.
