### ISSUE TITLE
Importing from CSV doesn't automatically check out/deploy assets

### ISSUE THREAD

**Issue by AMTJRWW** [snipe/snipe-it#5199]
#### Expected Behavior (or desired behavior if a feature request)

I expect my CSV file to import the data and automatically mark the objects as deployed to the stated user from the Username field.

-----

#### Actual Behavior

I have my CSV file with the Username field filled in (chose first.last in my setup and that is the format my username is in) and the Status field left blank. The assets import without any error messages but the assets are not automatically deployed to the given username. The asset is marked as "Pending". Been doing this is a test with the only user the Super Admin created and trying to assign assets to that account.

Screenshots of behavior:
https://imgur.com/a/d8e30

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
Fresh
- Version of Snipe-IT you're running
4.1.14 build 3446 (master)
- Version of PHP you're running
7.2.3
- Version of MySQL/MariaDB you're running
mysql Ver 15.1 Distrib 5.5.56-MariaDB
- What OS and web server you're running Snipe-IT on
CentOS 7-4.1708.e17, Apache 2.4.6-67
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Git Install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No errors
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
The import page and then list all assets page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
None
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Can't import in the demo
- Include any additional information you can find in `storage/logs` and your webserver's logs.
laravel.log is over 1000 lines long. Not sure what would be relevant.
- Include what you've done so far in the installation, and if you got any error messages along the way.
Installed as per user guide, got errors relating to SELinux, solved by shutting of SE.
- Indicate whether or not you've manually edited any data directly in the database
I have not

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by blackrandom** [comment]
For the import field 'Name' select 'Full Name' from the options. I think the checkout is done via the 'Full Name' field not the 'Username' field.

**Comment by AMTJRWW** [comment]
Using the Full Name field did assign the asset and give the meta status of "Deployed" but the main status is still "Pending." This will require me to bulk edit the entries to a different status, which isn't a huge problem but it is an extra step. Maybe checked out could be a flag that is toggled on import so I can set status and deploy on import?

Thanks for the help.

**Comment by amarjeets-pb** [comment]
IMPORT from CSV doesn't work. 
File import completed but it shows PROCESSING...... records are not updating & not getting an error.
