### ISSUE TITLE
Location mandatory fields do not work in all geographies

### ISSUE THREAD

**Issue by trapdoor123** [snipe/snipe-it#520]
I am starting to use Snipe-IT in the UK. However, everytime I set up a location, I am faced with two issues to work around:

1. I am forced to set up a State (which we don't have) . 
2. UK postal codes (like Canadian post codes) have a space in the middle of them, which is not in the allowed character list.

For reference, a typical address format for London is: 
123 Acacia Avenue, 
London
SW1 1AA

**Comment by trapdoor123** [comment]
Should just add that I'm running v1.2.4. I see other closed issues that are similar to this, but it's not working in this version. Apologies if it's just not made it to the prod version yet.

**Comment by snipe** [comment]
You should be able to pull the latest off of develop to resolve this. It will be pushed out in the next release.
