### ISSUE TITLE
how to changes the existing MAIL_FROM_ADDR and MAIL_REPLYTO_ADDR. email ID??

### ISSUE THREAD

**Issue by ziyaul121** [snipe/snipe-it#5202]
#### Expected Behavior (or desired behavior if a feature request)

Dear Snipe,

I want to change the the MAIL_FROM_ADDR  E-mail ID but whenever I am replacing with new email ID   in .env than still mail goes to old mail. Please help me. How I can change the  MAIL_FROM_ADDR and MAIL_REPLYTO_ADDR.

-----

#### Actual Behavior

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode  yed
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) yes

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh install
- Version of Snipe-IT you're running  Version v4.1.14
- Version of PHP you're running 7
- Version of MySQL/MariaDB you're running mariadb-5.5.56-2.el7.x86_64
- What OS and web server you're running Snipe-IT on Centos7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error --
- If a stacktrace is provided in the error, include that too. --
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Please see the documentation about clearing your config cache. https://snipe-it.readme.io/docs/common-issues

**Comment by ziyaul121** [comment]
Thanks a lot.
