### ISSUE TITLE
Issue on Windows / IIS (Blank page  - Hanging)

### ISSUE THREAD

**Issue by florentchawki** [snipe/snipe-it#521]
Hi All,

i am having an issue after a fresh install on IIS 7.0 on windows server 2012R2
I am using PHP 5.4.2.
Installed composer install / MariaDB 10.0
Updated the dns / server name / app.php and database.php /

Change the key to : ad980asd09as8d09as8d0as0d8asdada****** typed it manually 

But when i am go on the site which is : http://assets.uvpn.uk
The page does not show anything and the connection is still active ( Waiting for assets.uvpn.uk...) without displaying any error

The error log from : app / storage / logs 

[2015-02-13 16:54:02] production.ERROR: exception 'Illuminate\Filesystem\FileNotFoundException' with message 'File does not exist at path C:\Users\Administrator\Downloads\Sites\snipe-it-1.2.4\app/config/production/app.php' in C:\Users\Administrator\Downloads\Sites\snipe-it-1.2.4\vendor\laravel\framework\src\Illuminate\Filesystem\Filesystem.php:31
Stack trace:
#0 C:\Users\Administrator\Downloads\Sites\snipe-it-1.2.4\vendor\laravel\framework\src\Illuminate\Foundation\Console\KeyGenerateCommand.php(65): Illuminate\Filesystem\Filesystem->get('C:\Users\Admini...')
#1 C:\Users\Administrator\Downloads\Sites\snipe-it-1.2.4\vendor\laravel\framework\src\Illuminate\Foundation\Console\KeyGenerateCommand.php(43): Illuminate\Foundation\Console\KeyGenerateCommand->getKeyFile()
#2 C:\Users\Administrator\Downloads\Sites\snipe-it-1.2.4\vendor\laravel\framework\src\Illuminate\Console\Command.php(112): Illuminate\Foundation\Console\KeyGenerateCommand->fire()
#3 C:\Users\Administrator\Downloads\Sites\snipe-it-1.2.4\vendor\symfony\console\Symfony\Component\Console\Command\Command.php(253): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\Users\Administrator\Downloads\Sites\snipe-it-1.2.4\vendor\laravel\framework\src\Illuminate\Console\Command.php(100): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\Users\Administrator\Downloads\Sites\snipe-it-1.2.4\vendor\symfony\console\Symfony\Component\Console\Application.php(889): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 C:\Users\Administrator\Downloads\Sites\snipe-it-1.2.4\vendor\symfony\console\Symfony\Component\Console\Application.php(193): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Foundation\Console\KeyGenerateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 C:\Users\Administrator\Downloads\Sites\snipe-it-1.2.4\vendor\symfony\console\Symfony\Component\Console\Application.php(124): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 C:\Users\Administrator\Downloads\Sites\snipe-it-1.2.4\artisan(59): Symfony\Component\Console\Application->run()
#9 {main} [] []

Can anyone please suggest something?
Thank you

Florent

**Comment by snipe** [comment]
Can you confirm that `C:\Users\Administrator\Downloads\Sites\snipe-it-1.2.4\app\config\production\app.php` actually exists?

**Comment by snipe** [comment]
Looks like you got this sorted.
