### ISSUE TITLE
 Where to add custom text in asset delivery mail.

### ISSUE THREAD

**Issue by ziyaul121** [snipe/snipe-it#5210]
#### Expected Behavior (or desired behavior if a feature request)
Dear Snipe,

I want to add custom text "This is to inform you that following item has been assigned to you" in asset delivery mail and this requirements of my team. Please help me where I can change it. Please Help me and thanks in advance.
-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode yes
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running  Version v4.1.14 
- Version of PHP you're running 7
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on Centos 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by ziyaul121** [comment]
Please help .....

**Comment by 5quirrel** [comment]
You do this under **General Settings > Default EULA** or in Category Properties under **Category EULA**

**Comment by Raj22223** [comment]
Any way to change the Subject ?

**Comment by ziyaul121** [comment]
Thanks @5quirrel , But I wanted to edit this line "A new item has been checked out under your name, details are below." please tell me where I can edit it.

**Comment by ziyaul121** [comment]
Dear @snipe 

Please help me.

**Comment by 5quirrel** [comment]
@ziyaul121 @Raj22223 you could edit that string in the appropriate language files manually, but you'd have to make that change after every update.

_resources/lang/en/mail.php
resources/lang/en-GB/mail.php_

**Comment by ziyaul121** [comment]
Thanks A lot @5quirrel ,

Great, Appreciate your help.

**Comment by GaoGaoCE** [comment]
> @ziyaul121 @Raj22223 you could edit that string in the appropriate language files manually, but you'd have to make that change after every update.
> 
> _resources/lang/en/mail.php resources/lang/en-GB/mail.php_

Hello, can we add more username on subject ??? i mean : "Asset delivery confirmation + username
"
