### ISSUE TITLE
Table resize issue

### ISSUE THREAD

**Issue by snazy2000** [snipe/snipe-it#5211]
#### Expected Behavior (or desired behavior if a feature request)

The table should dynamically change not only on a page refresh, I believe this happens anywhere that bootstrap tables is used.

It never used to do this a few versions back.
-----

#### Actual Behavior

1.	First Page load without Search result
 
![image](https://user-images.githubusercontent.com/1378836/37452546-d2707612-282c-11e8-8f74-f7152d1b8c12.png)

2.	Search for assets
 
![image](https://user-images.githubusercontent.com/1378836/37452550-d475b3c8-282c-11e8-8e1d-5e7f51787304.png)

The height of the container hasn’t changed at this point

3.	Refresh the page
 
![image](https://user-images.githubusercontent.com/1378836/37452555-d75be986-282c-11e8-813c-122f1183f40c.png)

Now it looks as expected on the form (without the big white space at the bottom)
4.	Remove the search result
![image](https://user-images.githubusercontent.com/1378836/37452560-da60d308-282c-11e8-9b42-8e9b8c6ec23c.png)

 
Does not rescale to the full page ☹ Note the scroll bars. This is even worse when you search for a specific asset and you have 1 row then you do the same again and you can only see 1 asset with a  scroll bar!

-----

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running  v4.1.14
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.  - **YES**

**Comment by snazy2000** [comment]
Looks like setting the fixed-table-body height to auto fixes the issue

https://github.com/wenzhixin/bootstrap-table/issues/641

What do you think @snipe

**Comment by snipe** [comment]
Can you pull from the latest on master/develop and tell me if this fixes the issue for you?

**Comment by snazy2000** [comment]
@snipe Yes thats all working now, noticed this was done while ago thanks for putting this in its much better!
