### ISSUE TITLE
Adding a sub folder with a sub menu

### ISSUE THREAD

**Issue by UpulSS** [snipe/snipe-it#5212]
Hi,

Is it possible to add a menu in to “Create New” drop down menu list

Create New
>>Asset		  - http://snipeit/hardware/create
>>License         - http://snipeit/licenses/create
>>Accessory     - http://snipeit/accessories/create
>>Consumable - http://snipeit/consumables/create
>>Component  - http://snipeit/components/create
>>**AMC**		  - **http://snipeit/amc/create**

Since I need to track my Annual Maintenance Contracts also. Appreciate anyone could to advice on this.

**Comment by tydonk** [comment]
I would also like to be able to add links to the Create New dropdown menu
