### ISSUE TITLE
Missing/Hidden Assets

### ISSUE THREAD

**Issue by tine128** [snipe/snipe-it#5214]
#### Expected Behavior (or desired behavior if a feature request)

See assets after import.

-----

#### Actual Behavior

I was able to import new assets. When I go to my dashboard, it has the correct number of items. The issue is that when I go into "More info" within the assets there is nothing there. 
https://i.imgur.com/RuJGX9s.png
https://i.imgur.com/oHilDrA.png

Is there a way for me to clear out the items? I was able to import a smaller sample as a test. Everything was imported and I was able to see the items. The differences between the two imports are the values I entered during the second import.   

-----

#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode 

- [yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
yes
- Version of Snipe-IT you're running
Version v4.1.10 - build 3249 (master
- Version of PHP you're running
7.2
- Version of MySQL/MariaDB you're running

- What OS and web server you're running Snipe-IT on
godaddy 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
LOG.error: ErrorException: Trying to get property of non-object in /home/hcaadmin/public_...
error
log
LOG.error: ErrorException: Trying to get property of non-object in /home/hcaadmin/public_...
error
log
Please let me know if you need the logs.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
No, importing is disabled.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by chaaza** [comment]
Have you try refreshing the table using the button next to the search box? I've experienced this issue with the licenses page.

**Comment by tine128** [comment]
Yes and I am still unable to see anything.

**Comment by blackout1231** [comment]
This might be a different issue, but I had that problem early on as well. It was because (in my case) the Model Number and Model Name were not the same as what I setup under the Asset Model Settings.

There were other issues with my CSV (and the data on it) that I don't recall what they were, but it was because of some issues with the data on my CSV.

**Comment by snipe** [comment]
If you click on the Deleted Assets or Archived Assets option in the sidenav, do you see your assets?

**Comment by tine128** [comment]
No.
