### ISSUE TITLE
Hardware - Maintenances - no Action Buttons

### ISSUE THREAD

**Issue by m4rphel** [snipe/snipe-it#5215]
#### Expected Behavior (or desired behavior if a feature request)

On the Tab "Maintenance" of an Hardware Object a Column called "Actions" is available.
In this Column should be Action Button for Edit and Remove available.

-----

#### Actual Behavior

No Buttons. Just a Text "maintenanceActions"

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh
- Version of Snipe-IT you're running
4.1.14
- Version of PHP you're running
7.
- Version of MySQL/MariaDB you're running
xx
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
no debug
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
https://demo.snipeitapp.com/hardware/1024#maintenances
- If a stacktrace is provided in the error, include that too.
no
- Any errors that appear in your browser's error console.
no
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
it is: https://demo.snipeitapp.com/hardware/1024#maintenances
- Include any additional information you can find in `storage/logs` and your webserver's logs.
none
- Include what you've done so far in the installation, and if you got any error messages along the way.
nothing
- Indicate whether or not you've manually edited any data directly in the database
no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
This has already been fixed on master and will be in the next release.
