### ISSUE TITLE
Small bug when zoomed in

### ISSUE THREAD

**Issue by bbrennan825** [snipe/snipe-it#522]
I found a small bug while I was playing around with SnipeIT today. This happens when you're zoomed in > 175% and the site looks to convert to a format that is more mobile friendly. When you click on the menu icon, the bar at the bottom where it says "Snipe IT is a free open source project by @snipeyhead.Fork it | Documentation | Help Translate It! | Report a Bug (v1.2.4)" moves to just under the title bar and overlaps itself. Not really a high priority, but thought I should let you know it's happening.

**Comment by buzzedword** [comment]
Most every website will break if you zoom in more than 100%. Unless it's rocking some serious WAI-ARIA / ADA compliance, that's going to break. That's a metric ton of work to make things accessible at high magnification, I'd seriously recommend hitting the donate button. Not a lot of people are taking that one on.
