### ISSUE TITLE
reset generated labels

### ISSUE THREAD

**Issue by mandelbrotmedia** [snipe/snipe-it#5221]
#### Expected Behavior (or desired behavior if a feature request)

i have new labels which are smaller then the old ones.
if i print some label they should all fit on the new "smaller" labels

-----

#### Actual Behavior
if i print out a label from a new asset it fits perfect.
if i print out a label which i printed some time ago, the size does not change and it prints too large labels.
it looks like, that the old labels a pregenereated.

is there a way to reset the pregenerated barcodes?

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
fresh
- Version of Snipe-IT you're running
v4.1.11
- Version of PHP you're running
7.1.13
- Version of MySQL/MariaDB you're running
10.1.30-MariaDB
- What OS and web server you're running Snipe-IT on
Windows Server 201;6 xampp, apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
git
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
Nope
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Just delete the labels from the `public/uploads/barcodes` directory

**Comment by mandelbrotmedia** [comment]
worked perfect! Thx alot!!
