### ISSUE TITLE
LDAP user Sync not working. 

### ISSUE THREAD

**Issue by ziyaul121** [snipe/snipe-it#5222]
Dear @snipe ,

LDAP Connection and user authentication is successfully done but I am not able to see the list of users in current users under people. Whenever I try to sync with LDAP User Sync than below error coming "
This page isn’t working
 is currently unable to handle this request.
HTTP ERROR 500

I also tried to sync with LDAP Command Line Sync in centos 7 but below error is coming. Please look into this. 

t]# php artisan snipeit:ldap-sync --summary
PHP Fatal error:  Allowed memory size of 524288000 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/snipeit/app/Models/Ldap.php on line 269
PHP Fatal error:  Allowed memory size of 524288000 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 122

![image](https://user-images.githubusercontent.com/37359588/37597515-20a0aa40-2b99-11e8-86db-e106efb2a4f6.png)

-----

#### Actual Behavior

All AD users should be listed in application in current user.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode yes
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) yes

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running Version v4.1.14 
- Version of PHP you're running 7
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on Centos 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by ziyaul121** [comment]
I have set memory limit to 1024 MB in /etc/php.ini but still no luck. Please help me

**Comment by snipe** [comment]
You'll need to increase your memory limit even more, or narrow down your OU/Base DN more. If your BaseDN has thousands and thousands of people in it, the system will run out of memory trying to process them.

**Comment by ziyaul121** [comment]
Dear @snipe 

Thanks a lot. Now all AD users sync post set ldap filter "&(objectcategory=person)(objectclass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2))" and listed in application but currently in users details only their first name , last name, username, full name and email is coming whereas I want phone number and department also. Please help me how I can get phone number and department in user details.

**Comment by snipe** [comment]
That is not currently possible.
