### ISSUE TITLE
Feature Request: Multiple Locations for User

### ISSUE THREAD

**Issue by lostmydog** [snipe/snipe-it#5223]
#### Expected Behavior (or desired behavior if a feature request)
In my company, we have two offices and a few dozen employees have workstations setup in both offices. It would be really nice if we had the ability to assign more than one location to a user. This would mean a bit of UI changes of course, because then when choosing to checkout an asset to a user that has more than one location, you would then be prompted "Location A or Location B" etc. 

-----

#### Actual Behavior
Right now because this functionality is not available, I instead create duplicate users with the name of the second location in parenthesis. This means I select John Doe (Denver) when selecting the other branch. The main issue with doing things this way of course is when/if John Doe leaves, because we then have to remember to delete both employees, which can get confusing because some people have dual-setups and others do not.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I'd be willing to look at a PR for this feature, but given the amount of additional complexity it introduces for what I think is probably an edge case, I don't think this will be on our short term roadmap.

**Comment by misilot** [comment]
Just wanted to add a use case.

We are trying to use a single instance with the Multi Company support, but want to share the users between the two companies.

Company A is IT (tracking hardware, etc...) where Company B is building services tracking furniture and other items. Both "companies" check out items to locations and users as required. However, when "Full Multiple Companies Support" is enabled the users are only available for checkout if the asset manager, and the user are in the same company. 

When we have "Full Multiple Companies Support" disabled it works, however now both sides see the commingled assets.

Thanks!

**Comment by sylvank** [comment]
Would like to add support for this. Due to COVID, most users started working from home. Now, most users are returning to the office part-time. 

So each user/person has assets:
- At home (monitors, webcams, printers)
- At the office (desktop computers, monitors, desk phones, scanners etc.)
- On their person (laptop)

It would be nice to be able to quickly identify which items are onsite or offsite, without creating multiple copies of users as @lostmydog suggested.
