### ISSUE TITLE
Feature Request: Search Accessories by Manufacturer Field

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#5225]
Currently the only way to search for an accessory is by the Name field, this is obviously annoying to say the least as who remembers what every name of every accessory might be. 

Shown below is what I'm describing. By editing either asset name to include "Logitech" can I then find these accessories by their "manufacturer" otherwise I have to search by the name. 

https://i.imgur.com/lseYwUx.png
https://i.imgur.com/vyrBNDu.png
https://i.imgur.com/9jgnGS4.png

Let me know if you need anything else.

**Comment by snipe** [comment]
This is on master now
