### ISSUE TITLE
Feature Request: License Alert Threshold

### ISSUE THREAD

**Issue by B3RN0UT** [snipe/snipe-it#5226]
#### Expected Behavior (or desired behavior if a feature request)

License notification should also send a notifications mail when the amount of licenses is below a critical value.
For example you have 50 whatever licenses and you need a reminder to order more when you already taken 45 or stuff like that.
The same/needed function is already implemented on accessories.
-----

#### Actual Behavior

Currently notifications for Licenses will be sent when a license is about to expire.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Version of Snipe-IT you're running: 4.1.14

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snowwhite686** [comment]
Our license module doesn't notify about expiry or nearing to expiry how will i test this feature?
Also there should be some highlight in the grid that this is about to expiry or already expired? some RED indicator?
