### ISSUE TITLE
Assets assigned to another asset is not visible from asset view

### ISSUE THREAD

**Issue by colinerd** [snipe/snipe-it#5227]
#### Expected Behavior (or desired behavior if a feature request)

When I assign Asset A against Asset B, this works fine. When looking up the Asset in the "List All" view, I can see it assigned to Asset B.

Now when I open Asset B, I would expect to see Asset A visible on the "Assets" tab.

-----

#### Actual Behavior

I can see in the "List all" asset overview all assets and I can see Asset A assigned to Asset B.

When opening Asset B, the "Assets" tab remains empty while Asset A is assigned to it (as it shows on the list all assets view). The text shows "No matching records found"

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh Install
- Version of Snipe-IT you're running: 4.1.14
- Version of PHP you're running: 7.1.7
- Version of MySQL/MariaDB you're running: 10.1
- What OS and web server you're running Snipe-IT on: Windows Server 2016 & IIS 10
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual Install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: There is no error, the list view shows no matching records.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: http://*domainname*/hardware/375#assets
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.: Not reproducible on the demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. There have not been any error messages nor was there an issue during assignment of the asset to another asset.
- Indicate whether or not you've manually edited any data directly in the database: Not manually edited database.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Is there anything in your error logs?

**Comment by colinerd** [comment]
No there are no errors in the log. I did check the SELECT query and ran it directly on the database but got no results there either....

> select `assets`.* from `assets` inner join `status_labels` as `status_alias` on `status_alias`.`id` = `assets`.`status_id` and `status_alias`.`archived` = '0' where `assets`.`assigned_to` = '205' and `assets`.`assigned_type` = 'App\Models\Asset' and `assets`.`deleted_at` is null order by `assets`.`created_at` asc limit 50 offset 0

If I remove this part from the query, I do get the expected result directly from the database;

> and `assets`.`assigned_type` = 'App\Models\Asset'

The item has "App\Models\Asset" as assigned_type in the database so not sure why I get no results when using the original query.....

I tried running a small select query to just select all assets from the assets table where assigned_type = 'App\Models\Asset' but got no results on that query either so something is wrong as there are records in there with that assigned_type.

**Comment by colinerd** [comment]
Hi Snipe, Did the above information help to trace down the issue?
Is there anything else I can provide to assist?
