### ISSUE TITLE
Import Issue - The model id field is required. 

### ISSUE THREAD

**Issue by Steven4x4** [snipe/snipe-it#5228]
#### Expected Behavior (or desired behavior if a feature request)

Importing assets using an export as a template, should import accordingly.

-----

#### Actual Behavior

When importing assets: I'm getting an error saying "The model id field is required."
After reviewing the database, I can see there is a specific id associated to the model of the asset.
The problem is, there is no way to map a field to the model id to fix the issue.
I've tried "Model Name" and "Model Number" using both the text based name and the id itself.
But, I have not been able to successfully import assets.

-----

#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh Install 
- Version of Snipe-IT you're running v4.1.14 - build 3382 (master
- Version of PHP you're running 5.6.34
- Version of MySQL/MariaDB you're running MySQL
- What OS and web server you're running Snipe-IT on Ubuntu 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Webuzo
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error Import button on Import page.
- If a stacktrace is provided in the error, include that too.

Item | Errors
-- | --
iPhone 6S | Asset Model "iPhone 6S": The manufacturer id field is required.
iPhone - 01 | Asset "iPhone - 01": The model id field is required.
iPhone - 02 | Asset "iPhone - 02": The model id field is required.
iPhone - 03 | Asset "iPhone - 03": The model id field is required.
iPhone - 04 | Asset "iPhone - 04": The model id field is required.
..... etc

**Comment by danr12** [comment]
I get this alot when my CSV was missing a Model Number information. Make sure all your assets have a Model Number and Model Name filled out and it should import OK. That's what I found personally.

**Comment by Steven4x4** [comment]
danr12, I had tried that a few days ago and it worked. Thank you.
