### ISSUE TITLE
Export/Import Issue

### ISSUE THREAD

**Issue by Steven4x4** [snipe/snipe-it#5229]
#### Expected Behavior (or desired behavior if a feature request)

When you export data from Snipe. I'm expecting it to have the lay out of the required fields with the associated field names so that I can edit it in Excel, Save it as a CSV and reimport it so that all of the field are already mapped.

-----

#### Actual Behavior

Exported field Asset, doesn't link to Item Name.
Exported field Model, doesn't link to Model Number nor Model Name.
Also related to another issue https://github.com/snipe/snipe-it/issues/5228

-----

#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh Install 
- Version of Snipe-IT you're running v4.1.14 - build 3382 (master
- Version of PHP you're running 5.6.34
- Version of MySQL/MariaDB you're running MySQL
- What OS and web server you're running Snipe-IT on Ubuntu 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Webuzo
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error Export Button on Asset Page

**Comment by snipe** [comment]
> Exported field Asset, doesn't link to Item Name. 

I don't understand what this means

**Comment by Steven4x4** [comment]
So, my goal was to import a bunch of iPhones with their associated date.
I created one iPhone as an asset.
I searched for that asset and exported the data.

This gave me a csv file that I was hoping to use as a template to import it back into the system.
It exported the following fields: 
"Asset Name","Asset Tag",Serial,Model,Category,Status,"Checked Out To",Location,"Purchase Cost","Phone Number",IMEI/MEID

I figured, I could use that export as a template to import the other 15 iPhones I had.
I populated the template with the remaining data and head to the import tool.
I selected the file, it uploaded, I clicked process, It brought up the fields for importing, but the following fields were not recognized automatically:
Asset Name, Serial, Model

![image](https://user-images.githubusercontent.com/20448250/37681469-01ead872-2c44-11e8-8d6f-1ff46d2d17b8.png)

So, its nothing major, I can manually select the associated import fields, but I was expecting since I kept the same headers that were exported from the system, that they'd be recognized by the system when I went to import them again.

**Comment by snipe** [comment]
That's not something that's super easily fixed (and we provide a field mapper specifically to deal with that), especially if we need it to be multi-language aware.

**Comment by mhanshaw** [comment]
Steven, can you shed some light on your import process?

I did the same as you, created some assets manually, then exported the list and tried to build my import format based on what Snipe-IT's exported CSV.

However, I'm not finding a good format as everything I have tried comes up with "The Model ID Field is required" or "The Manufacturer ID Field is required", etc.

Can you share your CSV format so that I can try it out?

**Comment by Steven4x4** [comment]
mhanshaw,

What I discovered is you have to have two fields to resolve the "Model ID" import issue:
Model Name
and
Model Number

I believe they can be the same value, but you need to have both of those fields in the CSV file.
