### ISSUE TITLE
Loading more results drop down doesn't load more results

### ISSUE THREAD

**Issue by marera123** [snipe/snipe-it#5232]
#### Expected Behavior (or desired behavior if a feature request)

For creating assets the drop down wont load additional entries. Same on my own host and in Snipe-It demo server as well. So i guess this has something to do with browser setup. Same for IE, Chrome, Edge.
Has anyone encountered this or can suggest how to deal with it?

I skipped all the guidelines as the same behaviour is on local host and DEMO server as well.

![2018-03-21 10_59_19-create asset model __ socar tallinn](https://user-images.githubusercontent.com/37616402/37702046-f7128f06-2cf9-11e8-8e42-53a06b45f21a.png)

**Comment by snipe** [comment]
What was the issue here?

**Comment by marera123** [comment]
The problem was that the categories I've set were for accessory wasnt showing in creating a new asset.
And at first i didnt understand why, but now i do

**Comment by ngocdoan** [comment]
How did you resolve it?
I'm having the same issues?

**Comment by JetDanTe** [comment]
Up! I have found the same bug? How can fix it?
