### ISSUE TITLE
Checkout Component/Asset to Asset

### ISSUE THREAD

**Issue by ktoczyski** [snipe/snipe-it#5235]
Hello,

I have question about checkout asset to asset. I created two assets and one I checked out to another asset.

This porcedure works fine.

![asset1](https://user-images.githubusercontent.com/29401151/37714065-dce4b2de-2d18-11e8-9cc1-e02f0789211c.PNG)

But when I open second asset and choose tab Assets I don't see it.

![asset2](https://user-images.githubusercontent.com/29401151/37714141-11b89714-2d19-11e8-955e-497b9da709d2.PNG)

Is this the correct situation or I something have wrong?

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh
- Version of Snipe-IT you're running
v4.1.14 
- Version of PHP you're running
5.6.31
- Version of MySQL/MariaDB you're running
MySQL
- What OS and web server you're running Snipe-IT on
FreeBSD 11.1
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual

**Comment by andrewcgmorris** [comment]
We have noticed this also.
From the testing we have done it looks like the interface is searching for references using the wrong field value.

It is possible that this is also affecting the custom search in the assets.
You cannot search for nested assets (assets checked out to other assets) using the Asset ID or Name. If you type the Database row ID (eg 106) then you see the assets assigned to the asset on line 106 of the database table.

Here you can see the search works using 106 as the search parameter:
![capture1](https://user-images.githubusercontent.com/28731911/37783875-7108f74c-2dee-11e8-9a9a-c7c00ad2a783.JPG)

Here you can see using the Asset ID for that device it returns nothing:
![image](https://user-images.githubusercontent.com/28731911/37783942-9b0c35a4-2dee-11e8-86ba-f8596be5461a.png)

Perhaps these are related.

**Comment by snipe** [comment]
@ktoczyski 

Please provide answers to the questions you deleted.

- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

I cannot reproduce this on the demo.

<img width="1108" alt="screen shot 2018-03-22 at 2 22 19 pm" src="https://user-images.githubusercontent.com/197404/37799767-f0582196-2ddd-11e8-8f83-b7b1a9ed7e79.png">

<img width="1281" alt="screen shot 2018-03-22 at 2 22 33 pm" src="https://user-images.githubusercontent.com/197404/37799773-f63d7f66-2ddd-11e8-9861-28809ca8d02f.png">

Please check your error logs and see if there's anything useful in there.

**Comment by ktoczyski** [comment]
- If you're getting an error in your browser, include that error
No
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
stock.xxx.xxx/hardware/10#assets
- If a stacktrace is provided in the error, include that too.
No
- Any errors that appear in your browser's error console.
No
- Confirm whether the error is reproduceable on the demo.
No
- Include any additional information you can find in app/storage/logs and your webserver's logs.
I have not any errors.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
No

**Comment by snipe** [comment]
Try upgrading
