### ISSUE TITLE
PDU Asset assignment- need feature... 

### ISSUE THREAD

**Issue by jtrivino07** [snipe/snipe-it#5238]
#### Expected Behavior (or desired behavior if a feature request)
Having an issue with our PDU's (Power Distribution Units). We own these assets and want to be able to check out to **various** assets. The idea is that each PDU has either 12 or 24 outlets. I want to be able to go to the asset and assign checked out asset outlet 1 or 2 or three etc... I have also added fields for power outlet number being assigned to that device.  However, I'm not able to assign (link) or check out specific asset to multiple assets.
I tried using adding PDU as accessories, consumable, or categories. The problem when using these I'm not able to assign the "Asset Model" or existing asset as an accessory, consumable, or component. 
The only work around have been able to do is to have two create an asset and then create a component matching that asset making me create two records for one item.

The solution I'm truly looking for is to be able to add a custom filed said called PDU or power and be able to choose let's say PDU assets to drop down list and pick the one that the specific asset is using. 
I'm including some screenshots below to make everything a bit more clear... 

Adding PDU as an Asset - would like to be able to check out to more than asset if possible)

Screenshot#1
![image](https://user-images.githubusercontent.com/25510862/37743359-20f7a43c-2d40-11e8-912b-c9939c99d084.png)

when adding as Accessory (similar behavior with consumable or component) - I can't use the Asset model for PDU  or the assign the asset on screenshot above as an accessory or component) I'm not able to assign "custom fields", and for instance things like Model No. (which is part of adding the asset in screenshot#1)  making create two items for one asset? The same as rack position and U I can't add. Also how can I make this like 24 outlets available within this asset to make available to check out?
Screenshot#2
![image](https://user-images.githubusercontent.com/25510862/37743713-d23297b0-2d41-11e8-9311-ce930c1d93a9.png)

(what you expect to happen goes here)

Screenshot#3
I would like to be able to add different PDU's and be able to browse them here:
![image](https://user-images.githubusercontent.com/25510862/37744085-b74bc294-2d43-11e8-8d13-ec1c6053fc6c.png)
 Screenshot#4
Is it possible to add list of assets from DB in the drop down?
![image](https://user-images.githubusercontent.com/25510862/37744110-e4b6253a-2d43-11e8-86f7-a6c1bf18c238.png)

Any suggestions on how to go about this are welcome. Thank you!
-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode - Using your hosted services.
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) - couldn;t find anything related here

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? we are not hosting this.
- Version of Snipe-IT you're running -  | v4.1.14  build 3408 (ga705c71)
- Version of PHP you're running n/a
- Version of MySQL/MariaDB you're running n/a
- What OS and web server you're running Snipe-IT on n/a
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) n/a
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error n/a
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - included screenshots
- If a stacktrace is provided in the error, include that too. no errors
- Any errors that appear in your browser's error console. - looking for available feauture
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way - already explained.
- Indicate whether or not you've manually edited any data directly in the database - n/a

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Given the level of complexity to build this feature in and the other priorities on our roadmap, I don't see us building this any time soon. Assets currently have a one-to-one relationship with whatever they are checked out, so and it would be enormously complicated (especially factoring in company scoping) to change the way that works.
