### ISSUE TITLE
Start and End warranty dates for assets

### ISSUE THREAD

**Issue by robcalcroft** [snipe/snipe-it#524]
Would be great to be able to manually specify start and end dates for warranties as sometimes the purchase date is not the date that a warranty for the asset was purchased.
##

**Comment by VHWDev** [comment]
I totally support this idea. Just wanted to state that :)

**Comment by snipe** [comment]
Would we need an end date if you enter a warrantee time (in months). I feel like just a start date would work there.

![screen shot 2015-02-18 at 3 24 30 am](https://cloud.githubusercontent.com/assets/197404/6246431/b0068356-b71d-11e4-8c5c-e1557202ba1f.png)

**Comment by robcalcroft** [comment]
@snipe  Would we be able to change the unit we use for that? i.e. could we specify 'Days' instead of months? If so then yes this method will be great.

**Comment by VHWDev** [comment]
@snipe I would say a start date combined with the suggestion of @robcalcroft , this is something we're currently missing.

**Comment by drahamim** [comment]
I would love to be able to specify Warranty (or maybe a new field for Service coverage) with an end date. (My use case is servers which can get some tier of support that has an expiration date that is not based on purchase date and gets changed as contracts get renewed)

**Comment by twisted3motions** [comment]
My dells have a ship date (purchase date), and then a warranty start date a day or so off.  So a start of warranty would be nice
