### ISSUE TITLE
Ignore this, everything is good now!

### ISSUE THREAD

**Issue by Chris-2515** [snipe/snipe-it#5250]
Ignore this, everything is good now!

**Comment by snipe** [comment]
Awesome! Glad to hear you're all sorted. In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
