### ISSUE TITLE
LDAP Search OU for Locations with a path with spaces

### ISSUE THREAD

**Issue by meanderfox** [snipe/snipe-it#5251]
#### Expected Behavior (or desired behavior if a feature request)

Set the search OU for each location and the users should automatically be assigned to the locations they're in

-----

#### Actual Behavior

All of the users are going into a single location. I have a feeling that it has something to do with the DN to my OU having a space in it, but i could be way off the mark. If i just set a single location with an OU, it puts All of the users into that. if i set it in multiple, it seems to set all of the users to be in whichever location is alphabetically last. I have tried putting the string in quotes, but it didnt change the behavior.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?: Fresh
- Version of Snipe-IT you're running: 4.2.0
- Version of PHP you're running: 7.0.27-0+deb9u1
- Version of MySQL/MariaDB you're running: 10.1.26-MariaDB-0+deb9u1
- What OS and web server you're running Snipe-IT on: Debian 9.4.0
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: No error displayed, but it happens after setting a Search OU and syncing LDAP
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by jamiepassa** [comment]
Did you get this working?

**Comment by meanderfox** [comment]
I did, it appears as though the behavior is that if there are any users that fall outside of the scope of a previous OU filter, they will all go into the remaining. For example, if i have four OUs and i just put a filter on OU1, all users will end up in there. if  i put the filter in for OU1 and OU2, everyone in OU1 will be correct, and everyone else will be in OU2. Once i added all of the filters for all the locations, so there was complete coverage and all users would show up in one of them, it worked fine

**Comment by jamiepassa** [comment]
So I am trying to get locations to sync over from AD, we have a flat OU so all users in one OU.

________________________________

**Comment by sabait** [comment]
Is there any way to use Location Sync when you have users that are not in AD? As is stands if you have locations that are not assigned to Search OUs, they will randomly be assigned a location.
