### ISSUE TITLE
Importing with CSV into Encrypted Custom Field -  Error Decrypting: The payload is invalid.

### ISSUE THREAD

**Issue by xdanmeyerx** [snipe/snipe-it#5252]
#### Expected Behavior (or desired behavior if a feature request)

Data is imported to a custom encrypted Asset field and is encrypted as part of the csv import process. 

-----

#### Actual Behavior

Data is placed into custom field not encrypted (If you pull a csv report, the data is shown correctly). However, on the web GUI it says:  "Error Decrypting: The payload is invalid."

Understandably, the data I imported is not pre-encrypted, and thus, cannot be decrypted. 

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode (Import doesn't seem to work in Debug Mode)
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running v4.1.14 build 3446 (g90bff709a)
- Version of PHP you're running 7.0.25-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running - 10.0.34-0ubuntu0.16.04.1
- What OS and web server you're running Snipe-IT on Ubuntu, Apache 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc), git
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - No Error 
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - import
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. n/a
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
That's definitely a bug - thanks for reporting it!

**Comment by xdanmeyerx** [comment]
No one wants to work on my important issue? ;) Looks like I'm going stale.

**Comment by snipe** [comment]
@dmeltzer - can you take a look at this?

**Comment by inietov** [comment]
@viclou @snipe  Why this was reopened? Surely it was discussed, but I totally forgot. Someone remember?

**Comment by snipe** [comment]
I couldn’t tell you. Whenever we see invalid payload, it usually means the app key has changed. (This was also red-opened in 2019, so I’m going to assume it’s stale and can be safely closed.
