### ISSUE TITLE
Snipe-IT not working after changing MAIL_FROM_NAME in .env

### ISSUE THREAD

**Issue by ziyaul121** [snipe/snipe-it#5253]
#### Expected Behavior (or desired behavior if a feature request)

Whenever I am changing the MAIL_FROM_NAME=Snipe-IT to IT-Asset than error showing 
"The website cannot display the page" 

MAIL_DRIVER=smtp
MAIL_HOST=
MAIL_PORT=25
MAIL_ENCRYPTION=''
MAIL_FROM_ADDR=abc@xyz.com
MAIL_FROM_NAME=IT Asset
MAIL_REPLYTO_ADDR=abc@xyz.com
MAIL_REPLYTO_NAME=IT Asset 

I also restart the Httpd services to refresh the cache but still same error.  

-----

#### Actual Behavior

I wanted to Specify the name "IT Asset"that should show up in the recipient's inbox when they receive email

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode  yes
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) Yes

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running Version v4.1.14 
- Version of PHP you're running 7
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on Centos 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. "The website cannot display the page"
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Try changing `MAIL_ENCRYPTION=''` to `MAIL_ENCRYPTION=null`

**Comment by ziyaul121** [comment]
Thank you so much Dear @snipe , I really appreciate your support.
