### ISSUE TITLE
Removing Licenses

### ISSUE THREAD

**Issue by BiberM** [snipe/snipe-it#5257]
#### Expected Behavior (or desired behavior if a feature request)

We have certain licenses that need to be removed from our stock. Examples are Windows OEM Licenses. Once the device that came with the OEM license is archived or removed the licenses also need to be archived or scrapped. We need a way to mark licenses so that they cannot be checked out any more.

-----

#### Actual Behavior

Licenses can only be checked in and out. I can set an expiry date in the past. Additionally there is a checkbox whether this license can be assigned. The number of seats cannot be set to 0.
But still the license can be checked out to an asset or user.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
freshly installed v4 and then updated

- Version of Snipe-IT you're running
4.2.0

- Version of PHP you're running 
Didn't look it up. Is that needed in this case?

- Version of MySQL/MariaDB you're running
Didn't look it up. Is that needed in this case?

- What OS and web server you're running Snipe-IT on
Didn't look it up. Is that needed in this case?

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
area licenses (details in story above)

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
reproducible. I created the license 'Test_to_delete'.

- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
no editing DB-native.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by Jarli01** [comment]
Wouldn't deleting the license record from the system suffice?

**Comment by Jarli01** [comment]
Or are you still wanting to track the license even though it's past its usable life. 

Much like my ticket here: https://github.com/snipe/snipe-it/issues/3757

**Comment by BiberM** [comment]
Well yes and no (sort of).

I don't care if the license is still registered with us as long as I cannot use it / check it out anymore. But I can! I can assign a license which is expired and we don't own anymore to a user or an asset.

Somehow it would be nice if the license is just deactived and not deleted. This way you have the history.

I left the exact solution vage on purpose. Maybe the devs have another solution that I didn't think of.

**Comment by BiberM** [comment]
Just to add: The deletion of the license would be sufficient if there were the possibility to do that!

**Comment by snipe** [comment]
I'm not sure what you mean here. Licenses can be deleted.

![Uploading Screen Shot 2018-04-04 at 8.13.12 PM.png…]()

**Comment by BiberM** [comment]
I am sorry! I missed that as these buttons were hidden in the right and the scrollbar is only visible at the bottom.

So there is no possibility to keep the history but at least we can stay consistent. Thank you for the tip and sorry for any inconveniences.

**Comment by snipe** [comment]
@BiberM licenses are soft-deleted, I believe, so the history is still *there*, just hard to see through the UI. Perhaps a "deleted licenses" section should be added.

**Comment by itsjustpyro** [comment]
A deleted licenses section would still be a great option. 

Is there any way to get a report of the soft-deleted licenses?

**Comment by felibb** [comment]
Sorry to resurrect, but I'm at a point where I also would like to access a deleted license.  Any tips?
