### ISSUE TITLE
Import from .CSV stuck at 100%

### ISSUE THREAD

**Issue by Jwes115** [snipe/snipe-it#5260]
#### Expected Behavior (or desired behavior if a feature request)

Assets are imported to Snipe-IT

-----

#### Actual Behavior

File uploads and processes to 100% and no action is taken after this. No error message is displayed, and no records are added.

Initially I used the template from the website for assets. I also tried to export .csv and apply info to these fields and still no luck.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - Fresh install
- Version of Snipe-IT you're running - v3.6.4 build 12 (gf7e4fca)
- Version of PHP you're running - 7.0.28-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running - 5.2.45
- What OS and web server you're running Snipe-IT on - OSX
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Without a stack trace, we can't really tell what could be going on here. 

Also, you should probably upgrade. 3.6.4 is pretty old.
