### ISSUE TITLE
Feature Request - Show users their unaccepted assets

### ISSUE THREAD

**Issue by colinator19** [snipe/snipe-it#5265]
#### Feature Request

Once you assign assets to a user, they will get an acceptance email with a link. If they forget or lose the email, they have no option to accept the asset without knowing the exact link.

Can an overview be added to the system where you can see your unaccepted assets as a user?

At the moment, when you login as an user, you can show the assigned assets but you cannot see if the asset is not accepted nor is there a button to accept the asset in the event it was not accepted before.

-----

**Comment by colinerd** [comment]
To add to this - I would like to see under the user account (or asset) if it has been accepted or not and have it mention the EULA acceptance as well. 

I know there is a report but since it only shows non-accepted assets and you do might not have all categories turned on for acceptance, it give a more clear overview.

**Comment by goludiaOH** [comment]
I completely agree with this new feature request - my company would like the same functions.
a) as a user to be able to accept an asset from within the tool (see a list of assets pending your acceptance instead of having to hunt for all the emails)
b) a more clear indication of whether each asset was accepted or not

The history tab technically shows the history of when it has been accepted but it's difficult to parse and it would be helpful if that information was more prominent.  For instance if it is pending acceptance, there is no history line item.

**Comment by colinerd** [comment]
This would still be a feature request. Is there any update?

**Comment by tsbadam** [comment]
I agree, this would be a great request! Any update?

**Comment by mahesh2471990** [comment]
+1 i too agree we can get the reports of unaccepted but this is feature will be good. Easy for user if they missed out the mail

**Comment by oferzern** [comment]
+1 this would be great, and also it may be good to create a central page to accept all pending assets (if I've checked out 3-4 items at once over to the same person, instead of needing to click on 3-4 different links, just to click on one and there to accept everything at once)

**Comment by fletch8527** [comment]
What version was that introduced? Im on v4.6.2 but dont see it. I see its on the demo site, but that appears to be on a beta version of v5?

**Comment by ks9389** [comment]
Yes it’s on the beta.. you need to wait for release...

On 1 Nov 2018, at 12:44, fletch8527 <notifications@github.com<mailto:notifications@github.com>> wrote:


What version was that introduced? Im on v4.6.2 but dont see it. I see its on the demo site, but that appears to be on a beta version of v5?

**Comment by viclou** [comment]
+1 FD 13265

**Comment by snipe** [comment]
@viclou The previous ticket responses here in GH indicate that this is already on develop - is that not true?

**Comment by colinator19** [comment]
> @viclou The previous ticket responses here in GH indicate that this is already on develop - is that not true?

@snipe it was in dev for version 5.0 but that was never released and not sure what happend to that version either. 

It contained more feature requests I was really looking forward to.

It does not seem to be implemented anywhere is the 4.x versions afaik.

**Comment by feedback2ajeet** [comment]
Thats true its very it is very important feature ! this would be great to create a central page to accept all pending assets. May i know when it will release ?

**Comment by yanagha** [comment]
Hi, we are also waiting for this feature. It was in beta version 5.0 but the feature is not available in the current version and beta version also. When it will be available?

**Comment by yanagha** [comment]
Is there any update?

**Comment by Relix360** [comment]
Is there any chance for this to be in a v4.9.x version?

**Comment by sarang2502** [comment]
+1 This is still relevant

**Comment by Relix360** [comment]
bounty added to push this into master 

@snipe

**Comment by Relix360** [comment]
https://www.bountysource.com/issues/56464803-feature-request-show-users-their-unaccepted-assets


<blockquote><img src="https://cloudinary-a.akamaihd.net/bountysource/image/upload/d_noaoqqwxegvmulwus0un.png,c_pad,w_400,h_400,b_white/Bountysource_Animals61_aprjzp.png" width="48" align="right"><div><img src="favicon.ico?v=3" height="14"> Bountysource</div><div><strong><a href="https://www.bountysource.com/issues/56464803-feature-request-show-users-their-unaccepted-assets">$30 Bounty on snipe/snipe-it</a></strong></div><div>snipe/snipe-it</div></blockquote>

**Comment by yanagha** [comment]
When will be released Version v5.0.0?

**Comment by Relix360** [comment]
Is this going to be release on V5? @snipe

**Comment by fletch8527** [comment]
Still relavent

**Comment by Relix360** [comment]
@snipe This one is already resoved if im not wrong ^^
