### ISSUE TITLE
EULA showing in a small window

### ISSUE THREAD

**Issue by colinerd** [snipe/snipe-it#5266]
#### Expected Behavior (or desired behavior if a feature request)

When accepting assets, the EULA should be displayed in full (or atleast use the full screen size)

-----

#### Actual Behavior
EULA textarea is very small which means you have to scroll quite a bit if the EULA is rather larger like in our case.

![eula_smallwindow](https://user-images.githubusercontent.com/15741333/37958999-448f142c-31b2-11e8-9993-565d34f34ca5.JPG)

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh Install
- Version of Snipe-IT you're running 4.1.14
- Version of PHP you're running 7.1
- Version of MySQL/MariaDB you're running 10.1
- What OS and web server you're running Snipe-IT on Server 2016 - IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual Installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - http://*domainname*/account/accept-asset/2261
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - Unable to test
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by blackrandom** [comment]
I don't know if this is allowed but if you navigate to "snipe-it\resources\views\account\accept-asset.blade.php" you should be able to edit line 24:

`#eula_div {
    width: 100%;
    height: 200px;
    overflow: scroll;
}`

change the height to auto so it looks like:

`#eula_div {
    width: 100%;
    height: auto;
    overflow: scroll;
}`

This should resize that frame for you to the end. Again I'm not sure if you are comfortable editing the code directly or if I should be suggesting that so try at your own risk. I've made the change myself and it works for me but your case may be different. Also note, doing an 'upgrade' to a new version in the future will overwrite this file so keep the changes backed up.
