### ISSUE TITLE
Feature Request: Users can request asset type instead of specific asset ID

### ISSUE THREAD

**Issue by goludiaOH** [snipe/snipe-it#5269]
Our company workflow has many different types of assets, and many times employees just want an asset of a given type but don't care which specific asset it is.  We would prefer they request their asset type and leave it up to admins who manage the overall pool of assets to find the specific individual asset and check out that asset to the user.  

There may be different reasons we don't want to check out a specific asset to someone, maybe it's an older version and we have a newer one available, or some other reason the user doesn't care about. Similarly, there may be information about the asset available in snipe that the user doesn't understand.  Ultimately we don't want to put the burden onto the user to find a specific asset and have to request only that asset.

We want the admins to be able to configure what fields or asset categories users can request from.
Additionally, we'd like the request submission action to notify all admins or a configurable set of users.
-----

Currently I believe the only way for a user to request an asset is to go to the Requestable menu, find and select a specific asset (from among potentially thousands of assets), and click "request".  They are not able to request something more generic like "I want a 10" tablet" or "I want any device that has Android KitKat on it".

-----

#### Please confirm you have done the following before posting your bug report:

- [n/a ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running Version v4.1.11-pre - build 3299 (master)
- Version of PHP you're running PHP: 7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running mysql Ver 14.14 Distrb 5.7.21
- What OS and web server you're running Snipe-IT on OS:  Ubuntu 16.04 Web Server: Apache/2.4.18
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
We have this at the asset model level.
