### ISSUE TITLE
Feature Request: Improved Slack Integration

### ISSUE THREAD

**Issue by goludiaOH** [snipe/snipe-it#5270]
Our company uses Slack very heavily in our daily workflows across all teams.  People like to be able to integrate other tools so that they get notifications all in one place and can take actions from within slack (like the google drive integration for one example where you get notified about new document shares, comments within documents, etc).  We think it will lead to more reliable asset management if we can better integrate Snipe with Slack.

- We would like to have snipe integration to notify users about assets being transferred to them
- We would like to have snipe integration to accept or reject assets being transferred to them
- We would like to have snipe integration to initiate a transfer of an asset that I own using the asset ID to someone else (without being given the ability to leave it in a "checked in" state unless you're an admin)
- We would like to have snipe integration to list your currently owned assets, and if any are pending acceptance
- We would like to have snipe integration to set/send reminders to people that they have assets pending their acceptance.  The frequency of which is configurable by the admin (similar to the alert emails)

-----

Currently snipe posts notifications to a slack channel which you can subscribe to, but that means that each user subscribed there will get ALL transfer notifications.  Most of this slack integration mentioned above is not available. 

-----

#### Please confirm you have done the following before posting your bug report:

- [ n/a] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running Version v4.1.11-pre - build 3299 (master)
- Version of PHP you're running PHP: 7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running mysql Ver 14.14 Distrb 5.7.21
- What OS and web server you're running Snipe-IT on OS:  Ubuntu 16.04 Web Server: Apache/2.4.18
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
These are all great ideas, but we won't be able to implement this easily until we move to PHP7.

**Comment by snipe** [comment]
In the meantime, you (or someone else) could build a wrapper for the slash web hooks that ties into the API.

**Comment by goludiaOH** [comment]
Thanks for the reply - any ideas when you might move to PHP7?

**Comment by snipe** [comment]
Not for a while yet. Months and months, for sure.

**Comment by BrettFagerlund** [comment]
Not sure if this is still alive, but would love to get basic slack notifications on asset maintenance creation.

**Comment by poVoq** [comment]
Just to report, the Slack integration also works with a selfhosted Mattermost.

But it would be really nice (as sort of mentioned above) if the slack endpoint (to allow different Mattermost installations and teams) as well as the channel could be changed per company or maybe even department.

Especially in a multi-company setup the Slack/Mattermost integration is otherwise not really usable.

Thanks in advance for looking into this!
