### ISSUE TITLE
Default Company or Assets

### ISSUE THREAD

**Issue by chaaza** [snipe/snipe-it#5273]
#### Expected Behavior (or desired behavior if a feature request)

If an Admin of company A want to create users or assets or others like consumables and components, he can only create data to his company only. The company field for users or others like consumables and components are set as default to his company.

-----

#### Actual Behavior

The admin have to choose his company one by one when creating new assets or users. Moreover, he can create assets to another company which is not secure.

-----

**Comment by MuratKurnaz** [comment]
Is there a chance that this change would be added to snipe-it?
