### ISSUE TITLE
Feature Request: Location Managers be able to view assets assigned to their locations

### ISSUE THREAD

**Issue by Raykongstar** [snipe/snipe-it#5276]
#### Expected Behavior (or desired behavior if a feature request)

Location Managers should be able to view assets checked out to their locations. This will very much suite dynamic environments where managers of locations do change quite frequently. 

-----

#### Actual Behavior

Location Managers are unable to view assets assigned to their locations.

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode **Yes**
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) **Yes**

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Fresh** 
- Version of Snipe-IT you're running - **4.1.14**
- Version of PHP you're running - **7.1.17**
- Version of MySQL/MariaDB you're running - **MariaDB 10.0**
- What OS and web server you're running Snipe-IT on - **Windows Server 2012 R2** and **IIS**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - **Manual**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **No error, it's a feature request**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **Not applicable**
- If a stacktrace is provided in the error, include that too. **No stacktrace**
- Any errors that appear in your browser's error console. **None**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. **N/A**
- Include any additional information you can find in `storage/logs` and your webserver's logs. **N/A**
- Include what you've done so far in the installation, and if you got any error messages along the way. **N/A**
- Indicate whether or not you've manually edited any data directly in the database **No!**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
> Location Managers are unable to view assets assigned to their locations.

Are you using full company support? Locations do not currently (and likely will not soon) support granular location-specific permissions.
