### ISSUE TITLE
CSV Import

### ISSUE THREAD

**Issue by durrana** [snipe/snipe-it#5277]
#### Expected Behavior (or desired behavior if a feature request)

I have over 500 assets with names and surnames which are in Snipe database and I have created a CSV to refresh the users what are assigned to each device.

-----

#### Actual Behavior

After the import, the new users are not attached to the device.

I have created a csv with just one asset but this does not assign to the new user either.

Do I have to use a username or will it match 1st name and surname if the username is missing?

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade No
- Version of Snipe-IT you're running 4.20
- Version of PHP you're running 7.0.10
- Version of MySQL/MariaDB you're running 
- What OS and web server you're running Snipe-IT on Windows Server 2012
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) GitHub
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

**Comment by snipe** [comment]
It will try to create the username based off of the setting for usernames in the Admin Settings and the Full Name field.
