### ISSUE TITLE
Enhancement - Ability for admin to check requestable assets out to users

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#528]
Would be nice if an Admin could go into the Requestable section and check an item out to a user. This would keep the audit trail we need a give a quick view of all the requestable items. 

Based off the empty actions section I'm not sure if this functionality should already be here or not.

![image](https://cloud.githubusercontent.com/assets/10247644/6231998/53a304da-b697-11e4-9242-c741fc9192b5.png)

**Comment by madd15** [comment]
As an admin under assets there is a link to requestable which provides alist of all requestable and has the checkout option as well as edit and delete

**Comment by snipe** [comment]
@madd15 requestable doesn't yet have the ability to do anything, it's display only at the moment.

**Comment by snipe** [comment]
Opps, you're right, there is in the admin. I hit send too quickly and didn't read well enough. Derp.

**Comment by madd15** [comment]
I would be assuming that the actions section on the page in the image will provide users with a button to request the item, possibly a button for admin to approve the request (depending how it is handled ofcourse).

**Comment by kobie-chasehansen** [comment]
Another way I could see us using the feature would be someone comes to our desktop team for a requestable item, say a projector. The desktop guy grabs the projector, goes into the requestable section, clicks check out and then selects the user. When the projector comes back Desktop goes back into the requestable section and clicks check in.

In my use case I just dont think I can get my users trained to log in and request an asset but I can get my desktop team to do it. Right now they have to fill out a portable request form for tracking.

**Comment by madd15** [comment]
![reqass](https://cloud.githubusercontent.com/assets/3274937/6237737/36e81034-b745-11e4-9b57-8f1bada10dc5.png)

**Comment by kobie-chasehansen** [comment]
:( i feel stupid now

**Comment by snipe** [comment]
@kobie-chasehansen lol! Nah, I tend to blame the UX when I can't find stuff I'm looking for. Just blame me :)
