### ISSUE TITLE
Feature Request: Recent Activity for non-admin users/more granular report permissions, notes on checkout of accessories

### ISSUE THREAD

**Issue by delize** [snipe/snipe-it#5285]
#### Expected Behavior (or desired behavior if a feature request)
We are trying to roll out a new service using SnipeIT in that our office management has meeting room related hardware (because our office apparently can't clean up after themselves). 

I have created a group that allows those users to be able to view, checkout and checking accessories, and allows them to request requestable assets (for now as we wanted to see which would work better). After sitting down with the employee that would potentially test this out, he had a few requests that he wanted to see done to make it easier on the employees performing this so they knew instantly who still had what.

He basically wanted a "shopping cart" view of all the items that have been checked out - with that said, his example was to go to Amazon, proceed to check out three items and put them in the cart, and then say once an employee turned them back in, they could be deleted. This already sorta exists with the current views for an item within accessories, however - an employee would have to go narrow down on that view - and since there are no notes associated with an item and there is no "differentiation" between each accessory (besides creating separate accessories for every "unique" item - say cable 1, cable 2) it makes it difficult for the employee to know who has now checked back in what cable. This becomes more relevant if they request two of the same item but then only turn back in one.

Some solutions:
- Having a recent activity on the users's page based on that user's activity (if a user has checked out, checked in an item it would show up there) basically a filtered view of the /reports/activity page based on the current logged on user.
- Allowing for more granular permissions in to the reports access. Instead of it just being all or nothing to be able to see the /reports/activity page, allow access to specific reports at the permissions level, so we could enable access to the previous link, but leave all other reports disabled.
- Add a notes feature to checkout as well, to match the same functionality of checkin.

-----

#### Actual Behavior

N/A

-----

#### Provide answers to these questions:

- Is this a fresh install or an upgrade? upgrade
- Version of Snipe-IT you're running v4.1.10 - build 3249 (master)
- Version of PHP you're running Docker version
- Version of MySQL/MariaDB you're running MySQL 5.6.38
- What OS and web server you're running Snipe-IT on Docker
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error N/A
- If a stacktrace is provided in the error, include that too. N/A
- Any errors that appear in your browser's error console. N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. N/A
- Include any additional information you can find in `storage/logs` and your webserver's logs. N/A
- Include what you've done so far in the installation, and if you got any error messages along the way. N/A
- Indicate whether or not you've manually edited any data directly in the database N/A

**Comment by delize** [comment]
Not stale... :/

**Comment by delize** [comment]
Is there any way to tell stale bot to ignore feature requests? Seems redundant to close a feature request due to staleness the sole reason it is stale is that no one is working on it.

**Comment by delize** [comment]
@snipe can you re-open this? I don't see a way to do so. :(

**Comment by dynomation4** [comment]
I would also like to request this feature! :)
