### ISSUE TITLE
Install / upgrade to a fixed version

### ISSUE THREAD

**Issue by benrubson** [snipe/snipe-it#5288]
Hi,

When we install or upgrade, git master branch is used.
We should rather be able to install or upgrade to a fixed version, for example v4.2.0.
IMO I think it's better to use a released version rather than the master branch which could contain some new "development" bugs.
Could it then be possible to update installation / upgrade procedures so that we can specify a version ?
Or create a `release` branch which would contain the last released version ?
There are several possibilities here...

Thank you very much 👍 

Ben

**Comment by snipe** [comment]
Master is considered stable and always has the latest hotfixes on it. (It's what we deploy our customers from.) The develop branch is the one for folks who want to live dangerously. (We do not accept PRs against master, only develop, unless they are emergency hot fixes.)

**Comment by snipe** [comment]
Additionally, if you use `php upgrade.php tags/<version>`, it should check out whatever tag you want.

**Comment by benrubson** [comment]
OK thank you @snipe 👍
