### ISSUE TITLE
Missing Check in / out button after updating to 1.2.4

### ISSUE THREAD

**Issue by Gabisonfire** [snipe/snipe-it#529]
Like the title says, after updating to 1.2.4, the Check In / Check Out button is missing on the licenses view. I've tried to reinstall completely but the issue is still present.

Let me know if I need to provide more information! Thanks!

**Comment by kobie-chasehansen** [comment]
this is due to an interface change, is the check in/out button there when you click into the license?

**Comment by kobie-chasehansen** [comment]
the interface got extremely cluttered when working with multiple licenses for the same product. You can see the discuession on this top here in #508

**Comment by Gabisonfire** [comment]
![2015-02-17 14_17_13-snipe it asset management](https://cloud.githubusercontent.com/assets/6416239/6235339/ca034208-b6af-11e4-80d9-8a398080fcc4.png)

I do see the check in button when I click on the license though.

**Comment by kobie-chasehansen** [comment]
Not sure what other thoughts @snipe has for the license screen.

Pretty sure its open up to discussion if you have some improvement suggestions.

**Comment by Gabisonfire** [comment]
Thought I'd include the top row as well to show that even the column won't show up.
![untitled](https://cloud.githubusercontent.com/assets/6416239/6236310/ace4f376-b6b7-11e4-9d7b-613a722bd6b4.png)

**Comment by snipe** [comment]
Yes, this isn't an accident. It was a request by several users, as that page was getting really hard to handle with a lot of licenses. If you have any suggestions on other ways we can handle it, we're definitely open to hearing them.

**Comment by Gabisonfire** [comment]
Oh ok I can understand that. That would not be an issue but we are moving all our licenses from a wiki to snipeit so that makes it a bit harder. Maybe being able to customize the view for that page would be great or being able to check out the license when you create it would ease that. 

Anyways, thanks for earing me out :)

**Comment by snipe** [comment]
Or how about this.... If there are any open seats on a license, a checkout button appears on that listing page. If there are no open seats, you have to click into the license to checkout some seats.

**Comment by Gabisonfire** [comment]
Even better!

**Comment by snipe** [comment]
@kobie-chasehansen does that meet your needs as well? If so, I'll take it on.

**Comment by kobie-chasehansen** [comment]
Think that works well. guessing it will just pick the next avl seat to check out?

**Comment by snipe** [comment]
Exactly. Since the actual seat itself doesn't matter.

**Comment by kobie-chasehansen** [comment]
sounds good.

any additional thought on how to handle the same software under different purchases or is that a much bigger enhancement/project?

**Comment by snipe** [comment]
It's a slightly bigger project, but also I need to really think through what that flow looks like. It's gnarly from a UX perspective.
