### ISSUE TITLE
Import Assets Does Not Check Out To User

### ISSUE THREAD

**Issue by CSmilwaukee** [snipe/snipe-it#5290]
#### Expected Behavior (or desired behavior if a feature request)

When importing assets with csv, leaving status blank and providing a username, it should automatically be checked out to that user.

-----

#### Actual Behavior

Asset gets created however status is set to ready to deploy and asset is not checked out to any user.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running 4.2.0
- Version of PHP you're running 5.6.34
- Version of MySQL/MariaDB you're running 5.5.56-MariaDB
- What OS and web server you're running Snipe-IT on Linux
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by dmeltzer** [comment]
Does it work if you provide a status? Or does it not work at all?

**Comment by CSmilwaukee** [comment]
Hello, I tried with a status of Ready to Deploy and Deployed but neither check out the asset. The status says "deployed" but doesn't say to who.

**Comment by jasonlshelton** [comment]
Changing the Header row of my CSV file has resolved the issue for me. Instead of "Name" I have "Full name" and rather than selecting "Checked out to" when importing, I mapped that field to "Full Name"

**Comment by CSmilwaukee** [comment]
@jasonlshelton life saver! That worked. Thanks so much.

**Comment by dmeltzer** [comment]
Hello,

Are you importing use the CLI or the web importer? If the web importer, did you assign the "name" field to the "Full name" importer column before pressing import? Or was this field left blank?

**Comment by CSmilwaukee** [comment]
Hi, I was using the web importer.

In addition to changing the header in the CSV from "name" to "Full name" I did assign that field to the "Full name" in the import field column. I did not leave it blank.

Thanks

**Comment by seankaiser** [comment]
@MJ-DA, I was having the same issue that you're having, also on version 4.2.0, and worked around it by importing both full name and username into their respective fields. The import process seems to be checking the asset out to the user found via the full name, and matching it to the user record found via the username.

Hope that helps!

**Comment by mankdhodi** [comment]
Hi Team, Everytime i fetch asset from the csv file, it misses on the checked out to field and it turns out to be blank..I have also tried to map checked out to field with full name it converts the asset into user in the checked out to column and makes new entry of an user in the people section in navigation tree....It will be great if you can tell me the proper field name for this to map it to snipe/IT...

**Comment by EddySo** [comment]
Hi Everyone, I had same issue, Thanks a lot to @jasonlshelton, change my CSV header from "Checked out" to "Full Name" solved my problèm.

My poblem was: Impossible to link user with asset after importing aset CSV with targeting user.

Thank you!
