### ISSUE TITLE
This page isn’t working. currently unable to handle this request. HTTP ERROR 500

### ISSUE THREAD

**Issue by jloutsch** [snipe/snipe-it#5294]
#### Expected Behavior (or desired behavior if a feature request)
The SnipeIT page loads
-----

#### Actual Behavior
The http 500 error occurs

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh install
- Version of Snipe-IT you're running - 4.2.0
- Version of PHP you're running - 7.1.15
- Version of MySQL/MariaDB you're running - Ver 15.1 Distrib 5.5.56-MariaDB, for Linux (x86_64) using readline 5.1
- What OS and web server you're running Snipe-IT on - CentOS 7, httpd
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error. can't load any browser pages
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - happens when loading the main IP of the server. 
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. 500 Internal Server Error
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo: Demo loads properly
- Include any additional information you can find in `storage/logs` and your webserver's logs.
httpd access log:

php7:error] [pid 1672] [client 10.8.0.190:56858] PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/html/snipeit/app/Exceptions/Handler.php:39\nStack trace:\n#0 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Dotenv\\Exception\\InvalidFileException))\n#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Dotenv\\Exception\\InvalidFileException))\n#2 /var/www/html/snipeit/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))\n#3 {main}\n  thrown in /var/www/html/snipeit/app/Exceptions/Handler.php on line 39

- Include what you've done so far in the installation, and if you got any error messages along the way. Installation completed successfully. I disabled firewall and SElinux as a test and still saw the 500 error.

- Indicate whether or not you've manually edited any data directly in the database. No.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/installation-issues#section-fatal-error-uncaught-exception-reflectionexception-with-message-class-log-does-not-exist

**Comment by jloutsch** [comment]
Thanks for providing that link. All set now.
