### ISSUE TITLE
Can I generate asset report with crontab job.

### ISSUE THREAD

**Issue by ziyaul121** [snipe/snipe-it#5295]
#### Expected Behavior (or desired behavior if a feature request)

I wanted to generate asset report with the help of cron job in a month and automatically send report by Email . How I Can achieve?  

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  Fresh installed 
- Version of Snipe-IT you're running Version v4.1.14
- Version of PHP you're running 7
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on centos 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh 
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by ziyaul121** [comment]
is it possible?

**Comment by EarlRamirez** [comment]
You have a few options to achieve this, assuming that you have full access to the database you can use your favourite programming language to run the SQL query to generate the asset report have it emailed.

**Comment by ziyaul121** [comment]
Dear @EarlRamirez ,
Thanks a lot.
Yes, I do have full access on the database. Could you please give me some details.?

**Comment by EarlRamirez** [comment]
@ziyaul121 I will try and create a script when I have some free time, hopefully, by the end of this week and share it with the community

**Comment by ziyaul121** [comment]
Dear @EarlRamirez , 
Great, That's very kind of you. I really appreciate this.

**Comment by EarlRamirez** [comment]
@ziyaul121 sorry for the delayed response, are there any special format you will like this report in? What sort of information are you expecting in this report? Asset name, serial, model etc.

I am sort of getting my hand wet with python so bear with me a little :smiley:

**Comment by ziyaul121** [comment]
Dear @EarlRamirez , Format either csv or excel, that would be great. The information in the report like asset name , Asset tag , Serial , Model , Model No, location, company name and checkedout to are required. 

Sure Sure, I very much  appreciate your efforts and kindness.
