### ISSUE TITLE
Highlight top result, rather than Clear Selection, in Location search drop down

### ISSUE THREAD

**Issue by joepitt91** [snipe/snipe-it#5296]
#### Expected Behavior (or desired behavior if a feature request)

1. Go to a page with a Location drop down (Create Asset, Check Out to location)
2. Click into Location drop down
3. Scan barcode which is exact match to a Location Name (i.e. type exact Location name and hit Enter)
4. Scanned/Typed Location is Selected in Location box

-----

#### Actual Behavior

1. Go to a page with a Location drop down (Create Asset, Check Out to location)
2. Click into Location drop down
3. Scan barcode which is exact match to a Location Name (i.e. type exact Location name and hit Enter)
4. Location box is cleared as Enter key accepts Clear Selection, rather than the top search result

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode: N/A - Feature Request
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) - N/A - Feature Request

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? fresh
- Version of Snipe-IT you're running: v4.2.0 - build 3497 (master)
- Version of PHP you're running: PHP 7.0.28-0
- Version of MySQL/MariaDB you're running: MySQL 5.7.21-0
- What OS and web server you're running Snipe-IT on: Ubuntu 16.04.4 LTS (GNU/Linux 4.13.0-37-generic x86_64)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual - following installation guide.
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: N/A - Feature Request
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: /hardware/create
- If a stacktrace is provided in the error, include that too.: N/A - Feature Request
- Any errors that appear in your browser's error console.: N/A - Feature Request
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.: Yes
- Include any additional information you can find in `storage/logs` and your webserver's logs.: N/A - Feature Request
- Include what you've done so far in the installation, and if you got any error messages along the way.: N/A - Feature Request
- Indicate whether or not you've manually edited any data directly in the database: no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by joepitt91** [comment]
Bump to stop the stale bot closing this while its under consideration.

**Comment by snipe** [comment]
@tilldeeke does your PR resolve this issue?

**Comment by tilldeeke** [comment]
I think this is the same underlying issue as #5857 🤔

The scanner types "Enter" while the ajax request for the search is ongoing. Since the list tries to select an entry after the "Enter" key is pressed, this would select the wrong entry.

I'm going to think about this a bit more and will open a PR when I find a solution that should fix both of them. 😊

**Comment by takuy** [comment]
@tilldeeke I do think your #5857 PR fixed this. This seems to be the current behavior on the Demo site. It'll always default to the first element in the list, rather than "Clear Selection" like it was before.

**Comment by tilldeeke** [comment]
@takuy When the whole result set is loaded into the select list, then this will be fine. But when the results aren't completely loaded (Location "AAA" - "GGG" are loaded, "GGH" - "ZZZ" are not) we have a race condition. When I search for "ZZZ" and press enter directly, the select list will select the first entry while the ajax request is still ongoing. But because only "AAA" to "GGG" are loaded so far, the select list doesn't pick the correct entry. 🤔

**Comment by joepitt91** [comment]
Race condition outstanding

**Comment by joepitt91** [comment]
Race condition still present
