### ISSUE TITLE
request: CVS upload file： transform the encoding of CVS to UTF-8 

### ISSUE THREAD

**Issue by jintongqiao** [snipe/snipe-it#5297]
Hello, I'm here again.

I came from China, and I recently submitted a question about the time when CVS contained Chinese, the upload stopped at 10%, and the Chinese data turned into a random code after importing CVs. I recently found out:

When I open the CVS file with TXT text, then save it into UTF-8 format, and then import it to snipe-it, the Chinese display is normal, no more random code.

So, I think the solution to Chinese garbled problem is to transform the encoding of CVS to UTF-8 when uploading CVS to server. Maybe in the source code, we need to add a judgement when uploading. It's not utf8 encoding, it's converted to utf8 encoding.

I hope you can give me some advice, though I am not good at PHP programming. Thank you

**Comment by jintongqiao** [comment]
Similarly, in the report - custom report, open the exported CVS file directly in the report, Chinese is a random code, but if you open the exported CVS with txt and then save it as utf8 format, then it is normal Chinese to open the CVS view at this time.

**Comment by snipe** [comment]
That sounds like the encoding should be set to UTF-8 as you're exporting the CSV. Encoding can be handled via tools like iconv, however we cannot assume that every user has that installed, so it's not really practical to handle that on the server.

**Comment by jintongqiao** [comment]
I'm sorry, sir.
Because I'm not good at PHP programming, can you tell me which file, and  where to add the conversion code that can change the uploaded CVS file to utf8? Come on, please.

**Comment by snipe** [comment]
I am not a sir.

There is no code to add anywhere. Try [saving your CSV in alternate encodings in Excel,](https://www.ablebits.com/office-addins-blog/2014/04/24/convert-excel-csv/) and/or use something like [iconv](https://www.gnu.org/software/libiconv/) to convert via the command line.
