### ISSUE TITLE
Depreciation Report issue

### ISSUE THREAD

**Issue by raz0r-r** [snipe/snipe-it#5298]
#### Expected Behavior (or desired behavior if a feature request)

A functioning Depreciation Report

-----

#### Actual Behavior

Whenever even a single custom depreciation is set (assigned to a model or not), the depreciation report page returns a "Whoops" error.

This started suddenly after one of the upgrades (using upgrade.php).

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
**Initial install that has been upgraded several times.**
- Version of Snipe-IT you're running
**v4.2.0 - build 3497**
- Version of PHP you're running
**PHP 7.0.28-0ubuntu0.16.04.1**
- Version of MySQL/MariaDB you're running
**MariaDB 10.0.34**
- What OS and web server you're running Snipe-IT on
**Ubuntu 16.04.3 LTS, Apache/2.4.18**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
**Install.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
**Attached whole error page with debug turned on (changed to .txt from .html)**
[depreciation.txt](https://github.com/snipe/snipe-it/files/1868029/depreciation.txt)

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
**/reports/depreciation**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
**Can not reproduce on the demo page**
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
**Have added/imported assets directly to snipeit.assets (some do not have a Tag at all at this point, could this be the cause?)**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Can you provide the lines around line 74 in /var/www/snipe-it/resources/views/reports/depreciation.blade.php

**Comment by raz0r-r** [comment]
Lines 59-99

         <tbody>
              @foreach ($assets as $asset)
              <tr>
                <td>{{ is_null($asset->company) ? '' : $asset->company->name }}</td>
                <td>
                  @if ($asset->model)
                  {{ $asset->model->category->name }}
                  @endif
                </td>
                <td>
                  @if ($asset->deleted_at!='')
                  <del>{{ $asset->asset_tag }}</del>
                  @else
                  {{ $asset->asset_tag }}
                  @endif
                </td>
                <td>{{ $asset->model->name }}</td>
                @if ($snipeSettings->display_asset_name)
                <td>{{ $asset->name }}</td>
                @endif
                <td>{{ $asset->serial }}</td>
                <td>
                  @if ($asset->model->depreciation)
                  {{ $asset->model->depreciation->name }}
                  @endif
                </td>
                <td>
                  @if ($asset->model->depreciation)
                  {{ $asset->model->depreciation->months }}
                  @endif
                </td>
                <td>
                    @if (($asset->checkedOutToUser()) && ($asset->assigned))
                       {{ $asset->assigned->getFullNameAttribute() }}
                    @else

                        @if ($asset->assigned)
                            {{ $asset->assigned->name }}
                        @endif
                    @endif
                </td>

**Comment by snipe** [comment]
Whats actually on line 74 of that file? No line numbers in GH issues :(

**Comment by raz0r-r** [comment]
@endif
                </td>
                <td>{{ $asset->model->name }}</td>

These are lines 73, 74 & 75

**Comment by snipe** [comment]
It sounds like you have an asset without a model then?

**Comment by raz0r-r** [comment]
Yes, that fixed it. Did a couple of queries in the asset table and found an asset with model_id set to 0, weirdly enough. Changed it to the appropriate value and that fixed it. 

Thanks!
