### ISSUE TITLE
Deleted Asset

### ISSUE THREAD

**Issue by david-vernon** [snipe/snipe-it#530]
Newly installed 1.2.3 yesterday, then upgraded to 1.2.4 this morning on Linux (Apache24 PHP54).

When I click on the new "Deleted" assets link I get an error:

*Trying to get property of non-object (View: /var/www/html/app/views/backend/hardware/index.blade.php)*
*/var/www/html/app/storage/views/8e98b8bb60ffb211112e6eb903e2e04a#77*

*Trying to get property of non-object*
*/var/www/html/app/storage/views/8e98b8bb60ffb211112e6eb903e2e04a#77*

No other errors encountered.

![image](https://cloud.githubusercontent.com/assets/11035822/6237602/53cd0408-b6c2-11e4-9685-331a7e2f29de.png)

**Comment by snipe** [comment]
Can you pull the latest off develop and see if that solves your problem? We're about ready to do a new release.

**Comment by david-vernon** [comment]
I pulled develop, and still seeing the same page.

**Comment by snipe** [comment]
Can you show me a few lines of code above and below line 77 in /var/www/html/app/storage/views/8e98b8bb60ffb211112e6eb903e2e04a?

**Comment by david-vernon** [comment]
<thead>
        <tr role="row">
                <th class="col-md-1" bSortable="false"></th>
            <th class="col-md-1" bSortable="true"><?php echo \Illuminate\Support\Facades\Lang::get('admin/hardware/table.asset_tag'); ?></th>
            <th class="col-md-3" bSortable="true"><?php echo \Illuminate\Support\Facades\Lang::get('admin/hardware/table.asset_model'); ?></th>
            <?php if(Setting::getSettings()->display_asset_name): ?>
            <th class="col-md-3" bSortable="true"><?php echo \Illuminate\Support\Facades\Lang::get('general.name'); ?></th>
            <?php $spanrows++; ?>
            <?php endif; ?>
            <th class="col-md-2" bSortable="true"><?php echo \Illuminate\Support\Facades\Lang::get('admin/hardware/table.serial'); ?></th>
            <th class="col-md-2" bSortable="true"><?php echo \Illuminate\Support\Facades\Lang::get('general.status'); ?></th>
            <th class="col-md-2" bSortable="true"><?php echo \Illuminate\Support\Facades\Lang::get('admin/hardware/table.location'); ?></th>
            <?php if(Input::get('Deployed') && Setting::getSettings()->display_checkout_date): ?>
            <th class="col-md-2" bSortable="true"><?php echo \Illuminate\Support\Facades\Lang::get('admin/hardware/table.checkout_date'); ?></th>
            <?php $spanrows++; ?>
            <?php endif; ?>
            <?php if(Setting::getSettings()->display_eol): ?>
                <th class="col-md-2"><?php echo \Illuminate\Support\Facades\Lang::get('admin/hardware/table.eol'); ?></th>
                <?php $spanrows++; ?>
            <?php endif; ?>
            <th class="col-md-1"><?php echo \Illuminate\Support\Facades\Lang::get('admin/hardware/table.change'); ?></th>
            <th class="col-md-2 actions" bSortable="false"><?php echo \Illuminate\Support\Facades\Lang::get('table.actions'); ?></th>
        </tr>
    </thead>

**Comment by snipe** [comment]
Also, have you added any production data in there yet? If not, try re-seeding the database with `php artisan db:seed`

**Comment by david-vernon** [comment]
Sorry... trying again.

    <thead>
        <tr role="row">
                <th class="col-md-1" bSortable="false"></th>
            <th class="col-md-1" bSortable="true"><?php echo \Illuminate\Support\Facades\Lang::get('admin/hardware/table.asset_tag'); ?></th>
            <th class="col-md-3" bSortable="true"><?php echo \Illuminate\Support\Facades\Lang::get('admin/hardware/table.asset_model'); ?></th>
            <?php if(Setting::getSettings()->display_asset_name): ?>
            <th class="col-md-3" bSortable="true"><?php echo \Illuminate\Support\Facades\Lang::get('general.name'); ?></th>
            <?php $spanrows++; ?>
            <?php endif; ?>
            <th class="col-md-2" bSortable="true"><?php echo \Illuminate\Support\Facades\Lang::get('admin/hardware/table.serial'); ?></th>
            <th class="col-md-2" bSortable="true"><?php echo \Illuminate\Support\Facades\Lang::get('general.status'); ?></th>
            <th class="col-md-2" bSortable="true"><?php echo \Illuminate\Support\Facades\Lang::get('admin/hardware/table.location'); ?></th>
            <?php if(Input::get('Deployed') && Setting::getSettings()->display_checkout_date): ?>
            <th class="col-md-2" bSortable="true"><?php echo \Illuminate\Support\Facades\Lang::get('admin/hardware/table.checkout_date'); ?></th>
            <?php $spanrows++; ?>
            <?php endif; ?>
            <?php if(Setting::getSettings()->display_eol): ?>
                <th class="col-md-2"><?php echo \Illuminate\Support\Facades\Lang::get('admin/hardware/table.eol'); ?></th>
                <?php $spanrows++; ?>
            <?php endif; ?>
            <th class="col-md-1"><?php echo \Illuminate\Support\Facades\Lang::get('admin/hardware/table.change'); ?></th>
            <th class="col-md-2 actions" bSortable="false"><?php echo \Illuminate\Support\Facades\Lang::get('table.actions'); ?></th>
        </tr>
    </thead>

**Comment by david-vernon** [comment]
Yes, I seeded the db then deleted several of the assets. After re-seeding the error is gone.

**Comment by snipe** [comment]
Great - we fixed an issue with a duplicate item in the seed last night.

**Comment by david-vernon** [comment]
Looks great!!!

Thanks!

**Comment by snipe** [comment]
![tumblr_mhd2w9yhdp1s410g9o1_400](https://cloud.githubusercontent.com/assets/197404/6238666/d559a370-b6b1-11e4-8926-b0f75278b524.gif)
