### ISSUE TITLE
LDAP Issue : Can connect to LDAP server but cannot login

### ISSUE THREAD

**Issue by mulvenstein** [snipe/snipe-it#5300]
#### Expected Behavior (or desired behavior if a feature request)

LDAP works with sign in + authentication
-----

#### Actual Behavior

cannot login to LDAP
-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
   upgrade
- Version of Snipe-IT you're running 
   4.2
- Version of PHP you're running 
   5.6.33-0+deb8u1
- Version of MySQL/MariaDB you're running:
  Ver 14.14 Distrib 5.5.59
- What OS and web server you're running Snipe-IT on
   Turnkey linux + apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
   git
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
   admin/ldap test ldap button
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
   GET http://10.22.13.162/uploads/logo.png 404 (Not Found)
ldap:1 This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
   Able to authenticate, but cannot login. Am able to connect to LDAP admin on seperate windows machine
- Indicate whether or not you've manually edited any data directly in the database
   no i have not

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

![ldap1](https://user-images.githubusercontent.com/24484884/38217200-763b7504-369b-11e8-8072-42b2db998463.PNG)
![ldap2](https://user-images.githubusercontent.com/24484884/38217201-7647b9d6-369b-11e8-92ee-3617f197b54b.PNG)

**Comment by jmb1304** [comment]
I am having the same issue.

**Comment by mulvenstein** [comment]
Found a workaround with https://github.com/snipe/snipe-it/issues/3234#issuecomment-276964973.

**Comment by jmb1304** [comment]
I have solved the problem. The recommended config is listed on their website if you are using Active Directory.

[https://snipe-it.readme.io/docs/ldap-sync-login](https://snipe-it.readme.io/docs/ldap-sync-login)

**Comment by jasonlshelton** [comment]
I'm assuming you are putting the correct password in for binduserpassword? Are there any errors on the LDAP server? Maybe a failed login attempt that may point the the answer?
