### ISSUE TITLE
Azure PaaS (Windows) Question

### ISSUE THREAD

**Issue by cdeli** [snipe/snipe-it#5303]
Working on getting Snipe-IT configured in Azure PaaS. Has this been attempted yet? I am running into an issue with the public folder side of things now, the MySQL DB is up and running but the permissions on the public folder seem to be an issue for me at this time.

**Comment by cdeli** [comment]
Looks like I am getting the error "D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory." Not sure where to change this since I am using a windows app service plan in Azure. Tried a few settings but nothing so far.

**Comment by snipe** [comment]
I don't know Azure PaaS very well, but maybe this will help? https://stackoverflow.com/questions/18925075/how-can-i-set-the-root-folder-for-an-azure-websites-site

**Comment by cdeli** [comment]
Its a step in the right direction. This would be a lot easier if Microsoft didnt break the IIS Manager connection you could do. I could then have set it up just like a normal IIS site.

I will keep plugging away. Would like to be able to to get this working and author some instructions for others to use as well.

**Comment by snipe** [comment]
Sure, that would be great. Once you get it sorted, if you want to post some instructions here in Markdown, we'll move them to the docs site.

**Comment by cdeli** [comment]
Large issue I am running into is the key generation, while you can install Composer via the extension in the web-app in Azure, you don't have the following command available that I have found yet.

`php artisan key:generate`

If anyone has a workaround for this then that would be helpful. I am still looking myself.

**Comment by BrettFagerlund** [comment]
You should be able to generate locally via `php artisan key:generate --show.` 
 or via ps (works in azure shell/kudu)
`$appkey = 'base64:' + [Convert]::ToBase64String((1..32 |% { [byte](Get-Random -Minimum 0 -Maximum 255) }))`
then push APP_KEY=$appkey into the env file manually or via cli

**Comment by snipe** [comment]
Hm, not having artisan commands available is problematic though.... 

This guide is long, but I think it's what you might need?
http://blog.bobbyallen.me/2015/06/26/configuring-and-hosting-laravel-5-x-applications-on-windows-azure/

There are obviously bits that don't apply here, but specifically the composer/artisan stuff is probably what you're looking for.

**Comment by BrettFagerlund** [comment]
Is it only the keygen that fails? or all artisan stuff?

**Comment by BrettFagerlund** [comment]
Artisan should work as expected for migrations going via kudu. 

On another note, make sure to configure the additional verbs as its not in the source config(might be good idea?) 
You can find the list here - https://snipe-it.readme.io/v4.2.0/docs/windowsiis

And i'm pretty sure the spatie backup is going to have issues, but with a scheduled app services backup it's not really necessary.

**Comment by snipe** [comment]
Yeah, the backup doesn't currently like remote databases as a limitation of the library we use. :(

**Comment by cdeli** [comment]
Got a bit busy, haven't kept up on this as I should have recently. Some IIS settings that require going into IIS may not work and I need to work them in differently due to IIS manager not working with Azure currently. 

Going to try the keygen via kudu tomorrow or next week once I have a moment and see if I can get it to work.

**Comment by BrettFagerlund** [comment]
Which settings are you referring to? There shouldn't be anything which can't go in directly via config.

btw all the keygen does is generate the appkey which can easily be done manually.

**Comment by Bukhosi** [comment]
Hello , Did you suceed with Azure deployment?

**Comment by rahulrana-XOM** [comment]
cdeli or anyone: any luck deploying Snipe-IT to an windows Azure App Service? Everything is mostly up and running except the API throws a 500 error whenever called which I'm thinking is due to some IIS permissions.

No way to use IIS Manager with Azure web apps so are there any alternatives?

**EDIT**: I no longer get http 500 errors on API calls after installing the composer extension in Kudu and running `composer update`
