### ISSUE TITLE
Feature Request: Synchronizing the various notes fields into one

### ISSUE THREAD

**Issue by docdre721** [snipe/snipe-it#5306]
#### Expected Behavior (or desired behavior if a feature request)

Desired behavior: Any notes from either the check in/out process or asset update page will sync and show in all other notes fields

-----

#### Actual Behavior
When entering notes in the checkin/checkout/asset update process, the information doesn't sync across the other notes fields and is creating some confusion.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
> When entering notes in the checkin/checkout/asset update process, the information doesn't sync across the other notes fields and is creating some confusion.

I can't see how this would be expected behavior. Can you give me a use case?

**Comment by docdre721** [comment]
if someone enters information into the notes field on check in, this data is not present on the “List All” notes column. You have to check the asset history to see the note. Same thing happens if data is entered into the notes field upon checkout.

--
Dré Hopson
User Success Consultant

Technology and Innovation –
Davidson College
(704)894-2965 - Direct Line
(704)894-2900 - Service Desk

**Comment by snipe** [comment]
Those are really two different tables though. The All Assets page shows you information about the assets themselves. We could potentially show you the last checkout/checkin note in that view, but it would be difficult to sort on, since that information isn't in the assets table, it's in the checkin/checkouts table. 

> Any notes from either the check in/out process or asset update page will sync and show in all other notes fields

That could potentially be a lot of notes (taking up a lot of space on the screen), and would likely break  most people's layouts. I could potentially see a trigger able modal window that has note history on in that listing view, but I don't think it makes sense to include all checkout/checkin notes in the assets view. That would confuse more than it would help.

**Comment by docdre721** [comment]
We agree that seeing all the notes would get rather confusing in that space... perhaps the notes field showing the last updated note from either check-in/out or from the update assets page in that space?
