### ISSUE TITLE
DB Migration without upgrading Snipe-it First

### ISSUE THREAD

**Issue by pmd006** [snipe/snipe-it#5309]
#### Expected Behavior (or desired behavior if a feature request)

Want to move DB from 3.6 install to new 4.2 install on a different VM, but no idea how to upgrade the DB without first upgrading the old install which is proving to be a real turd of a process (hence me just propping up a new VM that I installed the new 4.2 on and am trying to restore a backup to).

So I guess what I'm expecting (hoping) is there's a way to a migration/upgrade without first having to upgrade the old install to the latest version (restore from backup from old server to new server and then upgrade database or something along those lines). 

-----

#### Actual Behavior

Oofda, stuff breaks. Lots of dates blank, tables missing columns, etc. Can't even open the Users pages and such. This is probably expected though right? There were changes to the DB that need to be applied before this would be expected to work.

-----

#### Please confirm you have done the following before posting your bug report:

- [  No ] I have enabled debug mode 
- [ Yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Both?
- Version of Snipe-IT you're running
3.6.x on the old server, latest  4.2 on new server.
- Version of PHP you're running
PHP 7.0.28
- Version of MySQL/MariaDB you're running
mysql 5.7.21

- What OS and web server you're running Snipe-IT on
ubuntu server 16.04.1

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Old install I think i used the install.sh script (dude it was over a year ago, it may as well have been a different person that did it) and for the latest I followed the tutorial in the readme.io.

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Eh, User pages won't work, that's for sure one. Dates of asset changes also don't show. I mean, I'm confident its because the old DB needs to be upgraded.

- If a stacktrace is provided in the error, include that too.

- Any errors that appear in your browser's error console.

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
I'd probably have to upload an old blank DB somehow and lets be real that's probably not something anyone logically would have tested.

- Include any additional information you can find in `storage/logs` and your webserver's logs.

- Include what you've done so far in the installation, and if you got any error messages along the way.
Install went fine. Only issue with 4.2 came up during pre-flight but I think its a known bug.

- Indicate whether or not you've manually edited any data directly in the database
Nope. 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I don’t think you want to upgrade the DB without upgrading the install. First of all, that’s not really possible, since the database upgrade stuff is in the code itself (therefore if you moved to another 3.6 version, there would be nothing to upgrade) but also because that would break things, since the database and the code wouldn’t match up anymore.

I think you’ve overthinking this a bit. Export your old database. Get your new 4.2 VM setup with the new 4.2 code, import the database and run migrations. If you’re getting specific errors, we can try to address them, but upgrading from 3.x to 4.x is well documented and isn’t that much of a hassle.

**Comment by snipe** [comment]
This might help: https://snipe-it.readme.io/v4.2.0/docs/moving-snipe-it

If you're still having trouble, please reply with specific error messages you're seeing. Something a little more detailed than "Eh, User pages won't work, that's for sure one." would be a good place to start.

**Comment by pmd006** [comment]
Ah Perfect!, I didn't notice there was that section of the readme and my searches had turned up nil, I will check that out and do my best! Thanks for the reply and sorry for my late reply, I've been away from email for a bit. 

Thanks again!
