### ISSUE TITLE
Feature Request: Track LDAP account expire

### ISSUE THREAD

**Issue by moritz31** [snipe/snipe-it#5310]
We are currently evaluating snipe-it for use in our house. 
Every user has an ldap account, which expires someday when he leaves, what will happen if the account in the ldap is deleted and there are license left which are assigned to him. Is it possible to keep track of that and notify per mail when the account is expired and the user don't need the software?

**Comment by grimstoner** [comment]
We use a Powershell script to disable the user, move the user to a specified OU, remove all group memberships, add an autoresponder to his Exchange email, and then de-allocate all his assets via https://github.com/snazy2000/SnipeitPS
