### ISSUE TITLE
Bug: Unable to modify Maintenance

### ISSUE THREAD

**Issue by lostmydog** [snipe/snipe-it#5311]
#### Expected Behavior (or desired behavior if a feature request)
Go to any asset that has had maintenance, you will see  that under the "Actions" column it simply states "maintenanceActions". I just added maintenance to an asset for the first time, however I assume that that should probably be a 'delete, edit' button.

View the bug in the demo:
https://demo.snipeitapp.com/hardware/37#maintenances

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running 4.2
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by sysnoo** [comment]
I am with Version v4.2.0 - build 3497   I don't have that issue.
All good Except for maintenance report where there is no asset name or tag (#5151 )

**Comment by lostmydog** [comment]
@sysnoo Do you mean build 3479? I am on build 3479, as is the demo, the bug exists in both. If you click the link i supplied you should see the issue.

![image](https://user-images.githubusercontent.com/33837075/38375913-594b1446-38c5-11e8-8dd0-29cbb04e2a36.png)

**Comment by snipe** [comment]
I believe this is already fixed on master.
