### ISSUE TITLE
Feature Request: See assets assigned to other asset in user assets list

### ISSUE THREAD

**Issue by korio77** [snipe/snipe-it#5312]
Good afternoon,

I have seen that once you assign an asset, to another asset and then the last one to an user, the first one is not present on the user assets list.

A little explanation:

You have one asset that is a sim card, you assign that sim card to a phone, and then the phone to an user.

If you go to the user assets list, you can see the phone, but not the sim, you have to go to the phone asset list to be able to see the sim.

I think this can be very useful if you need for example all the stuff assigned to an user, you go to assets and see every asset assigned to him, you dont need to go to each asset and check if each one has assets assigned to them.

i hope i have explained myself properly, i think this should be applied for everything (components, licenses etc etc).

Regards.

P.D: Using the last master of SnipeIT, updated yesterday.

**Comment by JarbyDev** [comment]
I would like to vote for this Feature Request.

**Comment by JarbyDev** [comment]
@snipe Will this Feature Request Implemented on the v5 Release?
