### ISSUE TITLE
Feature Request: Multiple LDAP Server

### ISSUE THREAD

**Issue by meyerf99** [snipe/snipe-it#5315]
Hello,

Is it possible to add more than one ldap address in ldap config?
We have two ldap server and if it's possible we would like to use both for ldap login.

Kind regards,

Flavio

**Comment by snipe** [comment]
Hi Flavio - that's not currently possible, but it's something we've heard requested before. Can you explain your use case to me a little better? What's the reason for two LDAP servers? Are they sub-company-specific or something? We we can understand your use-case, we may be able to implement something like this.

**Comment by meyerf99** [comment]
Hi @snipe - If someone use two active directory ldap servers and one goes down, all login request can be handled with the second ldap server. Other use case is for load balancing all login requests for better and faster handling. It would be great, if you implement this feature in future versions.

Kind regard, 

Flavio

**Comment by colinerd** [comment]
@meyerf99 I take you are talking about DC's in the same forest? Could you not just use the FQDN of your AD as LDAP server address? The FQDN should go to the closest available DC in your domain....

**Comment by hctclyerly** [comment]
I would like to sync different LDAPs as we are not one big forest and we have no trusts between domains, so maybe if instead we could sync a different LDAP per company and each of our sites were created as different companies that would work.

**Comment by meyerf99** [comment]
We will not use LDAP. As a result, I will close the issue.

**Comment by hardxman** [comment]
I used Snipe-IT for multi companies feature. I Would like to sync User from multi LDAP separate companies too.
