### ISSUE TITLE
Bug: Some Assets missing from All Assets view for non Super Admins

### ISSUE THREAD

**Issue by bricelabelle** [snipe/snipe-it#5320]
#### Expected Behavior (or desired behavior if a feature request)

Non Super Admin users should be able to see all assets on the All Assets view.

-----

#### Actual Behavior

Non Super Admin users are missing seemingly random assets from their All Assets view as well as filtered views. Turning off Full Multiple Companies support allows things to function normally. None of the assets missing have a company assigned so turning on the Full Multiple Companies feature shouldn't have any effect on what the majority of our users can see, yet somehow it does. 

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running 
v4.1.14 build 3446 (g90bff709a)

- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Check and make sure the users themselves don't have a company set.

**Comment by bricelabelle** [comment]
Snipe, thanks for the quick reply! The users in question do not have a company set.

**Comment by bricelabelle** [comment]
@snipe , this issue is still present in v4.6.6. When full multiple companies support is turned on, users that aren't admins don't see some assets on the all assets page or other pages listing multiple assets. They can still browse to them if they enter the asset tag in the "lookup by asset tag" box.

**Comment by bricelabelle** [comment]
I also just tested on version 4.6.16 and the issue is still there for me.
