### ISSUE TITLE
Update User Information from LDAP

### ISSUE THREAD

**Issue by meyerf99** [snipe/snipe-it#5328]
Hello @snipe 

We have 300 imported LDAP AD users and want to update all users with some more informations.
- Company
- Language
- Manager
- Department
- Location

Is it possible to update all users with one .csv file?

Kind regards,

Flavio

**Comment by pompushko** [comment]
snazy2000 , could you share your script?

**Comment by meyerf99** [comment]
@snazy2000 Please see his GitHub Repository: https://github.com/snazy2000/SnipeitPS

**Comment by DokH** [comment]
Steven,
I tried to 'Install-Module SnipeitPS' on a PS 5.1 Windows Server 2012 R2, but PS complained that Get-Location already exists.
It is already part of this: Microsoft.PowerShell.Management.
How can I get around this?

**Comment by snipe** [comment]
@DokH Please ask your question on the SnipeITPS Github issues, as it's a separate project.
