### ISSUE TITLE
List view not returning to full size after removing filter

### ISSUE THREAD

**Issue by colinerd** [snipe/snipe-it#5330]
#### Expected Behavior (or desired behavior if a feature request)

When you open the "all assets" list view, you can apply a filter, like an asset tag number.
It will show the results and adjusts the size of the list accordingly. If you remove the filter - it should readjust the size of the list again.

-----

#### Actual Behavior

After applying the filter, the size of the list does not change accordingly unless you refresh the entire page.
*attached screenshot of removing a filter that just showed 1 item....
![screen not full size after filtering](https://user-images.githubusercontent.com/15741333/38520734-e929736a-3c43-11e8-91a8-548858e06988.PNG)

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh Install (git)
- Version of Snipe-IT you're running (4.2.0)
- Version of PHP you're running (7.1.7)
- Version of MySQL/MariaDB you're running (10.1)
- What OS and web server you're running Snipe-IT on (Server 2016 - IIS 10)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) (git)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error (There is no error)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error (demo: https://demo.snipeitapp.com/hardware)
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. (Yes)
- Indicate whether or not you've manually edited any data directly in the database (No)

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I can't reproduce this in Safari/Chrome- what browser are you using? 

![screenflow-chrome](https://user-images.githubusercontent.com/197404/38528784-e87cf104-3c15-11e8-8ab8-d04a8cfe91f8.gif)

**Comment by Raj22223** [comment]
It happens to me too, to avoid this I need to refresh the page again. I am using chrome browser

**Comment by 5quirrel** [comment]
This only happens to me if the filter still has a value in it before I open the page. If I open an asset page with the filter field empty or empty it and refresh it behaves like your GIF @snipe.

I can also reproduce this on both my local instance and demo.

Chrome Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by colinerd** [comment]
@snipe I am using Firefox 60.0 but am seeing this in Chrome as well.
Created a gif to show;

![snipeit-listview-issue](https://user-images.githubusercontent.com/15741333/38545483-748365f4-3caa-11e8-9852-8e60e6e658e9.gif)

**Comment by leebaggaley** [comment]
Agree With 5quirrel & colinerd above, i've just got used to doing an F5 refresh when navigating between pages so no biggie but would be good to have a fix :)

**Comment by scraane** [comment]
I have the same issue. Using Chrome and Snipe 4.4.1

**Comment by snipe** [comment]
I can't fix it if I can't reproduce it though. What version of Chrome are you using?

**Comment by 5quirrel** [comment]
I'm not seeing it anymore.

I have since updated both Chrome to Version 67.0.3396.62 and Snipe-IT to v4.4.1

List now returns to full length after clearing old value, where as previously it behaved exactly like @colinerd 's gif.

**Comment by scraane** [comment]
Using Chrome 66.0.3359.181

**Comment by colinerd** [comment]
Still have the issue on Firefox 61.0 64-bit with Snipe-IT 4.4.1 build 3636
