### ISSUE TITLE
Missing Asset Models after upgrade to v4.2.0

### ISSUE THREAD

**Issue by drumgod** [snipe/snipe-it#5331]
#### Expected Behavior (or desired behavior if a feature request)

Before upgrading i was able to view all the asset models in the /models page. I upgraded to version 4.2.0 and now all my asset models are gone. 

Navigating to the asset models view should show me the models i have configured before the upgrade. I can manually view the data in the database. See attached screen shots.
![website](https://user-images.githubusercontent.com/36162901/38521270-2ebdb656-3c13-11e8-88f3-a1e148269281.png)
![database](https://user-images.githubusercontent.com/36162901/38521283-3a73f622-3c13-11e8-924a-60740c6d6c69.png)

-----

#### Actual Behavior

No data is displayed; however i can manually see the data in the marhia 10.2.7 SQL database.

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running 4.2.0
- Version of PHP you're running 7
- Version of MySQL/MariaDB you're running 10.2.
- What OS and web server you're running Snipe-IT on Windows 2008
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) GIT
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error; no error is displayed
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error. /models

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. Yes;
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data[Learn More]

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database; No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
All of those category id and manufacturer ids are correct, right? They map to existing categories and manufacturers?

Please provide a stack trace from your `storage/logs/laravel.log`

**Comment by snipe** [comment]
> Next Doctrine\DBAL\Driver\PDOException: could not find driver in C:\inetpub\wwwroot\snipe-it-4.1.9\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:47

That usually means MySQL isn't running. Is that error recent? Do you see it added again when you load that page?

What browser are you using? Does this issue happen in a different browser? Have you tried disabling your browser extensions to confirm that there's not a conflict somewhere?

**Comment by drumgod** [comment]
That error appeared during my upgrade; i was able to fix it and move forward with the update. 

Ive tried Chrome/IE/Firefox on multiple machines. 

I have noticed this output in my php error logs:
[11-Apr-2018 14:31:22 UTC] PHP Warning:  Module 'gd' already loaded in Unknown on line 0
[11-Apr-2018 14:31:22 UTC] PHP Warning:  Module 'mysqli' already loaded in Unknown on line 0
[11-Apr-2018 14:31:31 UTC] PHP Warning:  Module 'gd' already loaded in Unknown on line 0
[11-Apr-2018 14:31:31 UTC] PHP Warning:  Module 'mysqli' already loaded in Unknown on line 0

Does this help at all?

**Comment by drumgod** [comment]
Some errors are appearing in my console when i enable debuging on firefox (ctrl+shift+K):


GET
http://inventory.future.com/models
[HTTP/1.1 200 OK 359ms]
GET
http://inventory.future.com/js/plugins/select2/select2.min.css
[HTTP/1.1 304 Not Modified 0ms]
GET
http://inventory.future.com/js/plugins/iCheck/all.css
[HTTP/1.1 304 Not Modified 0ms]
GET
http://inventory.future.com/css/bootstrap-table.css
[HTTP/1.1 304 Not Modified 0ms]
GET
http://inventory.future.com/css/dist/all.css
[HTTP/1.1 304 Not Modified 0ms]
GET
http://inventory.future.com/js/dist/all.js
[HTTP/1.1 304 Not Modified 0ms]
GET
http://inventory.future.com/js/bootstrap-table.min.js
[HTTP/1.1 304 Not Modified 0ms]
GET
http://inventory.future.com/js/extensions/mobile/bootstrap-table-mobile.js
[HTTP/1.1 304 Not Modified 0ms]
GET
http://inventory.future.com/js/extensions/export/bootstrap-table-export.js
[HTTP/1.1 304 Not Modified 15ms]
GET
http://inventory.future.com/js/extensions/export/jquery.base64.js
[HTTP/1.1 304 Not Modified 0ms]
GET
http://inventory.future.com/js/FileSaver.min.js
[HTTP/1.1 304 Not Modified 0ms]
GET
http://inventory.future.com/js/xlsx.core.min.js
[HTTP/1.1 304 Not Modified 0ms]
GET
http://inventory.future.com/js/jspdf.min.js
[HTTP/1.1 304 Not Modified 0ms]
GET
http://inventory.future.com/js/jspdf.plugin.autotable.js
[HTTP/1.1 304 Not Modified 0ms]
GET
http://inventory.future.com/js/extensions/export/tableExport.min.js
[HTTP/1.1 304 Not Modified 0ms]
GET
http://inventory.future.com/js/extensions/toolbar/bootstrap-table-toolbar.js
[HTTP/1.1 304 Not Modified 0ms]
GET
http://inventory.future.com/js/extensions/sticky-header/bootstrap-table-sticky-header.js
[HTTP/1.1 304 Not Modified 0ms]
GET
http://inventory.future.com/js/extensions/cookie/bootstrap-table-cookie.js
[HTTP/1.1 304 Not Modified 0ms]
Unknown property ‘user-select’.  Declaration dropped.
select2.min.css:1:234
Unknown property ‘user-select’.  Declaration dropped.
select2.min.css:1:699
Unknown pseudo-class or pseudo-element ‘-webkit-search-cancel-button’.  Ruleset ignored due to bad selector.
select2.min.css:1:1156
Unknown property ‘user-select’.  Declaration dropped.
select2.min.css:1:1529
Unknown pseudo-class or pseudo-element ‘-webkit-search-cancel-button’.  Ruleset ignored due to bad selector.
select2.min.css:1:2109
Expected ‘none’, URL, or filter function but found ‘alpha(’.  Error in parsing value for ‘filter’.  Declaration dropped.
select2.min.css:1:2419
Error in parsing value for ‘background-image’.  Declaration dropped.
select2.min.css:1:8692
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.
select2.min.css:1:8848
Error in parsing value for ‘background-image’.  Declaration dropped.
select2.min.css:1:9749
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.
select2.min.css:1:9905
Error in parsing value for ‘background-image’.  Declaration dropped.
select2.min.css:1:11306
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.
select2.min.css:1:11458
Error in parsing value for ‘background-image’.  Declaration dropped.
select2.min.css:1:11836
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.
select2.min.css:1:11992
Unknown property ‘-moz-border-radius’.  Declaration dropped.
bootstrap-table.css:34:24
Unknown property ‘-moz-border-radius-topleft’.  Declaration dropped.
bootstrap-table.css:71:32
Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped.
all.css:1:140
Unknown pseudo-class or pseudo-element ‘-webkit-inner-spin-button’.  Ruleset ignored due to bad selector.
all.css:1:1470
Unknown pseudo-class or pseudo-element ‘-webkit-search-cancel-button’.  Ruleset ignored due to bad selector.
all.css:1:1676
Unknown property ‘orphans’.  Declaration dropped.
all.css:1:2565
Unknown property ‘widows’.  Declaration dropped.
all.css:1:2574
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped.
all.css:1:3783
Error in parsing value for ‘outline’.  Declaration dropped.
all.css:1:15547
Error in parsing value for ‘outline’.  Declaration dropped.
all.css:1:35452
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector.
all.css:1:36524
Unknown pseudo-class or pseudo-element ‘-webkit-input-placeholder’.  Ruleset ignored due to bad selector.
all.css:1:36571
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
all.css:1:36837
Unknown property ‘user-select’.  Declaration dropped.
all.css:1:44688
Error in parsing value for ‘outline’.  Declaration dropped.
all.css:1:44823
Unknown property ‘zoom’.  Declaration dropped.
all.css:1:83731
Expected media feature name but found ‘transform-3d’.
all.css:1:105114
Error in parsing value for ‘-webkit-perspective’.  Declaration dropped.
all.css:1:105438
Error in parsing value for ‘perspective’.  Declaration dropped.
all.css:1:105455
Unrecognized at-rule or error parsing at-rule ‘@-ms-viewport’.
all.css:1:110190
Error in parsing value for ‘display’.  Declaration dropped.
all.css:1:113317
Error in parsing value for ‘display’.  Declaration dropped.
all.css:1:113894
Error in parsing value for ‘display’.  Declaration dropped.
all.css:1:114802
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped.
all.css:15:144
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector.
all.css:15:3426
Unknown pseudo-class or pseudo-element ‘-webkit-input-placeholder’.  Ruleset ignored due to bad selector.
all.css:15:3506
Unknown pseudo-class or pseudo-element ‘-ms-input-placeholder’.  Ruleset ignored due to bad selector.
all.css:15:24567
Unknown property ‘appearance’.  Declaration dropped.
all.css:15:24765
Error in parsing value for ‘z-index’.  Declaration dropped.
all.css:15:29091
Unknown property ‘user-select’.  Declaration dropped.
all.css:15:47028
Error in parsing value for ‘background’.  Declaration dropped.
all.css:15:54041
Error in parsing value for ‘background’.  Declaration dropped.
all.css:15:54162
Error in parsing value for ‘background’.  Declaration dropped.
all.css:15:54277
Error in parsing value for ‘background’.  Declaration dropped.
all.css:15:54392
Error in parsing value for ‘background’.  Declaration dropped.
all.css:15:54509
Error in parsing value for ‘background’.  Declaration dropped.
all.css:15:54626
Error in parsing value for ‘background’.  Declaration dropped.
all.css:15:54742
Error in parsing value for ‘background’.  Declaration dropped.
all.css:15:54856
Error in parsing value for ‘background’.  Declaration dropped.
all.css:15:54969
Error in parsing value for ‘background’.  Declaration dropped.
all.css:15:55083
Expected color but found ‘none’.  Error in parsing value for ‘background-color’.  Declaration dropped.
all.css:15:60513
Unknown property ‘-moz-osx-font-smoothing’.  Declaration dropped.
all.css:18:645
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
all.css:18:31189
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
all.css:18:31221
Unknown property ‘-moz-border-radius’.  Declaration dropped.
all.css:22:73
Unknown property ‘user-select’.  Declaration dropped.
all.css:22:1431
Unknown property ‘-moz-border-radius’.  Declaration dropped.
all.css:22:1552
Error in parsing value for ‘background-image’.  Declaration dropped.
all.css:22:2302
Error in parsing value for ‘background-image’.  Declaration dropped.
all.css:22:2445
Error in parsing value for ‘background-image’.  Declaration dropped.
all.css:22:2513
Unknown property ‘-moz-border-radius’.  Declaration dropped.
all.css:22:4000
Error in parsing value for ‘background-image’.  Declaration dropped.
all.css:22:4299
Error in parsing value for ‘background-image’.  Declaration dropped.
all.css:22:4442
Error in parsing value for ‘background-image’.  Declaration dropped.
all.css:22:4510
Unknown property ‘-moz-border-radius’.  Declaration dropped.
all.css:22:4782
Error in parsing value for ‘background-image’.  Declaration dropped.
all.css:22:6117
Error in parsing value for ‘background-image’.  Declaration dropped.
all.css:22:6254
Error in parsing value for ‘background-image’.  Declaration dropped.
all.css:22:6319
Error in parsing value for ‘background-image’.  Declaration dropped.
all.css:22:7827
Error in parsing value for ‘background-image’.  Declaration dropped.
all.css:22:7958
Error in parsing value for ‘background-image’.  Declaration dropped.
all.css:22:8020
Unknown property ‘-moz-border-radius’.  Declaration dropped.
all.css:22:9390
Error in parsing value for ‘background-image’.  Declaration dropped.
all.css:22:9898
Error in parsing value for ‘background-image’.  Declaration dropped.
all.css:22:10029
Error in parsing value for ‘background-image’.  Declaration dropped.
all.css:22:10091
Unknown property ‘-moz-border-radius’.  Declaration dropped.
all.css:22:12184
Unknown property ‘-moz-border-radius’.  Declaration dropped.
all.css:22:12309
Unknown property ‘-moz-border-radius’.  Declaration dropped.
all.css:22:12874
Unknown property ‘-moz-box-shadow’.  Declaration dropped.
all.css:22:12957
Unknown property ‘-moz-background-clip’.  Declaration dropped.
all.css:22:13077
GET
http://inventory.future.com/js/plugins/iCheck/minimal/_all.css
[HTTP/1.1 304 Not Modified 1ms]
GET
http://inventory.future.com/js/plugins/iCheck/square/_all.css
[HTTP/1.1 304 Not Modified 1ms]
GET
http://inventory.future.com/js/plugins/iCheck/flat/_all.css
[HTTP/1.1 304 Not Modified 2ms]
GET
http://inventory.future.com/js/plugins/iCheck/line/_all.css
[HTTP/1.1 304 Not Modified 2ms]
GET
http://inventory.future.com/js/plugins/iCheck/polaris/polaris.css
[HTTP/1.1 304 Not Modified 1ms]
GET
http://inventory.future.com/js/plugins/iCheck/futurico/futurico.css
[HTTP/1.1 304 Not Modified 1ms]
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:5:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:51:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:52:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:53:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:54:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:67:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:113:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:114:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:115:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:116:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:129:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:175:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:176:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:177:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:178:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:191:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:237:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:238:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:239:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:240:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:253:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:299:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:300:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:301:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:302:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:315:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:361:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:362:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:363:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:364:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:377:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:423:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:424:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:425:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:426:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:439:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:485:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:486:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:487:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:488:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:501:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:547:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:548:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:549:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:550:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:6:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:52:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:53:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:54:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:55:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:68:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:114:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:115:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:116:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:117:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:130:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:176:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:177:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:178:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:179:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:192:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:238:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:239:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:240:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:241:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:254:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:300:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:301:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:302:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:303:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:316:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:362:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:363:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:364:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:365:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:378:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:424:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:425:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:426:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:427:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:440:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:486:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:487:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:488:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:489:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:502:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:548:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:549:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:550:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:551:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:564:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:610:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:611:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:612:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:613:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:6:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:46:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:47:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:48:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:49:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:62:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:102:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:103:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:104:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:105:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:118:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:158:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:159:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:160:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:161:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:174:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:214:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:215:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:216:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:217:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:230:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:270:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:271:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:272:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:273:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:286:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:326:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:327:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:328:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:329:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:342:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:382:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:383:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:384:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:385:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:398:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:438:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:439:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:440:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:441:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:454:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:494:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:495:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:496:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:497:25
Expected declaration but found ‘*’.  Skipped to next declaration.
_all.css:510:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:550:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:551:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:552:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:553:25
Unknown property ‘-moz-border-radius’.  Declaration dropped.
_all.css:15:24
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:64:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:65:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:66:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:67:25
Unknown property ‘-moz-border-radius’.  Declaration dropped.
_all.css:89:24
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:138:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:139:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:140:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:141:25
Unknown property ‘-moz-border-radius’.  Declaration dropped.
_all.css:163:24
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:212:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:213:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:214:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:215:25
Unknown property ‘-moz-border-radius’.  Declaration dropped.
_all.css:237:24
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:286:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:287:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:288:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:289:25
Unknown property ‘-moz-border-radius’.  Declaration dropped.
_all.css:311:24
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:360:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:361:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:362:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:363:25
Unknown property ‘-moz-border-radius’.  Declaration dropped.
_all.css:385:24
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:434:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:435:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:436:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:437:25
Unknown property ‘-moz-border-radius’.  Declaration dropped.
_all.css:459:24
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:508:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:509:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:510:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:511:25
Unknown property ‘-moz-border-radius’.  Declaration dropped.
_all.css:533:24
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:582:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:583:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:584:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:585:25
Unknown property ‘-moz-border-radius’.  Declaration dropped.
_all.css:607:24
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:656:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:657:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:658:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:659:25
Unknown property ‘-moz-border-radius’.  Declaration dropped.
_all.css:681:24
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
_all.css:730:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
_all.css:731:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
_all.css:732:25
Expected media feature name but found ‘min-device-pixel-ratio’.
_all.css:733:25
Expected declaration but found ‘*’.  Skipped to next declaration.
futurico.css:6:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
futurico.css:46:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
futurico.css:47:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
futurico.css:48:25
Expected media feature name but found ‘min-device-pixel-ratio’.
futurico.css:49:25
Expected declaration but found ‘*’.  Skipped to next declaration.
polaris.css:6:5
Expected media feature name but found ‘-webkit-min-device-pixel-ratio’.
polaris.css:52:25
Expected media feature name but found ‘-moz-min-device-pixel-ratio’.
polaris.css:53:25
Expected media feature name but found ‘-o-min-device-pixel-ratio’.
polaris.css:54:25
Expected media feature name but found ‘min-device-pixel-ratio’.
polaris.css:55:25
jQuery.Deferred exception: JSON.parse: unexpected character at line 1 column 1 of the JSON data BootstrapTable.prototype.initCookie@http://inventory.future.com/js/extensions/cookie/bootstrap-table-cookie.js?v=1:313:29
BootstrapTable.prototype.initTable@http://inventory.future.com/js/extensions/cookie/bootstrap-table-cookie.js?v=1:295:9
o.prototype.init@http://inventory.future.com/js/bootstrap-table.min.js:7:7451
BootstrapTable.prototype.init@http://inventory.future.com/js/extensions/mobile/bootstrap-table-mobile.js:91:9
BootstrapTable.prototype.init@http://inventory.future.com/js/extensions/cookie/bootstrap-table-cookie.js?v=1:279:9
o@http://inventory.future.com/js/bootstrap-table.min.js:7:2730
a.fn.bootstrapTable/<@http://inventory.future.com/js/bootstrap-table.min.js:8:22036
each@http://inventory.future.com/js/dist/all.js?id=6769a7c5085ca8147451:1:26098
each@http://inventory.future.com/js/dist/all.js?id=6769a7c5085ca8147451:1:24365
a.fn.bootstrapTable@http://inventory.future.com/js/bootstrap-table.min.js:8:21727
@http://inventory.future.com/models:810:9
c@http://inventory.future.com/js/dist/all.js?id=6769a7c5085ca8147451:2:20896
o/</d<@http://inventory.future.com/js/dist/all.js?id=6769a7c5085ca8147451:2:21212
 undefined
all.js:2:22491
Error in parsing value for ‘height’.  Declaration dropped.
models
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data[Learn More]
bootstrap-table-cookie.js:313:29
GET
http://inventory.future.com/uploads/logo.jpg
[HTTP/1.1 304 Not Modified 1ms]
GET
http://gravatar.com/avatar/6a9b00b3f68ce70c2742a260e8e317fd
[HTTP/1.1 304 Not Modified 125ms]

**Comment by snipe** [comment]
What specific version of PHP7 are you running?

**Comment by drumgod** [comment]
7.1.9

**Comment by drumgod** [comment]
I have decided just to go back to my old version.

**Comment by lbellamy** [comment]
I have the same problem with basically the same settings.
I can see every this listed under all assets, but when I look at just categories or just asset models there is nothing. Even though the data is listed in List All
