### ISSUE TITLE
Confused about location and default location

### ISSUE THREAD

**Issue by Crunky** [snipe/snipe-it#5333]
Hi,

i am a bit confused about location and default location.

If i create a new asset i set the location, everything is fine. Now i change the location afterwards and the "old" value still appears in the overview. In asset details i now see both locations ... why and how to handle this correctly to change first set location afterwards?

Thanks
Marco

**Comment by kiplandiles** [comment]
This is confusing to me as well. I'm using SnipeIT Cloud and from reading other posts related to this question it appears that the Location is determined by the location of the user it is checked out to. This is not always ideal since I wanted to check out an asset to a user that works in the office but that will be taking this asset home (temporary usage of a laptop). In this case I wanted to set the Location to Remote but could not. I can only change the Default Location which is here at the office.

**Comment by JayRad11** [comment]
I too am having this same issue. I can create a new asset, and set it's location through the "default location" drop down select, which saves successfully to the assets record. However, if I try to change an existing asset's location, the change made is not saved.

**Comment by n-v-o** [comment]
@kiplandiles I've ran into the same situation. I have a few users who have assets in multiple locations, but have a primary office. Basically, if an asset is checked out to a user who has the location information filled out, the asset will be set to the user's location. If the user doesn't have a location field filled out. I've noticed it will resolve to the "default location". 
#2196 and #3899 touch base on functionality that may be useful, the ability to override an assets location vbia an optional location field during checkout.

**Comment by kgortmak** [comment]
Yes, this still is an issue. I just noticed that the asset overview, when typing location information in the search field, actually lists the assets filtered on the DEFAULT location, and NOT (which makes more sense) filtered on the actual Location. This is not logical. I would consider it being a bug.

**Comment by sdecaux** [comment]
Yes I find it confusing too. When we check out an asset, located in "stock" to an user, the "default location" neither "location" is changed. to have correct location (= the office of the user), we have then to edit the asset and change the "default location" field.

**Comment by AL4AL** [comment]
This thread be continued in https://github.com/snipe/snipe-it/issues/2196
