### ISSUE TITLE
metric system everywhere

### ISSUE THREAD

**Issue by harcesz** [snipe/snipe-it#5334]
for deeper localization, it would be nice to have all units adjusted to local standards; the label generator seems to be hardcoded to inches, and conversions of DPI/pixels/centimeters -> inches are a bit of a pain. 

also: metric FTW!

**Comment by harcesz** [comment]
anybody interested in doing this as paid work? how much should the bounty be?

**Comment by kale1d0code** [comment]
Being able to use the correct unit of measurement would be very valuable for our organisation or any I'd imagine.
Takes a very long time to convert and to get right.
