### ISSUE TITLE
image cloning

### ISSUE THREAD

**Issue by harcesz** [snipe/snipe-it#5335]
assets are cloned including picture, but it disappears on save. there doesn't seem to be a way to recycle an earlier upload, so I need to reupload the same picture a number of times

Snipe-IT version | v4.1.14  build 3408 (ga705c71)
-- | --
Software License | AGPL3
PHP Version | 7.0.25-0ubuntu0.16.04.1
Laravel Version | 5.4.35

**Comment by therealjoshuad** [comment]
What kind of “model” are you using? We have a “model” for each actual laptop model, and an associated picture. When we create an asset that is derived from that model, the picture is inherited from the model.

If you’re not using models with a generic, “laptop” model, then add your photo to that model, and you should refer the desired effect.

**Comment by therealjoshuad** [comment]
Should receive the desired effect**

**Comment by snipe** [comment]
This isn't really a bug, honestly. The alternative here would be to physically copy the image each time, which doesn't seem like it makes a lot of sense. You would have hundreds of the same image taking up space on your hard drive. 

@therealjoshuad is correct here - the better way to do it would be to set the image as your model image. If a model image is found, it will use that. If there is an asset-specific image, that will override the model image.

**Comment by chelmoski** [comment]
@snipe I have a question about this. I've set up an asset model which contains our financial definitions (Location ID and Department ID) as we are a non-profit and need to report on how much each department is worth. Using an asset model is the only way I can see to accomplish this and have our reports easy to sort. Is manually uploading the image on each asset clone the best way to have pictures for each asset?
