### ISSUE TITLE
[Feature Request] Mark required fields on setup

### ISSUE THREAD

**Issue by Matthewrbowker** [snipe/snipe-it#5338]
#### Expected Behavior (or desired behavior if a feature request)

I've had to set up Snipe-IT 3 times so far (different development machines, because reasons).  Every time, I forget required fields on the "Create a User" screen in the setup process.  It would be wonderful if the required fields were marked, either with a * or the right-side orange bar.  

-----

#### Actual Behavior

Required fields are not marked visually.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - Fresh install
- Version of Snipe-IT you're running - 4.2
- Version of PHP you're running - 7.1.7 CLI
- Version of MySQL/MariaDB you're running - N/A
- What OS and web server you're running Snipe-IT on - Reproduced on MacOS 10.13, Windows 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual instalation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - No error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - "/setup/user," clicking "submit" if a required element is forgotten
- If a stacktrace is provided in the error, include that too. - N/A
- Any errors that appear in your browser's error console. - N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - Cannot confirm, demo is already installed.
- Include any additional information you can find in `storage/logs` and your webserver's logs. - Just a whole bunch of 200 return codes :)
- Include what you've done so far in the installation, and if you got any error messages along the way. - I've had to install manually using "php artisan migrate" due to a migration error - I will file a separate issue when I finish gathering notes on reproduction.  
- Indicate whether or not you've manually edited any data directly in the database - There's no data added in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
That's a pretty fair request :)
