### ISSUE TITLE
500 Server Error after fresh install

### ISSUE THREAD

**Issue by pn-taylor** [snipe/snipe-it#5341]
After installing Snipe-it on a new install of CentOS7 I download the master install.sh and run. After completion I navigate to the URL specific to be greeted by a 500 Internal Server Error rather than the pre-flight checks.

After investigating the httpd logs I noticed one was due to the source files for Psy was missing. I downloaded, copied and chown for apache and tried again only to have the same issue. The logs, however, are serving up a new error:

[Wed Apr 11 19:01:19.617572 2018] [php7:error] [pid 54925] [client 192.168.16.104:13006] PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/html/snipeit/app/Exceptions/Handler.php:39\nStack trace:\n#0 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Dotenv\\Exception\\InvalidFileException))\n#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Dotenv\\Exception\\InvalidFileException))\n#2 /var/www/html/snipeit/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))\n#3 {main}\n  thrown in /var/www/html/snipeit/app/Exceptions/Handler.php on line 39

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh Install
- Version of Snipe-IT you're running: latest
- Version of PHP you're running 7
- Version of MySQL/MariaDB you're running: 5.5.56
- What OS and web server you're running Snipe-IT on: CentOS 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): install.sh

Below is the output from httpd/error_log after restarting httpd post copying the psy files across:

`[Wed Apr 11 19:00:11.432866 2018] [mpm_prefork:notice] [pid 54892] AH00170: caught SIGWINCH, shutting down gracefully
[Wed Apr 11 19:00:12.472203 2018] [core:notice] [pid 54923] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Wed Apr 11 19:00:12.472675 2018] [suexec:notice] [pid 54923] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using inventory.wildbear.tv. Set the 'ServerName' directive globally to suppress this message
[Wed Apr 11 19:00:12.485777 2018] [auth_digest:notice] [pid 54923] AH01757: generating secret for digest authentication ...
[Wed Apr 11 19:00:12.486209 2018] [lbmethod_heartbeat:notice] [pid 54923] AH02282: No slotmem from mod_heartmonitor
[Wed Apr 11 19:00:12.499051 2018] [mpm_prefork:notice] [pid 54923] AH00163: Apache/2.4.6 (CentOS) PHP/7.1.15 configured -- resuming normal operations
[Wed Apr 11 19:00:12.499072 2018] [core:notice] [pid 54923] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Apr 11 19:00:18.590796 2018] [php7:error] [pid 54927] [client 192.168.16.104:12987] PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/html/snipeit/app/Exceptions/Handler.php:39\nStack trace:\n#0 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Dotenv\\Exception\\InvalidFileException))\n#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Dotenv\\Exception\\InvalidFileException))\n#2 /var/www/html/snipeit/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))\n#3 {main}\n  thrown in /var/www/html/snipeit/app/Exceptions/Handler.php on line 39
[Wed Apr 11 19:00:19.876965 2018] [php7:error] [pid 54928] [client 192.168.16.104:12988] PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/html/snipeit/app/Exceptions/Handler.php:39\nStack trace:\n#0 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Dotenv\\Exception\\InvalidFileException))\n#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Dotenv\\Exception\\InvalidFileException))\n#2 /var/www/html/snipeit/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))\n#3 {main}\n  thrown in /var/www/html/snipeit/app/Exceptions/Handler.php on line 39
[Wed Apr 11 19:01:19.617572 2018] [php7:error] [pid 54925] [client 192.168.16.104:13006] PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/html/snipeit/app/Exceptions/Handler.php:39\nStack trace:\n#0 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Dotenv\\Exception\\InvalidFileException))\n#1 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Dotenv\\Exception\\InvalidFileException))\n#2 /var/www/html/snipeit/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))\n#3 {main}\n  thrown in /var/www/html/snipeit/app/Exceptions/Handler.php on line 39
`

**Comment by snipe** [comment]
Did you try the solutions listed here? 
https://snipe-it.readme.io/docs/installation-issues#section-fatal-error-uncaught-exception-reflectionexception-with-message-class-log-does-not-exist

**Comment by pn-taylor** [comment]
Here's the stack trace when trying to edit an asset:


(3/3) QueryExceptionSQLSTATE[42S22]: Column not found: 1054 Unknown column 'default_label' in 'order clause' (SQL: select `name`, `id` from `status_labels` where `status_labels`.`deleted_at` is null order by `default_label` desc, `name` asc, `deployable` desc)
--
in Connection.php (line 647)
at Connection->runQueryCallback('select `name`, `id` from `status_labels` where `status_labels`.`deleted_at` is null order by `default_label` desc, `name` asc, `deployable` desc', array(), object(Closure))in Connection.php (line 607)
at Connection->run('select `name`, `id` from `status_labels` where `status_labels`.`deleted_at` is null order by `default_label` desc, `name` asc, `deployable` desc', array(), object(Closure))in Connection.php (line 326)
at Connection->select('select `name`, `id` from `status_labels` where `status_labels`.`deleted_at` is null order by `default_label` desc, `name` asc, `deployable` desc', array(), true)in Builder.php (line 1705)
at Builder->runSelect()in Builder.php (line 1690)
at Builder->get(array('name', 'id'))in Builder.php (line 1888)
at Builder->pluck('name', 'id')in Builder.php (line 656)
at Builder->pluck('name', 'id')in Helper.php (line 239)
at Helper::statusLabelList()in AssetsController.php (line 266)
at AssetsController->edit('110')
at call_user_func_array(array(object(AssetsController), 'edit'), array('hardware' => '110'))in Controller.php (line 55)
at Controller->callAction('edit', array('hardware' => '110'))in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(AssetsController), 'edit')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 572)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php (line 43)
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php (line 49)
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php (line 49)
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php (line 42)
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 574)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 533)
at Router->dispatchToRoute(object(Request))in Router.php (line 511)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php (line 51)
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php (line 25)
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php (line 56)
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php (line 27)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

**Comment by DutchCloud4Work** [comment]
I have the exact same error after a fresh installation on a debian server.

    Is this a fresh install or an upgrade? Fresh Install
    Version of Snipe-IT you're running: latest
    Version of PHP you're running 7
    Version of MySQL/MariaDB you're running: Server version: 10.1.26-MariaDB-0+deb9u1
    What OS and web server you're running Snipe-IT on: Debian 9.4
    What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): install.sh

[Thu Apr 12 11:19:17.840481 2018] [:error] [pid 1374] [client 172.16.10.114:61935] PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/snipeit/app/Exceptions/Handler.php:39\nStack trace:\n#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(314): App\\Exceptions\\Handler->report(Object(Dotenv\\Exception\\InvalidFileException))\n#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(Dotenv\\Exception\\InvalidFileException))\n#2 /var/www/snipeit/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))\n#3 {main}\n  thrown in /var/www/snipeit/app/Exceptions/Handler.php on line 39

**Comment by DutchCloud4Work** [comment]
Ok found the error..
When the wizard finishes with the mail settings, I used a space in the MAIL_FROM_NAME & MAIL_REPLYTO_NAME. (Asset Management).
After removing this space in my .ENV file everything works. /var/www/snipeit/.env

**Comment by pn-taylor** [comment]
@DutchCloud4Work I did too, have removed the space but still receiving some epic errors when ediing.

**Comment by pn-taylor** [comment]
Decided to, in the end, install the version that the DB was exported from. I'll upgrade from there and see if we avoid these errors. I'll close this issue as, realistically, I now have a running and stable version.
