### ISSUE TITLE
File attachments size in software license.

### ISSUE THREAD

**Issue by ziyaul121** [snipe/snipe-it#5348]
Whenever I try to upload pdf file more than 2 MB in software license than its throwing error"Error: One or more of your files is too large or is a filetype that is not allowed. Allowed filetypes are png, gif, jpg, jpeg, doc, docx, pdf, txt, zip, rar, rtf, xml, and lic." 

whereas I am able to upload file  upto 10 MB in Assets but not in software license.
I have changed the setting in php.ini  post_max_size = 20M  and upload_max_filesize=10M .

-----

#### Actual Behavior

not able to upload file more than 2 MB in software license. 

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  Fresh
- Version of Snipe-IT you're running Version v4.1.14 
- Version of PHP you're running 7
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by akivacp** [comment]
I changed the following in the php.ini file ( around line 845 ish)
located in /etc/php/7.4/apache2

```
; Maximum allowed size for uploaded files.
; http://php.net/upload-max-filesize
upload_max_filesize = 2M
```

then I ran the command (in my Ubuntu)
`sudo service apache2 restart`
