### ISSUE TITLE
Snipe-it license Error

### ISSUE THREAD

**Issue by scsaus** [snipe/snipe-it#5349]
When i go to license tab and try to create new license.I get the following error.i have followed the license instruction guide for XAMPP on snipe-it website but no avail.Any help will be appreciated.Thanks

**Object not found!
The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error. 
If you think this is a server error, please contact the webmaster. 
Error 404
snipe.local
Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.20**

**Comment by snipe** [comment]
Unfortunately, this is a XAMPP configuration issue, not a Snipe-IT issue, so unless we have some XAMPP users that can assist, I'm not sure what to tell you. I know we do have some folks using XAMPP, but we recommend against it because of some of their built-in defaults that have to be overridden.
