### ISSUE TITLE
ASSET_LOGS Timestamp Not Updating

### ISSUE THREAD

**Issue by dguedry** [snipe/snipe-it#535]
The checkin/checkout timestamps in asset_logs are not being set and are defaulting to '0000-00-00'.  As a work-around, I've changed the created_at field to a TIMESTAMP instead of DATETIME and set the default value to CURRENT_TIMESTAMP.

**Comment by kobie-chasehansen** [comment]
This sounds the same as #499.

What version are you on right now?

**Comment by dguedry** [comment]
You're right.  I didn't see #499... same issue.  I'm using 1.2.3.  Thanks!

**Comment by kobie-chasehansen** [comment]
should be resolved if you upgrade to 1.2.5 (43cdace9de2f717b1550fe0a75e7a4e4987dedfe)
