### ISSUE TITLE
Assigning a license to an asset does not generate new entry in asset history

### ISSUE THREAD

**Issue by duel007** [snipe/snipe-it#5351]
I'm not sure if this would be considered a bug or a feature request, or if this is even a desired feature. I'll leave that up to the reviewer. I just happened to notice this activity while assigning a Windows license to a PC.

#### Expected Behavior (or desired behavior if a feature request)

A new entry in the asset history stating the information (license name, date of assignment, user that assigned it, and any note from the assignment note field) about the license that was assigned. License history is also updated.

-----

#### Actual Behavior

No entry in the asset history is created. The asset is assigned, and the asset activity is noted within the recent items on the homepage.
License assignment history is updated as expected.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh install.
- Version of Snipe-IT you're running - 4.2.0
- Version of PHP you're running - docker image
- Version of MySQL/MariaDB you're running 5.6, docker.
- What OS and web server you're running Snipe-IT on. Ubuntu docker host.
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Docker.
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: serverurl.com/hardware/127#history. (No error is generated)
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: Yes, I am able to reproduce this in the demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database: No.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by duel007** [comment]
This is still happening for me. Thanks.

**Comment by duel007** [comment]
I am still experiencing this issue.

**Comment by snipe** [comment]
Are you still running 4.2.0? Have you tried upgrading?

**Comment by duel007** [comment]
Should have mentioned that, yes I am on 4.6.3 currently.
