### ISSUE TITLE
Trying to connect to MY AD server however im still getting Could not bind to LDAP: Can't contact LDAP server

### ISSUE THREAD

**Issue by wnorales** [snipe/snipe-it#5352]
![capture1](https://user-images.githubusercontent.com/10760389/38704566-c5e0f0a8-3e74-11e8-8ec8-b6ef1003e467.PNG)

**Comment by samotelf** [comment]
I'll share my config:

LDAP Integration  LDAP enabled √
Active Directory  This is an Active Directory server √
LDAP Password Sync  Yes √
Active Directory domain contoso.com
LDAP Server ldap://ipaddressofyourdc:389
Use TLS  NO
Allow invalid SSL Certificate √
LDAP Bind Username ldap.user
LDAP Bind Password password
Base Bind DN dc=contoso,dc=com
LDAP Filter &(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))
Username Field samaccountname
Last Name sn
LDAP First Name givename
LDAP Authentication query samaccountname=
LDAP Version 3
LDAP Email mail

Save
Goto config again
Test below
Profit

**Comment by wnorales** [comment]
@samotelf 
would ldap.user be admin account on the domain controller?  if so still getting the same error message

**Comment by samotelf** [comment]
Nope, a normal user works.

**Comment by rummepa** [comment]
hi,

we are running version: v4.2.0 build 3497 (g590938f)
and we where facing the same issue...

when i use your config @samotelf we need to modify the LDAP Bind Username to domain\username then it works!

**Comment by wnorales** [comment]
@rummepa  IT WORKED !!!!!1
Thanks You

**Comment by samotelf** [comment]
hm, strange, glad it worked out!
happy sniping 👍
