### ISSUE TITLE
Feature Request: See all broken/stolen assets from user john doe when assigning a new/replacement asset 

### ISSUE THREAD

**Issue by samotelf** [snipe/snipe-it#5353]
#### Expected Behavior (or desired behavior if a feature request)

We have a kind of a break one asset credit rule. So, it would be awesome to get some kind of warning when deploying an asset to a user if he already broke one.

(what you expect to happen goes here)

For instance: A user broke an asset (laptop screen/mobile) and they come to IT to replace it, It would be great to somehow get notified that a user broke an asset in the past.

#### Actual Behavior

When deploying the asset I can see at the right the deployed assets for that user

(what actually happens goes here)

I believe that when deploying the asset I can see at the right the deployed assets for that user, but not the broken ones, maybe there's some kind of workflow or asset management that I'm not doing right?
Thank you very much.
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by samotelf** [comment]
Hello Snipe, thank you.... also just to make sure, not also if the user has broken one in the past or if the asset was stolen :)
Thank you.

**Comment by samotelf** [comment]
Hello, commenting because I think this would be an important step towards asset management.
I hope my reply can open the ticket again.
Thank you very much.

**Comment by samotelf** [comment]
Hello Snipe, I was wondering if you have any news on this feature request. V5? (wink:wink)
I've been thinking about it and it would be nice to have a report with lost/broken assets.
Right now I have created these status labels but if the asset returns (repaired/recovered) we have no way of knowing to whom the asset belonged to, unless I go to the asset's history. (AFAIK), which means that if a user broke/lost an asset I would have to check the history of all the assets with these status.
It would be awesome to have some kind of report like the depreciation report or even more awesome with glitter and a unicorn, to have a warning displayed when assigning an asset to a user who already broke/lost/ one in the past (in our case 4 years for laptops and 2 for mobiles) and if so pull the monetary value in the depreciation report to follow up with the user's manager.
Is this feasible? Do you think it will be implemented in the future?
Thank you very much.

**Comment by samotelf** [comment]
Dear Bot, it is still relevant :)
Please make this a upcoming feature.
As I mentioned earlier it would be nice to have a record of all the broken assets by user.
That could come as a warning when assigning an asset to the user.
Reopening it.

**Comment by tymik** [comment]
+1 for that. i personally don't have a case for it at the moment, but it may change in future.

**Comment by tymik** [comment]
It's still relevant

**Comment by xAbrielx** [comment]
+1 it would be very useful

**Comment by chantellmocha** [comment]
I agree - this would be helpful for my team as well, for obvious reasons.

**Comment by HammyHavoc** [comment]
Looks like I'll be creating `Status` for this too, this would be super useful to have properly integrated.

**Comment by autorekasim** [comment]
Not sure why this is closed, still very relevant and I'd love to see this.
