### ISSUE TITLE
Support for Mobility License

### ISSUE THREAD

**Issue by DanielNemanic** [snipe/snipe-it#536]
Sometimes it is necessary to install a License on a Laptop.
AutoDesk etc has the ability in the license agreement to install this License on a Laptop.

Is there any way, without seats, to checkin?
Maybe an extra field in the future under seats. The ability to assign a device to that license, but not directly to the seat.

**Comment by snipe** [comment]
Hi @DanielNemanic - in the license checkout, you can select either a person or an asset to assign a license to. There is no way to checkout without seats, but if you only had one seat, you would just create one seat and assign that.

**Comment by DanielNemanic** [comment]
Yes thats correct.
This should work.
