### ISSUE TITLE
API Token lost after upgrade docker container

### ISSUE THREAD

**Issue by Dramaretchi** [snipe/snipe-it#5366]
Thanks for this awesome tool. I have an issue:

I have a mobile app that needs to call the hardware API. The API key is hardcoded into the app everything its ok. 

Anyhow, today we backup all data (.sql file) and we have created another Dock container due to we updated from 4.1.13 to 4.2.0 **but we lost the API tokens** (they are listed on Personal API Keys but not work until we create a new one).

How can I use the API without a token under our responsibility **or** how can I backup the API tokens? can be stored in the database? or use a username / password?

Cheers,

**Comment by uberbrady** [comment]
If you sitll have the old container, look for the oauth keys in the `./storage` subdirectory - and then you can copy them over to the new Docker container.

That is, until we fix the oauth key persistence issue fully.

**Comment by uberbrady** [comment]
So here's some more info in case you need it - 

When I do this:

```bash
docker exec -t -i snipeit /bin/bash
```

I can do this and this is what I see:

```bash
root@b59004fd0f59:/var/www/html# ls -al storage/
total 32
drwxr-xr-x 1 docker root  4096 Apr  7 02:45 .
drwxr-xr-x 1 docker root  4096 Mar 29 02:19 ..
drwxr-xr-x 1 docker root  4096 Mar 29 02:19 app
drwxr-xr-x 1 docker root  4096 Mar 29 02:19 debugbar
drwxr-xr-x 1 docker root  4096 Mar 29 02:19 framework
drwxr-xr-x 1 docker root  4096 Mar 29 02:19 logs
-rw-r--r-- 1 docker staff 3292 Apr  7 02:45 oauth-private.key
-rw-r--r-- 1 docker staff  812 Apr  7 02:45 oauth-public.key
lrwxrwxrwx 1 root   root    37 Mar 29 02:19 private_uploads -> /var/lib/snipeit/data/private_uploads
```

The keys you need to extract and copy over to your newer container would be the `oauth-private.key` and `oauth-public.key` - if you can grab those off of the old container, and copy them into the same locations on the new one, you should be all set. I'm working on fixing the problem, permanently, right now - but that will only help people going forward, not right now.

**Comment by snipe** [comment]
This should be fixed on develop now.

**Comment by Dramaretchi** [comment]
Thank you!!
