### ISSUE TITLE
Feature Request: License Annual Maintenance / Software Assurance

### ISSUE THREAD

**Issue by FooBarTrixibell** [snipe/snipe-it#5367]
#### Desired Behavior

When ticking the maintained box in Licenses an additional box for maintenance cost could be added, allowing for ongoing maintenance costs to be tracked.

**Comment by sashashark** [comment]
+1 for this request.  Initial purchase of some high-end R&D software costs CapEx dollars and depreciates.  Yearly support tracking adds to the cost and definitely needs to be tracked for budgetary reasons.
