### ISSUE TITLE
No sync of employeeID using LDAP

### ISSUE THREAD

**Issue by pvhkai** [snipe/snipe-it#5369]
Dear all,

first of all I want to say thanks for the great product - we are using Snipe-IT now for more than a year and it is great! :)

I now faced an issue synchronizing the LDAP employeeID. We had no employeeID set in our AD yet so I did not fill out the field on the LDAP admin page. Now this has been switched. So there is a need to synchronize all employeeIDs from the users. I filled "employeeID" in the  "LDAP Employee Number" and saved. I tried to update the users using LDAP but the Employee Number stays empty. Creating new users works perfectly so I think the LDAP itself works well!

Also laravel.log stays empty (no error has been logged). 

### We are using:
- Snipe IT v4.2.0 build 3497
- Microsoft-IIS/8.5 
- PHP version: 7.0.11 
- mysqlnd 5.0.12

Thanks a lot,
pvhkai

**Comment by vogtmh** [comment]
Hi Pvhkai,

have you tried to use "employeeid" (all lowercase)?

- Max

**Comment by vogtmh** [comment]
Nice one :)

**Comment by snipe** [comment]
Awesome! Glad to hear you're all sorted. In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
