### ISSUE TITLE
Order of numerical custom fields

### ISSUE THREAD

**Issue by vogtmh** [snipe/snipe-it#5371]
#### Expected Behavior (or desired behavior if a feature request)

Numerical fields should be sorted ascending.

![image](https://user-images.githubusercontent.com/37808063/38795619-2313b6c0-4159-11e8-9a20-2ddc3fa2d0aa.png)

-----

#### Actual Behavior

Numerical fields are sorted by an alphabetical algorithm, which compares them char by char. 

![image](https://user-images.githubusercontent.com/37808063/38795553-f3eb4ea8-4158-11e8-8c5e-8612d15e4193.png)

-----

#### Potential fix

Sorting is done through orderBy which depends on the db field type. Numerical fields in SnipeIT create text db entries, therefore the sorting uses alphabetical comparison.

Manually changing the db field through phpmyadmin fixed the issue for me. 

![image](https://user-images.githubusercontent.com/37808063/38796197-ef3a931c-415a-11e8-8ceb-d71fa6a9e2f0.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Current Demo on https://demo.snipeitapp.com/hardware
- Version of Snipe-IT you're running: 4.2.0 build 3497
- Bug can be reproduced on current demo with assets "sort-numerical1", "sort-numerical2", "sort-numerical3"

**Comment by snipe** [comment]
We won't be supporting db-specific field creation any time soon. Different versions of MySQL can react differently (badly) if you try to change the field type and the existing content doesn't match what you're trying to change it to.
