### ISSUE TITLE
Feature Request - Account Permission to View Encrypted Fields

### ISSUE THREAD

**Issue by andrewcgmorris** [snipe/snipe-it#5373]
#### Expected Behavior (or desired behavior if a feature request)

Account permission radio button to allow access to View encrypted fields. 
Account permission radio button to allow access to Edit encrypted fields.
Would like to add this to a group where users are not necessarily Administrators to allow engineers to view. Similar to the other permission group options. 

-----

#### Actual Behavior

Only Administrators can view encrypted fields.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by PetriAsi** [comment]
This would be very useful for us.

**Comment by coxmic** [comment]
Would also like this feature

**Comment by CVogus** [comment]
This would be an incredibly important feature. I would like to restrict access to most parts of SnipeIT to prevent bad data from being created easily by inventory managers, but I also want to allow them to see/edit encrypted fields (which may contain sensitive info) without giving them Super User which is essentially the keys to the kingdom. Super User is a quick and assured way of opening the door for all kinds of bad data.

**Comment by itsFlake** [comment]
This would be very useful for us.
Our accounting need the information in the field.
