### ISSUE TITLE
Bulk delete users

### ISSUE THREAD

**Issue by meyerf99** [snipe/snipe-it#5374]
Hi guys,

I want to delete all LDAP imported users from our Snipe-IT.

V. 4.2.0

But now i get this Error: "Whoops, looks like something went wrong."

Does any one know this issue with bulk delete users?

Kind regards,

Flavio

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by meyerf99** [comment]
@snipe Sorry for my mistake...

- CentOS 7.4 and Apache 2.4
- We used the method with install.sh
- Error: Whoops, looks like something went wrong.
- I was on the people Snipe-IT site and want to bulk delete some LDAP imported users.
- Error can't reproduce in your demo infra because we can't delete bulk users.

I hope this informations are enough. If not you can ask me for more informations.

**Comment by clstone99** [comment]
I am having the same issue.  
v4.2.0 - build 3497
CentOS 7.4
PHP v7.2.4
MariaDB 5.5 

Steps:
- On the People page, selected ~49 users, choose Bulk Checkin & Delete, then Go.  
- WARNING: You are about to delete the 49 user(s) listed below. Super admin names are highlighted in red.
- Choose 'Archived' the bottom of the page 
- Click Submit
- Error:  Whoops, looks like something went wrong

Attached:  
1) ErrorException.txt
2) DebugMessage.txt

Please let me know if additional debug output will help.
[ErrorException.txt](https://github.com/snipe/snipe-it/files/1921561/ErrorException.txt)
[DebugMessage.txt](https://github.com/snipe/snipe-it/files/1921562/DebugMessage.txt)

**Comment by meyerf99** [comment]
Hi @snipe 

Do you know this issue in the latest Snipe-IT version?

**Comment by snipe** [comment]
> Error: Whoops, looks like something went wrong.

As we mentioned, we need a stack trace from your logs. Without additional information, we can't possibly know what's happening.

**Comment by dmeltzer** [comment]
@clstone99 snipe-it is currently not playing nicely with php7.2  I'd recommend downgrading to php7.1 for the present until we can hunt down all bugs.  @meyerf99 if you are on php7.2 the same advice applies

**Comment by meyerf99** [comment]
@dmeltzer @clstone99 @snipe 

We solved this issue with downgrading PHP to version 7.1.16.
