### ISSUE TITLE
Debug Mode Stuck On

### ISSUE THREAD

**Issue by bdg-robert** [snipe/snipe-it#5375]
#### Expected Behavior (or desired behavior if a feature request)

When APP_DEBUG=false is set, debug should be off.

-----

#### Actual Behavior

Debug mode is on, despite having APP_DEBUG=false set in the .env file.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
Fresh Install
- Version of Snipe-IT you're running
v4.2.0 - build 3497 (master)
- Version of PHP you're running
7.0.28-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running
mysql Ver 14.14 Distrib 5.7.21
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04 LTS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
NA
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Dashboard
- If a stacktrace is provided in the error, include that too.
NA
- Any errors that appear in your browser's error console.
NA
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
NA
- Include any additional information you can find in `storage/logs` and your webserver's logs.
NA
- Include what you've done so far in the installation, and if you got any error messages along the way.
Debug turned on to troubleshoot an image file upload causing an error. Issues resolved but now Debug mode won't disable.
- Indicate whether or not you've manually edited any data directly in the database
NA

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/common-issues#section-changes-to-my-env-file-dont-seem-to-be-updating
