### ISSUE TITLE
Import only setting one location field in DB

### ISSUE THREAD

**Issue by cepacs** [snipe/snipe-it#5396]
#### Expected Behavior (or desired behavior if a feature request)
When importing an asset with a location I was hoping to see that fill in both location fields (rtd_location_id & location_id) in the asset table.
 
-----
#### Actual Behavior
Currently on import it will fill in the rtd_location_id which means if we try to export on a location we don't get those items.  If I go into the asset and simply click save it does seem to populate the location_id at that point and then all is good, but obviously on large imports this would not be ideal.

I am not sure if this is a bug and maybe by design but if it is I would like to see a request a feature update to have location_id be updated by the importer too.

Thanks :)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Fresh**
- Version of Snipe-IT you're running **Version v4.2.0 build 3497 (master)**
- Version of PHP you're running **PHP version: 7.1.16**
- Version of MySQL/MariaDB you're running **MySQL Server version: 5.7.21**
- What OS and web server you're running Snipe-IT on **Windows Server 2016 / IIS**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **GIT**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I believe this was fixed in a later version.
