### ISSUE TITLE
Compliment and Ticket of Gratitude

### ISSUE THREAD

**Issue by SkellaMental** [snipe/snipe-it#5397]
#### Expected Behavior (or desired behavior if a feature request)
Simple running install.sh
installer takes care and plays "mother hen"  - log in to home page - start working.
(what you expect to happen goes here)

-----

#### Actual Behavior
Good Day Snipe/SnipeIT

Followed instructions
much blank pages, ERROR 500 and "Doh, etc etc" messages. 
Loads of googling, githubbing, cursing, uninstalling , flushing, removing, purging, apt-getting, laravelling, then finally realising that firstly I had the php updated but not enabled (a2dismod5 && a2enmod php7.1) and also that the php version (cli) was incorrect  and also the install.sh does not actually complete the migrate and install unless you run it with elevated rights.

after much editing of the apache.conf file, sites-enabled, and multiple iterations of .htaccess, ufw, and apparmor this was the final clincher for me

`sudo a2dismod php5 && sudo a2dismod php5.6 && sudo a2enmod php7.1 && sudo service apache2 restart`

Just thought I would (after a few evenings pain) tell you a **great thank you for a REALLY useful piece of kit and that there is someone out there who appreciates all your hard work!**

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
Yes - for a while - now disabled
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
Also loads of reading
-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install - multiple times
- Version of Snipe-IT you're running
v4.2.0 build 3497 (g590938f)
- Version of PHP you're running
first 5.0 , then 5.6 then PHP 7.1.16-1+ubuntu14.04.1+deb.sury.org+1 (cli)
- Version of MySQL/MariaDB you're running
mysql  Ver 15.1 Distrib 10.1.32-MariaDB, for debian-linux-gnu (i686) using readline 5.2
- What OS and web server you're running Snipe-IT on
Description:	Ubuntu 14.04.5 LTS "trusty"
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
it has since passed
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
index.php
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
repeated entries as follows

> PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 444

- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
yes - had to change user password in both .env and mariadb. 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
>  install.sh does not actually complete the migrate and install unless you run it with elevated rights

Yeah, the installer has to install PHP, etc, so it needs sudo or root. There's no way around that.

> a great thank you for a REALLY useful piece of kit and that there is someone out there who appreciates all your hard work!

Thanks so much for the kind words!
