### ISSUE TITLE
Asset View - User permissions

### ISSUE THREAD

**Issue by JSCMP** [snipe/snipe-it#5399]
#### Expected Behavior (or desired behavior if a feature request)

Any way to restrict what assets get displayed to a user? We have users out in the field we would like to be able to check out and checkin assets using QR codes. The problem right now, is that those users are able to see the entire asset inventory list once they login.  Editing the permissions for the user, and denying viewing rights disables them from viewing all the assets, including the ones we want them to be able to view/checkout/checkin. I have played with the company fields on the assets and the users, but makes no difference as far as rights/permissions. Either they see all assets or none. We don't want users to be able to see the entire company's assets. Also is there a way to checkout or checkin by just using the QR code out in the field, that is easier than having to login, and additionally do a few additional extra steps? Could just login be implemented, and maybe a simple checkin and checkout button? Thank you.
-----

#### Actual Behavior

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  Fresh Instal
- Version of Snipe-IT you're running - 4.2.0
- Version of PHP you're running - 5.6
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on - CENTOS, Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Softaculous
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by EarlRamirez** [comment]
@JSCMP this *might* work for you, enable **Full Multi-company support** create a company for this user and grant him the desired group, this worked for me. Multi-company support permits access only to that company. I know it's not pretty but it can be an interim solution.

**Comment by JSCMP** [comment]
Thank you EarlRamirez, this may work as an interim solution.

**Comment by ARCHIT48** [comment]
There still isn't any solution to this - I want a specific list of assets to be viewed to a specific user.

**Comment by snipe** [comment]
That's not on the short term roadmap at this time.

**Comment by ARCHIT48** [comment]
:) Thank You for such a prompt response, I was wondering - is there any other open source application which can help solve this problem statement.

**Comment by snipe** [comment]
What's the use case here? Full Company Support should be able to handle most of these use cases.

**Comment by ARCHIT48** [comment]
So, we are basically an integration company between the telematic devices and batteries for Electric Vehicle Company. 
The assets need to be dispatched to battery manufacturers and from there the battery manufacturers will give it the vendors and that's where comes the need of - dispatching specific assets to specific users.

**Comment by snipe** [comment]
Right, but wouldn't Full Multiple Company support handle that for you? You would set up the restrictions as "companies"

**Comment by ARCHIT48** [comment]
No, actually there are sub levels in a company where selective assets are to be dispatched
Snipe It is quite adequate for plenty of things, but just this feature is a much needed and it would be a complete package of all. :)

**Comment by snipe** [comment]
I don't know of any software out there that does that, sorry.

**Comment by ARCHIT48** [comment]
NO issues, I really appreciate the time you invested to communicate. 
Thanks a ton.

**Comment by snipe** [comment]
Sure thing - I'm sorry I don't have a better answer for you :(

**Comment by ARCHIT48** [comment]
So, can this feature be added to snipe it?

**Comment by thatsankur** [comment]
Much needed one. Right now the guys who are just supposed to checkin and checkout the assets assigned to them are capable of doing more than that.  They can check in assets assigned to anywhere and checkout to anyone. I have to explore  full company support but without workaround it would be kind of expected behaviour! 

Anyways let me explore this system bit more.

**Comment by Nimeshin** [comment]
This is a needed feature for many reasons, users should only be able to see assets check out to them for accountability purposes as well.
