### ISSUE TITLE
Empty menu for user without permission

### ISSUE THREAD

**Issue by pscsantoni** [snipe/snipe-it#5403]
#### Expected Behavior (or desired behavior if a feature request)

When a user without any permission login, the left menu should not be displayed as it is empty.

-----

#### Actual Behavior

When a user without any permission login, the left menu is available, but without any items listed. Users can assume it is a bug.

-----

#### Please confirm you have done the following before posting your bug report:

- [* ] I have enabled debug mode 
- [* ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
_Fresh install_
- Version of Snipe-IT you're running
_v4.1.14_
- Version of PHP you're runnin
_php7.0.29-1+ubuntu16.04.1+deb.sury.org+1_
- Version of MySQL/MariaDB you're running
_MariaDB 10.2_
- What OS and web server you're running Snipe-IT on
_ubuntu 16.04_
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
_No error_
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
_Home page_
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
_None_
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Please provide a screenshot.

**Comment by pscsantoni** [comment]
![snipe-it](https://user-images.githubusercontent.com/38563485/39195266-c2cf01ec-47df-11e8-9667-b01aa89384be.png)

Hello,
Here is the screenshot.
Best,
Pascal.

**Comment by pscsantoni** [comment]
Hello,

Any news regarding this request ?
Is it possible to know if this behaviour is in design or a bug ?

Thanks for your time !

**Comment by sa1eemKhan** [comment]
Hi @pscsantoni Have you solved this problem? I am facing the same problem.
![image](https://user-images.githubusercontent.com/44273781/47257692-7f4bc100-d4aa-11e8-9984-6f727d5030e7.png)
