### ISSUE TITLE
Undo, remove, and/or edit a consumable's checkout record.

### ISSUE THREAD

**Issue by jjmuelle-bhk** [snipe/snipe-it#5405]
#### Expected Behavior (or desired behavior if a feature request)

Ability to undo, remove or even edit a record from a consumable's checkout record.

-----

#### Actual Behavior

No UI ability to do the above. If I accidentally check out the wrong consumable, there's no way to properly undo it.

I could delete the item and create it again, and checkout the correct amount, but then all of the time stamps would be incorrect.

I could find the entry in the database table and delete it, but without the knowledge of how the data is stored and referenced, that has the potential to break everything. If at all possible, for the time being, if you could walk me through what it would take to effectively remove the entry from a consumable's checkout record, that would be fantastic.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Upgrade**
- Version of Snipe-IT you're running **v4.2.0**
- Version of PHP you're running **7.0.28-0ubuntu0.16.04.1**
- Version of MySQL/MariaDB you're running **10.0.33-MariaDB-0ubuntu0.16.04.1**
- What OS and web server you're running Snipe-IT on **Ubuntu 16.04.3 LTS - Apache/2.4.18 (Ubuntu)**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **git clone**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **N/A**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **N/A**
- If a stacktrace is provided in the error, include that too.  **N/A**
- Any errors that appear in your browser's error console. **N/A**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. **The demo also doesn't seem to allow modifying a consumable's records**
- Include any additional information you can find in `storage/logs` and your webserver's logs. **N/A**
- Include what you've done so far in the installation, and if you got any error messages along the way. **N/A**
- Indicate whether or not you've manually edited any data directly in the database **N/A**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by dougthor42** [comment]
I just ran into this problem... can this request be re-opened?

**Comment by AsimAJ33** [comment]
I'd also really like this feature.  I just accidentally checked out the wrong consumable to a user.

**Comment by reuben-thundergrid** [comment]
+1 much needed
