### ISSUE TITLE
New Install. QR Code directing to internal IP. APP_URL= correctly set to external domain

### ISSUE THREAD

**Issue by JSCMP** [snipe/snipe-it#5406]
#### Expected Behavior (or desired behavior if a feature request)

Brand new installation. APP_URL has the correct domain to access the website from the Internet, I can manually open it and test that it works, yet when I scan the QR codes it opens the internal IP address.:
http://10.0.1.254/hardware/2

My env. file showing the APP_URL:

Why is Snipe-IT generating QR codes with internal IP, where nowhere I have put the Internal IP for it.
Using 4.2.0

APP_ENV=production
APP_DEBUG=false
APP_KEY=
APP_URL=http://XXXXXXXX.com
APP_TIMEZONE='UTC'
APP_LOCALE=en

See issue #4530 . Similar and never was resolved. Where App_URL shows the correct URL yet the QR code shows internal IP.
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
The only thing I can think of is that you have a misconfiguration in your web server's hostname. QR codes use the routes, which (I think) uses your hostname.

**Comment by JSCMP** [comment]
Thank you snipe, I will check those again.
