### ISSUE TITLE
Found some non-translated text in notifications

### ISSUE THREAD

**Issue by smksar** [snipe/snipe-it#5411]
Version 4.2.0

Just to share I found out that the following notifications (under snipe-it\app\Notifications) do not have any language translated but just English:

1. ExpectedCheckinNotification.php
![image](https://user-images.githubusercontent.com/38576928/39081440-e8c7f58e-4573-11e8-9bc9-c29f7add09eb.png)

2. CheckinLicenseNotification.php
![image](https://user-images.githubusercontent.com/38576928/39081432-d256bed4-4573-11e8-9232-4369be257a93.png)

3. CheckoutAccessoryNotification.php
![image](https://user-images.githubusercontent.com/38576928/39081450-066e351c-4574-11e8-8b79-7e96bde1708f.png)

4. CheckinAssetNotification.php
![image](https://user-images.githubusercontent.com/38576928/39081453-1e8bfac6-4574-11e8-8fa0-e943b743d844.png)

I understand to edit and do it myself but would like to share and help in my smallest way possible for others as well. 

Thank you Snipe-IT m(_ _)m

**Comment by EarlRamirez** [comment]
@smksar you can check out **https://snipe-it.readme.io/docs/contributing-overview** for contributing to the project
