### ISSUE TITLE
document deployment without .htaccess

### ISSUE THREAD

**Issue by benrubson** [snipe/snipe-it#5412]
Hi,

Would be nice to add to the documentation rules required by an Apache VirtualHost for a deployment without `.htaccess` file.
There is a performance hit enabling `.htaccess` files, as well as some security concerns.

Rewrite rules should ideally be given outside of `<Directory>` sections, so that an additional / unwanted `Options +FollowSymLinks` is not needed.

Thank you 👍 

Ben

**Comment by benrubson** [comment]
Here is what I have in my Apache VirtualHost :

```
RewriteEngine On
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} (.+)/$
RewriteRule ^ %1 [L,R=301]
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
RewriteRule ^ /index.php [L]
```

**Comment by benrubson** [comment]
Why administration issue ?
Apache `.htaccess` files are from Snipe-IT, so we should be able to translate them to Apache VirtualHost rules :)

**Comment by benrubson** [comment]
Mmmh system administrators can't guess needed rules.
`.htaccess` files are provided by Snipe-IT, so its documentation should be able to list these rules to include into an Apache VirtualHost :)
I've constructed the list above based on `public/.htaccess`, it's not so far from reality.
I think it would be nice to have it documented (and maintained according to `.htaccess` updates).

**Comment by snipe** [comment]
They can't guess needed rules, but if they understand enough about servers to add those rules to their virtual host configuration, they know to check the htaccess for the rules. 

This is really an issue of not wanting to further confuse users for the edge case of someone who wants to move those rules into their vhost config. Non-web folks already have a hard time getting things up and running, as evidenced by the fact that we have to explain how to set up a virtual host in the first place (which I feel is also out of scope for project documentation, but we got too many GH issues asking questions about how to set up a website.)

Anyway - it's added. Hopefully it won't confuse people further.

**Comment by benrubson** [comment]
> if they understand enough about servers to add those rules to their virtual host configuration, they know to check the htaccess for the rules.

I admit Snipe-IT has rather simple `.htaccess` files, just one, and simple to translate to VirtualHost rules. But some other projects have many ones, with tens of rules...
Having them documented makes sysadmin more confident :)

Thank you very much then for having [documented it](https://snipe-it.readme.io/docs/linuxosx) 👍
Perhaps you could also modify the configuration you just added (the one with the rewrite rules then) with the following :
```
		AllowOverride None
		Options None
```
`AllowOverride All` / `Options  +Indexes` values are here just to make Apache to look for `.htaccess` files, which is then no more wanted, for performance and/or security reasons.
Thank you again !
