### ISSUE TITLE
[Feature Request] Get Consumables by tag name

### ISSUE THREAD

**Issue by Dramaretchi** [snipe/snipe-it#5413]
Hello, with the REST API, how can I get the Consumables by tag name or by Company id plus Category id?

Thank you! awesome platform.

Cheers,

**Comment by snipe** [comment]
Consumables don't have asset tags, so there is no way to search for them by tag. 

To return them by company or category, just pass that in your query string. 

/api/v1/consumables?category_id=10
/api/v1/consumables?company_id=10

**Comment by Dramaretchi** [comment]
Thank you ! and sorry for my question. How can I help to support this awesome project? Paypal?

**Comment by snipe** [comment]
@Dramaretchi Don't apologize for questions - our documentation was missing those parameters. I've updated them now to reflect the filter-able fields. https://snipe-it.readme.io/v4.2/reference#consumables

We always appreciate donations, thank you! :) You can use PayPal or a credit card. https://snipeitapp.com/donate
