### ISSUE TITLE
Add missing REST API documentation for maintenances endpoint (/api/v1/maintenances)

### ISSUE THREAD

**Issue by nhut** [snipe/snipe-it#5416]
#### Expected Behavior (or desired behavior if a feature request)
Maintenance endpoint REST API to be shown in REST API documentation https://snipe-it.readme.io/v4.2/reference.
-----

#### Actual Behavior
Currently it is missing from the REST API documentation https://snipe-it.readme.io/v4.2/reference. Maintenance REST API endpoint works though e.g.
- GET /api/v1/maintenances
- GET /api/v1/maintenances?asset_id=1
(Found them from the source code)
-----

#### Please confirm you have done the following before posting your bug report:
- [o] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
-----

**Comment by snipe** [comment]
https://snipe-it.readme.io/v4.2.0/reference#maintenances

**Comment by harryjohn-dev** [comment]
@nhut do they exist in the source code? Wanting to PATCH also...

**Comment by nhut** [comment]
> @nhut do they exist in the source code? Wanting to PATCH also...

@sheppyh Documentation is updated since I last use it: https://snipe-it.readme.io/reference#maintenances
It still doesn't list all the endpoints though but you can give it a try.

You can check the code in:
https://github.com/snipe/snipe-it/blob/v5.0.12/app/Http/Controllers/Api/AssetMaintenancesController.php

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference#maintenances">Overview</a></strong></div><div>Snipe-IT is a free, open source IT asset management system. Features include management of assets, users, licenses, accessories, consumables and components, as well as two-factor authentication, LDAP/AD syncing, and asset acceptance confirmation.</div></blockquote>
<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snipe/snipe-it">snipe/snipe-it</a></strong></div><div>A free open source IT asset/license management system - snipe/snipe-it</div></blockquote>
