### ISSUE TITLE
[Feature Request] API query to exclude IDs from result

### ISSUE THREAD

**Issue by cwoods131** [snipe/snipe-it#5417]
#### Expected Behavior (or desired behavior if a feature request)

When querying the API would it be possible to exclude certain IDs from the result. 
Example:
api/v1/hardware?status_id!=4

Would return all the hardware that does not have a Status Label ID of 4.

If it's possible to add 'status_id!' (with exclamation point) then exclude which ever id the value of that variable is.

Thank you in advance.

-----

#### Actual Behavior

Currently this feature doesn't exist.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

Is this a fresh install or an upgrade?
Fresh

Version of Snipe-IT you're running
v4.1.14 - build 3416 (master

Version of PHP you're running
7.0.25-0ubuntu0.16.04.1

Version of MySQL/MariaDB you're running
10.1.31-MariaDB-1~xenial - mariadb.org binary distribution

What OS and web server you're running Snipe-IT on
Win7 on Chrome 64

What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual

What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
api/v1/hardware

Indicate whether or not you've manually edited any data directly in the database
No data has been manually edited.

**Comment by cwoods131** [comment]
We are using the API to filter out specific status' and categories for custom reports. We have added multiple status labels for our mass of inventory. For instance, I need to return all devices that don't have a status - 'In For Service'
Thank you!

**Comment by bud313** [comment]
Being able to search for things that don't match a query would help me with some of my api calls as well.
