### ISSUE TITLE
email alerts not sending

### ISSUE THREAD

**Issue by chrisleary7** [snipe/snipe-it#5418]
#### Expected Behavior (or desired behavior if a feature request)

I expect when our consumables get below the specified level that an alert would be sent to the users listed in Notifications.

-----

#### Actual Behavior

The webpage shows the alert that the consumable is below the minimum level but the email never sends.

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? fresh install
- Version of Snipe-IT you're running - 4.1.10
- Version of PHP you're running - 5.6.25
- Version of MySQL/MariaDB you're running - 
- What OS and web server you're running Snipe-IT on - Windows Server 2016 & wamp
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - no error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Consumables
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. - no error messages
- Indicate whether or not you've manually edited any data directly in the database - no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

We have Snipe-IT up and running and are able to send test emails but when we test our consumables by lowering the quantity below the minimum we do not get any email alerting us.  If I am on the server and run the php artisan inventory:alert, I get the message "There are no commands defined in the inventory namespace."  When I search on that I find a lot of references to Linux servers but no windows.  Is there a scheduled task that needs to run to get this information and if so how would that be configured?

Thanks.

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/configuring-alerts-backups
