### ISSUE TITLE
Assets All Pending View not working

### ISSUE THREAD

**Issue by vaxo101** [snipe/snipe-it#5419]
#### Expected Behavior (or desired behavior if a feature request)

Sidebar > Assets > All Pending: Shows Pending

-----

#### Actual Behavior

Sidebar > Assets > All Pending: Shows Ready to Deploy then at bottom of page shows pending

-----

#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running? v4.2.0 - build 3497 (master)
- Version of PHP you're running? 7.0.28-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running?
- What OS and web server you're running Snipe-IT on? Ubuntu 16.04 Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: No error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error? Sidebar > Assets > All Pending
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. No
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. No
- Include any additional information you can find in `storage/logs` and your webserver's logs. 
- Include what you've done so far in the installation, and if you got any error messages along the way.
Rebooted the server.
- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Can you provide screenshots of your status labels page?

**Comment by vaxo101** [comment]
URL/hardware?status=Pending
Screenshot:
https://i.imgur.com/i5d1wNe.png

**Comment by snipe** [comment]
The status labels page, not the assets page.

**Comment by vaxo101** [comment]
hi @snipe unsure what page that is. Can you provide what the URL should be? (mydomain.com/example)

**Comment by leebaggaley** [comment]
mydomain.com/statuslabels

**Comment by leebaggaley** [comment]
Sounds like you may have a few status labels set to "Pending" (See image). Might be an idea to have a look at the statuses to check and make the necessary adjustments ;)

![image](https://user-images.githubusercontent.com/37484200/39274801-0a914b1a-48db-11e8-8e09-5dec2392d4e0.png)
