### ISSUE TITLE
[Bug?] LDAP/AD settings

### ISSUE THREAD

**Issue by steven3721** [snipe/snipe-it#5420]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

after configured the LDAP/AD, it should allow new created LDAP/AD user to sign in, and we should can run LDAP/AD user sync to import users from LDAP/AD.
-----

#### Actual Behavior

1. I can run ldap/ad user sync, but new created AD users cannot sign in, the snipe-it couldn't create the user.
2. I have to update the ldap/ad settings in snipe-it to allow AD user to sign in.
        Changes:
        Username Field: samaccountname  -> sAMAccountName
        LDAP First Name: givenname  -> givenName
3. After changed the ldap settings, ldap/ad user sync doesn't work anymore, to make it work again, I have to restore the changes in ldap/ad settings.

-----

#### Please confirm you have done the following before posting your bug report:

- [ Y ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install
- Version of Snipe-IT you're running  
 4.20
- Version of PHP you're running    
php5.6
- Version of MySQL/MariaDB you're running
MySQL 5.5.47
- What OS and web server you're running Snipe-IT on   
Ubuntu 14.04, Apache 2.4.18
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)  
manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
LDAP/AD User Sync  and Login page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
login page : Error:  The username or password is incorrect. (when use samaccount and givenname in ldap settings)
LDAP/AD User Sync: The firstname is required, the username is required.  (when use sAMAccountName and givenName in ldap settings)
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
production.ERROR: There was an error authenticating the LDAP user: Could not create local user
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by Mynty100** [comment]
If windows AD should look like this.
![image](https://user-images.githubusercontent.com/34461276/39905975-7a43a71a-5523-11e8-8faf-bf7231d3048a.png)
provided you service account has permissions and you are pointing to the right OU.

**Comment by karolyczovek** [comment]
Also have the issue, IF we synced with ldap BEFORE the user tries to log in, so the user entry is present before. If the user logs in first, just works fine.
