### ISSUE TITLE
403 Forbidden Error

### ISSUE THREAD

**Issue by qcfourie** [snipe/snipe-it#5424]
#### Expected Behavior (or desired behavior if a feature request)

Hi All

I need some help please, when opening the URL to my newly installed server and Snipe-IT, I exepct to see the Snipe-IT login page, but instead receive the following error:
Blank page opens with "403 Forbidden Error"

I followed these instructions exactly
https://www.vultr.com/docs/how-to-install-snipe-it-on-centos-7

Some more information:
- It is a fresh Install 
- Snipe-IT version 4.2
- PHP version 5.6.35
- Mysql  Ver 15.1 Distrib 5.5.56-MariaDB
- CentOS Linux 7

Anyone's help would be greatly appreciated.

Thank you in advance!

**Comment by snipe** [comment]
There's not really an easy way to know what you did wrong here. (Additionally, we recommend using our own documentation over a third-party, since we keep ours updated.) 403 errors usually happen on servers because the virtual host is pointing at a default directory instead of where they should be pointing, in this case at your Snipe-IT public directory.

**Comment by qcfourie** [comment]
Thank you for the prompt and friendly assistance. Do you perhaps have a quick link to your installation guide?

Best regards

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/installation

**Comment by qcfourie** [comment]
I noticed that the {server-IP} was removed from all the above URLs

**Comment by qcfourie** [comment]
Hi

When checking the folder permissions, the apache user does have rights to the folder
[root@snipeit ~]# ls -ld /var/www/html
drwxrwsr-x. 3 apache apache 21 Apr 25 06:54 /var/www/html

Still receiving "You don't have permission to access / on this server."

Any help please

**Comment by snipe** [comment]
As I mentioned, this usually is a result of your virtual host in your web server's configuration pointing to the wring directory. We can't really help you without seeing what you have.

**Comment by qcfourie** [comment]
Thanks, herewith the virtualhost setting

<VirtualHost *:80>
    ServerName snipeit.afgri.com
    DocumentRoot /var/www/html/snipe-it/public
    <Directory /var/www/html/snipe-it/public>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
    </Directory>
</VirtualHost>

**Comment by qcfourie** [comment]
![image](https://user-images.githubusercontent.com/17596511/39246887-255a2ea0-4898-11e8-87a6-12d216ccf5bc.png)

**Comment by EarlRamirez** [comment]
@qcfourie which method did you use to install Snipe-IT? I have never experienced any issues, using ./install or manual, below is the vhost from a vanilla install
<VirtualHost *:80>
ServerAdmin webmaster@localhost
    <Directory /var/www/html/snipeit/public>
        Allow From All
        AllowOverride All
        Options +Indexes
   </Directory>
    DocumentRoot /var/www/html/snipeit/public
    ServerName kvm-snipeit
        ErrorLog /var/log/httpd/snipeIT.error.log
        CustomLog /var/log/access.log combined
</VirtualHost>

**Comment by qcfourie** [comment]
Thank you very much Earl, seeing that this forum tool removes certain XML nodes, is this what you mean by the above? I still get the same result: "You don't have permission to access /snipe-it on this server."

![image](https://user-images.githubusercontent.com/17596511/39281843-033503ee-4907-11e8-8841-7ebaeb969ce6.png)

**Comment by qcfourie** [comment]
What is your recommendation please? Should I start from scratch again?

**Comment by EarlRamirez** [comment]
You can try the installation again, by running ./install.sh from the snipe-it directory that you have downloaded.

**Comment by qcfourie** [comment]
Hi Earl / Snipe
I did the installation exactly as described in the below tutorial
https://snipe-it.readme.io/docs/installation

When I open my web page now, I do not receive an error anymore, but a blank page.

When looking at the error log in the /var/log/httpd/ folder, the below error messages is very prominent.

Any help please!

[Thu Apr 26 14:11:40.108021 2018] [:error] [pid 1289] [client 192.168.29.117:1845] PHP Warning:  require(/var/www/html/snipeit/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/snipeit/bootstrap/autoload.php on line 17
[Thu Apr 26 14:11:40.108098 2018] [:error] [pid 1289] [client 192.168.29.117:1845] PHP Fatal error:  require(): Failed opening required '/var/www/html/snipeit/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipeit/bootstrap/autoload.php on line 17

**Comment by EarlRamirez** [comment]
@qcfourie you can try running composer again, keep an eye out for any timeouts.

**Comment by qcfourie** [comment]
Hi Earl / Snipe

Now I receive a page timeout error.

How do we go ahead getting paid support please?

Best reagrds

**Comment by EarlRamirez** [comment]
@qcfourie here you go **https://snipeitapp.com/hosting**

**Comment by qcfourie** [comment]
Hi Earl

There is just monthly recurring plans. What if I need just an hour or so of your time to correct my install?

Awaiting your response

**Comment by EarlRamirez** [comment]
@qcfourie I may have a little time after 1300 EDT.

**Comment by qcfourie** [comment]
Hi Dear

Thank you for your response. Apologies for only getting back to you now. Can we arrange for any time today (Monday) please? Should we arrange for 13:00 EDT?

Thank you in advance!

Regards

[QFSigNew2]<http://www.qcsolutions.co.za/>











[QFQR]

Tel: +27 87 742 2500

Email: quentin@za.qcsintl.com<mailto:quentin@za.qcsintl.com>

50 Kremetart st



Direct: +27 87 742 2502

Website: www.qcsolutions.co.za<http://www.qcsolutions.co.za/>

Val de Grace



Cell: +27 83 653 6623

Skype: qcfourie

Pretoria, South Africa

**Comment by qcfourie** [comment]
Hi Earl

Just a reminder on the below. Please let me know if we can schedule a time and date to look at the issue please.

Best regards

[QFSigNew2]<http://www.qcsolutions.co.za/>











[QFQR]

Tel: +27 87 742 2500

Email: quentin@za.qcsintl.com<mailto:quentin@za.qcsintl.com>

50 Kremetart st



Direct: +27 87 742 2502

Website: www.qcsolutions.co.za<http://www.qcsolutions.co.za/>

Val de Grace



Cell: +27 83 653 6623

Skype: qcfourie

Pretoria, South Africa





From: Quentin Fourie
Sent: Monday, 30 April 2018 4:57 AM
To: snipe/snipe-it <reply@reply.github.com>; snipe/snipe-it <snipe-it@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [snipe/snipe-it] 403 Forbidden Error (#5424)

Hi Dear

Thank you for your response. Apologies for only getting back to you now. Can we arrange for any time today (Monday) please? Should we arrange for 13:00 EDT?

Thank you in advance!

Regards

[QFSigNew2]<http://www.qcsolutions.co.za/>











[QFQR]

Tel: +27 87 742 2500

Email: quentin@za.qcsintl.com<mailto:quentin@za.qcsintl.com>

50 Kremetart st



Direct: +27 87 742 2502

Website: www.qcsolutions.co.za<http://www.qcsolutions.co.za/>

Val de Grace



Cell: +27 83 653 6623

Skype: qcfourie

Pretoria, South Africa

**Comment by qcfourie** [comment]
Thank you all very much!

**Comment by EarlRamirez** [comment]
@snipe thanks! @qcfourie I'm current on UTC -0400 timezone, I will try and be available at 22:00 (my local time) to try and help you out if this time does not work out, Sunday will be our second option; however, I will only be able to commit one hour.

**Comment by qcfourie** [comment]
Hi Earl

Thank you again for your willingness to help

Let's make it Sunday, when will you be available?

Again I appreciate you help

**Comment by EarlRamirez** [comment]
@qcfourie 1300 EDT, you can also send a message on gitter.im snipe/snipe-it

**Comment by qcfourie** [comment]
Thank you, will message you then!

**Comment by qcfourie** [comment]
Hi Earl

I'm available when you are...... thanks
