### ISSUE TITLE
Customizing the default view in /hardware

### ISSUE THREAD

**Issue by ghost** [snipe/snipe-it#5425]
#### Expected Behavior (or desired behavior if a feature request)

Customizing the default view:
What I want is very simple: When a user loggs-in into Snipe-IT and goes to /hardware, I want a different view there, and being still there, if the cookies are deleted.

-----

#### Actual Behavior

As and Admin, I can't customize the default view in /hardware. 

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [✔] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
A fresh install.
- Version of Snipe-IT you're running
`4.2.0 - build 3497`
- Version of PHP you're running
`PHP 7.0.28-0ubuntu0.16.04.1`
- Version of MySQL/MariaDB you're running
`mysql  Ver 15.1 Distrib 10.0.34-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`
- What OS and web server you're running Snipe-IT on
`Ubuntu 16.04.4 LTS`
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
https://snipe-it.readme.io/v4.2.0/docs/installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Yes.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by snipe** [comment]
I don't understand what you mean by custom view. Can you explain, and/or provide mockups?

**Comment by passboltUser** [comment]
I'd like the `Id` field to be already checked by default and would like to move my 1 custom field set, which consists of 4 new fields, to the left, next to the `Id` field, because those 4 new fields are located at the right hand side, far away from the first `Id` field.

**Comment by leebaggaley** [comment]
Hi PassboltUser -(only a bit of my advice and certainly not the views of Snipe or affiliated companies) 

I think you are taking away from what this project is (Opensource - with the dedication from Snipe), We would all like some custom features to hard code our preferences. From my experience though so far with this application, I believe you can achieve most of what you require with cookies enabled. I appreciate that when you clear your cache you would need to set this up again, but it would be near impossible to have a settings page to hard code these variables (especially with all the customization from end users). To be honest I absolutely love the way that the cookies are handled as it gives us far more scope to adjust our experience on the fly and I personally wouldn't want to have to spend ages making changes in an "admin panel" to get the desired results

**Comment by EarlRamirez** [comment]
@passboltUser are you referring to 
![image](https://user-images.githubusercontent.com/12306859/39792429-8e825cec-530e-11e8-9132-914859a13d24.png)

or actually moving the columns from left to right?

**Comment by passboltUser** [comment]
@EarlRamirez Yes, I'm referring to the picture you attached (where I want certain checkmarks to be checked by default and certain columns be on different positions by default if an user loggs in without any cookies i.e. not relying on settings being saved in cookies).

**Comment by passboltUser** [comment]
Of course it's still relevant..

**Comment by mholkesvik-r7** [comment]
I'd really like to have it.

**Comment by snipe** [comment]
I’d be willing to look at a PR for this, but I have to be honest and say this is definitely not on our development roadmap right now.

**Comment by passboltUser** [comment]
Thanks for info. Then I guess this can be staled by the bot, may someone else reply if interested.

**Comment by tohagan** [comment]
We'd also need this feature.  Thanks!

**Comment by wilkems** [comment]
Just installed Snipe IT and I would really like to reorder columns. There is certain data that I think goes better together and I'd like to have it more to the left and be able to just control the column order.

**Comment by TrishF81** [comment]
Our team just discovered Snipe IT, and we would really love the ability to move the columns around.  We have our assets displayed in a way that works for our team in Excel, and would like it to be the same in Snipe IT.

**Comment by captainlinky** [comment]
We would also like this feature implemented. It would greatly improve the products functionality.

**Comment by ChrissGuthrie** [comment]
This would be very helpful, since my custom fields -- the fields most important to me-- are far off to the right and I have to scroll across each line to access them.

**Comment by hellphish** [comment]
We'd love to be able to reorder columns. @snipe what was the bug that conflicted with another library you posted about in May '18? Is there a chance it has been fixed now?

**Comment by tomholovis** [comment]
Giving this a poke so that it doesn't go stale. The larger our Snipe usage becomes, the more custom columns are added and are set to be viewed by default. Setting a default "view" would be very helpful.

**Comment by TJucutan** [comment]
I'd like to have this as well. It'd be nice to have the Manufacturer column next to Model for example.

**Comment by j-moran** [comment]
Definitely still a relevant feature. In an enterprise environment where reports and data are essential for viewing it would be really nice to be able to organize data according to our needs.

**Comment by da64u** [comment]
Please allow columns to be reordered. I was trying to move the Checkin/Checkout box to the left side and realized this limitation.

**Comment by bcourtade** [comment]
Being able to set a default column selection would be nice.  Currently the first step in our documentation for new users is for them to click the column box and uncheck all of the extra fields we've added so that check-in/check-out fits on the screen.

**Comment by viclou** [comment]
+1 FD14082

**Comment by wfillmer** [comment]
The ability to re-order the columns on the "All Assets" view would be a fantastic improvement.

**Comment by Puddl36lum** [comment]
+1

**Comment by skizznat** [comment]
AssetTiger, which appears to be using Snipe-IT as their platform, has overcome the column arrangement limitation that appears to continue to vex the Snipe-IT devs.  Not trying to steer folks to AT but just saying that it's possible to fix the problem.

**Comment by PartTimeJS** [comment]
A bump for implementing this, please.

**Comment by Tezameru** [comment]
+1 as well. Still needed.

**Comment by jackhartnett** [comment]
+1 I would love this feature.  It would make life much easier for our end users checking in and out devices.

**Comment by teamuppolska** [comment]
Yep, important feature

**Comment by PetriAsi** [comment]
Yes, we need this

**Comment by chais0n** [comment]
This is still needed

**Comment by K-Sugar** [comment]
Would be very interested in the feature as well, as some things make more sense when standing next to each other

**Comment by ysdndev** [comment]
+1 Would be a very useful feature

**Comment by fernadie** [comment]
+1

**Comment by kevinjclear** [comment]
**+1** 

We just adopted SnipeIT and would love to have some of our custom headers along with the Check-in/Check-out button rearranged closer to the first few columns for ease of use.

**Comment by miicah** [comment]
As above, we would love to have the check-in/check-out button on the left, right now our only option is to just remove a lot of data from the view until we don't have to scroll sideways to see it.

**Comment by Prodeguerriero** [comment]
One-upping this one as well. Being able to define organize columns and save a "default" layout that applies everywhere would be very nice.

**Comment by rschitz** [comment]
+1

**Comment by roland-x83** [comment]
+1

**Comment by sylvank** [comment]
Also support customizing default visibility of columns and rearranging them. Should be saved as a user preference.

**Comment by DoK44** [comment]
+1

**Comment by lukascaplikas** [comment]
+1

**Comment by guiluxdj** [comment]
+1
maybe an idea with **https://bootstrap-table.com/docs/extensions/reorder-columns/**

<blockquote><div><strong><a href="https://bootstrap-table.com/docs/extensions/reorder-columns/">Table Reorder Columns · Bootstrap Table</a></strong></div><div>Table Reorder Columns extension of Bootstrap Table.</div></blockquote>

**Comment by snipe** [comment]
> maybe an idea with https://bootstrap-table.com/docs/extensions/reorder-columns/

Once again, as we stated elsewhere, the last time we checked with that specific library, it directly conflicted with other libraries we were using. 

<blockquote><div><strong><a href="https://bootstrap-table.com/docs/extensions/reorder-columns/">Table Reorder Columns · Bootstrap Table</a></strong></div><div>Table Reorder Columns extension of Bootstrap Table.</div></blockquote>

**Comment by hellphish** [comment]
Have these conflicts been reported to the developers?

**Comment by snipe** [comment]
A long time ago, yes.

**Comment by cstout1** [comment]
+1 here as well.

**Comment by stefvp** [comment]
+1 for this feature..
recently it seems like the cookie is not saved anymore on my system? so literally everytime I switch from asset to license or any other page I have to re-check and un-check all the boxes I need...
reproduced this behaviour in edge, firefox and brave browser.

**Comment by snipe** [comment]
@Mi3czy - This has been fixed in 5.4.2, per the release notes. 

To the OP, it’s unlikely that storing column preferences in the database (aka not in cookies) is going to make the short term roadmap any time soon.

**Comment by gertz22** [comment]
HI in our company also, looking for reorder feature. Like manufactorer and model..

**Comment by Tyree** [comment]
Absolutely, 100% agree this is a must-have. The order of the columns make no sense. Why can't the sorting in the custom fieldset be used in the column ordering??? Why is this a cookie-dependent feature? How is the fieldset order stored? Couldn't the same data be used for the column order?

**Comment by hpham93** [comment]
+1 for this feature

**Comment by ghost** [comment]
+1 on reorder columns, would be really important to us!

**Comment by davisrael** [comment]
+1 - especially since adjusting a large list of column's visibility currently seems broken (= not stored). Additionally, upon completion, nginx bails out with a
"header or cookie size too large". Deleting cookies is the only way of solving this.
Did anyone maybe have a look at the cookie structure - some manual tweaks that could pre-set a column visibility status?
Best :)

**Comment by SGLurker** [comment]
Great software! Love it! 
Workaround for me is to edit /app/Presenters/AssetPresenter.php
Amend the fields that you want to "uncheck" during the initial loading of the page.
Change "visible" => true, to "visible" => false
When the page load, the layout will be based on all "visible = true" fields.

**Comment by carsonh4te** [comment]
+1 for reorder columns

**Comment by ryassuda** [comment]
+1

**Comment by tntmario** [comment]
+1

**Comment by carlyle9** [comment]
+1

**Comment by snipe** [comment]
You can switch to `localStorage` in your env for `BS_TABLE_STORAGE` for remembering the columns that are shown there. That will persist in the browser beyond cookie deletion. https://snipe-it.readme.io/docs/configuration#optional-session-settings

We do not have any plans on implementing a database-backed version of that at this time.

<blockquote><img src="https://snipe-it.readme.io/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuration#optional-session-settings">Configuration</a></strong></div><div>This section is where you edit the Snipe-IT configuration file to reflect your own settings, such as your database credentials, mail server, preferred language, timezone, and so on. Some of the settings are optional, some are required.Don't be intimidated by the length of this page. The configuratio...</div></blockquote>

**Comment by carlyle9** [comment]
I am interested in the reordering of columns, that option doesn't appear to be supported for any configuration at this time.

**Comment by snipe** [comment]
As discussed in other GH issues, the javascript library we use has a bug in the re-ordering extension which causes conflicts with the other table features. If they ever get that fixed, we'll add it.

**Comment by nickMLB** [comment]
Could you share a link to this issue of the javascript library? Maybe we could upvote or +1 is as well?

**Comment by TieuBao1606** [comment]
Hello everyone, I am a new user with the same desire as you.

During the search process, I tried to find a way to change the order of the fields in the AssetPresenter.php file ( /var/www/html/app/Presenters/)

Result: I have changed the positions that I expected. However, with only one person, I cannot evaluate all the possible errors, can you try and give me some advice?
P/s: You should backup the AssetPresenter.php file before making any changes so that you can Rollback it back to its original state

![After](https://github.com/user-attachments/assets/24608e1d-1ef3-4986-8ca9-55f0bb213408)
![Before](https://github.com/user-attachments/assets/db2d4bb6-5dd6-4755-bcd1-577069638b2b)

**Comment by BSKilglass** [comment]
+1

**Comment by gilachateam** [comment]
We really need this!

All assets, wich is the most important thing on this system should have selectable buttons or a combo, with any Category created, and each category should have custom column order and permision,, is no the same a PC , than a printer, this should be showed different for each category.

**Comment by jamjarae** [comment]
This would be great but at the very least could we have the Custom Fields sortable as they currently appear in the order they were added.

Custom Fields within Fieldsets are sortable but I'm talking about the Custom Fields list itself.

**Comment by AB-131015** [comment]
I would also like this

**Comment by geekguidance** [comment]
Has the JS library bug that prevents this feature from working correctly ever been corrected? I would love to be able to move the columns into a more cohesive order. I saw some possibly work arounds for on-prem users. Are there any work arounds for hosted users?
