### ISSUE TITLE
How to add/link sub-assets to an asset under /hardware/417#assets

### ISSUE THREAD

**Issue by passboltUser** [snipe/snipe-it#5426]
#### Expected Behavior (or desired behavior if a feature request)

I have a notebook and want to link a docking station to it, so that when I go to that specific notebook, I can see sub-assets that belong to this notebook. Would that be under /hardware/ID#assets ?

-----

#### Actual Behavior

I thought it might be under /hardware/417#assets (417 is that specific notebook), where I could add/link assets (like a docking station) what would belong to this notebook, but unfortunately I don't see any Add button there. I couldn't find any assets under https://snipeitapp.com/demo which would list any sub-assets under /hardware/ID#assets either.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [✔] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
A fresh install.
- Version of Snipe-IT you're running
`4.2.0 - build 3497`
- Version of PHP you're running
`PHP 7.0.28-0ubuntu0.16.04.1`
- Version of MySQL/MariaDB you're running
`mysql  Ver 15.1 Distrib 10.0.34-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`
- What OS and web server you're running Snipe-IT on
`Ubuntu 16.04.4 LTS`
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
https://snipe-it.readme.io/v4.2.0/docs/installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by leebaggaley** [comment]
You simply need to assign an asset to an asset, i.e create a new asset for "Docking Station" then check out that asset to the notebook - Thats assuming you want to track the docking station as an asset, you can create a new component "Docking Station" and add that to the said asset. Once you assign the component or asset to the original asset it will be visible

![image](https://user-images.githubusercontent.com/37484200/39273436-b2abfe12-48d6-11e8-8edd-540bc1ce8f83.png)
