### ISSUE TITLE
Feature request: force SSL in Laravel app

### ISSUE THREAD

**Issue by back-2-95** [snipe/snipe-it#5428]
#### Expected Behavior (or desired behavior if a feature request)

Laravel app should force SSL if app url is set to https://.....

So something like below with if clause (if APP_URL starts with https).

```
namespace App\Providers;

use Illuminate\Support\Facades\URL;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {
        URL::forceScheme('https');
    }
```

**Comment by snipe** [comment]
Laravel uses https if the APP_URL is set to https - but there are particular configurations that can complicate things, specifically if you're running behind a proxy or if your virtualhost SSL setting isn't configured correctly. 

You can always uncomment the [htaccess rules](https://snipe-it.readme.io/docs/security#section-additional-security) we provide to force https connections.

**Comment by back-2-95** [comment]
Hi,

I have APP_URL set to https, but css and js files get http URLs.

And we have nginx-proxy in the front. Is there some recommended nginx confs for this kind of scenario?

**Comment by chrkaatz** [comment]
We have the same issue. I did not see why this have been closed here.
