### ISSUE TITLE
Possible Bug - Category widget/form on dashboard spilling over

### ISSUE THREAD

**Issue by leebaggaley** [snipe/snipe-it#5431]
#### Expected Behavior (or desired behavior if a feature request)

Dashboard category widget displays properly

-----

#### Actual Behavior

Dashboard widget is spilling over the "View All" button into the footer. Tested in Chrome, IE & Edge

![image](https://user-images.githubusercontent.com/37484200/39271472-112b3be8-48d1-11e8-9ee3-762b380d21e4.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode  -- Yes
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) - Yes

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running 4.2.0 - (3508 Master)
- Version of PHP you're running 7.0.28-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running 
- What OS and web server you're running Snipe-IT on Ubuntu/Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Git
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error None
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Dashboard
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. Same in Demo
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by cslucian** [comment]
I had the same issue. It seems that is a forgotten div in the /resources/views/dashboard.php
At Categories section I have put:

 **_<div class="table-responsive">_**
            <div class="col-md-12">
                        <table
                                data-cookie-id-table="dashCategorySummary"
                                data-height="400"
                                data-side-pagination="server"
                                data-sort-order="desc"
                                data-sort-field="assets_count"
                                id="dashCategorySummary"
                                class="table table-striped snipe-table"
                                data-url="{{ route('api.categories.index', ['sort' => 'assets_count', 'order' => 'asc']) }}">

                            <thead>
                            <tr>
                                <th class="col-sm-3" data-visible="true" data-field="name" data-formatter="categoriesLinkFormatter" data-sortable="true">{{ trans('general.name') }}</th>
                                <th class="col-sm-3" data-visible="true" data-field="category_type" data-sortable="true">{{ trans('general.type') }}</th>
                                <th class="col-sm-1" data-visible="true" data-field="assets_count" data-sortable="true"><i class="fa fa-barcode"></i></th>
                                <th class="col-sm-1" data-visible="true" data-field="accessories_count" data-sortable="true"><i class="fa fa-keyboard-o"></i></th>
                                <th class="col-sm-1" data-visible="true" data-field="consumables_count" data-sortable="true"><i class="fa fa-tint"></i></th>
                                <th class="col-sm-1" data-visible="true" data-field="components_count" data-sortable="true"><i class="fa fa-hdd-o"></i></th>
                            </tr>
                            </thead>
                        </table>
                    **_</div>_**

For it worked! 

Best Regards,

**Comment by leebaggaley** [comment]
Thanks, ill give it a try

**Comment by leebaggaley** [comment]
Seems to relate to https://github.com/snipe/snipe-it/issues/5453
