### ISSUE TITLE
Feature request: make everything Requestable

### ISSUE THREAD

**Issue by DokH** [snipe/snipe-it#5435]
#### Desired behavior

Make licenses, consumable, accessories, components also requestable.
That way one can create an IT internal web shop for ones users without having to go with a separate eCommerce webshop solution.

**Comment by x3inspire** [comment]
Yes, vote for it.
Right now only asset can be requested.  Accessories, Consumables, Components should be able requested like Asset too. Example i want to put like keyboard under accessories, toner under consumables.  So this item must be requested by user.
