### ISSUE TITLE
Assigning multiple custom field sets to models?

### ISSUE THREAD

**Issue by passboltUser** [snipe/snipe-it#5436]
#### Expected Behavior (or desired behavior if a feature request)

I have 1 custom field set, called "OL", so going to `/fields` or clicking this specific field set (`/fields/fieldsets/3`), I and others would know, which fields come from another program. Now I would like to add an additional field called "Product number", but I wouldn't like to edit the OL set because the OL program doesn't contain a "Product number" field. It is possible to assign multiple custom field sets to models instead of e.g. editing the "OL" set and adding "Product number" to it? Maybe it would have other benefits too.

-----

#### Actual Behavior

I went to `/fields`, created a second field set with only one field called "Product number" and tried to edit a model and add that second field set next to the already assigned "OL" field set. Unfortunately I can only chose either one, so either "OL" or "Product number", and unfortunately not both. 

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [✔] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
A fresh install.
- Version of Snipe-IT you're running
`4.2.0 - build 3497`
- Version of PHP you're running
`PHP 7.0.28-0ubuntu0.16.04.1`
- Version of MySQL/MariaDB you're running
`mysql  Ver 15.1 Distrib 10.0.34-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`
- What OS and web server you're running Snipe-IT on
`Ubuntu 16.04.4 LTS`
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
https://snipe-it.readme.io/v4.2.0/docs/installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Yes.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by EarlRamirez** [comment]
@passboltUser this would be a feature request because this is not the behaviour of the Field Set

**Comment by snipe** [comment]
It's not possible to associate multiple field sets to a model, but you can always create a new model that has all of the fields you need.
