### ISSUE TITLE
Asset statuses

### ISSUE THREAD

**Issue by david-vernon** [snipe/snipe-it#544]
Similar to Issue #527, if I create an asset with a status of Pending AND assign it to a user during creation, then there is a deployed asset with status_id = Pending. So it shows up in Deployed Assets, but has no check in/out button. Maybe the answer is, "don't do that." 

Is this the expected behavior? Do most people add a "Deployed" status to set Deployed Devices to?

Thanks!

**Comment by snipe** [comment]
Hmm... let me take a look. If it's not an actual bug, it's at the very least a dumb UI thing that should be addressed.

![bill murray face](https://cloud.githubusercontent.com/assets/197404/6277102/b350d2ae-b840-11e4-9a2b-f886435f4980.gif)

**Comment by snipe** [comment]
I think at the very least it should give you an error if you try to check out a pending asset to a person. Nothing should be checked out to someone unless its status is deployable.

**Comment by david-vernon** [comment]
Yes, and you shouldn't be able to edit the status of a deployed device to a status with type other than Deployable.

**Comment by snipe** [comment]
In 2.0, you won't be able to edit the status of an asset that's been checked out.
