### ISSUE TITLE
Issue with Docker Documentation

### ISSUE THREAD

**Issue by iStatiK** [snipe/snipe-it#5445]
**This is for others in case they experience this issue.**  

I am migrating our system to Docker.  While running through the documentation in the Docker section, I was at the point to run the final docker container using this:

> docker run -d -p YOUR_PORT_NUMBER:80 --name="snipeit" --link snipe-mysql:mysql --env-file=my_env_file --mount source=snipe-vol,dest=/var/lib/snipeit snipe/snipe-it

but kept receiving this error:

> invalid argument "source=snipesql-vol,dest=/var/lib/snipeit" for "--mount" flag: unexpected key 'dest' in 'dest=/var/lib/snipeit'
> See 'docker run --help'.

Upon further investigation, I discovered the issue was with the "dest" portion as you can tell from the error.  According to their documentation at[https://docs.docker.com/storage/bind-mounts/]( https://docs.docker.com/storage/bind-mounts/), the correct syntax is 

> destination, dst, or target

So, after changing the syntax to this, I was able to successfully run the command.

> docker run -d -p YOUR_PORT_NUMBER:80 --name="snipeit" --link snipe-mysql:mysql --env-file=my_env_file --mount source=snipe-vol,**dst**=/var/lib/snipeit snipe/snipe-it

**Comment by snipe** [comment]
@uberbrady can you fix please?

**Comment by uberbrady** [comment]
Wonderful catch, thank you so much!

**Comment by uberbrady** [comment]
Fixed on both 4.2 and 5.0 branches.
