### ISSUE TITLE
install SnipeIT on windows 10

### ISSUE THREAD

**Issue by elpijitigakilo** [snipe/snipe-it#5449]
i already follow this step https://snipe-it.readme.io/docs/wamp
but i got error 500

any suggestion for help me to solve this issue? 

my environment is
windows 10 latest patch 
apache 2.4.33
php 7.0.29
mysql 5.7.21
mariaDB 10.2.14
wampserver 3.1.3 32bit

i just install it and not install anything. 
please help if i'm wrong

error list
::1 - - [30/Apr/2018:09:43:21 +0700] "GET /index.php?img=pngFolderGo HTTP/1.1" 200 694
::1 - - [30/Apr/2018:09:43:21 +0700] "GET /index.php?img=pngWrench HTTP/1.1" 200 741
::1 - - [30/Apr/2018:09:43:21 +0700] "GET /index.php?img=pngFolder HTTP/1.1" 200 850
::1 - - [30/Apr/2018:09:43:21 +0700] "GET /index.php?img=gifLogo HTTP/1.1" 200 4549
::1 - - [30/Apr/2018:09:43:21 +0700] "GET /index.php?img=pngPlugin HTTP/1.1" 200 548
::1 - - [30/Apr/2018:09:43:29 +0700] "GET / HTTP/1.1" 200 5565
::1 - - [30/Apr/2018:09:43:29 +0700] "GET /index.php?img=pngFolderGo HTTP/1.1" 200 694
::1 - - [30/Apr/2018:09:43:29 +0700] "GET /index.php?img=pngFolder HTTP/1.1" 200 850
::1 - - [30/Apr/2018:09:43:29 +0700] "GET /index.php?img=pngWrench HTTP/1.1" 200 741
::1 - - [30/Apr/2018:09:43:29 +0700] "GET /index.php?img=pngPlugin HTTP/1.1" 200 548
::1 - - [30/Apr/2018:09:43:29 +0700] "GET /index.php?img=gifLogo HTTP/1.1" 200 4549
172.18.1.151 - - [30/Apr/2018:10:06:08 +0700] "GET /currentsetting.htm HTTP/1.1" 500 20781
172.18.1.151 - - [30/Apr/2018:10:50:56 +0700] "GET /currentsetting.htm HTTP/1.1" 404 304
172.22.19.177 - - [30/Apr/2018:12:13:34 +0700] "GET / HTTP/1.1" 200 956
172.22.19.177 - - [30/Apr/2018:12:14:34 +0700] "-" 408 -
172.22.19.177 - - [30/Apr/2018:12:14:34 +0700] "-" 408 -
172.22.19.177 - - [30/Apr/2018:12:19:13 +0700] "GET / HTTP/1.1" 500 20781

**Comment by snipe** [comment]
We need info from your app logs, as we originally requested in the GH issue template.
