### ISSUE TITLE
Issue: Asset by status

### ISSUE THREAD

**Issue by meyerf99** [snipe/snipe-it#5454]
Hey Snipe-IT Dev Team

I found an issue with the dashboard "Asset by status".
We have "deployed some of our devices but in the dashboard i see only "ready to deploy".
When i look on "All Deployed", i see this deployed asset but with status label "ready to deploy" in blue.

Is this a bug?
![snipe-it status](https://user-images.githubusercontent.com/28959963/39431955-931b4e6c-4c92-11e8-9adf-5284e87f8eef.PNG)
![snipe-it status_1](https://user-images.githubusercontent.com/28959963/39431958-972aeda0-4c92-11e8-8bc9-1471894aa725.PNG)
![snipe-it status_2](https://user-images.githubusercontent.com/28959963/39431961-9a3eeb40-4c92-11e8-9b69-3d59e3f5c3a4.PNG)

**Comment by leebaggaley** [comment]
Hi, I believe that you would need to manually change the status of the asset (after checking out). When checking out an asset there is no current way to change the status so it will retain the current status but will be "tagged" with the metadata of deployed. I.E (If I have an asset in status ready to deploy, when you check out this asset, it will still have the status of "Ready To Deploy" but the meta data will display as deployed. 

Currently you will need to change the status of the deployed item to whatever is required separately (Deployed) etc... I think a feature request will need to be added to change status on check-out (its something I could also do with)

**Comment by leebaggaley** [comment]
Added a feature request https://github.com/snipe/snipe-it/issues/5462

**Comment by EarlRamirez** [comment]
@meyerf99 you did not complete the questions that are required; therefore, it is not easy to determine if it is a bug or not, I am not able to reproduce what you are seeing.

**Comment by meyerf99** [comment]
@EarlRamirez We have a lot assets that are in status "deployed (blue icon)". On the main site (dashboard) i see only "pending" and "ready to deploy" status and not "deployed. 
All deployed assets have been added to Ready to Use status

Maybe you know now what i mean or my problem is.

**Comment by meyerf99** [comment]
@snipe Is this a bug or a feature request?

**Comment by klluedtke** [comment]
I am seeing this same issue. Most of our devices are checked out and Deployed. Yet on the dashboard it shows Ready to Deploy which is including Deployed. But what I am looking for is to see how many assets of a certain model that are available to check out at any time.

**Comment by brandonbelisle** [comment]
This is a bug. My installation also has the same issue. In fact even when I edit the asset I cannot set it to "Deployed" status as there is no "Deployed" status.

**Comment by leebaggaley** [comment]
I believe it uses the actual status rather than the meta status (Pending, deployed etc...) I have over 1000 assets all displaying correctly, just need to make sure the status is changed manually after checkout

![image](https://user-images.githubusercontent.com/37484200/42572752-13bcfbbc-8512-11e8-8d2d-18d13ee290da.png)

**Comment by leebaggaley** [comment]
@brandonbelisle you need to create the required statuses in settings first, I use these statuses to break down my assets into lists as per my image above

**Comment by ernestasen** [comment]
It's still relevant

**Comment by meyerf99** [comment]
@snipe Any news?

**Comment by tymik** [comment]
I also wanted to report the bug - in my case checking out asset does change it's meta state to deployed (from green to blue dot), but "status" remains unchanged.
The solution for that, as I see it, would be to add dropdown menu with status (currently not available), for single and bulk checkout, with "deployed" or "in use" selected by default and ability to change status if someone would need different status when asset is deployed.

**Comment by tymik** [comment]
It's still relevant

**Comment by Robert-Azelis** [comment]
Yes, it still relevant, missing meta status **Deployed** on chart. Please add option under _**Deployable setting**_ to select if meta status **Deployed** should be shown on chart.

**Comment by burrows7li** [comment]
It's still relevant
