### ISSUE TITLE
snipe-it docker installation error

### ISSUE THREAD

**Issue by dmongan1** [snipe/snipe-it#5458]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)
docker run -d -p YOUR_PORT_NUMBER:80 --name="snipeit" --link snipe-mysql:mysql --env-file=/etc/my_env_file --mount source=snipe-vol,dest=/var/lib/snipeit snipe/snipe-it

expect no errors
-----

#### Actual Behavior

(what actually happens goes here)

-----invalid argument "source=snipe-vol,dest=/var/lib/snipeit" for "--mount" flag: unexpected key 'dest' in 'dest=/var/lib/snipeit'
See 'docker run --help'.

The previous steps ran ok.
docker run --name snipe-mysql --env-file=/etc/my_env_file --mount source=snipesql-vol,target=/var/lib/mysql -d -P mysql:5.6

docker run --rm snipe/snipe-it

edited /etc/my_env_file

MYSQL_ROOT_PASSWORD=passwd1
MYSQL_DATABASE=snipeit
MYSQL_USER=snipeit
MYSQL_PASSWORD=passwd2

# Email Parameters
# - the hostname/IP address of your mailserver
MAIL_PORT_587_TCP_ADDR=smtp.whatever.com
#the port for the mailserver (probably 587, could be another)
MAIL_PORT_587_TCP_PORT=587
# the default from address, and from name for emails
MAIL_ENV_FROM_ADDR=youremail@yourdomain.com
MAIL_ENV_FROM_NAME=Your Full Email Name
# - pick 'tls' for SMTP-over-SSL, 'tcp' for unencrypted
MAIL_ENV_ENCRYPTION=tcp
# SMTP username and password
MAIL_ENV_USERNAME=your_email_username
MAIL_ENV_PASSWORD=your_email_password

# Snipe-IT Settings
APP_ENV=production
APP_DEBUG=false
APP_KEY=base64:cFOSODxTh//mOf2XTeWSSWUWCZ/fvEDiUY9geSUM6rY=
APP_URL=http://127.0.0.1:80
APP_TIMEZONE=US/Central
APP_LOCALE=en

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
no
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
yes
-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?   fresh install
- Version of Snipe-IT you're running  followed instructions from https://snipe-it.readme.io/v4.2.0/docs/docker
- Version of PHP you're running      Container image
- Version of MySQL/MariaDB you're running   Container image
- What OS and web server you're running Snipe-IT on     Redhat 7.5
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)   docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error    N/A
- If a stacktrace is provided in the error, include that too.   N/A
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by cringer** [comment]
This is a docker error and it says right at the top the error.
`invalid argument "source=snipe-vol,dest=/var/lib/snipeit" for "--mount" flag: unexpected key 'dest' in 'dest=/var/lib/snipeit'`

If you look at the docks for volumes you will note the valid keys are destination, dst, or target
https://docs.docker.com/storage/volumes/#choose-the--v-or---mount-flag

Moreso if you look at the example you are trying to copy you'd notice you have a typo.  From the document.  https://snipe-it.readme.io/v4.2.0/docs/docker

`docker run -d -p YOUR_PORT_NUMBER:80 --name="snipeit" --link snipe-mysql:mysql --env-file=my_env_file --mount source=snipe-vol,dst=/var/lib/snipeit snipe/snipe-it`

**Comment by dmongan1** [comment]
syntax in documentation is incorrect.     dest=    should be   dst=
