### ISSUE TITLE
CSV User Import - Blank line

### ISSUE THREAD

**Issue by madd15** [snipe/snipe-it#546]
If there is a blank line on the end of the csv file then it causes an undefined offset error when it tries to process the line.

![alt](http://i.imgur.com/empfYOF.png)

**Comment by madd15** [comment]
Could possibly add `if (isset($row[2]))` to check if email is set before checking for existing user. Might also allow for returning user not added no email provided.

**Comment by snipe** [comment]
Used `array_key_exists` :)

**Comment by madd15** [comment]
Okay even better
