### ISSUE TITLE
User photo from ActiveDirectory

### ISSUE THREAD

**Issue by RealEnder** [snipe/snipe-it#5464]
AcviveDirectory can hold user photo inside and a lot of organizations use it as part of their HR process.
Since Snipe-it users can upload their own avatars, it will be nice feature to pull photo from AD, when using that auth option.

**Comment by brewinlibrarian** [comment]
+1

**Comment by samotelf** [comment]
+1

**Comment by snazy2000** [comment]
+1

**Comment by LordMessi** [comment]
+1

**Comment by Gauva1n** [comment]
+1
