### ISSUE TITLE
Search not working for the list view of users displayed in Accessory

### ISSUE THREAD

**Issue by Raj22223** [snipe/snipe-it#5471]
#### Please confirm you have done the following before posting your bug report:

**Describe the bug**
Search not working for the list view of users displayed in Accessory

**Expected behavior**
When we look for any user in a search bar it should pick the user in the list, but nothing happens when we search.

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

- Version of Snipe-IT you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- If you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproduceable on the demo.
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)

**Comment by Raj22223** [comment]
- Version of Snipe-IT you're running
**Version v4.3.0 - build 3559 (master)**
- What OS and web server you're running Snipe-IT on
**Windows server 2012**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
**Through Git hub desktop Application**
- If you're getting an error in your browser, include that error
**No error**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
**Page : snipe-it/public/accessories/1 ( Here search is not working)**
- If a stacktrace is provided in the error, include that too.
**No**
- Any errors that appear in your browser's error console.
**No**
- Confirm whether the error is reproduceable on the demo.
**NA**
- Include any additional information you can find in app/storage/logs and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

**Comment by Raj22223** [comment]
@snipe image attached for better understanding.

![image](https://user-images.githubusercontent.com/34770213/39922900-1076073a-553f-11e8-828b-91dd1b56af1e.png)

**Comment by aadrina** [comment]
Search function in accessories, components and consumables for user or asset in our system also not working...

**Comment by Raj22223** [comment]
@snipe could you check the above screen shot posted to understand about the issue. Thanks

**Comment by inietov** [comment]
I like this. I'm starting getting this to work right now.

**Comment by inietov** [comment]
Can't reproduce the error :(

**Comment by snipe** [comment]
@inietov this is reproducible on the demo. 

https://demo.snipeitapp.com/accessories/1
<img width="1047" alt="screen shot 2018-08-02 at 7 32 04 pm" src="https://user-images.githubusercontent.com/197404/43621145-cd6f3532-968a-11e8-9f30-2ceb99f1c35a.png">

The functionality to search on assigned users was never built.
