### ISSUE TITLE
Assett import fails

### ISSUE THREAD

**Issue by 3starmick** [snipe/snipe-it#5473]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I try import an asset csv from GUI and CLI, and both fail with:

php artisan snipeit:import /home/barry/AssetsAMS.csv
======= Importing Items from /home/barry/AssetsAMS.csv =========
 34/34 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%The following Errors were encountered.
Error: Item: 13-inch MacBook Pro Early 2015 failed validation: {"Asset Model \"13-inch MacBook Pro Early 2015\"":{"category_id":["The category id field is required."],"manufacturer_id":["The manufacturer id field is required."]}}
Error: Item: AMS00013 failed validation: {"Asset \"AMS00013\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: 13-inch MacBook Pro (Early 2015) failed validation: {"Asset Model \"13-inch MacBook Pro (Early 2015)\"":{"category_id":["The category id field is required."],"manufacturer_id":["The manufacturer id field is required."]}}
Error: Item: AMS00014 failed validation: {"Asset \"AMS00014\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: 15-inch Retina MacBook Pro with TouchID (Late 2016) failed validation: {"Asset Model \"15-inch Retina MacBook Pro with TouchID (Late 2016)\"":{"category_id":["The category id field is required."],"manufacturer_id":["The manufacturer id field is required."]}}
Error: Item: AMS00015 failed validation: {"Asset \"AMS00015\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: 15-inch Retina MacBook Pro (Mid 2012) failed validation: {"Asset Model \"15-inch Retina MacBook Pro (Mid 2012)\"":{"category_id":["The category id field is required."],"manufacturer_id":["The manufacturer id field is required."]}}
Error: Item: AMS00084 failed validation: {"Asset \"AMS00084\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00097 failed validation: {"Asset \"AMS00097\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00098 failed validation: {"Asset \"AMS00098\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00106 failed validation: {"Asset \"AMS00106\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: 13-inch Retina MacBook Pro (Late 2012) failed validation: {"Asset Model \"13-inch Retina MacBook Pro (Late 2012)\"":{"category_id":["The category id field is required."],"manufacturer_id":["The manufacturer id field is required."]}}
Error: Item: AMS00142 failed validation: {"Asset \"AMS00142\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: 15-inch Retina MacBook Pro (Late 2013) failed validation: {"Asset Model \"15-inch Retina MacBook Pro (Late 2013)\"":{"category_id":["The category id field is required."],"manufacturer_id":["The manufacturer id field is required."]}}
Error: Item: AMS00151 failed validation: {"Asset \"AMS00151\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00152 failed validation: {"Asset \"AMS00152\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00193 failed validation: {"Asset \"AMS00193\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00224 failed validation: {"Asset \"AMS00224\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: 15-inch Retina MacBook Pro (Mid 2015) failed validation: {"Asset Model \"15-inch Retina MacBook Pro (Mid 2015)\"":{"category_id":["The category id field is required."],"manufacturer_id":["The manufacturer id field is required."]}}
Error: Item: AMS00249 failed validation: {"Asset \"AMS00249\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00250 failed validation: {"Asset \"AMS00250\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00253 failed validation: {"Asset \"AMS00253\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00254 failed validation: {"Asset \"AMS00254\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00255 failed validation: {"Asset \"AMS00255\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00257 failed validation: {"Asset \"AMS00257\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: 15-inch Retina MacBook Pro with TouchID (Mid 2017) failed validation: {"Asset Model \"15-inch Retina MacBook Pro with TouchID (Mid 2017)\"":{"category_id":["The category id field is required."],"manufacturer_id":["The manufacturer id field is required."]}}
Error: Item: AMS00260 failed validation: {"Asset \"AMS00260\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00261 failed validation: {"Asset \"AMS00261\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00265 failed validation: {"Asset \"AMS00265\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00266 failed validation: {"Asset \"AMS00266\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00268 failed validation: {"Asset \"AMS00268\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: 13-inch Retina MacBook Pro with TouchID (Mid 2017) failed validation: {"Asset Model \"13-inch Retina MacBook Pro with TouchID (Mid 2017)\"":{"category_id":["The category id field is required."],"manufacturer_id":["The manufacturer id field is required."]}}
Error: Item: AMS00269 failed validation: {"Asset \"AMS00269\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00270 failed validation: {"Asset \"AMS00270\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00271 failed validation: {"Asset \"AMS00271\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00272 failed validation: {"Asset \"AMS00272\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00273 failed validation: {"Asset \"AMS00273\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00274 failed validation: {"Asset \"AMS00274\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00275 failed validation: {"Asset \"AMS00275\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00276 failed validation: {"Asset \"AMS00276\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00276 (3) failed validation: {"Asset \"AMS00276 (3)\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: AMS00278 failed validation: {"Asset \"AMS00278\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}
Error: Item: BER00258 failed validation: {"Asset \"BER00258\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}

**To Reproduce**

**Expected behavior**
Assets are uploaded.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v4.3.0  build 3559
 - OS: [e.g. Ubuntu, CentOS] Ubuntu
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version  7.2.3-1ubuntu1

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS
 - Browser [e.g. chrome, safari] Firefox

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? Fresh
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) GIT
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by 3starmick** [comment]
Just to clarify, no assets are imported.

**Comment by snipe** [comment]
@3starmick Did you try it using the template we provide in the documentation? Based on those errors, it looks like you're missing some fields. https://snipe-it.readme.io/docs/importing

**Comment by 3starmick** [comment]
I've also tested with the sample csv from Snipe-IT, and that works (glad I backed up my DB! 😂 )
I've removed the data from the sample, and added, my own, but the same thing happens.

**Comment by 3starmick** [comment]
I even mapped everything correctly (or so I thought) in the web GUI.

**Comment by 3starmick** [comment]
<img width="575" alt="screen shot 2018-05-03 at 17 16 31" src="https://user-images.githubusercontent.com/38954775/39585780-d1989248-4ef5-11e8-8d71-88c65f4a6113.png">

**Comment by 3starmick** [comment]
I even tried it with all the template csv fields

**Comment by snipe** [comment]
You're missing a bunch of fields there.

**Comment by 3starmick** [comment]
I thought the blank entry was odd too. I don't have any blank Assets. Could it be the formatting somehow changing?

<img width="1097" alt="screen shot 2018-05-03 at 17 39 46" src="https://user-images.githubusercontent.com/38954775/39587105-ff91ba6e-4ef8-11e8-8474-e7930fa4f794.png">

**Comment by snipe** [comment]
You need columns and values for all of the fields that are marked as required in the documentation. Model names, categories, etc.

**Comment by 3starmick** [comment]
I thought that was the case, but the template (which works) has blank cells. I'll try with data in all the cells.

**Comment by snipe** [comment]
Not all of the fields in the sample are required - the ones that are required are marked as such in the documentation.

**Comment by 3starmick** [comment]
Yes, but I have all of them. I just put data in all the cells, so I have all the fields (in the template, just to be sure), with data, and it still fails. I had read the docs quite extensively, so I am aware of that. I can imagine how annoying it is when people dont read it, but I have,

**Comment by 3starmick** [comment]
Ok, so I have redone it again, and it has worked. The assett tag column was looked populated but wasnt. Thanks for your help|!

**Comment by mankdhodi** [comment]
Hi Team, Everytime i fetch asset from the csv file, it misses on the checked out to field and it turns out to be blank..I have also tried to map checked out to field with full name it converts the asset into user in the checked out to column and makes new entry of an user in the people section in navigation tree....It will be great if you can tell me the proper field name for this to map it to snipe/IT...
