### ISSUE TITLE
Timezone not being correctly loaded from .env or config file

### ISSUE THREAD

**Issue by HirtLocker128** [snipe/snipe-it#5474]
#### Please confirm you have done the following before posting your bug report:

- [ X ] I have enabled debug mode 
- [ X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
We set the timezone in .env file to be "America/New_York" but all timestamps still appear as UTC. We have also tried changing the default in app/config.php to EST but still does not work.

**Expected behavior**
Any actions moving forward will record timestamps in EST instead of UTC

**Server (please complete the following information):**
 - Snipe-IT Version 4.2.0
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version: 7.0

**Error Messages**
None

**Comment by snipe** [comment]
Did you clear your config cache when you changed it? (Don't change the config files.)

**Comment by HirtLocker128** [comment]
Yes, ran "php artisan config:cache"

**Comment by HirtLocker128** [comment]
New records are still being created in UTC no matter which way we try.

**Comment by Mynty100** [comment]
make sure run php artisan config:clear not config:cache

http://php.net/manual/en/timezones.php

I also edited php,ini to reflect the change. Mine is set to Australia/Brisbane and working.

**Comment by HirtLocker128** [comment]
@Mynty100 That worked! Thank you!
