### ISSUE TITLE
Custom Fields for Asset Model

### ISSUE THREAD

**Issue by bud313** [snipe/snipe-it#5478]
**Server (please complete the following information):**
 - Snipe-IT Version 4.1.14
 - OS: Ubuntu 16.04 LTS
 - Web Server: apache2
 - PHP Version: PHP 7.0.28

We have information that we need to store about specific model of devices. For example ChromeOS devices we need to store the date they will stop receiving updating automatically. This isn't a deprecating date from the time it is purchased it is a static date for all devices of this model. 

I would like to see a way to create custom fields for asset models like is available for assets. The information in the custom fields pertain to the model so every asset of that model has the same information. 

We have considered creating a default device for each model and then using custom fields for the asset to store this information. We can considered adding the information in the notes field. We have also considered keeping it in another location that we reference. 

![image](https://user-images.githubusercontent.com/6100099/39598320-2597e106-4ee6-11e8-925d-f1daa7106534.png)

**Comment by therealjoshuad** [comment]
What we do is have a fieldset for each "class" of model. So in my example, I have a "WiFi MAC" custom field that I want only on Laptops. So each new **model** for a specific model of laptop that I create, gets the **Laptop** custom field.

In your case, you'd probably create a fieldset for **Chromebook** or **ChromeOS**, then tag that fieldset to every **model** that's appropriate. You'd also add any other associated fields with that model. A custom field can be associated with many fieldsets.

Here's a quick little diagram of the relationship that I drew my colleagues when on-boarding them into using the software.

![image](https://user-images.githubusercontent.com/3893036/39602845-06f7902e-4eec-11e8-80b0-daf4797402f5.png)

**Comment by snipe** [comment]
If you upgrade to the latest version, default custom field values are now available, so you can create a fieldset, add custom fields to it, and set defaults that will pre-populate when you create new assets that belong to that model.

**Comment by soslan** [comment]
Default value is not a solution. Say I want display resolution to be fixed across all assets of my model. There is no reason to make it editable.
