### ISSUE TITLE
Clean up asset detailed view

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#548]
would look nice to shift some of the details into the second column. right now only warranty is listed in column two.

**Comment by snipe** [comment]
That's a little easier said than done, since some fields won't show up (if they have no value).

**Comment by kobie-chasehansen** [comment]
ah. Well maybe group things that would be entered together or things that are calculated based off another value.

Let me try to mock an idea or two up

**Comment by kobie-chasehansen** [comment]
Don't know if this makes sense or not with the way fields would show up

![image](https://cloud.githubusercontent.com/assets/10247644/6279605/a20625fe-b871-11e4-80fd-5e2bec64e9b1.png)

**Comment by snipe** [comment]
That's the way I used to have it, but since some fields won't show up, it becomes difficult to group the related ones together.

**Comment by kobie-chasehansen** [comment]
@snipe Any chance this can be revisited?
