### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#5482]
#### Please confirm you have done the following before posting your bug report:

Manage custom fields description reads as: "About Fieldsets
Fieldsets allow you to create groups of custom fields that are frequently re-used used for specific asset model types."

It should read as 

"About Fieldsets
Fieldsets allow you to create groups of custom fields that are frequently re-used for specific asset model types."

**Describe the bug**
Clerical / typo

**To Reproduce**
1. Go to Settings
2. Click on Custom Fields
3. Read "About fieldsets"

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.3.0 -3559

Confirmed on the demo as well.

**Comment by CronKz** [comment]
I've made that correction. Waiting for proofreader to confirm.

**Comment by snipe** [comment]
This is fixed on develop
