### ISSUE TITLE
Upload a file on a asset does not work

### ISSUE THREAD

**Issue by dennislittle** [snipe/snipe-it#5484]
#### Expected Behavior (or desired behavior if a feature request)

Upload a file on a asset does not work

-----

#### Actual Behavior

Getting a error  "Error: You did not select any files for upload, or the file you are trying to upload is too large"

And i do`nt see any file added

-----

#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Upgrade from 2 to 4.3**
- Version of Snipe-IT you're running **4.3**
- Version of PHP you're running **7.2.5**
- Version of MySQL/MariaDB you're running **?**
- What OS and web server you're running Snipe-IT on **Windows and IIS**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Manual**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **No**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **/hardware/87#files**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. **Error: You did not select any files for upload, or the file you are trying to upload is too large**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. **No**
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. **Update from 4.2 to 4,3, checked it with debug mode and update PHP**
- Indicate whether or not you've manually edited any data directly in the database **No**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Is there anything in your `storage/logs/laravel.log` when you try the upload?

**Comment by dennislittle** [comment]
No errors in de Lavarel.log

Verstuurd vanaf mijn iPhone

**Comment by snipe** [comment]
If you can't reproduce it on the demo, it must be something specific to your file or your environment. What can you tell me about the file (size, etc) and your PHP settings for max file upload size?

**Comment by dennislittle** [comment]
Hi,

It`s a text file from 2kb with a bitlocker key. But also if i use a pdf 500
kb it fails. I have the standard PHP settings for upload size. I did not
change anything

Kind regards,

Dennis van Eck

2018-05-04 23:27 GMT+02:00 snipe <notifications@github.com>:

**Comment by vogtmh** [comment]
Works fine on my installation. Maybe you don't have the necessary write permissions?

I used this guide for my LAMP installation on Ubuntu 16.04: https://www.ceos3c.com/cloud/how-to-install-snipeit-on-ubuntu-16-04-on-aws-free-tier/

**Comment by vogtmh** [comment]
Oh sorry.. my fault. I don't have any clue on IIS. Didn't think that people would use these anymore.. :-/

**Comment by crazzyfool** [comment]
I seem to be having the same issue here.  My colleague is unable to upload a BitLocker recovery key.  Most things they can upload fine including much bigger files such as .jpg etc.  I think this is an issue with the file encoding and/or the PHP checks being done.  To give more information.....

The file that can not be uploaded is only 4kb:

```
$ du -sh BitLocker\ Recovery\ Key\ G42E07CB-C5BF-59AB-BDFF-537B0CB725E2-mllove.TXT
4.0K	BitLocker Recovery Key G42E07CB-C5BF-59AB-BDFF-537B0CB725E2-mllove.TXT
```

If I run a 'file' on it, for some reason it shows as 'data' (which I think means it doesn't know what type of file it is):

```
$ file BitLocker\ Recovery\ Key\ G42E07CB-C5BF-59AB-BDFF-537B0CB725E2-mllove.TXT
BitLocker Recovery Key G42E07CB-C5BF-59AB-BDFF-537B0CB725E2-mllove.TXT: data
```

If I do a 'cat', I can see a couple of weird characters at the start of the line:

```
$ head -n1 BitLocker\ Recovery\ Key\ G42E07CB-C5BF-59AB-BDFF-537B0CB725E2-mllove.TXT 
ÿþBitLocker Drive Encryption recovery key
```

If I use vim, I see a couple at the end:

```
BitLocker Drive Encryption recovery key^@
...
```

If I try to remove all the weird characters:

```
$ sed $'s/[^[:print:]\t]//g' BitLocker\ Recovery\ Key\ G42E07CB-C5BF-59AB-BDFF-537B0CB725E2-mllove.TXT > new-2019-02-25-05.txt
```

The new file now shows as 'UTF-16' but can be uploaded okay:

```
$ file new-2019-02-25-05.txt
new-2019-02-25-05.txt: Little-endian UTF-16 Unicode text, with very long lines, with no line terminators
```

I think this is the issue but no sure what can be done.  I have also tested on the demo site and I have the same issue.  I have attached the file for testing.

**Comment by crazzyfool** [comment]
.....or even better:

```
$ LC_ALL=C sed 's/[^[:blank:][:print:]]//g' BitLocker\ Recovery\ Key\ G42E07CB-C5BF-59AB-BDFF-537B0CB725E2-mllove.TXT > new-2019-02-25-06.txt

$ file new-2019-02-25-06.txt
new-2019-02-25-06.txt: ASCII text
```
