### ISSUE TITLE
Groups - Account permission groups does not refelect most of the time 

### ISSUE THREAD

**Issue by sachinbhosale86** [snipe/snipe-it#5486]
#### Please confirm you have done the following before posting your bug report:

- [ Yes ] I have enabled debug mode 
- [ Yes ] I have read & checked the Common Issues page (https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Groups'
3. Created & existing group does not reflect 

**Expected behavior**
Groups should be visible

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [Windows]
 - Web Server: [Apache]
 - PHP 7.1.9

**Comment by snipe** [comment]
> Created & existing group does not reflect

I don't know what this means. Can you provide clarification and/or screenshots?

**Comment by sachinbhosale86** [comment]
![capture1](https://user-images.githubusercontent.com/23054845/39659812-d3c4bdda-504e-11e8-9287-60e7c191fec1.JPG)
![capture](https://user-images.githubusercontent.com/23054845/39659813-d3f1ac78-504e-11e8-9e1e-2ebbcc846986.JPG)

**Comment by snipe** [comment]
Anything in your `storage/logs/laravel.log`? I can't reproduce that here.
