### ISSUE TITLE
The code execution cannot proceed because MSVCP120.dll was not found.

### ISSUE THREAD

**Issue by GeorgeVolak** [snipe/snipe-it#5488]
- [N/A] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

- Is this a fresh install or an upgrade? YES on a fresh Windows 10 Pro 1803 version
![snipe-it](https://user-images.githubusercontent.com/39016528/39668762-411fc5ae-508c-11e8-9c0f-04965b248c14.PNG)

- Version of Snipe-IT you're running - trying to install the latest version
- Version of PHP you're running - whatever comes with latest WAMP
- Version of MySQL/MariaDB you're running  - whatever MySQL comes with latest WAMP
- What OS and web server you're running Snipe-IT on - Windows 10 Pro 1803 + WAMP
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual

Immediately after installing WAMP, I get these errors:

![snipe-it 2](https://user-images.githubusercontent.com/39016528/39668810-df313ec0-508d-11e8-9325-a55b1f8ab1a5.PNG)
![snipe-it 3](https://user-images.githubusercontent.com/39016528/39668812-f3ffa724-508d-11e8-94bd-55e108a17e84.PNG)
![image](https://user-images.githubusercontent.com/39016528/39668814-05f327da-508e-11e8-88ea-b9d61a91e2e6.png)
![image](https://user-images.githubusercontent.com/39016528/39668816-15b72f18-508e-11e8-8599-df2588918972.png)
![image](https://user-images.githubusercontent.com/39016528/39668819-2057b30c-508e-11e8-9cf9-e516babe4222.png)
![image](https://user-images.githubusercontent.com/39016528/39668820-2c90b538-508e-11e8-8464-65e70bb8170d.png)

I have followed this: https://snipe-it.readme.io/docs/wamp

I had installed both  VSU_4\vcredist_x64.exe and VSU_4\vcredist_x86.exe

Thank you!

**Comment by snipe** [comment]
This looks like you're missing something in your Microsoft installation. 

```
Hello,
Thank you for visiting Microsoft Community.
As per the description I understand that you are getting an error which says missing MSVCP120.dll. I will certainly help you with the issue.
 
I would like you to know that msvcp120.dll is a part of Microsoft Visual C++ and is often required for running programs developed with Visual C++.
Some games or applications may need the file in the game/application installation folder. Copying it from Windows systemfolder to the install-folder of the game/application should fix that problem. Make sure to use the 32bit dll-file for 32bit software, and 64bit dll-file for 64bit software.
 
Possible error messages regarding this file:
 
"msvcp120.dll Not Found"'
"The file msvcp120.dll is missing"
"File msvcp120.dll not found"
"The program can't start because MSVCP120.dll is missing from your computer. Try reinstalling the program to fix this problem
If it for some reason doesn't work by just replacing the file, you might need to re-install the Microsoft visual C++ Redistributable package which can be found here:
http://www.microsoft.com/en-us/download/details.aspx?id=40784
 
x86 for 32bit (x86) Windows, x64 for 64bit (x64) Windows. If using a 64bit Windows, install both.
Hope this information helps. 
```

https://answers.microsoft.com/en-us/windows/forum/windows_7-performance/missing-msvcp120dll-file/f0a14d55-73f0-4a21-879e-1cbacf05e906?auth=1

**Comment by LastStarSS** [comment]
Hi!
I have a easiest and fastest way to fix your problem which is worked for me:
1. (For compressed files)This happened when your compressed file(.zip,.rar,...) didn’t see that “missing file” so check for that file, is it really missing or it just because your file doesn’t have it by go to file explorer: C:/system32/(your missing file’s name). If you already have it, move it to the compressed file. If you didn’t have that file, download it and move to your compressed file.
Source to download your missing file:
VCRUNTIME140.dll: https://www.dll-files.com/vcruntime140.dll.html
MSVCR120.dll: https://www.dll-files.com/vcruntime140.dll.html
And also use that page to download any file end withs .dll
    (For uncompressed files) Same as compressed files

Hope this will help!
