### ISSUE TITLE
Bulk Audit: Update location and display in log

### ISSUE THREAD

**Issue by crmunro** [snipe/snipe-it#5489]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.3.0 - build 3559 (master)
 - OS: Windows Server
 - Web Server: IIS
 - PHP Version: 7.1.10

**Is your feature request related to a problem? Please describe.**
When auditing assets, it would be useful if the asset was updated with it's new location if it differs from the expected location. We regularly sweep all our buildings for assets, and we'd like to be able to walk into a room and scan every asset we find, and have it logged and updated in the asset register. 

**Describe the solution you'd like**
When an asset is audited, log the location seen into the "History" tab of the asset, and update it's current location.

**Describe alternatives you've considered**
We could use the "Bulk Checkout" feature to achieve this, but we'd like the "audit trail" as it were to reflect the action taken. eg. our team didn't actively move the asset (if we had, we'd have checked it out there) but a user has moved the asset to a new location, which we became aware of in an asset audit.

**Comment by lostmydog** [comment]
It sounds like you're looking for functionality similar to what i described in: https://github.com/snipe/snipe-it/issues/4644
