### ISSUE TITLE
Use server-side processing for DataTables to improve load time

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#549]
http://www.datatables.net/examples/data_sources/server_side.html

**Comment by snipe** [comment]
This looks promising: https://github.com/bllim/laravel4-datatables-package

**Comment by snipe** [comment]
For anyone following along with the home game, I have an almost-working version of this for assets in a feature branch (`features/chumper-datatables`) right now. It broke the deletion confirmation and I need to add the bulk-edit back in, but it's coming along very well. Hoping to have something on `develop` in the next few days.

**Comment by snipe** [comment]
The current issues list:

* Add bulk edit back in
* Fix delete confirmation
* Fix ordering in columns with links
* Tighten up the layout a smidge
- Add TableTools

**Comment by madd15** [comment]
Table tools should be added

**Comment by snipe** [comment]
I see that, thanks! I wonder why it's a different set of icons from the DataTables website :-/

**Comment by madd15** [comment]
I may have turned turned the images on in the css could revert it to the default which has no icons on buttons

**Comment by snipe** [comment]
How did you turn them on? I can try turning them off, just not sure what you did

**Comment by snipe** [comment]
Nvm, I got it :)

**Comment by snipe** [comment]
Are the tabletools working for you? I don't see anything downloaded when I click on CSV or Excel

**Comment by snipe** [comment]
Hrm. ColVis doesn't seem to be saving the state either. :-/

**Comment by madd15** [comment]
i am able to get a CSV with what ever is visible on the table

**Comment by snipe** [comment]
Not working for me. :( Maybe works in non-Safari browsers.

**Comment by snipe** [comment]
Updated the to-do list with my changes from tonight. Really nice work on this, @madd15. You've been a great help working on the front-end while I wired up the back. 

Yay teamwork!

![ipk42t6](https://cloud.githubusercontent.com/assets/197404/6651260/e67c0004-c9f7-11e4-8390-7b53e5031acd.gif)

**Comment by snipe** [comment]
Really nice work here, @madd15!

**Comment by madd15** [comment]
Doing my best to help :)

**Comment by madd15** [comment]
https://datatables.net/examples/server_side/pipeline.html
Not sure this would be possible

**Comment by snipe** [comment]
I saw that. It's kind of a different problem tho. The problem isn't the number of ajax calls we're making. This is a low-traffic app, so I'm not as worried about the number of calls, and in fact I think making more calls that contain less stuff would probably help us, since the slowness is coming from returning that gigantic collection of data that then needs to be sorted and stuff into the DOM.

**Comment by madd15** [comment]
Just posting a list so I can keep track of this bit a little easier (mainly for my own sanity :smile: )

**Apply Chumper datatables to Accessories section**
- [ ] Accessories - getIndex
- [ ] Accessories - getView (maybe)

**Apply Chumper datatables to Licenses section**
- [ ] Licenses - getIndex
- [ ] Licenses - getView (maybe)
