### ISSUE TITLE
Question for the Slack bot

### ISSUE THREAD

**Issue by Hiuja** [snipe/snipe-it#5490]
Hello,

I do not know if I have permission to ask that but you never know. Here I would like to modify the slack bot for snipe it. I would like to allow my users to power when the bot sends a notification for the return of an object for example that anyone could click a button (Take) in the bot that would allow them to take the object without going through the snipe interface it. Unfortunately, I do not really know how to do it first of all because there is this drop-down list that must be completed when someone wants to take an item from the inventory. And I do not know how to prevent individuals from reconnecting each time.

**Comment by snipe** [comment]
Those kinds of web hooks aren't really easily done in the current version of Laravel/Snipe-IT, but they are on the roadmap for future releases.
