### ISSUE TITLE
Error: object file XXX is empty

### ISSUE THREAD

**Issue by serpentsilver01** [snipe/snipe-it#5492]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**
go to snipeit dir and run
php upgrade.php

**Expected behavior**
Update to 4.3 for 4.2

**Screenshots**
Get Git is installed.
Already on 'master'
error: object file .git/objects/71/708e349c64a756f9869ce23ee8498030581 is empty
error: object file .git/objects/71/708e349c64a756f9869ce23ee8498030581 is empty
fatal: loose object 71708e349c64a756f9869ce23ee1ee8498030581 (stored in .git/objects/71/708 ...
fatal: the remote end hung unexpectedly
-- no local changes to save

**Server (please complete the following information):**
 - Snipe-IT Version 4.2
 - OS: Ubuntu server 16.04 LTS
 - Web Server: Apache
 - PHP Version 7.0

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
This is a git issue, not a Snipe-IT issue, but you can try a fresh clone. Just backup your old oauth keys (in storage), your .env, and any uploaded files, then move them over once you've re-cloned. 
http://howto.lintel.in/fix-git-object-file-empty-error/
