### ISSUE TITLE
Rename Fieldsets

### ISSUE THREAD

**Issue by jjmuelle-bhk** [snipe/snipe-it#5497]
**Server (please complete the following information):**
 - Snipe-IT Version: **v4.3.0 build 3559 (g9eab9ad40)**
 - OS: [e.g. Ubuntu, CentOS] **Ubunto 16.04.4 LTS**
 - Web Server: [e.g. Apache, IIS] **Apache 2.4.18 (Ubuntu)**
 - PHP Version **7.0.28-0ubuntu0.16.04.1**

**Is your feature request related to a problem? Please describe.**
I cannot rename a fieldset.

**Describe the solution you'd like**
Ability to edit the name of the fieldset. Either from the list of fieldsets and/or when viewing a single fieldset.

**Describe alternatives you've considered**
I could create a new fieldset, and set it up with custom fields exactly the same, then reassign each model to the new fieldset.

**Additional context**
I want to rename one of my fieldset that I've named "Computer" to "Workstation", as that is more concisely what the fieldset describes.

**Comment by nixn** [comment]
While I would love this feature too, it's possible to manually change the name in the database. The column for that is `custom_fieldsets`.`name`. Just change it and it's reflected instantly (no caching).
