### ISSUE TITLE
Error SoftDeletingTrait not found

### ISSUE THREAD

**Issue by Nubianprince** [snipe/snipe-it#550]
[2015-02-20 19:37:01] production.ERROR: exception 'ErrorException' with message 'Class 'Illuminate\Database\Eloquent\SoftDeletingTrait' not found' in /var/www/it/vendor/laravel/framework/src/Illuminate/Foundation/AliasLoader.php:64

Got this error after updating files from master and running php artisan migrate. Anyone ran into  this?

**Comment by snipe** [comment]
Did you update composer as well? What version were you running before?

**Comment by Nubianprince** [comment]
yea i ran php composer.phar dump-autoload then php artisan migrate.. i also ran composer.phar self-update so i should be using the latest version

**Comment by snipe** [comment]
No, I mean `php composer.phar update`.

**Comment by snipe** [comment]
If you're on an older version, you may have missed the transition from Laravel 4.1 to 4.2. Upgrading to 4.2 meant changing the way we handled soft deletes, but if you have new code and an old Laravel install (since it's install via composer), I could see this happening.

**Comment by Nubianprince** [comment]
composer update did the trick.. thanks.. you guys are doing a great job.

**Comment by snipe** [comment]
Glad to hear you got it sorted! (And thanks!)
![aww-yeah](https://cloud.githubusercontent.com/assets/197404/6309431/45160f8a-b902-11e4-8ddf-c6e30170e73d.gif)
