### ISSUE TITLE
License files not downloadable from License File page after upgrade to 4.3.0

### ISSUE THREAD

**Issue by muteid10t** [snipe/snipe-it#5501]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Cannot download license files from License File Uploads page on v4.3.0. It was possible on version v4.2.0.

**To Reproduce**
1. Go to Licenses
2. Click on File Uploads
3. Upload a file
4. Downloads column no longer has a download button

Experienced on my install and verified on Demo

**Expected behavior**
Expected behavior is to have a way to download the license file as there was in previous versions.

**Screenshots**
N/A

**Server (please complete the following information):**
 - Snipe-IT Version V4.3.0
 - OS: Centos 7
 - Web Server: Apache HTTPD
 - PHP Version: 7.1.16

**Desktop (please complete the following information):**
 - OS: OSx 10.13.4
 - Browser Chrome
 - Version 66.0.3359.139

**Smartphone (please complete the following information):**
Not tested from smartphone

**Error Messages**
No error messages

**Additional context**
- Is this a fresh install or an upgrade?  Upgrade
- What method you used to install Snipe-IT? installed from install.sh, upgraded using 'php upgrade.php'
- Include what you've done so far: Followed all of the troubleshooting steps in the Common Issue Doc
- Indicate whether or not you've manually edited any data directly in the database: No manual edits done to the database

**Comment by snipe** [comment]
This is fixed on develop and will be in the next merge
