### ISSUE TITLE
Enable cron on Docker container/Enable automatic LDAP Imports on docker container.

### ISSUE THREAD

**Issue by delize** [snipe/snipe-it#5502]
**Server (please complete the following information):**
 - Snipe-IT Version 4.2.0
 - OS: [e.g. Ubuntu, CentOS] Docker - Ubuntu
 - Web Server: Docker Apache
 - PHP Version: Docker PHP version

**Is your feature request related to a problem? Please describe.**
Currently spinning up a docker image, cron is not installed on base image. This renders the ability to perform tasks like #4602 or #3962 not possible.

**Describe the solution you'd like**
Implement Cron into the docker container so that we can enable a cron script to run ldap imports automatically. 

OR

Implement a configurable time interval that ldap imports occur. 

**Describe alternatives you've considered**
Doing it manually, but this doesn't scale and isn't a good idea. 

**Additional context**
I am not sure whether this should be a feature request or a bug, since it goes both ways.

**Comment by delize** [comment]
Some examples of this can be found here:
https://www.ekito.fr/people/run-a-cron-job-with-docker/
https://stackoverflow.com/questions/37458287/how-to-run-a-cron-job-inside-a-docker-container
https://medium.com/@jonbaldie/how-to-run-cron-jobs-inside-docker-containers-26964315b582

**Comment by EarlRamirez** [comment]
@delize you can install cronie and crontabs from the container and commit the changes as an interim solution

**Comment by snipe** [comment]
I'm not sure what you're asking for, @delize. The PR to add cron was already merged and will be in the next release.

**Comment by delize** [comment]
ah, i was not aware. Nevermind then! I look forward to the next release!

**Comment by SpartacusIam** [comment]
> ah, i was not aware. Nevermind then! I look forward to the next release!

Did you ever get this working?  If so, what command are you actually running inside the container to do the ldap sync?
