### ISSUE TITLE
Default values in Custom Asset Report leads to ERR_INVALID_RESPONSE page

### ISSUE THREAD

**Issue by Meph1234** [snipe/snipe-it#5503]
#### Expected Behavior (or desired behavior if a feature request)

In the Custom Asset Report, if i leave all fields default then press Generate to export a csv file of all assets

-----

#### Actual Behavior

Chrome: Site cant be reached, http://SNIPESERVER/reports/custom, ERR_INVALID_RESPONSE
IE11: asks me to open CUSTOM and then says it fails to download.

If I set the field Default Location in the custom report to any of the locations, it generates a report but it only has headers in it.

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade from 4.2.0

- Version of Snipe-IT you're running  
v4.3.0 - build 3586 (master)

- Version of PHP you're running 
7.2.5-1+ubuntu16.04.1+deb.sury.org+1

- Version of MySQL/MariaDB you're running
 MariaDB 10.1.32

- What OS and web server you're running Snipe-IT on
Ubuntu 16.04.4 LTS

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Install.sh and then followed instructions to change to the git pull procedure

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
/reports/custom, the Generate Button

- If a stacktrace is provided in the error, include that too.

- Any errors that appear in your browser's error console.
Chrome: Site cant be reached, http://SNIPESERVER/reports/custom, ERR_INVALID_RESPONSE
IE11: asks me to open CUSTOM and then says it fails to download.

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
It is not reproducable

- Include any additional information you can find in `storage/logs` and your webserver's logs.

from Laravel.log
[2018-05-09 12:21:51] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function present() on null in /var/www/snipe-it/app/Http/Controllers/ReportsController.php:580
Stack trace:
#0 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(39): App\Http\Controllers\ReportsController->App\Http\Controllers\{closure}(Object(Illuminate\Database\Eloquent\Collection))
#1 /var/www/snipe-it/app/Http/Controllers/ReportsController.php(679): Illuminate\Database\Eloquent\Builder->chunk(500, Object(Closure))
#2 [internal function]: App\Http\Controllers\ReportsController->App\Http\Controllers\{closure}()
#3 /var/www/snipe-it/vendor/symfony/http-foundation/StreamedResponse.php(114): call_user_func(Object(Closure))
#4 /var/www/snipe-it/vendor/symfony/http-foundation/Response.php(371): Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
#5 /var/www/snipe-it/public/index.php(61): Symfony\Component\HttpFoundation\Response->send()

This has the ReportsController.php from May 9, before this is was same error but Line 570

- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
No i have not

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
This is already fixed in develop https://github.com/snipe/snipe-it/commit/8ad5eb3e59bd1853288e481a07b052adfe2bdd3b
