### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by jtvdwesthuizen** [snipe/snipe-it#5505]
Hi,

Will it be possible to export your content from GLPI to another system like Snipe IT?

Please let me know if it's possible.

Much appreciated.

Thanks.

**Comment by snipe** [comment]
> Will it be possible to export your content from GLPI to another system like Snipe IT?

All of your data can be exported from Snipe-IT. It would depend on the import capabilities of the other system you're trying to import Snipe-IT data into to determine whether it can be imported.

**Comment by snipe** [comment]
If you're trying to import from GLPI to Snipe-IT, see our [importing documentation](https://snipe-it.readme.io/docs/importing).
