### ISSUE TITLE
 Custom Asset Report not exporting correctly - Exports code

### ISSUE THREAD

**Issue by samotelf** [snipe/snipe-it#5512]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Custom asset report exports code and not the assets :(
Error also present in the snipe-it demo

**To Reproduce**
1. Go to 'Reports'
2. Click on 'Custom Asset Reports'
3. Click on 'Generate'
4. Open .csv in Excel

**Expected behavior**
CSV export with assets.
Report was working in previous version

**Screenshots**

**Server (please complete the following information):**
 - v4.3.0 - build 3559 (master)
 - CentOS 7
 - Apache
 - 7

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Firefox
 - 59.0.3

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by samotelf** [comment]
Yes, that’s it.
It happens the same in the demo.

**Comment by snipe** [comment]
Duplicate of #5503

**Comment by TheVakman** [comment]
@snipe I don't think this is the same at #5503.

I'm able to export the report from custom reports but within the report, I'm missing data and I have that above error/content in the report itself.

I'm on the latest master right now, build 3559.

**Comment by snipe** [comment]
That error doesn't tell me anything though. I need the actual stack trace.

**Comment by TheVakman** [comment]
@snipe I've grabbed the stack trace from the laravel log. Let me know if there's anything to try if you update the develop branch.
```
[2018-05-15 17:29:16] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function present() on null in /var/www/html/snipeit/app/Http/Controllers/ReportsController.php:570
Stack trace:
#0 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(39): App\Http\Controllers\ReportsController->App\Http\Controllers\{closure}(Object(Illuminate\Database\Eloquent\Collection))
#1 /var/www/html/snipeit/app/Http/Controllers/ReportsController.php(669): Illuminate\Database\Eloquent\Builder->chunk(500, Object(Closure))
#2 [internal function]: App\Http\Controllers\ReportsController->App\Http\Controllers\{closure}()
#3 /var/www/html/snipeit/vendor/symfony/http-foundation/StreamedResponse.php(114): call_user_func(Object(Closure))
#4 /var/www/html/snipeit/vendor/symfony/http-foundation/Response.php(371): Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
#5 /var/www/html/snipeit/public/index.php(61): Symfony\Component\HttpFoundation\Response->send()
#6 {main}
[2018-05-15 17:29:16] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function present() on null in /var/www/html/snipeit/app/Http/Controllers/ReportsController.php:570
Stack trace:
#0 /var/www/html/snipeit/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(39): App\Http\Controllers\ReportsController->App\Http\Controllers\{closure}(Object(Illuminate\Database\Eloquent\Collection))
#1 /var/www/html/snipeit/app/Http/Controllers/ReportsController.php(669): Illuminate\Database\Eloquent\Builder->chunk(500, Object(Closure))
#2 [internal function]: App\Http\Controllers\ReportsController->App\Http\Controllers\{closure}()
#3 /var/www/html/snipeit/vendor/symfony/http-foundation/StreamedResponse.php(114): call_user_func(Object(Closure))
#4 /var/www/html/snipeit/vendor/symfony/http-foundation/Response.php(371): Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
#5 /var/www/html/snipeit/public/index.php(61): Symfony\Component\HttpFoundation\Response->send()
#6 {main}
```

**Comment by samotelf** [comment]
Thank you Lawrence.

**Comment by snipe** [comment]
I can't reproduce this on the demo - what do you have selected for the custom asset report?

**Comment by snipe** [comment]
Also if you can show me what's on line 570 of `/var/www/html/snipeit/app/Http/Controllers/ReportsController.php`, that would help too. Hard to tell which specific version of that file you have.

**Comment by TheVakman** [comment]
@snipe It's possible I messed this file up when I was on Gitter with you that night troubleshooting the counts() one.

Let me grab the latest master again just to be on the safe side.

**Comment by TheVakman** [comment]
"not sure if bug" is definitely an accurate tag here.

Once I realized that was the file, it sort of clicked. I grabbed the file directly and I don't seem to be getting the error now.

Sorry @snipe but the good news is there are no changes needed from your side! 👍

**Comment by samotelf** [comment]
I updated snipe to the last version.
It’s ok now. Thank you all for the help.
@snipe you can close the incident now.

**Comment by samotelf** [comment]
Closing
