### ISSUE TITLE
Feature Request: Ability to move columns so they have a different display order (not related to sort order)

### ISSUE THREAD

**Issue by muteid10t** [snipe/snipe-it#5514]
**Server (please complete the following information):**
 - Snipe-IT Version: 4.3.0
 - OS: CentOS 7
 - Web Server: Apache httpd
 - PHP Version: 7.1

**Is your feature request related to a problem? Please describe.**
Not related to a specific problem

**Describe the solution you'd like**
It would be nice to be able to change the display order of the different field headers on the Asset and License pages, eg, move State from being the 4 column to being the 3 column.

**Describe alternatives you've considered**
I've disabled all of the fields I don't want to see on these pages but having the ability to change the column display order would be nice.

**Additional context**
N/A but I'm happy to answer any questions.

**Comment by EarlRamirez** [comment]
@muteid10t I believe that this is the same as #5425

**Comment by snipe** [comment]
Duplicate of #5425
