### ISSUE TITLE
License Checkout Email Notification

### ISSUE THREAD

**Issue by Atriarc** [snipe/snipe-it#5516]
#### Expected Behavior (or desired behavior if a feature request)

Capability of turning off email notification of software license checkout to a user.

-----

#### Actual Behavior

Not seeing an option to turn off license checkout notification to users.

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install.
- Version of Snipe-IT you're running
v4.2.0 build 3497 (g590938f)
- Version of PHP you're running
7.0.27-0+deb9u1
- Version of MySQL/MariaDB you're running
5.5.52-MariaDB
- What OS and web server you're running Snipe-IT on
Debian 9
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
None
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
None
- Any errors that appear in your browser's error console.
None
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
N/A
- Include any additional information you can find in `storage/logs` and your webserver's logs.
None
- Include what you've done so far in the installation, and if you got any error messages along the way.
Searched for email notifications for licenses in Issue Tracker, SnipeIT Documentation, and Google.
- Indicate whether or not you've manually edited any data directly in the database
No data has been manually edited.

**Comment by snipe** [comment]
This is already in development.
