### ISSUE TITLE
Unable to use API

### ISSUE THREAD

**Issue by lstcl4563** [snipe/snipe-it#5517]
#### Expected Behavior (or desired behavior if a feature request)

Simple JavaScript request to list all users, following the example found [here](https://snipe-it.readme.io/v4.2.0/reference).

-----

#### Actual Behavior

All I can see is the error:

> Failed to load url: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

-----

#### Please confirm you have done the following before posting your bug report:

- [ N ] I have enabled debug mode 
- [ Y ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
Fresh install
- Version of Snipe-IT you're running
4.1.11
- Version of PHP you're running
PHP 7.0
- Version of MySQL/MariaDB you're running
Ver 15.1
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04, Apache 2.4.18, running on an AWS EC2 microinstance
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Don't know, the person that set it up has left and never told me.
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
> Failed to load url: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
I can't recreate this with the demo because of a different error:
> Failed to load resource: net::ERR_CERT_DATE_INVALID

- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Here's the script portion of the HTML file:

```
var data = JSON.stringify(false);
var xhr = new XMLHttpRequest();
xhr.withCredentials = true;

xhr.open("GET", "http://ipaddress/api/v1/users");

xhr.setRequestHeader('Accept', 'application/json');
xhr.setRequestHeader('Content-type', 'application/json');
xhr.setRequestHeader('Authorization', 'Bearer API-KEY');

xhr.send(data);
```

**Comment by snipe** [comment]
If the API request coming from the same domain/protocol/ip? If not, you're running into a CORS issue. 

https://stackoverflow.com/questions/20035101/why-does-my-javascript-get-a-no-access-control-allow-origin-header-is-present
