### ISSUE TITLE
Unable to create asset with POST to API, but GET works fine

### ISSUE THREAD

**Issue by markbrule** [snipe/snipe-it#5518]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Trying to use the POST method on /api/v1/hardware/1 API endpoint, and I'm getting back "status: error, messages: Method not allowed". GET method works properly - returns all the assets.

**To Reproduce**
curl -i -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' -H 'Authorization: Bearer <insert api token>' -d '{"asset_tag": "MNVR-TEST-TEST", "model_id": 8}' http://0.0.0.0/api/v1/hardware/1

**Expected behavior**
Expected to insert an asset into the database. No asset added.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.2.0 build 3947 and 4.3.0 build 3586
 - OS: Ubuntu 16.04LTS
 - Web Server: Apaceh
 - PHP Version: 7.0 and 7.1

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser Chrome
 - Version  66.0.3359.139

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
No errors through the browser, API returns
{
    "status": "error",
    "messages": "Method not allowed",
    "payload": null
}

**Additional context**
- Is this a fresh install or an upgrade? fresh
- What OS and web server you're running Snipe-IT on Ubuntu 16.04 / Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) did manual as well as install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
No manual edits

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by markbrule** [comment]
Also checked common issues - haven't found anything.
Tried on develop.snipeit.com - which works

**Comment by snipe** [comment]
If you're trying to create an asset, you wouldn't use the endpoint `/api/v1/hardware/1`, you would use `/api/v1/hardware`. See [the documentation](https://snipe-it.readme.io/v4.2.0/reference#hardware-create).
