### ISSUE TITLE
How to get the Snipe-IT home page?

### ISSUE THREAD

**Issue by abazeed** [snipe/snipe-it#552]
I did all installation steps successfully, but when I am going to the http://localhost/snipe which is my installation folder; it's showing the folder contents (as shown in the image), no login page or any webpage.

![snipe](https://cloud.githubusercontent.com/assets/11146126/6329131/23184006-bb87-11e4-8d1e-9d67aa84a2e5.PNG)

Please help!!

**Comment by snipe** [comment]
Your Apache document root shou,d be the `public` folder

**Comment by jankiram** [comment]
i am also getting same problem . i want to install this software in my godaddy linux server. please tell me the procedure

**Comment by snipe** [comment]
@jankiram Please see the linux installation instructions. http://snipeitapp.com/documentation/installing-on-linuxosx/

**Comment by jankiram** [comment]
i uploaded into public_html folder .after that i opened the url/public it is showing the error like
Warning: require(/home/pitecnib/public_html/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory
what should i do?

**Comment by snipe** [comment]
@jankiram Did you run the composer install as outlined in the documentation? A little more info on what you've done so far would be really helpful.

**Comment by snipe** [comment]
@jankiram - any updates on this?

**Comment by DebrahR** [comment]
Same Problem, installed composer, set the DocumentRoot to the public folder within the snipe app, it is reading the index.php page but not running as a php file just echoing as basic html text. HELP!@!

**Comment by snipe** [comment]
@DebrahR that actually sounds like a different issue. Are you sure you have PHP installed? Can I see a screenshot? Also, please see the getting help instructions: http://snipeitapp.com/documentation/getting-help/

**Comment by DebrahR** [comment]
@snipe version running is snipe-it-1.2.6.1 on Ubuntu 14. I have Apache2 installed running on port 80, yeah php5 and all its add-ons are installed. 
![screenshot](https://cloud.githubusercontent.com/assets/6727973/7159318/ec925246-e346-11e4-9d68-6b577e2a250a.png)
![screenshot from 2015-04-15 09_05_29](https://cloud.githubusercontent.com/assets/6727973/7159319/ec9284b4-e346-11e4-832f-e471e6b7b996.png)

**Comment by DebrahR** [comment]
@snipe i added an excepted to my Google Chrome browser to access my web server on Ubuntu from Windows and I get that 404 error saying auth/signin not found.

**Comment by snipe** [comment]
Looks like you need to enable mod_rewrite. Use step 5.1 here: http://snipeitapp.com/documentation/installing-on-linuxosx/

Specifically the AllowOverride bit.

**Comment by DebrahR** [comment]
@snipe thought i had it enabled. Thank You!

**Comment by snipe** [comment]
Glad you got it sorted! 
![anigif_enhanced-26281-1427581758-6](https://cloud.githubusercontent.com/assets/197404/7165137/76a8c8d0-e35a-11e4-9d0a-88df69d21c0c.gif)
