### ISSUE TITLE
Extend/Amend expected check-in date 

### ISSUE THREAD

**Issue by fraserc182** [snipe/snipe-it#5522]
- Snipe-IT Version  v4.1.10 - build 3249
 - OS: CentOS
 - Web Server: Apache
 - PHP Version: 7

**Is your feature request related to a problem? Please describe.**

 - When a new person joins, we do not know when they will be leaving. When we get a notification from HR that a person is leaving I would like to then be able to update expected check-in date on the assets assigned to them. So we can be alerted on the leaving date about the assets we are expecting back.

**Describe the solution you'd like**

- When I edit an asset, I would like to be able to change the expected check-in date.

**Describe alternatives you've considered**

- Potentially building a webpage which will take username and leaving date which we can then insert into the database to manually update expected check-in date.

**Additional context**

**Comment by carlashley** [comment]
I'd love to see this feature implemented as well.

Current workflow for modifying the expected check in date via the UI involves actually checking in the asset, and then re-checking out the asset to the same user/location and setting the new expected check in date. This isn't a very practical workflow.
Enabling this to be changed on the asset details page would also allow bulk updates to be made to assets that have the same expected check in date.

**Comment by scraane** [comment]
I would like this also.

**Comment by scraane** [comment]
Still wanted

**Comment by fraserc182** [comment]
Still want this!

**Comment by fraserc182** [comment]
Still want this!

**Comment by tymik** [comment]
+1

**Comment by ssdit** [comment]
want this

**Comment by Mynty100** [comment]
Hi, YES! can this please be added. We have people hand in their laptop for repair and lend them a temporary device and set a 7 day expected check-in. Sometimes though we need to extend this. Could this be made possible as we have to check-in the device and then check back out with the changed date.

Thanking you,
Mynty.

**Comment by mahesh2471990** [comment]
This is feature is must.

@snipe please consider this

**Comment by fkick** [comment]
+1

**Comment by avassdal** [comment]
+1

**Comment by fkick** [comment]
Yes still relevant and would be much appreciated

**Comment by domain-admin** [comment]
This issue and request is important to me too

**Comment by sambayford** [comment]
+1

**Comment by mowoodsiii** [comment]
Me three!

**Comment by Mynty100** [comment]
Yeah love an update or explanation if possible please.
Cheers.

**Comment by fkick** [comment]
Yes still requested

**Comment by Lod3** [comment]
Indeed, I would like this feature as well

**Comment by tomse** [comment]
+1 for this feature

**Comment by ersatyle** [comment]
need this as well to extend the expected checkin time, sometime you need to do it...

**Comment by jmdelaro** [comment]
+1 for this feature

**Comment by bcoory** [comment]
+1 would make life so much easier!

**Comment by maxlehot1234** [comment]
+1 @snipe

**Comment by fkick** [comment]
Yes this is still relevant perhaps more so with Covid

**Comment by yayadrian** [comment]
Yep still really want this feature please

**Comment by ChiefSlac** [comment]
I'd like to see this. Right now we're checking in and then checking out to clear the date.

**Comment by tomse** [comment]
yes, still relevant

**Comment by fkick** [comment]
Yes. Still relevant.

**Comment by Mynty100** [comment]
100% still looking for this feature. 
Cheers.

**Comment by snipe** [comment]
This is already on develop
