### ISSUE TITLE
Search box missing for users that can only request assets

### ISSUE THREAD

**Issue by mlozevski** [snipe/snipe-it#5525]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When a user that only has the permission to view requestable assets logs in and goes to the requestable assets page there is no search box to search for assets. 

**To Reproduce**
1. Be a user who only has permission to view requestable assets and log in
2. Click on Requestable

<img width="676" alt="2018-05-11 08_00_12-requestable assets __ cisco meraki support lab - asset management" src="https://user-images.githubusercontent.com/34195585/39931207-89decca4-54f1-11e8-9009-4fe47c3256aa.png">

**Expected behavior**
There should be a search box like this:
<img width="320" alt="2018-05-11 08_02_56-requestable assets __ cisco meraki support lab - asset management" src="https://user-images.githubusercontent.com/34195585/39931279-c1319830-54f1-11e8-8942-4366c99cac6e.png">

**Server (please complete the following information):**
 - Version 4.2.0
-  Working version (4.1.10)
 - OS: Ubuntu 16.04
 - Web Server: Apache
 - PHP Version 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome and firefox

**Comment by mlozevski** [comment]
Nevermind, this looks fixed in 4.3

**Comment by snipe** [comment]
Awesome! Glad to hear you're all sorted. In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
