### ISSUE TITLE
Add Option to Remove Duplicate EULA in Asset Delivery Email

### ISSUE THREAD

**Issue by davidbwashburn** [snipe/snipe-it#5526]
**Server (please complete the following information):**
 - Snipe-IT Version
**4.3.0**
 - OS: [e.g. Ubuntu, CentOS]
**Ubuntu**
 - Web Server: [e.g. Apache, IIS]
**NGINX**
 - PHP Version 
**7.1**

**Is your feature request related to a problem? Please describe.**
Our EULA is very long so users are missing the "**Click to accept**" button at the bottom of the email.

**Describe the solution you'd like**
We'd like an option to remove the EULA from the email sent to users. A copy of the EULA is already on the user acceptance page when they click to follow the link and E-Sign the asset, so there's not a real need for it to be on the email as well in our opinion.

**Describe alternatives you've considered**

- We attempted to edit the **accept-accessory.blade.php** file's HTML to add a custom style to `style=" display: none!important;"` on the EULA `<p>` portion of the email but it came with unintended consequences.

- We also attempted to edit the **default.blade.php** CSS style and force the container of the EULA to `display: none;` but there are no unique ID's or classes on the table elements in the email to target the EULA section and hide it.

**Additional context**
Adding a custom ID or class to this specific table might help? Or an option to remove the EULA from the email altogether. That would be the ideal solution. 

<img width="628" alt="id" src="https://user-images.githubusercontent.com/39170912/39940725-d604a242-551f-11e8-9f1b-68351a3c6902.PNG">

**Comment by snipe** [comment]
That won't work for many of our users, who require (through their corporate policies) that the EULA is emailed. We can consider adding that as an optional setting though.

**Comment by snipe** [comment]
I'll keep this open as an open feature request
