### ISSUE TITLE
Unable to edit assets using API with non super user/admin permissions

### ISSUE THREAD

**Issue by niallmooney** [snipe/snipe-it#5529]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When trying to edit assets using Patch in the API with a non super user/admin user API key (But being granted edit permissions in the assets section), The response which gets returned is a 403 forbidden error with asset not being updated. From the looks of things this appears to be a regression introduced between 4.1.14 -> 4.2.0 and is still present in 4.3.0. I have granted full access permissions to the user apart from super user and/or admin privileges and I am still unable to edit assets through the API. If I grant the user admin or super user privileges the user is able to edit the asset through the API  

**To Reproduce**
1. Grant user only permissions for asset section / generate API key
2. Generate API key for user
3. Patch changes to asset (i.e Notes/rtd_location_id) using postman
4. Receive 403 error

Other notes: 
- User is still able to use API to view assets/create assets with restricted permission set, just not update.
- When user has super user or admin permissions the API returns that the Asset updated successfully with the changes present.

**Expected behavior**
Users with edit permissions for assets should be able to edit assets using the API

**Screenshots**
Permissions levels
![4_3_0_perms](https://user-images.githubusercontent.com/5770937/39964341-bfb57a46-56c5-11e8-9414-f23151a2746b.png)

**Server (please complete the following information):**
 - Snipe-IT Version: 4.2.0 and 4.3.0
 - OS: CentOS 7.
 - Web Server: Apache 2.4.6
 - PHP Version: 5.6.36

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Postman
 - Version: 6.0.10

**Error Messages**

[4_2_0_API_Error.html.txt](https://github.com/snipe/snipe-it/files/1998166/4_2_0_API_Error.html.txt)
[4_3_0_API_Error.html.txt](https://github.com/snipe/snipe-it/files/1998167/4_3_0_API_Error.html.txt)
Laravel log only contains lines to do with a separate issue I was having which is more to do with me messing up API calls.
([2018-05-13 14:30:16] dev.ERROR: A checkout is not allowed under these circumstances)

**Additional context**
- Is this a fresh install or an upgrade?: Upgrade
- What OS and web server you're running Snipe-IT on: CentOS/Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual
- Include what you've done so far in the installation, and if you got any error messages along the way.: Imported demo content for testing purposes and added an custom field for MAC Address. Actual production instance this issue initially occurred on is fully populated with assets using CSV importer + added several custom fields.
- Indicate whether or not you've manually edited any data directly in the database: Demo - No,

**Comment by cwoods131** [comment]
We are having this issue too, as we do not want to grant Admin to all users who will be using the API. This is a major road block for us at the moment so anything you can do to alleviate this issue, we would greatly appreciate it. Thank you in advance

**Comment by snipe** [comment]
I don't see anything wrong with the gate that's being used in that API call.

`$this->authorize('edit', Asset::class);`

**Comment by niallmooney** [comment]
Just had a look at this again in 4.6.3 and it appears to be working as expect, so I'd say at this stage this issue can be closed off.
