### ISSUE TITLE
Managing consumables and accessories (quantities not serial numbers).

### ISSUE THREAD

**Issue by abazeed** [snipe/snipe-it#553]
In my company, IT department is responsible about managing consumables (Like toner cartridges) that will be used once then replaced with a new one and so on, also accessories (Like mice, keyboards, network cables, power extensions, mouse pads, ...) which has no serial numbers and should by managed as quantity assets that will be reduced if checked out for any user.
These assets should be added to the system by quantity not by serial numbers.

**Comment by snipe** [comment]
How do you manage inventory though? So, let's say you have 15 mice. A few get broken (as happens). Do you need to mark those as broken and undeployable? When you buy more of the same kind, do you need to track when they were purchased, how much they cost, manufacturer, etc?

**Comment by abazeed** [comment]
● When a mouse get broken, we replace it with a new one and mark the broken one as bad, at the end of the year we make a scrap list of all bad items, so we can mark them as undeployable.
● For the accessories, we don't care about tracking each item purchase date, or that this specific mouse belongs to that exact user. only we care about tracking our stock quantity and the users who have that item.
● We don't care about the manufacture or the cost, we care about the category (mouse, keyboard, ...) and the type (Apple mouse, Wireless keyboard, CAT-6 network cable, ...).

And thanks a lot for your time and interest.

**Comment by snipe** [comment]
This is very helpful, thanks!

**Comment by snipe** [comment]
So it sounds like to implement this, we need another table for "accessories" that is sort of like category but not exactly. Like asset models, but with way less info.

**Comment by snipe** [comment]
I'm basically planning this:

		 Schema::create('accessories', function ($table) {
            $table->increments('id');
            $table->string('name')->default(NULL);
            $table->integer('category_id')->default(NULL);
            $table->integer('qty')->default(NULL);           
            $table->timestamps();
            $table->softDeletes();
        });

Where the name of the accessory basically serves as the type. So an Apple Mouse would look something like this:

- name: Apple Mouse
- category: mice
- qty: quantity

Effectively, accessories becomes nothing more than a name and quantity associated with a category.

**Comment by abazeed** [comment]
That's great. So when:
● An item checked out to any user; the quantity will be reduced, and the user assets will show extra item which is mouse or any other accessories.
● An item checked in from any user; the item will disappear from the user assets, and the stock quantity will remain same in case if it's undeployable.

**Comment by kobie-chasehansen** [comment]
Maybe this applies to both normal assets and accessories but some type of selection box on checkin that allows you to mark the item as ready to deploy/pending/un-deployable/archived.

**Comment by snipe** [comment]
Hm. But if we're dealing with quantities, not actual items, I'm not sure how we'd do that. The items themselves don't really exist, except as a quantity field in the containing accessory type.

**Comment by jghanlon** [comment]
a few more things for inventory which may or may not be barcoded: wacom tablets, laptop lock (with key #?), 2nd Laptop AC adapter, video adapters, thunderbolt adapters, USB hubs, network switches.

**Comment by jghanlon** [comment]
It would be nice to also see if a particular user has been destroying an unusual amount of keyboards.
For example I had to give a user her 3rd keyboard this year due to her spilling on them.  It would be nice to know who is destroying keyboards and how many we're ewasting each month, quarter, year.

Now that I think about it, maybe there should be an option to send an item to EWASTE.  We have a holding bin for ewaste items.  It could be considered a LOCATION that holds INVENTORY.  That way barcoded items could show in their history that they were sent to EWASTE.

**Comment by snipe** [comment]
I'm going to close this ticket now, since I have a basic accessory system up on develop. I'll add undeployable for the 1.2.7 release.

@jghanlon you could also probably create an undeployable status label for EWASTE. I definitely do want to build in the ability to see users who are... problematic though.

**Comment by johnbchron** [comment]
I know this thread is super old but it's relevant to what I'd like to say. Can we please add a "Replenish" button to consumables? Right now there's a checkout button which works great but once you run out of a certain type of consumable, there's not really a good way to indicate that you bought more and replenished your stock. The options right now are basically either delete the old consumables record and make a new one, or directly edit the count field, which returns unhelpful metrics. If I'm missing how this is **supposed** to work, please enlighten me. Thank you for your time.

**Comment by ruddens** [comment]
> I know this thread is super old but it's relevant to what I'd like to say. Can we please add a "Replenish" button to consumables? Right now there's a checkout button which works great but once you run out of a certain type of consumable, there's not really a good way to indicate that you bought more and replenished your stock. The options right now are basically either delete the old consumables record and make a new one, or directly edit the count field, which returns unhelpful metrics. If I'm missing how this is **supposed** to work, please enlighten me. Thank you for your time.

Any one, any update on this? As @johnbchron says, how do you work with consumables and add more to them? or am i missing the workflow?
