### ISSUE TITLE
Upgrade.php not finding upgrade

### ISSUE THREAD

**Issue by GeffenMetzger** [snipe/snipe-it#5531]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When running php upgrade.php, the upgrade process runs but no upgrade is actually performed. Currently running version 4.2.0. I've also checked to see if its just an issue where it doesn't show the right version number, but one of the features added in 4.3 isn't there (uploading image during audit).

**To Reproduce**
Run upgrade.php
Clear browser cookies
Login
Check version listed

**Expected behavior**
Version listed should be 4.3.0

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version: 4.2.0
 - OS: Win 7
 - Web Server: WAMP
 - PHP Version: 7.2.4

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Firefox
 - Version: Latest

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade?
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snazy2000** [comment]
Whats the output of the upgrade.php look like? As its most likely erroring.

**Comment by GeffenMetzger** [comment]
Hey snazy, I've got a big presentation coming up (about SnipeIT actually) so I haven't had a chance to get a printout of the update cmd. I'll try to get this at some point today for you to see, it looks like it runs all the way through but I'll have to increase the cmd history buffer to see the full log. Unless theres an update log file that gets created that I just don't know about. Thanks for the reply though!

**Comment by GeffenMetzger** [comment]
Turns out you were on the right track, just had to stash my changes before doing the upgrade, all is well now. Thank you!!
