### ISSUE TITLE
How to reset ID number in "Companies"

### ISSUE THREAD

**Issue by SirajQu** [snipe/snipe-it#5535]
Hi,
I have added before companies and I deleted them, 
then I create new company but it's not resting the ID number from the beginning, it continue making number from last ID!

Kindly help.
![snipe-it](https://user-images.githubusercontent.com/30687897/40008962-58bb1b36-57a9-11e8-8432-a8dcd7226c3e.jpg)

**Comment by snipe** [comment]
The ID is not important for any purpose other than internal workings.
