### ISSUE TITLE
Backups file contains only SQL dump of databases

### ISSUE THREAD

**Issue by sid8000** [snipe/snipe-it#5539]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Taking backup using script or from application generates zip containing only SQL dump of databases.
There were no images or file attachments.

Even with command, backup files generates around 1 MB same as screenshot.

**Expected behavior**
Backup file should contain images and file attachments.

**Screenshots**

![image](https://user-images.githubusercontent.com/30995759/40049059-556f094e-5851-11e8-96d4-6fb0ce652e54.png)

**Server (please complete the following information):**
 - Snipe-IT Version **4.3.0**
 - OS: [e.g. Ubuntu, CentOS] **Windows **
 - Web Server: [e.g. Apache, IIS] ** WampServer **
 - PHP Version **7.1.9**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] **Chrome**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? **Upgrade**
- What OS and web server you're running Snipe-IT on  **Windows 7 with WampServer**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Manual**
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Can you show me a screenshot of your expanded zip file, and check the logs for any errors that may have come up while backing up?

**Comment by sid8000** [comment]
This is all Windows Default ZIP Program's fault.
Until now I was using default Windows extraction tool. For some reason, I switched to 7-zip and voilà.
All the files are there.
![image](https://user-images.githubusercontent.com/30995759/40158317-6e16ad46-59c1-11e8-997e-3935c29f8414.png)
![image](https://user-images.githubusercontent.com/30995759/40158319-70310c34-59c1-11e8-9ffb-deecbfdd802c.png)
