### ISSUE TITLE
Server Configuration

### ISSUE THREAD

**Issue by aamarnath** [snipe/snipe-it#554]
Please do help me out....

1. Installed WAMP server (Up and running)
2. Copied Snipe-IT folder to c:\wamp\www
3. Composer installed upon Snipe-IT folder (Command line, it prompted for username and password. provided the same and setup completed successfully)

Next what?

I am able to get the wamp server home page with http://172.25.60.28:8081 (Port 80 is used on IIS)

If I try to access the project folder http://172.25.60.28:8081/snipe-it the page does not display any thing.

Please do suggest, how to configure and get the project index page.

Thank in advance,

J Arvind Amarnath

**Comment by snipe** [comment]
Have you set the document root to `c:\wamp\www\public`?

**Comment by aamarnath** [comment]
Yes, its been set to: 

DocumentRoot "C:\wamp\www\snipe-it\public"

**Comment by snipe** [comment]
And you restarted the web server after setting that document root?

**Comment by aamarnath** [comment]
Yes, I restarted all the services

**Comment by aamarnath** [comment]
It popped up with new error message:

Not Found
The requested URL /auth/signin was not found on this server.
--------------------------------------------------------------------------------
Apache/2.4.9 (Win32) PHP/5.5.12 Server at 172.25.60.28 Port 8081

**Comment by snipe** [comment]
Did you configure apache to with AllowOverride to allow htaccess to work?

**Comment by aamarnath** [comment]
I just downloaded WAMP server windows version and got it installed. It dint prompt for any inputs, apart from php.exe file path.

**Comment by snipe** [comment]
Please see the Common Issues documentation. http://snipeitapp.com/documentation/common-issues/

**Comment by aamarnath** [comment]
I took up a new machine and installed WAMP server and checked localhost and myphpadmin page was working fine.

Copied Snipe-it folder to d:\wamp\www & modified D:\wamp\bin\apache\apache2.4.9\conf\httpd.conf

1. Change the DocumentRoot "D:\wamp\www\snipe-it\public"
2. Enabled LoadModule rewrite_module modules/mod_rewrite.so
3. <Directory />
    AllowOverride All
    Require all granted
</Directory>
4. Copied and renamed database.example.php to database.php
5. Modified database.php file with following details:
'mysql' => array(
            'driver'    => 'mysql',
            'host'      => 'localhost',
            'database'  => 'snipeit_AsstMgmt',
            'username'  => 'itsupport',
            'password'  => 'itsupport',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'strict'    => false,
6. Created a database and user on myphpadmin with full admin permission.
7. Installed composer on D:\wamp\www\snipe-it
8. Restarted all services on wamp server.

When i execute localhost page its given "Server Error: 500 (Internal Server Error"

Please do suggest me if i have missed out any step.

**Comment by snipe** [comment]
What do your apache logs and `app/storage/logs` files say?

**Comment by aamarnath** [comment]
Access log: 127.0.0.1 - - [24/Feb/2015:14:05:03 -0800] "GET /auth/signin HTTP/1.1" 500 5088

app/storage/logs:

Next exception 'ErrorException' with message 'Database [] not configured. (View: D:\wamp\www\snipe-it\app\views\backend\layouts\default.blade.php) (View: D:\wamp\www\snipe-it\app\views\backend\layouts\default.blade.php)' in D:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php:265

**Comment by snipe** [comment]
What environment are you running this in, production? Is there an `app/config/production/database.php`? (You mentioned you copied the file, but you didn't say to where.)

This happens sometimes when you think you're running the app in one environment, but because you've missed something somewhere else, the app thinks it's running in a different environment, so it's looking in the wrong  `app/config/<environment>` directory for config info. Try copying your `database.php` over to  `app/config/`.

**Comment by aamarnath** [comment]
I am not running on production environment.

database file location:
D:\wamp\www\snipe-it\app\config\local\database.php

**Comment by snipe** [comment]
Well, you are, you just don't know it. Did you add your hostname to the `bootstrap/start.php` the the `local` array?

Side note, if you're not planning on doing any development on the codebase, it's best to run this in production mode.

**Comment by aamarnath** [comment]
No I just made the change in Bootstrap/start.php page.

replaced YourLocalDevHostname = 172.25.60.47

**Comment by snipe** [comment]
Is that actually your hostname? (It needs hostname, not IP address.)

**Comment by snipe** [comment]
(In Windows, it would probably be your machine name.)

Regardless, it's definitely defaulting to production, that's why you're seeing that error. If you want to run it in production, just copy the config files you have in `app/config/local` into `app/config/production` and you should be all set.

**Comment by snipe** [comment]
(If you type in `hostname` from the command line, it *should* tell you the hostname, but again, I don't do windows, so you may have to google it.)

**Comment by aamarnath** [comment]
Moved database.php file from config/local  to config/production but no luck its coming up with same server error:500

**Comment by snipe** [comment]
Same error in your logs?

**Comment by snipe** [comment]
(Sorry, didn't mean to close that issue. Mis-clicked.)

**Comment by aamarnath** [comment]
php error log:

[24-Feb-2015 22:42:22 Europe/Paris] PHP Fatal error:  require(): Failed opening required 'D:\wamp\www\snipe-it\bootstrap/../vendor/autoload.php' (include_path='.;C:\php\pear') in D:\wamp\www\snipe-it\bootstrap\autoload.php on line 17

Access error log:

127.0.0.1 - - [24/Feb/2015:15:15:37 -0800] "GET /phpmyadmin/phpmyadmin.css.php?server=1&token=259ba63363d9f9aa79f5aae88a6d1987&nocache=5647559939ltr HTTP/1.1" 200 93053
127.0.0.1 - - [24/Feb/2015:15:15:37 -0800] "GET /phpmyadmin/js/get_scripts.js.php?token=259ba63363d9f9aa79f5aae88a6d1987&scripts[]=jquery/jquery-1.8.3.min.js&scripts[]=ajax.js&scripts[]=keyhandler.js&scripts[]=jquery/jquery-ui-1.9.2.custom.min.js&scripts[]=jquery/jquery.sprintf.js&scripts[]=jquery/jquery.cookie.js&scripts[]=jquery/jquery.mousewheel.js&scripts[]=jquery/jquery.event.drag-2.2.js&scripts[]=jquery/jquery-ui-timepicker-addon.js&scripts[]=jquery/jquery.ba-hashchange-1.3.js&scripts[]=jquery/jquery.debounce-1.0.5.js&scripts[]=jquery/jquery.menuResizer-1.0.js&scripts[]=cross_framing_protection.js&scripts[]=rte.js&scripts[]=tracekit/tracekit.js&scripts[]=error_report.js&scripts[]=doclinks.js&scripts[]=functions.js&scripts[]=navigation.js&scripts[]=indexes.js&scripts[]=common.js&scripts[]=codemirror/lib/codemirror.js&scripts[]=codemirror/mode/sql/sql.js&scripts[]=codemirror/addon/runmode/runmode.js HTTP/1.1" 200 1039434
127.0.0.1 - - [24/Feb/2015:15:15:37 -0800] "GET /phpmyadmin/js/messages.php?lang=en&db=&token=259ba63363d9f9aa79f5aae88a6d1987 HTTP/1.1" 200 17755
127.0.0.1 - - [24/Feb/2015:15:15:38 -0800] "GET /phpmyadmin/version_check.php?&_nocache=1424819738795316774 HTTP/1.1" 200 40
127.0.0.1 - - [24/Feb/2015:15:15:41 -0800] "GET /phpmyadmin/server_privileges.php?db=&token=259ba63363d9f9aa79f5aae88a6d1987&viewing_mode=server&ajax_request=true&ajax_page_request=true&menuHashes=5918d115&_nocache=1424819741507668684 HTTP/1.1" 200 14274
127.0.0.1 - - [24/Feb/2015:15:15:41 -0800] "GET /phpmyadmin/js/get_scripts.js.php?scripts[]=server_privileges.js&token=259ba63363d9f9aa79f5aae88a6d1987&call_done=1 HTTP/1.1" 200 26581
127.0.0.1 - - [24/Feb/2015:15:16:22 -0800] "POST /phpmyadmin/server_privileges.php HTTP/1.1" 200 1350
127.0.0.1 - - [24/Feb/2015:15:16:26 -0800] "GET /phpmyadmin/server_privileges.php?adduser=1&token=259ba63363d9f9aa79f5aae88a6d1987&ajax_request=true&_nocache=1424819786858473675 HTTP/1.1" 200 16049
127.0.0.1 - - [24/Feb/2015:15:16:32 -0800] "GET /phpmyadmin/server_privileges.php?ajax_request=true&token=259ba63363d9f9aa79f5aae88a6d1987&validate_username=true&username=itsupport&_nocache=1424819792479210106 HTTP/1.1" 200 205
127.0.0.1 - - [24/Feb/2015:15:16:59 -0800] "POST /phpmyadmin/server_privileges.php HTTP/1.1" 200 3503
127.0.0.1 - - [24/Feb/2015:15:17:27 -0800] "GET / HTTP/1.1" 302 356
127.0.0.1 - - [24/Feb/2015:15:17:27 -0800] "GET /auth/signin HTTP/1.1" 500 5088
127.0.0.1 - - [24/Feb/2015:15:17:28 -0800] "GET /favicon.ico HTTP/1.1" 304 -
127.0.0.1 - - [24/Feb/2015:15:25:25 -0800] "GET / HTTP/1.1" 302 356
127.0.0.1 - - [24/Feb/2015:15:25:26 -0800] "GET /auth/signin HTTP/1.1" 500 5088

app/storage/logs:

2015-02-24 23:25:26] local.ERROR: exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit_asstmgmt.settings' doesn't exist' in D:\wamp\www\snipe-it\vendor\laravel\framework\src\Illuminate\Database\Connection.php:299

**Comment by snipe** [comment]
Sounds like you didn't finish the install. Did you run `php artisan app:install`?

**Comment by snipe** [comment]
You need to follow all of the directions listed here: http://snipeitapp.com/documentation/installing-on-linuxosx/ Looks like you stopped at the end of Step 2.

**Comment by aamarnath** [comment]
Yes.. i missed this step. 

after executing php artisan app:install i got the login page. 

The only problem is i am not able to get this url over the network. 

Thanks for your support.

**Comment by snipe** [comment]
I don't understand. How did you get to a login page if you can't access the url?

**Comment by aamarnath** [comment]
from wamp server, localhost page i am able to view the login page... if i try to access the url over the network using hostname or IP address its coming up with 403 error You don't have permission to access / on this server.

**Comment by snipe** [comment]
I'm afraid that's out of scope for Snipe-IT support, as that's a WAMP issue. You may have some luck wit these links. 

http://stackoverflow.com/questions/5953803/wamp-server-available-over-wireless-network
http://www.codeproject.com/Tips/395286/How-to-Access-WAMP-Server-in-LAN-or-WAN

**Comment by aamarnath** [comment]
Thank you....:)
