### ISSUE TITLE
Error message with button "Test LDAP" is empty

### ISSUE THREAD

**Issue by doekman** [snipe/snipe-it#5540]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
On the `/admin/ldap`-page, when pressing the button "Test LDAP", an error icon is shown without a text message.

**To Reproduce**
1. Go to `/admin/ldap`
2. Make sure LDAP enabled is checked.
3. Have an "LDAP Server" filled in, like `ldap://myserver.mydomain.com` (I connect to an macOS Server.app Open Directory server)
4. Use as "LDAP Bind Username" a username like `OpenDirReader`
5. Fill out the correct password, and also other fields.
6. Click on "Save"
3. Now go again to `/admin/ldap`
4. Press the button "Test LDAP"

**Expected behavior**
A text message explaining the error (below the "Test LDAP" button, right of the red error-icon).

**Screenshots**
![test ldap error](https://user-images.githubusercontent.com/1086388/40049341-d64cc758-5834-11e8-9526-08128518936b.png)

**Server (please complete the following information):**
 - Snipe-IT Version: v4.3.0 build 3586 (gec1fa8e90)
 - OS: Debian
 - Web Server: NGINX
 - PHP Version: 7.0.27-0+deb9u1

**Desktop (please complete the following information):**
 - OS: macOS 10.13.4 (17E202)
 - Browser: Safari 11.1 (13605.1.33.1.4)

**Error Messages**

    [11:24:50] LOG.debug: Preparing to test LDAP connection
    [11:24:50] LOG.debug: attempting to bind to LDAP for LDAP test
    [11:24:50] LOG.debug: Bind failed

**Description**
Via Safari's developer console I see that the URL `/api/v1/settings/ldaptest` returns the JSON `{"message": "Could not bind to LDAP: Invalid DN syntax"}`. This information is not shown to in the UI.

Also: I figured out the exact problem why LDAP Test failed: the field "LDAP Bind Username" is put into the `bind_rdn` parameter of the `ldap_bind` function. The `bind_rdn` is not a username, but an LDAP dn format, like `uid=OpenDirReader,cn=users,dc=myserver,dc=mydomain,dc=com`.

So this bug is about:
1. LDAP Test button should show some error message text.
2. The LDAP settings screen should provide some guidance as what to fill into the field "LDAP Bind Username" (for example: rename the field to "LDAP Bind DN").

**Comment by snipe** [comment]
LDAP configuration is detailed in detail here: https://snipe-it.readme.io/docs/ldap-sync-login

**Comment by Mynty100** [comment]
Is this a windows AD or open source AD ?

Based on your setting these would not be what I would use for windows AD. 

Let us know try help you further.

**Comment by doekman** [comment]
By the way, we use OpenLDAP on macOS (the one that came with Server.app). I've got my LDAP sync working already, so this one is for the person installing Snipe-IT after me :-)

**Comment by doekman** [comment]
was already fixed.
