### ISSUE TITLE
Need help to debug further... LDAP

### ISSUE THREAD

**Issue by maxit1** [snipe/snipe-it#5543]
#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode 
- [yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Im trying to connect my snipe-it to my local ucs openLDAP, im not sure if this is wether a bug or just my fault but I'm looking for help nevertheless. 
I tried multiple setups in the ldap configuration, and I either get wrong dn syntax or 500 server error.

tried following setups

LDAP Server ldap://IP:7389 | ldap://fqdn:7389

yes/no Use TLS  (-> No always gives me Invalid DN syntax error)

yes/no Allow invalid SSL Certificate 

LDAP Bind Username username@server.com | username@(hostname of DC).server.com  | uid=username,dc=server,dc=com 
LDAP Bind Password (I've checked with multiple accounts here not just one)
Base Bind DN dc=server,dc=com | cn=users,dc=server,dc=com
LDAP Filter &(objectClass=organizationalPerson) | &(cn=*)
Username Field uid
Last Name sn
LDAP First Name cn
LDAP Authentication query uid=
LDAP Version 3

I've also tried to connect it via port 389 to the samba ad, changing uid to samaccountname etc.

**To Reproduce**
see above, trying to setup LDAP

**Expected behavior**
When theres "500 Server error"-Error maybe a liiiiittle bit more info but "connection failed" from the debug log as the server is able to ping the domain controller by ip, hostname and fqdn. The userdata is right also I'm not exactly sure where the syntax error lies when it is basically like the documentation says (and this time not just on snipe-it's documention but also on UCS' documentation)

(ALSO: I'm not a 100% sure if my data entered was right, but I followed the documentation and tried around a bit, so I guess there should've been something right atleast)

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version  4.20
 - OS: [e.g. Ubuntu, CentOS] Ubuntu 16.04.4
 - Web Server: [e.g. Apache, IIS]  Server version: Apache/2.4.18 (Ubuntu)
Server built:   2018-04-18T14:53:04

 - PHP Version PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10 Pro
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 54

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

Debug window gives me even less informative information other than 500 Server error and invalid dn syntax - happens when both errors show up.

    [16:00:29] LOG.debug: Preparing to test LDAP login

    [16:00:29] LOG.debug: Bind failed

 

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on - see above
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

It seems to try to login though when theres wrong user data it shows the corresponding error.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Mynty100** [comment]
So bind failure suggests that the service account you are using does not have permissions to the base bind DN. Or perhaps you have not enter the information correctly.

LDAP Bind Username: In this field use the 'distinguishedName' 
EG: CN=LDAP,OU=Service Accounts,DC=Server,DC=COM

LDAP Bind Password: Service account password

Base Bind DN: dc=server,dc=com - or the specific OU the service account has permission to search.
LDAP Filter: &(objectClass=organizationalPerson) | &(cn=*) - This is specific to what you are looking to filter. Personal we filter by security groups.
EG: &(objectClass=user)(memberof= CN=domain users,OU=Security Groups,DC=server,DC=COM)

Username Field: uid or samaccountname
Last Name: sn
LDAP First Name: cn or givenname
LDAP Authentication query: uid= or samaccountname=
LDAP Version: 3


Let us know how you go with this. or have any other questions.

**Comment by maxit1** [comment]
You are my Hero! It works!
I changed bind username to uid=LDAP-READONLY,cn=users,dc=server,dc=com
and &(objectClass=organizationalPerson) to just person according to https://www.univention.de/2016/09/how-to-integrate-with-ldap-generische-ldap-anbindung/ (German!) theres no objectClass user.

Thank you so much!!!

One thing, thats not really important but it just occured:
All users are imported like this
Firstname Field: Firstname Surname
Surname Field: Surname

so it looks like Testname Testsurname Testsurname. Well I can change that by hand, but it would be awesome if there was a solution to this. (maybe this occurs due to the filter?)

**Comment by Mynty100** [comment]
It depends if your using a Microsoft AD server or something like openLDAP will depend on the &(objectClass=*) 

Glad to hear you got it working though. Enjoy!
