### ISSUE TITLE
Checkout Asset API Query Params Incorrect

### ISSUE THREAD

**Issue by CBrooks12** [snipe/snipe-it#5545]
**Describe the bug**
The documentation [here](https://snipe-it.readme.io/v4.0/reference#hardwareidcheckout) is incorrect. The query params are incorrect. I found the correct params [here](https://github.com/snipe/snipe-it/blob/master/app/Http/Requests/AssetCheckoutRequest.php)

In short, the correct params are 
~~~
$rules = [
            "assigned_user"         => 'required_without_all:assigned_asset,assigned_location',
            "assigned_asset"        => 'required_without_all:assigned_user,assigned_location|different:'.$this->id,
            "assigned_location"     => 'required_without_all:assigned_user,assigned_asset',
            "checkout_to_type"      => 'required|in:asset,location,user'
        ];
~~~
**To Reproduce**
This is the powershell body I used when I invoked the method
~~~
$payload = @{
            "assigned_user" = $userId
            "checkout_to_type" = "user"
}
~~~
And it returned a success.

Let me know if there's any other information you would like me to provide.

Chris

**Comment by snipe** [comment]
I'm not sure what's incorrect here....

**Comment by CBrooks12** [comment]
From the documentation, I was led to believe the param I was supposed to use was "user_id" and nowhere was it mentioned I needed a "checkout_to_type" parameter. 

My first attempt based on the documentation was:
```
$payload = @{
    "user_id" = $user_id
}
```
Which gave me an error that I needed one of the assigned types.

Hope this clears it up.

Chris

**Comment by snipe** [comment]
Ah, I think I understand. The query parameters were correct, but the note at the bottom was outdated.

Correct:

<img width="711" alt="screen shot 2018-05-16 at 5 43 24 pm" src="https://user-images.githubusercontent.com/197404/40150792-b4a1e97e-5930-11e8-8bdd-8efb524c99f4.png">

Outdated:

<img width="640" alt="screen shot 2018-05-16 at 5 43 30 pm" src="https://user-images.githubusercontent.com/197404/40150796-ba74d3b6-5930-11e8-9919-317bde741797.png">

It's been updated, thanks.
