### ISSUE TITLE
Snipe-IT Preflight setup issue

### ISSUE THREAD

**Issue by qcfourie** [snipe/snipe-it#5548]
Expected Behavior (or desired behavior if a feature request)

Hi All

The problem I'm having is, when you open the web page to run the pref-light with debugging on, I receive the following error

(3/3) QueryException
SQLSTATE[HY000] [2002] Permission denied (SQL: select * from information_schema.tables where table_schema = snipeit and table_name = users)

I followed these suggested instructions exactly
https://snipe-it.readme.io/docs/installation

Some more information:

    It is a fresh Install
    Snipe-IT version 4.2
    PHP version 5.6.35
    Mysql Ver 15.1 Distrib 5.5.56-MariaDB
    CentOS Linux 7

My MariaDB users are:
MariaDB [mysql]> select user,host from mysql.user;
+------------+-----------------------+
| user       | host                  |
+------------+-----------------------+
| snipe_user | %                     |
| root       | 127.0.0.1             |
| root       | ::1                   |
| root       | localhost             |
| snipe_user | localhost             |
| root       | localhost.localdomain |
+------------+-----------------------+
6 rows in set (0.00 sec)

My .env database settings are correct
DB_DATABASE=snipeit
DB_USERNAME=snipe_user
DB_PASSWORD=Scr!ba99123~!@
and I can log into Mysql with same user and query the snipeit database although there are no tables.

Anyone's help would be greatly appreciated.

Thank you in advance!

**Comment by EarlRamirez** [comment]
@qcfourie What is your DB host? It appears that this is related to SELinux **https://stackoverflow.com/questions/34673627/sqlstatehy000-2002-permission-denied#44092808** What is the output of **ausearch -m avc -ts recent** to see if SELinux is the culprit you can temporarily set SELinux to permissive mode **setenforce 0** and see if  you get the same error.

**Comment by qcfourie** [comment]
Hi Earl
It's a local DB as per my previous emails.

The result #ausearch -m avc -ts recent
[user@localhost ~]$ sudo ausearch -m avc -ts recent
----
time->Mon May 21 22:07:34 2018
type=PROCTITLE msg=audit(1526954854.171:122752): proctitle=2F7573722F7362696E2F6874747064002D44464F524547524F554E44
type=SYSCALL msg=audit(1526954854.171:122752): arch=c000003e syscall=42 success=no exit=-13 a0=b a1=7fe5a1b27650 a2=10 a3=5b037b66 items=0 ppid=991 pid=25920 auid=4294967295 uid=48 gid=48 euid=48 suid=48 fsuid=48 egid=48 sgid=48 fsgid=48 tty=(none) ses=4294967295 comm="httpd" exe="/usr/sbin/httpd" subj=system_u:system_r:httpd_t:s0 key=(null)
type=AVC msg=audit(1526954854.171:122752): avc:  denied  { name_connect } for  pid=25920 comm="httpd" dest=3306 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:mysqld_port_t:s0 tclass=tcp_socket
----
time->Mon May 21 22:10:02 2018
type=PROCTITLE msg=audit(1526955002.490:122803): proctitle=2F7573722F7362696E2F6874747064002D44464F524547524F554E44
type=SYSCALL msg=audit(1526955002.490:122803): arch=c000003e syscall=42 success=no exit=-13 a0=b a1=7fe5a1b27650 a2=10 a3=5b037bfa items=0 ppid=991 pid=25922 auid=4294967295 uid=48 gid=48 euid=48 suid=48 fsuid=48 egid=48 sgid=48 fsgid=48 tty=(none) ses=4294967295 comm="httpd" exe="/usr/sbin/httpd" subj=system_u:system_r:httpd_t:s0 key=(null)
type=AVC msg=audit(1526955002.490:122803): avc:  denied  { name_connect } for  pid=25922 comm="httpd" dest=3306 scontext=system_u:system_r:httpd_t:s0 tcontext=system_u:object_r:mysqld_port_t:s0 tclass=tcp_socket
[user@localhost ~]$

**Comment by qcfourie** [comment]
I ran the setenforce 0 command.
i think we are making progress, my new results error message when trying to open the pre-flight is:

(1/1)                                         RuntimeException                                                                          The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.
--
in Encrypter.php (line 43)
at Encrypter->__construct('afgri', 'AES-256-CBC')in EncryptionServiceProvider.php (line 27)
at EncryptionServiceProvider->Illuminate\Encryption\{closure}(object(Application), array())in Container.php (line 726)

**Comment by EarlRamirez** [comment]
@qcfourie looks like you need to generate the app keys **php artisan key:generate**

**Comment by EarlRamirez** [comment]
@qcfourie for the SELinux denial you can enable **setsebool -P httpd_can_network_connect_db 1** and enable SELinux **setenforce 1** and for the runtime exception you can check the following link **https://stackoverflow.com/questions/39693312/the-only-supported-ciphers-are-aes-128-cbc-and-aes-256-cbc-with-the-correct-key**

**Comment by qcfourie** [comment]
Thank you Earl and Snipe. The problem was that I did not have the APP_URL correct in my .env file.

**Comment by EarlRamirez** [comment]
@qcfourie there were multiple issues, initially, it was SELinux, followed by APP_KEY, missing and the APP_URL.
Glad that you are sorted.

**Comment by qcfourie** [comment]
Yes, thank you!
