### ISSUE TITLE
Username/Password not working for demosite

### ISSUE THREAD

**Issue by akshaysin** [snipe/snipe-it#555]
I was just trying to give a demo walk through of snipe-it to a friend of mine, but noticed that the demo credentials given on the home page are no longer working :+1: 

URL : http://demo.snipeitapp.com/auth/signin
Email: admin@example.com
Password: testadminuser

Someone must have changed it. Please look into it.

Thanks - Akshay

**Comment by snipe** [comment]
Fixed now. Thanks.

**Comment by theoden16** [comment]
Hi There,
I was going to have a look at you live demo (http://demo.snipeitapp.com/auth/signin) to have a walk though of snipe-it, sadly the demo credentials seems to no longer be working. 
Could you have a look into it.
Cheers - Laurent

**Comment by snipe** [comment]
@theoden16 please try now
