### ISSUE TITLE
 PHP Fatal error:  require(): Failed opening required '/var/www/html/snipeit/vendor/composer/..

### ISSUE THREAD

**Issue by inanin** [snipe/snipe-it#5551]
_____       _                  __________
      / ___/____  (_)___  ___        /  _/_  __/
      \__ \/ __ \/ / __ \/ _ \______ / /  / /
     ___/ / / / / / /_/ /  __/_____// /  / /
    /____/_/ /_/_/ .___/\___/     /___/ /_/
                /_/

  Welcome to Snipe-IT Inventory Installer for CentOS, Fedora, Debian and Ubuntu!

  The installer has detected centos version 7.
  Q. What is the FQDN of your server? (snipeit): asset.elegantliving.cn
     Setting to asset.elegantliving.cn

  Q. Do you want to automatically create the database user password? (y/n) y

* Adding IUS, epel-release and MariaDB repositories.
* Installing Apache httpd, PHP, MariaDB and other requirements.
  * httpd already installed
  * Installing mariadb-server
  * git already installed
  * Installing unzip
  * Installing php71u
  * Installing php71u-mysqlnd
  * Installing php71u-bcmath
  * Installing php71u-cli
  * Installing php71u-common
  * Installing php71u-embedded
  * Installing php71u-gd
  * Installing php71u-mbstring
  * Installing php71u-mcrypt
  * Installing php71u-ldap
  * Installing php71u-json
  * Installing php71u-simplexml
  * Installing php71u-process
* Configuring Apache.
* Setting up hosts file.
* Setting MariaDB to start on boot and starting MariaDB.
* Securing MariaDB.

NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MariaDB
      SERVERS IN PRODUCTION USE!  PLEASE READ EACH STEP CAREFULLY!

In order to log into MariaDB to secure it, we'll need the current
password for the root user.  If you've just installed MariaDB, and
you haven't set the root password yet, the password will be blank,
so you should just press enter here.

Enter current password for root (enter for none): 
OK, successfully used password, moving on...

Setting the root password ensures that nobody can log into the MariaDB
root user without the proper authorisation.

Set root password? [Y/n] y
New password: 
Re-enter new password: 
Password updated successfully!
Reloading privilege tables..
 ... Success!

By default, a MariaDB installation has an anonymous user, allowing anyone
to log into MariaDB without having to have a user account created for
them.  This is intended only for testing, and to make the installation
go a bit smoother.  You should remove them before moving into a
production environment.

Remove anonymous users? [Y/n] y
 ... Success!

Normally, root should only be allowed to connect from 'localhost'.  This
ensures that someone cannot guess at the root password from the network.

Disallow root login remotely? [Y/n] y
 ... Success!

By default, MariaDB comes with a database named 'test' that anyone can
access.  This is also intended only for testing, and should be removed
before moving into a production environment.

Remove test database and access to it? [Y/n] y
 - Dropping test database...
 ... Success!
 - Removing privileges on test database...
 ... Success!

Reloading the privilege tables will ensure that all changes made so far
will take effect immediately.

Reload privilege tables now? [Y/n] y
 ... Success!

Cleaning up...

All done!  If you've completed all of the above steps, your MariaDB
installation should now be secure.

Thanks for using MariaDB!
* Creating MariaDB Database/User.
* Please Input your MariaDB root password:
Enter password: 
* Cloning Snipe-IT from github to the web directory.
* Configuring .env file.
* Installing and running composer.
All settings correct for using Composer
Downloading...

Composer (version 1.6.5) successfully installed to: /var/www/html/snipeit/composer.phar
Use it: php composer.phar

Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 86 installs, 0 updates, 0 removals
  - Installing symfony/finder (v3.4.4): Cloning 613e263107
  - Installing symfony/polyfill-mbstring (v1.7.0): Cloning 78be803ce0
  - Installing symfony/var-dumper (v3.4.4): Cloning 472a984993
  - Installing psr/log (1.0.2): Cloning 4ebe3a8bf7
  - Installing maximebf/debugbar (1.13.1): Cloning afee79a236
  - Installing vlucas/phpdotenv (v2.4.0): Cloning 3cc116adbe
  - Installing symfony/css-selector (v3.1.10): Cloning 722a87478a
  - Installing tijsverkoyen/css-to-inline-styles (2.2.1): Cloning 0ed4a2ea4e
  - Installing symfony/routing (v3.4.4): Cloning 235d01730d
  - Installing symfony/process (v3.4.4): Cloning 09a5172057
  - Installing paragonie/random_compat (v2.0.11): Cloning 5da4d3c796
  - Installing symfony/polyfill-php70 (v1.7.0): Cloning 3532bfcd8f
  - Installing symfony/http-foundation (v3.4.4): Cloning 8c39071ac9
  - Installing symfony/event-dispatcher (v3.4.4): Cloning 26b87b6bca
  - Installing symfony/debug (v3.4.4): Cloning 53f6af2805
  - Installing symfony/http-kernel (v3.4.4): Cloning 911d2e5dd4
  - Installing symfony/console (v3.4.4): Cloning 26b6f419ed
  - Installing swiftmailer/swiftmailer (v5.4.9): Cloning 7ffc1ea296
  - Installing ramsey/uuid (3.7.3): Cloning 44abcdad87
  - Installing symfony/translation (v3.4.4): Cloning 10b32cf0ea
  - Installing nesbot/carbon (1.22.1): Cloning 7cdf42c0b1
  - Installing mtdowling/cron-expression (v1.2.1): Cloning 9504fa9ea6
  - Installing monolog/monolog (1.23.0): Cloning fd8c787753
  - Installing league/flysystem (1.0.42): Cloning 09eabc54e1
  - Installing erusev/parsedown (1.6.4): Cloning fbe3fe878f
  - Installing doctrine/inflector (v1.1.0): Cloning 90b2128806
  - Installing laravel/framework (v5.4.35): Cloning 54aa18a4e8
    Failed to download laravel/framework from source: The process "git clone --no-checkout 'https://github.com/laravel/framework.git' '/var/www/html/snipeit/vendor/laravel/framework' && cd 
'/var/www/html/snipeit/vendor/laravel/framework' && git remote add composer 'https://github.com/laravel/framework.git' && git fetch composer" exceeded the timeout of 300 seconds.    Now trying to download from dist
  - Installing laravel/framework (v5.4.35): Downloading (100%)         
  - Installing barryvdh/laravel-debugbar (v2.4.3): Cloning d7c88f0813
  - Installing doctrine/lexer (v1.0.1): Cloning 83893c552f
  - Installing doctrine/annotations (v1.4.0): Cloning 54cacc9b81
  - Installing doctrine/cache (v1.6.2): Cloning eb152c5100
  - Installing doctrine/collections (v1.4.0): Cloning 1a4fb7e902
  - Installing doctrine/common (v2.7.3): Cloning 4acb8f8962
  - Installing doctrine/dbal (v2.5.13): Cloning 729340d8d1
  - Installing fideloper/proxy (3.3.4): Cloning 9cdf6f118a
  - Installing guzzlehttp/promises (v1.3.1): Cloning a59da6cf61
  - Installing psr/http-message (1.0.1): Cloning f6561bf28d
  - Installing guzzlehttp/psr7 (1.4.2): Cloning f5b8a8512e
  - Installing intervention/image (2.4.1): Cloning 3603dbcc9a
  - Installing jakub-onderka/php-console-color (0.1): Cloning e0b393dacf
  - Installing javiereguiluz/easyslugger (v1.0.0): Cloning 11524a3fd7
  - Installing zendframework/zend-diactoros (1.7.0): Cloning ed6ce7e210
  - Installing symfony/psr-http-message-bridge (v1.0.2): Cloning c2b757934f
  - Installing phpseclib/phpseclib (2.0.9): Cloning c9a3fe35e2
  - Installing league/event (2.1.2): Cloning e4bfc88dbc
  - Installing lcobucci/jwt (3.2.2): Cloning 0b5930be73
  - Installing defuse/php-encryption (v2.1.0): Cloning 5176f5abb3
  - Installing league/oauth2-server (6.1.1): Cloning a0cabb573c
  - Installing guzzlehttp/guzzle (6.3.0): Cloning f4db5a78a5
  - Installing firebase/php-jwt (v4.0.0): Cloning dccf163dc8
  - Installing laravel/passport (v3.0.2): Cloning c6a23ff4f0
  - Installing nikic/php-parser (v3.1.4): Cloning e57b3a0978
  - Installing jakub-onderka/php-console-highlighter (v0.3.2): Cloning 7daa75df45
  - Installing dnoegel/php-xdg-base-dir (0.1): Cloning 265b859349
  - Installing psy/psysh (v0.8.17): Cloning 5069b70e8c
    Failed to download psy/psysh from source: The process "git clone --no-checkout 'https://github.com/bobthecow/psysh.git' '/var/www/html/snipeit/vendor/psy/psysh' && cd '/var/www/html/sni
peit/vendor/psy/psysh' && git remote add composer 'https://github.com/bobthecow/psysh.git' && git fetch composer" exceeded the timeout of 300 seconds.    Now trying to download from dist
  - Installing psy/psysh (v0.8.17): Downloading (100%)         
  - Installing laravel/tinker (v1.0.3): Cloning 852c2abe0b
  - Installing laravelcollective/html (v5.4.9): Cloning f04965dc68
  - Installing league/csv (8.2.2): Cloning fa8bc05f64
  - Installing maknz/slack (1.7.0): Cloning 7f21fefc70
  - Installing neitanod/forceutf8 (v2.0.1): Cloning 47c883ab27
  - Installing patchwork/utf8 (v1.3.1): Cloning 30ec6451ae
  - Installing phpdocumentor/reflection-common (1.0.1): Cloning 21bdeb5f65
  - Installing phpdocumentor/type-resolver (0.3.0): Cloning fb39335120
  - Installing sebastian/recursion-context (2.0.0): Cloning 2c3ba150cb
  - Installing sebastian/exporter (2.0.0): Cloning ce474bdd1a
  - Installing sebastian/diff (1.4.3): Cloning 7f066a26a9
  - Installing sebastian/comparator (1.2.4): Cloning 2b7424b55f
  - Installing webmozart/assert (1.3.0): Cloning 0df1908962
  - Installing phpdocumentor/reflection-docblock (3.2.2): Cloning 4aada1f93c
  - Installing doctrine/instantiator (1.0.5): Cloning 8e884e78f9
  - Installing phpspec/prophecy (v1.6.2): Cloning 6c52c2722f
  - Installing symfony/polyfill-util (v1.7.0): Cloning e17c808ec4
  - Installing symfony/polyfill-php56 (v1.7.0): Cloning ebc999ce5f
  - Installing christian-riesen/base32 (1.3.1): Cloning 0a31e50c0f
  - Installing pragmarx/google2fa (v1.0.1): Cloning b346dc1383
  - Installing predis/predis (v1.1.1): Cloning f0210e3888
  - Installing rollbar/rollbar (v1.3.6): Cloning a8a977976d
  - Installing rollbar/rollbar-laravel (v2.2.2): Cloning 0e396fc727
  - Installing schuppo/password-strength (v1.10): Cloning 06198d64e9
  - Installing spatie/db-dumper (1.5.1): Cloning efdf41891a
  - Installing spatie/laravel-backup (3.11.0): Cloning 2382532ce5
  - Installing tecnickcom/tc-lib-color (1.12.8): Cloning 1d1f9fbb03
  - Installing tecnickcom/tc-lib-barcode (1.15.7): Cloning 96ad2aae7f
  - Installing tightenco/ziggy (v0.4.1): Cloning 88ceae070d
  - Installing unicodeveloper/laravel-password (1.0.3): Cloning c2e532cbbb
  - Installing watson/validating (3.1.2): Cloning 22edd06d45
Generating optimized autoload files
* Setting permissions.
* Generating the application key.
* Artisan Migrate.
* Creating scheduler cron.
no crontab for root
* Configuring firewall to allow HTTP traffic only.
* Configuring SELinux.
* Setting Apache httpd to start on boot and starting service.
  Q. Do you want to configure mail server settings? (y/n) n

  ***Open http://asset.elegantliving.cn to login to Snipe-IT.***

* Cleaning up...
* Finished!
![image](https://user-images.githubusercontent.com/29162188/40177312-cc2a2440-5a10-11e8-8ee5-c01999cb1406.png)

tailf error_log 
[Thu May 17 20:04:34.695268 2018] [php7:warn] [pid 1526] [client 192.168.5.88:57211] PHP Warning:  require(/var/www/html/snipeit/vendor/composer/../laravel/framework/src/Illuminate/Foundati
on/helpers.php): failed to open stream: No such file or directory in /var/www/html/snipeit/vendor/composer/autoload_real.php on line 66[Thu May 17 20:04:34.695328 2018] [php7:error] [pid 1526] [client 192.168.5.88:57211] PHP Fatal error:  require(): Failed opening required '/var/www/html/snipeit/vendor/composer/../laravel/
framework/src/Illuminate/Foundation/helpers.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipeit/vendor/composer/autoload_real.php on line 66[Thu May 17 20:04:36.904519 2018] [php7:warn] [pid 1470] [client 192.168.5.88:57214] PHP Warning:  require(/var/www/html/snipeit/vendor/composer/../laravel/framework/src/Illuminate/Foundati
on/helpers.php): failed to open stream: No such file or directory in /var/www/html/snipeit/vendor/composer/autoload_real.php on line 66[Thu May 17 20:04:36.904550 2018] [php7:error] [pid 1470] [client 192.168.5.88:57214] PHP Fatal error:  require(): Failed opening required '/var/www/html/snipeit/vendor/composer/../laravel/
framework/src/Illuminate/Foundation/helpers.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipeit/vendor/composer/autoload_real.php on line 66[Thu May 17 20:04:38.403657 2018] [php7:warn] [pid 1473] [client 192.168.5.88:57213] PHP Warning:  require(/var/www/html/snipeit/vendor/composer/../laravel/framework/src/Illuminate/Foundati
on/helpers.php): failed to open stream: No such file or directory in /var/www/html/snipeit/vendor/composer/autoload_real.php on line 66[Thu May 17 20:04:38.403687 2018] [php7:error] [pid 1473] [client 192.168.5.88:57213] PHP Fatal error:  require(): Failed opening required '/var/www/html/snipeit/vendor/composer/../laravel/
framework/src/Illuminate/Foundation/helpers.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipeit/vendor/composer/autoload_real.php on line 66[Thu May 17 20:04:39.360835 2018] [php7:warn] [pid 1474] [client 192.168.5.88:57216] PHP Warning:  require(/var/www/html/snipeit/vendor/composer/../laravel/framework/src/Illuminate/Foundati
on/helpers.php): failed to open stream: No such file or directory in /var/www/html/snipeit/vendor/composer/autoload_real.php on line 66[Thu May 17 20:04:39.360884 2018] [php7:error] [pid 1474] [client 192.168.5.88:57216] PHP Fatal error:  require(): Failed opening required '/var/www/html/snipeit/vendor/composer/../laravel/
framework/src/Illuminate/Foundation/helpers.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipeit/vendor/composer/autoload_real.php on line 66[Thu May 17 20:04:40.340489 2018] [php7:warn] [pid 1475] [client 192.168.5.88:57215] PHP Warning:  require(/var/www/html/snipeit/vendor/composer/../laravel/framework/src/Illuminate/Foundati
on/helpers.php): failed to open stream: No such file or directory in /var/www/html/snipeit/vendor/composer/autoload_real.php on line 66[Thu May 17 20:04:40.340525 2018] [php7:error] [pid 1475] [client 192.168.5.88:57215] PHP Fatal error:  require(): Failed opening required '/var/www/html/snipeit/vendor/composer/../laravel/
framework/src/Illuminate/Foundation/helpers.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/snipeit/vendor/composer/autoload_real.php on line 66

**Comment by inanin** [comment]
error

**Comment by EarlRamirez** [comment]
@inanin, this should do the trick for you
**https://stackoverflow.com/questions/28177019/composer-exceeded-the-timeout-of-300-seconds-while-installing-sylius-on-composer**

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
