### ISSUE TITLE
[Feature Request] Alerts when close to date

### ISSUE THREAD

**Issue by cduverne** [snipe/snipe-it#5552]
**Server (please complete the following information):**
 - Snipe-IT 4.2.0
 - OS: Ubuntu
 - Web Server: Apache (Docker deployment)
 - PHP Version : Docker Deployment

**Is your feature request related to a problem? Please describe.**
When an asset reaches its EOL data or next audit date, no alert is raised

**Describe the solution you'd like**
Alerts or notifications are sent when an asset is close to the alert date. This parameter could be customizable (ie: 1 month before EOL, or 3 months before next audit etc...)

**Describe alternatives you've considered**
None

**Additional context**
I'm really grateful of the amazing job you did on SnipeIT! It's a great tool and we love it! Thanks!

**Comment by snipe** [comment]
Alerts for what? What date, exactly? We already have several date-based alerts. 

https://snipe-it.readme.io/docs/configuring-alerts-backups
https://snipe-it.readme.io/docs/email-alerts

**Comment by wilsonlspacheco** [comment]
Our Snipe-It isnt't alerting when an asset is close to plan date.
Can you help us ?

**Comment by snipe** [comment]
@wilsonlspacheco those are emailed. You have to set the cron/automated task tho. https://snipe-it.readme.io/docs/configuring-alerts-backups

**Comment by wilsonlspacheco** [comment]
@snipe Our version is Cloud Hosted. We have everything set up to receive the email alerts, but we're not receiving anything ... Can you help please? If you prefer, email us plz: it@introsys.eu

![2018-07-17_12h19_09](https://user-images.githubusercontent.com/35998796/42814377-ec4f26dc-89bb-11e8-9992-88b53079c610.png)

**Comment by snipe** [comment]
Hi @wilsonlspacheco - we'll have someone from support reach out to you at that email via our helpdesk.

**Comment by wilsonlspacheco** [comment]
ok @snipe . I will wait your contact

**Comment by snipe** [comment]
@wilsonlspacheco I believe we've enabled your alerts. Please send us an email at support@snipeitapp.com if you're still not seeing them.
