### ISSUE TITLE
Get 404 after migrating to new server

### ISSUE THREAD

**Issue by shanekw** [snipe/snipe-it#5557]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Migrated to a new server, but get a 404 when going to the url in a browser.

**To Reproduce**
1. follow git installation instructions
2. follow migration instructions
3. go to url in a browser
4. See 404 error

**Expected behavior**
snipe-it loads correctly

**Screenshots**
n/a it's a 404 error

**Server (please complete the following information):**
 - Snipe-IT Version: 4.3
 - OS: centos 7
 - Web Server: apache
 - PHP Version: 5.6.36

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome
 - Version: 65

**Error Messages**
- debug is turned on
- no browser error
- no stacktrace error
- no browser error console error
- not reproducible on the demo
- nothing in storage/logs
- apache log: tail -f /var/log/httpd/error_log
-----------------
[Thu May 17 15:48:27.721329 2018] [auth_digest:notice] [pid 14344] AH01757: generating secret for digest authentication ...
[Thu May 17 15:48:27.721988 2018] [lbmethod_heartbeat:notice] [pid 14344] AH02282: No slotmem from mod_heartmonitor
[Thu May 17 15:48:27.747206 2018] [mpm_prefork:notice] [pid 14344] AH00163: Apache/2.4.6 (CentOS) PHP/5.6.36 configured -- resuming normal operations
[Thu May 17 15:48:27.747259 2018] [core:notice] [pid 14344] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Thu May 17 16:07:08.750084 2018] [mpm_prefork:notice] [pid 14344] AH00170: caught SIGWINCH, shutting down gracefully
[Thu May 17 16:07:14.820477 2018] [suexec:notice] [pid 16047] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu May 17 16:07:14.847395 2018] [auth_digest:notice] [pid 16047] AH01757: generating secret for digest authentication ...
[Thu May 17 16:07:14.848082 2018] [lbmethod_heartbeat:notice] [pid 16047] AH02282: No slotmem from mod_heartmonitor
[Thu May 17 16:07:14.874858 2018] [mpm_prefork:notice] [pid 16047] AH00163: Apache/2.4.6 (CentOS) PHP/5.6.36 configured -- resuming normal operations
[Thu May 17 16:07:14.874895 2018] [core:notice] [pid 16047] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
--------------

**Additional context**
- Is this a fresh install or an upgrade? 
 fresh migration

- What OS and web server you're running Snipe-IT on
centos 7 and apache

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
git installation

- Include what you've done so far in the installation, and if you got any error messages along the way.
git installation instructions and migration instructions, no error messages along the way

- Indicate whether or not you've manually edited any data directly in the database
didn't edit db data manually

**Comment by shanekw** [comment]
forgot to mention: tried the commands in the "Handy Command" section in the Common Issues page

**Comment by snipe** [comment]
My guess would be an Apache Virtualhost configuration that’s incorrect (pointing to the wrong directory). Can you post your Apache Virtualhost config?

**Comment by shanekw** [comment]
I'm not using a virtualhost since it's the only site running on the server but here's my httpd.conf:

[httpd.conf.txt](https://github.com/snipe/snipe-it/files/2018539/httpd.conf.txt)
