### ISSUE TITLE
PHP Parse Error

### ISSUE THREAD

**Issue by ewm2000** [snipe/snipe-it#5559]
#### Please confirm you have done the following before posting your bug report:

- [no ] I have enabled debug mode 
- [yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When setting up IT snipe, I ran php artisan key:generate but Got this error
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/snipe-it/artisan on line 31

**Server (please complete the following information):**
 - Snipe-IT Version: 4.3.0
 - OS: Centos
 - Web Server: Apache
 - PHP Version : 5.4.16

**Error Messages**
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/snipe-it/artisan on line 31

**Additional context**
Fresh Install 
Manual Installation
Centos and Apache
No Errors Until now

**Comment by CODE-REaD** [comment]
Note that https://snipe-it.readme.io/docs/requirements currently indicates PHP 7.1.2 or higher is required, not 5.6.4 as reported above.
