### ISSUE TITLE
Error when doing composer install

### ISSUE THREAD

**Issue by adj1984** [snipe/snipe-it#556]
When I do the composer install, I get this error:

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for intervention/image dev-master -> satisfiable by i
ntervention/image[dev-master].
    - intervention/image dev-master requires ext-fileinfo * -> the requested PHP
 extension fileinfo is missing from your system.

**Comment by snipe** [comment]
The error is telling you what's wrong. `the requested PHP
extension fileinfo is missing from your system.`
