### ISSUE TITLE
Use 'Audit Interval' for default value during a single-asset Audit!

### ISSUE THREAD

**Issue by lostmydog** [snipe/snipe-it#5560]
**Server (please complete the following information):**
Right now, Audit Interval (found in settings/alerts) allows you to set the number of months between an audit. This value is only used in the bulk-audit feature right now. If you go to audit a singular item, the date of the 'next-audit' is todays date. Please make this value change with the default value! I accidentally audited several dozen items not noticing that the audit is already expired!

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by snipe** [comment]
@lostmydog I'm not sure what you mean here. I just tested by doing a single audit on an item, with an audit cycle set to 12 months. 

<img width="765" alt="screen shot 2018-05-18 at 2 45 17 pm" src="https://user-images.githubusercontent.com/197404/40259273-4ea16098-5aaa-11e8-9fdc-ba09e9a9d03b.png">

<img width="581" alt="screen shot 2018-05-18 at 2 45 51 pm" src="https://user-images.githubusercontent.com/197404/40259280-5317e994-5aaa-11e8-9d12-bc77ffd7c493.png">

**Comment by lostmydog** [comment]
@snipe oh wow, silly me! I was able to do that after setting the audit-cycle to 12 months. If you've never set the audit cycle before, a semi-transparent 12 appears in the box (which I always figured meant 12 is the default). Apparently that phantom-looking 12 only applies to bulk-audit. After clicking the box and inputting 12 myself, the feature now works as intended! So something about the default value of 12 does not affect the single-item audit, at least in my environment it didn't. This can surely be closed, thank you!

**Comment by snipe** [comment]
Hi @lostmydog - Got it. The "phantom" 12 is just HTML placeholder, to be used as a suggested value, but it's not truly a default.
