### ISSUE TITLE
Attach or link to Invoice from an asset\component\license 

### ISSUE THREAD

**Issue by ncs-madams** [snipe/snipe-it#5561]
**Server (please complete the following information):**
v4.2.0 build 3479 (gbf74bb1)
Hosted

**Is your feature request related to a problem? Please describe.**
yes, when you look up an item for a warranty claim you generally need the original invoice or just to produce it. 

**Describe the solution you'd like**
Directly under Order Number, there should be a Google Drive or some other option that would allow you to link to or host those images.

**Comment by snipe** [comment]
@ncs-madams Licenses already allow for file uploads. We can consider adding them to other items as well, although I think there may already be issues open for that.

**Comment by diskmandata4** [comment]
Do we have update on this  _"We can consider adding them to other items"_ for components? I'm using v.4.9 of SnipeIT. Thank you!
