### ISSUE TITLE
AD accounts cannot be landed on snipeIT

### ISSUE THREAD

**Issue by inanin** [snipe/snipe-it#5565]
**Describe the bug**

AD synchronization is normal, but use AD user name and password to login to snipe-IT hint (Error: The username or password is incorrect.).

The login username and password are also correct

**Screenshots**

![default](https://user-images.githubusercontent.com/29162188/40274720-fe290806-5c10-11e8-95d6-e9e64f5b1336.png)  
![default](https://user-images.githubusercontent.com/29162188/40274728-3325b13a-5c11-11e8-98cd-3751dd230b00.png)  
![default](https://user-images.githubusercontent.com/29162188/40274705-17aa489a-5c10-11e8-9802-d827a3a59bba.png)  

**Server (please complete the following information):**
 - Snipe-IT Version v4.3.0 - build 3610
 - OS: [CentOS 7]
 - Web Server: Apache/2.4.6 (CentOS)
 - PHP Version PHP 7.2.5 (cli)

**Comment by snipe** [comment]
This is typically a result of an incorrect LDAP Auth Query setting. For AD, this is usually `sAMAccountName=`.  Please see the documentation.
https://snipe-it.readme.io/docs/ldap-sync-login

**Comment by sokeada** [comment]
I have the same issue, when i was test on v4.1.3 was ok, same ldap config but still not able to login.

**Comment by ernestasen** [comment]
@inanin Can you shareyour current LDAP settings? 
I have the following and it works:
**LDAP Filter**: objectClass=person
**Username Field**: samaccountname
**LDAP Authentication query**: samaccountname=

**Comment by aalaily** [comment]
This may / may not be related to this:

[https://github.com/snipe/snipe-it/issues/5695](url)

Give the solution there a try and see if the problem is resolved.  Worked for me.
