### ISSUE TITLE
[Feature Request ] TIPweb-IT

### ISSUE THREAD

**Issue by memtech3** [snipe/snipe-it#5566]
**Describe the solution you'd like**
I would like to see more of the features in tipweb-it audits that show whats supposed to be in that room and mark tags as misplaced and prompt you to either transfer to new room or ignore

Here is the tipweb manual so you can see what I mean
http://www.tipwebhelp.com/tipwebithelp/

**Comment by snipe** [comment]
Please use the Feature Request template if you're requesting new features.

Secondly, if there are specific features from TIPweb that you'd like to see, please detail them here with your specific use-cases and workflows. I don't feel it's appropriate to point us to a URL and tell us to do the homework on what you want, and then also build it.
