### ISSUE TITLE
Multi instants LDAP Connection

### ISSUE THREAD

**Issue by quanquangduc** [snipe/snipe-it#5567]
Dear Snipe-IT team,

Our Company is Holdings Company . It have 4 Active Directory .
for example:
test01.local
test02.local
test03.local
test04.local

How can I import user AD from 4 domain controller ?

Many Thanks

**Comment by snipe** [comment]
You cannot at this time. The best you can do there is location-specific Cus

**Comment by Mikey84** [comment]
Would they need such a development?
That would be important to us too, we have two provinces.
But I think that would be a useful development for many other companies as well.
