### ISSUE TITLE
Unable to generate Key

### ISSUE THREAD

**Issue by ewm2000** [snipe/snipe-it#5569]
#### Please confirm you have done the following before posting your bug report:

- [no ] I have enabled debug mode 
- [yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When Setting up snipe it, I got to the point of setting the key. I ran php artisan key:generate and got this error
 `PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/snipe-it/app/Exceptions/Handler.php:39
Stack trace:
#0 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(320): App\Exceptions\Handler->report(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#1 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(132): Illuminate\Foundation\Console\Kernel->reportException(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#2 /var/www/snipe-it/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 {main}
  thrown in /var/www/snipe-it/app/Exceptions/Handler.php on line 39
`

**Server (please complete the following information):**
 - Snipe-IT Version: 4.3.0
 - OS: Cenots
 - Web Server: Apache v.2.4.6
 - PHP Version 7.2.5

**Additional context**
-Fresh install 
- CentOS and Apache
- Manual Installation
- Followed all the steps in the documentation to the letter and in the order they are presented in the documentation

Note:
I am using the Remi72 Repository to install PHP as Centos isnt currently shipping PHP 7.2.5

**Comment by EarlRamirez** [comment]
@ewm2000 is this a clean installation?

**Comment by ewm2000** [comment]
@EarlRamirez yes. I started the Installation a few minutes ago

**Comment by EarlRamirez** [comment]
@ewm2000 don't know if this will help but can you try running this again **php composer.phar install --no-dev --prefer-source** from your snipe-it directory

**Comment by ewm2000** [comment]
Here is my output
`[root@localhost snipe-it]# composer install --no-dev --prefer-source
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
`
Its all up to date

**Comment by EarlRamirez** [comment]
@ewm2000 it is not recommended to run composer as root, check out **https://snipe.net/2017/11/15/so-you-ran-composer-as-root/**. I can only suggest that you use ./install.sh, this script does all the heavy lifting for you. ==> **https://snipe-it.readme.io/docs/downloading**

**Comment by ewm2000** [comment]
But does install.sh run composer as well?

**Comment by EarlRamirez** [comment]
The only thing it does not do is create the snipeit OS user and set the permissions to snipeit/storage and snipeit/public

**Comment by ewm2000** [comment]
ok. Ill restart from scratch and try again

**Comment by ewm2000** [comment]
How easy is it to update Snipe-IT if I stick with the installer?

**Comment by EarlRamirez** [comment]
from the snipeit root directory **php update.php**

**Comment by snipe** [comment]
Usually when we see that Log error, it's something unrelated, like a space in the env where there shouldn't be one. https://snipe-it.readme.io/docs/installation-issues#section-fatal-error-uncaught-exception-reflectionexception-with-message-class-log-does-not-exist
