### ISSUE TITLE
People view - add ability to sort by last name 

### ISSUE THREAD

**Issue by viclou** [snipe/snipe-it#5570]
FD #5866

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by snipe** [comment]
As I mentioned, this isn't that difficult to implement from the actual sorting side, but conveying that through the UI will be more complicated. We could potentially add it as a setting in the Settings section, but I'd want to hear from others whether this option would be that important to them. Hate to have 5 million tiny settings for every little thing. Each one is a new logic fork to track for testing, etc.
