### ISSUE TITLE
Installer Script Encounters error on fresh cent 7 instance.

### ISSUE THREAD

**Issue by lry-rincon-jekyll** [snipe/snipe-it#5574]
![image](https://user-images.githubusercontent.com/38265309/40339778-289613e4-5d39-11e8-84cb-378e251718ae.png)

![image](https://user-images.githubusercontent.com/38265309/40340014-2d12a120-5d3a-11e8-9797-9db510391a2d.png)

I encounter this error when attempting to use the script way and also using the git clone way (when installing the composer) files. Any ideas?

**Comment by snipe** [comment]
This can be caused by NFS limits on filesystems, lags on github itself, low memory or any number of things. 

Try the suggestions listed here:
https://stackoverflow.com/a/18917919/200021
