### ISSUE TITLE
Unable to Upgrade to 4.4.1 from 4.3.0 Error while migrating

### ISSUE THREAD

**Issue by sid8000** [snipe/snipe-it#5575]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Upgrading manually from 4.3.0 to 4.4.1.
While running "php artisan migrate" got following error
![image](https://user-images.githubusercontent.com/30995759/40343682-aa07a1f2-5dae-11e8-8919-caf795f06323.png)

**Expected behavior**
Migration should be successful.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version **4.3.0**
 - OS: [e.g. Ubuntu, CentOS] **Windows**
 - Web Server: [e.g. Apache, IIS] **WAMPServer**
 - PHP Version **7.1.9**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? **Upgrade**
- What OS and web server you're running Snipe-IT on **WAMPServer**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Manual**
- Include what you've done so far in the installation, and if you got any error messages along the way.
Copied old .env file, storage/private_uploads folder, OAUTH files and public/upload folder.
Executed following commands
php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan migrate
At this command SQLSTATE error occurred as per screenshot
- Indicate whether or not you've manually edited any data directly in the database
No manual editing

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Can you check whether the table is myisam or innodb?

**Comment by snipe** [comment]
Alright - I think I see what's happening.

If your MySQL defaults to MyISAM as a storage engine (and I'm not 100% sure why it would, as InnoDB has been the default for years, since MySQL 5.6), you will have to run the following on your database:

 `ALTER TABLE action_logs ENGINE = InnoDB` 
 `ALTER TABLE assets ENGINE = InnoDB` 

Also you should probably set InnoDB to your default storage engine in your MySQL. MyISAM is, in general, the worse option.

**Comment by sid8000** [comment]
For all others who are having this issue.
Need to drop indexes before running migration again.
Just run following commands in MySQL console.

> DROP INDEX action_logs_item_type_item_id_action_type_index ON action_logs;

> DROP INDEX action_logs_created_at_index ON action_logs;

> DROP INDEX action_logs_target_type_target_id_action_type_index ON action_logs;

Run all three commands even with error(mostly index_name not found).
Now, migration will be successful.

> Also you should probably set InnoDB to your default storage engine in your MySQL

Yes. I have changed the Default Storage Engine to InnoDB.
And one more thing, should I changed engine for all the tables?

**Comment by snipe** [comment]
I’ll be adding a migration to set storage engines for the other tables in the next release

**Comment by jmartins1** [comment]
I am still receiving this error with 4.4.1.

**Comment by snipe** [comment]
The solution is already in the comments here.

**Comment by jmartins1** [comment]
I still receive the following issue. 

I’ve also run the following commands:

composer install --no-dev --prefer-source

composer dump-autoload

ALTER TABLE action_logs ENGINE = InnoDB (was successful)
ALTER TABLE assets ENGINE = InnoDB (was successful)

php artisan migrate (FAILED)

php artisan config:clear

php artisan config:cache

Ran the following and attempted again:

composer dump-autoload
composer clear-compiled
php artisan config:clear
php artisan view:clear
php artisan cache:clear
php artisan route:clear

**Comment by sid8000** [comment]
https://github.com/snipe/snipe-it/issues/5575#issuecomment-391221310

Did you delete already created indexes as per my comment?

**Comment by jmartins1** [comment]
I was able to get it working thank you. 

⁣Sent from BlueMail ​
