### ISSUE TITLE
Pre-Flight & Setup page no graphics + debug activated/not shown

### ISSUE THREAD

**Issue by eszeus** [snipe/snipe-it#5576]
Hello again,

my "Whoops" Problem is solved now, thanks for the help!
Now I can access the Website, but doesnt load the index.php file when browsing to my local-ip adress.
I must manually add /index.php at the end of the IP to reach the Pre-Flight & Setup page.

When I reach the Pre-Flight & Setup page it also doesnt show me the graphics, its text based only.
What exactly went wrong here?
info.php is working fine and showing me the php info page.
![dsc_0316](https://user-images.githubusercontent.com/1364619/40356356-16e707fe-5db9-11e8-8ba2-4131bb80ad7f.JPG)

Thanks for any help ;)

Debug IS turned ON. And it still thinks that I turned it Off in the Pre-Flight & Setup page....

**Comment by snipe** [comment]
I’d check your DirectoryIndex and rewrite rules.

**Comment by eszeus** [comment]
@snipe Checked rewrite rules, deactivated .htaccess for testing, checked DirectoryIndex in "/etc/apache2/mods-enabled/dir.conf" (all index.* as html, php etc are written there).

I cant figure out why it shouldnt be working.

If I browse to http://IP/ it doesnt redirect me to http://IP/**index.php** but it automatically redirects me to http://IP/**setup**

Also the graphics are not shown at the index.php as I posted above.


If you still think it could be "DirectoryIndex and rewrite rules" I would be very happy to get an explanation about how/what you mean with it :D 

Thanks again for the help! Really appreciate it ;)

**Comment by eszeus** [comment]
Can be closed. Figured it out :D

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
