### ISSUE TITLE
E-Mails not sending (Request, Question - no bug)

### ISSUE THREAD

**Issue by eszeus** [snipe/snipe-it#5583]
Hello there again,

I followed the instructions on 
https://snipe-it.readme.io/docs/configuration
and used my E-Mail Providers Settings but it isnt working yet.

Is there a deeper explanation about how to configure these specific elements? (mail)
Is it SSL or TLS? Is it 587 or 465? I cant figure this config out.

Any help and information about how to setup the Mail section would be awesome! 
Thanks ;)

**Comment by snipe** [comment]
@eszeus there isn’t a way for us to know that, since it depends on the setup of your email provider. Your best bet will be to contact your email administrator and ask them.
