### ISSUE TITLE
Can we use Azure Active Directory OAuth

### ISSUE THREAD

**Issue by jmas-tatsuya-ogawa** [snipe/snipe-it#5585]
We hope login with Azure AD OAuth.
So, we found following laravel plugin.
https://github.com/metrogistics/laravel-azure-ad-oauth
Is it possible to realize a SSO using this?

**Comment by surajsinghbais** [comment]
Could we set Oauth for office 365 in this? I tried. but didn't.

**Comment by aj-bayanat** [comment]
More relevant than ever now as Microsoft is going to stop legacy auth support in early 2023. Now there is a command line option to allow legacy auth for your 365 tenants but it's going to completely be gone very soon.
