### ISSUE TITLE
Can you update the background color for the login page? Also, can the login banner be more wide rather than narrow?

### ISSUE THREAD

**Issue by lry-rincon-jekyll** [snipe/snipe-it#5586]
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by snipe** [comment]
You can use the Custom CSS option in the Admin > Branding settings to override styles.
