### ISSUE TITLE
Can't delete persons

### ISSUE THREAD

**Issue by chreichwein** [snipe/snipe-it#5589]
[x ] I have enabled debug mode
[x ] I have read checked the Common Issues page
Fresh install
Snipe IT Version v4.1.14 - build 3382 (master)
PHP 7.2
MariaDB 10.0
Windows Server 2012 R2 IIS
GitHub installation

If I try to delete a person I get an error:

![image](https://user-images.githubusercontent.com/36449487/40475364-b5cd72a2-5f41-11e8-94e0-2f051779a734.png)

**Comment by chreichwein** [comment]
I upgraded to Version v4.4.1 - build 3636 (master) and the issues is solved now.

**Comment by snipe** [comment]
That was an issue with PHP7.2 changing the way `count()` works against null objects. We've been fixing those as we go, but if you see that particular error again elsewhere in the system, please let us know.

**Comment by chreichwein** [comment]
Hey again, now i have the same issue again. I did a complete new git installation with php 7.2 and maria db 10.0, Snipe-IT Version v4.4.1 - build 3636

![image](https://user-images.githubusercontent.com/36449487/41732147-99844b5c-7580-11e8-99e1-f0cb557716b5.png)

Do you guys have a solution for this ready?

**Comment by snipe** [comment]
This issue was already resolved. I cannot reproduce this locally or on the demo.

**Comment by chreichwein** [comment]
I try to give you more detail.
The db files and the imported users from the ad are from an older snipe-it version (v4.1.14). I made a new git installation. After that I migrated all other files from the old version (v4.1.14) to the new git installation (v4.4.1). All old imprted user can't be deleted, but if I import some new user I can delete them.

**Comment by chreichwein** [comment]
Well, i changed the php version from 7.2 to 7.1 - now everything is fine again, I can delete all users.
