### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by chreichwein** [snipe/snipe-it#5590]
[x ] I have enabled debug mode
[x ] I have read checked the Common Issues page
Fresh install
Snipe IT Version v4.3.0
PHP 7.2
MariaDB 10.0
Windows Server 2012 R2 IIS
GitHub installation

I have 1700 imported assets, when I try to view them in the assets view, it takes about 10 seconds to show up. If I try to sort them it also takes a while. When I downgrade to version 4.1.14 it goes very fast. I have no idea why that happens.

**Comment by chreichwein** [comment]
I upgraded to Version v4.4.1 - build 3636 (master) and the issues is solved now.

**Comment by pcsmarts502** [comment]
This was the fix a couple of weeks ago.    create index action_logs_item_id_item_type ON action_logs(item_id, item_type);  They created an index which speeded things up.  Check out this thread. https://github.com/snipe/snipe-it/issues/5511#issuecomment-390888892

**Comment by snipe** [comment]
@pcsmarts502 please do not recommend people make manual database changes. It only leads to complications down the line.

**Comment by pcsmarts502** [comment]
Ok sorry about that
