### ISSUE TITLE
Changing an encrypted custom text field leads to field losing it's encryption

### ISSUE THREAD

**Issue by hypnotoadts** [snipe/snipe-it#5591]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

Bug Description:
Changing an encrypted custom text field leads to field losing it's encryption

**To Reproduce**
1. Go to 'custom fields' and create a encrypted custom field of the type 'text'
2. Assign custom field to assets
3. Open an asset and insert a value into the custom field (the custom field is now readable for all user with corresponding roles)
4. Go to 'custom fields' and change the name of the newly created field.
5. The field is now readable by all users and shows the encrypted value

6. (Remedy) in sql: change the value 'field_encryption' for the custom field from 0 to 1 

*Expected behavior**
The custom field should stay encrypted after a change.

**Server (please complete the following information):**
 - Snipe-IT Version v4.1.11-pre - build 3307 (master)
 - OS: Debian 8 Jessie
 - Web Server: Apache
 - 7.2.2

**Desktop (please complete the following information):**
 - OS: Windows 7 
 - Browser: Chrome
 - Version: 66.0.3359.181

Note:
I'm totally aware that a name change of a custom field should not to be lightly done, but the change was made "by mistake".

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
This should be fixed on develop now and will be in the next release
