### ISSUE TITLE
License Error after v4.4.1

### ISSUE THREAD

**Issue by danr12** [snipe/snipe-it#5593]
#### Please confirm you have done the following before posting your bug report:

- [Yes ] I have enabled debug mode 
- [Yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When adding a new license it bombs out to the Whoops page. 
DEBUG shows:

3/3) QueryException

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category_id' in 'field list'
 (2/3) PDOException

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category_id' in 'field list'

 (1/3) PDOException

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category_id' in 'field list'
**To Reproduce**
Create new license, add your new license category and relevant info. then save. It then throws the whoops page.

**Server (please complete the following information):**
 - Snipe-IT Version 4.4.1
 - OS: [e.g. Ubuntu, CentOS] CentOS7
 - Web Server: [e.g. Apache, IIS] 
 - PHP Version 7.1.17 

I ran git pull from snipe it directory to upgrade and ran the usual commands to clear common issues (php artistan commands). 

Any ideas?

**Comment by danr12** [comment]
Also getting this when checking out items:

 (3/3) QueryException

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'checkout_counter' in 'field list' (SQL: update `assets` set `checkout_counter` = `checkout_counter` + 1, `updated_at` = 2018-05-24 16:40:40 where `id` = 231 and `assets`.`deleted_at` is null)

However they do appear to still check out anyway? Can anyone help shed some light please

**Comment by snipe** [comment]
You have to run migrations any time you upgrade Snipe-IT to pick up database changes that were made. 

`php artisan migrate`

https://snipe-it.readme.io/docs/upgrading#section-after-pulling-the-new-version-files
