### ISSUE TITLE
Feature Request: Asset Acceptance Notification

### ISSUE THREAD

**Issue by GeffenMetzger** [snipe/snipe-it#5596]
#### Expected Behavior (or desired behavior if a feature request)

I'd like to have an email or some sort of notification triggered when a user Accepts an asset. We are fairly strict about having users accept assets, so receiving an email when someone accepts would be extremely helpful.

-----

#### Actual Behavior

No email notification on acceptance 😢 

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

Running Snipe IT 4.3 on Windows 7 WAMP server

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by jjangmoo** [comment]
+1
