### ISSUE TITLE
403 On set up prior to Pre-Flight

### ISSUE THREAD

**Issue by PalmerCurling** [snipe/snipe-it#5597]
We are looking into setting up Snipe-IT and have run into issues with getting to the pre-flight step.
We battled through some issues (mostly cause we are flying somewhat blind into configuration of this for the first time in a long time) and suspect the issue is a PEBKAC, just looking to piece together why we're getting 403 Forbidden Errors when we try to hit the install.

 - Snipe-IT Version: Git cloned as of 5/21/18
 - OS: Ubuntu 18:04
 - Web Server: Apache
 - PHP Version: 7.2.5

Pretty sure it's Apache-config related, but I am just not sure where to go to resolve it.

We are running the Snipe-IT VirtualHost over port 81 as port 80 is being used for the VirtualHost for our Wiki. Alias is configured according to Snipe-IT documentation, edits made to site.conf in apache conf files and in the .htaccess file in Snipe-IT root. Perhaps .env url is incorrect for IP address? Currently it reads: App_URL=http://10.1.10.118:81/snipe-it.

Snipe IT install folder is ~/Snipe-IT, and apache conf is pointed at it - would the install folder not being in /var/www cause a problem?

Thanks in advance for the help!

**Comment by snipe** [comment]
Using subdirectories is a little trickier (versus a domain name, IP address, or subdomain), which is why we generally discourage it for newbies. We have documentation for that here: https://snipe-it.readme.io/docs/subdirectories

**Comment by PalmerCurling** [comment]
we had followed that page, but still getting the 403 error.

I need to confirm with my teammate as I had to leave early yesterday, but i believe we spun up a new Linux VM and decided to host separately (though i think he said he ran into an error there too - but it was a Snipe-IT error now not apache, so obviously the wheel of progress is slow but inevitable.)

**Comment by snipe** [comment]
Any updates?
