### ISSUE TITLE
Cannot delegate requested item emails to another email address

### ISSUE THREAD

**Issue by johnnygtech** [snipe/snipe-it#5598]
#### Please confirm you have done the following before posting your bug report:

- [ Y ] I have enabled debug mode 
- [ Y ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
There doesn't appear to be a way to configure an email address to receive item request notifications.  And the notifications area doesn't allow us to configure different recipients for different types of reports.

It also isn't clear where the email address for requestable assets is configured.  The emails which get sent do not appear to pull from the Settings-->Notifications email address conifguration.

**To Reproduce**
1. Attempt to configure an email address to receive item requests that isn't the same as the 'default' admin email recipient.

**Expected behavior**
There should be a way to delegate email recipients for notifications to different users other than the root admin user.

**Screenshots**
N/A

**Server (please complete the following information):**
 - Snipe-IT Version : v4.4.1  build 3636
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version: 7.2

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Error Messages**
N/A

**Additional context**
- Is this a fresh install or an upgrade? N/A
- What OS and web server you're running Snipe-IT on: See above
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): GIT
- Include what you've done so far in the installation, and if you got any error messages along the way.
We attempted to modify the settings in the Settings --> General --> Notifications section.  That email address setting doesn't appear to effect the desired behavior.
- Indicate whether or not you've manually edited any data directly in the database: No

Add any other context about the problem here:  If this is expected behavior the documentation does not indicate the procedure.  If it is not expected behavior this issue can be changed to a feature request.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
This is configurable in the Admin > Alerts settings.

<img width="666" alt="screen shot 2018-05-24 at 1 41 17 pm" src="https://user-images.githubusercontent.com/197404/40512596-34933b60-5f58-11e8-9fdd-a2f4a9e7eb3c.png">
