### ISSUE TITLE
UNREADABLE QR CODE

### ISSUE THREAD

**Issue by Flash1206** [snipe/snipe-it#5599]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I'm trying to print QR codes but some of them are missing modules, making the QR code unreadable

**To Reproduce**
1. Go to All ASSETS
2. Click on GENERATE LABELS
3. Scroll down to LABEL

**Expected behavior**
SHOW A COMPLETE AND READABLE QR CODE

**Screenshots**
https://i.imgur.com/dZXlAj7.png

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: WINDOWS 10
 - Web Server: GO DADDY
 - PHP Version LATEST

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by EarlRamirez** [comment]
@Flash1206 would you be able to paste the screenshot here? I am not able to see it from the link.

**Comment by snipe** [comment]
Also what do you mean by missing modules?

**Comment by Flash1206** [comment]
Hey! So I figured it out. Thanks for getting back to me. As for modules I was referring to the positions or "blocks" that appear on a QR code. All I did was duplicate my assets and my problem was resolved. Thanks again!

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
