### ISSUE TITLE
Bug in acceptance URL

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#560]
missing a : and a /

![image](https://cloud.githubusercontent.com/assets/10247644/6372177/1a776ca2-bcd0-11e4-95dc-6ce1c2a9acc1.png)

**Comment by snipe** [comment]
That email actually uses a config setting. Can you check your `app/config/<environment>/app.php` and check what your URL is set to? I think the slash might be missing there.

The email template literally uses `{{{ Config::get('app.url') }}}`

**Comment by kobie-chasehansen** [comment]
ugh. fixed... ty

**Comment by snipe** [comment]
:D

![break-the-internet](https://cloud.githubusercontent.com/assets/197404/6378113/05d69260-bcde-11e4-973a-c539efef2e46.gif)
