### ISSUE TITLE
Snipe-IT Pre-Flight: Config File not valid

### ISSUE THREAD

**Issue by TetrusP** [snipe/snipe-it#5600]
#### Expected Behavior (or desired behavior if a feature request)

I believe I installed everything properly, my document root is /var/www/html/snipe-it/public, so the .env file should not be readable by the outside world (I may be wrong, I am assuming based on research I have done online).

-----

#### Actual Behavior

I get this error: "Please make sure your .env is not readable by the outside world via web browser...[]"

The debug is on and gives me information that I do not really understand (new to databases/Apache)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?: **fresh install**
- Version of Snipe-IT you're running: **Most recent (git clone)**
- Version of PHP you're running: **Php7.0**
- Version of MySQL/MariaDB you're running: **MySql 5.7.22-0** 
- What OS and web server you're running Snipe-IT on: **Ubuntu 0.16.04.1,  Apache/2.4.18 (Ubuntu)**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): **Composer install**

**Below is my Apache configuration (document root is defined in apache2.conf as well**

<VirtualHost *:80>
        <Directory /var/www/html/snipe-it/public>
                Allow From All
                AllowOverride All
                Options +Indexes
        </Directory>

        DocumentRoot /var/www/html/snipe-it/public
        ServerName [server name]
        # Other directives here
</VirtualHost>

**Below is the full error I get when I browse to http://"server"/.env**

Whoops, looks like something went wrong.

(3/3) ErrorExceptionTrying to get property of non-object (View: /var/www/html/snipe-it/resources/views/layouts/basic.blade.php) (View: /var/www/html/snipe-it/resources/views/layouts/basic.blade.php)
--
in 20bb6b1db93f64f3404f69a3747dd824ab668cec.php (line 59)
at CompilerEngine->handleViewException(object(ErrorException), 1)in PhpEngine.php (line 44)
at PhpEngine->evaluatePath('/var/www/html/snipe-it/storage/framework/views/8a207de072a854e417922cb05701532971de60cd.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => false, 'exception' => object(NotFoundHttpException), 'snipeSettings' => null))in CompilerEngine.php (line 59)
at CompilerEngine->get('/var/www/html/snipe-it/resources/views/errors/404.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => false, 'exception' => object(NotFoundHttpException), 'snipeSettings' => null))in View.php (line 137)
at View->getContents()in View.php (line 120)
at View->renderContents()in View.php (line 85)
at View->render()in Response.php (line 38)
at Response->setContent(object(View))in Response.php (line 200)
at Response->__construct(object(View), 404, array())in ResponseFactory.php (line 55)
at ResponseFactory->make(object(View), 404, array())in ResponseFactory.php (line 69)
at ResponseFactory->view('errors::404', array('exception' => object(NotFoundHttpException)), 404, array())in Handler.php (line 195)
at Handler->renderHttpException(object(NotFoundHttpException))in Handler.php (line 173)
at Handler->prepareResponse(object(Request), object(NotFoundHttpException))in Handler.php (line 119)
at Handler->render(object(Request), object(NotFoundHttpException))in Handler.php (line 101)
at Handler->render(object(Request), object(NotFoundHttpException))in Pipeline.php (line 82)
at Pipeline->handleException(object(Request), object(NotFoundHttpException))in Pipeline.php (line 32)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php (line 51)
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php (line 25)
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php (line 56)
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php (line 35)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

(2/3) ErrorExceptionTrying to get property of non-object (View: /var/www/html/snipe-it/resources/views/layouts/basic.blade.php)
--
in 20bb6b1db93f64f3404f69a3747dd824ab668cec.php (line 59)
at CompilerEngine->handleViewException(object(ErrorException), 2)in PhpEngine.php (line 44)
at PhpEngine->evaluatePath('/var/www/html/snipe-it/storage/framework/views/20bb6b1db93f64f3404f69a3747dd824ab668cec.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => false, 'obLevel' => 1, 'exception' => object(NotFoundHttpException), 'snipeSettings' => null))in CompilerEngine.php (line 59)
at CompilerEngine->get('/var/www/html/snipe-it/resources/views/layouts/basic.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => false, 'obLevel' => 1, 'exception' => object(NotFoundHttpException), 'snipeSettings' => null))in View.php (line 137)
at View->getContents()in View.php (line 120)
at View->renderContents()in View.php (line 85)
at View->render()in 8a207de072a854e417922cb05701532971de60cd.php (line 28)
at include('/var/www/html/snipe-it/storage/framework/views/8a207de072a854e417922cb05701532971de60cd.php')in PhpEngine.php (line 42)
at PhpEngine->evaluatePath('/var/www/html/snipe-it/storage/framework/views/8a207de072a854e417922cb05701532971de60cd.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => false, 'exception' => object(NotFoundHttpException), 'snipeSettings' => null))in CompilerEngine.php (line 59)
at CompilerEngine->get('/var/www/html/snipe-it/resources/views/errors/404.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => false, 'exception' => object(NotFoundHttpException), 'snipeSettings' => null))in View.php (line 137)
at View->getContents()in View.php (line 120)
at View->renderContents()in View.php (line 85)
at View->render()in Response.php (line 38)
at Response->setContent(object(View))in Response.php (line 200)
at Response->__construct(object(View), 404, array())in ResponseFactory.php (line 55)
at ResponseFactory->make(object(View), 404, array())in ResponseFactory.php (line 69)
at ResponseFactory->view('errors::404', array('exception' => object(NotFoundHttpException)), 404, array())in Handler.php (line 195)
at Handler->renderHttpException(object(NotFoundHttpException))in Handler.php (line 173)
at Handler->prepareResponse(object(Request), object(NotFoundHttpException))in Handler.php (line 119)
at Handler->render(object(Request), object(NotFoundHttpException))in Handler.php (line 101)
at Handler->render(object(Request), object(NotFoundHttpException))in Pipeline.php (line 82)
at Pipeline->handleException(object(Request), object(NotFoundHttpException))in Pipeline.php (line 32)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php (line 51)
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php (line 25)
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php (line 56)
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php (line 35)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

(1/3) ErrorExceptionTrying to get property of non-object
--
in 20bb6b1db93f64f3404f69a3747dd824ab668cec.php (line 59)
at HandleExceptions->handleError(8, 'Trying to get property of non-object', '/var/www/html/snipe-it/storage/framework/views/20bb6b1db93f64f3404f69a3747dd824ab668cec.php', 59, array('__path' => '/var/www/html/snipe-it/storage/framework/views/20bb6b1db93f64f3404f69a3747dd824ab668cec.php', '__data' => array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => false, 'obLevel' => 1, 'exception' => object(NotFoundHttpException), 'snipeSettings' => null), 'obLevel' => 2, '__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => false, 'exception' => object(NotFoundHttpException), 'snipeSettings' => null))in 20bb6b1db93f64f3404f69a3747dd824ab668cec.php (line 59)
at include('/var/www/html/snipe-it/storage/framework/views/20bb6b1db93f64f3404f69a3747dd824ab668cec.php')in PhpEngine.php (line 42)
at PhpEngine->evaluatePath('/var/www/html/snipe-it/storage/framework/views/20bb6b1db93f64f3404f69a3747dd824ab668cec.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => false, 'obLevel' => 1, 'exception' => object(NotFoundHttpException), 'snipeSettings' => null))in CompilerEngine.php (line 59)
at CompilerEngine->get('/var/www/html/snipe-it/resources/views/layouts/basic.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => false, 'obLevel' => 1, 'exception' => object(NotFoundHttpException), 'snipeSettings' => null))in View.php (line 137)
at View->getContents()in View.php (line 120)
at View->renderContents()in View.php (line 85)
at View->render()in 8a207de072a854e417922cb05701532971de60cd.php (line 28)
at include('/var/www/html/snipe-it/storage/framework/views/8a207de072a854e417922cb05701532971de60cd.php')in PhpEngine.php (line 42)
at PhpEngine->evaluatePath('/var/www/html/snipe-it/storage/framework/views/8a207de072a854e417922cb05701532971de60cd.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => false, 'exception' => object(NotFoundHttpException), 'snipeSettings' => null))in CompilerEngine.php (line 59)
at CompilerEngine->get('/var/www/html/snipe-it/resources/views/errors/404.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => false, 'exception' => object(NotFoundHttpException), 'snipeSettings' => null))in View.php (line 137)
at View->getContents()in View.php (line 120)
at View->renderContents()in View.php (line 85)
at View->render()in Response.php (line 38)
at Response->setContent(object(View))in Response.php (line 200)
at Response->__construct(object(View), 404, array())in ResponseFactory.php (line 55)
at ResponseFactory->make(object(View), 404, array())in ResponseFactory.php (line 69)
at ResponseFactory->view('errors::404', array('exception' => object(NotFoundHttpException)), 404, array())in Handler.php (line 195)
at Handler->renderHttpException(object(NotFoundHttpException))in Handler.php (line 173)
at Handler->prepareResponse(object(Request), object(NotFoundHttpException))in Handler.php (line 119)
at Handler->render(object(Request), object(NotFoundHttpException))in Handler.php (line 101)
at Handler->render(object(Request), object(NotFoundHttpException))in Pipeline.php (line 82)
at Pipeline->handleException(object(Request), object(NotFoundHttpException))in Pipeline.php (line 32)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php (line 51)
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php (line 25)
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php (line 56)
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php (line 35)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

**Below is the addition log information**

#46 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#52 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#53 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#54 /var/www/html/snipe-it/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#55 {main}

**I've basically finished the installation, chances are that I may have missed something in the process if I am getting an error like this I just cant find it**

The only edits I've made into the database is create the mysql user

**Comment by snipe** [comment]
You shouldn't be browsing to the .env file - is your install working, or not?

**Comment by TetrusP** [comment]
I can continue through the Pre-Flight and get to the main page but with that error I am not comfortable using the application until I fix it. 

Does that error mean I am browsing the .env file? Wouldn't I be able to see its contents.

**Comment by TetrusP** [comment]
Not sure what happened, but after I went through the pre-flight, when I try to browse to /.env I get a 404 Page not found.

**Comment by snipe** [comment]
That's because the error was bring triggered because you hadn't completed pre-flight yet. Once you completed pre-flight, the settings table was populated, so you got a normal 404.
