### ISSUE TITLE
/hardware overview fields and content table are misaligned after a field is clicked for sorting

### ISSUE THREAD

**Issue by passboltUser** [snipe/snipe-it#5601]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [✔] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When I go to `/hardware`, scroll to the right, and click any of the fields on the right to sort, after sorting the scrollbar is positioned correctly, but the headlines are positioned wrongly.

**To Reproduce**
1. Go to `https://demo.snipeitapp.com/hardware`
2. Make sure the browser window is small enough so a scrollbar appears.
3. Scroll to the right
4. And click any of the fields there to sort
5. The fields are wrongfully positioned
6. The misalignment goes away after one moves the scrollbar slightly

**Expected behavior**
The headline fields and the scrollbar/item entries should be equally positioned vertically when a field is clicked for sorting. 

**Server (please complete the following information):**
 - Snipe-IT Version 
v4.4.1 - build 3636 (master)
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**
Happens for me with Firefox on Linux and windows
Firefox
 60

I did not post the other infos because this happens on your demo page too.

**Comment by snipe** [comment]
I believe that's a bug in the javascript library we use for table display. I'm not sure it's something we can fix. :-/

**Comment by passboltUser** [comment]
Which lib is it? I can file a bug report.

**Comment by passboltUser** [comment]
bug still there

**Comment by snipe** [comment]
@passboltUser we use Bootstrap tables, but I'm not sure which extension is the one that's triggering the issue.

**Comment by passboltUser** [comment]
@snipe How can I find the list the Bootstrap extensions used?
