### ISSUE TITLE
Categories not Displaying after Upgrade to 4.4.1

### ISSUE THREAD

**Issue by cwoods131** [snipe/snipe-it#5603]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After upgrading to 4.4.1 our Category data is still intact, however Snipe-IT is not displaying anything and says "No matching records found". This looks like it may be an SQL error where a column is not found. 

**To Reproduce**
1. After the upgrade to 4.4.1
2. Go to settings Categories
3. Categories displays "No matching record found"

We could also replicate by attempting to add a license (Our licenses is empty and unused)

**Expected behavior**
Display the existing categories that were entered in the previous version.

**Server (please complete the following information):**
 - Snipe-IT Version v4.4.1 - build 3636 (master)
 - PHP Version 7.0.25-0ubuntu0.16.04.1

**Desktop (please complete the following information):**
 - Win7 on Chrome 64

**Error Messages**
in larval.log

Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'licenses.category_id' in 'where clause' (SQL: select `id`, `created_at`, `updated_at`, `name`, `category_type`, `use_default_eula`, `eula_text`, `require_acceptance`, `checkin_email`, `image`, (select count(*) from `assets` inner join `models` on `models`.`id` = `assets`.`model_id` where `models`.`deleted_at` is null and `categories`.`id` = `models`.`category_id` and `models`.`deleted_at` is null and `assets`.`deleted_at` is null) as `assets_count`, (select count(*) from `accessories` where `categories`.`id` = `accessories`.`category_id` and `accessories`.`deleted_at` is null) as `accessories_count`, (select count(*) from `consumables` where `categories`.`id` = `consumables`.`category_id` and `consumables`.`deleted_at` is null) as `consumables_count`, (select count(*) from `components` where `categories`.`id` = `components`.`category_id` and `components`.`deleted_at` is null) as `components_count`, (select count(*) from `licenses` where `categories`.`id` = `licenses`.`category_id` and `licenses`.`deleted_at` is null) as `licenses_count` from `categories` where `categorie `.`deleted_at` is null order by `assets_count` asc limit 20 offset 0) in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php:647
in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php:647
Next Illuminate\Database\QueryException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'licenses.category_id' in 'where clause' (SQL: select `id`, `created_at`, `updated_at`, `name`, `category_type`, `use_default_eula`, `eula_text`, `require_acceptance`, `checkin_email`, `image`, (select count(*) from `assets` inner join `models` on `models`.`id` = `assets`.`model_id` where `models`.`deleted_at` is null and `categories`.`id` = `models`.`category_id` and `models`.`deleted_at` is null and `assets`.`deleted_at` is null) as `assets_count`, (select count(*) from `accessories` where `categories`.`id` = `accessories`.`category_id` and `accessories`.`deleted_at` is null) as `accessories_count`, (select count(*) from `consumables` where `categories`.`id` = `consumables`.`category_id` and `consumables`.`deleted_at` is null) as `consumables_count`, (select count(*) from `components` where `categories`.`id` = `components`.`category_id` and `components`.`deleted_at` is null) as `components_count`, (select count(*) from `licenses` where `categories`.`id` = `licenses`.`category_id` and `licenses`.`deleted_at` is null) as `licenses_count` from `categories` where `categorie `.`deleted_at` is null order by `assets_count` asc limit 20 offset 0) 

Whoops, looks like something went wrong.
(3/3) QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category_id' in 'field list' (SQL: insert into `licenses` (`company_id`, `depreciation_id`, `expiration_date`, `license_email`, `license_name`, `maintained`, `manufacturer_id`, `name`, `notes`, `order_number`, `purchase_cost`, `purchase_date`, `purchase_order`, `reassignable`, `seats`, `serial`, `supplier_id`, `category_id`, `termination_date`, `user_id`, `updated_at`, `created_at`) values (, , , , , 0, 45, Aleir, , , , , , 1, 1, dddd, , 26, , 6048, 2018-05-25 09:19:01, 2018-05-25 09:19:01))

**Comment by snipe** [comment]
Did you run migrations?

**Comment by cwoods131** [comment]
We used the update script and then ran migrations manually after. Upon running it again, we are getting these:

In Connection.php line 647:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_cust
  om_fields' already exists (SQL: create table `models_custom_fields` (`id` i
  nt unsigned not null auto_increment primary key, `asset_model_id` int not n
  ull, `custom_field_id` int not null, `default_value` text null) default cha
  racter set utf8mb4 collate utf8mb4_unicode_ci)


In PDOStatement.php line 107:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_cust
  om_fields' already exists

In PDOStatement.php line 105:

 SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_cust
  om_fields' already exists

**Comment by cwoods131** [comment]
It looks like someone in the department had altered the database that we were unaware of. Please disregard this ticket. This was our fault. My apologies. Upon seeing that error we figured out the issue.

Thank you

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
