### ISSUE TITLE
What User Permission do i set to see Acceptance page?

### ISSUE THREAD

**Issue by JulMac007** [snipe/snipe-it#5604]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version - v4.3.0 build 3586 (gec1fa8e90) 
 - OS: [e.g. Ubuntu, CentOS] - CentOS7
 - Web Server: [e.g. Apache, IIS] - Apache
 - PHP Version -  7.1.17

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Windows 7 
 - Browser [e.g. chrome, safari] Firefox and IE
 - Version [e.g. 22] = 60.0.1 and 11

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? - Fressh
- What OS and web server you're running Snipe-IT on CentOS 7, Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

What permission do I need to set for non-admin user so that they can see the Acceptance page?
I did a lot of testing with granular permission setting, the only time it shows the Acceptance page with Accept or Decline radio button is when i set the user's permission with Global: Super User - Grant.
a
the page gives Error:  Insufficient permissions!   if a user doesn't have grant permission on Global: Super User.

**Comment by snipe** [comment]
> What permission do I need to set for non-admin user so that they can see the Acceptance page?

You just need "View Requestable Assets" (in the Assets section of permissions). Make sure neither the user nor group deny that permission.

**Comment by snipe** [comment]
Actually, I misunderstood. No special permissions are needed for the user to see an acceptance page with the accept/decline options - but the person who is logged in has to be the person the item was checked out to.

**Comment by JulMac007** [comment]
hi @snipe thanks for the reply.

I clicked on the email linked that says "**I have read and agree to the terms of use, and have received this item**"

Logged on Snipe-IT with the account that the asset was checked out to and received this error after logging in.
![image](https://user-images.githubusercontent.com/38925170/40683986-f2b432a8-6344-11e8-99e9-067445abdf46.png)

The only time that I can view the accept/decline options is when i granted a user with Super: Global user
