### ISSUE TITLE
can't set up snipe-it as apache subdirectory

### ISSUE THREAD

**Issue by fazlerabbi37** [snipe/snipe-it#5609]
#### Please confirm you have done the following before posting your bug report:

- [NO ] I have enabled debug mode 
- [ YES] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I have a Ubuntu 16.04 Server where I have a few other service deployed. I used installer to install snipe-it though I know it say's it is expecting a clean Ubuntu Server. I sill used installer thinking that I would be able to twick the apache conf file to serve snipe-it as a subdirectory. I gave the private address of ``10.10.10.10`` as the fqdn as I was planing to server in with the local network. When the installation finised I opened the snipeit.conf file and modified the file as follows::

    <VirtualHost *:80>

    Alias /snipeit "/var/www/snipeit/public"

        <Directory /var/www/snipeit/public>
                Allow From All
                AllowOverride All
                Options +Indexes
        </Directory>

        DocumentRoot /var/www/snipeit/public
        ServerName 10.10.10.10
        # Other directives here
    </VirtualHost>

I expected to go to the link [10.10.10.10/snipeit](10.10.10.10/snipeit) and see the pre-flight check. When I enter the [10.10.10.10/snipeit](10.10.10.10/snipeit), it redricted to [10.10.10.10/setup](10.10.10.10/setup). I smply entered the ip address: [10.10.10.10](10.10.10.10) and hoped to see all the subdrictories but again it redricted me to [10.10.10.10/snipeit](10.10.10.10/snipeit). How can I fix it?

**Server (please complete the following information):**
 - Snipe-IT: master  
 - OS: Ubuntu 16.04 Server
 - Web Server: Apache
 - PHP Version: 7.1

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 Desktop
 - Browser: chrome
 - Version: 66

**Comment by fazlerabbi37** [comment]
@snipe it is still relevant as I am still stuck with the situation. would be glad if you could please have a look into it. happy to provide any additional details if necessary.

**Comment by fazlerabbi37** [comment]
thank you very much! really looking forward to it.

**Comment by EarlRamirez** [comment]
I was able to test this and it works right off the bat; however, I both options are working for the default configuration (without the subdirectory) and the subdirectory. 
Did you update the .htaccess file located in the public directory of snipeit? _/var/www/html/snipeit/public/.htaccess_

**Comment by fazlerabbi37** [comment]
Thank you very much! I made a mistake while editing ``.htaccess`` file which I fixed and now it works fine!

**Comment by MELKHATEEB** [comment]
@fazlerabbi37  I have the same issue ?! , please tell me how did you solve it ?!

**Comment by fazlerabbi37** [comment]
@MELKHATEEB see this [part](https://snipe-it.readme.io/docs/subdirectories#section-modify-your-htaccess) of the documentaton.

**Comment by MELKHATEEB** [comment]
@fazlerabbi37  already did that

**Comment by fazlerabbi37** [comment]
Can you share your snipe-it.conf, httpd.conf, and .htaccess? Not sure how much can I help but maybe something you simply overlooked?

**Comment by MELKHATEEB** [comment]
this snipe-it.conf :
<VirtualHost *:80>

    Alias /snipe-it "/var/www/snipe-it/public"

        <Directory /var/www/snipe-it/public>
                Allow From All
                AllowOverride All
                Options +Indexes
        </Directory>

        DocumentRoot /var/www/snipe-it/public
        #ServerName localhost
        ServerName x.x.x.x
        # Other directives here
</VirtualHost>

and this .htaccess in snipe-it/public directory : 

<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On
    RewriteBase /snipe-it

    # Uncomment these two lines to force SSL redirect in Apache
    # RewriteCond %{HTTPS} off
    # RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Security Headers
    # Header set Strict-Transport-Security "max-age=2592000" env=HTTPS
    # Header set X-XSS-Protection "1; mode=block"
    # Header set X-Content-Type-Options nosniff
    # Header set X-Permitted-Cross-Domain-Policies "master-only"

</IfModule>
Options -Indexes

**Comment by MELKHATEEB** [comment]
it's existing, but i don't know why it gone when i copied this part

**Comment by fazlerabbi37** [comment]
if it exists then it should not be a problem.
