### ISSUE TITLE
When a hardware asset is checked in the software assigned sticks with machine

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#561]
Found a case today where a laptop with software assigned was checked back in from a user. would be nice if in this case the software automatically checks back in as well.

![image](https://cloud.githubusercontent.com/assets/10247644/6372357/9c313e48-bcd1-11e4-9005-e5bcc8747df2.png)

![image](https://cloud.githubusercontent.com/assets/10247644/6372434/35bdc9dc-bcd2-11e4-92f8-10390e42a542.png)

**Comment by snipe** [comment]
Would need to make sure we only set it back to checked in if the license is checked out to a person, not an asset

**Comment by kobie-chasehansen** [comment]
yes, and I think check it back in if its checked out to the asset and user. Right now say an Office license we check out to the asset and the user. maybe we should just check it out to the asset.

**Comment by snipe** [comment]
Hrm. You shouldn't be able to check it out to both. :-/

**Comment by kobie-chasehansen** [comment]
oh... lol well then

**Comment by snipe** [comment]
![tumblr_inline_nk79njr5yo1raprkq](https://cloud.githubusercontent.com/assets/197404/6378699/e8084aa4-bce1-11e4-99de-1e61581255af.gif)

**Comment by BrettFagerlund** [comment]
Checking out to the asset or user depending on the licence type does seem to be the only way.
Licences for office can be like 1 user, 5 device so isn't really supported unless user and asset seats become separate.
OEM office on the asset, and FPP/OPEN on the user is what fits us well.

If you shouldn't be able to check out to an asset and user together then there's a bug in there, as we initially did the same thing.

**Comment by diwanicki** [comment]
Maybe an option to also check in all assigned software when checking asset back in? If I'm returning a unit to stock, but it is already configured for reissue I don't want to release all of the software. If a unit is coming in for a re image or disposal then I do want to release all licenses associated with it.




A checkbox below the Notes field? A dialog box which comes up when checkin is clicked?



—

**Comment by nickmacwiz** [comment]
maybe I'm not understanding this correctly but shouldn't the license only be checked in AFTER it is REMOVED from the computer?

**Comment by kobie-chasehansen** [comment]
In my use case we assume all machines being checked in are going to be reimaged.
