### ISSUE TITLE
Normal User Dashboard

### ISSUE THREAD

**Issue by mahesh2471990** [snipe/snipe-it#5613]
** Server:**
 - Snipe-IT Version : 4.4.0
 - OS: Windows Server 2016
 - Web Server: IIS
 - PHP Version : 5.56

**Is your feature request related to a problem? Please describe.**
When Normal User Login. Who is not having permission to edit. The User will be able to see the Asset which is checked in. I would recommend the user must about see many more fields of the Particular Asset.

Example : 
![capture](https://user-images.githubusercontent.com/16305213/40618655-d4673a4c-62af-11e8-9f8b-9bdbdb96d5a7.JPG)

Above image, you see only a few things we can see. Like Category / Asset Tag / Name / Model / Image.
I would tell user able to many more things on the Asset. 

Like I have custom Field of RAM/CPU/HDD/OS. Many more default things like Purchase Date/ Warranty etc. It must customize that we can select each field which to view.

I have checkout the one laptop to User A, with 8GB RAM 500GB etc. If any of the RAM is misused by User A, we can show him that he has accepted the same configuration before as EULA. So in future, we upgrade to 16GB Ram we can update the same for that asset. So he can see the Upgrade things also. That would best feature. Where we can customize the things which can view by User A.

Giving View of Assets will view all the assets of the company. Which is not Good.

**Describe the solution you'd like**
Permission Tab should be adding to the fields to view by default by a normal user.
**Describe alternatives you've considered**

**Comment by snipe** [comment]
As mentioned in your ticket #5615, this is not on the short term roadmap, as we would need to make that customizable for admins. Many admins want only limited data exposed to the user.

**Comment by mahesh2471990** [comment]
This is ok I have done some hardcoded in snipe-it\resources\views\account\view-assets.blade.php. Adding 
<td>{{ $asset->_snipeit_ram_2}}</td>
 <td>{{ $asset->_snipeit_operating_system_4}}</td>
I able to see the customise things when normal user login
