### ISSUE TITLE
Total cost of a person

### ISSUE THREAD

**Issue by fabry756** [snipe/snipe-it#5614]
**Server (please complete the following information):**
 - Snipe-IT Version v4.3.0.
 - OS: CentOS
 - Web Server: Apache
 - PHP Version 7.1.17

**Is your feature request related to a problem? Please describe.**
Hi snipe, I need to see the total cost about a person. Is this possible?

**Describe the solution you'd like**
If i search an ID/username/person in people section, I'd like to see the cost for person as for license/accessories/assets

**Comment by snipe** [comment]
We would have to see how much this could potentially impact performance on larger systems.

**Comment by fabry756** [comment]
Is it possible to insert this feature as an optional feature that you can enable/disable? For my company (100-110 employees) could be an interesting feature

**Comment by memtech3** [comment]
A person is priceless...

**Comment by fabry756** [comment]
It is not true that a person is priceless :) for example, my company want to know how much cost an employee (asset, license, accessories....)

**Comment by memtech3** [comment]
No Stale! BOOO!

**Comment by jaydenrussell** [comment]
Staff Technology costs are something that management wants to see. It also highlights the hidden costs for additional hardware and software that is added adhoc

**Comment by adamfortin** [comment]
Hi, I really want to use implement Snipe-IT but my manager needs to be able to do reports of user's costs to his superior... I would really like this implementation...

**Comment by tymik** [comment]
+1, i find this useful too!

**Comment by adamfortin** [comment]
Still relevant Stale Bot...

**Comment by adamfortin** [comment]
Still relevant

**Comment by adamfortin** [comment]
YESSSSSSSSSSSSSSS

**Comment by adamfortin** [comment]
Still relevant...

**Comment by bcourtade** [comment]
Still relevant Stale Bot...

**Comment by Ng-marelec** [comment]
Still relevant!
A person or location or department or ... has X assets of cost Xcost, Y licenses with Ycost and Z accessories with Zcost.
Total should be X*Xcost+Y*Ycost+Z*Zcost...
This is very relevant as a way to prevent/maintain cost tracking.
