### ISSUE TITLE
Manager must have view of his team Member Assets

### ISSUE THREAD

**Issue by mahesh2471990** [snipe/snipe-it#5615]
- Snipe-IT Version 4.4.0
 - OS: Windows Server 2016
 - Web Server: IIS
 - PHP Version 5.56

**Is your feature request related to a problem? Please describe.**
I have already requested the same feature 2 years ago. 

Example: **Two Users Alba and Tim both of Manager is Alan.**
Alba is having two assets (One is Laptop and one PC)
Tim is having Two Assets (One is Mobile and MAC)
Alan is Having one asset (Laptop)

When Tim login(Normal User) He can see the details of Mobile configuration and Mac Configuration things which are checked out to him.

Same to Alba also. when she login she can see her assets in the dashboard.

But When I have assigned Reporting Manager of Alba and Tim is **Alan.**

When Alan login he can see only his Laptop Configuration things in his Dashboard.

I request you add a new feature. Alan Login (As he is Manager) We can only see Alba and Tim Assets also.
So he is also responsible if any asset is changed ownership by the Alba and Tim itself. He can also track the thing used by his team. He will aware what and all asset for his project.

All company wants have IT Asset tool where they can track who is using what assets. All company IT Admin or Asset Admin checkout any Asset according to their Manager Approval users. Even Many managers will not be having details what and all asset is used by their teams. because always Team grows. This is only tools almost all things are matching. Past two years this tool is much better.

I suggest who is Reporting Manager(Tima and Alba) Must have the things clear where Alan can plan accordingly.
I suggest Manager must have only the view option to Assets of their team, **_not all assets_**. If they have access to see all assets everything will _**be the mess.**_ Only IT admin or Asset admin can see all things. 

Reporting Manager should be to see their team members used assets **only.**

Manager Login he should have a new tab called **Teams.**
The main dashboard he can see his assets which is checkout.

When he clicks on **Teams** tab. List of all users who are reporting to him should be view even all the assets used by them. 

And also Dashboard for normal User login must have a view of more fields of the Asset. The best option for Custom Field you have implemented @snipe (Thank you). You are awesome, the Same way the custom field or any default field should be viewed in the dashboard for normal user login.

**Comment by snipe** [comment]
This isn't on the short term roadmap, but we would consider accepting a pull request if someone wanted to work on it. 

> And also Dashboard for normal User login must have a view of more fields of the Asset. 

Also not on the short term roadmap, as we would need to make that customizable for admins. Many users want only limited data exposed to the user.

**Comment by mahesh2471990** [comment]
@snipe I Agree with you many admins required fewer data to be shown. If you customize for each it would be awesome. 
I Suggest you use the same view which already we have. Normal Dashboard should be like below snapshot

![capture](https://user-images.githubusercontent.com/16305213/40700275-85e43d3c-63f6-11e8-96ac-1d2cfda411e8.JPG)

**When the normal User login if User has many assets checked out. The user must be able to click on the Asset Tag.** _where we don't have that option for the normal user as of now_.  **Normal User should get above view.  Above view is pretty good and cool. When the user can see the image of asset at the side in full pledge and all remaining Configuration. Normal User will be happy to watch the things** ONLY VIEW OPTION IS RECOMMENDED. SO USER CAN SEE THE CUSTOM FIELD DETAILS ALSO. LIKE (mac address, ram, Cpu, Os, HDD etc). Even some default details where we can customize the **cost** of the asset is not required to be viewed by Normal User. they many things we need/may not need to be viewed.

So better we can use the checkbox in front of all the field which should be viewed/not view in Dashboard.

Some admin tells they need minimal information. For admin end its good. An example we are adding an image to assets. When normal user login they can see the image, but its very small. Above view is pretty good. where I was talking about.

Now we have this view for Default User. Where it's boring and not so cool to view. Its Tiny and not more details of the Asset are there. when we can click on asset tag. nothing working. below image
![40618655-d4673a4c-62af-11e8-9f8b-9bdbdb96d5a7](https://user-images.githubusercontent.com/16305213/40700434-1e5d54d6-63f7-11e8-9eab-2f691eb0fea6.JPG)

I hope @snipe. This feature will improve your product more. Just give click option on asset tag so he can some more information with the first snapshot I mentioned. 
**What to be viewed what not to be viewed** should be customized by adding a checkbox to all fields or in settings you have an option as Labels. See the Below image.

Add the labels here which is required. This would be easy and awesome

![capturelablles](https://user-images.githubusercontent.com/16305213/40701311-1c7b007e-63fb-11e8-8900-211d0adc7a3a.JPG)


@snipe : I had another feature regarding Managers. You didn't reply for that. This is very important i feel.

**Comment by mahesh2471990** [comment]
@snipe Any Update on this

**Comment by snipe** [comment]
@mahesh2471990 As I said, it isn't on the short term roadmap, but we would consider accepting a pull request if someone wanted to work on it.

**Comment by snipe** [comment]
@mahesh2471990 As I said, it isn't on the short term roadmap, but we would consider accepting a pull request if someone wanted to work on it.

**Comment by RichardBouwman** [comment]
Hello @snipe , i've seen your awnser multiple times. 

I only wish to see a manager tab on the home screen where the manager is able to see all the assest assigned to members of his crew. And wish to exclude all the other assests.

I couldn't find any open issues regarding this request. With this reply I hope the issue get's reopend and hopefully someone can build something like that for Snipe-IT. 

Last but not least, thanks for building Snipe-IT it already helps a lot.

**Comment by Oddalmighty** [comment]
Hello @snipe! (I'm not sure if it's appropriate to re-open this issue or if I should have created a new one). Have there been any plans / development to allow managers to see all staff assets? We have the same issue. We have assets assigned to individual staff, but managers are only able to see their own or all assets in the system. Giving them access to all assets is not ideal and overwhelming for those outside our IT department. We'd like to see managers log in and be able to print off all assets assigned to them and their staff during our inventory process.

Thank you for all you do and for a brilliant tracking system. It has completely transformed the tech flow in our agency.

**Comment by SSzretter** [comment]
I need this feature as well and added it quickly so while this is not quality code it worked for my use case.    For my situation I want the manager to be able to log in and see not only the assets checked out to them but also assets check out to their direct reports AND assets checked out the department they are set to.   

It would be great if someone could clean this up, add a setting to enable it and merge it in.  I know it is going to be very useful here.  Sorry for the poor formatting of the code below, this comment system does not seem to like my linebreaks when pasting code.


I modified:

\vapp\http\controllers\viewassetscontroller.php
   function getIndex()
  before the  isset($user->id) and the return view, I added this (I am not 100% familiar with laravel syntax for queries so I used a sql query):

`$staffassets = \DB::select('SELECT assets.*, models.name AS modelname, categories.name AS categoryname, users.username, locations.name AS locname, departments.name AS depname FROM assets RIGHT JOIN users ON users.id = assets.assigned_to LEFT JOIN locations ON locations.id = users.location_id LEFT JOIN departments ON departments.id = users.department_id LEFT JOIN models ON models.id = assets.model_id LEFT JOIN categories ON categories.id = models.category_id  WHERE users.manager_id = ?', [$user->id]);`
	
`$departmentassets = \DB::select('SELECT assets.*, models.name AS modelname, categories.name AS categoryname
, users.username, locations.name AS locname, departments.name AS depname ,um.username AS managersName FROM assets left JOIN users ON users.id = assets.assigned_to LEFT JOIN users um ON um.id = users.manager_id left JOIN departments ON departments.id = users.department_id LEFT JOIN locations ON locations.id = users.location_id LEFT JOIN models ON models.id = assets.model_id LEFT JOIN categories ON categories.id = models.category_id WHERE users.department_id = ? ORDER BY um.username, users.username', [$user->department_id]);`

I also changed the 'return view(' line so it passes my two new variables:

`return view('account/view-assets', compact('user', 'userlog', 'staffassets','departmentassets'))`


I changed the blade :
  \resources\views\account\view-assets.blade.php
(below the div row that displays their own assets, I added two more div rows for direct report assets and department assets)


` <div class="row">   <div class="col-md-12">     <div class="box box-default">          @if ($user->id)           <div class="box-header with-border">             <div class="box-heading">               <h2 class="box-title">Assets assigned to direct reports</h2>             </div>           </div><!-- /.box-header -->         @endif        <div class="box-body">         <!-- checked out assets table -->           <div class="table-responsive">              <table                   data-cookie="true"                   data-cookie-id-table="userAssets"                   data-pagination="true"                   data-id-table="userAssets"                   data-search="true"                   data-side-pagination="client"                   data-show-columns="true"                   data-show-export="true"                   data-show-refresh="true"                   data-sort-order="asc"                   id="userAssets"                   class="table table-striped snipe-table"                   data-export-options='{                   "fileName": "my-assets-{{ date('Y-m-d') }}",                   "ignoreColumn": ["actions","image","change","checkbox","checkincheckout","icon"]                   }'>               <thead>               <tr>                 <th>#</th>                 <th class="col-md-1" data-switchable="true" data-visible="true">{{ trans('general.category') }}</th>                 <th class="col-md-1" data-switchable="true" data-visible="true">{{ trans('admin/hardware/table.asset_tag') }}</th>                 <th class="col-md-1" data-switchable="true" data-visible="true">{{ trans('general.name') }}</th>                 <th class="col-md-1" data-switchable="true" data-visible="true">{{ trans('admin/hardware/table.asset_model') }}</th>                 <th class="col-md-1" data-switchable="true" data-visible="true">{{ trans('admin/hardware/table.serial') }}</th>                 <th class="col-md-1" data-switchable="true" data-visible="true">username</th> 				 <th class="col-md-1" data-switchable="true" data-visible="true">location</th> 				  <th class="col-md-1" data-switchable="true" data-visible="true">department</th> 				   <th class="col-md-1" data-switchable="true" data-visible="true">lastCheckedOut</th>               </tr>                </thead>               <tbody>                 @php                   $counter = 1                 @endphp                 @foreach ($staffassets as $asset)                 <tr>                   <td>{{ $counter }}</td> 				   <td>{{ $asset->categoryname }}</td> 				    <td>{{ $asset->asset_tag }}</td> 				   <td>{{ $asset->name }}</td> 				                                       <td>{{ $asset->modelname }}</td>                                    <td>{{ $asset->serial }}</td>                    <td>{{ $asset->username }}</td> 					   <td>{{ $asset->locname }}</td> 					   <td>{{ $asset->depname }}</td> 					    					   <td>{{ $asset->last_checkout }}</td>                 </tr>                                 @php                   $counter++                 @endphp                 @endforeach               </tbody>             </table>           </div> <!-- .table-responsive-->       </div> <!-- .box-body-->     </div><!--.box.box-default-->   </div> <!-- .col-md-12--> </div> <!-- .row--> `

` <div class="row">   <div class="col-md-12">     <div class="box box-default">          @if ($user->id)           <div class="box-header with-border">             <div class="box-heading">               <h2 class="box-title">Assets assigned to DEPARTMENT</h2>             </div>           </div><!-- /.box-header -->         @endif        <div class="box-body">         <!-- checked out assets table -->           <div class="table-responsive">              <table                   data-cookie="true"                   data-cookie-id-table="userAssets"                   data-pagination="true"                   data-id-table="userAssets"                   data-search="true"                   data-side-pagination="client"                   data-show-columns="true"                   data-show-export="true"                   data-show-refresh="true"                   data-sort-order="asc"                   id="userAssets"                   class="table table-striped snipe-table"                   data-export-options='{                   "fileName": "my-assets-{{ date('Y-m-d') }}",                   "ignoreColumn": ["actions","image","change","checkbox","checkincheckout","icon"]                   }'>               <thead>               <tr>                 <th>#</th>                 <th class="col-md-1" data-switchable="true" data-visible="true">{{ trans('general.category') }}</th>                 <th class="col-md-1" data-switchable="true" data-visible="true">{{ trans('admin/hardware/table.asset_tag') }}</th>                 <th class="col-md-1" data-switchable="true" data-visible="true">{{ trans('general.name') }}</th>                 <th class="col-md-1" data-switchable="true" data-visible="true">{{ trans('admin/hardware/table.asset_model') }}</th>                 <th class="col-md-1" data-switchable="true" data-visible="true">{{ trans('admin/hardware/table.serial') }}</th>                 <th class="col-md-1" data-switchable="true" data-visible="true">username</th> 				 <th class="col-md-1" data-switchable="true" data-visible="true">location</th> 				  <th class="col-md-1" data-switchable="true" data-visible="true">department</th> 				   <th class="col-md-1" data-switchable="true" data-visible="true">lastCheckedOut</th> 				   <th class="col-md-1" data-switchable="true" data-visible="true">managersName</th>               </tr>                </thead>               <tbody>                 @php                   $counter = 1                 @endphp                 @foreach ($departmentassets as $asset)                 <tr>                   <td>{{ $counter }}</td> 				   <td>{{ $asset->categoryname }}</td> 				    <td>{{ $asset->asset_tag }}</td> 				   <td>{{ $asset->name }}</td> 				                                       <td>{{ $asset->modelname }}</td>                                    <td>{{ $asset->serial }}</td>                    <td>{{ $asset->username }}</td> 					   <td>{{ $asset->locname }}</td> 					   <td>{{ $asset->depname }}</td> 					    					   <td>{{ $asset->last_checkout }}</td> 					   <td>{{ $asset->managersName }}</td> 					    					                    </tr>                                 @php                   $counter++                 @endphp                 @endforeach               </tbody>             </table>           </div> <!-- .table-responsive-->       </div> <!-- .box-body-->     </div><!--.box.box-default-->   </div> <!-- .col-md-12--> </div> <!-- .row--> `
