### ISSUE TITLE
Asset File Previews Open Twice

### ISSUE THREAD

**Issue by joepitt91** [snipe/snipe-it#5616]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When clicking on uploaded images of assets, under the Files tab, the lightbox with the image open twice, so when dismissing the preview, you have to click the  backstage twice, and see the lightbox fade out twice.

**To Reproduce**
1. Go to '/hardware/305#files'
2. Click on a preview in the image column
3. click the greyed out background: the background becomes slightly lighted and one lightbox can be seen closing
4. click the greyed out background: the page becomes active again and the remaining lightbox can be seen closing

**Expected behavior**
Lightbox should only open once, and be dismissed with a single click

**Screenshots**
After opening preview
![2018-05-28](https://user-images.githubusercontent.com/16159859/40626903-702a5484-62b3-11e8-8dcf-b432b5bb1577.png)

after first click on background (notice the background is slightly lighter)
![2018-05-28 1](https://user-images.githubusercontent.com/16159859/40626913-78cf33ac-62b3-11e8-8217-922b0787b41b.png)

**Server (please complete the following information):**
 - Snipe-IT Version **v4.4.1**
 - OS: [e.g. Ubuntu, CentOS] **Ubuntu**
 - Web Server: [e.g. Apache, IIS] **Apache**
 - PHP Version **v7.0.30**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] **Windows 10**
 - Browser [e.g. chrome, safari] **Chrome & IE**
 - Version [e.g. 22] **v66.0.3359.181 & v11 (respectively)**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **No Error**
- If a stacktrace is provided in the error, include that too. **No stacktrace**
- Any errors that appear in your browser's error console. **No Error**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. **Yes**
- Include any additional information you can find in `storage/logs` and your webserver's logs. **No Log Entries**

**Additional context**
- Is this a fresh install or an upgrade? **Upgrade**
- What OS and web server you're running Snipe-IT on **Ubuntu & Apache**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Git clone to install and php upgrade.php to upgrade**
- Include what you've done so far in the installation, and if you got any error messages along the way. *installed, configured and populated without error**
- Indicate whether or not you've manually edited any data directly in the database **No**

Add any other context about the problem here. **Nothing to add**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Weirdly, I used to be able to reproduce this last week both locally and on the demo, but now I cannot, on Safari/Chome/Firefox/Brave. I'm genuinely confused.

**Comment by snipe** [comment]
Aha - I take it back. I can reproduce it. It's not happening in other places where the modal appears, just there.

**Comment by snipe** [comment]
This is fixed on develop and will be in the next release/merge to master
