### ISSUE TITLE
Model column width in the 'assets' view

### ISSUE THREAD

**Issue by knightlightning** [snipe/snipe-it#5618]
**Server (please complete the following information):**
 - Snipe-IT Version v4.4.1 - build 3636 (master)
 - OS: [e.g. Ubuntu, CentOS] Ubuntu 18.04
 - Web Server: [e.g. Apache, IIS] Apache 2.4
 - PHP Version PHP 7.2.5-0ubuntu0.18.04.1

**Is your feature request related to a problem? Please describe.**
It seems that no matter how long a model's name is it renders as a single line in the 'assets' view. This causes the scrollbar to appear at the bottom. It's inconvenient because action buttons become hidden and to edit an asset you should first scroll to bottom of the page (to see horisontal scrollbar) then scroll to right after that scroll back to the asset you was going to edit and only then will you be able to push the 'update' button. Now, 'models' view behaves correctly here. It's able to break a model's name to multi-string. Is it possible to implement same behavior in all the views?

**Describe the solution you'd like**
Break long text lines to multi-strings in 'all assets' view to prevent horizontal scrollbar from appearing as long as possible.

**Describe alternatives you've considered**
Make actions buttons (don't know how to name it correctly) available regardless of the scrollbar's position.

**Additional context**

![screen1](https://user-images.githubusercontent.com/13230743/40641594-0cbaab54-633c-11e8-8901-5847f5732b4d.png)
![screen2](https://user-images.githubusercontent.com/13230743/40641595-0cf0a632-633c-11e8-8a6b-0784bff682ab.png)

**Comment by knightlightning** [comment]
> We don't really have a way of knowing what "long" is in the context of everyone's screen+content though.
It doesn't matter. (Well, if it does, I suggest we stick to standard FullHD.) All I meant is wouldn't it be nice to have the same behavior of a column's word wrap ability regardless of the view this column appears in?

**Comment by snipe** [comment]
Some folks (myself included) don't like the visual presentation of varying heights of table rows. It sounds silly, but it is what it is. Since we don't currently have a way to set column widths, this could be visually unappealing to a lot of folks.

**Comment by knightlightning** [comment]
> Some folks (myself included) don't like the visual presentation of varying heights of table rows.
But you have such rows in the 'View Models' screen. It's on the screenshot above.

**Comment by knightlightning** [comment]
Never mind. We've refactored our model names and it seems OK now.
Thanks for the work you're doing. It's awesome.
