### ISSUE TITLE
Cannot install on Ubuntu v18.04

### ISSUE THREAD

**Issue by pduxbury** [snipe/snipe-it#5622]
Hi,

Trying to install on Ubuntu v18.04 but get 'Unsupported Ubuntu version.
Online document states v14 and greater so not sure why i would get this error.

Thanks,
Paul

**Comment by sokeada** [comment]
I'm running Snipe-IT v4.3 on Ubuntu 18.04 LTS since 2 May 2018 then upgraded to v4.4.1 on 21 May 2018 till now, seems ok.

**Comment by pduxbury** [comment]
![image](https://user-images.githubusercontent.com/35700465/40653180-47fc8700-6332-11e8-8cfb-161b78b3b5e2.png)

**Comment by pduxbury** [comment]
used the following and got the above:

wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh
chmod 744 install.sh
./install.sh

**Comment by jfausto1** [comment]
I also tried to install using the command below:

wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh
chmod 744 install.sh
./install.sh

After I enter a new password on the password option, I get the same prompt, "Unsupported Ubuntu Version. Version found: 18.04"

I also tried using the auto-generated password option and arrived at the same error prompt.

![image](https://user-images.githubusercontent.com/39745751/40683350-350595ea-6343-11e8-99fa-ccfb615723d6.png)

**Comment by sokeada** [comment]
I see. I'm using this instruction as recommended by the owner. Installing via github is recommend and future version upgrade is easier. 

https://snipe-it.readme.io/docs/introduction

**Comment by pduxbury** [comment]
even when using the github to clone. you then run the install.sh and get the exact same error

**Comment by pduxbury** [comment]
appears in the :snipeit.sh script it doesnt have anything for ubuntu 18.04

**Comment by sokeada** [comment]
i see, this question might goes to the owner as i was using github to clone but not run with install.sh.

**Comment by memtech3** [comment]
I have the same problem, decided to use centos 7 because it worked

**Comment by tiagom62** [comment]
Ill get snipeit.sh updated for 18.04.

**Comment by tiagom62** [comment]
Once #5687 is merged and makes its way to master 18.04 will be supported.

**Comment by ilyapelevinRISE** [comment]
Hi everyone!
I have exactly the same issue with Debian 10:

       _____       _                  __________
      / ___/____  (_)___  ___        /  _/_  __/
      \__ \/ __ \/ / __ \/ _ \______ / /  / /
     ___/ / / / / / /_/ /  __/_____// /  / /
    /____/_/ /_/_/ .___/\___/     /___/ /_/
                /_/


  Welcome to Snipe-IT Inventory Installer for CentOS, Fedora, Debian and Ubuntu!

  The installer has detected Debian version 10 codename buster.
  Q. What is the FQDN of your server? (XXXXXXXXXX):      Setting to XXXXXXXXXX

  Q. Do you want to automatically create the database user password? (y/n)   y

  Q. What do you want your snipeit user password to be?
Unsupported Debian version. Version found: 10

**Comment by dsit99** [comment]
I get a similar error message on ubuntu 18.04


  Q. Do you want to automatically create the database user password? (y/n) y

./snipeit.sh: line 425: [: 18.04: integer expression expected
Unsupported Ubuntu version. Version found: 18.04

**Comment by Departing** [comment]
I too get the same error on a completely clean AWS EC2 Ubuntu instance:
Q. Do you want to automatically create the database user password? (y/n) y

./snipeit.sh: line 425: [: 18.04: integer expression expected
Unsupported Ubuntu version. Version found: 18.04

EDIT: I've fixed the issue myself. Went to line 425 on the installation script (snipeit one), then changed -ge to ==
