### ISSUE TITLE
Mysql issue 

### ISSUE THREAD

**Issue by Tristantarrieux** [snipe/snipe-it#5625]
#### Expected Behavior (or desired behavior if a feature request)
Hello,
I have a snipe it 4.1.11 in production and i have just installed snipe it 4.4.1 to make some tests and to show this app to our news employee.
To show how we work, i've restored the database of snipeit 4.1.11 on the 4.4.1 version.
when i want to create an asset (only for an asset, not for user, ...) i have this error:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'default_label' in 'order clause' (SQL: select `name`, `id` from `status_labels` where `status_labels`.`deleted_at` is null order by `default_label` desc, `name` asc, `deployable` desc)

Do you have a way to resolve this issue please?

Best regards

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
That's to be expected, as the database schema from 4.1.1 isn't the same as the one from 4.4.1. You'll need to run through the [normal upgrade process](https://snipe-it.readme.io/docs/upgrading#section-after-pulling-the-new-version-files), which includes running migrations, among other things.
