### ISSUE TITLE
Question - how to import attributes from LDAP? 

### ISSUE THREAD

**Issue by jamiepassa** [snipe/snipe-it#5633]
**Server (please complete the following information):**
 - Snipe-IT Version v4.3.0 - build 3610 (master) 
 - OS: [e.g. Ubuntu, CentOS] Cent OS 7 Kernel 3.10
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 

**Is your feature request related to a problem? Please describe.**
LDAP Query for locations and other attributes. Currently only user, cn, and mail are added, need to add phone numbers, address, officelocation, etc. 

**Describe the solution you'd like**
Importing locations and other AD attributes into SnipeIt. 

**Describe alternatives you've considered**
None

**Additional context**

**Comment by snipe** [comment]
Duplicate of #2853
