### ISSUE TITLE
How to setting dashboard to show minimize recent activity permanent.

### ISSUE THREAD

**Issue by suwat2019** [snipe/snipe-it#5634]
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by suwat2019** [comment]
Snipe-IT version | v4.3.0 build 3586 (gec1fa8e90)
-- | --
Software License | AGPL3
PHP Version | 7.1.17
Laravel Version | 5.4.35

**Comment by snipe** [comment]
That's not currently possible.
