### ISSUE TITLE
[Feature Request] Definitive Media Library (DML) Module

### ISSUE THREAD

**Issue by joepitt91** [snipe/snipe-it#5640]
**Server (please complete the following information):**
 - Snipe-IT Version **v4.4.1**
 - OS: [e.g. Ubuntu, CentOS] **Ubuntu**
 - Web Server: [e.g. Apache, IIS] **Apache**
 - PHP Version  **v7.0.30**

**Is your feature request related to a problem? Please describe.**
Snipe-IT does not currently have a native way to keep track of a Definitive Media Library (DML), A DML should hold definitive media for all versions of all software that has been deployed to an environment to allow for returning to a known baseline should a conflict occur with a newer version.

**Describe the solution you'd like**
A Media item type, which is a hybrid between Asset and Licence.

I'd expect Media to have default fields like:

* Company (lookup from Company table)
* Media Tag / Barcode
* Name (e.g. Windows 10)
* Manufacturer (e.g. Microsoft - lookup from Manufacturer table)
* Version (e.g. 1801 x64)
* Type (e.g. DVD)
* Default Location (lookup from location table)
* Copies (e.g. 20)
* Associated Licence (lookup from licence table)

**Notes:**
* Type would be something like CD, DVD, Blu-Ray, USB, Virtual (ISO), etc. - potentially its own Category type in settings.
* Copies would work in the same way as licence seats i.e. each can be checked out individually to a Person, Location or Asset. 
  * Discussion Point - should copies be able to have a unique barcode?
* Associated Licence would be a cross reference to a licence.
  * Discussion Point - would this add value or not?
* Custom Field support would be good, as some may wish to record Things like OS Versions, Min Specs, etc. against each version (i.e. v1.0 requires Win XP and 2GB RAM, v2.0 requires Win 10 and 4GB RAM)
* The main difference between Licence and Media is that 1 Licence may cover multiple versions of a piece of software, but the DML should hold copies of all versions that have been deployed.
* Another reason for separation from Licence is that a user being assigned a licence for a piece of software, doesn't automatically mean they also need to be issued with a copy of the media from the DML.

**Describe alternatives you've considered**
* Create a "Media" Asset Model to capture DML Items, more a workaround than a solution, prone to human error / typos.
* Create an Asset Model for every version of every piece of software, then create assets for every piece of media, clunky to administer and would cause significant bloat to Asset Model list.
* Use an alternate application for Media Management, fragments asset management.

**Additional context**
I appreciate this may require significant work to implement and will need a level of discussion to agree a field set before work on it can begin, however, I think it would be a useful addition to this great tool.

**Comment by memtech3** [comment]
+1 this would be very useful for a production environment

**Comment by memtech3** [comment]
Not Stale

**Comment by joepitt91** [comment]
Not stale

**Comment by snipe** [comment]
> The main difference between Licence and Media is that 1 License may cover multiple versions of a piece of software, but the DML should hold copies of all versions that have been deployed

But licenses already support license seats - and you can have 1 license seat (disk) or 1000. It sounds to me like the only thing you want that Licenses doesn't already have is a checkbox for whether or not they have the physical media. 

There are already tickets for custom fields for licenses, and physical media + licenses (keys) per seat have also been on the roadmap.

**Comment by joepitt91** [comment]
I don't think its that simple, 

1. Not all software has a license, but may still have media
2. Media doesn't always have to be for software, e.g. it could be data, audio, video

This request is about the ability to track media, not add media to software licenses, hope that make sense.

**Comment by joepitt91** [comment]
Still think this is a valid request
