### ISSUE TITLE
Re-Send emails to users

### ISSUE THREAD

**Issue by el-capitano** [snipe/snipe-it#5641]
**Server (please complete the following information):**
 - Snipe-IT Version 4.4
 - OS: [e.g. Ubuntu, CentOS] Windows
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7

**Is your feature request related to a problem? Please describe.**
Currently the system has the option to send an email to the user (credentials) upon user creation, how about when importing users. Also, this is the same when sending an email to a user to check-out or accept an asset.

**Describe the solution you'd like**
The ability to add a button to re-send the email to the user in the above mentioned scenarios and any other tasks that requires sending an email, sometimes the email don't get through or the email field was written wrong by mistake.

**Describe alternatives you've considered**

**Additional context**
One more question, where can I find the signature of the users who accepted the asset? maybe it should be present in their profile page or under Files ?

**Comment by el-capitano** [comment]
Hey, thanks for the reply

How about the Signature of the user, is there any ability for the admin to see them and also for the user to have a copy of it shown in their dashboard?
Sorry I know this is a different question just out of curiosity

**Comment by snipe** [comment]
The signature is included asset history when the user signs for an asset. https://snipe-it.readme.io/docs/requiring-acceptance
