### ISSUE TITLE
Checkout History for Accessories

### ISSUE THREAD

**Issue by bhimself2018** [snipe/snipe-it#5644]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.4.1 - build 3636 (master)
 - OS: [e.g. Ubuntu, CentOS] FreeBSD 11.1
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 5.6

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to see checkout/in history of an accessory, exactly like implemented for licenses & assets.

**Describe alternatives you've considered**
Using licenses (instead of accessories) to manage an item

**Additional context**
We're looking at managing physical keys for our satellite offices in Snipe-IT. For us, this also then requires an EULA & required acceptance. This process works well, and submits successfully from the user perspective, however the information is not shown anywhere (e.g. https://demo.snipeitapp.com/accessories/9#history)
This information is also not available through the user (e.g. https://demo.snipeitapp.com/users/1#history_tab) as the history tab for users does not have the option to display signature.
For an audit, we have no way to display the signature of an accepted accessory.
updating this to work like the new licenses page (e.g. https://demo.snipeitapp.com/licenses/2#history) would be greatly appreciated!
Thanks in advance!

**Comment by Rahul9937017620** [comment]
![image](https://user-images.githubusercontent.com/85273367/162960404-3cf58d26-db8e-44a9-a809-431654a5ed79.png)
Same issue. Can't show signature in accessories history column.

**Comment by snipe** [comment]
@Godmartinz want to take a stab?

**Comment by 25hash** [comment]
The feature is there in the user history tab, in the columns selection. I think this can be closed.

**Comment by Godmartinz** [comment]
acceptance signatures seem to be included in accessories' history and users' history now. I will close this for now.
