### ISSUE TITLE
[ISSUE] Problem when attempting to request asset

### ISSUE THREAD

**Issue by memtech3** [snipe/snipe-it#5646]
- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When any user clicks the request asset button, they are redirected to a red oops screen

**To Reproduce**
1. Go to '.requestable assets.'
2. Click on 'request asset'

**Expected behavior**
The asset to be requested by user

**Server (please complete the following information):**
 - Snipe-IT Version: Version v4.4.1 - build 3636 (master)
- OS: CentOS 7
- Web Server: Apache
- PHP Version: 7.1.17

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
Fresh Install
Used install.sh
Added groups and custom fields

**Comment by snipe** [comment]
We need a stack trace to be able to assist you.

**Comment by memtech3** [comment]
how would i obtain that
