### ISSUE TITLE
Deleted assets list throw an error

### ISSUE THREAD

**Issue by alexesba** [snipe/snipe-it#565]
When you goes to the url  /hardware?Deleted=true. If the related "models" associated to  the deleted "assets" the application throw an error. It could be fixed allowing to the models to have soft deleted too.

**Comment by snipe** [comment]
You should not be able to delete models with associated assets. 
![screen shot 2015-02-25 at 4 18 15 pm](https://cloud.githubusercontent.com/assets/197404/6383850/f414b9b8-bd09-11e4-9fd4-d9116bcbd8c6.png)

**Comment by alexesba** [comment]
I notice that, but this what i did to get that error. With a fresh install  i removed all the assets first, then i went to the models section and removed all of them. Then I wanted to see all my deleted assets. And is there when the error happens because we are trying to get the name of the related model but there is no longer available. If this is not an issue please remove this card.
