### ISSUE TITLE
Not able to import from CSV (hangs)

### ISSUE THREAD

**Issue by tjone270** [snipe/snipe-it#5650]
#### Please confirm you have done the following before posting your bug report:

- [ Y ] I have enabled debug mode 
- [ Y ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Clicking Import after uploading a CSV hangs on "Processing"
A 500 Internal Server Error is logged in Chrome Inspector when attempting to run an AJAX job.
(have tried multiple CSVs including hand-made in Sublime to Excel-exported ones.

**To Reproduce**
1. Use latest Master branch.
2. Click on 'Import'
3. Upload a CSV
4. Set up the fields.
5. Click 'Import'

**Expected behavior**
Importing to begin.
![capture](https://user-images.githubusercontent.com/6151202/40893802-e8872158-67e7-11e8-8ec1-0ad0a11c1c61.JPG)
)

**Server (please complete the following information):**
 - Snipe-IT Version: 3636
 - OS: [e.g. Ubuntu, CentOS] Ubuntu 16.04
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version: PHP 7.1.17-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May  5 2018 04:55:21) ( NTS )

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 7 
 - Browser [e.g. chrome, safari] Chrome (and tested with IE (stupidly))
 - Version [e.g. 22] Latest

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] N/A
 - OS: [e.g. iOS8.1] N/A
 - Browser [e.g. stock browser, safari] N/A
 - Version [e.g. 22] N/A

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting
![capture](https://user-images.githubusercontent.com/6151202/40894030-e81c6e42-67e9-11e8-9299-fcd5a83c6a66.JPG)
![exception](https://user-images.githubusercontent.com/6151202/40894031-e8540ffa-67e9-11e8-8915-ee1b8c5dc55a.JPG)
![message 2](https://user-images.githubusercontent.com/6151202/40894032-e88bf348-67e9-11e8-8026-0f2b87c2b0c6.JPG)
![messages](https://user-images.githubusercontent.com/6151202/40894033-e8c73bce-67e9-11e8-8283-02f16e7f1b3c.JPG)
 an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? Fresh install
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) git
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by tjone270** [comment]
Hi, is there an update on this?

**Comment by snipe** [comment]
Based on your error message (and a quick google search), you don't have the correct extensions installed. https://stackoverflow.com/a/3872578/200021
