### ISSUE TITLE
Receive multiple email notification

### ISSUE THREAD

**Issue by aadrina** [snipe/snipe-it#5651]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Receive 3 times same email notification on license expiry or inventory report.

**Expected behavior**
Receive only one email notification per subject.

**Screenshots**
![capture](https://user-images.githubusercontent.com/38774791/40898106-c05ef62e-67f1-11e8-9f9b-df549d5927e0.PNG)

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
Snipe-IT version | v4.1.3 build 94 (gb6a14d2)
PHP Version | 7.0.30-0ubuntu0.16.04.1
Laravel Version | 5.4.29

**Comment by snipe** [comment]
I don't think his is an issue on our end. Check that your automated task/cron job isn't running more than once, and make sure the destination email address(s) aren't ones where you could be listed in multiple distribution lists.

**Comment by aadrina** [comment]
there's only one email listed in the email notification destination email and it is a group email...
Please teach me how to check automated task/cron? newbie here.

**Comment by XcelerationAdmin** [comment]
I am having the same issue which causes 6 emails to be emailed at midnight. Chron is empty except my AD command, and scheduler shows the tasks once.
