### ISSUE TITLE
Pre-flight won't load properly

### ISSUE THREAD

**Issue by mastertigurius** [snipe/snipe-it#5652]
![screen shot 2018-05-31 at 17 33 58](https://user-images.githubusercontent.com/19308094/40919302-093f4c9a-6801-11e8-9b59-f510dd82ffb4.png)
#### Expected Behavior (or desired behavior if a feature request)

Write URL in browser to get to pre-flight setup.

-----

#### Actual Behavior

Intended URL is not responsive, but I get to pre-flight if I manually add "index.php" at the end. However, the pre-flight page doesn't seem like it has loaded correctly, with certain links and elements missing. If I take it through to step 4, it does not complete the setup.

-----

#### Please confirm you have done the following before posting your bug report:

- [*] I have enabled debug mode 
- [*] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install.

- Version of Snipe-IT you're running
4.1.7

- Version of PHP you're running
7.0

- Version of MySQL/MariaDB you're running
MySQL 14.14 Dist 5.7.22

- What OS and web server you're running Snipe-IT on
Ubuntu 17.04 LTS, Apache

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Install.sh

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
Refused to apply style from 'http://snipe-it.corp.territorystudio.com/index.php/setup' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
setup:1 Refused to execute script from 'http://snipe-it.corp.territorystudio.com/index.php/setup' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
setup:239 Uncaught ReferenceError: $ is not defined
    at setup:239
setup:244 Uncaught ReferenceError: $ is not defined
    at setup:244
setup:1 Refused to apply style from 'http://snipe-it.corp.territorystudio.com/index.php/setup' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
No

- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
Some access errors when running composer. Changing permissions seemed to fix this.

- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
That URL is wrong - you shouldn't have index.php in your URL. What do you have for your APP_URL in your .env?

**Comment by mastertigurius** [comment]
The basic app settings are (redacted):

# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=base64:***************************************
APP_URL='snipe-it.corp.****************.com'
APP_TIMEZONE='Europe/London'
APP_LOCALE=en-GB
BACKUP_ENV=false

I also tried including https:// before the APP_URL, but it didn't work either. The only way I can get any response from the site is by adding index.php at the end when accessing it in the browser.

**Comment by snipe** [comment]
If you need index.php, then your rewrite rules are not working on your server. https://snipe-it.readme.io/docs/installation-issues#section-the-requested-url-setup-was-not-found-on-this-server

**Comment by mastertigurius** [comment]
Ok, it seems mod_rewrite is working, as adding the garbage text alters the feedback given by the browser when trying to access the site. Still doesn't work though....not sure what could be wrong here. I followed the directions for configuring the Apache default settings given here:
https://askubuntu.com/questions/48362/how-to-enable-mod-rewrite-in-apache

Attached the 000-default (renamed to txt).

[000-default.txt](https://github.com/snipe/snipe-it/files/2077224/000-default.txt)

**Comment by snipe** [comment]
You're always going to need to add the protocol before the URL (per the docs), so you should have http:// or https:// in your APP_URL.

> Intended URL is not responsive

Can you be more specific about what you see when you go to the intended URL?

**Comment by mastertigurius** [comment]
I'm pretty sure I had http:// added in APP_URL before, might have removed it while troubleshooting and forgot to add it back again. Didn't work with it added either, so I decided to completely wipe it and start on a clean slate, running ubuntu 16.04 instead.
I'm still getting just a blank page (firefox) or Error 500 (Chrome) when trying to access it.
Error logs mentioned psysh missing, which does remind me that the composer installation has a weirdly long pause when it gets to psysh - maybe as long as 5 minutes.
Pasted the error below:

[Fri Jun 08 15:57:29.172366 2018] [mpm_prefork:notice] [pid 26640] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Fri Jun 08 15:57:29.172405 2018] [core:notice] [pid 26640] AH00094: Command line: '/usr/sbin/apache2'
[Fri Jun 08 15:57:33.714976 2018] [:error] [pid 26643] [client 192.168.51.65:53037] PHP Warning:  require(/var/www/snipe-it/vendor/composer/../psy/psysh/src/Psy/functions.php): failed to open stream: No su$
[Fri Jun 08 15:57:33.715033 2018] [:error] [pid 26643] [client 192.168.51.65:53037] PHP Fatal error:  require(): Failed opening required '/var/www/snipe-it/vendor/composer/../psy/psysh/src/Psy/functions.ph$
[Fri Jun 08 15:57:37.470114 2018] [:error] [pid 26644] [client 192.168.51.65:53038] PHP Warning:  require(/var/www/snipe-it/vendor/composer/../psy/psysh/src/Psy/functions.php): failed to open stream: No su$
[Fri Jun 08 15:57:37.470159 2018] [:error] [pid 26644] [client 192.168.51.65:53038] PHP Fatal error:  require(): Failed opening required '/var/www/snipe-it/vendor/composer/../psy/psysh/src/Psy/functions.ph$
[Fri Jun 08 15:59:17.842644 2018] [mpm_prefork:notice] [pid 26640] AH00169: caught SIGTERM, shutting down
[Fri Jun 08 15:59:18.959034 2018] [mpm_prefork:notice] [pid 26718] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Fri Jun 08 15:59:18.959069 2018] [core:notice] [pid 26718] AH00094: Command line: '/usr/sbin/apache2'

**Comment by mastertigurius** [comment]
Any idea how I might be able to shoehorn Psysh into the system?

**Comment by snipe** [comment]
You shouldn’t have to, just set the co poser timeout to a higher number. This has been asked and answered a few times here, so check closed issues for the specific command.

**Comment by snipe** [comment]
I've added docs on how to do this: https://snipe-it.readme.io/v4.4.0/docs/installation-issues#section-failed-to-download-psypsysh-from-source

**Comment by sayo1296** [comment]
It is still not loading in any way why??

**Comment by EarlRamirez** [comment]
Huh? What issue are you experiencing, please create a new issue and we will be happy to assist
