### ISSUE TITLE
Whoops Something went wrong! 

### ISSUE THREAD

**Issue by jakkennedy** [snipe/snipe-it#5654]
#### Expected Behavior (or desired behavior if a feature request)

I am using Wamp, and am able to get to the setup page localhost/setup, and everything is green. I ensured the mysql user has access to the database that I created. When clicking next to setup the database tables I get an error. I enabled debugging, and will post the results below. 

-----

#### Actual Behavior

(what actually happens goes here)

(1/3)                                         PDOException                                     SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'action_logs_target_id_target_type_index'
--

(2/3)                                         PDOException SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'action_logs_target_id_target_type_index'
--

(3/3)                                         QueryException                                     SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'action_logs_target_id_target_type_index' (SQL: alter table `action_logs` add index `action_logs_target_id_target_type_index`(`target_id`, `target_type`))
--

--

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh Install
- Version of Snipe-IT you're running latest 4.4.1
- Version of PHP you're running 7.0.29
- Version of MySQL/MariaDB you're running 5.7.21
- What OS and web server you're running Snipe-IT on Win Server 2016 via Wamp/Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error ; see above
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error after clicking the "Setup database tables"
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by jakkennedy** [comment]
Same issue as https://github.com/snipe/snipe-it/issues/5612

**Comment by jakkennedy** [comment]
https://github.com/snipe/snipe-it/issues/5628#issuecomment-393658362

Resolved by

running: 

php artisan passport:install

followed by;

DROP INDEX action_logs_target_id_target_type_index ON action_logs
DROP INDEX action_logs_created_at_index ON action_logs
DROP INDEX action_logs_item_type_item_id_action_type_index ON action_logs
DROP INDEX action_logs_target_type_target_id_action_type_index ON action_logs

**Comment by snipe** [comment]
This has been asked and answered a few times here. https://github.com/snipe/snipe-it/issues/5628#issuecomment-393658362
