### ISSUE TITLE
Notifications for Consumables

### ISSUE THREAD

**Issue by Nutlink** [snipe/snipe-it#5659]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Consumables have 3 numbers - Total, Remaining, and Minimum Quantity.  When the Remaining is less than the Minimum Quantity there are no alerts through email or the top menu.  However, when the Total is less than the Minimum Quantity the alert is triggered and the email is sent.

**To Reproduce**
1. Go to 'Consumables' and create a new Consumable.  Set the Minimum Quantity as a number equal to or less than the Quantity.  Save the Consumable.
2. Click on 'Checkout' and check out the Consumable.  Do this until the Remaining number is less than the Minimum Quantity.  Notice that there are no alerts triggered or sent.
3. Click on 'Update' on the Consumable.  Change the Quantity to be less than the Minimum Quantity and Save it.
4. The alert is now triggered.

**Expected behavior**
The number Remaining goes down as the consumables are checked out, so it stands to reason that this would be the number that should trigger the alert when it is less than the Minimum Quantity.

**Server (please complete the following information):**
 - Snipe-IT Version v4.4.1 build 3636
 - OS: Windows Server 2016 Standard
 - Web Server: Apache 2.4.33
 - PHP Version 7.2.4

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser: Chrome/Firefox

**Error Messages**
- No error appears, however this does happen on the demo as well.

**Additional context**
- Is this a fresh install or an upgrade? - Fresh install
- What OS and web server you're running Snipe-IT on - Windows Server 2016, Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Git Clone
- Include what you've done so far in the installation, and if you got any error messages along the way. - Created admin users and imported Assets through a CSV
- Indicate whether or not you've manually edited any data directly in the database - No, we have not.

The only other note I have found regarding this issue was in ticket #3310, however I do not know what file the user edited to resolve this.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by 5quirrel** [comment]
Hi @Nutlink you're not alone we have the same issue #5317

**Comment by snipe** [comment]
This is fixed on develop now
