### ISSUE TITLE
API redirects to login

### ISSUE THREAD

**Issue by R0cketM0nster** [snipe/snipe-it#5660]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When trying to use the API the response is:
"Redirecting to <a href="http://10.0.10.118/login">http://10.0.10.118/login</a>."

**To Reproduce**
1. `curl -i http://10.0.10.118/api/v1/hardware -H "Authorization: test eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjVjMGQ3NTU0MTQzZGNhMmViMjUzNDRhMTNlNjdkYzdiMTVmZGU5MzQwM2M4NjM3NjIzYmY3M2Y0NDE3MTZkYzc1MWNjMGE4ZjM1ODk4ZGU2In0.eyJhdWQiOiIxIiwianRpIjoiNWMwZDc1NTQxNDNkY2EyZWIyNTM0NGExM2U2N2RjN2IxNWZkZTkzNDAzYzg2Mzc2MjNiZjczZjQ0MTcxNmRjNzUxY2MwYThmMzU4OThkZTYiLCJpYXQiOjE1MjgyNDIwMTksIm5iZiI6MTUyODI0MjAxOSwiZXhwIjoxNTU5Nzc4MDE5LCJzdWIiOiIxMjEiLCJzY29wZXMiOltdfQ.nhUj1JV8xpx_iYRU81ibPW9xnrNRBfsnXL-UBltrKBLHB2PIFNurPOYH5lYZX7GVATVOiB3ugg0FBXNNr3ijAFBvIqQKXan6l7BpMnHQbux4vj1Sdwc3BP7XKNvEnZQhSFCc2jP3L1kv-iP7CxpchvygOorWAVHGmH4U0AWFhIHoCEaZfwz_U6-DvK_Lv0BbbLxHGMWTKXd6ZrHAivWtZJ_Mu2BqrcBPEgmv-_DZtXMh-VxGk7quWVKfokfiMME6TD3VGtqiWr7GdiPw9PpUxGyiCrOFzJlcyxE4X7ZUiXG8F0imKRqSxuP5UMRvmhq5L5JZqDBrIu8OOAQdFM0ZFiZ5YSOM7Jx3Lag7R_H0lGSRcsazLoYoBvMBokapuzcxIVOzi7APSby3kkx8lzJG2SEFZZVvMPm2m04V6hY-O3t9TBx51FTv3gG_9UX5Iz1WXqOf6B1AfMLPs-f-7allEqym1RvnDh6jiKSjRGn3xveiOHxmWCd2nfZ-CDi3Seo8pMhy9Ol3No1KSihPO92mjsNcA2HGNlG8tTETe3pUXKT1vGZzZ-iiKt52P8IoWBuDlVJfUwk-FQwdoSYIA1ryw4JN-FyJP-DhGO9h6jWnjZ244-LyGL5ObIT3bWYaGAF8vmqav1gIfsKje_jFPMJDfNdL98JSPV56jLhy3NCHGiE" -H "Content-type: application/json"`

2. Response:

```
HTTP/1.1 302 Found
Date: Tue, 05 Jun 2018 23:58:22 GMT
Server: Apache/2.4.18 (Ubuntu)
Vary: Authorization
Cache-Control: no-cache, private
Location: http://10.0.10.118/login
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin
X-XSS-Protection: 1;mode=block
X-Frame-Options: SAMEORIGIN
Set-Cookie: snipeit_session=cVlrDzU6LfZsRjuSDzc8xGlGDwrPlMYi9KvZaZCJ; expires=Thu, 14-Jun-2018 07:58:22 GMT; Max-Age=720000; path=/; HttpOnly
Content-Length: 340
Content-Type: text/html; charset=UTF-8

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url=http://10.0.10.118/login" />

        <title>Redirecting to http://10.0.10.118/login</title>
    </head>
    <body>
        Redirecting to <a href="http://10.0.10.118/login">http://10.0.10.118/login</a>.
    </body>
</html>@SNIPEIT:/var/www/html/snipeit/storage$ ^C
@SNIPEIT:/var/www/html/snipeit/storage$ ^C
@SNIPEIT:/var/www/html/snipeit/storage$
```

**Expected behavior**
Should respond with list of hardware

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.4.1
 - OS: Ubunut 16.04
 - Web Server: Apache
 - PHP Version 7.0.30

**Comment by snipe** [comment]
Why do you have `Authorization: test `?

<img width="974" alt="screen shot 2018-06-05 at 6 38 09 pm" src="https://user-images.githubusercontent.com/197404/41011034-ba3b3df8-68ef-11e8-81f7-930b95dfb88f.png">

**Comment by snipe** [comment]
Per the docs, your Authorization header should start be: `Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjVjMGQ3NTU0MTQzZGNhMmViMjUzNDRhMTNlNjdkYzdiMTVmZGU5MzQwM2M4NjM3NjIzYmY3M2Y0NDE3MTZkYzc1MWNjMGE4ZjM1ODk4ZGU2In0.eyJhdWQiOiIxIiwianRpIjoiNWMwZDc1NTQxNDNkY2EyZWIyNTM0NGExM2U2N2RjN2IxNWZkZTkzNDAzYzg2Mzc2MjNiZjczZjQ0MTcxNmRjNzUxY2MwYThmMzU4OThkZTYiLCJpYXQiOjE1MjgyNDIwMTksIm5iZiI6MTUyODI0MjAxOSwiZXhwIjoxNTU5Nzc4MDE5LCJzdWIiOiIxMjEiLCJzY29wZXMiOltdfQ.nhUj1JV8xpx_iYRU81ibPW9xnrNRBfsnXL-UBltrKBLHB2PIFNurPOYH5lYZX7GVATVOiB3ugg0FBXNNr3ijAFBvIqQKXan6l7BpMnHQbux4vj1Sdwc3BP7XKNvEnZQhSFCc2jP3L1kv-iP7CxpchvygOorWAVHGmH4U0AWFhIHoCEaZfwz_U6-DvK_Lv0BbbLxHGMWTKXd6ZrHAivWtZJ_Mu2BqrcBPEgmv-_DZtXMh-VxGk7quWVKfokfiMME6TD3VGtqiWr7GdiPw9PpUxGyiCrOFzJlcyxE4X7ZUiXG8F0imKRqSxuP5UMRvmhq5L5JZqDBrIu8OOAQdFM0ZFiZ5YSOM7Jx3Lag7R_H0lGSRcsazLoYoBvMBokapuzcxIVOzi7APSby3kkx8lzJG2SEFZZVvMPm2m04V6hY-O3t9TBx51FTv3gG_9UX5Iz1WXqOf6B1AfMLPs-f-7allEqym1RvnDh6jiKSjRGn3xveiOHxmWCd2nfZ-CDi3Seo8pMhy9Ol3No1KSihPO92mjsNcA2HGNlG8tTETe3pUXKT1vGZzZ-iiKt52P8IoWBuDlVJfUwk-FQwdoSYIA1ryw4JN-FyJP-DhGO9h6jWnjZ244-LyGL5ObIT3bWYaGAF8vmqav1gIfsKje_jFPMJDfNdL98JSPV56jLhy3NCHGiE`

**Comment by R0cketM0nster** [comment]
Thanks, I was under the impression that 'Bearer' was a placeholder for the name you choose when creating the key.
