### ISSUE TITLE
Make Notes Field required when changing the status label of an asset

### ISSUE THREAD

**Issue by BarryCDV** [snipe/snipe-it#5662]
- Version v4.2.0 - build 3508

As the asset manager it get very frustrating when staff change the status of an asset and don't include any Notes as to why it's changed. I would like the option to make this field mandatory.

Whilst I'm going to be working on the training aspect to make sure this done, it would be helpful if I could enforce the need for the notes to be entered to update/change an asset status label or edit an asset. 

some examples:
In checkin:
![image](https://user-images.githubusercontent.com/39989213/41033110-50a9823a-697d-11e8-87a3-6cc8f1d08ded.png)

On editing:
![image](https://user-images.githubusercontent.com/39989213/41033195-868dcfe6-697d-11e8-86dc-c6ab0e51b28f.png)

**Comment by joepitt91** [comment]
If implemented I think this should be an optional setting, as many user will find this frustrating, if they do not require a note.

**Comment by BarryCDV** [comment]
+1 to what @joepitt91 said it should deffo be optional I know not everyone will require this functionality.
