### ISSUE TITLE
Bulk Checkin/Checkout of accessories

### ISSUE THREAD

**Issue by Riprock** [snipe/snipe-it#5665]
**Server (please complete the following information):**
 - Snipe-IT Version -v4.4.1 build 3636 
 - OS: Centos 7 
 - Web Server: Apache
 - PHP Version - 7.1.17

**Is your feature request related to a problem? Please describe.**
At my place of work we have a supply closet full of cables. We have people constantly taking cables in and out of the closet. My Superior wants to be able to track the number of cables we have so he can know If we need to buy more and he wants to track the number of each type of cable that we currently have in supply.

**Describe the solution you'd like**
The Ability to set bulk checkout of an accessory and to do bulk check in when the cables have returned. (Small fill in that just takes a number)

**Comment by smksar** [comment]
Hi @snipe albeit my post is closed because duplication.. Hope the idea of having Bulk Checkout with shopping cart / trolley icon between the Dashboard icon and Assets icon will be considered as it will be the most clicked icon for many =)

Thanks for your tremendous support as always

**Comment by snipe** [comment]
@smksar I'm not sure a shopping cart analogy will make the most sense to most users here. The icon itself implies an exchange of money, and that feels alien to this app.

I'll think about it.

**Comment by ecellsworth** [comment]
Is being able to check in and out in quantity for all categories something that is will be happening in the near future? When you are working on a project that requires bulk accessories and assets then it doesn't make sense to check out one item at a time. Sometime we over estimate and need to check back in cables, hubs, hosts...in bulk as well. It would be appreciated.

**Comment by ecellsworth** [comment]
We still want it if that’s what you are asking. lol

Eric C. Ellsworth

**Comment by sambayford** [comment]
This feature would be very helpful for our college environment where a laptop and accessories are checked out together to students.

**Comment by riccardocagnasso** [comment]
I'm considering adopting your software but it seems that this feature is required for my use case.

**Comment by tymik** [comment]
duplicate of #5140 as i can see, still +1 from me!

**Comment by tymik** [comment]
still relevant

**Comment by RivoHenfri** [comment]
still relevant, is there got the solution right now?

**Comment by MSTigers** [comment]
Stalebot not re-opening. #Rude

**Comment by MSTigers** [comment]
Duplicate of #5140 unless part of 5140 can't be implemented then I'd happily take this part as mentioned above.
