### ISSUE TITLE
Ability to change statuses without editing asset

### ISSUE THREAD

**Issue by MiamiFinsFan13** [snipe/snipe-it#5666]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.2.0 build 3508 (g590938f)
 - OS: Windows Server 2012 R2
 - Web Server: IIS
 - PHP Version: 7.2.2

**Is your feature request related to a problem? Please describe.**
I find it frustrating that it is not possible to change the status of an asset without having Edit permissions on the asset. Ideally the users prepping the assets would not be able to change things like serial number, model number, etc. when prepping assets. We have a bunch of custom status labels that describe where the asset is in the life cycle (i.e. in stock-not imaged, imaged - not assigned) that we want to leave in pending so they can't be assigned to users and then move to deployable and then check them out. However, we don't want all users who will be checking items in and out to be able to edit the assets.

**Describe the solution you'd like**
Ideally there would be an additional permission level that allows manipulation of the asset status. A drop down would be presented in the Asset view that would allow the user to select the status that they want to set the asset to.  

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by esspeecy410** [comment]
The way our organisation works is that we create assets ready for installation ahead of work in site, so we use a Deployable status; then when the assets are installed we use an Installed status, so we check out the asset but there's no option to change the status at the point of check out, so we have to edit the asset and manually change its status. If you can change the status when checking an asset in, it seems to me that you should be able to do that when you check the asset out.

________________________________

**Comment by MiamiFinsFan13** [comment]
This is still a feature we would like to see please
