### ISSUE TITLE
403 during preflight

### ISSUE THREAD

**Issue by pgrimesdsi** [snipe/snipe-it#5668]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The issue I am running into is when in pre-flight I get a 403 error.

Forbidden
You don't have permission to access / on this server.
Apache/2.4.29 (Ubuntu) Server at IP Address

I am running on a fresh git pull of Snipe-IT on a fresh install of Ubuntu Server 18.04. I was having file permission problems with Apache but those appear to have been resolved. In the Apache logs I am getting an error of: [Wed Jun 06 19:29:17.282326 2018] [authz_core:error] [pid 3323] [client 10.XX.X.XX:57183] AH01630: client denied by server configuration: /home/snipeit/snipe-it/public/

I have Apache and PHP installed in their default locations and Snipe-IT installed to /home/snipeit/snipe-it. I have configured my 000-default.conf to point the directory and document root to /home/snipeit/snipe-it/public

**Expected behavior**
Pre-flight to show in a browser

**Server (please complete the following information):**
 - Snipe-IT Version Current
 - OS: [Ubuntu Server 18.04]
 - Web Server: [Apache2]
 - PHP Version 5.6

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [Current]

**Error Messages**
- WITH DEBUG TURNED ON, I have no error logs generating
- Include any additional information you can find in `storage/logs` and your webserver's logs.
storage\logs is empty

**Additional context**
- Is this a fresh install? yes 
- What method you used to install Snipe-IT  git

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Based on that error message, it looks like you might have a typo in your server config. I'm seeing a reference to `/home/snipeit/snipe-it/public/public` which isn't going to be a valid path.

**Comment by pgrimesdsi** [comment]
![image](https://user-images.githubusercontent.com/40005757/41063400-225c121e-699e-11e8-8785-6da985c616a9.png)

**Comment by pgrimesdsi** [comment]
![image](https://user-images.githubusercontent.com/40005757/41063818-5cde9564-699f-11e8-9f63-3c80921c0468.png)

**Comment by snipe** [comment]
I'd check and make sure that index.php is set as a DirectoryIndex in your apache configs. If you can go to `your-snipe-it-domain/index.php` and it loads, you need to add index.php as a DirectoryIndex and restart apache.

**Comment by pgrimesdsi** [comment]
It 403's for index.php as well.

You don't have permission to access /index.php on this server.

**Comment by snipe** [comment]
What are the file/directory permissions for your snipeit project directory?

**Comment by pgrimesdsi** [comment]
I did chmod -R 755 /home

I know I should have been a bit more granular but this go around is mostly to test and see if I and the other helpdesk guy like Snipe-IT better than our current product.

**Comment by snipe** [comment]
If you create a temporary `index-test.html` file in ` /home/snipeit/snipe-it/public`, can you browse to `snipeit.dsinps.com/index-test.html`? If not, then there's still something wrong with your apache configs. I don't see anything obvious, but maybe Apache isn't honoring your virtualhost config for some reason?

**Comment by pgrimesdsi** [comment]
I have done that and it is still failing. Could it be an issue with apache2.conf?

**Comment by snipe** [comment]
> I have done that and it is still failing

Same error, or something else?

If you can't see your test file, Apache isn't even looking in the right place, which explains why you're seeing 403s everywhere. My guess is that it's looking in an empty directory, and you have directory indexing turned off (which is a good thing), so it's hardline 403ing you. 

I'd try the steps outlined here:
https://askubuntu.com/a/458645

Specifically copying over the config to `/etc/apache2/sites-available/snipeit.conf` and then enabling the config, and restarting apache.

**Comment by pgrimesdsi** [comment]
Ok. Progress! Now I am getting a 500 error and the apache logs are talking about .htaccess

![image](https://user-images.githubusercontent.com/40005757/41066138-7fb142b0-69a6-11e8-87af-8f8274f799ed.png)

**Comment by snipe** [comment]
Yay, progress! Take a look at this answer and see if it helps:
https://serverfault.com/a/529015

**Comment by pgrimesdsi** [comment]
I wiped the server today. I set back up from scratch and did not get any 403 errors. However I was receiving the 500 error relating to the Ifmodule from above. I bypassed that by commenting out the entire .htaccess file at /home/snipe/snipe-it/

I am sure there must be a more elegant solution but this works for the time being while we test and see if we want to bring Snipe-IT into our permanent toolbox.

Thanks so much for your help in trouble shooting these issue yesterday!

**Comment by snipe** [comment]
You need the rewrite rules in order for the system to function though.

**Comment by pgrimesdsi** [comment]
So far it has been up and stable with the .htaccess commented out. I agree that if we do keep it full time those rules should get ironed out thought. I think you can mark this issue as closed and resolved though since we have a running instance up. Thanks again for all your help troubleshooting this!
