### ISSUE TITLE
[ISSUE] API Problems With Localhost

### ISSUE THREAD

**Issue by memtech3** [snipe/snipe-it#5670]
**Describe the bug**
When trying to use the api with postman on localhost, I am unable to get a response when I have a bearer key however when remove the key I get an unauthenticated response

**Screenshots**
[Tones.zip](https://github.com/snipe/snipe-it/files/2078858/Tones.zip)
![cap2](https://user-images.githubusercontent.com/20732350/41077222-08a69afa-69db-11e8-8531-42dae386615c.PNG)
![cap1](https://user-images.githubusercontent.com/20732350/41077223-08bc6b32-69db-11e8-8837-98b9ad771418.PNG)

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: Centos 7
 - Web Server: Apache
 - PHP Version: 7.1.17

**Additional context**
- Fresh Install
- Installed with install.sh
- No manually edited data

**Comment by snipe** [comment]
There's no reason within Snipe-IT where that would be the case. You may want to [check this thread on the postman repo](https://github.com/postmanlabs/postman-app-support/issues/2214), or try attempting it via curl to rule more things out.
