### ISSUE TITLE
 Login with Remote User Header not working with IIS

### ISSUE THREAD

**Issue by mlubos** [snipe/snipe-it#5671]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The Login with 'Remote User Header' enabled does not work in my environment.
It always shows the login page.
The problem is that echo $_SERVER['REMOTE_USER'] on IIS gives me something like 'MYDOMAIN\john.doe' but the code in LoginController.loginViaRemoteUser expects 'john.doe'.

I've modified the loginVieRemoteUser function in order to make it work for me:

    `private function loginViaRemoteUser(Request $request)
    {
        $remote_user = $request->server('REMOTE_USER');        
        if (Setting::getSettings()->login_remote_user_enabled == "1" && isset($remote_user) && !empty($remote_user)) {
            LOG::debug("Authenticatiing via REMOTE_USER.");

            // ml: fix for trailing domain name 'MYDOMAIN\john.doe' in REMOTE_USER
            $pos = strpos($remote_user, '\\');
            if ($pos > 0) {
                $remote_user = substr($remote_user, $pos + 1);
            };
            // ml: end

            try {
                $user = User::where('username', '=', $remote_user)->whereNull('deleted_at')->first();
                LOG::debug("Remote user auth lookup complete");
                if(!is_null($user)) Auth::login($user, true);
            } catch(Exception $e) {
                LOG::error("There was an error authenticating the Remote user: " . $e->getMessage());
            }
        }
    }`

**To Reproduce**
1. You probably have to use IIS...
2. Go to Snipe-IT home page
3. You always get the login page, no automatic login

**Expected behavior**
The user should not be required to login using the REMOTE_USER server variable

**Server (please complete the following information):**
 - Snipe-IT Version: v4.4.1 - build 3636 (master)
 - OS: Windows Server 2008 R2
 - Web Server: IIS 7.5
 - PHP Version 7.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser IE 11, FireFox 60.0.1

**Error Messages**
There are no error messages, it simply does not login.

**Additional context**
I don't think that a backslash could be part of a user name so adding this shouldn't break anything.

**Comment by snipe** [comment]
You may want to as @dkaatz about that, as he built that part.

**Comment by snipe** [comment]
This fix is on develop and will be in the next release.
