### ISSUE TITLE
Incomplete Translation to Portuguese

### ISSUE THREAD

**Issue by KnyxPT** [snipe/snipe-it#5672]
- [ X] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

I want to change the whole Snipe-IT UI language to portuguese but I find some parts of the app aren't translated even though I already edited all local Language translations files  (That I can find), changed the default language and user language to Portuguese. 

**Expected behavior**

After changing all setting (that I know of) I expected that the setting in the screenshots below would be translated

**Screenshots**

![translation 4](https://user-images.githubusercontent.com/37289115/41107269-9079fa68-6a61-11e8-9d37-5bead01e1278.png)

> The notification text appears in english;

![translations](https://user-images.githubusercontent.com/37289115/41085964-10d65ee8-6a28-11e8-86c6-6c3d2c8320d1.png)
*Highlithed the parts that still show up in english.

> The bulk actions and the button show up in english.

> The custom export button show up in english.

> The search bar shows up in english.

> The Showing page number to page number and number of rows text shows up in english.  Even though the "bootstrap-table-pt-PT.js" file shows the function to translate this part of the text:

"(function ($) {
    'use strict';

    $.fn.bootstrapTable.locales['pt-PT'] = {
        formatLoadingMessage: function () {
            return 'A carregar... Por favor aguarde...';
        },
        formatRecordsPerPage: function (pageNumber) {
            return pageNumber + ' registos por página';
        },
        formatShowingRows: function (pageFrom, pageTo, totalRows) {
            return 'A mostrar ' + pageFrom + ' até ' + pageTo + ' de ' + totalRows + ' linhas';
        },
        formatSearch: function () {
            return 'Pesquisar';
        },
        formatNoMatches: function () {
            return 'Nenhum registo encontrado';
        }
    };

    $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['pt-PT']);

})(jQuery);"

![translations2](https://user-images.githubusercontent.com/37289115/41086939-f56145da-6a2a-11e8-830d-597762a2080c.png)

> In the dashboard page, the button of recente activity appears in english;
> The status and asset resume titles and the Type field in the Asset Category resume appears in english;
> The button View All button in the Asset category also shows the text in english.

![translations3](https://user-images.githubusercontent.com/37289115/41087179-7e4f6d5e-6a2b-11e8-8063-2e9f54845afe.png)

> In the persons page The expot button, the selected rows menu appears and the search bar text shows up in eglish;
>The dashboard left menu link appears in english;

**Server (please complete the following information):**
 - Snipe-IT Version v4.2.0 - build 3479 (master)
 - OS: Windows Server 2012 R2
 - Web Server: Apache 2.4.27
 - PHP Version: 7.1.9 

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Internet Explorer 11 nd Chrome 66.0.3359.181 (64 bits)

**Error Messages**
- No error message;
- No stacktrace;
- No browser error console error;
- Reproducible on the demo: https://snipeitapp.com/demo.

![translation snipeit demo](https://user-images.githubusercontent.com/37289115/41087582-9df318e4-6a2c-11e8-9f6f-99bc86e17d15.png)

**Additional context**
- Fresh installation; 
- Manual installation;
- No data edited manually in the database;

If anyone can point out what im missing here in the translation aspect it would be higly appreciated.

**Comment by snipe** [comment]
We try our best to localize as many of the strings as possible, but we do know there are still some areas that are incomplete.
