### ISSUE TITLE
Question - v3.6.2 build 18 to v4.4.1

### ISSUE THREAD

**Issue by Weaksid** [snipe/snipe-it#5674]
Hello,

This is just a general question since I couldn't find the answer.

I'm curious if it's possible to backup the database on v3.6.2 build 18 and restore it on a different server with v4.4.1 without upgrading the current server? I'm going to assume probably no due to the database layout but not sure if there might be a migration tool I missed while reading through the documentation and searching the issues section. 

Our current server is giving some issues and we're severely behind on updates if you couldn't tell from the current version. So, we just wanted to see if there was a quick way of moving the data over to a fresh install. 

Thank you very much for your hard work

**Comment by snipe** [comment]
You would want to move the database over to the new server with 4.4.1, and then run-through the upgrade process. https://snipe-it.readme.io/docs/upgrading
