### ISSUE TITLE
User with custom "admin" rights unable to see specific accessories

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#5675]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
A picture is worth a thousand words

In this picture the USB-C to Thunderbolt accessory isn't visible. 
https://i.imgur.com/dmYULoT.png

After changing the users permissions to a full admin the user can now see the accessory
https://i.imgur.com/2nD4nEx.png

**To Reproduce**
I'm uncertain of how to reproduce this issue. 

**Expected behavior**
A user with full view and edit rights to everything in the system, excluding delete rights should be any to search for or browse for any item or person etc. 

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.4.1 build 3636
 - OS: CentOS 7
 - Web Server: apache
 - PHP Version 7.1.18

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 60.0.1

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Sounds like you probably have full company support turned on. Disable that, or make sure your accessories/people/etc are listed in the same company. https://snipe-it.readme.io/docs/general-settings#section-full-multiple-companies-support
