### ISSUE TITLE
Accessories/Components Total Value Ignores Quantity

### ISSUE THREAD

**Issue by joepitt91** [snipe/snipe-it#5676]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
when accessing `/accessories` or `/components` the total value of all accessories, at the bottom of the table, is the sum of the Purchase Cost column, and does not take into account the Quantity column, I believe the correct total should be the sum of line totals, which would be caclulated by doing purchase cost * Qty. 

I believe this is a bug and not by design due to the way Purchase cost is used elsewhere in Snipe-IT, biggest example being Components checked out to Assets: on the `/hardware/1#components` page, Purchase Cost is shown (unmodified), regardless of how many are checked out to that asset, which makes sense, as you want to know the total value of the components assigned to that asset (related #2416 - please can this be reopened as the stale bot closed it without it being addressed).

**To Reproduce**
1. Go to '/accessories/create'
2. Create an Accessory with a quantity of 10 and a Purchase Cost of 10.00
3. Click on 'Save'
4. See the total at the bottom of the page shows 10.00 not 100.00.

**Expected behavior**
All Total fields which calculate their value based on the Purchase Cost of classes of items with a quantity should first multiple the Purchase Cost by Quantity before adding all values up.

**Screenshots**
![accessoriestotal](https://user-images.githubusercontent.com/16159859/41117623-7598aa2c-6a85-11e8-835f-0a88707f1e52.PNG)

**Server (please complete the following information):**
 - Snipe-IT Version **v4.4.1**
 - OS: [e.g. Ubuntu, CentOS] **Ubuntu**
 - Web Server: [e.g. Apache, IIS] **Apache**
 - PHP Version **v7.0.30**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] **Windows 10**
 - Browser [e.g. chrome, safari] **Chrome**
 - Version [e.g. 22] **67**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] **S8+**
 - OS: [e.g. iOS8.1] **Android 8.0.0**
 - Browser [e.g. stock browser, safari] **Chrome**
 - Version [e.g. 22] **Latest**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **No error logged**
- If a stacktrace is provided in the error, include that too. **No error logged**
- Any errors that appear in your browser's error console. **No error logged**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. **Yes**
- Include any additional information you can find in `storage/logs` and your webserver's logs. **No error logged**

**Additional context**
- Is this a fresh install or an upgrade? **Upgrade**
- What OS and web server you're running Snipe-IT on **Ubuntu / Apache**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Recommended git clone method**
- Include what you've done so far in the installation, and if you got any error messages along the way. **install, configure and populate without errors**
- Indicate whether or not you've manually edited any data directly in the database **No**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by joepitt91** [comment]
Still relevant

**Comment by joepitt91** [comment]
Not stale

**Comment by joepitt91** [comment]
Not stale, the total field is only useful if it is an actual total.

**Comment by tymik** [comment]
+1

**Comment by crypticsh** [comment]
+1 to this.  Right now this is just distracting. Either remove the cost completely or calculate total based on quantity as recommended.  Or explain why it is this way if it is on purpose?

**Comment by Shadowfita** [comment]
+1 still a frustration.

**Comment by ced455** [comment]
@snipe Could you reopen this issue ?
this could be usefull

**Comment by maciejewskikamil** [comment]
@snipe Any updates?
I have the same problem here.

**Comment by karnoha** [comment]
+1 same issue here. Please fix this, or delete the sum.

**Comment by Ng-marelec** [comment]
+1 IMO, this is a basic feature? Why isn't this working in the first place?
If I change the # of licenses, it should just do the cost * #? Now we have to change it ourselves...

**Comment by Computroniks** [comment]
I think the problem is with the function that is used to calculate the total. It is generic function that is used to sum the values of a specified column. To get the total all that would need to be done is multiply the value by the quantity for that row. This would need to be done in a seperate function though as this one is used else where. I'm thinking something like sumFormatterQuantity(). It would mean that the sum function for all of the affected tables would have to be modified though.
https://github.com/snipe/snipe-it/blob/9a5d9eafebb80f1992ea2c38cd36d2256445475f/resources/views/partials/bootstrap-table.blade.php#L598-L607
