### ISSUE TITLE
Limit which Assets a user can manage

### ISSUE THREAD

**Issue by ks9389** [snipe/snipe-it#5679]
== Hosted ==

**Is your feature request related to a problem? Please describe.**
We have assets assigned to different companies, and we would like one of the users from a different company to only be able to edit the assets assigned for that company

**Describe the solution you'd like**
A custom permission filter on the permissions per user, where you can build a scenario using filters. e.g. Create / View / Edit Assets where Company = "CompanyX" or Company = "CompanyY"

**Comment by snipe** [comment]
That's a pretty complicated change for us to implement. I'd consider reviewing a pull request with this functionality, but currently users can only belong to one company, and changing that behavior would require quite a bit of work.

**Comment by ks9389** [comment]
But at the moment even when I assign a user to a specific company, they see all assets and not just those belonging to their company?

**Comment by snipe** [comment]
@ks9389 Do you have full company support enabled?

**Comment by ks9389** [comment]
Never even noticed that setting - that has at least solved some of my issues for the time being! I assume if that user is assigned an asset from a different company to the one they’re in they can still accept that?

Thanks for your help!

**Comment by snipe** [comment]
> I assume if that user is assigned an asset from a different company to the one they’re in they can still accept that?

They can, although to be honest, it probably shouldn't be allowed to check out assets to users from a different company. The tricky part would come in if someone turned that setting on after a bunch of things had been assigned - for example, do we unassigned the ones that don't match the company, etc?

**Comment by ks9389** [comment]
Would probably need to be an option - you may get instances of completely different companies, but our setup is 4/5 companies who are quite fluid and will have some kit from one place and some from another...

Sent from my iPhone

On 8 Jun 2018, at 13:56, snipe <notifications@github.com<mailto:notifications@github.com>> wrote:


I assume if that user is assigned an asset from a different company to the one they’re in they can still accept that?

They can, although to be honest, it probably shouldn't be allowed to check out assets to users from a different company. The tricky part would come in if someone turned that setting on after a bunch of things had been assigned - for example, do we unassigned the ones that don't match the company, etc?
