### ISSUE TITLE
Issue with Thai language

### ISSUE THREAD

**Issue by MzK0RE** [snipe/snipe-it#568]
For example, characters without vowels like "ทดสอบ" will works just fine. However, if i use vowels like "สูงส่ง" Snipe-IT will show that i have an errors in my form. Is there anyway to fix this problem? Thanks.

**Without vowels**
![capture](https://cloud.githubusercontent.com/assets/9249682/6388488/084cab34-bdcd-11e4-9364-1f83753c3bbe.JPG)

**With vowels**
![capture2](https://cloud.githubusercontent.com/assets/9249682/6388494/17491370-bdcd-11e4-9359-19912d5cd424.JPG)

**Comment by snipe** [comment]
Hm, shit, you're right. Looks like there's an issue in the custom validator. I'll take a look.

**Comment by uberbrady** [comment]
I added some comments, and also added unicode 'marks' - this may have a negative side-effect in that I believe this will allow:

é or ñ or other accented, zero-space-taking characters.

Œ (oe ligature) and other space-taking-up 'marks'

If this is OK, then I think I have it fixed!
