### ISSUE TITLE
Single Acceptance Page

### ISSUE THREAD

**Issue by ks9389** [snipe/snipe-it#5680]
== Hosted ==

**Is your feature request related to a problem? Please describe.**
A user can only accept assets if they follow the individual link in each email.

**Describe the solution you'd like**
To follow one link to a page where you can accept any assets that are assigned. Even better if this page is available on login and not only via a link.

--- Related Feature

**Is your feature request related to a problem? Please describe.**
If accepting of assets is not available on login without a link, there is no way to resend an acceptance email unless the asset is checked in and out again.

**Describe the solution you'd like**
Button on unaccepted assets report to resend bulk or individual emails for unaccepted assets.

**Comment by ks9389** [comment]
Still relevant!

**Comment by bendaugherty** [comment]
This would be great if we can have users accept it without having to sign with a touchscreen device or mouse, more along the lines of type in a name and click option? We have staff and students receiving devices and want them to accept the agreement via a click or login.   Also, related to this, can we send an assigned assets form or email with a link to users to verify they still have those assets.

**Comment by sanjurofla** [comment]
still valid
