### ISSUE TITLE
Scheduled / Routine LDAP Syncs

### ISSUE THREAD

**Issue by ks9389** [snipe/snipe-it#5681]
== Hosted ==

**Is your feature request related to a problem? Please describe.**
When a new user is created in AD, a manual LDAP Sync needs to be completed

**Describe the solution you'd like**
The ability to do a cron job / scheduled LDAP Syncs. E.g. Daily / Weekly.

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/ldap-sync
