### ISSUE TITLE
Adding PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT => false to env file

### ISSUE THREAD

**Issue by federiconan** [snipe/snipe-it#5683]
**Server (please complete the following information):**
 - Snipe-IT 4.4.1 - build 3636
 - OS: Ubuntu shipped with docker image
 - Web Server: Apache
 - PHP Version: 7.0.30

**Is your feature request related to a problem? Please describe.**
If you want to use  google cloud Kubernets containers with google cluster mysql over ssl, you can´t connect to the database because the IP doesn´t match the CN. You can´t put the name of the mysql cluster as well. 

**Describe the solution you'd like**
Add to the env file the " PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT" flag 

**Describe alternatives you've considered**
Add the google mysql name.

**Additional context**

**Comment by snipe** [comment]
I'm not really sure I want to enable folks doing things that could make a system less secure though.

**Comment by federiconan** [comment]
I totally understand your point ,what will be the best alternative if we are working in google environments? Could be a well commented option with true or false :)

**Comment by snipe** [comment]
Let me do a little research and see if there's any other way to work around this issue. This is the first time it's come up, so I need to dig around a little.

**Comment by marcosiebecke** [comment]
Would be nice if there would be a solution for this.
Just ran into pretty much the same issue (though using a plain docker host instead of k8s).
