### ISSUE TITLE
Getting SSL to Work Via WAMP

### ISSUE THREAD

**Issue by jakkennedy** [snipe/snipe-it#5692]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

Hello,

This isn't necessary a bug, but I have been unable to get Snipe to function via WAMP on a windows server. I have tried several walkthroughs, and I end up breaking the Apache Service. If anyone could guide to the right location to get this figured out that would be awesome. I am willing to try and get it to work in IIS again, but the walkthroughs are rare and the one I tried failed. 

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [Windows Server 2016]
 - Web Server: [WAMP / Apache ]
 - PHP Version 7.0.29

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? Fresh Install, and I amble to create a user, and database tables.

Looking for guidance to get Snipe moved over from a Linux server to Windows. Can't get SSL working.

**Comment by jakkennedy** [comment]
Walkthroughs tried

http://www.phpjoel.com/2011/04/07/installing-ssl-using-openssl-on-a-wamp-localhost/

https://madurad.wordpress.com/2014/04/25/redirect-http-to-https-with-wamp-server/

**Comment by jakkennedy** [comment]
I would really like to get it working via IIS if i could!

**Comment by EarlRamirez** [comment]
@jakkennedy  if you will like to generate SSL for IIS you will need IIS Resource Kit "https://www.microsoft.com/en-us/download/details.aspx?id=17275", navigate to C:\Program Files (x86)\IIS Resources\SelfSSL from the command line and run the following command

selfssl.exe /N:CN=<server_name_or_domain> /K:2048 /V:1825 /P:443 /T /S:<site_id>
