### ISSUE TITLE
[Feature Request] Allow exposure of license number/serial to assigned user

### ISSUE THREAD

**Issue by LinkMJB** [snipe/snipe-it#5693]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.4.1 build 3636 (gece916e12)
 - OS: Ubuntu Xenial
 - Web Server: Apache
 - PHP Version: 7.0.30-0ubuntu0.16.04.1

**Is your feature request related to a problem? Please describe.**
In the circumstance that a software license is purchased on behalf of a user, and the license is assigned to the user, the user is unable to view the license serial/code that has been assigned to them upon login to snipe-it dashboard.

**Describe the solution you'd like**
I would like the ability to optionally allow the assigned user to see license serials/codes that have been assigned to them. A simple "visible to assigned user/hidden from assigned user" option for the license would be sufficient to control this feature per license.

**Describe alternatives you've considered**
I have not been able to find any workaround to accomplish this. If this is a simple RTFM, please let me know 😄

**Comment by snipe** [comment]
They should be able to view this in the Assigned Assets page in the Profile menu.

<img width="463" alt="screen shot 2018-06-11 at 5 27 28 pm" src="https://user-images.githubusercontent.com/197404/41263583-c8039348-6d9c-11e8-8460-ec27c55851a5.png">

**Comment by LinkMJB** [comment]
Thanks for the quick response @snipe!!! I think the problem we ran into in this case was the fact that the group the user was assigned to did not have the ability to view the license key. Adding that permission to the assigned group appears to have fixed it, except for the fact that it seems to be limited to 47 characters. Even downloading the rows truncates the license keys with `...` at the end.

**Comment by snipe** [comment]
That's a known limitation, I think. I'll try to fix that for you.

**Comment by LinkMJB** [comment]
Thank you @snipe! Would you like a separate ticket/issue? Or should we just rename this one?

**Comment by snipe** [comment]
It's fixed on develop and will be in the next release
