### ISSUE TITLE
[Feature Request] Support requestable licenses

### ISSUE THREAD

**Issue by LinkMJB** [snipe/snipe-it#5694]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.4.1 build 3636 (gece916e12)
 - OS: Ubuntu Xenial
 - Web Server: Apache
 - PHP Version: 7.0.30-0ubuntu0.16.04.1

**Is your feature request related to a problem? Please describe.**
In the circumstance that a software license is considered as shared or floating between multiple users, there does not seem to be any way to request the license.

**Describe the solution you'd like**
I would like the ability to assign licenses as "requestable" in the same way that assets can be a requestable resource. This should trigger a notification to be sent to the user currently holding the requested license, that someone is waiting for the license to be available.

**Describe alternatives you've considered**
I have not been able to find any workaround to accomplish this. If this is a simple RTFM, please let me know 😄

**Comment by LinkMJB** [comment]
I personally think this is still relevant, and worth keeping open

**Comment by garyeep** [comment]
This feature would be amazing to have!

**Comment by snipe** [comment]
That's on the longer-term roadmap. We have a lot of refactoring to do before we're ready for this, but it's on the list.

**Comment by LinkMJB** [comment]
@snipe should this issue be left open? Or should it be closed if it's already on a roadmap?

**Comment by tymik** [comment]
> That's on the longer-term roadmap. We have a lot of refactoring to do before we're ready for this, but it's on the list.

could you add relevant labels to issue then? it would be useful to know it is on roadmap.

**Comment by ebricca** [comment]
as noted in #6520 .. would be nice for other types like consumables / accessories / components as well

related to the self-checkout idea #5994 ,  #6656

**Comment by maxlehot1234** [comment]
Anything on this?

Allow users to request a license could be really useful.

For now, I can create an assets that allow users to request it, but it was weird.

We planned to use snipe-it in our compagny, but few things need to be changed/added before.
- requestables licences
- more permissions. For example allow players to see requestables assets, but hide checkin options, actions menu, consumables tab, components tab, settings tab,etc
- a sticky top bar with the menu and search form?
- a jquery search form with instant result?
- maybe more things.


It was probable hard to do everything, but I know you can do it ;)

Hope the requestables licences will be ready soon

**Comment by jernejr** [comment]
We are also implementing the use of SnipeIt in our company and we are really missing the before mentioned features. Mostly the feature of requesting licenses and granular permissions in the sense what group of licenses a user can actually see. 

Hope this will be implemented in the near future.

**Comment by jburger** [comment]
Putting in our support for this feature - we rely a lot on self management - and being able to allow people to request an existing license would be fantastic.

**Comment by angrygreenfrogs** [comment]
We'd also love to have this feature so that users could request a license or access to a system.

**Comment by CKeckNorthIO** [comment]
+1 for that feature.
We really miss request-able licenses here. Thank you!
