### ISSUE TITLE
Authenticating User via LDAP not working properly - solution included

### ISSUE THREAD

**Issue by aalaily** [snipe/snipe-it#5695]
In the latest version of the application (and presumably since v3.0), the LDAP authentication is not working as expected.

Looking at "app/Models/Ldap.php", function "findAndBindUserLdap($username, $password) attempts to bind the user directly to LDAP, thus defeating the purpose of having a system configured bind user and breaking the application for administrators who depend on the configured bind user to find & authenticate the credentials passed to the function.

With that in mind, the line (#99):
`if (!$ldapbind = @ldap_bind($connection, $userDn, $password)) {`

Should be replaced by:
`$ldaprdn  = $settings->ldap_uname;`
`$ldappass = \Crypt::decrypt(Setting::getSettings()->ldap_pword);`
`if (!$ldapbind = @ldap_bind($connection, $ldaprdn, $ldappass)) {`
_(this ensures that we are binding to LDAP using the configured bind user)_

and then after successfully finding the first entry in the $filterQuery on line #110 the following code should be added:

`if( !$userDn = @ldap_get_dn($connection, $entry) ) {`
`      return false;`
`}`
`if( !$isbound = ldap_bind($connection, $userDn, $password) ) {`
`      return false;`
`}`
_(this ensures that the username and password that were passed are valid credentials)_

I hope this helps people who are having trouble authenticating using LDAP in an environment where a Bind user is absolutely required for any type of query.

Aladin

**Comment by aalaily** [comment]
@Patrock ... the problem is that the filter query cannot be run by the user who is trying to log in, hence why it's critical to use the bind user as it covers all the cases.

If you look at the original LDAP code from version 3.6.3 you will notice that the code is almost exactly as I wrote it above.  It probably got shaved a little too much in subsequent versions.

Anyway, I hope this helps.

**Comment by sduensin** [comment]
Thank you!

**Comment by sduensin** [comment]
Well, Stale Bot, I had to make the above changes to get it to work.  Guessing that hasn't been merged since nobody closed this.  :-)
