### ISSUE TITLE
[Feature Request] Location Enhancements

### ISSUE THREAD

**Issue by joepitt91** [snipe/snipe-it#5697]
**Server (please complete the following information):**
 - Snipe-IT Version **4.4.1**
 - OS: [e.g. Ubuntu, CentOS] **Ubuntu**
 - Web Server: [e.g. Apache, IIS] **Apache**
 - PHP Version **v7.0.30**

**Is your feature request related to a problem? Please describe.**
While Locations can have a parent child relationship, this does not trigger behaviour expected of a hierarchy of locations, e.g.:

* Inheritance of `Manager`, `Currency` and `Address` from parent (if not specifically overwritten)
* Prevention of deletion of parent locations which have children
* Reporting of child locations on parent Location details page
* Reporting of child location's assets, accessories and consumables on parent Location Page (potentially what #5555 is asking for?)
* A location tree, to logically show the hierarchy on the Location Settings Page

Other enhancements could include:

* The ability to reuse an already uploaded location image, rather than having to repeatedly upload the same icon, e.g. for boxes / bins
* A location Tag / bar code (which is included in search lists, in the same way model number is for asset models) to allow for selection with a barcode reader during bulk checkouts / Audits / etc. (dependent on #5296)
* **Edit** Reporting on Accessories and Consumables assigned to locations as well as People and Assets.
* **Edit** Prevent deletion when Accessories or Consumables are assigned to location

**Describe the solution you'd like**
Review and enhancement of the Location module, to enhance its capabilities, as per the above.

**Describe alternatives you've considered**
Continue to work around the above limitations, leading to additional effort.

**Additional context**

**Comment by joepitt91** [comment]
Still required IMHO

**Comment by marrodox** [comment]
Not sure why this is closed, it's a fantastic suggestion that still isn't added. I'd love to see this in a near release.
