### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by josephsmartinez** [snipe/snipe-it#5698]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Not a bug. More of an internal error or installation error. I trust this software as been tested. 

**Expected behavior**

I trying to get my CentOS environment setup to run snipe-IT.
I have been reading through the documentation online https://snipe-it.readme.io/docs/ which as been extremely helpful so far, but now I am stumped.

After reading past issues from the GitHub site for similar issues. 
https://github.com/snipe/snipe-it/issues/4300

I notice that the... 

/var/www/html/inventorydb/storage/logs directory is empty for starters. 

and the log from /etc/htttp/log is reporting 
10.105.2.6 - - [12/Jun/2018:10:21:29 -0400] "GET /inventorydb/public/ HTTP/1.1" 500 –

I have followed the step from this link https://snipe-it.readme.io/docs/installation-issues#section-fatal-error-uncaught-exception-reflectionexception-with-message-class-log-does-not-exist
as suggested from @snipe from a past issue with another person. 

However...

I removed the composer.lock but when run php composer.phar dump-autoload command I get: 

[RuntimeException]
  Could not scan for classes inside "/var/www/html/inventorydb/vendor/pa
  tchwork/utf8/src/Normalizer.php" which does not appear to be a file no
  r a folder

Add if I run php composer.phar update --no-dev --prefer-source I get:

Do not run Composer as root/super user! See https://getcomposer.org/root for deta
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.4.35
    - laravel/framework v5.4.35 conflicts with roave/security-advisories[dev-mast
    - laravel/framework v5.4.35 conflicts with roave/security-advisories[dev-mast
    - Installation request for laravel/framework 5.4.35 -> satisfiable by laravelrk[v5.4.35].
    - Installation request for roave/security-advisories dev-master -> satisfiablve/security-advisories[dev-master].

Running update with --no-dev does not mean require-dev is ignored, it just means ages will not be installed. If dev requirements are blocking the update you have ve those problems.

This my first time working with Laravel Fram-Work so any assistance would be appreciated. Thank you !

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version:  v4.4.1
 - OS:  CentOS
 - Web Server:  Apache,
 - PHP Version:  v5.6.35-dev

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Current

**Smartphone (please complete the following information):**
 - Device: iPhone6
 - OS: iOS8.1
 - Browser: safari
 - Version 22

**Error Messages**
No error message within the snipe-IT log files :(
https log error
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
10.105.2.6 - - [12/Jun/2018:10:21:29 -0400] "GET /inventorydb/public/ HTTP/1.1" 500 -

**Additional context**
More information is pending from the team I am working with. 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by josephsmartinez** [comment]
just read this -> https://github.com/snipe/snipe-it/issues/5337
Should we just update to PHP7? or use an older version of Snipe-IT with with PHP5?

**Comment by snipe** [comment]
Comment out the `roave/security-advisories` line in composer.json, run composer update. Once composer has run successfully, uncomment the  `roave/security-advisories` line. It's a sorry workaround, but it should do it.

**Comment by josephsmartinez** [comment]
All good. 

I needed the following --  $yum install php php-tecnickcom-tc-lib-barcode.noarch --- to execute:  
- php composer.phar install --no-dev --prefer-source

After all dependencies are installed, then using the following works prefect: 
- sudo php artisan key:generate

------------Installation-------------------
Some helpful resources for other people: 
- https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-centos-7
- https://snipe-it.readme.io/docs/requirements   ***VERY IMPORTANT****
- https://www.vultr.com/docs/how-to-install-snipe-it-on-centos-7
- https://www.linux.com/learn/intro-to-linux/2017/12/how-manage-users-groups-linux
- https://www.digitalocean.com/community/tutorials/how-to-create-a-sudo-user-on-centos-quickstart

----------Common Error -----------------------------
[RuntimeException] vendor does not exist and could not be created.
- https://github.com/panique/huge/issues/392

DocumentRoot 
- https://snipe-it.readme.io/docs/subdirectories

By default, the policy httpd_can_network_connect_db is disabled.
- https://magento.stackexchange.com/questions/195019/sqlstatehy000-2002-permission-denied

THANK YOU!!!!! @snipe 

Joseph Martinez
FIU Linux Admin

**Comment by meisaputra** [comment]
i have Snipe-IT v4.5.0 build 3701 (gbf1e742df) on PHP Version 5.6.36 and Laravel Version 5.4.35
my case is empty list in assets page whereas there are records in database.
i found pointer in laravel.log like this... but i can't find the line to fix it.

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dh_dh_assets.company_id' in 'where clause' (SQL: select count(*) as aggregate from `dh_assets` inner join `dh_status_labels` as `dh_status_alias` on `dh_status_alias`.`id` = `dh_assets`.`status_id` and `dh_status_alias`.`archived` = 0 where `dh_dh_assets`.`company_id` = 1 and `dh_assets`.`deleted_at` is null)' in <hosting>/vendor/laravel/framework/src/Illuminate/Database/Connection.php:647

please fix it and let me know by mention me. thank you.

**Comment by snipe** [comment]
@meisaputra your issue is unrelated to the original issue, and would be better suited as its own issue. You need to run migrations to add the new column.
