### ISSUE TITLE
Keep sorting order in URL link

### ISSUE THREAD

**Issue by passboltUser** [snipe/snipe-it#5701]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.4.1 - build 3636 (master)

**Is your feature request related to a problem? Please describe.**
When under `/hardware` and one sorts by certain column, update/generate the URL so that the sorting order can be sent to other people by copying the browsers URL.
Sample: https://domainname.com/hardware?sorted_by=my_field_name

**Describe alternatives you've considered**
Instead of generating the URL in the browser's URL field automatically when sorted by a column, a button can be pressed and the URL is copied into the clipping board.

**Comment by snipe** [comment]
That’s a lot more complacated than it sounds. I’d be willing to accept a PR for this, but it’s likely not so,etching we’ll get to any time soon.
