### ISSUE TITLE
V2 to V4

### ISSUE THREAD

**Issue by murtazamaz** [snipe/snipe-it#5703]
**Server (please complete the following information):**
 - Snipe-IT Version V4
 - OS: Windows 10
 - Web Server: WAMP
 - PHP Version 7

I have Snipe version snipe-it-2.1.0 which is running fine. I have installed WAMP 3.0.6 and Snipe Version snipe-it-4.0.13.  everything is fine.

I have Backup i just need to import in new version 4.0.13, it is giving error.

pls help how to do.

**Comment by snipe** [comment]
Without knowing the error it's giving you, I'm not sure how we're supposed to help you.

**Comment by murtazamaz** [comment]
Thanks For Reply, actually Error is different pls find below some details

01: I Export data from 2.10 Snipe and Import in 4.0.13 snipe.
02: Both Computers are different and in both machine both Snipe running perfectly.
03: Data Export very Smoothly without any Error means successful.
04: After Import when i check the website (localhost) it says Whoops, look like something went Wrong.

Please help what shall i do.
regards

**Comment by murtazamaz** [comment]
HI, pls help me to resolve the issue.... i am waiting.

thanks

**Comment by sjlaird** [comment]
Why not try the v2 to v3 then v3 to v4 upgrade path? Maybe you will have more success.

**Comment by murtazamaz** [comment]
Hmmm.. actually this will be long path....ok until i get any response i will try this if i can do.
i am not expert i did this by watching a youtube video so ... i do not know if same way for V3 configuration.
