### ISSUE TITLE
Deplystatus does not change color and missing from dashboard. 

### ISSUE THREAD

**Issue by darthvidur** [snipe/snipe-it#5704]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)
when checking out an asset the status does not change to deployed. 
-----

#### Actual Behavior

(what actually happens goes here)
When i checkout a asset it it shows as Ready to Deploy Deployed
So my dashboard graph shows everything as ready to deployed even when it is in fact deployed to users.
https://imgur.com/a/TMSSxpT

https://imgur.com/a/WbWQOMh
-----

#### Please confirm you have done the following before posting your bug report:

- [Y ] I have enabled debug mode 
- [Y ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  Upgrade
- Version of Snipe-IT you're running Version v4.4.1 - build 3636 (master)
- Version of PHP you're running PHP 7.0.22-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running mysql  Ver 15.1 Distrib 10.0.33-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- What OS and web server you're running Snipe-IT on ubuntu0.16.04 Apache? 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) git pull  install.sh 
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error Not that I can see
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error =  Asset page and Dashboard.
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. Not showing anything 
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
[2018-06-13 12:46:43] production.ERROR: Debugbar exception: Route [debugbar.openhandler] not defined.

- Include what you've done so far in the installation, and if you got any error messages along the way.
I just upgraded it a long time ago i just noticed this issue when my boss wanted a report.
- Indicate whether or not you've manually edited any data directly in the database = Not that I am aware of

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Deployed is not a true status, it's a meta status which could be true across multiple statuses that are deployable.
