### ISSUE TITLE
Dashboard: Clear history

### ISSUE THREAD

**Issue by NK74** [snipe/snipe-it#5705]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
How to clear history on dashboard ? thanks

**Screenshots**
![image](https://user-images.githubusercontent.com/17825769/41354589-abb9f96e-6f1f-11e8-8dc9-ca3579c699eb.png)

**Server (please complete the following information):**
 - Snipe-IT Version v4.4.1 - build 3636 (master)
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version 7.1

**Comment by snipe** [comment]
There is no way to do that. Removing the records from the database would be the only way, and that sort of defeats the purpose of having an asset tracker that keeps history.
