### ISSUE TITLE
Forbidden You don't have permission to access /index.php on this server.

### ISSUE THREAD

**Issue by idonttakedrugsitakenaps** [snipe/snipe-it#5707]
**Describe the bug**

To start, I'm an IT intern in a firm which I'm being tasked to find an open source software for IT asset management database and thats why I'm here, please bear with me because I'm not an IT pro and I try my best.

I implemented Snipe-IT in one of the servers I built yesterday. I installed Snipe IT V4.4.1 - build 3636 (master), Composer v1.6.5, WAMPSERVER 3.0.6 in Windows Server 2012 R2 environment. So far, everything is working just fine, I can RDP to my server, access localhost and Snipe-IT can be access inside the server. However, when I'm not in that server and I'm trying to access the server itself from a firefox/chrome in one of the PCs in the network http://myservername/index.php. I get Forbidden You don't have permission to access /index.php on this server error. I've tried accessing .env file and index.php using Notepad++ to see if I can solve my problem but it doesnt get me anywhere and I was wondering if you guys could help me out. Maybe in a nutshell my question would be, how do I access snipe-it that I installed in Windows Server without RDP-ing to the server and just access it directly from a browser? In addition, how do I set the webpage to be https? Thank you for your help, greatly appreciated!

**Server (please complete the following information):**
 - Snipe IT V4.4.1 - build 3636 
 - OS: Windows Server 2012 R2
 - Web Server: WAMPSERVER 3.0.6, Apache, 
 - PHP Version: 7.0.10

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chrome
 - Version 66.0.3359.181 (Official Build) (64-bit)

**Error Messages**
Forbidden
You don't have permission to access /index.php on this server.
Apache/2.4.23 (Win64) PHP/7.0.10 Server

**Additional context**
- Fresh install
- What OS and web server you're running Snipe-IT on
- I guess its a manual installation because I extracted Snipe-IT.zip to www folder in WAMP 
- I edited .env file to APP_URL=http://it-ik and DB_DATABASE=asset and DB_USERNAME=root

**Comment by snipe** [comment]
> how do I access snipe-it that I installed in Windows Server without RDP-ing to the server and just access it directly from a browser? 

I'm guessing maybe your server name in Apache isn't set up correctly? It's kind of hard to tell without seeing what your setup is. If you're getting a 403 error (not a DNS error), that means (in theory) that the server is able to accessed via http. (You might try to determine whether or not for sure that the 403 you're getting it actually coming from your Snipe-IT server though, versus another server on the network.)

> In addition, how do I set the webpage to be https? 

You would need to set up an SSL certificate for it. (We strongly recommend against using self-signed certificates, as it gets users used to accepting invalid certificate prompts.)

**Comment by idonttakedrugsitakenaps** [comment]
I'm sure the 403 error is coming from the exact server where I installed Snipe-IT because when I try to access it using the http://myservername/index.php and http://serveripaddress/index.php I'd get the same error, I guess I didnt set up the Apache correctly. It was not until yesterday I know Apache exist and I still have no idea how to access the setting although I can see it when I click WAMP icon on the tray. Could you point me where is the Apache setting so I could point it out to you? Or anything that can help me?

**Comment by snipe** [comment]
I don't use WAMP, so I can't really help that much here, but I think you want to be looking at section 6 of the documentation: https://snipe-it.readme.io/docs/wamp

**Comment by snipe** [comment]
(Remember that after changes to Apache, you have to restart the web server.)

**Comment by sid8000** [comment]
@idonttakedrugsitakenaps Click on WAMP, then on apache, and then open httpd.conf file. In this file make necessary changes(Virtual Host settings) as per the documentation.
Follow provided documentation, it has everything to run Snipe-IT successfully.
