### ISSUE TITLE
Whoops, looks like something went wrong. - After power outage

### ISSUE THREAD

**Issue by shawner47** [snipe/snipe-it#5708]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

After an extended power outage the server came up and even though it showed that there were 145 devices in the dashboard, there were none when trying to look at All Assets (or any other page).  After trying the Common Issue fixes, the page now only comes up with the Whoops... message.  I have tried to upgrade to the latest version from github with the same result.  

**To Reproduce**
Unknown how to reproduce.  

**Expected behavior**

Page to load normally.

**Screenshots**

![image](https://user-images.githubusercontent.com/31420763/41368715-bb4ecf80-6f10-11e8-9185-3053252d29f5.png)

**Server (please complete the following information):**
 - Snipe-IT Version I do not know the version that was pulled from git.  I assume the latest stable.
 - OS: [e.g. Ubuntu, CentOS] CentOS 7
 - Web Server: [e.g. Apache, IIS] Apache 
 - PHP Version  7.1.14

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome and Firefox
 - Version [e.g. 22] Chrome 66.0.3359.181  Firefox 60.0.2

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

UnexpectedValueException                                                                          The  stream or file "/var/www/html/snipeit/storage/logs/laravel.log" could  not be opened: failed to open stream: Permission denied
--
in StreamHandler.php (line 107)

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? Upgrade at this point.  I can roll back to pre-upgrade (with error still existing)
- What OS and web server you're running Snipe-IT on  - CentOS and Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)  Manual originally, migrated to git after error.
- Include what you've done so far in the installation, and if you got any error messages along the way.  Nothing that was not in the original install instructions as well as upgrade instructions.  No errors with those at the time.  This has been working flawlessly for months until the power outage. 
- Indicate whether or not you've manually edited any data directly in the database - Have not

Seeing that it was a potential permissions error, I have also tried without success, to change permissions for the storage/logs folder (chmod -R 777).  Verified the permissions changed but still the same error.  I am now at a loss. 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Looks like you just need to make the `storage` directory and its subdirectories writable. It looks like you tried that, so the only other thing it really could be is that you're running SELinux, and you may have turned it off the first time you set it up, but it wasn't set to up to be turned off on a reboot.

https://snipe-it.readme.io/docs/linuxosx#section-notes-on-selinux

**Comment by shawner47** [comment]
@snipe 
Gah!  I KNEW I was missing something!  Thank you, thank you, thank you!  I had to install semanage (yum install policycoreutils-python for anyone who is wondering), but after that I followed the steps in your link and BAM!  Back online.  Thank you again!

![image](https://user-images.githubusercontent.com/31420763/41382772-a4523300-6f3b-11e8-9c4f-ff89bf9310f4.png)

**Comment by snipe** [comment]
Nice work! 

![baymax-balalala](https://user-images.githubusercontent.com/197404/41384034-75c91a48-6f28-11e8-83e5-d39742baf853.gif)

Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
