### ISSUE TITLE
Trouble Creating New Asset

### ISSUE THREAD

**Issue by leetheod** [snipe/snipe-it#5709]
#### Please confirm you have done the following before posting your bug report:

- [ X ] I have enabled debug mode 
- [ X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

I am not able to create a new asset because I cannot select a model nor make a custom one. Whenever I attempt to make a custom asset model, I cannot select a category which is a requirement. If I attempt to select 'Model' it says "No results found"

**To Reproduce**
1. Go to 'Create New' -> 'Asset'
2. Click on 'New' (Next to Model)
3. Click on 'Select Category'
4. "No results found"

**Expected behavior**

A list of categories to choose from should appear which I can select from so that I can create an asset.

**Screenshots**
![test](https://user-images.githubusercontent.com/31257221/41384513-2003b8a4-6f2b-11e8-8ba2-4942127a99ea.png)

**Server (please complete the following information):**
 - Snipe-IT Version-- 4.4.1
 - OS: [e.g. Ubuntu, CentOS]-- Debian
 - Web Server: [e.g. Apache, IIS]-- Apache2
 - PHP Version-- 7.0.27

**Error Messages**
I could not reproduce this error in the Snipe-IT Demo.

- Include any additional information you can find in `storage/logs` and your webserver's logs.
production.ERROR: ReflectionException: Class session does not exist in /var/www/snipe-it/$pe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php:729

**Additional context**
This was a fresh install on Debian 9 with Apache2. I manually installed this with the following:

The steps below document my process. 
In order to install Apache (web server) and other PHP libraries, I typed "sudo apt install apache2 libapache2-mod-php php php-pdo php-mbstring php-tokenizer php-curl php-mysql php-ldap php-zip php-fileinfo php-gd php-dom php-mcrypt php-bcmath –y" 
Next, I needed to start the Apache service and enable it to start upon boot and so I used the commands "sudo systemctl start apache2" and "sudo systemctl enable apache2" 
Next, I needed to install and configure MariaDB. First, I added the APT key using "sudo apt-get install software-properties-common dirmngr -y 
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xF1656F24C74CD1D8"  
Then I added the MariaDB repository using "sudo add-apt-repository 'deb [arch=amd64,i386,ppc64el] http://ftp.hosteurope.de/mirror/mariadb.org/repo/10.1/debian stretch main'" 
Next we checked for any updates using "sudo apt-get update –y" 
Now using "sudo apt install mariadb-server mariadb-client –y" we finish installing MariaDB 
Similar to Apache, I needed to start MariaDB and enable it to start upon boot using "sudo systemctl start mysql" and "sudo systemctl enable mysql" 
Next I ran "sudo mysql_secure_installation" in order to secure my MariaDB  
Set root password? [Y/n] nRemove anonymous users? [Y/n] yDisallow root login remotely? [Y/n] yRemove test database and access to it? [Y/n] yReload privilege tables now? [Y/n] 
Next I logged into the MariaDB shell using "mysql -u root –p" 
 I then typed "MariaDB [(none)]> create database snipeitdb character set utf8;" in order to create the database for Snipe-IT 
Then I created a Snipe-IT user with "GRANT ALL PRIVILEGES ON snipeitdb.* TO 'snipeit'@'localhost' IDENTIFIED BY 'password';"  
Next I typed "flush privileges;" to flush the privileges and then "quit" to exit 
 
Now that LAMP is fully installed, we move towards installing Snipe-IT. 
 
You can download the latest version of the Snipe-IT from Git repository with the following command "git clone https://github.com/snipe/snipe-it snipe-it" 
Then using "sudo mv snipe-it /var/www/" we move the snipe-it directory to the apache root directory 
Next I needed to install Composer to the system using "curl -sS https://getcomposer.org/installer | php 
sudo mv composer.phar /usr/local/bin/composer"  
Using "cd /var/www/snipe-it" and "sudo composer install --no-dev --prefer-source" I made sure I was in the snipe-it directory and installed the PHP dependencies using Composer 
After this I copied the sample .env file to make edits using "sudo cp .env.example .env" and "sudo nano .env" 
Next, I generated the APP_key found in the .env file with "sudo php artisan key:generate" 
Then, to populate mysql with snipe its database, type "sudo php artisan migrate" 
Next, provide the appropriate ownership and file permissions with the following command: "sudo chown -R www-data:www-data storage public/uploads" and  
"sudo chmod -R 755 storage public/uploads" 
 
To Configure Apache, do the following: 
To create an apache virtual host directive for Snipe-IT create the snipeit.conf file inside /etc/apache2/sites-available directory using "sudo nano /etc/apache2/sites-available/snipeit.conf"  
<VirtualHost *:80> 
<Directory /var/www/snipe-it/public>        
Require all granted         
AllowOverride All 
</Directory> 
   DocumentRoot /var/www/snipe-it/public     
ServerName example.com         
ErrorLog /var/log/apache2/snipeIT.error.log 
       CustomLog /var/log/apache2/access.log combined 
</VirtualHost> 
To enable the virtual host, use "sudo a2ensite snipeit.conf" 
Then, I enabled PHP mcrypt, mbstring module and Apache rewrite module with the following commands "sudo phpenmod mcrypt" and "sudo phpenmod mbstring" and "sudo a2enmod rewrite" 
Finally, restart apache web server to apply all the changes using "sudo systemctl restart apache2" 
 
Firewall 
By default, Snipe-IT runs on port 80, so you will need to allow port 80 through the firewall. To install the firewall type "sudo apt-get install ufw –y" 
Once UFW is installed, enable it to start on boot time with the following command "sudo ufw enable" 
Next, allow port 80 using the following command "sudo ufw allow 80" 
Finally, reload the UFW firewall rule with the following command "sudo ufw reload" 

I did not manually edit any data.

**Comment by leetheod** [comment]
edited photo

**Comment by snipe** [comment]
Have you created any categories yet?

**Comment by leetheod** [comment]
I didn't create any asset categories. Where would I do that?

**Comment by leetheod** [comment]
HI snipe, could you help me with this one? I still can't figure this out.
