### ISSUE TITLE
Feature request: Asset location history

### ISSUE THREAD

**Issue by joseph707** [snipe/snipe-it#571]
Hi, not sure if this has been addressed. Is it possible to have a history of the location of asset movement. That is, if I had a desktop, rather than checkout  to a user, we can checkout to a particular location/ area. And if that desktop has been moved, we can enter the system the next new location.

I believe currently we can get a history of the checkin/ checkout in the asset history.

This will be useful if we wanted to get a trail of asset movement. If exportable as a part of asset report, this would be fantastic.

Regards

Jo

**Comment by snipe** [comment]
Hi @joseph707 - this has been addressed in #512 and a few others, but I can't find them right this second.

**Comment by joseph707** [comment]
Hi Snipe, yep. I saw the other 2 tickets having the same request. And I see this is an enhancement and in the pipeline.

excellent.

regards

Jo
