### ISSUE TITLE
Permissions issue, granted full permissions and forced through

### ISSUE THREAD

**Issue by moltari** [snipe/snipe-it#5712]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
when going to the site to start precheck i get a "whopps something went wrong" error. when turning on debugging ti seems to be issues accessing a log file. check permissions, iusr has "full control" and i forced inheritance down the chain for: sotrage, vendor, and public.

i checked the file lsited below and saw that it's the laravel.log file. that file doesn not exist, so i could not check it for explicit permissions issues. 

this is an install on windows server 2012 using IIS 8 (ver 6.2)

**To Reproduce**
open page, see error 

**Expected behavior**
preflight starts 
**Screenshots**
will include error text 

**Server (please complete the following information):**
 - Snipe-IT Version 4.4.1
 - OS: windows server 2012 standard 
 - Web Server: IIS 
 - PHP Version 7.2? (hard to check,, released march this year.)

all testing done on server using IE and Chrome

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

(1/1) UnexpectedValueExceptionThe stream or file "C:\inetpub\wwwroot\SnipeIT\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied
--
in StreamHandler.php (line 107)
at StreamHandler->write(array('message' => 'UnexpectedValueException: The stream or file "C:\\inetpub\\wwwroot\\SnipeIT\\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\StreamHandler.php:107Stack trace:#0 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)#1 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(337): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#2 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(616): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#3 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#4 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#5 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(221): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#6 C:\\inetpub\\wwwroot\\SnipeIT\\app\\Exceptions\\Handler.php(39): Illuminate\\Support\\Facades\\Facade::__callStatic(\'error\', Array)#7 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#9 C:\\inetpub\\wwwroot\\SnipeIT\\public\\index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#10 {main}', 'context' => array(), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'production', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2018-06-14 16:17:36] production.ERROR: UnexpectedValueException: The stream or file "C:\\inetpub\\wwwroot\\SnipeIT\\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\StreamHandler.php:107Stack trace:#0 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)#1 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(337): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#2 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(616): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#3 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#4 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#5 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(221): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#6 C:\\inetpub\\wwwroot\\SnipeIT\\app\\Exceptions\\Handler.php(39): Illuminate\\Support\\Facades\\Facade::__callStatic(\'error\', Array)#7 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#9 C:\\inetpub\\wwwroot\\SnipeIT\\public\\index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#10 {main} '))in AbstractProcessingHandler.php (line 37)
at AbstractProcessingHandler->handle(array('message' => 'UnexpectedValueException: The stream or file "C:\\inetpub\\wwwroot\\SnipeIT\\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\StreamHandler.php:107Stack trace:#0 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)#1 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(337): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#2 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(616): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#3 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#4 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#5 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(221): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#6 C:\\inetpub\\wwwroot\\SnipeIT\\app\\Exceptions\\Handler.php(39): Illuminate\\Support\\Facades\\Facade::__callStatic(\'error\', Array)#7 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#9 C:\\inetpub\\wwwroot\\SnipeIT\\public\\index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#10 {main}', 'context' => array(), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'production', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2018-06-14 16:17:36] production.ERROR: UnexpectedValueException: The stream or file "C:\\inetpub\\wwwroot\\SnipeIT\\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\StreamHandler.php:107Stack trace:#0 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)#1 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(337): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#2 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(616): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#3 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#4 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#5 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(221): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#6 C:\\inetpub\\wwwroot\\SnipeIT\\app\\Exceptions\\Handler.php(39): Illuminate\\Support\\Facades\\Facade::__callStatic(\'error\', Array)#7 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 C:\\inetpub\\wwwroot\\SnipeIT\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#9 C:\\inetpub\\wwwroot\\SnipeIT\\public\\index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#10 {main} '))in Logger.php (line 337)
at Logger->addRecord(400, object(UnexpectedValueException), array())in Logger.php (line 616)
at Logger->error(object(UnexpectedValueException), array())in Writer.php (line 203)
at Writer->writeLog('error', object(UnexpectedValueException), array())in Writer.php (line 114)
at Writer->error(object(UnexpectedValueException))in Facade.php (line 221)
at Facade::__callStatic('error', array(object(UnexpectedValueException)))in Handler.php (line 39)
at Handler->report(object(UnexpectedValueException))in HandleExceptions.php (line 81)
at HandleExceptions->handleException(object(UnexpectedValueException))

**Additional context**
fresh install
windows server 2012,
had to manually install PHP as windows web platform installer wouldnt connect to download sources
the one thing i haven't installed is GD or the atlernative, i'm having a hard time finding an easy way to deploy without compiling from source. 

no more context, just thanks to anyone providing assistance with this. 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by EarlRamirez** [comment]
@moltari are you still having issues with your permission?

**Comment by moltari** [comment]
Hello @EarlRamirez i am still having issues with this. sadly we've been swamped and i havn't had time to play with it further, was hoping someone might be able to point out what i'm missing!

thanks,
