### ISSUE TITLE
Reminder email to IT and employee about check in date?

### ISSUE THREAD

**Issue by lry-rincon-jekyll** [snipe/snipe-it#5713]
Has this been implemented? :)

Snipe - you guys are awesome! Love the program!

**Comment by mainstayit** [comment]
It is indeed:

`php artisan snipeit:expected-checkin`

**Comment by mylle** [comment]
Can I change from how many days before checkin date the reminders are sent? 
Now my users get a reminder every day 7 days before checkin date.

**Comment by Coolfeather2** [comment]
would also like to modify it
