### ISSUE TITLE
Help: Ubuntu distro upgrade to 18.04 > only a text page is shown

### ISSUE THREAD

**Issue by cslucian** [snipe/snipe-it#5714]
> Well after upgrading my Ubuntu server from Ubuntu 18.04 all I see is the bellow text page. And I don't know what can I do to restore it.  I can't reinstall all but maybe we can fix it.
> 
> Thank you in advance
> 
> **Describe the bug**
> when I access snipe all I see is:
> 
> <?php
> 
> /**
>  * Laravel - A PHP Framework For Web Artisans
>  *
>  * @package  Laravel
>  * @author   Taylor Otwell <taylor@laravel.com>
>  */
> 
> /*
> |--------------------------------------------------------------------------
> | Register The Auto Loader
> |--------------------------------------------------------------------------
> |
> | Composer provides a convenient, automatically generated class loader for
> | our application. We just need to utilize it! We'll simply require it
> | into the script here so that we don't have to worry about manual
> | loading any of our classes later on. It feels nice to relax.
> |
> */
> 
> require __DIR__.'/../bootstrap/autoload.php';
> 
> /*
> |--------------------------------------------------------------------------
> | Turn On The Lights
> |--------------------------------------------------------------------------
> |
> | We need to illuminate PHP development, so let us turn on the lights.
> | This bootstraps the framework and gets it ready for use, then it
> | will load up this application so that we can run it and send
> | the responses back to the browser and delight our users.
> |
> */
> 
> $app = require_once __DIR__.'/../bootstrap/app.php';
> 
> // set the public path to this directory
> $app->bind('path.public', function() {
>     return __DIR__;
> });
> 
> /*
> |--------------------------------------------------------------------------
> | Run The Application
> |--------------------------------------------------------------------------
> |
> | Once we have the application, we can handle the incoming request
> | through the kernel, and send the associated response back to
> | the client's browser allowing them to enjoy the creative
> | and wonderful application we have prepared for them.
> |
> */
> 
> $kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);
> 
> $response = $kernel->handle(
>     $request = Illuminate\Http\Request::capture()
> );
> 
> $response->send();
> 
> $kernel->terminate($request, $response);
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> Perfectly wotking Ubuntu 16.04 upgrade it to 18.04
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Server (please complete the following information):**
>  - Snipe-IT Version latest stable
>  - OS: Ubuntu 18.04
>  - Web Server: Apache
>  - PHP Version 7.2
> 
> **Desktop (please complete the following information):**
>  - OS:Ubuntu 18.04
>  - Browser [e.g. chrome, safari]
>  - Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
>  - Device: [e.g. iPhone6]
>  - OS: [e.g. iOS8.1]
>  - Browser [e.g. stock browser, safari]
>  - Version [e.g. 22]
> 
> **Error Messages**
> - WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
> - If a stacktrace is provided in the error, include that too.
> - Any errors that appear in your browser's error console.
> - Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
> - Include any additional information you can find in `storage/logs` and your webserver's logs.
> 
> **Additional context**
> - Is this a fresh install or an upgrade? 
> - What OS and web server you're running Snipe-IT on
> - What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
> - Include what you've done so far in the installation, and if you got any error messages along the way.
> - Indicate whether or not you've manually edited any data directly in the database
> 
> Add any other context about the problem here.
> 
> Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.
> 
> 
>

**Comment by cslucian** [comment]
....Later edit... downgraded PHP 7.2 to 7.1 and all seems ok now

**Comment by snipe** [comment]
First google result: https://askubuntu.com/questions/1028422/php-shows-up-as-plain-text-after-upgrade-to-18-04/1028574
