### ISSUE TITLE
Latest Docker image of snipe-it .env does not contain  DB_PORT=${MYSQL_PORT_3306_TCP_PORT}

### ISSUE THREAD

**Issue by thatmichael85** [snipe/snipe-it#5718]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When I try to deploy a snipe-it image that connects to a MySQL DB that uses a port other than 3306, Debug info shows that connection is refused.

**To Reproduce**
1. Use lates snipe-it docker image.
2. Follow steps in https://snipe-it.readme.io/v4.4.0/docs/docker -> Using a Standalone Database (not a container) to create my_standalone_env_file
3. Create a MYSQLDB that listens to a port other an 3306.
4. Set MYSQL_PORT_3306_TCP_PORT variable to a port set in 3.

**Expected behavior**
Connection should succeed.

**Screenshots**
N/A

**Server (please complete the following information):**
 - Snipe-IT:Latest Docker image 
 - OS: Ubuntu
 - Docker: Docker version 18.03.1-ce, build 9ee9f40

**Error Messages**

(2/3) PDOExceptionSQLSTATE[HY000] [2002] Connection refused
--
in PDOConnection.php (line 47)
at PDOConnection->__construct('mysql:host=172.17.0.1;port=**3306**;dbname=snipeit', 'snipeit', '12345678', array(0, 2, 0, false, false))in Connector.php (line 65)
at Connector->createPdoConnection('mysql:host=172.17.0.1;port=**3306**;dbname=snipeit', 'snipeit', '12345678', array(0, 2, 0, false, false))in Connector.php (line 44)

**WORK AROUND**
1. Connect to Snipe-it docker image using sudo docker exec -it <snipe_container_name> bash -l
2. add in the .env file DB_PORT=${MYSQL_PORT_3306_TCP_PORT}

**Comment by snipe** [comment]
@uberbrady have you had a chance to look at this?

**Comment by uberbrady** [comment]
Okay, fix is now in the Develop branch.
