### ISSUE TITLE
Create License function is Access forbidden!: Error 403

### ISSUE THREAD

**Issue by nvcuong0702** [snipe/snipe-it#5721]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**
1. Go to 'Login Website: http://localhost:8080'
2. Click on 'Create New --> License'

**Screenshots**
![untitled](https://user-images.githubusercontent.com/40381144/41581645-59388774-73c9-11e8-9af1-240240a56675.png)
![untitled1](https://user-images.githubusercontent.com/40381144/41581648-5a48cea8-73c9-11e8-9c3e-fb658fa9c12a.png)

**Server (please complete the following information):**
 - Snipe-IT Version: 4.4.1
 - OS: Window Server 2016
 - Web Server: Apache
 - PHP Version: 5.6

**Desktop (please complete the following information):**
 - OS: window 10
 - Browser chrome
 - Version 67

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

When i use port default. It is OK! When i begin create virtual port in XAMPP. It is not OK!
It can not create new license as Screenshots

Can you help me please!

**Comment by sid8000** [comment]
Instead of localhost have you tried with IP address.
Also have you updated "Listen" line with 8080 port?

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/xampp#section-remove-built-in-aliases
