### ISSUE TITLE
Unable to sync

### ISSUE THREAD

**Issue by lockbucket** [snipe/snipe-it#5723]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After upgrading to the current version, we are unable to synchronize AD users after performing an LDAP sync either through the application or through the command line.  We have also verified that we could connect and authenticate to LDAP on multiple DCs.

![snipe_it_sync](https://user-images.githubusercontent.com/31346961/41601683-b0c6a4c4-739e-11e8-9c5b-289415740915.png)

**To Reproduce**

**Expected behavior**
When performing an LDAP Sync, synchronize new/old accounts into the User database.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.4.1
 - OS: [e.g. Ubuntu, CentOS] Windows 2016
 - Web Server: [e.g. Apache, IIS] IIS
 - PHP Version 5.6.31

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Error Messages** (N/A)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. NA
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? Upgrade
- What OS and web server you're running Snipe-IT on - Windows 2016 IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - no manual updating

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by lockbucket** [comment]
I have updated my PHP to 7.2.2 and I am still receiving the error.  I have verified that the php_ldap.dll is enabled and I have been able to authenticate without issue.

**Comment by snipe** [comment]
Please provide answers to more of the questions in the original issue template.

What's in your error logs? What happens when you try to synchronize? (Does nothing since, do you get an error, etc?)

> After upgrading to the current version, we are unable to synchronize AD users after performing an LDAP sync either through the application or through the command line. We have also verified that we could connect and authenticate to LDAP on multiple DCs.

Proving your LDAP settings would probably help here too.

**Comment by lockbucket** [comment]
I have enabled debug mode, and no errors are being written to the logs.  As far as when I synchronize, I have provided a screenshot in my initial question as it reports "LDAP sync successful".  I have tried clearing the cache and verifying that we are running the latest version of snipe-it.

![ad](https://user-images.githubusercontent.com/31346961/41742152-c77a5704-7562-11e8-9faf-aed52965dfb8.png)

**Comment by MSTigers** [comment]
What about when you do Test LDAP login?

**Comment by MSTigers** [comment]
I'd speculate that your LDAP filter being `&(cn=)` may need to put it to `&(cn=*)`

**Comment by lockbucket** [comment]
I was able to successfully login through LDAP and I have changed to &(cn=*) with still no luck.

**Comment by nmilanov** [comment]
I have the same problem. Here some details:

- Snipe-IT Version v4.4.2 - build 3666 (master)
- OS: Ubuntu 16.04.4 LTS
- Web Server: Apache/2.4.18
- PHP Version 7.0.30

I didn't get any error message (with APP_DEBUG=true ).
In browser, after sync - it return "Success: LDAP Import successful. ", but I didn't see new users. I see some old users that are updated (or at least this is written in column "Notes").

This is not fresh install - this is an update from 4.1.3 to lastest version.

**Comment by lockbucket** [comment]
Yep, I have even tried a different account, migrating the database, and still no luck.

**Comment by lockbucket** [comment]
I found the issue, with previous versions, we could use sAMAccountName for the username when trying to sync LDAP.  With the new version, I modified it to all lowercase samaccountname and it synced correctly.
