### ISSUE TITLE
Categories not showing list, but data is in the actual DB.

### ISSUE THREAD

**Issue by bigfootboet** [snipe/snipe-it#5724]
#### Please confirm you have done the following before posting your bug report:

- [Y ] I have enabled debug mode  - YES debug is enabled but in debug no errors appear.
- [ Y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) - YES, I have searched and read many posts.

**Describe the bug**
When I select the categories page, nothing shows, just says 'No Matching records found'. I can also without any problems create a new category from the main Categories page, but once the new category is create and the screen refreshes, nothing shows in the list, just says 'No Matching records found'. 

However under the Modals page, if I edit a model I can use the drop-down and I can see all categories, and I can also create a new category from that page.

I did see the post: https://github.com/snipe/snipe-it/issues/2144 and this sounds like what happened to me. 
However I cannot remember what category was edited which may be causing he problem, and I also cannot restore a backup that might be many months old as I don't know how far back this problem started.

**Server (please complete the following information):**
 - Snipe-IT Version - V4.4.1 build 3636
 - OS: [e.g. Ubuntu, CentOS] - Windows 2008 R2, IIS7
 - Web Server: [e.g. Apache, IIS], IIS7
 - PHP Version - 7.2.5

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Win 7 SP2 and Win10 is the same
 - Browser [e.g. chrome, safari] - firefox or chrome is the same

**Error Messages**
- WITH DEBUG TURNED ON, - No errors with Debug switched on.
- Any errors that appear in your browser's error console.- Nothing.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - No

**Additional context**
- Is this a fresh install or an upgrade? Fresh instl, but tried migrate,...
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - GIT
- Indicate whether or not you've manually edited any data directly in the database - Yes, We manually edited cost price of assets. Only viewed the Categories table to check if all data is there.

**Comment by snipe** [comment]
We'll need errors from your error log.

**Comment by bigfootboet** [comment]
Hello, and thank you very much for the quick response!

Please find attached 'laravel.log', I have only copied the last few hundred entries in the log, else is would be huge.

I see there is an error: Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'licenses.category_id' in 'where clause' in C:\inetpub\wwwroot\snipe-it\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:79

[laravel.log](https://github.com/snipe/snipe-it/files/2118343/laravel.log)

Hope this all helps.

**Comment by snipe** [comment]
Whenever you see a column not found error, you have to run migrations. `php artisan migrate`

**Comment by bigfootboet** [comment]
Hi there. I did already run migrations, but let me do them again and I will provide feedback. Thank you for your time.

**Comment by bigfootboet** [comment]
Strange, but when I try php artisan migrate now I get the below msg:

![migrate err](https://user-images.githubusercontent.com/40418871/41645524-8a588b6c-7471-11e8-8a50-599806eacd0a.JPG)

**Comment by bigfootboet** [comment]
Hello. I have exported the migrations table to csv and attached in zip format.

[Migrations.zip](https://github.com/snipe/snipe-it/files/2118626/Migrations.zip)

**Comment by bigfootboet** [comment]
Hello. Some feedback. I have done a manual install of Snipe-it on a temp workstation running WAMP 3.1, then imported the data from the production IIS server and on the temp workstation I can see the categories fine. Does it sound like a re-installation is required?

**Comment by bigfootboet** [comment]
Some more feedback. I renamed the snipe-it folder on the production server, copied the entire snipe-it folder from the temp workstation onto the production server, set the .env file for the production environment and all is working perfect. I can see the categories as it should be.

**Comment by snipe** [comment]
That... doesn’t make a lot of sense, TBH, but I’m glad you got everything sorted
