### ISSUE TITLE
Change checkout email text

### ISSUE THREAD

**Issue by aldervall** [snipe/snipe-it#5725]
#### Please confirm you have done the following before posting your bug report:

- [- ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

I love this software! Thanks Snipe! I have changed my language to sv in the .env file, however when email sent on asset checkout i get a Thanks, (Sitename) In English at the end of every email. Everything else is in Swedish just this "Thanks" at the end.
Which php/txt file can i change this outcome to Swedish?
 
**To Reproduce**
Checkout asset and send automatic Email in Swedish

**Expected behavior**
Should be the correct language when email is sent. "Tack" instead of "Thanks"

**Screenshots**
<a href="https://ibb.co/ijwujd"><img src="https://preview.ibb.co/iserVJ/Sk_rmklipp.png" alt="Sk_rmklipp" border="0"></a>

**Server (please complete the following information):**
 - Snipe-IT Version: 4.1
 - OS: Ubuntu 16.4
 - Web Server: Apache
 - PHP Version: 7.1

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Chrome
 - Version -

**Additional context**
Fresh install

There are afew other issues but those are not as critical as this one because this email is going out to clients.

**Comment by aldervall** [comment]
Found this in.
/www/snipeit/resources/views/notifications/markdown/checkout-asset.blade.php

**Comment by matmair** [comment]
I had the same error, will submit PR shortly
