### ISSUE TITLE
Upgrading to 3.6 - Artisan Migrate fails

### ISSUE THREAD

**Issue by sarcophilus** [snipe/snipe-it#5737]
#### Expected Behavior (or desired behavior if a feature request)

Database migrates

-----

#### Actual Behavior

Have version 

Trying to upgrade from v0.3.6 alpha to version v3.6.6. I have downloaded source code in tar.gz, and followed steps in https://snipe-it.readme.io/docs/upgrading-to-v3 

Came to step 7 without any errors, but when running php artisan migrate I get the error: 

 [Doctrine\DBAL\DBALException]
  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySqlPlatform
   may not support it.

I have found another issue here describing the same problem, but it said that it was fixed in 3.5 and later, and I am now in 3.6. 

Have not gotten so far as to start snipe it, so questions about web page and debug are not relevant

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade 
- Version of Snipe-IT you're running: From v0.3.6 alpha to v3.6.6
- Version of PHP you're running: v 5.6.36 
- Version of MySQL/MariaDB you're running: 5.5.40
- What OS and web server you're running Snipe-IT on: Ubuntu 14.4, Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual installation of downloaded files

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Wow, that's OLD! 

The fix is in 3.6.0, according the source code. You can see the commit here:
https://github.com/snipe/snipe-it/commit/0a506120b772649b98f92389cc36c9eb33f885b8

When you look at the tables, are there any enum fields present?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
