### ISSUE TITLE
Help with turning checkout_date to a required parameter

### ISSUE THREAD

**Issue by shivamtrivedi** [snipe/snipe-it#5738]
#### Expected Behavior (or desired behavior if a feature request)

When I try to request an asset checkout, I would like for the checkout date and the notes field to be required fields. 

-----

#### Actual Behavior

I changed the "AssetCheckoutRequest.php" file to match the following rules below:
public function rules()
` 
   {
        $rules = [
            "assigned_user"         => 'required_without_all:assigned_asset,assigned_location',
            "assigned_asset"        => 'required_without_all:assigned_user,assigned_location|different:'.$this->id,
            "assigned_location"     => 'required_without_all:assigned_user,assigned_asset',
            "checkout_to_type"      => 'required|in:asset,location,user',
            "checkout_date"         => 'required|date',
        ];

        return $rules;
    }
`

This causes undefined errors, and does not let me submit the form even when the information is correct. 

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade

- Version of Snipe-IT you're running
4.3

- Version of PHP you're running
7.2.3

- Version of MySQL/MariaDB you're running
mysql  Ver 15.1 Distrib 10.0.34-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

- What OS and web server you're running Snipe-IT on
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
I am on the Checkout Asset page. I am interacting with the Checkout_date element

- If a stacktrace is provided in the error, include that too.

- Any errors that appear in your browser's error console.

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.

- Include any additional information you can find in `storage/logs` and your webserver's logs.

- Include what you've done so far in the installation, and if you got any error messages along the way.

- Indicate whether or not you've manually edited any data directly in the database
No direct edit to the database. Only to the PHP file

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I'd need to see specific errors.
