### ISSUE TITLE
is it possible to bulk check out with csv file?

### ISSUE THREAD

**Issue by BaekSeungGyeong** [snipe/snipe-it#5740]
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by snipe** [comment]
Yes
