### ISSUE TITLE
QueryException：SQLSTATE[42S01]: Base table or view already exists:

### ISSUE THREAD

**Issue by wh211212** [snipe/snipe-it#5741]
# QueryException
SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'accessories_users' already exists (SQL: create table `accessories_users` (`id` int unsigned not null auto_increment primary key, `user_id` int null, `accessory_id` int null, `assigned_to` int null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci engine = InnoDB)

**Comment by snipe** [comment]
Looks like something went wrong with your migrations. Can you show me the contents of your migrations table? (And next time please fill out the issue template. We ask those questions for a reason.)
