### ISSUE TITLE
Better Management of E-Mail-Notifications

### ISSUE THREAD

**Issue by PascalTr** [snipe/snipe-it#5746]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.4.1
 - OS: Windows Server 2012 R2
 - Web Server: IIS
 - PHP Version: 7.2.6

**Is your feature request related to a problem? Please describe.**
I wanted to enable notifications only for Users of a specific group (or one specific email) and only on asset checkin/checkout. The user that the asset is checked in or checked out should not get notified.
On the website it is listed as an option for mails that are send to admins but there is no clear option in the Alerts settings. 

**Describe the solution you'd like**
I'd like to have some checkboxes for emails that are going to be send. Something like the list on the new website at "Email Notifications" but with checkboxes right next to it so I can select, that no emails should get send to the user. 

**Describe alternatives you've considered**
Maybe that we can change it in the .env file.

**Additional context**
If there already is an option to change this I'd be more than happy to know where it is located.

**Comment by snipe** [comment]
That is not currently an option. 

The way checkouts currently work makes this a little more complicated than it might seem, but we can take a look. 

In the meantime, you can just remove the email addresses for people you don’t ever want to email.
