### ISSUE TITLE
Does snipe-it works with 64-bit version of WAMP?

### ISSUE THREAD

**Issue by kashifkhawaja** [snipe/snipe-it#5747]
In the snipe-it documentation(https://snipe-it.readme.io/docs/wamp) it says to install 32-bit version of WAMP, does this means that we can't use it with a 64bit version of WAMP?

**Comment by SjamonDaal** [comment]
Just try this, it should work. If it doesn't work use the 32-bit installer or let us know what doesn't work.

**Comment by kashifkhawaja** [comment]
ok, thank you.
