### ISSUE TITLE
Custom email templates (made easy)

### ISSUE THREAD

**Issue by SjamonDaal** [snipe/snipe-it#5748]
**Server (please complete the following information):**
 - Snipe-IT Version v4.4.1
 - OS: Debian
 - Web Server: Apache
 - PHP Version  7.1

**Describe the solution you'd like**
We would like to have some kind of easy option within snipe-it to be able to change the email template/layouts for every mail. This so that everyone can mail with there own email templates, add details to the email and remove details easily!

**Describe alternatives you've considered**
We thought about 2 options and would like to hear suggestions from you guys!
1. Adding a section in the admin control panel to change email templates (textbox with html code).
2. Email template folder on the server.

**Additional context**
I personally like the first option because we can make a section with suggested variables to send values in the email. If anyone knows a better way or already build something like this, please respond! Do you like this idea, please like!

**Comment by SjamonDaal** [comment]
Yep

**Comment by SjamonDaal** [comment]
still relevant

**Comment by LordDamocles** [comment]
Still Relevant.

**Comment by SvenMazet** [comment]
I'd very much appreciate a way to customise the email layout: the blank space between assets is just, for the lack of a better word, huge. 
![snipe_email](https://user-images.githubusercontent.com/68681773/97692153-b4c71400-1a9f-11eb-8e5f-03f921ec8c13.png)

**Comment by MorganRedell** [comment]
Did this ever become a feature? I'd like to customize our Missed Expected Check In emails, because the default template isn't helpful for our purposes. We are a hosted customer running version 6.0.13 if that helps!

**Comment by snipe** [comment]
It's not currently on the short term roadmap.

**Comment by MorganRedell** [comment]
Understood, y'all are rapidly expanding. Is there currently any way at all to customize Missed Expected Check in emails?

**Comment by snipe** [comment]
Alas, not without messing with the code. Which you're perfectly allowed to do, it just can sometimes make upgrading a bit of a pain, since you'll need to reapply those changes with the updated codebase. :(

**Comment by snipe** [comment]
It's not off the roadmap - we just have a few bigger things we need to handle first :(
