### ISSUE TITLE
Search Function

### ISSUE THREAD

**Issue by sandw0rm** [snipe/snipe-it#5749]
Firstly, thank you for any help with this and Secondly thank you for such a handy and helpful tool, its fantastic and gotten me into my bosses good books.

**Server (please complete the following information):**
 - Snipe-IT Version 4.4.1
 - OS: [e.g. Ubuntu, CentOS] Ubuntu 16.04.4
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version: 7.0.30-0

**Is your feature request related to a problem? Please describe.**
On, the dashboard we have the ability to search via asset ID, is it possible to change that to search by user.?

**Describe the solution you'd like**
Is there an ability to change the search field

**Describe alternatives you've considered**
Can search via going into assets and doing it that way, just wondering if possible to change the search parameter on the dashboard to make it easier for the more lazier staff

**Comment by fryguy503** [comment]
I would like to piggy back on this. The customization of the top search bar would be great if we could select what field to search by. e.g. I would like to search by Serial Number instead of Asset tag.

**Comment by memtech3** [comment]
NO STALE!

**Comment by snipe** [comment]
> Can search via going into assets and doing it that way, just wondering if possible to change the search parameter on the dashboard to make it easier for the more lazier staff

That top search is meant to be used with a barcode scanner, that's why it only accepts asset tags. More explanation can be found here: #3216
