### ISSUE TITLE
requestable-assets.blade.php - disable asset for requestable if there is expected_checkin_date

### ISSUE THREAD

**Issue by leonmflai** [snipe/snipe-it#5750]
**Server (please complete the following information):**
 - Snipe-IT Version  Snipe-IT version | v4.4.2  build 3666 (gaa5003d29)
 - OS: [e.g. Ubuntu
 - Web Server: Apache
 - PHP Version  7.0.30-0ubuntu0.16.04.1

I was using Snipe-IT v4.2 b4 and changed some codes on this page.

 snipe-it/resources/views/account/requestable-assets.blade.php

I added some codes to check if the asset it loan out then asset will not be requestable.

``
 _@if ($asset->assigned_to != '' && $asset->assigned_to > 0)
   Unavaiable due to Checked Out
 @else		
	@if ($asset->isRequestedBy(Auth::user()))
	        {Form::submit(trans('button.cancel'), ['class' => 'btn btn-danger btn-sm'])}}
	@else
		{{Form::submit(trans('button.request'), ['class' => 'btn btn-primary btn-sm'])}}
@endif_
                                           				

However, I found code of v4.4.2 has been significantly changed and I can no longer identify these code in the code of same path / file.

Anyone can help me? Thanks so much.

**Comment by else** [comment]
Please don't mention me :S

**Comment by snipe** [comment]
You'd probably need to add another field to the AssetsTransformer `transformRequestedAsset` method, and then add a javascript formatter to the `resources/views/partials/bootstrap-tables.blade.php` file.
