### ISSUE TITLE
Custom Report Must have Users Manager Name

### ISSUE THREAD

**Issue by mahesh2471990** [snipe/snipe-it#5752]
Snipe-IT Version 4.4.0
OS: Windows Server 2016
Web Server: IIS
PHP Version 5.56

**Is your feature request related to a problem? Please describe.**
I was trying to get the Manager Name in Custom report.
I have made changes in 
 SnipeIT\app\Http\Controllers\ReportsController.php
In Section of **Exports the custom report to CSV** (from Line No 292)
Line after line 402 after Employee Num
`if ($request->has('manager')) {  $header[] = trans('admin/users/table.manager'); }`

So I get Display in Custom Report Like this below image
![capturemanager](https://user-images.githubusercontent.com/16305213/41960258-f27c93dc-7a0c-11e8-878f-e2d1971bc074.JPG)

Once I generate Report I should Manager Name where I have added some code like this. 
Line No 605 after Employee num
`if ($request->has('manager')) {
                        // Only works if we're checked out to a user, not anything else.
                        if ($asset->checkedOutToUser()) {
                            $row[] = ($asset->assignedto) ? $asset->assignedto->manager_id: '';
                        } else {
                            $row[] = ''; // Empty string if unassigned
                        }`
**Where in result in .csv i get only Manager id like this below image. because it my bad i have given manager_id**
![capturecsv](https://user-images.githubusercontent.com/16305213/41960669-ffcb5c16-7a0d-11e8-9fd6-c30bfecd90fa.JPG)

If I change `$row[] = ($asset->assignedto) ? $asset->assignedto->manager: '';`

I get a result like this all the things of the user info.
![capturemah](https://user-images.githubusercontent.com/16305213/41960851-6f50b6f8-7a0e-11e8-9a5c-0f6b8c3f2ef8.JPG)

And also tried with changes `$row[] = ($asset->assignedto) ? $asset->assignedto->manager->first_name:";`
Then when i hit generate report it throw the error.

![capturebrowser](https://user-images.githubusercontent.com/16305213/41961049-021be9b2-7a0f-11e8-8e09-8031b419e633.JPG)

can anyone help to get Manager name in Custom Report

**Comment by snipe** [comment]
This is already on the develop branch.
