### ISSUE TITLE
PHP Parse error while running "php artisan key:generate"

### ISSUE THREAD

**Issue by Tomasthanes** [snipe/snipe-it#5753]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
# php artisan key:generate
PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/html/snipe-it-4.4.1/artisan on line 31

**To Reproduce**
I'm following the Install Manual and am at the step https://snipe-it.readme.io/docs/generate-your-app-key
When I run the command, I get the error message.

**Expected behavior**
I expect it to generate the app key and update the .env file.

**Screenshots**
Since I'm on the CLI, I don't think a screen shot would help

**Server (please complete the following information):**
 - Snipe-IT Version 4.4.1
 - OS: [e.g. Ubuntu, CentOS] Oracle Linux Server release 7.5
 - Web Server: [e.g. Apache, IIS] httpd.x86_64                       2.4.6-80.0.1.el7
 - PHP Version  php.x86_64                         5.4.16-45.el7

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome (once I get it installed)
 - Version [e.g. 22] N/A

**Smartphone (please complete the following information):**
N/A

**Error Messages**
See the describe the error section above.

**Additional context**
- Is this a fresh install or an upgrade? Fresh.
- What OS and web server you're running Snipe-IT on? See above
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)?  I downloaded the tarball and am following the instructions.  I can provide a detailed Server Build document with the steps I took to get here.
- Include what you've done so far in the installation, and if you got any error messages along the way.  I'm following the Install Manual in order.
- Indicate whether or not you've manually edited any data directly in the database.  No database yet.  We are using MySQL Community once we get there.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Per the [requirements](https://snipe-it.readme.io/docs/requirements), Snipe-IT requires PHP >= 5.6.4

**Comment by Tomasthanes** [comment]
You are so quick!  Thank you.
