### ISSUE TITLE
Unable to customize new asset fileds

### ISSUE THREAD

**Issue by arun767** [snipe/snipe-it#5756]
**Server (please complete the following information):**
 - Snipe-4.4.2 
 - OS: Ubuntu 16.04
 - Web Server:Apache/2.4.18 
 - PHP Version 7.0

I have configured a server for my store department. In the new asset tab, I can see that there are some tabs which I don't require. please help, whether I can customize the new asset tab with my custom field.

**Comment by EarlRamirez** [comment]
@arun767, this should get you going _https://snipe-it.readme.io/docs/custom-fields_

**Comment by arun767** [comment]
thanks. I have checked but whatever custom filed I have configured, those filed not came in new asset windows and I am not able to see any option to remove which are currently there like purchase,supplier like

**Comment by EarlRamirez** [comment]
@arun767 you will need to add the custom fields to a custom field set and then associate the custom field set to the model of the equipment that you will like the custom fields to appear on.

**Comment by arun767** [comment]
@EarlRamirez Is there any option to delete the fields currently present  custom fields in create new asset templete.

**Comment by snipe** [comment]
@arun767 you manage which fields are associated to a fieldset in the Custom Fields section. Click on the fieldset name and you can add/remove associated fields. 

<img width="1388" alt="screen shot 2018-07-05 at 8 06 36 pm" src="https://user-images.githubusercontent.com/197404/42357905-fdaa31f0-808e-11e8-8220-41bb45fbb688.png">
