### ISSUE TITLE
New Install of Snipe-IT 

### ISSUE THREAD

**Issue by flogadob** [snipe/snipe-it#5757]
#### Expected Behavior (or desired behavior if a feature request)

(trying to run composer install --no-dev --prefer-source to install Snipe-IT dependencies)

-----

#### Actual Behavior

(Im getting a problem:  installation request for tecnickcom/tc-lib-barcode 1.15.7 -> satisfiable by tecnickcom/tc-lib-barcode[1.15.7] tecnickcom/tc-lib-barcode 1.15.7 requires ext-gd * the requested PHP extension gd is missing from your system)

Im completely new to Linux, never done this before, so its probably really simple, but Ive no idea how to install this
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode - haven't finished setup of Snipe-IT
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)  Yes

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh install
- Version of Snipe-IT you're running The guide i'm following says the latest version of Snipe-IT will be  installed when i run the git clone command so im assuming thats v4.4.1
- Version of PHP you're running PHP7.2
- Version of MySQL/MariaDB you're running MySQL Version 5.7
- What OS and web server you're running Snipe-IT on Ubuntu Server 18.04 Nginx
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error N/A
- If a stacktrace is provided in the error, include that too. N/A
- Any errors that appear in your browser's error console. N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. N/A
- Include any additional information you can find in `storage/logs` and your webserver's logs. N/A
- Include what you've done so far in the installation, and if you got any error messages along the way. N/A
- Indicate whether or not you've manually edited any data directly in the database N/A

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by flogadob** [comment]
@EarlRamirez  i've got the ISO downloading now ill give this a shot instead, thank you very much for replying

**Comment by EarlRamirez** [comment]
@flogadob, you are most welcome, let me know how it goes.

**Comment by paulo1624** [comment]
you must install first this missing file tecnickcom, you may get the file also here in github.

**Comment by hbqclh** [comment]
You can try the docker way. All will become simple.

**Comment by AbiRavina** [comment]
Hi All,

Nice to see you,
Would you like to share your experience installation Snipe IT on Windows 7,
Currently I am not success to install event I have follow manual instruction from this link : https://snipe-it.readme.io/docs/windowsiis

If you don't mind please cache me up on this email 

Thank you

**Comment by sid8000** [comment]
@AbiRavina try using WAMP instead of IIS..https://snipe-it.readme.io/docs/wamp

**Comment by snipe** [comment]
> satisfiable by tecnickcom/tc-lib-barcode[1.15.7] tecnickcom/tc-lib-barcode 1.15.7 requires ext-gd

It's telling you that the system needs the GD Library, [per the requirements](https://snipe-it.readme.io/docs/requirements).
