### ISSUE TITLE
Feature Request - Review and modify expected check-in dates

### ISSUE THREAD

**Issue by MSWork79** [snipe/snipe-it#5762]
**Server (please complete the following information):**
 - Snipe-IT Version Version v4.3.0 - build 3586
 - OS: Ubuntu 16.04
 - Web Server: Apache2
 - PHP Version  7.1.17-1
--

**Is your feature request related to a problem? Please describe.**
Yes. The problem I have is when an employee's contract is not renewed/retiring/etc., we often know the dates ahead of time, some times a month or more in advance. Previously their assets when checked-out had no "expected" check-in date. This has changed but I cannot update Snipe-IT to reflect this.

**Describe the solution you'd like**
To be able to view an asset's expected check-in date and then be able to modify it. E.g., previously there was no expected date, but now it will be Oct 31, 2018. This way when their deadline comes up and have yet to check-in their assets we can track through the same fashion of an asset that had an expected check-in date.

**Describe alternatives you've considered**
3rd party reminders/notifications/tracking that would basically say "Go check Snipe on this date to see if they still have assets out.

**Comment by gvlterr0r** [comment]
This would be a great feature to have, we have the same scenario with employees and contract dates.

**Comment by romannazarenko** [comment]
+1

**Comment by hixair** [comment]
We often have employees contracts extended and it's not really convenient to have to checkin and checkout devices to put a new expiry date.
By the way, i send all my love to the project team, Snipe-IT is so nice and convenient, made a big part of our work a lot easier. 
HUGE Thanks !!!!!

**Comment by MSTigers** [comment]
Yep still relevant stale bot. _*shoos*_

**Comment by hixair** [comment]
**It is** still relevant. Thank you stale bot, I know you only do you job ;)

**Comment by hixair** [comment]
Still relevant. Come back after v5 is out !

**Comment by MSTigers** [comment]
Preemptive stalebot shooing. Still very interested in this as well. Would be incredibly convenient for tracking assets in relation to getting them back from users in a timely, organized fashion.

**Comment by renardeau** [comment]
+1
I'm new to snipe-IT, but as far as I understood, there is no possibility to edit the check-out data. 
We do experience a need to update the expected check-in date, but also other check-out fields like the notes.

**Comment by viclou** [comment]
+1 FD#10829

**Comment by mahesh2471990** [comment]
+1

**Comment by ajsy** [comment]
+1
btw from database you can update the expected check-in

**Comment by fkick** [comment]
+1 on this...we deal with a lot of freelancers who often get extended or wrap early depending on shifting project due dates and this would be a great help.

@ajsy how are you updating from the database?

Thanks!

**Comment by ajsy** [comment]
I'm using phpmyadmin web console
the table name is assets 
the column name is expected_checkin

![Picture](https://user-images.githubusercontent.com/35658596/61353106-a4bdfd80-a877-11e9-8446-ccf736d641a2.jpg)

**Comment by aldervall** [comment]
+1.
I would also take a look at **accountExpires** _Attribute_ in LDAP.
Implement a reminder email before it expires.
It's quite often that users have an AD account that get prolonged. Should reduce the hassle of editing endates in 2 instanses.

**Comment by avassdal** [comment]
+1

**Comment by MBSMC** [comment]
I would also be interested in modify expected check-in dates so that way when we find out someone is leaving the organisation the date can be updated to follow up with them.

**Comment by hixair** [comment]
I realize that I would like to have this feature and I would like to be able to update it via API too ! We update our directory and home tools with the end date we hate from the HR suite, would be great to edit asset end dates as well !

**Comment by sambayford** [comment]
+1
duplicate of [https://github.com/snipe/snipe-it/issues/5522](url)

**Comment by hixair** [comment]
It is !

**Comment by maxlehot1234** [comment]
Anything @snipe ? ;)

**Comment by maxlehot1234** [comment]
It is

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jhamernik** [comment]
Still relevant - much needed feature

**Comment by G13312** [comment]
Still relevant! A much needed addition since we dont always know when an employee is leaving and also good to track assets that havent been returned in time!

**Comment by MSWork79** [comment]
COVID hit, I've got about 500+ devices spamming out email notifications for needing to be checked in since we changed our return policy (extending possession through the summer).

This is unpleasant. Disabling email alerts doesn't seem to stop them from going out either.

![image](https://user-images.githubusercontent.com/33290254/84665834-ec189800-aee5-11ea-885a-3ab2bcc469c7.png)

**Comment by sean-borg** [comment]
@snipe I am interested in fixing this issue however am a little unsure how best to implement the fix
and wanted to get some feedback on my thoughts of a potential fix.

My current ideas are
 - Having expected checkin date as link similar to Manufacturer, category and model.
   Clicking link will take you to an edit date page.           
 - Add another option in the actions tab "Update expected Checkin date"
   Clicking the option will take you to an edit date page.
 - Being able to edit date directly in the View Asset > details page.
   This idea I'm very unsure about it doesn't really fit with the rest of the page and having looked at how the 
   table is loaded it could become unnecessarily  complicated

Open to other suggested fixes :)

**Comment by hixair** [comment]
Looks great !
The way I was expecting it to work : using the edit button for the check-out asset (asset update page), you should be able to edit a form item with the current date, select a new date and save to update !

**Comment by G13312** [comment]
Same as @hixair ! Going in a checked-out asset > Actions > Edit Asset then be able to edit the Expected Checkin Date from there would be the best way imo. Would also be great to be able to see it in Reports, great for tracking assets that are not returned in time.

Thanks!

**Comment by MSWork79** [comment]
As I mentioned a few comments above, disabling it doesn't seem to have any effect. While I would love to be able to modify/change the expected date, I need to fix my problem now. Anyone know of a way to STOP it from sending out notifications, besides the obvious of going into .env and removing email settings?

I do not want to go through and manually check-in/check-out every single asset all over again.

**Comment by MSWork79** [comment]
So clarification from my original request.

>**Describe the solution you'd like**
>To be able to view an asset's expected check-in date

This **CAN** be viewed in the Asset View page
![image](https://user-images.githubusercontent.com/33290254/86788620-fe40ae80-c02b-11ea-9db2-a3c0237240f4.png)

and then select the field in the columns display
![image](https://user-images.githubusercontent.com/33290254/86788949-5f688200-c02c-11ea-9053-6d0097602508.png)

Result:
![image](https://user-images.githubusercontent.com/33290254/86789164-9fc80000-c02c-11ea-92de-44cf9a6c35b5.png)

Just wanted to clarify that you can indeed VIEW the expected check-in dates. Of course, even if you try to slipstream an import, you have to map it which you can't do (hence this feature request).

![image](https://user-images.githubusercontent.com/33290254/86789302-c4bc7300-c02c-11ea-9845-3462f0ca0d33.png)

**Comment by aldervall** [comment]
> 
> 
> @snipe I am interested in fixing this issue however am a little unsure how best to implement the fix
> and wanted to get some feedback on my thoughts of a potential fix.
> 
> My current ideas are
> 
>     * Having expected checkin date as link similar to Manufacturer, category and model.
>       Clicking link will take you to an edit date page.
> 
>     * Add another option in the actions tab "Update expected Checkin date"
>       Clicking the option will take you to an edit date page.
> 
>     * Being able to edit date directly in the View Asset > details page.
>       This idea I'm very unsure about it doesn't really fit with the rest of the page and having looked at how the
>       table is loaded it could become unnecessarily  complicated
> 
> 
> Open to other suggested fixes :)

Iam guessing alot of snipe-it users are importing Users/Accounts via LDAP/AD.
To correlate the attribute **"accountExpires"** with **"Expected Checkin Date"** or to have that option when you checkout a device.

So whenever you do a LDAP sync the Expected Checkin Date are changed equal to what LDAP says.
And iam guessing HR systems are getting their information from LDAP/AD or vice versa.

This is just my take on it :)

Thanks @sean-borg for taking a look.

**Comment by hixair** [comment]
Wow this is actually the best way to do it in my opinion too !
We are already leveraging the accountExpires date for a lot of thing, makes sense to set an expected checkin date !

**Comment by MSWork79** [comment]
I would advise caution as mentioned above, for anything that's automated to be flexible or the ability for it to be optional. The sync/LDAP/automated seems pretty cool of course, but back in July of 2018 I referenced #5864 "User's Resignation Date" as it was discussed there briefly to tie those two together. I still am against it, especially if A.) is required and B.) holds up the implementation of _this_ feature due to complexity.

Me in 2018, and me now:
> I personally wouldn't want anything done automatically with this besides an email notification saying "past expiration/past resignation."

**Comment by fkick** [comment]
I agree with @MSTigers and would prefer that the extension have a manual option rather then be tied to the AD attribute. We often see case of HR misfiling wrap dates were AD would be incorrect as we deal with a lot of free lancers. Manually being able to set the extension date would be preferable in those circumstances.

**Comment by hixair** [comment]
Or maybe add a checkbox to the LDAP settings to select to sync the dates or not ?

**Comment by aldervall** [comment]
![Maby as easy as this](https://user-images.githubusercontent.com/25901015/87121949-32aea780-c284-11ea-8f95-60e0828ec438.png)

Maybe?

**Comment by sean-borg** [comment]
> Iam guessing alot of snipe-it users are importing Users/Accounts via LDAP/AD.
> To correlate the attribute **"accountExpires"** with **"Expected Checkin Date"** or to have that option when you checkout a device.
> 
> So whenever you do a LDAP sync the Expected Checkin Date are changed equal to what LDAP says.
> And iam guessing HR systems are getting their information from LDAP/AD or vice versa.
> 
> This is just my take on it :)
> 
> Thanks @sean-borg for taking a look.

I like the idea however I think this may be better as a separate request :)

Unfortunately with my current knowledge of snipeit and LDAP I wont be able to tackle it. 
But should be different enough to warrant another feature request :)

**Comment by Salzi** [comment]
Still relevant.

**Comment by ivan5rov** [comment]
This is so very much relevant, I hope we see it implemented one day (edit expected check-in date). Right now my workaround is check-in/check-out with expected return date, but this creates unnecessary noise in logs (and emails). Please please please add this feature!

**Comment by shigel** [comment]
+1

**Comment by AvalonBurned** [comment]
+1

**Comment by MSWork79** [comment]
I have it on decent authority from a peer that this is live on 5.0.13-pre

**Comment by fkick** [comment]
This looks to be live in v5.0.12 - build 5705 (master).

To adjust (or bulk adjust checkin date) from the Asset screen select the assets you need to adjust and go to the bulk edit menu (even if it's a single asset you are changing).

A new field "Expected Checkin Date" is available and you can set a new date then click save.

<img width="1030" alt="Screen Shot 2021-02-25 at 10 30 25 AM" src="https://user-images.githubusercontent.com/8224667/109184460-a38fca80-7754-11eb-9057-80a84a051a08.png">

**Comment by MSWork79** [comment]
This is live as mentioned above.
