### ISSUE TITLE
Admins cannot import csv

### ISSUE THREAD

**Issue by mihsu81** [snipe/snipe-it#5763]
#### Please confirm you have done the following before posting your bug report:

- [y ] I have enabled debug mode 
- [ y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Admins (not Super Users) cannot import csv files from the Import Page. The selected file loads until 10% and stops. Super Users can import csv files and process them without issues.

**To Reproduce**

**Expected behavior**
Admins should be able to import csv files.

**Screenshots**
![image](https://user-images.githubusercontent.com/40715497/42124918-d59dc6fe-7c74-11e8-88d4-f7313fa05671.png)

**Server (please complete the following information):**
 - Snipe-IT Version v4.4.2 - build 3666 (master)
 - OS: CentOS 7.5.1804
 - Web Server: Apache 2.4.6
 - PHP Version: 5.6.36

**Desktop (please complete the following information):**
 - OS: Windows 10, Server 2012 R2
 - Browser Chrome, Edge
 - Version 67.0.3396.99, 42.17134.1.0

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error (Not getting any errors)
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. (None)
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. (The demo does not support Import)
- Include any additional information you can find in `storage/logs` and your webserver's logs. (Couldn't find any info related to this)

**Additional context**
- Is this a fresh install or an upgrade? Upgrade
- What OS and web server you're running Snipe-IT on: CentOS 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): GIT
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database: No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Can you import as a super user? This doesn't sound like a user permissions issue to me, more like upload directory permissions or something else.

**Comment by mihsu81** [comment]
Yes, i can upload as a Super User. Any suggestions what other logs i could check, except what is suggested in the template or Debug mode?
