### ISSUE TITLE
Suggestion: Asset by Status pie chart to show Deployed asset

### ISSUE THREAD

**Issue by zainudin01** [snipe/snipe-it#5768]
Hi there,

I love that pie chart to show off to my boss that we have everything (asset) in place. Would be great if the legend "Ready to deploy" to be displayed as "Deployed" colored as blue. There should be another "ready to deploy" with green color showing number of asset which are not deployed yet. Currently we need to add new status = "in storage" just to show we have a few asset which is ready to be deployed. 

Pie should be as below:

![image](https://user-images.githubusercontent.com/40679548/42194061-aaddfd76-7ea4-11e8-95d9-a7c84ed6b000.png)

Snipe-IT version | v4.3.0 build 3610 (g4ba9792fb)
Software License | AGPL3
PHP Version | 7.0.30-0ubuntu0.16.04.1
Laravel Version | 5.4.35

**Comment by ernestasen** [comment]
I think simlar issue was already reported here: https://github.com/snipe/snipe-it/issues/5454
