### ISSUE TITLE
QR Code Generation [port number in APP_URL not followed in image URL]

### ISSUE THREAD

**Issue by ndom91** [snipe/snipe-it#5769]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

I'm sorry to have deleted most of the template, but this I think I've got the problem narrowed down pretty well. 

So I read a lot of the other "QR Code not generating" posts, and checked my APP_URL in the .env file and it was obviously wrong as well..

The problem I have now, however, is that the URL in the Asset page, for example, isn't including the port number which I specified in the APP_URL variable. My `APP_URL='http://192.168.1.240:8001'` and the URL when I inspect the page is simply `http://192.168.1.240/hardware/9/qr_code`.

If I visit that URL in the browser and manually add `:8001` the QR Code loads perfectly. 

For comparison - the images load with the port number in the URL perfectly as well. See page source:
```
<img src="http://192.168.1.240:8001/uploads/models/1-hppavilionpng.png" class="assetimg img-responsive">
<img src="http://192.168.1.240/hardware/9/qr_code" class="img-thumbnail pull-right" style="height: 100px; width: 100px; margin-right: 10px;">
```

Am I possibly just formatting the APP_URL string wrong? Does it maybe not support port numbers?

EDIT: When generating the label sheet with the qr-codes on them, they also point to `http://192.168.1.240:8001/hardware/xx` - so even there the port is included and correct. Only on the asset page itself, where the asset image and qr code are shown, the port does not seem to be included. Very strange..

**Comment by ndom91** [comment]
So I've cleared my caches with the commands mentioned in the 'common issues' page of the snipe-it docs:

```
composer dump-autoload
composer clear-compiled
php artisan config:clear
php artisan view:clear
php artisan cache:clear
php artisan route:clear
```

However, I CANNOT for the life of me get snipe to accept my addition of the port to my .env file.

I also grepped a bit and found in `resources/views/hardware/view.blade.php` the code for generating the qr code line in the asset view page:
```
              @if  ($snipeSettings->qr_code=='1')
                 <img src="{{ config('app.url') }}/hardware/{{ $asset->id }}/qr_code" class="img-thumbnail pull-right" style="height: 100px; width: 100px; margin-right: 10px;">
              @endif
```

And I noticed the lines above it, for example where it pulls the image of the device (which works 100% in my case) is created via a ` <img src="{{ url('/') }}/uploads/models/{{{ $asset->model->image }}}" class="assetimg img-responsive">` So I tried using the `{{ url('/') }}` in place of the `{{ config('app.url') }}` but that change wasn't applied either. Even after clearing my cache/configs/everythign with the commands above.. 

I also tried to just manually add `:8001` to the original qr code URL generating code in view.blade.php, but that wasn't applied either. 

Its like no matter what changes I make - nothing is getting through. 

Am I missing something here?!

**Comment by ndom91** [comment]
@snipe 

Of course it ended up being a silly error on my part, got it working :) 
I had snipe cloned into /opt/snipe and /var/www/html/snipe and I kept making changes to the .env file that wasn't the "live" version of snipe :laughing:

**Comment by ndom91** [comment]
No further response - issue is closed then.

If anyone comes across this and is also interested in setting up a custom tab in the asset view, you can get a hold of me on here and on twitter [at]ndom91.

**Comment by yk48** [comment]
@ndom91  Can you kindly navigate the process of customization of your asset page and the QR Code?

**Comment by ndom91** [comment]
@yk48 sorry I dont work at the company where I was running this anymore.
