### ISSUE TITLE
Enhancement: Allow Asset Acceptance without user having to log in [$100]

### ISSUE THREAD

**Issue by hansenc0705** [snipe/snipe-it#577]
In our case we don't plan on communicating usernames and passwords (at least till LDAP auth is setup). Would be nice to use the asset acceptance but not require the user to log in to accept the asset.
##

**Comment by phantomofrussia** [comment]
I would like to add this is something I would like implemented as well. The I work for a healthcare nonprofit and the medical staff already complain a lot about having so many different logins for this, that and the other. Once LDAP auth is setup I would require them to login.

**Comment by pfeigl** [comment]
Was about to add exactly this requirement but found this one, which I want to promote.
Without AD support, it's close to impossible for us (>200 users) to communicate login information for yet another system.

**Comment by kobie-chasehansen** [comment]
a nice to have feature along with this would be to remind users every x months about the agreed terms of use.

**Comment by adam-nelson** [comment]
Wouldn't bet better just walk around with a tablet/ipad and have the customer sign?

**Comment by kobie-chasehansen** [comment]
would rather it being automatic.

**Comment by Ahimta** [comment]
Is this issue still open?

**Comment by adam-nelson** [comment]
In some environments a signature on an mobile phone would be enough

https://szimek.github.io/signature_pad/

On Tue, Mar 21, 2017 at 5:22 AM, Abdullah Alansari <notifications@github.com

**Comment by Ahimta** [comment]
It's technically feasible to give someone the ability to accept an asset (or do any other privileged action)  without requiring them to log in. If the bounty is still open and there's still demand for this, I will work on it.

**Comment by ericdude101** [comment]
Im not oppose to havi g the users login, but I would really like the app to redirect the users to the origional destination upon login. So once they link ober from their email and login it continues to drop them at the asset acveptance screen instead of the dashboard. As it sits, unless the user is already logged into snipe-it prior to clicking the link, the link is useless.

**Comment by lokesh-sg** [comment]
I second to @ericdude101, even I face the same issue. Asset acceptance takes user to login page and post login it just redirects Dashboard rather getting into actual asset acceptance page. Can we have solution for this. I am seeing this issue from version 3.2.x
