### ISSUE TITLE
No way to create a new manufacture in new asset window

### ISSUE THREAD

**Issue by rjs5327** [snipe/snipe-it#5776]
#### Expected Behavior (or desired behavior if a feature request)

In new asset there should be a button like in new licence that allows you to create a new manufacture

#### Actual Behavior

You have to exit and go to settings manufacture to create

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running  v4.4.1 build 3636 (gece916e12)
- Version of PHP you're running 

5.6.35
--

- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Manufacturers are at the asset model level, not the asset itself.

**Comment by rjs5327** [comment]
I understand. Lets go through a exercise.
With a brand new setup
Go to Create New - Asset
click new button by model
Click manufacture there is no manufactures and no way to create one right there. 

No lets take a fieldtrip.
Click new accesory
look beside manufacture there is a button called new which enters a new manufacture record into the Db. 

That is what should be in the new asset dialog. 

Also that is true that it is in the asset model but there is a hold up in process flow compared to the accessory method. Both are referencing the same manufacture table in the database i would assume there is a ID and that is tied to the info that is tied to the model that is tied to the asset.

**Comment by rjs5327** [comment]
Correction new model dialog  i see where the confusion is

**Comment by snipe** [comment]
Right, but when you create the asset model and need to create a manufacturer, that would trigger a second modal window from he existing asset model modal window, which is kinda gross.

**Comment by F3d0s** [comment]
This issue is still relevant, it has been reported 4 years ago...
