### ISSUE TITLE
Accessory checkout while checking out assets

### ISSUE THREAD

**Issue by nickmacwiz** [snipe/snipe-it#578]
Can the Accessories be checkout while on the asset checkout page? This would be a great addition!!
##

**Comment by snipe** [comment]
Can you describe what you mean? I'm not following.

**Comment by nickmacwiz** [comment]
![screenshot 2015-02-28 15 42 56](https://cloud.githubusercontent.com/assets/11078660/6428722/8070601c-bf60-11e4-8c0b-2d7aa7a3b12c.png)

On the page in the screen shot for checking out assets it would be nice if we could select as many accessories as needed to be checkout out with this asset. Does this make more sense?

**Comment by snipe** [comment]
I think I understand, yes.

(BTW, if you're running this in production, you can remove that bottom debugger by changing `'debug' => true;` to `'debug' => false;`in your `app/config/production/app.php`.)
