### ISSUE TITLE
Upgrade to latest DBAL Version for MariaDB Support

### ISSUE THREAD

**Issue by ocelotsloth** [snipe/snipe-it#5780]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.4.1
 - OS: Ubuntu 16.04
 - Web Server: Apache
 - PHP Version: 7.1.3

**Is your feature request related to a problem? Please describe.**
As noted in the release notes for the past several versions, the version of DBAL used does not support MariaDB 10.2+ and the community here was waiting for a pull request to be merged in. Because my environment uses this version of MariaDB, we have been unable to complete the latest update nor install the second instance we have needed for some time.

DBAL release version 2.7.0 on April 4th (followed by 2.7.1 on April 8th), which contains the patch referenced by the latest release of Snipe-IT.

**Describe the solution you'd like**
I'd like to see [DBAL v2.7.1](https://github.com/doctrine/dbal/releases/tag/v2.7.1) included in the next release.

**Comment by snipe** [comment]
Can you downgrade your version of MariaDB?

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by ocelotsloth** [comment]
Woah there! This is absolutely still an issue regardless of if I can downgrade or not.

As it happens, I cannot downgrade MariaDB in my environment, which is why we need the update to DBAL included in a future release. Please reopen this issue.

**Comment by snipe** [comment]
It might still be an issue, but there's not a lot *I* can do about it. They didn't release it as a bug fix, and the next version requires PHP7, so my hands are tied until we release v5.

**Comment by ocelotsloth** [comment]
I get that...heh I also don't understand why they didn't backport that bugfix...

It just doesn't make sense to close the issue. There isn't anything on the release documentation acknowledging the current status of the problem, so having the only issue addressing it marked closed doesn't really send the right message to anybody looking for a solution.

**Comment by snipe** [comment]
If they're looking for a solution, hopefully they'll find this ticket if they did a search in the issues. The upgraded version has been on the [experimental PHP7/Laravel 5.6 branch](https://github.com/snipe/snipe-it/blob/fuuuuuu/5_0-php7required/composer.json) for several months, so once we're ready to move forward with that (which should be soon), it will be merged in.

**Comment by snipe** [comment]
(I also don't understand why they didn't release it as a bugfix. It's screwed up a lot of people, and asking them all to upgrade to PHP7.1 to fix something they effectively broke seems kinda messed up.)

**Comment by ocelotsloth** [comment]
Fair enough. We'll probably just end up propping up a special, *hopefully-temporary*, database server for this until this is resolved.

Thanks for the attention!

**Comment by snipe** [comment]
It's a shit situation, and I'm sorry you have to resort to that. :(

**Comment by Majkl578** [comment]
> I also don't understand why they didn't release it as a bugfix.

Because it wasn't a bug fix, but a new feature.

> to fix something they effectively broke seems kinda messed up

Can you please elaborate what was _broken in DBAL_? The PR requested for backport is a new feature: support for new platform version of MariaDB, vendor that is well known for BC breaks even in patch versions.

> so my hands are tied until we release v5

Your package should not (or rather must not) restrict consumers from using newer semver-compliant versions of dependencies.
Right now, your package is locked at very old and unsupported DBAL 2.5.13. This is both a severe security risk (as locking at 2.5.13 would prevent installing eventual 2.5.14 in case security issue appeared) and an issue for your consumers, which this issue is a proof of.

This package should depend on `"doctrine/dbal": "^2.5.13"`.
