### ISSUE TITLE
Errors when running "php artisan migrate"

### ISSUE THREAD

**Issue by Tomasthanes** [snipe/snipe-it#5781]
#### Please confirm you have done the following before posting your bug report:

- [N/A ] I have enabled debug mode 
- [Yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I'm following the steps in the snipeit.sh shell script for RHEL 7.  When I get to the step that looks like:

  echo "* Artisan Migrate."
  log "php $APP_PATH/artisan migrate --force"

It fails with the errors that you can review in the attached screenshot.

**To Reproduce**

**Expected behavior**
I expected the "php artisan migrate" work work without any visible errors.

**Screenshots**
See attached screenshot.

**Server (please complete the following information):**
 - Snipe-IT Version 4.4.1
 - OS: [e.g. Ubuntu, CentOS] Oracle Linux Server release 7.5
 - Web Server: [e.g. Apache, IIS] httpd.x86_64 2.4.6-80.0.1.el7
 - PHP Version php.x86_64 7.1.19-1.ius.centos7 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? Fresh install
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh --> snipeit.sh
- Include what you've done so far in the installation, and if you got any error messages along the way. I did not get any other error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database. We haven't gotten this far.
![snipe-it artisan migration errors](https://user-images.githubusercontent.com/18180348/42341389-c32be9a2-8047-11e8-956f-f756658e58c7.PNG)

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by EarlRamirez** [comment]
@Tomasthanes based on the errors you do not have access to the DB.

**Comment by EarlRamirez** [comment]
@Tomasthanes are you able to access the DB with the credentials this is in the _.env_ file?
