### ISSUE TITLE
Licence Page show Object not found error 404

### ISSUE THREAD

**Issue by Arunryadav** [snipe/snipe-it#5783]
**Server (please complete the following information):**
 - Snipe-IT Version :- 4.4.2 
 - OS: [Windows 2012 R2]
 - Web Server: [e.g. Apache, xampp]
 - PHP Version :7.2.6 
I have configured yesterday Snipe-it,  When I click license Page  got below error please suggest me the solution.

Object not found!
The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error. 

If you think this is a server error, please contact the webmaster. 

Error 404
snipe.jmfonline.in
Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6

**Comment by snipe** [comment]
Are you using Apache with xampp? If so, you have to remove the built-in aliases. https://snipe-it.readme.io/docs/xampp#section-remove-built-in-aliases

**Comment by Arunryadav** [comment]
Thanks for  revert, We have remove  same from (httpd-xapmm.conf) After remove we are not able to start apache server getting below error.

[Thu Jul 05 16:08:14.842604 2018] [ssl:warn] [pid 4124:tid 400] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 05 16:08:14.936384 2018] [ssl:warn] [pid 4124:tid 400] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 05 16:08:15.936360 2018] [mpm_winnt:notice] [pid 4124:tid 400] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Thu Jul 05 16:08:15.936360 2018] [mpm_winnt:notice] [pid 4124:tid 400] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Thu Jul 05 16:08:15.936360 2018] [core:notice] [pid 4124:tid 400] AH00094: Command line: 'C:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Thu Jul 05 16:08:15.936360 2018] [mpm_winnt:notice] [pid 4124:tid 400] AH00418: Parent: Created child process 4892
[Thu Jul 05 16:08:16.498886 2018] [ssl:warn] [pid 4892:tid 400] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 05 16:08:16.592593 2018] [ssl:warn] [pid 4892:tid 400] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 05 16:08:16.670761 2018] [mpm_winnt:notice] [pid 4892:tid 400] AH00354: Child: Starting 150 worker threads.
[Thu Jul 05 16:11:59.622643 2018] [ssl:warn] [pid 3184:tid 480] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 05 16:11:59.700756 2018] [ssl:warn] [pid 3184:tid 480] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 05 16:11:59.778884 2018] [mpm_winnt:notice] [pid 3184:tid 480] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Thu Jul 05 16:11:59.778884 2018] [mpm_winnt:notice] [pid 3184:tid 480] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Thu Jul 05 16:11:59.778884 2018] [core:notice] [pid 3184:tid 480] AH00094: Command line: 'C:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Thu Jul 05 16:11:59.794505 2018] [mpm_winnt:notice] [pid 3184:tid 480] AH00418: Parent: Created child process 4768
[Thu Jul 05 16:12:00.388273 2018] [ssl:warn] [pid 4768:tid 400] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 05 16:12:00.482031 2018] [ssl:warn] [pid 4768:tid 400] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 05 16:12:00.544516 2018] [mpm_winnt:notice] [pid 4768:tid 400] AH00354: Child: Starting 150 worker threads.
[Thu Jul 05 17:03:20.322350 2018] [mpm_winnt:notice] [pid 3184:tid 480] AH00422: Parent: Received shutdown signal -- Shutting down the server.
[Thu Jul 05 17:03:22.353636 2018] [mpm_winnt:notice] [pid 4768:tid 400] AH00364: Child: All worker threads have exited.
[Thu Jul 05 17:03:22.400484 2018] [mpm_winnt:notice] [pid 3184:tid 480] AH00430: Parent: Child process 4768 exited successfully.
[Thu Jul 05 17:03:23.541121 2018] [ssl:warn] [pid 4836:tid 488] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 05 17:03:23.650480 2018] [ssl:warn] [pid 4836:tid 488] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 05 17:03:23.712977 2018] [mpm_winnt:notice] [pid 4836:tid 488] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 configured -- resuming normal operations
[Thu Jul 05 17:03:23.712977 2018] [mpm_winnt:notice] [pid 4836:tid 488] AH00456: Apache Lounge VC15 Server built: Mar 28 2018 12:12:41
[Thu Jul 05 17:03:23.712977 2018] [core:notice] [pid 4836:tid 488] AH00094: Command line: 'C:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Thu Jul 05 17:03:23.728607 2018] [mpm_winnt:notice] [pid 4836:tid 488] AH00418: Parent: Created child process 4932
[Thu Jul 05 17:03:24.306804 2018] [ssl:warn] [pid 4932:tid 400] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 05 17:03:24.400532 2018] [ssl:warn] [pid 4932:tid 400] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Thu Jul 05 17:03:24.478625 2018] [mpm_winnt:notice] [pid 4932:tid 400] AH00354: Child: Starting 150 worker threads.

**Comment by Arunryadav** [comment]
11:35:09 AM  [Apache] 	Error: Apache shutdown unexpectedly.
11:35:09 AM  [Apache] 	This may be due to a blocked port, missing dependencies, 
11:35:09 AM  [Apache] 	improper privileges, a crash, or a shutdown by another method.
11:35:09 AM  [Apache] 	Press the Logs button to view error logs and check
11:35:09 AM  [Apache] 	the Windows Event Viewer for more clues
11:35:09 AM  [Apache] 	If you need more help, copy and post this
11:35:09 AM  [Apache] 	entire log window on the forums

**Comment by Arunryadav** [comment]
Thanks A Lot its working fine now
