### ISSUE TITLE
old users not showing after upgrading

### ISSUE THREAD

**Issue by ctacay** [snipe/snipe-it#5788]
#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode 
- [ yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After upgrading my snipe from 4.1 to the latest; i cant see the OLD users when checking out an asset. it's only showing new button.

**Server (please complete the following information):**
 - Snipe-IT Version v4.4.1 build 3636 (gece916e12)
 - OS: [e.g. Ubuntu, CentOS] Windows 10
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.1.9

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari] chrome

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? -uograde
![v1](https://user-images.githubusercontent.com/32893706/42418391-b16a3f96-82b0-11e8-8905-a191d00e07e6.PNG)
![v2](https://user-images.githubusercontent.com/32893706/42418392-b1987028-82b0-11e8-83e3-36d9d1933bb2.PNG)

- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Please answer the additional questions in the issue template.
