### ISSUE TITLE
Accepting Assets

### ISSUE THREAD

**Issue by Vulfoliac** [snipe/snipe-it#579]
There is no way to tell if a user really did accept an asset, also once the asset was accepted they are still able  to accept if they click on the link again.

**Comment by snipe** [comment]
What do you mean? The acceptance shows up in the asset history.

![screen shot 2015-03-01 at 2 25 17 pm](https://cloud.githubusercontent.com/assets/197404/6433247/dd3bb440-c01e-11e4-93b0-dc1223ef372f.png)
