### ISSUE TITLE
3/3) QueryException  SQLSTATE[HY000] [2002] Permission denied (SQL: select * from information_schema.tables where table_schema = snipeit_data and table_name = users)

### ISSUE THREAD

**Issue by galbayer** [snipe/snipe-it#5792]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by EarlRamirez** [comment]
@galbayer it is highly recommended that you use _https://snipe-it.readme.io/docs/installation_ to install Snipe-IT.

There is a custom ISO that included Snipe-IT preinstalled, you can find it here --> https://github.com/EarlRamirez/snipeit_iso. 

Regarding your error, you may want to check if you can log in to the DB from the shell using the credentials that are supplied in the .env file.

**Comment by snipe** [comment]
Errors like that usually mean MySQL isn't running

**Comment by galbayer** [comment]
thank you all for helping out. I managed to install it again using the same work instructions.
i'm not very familiar with Linux Administration.

when I've tried to go over the instructions released in the snipe-it.readme.io some of the repositories wouldn't add to the machine and many packages are missing.


thanks again, the system is up and running :-)

**Comment by EarlRamirez** [comment]
@galbayer can you shed some details so that doc can be updated?
- Which repositories are you referring to?
- What packages are missing?

**Comment by galbayer** [comment]
I’ll have to re-deploy to be able to share it again.
I’ll do it next week
