### ISSUE TITLE
Multiple Field Sets against models

### ISSUE THREAD

**Issue by AndrewDRigg** [snipe/snipe-it#5794]
I am starting to configure Snipe and would like to confige generic field sets across models.
I am thinking Warranty, Location ie fields that require common data and apply these multiple  field sets to each model.

Warantary Field set containing
Start date
End Date
Warranty detail (24x7; 00:90-17:00 etc.

Alternatively the ability to amalgamate multiple field sets into a single field set could provide a similar capability.

This is my first enquiry

Hope I am making sense.

Thanks Andrew

**Comment by snipe** [comment]
Multiple fieldsets on an asset model are not currently possible, however fields may appear in multiple fieldsets, so you can create fieldsets that cover all of your use cases.
