### ISSUE TITLE
Case insensitive username

### ISSUE THREAD

**Issue by smksar** [snipe/snipe-it#5800]
Latest Snipe-IT 4.4.1

Currently login usernames are case sensitive and we set the usernames of our users to match their login IDs which are all uppercase but our systems nevertheless still allow the use of all lowercase as long it matches.

I would like to suggest in Security Settings page to have one more checkbox with title "Allow case insensitive username?" that would then allow usernames to be entered anyhow if selected.

Passwords of course remain case sensitive as Snipe-IT already doing.

Thanks a lot always~!

**Comment by snipe** [comment]
Usernames are already case insensitive, since mysql searches are case-insensitive.

**Comment by smksar** [comment]
Oh wow.. indeed it is.. I must have missed an update release notes before as I wasn't able to login by typing all lowercase username. 

**THANK YOUUUUU**

**Comment by snipe** [comment]
MySQL has always been case-insensitive, so Snipe-IT usernames have always been case-insensitive. Maybe you were trying to login with your email instead of your username before. It happens. :)
