### ISSUE TITLE
How can change the asset ID starts at 0

### ISSUE THREAD

**Issue by Jetranger** [snipe/snipe-it#5801]
When all assets are deleted, the imported assets continue to have the original ID, and how to reset the asset ID？not asset tag.

**Comment by snipe** [comment]
The asset ID isn't relevant to anything in the system that's human-visible, so there should never be a need to reset them. I'm not sure what you mean when you say "the imported assets continue to have the original ID". If they were deleted, how do they have IDs at all?

To reset the auto-incremented in MySQL, use `ALTER TABLE tablename AUTO_INCREMENT = 1` - however we [strongly caution against modifying the database directly](https://snipe-it.readme.io/docs/manually-editing-data).
