### ISSUE TITLE
Custom workstations management

### ISSUE THREAD

**Issue by dimton** [snipe/snipe-it#5803]
This isn't any bug or feature request. Just a simple questions to fellow admins who use SnipeIT in their daily job.

I use a simple naming schema for every workstation in our company, like PC001, PC002, PC003, etc. Well, some of these workstations are branded PCs whereas most of them are custom builds.

I want some ideas on how to document this kind of workstations on SnipeIT. Since there is no particular Asset Model, I am not sure how to proceed with this.

Can you please make your suggestions or your own practices you implement in your environment?

Thanks

**Comment by EarlRamirez** [comment]
@dimton I use custom fields and custom field set to overcome this, you can create a model for your custom built workstations and associate the custom fields with this model(s). You can find details about custom fields here --> _https://snipe-it.readme.io/docs/custom-fields_

**Comment by cslucian** [comment]
i did a similar thing too
Create Manufacturer > "Custom Build"
Create Model > "Custom Desktop"
Create Custom field that we can use them on any type of desktop/laptop such as: Cpu/GPU/Ram/Storage info
![capture](https://user-images.githubusercontent.com/879352/42616545-6cf952ca-85b7-11e8-9935-6c5d9afe092a.PNG)

**Comment by dimton** [comment]
Thank you both, @EarlRamirez and @cslucian, for sharing this with me. I will create a Custom Build model and associate it with a custom fieldset.
