### ISSUE TITLE
Import - Bug: Snipe-it always creats new Model Name's

### ISSUE THREAD

**Issue by p-mac90** [snipe/snipe-it#5805]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When I import assets via an .cvs file, snipe-it creates always a new Model Name. Dispite the Model Name in the .cvs file is the same as the Model Name that I created in snipe-it. So when I import all my +2000 assets I will have thousand different Model Names. My goal is to have as few different Model Name's  as possible.

I know that snipe-it create a new Model Name if it doesn't exist, but the Model Name's are the same.  

**Expected behavior**
Actual snipe-it should assign the asset to the already existing Model Name, not create a new one. 

**Server (please complete the following information):**
 - Snipe-IT Version: v4.1.6-pre build 2963 (g83c8449)
 - OS: Ubuntu 18.02
 - PHP Version: 7.0.22-0ubuntu0.16.04.1

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.12
 - Browser Chrome
 - Version  62.0.3202.94

**Error Messages**
There are no error messages

**Comment by EarlRamirez** [comment]
@p-mac90 I am not 100% certain that this is a bug, I saw this in the past and a new model was created because the cases (upper/lower) were different. Verify that the names are exactly the same.

**Comment by katiCore** [comment]
same Problem here @p-mac90

**Comment by EarlRamirez** [comment]
@katiCore or @p-mac90 share the header and one of the models that are being changed, will like to confirm if it is indeed a bug or not.

**Comment by p-mac90** [comment]
Hi @EarlRamirez, 

I have the solution. When you import new Model's you have to set the Field "Model Number" even if it's not required. If you set the Model Number, Snipe-IT assigned your imported Model's to the existing Model's.

**Comment by dmeltzer** [comment]
Hi,

This sounds like a bug.  Nonexistent model numbers should be considered the same.  Will try to take a look
