### ISSUE TITLE
No authorization needed to create/edit/delete companies, depreciations, reports, custom fields and custom fieldsets

### ISSUE THREAD

**Issue by tilldeeke** [snipe/snipe-it#5806]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
There are no authorization checks for creating/editing/deleting companies, depreciations, reports, custom fields and custom fieldsets via the UI.

**To Reproduce**
1. Create user that does not have the permission to create a company
2. Login with that user
3. Go to /companies/create
4. Fill out the form & send it
5. A new company is created. 

The user themself can't see the new company directly since the table loads from the api, which checks for the correct authorization. Any user with the "companies.view" permission can see the new company.

**Expected behavior**
You get a 403 HTTP Error at step 3, saying you are not allowed to access this route.

**Server (please complete the following information):**
 - Snipe-IT Version: v4.5.0 - build 3701 (master)
 - OS: Ubuntu
 - Web Server: nginx
 - PHP Version: 7.2-fpm

**Additional context**
- Is this a fresh install or an upgrade? : **Fresh install.**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)? **git pull**
- Include what you've done so far in the installation, and if you got any error messages along the way. **Only created the user.**

**Comment by snipe** [comment]
This is on develop now
