### ISSUE TITLE
Sublocation / Bins

### ISSUE THREAD

**Issue by nathanmcguire** [snipe/snipe-it#5808]
**Server (please complete the following information):**
 - Snipe-IT Version 4.4.2
 - OS: Ubuntu 16.04
 - Web Server: Apache
 - PHP Version 7.0.30-0ubuntu0.16.04.1

**Is your feature request related to a problem? Please describe.**
I'm frustrated that locations functionality is fairly flat. I know you can assign parent locations and thus have child locations. This seems like it is more geared toward building locations instead of the room within the building or the rack/bin/shelf within the room. 

**Describe the solution you'd like**
I would like a location entity to have a list of minor locations associated with it. 
Upon checkout/checkin I would like to be able to pick a major location and a minor location.

**Describe alternatives you've considered**
1. Creating a location for each minor location. This will create a very lengthy list of locations to pick from.
2. Creating a list of general rules of where things should be and posting in storage closet.

**Additional context**
I'm envisioning the current location entity type to be equivalent to buildings.
Buildings contain Rooms.
Rooms of type storage contain Racks/Bins/Shelfs.

**Comment by snipe** [comment]
> I would like a location entity to have a list of minor locations associated with it.

I don't really understand the use case here. If you've created your location and publications, why is this is necessary? What even is a minor location?

**Comment by nathanmcguire** [comment]
Do you consider places inside a storage closet like shelves or bins to be locations? If there is a closet full of small assets sitting on shelving units or in bins, I think it would be nice to know what shelf or bin the asset was filed to when it was checked in: something more defined than a note but won't make the locations list lengthy.

Minor locations(places inside rooms) is necessary to shorten the location list. 

Having minor locations(shelves or bins) would keep each shelve or bin from being listed in the locations list, but would allow a selection from a second list(of shelves or bins) that would be populated once the location (room) was selected.

**Comment by snipe** [comment]
Locations are locations. It’s up to you to decide what’s a major or minor location. We have plenty of users who narrow their locations down to literal shelves, and plenty that don’t, but I don’t see us building in major/minor locations into the core.

**Comment by nathanmcguire** [comment]
Thanks.
