### ISSUE TITLE
The import of licenses is not proceeding! I want to show error on import if you will import a same serial number on licenses

### ISSUE THREAD

**Issue by markwizer** [snipe/snipe-it#5809]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**
Error will acquire, Serial number already taken.

**Screenshots**
![issue](https://user-images.githubusercontent.com/40789706/42558001-906e4246-8522-11e8-88bb-de5793df1e83.PNG)
Not redirecting or anything it's just stock there

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS] Windows 8.1 Pro
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 5.6.4

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? upgrade
- What OS and web server you're running Snipe-IT on localhost
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
If it's stuck there, then something else is wrong. Please complete the rest of the questions in the issue template so that we can try to help you.
