### ISSUE TITLE
Feature request: Use "Search by Asset Tag" to search by Serial Number

### ISSUE THREAD

**Issue by PascalTr** [snipe/snipe-it#5812]
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
With the new SnipeIT Version 4.5.0 you can enable that the serial number needs to be unique.
Would it be possible to add an option in the settings menu so that I can change the Search Bar in the top from "Search by Asset Tag" to "Search by Serial" because in our company we use the Serial-Number as a unique identifier. So thanks for implementing this btw. It really helps alot.

**Describe alternatives you've considered**
Maybe add the normal search bar that you have on the "All assets" page up there too. 
Not to replace the other one but this would be much quicker. And maybe add an option to not save the previous search result when using this search bar.

**Additional context**

**Comment by snipe** [comment]
That top search is meant to be used with a barcode scanner, that's why it only accepts asset tags. More explanation can be found here: #3216

**Comment by PascalTr** [comment]
Thanks for your answer.
I do understand that it wasn't possbile at this time because the serial wasn't unique.
But with v4.5.0 you've added the option to enable the serial as a unique identifier so for my understanding the before mentioned problem doens't exists anymore if this option is enabled (except the archived assets but the don't have to be shown when you search through the top bar search).

If this could be implemented it should just be enabled when you have enabled this option in the settings.

**Comment by towntronic** [comment]
Hi. Any progress on this?
I understand the top search bar is specifically meant to be used with a barcode scanner.
The company I work for do not use the barcode scanner feature/function.
Maybe a setting to move the search bar thats in All Assets page to be moved to the top bar and even disabling the barcode scanner search bar?

**Comment by ghost** [comment]
Hi there @snipe ,

I understand that the top search is meant to be used with a barcode scanner. However, all of our assets have S/N barcodes on them (either from the manufacturer or from ourselves), and we would rather not use additional asset tags.

Given that it has been requested by numerous people, this is a fairly common scenario, and it is frankly shocking that it is not supported. I don't think anyone needs the ability to search both S/N and asset tags, so the mentioned "fringe cases where one asset's asset tag is the same as another asset's serial" (in #3216) would not be an issue.

The lack of this feature is, unfortunately, a showstopper for my org. :(

**Comment by DHNS** [comment]
I also think this is an essential feature. More often than not I have equipment with no asset number that I need to lookup by serial. I actually prefer tracking by serial because it is built into a device at manufacture, cannot be changed, cannot be lost or removed, is almost always unique, and can be read by software/scripts/agents over the network.

Not being able to search for serial numbers is a showstopper for me as well.

**Comment by Prodeguerriero** [comment]
I realize this has been stale for a while now, but I want to add my opinion on the matter.
We currently have roughly ~1000 assets, most of which have been tracked via their S/N until the moment we switched to Snipe-IT. We are now in the process of migrating to using asset tags, but the majority of our assets still need to be looked up using the old identifier.

A way to enable the search field to _also_ look at the serial number (or have a quick way to switch the field's scope on the fly) would be practical.

**Comment by cstout1** [comment]
It would be a great use of the prominent search field to be able to choose which field it is searching. Could potentially even be a user preference. I know I'd be thrilled as someone who does not use asset tags and _only_ searches serial numbers.
