### ISSUE TITLE
Custom user name generation

### ISSUE THREAD

**Issue by NiklasNord** [snipe/snipe-it#5814]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.1.9-pre - build 3117
 - OS: Unknown
 - Web Server: Unknown
 - PHP Version: Unknown

**Is your feature request related to a problem? Please describe.**
When setting up Snipe-IT for a larger organization, potentially 1500+ users and 2000+ assets, without LDAP, the need for an agile user import is needed. Especially user name generation to avoid errors and duplicates. This becomes very evident when trying to separate staff and students in K-12 schools.

**Describe the solution you'd like**
More options to choose for automatic user name creation using numbers as complement to letters.
For example 'XXXxxx000'
XXX - first three letters in first name
xxx - first three letters in last name
000 - consecutive number changed from 001 to 002, 003, 004 etc when duplicates of XXXxxx are found

Options to set a prefix on user names to (in my case) separate students from staff.
For example adding the letter 'e' and a '.' befor the user name. 'e.XXXxxx000' for students. (e is the first letter in the swedish word 'elev' which means student)

**Describe alternatives you've considered**
The current options is not safe from duplicate user names.

**Comment by snipe** [comment]
Hi - while this isn't a bad suggestion, it would be pretty messy to arbitrarily implement. It's probably easier for you to generate those in your Excel files using a formula and export those usernames directly.
