### ISSUE TITLE
Users not getting emailed

### ISSUE THREAD

**Issue by Arsenal10108** [snipe/snipe-it#5816]
#### Expected Behavior (or desired behavior if a feature request)
Users are not getting an email when an asset is checked out/Check in for them
-----

#### Actual Behavior

No email is sent, I could just be missing something to get them to send. The "test email" function works perfectly. I am using gmail and followed the config steps for gmail. 

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh Install
- Version of Snipe-IT you're running 4.4.2
- Version of PHP you're running Whatever is the latest version
- Version of MySQL/MariaDB you're running Latest version that is part of install
- What OS and web server you're running Snipe-IT on Ubuntu server 16.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by Arsenal10108** [comment]
I am stupid, I found it :)

**Comment by Arsenal10108** [comment]
Just kidding, I found where it says email users when this asset category is checked in or out but it still didn't go. I am kind of a noob with this so I am sure I am missing something. This is a fresh out of the  box install using composer on Ubuntu 16.04

**Comment by Arsenal10108** [comment]
Do I need to do anything with Cron? i founf the "self hosters may need to configure cron to ping the scheduler every minute but i figured that was for the backup/EOL etc alerts
 I just want to email the user when I check out an asset to them.

**Comment by Arsenal10108** [comment]
That was the Key, I had not filled in the EULA. As soon as I populated Something in there and went to check out an asset it now say "this user will be email a copy of the EULA" Awesome, I knew it was something easy. I didn't ready anywhere where it said that the EULA was required, maybe I missed it.

**Comment by 5quirrel** [comment]
I don't think it's documented and/or a bug

**Comment by brianhoganm** [comment]
I missed this one too! Thank goodness I found this. I spent several hours on this.  I forgot to place a check mark for the category. AND...I love the fact that I can choose which category to send emails!  LOVE THIS @snipe
