### ISSUE TITLE
Upgrade.php Permission Denied

### ISSUE THREAD

**Issue by BHollowell** [snipe/snipe-it#5817]
#### Expected Behavior (or desired behavior if a feature request)

upgrade.php should perform an automatic upgrade

-----

#### Actual Behavior

upgrade.php returns multiple permission denied errors, states that it completes the upgrade, but the footer version doesn't change.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install, first time trying to upgrade

- Version of Snipe-IT you're running
Current 4.1.4, updating to 4.5.0

- Version of PHP you're running
PHP 5.6 currently, but planning to upgrade to 7.x soon.

- Version of MySQL/MariaDB you're running
 MySQL 5.6.39

- What OS and web server you're running Snipe-IT on
CentOS 7

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Git intall.sh

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
N/A

- If a stacktrace is provided in the error, include that too.
N/A

- Any errors that appear in your browser's error console.
N/A

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
N/A

- Include any additional information you can find in `storage/logs` and your webserver's logs.
N/A

- Include what you've done so far in the installation, and if you got any error messages along the way.
N/A

- Indicate whether or not you've manually edited any data directly in the database
Yes, I've manually edited checked out data for assets during my initial data import since there is no bulk checkout to location in the current version I am running.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by BHollowell** [comment]
Here's the command line output for upgrade.php

`[snipe_user@sbdc-netinv01 html]$ php upgrade.php
PHP Notice:  Undefined offset: 1 in /var/www/html/upgrade.php on line 16
Welcome to the Snipe-IT upgrader.

Please note that this script will not download the latest Snipe-IT
files for you unless you have git installed.
It simply runs the standard composer and artisan
commands needed to finalize the upgrade after.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! If you have any encrypted custom fields, BE SURE TO run the recrypter if upgrading from v3 to v4.
!! See the Snipe-IT documentation for help:
!! https://snipe-it.readme.io/docs/upgrading-to-v4
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--------------------------------------------------------
STEP 1: Backing up database:
--------------------------------------------------------

-- Starting backup...
Dumping database snipeit...
Backup failed because The dump process failed with exitcode 1 : General error : sh: /var/www/html/storage/laravel-backups/temp//snipeit.sql: No such file or directory
.
Backup failed because: The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied.

In StreamHandler.php line 107:

  The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied




--------------------------------------------------------
STEP 2: Putting application into maintenance mode:
--------------------------------------------------------

--
In StreamHandler.php line 107:

  The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied




--------------------------------------------------------
STEP 3: Pulling latest from Git (master branch):
--------------------------------------------------------

Git is installed.
fatal: Unable to create '/var/www/html/.git/index.lock': Permission denied
fatal: Unable to create '/var/www/html/.git/index.lock': Permission denied
Cannot save the current index state
error: cannot open .git/FETCH_HEAD: Permission denied

-- -- -- --------------------------------------------------------
Step 4: Cleaning up old cached files:
--------------------------------------------------------

-- No bootstrap/cache/compiled.php, so nothing to delete.
-- Deleting bootstrap/cache/services.php. It it no longer used.
-- No bootstrap/cache/config.php, so nothing to delete.
-- Configuration cache cleared!
-- Cache cleared successfully.
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
Step 5: Updating composer dependencies:
(This may take an moment.)
--------------------------------------------------------

-- Local composer.phar detected, so we'll use that.

Generating optimized autoload files


  [ErrorException]
  file_put_contents(/var/www/html/vendor/composer/autoload_namespaces.php): failed to open stream: Permission denied


dump-autoload [--no-scripts] [-o|--optimize] [-a|--classmap-authoritative] [--apcu] [--no-dev]

Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 0 installs, 0 updates, 33 removals
  - Removing symfony/yaml (v3.4.4)


  [RuntimeException]
  Could not delete /var/www/html/vendor/symfony/yaml/.gitignore: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_s
  et() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your tim
  ezone.


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...





--------------------------------------------------------
Step 6: Migrating database:
--------------------------------------------------------

-- Migrating: 2016_06_01_000001_create_oauth_auth_codes_table
Migrated:  2016_06_01_000001_create_oauth_auth_codes_table
Migrating: 2016_06_01_000002_create_oauth_access_tokens_table
Migrated:  2016_06_01_000002_create_oauth_access_tokens_table
Migrating: 2016_06_01_000003_create_oauth_refresh_tokens_table
Migrated:  2016_06_01_000003_create_oauth_refresh_tokens_table
Migrating: 2016_06_01_000004_create_oauth_clients_table
Migrated:  2016_06_01_000004_create_oauth_clients_table
Migrating: 2016_06_01_000005_create_oauth_personal_access_clients_table
Migrated:  2016_06_01_000005_create_oauth_personal_access_clients_table


--------------------------------------------------------
Step 7: Checking for OAuth keys:
--------------------------------------------------------

- OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 8: Caching routes and config:
--------------------------------------------------------

-- Configuration cache cleared!

In StreamHandler.php line 107:

  The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied


-- Route cache cleared!

In StreamHandler.php line 107:

  The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied



--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is now live.


--------------------------------------------------------
FINISHED! Clear your browser cookies and re-login to use :
your upgraded Snipe-IT.
--------------------------------------------------------
`

**Comment by BHollowell** [comment]
Here's the command line output for upgrade.php

```
[snipe_user@sbdc-netinv01 html]$ php upgrade.php
PHP Notice:  Undefined offset: 1 in /var/www/html/upgrade.php on line 16
Welcome to the Snipe-IT upgrader.

Please note that this script will not download the latest Snipe-IT
files for you unless you have git installed.
It simply runs the standard composer and artisan
commands needed to finalize the upgrade after.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! If you have any encrypted custom fields, BE SURE TO run the recrypter if upgrading from v3 to v4.
!! See the Snipe-IT documentation for help:
!! https://snipe-it.readme.io/docs/upgrading-to-v4
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
--------------------------------------------------------
STEP 1: Backing up database:
--------------------------------------------------------

-- Starting backup...
Dumping database snipeit...
Backup failed because The dump process failed with exitcode 1 : General error : sh: /var/www/html/storage/laravel-backups/temp//snipeit.sql: No such file or directory
.
Backup failed because: The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied.

In StreamHandler.php line 107:

  The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied




--------------------------------------------------------
STEP 2: Putting application into maintenance mode:
--------------------------------------------------------

--
In StreamHandler.php line 107:

  The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied




--------------------------------------------------------
STEP 3: Pulling latest from Git (master branch):
--------------------------------------------------------

Git is installed.
fatal: Unable to create '/var/www/html/.git/index.lock': Permission denied
fatal: Unable to create '/var/www/html/.git/index.lock': Permission denied
Cannot save the current index state
error: cannot open .git/FETCH_HEAD: Permission denied

-- -- -- --------------------------------------------------------
Step 4: Cleaning up old cached files:
--------------------------------------------------------

-- No bootstrap/cache/compiled.php, so nothing to delete.
-- Deleting bootstrap/cache/services.php. It it no longer used.
-- No bootstrap/cache/config.php, so nothing to delete.
-- Configuration cache cleared!
-- Cache cleared successfully.
-- Route cache cleared!
-- Compiled views cleared!

--------------------------------------------------------
Step 5: Updating composer dependencies:
(This may take an moment.)
--------------------------------------------------------

-- Local composer.phar detected, so we'll use that.

Generating optimized autoload files


  [ErrorException]
  file_put_contents(/var/www/html/vendor/composer/autoload_namespaces.php): failed to open stream: Permission denied


dump-autoload [--no-scripts] [-o|--optimize] [-a|--classmap-authoritative] [--apcu] [--no-dev]

Loading composer repositories with package information
Installing dependencies from lock file
Package operations: 0 installs, 0 updates, 33 removals
  - Removing symfony/yaml (v3.4.4)


  [RuntimeException]
  Could not delete /var/www/html/vendor/symfony/yaml/.gitignore: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_s
  et() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your tim
  ezone.


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...





--------------------------------------------------------
Step 6: Migrating database:
--------------------------------------------------------

-- Migrating: 2016_06_01_000001_create_oauth_auth_codes_table
Migrated:  2016_06_01_000001_create_oauth_auth_codes_table
Migrating: 2016_06_01_000002_create_oauth_access_tokens_table
Migrated:  2016_06_01_000002_create_oauth_access_tokens_table
Migrating: 2016_06_01_000003_create_oauth_refresh_tokens_table
Migrated:  2016_06_01_000003_create_oauth_refresh_tokens_table
Migrating: 2016_06_01_000004_create_oauth_clients_table
Migrated:  2016_06_01_000004_create_oauth_clients_table
Migrating: 2016_06_01_000005_create_oauth_personal_access_clients_table
Migrated:  2016_06_01_000005_create_oauth_personal_access_clients_table


--------------------------------------------------------
Step 7: Checking for OAuth keys:
--------------------------------------------------------

- OAuth keys detected. Skipping passport install.

--------------------------------------------------------
Step 8: Caching routes and config:
--------------------------------------------------------

-- Configuration cache cleared!

In StreamHandler.php line 107:

  The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied


-- Route cache cleared!

In StreamHandler.php line 107:

  The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied



--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

-- Application is now live.


--------------------------------------------------------
FINISHED! Clear your browser cookies and re-login to use :
your upgraded Snipe-IT.
--------------------------------------------------------
```

**Comment by EarlRamirez** [comment]
@BHollowell  what is the output of ls -la from the snipeit directory? Which account did you use to perform the upgrade?

**Comment by BHollowell** [comment]
Here's the output. I'm running the upgrade from my user account called "snipe_user" (Pretty generic, I know...), and that user is a member of the apache group.

```
[snipe_user@servername  html]$ ls -la
total 2332
drwxr-xr-x. 16 apache apache    4096 Mar  6 13:33 .
drwxr-xr-x.  4 root   root        33 Mar  1 17:14 ..
-rw-r--r--.  1 apache apache   23501 Mar  1 17:15 .all-contributorsrc
drwxr-xr-x. 17 apache apache     251 Mar  1 17:15 app
-rw-r--r--.  1 apache apache    1646 Mar  1 17:15 artisan
drwxr-xr-x.  3 apache apache      54 Mar  1 17:15 bootstrap
-rw-r--r--.  1 apache apache     875 Mar  1 17:15 bower.json
-rw-r--r--.  1 apache apache    9210 Mar  1 17:15 c3.php
-rw-r--r--.  1 apache apache     373 Mar  1 17:15 codeception.yml
-rw-r--r--.  1 apache apache    3228 Mar  1 17:15 CODE_OF_CONDUCT.md
-rw-r--r--.  1 apache apache    2336 Mar  1 17:15 composer.json
-rw-r--r--.  1 apache apache  256861 Mar  1 17:15 composer.lock
-rwxr-xr-x.  1 apache apache 1861877 Mar  6 13:25 composer.phar
drwxr-xr-x.  2 apache apache    4096 Mar  1 17:15 config
-rw-r--r--.  1 apache apache     317 Mar  1 17:15 CONTRIBUTING.md
-rw-r--r--.  1 apache apache      90 Mar  1 17:15 crowdin.yml
drwxr-xr-x.  5 apache apache      72 Mar  1 17:15 database
drwxr-xr-x.  2 apache apache     132 Mar  1 17:15 docker
-rw-r--r--.  1 apache apache     667 Mar  1 17:15 docker.env
-rw-r--r--.  1 apache apache    2898 Mar  1 17:15 Dockerfile
-rw-r--r--.  1 apache apache      67 Mar  1 17:15 .dockerignore
-rw-r--r--.  1 apache apache    2860 Apr  5 09:44 .env
-rw-r--r--.  1 apache apache    2748 Mar  1 17:15 .env.example
-rw-r--r--.  1 apache apache    1826 Mar  1 17:15 .env.testing
-rw-r--r--.  1 apache apache    1755 Mar  1 17:15 .env.testing-ci
-rw-r--r--.  1 apache apache     536 Mar  1 17:15 .env.tests
-rw-r--r--.  1 apache apache     491 Mar  1 17:15 .env.unit-tests
-rw-r--r--.  1 apache apache    1711 Mar  1 17:15 gh-changelog.php
drwxr-xr-x.  8 apache apache     163 Mar  1 17:15 .git
-rwxr-xr-x.  1 apache apache      11 Mar  1 17:15 .gitattributes
drwxr-xr-x.  2 apache apache      91 Mar  1 17:15 .github
-rwxr-xr-x.  1 apache apache    1061 Mar  1 17:15 .gitignore
-rw-r--r--.  1 apache apache     251 Mar  1 17:15 .htaccess
-rw-r--r--.  1 apache apache     956 Mar  1 17:15 index.html
-rwxr-xr-x.  1 apache apache     371 Mar  1 17:15 install.sh
-rwxr-xr-x.  1 apache apache   34519 Mar  1 17:15 LICENSE
-rw-r--r--.  1 apache apache    1713 Mar  1 17:15 package.json
-rw-r--r--.  1 apache apache    1097 Mar  1 17:15 phpunit.xml
drwxr-xr-x.  8 apache apache     198 Mar  1 17:15 public
-rw-r--r--.  1 apache apache   27388 Mar  1 17:15 README.md
drwxr-xr-x.  6 apache apache      59 Mar  1 17:15 resources
drwxr-xr-x.  3 apache apache      66 Mar  1 17:15 routes
drwxr-xr-x.  2 apache apache     132 Mar  1 17:15 sample_csvs
-rw-r--r--.  1 apache apache     567 Mar  1 17:15 server.php
-rw-r--r--.  1 apache apache   24622 Mar  1 17:15 snipeit.sh
drwxr-xr-x.  8 apache apache     157 Mar 13 17:09 storage
drwxr-xr-x. 10 apache apache    4096 Mar  1 17:15 tests
-rw-r--r--.  1 apache apache    2827 Mar  1 17:15 .travis.yml
-rw-r--r--.  1 apache apache    6111 Mar  1 17:15 upgrade.php
drwxr-xr-x. 63 apache apache    4096 Mar  6 14:02 vendor
-rw-r--r--.  1 apache apache    2133 Mar  1 17:15 webpack.mix.js
[snipe_user@servername html]$
```

**Comment by EarlRamirez** [comment]
the files are all owned by apache; therefore, using snipe_user will not work, try _sudo -u apache php upgrade.php_

**Comment by EarlRamirez** [comment]
Forget to mention, even though _snipe_user_ is a member of the apache group, it will also fail because the apache group only has read access

**Comment by BHollowell** [comment]
Hey, look at that! Silly things...

Would you recommend changing the perms from 755 to 775 so I can use the snipe_user account to run this upgrade natively, or would it make more sense to chown these to snipe_user:snipe_user?

**Comment by EarlRamirez** [comment]
chmod -R 775 <snipeit> directory will work

**Comment by BHollowell** [comment]
Just to be clear, should I run this on the root directory? In my case that's just the default /var/www/html directory for apache, but I want to make sure the recursive flag won't interfere with any of the special perms I had to set for the public and other directories during the initial installation.

**Comment by EarlRamirez** [comment]
Running it from the root directory will be the easiest, then you can modify the permissions on storage/ and public/

**Comment by EarlRamirez** [comment]
@BHollowell will be closing the ticket as the reported issue was resolved
