### ISSUE TITLE
[Feature Request] Require -either- asset tag or serial number

### ISSUE THREAD

**Issue by BHollowell** [snipe/snipe-it#5819]
**Server (please complete the following information):**
 - Snipe-IT Version 4.1.4
 - OS: CentOS 7
 - Web Server: Apache
 - PHP Version 5.6

**Is your feature request related to a problem? Please describe.**

My company does not assign asset tag values to our equipment, we track everything based on serial number. Snipe requires an asset tag value, but not serial number. Currently our not so terrible workaround is to insert the serial number in both fields.

**Describe the solution you'd like**

It would be nice if there was a toggle in the settings that could switch the primary attribute between asset tag and serial number as the tracking option of choice,

**Describe alternatives you've considered**

The alternative for us would be to continue adding the serial number value in both fields.

**Additional context**

**Comment by snipe** [comment]
It’s unlikely we could implement that, as required asset tags are an underlying assumption in a lot of our business logic. What I would do instead is turn on the required serial number option, and also turn on auto-incrementing asset tags so that they’re generated for you.

**Comment by BHollowell** [comment]
@snipe Thanks for the reply! I complete understand the situation with asset tags being required. I also appreciate the alternative, but I think we'll probably just continue to add the value in both locations.

Thanks!
