### ISSUE TITLE
History information

### ISSUE THREAD

**Issue by smksar** [snipe/snipe-it#5822]
Current v4.5.0

When viewing the history for an item, let's use location as specific example 
![image](https://user-images.githubusercontent.com/38576928/42615373-88702bb2-85dc-11e8-964a-323d30352231.png)
It shows as ID instead of name, which can be overwhelming when trying to figure out what is the location name for ID 21 and what was 22?

Would like to suggest either:
1. Shows up as name; or if not possible or too long
2. To pop up when hovering on the IDs using CSS tooltip
![image](https://user-images.githubusercontent.com/38576928/42615493-144db5aa-85dd-11e8-84a8-60882644d8d2.png)

Thank you as always for the great effort and continuous updates!!

**Comment by snipe** [comment]
That's always been on the roadmap.

**Comment by viclou** [comment]
+1 33980
