### ISSUE TITLE
Listing assets pagination bug

### ISSUE THREAD

**Issue by tamasberesoebb** [snipe/snipe-it#5823]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

Reloading the asset list with fewer items when the user is not on the first page, loads an empty page with no pagination (buttons are missing).

**To Reproduce**

1. Have many (100+) assets
2. Open all assets
3. Go to page 2
4. Go to an other view, where there are only a few results (<30)
5. Page is empty
6. Go to all assets
7. Go to page 1
8. Go to an other view, where there are only a few results (<30)
9. Assets are loaded

**Expected behavior**

Pagination should switch back to page 1 on reloading of the list.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
Version v4.4.2 - build 3666 (master)

 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**
Windows, Mac
Chrome
Version 67.0.3396.99

**Comment by sargentjay** [comment]
I am experiencing the same issue with Version v4.6.2 - build 3844 (master) in both chrome Version 64.0.3282.167 and Internet Explorer 11.0.9600.
It is as if the Pagination is keeping its previous selection.
I have not had a chance to look if this is server-side caching or client side yet. 

Here is a short gif showing what is happening. 
![Snipe-IT_2018-07-25_12-10-10.gif](https://github.com/sargentjay/JaysOpenSourceHelper/blob/master/Snipe-IT/Snipe-IT_2018-07-25_12-10-10.gif?raw=true)

**Comment by snipe** [comment]
I can'r reproduce this locally - can you reproduce it on the demo?

**Comment by sargentjay** [comment]
Yeah, looks like it does the same for me on the demo too. 

I do see that it does seem to work right when selecting a label that has more than one page. But if you have only one page of a certain label, it does not display anything in the table.

**Comment by tamasberesoebb** [comment]
It is still relevant.

**Comment by mmorais-idealsumario** [comment]
This issue is still present, both in master and develop branches to this date. It is reproducible in the demo site by e.g. going to Licenses page (which has currently 8.215 records), clicking "Next" all the way to the last page, and then Assets > List All (which has just 16 total). The result is an empty list with no pagination buttons.

**Comment by tamasberesoebb** [comment]
this issue is still relevant, and is annoying the heck out of our team on a daily basis.
