### ISSUE TITLE
Docker hub build is failing 

### ISSUE THREAD

**Issue by duel007** [snipe/snipe-it#5824]
Hello,

The docker hub build for v.4.5.0 is failing. Could you take a look? Thanks!

https://hub.docker.com/r/snipe/snipe-it/

**Comment by EarlRamirez** [comment]
@duel007 any errors?

**Comment by duel007** [comment]
@EarlRamirez This is where the build is failing: https://travis-ci.org/snipe/snipe-it

Not much I can do about it, this is all on the maintainers

**Comment by snipe** [comment]
Thanks for the heads up - this has been fixed. 
<img width="817" alt="screen shot 2018-07-12 at 2 34 50 pm" src="https://user-images.githubusercontent.com/197404/42660691-cc58678c-85e0-11e8-8738-7cddcd6a4715.png">
