### ISSUE TITLE
Cron Task for importing Users VIA CSV

### ISSUE THREAD

**Issue by Arsenal10108** [snipe/snipe-it#5827]
I Deleted most of the other stuff as this isn't so much of a bug as it is a Help Me (if its even possible)

The way Our Current LDAP structure is set up is not really conducive to importing with LDAP as we have a bunch of service accounts that get imported and get assigned the complete wrong location if there is no Search OU defined in the location settings. 

I can really get Granular with it with a CSV file though. I can auto generate the CSV file and even get it into the server automatically but I was wondering if it was possible to schedule a daily cron job to grab that CSV and import it? We have students coming and going all the time. 

Some Info for you
Snipe-IT Version 4.4.2
Ubuntu server 16.04 LTS
PHP 7
Installed using composer

**Comment by snipe** [comment]
@Arsenal10108 in the future, please select the feature request template and fill in the info there, as this would be a new feature.

Importing via CSV cron isn't currently possible, but you might want to consider using the API to import things. 

>  I can auto generate the CSV file and even get it into the server automatically 

If you can do all that already, the far easier solution would be to hit the API in that script/process and insert there.

**Comment by Arsenal10108** [comment]
Sorry about that! I wasn't sure if it was possible yet so I didn't know where to put it. 
I am not familiar with coding at all, Could you help walk me through that? To give you an example of how ignorant I am I had to google what API stands for haha!

**Comment by dmeltzer** [comment]
Depending on the format, you should be able to use `php artisan snipeit:import` to import the csv in a cron, there's a (poorly documented) way of passing custom field mappings if necessary

**Comment by Arsenal10108** [comment]
Thanks! am I missing some place to find this info? All I am able to locate is the user manual which has some info but not super technical. 
I am not looking to deviate from the standard CSV, I can only think of one reason to use a custom field but it isnt a tie breaker. I would like to just get it working first and then I can tweak it haha.

**Comment by Arsenal10108** [comment]
![image](https://user-images.githubusercontent.com/41116612/43075077-7e6be466-8e4d-11e8-88c2-349f63f2dd05.png)

So I tried that, The Importing assets and more portion of the user manual has info on importing assets and stuff but not users, I tried just adding item type of users but it didn't like it. Should I just try it without an item type?

**Comment by dmeltzer** [comment]
Try --item-type user (sorry, it should be more robust--the CLI importer doesn't get used often enough to track these things down.

Also, make sure you're using 4.6.2... there's been a number of updates to the user importer in the last few days to match more fields.

The following field names should work, it's what we use in the test.

```
First Name,Last Name,email,Username,Location,Phone Number,Job Title,Employee Number,Company
```

**Comment by Arsenal10108** [comment]
I will update as I am still on 4.4.2.
That format is exactly how I have my csv set up. :)

I tried to change it just user and it says it was done successfully however there is a user in the CSV file that is not in the database :0 So I am not sure that it actually went successfully.  But let me update first and I'll give it another try. 

Also, does it matter if the Job Title, Employee Number and Company fields are blank or do they all have to have something in them?

**Comment by dmeltzer** [comment]
permissions probably got weird.... you'll want to chown -R the files as your-user:www-data

**Comment by Arsenal10108** [comment]
Hmmmm....  chown /var/www/snipeit ad_admin:www-data let it go through but now it says whoops somehting went wrong. 

Looks like the upgrade went fine.. I don't know where to start on this one. 
I tried clearing cache and even a new browers and its still broke

Sorry to take this totally off topic. Should I start a new thread?

**Comment by Arsenal10108** [comment]
Sorry this is what i actually typed. 
![image](https://user-images.githubusercontent.com/41116612/43078919-c5cbba0a-8e59-11e8-825b-ae98791c06b4.png)

**Comment by Arsenal10108** [comment]
Figured out the update thing... However the importer is acting the same as it did before. It quickly responds back with imported successfully but one of the users that is in the CSV has not actually been imported.
