### ISSUE TITLE
Trying to get property of non-object snip-it - New Install

### ISSUE THREAD

**Issue by TOA-OSS** [snipe/snipe-it#583]
Hi there....

Your software looks, great hopefully we can start using it soon!

I have managed to install it fully with demo SQL data

See attached image, this is a install with PHP 5.5.13/MySQL 5.6.19 on Windows Server 2012 R2

Is it just the case I'm using MySQL instead of MariaDB?

![capture](https://cloud.githubusercontent.com/assets/7711546/6440643/08eecc68-c0d7-11e4-8553-d558ef7f53f7.PNG)

Many Thanks

**Comment by madd15** [comment]
There should be no issue in running MYSQL. Can you confirm all files are correct and that all installation commands completed successfully? Also which version of snipe-it are you using?

**Comment by TOA-OSS** [comment]
Thanks for the reply. I am using version 1.2.6. I have followed all the instructions, I have set the configuration in all the folders (Local, Production, Staging, Testing) And even tried giving IUSR full permissions to the whole of SnipeIT's IIS folder.

**Comment by madd15** [comment]
Could you please check that the settings table has data in it

**Comment by TOA-OSS** [comment]
Hi Madd15

It does seem the settings table has no data in it. I tried your query in PHPMyAdmin but nothing seems to happen (Selected the database called Assets, called query, pasted in the code and clicked submit query.)  Nothing new seems to be in the settings table

Thanks for your help

**Comment by snipe** [comment]
Is there an error when you submit that query in phpMyAdmin?

**Comment by TOA-OSS** [comment]
umm, very weird, the script worked through MySQL Management this time :)
