### ISSUE TITLE
empty list in assets page if non superadmin.

### ISSUE THREAD

**Issue by meisaputra** [snipe/snipe-it#5830]
i have Snipe-IT v4.5.0 build 3701 (gbf1e742df) on PHP Version 5.6.36 and Laravel Version 5.4.35. application installed using softaculous in cpanel.
please fix it and let me know by mention me. thank you.

#### Please confirm you have done the following before posting your bug report:

- [  ] I have enabled debug mode 
- [v] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
bug found is empty list in assets page whereas there are records in database.

**To Reproduce**
1. Go to installed 'snipe-it'
2. Click on 'assets > list all'
3. Scroll to 'content' area
4. See error, empty list.

**Expected behavior**
all asets listed.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v4.5.0 build 3701 (gbf1e742df)
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version 5.6.36

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome
 - Version 67.0.3396.99 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
`error cannot reproduce in demo`
- Include any additional information you can find in `storage/logs` and your webserver's logs.
`Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dh_dh_assets.company_id' in 'where clause' (SQL: select count(*) as aggregate from dh_assets inner join dh_status_labels as dh_status_alias on dh_status_alias.id = dh_assets.status_id and dh_status_alias.archived = 0 where dh_dh_assets.company_id = 1 and dh_assets.deleted_at is null)' in /vendor/laravel/framework/src/Illuminate/Database/Connection.php:647`

**Additional context**
- Is this a fresh install or an upgrade? 
`fresh install from softaculous in cpanel`
- What OS and web server you're running Snipe-IT on
`apache on ubuntu`
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
`via softaculous`
- Include what you've done so far in the installation, and if you got any error messages along the way.
`no, just follow the instruction on screen`
- Indicate whether or not you've manually edited any data directly in the database
`no`
- Add any other context about the problem here.
`empty list occurs when non superadmin go to assets > list all. but if change a user permission to supper admin, he can view the list. ` 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
You have to run migrations.

**Comment by meisaputra** [comment]
ok, i'll try to find how to do it in shared hosting...

**Comment by snipe** [comment]
This seems like it might be a bug on softaculous' side. They should have run `php artisan migrate` in whatever script they built to upgrade their own users. If you have SSH access, you can just SSH into the shared host, cd to the main snipeit directory and then run `php artisan migrate`.

**Comment by snipe** [comment]
(They unfortunately don't include us in any of that process, so they sometimes break things and we have no real way of knowing what they might have forgotten to do.)

**Comment by meisaputra** [comment]
while waiting response from hosting support, i look detail into error log, there is error in writing table prefix. but i don't know where the code located.

**Comment by snipe** [comment]
> there is error in writing table prefix

I'm not sure what you mean here

**Comment by meisaputra** [comment]
refer to ** or bold part in code... there is double table prefix.

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dh_dh_assets.company_id' in 'where clause' (SQL: select count(*) as aggregate from dh_assets inner join dh_status_labels as dh_status_alias on dh_status_alias.id = dh_assets.status_id and dh_status_alias.archived = 0 where **dh_**dh_assets.company_id = 1 and dh_assets.deleted_at is null)' in /vendor/laravel/framework/src/Illuminate/Database/Connection.php:647

**Comment by snipe** [comment]
When you look at your .env file in your project root, what does it say for table prefix?

**Comment by meisaputra** [comment]
in my .env written
DB_PREFIX=dh_
but, look at string **where dh_dh_assets.company_id** in laravel.log there is 2 table prefixes.

`Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'dh_dh_assets.company_id' in 'where clause' (SQL: select count(*) as aggregate from dh_assets inner join dh_status_labels as dh_status_alias on dh_status_alias.id = dh_assets.status_id and dh_status_alias.archived = 0 where dh_dh_assets.company_id = 1 and dh_assets.deleted_at is null)' in /vendor/laravel/framework/src/Illuminate/Database/Connection.php:647`

**Comment by meisaputra** [comment]
why only in `dh_dh_assets.company_id = 1` the prefix written 2 times, while the other tables in not?

**Comment by snipe** [comment]
I don't have any idea why the prefix is there twice. There's nothing in the code that should cause that.

**Comment by TrueBurn** [comment]
I have the same issue.
Version v4.6.6 - build 3926 (master)
OS: Ubuntu
Web Server: Apache

I ran "sudo php artisan migrate" but still have the issue.

[12:36:45] LOG.error: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sn_sn_assets.company_id' in 'where clause' in /var/www/snipeit/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:77
Stack trace:

I installed using install.sh

**Comment by user-4711** [comment]
hello,

is this now the official solution? Will this be merged with the master?
We also run into this error and don't wanna "hack" around in the sourcecode...
