### ISSUE TITLE
Company name should be fixed in Asset

### ISSUE THREAD

**Issue by patelriya5736** [snipe/snipe-it#5831]
How can i fixed company name when i create new asset?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by snipe** [comment]
I don't understand what you mean.

**Comment by patelriya5736** [comment]
when i create asset for single company i need company name is fixed in textbox I dont need select view.
how can i change it to text box with fixed value?

**Comment by patelriya5736** [comment]
Is it possible??
if possible then plzz help...
Thank you .

**Comment by snipe** [comment]
It is not currently possible, that's why it's labeled a feature request.

**Comment by patelriya5736** [comment]
Thank You.
