### ISSUE TITLE
We need to setup a new environment Snipe-it application with IIS and SQL server   

### ISSUE THREAD

**Issue by Arunryadav** [snipe/snipe-it#5832]
We need to setup a new environment Snipe-it application with IIS and SQL server , Please provide me installation document for the same

**Comment by snipe** [comment]
Snipe-IT does not work with SQL Server, [only with MySQL and MariaDB](https://snipe-it.readme.io/docs/requirements). The installation manual is [here](https://snipe-it.readme.io/docs/installation).
