### ISSUE TITLE
Convert from Linux to Windows

### ISSUE THREAD

**Issue by Nu2SnipeIT** [snipe/snipe-it#5835]
First, I apologize if this is not posted correctly.  I'm new to posting questions in forums like this.

The document at https://snipe-it.readme.io/docs/getting-help  says "Please do not email for installation support."  If this is not where I get assistance with this, can you please advise me where I can find help?

My Issue:
My predecessor setup Snipe-IT on a Ubuntu Linux (64-bit) VM and has now left the company.  No one here knows anything about Linux and there are no plans to use it in the future.  So, I'm trying to figure out if we can convert our Linux based Snipe-IT over to Windows.  If possible, my intention is to spin up a new VM running Windows Server 2012 R2, install Snipe-IT, then bring all our data over by the most efficient means possible.

I found the post https://github.com/snipe/snipe-it/issues/4343 entitled , How to Install Snipe IT in Windows using Git and WAMP #4343.  (Just wondering if it's accurate and up to date for the latest version of Snipe-IT.)  I followed the link in it to https://snipe-it.readme.io/docs/wamp.  Unfortunately, it doesn't appear to address bringing data over from an existing Linux installation.

I've also looked through https://snipe-it.readme.io/v4.5.0/docs but can't tell if the conversion I need to do is possible or what the proper steps would be.

Here's all my info, I think...

#### Provide answers to these questions:
- Is this a fresh install or an upgrade? 
Not sure, maybe both.  I'd like to do a fresh install of the latest Windows version but may need to install a version compatible with our current Linux version, get our data imported, the upgrade the Windows version.

- Version of Snipe-IT you're running
v3.6.3  build 15 (g1bf34d7)

- Version of PHP you're running
PHP Version | 7.0.15-0ubuntu0.16.04.4
Laravel Version | 5.2.45

- Version of MySQL/MariaDB you're running
10.1.21-MariaDB-1~xenial

- What OS and web server you're running Snipe-IT on
Guest OS:  Ubuntu Linux (64-bit) running on Appache

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Pretty sure it was a manual install.  Doesn't seem to match up with documentation.

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
N/A

- If a stacktrace is provided in the error, include that too.
N/A

- Any errors that appear in your browser's error console.
N/A

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
N/A

- Include any additional information you can find in `storage/logs` and your webserver's logs.
N/A

- Include what you've done so far in the installation, and if you got any error messages along the way.
N/A

- Indicate whether or not you've manually edited any data directly in the database
I have not.  Anyone before me?  Unknown.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

Any help/advise/links you can provide will be very much appreciated.  Thanks in advance!

-Noob

**Comment by samotelf** [comment]
Why don't you spin a CentOS VM and install Snipe using the install script?
I'm a noob too and I was able to do that, besides you learn a few things. I can give you directions if you want. Or, you can follow [this guide](https://www.reddit.com/r/sysadmin/comments/71qh4z/snipeit_installation/) that I found when I was searching for a install tutorial.
Best of luck.

**Comment by EarlRamirez** [comment]
@samotelf don't think he will one that option either, for newbies to Linux there was a custom CentOS created which includes Snipe-IT. Kickstart is used to automate OS installation and a few others scripts to complete the post-installation and it can be found here --> _https://github.com/EarlRamirez/snipeit_iso_ 

@Nu2SnipeIT maybe I can provide you with some guidance to transfer your data from Ubuntu to Server 2012.
- Provision your Server 2012
- Install WAMP _https://snipe-it.readme.io/docs/wamp_
- Acquire the APP key from the .env file
- Acquire the most recent backup
- Replace the Windows server APP key with the one from the Ubuntu server 
- Extract the backup and import the .sql file into your windows MySQL (_mysql db_name < backup-file.sql_)

Let me know if this helps

**Comment by samotelf** [comment]
That's awesome! Kudos 👍

**Comment by snipe** [comment]
@Nu2SnipeIT - you'll need to run the backup at Admin > Backups. That will back up your database and any uploaded files. Then when you have a fresh install on your Windows machine, import the old database over the new one, copy over any uploaded files that are in the backup zip and copy the .env file over. (You may need to update the database credentials there though.)

**Comment by Nu2SnipeIT** [comment]
Thanks for all the advice.  I got called off the Snipe conversion for a few days but hope to be back to it by next week.  Sounds like EarlRamirez and Snipe are on the same page I am.  This is a Windows shop so I want to convert to Windows based Snipe rather than CentOS.  Thanks though, samotelf.

Earl, will I be able to run both the Linux and Windows versions side by side until I'm sure everything transferred over properly?  I've never installed WAMP before and I'm not familiar with the APP key you're referring to.  Sounds like maybe I'll only be able to run one instance at a time?

**Comment by snipe** [comment]
@Nu2SnipeIT there's no reason why you can't run two instances at the same time, but do be careful if anyone's adding any data to it - if they input data on the old one, after you've already dumped the database to the new one, that data could be lost (since you already grabbed the old data).

The APP_KEY will be in your .env file, in the document root. https://snipe-it.readme.io/docs/configuration

**Comment by snipe** [comment]
We actually have documentation on moving Snipe-IT to a new server here: https://snipe-it.readme.io/docs/moving-snipe-it

**Comment by Nu2SnipeIT** [comment]
Thanks, snipe, I saw that documentation earlier.  Being unfamiliar with the .env file mentioned, databases in general, phpMyAdmin, MySQL and MariaDB, I couldn't tell if it addressed a migration from Linux to Windows or if it is only for use between like operating systems.

I've tried running the Generate Backup under Admin > Backups a few times and while it says it completed successfully, even after a refresh it doesn't show any file(s).  I have no idea where to find /var/www/snipeit/storage/app/backups to see if there's anything there.

**Comment by Nu2SnipeIT** [comment]
Finally getting back to this but making zero progress.  The documentation mentions a .env file which I can't find.  It mentions running Admin > Backups which reports successful but shows no file being created.  The following is copied from my screen:

Success: A new backup file was successfully created.
Backup files are located in: /var/www/snipeit/storage/app/backups

I navigated to the backups folder and ran ls -al and get the following.  I don't understand this output.  "total 12"??  12 what?  I see what looks like 3 entries.  Whatever the case, I just ran the backup and I see nothing with today's date.

total 12
drwxr-xr-x 2 www-data www-data 4096 Feb 17  2017 .
drwxr-xr-x 3 www-data www-data 4096 Feb 17  2017 ..
-rwxr-xr-x 1 www-data www-data   13 Feb 17  2017 .gitignore
xxxxxxx@xxxxxx:/var/www/snipeit/storage/app/backups$

Since I can't seem to make any progress deciphering the existing installation or how to back it up, update it or transfer it, I thought I'd approach it from another angle.... spin up a new VM and start from scratch.  My boss has to actually spin up the VM and his first question is "what are the spec?".  I pull up what I think are the instructions, https://snipe-it.readme.io/docs/server-configuration, but there is nothing about the VM requirements!

I am totally frustrated with this but my boss still wants me to figure it out.  I don't know Linux and have to Google every single command.  Can someone please provide me step by step instructions?  I need our Linux SnipeIT running on Windows Server 2012 R2.  I have zero information about how it was originally installed.

(banging-head-on-wall)

**Comment by EarlRamirez** [comment]
@Nu2SnipeIT will you be available on the weekend, maybe we can meet on gitter.im to resolve the issue. Additionally, there are no requirements for the VM that I am aware off, Snipe-IT can run on a Raspberry Pi. It truly depends on your requirements.

There is also a hosted solution that you can use _https://snipeitapp.com/pricing_

**Comment by Nu2SnipeIT** [comment]
Update:  well, I found my .env file in  /var/www/snipeit/.env
I created a folder in my login directory called MDP and tried to copy the file there - Permission denied.  Below is the command I found Googling it, what am I doing wrong??

xxxxxx@xxxxxx:/var/www/snipeit$ cp .env MDP

**Comment by Nu2SnipeIT** [comment]
Thanks for the offer, Earl.  Unfortunately, I'll be out of town this weekend.  Any other times good for you?  I'll do my best to make myself available.  I'm the CST zone and can be available in the evening if that helps.

**Comment by EarlRamirez** [comment]
I'm currently on EDT, maybe, we can try at 17:45 time and hash it out for an hour or so, you have the Windows server up already, you are using WAMP or IIS.

**Comment by Nu2SnipeIT** [comment]
4:45 CST today?  I can do that.  I'm told IIS.

**Comment by Nu2SnipeIT** [comment]
Earl, I'm signed into gitter.im and will be the rest of the day.  I'm told I "should" have a new VM to work with by 4:30 CST but it's not guaranteed.

**Comment by EarlRamirez** [comment]
I'm here

**Comment by Nu2SnipeIT** [comment]
Earl, I got your msg that you're on gitter but I guess I don't know how to start the chat session.  I don't see you and don't see how to search for people.

**Comment by Nu2SnipeIT** [comment]
@EarlRamirez I think I figured out gitter and started a private conversation.  Waiting....
BTW - Thanks for the help!!!
