### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by jmartins1** [snipe/snipe-it#5836]
1. When marking a user as Active = No, under People (people management tab), the user should also not be available to have items checked out to them under check-out/user.

2. An options to block certain users from being pulled during sync using LDAP would be great. I have test accounts and vendor accounts that do not need to be imported during sync.

3.  You should not be able to mark a user as Active = No, under People (people management tab), if an item is still assigned to them.

Thanks for the hard work guys. Love your platform.

**Comment by snipe** [comment]
@jmartins1 the active flag just disables their login. If you want a user to not show up in the list you should delete them.
