### ISSUE TITLE
Easy Self Extracting SNIPE-IT installer

### ISSUE THREAD

**Issue by jrtoman** [snipe/snipe-it#585]
I put a request into bitnami to get snipe-it entered into there monthly contest to make an easy to install application, but requires people to vote on it. I wasn't sure where to post the link do i will post it here. All you need to do is vote it appears.  Here's the link https://bitnami.com/stack/snipe-it

**Comment by jrtoman** [comment]
Official Link:

https://bitnami.com/contest?utm_source=bitnami&utm_medium=badge&utm_term=snipe-it&utm_campaign=Application%2BContest&product=snipe-it#voted

**Comment by snipe** [comment]
It keeps telling me I already voted when I didn't :(

**Comment by jrtoman** [comment]
Weird I see we are up to 6 votes, but as to why it says you already voted I am unsure. Perhaps you can drop the an email?

**Comment by jrtoman** [comment]
Just a note you can recast your vote once every month which in turn will help us get more votes!
