### ISSUE TITLE
Could not bind to LDAP: Can't contact LDAP server

### ISSUE THREAD

**Issue by batchn00b** [snipe/snipe-it#5850]
I have a freshly installed Debian stretch Server with only SnipeIT running on it

im trying to set up the LDAP connect but im getting the same error: Could not bind to LDAP: Can't contact LDAP server

DNS Server is reachable and i can resolve the name. Ports are also reachable (636)
In the LDAP Server field i have tried to put in the IP Adress of both Domain Controller and the DNS Name of each of them. It didnt work with any of it.

I have an icinga running on another machine and the LPAP connect works there without any issues. 

How to fix this?

I have seen this issue couple of times in the board but i havent found any solution

![image](https://user-images.githubusercontent.com/38785247/42746283-63890db6-88d7-11e8-9544-bd919a8cdc4f.png)

**Comment by EarlRamirez** [comment]
I used the domain name when I configured it, when I am back at my computer I will try and share my configuration with you.

**Comment by batchn00b** [comment]
Okay you are right.  BUT i had to save first before the Test worked. Thats kinda stupid. Thanks anyways

**Comment by EarlRamirez** [comment]
I don't see why you see this as *stupid* for me it makes perfect sense, the information is being entered in to a HTML form, therefore, the only way for the system to know about the changes is to save/commit/apply. Seems like you sort of want to create an account, e.g. Amazon, Google and want it to work without even submitting the changes.

Hope this helps clarify things and why this is not _kinda stupid_ 

Glad that it worked for you, by the way.

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
