### ISSUE TITLE
Asset model image upload error: 404 not found

### ISSUE THREAD

**Issue by tcintura** [snipe/snipe-it#5852]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**
Get image uploaded
**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT 4.4.2
 - CentOS 7
 - Web Server: nginx]
 - PHP Version 7

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [chrome]
 - Version [67.0]

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, I only see a blank page I cannot even login.

**Additional context**
- Is this a fresh install or an upgrade? Is a fresh one.
- What OS and web server you're running Snipe-IT on?  **CentOs 7** & Nginx **(LEMP)**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) I used **git clone**
- Include what you've done so far in the installation, and if you got any error messages along the way. No, I did not get any error.
- Indicate whether or not you've manually edited any data directly in the database. No I did not do any

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

Good day all,

Please help me!!
Im using LEMP Centos7+php7.0.3 + mariadb+ nginx. I have installed snipeit4.4.2 and I cannot upload asset model image but for companies and manufactures it works.

Find below print screen:
![snipeerror](https://user-images.githubusercontent.com/41233767/42755218-9a088efa-88f7-11e8-82ec-a8e1a4dc93d9.PNG)

Thanks in advance.

**Comment by EarlRamirez** [comment]
Can you enable debugging and share the logs with us, was this a clean install? The more information you provide the better we will able to assist you. Therefore, it will be highly appreciated if you can complete the questions in the form

**Comment by tcintura** [comment]
Yes it is a clean installation.

**Comment by EarlRamirez** [comment]
Are you able to provide any sort of los, Nginx is complaining that the path does not exists

**Comment by tcintura** [comment]
Yes it is. See below:
![error](https://user-images.githubusercontent.com/41233767/42772004-4f9550f6-8929-11e8-8996-6a1ee56d244d.PNG)

**Comment by snipe** [comment]
That's showing permission denied errors. Is your `public/uploads` directory and all subdirectories writable?

**Comment by EarlRamirez** [comment]
By default CentOS uses SELinux enabled and it will block php-fpm, try temporarily setting SELinux to permissive mode _sudo setenforce 0_ and see how it goes, you are seeing the same behaviour you may have missconfigure Nginx or php-fpm, also ensure that it php-fpm is running

**Comment by tcintura** [comment]
Thanks everybody, I solved the problem. I changed the owner of files to nginx.
