### ISSUE TITLE
Selecting "DataMatrix" always outputs QR Codes

### ISSUE THREAD

**Issue by frapposelli** [snipe/snipe-it#5853]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

Very similar to what happened in #2797, if I select `DATAMATRIX` as 2D code, I still get QRCodes

**To Reproduce**
1. Go to 'Admin/Barcodes'
2. Click on 'Display Square Codes'
3. Select "DATAMATRIX" as "2D Barcode Type"
3. Generate label
4. See QR code instead of Datamatrix

**Expected behavior**
Get a Datamatrix label

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

No Error

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.

It is reproducible in demo

**Additional context**
- Is this a fresh install or an upgrade? 

Fresh install, git cloned.

**Comment by snipe** [comment]
Did you clear out the barcodes directory to remove the already-generated barcode files?

**Comment by frapposelli** [comment]
Yep, public/uploads/barcodes is empty.

**Comment by frapposelli** [comment]
The problem apparently fixed itself after adding a new asset and regenerating all the labels.
