### ISSUE TITLE
Bulk Audit feature request

### ISSUE THREAD

**Issue by CraigBoucher** [snipe/snipe-it#5854]
**Server (please complete the following information):**
 - Snipe-IT Version v4.4.2 - build 3666 (master)
 - OS: Ubuntu 16.04.4
 - Web Server: Nginx
 - PHP Version 7.0

**Is your feature request related to a problem? Please describe.**
The issue I'm having is with the way the Bulk Audit feature currently works. There are two issues: 1) It would be better for us if the Location field was first and able to be scanned in one click (as opposed to clicking once to highlight the Location field and then either begin typing or scan barcode). And 2) setting the Location in the Audit does not change it in the database. So, in order to set the new locations found during the course of the audit, you would have to run the Audit Report and then manually go through the list and fix the Locations.

**Describe the solution you'd like**
Here is how we would like the Bulk Audit feature to work: the Location field field should be first on the list and we would scan Location barcode tags to set this field. Once the Location is set, we would then scan in all the Asset Tag barcodes for each asset that exists in that particular location. Also, once the Location is updated during the course of the Audit, it should be updated in the database as well without any further action.

**Describe alternatives you've considered**
We are looking into replacing our current Asset Management system and Snipe-IT is almost there. We would be willing to go the hosted route or pay for Pro Support if these two issues were resolved. My boss and I like the way Snipe-IT works for the most part. We are looking at a couple different commercial systems like Wasp and EZ Office Inventory, but would rather go with Snipe-IT if we could just get these two issues fixed.

**Additional context**

**Comment by snipe** [comment]
>  It would be better for us if the Location field was first and able to be scanned in one click (as opposed to clicking once to highlight the Location field and then either begin typing or scan barcode)

Exactly how would it be scanned? The scanner is meant to be used with assets.

> And 2) setting the Location in the Audit does not change it in the database.

That is intended behavior at this point. Actually physically moving an asset needs a more formal process, permissions, etc than editing.

**Comment by memtech3** [comment]
in tipweb-IT you are given the option at the end of an audit to move (or "collect") an item to the location it was scanned at during the audit.

**Comment by memtech3** [comment]
Also, you can see what hasn't been audited

**Comment by rkantos** [comment]
QuaggaJS should work for this issue too, only for 2D codes. For 2D code support I recommend adding support for an android application called "Barcode & QR code Keyboard", which has amazing performance (even compared to proprietary SDK from Scandit). It also supports REST requests, so it should be trivial to implement it with PHP. It could be used in multiple scenarios, especially when checking out/in multiple assets with barcodes!

Performance demo for "Barcode & QR code Keyboard" (please disregard the music and see the barcode scanning performance, which is unbelieavable in my opnion) https://www.youtube.com/watch?v=yhrV255hBW0
Performance for Scandit (which probably has licensing costs of thousands per device): https://www.youtube.com/watch?v=xe0NuLFC9_o
I also recommend everyone to test QuaggaJS demo (please try it with a camera enabled device or smartphone) , which also has great performance, while only being 1D -code capable: https://serratus.github.io/quaggaJS/examples/live_w_locator.html

**Comment by hesske** [comment]
Moving an asset during the audit to the location it is scanned at when it is scanned at that location is a feature we would like to see as well.
