### ISSUE TITLE
Check In, Check out Whoops error related to migrations

### ISSUE THREAD

**Issue by wesleytb13** [snipe/snipe-it#5856]
#### Expected Behavior (or desired behavior if a feature request)

Check In/Check out Items without an error. 

-----

#### Actual Behavior

I get a Whoops every time we check something in or out and it's not putting a Check In entry in the history of items showing where it was checked in - even though it is marking the items as checked in. 

I did some searching for possible fixes and saw where this was related to possibly needing to do a migration and I tried to do a migration and am getting errors when trying to do that. This is where I am getting lost in trying to fix the issue. Not sure how to proceed with the error being given. I found another issue with a similar error and it had something to do with the migration tables not updating properly and the fix was to Insert an entry in the migration table but I didn't want to try that without having someone look at what I am getting first. 
-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? It was an upgrade
- Version of Snipe-IT you're running - Version v4.4.1 - build 3636 (master)
- Version of PHP you're running - PHP 7.2.6
- Version of MySQL/MariaDB you're running - MySQL 5.7.19
- What OS and web server you're running Snipe-IT on - Server 2016/WAMP
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - originally just a manual installation but we converted to a git install a long way back
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

(3/3) QueryExceptionSQLSTATE[42S22]: Column not found: 1054 Unknown column 'checkin_counter' in 'field list' (SQL: update `assets` set `checkin_counter` = `checkin_counter` + 1, `updated_at` = 2018-07-16 13:50:35 where `id` = 993 and `assets`.`deleted_at` is null)
--
in Connection.php (line 647)
at Connection->runQueryCallback('update `assets` set `checkin_counter` = `checkin_counter` + 1, `updated_at` = ? where `id` = ? and `assets`.`deleted_at` is null', array('2018-07-16 13:50:35', 993), object(Closure))in Connection.php (line 607)
at Connection->run('update `assets` set `checkin_counter` = `checkin_counter` + 1, `updated_at` = ? where `id` = ? and `assets`.`deleted_at` is null',array('2018-07-16 13:50:35', 993), object(Closure))in Connection.php (line 477)
at Connection->affectingStatement('update `assets` set `checkin_counter` = `checkin_counter` + 1, `updated_at` = ? where `id` = ? and `assets`.`deleted_at` is null', array('2018-07-16 13:50:35', 993))in Connection.php (line 416)
at Connection->update('update `assets` set `checkin_counter` = `checkin_counter` + 1, `updated_at` = ? where `id` = ? and `assets`.`deleted_at` is null',array('2018-07-16 13:50:35', 993))in Builder.php (line 2147)
at Builder->update(array('checkin_counter' => object(Expression), 'updated_at' => '2018-07-16 13:50:35'))in Builder.php (line 2185)
at Builder->increment('checkin_counter', 1, array('updated_at' => '2018-07-16 13:50:35'))in Builder.php (line 773)
at Builder->increment('checkin_counter', 1, array())in Model.php (line 428)
at Model->incrementOrDecrement('checkin_counter', 1, array(), 'increment')in Model.php (line 391)
at Model->increment('checkin_counter', 1)in Loggable.php (line 131)
at Asset->logCheckin(object(User), '')in AssetsController.php (line 585)
at AssetsController->postCheckin(object(AssetCheckinRequest), '993', null)
at call_user_func_array(array(object(AssetsController), 'postCheckin'), array(object(AssetCheckinRequest), 'assetId' => '993', null))in Controller.php (line 55)
at Controller->callAction('postCheckin', array(object(AssetCheckinRequest), 'assetId' => '993', null))in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(AssetsController), 'postCheckin')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 572)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php (line 43)
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php (line 49)
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php (line 49)
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php (line 42)
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 574)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 533)
at Router->dispatchToRoute(object(Request))in Router.php (line 511)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php (line 51)
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php (line 25)
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php (line 56)
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php (line 27)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - https://ourdomain//hardware/993 and clicking the Action Drop down and choosing CheckIn Asset
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
This log file made the body of the message way too long to allow it to be posted. I can provide parts of it if that will help however it might not be needed given the issue seems to be with the migration table I think.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - i have not done this yet

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by wesleytb13** [comment]
- I am also including my migration table as it seemed to be the key in fixing this problem for another user: 
+-----+--------------------------------------------------------------------------+-------+
| id  | migration                                                                | batch |
+-----+--------------------------------------------------------------------------+-------+
|   1 | 2012_12_06_225921_migration_cartalyst_sentry_install_users               |     1 |
|   2 | 2012_12_06_225929_migration_cartalyst_sentry_install_groups              |     1 |
|   3 | 2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot  |     1 |
|   4 | 2012_12_06_225988_migration_cartalyst_sentry_install_throttle            |     1 |
|   5 | 2013_03_23_193214_update_users_table                                     |     1 |
|   6 | 2013_11_13_075318_create_models_table                                    |     1 |
|   7 | 2013_11_13_075335_create_categories_table                                |     1 |
|   8 | 2013_11_13_075347_create_manufacturers_table                             |     1 |
|   9 | 2013_11_15_015858_add_user_id_to_categories                              |     1 |
|  10 | 2013_11_15_112701_add_user_id_to_manufacturers                           |     1 |
|  11 | 2013_11_15_190327_create_assets_table                                    |     1 |
|  12 | 2013_11_15_190357_create_licenses_table                                  |     1 |
|  13 | 2013_11_15_201848_add_license_name_to_licenses                           |     1 |
|  14 | 2013_11_16_040323_create_depreciations_table                             |     1 |
|  15 | 2013_11_16_042851_add_depreciation_id_to_models                          |     1 |
|  16 | 2013_11_16_084923_add_user_id_to_models                                  |     1 |
|  17 | 2013_11_16_103258_create_locations_table                                 |     1 |
|  18 | 2013_11_16_103336_add_location_id_to_assets                              |     1 |
|  19 | 2013_11_16_103407_add_checkedout_to_to_assets                            |     1 |
|  20 | 2013_11_16_103425_create_history_table                                   |     1 |
|  21 | 2013_11_17_054359_drop_licenses_table                                    |     1 |
|  22 | 2013_11_17_054526_add_physical_to_assets                                 |     1 |
|  23 | 2013_11_17_055126_create_settings_table                                  |     1 |
|  24 | 2013_11_17_062634_add_license_to_assets                                  |     1 |
|  25 | 2013_11_18_134332_add_contacts_to_users                                  |     1 |
|  26 | 2013_11_18_142847_add_info_to_locations                                  |     1 |
|  27 | 2013_11_18_152942_remove_location_id_from_asset                          |     1 |
|  28 | 2013_11_18_164423_set_nullvalues_for_user                                |     1 |
|  29 | 2013_11_19_013337_create_asset_logs_table                                |     1 |
|  30 | 2013_11_19_061409_edit_added_on_asset_logs_table                         |     1 |
|  31 | 2013_11_19_062250_edit_location_id_asset_logs_table                      |     1 |
|  32 | 2013_11_20_055822_add_soft_delete_on_assets                              |     1 |
|  33 | 2013_11_20_121404_add_soft_delete_on_locations                           |     1 |
|  34 | 2013_11_20_123137_add_soft_delete_on_manufacturers                       |     1 |
|  35 | 2013_11_20_123725_add_soft_delete_on_categories                          |     1 |
|  36 | 2013_11_20_130248_create_status_labels                                   |     1 |
|  37 | 2013_11_20_130830_add_status_id_on_assets_table                          |     1 |
|  38 | 2013_11_20_131544_add_status_type_on_status_labels                       |     1 |
|  39 | 2013_11_20_134103_add_archived_to_assets                                 |     1 |
|  40 | 2013_11_21_002321_add_uploads_table                                      |     1 |
|  41 | 2013_11_21_024531_remove_deployable_boolean_from_status_labels           |     1 |
|  42 | 2013_11_22_075308_add_option_label_to_settings_table                     |     1 |
|  43 | 2013_11_22_213400_edits_to_settings_table                                |     1 |
|  44 | 2013_11_25_013244_create_licenses_table                                  |     1 |
|  45 | 2013_11_25_031458_create_license_seats_table                             |     1 |
|  46 | 2013_11_25_032022_add_type_to_actionlog_table                            |     1 |
|  47 | 2013_11_25_033008_delete_bad_licenses_table                              |     1 |
|  48 | 2013_11_25_033131_create_new_licenses_table                              |     1 |
|  49 | 2013_11_25_033534_add_licensed_to_licenses_table                         |     1 |
|  50 | 2013_11_25_101308_add_warrantee_to_assets_table                          |     1 |
|  51 | 2013_11_25_104343_alter_warranty_column_on_assets                        |     1 |
|  52 | 2013_11_25_150450_drop_parent_from_categories                            |     1 |
|  53 | 2013_11_25_151920_add_depreciate_to_assets                               |     1 |
|  54 | 2013_11_25_152903_add_depreciate_to_licenses_table                       |     1 |
|  55 | 2013_11_26_211820_drop_license_from_assets_table                         |     1 |
|  56 | 2013_11_27_062510_add_note_to_asset_logs_table                           |     1 |
|  57 | 2013_12_01_113426_add_filename_to_asset_log                              |     1 |
|  58 | 2013_12_06_094618_add_nullable_to_licenses_table                         |     1 |
|  59 | 2013_12_10_084038_add_eol_on_models_table                                |     1 |
|  60 | 2013_12_12_055218_add_manager_to_users_table                             |     1 |
|  61 | 2014_01_28_031200_add_qr_code_to_settings_table                          |     1 |
|  62 | 2014_02_13_183016_add_qr_text_to_settings_table                          |     1 |
|  63 | 2014_05_24_093839_alter_default_license_depreciation_id                  |     1 |
|  64 | 2014_05_27_231658_alter_default_values_licenses                          |     1 |
|  65 | 2014_06_19_191508_add_asset_name_to_settings                             |     1 |
|  66 | 2014_06_20_004847_make_asset_log_checkedout_to_nullable                  |     1 |
|  67 | 2014_06_20_005050_make_asset_log_purchasedate_to_nullable                |     1 |
|  68 | 2014_06_24_003011_add_suppliers                                          |     1 |
|  69 | 2014_06_24_010742_add_supplier_id_to_asset                               |     1 |
|  70 | 2014_06_24_012839_add_zip_to_supplier                                    |     1 |
|  71 | 2014_06_24_033908_add_url_to_supplier                                    |     1 |
|  72 | 2014_07_08_054116_add_employee_id_to_users                               |     1 |
|  73 | 2014_07_09_134316_add_requestable_to_assets                              |     1 |
|  74 | 2014_07_17_085822_add_asset_to_software                                  |     1 |
|  75 | 2014_07_17_161625_make_asset_id_in_logs_nullable                         |     1 |
|  76 | 2014_08_12_053504_alpha_0_4_2_release                                    |     1 |
|  77 | 2014_08_17_083523_make_location_id_nullable                              |     1 |
|  78 | 2014_10_16_200626_add_rtd_location_to_assets                             |     1 |
|  79 | 2014_10_24_000417_alter_supplier_state_to_32                             |     1 |
|  80 | 2014_10_24_015641_add_display_checkout_date                              |     1 |
|  81 | 2014_10_28_222654_add_avatar_field_to_users_table                        |     1 |
|  82 | 2014_10_29_045924_add_image_field_to_models_table                        |     1 |
|  83 | 2014_11_01_214955_add_eol_display_to_settings                            |     1 |
|  84 | 2014_11_04_231416_update_group_field_for_reporting                       |     1 |
|  85 | 2014_11_05_212408_add_fields_to_licenses                                 |     1 |
|  86 | 2014_11_07_021042_add_image_to_supplier                                  |     1 |
|  87 | 2014_11_20_203007_add_username_to_user                                   |     1 |
|  88 | 2014_11_20_223947_add_auto_to_settings                                   |     1 |
|  89 | 2014_11_20_224421_add_prefix_to_settings                                 |     1 |
|  90 | 2014_11_21_104401_change_licence_type                                    |     1 |
|  91 | 2014_12_09_082500_add_fields_maintained_term_to_licenses                 |     1 |
|  92 | 2015_02_04_155757_increase_user_field_lengths                            |     1 |
|  93 | 2015_02_07_013537_add_soft_deleted_to_log                                |     1 |
|  94 | 2015_02_10_040958_fix_bad_assigned_to_ids                                |     1 |
|  95 | 2015_02_10_053310_migrate_data_to_new_statuses                           |     1 |
|  96 | 2015_02_11_044104_migrate_make_license_assigned_null                     |     1 |
|  97 | 2015_02_11_104406_migrate_create_requests_table                          |     1 |
|  98 | 2015_02_12_001312_add_mac_address_to_asset                               |     1 |
|  99 | 2015_02_12_024100_change_license_notes_type                              |     1 |
| 100 | 2015_02_17_231020_add_localonly_to_settings                              |     1 |
| 101 | 2015_02_19_222322_add_logo_and_colors_to_settings                        |     1 |
| 102 | 2015_02_24_072043_add_alerts_to_settings                                 |     1 |
| 103 | 2015_02_25_022931_add_eula_fields                                        |     1 |
| 104 | 2015_02_25_204513_add_accessories_table                                  |     1 |
| 105 | 2015_02_26_091228_add_accessories_user_table                             |     1 |
| 106 | 2015_02_26_115128_add_deleted_at_models                                  |     1 |
| 107 | 2015_02_26_233005_add_category_type                                      |     1 |
| 108 | 2015_03_01_231912_update_accepted_at_to_acceptance_id                    |     1 |
| 109 | 2015_03_05_011929_add_qr_type_to_settings                                |     1 |
| 110 | 2015_03_18_055327_add_note_to_user                                       |     1 |
| 111 | 2015_04_29_234704_add_slack_to_settings                                  |     1 |
| 112 | 2015_05_04_085151_add_parent_id_to_locations_table                       |     1 |
| 113 | 2015_05_22_124421_add_reassignable_to_licenses                           |     1 |
| 114 | 2015_06_10_003314_fix_default_for_user_notes                             |     1 |
| 115 | 2015_06_10_003554_create_consumables                                     |     1 |
| 116 | 2015_06_15_183253_move_email_to_username                                 |     1 |
| 117 | 2015_06_23_070346_make_email_nullable                                    |     1 |
| 118 | 2015_06_26_213716_create_asset_maintenances_table                        |     1 |
| 119 | 2015_07_04_212443_create_custom_fields_table                             |     1 |
| 120 | 2015_07_09_014359_add_currency_to_settings_and_locations                 |     1 |
| 121 | 2015_07_21_122022_add_expected_checkin_date_to_asset_logs                |     1 |
| 122 | 2015_07_24_093845_add_checkin_email_to_category_table                    |     1 |
| 123 | 2015_07_25_055415_remove_email_unique_constraint                         |     1 |
| 124 | 2015_07_29_230054_add_thread_id_to_asset_logs_table                      |     1 |
| 125 | 2015_07_31_015430_add_accepted_to_assets                                 |     1 |
| 126 | 2015_09_09_195301_add_custom_css_to_settings                             |     1 |
| 127 | 2015_09_21_235926_create_custom_field_custom_fieldset                    |     1 |
| 128 | 2015_09_22_000104_create_custom_fieldsets                                |     1 |
| 129 | 2015_09_22_003321_add_fieldset_id_to_assets                              |     1 |
| 130 | 2015_09_22_003413_migrate_mac_address                                    |     1 |
| 131 | 2015_09_28_003314_fix_default_purchase_order                             |     1 |
| 132 | 2015_10_01_024551_add_accessory_consumable_price_info                    |     1 |
| 133 | 2015_10_12_192706_add_brand_to_settings                                  |     1 |
| 134 | 2015_10_22_003314_fix_defaults_accessories                               |     1 |
| 135 | 2015_10_23_182625_add_checkout_time_and_expected_checkout_date_to_assets |     1 |
| 136 | 2015_11_05_061015_create_companies_table                                 |     1 |
| 137 | 2015_11_05_061115_add_company_id_to_consumables_table                    |     1 |
| 138 | 2015_11_05_183749_image                                                  |     1 |
| 139 | 2015_11_06_092038_add_company_id_to_accessories_table                    |     1 |
| 140 | 2015_11_06_100045_add_company_id_to_users_table                          |     1 |
| 141 | 2015_11_06_134742_add_company_id_to_licenses_table                       |     1 |
| 142 | 2015_11_08_035832_add_company_id_to_assets_table                         |     1 |
| 143 | 2015_11_08_222305_add_ldap_fields_to_settings                            |     1 |
| 144 | 2015_11_15_151803_add_full_multiple_companies_support_to_settings_table  |     1 |
| 145 | 2015_11_26_195528_import_ldap_settings                                   |     1 |
| 146 | 2015_11_30_191504_remove_fk_company_id                                   |     1 |
| 147 | 2015_12_21_193006_add_ldap_server_cert_ignore_to_settings_table          |     1 |
| 148 | 2015_12_30_233509_add_timestamp_and_userId_to_custom_fields              |     1 |
| 149 | 2015_12_30_233658_add_timestamp_and_userId_to_custom_fieldsets           |     1 |
| 150 | 2016_01_28_041048_add_notes_to_models                                    |     1 |
| 151 | 2016_02_19_070119_add_remember_token_to_users_table                      |     1 |
| 152 | 2016_02_19_073625_create_password_resets_table                           |     1 |
| 153 | 2016_03_02_193043_add_ldap_flag_to_users                                 |     1 |
| 154 | 2016_03_02_220517_update_ldap_filter_to_longer_field                     |     1 |
| 155 | 2016_03_08_225351_create_components_table                                |     1 |
| 156 | 2016_03_09_024038_add_min_stock_to_tables                                |     1 |
| 157 | 2016_03_10_133849_add_locale_to_users                                    |     1 |
| 158 | 2016_03_10_135519_add_locale_to_settings                                 |     1 |
| 159 | 2016_03_11_185621_add_label_settings_to_settings                         |     1 |
| 160 | 2016_03_22_125911_fix_custom_fields_regexes                              |     1 |
| 161 | 2016_04_28_141554_add_show_to_users                                      |     1 |
| 162 | 2016_05_16_164733_add_model_mfg_to_consumable                            |     1 |
| 163 | 2016_05_19_180351_add_alt_barcode_settings                               |     1 |
| 164 | 2016_05_19_191146_add_alter_interval                                     |     1 |
| 165 | 2016_05_19_192226_add_inventory_threshold                                |     1 |
| 166 | 2016_05_20_024859_remove_option_keys_from_settings_table                 |     1 |
| 167 | 2016_05_20_143758_remove_option_value_from_settings_table                |     1 |
| 168 | 2016_06_01_140218_add_email_domain_and_format_to_settings                |     1 |
| 169 | 2016_06_22_160725_add_user_id_to_maintenances                            |     1 |
| 170 | 2016_07_13_150015_add_is_ad_to_settings                                  |     1 |
| 171 | 2016_07_14_153609_add_ad_domain_to_settings                              |     1 |
| 172 | 2016_07_22_003348_fix_custom_fields_regex_stuff                          |     1 |
| 173 | 2016_07_22_054850_one_more_mac_addr_fix                                  |     1 |
| 174 | 2016_07_22_143045_add_port_to_ldap_settings                              |     1 |
| 175 | 2016_07_22_153432_add_tls_to_ldap_settings                               |     1 |
| 176 | 2016_07_27_211034_add_zerofill_to_settings                               |     1 |
| 177 | 2016_08_02_124944_add_color_to_statuslabel                               |     1 |
| 178 | 2016_08_04_134500_add_disallow_ldap_pw_sync_to_settings                  |     1 |
| 179 | 2016_08_09_002225_add_manufacturer_to_licenses                           |     1 |
| 180 | 2016_08_12_121613_add_manufacturer_to_accessories_table                  |     1 |
| 181 | 2016_08_23_143353_add_new_fields_to_custom_fields                        |     1 |
| 182 | 2016_08_23_145619_add_show_in_nav_to_status_labels                       |     1 |
| 183 | 2016_08_30_084634_make_purchase_cost_nullable                            |     1 |
| 184 | 2016_09_01_141051_add_requestable_to_asset_model                         |     1 |
| 185 | 2016_09_02_001448_create_checkout_requests_table                         |     1 |
| 186 | 2016_09_04_180400_create_actionlog_table                                 |     1 |
| 187 | 2016_09_04_182149_migrate_asset_log_to_action_log                        |     1 |
| 188 | 2016_09_19_235935_fix_fieldtype_for_target_type                          |     1 |
| 189 | 2016_09_23_140722_fix_modelno_in_consumables_to_string                   |     1 |
| 190 | 2016_09_28_231359_add_company_to_logs                                    |     1 |
| 191 | 2016_10_14_130709_fix_order_number_to_varchar                            |     1 |
| 192 | 2016_10_16_015024_rename_modelno_to_model_number                         |     1 |
| 193 | 2016_10_16_015211_rename_consumable_modelno_to_model_number              |     1 |
| 194 | 2016_10_16_143235_rename_model_note_to_notes                             |     1 |
| 195 | 2016_10_16_165052_rename_component_total_qty_to_qty                      |     1 |
| 196 | 2016_10_19_145520_fix_order_number_in_components_to_string               |     1 |
| 197 | 2016_10_27_151715_add_serial_to_components                               |     1 |
| 198 | 2016_10_27_213251_increase_serial_field_capacity                         |     1 |
| 199 | 2016_10_29_002724_enable_2fa_fields                                      |     1 |
| 200 | 2016_10_29_082408_add_signature_to_acceptance                            |     1 |
| 201 | 2016_11_01_030818_fix_forgotten_filename_in_action_logs                  |     1 |
| 202 | 2016_11_13_020954_rename_component_serial_number_to_serial               |     1 |
| 203 | 2016_11_16_172119_increase_purchase_cost_size                            |     1 |
| 204 | 2016_11_17_161317_longer_state_field_in_location                         |     1 |
| 205 | 2016_11_17_193706_add_model_number_to_accessories                        |     1 |
| 206 | 2016_11_24_160405_add_missing_target_type_to_logs_table                  |     1 |
| 207 | 2016_12_07_173720_increase_size_of_state_in_suppliers                    |     1 |
| 208 | 2016_12_19_004212_adjust_locale_length_to_10                             |     1 |
| 209 | 2016_12_19_133936_extend_phone_lengths_in_supplier_and_elsewhere         |     1 |
| 210 | 2016_12_27_212631_make_asset_assigned_to_polymorphic                     |     1 |
| 211 | 2017_01_09_040429_create_locations_ldap_query_field                      |     1 |
| 212 | 2017_01_14_002418_create_imports_table                                   |     1 |
| 213 | 2017_01_25_063357_fix_utf8_custom_field_column_names                     |     1 |
| 214 | 2017_03_03_154632_add_time_date_display_to_settings                      |     1 |
| 215 | 2017_03_10_210807_add_fields_to_manufacturer                             |     1 |
| 216 | 2017_05_08_195520_increase_size_of_field_values_in_custom_fields         |     1 |
| 217 | 2017_05_22_204422_create_departments                                     |     1 |
| 218 | 2017_05_22_233509_add_manager_to_locations_table                         |     1 |
| 219 | 2017_06_14_122059_add_next_autoincrement_to_settings                     |     1 |
| 220 | 2017_06_18_151753_add_header_and_first_row_to_importer_table             |     1 |
| 221 | 2017_07_07_191533_add_login_text                                         |     1 |
| 222 | 2017_07_25_130710_add_thumbsize_to_settings                              |     1 |
| 223 | 2017_08_03_160105_set_asset_archived_to_zero_default                     |     1 |
| 224 | 2017_08_22_180636_add_secure_password_options                            |     1 |
| 225 | 2017_08_25_074822_add_auditing_tables                                    |     1 |
| 226 | 2017_08_25_101435_add_auditing_to_settings                               |     1 |
| 227 | 2017_09_18_225619_fix_assigned_type_not_being_nulled                     |     1 |
| 228 | 2017_10_03_015503_drop_foreign_keys                                      |     1 |
| 229 | 2017_10_10_123504_allow_nullable_depreciation_id_in_models               |     1 |
| 230 | 2017_10_17_133709_add_display_url_to_settings                            |     1 |
| 231 | 2017_10_19_120002_add_custom_forgot_password_url                         |     1 |
| 232 | 2017_10_19_130406_add_image_and_supplier_to_accessories                  |     1 |
| 233 | 2017_10_20_234129_add_location_indices_to_assets                         |     1 |
| 234 | 2017_10_25_202930_add_images_uploads_to_locations_manufacturers_etc      |     1 |
| 235 | 2017_10_27_180947_denorm_asset_locations                                 |     1 |
| 236 | 2017_10_27_192423_migrate_denormed_asset_locations                       |     1 |
| 237 | 2017_10_30_182938_add_address_to_user                                    |     1 |
| 238 | 2016_06_01_000001_create_oauth_auth_codes_table                          |     2 |
| 239 | 2016_06_01_000002_create_oauth_access_tokens_table                       |     2 |
| 240 | 2016_06_01_000003_create_oauth_refresh_tokens_table                      |     2 |
| 241 | 2016_06_01_000004_create_oauth_clients_table                             |     2 |
| 242 | 2016_06_01_000005_create_oauth_personal_access_clients_table             |     2 |
| 243 | 2017_11_08_025918_add_alert_menu_setting                                 |     2 |
| 244 | 2017_11_08_123942_labels_display_company_name                            |     2 |
| 245 | 2017_12_12_010457_normalize_asset_last_audit_date                        |     3 |
| 246 | 2017_12_12_033618_add_actionlog_meta                                     |     3 |
| 247 | 2017_12_26_170856_re_normalize_last_audit                                |     3 |
| 248 | 2018_01_17_184354_add_archived_in_list_setting                           |     3 |
| 249 | 2018_01_19_203121_add_dashboard_message_to_settings                      |     3 |
| 250 | 2018_01_24_062633_add_footer_settings_to_settings                        |     3 |
| 251 | 2018_01_24_093426_add_modellist_preferenc                                |     3 |
| 252 | 2018_02_22_160436_add_remote_user_settings                               |     3 |
| 253 | 2018_03_03_011032_add_theme_to_settings                                  |     3 |
| 254 | 2018_03_06_054937_add_default_flag_on_statuslabels                       |     3 |
| 255 | 2018_03_23_212048_add_display_in_email_to_custom_fields                  |     3 |
| 256 | 2018_03_24_030738_add_show_images_in_email_setting                       |     3 |
| 257 | 2018_03_24_050108_add_cc_alerts                                          |     3 |
| 258 | 2018_03_29_053618_add_canceled_at_and_fulfilled_at_in_requests           |     4 |
| 259 | 2018_03_29_070121_add_drop_unique_requests                               |     4 |
| 260 | 2018_03_29_070511_add_new_index_requestable                              |     4 |
| 261 | 2018_04_16_133902_create_custom_field_default_values_table               |     4 |
| 262 | 2018_05_04_073223_add_category_to_licenses                               |     4 |
| 263 | 2018_05_04_075235_add_update_license_category                            |     4 |
| 264 | 2018_05_08_031515_add_gdpr_privacy_footer                                |     4 |
+-----+--------------------------------------------------------------------------+-------+
264 rows in set (0.00 sec)

**Comment by snipe** [comment]
What's the error you're getting when you run migrations?

**Comment by wesleytb13** [comment]
I must have accidentally cut that out with the logs - sorry. I get the following error when I run php artisan migrate:

In Connection.php line 647:

  SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'action_logs_target_id_target_type_index
  ' (SQL: alter table `action_logs` add index `action_logs_target_id_target_type_index`(`target_id`, `target_type`))


In PDOStatement.php line 107:

  SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'action_logs_target_id_target_type_index
  '


In PDOStatement.php line 105:

  SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'action_logs_target_id_target_type_index
  '

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/installation-issues#section-duplicate-key-name-action_logs_target_id_target_type_index
