### ISSUE TITLE
Selecting a file for upload given no notification of selection 

### ISSUE THREAD

**Issue by brandenk514** [snipe/snipe-it#5859]
- Snipe-IT Version: v4.5.0 - build 3701
 - OS: Ubuntu 18.04 LTS
 - Web Server: Apache
 - PHP Version: 7.0

Issue:
When uploading a file to an asset there is no file name or notification that the file was selected. 

Possible solution:
I would like to see some notification that selected file is there before I upload it

Alternative solution:
Snipe could use a check mark instead of the file name. 

Please let me know if more information is needed.

**Comment by snipe** [comment]
This should be fixed with https://github.com/snipe/snipe-it/pull/5861
