### ISSUE TITLE
User's Resignation Date

### ISSUE THREAD

**Issue by smksar** [snipe/snipe-it#5864]
**Server (please complete the following information):**
 - Snipe-IT Version 4.5
 - OS: Windows 10
 - Web Server: Apache 2.4.33
 - PHP Version 7.2.4

**Is your feature request related to a problem? Please describe.**
Currently you have to set the Expected Checkin Date during a checkout of an asset but for not possible for our case as we do not know when is the user resigning.

**Describe the solution you'd like**
Similar to Expected Checkin Date during checkout of asset but to have it available in User's page as an option to add Resignation Date which works exactly as Expected Checkin Date. We receive information from HR of when the user will be resigning. Would be nice to have a field to add the user's resignation date and will be reminded on the day or at certain time by email.

**Describe alternatives you've considered**
No alternatives

**Comment by MSTigers** [comment]
Related to my request #5762 , this would be a great addition.

**Comment by dmeltzer** [comment]
Is the goal a reminder that the user will be resigning? Or that all items will be checked in automatically on this date?

**Comment by smksar** [comment]
Hi @dmeltzer if based on Expected Checkin Date feature it would be just reminder because if automatically checkin but the items are not with us yet then it would raise another issue?

Also I believe if to automatically checkin would require more coding then duplicating of whats already available. Is it possible when filling up resignation date this entry will use the column in database of Expected Checkin Date and work the same way as putting the date during checkout?

**Comment by MSTigers** [comment]
I personally wouldn't want anything done automatically with this besides an email notification saying "past expiration/past resignation."

**Comment by MSTigers** [comment]
Still relevant, marked for ready to deploy and a great feature.

**Comment by MSTigers** [comment]
Still ready to deploy, go away bot

**Comment by MSTigers** [comment]
👍

**Comment by MSTigers** [comment]
We meet again.

**Comment by G13312** [comment]
Still relevant! A much needed addition since we dont always know when an employee is leaving and also good to track assets that havent been returned in time!
