### ISSUE TITLE
Deactivate user instead of deleting

### ISSUE THREAD

**Issue by smksar** [snipe/snipe-it#5865]
Server (please complete the following information):

Snipe-IT Version 4.5
OS: Windows 10
Web Server: WAMP Apache 2.4.33
PHP Version WAMP 7.2.4

**Is your feature request related to a problem? Please describe.**
Currently the only option to bulk check in is by using Checkin & Delete User option. I just test with hard delete because I can foresee that any of the team members could accidentally run this option and it would wipe the history of the assets of the users deleted.

**Describe the solution you'd like**
Would love the option to Checkin & Deactivate User instead of deleting as this would very much solves the issue of retaining the history of the assets. I want to hard delete other soft deleted items but not users that have their names attached to assets history. So with the option of deactivating the user I still can see their names in the history of any assets. I believe the process is very much the same as Checkin & Delete user, just that at the end, instead of deleting, deactivate the user.

**Describe alternatives you've considered**
Must manually check in items belonging to the user then deactivating the user. User may have more than 10 assets/accessories to check in.

**Comment by snipe** [comment]
The assumption here is that only people you trust would be set as super admins, and therefore only people you trust would have the ability to purge data from the database. If a user is not purged, they can be restored at any time.
