### ISSUE TITLE
BUG? Checkout user: Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by andreasoc** [snipe/snipe-it#5866]
#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
when check in or checkout the assent, receive this error , but , if refresh page, the operation of assign work fine.
This is the errors: 

Whoops, looks like something went wrong.

(3/3) QueryExceptionSQLSTATE[42S22]: Column not found: 1054 Unknown column 'checkin_counter' in 'field list' (SQL: update `assets` set `checkin_counter` = `checkin_counter` + 1, `updated_at` = 2018-07-17 12:12:36 where `id` = 236 and `assets`.`deleted_at` is null)
--
in Connection.php (line 647)
at Connection->runQueryCallback('update `assets` set `checkin_counter` = `checkin_counter` + 1, `updated_at` = ? where `id` = ? and `assets`.`deleted_at` is null', array('2018-07-17 12:12:36', 236), object(Closure))in Connection.php (line 607)
at Connection->run('update `assets` set `checkin_counter` = `checkin_counter` + 1, `updated_at` = ? where `id` = ? and `assets`.`deleted_at` is null',array('2018-07-17 12:12:36', 236), object(Closure))in Connection.php (line 477)
at Connection->affectingStatement('update `assets` set `checkin_counter` = `checkin_counter` + 1, `updated_at` = ? where `id` = ? and `assets`.`deleted_at` is null', array('2018-07-17 12:12:36', 236))in Connection.php (line 416)
at Connection->update('update `assets` set `checkin_counter` = `checkin_counter` + 1, `updated_at` = ? where `id` = ? and `assets`.`deleted_at` is null',array('2018-07-17 12:12:36', 236))in Builder.php (line 2147)
at Builder->update(array('checkin_counter' => object(Expression), 'updated_at' => '2018-07-17 12:12:36'))in Builder.php (line 2185)
at Builder->increment('checkin_counter', 1, array('updated_at' => '2018-07-17 12:12:36'))in Builder.php (line 773)
at Builder->increment('checkin_counter', 1, array())in Model.php (line 428)
at Model->incrementOrDecrement('checkin_counter', 1, array(), 'increment')in Model.php (line 391)
at Model->increment('checkin_counter', 1)in Loggable.php (line 131)
at Asset->logCheckin(object(Location), '')in AssetsController.php (line 585)
at AssetsController->postCheckin(object(AssetCheckinRequest), '236', null)
at call_user_func_array(array(object(AssetsController), 'postCheckin'), array(object(AssetCheckinRequest), 'assetId' => '236', null))in Controller.php (line 55)
at Controller->callAction('postCheckin', array(object(AssetCheckinRequest), 'assetId' => '236', null))in ControllerDispatcher.php (line 44)
at ControllerDispatcher->dispatch(object(Route), object(AssetsController), 'postCheckin')in Route.php (line 203)
at Route->runController()in Route.php (line 160)
at Route->run()in Router.php (line 572)
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php (line 43)
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php (line 49)
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php (line 49)
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php (line 42)
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php (line 65)
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php (line 37)
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php (line 59)
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Router.php (line 574)
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php (line 533)
at Router->dispatchToRoute(object(Request))in Router.php (line 511)
at Router->dispatch(object(Request))in Kernel.php (line 176)
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php (line 30)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php (line 51)
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php (line 25)
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php (line 27)
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php (line 56)
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php (line 17)
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php (line 18)
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php (line 17)
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php (line 18)
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php (line 17)
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php (line 49)
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php (line 64)
at StartSession->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php (line 46)
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php (line 148)
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php (line 53)
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php (line 102)
at Pipeline->then(object(Closure))in Kernel.php (line 151)
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php (line 116)
at Kernel->handle(object(Request))in index.php (line 58)

**To Reproduce**
1. Go to 'an asset'
2. Click on 'checkin or checkout'
3. Scroll down to 'save'

**Expected behavior**
that you correctly assign me the user

**Screenshots**
![image](https://user-images.githubusercontent.com/2852354/42811561-3444e4aa-89bb-11e8-8af6-a42179fc4bac.png)

**Server (please complete the following information):**
 - Snipe-IT Version 4.5.0
 - OS: [e.g. Ubuntu, CentOS]Windows Server 2012 R2
 - Web Server: [e.g. Apache, IIS] Apache 2.4.27
 - PHP Version  7.0.23

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] the last

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? **After upgrade to the last version** 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by EarlRamirez** [comment]
@andreasoc sounds like the DB migration did not complete but the "refreshing it page" confuses me because it works after this. Don't know if this will help but you can try running the upgrade again or running just the DB migration _php artisan db:migrate --force_

**Comment by dmeltzer** [comment]
`php artisan migrate` not `db:migrate`

**Comment by andreasoc** [comment]
![](https://files.gitter.im/snipe/snipe-it/5W8F/image.png)
this was the error after migrate

**Comment by snipe** [comment]
@andreasoc 
https://snipe-it.readme.io/docs/installation-issues#section-specified-key-was-too-long-max-key-length-is-1000-bytes

**Comment by SylentBobNJ** [comment]
Just as an FYI, I was having this same issue after migrating to 4.5.0 and moving to the git install from tarball on Ubuntu.  I ran the 'php artisan migrate' (without --force) command and it seems to have resolved the issue for me.  
Thanks, @EarlRamirez and @dmeltzer !

**Comment by andreasoc** [comment]
@snipe 
i run the command describes on the KB
DROP INDEX action_logs_target_id_target_type_index ON action_logs;
DROP INDEX action_logs_created_at_index ON action_logs;
DROP INDEX action_logs_item_type_item_id_action_type_index ON action_logs;
DROP INDEX action_logs_target_type_target_id_action_type_index ON action_logs;

ALTER TABLE action_logs ENGINE = InnoDB
ALTER TABLE assets ENGINE = InnoDB

after that run:
php migrate artisan
![image](https://user-images.githubusercontent.com/2852354/42866709-a90caa4a-8a6d-11e8-8d6a-360525baf5fc.png)

and all work fine now! 
thanks everyone!
