### ISSUE TITLE
Resource Booking

### ISSUE THREAD

**Issue by eangulus** [snipe/snipe-it#5870]
I would like to see a resource booking system added in for assets that are loaned out.

For example, vehicles could be booked out to staff and staff could request to book for certain dates and times.

**Comment by n-v-o** [comment]
This functionality exists: https://snipe-it.readme.io/docs/requestable-assets

I don't think the client can ask for it for a certain date/time, which I could see that being useful.  That said, you can still select a checkout and expected check in date when checking that out. You might be able use the notes field to specify times.

**Comment by smksar** [comment]
I believe by suggesting booking feature a calendar integration may be involved for users to see if there is available unit to loan for a period that will lock in the calendar.

This alone may require another module Booking system that perhaps could be enabled/disabled under Settings if the company decides to integrate an asset reservation system.

**Comment by eangulus** [comment]
Still relevant to me for as long as the feature doesn't exist.

**Comment by grifu** [comment]
I'm still working on this subject. 
For now, the user can define a check in/out date-time for reservation and a mail will be sent to the manager. You can see a snapshot in this [https://ibb.co/cPWwLV].
Next, a table should be created to handle the requests.

**Comment by apbutle** [comment]
+1 A booking request calendar, or "reservation" calendar would be a useful feature.

**Comment by grifu** [comment]
We are working on this feature. It is a working in progress.

**Comment by CookieCrumbles** [comment]
> We are working on this feature. It is a working in progress.

Any ETA on this ?

**Comment by rgu-ghanson** [comment]
+1. This is exactly the solution I would be looking for. Thank you Snipe-IT devs.

**Comment by ITHanke** [comment]
+1 any news about this? This will be a awesome feature!

**Comment by maxlehot1234** [comment]
+1 @snipe

**Comment by TheXRMonk** [comment]
+1 really essential for smaller companies

**Comment by sonicnkt** [comment]
+ 1 


currently evaluating snipe-it for our organisations assets. 
A complete reservation system that can be enabled for certain assets would be really cool. 
We have a few devices that are shared between the departments and should be bookable months in advances so everybody could plan their events. If this could be done within snipe-it with a calendar view to check when a device is available would be great so we dont have to rely on another software to manage that and manually update snipe-it accordingly. 

Also our users dont have to use different platforms to request certain devices.

**Comment by grifu** [comment]
Our custom version of Snipe-it is working with the reservation system for about one year as you can see in the picture. However, this version was hardcoded because I did not have time for development. Thus, it is not possible to share. I'll try contributing when I have time.

Best

![sni](https://user-images.githubusercontent.com/2684903/104930766-828dca00-599d-11eb-8c7c-763a78eca5ea.jpg)

**Comment by sonicnkt** [comment]
@grifu this looks like exactly what i would need :) Hope this or something like it makes it into the main version sometime.

**Comment by valentim89** [comment]
+1

**Comment by macpijan** [comment]
Why this was closed by bot here: https://github.com/snipe/snipe-it/issues/5870#issuecomment-463539675, despite the interest was still made by several users?

**Comment by macpijan** [comment]
Seems to be a duplicate request (or at least very similar) to: https://github.com/snipe/snipe-it/issues/5081
I do not see it being linked here as of now, so it might be helpful.
