### ISSUE TITLE
Question about LDAP-/AD-Sync

### ISSUE THREAD

**Issue by PascalTr** [snipe/snipe-it#5873]
We'd like to enable the LDAP-Sync for SnipeIT but we have some questions first. Maybe someone can answer these:

- What happens if I want to delete a user in SnipeIT but it still exists at the AD-Server? Is it getting created again?

- Is there a way to enable the login via the AD-Credentials only for users of a special AD-Group?

- Is there a way to enable Single Sign On for SnipeIT?

- Can I add a default group for all imported users?

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
* Upgrade
- Version of Snipe-IT you're running
* v4.5.0 
- Version of PHP you're running
* 7.2.6
- Version of MySQL/MariaDB you're running
* 5.7.17
- What OS and web server you're running Snipe-IT on
* Windows Server 2012 R2 // IIS-Webserver
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
* manual

**Comment by n-v-o** [comment]
> What happens if I want to delete a user in SnipeIT but it still exists at the AD-Server? Is it getting created again?

Depends on how you're importing users. https://snipe-it.readme.io/v4.5/docs/ldap-sync-login. Basically, if you're filtering. You can identify a base bind DN where you identify an OU where your users are, then you filter based on a security groups. If you don't do any filtering, then the user would be re-added. If you filter based on a security group, and that user is removed from said group, then they would not be re-added.

>Is there a way to enable the login via the AD-Credentials only for users of a special AD-Group?

Technically yes, if you're pointing your filter to that security group. You'd use a LDAP filter like:

`&(objectclass=user)(memberOf:1.2.840.113556.1.4.1941:=CN=TESTGROUP,OU=X,OU=Y,OU=Z` 

This would grab users in a group and any users in nested groups below that.

>Is there a way to enable Single Sign On for SnipeIT?

Looks like there's an active ticket on this: #542 

>Can I add a default group for all imported users?

Not that I'm aware of.

**Comment by DeusMaximus** [comment]
> Is there a way to enable Single Sign On for SnipeIT?

You're going to have to be a bit more specific. Do you mean SAML type stuff like @n-v-o linked to, or do you mean the ability for Windows domain users to automagically login just by visiting the page in IE/Edge or Chrome? Because if it's the latter, there should be a fix coming soon for that.

**Comment by snipe** [comment]
@PascalTr SAML support was implemented in this PR via `REMOTE_USER`: https://github.com/snipe/snipe-it/pull/5142

Future SSO development will probably be in the direction of OAuth, not SAML.

**Comment by mbrrg** [comment]
@snipe Glad to hear that there are plans for OAuth SSO. The REMOTE_USER stuff might be useful in an on-prem/web server scenario but when using a Docker based setup and a cloud based identity provider it would require a great deal of extra/unnecessary plumbing to get it working. OAuth2 would be much easier.
