### ISSUE TITLE
install snipe-it on shared hosting (bluehost)

### ISSUE THREAD

**Issue by grifu** [snipe/snipe-it#5875]
#### Expected Behavior (or desired behavior if a feature request)
I'm trying to install Snipe-It on a shared hosting (Bluehost).

Installation Folder /home/public_html/snipeit

Everything seems to install correctly:
- git clone https://github.com/snipe/snipe-it snipeit
- cp .env.example .env
- .env edit the APP_URL to http://domain/snipeit; database configuration with the usual prefix
- install composer locally with php composer.phar install --no-dev --prefer-source (tried also global composer installation)
- Key generation with php artisan key:generate

Create a subdomain snipeit to domain/public_html/snipeit/public

Result
placing snipeit.domain.com I get in Safari an empty page on Chrome the fowling message: "This page isn’t working. sniepit.domain.com is currently unable to handle this request. HTTP ERROR 500"

There is another issue reporting the same problems with codyjbennett 
https://github.com/snipe/snipe-it/issues/5628

I appreciate any help on this.

**Comment by snipe** [comment]
Without specific error logs, there isn't any way for us to know what's happening here.

**Comment by snipe** [comment]
Please fill in the whole issue template in the future, so we don't have to re-ask the questions we need in order to help you. 

What version of PHP are you running? Snipe-IT [requires](https://snipe-it.readme.io/docs/requirements) v5.6.4 or higher. 
https://snipe-it.readme.io/docs/installation-issues#section-php-version-issues

**Comment by grifu** [comment]
Sorry about that.

The versions provided by Bluehost are the fowling:
Apache | 2.2.34
PHP | 5.6.32
MySQL | 5.6.32-78.1

It seems that the PHP version does not full fill the requirements, although is a very small difference. Required version: 5.6.4, Bluehost version: 5.6.32

**Comment by snipe** [comment]
Yeah, unfortunately, there's no way around the PHP requirement. :-/

**Comment by grifu** [comment]
Does an older version of Snipe-It work with the PHP 5.6.32 version?
In the fowling thread https://github.com/snipe/snipe-it/issues/5628  , codyjbennett was able to install and run Snipe-It from Bluehost. I believe that using the same PHP version as mine.

**Comment by grifu** [comment]
It is possible to upgrade the PHP version on Bluehost. Probably codyjbennett was using a newer version.  Need to be careful because I'm using some applications that are not compatible with new versions of PHP. But I'll make a try.

**Comment by snipe** [comment]
Depending on how they have you set up, you may be able to toggle versions between different domains/projects. (If they're running PHP as fastcgi, versus an Apache module.)

**Comment by grifu** [comment]
Ok, I have upgrade PHP to version 7 and everything is now working.
Thank you snipe.

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
