### ISSUE TITLE
[Feature Request] Granular Edit Asset Permissions

### ISSUE THREAD

**Issue by CoffeeSquirrel** [snipe/snipe-it#5885]
**Server (please complete the following information):**
 - Snipe-IT Version **4.4.1**
 - OS: [e.g. Ubuntu, CentOS]  **Windows Server 2012 R2**
 - Web Server: [e.g. Apache, IIS]  **IIS**
 - PHP Version  **7.2.2**

**Is your feature request related to a problem? Please describe.**
I have users that are "managers" not "admins" that have the authority to edit certain asset information. However, if I grant them Edit access, they can edit _every_ field. I only want my "manager" users to be able to edit the following fields:  Company, Status, Checkout, Asset Name, and Location. The rest of the fields would be for the admins and super admins only.

**Describe the solution you'd like**
More granular asset editing permissions

**Describe alternatives you've considered**
Denying edit permissions and having one super admin handle all editing.

**Additional context**
Full Multiple Companies Support is enabled.

**Comment by dmeltzer** [comment]
I worry about the UI/logic for such an interface.  This feels like it's better handled at a social level than a technical one
