### ISSUE TITLE
[Question] How to organize Virtual Machines (No asset tag, no serial)?

### ISSUE THREAD

**Issue by violetrain** [snipe/snipe-it#589]
Hi,

How do you organize virtual machines in snipe-it? They have neither an asset tag nor a serial number (which are mandatory fields) but hold licenses. Do I need to work with dummy entries here?
If so, feature request: Allow creation of virtual computer models which don't need asset tags and serial numbers.

Peter
##

**Comment by kobie-chasehansen** [comment]
Snipe-IT can generate asset tags, maybe there can be a way to generate asset tags when needed but input an asset tag when not needed. then that generated asset tag can be added to a custom attribute field within the hypervisor.

I know custom attributes would work in VMware, not sure about other hypervisors.

**Comment by violetrain** [comment]
Sure, that will work, but does not solve the serial number problem.
From my point of view assets tags and serial numbers belong to real hardware, not to virtual machines, cause they are simply not assets. Currently I'm using the VM's Backup ID as asset tag and serial number, but I'm not really happy with this solution. Using automatically generated asset tags instead will change nothing.

**Comment by kobie-chasehansen** [comment]
Nice. for my use case I couldn't find a short, unique id to use. I will have to look into the backup jobs for one.

Maybe add a method to Model creation that grays out the serial number field all together? For us we don't use the name field as it is so think I would want to enter the VM name as my serial number.

@violetrain - How would you like to see this work within the interface?

**Comment by violetrain** [comment]
Well, the backup ID comes from my powershell backup script...
Good question about the interface, I assume leaving away asset tag and serial will break snipe-it's  internal logic (i often enough messed up the database with my scripts :). Maybe a "virtual" computer model which will use internal hidden values for asset tag and serial number might work? Simply create long random unique values and don't display them in the interface...

**Comment by rp-tech** [comment]
I just made up my own tags to deal with this issue (preceded by the letter 'V') - that way I can assign software licenses to my virtual machines

**Comment by violetrain** [comment]
That’s an option, but from my point of view virtual machines are not assets, because they are not real hardware. And I have no control over the asset tags, they are assigned by finance department, so I can’t add something or increase the counter on my own. Would have to maintain my own list of VM asset tags…
 
 
 
Peter Weissflog - IT-Administration
email : weissflog@tesis.de  
phone : +49 89 747377-25
 
Von: rp-tech [mailto:notifications@github.com] 
Gesendet: Mittwoch, 3. Juni 2015 23:58
An: snipe/snipe-it
Cc: violetrain
Betreff: Re: [snipe-it] [Question] How to organize Virtual Machines (No asset tag, no serial)? (#589)
 
I just made up my own tags to deal with this issue (preceded by the letter 'V') - that way I can assign software licenses to my virtual machines

**Comment by deld** [comment]
So is the best conclusion on this to use assets and fake a tag num?.  We're trying to list Amazon EC2 reserved instances.....the licensing section seem to be a "better" fit with the start and expiration dates, but we'd like to be able to have our folks check them out as assets.  So either we manually manage it internally with licenses, or we have virtual assets (without the start and stop dates, etc).  Does anyone have a best practice on how to manage this?

**Comment by uberbrady** [comment]
Very interesting problems here. I don't know that I have solutions, but let me talk through what I'm thinking - 

AWS actual _instances_ certainly do have a sort-of 'serial number' you can track - the instance ID. ```i-12345678``` or whatever.

But a reservation - well, that has a reservation ID, an ```r-``` number. But it has start and end dates. That feels like I would want to make the instances into Assets, and the reservations into Software Licenses. You could then set durations of one year or three, perhaps, and keep track of when the reservations are expiring? I would 'check out' a reservation to an instance when I figured it was being used. But then again, would you want to create multiple "locations" for different AWS regions or Availability zones? That might not be necessary. But if you check out a reservation to an instance, the system will let you do illegal things like assign a ```us-east-1b``` reservation to a ```us-east-1e``` instance...

**Comment by deld** [comment]
interesting.....good point on the instance id's.  Reservations do have the unique id - but from what I see in my console it is for the entire order.  For instance I have one order with over 20 VM's - they show up as one line item with one reservation ID.  

I'm not worried about the illegal assigning of instances in one region to another.  My main goal is to grant access to a team of devs to go play, but check things in and out when not using the for others to play. In that case adding the license to it may be over kill.  I like the end dates associated with them, but to essentially  have the same info in two spots (assets and licenses) may add un necessary complexity.  Maybe I just hope that the whole virtual assets is worked out before my reservations expire :-D

**Comment by uberbrady** [comment]
I think the software licenses and then creating/destroying an 'asset' for the actual instance makes the most sense.

If you get reservations that are for more than one box, you can use a multi-seat license.

It should be pretty straightforward there, no? Other than, I guess, the fact that you have to create a pseudo-asset for the instance...

**Comment by deld** [comment]
that's fair - good work around for now until we get virtual assets addressed a little better.

**Comment by violetrain** [comment]
What about combining assets (hardware) with licenses (OS and programs) by using a, let’s call it “installation”, object? The asset object still holds asset tag and serial while the installation object holds the mandatory installation name (which, in my point of view is the unique DNS name) and software checkouts.
Then you can bind multiple “installation” objects to an asset, e.g. multiple virtual machines to one server or multiple operating systems to a multi boot machine.
 
Peter
 
 
Von: deld [mailto:notifications@github.com] 
Gesendet: Mittwoch, 1. Juli 2015 01:40
An: snipe/snipe-it
Cc: violetrain
Betreff: Re: [snipe-it] [Question] How to organize Virtual Machines (No asset tag, no serial)? (#589)
 
interesting.....good point on the instance id's. Reservations do have the unique id - but from what I see in my console it is for the entire order. For instance I have one order with over 20 VM's - they show up as one line item with one reservation ID. 
I'm not worried about the illegal assigning of instances in one region to another. My main goal is to grant access to a team of devs to go play, but check things in and out when not using the for others to play. In that case adding the license to it may be over kill. I like the end dates associated with them, but to essentially have the same info in two spots (assets and licenses) may add un necessary complexity. Maybe I just hope that the whole virtual assets is worked out before my reservations expire :-D

**Comment by haynes11** [comment]
Hi,

I'm looking to use SNIPE-IT for all the virtual machines on my infrastructure along with Windows licensing + WHM/Cpanel licensing. It would be really really useful to get this.

Best,
J
