### ISSUE TITLE
Missing filter in licences

### ISSUE THREAD

**Issue by shinduke** [snipe/snipe-it#5892]
**Server (please complete the following information):**
 - Snipe-IT Version  v4.5.0 build 3701
 - OS: CentOS

**Is your feature request related to a problem? Please describe.**
Our company is splitted to several towns/locations and so are also our licences splited. It would be amasing if we could filter the licences for a location.
Because we share the licences it would be a nice feature to see which licence is in which location at the moment.
In actual state we have to go into every licence description and look where it is. With a filter option in the overview this would be 10 times faster.

**Describe the solution you'd like**
An filter option like the filter already added (ID, company, key, etc.)

**Comment by shinduke** [comment]
I think the frist one ist the right way for us.

At this moment we connect a licence to an asset which is at a location. This is fine, because we need to know on which asset the licence is installed. Our assets are bind to a location.
Our problem is, that we don´t search for assets. If we look a the licence overview we see all informations but not where the licences are or better in which location they are. We have to go into every licence description. 
So our goal is to filter in the licence overview all licences which are connected to the assets in one localtion.

I.e. we got 12 licences in Berlin on 12 assets. So we go to the licence filter and choose location as a filter and type berlin.
The goal is to see then all licences which are in berlin.
An additional good point would be that you could choose a filter for assets as well so you would see in the overview on which asset they are and in which location. But for us would be the location point the important one.

**Comment by snipe** [comment]
I'm not really sure how we'd convey that though, since the licenses listing page is more about the license itself, not the seats. You could have a single license with seats checked out to 100 different places. Since the license seats aren't visible on the licenses listing page, I'm not sure how we'd display that information even if we wanted to.
