### ISSUE TITLE
Custom fields of type "CUSTOM REGEX" are always saved as "ANY"

### ISSUE THREAD

**Issue by gfreeman1** [snipe/snipe-it#5896]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When creating or editing a custom field and choosing "CUSTOM REGEX" for the format, it is always saved as "ANY" instead.

**To Reproduce**
1. Go to 'Settings - Custom Fields'
2. Click on 'New Custom Field'
3. Fill in a name and choose 'CUSTOM REGEX' for the format
4. Fill in the 'Custom Regex Format' field using the example regex given
5. Click the 'Save' button
6. Scroll down to see your new custom field
7. Note how the format column says 'ANY' instead of showing the custom regex
8. Click the Edit button
9. Note how the Format field has reverted to 'ANY'

**Expected behavior**
After saving a "CUSTOM REGEX" custom field, it should show the regex in the custom fields list.

**Screenshots**
Creating a new custom field:
![customfieldissue-1](https://user-images.githubusercontent.com/2089782/42957316-4d4bdbac-8b50-11e8-91ad-82411f4a331c.png)

After saving:
![customfieldissue-2](https://user-images.githubusercontent.com/2089782/42957322-52d7034e-8b50-11e8-8955-9ea1e9f7e556.png)

After clicking the Edit button for the field:
![customfieldissue-3](https://user-images.githubusercontent.com/2089782/42957326-54e99bf6-8b50-11e8-813b-a05eeae2be41.png)

Custom field as it appears in the database:
![customfieldissue-4](https://user-images.githubusercontent.com/2089782/42957896-ec690718-8b51-11e8-8d61-39aea244713a.png)

**Server:**
 - Snipe-IT Version: v4.5.0 - build 3701 (master)
 - OS: Ubuntu 18.04 LTS (GNU/Linux 4.15.0-23-generic x86_64)
 - Web Server: Apache/2.4.29 (Ubuntu)
 - PHP Version: PHP 7.2.7-0ubuntu0.18.04.2

**Desktop:**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: 67.0.3396.99 (Official Build) (64-bit)

**Error Messages**
- I couldn't find any error messages anywhere relating to this
- I have successfully reproduced the issue on the demo

**Additional context**
- Not sure that it matters, but Snipe-IT is installed in a Ubuntu VM running under Hyper-V.
- I tried upgrading to v4.6, but the issue persisted so I reverted the VM's snapshot to get back to v4.5
- Snipe-IT was installed using install.sh
- If I manually update the database, the custom fields display and behave as expected.

**Comment by snipe** [comment]
I have a partial fix on develop/master right now, but the edit screen is defaulting to boolean. It saves correctly now, but you have to re-select custom regex from the dropdown if you edit. I'll have a more complete fix shortly.
