### ISSUE TITLE
Custom Reports

### ISSUE THREAD

**Issue by jmartins1** [snipe/snipe-it#5897]
I work at a school and each year staff return all equipment signed out to them. Generally, we reissue the same equipment they held the year before. It would be very nice to have an option in the custom reports to add the TARGET (as seen on the History tab for each user)  to the report, i.e.  This way we could easily see who the equipment was signed out to previously.

Thanks!

**Comment by snipe** [comment]
I'm not sure I understand - you can already see the users the assets are checked out to in the custom report.

**Comment by jmartins1** [comment]
I mean when the asset has been signed in. You are not able then to view who previously had the item. The only way to do this is to look up each asset or user and look at the history tab.

 

Thanks!

**Comment by ks9389** [comment]
Run the report before the assets are checked in and export it to a CSV so that you have a comparison..?

**Comment by jmartins1** [comment]
Please close, although it would have been nice to have this ability.

⁣Sent from BlueMail ​

**Comment by jmartins1** [comment]
Please close.

⁣Sent from BlueMail ​

**Comment by jmartins1** [comment]
I think it would be nice to offer an ability to generate reports by a particular data.  So, SnipeIT would generate a report of all items as they appeared for that particular time...a snapshot if you will. Or provide an option to generate an inventory snapshot that you can mount to find previous item standing, e.g. checked it/out, when to whom, etc.

⁣Sent from BlueMail ​

**Comment by jmartins1** [comment]
Yes

⁣Sent from BlueMail ​

**Comment by jmartins1** [comment]
Please close. I don't want to be asked by a bot if the issue is still relevant. Either tell me that you're considering it, not going to implement it, or simply close the request.
