### ISSUE TITLE
[Feature Request] Additional notes field 'hardware information' for assets

### ISSUE THREAD

**Issue by violetrain** [snipe/snipe-it#590]
It would be nice to have an additional notes field for assets where some hardware info can be placed.

Peter
##

**Comment by madd15** [comment]
Could the hardware info not be placed in the existing note field?

**Comment by violetrain** [comment]
Generally yes, but we are using the notes field for organisational stuff (like the purpose of a shared computer), which we don't want to mix up with the hardware information. Additionally, if you create an asset report I would like to see the hardware info there but not the IT departments internal notes.
Also it would be much easier to populate a separate field by script without touching the other notes. We are running Lansweeper and would like to regularly auto populate the hardware notes with live-scan information.

**Comment by snipe** [comment]
How are you planning on updating this field automatically? Do you have a script?

**Comment by cobrien165** [comment]
Along with this, a notes field or a hardware info field would be helpful within the Asset Models. That way, the notes or additional notes for the specific asset would only need to include hardware info outside of the original model specs. ie. the model comes with 4GB of RAM normally but the specific asset has been upgraded to 8GB.

**Comment by violetrain** [comment]
Nice idea, but only useful for models which are not highly configurable. Dell, HP, Lenovo etc. are offering multiple configurations options for enterprise customers, so you might have no equally configured machines (as we have, and we have many).
 
Peter
 
 
Peter Weissflog - IT-Administration
email : weissflog@tesis.de  
phone : +49 89 747377-25
 
Von: cobrien165 [mailto:notifications@github.com] 
Gesendet: Dienstag, 2. Juni 2015 19:11
An: snipe/snipe-it
Cc: violetrain
Betreff: Re: [snipe-it] [Feature Request] Additional notes field 'hardware information' for assets (#590)
 
Along with this, a notes field or a hardware info field would be helpful within the Asset Models. That way, the notes or additional notes for the specific asset would only need to include hardware info outside of the original model specs. ie. the model comes with 4GB of RAM normally but the specific asset has been upgraded to 8GB.
