### ISSUE TITLE
Allow accessories to be edited in bulk

### ISSUE THREAD

**Issue by mtausig** [snipe/snipe-it#5901]
**Server (please complete the following information):**
 - Snipe-IT V4.5.0
 - OS: Ubuntu 16.04
 - Web Server: nginx
 - PHP Version 7.0

**Is your feature request related to a problem? Please describe.**
Sometimes you like to edit multiple accessories in bulk. For instance if you want to assign multiple thing to a newly created location

**Describe the solution you'd like**
Accessories should be bulk editable just like assets (selecting all you need and then select edit from the drop down in the top left corner)

**Describe alternatives you've considered**
Edit all accessories one by one. Takes a long time.

**Comment by snipe** [comment]
> For instance if you want to assign multiple thing to a newly created location

That doesn't sound like bulk editing to me, that sounds like bulk checkin/checkout...

**Comment by mtausig** [comment]
Location was just an example. I might also want to set the maufacturer or the purcahse date in bulk for a couple of accessories. Just like I can do wit assets.

**Comment by mtausig** [comment]
Still relevant to me.

**Comment by mtausig** [comment]
Still relevant to me.

**Comment by didiatworkz** [comment]
Still relevant to me, too ;)

**Comment by tymik** [comment]
+1, i also find an use for it!
examples for it i have noted are change of:

- location
- order no.
- company
- category
- supplier

and there might be possibly more.
e.g.: i can not have the order no when adding some accessories and have it provided later by financial departament - i'd like to be able to update all assets from that order in bulk.

**Comment by mtausig** [comment]
Still relevant to me.

**Comment by mtausig** [comment]
Still relevant.

**Comment by mtausig** [comment]
Still relevant.

**Comment by mtausig** [comment]
still relevant

**Comment by harracuda** [comment]
Still relevant!
