### ISSUE TITLE
snipe it import error

### ISSUE THREAD

**Issue by prabhu232** [snipe/snipe-it#5907]
Hi,

I am facing issue snip it csv asset file import.error details mentioned below.please help to resolve the issue.

Error : Asset "": The model id field is required.The asset tag field is required. 

Regards,
S.Prabhu

**Comment by EarlRamirez** [comment]
You need to include the Asset model number and Asset Tag in your CSV file, if you can share your header we will be able to help you out more

**Comment by prabhu232** [comment]
HI,

Thanks for your reply. Yes i have included model and asset tag.Please find attachment.

[Asset.xlsx](https://github.com/snipe/snipe-it/files/2215909/Asset.xlsx)

**Comment by EarlRamirez** [comment]
@prabhu232 here is a sample header of an import that was successful

Company | Item Name | MAC Address | Model Name | IP Address | Servicing Location | Model Number | Serial Number | Manufacture | Category | Location | Status | Asset Tag
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
You need to include the Model Number at least based on the sample that you have shared, it does not have that information; therefore, you will need to map it from the web UI

**Comment by EarlRamirez** [comment]
_You need to include the Model Number at least based on the sample that you have shared, it does not have that information; therefore, you will need to map it from the web UI_

**Comment by prabhu232** [comment]
Yes After mapping the model number and model name is Working.
thanks for your support.

**Comment by prabhu232** [comment]
I am facing one more issue.i Am unable browse outside that server.below mentioned error getting

 Not Found
The requested URL / was not found on this server.

Apache/2.4.17 (Win64) PHP/7.0.0 Server at local host Port 80
