### ISSUE TITLE
domain subfolder home link

### ISSUE THREAD

**Issue by alexisskeates** [snipe/snipe-it#591]
I've started using Snipe-it for my self and now decided to start using for my client. What I have done so far is setup a single web server and and am running multiple instances of the application under the same domain name.

So in my apache root which is /var/www/html I have a number symlinks pointing back to /var/www/snipeit-client1/public /var/www/snipteit-client2/public and so on.

I'm in the process of putting up a front facing page in the /var/www/html which will redirect the client to the correct subfolder dependant on their email address domain.

This all works great and I even manage to script the install so I can setup a new instance of this in a few seconds.

How ever the one issue I am having is when you log in as a client and then click the home link in the top right hand corner of application the "SNIPE IT ASSET MANAGEMENT LINK" I get redirected back to /var/www/html/ is there anywhere I can change this so I get redirected back to the /var/www/html/snipeit-client1 or /var/www/html/snipeit-client2 even if I have to change this manually on each install.

**Comment by snipe** [comment]
This is fixed on develop
