### ISSUE TITLE
 System crashed due to hardware failure disaster, need to restore the services.

### ISSUE THREAD

**Issue by ziyaul121** [snipe/snipe-it#5912]
#### Expected Behavior (or desired behavior if a feature request)

Hi Snipe, 

Unfortunately the system crashed due to hardware failure disaster. I do have a zip backup only, I have no choice but to do a fresh install on another machine.

How can I restore the services and application data.

Please guide me, How I can restore the application. 

Thanks in advance.
-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  Fresh Install
- Version of Snipe-IT you're running  Version v4.1.14
- Version of PHP you're running 7
- Version of MySQL/MariaDB you're running 
- What OS and web server you're running Snipe-IT on centos 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh,
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by EarlRamirez** [comment]
you can give this a try _https://snipe-it.readme.io/docs/upgrading-to-v4_, if it does point you in the right direction, I will walk you through the process

**Comment by ziyaul121** [comment]
Thanks Dear Earl Ramirez,
This is the upgrading procedure but old machine disk totally crashed so I don't have anything only zip backup file,  how can I get my application data from old machine zip backup file to new fresh installed machine.
How can I use this Zip backup file in restoring database in new fresh installed machine. ??

**Comment by EarlRamirez** [comment]
The data is within the backup*.zip file
![image](https://user-images.githubusercontent.com/12306859/43036337-6b9b4302-8d32-11e8-91fc-3354694d932f.png)
Give me about 30 to 45 minutes and I will be able to walk you through the process if required, that is correct, it is upgrading; however, it should be able to get you started.

**Comment by EarlRamirez** [comment]
Noticed that the templated was not completed; therefore, the assumption will be that you are using a Linux distribution
- unzip the backup.zip from the server that crashed _unzip backup*.zip_
- copy the upload directory from your backup to your new server 
cp -R snipe-it-backup/public/uploads/* snipe-it/public/uploads
cp -R snipe-it-backup/storage/private_uploads/* snipe-it/storage/private_uploads
cp -R snipe-it-backup/storage/app/backups/* snipe-it/storage/app/backups
cp -R snipe-it-backup/.env snipe-it/ (assuming that you have a backup of the .env file or the APP key)
cp -R snipe-it-backup/storage/oauth-private.key snipe-it/storage/oauth-private.key
cp -R snipe-it-backup/storage/oauth-public.key snipe-it/storage/oauth-public.key
- restore the SQL backup from the shell _mysql db_name < backup-file.sql_
- clear your cache
php artisan config:clear
php artisan cache:clear

**The APP key is required to decrypt the database that crashed on the previous server** 
The document that I should have sent you was _https://snipe-it.readme.io/docs/switching-to-a-git-install_

**Comment by snipe** [comment]
Hi @ziyaul121 - you should just be able to follow the directions for [moving Snipe-IT to a new server](https://snipe-it.readme.io/docs/moving-snipe-it) (since that's basically what you're doing.)

**Comment by EarlRamirez** [comment]
Our condolences

**Comment by snipe** [comment]
@ziyaul121 oh my gosh, I'm so sorry for your loss. :(

**Comment by ziyaul121** [comment]
Dear All,
I am importing database with below command but getting this error, Pls help me.
snipeit]# mysql snipeit <snipeit.sql
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)

**Comment by snipe** [comment]
@ziyaul121 Looks like you're not passing a user/password into your import process, and the mysql on your new server probably requires a user/password.

**Comment by ziyaul121** [comment]
Dear Snipe ,

Got it and it worked after using root password but now whenever I am migrating database with below command than this error comes. Pls look into this.

 **snipeit]# php artisan migrate**
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes


In Connection.php line 647:

  SQLSTATE[HY000] [1045] Access denied for user 'snipeit'@'localhost' (using passw
  ord: YES) (SQL: select * from information_schema.tables where table_schema = sni
  peit and table_name = migrations)


In PDOConnection.php line 47:

  SQLSTATE[HY000] [1045] Access denied for user 'snipeit'@'localhost' (using passw
  ord: YES)


In PDOConnection.php line 43:

  SQLSTATE[HY000] [1045] Access denied for user 'snipeit'@'localhost' (using passw
  ord: YES)

**Comment by ziyaul121** [comment]
Everything went well but once I run snipeit]# php artisan migrate  command than it is throwing above comment error. Please help me how can I fix it. Please

**Comment by EarlRamirez** [comment]
Are you able to authenticate to with the snipeit user from the shell with the credentials in the .env config file? Looks like you will need to update your credentials

**Comment by ziyaul121** [comment]
But snipeit database is already there. can u please confirm DB_USERNAME=snipeit is OS user or database user? It is not in OS may be it might be in database users. How can I see database user? And reset the password and grant permission and update in .env ??

MariaDB [(none)]> create database snipeit;
ERROR 1007 (HY000): Can't create database 'snipeit'; database exists
MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| snipeit            |
+--------------------+
4 rows in set (0.00 sec)

**Comment by snipe** [comment]
DB_USERNAME=snipeit is the database's user.

Just because the database exists doesn't mean there is a user that's been set up that can access it. There are some tutorials here:

https://dba.stackexchange.com/questions/23265/mysql-show-grants-for-all-users
https://www.digitalocean.com/community/tutorials/how-to-create-a-new-user-and-grant-permissions-in-mysql

**Comment by ziyaul121** [comment]
Ok, So snipeit database and snipeit user is already there than only I need to perform 5th step from this guide https://snipe-it.readme.io/docs/creating-a-database-and-user

Right ?? Also I need to update database details in .env ?
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=snipeit
DB_USERNAME=snipeit
DB_PASSWORD=KWYfPnNZasdcFuvyffz
DB_PREFIX=null
DB_DUMP_PATH='/usr/bin'
DB_CHARSET=utf8mb4as
DB_COLLATION=utf8masb4_unicodeasd

Step 5: Grant privileges while assigning the password
MySQL
 grant all on snipeit.* to 'snipe_user'@'localhost' identified by 'YOUR_DB_PASSWORD_HERE';

**Comment by EarlRamirez** [comment]
@ziyaul121  that is correct, execute step 5

**Comment by EarlRamirez** [comment]
@ziyaul121 in future please omit all sensitive data, e.g. DB password, APP_KEY, etc

**Comment by ziyaul121** [comment]
Yes I have already made some changes in values before posting, Thank you so much , here DB_PASSWORD=KWYfPnNZasdcFuvyffz automatically set by insatll.sh. should I set human readable password here. 

I executed but same error. Please look into this.  

 grant all on snipeit.* to 'snipeit'@'localhost' identified by 'My DB password';
Query OK, 0 rows affected (0.00 sec)

MariaDB [(none)]> quit
Bye
[root@svrvdc-asset snipeit]#
[root@svrvdc-asset snipeit]# pwd
/var/www/snipeit
[root@svrvdc-asset snipeit]# php artisan migrate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes


In Connection.php line 647:

  SQLSTATE[HY000] [1045] Access denied for user 'snipeit'@'localhost' (using passw
  ord: YES) (SQL: select * from information_schema.tables where table_schema = sni
  peit and table_name = migrations)


In PDOConnection.php line 47:

  SQLSTATE[HY000] [1045] Access denied for user 'snipeit'@'localhost' (using passw
  ord: YES)


In PDOConnection.php line 43:

  SQLSTATE[HY000] [1045] Access denied for user 'snipeit'@'localhost' (using passw
  ord: YES)

**Comment by EarlRamirez** [comment]
Once you have updated/changed the DB password from step 5 you will need
to update the .env with that new password. 

The password can be anything that you like as long as it is the correct
one and the only you or the admin knows it.

Were you able to connect to the DB with the updated credentials, _mysql
-u snipeit -p_

**Comment by ziyaul121** [comment]
Yes, I am able to connect.
 mysql -u snipeit -p
Enter password:
Welcome to the MariaDB monitor. 
So I need to update this password in .env like below.
DB_PASSWORD=---------

Please help me I never change this value. I just copy the old machine .env to new machine .env 

I need to update this below like:
DB_PASSWORD=Mypassword

**Comment by EarlRamirez** [comment]
That is correct you will need to update the.env with the password you used
to successfully authenticate with the DB.

**Comment by ziyaul121** [comment]
Thanks a lot , Once update password in .env than it worked. But below error now coming.

 snipeit]# php artisan migrate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes


In Connection.php line 647:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_custom_fields' already exists (SQL: create table `models_custom_fields` (`id` int unsigned not null a
  uto_increment primary key, `asset_model_id` int not null, `custom_field_id` int not null, `default_value` text null) default character set utf8mb4 collate utf8mb4_unicode_c
  i engine = InnoDB)


In PDOStatement.php line 107:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_custom_fields' already exists


In PDOStatement.php line 105:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_custom_fields' already exists

**Comment by ziyaul121** [comment]
Woooooooooow, You all saved me. Now it worked and everything sort out fine.

Thanks a lot and God bless you both.

**Comment by EarlRamirez** [comment]
Glad that you are in a better place with your restore, @ziyaul121  are you using MariaDB version 10?

Same to you...

**Comment by ziyaul121** [comment]
Dear All,
Now whenever I try to checkout the software licenses than its throwing error "Whoops, looks like something went wrong." and also whenever checkin than it checkin successfully but it is not returning to the previous page and coming same error Whooops.

I can checkout, checkin asset, accessories and consumables successfully but reutring page throwing error "Whooops".

But can't checkout software licenses because it is not going to select user page. as soon as  I click checkout software license it throws error ""Whoops," 

Please help me to fix out this issue. 

@EarlRamirez , I am using Server version: 5.5.56-MariaDB MariaDB Server

**Comment by ziyaul121** [comment]
Dear All, 
Please find the below debug logs whenever I checkout software license. Pls help me out.


(2/2) ErrorExceptionTrying to get property of non-object (View: /var/www/snipeit/resources/views/licenses/checkout.blade.php)
--
in License.php line 236
at CompilerEngine->handleViewException(object(ErrorException), 1)in PhpEngine.php line 44
at PhpEngine->evaluatePath('/var/www/snipeit/storage/framework/views/b1b1373a384d1e2b3b2d59f4d827cf3c239b62e2.php', array('__env' =>object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => true, 'signedIn' => true, 'user' => object(User), 'license' =>object(License), 'snipeSettings' => object(Setting)))in CompilerEngine.php line 59
at CompilerEngine->get('/var/www/snipeit/resources/views/licenses/checkout.blade.php', array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => true, 'signedIn' => true, 'user' => object(User), 'license' => object(License), 'snipeSettings' => object(Setting)))in View.php line 137
at View->getContents()in View.php line 120
at View->renderContents()in View.php line 85
at View->render()in Response.php line 38
at Response->setContent(object(View))in Response.php line 201
at Response->__construct(object(View))in Router.php line 615
at Router->prepareResponse(object(Request), object(View))in Router.php line 572
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php line 43
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php line 49
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php line 49
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php line 42
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Router.php line 574
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 533
at Router->dispatchToRoute(object(Request))in Router.php line 511
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php line 51
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php line 25
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php line 27
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

**Comment by snipe** [comment]
Did you try to run migrations? My guess would be that your license is connected to an invalid category

**Comment by ziyaul121** [comment]
Dear @snipe ,

yes, Once I run than below message coming. But whenever refresh the homepage than I found all my license data and asset data perfectly. but why this error now :( :(.

 **snipeit]# php artisan migrate**
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes


In Connection.php line 647:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_cust
  om_fields' already exists (SQL: create table `models_custom_fields` (`id` i
  nt unsigned not null auto_increment primary key, `asset_model_id` int not n
  ull, `custom_field_id` int not null, `default_value` text null) default cha
  racter set utf8mb4 collate utf8mb4_unicode_ci engine = InnoDB)


In PDOStatement.php line 107:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_cust
  om_fields' already exists


In PDOStatement.php line 105:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_cust
  om_fields' already exists

**Comment by ziyaul121** [comment]
And even I am not able to create new software licences. Pls find the attached debug log. 
In my old machine Snipe IT version was Version v4.1.14 but once I moved to newly machine and installed there as per guided than its version is v4.6.3 build 3866 (g3de1de9dc) .
is it due to version ?? Software category was not in Version v4.1.14 but now it available in latest version.

[Debug logs error while creating new licesnse.txt](https://github.com/snipe/snipe-it/files/2231481/Debug.logs.error.while.creating.new.licesnse.txt)

**Comment by ziyaul121** [comment]
Software license category was not in older version Version v4.1.14 and once I moved it version change to v4.6.3 build 3866 (g3de1de9dc)  and in this snipe IT version there is software license category which is good . is this reason and there might be no table with category name. How can I fix this issue.

**Comment by snipe** [comment]
The problem is that something failed in your migrations. It's very late here tho. I'll try to help you tomorrow.

**Comment by ziyaul121** [comment]
Dear @snipe , Thanks a lot , I will be waiting...

**Comment by ziyaul121** [comment]
Dear @snipe , could you please help me to fix out this issue. And I found one more issue same like me.
is this my solution? 
Pls help.
https://github.com/snipe/snipe-it/issues/5920

**Comment by EarlRamirez** [comment]
Just finish my last examination, will be able to help you or try to once I'm in front or my computer

**Comment by ziyaul121** [comment]
Thanks Dear @EarlRamirez, In this exam, may you shine more than your contemporaries. May your efforts be coloured. All the best.

**Comment by ziyaul121** [comment]
Dear All,
Please help me to fix out the issue, It is in production and very pressure on me to sort out it soon.

**Comment by EarlRamirez** [comment]
Thanks for your kind words

**Comment by EarlRamirez** [comment]
I'm still in transit to home, will try to help you from my mobile so bear with me.

**Comment by ziyaul121** [comment]
snipeit]# php upgrade.php

ERROR: This script should not be run as root/admin. Exiting.

So from which ID it need to be run?

**Comment by ziyaul121** [comment]
Dear @snipe ,

Please help me to fix out this issue. This is production server and very pressure on me to get it fixed. 

snipeit]$ php upgrade.php

Step 6: Migrating database:
--
In Connection.php line 647:

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_custom_fields' already exists (SQL: create table models_custom_fields (id int unsigned not null a
uto_increment primary key, asset_model_id int not null, custom_field_id int not null, default_value text null) default character set utf8mb4 collate utf8mb4_unicode_c
i engine = InnoDB)

In PDOStatement.php line 107:

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_custom_fields' already exists

In PDOStatement.php line 105:

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_custom_fields' already exists
