### ISSUE TITLE
Feature: Automate Maintenance statuslabel update

### ISSUE THREAD

**Issue by SjamonDaal** [snipe/snipe-it#5924]
**Feature request.**
When you checkout a asset there are three options for "Checkout to", one of them is "Asset", verry illogical.
A better option shoud be "Supplier", when a asset is returned to the supplier or out for repair, the checkout location can be set to the Supplier.

This way you can better track the location of your asset.

**Comment by dmeltzer** [comment]
If we did something like this, I'd rather tie it into the asset maintenence infrastructure, (maybe add an RMA field to the maintenence?) where during the dates of the maintenece the effective location was shown as the supplier (or manufacturer?)

**Comment by SjamonDaal** [comment]
Hi @dmeltzer,  
Thanks but I don't understand what you mean.  
  
Our intentions is to have the asset checked out to the supplier, if your asset is out for repair the asset status is: Out for Repair, and the asset is checked out to the supplier.  
  
This makes it easy to see where youre asset is located.

**Comment by dmeltzer** [comment]
Hello,

We already have an asset maintences sections 
![image](https://user-images.githubusercontent.com/3803132/43073377-517db390-8e47-11e8-9e37-7c9dece96835.png)

My suggestion is that we extend this to allow for the maintenance to have a location associated with it, and that this overrides the display location (and maybe modifies displayed asset status).  This would give one place to enter details when an asset is being maintained.

**Comment by SjamonDaal** [comment]
Sounds cool, and when the repair is ended by entering the completion date the status automatically turns back to deployed and the location displays the origional deployment location. :)

**Comment by dmeltzer** [comment]
That would be the goal :)

**Comment by SjamonDaal** [comment]
We are currently customizing Snipe-IT for our environment, when all our requirements are added we will see what we can upstream and after that we will take a look at this functionality.  
  
If someone else is able to implement this on a short notice, that would be awesome! :)

**Comment by tothetopgg** [comment]
Would love for this to get added. Currently we have to edit the assets in 2 areas, which feels a little bit messy and is prone to mistakes.

**Comment by fumunda** [comment]
Agreed. This would be a great addition.

**Comment by fumunda** [comment]
Still relevant to me
