### ISSUE TITLE
New Installation

### ISSUE THREAD

**Issue by Saravananadmin** [snipe/snipe-it#593]
Dear Team,

I am tried to install snipe-it in Centos 7 & Ubuntu 14.04. I facing lot of errors while installation. Please share me if you have any installation guide for install this application.

Thanks & Regards
Saravanan V.A

**Comment by snipe** [comment]
Please see the documentation: http://snipeitapp.com/documentation/getting-help/

**Comment by Saravananadmin** [comment]
Hi Friends,

    snipe-it version :- 1.2.5

    Server OS :- Ubuntu 14.04

   I facing issue while install snipe-it application in ubuntu 14.10

    Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing d11wtq/boris (v1.0.8)
    Downloading: connection...    Failed to download d11wtq/boris from dist: The "https://api.github.com/repos/d11wtq/boris/zipball/125dd4e5752639af7678a22ea597115646d89c6e" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing d11wtq/boris (v1.0.8)
    Cloning 125dd4e5752639af7678a22ea597115646d89c6e


   Please share installation guide or video's 

Thanks & Regards 
Saravanan V.A
