### ISSUE TITLE
Stored workflows

### ISSUE THREAD

**Issue by tiberiufilip** [snipe/snipe-it#5931]
Hi,

We are currently testing Snipe-IT solution, but we want to know if it's possible to have a new feature.

We want to force a certain flow for the device status? 
For example, when we buy a device we add it to snipe it with the status New, after that we image it and we set the status Ready, and when it reaches the user we set the status Deployed. 

If a user leaves the company or if the device has a problem we want that certain device to have available only a few statuses, like: Service, Lost, Used or Archived.

Thank you!
Mihai

**Comment by EarlRamirez** [comment]
@tiberiufilip this can be achieved by using status Labels 
_About Status Labels

Status labels are used to describe the various states your assets could be in. They may be out for repair, lost/stolen, etc. You can create new status labels for deployable, pending and archived assets._

![image](https://user-images.githubusercontent.com/12306859/43080695-dee4badc-8ec2-11e8-890d-dfbf1aff9646.png)

**Comment by tiberiufilip** [comment]
@EarlRamirez  Hi and thank you for the reply.
I know how label works, but we want to restrict the label you can choose when you move a laptop from a status to another. 

Like I said, we want a certain device to have available only a few statuses, like: Service, Lost, Used or Archived.

For example, from the image above: if the laptop has status deployed, I want to be able to change status only to Archived or Undeployable.

Thank you!

**Comment by EarlRamirez** [comment]
@tiberiufilip my bad, it is crystal clear now, this will be a feature request, you should have used the **Future Request**, will leave this one for the pros :).

**Comment by SjamonDaal** [comment]
This is cool!  
I don't think it has to be a particular sequence but a function status list that can be created for each "Asset Category".

2 drop-down lists, the first one with existing functions and the right one with exising status labels.

| Function Selection | Status Selection |
| ------------- | ------------- |
| Create Asset      | Pending Acceptance|
| Accepted | Deployed|
| Checkin  | Returned |
| Maintenance | Out for Repair (#5924)|

**Comment by SjamonDaal** [comment]
Yep,
someone out there willing to implement this?

**Comment by tiberiufilip** [comment]
@stale Yes, it is still relevant. Please implement this feature if possible, it will be very useful to us.

**Comment by tiberiufilip** [comment]
Yes, it is still relevant. Please implement this feature if possible, it will be very useful to us.

**Comment by tiberiufilip** [comment]
Hi, 

This was a feature request. Do I need to post this somewhere else? We would appreciate if you would implement it.

Thanks!
