### ISSUE TITLE
ErrorException Trying to get property of non-object in License.php line 231

### ISSUE THREAD

**Issue by hoolius** [snipe/snipe-it#5932]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Error thrown on checkin/checkout of a license to a user. The license is still checked out (or in).

**To Reproduce**
Check out or check in a license to a user.

**Server (please complete the following information):**
 - Snipe-IT Version - 4.6.2
 - OS: Ubuntu 16.04.4 LTS
 - Web Server: Apache
 - PHP Version: 7.0.30-0ubuntu0.16.04.1

**Error Messages**
(1/1) ErrorExceptionTrying to get property of non-object
--
in License.php line 231
at HandleExceptions->handleError(8, 'Trying to get property of non-object', '/var/www/html/app/Models/License.php', 231, array())in License.php line 231
at License->checkin_email()in CheckoutLicenseNotification.php line 84

**Additional context**
- Have upgraded several times (php upgrade.php method)
- I have manually edited data directly in the database

The error is triggered on the line referencing checkin email:
 public function checkin_email()
    {
        return $this->model->category->checkin_email;
    }
[checkouterror.pdf](https://github.com/snipe/snipe-it/files/2219503/checkouterror.pdf)

**Comment by tilldeeke** [comment]
Hey @hoolius!  This should be fixed on develop, after this PR #5898.

**Comment by hoolius** [comment]
Thanks!
