### ISSUE TITLE
the label it is truncated

### ISSUE THREAD

**Issue by andreasoc** [snipe/snipe-it#5935]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Preview of labels on chrome , view the label truncated, before the upgrade work it fine.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/2852354/43086456-a14a9324-8e9d-11e8-8a5a-19ea6795232c.png)

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.0
 - OS: [e.g. Ubuntu, CentOS]Windows Server 2012 R2
 - Web Server: [e.g. Apache, IIS] Apache 2.4.27
 - PHP Version 7.0.23

**Desktop (please complete the following information):**
 - OS: Windows 10 18.03 version
 - Browser Chrome last version
 - Version  67.0.3396.99 

**Error Messages**
nothing

**Additional context**
- Is this a fresh install or an upgrade? upgrade
- What OS and web server you're running Snipe-IT on 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)manual 
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by andreasoc** [comment]
with google inspector on label i view this log
[Deprecation] Styling master document from stylesheets defined in HTML Imports is deprecated. Please refer to https://goo.gl/EGXzpw for possible migration paths.

**Comment by andreasoc** [comment]
is seems that snipe-it add the space for Display the 1D code ..is the same space

**Comment by snipe** [comment]
@andreasoc I can't reproduce this locally. 

<img width="820" alt="screen shot 2018-07-26 at 3 44 41 am" src="https://user-images.githubusercontent.com/197404/43258051-4f8b7914-9086-11e8-90d5-df3f92f311fd.png">

Is there anything in your error logs or browser console?

**Comment by andreasoc** [comment]
try to change your setting like that
![image](https://user-images.githubusercontent.com/2852354/43261147-05da821e-90dc-11e8-8bb5-b87bcce3cf9e.png)

![image](https://user-images.githubusercontent.com/2852354/43261188-245aec4c-90dc-11e8-8857-097ceb00d659.png)

**Comment by andreasoc** [comment]
I am frustrated for this.. i try every every change of size of label , i haven't a solution..

**Comment by andreasoc** [comment]
up to version 4.2.0, the label came out perfect even with these dimensions.
thanks

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)

**Comment by andreasoc** [comment]
yea absolutely! I cant' wait for this bug being resolved..

**Comment by andreasoc** [comment]
yes

**Comment by andreasoc** [comment]
yes
