### ISSUE TITLE
Allow dismissal of notification on a per user basis

### ISSUE THREAD

**Issue by brandenk514** [snipe/snipe-it#5937]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.5.0
 - OS: Ubuntu 18.04 LTS
 - Web Server: Apache
 - PHP Version: 7.0

**Is your feature request related to a problem? Please describe.**
Snipe needs a way to dismiss notifications if they have already been read by the user

**Describe the solution you'd like**
I would like to see a way to dismiss notifications individually from the drop-down menu at the top, with the addition of a clear all button.

**Describe alternatives you've considered**
Notifications are dismissed once the user presses the flag to see the notifications.

**Additional context**
Notification dismissal should only apply to one person and not the whole system.

**Comment by snipe** [comment]
This is a non-trivial change, and while it's something we've been interested in implementing for a while, it would require reworking a lot of how notifications work.
