### ISSUE TITLE
User Location Issue

### ISSUE THREAD

**Issue by smksar** [snipe/snipe-it#5938]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.2
 - OS: Windows
 - Web Server: Wamp 3.3.1
 - PHP Version 7.2.4

**Is your feature request related to a problem? Please describe.**
Our office has 3 different buildings thus we set the user's location as per their building location but I noticed when I log in as a user, in "Edit Your Profile" page, they can simply change their location as they wish.

Under location we have more than just the 3 buildings, such as meeting rooms (to assign assets), store etc (like 20+ not supposed to be user's location but more for asset) and user can see all these and change their location as they wish.

**Describe the solution you'd like**
Is it possible to have an option in the admin settings under General Settings or a new sub group "Users" next to "Groups" icon say something like "Allow user to change location?" checkbox and if it is checked, then the location dropdown in Edit Your Profile page will be removed/hidden? 

Or to have it as a one of group permission settings.
![image](https://user-images.githubusercontent.com/38576928/42608431-3f7c4822-85ba-11e8-9a74-3b8584671098.png)
Option to Grant or Deny "Change Location" ?

**Describe alternatives you've considered**
As this is more of backend I cannot think of alternatives

**Comment by SjamonDaal** [comment]
Note: I actually don't think this is a Issue but a Feature Request.
