### ISSUE TITLE
Upgrade Error

### ISSUE THREAD

**Issue by durrana** [snipe/snipe-it#5939]
#### Please confirm you have done the following before posting your bug report:

- [Yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When running the upgrade I get the following error:

--------------------------------------------------------
Step 6: Migrating database:
--------------------------------------------------------

--
In Connection.php line 647:

  SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name
  'action_logs_target_id_target_type_index' (SQL: alter table `action_logs` a
  dd index `action_logs_target_id_target_type_index`(`target_id`, `target_typ
  e`))

In PDOStatement.php line 107:

  SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name
  'action_logs_target_id_target_type_index'

In PDOStatement.php line 105:

  SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name
  'action_logs_target_id_target_type_index'
**Server (please complete the following information):**
 - Snipe-IT Version V4.6.2
 - OS: Server 2012 R2
 - Web Server: WAMP
 - PHP Version 7.1.19

I am also getting an error message on checking in and out assets.

Thanks

Adam

**Comment by tilldeeke** [comment]
Hey @durrana! 
You'll find a fix on the Common Issues page: https://snipe-it.readme.io/docs/installation-issues#section-duplicate-key-name-action_logs_target_id_target_type_index

**Comment by durrana** [comment]
Hi

Just tried that but get this from MySQL:



Error

SQL query: 


DROP INDEX action_logs_target_id_target_type_index ON action_logs



MySQL said: Documentation 
#1091 - Can't DROP 'action_logs_target_id_target_type_index'; check that column/key exists

Adam

**Comment by tilldeeke** [comment]
Hm, thats strange. Could you run `SHOW INDEX FROM action_logs;` as well and post the result?

**Comment by durrana** [comment]
Hi

Your SQL query has been executed successfully.

SHOW INDEX FROM action_logs



action_logs	0	PRIMARY	1	id	A	4539				BTREE			
action_logs	1	action_logs_thread_id_index	1	thread_id	A	4539			YES	BTREE

**Comment by durrana** [comment]
Step 6: Migrating database:
--------------------------------------------------------

--
In Connection.php line 647:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
  oo long; max key length is 1000 bytes (SQL: alter table `action_logs` add i
  ndex `action_logs_item_type_item_id_action_type_index`(`item_type`, `item_i
  d`, `action_type`))


In PDOStatement.php line 107:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
  oo long; max key length is 1000 bytes


In PDOStatement.php line 105:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t
  oo long; max key length is 1000

**Comment by tilldeeke** [comment]
Aaand the next article from the common issues: https://snipe-it.readme.io/docs/installation-issues#section-specified-key-was-too-long-max-key-length-is-1000-bytes
