### ISSUE TITLE
License Questions and Thoughts

### ISSUE THREAD

**Issue by cobrien165** [snipe/snipe-it#594]
Hello,

First off, I love this tool. It is exactly what I was looking for to start moving away from my giant, unruly, and often outdated spreadsheet. Keep up the great work. 

I have some questions and thoughts about the licenses section. Has anyone requested managing network licenses? I did some quick searching and didn’t find an existing topic yet. One example is that we have networked seats of AutoDesk products and many times we have 8-10 total seats with 15-30 potential users.

I like the process of checking in and out licenses, but am curious of any more functionality being planned for within the seat view. This stems from each seat being a specific entity that is tied to a specific user. If I have 120 Office 2013 licenses, there is no difference between seat 12 and seat 23. Is there any way or a plan to allow that data to be more fluid? Such as:

-Sorting the users alphabetically within the seat view, or generating a user listing for specific software
-Checking a license back in that adds it back to a pool rather than releasing a specific numbered seat
-Generate an email group or listing from the user list of checked out licenses

My final thought is on managing different license versions. Many times I have a static amount of licensing for software with users split on what versions they are running. 20 total AutoCAD licenses with users running versions 2013-2015. Would there be a way to manage a license pool and have different versions within that pool? Currently, how I foresee doing this is listing each version with the same amount of seats and tying users to that, but would ideally like to keep the proper total amount to avoid confusion.
##

**Comment by cobrien165** [comment]
I've just started to use the Accessories section with 1.2.6. This is exactly how software seats should work for the majority of licenses that I work with. A pool of licenses with a list of users associated. Is there any plan to have that option for software licenses or to be able to have it work in tandem with the specific seats?

**Comment by adam820** [comment]
To add some thoughts, we were also just talking about this today, and how it might work. All the licenses should stay together, as they're still software licenses, and should be "checked out" as such. In the case of a network license pool, where we have 8 licenses of something that can run concurrent based on the people who use it, I still want to know the 35 people who "use" those 8 licenses, from a tracking point of view. ("I need to upgrade Software™ v.Foo to Software™ v.Bar, who are the people who use that?")

I would foresee a license "type" field on the New License screen that differentiates between a standalone/retail copy that can be individually allocated, and a network type. On the network type, you still supply the seat amounts, e.g. "8", but with a single license key listed. When you check out a "seat" to a user/machine, the available license count does not decrement, nor does it increment when checking in. The list of people/machines with a checked out license is still maintained, with the history.

**Comment by cobrien165** [comment]
Thanks Adam, I think your idea for the network licenses would be perfect. Across the license types I've dealt with, I'd like to see three different "types" when you make a new license:

1. Stand-alone, assigned seat licenses, like it is currently.
2. Network licenses with static number of seats, but checking out/in doesn't increase or decrease license counts.
3. License pools for large user base installs where seat numbers don't matter. Like I mentioned above, essentially combining the functionality of the new Accessories feature with the detailed info of adding a license.

**Comment by hwongzinio** [comment]
We would like to order this tool but we do not use paypal, seems we are stuck as this is your ONLY form of payment?

**Comment by snipe** [comment]
@hwongzinio you should be able to use a credit card through PayPal, no?

**Comment by hwongzinio** [comment]
Nope, our CC is linked to our paypal merchant account and it deducts merchant credit before charging card, we had to remove the card from our main account. And create a NEW paypal just to do this... very troublesome. Why not also take amazon so people have a choice. ty

**Comment by snipe** [comment]
We've set up non-Paypal payment options. http://snipeitapp.com/hosting/credit-card-sign-up/
