### ISSUE TITLE
Find out Acceptance ID #

### ISSUE THREAD

**Issue by ks9389** [snipe/snipe-it#5941]
Not a bug or issue really; just looking to see if there's something I can do here.

I want to send reminder emails to people that haven't accepted their assets yet. The ID # that is part of the acceptance URL - is there a way I can find out what this is, so that I can send the link back out to users?

Is there an easy way to work out what this would be or is it just a random id generated?

Cheers

**Comment by SjamonDaal** [comment]
This should be a default feature! 👍

**Comment by snipe** [comment]
Duplicate of #2294
