### ISSUE TITLE
customize email

### ISSUE THREAD

**Issue by Ale-gmt** [snipe/snipe-it#5942]
HI,

When an asset is assigned and sends an email to the user to confirm delivery. is it possible to customize the content of the e-mail?

**Comment by SjamonDaal** [comment]
Hi,
There is a feature request for the templates #5748
And I recently posted about EULA Normalization #5933

Need more information? Just ask :)

**Comment by snipe** [comment]
The only thing that's currently customizable (and probably will be for a while) is the EULA, if you use one.

**Comment by snipe** [comment]
Those are all handled via language files. You can change those by modifying the text in the `resources/lang/it/` folder, but bear in mind that those values will be overwritten the next time you update, so you'll have to keep applying your changes.

**Comment by GaoGaoCE** [comment]
> hi, The Eula is OK. Instead, you can customize the text of the email (example: the object of the email-the text-terms of use). I enclose screenshot. ![cattura](https://user-images.githubusercontent.com/41622565/43271837-e419d176-90f8-11e8-947d-1650d6059c1b.PNG)

Hello, how can customize like this ? may you manual ?
