### ISSUE TITLE
Customize "Print all assigned"

### ISSUE THREAD

**Issue by Qatar12345** [snipe/snipe-it#5944]
Please let us know any option for the Customize "Print all assigned"  page.
We need to add my company Logo on the page. When we recovered IT equipment's from the user.

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Qatar12345** [comment]
Customize "Print all assigned"

**Comment by zrlahm** [comment]
Hello, 
i want to import our confirmed text to print all assinged page. is it possible or not ?

**Comment by snipe** [comment]
You can edit the blade file itself, but it’s not currently an option in the app itself.

**Comment by zrlahm** [comment]
how can i find blade file in ubuntu. i am not profesional on ubuntu sorry :(

**Comment by OscarRiveraQIC** [comment]
/var/www/html/snipe-it/resources/views/users/print.blade.php
