### ISSUE TITLE
Feature request: attachment icon on the dashboard of assets, license etc.. 

### ISSUE THREAD

**Issue by andreasoc** [snipe/snipe-it#5948]
**Is your feature request related to a problem? Please describe.**
it would be useful view an icon of attachment, if there is at least one file, in the view of assets, license etc.. 
where? near the asset name and license name ..for me 

**Describe the solution you'd like**
it would be useful view an icon of attachment, if there is at least one file, in the view of assets, license etc.. 
where? near the asset name and license name ..for me 👍

**Comment by snipe** [comment]
What is the specific use case here? That would require additional SQL queries, which we try to avoid unless there's a good use case.

**Comment by andreasoc** [comment]
- when, for example, you update licenses document or service contracts (I use snipe for this), you start loading multiple files in the records, I do not remember where you uploaded them if you do not have a graphic that shows you.

- in general it is convenient to see where there is documentation and where it is missing

**Comment by andreasoc** [comment]
yes!

**Comment by andreasoc** [comment]
yes!
