### ISSUE TITLE
Ldap Authentication

### ISSUE THREAD

**Issue by recep2661** [snipe/snipe-it#5949]
- Snipe-IT Version  Version v4.4.1 - build 3636 (master)
 - OS: [e.g. Ubuntu, server ]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 7

Hello there ,
When authenticating ldap, is it possible to get the users' mail, user name, other information out of password information?
I would like to support you in this regard.

**Comment by samotelf** [comment]
Hello. 
The imported users show you the Display Name, First Name, Last Name, Username and Email.
You can take a look [here](https://social.technet.microsoft.com/wiki/contents/articles/5392.active-directory-ldap-syntax-filters.aspx?Sort=MostRecent) and check the LDAP Filters as it is mentioned in the Snipe-IT Manual.

**Comment by recep2661** [comment]
Hi I want to draw the user's regional department and other information but how do I do that?

**Comment by snipe** [comment]
@recep2661 that's not currently possible.

**Comment by snipe** [comment]
Duplicate of #3486
