### ISSUE TITLE
Internet Explorer Issue

### ISSUE THREAD

**Issue by vberisha01** [snipe/snipe-it#595]
I am unable to login using internet explorer v11. It works fine on Chrome + Firefox.

**Comment by snipe** [comment]
Is this also happening on the demo?

**Comment by snipe** [comment]
Hi @vberisha01 - we're unable to reproduce this issue on our end. What version are you using?

**Comment by vberisha01** [comment]
I am using the latest version -1.2.6. I actually figured out how to fix
this issue - I had to reseed the database.

I appreciate your help.

-Vic

**Comment by Marc127** [comment]
Hi, 
I am having the same issue? Chrome and firefox work ok, but Internet Explorer does not load after entering in login details. I am on v1.2.7.  i'm not sure how to reseed the database if this is the cause?  any tips on how I can resolve the IE login issue?
cheers
-Marc

**Comment by snipe** [comment]
@Marc127 are you able to reproduce this on the demo?
