### ISSUE TITLE
Whoops something went wrong after 4 upgrade

### ISSUE THREAD

**Issue by Arsenal10108** [snipe/snipe-it#5958]
Little back story, I was on 4.4.2 and needed to upgrade to the latest I think it is 4.6.2, I couldn't run php upgrade.php as I was getting a buch of errors so I chown -R (myuser):www-data snipeit folder and then it allowed the upgrade to go through, which brings us to where we are now. 

![image](https://user-images.githubusercontent.com/41116612/43202512-b53a9b34-8fe9-11e8-81a1-cbd67ba227f4.png)

Looks like a typical permissions issue.... HOWEVER, I have tried to reset permission every way I can. 
I have followed the directions in the common issues, it doesn't seem to like any of the permissions.
I have even set the snipeit directory back to root permissions and then changed ownership of just the storage and public uploads folder, it still says permission denied..

here is the permissions of my storage folder  
![image](https://user-images.githubusercontent.com/41116612/43202276-10bd6abe-8fe9-11e8-972f-f2387979023d.png)
My Logs folder is the same, the only thing in there is the laravel.log 
![image](https://user-images.githubusercontent.com/41116612/43202330-38d92092-8fe9-11e8-86de-844d40422ed5.png)

I am Stuck

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running 4.6.6
- Version of PHP you're running 7
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by EarlRamirez** [comment]
chmod 0777 storage should do the trick

**Comment by EarlRamirez** [comment]
@snipe  you beat me to it :), @Arsenal10108 try _chmod -R 0777 storage_

**Comment by Arsenal10108** [comment]
@snipe I think that was exactly the issue, I also changed the snipeit directory owner to www-data:www-data and that seemed to work! I never added ad_admin to the www-data group. I just assumed that was the user that I was using so it could write to it lol. 

@EarlRamirez I am sure that would have also worked but I am just going to stick with what I have for now since its working! thanks for the quick response guys!

**Comment by huangshifang** [comment]
I also use the 4.42 version, but on the Windows platform,the upgrade is smooth, but it is found that the v4.62 can not use the import function, no wrong, it is not reacting after the click, is the state that you have been waiting, It hasn't been reacted for a long time，but I returned to the 4.42 version ， quickly import success .

**Comment by snipe** [comment]
@huangshifang - that issue is unrelated to the original topic of this thread. Please create a new issue.
