### ISSUE TITLE
User with only Audit permissions doesn't have Audit link.

### ISSUE THREAD

**Issue by srazer** [snipe/snipe-it#5961]
#### Please confirm you have done the following before posting your bug report:

- [Error when trying ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
A link to the Bulk Audit screen is not present when user only has Audit permissions.

**To Reproduce**
1. Create a group that only has Grant Audit Permissions.
2. Assign user to only that group.
3. User logs in and doesn't have a link on the nav bar for Bulk Audit.
4. User can go to /hardware/bulkaudit

**Expected behavior**
Audit should show up in the Navigation bar

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.3 - build 3866
 - OS: [e.g. Ubuntu, CentOS] Server 2016
 - Web Server: [e.g. Apache, IIS] IIS
 - PHP Version 7.1.14

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Windows 10
 - Browser [e.g. chrome, safari]  Chrome, IE

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
I enabled debug and got the following error in laravel.log:
[2018-07-25 15:37:43] production.ERROR: Debugbar exception: Route [debugbar.openhandler] not defined.  
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
None
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
Upgrade
- What OS and web server you're running Snipe-IT on
Server 2016 IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual
- Include what you've done so far in the installation, and if you got any error messages along the way.
NA
- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Can you provide a screenshot please

**Comment by srazer** [comment]
![capture2](https://user-images.githubusercontent.com/1082431/43260497-aedf168e-90a7-11e8-90fc-4e09a647624c.JPG)
![capture](https://user-images.githubusercontent.com/1082431/43260498-aee7cb58-90a7-11e8-9841-5ac2634f27cd.JPG)

**Comment by uknzaeinozpas** [comment]
> [2018-07-25 15:37:43] production.ERROR: Debugbar exception: Route [debugbar.openhandler] not defined.
Is probably related to come a cached route, try `php artisan route:clear`
