### ISSUE TITLE
Comma-delimited email addresses no longer work in Settings > Alerts

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#5965]
I think this is due to the new notification system. We'll need to parse that differently, or remove the text/validation that says allows multiple addresses there.

When you try to run any of the alerts with multiple comma delisted addresses set in your alerts, it will trigger:

`Address in mailbox given [system.admin@xxx.com,someone.else@xxx.com] does not comply with RFC 2822, 3.6.2.`

The temporary solve for this is to use only one admin address. If you need it to go to multiple recipients, you should create a distribution list to handle that, if your company policy allows for it.

**Comment by Jarli01** [comment]
Just adding to the pile of proof. 

Address in mailbox given [user@domain.com, user@domain.com] does not comply with RFC 2822, 3.6.2.

**Comment by snipe** [comment]
I believe @inietov is working on this issue.

**Comment by snipe** [comment]
This is merged into dev now
