### ISSUE TITLE
how to remove unwanted fields from asset,accseories,license,consumables tab.

### ISSUE THREAD

**Issue by meenakshi03** [snipe/snipe-it#5967]
**Server (please complete the following information):**
 - Snipe-IT Version - 4.6.3
 - OS: [e.g. Ubuntu, CentOS] - Windows 7
 - Web Server: [e.g. Apache, IIS] - Apache
 - PHP Version - 7

**Is your feature request related to a problem? Please describe.**
yes,getting unwanted fields in the license,accesories,asset tab

**Describe the solution you'd like**
there should be a provision to uncheck the unwanted fields and then they will no longer available in the form

**Describe alternatives you've considered**

**Additional context**

**Comment by snipe** [comment]
That's not currently possible, and isn't on the short term roadmap.

**Comment by MelanyB-N26** [comment]
Will this be done anytime soon? or won't be in any roadmap at all?

**Comment by anurag939** [comment]
Yes feature is very much desirable as we don't want to use Asset Name & is confusing us.

**Comment by berilslv** [comment]
Totally agree with asset name. For example my computer doesn't have name, it only has model;brand;IMEI; and other values, but name.... (My dogs name is Nino) :)
