### ISSUE TITLE
Add "Clone" button in asset creation dialog

### ISSUE THREAD

**Issue by romannazarenko** [snipe/snipe-it#5973]
Snipe-IT version	v4.6.3 build 3866 (g3de1de9dc)
PHP Version	7.1.19
Laravel Version	5.4.35

Add button "Clone" button to asset creation window

If i need create many assets one by one, i need press "save" then press clone. This is not effective, imho, and i spend more time to create assets. 

**Describe alternatives you've considered**
Add clone button beside save button

![untitled](https://user-images.githubusercontent.com/25567563/43271203-9a6e941a-90ff-11e8-8dbc-00fbcdddd55a.jpg)

**Comment by snipe** [comment]
Would this not be solved by the additional of the ability to create multiple of the same asset (with just asset tag and serial being different) that's on develop now, or do you need additional fields that are also different?

**Comment by anmol26s** [comment]
Can I run mysql query to add multiple asset at once in the version < 5.0 for now? If yes please provide me the query? 
Further will this feature be there for accessories too?

**Comment by snipe** [comment]
> Can I run mysql query to add multiple asset at once in the version < 5.0 for now? 

Its your system, you can do whatever you'd like. I'd recommend against it though. Better to use the importer - that's what it's for. That or the API.

> Further will this feature be there for accessories too?

Not for v5, and it's a lower priority than other features we have on deck. Again, I'd suggest the CSV importer or the API.
