### ISSUE TITLE
Display the company in the department dropdown

### ISSUE THREAD

**Issue by Louis-Kre** [snipe/snipe-it#5974]
**Server (please complete the following information):**
 - Snipe-IT Version : 4.5
 - OS: Ubuntu 16.04
 - Web Server: Apache2
 - PHP Version 7.0

**Is your feature request related to a problem? Please describe.**
We manage two companies with snipe-it and both have a simular department structure.
I create a php-script that loads all users from the active-directory and insert them in the correct company and department.
But in snipe-it you have only one list with all departments and you can't identify the company.

**Describe the solution you'd like**
On solution is a short-name on the company (f.e. 3 letters) and this will printed bevor the department-name.
Like so: Company: Demonstration Inc. (Shortcut: DEM)
And the department Maintenance will printed: DEM-Maintenance in the dropdown.

**Describe alternatives you've considered**
One alternative could be the following structure:
Company Name
- Department 1
- Department 2
- Department ...
 Company 2 Name
- Department ...

**Additional context**
no thanks :-D

Thank you for you reading time, I would be glad about an implementation in the next releases.

**Comment by dmeltzer** [comment]
Related Question to be answered while implementing this--In Full multiple company support mode should we scope departments to the company they are associated with?

**Comment by snipe** [comment]
@dmeltzer probably? Maybe? But I could also see it being a pain in the balls to have to recreate every department in each company you manage, which is why I built it unstopped to begin with.

**Comment by Louis-Kre** [comment]
@snipe but the departments in different companies are not the same.
So is a HR-Department in an american company not the same department like a HR in germany.
You have different manager, locations, companies and different users.
