### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by rajasuresh2** [snipe/snipe-it#5976]
#### Please confirm you have done the following before posting your bug report:

- [Yes ] I have enabled debug mode 
- [Yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
SQLSTATE[HY000] [2002] No such file or directory

**To Reproduce**
1. Go to '...' http://localhost/snipeit/public

**Expected behavior**
Should able to show the screen

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version : latest version
 - OS: [e.g. Ubuntu, CentOS]: mac
 - Web Server: [e.g. Apache, IIS]: Apache
 - PHP Version : 7

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] mac book pro
 - Browser [e.g. chrome, safari] safari

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

(1/3) PDOExceptionSQLSTATE[HY000] [2002] No such file or directory
--
in PDOConnection.php line 43
at PDO->__construct('mysql:host=localhost;port=3306;dbname=snipeit', 'snipe_user', 'Password!', array(0, 2, 0, false, false))in PDOConnection.php line 43
at PDOConnection->__construct('mysql:host=localhost;port=3306;dbname=snipeit', 'snipe_user', 'Password!', array(0, 2, 0, false, false))in Connector.php line 65
at Connector->createPdoConnection('mysql:host=localhost;port=3306;dbname=snipeit', 'snipe_user', 'Password!', array(0, 2, 0, false, false))in Connector.php line 44
at Connector->createConnection('mysql:host=localhost;port=3306;dbname=snipeit', array('driver' => 'mysql', 'host' => 'localhost', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipe_user', 'password' => 'Password!', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => 'InnoDB', 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array(), 'name' => 'mysql'), array(0, 2, 0, false, false))in MySqlConnector.php line 24
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => 'localhost', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipe_user', 'password' => 'Password!', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => 'InnoDB', 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array(), 'name' => 'mysql'))in ConnectionFactory.php line 183
at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
at call_user_func(object(Closure))in Connection.php line 883
at Connection->getPdo()in Connection.php line 904
at Connection->getReadPdo()in Connection.php line 392
at Connection->getPdoForSelect(true)in Connection.php line 318
at Connection->Illuminate\Database\{closure}('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in Connection.php line 640
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php line 607
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php line 326
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in MySqlBuilder.php line 18
at MySqlBuilder->hasTable('users')in Facade.php line 221
at Facade::__callStatic('hasTable', array('users'))in Setting.php line 68
at Setting::setupCompleted()in CheckForSetup.php line 22
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

(2/3) PDOExceptionSQLSTATE[HY000] [2002] No such file or directory
--
in PDOConnection.php line 47
at PDOConnection->__construct('mysql:host=localhost;port=3306;dbname=snipeit', 'snipe_user', 'Password!', array(0, 2, 0, false, false))in Connector.php line 65
at Connector->createPdoConnection('mysql:host=localhost;port=3306;dbname=snipeit', 'snipe_user', 'Password!', array(0, 2, 0, false, false))in Connector.php line 44
at Connector->createConnection('mysql:host=localhost;port=3306;dbname=snipeit', array('driver' => 'mysql', 'host' => 'localhost', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipe_user', 'password' => 'Password!', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => 'InnoDB', 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array(), 'name' => 'mysql'), array(0, 2, 0, false, false))in MySqlConnector.php line 24
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => 'localhost', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipe_user', 'password' => 'Password!', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => 'InnoDB', 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array(), 'name' => 'mysql'))in ConnectionFactory.php line 183
at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
at call_user_func(object(Closure))in Connection.php line 883
at Connection->getPdo()in Connection.php line 904
at Connection->getReadPdo()in Connection.php line 392
at Connection->getPdoForSelect(true)in Connection.php line 318
at Connection->Illuminate\Database\{closure}('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in Connection.php line 640
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php line 607
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php line 326
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in MySqlBuilder.php line 18
at MySqlBuilder->hasTable('users')in Facade.php line 221
at Facade::__callStatic('hasTable', array('users'))in Setting.php line 68
at Setting::setupCompleted()in CheckForSetup.php line 22
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

3/3) QueryExceptionSQLSTATE[HY000] [2002] No such file or directory (SQL: select * from information_schema.tables where table_schema = snipeit and table_name = users)
--
in Connection.php line 647
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php line 607
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php line 326
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in MySqlBuilder.php line 18
at MySqlBuilder->hasTable('users')in Facade.php line 221
at Facade::__callStatic('hasTable', array('users'))in Setting.php line 68
at Setting::setupCompleted()in CheckForSetup.php line 22
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

**Additional context**
- Is this a fresh install or an upgrade? fresh install
- What OS and web server you're running Snipe-IT on MacOS High Sierra 10.13.5
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

http://localhost/snipeit/public
1. if I put DB_HOST in .env as 127.0.0.1 then redirecting the https://apples-macbook-pro-4.local/snipe-it/public/setup and page is
 
Not Found
The requested URL /snipe-it/public/setup was not found on this server.

1. if I put DB_HOST in .env as localhost then SQLSTATE error is coming
 
Not Found
The requested URL /snipe-it/public/setup was not found on this server.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Louis-Kre** [comment]
I have never tried to run snipe-it on macos...
But it looks like a problem with the installed dependencies.

How did you installed snipeit? With the installer.sh? or via git clone?

Did you installed all requirements from https://snipe-it.readme.io/v4.6.2/docs/requirements ?

**Comment by snipe** [comment]
`public` should not be in the URL.

**Comment by snipe** [comment]
It's in the documentation.

https://snipe-it.readme.io/docs/configuration#section-required-basic-app-settings

<img width="768" alt="screen shot 2018-07-27 at 1 00 27 am" src="https://user-images.githubusercontent.com/197404/43309055-81e24b74-9138-11e8-8295-1cc6ad8a6987.png">

The phrase public should not be in the URL, because that should be set as the Document Root. If you want to run Snipe=IT in a subdirectory, you need to follow these additional instructions. https://snipe-it.readme.io/docs/subdirectories

**Comment by rajasuresh2** [comment]
Thank you very much for the quick response.

I had tried both http://localhost and http://127.0.0.1

There is no public in the url too.

**Comment by snipe** [comment]
> if I put DB_HOST in .env as 127.0.0.1 then redirecting the https://apples-macbook-pro-4.local/snipe-it/public/setup and page is

Again, `public` should not be in the URL. Based on your original ticket, it is.

**Comment by rajasuresh2** [comment]
Hi,

Thanks for the response, when i configure without public then i am getting
below error.  And also i have attached configuration files for your
reference.

D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It
should be set to the public directory.

Paths and respective files:

1. /Library/Server/Web/Data/Sites/Default/snipe-it/.env
2. /private/etc/apache2/extra/httpd-vhosts.conf
3. /Library/Server/Web/Config/apache2/httpd_server_app.conf

Thanks
Suresh

**Comment by EarlRamirez** [comment]
can you share the content of _/private/etc/apache2/extra/httpd-vhosts.conf_?

**Comment by rajasuresh2** [comment]
Here the content of the file */private/etc/apache2/extra/httpd-vhosts.conf*

# Virtual Hosts

#

# Required modules: mod_log_config


# If you want to maintain multiple domains/hostnames on your

# machine you can setup VirtualHost containers for them. Most configurations

# use only name-based virtual hosts so the server doesn't need to worry
about

# IP addresses. This is indicated by the asterisks in the directives below.

#

# Please see the documentation at

# <URL:http://httpd.apache.org/docs/2.4/vhosts/>

# for further details before you try to setup virtual hosts.

#

# You may use the command line option '-S' to verify your virtual host

# configuration.


#

# VirtualHost example:

# Almost any Apache directive may go into a VirtualHost container.

# The first VirtualHost section is used for all requests that do not

# match a ServerName or ServerAlias in any <VirtualHost> block.

#

#<VirtualHost *:80>

#    ServerAdmin webmaster@dummy-host.example.com

#    DocumentRoot "/usr/docs/dummy-host.example.com"

#    ServerName dummy-host.example.com

#    ServerAlias www.dummy-host.example.com

#    ErrorLog "/private/var/log/apache2/dummy-host.example.com-error_log"

#    CustomLog "/private/var/log/apache2/dummy-host.example.com-access_log"
common

#</VirtualHost>


#<VirtualHost *:80>

#    ServerAdmin webmaster@dummy-host2.example.com

#    DocumentRoot "/usr/docs/dummy-host2.example.com"

#    ServerName dummy-host2.example.com

#    ErrorLog "/private/var/log/apache2/dummy-host2.example.com-error_log"

    CustomLog "/private/var/log/apache2/dummy-host2.example.com-access_log"
common

#</VirtualHost>


<VirtualHost *:80>

    <Directory "/Library/Server/Web/Data/Sites/Default/snipe-it/">

        Allow From All

        AllowOverride All

        Options +Indexes

    </Directory>

    DocumentRoot /Library/Server/Web/Data/Sites/Default/snipe-it/

    ServerName http://localhost

    ServerAlias www.localhost

</VirtualHost>

**Comment by rajasuresh2** [comment]
Hi,

Please help me.

Thanks
Suresh

**Comment by rajasuresh2** [comment]
Yes still my snipe-it is not Up in my mac laptop, appreciate if you could
help me.

Thanks
Suresh

**Comment by rajasuresh2** [comment]
Please can any one help me on this topic?

**Comment by rajasuresh2** [comment]
Actually issue is there still but unfortunately i didnt get any solution.
May be we can close this. thanks

**Comment by rajasuresh2** [comment]
Thank you  very much for the quick response
