### ISSUE TITLE
When checkout asset, its state is not changed to 'assigned'

### ISSUE THREAD

**Issue by diwanicki** [snipe/snipe-it#598]
Noticed this behavior today when updating some records. v 1.2.5

**Comment by violetrain** [comment]
As far as I can see in the database's "status_labels" table the state "assigned" does not exist (if you don't create it manually). 
But I agree with you that this should be changed.

**Comment by snipe** [comment]
@diwanicki can you describe what you mean? When you checkout an asset, it becomes "deployed" and that's where you find it in the sidenav.

**Comment by snipe** [comment]
Hi @diwanicki - any updates?

**Comment by snipe** [comment]
Is this still an issue? I'm still not clear on what you mean here.

When an asset is assigned to someone, it becomes "Deployed". A status label is not required (or used) for this state, since it's always the same.
