### ISSUE TITLE
Request Datacenter/ Rack functionality

### ISSUE THREAD

**Issue by didentifier** [snipe/snipe-it#5985]
- Snipe-IT latest Version 
 - OS: CentOS
 - Web Server:  Apache

Hello Guys,

I loved the application to be honest however it misses a very important functionality for me. Datacenter and rack management are important for a lot of companies.

You could be adding another category of datacenter or something in which you may be able to add racks of specific rows that can be populated with assets and also a picture of the rack. Also this can be expanded to maintenance notifications to appropriate departments by the appropriate departments if that makes sense at all

Thank you for your great work though guys I would very much like to also give help

**Comment by snipe** [comment]
Is there a reason why you can't use Location for Rack / Datacenter?

**Comment by didentifier** [comment]
In my opinion racks and locations are 2 different things, some times when you have 2-3 or more racks and datacenters you want to have a way to find on which rack an Asset is. for example The Asset X34  is in location New York 2  on the Rack A1 row U13.

**Comment by EarlRamirez** [comment]
What I believe you can do is use **netbox** and integrate Snipe-IT via an API.

**Comment by snipe** [comment]
> for example The Asset X34 is in location New York 2 on the Rack A1 row U13

Right, but you could use sub-locations for that.

- New York 2
    - A1 Row U13

Alternatively you could use custom fields

**Comment by snipe** [comment]
I'm not averse to creating a Datacenter object, it's just that it seems like it would effectively just mimic locations.

**Comment by didentifier** [comment]
I believe you are right but this is not a feature it is indeed a workaround

**Comment by snipe** [comment]
@didentifier if the behavior would be exactly the same as locations, it's not really a workaround. It feels wrong to create new functionality that exactly reproduces existing functionality and just giving it a different name.

**Comment by didentifier** [comment]
I still disagree with you.

For the Data center yes the location and sub location would help, but for the rack management it doesn't  help a lot an infrastructure engineer.

Please have a look at the second feature in the link below, and I think we will be on the same page, if not no worries I can spend some time implement it for myself, play around since the project is open source and everyone is happy.

https://www.easydcim.com/features

**Comment by hafidzi** [comment]
@didentifier or, you could just setup custom field for rack under the datacenter/server category that have details.

**Comment by albercuba** [comment]
This is actually one of the thing keeping me back from moving to Snipe-IT. I've used Ralph and GLPI and they both have the Datacenter/Rack functionality.

Something like this:
https://glpi-project.org/wp-content/uploads/2018/03/dcim_racks.jpg

Also the options to add network segments, domains,

**Comment by jorenlove** [comment]
Snipe-IT looks awesome, but I'd plus 1 the desire for this. Tracking of power circuits at the data center would good too.

**Comment by colttt** [comment]
Any progress on this? this it quiet important for us too, and may a showstopper
