### ISSUE TITLE
Logging in as a non-activated user gives unclear error message

### ISSUE THREAD

**Issue by dmeltzer** [snipe/snipe-it#5989]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Currently, if you create a user and do not activate them, when the user tries to login they are returned back to the login screen with a generic "username or password is incorrect" message.  We should provide feedback that instead their account is not activated for logins.

**To Reproduce**
1. Go to Login page
2. Attempt to login as an unactivated user
3. See the "username or password is incorrect error message returned

**Expected behavior**
An error message is displaying indicating the user is not activated.

**Comment by snipe** [comment]
I opted for a more generic message so that we do not disclose what accounts are currently registered, for security purposes. Same reason we don’t specify whether your username or password is wrong. Could present the opportunity for spearphishing, etc.

**Comment by snipe** [comment]
This has been fixed
