### ISSUE TITLE
RedHat Document Update

### ISSUE THREAD

**Issue by collinsg** [snipe/snipe-it#5992]
Just a heads up that php has changed location to /etc/opt/rh/rh-php71/php.ini  and the http server is now in /opt/rh/httpd24/root/etc/httpd.  With the latest versions of php (56 and newer) you need the http24 apache server on Redhat.  The snipe team needs to add that to their documentation.

**Comment by EarlRamirez** [comment]
@collinsg thanks for the heads up, what version of RHEL are you using? That location sounds like you are using the Software Collection Library (SCL)

**Comment by collinsg** [comment]
RHEL 7.5 and yes, it is the software collection Library
