### ISSUE TITLE
Snipe IT slow loading

### ISSUE THREAD

**Issue by kumori2412** [snipe/snipe-it#5999]
Hello guys,

I have installed snipe-it on Xampp (Windows Server 2012)
Following is the version details of the components
PHP 7.2.7
Apache/2.4.33 

The website loads quite slowly because I have installed snipe-it in an closed environment where there is no Internet available. (actually we have own proxy server that didn't allow most URLs)
I think when the webpage loads, it looks for few connections to google APIS, jquery,...
Because our proxy server didn't allow these URLs, so it will take huge time to load

I'm wondering Is there anyway I can pass those URLs connection when start our website?
Any pointers would be really helpful.

**Comment by snipe** [comment]
Did you uncheck the "This install can load scripts from the outside world" box in Settings?
