### ISSUE TITLE
logon password 

### ISSUE THREAD

**Issue by elmxmo** [snipe/snipe-it#600]
how to I change user's password?

**Comment by madd15** [comment]
Are you changing your password or another user?

**Comment by elmxmo** [comment]
Just trying to log in for the first time. I only have one user account which can be seen in phpMyAdmin console. How can I reset that user’s password without having email configured?

**Comment by snipe** [comment]
If you don't have any production data in there yet, you should drop your DB tables and re-run the install. Without email support, there's not going to be a way to change a password without being logged in. The passwords are salted and hashed in the database, so just changing them manually in the DB won't work.
