### ISSUE TITLE
Audit over API does not set next audit date in database

### ISSUE THREAD

**Issue by jazz-o-mat** [snipe/snipe-it#6004]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When i do an Audit over GUI, next audit date will shown in the asset table view.
When i audit over API, it is not shown.

The output:
{"status":"success","messages":"Asset audit successfully logged.","payload":{"asset_tag":"00000016","note":"","next_audit_date":{"datetime":"2019-07-30 00:00:00","formatted":"30.07.2019 00:00"}

But the table field in GUI stays empty.

**To Reproduce**
1. Go to 'Assets/Bulk audit"
2. Click on 'Audit for an asset'
3. Go to 'Assets/List"
4. Search for "this asset"
5.  Look at "Next Audit Date" - filled
6.  Run curl with:
curl https://assets.qa.server.com/api/v1/hardware/audit -H "Authorization: Bearer  eyJ0eXAi...iUYG3wIfcY" -H "Content-Type: application/json" --request POST --data '{"asset_tag":"00000016","location_id":"1"}'
{"status":"success","messages":"Asset audit successfully logged.","payload":{"asset_tag":"00000016","note":"","next_audit_date":{"datetime":"2019-07-30 00:00:00","formatted":"30.07.2019 00:00"}}}
7: Look at "Next Audit Date" - empty

**Expected behavior**
"Next Audit Date" should be filled

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.3 - build 3866 (master)
 - OS: [CentOS]
 - Web Server: [Apache]
 - PHP Version 7.0.31

**Comment by snipe** [comment]
The two behave exactly the same, the difference is that the front-end pre-populates the next audit date. If you pass a next_audit_date via the API, that will be stored.
