### ISSUE TITLE
Feature Request: Better support for multiple images of an asset.

### ISSUE THREAD

**Issue by tylerk9** [snipe/snipe-it#6006]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.3
 - OS: [e.g. Ubuntu, CentOS] CentOS
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7

**Is your feature request related to a problem? Please describe.**
A lot of times our team tries to upload multiple images to an asset when entering items. I have noticed only one of the images actually saves to the asset. I understand you can open the asset later then go to the files tab and upload more images that way, but explaining this to employees makes it much more difficult and I am hoping for a more stream-lined solution.

**Describe the solution you'd like**
Ability to upload multiple images from the "Create Asset" page.

**Describe alternatives you've considered**
Creating the asset, then going to the files tab and pressing upload files. Takes too long and shouldn't have to be an additional step.

**Additional context**
The medical industry our company works with has a lot of large and oddly shaped items we upload to Snipe-IT. Because of this, we like having images of items at different angles/viewpoints. It is currently difficult to upload and view multiple images on a certain asset.

**Comment by snipe** [comment]
@tylerk9 - that's just not how they're meant to work. The asset image is just that - one single image. Anything else attached to it gets saved as files. Those files may or may not be images. It's unlikely we would change this any time soon, as it seems to work for most folks, and would require a pretty huge code and UI change.
