### ISSUE TITLE
Requestable Assets - Add dates requested for check-out option

### ISSUE THREAD

**Issue by tsbadam** [snipe/snipe-it#6007]
**Server (please complete the following information):**
 - Snipe-IT Version 4.4.1
 - OS: [e.g. Ubuntu, CentOS] Server 2008
 - Web Server: [e.g. Apache, IIS] IIS
 - PHP Version 7.2.4

**Is your feature request related to a problem? Please describe.** I'd like when a user tries to request an asset that they can put the date they need to checkout the asset (example: August 1st - August 14th), that way if they have a request in for Asset 1234 then someone else can't request the same asset. Example: Today is July 30th. User 1 wants Asset 1234 from August 1st - 14th and requests it today. On July 31st, User 2 requests the asset from July 31st - August 2nd. Because User 2 is requesting the asset BEFORE user 1, he will get it checkout out to him but it overlaps when user 1 wants it and user 1 requested it first so he should get it first and user 2's request should be rejected because the asset wouldn't be available during that time frame. I hope that makes sense :)

**Describe the solution you'd like** I would like it if the user can put in a time frame of when they need the asset so another user can't request the same asset during that timeframe.

**Describe alternatives you've considered** Only other way I can think of to fix it with the current setup is to check out the asset early, but then there is a timeframe that nobody would be able to check it out even though its not really being used. Seems like wasted time. 

**Additional context**

**Comment by viclou** [comment]
+1
