### ISSUE TITLE
Whoops error on checkin or checkout

### ISSUE THREAD

**Issue by tamasberesoebb** [snipe/snipe-it#6008]
- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Checking out an asset results in a 500. The asset is actually checked out when I refresh the page.
Same thing happens when I cancel the checkout.

**To Reproduce**
1. Go to requestable page
2. Click on check out
3. 500 page loads after a few seconds
4. Refresh page
5. Asset is checked out

**Expected behavior**
Asset checkout should work.

**Server (please complete the following information):**
 - Snipe-IT Version 
Version v4.4.2 - build 3666 (master)

**Additional context**
- Is this a fresh install or an upgrade? 
This is a fresh install, was never upgraded. I see other tickets here, where people had problems upgrading, but this was with a fresh install.

**Comment by EarlRamirez** [comment]
@tamasberesoebb can you enable debugging mode and share those errors with us?

**Comment by EarlRamirez** [comment]
@tamasberesoebb basically complete the template so that we are in a better position to assist you.

**Comment by snipe** [comment]
This is usually a misconfiguration in your email server settings, or an invalid slack integration. 
https://snipe-it.readme.io/docs/common-issues#section-whoops-error-on-checkincheckout
