### ISSUE TITLE
Does anyone see any problem auto-updating snipe + mysql containers via watchtower?

### ISSUE THREAD

**Issue by ovizii** [snipe/snipe-it#6009]
Watchtower: https://hub.docker.com/r/v2tec/watchtower/

This is a general inquiry hence I didn't provide any server details. I'm running snipe + mysql according to your docker instructions and things work really well. 

The images used by these two containers are:
mysql:5.6 
snipe/snipe-it 

I don't see any problems with mysql since I am sticking to the 5.6 versions but not sure about snipe.  I think if snipe auto-updates to say v. 5 things might break so I am wondering why there's no tag like: v4 for example? https://hub.docker.com/r/snipe/snipe-it/tags/ (I only see very specific tags here like 4.6.3) 

I assume if I use snipe-it:latest I might end up with a potential v5. 

Can anyone give some feedback on this?

**Comment by snipe** [comment]
I don't know anything about watchtower, so I can't speak to that.

>  so I am wondering why there's no tag like: v4 for example

I'm not sure what you're asking for here. The tags correspond to Snipe-IT version numbers. 

> I assume if I use snipe-it:latest I might end up with a potential v5.

v5 of Snipe-IT, or v5 or mysql (or something else)? v5 of Snipe-IT is on develop. As long as you don't pull develop, you'll have what's currently table in the v4 line, until v5 gets merged into master.

**Comment by ovizii** [comment]
Thanks for the reply. let me try and clarify your questions: 

> so I am wondering why there's no tag like: v4 for example
> 
> I'm not sure what you're asking for here. The tags correspond to Snipe-IT version numbers.

Take another example, i.e. mysql. here we have tags like: 5 or 5.6 or 5.7 thus making sure that I stay on the selected version. So from my perspective, a tag for snipe-it called 4 would make sense as that makes me always stay on version 4. 

This would that would enable me to automate the updating of these 2 containers. and use: 
mysql:5.6
snipe/snipe-it:4

But its not important, I thought maybe someone had already thought to use watchtower.
