### ISSUE TITLE
better LDAP connector - code suggestion inside

### ISSUE THREAD

**Issue by realPilotfish** [snipe/snipe-it#6010]
**Server (please complete the following information):**
 - Snipe-IT Version v4.6.3 
 - OS: Debian 9.3
 - Web Server: Apache 2.4.25-3
 - PHP Version PHP 7.0.27-0+deb9u1

**Is your feature request related to a problem? Please describe.**
Users cannot login by uid using openldap

**Describe the solution you'd like**
It is common pratice to do a ldap-search by user-provided login-string and ldap-field before actually binding. In this way you can log in by any field you like. Usually this is uid, could be by email oder cn of course,
OpenLDAP does not allow to bind by uid also.

**Describe alternatives you've considered**
We could log in by cn, but all other systems require the uid so this would be confusing.

**Additional context**
The proposed change is easy to implement. I did this already for our installation:
In file app/Models/Ldap.php change findAndBindUserLdap. 

Insert the following code to line 93:

```
       if (!$ldapbind = @ldap_bind($connection)) {
            return false;
        }

        $filterQuery = "(".$settings->ldap_auth_filter_query . "=" . $username .")";
        $results = ldap_search($connection, $baseDn, $filterQuery);
        $users = ldap_get_entries($connection,$results);

        if ($users['count']<1) {
                throw new Exception('Could not find a user matching filter!');
                return false;
        }

        $userDn = $users[0]['dn'];

```

and remove the following line
$filterQuery = $settings->ldap_auth_filter_query . $username;

There should be some more checks and maybe a config option to enable this because it is not needed for AD operation.

**Comment by snipe** [comment]
I'm not able to reproduce your original issue. As long as you have `uid=` in your LDAP Auth Query, you should be able to login via uid. In fact, it's expected that you would. But if you want to login with something else, you can change it in your Admin Settings.

**Comment by realPilotfish** [comment]
In my experience, vanilla OpenLDAP does not allow to bind with anything else but with the dn which usually is based on cn and not uid. 
Testing on my standard openldap-servers confirms this. Maybe there's an openldap addon or special config, correct me if this is the case.
 
This is why usually clients (like redmine, mediawiki or samba) do a two-step search and bind.

Here is a good explanation:
[https://connect2id.com/products/ldapauth/auth-explained](https://connect2id.com/products/ldapauth/auth-explained)

I know Active Directory behaves differently.

**Comment by realPilotfish** [comment]
I think it is still relevant. A proper LDAP implementation should be the goal.

**Comment by colin-campbell** [comment]
For maximum compatibility, LDAP authentication should really always bind with the full user DN as  specified in the record. In particular nested OUs are not handled at all by:

`$ldap_username_field.'='.$username.','.$settings->ldap_basedn;`

For LDAP (as opposed to AD) Should the user record not always be retrieved by the admin bind and the authentication bind done by:

`$userDn = $users[0]['dn'];`  ?
