### ISSUE TITLE
Uploaded Files shows wrong "Created at" date

### ISSUE THREAD

**Issue by kchagnon-snowbound** [snipe/snipe-it#6011]
**Describe the bug**
The "Created at" date shown on the Files tab of the View Asset page shows the date the asset was created instead of the date the file was uploaded.

**To Reproduce**
1. Upload a new file to an Asset
2. "Created at" date will show the date/time that the actual asset was created instead of the date/time the file was uploaded.

**Expected behavior**
"Created at" date should show the date/time that the file was added/uploaded to the asset.

**Screenshots**
Attached screen shot showing 3 files all uploaded at different times but all show the same "Created at" date/time.  Attached a second screenshot of that asset's "Details" page showing that the "Created at" date on the Files page is using the same date as the "Created at" on the Details Asset page.

**Server (please complete the following information):**
 - Snipe-IT Version 4.5.0
 - OS: Ubuntu
![bug](https://user-images.githubusercontent.com/18011929/43467020-cd2859ec-94ae-11e8-8cbe-cc47bad2d5bd.PNG)
![compare](https://user-images.githubusercontent.com/18011929/43467044-da702526-94ae-11e8-845e-bba618a05136.PNG)

**Desktop (please complete the following information):**
 - OS: Win 10 Build 1709
 - Browser Chrome
 - Version 67.0.3396.99

**Comment by EarlRamirez** [comment]
@kchagnon-snowbound strange, I don't even see the Created date under v4.6.3,
