### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by cube98** [snipe/snipe-it#6012]
I am at the stage of 'Pre-Flight &Setup' where I enter my Snipe-IT url and should be taken to the Pre-Flight screen. However when I try this my browser pops up with this:
![capture](https://user-images.githubusercontent.com/41964777/43470918-adf7db3c-94e1-11e8-81cf-2b447a8c114b.PNG)

I have went through all the previous instructions from the installation manual. I would really appreciate some help. I am new to all of this and I'm a little bit lost

 - Snipe-IT Version: 4.6.3
 - OS: Windows 10
 - Web Server: IIS
 - PHP Version: 7.2.8

 - Browser: Chrome

**Comment by EarlRamirez** [comment]
@cube98 what happens when you try to use the IP address of the server?

**Comment by cube98** [comment]
I get a web page with the message:
This page isn’t working
192.168.0.4 didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by EarlRamirez** [comment]
This is purely an IIS configuration, are you able to hit the default test page? This error **ERR_NAME_NOT_RESOLVED** tell me that you most probably do not have a binding for the server or the server is not even listening, though I can be wrong.

**Comment by EarlRamirez** [comment]
Since you can hit the default page, your server is up and running, if you are using hostname you will need to have that name resolved via the IP address, this can be achieved from hosts file _c:\windows\system32\etc\drives\hosts_. Verify that your path to the snipeit directory is properly configured.

**Comment by cube98** [comment]
Done as you said with changing the hosts file. Now I am getting this page
![capture](https://user-images.githubusercontent.com/41964777/43569066-55ae9f3a-962e-11e8-90b6-96cd2c28a822.PNG)

According to the link at the bottom "This problem occurs because the ApplicationHost.config file or the Web.config file contains a malformed XML element."

This is the code in the web.config file:

<configuration>
  <system.webServer>
    <rewrite>
      <rules>
        <rule name="Imported Rule 1" stopProcessing="true">
          <match url="^(.*)/$" ignoreCase="false" />
          <conditions>
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
          </conditions>
          <action type="Redirect" redirectType="Permanent" url="/{R:1}" />
        </rule>
        <rule name="Imported Rule 2" stopProcessing="true">
          <match url="^" ignoreCase="false" />
          <conditions>
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
          </conditions>
          <action type="Rewrite" url="index.php" />
        </rule>
      </rules>
    </rewrite>
    <staticContent>
        <remove fileExtension=".woff2" />
        <mimeMap fileExtension=".woff2" mimeType="application/x-font-woff2" />
    </staticContent>
  </system.webServer>
</configuration>

**Comment by cube98** [comment]
`<configuration>
  <system.webServer>
    <rewrite>
      <rules>
        <rule name="Imported Rule 1" stopProcessing="true">
          <match url="^(.*)/$" ignoreCase="false" />
          <conditions>
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
          </conditions>
          <action type="Redirect" redirectType="Permanent" url="/{R:1}" />
        </rule>
        <rule name="Imported Rule 2" stopProcessing="true">
          <match url="^" ignoreCase="false" />
          <conditions>
            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" ignoreCase="false" negate="true" />
            <add input="{REQUEST_FILENAME}" matchType="IsFile" ignoreCase="false" negate="true" />
          </conditions>
          <action type="Rewrite" url="index.php" />
        </rule>
      </rules>
    </rewrite>
    <staticContent>
        <remove fileExtension=".woff2" />
        <mimeMap fileExtension=".woff2" mimeType="application/x-font-woff2" />
    </staticContent>
  </system.webServer>
</configuration>
`

**Comment by cube98** [comment]
Here is more details in case it helps
![capture](https://user-images.githubusercontent.com/41964777/43581207-0d454664-9650-11e8-86b9-3a46d8e7104d.PNG)

**Comment by EarlRamirez** [comment]
@cube98 will have to check this during the weekend and report back, you did use the docs provided correct?

**Comment by cube98** [comment]
Correct

**Comment by snazy2000** [comment]
Do you have URL Rewrite installed?

**Comment by cube98** [comment]
I do @snazy2000

**Comment by karrynotme** [comment]
Hi there, I got the same issues, may I know how could you fixed it?
