### ISSUE TITLE
Make Accessory Note field visible somewhere after checkout

### ISSUE THREAD

**Issue by kchagnon-snowbound** [snipe/snipe-it#6013]
**Server (please complete the following information):**
 - Snipe-IT Version  4.5.0
 - OS: Ubuntu

**Is your feature request related to a problem? Please describe.**
The Notes field has been added to the checkout form for Accessories (request #5607) however the information entered in the Notes field cannot be seen anywhere.  As an example, I have set up Laptop Locks as an Accessory.  When I check one out to a user, in the Notes field I have entered the combination for the lock issued to that user.  After clicking Checkout to assign to the user, I do not see a way to see that Notes field again and therefore cannot see the combination for that particular lock,

**Describe the solution you'd like**
When you click on the Accessory Name it pulls up a screen showing all the users who have that accessory checked out (see attached screenshot)
![accessory](https://user-images.githubusercontent.com/18011929/43472281-110fd7fa-94bb-11e8-9262-4f008e22a78e.PNG)
.  Currently the screen only shows User and Actions.  Perhaps showing the Notes field on this screen would suffice.

**Describe alternatives you've considered**
I cannot think of an alternative but any way that the Notes field can be viewed would be fine.

**Additional context**

**Comment by EarlRamirez** [comment]
@kchagnon-snowbound this can be achieved by toggling the Notes from hide/show menu.
![image](https://user-images.githubusercontent.com/12306859/43474161-1869b4bc-94c0-11e8-9511-a9e0856a3abd.png)

**Comment by kchagnon-snowbound** [comment]
@EarlRamirez Thank you for your reply.  I had initially checked that but am not seeing it.  I am using v. 4.5.0 and just realized 4.6.0 has been released.  Maybe that is in the new release?

**Comment by EarlRamirez** [comment]
@kchagnon-snowbound, my bad this will actually be a **feature request**
