### ISSUE TITLE
Asset Tag field, searchable but not selectable (as 'Company' or 'Model')

### ISSUE THREAD

**Issue by ivanlinares** [snipe/snipe-it#6014]
**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.3
 - OS: [CentOS]
 - Web Server: [Apache]
 - PHP Version 7.x

Hi, I'm a new user of Snipe-IT and found your system fantastic! I'd like to suggest the following feature: 

I'm assigning "asset tags" to all my assets and I don't know which asset tags I've already assigned, would be very cool to have the text box to behave like the company or model text box with the restriction to not possible selecting one, that way as I'm typing I know what tags were created already and won't duplicate any.

You see, I'm assigning tags with the following structure, take for example **MQBPPJLAPSIS001**

**MQB** - Acronym to our company name (Movil QroBus SA de CV)
**PPJ** - The location (Patio PaJaros)
**LAP** - Asset Type (LAPtop)
**SIS** - The department to which belongs (Sistemas)
**001** - Sequential number in case of any repeated assets in the same Company, Location, Asset Type and Department exists.

When typing up to the last field (sequential number) the system will search and will popup with the searchable text box behavior, and I will add the 002 tag in case 001 was already there...

Thank you!

**Additional context**
![create asset](https://user-images.githubusercontent.com/22164094/43490410-1e287868-94e6-11e8-9e3c-6d92300a1c0a.PNG)

**Comment by EarlRamirez** [comment]
@ivanlinares  the **Asset Tag** is already unique; therefore, it will not allow you to create a duplicate Asset Tag, so you don't have to worry about duplicates.

**Comment by ivanlinares** [comment]
Hi Earl, I know, but I don't know which ones I already created, that's why the field should yield the already stored when entering new ones (like excel autocomplete), otherwise I must open one window with the assets listing to view the assets already created and the main window where I create new ones.

**Comment by snipe** [comment]
@ivanlinares you're combining a lot of different information into your asset tags. I'm not sure how the system would know what the next tag is.

**Comment by ivanlinares** [comment]
@snipe I don't want the system to guess what the next tag is, and yes, aren't my Asset tags impressive and smart? I can add also the year it was purchased and on and on and on, but I personally think that this information is enough instead of asset tags like: "000000000123", wth is that?!

I just want the field to behave like a search text box (model, company, etc) with a slight variation to not possibly select the previous created tags...


Thank you

**Comment by ivanlinares** [comment]
Simple, when you type in the asset tag box you will see the results like the company and model text boxes behave, but with the difference that the results can't be selected...
