### ISSUE TITLE
Assets assigned to locations are not showing up.

### ISSUE THREAD

**Issue by 17achisolm** [snipe/snipe-it#6022]
I have an asset that is assigned to a room with a building set the parent location. When i am in the locations it says the room has 27 assets assigned to it. When i click the location to see what assets are assigned to it, only 1 unit is listed not 27.

**Comment by snipe** [comment]
Please answer the questions in the issue template.

**Comment by smksar** [comment]
There is possibility that it is being filtered, could you clear the search field and click refresh?
![image](https://user-images.githubusercontent.com/38576928/43527098-5c0a521c-95d8-11e8-98ed-5bbf12374e3a.png)
