### ISSUE TITLE
Overview with yet not accepted assets

### ISSUE THREAD

**Issue by chrstmnn** [snipe/snipe-it#6025]
**Is your feature request related to a problem? Please describe.**
Today when I check out an asset to an user, the user gets a mail in order to accept the asset. In the asset history I can see, whether the asset has been accepted yet.
By now I cannot see, which assets are not accepted yet although the are checked out.

**Describe the solution you'd like**
Create an overview that lists all checked out assets that are not accepted by now.
Furthermore an alert would be nice, if an acceptance is pending more than 24 hours.

**Describe alternatives you've considered**
Maintain paper protocols (print all assigned) and check whether they have returned yet.

**Comment by snipe** [comment]
https://demo.snipeitapp.com/reports/unaccepted_assets
