### ISSUE TITLE
Supplier View should have a URL Column

### ISSUE THREAD

**Issue by thesurfaceofthevoid** [snipe/snipe-it#6028]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.3 build 3866 (g3de1de9dc)
 - OS: Ubuntu 18.10
 - Web Server: Apache
 - PHP Version: 7.2.7-0ubuntu0.18.04.2

**Is your feature request related to a problem? Please describe.**
Due to many/most suppliers being websites (BH Photo, Amazon, Ingram, etc), it would be nice to have an option to see URL column.

**Describe the solution you'd like**
A URL column is selectable.

**Describe alternatives you've considered**
Googling an address, having your own browser bookmarks, or simply clicking deeper into Snipe to acquire a URL is only a minor inconvenience.

**Additional context**
<img width="1668" alt="screen shot 2018-08-01 at 19 32 17" src="https://user-images.githubusercontent.com/16564027/43554360-dc9640ec-95c1-11e8-9bb6-fb9941b3f8dd.png">

**Comment by thesurfaceofthevoid** [comment]
Well, that was simply incredible speed for such a minor request. Thank you very much.

**Comment by snipe** [comment]
No problem - it won't be out in a release until v5 comes out though. It's only on develop for now.
