### ISSUE TITLE
Email takes a long time to send

### ISSUE THREAD

**Issue by tcintura** [snipe/snipe-it#6032]
#### Expected Behavior (or desired behavior if a feature request)

Processes involving sending emails are fast

-----

#### Actual Behavior

**Processes involving sending emails takes a long time to be completed (1.5 - 2 min)**

-----

#### Please confirm you have done the following before posting your bug report:
Yes, I did all of it.
-----
#### Provide answers to these questions:

- Fresh installation
- Snipe-IT v4.4.2 build 3666 (gaa5003d29)
- PHP Version  7.0.30
- CentOs 7 & Chrome
- Github recommended
- I do not get any error

Hi everybody, 

Please some one help me! 

regards,
tcintura

**Comment by EarlRamirez** [comment]
@tcintura I am using both _on-premise_ and _hosted_ and I do not see such delays when I send a test notification on both of the solutions that I am using, additionally, when I generate emails from the CLI on the _on-premise_ box I receive them almost instantly. 
Are you seeing the same behaviour when you send email from the setup that you are using?  It is a bit challenging to _help you_ when you did not provide us with details, e.g. what are you using for your email notification etc.

**Comment by tcintura** [comment]
HI @EarlRamirez I'm using exchange server

**Comment by snipe** [comment]
There's nothing on our end that would cause that. My guess would be a firewall issue or something on the exchange server's side.

**Comment by tcintura** [comment]
Which driver do you recommend, currently i'm using **SMTP**. When I change it to **MAIL** driver the test mail is approved and the process  is very fast but nothing appears on my inbox.

**Comment by EarlRamirez** [comment]
I don't use exchange but one of the setup I used Postfix as a relay and configured Snipe-IT to use Postfix and that was okay but I think the emails were being duplicated. You will need to diagnose this by checking the logs, with Mail you may need to enable a few SELinux Boolean you may want to check that as well
