### ISSUE TITLE
Default Location

### ISSUE THREAD

**Issue by avinashramsunder** [snipe/snipe-it#6035]
Hi

I am unable to generate a custom report with Default Location.

Would this be a feature going forward?

![capture](https://user-images.githubusercontent.com/42037212/43588019-ddac47a6-966b-11e8-8abe-b1c6c1e7d8dd.PNG)

**Comment by snipe** [comment]
This is already a feature.

<img width="258" alt="screen shot 2018-08-02 at 9 26 35 am" src="https://user-images.githubusercontent.com/197404/43597198-355da458-9636-11e8-832c-30918e2835da.png">

https://demo.snipeitapp.com/reports/custom
