### ISSUE TITLE
[Feature Request] Right Click Menu

### ISSUE THREAD

**Issue by memtech3** [snipe/snipe-it#6036]
**Is your feature request related to a problem? Please describe.**
Habit of right clicking to get what I want
**Describe the solution you'd like**
I would like to see right click menus for actions in snipe-it like adding, deleting, editing, duplicating etc

**Some ideas I have found online are**
https://www.sitepoint.com/building-custom-right-click-context-menu-javascript/
https://www.w3schools.com/jsref/event_oncontextmenu.asp

**Comment by snipe** [comment]
I'm not particularly interested in home-growing context menus that we'll need to force into working nicely with bootstrap tables. There is a bootstrap table extension (although it's old, and the demo is 404ing now), but I don't know if it works with modern versions of bootstrap table, or what it might conflict with in terms of our other plugins. 

Additionally, from a UIX perspective, I find right-click menus enormously frustrating, so this would come in as a very low priority feature.

**Comment by memtech3** [comment]
I think that the right click menu is a great idea because I'm always trying to right click on things just from habbit. m3 right clicks, m3 gets menu

**Comment by snipe** [comment]
I understand that you feel that way, however I disagree.

**Comment by memtech3** [comment]
If I make the UI will you implement it

**Comment by snipe** [comment]
The UI easy. It's testing it with every browser and with all of our bootstrap table extensions that is harder and very time consuming.

**Comment by snipe** [comment]
Plus it would need a setting to turn it on or off, as many people find overriding the browser's default right click behavior annoying.
