### ISSUE TITLE
User import via CSV sends emails

### ISSUE THREAD

**Issue by kgmoore431** [snipe/snipe-it#6042]
#### Expected Behavior (or desired behavior if a feature request)

Importing users via CSV should not send emails to users or should have a configuration field / flag to  allow state to be set for importing as inactive/active.

-----

#### Actual Behavior
when importing a user list via CSV import all imported users received an email with a username and password.  The emails were unexpected and the accounts were not active so the email was reported as spam by many users.

-----

#### Please confirm you have done the following before posting your bug report:

- [ X ] I have enabled debug mode 
- [ X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh
- Version of Snipe-IT you're running
Hosted at snipe-it.io

**Comment by snipe** [comment]
Hi @kgmoore431 - that's a known issue (sorry about that.) 

I think probably the best way for us to handle this is to provide a checkbox for "activate user (allow them to login)" which triggers another checkbox for "send emails".

@dmeltzer is this something you can tackle, or should I take a look?

**Comment by snipe** [comment]
I believe this has been fixed on master and develop
