### ISSUE TITLE
LDAP sync on CLI fails

### ISSUE THREAD

**Issue by xpfgsyb** [snipe/snipe-it#6044]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
If I try to run ``php artisan snipeit:ldap-sync --summary -vvv`` from root I get the error posted below in the error messages section.

I'm not sure when exactly it started to fail. It may have been at the point when we upgraded from 4.3.0 to 4.5.0 with the ``php upgrade.php`` method or when we updated Debian from 8 to 9.

**To Reproduce**
1. SSH to the server
2. cd to the root directory of Snipe-IT, in our case ``cd /var/www/asset-management``
3. Run ``php artisan snipeit:ldap-sync --summary -vvv``

**Expected behavior**
Sync LDAP (Active Directory) to the people in Snipe-IT.

**Screenshots**
None, see error output.

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.3, 4.5.0
 - OS: Debian 9.5
 - Web Server: Apache 2.4.25
 - PHP Version 5.6.36 (php5-ldap is installed and enabled, I mention it as one of the common problems refers to it)

**Desktop (please complete the following information):**
Not relevant

**Smartphone (please complete the following information):**
Not relevant

**Error Messages**

> In Ldap.php line 42:
>                                                            
>   [Symfony\Component\Debug\Exception\FatalThrowableError]  
>   Call to undefined function App\Models\ldap_connect()     
> 
> Exception trace:
>  App\Models\Ldap::connectToLdap() at /var/www/asset-management/app/Console/Commands/LdapSync.php:57
>  App\Console\Commands\LdapSync->handle() at n/a:n/a
>  call_user_func_array() at /var/www/asset-management/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
>  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /var/www/asset-management/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
>  Illuminate\Container\BoundMethod::callBoundMethod() at /var/www/asset-management/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
>  Illuminate\Container\BoundMethod::call() at /var/www/asset-management/vendor/laravel/framework/src/Illuminate/Container/Container.php:539
>  Illuminate\Container\Container->call() at /var/www/asset-management/vendor/laravel/framework/src/Illuminate/Console/Command.php:182
>  Illuminate\Console\Command->execute() at /var/www/asset-management/vendor/symfony/console/Command/Command.php:252
>  Symfony\Component\Console\Command\Command->run() at /var/www/asset-management/vendor/laravel/framework/src/Illuminate/Console/Command.php:167
>  Illuminate\Console\Command->run() at /var/www/asset-management/vendor/symfony/console/Application.php:946
>  Symfony\Component\Console\Application->doRunCommand() at /var/www/asset-management/vendor/symfony/console/Application.php:248
>  Symfony\Component\Console\Application->doRun() at /var/www/asset-management/vendor/symfony/console/Application.php:148
>  Symfony\Component\Console\Application->run() at /var/www/asset-management/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122
>  Illuminate\Foundation\Console\Kernel->handle() at /var/www/asset-management/artisan:35

**Additional context**
- Is this a fresh install or an upgrade? Upgraded; upgrade path: 3.6.6 -> 4.1.11 -> 4.3.0 -> 4.5.0 -> 4.6.3
- What OS and web server you're running Snipe-IT on. See server section.
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc). Unsure, one of the first two.
- Indicate whether or not you've manually edited any data directly in the database. No manual edits in the DB.

**Comment by snazy2000** [comment]
Doesn't look like you have the PHP LDAP module installed.

**Comment by xpfgsyb** [comment]
I created a new file with phpinfo() in the snipe it directory and checked the ldap module. It shows that ldap support is enabled.
It does work in the GUI, but not on CLI. Are there differences between these two methods?

**Comment by jwhulette** [comment]
I think on some linux installs have a different binary for the CLI version. Run php -m from the command line to see if the LDAP module shows as being installed.

**Comment by xpfgsyb** [comment]
Thank you very much for the hint, @jwhulette !

LDAP were missing in the CLI version. While we use PHP 5 in Apache, PHP 7 were used on the CLI. I guess that happened while the upgrade from Debian 8 to 9. So installing the missing LDAP and MySQL module fixed my problem and the LDAP importer does work again. Thank you!
