### ISSUE TITLE
Upgrading snipe-it: returned error "PHP Fatal error:  Allowed memory size of 524288000 bytes exhausted" at php artisan migrate

### ISSUE THREAD

**Issue by Axcendio** [snipe/snipe-it#6048]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
It is not actually a bug. 
But when I try to migrate db by "php artisan migrate" I keep on receiving error "PHP Fatal error:  Allowed memory size of 524288000 bytes exhausted"

**To Reproduce**
1. run: php artisan migrate
2.  Say yes for affirmation:
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

3. It will then returned memory being exhausted again:

PHP Fatal error:  Allowed memory size of 524288000 bytes exhausted (tried to allocate 100 bytes) in /usr/local/snipeit430test/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 301

**Expected behavior**
DB migrated without error.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version - 4.3.0
 - OS: CentOS 7.5
 - Web Server: apache-2.4.33
 - PHP Version: php-5.6.36

**Desktop (please complete the following information):**
Not related
**Smartphone (please complete the following information):**
Not related

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? Upgrade
- What OS and web server you're running Snipe-IT on 
 --Snipe-IT Version - 4.3.0
 --OS: CentOS 7.5
 --Web Server: apache-2.4.33
 --PHP Version: php-5.6.36

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) GIT
- Include what you've done so far in the installation, and if you got any error messages along the way.

git pull
install composer
php composer.phar install --prefer-source
php composer.phar dump-autoload
php artisan migrate - Stuck here due to error as per explained above.

- Indicate whether or not you've manually edited any data directly in the database
Nope

I increased the memory_limit in my php.ini to 1024M.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by EarlRamirez** [comment]
@Axcendio  maybe you want to try **php upgrade.php** this will clear cache and configs that _might_ resolve your issue

**Comment by Axcendio** [comment]
Thanks Earl,
When it comes down to migrating database. It came out with the same error.
I am suspecting there's something wrong with the DB now.
--------------------------------------------------------
Step 6: Migrating database:
--------------------------------------------------------

PHP Fatal error:  Allowed memory size of 524288000 bytes exhausted (tried to allocate 91 bytes) in /usr/local/snipe-it/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 142
--

**Comment by Axcendio** [comment]
I think I'll compile a new php 7 instead

**Comment by Axcendio** [comment]
YES! Sad to say it's the DB. Which I did not think was the source of the issue. Some admin.
I upgraded my php to php 7.0.24. Remove all custom field in the assets table which has NO data inside.
Some admin.
--------------------------------------------------------
Step 6: Migrating database:
--------------------------------------------------------


In Connection.php line 647:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_custom_fields' already exists (SQL: create table `models_custom_fields` (`id` int unsigned not null a
  uto_increment primary key, `asset_model_id` int not null, `custom_field_id` int not null, `default_value` text null) default character set utf8mb4 collate utf8mb4_unicode_c
  i engine = InnoDB)


In PDOStatement.php line 107:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_custom_fields' already exists


In PDOStatement.php line 105:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_custom_fields' already exists

**Comment by Axcendio** [comment]
Now I got this after I drop the table "models_custom_fields"
Step 6: Migrating database:
--------------------------------------------------------

--
In Connection.php line 647:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `action_logs` add index `action_logs_item
  _type_item_id_action_type_index`(`item_type`, `item_id`, `action_type`))


In PDOStatement.php line 107:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes


In PDOStatement.php line 105:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

**Comment by Axcendio** [comment]
I changed the mysql engine in config/database.php from InnoDB to 

'engine' => 'InnoDB ROW_FORMAT=DYNAMIC'

Solve the last issue.
💃
