### ISSUE TITLE
requestable assets are not "clickable" (v1.2.6)

### ISSUE THREAD

**Issue by diwanicki** [snipe/snipe-it#605]
The requestable assets view does not allow selection of any of the assets - it is a static table view. Serial number field could be a hyperlink, at a minimum.

**Comment by snipe** [comment]
Do you mean from the non-admin view or the admin view?

**Comment by diwanicki** [comment]
from the admin view - I don't use the non-admin features (yet)

**Comment by snipe** [comment]
I'm not sure what you mean. The requestable assets (when you click on it in the left-side nav) looks just like the other screens. 

![screen shot 2015-03-04 at 1 38 47 pm](https://cloud.githubusercontent.com/assets/197404/6494055/e0d2be08-c273-11e4-9f5c-f0ab976fe75f.png)

**Comment by diwanicki** [comment]
I am not getting that behavior...  Snipe-IT (v1.2.6-12)
![screen shot 2015-03-04 at 4 40 26 pm](https://cloud.githubusercontent.com/assets/6108682/6494203/04a538e6-c28e-11e4-9fb8-9007bd587f05.jpg)

**Comment by snipe** [comment]
That's the user view - click on Assets and look in the expanded menu for "Requestable"
