### ISSUE TITLE
Email and username format - FirstName, Last Initial

### ISSUE THREAD

**Issue by grandmamoses** [snipe/snipe-it#6053]
**Server (please complete the following information):**
 - Snipe-IT Version  - 4.6.3
 - OS: [e.g. Ubuntu, CentOS] Ubuntu
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.2

**Describe the solution you'd like**
At our company we use a username and email address format of FirstnameLastInitial@company.com.
e.g. John Smith would be Johns@company.com. Could this format please be added as an option in settings?

Many thanks for a great project!

**Comment by EarlRamirez** [comment]
@grandmamoses we have a variety of email formats and they are all able to receive emails, just curious to know what challenges are you facing?

**Comment by grandmamoses** [comment]
Hi Earl

Thanks for the response.

I don't have an issue per se, however I'm not sure what issues I may have by not being able to select the correct **email** and **username** formats in the **General Settings Page**. The format we use at our company is not available in the dropdowns. We use FirstnameLastInitial for the username as well as the email address which is not an option in the dropdowns for both settings, and was wondering if this format could be added? In our company for eg. user John Smith would have username in Active Directory (LDAP is working :-)) of JohnS and email address of johns@example.com.

![image](https://user-images.githubusercontent.com/22368225/44305740-ee5c4a80-a37f-11e8-899b-23a8e9a7aea5.png)

Thanks!

**Comment by grandmamoses** [comment]
Commenting to keep this active.
