### ISSUE TITLE
Cloning model with Image

### ISSUE THREAD

**Issue by smksar** [snipe/snipe-it#6056]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.3
 - OS: Windows 10
 - Web Server: WAMP 3
 - PHP Version 7.2.4

**Is your feature request related to a problem? Please describe.**
Currently when cloning a model that has image, the cloned model will not copy the image but only the fields information

**Describe the solution you'd like**
When cloning a model that has image attached to it, the cloned model will also have the same image attach to it.

**Describe alternatives you've considered**
Currently must attach back manually the same image of the same model to the cloned model.

**Comment by Bluesmell** [comment]
Server (please complete the following information):
Snipe-IT Version v4.6.5 build 3907 (g7a44da85a)
OS: ubuntu16.04.1
Web Server: Apache (all installed with install.sh)
PHP Version 7.1.22-1

Is your feature request related to a problem? Please describe:
Currently when cloning a model that has image, the cloned model will not copy the image but only the fields information

Describe the solution you'd like:
When cloning a model that has image attached to it, the cloned model will also have the same image attach to it.

Describe alternatives you've considered
Currently must attach back manually the same image of the same model to the cloned model.

(So I have same problem that smksar) 
How to fix?
