### ISSUE TITLE
Accept EULA and Sign for asset right at check-out instead of email

### ISSUE THREAD

**Issue by mmahoney812** [snipe/snipe-it#6058]
Could it be possible for someone to sign and accept the EULA right at check-out instead of them having to do it from their emails? We need to make sure that people accept and sign before the equipment leaves the building.

**Comment by leebaggaley** [comment]
👍

**Comment by IxFail** [comment]
Already issue/request of this #3750

**Comment by nopanik42** [comment]
+1 !! Please that would be so useful...

Thanks!

**Comment by leebaggaley** [comment]
yes please

**Comment by IxFail** [comment]
Yes

**Comment by snipe** [comment]
Sorry, just realized this is a dupe.
