### ISSUE TITLE
Dashboard button not clickable in navigation pane on left side between specific pixel widths

### ISSUE THREAD

**Issue by n-v-o** [snipe/snipe-it#6059]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
A repost of #5085 that was auto closed, but still a bug. Apologies for duplicating the post, not sure if the original poster is still active.

For some reason the dashboard button in the navigation pane cannot be clicked on in specific circumstances; when you set a browser width between 975 and 1360 pixels wide, you cannot click the Dashboard. (see screenshots). I don't believe the resolution set on the display makes a difference.

**To Reproduce**
Set browser width to any width between 975 and 1359, and you can't click the "Dashboard" button between the nav pane. at 974 pixels and below, it works, and at 1360 pixels and above, it works. Also setting it to full screen seems to make it work in most cases too. To see you browser width, you can use this tool : [Browser Size Checker](https://www.internetmarketingninjas.com/seo-tools/whats-my-browser-size/)

As a reference point, I'm running a 2560x1440 display. 

**Expected behavior**
you should be able to click the navigation pane, in the GUI.
**Screenshots**
974 Pixels Wide
![974 pixels wide](https://user-images.githubusercontent.com/29506123/43872135-2ac753e6-9b4e-11e8-84a7-6738385126ab.png)

975 Pixels Wide
![975 pixels wide](https://user-images.githubusercontent.com/29506123/43872138-2f2effa6-9b4e-11e8-9330-e06fac88f256.png)

1359 Pixels Wide
![1359 pixels wide](https://user-images.githubusercontent.com/29506123/43872141-31272392-9b4e-11e8-8a22-1960966fee90.png)

1360 Pixels Wide
![1360 pixels wide](https://user-images.githubusercontent.com/29506123/43872142-32c3e384-9b4e-11e8-96aa-0cb6ea3c3477.png)

**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.3
 - OS: Windows 10 and Windows Server 2012 R2
 - Web Server:IIS
 - PHP Version: 7.2.7

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows and Mac
 - Browser: Chrome and Firefox
 - Version: latest

**Error Messages**
no error messages - but this is reproducible in the demo.

**Additional context**

There are a couple key graphical components. at the 1360 pixels mark, that is when the top nav-pane switches to a single line.  At the 975 mark, the nav pane slides down introducing a big space above the Dashboard button. I tried to highlight these in the screenshots.

**Comment by snipe** [comment]
That's helpful, thanks!

**Comment by leebaggaley** [comment]
Hi, I dont know whether this is related or not but on a mobile (im using Samsung J5 at the moment) when in an asset none of the buttons (Asserts, licenses, history files etc...) are clickable unless i rotate the screen into landscape mode, one in landscape its fine. Just thought this may be useful to know
