### ISSUE TITLE
Expiration or Due Date

### ISSUE THREAD

**Issue by dguedry** [snipe/snipe-it#606]
In this brave new world of Cyber Security, it'd be really awesome if there were some sort of mechanism to add a due date during checkout (i.e. the date you HAVE to bring it back to IT to get scanned/hardened).  What would be super-cool is to have emails sent to that user every day (annoy them enough so they'll bring it back)

Thanks for all of your hard work.  This is a really great app!
##

**Comment by dguedry** [comment]
Maybe even a category for sanitized (meaning it's a USB or something that has been wiped and  is definitely clean) and scanned (meaning it has files but IT needs to scan it every so often to make sure they're free of any newly-introduced vulnerabilities).  I don't know... you guys seem to have a knack for making inventory mgmt work.  Maybe you have an idea on how this would work best.

**Comment by jahrj** [comment]
I agree, this would be an amazing feature for how we are using Snipe-IT.

**Comment by snipe** [comment]
Just so I'm clear, we already have expected_checkin as an option. You're looking for email alerts?

<img width="785" alt="screen shot 2015-12-01 at 3 11 59 pm" src="https://cloud.githubusercontent.com/assets/197404/11517378/eab8adf6-983d-11e5-8cee-e47793736a54.png">

**Comment by dguedry** [comment]
Yeah, was looking for email alerts to nag users before the expiration date occurred.

**Comment by snipe** [comment]
Who would we be nagging though? The admins, or the person to whom the asset is checked out?

**Comment by Marklange** [comment]
I Agree this would greatly extend the usefulness to my organization. I would also be happy with a "you are late" email as well that went out to the lend user.
