### ISSUE TITLE
Error Run "sudo php artisan key:generate"

### ISSUE THREAD

**Issue by momaydopod** [snipe/snipe-it#6060]
#### Expected Behavior (or desired behavior if a feature request)

localadmin@THACINVEN:/var/www/snipe-it$ sudo php artisan key:generate
PHP Warning:  require(/var/www/snipe-it/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/snipe-it/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/snipe-it/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/snipe-it/bootstrap/autoload.php on line 17

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? >> Fresh install
- Version of Snipe-IT you're running >> Lasted version on Git
- Version of PHP you're running >> PHP Version 7.1.17
- Version of MySQL/MariaDB you're running  >> 
- What OS and web server you're running Snipe-IT on >> Ubuntu 17.0
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by mmahoney812** [comment]
Did you run composer first?

**Comment by momaydopod** [comment]
Once i run composer It’s happen error .

**Comment by mmahoney812** [comment]
[https://snipe-it.readme.io/docs/install-dependencies]

**Comment by momaydopod** [comment]
Cannot install composer

`root@INVEN:/var/www/snipe-it$ sudo curl -sS https://getcomposer.org/in                                        staller | php
All settings correct for using Composer
The installation directory "/var/www/snipe-it" is not writable
root@INVEN:/var/www/snipe-it$ curl -sS https://getcomposer.org/install                                        er | php
All settings correct for using Composer
The installation directory "/var/www/snipe-it" is not writable
`

**Comment by momaydopod** [comment]
I use this command is working fine


`root@INVEN:/$ curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/var/www/snipe-it --filename=composer
All settings correct for using Composer
Downloading...

Composer (version 1.7.1) successfully installed to: /var/www/snipe-it/composer
Use it: php /var/www/snipe-it/composer
`

**Comment by momaydopod** [comment]
when i run got error


`root@INVEN:/var/www/snipe-it$ sudo composer install --no-dev –prefer-source
[sudo] password for localadmin:
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Invalid argument –prefer-source. Use "composer require –prefer-source" instead to add packages to your composer.json.`


I following https://websiteforstudents.com/how-to-install-php-composer-on-ububuntu-16-04-17-10-18-04/

**Comment by momaydopod** [comment]
Hi 

Which CENOS version support ?

**Comment by momaydopod** [comment]
This is file bootstrap/auto.php


`<?php

define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| Register The Composer Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader
| for our application. We just need to utilize it! We'll require it
| into the script here so that we do not have to worry about the
| loading of any our classes "manually". Feels great to relax.
|
*/

require __DIR__.'/../autoload.php';

/*
|--------------------------------------------------------------------------
| Include The Compiled Class File
|--------------------------------------------------------------------------
|
| To dramatically increase your application's performance, you may use a
| compiled class file which contains all of the classes commonly used
| by a request. The Artisan "optimize" is used to create this file.
|
*/

$compiledPath = __DIR__.'/cache/compiled.php';

if (file_exists($compiledPath)) {
    require $compiledPath;
}
`

**Comment by EarlRamirez** [comment]
@momaydopod both CentOS 6 and 7 are supported
