### ISSUE TITLE
Assigned User Group cannot be deselected

### ISSUE THREAD

**Issue by chrstmnn** [snipe/snipe-it#6061]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
If a user has a user group assigned, I cannot deselect the group.

**To Reproduce**
1. Create one user group.
2. Create a new user and assign this user group.
3. Open update page for user.
4. Try to deselect assigned user group. --> impossible

**Expected behavior**
If I click in the blank field oder again on the selected user group, the user group is deselected.

**Server (please complete the following information):**
 - Snipe-IT Version 4.2.0
 - OS: hosted version by snipe

**Desktop (please complete the following information):**
 - OS: macOS HighSierra
 - Browser Safari
 - Version 11.1.2

**Comment by smksar** [comment]
Due to it being a multi select box, try Ctrl+click on the group name to deselect then save.

**Comment by snipe** [comment]
@smksar is correct. As with all multi-select lists, ctrl+click will select/deselect.
