### ISSUE TITLE
LDAP Sync stopped working - ldap_search(): Search: Invalid DN syntax

### ISSUE THREAD

**Issue by PhilippNorres** [snipe/snipe-it#6063]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
LDAP Sync stopped working. getting "ldap_search(): Search: Invalid DN syntax". Worked once and after deleting all people and redoing I got this error.

**To Reproduce**
1. Go to 'People'
2. Click on 'LDAP Sync'
3. Click on 'Synchronize'

**Expected behavior**
Importing Active Directory Users

**Screenshots**
![2](https://user-images.githubusercontent.com/42238409/43894319-0111075c-9bd2-11e8-8b70-899f57eddeb9.JPG)
![1](https://user-images.githubusercontent.com/42238409/43894320-0147283c-9bd2-11e8-8ef2-6f1a4cc0137f.JPG)

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.3 - build 3866
 - OS: UBuntu 16.04 LTS x64
 - Web Server: Apache
 - PHP Version 7.0.30-0ubuntu0.16.04.1

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Firefox
 - Version 61.0.1

**Error Messages**
(1/1)  ErrorException                     ldap_search(): Search: Invalid DN syntax
--
in Ldap.php line 262
at HandleExceptions->handleError(2, 'ldap_search(): Search: Invalid DN syntax', '/var/www/snipeit/app/Models/Ldap.php', 262, array('base_dn' => 'NORRES Germany', 'ldapconn' => resource, 'ldap_bind' => null, 'filter' => '&(cn=*)', 'page_size' => 500, 'cookie' => '', 'result_set' => array(), 'global_count' => 0, 'ldap_paging' => true))
at ldap_search(resource, 'NORRES Germany', '(&(cn=*))')in Ldap.php line 262
at Ldap::findLdapUsers('NORRES Germany')in LdapSync.php line 128
at LdapSync->handle()

**Additional context**
- Is this a fresh install or an upgrade?  
Fresh Install
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
GIT
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by jwhulette** [comment]
Try using just **cn=*** as the filter.

**Comment by PhilippNorres** [comment]
Thank you but it won´t change something.
Is there a way the database or cache have a problem? This sync worked for the first time but I had to many users so I decided to delete all and now I´m in this situation.

![grafik](https://user-images.githubusercontent.com/42238409/44193144-338b3d00-a132-11e8-8d8c-209e60894132.png)

**Comment by jwhulette** [comment]
Try putting just cn=*, no parentheses or ampersand. So the only thing in the filter field is cn=*

**Comment by PhilippNorres** [comment]
Nothing changed :-/

![grafik](https://user-images.githubusercontent.com/42238409/44208700-76183e00-a161-11e8-8edf-dbb3295a452f.png)

**Comment by jwhulette** [comment]
I think the issue might be your base bind dn. In the error the base bind dn does not have the string you put in the form field. Does the test button on the page work? Are you able to connect with the user?

**Comment by PhilippNorres** [comment]
Yes the test buttons both works. Is there a Cache which have to be deleted also?

I used:
composer dump-autoload
composer clear-compiled
php artisan config:clear
php artisan view:clear
php artisan cache:clear
php artisan route:clear

but composer clear-compiled do not work.

**Comment by jwhulette** [comment]
@PhilippNorres Your base_dn in your error shows "NORRES Germany", which does not seem correct. Your base_dn should be something like, dc=example,dc=com. And in your configuration I don't see NORRES Germany anywhere on the screen. So I would check your database, settings table, ldap_basedn field to to make sure they match with your settings. As far as I know the LDAP fields are not cached.

**Comment by kgronn** [comment]
I have the same issue and unable to get the Base_DN to change. It has locked it self on a test OU. Cannot find where to change it. No matter what I write in Search filter and Base_DN it still adds the test OU in front. I need to get rid of DC=ED, but don't know how.

The Sync worked fine once and then when we tried to do a resync I get this error;

at HandleExceptions->handleError(2, 'ldap_search(): Search: No such object', '/var/www/snipeit/app/Models/Ldap.php', 265, array('base_dn' => 'dc=ED,dc=
