### ISSUE TITLE
Extracting user-signed EULA

### ISSUE THREAD

**Issue by musayev-io** [snipe/snipe-it#6065]
Is it possible to extract the user-signed EULA upon asset checkout? 
If this is not a current feature, is this a feature request on the roadmap?

Thanks!

**Comment by jspieldenner** [comment]
To whom this may concern:

We have elected to not proceed with SnipeIT solely based on the fact that a
(EULA+Signature) document was not able to be extracted, rather these
documents (EULA and Signature) were saved separately, hence presumably
void. Accordingly, for our purposes this ticket is no longer relevant.
However, if you (your team) ever add the feature to "extract signed EULAs",
we would love to roll it out!

I hope this helps!


Respectfully,

*James M. Spieldenner*
*Network Technician I*
[image: VAE Logo]
6225 Brandon Avenue, Suite 230
Springfield, Virginia 22150
Direct: (614) 453-5781
Email: james.spieldenner@vaeit.com
Website: www.vaeit.com

**Comment by steineracedo** [comment]
Hi @snipe I'll like to keep this feature request opened, in our case we need to print the letter that the user digitally signed due to HR folks ask for it. Seems that the way it worked now it only allows to see the user signature only in the asset history and that is not enough as evidence.

**Comment by steineracedo** [comment]
Hi Snipe please keep this opened, this is still needed

**Comment by cellenburg** [comment]
@snipe Any update on this? This would be critical to our business function of proving that the user accepted a EULA with their signature.

**Comment by dominikborkowski** [comment]
Would love to see this as a feature, especially for assets that have been checked out and are no longer on premises. Our recurring asset audits require either the presence of an asset, or a signed form with a signature. 

If we could print out the generated EULAs with the signatures on them, that would satisfy the audit requirements.

Thanks!
