### ISSUE TITLE
 QueryException could not find driver (SQL: select * from information_schema.tables where table_schema = snipeit_db and table_name = users)

### ISSUE THREAD

**Issue by gmb07** [snipe/snipe-it#6066]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

Hi Snipe, hope you can help me here again. I probably missed some settings. I'm done with the composer install and I'm about to setup the snipeit from the browser but I was prompted with the error.

#### Actual Behavior

(what actually happens goes here)

This is the error
![image](https://user-images.githubusercontent.com/25238924/43946075-c10eb36c-9cb6-11e8-83ee-f3ea97f75fea.png)

![image](https://user-images.githubusercontent.com/25238924/43946106-da23ec5a-9cb6-11e8-9d09-c081e9fdf15d.png)

![image](https://user-images.githubusercontent.com/25238924/43946116-e63e0890-9cb6-11e8-9717-c282b2acbbf1.png)

Note: I didn't capture the whole error as it shows my database access on some of the rows. If there are still information you need to see from the error appeared, just tell me.

#### Please confirm you have done the following before posting your bug report:

- [*] I have enabled debug mode 
- [*] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?>>> FRESH INSTALL
- Version of Snipe-IT you're running>>> LATEST (4.6.3)
- Version of PHP you're running >>> v5.6
- Version of MySQL/MariaDB you're running >>> v14.14
- What OS and web server you're running Snipe-IT on >>> UBUNTU SERVER 18.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) >>> MANUAL installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error >>> PROVIDED THE SCREEN SHOT
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error >>> SETUP PAGE
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs. >>> BELOW ARE THE DATA GATHERED FROM LARAVEL LOGS:
#31 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#38 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#39 /var/www/snipe-it/public/index.php(59): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#40 {main}

- Include what you've done so far in the installation, and if you got any error messages along the way. >>> INSTALLED THE OTHER PHP EXTENSIONS THAT I MISSED.
- Indicate whether or not you've manually edited any data directly in the database >>> NO.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by EarlRamirez** [comment]
@gmb07 try downgrading your version of MariaDB to 10.0 or 10.1 and try again.

**Comment by gmb07** [comment]
@EarlRamirez, I'm going to try that, thank you for your suggestion.

**Comment by EarlRamirez** [comment]
@gmb07 forget to mention that you can find an OS that contains Snipe-IT here **https://github.com/EarlRamirez/snipeit_iso**
