### ISSUE TITLE
Image not saved when creating new asset

### ISSUE THREAD

**Issue by padrogass** [snipe/snipe-it#6067]
#### Please confirm you have done the following before posting your bug report:

- [ yes] I have enabled debug mode 
- [yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**
1. Go to 'New Asset'
2. Fill in all the fields
3. Scroll down to 'Send Image' and select the image file
4. Save
5. The new asset created doesn't have the image saved. You need to edit it and upload it again, and the image is saved

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.3 build 3866 (g3de1de9dc)
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version 7.2.8-1+ubuntu16.04.1+deb.sury.org+1

**Desktop (please complete the following information):**
 - OS: win 10 x64
 - Browser chrome
 - Version 58

**Error Messages**
- WITH DEBUG TURNED ON, No errors. 

**Additional context**
- Is this a fresh install or an upgrade? Upgrade

**Comment by EarlRamirez** [comment]
@padrogass I have tried to reproduce this error and unfortunately, I do not experience this issue, can you enable debugging and share it with the community?
