### ISSUE TITLE
Composer Installation Issue

### ISSUE THREAD

**Issue by dorongnong** [snipe/snipe-it#607]
Hello,

I tried to install snipe-it on Windows IIS.
When I was installing composer, I am getting this error.

Can anyone help me on this?

Thanks.

Command: composer install

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing bacon/bacon-qr-code (dev-master f2937bc)
    Downloading: connection...    Downloading: 100%
    Downloading: connection...    Downloading: 0%
    Downloading: 5%
    Downloading: 25%
    Downloading: 30%
    Downloading: 35%
    Downloading: 40%
    Downloading: 55%
    Downloading: 60%
    Downloading: 65%
    Downloading: 70%
    Downloading: 95%
    Downloading: 100%
    Downloading: connection...    Downloading: 0%
    Downloading: 5%
    Downloading: 10%
    Downloading: 15%
    Downloading: 35%
    Downloading: 40%
    Downloading: 45%
    Downloading: 50%
    Downloading: 70%
    Downloading: 75%
    Downloading: 80%
    Downloading: 100%
    Failed to download bacon/bacon-qr-code from dist: The "https://api.github.co
m/repos/Bacon/BaconQrCode/zipball/f2937bc90179125ae7c708233c7a2927b2a35033" file
 could not be written to C:\inetpub\wwwroot\snipe-it\vendor/bacon/bacon-qr-code/
59f5a07da22cfac3d510a787dbd00933: failed to open stream: Permission denied
    Now trying to download from source
  - Installing bacon/bacon-qr-code (dev-master f2937bc)
    Cloning f2937bc90179125ae7c708233c7a2927b2a35033

  [RuntimeException]
  Failed to clone git@github.com:Bacon/BaconQrCode.git, git was not found, ch
  eck that it is installed and in your PATH env.
  'git' is not recognized as an internal or external command,
  operable program or batch file.

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-p
lugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress
] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [pac
kages1] ... [packagesN]

**Comment by snipe** [comment]
Please see the getting help documentation: http://snipeitapp.com/documentation/getting-help/

**Comment by dorongnong** [comment]
Sorry. Here is an additional info.

1. I am running v1.2.6.
2. Windows 2008 R2, IIS 7.5

Thanks.

**Comment by snipe** [comment]
1.2.6 doesn't seem likely, since we don't use `bacon/bacon-qr-code` in 1.2.6.

**Comment by snipe** [comment]
(We switched to `dinesh/barcode`)

**Comment by dorongnong** [comment]
Oops sorry. It is 1.2.5.

**Comment by snipe** [comment]
1.2.6 is out, so I would use that instead. https://github.com/snipe/snipe-it/releases/tag/v1.2.6
