### ISSUE TITLE
Migrating Snipe-IT MySQL database from Ubuntu server to another

### ISSUE THREAD

**Issue by SirajQu** [snipe/snipe-it#6071]
Hi everyone,

I have an old Ubuntu server with Snipe-IT installed version v3.6.6 build 1,
I want to move snipeit database from the old server to new Ubuntu server which I have installed on it Snipe-IT version v4.6.3 - build 3866

Now I want to move MySQL database from the older server to the new, to be able to import the tables and values that inside the old database, is that possible and how do I do that?

**Comment by SirajQu** [comment]
@IxFail 
Thank you, actually I have followed that tutorial but it didn't work with me.

**Comment by EarlRamirez** [comment]
@SirajQu  this should help you **https://snipe-it.readme.io/docs/moving-snipe-it**, if it doesn't let us know exactly where it is failing and will try and give you a hand.

**Comment by snipe** [comment]
> Thank you, actually I have followed that tutorial but it didn't work with me.

You would need to define what "didn't work for me" means, exactly. Are you getting errors? If so, what are they?
