### ISSUE TITLE
How to change email notification subject title or content?

### ISSUE THREAD

**Issue by alvinsiab** [snipe/snipe-it#6073]
When an asset is checked out, user will receive a notification with the subject "Confirm Asset Delivery".
I want to change this subject title, but I'm not sure how.

**Comment by smksar** [comment]
It is in resources\lang\en where you can change other text as well.. for your case it is mail.php

![image](https://user-images.githubusercontent.com/38576928/44024348-9f634f14-9f1f-11e8-9e9b-2bb293ef5b1e.png)

Be informed that if you do the changes, the next update **will** overwrite this file and you would lose all the changes made.

**Comment by alvinsiab** [comment]
Noted. Thanks
