### ISSUE TITLE
How do I search by Default Location

### ISSUE THREAD

**Issue by avinashramsunder** [snipe/snipe-it#6075]
Hi

How do you search by default location?

Please see attached as I do not see it as an option.

Regards

Avinash Ramsunder

![capture](https://user-images.githubusercontent.com/42037212/44034182-c63854d0-9f0c-11e8-8b1b-aa45cb15d259.PNG)

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [Ubuntu]
 - Web Server: Apache,
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by smksar** [comment]
What's your version? It's available in my version 4.6.3..
