### ISSUE TITLE
Error 400 Bad Request when installing from source

### ISSUE THREAD

**Issue by VMFnet** [snipe/snipe-it#6076]
Installing a new instance of snipe-it (fresh manual install of the snipe-it 4.6.3 tarball - 25 july 2018) on a CentOS 7 server. SeLinux is disabled on this particular server.  
Configuring the apache vhost to serve the site as https with its own domain name. The TLS certificate is working and valid.
After folowing the steps from https://snipe-it.readme.io/docs/installation, i try to access my-domain/setup and get a HTTP 400 Bad Request error in the browser.

**To Reproduce**
1. Install following https://snipe-it.readme.io/docs/installation
2. Open brower to the snipe-it installation domain, brower redirects the install to the /setup route
3. HTTP 400 Bad Request error is displayed in browser

**Expected behavior**
accessing /setup page to finish pre-flight

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.3
 - OS: CentOS 7
 - Web Server: Apache 2.4.6
 - PHP Version : 7.2.8 (remi-rpm)

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Browsers : Firefox 61.0.2, Chromium 70.0.3509.0

**Error Messages**
- nothing shows up in the logs :-(

**Comment by EarlRamirez** [comment]
@VMFnet this sounds like Apache, can you try and enable debug and share the error with us.

**Comment by VMFnet** [comment]
app_debug is activated inside the .env file, i've got nothing in storage/logs.

I've change the loglevel of apache.  Here's the output of ssl_error.log : 

[rid#5651abb1bfc0/initial] init rewrite engine with requested uri /
[rid#5651abb1bfc0/initial] applying pattern '^' to uri '/'
[rid#5651abb1bfc0/initial] applying pattern '^' to uri '/'
[rid#5651abb1bfc0/initial] pass through /
[rid#5651abb36db0/subreq] init rewrite engine with requested uri /index.html
[rid#5651abb36db0/subreq] applying pattern '^' to uri '/index.html'
[rid#5651abb36db0/subreq] rewrite '/index.html' -> 'index.php'
[rid#5651abb36db0/subreq] local path result: index.php
[rid#5651abb36db0/subreq] init rewrite engine with requested uri /index.php
[rid#5651abb36db0/subreq] applying pattern '^' to uri '/index.php'
[rid#5651abb36db0/subreq] pass through /index.php
[rid#5651abb1bfc0/initial] init rewrite engine with requested uri /setup
[rid#5651abb1bfc0/initial] applying pattern '^' to uri '/setup'
[rid#5651abb1bfc0/initial] applying pattern '^' to uri '/setup'
[rid#5651abb1bfc0/initial] rewrite '/setup' -> 'index.php'
[rid#5651abb1bfc0/initial] local path result: index.php

the config is as follows : 
<VirtualHost *:443>
    DocumentRoot /srv/snipeit/public/
    ErrorLog /var/logs/httpdlogs/snipeit/ssl_error.log
    <Directory "/srv/snipeit/public">
        AllowOverride None
        Options -Indexes
        Require all granted
    </Directory>
    Header always set Strict-Transport-Security "max-age=15768000"
    RewriteEngine On
    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]
    # Handle Front Controller...
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
    # Handle Authorization Header
    # RewriteCond %{HTTP:Authorization} .
    # RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
    SSLEngine on
    …  (certificates edited out)
</VirtualHost>

**Comment by VMFnet** [comment]
I tried installing snipe-it from git on a freshly installed vanilla CentOS with the same PHP stack but with the default CentOS-provided Apache configuration .  
Snipe-IT seems to be working (pasing setup and displaying the app dashboard correctly.

I'll be investigating what settings in the previous servers' apache config causes the http 400 error.

**Comment by VMFnet** [comment]
Unfortunately, nothing shows up in Apache's logs.  

However, the error might come from a mistypted .env file (a space in some variable as described in this issue : #6104 ).
 I'll check the .env file on the server when i have access to see if it's the root cause of this issue.
