### ISSUE TITLE
Emails no longer being sent - O365

### ISSUE THREAD

**Issue by OprSysAdm** [snipe/snipe-it#6077]
#### Expected Behavior (or desired behavior if a feature request)

Currently attempting to restore the ability of my install to send emails after upgrading to O365. The emails were being sent fine before the upgrade to O365.

-----

#### Actual Behavior

Emails are not sent when trying to send via the "Send Test" button in the General Settings. Get error "Mail could not be sent."
-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? n/a - This is the same installation which was previously working before upgrading to O365
- Version of Snipe-IT you're running
v4.1.10 build 3249 (g8d3a214)
- Version of PHP you're running
7.0.30-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running
5.7.23-0ubuntu0.16.04.1
- What OS and web server you're running Snipe-IT on
Ubuntu 16.04 / Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
don't recall - manual I think. The problem is not with the install as everything is working perfectly before upgrade to O365
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
"VM388:1 POST http://assets.opr/api/v1/settings/mailtest 500 (Internal Server Error)"

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error.
I am trying to restore the email functionality that I had working before upgrading to O365. I have tried to edit the .env file multiple times using every setting for my SMTP etc that I can think of and nothing is allowing the mail test to send. This was working fine before we switched to O365 servers. 

I have checked the mail.log but don't see anything that I can recognize as a problem. If it helps I am able to receive a test email if I use the command:
 **echo "Test Email" | mail -s "Email test Subject" myemail@mydomain.com**

In terms of additional troubleshooting, I have not done anything except try to change the .env using the settings that I have been provided by our vendor. It 'seems' like the snipe-it is trying to use a different email system or something? 

I am not a programmer in any way so I can't even begin to figure out what the problem is. Hopefully someone can help. Just to say that all the other functionality is fine and this installation was working perfectly before we switched over.

**Comment by Jarli01** [comment]
Can you confirm the details in your .env file? The new SMTP address should be smtp.office365.com, port 587. 

Likely using TLS.

**Comment by OprSysAdm** [comment]
Good Morning, 
This is what I have been using: 

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=smtp.office365.com
MAIL_PORT=587
MAIL_USERNAME=myemail@mydomain.com
MAIL_PASSWORD=redacted
MAIL_ENCRYPTION=TLS
MAIL_FROM_ADDR=myemail@mydomain.com
MAIL_FROM_NAME='Asset Manager'
MAIL_REPLYTO_ADDR=myemail@mydomain.com
MAIL_REPLYTO_NAME='Asset Manager'

# --------------------------------------------
The email address and password have been modified for privacy. The email address being used is a full/valid office 365 account with a valid password.

Thanks!

**Comment by Jarli01** [comment]
That all looks compatible with what I have in my .env file

```MAIL_DRIVER=smtp
MAIL_HOST=smtp.office365.com
MAIL_PORT=587
MAIL_USERNAME=user@domain.com
MAIL_PASSWORD=password
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=user@domain.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=myaddr@domain.com
MAIL_REPLYTO_NAME='Snipe-IT'
```

**Comment by Jarli01** [comment]
You might need to confirm your settings with your O365 tenant, you might be using different settings. 

Are you an O365 admin?

**Comment by OprSysAdm** [comment]
When I use these settings I receive the error "Failed to load resource: the server responded with a status of 500 (Internal Server Error)" in the browser console. 

I am not sure what the issue is as this email is what I use for all other alerting that I have configured in the environment and it is working perfectly in all other systems , save this one.

**Comment by Jarli01** [comment]
You're installed on Ubuntu, correct?

**Comment by Jarli01** [comment]
Yeah Ubuntu 16.04 hrm. . . and this system sent emails previously?

**Comment by OprSysAdm** [comment]
Yes, Ubuntu 16.04. This is not a new install - the only change has been with email. It was working perfectly before this. 

One thing I did notice though which may be significant is that on the interface when I go to try the 'Send Test" button it says "This will attempt to send a test mail to " and gives me some completely different email address (the old one) but I see nowhere that I can go and change this. This old address is not a full email - it's just a mailing list. 

If the system is using the variables that I have specified in the .env file then why is it saying that it will send email to a completely different email address? Hope that makes sense and helps to figure out where the issue is.

**Comment by Jarli01** [comment]
Ah you're looking in the General settings, there are email setting there, yes. But for email alerts you need to goto Notifications. 

Check that the addresses are correct there and then test.

**Comment by Jarli01** [comment]
The "send test" address is what is set in your .env file, to update you need to refresh the settings. 

One sec while I look it up.

**Comment by Jarli01** [comment]
https://snipe-it.readme.io/v3.6.2/docs/common-issues

Try this from a terminal

```php artisan config:clear```

**Comment by OprSysAdm** [comment]
I have already done this, as well as restarting the apache server. Did not work. 

Every time I have made a change in the .env I do this.

**Comment by OprSysAdm** [comment]
I have done:
$ sudo nano .env
$ php artisan config:clear
Configuration cache cleared!
$ sudo service apache2 restart

**Comment by Jarli01** [comment]
Unfortunately than I don't know what else the issue might be, you might have to wait for @snipe and team to help troubleshoot. 

(FYI I'm just another guy using the software)

**Comment by OprSysAdm** [comment]
oh! ok, thanks! I thought you were the support guy. Thank you for trying ;)

**Comment by Jarli01** [comment]
The normal process to clearing your .env cache is to do 

php artisan config:clear
php artisan config:cache


I don't see that listed in the help docs or your response.

**Comment by OprSysAdm** [comment]
Darn, thought that might have been it. No dice, still not updating or sending. Thanks again ;)

**Comment by Jarli01** [comment]
Have you restarted the entire server, just for testing?

**Comment by Jarli01** [comment]
Or cleared your browser cache on your workstation.

**Comment by OprSysAdm** [comment]
Yes, I have done both - and I have just repeated the process. Still the same issue.

**Comment by Jarli01** [comment]
@OprSysAdm hrm, well I wish you luck I'm at my end of what I've encountered. Hopefully the team can further assist. 

If you want to live chat with some of the team you can find them on https://gitter.im/snipe/snipe-it

**Comment by OprSysAdm** [comment]
Thanks again! 
It's not super critical so I can wait and let them help people who have more serious problems on the chat. I'm sure someone will help when they can.

**Comment by samotelf** [comment]
Hi, my two noob cents here.
Please try to clear your cache using:
**sudo -u apache php artisan config:clear
sudo -u apache php artisan config:cache**

It seems everything is ok.
The account you're using to send the email has a valid license?
You can check your .env file and this is the field that will change the email field in General Settings -> Test Email. (changr this field and run config:clear and config:cache
**MAIL_REPLYTO_ADDR=Snipe-IT@contoso.com**

This is my .env configuration regarding the email.
**MAIL_DRIVER=smtp
MAIL_HOST=smtp.office365.com
MAIL_PORT=587
MAIL_USERNAME=contoso.communication@contoso.com
MAIL_PASSWORD=password
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=Snipe-IT@contoso.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=Snipe-IT@contoso.com
MAIL_REPLYTO_NAME='Snipe-IT'**

**Comment by OprSysAdm** [comment]
Hi @samotelf 

Thank you for trying however these are things that I had already tried above. The account IS valid and it does not matter what I have done after I make the changes to my .env file. The "Test Email" recipient never changes from the original email account that was there before the change to O365.

I think this information is being store elsewhere - but I do not know where or how to change it. Given that I am able to send email fine when I use the if I use the below command this seems very likely:
**echo "Test Email" | mail -s "Email test Subject" myemail@mydomain.com**

Unfortunately I am not in any way a developer/programmer so I don't have the depth required to figure this out on my own.

**Comment by samotelf** [comment]
Hm, maybe it is stored elsewhere.
But I guarantee you that I have changed it yesterday so I could reply to you.
The field is indeed MAIL_REPLYTO_ADDR=
Just for fun, have you tried to change your .env to debug mode to see it the file changes and if the app turns to debug mode?
And I’m a noob either but it seems to me that e-mail test that you did does not use your office 365 credentials right?
Is your solution hybrid?

**Comment by OprSysAdm** [comment]
@samotelf very sorry but I am not understanding what it is that you are asking.

My .env file settings are above, they are correct as far as everyone has indicated. The fact that the "Email Test" is not using O365 is the problem that I am having.

We only have one email system - Office365, it is not hybrid.

**Comment by samotelf** [comment]
Can you do this?
Enable debug mode. In your .env , set APP_DEBUG to true.
And do a config clear and a config cache.
See if the app goes to debug mode

**Comment by OprSysAdm** [comment]
Hi @samotelf,

While I appreciate the help, I have already done these things as in my first post. In order to request help you should have recorded errors while in debug mode. You can see the error in my first post that I received in the browser - nothing changed.

**Comment by OprSysAdm** [comment]
Hi! Is there anyone who can please look at this? It's been 15 days and I wouldn't mind some help.

**Comment by OprSysAdm** [comment]
This is resolved now.

**Comment by snipe** [comment]
Can you explain what the issue was, in case someone else has the same problem?

**Comment by OprSysAdm** [comment]
Looks like the cache wasn't actually clearing when I did the commands above. Someone on the chat suggested:

sudo php artisan config:clear
sudo php artisan config:cache 
at which point my email address finally changed in the interface to the new one. then I had also been connected to our protected B segment via vpn. When I tried the first time it was still failing until I disconnected from the vpn then it worked finally. 

The suggestions above were close but didn't quite work in my case for whatever reason.

**Comment by chamika83** [comment]
@snipe Yes I do have 
MAIL_DRIVER=SMTP
MAIL_HOST=smtp.office365.com
MAIL_PORT=587
MAIL_USERNAME=sysalert@Mydomain.com
MAIL_PASSWORD=PASSWORD
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=sysalert@Mydomain.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=chamika@Mydomain.com
MAIL_REPLYTO_NAME='Snipe-IT'
MAIL_AUTO_EMBED_METHOD='attachment'


Win Server 2016
Version v5.1.5 - build 6029 (master)
PHP 7.3.28

Error - Mail could not be sent.
No additional error message provided. Check your mail settings and your app

Debug - all.js?id=dde965016a515da2f8d2:3 POST http://192.168.159.130/api/v1/settings/mailtest 500 (Internal Server Error)
