### ISSUE TITLE
Importing Users with .CSV issue

### ISSUE THREAD

**Issue by RDCuser** [snipe/snipe-it#608]
Tried to import this simple user .csv file:
https://www.dropbox.com/s/irj5xe1i43qbrf2/test_import.csv?dl=0

Login to Snipe-IT from Windows 8.1 x64 machine with Google Chrome 40.0 and try to perfom user import (tried both with and without header row). A message "Success:success" appears, but no user added. Same for Firefox and IE on this machine.

But when login to Snipe-IT from Ubuntu Desktop 14.10 with Firefox 36.0 this same file imported perfectly and user was actually added into database.

**Comment by snipe** [comment]
Hm. Your sample file imported just fine for me... 
![screen shot 2015-03-04 at 1 38 47 pm](https://cloud.githubusercontent.com/assets/197404/6504160/1b28c12c-c2e9-11e4-8d79-2a3413441e3d.png)

**Comment by rnovo1983** [comment]
Well mine right now its only uploading just the ones have email registered. Any way to load only the First two Columns.

**Comment by snipe** [comment]
Email addresses are required for all users, so this is expected behavior

**Comment by rnovo1983** [comment]
fixed thanks.

**Comment by fikrigusti** [comment]
Hi, I have just installed Snipe-IT and seems running smoothly for a week. But when I tried to import users it says "Success: Success" but no user added. I am using Chrome on OS El Capitan machine. 
Herewith I enclosed the screenshot.
![screen shot 2016-05-08 at 11 37 44 pm](https://cloud.githubusercontent.com/assets/19204319/15099042/08d62b8c-1576-11e6-8717-3c3015282ea2.png)

**Comment by fikrigusti** [comment]
Hi, 
I am having the same problem, it says "Success" but no user added. I am using Chrome on OS X machine. 
![screen shot 2016-05-08 at 11 37 44 pm](https://cloud.githubusercontent.com/assets/19204319/15099090/b88561f6-1576-11e6-86c4-c644224747f0.png)
