### ISSUE TITLE
User last login not updated/synced?

### ISSUE THREAD

**Issue by smksar** [snipe/snipe-it#6084]
#### Expected Behavior (or desired behavior if a feature request)
When a user logs in Snipe-IT, it will update the last login of the user

-----

#### Actual Behavior
User showed to me that he/she has logged in.. right in front of me, yet the last login still showing date when I first imported the users even after refreshing multiple times.

Is there a command for this like how I can synchronize asset locations with php artisan snipeit:sync-asset-locations --output=all?

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade
- Version of Snipe-IT you're running
4.6.3
- Version of PHP you're running
7.2.4
- Version of MySQL/MariaDB you're running
5.7.21
- What OS and web server you're running Snipe-IT on
Windows 10 Enterprise
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
When you look in the database, is it updated there?

**Comment by snipe** [comment]
(Also, can you reproduce this on the demo?)

**Comment by smksar** [comment]
Hi @snipe thanks for checking up, noticed you went missing for a while :P Went for a well deserved holiday hopefully? Hehe..

I just looked into the db after your comment and unfortunately those same users last login were not updated! I am not sure why but a few others' last login updated just fine~ including myself

Also based on your suggestion, I tried to create a login in the demo, that was possible but I wasn't able to activate the created user for me to do a test. I also wanted to change password for one of the many available users but not allowed to do so, thus I am not sure how to test in the demo?

**Comment by snipe** [comment]
I didn't go missing. I was at a conference, which I explained I would be in several different threads. 

I don't have any idea why this would work for some people and not others. The code is pretty straightforward:

```
if ($user = Auth::user()) {
            $user->last_login = \Carbon::now();
            \Log::debug('Last login:'.$user->last_login);
            $user->save();
        }
```

You watched the user logout and then login completely from the login screen?

**Comment by snipe** [comment]
> Should I enable the crush cookie on session close?

If you don't want users sessions to be preserved, then sure.

The only thing I can think of in your particular circumstance is that users who have ONLY logged in via the password reset action may not have login_date logged. Once that session expires and they login traditionally, it would log their login date.

**Comment by smksar** [comment]
Oh! I just looked at login_attempts table and I **do** see those users with the right timestamp (column created_at)

Is there a flow if forgotten password was requested and user logged in via the forgot password link it will not detect the last_login?

**Comment by smksar** [comment]
Eh? hahah posted at the same time.. and same thought too!
