### ISSUE TITLE
Maintenances don't show history detail

### ISSUE THREAD

**Issue by hoangdinhanphabe** [snipe/snipe-it#6087]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**
1. Go to Asset Tag
2. Click on Maintenances
3. See error

**Expected behavior**
The maintenances are supposed to show detail in history

**Screenshots**
![image](https://user-images.githubusercontent.com/42403971/44138502-6202b94a-a09e-11e8-89b2-9fa8e5932e4f.png)

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**
 - OS: 4.6.3
 - Browser Chrome
 - Version 68

**Comment by leebaggaley** [comment]
I encounter this quite frequently, just clear your cache in your browser and they come back 👍

**Comment by hoangdinhanphabe** [comment]
That solved my problem. Thank you very much
