### ISSUE TITLE
Customize Report For SnipeIT

### ISSUE THREAD

**Issue by hungnth27** [snipe/snipe-it#6088]
**Server (please complete the following information):**
 - Snipe-IT Version 4.4.2
 - OS: [e.g. Ubuntu, CentOS] Ubuntu
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7

**Is your feature request related to a problem? Please describe.**
The report in my SnipeIT is classic CSV and I want to customize it.

**Describe the solution you'd like**
I want to know how to customize or replace my company's report to the SnipeIT's report.
**Describe alternatives you've considered**
Create a button for create template or import report template.

**Comment by hungnth27** [comment]
It's mean that my company have a report with company's logo and company's template. I want that when I click to export the report in SnipeIt, software will export for me a report which have company's logo and template. Where can I edit or customize?

**Comment by snipe** [comment]
You can edit the CSV after it's completed and save it as an XLS or doc file after adding your logo. CSV files don't really support logos, so it's not something we can add.
