### ISSUE TITLE
Modification : can asset form be modified?

### ISSUE THREAD

**Issue by patelriya5736** [snipe/snipe-it#6092]
I want modified some fields in asset form.like when any asset checkout to user then password is require filed for user.i want remove that mandatory field for password.
is it possible?

**Comment by snipe** [comment]
I'm not sure I understand what you're asking. Can you provide screenshots?

**Comment by patelriya5736** [comment]
![snipeit](https://user-images.githubusercontent.com/41178812/44247511-6ac91f00-a202-11e8-88f9-a8b2be3cacfd.png)

**Comment by snipe** [comment]
It's not possible to remove that at this time.

**Comment by patelriya5736** [comment]
Is it possible to do it in my local system?
if possible then please help me to solve this.
