### ISSUE TITLE
Feature request for Requestable Assets

### ISSUE THREAD

**Issue by KumarPOnline** [snipe/snipe-it#6094]
**Server (please complete the following information):**
 - Snipe-IT Version : Version v4.6.3 - build 3866
 - OS: [e.g. Ubuntu, CentOS] : Ubuntu 16.04 LTS
 - Web Server: [e.g. Apache, IIS] : Apache 2.4
 - PHP Version : PHP 7.0

**Is your feature request related to a problem? Please describe.**
I'm not clear about Requestable Assets, But as I feel, the user can request the asset which we have on stock. What is the process to get request with new products ?

**Describe the solution you'd like**
It's good, if we have common request form to get new product requests with some ticketing system.
By this, we can give  the asset / components to the user by priority or the FIFO.

**Describe alternatives you've considered**

**Additional context**
Sorry for the poor Language.

**Comment by EarlRamirez** [comment]
Basically, a user can only request an asset that is marked as requestable from the asset model or the asset itself.
