### ISSUE TITLE
Raspian 9.4 - Backups not functioning in develop branch

### ISSUE THREAD

**Issue by jasonlshelton** [snipe/snipe-it#6096]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After changing to the develop branch of snipeit, when I go to control panel -> backups and click on generate backup, I get the following error:

![capture](https://user-images.githubusercontent.com/13071957/44236248-2b96c180-a161-11e8-9975-0963619dfdf3.PNG)

**To Reproduce**
(Install Dev environment, Version v5.0.0-pre - build 3866 (develop))
1. Go to Settings ->Backups
2. Click on Generate backup
3. See error

**Expected behavior**
Backup should have been created.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version: Version v5.0.0-pre - build 3866 (develop)
 - OS: [e.g. Ubuntu, CentOS] Raspian 9.4
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.2.4-1+b2

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 68.0.3440.106 (Official Build) (64-bit)

**Error Messages**
No error message in logs 

**Additional context**
- Is this a fresh install or an upgrade? 
Had issue, deleted whole install and ran installer from scratch, then switched to develop branch using directions in documentation

- What OS and web server you're running Snipe-IT on

Raspberry Pi Zero W with raspbian 9.4

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Installer script

- Include what you've done so far in the installation, and if you got any error messages along the way.
Nothing, installed fresh to test issue

- Indicate whether or not you've manually edited any data directly in the database
No, new install fresh database.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Can you reproduce this on the develop demo? https://develop.snipeitapp.com

**Comment by jasonlshelton** [comment]
No, that feature is disabled in the development demo.

**Comment by snipe** [comment]
I just tried it on the develop demo and it worked (after disabling the demo lock, of course), so I'm not sure how to troubleshoot this issue. 

<img width="1389" alt="screen shot 2018-08-16 at 3 38 20 pm" src="https://user-images.githubusercontent.com/197404/44238642-749f4380-a16a-11e8-81f9-5bceb6e06c29.png">

**Comment by jasonlshelton** [comment]
I'm guessing there is a permissions problem, but I can't find what files and directories it looks in so I can check those permissions.

**Comment by jasonlshelton** [comment]
Interesting side note. If I run `php artisan backup:run` the backup works, but places the resulting file in snipeit/backups instead of snipeit/storage/app/backups I don't know if that is expected behavior. I was able to run the backup from web before changing to develop branch. 

I know this has to be on my end, but I'd still like to figure out what I did wrong so I can help others avoid the error.

**Comment by jasonlshelton** [comment]
I completely reinstalled from OS up. Still getting the error. Backups work in initial install, then fail after changing to develop branch.  Opening up my system for examination. This computer is only used for snipeit and will be wiped after this gets figured out.  

http://themadhouse.org:8000  
user: admin
password: password

ssh is at port 5022
user: snipeitapp
password: P@ssw0rd

**Comment by snipe** [comment]
When you switch to the develop branch, you're also running composer install, right?

**Comment by jasonlshelton** [comment]
Yep, I ran all of the commands in "Switching from Production to Develop branches" and then ran all of the "Handy Commands" on the common issues page.

**Comment by jasonlshelton** [comment]
issue seems to have been resolved, latest git pull resulted in backups working properly. No other changes were made on my system, so I will close this issue.
