### ISSUE TITLE
Consistent view features between search, all assets, and software license

### ISSUE THREAD

**Issue by brandenk514** [snipe/snipe-it#6097]
**Server (please complete the following information):**

- Snipe-IT Version: 4.6.3
- OS: Ubuntu 18.04 LTS
- Web Server: Apache
- PHP Version: 7.2

**Is your feature request related to a problem? Please describe.**
It seems that there are different features between different views. Ex. I can't bulb delete or edit software licenses. The checkboxes for each row appears to be missing, as well as the edit/delete drop-down in the top left corner of the view.

**Describe the solution you'd like**
I would like to see consistency for features and UI around all the views whether I am looking at all assets, all software, or searching.

**Describe alternatives you've considered**
Any way to get that same functionality restored in all the views.

**Comment by snipe** [comment]
Each one of those bulk actions requires special handling based on business logic and additional code. It's obviously our goal to make those views consistent, we just haven't had the time to do so for everything yet.
