### ISSUE TITLE
Bulk upload Asset inventory   

### ISSUE THREAD

**Issue by Arunryadav** [snipe/snipe-it#6098]
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**
I want to bulk upload asset inventory?   

**Describe the solution you'd like**
Can i upload the same from back end or any other way

**Comment by smksar** [comment]
Please read through the documentation before posting.

https://snipe-it.readme.io/docs/importing
