### ISSUE TITLE
Check out our first video tutorial: Custom Fields

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#6103]
Yeah, I know most of you already know how custom fields work, but I'm pretty proud of this video. It's our first of hopefully many video tutorials to supplement the user's manual.

[![Snipe-IT Custom Fields Tutorial](https://user-images.githubusercontent.com/197404/44297233-f4203600-a282-11e8-973d-ea2066f5a878.png)](https://youtu.be/AmKc0GuQbAU)

(And before you ask, no, I have no plans on creating videos for installation at this time.)

**Comment by huangshifang** [comment]
hey, Seemingly impossible to play， Maybe the reason for China's network.

**Comment by snipe** [comment]
@huangshifang Hm, that I don't know - the image above should just link to YouTube, but I don't know what restrictions there might be in China.

**Comment by smksar** [comment]
Wow that is rather detailed first video! That is you right @snipe =).. Welll done..!! Perhaps can do without background music as the video itself is solid enough.

**Comment by huangshifang** [comment]
@EarlRamirez Thanks!

**Comment by snipe** [comment]
@EarlRamirez nice workaround, thanks!

**Comment by EarlRamirez** [comment]
@snipe you are most welcome, anything for the community :)
