### ISSUE TITLE
Class 'Log' not found when generating app key

### ISSUE THREAD

**Issue by VMFnet** [snipe/snipe-it#6104]
Installing Snipe-It 4.6.3 on a CentOS 7 server with stock Apache and remi-php 7.2.9.

I get this error when running `php artisan key:generate` 

> PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/app/Exceptions/Handler.php:39
> Stack trace:
> #0 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(320): App\Exceptions\Handler->report(Object(Dotenv\Exception\InvalidFileException))
> #1 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(124): Illuminate\Foundation\Console\Kernel->reportException(Object(Dotenv\Exception\InvalidFileException))
> #2 /var/www/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #3 {main}
>   thrown in /var/www/app/Exceptions/Handler.php on line 39

**Comment by snipe** [comment]
This is usually an issue with the syntax within your .env config. 
https://snipe-it.readme.io/docs/installation-issues#section-fatal-error-uncaught-exception-reflectionexception-with-message-class-log-does-not-exist

**Comment by VMFnet** [comment]
You're absolutely right @snipe , it ws a misconfigured .env file causing havoc. Thanks !
Now snipe-it installs correctly.
