### ISSUE TITLE
Error on composer update

### ISSUE THREAD

**Issue by hbrecht** [snipe/snipe-it#6105]
#### Expected Behavior (or desired behavior if a feature request)

No Error on update

-----

#### Actual Behavior

When updating snipeit via php upgrade.php I got the warning:
"Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them."

So I wanted to update manually via
update --no-dev --lock

And got 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - roave/security-advisories dev-master conflicts with symfony/http-foundation[v3.4.12].
    - roave/security-advisories dev-master conflicts with symfony/http-foundation[v3.4.12].
    - roave/security-advisories dev-master conflicts with symfony/http-foundation[v3.4.12].
    - Installation request for roave/security-advisories dev-master -> satisfiable by roave/security-advisories[dev-master].
    - Installation request for symfony/http-foundation (locked at v3.4.12) -> satisfiable by symfony/http-foundation[v3.4.12].

-----

#### Please confirm you have done the following before posting your bug report:

- [No, why?] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade

- Version of Snipe-IT you're running
v4.6.3 - build 3876 (master)

- Version of PHP you're running
7.0.30

- Version of MySQL/MariaDB you're running
n/a

- What OS and web server you're running Snipe-IT on
Debian / Apache

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
php upgrade.php

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
n/a

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
n/a

- If a stacktrace is provided in the error, include that too.
n/a

- Any errors that appear in your browser's error console.
n/a

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
n/a

- Include any additional information you can find in `storage/logs` and your webserver's logs.
n/a

- Include what you've done so far in the installation, and if you got any error messages along the way.
n/a

- Indicate whether or not you've manually edited any data directly in the database
no.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Grab a fresh copy of composer.json and composer.lock from master, and re-run composer install. Running update will not work with what's currently on master.
