### ISSUE TITLE
Problem while updating Snipe-IT from 4.4.1 to 4.6.3

### ISSUE THREAD

**Issue by nikmohdaiman** [snipe/snipe-it#6106]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Snipe-IT Update did not complete successfully

**To Reproduce**
1. Go to Snipe-IT directory
2. Run php upgrade.php

**Expected behavior**
Snipe-IT able to update without problems

**Server (please complete the following information):**
 - Snipe-IT Version : 4.4.1
 - OS: [e.g. Ubuntu, CentOS] : Ubuntu
 - Web Server: [e.g. Apache, IIS] : Apache
 - PHP Version : 7.2.8

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Windpws 10
 - Browser [e.g. chrome, safari] : Chrome
 - Version [e.g. 22] : 68.0.3440.106

**Error Messages**
- syntax error in snipeit/app/Console/Commands/SendExpirationAlerts.php

**Additional context**
- Is this a fresh install or an upgrade? - Upgrade
- What OS and web server you're running Snipe-IT on - Ubuntu 16.04 / Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Git
- Include what you've done so far in the installation, and if you got any error messages along the way. - modified SendExpirationAlerts.php
- Indicate whether or not you've manually edited any data directly in the database - no

- I have made some changes to SendExpirationAlerts.php file 
   
   e.g

$asset_data['email_content'] .= '<td><a href="'.config('app.url').'/hardware/'.e($asset->id).'/view">';
$asset_data['email_content'] .= $asset->present()->name().'</a></td><td>'.e($asset->asset_tag).'</td>';

change to

//$asset_data['email_content'] .= '<td><a href="'.config('app.url').'/hardware/'.e($asset->id).'/view">'; $asset_data['email_content'] .= '<td>'.$asset->present()->name().'</a></td><td>'.e($asset->asset_tag).'</td>';

I have checked the SendExpirationAlerts.php file for version 4.4.1 and 4.6.3 are totally different in term of coding. Am I able to update Snipe-IT and keep my changes?

**Comment by EarlRamirez** [comment]
@nikmohdaiman you will need to stash (**git statsh**) the changes before you can perform the upgrade or you can add the modified file to the exclude directory so that git will ignore it.

**Comment by snipe** [comment]
> or you can add the modified file to the exclude directory so that git will ignore it.

That's not a good long term solution, as it will also ignore any updates we push out from upstream

**Comment by snipe** [comment]
@nikmohdaiman You'll need to reapply your changes with the updated code for 4.6.3. It's unfortunate, but that's why we recommend opening a PR so people's changes can be committed upstream.
