### ISSUE TITLE
Importing - Add checkout type of Asset so assets can be checkout out to other assets on import

### ISSUE THREAD

**Issue by brandenk514** [snipe/snipe-it#6107]
**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.3
 - OS: Ubuntu 18.04 LTS
 - Web Server: Apache
 - PHP Version: 7.2

**Is your feature request related to a problem? Please describe.**
An asset cannot be checked out to another asset during import, yet the feature exists for new assets in Snipe already.

**Describe the solution you'd like**
A field or someway to assign an asset to another asset rather than user or location when importing via CSV.

**Describe alternatives you've considered**
A way to define the import in the CSV so it knows to check out the asset to another asset.

**Comment by snipe** [comment]
Duplicate of #4519
