### ISSUE TITLE
Unknown Database

### ISSUE THREAD

**Issue by dorongnong** [snipe/snipe-it#611]
Hello,

I have installed snipe-it 1.2.6 on Win 2008 R2.
When I install composer, I see one message, 

 [PDOException]
 SQLSTATE[HY000] [1049] Unknown database 'snipeit_asset'

After installation was done, when I opened website, it showed very weir page, can anyone give me advice? Should I have to create a database table manually?
![image](https://cloud.githubusercontent.com/assets/11323800/6518685/203a06a6-c35e-11e4-8dea-ff26c3924681.png)

![image](https://cloud.githubusercontent.com/assets/11323800/6518710/8a881e08-c35e-11e4-8819-a0cebba5e02a.png)

**Comment by madd15** [comment]
You have a '-' not a '_' in the actual DB name

**Comment by madd15** [comment]
Also if thats the case, you might not have been able to run the `php artisan app:install` command either.

**Comment by dorongnong** [comment]
Thanks madd15. I have corrected database name and run install again.
No I am getting this error.
 [Illuminate\Database\QueryException]
 SQLSTATE[HY000]: General error: 1364 Field 'eula_text' doesn't have a defau
 lt value (SQL: insert into `categories` (`created_at`, `deleted_at`, `name`
 , `require_acceptance`, `updated_at`, `use_default_eula`, `user_id`) values
  (2015-02-21 03:03:00, , Laptops, 0, 2015-02-21 03:03:00, 0, 1), (2015-02-2
 1 03:03:00, , Desktops, 0, 2015-02-21 03:03:00, 0, 1), (2015-02-21 03:03:00
 , , Tablets, 0, 2015-02-21 03:03:00, 0, 1), (2015-02-21 03:03:00, , Phones,
  0, 2015-02-21 03:03:00, 0, 1), (2015-02-21 03:03:00, , Monitors, 0, 2015-0
 2-21 03:03:00, 0, 1))






 [PDOException]
 SQLSTATE[HY000]: General error: 1364 Field 'eula_text' doesn't have a defau
 lt value

I made change accordingly by following this link but no luck.
https://github.com/snipe/snipe-it/commit/2d196b1595ec87f119ad5a82f8f676918c52c896

Any advises?

**Comment by snipe** [comment]
Grab the latest off of develop - that's fixed there

**Comment by dorongnong** [comment]
Sorry. What is latest off of develop?

**Comment by dorongnong** [comment]
Now I got what you mean. I grab one from develop and completed installation.
New error is showed up.

Any advice?

![image](https://cloud.githubusercontent.com/assets/11323800/6519774/e9a47404-c36d-11e4-9420-48065b926be3.png)

**Comment by madd15** [comment]
Could you please check that the settings table has data in it

If there is no data try running the query from http://pastebin.com/vs819w6r against your Snipe-IT DB

**Comment by dorongnong** [comment]
I run the query and I got 'eula_taxt' error.
I deleted database and reinstall composer then I see a new error as below at the end
.
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","me
ssage":"Class 'AddEulaFields' not found","file":"C:\\inetpub_new\\wwwroot\\snipe
-it\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator
.php","line":301}}

**Comment by madd15** [comment]
try running the command `composer dump-autoload` then run the install again

**Comment by dorongnong** [comment]
Hi madd15,

Thanks for all your helps.
I run 'composer dump-autoload and did fresh installation again.
Unfortunately I got same error message.

{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","me
ssage":"Class 'AddEulaFields' not found","file":"C:\\inetpub_new\\wwwroot\\snipe
-it\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Migrations\\Migrator
.php","line":301}}

I looked 301 line on migrator.php file. here is a snap-shot.
Any suggestions to edit?
![image](https://cloud.githubusercontent.com/assets/11323800/6531800/ce9a2856-c3f0-11e4-9d4b-109d3e6af886.png)

**Comment by dorongnong** [comment]
I have tried composer dump-autoload, composer update and composer update --no-scripts but no luck.

**Comment by snipe** [comment]
You definitely shouldn't need to edit any files for this. There's something else wrong here. It almost feels like you don't have a complete installation or something.

**Comment by snipe** [comment]
"I run the query and I got 'eula_taxt' error.
I deleted database and reinstall composer then I see a new error as below at the end"

You have to reinstall via artisan as well, if you delete the databases. Composer just grabs all of the vendor libraries, and doesn't rely on a database to exist. the `php artisan app:install` command creates your database tables and runs all of the migrations. You can't do one or the other, it has to be both.

**Comment by snipe** [comment]
Any updates here?

**Comment by dorongnong** [comment]
How can I reinstall via artisan before running php artisan app:install?

**Comment by snipe** [comment]
Drop the tables in the snipe_it database.
Run `composer install --no-dev`
Run `php artisan app:install --env=production`

In that order.

**Comment by dorongnong** [comment]
Thanks it fixed my issue. :)

**Comment by sequencefive** [comment]
hello
i have tried all on this thread but i keep having this error

 ErrorException (E_ERROR)

SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: No such host is known. (View: C:\wamp\www\aaa\app\views\backend\layouts\default.blade.php) (View: C:\wamp\www\aaa\app\views\backend\layouts\default.blade.php)
