### ISSUE TITLE
Identify user's incident

### ISSUE THREAD

**Issue by smksar** [snipe/snipe-it#6110]
Snipe-IT 4.6.3

**Is your feature request related to a problem? Please describe.**
We have users who just don't take responsibility of taking care company assets but take care of their personal items with their dear life, bleh.. so in Snipe-IT I put remarks in the Notes section for the users e.g., User lost headset but it doesn't appear when you view the profile. Must edit user to see Notes.

**Describe the solution you'd like**
Perhaps another tab with the title Incidents where we can type or use a preset to state something about the user and link with the lost/burn/whatever-their-excuse assets or accessories for other admins to know that this user has lost something that were assigned to them so that we have better judgement of the user. Currently only the at then current admin knows what the user has done and not the future admins.

**Describe alternatives you've considered**
Using the already existing field Notes by manually typing the incident of the user

**Comment by snipe** [comment]
@smksar that information would/should be logged in history with the status change + notes

**Comment by smksar** [comment]
@snipe sorry for this one I don't really agree.. why? Because what you suggested is limited to just of those assets history notes.. 

How do we identify the user is not in good standing? Means s/he has bad history of losing/breaking stuff. Maybe say... traffic light icon next to the name such as green no issue, yellow lost/broke things once, red.. oh red.... 

Basically what I am suggesting is the user's standing with IT assets. If I just change status and add notes, it will appear on the asset history but it will not appear in user's history as there is no Notes column also, it can dissapear (need to scroll and look for one by one row)
