### ISSUE TITLE
Multiple Expiring Asset Notifications

### ISSUE THREAD

**Issue by XcelerationAdmin** [snipe/snipe-it#6114]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Receive the same email 6 times for the same asset at midnight each day.
Chron has no commands except LDAP sync. Changing .env mail settings prevents all emails and adding correct credentials sends 6 duplicates. Test email runs once, and forcing php notification runs 

**Expected behavior**
Receive only one email for each item.

**Screenshots**
Screenshot taking from #5651 as it is same issue.
![image](https://user-images.githubusercontent.com/42586847/44476720-a00cad00-a606-11e8-8b92-d56e6d47bce5.png)

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.3 Build 3876 (master)
 - OS: [Ubuntu 16.04.4 LTS]
 - Web Server: [Apache]
 - PHP Version 7.1.20

**Comment by snipe** [comment]
> Chron has no commands except LDAP sync.

That's simply not possible. Perhaps there is a different cron under s different user that's invoking that alert. Cron controls whether those alerts go out - there is nothing else in the system that triggers them.

**Comment by XcelerationAdmin** [comment]
Reviewing your comment, I listed all of my users and checked the crontab for each of them individually.  As you said, one of said users seemed to have the command listed below six times which corresponded to the six notifications I have received.

*** * * * * /usr/bin/php /var/www/snipeit/artisan schedule:run >> /dev/null 2>&1**

I will update the ticket tomorrow with an update regarding my problem.
For anyone else experiencing this problem ->

**cut -d: -f1 /etc/passwd** is the command I used to find all my users
**sudo crontab -l -u [user]** to list crontab individually for each user
**sudo crontab -e -u [user]** to edit crontab and remove the additional entries

**Comment by snipe** [comment]
@XcelerationAdmin those are helpful commands, thanks!

**Comment by XcelerationAdmin** [comment]
Purging the other five entries fixed my issue.
Thank you @snipe

**Comment by hjertis** [comment]
> Reviewing your comment, I listed all of my users and checked the crontab for each of them individually. As you said, one of said users seemed to have the command listed below six times which corresponded to the six notifications I have received.
> 
> > * * * * * /usr/bin/php /var/www/snipeit/artisan schedule:run >> /dev/null 2>&1
> 
> I will update the ticket tomorrow with an update regarding my problem. For anyone else experiencing this problem ->
> 
> **cut -d: -f1 /etc/passwd** is the command I used to find all my users **sudo crontab -l -u [user]** to list crontab individually for each user **sudo crontab -e -u [user]** to edit crontab and remove the additional entries

thank you very very much. I found 2 entries on one of my users. incredibly helpful.
