### ISSUE TITLE
Notify users of checkin date

### ISSUE THREAD

**Issue by wynandbecker** [snipe/snipe-it#6116]
#### Expected Behavior (or desired behavior if a feature request)

I keep seeing that it is possible to send emails to users that assets are assigned to, reminding them to bring back their assets.
I seem to be unable to work out how to set that up.

Could anyone please point me to some documentation on how to configure that?

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode No
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) Yes

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running v4.6.3
- Version of PHP you're running 7.5.9
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on CentOS 7 / Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
If you're using the scheduler, it should run along with the other commands. 
https://snipe-it.readme.io/docs/configuring-alerts-backups
