### ISSUE TITLE
Assett undeployable because of a status label

### ISSUE THREAD

**Issue by ovizii** [snipe/snipe-it#6117]
Running snipe-it latest via docker image. 
I just noticed one of my assets cannot be checked out and the tooltip says "This item has a status label that is undeployable and cannot be checked out at this time." 

If I however edit the asset, I see its Status as "ready to deploy" and below it says: "That status is deployable. This asset can be checked out"

Am I having a blonde moment or what am I doping wrong here? What status label is this tool tip talking about?

![image](https://user-images.githubusercontent.com/837902/44520213-8d11df80-a6cf-11e8-9d2f-683999af5c5d.png)

![image](https://user-images.githubusercontent.com/837902/44520224-9733de00-a6cf-11e8-95b6-0f2e4abf4594.png)

**Comment by ovizii** [comment]
The asset above is a laptop. I now realized that the two LCD screens assigned to this laptop show as not able to be checked out, same as my initial first post except I can see in its history it was checked out but not checked in. 

These 3 screenshots are all abut the LCD monitor.

![image](https://user-images.githubusercontent.com/837902/44520851-72406a80-a6d1-11e8-820c-0c322a9ac17b.png)

![image](https://user-images.githubusercontent.com/837902/44520907-a451cc80-a6d1-11e8-8412-b625863cfe2c.png)

![image](https://user-images.githubusercontent.com/837902/44520958-c64b4f00-a6d1-11e8-84bc-b5f500a30e69.png)


Also, I am wondering why the "actions" show in German when the rest of my interface is clearly English.

**Comment by snipe** [comment]
> Also, I am wondering why the "actions" show in German when the rest of my interface is clearly English.

Is it possible that your app settings are set to German (Admin Settings > Locale) but your UI is in english because your account-level local is set to English?

**Comment by ovizii** [comment]
That's possible, I'd have to check, there is another guy using this snipe-it instance and he's less fluid in English so he might have changed the app settings to German which I didn't notice as all my preferences are set to English. 

Any idea how to debug the other issues?

**Comment by snipe** [comment]
> Any idea how to debug the other issues? 

I'd like to debug the language issue first, as I think they may be related.

**Comment by snipe** [comment]
Also, what version of Snipe-IT are you running? (Next time please answer the questions in the issue template. We ask them for a reason, so we don't have to ask for more information later in the thread.)

**Comment by snipe** [comment]
I'm wondering if it's related to #4099

**Comment by snipe** [comment]
Try changing the locale in your .env to `APP_LOCALE=en`, and clearing your config cache using `php artisan config:clear`

**Comment by ovizii** [comment]
Here is the info and sorry for not providing it before hand. 

`docker run -d -p 9191:80 --name="snipeit" --restart=unless-stopped --env-file=/mnt/snipe-it/snipe-env -v /mnt/snipe-it:/var/lib/snipeit snipe/snipe-it`

which leads to v4.6.3 - build 3866 (master) 

-----------------
I checked my env file and its indeed
APP_LOCALE=de 

I don't care that much about the locale and thinking about the fact that I have a colleague using it who's not that proficient in English I should keep it on de but I'd like to avoid mixing of languages. Anything else I can do about this?

**Comment by snipe** [comment]
> I don't care that much about the locale and thinking about the fact that I have a colleague using it who's not that proficient in English I should keep it on de but I'd like to avoid mixing of languages.

Please switch it to `en` and clear your config cache as I asked. We're trying to troubleshoot the issue.

The languages won't be mixed. There are three tiers of localization:

- `.env`, which is only used for setup
- Admin Settings > Localization - which is only used if the user doesn't have a language set in their personal settings, and for the not-logged-in messaging when we don't know who the user is
- Profile > Language - which is used when we know who you are

**Comment by snipe** [comment]
Also can you show me a screenshot of your Status Labels listing page?

**Comment by ovizii** [comment]
OK, I change the .env file to reflect: 
APP_LOCALE=en 
stopped, remove, recreated the docker container as per my command posted earlier then 
I did a docker exec -i -t snipeit-latest php artisan config:clear

Here is the screenshot you asked for (I assume this is the Status Labels listing page?)
![image](https://user-images.githubusercontent.com/837902/44578194-4dacc700-a793-11e8-95c0-f787815cb713.png)

**Comment by snipe** [comment]
> Here is the screenshot you asked for (I assume this is the Status Labels listing page?)

Nope - go to the gear icon on the lower left, and find "Status Labels"

**Comment by ovizii** [comment]
Sorry, I got it now.
![image](https://user-images.githubusercontent.com/837902/44578516-1ee32080-a794-11e8-976d-921a4fe34b07.png)

**Comment by ovizii** [comment]
I can't remember ever having visited that page, except maybe when I first set up snipe-it. Shouldn't there be a status label: deployed too?

**Comment by snipe** [comment]
>  Shouldn't there be a status label: deployed too?

No, deployed is a meta-status. Deployable status label type + checked out to someone/somethijng = Deployed.

**Comment by ovizii** [comment]
Any more progress on this issue? 
I still have undeployable assets where I can't click the checkout button. 

Also, still having deployment issues. The "green" ready to deploy status is correct, the blue one however also says ready to deploy but next to it it says "deployed - what's going on here?
![image](https://user-images.githubusercontent.com/837902/44980674-d9330e80-af70-11e8-8b3d-c2266b558e8a.png)

**Comment by ovizii** [comment]
Anything? I'm stuck with devices I can't check out: 
![image](https://user-images.githubusercontent.com/837902/45818626-87191980-bce2-11e8-9151-ed15beb96a84.png)
 
The only workaround is to clone, checkout, delete original, which is loads of work :-(

**Comment by ovizii** [comment]
dear stalebot: I still consider this issue relevant but there haven't been any replies recently.

**Comment by ovizii** [comment]
dear stalebot: I still consider this issue relevant but there haven't been any replies recently.
