### ISSUE TITLE
Asset Model - Add Default values not diplaying correctly

### ISSUE THREAD

**Issue by Jhamende** [snipe/snipe-it#6118]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When trying to change the **default values** for custom fields under **asset model** . I noticed that if the first field is a dropdown/list, it doesn't displays correctly as a list, but all values in one line. 
Reset Navigation history doesn't help. 

**To Reproduce**
1. Go to Settings > Asset Model.'
2. Click on 'Edit button' on a model with a list as first custom field (you known your own database  :) ). 
3. Check the 'Add default values' checkbox
4. Click on the dropdown. 
5. There is only one value available in list with all values from list into it. 

**Expected behavior**
One value = One list item

**Screenshots**
![image](https://user-images.githubusercontent.com/14819237/44524644-a2423a80-a6de-11e8-845a-af3b5184d11c.png)

![image](https://user-images.githubusercontent.com/14819237/44524733-ee8d7a80-a6de-11e8-9ff9-0928e4492fc8.png)

Custom Field:
![image](https://user-images.githubusercontent.com/14819237/45417223-f6a75d00-b681-11e8-831c-da7b6e2c1253.png)

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.3
 - OS: Ubuntu Server 16.04.1
 - Web Server: Apache
 - PHP Version 7.0.30

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Firefox

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by jwhulette** [comment]
I was going to work on this, but as far as I can tell it appears to be working correctly. 
@Jhamende Did you put each OS on it's own line?
![custom_fields____exercitationem_quisquam_alias_consequatur_qui_quia_](https://user-images.githubusercontent.com/4930051/45045275-7446e980-b040-11e8-82a6-489e8211f015.png)

![update_asset_model____exercitationem_quisquam_alias_consequatur_qui_quia_](https://user-images.githubusercontent.com/4930051/45045347-a22c2e00-b040-11e8-8993-1ee799a9251e.png)

**Comment by Jhamende** [comment]
Well I went again to the custom field and just saved it again even if each value had its own line.  It seems to work now. It probably herited an error from a previous version of Snipe IT.

**Comment by jwhulette** [comment]
@Jhamende That's great that it's working. Can you please close this ticket?

**Comment by snipe** [comment]
Thanks so much for following up - it's always a big help in managing tickets! <3
