### ISSUE TITLE
I need to add multiple CC mail

### ISSUE THREAD

**Issue by murugavelc** [snipe/snipe-it#6119]
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

I can't add more than one CC mail to notify email for checkin/chickout. can you do the needful ?

**Comment by snipe** [comment]
## Server (please complete the following information):

Snipe-IT Version
OS: [e.g. Ubuntu, CentOS]
Web Server: [e.g. Apache, IIS]
PHP Version

**Comment by snipe** [comment]
I don't believe that's possible at this time - you should create a distribution list and include everyone that should be included on the checkin/checkout emails to that address.
