### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by stupac86** [snipe/snipe-it#612]
Hi All,

I'm trying to install snipe-it on to a Windows 2012 server. I've been following the instructions but when I try to install Composer into the C:\inetpub\wwwroot\snipe-it\ directory, I'm getting the following error:

 - Installing d11wtq/boris (v1.0.8)
   Downloading: connection...
   Failed to download d11wtq/boris from dist: The "https://api.github.com/repos
d11wtq/boris/zipball/125dd4e5752639af7678a22ea597115646d89c6e" file could not b
 downloaded (HTTP/1.1 404 Not Found)
   Now trying to download from source
 - Installing d11wtq/boris (v1.0.8)
   Cloning 125dd4e5752639af7678a22ea597115646d89c6e

 [RuntimeException]
 Failed to clone git@github.com:d11wtq/boris.git, git was not found, check t
 hat it is installed and in your PATH env.
 'git' is not recognized as an internal or external command,
 operable program or batch file.

Could somebody please offer some advice as to what is happening?

Many thanks,
Stuart

**Comment by luiscarlosmarquespereira** [comment]
It doesnt work on windows!!!

**Comment by stupac86** [comment]
Really? http://snipeitapp.com/documentation/installing-on-iis/

**Comment by t3kt** [comment]
The repo seems to have moved to https://github.com/borisrepl/boris, though I don't know enough about Compose to know what to do with the compose.lock config file to fix that.

**Comment by snipe** [comment]
I just spoke to the author of Boris, and [he said it should be fixed](https://twitter.com/d11wtq/status/573961551473856512).

**Comment by rnovo1983** [comment]
Hi, I followed every single step on the installation on IIS, but I just receive at the end a black page on my http://localhost  Route to /inetpub/wwwroot/snipe-it/public/ assigned. But no instructions on how to add sample data to the database previously created on the mysql server.

**Comment by rnovo1983** [comment]
Or response from the app.. :(

**Comment by snipe** [comment]
Please tell us what's in your logs. We need more information in order to help you. 

Did you run composer install? If so, did you see any errors? 
Did you run php artisan app:install? If so, did you see any errors?

Think about the information you would need to solve an end-user's problem. We need the same kinds of info to help you.

**Comment by rnovo1983** [comment]
this is what composed install on the snipe-it folder shows me : Command: composer install

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for intervention/image dev-master -> satisfiable by i
ntervention/image[dev-master].
    - intervention/image dev-master requires ext-fileinfo * -> the requested PHP
 extension fileinfo is missing from your system.


C:\inetpub\wwwroot\snipe-it>

**Comment by snipe** [comment]
Please see the Common Issues page. http://snipeitapp.com/documentation/common-issues/

As the error message states, you're missing the fileinfo extension.

**Comment by rnovo1983** [comment]
thanks, the composed was successfully installed but executing the 'line php artisan app:install'
gives me no result.

![image](https://cloud.githubusercontent.com/assets/11360172/6540223/065124d8-c460-11e4-9afd-4af3f4ccbf9d.png)

**Comment by snipe** [comment]
According to the docs, that's not how you're meant to do composer install for IIS:

1. Open C:\inetpub\wwwroot\snipe-it in Windows Explorer
 - Right Click and select Composer Install. This will install the dependencies. Once completed move to next step
 - Right Click and select Use Composer here
 - Type php artisan app:install and follow the prompts

http://snipeitapp.com/documentation/installing-on-iis/

**Comment by rnovo1983** [comment]
Open C:\inetpub\wwwroot\snipe-it in Windows Explorer
Right Click and select Composer Install. This will install the dependencies. Once completed 
- the dependencies where installed. 
-did right click on the folder, did use composer here
-It opens that cmd window & I type php artisan app:install
![image](https://cloud.githubusercontent.com/assets/11360172/6540269/0ea18ddc-c463-11e4-995f-6ae237a64a0f.png)

Sorry, if I'm doing it wrong can you explain me a little bit more. Please.

**Comment by snipe** [comment]
Do you have anything new in your logs?

**Comment by rnovo1983** [comment]
![image](https://cloud.githubusercontent.com/assets/11360172/6540333/21ea112c-c466-11e4-90f5-0f9683c98771.png)

**Comment by stupac86** [comment]
Hey Snipe,

Thanks for looking into this but I'm still getting the same error when running the composer install:

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing d11wtq/boris (v1.0.8)
    Downloading: connection...
    Failed to download d11wtq/boris from dist: The "https://api.github.com/repos
/d11wtq/boris/zipball/125dd4e5752639af7678a22ea597115646d89c6e" file could not b
e downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing d11wtq/boris (v1.0.8)
    Cloning 125dd4e5752639af7678a22ea597115646d89c6e
 
 
 
  [RuntimeException]
  Failed to clone git@github.com:d11wtq/boris.git, git was not found, check t
  hat it is installed and in your PATH env.
  'git' is not recognized as an internal or external command,
  operable program or batch file.

Many thanks,
Stuart

**Comment by snipe** [comment]
Try running `composer clear-cache` and re-running the install. Composer may be caching the vendor location, even though the entry on Packagist was updated by the REPL author.

**Comment by rnovo1983** [comment]
Yeah same thing for me it worked for me on my ubuntu server but in IIS got the same thing 

C:\inetpub\wwwroot\snipe-it>composer clear-cache
Clearing cache (cache-dir): C:\Users\admin\AppData\Local\Composer
Clearing cache (cache-files-dir): C:\Users\admin\AppData\Local\Composer\files
Clearing cache (cache-repo-dir): C:\Users\admin\AppData\Local\Composer\repo
Cache directory does not exist (cache-vcs-dir):
All caches cleared.

C:\inetpub\wwwroot\snipe-it>composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing d11wtq/boris (v1.0.8)
    Downloading: connection...
    Failed to download d11wtq/boris from dist: The "https://api.github.com/repos
/d11wtq/boris/zipball/125dd4e5752639af7678a22ea597115646d89c6e" file could not b
e downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing d11wtq/boris (v1.0.8)
    Cloning 125dd4e5752639af7678a22ea597115646d89c6e



  [RuntimeException]
  Failed to clone git@github.com:d11wtq/boris.git, git was not found, check t
  hat it is installed and in your PATH env.
  'git' is not recognized as an internal or external command,
  operable program or batch file.

**Comment by snipe** [comment]
It doesn't look like it really cleared the cache, since it's saying the cache was not found. I honestly don't know if there's a different way to clear the composer cache on IIS. I would just install git so you can download the package via the redirect. It's dumb that you should have to do this, but not sure what else to suggest, since `composer clear-cache` is the solve, but it doesn't seem to be working for you.

**Comment by snipe** [comment]
Can you tell me if there's anything in `c:\users\YOU\.composer\cache`?

**Comment by snipe** [comment]
(Or `C:\Users\YOU\AppData\Local\Composer\files`)

**Comment by snipe** [comment]
You can also try running `composer config cache-dir` to see if it will tell you where the cache is.

**Comment by rnovo1983** [comment]
[image: Inline image 1]


On Thu, Mar 12, 2015 at 1:36 AM, snipe <notifications@github.com> wrote:

> You can also try running composer config cache-dir to see if it will tell
> you where the cache is.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snipe/snipe-it/issues/612#issuecomment-78426661>.
>



-- 
Thank you,
Roberto Novo Cruz

CARECLOUD
I.T Specialist

**Comment by rnovo1983** [comment]
I got this

On Thu, Mar 12, 2015 at 1:39 AM, Roberto Novo <rnovo@carecloud.com> wrote:

> [image: Inline image 1]
>
>
> On Thu, Mar 12, 2015 at 1:36 AM, snipe <notifications@github.com> wrote:
>
>> You can also try running composer config cache-dir to see if it will
>> tell you where the cache is.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/snipe/snipe-it/issues/612#issuecomment-78426661>.
>>
>
>
>
> --
> Thank you,
> Roberto Novo Cruz
>
> CARECLOUD
> I.T Specialist
>



-- 
Thank you,
Roberto Novo Cruz

CARECLOUD
I.T Specialist

**Comment by snipe** [comment]
I don't think your image came through.

**Comment by rnovo1983** [comment]
[image: Inline image 1]

On Thu, Mar 12, 2015 at 1:40 AM, Roberto Novo <rnovo@carecloud.com> wrote:

> I got this
>
> On Thu, Mar 12, 2015 at 1:39 AM, Roberto Novo <rnovo@carecloud.com> wrote:
>
>> [image: Inline image 1]
>>
>>
>> On Thu, Mar 12, 2015 at 1:36 AM, snipe <notifications@github.com> wrote:
>>
>>> You can also try running composer config cache-dir to see if it will
>>> tell you where the cache is.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/snipe/snipe-it/issues/612#issuecomment-78426661>.
>>>
>>
>>
>>
>> --
>> Thank you,
>> Roberto Novo Cruz
>>
>> CARECLOUD
>> I.T Specialist
>>
>
>
>
> --
> Thank you,
> Roberto Novo Cruz
>
> CARECLOUD
> I.T Specialist
>



-- 
Thank you,
Roberto Novo Cruz

CARECLOUD
I.T Specialist

**Comment by snipe** [comment]
Still not coming through. It's showing as text.

**Comment by rnovo1983** [comment]
ok, I got two folders

-Files
-Repo
.htaccess

On Thu, Mar 12, 2015 at 1:42 AM, snipe <notifications@github.com> wrote:

> Still not coming through. It's showing as text.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snipe/snipe-it/issues/612#issuecomment-78427021>.
>



-- 
Thank you,
Roberto Novo Cruz

CARECLOUD
I.T Specialist

**Comment by snipe** [comment]
That's the output of what, exactly? Can you try `composer config cache-dir` so we can make sure we're looking at the right place?

**Comment by rnovo1983** [comment]
C:\inetpub\wwwroot\snipe-it>composer config cache-dir
C:/Users/admin/AppData/Local/Composer

**Comment by rnovo1983** [comment]
thats the folder

**Comment by rnovo1983** [comment]
C:\Users\admin\AppData\Local\Composer

**Comment by snipe** [comment]
`C:/Users/admin/AppData/Local/Composer` is the folder with the `Files`, `Repo`, etc directories in them?

**Comment by rnovo1983** [comment]
exactly.

**Comment by snipe** [comment]
Try removing the `composer.lock` and running `composer install`. (I'm really just guessing here - this just works on linux, not sure why it's being such a bastard on IIS)

**Comment by rnovo1983** [comment]
delete composer.lock on snipe folder?

**Comment by snipe** [comment]
Yes. I'm hoping that without one, it will try to do a fresh update.

**Comment by rnovo1983** [comment]
Did it...
I'm waiting its taking a couple of minutes ...

On Thu, Mar 12, 2015 at 1:51 AM, snipe <notifications@github.com> wrote:

> Yes. I'm hoping that without one, it will try to do a fresh update.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snipe/snipe-it/issues/612#issuecomment-78427682>.
>



-- 
Thank you,
Roberto Novo Cruz

CARECLOUD
I.T Specialist

**Comment by snipe** [comment]
Yeah, it will take a few.

**Comment by rnovo1983** [comment]
Dear lord...

It works!!!

Now I got this on this module

  - Installing sebastian/diff (dev-master 863df96)
    Downloading: connection...

Could not fetch
https://api.github.com/repos/sebastianbergmann/diff/zipball/863d
f9687835c62aa423a22412d26fa2ebde3fd3, enter your GitHub credentials to go
over t
he API rate limit
A token will be created and stored in
"C:/Users/admin/AppData/Roaming/Composer/a
uth.json", your password will never be stored
To revoke access to this token you can visit
https://github.com/settings/applica
tions
Username:


On Thu, Mar 12, 2015 at 1:53 AM, Roberto Novo <rnovo@carecloud.com> wrote:

> Did it...
> I'm waiting its taking a couple of minutes ...
>
> On Thu, Mar 12, 2015 at 1:51 AM, snipe <notifications@github.com> wrote:
>
>> Yes. I'm hoping that without one, it will try to do a fresh update.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/snipe/snipe-it/issues/612#issuecomment-78427682>.
>>
>
>
>
> --
> Thank you,
> Roberto Novo Cruz
>
> CARECLOUD
> I.T Specialist
>



-- 
Thank you,
Roberto Novo Cruz

CARECLOUD
I.T Specialist

**Comment by rnovo1983** [comment]
I guess I need my credentials of github?!

**Comment by snipe** [comment]
Okay, you should be able to enter your github username and password at the prompt. It's nothing to worry about, and will just store a token locally on the machine you're installing this on. Nothing gets sent to me (or anywhere other than Github).

**Comment by rnovo1983** [comment]
THANKKKSSS!!!!!!  A LOT SNIPE

On Thu, Mar 12, 2015 at 1:57 AM, snipe <notifications@github.com> wrote:

> Okay, you should be able to enter your github username and password at the
> prompt. It's nothing to worry about, and will just store a token locally on
> the machine you're installing this on. Nothing gets sent to me (or anywhere
> other than Github).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snipe/snipe-it/issues/612#issuecomment-78428130>.
>



-- 
Thank you,
Roberto Novo Cruz

CARECLOUD
I.T Specialist

**Comment by rnovo1983** [comment]
GREAT HELP THANKS AGAIN!

On Thu, Mar 12, 2015 at 2:02 AM, Roberto Novo <rnovo@carecloud.com> wrote:

> THANKKKSSS!!!!!!  A LOT SNIPE
>
> On Thu, Mar 12, 2015 at 1:57 AM, snipe <notifications@github.com> wrote:
>
>> Okay, you should be able to enter your github username and password at
>> the prompt. It's nothing to worry about, and will just store a token
>> locally on the machine you're installing this on. Nothing gets sent to me
>> (or anywhere other than Github).
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/snipe/snipe-it/issues/612#issuecomment-78428130>.
>>
>
>
>
> --
> Thank you,
> Roberto Novo Cruz
>
> CARECLOUD
> I.T Specialist
>



-- 
Thank you,
Roberto Novo Cruz

CARECLOUD
I.T Specialist

**Comment by snipe** [comment]
@rnovo1983 no problem. 

![chewbacca hair](https://cloud.githubusercontent.com/assets/197404/6612990/4d940d60-c843-11e4-9ed6-e20a2277cbcd.gif)

@stupac86 The solves here should solve your issue, too, so I'm going to close this ticket for now. Let me know if you're still stuck and I'll re-open.

**Comment by rnovo1983** [comment]
I here again happiness just ended again!!! :)

C:\inetpub\wwwroot\snipe-it>php artisan app:install
=====================================

  Step: 1

    Please follow the following
    instructions to create your
    default user.

-------------------------------------

Please enter your first name: admin
Please enter your last name: carecloud
Please enter your user email: itsupport@carecloud.com
Please enter your user password (at least 8 characters): m4gn1f1c3nt!!
Do you want to seed your database with dummy data? (deafult is yes): yes


=====================================

  Step: 2

    Preparing your Application

-------------------------------------

Application key [mVogGSHuoYuCM8wAD9SHxhQYuajTtLOe] set successfully.



  [PDOException]
  SQLSTATE[HY000] [1045] Access denied for user 'travis'@'localhost' (using
p
  assword: NO)



app:install



C:\inetpub\wwwroot\snipe-it>

On Thu, Mar 12, 2015 at 2:07 AM, snipe <notifications@github.com> wrote:

> @rnovo1983 <https://github.com/rnovo1983> no problem.
>
> [image: chewbacca hair]
> <https://cloud.githubusercontent.com/assets/197404/6612990/4d940d60-c843-11e4-9ed6-e20a2277cbcd.gif>
>
> @stupac86 <https://github.com/stupac86> The solves here should solve your
> issue, too, so I'm going to close this ticket for now. Let me know if
> you're still stuck and I'll re-open.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snipe/snipe-it/issues/612#issuecomment-78428787>.
>



-- 
Thank you,
Roberto Novo Cruz

CARECLOUD
I.T Specialist

**Comment by snipe** [comment]
You need to follow the installation instructions to set your database username and password

**Comment by kambho** [comment]
Try removing the composer.lock and running composer install. (I'm really just guessing here - this just works on linux, not sure why it's being such a bastard on IIS)

This worked for me too on linux!! Thank you

**Comment by ruckuss123** [comment]
Hi, 

I'm stick at the tocken sections.  I generated a token, but, doens't let me type into the command window that pops up.. 

![image](https://cloud.githubusercontent.com/assets/13805196/9287191/e6d2c9b8-42d6-11e5-8463-03e4966f00a1.png)

it doesn't take anyhting I type in there, just says no token givien, aborting.  please help.

**Comment by snipe** [comment]
@ruckuss123  What token are you trying to generate, exactly?

**Comment by salam82** [comment]
![4](https://cloud.githubusercontent.com/assets/7134646/9830127/bef89262-593b-11e5-91c3-7b8546fdda13.PNG)

I am trying since a week to install snipe-it but no luck. today it shows this error. kindly guide.

**Comment by snipe** [comment]
Looks like it can't reach out to the internet to contact packagist for the vendor dependencies. Do you maybe have some funky firewall rules preventing outside connections?

**Comment by salam82** [comment]
well I also try without firewall & proxy but the same msg. Is there any automatic installation method so a person can get it run easily :)

**Comment by snipe** [comment]
Even if there was one, if your system can't access the outside world, you won't be able to install the dependencies. You have to solve that problem first.
