### ISSUE TITLE
Steup Error

### ISSUE THREAD

**Issue by wangwbwwb** [snipe/snipe-it#6124]
**Server (please complete the following information):**
 - Snipe-IT 4.6.3 
 - OS: [windows server2012]
 - Web Server: [iis 8.5]
 - PHP Version 7.2.9

(3/3) ErrorExceptionTrying to get property 'privacy_policy_link' of non-object (View: C:\inetpub\wwwroot\snipe-it-4.6.3\resources\views\layouts\basic.blade.php) (View: C:\inetpub\wwwroot\snipe-it-4.6.3\resources\views\layouts\basic.blade.php)
--
in 50431d4b02d0abceca52389f94f42179e17f8f15.php line 59
at CompilerEngine->handleViewException(object(ErrorException), 1)in PhpEngine.php line 44
at PhpEngine->evaluatePath('C:\\inetpub\\wwwroot\\snipe-it-4.6.3\\storage\\framework\\views/400f32f1665aee82b5585ab9c435cf4b7d14092a.php',array('__env' => object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => false, 'exception' =>object(NotFoundHttpException), 'snipeSettings' => null))in CompilerEngine.php line 59
at CompilerEngine->get('C:\\inetpub\\wwwroot\\snipe-it-4.6.3\\resources\\views/errors/404.blade.php', array('__env' => object(Factory), 'app' =>object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => false, 'exception' => object(NotFoundHttpException), 'snipeSettings' => null))in View.php line 137
at View->getContents()in View.php line 120
at View->renderContents()in View.php line 85
at View->render()in Response.php line 38
at Response->setContent(object(View))in Response.php line 201
at Response->__construct(object(View), 404, array())in ResponseFactory.php line 55
at ResponseFactory->make(object(View), 404, array())in ResponseFactory.php line 69
at ResponseFactory->view('errors::404', array('exception' => object(NotFoundHttpException)), 404, array())in Handler.php line 195
at Handler->renderHttpException(object(NotFoundHttpException))in Handler.php line 173
at Handler->prepareResponse(object(Request), object(NotFoundHttpException))in Handler.php line 119
at Handler->render(object(Request), object(NotFoundHttpException))in Handler.php line 101
at Handler->render(object(Request), object(NotFoundHttpException))in Pipeline.php line 82
at Pipeline->handleException(object(Request), object(NotFoundHttpException))in Pipeline.php line 32
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php line 51
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php line 25
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php line 35
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

**Comment by snipe** [comment]
Server (please complete the following information):

Snipe-IT Version
OS: [e.g. Ubuntu, CentOS]
Web Server: [e.g. Apache, IIS]
PHP Version

**Comment by wangwbwwb** [comment]
Snipe-IT Version 4.6.3
OS: [windows server2012]
Web Server: [iis 8.5]
PHP Version 7.2.9
