### ISSUE TITLE
Multiple sw running with XAMPP including SNIPE-IT

### ISSUE THREAD

**Issue by ConsorzioRicambi** [snipe/snipe-it#6125]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

It's not a "bug", rather is a doubt. I'm not a programmer and I've read a lot of pages but I didn't found anything helpfull. 
I have XAMPP installed currently running 2 apps (OSTicket as ticketing system and a PHPBB3 as forum) and so i can't use TOMCAT with DocumentRoot pointing to SNIPE-IT because doing so only SNIPE-IT works. Is there a way to let Snipe-IT and other apps working at the same time??

I apologize about the stupid question (maybe) and about my bad english.

Thanks in advance and regards.

**To Reproduce**

Simply follow installation of snipe-it step by step having other apps running with xampp.

**Expected behavior**
I hope is possible to use snipe-it and other apps at the same time.

**Server (please complete the following information):**
 - Snipe-IT 4.6.3
 - OS: Windows 10 PRO
 - XAMPP: 3.2.2

**Desktop (please complete the following information):**
 - Same as server 
 - Chrome, I.E., Firefox

**Smartphone (please complete the following information):**

**Additional context**
- Fresh installation
- For installation i've followed guide "installation with XAMPP"

**Comment by snipe** [comment]
This is really a XAMPP config issue, not a Snipe-IT issue. You might try these resources for setting up VirtualHosts in XAMPP:

https://stackoverflow.com/questions/3660066/hosting-multiple-local-sites-with-xampp
http://shapesandelements.com/setup-virtualhost-with-tomcat-and-xampp-on-windows-7/

**Comment by ConsorzioRicambi** [comment]
Thanks for the answer but maybe is not so correct to close the thread. I've not resolved yet my issue and maybe others may have the solution.. 
In fact i've tried what is written into both sites you gave to me but it doesn't work..
So if anyone before me had the same issue and resolved it please, even in PM, contact me.
Thanks in advance.

**Comment by snipe** [comment]
It's closed because it's not a Snipe-IT issue, it's  XAMPP issue.

**Comment by ConsorzioRicambi** [comment]
Ok i've understood.. i was only saying that maybe i'm not the unique man on the Earth that had this issue and maybe someone has a solution (or has a way to bypass this XAMPP issue).
Anyway thanks a lot because your URLs gave me a hope :-)

Regards,
Andrea.

**Comment by snipe** [comment]
@ARKaMAN @dangerd1 @chaaza @mandelbrotmedia Sorry to tag you out of the blue, but do you have suggestions for @ConsorzioRicambi? I don't run windows, so not sure what to suggest beyond the links I provided.

Thanks in advance!
