### ISSUE TITLE
Feature Request for addtl. Asset permissions on Company level and changes to the Asset ID settings

### ISSUE THREAD

**Issue by dvogelho** [snipe/snipe-it#6126]
**Server (please complete the following information):**
Snipe-IT Version: v4.6.3 build 3866 (g3de1de9dc)
OS: Debian: Debian GNU/Linux 9 (stretch) version 9.5
Web Server: Apache/2.4.25
PHP Version: PHP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS )

**Is your feature request related to a problem?**
- No

**Describe the solution you'd like**
- I'd like to have an additional permission option to grant the access to Assets, Accessories, Consumables, Licenses only to a specific Company or Companies.
- I'd like to be able to define separate Asset IDs / Prefixes for e.g. IT and non-IT, to have a separation in the system, so it would be great to be able to define a range of asset numbers for IT and a separate range non-IT in our case.

**Describe alternatives you've considered**
- Not aware of any alternatives, because if a user has the permissions to Assets, Accessories, Consumables, Licenses he can manage all of them of all created Companies at the moment, but maybe he's only responsible for one ore more Companies.
- Not aware of any alternatives, because if an IT or non-IT Asset will be created, all of them will get an Asset ID of the same range of numbers and with the same prefix as well, which is not really helpful for the overview afterwards in case of audits.

Hopefully this is possible and will be implemented soon, both features will improve our processes and the usage of the system.

Looking forward to your answers.

**Comment by snipe** [comment]
> I'd like to have an additional permission option to grant the access to Assets, Accessories, Consumables, Licenses only of a specific Company or Companies.

Use full company support.
https://snipe-it.readme.io/docs/general-settings#section-full-multiple-companies-support

> Not aware of any alternatives, because if an IT or non-IT Asset will be created, all of them will get an Asset ID of the same range of numbers and with the same prefix as well, which is not really helpful for the overview afterwards in case of audits.

Seems similar to #3914

**Comment by dvogelho** [comment]
Your answer was really fast! 
Many thanks for the note, I will check this out and great to hear that this feature is already ready for dev.

**Comment by dvogelho** [comment]
Yes for sure. Thanks.

**Comment by dvogelho** [comment]
My fault, thread can be closed
