### ISSUE TITLE
Login info for demo site doesn't work

### ISSUE THREAD

**Issue by t3kt** [snipe/snipe-it#613]
The login info specified on http://snipeitapp.com/demo/ does not work on http://demo.snipeitapp.com/.

**Comment by tester1234567890q** [comment]
it works for me

**Comment by t3kt** [comment]
huh... i just tried it again and it worked. i was copying/pasting both times. maybe i missed something.

**Comment by drahamim** [comment]
which login? Admin?

**Comment by t3kt** [comment]
The admin one now works but as far as I can tell it didn't earlier.
The reporting one does not appear to be working at the moment.

**Comment by drahamim** [comment]
Reporting didn't work for me either. Not sure why admin didn't work. I just tested multiple login (Two separate browsers) and that doesn't seem to be an issue. May have just been a minor blip.

**Comment by snipe** [comment]
Looks like someone playing with the site deleted the reporting user. I restored it, so the login should work again.
