### ISSUE TITLE
Depreciation Methods Improvement

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#6130]
**Server (please complete the following information):**
 - Snipe-IT Version  v4.6.3 build 3876 (g5db5134ae)
 - OS: [e.g. Ubuntu, CentOS] CentOS 7
 - Web Server:  Apache
 - PHP Version 7.1.21

**Is your feature request related to a problem? Please describe.**
The depreciation functionality appears to depreciate monthly, we depreciate our assets much more accurately and depreciate to the day, from the initial checkout operation. 

As Snipe-IT is currently, depreciation is a "one solution fits all" approach which it doesn't work for our accounting department as they work to the day, and from when an asset is first put into service. (first check out). 

**Describe the solution you'd like**
An option flag(s) to set depreciation method to operate per day from the initial check out date. 

**Describe alternatives you've considered**
Continuing to use excel to track assets from the accounting side, and to use Snipe-IT to account for the transactional information an IT department needs. .. 

**Additional context**
I would love to have my accounting department stop using Excel as they even realize that they are missing out on a lot of important information. IE: if an asset is destroyed they should know to eat the cost immediately rather than depreciating the item over the expected usable life.

**Comment by memtech3** [comment]
Maybe add a custom depreciation format so that users can type in the equation of depreciation that they are using

**Comment by Jarli01** [comment]
@memtech3 that might work as well, but would be a bit more in-depth rather than just changing the depreciation term. 

Doable though.

**Comment by Jarli01** [comment]
This is still a critical function to allow the accounting team to be able to Buy-In on using Snipe-IT for their needs rather than excel documents.

**Comment by Jarli01** [comment]
While this may be an option for some, there is also the issue that assets get depreciated based on their creation data.

My accounting team depreciated based on initial check-out date (when something is put in service).

**Comment by Jarli01** [comment]
Please reopen this is still relevant.

**Comment by Lerato6221** [comment]
Please reopen this, it is still relevant, We want to use snipe it in my company but the depreciation is not working for us, we need a day to day depreciation and to be able to apply certain percentage.

**Comment by snipe** [comment]
This is not currently a priority for us. We would entertain a PR tho.
