### ISSUE TITLE
Create Purchase Order and subsequent assets and accessories from delivered purchases

### ISSUE THREAD

**Issue by yajmarshall** [snipe/snipe-it#6133]
This was already posted by other members but it is really a extraordinary element and one that is really needed

"Introduce an element called "Purchase Orders" (or just "Orders"). On this element, capture:
Supplier
Asset Model/Consumable/Accessory (from existing items)
Qty ordered
Price per item
Date of order
Notes (optional)
Auto-generate a Purchase Order number when a PO is created, of which the format is definable (via Regex maybe?) in the Settings menu.

Allow this Purchase Order to be "Fulfilled"... when a PO is Fulfilled:

On Consumables/Accessories, the Quantity deployable is increased with the Qty on the PO on the existing items
On Asset Models, new Assets are created with default values for the amount of items on the PO; or maybe by displaying a page with a grid-like interface where each Asset to be created's fields can be modified before they are created; or, maybe asking for a CSV import as part of the Fulfillment with the details of each Asset? The Order Number field on the Asset should be pre-populated with the PO number, and this number cannot be changed.
Allow a Purchase Order to be "Cancelled". Self-explanatory.

Remove the Order Number field from Consumables and Accessories, as this is now contained in the PO.

Allow a user to view the purchase orders related to an Asset/Consumable/Accessory in a grid on the View page (i.e. on http://mysniperserver/consumables/1, underneath the consumable Checkout details)

Allow navigation from an Asset to the Purchase Order (since the Purchase Order number is present on the Asset and not changeable)

(Nice to have) Allow a Custom Fieldset for Purchase Orders, i.e. to add a Payment Number, Delivery Date etc

Another nice to have would be to actually generate the PO document (i.e. "export" the PO element as a PDF file with a definable logo in Settings somewhere?) that can be sent to the Supplier."

**Comment by memtech3** [comment]
Maybe also add integrations into financial software?

**Comment by grimstoner** [comment]
Duplicate of #4488

**Comment by Lansingnl** [comment]
I would really want to use Snipe-it for our company assest management, but the fact that I can not generate a purchase order for the assets I want to buy makes it impossible for us to use it. I would really appreciate this feature being added.
