### ISSUE TITLE
Checkout Accessories to Assets

### ISSUE THREAD

**Issue by Freaksed** [snipe/snipe-it#6134]
I like that you can check assets out to other assets (in essence creating a package). But it would be nice if you could do the same with accessories.
For example a wireless controller, chargers, etc where you send them out in a kit

**Comment by EarlRamirez** [comment]
@Freaksed  this looks like a duplicate to #5140

**Comment by Freaksed** [comment]
you are correct, thanks, ill close

**Comment by snipe** [comment]
Also, kits are an additional, older feature request :)
