### ISSUE TITLE
Asset Import creates new users rather than using existing ones.

### ISSUE THREAD

**Issue by Tennoo** [snipe/snipe-it#6136]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When importing assets via the web importer, the importer creates a new user and checks the asset to the newly created user rather than using existing ones. This happens when I map the users full name to the "Full Name" field. I've also tried to map their full names to "Checked out to" and their usernames.
The users are synced with LDAP if that makes any difference.

I have looked at the similiar questions raised, but none of the solutions that were proposed in those threads were helpful for me. I have looked at these threads:
#5290 
#5061 
#5199

**Expected behavior**
Imported assets should be checked out to existing users, not creating new ones.

**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.3
 - OS: [e.g. Ubuntu, CentOS]: WIndows Server 2016
 - Web Server: [e.g. Apache, IIS] IIS
 - PHP Version 7.2

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome

**Additional context**
- Is this a fresh install or an upgrade? Fresh
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual

**Comment by EarlRamirez** [comment]
can you share a sample of your CSV, will like to try and reproduce this error?

**Comment by Tennoo** [comment]
Hi, I probably should have provided that from the start. For some reason I cannot attach a CSV file, but I have provided a corresponding Excel sheet.
[asset.xlsx](https://github.com/snipe/snipe-it/files/2335218/asset.xlsx)


Thank you.

**Comment by imthattalldude** [comment]
I don't know if you still needed an answer, but I have found that the username of the intended user has to match how your username format is set in the snipe-it settings. It translates the name into a username using your username format. So if it doesn't find a user with the username it's looking for, it makes a new one. The username format setting is in the general settings in Snipe-it.
