### ISSUE TITLE
LDAP Integration Fail (memory error and DN syntax)

### ISSUE THREAD

**Issue by jmcdowell21** [snipe/snipe-it#6137]
#### Expected Behavior (LDAP integration / import of users)

Import AD users from organization

-----

#### Actual Behavior

Returns a memory error when importing high volumes and a DN syntax error when smaller groups.

Memory error:

xxxxxxxxxxxxxxxxxxxx [~/xxxxxxxxx.xxxxx.xxx.xxx/snipe-it]# php artisan snipeit:ldap-sync --location=CampusAD --summary

PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 4096 bytes) in /home/xxxxx/xxxxxxxxx.xxxxx.xxx.xxx/snipe-it/app/Models/Ldap.php on line 269
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 4096 bytes) in Unknown on line 0

DN Syntax error:

xxxxxxxxxxxxxxxxxxxx [~/xxxxxxxxx.xxxxx.xxx.xxx/snipe-it]# php artisan snipeit:ldap-sync --location=xxxxxxxx --summary

In Ldap.php line 262:

  ldap_search(): Search: Invalid DN syntax

-----

#### Please confirm you have done the following before posting your bug report:

- [No] I have enabled debug mode 
- [Yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - No
- Version of Snipe-IT you're running - v4.5.0 build 3701
- Version of PHP you're running - 7.1.21
- Version of MySQL/MariaDB you're running - 5.6.40
- What OS and web server you're running Snipe-IT on - Linux / lamp
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - unknown (I took over this position, unsure what method the previous holder used)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - using terminal, not browser, errors are above.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - not on the browser, but I am trying to do the LDAP integration/perform the import on the terminal
- If a stacktrace is provided in the error, include that too.

[2018-08-28 00:07:10] production.ERROR: ErrorException: ldap_search(): Search: Invalid DN syntax in /home/xxxxx/xxxxxxxxx.xxxxx.xxx.xxx/snipe-it/app/Models/Ldap.php:262
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'ldap_search(): ...', '/home/xxxxx/inv...', 262, Array)
#1 /home/xxxxx/xxxxxxxxx.xxxxx.xxx.xxx/snipe-it/app/Models/Ldap.php(262): ldap_search(Resource id #487, 'RM. 307', '(&(sAMAccountTy...')
#2 /home/xxxxx/xxxxxxxxx.xxxxx.xxx.xxx/snipe-it/app/Console/Commands/LdapSync.php(128): App\Models\Ldap::findLdapUsers('RM. 307')
#3 [internal function]: App\Console\Commands\LdapSync->handle()
#4 /home/xxxxx/xxxxxxxxx.xxxxx.xxx.xxx/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#5 /home/xxxxx/xxxxxxxxx.xxxxx.xxx.xxx/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#6 /home/xxxxx/xxxxxxxxx.xxxxx.xxx.xxx/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#7 /home/xxxxx/xxxxxxxxx.xxxxx.xxx.xxx/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#8 /home/xxxxx/xxxxxxxxx.xxxxx.xxx.xxx/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#9 /home/xxxxx/xxxxxxxxx.xxxxx.xxx.xxx/snipe-it/vendor/symfony/console/Command/Command.php(252): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#10 /home/xxxxx/xxxxxxxxx.xxxxx.xxx.xxx/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#11 /home/xxxxx/xxxxxxxxx.xxxxx.xxx.xxx/snipe-it/vendor/symfony/console/Application.php(946): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/xxxxx/xxxxxxxxx.xxxxx.xxx.xxx/snipe-it/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\LdapSync), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/xxxxx/xxxxxxxxx.xxxxx.xxx.xxx/snipe-it/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/xxxxx/xxxxxxxxx.xxxxx.xxx.xxx/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /home/xxxxx/xxxxxxxxx.xxxxx.xxx.xxx/snipe-it/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 {main}

- Any errors that appear in your browser's error console. - n/a
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - unsure how to reproduce ldap error on demo w/o putting in credentials
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - increased PHP memory

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by jmcdowell21** [comment]
Currently, the Base Bind DN is "dc=campusad,dc=msu,dc=edu". After looking at the documentation and other issues this looks correct to me but it's still returning the Invalid DN syntax error.

**Comment by EarlRamirez** [comment]
@jmcdowell21  for the DN error you can confirm this by using the _dsquery_ command to get the full DN, don't know if this will resolve your issue, I think it's worth a shot.

What is the memory limit in your php.ini?

**Comment by jmcdowell21** [comment]
@EarlRamirez I don't have access to the AD server (the DN was provided by another group within IT). I can contact them and have them pull the full DN though.

The memory limit is currently set to 1024MB.

**Comment by jmcdowell21** [comment]
@EarlRamirez I heard back from the AD group, the DN I have is the full DN.

**Comment by EarlRamirez** [comment]
@jmcdowell21  glad that you confirm that the DN is correct, currently, I am not in the environment where I can try and reproduce this; however, hopefully, in a few days I'll be able to and see if we can get this resolved. 

You can try and increase the memory temporarily and see if it will resolve the issue, I will have to do some research on this to be able to help you better

**Comment by jmcdowell21** [comment]
@EarlRamirez Awesome! Thank you very much, I look forward to hearing back. In the meantime, I'll check on what steps we'll need to take to increase memory to the server.
