### ISSUE TITLE
How to access the login page?

### ISSUE THREAD

**Issue by amandagomesb** [snipe/snipe-it#614]
Good evening. Did all the installation correctly, but do not know what the final step to get to the login page. The apache virtual host is already configured for the public folder, and when I access the returned page is:

![initialpage](https://cloud.githubusercontent.com/assets/6208272/6538969/3ad27288-c448-11e4-96b3-9c5559e8a9e4.JPG)

Thanks!

**Comment by dbierspb** [comment]
It sounds like you don't have PHP installed at the moment if it is just returning the source code of the main page.

Is that what is happening?

**Comment by snipe** [comment]
That's what it sounds like to me too, tho I'm not sure how you got through the installation without having php installed. Maybe php-cli only? That would be weird.

**Comment by splaer** [comment]
Either you do not have apache php module enabled or you do not have directory index set to index.php

Both are very common and depending on the version of apache and the os you are running have slightly different fixes. If running Linux then you need the mod php package. They provide a so file for apache. Glad to offer more assistance if we have a few more details.

**Comment by snipe** [comment]
Even if apache's default index is not set to index.php, it should still not display PHP code on the page. Php is simply not running, or somehow the Apache directives are not looking at .php files as files that should be parsed by php.

**Comment by dbierspb** [comment]
What OS is this on?

**Comment by amandagomesb** [comment]
Friends,
Thanks for the initial help of all. I'm picking up items you mentioned. To advance, my operating system is Ubuntu 14.04.2 and related to PHP, I have the following packages installed:

![image](https://cloud.githubusercontent.com/assets/6208272/6564685/84bebda0-c689-11e4-9ef6-21378ac02f13.png)

Post more information soon!

Thank you!

**Comment by amandagomesb** [comment]
Friends,
Again, thank you.
As the splaer commented, missing just install apache php module!

sudo apt-get install libapache2-mod-php5

I can have the home page and log in, no problems!
Thank you.

Hugs,
Amanda Gomes.
