### ISSUE TITLE
Feature Request - Email Audit

### ISSUE THREAD

**Issue by aporzio1** [snipe/snipe-it#6147]
It would be great to be able to have snipe-it email the user a list of assets that are checked out to them and then they be able to approve or submit corrections and have an admin in snipe it be able to approve the correction.

**Comment by aporzio1** [comment]
An example would be according to my assets, I have a laptop and an iPad. But I returned that iPad 2 months ago and it was never removed from my inventory. 

So I would get this email showing what I have and if everything is correct then I click a button that says approve. If it is not then I know I need to get that straighted out before I can approve it.

**Comment by snipe** [comment]
I think the best we would do for that would be to periodically send users a list of what they have. If they have disputes, they can reply to the IT dept to sort it out.

**Comment by snipe** [comment]
Emailable report will be available in v5, per https://github.com/snipe/snipe-it/commit/77cdb2f409ccf8cfbd94fb26847b3ea205a3e22a

**Comment by davepage-mcr** [comment]
Just +1 for this feature, will be super handy for us :)
