### ISSUE TITLE
Check out/in reports

### ISSUE THREAD

**Issue by mirso1703** [snipe/snipe-it#6149]
Good morning,

we have started using your tool in our IT Department and what we noticed that there is no option in exporting a check out/in reports lets say as a device delivery and device damage reports.

This would be really helpful as some of the users don't have an account and we need their signature that they got the device.

It would be good if you could make a digital signature so let's say, check out and if you want a recipient's signature, we open a device on an iPad or iPod and give the user to sign, and while checking out it goes in the notes and stores in history and you can print it 

As we are managing a company which has over 5000 employees and thousands of devices , this thing would be really helpful.

**Comment by snipe** [comment]
> we have started using your tool in our IT Department and what we noticed that there is no option in exporting a check out/in reports lets say as a device delivery and device damage reports.

That's not a bad idea. We'll look into adding that.

> It would be good if you could make a digital signature so let's say, check out and if you want a recipient's signature, we open a device on an iPad or iPod and give the user to sign, and while checking out it goes in the notes and stores in history and you can print it

This feature already exists: 
https://snipe-it.readme.io/docs/requiring-acceptance

**Comment by awtivy** [comment]
Any word on new reports for check-in/out history?

**Comment by lubna201** [comment]
exporting a check out/in reports lets say as a device delivery and device damage reports.- did you added this feature
