### ISSUE TITLE
Email header banner bug

### ISSUE THREAD

**Issue by toblerooon** [snipe/snipe-it#6154]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After upgrading from 4.2 to 4.6, email header is kind of.. different. Font style is not the same as it was before the upgrade but the color changes as I change it on Admin > Branding. Need to fix this as the text from the email header is barely visible

**To Reproduce**
Can't replicate on demo. Tried downgrading to 4.2, worked fine.

**Expected behavior**
It should at least display the same font style and size it had on the previous versions. 

**Server (please complete the following information):**
 - Snipe-IT Version: **4.6**
 - OS: [e.g. Ubuntu, CentOS]: **Ubuntu 16.04 LTS**
 - Web Server: [e.g. Apache, IIS] **Apache**
 - PHP Version: **PHP 7**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] **Linux Mint 17.3 Cinnamon**
 - Browser [e.g. chrome, safari]: **Chrome**
 - Version [e.g. 22] **68**

**Additional context**
- Is this a fresh install or an upgrade? **Upgrade**
- What OS and web server you're running Snipe-IT on? **Ubuntu 16.04 LTS, in Chrome browser**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Git**
- Include what you've done so far in the installation, and if you got any error messages along the way. **None**
- Indicate whether or not you've manually edited any data directly in the database **No**

**Comment by snipe** [comment]
Can you please provide before/after screenshots?

**Comment by Heyroon** [comment]
**Before upgrade:**
![received_1964157577222543](https://user-images.githubusercontent.com/38780052/45128710-1b975e00-b1b2-11e8-911b-ad819a12ac52.png)

**After upgrade:**
![received_471286836702115](https://user-images.githubusercontent.com/38780052/45128721-218d3f00-b1b2-11e8-8df4-a7f77bee1360.png)

**Comment by Heyroon** [comment]
I'll try that. But do you think you can add a customization feature for emails sent?

**Comment by Heyroon** [comment]
Oh I see. Guess I'll settle with this in the meantime. Thanks!
