### ISSUE TITLE
Snipe not working on Debian 18.04

### ISSUE THREAD

**Issue by rodriguesjpmunch** [snipe/snipe-it#6155]
#### Actual Behavior
(what you expect to happen goes here)
Installed a fresh install as on https://snipe-it.readme.io/docs/downloading and ran the install.sh, after all the automatic settings the webpage does not want to open up. 

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode > No, commands after debug not working
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) > Yes
-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh Install
- Version of Snipe-IT you're running: Downloaded directly from/with GitHub command, believe the latest version
- Version of PHP you're running: Downloaded directly from/with GitHub command install.sh, standard one that comes with v4.6.3
- Version of MySQL/MariaDB you're running > Downloaded directly from/with GitHub command install.sh, standard one that comes with v4.6.3
- What OS and web server you're running Snipe-IT on: Ubuntu 18.04.1 LTS / Apache (Downloaded directly from/with GitHub command install.sh, standard one that comes with v4.6.3)
- What method you used to install Snipe-IT : install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error > No
- Indicate whether or not you've manually edited any data directly in the database > No

The weird thing I can see is that when running the Handy commands; the following commands gives issues with errors;

# composer clear-compiled
  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "clear-compiled" is not defined.

 # php artisan config:clear
PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/snipeit/app/Exceptions/Handler.php:39
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(320): App\Exceptions\Handler->report(Object(Dotenv\Exception\InvalidFileException))
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(124): Illuminate\Foundation\Console\Kernel->reportException(Object(Dotenv\Exception\InvalidFileException))
#2 /var/www/snipeit/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 {main}
  thrown in /var/www/snipeit/app/Exceptions/Handler.php on line 39

**Comment by snipe** [comment]
When you see a "Class Log not found" error, it usually means there's a syntax error in your .env file. 
https://snipe-it.readme.io/docs/installation-issues#section-fatal-error-uncaught-exception-reflectionexception-with-message-class-log-does-not-exist

**Comment by rodriguesjpmunch** [comment]
Thanks gents for the replies. 
Still investigating and struggeling. 
Not so a pro with these apache servers. 

.env file here; 

Created By Snipe-it Installer
# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=ChangeMe
APP_URL=http://snipeit2
APP_TIMEZONE=Etc/UTC
APP_LOCALE=en

# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=snipeit
DB_USERNAME=snipeit
DB_PASSWORD= '456 48 Berry Aster'
DB_PREFIX=null
DB_DUMP_PATH='/usr/bin'
DB_CHARSET=utf8mb4
DB_COLLATION=utf8mb4_unicode_ci

# --------------------------------------------
# OPTIONAL: SSL DATABASE SETTINGS
# --------------------------------------------
DB_SSL=false
DB_SSL_KEY_PATH=null
DB_SSL_CERT_PATH=null
DB_SSL_CA_PATH=null
DB_SSL_CIPHER=null

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=
MAIL_PORT=25
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=
MAIL_FROM_ADDR=snipeit@domainname.co.za
MAIL_FROM_NAME='Snipe IT Asset'
MAIL_REPLYTO_ADDR=support@domainname.co.za
MAIL_REPLYTO_NAME='Support Team'

# --------------------------------------------
# REQUIRED: IMAGE LIBRARY
# This should be gd or imagick
# --------------------------------------------
IMAGE_LIB=gd

# --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME=snipeit_session
COOKIE_DOMAIN=null
SECURE_COOKIES=false

# --------------------------------------------
# OPTIONAL: SECURITY HEADER SETTINGS
# --------------------------------------------
REFERRER_POLICY=same-origin
ENABLE_CSP=false

# --------------------------------------------
# OPTIONAL: CACHE SETTINGS
# --------------------------------------------
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

# --------------------------------------------
# OPTIONAL: REDIS SETTINGS
# --------------------------------------------
REDIS_HOST=null
REDIS_PASSWORD=null
REDIS_PORT-null

# --------------------------------------------
# OPTIONAL: AWS S3 SETTINGS
# --------------------------------------------
AWS_SECRET=null
AWS_KEY=null
AWS_REGION=null
AWS_BUCKET=null

# --------------------------------------------
# OPTIONAL: LOGIN THROTTLING
# --------------------------------------------
LOGIN_MAX_ATTEMPTS=5
LOGIN_LOCKOUT_DURATION=60

# --------------------------------------------
# OPTIONAL: MISC
# --------------------------------------------
APP_LOG=single
APP_LOG_MAX_FILES=10
APP_LOCKED=false
FILESYSTEM_DISK=local
APP_TRUSTED_PROXIES=192.168.1.1,10.0.0.1
ALLOW_IFRAMING=false
APP_CIPHER=AES-256-CBC
GOOGLE_MAPS_API=
BACKUP_ENV=true

**Comment by snipe** [comment]
Is the "Created By Snipe-it Installer" at the top of the .env file just like in your example? Or is there a pound symbol in front of it?

**Comment by rodriguesjpmunch** [comment]
No pound symbol. Will insert and test.

**Comment by snipe** [comment]
That doesn't look like the same issue, that looks like a totally different issue. That's the default ubuntu page, which means your web server isn't looking in the right place for your Snipe-IT installation.  I'd need to see your apache configuration to see what might be wrong there.

**Comment by rodriguesjpmunch** [comment]
snipe2.conf file in Apache folder under "sites-available"

<VirtualHost *:80>
  <Directory /var/www/snipeit/public>
      Allow From All
      AllowOverride All
      Options -Indexes
  </Directory>

  DocumentRoot /var/www/snipeit/public
  ServerName snipeit2
</VirtualHost>

Apache2.conf FILE Here

# This is the main Apache server configuration file.  It contains the
# configuration directives that give the server its instructions.
# See http://httpd.apache.org/docs/2.4/ for detailed information about
# the directives and /usr/share/doc/apache2/README.Debian about Debian specific
# hints.
#
#
# Summary of how the Apache 2 configuration works in Debian:
# The Apache 2 web server configuration in Debian is quite different to
# upstream's suggested way to configure the web server. This is because Debian's
# default Apache2 installation attempts to make adding and removing modules,
# virtual hosts, and extra configuration directives as flexible as possible, in
# order to make automating the changes and administering the server as easy as
# possible.

# It is split into several files forming the configuration hierarchy outlined
# below, all located in the /etc/apache2/ directory:
#
#       /etc/apache2/
#       |-- apache2.conf
#       |       `--  ports.conf
#       |-- mods-enabled
#       |       |-- *.load
#       |       `-- *.conf
#       |-- conf-enabled
#       |       `-- *.conf
#       `-- sites-enabled
#               `-- *.conf
#
#
# * apache2.conf is the main configuration file (this file). It puts the pieces
#   together by including all remaining configuration files when starting up the
#   web server.
#
# * ports.conf is always included from the main configuration file. It is
#   supposed to determine listening ports for incoming connections which can be
#   customized anytime.
#
# * Configuration files in the mods-enabled/, conf-enabled/ and sites-enabled/
#   directories contain particular configuration snippets which manage modules,
#   global configuration fragments, or virtual host configurations,
#   respectively.
#
#   They are activated by symlinking available configuration files from their
#   respective *-available/ counterparts. These should be managed by using our
#   helpers a2enmod/a2dismod, a2ensite/a2dissite and a2enconf/a2disconf. See
#   their respective man pages for detailed information.
#
# * The binary is called apache2. Due to the use of environment variables, in
#   the default configuration, apache2 needs to be started/stopped with
#   /etc/init.d/apache2 or apache2ctl. Calling /usr/bin/apache2 directly will not
#   work with the default configuration.


# Global configuration
#

#
# ServerRoot: The top of the directory tree under which the server's
# configuration, error, and log files are kept.
#
# NOTE!  If you intend to place this on an NFS (or otherwise network)
# mounted filesystem then please read the Mutex documentation (available
# at <URL:http://httpd.apache.org/docs/2.4/mod/core.html#mutex>);
# you will save yourself a lot of trouble.
#
# Do NOT add a slash at the end of the directory path.
#
#ServerRoot "/etc/apache2"

#
# The accept serialization lock file MUST BE STORED ON A LOCAL DISK.
#
#Mutex file:${APACHE_LOCK_DIR} default

#
# The directory where shm and other runtime files will be stored.
#

DefaultRuntimeDir ${APACHE_RUN_DIR}

DefaultRuntimeDir ${APACHE_RUN_DIR}

#
# PidFile: The file in which the server should record its process
# identification number when it starts.
# This needs to be set in /etc/apache2/envvars
#
PidFile ${APACHE_PID_FILE}

#
# Timeout: The number of seconds before receives and sends time out.
#
Timeout 300

#
# KeepAlive: Whether or not to allow persistent connections (more than
# one request per connection). Set to "Off" to deactivate.
#
KeepAlive On

#
# MaxKeepAliveRequests: The maximum number of requests to allow
# during a persistent connection. Set to 0 to allow an unlimited amount.
# We recommend you leave this number high, for maximum performance.
#
MaxKeepAliveRequests 100

#
# KeepAliveTimeout: Number of seconds to wait for the next request from the
# same client on the same connection.
#
KeepAliveTimeout 5


# These need to be set in /etc/apache2/envvars
User ${APACHE_RUN_USER}
Group ${APACHE_RUN_GROUP}

#
# HostnameLookups: Log the names of clients or just their IP addresses
# e.g., www.apache.org (on) or 204.62.129.132 (off).
# The default is off because it'd be overall better for the net if people
# had to knowingly turn this feature on, since enabling it means that
# each client request will result in AT LEAST one lookup request to the
# nameserver.
#
HostnameLookups Off

# ErrorLog: The location of the error log file.
# If you do not specify an ErrorLog directive within a <VirtualHost>
# container, error messages relating to that virtual host will be
# logged here.  If you *do* define an error logfile for a <VirtualHost>
# container, that host's errors will be logged there and not here.
#
ErrorLog ${APACHE_LOG_DIR}/error.log

#
# LogLevel: Control the severity of messages logged to the error_log.
# Available values: trace8, ..., trace1, debug, info, notice, warn,
# error, crit, alert, emerg.
# It is also possible to configure the log level for particular modules, e.g.
# "LogLevel info ssl:warn"
#
LogLevel warn

# Include module configuration:
IncludeOptional mods-enabled/*.load
IncludeOptional mods-enabled/*.conf

# Include list of ports to listen on
Include ports.conf


# Sets the default security model of the Apache2 HTTPD server. It does
# not allow access to the root filesystem outside of /usr/share and /var/www.
# The former is used by web applications packaged in Debian,
# the latter may be used for local directories served by the web server. If
# your system is serving content from a sub-directory in /srv you must allow
# access here, or in any related virtual host.
<Directory />
        Options FollowSymLinks

<Directory />
        Options FollowSymLinks
        AllowOverride None
        Require all denied
</Directory>

<Directory /usr/share>
        AllowOverride None
        Require all granted
</Directory>

<Directory /var/www/>
        Options Indexes FollowSymLinks
        AllowOverride None
        Require all granted
</Directory>

#<Directory /srv/>
#       Options Indexes FollowSymLinks
#       AllowOverride None
#       Require all granted
#</Directory>




# AccessFileName: The name of the file to look for in each directory
# for additional configuration directives.  See also the AllowOverride
# directive.
#
AccessFileName .htaccess

#
# The following lines prevent .htaccess and .htpasswd files from being
# viewed by Web clients.
#
<FilesMatch "^\.ht">
        Require all denied
</FilesMatch>


#
# The following directives define some format nicknames for use with
# a CustomLog directive.
#
# These deviate from the Common Log Format definitions in that they use %O
# (the actual bytes sent including headers) instead of %b (the size of the
# requested file), because the latter makes it impossible to detect partial
# requests.
#
# Note that the use of %{X-Forwarded-For}i instead of %h is not recommended.
# Use mod_remoteip instead.
#
LogFormat "%v:%p %h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" vhost_combined
LogFormat "%h %l %u %t \"%r\" %>s %O \"%{Referer}i\" \"%{User-Agent}i\"" combined
LogFormat "%h %l %u %t \"%r\" %>s %O" common
LogFormat "%{Referer}i -> %U" referer
LogFormat "%{User-agent}i" agent

# Include of directories ignores editors' and dpkg's backup files,
# see README.Debian for details.

# Include generic snippets of statements
IncludeOptional conf-enabled/*.conf

# Include the virtual host configurations:
IncludeOptional sites-enabled/*.conf

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet

**Comment by snipe** [comment]
What do you have in your `sites-enabled` directory?

**Comment by rodriguesjpmunch** [comment]
lrwxrwxrwx 1 root root   35 Sep  4 09:00 000-default.conf -> ../sites-available/000-default.conf
lrwxrwxrwx 1 root root   31 Sep  4 09:01 snipeit.conf -> ../sites-available/snipeit.conf

**Comment by snipe** [comment]
Try `sudo a2dissite 000-default.conf`

**Comment by snipe** [comment]
(And restart the web server)

**Comment by jasonbone75** [comment]
> snipe2.conf file in Apache folder under "sites-available"

> lrwxrwxrwx 1 root root 31 Sep 4 09:01 snipeit.conf -> ../sites-available/snipeit.conf

snipeit.conf enabled but snipe2.conf available??

**Comment by snipe** [comment]
Whatever one was generated by the installer should be the one that's active. `000-default.conf` can override (since it gets loaded first, because of the 000).

**Comment by rodriguesjpmunch** [comment]
Disabled successfully, but the webpage still not opening.

**Comment by snipe** [comment]
Can you be more specific? Different error, same error, etc?

**Comment by rodriguesjpmunch** [comment]
![image](https://user-images.githubusercontent.com/42966640/45220090-6053ef80-b2ad-11e8-89f7-4988224d04db.png)

URL still not working. That's all I want to get up and running is the webpage.

**Comment by snipe** [comment]
What's in your `sites-available` dir now? Where does your `snipeit2.conf` live? You should only have one, either `snipeit2.conf` or `snipeit.conf` in that directory. Try editing `snipeit.conf` to have the same info as your `snipeit2.conf` and restart the server.

**Comment by rodriguesjpmunch** [comment]
Hey Gents, thanks for your time and effort.
I just nuked and start from scratch and followed a other installation path.
