### ISSUE TITLE
Ability to choose columns for report view (Users' asset view display)

### ISSUE THREAD

**Issue by sickyazone** [snipe/snipe-it#6157]
**Server:**
 - Snipe-IT Version: 4.6.2 Build 3866 (master)
 - OS: Windows Server 2016, Build 1607
 - Web Server: IIS 10
 - PHP Version: 7.2.4

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
When our users/employees log in, they are able to see the assets they have checked out and the assets name. 
Is it possible for them to also see the purchase date of the asset and/or other columns? 
I couldn’t find anything in the group permission settings regarding giving access to columns on the “View Assets” page under oursnipeitsite.com/account/view-assets.

**Comment by sickyazone** [comment]
This is still relevant, but nobody have given me any updates if it's something they're even gonna do.

**Comment by adam-zieba** [comment]
Hi!
I have this same problem. Is there any premission that allows user to see custom fields after log in? Our group "users" does not have any permission granted.
