### ISSUE TITLE
Weird check for Ldap Account active

### ISSUE THREAD

**Issue by Thoro** [snipe/snipe-it#6158]
The code in LdapSync.php from #3640 uses this check:

``` 
                if( array_key_exists('useraccountcontrol', $results[$i]) ) {
                    $enabled_accounts = [
                        '512', '544', '66048', '66080', '262656', '262688', '328192', '328224'
                    ];
                    $item['activated'] = ( in_array($results[$i]['useraccountcontrol'][0], $enabled_accounts) ) ? 1 : 0;
                } else {
                    $item['activated'] = 0;
                }
```

But AD actually defines pretty well that ACCOUNTDISABLE is 0x2, is there any specific reason to have the non-exhaustive list?

Wouldn't a check like this be better:

``` 
                if( array_key_exists('useraccountcontrol', $results[$i]) ) {
                    $item['activated'] = ($results[$i]['useraccountcontrol'][0] & 0x2) === 0x2 ? 0 : 1;
                } else {
                    $item['activated'] = 0;
                }
```

Additionally in the documentation https://snipe-it.readme.io/v4.6.3/docs/ldap-sync-login there is this ldap filter:

&(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))

which will exclude any deactivated users and break the disabling user account feature

**Comment by snipe** [comment]
> Wouldn't a check like this be better:

I don't think there was a specific reason it was limited. 

> which will exclude any deactivated users and break the disabling user account feature

Yes, not everyone wants to import AD-deactivated users at all. There are a lot of different ways people use the syncing features and for many, they'll have thousands of deactivated users (schools, for example), that they don't want to import at all, not just import and leave as deactivated.

**Comment by Thoro** [comment]
So, we could adapt the check in the sync. (I can give a PR)

And amend the documentation with that mention.

**Comment by elkbullwinkle** [comment]
This change broke our sync with freeipa now all accounts are disabled after the sync.

**Comment by elkbullwinkle** [comment]
`
else {
                    $item['activated'] = 0;
                }`
`
This fallback change disables all users account imported from Ldap which don't have this Active directory specific field.

**Comment by Thoro** [comment]
Pretty sure you mean the change in #3640 , how are accounts disabled in FreeIPA? 

In this case I would add another check where the corresponding field can be set in the settings.
