### ISSUE TITLE
更换语言后，系统语言只在登录界面变了，其他依然是英文

### ISSUE THREAD

**Issue by cx6067682** [snipe/snipe-it#6159]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
有多种语言设置。 一个是应用程序，但也有一个配置文件级别设置。 在应用程序级别设置它将为没有用户语言集的任何人以及未登录的任何人更改它。

进入您的个人资料并将您的语言更改为中文。

如果可以，也请尝试用英语发帖。

**Comment by cx6067682** [comment]
我把中文的配置文件覆盖英文配置文件，完美解决！用户界面更改语言，菜单里面依然是英文！配置文件.env更改语言也是一样！

发自我的 iPhone

**Comment by snipe** [comment]
我真的不明白你用英文翻译中文confiig文件是什么意思。 我已经解释了配置如何工作。

`env APP_LOCALE`是您开始使用的默认语言。 它用于快速入门/设置页面。

“管理员设置>本地化”设置整体应用程序语言，如登录页面，以及没有在用户级别指定语言的任何登录用户。

“用户配置文件 - >语言”确定您以该用户身份登录时看到的语言。

**Comment by awaiter** [comment]
对啊 怎么汉化呢

**Comment by cx6067682** [comment]
最简单的就是备份英文，用中文覆盖！这个汉化做的不太好

发自我的iPhone

**Comment by Leezj9671** [comment]
> 最简单的就是备份英文，用中文覆盖！这个汉化做的不太好 发自我的iPhone
> […](#)
> 在 2020年9月14日，下午5:14，suntao098 ***@***.***> 写道： ﻿ 对啊 怎么汉化呢 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请问用中文覆盖是什么意思？能在哪里找到中文的呢？

**Comment by snipe** [comment]
@Leezj9671 Please see the localization documentation: https://snipe-it.readme.io/docs/localization 

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/localization">Localization</a></strong></div><div>Set the language and time/date display of your Snipe-IT installation</div></blockquote>

**Comment by cx6067682** [comment]
覆盖就是找到英文那个文件夹，把从官网下载的汉化包替换掉英文的文件夹

发自我的iPhone

**Comment by snipe** [comment]
就像我在其他地方提到的那样，请务必以英语发布问题和评论，因为这是我们的母语，并且任何其他通信都必须通过Google Translate进行。

如果您正在运行Snipe-IT，则中文翻译将包含在您已下载的Snipe-IT发行版中。 您只需要在上面链接中提到的三个不同位置中选择该语言（而不是英语）即可。 APP_LOCALE，“本地化”下的“管理员设置”以及用户的语言个人偏好。

您应该*绝对*不要覆盖任何语言文件夹。 如果您发现中文翻译不正确，请按照公认的翻译流程进行操作并提交更正：
https://snipe-it.readme.io/docs/translations

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/translations">Translations</a></strong></div><div>Traduci! 翻訳！Oversette! Traduire! 번역하기! แปล! ¡Traducir! Przetłumacz! Übersetzen!</div></blockquote>
