### ISSUE TITLE
Deleted Assets Page, 500 Internal Server Error

### ISSUE THREAD

**Issue by dguedry** [snipe/snipe-it#616]
When trying to view assets->deleted, I'm getting a 500 error on both the demo site and my local installation.

http://demo.snipeitapp.com/hardware?Deleted=true

**Comment by snipe** [comment]
Please see the documentation on getting help. http://snipeitapp.com/documentation/getting-help/

**Comment by dguedry** [comment]
Version 1.2.6
Error 500 - Internal Server Error

Log file output:
[2015-03-12 10:11:50] production.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in /var/www/html/snipe-it-1.2.6/app/storage/views/51d739af55050583e02c0a1ac3af37b9:95
Stack trace:
#0 /var/www/html/snipe-it-1.2.6/app/storage/views/51d739af55050583e02c0a1ac3af37b9(95): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', '/var/www/html/s...', 95, Array)
#1 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(9830): include('/var/www/html/s...')
#2 /var/www/html/snipe-it-1.2.6/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/s...', Array)
#3 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(9708): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/s...', Array)
#4 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(9695): Illuminate\View\View->getContents()
#5 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(9686): Illuminate\View\View->renderContents()
#6 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(10388): Illuminate\View\View->render()
#7 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(9918): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#8 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(5222): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#9 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(5030): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#10 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(5016): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#11 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(721): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(702): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#13 /var/www/html/snipe-it-1.2.6/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(7779): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(8386): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(8333): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(10992): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#18 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(664): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#19 /var/www/html/snipe-it-1.2.6/public/index.php(49): Illuminate\Foundation\Application->run()
#20 {main}

Next exception 'ErrorException' with message 'Trying to get property of non-object (View: /var/www/html/snipe-it-1.2.6/app/views/backend/hardware/index.blade.php)' in /var/www/html/snipe-it-1.2.6/app/storage/views/51d739af55050583e02c0a1ac3af37b9:95
Stack trace:
#0 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(9832): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /var/www/html/snipe-it-1.2.6/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/var/www/html/s...', Array)
#2 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(9708): Illuminate\View\Engines\CompilerEngine->get('/var/www/html/s...', Array)
#3 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(9695): Illuminate\View\View->getContents()
#4 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(9686): Illuminate\View\View->renderContents()
#5 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(10388): Illuminate\View\View->render()
#6 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(9918): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(5222): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(5030): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(5016): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(721): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(702): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /var/www/html/snipe-it-1.2.6/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(7779): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(8386): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(8333): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(10992): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /var/www/html/snipe-it-1.2.6/bootstrap/compiled.php(664): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /var/www/html/snipe-it-1.2.6/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []

**Comment by snipe** [comment]
Please delete your seed data and try again. There was a bug in the seed data that causes this issue. It's been resolved, but it not in a release yet.
