### ISSUE TITLE
Import not working well in 4.6.2

### ISSUE THREAD

**Issue by Arsenal10108** [snipe/snipe-it#6160]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When importing a long CSV File, Approximatey 800 Assets (seems like file size is anything over 16k) the import just hangs... on top of that it seems to be missing several assets that were on the CSV. Possibly ones that are not assigned to anyone. 
I tried to upgrade to 4.6.3, it looks like with went through, I cleared cookies and it still shows 4.6.2 

**To Reproduce**
Upload Large CSV and click import :)

**Expected behavior**
I expect all assets on CSV to be imported. 
**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.2
 - OS:  Ubuntu
 - Web Server: Apache 7
 - PHP Version  7.0.30

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome/Firefox
 - Version: Latest

**Smartphone (please complete the following information):**

**Error Messages**
No Error messages... just hangs. 

**Additional context**
- Is this a fresh install or an upgrade? Upgrade
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT Composer
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Arsenal10108** [comment]
If I do a git pull I get a error: your local changes would be overwritten by merge, then it lists all the updates and then says please commit etc etc then quickly say aborting.

**Comment by snipe** [comment]
@Arsenal10108 you've made local changes, that's why. You can stash your changes and then try pulling again. https://git-scm.com/book/en/v1/Git-Tools-Stashing
