### ISSUE TITLE
Standard label printing to most common label sizes (Avery 5160)

### ISSUE THREAD

**Issue by lostmydog** [snipe/snipe-it#6161]
**Is your feature request related to a problem? Please describe.**
Right now, it's an absolute nightmare to setup snipe-it to print to labels. I spent all day editing and wasting dozens of sheets of Avery 5160 labels (which I'm assuming are the most widely used for this application) only to find out that the labels printed fine on one of my copiers, but printed with a shift to the left on a different copier (both Ricoh copiers, both have the same settings, same tray, same browser, same version, etc). I think it would be incredible if Snipe-it built in functionality to at least be able to print with 100% accuracy for the mentioned 5160 labels. I've read from others that its possible if you save the labels as a pdf first, so maybe its as simple as having the page that pops up when you 'generate labels' be an 8.5x11 pdf thats formatted to print correctly.

**Describe the solution you'd like**
An easy solution to print on Avery 5160 labels, as in give us the ability to choose that label whilst keeping the ability to do custom ones.

**Describe alternatives you've considered**
None, right now i have some copiers that print the label fine, others have a shift to the left

**Additional context**

**Comment by snipe** [comment]
> but printed with a shift to the left on a different copier (both Ricoh copiers, both have the same settings, same tray, same browser, same version, etc)

You can see how this is an impossible situation for us to troubleshoot, right? If it prints fine on one and not the other, the issue is with the printer settings somewhere. That page is just HTML.

**Comment by memtech3** [comment]
TIPWeb IT does it fine (different size labels). It generates a PDF file of the labels and you just have to remember to tell your printer not to autofit to page
