### ISSUE TITLE
Cannot seem to log in to system after new install

### ISSUE THREAD

**Issue by HitenKacha** [snipe/snipe-it#6162]
Hi 
I have just done a fresh install of Snipe-IT on a Windows 2016 server

all seemed to go ok (even though still have email issues)

had to make a small change in terms of the custom URL but after logging out I cannot seem to log back in now.

I have only got a few test accounts set up but I cannot log in with either account.

what options do I have to check if the user account is set up and change the password so I can log in?

thanks

Hiten

**Comment by snipe** [comment]
Hi Hiten - please use the issue template we provide, so that we can better answer your questions. For example, I don't have any idea what version you're using. 

Did you try a forgotten password request? Are you using LDAP, or are these local users? Try creating a new admin using the command line tool, and then provide whatever additional information you can. https://snipe-it.readme.io/docs/create-an-admin

**Comment by HitenKacha** [comment]
Hi Snipe

thanks for this - I will give this a go next week and hopefully I can get an admin user added via command line.

**Comment by HitenKacha** [comment]
Hi,

unfortunatly this did not work although i can see the user did get added to the db when i am browsing using HeidiSQL.

As suggested see below for all the details following the initial template 

**#### Expected Behavior (or desired behavior if a feature request)**

access the system when logging in using admin user name and password

-----

#### Actual Behavior

it does not seem to accecpt the username and password but there are no errors, it just seems to refresh the page back to the log in point - i also noticed when i go the site i get a insuecure contenct blocked, this page is trying to load scripts from a unathenticated source in google chrome

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode - not sure how to without being able to log in 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) - yes

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? This is a fresh first time install on a new server 
- Version of Snipe-IT you're running - 4.6.4
- Version of PHP you're running - 7.2.9
- Version of MySQL/MariaDB you're running 10.0.0.36
- What OS and web server you're running Snipe-IT on - Windows 2016 / IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. - see above on 'actual behaviour'
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help
