### ISSUE TITLE
[Feature Request] Managing invoices and delivery notes (non-financial point of view)

### ISSUE THREAD

**Issue by abazeed** [snipe/snipe-it#617]
Is their any way to manage the received (new) items and add them to the assets through invoices and delivery notes, currently I can add some invoice related details when adding a new asset like:
* Purchase Date
* Supplier
* Order Number
* Purchase Cost
* Warranty

But I have to repeat these details for each item in the list. I think it would be much easier to add new items using one centralized invoices form.

**Comment by abazeed** [comment]
I will explain how it goes in our IT department, and what matters and doesn't matter in our work; so it would be easier for you to understand.

## Contacting Financial dept. for the needed items [LPO]

We send them a list of needed items, they will contact their suppliers to get the best offer, then issue an LPO (Local Purchase Order) of the items, and send it to the chosen supplier. Here, we care only for:
* LPO Number
* LPO date

## Receiving the supplier invoice [INVOICE]

After the supplier receives the LPO, he will send us an invoice of that. Here, we care only for:
* Invoice Number
* Invoice Date
* Supplier Name

## Receiving the items from supplier [DELIVERY NOTE]

After that, we start receiving items from supplier, it could be received in a single delivery or many deliveries, so each invoice could have one or more delivery notes. Here, we care only for:
* Delivery Note Number
* Delivery Note date
* Invoice Number
* Items (Assets or Accessories) [Serials or Quantities]

Items Price is not necessary because it's not the IT dept. business, but it could be useful to add it.

**Comment by abazeed** [comment]
##### Suggested Workflow

* Our work starts after receiving the first delivery
* I will create one invoice:
   [Invoice Number, Invoice Date, LPO Number, LPO Date and Supplier]
* Assign one delivery note for that invoice
   [Delivery Note Number and Delivery Note Date]
* Add the items to that delivery note.
* When saving the delivery note, it will add the assets and accessories to the store.
* I have to do that for each delivery I'm receiving till I get all the items mentioned in the invoice.

**Comment by madd15** [comment]
curious if file uploads work for this?
![alt](http://i.imgur.com/ZjSlG9J.png)

**Comment by abazeed** [comment]
My idea is having a more efficient way to enter a bulk or a batch of new assets into the system through one step, and the best way to do that is using an invoices/deliveries module.
So I can get 2 advantages of that:
* More organized and centralized way to enter new assets.
* Tracking invoices, delivery notes and LPOs data for each asset.

Again, I don't care about the financial part of invoices, I care only for the date and the number of the invoice, LPO and delivery note of the asset only.

**Comment by snipe** [comment]
@abazeed I don't see any technical challenges with this, but I am a little concerned about the UX and workflow changes for folks who don't have the same kind of workflow that you do, or at least don't need to track it closely (which seems to be the majority of them). I'll need to think about this a bit.

**Comment by abazeed** [comment]
Thanks @snipe for your reply, I'm sure you will do it soon or later; because it's the right way to do that. :relaxed:

**Comment by vsposato** [comment]
@abazeed I would be careful with saying it is the right way to do it, as right is usually defined by your environment.

So, if I understood you correctly, basically you would start by creating a PO with the quantity of each model you ordered. 
You would then create an invoice for each delivery and assign the items that were delivered on that invoice, and would decrement items from the master PO.
You would continue this process until all items have been delivered. You would then close out the PO as being completely delivered.

This would allow you to support your process, but also allow you to add items independently of this larger process. Does that make sense?

**Comment by abazeed** [comment]
@vsposato thanks for your point of view, but here I don't care about the invoices and financial part of the process, I do care about the delivery part only.
I meant we can use one form to enter the delivered items in one step, and make extra advantage of that to enter other details that could be needed later such as PO no., delivery note no. and the total invoice no.
The process here will be easier, shorter and centralized. So I don't have to enter each item individually and repeat shared info for each item such as: price, purchase date, order number, warranty...

**Comment by snipe** [comment]
Would this not be solved by adding row assets and then updating their attributes through bulk edit?

<img width="1015" alt="screen shot 2015-07-28 at 10 18 09 pm" src="https://cloud.githubusercontent.com/assets/197404/8950450/9ba60a58-3576-11e5-857a-8de4f74df34a.png">

**Comment by abazeed** [comment]
This will work in case of updating current assets, but will not help in the new assets receiving process.
