### ISSUE TITLE
Assign bulk Consumables/Assets

### ISSUE THREAD

**Issue by bagetsro** [snipe/snipe-it#6171]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)
We wanted to integrate office supplies to snipe-it. how to i assign consumables/assets per quantity?
-----

#### Actual Behavior

(what actually happens goes here)
by default, 1 qty per consumable can only be assigned. it would be tedious to assign 30 ballpens one by one to a user. 
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  4fresh install
- Version of Snipe-IT you're running  - 4.6.4
- Version of PHP you're running -7.0.29
- Version of MySQL/MariaDB you're running -10.2.14
- What OS and web server you're running Snipe-IT on -wampp, windows 10
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) -composer
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by wessieaa** [comment]
Bulk consumables to be checked out would be great

**Comment by tymik** [comment]
dup of #5140

**Comment by wessieaa** [comment]
Yes please
