### ISSUE TITLE
Should be possible to Checkout an Accessorie to a location

### ISSUE THREAD

**Issue by raskas** [snipe/snipe-it#6176]
Currently it is only possible to checkout an Accessory to a user. In some case it would be handy to checkout an Accessory to a specific location.

For example:
The keyboard has a fixed location, like meeting room.
It is not assigned to a user nor is it available to be handed out to someone else.

**Comment by memtech3** [comment]
Coudnt this be done by checking out to asset?

**Comment by raskas** [comment]
That is not logical, as the accessory is not linked to any assets.

**Comment by Beefy-Swain** [comment]
I also need this.

Is it even possible to check out an accessory to an asset?

**Comment by raskas** [comment]
*bump*

**Comment by tymik** [comment]
dup of #5140 and #5720 

hope someone can take care of all these dups i mark today to clean up the issues list a bit.

**Comment by raskas** [comment]
It is still relevant

**Comment by asciiphil** [comment]
Still relevant.  I'd really like to have a pool of monitors that get checked out to lab rooms.  There's no person to assign them to, just a location.

**Comment by raskas** [comment]
It is still relevant

**Comment by hatimdegani** [comment]
yes this is relevant this feature is very important

**Comment by asciipip** [comment]
Yes, it's still relevant.

**Comment by hatimdegani** [comment]
No this isn't a stale request StaleBot. So please unmark it as stale. I'll keep this request on my priority as long as this feature request isn't added to the SnipeIT module.

**Comment by jjardis** [comment]
The use case for me is, we have many wall TV's at our office. The only present solutions are:
- Create an asset for every accessory.
- Create a user for each location.

Would be awesome not to restrict what can be checked out where.

**Comment by jjardis** [comment]
Yes, this is still relevant

**Comment by netman63** [comment]
We have the same here where many of our devices are checked out to location.  There's no good way to do this unless we're creating users out of every location...which at that point is hundreds and hundreds of our locations.  Some things just don't get checked out to people but are stationary in a location.

**Comment by jjardis** [comment]
This is still relevant.

**Comment by TinaMccray** [comment]
+1

**Comment by psmalley-ati** [comment]
This is still happening, and we need this feature!
