### ISSUE TITLE
New Email and Username Format

### ISSUE THREAD

**Issue by davidmatthews85** [snipe/snipe-it#6178]
**Server (please complete the following information):**
 - Snipe-IT Version - v4.6.4
 - OS: [e.g. Ubuntu, CentOS] - Ubuntu 18.04
 - Web Server: [e.g. Apache, IIS] - Apache
 - PHP Version - 7.1.20

**Is your feature request related to a problem? Please describe.**

New Formats to be included in the General Settings options

**Describe the solution you'd like**

Email Format:
A full stop between First Initial and Last Name (j.smith@example.com)

Username Format
First Name First Initial (janes@example.com)

Cheers,

Dave

**Comment by memtech3** [comment]
I would like to see a custom format so that you could create your own format
