### ISSUE TITLE
Including new bootstrap plugins

### ISSUE THREAD

**Issue by grifu** [snipe/snipe-it#6179]
Is it possible to include new bootstrap plugins in snipe-it?
It would be interesting to use eonasdan-bootstrap-datetimepicker to be able define date and time in the check outs.

**Comment by snipe** [comment]
(We can expand the current date picker to include time, but our system doesn't really care about specific times for check outs, just dates.)

**Comment by grifu** [comment]
Hi,

I appreciate your answer.

In our School we have to include time for the expected-checkin.
I’ve made a fork of snipeit (https://github.com/grifu/snipe-it <https://github.com/grifu/snipe-it>) to be able change the code and support the time for checkin. I’m completely new to laravel and using the eonasdan-bootstrap-datetimepicker which runs with BS3.

It works well, but I’m having some problems with the integration of eonasdan-bootstrap-datetimepicker. It compiles well and it is included in both all.js and all.css. However, it does not display the glyphicons. It does if I make a npm install and a npm run dev. It seems that it loads the icons from node_modules folder.

Do you know what am I doing wrong?

Thanks in advance.
