### ISSUE TITLE
Custom field encryption - edit asset makes it unreadable

### ISSUE THREAD

**Issue by mattiasvriens** [snipe/snipe-it#6180]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Creating custom fields with encryption box checked works fine. After filling in the field in a new asset the field shows the padlock icon and is readable. After editing any field for that asset, all encrypted fields are then unreadable.

I am using an admin user with all rights granted.

**To Reproduce**
1. Create custom field and check encryption checkbox
2. Add custom field to fieldset
3. Create asset with that fieldset
4. Fill in encrypted custom field.
5. Save the asset and look for the encrypted field when opening the asset.
6. Edit the asset. 
7. While editing you can see the value of the encrypted field changed. It is no longer readable.
8. Save the asset, you can no longer read the encrypted value. 
9. This is an issue, because I want to be able to read the value of an encrypted field when I need the information that is in it. 

**Expected behavior**
I expect the field to be readable when logged in with admin user.

**Server (please complete the following information):**
 - Snipe-IT Version : v4.6.3 build 3866 (master)
 - OS: Windows 10 Pro
 - Web Server: IIS 10.0.17134.1
 - PHP Version : 7.0.31

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser : Chrome
 - Version : 69.0.3497.81

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No error messages appear
- Any errors that appear in your browser's error console.
No errors appear
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Cannot reproduce on the demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
Last line in Laravel log is:
[2018-09-07 09:38:10] production.ERROR: backups backups : error: Failed to backup  because: The dump process failed with exitcode 1 : General error :   

**Additional context**
- Is this a fresh install or an upgrade? 
Fresh install
- What OS and web server you're running Snipe-IT on: 
Windows 10 Pro - IIS 10.0.17134.1
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual install
- Include what you've done so far in the installation, and if you got any error messages along the way.
Everything works fine so far. Only other issue I see is making a backup fails because the path specified is wrong. This is something I will tackle later, after testing for a little while longer.
- Indicate whether or not you've manually edited any data directly in the database
No.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by mattiasvriens** [comment]
![encryption](https://user-images.githubusercontent.com/40495670/45358250-28a8b880-b5c9-11e8-8e96-0babad682ce1.png)

Screenshot from before and after editing an asset

**Comment by mattiasvriens** [comment]
Anyone else experiencing this?

**Comment by mattiasvriens** [comment]
Can anyone here please let me know if they have seen this issue before.
Thank you

**Comment by klechacz** [comment]
Hi Mattiasvriens,
I have experience the exact same issue you are describing today on freshly installed software during the initial overview.
My quick overview of code points out to  _'snipe-it/resources/views/models/custom_fields_form.blade.php'_ line **15** where raw value of the field is passed to the code generating input form.  Bug seams to be only related to multi-line text areas and therefore raw value (encrypted) is displayed to user, after you click save it is 'encrypted again'. My bet would be code should probably be more similar to one in line **39** where 'gracefullDecrypt' is run on the value before editing view is generated. Also most likely extra conditions should be made here to disallow users without access to encrypted content to destroy the field. 
_Disclaimer_: At the same time it has been literally years since last time I have wrote anything in PHP so I am not sure I am the best person to try to fix/test this suspicions

**Comment by klechacz** [comment]
Hi Mattiasvriens,
  Following diff worked for me

diff --git a/resources/views/models/custom_fields_form.blade.php b/resources/views/models/custom_fields_form.blade.php                                                                                                                       
index b03fbd6..1851250 100644                                                                                                                                                                                                                
--- a/resources/views/models/custom_fields_form.blade.php                                                                                                                                                                                    
+++ b/resources/views/models/custom_fields_form.blade.php                                                                                                                                                                                    
@@ -12,7 +12,7 @@                                                                                                                                                                                                                            
                   Input::old($field->db_column_name(),(isset($item) ? $item->{$field->db_column_name()} : $field->defaultValue($model->id))), ['class'=>'format select2 form-control']) }}                                                  
                                                                                                                                                                                                                                             
               @elseif ($field->element=='textarea')                                                                                                                                                                                         
-                      <textarea class="col-md-6 form-control" id="{{ $field->db_column_name() }}" name="{{ $field->db_column_name() }}">{{ Input::old($field->db_column_name(),(isset($item) ? $item->{$field->db_column_name()} : $field->defaultValue($model->id))) }}</textarea>                                                                                                                                                                                                      
+                      <textarea class="col-md-6 form-control" id="{{ $field->db_column_name() }}" name="{{ $field->db_column_name() }}">{{ Input::old($field->db_column_name(),(isset($item) ? \App\Helpers\Helper::gracefulDecrypt($field, $item->{$field->db_column_name()})  : $field->defaultValue($model->id))) }}</textarea>                                                                                                                                                       
                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                             
               @elseif ($field->element=='checkbox')

**Comment by klechacz** [comment]
Hi StaleBot - yes - this issue still persists and requires changes described above into code.

**Comment by Vento96** [comment]
Hi all,

I am experiencing the same issue in which the custom encrypted field becomes unreadable after asset edit.

Can I kindly ask if there is any way to manually recover the value from that field? I've tried using OpenSSL and the APP_KEY to decrypt the string value from that custom field, however, decryption process fails.

I would be very grateful for any help.

Kind regards,
Jakub

**Comment by klechacz** [comment]
Hi Mate,
  Even though it should be possible - I previously failed to do so - moreover I needed to re-apply this changes to code after last upgrade of the product as I have almost lost 2 or 3 keys before observing this issue is still there after the upgrade :( 

The best I can do is try to paste the more current diff in format which hopefully will be readable

```
diff --git a/resources/views/models/custom_fields_form.blade.php b/resources/views/models/custom_fields_form.blade.php
index bb4d479..d43ab8f 100644
--- a/resources/views/models/custom_fields_form.blade.php
+++ b/resources/views/models/custom_fields_form.blade.php
@@ -12,8 +12,11 @@
                   Request::old($field->db_column_name(),(isset($item) ? \App\Helpers\Helper::gracefulDecrypt($field, $item->{$field->db_column_name()}) : $field->defaultValue($model->id))), ['class'=>'format select2 form-control']) }}
 
               @elseif ($field->element=='textarea')
-                      <textarea class="col-md-6 form-control" id="{{ $field->db_column_name() }}" name="{{ $field->db_column_name() }}">{{ Request::old($field->db_column_name(),(isset($item) ? $item->{$field->db_column_name()} : $field->defaultValue($model->id))) }}</textarea>
-
+               @if (($field->field_encrypted=='0') || (Gate::allows('admin')))         
+                      <textarea class="col-md-6 form-control" id="{{ $field->db_column_name() }}" name="{{ $field->db_column_name() }}">{{ Request::old($field->db_column_name(),(isset($item) ? \App\Helpers\Helper::gracefulDecrypt($field, $item->{$field->db_column_name()})  : $field->defaultValue($model->id))) }}</textarea>
+               @else
+                            <input type="text" value="{{ strtoupper(trans('admin/custom_fields/general.encrypted')) }}" class="form-control disabled" disabled>
+                @endif
 
               @elseif ($field->element=='checkbox')
                     <!-- Checkboxes -->
```

**Comment by uberbrady** [comment]
@Vento96 you can try to open up Tinker (`php artisan tinker`) and mess around in the console - 

```php
$a = \App\Models\Asset::find(YOUR_ASSET_ID);
$a->the_snipeit_custom_field_name
```

And then perhaps you might be able to retrieve it?

Also, for decryption, try:
```
\Crypt::Decrypt($a->something)
```

**Comment by uberbrady** [comment]
@klechacz If you don't want your customized changes to get blown out on each upgrade - you could submit a PR with your changes and we will very likely accept them. Then they'll be in the actual source, and you should be all set.

We'll of course be happy to discuss what your change is doing and why it's needed and all that as well, in that process, if needed.

**Comment by klechacz** [comment]
hi @uberbrady,
  The only issue is I do not have a tooling for PHP set up on any of the workstations I currently have access to to properly go through whole PR process ... besides my PHP skills ... should have been called 'gone' at least five years ago ;)

As I understand it the root cause of the issue is that when the form is loaded for the admin the value in the field is not decrypted - but rather hex value of the enciphered form is put into the text-field. Therefore if you click save - the hex value of the encrypted form is considered new plain-text and saved. 

In the diff above I have basically used the snippet from the view presenting the asset details -  which was decrypting the value to plaintext and put it as the source for initial value of the edit form. Seams to work for us - however this changes are extremely crude and I am not sure about potential side-effects (eg. if the change tracking on the field value works properly etc.)
