### ISSUE TITLE
Ability to set a Shift / Offset for Label Printing in order to reuse same Sticker Sheet few times

### ISSUE THREAD

**Issue by fixlair** [snipe/snipe-it#6182]
**Server (please complete the following information):**
N/A : Cloud Version of Snipe IT

**Is your feature request related to a problem? Please describe.**
When using A4 sticker sheet on Printer for Label Printing we will print few Label (let say 10 for exemple) but the Sheet has a capacity of 65 Label => 55 label could be used on the Sheet 

**Describe the solution you'd like**
 It would be useful (and Eco Friendly) to be able to set a Shift / offset to start not at 0 but at a specified Shift position (number of Label that will be let in blank when printing) in order to reuse the same Sticker Sheet (in the example bellow to start at 11)

**Comment by memtech3** [comment]
This would help so much

**Comment by jacob-kowalski-at-molex** [comment]
If you want a solution. I couldn't get it to run in an extension, but should be possible.

[censored How to offset labels in Snipeit.pdf](https://github.com/snipe/snipe-it/files/11434553/censored.How.to.offset.labels.in.Snipeit.pdf)
