### ISSUE TITLE
Image not loading next to name

### ISSUE THREAD

**Issue by windblade89** [snipe/snipe-it#6183]
Hi, everyone 
The image is not loading next to the users name.

Kind Regards
Jan Muller
![snipeit](https://user-images.githubusercontent.com/43204460/45419588-01fd8700-b688-11e8-9d38-276f5f5919cb.PNG)

**Comment by EarlRamirez** [comment]
@windblade89 will it be possible if you can complete the template? It's a bit challenging to provide any sort of support if we do not know what Snipe-IT is running on.

**Comment by windblade89** [comment]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Image not loading on asset screen next to the users name.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to 'Any Asset'
2. Click on ''
3. Scroll down to 'User Allocated to'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
![snipeit](https://user-images.githubusercontent.com/43204460/45420546-ad0f4000-b68a-11e8-9d39-70a78262f7d7.PNG)


**Server (please complete the following information):**
 - Snipe-IT Version v4.6.4 build 3885 (g05ea61421)
 - OS: Ubuntu 16.04 LTS Server
 - Web Server: Apache
 - PHP Version 7.0.30-0ubuntu0.16.04.1

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. LG Q6]
 - OS: Android 7.0
 - Browser [Chrome]
 - Version [e.g. 22]

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Add any other context about the problem here.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
What is the URL to the image itself? Is it an uploaded image, or a gravatar image?

**Comment by windblade89** [comment]
I'm going to send you full screen grab. The site is hosted internally.

![snipeit screengrab](https://user-images.githubusercontent.com/43204460/45469767-23637f00-b72b-11e8-97f5-f142b3d2d3ab.PNG)

**Comment by windblade89** [comment]
Okay I inspected the item now. With Chrome that is were the QR code is suppose to display.

So I wonder why it is not displaying now.

**Comment by snipe** [comment]
If you access the image URL directly in the browser, what happens?

**Comment by windblade89** [comment]
![error](https://user-images.githubusercontent.com/43204460/45471741-4e9d9c80-b732-11e8-9b34-453722093f6b.PNG)

**Comment by snipe** [comment]
Please include any additional information you can find in `storage/logs` and your webserver's logs, and confirm that the `public/uploads/barcodes` directory exists and is writable.

**Comment by windblade89** [comment]
Should I try and set the folder premissions?

**Comment by snipe** [comment]
Yes.

**Comment by windblade89** [comment]
I've checked the File Permissions now. They are correct. Going to check the logs now.

**Comment by windblade89** [comment]
Only error I could find in the logs is 
![error](https://user-images.githubusercontent.com/43204460/45539906-5bda8a00-b80b-11e8-8e1b-e80951285fb1.PNG)

**Comment by windblade89** [comment]
Well the same problem still persists. I’ve checked the logs and they don’t indicate why this error is occurring.

Kind Regards
Jan Muller

Sent from Mail for Windows 10
