### ISSUE TITLE
Bulk-edit asset custom fields

### ISSUE THREAD

**Issue by docdre721** [snipe/snipe-it#6184]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.4
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**
We have a lot of assets that get re-issued or re-used in a different manner. Changing the custom fields we have created one by one is time consuming.

**Describe the solution you'd like**
The ability to select the assets, choose Edit and change the created custom fields for the assets.

**Additional context**
<img width="779" alt="screen shot 2018-09-12 at 9 59 09 am" src="https://user-images.githubusercontent.com/38051043/45430083-8e9d4a80-b672-11e8-9924-b3c81c132a78.png">
<img width="998" alt="screen shot 2018-09-12 at 9 59 22 am" src="https://user-images.githubusercontent.com/38051043/45430090-94932b80-b672-11e8-9feb-b4e0e73bfdb1.png">
This is the current option. Does not show any of the custom fields created.

<img width="397" alt="screen shot 2018-09-12 at 10 00 45 am" src="https://user-images.githubusercontent.com/38051043/45430167-c3110680-b672-11e8-873e-8b2f2d335bcf.png">
A sample of the custom fields we use.

**Comment by docdre721** [comment]
Still relevant

**Comment by jackka** [comment]
Still relevant

**Comment by jackka** [comment]
Please  reopen it

**Comment by jackka** [comment]
It's feature is very useful for us. Upvote!
