### ISSUE TITLE
Checkout to Project

### ISSUE THREAD

**Issue by thinkl33t** [snipe/snipe-it#6189]
**Is your feature request related to a problem? Please describe.**
Within our asset tracker we have development hardware that is assigned to a project for work on that project.  

We used to check out hardware to an engineer on the project, but as engineers commonly get switched between projects this was not working for tracking where hardware was.

As it stands, we've been checking out hardware to project managers, but as project managers may be managing multiple projects this is not scaling well at all, and reporting on what hardware a project currently has checked out to it is very manual.  

This causes issues on project closedown, when hardware needs to be returned but we have no idea what hardware was actually assigned.

**Describe the solution you'd like**
The ability to set up and check out items to projects, containing multiple engineers and one or more project manager.  The PM should be able to view and modify hardware belonging to that project.

**Comment by memtech3** [comment]
This would be awesome so long as in settings you could turn it off

**Comment by thinkl33t** [comment]
Yes, this would still be useful functionality

**Comment by thinkl33t** [comment]
This is still needed.

**Comment by sean-borg** [comment]
I'm looking at tackling this issue, bellow are some rough thoughts and questions on how to solve the issue.

Looking around snipe-it there is no project model or any other model already existing you may have planed to
take advantage of to make this feature?

So my though was to add one that would have many to many connection to people and the ability to checkout 
the asset to a project.
Is there any other properties you would like in projects? Maybe connecting them to a company, department or location?


Bellow is a very rough entity relationship diagram and some edited screenshots of where you would create projects,
how you would checkout to a project and assign user to project. 

![Screenshot_2020-07-14 Untitled Diagram drawio - diagrams net](https://user-images.githubusercontent.com/67109348/87408069-e1235700-c5ba-11ea-8336-69e590bf97b4.png)


![Screenshot_2020-07-13 Untitled Jam - Google Jamboard(2)](https://user-images.githubusercontent.com/67109348/87408270-234c9880-c5bb-11ea-9afd-25b7ef8b2e4f.png)

![Screenshot_2020-07-13 Untitled Jam - Google Jamboard](https://user-images.githubusercontent.com/67109348/87408250-1cbe2100-c5bb-11ea-9037-2e0181f483bc.png)

![Screenshot_2020-07-13 Untitled Jam - Google Jamboard(1)](https://user-images.githubusercontent.com/67109348/87408290-2ba4d380-c5bb-11ea-931c-2597ae7b1e68.png)

**Comment by sean-borg** [comment]
> The PM should be able to view and modify hardware belonging to that project.

The idea for being able to modify the hardware, I have a feeling may be awkward for me, what do you expect them to be able to modify?
 
Is it a case of them being able to allocate hardware, checked out to the project, to people on the project?
or do you want them to be able to check in/out hardware to there project?

**Comment by snipe** [comment]
We've entertained the idea of projects before. The permissions that we already have, which are deeply granular, make this harder than it looks. I don't hate the idea, but I'd definitely appreciate it if you work through this more with us before spending the time on a PR. If it's just an identifier (which it always starts out as, but then people will want to restrict it through that) that's fine, but to do this successfully, you'd have to redesign the underpinnings of how permissions work in Snipe-IT - which I'n not necessarily averse to, but gets into a lot of the guts of the thing.

**Comment by sean-borg** [comment]
I am happy to work through it with you and shall start putting together a more detailed spec of changes.
Is there any records of when the previous idea was floated that may be of some use?

**Comment by sean-borg** [comment]
@snipe Below is my MVP of the feature along with some future ideas at the very bottom, let me know what you think :)

- MVP
    Projects would be another entity that an asset can be checked out to.
    Users linked the the project will be able to see all assets checked out to the project, in a similar way to seeing assets checked out directly to them.
    This should add the standard view/create/edit/delete permissions for projects, similar to models/catagories/departments...ect

    Projects would also have an expected end date, used to send remainder emails to assigned users.

    This should be a good minimal start to projects allowing easy sorting of assets without any fundamental changes to permissions.
    From here we could see how snipe-it users use projects and make the correct changes to permission, to most suit the usage.

    This would result in the flowing changes to
    * UI
        - Under setting a new menu item "Projects" 
           This will present a list of projects that can be edited or newly created
        - New/edit project
          A screen allowing assigning users and PMs to project along with updating dates and description
        - /hardware/{id}/checkout
          A new tab "Project" next to User, Asset and location. To allow you to checkout an asset to a project
       - /hardware
         ability to order by Project allowing quick viewing of all assets assigned to a project
       - /account/view-assets
         for both users and PMs or project. assets assigned to projects will show up in this list, with a project column (blank if assigned directly to user)
       - /users/{id}/edit | /users/create
         A new multi select to assign a user to a Project
   
    * DB
       New table "Projects"
        - start date                      (DateTime)
        - expected end date      (DateTime)
        - Project Managers        (ManyToManyLinkToUser)
        - Assets                            (ManyToManyLinkToAssets)
        - Title                                (String)
        - Description                   (String)


    * permissions
        A new set of view/create/edit/delete permissions in users/groups for projects



- Potential future features
    * Have two tiers of users in projects eg PM's and users.
       Users wouldn't get reminder emails, and will have less permissions if added eg no ability to request checkout.
       This would be handy for knowing everyone associated with a project and tracking down assets
    * The Manager can request requestable Assets to be checked out to their Project 
    * The project could have Members synced from LDAP groups

**Comment by sean-borg** [comment]
@snipe would be nice to get some feedback on the possible implementation, as I'm not going to be able to work on it if we don't come to an agreement soon

**Comment by thinkl33t** [comment]
@snipe Please can we re-open this?  It was accidentally closed by stalebot after i'd asked it not to.

**Comment by snipe** [comment]
This isn’t something we’re considering at this time
