### ISSUE TITLE
Allow certain users to checkout equipment without admin equipment modification ability

### ISSUE THREAD

**Issue by nickmacwiz** [snipe/snipe-it#619]
Can we Allow certain users to checkout equipment without making them an admin and allowing them to modify and add equipment, users etc. So basically they are a super user but not super admin or admin.
##

**Comment by snipe** [comment]
Hi @nickmacwiz - what's your use case for this?

**Comment by nickmacwiz** [comment]
In our environment we have certain people that are allowed to check equipment out to our staff and we don't want those people to be able to create or modify items.

**Comment by snipe** [comment]
Is it only certain kinds of equipment? Would this be something that would need to be restrained by category or model?

**Comment by nickmacwiz** [comment]
No. We want them to be able to check out all equipment but not able to modify any of the equipment or add any equipment.

**Comment by snipe** [comment]
Got it

**Comment by malexaxwell** [comment]
Hello, I am currently looking into this software and have the same issue. Is this going to be available in another release? We need to allow users to check in / out items , but not have admin rights.

**Comment by HinoWolf** [comment]
Hell there! I too am in need of this functionality. Our use case is slightly different. We have a Video Game room that we run at events and would like to use it to check out games to event attendees. This means that all of our game room staff need the ability to check in and out games from inventory. In my case I have configured a separate company for this purpose. Any Idea when this might be released or when it will be available in a dev build.

**Comment by snipe** [comment]
The granular checkin/checkout permissions are available in Snipe-IT v4.
