### ISSUE TITLE
pre-flight does not show up

### ISSUE THREAD

**Issue by Metal-Frog** [snipe/snipe-it#6192]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I've installed snipe-it and followed the installation instructions. Besides the step to configure Apache because I'm trying to run it on a hosted server.
I also did a composer install which seems to went fine.
But when I call the installation the URL is redirected to /setup but pre-flight dos not show up, it (just shows server error 500 - see attached screenshot)?
The laraval.log is empty.
The apache log just shows this:
```
xxx - - [13/Sep/2018:12:11:33 +0200] "GET /setup HTTP/1.1" 500 645 snipe-it.ick-online.de "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0" "-"
xxx - - [13/Sep/2018:12:11:34 +0200] "GET /favicon.ico HTTP/1.1" 200 32038 snipe-it.ick-online.de "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0" "-"
xxx - - [13/Sep/2018:12:13:18 +0200] "GET / HTTP/1.1" 302 388 snipe-it.ick-online.de "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0" "-"
xxx - - [13/Sep/2018:12:13:21 +0200] "GET /setup HTTP/1.1" 500 645 snipe-it.ick-online.de "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0" "-"
```
The web server is Apache but I couldn't get the version.

**Screenshots**
![error500](https://user-images.githubusercontent.com/11056711/45483252-acd97800-b750-11e8-8a24-e08ed1be3dd1.png)

**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.4 
 - OS: Linux infong678 3.16.0
 - Web Server: Apache
 - PHP Version: 7.2

**Additional context**
- Is this a fresh install or an upgrade? Fresh
- What OS and web server you're running Snipe-IT on: see above
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manually
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database: just edited .env file

**Comment by Metal-Frog** [comment]
Status update:
Unfortunately I have no access to the apache error logs. I've activated php error log but the error causes no entries in the file.
I've increased PHP memory_limit and max_execution_time - no change.
I've been playing around with the .htaccess file in the /public directory and found out that after commenting the lines in the section "Handle Front Controller" the error 500 is gone but there was only an empty page then. To be honest: I didn't know what I was doing but I thought it could maybe help. Googling around I found out that there are a lot of 500 error messages with the provider 1&1 and that many of them could be fixed with the .htaccess file. But this is far of my knowledge ...

**Comment by snipe** [comment]
Uggggh 1&1 is the WORST. I know people have gotten it running tho. Can you ask 1&1 for your logs? (Last time I checked, I know they put apache error logs in a weird spot because of some funky java FTP server they run.)

> I've been playing around with the .htaccess file in the /public directory and found out that after commenting the lines in the section "Handle Front Controller" the error 500 is gone but there was only an empty page then

Yeah, that's because your commented out the rules that tell Apache how to parse the index.php page, which the app needs to function.
