### ISSUE TITLE
Creating a new accessory (usually) creates a blank entry

### ISSUE THREAD

**Issue by llauren** [snipe/snipe-it#6193]
#### Please confirm you have done the following before posting your bug report:

- [?] I have enabled debug mode, settind `APP_DEBUG=true` in `.env` and i've run `pgp artisan config:cache` but i'm still not getting a debug bar
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I tried creating my first Accessory, but ended with a blank entry. I can see in the activity log on the Dashboard that i've created the accessory but i can't select it because it has no title to click. I went to the Accessories page, which showed zero accessories. I then created a new Accessory with the same information, but this time the accessory was saved. Notably, it was saved under the URL accessories/2. When manually going to accessories/1, i get a Sad Panda.

To reproduce, i created a new Accessory, and lo and behold, it too disappeared.

Am i just incompetent or is this a bug? Please be kind, this is my first bug report :)

**To Reproduce**
1. Go to Create new - Accessory (top right menu)
2. Leave Company blank. Give Accessory a Name, Category (which now exists from previous attempts), Manufacturer (exists from previous Assets), leave Location blank, enter Model number, Order number, Purchase data, Purchase cost, Quantity and for flair, even an image.
3. Click Save
4. You get back to the Accessories page, where you don't have a new Accessory
5. Check the Dashboard, which says you've created a new (nothing).

**Expected behaviour**
Expected that a new Accessory has been created. Each time. After all, Assets are created every time.

**Screenshots**
![screen shot 2018-09-13 at 14 47 04](https://user-images.githubusercontent.com/2391330/45486525-1d3dc480-b764-11e8-97fe-b9fa60f35bed.png)

I've created a nothing, then created a "Näppäimistö" (keyboard), edited the Näppäimistö and finally checked it out. I've then created a nothing, a total of three times.

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.4 - build 3885 (master)
 - OS: Ubuntu 16.04.05 LTS 4.4.0-135-generic
 - Web Server: Apache 2.4.18-2ubuntu3
 - PHP Version PHP 7.1.17-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: May  5 2018 04:55:21) ( NTS )

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 69.0.3497.92 (Official Build) (64-bit)

**Additional context**
- I've run with verision 4.4.x for a while, ran into the problem, updated to 4.6.4, but the problem prevails
- I've managed to create 91 assets, a few users, and in five attempts, one accessory (and four "non-accessories")
- I also tried creating a new Accessory with only the required fields, with zero success (so count that as one accessory in six tries)

What can i do to help you further? I'm no database expert, so please be quite explicit if you want me to dig information straight from the source.

**Comment by llauren** [comment]
Oh crap. Silly me. The reason i seem to have created disappearing items is that i can't see them. When i log in as admin, the accessories are there. When i use Snipe-IT as myself, they are not visible.

Now i only need to figure out why. But let me at least say it's a bit of a usability problem when i'm able to create an item that i can't see or interact with.

**Comment by snipe** [comment]
My guess would be that you're using [Full Company Support](url
https://snipe-it.readme.io/docs/general-settings#section-full-multiple-companies-support) and the accessories and your non-admin user are not in the same category.

**Comment by snipe** [comment]
I wonder if this will be resolved longer term by the changes we added to the company selector, where if you are restricted by company, you cannot select a company, your own will be used if full company support is enabled.
