### ISSUE TITLE
Issues importing assets when following the sample csv. with highlighted required fields

### ISSUE THREAD

**Issue by jnguyenlg** [snipe/snipe-it#6195]
#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I keep getting 

Asset "": The model id field is required.
--

and I have followed the example and the required fields are there. What could be the issue? 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] ubuntu desktop

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? yes
- What OS and web server you're running Snipe-IT on : Ubuntu desktop
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by jnguyenlg** [comment]
[assets.xlsx](https://github.com/snipe/snipe-it/files/2380098/assets.xlsx)

**Comment by huangshifang** [comment]
![default](https://user-images.githubusercontent.com/41154731/45540868-1dab8d80-b840-11e8-8baf-6d98aaca0776.png)
You can use the template shown in the path

**Comment by huangshifang** [comment]
@jnguyenlg

**Comment by snipe** [comment]
Is this still an issue? Did you select "Assets" from the dropdown? If you could provide screenshots of your import screen with mapped fields, that would be helpful.

**Comment by jnguyenlg** [comment]
Hi,

Issue has been resolved, thank you.

Sent from my iPhone

On Oct 4, 2018, at 3:35 PM, snipe <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this still an issue? Did you select "Assets" from the dropdown? If you could provide screenshots of your import screen with mapped fields, that would be helpful.
