### ISSUE TITLE
Can not complete preflight 

### ISSUE THREAD

**Issue by kevinhopper** [snipe/snipe-it#6196]
#### Please confirm you have done the following before posting your bug report:

- [ X ] I have enabled debug mode 
- [ X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
During Snipe-IT Pre-Flight I am able to make it to Step 3. After filling out the requested information and upon selecting "Next: Save User" the page just refreshes and fails to proceed. I'm seeing no dialogue as to why this isn't proceeding. I'm running with docker compose and tail the log for snipe but am not getting any output. 

**To Reproduce**
1. Go to 'page 3 "Create Admin user'
2. Fill out all requested information 
3. Click on "Next: Save User"
4. Page reloads empty

**Expected behavior**
Enter the information, and proceed on to the snipe-it gui. 

**Screenshots**
I don't think a screenshot of preflight would be helpful, if you disagree I can of course add one. 

**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.3
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version : PHP 7.0.22

**Desktop (please complete the following information):**
 - OS: Centos
 - Browser: Chrome, Firefox
 - Version Chrome 68.0.3440.106

**Error Messages** -- none of this is applicable and console in chrome returns no valuable information.

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Turn on debugging and check the requests section of the debugger for any errors or messages.
https://snipe-it.readme.io/docs/advanced-debugging

**Comment by kylehemker** [comment]
@kevinhopper were you able to resolve this? I'm having the same exact issue. I've tried regenerating a new APP key, clearing the config cache and re-caching to no avail. I'm also not seeing any errors in the request section after enabling debugging.

**Comment by EarlRamirez** [comment]
@kylehemker are you getting any errors in from the storage log?

**Comment by kylehemker** [comment]
Yeah this one stands out.

> Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[HY000] [1045] Access denied for user 'sniper'@'localhost' (using password: YES) in C:\inetpub\wwwroot\snipe-it\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:47

I can connect to the DB in HeidiSQL with the parameters set in the `.env` file so I'm not sure what the issue is.

**Comment by EarlRamirez** [comment]
What version of MySQL/MariaDB are you running, the latest version of MySQL had significant changes and unfortunately PHP is a tad bit behind; therefore, I'll recommend downgrading your version of the DB and try again.

**Comment by kylehemker** [comment]
MariaDB 10.1

What version should I shoot for?

**Comment by EarlRamirez** [comment]
my bad, it shows that the password for user *sniper* is incorrect, that version should work 10.1.17 or a version around there has a problem. I saw you mentioned that the credentials worked using HeidiSQL, can you confirm your credentials in the .env and clear the cache and give it a shot.

**Comment by kylehemker** [comment]
Okay so I should be good with this version of MySQL?

Yes they work when connecting from HS, here are the creds from the `.env`:

> DB_CONNECTION=mysql
> DB_HOST=localhost
> DB_DATABASE=snipeit
> DB_USERNAME=sniper
> DB_PASSWORD=supersecretpassword
> DB_PREFIX=null
> DB_DUMP_PATH='C:\PROGRA~1\MariaDB 10.1\bin'
> DB_CHARSET=utf8mb4
> DB_COLLATION=utf8mb4_unicode_ci

Here's a snippet from HS:
![image](https://user-images.githubusercontent.com/19999521/46375616-845ee280-c659-11e8-8390-d284922ff3af.png)
![image](https://user-images.githubusercontent.com/19999521/46375717-c556f700-c659-11e8-89aa-e1410b443273.png)

See any issues there?

**Comment by kylehemker** [comment]
I tried swapping the snipe it user for root credentials and the behavior is the same. Just reloads the add user page with wiped out fields. With debug enabled I am not seeing any errors, my `larvel.log` file doesn't seem to be logging any new activity either though... I'll run through the directory permissions again to see if something is missing.

Any other thoughts?

**Comment by EarlRamirez** [comment]
I think I'm out of options, the errors show that it is credentials, can you share the output of _apt list mariadb-server_

**Comment by kylehemker** [comment]
I'm not sure what command you're referring to but running `show databases;` produces the following.

> +--------------------+
> | Database           |
> +--------------------+
> | information_schema |
> | mysql              |
> | performance_schema |
> | snipeit            |
> | test               |
> +--------------------+

**Comment by EarlRamirez** [comment]
From the command line (terminal)

**Comment by kylehemker** [comment]
I'm running on Windows Server 2016 and using IIS, unlike kevinhopper above.

**Comment by EarlRamirez** [comment]
@kylehemker can you try and downgrade your version of MySQL and let us know how it goes?

**Comment by kylehemker** [comment]
Sure what version should I downgrade to @EarlRamirez?
I just installed the version mentioned in the SnipeIT documentation.
https://snipe-it.readme.io/docs/requirements
**MariaDB 10.0.14 for Windows**
