### ISSUE TITLE
FEATURE REQUEST: Make it so a user can request assets online

### ISSUE THREAD

**Issue by nickmacwiz** [snipe/snipe-it#620]
When a user logs in and sees add a request this item button in the actions area and when a person with checkout capability click on that user later they can see what the user has requested and can click the checkout button to checkout the requested items. 
![screenshot 2015-03-09 08 14 09](https://cloud.githubusercontent.com/assets/11078660/6557809/23fed59e-c635-11e4-8c1d-decc12e15f1b.png)

**Comment by snipe** [comment]
This is already planned.

**Comment by dbierspb** [comment]
This will likely be my favorite part -- can't wait to see it :D

**Comment by drahamim** [comment]
Saw this (as I would also like this feature) and thought I would also note for when this is completed that It is marked as duplicate (but no note as to the original request) of  #12 so that they can be closed together.

**Comment by snipe** [comment]
Closing as duplicate of #12
