### ISSUE TITLE
Unable to run preflight on a FreeBSD box

### ISSUE THREAD

**Issue by MHCL-AlanD** [snipe/snipe-it#6201]
#### Expected Behavior (or desired behavior if a feature request)

on connection to IP address should run pre-flight scripts to set up database

-----

#### Actual Behavior

Whoops, looks like something went wrong.
various messages within panels, panels are headed

(3/3) QueryExceptioncould not find driver (SQL: select * from information_schema.tables where table_schema = snipeit and table_name = users)

(2/3) PDOExceptioncould not find driver

(1/3) PDOException
could not find driver

screen print attached
[snipeitstart.pdf](https://github.com/snipe/snipe-it/files/2383323/snipeitstart.pdf)
[snipeitconfig 2.pdf](https://github.com/snipe/snipe-it/files/2383339/snipeitconfig.2.pdf)

I have phpmyadmin installed and can login with the snipe_user credentials so the mysql and php are OK
the PDO & mysql & mysqli extension are installed

The error messages suggest it is not using the correct driver to access the database but don't know where else to look

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? fresh
- Version of Snipe-IT you're running 4.6.4
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by MHCL-AlanD** [comment]
Yes, mysqlnd is loaded, see output from php -m
![mysqlnd](https://user-images.githubusercontent.com/43271485/45586560-155f5b00-b8f1-11e8-977f-6ff30716d869.png)

**Comment by MHCL-AlanD** [comment]
thanks for the prod, missing pdo_mysql module, now installed and got passed that error, now says URL /setup was not found ..... 1 step further on :) :+1:

**Comment by EarlRamirez** [comment]
@MHCL-AlanD sorry for the delayed response, did you manage to get any further?

**Comment by MHCL-AlanD** [comment]
Hi, Yes, I've got it running now thanks

**Comment by EarlRamirez** [comment]
awesome, you can close the issue.
