### ISSUE TITLE
Problems with APP_URL variable

### ISSUE THREAD

**Issue by l13t** [snipe/snipe-it#6202]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
To make application working I need to specify `APP_URL` without http or https. If I specify `http://` in `APP_URL` I see cookie domain as `http://<my_domain_nam>`. Because of this, I'm not able to authenticate in Snipe-it and it redirects me back to login page. At the moment I have in `APP_URL` only domain name without http(s).
Also, restore password url is broken: it includes domain name twice.

**To Reproduce**
Steps to reproduce login problem:
1. Set `APP_URL` with `http://`
2. Run container
2. Go to login page, enter credentials and press login
3. See login page again

Steps to reproduce restore password problem:
1. Set `APP_URL` without `http://`
2. Press "I forgot my password"
3. Enter your email and press "Email Password Reset"
4. Check your mailbox for email from Snipe-IT

**Expected behavior**
Have proper "Restore password" link in email without domain duplicates and login works correctly.

**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.4
 - OS: Docker container based on clean Alpine 3.8 (https://github.com/l13t/docker-alpine-snipe-it)
 - Web Server: nginx
 - PHP Version: ```bash-4.4# php -v
PHP 7.2.8 (cli) (built: Jul 28 2018 17:55:09) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser: Firefox
 - Version: 62.0

**Error Messages**
There are no error messages in logs.

**Additional context**
- Used pre-existing database from version 3.6.4 and did all 3=>4 upgrade steps before starting container
- Alpine Linux 3.8
- Docker
- Nothing was changed in database manually.

If I have `http(s)://` in `APP_URL` specified, I don't have any errors in laravel.log file or in php/nginx logs about problems.

**Comment by ccomtest** [comment]
I think that is more a problem of your nginx.
You should check root directory listing in your nginx config. Also check forward, static links etc.

**Comment by l13t** [comment]
Yeah. Seems like you're right. I tried to test last week and it worked. I'll do more tests this week. But seems like this is root-cause of my issue. So ticket could could be closed
