### ISSUE TITLE
Audit Alert Emails

### ISSUE THREAD

**Issue by Brakow87** [snipe/snipe-it#6204]
#### Expected Behavior (or desired behavior if a feature request)
I would like to know if you can have Audit Alert Emails Sent.  I have setup the 3 tasks running correctly, but still am not getting any notifications for audit's that need to take place.  Below is the 3 tasks that run correctly.  I have also set all alerts in the settings/admin section and test emails work.  

artisan snipeit:expiring-alerts
artisan snipeit:inventory-alerts
artisan snipeit:expected-checkin

(what you expect to happen goes here)
Receive Audit expiration emails/Audit Due date emails.
-----

#### Actual Behavior

(what actually happens goes here)
I am receiving Low Inventory alert emails.
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? fresh install
- Version of Snipe-IT you're running v4.6.3 build 3866 (g3de1de9dc)
- Version of PHP you're running  7.2.8
- Version of MySQL/MariaDB you're running  5.4.35
--
- What OS and web server you're running Snipe-IT on  Windows 10/WAMP
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by sueesmar** [comment]
Hi, I have the same problem. Audit alert mails don't get sent, but the license and warranty expiration alerts were sent by mail. In https://github.com/snipe/snipe-it/issues/5552, there it is written, that audit alerts will be sent by mail. But in the source code, I think there is only slack implemented. What do I have to do, to get audit alert mails to work?

**Comment by snipe** [comment]
@sueesmar there is no audit alert email functionality in v4. The documentation explains what alerts get sent out: 

https://snipe-it.readme.io/docs/notifications-overview
https://snipe-it.readme.io/docs/configuring-alerts-backups

A slack message will be sent when an asset is audited, but there is no alerting for upcoming audits at this time.

**Comment by sueesmar** [comment]
@snipe thank you very much for your reply. Are there any plans or a roadmap to implement such upcoming audit alerts by mail? What is the meaning for the "Audit Warning Threshold" under the notification settings? Why can we set the "Next audit date"? Is it only to create custom reports with this field and filter it there in Excel? It would be a nice feature to get alerts by mail, starting the Threshold set. Thank you for the great work.

**Comment by snipe** [comment]
This is now on `master`, although not yet in a formal release. (I'll handle that tomorrow most likely.)

Details here: https://github.com/snipe/snipe-it/pull/6992

**Comment by sueesmar** [comment]
Wow, thank you very much for the really fast implementation of this feature. I will check it out as soon as possible, but the screenshots look already like I expect this feature should work. Thank you very much for the great work.
