### ISSUE TITLE
Retrieve Data from Amazon, Walmart and more for New Assets

### ISSUE THREAD

**Issue by jessetechno** [snipe/snipe-it#6206]
**Server (please complete the following information):**
 - Snipe-IT Version: 5 
 - OS: Linux
 - Web Server: Apache, PHP, MySQL
 - PHP Version: 7.2

**Is your feature request related to a problem? Please describe.**
When adding a new product you have to enter all the information about every single product.  This is time consuming and slows productivity.

**Describe the solution you'd like**
I would like to see a place where you can import a model from amazon, walmart or other mega-stores by scanning a UPC or searching through a module window.  It will import text and images to create it.

**Describe alternatives you've considered**
I considered making my own plugin but it was very difficult to impliment it without it being its own app and it needs to be intigrated.

**Comment by snipe** [comment]
> When adding a new product you have to enter all the information about every single product.

That's the point of asset models. You create them once, and make as many associated assets as you need. 

If you know of a free UPC database API, we can look into this, but I don't know of any.

**Comment by superfeetit** [comment]
I know this is a really old request, but I've used eandata.com in the past for grabbing data about products based on UPC. So you can just scan the barcode and then pull data about it to populate the form. I also know there are a ton of other similar ones: https://www.upcitemdb.com/, http://upcdatabase.org. But haven't used many others as they have more api limits and it was such a long time ago it was the best option. If it was implemented in snipe-it you would probably want to write it as a more open system where it could pull from several and you just setup your api credentials and endpoint and then field mapping config so if one of the upc db services went down you could always use another or if one person wanted to pay and not another they could. Just a though. I know any way to make asset entry quicker is great and just scanning the products bar code after being purchased would be ideal and then you could enter in details about service tag or warranty info afterwards.

**Comment by superfeetit** [comment]
There are also options like: https://docs.aws.amazon.com/AWSECommerceService/latest/DG/CHAP_RequestResponseExamples.html, but not sure about api key pricing or anything.
