### ISSUE TITLE
Timestamps are off by 1 hour

### ISSUE THREAD

**Issue by GeorgelT** [snipe/snipe-it#6211]
#### Expected Behavior (or desired behavior if a feature request)

When checking out or in an asset or license the timestamp displayed in the log should respect the time of saving.

-----

#### Actual Behavior

When checking in or out an asset or license the timestamp is set 1h earlier (I'm on CET so is probably UTC) than when it was actually created. The same does not happen for editing, creating that asset. 
I can create an asset and check it out imediately and it will show up 1 hour earlier as a timestamp. See screenshot of exactly this example.

![screenshot from 2018-09-18 11-00-48](https://user-images.githubusercontent.com/7941982/45676712-ad985280-bb32-11e8-8344-aab0334061d0.png)

I'm basically checking out the testasset one hour before I create it.

My .env file hast APP_TIMEZONE='CET' and it should be correct. I'm in central Europe.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 

Upgrade but previously was also doing this.
- Version of Snipe-IT you're running
4.6.4

- Version of PHP you're running

PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )

- Version of MySQL/MariaDB you're running

mysql  Ver 14.14 Distrib 5.7.23

- What OS and web server you're running Snipe-IT on

Ubuntu 16.04lts

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

Manual install and upgraded/changed it to git install

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

with APP_DEBUG=true set am not getting debug mode working.

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.

Does not happen on the demo, but it is also running a different timezone.

- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

![screenshot from 2018-09-18 10-49-45](https://user-images.githubusercontent.com/7941982/45676054-272f4100-bb31-11e8-9163-150039f4a889.png)

**Comment by GeorgelT** [comment]
Looks like you are correct that the server itself is running CEST: 

> Fri Sep 21 09:15:47 CEST 2018

I happend to have to create some devices today, so I did another checkin/out of the same asset again after changing the .env value.

Seems to have done nothing:
![screenshot from 2018-09-21 09-17-58](https://user-images.githubusercontent.com/7941982/45865951-7965a180-bd7f-11e8-9764-113765cd5ee2.png)

**Comment by ccomtest** [comment]
I just can say, that here there is no time difference.
When you chance values i have read something about that snipe-it is caching a lot of things.
Have you restart your system/flushed the cache?

You have to check that by yourself, i don't know where you can find that cache cleaning.

**Comment by ccomtest** [comment]
Found it: https://snipe-it.readme.io/v3.6.2/docs/clearing-the-config-cache

**Comment by GeorgelT** [comment]
Hi there,

yes I have them both set to the same value.

`admin@intranetv2:/srv/webapps/snipe-it$ date
Fri Sep 21 12:57:44 CEST 2018
admin@intranetv2:/srv/webapps/snipe-it$ cat .env | grep CEST
APP_TIMEZONE='CEST'
`

**Comment by ccomtest** [comment]
Hm, i know that because of different time settings from system and user environment.
So for "system" variables it is the clock of linux which will count (backend). For the "user" side it is the user variables (frontend). It's like in Active Directory time sync for a whole enterprise which you should not change. 

If you can change in the environment of the "web app" you can have different timings which might be usefull. So i don't see this as a real bug, but who really knows... ;)

**Comment by GeorgelT** [comment]
Ok, but as the initials suggest, this is "summer time", what happens when we switch to winter time/daylight savings and it changes to CET? Does the system adapt for daylight savings?

The systemtime will change to CET, which I guess is what happened when I first installed snipe-it. 

Anyway, thanks for helping me solve this it has been bugging me for quite some time. Did the update and thought this might be as good a time as any to try and fix the bug.

**Comment by ccomtest** [comment]
It's the default of most systems to automatically switch time bias by +1/+2. So it should change to +1 and winter time so you have the right time.
You just have to choose the right zone which is CEST for our zone. Your system is allready set fine with CEST.

Good to know it is working good now.
