### ISSUE TITLE
How do you use locations and the ldap search OU field?

### ISSUE THREAD

**Issue by CJChristensen** [snipe/snipe-it#6215]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Not really a bug but I am looking for information on how the LDAP Search OU field is used in locations. I am not quite understanding it's purpose. I would like to get a better handle on locations since currently  everyone just lands into a single location based on what I choose in the ldap sync and what I have my filter set in the admin ldap settings which sucks as 1 wrong move on the filter and I could accidentally mess up a large portion of user locations.

**To Reproduce**
Nothing to reproduce, looking for a better explanation/documentation

**Expected behavior**
Looking for better documentation around this issue

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version - Cloud

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [68]

**Smartphone (please complete the following information):**
NA

**Error Messages**
NA

**Additional context**
I am really just after some documentation around how to handle locations when you're using ldap sync. As I went through and updates about 20 people to different locations, ran an ldap sync (after editing the filter to hit these 20 people) and did not set a location for the sync and it reset my changes, so, how the hell do you properly set this up?

**Comment by hertel204** [comment]
@CJChristensen I have the same issue here. Believe that when you fill the "LDAP Search OU" field it should look for the users in that OU and add them to the Location selected, but it's not working for me.

I got the error: 
![image](https://user-images.githubusercontent.com/33985951/46170563-86e5c480-c274-11e8-9cd6-f2b05f0fa095.png)

**Comment by snipe** [comment]
@hertel204 can you please provide information from your app error logs.

**Comment by snipe** [comment]
Hi @hertel204 - I need the info from your app log so I can see what the error is.

**Comment by hertel204** [comment]
Hi, that what I got:


(1/1) ErrorExceptionUndefined index: samaccountname
--
in LdapSync.php line 133
at HandleExceptions->handleError(8, 'Undefined index: samaccountname', '/var/www/snipe-it/app/Console/Commands/LdapSync.php', 133, array('r', 'S'))in LdapSync.php line 133
at LdapSync->handle()
at call_user_func_array(array(object(LdapSync), 'handle'), array())in BoundMethod.php line 29
at BoundMethod::Illuminate\Container\{closure}()in BoundMethod.php line 87
at BoundMethod::callBoundMethod(object(Application), array(object(LdapSync), 'handle'), object(Closure))in BoundMethod.php line 31
at BoundMethod::call(object(Application), array(object(LdapSync), 'handle'), array(), null)in Container.php line 539
at Container->call(array(object(LdapSync), 'handle'))in Command.php line 182
at Command->execute(object(ArrayInput), object(OutputStyle))in Command.php line 251
at Command->run(object(ArrayInput), object(OutputStyle))in Command.php line 167
at Command->run(object(ArrayInput), object(BufferedOutput))in Application.php line 946
at Application->doRunCommand(object(LdapSync), object(ArrayInput), object(BufferedOutput))in Application.php line 248
at Application->doRun(object(ArrayInput), object(BufferedOutput))in Application.php line 148
at Application->run(object(ArrayInput), object(BufferedOutput))in Application.php line 141
at Application->call('snipeit:ldap-sync', object(Collection), null)in Kernel.php line 220
at Kernel->call('snipeit:ldap-sync', array('--location_id' => '3', '--json_summary' => true))in Facade.php line 221
at Facade::__callStatic('call', array('snipeit:ldap-sync', array('--location_id' => '3', '--json_summary' => true)))in UsersController.php line 876
at UsersController->postLDAP(object(Request))
at call_user_func_array(array(object(UsersController), 'postLDAP'), array(object(Request)))in Controller.php line 55
at Controller->callAction('postLDAP', array(object(Request)))in ControllerDispatcher.php line 44
at ControllerDispatcher->dispatch(object(Route), object(UsersController), 'postLDAP')in Route.php line 203
at Route->runController()in Route.php line 160
at Route->run()in Router.php line 572
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php line 43
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php line 49
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php line 49
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php line 42
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Router.php line 574
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 533
at Router->dispatchToRoute(object(Request))in Router.php line 511
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php line 51
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php line 25
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php line 27
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

**Comment by CJChristensen** [comment]
Is there a way to test the ldap filters and ldap search OU so that you don't go and blow up how you have things set up?

**Comment by hertel204** [comment]
ldap filter you can test on the ldap configuration page, but for Locations ldap search I couldn't find

**Comment by hertel204** [comment]
@snipe the solution for that case would be rewriting in lower case but my settings are already like that.

**Comment by snipe** [comment]
@hertel204 Yeah, I realize that, but that issue persisted for folks in the comments even after lowercasing.

**Comment by samotelf** [comment]
@hertel204 Are you using active directory?
Here are my configurations for AD:

LDAP Integration LDAP enabled √
Active Directory This is an Active Directory server √
LDAP Password Sync Yes √
Active Directory domain contoso.com
LDAP Server ldap://ipaddressofyourdc:389
Use TLS NO
Allow invalid SSL Certificate √
LDAP Bind Username ldap.user
LDAP Bind Password password
Base Bind DN dc=contoso,dc=com
LDAP Filter &(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))
Username Field samaccountname
Last Name sn
LDAP First Name givename
LDAP Authentication query samaccountname=
LDAP Version 3
LDAP Email mail

And then regarding locations what I have is for instance:

Offices (OU=Offices,DC=CONTOSO,DC=com) PARENT: NONE -> SnipeIT Location Configuration
-- Paris (OU=Paris,OU=Offices,DC=CONTOSO,DC=com) PARENT: Offices -> SnipeIT Location Configuration

I still have some caveats, but for now that's how I'm organising locations.
Hope it helps.

**Comment by hertel204** [comment]
@samotelf the issue #4121 resolved my question.

thanks!
