### ISSUE TITLE
Stuck with Docker

### ISSUE THREAD

**Issue by Metal-Frog** [snipe/snipe-it#6216]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
No bug. I'm just stuck on trying to get the docker image working. I'm using the DockerToolbox on Windows 10.
I've followed the instructions on your [docker documentation](https://snipe-it.readme.io/docs/docker). And I have to admit that I'm not very familiar with docker.

I think that the snipe-it container cannot find the database. 
The database has been created in "snipe-mysql", but it is empty. This container says that the Docker port 3306 is mapped to 192.168.99.100:32769.
As in your guide I did not set the variables MYSQL_PORT_3306_TCP_ADDR and MYSQL_PORT_3306_TCP_PORT. (BTW: the local ports change with every start of the container).
In the "snipe-it" container the varaible APP_URL is set to http://127.0.0.1:32777. The page I open on my host is http://192.168.99.100:32777.
The text in the  PDOException is the reason why I think that snipe-it does not find the datebase. But even when I set the MYSQL_PORT_... variables there is no success (see attachments).
What's wrong in my configuration?

PS: In the shell is the error message:
`AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message`

**Screenshots**
[1-debug_without_MYSQLport.pdf](https://github.com/snipe/snipe-it/files/2395715/1-debug_without_MYSQLport.pdf)
[2-debug_with_MYSQLport.pdf](https://github.com/snipe/snipe-it/files/2395716/2-debug_with_MYSQLport.pdf)

**Server (please complete the following information):**
Docker images

**Comment by ccomtest** [comment]
Hi there,

I see 2 different private networks, which maybe cant talk to each other due to missing routing.

Then i dont see a docker run command which bind the container port to your host port.

**Comment by Metal-Frog** [comment]
Those should have been my run commands:
```
docker run --name snipe-mysql --env-file=./snipe.env --mount source=snipesql-vol,target=/var/lib/mysql -d -P mysql
docker run -d -p 32777:80 --name="snipeit" --link snipe-mysql:mysql --env-file=./snipe.env --mount source=snipe-vol,dst=/var/lib/snipeit snipe/snipe-it

```

> I see 2 different private networks

What do I have to change?

**Comment by ccomtest** [comment]
First check your config of apache, which says it can't determine FQDM of your server and check the IPs.
Probably set all docker service IPs to 127.0.0.1 (not localhost). You will bind them to your host IP with the docker run command then.

**Comment by ccomtest** [comment]
Here are my configs, as far as i am allowed to pusblish, mabye they help you:

Netzwerk:
- sudo nano /etc/netplan/01-netcfg.yaml
	
```
network:
  version: 2
  renderer: networkd
  ethernets:
	enp0s3:
	  dhcp4: no
	  dhcp6: no
	  addresses: [HOST-IP/N-CLASS]
	  gateway4: GW-IP
	  nameservers:
	    addresses: [NS-IP]
```

Your snipe.env should look like:

```
# Mysql Parameters
MYSQL_ROOT_PASSWORD=PASSWORD
MYSQL_DATABASE=snipeit
MYSQL_USER=snipeit
MYSQL_PASSWORD=PASSWORDforSNIPE-User

# Snipe-IT Settings
APP_ENV=production
APP_DEBUG=false
APP_KEY=YOURAPPKey as shown in Documentation
APP_URL=http://127.0.0.1:80
APP_TIMEZONE=Europe/Berlin
APP_LOCALE=de
```

Run command: 
`docker run --name snipe-mysql --env-file=my_env_file --mount source=snipesql-vol,target=/var/lib/mysql -d -P mysql:5.6 //or disable strict-mode when using MySQL > 5.6`

`docker run -d -p 80:80 --name="snipeit" --link snipe-mysql:mysql --env-file=my_env_file --mount source=snipe-vol,dst=/var/lib/snipeit snipe/snipe-it`

**Comment by Metal-Frog** [comment]
Hmmm.
The FQD servernane seems to be without any relevance.
I've tried to use mysql:5.6 but every version below 8 does not run. But I've managed to get version 8 with strict mode off.

I have no explanation for this: Besides these two are set or not - now I get a complete different error message: `SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client`
[NewError.pdf](https://github.com/snipe/snipe-it/files/2420192/NewError.pdf)

**Comment by snipe** [comment]
@uberbrady can you take a look at this when you get a moment?

**Comment by uberbrady** [comment]
I think newer MySQLSnapshot have a different auth framework than the older ones.

What do you get if you just try to run a stand-alone container with 5.6? Put the output you get here.

**Comment by Metal-Frog** [comment]
I create the container with the following command:
`docker run --name snipe-mysql-5.6 --env-file=./snipe.env --mount source=snipesql-vol,target=/var/lib/mysql -d -P mysql:5.6`
But it doesn't start. Kitematic says it is running but it actually isn't. When I try to run a shell I get the error: `Error response from daemon: Container 643...dbe is not running`
I don't know if there are any further logs ...

**Comment by uberbrady** [comment]
I don't really know much about Kitematic; can you try just using the CLI by itself without using Kitematic, and see if you get better results?

**Comment by HinchK** [comment]
@Metal-Frog you will have to check your parameters being passed into your docker containers using `docker inspect`.  

This docker-issue has a very simple docker-compose....check out the sample environment file I attached here to see how the application environment and the database environment each require very specific settings passed in, in addition to the traditional snipe-it `.env` settings: https://github.com/snipe/snipe-it/issues/6346

**Comment by Metal-Frog** [comment]
This happens only with DockerToolbox on Windows.
With Docker everything runs fine.
