### ISSUE TITLE
New Model window will not close after model created - Ubuntu 18.04.01 LTS

### ISSUE THREAD

**Issue by OprSysAdm** [snipe/snipe-it#6219]
- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I have just upgraded the VM on which my snipe is installed to Ubuntu 18.04.1 LTS. Everything has migrated correctly and is functional however I have noticed that all of a sudden when I try to create a new model within the create new asset interface the 'submit' button is no longer functional. The new model DOES get created but the window stays open with no indication that the operation completed.

**To Reproduce**
1. Go to the 'Assets' list 
2. Click on 'Create New'
3. When the "Create Asset' window opens, click the "New" button next to 'model'
4. Enter in all information in the 'Create Asset Model' window and then click "Save"

**Expected behavior**
When the 'Save' is clicked, the "Create model" window should close and the asset should be available to select in the 'Create Asset' window. The window never closes and there is no indication that anything happens.

**Server:**
 - Snipe-IT Version: v4.1.10 build 3249 (g8d3a214)
 - OS: Ubuntu 18.04.01 LTS
 - Web Server: Apache
 - PHP Version : 7.2.7-0ubuntu0.18.04.2

**Desktop :**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 68.0.3440.106 (Official Build) (64-bit)

**Error Messages**

- From the browser debug console
![image](https://user-images.githubusercontent.com/33499358/45833065-af4c4c80-bcd1-11e8-8167-a45964639709.png)

-storage log
#54 /var/www/SnipeIt/snipeit4/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#55 /var/www/SnipeIt/snipeit4/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\ Http\Request))
#56 {main}
[2018-09-20 11:35:24] production**.ERROR**: ErrorException: count(): Parameter must be an array or an object that implements Countable in /var/www/SnipeIt/snipeit4/app/Helpers/Helper.php:693
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'count(): Parame...', ' /var/www/SnipeI...', 693, Array)
#1 /var/www/SnipeIt/snipeit4/app/Helpers/Helper.php(693): count('Model created s...')
#2 /var/www/SnipeIt/snipeit4/app/Http/Controllers/Api/AssetModelsController.php(86): App\Helpers\Helper::formatStandardApiResponse('success', Object(App\Models\AssetModel), '**Model created** s...')
#3 [internal function]: App\Http\Controllers\Api\AssetModelsController->store(Object(Illuminate\Http\Request))
#4 /var/www/SnipeIt/snipeit4/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_funcarray(Array, Array)

**Comment by EarlRamirez** [comment]
Can you upgrade Snipe-IT to the latest version and let us know if you are still experiencing this behaviour?

**Comment by OprSysAdm** [comment]
@EarlRamirez Thank you, I should have thought of that . I probably assumed that everything would have gotten updated automatically when I did the dist-upgrade. It's working again now.
