### ISSUE TITLE
IIS - DNS host name doesnt display correctly

### ISSUE THREAD

**Issue by JamesTaylor76** [snipe/snipe-it#622]
I have Snipe-IT running on windows server 2012.  When I use the IP address to access the site http://10.xx.xx.xx then the site displays correctly.  I also have a DNS for this IP address, but when accessing using http://DNSName  it does not format the page correctly.

Anyone else experiencing this problem?

**Comment by dbierspb** [comment]
If it doesn't display correctly, are you able to view the source code to
make sure the CSS and other elements are linking correctly?

On Mon, Mar 9, 2015 at 11:20 AM, JamesTaylor76 <notifications@github.com>
wrote:

> I have Snipe-IT running on windows server 2012. When I use the IP address
> to access the site http://10.xx.xx.xx then the site displays correctly. I
> also have a DNS for this IP address, but when accessing using
> http://DNSName it does not format the page correctly.
>
> Anyone else experiencing this problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snipe/snipe-it/issues/622>.
>



-- 

David Biers

System Administrator

ProfitBricks, Inc.

Mobile: 1-361-549-3395

Support Hotline: 1-866-936-0764

Email: david.biers@profitbricks.com

Web:  Learn why we're the Price/Performance leader in Cloud Computing
<http://www.profitbricks.com/>

<http://www.profitbricks.com/>

**Comment by JamesTaylor76** [comment]
Hi,

Yes I have viewed the source code and it appears to be formatted correctly, I cannot quite understand why it is not displaying correctly

Interestingly, it displays correctly in Google Chrome... using both paths.

**Comment by joseph707** [comment]
Hi James

That is weird. Have you specified things like this
a. DNS host A-record to the machine. Done through your DNS server
b. Host name, if any, on the IIS, Host name section
c. No firewall blocking
d. Check event viewer for possible errors
e. Do a NSlookup to the hostname and see if the IP returns
f. Are you able to sign-in to SNIPE IT

Let us know how it goes.

Cheers

Joseph

**Comment by JamesTaylor76** [comment]
I believe the DNS is done directly to the IP address, our IT set that up for me...
There is no firewall running on the web server at the moment.
NSlookup returns the correct IP address from the DNS server.
Yes I am able to sign into the site.

**Comment by nickmacwiz** [comment]
you said that the site displays correctly on chrome. What browser is there an issue with? IE? Also is the issue appearing on multiple machines or only on one workstation?

**Comment by JamesTaylor76** [comment]
It is happening on multiple machines,

Yes the problem is on IE, I am using 11, but also tried it on IE 8&9 with the same issue.

**Comment by joseph707** [comment]
hi @JamesTaylor76 

Have you entered the hostname for as shown below?

![capture](https://cloud.githubusercontent.com/assets/9422649/6561966/70f62c5c-c6ae-11e4-8bc7-d729acb67591.JPG)

regards

Joseph

**Comment by joseph707** [comment]
hi @JamesTaylor76 

Also, put the site in computability mode, add it via Tools > Compatibility view  setting and add the current site, I mean your IT asset site. Should work.

Regards

Joseph

**Comment by nickmacwiz** [comment]
is the server running the newest version of php?

**Comment by JamesTaylor76** [comment]
No,

I added just the dns name and not the domain on the end.

I have now added the domain name and I was taken to the default website. http://DNSName

I used the fully qualified name http://DNSName.yourdomain.uk.com and it has now worked correctly for me

Thanks for the help Joseph..

However I would prefer just to use the DNS name only as its a shorter address for out guys to remember, but it is a solution for the moment. Thanks.

Regards

James

**Comment by nickmacwiz** [comment]
you will need to add an additional record on your local DNS Server for the translation from DNSName to http://DNSName.yourdomain.uk.com

**Comment by JamesTaylor76** [comment]
yes the PHP is all up to date.

I shall just issue an update to everyone asking them to use the fully qualified address and see how they get on.

Regards

**Comment by joseph707** [comment]
hi @JamesTaylor76 

Glad it worked. Keeping the FQN, is good and that is how your IT team would have set up, presumably.

cheers
Joseph
