### ISSUE TITLE
Invalid Username/Password

### ISSUE THREAD

**Issue by aappleby89** [snipe/snipe-it#6220]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I got the program up and running yesterday. I entered asset data, and everything seems fine. Then all of a sudden it says I can't login due to invalid credentials. I have tried everything, including creds saved in LastPass, and nothing. So, I restored the Mysql database and it worked fine. Then today it worked fine all day, until it kicks me out again. Also, when I do a forgot password option it tells me that user doesn't exist with that email, even though I'm able to confirm in mysql that it does. Has anyone else seen this?
**To Reproduce**

**Expected behavior**
I expect to be able to login normally
**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version Latest
 - OS: [e.g. Ubuntu, CentOS] Ubuntu
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS, Windows,
 - Browser [e.g. chrome, safari] Safari, Chrome, Firefox

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]iPhone, Note 9
 - OS: [e.g. iOS8.1]iOS 12, and latest android
 - Browser [e.g. stock browser, safari]Sarfari, Google Chrome

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by aappleby89** [comment]
Ok, so I was able to get myself logged back in, but it was a really weird scenario. Somehow, my users "Activated" status was changed to off. So, I created another user. In the gui that user shows as "Activated" in other words the "User can login" box is checked. However, when I go to confirm that in the database, it is not activated. Two things concern me, why did my user's activation status change on its own, and why is me checking that box to activate not making its way back to the database? I'm not seeing any other database type issues. Any help on why this would be the case would be appreciated. 

MariaDB [snipeit]> SELECT * FROM users WHERE username = 'administrator' AND activated = '1';
Empty set (0.00 sec)

**Comment by EarlRamirez** [comment]
@aappleby89 try creating a new account using _https://snipe-it.readme.io/docs/create-an-admin_ and see what is going on with the account, looks like the account is getting disabled, you will have to check the logs to get clues as to why you are experiencing this behaviour.

**Comment by tmvillain13** [comment]
I just posted the defect -> https://github.com/snipe/snipe-it/issues/6252 

Try to remember if you were editing your own user. This might be the reason. 

Just have another backup admin user in place, to fix the "Active" flag on your user. Or simply update the flag via Data Base Update. Until the bug is fixed
