### ISSUE TITLE
Used the snipe-it "download installer" option, but can't access the page for the first time

### ISSUE THREAD

**Issue by perscheta** [snipe/snipe-it#6221]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)
I should be able to access the web page listed to login to Snipe-IT
-----

#### Actual Behavior

(what actually happens goes here)
The page takes minutes to load and error "this page isn't working" with an ERR_EMPTY_RESPONSE
I am unable to get into debug mode, let alone create cp an .env I get the rror
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
yes
- Version of Snipe-IT you're running
v4.6.3
- Version of PHP you're running
7.2.10
- Version of MySQL/MariaDB you're running
tried to find version, but returned with "command 'mysql' not found..."
- What OS and web server you're running Snipe-IT on
ubuntu 18.0.4, tried to find apache version, but returned with command 'httpd' not found..."
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
I cannot access .env file (Permission denied)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Trying to access it for the first time after performing install.sh
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
No errors
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
N/A
- Include any additional information you can find in `storage/logs` and your webserver's logs.
No log, folder is empty
- Include what you've done so far in the installation, and if you got any error messages along the way.
Please refer to the text of the install.sh process:
________________________________________________

*** Configuring Apache.
* Setting up hosts file.
* Starting MariaDB.
* Securing MariaDB.
./snipeit.sh: line 450: /usr/bin/mysql_secure_installation: No such file or directory
* Creating Snipe-IT user.
* Creating MariaDB Database/User.
* Please Input your MariaDB root password:
./snipeit.sh: line 190: mysql: command not found
* Cloning Snipe-IT from github to the web directory.
* Configuring .env file.
* Installing composer.
All settings correct for using Composer
Downloading...

Composer (version 1.7.2) successfully installed to: /home/snipeitapp/composer.phar
Use it: php composer.phar

* Setting permissions.
* Running composer.
Loading composer repositories with package information
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for erusev/parsedown 1.7.1 -> satisfiable by erusev/parsedown[1.7.1].
    - erusev/parsedown 1.7.1 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 2
    - Installation request for laravel/framework v5.4.35 -> satisfiable by laravel/framework[v5.4.35].
    - laravel/framework v5.4.35 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 3
    - Installation request for league/csv 8.2.3 -> satisfiable by league/csv[8.2.3].
    - league/csv 8.2.3 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 4
    - Installation request for maknz/slack 1.7.0 -> satisfiable by maknz/slack[1.7.0].
    - maknz/slack 1.7.0 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
  Problem 5
    - Installation request for tecnickcom/tc-lib-barcode 1.15.12 -> satisfiable by tecnickcom/tc-lib-barcode[1.15.12].
    - tecnickcom/tc-lib-barcode 1.15.12 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
  Problem 6
    - laravel/framework v5.4.35 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - watson/validating 3.1.6 requires illuminate/contracts 5.3.* || 5.4.* || 5.5.* || 5.6.* -> satisfiable by laravel/framework[v5.4.35].
    - Installation request for watson/validating 3.1.6 -> satisfiable by watson/validating[3.1.6].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.2/cli/php.ini
    - /etc/php/7.2/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.2/cli/conf.d/10-opcache.ini
    - /etc/php/7.2/cli/conf.d/10-pdo.ini
    - /etc/php/7.2/cli/conf.d/15-xml.ini
    - /etc/php/7.2/cli/conf.d/20-calendar.ini
    - /etc/php/7.2/cli/conf.d/20-ctype.ini
    - /etc/php/7.2/cli/conf.d/20-curl.ini
    - /etc/php/7.2/cli/conf.d/20-dom.ini
    - /etc/php/7.2/cli/conf.d/20-exif.ini
    - /etc/php/7.2/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.2/cli/conf.d/20-ftp.ini
    - /etc/php/7.2/cli/conf.d/20-gd.ini
    - /etc/php/7.2/cli/conf.d/20-gettext.ini
    - /etc/php/7.2/cli/conf.d/20-iconv.ini
    - /etc/php/7.2/cli/conf.d/20-json.ini
    - /etc/php/7.2/cli/conf.d/20-ldap.ini
    - /etc/php/7.2/cli/conf.d/20-mysqli.ini
    - /etc/php/7.2/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.2/cli/conf.d/20-phar.ini
    - /etc/php/7.2/cli/conf.d/20-posix.ini
    - /etc/php/7.2/cli/conf.d/20-readline.ini
    - /etc/php/7.2/cli/conf.d/20-shmop.ini
    - /etc/php/7.2/cli/conf.d/20-simplexml.ini
    - /etc/php/7.2/cli/conf.d/20-sockets.ini
    - /etc/php/7.2/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.2/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.2/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.2/cli/conf.d/20-tokenizer.ini
    - /etc/php/7.2/cli/conf.d/20-wddx.ini
    - /etc/php/7.2/cli/conf.d/20-xmlreader.ini
    - /etc/php/7.2/cli/conf.d/20-xmlwriter.ini
    - /etc/php/7.2/cli/conf.d/20-xsl.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
chgrp: cannot access '/var/www/snipeit/vendor': No such file or directory
* Generating the application key.
* Artisan Migrate.
* Creating scheduler cron.
no crontab for root
* Restarting Apache httpd.
  Q. Do you want to configure mail server settings? (y/n) n

  ***Open http:/db.fsha.local to login to Snipe-IT.***

* Cleaning up...
* Finished!

~$ cp .env.example .env
cp: cannot stat '.env.example': No such file or directory
~$ cd /var/www/snipeit
/var/www/snipeit$ cp .env.example .env
cp: cannot create regular file '.env': Permission denied
/var/www/snipeit$ composer dump-autoload
Generating optimized autoload files

                                                                    
  [RuntimeException]                                                
  /var/www/snipeit/vendor does not exist and could not be created.  
                                                                    

dump-autoload [--no-scripts] [-o|--optimize] [-a|--classmap-authoritative] [--apcu] [--no-dev]

/var/www/snipeit$ composer clear-compiled

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "clear-compiled" is not defined.                        
                                                                  

/var/www/snipeit$ php artisan config:clear
PHP Warning:  require(/var/www/snipeit/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/snipeit/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/snipeit/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/snipeit/bootstrap/autoload.php on line 17
/var/www/snipeit$ php artisan cache:clear
PHP Warning:  require(/var/www/snipeit/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/snipeit/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/snipeit/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/snipeit/bootstrap/autoload.php on line 17
/var/www/snipeit$ php artisan route:clear
PHP Warning:  require(/var/www/snipeit/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/snipeit/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/snipeit/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/snipeit/bootstrap/autoload.php on line 17
/var/www/snipeit$ php --version
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies
var/www/snipeit$ mariadb --version

Command 'mariadb' not found, but can be installed with:

sudo apt install mariadb-client-core-10.1

/var/www/snipeit$ mysql --version

Command 'mysql' not found, but can be installed with:

sudo apt install mysql-client-core-5.7   
sudo apt install mariadb-client-core-10.1 (You will have to enable component called 'universe')

/var/www/snipeit$ mysql -v

Command 'mysql' not found, but can be installed with:

sudo apt install mysql-client-core-5.7   
sudo apt install mariadb-client-core-10.1 (You will have to enable component called 'universe')

/var/www/snipeit$ apache --version

Command 'apache' not found, did you mean:

  command 'apache2' from deb apache2-bin

Try: sudo apt install <deb name>

/var/www/snipeit$ apache2 --version
[Fri Sep 21 13:48:42.460944 2018] [core:warn] [pid 20423] AH00111: Config variable ${APACHE_RUN_DIR} is not defined
apache2: Syntax error on line 80 of /etc/apache2/apache2.conf: DefaultRuntimeDir must be a valid directory, absolute or relative to ServerRoot
/var/www/snipeit$ httpd -v

Command 'httpd' not found, did you mean:

  command 'http' from snap http (0.9.9-1)
  command 'xttpd' from deb xtide
  command 'http' from deb httpie

See 'snap info <snapname>' for additional versions.**

________________________________________________

- Indicate whether or not you've manually edited any data directly in the database
No data has been altered.
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by perscheta** [comment]
> for the first few lines, it appears that your database (mariadb) is not installed, looking further into your logs looks like most of the packages were not installed. Ensure that the server has access to the internet and give the install.sh script a shot again.

Would it have anything to do with the Ubuntu OS and that it is 18.04? The reason I ask is that the command to install php is different from older version, where now, php7.2-xxx is the command as to before it was php-xxx

**Comment by perscheta** [comment]
Ok, I was able to install all php extensions along with Mysql but now I am in a loop 
<img width="580" alt="screen shot 2018-09-24 at 11 19 22 am" src="https://user-images.githubusercontent.com/31716811/45970565-bd5cde80-bfeb-11e8-8ef9-010a1f05660d.png">

I tried it twice and I keep getting this loop.

**Comment by EarlRamirez** [comment]
Try mysql_secure_installation from the terminal.

**Comment by perscheta** [comment]
great that fixed it! I was able to proceed and get to the preflight page.
 thanks!
