### ISSUE TITLE
QR codes doesn't change app url

### ISSUE THREAD

**Issue by mateuszWlazlowski** [snipe/snipe-it#6230]
Hello,
I have snipeit on my serwer, i'm using it by month connecting by IP to my server. Now I bought a domain which I entered in my .env file. From this moment when I want to print QR codes for assets some of them have new APP_URL and rest of them have still have old APP_URL. I deleted everything from /public/upload/barcodes/ and entered php artisan config:clear and php artisan config:cache.

What should I do to set every qr to new APP_URL?

**Comment by snipe** [comment]
You have to delete the old barcodes in `public/uploads/barcodes`

**Comment by mateuszWlazlowski** [comment]
@snipe as I said "I deleted everything from /public/upload/barcodes/ and entered php artisan config:clear and php artisan config:cache." and still the same.

**Comment by snipe** [comment]
The QR codes pull directly from the app_url, so there’s no way anything else could be going on. Have you tried clearing your browser cache and views cache?

**Comment by mateuszWlazlowski** [comment]
Yes, I cleared views cache and browser cache. I have 300 assets and only 8 have an old APP_URL adress

**Comment by PieterHc** [comment]
i there any news on this topic i'm struggeling with this to.
my app runs ons 172.22.0.18 but i created a dns name. 
I cleared everything metioned but the result stays the same

**Comment by snipe** [comment]
No news, because there's nothing new to report. The QR codes use the `APP_URL`. They get created and then cached in the directory mentioned above. If you've cleared your config cache AND your barcode cache, then I honestly don't know what to tell you. It's not more complicated than that.

**Comment by PieterHc** [comment]
Hello, 
thanks for the info, 
To be clear
I ajusted the .ENV file in the C:\inetpub\wwwroot\snipeit\ folder
i removed all files from the C:\inetpub\wwwroot\snipeit\public\uploads\barcodes folder
I entered the php commands from a CDM windows openend in my C:\inetpub\wwwroot\snipeit\ folder.
php artisan config:clear
php artisan config:cache

I'm running snipe on an IIS on a windows server 2019.
