### ISSUE TITLE
Composer installations issues: Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by orichard87** [snipe/snipe-it#6231]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by orichard87** [comment]
I get the following error:
Problem 1 
- roave/security-advisories dev-master conflicts with symfony/http-foundation[v3.4.12]
-Installation for roave/security-advisories dev-master -> satisfiable y roave/security-advisories[dev-master]
-Installation request for symfony/http-foundation (locked at v3.4.12) -> satisfiable by symfony/http-foundation[3.4.12]

**Comment by orichard87** [comment]
This is for a new install however I ran into similar issues to run composer update --lock

**Comment by snipe** [comment]
You shouldn't be updating composer. You should be using composer install

**Comment by Tonylaoshi2018** [comment]
if you run into this problem, you need to install other php realated packages. Make sure you have all installed according to below list. you can use yum install to install them.
PHP related package list:   php php-openssl php-pdo php-mbstring php-tokenizer php-curl php-mysql php-ldap php-zip php-fileinfo php-gd php-dom php-mcrypt php-bcmath .

**Comment by snipe** [comment]
I don't think you need mcrypt anymore unless you're upgrading from a very old version and need to convert encrypted fields.

I also don't think you need php-dom unless you're installing it in development mode (by running `composer install` without the `--no-dev` flag). That's used by the testing framework IIRC.

<img width="632" alt="Screen Shot 2020-09-15 at 11 10 16 PM" src="https://user-images.githubusercontent.com/197404/93298858-dfd3fd80-f7a8-11ea-8a04-0d39c9a88e73.png">

https://snipe-it.readme.io/docs/requirements

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/requirements">Requirements</a></strong></div><div>The requirements for Snipe-IT are fairly standard for a modern web server, and most servers will have most or all of these components already installed. If for some reason you don't have them installed, they are relatively easy to add.       </div></blockquote>
