### ISSUE TITLE
Unable to load pre flight page

### ISSUE THREAD

**Issue by abhalla89** [snipe/snipe-it#6232]
I am new to  snipe it , I did it everything but my preflight page doesnot have green check marks. 
![image](https://user-images.githubusercontent.com/43584077/46032920-df795e00-c0ca-11e8-8c63-9cc5993607a3.png)

Also when i click on create user/ create database table - nothing happens but if i click on step 2. stpe 3 - it goes to next page but cannot save user becuase the buttons are not working.

Also on the wamp
![image](https://user-images.githubusercontent.com/43584077/46033019-210a0900-c0cb-11e8-846d-2f61f4ae077e.png)

**Comment by EarlRamirez** [comment]
You will need to disable debugging from your .env and clear the cache and you should have all green.

**Comment by abhalla89** [comment]
Now it says whoops, like something wen wrong.

**Comment by EarlRamirez** [comment]
okay, enable debugging and proceed until you see the app then we can work together to disable debugging if you are still getting any errors share it with us.

**Comment by abhalla89** [comment]
Getting this now 

![image](https://user-images.githubusercontent.com/43584077/46089835-5b33e300-c17d-11e8-84ec-3a41779519a0.png)

**Comment by EarlRamirez** [comment]
the DB password in .env for snipe_user is incorrect, update it with the correct password and give it a try again.

**Comment by abhalla89** [comment]
Bingo good thing is i am on the screen and when i click create database tables , I get

![image](https://user-images.githubusercontent.com/43584077/46091295-88ce5b80-c180-11e8-8b0a-d8da75217576.png)

**Comment by EarlRamirez** [comment]
hmm strange, can you run the migration step and see if you get any errors?

**Comment by abhalla89** [comment]
it is on the migrate page only, how do you want me to run that.

**Comment by EarlRamirez** [comment]
from the terminal in Snipe-IT root directory **artisan migrate --force**

**Comment by EarlRamirez** [comment]
correction **php artisan migrate --force**

**Comment by abhalla89** [comment]
![image](https://user-images.githubusercontent.com/43584077/46092649-540fd380-c183-11e8-9501-43eb6f32d05b.png)

**Comment by EarlRamirez** [comment]
change the permission on the storage folder so that the app has access to read and write to the logs, for testing purpose give everyone full control to that file and run the command again

**Comment by abhalla89** [comment]
![image](https://user-images.githubusercontent.com/43584077/46093721-12ccf300-c186-11e8-8f51-df2e67cecdfb.png)

**Comment by EarlRamirez** [comment]
@abhalla89 do you still need assistance with this?

**Comment by juanolmeda** [comment]
Hi there,

I'm getting the very same error!  Exact same issue.  Already tried forcing the migration and then got the same 3 errors posted by @abhalla89.

What would be the correct way to fix this issue?

We are currently running MySQL Ver 15.1 Distrib 10.3.10-MariaDB...

Please advise and thank you!
