### ISSUE TITLE
Load Balancer Issues

### ISSUE THREAD

**Issue by a3yko** [snipe/snipe-it#6239]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

Its not so much a bug as it is a configuration issue.
I am getting the mixed content error on the server when ssl is injected via a load balancer which is external. From what i read in the reverse proxies section of the docs, the RequestHeader set X-Forwarded-Proto "https" piece would be usable if i am using apache as a load balancer rather than an external one, however, i went ahead and tried it anyway with no luck.

Side Note: We initially had it redirect in the load balancer, but have disabled it to make testing easier

So my question is, how would i force the app to change url's to https:// if its an external load balancer that makes all requests in https to a server running in http

I am new to some of the terminology and networking piece is not my strong suit and if I misunderstood the documentation or if I missed something I apologize in advance.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.4
 - OS: CentOS  7
 - Web Server: Apache
 - PHP Version: 7.2

**Desktop (please complete the following information):**
 - Device: Laptop
 - OS: Windows 10
 - Browsers: Chrome V69 Firefox V62 IEV11 Edge V42

**Error Messages**
**Mixed content errors**

**Additional context**
- Is this a fresh install or an upgrade? **Fresh install**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **manual**
- Include what you've done so far in the installation, and if you got any error messages along the way.
**The site works without https**
- Indicate whether or not you've manually edited any data directly in the database - **No**

**Comment by snipe** [comment]
What do you have in your .env for `APP_TRUSTED_PROXIES`?

**Comment by a3yko** [comment]
APP_TRUSTED_PROXIES=*

**Comment by snipe** [comment]
And you cleared your config cache after that?

**Comment by a3yko** [comment]
After every .env edit i run the following
composer dump-autoload - comes back with unknown command
composer clear-compiled - comes back with unknown command
php artisan config:clear
php artisan view:clear
php artisan cache:clear
php artisan route:clear

**Comment by a3yko** [comment]
I have also tried uncommenting the following lines in the .htaccess file provided
`   #RewriteCond %{HTTPS} off
    #RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]`
This gets rid of the mixed content errors i get in my browser console and the browser says the website is secure, however, I end up with the "Too many redirects error" in all browsers

**Comment by jwhulette** [comment]
@a3yko Where is your application and load balancer located, AWS? If so, I have used this: 
### Force HTTPS - Proto needed for AWS ELB
    RewriteCond %{HTTP:X-Forwarded-Proto} !https
    RewriteCond %{HTTP_USER_AGENT} !^ELB-HealthChecker
    RewriteRule ^.*$ https://%{HTTP:Host}%{REQUEST_URI} [L,R=permanent]

**Comment by a3yko** [comment]
@jwhulette 
Everything is run on site. I tested your snippet, and i am getting a "Too many redirects error"

**Comment by a3yko** [comment]
@jwhulette When i remove the rewrite, i get an insecure style sheet error and insecure script error. I can still login, however, it redirects back to http:// afterwhich the site loads normally with everything functioning. originally we set the  https redirect on the Load Balancer and while we did not get a "too many redirects" error. we got mixed content errors on all pages of the app.

**Comment by jwhulette** [comment]
@a3yko There is an option in the admin section, Admin -> Settings -> Remote Scripts. If you uncheck that it will not load remote scripts, it will use the included. See if that solves the issue. Also, what are the script & style urls?

**Comment by a3yko** [comment]
@jwhulette  I have unchecked the box requested and am still getting the following errors in the image below

![ereros](https://user-images.githubusercontent.com/13548954/46365747-0ab9fb00-c63f-11e8-8d98-810e0d54baa8.PNG)

**Comment by a3yko** [comment]
@jwhulette 
These are the request headers the app is receiving according to the Debugger
![request headers](https://user-images.githubusercontent.com/13548954/46366006-aea3a680-c63f-11e8-9380-fcf9844a2a93.PNG)

**Comment by jwhulette** [comment]
@a3yko Ok I believe the issue is that the application uses Laravel URL helper which creates a standard URL for the link. Try setting URL::forceScheme('https'); , https://stackoverflow.com/a/43677234

**Comment by a3yko** [comment]
@jwhulette I would be happy too, in which file/location would you like me to put that, I am not familiar with PHP to a level where i would be confident to edit any of this without guidance

**Comment by jwhulette** [comment]
App\Providers\ AppServiceProvider.php

**Comment by a3yko** [comment]
@jwhulette 
It worked, I will keep this open in case I run into problems for the next couple days. But it worked!

**Comment by snipe** [comment]
This is not the ideal solution here, and will make upgrading difficult.

**Comment by jwhulette** [comment]
With the new css / js cleanup in V5 this issue will should not occur. Since the assets were using the laravel **url** helper it was creating a standard http url and not creating the url based not the site url. 
It was a fix for his specific issue. 

I don't think it has anything to do with trusted proxies as that is used in php, not for getting stylesheets and javascript files, the browser is getting those. But I could be wrong.

**Comment by snipe** [comment]
> Since the assets were using the laravel url helper it was creating a standard http url and not creating the url based not the site url.

This should still work, using trusted proxies. That's what trusted proxies does, and it's worked previously. Laravel (Symphony, really, I think) tries to be clever and serve assets based on the protocol it can detect automagically, and for some reason that's not working for everyone suddenly.

**Comment by jwhulette** [comment]
@snipe You are right.

**Comment by chrkaatz** [comment]
This is still relevant
