### ISSUE TITLE
Licensing and seat serial numbers

### ISSUE THREAD

**Issue by JamesTaylor76** [snipe/snipe-it#624]
This is more a feature request/query than a bug,

We have a situation where our company owns multiple licences for an application.  Each of these licences are supplied on a USB Hasp dongle which each have a unique serial/license number.

To use these in the Snipe-IT model, we need to add each dongle individually to the licence list with one seat each.

I could create a [USB Licence] category and [Application X] as a model and add USB Dongles as assets in order to assign them, but as they are licenses Id like to manage them under the licenses section.  

Would there be any way to assign more detailed information to each seat of a licence or permanently assign a license seat to an asset (a USB dongle) other than when it is assigned to a person? 

Thanks.
##

**Comment by hyggja** [comment]
+1

**Comment by eduardok** [comment]
You can already checkout a license seat to an asset only, you are not required to select the user. Perhaps I'm misunderstanding.
