### ISSUE TITLE
Login problem via https

### ISSUE THREAD

**Issue by Thoronier** [snipe/snipe-it#6242]
**Server (please complete the following information):**
 - Snipe-IT Version 4.2.0
 - OS: [e.g. Ubuntu, CentOS] Microsoft
 - Web Server: [e.g. Apache, IIS] MySQL and IIS
 - PHP Version 7.2.8

**Is your feature request related to a problem? Please describe.**
When i logged in from ohter PC if I log on the tool from another pc, via https url. then, although the window goes up with loggin but when I log in I land again when loggin again. but if I log in locla on the server then it works.

**Describe the solution you'd like**
That the loggin from outside via https is possible.

**Describe alternatives you've considered**
The default is the tool is intended to be accessible from outside. Only company intrinsically accessible without the users having direct access to the server and using https.

**Additional context**
![grafik](https://user-images.githubusercontent.com/43639311/46141757-2c893b80-c255-11e8-8f30-a9a8f8c56e0f.png)

**Comment by snipe** [comment]
Please provide the additional information asked for in the original issue template, specifically that related to browser console logs and error logs.

**Comment by Thoronier** [comment]
![grafik](https://user-images.githubusercontent.com/43639311/46190277-42e5d480-c2f3-11e8-8e7c-00d534588c8d.png)

**Comment by Thoronier** [comment]
![grafik](https://user-images.githubusercontent.com/43639311/46459991-d9663a00-c7ba-11e8-95d9-954cd411e014.png)

**Comment by snipe** [comment]
What's your APP_URL in your .env and are you running this behind a proxy server?

**Comment by Thoronier** [comment]
The APP_URL is  APP_URL=https://bos-assetmanagement.bechtle.de and it runs behinde proxy server. I have set APP_TRUSTED_PROXIES on APP_TRUSTED_PROXIES=10.252.11.36,10.0.1.10

**Comment by a3yko** [comment]
@Thoronier Hello, I had the same issue you are having. I fixed it by adding `\URL::forceScheme('https');`
inside the boot function in the file /snipeit/app/providers/AppServiceProvider.php, also that line of code will not work unless you add the following at the top use Illuminate\Support\Facades\URL;

Thanks,
a3yko

**Comment by Thoronier** [comment]
You're a genius, that will solve the problem. Thank you a3yko and snipe.

**Comment by a3yko** [comment]
@Thoronier  sweet, you can find more info if need in #6239

**Comment by Thoronier** [comment]
Thanks
