### ISSUE TITLE
Searching Asset History Notes

### ISSUE THREAD

**Issue by koolk** [snipe/snipe-it#6243]
- Snipe-IT Version 4.6.4
 - OS: [e.g. Ubuntu, CentOS] Ubuntu
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7

**Is your feature request related to a problem? Please describe.**
When checking in/out an item there is a notes field, it would be an excellent improvement if that notes field was searchable via the main search function.

**Describe the solution you'd like**
Make the history notes field searchable

**Describe alternatives you've considered**
As a work around I copy the note and then go edit the asset and add the note to the asset notes.

**Additional context**
Since notes under the asset tag are searchable I think it makes sense for the asset history notes to be searchable as well.

**Comment by snipe** [comment]
> It would be an excellent improvement if that notes field was searchable via the main search function.

That's a little harder said than done. The notes on a checkout are stored in the table that holds actions, not the overall assets table. That actions table can get very large, and so querying against it can slow things down quite a bit for users with large datasets.

**Comment by koolk** [comment]
Would it be possible to have the note copy itself automatically into the overall assets table with a timestamp with an optional check box or something along those lines ?

**Comment by koolk** [comment]
> > It would be an excellent improvement if that notes field was searchable via the main search function.
> 
> That's a little easier said than done. The notes on a checkout are stored in the table that holds actions, not the overall assets table. That actions table can get very large, and so querying against it can slow things down quite a bit for users with large datasets.

Would it be possible to have the note copy itself automatically into the overall assets table with a timestamp with an optional check box or something along those lines ?

**Comment by snipe** [comment]
I think that would just be more confusing then, since it would imply to the user the they're searchable, but it's really only searching the assets table.

**Comment by luvustea** [comment]
This would help me a lot. Can we maybe have a checkbox to search the notes with a warning that it may take a long time?

**Comment by snipe** [comment]
I don't really see this happening. The UI is too confusing, and the table joins we'd have to do would be brutal.
