### ISSUE TITLE
Custom Fields for Assets

### ISSUE THREAD

**Issue by koolk** [snipe/snipe-it#6244]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.4
 - OS: [e.g. Ubuntu, CentOS] Ubuntu
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7

**Is your feature request related to a problem? Please describe.**
Currently when creating custom fields they can only be applied when creating a new "Model". This is good, but would be a tremendous improvement if custom asset fields could be created and applied to individual assets.

**Describe the solution you'd like**
When creating a custom field it would be automatically available to all existing assets and all newly created assets. Specifically I would use this with the drop down list for items that need to be in groups like Middle School Laptop Cart, Upper School Laptop Cart, Lower School iPad Cart, Upper School Faculty, Class of '22 etc... (These fields need to be searchable for quick access) Of course not all devices need this custom field in which case the drop down field would just be left as blank for those assets.

**Describe alternatives you've considered**
As an alternative I currently create users with the names I mentioned above and asset name accordingly, although this is not ideal because when a user checks out one of these laptops/devices for use It becomes tricky to track devices.
**Additional context**
It would be great if tags appeared next to the devices based on the custom fields similarly to the way they do with the meta status "deployed".

**Comment by snipe** [comment]
> Currently when creating custom fields they can only be applied when creating a new "Model". This is good, but would be a tremendous improvement if custom asset fields could be created and applied to individual assets.

That is literally the point of having them at the model level though. Every asset has a model, so you choose what custom fields you want at the model level, so that they are applied to the assets when you create/edit them. The “Groups” your describing are the field sets.

**Comment by koolk** [comment]
> > Currently when creating custom fields they can only be applied when creating a new "Model". This is good, but would be a tremendous improvement if custom asset fields could be created and applied to individual assets.
> 
> That is literally the point of having them at the model level though. Every asset has a model, so you choose what custom fields you want at the model level, so that they are applied to the assets when you create/edit them. The “Groups” your describing are the field sets.

Understood, I will create my custom field drop down and add it to a new field set. Then ill edit each Model adding it there. Finally, I will then go to the individual assets and select from drop down menu the option needed. I didn't understand how field-set/custom-field worked together. My brain understands now. Also, the bit i mentioned about a tag appearing under the status isn't necessary because it can be marked as visible from the customize view menu.
Thank you!
