### ISSUE TITLE
upgrade.php warnings 

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#6245]
Not sure how to really explain the issue other than to post the code block from ssh. While the script still works, there are several warnings / things to concern over. 

I'm not familiar enough with PHP to address/test any changes here but was curious if this could be investigated.

	PHP Notice:  Undefined offset: 1 in /var/www/html/snipeit/upgrade.php on line 16
	Welcome to the Snipe-IT upgrader.

	Please note that this script will not download the latest Snipe-IT
	files for you unless you have git installed.
	It simply runs the standard composer and artisan
	commands needed to finalize the upgrade after.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!! If you have any encrypted custom fields, BE SURE TO run the recrypter if upgrading from v3 to v4.
	!! See the Snipe-IT documentation for help:
	!! https://snipe-it.readme.io/docs/upgrading-to-v4
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	--------------------------------------------------------
	STEP 1: Backing up database:
	--------------------------------------------------------

	-- Starting backup...
	Dumping database snipeit...
	Determining files to backup...
	Zipped 67 files...
	Copying 2018-09-27-120702.zip (size: 327.32 KB) to disk named local...
	Successfully copied .zip file to disk named local.
	Backup completed!

	--------------------------------------------------------
	STEP 2: Putting application into maintenance mode:
	--------------------------------------------------------

	-- Application is now in maintenance mode.

	--------------------------------------------------------
	STEP 3: Pulling latest from Git (master branch):
	--------------------------------------------------------

	Git is installed.
	Already on 'master'
	warning: CRLF will be replaced by LF in .github/ISSUE_TEMPLATE/Bug_report.md.
	The file will have its original line endings in your working directory.
	warning: CRLF will be replaced by LF in .github/ISSUE_TEMPLATE/Feature_request.md.
	The file will have its original line endings in your working directory.
	warning: CRLF will be replaced by LF in .github/ISSUE_TEMPLATE/Bug_report.md.
	The file will have its original line endings in your working directory.
	warning: CRLF will be replaced by LF in .github/ISSUE_TEMPLATE/Feature_request.md.
	The file will have its original line endings in your working directory.
	-- Saved working directory and index state WIP on master: 55846cc Changed LOG::                                                                                                                                                              to Log::
	HEAD is now at 55846cc Changed LOG:: to Log::
	-- M    .github/ISSUE_TEMPLATE/Bug_report.md
	M       .github/ISSUE_TEMPLATE/Feature_request.md
	-- Already up-to-date.
	--------------------------------------------------------
	Step 4: Cleaning up old cached files:
	--------------------------------------------------------

	-- No bootstrap/cache/compiled.php, so nothing to delete.
	-- Deleting bootstrap/cache/services.php. It it no longer used.
	-- Deleting bootstrap/cache/config.php. It it no longer used.
	-- Configuration cache cleared!
	-- Cache cleared successfully.
	-- Route cache cleared!
	-- Compiled views cleared!

	--------------------------------------------------------
	Step 5: Updating composer dependencies:
	(This may take an moment.)
	--------------------------------------------------------

	-- Local composer.phar detected, so we'll use that.

	Generating optimized autoload files
	Loading composer repositories with package information
	Installing dependencies from lock file
	Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
	Nothing to install or update
	Generating optimized autoload files

	--------------------------------------------------------
	Step 6: Migrating database:
	--------------------------------------------------------

	-- Nothing to migrate.

	--------------------------------------------------------
	Step 7: Checking for OAuth keys:
	--------------------------------------------------------

	- OAuth keys detected. Skipping passport install.

	--------------------------------------------------------
	Step 8: Caching routes and config:
	--------------------------------------------------------

	-- Configuration cache cleared!
	Configuration cached successfully!
	-- Route cache cleared!
	Routes cached successfully!

	--------------------------------------------------------
	Step 9: Taking application out of maintenance mode:
	--------------------------------------------------------

	-- Application is now live.

	--------------------------------------------------------
	FINISHED! Clear your browser cookies and re-login to use :
	your upgraded Snipe-IT.
	--------------------------------------------------------

**Comment by snipe** [comment]
Those are just warnings. Did the upgrade work?

**Comment by Jarli01** [comment]
Yes, the upgrade works without issue. Just not sure how to address the warnings. Be the one from the script or some issue with something that needs to be updated on my host.

**Comment by snipe** [comment]
If it upgraded alright than I wouldn’t worry about it too much. I think we fixed the offset warning already, and the CRLF warning is hit trying to be helpful but ending up being confusing. You can learn more about that here: https://stackoverflow.com/a/5834094

**Comment by Jarli01** [comment]
Thanks
