### ISSUE TITLE
Clean up CSS files

### ISSUE THREAD

**Issue by jwhulette** [snipe/snipe-it#6246]
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by snipe** [comment]
Should I close this?
