### ISSUE TITLE
API Calls returning inconsistent and incorrect information

### ISSUE THREAD

**Issue by wsidl** [snipe/snipe-it#6248]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I've noticed this in the /licenses and /manufacturers endpoints so far, but when I retrieve a list of items from an endpoint, I will get the information relevant to object in question. If I call the endpoint for a specific object (providing the object's ID), I will get the information for that ID but the information is incorrect.

The specific fields I'm looking at is for licenses and manufacturers and the seats and free_seats_count (licenses) and at "licenses_count" (manufacturers).

Looking at /manufacturers, I will retrieve something similar to:
```javascript
... "support_email": "", "assets_count": 0, "licenses_count": 3, "consumables_count": 0, ...
```
This is similar to what is presented in the Web Interface. If I call /manufacturers/:id, the information returns is slightly different:
```javascript
... "licenses_count": 0, ...
```
Same thing happens with the /licenses endpoint for "seats" and "free_seats_count":
```javascript
... "seats": 25, "free_seats_count": 18, ...
```
vs /licenses/:id endpoint:
```javascript
... "seats": 25, "free_seats_count": 0, ...
```

**To Reproduce**
1. Create a manufacturer, a license by that manufacturer with a number of seats and assign/checkout some seats to users.
2. Create a request to /api/v1/manufacturers, find new manufacturer and check "licenses_count". Copy ID
3. Create a request to /api/v1/manufacturers/:id using ID from last step, check "licenses_count" again.
4. Create a request to /api/v1/licenses, find new license and check "free_seats_count". Copy ID.
5. Create a request to /api/v1/licenses/:id using ID from last step, check "free_seats_count" again.

**Expected behavior**
All values from endpoints should match the information from other endpoints.

**Server (please complete the following information):**
 - Snipe-IT v4.6.4
 - OS: CentOS 7
 - Web Server: Apache
 - PHP v5.6

**Error Messages**
No errors reported

**Additional context**
Also appears on development database on API Documentation

**Comment by snipe** [comment]
Manufacturers and a few other endpoints have already been fixed on develop.
