### ISSUE TITLE
New to Snipe-IT - Installation Issues on IIS

### ISSUE THREAD

**Issue by tzielinskiaptn** [snipe/snipe-it#625]
I am setting up Snipe-IT 1.2.6.

This is a Windows 2012 R2 Server, running IIS 8.5.

I have followed the instructions in the installing under IIS guide.

I'm seeing a call to undefined method error when I try acessing the site.

The entry in the error log is:

[2015-03-09 19:23:52] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Cookie\CookieJar::get()' in C:\inetpub\wwwroot\SnipeIT\vendor\cartalyst\sentry\src\Cartalyst\Sentry\Cookies\IlluminateCookie.php:105
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2015-03-09 19:25:57] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined method Illuminate\Cookie\CookieJar::get()' in C:\inetpub\wwwroot\SnipeIT\vendor\cartalyst\sentry\src\Cartalyst\Sentry\Cookies\IlluminateCookie.php:105
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []

Any help or guidance would be much appreciated.

**Comment by madd15** [comment]
Hi,
Could you try running the commands `composer update` and `composer dump-autoload`?

**Comment by tzielinskiaptn** [comment]
Hi,

I've run those two commands, both seem to complete.

**Comment by snipe** [comment]
And...? Has your error message gone away? Has it changed at all? 

Help us to help you :)

![helpme-helpyou](https://cloud.githubusercontent.com/assets/197404/6566058/d95237c8-c672-11e4-9b20-9f4fcda39b32.gif)

**Comment by tzielinskiaptn** [comment]
Sorry, my bad on that one.

I ran the two commands, both appear to complete.

I encounter the same error accessing the site.

**Comment by snipe** [comment]
So, I'm seeing reports of this error in connection to Sentry, and they recommend upgrading to Sentry 2.1.0. I don't know why you would be having this problem while others aren't but you can try this: 

In `composer.json`, change:

`"cartalyst/sentry": "2.0.*",`

to 

`"cartalyst/sentry": "2.1.*",`

And re-run `composer install`

If this works for you, I'll update the composer file in the repo.

**Comment by tzielinskiaptn** [comment]
This did resolve the original error, thank you. 

I will submit a new post for the next issue I've encountered.
