### ISSUE TITLE
"Active" User attribute is turned off when editing other not related to it information on the own user

### ISSUE THREAD

**Issue by tmvillain13** [snipe/snipe-it#6252]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When user with the grants to edit other users going into it's own profile and changing the data, "Active" flag got reseted and saved in OFF state. So the user cannot turn it back unless another user profile may turn it back to Active or via Data Base

**To Reproduce**
0. Login as User who may edit Users
1. Go to 'People'
2. Click on 'Edit' for your OWN user
3. Scroll down to 'City' and put a value
4. Make sure "Active" flag is ON
5. Press "Save" button
6. Logout
7. Try to Login
8. User is not able to login as "Active" flag reseted to OFF

**Expected behavior**
"Active" flag should not be reseted. Only "City" field should be updated.

**Screenshots**
![image](https://user-images.githubusercontent.com/4356443/46185190-34b59b00-c296-11e8-9fee-9165bb280df6.png)

**Server (please complete the following information):**
 - Snipe-IT Version : v4.6.4 build 3885 (g05ea61421)
 - PHP Version : 7.0.30-0ubuntu0.16.04.1

**Desktop (please complete the following information):**
 - OS: ANY

**Smartphone (please complete the following information):**
 - Device: ANY

**Error Messages**
- No Errors
- On Demo the feature is disabled

**Additional context**
- Fresh Install
- Running on QNAP via Docker

**Comment by snipe** [comment]
Does this happen with only your own user, or any user?

**Comment by tmvillain13** [comment]
That happens only with the own user.

**Comment by snipe** [comment]
This fix is in the latest release
