### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category_id' in 'field list' 

### ISSUE THREAD

**Issue by alanauckland86** [snipe/snipe-it#6253]
#### Please confirm you have done the following before posting your bug report:

- [ YES] I have enabled debug mode 
- [YES ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When creating a license from http:website.com/licenses/create
Using the "New" button to create a category is not inserting and updating the database with the category.
o when I visit the page I can choose the category it appears in the list. 
When I then submit the new license with the new category the license fails to create saying that the category doesn't exist: 
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category_id' in 'field list' 

When I visit the page to view categories only there are no categories. 

So to clarify on create a license page the category drop-down list is populated with a category I tried to make using the new button on that page. That category is not in the database and fails. 

I have cleared my browser cache. I have used debug mode and ran the PHP commands to clear the server cache. 

The category still appears in the dropdown list when trying to create a new license 

**To Reproduce**
1. Go to 'create new license '
2. Click on '.new next to category'
3. create a new category
3. Continue to create new license using the new category created

**Expected behavior**
New category and licence to be created 

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.3
 - OS: [e.g. Ubuntu server ]
 - Web Server: apache]
 - PHP Version : 7

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser [e.g. chrome 60 and FireFox 62]

**Error Messages**
- SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category_id' in 'field list'

**Comment by alanauckland86** [comment]
Last time we done server patches I done a git fetch and checkout out the latest tag.  It was previously 4. Something i believe. 


Sent from my Samsung device

-------- Original message --------

**Comment by snipe** [comment]
> Last time we done server patches I done a git fetch and checkout out the latest tag

When you upgrade Snipe-IT, you have to [go through the upgrade process](https://snipe-it.readme.io/docs/upgrading) or use `php upgrade.php` (as @EarlRamirez mentioned). If you just did  git fetch, you didn't actually run migrations, which is why you're seeing the column not found error. The column doesn't exist because you skipped the migrations process that adds it.

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
