### ISSUE TITLE
Switch the EULA text direction from LTR to RTL in email

### ISSUE THREAD

**Issue by ajsy** [snipe/snipe-it#6254]
Our EULA in Arabic language, at check-out user receive email with EULA the text direction is from left to right, how we can switch the text direction from LTR to RTL in email?

**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.4 build 3885 (g05ea61421)
 - OS: Ubuntu 18.04
 - Web Server: Apache
 - PHP Version : 7.2.10-0ubuntu0.18.04.1

**Additional context**
![new bitmap image](https://user-images.githubusercontent.com/35658596/46200897-881dfc80-c31b-11e8-8d8f-e6a953704ede.jpg)

already tried the html tag like this, but no luck
```
<div dir=rtl>...</div>
<div lang="ar-SY">…</div>
```

**Comment by jvarn** [comment]
I realise this thread is ancient, but I'll add this note here in case others need a quick fix for an RTL only deployment. Changing the email direction to RTL and text-alignment to right for all emails is relatively easy. Simply edit `/var/www/html/snipeit/resources/views/vendor/mail/html/layout.blade.php` and add the following to the style section:

```css
h1,p,table {
    direction: rtl;
    text-align: right!important;
}
```

I haven't yet found a simple way to apply it conditionally (e.g. LTR for English and RTL for Arabic).
