### ISSUE TITLE
Use of Non US characters in LDAP query 

### ISSUE THREAD

**Issue by LewkDo** [snipe/snipe-it#6255]
#### Expected Behavior (or desired behavior if a feature request)

I expect LDAP Search OU: OU=Malmö,OU=Sweden,DC=domain,DC=local
To only import users in that OU, not entire Sweden because LDAP query doesnt recognize the swedish character "Ö" in "Malmö".

-----

#### Actual Behavior

For some reason the LDAP imports OU=Sweden,DC=domain,DC=local

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Both fresh and after upgrade to 4.6.4 (build 3885)
- Version of Snipe-IT you're running
4.6.4 (build 3885)
- Version of PHP you're running
5.6.26
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
Windows IIS.
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual first, then reinstalled using git.
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
People - Ldap sync.
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by viktorfs** [comment]
Sorry for the "useless" answer but you should really get used to not using special characters as much as you can(þ,ð,ö,é,í) etc for AD, they will just cause a lot of unwanted pain in the ass for a lot of programs/systems. I had to change the name of a OU which had Ö in it and led to all kinds of shit that I did´t think of :/ .  
-Fun stuff

**Comment by LewkDo** [comment]
> 
> Sorry for the "useless" answer but you should really get used to not using special characters as much as you can(þ,ð,ö,é,í) etc for AD, they will just cause a lot of unwanted pain in the ass for a lot of programs/systems. I had to change the name of a OU which had Ö in it and led to all kinds of shit that I did´t think of :/ .
> -Fun stuff
Yes, I know, unfortunately my predecessor didn't :D 
 
It actually seems the Ö isnt the problem either, I removed the location with Ö in the name from SnipeIT, it happened to have the latest ID. Now the next "location" with highest ID syncs all users, even outside target OU...
