### ISSUE TITLE
Deployed Assets -- Incorrect status.

### ISSUE THREAD

**Issue by flbased** [snipe/snipe-it#6257]
#### Expected Behavior (or desired behavior if a feature request)
On asset checkout, Status should say deployed

-----

#### Actual Behavior

**- System is updating Checkin/Checkout from Checkout to Checkin
**- "Status" reads - (Blue Circle) Ready to Deploy [Deployed]
**- Clicking on (Blue Circle) Ready to Deploy [Deployed] takes me to "Ready to Deploy Assets" page
**- Dashboard does not show Deployed Asset count 
**- Clicking on Nav bar > All Deployed does return the "Deployed Assets" Page with showing the deployed assets.

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  - 3 fresh installs, 2 on Ubuntu 18.4 LTS and 1 on IIS
- Version of Snipe-IT you're running - 4.6.4
- Version of PHP you're running - 7.2.10
- Version of MySQL/MariaDB you're running - 10.1.34
- What OS and web server you're running Snipe-IT on - Ubuntu 18.4 LTS / Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - https://snipe-it.readme.io/docs/installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - No
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - N/A
- If a stacktrace is provided in the error, include that too. - No
- Any errors that appear in your browser's error console. - No
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - Yes
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help
![image](https://user-images.githubusercontent.com/43681746/46222929-df25d080-c31f-11e8-8537-5486a43db0b6.png)

**Comment by snipe** [comment]
> "Status" reads - (Blue Circle) Ready to Deploy [Deployed]

So, it's showing as deployed. The only bug I see here is "Dashboard does not show Deployed Asset count" - which there are existing issues about.

Or am I missing something?

**Comment by flbased** [comment]
Noted on the dashboard.

- Under "Status" The text Reads "Ready to Deploy [Deployed]" not Deployed.

From the Nav bar > Assets > List All
- In its current state, when clicking on any item with the status "Ready to Deploy [Deployed]" Status, it does not go to the Deployed Assets page but the  Ready to Deploy Assets Page listing both the (Green Button) Ready to deploy items and (Blue Button) Ready to Deploy [Deployed] assets.

![image](https://user-images.githubusercontent.com/43681746/46228751-19e43480-c331-11e8-8ea1-45e2135a4584.png)

**Comment by flbased** [comment]
> That's the expected behavior. The status label is "Ready to Deploy", the status type is "deployed".
>
Has this text been changed in later releases? Why would the Status be "Ready to Deploy" when the asset is checked out and deployed? 

Any feedback on:
From the Nav bar > Assets > List All
- In its current state, when clicking on any item with the status "Ready to Deploy [Deployed]" Status, it does not go to the Deployed Assets page but the Ready to Deploy Assets Page listing both the (Green Button) Ready to deploy items and (Blue Button) Ready to Deploy [Deployed] assets.

**Comment by snipe** [comment]
> Has this text been changed in later releases? 

Many versions ago, yes.

> Why would the Status be "Ready to Deploy" when the asset is checked out and deployed?

Because that's literally the status name it belongs to. We used to obfuscate that when it was deployed, and people complained, so we provide both now.

**Comment by flbased** [comment]
OK, thank you for the quick response.

I will await your answer on my Nav Bar query. As an update, I also just tested clicking on the "Ready to Deploy [Deployed]" Status from within the Deployed Assets Page (Nav Bar > Assets > All Deployed) and once again it took me to the Ready to Deploy Assets page listing both the items as show in my screen shot above.

**Comment by snipe** [comment]
I'm not really sure what you mean about nav bar. I can't reproduce this at all, locally or on the demo. Ready to Deploy on the demo shows this:

<img width="1431" alt="screen shot 2018-09-29 at 5 06 13 pm" src="https://user-images.githubusercontent.com/197404/46251546-11136180-c40a-11e8-9ff1-14dd9581abd1.png">

**Comment by flbased** [comment]
By nav bar I mean the left side of the screen, Dashboard, Assets, Licenses.....etc. 
![image](https://user-images.githubusercontent.com/43681746/46290694-84c48400-c55a-11e8-926c-524559dff86f.png)

- Clicking on Assets  > All Ready to Deploy - returns the correct information.
- Clicking on Assets > All Deployed - returns the correct information).
-- From within the All Deployed results, clicking on any status of  ![image](https://user-images.githubusercontent.com/43681746/46291175-cd307180-c55b-11e8-8d6f-5c862c7f9ce2.png) takes you to the Ready to Deploy Assets page listing both ![image](https://user-images.githubusercontent.com/43681746/46291383-4c25aa00-c55c-11e8-9058-09227b497483.png) and ![image](https://user-images.githubusercontent.com/43681746/46291365-43cd6f00-c55c-11e8-9a12-b469854f9e87.png) assets. This is confirmed happening on 10/1/2018 on the demo site as well.
![image](https://user-images.githubusercontent.com/43681746/46290942-35328800-c55b-11e8-9089-d65d2338edb4.png)
 On the demo site, the above described behavior is being returned under https://demo.snipeitapp.com/statuslabels/1 while results for my install are being returned under https://my.url/statuslabels/2

**Comment by snipe** [comment]
That's expected behavior, since it's linking to all of the assets with that status label.

**Comment by flbased** [comment]
I have been using snipe-it for quite some time, worked with many different versions and very much like the product however there is something fundamentally wrong here. All the answers I am getting back from the issues raised is 'expected behavior". From someone who manages and have to report on asset assignments, producing custom reports which the verbiage shown on the .csv that an asset Status : Ready to Deploy (deployed) is confusing at best to upper management.
Also:
 - A deployed asset should not have a status labelled "Ready to Deploy [Deployed] - can the text not be changed to Deployed or Deployed [Deployed] as in previous versions? Would this not also address the incorrect results obtained as described in my last post? 
- We cannot be expected to accept that from my screen shot of the Ready to Deploy assets Page also directly shown on https://demo.snipeitapp.com/statuslabels/1 that an asset which is already checked out be listed under the Ready to Deploy Assets page. Providing this list is generated by Status labels, would changing the text on the status label not also address this issue?

https://demo.snipeitapp.com/statuslabels/1 = ![image](https://user-images.githubusercontent.com/43681746/46355906-b65b4f00-c62f-11e8-8aa5-acf883a92dfd.png) and ![image](https://user-images.githubusercontent.com/43681746/46355930-c3783e00-c62f-11e8-9c59-3c484802a286.png)


https://demo.snipeitapp.com/statuslabels/2 = Pending
https://demo.snipeitapp.com/statuslabels/3 = Archived
Can there not be a https://demo.snipeitapp.com/statuslabels/x = Deployed 

I hope there can be some resolution to this as snipe-it truly is a great product.

**Comment by jackka** [comment]
**Snipe**, **Flbased**,
Excuse me for squeezing into your conversation.
But I almost opened new issue for the same problem.

But missing "Deployed" status.. and this your conversation makes doubt to me what should I do next.

As far as the Snipe-IT is completely suitable for me and I plan to contribute as developer to this project, 
I'll try to making clear this issue for myself if **Admirable Snipe** would allow it.

I've contributed a little bit with Russian translation at http://crowdin.com
What I see in my deployed Snipe-IT instance?
Total discordance in Russian and English translation around statuses!

(In Russian status "Undeployable" translated like "Выданные" that means "Deployed" but in English "Deployed" doesn't exist )

![image](https://user-images.githubusercontent.com/6271335/47849104-898e8900-dde1-11e8-850a-3634ecfa9ba7.png)

So, I think statuses is the key moment of the Snipe-IT and I want to ask You, **Greatly Respected Snipe**
for more information about the causes and the people who incited You to decide making mess in statuses.
I'm still not understand how the clear status "Deployed" could perceive some way otherwise?

Thank You in advance 
for a little bit more details about mess with "Deployed" status. May be a link to old conversation about it?...

**Comment by jackka** [comment]
**Dear Snipe**, sorry for disturbance, but you know here is -> [issue 6117](https://github.com/snipe/snipe-it/issues/6117) something weird with the meta “Deployed” status has risen and floats with bubbles (joke).

**Comment by jackka** [comment]
Ow, **Snipe**! I've understood the essence!
We shouldn't (doesn't make sense just alone status change to "Deployed" without target) and therefore Snipe-IT doesn't give us assign "Deployed" status by hand. Just action "Checkout to" with real target make sense to assign "Deployed" status.

And it seems I see the solution with mess around "Ready to Deploy [Deployed]" ! 

Try to fix the names of statuses from "Ready to deploy" -> "Deploying" 
and status "Ready to Deploy [Deployed]" -> "Deploying [complete]"

Huh? :)

**Comment by fumunda** [comment]
I too like the idea of having assets that when they are checked out, automatically go to a status of "Deployed" rather than "Ready to Deploy (Deployed)".  Current setup seems kinda redundant and wonky.  Would there be a way for me to add the function to "check out" that it automatically puts in Deployed status?  I can create my own status label for it sure, but I would like to have  a way to have it done automatically at "Check Out".  When checking in, I would still have to assign status which makes sense.  I have a status label of "In for Repairs" that I have to select if that is the case.  You get what I mean....

Just a thought.

**Comment by jackka** [comment]
Oh! Just glance what I found here. https://github.com/snipe/snipe-it/wiki/Assets
The glorious days.

**Comment by jackka** [comment]
@fumunda 
We have auto status changing action which needs to keep originator status. That's the reason why it is what it is, I think.

**Comment by Jjohn490** [comment]
What @flbased said.

**Comment by jackka** [comment]
I understand that it's a difficult core question and maybe will be solved by another elegant feature which gives user more choice with status system, for example.

**Comment by sashashark** [comment]
In full agreement with @flbased and others have posted.  This is an odd choice :/   I'm a new user (setup today, yay!) and baffled by the choice to not have a Deployed status.  That said, the reports and dashboard do show Ready to Deploy (Deployed), so I can make it work.  I guarantee my boss will question this though...

**Comment by jackka** [comment]
@sashashark
>This is an odd choice :/

I think it's temporary decision in software evolving process which gives an opportunity to split out automatically changeable status (condition) "Deployed" and other regular statuses which like a markers works.

>I guarantee my boss will question this though...

Boss should also ask - how much.
My boss already asked :) and we will continue to use this  admirable software.

**Comment by michaelfahy** [comment]
I've got a similar issue, but the Status column shows both Pending and Deployed which does not make sense.
It should just show deployed.
![pending-deployed](https://github.com/snipe/snipe-it/assets/8452366/4f1a4d96-0b63-48de-b317-d56aa7d096a8)

**Comment by snipe** [comment]
@michaelfahy In your case, "Pending" is the name of the label. Think about your workflow and figure out what status label names make the most sense for how your stuff works.
