### ISSUE TITLE
v5 (develop) - Remove remote JS/CSS file loading

### ISSUE THREAD

**Issue by jwhulette** [snipe/snipe-it#6259]
Since this is a business critical application all related JS / CSS file should be loaded from the application. External files may not be available. 

The option to have external loading file should be removed also.

**Comment by jwhulette** [comment]
Just seems odd to have it for maybe 2 js files. It’s adding overhead on the page rendering albeit minuscule. 
Just a thought.

**Comment by snipe** [comment]
Well, then they open a ticket here and we tell them. :-/ 

I don't have strong enough feelings on this to really object.
