### ISSUE TITLE
Logo size on mobile devices

### ISSUE THREAD

**Issue by rp-tech** [snipe/snipe-it#627]
This is a minor issue.

When utilizing the mobile interface along with the new logo feature, the new logo does not shrink to fit the size of the mobile device, resulting in having to scroll over to read the whole page (particularly noticeable when using a long logo).

Expected behavior: logo should shrink along with the rest of the page reflow to fit on the screen of the mobile.

Not a big deal, just FYI.

**Comment by snipe** [comment]
Thanks for the heads up

**Comment by snipe** [comment]
FYI, we're having a tough time reproducing this.
