### ISSUE TITLE
 Snipeit.sh error in proxy environment

### ISSUE THREAD

**Issue by a0z0** [snipe/snipe-it#6270]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.4
 - OS: CentOS 7
 - Web Server: Apache
 - PHP Version 7.2.9

Snipeit.sh error in proxy environment.
Where can I set the proxy in PHP.

https://github.com/snipe/snipe-it/blob/master/snipeit.sh
169:  run_as_app_user php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"

**Comment by EarlRamirez** [comment]
@a0z0 you have a few options, duckduckgo recommends https://stackoverflow.com/questions/3487845/using-http-proxy-in-php or you can do it from the OS level as described here ==>> https://nazimkuet.wordpress.com/2015/08/26/how-to-setup-network-on-centos-7-and-configuring-web-proxy/

**Comment by EarlRamirez** [comment]
@a0z0 thanks for the feedback, will have to test it thoroughly before I make a PR.
