### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by jmartins1** [snipe/snipe-it#6271]
Is there any plan to move over to HTTPS?

I really like SnipeIT but connecting it to Active Directory without HTTPS encryption is an issue. I was easily able to extract a test user's login information through packet sniffing. Please tell me this is in the works.

**Comment by snipe** [comment]
I don’t understand the question. If you want to run Snipe-IT, you can do that. In fact, we encourage it.

**Comment by jmartins1** [comment]
Okay, maybe I should have started with a more basic question. How do I run SnipeIT in HTTPS.

**Comment by snipe** [comment]
https://besthostingforasp.net/install-ssl-certificate-windows-server-2012-r2/
