### ISSUE TITLE
QR code label is caching old IP address - want to redirect to new IP address

### ISSUE THREAD

**Issue by leyeoyelami** [snipe/snipe-it#6273]
#### Expected Behavior (or desired behavior if a feature request)
so...i changed the IP address for my snipeit from xxx.xxx.xxx.120 to xxx.xxx.xxx.125. Thus, when i generate labels; some of the assets that was imported under the old IP address are redirecting to ...xxx.120. However, any new assets under the new IP address - works fine.  

I want all the asset labels or QR code to redirect to the new IP address.

-----

#### Actual Behavior

All of the assets that were created under the old IP address are not redirecting to the new IP address.
-----

#### Please confirm you have done the following before posting your bug report:

- [yes] I have enabled debug mode 
- [yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
fresh install
- Version of Snipe-IT you're running
4.6.3
- Version of PHP you're running
PHP 7.1.21 (cli)
- Version of MySQL/MariaDB you're running
5.5.60-MariaDB
- What OS and web server you're running Snipe-IT on
CentOS 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
n/a
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
n/a
- If a stacktrace is provided in the error, include that too.
n/a
- Any errors that appear in your browser's error console.
n/a
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
n/a
- Include any additional information you can find in `storage/logs` and your webserver's logs.
n/a
- Include what you've done so far in the installation, and if you got any error messages along the way.
n/a
- Indicate whether or not you've manually edited any data directly in the database
n/a

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Clear the files from the public/uploads/barcodes directory

**Comment by leyeoyelami** [comment]
that didn't fix it.

**Comment by leyeoyelami** [comment]
> that didn't fix it. its still redirecting to the same old IP address.

when i look at the URL closer. it seems to be redirect to "IP Address/hardware/(old asset tag)

**Comment by Jarli01** [comment]
Did you simply remove everything ```.png``` with ```sudo rm -rf qr*.png```?

**Comment by leyeoyelami** [comment]
> Did you simply remove everything `.png` with `sudo rm -rf qr*.png`?

that's right. i removed everything *png using that command.

**Comment by Jarli01** [comment]
And once you removed those labels you generated a new label?

**Comment by leyeoyelami** [comment]
yeap! that's correct. and the old assets that were imported under the old IP address are still redirecting to the old IP.

**Comment by Jarli01** [comment]
@snipe can you reopen?

**Comment by snipe** [comment]
I can't imagine how this is a bug. The QR code generator just takes the APP_URL and creates the code. There's nothing more complicated going on.
