### ISSUE TITLE
Automatic backups on Linux Server

### ISSUE THREAD

**Issue by nomanrehman** [snipe/snipe-it#6274]
**Server (please complete the following information):**
 - Snipe-IT Version : v3.5.2-11
 - OS: [e.g. Ubuntu, CentOS] CentOS
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 5.6.29

**Is your feature request related to a problem? Please describe.**
How to take automatic backup of Snipe-IT all assets and how to configure email when backup is taken then it automatically send e-mail on a specific ID. 
Same automatic email when the asset life comes to an end (EOL).

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/configuring-alerts-backups
