### ISSUE TITLE
synchronize assets into iTop? 

### ISSUE THREAD

**Issue by SSOHPG** [snipe/snipe-it#6275]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.5
 - OS: [e.g. Ubuntu, CentOS] Centos 7
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version  7.2

**Is your feature request related to a problem? Please describe.**
only a problem i'm trying to solve haha.

**Describe the solution you'd like**

i love snipe-it and we use iTop as helpdesk and ITSM/CMDB tool and i'm looking for a way to have our computers and laptop somehow synchronised to the CMBD of iTop so we can attach tickets to devices and i have no concrete idea on how to do this. maybe someone has already had experience getting this to work?

both snipeit and itop have a REST api maybe that is the way to go?
iTop can work with csv files as data synchro source but that would mean i would have to somehow automatically generate a csv file from Snipeit and let that import on a timed interval into iTop.

**Describe alternatives you've considered**

**Additional context**
Looking for input here or ideas and help if possible maybe steering me into the right directions is enough.

if this question is totally out of scope feel free to close it.

**Comment by Mynty100** [comment]
Helpdesk with integrated with an Asset Managment is something we are after as well. Looking at iTop mixed in with SnipeIT would be godlike, or if SnipeIT decided to make there out helpdesk within the SnipeIT app. However, I dare say, this is either not on their radar or if undertaken would require a major overhaul.
