### ISSUE TITLE
Adding a multiple checkout list feature

### ISSUE THREAD

**Issue by kuromatsu01** [snipe/snipe-it#6278]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.5
 - OS: Ubuntu 16
 - Web Server: nginx
- PHP Version 

**Is your feature request related to a problem? Please describe.**
It's a pain to check out the license to multiple users e.g. got slack 
Have to assign every single user a slack license

**Describe the solution you'd like**
A multi user "Check out to..." where i can check everyone or more user at a time

Thank you very much!

**Comment by ccomtest** [comment]
Have the same Issue.
Would like to add a Windows 2 core license to a server asset. For the Moment I have to put one license after one to the asset. With 6 servers having 28 cores each, there is no fun in any way.
