### ISSUE TITLE
Using snipe-it with squid proxy

### ISSUE THREAD

**Issue by bab5470** [snipe/snipe-it#6281]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I have a snipe it installation on a centos system without direct internet access. Outbound internet requests have to go through a squid proxy. I've set the HTTP_PROXY and HTTPS_PROXY values on my system but they aren't picked up by snipe-it. I believe that this is more of a PHP issue than a snipe-it issue. However it is possible to make PHP curl requests use a proxy server via CURL_OPTS:

$url = 'https://www.google.com';
$proxy = 'myproxyserver.domain.local:8080';
//$proxyauth = 'user:password';

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,$url);
curl_setopt($ch, CURLOPT_PROXY, $proxy);
//curl_setopt($ch, CURLOPT_PROXYUSERPWD, $proxyauth);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_HEADER, 1);
$curl_scraped_page = curl_exec($ch);
curl_close($ch);

echo $curl_scraped_page;

The reason this is a problem is that the slack integration needs to be able to make an outbound https connection and since the system doesn't have direct internet access the request fails. I suspect this would also impact things like checking for updates etc. 

**To Reproduce**
Your system should not have direct internet access 
You need a *forward* proxy server setup (for examples squid)

Steps to reproduce the behaviour:
1. Go to settings
2. Click on slack
3. Enter a valid endpoint, slack channel, and bot name, then click "Test # Integration"
4. You'll get an error: cURL error 7: Failed connect to hooks.slack.com:443; Connection timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Expected behavior**
You should be able to specify an http and https proxy server (and ports) in .env and the CURL request should use those. 

**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.4 
 - OS: Centos
 - Web Server: Apache 
 - PHP Version: PHP 5.6.38

**Comment by EarlRamirez** [comment]
@bab5470 apologies for taking this long to get back to you on this. I was able to install Snipe-IT behind a Squid proxy, one thing I did notice was after I updated /etc/environment I had to reboot the server for the changes to take effect.
Below are the steps I took

- add proxies to /etc/environment 
http_proxy="server_IP_address:porxy_port"
https_proxy="server_IP_address:porxy_port"
ftp_proxy="server_IP_address:porxy_port"
- Reboot server
- Download Snipe-IT using git
- Run ./install.sh from the snipe-it directory 

Below are a few logs from the Squid proxy server
1539948046.415    783 192.168.122.47 TCP_TUNNEL/200 25196 CONNECT github.com:443 - HIER_DIRECT/192.30.253.113 -
1539948048.273    864 192.168.122.47 TCP_TUNNEL/200 132360 CONNECT github.com:443 - HIER_DIRECT/192.30.253.113 -
1539948048.274   1796 192.168.122.47 TCP_TUNNEL/200 8831 CONNECT github.com:443 - HIER_DIRECT/192.30.253.113 -
1539948048.983    698 192.168.122.47 TCP_TUNNEL/200 8732 CONNECT github.com:443 - HIER_DIRECT/192.30.253.113 -
1539948050.828    857 192.168.122.47 TCP_TUNNEL/200 92308 CONNECT github.com:443 - HIER_DIRECT/192.30.253.113 -
1539948050.828   1776 192.168.122.47 TCP_TUNNEL/200 9120 CONNECT github.com:443 - HIER_DIRECT/192.30.253.113 -
1539948051.495    645 192.168.122.47 TCP_TUNNEL/200 9092 CONNECT github.com:443 - HIER_DIRECT/192.30.253.113 -
1539948053.242    922 192.168.122.47 TCP_TUNNEL/200 151011 CONNECT github.com:443 - HIER_DIRECT/192.30.253.113 -
1539948053.242   1694 192.168.122.47 TCP_TUNNEL/200 13279 CONNECT github.com:443 - HIER_DIRECT/192.30.253.113 -
1539948053.922    668 192.168.122.47 TCP_TUNNEL/200 13236 CONNECT github.com:443 - HIER_DIRECT/192.30.253.113 -
1539948055.958   1206 192.168.122.47 TCP_TUNNEL/200 1210046 CONNECT github.com:443 - HIER_DIRECT/192.30.253.113 -
1539948055.958   1991 192.168.122.47 TCP_TUNNEL/200 41436 CONNECT github.com:443 - HIER_DIRECT/192.30.253.113 -
1539948056.787    818 192.168.122.47 TCP_TUNNEL/200 41268 CONNECT github.com:443 - HIER_DIRECT/192.30.253.113 -

Let me know if this helps

**Comment by bradley-baker** [comment]
I'm sorry this is still not working for us and in the example above all you've done is shown that GIT can use the proxy. Not that snipe-it can. 

If snipe-it were using the proxy you'd see entries for hooks.slack.com in the proxy server logs. 

I can confirm if I setup a static page like like test.php and use the following it automatically uses the proxy: 

`<?php

$ch = curl_init("http://www.example.com/");
$fp = fopen("example_homepage.txt", "w");

curl_setopt($ch, CURLOPT_FILE, $fp);
curl_setopt($ch, CURLOPT_HEADER, 0);

curl_exec($ch);
if(curl_error($ch)) {
    fwrite($fp, curl_error($ch));
}
curl_close($ch);
fclose($fp);
?>`

So I can prove that our proxy server works, that php can access it using curl but snipe it just produces: cURL error 7: Failed connect to hooks.slack.com:443; Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)

I don't even see it attempting to hit the proxy server so I have a feeling its ignoring the proxies in  /etc/environment

I also rebooted after updating /etc/environment and setenforce (selinux) is set to permissive. Could you please have a look at this again?

<blockquote><img src="https://curl.haxx.se/favicon.ico" width="48" align="right"><div><strong><a href="https://curl.haxx.se/libcurl/c/libcurl-errors.html">libcurl - Error Codes</a></strong></div></blockquote>

**Comment by bradley-baker** [comment]
Is there a way to re-open this or should I create a new issue.

**Comment by bradley-baker** [comment]
I tried setting my http proxy via environment variables - uppercase/lowercase, with and without a protocol, and using an IP. 

While curl and wget were happy, and I could even get the PHP curl function to work in a test.php file - snipe-it stubbornly refused to use my proxy server for outbound internet access. 

(Our snipe-it installation resides on a management server in a secure segment of our network without direct outbound internet access)

I was finally able to get it to work using a bit of hacking (use this at your own risk!). Hopefully it helps someone else though:

Find this block in /vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php and remove it:

```
        if (isset($options['proxy'])) {
            if (!is_array($options['proxy'])) {
                $conf[CURLOPT_PROXY] = $options['proxy'];
            } else {
                $scheme = $easy->request->getUri()->getScheme();
                if (isset($options['proxy'][$scheme])) {
                    $host = $easy->request->getUri()->getHost();
                    if (!isset($options['proxy']['no']) ||
                        !\GuzzleHttp\is_host_in_noproxy($host, $options['proxy']['no'])
                    ) {
                        $conf[CURLOPT_PROXY] = $options['proxy'][$scheme];
                    }
                }
            }
        }
```


Replace it with this:
`$conf[CURLOPT_PROXY] = "1.2.3.4:8080";`

Substitute 1.2.3.4:8080 with your proxy servers IP and port number. Note there's no http or https in front of it.

You may need to clear your cache:
`php artisan config:cache`

You may also need to either turn selinux off
`setenforce permissive`

Or allow access to your snipeit installation via
`chcon -R -t httpd_sys_rw_content_t /path/to/your/snipeit`

**Note because we're hacking the guzzle http library directly if you ever upgrade snipe-it you will need to do this again.**  This has been tested on 4.9.2

I suspect the root of this issue is that SnipeIt should be setting "$options['proxy']"" when it calls the GuzzleHTTP library (and maybe it is - I don't know the SnipeIt source code well enough) I just couldn't get SnipeIt to use my proxy server any other way. 

I really hope this saves someone else hours of troubleshooting I spent trying to figure it out.

**Comment by MichalMMac** [comment]
Why is this issue closed? HTTP proxy support would be great thing to have.
