### ISSUE TITLE
Improve total Purchase Cost Calculation in /accessories

### ISSUE THREAD

**Issue by fixlair** [snipe/snipe-it#6282]
**Server (please complete the following information):**
N/A : Cloud Version

**Is your feature request related to a problem? Please describe.**
On Accessories page, the Total purchase cost does not take into account Total Quantity, it only does a Sum of each type of Accessories

**Describe the solution you'd like**
It seems to be nice to make a sum of : Total Number of each accessories x Purchase cost of each accessories 

![image](https://user-images.githubusercontent.com/664748/46393287-d436bb80-c6e4-11e8-8624-22b62db59db5.png)

**Comment by fixlair** [comment]
Yes I think it's still revelant !

**Comment by tymik** [comment]
dup of #5614

**Comment by bcourtade** [comment]
Still relevant Stale Bot...

**Comment by masood7xt** [comment]
Still facing this issue and it hasn't been solved.

**Comment by taigaak** [comment]
This is still a relevant issue.
