### ISSUE TITLE
Snipe-IT v5 Progress Report

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#6287]
Hello, nerds!

Just a quickie update on what we've gotten done so far in the upcoming v5 (currently on the `develop` branch). Lots of stuff is changed under the hood, as we've upgraded the underlying framework to Laravel 5.7, but there are a bunch of bufixes and new features, as well as some UI improvements.

One of the bigger changes to the system is the introduction of Flysystem support, which means you can host your asset uploads, logos, etc on S3 or Rackspace.

The small things matter as much to us as the big ones do, so we've spent some time trying to really refine some of the commonly used UI elements, for example the improved logo upload+preview interface:

![better-logo](https://user-images.githubusercontent.com/197404/46439862-863aab80-c716-11e8-82b3-5e2c7c89d799.gif)

### Added
- Added attempted logins admin screen
- Added better support for NFC/RFID/Barcode scanners in select boxes
- Added ability to trigger password reset emails for users
- Added Raspbian 9.4 to snipeit.sh installer
- Added department and manager to user import
- Added php version check to `upgrade.php`
- Added check for minimum PHP version in setup
- Added #5957 - Flysystem support #6262 which allows you to use S3 or Rackspace to host your file uploads
- Added console command to move local files to S3 (or other remote host) for Flysystem support
- Added better asset acceptance flow (thanks, @uberbrady and @tilldeeke!)
- Added console command to send inventory reports to users
- Added alt text to email headers
- Added #1237 - depreciation with half-year convention.
- Remove company select option if the user is not an admin and FCS is enabled
- Improved help windows
- Added save button at the top of the screen for long create/edit forms 
- Added basic client-side validation
- Added basic kit functionality

### Fixed
- Fixed #6004 - set a default `next_audit_date` if none provided
- Fixed #6011 - use correct file created at date
- Limit width of title logo so it doesn’t break with long names
- Fixed #6013 - add accessory checkout notes to detail page
- Fixed #5964 -  group IDs can be now be passed to user creation API
- Fixed bug where checkout right-side menu would display assets checked out to non-users with the same ID
- Fixed DBAL issue affecting MariaDB 10.2.7 or greater
- Fixed #6029 - model number not appearing in checkin/checkout emails
- Fixes #6016 - check for an existing username before getting creative
- Fixed - only allow activated users to reset their password
- Fixed - set activated checkbox to 1 by default on new user
- Fixed #6082 - don’t show expected checkin in email if none given
- Fixed #6284 - missing checkout information on Status Labels API asset list method
- Fixed #6252 - activated flag not checked when editing active user
- Fixed #4151 - undefined index: `samaccountname` on LDAP import
- Fixed #6248 - add free seats to licenses API endpoint
- Fixed #5965 - allow multiple alert email addresses (#6233) (regression from v4.3.x)
- Fixed checking permissions for users with no permissions set
- Fixed - prevent deleting manufacturers via API if they have items/models
- Fixed view if model doesn't have a manufacturer
- Fixed - added counts to location show() API method
- Fixed #5811 - non-US Characters in user export
- Fixed #6082 - don’t show expected checkin in email if none given
- Fixed #6284 - missing checkout information on Status Labels API asset endpoint
- Fixed: #6263 - missing oauth tables when using the setup quick start

 
### Documentation
- Added [Notifications Overview](https://snipe-it.readme.io/docs/notifications-overview)
- Added [Migrating Files](https://snipe-it.readme.io/docs/migration-uploads)
- Updated [Configuration](
https://snipe-it.readme.io/docs/configuration#section-optional-amazon-s3-settings) to include AWS settings

### Multi-Asset Creation

We're currently working on a way to easily create multiple assets from the Create Asset screen. This is a little tricksier than it seems, because there are both front end and backend considerations (validation, etc), but it's coming along well.

![screenflow](https://user-images.githubusercontent.com/197404/46438234-35c14f00-c712-11e8-9aff-d803f8a5df99.gif)

### Backups are Donked

I'm not actually sure how to handle this one right now, but backups will no longer work the same way with Flysystem. Need to investigate.

We're still shooting to get as many of the [v5 milestone issues](https://github.com/snipe/snipe-it/milestone/23) handled prior to release, but as always, it should be used as a roadmap guide, and some features/fixes many not make it in this version.

**Comment by thanukalpa** [comment]
Hi I'm Kalpa De Silva from Sri Lanka working as a IT specialist from Large scale apparel business. I go through your all conversations and finally I installed on premise Snipe-IT system. I would like to give some major changes to your system and we already trying to do it using our internal

**Comment by snipe** [comment]
@thanukalpa If you have feature requests you're interested in working on, please see the [contributing documentation](https://snipe-it.readme.io/docs/contributing-overview), and make sure you discuss your approach with us here via Github Issue so that we can make sure you're going down a path that will work long-term for the project. Thanks!

**Comment by lb1f** [comment]
Question, will the upgrade to version 5 from the latest stable likely be straight forward or should I look at installing the development version now and upgrade that to stable once it's released?

I know development should never be expected to be stable etc etc, but sometimes dealing with slight issues is easier than ripping it all out when it comes to upgrade time.

**Comment by snipe** [comment]
It should be pretty straightforward. The only thing that might take some shenanigans is if you decide to host your uploaded assets in AWS S3 or Rackspace separate from your Snipe-IT instance. We have a command line tool for that as well. Some directories will also be moved around a little, but the upgrade script should hopefully handle that for you without too much fuss. Hopefully. ;)

**Comment by lb1f** [comment]
Thanks, I'll start with stable and wait a bit for any upgrade issues to be resolved (if there are any).

**Comment by ichayapet** [comment]
The link above for Migrating Files doesn't work, it takes me the documentation page with 404 page not found

**Comment by snipe** [comment]
@ichayapet v5 isn't out yet.

**Comment by bprfh** [comment]
Are there any Plans to add Purchase Orders, like it was suggested in #6133?
Thanks for the great work so far!

**Comment by aaronpierce** [comment]
Is [this](https://github.com/snipe/snipe-it/commit/ff879e2018f1fac406b813d423ba7d617817b2c7) commit about altering assets location through audits only coming with v5? Or is it the newest release?

**Comment by snipe** [comment]
@aaronpierce I believe that's only on develop right now

**Comment by memtech3** [comment]
In the develop preview, the bulk audit feature doesn't update locations if assets are checked out. What would be great is if you opened an audit, scanned all of the items, and then save (to continue to work on it later) or close (done with audit, ready to review) and review items that are checked out and select what to do with them (check out to new location, ignore, set status etc), remove items from the audit, and view what was supposed to be in each room and is missing, misplaced etc

**Comment by andreasoc** [comment]
i can't wait, thanks for the great work

**Comment by snipe** [comment]
@memtech3 - please open a new issue for that so we can discuss it there. Thanks!

**Comment by snipe** [comment]
@aaronpierce v5 only, sorry. It's too difficult to keep back porting features and working on the new version as well.

**Comment by BharathKumarGajula** [comment]
Will we get SSO/ Single Sign on feature in v5 release.

**Comment by ffuentes** [comment]
And u2f? Please allow security keys as 2fa.

**Comment by snipe** [comment]
@BharathKumarGajula @ffuentes alas, SSO and u2f will not be in the v5 release.

**Comment by ffuentes** [comment]
Hi @snipe, ok I understand. Can at least be *addressed* #6567?

**Comment by navachaitanya** [comment]
When would be version 5 is available for public release, we are waiting for this release from long time.

**Comment by gilesytheking** [comment]
How about Bulk Check In feature?

**Comment by thameerakn** [comment]
Hi,

Will Maintenance Agreement/ General Agreements option included in this release? It would be great feature to have if its possible.

**Comment by itscsquared** [comment]
Is there anything more to update on this? I know the versions of 4.7 had been released but was wondering when we could expect v5.

**Comment by tvsuhail** [comment]
Hi, When we can expect stable release of v5?

**Comment by andres-baller** [comment]
Looks exciting! Can we also expect kits #6756 to make it into master for v5?

**Comment by SoXX-TheFennec** [comment]
Are you guys working on something like #5081 forV5?

**Comment by iamdeanstew** [comment]
Is V5 ever coming out? Multi add assets and printing of equipment receipts are crucial.

**Comment by JoatWiPete** [comment]
Any chance of Snipe-IT v5 getting bumped to [ Laravel 6.0 LTS ] ( https://laravel-news.com/laravel-6 ) when it releases, instead of 5.7?
I'm ignorant of what that entails but LTS support sounds nice.

**Comment by kamwai** [comment]
> Is V5 ever coming out? Multi add assets and printing of equipment receipts are crucial.

yeah, i cannot deploy this solution without this feature.

**Comment by phatuous** [comment]
I tried to look at what issues remained open, in case I could do some small part to get it live by contributing a pull request... I found five open issues on the v5 milestone, but the couple I clicked into had already been merged, so I couldn't tell if they were genuinely still open.

What can we do to help get v5 across the finish line?

**Comment by phatuous** [comment]
Ok - well we're definitely interested in the LDAP/AD piece, so that's a great fit for us to pitch in on.

how can we help with testing? we just finished setting up our own Test AD, so we've got a safe sandbox to play with.

**Comment by snipe** [comment]
@phatuous LDAP/AD login, syncing, etc. It should behave the same on both versions. *Should*.

**Comment by phatuous** [comment]
roger that - we'll get cracking on standing up a parallel v5 version of our current V4.7.5 instance, and start hammering on the LDAP/AD piece. we'll report back any issues, esp. unexpected differences (we're expecting *some* intentional differences, like syncing of Department).

**Comment by phatuous** [comment]
qq: should we be testing against dev branch or v5.0.0-beta-2 label?

**Comment by snipe** [comment]
`develop` branch please :)

**Comment by chay22** [comment]
Hello! Do you guys still need a hand to write tests? I am currently creating them [here](https://github.com/chay22/snipe-it/tree/bulk-action/tests/acceptance). I rely on ChromeDriver since phantomjs just does not work on my environment.

**Comment by timwsuqld** [comment]
@stale this issue is still relevant until v5 is released. @snipe can we make the stale bot ignore this issue somehow?

**Comment by lopezio** [comment]
Hi, seems LDAP Sync functionality is out in the wild on 5.0? #6352 brought in a lot of changes, but broke \App\Console\Commands\LdapSync as well as the sync via webui by removing \App\Models\Ldap . Copying the \App\Models\Ldap from the latest master, for now, seems to work, but I'm sure it's intended. Any pointers on what needs to be refactored?

**Comment by andreasoc** [comment]
> Hi, seems LDAP Sync functionality is out in the wild on 5.0?

it's already present

**Comment by jackvockins** [comment]
@snipe do we have an ETA on a V5 release? Can we expect to see it at some point next year?

**Comment by hixair** [comment]
Hi ! 
I just want to know if you still need help on testing ? Anything we can do to help ?

![mypart](https://www.longrangehunting.com/attachments/starship-trooper-doing-my-part-gif.148194/)

**Comment by maxlehot1234** [comment]
Any ETA on V5 @snipe

**Comment by 54656452** [comment]
Any chance that https://github.com/snipe/snipe-it/issues/5925 is going to make an appearance in V5?

**Comment by luixal** [comment]
It would be really helpful if multi-assets allows to input assets in a "comma separated" way instead of having to click.

Having a way to create multiple numerical based assets would be great too. i.e: using "MyDevice %[10-15]" to get MyDevice 10, MyDevice 11, ..., MyDevice 15 created.

**Comment by iainhallam** [comment]
v5 is pretty relevant. @snipe Can the stale bot be backed off a bit, perhaps to four or six months?

**Comment by HinchK** [comment]
(bump)
issue to track LDAP changes:

https://github.com/snipe/snipe-it/issues/7896

**Comment by nickjmv** [comment]
Any status update when the release will be?

**Comment by daletnt** [comment]
I would like to test the RFID integration, please can you let me know when this feature will be ready for testing?

**Comment by snipe** [comment]
@daletnt Can you be more specific about what you're trying to do exactly?

**Comment by snipe** [comment]
Heads up - we're shooting for an RC this week or next, with the aim to be to release v5 mid Sept. 

![its-happening](https://user-images.githubusercontent.com/197404/91263152-1c21ba00-e725-11ea-9bac-a947818bfde8.gif)

**Comment by tvsuhail** [comment]
Good to hear that it is going to be finally out...👍

**Comment by andreasoc** [comment]
top!

**Comment by snipe** [comment]
v5-beta-3.0.0 is released - https://github.com/snipe/snipe-it/releases/tag/v5.0.0-beta-3.0

<blockquote><img src="https://repository-images.githubusercontent.com/14346979/164a6580-7d79-11e9-865f-eae87593e11a" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/snipe/snipe-it/releases/tag/v5.0.0-beta-3.0">Release v5.0.0-beta-3.0 · snipe/snipe-it</a></strong></div><div>New from v5.0.0-beta-2 to v5.0.0-beta-3
IMPORTANT: This version of Snipe-IT requires PHP 7.2 or greater
Added

Accessibility features already back ported to v4.9.x
Merge user script already back po...</div></blockquote>
