### ISSUE TITLE
Importing csv File results into Exception "The 'send-welcome' option does not exist."

### ISSUE THREAD

**Issue by mwoelfer-tgm** [snipe/snipe-it#6291]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When importing any csv file, an exception is thrown that says "The 'send-welcome' option does not exist.'. 

I used the command ```php artisan snipeit:import sample-assets.csv```.

If the importing is done via the gui in the web interface, it just says "processing..." and freezes. 

**To Reproduce**
1. Set up Docker Container according to guide
2. Complete Setup
3. Access the container 
4. Type in command ```php artisan snipeit:import <any csv file>```
5. See error

**Expected behavior**
The data should be imported without error messages. 

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.5 build 3897 (gff824ec4d)
 - OS: Ubuntu 16.04.5 LTS (Xenial Xerus) Docker Image
 - Web Server: [Apache
 - PHP Version: 7.0

**Error Messages**

```
In Input.php line 150:
                                                                  
  [Symfony\Component\Console\Exception\InvalidArgumentException]  
  The "send-welcome" option does not exist.                       
                                                                  

Exception trace:
 Symfony\Component\Console\Input\Input->getOption() at /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php:276
 Illuminate\Console\Command->option() at /var/www/html/app/Console/Commands/ObjectImportCommand.php:77
 App\Console\Commands\ObjectImportCommand->fire() at n/a:n/a
 call_user_func_array() at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:539
 Illuminate\Container\Container->call() at /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php:182
 Illuminate\Console\Command->execute() at /var/www/html/vendor/symfony/console/Command/Command.php:251
 Symfony\Component\Console\Command\Command->run() at /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php:167
 Illuminate\Console\Command->run() at /var/www/html/vendor/symfony/console/Application.php:946
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /var/www/html/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122
 Illuminate\Foundation\Console\Kernel->handle() at /var/www/html/artisan:35

```

**Additional context**
- Is this a fresh install or an upgrade? 
Fresh install from Docker Image
- What OS and web server you're running Snipe-IT on
Ubuntu with Apache as given in the Docker Image
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Docker
- Include what you've done so far in the installation, and if you got any error messages along the way.
Completed the Flight Setup. I thought maybe the reason was because I didn't properly set up the mail server, but I even got that working and still can't import data.

I also tried updating the php Packages, checked if all php extension are installed and ready.

I deleted and re installed the docker containers (and the volumes) about 3 times, every time the same issues.

**Comment by snipe** [comment]
Are you pulling from the versioned docker image, or master?

**Comment by ReignSol** [comment]
I'm having the same issue
