### ISSUE TITLE
Invalid_credentials, "message": "The user credentials were incorrect."

### ISSUE THREAD

**Issue by mateuszWlazlowski** [snipe/snipe-it#6294]
Hello,
I want to get Bearer from Oauth, and when i trying to POST request to url/oauth/token i have got: 
{
    "error": "invalid_credentials",
    "message": "The user credentials were incorrect."
}

This is my request from Postman:
![screenshot from 2018-10-04 16-04-59](https://user-images.githubusercontent.com/26224661/46479660-da658e80-c7ef-11e8-9346-01bc52854ff7.png)

I have created clients:

![dsadsadas](https://user-images.githubusercontent.com/26224661/46479911-64adf280-c7f0-11e8-8c69-f5cac0107dfd.png)

Password and usernane are correct and working via WWW

**Comment by snipe** [comment]
I don't understand what you're trying to do here. You'd need to be authenticated in order to hit any of the API endpoints (otherwise how would it know who you are), so you'd need a Bearer token in order to generate from from the API.

**Comment by mateuszWlazlowski** [comment]
Yes and i generate my token by oauth client and to get Bearer code i need to post this on {url}/oauth/token and then in response I got user bearer code like on the screen:
![screenshot from 2018-10-05 11-31-49](https://user-images.githubusercontent.com/26224661/46527804-76e06d00-c892-11e8-9a65-688deb2d0f0e.png)

I solved it, the request parameter "username" isn't a snipe username, it is an email parameter from snipe account.

Thank you snipe for fast reaction.

**Comment by mateuszWlazlowski** [comment]
For everyone with this problem:
If you want to use username instead of email in this request to get Bearer code change this line in /var/www/snipeit/vendor/laravel/passport/src/Bridge/UserRepository.php

           ` $user = (new $model)->where('email', $username)->first(); `
to
            `$user = (new $model)->where('username', $username)->first();`

Now this is the 44 line of code.

![screenshot from 2018-10-05 12-29-18](https://user-images.githubusercontent.com/26224661/46530761-1a358000-c89b-11e8-9c23-f3520cf5c0a0.png)

**Comment by snipe** [comment]
### You should never, ever overwrite vendor libraries. Any changes you make will be overwritten the next time you upgrade.

I cannot possibly stress this enough.

Snipe-IT uses usernames, not email addresses (as not all users have email addresses), for all logins, so I'm not sure what you solved here.

**Comment by mateuszWlazlowski** [comment]
As I wrote before, I want to send request like in first post for Bearer code to oauth. And when i use username in 'username' parameter its returning "error": "invalid_credentials", but when i use snipe user's email its working properly

**Comment by snipe** [comment]
> I want to send request like in first post for Bearer code to oauth

But what are you trying to DO? Why are you trying to do that?

**Comment by mateuszWlazlowski** [comment]
Because I want can login on users accounts from my mobile app which use yours snipe API.

**Comment by sandertrellez** [comment]
In your user model you should a findForPassport method:
**Never, edit in vendor directory.**

    public function findForPassport($username) {
        return $this->where('username', $username)->first();
    }
