### ISSUE TITLE
Adding important LDAP fields from AD attributes.

### ISSUE THREAD

**Issue by SirajQu** [snipe/snipe-it#6295]
Hi
I would like to make suggestion to add more fields in LDAP to fetch more attributes from Active Directory,
as I have searched here for the same subject then I came to know that the more fields in LDAP the longer processing for LDAP sync which lead to memory issues.

but at least it would be great if the fields of the title and department  is added which they are very important to make to identification of the user.

**Comment by Mynty100** [comment]
Yes it would be great to pull other AD attributes. Customs ones as well as things like the description field etc.

**Comment by thanukalpa** [comment]
is this issue resolved ??

**Comment by Mynty100** [comment]
Haven't seen these features to be added. but I also haven't read all the patch notes for a bit. Be great to see more LDAP fields be able to be pulled down.

**Comment by viclou** [comment]
FD#8710 +1

**Comment by Mynty100** [comment]
Yes, we are waiting to hear from an admin about this. we want to be able to import any field or attribute via LDAP from AD. This would be so incredibly helpful.

**Comment by ruimarinho** [comment]
Yes.

**Comment by ajsy** [comment]
I need moor LDAP to fetch like (Department, Manager and Company)

**Comment by Mynty100** [comment]
Still, a very much wanted feature. Please consider this for v5 or something.
Thanking you,
Mynty.

**Comment by Mynty100** [comment]
Good morning,
Yes some extra field and custom variables is still wanted.
Thanking you,

**Comment by bigcammy** [comment]
Yes, to be able to map additional fields such as Title and Department would be great.

**Comment by bigcammy** [comment]
Yes, to be able to map additional fields such as Title and Department would be great.



Camron Smith
Systems Administrator

ACKERMAN McQUEEN
1133 N. Robinson Avenue
Oklahoma City, OK 73103 | (405) 843-7777
camron-smith@am.com | www.am.com<http://www.am.com>

[cid:A&Mc-Logo-Small_334cfd8c-afbd-4acc-85e1-5c5a36b526a6.png]

**Comment by bigcammy** [comment]
Yes, to be able to map additional fields such as Title and Department would be great.

**Comment by SirajQu** [comment]
Still would like to see some of these fields added to the LDAP

**Comment by evmimagina** [comment]
Hi,

**We need this feature too!!.** Also would be nice to be able to create locations based on AD property (AD Group, AD attribute…) instead of just OU where the user leaves.

Many thanks,

**Comment by siegfriedpicavet** [comment]
extra ldap fields mapped to snipe it would be awesome. Title, email, phone, department and manager are all ldap fields who are filled in in our active directory and it would be easy if we could use this fields in snipe-it too to filter out the people tab.
