### ISSUE TITLE
Make user to view only specific category in the assets

### ISSUE THREAD

**Issue by SirajQu** [snipe/snipe-it#6296]
Hi,
I don't know if anyone suggest same this thing, which to make the permission of the user to view and edit only specific category in the assets not all of them.

If that's possible it would be great.

**Comment by jackka** [comment]
in develop

**Comment by jackka** [comment]
yes

**Comment by SirajQu** [comment]
I really wish this feature is coming soon with the next update.

**Comment by SirajQu** [comment]
Yes, we need such a feature.

**Comment by SirajQu** [comment]
Yes

**Comment by snipe** [comment]
This feature is not actively being developed, and isn't on the short term roadmap at this time. Restricting asset visibility is only possible via Company + Full Company Support at this time, and that's unlikely to change any time soon. It's enormously complicated to build and even harder to test - and people want that restriction on department, etc etc etc. 

I'd consider a pull request, but it's not being worked on right now.

**Comment by thasleemnazeer** [comment]
+1
Please add this feature. It is very helpful.
