### ISSUE TITLE
Error with email addresses when syncing from LDAP

### ISSUE THREAD

**Issue by JuddTracy-DAS** [snipe/snipe-it#6298]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

When Synchronizing my LDAP accounts I get errors with importing related to email addresses.  It seems any email with the format "first.last@example.com" fail with the notes column stating "The email format is invalid."  Email addresses that do not have the "dot" in them seem to work fine.

I can however create a local user that has an email with an email address using that format.

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.4
 - OS: Docker
 - Web Server: Container Version
 - PHP Version: Container Version

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 69.0.3497.100

**Additional context**
- This is an initial install to test how to deploy the docker image and set it up.  I had two local accounts created and a few assets imported from spreedsheet but nothing else setup on the server.

**Comment by snipe** [comment]
That doesn't really make any sense though, as both individual save and LDAP save uses the standard email validator...

**Comment by JuddTracy-DAS** [comment]
Every time I go to sync LDAP the one account that is the format "first.last@example.com" fails saying The email format is invalid."

Is there anything you would like me to do to test this some more?

**Comment by JuddTracy-DAS** [comment]
So I figured out the issue.  The validator was not triggering on the "first.last@example.com".  The issue was that I accidentally had a space at the end of the email address.  Took a little while to spot that little mistake.  Maybe the LDAP Sync code could add a trim function to the values?
