### ISSUE TITLE
Auto-populate Default Location Value For Selected Company

### ISSUE THREAD

**Issue by rpesta** [snipe/snipe-it#6299]
**Server (please complete the following information):**
 - Snipe-IT Version v4.6.5 build 3897 (gff824ec4d)
 - OS: HOSTED
 - Web Server: HOSTED
 - PHP Version 7.1.20

**Is your feature request related to a problem? Please describe.**
When creating a new asset, you have the option to select a default location if the asset is unassigned. By default this is not populated and causes confusion with multiple companies. Also, it's another field to fill out.

**Describe the solution you'd like**
There should be an option in the Company settings to select a Default Location default setting. When a new asset is created and a Company name is selected, the Default Location should be changed automatically, or if no location is explicitly selected, it should default to the value set by the Company setting.

**Describe alternatives you've considered**
Programatically, using the API, select a default location for newly created assets, but this option might not always be applicable. Eg. If a 3rd party contractor with their own Company has assets located at a different Company.

**Comment by snipe** [comment]
I doubt we'll implement something like this. My concern is that if people aren't paying attention, the default location will be saved accidentally. In general, missing data is better than bad data, IMHO.
