### ISSUE TITLE
Crontab is working fine, but still not getting alert email

### ISSUE THREAD

**Issue by lewislai** [snipe/snipe-it#6300]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Crontab are running fine, but i can't receive any alert email.
env files, configure correctly.

![image](https://user-images.githubusercontent.com/43874896/46523336-fb91b200-c8b7-11e8-8b49-495bb87812a8.png)

If i delete  
// Send a rollup to the admin, if settings dictate
//            $recipients = collect(explode(',', $settings->alert_email))->map(function ($item, $key) {
//                return new \App\Models\Recipients\AlertRecipient($item);
//           });

I will get Alert, from log . Still cannot get the alert from email.
 
![image](https://user-images.githubusercontent.com/43874896/46523408-35fb4f00-c8b8-11e8-8030-98d44d67f03f.png)

![image](https://user-images.githubusercontent.com/43874896/46523551-a2764e00-c8b8-11e8-80cb-b6367f7c83a3.png)

**To Reproduce**

**Expected behavior**

**Screenshots**
above

**Server (please complete the following information):**
 - Snipe-IT Version  
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 4.6.5

cPanel Version | 74.0 (build 9)
Apache Version | 2.4.34
PHP Version | 5.6.37
MySQL Version | 5.6.41
Architecture | x86_64
Operating System | linux
Path to Sendmail | /usr/sbin/sendmail
Path to Perl | /usr/bin/perl
Perl Version | 5.16.3
Kernel Version | 3.10.0-714.10.2.lve1.5.12.el7.x86_64

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version 68.0.3440.106 (Official Build) (64-bit)

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

production.ERROR: exception 'ErrorException' with message 'Argument 1 passed to App\Models\Recipients\AlertRecipient::__construct() must be an instance of App\Models\Recipients\string, string given, called in /home/jwspring/public_html/jwsinv/app/Console/Commands/SendExpirationAlerts.php on line 57 and defined' in /home/jwspring/public_html/jwsinv/app/Models/Recipients/AlertRecipient.php:8

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
no
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
Fresh
- What OS and web server you're running Snipe-IT on
Linux
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
softaculous
- Include what you've done so far in the installation, and if you got any error messages along the way.
no, all smooth
- Indicate whether or not you've manually edited any data directly in the database
no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Please complete the rest of the issue template.

**Comment by lewislai** [comment]
yes , i do have.
![image](https://user-images.githubusercontent.com/43874896/46524684-30a00380-c8bc-11e8-86b6-d9ad2910dc28.png)

**Comment by jwhulette** [comment]
@snipe I believe the error is related to the type hinting in the construct of the AlertRecipient class. I don't think PHP 5 likes it. I would remove it, form __construct(string $email) to __construct($email).

**Comment by snipe** [comment]
@jwhulette Makes sense (tho it looks more like a namespacing issue than an actual typehinting issue). It's a short-term problem anyway though, since v5 will be out soon enough, and it requires PHP 7.

@lewislai - are you able to upgrade your PHP to v7?

**Comment by romannazarenko** [comment]
Same here. 

PHP Version | 7.1.22
-- | --
Laravel Version | 5.4.35
Expiring alerts sends only for licenses. Warranty alerts won't sends from Cron or from manual command

**Comment by jwhulette** [comment]
@lewislai @romannazarenko Do you get any errors when running manually? If so post them here.

**Comment by romannazarenko** [comment]
@jwhulette no, i don't see any errors

**Comment by jwhulette** [comment]
@romannazarenko What's the output when you manually run the command?

**Comment by jwhulette** [comment]
@romannazarenko Can you check your mail logs to see if the email is being sent?

**Comment by jwhulette** [comment]
@romannazarenko Can your server send emails? How does it send email, Post, Sendmail, AWS?
In your .env file do you have your email section filled out? What do you have there? Can I see it with sensitive info removed?

Also, I'm on gitter right now, might me easier, 
https://gitter.im/snipe/snipe-it?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by jwhulette** [comment]
Created PR https://github.com/snipe/snipe-it/pull/6321 to fix @romannazarenko issue.
