### ISSUE TITLE
v5 develop - Duplicate asset tags somehow being allowed

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#6301]
Leaving myself a note....

This is using the multi-asset create form (new in v5). We use model-level validation, so I'm honestly unsure how this is getting saved in the first place. It should have been rejected at the `$asset->save() level`.

The Asset Controller method to store new assets still needs a little work, like collecting the validation errors and presenting them in a way that's sane on the page, but we need to figure out why that asset was allowed to be saved in the first place. 

<img width="834" alt="screen shot 2018-10-05 at 5 52 13 am" src="https://user-images.githubusercontent.com/197404/46536607-df642580-c863-11e8-9c44-d074a9e3a1e0.png">

Ideally, we'll do a server-side validation call on the frontend to prevent asset tag collisions but we obviously can't trust client-side validation. 

I'm just not sure why that model level validation isn't firing.

**Comment by memtech3** [comment]
Isn't this fixed?

**Comment by inietov** [comment]
I have this assigned, but I haven't looked at it. As far as I know this is still an issue.

**Comment by inietov** [comment]
I have this assigned, but I haven't looked at it. As far as I know this is still an issue.

**Comment by uberbrady** [comment]
Hey @inietov I'm working on #6304 and I'm doing a lot of creates and multi-item creates so I'll be able to give you some more info as I'm testing that change.

Right now, it _does_ look like you can't create two items with the same asset tag. I'll confirm that and get back to you.

**Comment by inietov** [comment]
Thank you for your help.
