### ISSUE TITLE
v5 develop - implement the rest of the client-side validation

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#6302]
We have partial [client-side validation](http://www.formvalidator.net) working right now, but we don't have them all covered just yet. Also, this gets a little trickier with our form partials because depending on the context, some fields may or may not be required. 

I do feel like *some* client-side validation is better than none (which we currently have), so it wouldn't break my heart to launch with partial coverage, but I'd like to try to cover as many bases as we can.

Additionally, we'll need to see if we can implement it on custom fields. This could be tricksy, specifically for regexes, but we'll see.

**Comment by smb** [comment]
Maybe https://github.com/proengsoft/laravel-jsvalidation could help, no need for separate frontend + backend implementations.
