### ISSUE TITLE
v5 develop - Test/bench/optimize multi-asset create

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#6304]
It seems a little slow on my local environment when only creating a handful of assets at one time (although admittedly I did check them out on creation, so it has to send an email and send a message to slack.) I'm not particularly interested in using a queuing system, just because it adds more complexity to a system users already struggle getting up and running, but we may need to think through whether there is a better way to handle it that could be faster.

**Comment by jwhulette** [comment]
@snipe I found this, [simple queuing](https://laracasts.com/discuss/channels/laravel/free-queue-solution-for-shared-hosting/replies/140234). It could help. Let me know your thoughts, I would be willing to do a PR for it.
