### ISSUE TITLE
v5 develop - Error when running db:seeder

### ISSUE THREAD

**Issue by jwhulette** [snipe/snipe-it#6306]
An error occurs in the AssetSeeder when creating assets. The Asset model has a reference to the Settings class with is not populated so the auto_increment_assets function fails. 

Creating PR to add the Laravel helper optional on the settings variable to allow the seeding to take place.

**Comment by snipe** [comment]
Is that only on a fresh install? I seed all day long and have not run into issues. (We use the ResetDemoSettings console command on the demo itself.)

**Comment by jwhulette** [comment]
Yes, on a fresh install.

**Comment by snipe** [comment]
That makes sense - I rarely seed from a 100% empty database, so my settings table remains every time I seed. Good catch - thanks!
