### ISSUE TITLE
Bulk edit people's location doesn't move their assets

### ISSUE THREAD

**Issue by vstephanou** [snipe/snipe-it#6311]
I am trying to move several people from one location to another, using Bulk Edit. 

Each user has assets and these assets initially count to the location's asset count. Assets were checked out to the users normally.

When the Bulk edit is performed, the location of the users is updated correctly, but the Assets stay in the original location. In the Locations page I confirm that user count has changed for the target location but Assets stay unchanged.

When I do the same by just editing a single user, the assets move correctly, so it's only a matter of bulk edit, not changing the location to a user.

I reproduced the same behavior in the demo by moving two users from North Laynefort to Ambattur. Assets in Ambattur stay zero.

---------------

- [- ] I have enabled debug mode _I don't see debug mode it's a hosted installation_
- [ +] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

Snipe-IT version | v4.6.5 build 3897 (gff824ec4d)
Software License | AGPL3
PHP Version | 7.1.20
Laravel Version | 5.4.35

Desktop
OS: Mac OS High Sierra 10.14 (also on 10.13.6)
Browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)

**Comment by tymik** [comment]
i'd even say there should be boolean to indicate if assets should change location with user or not - as there are cases where user may move with assets or leave them at current location and obtain other ones at new location

**Comment by snipe** [comment]
If someone leaves them at the current location and obtains new ones at the new location, that asset should be checked in from that person and new ones checked out at the new location. The entire point of having an asset management system is maintaining that chain of custody.

**Comment by tymik** [comment]
But it could allow to check in automatically when a person is moved, right?

Case:
Employee comes today with assets, is leaving the office and will be starting the other office tomorrow (or in few days) - i can move the employee to that location at this moment and the assets can automatically be checked out, as I authorize it by moving the employee to other location. It doesn't break the chain then and simplifies the usage.
