### ISSUE TITLE
404 When Importing assets from the web

### ISSUE THREAD

**Issue by ellisgeek** [snipe/snipe-it#6313]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

## **Describe the bug**
When Importing assets after setting all the fields to match the headers and clicking import the import says it is successful and then redirects to `https://inventory.domain/undefined` which results in a 404.

As a possible note the CSV i am using is an asset report from another installation.

## **To Reproduce**
1. Upload a CSV to import 
2. Set fields to match headers.
3. Click Import
4. Green Bootstrap alert flashes and then you are redirected to `https://inventory.domain/undefined` which results in a 404.

## **Expected behavior**
Assets should be imported and you should be redirected to the assets list  (i think)

## **Screenshots**
![snipe](https://user-images.githubusercontent.com/556100/46624213-b8bd1d80-caf5-11e8-9ad7-ef871c19629b.PNG)

## **Server (please complete the following information):**
 - Snipe-IT Version: v4.6.5 - build 3907 (master)
 - OS: Ubuntu 16.04
 - Web Server: Nginx  nginx/1.10.3 (Ubuntu) / HAProxy 1.6.3
 - PHP Version: 7.0.22-0ubuntu0.16.04.1

## **Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 69.0.3497.100 (Official Build) (64-bit)

## **Smartphone (please complete the following information):**
N/A

### Browser Console
None

### DEBUG BAR
```
/media/www/var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/RouteCollection.php#179
Symfony\Component\HttpKernel\Exception\NotFoundHttpException
            return $this->getRouteForMethods($request, $others);
        }

        throw new NotFoundHttpException;
    }

    /**
```

### Larvel.log
None

### PHP / Nginx
None

**Additional context**
- **Is this a fresh install or an upgrade?** Upgrade
- **What OS and web server you're running Snipe-IT on** Ubuntu 16.04 /Nginx
- **What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)** Manual Install / Git Pull
- **Include what you've done so far in the installation, and if you got any error messages along the way.** Add Models and Manufacturers, Setup LDAP, Setup HTTPS.
- **Indicate whether or not you've manually edited any data directly in the database** No

**Comment by EarlRamirez** [comment]
@ellisgeek did you clear your cache, etc. after you did a _git pull_?

**Comment by ellisgeek** [comment]
Yes, I did an `artisan cache:clear` and `artisan config:clear` after the update.

**Comment by EarlRamirez** [comment]
Are you seeing the same behaviour if you create an asset?

**Comment by ellisgeek** [comment]
No,

Creating assets works just fine. it's only on import. 

I'm also having issues with the CLI importer #6190

**Comment by ctorres4745** [comment]
Same here. Any updates?

**Comment by ReignSol** [comment]
Yeah, I think so.

**Comment by yosiasz** [comment]
Issue happens elsewhere even when using 

```
php artisan snipeit:import sample.csv
```

![image](https://user-images.githubusercontent.com/900951/99292300-dfca9b00-27f5-11eb-91c0-243895a789bc.png)

**Comment by IanSimon82** [comment]
This is an issue for me still in version 5.4.3. Everthing I have is very simmilar to what has been posted previously. If someone has figured this out, please let me know!

**Comment by isimon1** [comment]
Hello. I have solved this issue! 
Check your env file, under Database Settings, your DB Dump Path should be as follows:
DB_DUMP_PATH='C:\Program Files\MariaDB 10.5\bin'

Mine was changed for some reason after I had set this correctly in the past.
