### ISSUE TITLE
GUI not showing Users / Models but they are present in the DB.

### ISSUE THREAD

**Issue by droneaware** [snipe/snipe-it#6315]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Database shows models and users but does not show any in the GUI.

**Expected behavior**
I expect to see the users and models I have in the Database but none are displayed. Trying to "create a new user" says that usernames must be unique.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser chrome
 - Version 69.0.x

**Additional context**
- Is this a fresh install or an upgrade? 
  Fresh Install on AWS with a restore from an existing version done via SQL command line

- What OS and web server you're running Snipe-IT on
  Ubuntu & Apache2

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  Preconfigured AWS image

- Indicate whether or not you've manually edited any data directly in the database
  Not data but have added required columns

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Please provide information from your app logs.

**Comment by droneaware** [comment]
Issue on my end
