### ISSUE TITLE
Creating new asset shows no errors but does not save in the DB....

### ISSUE THREAD

**Issue by droneaware** [snipe/snipe-it#6316]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Click "create new asset" and enter all required fields, Click save, page refreshes to "default" state w/ no error messages displayed. Record is not created in DB.

**To Reproduce**
1. Go to lit all assets
2. Click on create new
3. Fill in all fields
4. Click save
5. No error message
6. No new entry in DB

**Expected behavior**
After clicking submit I expect to see the error or success message appear in the GUI.

**Server (please complete the following information):**
 - OS: UBUNTU
 - Web Server: apache2

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 69.0.x

**Error Messages**
N/A

**Additional context**
- Is this a fresh install or an upgrade? 
  Fresh Install
- What OS and web server you're running Snipe-IT on
  Ubuntu / Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
  AWS image
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
  no data but had to add columns as old backup didn't contain all pertinent data

**Comment by snipe** [comment]
When you click save, what actually happens though? What version of Snipe-IT are you running? Also, I'm not sure what you mean by "AWS Image" as your installation type.

> no data but had to add columns as old backup didn't contain all pertinent data

Can you explain that please? You should NEVER have to add columns manually.

Additionally, please provide us the information from your app log.
