### ISSUE TITLE
AD LDAP Sync Location based on AD Group Membership.

### ISSUE THREAD

**Issue by Mercwri** [snipe/snipe-it#6319]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.4
 - OS: CentOS
 - Web Server: Apache
 - PHP Version 7.1.21

**Is your feature request related to a problem? Please describe.**
AD Groups are often used over OUs for sorting AD User's by Location

**Describe the solution you'd like**
The option to use either an LDAP filter or AD Group Membership search to assign user's to Locations.

**Comment by michael-misiaszek** [comment]
I have found a way to get users of a specific group. I have added all my users and groups to a single group and imported them that way. Here is the example query:

&(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(memberOf:1.2.840.113556.1.4.1941:=CN=EveryoneGroup,CN=Users,DC=domain,DC=com)

Explanation:

**(All User Objects)**
sAMAccountType=805306368 

**(Filters out disabled accounts)**
userAccountControl:1.2.840.113556.1.4.803:=2 

**(Search this group and nested groups)**
memberOf:1.2.840.113556.1.4.1941:=CN=EveryoneGroup,CN=Users,DC=domain,DC=com 

The link below helps a bunch when developing your own query.
**Syntax Filters:** https://social.technet.microsoft.com/wiki/contents/articles/5392.active-directory-ldap-syntax-filters.aspx?Sort=MostRecent

You can test your queries in ADUC. Expand the ADUC and right click Saved Queries to create a new one. Give it a name and query root (I used the root of my domain). Hit Define query and select custom search from the drop down menu. Paste in your query and test it out.

Hope this helps.

**Comment by Mercwri** [comment]
Is that just for Syncing LDAP Users in general?

My issue is that when I LDAP Sync it wants to sort users into Locations based on OUs only. I have a large subset of users that are not in a location based OU but are associated to a location (in AD) via a Group Membership. Manually adjusting once after the inital import wouldn't be the worst thing in the world but then it re-sorts them each LDAP Sync.

**Comment by MSTigers** [comment]
Duplicate of #3486
