### ISSUE TITLE
Suggestion:  Usability, Organization

### ISSUE THREAD

**Issue by dbierspb** [snipe/snipe-it#632]
It may be best to have this available on all pages (assets, accessories, licenses, etc) as well as have a straight up "Select what columns to show".  Tracmor does this and it's great for getting a good view of everything.

![Tracmor Selection](http://iaas.me/screenshots/2015-03-10_0943.png)

Another issue I run into is being unable to resize each column so I end up with taller rows due to lines being broken (second arrow from left).  Not to mention that if I want to bulk update, I cannot "select all" using the header bar to the entire table (first arrow on the left):

![Current Issues/Suggestions](http://iaas.me/screenshots/2015-03-10_0945_001.png)

**Comment by Gabisonfire** [comment]
I could really use that as well!

**Comment by madd15** [comment]
Suggestion no. 1
![columns](http://i.imgur.com/gbbXOhl.png)

**Comment by dbierspb** [comment]
Niceeeeeee @madd15 -- Very sexy, indeed! :)

**Comment by madd15** [comment]
Latest dev now also has check all
