### ISSUE TITLE
Search should yield umlauts as well when typing ae, oe and ue

### ISSUE THREAD

**Issue by 3ter** [snipe/snipe-it#6322]
**Server**
 - Snipe-IT Version: 4.6.5
 - OS: Windows Server 1607
 - Web Server: IIS
 - PHP Version: 7.2

**Is your feature request related to a problem? Please describe.**
When typing without umlauts I can't search for German usernames containing them.

**Describe the solution you'd like**
I want to have ae, oe and ue entered in the search bar also give results for ä, ö, ü.
e.g. Roehrbein gets the surname Röhrbein

**Describe alternatives you've considered**
Switching between input methods or searching only for part of the names are workarounds.

**Comment by viclou** [comment]
@3ter I believe this ticket is related https://github.com/snipe/snipe-it/issues/5025
