### ISSUE TITLE
Importing stuck at "Processing" after updating to version 4.6.5

### ISSUE THREAD

**Issue by SirajQu** [snipe/snipe-it#6325]
**Expected behavior**
Import CSV, process CSV, match fields, import success.

**Screenshots**
<a href="https://www.sirajgraphy.com/Images-Sharing/Image-Share/n-BxQfNf/i-N3R82nV/A"><img src="https://photos.smugmug.com/photos/i-N3R82nV/0/cbc61c42/L/i-N3R82nV-L.jpg" alt=""></a>

**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.5
 - OS: [Ubuntu]: 16.04.1
 - Web Server: [Apache v2.4.18]
 - PHP Version: 7.0.32

**Actual Behavior**
Importing through GUI is stuck at "Processing"
although it was working fine before updating the version of Snipe-IT

**Additional context**
- Is this a fresh install or an upgrade? 
It's been upgraded from v4.6.3 to 4.6.5

Inside the file "config/version.php" after upgrading "php upgrade.php"

> <?php
?php
return array (
  'app_version' => 'v4.6.5',
  'full_app_version' => 'v4.6.5 - build 3915-gc7596e774',
  'build_version' => '3915',
  'prerelease_version' => '',
  'hash_version' => 'gc7596e774',
  'full_hash' => 'v4.6.5-13-gc7596e774',
  'branch' => 'master',
);

**Comment by EarlRamirez** [comment]
Can you enable debugging and share the logs with us?

**Comment by SirajQu** [comment]
> Can you enable debugging and share the logs with us?

Thank you for replying, now it works when I remove the header field (Full Name)
which supposed to checkout the assets for the users, but it didn't work with it.

I would be grateful if you could help me with that and here is the logs of the debugging:

`
[2018-10-13 10:02:04] production.ERROR: ErrorException: Undefined index: manager_id in /var/www/snipeit/app/Importer/Importer.php:311#8 /var/www/snipeit/app/Importer/Importer.php(136): Illuminate\Support\Facades\Facade::__callStatic('transaction', Array)
#9 /var/www/snipeit/app/Http/Requests/ItemImportRequest.php(58): App\Importer\Importer->import()
#10 /var/www/snipeit/app/Http/Controllers/Api/ImportController.php(125): App\Http\Requests\ItemImportRequest->import(Object(App\Models\Import))
#11 [internal function]: App\Http\Controllers\Api\ImportController->process(Object(App\Http\Requests\ItemImportRequest), '54')
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('process', Array)
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\ImportController), 'process')
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#16 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(572): Illuminate\Routing\Route->run()
#17 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#20 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#23 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#24 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#25 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#26 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#27 /var/www/snipeit/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Rout`
