### ISSUE TITLE
Label settings: user defined presets

### ISSUE THREAD

**Issue by vstephanou** [snipe/snipe-it#6326]
Hello,

I was wondering if it would be doable to have the ability to save all the label settings (size, margins etc) as presets, in order to accomodate different kinds of labels for different assets. For example we could have big labels for laptops and small labels with less info for mobile phones or other.

Does anybody else find this useful?

**Comment by ajamali1** [comment]
**+1 it's useful**, especially when having two or more printers & tow or more users with create data permissions and they located in different sections/departments

**Comment by ajsy** [comment]
Hi,

I did it , and it's working great, now I have two label settings, labels and custom labels for two different label size.

![1](https://user-images.githubusercontent.com/35658596/47545762-a82ee480-d8f6-11e8-894b-3ec58f3449c1.jpg)


**Default Label specifications** 

![2](https://user-images.githubusercontent.com/35658596/47545769-b11fb600-d8f6-11e8-9c0b-094dde60d538.jpg)


**Custom Label specifications** 

![3](https://user-images.githubusercontent.com/35658596/47545774-b4b33d00-d8f6-11e8-819e-a5173a419c00.jpg)


![4](https://user-images.githubusercontent.com/35658596/47545780-ba108780-d8f6-11e8-831d-e1b12cb2bbcc.jpg)

**Comment by vstephanou** [comment]
I would still like to see this as a feature, having to change all the
settings just to print on another size label is kind of a trivial and
boring task.

Thank you
