### ISSUE TITLE
Feature Request: Keeping track of SIM Cards, Mobile Phones, and Mobile Phone Numbers

### ISSUE THREAD

**Issue by phantomofrussia** [snipe/snipe-it#633]
All three of these can be changed to a person assigned to them depending on what happened to one or the other. 
For example I have a SIM Card 123456 assigned to Mobile Phone Number: 202.123.4567 attached to Mobile Phone IMEI number: 0987665. My phone breaks and I take the SIM card out of the phone and put it into another phone. Now my SIM Card, and Mobile Phone Number stay the same but the Mobile Phone IMEI number has changed. 
Another instance would be: My company is upgrading phones but keeping the numbers. The SIM Card and Mobile Phone IMEI number is changing but the Mobile Phone Number is not. I thought about making all three of these into assets but I was wondering if a better way could be setup for keeping track of this. 

I was thinking of doing it this way: assigning a SIM Card to a Mobile Phone number and assigning the Mobile Phone number to the Mobile Phone. The Mobile Phone is considered the asset in this instance and the SIM Card and Mobile Phone Number are some kind of accessories. Each SIM card has a unique SSN number though so they can't just be grouped together. 

Hopefully you guys are able to follow my train of thought here...
Phantomofrussia

**Comment by aglasson** [comment]
We associate a phone number with a SIM by using the notes field but not a phone. Seeing as that is fixed unless porting take place. We have both the SIM and the Phone as assets.
Once you have checked out both assets to a user you can always check back in the phone and give them a different one while they retain their SIM (number). Or if the SIM is ported you just delete the old one as the SIM is now dead and add the mobile number to the new SIM asset notes.
It works quite well and haven't found a need to do it any differently so far.

We are using the SIM number as the asset as we don't want to waste asset tags on SIM's and it means the identifying number on the SIM itself is easily identifiable in the database.

Just my 2c.

SimCard Asset:
![simcards](https://cloud.githubusercontent.com/assets/11340849/6700947/7745f7fe-cd61-11e4-8f81-18ec7e7f9c89.png)

PhoneAsset:
![phones](https://cloud.githubusercontent.com/assets/11340849/6700950/7ac57c1a-cd61-11e4-88f8-3abfd76bd9f4.png)

**Comment by phantomofrussia** [comment]
@aglasson Thanks for showing me how your company has it configured. That helped a lot and I will use it like that as well.
