### ISSUE TITLE
Setting up the LDAP-Sync but I don't know how to configrue the LDAP-Filter

### ISSUE THREAD

**Issue by PascalTr** [snipe/snipe-it#6332]
#### Expected Behavior (or desired behavior if a feature request)

Hello everyone,

I want to configure SnipeIT to import users only from one specific OU but I don't know how to setup the Base Bind DN and the LDAP Filter for this specific thing.

I want to get the users from this patch: DC=de,DC=OUR_DOMAIN,OU=Location,OU=Users,OU=EDV.

I already tried the following LDAP-Filters:
&(memberOf=*CN=EDV*)
&(cn=*,OU=Location,OU=Users,OU=EDV)
&(OU=Location,OU=Users,OU=EDV)

And i already tried to use the LDAP-Filter &(cn=*) with the Base Bind DN configured to the before mentioned path.
But when I try to sync the users through the web interface it won't show any of these users.
The Test LDAP Login also doesn't work for any of these users.

When I use the Base Bind DN "DC=de,DC=OUR_DOMAIN" and the LDAP Filter "&(cn=*)" its correctly syncing every entry that exists.

Can anybody tell me how I have to setup the LDAP Filter?

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
* Upgrade
- Version of Snipe-IT you're running
* v4.6.3
- Version of PHP you're running
* v7.0.9
- Version of MySQL/MariaDB you're running
* 5.7.17 MySQL Community Server
- What OS and web server you're running Snipe-IT on
* Windows Server 2012 R2 / Microsoft-IIS 8.5
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
* manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by ThomasDE91** [comment]
Hi,

so your base bind could be the "Main" Folder where you put your Users
CN=Users,DC=some,DC=domain,DC=sub,DC=com

To get all users  that are member of CN snipe, this is my setup, this would be the correct filter
&(objectCategory=user)(memberOf=CN=snipe,CN=Users,DC=my,DC=domain,DC=company,DC=com) You should be able to replace my values with yours.
It seems to me that you forgot &(objectCategory=user) in your Filter String so it did not return anything.

Let me know if this helps you.

**Comment by geeker21** [comment]
I am running into something similar, no matter what i have in the base bind or filter I receive "Login Failed. username  did not successfully bind to LDAP. I can do a successful LDAP Sync though.

I am using the following settings:
Username Field: samaccountname
Last Name: sn
LDAP Authentication query: sAMAccountName=
