### ISSUE TITLE
Snipe-IT by Docker: no start after server reboot

### ISSUE THREAD

**Issue by DZAUKER** [snipe/snipe-it#6336]
#### Expected Behavior (or desired behavior if a feature request)

Expected Behavior: Snipe-IT working after server reboot

-----

#### Actual Behavior

Snipe-IT doesn't respond after a server reboot.
Unable to reach the site.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install
- Version of Snipe-IT you're running: v4.6.5 build 3915 (gc7596e774)
- Version of PHP you're running: 7.0.32-0ubuntu0.16.04.1
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on: Turnkey LAMP Ubuntu / Apache 2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Docker

**Comment by EarlRamirez** [comment]
@DZAUKER are the containers running and car you able to access them?
