### ISSUE TITLE
Admin profile across multi-company

### ISSUE THREAD

**Issue by ffuentes** [snipe/snipe-it#6337]
**Server (please complete the following information):**
 - Snipe-IT Version: **4.6.5**
 - OS: **CentOS7**
 - Web Server: **Apache + nginx proxy (Letsencrypt)**
 - PHP Version: **7.1.15**

**Is your feature request related to a problem? Please describe.**
I would like to have Admin profiles across multi-company. With the **full multi-company support** enabled, the users (including admins) assigned to companies are restricted to the company data only. 
That's good for normal users. but I have an employee that is a admin for 2 companies.

**Describe the solution you'd like**
Asign some Admin users to 2 o more companies.

**Comment by EarlRamirez** [comment]
@ffuentes in essence you are looking for a global admin or are you looking for something more granular, where you can have admin1 assigned to  company_a and company_b and admin2 assign to company_c and company_d? If not you can give these users global permission, as this will give them access across companies.

**Comment by jackka** [comment]
I have the similar difficulties with sharing companies between people.
I use the “company” as a “cost center” with mode “Full Company Support” ( with local "company" -> "cost center" lang fix ), it gives support for the restrictions and etc. I know this is a perversion, but it is most adequate way to have "cost center" notion in our company for now.

So I need the same Feature - that is named:
         "One person belongs more than one company".

As far as I understand, this function requires new table for binding ( user_id <-> company_id )

**Comment by ffuentes** [comment]
> @ffuentes in essence you are looking for a global admin or are you looking for something more granular, where you can have admin1 assigned to company_a and company_b and admin2 assign to company_c and company_d? If not you can give these users global permission, as this will give them access across companies.


My apologies for the late answer, it was a busy month the last one.

Yes, I'm looking for a more granular control. Now I have a new employee who is starting with Snipe-IT. I created his account and with that he got access to every Assets that is registered. I prefer give partial access by company, and not full access. In that case he will manage the Assets for the Company A, and then after evaluation I can promote him to Company B, so he will be Administrator for both Companies.

**Comment by jackka** [comment]
@ffuentes I've done some development that makes this wishes reality but it works in semi manual mode.
When I'll finish this development I'll trying to publish it here, of course.
In short words I've created table for manage relation between companies and users via artisan and have coded restriction in accordance to this table for displaying assets.

**Comment by ffuentes** [comment]
Hi @jackka great news! Hope I can test it soon.

Let me know when it's ready. I'll try to spin a new VM for testing it.

**Comment by jackka** [comment]
Ок.

**Comment by jackka** [comment]
In developement

**Comment by alasham** [comment]
Yes
