### ISSUE TITLE
Install.sh not working

### ISSUE THREAD

**Issue by memtech3** [snipe/snipe-it#6339]
**Describe the bug**
When using the install.sh script, going to the server just sends you to the apache default page

**To Reproduce**
Attempt to use the install.sh script

**Expected behavior**
Going to the snipeit setup page

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4
 - OS: [Ubuntu 18, Kubuntu]
 - Web Server: [Apache]

**Comment by EarlRamirez** [comment]
The fix for this is currently in the dev branch, you can delete the default page that starts with 000 and rename the snipeit config by putting 000 in front.

**Comment by memtech3** [comment]
where is this file located

**Comment by memtech3** [comment]
Thanks Earl, that fixed everything
