### ISSUE TITLE
License seats not shown, offset is cached?!

### ISSUE THREAD

**Issue by uknzaeinozpas** [snipe/snipe-it#6341]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Snipe-IT remembers the page (offset) of license seats you last visited, if a license with less seats is visited the page won't show any seats.

**To Reproduce**
1. Go to a license with more than 25 seats
2. Click on the second page of the license seats
3. Go to a license with less than 25 seats
4. No seats are shown: "No matching records found"

**Expected behavior**
Seats should be visible

**Screenshots**
![2018-10-18 11_25_58-view license__snipe-it asset management](https://user-images.githubusercontent.com/22473767/47144982-f88bbe00-d2c8-11e8-81ab-c5b644a61f81.png)

**Server:**
 - Snipe-IT Version v4.6.5 - build 3915
 - OS: Windows 2008r2
 - Web Server: Apache
 - PHP 5.x

**Desktop:**
 - OS: OSX / Windows
 - Browser: Chrome / Firefox
 - Version lastest

**Error Messages**
- [x] Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- If a stacktrace is provided in the error, include that too.
```
    12. \app\Http\Controllers\Api\LicensesController.php:235
    32. \app\Http\Middleware\CheckForDebug.php:25
    35. \app\Http\Middleware\CheckForSetup.php:27
    38. \vendor\fideloper\proxy\src\TrustProxies.php:56
    41. \app\Http\Middleware\NosniffGuard.php:17
    44. \app\Http\Middleware\ContentSecurityPolicyHeader.php:18
    47. \app\Http\Middleware\ReferrerPolicyHeader.php:17
    50. \app\Http\Middleware\XssProtectHeader.php:18
    53. \app\Http\Middleware\FrameGuard.php:17
    68. \public\index.php:59 
```

**Additional context**
- Is this a fresh install or an upgrade? 
It's an upgrade

**Comment by snipe** [comment]
I need a complete stack trace here - that's only a partial.

**Comment by uknzaeinozpas** [comment]
Sorry, that's everything I got:
![2018-10-18 11_25_58-view license__snipe-it asset management](https://user-images.githubusercontent.com/22473767/47221634-3c5bf180-d3b5-11e8-9841-7dc5811efc91.png)

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/whoops#section-tailing-a-log-file-on-linuxosx

**Comment by uknzaeinozpas** [comment]
Yes, no, sorry that's everything I got. Logs are completely empty. Can I increase the logging level over the normal debug setting?

**Comment by snipe** [comment]
You can do that via the .env, but an fatal error like that would show in the logs regardless of your settings. Check and make sure the log file is writable by the webserver.

**Comment by uknzaeinozpas** [comment]
I don' think that it is logged as error, there is probably something wrong with the calculation of the offset value.
Can you supply info about how to increase the verbosity of the logging, google is dead silent about it and setting "APP_DEBUG=true" isn't sufficient.

**Comment by snipe** [comment]
> I don' think that it is logged as error,

I'm not sure how it wouldn't be. Results either exist or they don't, and if they don't, it's an error. 

> Can you supply info about how to increase the verbosity of the logging
Add `APP_LOG_LEVEL` to your `.env`

https://github.com/snipe/snipe-it/blob/master/config/app.php#L167

**Comment by snipe** [comment]
> The only thing that I can say is, that this request returns a wrong value:

That's not necessarily a wrong value. The number of rows to return (in addition to ordering, etc) is stored in a browser cookie so that you don't have to select it each time. That said, 75 > 12, so it should still be returning results. 

Hav you tried clearing your browser cache?

**Comment by snipe** [comment]
Interestingly, in the[ bootstrap tables documentation](http://bootstrap-table.wenzhixin.net.cn/documentation/), it shows that passable as a `data-` parameter, but when I test locally, it doesn't seem to have any effect. :-/

<img width="851" alt="screen shot 2018-10-31 at 7 42 23 pm" src="https://user-images.githubusercontent.com/197404/47829509-1d5e4780-dd45-11e8-94c8-dd9a0873b968.png">

**Comment by uknzaeinozpas** [comment]
> Can you try going to a different license page (one with more than 25 seats) and navigating back to page one on that detail view?

Yes, this will update the cookie `licenses.show.bs.table.pageNumber` to the last visited page count/offset and the seats are visible again

> Have you tried clearing your browser cache?

Clearing the cache does not help but clearing the cookies does.

**Comment by snipe** [comment]
@inietov can you bang this out on develop real quick? Let me know in slack if you need more details.

**Comment by uknzaeinozpas** [comment]
> Thanks for your help in troubleshooting this.

@snipe Thank you, you are helping me ;)

**Comment by uknzaeinozpas** [comment]
@inietov I've successfully tested your fix , thx a lot!
