### ISSUE TITLE
Items listed in /etc/cron.* are not executing on Docker container

### ISSUE THREAD

**Issue by delize** [snipe/snipe-it#6344]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
On Docker image, Items placed in /etc/cron.hourly are not executing. 

**To Reproduce**
1. Deploy Docker Image `v4.6.4 - build 3881 (master)`
2. Place shell script with 744 permissions 

In our case, we have two shell scripts (LDAP Import):
```
root@95214e6fb2d0:/etc/cron.hourly# cat ldap_import.sh
#!/bin/sh
cd /var/www/html/
php artisan snipeit:ldap-sync -vvv
```

and an asset import  script (can't show it unfortunately, but, it is similar to the above). Both files have permissions sets of
`-rwxr--r--  1 root root`

3. Wait...
4. scripts in cron.hourly do not execute (and in our case the assets are not importing nor do we have automatic LDAP user import)

**Expected behavior**
Scripts should execute, and both scripts should add new assets and users to SnipeIT.

If I execute the shell scripts in bash from the appropriate folder, the scripts exit cleanly and the tasks are performed.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
`v4.6.4 - build 3881 (master)`
 - OS: [e.g. Ubuntu, CentOS]
```
cat /etc/issue
Ubuntu 16.04.5 LTS
```
 - Web Server: [e.g. Apache, IIS]
```
dpkg -l | grep -i apache
ii  apache2                       2.4.18-2ubuntu3.9                     amd64        Apache HTTP Server
ii  apache2-bin                   2.4.18-2ubuntu3.9                     amd64        Apache HTTP Server (modules and other binary files)
ii  apache2-data                  2.4.18-2ubuntu3.9                     all          Apache HTTP Server (common files)
ii  apache2-utils                 2.4.18-2ubuntu3.9                     amd64        Apache HTTP Server (utility programs for web servers)
ii  libapache2-mod-php7.0         7.0.30-0ubuntu0.16.04.1               amd64        server-side, HTML-embedded scripting language (Apache 2 modul
```
 - PHP Version
```
dpkg -l | grep -i php
ii  libapache2-mod-php7.0         7.0.30-0ubuntu0.16.04.1               amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  php-common                    1:35ubuntu6.1                         all          Common files for PHP packages
ii  php7.0-bcmath                 7.0.30-0ubuntu0.16.04.1               amd64        Bcmath module for PHP
ii  php7.0-cli                    7.0.30-0ubuntu0.16.04.1               amd64        command-line interpreter for the PHP scripting language
ii  php7.0-common                 7.0.30-0ubuntu0.16.04.1               amd64        documentation, examples and common module for PHP
ii  php7.0-curl                   7.0.30-0ubuntu0.16.04.1               amd64        CURL module for PHP
ii  php7.0-gd                     7.0.30-0ubuntu0.16.04.1               amd64        GD module for PHP
ii  php7.0-json                   7.0.30-0ubuntu0.16.04.1               amd64        JSON module for PHP
ii  php7.0-ldap                   7.0.30-0ubuntu0.16.04.1               amd64        LDAP module for PHP
ii  php7.0-mbstring               7.0.30-0ubuntu0.16.04.1               amd64        MBSTRING module for PHP
ii  php7.0-mcrypt                 7.0.30-0ubuntu0.16.04.1               amd64        libmcrypt module for PHP
ii  php7.0-mysql                  7.0.30-0ubuntu0.16.04.1               amd64        MySQL module for PHP
ii  php7.0-opcache                7.0.30-0ubuntu0.16.04.1               amd64        Zend OpCache module for PHP
ii  php7.0-readline               7.0.30-0ubuntu0.16.04.1               amd64        readline module for PHP
ii  php7.0-xml                    7.0.30-0ubuntu0.16.04.1               amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ii  php7.0-zip                    7.0.30-0ubuntu0.16.04.1               amd64        Zip module for PHP
``` 

**Desktop (please complete the following information):**
`macOS 10.13.6`
`Chrome`
`69`

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
`N/A`
- If a stacktrace is provided in the error, include that too.
`N/A`
- Any errors that appear in your browser's error console.
`N/A`
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
`N/A
- Include any additional information you can find in `storage/logs` and your webserver's logs.
```
ls -al /var/www/html/storage/logs/
total 12
drwxr-xr-x  2 docker root 4096 Aug 28 18:54 .
drwxr-xr-x 14 docker root 4096 Sep 26 22:04 ..
-rwxr-xr-x  1 docker root   14 Aug 28 18:54 .gitignore
```
No relevant system logs in docker container (since no syslog).

Cron is installed:
```
dpkg -l | grep -i cron
ii  cron                          3.0pl1-128ubuntu2                     amd64        process scheduling daemon
```

**Comment by EarlRamirez** [comment]
does cron get executed if you use the /etc/crontab or create a user cron job?

**Comment by delize** [comment]
If I run what is in crontab:

```
root@95214e6fb2d0:/var/www/html# cd / && run-parts --report /etc/cron.hourly
/etc/cron.hourly/asset_automation:
======= Importing Items from /assetmanagement/assetrecord_10222018.csv =========
All Items imported successfully!

root@95214e6fb2d0:/#
```

**Comment by delize** [comment]
Bump, let me know if you need any further information on my end.

**Comment by snipe** [comment]
Are you using the latest version? The PR was merged and was released in 4.6.5

**Comment by delize** [comment]
We have not tested 4.6.5 as when looking through the release notes this was not mentioned in a FIX/ADD/IMPROVE. There was no indication that this would have been fixed.

**Comment by snipe** [comment]
@delize That's my bad - I try my best to cover everything, but if the PR isn't phrased with a fix, sometimes I miss them (and IIRC, the patch was made to develop, so I had to pull it forward into the master branch for release). 

We always try to make sure PR is correctly linked to [the issue](https://github.com/snipe/snipe-it/issues/5502#ref-pullrequest-334334571), but we're also human. In the future though, you can always look at the linked PR and check the tagged releases to see if the changes are there - or ask in the original thread if it's been formally released yet.

At any rate, you may want to hold off for an hour or so - we're about to release 4.6.6 today. It's only a bug fix release, but may as well pick up those changes too, right?

**Comment by snipe** [comment]
v4.6.6 is now out, if you're interested in giving it a try

**Comment by delize** [comment]
Trying to push 4.6.6 right now in our testing/production env, so will let you know soon what our outcome is.

**Comment by delize** [comment]
Unfortunately, with the upgrade to v4.6.6 I am still seeing the same issue. But I need to investigate a bit further, it is more than likely something I am doing, but, I just want to be 100% sure.

**Comment by delize** [comment]
I am still experiencing the problem. If I run run-parts under /etc/cron.hourly I experience the output, but cron is still not automatically executing the shell scripts within the /etc/cron.hourly folder.

**Comment by delize** [comment]
We had a purchase that occurred yesterday, where our data manipulation tool ran and outputted the correct csv file. 

However, there was no update in the dashboard for any newly added items today. So I logged into the server and exec'ed into the docker container:
```
root@45758d2df8cd:/var/www/html# run-parts -vv --report /etc/cron.hourly/
run-parts: executing /etc/cron.hourly//asset_automation_import_cdw
/etc/cron.hourly//asset_automation_import_cdw: --report --list /etc/cron.hourly/
======= Importing Items from /te/assetmanagement/assetrecord_11282018.csv =========
A matching category: Notebook/Mobile Devices already exists
A matching Company COMPANY already exists
Location SAN FRANCISCO already exists
Manufacturer Apple Notebook Systems (APN) already exists
A matching Status Ready to Deploy already exists
Supplier CDW already exists
Insufficient user data provided (Full name is required)- skipping user creation, just adding asset
Custom Field Invoice Number: INVOICENUMBER
Custom Field Customer PO: PONUMBER
Custom Field Purchased By: LASTNAME FIRSTNAME
No Matching Asset, Creating a new one
A matching model already exists, returning it.
Asset APPLE MBP 13.3 SIL 2.5 16GB 512GB (4967514) with serial number  was created

 1/5 [▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░░]  20% < 1 sec------------- Action Summary ----------------
A matching category: Notebook/Mobile Devices already exists
A matching Company COMPANY already exists
Location SAN FRANCISCO already exists
Manufacturer Apple Notebook Systems (APN) already exists
A matching Status Ready to Deploy already exists
Supplier CDW already exists
Insufficient user data provided (Full name is required)- skipping user creation, just adding asset
Custom Field Invoice Number: INVOICENUMBER
Custom Field Customer PO: PONUMBER
Custom Field Purchased By: LASTNAME FIRSTNAME
No Matching Asset, Creating a new one
A matching model already exists, returning it.
Asset APPLE MBP 13.3 SIL 2.5 16GB 512GB (4967514) with serial number  was created

 2/5 [▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░]  40% < 1 sec------------- Action Summary ----------------
A matching category: Notebook/Mobile Devices already exists
A matching Company COMPANY already exists
Location SAN FRANCISCO already exists
Manufacturer Apple Notebook Systems (APN) already exists
A matching Status Ready to Deploy already exists
Supplier CDW already exists
Insufficient user data provided (Full name is required)- skipping user creation, just adding asset
Custom Field Invoice Number: INVOICENUMBER
Custom Field Customer PO: PONUMBER
Custom Field Purchased By: LASTNAME FIRSTNAME
No Matching Asset, Creating a new one
A matching model already exists, returning it.
Asset APPLE MBP 13.3 SIL 2.5 16GB 512GB (4967514) with serial number  was created

 3/5 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░]  60% < 1 sec------------- Action Summary ----------------
A matching category: Notebook/Mobile Devices already exists
A matching Company COMPANY already exists
Location SAN FRANCISCO already exists
Manufacturer Apple Notebook Systems (APN) already exists
A matching Status Ready to Deploy already exists
Supplier CDW already exists
Insufficient user data provided (Full name is required)- skipping user creation, just adding asset
Custom Field Invoice Number: INVOICENUMBER
Custom Field Customer PO: PONUMBER
Custom Field Purchased By: LASTNAME FIRSTNAME
No Matching Asset, Creating a new one
A matching model already exists, returning it.
Asset APPLE MBP 13.3 SIL 2.5 16GB 512GB (4967514) with serial number  was created

 4/5 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░]  80% < 1 sec------------- Action Summary ----------------
A matching category: Notebook/Mobile Devices already exists
A matching Company COMPANY already exists
Location SAN FRANCISCO already exists
Manufacturer Apple Notebook Systems (APN) already exists
A matching Status Ready to Deploy already exists
Supplier CDW already exists
Insufficient user data provided (Full name is required)- skipping user creation, just adding asset
Custom Field Invoice Number: INVOICENUMBER
Custom Field Customer PO: PONUMBER
Custom Field Purchased By: LASTNAME FIRSTNAME
No Matching Asset, Creating a new one
A matching model already exists, returning it.
Asset APPLE MBP 13.3 SIL 2.5 16GB 512GB (4967514) with serial number  was created

 5/5 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100% < 1 sec------------- Action Summary ----------------
All Items imported successfully!

run-parts: executing /etc/cron.hourly//ldap_import
```
Looking at the logs from ./storage/logs I see that nothing actually imported automatically:
```
[2018-11-20 22:43:27] production.INFO: ------------- Action Summary ----------------
[2018-11-28 17:54:59] production.INFO: A matching category: Notebook/Mobile Devices already exists
```

However when I look at the history of one of those assets:
![image](https://user-images.githubusercontent.com/4028612/49172025-bce70980-f2f4-11e8-83cf-5b2c05889f1c.png)

So something is definitely broken with cron, and without having syslog in the docker container it makes it incredibly difficult to troubleshoot. I also am confused as to why there are two line entries in the history for the asset since the upload only occurred once.

**Comment by JonathonReinhart** [comment]
@snipe Are you referring to PR #5729? I added a comment there (https://github.com/snipe/snipe-it/pull/5729#issuecomment-454551682) that explains the shortcomings of that PR and the root cause of this issue.

**Comment by JonathonReinhart** [comment]
Furthermore, I don't see anywhere in my `snipe-it:4.6.7` image that the [appropriate cron entry](https://github.com/snipe/snipe-it/blob/v4.6.7/snipeit.sh#L230) is actually configured anywhere.

```
root@65434c97ed30:/etc# grep -rn 'artisan' .
root@65434c97ed30:/etc# 
```

The [`Dockerfile`](https://github.com/snipe/snipe-it/blob/v4.6.7/Dockerfile) doesn't run the `snipeit.sh` installation script, and doesn't add any crontab entries itself.

**Comment by JonathonReinhart** [comment]
Also, in #5922, @EarlRamirez added `cron` *again* to the `Dockerfile`!

**Comment by delize** [comment]
@JonathonReinhart this seems to be the exact issue that I am referring to where you added a comment to. It doesn't look like a daemonized cron job is running, which renders cron pointless.

**Comment by JonathonReinhart** [comment]
All: In my PR #6606 I update the docker image to run `artisan schedule:run` once per minute. That means everything in [`App\Console\Kernel.schedule()`](https://github.com/snipe/snipe-it/blob/v4.6.7/app/Console/Kernel.php#L42) will run on their schedules.

Is this sufficient for Snipe-IT as a whole, and for your deployments? Or do we actually need real `cron`? In other words: should `snipeit:ldap-sync` be added to the snipe-it standard schedule instead of added to the `crontab` by an admin?

Note that if an admin, running the `snipe-it` docker image, *really* wants to run a custom command in the container, one can do so via `docker exec`:
```
$ docker exec -it -u 1000:50 snipeit id
uid=1000(docker) gid=50(staff) groups=50(staff)
```

**Comment by delize** [comment]
Personally, I added ldap-sync to occur as a cronjob only because it wasn't included by default. 

However, I do think that it should be a configurable option and best left for the admin to decide on how often it occurs. If your setting is hardcoded I would say that would be a negative addition. 

For instance, we have ldap sync to run twice a day - how often are LDAP changes occurring at the business level for instance? LDAP runs every minute may or may not cause a monitoring system to go off. Once every hour I would say would be more reasonable. But still a configurable change would be better than hardcoded.

**Comment by delize** [comment]
Once #6606 is released into stable, I will be happy to give this some feedback on whether it resolves the issue or not that we were experiencing. 

Happy to see some headway with this!

**Comment by delize** [comment]
I have good news, and bad news:

Good news, is that we have started seeing automated email reports and things like that after the implementation fix:

```
No scheduled commands are ready to run.
No scheduled commands are ready to run.
Running scheduled command: '/usr/bin/php7.0' 'artisan' snipeit:inventory-alerts > '/dev/null' 2>&1
Running scheduled command: '/usr/bin/php7.0' 'artisan' snipeit:expiring-alerts > '/dev/null' 2>&1
Running scheduled command: '/usr/bin/php7.0' 'artisan' snipeit:expected-checkin > '/dev/null' 2>&1
Running scheduled command: '/usr/bin/php7.0' 'artisan' backup:clean > '/dev/null' 2>&1
No scheduled commands are ready to run.
No scheduled commands are ready to run.
```

The bad news is that I still don't see cron.* folders executing when using `docker logs containername` to view them or when searching through the various log files on the machine (storage/logs/ included)
```
root@8e6f10502f6b:/var/www/html# cat /var/log/lastlog
root@8e6f10502f6b:/var/www/html# cat /var/log/faillog
root@8e6f10502f6b:/var/www/html# cat /var/log/dmesg
(Nothing has been logged yet.)
```

Again these scripts still work perfectly fine if executed manually, but automatically using the /etc/cron.* folders nothing appears to be working.

**Comment by JonathonReinhart** [comment]
@delize Please see my comment right above yours: https://github.com/snipe/snipe-it/issues/6344#issuecomment-455755506

PR #6606 does *not* run `cron`. It only runs the Laravel schedule.
