### ISSUE TITLE
Want to add Urdu Translation to Snipe-IT

### ISSUE THREAD

**Issue by sa1eemKhan** [snipe/snipe-it#6345]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.5 build 3915 (gc7596e774) 
 - OS: [Ubuntu]
 - Web Server: [Apache]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**
Snipe-IT does not have a translation in Urdu(Pakistan).

**Describe the solution you'd like**
I am from Pakistan which national language is Urdu and Urdu is my mother tongue as well. So I want to contribute in translating the Snipe-IT into Urdu. So I need your permission.

**Comment by sa1eemKhan** [comment]
@snipe

**Comment by snipe** [comment]
All set: https://crowdin.com/project/snipe-it/ur-PK
