### ISSUE TITLE
Unable to Sign-In Using AD Credentials

### ISSUE THREAD

**Issue by corygoodwin97** [snipe/snipe-it#6348]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I have been trying to sign into the Portal using my Active Directory (LDAP) credentials and I am being told:  Error: The username or password is incorrect.

**To Reproduce**
1. Go to the SnipeIT install location.
2. Enter Active Directory Username/Password.

**Expected behavior**
You should be able to login to the Administrative Portal.

**Screenshots**
http://prntscr.com/l83ko9

**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.5 build 3915
 - OS: CentOS 6.9
 - Web Server: Apache
 - PHP Version: 7.1.22
 - Laravel Version: 5.4.35

**Desktop (please complete the following information):**
 - OS: macOS High Sierra v10.13.6
 - Browser: Google Chrome

**Smartphone (please complete the following information):**
N/A

**Error Messages**
N/A

**Additional context**
- Fresh Install

**Comment by lemont97** [comment]
would you mind sharing the screenshot of your set up? here is mine. hope it helps.
https://svalve-my.sharepoint.com/:i:/g/personal/joey_chow_swagelok_com_sg/EWqiIefKpIlClGF2lz-YM24B_Bc-VOBMpYPBBmp-5aqgKw?e=nkKwFY

**Comment by elreydetoda** [comment]
@corygoodwin97 #1721

**Comment by auroraeosrose** [comment]
see if the fix in #6375 works - this is the same issue I was having :)
