### ISSUE TITLE
Composer Installation Issue

### ISSUE THREAD

**Issue by dorongnong** [snipe/snipe-it#635]
Version: 1.2.6
OS: Ubuntu 14.4

Hi,

I had a lot of issue when installing snipeit on Windows, so I decided to install in on Linux.
When I run composer I got following error.
![image](https://cloud.githubusercontent.com/assets/11323800/6588334/4cbe76f6-c74d-11e4-9d81-1e88a3326e32.png)

It seems there is a similar post on https://github.com/snipe/snipe-it/issues/612 but I don't think it has been fixed.

Do you have any suggestions?

Thanks.

**Comment by uberbrady** [comment]
It seems to want you to have 'git' installed? you can try that to see if it helps - though it shouldn't.

```apt-get install git``` or ```yum install git``` and see what happens?

**Comment by madd15** [comment]
did you try running `composer clear-cache` then rerunning `composer install`?

**Comment by uberbrady** [comment]
@madd15 has better advice :)

**Comment by dorongnong** [comment]
Thanks uberbrady!!
I just manually installed git and it fixed the issue.

**Comment by dorongnong** [comment]
hum. I have another error now.
When running "php artisan app:install," I got error message, Database [] not configured.
I double checked 'bootstrap/start.php' and database, everythiong seems to be fine.
![image](https://cloud.githubusercontent.com/assets/11323800/6588686/5617fd9e-c752-11e4-9c1c-053967467be8.png)

![image](https://cloud.githubusercontent.com/assets/11323800/6588698/8345f712-c752-11e4-9eba-3b495657ea9c.png)

Any suggestions?

**Comment by snipe** [comment]
Please see the common issues page in the documentation: http://snipeitapp.com/documentation/common-issues/

**Comment by dorongnong** [comment]
I already did. I checked my hostname and bootstrap/start.php file. Everything looks good.

![image](https://cloud.githubusercontent.com/assets/11323800/6589249/390249d2-c75a-11e4-8245-2a9c89dbe281.png)


![image](https://cloud.githubusercontent.com/assets/11323800/6589242/21180d66-c75a-11e4-80a3-de41be84003a.png)

**Comment by uberbrady** [comment]
I'm guessing since you used the same name for 'local' as you did for 'production' that the system thinks you are in local mode, not production mode.

So your production database configuration isn't being read.

If you change the hostnames so that sradev01qairv is no longer in the 'local' hostnames, it should then figure out correctly that you're in Production mode.

**Comment by dorongnong** [comment]
after moving database.php to app/coonfig, this has been resolved. Thanks All!!
