### ISSUE TITLE
Normal user not able to update asset maintenance records

### ISSUE THREAD

**Issue by ausean** [snipe/snipe-it#6351]
#### Expected Behavior (or desired behavior if a feature request)

User (granted with all rights to Assets) should be able to update and delete asset maintenance.

-----

#### Actual Behavior

All users (except Super User) are not able to update or delete asset maintenance.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade

- Version of Snipe-IT you're running
 v4.6.5 - build 3915 (master)

- Version of PHP you're running
7.1.21
- Version of MySQL/MariaDB you're running
MySQL 5.7.23

- What OS and web server you're running Snipe-IT on
Windows Server 2012 R2

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Git 

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
NA

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
NA
- If a stacktrace is provided in the error, include that too.
NA

- Any errors that appear in your browser's error console.
no

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Could not create a user account to verify the issue. With the default (admin) account, no issue.

- Include any additional information you can find in `storage/logs` and your webserver's logs.
No error from logs

- Include what you've done so far in the installation, and if you got any error messages along the way.
Tried on brand new version of v4.4.1. Same issue.
There was a bug #5311 filed in Apr 2018 and was closed.

- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by najamalvi** [comment]
Hi,
Did some body find the solution to this issue already?

I am facing same, as a non super admin user unable to edit maintenances where as I can create new maintenance. 

Ver: 4.6.6
Thanks
