### ISSUE TITLE
Custom Field with “Accessories” in the title causes crash

### ISSUE THREAD

**Issue by jessetechno** [snipe/snipe-it#6355]
“Approved Accessories” Field Causing issues:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I have a custom field name “Approved Accessories” that is causing asset adding/editing to crash.  

**To Reproduce**
1. Go to 'create asset' or edit any asset with a custom field named something with the word "Accessories" in it.
2. Click on 'Create' or 'Update' 
3. Page loads and the create/edit form is unchanged (either blank if create form or back to how it was before you made changes in edit form as nothing was saved).  
4. It is as if you reloaded the page.  No errors are placed in the log or produced by script.

 - Snipe-IT Version: 4.6.5 - build 3915
 - OS: [Linux]
 - Web Server: Apache (I believe)
 - PHP Version : 7.1

**Desktop (please complete the following information):**
 - OS: [MacOS 10.13.6]
 - Browser Chrome & Safari

**Comment by EarlRamirez** [comment]
@jessetechno I used your steps to try and reproduce this behaviour and unfortunately, I was not able to; therefore, we'll need you to enable debugging and share the logs with us.

Steps I took to try and reproduce this behaviour
- Create a custom field "My Accessories"
- Assigned it to an asset model
- Create and update asset and populate that custom field, the form is saved with all fields.

**Comment by snipe** [comment]
I'm also unable to reproduce this issue. There's nothing in the code that would be specific to custom field names, so I'm not sure how to reproduce this.
