### ISSUE TITLE
Settings up web server

### ISSUE THREAD

**Issue by dorongnong** [snipe/snipe-it#636]
Version 1.2.6
OS: Ubuntu 14.4

From Linux installation documentation, it said 'the document root for the app should be set to the public directory.' I do not see public folder on it.

Shout I create it?

Also additional question. When setting up PHP-FPM, Should I put installation folder on the root?
For EX, root /var/www/itasset/snipe-it-1.2.6;

Thanks.

**Comment by dbierspb** [comment]
When you clone the git repo, there is a public folder.  This "public" folder should be the document root.
