### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by jmartins1** [snipe/snipe-it#6362]
Embed force HTTPS option as never or always on future versions. Allowing end user to use HTTPS if they wish; set as default. Configuring HTTPS is not straight forward and varies on end user set up.

**Comment by EarlRamirez** [comment]
This varies from servers (CentOS, Debian, Windows) web server (Apache, Nginx, IIS) it is really up to you to configure SSL. 

For what its worth, you can check out _https://github.com/EarlRamirez/snipeit_iso_ recently added HTTPS as the default.
