### ISSUE TITLE
Database Backup

### ISSUE THREAD

**Issue by jmartins1** [snipe/snipe-it#6363]
Incorporate scheduled database and pertinent file (e.g. equipment images) backup. Allow ability to change backup location.

**Comment by EarlRamirez** [comment]
Your issues need to be more details so we recommend that you complete the template (issue or feature request) so that we will be in a better position to provide you with guidance.

**Comment by jmartins1** [comment]
Did I not at this as a feature request?

**Comment by EarlRamirez** [comment]
> Incorporate scheduled database and pertinent file (e.g. equipment images) backup. Allow ability to change backup location.
This is what you wrote

**Comment by snipe** [comment]
This feature already exists. https://snipe-it.readme.io/docs/configuring-alerts-backups
