### ISSUE TITLE
Admin user account not activated on synced with LDAP

### ISSUE THREAD

**Issue by knavet** [snipe/snipe-it#6364]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
As the administrator who setup the SnipeIt installation, on sync with LDAP, it should allow me (the administrator to login). But now I can't.

**To Reproduce**
1. Create a new installation, enter a username of XXXXXX
2. Setup LDAP sync (AD)
3. Sync users from LDAP into the system. (one of the users happens to have username = XXXXXX, which is the same person)
4. System will correctly identify XXXXXX as the admin and correctly update the displayed name, but the [activated] flag will stay 0.
5. Result = This username (with the correct AD pwd) will fail to authenticate/login.

**Expected behavior**
The [activated] flag should be 1 instead.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.5, Build 3897
 - OS: Windows 2016
 - Web Server: IIS
 - PHP Version: 5.6

**Error Messages**
Logs show in laravel.log shows 
**production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory**  

**Additional context**
- Is this a fresh install or an upgrade?  Fresh Install
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT: Manual installation via pre-flight 

To resolve, go to SQL editor and update my own account from activated=0 to activated=1

**Comment by jwhulette** [comment]
@knavet The import checks to see if your AD user has an userAccountControl id of '512', '544', '66048', '66080', '262656', '262688', '328192', '328224' if not it sets it to inactive. 

What is the userAccountControl id of the user not being activated?

**Comment by knavet** [comment]
> @knavet The import checks to see if your AD user has an userAccountControl id of '512', '544', '66048', '66080', '262656', '262688', '328192', '328224' if not it sets it to inactive.
> 
> What is the userAccountControl id of the user not being activated?

Oh yes, user is 66048. Strange as to why it wasn't activated?

**Comment by jwhulette** [comment]
@knavet It's odd that all the other users are activated but one. How are you doing the sync, command line or on the Users page in the app? Do you have an active flag set in the LDAP settings?
