### ISSUE TITLE
Unable to launch - APP_KEY not recognized

### ISSUE THREAD

**Issue by atrystan** [snipe/snipe-it#6366]
#### Expected Behavior (or desired behavior if a feature request)

After entering APP_KEY into the my_env_file, Snipe-IT should launch.

-----

#### Actual Behavior

I have made three separate attempts at install, all with the same results. Per instructions here:

https://snipe-it.readme.io/v4.6.3/docs/docker

I should run:

docker run --rm snipe/snipe-it

which will result in a message such as this:

Please re-run this container with an environment variable $APP_KEY
An example APP_KEY you could use is: 
base64:D5oGA+zhFSVA3VwuoZoQ21RAcwBtJv/RGiqOcZ7BUvI=

When I paste that key into the my_env_file and attempt to relaunch, the same message appears.

-----

#### Please confirm you have done the following before posting your bug report:

- [N/A ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 

Fresh

- Version of Snipe-IT you're running

Latest from Docker

- Version of PHP you're running

n/a, haven't gotten that far

- Version of MySQL/MariaDB you're running

n/a, haven't gotten that far

- What OS and web server you're running Snipe-IT on

no web server yet
Centos 7, build 1804

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

Docker

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

n/a, haven't gotten that far

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

n/a, haven't gotten that far

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by jwhulette** [comment]
@atrystan To clarify, you put the app key in the file named .env correct?

**Comment by atrystan** [comment]
P.S. Unclear which of these is the correct one. I only have this one project on the machine, so presumably they all came from snipe-it

`[root@lill-asset /]# find / -name *.env*
/var/lib/docker/overlay2/48a6ac1b4b0bfdcfc56b2090844319ed5e81f205592a5ef763a6a69bb3a04e48/diff/var/www/html/.env.unit-tests
/var/lib/docker/overlay2/48a6ac1b4b0bfdcfc56b2090844319ed5e81f205592a5ef763a6a69bb3a04e48/diff/var/www/html/.env.testing-ci
/var/lib/docker/overlay2/48a6ac1b4b0bfdcfc56b2090844319ed5e81f205592a5ef763a6a69bb3a04e48/diff/var/www/html/docker/docker.env
/var/lib/docker/overlay2/48a6ac1b4b0bfdcfc56b2090844319ed5e81f205592a5ef763a6a69bb3a04e48/diff/var/www/html/.env.testing
/var/lib/docker/overlay2/48a6ac1b4b0bfdcfc56b2090844319ed5e81f205592a5ef763a6a69bb3a04e48/diff/var/www/html/.env.tests
/var/lib/docker/overlay2/48a6ac1b4b0bfdcfc56b2090844319ed5e81f205592a5ef763a6a69bb3a04e48/diff/var/www/html/.env.example
/var/lib/docker/overlay2/d0787326ea167fa6e41747c2d469a45402b64fbfbb8fd9c50e799c81970724eb/diff/var/www/html/.env
/var/lib/docker/overlay2/886d907334b3606a40aacbe0ad57e216739f2ed66662077cf08f34649ccfe2aa/diff/var/www/html/vendor/codeception/codeception/tests/data/params/params.env
/var/lib/docker/overlay2/886d907334b3606a40aacbe0ad57e216739f2ed66662077cf08f34649ccfe2aa/diff/var/www/html/vendor/codeception/codeception/tests/data/params/params.env.example
/var/lib/docker/overlay2/66361e5e2913feb2dc0de88a0f682f3dd1f7c03566e045be8462c3cc83029e50/diff/var/www/html/.env.unit-tests
/var/lib/docker/overlay2/66361e5e2913feb2dc0de88a0f682f3dd1f7c03566e045be8462c3cc83029e50/diff/var/www/html/.env
/var/lib/docker/overlay2/66361e5e2913feb2dc0de88a0f682f3dd1f7c03566e045be8462c3cc83029e50/diff/var/www/html/.env.testing-ci
/var/lib/docker/overlay2/66361e5e2913feb2dc0de88a0f682f3dd1f7c03566e045be8462c3cc83029e50/diff/var/www/html/docker/docker.env
/var/lib/docker/overlay2/66361e5e2913feb2dc0de88a0f682f3dd1f7c03566e045be8462c3cc83029e50/diff/var/www/html/.env.testing
/var/lib/docker/overlay2/66361e5e2913feb2dc0de88a0f682f3dd1f7c03566e045be8462c3cc83029e50/diff/var/www/html/.env.tests
/var/lib/docker/overlay2/66361e5e2913feb2dc0de88a0f682f3dd1f7c03566e045be8462c3cc83029e50/diff/var/www/html/.env.example
`

**Comment by jwhulette** [comment]
It’s the .env file in the html directory

**Comment by atrystan** [comment]
@jwhulette Thank you for the response. I realize that I'm being incredibly obtuse here, but each one of those .env files is in an html directory. It's unclear which one is the right one, all of these came with SnipeIt.

**Comment by jwhulette** [comment]
It’s var/www/html/.env Sorry I’m not well versed in Docker

**Comment by atrystan** [comment]
@jwhulette Thanks for the follow up.

I tried putting it in all of the .env files I could find, no luck. There is definitely something missing from the instructions here.

Is it possible to invoke snip-it with the app key as a flag? That would be a good workaround...

**Comment by atrystan** [comment]
To follow up--

We had attempted the Docker method when one of my staff was unable to get the scripted install to work. After having problems with the Docker method, I tried to scripted install myself, and had it up and running in about 10 minutes.

Closing out issue.
