### ISSUE TITLE
Issue with 255 characters

### ISSUE THREAD

**Issue by ErikAzzi** [snipe/snipe-it#6369]
Hi hope someone can help me . I have an issue on one specific asset tag I have more than 255 characters which I can’t reduce or separate. Is there any way I can input that data together?

Thanks in advance

**Comment by jwhulette** [comment]
@ErikAzzi The asset tag field in the database is set to a limit of 191 characters. You could manually change the length of the field in the database. I don't think it would cause issue but it could.
