### ISSUE TITLE
Shibboleth Authentication

### ISSUE THREAD

**Issue by tjbryantuncc** [snipe/snipe-it#6371]
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: Redhat
 - Web Server: Apache
 - PHP Version 7.1.3

**Is your feature request related to a problem? Please describe.**
My group is considering using snipe-it.  Our university requires web applications to use shibboleth.  If I fork and add this feature, how likely would it be for the pull request to be accepted?  

**Describe the solution you'd like**
I would add an environment property to toggle if shibb was enabled or not.  If shibb is enabled, an option would appear on the login page to use shibb login.  The shibboleth IDP login url would be an environment property value.  When shibb login is clicked, the browser would be redirected to the shibboleth IDP login, the user logs in, shibboleth redirects to the shibb auth controller I create, and the user would be logged in.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by snipe** [comment]
Hi there. I don't see any reason why it wouldn't be merged if you created a PR. One thing I might add though is that we typically want to have variables like that added to the settings database table, so that we can validate them using our model-level validation, etc and prevent pebkac.
