### ISSUE TITLE
The license agreement is declined via signature but status still assigned

### ISSUE THREAD

**Issue by happicamper** [snipe/snipe-it#6383]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The license is assigned even it has been declined by the user. 

**To Reproduce**
1. Go to License tab
2. Click on one of the license and assigned it to a user.
3. User declines the asset delivery email via signature
4. Show current status, it is still assigned to a user.

**Expected behavior**
The license shouldn't be assigned to the user who has declined it.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.6 build 3926 (g1a10aa0dd) 
 - OS: Docker Service on CentOS

**Error Messages**
- No error found

**Additional context**
- What method you used to install Snipe-IT: Docker

**Comment by snipe** [comment]
In the case of physical assets though, many times the hardware is already in the user's possession. To un-assign it arbitrarily could cause it to get lost.

**Comment by happicamper** [comment]
Oh sorry, is this an expected behavior? Is it just me or the previous version, it automatically un-assigned the asset upon declining the agreement.

**Comment by happicamper** [comment]
@snipe I guess it is, well that makes sense. Thank you!
