### ISSUE TITLE
[BUG] License search does not "look" in categories 

### ISSUE THREAD

**Issue by Diniver** [snipe/snipe-it#6386]
Bug is reproducable in demo website

In few words, when I am trying to search licenses by category, I am getting strange results or non at all.

**To reproduce**

1. Software Licenses
2. Enable _Category_ from columns 
We have 9 licenses currently in the demo site:

![image](https://user-images.githubusercontent.com/31882138/47919125-7e516100-dea6-11e8-9fda-b806cd5a7f87.png)

3. I would like to see all graphic software, so I type graph in search

![image](https://user-images.githubusercontent.com/31882138/47919213-beb0df00-dea6-11e8-89c9-686c070d84cf.png)

If I type software it picks up only office software but not all of them. There should be 3 licenses under office software category

![image](https://user-images.githubusercontent.com/31882138/47919295-ebfd8d00-dea6-11e8-9824-8bd22f923a52.png)

I have used demo website for this bug report, but I have the problem on my server as well

My server information
Snipe-IT version | v4.6.6  build 3926 (g1a10aa0dd)
PHP Version | 7.2.10-0ubuntu0.18.04.1
MySQL | 5.7.24-0ubuntu0.18.04.1 
Laravel Version | 5.4.35

**Comment by snipe** [comment]
Thanks for this bug report! This issue has been fixed and merged into the `master` branch, and will be in the next release.

![trek-nods](https://user-images.githubusercontent.com/197404/47946205-b9af5800-dec5-11e8-85af-fce7915a0938.gif)
