### ISSUE TITLE
Why won't the test email change when I change it in the env file or config.v2.json file?

### ISSUE THREAD

**Issue by GSpell1997** [snipe/snipe-it#6388]
#### Expected Behavior (or desired behavior if a feature request)

During my setup of Snipe-It I accidentally mistyped my MAIL_ENV_FROM_ADDR to .com when I wanted it as .edu. So I went and changed that in my .env file and even the config.v2.json file in hopes that it would change to the proper email.

-----

#### Actual Behavior

But when I do that, it says it changed in the file when I output it. But when I go to actually send a test email on my snipe-it server it still has the old email. It never changes. I am stuck and could not find actual documentation on why my email change does not work.

-----

#### Please confirm you have done the following before posting your bug report:

- [ x ] I have enabled debug mode 
- [ x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? (FRESH INSTALL) 
- Version of Snipe-IT you're running (v.4.6.6)
- Version of PHP you're running (7.0.32-0ubuntu0.16.04.1)
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on (Using it on Windows 10, but hosting it on SLES 15)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) (DOCKER)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by jwhulette** [comment]
@GSpell1997 Try clearing your config and cache.
