### ISSUE TITLE
Hi need some help here 

### ISSUE THREAD

**Issue by rnovo1983** [snipe/snipe-it#639]
Im getting this error 

Error in exception handler: The stream or file "/var/www/html/snipe/app/storage/logs/log-apache2handler-2015-03-11.txt" could not be opened: failed to open stream: Permission denied in /var/www/html/snipe/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:84

**Comment by snipe** [comment]
Looks like you kissed step 4? http://snipeitapp.com/documentation/installing-on-linuxosx/

**Comment by snipe** [comment]
Looks like you missed step 4? http://snipeitapp.com/documentation/installing-on-linuxosx/

**Comment by snipe** [comment]
Looks like you missed step 4? http://snipeitapp.com/documentation/installing-on-linuxosx/

**Comment by snipe** [comment]
Ugh, sorry for all the posts. GitHub site hiccuped.

**Comment by rnovo1983** [comment]
I fix that already now I got this on the web site

The requested URL /auth/signin was not found on this server.

**Comment by rnovo1983** [comment]
mmm, fixed that now got...

 Error in exception handler.

I see no Logs created on /app/storage

**Comment by snipe** [comment]
What is the error specifically? Have you actually followed the install directions from start to finish?

**Comment by rnovo1983** [comment]
this is what I have right now... 

Not Found

The requested URL /auth/signin was not found on this server.

Apache/2.4.7 (Ubuntu) Server at 192.168.123.20 Port 80

**Comment by rnovo1983** [comment]
I think is related to apache configuration.

**Comment by dbierspb** [comment]
What is showing in the error logs for apache?  Did you add the virtualhost directives that were in the installation instructions?

Have you tried enabling debug mode, just to be sure?  It sounds like a broken re-write rule (or you just don't have rewrite enabled/on).  It may be you're missing the AllowOverride directive in the vhosts for the directories.

**Comment by snipe** [comment]
Yeah, sounds like mod_rewrite is either not installed, or not enabled via Apache directives.

**Comment by dbierspb** [comment]
@rnovo1983 Any update on this?  Were you able to get it working?  Can you please post your virtualhost config for this?

**Comment by snipe** [comment]
(This is actually the first entry on the common issues page.) http://snipeitapp.com/documentation/common-issues/
