### ISSUE TITLE
Markdown in Notes field

### ISSUE THREAD

**Issue by giuliofoletto** [snipe/snipe-it#6391]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.6 build 3926 (g1a10aa0dd)
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version: 7.1.23

**Is your feature request related to a problem? Please describe.**
I want to add a detailed description to each asset, which might include links to external documentation, websites etc. 

**Describe the solution you'd like**
The Notes field (or any multi line text field) should support markdown (maybe GFM).

**Comment by snipe** [comment]
Unfortunately, that could cause issues with reverse-compatibility. Anyone with a line of notes with a hash symbol, for example, will have that rendered as markdown, which would create a giant `<h1></h1>` and would look pretty awful.

We might be able to add a method to auto link urls, but I'm not sure markdown would work here. Or if it did, it would have to be a setting folks could turn on and off.

**Comment by giuliofoletto** [comment]
I guess a setting would be ok. An alternative solution could be the possibility to add custom fields that support GFM, as a new form element (eg "Text Area with GFM") or as a new format (in addition to regex, email... and restricted only to Text Area forms).

**Comment by YoSiJo** [comment]
Sorry to drag this topic into the light of day, but Markdown support would be very handy here.
I would prefer an activatable setting and even see its future default at true.
@snipe is it possible to reopen this issue?

**Comment by llauren** [comment]
While a bit of a workaround for us, this would still be a useful feature.

What we are looking for is adding a link to the maintenance case at the repair provider. #6609 suggests adding **custom fields to a maintenance case**, but it seems that feature request has gone stale. 

The more functional solution would be to allow adding links as text to the maintenance Notes field. The link text would be automatically interpreted as links when not editing the text field, or even as an option when hovering over the link, á la Google Docs.

A viable solution, though still a kluge, would be allowing markdown to create a link.
