### ISSUE TITLE
Request to add import fields

### ISSUE THREAD

**Issue by a0z0** [snipe/snipe-it#6393]
Hello.

**Server (please complete the following information):**
 - Snipe-IT Version : 4.6.6
 - OS: CentOS7
 - Web Server: Apache
 - PHP Version 7.2.9

**Is your feature request related to a problem? Please describe.**
I am in trouble with asset data migration.

**Describe the solution you'd like**
Request to add import fields.
- Users import fileds: notes
- Assets import  fileds: checkout_at, expected_checkin

**Comment by sinichi19** [comment]
I believe, if the model you need import is already in the system and set the custom fieldset, all your imported asset is inheri the settings of the model, make sure you type the exact model and model# before you import.
