### ISSUE TITLE
There are too many columns in the asset list

### ISSUE THREAD

**Issue by a0z0** [snipe/snipe-it#6394]
Hello.

**Server (please complete the following information):**
 - Snipe-IT Version : 4.6.6
 - OS: CentOS7
 - Web Server: Apache
 - PHP Version 7.2.9

**Is your feature request related to a problem? Please describe.**
When there are many custom fields, the asset list table columns can not be displayed.

**Describe the solution you'd like**
Do not show custom fields in list by default.

**Comment by EarlRamirez** [comment]
How many customs fields do you have? Can you share the error and enable debugging and share those errors with us as well.

**Comment by a0z0** [comment]
Thank you EarlRamirez.

It is not an error.
However, it is difficult to see the list
