### ISSUE TITLE
Graph of Asset by Status in Dashboard became small (works in mobile) - Similar to #4678

### ISSUE THREAD

**Issue by samotelf** [snipe/snipe-it#6395]
#### Please confirm you have done the following before posting your bug report:

- [√ ] I have enabled debug mode 
- [ √] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Graph of Asset by Status in Dashboard became small - Similar to #4678 however it is fine on Mobile

**To Reproduce**
1. Go to 'Dashboard'
4. See small graph

**Expected behavior**
Graph of assets proportionally presented

Screenshots
**https://paste.pics/4228H - Desktop
https://paste.pics/4228Y - Mobile**

**Server (please complete the following information):**
 - Snipe-IT Version - 4.6.6
 - OS: [e.g. Ubuntu, CentOS] - CentOS 7
 - Web Server: [e.g. Apache, IIS] - Apache
 - PHP Version - 7.1.13

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - MacOS 10.13.6
 - Browser [e.g. chrome, safari] - Safari and Chrome
 - Version [e.g. 22] - 12.0.1 and 70.0.3538.77

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] - iPhone X
 - OS: [e.g. iOS8.1] - iOS 12.1
 - Browser [e.g. stock browser, safari] - Safari
 - Version [e.g. 22] - xxx

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? - Upgrade
- What OS and web server you're running Snipe-IT on - Centos7 + Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Manual
- Include what you've done so far in the installation, and if you got any error messages along the way. - N/A
- Indicate whether or not you've manually edited any data directly in the database - No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by samotelf** [comment]
@jwhulette Thank you. Did a sudo -u apache php artisan config:clear and sudo -u apache php artisan config:cache but no dice. Please note that this issue is also present in the Demo.
I didn't have the npm command so I did a yum install -y node.js and the output for node -v is v6.14.3
and for npm is 3.10.10.
Tried to run sudo -u apache npm run prod and I've got this output:

sh: cross-env: command not found
So, did a npm install cross-env with the following:
sudo npm install cross-env
and when i run
sudo npm run prod I have this:

> @ prod /var/www/html/snipeit
> npm run production


> @ production /var/www/html/snipeit
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules/webpack/bin/webpack.js ENOENT
    at exports._errnoException (util.js:1020:11)
    at Press.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:613:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
    at bootstrap_node.js:507:3

Any ideas?
Thank you in advance.

**Comment by jwhulette** [comment]
@samotelf I think your node is old, that's the reason for the error, but not sure. I'll look into it.

**Comment by jwhulette** [comment]
@samotelf I just check the demo site, https://demo.snipeitapp.com and it's working correctly.

**Comment by samotelf** [comment]
Hi @jwhulette I think it has nothing to do with it.
I just made the following test.
I fired my snipeit test vm and with one asset the cake is fine (it could be bigger though)but after I imported my sql file from production, the cake turned small.

Here, take a look:

New installation:
https://prnt.sc/ljnbz5
After import:
https://prnt.sc/ljncfw

Also, you can also notice a difference from the demo and the develop demo.
The develop demo is working fine.
And since I believe this will be corrected in v5 I will now be closing this issue.
Thank you anyway for your help.

**Comment by samotelf** [comment]
Well, this has been bugging me and I will re-open this issue.
I troubleshooted this and the issue here is the more asset labels you have, the more the graph will diminish until it disappears completely. The graph should adjust accordingly.
We're talking about 4 or 5 more status labels.

**Comment by ckinsler** [comment]
Can confirm, we're seeing the same issue with 10 labels

![image](https://user-images.githubusercontent.com/10969819/50017616-37b95100-ff92-11e8-88f4-5477ad94af08.png)
