### ISSUE TITLE
Running upgrade.php says autoload.php is missing altough it is not

### ISSUE THREAD

**Issue by dan-e-mediapplications** [snipe/snipe-it#6396]
Hello,

I have performed an OS server update on AWS Centos 6.10 2.6.32-754.6.3.el6.x86_64 
(Snipe-it is on 4.20 version, WebServer version: Apache/2.2.15 (Unix))
Which upgraded PHP to PHP 7.1.23. & Zend Engine v3.1.0.
After a reboot (For the Kernel to change), i have ran `php upgrade.php`
and git was pulled to this commit
From https://github.com/snipe/snipe-it
   2d0df24..b6daad7  develop    -> origin/develop
   f374ac1..192aa9e  master     -> origin/master
From https://github.com/snipe/snipe-it
 * [new tag]         v4.6.4     -> v4.6.4
 * [new tag]         v4.6.5     -> v4.6.5
 * [new tag]         v4.6.6     -> v4.6.6
-- No local changes to save
-- -- Updating f374ac1..192aa9e

But saw many errors like the ones below:
`No such file or directory in /opt/git/bootstrap/autoload.php`

--> the file do exists..
[user git]$ cd /opt/git/bootstrap/
[user bootstrap]$ ls -la
total 20
drwxrwxr-x.  3 user user 4096 2018-11-04 18:27 .
drwxr-xr-x. 15 user user 4096 2018-11-04 18:16 ..
-rw-rw-r--.  1 user user 1602 2018-04-12 09:52 app.php
-rw-rw-r--.  1 user user 1079 2018-11-04 18:27 autoload.php
drwxrwxr-x.  2 user user 4096 2018-04-12 09:52 cache

The end outcome is that the upgrade is not happening and I am still on version 4.20
Here are the full error I get.

--------------------------------------------------------
STEP 1: Backing up database:
--------------------------------------------------------

PHP Warning:  require(/opt/git/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /opt/git/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/opt/git/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /opt/git/bootstrap/autoload.php on line 17
--

--------------------------------------------------------
STEP 2: Putting application into maintenance mode:
--------------------------------------------------------

PHP Warning:  require(/opt/git/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /opt/git/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/opt/git/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /opt/git/bootstrap/autoload.php on line 17
--

--------------------------------------------------------
STEP 3: Pulling latest from Git (master branch):
--------------------------------------------------------

Git is installed.
Already on 'master'
-- No local changes to save
-- -- Already up-to-date.
--------------------------------------------------------
Step 4: Cleaning up old cached files:
--------------------------------------------------------

-- No bootstrap/cache/compiled.php, so nothing to delete.
-- No bootstrap/cache/services.php, so nothing to delete.
-- No bootstrap/cache/config.php, so nothing to delete.
PHP Warning:  require(/opt/git/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /opt/git/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/opt/git/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /opt/git/bootstrap/autoload.php on line 17
PHP Warning:  require(/opt/git/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /opt/git/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/opt/git/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /opt/git/bootstrap/autoload.php on line 17
PHP Warning:  require(/opt/git/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /opt/git/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/opt/git/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /opt/git/bootstrap/autoload.php on line 17
PHP Warning:  require(/opt/git/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /opt/git/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/opt/git/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /opt/git/bootstrap/autoload.php on line 17
-- -- -- --
--------------------------------------------------------
Step 5: Updating composer dependencies:
(This may take an moment.)
--------------------------------------------------------

-- We couldn't find a local composer.phar - trying globally.

sh: composer: command not found
sh: composer: command not found

--------------------------------------------------------
Step 6: Migrating database:
--------------------------------------------------------

PHP Warning:  require(/opt/git/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /opt/git/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/opt/git/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /opt/git/bootstrap/autoload.php on line 17
--

--------------------------------------------------------
Step 7: Checking for OAuth keys:
--------------------------------------------------------

PHP Warning:  require(/opt/git/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /opt/git/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/opt/git/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /opt/git/bootstrap/autoload.php on line 17
--------------------------------------------------------
Step 8: Caching routes and config:
--------------------------------------------------------

PHP Warning:  require(/opt/git/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /opt/git/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/opt/git/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /opt/git/bootstrap/autoload.php on line 17
PHP Warning:  require(/opt/git/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /opt/git/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/opt/git/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /opt/git/bootstrap/autoload.php on line 17
-- --
--------------------------------------------------------
Step 9: Taking application out of maintenance mode:
--------------------------------------------------------

PHP Warning:  require(/opt/git/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /opt/git/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/opt/git/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /opt/git/bootstrap/autoload.php on line 17
--

**Comment by dan-e-mediapplications** [comment]
Thanks.
I have installed Composer and landed on another error:
Application is in production - so tried to edit the .env file, php artisan down, restart the app- no joy.
Tried to add this user 'forge' to DB but no joy.

In Connection.php line 647:
  SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO) (SQL: select * from information_schema.tables where table_schema = forge and table_name = migrations)

In PDOConnection.php line 47:
  SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO)

In PDOConnection.php line 43:
  SQLSTATE[HY000] [1045] Access denied for user 'forge'@'localhost' (using password: NO)

**Comment by dan-e-mediapplications** [comment]
Any one ?

**Comment by snipe** [comment]
If it's still looking for forge, it's not reading your .env file. You need to figure out why that is.

**Comment by dan-e-mediapplications** [comment]
Got it. leaving this for the people who will encounter this issue as me.

For some unknown turn of events, the permission level changed, probably when upgrading.
Once permissions were changed all around to the correct one, site was up and running.

**Comment by anvar88at** [comment]
Warning: require(/home/vin3337506/viniks.net/docs/bootstrap/autoload.php): failed to open stream: No such file or directory in /home/vin3337506/viniks.net/docs/index.php on line 22

Fatal error: require(): Failed opening required '/home/vin3337506/viniks.net/docs/bootstrap/autoload.php' (include_path='.:/home/vin3337506/viniks.net/php') in /home/vin3337506/viniks.net/docs/index.php on line 22
