### ISSUE TITLE
Importing stuck at "Processing" @ version 4.6.6 & 500 (Internal Server Error)

### ISSUE THREAD

**Issue by shiroamada** [snipe/snipe-it#6398]
Expected behavior
Import CSV, process CSV, match fields, import success.

Screenshots

Server (please complete the following information):

Snipe-IT Version: 4.6.6
OS: [Ubuntu]: Windows Server 2016 Standard
Web Server: [Apache v2.4.27]
PHP Version: 7.1.8

Actual Behavior
VM339:1 POST http://assets.shiroamada.test:81/api/v1/imports/process/4 
500 (Internal Server Error)
Importing through GUI is stuck at "Processing"

Additional context

Is this a fresh install or an upgrade?
It's been upgraded to 4.6.6
Inside the file "config/version.php" after upgrading "php upgrade.php"

```
<?php
return array (
  'app_version' => 'v4.6.6',
  'full_app_version' => 'v4.6.6 - build 3926-g1a10aa0dd',
  'build_version' => '3926',
  'prerelease_version' => '',
  'hash_version' => 'g1a10aa0dd',
  'full_hash' => 'v4.6.6-24-g1a10aa0dd',
  'branch' => 'master',
);

```

Log:
```
[2018-11-05 17:46:46] production.ERROR: ErrorException: Undefined index: manager_id in C:\www\snipe-it\app\Importer\Importer.php:319
```

**Comment by cbfloyd** [comment]
We are having this issue and it appeared after going to 4.6.6. Cleared Cache using the artisan clear commands and not an issue in browser cache.  JavaScript console shows  Failed to load resource: the server responded with a status of 500 (Internal Server Error)  - we're running on Umbutu 18.04. 

[15:22:00] LOG.error: ErrorException: Undefined index: manager_id in /var/www/html/snipeit/app/Importer/Importer.php:319

LINE 319 of that file is:
$user->manager_id = ($user_array['manager_id'] ? $user_array['manager_id'] : null);

**Comment by cbfloyd** [comment]
Not sure if this is a final fix or not, but I changed line 319 and the error no longer appears:

OLD: $user->manager_id = ($user_array['manager_id'] ? $user_array['manager_id'] : null);
NEW: $user->manager_id = (**isset(**$user_array['manager_id']**)** ? $user_array['manager_id'] : null);

Made a similar change to the line 320 as well, using the isset() function to test if item exists (set). 
OLD: $user->department_id = ($user_array['department_id'] ? $user_array['department_id']:  null);
NEW: $user->department_id = (isset($user_array['department_id']) ? $user_array['department_id']:  null);

We're running PHP Version 7.2.10-0ubuntu0.18.04.1 if that makes any differences in the testing of variables.

**Comment by Damancor** [comment]
This fixed my issue as well. Thanks for the fix!
