### ISSUE TITLE
Composer Install unable to resolve packages

### ISSUE THREAD

**Issue by awinterton** [snipe/snipe-it#6399]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
composer install error

C:\inetpub\snipe-it>composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for intervention/image 2.4.2 -> satisfiable by intervention/image[2.4.2].
    - intervention/image 2.4.2 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
  Problem 2
    - Installation request for league/flysystem 1.0.48 -> satisfiable by league/flysystem[1.0.48].
    - league/flysystem 1.0.48 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
  Problem 3
    - league/flysystem 1.0.48 requires ext-fileinfo * -> the requested PHP extension fileinfo is missing from your system.
    - spatie/laravel-backup 3.11.0 requires league/flysystem ^1.0.8 -> satisfiable by league/flysystem[1.0.48].
    - Installation request for spatie/laravel-backup 3.11.0 -> satisfiable by spatie/laravel-backup[3.11.0].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\Program Files\PHP\v7.2\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.3
 - OS: Windows Server 2012 R2
 - Web Server: IIS
 - PHP Version 7.2.7

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version latest

**Additional Info
Server is hosting other web applications. SnipeIT will be it's own site on the server. Will be using a different port to prevent http/s conflicts. Other web apps are on PHP5.6. The site for Snipe-IT is set to 7.2.7.

**Comment by snipe** [comment]
According to the error, you need the fileinfo extension enabled in your PHP

**Comment by awinterton** [comment]
Thank you. I've been having a hard time following the guide. Enabling the fileinfo extension solved the problem.
