### ISSUE TITLE
Being able to create lists of devices which then need to be maintained until a certain date

### ISSUE THREAD

**Issue by passboltUser** [snipe/snipe-it#6401]
**Server (please complete the following information):**
 - Snipe-IT Version 
 v4.6.5 - build 3915 (master)

**Is your feature request related to a problem? Please describe.**
The way it currently works is a problem, yes. A maintenance schedule list of certain devices needs to be maintained/completed until a certain date, if not, the unmaintained devices in that list get first a yellow background color, then a red one and the notification emails may be sent more frequently. 

**Describe the solution you'd like**
I want to be able to create a list of devices which must be maintained until a certain date. The user who maintains the list picks a device from the list, sets it to maintained and then that device gets a green background color, although that thing with the color is not so important. 

**Describe alternatives you've considered**
I considered using what Snipe-IT already has: Selecting a device, clicking the Maintenance tab, and clicking maintain. Then that device is listed under `/hardware/maintenances`. But what I want is to be able to create lists of devices, say e.g. "Servers", or "Client PCs" which then need to be maintained until a certain date.

I asked my question initially here and was suggested to open a feature request: https://github.com/snipe/snipe-it/issues/6340

**Comment by kmclea16** [comment]
I second this idea. We'd need a feature like this if we were to consider implementing Snipe-IT at our school.

**Comment by passboltUser** [comment]
We are not using Snipe-IT anymore exactly due to this one missing feature.
