### ISSUE TITLE
To accept assets user have to have admin permissions

### ISSUE THREAD

**Issue by jackka** [snipe/snipe-it#6403]
- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
To Accept assets user have to have Admin permissions

**To Reproduce**
1. User received email with acceptance link.
1. User logged in already.
1. User clicked the acceptance link from email.
1. And got Error: Insufficient permissions! <img src="https://user-images.githubusercontent.com/6271335/48077016-7de2fe00-e1f7-11e8-82ea-1f61278ebb09.png" width="250" >

**Expected behavior**
User should have an ability to accept assets with any lower permissions than Admin

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.5 - build 3915 (master)
 - OS: ubuntu0.18.04.1
 - Web Server: Apache/2.4.29 
 - PHP Version: 7.2.10

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi 
 - Version: 1.15.1147.64 (Stable channel) (32-bit)

**Comment by jackka** [comment]
Yep

**Comment by jackka** [comment]
This happened in FullMultiCompany mode. It was the appropriate behavior.

**Comment by dannyvergel** [comment]
hi everyone, any fix or workaround?

**Comment by elorden** [comment]
> hi everyone, any fix or workaround?

I could be wrong, but typically that issue is that user in question is not assigned to the same Company as the Asset they're attempting to accept.  That is by design unless I'm misunderstanding.

**Comment by dannyvergel** [comment]
Thanks, doing that, works perfecly!


*Confidencialidad:*

* La información contenida en este email es confidencial y sólo puede ser
utilizada por la persona o la compañía a la   cual está dirigido y/o por el
emisor. Si no es el receptor autorizado, cualquier retención, difusión,
distribución o copia de este mensaje es prohibida y será sancionada por la
ley. Si por error recibe este mensaje, favor enviarlo de vuelta y borrar el
mensaje recibido inmediatamente.


* This message may contain privileged, confidential or proprietary
information for the sole use of Danny Vergel and  related persons or
business enterprises.The use, copy or distribution of this message may only
be made by and to authorized parties. If you received this message by
mistake, please delete it and notify to the sender immediately.You should
not use the information contained for any purpose or share it with others.

*Antes de imprimir este mensaje, piensa si es necesario hacerlo.
*Before printing this message,  think about if necessary.
