### ISSUE TITLE
Feature Request: Custom Actions Button to use Snipe as MDM

### ISSUE THREAD

**Issue by bricelabelle** [snipe/snipe-it#6404]
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**
No, this would be additional functionality.

**Describe the solution you'd like**
MicroMDM is an open source MDM solution for Apple devices. While very powerful and free, there is no GUI. We have already begun using MicroMDM to pull mdm data into Snipe-IT using the API and custom fields. What we would like to see is a customizable button on the asset details page that would allow us to run API calls to our MicroMDM server/ Apple DEP etc. We could make Snipe-IT into a powerful mdm interface with MicroMDM running on the back end. We are currently working on using locations set in Snipe-IT to determine which DEP profiles get applied to a device. The main thing we need is a button that would allow us to run DEP commands in real time using API calls. 

**Describe alternatives you've considered**
There are many open source mdm's but none that come with a good GUI or the ability to filter and sort devices into useful groups the way Snipe can. 

**Additional context**

**Comment by mardoqueo** [comment]
Snipe-IT for MDM would be just perfect! +1

**Comment by untuned** [comment]
I second this, would love to see this as an addon!
