### ISSUE TITLE
Allow administrators to specify custom fields to be updated during check-in/check-out

### ISSUE THREAD

**Issue by lovettbp** [snipe/snipe-it#6407]
Currently, Snipe has a pre-defined set of fields that can be updated by an administrator at check-in/check-out (e.g. asset name, status, etc.)

Some fields need to be updated every time an asset is checked in or out to a new user. Sure, we can just go and edit the asset, but it is easy to forget to do this and allowing admins to specify custom fields to include on the check in/out page would be extremely helpful.

For example, in our organization, we have a strict "no local administrator" policy for PCs. However, some users require local admin privs due to legacy software. We created a custom required field for all of our PC models that gives a y/n option for a user's local admin status and a text box to explain why they have local admin privs. Obviously, if a user is terminated or the PC is swapped out and given to a new user, this field would change and it would be much easier to have this information presented at check in/out as a result.

Below is an example of how this would look in practice.

![fksherj](https://user-images.githubusercontent.com/3360358/48143668-4ae34d80-e27d-11e8-9e2f-d1d25083d9d6.png)

Admins would be able to specify which custom fieldsets appear at check in/out for specific models.

**Comment by bricelabelle** [comment]
Our team would LOVE this feature!

**Comment by lovettbp** [comment]
Issue is still relevant, waiting on feedback from @snipe
