### ISSUE TITLE
Puchase costs must be a number 

### ISSUE THREAD

**Issue by MoreLoliThanYou** [snipe/snipe-it#6411]
#### Expected Behavior (or desired behavior if a feature request)

If i type the price 158.369,24 (in Germany we write prices like this) it should be fine.

-----

#### Actual Behavior

If i try to write the price like that snipe-it says: "purchase cost must be a number"

-----

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----

- Is this a fresh install or an upgrade?          fresh installation
- Version of Snipe-IT you're running          v4.6.6 - build 3926
- Version of PHP you're running          php 7.0.30mq
- Version of MySQL/MariaDB you're running          mysql Ver 15.1 Distrib 10.1.26-MariaDB
- What OS and web server you're running Snipe-IT on          Debian 9
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)          the git clone method
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error          Debug on, no error expect for "purchase cost must be a number"
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error          I am at the "Create Asset" page
- Any errors that appear in your browser's error console.          no
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.          it is reproducible on the demo

**Comment by Jarli01** [comment]
"Normally in the UK as €100.00. BUT for sums in excess of €1000.00 In some countries you write it as €1.000:00 or €1,000:00. I commend the latter in writing as it is unlikely to be misunderstood.
For sums in excess of a few million, it is rarely written without a separator between each group of three numbers,
So I would write €123,456,789:98. Chance would be a fine thing."

Reference([1 Quora.com How do I properly. . .](https://www.quora.com/How-do-I-properly-write-the-euro-currency-amounts))

**Comment by Jarli01** [comment]
I think the issue lies in the use of the comma as a currency separator. 

IE: €10,532.40 must be entered as €10532.40

But the convention shows using comma every 3 digits and using a period ( . ) for the fractional amounts. 

IE: €12,356,982.53

**Comment by Jarli01** [comment]
I too would appreciate the use of commas for USD and cents as well.

**Comment by Jarli01** [comment]
Yes it is. I would appreciate if this feature would be included

**Comment by MoreLoliThanYou** [comment]
Yes the Problem ist still present. I updated to Version 4.6.8

If i want to wirte a Price like 567,78€ i have to write it 567.78€ , i am not allowed to use ","

**Comment by heikoboehme** [comment]
is this fixed in the recent versions ?

**Comment by snipe** [comment]
Currency format has been available for quite some time. Comma separators between sets of 3 digits will be in v6.
<img width="900" alt="Screen Shot 2021-06-28 at 11 35 16 PM" src="https://user-images.githubusercontent.com/197404/123748873-a49f4880-d869-11eb-8ccd-fc5b7e0ff28d.png">

**Comment by heikoboehme** [comment]
ohhhhhh i should proceed an update!! Thank you so much!!

**Comment by D3I5** [comment]
oh great news :D (i forgot about this toppic tbh.) seams like i am going to update soon. THX :)
