### ISSUE TITLE
Cant redirect to HTTPS

### ISSUE THREAD

**Issue by sinichi19** [snipe/snipe-it#6414]
#### Expected Behavior (or desired behavior if a feature request)
Newbie here: Need an assistance please..
Succesfuly installed the ssl wildcard certificate from comodo then
Cant load the page when accessing via domain Ex. snipe.mydomain.com:1234
i used port mapping in our firewall to listen to port 443 
and  i need mannualy type the https to work.

.ENV
My APP_URL=https://snipe.mydomain.com:1234

htacess: 
   RewriteEngine On

    # Uncomment these two lines to force SSL redirect in Apache
  RewriteCond %{HTTPS} off
  RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
-----

#### Actual Behavior

i successfully browse and log in when i manually typed the complete adress Ex. https://snipe.mydomain.com:1234

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  upgraded 
- Version of Snipe-IT you're running : 4.6.6
- Version of PHP you're running : 7.2.11
- Version of MySQL/MariaDB you're running - MariaDB 10.0
- What OS and web server you're running Snipe-IT on : Windows 10 IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) using git 
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the 

https://snipe-it.readme.io/docs/getting-help

**Comment by jwhulette** [comment]
@sinichi19 I think the problem is the https is normally port 443, so the redirect is going to that port. You have a different port configured. I believe you need to adjust your vhost configuration to ensure that it's listening to port 1234.

**Comment by sinichi19** [comment]
@jwhulette thank you for your comment. You mean is every computer need to connect to the server is i need to add the configuration in their host file. Or on server only? May request sample configuration? Thank you very much

**Comment by jwhulette** [comment]
@sinichi19 No, in the Apache VHOST configuration file for the site you can specify the port.
[https://serverfault.com/a/246474](urlhttps://serverfault.com/a/246474)

**Comment by sinichi19** [comment]
@jwhulette where can i locate the vhost hehe sorry not familiar to that file and settings.. im using windows iis .  Gaian thank you 🤗🤗

**Comment by jwhulette** [comment]
@sinichi19 Sorry, I just read your using IIS for web serving, not Apache. You would have to google on how to set up IIS website for specific port. I have no idea how to accomplish that on IIS.

**Comment by sinichi19** [comment]
@jwhulette ok thank you again now i have an idea.. God bless

**Comment by EarlRamirez** [comment]
@sinichi19 I will try to help you with your binding, I am no expert in Windows IIS but I think I may be able to point you in the right direction.

- From IIS select the site that you will like to listen on port 443
- Select Binding under the Action window on the right
- The Edit Site Binding window will open, select https for the type and 443 for the port.
- Select the SSL certificate that you will like to use for this site.
Let me know if this helps.

**Comment by EarlRamirez** [comment]
@sinichi19 my bad,  check out the following sites and see if it helps you

- https://www.ntweekly.com/2017/01/17/how-to-redirect-http-to-https-website-with-microsoft-iis-7-web-server/
- https://www.saotn.org/redirect-http-to-https-on-iis/

**Comment by sinichi19** [comment]
@ErlRamirez ok i will check thank you very much sir. I will give you a feedback if its already ok. I also reading some tuitorial.🤗🤗🤗 Thank you

**Comment by sinichi19** [comment]
I will temporary close this request.. thank you guys..
