### ISSUE TITLE
Asset Acceptance Hard Copy

### ISSUE THREAD

**Issue by nazirahmadnoori** [snipe/snipe-it#6415]
**Server (please complete the following information):**
 - Snipe-IT Version : v4.6.6 build 3926 (g1a10aa0dd)
 - OS: CentOS 7
 - Web Server: Apache
 - PHP 7.2

**Is your feature request related to a problem? Please describe.**
It is not a problem but it is necessary to be there, I want a feature then when we do check out or check it and Asset there should be a option to print a details of the Asset with user and then the user should be able to sign on it. 

**Describe the solution you'd like**
a activity report should be print with the all details for the user and Asset 

**Describe alternatives you've considered**
we can integrate with some invoicing platform 

**Additional context**

**Comment by omyno** [comment]
To add to this, it would be even better if the "Print All Assigned" would show the EULA text that the user had signed when he checked the asset in/out and if it would show the corresponding digital signature as an image.

Currently, I don't have a way to hand a user a piece of paper (with his signature already in it) as proof that they checked an asset in/out.

**Comment by snipe** [comment]
Duplicate of #3750
