### ISSUE TITLE
Check out Asset to Location Email Notification

### ISSUE THREAD

**Issue by sinichi19** [snipe/snipe-it#6417]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.6
 - OS: Windows 10
 - Web Server: IIS
 - PHP Version 7.2.11

**Is your feature request related to a problem? Please describe.**
I dont know if this is duplicate or existing features, my request is if the asset check out to the location someone received an email notification.

**Describe the solution you'd like**
If the Location have assigned Manager that person received the email notification of the check out item

Thank You and More Power

**Comment by samotelf** [comment]
+1 (or at least be able to checkout to a location even if email notifications are enabled for that category)

**Comment by robinstacey007** [comment]
+1 ,  this would be very useful to us.

**Comment by samotelf** [comment]
I stand corrected:

In v4.6.6 - build 3926 (master) you can already checkout to location even if the category has "Require users to confirm acceptance of assets in this category." turned on.
What about Teams integration?

**Comment by tymik** [comment]
> +1
> 
> We use a common slack channel for notifications and I can't see a reason why notifications should be limited to checkouts to users.

^^ this ^^

+1 too

**Comment by ajsy** [comment]
it would be nice to send email notification to location manger when checking out asset to location

**Comment by sinichi19** [comment]
why closed?

**Comment by sinichi19** [comment]
still hopping ^__^

More Power Snipe-IT

**Comment by samfisher83** [comment]
If you notification when you check out to a location you can go to  app/Listeners/CheckoutableListener.php

Comment out this line
        if(! $event->checkedOutTo instanceof User) {
            return;
        }


and this line:

        if(!$event->checkedOutTo instanceof User) {
            \Log::debug('checked out to not a user');
            return;
        }

It would be nice if it was a feature, but this is a quick way to get notifications.

**Comment by samfisher83** [comment]
The part of the code the notifications are filtered is here:

CheckoutableListener.php:        

```

    if(! $event->checkedOutTo instanceof User) {
            return;
        }
```

You would just need to add your own function there to send an email or slack notification or what ever you want to do. Obviously it is a complete hack, but it isn't too hard to do.

**Comment by snipe** [comment]
> If the Location have assigned Manager that person received the email notification of the check out item

That gets pretty messy in terms of where we store those preferences.

**Comment by H264x** [comment]
Hi,

is there already some kind of solution for this?

Since I don't know anything about proper programming and can't/won't customize the scripts. 

I get around this by adding this to the specific person first and add a note, that it will be revoked, but still exists. The email goes out. Then I take it back and do it correctly.

**Comment by Callandt** [comment]
+1 Need this in my organisation.

When you check out an asset on a location -> mail to the assigned manager of that location
