### ISSUE TITLE
trying to import only users.

### ISSUE THREAD

**Issue by JasonDraneWork** [snipe/snipe-it#6419]
Following the template laid out in your documentation. I am attempting to use the cmd php artisan to import only users. 

here is the error i receive. 
======= Importing Items from /home/ubuntu/Employees.csv =========
 99/99 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%The following Errors were encountered.
Error: Item:  failed validation: {"Asset \"\"":{"model_id":["The model id field is required."],"asset_tag":["The asset tag field is required."]}}

Your model for users, does not state it needs asset tags nor model..clearly i am doing something wrong just not sure what?

**Comment by bricelabelle** [comment]
Try it like this:
php artisan snipeit:import --item-type user /home/ubuntu/Employees.csv

I'm actually working on this now. The item-type of "user" is not documented anywhere that I can find but it does appear to work. There is also not any documentation of which headings are required so it's trial and error.
