### ISSUE TITLE
Feature Request - Accessory Minimum Quantity 0 and not notify

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#6420]
**Server (please complete the following information):**
 - Snipe-IT Version v4.6.6
 - OS: [e.g. Ubuntu, CentOS] CentOS 7
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.1.24
--

**Is your feature request related to a problem? Please describe.**
Looking for a means to have a minimum quantity for an accessory of 0 (or maybe -1) so as to not be notified that we're out of stock for that specific accessory type. 

**Describe the solution you'd like**
If I set the quantity of an accessory ```Min. QTY``` to be 0 (more likely -1) that no flag is raised stating I'm at or below my minimum QTY. 

**Describe alternatives you've considered**
Simply ignoring the quantity alert and email notifications of supply issues for these accessories. 

**Additional context**

![chrome_2018-11-12_14-46-23](https://user-images.githubusercontent.com/14837699/48371385-bff1c100-e689-11e8-9ae8-137a2c25fc06.png)

For example, I only have one i1 Profiler accessory. 

![chrome_2018-11-12_14-47-43](https://user-images.githubusercontent.com/14837699/48371454-ec0d4200-e689-11e8-9328-9dd9f857a76c.png)

When it's checked out, great someone is color calibrating their monitor. I don't need to know that I have 0 of this accessory and am looking for a way to avoid bloating my alerts and email communications.

**Comment by Jarli01** [comment]
Email template showing the QTY. 

![outlook_2018-11-12_15-43-02](https://user-images.githubusercontent.com/14837699/48374066-b0767600-e691-11e8-8067-643882c52e99.png)

**Comment by tymik** [comment]
@snipe i would even like to mark it as a bug, not only a feature request, as at my place i have notifications for all items that have actual QTY<=5 - disrespecting the actual minimum QTY i have set

version I have:  Version v4.6.6 - build 3926 (master) 
i can also provide screens of that if needed.

**Comment by tymik** [comment]
@snipe i would even like to mark it as a bug, not only a feature request, as at my place i have notifications for all items that have actual QTY<=5 - disrespecting the actual minimum QTY i have set.
The issue does not appear if I have QTY>=6 for particular accessory.

version I have:  Version v4.6.6 - build 3926 (master) 
i can also provide screens of that if needed.

**Comment by Jarli01** [comment]
Please reopen this ticket.

**Comment by zlyczarny** [comment]
Still issue still occurs, any solution?
