### ISSUE TITLE
Full Multiple Company Support Permission

### ISSUE THREAD

**Issue by sinichi19** [snipe/snipe-it#6421]
**Server (please complete the following information):**
 - Snipe-IT Version  : 4.6.6
 - OS: Windows 10
 - Web Server: IIS
 - PHP Version 7.2.11

**Is your feature request related to a problem? Please describe.**
I want to enable the Full company support so our user can only view their asset in their company only.
But I dont want to give a super admin to the other staff who encoded and manage the asset details to view all the company. 
This is to protect or contain who can edit the settings or prevent to delete the data.

**Describe the solution you'd like**
If its possible that the Full Multiple Company Support is can enable in the user permission or in the groups permission 

**Additional Notes**
Or if we can set that the user is can only view the full details of the assigned asset or license

**Comment by jackka** [comment]
I've installed 4.6.6 and it seems has a bug with admin permissions - Snipe-IT does not show assets for admin permissions in "All assets" menu.
In 4.6.5 works normally and latest revision works well.

**Comment by snipe** [comment]
@jackka I'm unable to reproduce this locally. Can you provide screenshots to explain what you mean?

**Comment by paoloposo** [comment]
@snipe I believe I am experiencing the same bug as @jackka. Here are some details:

- I have enabled full company support
- I created some companies (say A and B)
- I created a "normal" (=non-admin) User U
- I created a Group G, which I have given the permission to view, create, edit and delete assets.
- I assigned User U to company A and added him to group G

Now, when I create assets which are assigned to company A, User U cannot see these under "All assets". The table there is empty. However, when I use a direct link (e.g. https://example.com/hardware/23), U can view and edit the asset as per his persmissions.

**Comment by paoloposo** [comment]
Also, this *does* work as expected with consumables.

**Comment by jackka** [comment]
Hello @snipe.
It is not reproducible as I described it. Sorry.
I have repeatedly noticed that assets disappear from "Assets view" and only internal button "refresh" gives a help. I didn't catch a moment when this disappearing happens.

**Comment by jackka** [comment]
Yes

**Comment by yk48** [comment]
still relevant

**Comment by moufpouf** [comment]
same problem.Version v4.9.4 - build 4437.

**Comment by Gnirav** [comment]
I have multiple company in @snipe and wanted set SMTP company wise, is this possible and if then how?
