### ISSUE TITLE
No HTTP resource was found that matches the request URI

### ISSUE THREAD

**Issue by underdpt** [snipe/snipe-it#6422]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
All tables are empty. In a newly installed instance, I can create any registry, but then I doesn't appear on the table (shows "No matching records found").
On the console it shows an error 404 when refreshing the tables, with the message:
`{"Message":"No HTTP resource was found that matches the request URI 'http://sitename.com:41234/api/v1/companies?order=asc&offset=0&limit=20'."}`

The site is listening on port 9000, and that is reflected on `.env` (`APP_URL=sitename.com:9000`) but if you look at the error sent to the browser, the port is not the same, so I think that's where the error is.

**To Reproduce**
Go to any listing/table on the site, it shows empty.

**Expected behavior**
It should show the items existing on the database.

**Screenshots**
N/A

**Server (please complete the following information):**
 - Snipe-IT Version Version v4.6.6 - build 3926 (master)
 - OS: Windows Server 2012
 - Web Server: IIS
 - PHP Version: 5.6.35

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox 
 - Version 63.0.1

**Smartphone (please complete the following information):**
N/A

**Error Messages**
`{"Message":"No HTTP resource was found that matches the request URI 'http://sitename.com:41234/api/v1/companies?order=asc&offset=0&limit=20'."}`

**Additional context**
Fresh install, only thing i can think of is that it's installed on port 9000.

**Comment by sinichi19** [comment]
I'm sure but in your port mapping in your Firewall is the port 80 is listening to port 9000?

**Comment by underdpt** [comment]
Yes, the firewall is open on port 9000 (have in mind that I can access the software, is only the table contents i'm missing).

I've tried APP_URL, but that's only for artisan commands, If I'm not mistaken.

**Comment by underdpt** [comment]
I've done a few tests and changed the server to listen on port 80, but the issue is still there, so nothing to do with that.

The error message says the app tries to load the listing on port  41234, I couldn't find this number anywhere on the code, any hints?

`{"Message":"No HTTP resource was found that matches the request URI 'http://sitename.com:41234/api/v1/companies?order=asc&offset=0&limit=20'."}`

**Comment by underdpt** [comment]
After further investigation, it seems that an as****e did put his project redirections on the ISS main configuration, applying them to all sites.

So, there was a global redirect over all */api/* requests that was causing this issue. I'm closing this as has nothing to do with Snipe-It.
