### ISSUE TITLE
Feature Request: "One person belongs more than one company".

### ISSUE THREAD

**Issue by jackka** [snipe/snipe-it#6423]
**Server (please complete the following information):**
 - Snipe-IT Version: **4.6.5**
 - OS: **ubuntu0.18.04.1**
 - Web Server: **Apache**
 - PHP Version: **PHP 7.2.10-0**

**Is your feature request related to a problem? Please describe.**
    I need to have person which would see assets more than one company in 
    restricted "FullCompanySupport" mode.

**Describe the solution you'd like**
   Developing something with many-to-many relationship between users and companies things.
   This is complicated feature development concerning some interfaces, import functionality and etc.

**Describe alternatives you've considered**
   No

**Additional context**
  I'm going to use it ( just locally in our company ) along with 
  substitute “Company” thing to “Cost Center” ( just fixing translations ).
  And I hope in the future we manage to develop real alone item like "Cost Center".

Thank you

**Comment by jackka** [comment]
For security reasons the new asset without given company name should receive company_id from the user who creates this asset.

**Comment by jackka** [comment]
yes

**Comment by heikoboehme** [comment]
urgently needed feature
