### ISSUE TITLE
GMAIL -SMTP Server support

### ISSUE THREAD

**Issue by rajeshgeeks** [snipe/snipe-it#6425]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Hello,

Looking to resolve google SMTP error issue.

SMTP configuration setup as below :

MAIL_DRIVER=smtp
MAIL_HOST=smtp-relay.gmail.com
MAIL_PORT=587
MAIL_USERNAME=YOURUSERNAME
MAIL_PASSWORD=YOURPASSWORD
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=asset@mydemosite.com.au
MAIL_FROM_NAME='Snipe-IT'
MAIL_FROM_ADDR=asset@mydemosite.com.au
MAIL_REPLYTO_NAME='Snipe-IT'

Error: Mail testing using General >>Test Mail :" Mail could not be sent."

laravel log:
[2018-11-16 02:11:00] production.ERROR: Swift_TransportException: Expected response code 250 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials m47sm264275iti.1 - gsmtp
" in /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:383
Stack trace:
#0 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(281): Swift_Transport_AbstractSmtpTransport->_assertResponseCode('535-5.7.8 Usern...', Array)
#1 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(270): Swift_Transport_AbstractSmtpTransport->executeCommand('RSET\r\n', Array, Array)
#2 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/Auth/XOAuth2Authenticator.php(55): Swift_Transport_EsmtpTransport->executeCommand('RSET\r\n', Array)
#3 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php(176): Swift_Transport_Esmtp_Auth_XOAuth2Authenticator->authenticate(Object(Swift_SmtpTransport), 'YOURUSERNAME', 'YOURPASSWORD')
#4 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(332): Swift_Transport_Esmtp_AuthHandler->afterEhlo(Object(Swift_SmtpTransport))
#5 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(118): Swift_Transport_EsmtpTransport->_doHeloCommand()

NOTE :I'm using gmail smtp server. And my credential is correct.

Thanks,

//Rajesh

**To Reproduce**
1. Go to 'Settings>Test Mail'
4. See error : "Mail could not be sent"

**Expected behavior**
Able to send email.

**Screenshots**
![image](https://user-images.githubusercontent.com/45085739/48594608-347b7700-e98c-11e8-979b-d2b3e4cae732.png)

**Server (please complete the following information):**
 - Snipe-IT Version :Version v4.6.6 - build 3926 (master)
 - OS: [e.g. Ubuntu, CentOS]CentOS CentOS Linux release 7.5.1804 (Core)
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version : PHP 7.1.23 (cli) (built: Oct 16 2018 14:29:46) ( NTS )

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  : 
 - Browser [e.g. chrome, safari] : chrome

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by sinichi19** [comment]
Sir assumed that your MAIL_USERNAME and MAIL_PASSWORD is correct
Kindly try to Replace your MAIL_HOST to =smtp.gmail.com

**Comment by rajeshgeeks** [comment]
Hi @sinichi19 ,

Thanks for the prompt response.
I have changed the settings as suggested but no luck. Still the problem persist.

Logs:
#69 {main}
[2018-11-16 04:01:34] production.ERROR: Swift_TransportException: Expected response code 250 but got code "535", with message "535-5.7.8 Username and Password not accepted. Learn more at
535 5.7.8  https://support.google.com/mail/?p=BadCredentials 34sm44660693pgp.90 - gsmtp
" in /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:383
Stack trace:
#0 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(281): Swift_Transport_AbstractSmtpTransport->_assertResponseCode('535-5.7.8 Usern...', Array)
#1 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(270): Swift_Transport_AbstractSmtpTransport->executeCommand('RSET\r\n', Array, Array)
#2 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/Auth/XOAuth2Authenticator.php(55): Swift_Transport_EsmtpTransport->executeCommand('RSET\r\n', Array)
#3 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php(176): Swift_Transport_Esmtp_Auth_XOAuth2Authenticator->authenticate(Object(Swift_SmtpTransport), 'rajesh', 'August2018')
#4 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(332): Swift_Transport_Esmtp_AuthHandler->afterEhlo(Object(Swift_SmtpTransport))
#5 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(118): Swift_Transport_EsmtpTransport->_doHeloCommand()
#6 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(443): Swift_Mailer->send(Object(Swift_Message), Array)
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(217): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(60): Illuminate\Mail\Mailer->send(Object(Illuminate\Support\HtmlString), Array, Object(Closure))
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(113): Illuminate\Notifications\Channels\MailChannel->send(Object(App\Models\Setting), Object(App\Notifications\MailTest))
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(89): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(App\Models\Setting), '49b7f732-1321-4...', Object(App\Notifications\MailTest), 'mail')
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(64): Illuminate\Notifications\NotificationSender->sendNow(Object(Illuminate\Database\Eloquent\Collection), Object(App\Notifications\MailTest))


Is there any working sample or demo tested with smtp.gmail.com earlier ?

//Rajesh

**Comment by sinichi19** [comment]
its your google account enabled the pop or smtp settings in your gmail? if yes you may use the https://snipe-it.readme.io/docs/common-issues or https://snipe-it.readme.io/docs/configuration

**Comment by jackka** [comment]
In my case, which is similar to yours (it seems) the problem was solved with changing mail driver to "mail" from "smtp".
and installing additional (sendmail) software at Snipe-IT server which works on Ubuntu 18.04.

Our Snipe-IT config is the following:

MAIL_DRIVER=mail
MAIL_HOST=smtp.<mailserver>.com
MAIL_PORT=587
MAIL_USERNAME=<account>@<mailserver>.com
MAIL_PASSWORD='<password>'
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=snipeit@<mailserver>.com
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=snipeit@<mailserver>.com
MAIL_REPLYTO_NAME='Snipe-IT'

I hope it helps you in some way.

**Comment by rajeshgeeks** [comment]
Hi @jackka ,
After your suggestion to change driver i can see success on SnipeIT email text. Nothing on log but still no email is received on my mail inbox.

![image](https://user-images.githubusercontent.com/45085739/48926336-f3451300-ef07-11e8-92ff-0123120f54e5.png)


my configuration is : 
# --------------------------------------------

MAIL_DRIVER=mail
MAIL_HOST=smtp-relay.gmail.com
MAIL_PORT=587
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=asset@xxxxxxxtap.com.au
MAIL_FROM_NAME='ASSET'
MAIL_REPLYTO_ADDR=asset@xxxxxxntap.com.au
MAIL_REPLYTO_NAME='Snipe-IT'

the reason i set username /password null is cause this is an group email id.

//Rajesh

**Comment by rajeshgeeks** [comment]
Resolved.

**Comment by jackka** [comment]
Nice to help You! :)

**Comment by BaronVIP** [comment]
Dear ，May I ask how to solve the problem? I also encountered the same problem. The email could be successfully tested, but the inbox could not be received.
