### ISSUE TITLE
Feature Request: Permission to view full details and Clickable Asset Tag

### ISSUE THREAD

**Issue by sinichi19** [snipe/snipe-it#6426]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.6
 - OS: Win10
 - Web Server: IIS
 - PHP Version 7.2.11

**Is your feature request related to a problem? Please describe.**
My request is please enable to click the asset tag when non admin log in and can view the full details of the assigned asset or software only,  

I configured to deny all the access for normal user to view only their assigned asset only and nothing more but they have only a limited details i think its much better if they can view also the full page

**Describe the solution you'd like**
hope this picture will help for what I requesting
<a href="http://tinypic.com?ref=307ucld" target="_blank"><img src="http://i68.tinypic.com/307ucld.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

and after click the asset tag can now view the full details

<a href="https://ibb.co/dZePaL"><img src="https://preview.ibb.co/c14qFL/full-view.jpg" alt="full-view" border="0"></a><br /><a target='_blank' 

Please ^___^

**Comment by sinichi19** [comment]
@EarlRamirez 

Hi Sir what do you think to my request any comment / suggestion or it's possible to make non admin can only view their assigned asset only and nothing more.

Best Regards and Thank You

**Comment by tymik** [comment]
+1, but as a configurable - admins may want or want not to give full details for users on assets deployed to them

**Comment by sinichi19** [comment]
@tymik  Thank you sir

**Comment by sinichi19** [comment]
still hopping to consider this request
Thank you

**Comment by sinichi19** [comment]
still hopping

**Comment by yk48** [comment]
@snipe Please regard this issue. Such feature is needed.

**Comment by sinichi19** [comment]
> @snipe Please regard this issue. Such feature is needed.

Thanks

**Comment by sinichi19** [comment]
And still hopping

**Comment by sinichi19** [comment]
2020 still hopping

**Comment by sinichi19** [comment]
still hopping ^__^

More Power Snipe-IT
