### ISSUE TITLE
Issue while setting up Snipe IT in IIS - related to Git access

### ISSUE THREAD

**Issue by hanamanthalli** [snipe/snipe-it#643]
I am trying to setup Snipe-IT on Windows 7 Professional 32 bit OS on IIS server 7.5

I have installed all the prerequired software as per the guidelines mentioned in the installation guide http://snipeitapp.com/documentation/installing-on-iis/

I am facing problem at this step:

Open C:\inetpub\wwwroot\snipe-it in Windows Explorer
Right Click and select Composer Install. This will install the dependencies. Once completed move to next step

On Selecting Composer Install few of the files gets installed for few more at the end it is asking for git user name and password.

Did Anybody faced such issue? If so did you find a solution for the same, if so please share the details it would be very helpful.

**Comment by florentchawki** [comment]
Yes it's your username and password for Github.com .
If you put them it will work .

Thank you
