### ISSUE TITLE
Migration Issue v3 to v4

### ISSUE THREAD

**Issue by ddarrund** [snipe/snipe-it#6431]
Hi,

I am trying to migrate from v3 to v4, I got this error below after the restoring the DB either from the sql dump or db backup, once I drop the table, it will create another error on another table and so on:

/var/www/snipeit$ php artisan migrate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

In Connection.php line 647:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oauth_personal_access_clients' already exists (SQL: create table `oauth_persona
  l_access_clients` (`id` int unsigned not null auto_increment primary key, `client_id` int not null, `created_at` timestamp null, `updated_at` t
  imestamp null) default character set utf8mb4 collate utf8mb4_unicode_ci engine = InnoDB)

In PDOStatement.php line 107:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oauth_personal_access_clients' already exists

In PDOStatement.php line 105:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oauth_personal_access_clients' already exists

**Comment by Jarli01** [comment]
Did you follow the process here: https://snipe-it.readme.io/v4.0/docs/upgrading-to-v4 ?

You need to put the application into maintenance mode and then run through a few more steps.

**Comment by ddarrund** [comment]
Hi,
 I have followed the process you mentioned above and still getting:

php artisan migrate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes


In Connection.php line 647:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oauth_personal_access_clients' already exists (SQL: create table `oauth_personal_access_clients`
   (`id` int unsigned not null auto_increment primary key, `client_id` int not null, `created_at` timestamp null, `updated_at` timestamp null) default character s
  et utf8mb4 collate utf8mb4_unicode_ci engine = InnoDB)


In PDOStatement.php line 107:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oauth_personal_access_clients' already exists


In PDOStatement.php line 105:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oauth_personal_access_clients' already exists
