### ISSUE TITLE
Remove Consumable Checkout

### ISSUE THREAD

**Issue by ks9389** [snipe/snipe-it#6435]
**Server (please complete the following information):**
 - Snipe-IT Version - Version v4.6.5 - build 3897 (master) Hosted

**Is your feature request related to a problem? Please describe.**
Accidentally checked out a consumable twice to a user. I have no way to remove one of the records, so my historical data is now incorrect.

**Describe the solution you'd like**
Ability to delete a consumable checkout record (effectively checkin)

**Describe alternatives you've considered**
I can get around it to delete the consumable and re-checkout the existing history. Worked in current scenario as I only had a short history. However, times/dates are incorrect and will be harder with a much larger history.

**Comment by citizenkepler** [comment]
We just encountered this issue as well.  I needed to correct a consumable issue, and now the user has a duplicate as I can not remove the other consumable. I have a snipe-hosted platform.

**Comment by citizenkepler** [comment]
I would like to add that if you delete the consumable, it stays in the user's account. When you click on the consumable you deleted, snipe-it throws an error as the consumable has been removed from the system but was not removed from the user.

**Comment by uberbrady** [comment]
@citizenkepler definitely reach out to support@snipeitapp.com to see if we can help. Worst-case scenario we can do a little bit of DB surgery for you.
