### ISSUE TITLE
Who has been breaking assets - reporting

### ISSUE THREAD

**Issue by papacucku** [snipe/snipe-it#6436]
#### Expected Behavior (or desired behavior if a feature request)

Not an issue or bug I would just like to learn how to run a report that will tell us who (in history) has been breaking the most chromebooks. We assign status when we check them back in of broken - intentional or broken - accident.  It would be nice to know which students have or are breaking the most.  We have users under locations so it would be nice to know if "the high school location" compares to another location as well.   I will try to see what I can figure out with the reporting but anyone that has already done this and has tips let me know. 

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by papacucku** [comment]
Sure.  Its more of a general reporting question no real updates.

**Comment by Nesteph** [comment]
If you do a Custom Asset Report and choose the options below (tweak as needed) and limit it to the specific model you are looking at, you'll get a csv that you can then open in Excel/Google Docs/etc and do some filtering/sorting/calculations on. I would use a pivot table for something like this myself. I've attached an example of a setup that could be used for that.
[Custom Asset Report.xlsx](https://github.com/snipe/snipe-it/files/2907633/Custom.Asset.Report.xlsx)


- Company
- Asset Tag
- Serial
- Location
- Status
- Assigned To
- Username
