### ISSUE TITLE
Users dashboard does not reflect view permissions

### ISSUE THREAD

**Issue by stbc** [snipe/snipe-it#6438]
**Server (please complete the following information):**
 - 4.6.6
 - Ubuntu
 - apache
 - 7

**Is your feature request related to a problem? Please describe.**
The dashboard view of a users does not reflect the navigation structure displays as based on permissions. Details: If a user logs in and he does not have the right to even view the consumables, the corresponding menu item is not displayed - this is what I would consider as expected behaviour. But on the dahsboard the consumables table is displayed, which could lead to confusion. See attached screenshot. Sam applies for all other items...

![grafik](https://user-images.githubusercontent.com/2520567/48759319-099e6500-eca3-11e8-9784-6ff8e3e116e4.png)

**Describe the solution you'd like**
If a user does not have the proper rights to view a certain category, it shouldn't be displayed on the dashboard.

**Comment by Jarli01** [comment]
This is because the user is able to see all items that are checked out to that user. In this case "Tester Testmann".

**Comment by morrow72** [comment]
Got the same problem in an installation with Full Multiple Companies Support.
I created 2 Companies and User Groups.
Users in one Group and access to one Company should only see Categories, Assets etc. for that specific Company. 
But the Dashboard shows ALL Categories or Asset Status even if they're from the other Company. 
It's just the Dashboard that shows this stuff. If i open List all Assets or Categories there are none.
There are no items checked out to any of these users.
Screenshot shows Dashboard of one user with NO access to categories or assets from the other Company where theses Assets and Categories are in.
![dashboard](https://user-images.githubusercontent.com/45624790/49507064-fa610f00-f87f-11e8-99e2-5acd6115f023.JPG)
Any help is appreciated
Rgds

**Comment by Jarli01** [comment]
@morrow72 are your users in the two separate companies superadmins?

**Comment by snipe** [comment]
@morrow72 We don't have a permission whereby a user can see assets but cannot see categories. Category > View as a permission is a little misleading. If you can see Assets or Asset Models, you will always be able to see Categories (as they are an attribute of categories), and categories are not bound by company. The Category > View permission really relates to the ability to see the listing in the left-side settings menu where people can see Acceptance, EULA, etc.

**Comment by morrow72** [comment]
@Jarli01 : no, none of all users have superadmin rights except the superadmin itself.
@snipe : Strange thing. While we are testing Multiple Companies Mode in our Test Environment I will delete the new Group and the new Users and re-setup them again Step by Step and then Test again. Maybe there is a wrong Setting I made
Thanks for your quick answer, appreciate that :-)

**Comment by morrow72** [comment]
Hi there. Unfortunately I still got a Problem, I think it's some kind of a Permission Issue.
As I said, I rebuilt the 2nd Company, re-setup users and groups. 

One Group has only little rights to just VIEW several things like assets, licenses, models, categories, custom fields, suppliers, manufacturers and locations. They even can't VIEW Companies. Users in this Group are set to be part of just this 2nd Company.

The 2nd Group has got some more rights to view, create or edit the above mentioned Parts of Group Permissions. 
But there are NO Admin or Super Admin Rights! 
Users in this Group are as well bound to just the 2nd Company. But still they can, for example, create a new Asset and select the 1st Company where this Asset should belong to. 

In the Assets Overview this User can see this Asset, even if it's set to belong to the other Company and another user who is in the User-Group with little rights can see this Asset as well?

How can I set the User Groups/Users to JUST see all Parts of the 2nd Company but NOT/NEVER see Parts of the 1st Company even can't create an Asset who could belong to the 1st Company?

Thanks in advance for your help.
Regards

**Comment by darshitvvora** [comment]
This is still relevant. If we enable Full Company Support an dcreate a Admin IN  specific company than the asset visibility is restricted properly but Dashboard shows count of all assets from all company. This experience is misleading and wron. Can you suggest solution for this?

**Comment by syssplgillz** [comment]
Having the same issue as well.

**Comment by NickBarssGHL** [comment]
This is still an issue. Doesn't seem secure when a user from any company can see asset counts on their dashboard for the entire database.

**Comment by Jarli01** [comment]
@NickBarssGHL is the true for all users or only for superadmins?

**Comment by NickBarssGHL** [comment]
@Jarli01 This is true of all users. I set full multi company support on, and created a company with a test user that is only an admin for the company. They can't see any assets or anything yet their dashboard contains numbers and statistics on assets not assigned to her company in any shape or form. 
Here is the dashboard for the user, with asset numbers clearly showing up that are assigned to different companies.
![image](https://user-images.githubusercontent.com/69014499/96922838-6782eb00-147e-11eb-8bfb-9c126a0169b9.png)

Here is the user's permission settings (set to admin, with everything else on inherit)
![image](https://user-images.githubusercontent.com/69014499/96923086-c5173780-147e-11eb-9ff3-ba9c78ae2299.png)

**Comment by snipe** [comment]
Only admins even see the dashboard tho, and super admins transcend full company support permissions.

**Comment by NickBarssGHL** [comment]
@snipe What I'm saying is the categories numbers appearing on the admin's dashboards are out of scope. Shouldn't the admin only be able to see the category numbers for the scope of their company?
