### ISSUE TITLE
FatalErrorException(e_error)

### ISSUE THREAD

**Issue by florentchawki** [snipe/snipe-it#644]
Hi Guys,

I had Snipe it running but decided to migrate to a new server with new domain.
Did update all necessary files / computer names / dns etc..run composer install and then:

![untitled](https://cloud.githubusercontent.com/assets/10992266/6622829/090c5866-c8d7-11e4-9cdb-231d7366fd63.png)

Can you please help ?

Regards

**Comment by florentchawki** [comment]
Running PHP 5.4 / COMPOSER INSTALL / IIS 7 / 2012 SERVER /  MARIADB.

Thank you 

(Imported the previous sql)

**Comment by snipe** [comment]
Grab the latest off of the develop branch and run composer install, or edit your `composer.json` Is using Sentry 2.1.* and then run composer update.
