### ISSUE TITLE
Can not create asset

### ISSUE THREAD

**Issue by RaoFahim** [snipe/snipe-it#6441]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Server (please complete the following information):**
 - Snipe-IT Version v4.2.0 build 3479 (gbf74bb1)
 - OS: [windows server 2012]
 - Web Server: [Apache]
 - PHP Version 7.2.3
--

Hey snipe i have been using your asset management system for a long time now with some additional tables in mysql linked with the tables of snipe it asset management. but suddenly i am unable to create assets. it is not showing any error on asset creation it just refreshes the page and nothing else. non assets are created.

can you kindly provide your views on this issue.

**Comment by mltmjoe** [comment]
For what it's worth:
Running version 5.4.35
Recently changed from self-installed to install from Git as suggested. This issue did not occur on the last version.

**Comment by RaoFahim** [comment]
i installed it on another server and it is working fine. thanks guys.
