### ISSUE TITLE
Drop down Currency Selection

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#6442]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.6
 - OS: [e.g. Ubuntu, CentOS] CentOS 7
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.1.24

**Is your feature request related to a problem? Please describe.**
Setting the currency for a location is less intuitive than it could be. All fields are manually filled in, or defaults. 

**Describe the solution you'd like**
Dropdown options for currency abbreviations, USD for US Dollars, EUR for Euros, GBP for Pounds, along with the other top country currency abbreviations and symbols. Russia, China etc who likely have their own abbreviations and symbols. 

**Describe alternatives you've considered**
Manually entering this information into the Localization settings.

**Comment by Jarli01** [comment]
Please reopen this feature request.

**Comment by snipe** [comment]
I'd be willing to accept a pull request for this, but I don't see us working on it any time soon.
