### ISSUE TITLE
Import Issue - Model ID field required

### ISSUE THREAD

**Issue by erinFTW** [snipe/snipe-it#6443]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**
CSV asset imports are not going through. Upon import attempt I am given the `Asset "[asset name]": The model id field is required.` error. All fields are properly mapped. Sample CSV:

`Company,Network,Install Date,Item Name,Serial Number,Category,description,model id,model number,model name,IP address,MAC Address,Wireless MAC,switch port,location,support type,support contract number,support contract expiration,notes,asset tag
Company Name,Network Name,2/27/2014,CHSJISW01-01,FOC18010AAT,Switch,null,c2960x,c2960x,Cisco-2960X Core Switch,127.0.0.1,############,############,1,MDF 1st Floor,null,null,NULL,null,chmar0001`

**Screenshots**
![image](https://user-images.githubusercontent.com/43587921/48797108-f0a7ab00-ecc6-11e8-8d6a-aa5e0ca5c34d.png)

![image](https://user-images.githubusercontent.com/43587921/48797408-ad017100-ecc7-11e8-997a-4456a755ec9b.png)

**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.6 build 3926
 - OS: CentOS
 - Web Server: Apache
 - PHP Version: 7.1.23

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 70.0.3538.102 x64

**Error Messages**
`Warning Some Errors occured while importing`

**Additional context**
- Is this a fresh install or an upgrade? Fresh install
- What OS and web server you're running Snipe-IT on: CentOS - Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way. No other issues
- Indicate whether or not you've manually edited any data directly in the database. No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by yuanhanglinux** [comment]
I have a similar problem, after I imported csv file , click process,   I find  only have a few filed  in "imported field"  
![image](https://user-images.githubusercontent.com/35515498/48846566-6486a800-edda-11e8-8775-1a0f96b79a59.png)
Dose anybody can tell me how to add the field in "import field",thanks.

**Comment by yuanhanglinux** [comment]
![image](https://user-images.githubusercontent.com/35515498/48846837-01494580-eddb-11e8-8037-30b56f2c6e6c.png)
In "import field" , I can't find "id" field,  I don't know why .

**Comment by EarlRamirez** [comment]
this may help you
https://github.com/snipe/snipe-it/blob/master/app/Importer/import_mappings.md

**Comment by yuanhanglinux** [comment]
@EarlRamirez  Thank you very much.

**Comment by erinFTW** [comment]
In my case, all the mappings are correctly assigned for Assets

**Comment by erinFTW** [comment]
@5quirrel derp. That worked lol. For some reason it's not importing my custom fields though. They are in the CSV and they are being mapped in the import, but they're not actually importing.
![image](https://user-images.githubusercontent.com/43587921/49031773-88e2db80-f170-11e8-9490-a637ab857b55.png)

**Comment by erinFTW** [comment]
The data looks like it's importing, I can run an asset export and the data is there, however it's not displaying in the Asset view.

**Comment by erinFTW** [comment]
I managed to fix the issue. I had not assigned the Fieldset to all models. Working now. Thank you for the assist!

**Comment by 5quirrel** [comment]
@erinFTW no worries, importing can be finicky the first time

**Comment by newgithubguy** [comment]
> I managed to fix the issue. I had not assigned the Fieldset to all models. Working now. Thank you for the assist!

Where do I change that setting?  I am having the same issue.
