### ISSUE TITLE
How do I adjust the allowed filetypes???

### ISSUE THREAD

**Issue by rp-tech** [snipe/snipe-it#645]
When I go to attach a file, for example, a zip file containing a license file to one of our software licenses, it tells me the filetype is not allowed.

I checked the php config files but I do not see mimes.php anywhere?

Is there a specific configuration file that holds this setting? I did not see it in the documentation anywhere.

Please advise,

Thanks!

**Comment by snipe** [comment]
File types are not a configurable option at this point. If you change them in the model, your changes will be overwritten any time we update that file. What mime type were you looking to add?

**Comment by rp-tech** [comment]
Right now I'm trying to upload a 20 KB zip file, which contains a .LIC file for our AV software, and an email (.msg) file containing the discussion surrounding the purchase.

It would be nice if this were a configurable option.

Can you point me to the correct PHP file for now so I can (temporarily) allow myself to upload it?

**Comment by snipe** [comment]
It would be in the licenses model.

**Comment by rp-tech** [comment]
Hmm, I checked app/models/License.php and LicenseSeat.php, I don't see any code pertaining to mime / file types?

**Comment by snipe** [comment]
I already pushed this out to the develop branch.

**Comment by rp-tech** [comment]
Oh, I see.. app/controllers/admin/LicensesController.php

Thank you!
