### ISSUE TITLE
Avatar image broken despite already having set APP_URL

### ISSUE THREAD

**Issue by EdenResident** [snipe/snipe-it#6450]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The avatar image is broken (not showing) even though I have set the APP_URL correctly and I have already restarted the server. In the 1st screenshot, the round avatar next to Delete Avatar is showing correctly but the avatar on the top right (next to my username) is broken. BTW, my site is installed on port 8080.

The URL in the screenshot is (sorry, this IP is local so you can't access it)
_http://172.21.132.73:8080/snipe-it/public/account/profile_
The APP_URL is
_APP_URL=http://172.21.132.73:8080/snipe-it_

If  I do right-click on the broken image, the IMG URL is showing up as 
_http://172.21.132.73:8080/snipe-it/uploads/avatars/dinh-ton.jpg_
However, the actual image is stored in this link (there's an extra **_public_** folder in there)
_http://172.21.132.73:8080/snipe-it/public/uploads/avatars/dinh-ton.jpg_
(this one displays just fine)

Also, another page with a broken image is the View Asset page with the broken QR code (screenshot #2). The (broken) IMG URL is 
_http://172.21.132.73:8080/snipe-it/hardware/3/qr_code_

**To Reproduce**
As described, the image is broken right from the top bar.
For the QR image, go to any View Asset page.

**Expected behavior**
Expect the uploaded avatar and the generated QR image to show up.

**Screenshots**

![image](https://user-images.githubusercontent.com/40486966/48928958-ab79b800-ef16-11e8-95c1-7698590651c7.png)

![image](https://user-images.githubusercontent.com/40486966/48929167-96058d80-ef18-11e8-93bd-e888dee43616.png)

**Server (please complete the following information):**
 - Snipe-IT Version v4.2.0 build 3479 (gbf74bb1)
 - OS: Windows
 - Web Server: IIS 7 (PHP)
 - PHP Version: 5.6.25

**Desktop (please complete the following information):**
 - OS: Windows 8
 - Browser Chrome
 - Version 70.0.3538.102 

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? Fresh Install with WAMP stack.
- What OS and web server you're running Snipe-IT on: Windows 2008 R2, IIS 7, PHP
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual
- Include what you've done so far in the installation, and if you got any error messages along the way. Nothing, except for editing the .env file.
- Indicate whether or not you've manually edited any data directly in the database. No.

My Snipe-It is installed in the same webserver as a couple other web sites (WMAP stack). Local path is D:\wamp64\www\snipe-it

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by sinichi19** [comment]
try to remove in you APP_URL=http://172.21.132.73:8080
w/o the /snipe-it

**Comment by EdenResident** [comment]
sinichi19, I did what you said but the avatar is still broken. This time, the IMG URL is
http://172.21.132.73:8080/uploads/avatars/dinh-ton.jpg
(ie, the snipe-it folder is gone from the URL).

If I can somehow get the **_public_** folder to show up in these links, everything would be fine again.
