### ISSUE TITLE
No user notes in the database after import from .csv file.

### ISSUE THREAD

**Issue by jackka** [snipe/snipe-it#6452]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
   No user notes in the database after import from .csv file.
==============
**To Reproduce**
1. Prepare .csv file [users4import-github.csv.txt](https://github.com/snipe/snipe-it/files/2610821/users4import-github.csv.txt) with the following data fields:
Employee Number,First Name,Last Name,Username,email,activated,Department,Location,Notes,Company,Job Title
1. Do import process.
1. Check users list in UI, check in the database.
1. No notes of users at all.

**Expected behavior**
   Notes imported with users successfully.

**Screenshots**
<img src="https://user-images.githubusercontent.com/6271335/48944564-4df66300-ef38-11e8-9519-97f4b97f7c36.png" width="300" ><img src="https://user-images.githubusercontent.com/6271335/48945804-c0694200-ef3c-11e8-8f24-b27738412206.png" width="350" >

**Server (please complete the following information):**
 - Snipe-IT Version **4.6.6**
 - OS: [e.g. Ubuntu, CentOS] **Ubuntu 18.04**
 - Web Server: [e.g. Apache, IIS] **Apache**
 - PHP Version **PHP 7.2.10**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] **Win10**
 - Browser [e.g. chrome, safari] **Vivaldi**
 - Version [e.g. 22] latest **2.1.1337.51 (Stable channel) (32-bit)**

**Smartphone (please complete the following information):**
no

**Error Messages**
no

**Additional context**
no

**Comment by jackka** [comment]
In "develop" branch (5.4.35) it fixed

**Comment by snipe** [comment]
@dmeltzer do you have a moment to take a look at this?

**Comment by jackka** [comment]
yes

**Comment by jackka** [comment]
Fixed by 1e1d32d commit
