### ISSUE TITLE
Email alert for requestable assets

### ISSUE THREAD

**Issue by Mynty100** [snipe/snipe-it#6453]
**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.6
 - OS: Linux Mint 18.3
 - Web Server: Apache
 - PHP Version: 7.1.22

**Is your feature request related to a problem? Please describe.**
Currently, no email notification is sent when a requestable asset is requested.

**Describe the solution you'd like**
Email alerts with what has been requested and by whom with a button to approve or deny this. This emails the requestor with an approved or deny email. 
If approved and email is a link is sent to alerts which takes you to the checkout page all set up ready to just click check out.

**Describe alternatives you've considered**
having to keep an eye on the dashboard. Staff call/email us after they request the asset. 

Thanking you,
Mynty.

**Comment by tymik** [comment]
+1, also slack notification (with ability to select where these notifications should go)

**Comment by Mynty100** [comment]
No one ever got back to us on this. Please advise.

**Comment by bwd-sys** [comment]
Could you please reconsider this? Ideally, the same recipients of asset's check out and check ins should also receive the asset requests.

**Comment by JackPo** [comment]
+1, would be great to have this.

Would additionally love to have the option of making requestor the manager (which is already synced from LDAP).

**Comment by gertz22** [comment]
+1 for me. notify admins or manager about asset request is important

**Comment by bbacani** [comment]
+1
