### ISSUE TITLE
Checking out an asset to a user with multiple locations

### ISSUE THREAD

**Issue by EdenResident** [snipe/snipe-it#6458]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.2.0 build 3479 (gbf74bb1)
 - OS: Windows
 - Web Server: IIS 7 (PHP)
 - PHP Version: 5.6.25

**Is your feature request related to a problem? Please describe.**
This feature has been suggested in these posts #5333, #3899, #2196. Seeing that there's a demand for this feature, I would like to suggest it again. 

In my organization, a user may have multiple locations assigned to him. For example, my IT guy, John, is responsible for 4 different data centers, beside the Main Office where he typically works. Right now, when an asset is checked out to John, its location is set as Main Office through inheritance and it cannot be changed. So, if John takes it to Data Center A for installation, there's no way we can track that.

**Describe the solution you'd like**
When checking out an asset, beside the assigned user, we'd like to also set the location. Now, I understand the rationale behind a strong coupling between users and locations but in real life, a user may have multiple assigned locations so a one-to-one relationship doesn't fully address this.

To retain the strong coupling, we can assign a user to multiple locations (not just his default location). That way, when checking out, we can only select among the locations assigned to him.

**Describe alternatives you've considered**
Right now, to get around this, when John takes the asset to Data Center A, we have to make him "check-in" to A. This allows us to track the asset-location but there's 2 issues:
- no one is currently set as responsible for it (should be John)
- the asset should be no longer deployable, but it still is because it has been "checked-in".

Thank you in advance for reading.

**Comment by 5quirrel** [comment]
In your example why don't you check it out the item directly to a "Data Centre A" location instead?

Personally I wouldn't really consider it deployed to the user anymore after it's installed in a separate facility?

**Comment by EdenResident** [comment]
Hi 5quirrel, if I did that, I wouldn't be able to know if it's John or Jack who took it to Data Center A. If it gets lost or broken, I wouldn't know who to blame. Also, even though it's installed at Data Center A, it's John who's still regularly using and maintaining it, ie. it's still "deployed" to him just as any other assets that are deployed to him but are sitting at his main location (Main Office).

**Comment by tamws27** [comment]
I did a hack to fix this in 4.9.2, please have a look to: https://github.com/snipe/snipe-it/issues/2196
