### ISSUE TITLE
Feedback: filter by category

### ISSUE THREAD

**Issue by rp-tech** [snipe/snipe-it#646]
It took me quite a few steps to figure out how to actually filter the assets by category.

Perhaps in the future an easier method of doing this can be added to the UI.

Right now, the steps are as follows:

1. Click on Assets
2. Click Asset Categories
3. Click on the little number under the Assets column to display assets under that category - it is just not a very obvious method of trying to accomplish this.

Maybe there can be a fast 'filter by category' option added to the existing Asset views - i.e. Deployed, Ready to Deploy, Pending, and List All should all have an option to sort *and* filter by type, this would be supremely useful.

Further, under the Asset category name, you should be able to just click on the category name itself i.e. 'Desktops' and not have to click the little number in the assets column to bring up those type of assets.

Regards,

**Comment by madd15** [comment]
The latest on the develop branch will allow for the category column to be shown and sorted
![alt](http://i.imgur.com/ch1LDSL.png)
![alt](http://i.imgur.com/gbbXOhl.png)
