### ISSUE TITLE
[Feature Request] Initiate bulk checkout from assets list

### ISSUE THREAD

**Issue by paoloposo** [snipe/snipe-it#6462]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.6 build 3926 (g1a10aa0dd)  
 - OS: Debian
 - Web Server: Apache
 - PHP: 7.0.30-0+deb9u1

**Is your feature request related to a problem? Please describe.**
Bulk checkout is too complicated. For example, it's not possible to search for assets and checkout all results. Instead you have to select each asset from a tiny dropdown.

**Describe the solution you'd like**
In the assets view, there are already checkboxes for each entry as well as an action selector at the top. I suggest adding another action there, "Bulk checkout", which when activated redirects you to the existing bulk checkout page, but with the dropdown already filled in with whatever you selected in the assets list.
This would be an improvement because you can leverage the already implemented searching and filtering mechanisms.

**Describe alternatives you've considered**
\--

**Additional context**
\--

Cheers,
Paolo

**Comment by tymik** [comment]
+1

**Comment by apbutle** [comment]
This would be amazingly useful

**Comment by paoloposo** [comment]
it is.
