### ISSUE TITLE
Search within "Users" doesn't allow to search by Company name

### ISSUE THREAD

**Issue by jackka** [snipe/snipe-it#6464]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

Search within "Users" doesn't allow to search by Company name
===========

**To Reproduce**
1. Click "Settings" -> "Companies" <img src="https://user-images.githubusercontent.com/6271335/49145758-8ff51f80-f311-11e8-9824-db8289e10049.png" width="250">
1. Copy any company name <img src="https://user-images.githubusercontent.com/6271335/49146244-c97a5a80-f312-11e8-8564-b18fdd08db81.png" width="400">
1. Click "People" <img src="https://user-images.githubusercontent.com/6271335/49146128-8ae4a000-f312-11e8-9bc3-75d8fb80f14a.png" width="300">
1. Click to the "Search" field <img src="https://user-images.githubusercontent.com/6271335/49146561-75bc4100-f313-11e8-8f34-319d44982580.png" width="300">
1. Paste the copied company name into the search field
1. Blank search results we have. <img src="https://user-images.githubusercontent.com/6271335/49146796-f8450080-f313-11e8-8a72-1f3cf9be56b6.png"  width="300">

**Expected behavior**
List of people we are searching for 
with the company name that they are connected should be displayed.
|
This **v5.0.0-pre - build 3866** build of develop branch allows to get around the above bug with list of people in certain company on the "Companies" page.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version  **4.6.5** -> **4.6.6** -> **v5.0.0-pre - build 3866**
 - OS: **Ubuntu 18.04**
 - Web Server: **Apache**
 - PHP Version **7.2.10**

**Desktop (please complete the following information):**
 - OS: **Win10**
 - Browser **Vivaldi**
 - Version **2.1.1337.51 (Stable channel) (32-bit)**

**Smartphone (please complete the following information):**
nope

**Error Messages**
nope

**Additional context**
nope

Thank you

**Comment by snipe** [comment]
This is fixed on develop and will be in the next release.
