### ISSUE TITLE
[Feature request] Slack integration for licences expiration

### ISSUE THREAD

**Issue by vladonexp** [snipe/snipe-it#6465]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.6
 - OS: [e.g. Ubuntu, CentOS] CentOS 7.0
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.2

**Is your feature request related to a problem? Please describe.**
Great product but we're missing one crucial option: Slack integration for licenses expiration notices. That would spare us a lot of hassle! Many thanks.

**Describe the solution you'd like**
Add an option to what should be sent to Slack or via email?

**Describe alternatives you've considered**

**Additional context**

**Comment by tobias-mierzwa** [comment]
Would be still awesome, if there is an integration for rocket chat.

**Comment by stbc** [comment]
Well, this actually works right away. Just create an intergration in RC, customize the fancy parts and copy the webhook url into the Snipe-IT Slack configuration. Works. ;)

**Comment by tobias-mierzwa** [comment]
Thanks for that, its working perfect :-)
