### ISSUE TITLE
 php artisan key:generate failure

### ISSUE THREAD

**Issue by willxd42** [snipe/snipe-it#6472]
Trying to set up for installation following this guide

[https://snipe-it.readme.io/docs/generate-your-app-key](https://snipe-it.readme.io/docs/generate-your-app-key
)
```

Warning: require(/Users/will/Desktop/Projects/snipe-it/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /Users/will/Deskt
op/Projects/snipe-it/bootstrap/autoload.php on line 17

Fatal error: require(): Failed opening required '/Users/will/Desktop/Projects/snipe-it/bootstrap/../vendor/autoload.php' (include_path='.:') in /Users/will/Des
ktop/Projects/snipe-it/bootstrap/autoload.php on line 17
macs-MBP:snipe-it will$


```

whe i run ` php artisan key:generate`

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/installation-issues#section-warning-requirebootstrapvendorautoloadphp-failed-to-open-stream-no-such-file-or-directory
