### ISSUE TITLE
Bar-code Scanner

### ISSUE THREAD

**Issue by jmartins1** [snipe/snipe-it#6476]
Issue:
When using Bar-code scanner, you must first click in the "Lookup by Asset Tag" field for SnipeIT to process the request and search inventory.

Expected:
SnipeIT should accept the input and search inventory regardless of active field; you shouldn't have to select the "Lookup by Asset Tag" field.

![2018-12-04_9-41-14](https://user-images.githubusercontent.com/31219479/49458061-468d5000-f7a9-11e8-940c-0cbd67c5a719.jpg)

**Comment by 5quirrel** [comment]
Most barcode scanners simply function as keyboard emulators. Snipe-IT has no way to distinguish input from the barcode scanner vs from the keyboard.

You wouldn't want all keyboard input to be hijacked and input to that field, and if it was possible, it would be frustrating for it to be hijacking the scanner's input constantly. Personally, I use a scanner to populate every field I can when inputting new items, and I'm not sure how you could logically have it programmed to distinguish between a lookup and data entry task.

I can think of one way this could be achieved, but it's still messy. If there was a keyboard shortcut configured for that field within Snipe-IT you could then prepend the required keystroke to shift focus to that field before the data in the scanner's programming. You'd still hamstring yourself using the scanner for inputting data in other fields, or even in to other applications though.

**Comment by hixair** [comment]
A shortcut would be a good start, event if it's not implemented to the scanner, it would be easier than having to mouse and click the field.
I usually use Tab to move between fields, maybe the focus could be tweaked so that it first highlights the lookup field when pressed (this is how it used to work at my previous work, tab/scan was a habit to get)

**Comment by jmartins1** [comment]
Hmm, I would imagine that it's possible to program an option in SnipeIT to go into a "QR Scanner" mode allowing the scanner to act as the primary input tool. Having to click the field each time kind of defeats the purpose of the scanner. Currently, I find it way faster to simply type in our 4 digit codes. Granted if you have a long code the scanner would be easier.

**Comment by snipe** [comment]
So we actually already kind of do that (or we did - might be a regression), just not on pages with forms on them, since the more common use case is that when a form page is open, the actual keyboard form should be the one with focus.
