### ISSUE TITLE
Change Favicon Snipe IT v2.1.0-55

### ISSUE THREAD

**Issue by mariomasa** [snipe/snipe-it#6478]
#### Expected Behavior (or desired behavior if a feature request)
I upload my new favicon.icon to the folder ".../public/", I refresh the browser and I expected the new favicon will substitute the older one.

-----

#### Actual Behavior

Nothing happens

-----

#### Please confirm you have done the following before posting your bug report:

- [YES ] I have enabled debug mode 
- [ YES] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? fresh install
- Version of Snipe-IT you're running. v2.1.0-55
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on; Debian 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
@mariomasa That sounds like a browser cache issue. We don't do anything special with the favicon, especially not in that version.

**Comment by patelcsobeys** [comment]
@mariomasa; Clear browser cache and you should be ok. I had the same issue but it got fixed after clearing browser cache.
