### ISSUE TITLE
LDAP sync is deactivating users

### ISSUE THREAD

**Issue by dedenelogic** [snipe/snipe-it#6480]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Two admin users in Snipe IT have been complaining that they cannot log in recently.
- We go into Snipe IT and see that their account is deactivated.
- This started happening in version 4.6.5 so we updated to 4.6.6 - issue persisted.
- After digging, we noticed that every time we run a LDAP sync those two users are deactivated.
- Other users are not effected.
- We have toggled "LDAP Active Flag" to "yes", but the issue remains.
- We can reproduce this without fail using the following procedure...

**To Reproduce**
1. Go to 'People'
2. Confirm that the two users are activated (can log in). 
3. Click on 'LDAP Sync'
4. Click on 'Synchronize'
5. Wait for sync to finish successfully
6. Go to 'People'
7. Confirm that the two users are deactivated (cannot log in).
8. Click on "Update" for those users.
9. Check "This user can login"
10. Click "Save"
11. The users can now log in again .

**Expected behavior**
1. Syncronise LDAP
2. Users are not deactivated.

**Screenshots**
**Before LDAP sync:**
![snipe-it-before](https://user-images.githubusercontent.com/45637528/49536991-d01a4c00-f895-11e8-90c8-a7bb8106d351.PNG)
**After LDAP sync:**
![snipe-it-after](https://user-images.githubusercontent.com/45637528/49537013-d90b1d80-f895-11e8-821c-33c91aa8e959.PNG)

**Server (please complete the following information):**
 - Snipe-IT Version : Version v4.6.6 - build 3926 (master)
 - OS: [e.g. Ubuntu, CentOS] : CentOS Linux release 7.5.1804 (Core)
 - Web Server: [e.g. Apache, IIS] : Apache httpd.x86_64 2.4.6-80.el7.centos
 - PHP Version : PHP 7.1.17

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Windows 10
 - Browser [e.g. chrome, safari] : Chrome and others
 - Version [e.g. 22] : Chrome Version 71.0.3578.80

**Error Messages**
- WITH DEBUG TURNED ON - no error messages
- If a stacktrace is provided in the error, include that too. - None
- Any errors that appear in your browser's error console. - None
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - NA
- Include any additional information you can find in `storage/logs` and your webserver's logs. - NA

**Additional context**
- Is this a fresh install or an upgrade? : Fresh install about a user in production
- What OS and web server you're running Snipe-IT on : see above
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) : Git
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - No I haven't

- We do see any difference in the user properties that may be causing the LDAP sync users to be deactivated.  My account is set up the same way as theirs.

**Comment by dedenelogic** [comment]
After disabling the "Store Password Using Reversible Encryption" option in Active Directory for the two affected users, the problem was resolved.  Thank you.

**Comment by snipe** [comment]
@VanillaNinjaD nice sleuthing - thanks!
