### ISSUE TITLE
LDAP sessions don't expire

### ISSUE THREAD

**Issue by rklingaman** [snipe/snipe-it#6482]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When I log in as LDAP user session never expires even on restart of computer. When I log in as local admin then session expires like it should.

**To Reproduce**
1. Log in as LDAP User.
2. Session never expires

**Expected behavior**
I would expect the LDAP session to expire

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: CentOS Linux release 7.5.1804 (Core)
 - Web Server: apache
 - PHP Version 7.2.12

**Desktop (please complete the following information):**
 - OS: Windows 10 LTSB 1607
 - Browser Chrome or Firefox
 - Version chrome:70 firefox:63.0.3

**Error Messages**
No Error Messages

**Additional context**
- Fresh Install
- No database modified
- Installed via GIT
- I have adjusted the session settings in .env and they work correctly with local accounts.

**Comment by snipe** [comment]
Are you logging out as the LDAP user?  What do you have for `SESSION_LIFETIME` and `EXPIRE_ON_CLOSE` in your env?

**Comment by snipe** [comment]
We don’t treat LDAP sessions any differently than local user sessions, so I honestly don’t have any idea why this would be happening. (You can see it in the code yourself, in the LoginController.) We basically check to see if LDAP is enabled, and if it is, try to auth against the LDAP server, and then if it finds a valid match, continues with auth as normal. There’s nothing special about an LDAP session as far as Snipe-IT goes.

**Comment by rklingaman** [comment]
Thanks for getting back to me. I used the storage inspector on Firefox to look at the Cookies when logged in as local admin and as a LDAP admin account. For the LDAP user account there is an extra cookie as remember_web_. 

Would this be what is causing it to not log out?

![snipe it sessions](https://user-images.githubusercontent.com/34689706/49748440-e6902100-fc62-11e8-8450-d73eb210d0c8.PNG)

**Comment by rklingaman** [comment]
I should also point out when deploying Grafana separate open source product I had some issues with this but then I found they have a setting called:

login_remember_days
The number of days the keep me logged in / remember me cookie lasts.

Changing that setting to a value of 0 fixed my issue there. Is there such a setting in Snipe IT for that?

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/configuration#section-optional-session-settings

Shouldn't affect LDAP users differently than local users though.

**Comment by rklingaman** [comment]
Can you confirm in your environment that if "remember me" is not checked then there is no remember me cookie?

**Comment by rklingaman** [comment]
**Behavior with Local Login:**
In my environment if I log on locally without "remember me" checked then I don't see a remember_web cookie. If i check it then I do see the rember_web cookie

**Behavior with LDAP LOGIN:**
No matter if I check or unchecked that box it sets a remember_web cookie so it seems the issue is that the remember me checkbox is not working correctly with LDAP. (defaults to always on)

Is there a method set that to always off?

**Comment by Cidwill** [comment]
Did you ever find a solution to this problem rklingaman?  We are encountering the exact same behaviour when using LDAP.

**Comment by rklingaman** [comment]
No we never did find a solution just kind of dealing with it and accepting the security risk of it.

**Comment by Cidwill** [comment]
I appreciate the response rklingaman.

**Comment by kcoyo** [comment]
@rklingaman @Cidwill Sorry to necropost, but did either of you find a workaround?

**Comment by ivenemark** [comment]
I am having the same issue with this however I am not using LDAP. Using local login. 

Appreciate if someone can give their 2 cents for this. Here's my ENV config looks like.

 --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_DRIVER=file
SESSION_LIFETIME=1440
EXPIRE_ON_CLOSE=true
ENCRYPT=false
COOKIE_NAME=snipeit_session
COOKIE_DOMAIN=null
SECURE_COOKIES=false
API_TOKEN_EXPIRATION_YEARS=15

**Comment by ivenemark** [comment]
> I am having the same issue with this however I am not using LDAP. Using local login.
> 
> Appreciate if someone can give their 2 cents for this. Here's my ENV config looks like.
> 
> # OPTIONAL: SESSION SETTINGS
> # --------------------------------------------
> SESSION_DRIVER=file SESSION_LIFETIME=1440 EXPIRE_ON_CLOSE=true ENCRYPT=false COOKIE_NAME=snipeit_session COOKIE_DOMAIN=null SECURE_COOKIES=false API_TOKEN_EXPIRATION_YEARS=15

Hi All. nevermind this. I have found what's causing. It was my browser auto refresh. That's why my session didn't expire. Thank you!
