### ISSUE TITLE
Department only can have one location assigned

### ISSUE THREAD

**Issue by stbc** [snipe/snipe-it#6486]
**Server (please complete the following information):**
 - 4.6.6. 
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version: 7

**Is your feature request related to a problem? Please describe.**
Departments only can have one location. 

**Describe the solution you'd like**
It would be great if a department could be assigned to more than one location.

**Describe alternatives you've considered**
./.

**Additional context**
./.

**Comment by sabait** [comment]
Why not just create two departments?
Department 1 - Location A
Department 1 - Location B

**Comment by stbc** [comment]
That would be sort of an ugly hack ;) Works but is not what I am looking for. You can not get cummulated values concering licence use, assets...

**Comment by stbc** [comment]
I would consider it relevant as a feature request..

**Comment by stbc** [comment]
This need some love... :/

**Comment by stbc** [comment]
Would still love to see that
