### ISSUE TITLE
Show Recursive Asset Assignments Under User Assignments

### ISSUE THREAD

**Issue by rpesta** [snipe/snipe-it#6489]
Context: We have a handful of assets assigned to our users, including "stationary" equipment (phones, monitors, etc) and non-stationary equipment (mouse, keyboard, etc). If a user changes desks, they will take their mouse and keyboard but not their monitors or deskphone, obviously.

Issue: We want to assign a phone or monitor to a desk itself. So an asset to asset assignment. Currently, that recursive asset is not visible in the users asset page.

Observed functionality: If I assign a phone to a desk and a desk to a user, under the user's assigned assets page, it only shows the desk, NOT the phone.

Desired functionality: If I assign a phone to a desk and a desk to a user, under the user's assigned assets page, it should show BOTH the desk and the phone.

**Comment by rpesta** [comment]
Still relevant.

**Comment by rpesta** [comment]
Yes still relevant

**Comment by rpesta** [comment]
Still a relevant recommendation.

**Comment by mmorais-idealsumario** [comment]
I second the request, not just for users, but also for locations and possibly all types of objects as well. If asset A is assigned to asset B, assigned to user C in location D, when listing assets in location D, all these objects should be listed.

This is in someway related to issue #7203, which I'm currently attempting to give a shot at resolving.

**Comment by valentyntu** [comment]
Hi guys, I'm going to implement the functionality requested by @rpesta. My colleagues also need it. Assets assigned to the other assets will be shown in the user's assets for admins, in "Print all assigned" and when the user views the account. It will be configurable in general settings.

**Comment by rpesta** [comment]
Yes still relevant.

**Comment by rpesta** [comment]
Yes, still a desired request.

**Comment by rpesta** [comment]
Still relevant.

**Comment by valentyntu** [comment]
@rpesta my [PR](https://github.com/snipe/snipe-it/pull/7293) was finally merged a month ago, so this feature is going to be included in some future releases. I guess you can close this thread.
