### ISSUE TITLE
Consumables - Minimum Quantity Alert

### ISSUE THREAD

**Issue by jmartins1** [snipe/snipe-it#6495]
Issue:
Consumables, minimum quantity alert producing alert before minimum quantity threshold has been met.

Expectation:
Alert produced only when minimum threshold has been met.

![quantityalert](https://user-images.githubusercontent.com/31219479/49759524-3a106800-fc7f-11e8-9fb4-7fd700c07bcb.jpg)

**Comment by 5quirrel** [comment]
@jmartins1 it does say "below or almost below"

The buffer is configurable under **Update Alert Settings > Inventory Alert Threshold **

**Comment by jmartins1** [comment]
Just curious, why would you have that there and then also have a minimum under the item itself? How or when would you use it that way?

⁣Sent from BlueMail ​

**Comment by jmartins1** [comment]
Yes, minimum quantity should be minimum quantity. If you set a minimum quantity alert it should alert at the threshold not before nor after.

⁣Sent from BlueMail ​
