### ISSUE TITLE
Delete Default Fields on "Create Asset Model"

### ISSUE THREAD

**Issue by AJCastroChandri** [snipe/snipe-it#6497]
**Server (please complete the following information):**
 - Snipe-IT Version v4.6.6 build 3926
 - OS: [e.g. Ubuntu, CentOS] Debian9 Stretch
 - Web Server: [e.g. Apache, IIS] Apache2
 - PHP Version php7.0

**Is your feature request related to a problem? Please describe.**
This is a feature request.
Would it be possible to delete the default fields on creating a new asset model?
On some cases, there are fields I will not use.

**Describe the solution you'd like**
Ideally, be able to "Create a Custom Asset Model" with zero fields.
User could add Field Sets to that Custom Asset Model.

**Describe alternatives you've considered**
At the moment, I am leaving all possible fields empty.

**Additional context**

**Comment by itsenaf** [comment]
Thumbs up! Would be awesome to have a possibility to hide fields like supplier. Because we never use it.
Sure its possible to change the code. But this seems to be a bit harder for a non web developer.

**Comment by AJCastroChandri** [comment]
I could definitely use the elimination of various of the default fields.

I do not how to do it, yet I have begun playing with Laravel.
Hopefully with that, I can learn enough in order to set the default fields optional/deletable.

It is my thinking that having the current default fields as optional would open up the Snipe-It project beyond the IT-focus it has at the present.

Feel free to close this issue is deemed appropiate.
Thanks.

**Comment by AJCastroChandri** [comment]
I... um... well... close it if you want bot.
=)

**Comment by snipe** [comment]
It's very unlikely we'll be implementing this any time soon. It affects a lot of business logic, and would introduce a ton of breaking changes.

**Comment by Fabshj** [comment]
> I could definitely use the elimination of various of the default fields.
> 
> I do not how to do it, yet I have begun playing with Laravel.
> Hopefully with that, I can learn enough in order to set the default fields optional/deletable.
> 
> It is my thinking that having the current default fields as optional would open up the Snipe-It project beyond the IT-focus it has at the present.
> 
> Feel free to close this issue is deemed appropiate.
> Thanks.

Hi, have you found a solution? 
BR Fabienne
