### ISSUE TITLE
Artisan snipeit:import not assigning asset to user

### ISSUE THREAD

**Issue by EnvistaGit** [snipe/snipe-it#6498]
I am trying to figure out why importing via the terminal is not finding a user that exists. 

https://snipe-it.readme.io/docs/importer-issues

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode yes
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) Yes there is nothing with this error in the common import issues

**Describe the bug**
Importing via csv cause it to throw an error saying it cannot find a user with the id with number
Even through that exact user exists.  Note that users are import from AD

**To Reproduce**
1. run  sudo php artisan snipeit:import /home/admin/Test2.txt -vvv
4.get error User does not appear to be an id with number: First Last.  Continuing through our processes

**Expected behavior**
Import assets and assign to applicable user.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 5.4.35
 - OS: CentOS
 - Web Server: Apache
 - PHP Version: 7.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Error Messages**
Not browser based
User does not appear to be an id with number: First Last.  Continuing through our processes

**Additional context**
- Is this a fresh install or an upgrade? Fresh Install with single custom feild
- What OS and web server you're running Snipe-IT on CentOS Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way. No special modification except a single non required custom field add from the web gui
- Indicate whether or not you've manually edited any data directly in the database: i have not manually modified the DBs

[admin@computer snipeit]$ sudo php artisan snipeit:import /home/admin/Test2.txt -vvv
[sudo] password for centadmin:
======= Importing Items from /home/admin/Test2.txt =========
A matching category: Laptop already exists
Company Company X was created
Location Toronto already exists
Manufacturer Dell already exists
User does not appear to be an id with number: First Last.  Continuing through our processes
User first.last@company.com already exists

In Importer.php line 319:

  [ErrorException]
  Undefined index: manager_id

Exception trace:
 Illuminate\Foundation\Bootstrap\HandleExceptions->handleError() at /var/www/snipeit/app/Importer/Importer.php:319
 App\Importer\Importer->createOrFetchUser() at /var/www/snipeit/app/Importer/ItemImporter.php:109
 App\Importer\ItemImporter->determineCheckout() at /var/www/snipeit/app/Importer/ItemImporter.php:88
 App\Importer\ItemImporter->handle() at /var/www/snipeit/app/Importer/AssetImporter.php:24
 App\Importer\AssetImporter->handle() at /var/www/snipeit/app/Importer/Importer.php:130
 App\Importer\Importer->App\Importer\{closure}() at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php:29
 Illuminate\Database\Connection->transaction() at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php:327
 Illuminate\Database\DatabaseManager->__call() at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:221
 Illuminate\Support\Facades\Facade::__callStatic() at /var/www/snipeit/app/Importer/Importer.php:137
 App\Importer\Importer->import() at /var/www/snipeit/app/Console/Commands/ObjectImportCommand.php:83
 App\Console\Commands\ObjectImportCommand->fire() at n/a:n/a
 call_user_func_array() at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:29
 Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:87
 Illuminate\Container\BoundMethod::callBoundMethod() at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:31
 Illuminate\Container\BoundMethod::call() at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php:539
 Illuminate\Container\Container->call() at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php:182
 Illuminate\Console\Command->execute() at /var/www/snipeit/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php:167
 Illuminate\Console\Command->run() at /var/www/snipeit/vendor/symfony/console/Application.php:946
 Symfony\Component\Console\Application->doRunCommand() at /var/www/snipeit/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /var/www/snipeit/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:122
 Illuminate\Foundation\Console\Kernel->handle() at /var/www/snipeit/artisan:35

[admin@computer snipeit]$

**Comment by EnvistaGit** [comment]
note that the "Company Company X was created" is a typo that does not actually happen. I just subbed in a different value.

**Comment by EnvistaGit** [comment]
Also forgot to mention the gui importer works but not for the specific list i have since it is about 450 entries. 

is there maybe some sort of specific formatting to the Name value?
Seems like it able to read the value but not match it for some reason.

**Comment by EnvistaGit** [comment]
tried to import without the "Full Name" field and it works thou it does appears that two other values do not  import. Those being MAC Address and Serial Number. Are my column names incorrect?
![capture](https://user-images.githubusercontent.com/43247047/49828304-27fefa00-fd51-11e8-8995-7e0129a96cb1.PNG)


However the asset does get added, without those fields.

**Comment by ReignSol** [comment]
To be honest we've had this problem for a while now. I've almost come to believe this is expected behavior. I wish it wasn't like this. It works with the web importer, but with the CLI, it will never check out an asset to a user.   :(

**Comment by snipe** [comment]
@EnvistaGit what version of Snipe-IT are you using? Your issue says 5-something, but v5 isn’t out yet, so that can’t be true.

**Comment by EnvistaGit** [comment]
whoops my bad pooled the wrong thing.

Snipe-IT version | v4.6.6 build 3926 (g1a10aa0dd)
Software License | AGPL3
PHP Version | 7.2.11
Laravel Version | 5.4.35

**Comment by EnvistaGit** [comment]
If it is the case where this is not the prefered method that fine it is not the biggest deal i can just break up the CSV and import it through the GUI importer.

**Comment by ReignSol** [comment]
I was thinking about doing this too for our setup. I made a Powershell script that runs when the user logs into the PC and it generate a csv file with the PC stats. Another script merge all the csvs into 1 csv. Snipe server auto imports the csvs. It's pretty neat. I just have to leave out the user and manually check out assets to users, or it won't work.
