### ISSUE TITLE
LDAP Sync email failed

### ISSUE THREAD

**Issue by andrefecto** [snipe/snipe-it#6507]
#### Please confirm you have done the following before posting your bug report:

- [No, using CLI ] I have enabled debug mode 
- [Yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Doing LDAP Sync if a user has an email with an apostrophe, it fails to import their email. (imports everything else just fine.) for example "first.o'leary@email.com" would fail. I think it's the apostrophe because all the other users we import have first.lastname@email.com and they work just fine.

**To Reproduce**
Have a user with an apostrophe in their email and try to import it using LDAP Sync.

**Expected behavior**
Expected is to import those emails.

**Screenshots**
Cannot include screenshots because of sensetive user data.

**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.4 build 3881
 - OS: Windows Server 2012 R2
 - Web Server: IIS
 - PHP Version: 7.2.9

**Error Messages**
"username: XXXXX was not imported: The email format is invalid." (I have confirmed that the user is imported but the email isn't.) 

I am using the: "php artisan snipeit:ldap-sync --summary" CLI because our LDAP sync is so large that it fails in the web browser.

**Comment by KeenRivals** [comment]
Dupe of #2282

**Comment by andrefecto** [comment]
Just for anyone that may look at this. The issue @KeenRivals referenced was closed because it was "stale" and never had a fix released for it.
