### ISSUE TITLE
Assign ldap user to default group

### ISSUE THREAD

**Issue by TheGammelgalopper** [snipe/snipe-it#6508]
**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.6
 - OS: Debian 9
 - Web Server: Apache
 - PHP Version: 7.0

**Is your feature request related to a problem? Please describe.**
We only have ldap users, who have no rights on first login. I have to manually assign a group for each user which is very time consuming.

**Describe the solution you'd like**
A solution like having a default group for all (new) users would be all I need! e.g. as described here: https://github.com/snipe/snipe-it/issues/4877

A nice to have would be the support of ldap groups, as described here: https://github.com/snipe/snipe-it/issues/1152

**Comment by RTodorov** [comment]
A default group could already help a lot (btw I'm using a dirty hack to achieve this behaviour with the help of mysql triggers) but ideally it could support some sort of LDAP group mapping.

**Comment by tymik** [comment]
+1

**Comment by chrisgassen** [comment]
still no updates on this??

@RTodorov could you share your dirty solution with mysql triggers? I am not too familiar with databases yet...

**Comment by snipe** [comment]
> still no updates on this??

Well since you added the extra question mark, we’ll get right on it. 🙄

We release and push fixes and features constantly. Sometimes the ones we push aren’t the ones you want, but they’re ones lots of other people do.

**Comment by soma115** [comment]
Yes, it is very much needed functionality. Thank you kindly.

**Comment by menacek04** [comment]
Yes, it is a needed function.

**Comment by jackhhh** [comment]
Yes, we need this useful function.

**Comment by chrisgassen** [comment]
oh pls dont close this...

**Comment by FLFrog** [comment]
+1 from me. We use LDAP to sync our users and it is very tiresome to have to manually add them to the correct user group. I would really appreciate the option to set a default user group for all imported LDAP users.

**Comment by fuzzbawl** [comment]
I would love to see this as well. It would be great to be able to define an LDAP OU within each permissions group so it can sync members with what is in LDAP. But even just a default group for new users to be added to would solve a lot of issues for us.

**Comment by FLFrog** [comment]
Still relevant to me!

**Comment by tsilman-marquette** [comment]
We are shifting over to LDAP after much talk and hand wringing. 
We have about 1300 potential users and possibly more to assign to a group. 

The "default" for a group should be selectable/editable. An example would be to allow view only access to assets for a new user. Alternatively, I suppose I could go directly into the database and script a change but am resistant to this line of thought.

A newbie account creation dialog might be handy. A new user could create an account which in turn would be assigned to the default group. This in turn would fire a review list to an Admin for status and upgrade to appropriate level of access.

**Comment by nickjmv** [comment]
We are also looking for this solution. It would be less time consuming! Sooo.. +1

**Comment by pfdan** [comment]
Yep, this would be great here too!

**Comment by tommivienna** [comment]
Yes, we would need this too!

**Comment by GermanKiwi** [comment]
+1 we need this for our company too. Looking forward to seeing it implemented!

**Comment by dopyrory3** [comment]
+1 there are loads of us who need this functionality

**Comment by nurdie** [comment]
Please, gods of opensource assets management, bestow this gift upon us

**Comment by menacek04** [comment]
Bump!!! 

+1 there are loads of us who need this functionality

**Comment by SergiusJanik456** [comment]
Would love (and need) this feature!

**Comment by gotfondue** [comment]
+1 on this feature as well, we need this for proper deployment.

**Comment by amffej** [comment]
+1

**Comment by taylor1123** [comment]
PLease!!

**Comment by gitbabis** [comment]
+1 on this feature.  Currently, after the LDAP connection, users are assigned to the admin group. It would be better for the site administrator to assign new users to a non admin group and generally the site administrator should have control over which group a new user will be assigned to.

**Comment by Kizan** [comment]
+1 on this. Could really use this feature! Some kind of default group that LDAP users could be assigned to would be great. Currently all the LDAP imported users show up as nothing. Manual assignment into groups is needed. Sigh.

**Comment by Norjek** [comment]
+1
Would be nice to have a default group setting.

**Comment by flippantremark** [comment]
+1 I'd like for end users to be able to have read only permissions to query the status of their device so that they can see for themselves when a device is due for replacement. Would save them bugging IT.

**Comment by marwinism** [comment]
+1 - Just discovered Snipe IT and are doing some research into rolling it out into our org. Applying a default group for "end users" would be pretty darn perfect. And / or grouping based on title in AD! 

Also, thanks for a great piece of software =)

**Comment by MikeW83** [comment]
+1 We also need this.

**Comment by uFojun** [comment]
+1 We also need this.

**Comment by Speed1** [comment]
+1 this would save a lot of time

**Comment by mwborn** [comment]
+1 this save a lot of time and avoid data manipulation.

**Comment by thomas-mc-work** [comment]
Isn't this project integrated into any of these funding sites like Liberapay or Bountysource? Maybe throwing some money on this topic could accelerate proper prioritization.

**Comment by PiChG** [comment]
+1 I would love to one day find relevant setting in LDAP/AD "On import from LDAP/AD assing user to group:"
Keepin my fingers crossed

**Comment by Techwolf12** [comment]
For a quick and dirty workaround, you can execute this query on the MySQL DB to create a trigger:
```
DROP TRIGGER IF EXISTS `snipeit`.`users_AFTER_INSERT_ADD_TO_GROUP`;

DELIMITER $$
USE `snipeit`$$
CREATE TRIGGER `snipeit`.`users_AFTER_INSERT_ADD_TO_GROUP` AFTER INSERT ON `users` FOR EACH ROW
BEGIN
INSERT INTO `snipeit`.`users_groups` (`user_id`, `group_id`) VALUES (NEW.id, '1');
END$$
DELIMITER ;
```

This assumes `snipeit` is your database name (change it if not) and group id `1` is your default group. It will be added for all users, not just LDAP users.
If you wonder what group has what ID, execute the following query:
```
SELECT id,name FROM snipeit.permission_groups;
```

(@chrisgassen mentioning if still relevant for you, it has been a while since your comment: https://github.com/snipe/snipe-it/issues/6508#issuecomment-489460631)

**Comment by komodin** [comment]
+1 to this feature! It would save a lot of time and we'll also avoid granting admin permissions to the Help Desk team to assign the default "Employee" group to every new user.

**Comment by philjak** [comment]
+1 need this, too!

**Comment by khrishino** [comment]
+1 please

**Comment by ghost** [comment]
+1 Would love this feature!

**Comment by jhd-old** [comment]
+1 please!

**Comment by t4ov** [comment]
+1

**Comment by default300** [comment]
+1

**Comment by gotfondue** [comment]
@snipe are you going to actually ignore this request for this long? I see other much less useful request getting assigned to someone yet this one, one of the MOST USEFUL features remains ignored.

**Comment by snipe** [comment]
@gotfondue I'm always confused when people say things like this. Do you somehow think being a jerk to the maintainers will get faster results? What you perceive as "less useful" is not always less useful to other people, and - surprise! - we have other people to think about than just you. Everybody uses Snipe-IT a little differently, and it's our job - not yours - to determine priorities that benefit the most people. If you don't like how we do things here, you're welcome to use another software package.

**Comment by snipe** [comment]
This was done some time ago - closing now
