### ISSUE TITLE
Not able to use LDAP/AD login,  There was an error authenticating the LDAP user: Could not find user in LDAP directory 

### ISSUE THREAD

**Issue by madslorenzen** [snipe/snipe-it#6509]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
We are unable to login with via LDAP. This error is shown :  production.ERROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory 
LDAP connection test from LDAP settings page is successful, but when trying to test with user credentials further down, it fails. We have tried many diffrent ways, read just about all bug reports and troubleshooted after them, but no luck.

**To Reproduce**
1. Setup LDAP integration with AD 
2. Test LDAP connction with success
3. Try to login with AD user 

**Expected behavior**
I would expect to be able to login with AD credentials.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.6 build 3926 (g1a10aa0dd)
 - OS: Windows 2016 x64
 - Web Server: WAMP
 - PHP Version 7.0.32

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser Chrome + Internet Explorer
 - Version 71.0.3578.98, 11.407.17134.0

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Debug mode turned on,  Login Failed. USER did not successfully bind to LDAP.
- If a stacktrace is provided in the error, include that too.
no.
- Any errors that appear in your browser's error console.
no
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
No (It is AD / LDAP)
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
Fresh
- What OS and web server you're running Snipe-IT on
 - Snipe-IT Version v4.6.6 build 3926 (g1a10aa0dd)
 - OS: Windows 2016 x64
 - Web Server: WAMP
 - PHP Version 7.0.32
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual Installation
- Include what you've done so far in the installation, and if you got any error messages along the way.
Everything runs, except the issue.
- Indicate whether or not you've manually edited any data directly in the database
We did not.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by madslorenzen** [comment]
All users are imported on LDAP sync although ending up not being able to login.
Ive checked the ldap filer many times.

**Comment by madslorenzen** [comment]
Any luck in finding a cause for our issue ?

**Comment by HinchK** [comment]
https://snipe-it.readme.io/docs/ldap-sync-login

**Comment by madslorenzen** [comment]
Hi HinchK, Thank you for your reply. 
We have tried many different settings for the LDAP AD Authentication Query - it has been tried with both uid=, samaccountname= and sAMAccountName= . The setting is now set as sAMAccountName= and import of users from AD is successful. But is is not possible to log in with a user from the AD, error message is shown as Error: The username or password is incorrect, and written in the log as RROR: There was an error authenticating the LDAP user: Could not find user in LDAP directory. 

So I have to say that the issues persists, please help.
Brgds Mads

**Comment by HinchK** [comment]
Mads!  Have you tried:  `uid=samaccountname`?

**Comment by madslorenzen** [comment]
I have now tried uid=samaccountname. After the configuration change, I did a LDAP Sync of the user accounts with success, but still are not able to login with AD accounts. Error messages are the same.

**Comment by HinchK** [comment]
Ok @madslorenzen - lets address two things from here:

Please check that the user accounts you are trying to log in with are "activated" in the system - 
![image](https://user-images.githubusercontent.com/1509456/50157789-2a98ac80-0287-11e9-8b3f-33da8b30ae6a.png)


ll Snipe-IT versions >4.4 require PHP 7.1.3 or higher.  Please update your instance's PHP to at leasst 7.1.3, and restart your web server.

**Comment by madslorenzen** [comment]
All AD users are activated.
![image](https://user-images.githubusercontent.com/23360696/50160768-60b34c00-02da-11e9-8939-e9df2aa058b8.png)

Our PHP version is 	7.0.32 - I will try to upgrade it to 7.1.3 now.

**Comment by madslorenzen** [comment]
With PHP version 7.2.10 the error continues. Still unable to log in with AD synced users.

**Comment by madslorenzen** [comment]
![image](https://user-images.githubusercontent.com/23360696/50161250-8d1b9800-02db-11e9-8f2f-7fd0c4113fc1.png)

**Comment by madslorenzen** [comment]
@HinchK Do you have any further suggestions on what we can do ?

**Comment by madslorenzen** [comment]
When using wireshark on the domain controller, I only see the Bind users password sent., never the user I try to authenticate. I only see a ldap success to find the login user, but I do not see a password beeing sent, or checked.

**Comment by madslorenzen** [comment]
After the LDAP bind SerachRequest that gives success in finding the login user, I only see these three entryes, before the LDAP unbind. All three reqests from SnipeIT server towards DC
![image](https://user-images.githubusercontent.com/23360696/50229288-42b51c80-03aa-11e9-9049-276753bbf140.png)

**Comment by madslorenzen** [comment]
@HinchK Do you have any further suggestions ?

**Comment by madslorenzen** [comment]
Hi - This setting has been set and tested several times without success. It it now the setting also:
![image](https://user-images.githubusercontent.com/23360696/50333722-8329ad00-0506-11e9-9173-04cdb75466a5.png)

**Comment by madslorenzen** [comment]
No luck. Test LDAP sync with success - test LDAP login no success.
![image](https://user-images.githubusercontent.com/23360696/50333796-ba985980-0506-11e9-9467-a5a44486c1ac.png)

**Comment by madslorenzen** [comment]
Tested LDAP sync with success, LDAP login with error:
![image](https://user-images.githubusercontent.com/23360696/50333836-d13eb080-0506-11e9-9d51-4c21cb3606fd.png)

**Comment by huangshifang** [comment]
![image](https://user-images.githubusercontent.com/41154731/50334413-2ef0ee00-0543-11e9-845f-db84207914d0.png)
![image](https://user-images.githubusercontent.com/41154731/50334462-56e05180-0543-11e9-8883-0bb1ef185772.png)

**Comment by huangshifang** [comment]
check your php version

**Comment by huangshifang** [comment]
snipe-it version 4.66 also sucess

**Comment by madslorenzen** [comment]
Stated the versions earlier in the ticket : 
![image](https://user-images.githubusercontent.com/23360696/50334613-27145800-0509-11e9-8ec8-2200b98d604e.png)

**Comment by huangshifang** [comment]
![image](https://user-images.githubusercontent.com/41154731/50334703-10d7bd80-0544-11e9-9704-da89c81cf05c.png)
try copy it

**Comment by huangshifang** [comment]
![image](https://user-images.githubusercontent.com/41154731/50334753-395fb780-0544-11e9-9bdc-320f55617fed.png)

**Comment by madslorenzen** [comment]
Tried to insert &(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2)) to LDAP Filter, No luck. Same result. Able to Test LDAP Sync - able to to LDAP sync under People, but not able to login - or test LDAP login - fails with not able to bind.

**Comment by HinchK** [comment]
@madslorenzen after doing some research, I regret to say that without our insight into active directory, we are just trying to hit a moving target.   

What we are doing here is matching usernames for usernames, from snipe-it to active directory.  This is pretty much whatever your domain's uid/username field LABEL is, mapped to one we pulled into Snipe-IT from the Sync.    Rather than get inside your domain - I did a little research and was able to compile a a sample list of common Snipe-IT LDAP Authentication Settings that I have had to implement over the years.

In some of these cases, we have had to use a setting like `uid=mail`, because the domain login enforced full email-usernames and thats how we were able to map it.....


This is by far the most common:
![image](https://user-images.githubusercontent.com/1509456/50367763-42965780-0537-11e9-9379-c62f4c6dffa3.png)

More LDAP Authentication Queries:
```
userprincipalname=

cn=                   (I don't think this was AD)

samaccountname=

uid=givenname

uid=

uid=mail

mail=
```

**Comment by huangshifang** [comment]
@madslorenzen It's a question of LDAP Authentication Queries.

**Comment by madslorenzen** [comment]
For futher insight to AD, we are able to assist ? We also started this support by asking for paid support – before we got forwarded to here.

**Comment by madslorenzen** [comment]
Also – when testing ldap, i get success, but when testing ldap authentication using the same credentials as the ad connect account, ldap auth still fails.
I REALLY NEED HELP WITH THIS !

From: Mads Askov Lorenzen
Sent: 7. januar 2019 11:59
To: 'snipe/snipe-it' <reply@reply.github.com>
Subject: RE: [snipe/snipe-it] Not able to use LDAP/AD login, There was an error authenticating the LDAP user: Could not find user in LDAP directory (#6509)


For futher insight to AD, we are able to assist ? We also started this support by asking for paid support – before we got forwarded to here.

**Comment by pvnick** [comment]
Did you get this figured out? I just got mine working after struggling with it for some time. Might be able to help you if you still need.

**Comment by diegorod** [comment]
Hi @pvnick , I'm having trouble myself. Can you share your settings ?

**Comment by cdcs68** [comment]
@dieorod - I had this same exact problem.  It turned out to be my Base Bind DN.  The problem showed up after I upgraded to v4.6.15.  Plus it isn't helpful that the error doesn't indicate any errors for the actual problem.  This took me days to figure out!!!

Below is an example of my base bind dn.

Base Bind DN My example: **OU=Sync,DC=your,DC=domain,DC=com**

I hope this is helpful.

**Comment by j33p4meplz** [comment]
Having a similar issue in docker on AD.

**Comment by diegorod** [comment]
My issue was a dumb one - I didn't check the box "This is an Active Directory server" because I thought it was referring to the server that snipeit was hosted on. After checking that box everything worked fine.

**Comment by j33p4meplz** [comment]
I was able to test auth with credentials, but i'm getting a bind error now
on trying to do an ldap sync.

**Comment by KUSD-GIT-ACCT** [comment]
@diegorod this actually got mine working. I assumed it meant is the server I'm hosting the website on an AD server so I never checked it.

**Comment by arlinters** [comment]
> My issue was a dumb one - I didn't check the box "This is an Active Directory server" because I thought it was referring to the server that snipeit was hosted on. After checking that box everything worked fine.

This fixed my issue. Thank you @diegorod !

**Comment by cdcs68** [comment]
Ok that’s great news!

**Comment by do-d1** [comment]
> 
> 
> My issue was a dumb one - I didn't check the box "This is an Active Directory server" because I thought it was referring to the server that snipeit was hosted on. After checking that box everything worked fine.

this helped me !!!
same thing i never was thinking to mark this checkbox , its not an LDAP server ...

**Comment by glencostiganFDC** [comment]
> My issue was a dumb one - I didn't check the box "This is an Active Directory server" because I thought it was referring to the server that snipeit was hosted on. After checking that box everything worked fine.

Yep, thought the same. It's worded weird...

**Comment by luanxinchen** [comment]
> @dieorod - I had this same exact problem. It turned out to be my Base Bind DN. The problem showed up after I upgraded to v4.6.15. Plus it isn't helpful that the error doesn't indicate any errors for the actual problem. This took me days to figure out!!!
> 
> Below is an example of my base bind dn.
> 
> Base Bind DN My example: **OU=Sync,DC=your,DC=domain,DC=com**
> 
> I hope this is helpful.

thanks bro! this fixed my issue!!! you r the best one!
