### ISSUE TITLE
wrong location in asset item list shown

### ISSUE THREAD

**Issue by it-world** [snipe/snipe-it#651]
Within the asset Item the correct location is shown.
In the asset item list there is everywhere the same location displayed (the default one).

**Comment by dbierspb** [comment]
@it-world : Can you provide a screen shot?  I'm not seeing the same thing you are.  

From my "Assets > List All" the correct location is shown.
From viewing the asset directly (/hardware/<id>/view/) I am actually not seeing the location listed at all.

**Comment by it-world** [comment]
@dbierspb  thanks for reply.
This is the list:
![assets](https://cloud.githubusercontent.com/assets/2543113/6650790/c53c1e60-ca24-11e4-81f0-4e2264f87541.png)
For example this is one of the assets:
![asset-at-hv-ai-01](https://cloud.githubusercontent.com/assets/2543113/6650792/ca0a084e-ca24-11e4-8dd9-aedeabd49757.png)

**Comment by madd15** [comment]
As this asset is checked out it take on the location of the person it is checked out too

**Comment by snipe** [comment]
That's correct. An assets location is the default location until it's been checked out, at which point it physically exists wherever that user does.
