### ISSUE TITLE
Requestable for Licenses, Accessories, Consumables and Components

### ISSUE THREAD

**Issue by x3inspire** [snipe/snipe-it#6520]
**Is your feature request related to a problem? Please describe.**
Yeah, because currently system only available request function for Asset. I have several of item like Toner, Keyboard and another item like paper under Admin Unit.  So this kind of item i'll put under Accessories, Consumables or Components.  Example if user want to request like keyboard, A4 paper so they need to request from the system like an asset to.

**Describe the solution you'd like**
Just make Licenses, Accessories, Consumables and Components available for requestable like asset.

**Additional context**
And please addon quantity option under request function, where user can request for how many they require. Example user want to request keyboard under accessories for 2 unit, so they can put 2 quantity under quantity option. And also under checkout option must addon how many quantity approved based on user request.  Let see my total keyboard have 20 unit in stock, one of user request for 3 unit and i only approved for 2 unit.  So in my stock still got balance 18 unit.

Hope Snipe IT can consider my idea, and sorry for my bad english.

Thanks!

**Comment by x3inspire** [comment]
Any one respon please?

**Comment by tymik** [comment]
duplicate of #5908

**Comment by ddlpre** [comment]
Not sure i should reply here or [https://github.com/snipe/snipe-it/issues/5908](url)

But i vote for this option.

**Comment by mamanto** [comment]
This feature should be implemented,  +1

**Comment by romeogemei** [comment]
count me in on this feature, thank you.

**Comment by Awangan** [comment]
This features is must! Voted!

**Comment by vourd** [comment]
Would definitely appreciate this feature! +1

**Comment by vourd** [comment]
Would definitely appreciate this feature! +1

**Comment by maxlehot1234** [comment]
+1 for this thing. It was a must have for this type of "service" ;)

**Comment by BoxedBrain** [comment]
I would love to see this! 👍

**Comment by x3inspire** [comment]
Hola, this feature still not implemented?

**Comment by justbeingthatguy** [comment]
+1 for this feature!!

**Comment by hatpt** [comment]
+1 for this feature!!

**Comment by BoxedBrain** [comment]
yes it is.

**Comment by gajo94** [comment]
Can we expect this feature in future releases?

**Comment by justbeingthatguy** [comment]
Still very much hoping this gets implemented

**Comment by justbeingthatguy** [comment]
Still relevant.

**Comment by aleksandrmetik** [comment]
+1 Very important feature, Thanks

**Comment by x3inspire** [comment]
+1 again.

**Comment by arazantsau** [comment]
We would like to get this feature also :)

**Comment by maxlehot1234** [comment]
Anything?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vorsoth100** [comment]
+1

**Comment by MrMontesa** [comment]
Same here. We'd like to ask staff to request  webcams, cheap headsets without serial, etc. Requesting an accessory would greatly improve our processes.
Same for licenses. We have O365 and everyone receives default lic. In addition staff can request license including Office. Would be good to be able to also handle such requests in Snipe.
Thanks much for your efforts.

**Comment by x3inspire** [comment]
Any update please...

**Comment by STI-IT** [comment]
+1 If components, consumable, and accessories had more features like the assets it would resolve a lot of these requests. Its about having the ability to adapt to a companies workflow.

**Comment by x3inspire** [comment]
2018 open thread, now almost 2 year still nothing?

**Comment by mschmidt291** [comment]
+1

**Comment by JackThursby252** [comment]
+1

**Comment by danielb7390** [comment]
+1

**Comment by x3inspire** [comment]
Is there any update?

**Comment by x3inspire** [comment]
Bump....

**Comment by Bingmano** [comment]
i would also like to see this.  Since my firm is 100% remote, i would appreciate the ability for users to request license seats for software / accessories (like replacement mouse, power cables, etc.) and have the ability for the admin to review, approve, then fulfil the request.

**Comment by arditm** [comment]
Indeed, A user normally has this kind of requests rather than assets. It would be good to have this feature.

**Comment by AImXOo0o** [comment]
+1

**Comment by roratonet** [comment]
During Covid times - even more important for a company to handle requests when 90% of the people are working from home

**Comment by x3inspire** [comment]
> During Covid times - even more important for a company to handle requests when 90% of the people are working from home

Yeah, but sad till now still no update.

**Comment by snipe** [comment]
> Yeah, but sad till now still no update.

Yeah, so sad. We've obviously just been sitting around this whole time. 🙄

**Comment by x3inspire** [comment]
What, still nothing?

**Comment by dannystart** [comment]
> > Yeah, but sad till now still no update.
> 
> Yeah, so sad. We've obviously just been sitting around this whole time. 🙄

How is this not a standard feature? Once a user is deployed with their hardware, I would have thought the most requested type of item are consumables.. because, they're, well, consumable... Ink/Toner, Headsets, USB Pen drives etc.

Please make it happen, I would consider donating/paying for this to be implemented. Thank you

**Comment by x3inspire** [comment]
After 2 years and still nothing T_T

**Comment by Exordian** [comment]
Requestable licenses would be very awesome!

**Comment by citizenkepler** [comment]
Just bought the Hosted plan and I was disappointed to see that only assets were requestable.  I would love to see Consumables, etc requestable.

**Comment by snipe** [comment]
(Closing as duplicate of #5908)

**Comment by viclou** [comment]
Related to internal FD issue 34159
