### ISSUE TITLE
Cannot Generate Backup

### ISSUE THREAD

**Issue by Damancor** [snipe/snipe-it#6527]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Cannot Generate Backup in web console.

**To Reproduce**
1. Go to 'backups'
2. Click on 'Generate backup'

**Expected behavior**
A backup file created and visible in the backups list in the web console.

**Screenshots**
![backup error](https://user-images.githubusercontent.com/45942682/50177062-0bbe0880-02cf-11e9-93af-2e64917a11e5.JPG)

**Server (please complete the following information):**
 - Snipe-IT Version 
v4.6.6 build 3926 (g1a10aa0dd)
 - OS: [e.g. Ubuntu, CentOS]
Windows 2012 R2 Datacenter
 - Web Server: [e.g. Apache, IIS]
IIS
 - PHP Version 
7.0.33
**Desktop (please complete the following information):**
Windows 10
Chrome
70.0.3538.110

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Production.ERROR: backups backups : error ; Failed to backup because: dump process failed with exitcode 1 : General error :
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
None
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
No
- Include any additional information you can find in `storage/logs` and your webserver's logs.
Production.ERROR: backups backups : error ; Failed to backup because: dump process failed with exitcode 1 : General error :

**Additional context**
- Is this a fresh install or an upgrade? 
Fresh Install
- What OS and web server you're running Snipe-IT on
Windows 2012 R2 Data center, IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by 5quirrel** [comment]
What do your permissions on that folder look like?

**Comment by Damancor** [comment]
Hi 5quirrel,

The IUSR user has modify permissions on the C:\inetpub\wwwroot\snipe-it\storage  folder. The only thing that caught my eye is that the path in my screenshot looks incorrect. The path should be C:\inetpub\wwwroot\snipe-it\storage\app\backups but I see C:\inetpub\wwwroot\snipe-it\storage/app/backups 

Any idea how to edit this path in the config?

**Comment by 5quirrel** [comment]
Na it's not the path that's displayed there. I had the same path running IIS, and I had the same problem.

Add IIS_IUSRS group to the Storage folder permissions with at least modify in addition to IUSR account. See how you go.

Previous issue #2454

**Comment by Damancor** [comment]
@5quirrel 

I added the permission above to storage and windows Temp folder it fixed my issues! Thank you for your help, you're a live saver! now I can try using the import feature with some peace of mind. :) 

![image](https://user-images.githubusercontent.com/45942682/50289039-ad5f6a00-0435-11e9-9d07-d64f5f9b9814.png)

**Comment by 5quirrel** [comment]
@Damancor no worries!

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)

**Comment by nestawnar** [comment]
> Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)
> 
> ![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)

Dear Am also getting the issue am tried all the troubleshooting
![Capture](https://user-images.githubusercontent.com/16223725/71553555-ec51d380-2a2a-11ea-8142-fac63eb1b79c.JPG)
 methods to solve the issue but no luck
