### ISSUE TITLE
Cannot create new assets

### ISSUE THREAD

**Issue by mltmjoe** [snipe/snipe-it#6528]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When attempting to add a new asset to Snipe, it gives a 'Whoops' error and does not load the form/page which collects the asset information. This happens regardless of the link used (as they all go to the same page). Also, when viewing the 'Categories' list it appears to be empty. However, categories still show for existing assets and I cannot add those again to the list as Snipe says they already exist. Before the update all functions worked perfectly. The database was not changed during the upgrade. 

**To Reproduce**
1. Go to Dashboard
2. Click 'New' > 'Asset' (or use the 'Create New' button within the asset list window)
3. See error

**Expected behavior**
Open the 'New Asset' page in order to add a new asset to Snipe

**Screenshots**
![snipenewasset error1](https://user-images.githubusercontent.com/43795454/50177885-f689af80-02b7-11e9-84bc-792f32693514.JPG)
![snipenewasset error2](https://user-images.githubusercontent.com/43795454/50177886-f689af80-02b7-11e9-9dc0-e76888c5629a.JPG)
![snipenewasset error3](https://user-images.githubusercontent.com/43795454/50177887-f7224600-02b7-11e9-88d8-9504a6e56582.JPG)

**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.6 build 3926 (g1a10aa0dd)
 - OS: Windows 10 Pro
 - Web Server: Apache
 - PHP Version: 7.1.9

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro x64
 - Browser Firefox
 - Version 65

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'default_label' in 'order clause' (SQL: select `name`, `id` from `status_labels` where `status_labels`.`deleted_at` is null order by `default_label` desc, `name` asc, `deployable` desc)
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? **Upgrade**
- What OS and web server you're running Snipe-IT on: Windows 10 Pro, Apache through WAMP
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Git
- Include what you've done so far in the installation, and if you got any error messages along the way.. **Followed the directions at (https://snipe-it.readme.io/docs/switching-to-a-git-install) and encountered no errors or issues.** 
- Indicate whether or not you've manually edited any data directly in the database:
**Yes, I added the 'category_id' field to the assets table after reviewing (https://github.com/snipe/snipe-it/issues/6156) in an attempt to fix the issue. The main reason for doing this is due to the issue with categories (see below)**
- I can successfully add a new license, component, accessory, user, etc. - anything except an asset.
- The Categories list _is empty_ and I cannot create new assets (likely due to this issue). When I try to re-create the categories it says that they need to be unique - so they do exist in the system, but are not properly referenced it seems. When viewing the list of assets, the proper categories still show in the list and asset details - nothing seems to be deleted but it's as if Snipe can't 'see' the categories.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by 5quirrel** [comment]
Missing a database migration maybe?

Did you swap to Git from a manual install of the same version? (e.g. 4.6.6 to 4.6.6)

**Comment by mltmjoe** [comment]
It was a swap to Git from a previous version. So I upgraded during the process.

**Comment by 5quirrel** [comment]
At what point in the process did you upgrade?

**Comment by snipe** [comment]
Did you run migrations when you upgraded?

**Comment by mltmjoe** [comment]
I have been inundated with other things and this fell by the wayside. 

No, I did not run migration when I did the change - my understanding was that it would upgrade during the process. 

What is the proper way to redo it now that it is in this stuck state? Do I completely remove snipe, re-install it from Git, and import the database? Is there a way to upgrade my database so it matches the current version? I want to get the system operating again as it is a pain to have it in this read-only state, but I don't know the best way to get it back and functioning.

**Comment by snipe** [comment]
How did you upgrade?

**Comment by snipe** [comment]
Try running `php artisan migrate` from the command line - if you see anything weird, paste the error here.

**Comment by mltmjoe** [comment]
C:\wamp\www\snipe-it>php artisan migrate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes


In Connection.php line 647:

  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'category_id' (SQL: alter table `licenses` add `category_id` int null)


In PDOStatement.php line 107:

  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'category_id'


In PDOStatement.php line 105:

  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'category_id'

**Comment by mltmjoe** [comment]
> 
> 
> How did you upgrade?

I did not do an upgrade directly - I just did the transition to Git thinking it would be fairly smooth. Do I need to wipe snipe from my system, re-install the older version (how do I confirm which version I had installed?), restore the backup, then upgrade it, then move to Git?
