### ISSUE TITLE
Keep asking credentials Credentials 

### ISSUE THREAD

**Issue by rnovo1983** [snipe/snipe-it#653]
HI, my snipe-it is ready and running  but it keeps asking me, to log-in every time I click on a different link. Any suggestions?.

Thank You

**Comment by snipe** [comment]
Not really. 

- Make sure your browser allows cookies, make sure your URL is correct in your `app/config/<environment>/app.php`
- Make sure `app/storage/sessions` is writable by the web server
- Maybe try changing `native` to `cookie` in `app/session.php` 
- Set the `lifetime` to something longer in  `app/session.php`

**Comment by dbierspb** [comment]
@rnovo1983 : is anything showing in your apache error logs?

**Comment by rnovo1983** [comment]
fixed already.. thanks.
