### ISSUE TITLE
Feature Request: Add notes field for accessories and cosumables

### ISSUE THREAD

**Issue by mtausig** [snipe/snipe-it#6530]
**Server (please complete the following information):**
 - Snipe-IT Version v4.6.6
 - OS: Ubuntu Xenial
 - Web Server: nginx
 - PHP Version 7.0.32

**Is your feature request related to a problem? Please describe.**

We want to store additional information for all our devices (like usage instructions or a link to the manufacturer). We use the *notes* field for assets and asset models, but sadly accessories and consumables do not have such a field

**Describe the solution you'd like**

Add a note field to accessories and consumables

**Describe alternatives you've considered**

The only workaround would be to make every accessory an asset, which is not a good idea.

**Additional context**

Something similar has already been proposed in issue #3661 , but it went stale and was closed before it was processed.

**Comment by mtausig** [comment]
Still very much desired & revelvant.

**Comment by mtausig** [comment]
Still relevant

**Comment by mtausig** [comment]
Still relevant.

**Comment by perezalvarezhi** [comment]
It looks like issue  #6918 is about the same and its already marked by the author as a featur request and ready for dev.

This issue is much older but might be better to move to that one.

**Comment by mtausig** [comment]
Still relevant.

**Comment by mtausig** [comment]
Still relevant
