### ISSUE TITLE
Ability to checkout accessories to assets, locations

### ISSUE THREAD

**Issue by Beefy-Swain** [snipe/snipe-it#6531]
**Describe the solution you'd like**
I would like to be able to check out accessories to both assets and locations

**Describe alternatives you've considered**
a separate "container" object type that both assets and containers can be checked out to

**Additional context**
We are an organization that spends much of our time working out of pelican cases on the road, as such we need a way to know not only what vehicle our equipment is in, but what container it is in. One way to do this would be to check out say, a 3ft XLR cable (accessory) to a pelican case (asset).

**Comment by tymik** [comment]
duplicate of #5140

**Comment by iamjustingraves** [comment]
Can we light this back up? Checking an accessory out to a location would be great in hotdesk implementations.

**Comment by benoithcc** [comment]
https://github.com/snipe/snipe-it/issues/5140
