### ISSUE TITLE
Sorting on IP Address doesn't work on last octet

### ISSUE THREAD

**Issue by tarun-teja** [snipe/snipe-it#6535]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I created a custom field of format IPV4 and added it to my assets. After creating a lot of assets, when I try to sort the assets based on IP address, the sorting doesn't work as expected.

**To Reproduce**
1. Create a custom IP field of IPV4 format and add that to sample model
2. Create few sample assets with different IP addresses 
ex:  Asset1 : 10.65.98.8, Asset2:  10.65.98.79, Asset 3: 10.65.98.83
3. Click on IP field header in the UI in Assets view

**Expected behavior**
In Ascending mode:
Asset1 : 10.65.98.8
Asset2:  10.65.98.79
 Asset 3: 10.65.98.83

**Actual behavior**

Asset2:  10.65.98.79
Asset1 : 10.65.98.8
 Asset 3: 10.65.98.83

**Server (please complete the following information):**
 - Snipe-IT Version : v4.6.6 build 3926 (g1a10aa0dd) 
 - OS: CentOS 7
 - Web Server: Apache
 - PHP Version 7.1.23
-- | --

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Mozilla firefox
 - Version 64.0

**Additional context**
- Is this a fresh install or an upgrade?  **Fresh install**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **manual installation**
- Indicate whether or not you've manually edited any data directly in the database : **No**

The sorting feature fails on the last octet for many other IP address of the similar format.

**Comment by jackka** [comment]
Tested on https://demo.snipeitapp.com
The same behavior.
![image](https://user-images.githubusercontent.com/6271335/50376721-376c2600-0622-11e9-8ce0-7f16b456758e.png)

**Comment by smb** [comment]
Sorting (custom fields, IP) needs to be done in PHP with natsort / strnatcmp instead of laravel/mysql sorting which can't handle natural order sorting.

**Comment by jackka** [comment]
yes. it's still relevant

**Comment by jackka** [comment]
Yes. It's still relevant.

**Comment by smb** [comment]
yes its still relevant.... stale bot should just go away, it doesnt help.

**Comment by snipe** [comment]
@smb it helps with our mental health. Some issues are opened by people who don't end up using the project, and then we just have thousands of open issues, many of which no one actually cares about anymore.
