### ISSUE TITLE
Email Notifications not working as the email address listed. It only send to Admin email

### ISSUE THREAD

**Issue by shiroamada** [snipe/snipe-it#6539]
#### Please confirm you have done the following before posting your bug report:

- [YES] I have enabled debug mode 
- [YES] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Email notification only sent to Admin user (shiro@example.com). I had set another user as Admin (ray@example.com), but it only send to shiro@example.com

In the admin notification I already set both email as ray@example, but email won't sent.
![image](https://user-images.githubusercontent.com/2062946/50394256-4b856400-0797-11e9-8699-1a77bae5ceba.png)

**Expected behavior**
send to responding user.

**Server (please complete the following information):**
 - Snipe-IT Version : 4.6.6
 - OS: [e.g. Ubuntu, CentOS]: Windows Server 2016 Standard
 - Web Server: [e.g. Apache, IIS] : Apache 2
 - PHP Version  : 7.1.8

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS 10.14.2
 - Browser [e.g. chrome, safari] Chrome 
 - Version [e.g. 22] 71

**Error Messages**
No error, but email not received.

**Comment by snipe** [comment]
Which email notifications are you referring to?

**Comment by shiroamada** [comment]
requestable assets email. All the email won't notify ray@example.com. It will only notify the admin email which is setup the snipe-it at the first place.
