### ISSUE TITLE
Item shown are always the same, change page doesn't work

### ISSUE THREAD

**Issue by crouch766** [snipe/snipe-it#6544]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
While showing users list page, changing page counter does not affected the list. Same users always shown.
The same happens for others pages, like asset and license.
Also changing the number of record to be shown does not reflect the changes in the page 

**To Reproduce**
1. Go to 'People'
2. Click on 'Page 2'
4. See error (Same users)

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.6 - build 3926 (master)
 - OS: Debian 9 x64
 - Web Server: Nginx
 - PHP Version PHP 7.0.33

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome - IE - EDGE

**Error Messages**
No error shown

**Additional context**
- Is this a fresh install or an upgrade? Fresh Install
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual Install

Thanks!

**Comment by 5quirrel** [comment]
You haven't left text in the filter box by any chance?

Does the problem follow you in inPrivate browsing in IE, or on other browsers?

**Comment by crouch766** [comment]
It seems that the filter bar does not work, if i try to filter one user, the user list doesn't change.
The same behavior if i try to filter the user when i want to assign an asset to one user.

Same with inPrivate (IE, Chrome, ecc..)

**Comment by snipe** [comment]
Next time please complete all of the issue template questions. Can you reproduce this on the demo? Is there anything in your logs? Anything in your browser console?

**Comment by crouch766** [comment]
Sorry, i've forgot the args on nginx conf: /index.php$is_args$args

I'm sorry if i wasted your time.

Regards,
S
