### ISSUE TITLE
WAMP + SSL to open localhost over HTTPS (Self-Signed Cert)

### ISSUE THREAD

**Issue by jmartins1** [snipe/snipe-it#6546]
Oh wise ones...I could use your assistance to solve the following:

I'm using:
Server 2012R2
WAMP Server (latest), Apache2.4.35, PHP 7.2.10, MySQL 5.7.23

I've been attempting use a self-signed cert to encrypt the traffic on our internal only Snipe-IT installation. Again, this is not publicly available, i.e. there is no domain assigned to the cert just localhost.

The issue is that browsers apparently do not like self-signed certificates anymore and I receive an error indicating that the cert is not secure/not valid.

Our installation of SnipeIT is for internal purposes only but do intend to use LDAP; so I need to encrypt the data. 

Questions
1. Although I receive this error, is the traffic still encrypted?
2. Has anyone been able to use a self-signed cert and got it to work. If so how?

I used the following installation example; went smooth. Chrome even accepted the cert initially, then it failed. Ideas/Suggestions?

Thank you ahead of time.

How to use WAMP + SSL to open localhost over https:

Download & install WampServer.
Open a command prompt (WindowsKey + R > cmd > click OK) and enter the following commands.
cd c:\wamp64\bin\apache\apache2.4.27\bin
openssl genrsa -aes256 -out private.key 2048
openssl rsa -in private.key -out private.key
openssl req -new -x509 -nodes -sha1 -key private.key -out certificate.crt -days 36500 -config c:\wamp64\bin\apache\apache2.4.27\conf\openssl.cnf
Note: You can pretty much answer the questions any way you want though real answers are best. The one question that really matters here is the FQDN. It should be: localhost.
Move the private.key and certificate.crt files from c:\wamp64\bin\apache\apache2.4.27\bin to the c:\wamp64\bin\apache\apache2.4.27\conf\key\ folder. If the key folder doesn't already exist, create it.
Using a text editor like Notepad, open c:\wamp64\bin\apache\apache2.4.27\conf\httpd.conf and un-comment following 3 lines:
LoadModule ssl_module modules/mod_ssl.so
Include conf/extra/httpd-ssl.conf
LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
Using a text editor like Notepad, open c:\wamp64\bin\apache\apache2.4.27\conf\extra\httpd-ssl.conf and apply the following changes:
Below the line: <VirtualHost _default_:443>, check the following parameters to ensure they are configured correctly and not commented.
-------------------------------------
DocumentRoot "c:/wamp64/www"
ServerName localhost:443
ServerAdmin admin@example.com
SSLSessionCache "shmcb:c:/wamp64/bin/apache/apache2.4.27/logs/ssl_scache(512000)"
ErrorLog "c:/wamp64/bin/apache/apache2.4.27/logs/error.log"
TransferLog "c:/wamp64/bin/apache/apache2.4.27/logs/access.log"
SSLCertificateFile "c:/wamp64/bin/apache/apache2.4.27/conf/key/certificate.crt"
SSLCertificateKeyFile "c:/wamp64/bin/apache/apache2.4.27/conf/key/private.key"
-------------------------------------
Save the file and close it.
You are done. To check the validity of file, at the command prompt, enter:
c:\wamp64\bin\apache\apache2.4.27\bin\httpd -t
and then use your web browse to go to https://localhost/

**Comment by snipe** [comment]
> The issue is that browsers apparently do not like self-signed certificates anymore and I receive an error indicating that the cert is not secure/not valid.

Unfortunately, that's just how this works :( The browser is telling you (and your users) that they don't know/trust the issuing Certificate Authority, which it can't, since it's self-signed. The traffic is still encrypted, but the browser can't certify that the cert came from somewhere that's trusted.

Best practices would dictate that you pick a domain or subdomain, and get a legitimate certificate, either by buying one or by using Let's Encrypt (free, but difficult to set up if you haven't done it before). You really don't want to teach your users that ignoring SSL warnings is "good".
