### ISSUE TITLE
Installation of snipe-it but can't get to pre-flight page

### ISSUE THREAD

**Issue by ash-hakopyan** [snipe/snipe-it#6548]
#### Expected Behavior (or desired behavior if a feature request)

I'm supposed to see the setup page of Snipe-It by now, but I get the following page when I type the IP address of my host on a browser:
-----

#### Actual Behavior

*/ /* |-------------------------------------------------------------------------- | Register The Auto Loader |-------------------------------------------------------------------------- | | Composer provides a convenient, automatically generated class loader for | our application. We just need to utilize it! We'll simply require it | into the script here so that we don't have to worry about manual | loading any of our classes later on. It feels nice to relax. | */ require __DIR__.'/../bootstrap/autoload.php'; /* |-------------------------------------------------------------------------- | Turn On The Lights |-------------------------------------------------------------------------- | | We need to illuminate PHP development, so let us turn on the lights. | This bootstraps the framework and gets it ready for use, then it | will load up this application so that we can run it and send | the responses back to the browser and delight our users. | */ $app = require_once __DIR__.'/../bootstrap/app.php'; // set the public path to this directory $app->bind('path.public', function() { return __DIR__; }); /* |-------------------------------------------------------------------------- | Run The Application |-------------------------------------------------------------------------- | | Once we have the application, we can handle the incoming request | through the kernel, and send the associated response back to | the client's browser allowing them to enjoy the creative | and wonderful application we have prepared for them. | */ $kernel = $app->make(Illuminate\Contracts\Http\Kernel::class); $response = $kernel->handle( $request = Illuminate\Http\Request::capture() ); $response->send(); $kernel->terminate($request, $response); 

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running: latest. Downloaded on 12/30/2018 from git
- Version of PHP you're running: 7.2
- Version of MySQL/MariaDB you're running: 14.14 distrib 5.7.24 on linux
- What OS and web server you're running Snipe-IT on: Ubuntu Linux 18 LTS Apache: v2.4.29
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error.  It's not an error, I just don't see the proper html page of snipe-it setup page to continue setting up the database tables etc.

- Include what you've done so far in the installation, and if you got any error messages along the way.
I had issues during mcrypt installation but got past it with help from searching google on the issue.

**Comment by EarlRamirez** [comment]
Looks like PHP is not installed or all of the required modules

**Comment by ash-hakopyan** [comment]
I've got PHP installed.
snipeadmin@snipeit:~$ php -v
PHP 7.2.10-0ubuntu0.18.04.1 (cli) (built: Sep 13 2018 13:45:02) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend                   Technologies
snipeadmin@snipeit:~$

I'll check for the modules required.

**Comment by snipe** [comment]
If you're seeing PHP code in your browser, PHP is not installed or enabled. It's *possible* (but unlikely) that index.php is not set as an extension that should be parsed by PHP, but I've not seen that be an issue in many years.

Remember that command line PHP (what you used to generate your installed modules list) is not the same as the apache module PHP. You might have PHP installed on your box, but not enabled via Apache. (What you hit in a web browser isn't the same PHP as you hit via command line.)

**Comment by ash-hakopyan** [comment]
No it is not. Thanks
