### ISSUE TITLE
Customization in Dashboard

### ISSUE THREAD

**Issue by okarjun** [snipe/snipe-it#6549]
Snipe-IT version | v4.6.3 build 3866 (g3de1de9dc)
Software License | AGPL3
PHP Version | 7.2.4
Laravel Version | 5.4.35
OS: Windows
Web Server:ISS

**Is your feature request related to a problem? Please describe.**
Currently, if we need to genrate report and filter/pivot data to find the asset in stock, asset in use, asset in repair, asset in damage.  We don't have a widget in dashboard to view the report in a snap

**Describe the solution you'd like**
Can you add the dashboard widget where manager can view ( Total Asset Puchase, Total Asset in Stock, Total Asset deployed.)
	Total Laptops purchased, used, in-stock.
	Tatal Printers purchased, used, in-stock.
	List of all the small IT accessories like adapters, moniors, pointers, HDDs, Pendrives etc. that we purchased, in use and in stock.

**Describe alternatives you've considered**
- Please add the custom widget option so that we can add the new dashboard based on our requirment.

**Comment by eyalgett** [comment]
+1
i would like to have the ability to customize dashboard widget so i can have my own query and get a relevant data with charts. as of today the only chart there (Assets by status) is not giving any added value.

**Comment by dbTunder** [comment]
+1
I would like to have local admins of sub-companies allowed to see recet activity and statistics for their own subset of assets and actions

**Comment by Norjek** [comment]
+1

**Comment by burrows7li** [comment]
+1

**Comment by PandiarajanSelvaraj** [comment]
It is relevant.

**Comment by ralphmodales** [comment]
+1
