### ISSUE TITLE
Auto populate requesting user in checkout menu when clicking on checkout on a requested item

### ISSUE THREAD

**Issue by duel007** [snipe/snipe-it#6552]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.6
 - OS: Docker
 - Web Server: -
 - PHP Version: Docker

**Is your feature request related to a problem? Please describe.**
In the requested section, requests for items are listed separately by user, not by item. Clicking on the Checkout button does not auto populate the requesting user on the next page.

**Describe the solution you'd like**
The requesting user should be auto populated on the checkout page.

**Describe alternatives you've considered**
Alternatively, it could be refactored in to sort requests per asset, and then allow the admin to choose which of the requesting users receives the requested item.

**Additional context**
-

**Comment by Puddl36lum** [comment]
+1

**Comment by duel007** [comment]
Relevant

**Comment by adhyuthn** [comment]
I'd like to reopen this request. It would be nice if the user field is auto-populated otherwise. This would make checking out a lot easier
![image](https://github.com/snipe/snipe-it/assets/98572686/a2db7ee6-b29b-457f-b6a8-fd15dd3642d2)
