### ISSUE TITLE
Asset request is not cleared when asset is checked in

### ISSUE THREAD

**Issue by duel007** [snipe/snipe-it#6553]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Asset request is not cancelled/cleared when a requested asset is checked out and then checked back in. The user request stays in the requested asset section, and user view shows "cancel".

**To Reproduce**
1. Request asset as user.
2. Checkout asset to user as admin.
3. Check in user as admin.
4. Observe that asset request is still showing in requested section.

**Expected behavior**
Asset request should be cleared when the asset is checked back in.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.6
 - OS: Docker
 - Web Server: Docker
 - PHP Version 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version  71.0.3578.98

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? Upgrade from previous.
- What OS and web server you're running Snipe-IT on: CentOS, Docker
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Docker
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database: No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Damancor** [comment]
Any word on this as I have the same problem.

**Comment by duel007** [comment]
This is still relevant.

**Comment by LeeSharman** [comment]
+1
