### ISSUE TITLE
Delete and Purge All Records Quickly

### ISSUE THREAD

**Issue by nspaul** [snipe/snipe-it#6559]
**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.7
 - OS: Ubuntu 16.04.5
 - Web Server: Apache
 - PHP Version: 7.2.13-1+ubuntu16.04.1

**Is your feature request related to a problem? Please describe.**
No. Just a basic feature request

**Describe the solution you'd like**
I am looking to move from an old homegrown inventory database over to Snipe-IT. I've been running regular bulk imports (with lots of records), and I'd like an easier way to dump all of the data that I imported, so I can run a fresh import. A naive improvement would be to let me select more than 500 items on the List All page. In my particular case I've got just over 2500 assets listed, so even having just an option to select 1000 or 1500 would be a major improvement over 500. Having a "Show All rows" would be ideal, but I understand that may not be an option in the case where someone has tens of thousands of records.

Another option might be to have a "Dump and Purge All Data" option in the Settings pane. This would make it easy to effectively reset the database to a base state.

**Describe alternatives you've considered**
I tried just editing the blade view (specifically, /resources/views/partials/bootstrap-table.blade.php) to give me a larger number. I changed the array on line 58 to:
`pageList: ['10','20', '30','50','100','150','200', '1500'],`
This did indeed show me 1500 records, but when I checked the select all button and then selected Delete and clicked Go, I got a red "Error: No assets selected" banner error.

**Additional context**

**Comment by Jarli01** [comment]
The amount of records that can be exported are a limit of the bootstrap tables library that is used in the system. 

I've asked about something similar in this FR here. #6429
