### ISSUE TITLE
Import restricted to superadmin only?

### ISSUE THREAD

**Issue by BHollowell** [snipe/snipe-it#6560]
#### Expected Behavior (or desired behavior if a feature request)

Users delegated as a company admin should be able to perform CSV imports

-----

#### Actual Behavior

Only superadmin users are able to perform CSV imports

-----

#### Please confirm you have done the following before posting your bug report:

- [yes] I have enabled debug mode 
- [yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
_Upgrade from within version 4_

- Version of Snipe-IT you're running
_v4.5.0 - build 3701 (master)_

- Version of PHP you're running
_PHP 5.6.36_

- Version of MySQL/MariaDB you're running
_Server version: 5.6.39 MySQL Community Server (GPL)_

- What OS and web server you're running Snipe-IT on
_CentOS Linux release 7.4.1708 (Core)_
_Server version: Apache/2.4.6 (CentOS)_

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
_Manual install and upgrade.php to upgrade to latest master_

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
_No error to speak of, just a failed upload at 10%_

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
_Import page, trying to upload a file_

- If a stacktrace is provided in the error, include that too.

- Any errors that appear in your browser's error console.

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
_Import is not available in the demo site_

- Include any additional information you can find in `storage/logs` and your webserver's logs.
_Nothing useful in this log. The end of the file refers to failed LDAP logins over the past few days. Nothing new generated during my testing._

- Include what you've done so far in the installation, and if you got any error messages along the way.

- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by BHollowell** [comment]
@snipe Can someone take a look at this?

**Comment by BHollowell** [comment]
Updates? Anyone?

**Comment by snipe** [comment]
According to the source code, if a user can create assets, they can import.
https://github.com/snipe/snipe-it/blob/master/app/Http/Controllers/Api/ImportController.php#L122

**Comment by BHollowell** [comment]
@snipe Could this be a file permissions issue? The problem doesn't come when attempting to process an import file, it's when we try to import the file in the first place. The upload progress bar hits 10% and then fails.

**Comment by BHollowell** [comment]
This is still an issue for me. How can I help troubleshoot this issue? What information should I gather?
