### ISSUE TITLE
One 

### ISSUE THREAD

**Issue by fhglaeser** [snipe/snipe-it#6564]
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by fhglaeser** [comment]
Please, can an Admin change the title of this issue in
"upload a pdf-document (e.g. bill) and allocate this to one or more several assets like pc, monitor etc.
Thanks

**Comment by Mynty100** [comment]
![image](https://user-images.githubusercontent.com/34461276/51082907-edc3b680-175b-11e9-9785-6d594414a0be.png)
When you are viewing an asset along the top is file option. on the far right you can upload files. images or documents or receipt.
