### ISSUE TITLE
Reconfigure 2FA

### ISSUE THREAD

**Issue by ffuentes** [snipe/snipe-it#6567]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Enabling, then disabling and enabling again 2FA does not regenerate a QR code.

**To Reproduce**
1. Enable 2FA for a user
2. Log out
3. Log in and use the 2FA code
4. Disable 2FA for the user
5. Log out
6. Log in using only the password
7. Enable 2FA

Then the system logout and ask for a 2FA code. A code using the first QR works.

**Expected behavior**
After enabling the 2FA it should generate a new QR code.

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.7 build 39944
 - OS: CentOS 7
 Web Server: Apache + nginx proxy (Letsencrypt)
PHP Version: 7.1.15

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.1
 - Browser Firefox Quantum 64.0

**Comment by ffuentes** [comment]
@snipe can you check this?

**Comment by snipe** [comment]
How are you disabling 2FA for the user? We don't have that as an option - only resetting their device. 

https://github.com/snipe/snipe-it/blob/master/app/Http/Controllers/Api/UsersController.php#L331-L349

**Comment by ffuentes** [comment]
> How are you disabling 2FA for the user? We don't have that as an option - only resetting their device.

I found the option editing the user as an admin. But first I looked in my own profile.

Should the user be able to reset it's own 2fa? Most of the services I use I can reset 2fa secret just by disable and enable again, and some of them allow 2fa reset.

I think that the user should have the possibility to reset the 2fa just by himself.

**Comment by soxhi8** [comment]
Giving administrators the option to let users reset their 2FA secret via self-service, would be a great addition.
