### ISSUE TITLE
Unable to delete imported csv files

### ISSUE THREAD

**Issue by jimmyjohnsonsmith** [snipe/snipe-it#6568]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)
The file should be deleted.
-----

#### Actual Behavior

I press the delete button and nothing happens with a blank red bar accross the page.
![image](https://user-images.githubusercontent.com/46530982/50906792-e5821900-13f3-11e9-9440-5039fb9389fe.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Fresh install**
- Version of Snipe-IT you're running - **4.6.6**
- Version of PHP you're running - **7.2.13**
- Version of MySQL/MariaDB you're running - **9.4.0.5125**
- What OS and web server you're running Snipe-IT on - **Windows Server 2016**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - **Manual**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - **No Error**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - **https://MYSITE/import**
- If a stacktrace is provided in the error, include that too. - **No Error**
- Any errors that appear in your browser's error console.
![image](https://user-images.githubusercontent.com/46530982/50907203-cb950600-13f4-11e9-832f-43144d58ee59.png)
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - **Not reproducible**
- Include any additional information you can find in `storage/logs` and your webserver's logs. - **No errors in logs**
- Include what you've done so far in the installation, and if you got any error messages along the way. - **Checked permissions, tried different browsers, checked php verbs for DELETE. The files do exist in storage/private_uploads/imports as well in the database. Have also reviewed issue #5034 and #4718**
- Indicate whether or not you've manually edited any data directly in the database - **I have, i'm able to delete the .csv**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by dmeltzer** [comment]
Hi, to confirm you've followed the instructions here? https://snipe-it.readme.io/v4.1.14/docs/windowsiis#section-set-additional-handler-mappings

**Comment by jimmyjohnsonsmith** [comment]
Hi,

Yes. 
![image](https://user-images.githubusercontent.com/46530982/51118209-cad9e680-17dd-11e9-94bc-e4ac53312edf.png)
