### ISSUE TITLE
Test EMAIL does not work. Neither does the I lost password work.

### ISSUE THREAD

**Issue by jbedgood** [snipe/snipe-it#6574]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

When I click the SEND TEST button to test email it just gives the error " Mail could not be sent."
Also when I use the "I forgot password link" I get a page that says "Whoops, looks like something went wrong."

**To Reproduce**
1. Go to '..login page.'
2. Click on '..i forgot my password..'
3. Scroll down to '. input your email address...'
4. See error Whoops, looks like something went wrong.

**Expected behavior**
It should send an email to the email provided with password reset instructions.
**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.7 - build 3944 (master
 - OS: [e.g. Ubuntu, CentOS] CentOS Linux release 7.6.1810 (Core)
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version PHP 7.2.13

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS 10.14.2
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 71.0.3578.98 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade?  Fresh ISO install.
- What OS and web server you're running Snipe-IT on See above
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) ISO
- Include what you've done so far in the installation, and if you got any error messages along the way.

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=mail
MAIL_HOST=10.10.10.11
MAIL_PORT=25
#MAIL_USERNAME=myemail
#MAIL_PASSWORD=mypass
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=engineering@domain.com
MAIL_FROM_NAME='Engineering'
MAIL_REPLYTO_ADDR=engineering@domain.com
MAIL_REPLYTO_NAME='Engineering'

And my postfix config just sends email to my local SMTP relay host. But nothing ever shows up at the Relay Host.

- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by SirajQu** [comment]
Dear can you tell me how did you solve this issue, because I'm facing the same?
