### ISSUE TITLE
Choose which columns to display in reports and to export

### ISSUE THREAD

**Issue by lucasjkr** [snipe/snipe-it#6575]
There was another ticket opened but it was also closed, so I'm opening a new ticket.

We are offered a handful of fields to show in reports (Audit, Admin, Item (tag), Location, etc), but it sure would be nice to be able to choose other columns, like Manufacturer, Model, etc.

Also, I would prefer the Asset Tag appear before the Name (makes for easier sorts).

Is this on anyone's current Work In Progress?

**Comment by lucasjkr** [comment]
Yes, still relevant. Reporting in general.

For instance, in my use case, in the audit log, I'd want to see the asset tag before the asset name. I'd also like the columns to be sortable. And the whole set should be filter-able by company.

My site has equipment from two different entities, so to be able to pull up an audit log for a single company, sort the days til next audit in ascending order, etc... that would be great). As much as I love your product so far (really, I do!), i keep going to PhpMyAdmin to query the DB for reports that aren't built in...

**Comment by snipe** [comment]
You'd need to use the Custom Asset Report for this, and then add/remove columns and sort as needed
