### ISSUE TITLE
Audit report export should export ALL records

### ISSUE THREAD

**Issue by lucasjkr** [snipe/snipe-it#6576]
When I export an audit report, it only exports the 20 records currently on the page. 

Why can't it export the entire found set of assets?

**Comment by lucasjkr** [comment]
CSV output only creates separate values for the table headers, not the data itself?

(rest of data is crammed into the first cell of each row).

I think a new export function needs to be created, rather than the bootstrap-table-export that seems to be used currently. It might yield fewer exportable types, but they would actually work, which would be pretty cool :)

**Comment by Trog3r** [comment]
To add onto this I would love to see the Assets->Assets Maintenances allow for exporting of all records instead of just the records being viewed. Alternatively being able to view All records and then being able to export instead of being limited to 500. Thanks!

**Comment by snipe** [comment]
This is a long-standing issue with the JavaScript table library we use. As soon as there’s a fix for that, it will get fixed across the entire system.

**Comment by raitech-arquivei** [comment]
Yes, it stills relevant for me.

I fact, it is a problem with all listing pages (assets, audit log, activity log, ...). There is a dirty way of circumventing it [here](https://github.com/snipe/snipe-it/issues/3527#issuecomment-298836414), but that is ugly and pernicious.

The Custom Asset Report almost fulfills my need: I must see what assets has been audited and by whom. Another column in Custom Report for that would be great, same for "last_audited_date" in API asset JSON information.
