### ISSUE TITLE
Whoops, looks like something went wrong. - after 1 moths of working app this morning get the error

### ISSUE THREAD

**Issue by ems294** [snipe/snipe-it#6579]
running environment Ubuntu 18.04

3/3) QueryExceptionSQLSTATE[HY000] [2002] No such file or directory (SQL: select * from information_schema.tables where table_schema = snipeit_data and table_name = users)
--
in Connection.php line 647
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit_data', 'users'),object(Closure))in Connection.php line 607
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit_data', 'users'), object(Closure))in Connection.php line 326
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit_data', 'users'))in MySqlBuilder.php line 18
at MySqlBuilder->hasTable('users')in Facade.php line 221
at Facade::__callStatic('hasTable', array('users'))in Setting.php line 68
at Setting::setupCompleted()in CheckForSetup.php line 22
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

(2/3) PDOExceptionSQLSTATE[HY000] [2002] No such file or directory
--
in PDOConnection.php line 47
at PDOConnection->__construct('mysql:host=localhost;port=3306;dbname=snipeit_data', 'snipeit_user', 'password', array(0, 2, 0, false, false))in Connector.php line 65
at Connector->createPdoConnection('mysql:host=localhost;port=3306;dbname=snipeit_data', 'snipeit_user', 'password', array(0, 2, 0, false, false))in Connector.php line 44
at Connector->createConnection('mysql:host=localhost;port=3306;dbname=snipeit_data', array('driver' => 'mysql', 'host' => 'localhost', 'port' => '3306', 'database' => 'snipeit_data', 'username' => 'snipeit_user', 'password' => 'password', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => 'InnoDB', 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' =>true, 'options' => array(), 'name' => 'mysql'), array(0, 2, 0, false, false))in MySqlConnector.php line 24
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => 'localhost', 'port' => '3306', 'database' => 'snipeit_data', 'username' => 'snipeit_user', 'password' => 'password', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => 'InnoDB', 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array(), 'name' => 'mysql'))in ConnectionFactory.php line 183
at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
at call_user_func(object(Closure))in Connection.php line 883
at Connection->getPdo()in Connection.php line 904
at Connection->getReadPdo()in Connection.php line 392
at Connection->getPdoForSelect(true)in Connection.php line 318
at Connection->Illuminate\Database\{closure}('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit_data', 'users'))in Connection.php line 640
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit_data', 'users'),object(Closure))in Connection.php line 607
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit_data', 'users'), object(Closure))in Connection.php line 326
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit_data', 'users'))in MySqlBuilder.php line 18
at MySqlBuilder->hasTable('users')in Facade.php line 221
at Facade::__callStatic('hasTable', array('users'))in Setting.php line 68
at Setting::setupCompleted()in CheckForSetup.php line 22
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

(1/3) PDOExceptionSQLSTATE[HY000] [2002] No such file or directory
--
in PDOConnection.php line 43
at PDO->__construct('mysql:host=localhost;port=3306;dbname=snipeit_data', 'snipeit_user', 'password', array(0, 2, 0, false, false))in PDOConnection.php line 43
at PDOConnection->__construct('mysql:host=localhost;port=3306;dbname=snipeit_data', 'snipeit_user', 'password', array(0, 2, 0, false, false))in Connector.php line 65
at Connector->createPdoConnection('mysql:host=localhost;port=3306;dbname=snipeit_data', 'snipeit_user', 'password', array(0, 2, 0, false, false))in Connector.php line 44
at Connector->createConnection('mysql:host=localhost;port=3306;dbname=snipeit_data', array('driver' => 'mysql', 'host' => 'localhost', 'port' => '3306', 'database' => 'snipeit_data', 'username' => 'snipeit_user', 'password' => 'password', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => 'InnoDB', 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' =>true, 'options' => array(), 'name' => 'mysql'), array(0, 2, 0, false, false))in MySqlConnector.php line 24
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => 'localhost', 'port' => '3306', 'database' => 'snipeit_data', 'username' => 'snipeit_user', 'password' => 'password', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => 'InnoDB', 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array(), 'name' => 'mysql'))in ConnectionFactory.php line 183
at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
at call_user_func(object(Closure))in Connection.php line 883
at Connection->getPdo()in Connection.php line 904
at Connection->getReadPdo()in Connection.php line 392
at Connection->getPdoForSelect(true)in Connection.php line 318
at Connection->Illuminate\Database\{closure}('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit_data', 'users'))in Connection.php line 640
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit_data', 'users'),object(Closure))in Connection.php line 607
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit_data', 'users'), object(Closure))in Connection.php line 326
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit_data', 'users'))in MySqlBuilder.php line 18
at MySqlBuilder->hasTable('users')in Facade.php line 221
at Facade::__callStatic('hasTable', array('users'))in Setting.php line 68
at Setting::setupCompleted()in CheckForSetup.php line 22
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

(1/1) ErrorExceptionfile_put_contents(): Only 0 of 118 bytes written, possibly out of free disk space
--
in Filesystem.php line 122
at HandleExceptions->handleError(2, 'file_put_contents(): Only 0 of 118 bytes written, possibly out of free disk space', '/var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php', 122, array('path' => '/var/www/snipe-it/storage/framework/sessions/HS0voglO4toBfA3JYz9KvTPFBeBTjQEJSwOvg5Qx', 'contents' => 'a:2:{s:6:"_token";s:40:"EKzCUoFC0x1hchYgEgGdA5uyylKYWt1xbeO3tyzp";s:6:"_flash";a:2:{s:3:"old";a:0:{}s:3:"new";a:0:{}}}', 'lock' => true))
at file_put_contents('/var/www/snipe-it/storage/framework/sessions/HS0voglO4toBfA3JYz9KvTPFBeBTjQEJSwOvg5Qx', 'a:2:{s:6:"_token";s:40:"EKzCUoFC0x1hchYgEgGdA5uyylKYWt1xbeO3tyzp";s:6:"_flash";a:2:{s:3:"old";a:0:{}s:3:"new";a:0:{}}}', 2)in Filesystem.php line 122
at Filesystem->put('/var/www/snipe-it/storage/framework/sessions/HS0voglO4toBfA3JYz9KvTPFBeBTjQEJSwOvg5Qx', 'a:2:{s:6:"_token";s:40:"EKzCUoFC0x1hchYgEgGdA5uyylKYWt1xbeO3tyzp";s:6:"_flash";a:2:{s:3:"old";a:0:{}s:3:"new";a:0:{}}}', true)in FileSessionHandler.php line 83
at FileSessionHandler->write('HS0voglO4toBfA3JYz9KvTPFBeBTjQEJSwOvg5Qx', 'a:2:{s:6:"_token";s:40:"EKzCUoFC0x1hchYgEgGdA5uyylKYWt1xbeO3tyzp";s:6:"_flash";a:2:{s:3:"old";a:0:{}s:3:"new";a:0:{}}}')in Store.php line 128
at Store->save()in StartSession.php line 88
at StartSession->terminate(object(Request), object(Response))in Kernel.php line 218
at Kernel->terminateMiddleware(object(Request), object(Response))in Kernel.php line 189
at Kernel->terminate(object(Request), object(Response))in index.php line 63

**Comment by ZephyriusOne** [comment]
Awesome glad to help!

**Comment by JonathonReinhart** [comment]
@ems294 Please close this issue, since it is resolved.

**Comment by ZephyriusOne** [comment]
@ems294  Please close this issue now if resolved.
