### ISSUE TITLE
Idea: LDAP/AD sync: convert to lower case (username / email)

### ISSUE THREAD

**Issue by smb** [snipe/snipe-it#6582]
I just synced our LDAP data to snipeit and now have Some.User@domain.com in my database.

LDAP sync could use some tolower() calls (email, username) - maybe as command-line option for the sync command? (with possible values: uppercase, lowercase, keep current)

What are your thoughts?

**Comment by rmattes** [comment]
This would be wrong. The local part of an rfc-822 compliant email address is case sensitive by the spec so FooBar@example.com and foo.bar@example.com are different mail addresses (even so most, but not all, admins wisely don't had out case-colliding mail addresses and/or have the mail server fix those problems). The LDAP import stage is the totally wrong place to fix your broken setup.
[N.B.:] in a case of madness/ignorance the X-500 consortium decided to make the 'email' attribute compare case insensitive ...
