### ISSUE TITLE
Missing data in custom field listbox which is contained character "

### ISSUE THREAD

**Issue by dhkivan** [snipe/snipe-it#6584]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) > it is similar case #3042

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.7
 - OS: [e.g. Ubuntu, CentOS] CentOS 7
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version: 7.2.13

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10
 - Browser [e.g. chrome, safari] chrome & IE 11

**Smartphone (please complete the following information):**

After upgraded Snipe-IT form 4.6.6 to 4.6.7, we found that the input data will be lost in the custom filed listbox and it contained the character " when re-edit asset.

It is no this problem before upgrade.

Input data
![image](https://user-images.githubusercontent.com/46602090/51042779-1af75400-15f8-11e9-979e-d59d39f0b7c2.png)

![image](https://user-images.githubusercontent.com/46602090/51042848-44b07b00-15f8-11e9-9d26-9e358b80c914.png)

When Re-edit
![image](https://user-images.githubusercontent.com/46602090/51042814-306c7e00-15f8-11e9-8522-62862a4f426f.png)

**Comment by MrMontesa** [comment]
Hey Devs,
I created a custom field for laptops called "screen width" and made it a LISTBOX with format ANY. Then I added items per row like:

14"
15"
16"
19"
when editing an asset, I can choose from the select box and can see that the value is properly saved. The database field contains the correct value. e.g. 14"
When now editing the asset again, the value is not loaded and the select field remains empty. On saving the asset the value is lost and NULL written to the asset table.
I have to always add the screen width manually again.

I renamed the custom field from 14" to 14 inch and all works fine. Seems like there is not enough character encoding for custom fields.
Let me know if you need more info.
Thanks much.

**Comment by JW-IT** [comment]
just adding some version info to my colleague
![image](https://user-images.githubusercontent.com/20500095/92702213-38426f80-f351-11ea-8154-b37e6c08f787.png)
