### ISSUE TITLE
Asset Page Viewing Error (whoops something went wrong)

### ISSUE THREAD

**Issue by ptrev30** [snipe/snipe-it#6586]
#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When I click on the Asset page the "Whoops Something Went Wrong" page comes up
This is a fresh install on IIS Windows Server 2016.  Please help

**To Reproduce**
1. Go to 'dashboard'
2. Click on 'More info underneath assets'
3. See error

**Expected behavior**
The assets list should pop up

**Screenshots**
![image](https://user-images.githubusercontent.com/46636391/51079491-af0aff00-167c-11e9-8377-977d1fc3fa95.png)

**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.7
 - OS: [Windows Server 2016]
 - Web Server: [IIS]
 - PHP Version: 7.3.1 

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [ 71.0.3578.98 ]

(2/2) ErrorExceptioncompact(): Undefined variable: operator (View: C:\inetpub\wwwroot\snipe-it\resources\views\hardware\index.blade.php)
--
in Builder.php line 1229
at CompilerEngine->handleViewException(object(ErrorException), 1)in PhpEngine.php line 44
at PhpEngine->evaluatePath('C:\\inetpub\\wwwroot\\snipe-it\\storage\\framework\\views/1af8e7af68c3eb76505b1fdb721ef685b8a9373a.php', array('__env' =>object(Factory), 'app' => object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => true, 'signedIn' => true, 'user' => object(User), 'company' => null, 'snipeSettings' => object(Setting)))in CompilerEngine.php line 59
at CompilerEngine->get('C:\\inetpub\\wwwroot\\snipe-it\\resources\\views/hardware/index.blade.php', array('__env' => object(Factory), 'app' =>object(Application), 'errors' => object(ViewErrorBag), 'debug_in_production' => true, 'signedIn' => true, 'user' => object(User), 'company' => null, 'snipeSettings' => object(Setting)))in View.php line 137
at View->getContents()in View.php line 120
at View->renderContents()in View.php line 85
at View->render()in Response.php line 38
at Response->setContent(object(View))in Response.php line 206
at Response->__construct(object(View))in Router.php line 615
at Router->prepareResponse(object(Request), object(View))in Router.php line 572
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php line 43
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php line 49
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php line 49
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php line 42
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Router.php line 574
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 533
at Router->dispatchToRoute(object(Request))in Router.php line 511
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php line 51
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php line 25
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php line 27
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

**Comment by ZephyriusOne** [comment]
This is due to using PHP 7.3. I ran into the same problem and corrected it by commenting out the line specified in "Builder.php" (Line 1229).

![image](https://user-images.githubusercontent.com/45017543/51261828-0b249a80-197f-11e9-8ff2-b8387fd944f2.png)

After that every worked fine. I believe this is due to "Operator" not being properly defined. You may be able to just remove "operator" but I never tested that.

If you want to avoid this issue altogether, downgrade to PHP 7.1 or 7.2.

**Comment by ptrev30** [comment]
@ZephyriusOne I removed operator and it fixed it thanks for the help!!

**Comment by ZephyriusOne** [comment]
@ptrev30 No problem. Please mark this issue as closed now. Glad I could help.

**Comment by snipe** [comment]
> This is due to using PHP 7.3. I ran into the same problem and corrected it by commenting out the line specified in "Builder.php" (Line 1229).

This is the wrong solution to this problem. You should never, ever change vendor files. Next time you update, your changes will be gone and you'll have to do it again - plus you don't know what other things it may affect.

I will have a fix out for this shortly.

**Comment by snipe** [comment]
Actually, it seems I can't fix this. It's an issue with the underlying framework. 
https://github.com/laravel/framework/issues/25192

They've fixed it in the framework, but I can't upgrade the framework on v4.x since it requires a [higher version of PHP](https://laravel.com/docs/5.5) and that would be a massively breaking change.

It won't be an issue in Snipe-IT v5, but for now your only option is to downgrade to PHP 7.2.

**Comment by ptrev30** [comment]
> Actually, it seems I can't fix this. It's an issue with the underlying framework.
> [laravel/framework#25192](https://github.com/laravel/framework/issues/25192)
> 
> They've fixed it in the framework, but I can't upgrade the framework on v4.x since it requires a [higher version of PHP](https://laravel.com/docs/5.5) and that would be a massively breaking change.
> 
> It won't be an issue in Snipe-IT v5, but for now your only option is to downgrade to PHP 7.2.

copy
