### ISSUE TITLE
Check-in Consumable 

### ISSUE THREAD

**Issue by suhartiman** [snipe/snipe-it#6587]
How i can checkin Consumables if we purchase same product for update stock and if we cancel distribute for user?. Thanks Snipe

**Comment by SjamonDaal** [comment]
Consumables can't be checked in. They are one time use only.

**Comment by tymik** [comment]
so rather the stock refill of consumable if i understand it right - i'd +1 it if so

**Comment by tellauri** [comment]
Hello, always the same issue

**Comment by tellauri** [comment]
> Check-in for update stock. I can insert purchase number, qty, price. **We no need input new item if we purchases some item. Just update stock**.

**Comment by SH4LT1S** [comment]
Hello how do add more consumables in stock?

**Comment by SjamonDaal** [comment]
> Hello how do add more consumables in stock?

Click edit and change the quantity.

**Comment by AlbertoPeperoni** [comment]
> > Hello how do add more consumables in stock?
> 
> Click edit and change the quantity.

It does not allow to do so.

**Comment by AlbertoPeperoni** [comment]
I am new user of Spipe-IT, and I do agree with above, that consumable should be able to add qty. for already existing consumables toners, to update the stock. We no need input new item if we purchases some item. Just update stock.

**Comment by Shovinus** [comment]
I think consumables really needs a rework.

This is meant for things like tone/paper/labels right?

So you should be able to check them out to specific assets such as printers or locations like you can with assets

This would help with keeping track of what asset is using up what stock the most etc. 

Also it would be nice if you could set up a master line and then do stock control to track purchases and cost rather than cost only being assigned once and 1 order assumed.

**Comment by afranchi74** [comment]
Hi, I agree that:
- consumables, can be used to manage toner, ink, paper, ... so it will be very usefull if we could be able to have a check-in procedure to increase the stock quantity.
- We should be able to check them out to specific assets such as printers or locations like you can with assets and this would help with keeping track of what asset is using up what stock the most etc
Hope you can consider this request in the new release
Regards
Andrea

**Comment by afranchi74** [comment]
any news on this?

**Comment by Schnatterowski** [comment]
+1

Any news?

**Comment by gajotnt** [comment]
1+
Consumables should have a option to update stock and also checkout to a Location/Department/Asset

https://github.com/snipe/snipe-it/issues/553#issuecomment-669332588

**Comment by FahadYousafMahar** [comment]
+1
I'm gonna work on it and send a PR when ready.

**Comment by makeitamaxiday** [comment]
+1
Consumables need an easier way to add stock. When consumables can be checked out to assets, I would love to see a report showing an asset or entire category's consumable usage over time!
