### ISSUE TITLE
Unique Asset Tags Sufix Per Company

### ISSUE THREAD

**Issue by mirso1703** [snipe/snipe-it#6589]
Dear Snipe,

is there a possibility to have snipeit generating tags specific to a company, currently it is scriptwide and cannot be adjusted on the company:

![image](https://user-images.githubusercontent.com/42896769/51098137-2483e600-17c9-11e9-9ea9-8949e86e4626.png)

That every company has its own unique suffix for the asset tag generation?

Thank you

**Comment by Puddl36lum** [comment]
+1

**Comment by FirstUnionGroup** [comment]
+1 for this feature. We have a group of companies and each is expected to have their unique asset tag prefix instead of suffix.
