### ISSUE TITLE
Feature Request: check out asset to location

### ISSUE THREAD

**Issue by it-world** [snipe/snipe-it#659]
We deploy most of our assets to locations (headquarters/offices/datacenters/buildings/floors/rooms...).
Most of the time there is not a physical person who is in charge of this assets (there are teams who maintain them. and a bunch of nodes or users who use them).

It would be great if we have the ability to deploy assets to locations too.

**Comment by dbierspb** [comment]
My current work-around for this was to create a user for the location.

Currently for items checked out to IT as a whole, we have an email distribution list for the entire IT department.  This email address is assigned to this user and as such, we check equipment/assets out to this "user".

**Comment by kobie-chasehansen** [comment]
Same thing we did.

**Comment by it-world** [comment]
Thanks for your replies. 

I had done the same (checked out assets to virtual IT users with different locations), in the end my first snipe it app enabled customer was confused, so i removed this users from the assets last weekend.  ;)

**Comment by snipe** [comment]
I believe this is a duplicate of #142?
