### ISSUE TITLE
Audit Log Add Department

### ISSUE THREAD

**Issue by mirso1703** [snipe/snipe-it#6592]
Dear Snipe,

while working on snipeit and bulk audit log , I've noticed that it doesn't show departments while doing the audit.

![image](https://user-images.githubusercontent.com/42896769/51116099-08506b00-1802-11e9-96b7-df19505de50d.png)

Is there option to add here Department where is device as one of the columns in the audit log?

Thank you

**Comment by snipe** [comment]
Assets don't have departments though...
