### ISSUE TITLE
Getting this error in fresh installation 'Whoops, looks like something went wrong'

### ISSUE THREAD

**Issue by krrishnaemp** [snipe/snipe-it#6593]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I am getting this bug after fresh installation
Whoops, looks like something went wrong

**Screenshots**
f applicable, adId screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/20884703/51133858-fef3ec80-185b-11e9-8c4e-e14105ac5d2e.png)

**Server (please complete the following information):**
 - Snipe-IT Version -4.6.7
 - OS: [e.g. Ubuntu, CentOS] Windows server 2012
 - Web Server: [e.g. Apache, IIS]IIS
 - PHP Version - 5.6.4

**Comment by Jekotia** [comment]
I am experiencing the exact same issue when using the official Docker image.

**Comment by snipe** [comment]
@krrishnaemp you either don't have php-mysql installed, or you don't have php-pdo installed, or both. 
https://stackoverflow.com/questions/35240414/laravel-5-pdoexception-could-not-find-driver
