### ISSUE TITLE
Bulk edit does not affect on the history of assets.

### ISSUE THREAD

**Issue by jackka** [snipe/snipe-it#6600]
*#### Please confirm you have done the following before posting your bug report:*

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

*Describe the bug*
**Bulk edit does not affect on the history of assets.**

*To Reproduce* on demo.snipeitapp.com
1. Select several assets by check boxes.
2. Click on 'Go' the button near "bulk edit" selection list.
3. Change Status for example or Company.
4. Try to find your changes in the history of asset - **No entries found!**

**Expected behavior**
As in single asset edit mode Companies or|and Satuses changes should be logged in history of asset.

**Screenshots**
![6nz7t-ourq3](https://user-images.githubusercontent.com/6271335/51316118-cffc9700-1a64-11e9-9d56-450be7388d7c.gif)

**Server (please complete the following information):**
http://demo.snipeitapp.com

**Desktop (please complete the following information):**
 - OS: win10
 - Browser: Vivaldi | 2.1.1337.51 (Stable channel) (32-bit)
 - Version: production 5.4.35

**Smartphone (please complete the following information):**
no

**Error Messages**
no

**Additional context**
no

**Comment by jackka** [comment]
yes

**Comment by jackka** [comment]
We can't use the bulk edit with this bug..

**Comment by Hsherif90** [comment]
Facing the same issue, I hope it gets fixed soon. Thanks.

**Comment by Hsherif90** [comment]
Not stale, awaiting fix! :)

**Comment by Hsherif90** [comment]
still relevant

**Comment by jackka** [comment]
It is still relevant
