### ISSUE TITLE
On fresh install, the "signatures" folder is not created

### ISSUE THREAD

**Issue by liqnuks** [snipe/snipe-it#6602]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
On the latest docker image, the folder `/var/www/html/storage/private_uploads/signatures` is not automaticly created when it's not exists

**To Reproduce**
Steps to reproduce the behaviour:
1. Run the docker image
2. Configure to have mandatory asset acceptance with signature
3. Check out an asset
4. When the user signs and accepts the asset, we have an HTTP 500 Error 

**Expected behavior**
If the `signatures` folder doesn't exist, it should be created.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.7 - build 3944 (master) 
 - Official docker image

**Error Messages**

```
file_put_contents(/var/www/html/storage/private_uploads/signatures/siglog-215-2019-01-18-043003.png): failed to open stream: No such file or directory
```

**Additional context**
- Fresh install

**Comment by kpko** [comment]
Hi,

I have the same problem on a fresh install via docker. So this problem still exists.
