### ISSUE TITLE
Edit Components from View Asset screen

### ISSUE THREAD

**Issue by Hobadee** [snipe/snipe-it#6603]
**Is your feature request related to a problem? Please describe.**
Managing multiple components assigned to an asset is clunky at best.  Snipe-IT requires you go to each component, and assign it to an asset.  While this workflow is used sometimes, the reverse workflow, where you are dealing with a single asset and adding or removing multiple components, is much more prevalent, but not supported in Snipe-IT.

**Describe the solution you'd like**
The Component tab of the View Asset screen should have an "Add Component" button added to it.  Clicking this button should bring up a dialog box to let you choose a component and Qty to add to the asset.

**Describe alternatives you've considered**
I can think of no other logical way to best add multiple components to a single asset, without a significantly awkward workflow.  (Which already exists.)

**Additional context**
Mock-up screenshots:
Button added to Asset View to add component:
![screen shot 2019-01-18 at 11 46 20 am](https://user-images.githubusercontent.com/3672739/51410295-08f64380-1b19-11e9-8da9-ce9b90775ca0.png)

Dialog box when button is clicked:
![screen shot 2019-01-18 at 12 00 06 pm](https://user-images.githubusercontent.com/3672739/51410288-0267cc00-1b19-11e9-9c32-7a332668f23e.png)

**Comment by Puddl36lum** [comment]
+1

**Comment by Hobadee** [comment]
Still relevant - would be a useful feature.

**Comment by Hobadee** [comment]
Bad bot!

Yes, this feature request is still relevant.

**Comment by Hobadee** [comment]
Bad bot!

**Comment by uFojun** [comment]
+1
