### ISSUE TITLE
Component Creation via Make/Model Workflow

### ISSUE THREAD

**Issue by Puddl36lum** [snipe/snipe-it#6607]
**Server (please complete the following information):**
 - Snipe-IT Version v4.6.6 - build 3926 (master)
 - OS: [e.g. Ubuntu, CentOS] Ubuntu 16.04
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

The components tab is great for non-serialized components but is less ideal for serialized components that are the same make/model/manufacturer and should utilize some of the existing asset workflow. While our assets often come with components installed, we often purchase replacement components separately, and in bulk, (workstation hard drives, for example) which are serialized but don't have asset tags.  In some cases we have dozens, sometimes hundreds of the same component make and model, and scrolling and paging through the components list is cumbersome.  Would also like to capture vendor name at creation.

**Describe the solution you'd like**

Perhaps, using a make/model workflow (similar to assets) where the user/admin can create make/model for a component, and check a box for serial/non-serialized components.  For non-serialized items, a user would set the quantity, and for serialized items, input serials instead of quantity.   I can't think of a component that wouldn't be serialized but it would be good to give the user the option to choose the component type (maybe they don't care to track by serial).  Components could be created in that way, and then, in the components page,  a list of components, make/model, where the individuals were rolled up, hidden, and the user could click to expand the list to view individuals with serials for both available and unavailable components would help with the user experience.  

Would also be helpful to capture vendor information at creation as well.  

**Describe alternatives you've considered**

**Additional context**

**Comment by lapf10** [comment]
+1
