### ISSUE TITLE
Getting error while taking backup

### ISSUE THREAD

**Issue by krrishnaemp** [snipe/snipe-it#6608]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I am getting Error: Backup failed because The dump process failed with exitcode 1 : General error : Access is denied. . while taking the backup

**Screenshots**
![image](https://user-images.githubusercontent.com/20884703/51446666-49350c00-1d3b-11e9-83d5-c2db3543ef29.png)

**Server (please complete the following information):**
 - Snipe-IT Version - 4.3
 - OS: Windows server 2012 R2
 - Web Server: IIS
 - PHP Version : 5.6.4

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by sinichi19** [comment]
Check your .ENV 
DB_DUMP_PATH

Path to the directory that contains mysqldump on your machine. This should point to the directory, not the binary itself.

This is often something like '/usr/bin' on linux systems.

Windows users should use something like: 'C:\\PROGRA~1\\MARIAD~1.0\\bin' or 'C:\\PROGRA~1\\MARIAD~1.1\\bin', depending your version (note the double-slashes).

If you're not sure what the path is to mysqldump, linux users can run which mysqldump and Windows users can use cmd /c for %A in ("C:\Program Files\MariaDB 10.1\bin") do @echo %~sA via command line to reveal the path information.

**Comment by snipe** [comment]
This usually means you have the wrong DB_DUMP_PATH specified, or your Windows user doesn't have access to the tmp directory.
