### ISSUE TITLE
Maintenance review date & Custom Fields

### ISSUE THREAD

**Issue by gilesytheking** [snipe/snipe-it#6609]
**Server (please complete the following information):**
Snipe-IT version | v4.6.7 build 3944
Software License | AGPL3
PHP Version | 7.0.33
Laravel Version | 5.4.35

**Is your feature request related to a problem? Please describe.**
A lot of our equipment & assets need to be tested on a regular basis (When new/received and then every 3, 6 or 12 months) for various reasons (PAT Testing, Servicing, Updates/Upgrades). When an item is PAT Tested, Serviced, etc we need to record certain information regarding the service or test results.

**Describe the solution you'd like**
- Add a renewal date field to "create Asset Maintenance" Page
- Notification/Email for asset Maintenance renewal date as per Notification settings (eg. Item xxxx will require "Asset maintenance Type" in 30 days)

- Create custom fields using the existing custom fields / fieldsets function
- Add a Maintenance Fieldset Dropdown for Asset Models
- Custom Maintenance fields would display after the notes section 

**Describe alternatives you've considered**
Currently using calender's to create reminders for equipment maintenance and servicing.

**Additional context**
![screenshot](https://user-images.githubusercontent.com/15634270/51479828-5a0b6f00-1d87-11e9-8ef5-a8a6516d04a8.png)

![screenshot1](https://user-images.githubusercontent.com/15634270/51479843-6263aa00-1d87-11e9-8f7a-1e56f4a88a37.png)

**Comment by PlasmaDragon** [comment]
This would be an amazing addition!

**Comment by sypher01** [comment]
On my use case, it's really needed ... opening again.

**Comment by gilesytheking90** [comment]
Any update regarding this feature request or this request #6623 - this is a much needed function to keep up to date with services, maintainance, upgrades, etc.

**Comment by YellowJacket51** [comment]
Is there any update on this? I would like to see this added.

**Comment by J3LUNT** [comment]
I'd like to see some type of custom fields here as well similar to asset custom fields.

I would like to track configuration backups that are performed on some of the instruments I have in my assets. 

Backup Fields would be something like:

Type (delta/full/etc)
Software or even vendor can pull through (script/Norton/etc)

Thanks!

**Comment by RobFullerGBHS** [comment]
This would be a great and powerful feature addition, many reasons why assets need regular preventative visitors to manage this in one platform and auto alert would be very welcomed.

Can we get this re-opened?

**Comment by danielnovello-pf** [comment]
The ability to add custom fields to the Maintenance page is kinda needed for us. Any news on this?

**Comment by mtettke123** [comment]
Would be really great to have this. Any updates?

**Comment by snipe** [comment]
No ETA at this time.

**Comment by tristangriffen** [comment]
Any update on this? Would be a very helpful feature.

**Comment by tomaskovacik** [comment]
I vote for this or custom fields in audit

**Comment by seanhowells** [comment]
This would be a gamechanger for us if it could be added

**Comment by liviuzaharia3** [comment]
We would need a custom field named "Benched Hours/Minutes" to track how long an asset has been benched.
This will be uses for KPI related info.
Thanks

**Comment by cyberdocwi** [comment]
+1 

I would like to see this programmed into Snipe-IT as well.  For me, when we send something in for maintenance / repair, we need an RMA number.  This also sees us track problems over a model number or a programming batch.  

Thank you!

**Comment by alex190304** [comment]
Unbelievable this hasn't been added 7 years later...

**Comment by snipe** [comment]
> Unbelievable this hasn't been added 7 years later...

@alex190304 Unbelievable that people think comments like this are helpful in any way...

**Comment by alex190304** [comment]
> > Unbelievable this hasn't been added 7 years later...
> 
> [@alex190304](https://github.com/alex190304) Unbelievable that people think comments like this are helpful in any way...

Fair response. Really enjoy using Snipe IT and would love to see this feature as it often comes up as something we need a solution for, and it would be great if it was built in to what we already use (Snipe IT).
