### ISSUE TITLE
When trying to access The Snipe IT site from IIS, Getting the screen with folder structure.

### ISSUE THREAD

**Issue by hanamanthalli** [snipe/snipe-it#661]
Hi All,

I am getting the attached screen while trying to access the Snipe IT site from IIS server.

I followed the steps as mentioned the Snipe IT manual Guide.

Everything was completed successfully..

But not able to open the site, Can someone Please help on what might be wrong here.

*************************************The page displayed like this**************************
localhost - /snipe-it/

--------------------------------------------------------------------------------
[To Parent Directory]

 3/12/2015 12:17 PM          395 .bash_history
 3/12/2015 12:17 PM           67 .dockerignore
 3/12/2015 12:17 PM           11 .gitattributes
 3/12/2015 12:17 PM          443 .gitignore
 3/12/2015 12:17 PM         1570 .travis.yml
 3/12/2015  4:12 PM        <dir> app
 3/12/2015 12:17 PM         2451 artisan
 3/16/2015 10:37 AM           97 auth.json
 3/16/2015 10:37 AM        <dir> bin
 3/12/2015  4:12 PM        <dir> bootstrap
 3/12/2015 12:17 PM        25943 CHANGELOG.md
 3/12/2015  6:25 PM         1561 composer.json
 3/12/2015 12:17 PM       134044 composer.lock
 3/12/2015 12:17 PM         1857 CONTRIBUTING.md
 3/12/2015  4:12 PM        <dir> docker
 3/12/2015 12:17 PM         2484 Dockerfile
 3/12/2015 12:17 PM         1655 gh-changelog.php
 3/12/2015 12:17 PM        34519 LICENSE
 3/12/2015 12:17 PM          567 phpunit.xml
 3/12/2015  6:35 PM        <dir> public
 3/12/2015 12:17 PM         4443 README.md
 3/12/2015 12:17 PM          522 server.php
 3/16/2015 11:30 AM        <dir> vendor

*****************************************************************************************************
Your valuable inputs are appreciated a lot.

Thanks,
Hanamant

**Comment by madd15** [comment]
the physical path in the site settings should be pointed to the public directory

Site name: Snipe IT
 Physical path: C:\inetpub\wwwroot\snipe-it\public
 Binding
 Type: http
 IP address: All Unassigned or a specific IP if you have one you will be using
 Port: 80 or any you wish to use
 Host name: assets.portal.local (this can be changed to suit your needs)

**Comment by hanamanthalli** [comment]
madd15,

Thanks for the response.

I have followed all the steps as per the Spine IT installation Guide, which already mentions these above points shared by you

Once again i rechecked and everything was as per the guideline and is intact with above points.

Still facing the problem.. Please can someone respond if you know the solution.

Thanks,
Hanamant

**Comment by snipe** [comment]
What happens when you click on the index.php in that directory listing? This almost definitely sounds like your DocumentRoot is wrong (as @madd15 mentioned). The fact that you can see the public directory as a subdirectry in your display means for a fact that public is not set to your document root. Did you restart your web server after setting that document root? That's the only other thing I can think of.

**Comment by hanamanthalli** [comment]
![image](https://cloud.githubusercontent.com/assets/11443099/6665784/8c03287e-cc03-11e4-9e1a-b67741a7acbd.png)


The Screen shown above is displayed and doesn't show up index.html... if i try to click on public and access index.html then i get this screen

![image](https://cloud.githubusercontent.com/assets/11443099/6665818/d69cc368-cc03-11e4-93ec-13f397fd6b42.png)

Yes.. i restarted the web server and started.

What might be the reason?

**Comment by madd15** [comment]
ok i see something odd with your setup. in your default site is snipe-it but you have set up assets.portal.local:8888 as another site. Please turn off the default site and try accessing assets.portal.local:8888 if you have the DNS setup.

ultimately you could delete the default site and set snipe it to use port 80 and localhost

**Comment by snipe** [comment]
FYI, there is no index.html in this app.

**Comment by hanamanthalli** [comment]
Again I tried to setup the website as mentioned by @madd15 in his previous comment.


![image](https://cloud.githubusercontent.com/assets/11443099/6682457/0b9a1da4-cc9f-11e4-936a-520ac0e69169.png)


Am seeing this below screen after setting up everything and clicking on browse button as in the above screenshot.


![image](https://cloud.githubusercontent.com/assets/11443099/6682443/cb3de3a8-cc9e-11e4-8c93-966c47457275.png)

In what times this screen appears

**Comment by madd15** [comment]
Have you ran `php artisan key:generate` with `--env=local` or `--env=production` depending on what your environment. Have you also run `php artisan app:install`?

**Comment by hanamanthalli** [comment]
Yes I did ran these commands

**Comment by hanamanthalli** [comment]
And @madd15 and @snipe 

Am seeing this error as in the screenshot.

![image](https://cloud.githubusercontent.com/assets/11443099/6683954/7d6634a0-ccb2-11e4-9920-7cbcfd0e3b9a.png)

**Comment by madd15** [comment]
Can you please provide the content of your setting table from your database. Thanks

**Comment by hanamanthalli** [comment]
@madd15 , Sorry to mind you.. I am new to this stuff.. can u please guide me how to get this data? if you have any document which gives the steps mentioned that would be great.. 


but as of now i tried from the knowledge what i have currently.. and am seeing these databases in mysql when trying  to get contents from settings table in mysql database using command line as in this screen..

![image](https://cloud.githubusercontent.com/assets/11443099/6684814/b419961a-ccba-11e4-8b76-b6dd8cc7f1b3.png)

**Comment by madd15** [comment]
@hanamanthalli Try out the instructions below and let me know if you have issues.

1. In the MYSQL command line type `CREATE DATABASE Snipe_IT;` (should not use the mysql DB)
2. Now change the `database.php` to point to `Snipe_IT`
3. Now re-run `php artisan app:install` the same way as during the installation
4. In the MYSQL command line type `USE Snipe_IT; SELECT * FROM settings;`
5. If there is nothing there, run the following in the MYSQL command line;
```
INSERT INTO `settings` (`id`,`created_at`,`updated_at`,`user_id`,`per_page`,`site_name`,`qr_code`,`qr_text`,`display_asset_name`,`display_checkout_date`,`display_eol`,`auto_increment_assets`,`auto_increment_prefix`,`load_remote`,`logo`,`header_color`,`alert_email`,`alerts_enabled`,`default_eula_text`,`barcode_type`) VALUES (1,'2015-03-10 22:54:47','2015-03-10 22:54:47',1,50,'Snipe IT Asset Management',NULL,NULL,NULL,NULL,NULL,0,'0',1,NULL,NULL,NULL,1,0,'QRCODE');
```

**Comment by hanamanthalli** [comment]
After running the command Select * from Settings, am getting the below result.

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| snipe_it           |
| test               |
+--------------------+
5 rows in set (0.00 sec)

MariaDB [(none)]> use snipe_it;
Database changed
MariaDB [snipe_it]> select * from settings;
+----+---------------------+---------------------+---------+----------+---------
------------------+---------+---------+--------------------+--------------------
---+-------------+-----------------------+-----------------------+-------------+
------+--------------+-------------+----------------+-------------------+-------
-------+
| id | created_at          | updated_at          | user_id | per_page | site_nam
e                 | qr_code | qr_text | display_asset_name | display_checkout_da
te | display_eol | auto_increment_assets | auto_increment_prefix | load_remote |
 logo | header_color | alert_email | alerts_enabled | default_eula_text | barcod
e_type |
+----+---------------------+---------------------+---------+----------+---------
------------------+---------+---------+--------------------+--------------------
---+-------------+-----------------------+-----------------------+-------------+
------+--------------+-------------+----------------+-------------------+-------
-------+
|  1 | 2015-03-17 11:17:17 | 2015-03-17 11:17:17 |       1 |       50 | Snipe IT
 Asset Management |    NULL | NULL    |               NULL |                  NU
LL |        NULL |                     0 | 0                     |           1 |
 NULL | NULL         | NULL        |              1 | NULL              | QRCODE
       |
+----+---------------------+---------------------+---------+----------+---------
------------------+---------+---------+--------------------+--------------------
---+-------------+-----------------------+-----------------------+-------------+
------+--------------+-------------+----------------+-------------------+-------
-------+
1 row in set (0.00 sec)

MariaDB [snipe_it]>

**Comment by madd15** [comment]
ok try loading the page now

**Comment by hanamanthalli** [comment]
@madd15 .. Thanks a lot for your help, its working now, am able to load the page.

![image](https://cloud.githubusercontent.com/assets/11443099/6686336/28be2bf0-ccc7-11e4-8ca2-65ea05485596.png)

**Comment by madd15** [comment]
@hanamanthalli No worries, glad I could get it sorted for you.


![alt](http://www.reactiongifs.com/r/tcfi.gif)

**Comment by snipe** [comment]
@madd15 nice work! Do we know what happened here? I feel like this isn't the first time the settings table has been donked, and I'd like to see if it's fixabke on our end,

**Comment by snipe** [comment]
(Also, I approve of your use of animated gifs :P )

**Comment by madd15** [comment]
I need to see if I can replicate the issue, so far I can't

**Comment by mikrowiz** [comment]
I'd like to add that running this script to populate the settings table worked for me as well.  During the initial install the settings table came up with all nulls.  Right after the user was created successfully an error was thrown about the notes field not having a default value.

[PDOException]
SQLSTATE[HY000]: General error: 1364 Field 'notes' doesn't have a default value.

I don't know if the installer maybe bailed after that error?  In any case, maybe this can help you in your quest to find out why the settings table isn't populating properly during the install sometimes.  Running the query to manually populate it here got it going for me.  Thanks for that ;)

BTW - this was IIS7 on Windows 2012 R2 with MySQL 5.6.

**Comment by galarg** [comment]
helppp meee :( same issue
