### ISSUE TITLE
User and Asset list  only displays 50 items

### ISSUE THREAD

**Issue by supafly69** [snipe/snipe-it#6610]
#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode yes
No errors 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
Yes 
**Describe the bug**

When adding new asset in the Asset model drop down not all the models are visible. and it scroll bar loops to the top of the list 

**To Reproduce**
1. Go to 'Create New  asset'
2. Click on 'Model drop down'
3. Scroll down to ''
4. See error No error 

**Expected behavior**
I should see the complete list of all the Asset models I created.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version  4.6.7 Build 3944
 - OS: [e.g. Ubuntu, CentOS] 7.2.10-0ubunto
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version  7.2.10-0ubunto

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrom Version 71.0.3578.98 (Official Build) (64-bit) or IE

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] N/A
 - OS: [e.g. iOS8.1] N/A

**Error Messages**
- WITH DEBUG TURNED ON, None
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. No errors 
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. Not  reproducible .
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? Fresh
- What OS and web server you're running Snipe-IT on 7.2.10-0ubunto
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database. Have not.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by supafly69** [comment]
Image of adding new Asset model drop down

**Comment by supafly69** [comment]
closed by mistake

**Comment by snipe** [comment]
Please answer the remaining issue template questions, specifically whether there is anything in your app logs or browser console. We definitely have users with more than 50 users in their system and they haven't run into this issue, so something else is awry here.

**Comment by supafly69** [comment]
[laravel.log](https://github.com/snipe/snipe-it/files/2793652/laravel.log)

**Comment by supafly69** [comment]
javascript?v=1546893874:2106 Uncaught TypeError: Cannot read property 'length' of undefined
    at child.<anonymous> (javascript?v=1546893874:2106)
    at child.set (javascript?v=1546893874:162)
    at child.<anonymous> (javascript?v=1546893874:294)
    at child.set (javascript?v=1546893874:162)
    at Array.<anonymous> (javascript?v=1546893874:973)
    at Function.each (javascript?v=1546893874:2)
    at child.dataChangeHandler (javascript?v=1546893874:967)
    at child.showDataSet (javascript?v=1546893874:955)
    at child.addDataSet (javascript?v=1546893874:917)
    at Object.success (javascript?v=1546893874:932)
(anonymous) @ javascript?v=1546893874:2106
set @ javascript?v=1546893874:162
(anonymous) @ javascript?v=1546893874:294
set @ javascript?v=1546893874:162
(anonymous) @ javascript?v=1546893874:973
each @ javascript?v=1546893874:2
dataChangeHandler @ javascript?v=1546893874:967
showDataSet @ javascript?v=1546893874:955
addDataSet @ javascript?v=1546893874:917
(anonymous) @ javascript?v=1546893874:932
j @ javascript?v=1546893874:2
fireWith @ javascript?v=1546893874:2
x @ javascript?v=1546893874:5
b @ javascript?v=1546893874:5
XMLHttpRequest.send (async)
(anonymous) @ VM232:1
send @ javascript?v=1546893874:5
ajax @ javascript?v=1546893874:5
ajax @ javascript?v=1546893874:1812
load @ javascript?v=1546893874:1804
loadDataSet @ javascript?v=1546893874:931
loadFromId @ javascript?v=1546893874:1049
handle @ javascript?v=1546893874:1034
(anonymous) @ javascript?v=1546893874:1147
XMLHttpRequest.send (async)
(anonymous) @ VM232:1
send @ all.js?id=a3a656ed6316d4c4efe7:3
ajax @ all.js?id=a3a656ed6316d4c4efe7:3
o.initServer @ bootstrap-table.min.js:8
BootstrapTable.initServer @ bootstrap-table-cookie.js?v=1:289
o.init @ bootstrap-table.min.js:7
BootstrapTable.init @ bootstrap-table-mobile.js:91
BootstrapTable.init @ bootstrap-table-cookie.js?v=1:279
o @ bootstrap-table.min.js:7
(anonymous) @ bootstrap-table.min.js:8
each @ all.js?id=a3a656ed6316d4c4efe7:1
each @ all.js?id=a3a656ed6316d4c4efe7:1
a.fn.bootstrapTable @ bootstrap-table.min.js:8
(anonymous) @ users:816
u @ all.js?id=a3a656ed6316d4c4efe7:2
c @ all.js?id=a3a656ed6316d4c4efe7:2
setTimeout (async)
(anonymous) @ all.js?id=a3a656ed6316d4c4efe7:2
u @ all.js?id=a3a656ed6316d4c4efe7:2
fireWith @ all.js?id=a3a656ed6316d4c4efe7:2
fire @ all.js?id=a3a656ed6316d4c4efe7:2
u @ all.js?id=a3a656ed6316d4c4efe7:2
fireWith @ all.js?id=a3a656ed6316d4c4efe7:2
ready @ all.js?id=a3a656ed6316d4c4efe7:2
f @ all.js?id=a3a656ed6316d4c4efe7:1

**Comment by supafly69** [comment]
Next Illuminate\Database\QueryException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' (SQL: select * from information_schema.tables where table_schema = snipeit and tab$
Stack trace:
#0 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
#1 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
#2 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(18): Illuminate\Database\Connection->select('select * from i...', Array)
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Database\Schema\MySqlBuilder->hasTable('users')
#4 /var/www/snipeit/app/Models/Setting.php(68): Illuminate\Support\Facades\Facade::__callStatic('hasTable', Array)
#5 /var/www/snipeit/app/Http/Middleware/CheckForSetup.php(22): App\Models\Setting::setupCompleted()
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 /var/www/snipeit/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#11 /var/www/snipeit/app/Http/Middleware/NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /var/www/snipeit/app/Http/Middleware/ContentSecurityPolicyHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\ContentSecurityPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Clo$
#16 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /var/www/snipeit/app/Http/Middleware/ReferrerPolicyHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\ReferrerPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/snipeit/app/Http/Middleware/XssProtectHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/snipeit/app/Http/Middleware/FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Htt$
#27 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(C$
#28 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Reque$
#30 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Il$
#33 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Reques$
#34 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#37 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#38 /var/www/snipeit/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#39 {main}

**Comment by snipe** [comment]
> Next Illuminate\Database\QueryException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' (SQL: select * from information_schema.tables where table_schema = snipeit and tab$

This means your database credentials are not correct.
