### ISSUE TITLE
Moved mysql db to AWS RDS cannot connect with previously working install.

### ISSUE THREAD

**Issue by dkmansion** [snipe/snipe-it#6611]
#### Expected Behavior (or desired behavior if a feature request)

Expect app to connect to AWS RDS instance of MySQL 5.7.17 with SSL enabled

-----

#### Actual Behavior

Receive SQLSTATE[HY000] [2002] (SQL: select * from information_schema.tables where table_schema = snipeit and table_name = settings) when debug is enabled 

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Neither, functioning version migrating localhost db to AWS RDS then editing .env to point to new db host**
- Version of Snipe-IT you're running - **v4.6.5 - build 3915 (master)**
- Version of PHP you're running - **PHP/5.6.38**
- Version of MySQL/MariaDB you're running - **5.7.17**
- What OS and web server you're running Snipe-IT on  -  **(Red Hat Enterprise Linux 7)  Apache/2.4.6**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - **install.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - **SQLSTATE[HY000] [2002] (SQL: select * from information_schema.tables where table_schema = snipeit and table_name = settings)**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - **Launch of root homepage**
- If a stacktrace is provided in the error, include that too. **

(4/4) QueryExceptionSQLSTATE[HY000] [2002] (SQL: select * from information_schema.tables where table_schema = snipeit and table_name = users)
--
in Connection.php line 647
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'),object(Closure))in Connection.php line 607
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php line 326
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in MySqlBuilder.php line 19
at MySqlBuilder->hasTable('users')in Facade.php line 221
at Facade::__callStatic('hasTable', array('users'))in Setting.php line 68
at Schema::hasTable('users')in Setting.php line 68
at Setting::setupCompleted()in CheckForSetup.php line 22
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 59

(3/4) PDOExceptionSQLSTATE[HY000] [2002]
--
in PDOConnection.php line 47
at PDOConnection::__construct('mysql:host=rdspentpmysql.mydomain.com;port=3306;dbname=snipeit', 'snipeit_user', 'removed_for_sharing', array(0, 2, 0, false, false, null, null, '/var/www/html/snipeit/storage/app/mysql_ssl_certificate/rds-combined-ca-bundle.pem', null))in Connector.php line 65
at Connector->createPdoConnection('mysql:host=rdspentpmysql.mydomain.com;port=3306;dbname=snipeit', 'snipeit_user', 'removed_for_sharing', array(0, 2, 0, false, false, null, null, '/var/www/html/snipeit/storage/app/mysql_ssl_certificate/rds-combined-ca-bundle.pem', null))in Connector.php line 45
at Connector->createConnection('mysql:host=rdspentpmysql.mydomain.com;port=3306;dbname=snipeit', array('driver' => 'mysql', 'host' => 'rdspentpmysql.mydomain.com', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipeit_user', 'password' => 'removed_for_sharing', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => 'InnoDB', 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' =>true, 'options' => array(null, null, '/var/www/html/snipeit/storage/app/mysql_ssl_certificate/rds-combined-ca-bundle.pem', null), 'name' => 'mysql'), array(0, 2, 0, false, false, null, null, '/var/www/html/snipeit/storage/app/mysql_ssl_certificate/rds-combined-ca-bundle.pem', null))in MySqlConnector.php line 24
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => 'rdspentpmysql.mydomain.com', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipeit_user', 'password' => 'removed_for_sharing', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => 'InnoDB', 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array(null, null, '/var/www/html/snipeit/storage/app/mysql_ssl_certificate/rds-combined-ca-bundle.pem', null), 'name' => 'mysql'))in ConnectionFactory.php line 183
at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
at call_user_func(object(Closure))in Connection.php line 883
at Connection->getPdo()in Connection.php line 904
at Connection->getReadPdo()in Connection.php line 392
at Connection->getPdoForSelect(true)in Connection.php line 318
at Connection->Illuminate\Database\{closure}('select * from information_schema.tables where table_schema = ? and table_name = ?',array('snipeit', 'users'))in Connection.php line 640
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php line 607
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'),object(Closure))in Connection.php line 326
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in MySqlBuilder.php line 19
at MySqlBuilder->hasTable('users')in Facade.php line 221
at Facade::__callStatic('hasTable', array('users'))in Setting.php line 68
at Schema::hasTable('users')in Setting.php line 68
at Setting::setupCompleted()in CheckForSetup.php line 22
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 59

(2/4) PDOExceptionSQLSTATE[HY000] [2002]
--
in PDOConnection.php line 43
at PDO->__construct()in PDOConnection.php
at PDOConnection->__construct('mysql:host=rdspentpmysql.mydomain.com;port=3306;dbname=snipeit', 'snipeit_user', 'removed_for_sharing', array(0, 2, 0, false, false, null, null, '/var/www/html/snipeit/storage/app/mysql_ssl_certificate/rds-combined-ca-bundle.pem', null))in Connector.php line 65
at Connector->createPdoConnection('mysql:host=rdspentpmysql.mydomain.com;port=3306;dbname=snipeit', 'snipeit_user', 'removed_for_sharing', array(0, 2, 0, false, false, null, null, '/var/www/html/snipeit/storage/app/mysql_ssl_certificate/rds-combined-ca-bundle.pem', null))in Connector.php line 45
at Connector->createConnection('mysql:host=rdspentpmysql.mydomain.com;port=3306;dbname=snipeit', array('driver' => 'mysql', 'host' => 'rdspentpmysql.mydomain.com', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipeit_user', 'password' => 'removed_for_sharing', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => 'InnoDB', 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' =>true, 'options' => array(null, null, '/var/www/html/snipeit/storage/app/mysql_ssl_certificate/rds-combined-ca-bundle.pem', null), 'name' => 'mysql'), array(0, 2, 0, false, false, null, null, '/var/www/html/snipeit/storage/app/mysql_ssl_certificate/rds-combined-ca-bundle.pem', null))in MySqlConnector.php line 24
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => 'rdspentpmysql.mydomain.com', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipeit_user', 'password' => 'removed_for_sharing', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => 'InnoDB', 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array(null, null, '/var/www/html/snipeit/storage/app/mysql_ssl_certificate/rds-combined-ca-bundle.pem', null), 'name' => 'mysql'))in ConnectionFactory.php line 183
at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
at call_user_func(object(Closure))in Connection.php line 883
at Connection->getPdo()in Connection.php line 904
at Connection->getReadPdo()in Connection.php line 392
at Connection->getPdoForSelect(true)in Connection.php line 318
at Connection->Illuminate\Database\{closure}('select * from information_schema.tables where table_schema = ? and table_name = ?',array('snipeit', 'users'))in Connection.php line 640
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php line 607
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'),object(Closure))in Connection.php line 326
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in MySqlBuilder.php line 19
at MySqlBuilder->hasTable('users')in Facade.php line 221
at Facade::__callStatic('hasTable', array('users'))in Setting.php line 68
at Schema::hasTable('users')in Setting.php line 68
at Setting::setupCompleted()in CheckForSetup.php line 22
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 59

(1/4) ErrorExceptionPDO::__construct(): Cannot connect to MySQL by using SSL
--
in PDOConnection.php line 43
at HandleExceptions->handleError(2, 'PDO::__construct(): Cannot connect to MySQL by using SSL', '/var/www/html/snipeit/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php', 43, array('dsn' => 'mysql:host=rdspentpmysql.mydomain.com;port=3306;dbname=snipeit', 'user' => 'snipeit_user', 'password' => 'removed_for_sharing', 'options' => array(0, 2, 0, false, false, null, null, '/var/www/html/snipeit/storage/app/mysql_ssl_certificate/rds-combined-ca-bundle.pem',null)))
at PDO->__construct('mysql:host=rdspentpmysql.mydomain.com;port=3306;dbname=snipeit', 'snipeit_user', 'removed_for_sharing',array(0, 2, 0, false, false, null, null, '/var/www/html/snipeit/storage/app/mysql_ssl_certificate/rds-combined-ca-bundle.pem', null))in PDOConnection.php line 43
at PDOConnection->__construct('mysql:host=rdspentpmysql.mydomain.com;port=3306;dbname=snipeit', 'snipeit_user', 'removed_for_sharing', array(0, 2, 0, false, false, null, null, '/var/www/html/snipeit/storage/app/mysql_ssl_certificate/rds-combined-ca-bundle.pem', null))in Connector.php line 65
at Connector->createPdoConnection('mysql:host=rdspentpmysql.mydomain.com;port=3306;dbname=snipeit', 'snipeit_user', 'removed_for_sharing', array(0, 2, 0, false, false, null, null, '/var/www/html/snipeit/storage/app/mysql_ssl_certificate/rds-combined-ca-bundle.pem', null))in Connector.php line 45
at Connector->createConnection('mysql:host=rdspentpmysql.mydomain.com;port=3306;dbname=snipeit', array('driver' => 'mysql', 'host' => 'rdspentpmysql.mydomain.com', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipeit_user', 'password' => 'removed_for_sharing', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => 'InnoDB', 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' =>true, 'options' => array(null, null, '/var/www/html/snipeit/storage/app/mysql_ssl_certificate/rds-combined-ca-bundle.pem', null), 'name' => 'mysql'), array(0, 2, 0, false, false, null, null, '/var/www/html/snipeit/storage/app/mysql_ssl_certificate/rds-combined-ca-bundle.pem', null))in MySqlConnector.php line 24
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => 'rdspentpmysql.mydomain.com', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipeit_user', 'password' => 'removed_for_sharing', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => 'InnoDB', 'unix_socket' => '', 'dump_command_path' => '/usr/bin', 'dump_command_timeout' => 300, 'dump_using_single_transaction' => true, 'options' => array(null, null, '/var/www/html/snipeit/storage/app/mysql_ssl_certificate/rds-combined-ca-bundle.pem', null), 'name' => 'mysql'))in ConnectionFactory.php line 183
at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
at call_user_func(object(Closure))in Connection.php line 883
at Connection->getPdo()in Connection.php line 904
at Connection->getReadPdo()in Connection.php line 392
at Connection->getPdoForSelect(true)in Connection.php line 318
at Connection->Illuminate\Database\{closure}('select * from information_schema.tables where table_schema = ? and table_name = ?',array('snipeit', 'users'))in Connection.php line 640
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php line 607
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'),object(Closure))in Connection.php line 326
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in MySqlBuilder.php line 19
at MySqlBuilder->hasTable('users')in Facade.php line 221
at Facade::__callStatic('hasTable', array('users'))in Setting.php line 68
at Schema::hasTable('users')in Setting.php line 68
at Setting::setupCompleted()in CheckForSetup.php line 22
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 59

**

- Any errors that appear in your browser's error console. - **None**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - **Cannot test since demo is not editable by me**
- Include any additional information you can find in `storage/logs` and your webserver's logs. **no additional info**
- Include what you've done so far in the installation, and if you got any error messages along the way. - *This was a fully functioning installation, which I am trying to point to AWS RDS instead of the localhost mysql installation.** 

Tests using the commandline mysql client on the same host are successful. ie

**mysql --host=rdspentpmysql.mydomain.com --port=3306 --database=snipeit --user=snipeit_user -p --ssl-ca=/var/www/html/snipeit/storage/app/mysql_ssl_certificate/rds-combined-ca-bundle.pem**

AWS RDS combined bundle "/var/www/html/snipeit/storage/app/mysql_ssl_certificate/rds-combined-ca-bundle.pem" is set in .env  

Values from .env file
\# --------------------------------------------
\# REQUIRED: DATABASE SETTINGS
\# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=**rdspentpmysql.mydomain.com**
DB_DATABASE=snipeit
DB_USERNAME=snipeit_user
DB_PASSWORD=removed_fo_sharing
DB_PREFIX=null
DB_DUMP_PATH='/usr/bin'

\# --------------------------------------------
\# OPTIONAL: SSL DATABASE SETTINGS
\# --------------------------------------------
DB_SSL=**true**
DB_SSL_KEY_PATH=null
DB_SSL_CERT_PATH=null
DB_SSL_CA_PATH=**'/var/www/html/snipeit/storage/app/mysql_ssl_certificate/rds-combined-ca-bundle.pem'**
DB_SSL_CIPHER=null
**
- Indicate whether or not you've manually edited any data directly in the database - **No**

The permissions for the rds-combined-ca-bundle.pem are 644 for apache:apache

Is there another location that the certificate bundle should be installed in on the host trying to connect to AWS RDS for Laravel to include it or is my CA_PATH value incorrect?

I have also cleared cache to relaunch settings from .env - ie. **sudo php artisan config:clear && sudo php artisan config:cache**
Thanks Greatly!

**Comment by snipe** [comment]
@HinchK @uberbrady can you see if you can reproduce this?

**Comment by dkmansion** [comment]
HI I am still seeing this issue it's unresolved...  Another post alluded to DB_SSL_CIPHER being finicky.  Any suggestions on how I should proceed?

**Comment by HinchK** [comment]
@snipe I recommend we re-open this. @dkmansion thank you for following up

The last time I used CA files for SSL was for replication - the premise is the same, and oh boy, I had issues!

Can you please test when the  `.pem` file's perms are 600?
Are there any errors logged by `(SnipeIT-Root)/storage/logs/laravel.log`?
How about MySQL? `/var/log/mysql/error.log`?

We are slated to do some RDS Testing in the very near future, and I think it would be silly NOT to test these SSL-DB connections with Snipe-IT.  I can't think of a reason that RDS specifically would behave any differently that old-school db replication across multiple datacenters, but I wouldn't throw out the possibility of needing to do something special via the console or CLI to make it work.

**Comment by dkmansion** [comment]
Thanks engagign my AWS owner engineers for the RDS error.log since the web app host did not have any logfile generated.  mysql/mariadb server is not installed on the web host.  Unfortunately I need them to pull the details.  

I did change the perms and that did not advance this still getting PDOExceptionSQLSTATE[HY000] [2002]


Note the aws engineer created a symbolic link to a non root drive for /var/www so this attached log shows the app path as /app/www/snipeit...
[laravel.log](https://github.com/snipe/snipe-it/files/3192559/laravel.log)

testing the cert file with `sudo -u apache cat /path/to/cert`  is successfully read.

This error shows in the laravel.log though.  

Will follow with the mysql/error.log as soon as possible.
![image](https://user-images.githubusercontent.com/5826629/57947339-7e89da80-7893-11e9-8079-a90d6ffab32c.png)

**Comment by barkermn01** [comment]
Could i ask why this is still closed? @snipe as at @HinchK, im also having problems with this exact thing now, 
if `DB_SSL=false` snipe-it has no problem talking to the Database but, if i enable it and set the CA, `DB_SSL_CA_PATH='/var/www/pma/certs/AmazonRootCA1.pem'` it does not work and the system can't make query the server, i know that CA cert is valid it's the exact one being used by PMA on the same server, 

This is a major problem as I'm operating in a GDPR country and snipe it contains personal information of staff members therefor i have to encrypt in transit.

**Comment by HinchK** [comment]
Make sure the permissions on the key are correct: `chmod 400 /var/www/pma/certs/AmazonRootCA1.pem`

Without relevant mysql/log errors you are describing a System Administration issue, which was at the core of the original issue and why it was closed.

Review User/Group ownership and follow those log files!   if the problem persists - please explain it in a new issue.  Good luck ☘️
