### ISSUE TITLE
Entering Maintenance from Asset Details view shows error when attempting to edit or expand maintenance from Asset Maintenances view.

### ISSUE THREAD

**Issue by Jarli01** [snipe/snipe-it#6614]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
If an asset maintenance is entered from the Asset hardware details view, and submitted. When looking at the asset maintenance from the Asset Maintenance specific window produces " Error: Asset Maintenance you were looking for was not found!"

**To Reproduce**
1. Go into the details on any asset with a status of Pending (haven't tested other assets with different status locally), create a maintenance operation within the Asset Details
2. Save the maintenance
3. Go to Assets > Asset Maintenance > Find the asset the local maintenance was performed on, click Edit.

**Expected behavior**
The asset maintenances to apply to the Maintenance view, and to be able to expand it without the displayed error below.

**Screenshots**

![chrome_2019-01-22_09-12-30](https://user-images.githubusercontent.com/14837699/51541044-dce30700-1e25-11e9-842a-84c3bdf34579.png)

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.7
 - OS: [e.g. Ubuntu, CentOS] CentOS 7
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.1.26

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 71.0.3578.98

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error 

No errors reported

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.

I can't reproduce the issue on the demo.

- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? Existing installation, updated with Master branch
- What OS and web server you're running Snipe-IT on CentOS 7, using Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Install Script
- Include what you've done so far in the installation, and if you got any error messages along the way.

I've tested in the Demo environment and can't reproduce

- Indicate whether or not you've manually edited any data directly in the database

No changes have been made. 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Can you do a fresh pull from master? I know we pushed out some maintenance updates a few weeks ago.

**Comment by Jarli01** [comment]
I update regularly (whenever you push to the master branch) and I also check regularly. 

I can pull again, but nothing gets changed.

**Comment by snipe** [comment]
Hm. Without being able to reproduce this locally (or on the demo), I'm not sure how to approach this. 

@inietov - can you bang this around and see if you can reproduce? If you can, we'll need to patch to master and develop, assuming it can be reproduced on both.

**Comment by Jarli01** [comment]
I could backup my entire VM and send you a copy of it if it was so required

**Comment by inietov** [comment]
@Jarli01 Sorry, I was running tests in master and develop. On Assets with status of pending and ready to deploy in both branches and wasn't unabled to reproduce the error, so no idea what can be happening in your install.

**Comment by Jarli01** [comment]
Interesting. Well it's not a world ender. If it becomes more of an issue I'll chase this one up a flag pole and maybe can provide more details.
