### ISSUE TITLE
Feature Request: View licenses checked out to an asset with the hardware API

### ISSUE THREAD

**Issue by bricelabelle** [snipe/snipe-it#6617]
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Our organization would like to be able to use the API to view licenses assigned to an asset. So sending a GET request to /hardware/:id/licenses would return licenses checked out to that asset. I have very little php experience, but working off of issue #6241 , I have this working in my own environment for assets (rather than users in that case).  I plan on submitting a pull request for this feature, so I'm opening this case to track that. 

**Describe alternatives you've considered**

**Additional context**

**Comment by snipe** [comment]
Fixed via #6621
