### ISSUE TITLE
How to complete the chinese translation by myself

### ISSUE THREAD

**Issue by bbingz** [snipe/snipe-it#6622]
**Server (please complete the following information):vm
 - Snipe-IT Version lasts
 - OS: [e.g. Ubuntu, CentOS] CentOS
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.2

**chinese translation is incomlete ,how can I modify it myself.**

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/translations
