### ISSUE TITLE
[Feature request] planned asset maintenance

### ISSUE THREAD

**Issue by GoogolplexM** [snipe/snipe-it#6623]
We would like to register planned maintenance for assets. Ideally this would also send e-mails when planned maintenance date nears. Also after the maintenance adding attachments (maintenance report, certificate, etc) would be great.

**Comment by GoogolplexM** [comment]
This is still relevant, please reopen this issue

**Comment by gilesytheking90** [comment]
is this planned for future development?

Would be great to combine to audit feature with maintenance's (Audit would become a type of maintenance) and have the option to select next due date with email notifications, as is currently with audits.

Could you also add the option to edit/create new maintenance types?

**Comment by gilesytheking** [comment]
Is this a feature that is likely to be released soon? Perhaps with V5? I have over 1000 assets registered on my snipe IT install, 90% of which are subject to regular checks, tests and inspections - PAT Testing, Visual Inspections, Upgrades, Cleaning, Servicing - the list goes on.

Im sure i speak for many snipe IT users that scheduled maintainaces is a key feature required for managing and maintaining our equipment.
