### ISSUE TITLE
Bulk Audit - Input several Asset tags

### ISSUE THREAD

**Issue by bgh88** [snipe/snipe-it#6624]
**Server (please complete the following information):**
 - Snipe-IT Version: Version v4.6.7 - build 3944 (master)
 - OS: Hosted
 - Web Server: Hosted
 - PHP Version: Hosted

**Is your feature request related to a problem? Please describe.**
When we have a list of several assets that have been audited, to track that in Snipe-IT we need to manually copy paste each Asset Tag in to the Bulk Audit function. Which is frustrating and time consuming 

**Describe the solution you'd like**
I'd like to be able to input several asset tags at once, separated with a comma.

**Comment by snipe** [comment]
Bulk audit is designed to be used with a barcode scanner, that’s why it works that way.

**Comment by bgh88** [comment]
Would be great if it could work in multiple ways, to support different workflows

**Comment by bgh88** [comment]
Yes, it is still relevant
