### ISSUE TITLE
How can i access snipeit to my local if the snipe it is on the Virtual Box.

### ISSUE THREAD

**Issue by michaelangelo1991** [snipe/snipe-it#6628]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

My snipe it is on windows 10 pro via wampp it is place on my virtual box.

The Problem is how can i access my snipeit on my VB thru ip on my local.

Thank you

**Comment by snipe** [comment]
This is not a Snipe-IT question, but more of a networking question. 

Here's a link that may help you:
https://www.howtogeek.com/howto/vmware/allow-access-to-a-vmware-virtual-machinenat-from-another-computer/

**Comment by michaelangelo1991** [comment]
Thanks :)
