### ISSUE TITLE
Can't import Active Directory users

### ISSUE THREAD

**Issue by bprfh** [snipe/snipe-it#6629]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Import of ldap users fails, with the error message "username field must be filled out".

**To Reproduce**
1. Go to 'persons'
2. Click on 'ldap sync'
3. See error 'username field must be filled out'

**Expected behavior**
The Active Directory users get imported

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.7 - build 3944 (master) 
 - OS: Debian 8.10 (Jessie)
 - Web Server: Apache
 - PHP Version 5.6

**Desktop (please complete the following information):**
 - OS: Fedora 29 Gnome
 - Browser Firefox
 - Version 64.0.2

**Error Messages**
none

**Additional context**
- Upgrade
- Debian 8.10 (Jessie), Apache
- php upgrade.php
- used and upgraded since August 2018
- No
- Atrribute used for username: sAMAccountName

This error occurs only, if you use the attribute sAMAccountName name for the username field.
CN for example works

**Comment by bprfh** [comment]
I could have sworn the import worked in earlier version with this settings(didn't change it since the installation).
But it works now, sorry for the unnecessary bug report, and thanks for the quick answer!

**Comment by snipe** [comment]
It's been this way for a while (for reasons that are too stupid and boring to get into.) Version 5 reworks a lot of our LDAP stuff, so hopefully this will all get easier soon.
