### ISSUE TITLE
API: Asset by tag endpoint returns 404 instead of 200

### ISSUE THREAD

**Issue by FlipABit** [snipe/snipe-it#6633]
#### Expected Behavior (or desired behavior if a feature request)

Calling the API URI: `/api/v1/hardware/bytag/<asset tag>` on an asset tag that does not exist should return an HTTP 200 status code.

-----

#### Actual Behavior

Calling the API URI: `/api/v1/hardware/bytag/<asset tag>` on an asset tag that does not exist returns an HTTP 404 status code, with a proper JSON response body.

This is inconsistent with the [documentations philosophy](https://snipe-it.readme.io/v4.0/reference#section-philosophy): `For example, if you made a valid HTTP request to retrieve an asset that doesn't exist, we'll return a 200 OK`

Sample Request:

```
curl -X GET \
  http://<HOST>/api/v1/hardware/bytag/187578 \
  -H 'Accept: application/json' \
  -H 'Authorization: Bearer <redacted>' \
  -H 'Content-Type: application/json' \
```
Response:

```
< HTTP/1.1 404 Not Found
< Date: Thu, 24 Jan 2019 18:37:07 GMT
< Server: Apache/2.4.18 (Ubuntu)
< Vary: Authorization
< Cache-Control: no-cache, private
< X-Content-Type-Options: nosniff
< Referrer-Policy: same-origin
< X-XSS-Protection: 1;mode=block
< X-Frame-Options: SAMEORIGIN
< Set-Cookie: snipeit_session=<redacted>; expires=Sat, 02-Feb-2019 02:37:07 GMT; Max-Age=720000; path=/; httponly
< Content-Length: 62
< Content-Type: application/json
<
* Connection #0 to host 127.0.0.1 left intact

{"status":"error","messages":"Asset not found","payload":null}
```

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh install (docker image)

- Version of Snipe-IT you're running
v4.6.7 - build 3944 (master)

- Version of PHP you're running

Whichever version is in the latest docker tag.

- Version of MySQL/MariaDB you're running

MySQL 5.6

- What OS and web server you're running Snipe-IT on

Ubuntu

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

Docker

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error

Using the REST API against `/api/v1/hardware/bytag/<asset tag>`

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by JonathonReinhart** [comment]
I find this behavior to be really confusing. (Returning a 200 when an asset is not found.)

If the asset is found, I get this JSON:
```python
{'asset_tag': '001',
 'assigned_to': {'employee_number': None,
                 'first_name': 'Jonathon',
                 'id': 1,
...
}
```

but if it is not found, I get this:
```python
{'messages': 'Asset not found', 'payload': None, 'status': 'error'}
```

So what is the intended way to check for an "asset not found"? To check the `status` key? That doesn't *quite* conflict with the `status_label` key on the valid asset data, but you can see this is kind of ambiguous.

Returning a 404 seems like the expected result. Of course, this leads to ambiguity between an improper request URL, and a properly-formatted request not finding an asset.

[This StackOverflow answer](https://stackoverflow.com/a/70203231/119527) makes a reasonable suggestion:

> 404 for not-found resource; 400 for not-found URL.

But I feel like this might break too many existing consumers...
