### ISSUE TITLE
504 Gateway Timeout during database migration

### ISSUE THREAD

**Issue by jamesbeamingwhite** [snipe/snipe-it#6635]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
504 Gateway Timeout when running migration via setup

**To Reproduce**
1. Click on 'Next: Create Database Tables'
2. See error

**Expected behavior**
I expected the database migration to complete

**Server (please complete the following information):**
 - Snipe-IT v4.6.7 
 - Laravel Forge on Ubuntu Custom VPS

**Desktop (please complete the following information):**

**Additional context**
Third round of fresh install. Preflight shows all green. I even went as far as setting setting unlimited timeout in php.

Is there other permissions I should look for? Manual setup via CLI steps perhaps?

**Comment by jamesbeamingwhite** [comment]
So threw this up incase someone would hit this before I figured it out. No permission issues. Just a 5 minute long database migration. ~260 migrations is a lot for a fresh install IMHO.

Baking in a feature suggestion would be some method to have fewer migrations to run with only fresh installs and then the incrementing migrations if you are upgrading.

**Comment by snipe** [comment]
>  ~260 migrations is a lot for a fresh install IMHO.

It's really not, when you'r dealing with a project that's been around for a while. But regardless, on a fresh install, those migrations should complete in under a minute. (We manager over 1200 installs, so we see this literally every day.)

> Baking in a feature suggestion would be some method to have fewer migrations to run with only fresh installs and then the incrementing migrations if you are upgrading.

The odds that "old" and "new" would fall out of sync are significantly prohibitive that it's not a feature I'd consider. As I said, on a typical (not crazy high powered) server, those migrations fire off pretty quickly - five minutes is not typical. I'd check the logs to see if there were any errors thrown during migrations which may have hitched things up.
