### ISSUE TITLE
Logos

### ISSUE THREAD

**Issue by jmartins1** [snipe/snipe-it#6637]
Suggestion:

Provide separate or ability to resize logos for SnipeIT GUI and email.

Currently, the logo file used for the SnipeIT GUI and email are shared. The issue is sizing. The logo may appear correct on the GUI but exceptionally out of proportion in email.

Thanks

**Comment by snipe** [comment]
This is already in the upcoming v5

<img width="817" alt="screen shot 2019-01-24 at 2 48 48 pm" src="https://user-images.githubusercontent.com/197404/51713554-30e91980-1fe7-11e9-9e44-169ae700be8e.png">
