### ISSUE TITLE
Migration Issue

### ISSUE THREAD

**Issue by android19** [snipe/snipe-it#6638]
**Server (please complete the following information):**
 - Snipe-IT Version - 4.3.7
 - OS: [e.g. Ubuntu, CentOS] - Windows 10
 - Web Server: [e.g. Apache, IIS] - Wamp, Apache 2.3.47
 - PHP Version - PHP 7.3.1

(3/3) QueryExceptionSQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.oauth_clients' doesn't exist (SQL: insert into `oauth_clients` (`user_id`, `name`, `secret`, `redirect`, `personal_access_client`, `password_client`, `revoked`, `updated_at`, `created_at`) values (, Snipe-IT Personal Access Client, A3X5xKYI1D0Vqn8idTvm3Gy27Vjer5s9wmcUYgm5, http://localhost, 1, 0, 0, 2019-01-25 03:07:36, 2019-01-25 03:07:36))
--
in Connection.php line 647
at Connection->runQueryCallback('insert into `oauth_clients` (`user_id`, `name`, `secret`, `redirect`, `personal_access_client`, `password_client`, `revoked`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?, ?)', array(null, 'Snipe-IT Personal Access Client', 'A3X5xKYI1D0Vqn8idTvm3Gy27Vjer5s9wmcUYgm5', 'http://localhost', true, false, false, '2019-01-25 03:07:36', '2019-01-25 03:07:36'), object(Closure))in Connection.php line 607
at Connection->run('insert into `oauth_clients` (`user_id`, `name`, `secret`, `redirect`, `personal_access_client`, `password_client`, `revoked`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?, ?)', array(null, 'Snipe-IT Personal Access Client', 'A3X5xKYI1D0Vqn8idTvm3Gy27Vjer5s9wmcUYgm5', 'http://localhost',true, false, false, '2019-01-25 03:07:36', '2019-01-25 03:07:36'), object(Closure))in Connection.php line 450
at Connection->statement('insert into `oauth_clients` (`user_id`, `name`, `secret`, `redirect`, `personal_access_client`, `password_client`, `revoked`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?, ?)', array(null, 'Snipe-IT Personal Access Client', 'A3X5xKYI1D0Vqn8idTvm3Gy27Vjer5s9wmcUYgm5', 'http://localhost', true, false, false, '2019-01-25 03:07:36', '2019-01-25 03:07:36'))in Connection.php line 404
at Connection->insert('insert into `oauth_clients` (`user_id`, `name`, `secret`, `redirect`, `personal_access_client`, `password_client`, `revoked`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?, ?)', array(null, 'Snipe-IT Personal Access Client', 'A3X5xKYI1D0Vqn8idTvm3Gy27Vjer5s9wmcUYgm5', 'http://localhost',true, false, false, '2019-01-25 03:07:36', '2019-01-25 03:07:36'))in Processor.php line 32
at Processor->processInsertGetId(object(Builder), 'insert into `oauth_clients` (`user_id`, `name`, `secret`, `redirect`, `personal_access_client`, `password_client`, `revoked`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?, ?)', array(null, 'Snipe-IT Personal Access Client', 'A3X5xKYI1D0Vqn8idTvm3Gy27Vjer5s9wmcUYgm5', 'http://localhost', true, false, false, '2019-01-25 03:07:36', '2019-01-25 03:07:36'), 'id')in Builder.php line 2133
at Builder->insertGetId(array(null, 'Snipe-IT Personal Access Client', 'A3X5xKYI1D0Vqn8idTvm3Gy27Vjer5s9wmcUYgm5', 'http://localhost', true, false, false, '2019-01-25 03:07:36', '2019-01-25 03:07:36'), 'id')in Builder.php line 1251
at Builder->__call('insertGetId', array(array('user_id' => null, 'name' => 'Snipe-IT Personal Access Client', 'secret' => 'A3X5xKYI1D0Vqn8idTvm3Gy27Vjer5s9wmcUYgm5', 'redirect' => 'http://localhost', 'personal_access_client' => true, 'password_client' => false, 'revoked' =>false, 'updated_at' => '2019-01-25 03:07:36', 'created_at' => '2019-01-25 03:07:36'), 'id'))in Model.php line 688
at Model->insertAndSetId(object(Builder), array('user_id' => null, 'name' => 'Snipe-IT Personal Access Client', 'secret' => 'A3X5xKYI1D0Vqn8idTvm3Gy27Vjer5s9wmcUYgm5', 'redirect' => 'http://localhost', 'personal_access_client' => true, 'password_client' => false, 'revoked' =>false, 'updated_at' => '2019-01-25 03:07:36', 'created_at' => '2019-01-25 03:07:36'))in Model.php line 653
at Model->performInsert(object(Builder))in Model.php line 522
at Model->save()in ClientRepository.php line 106
at ClientRepository->create(null, 'Snipe-IT Personal Access Client', 'http://localhost', true)in ClientRepository.php line 121
at ClientRepository->createPersonalAccessClient(null, 'Snipe-IT Personal Access Client', 'http://localhost')in ClientCommand.php line 61
at ClientCommand->createPersonalClient(object(ClientRepository))in ClientCommand.php line 37
at ClientCommand->handle(object(ClientRepository))
at call_user_func_array(array(object(ClientCommand), 'handle'), array(object(ClientRepository)))in BoundMethod.php line 29
at BoundMethod::Illuminate\Container\{closure}()in BoundMethod.php line 87
at BoundMethod::callBoundMethod(object(Application), array(object(ClientCommand), 'handle'), object(Closure))in BoundMethod.php line 31
at BoundMethod::call(object(Application), array(object(ClientCommand), 'handle'), array(), null)in Container.php line 539
at Container->call(array(object(ClientCommand), 'handle'))in Command.php line 182
at Command->execute(object(ArrayInput), object(OutputStyle))in Command.php line 255
at Command->run(object(ArrayInput), object(OutputStyle))in Command.php line 167
at Command->run(object(ArrayInput), object(OutputStyle))in Command.php line 197
at Command->call('passport:client', array('--personal' => true, '--name' => 'Snipe-IT Personal Access Client', 'command' => 'passport:client'))in InstallCommand.php line 32
at InstallCommand->handle()
at call_user_func_array(array(object(InstallCommand), 'handle'), array())in BoundMethod.php line 29
at BoundMethod::Illuminate\Container\{closure}()in BoundMethod.php line 87
at BoundMethod::callBoundMethod(object(Application), array(object(InstallCommand), 'handle'), object(Closure))in BoundMethod.php line 31
at BoundMethod::call(object(Application), array(object(InstallCommand), 'handle'), array(), null)in Container.php line 539
at Container->call(array(object(InstallCommand), 'handle'))in Command.php line 182
at Command->execute(object(ArrayInput), object(OutputStyle))in Command.php line 255
at Command->run(object(ArrayInput), object(OutputStyle))in Command.php line 167
at Command->run(object(ArrayInput), object(BufferedOutput))in Application.php line 946
at Application->doRunCommand(object(InstallCommand), object(ArrayInput), object(BufferedOutput))in Application.php line 248
at Application->doRun(object(ArrayInput), object(BufferedOutput))in Application.php line 148
at Application->run(object(ArrayInput), object(BufferedOutput))in Application.php line 141
at Application->call('passport:install', object(Collection), null)in Kernel.php line 220
at Kernel->call('passport:install')in Facade.php line 221
at Facade::__callStatic('call', array('passport:install'))in SettingsController.php line 259
at SettingsController->getSetupMigrate()
at call_user_func_array(array(object(SettingsController), 'getSetupMigrate'), array())in Controller.php line 55
at Controller->callAction('getSetupMigrate', array())in ControllerDispatcher.php line 44
at ControllerDispatcher->dispatch(object(Route), object(SettingsController), 'getSetupMigrate')in Route.php line 203
at Route->runController()in Route.php line 160
at Route->run()in Router.php line 572
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php line 49
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php line 49
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php line 42
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Router.php line 574
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 533
at Router->dispatchToRoute(object(Request))in Router.php line 511
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php line 51
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php line 25
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php line 35
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Please Help regarding on this issue . Thanks

**Comment by EarlRamirez** [comment]
@android19 can you try _php artisan migrate --force_ and let us know if you see the same behaviour. This command must be executed from your snipe-it directory, for example, /var/www/html/snipe-it/
