### ISSUE TITLE
Can't sync AD after removing OU

### ISSUE THREAD

**Issue by louisdj** [snipe/snipe-it#6639]
Context: We use Snipeit for a few years now and with the company growing, we decided to re-structure our Active Directory. Some OU's are deleted or replaced and new OU's are created.

#### Expected Behavior (or desired behavior if a feature request)

When I go to users > LDAP sync > press the synchronize button (without selecting a location), I expect a full sync of my AD users.
-----

#### Actual Behavior

After pressing the sync button, an error is show, and as I understood, the search query is looking for an OU that is deleted. 

`

(1/1) ErrorExceptionldap_search(): Search: No such object
--
in Ldap.php line 262
at HandleExceptions->handleError(2, 'ldap_search(): Search: No such object', '/var/www/html/app/Models/Ldap.php', 262, array('base_dn' => 'OU=Strategy,OU=ITP Employees,DC=itpagency,DC=be', 'ldapconn' => resource, 'ldap_bind' => null, 'filter' => '&(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))', 'page_size' => 500, 'cookie' => '', 'result_set' => array(), 'global_count' => 0, 'ldap_paging' => true))
at ldap_search(resource, 'OU=Strategy,OU=ITP Employees,DC=itpagency,DC=be', '(&(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))')in Ldap.php line 262
at Ldap::findLdapUsers('OU=Strategy,OU=ITP Employees,DC=itpagency,DC=be')in LdapSync.php line 128
at LdapSync->handle()
at call_user_func_array(array(object(LdapSync), 'handle'), array())in BoundMethod.php line 29
at BoundMethod::Illuminate\Container\{closure}()in BoundMethod.php line 87
at BoundMethod::callBoundMethod(object(Application), array(object(LdapSync), 'handle'), object(Closure))in BoundMethod.php line 31
at BoundMethod::call(object(Application), array(object(LdapSync), 'handle'), array(), null)in Container.php line 539
at Container->call(array(object(LdapSync), 'handle'))in Command.php line 182
at Command->execute(object(ArrayInput), object(OutputStyle))in Command.php line 255
at Command->run(object(ArrayInput), object(OutputStyle))in Command.php line 167
at Command->run(object(ArrayInput), object(BufferedOutput))in Application.php line 946
at Application->doRunCommand(object(LdapSync), object(ArrayInput), object(BufferedOutput))in Application.php line 248
at Application->doRun(object(ArrayInput), object(BufferedOutput))in Application.php line 148
at Application->run(object(ArrayInput), object(BufferedOutput))in Application.php line 141
at Application->call('snipeit:ldap-sync', object(Collection), null)in Kernel.php line 220
at Kernel->call('snipeit:ldap-sync', array('--location_id' => '11', '--json_summary' => true))in Facade.php line 221
at Facade::__callStatic('call', array('snipeit:ldap-sync', array('--location_id' => '11', '--json_summary' => true)))in UsersController.php line 876
at UsersController->postLDAP(object(Request))
at call_user_func_array(array(object(UsersController), 'postLDAP'), array(object(Request)))in Controller.php line 55
at Controller->callAction('postLDAP', array(object(Request)))in ControllerDispatcher.php line 44
at ControllerDispatcher->dispatch(object(Route), object(UsersController), 'postLDAP')in Route.php line 203
at Route->runController()in Route.php line 160
at Route->run()in Router.php line 572
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php line 43
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php line 49
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php line 49
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php line 42
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Router.php line 574
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 533
at Router->dispatchToRoute(object(Request))in Router.php line 511
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php line 51
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php line 25
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php line 27
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

`

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  upgrade
- Version of Snipe-IT you're running: 4.6.7
- Version of PHP you're running: docker container
- Version of MySQL/MariaDB you're running: MySQL 
- What OS and web server you're running Snipe-IT on: docker
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): docker
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: see above
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: /users/ldap
- If a stacktrace is provided in the error, include that too: see above
- Any errors that appear in your browser's error console.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
I assume you updated the OU in the admin settings?

**Comment by louisdj** [comment]
No, the OU for the search filter stayed the same. 
For example we have an OU called "Employees" and under that OU we had an OU for each team while now we have to OU "Employees" with under this OU and OU for each departement instead of teams.

However, Snipite is still looking for the OU of each team...

**Comment by louisdj** [comment]
@snipe Any idea how we can fix this?
