### ISSUE TITLE
"Perfect" csv import creates corrupt asset. List All assets no longer shows any assets.

### ISSUE THREAD

**Issue by aRiflip** [snipe/snipe-it#6640]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
List All assets doesn't show any assets. Failed asset creation actually creates a corrupt asset that can't be viewed or deleted.

**To Reproduce**
1. Create csv using the "sample csv" and removing the "not required" described in csv requirements section. (Many discrepancies between the two)
2. Import CSV
3. Process CSV
4. Category ID is required error.
5. Go to Dashboard - See 5 new Recent Activities
6. Click List All Assets - See no assets 

**Expected behavior**
To import the asset correctly

**Screenshots**
![capture01](https://user-images.githubusercontent.com/4913114/51737125-bf12dd80-2083-11e9-8a4d-c46996659b95.PNG)
![capture02](https://user-images.githubusercontent.com/4913114/51737138-c89c4580-2083-11e9-9dd6-d81f94ba6cc5.PNG)

**Server (please complete the following information):**
 - Snipe-IT Version - v4.1.10-pre  build 3215 (gf08bec6) 
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version - 7.0.32-0ubuntu0.16.04.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, Firefox, Edge

**Additional context**
Ideally, some up to date db restoration guides. Every post says something doesn't work or something is decrepit.

Love the program :)

**Comment by snipe** [comment]
Are you actually providing a category?

**Comment by aRiflip** [comment]
I didn't. And looking through the documentation I now see it is mentioned in the "Common fields". I was only looking at "Asset-only field". My bad.
I have managed to get my database restored now and the corrupt asset has been removed and "List All" lists all assets again :)

**Comment by snipe** [comment]
Excellent - glad you’e sorted. I know the importer documentation can be a little confusing. There are so many different variations of types of imports (assets without users associated, assets with users associated, licenses, etc), and I think we need to just suck it up and duplicate the information in the imports section for each variation to make it more clear.

**Comment by aRiflip** [comment]
Heh, I have another issue now. Pretty sure its related to doing the restore. I can no longer upload csv files anymore. "File(s) not uploaded. Please try again."
