### ISSUE TITLE
Php artisan key:generate

### ISSUE THREAD

**Issue by wisin-003** [snipe/snipe-it#6643]
#### Expected Behavior (or desired behavior if a feature request)
To generate key
(what you expect to happen goes here)
Generate Key
-----

#### Actual Behavior
Error: file_get_contents (c:\wamp\www\snipe-it/.env):  no such file or directory 
(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ n] I have enabled debug mode 
- [ y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? yes
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on -- Win10
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. CMD key generate error 
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Did you actually create the .env file?

**Comment by wisin-003** [comment]
> Did you actually create the .env file?

no. Whats there came from the download.

**Comment by snipe** [comment]
You have to create the .env file, [per the installation instructions](https://snipe-it.readme.io/docs/configuration).

**Comment by wisin-003** [comment]
Ok that worked. that went over my head! THX .. now im doing the virtual host settings. cant get that to work.

**Comment by arjunks94** [comment]
i have the env file created , i am not able to create key its giving a different error, please assis
![Screenshot from 2022-08-27 18-57-23](https://user-images.githubusercontent.com/84993460/187038244-c077a42d-cd14-4b2b-95e3-ea27533cef98.png)
t

**Comment by snipe** [comment]
What do you have as your APP_URL in your .env? https://github.com/snipe/snipe-it/issues/11213

**Comment by arjunks94** [comment]
http://dohsisnipeit.com
