### ISSUE TITLE
Can not update setting after upgrading from 3.6 to 4.6

### ISSUE THREAD

**Issue by sabinlald** [snipe/snipe-it#6646]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by sabinlald** [comment]
after upgrading from 3.6 to 4.6 not able to change any settings or save any settings file ..while viewing error logs

 `Stack trace:
#0 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(27): Illuminate\Encryption\Encrypter->__construct('XVP\xF2\xAB\xFDl\x9A\xA5\xEB_\x97\x8E\x08\x89...', 'rijndael-256')
#1 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(726): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Illuminate\Foundation\Application), Array)
#2 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build(Object(Closure))
#3 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\Container\Container->resolve('encrypter')
#4 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\Container\Container->make('encrypter')
#5 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(862): Illuminate\Foundation\Application->make('encrypter')
#6 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(790): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#7 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(757): Illuminate\Container\Container->resolveDependencies(Array)
#8 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(608): Illuminate\Container\Container->build('App\\Http\\Middle...')
#9 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(575): Illuminate\Container\Container->resolve('App\\Http\\Middle...')
#10 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): Illuminate\Container\Container->make('App\\Http\\Middle...')
#11 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(215): Illuminate\Foundation\Application->make('App\\Http\\Middle...')
#12 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(189): Illuminate\Foundation\Http\Kernel->terminateMiddleware(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#13 /var/www/html/snipe-it/public/index.php(63): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\Response))
#14 {main}  
`
![screenshot from 2019-01-27 01-26-18](https://user-images.githubusercontent.com/11918886/51791985-79fdc100-21d3-11e9-951f-44de007899ed.png)
 I am using Ubuntu 16 with php 7.0

**Comment by snipe** [comment]
Did you follow the instructions for upgrading from v3 to v4?

**Comment by sabinlald** [comment]
Yes i did as per instructions in documents.

**Comment by ZephyriusOne** [comment]
The error messages would suggest your APP_KEY value is somehow not correct. Try the below steps.


Run this command: **php artisan key:generate**

Clear the config cache using: **php artisan config:clear**


This may solve the problem for you.

**Comment by ZephyriusOne** [comment]
@sabinlald Did you manage to get this working?
