### ISSUE TITLE
object not found http://localhost/licenses/create

### ISSUE THREAD

**Issue by 03weng** [snipe/snipe-it#6647]
![capture](https://user-images.githubusercontent.com/46996852/51801535-a9a2dc80-2258-11e9-96fb-08cd614d9c10.PNG)

This misght be a simple one but i really have no idea.
Thanks

**Comment by EarlRamirez** [comment]
Can you complete the template, this will give the community sufficient information so that you can get the help you are seeking.

**Comment by ZephyriusOne** [comment]
Just curious, are you using XAMPP?
