### ISSUE TITLE
2FA Remember this device for 30 days

### ISSUE THREAD

**Issue by 1soproni** [snipe/snipe-it#6648]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.8
 - OS: Debian
 - Web Server: Apache
 - PHP Version 7.1

I would like to see a checkbox on 2FA that "Remember this device for 30 days"

2FA is very useful but I use snipeit on my office PC in 95%. Would be great if snipeit could remember for that PC but asked 2FA everywhere else.

**Comment by EarlRamirez** [comment]
Just curious about this, are you closing your browser each time? Are your expectations to have 2FA remembered across reboots? Are you using Snipe-IT HTTP or HTTPS?

**Comment by 1soproni** [comment]
Sorry, it works well.
