### ISSUE TITLE
LDAP Feature is not turned on

### ISSUE THREAD

**Issue by smannon** [snipe/snipe-it#6651]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode = NO
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) - YES

**Describe the bug**
So I know that Snipe-IT allows for LDAP connections and have read many of the support articles mentions not being able to login, but the one that I need and haven't found is how to "ENABLE" LDAP if going to the "Admin" section and clicking on LDAP you receive this error.
"It doesn't look like the LDAP extension is installed or enabled on this server. :("

**To Reproduce**
1. Go to '...' Admin; LDAP
2. Click on '....' Click on LDAP
4. See error "It doesn't look like the LDAP extension is installed or enabled on this server. :( "

**Expected behavior**
Configuration page for LDAP settings.
**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version - 4.6.7
 - OS: [e.g. Ubuntu, CentOS] - Windows Server 2018
 - Web Server: [e.g. Apache, IIS] - IIS
 - PHP Version - 7.3.1

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Windows
 - Browser [e.g. chrome, safari] - IE 11
 - Version [e.g. 22] - 11

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
So, you should install/enable[ the PHP LDAP extension](http://php.net/manual/en/book.ldap.php).
