### ISSUE TITLE
Date fields do not respect date format

### ISSUE THREAD

**Issue by ebonweaver** [snipe/snipe-it#6652]
#### Expected Behavior (or desired behavior if a feature request)

When you create a custom field of type DATE, the format for that field will obey the Localization settings.

-----

#### Actual Behavior

DATE fields are always some set format and ignore Localization

-----
#### Additional Info:

 Confirmed in 4.6.8 online demo.  
Set localization to US English with format style 10/07/18.
Use any Date field in an asset, custom or otherwise.
Paste in 10/07/18 and watch is do weird things changing the date to other formats and years.

The DATE format is so unwieldy as is we create all fields as ANY instead so we can actually paste in date strings.

**Comment by OneRFeris** [comment]
This is still happening on v4.8.0 - build 4186.

**Comment by RattleSkull** [comment]
Its happening on v4.7.8 build 4170 too. If I want to use the Format DD.MM.YYYY it changes 17.01.2020 to 22-07-13 which doesn't make any sense. But if you change the date through the REST API it works fine.
