### ISSUE TITLE
check in/out requestable assets

### ISSUE THREAD

**Issue by nmmclwhitehead** [snipe/snipe-it#6656]
**Server (please complete the following information):**
 - Snipe-IT Version  v4.6.5 build 3915 (gc7596e774)
 - OS: Ubuntu 16.04
 - Web Server: Apache
 - PHP Version 7.1

**Describe the solution you'd like**
have the ability for user to be able to check out and check in a requestable asset instead of only request.
the goal is so the user can checkout and in laptops that are spare loaners.

**Additional context**
![image](https://user-images.githubusercontent.com/46906609/51911977-280a9600-23a1-11e9-9517-7728a192fde2.png)

**Comment by GuessWild** [comment]
+1. we would benefit from this too. we have loanee pc’s that users sign off on paper sheet, having it in snipe it would be great feature.

**Comment by snipe** [comment]
Sounds like this might be related to #5994?
