### ISSUE TITLE
virtual host settings

### ISSUE THREAD

**Issue by wisin-003** [snipe/snipe-it#6659]
#### Please confirm you have done the following before posting your bug report:

- [no ] I have enabled debug mode 
- [yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I get this message: **D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory.**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS] 
 - Web Server: [e.g. Apache, IIS] WAMP
 - PHP Version - 7.2.14

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win10 
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by wisin-003** [comment]
ServerName localhost:http://192.168.168.37/snipeit:80

#
# Deny access to the entirety of your server's filesystem. You must
# explicitly permit access to web content directories in other
# <Directory> blocks below.
#
<Directory />
    AllowOverride All
    Require all granted
</Directory>

#
# Note that from this point forward you must specifically allow
# particular features to be enabled - so if something's not working as
# you might expect, make sure that you have specifically enabled it
# below.
#
HostnameLookups Off

#
# DocumentRoot: The directory out of which you will serve your
# documents. By default, all requests are taken from this directory, but
# symbolic links and aliases may be used to point to other locations.
#
DocumentRoot "C:/wamp/www/snipeit/public/"
<Directory "C:/wamp/www/snipeit/public/">

**Comment by huangshifang** [comment]
@wisin-003 
It might help you decide,and open" http://localhost "in web browser.

<VirtualHost *:80>
  ServerName localhost
  ServerAlias localhost
  DocumentRoot "F:/wamp/www/snipe-it/public"
  <Directory "F:/wamp/www/snipe-it/public">
    Options +Indexes +Includes +FollowSymLinks +MultiViews
    AllowOverride All
    Require local
 Require all granted
  </Directory>
