### ISSUE TITLE
Create account to add maintenance on printers

### ISSUE THREAD

**Issue by rgerritsen** [snipe/snipe-it#6662]
Is it possible to create an account that have privileges to only add maintenance entry's to our printers?

**Comment by snipe** [comment]
I'm not sure what the question is here, since I don't know how your organization and assets are set up. Are your printers assets or accessories? Are you asking for an "only maintenance" permission?

**Comment by rgerritsen** [comment]
Hi,
Yes my printers are assets. I want to create an account for our printer technician to register his work. 
Is this possible?
