### ISSUE TITLE
Windows/IIS Backup Error

### ISSUE THREAD

**Issue by blanchardc** [snipe/snipe-it#6668]
#### Actual Behavior

When running a backup from the GUI it fails with a general error. 
`'Error: Backup failed because The dump process failed with exitcode 1 : General error : The filename, directory name, or volume label syntax is incorrect. .'`

-----

#### Please confirm you have done the following before posting your bug report:

- [x]  I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh Install
- Version of Snipe-IT you're running 
v4.6.8
- Version of PHP you're running 
7.2.1.4
- Version of MySQL/MariaDB you're running 
10.0.37
- What OS and web server you're running Snipe-IT on
Windows 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
GIT
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
/admin/backups
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
Error is the same as in the error message 
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Cannot reproduce in the online demo
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
No errors during the install. This is the first error. 
- Indicate whether or not you've manually edited any data directly in the database
No changes have been made in the database 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

![error](https://user-images.githubusercontent.com/23637034/52018336-ace3d580-24af-11e9-9cf9-f45526efd8a8.PNG)

**Comment by snipe** [comment]
This usually means the DB_DUMP_PATH is incorrect in your settings. What do you have for that value?

**Comment by blanchardc** [comment]
DB_DUMP_PATH='C:\Program Files\MariaDB 10.0\bin'

**Comment by snipe** [comment]
Have you tried the paths listed in [the documentation](https://snipe-it.readme.io/docs/configuration#section-required-database-settings)?

**Comment by blanchardc** [comment]
I have tried changing it to: C:\PROGRA~1\MariaDB 10.1\bin and get the same error. I did the config cache clear after changing the DB_DUMP_PATH. Same result.

**Comment by snipe** [comment]
You likely need the double-slashes. There are instructions on how to find your correct path in those docs.

**Comment by blanchardc** [comment]
I tried the double-slashes as well. And ran the CMD in the docs to get the path. Didn't work with the double-slashes.

**Comment by nacabuta** [comment]
I found the solution here and worked for me
[SNIPE-IT BackUp Fix](https://www.youtube.com/watch?v=_Ofy9nT5fek)

**Comment by blanchardc** [comment]
@nacabuta - Thanks for the link. I had the DB_DUMP_PATH correct and the folder permissions but didn't restart IIS after making the changes. After restarting IIS the backup started working. Thanks for the help!
