### ISSUE TITLE
Assigned type value not populating via API

### ISSUE THREAD

**Issue by mattcdavis1** [snipe/snipe-it#6673]
- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When adding a hardware asset via the API the `assigned_type` column does not populate with a value.  Adding `assigned_type` to the API call does not help either.

**To Reproduce**
1. Create a hardware asset with the API that is assigned to a user via the `assigned_to` field

**Expected behavior**
The assigned_type field would populate with a value or alternative passing in `assigned_type` would populate this field with a value.

**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.8 build 3959 (g194d0733d)
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version: 7.2

**Comment by snipe** [comment]
You have to pass the ID of checkout target as `assigned_user`, `assigned_asset`, or `assigned_location`.

https://github.com/snipe/snipe-it/blob/master/app/Http/Controllers/Api/AssetsController.php#L521-L526

**Comment by mattcdavis1** [comment]
got it - thanks!
