### ISSUE TITLE
User List page timing out

### ISSUE THREAD

**Issue by shemken** [snipe/snipe-it#668]
Not sure if this is an issue or just something wonky with my install.  Everything has been working fine on the newest version, I'm running on a turnkey Debian installation.  I started the process of importing my users from a .csv file that I had exported from Active Directory, after the second attempt at importing (first attempt I got a time out php error, second attempt I got an out of memory error) now the screen is just blank and never loads at admin/users.

Everything else still seems to be functioning, in-fact I was still able to assign a new asset to a new user that had been imported during the above mentioned process. 

Thanks for any help

**Comment by snipe** [comment]
How many users do you have? I haven't heard of this issue before, but we can certainly try to help figure it out.

**Comment by shemken** [comment]
The .csv file that I uploaded had 800+ users to import.  The first time it got through it got like 310 of them when the first error came up.  Then I deleted out all the lines of users that looked like they successfully imported and tried it again.  The second time was around 513 users, that's when I got the out of memory error.  

After the first error when I imported around 300 users I was able to go to the user page and see all the users listed, it wasn't until after the second attempt that the user page is no longer available.  It doesn't produce any error on the screen it's just a blank white page.  I've tried it in Safari and Google Chrome, if I "view source" in chrome I get a blank page as well with no output.

**Comment by snipe** [comment]
Do you have anything in your server logs or application logs?

**Comment by shemken** [comment]
looking through logs, is there a specific log that I should look at?  Nothing is standing out to me in /var/log/messages or /var/log/apache2 stuff.. but maybe not looking in the right place.

**Comment by snipe** [comment]
Do you have an `error_log` in your `/var/log/apache2` directory? Anything there? See http://snipeitapp.com/documentation/getting-help/ for location of the app logs.

**Comment by shemken** [comment]
Bingo, I'm sure this means something, it seems like a similar error that I saw when it error'd out trying to import, although this error is talking about the vendor page it looks like, but I had tail on and that's the exact error that came up when I tried accessing the "people" link:

PHP Fatal error:  Allowed memory size of 33554432 bytes exhausted (tried to allocate 196605 bytes) in /snipeit/snipe-it/vendor
/laravel/framework/src/Illuminate/Database/Connection.php on line 301, referer: http://inventory.rsdnmp.org/

**Comment by shemken** [comment]
Trying to up my PHP memory in php.ini to 64 instead of the default 32, seeing if that helps

**Comment by snipe** [comment]
Okay, that's helpful. Which version are you using? `2.6.1`, or the latest from `develop` or `master`?

**Comment by snipe** [comment]
(Make sure you restart the web server after increasing the memory limit btw)

**Comment by shemken** [comment]
Apache/2.2.22 (Debian) PHP/5.4.36-0+deb7u3 mod_python/3.3.1 Python/2.7.3 mod_ssl/2.2.22 OpenSSL/1.0.1e mod_perl/2.0.7 Perl/v5.14.2 configured -- 

Snipe-IT - 1.2.6 (what it says at the bottom of the screen)

**Comment by snipe** [comment]
Sorry, that was weirdly dyslexic. Yes, I meant 1.2.6. We did release 1.2.6.1 (just a few minor fixes) but I'm not sure that's going to help you here. We have a revamped Users section on develop, but I don't think it's ready for production usage yet. We're looking into this. Hang tight.

**Comment by shemken** [comment]
Ok got it, I had to up the php.ini config in both of these locations:

/etc/php5/apache2/php.ini
/etc/php5/cli/php.ini

success, I've got my user list back and no error when clicking on the "people" link

**Comment by snipe** [comment]
Excellent, glad to hear it. We've been working on better handling for the users and assets page for > 1000 entries (that's what's on develop) so hopefully this should be less gnarly soon.

**Comment by shemken** [comment]
On a side note, I'm sure it's available or coming soon, is it very easy to connect this up to LDAP (active directory), if so point me in the documentation location

**Comment by snipe** [comment]
It's an open issue, but hasn't been started yet. We know some folks definitely need/want it.

**Comment by shemken** [comment]
Oh lame I think I already tweeted that at you... sorry consider this close.
