### ISSUE TITLE
[Question] How to handle "Combo kit" peripherals

### ISSUE THREAD

**Issue by acerspyro** [snipe/snipe-it#6687]
From what I understand, the issue tracker is the correct place to ask questions like these.

In our workplace, we order a lot of "bundled" hardware such as the Logitech MK540. The boxes for these have one serial number, and once you open them, the mouse and keyboard both have completely different serials.

![image](https://user-images.githubusercontent.com/4400999/52302065-1a817d00-295a-11e9-8476-71189c0c0f78.png)

How is this usually handled to keep track of our stock? We obviously don't want to open every box just to check the serials of the mouse and keyboard within, and we don't want to delete the combo box from our inventory and then re-create a mouse and a keyboard item once it is opened.

**Comment by 5quirrel** [comment]
You can record the other items as either assets or components and then check them out to the kit being its own asset. Then check out the kit when you deploy it.

**Comment by acerspyro** [comment]
@5quirrel I guess that's one solution.

We'll attempt that and come back here if anything doesn't work out. Thanks!
