### ISSUE TITLE
[Feature request] Images handling

### ISSUE THREAD

**Issue by tymik** [snipe/snipe-it#6691]
I was long thinking about how to categorize some of below, if as bugs or as FRs, here I come with putting all as FRs. Please note there are few smaller features, but all related with images and all have same root of this FR - using generic images instead of actual photos.

For what I have currently seen, cloning asset does not clone image related with it - i'm using generic images for easier visual recognition of items (e.g. network cables), therefore i have single image for more assets/accessories/consumables, just to represent the actual asset in generic way.

**Server (please complete the following information):**
 - Snipe-IT Version:  Version v4.6.6 - build 3926 (master) 

**Is your feature request related to a problem? Please describe.**
Images are not being cloned when assets are cloned.
Images are not inherited from models to assets.
Bulk update does not allow to set image.

**Describe the solution you'd like**
I'd like to:

- images be cloned on assets clone
- be able to set images on bulk update
- have possibility to inherit images from, e.g., models

And as I am aware some people might want to use actual photos for assets, not generic images, this should be optional to clone, inherit or bulk update the photo, depending on one's needs.

**Describe alternatives you've considered**
I considered that some might be using actual photos of assets therefore this should not be forced, but optional - might be possible to be set as do particular way by default.

**Additional context**
Haven't seen any open issues regarding images to mention here.
Didn't check for closed ones.
And I have checked changelogs for newer releases, none addressed my FR.

Also I have a question regarding images deduplication - if i add same image for more than 1 asset/accessory/consumable/etc, is it uploaded again and stored on server as additional image or is it deduplicated and the first uploaded image is actually used, without reuploading and unnecessarily storing another copy of same image?

**Comment by snipe** [comment]
> have possibility to inherit images from, e.g., models

This is currently the behavior. If an asset doesn't have an image but its model does, the asset's model is displayed. It's specifically designed for the generic image use-case you're describing here.

**Comment by tymik** [comment]
So it definitely did not work for me. I just checked history of assets and I was adding image to every single one of them. Also I can see that every asset reports different png name in history, so no deduplication.

![image](https://user-images.githubusercontent.com/1670525/52405600-ed54dc00-2acb-11e9-8335-13a642061eeb.png)
![image](https://user-images.githubusercontent.com/1670525/52405666-15443f80-2acc-11e9-9a02-0c85ace2b65d.png)
and I would not have added images one by one for every item if they were inherited.
If this part of my FR is actually implemented, then I'd switch it from FR to bug.

**Comment by tymik** [comment]
True, I must have had a glitch as I can see proper inheritance for newer assets.
But during history checking I've found that images are not deduplicated - those that I've added images manually report different png names in consecutive assets.

![image](https://user-images.githubusercontent.com/1670525/52405600-ed54dc00-2acb-11e9-8335-13a642061eeb.png)
![image](https://user-images.githubusercontent.com/1670525/52405666-15443f80-2acc-11e9-9a02-0c85ace2b65d.png)
