### ISSUE TITLE
Exception Error after upgrade + some time...

### ISSUE THREAD

**Issue by mr-gosh** [snipe/snipe-it#6694]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After patching the system to php 7.2.14 on ubuntu and upgrading snipe-it itself everything worked - a few days later (I don't know what happend in the meantime) the application shows the login screen - but after entering valid credentials an error is displayed

> count(): Parameter must be an array or an object that implements Countable
> 
> (1/1) ErrorException count(): > Parameter must be an array or an object that implements Countable
--

in the error log there appears an:

>     [2019-01-22 10:30:37] production.ERROR: ErrorException: count(): Parameter must be an array or an object that implements Countable in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:936

**To Reproduce**
1. Go to 'Login Screen'
2. Enter Credentials
3. whoooops...

**Expected behavior**
normally the user is logged in...

**Screenshots**
![snipeit](https://user-images.githubusercontent.com/3028703/52400456-76b1e180-2abf-11e9-87cc-a6e5e5549d7f.png)

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.7
 - OS: Ubuntu 16.04.5 LTS
 - Web Server: nginx 1.10.3
 - PHP Version 7.2.14

**Desktop (please complete the following information):**
 - OS: ubuntu linux
 - Browser firefox, vivaldi and chromium tested
 - Version multiple

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- this is an upgraded version - and it worked after the upgrade? 
- version is pulled via git
- searched for the bug - but only similar mentions demand to update to a newer version - what i did when before the bug first time appeared

[snipeit-log.txt](https://github.com/snipe/snipe-it/files/2840065/snipeit-log.txt)
[snipeit-output.txt](https://github.com/snipe/snipe-it/files/2840066/snipeit-output.txt)

**Comment by mr-gosh** [comment]
can anyone give me a hint what is going wrong here?

**Comment by snipe** [comment]
That error is typically associated with changes that PHP 7.2 brought in the way `count()` handles nulls, but i thought we already patched all that - and it seems odd that no one else has reported this with later versions, and that your upgrade worked just fine and then stopped. Do you have any external systems interfacing with your data, either directly or via the API?

**Comment by mr-gosh** [comment]
Hey Thanks for your time - we just use the API to Mattermost - nothing else...
Should I try to reinstall snipe-it? We have the data from nearly 30 co-corkers in there - so I try to not loose this information...

**Comment by mr-gosh** [comment]
can anyone give me a hint what is going wrong here?I downgraded to php7.1 and everything works as expected.
I think there are still some problems with php7.2 in some edge cases I encountered.

**Comment by mr-gosh** [comment]
Well - it is still.relevant as i can not upgrade to php 7.2 or newer I think
