### ISSUE TITLE
Update API Documentation

### ISSUE THREAD

**Issue by marcquark** [snipe/snipe-it#6696]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.7
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version 7.0

**Is your feature request related to a problem? Please describe.**
I'm writing an (up-to-date) Python module for the Snipe-IT API and have noticed that documentation and implementation don't always match.

**Describe the solution you'd like**
Updated API Reference

**Describe alternatives you've considered**
Sifting through the code, i'm not always 100% sure what i'm doing is right.

**Additional context**
One missing feature i found was the /licenses/:id/seats endpoint. It's not here: https://snipe-it.readme.io/reference#licenses
But it's implemented here: https://github.com/snipe/snipe-it/blob/master/routes/api.php#L413 and it works.
I'm not familiar enough with Laravel nor the Snipe-IT project to confidently identify all API features

**Comment by iainhallam** [comment]
If they don't match, is there a way that the documentation could be auto-generated from the API code?

**Comment by iainhallam** [comment]
Seats still not in the documentation.

**Comment by marcquark** [comment]
with https://github.com/snipe/snipe-it/pull/8058 merged, i'd like to reopen this one. i tried the "suggest edits" button on the api reference page but it didn't work. how/where is the API spec generated, and can it be influenced? if so, how? what's missing for this endpoint to make it into the API reference?

**Comment by marcquark** [comment]
summoning @snipe since Mr. Stalebot doesn't seem to keep the promise of reopening on reply :-D
i saw you posted in a couple of other tickets recently that the readme.io doc is acting funny. the /licenses/:id/seats endpoint is missing, could you please check why that is? if any patching is needed, i'd need to be pointed into the right direction, then i could try fixing it and submit a PR
