### ISSUE TITLE
Switching to a Git Install

### ISSUE THREAD

**Issue by bigworm** [snipe/snipe-it#6700]
Noticed today I was still running v4.6.3 and I followed the upgrade instructions on how to switch from manual install to git install for easier upgrading in the future...

I had a couple of errors after following the documentation that I thought you guys would be interested in.

[Thu Feb 07 19:13:35.019329 2019] [:error] [pid 29642] [client myip:54627] SoftException in Application.cpp:267: File "snipeit/public/index.php" is writeable by group
which I corrected by following google's suggestion to Change the file permissions from '0664' to '0644'

Then [Thu Feb 07 19:15:55.876183 2019] [:error] [pid 31604] [client myip:54673] SoftException in Application.cpp:657: Directory "/snipeit/public" is writeable by group
which I corrected by again using the google to change the permission to '0755'.

This was on a Centos box with git version 2.19.1

I followed the directions here https://snipe-it.readme.io/docs/switching-to-a-git-install

**Comment by snipe** [comment]
That looks like a... cPanel error? Thanks for the heads up - unfortunately permissions are something we have to rely on the user to handle, since they're all kinda different based on how the server is set up. We'll try to add a note to the docs tho.
