### ISSUE TITLE
LDAP Search OU finds users outside the OU

### ISSUE THREAD

**Issue by alexdobo** [snipe/snipe-it#6702]
#### Expected Behavior (or desired behavior if a feature request)

Search OU should only find the accounts in the selected OU, and not every account in the domain.

-----

#### Actual Behavior

It finds and imports the users that are in the selected OU, and then imports every user in the domain too.
In [this image](https://i.imgur.com/aEg6ejj.png) all of the users above the red line are in the IT OU. All of the users below the red line are in other OUs across the entire domain.
So it seems that it imports the correct users first, then adds every other user.
Here is a screenshot of LDAP Search OU box: https://i.imgur.com/qYz7bAm.png
Here is a screenshot of the LDAP settings page: https://i.imgur.com/PKEbqRe.png

-----

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Fresh**
- Version of Snipe-IT you're running **4.6.8**
- Version of PHP you're running  **7.2.10**
- Version of MySQL/MariaDB you're running  **MySQL 5.7.25**
- What OS and web server you're running Snipe-IT on  **Ubuntu 18.04.1 LTS, Apache2**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)  **Install.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error  **No error**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **Synchronize on /users/ldap**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. **Can't reproduce as it need to be running on my network**
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. **Pretty much a fresh install, I haven't received any errors**
- Indicate whether or not you've manually edited any data directly in the database **No**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by jlevy-wishfarms** [comment]
Oops, think you accidentally posted the same photo but one is unredacted

**Comment by alexdobo** [comment]
@jlevy-wishfarms Thanks for the heads up

**Comment by alexdobo** [comment]
I've done a network capture, and it looks like Snipe-IT does a search request for the entire domain before doing a search for just the requested OU

**Comment by mikem011** [comment]
Yes, this issue is still relevant.  I am experiencing it as well.
