### ISSUE TITLE
API call to /hardware/byserial not working

### ISSUE THREAD

**Issue by JuustoMestari** [snipe/snipe-it#6704]
**Describe the bug**
API call to /hardware/bytag/:tag works but call to /hardware/byserial/:serial ( https://snipe-it.readme.io/reference#hardware-by-serial ) does not work.
The _byserial_ call returns 403 (sad panda) html .
I am using a user token with permissions : Assets : view/edit/create
If I use a super administrator token then the api call to _byserial_ works.
It looks like it is related to permissions. Does _byserial_ require a special permission different than _bytag_?

**Expected behavior**
a call to _byserial_ should work the same way than _bytag_ ?

**Server (please complete the following information):**
 - Snipe-IT Version : 4.6.8 build 3959
 - OS: docker image (4.6.8)

**Additional context**
- Is this a fresh install or an upgrade? -> fresh
- What OS and web server you're running Snipe-IT on -> kubernetes v 1.13.3
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) -> docker
- Indicate whether or not you've manually edited any data directly in the database -> no

Thanks for your work!

**Comment by snipe** [comment]
API calls should never return sad panda HTML. Are you sure you have the correct headers? Can you show me the output of a Postman request with your headers intact?

**Comment by JuustoMestari** [comment]
Basically, I try bytag and it works fine then I just changed the url by replacing bytag with byserial (I didn't change any headers values) and I get sad panda.
Is this what you need?
Server →nginx/1.15.8
Date →Wed, 13 Feb 2019 12:17:23 GMT
Content-Type →text/html; charset=UTF-8
Transfer-Encoding →chunked
Connection →keep-alive
Vary →Accept-Encoding
Vary →Authorization
Cache-Control →no-cache, private
X-Content-Type-Options →nosniff
Referrer-Policy →same-origin
X-XSS-Protection →1;mode=block
X-Frame-Options →SAMEORIGIN
Set-Cookie →snipeit_session=9PeBIDSgmoJbOextFwVsY8NttGSzVwnUSTLZ5DI2; expires=Thu, 21-Feb-2019 20:17:23 GMT; Max-Age=720000; path=/; httponly
Strict-Transport-Security →max-age=15724800; includeSubDomains
Content-Encoding →gzip

![image](https://user-images.githubusercontent.com/4496300/52711480-956e1780-2f9a-11e9-8c81-58a9fc4b7826.png)

Hope this helps.

**Comment by snipe** [comment]
Try applying the patch I just pushed out to master.

**Comment by snipe** [comment]
(And let me know if that worked)

**Comment by JuustoMestari** [comment]
Yes, it works.
Thanks for the quick fix !

**Comment by snipe** [comment]
Awesome!
