### ISSUE TITLE
Change font color

### ISSUE THREAD

**Issue by KARTHIKEYANINDIRAN** [snipe/snipe-it#6706]
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: RHEL 7
 - Web Server: Apache
 - PHP Version 5

**Is your feature request related to a problem? Please describe.**
Where to change font color in login page fonts like "Please login" content. 

**Describe the solution you'd like**
Nil

**Describe alternatives you've considered**
Nil

**Additional context**
I have added to custom field and the same didn't shown in add new license or asset page. Please help on this.

**Comment by snipe** [comment]
> Where to change font color in login page fonts like "Please login" content.

You'll need to use the Custom CSS setting in Admin Settings > Branding and add CSS to change the color

> I have added to custom field and the same didn't shown in add new license or asset page. Please help on this.

Please keep separate issues separate. To add custom fields to assets, you have to add them to a fieldset and add the fieldset to models. We have a tutorial video here: https://snipe-it.readme.io/docs/custom-fields
