### ISSUE TITLE
[Feature request] Autoupdate when container starts

### ISSUE THREAD

**Issue by samatkiss** [snipe/snipe-it#6707]
Is it possible to add the database migration and other commands needed by update into the base image?
So when i pull the latest image, it upgrades automatically the database if there was an existing installation.

**Comment by lubo** [comment]
Hi @samatkiss, I believe my PR #6680 addresses this issue. Unfortunately, the code owner - @uberbrady, is unresponsive. :disappointed:

**Comment by snipe** [comment]
@lubo We apoligize for the delay. @uberbrady has a full-time job of his own and volunteers his time on this project, so your patience is appreciated.

**Comment by snipe** [comment]
This PR has been merged.
