### ISSUE TITLE
Missing tags on Docker Hub

### ISSUE THREAD

**Issue by lubo** [snipe/snipe-it#6708]
None of the today's releases is present on Docker Hub.

**Comment by snipe** [comment]
<img width="1122" alt="screen shot 2019-02-13 at 11 33 51 am" src="https://user-images.githubusercontent.com/197404/52738332-48cb1200-2f83-11e9-9b42-1fef67ef4827.png">


<img width="1120" alt="screen shot 2019-02-13 at 11 33 07 am" src="https://user-images.githubusercontent.com/197404/52738286-2df89d80-2f83-11e9-8c31-92c1c4608442.png">

Not really sure what's going on there. It shows my GH account connected.

**Comment by lubo** [comment]
But it shows no actual configuration. Have you tried reconnecting the repository? Perhaps something expired…

**Comment by snipe** [comment]
@lubo Yes, I'm aware of that - but that's the UI it's giving me. No option to configure anything. I've reconnected it and it's working again, but I have to set up the tag regex again.

**Comment by lubo** [comment]
I just wanna say this is a blocking issue for me. It prevents me from upgrading.

**Comment by snipe** [comment]
It’s not respecting the tag regex, so i’m nit sure what to tell you. I literally copy and pasted their example and it’s still showing up empty and in-triggerable.

**Comment by lubo** [comment]
Have you tried force-pushing an existing tag in Git?

**Comment by snipe** [comment]
Yes.

I used the trigger URL to force a build of 4.9.10, but still can't get the beta to build.

**Comment by lubo** [comment]
Upgraded to 4.9.10, thank you for that.

But I don't consider the issue resolved since the beta releases are still not there. What's the used regex?

**Comment by snipe** [comment]
Except they are: https://cloud.docker.com/repository/docker/snipe/snipe-it/tags

**Comment by snipe** [comment]
A few versions were skipped, but I'm fine with that. We released again right after that anyway, and those tags are picked up now.

**Comment by lubo** [comment]
My bad. Yeah, it's fine if those ones are missing. Thanks, consider resolved.
