### ISSUE TITLE
Duplicate user if changed the username on AD account?

### ISSUE THREAD

**Issue by dhkivan** [snipe/snipe-it#6714]
We use LDAP sync to import users from AD, if changed the username in AD which this account is already imported to database, then it will be created a new user in database on next LDAP sync?

If yes, can avoid it, for example check the employeeID or SID of user account or else?

**Comment by snipe** [comment]
Throughout the system, we use username as the identifying key, so i’m not sure there’s a good workaround here. To have it use employee ID (which many organizations don’t use) would break things in all kinds of new and awful ways.

**Comment by dhkivan** [comment]
Agreed to use username, just think can add an additional checking at LDAP sync process, e.g use employeeid or sid to double verify the account whether is exisit or not.

And what's the purpose of employee no. in the system?

**Comment by snipe** [comment]
> And what's the purpose of employee no. in the system?

It has no purpose other than being an additional piece of information some companies choose to track with the users/assets. Not everyone uses employee ID, so we can't base business logic around it.
