### ISSUE TITLE
Debug mode won't enable

### ISSUE THREAD

**Issue by EWebbs** [snipe/snipe-it#6715]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Debug mode won't enable.

I've update the .env file to APP_DEBUG=true, and cleared the cache and restarted Apache (as per documentation)

**Expected behavior**
Previously editing the .env file as described above worked for turning debug mode on and off.

**Server:**
 - Snipe-IT Version: v4.6.7
 - OS: Ubuntu 18.04.1 LTS
 - Web Server: Apache/2.4.29 (Ubuntu)
 - PHP Version: 7.2.15

**Desktop:**
 - OS: Windows 7
 - Browser: Chrome
 - Version: 72.0.3626.109

**Additional context**
- Fresh install 
- Running Snipe-IT on Ubuntu and Apache2
- Installed via Git
- Added data to the database via the app, the database has not been directly edited.

**Comment by EWebbs** [comment]
**Update:** Making any changes to the .env file appears to have no effect whatsoever. I have run the following commands:

*composer dump-autoload*
*php artisan clear-compiled*
*php artisan config:clear*
*php artisan view:clear*
*php artisan cache:clear*
*php artisan route:clear*

and restarted Apache. 

Is there anything else I can try?

**Comment by snipe** [comment]
Try changing the environment to `local` and clearing the config cache

**Comment by EWebbs** [comment]
I've just tried that and unfortunately it didn't work. 

I'm trying to look in the app logs in `storage/logs` for clues but the directory is empty. I've double checked the permissions and the server has read write access on all the snipe-it directories, so I'm not sure what's gone wrong.

**Comment by snipe** [comment]
@EWebbs unfortunately, I don't know either :(

**Comment by EWebbs** [comment]
@snipe what would you advise as a next step? Should I make a back up of the database, remove snipe-it completely and re-install?

**Comment by snipe** [comment]
@EWebbs I honestly have no idea. There isn't a reason I can give you why it wouldn't enable.

**Comment by EWebbs** [comment]
Hi @snipe FYI I have managed to enable debug mode by editing the .env file in /var/www/'project root name' rather than the .env file in the project root itself... Is there a link or process that is broken? or is this simply my bad?

**Comment by snipe** [comment]
I’m not sure what you mean. There should only be one .env file. What’s the difference in your case between project root name and project root?

**Comment by EWebbs** [comment]
@snipe I think perhaps we can put this down to my misunderstanding. Thanks for your help.
