### ISSUE TITLE
Column not found: 1054 Unknown column 'category_id' in 'field list' | Can't run artisan migrate

### ISSUE THREAD

**Issue by cjsssinpe** [snipe/snipe-it#6719]
#### Please confirm you have done the following before posting your bug report:

- [YES ] I have enabled debug mode 
- [YES] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Can't add licenses after 'upgrade' (Moved to new VM, looks like artisan migrate isn't working) - debug info below.

**Error Messages**
Debug Message
(3/3) QueryExceptionSQLSTATE[42S22]: Column not found: 1054 Unknown column 'category_id' in 'field list' (SQL: insert into `licenses` (`company_id`, `depreciation_id`, `expiration_date`, `license_email`, `license_name`, `maintained`, `manufacturer_id`, `name`, `notes`, `order_number`, `purchase_cost`, `purchase_date`, `purchase_order`, `reassignable`, `seats`, `serial`, `supplier_id`, `category_id`, `termination_date`, `user_id`, `updated_at`, `created_at`) values (, , , , , 0, 12, asdsa, , , , , , 1, 1, , , 19, , 15, 2019-02-15 12:55:19, 2019-02-15 12:55:19))
--
in Connection.php line 647
at Connection->runQueryCallback('insert into `licenses` (`company_id`, `depreciation_id`, `expiration_date`, `license_email`, `license_name`, `maintained`, `manufacturer_id`, `name`, `notes`, `order_number`, `purchase_cost`, `purchase_date`, `purchase_order`, `reassignable`, `seats`, `serial`, `supplier_id`, `category_id`, `termination_date`, `user_id`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', array(null, null, null, '', '',false, '12', 'asdsa', '', '', null, null, '', true, '1', '', null, '19', null, 15, '2019-02-15 12:55:19', '2019-02-15 12:55:19'), object(Closure))in Connection.php line 607
at Connection->run('insert into `licenses` (`company_id`, `depreciation_id`, `expiration_date`, `license_email`, `license_name`, `maintained`, `manufacturer_id`, `name`, `notes`, `order_number`, `purchase_cost`, `purchase_date`, `purchase_order`, `reassignable`, `seats`, `serial`, `supplier_id`, `category_id`, `termination_date`, `user_id`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', array(null, null, null, '', '', false, '12', 'asdsa', '', '', null, null, '', true, '1', '', null, '19', null, 15, '2019-02-15 12:55:19', '2019-02-15 12:55:19'), object(Closure))in Connection.php line 450
at Connection->statement('insert into `licenses` (`company_id`, `depreciation_id`, `expiration_date`, `license_email`, `license_name`, `maintained`, `manufacturer_id`, `name`, `notes`, `order_number`, `purchase_cost`, `purchase_date`, `purchase_order`, `reassignable`, `seats`, `serial`, `supplier_id`, `category_id`, `termination_date`, `user_id`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', array(null, null, null, '', '',false, '12', 'asdsa', '', '', null, null, '', true, '1', '', null, '19', null, 15, '2019-02-15 12:55:19', '2019-02-15 12:55:19'))in Connection.php line 404
at Connection->insert('insert into `licenses` (`company_id`, `depreciation_id`, `expiration_date`, `license_email`, `license_name`, `maintained`, `manufacturer_id`, `name`, `notes`, `order_number`, `purchase_cost`, `purchase_date`, `purchase_order`, `reassignable`, `seats`, `serial`, `supplier_id`, `category_id`, `termination_date`, `user_id`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', array(null, null, null, '', '',false, '12', 'asdsa', '', '', null, null, '', true, '1', '', null, '19', null, 15, '2019-02-15 12:55:19', '2019-02-15 12:55:19'))in Processor.php line 32
at Processor->processInsertGetId(object(Builder), 'insert into `licenses` (`company_id`, `depreciation_id`, `expiration_date`, `license_email`, `license_name`, `maintained`, `manufacturer_id`, `name`, `notes`, `order_number`, `purchase_cost`, `purchase_date`, `purchase_order`, `reassignable`, `seats`, `serial`, `supplier_id`, `category_id`, `termination_date`, `user_id`, `updated_at`, `created_at`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', array(null,null, null, '', '', false, '12', 'asdsa', '', '', null, null, '', true, '1', '', null, '19', null, 15, '2019-02-15 12:55:19', '2019-02-15 12:55:19'), 'id')in Builder.php line 2133
at Builder->insertGetId(array(null, null, null, '', '', false, '12', 'asdsa', '', '', null, null, '', true, '1', '', null, '19', null, 15, '2019-02-15 12:55:19', '2019-02-15 12:55:19'), 'id')in Builder.php line 1251
at Builder->__call('insertGetId', array(array('company_id' => null, 'depreciation_id' => null, 'expiration_date' => null, 'license_email' => '', 'license_name' => '', 'maintained' => false, 'manufacturer_id' => '12', 'name' => 'asdsa', 'notes' => '', 'order_number' => '', 'purchase_cost' => null, 'purchase_date' => null, 'purchase_order' => '', 'reassignable' => true, 'seats' => '1', 'serial' => '', 'supplier_id' => null, 'category_id' => '19', 'termination_date' => null, 'user_id' => 15, 'updated_at' => '2019-02-15 12:55:19', 'created_at' => '2019-02-15 12:55:19'), 'id'))in Model.php line 688
at Model->insertAndSetId(object(Builder), array('company_id' => null, 'depreciation_id' => null, 'expiration_date' => null, 'license_email' => '', 'license_name' => '', 'maintained' => false, 'manufacturer_id' => '12', 'name' => 'asdsa', 'notes' => '', 'order_number' => '', 'purchase_cost' => null, 'purchase_date' => null, 'purchase_order' => '', 'reassignable' => true, 'seats' => '1', 'serial' => '', 'supplier_id' => null, 'category_id' => '19', 'termination_date' => null, 'user_id' => 15, 'updated_at' => '2019-02-15 12:55:19', 'created_at' => '2019-02-15 12:55:19'))in Model.php line 653
at Model->performInsert(object(Builder))in Model.php line 522
at Model->save()in LicensesController.php line 115
at LicensesController->store(object(Request))
at call_user_func_array(array(object(LicensesController), 'store'), array(object(Request)))in Controller.php line 55
at Controller->callAction('store', array(object(Request)))in ControllerDispatcher.php line 44
at ControllerDispatcher->dispatch(object(Route), object(LicensesController), 'store')in Route.php line 203
at Route->runController()in Route.php line 160
at Route->run()in Router.php line 572
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Authenticate.php line 43
at Authenticate->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php line 49
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php line 49
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php line 42
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Router.php line 574
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 533
at Router->dispatchToRoute(object(Request))in Router.php line 511
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php line 51
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php line 25
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php line 27
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

Errors when running artisan migrate:

[snipeituser@SnipeIT snipe-it]$ php artisan migrate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

In StreamHandler.php line 107:

  The stream or file "/var/www/html/snipe-it/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied

[snipeituser@SnipeIT snipe-it]$ sudo php artisan migrate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes

In Connection.php line 647:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_custom_fields' already exists (SQL: create table `models_custom_fields` (`id` int unsigned not null auto_increment prima
  ry key, `asset_model_id` int not null, `custom_field_id` int not null, `default_value` text null) default character set utf8mb4 collate utf8mb4_unicode_ci engine = InnoDB)

In PDOStatement.php line 107:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_custom_fields' already exists

In PDOStatement.php line 105:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_custom_fields' already exists

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
see above
- If a stacktrace is provided in the error, include that too.
not sure on this one
- Any errors that appear in your browser's error console.
No error in console
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. 
no
- Include any additional information you can find in `storage/logs` and your webserver's logs.
haven't included laravel.log - its pretty big!

**Additional context**
- Is this a fresh install or an upgrade? - 
Fresh install, with a migrate from old version.
- What OS and web server you're running Snipe-IT on
CentOS Linux release 7.6.1810 (Core) (Azure VM)

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Git Clone

- Include what you've done so far in the installation, and if you got any error messages along the way.
Assumed install / upgrade completed fine, except now unable to add licenses

- Indicate whether or not you've manually edited any data directly in the database
No - haven't made it worse yet

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Artisan migrate is working, but your log file can’t be written to (according to your stack trace). Fix permissions on your log file and re-run migrations. It’s possible that the log permission error has bombed out your migrations and you might have created a bigger problem. You should never have to run migrations (or any artisan command) as root/sudo.

**Comment by cjsssinpe** [comment]
Thanks for the quick update! I updated permissions on the log file (to snipeituser, it was apache):

[snipeituser@SnipeIT storage]$ ls -la
total 32
drwxrwxrwx  8 root        root         214 Jan 30 02:42 .
drwxr-xr-x 16 root        root        4096 Feb 15 01:54 ..
drwxrwxrwx  3 root        root          39 Jan 29 22:39 app
drwxrwxrwx  2 root        root        8192 Feb 15 02:37 debugbar
drwxrwxrwx  5 root        root          66 Jan 29 22:39 framework
drwxr-xr-x  2 apache      apache         6 Jan 30 02:18 laravel-backups
drwxrwxrwx  2 snipeituser snipeituser   43 Jan 30 02:10 logs
-rw-rw-r--  1 snipeituser snipeituser 3292 Jan 30 02:36 oauth-private.key
-rw-r--r--  1 apache      apache      3292 Jan 30 02:10 oauth-private.key.bak
-rw-rw-r--  1 snipeituser snipeituser  812 Jan 30 02:36 oauth-public.key
-rw-r--r--  1 apache      apache       812 Jan 30 02:10 oauth-public.key.bak
drwxrwxrwx  9 root        root         115 Jan 29 22:39 private_uploads
[snipeituser@SnipeIT storage]$ cd logs/
[snipeituser@SnipeIT logs]$ ls -la
total 2792
drwxrwxrwx 2 snipeituser snipeituser      43 Jan 30 02:10 .
drwxrwxrwx 8 root        root            214 Jan 30 02:42 ..
-rwxrwxrwx 1 root        root             14 Jan 29 22:39 .gitignore
-rw-r--r-- 1 snipeituser snipeituser 2853642 Feb 15 03:53 laravel.log


Still getting an error when running migrate:


[snipeituser@SnipeIT snipe-it]$ php artisan migrate
**************************************
*     Application In Production!     *
**************************************

 Do you really wish to run this command? (yes/no) [no]:
 > yes


In Connection.php line 647:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_custom_fields' already exists (SQL: create table `models_custom_fields` (`id` int unsigned not null auto_increment prima
  ry key, `asset_model_id` int not null, `custom_field_id` int not null, `default_value` text null) default character set utf8mb4 collate utf8mb4_unicode_ci engine = InnoDB)


In PDOStatement.php line 107:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_custom_fields' already exists


In PDOStatement.php line 105:

  SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'models_custom_fields' already exists

**Comment by snipe** [comment]
Well, yeah, because migrations already got hoarked since the log file couldn't be written to. Can you dump your migrations table and show me what's in there?

**Comment by cjsssinpe** [comment]
Hi snipe,

I've dumped the migrations table (mysqldump -u root -p snipeit migrations > migrations.sql) and attached below.

[migrations.zip](https://github.com/snipe/snipe-it/files/2873518/migrations.zip)

Thank you for the help!

**Comment by cjsssinpe** [comment]
> Well, yeah, because migrations already got hoarked since the log file couldn't be written to. Can you dump your migrations table and show me what's in there?

Hi Snipe,

Any luck checking my migration table dump?

Cheers!

**Comment by cjsssinpe** [comment]
Managed to fix this by deleting any tables that were showing issues. Not recommended, but worked for me.
