### ISSUE TITLE
[Question] Are the files static after installation?

### ISSUE THREAD

**Issue by wilamu** [snipe/snipe-it#6721]
Hi, 

Hope this question makes sense, after the install and everything is up and running is it only the MySQL database that changes. Are all the files in the /var/www/snipeit directory static and no changes are made to them? 

Just implemented Snipe-IT this week and absolutely love it.

**Comment by EarlRamirez** [comment]
@wilamu I would say some most files are static the reason why I say this is because when there is a bug fix or a feature enhancement to Snipe-IT they will get updated when you upgrade Snipe-IT.

Hope this answers your question

**Comment by wilamu** [comment]
Hi @EarlRamirez yea that's perfect. I understand an upgrade will cause files to change but in the day to day they are fine? 

Many thanks for the reply.

**Comment by snipe** [comment]
Hi @wilamu - the only things that would potentially change would be any files you’ve uploaded.
