### ISSUE TITLE
Assets that are checked out to another asset don't change location

### ISSUE THREAD

**Issue by llecerf** [snipe/snipe-it#6724]
- [ x ] I have enabled debug mode 
- [ x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When changing the location of an asset, the assets that are checkout out to it don't have their locations changed

**To Reproduce**
1. Go to an asset
2. Click on Actions > Checkout
3. Checkout the asset to a location
4. See that the assets that are checked out to the first asset are still in the same location as before

**Expected behavior**
Assets that are checked out to the asset that moved should move as well

**Screenshots**

**Server :**
 - Snipe-IT Version v4.6.7
 - OS: [Windows 7]
 - Web Server: []
 - PHP Version 

**Desktop (please complete the following information):**
 - OS: [Windows 7]
 - Browser [Firefox]
 - Version [63.0.3]

**Comment by JonathonReinhart** [comment]
Yup.

**Comment by BW44b** [comment]
Is anyone else still having this problem?

**Comment by Scintillator** [comment]
This issue is still relevant, intuitive behavior would be the location change of a parent asset copying down to the child assets.
