### ISSUE TITLE
The PR #6716 changed column type of auto_increment_prefix from string to boolean

### ISSUE THREAD

**Issue by the-glu** [snipe/snipe-it#6725]
It seem that https://github.com/snipe/snipe-it/pull/6716 changed the type of the auto_increment_prefix to boolean, where it was a string before (Created here: https://github.com/snipe/snipe-it/blob/14eb6b387b827f18c574b34eb1af2525640082bb/database/migrations/2014_11_20_224421_add_prefix_to_settings.php and never changed again)

We where using before a string for our asset tags and now we can only use -127 to 127 as number (since boolean seems to be stored as tinyint in mysql) - witch is not really useful as a prefix.

**To Reproduce**
* Install the current master
* Goes to Admin / Asset tags
* Change Prefix to any string. Value is set back to zero
* Change Prefix to any number. Value is cap between -127 and 127.

**Expected behavior**
* Change Prefix to any string should keep the string specified.
* Change Prefix to any number should keep the number specified.

**Server:**
 - Snipe-IT Version: git / master
 - OS: Debian

**Comment by snipe** [comment]
Wasn’t that fixed in 4.6.11?

**Comment by the-glu** [comment]
It seems it was broken in 4.6.11: https://github.com/snipe/snipe-it/compare/v4.6.10...v4.6.11#diff-2683bd23ce061d2ad96727f8c8c621e3R17

**Comment by snipe** [comment]
D'oh - you're right. Pushed out a fix to master.
