### ISSUE TITLE
Error when trying to edit assets from the "Assets" tab in an asset

### ISSUE THREAD

**Issue by llecerf** [snipe/snipe-it#6726]
* [ x ] I have enabled debug mode
* [ x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When trying to edit/delete assets from the "Assets" tab in an asset you get an error message telling you "no assets selected"

**To Reproduce**

1. Go to an asset
2. Click on "Assets" between "Components" and "Maintenances"
3. Tick the boxes next to one or multiple assets and then select "Edit", "Delete" or "Generate Labels" above and click Go
4. Get sent back to the "Details" tab with the error message "No assets selected"

**Expected behavior**
You should be able to Edit, Delete or Generate Labels

**Server :**

* Snipe-IT Version v4.6.7
* OS: [Windows 7]
* Web Server: []
* PHP Version

**Desktop (please complete the following information):**

* OS: [Windows 7]
* Browser [Firefox]
* Version [63.0.3]

**Comment by snipe** [comment]
@inietov can you confirm if this is happening on develop?

**Comment by inietov** [comment]
@snipe It's happening.

**Comment by snipe** [comment]
@inietov do you want to take a stab at a fix? Not today tho - it’s the weekend :)

**Comment by inietov** [comment]
@snipe But of course!! Always happy to help
