### ISSUE TITLE
asset model request if QTY >1 does not request QTY

### ISSUE THREAD

**Issue by apbutle** [snipe/snipe-it#6727]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
If I have a large inventory of any given asset model and a quantity greater than 1 of said asset model is requested by a user, the qty of said asset requested only shows "1".  Also "available" Inventory does not reflect deployed assets and update the qty of "readily available for checkout" assets.

**To Reproduce**
1. Go to 'requestable, asset models, request a qty >1 of a model with enough "Available"'
2. Click on 'Assets-Requested'
3. Look at the listed requests
4. no error, but also no qty requested, if double checked in users' requested list (top right corner) qty requested is always 1

**Expected behavior**
If QTY is >1 it is expected that that QTY is reflected in a request. So that the admin can check out said QTY to user.  Also Users should only be able to see deployable but undeployed inventory as available. (this could mislead someone and result in a request more than what is available.)

**Server (please complete the following information):**

Snipe-IT version | v4.6.8 build 3959 (g194d0733d)
-- | --
Software License | AGPL3
PHP Version | 7.2.15-0ubuntu0.18.04.1
Laravel Version | 5.4.3

**Desktop (please complete the following information):**
 - OS: [Windows10]
 - Browser [Chrome]
 - Version [Version 71.0.3578.98 (Official Build) (64-bit)]

**Comment by apbutle** [comment]
Yes.  Still relevant.  Requests for multiple qty of a given model of
something is a function that seems halfway there.  A qty request can be out
in by a user. The qty just doesn't show up in the request to the "it
manager"

**Comment by Coolfeather2** [comment]
I have same issue

**Comment by Coolfeather2** [comment]
The QTY does appear in the email notification, but is not present in the requested asset section of Snipe-IT

Further on this, the "Request Asset Model" feature seem incomplete
There seems to be no obvious way to finalize or close the model requests once the asset has been purchased and set ready to deploy?

**Comment by Coolfeather2** [comment]
Still relevant
