### ISSUE TITLE
How to get custom fields data in mail alert

### ISSUE THREAD

**Issue by KARTHIKEYANINDIRAN** [snipe/snipe-it#6728]
**Server (please complete the following information):**
 - Snipe-IT Version **4.6.8**
 - OS: [e.g. Ubuntu, CentOS] **RHEL 7**
 - Web Server: [e.g. Apache, IIS] **Apache**
 - PHP Version **5**

**Is your feature request related to a problem? Please describe.**
How to get custom fields data in mail alert. Please help me its urgent

**Describe the solution you'd like**
Nil

**Describe alternatives you've considered**
Better to provide option for custom fields added to mail alert.

**Additional context**
nil

**Comment by snipe** [comment]
This is already in the upcoming version 5. (Additionally, in the future, you should be more specific regarding which notifications you’re talking about.)
