### ISSUE TITLE
Ability to set fields to required/optional

### ISSUE THREAD

**Issue by thomaschinhm** [snipe/snipe-it#6729]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.11 build 3980
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version: 7.0.33

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Able to set default fieldset as required/optional

**Comment by snipe** [comment]
@thomaschinhm what fields? Please be more specific with your feature requests.
