### ISSUE TITLE
Ability to remove default fieldset

### ISSUE THREAD

**Issue by thomaschinhm** [snipe/snipe-it#6730]
**Server (please complete the following information):**
 - Snipe-IT Version 	v4.6.11 build 3980
 - OS: ubuntu0.16.04.1
 - Web Server: Apache
 - PHP Version 7.0.33

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Able to remove default fieldset in asset and etc for fields that are not in use

**Comment by snipe** [comment]
Fieldsets are assigned at the model level, and cannot be removed from particular assets.
