### ISSUE TITLE
User showing as lastname, firstname instead of firstname lastname in Checkout to

### ISSUE THREAD

**Issue by thomaschinhm** [snipe/snipe-it#6731]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [Y ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
v4.6.11 build 3980

**To Reproduce**
Create a new asset. Set status ready to deploy and select a user to Checkout To

**Expected behavior**
Name listed are showing as lastname, firstname instead of firstname lastname

**Screenshots**
![image](https://user-images.githubusercontent.com/30923044/52895960-635bf000-31fc-11e9-9708-2e4b4c415bce.png)

**Server (please complete the following information):**
 - Snipe-IT Version 	v4.6.11 build 3980
 - OS: ubuntu0.16.04.1
 - Web Server: Apache
 - PHP Version 7.0.33

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 72.0.3626.109

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
This is intended behavior.

**Comment by samotelf** [comment]
Hello @snipe, we know but in some countries we use first name, last name.
Instead of Smith, John. (this bugged me but never really took the time to open a ticket)
Even in our address books we use first name, last name. I understand that its more of a commodity as long as we type the user name it shows up correctly. It's just the visual cue that seems off.
Do you think you can add that functionality?
Thank you.

**Comment by rsppeter** [comment]
I sure would like an options to select Firstname, lastname

**Comment by samotelf** [comment]
Indeed.
+1

**Comment by josuegodoy** [comment]
Indeed.
+2

**Comment by ReachyBayern** [comment]
Need this feature for companies in Germany too, and for sure for the company I am working for! Please provide a solution. Thanks in advance

**Comment by samotelf** [comment]
Yes, please again…
Please implement this.

**Comment by snipe** [comment]
This isn't really own the short term roadmap. If someone wanted to open a PR for it to fix it, I'd probably consider it, but in general, I am loathe to add new DB settings, since it's a whole new branch of testing that we have to do on an already sprawling system.

**Comment by SchachtnerTh** [comment]
It would be great to have the option to sort by lastname. So maybe it's not needed to have the database redesigned to show the username in the form "lastname, firstname" bit if there was an option to show the columns lastname and firstname in the assets list as well as in the reports. For me, this would be enough then and I think that would need much less development efforts. (But I cannot judge if this is true for everyone)
