### ISSUE TITLE
H01797: client denied by server configuration: /var/www/html/snipeit/public/.env

### ISSUE THREAD

**Issue by ejw179** [snipe/snipe-it#6737]
#### Expected Behavior (or desired behavior if a feature request)

When I click Next: Create Database Tables, it goes to next step.
(I can click "Step 2" Block on bread crumbs and it continue)
-----

#### Actual Behavior

![image](https://user-images.githubusercontent.com/37702673/52922404-0bea7c80-32ef-11e9-8530-a2d7dd6e8133.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
  Executed:
composer dump-autoload
composer clear-compiled
php artisan config:clear
php artisan view:clear
php artisan cache:clear
php artisan route:clear
-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running - Just cloned repo
- Version of PHP you're running - Php7.3.1
- Version of MySQL/MariaDB you're running - Ver 15.1 Distrib 5.5.60-MariaDB
- What OS and web server you're running Snipe-IT on - Centos7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - none displayed
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - http://snipeit.lab.local/setup
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

<VirtualHost *:80>
    ServerAdmin admin@lab.local
    DocumentRoot "/var/www/html/snipe-it/public"
    ServerName snipeit.lab.local
    ServerAlias www.snipeit.lab.local
    <Directory "/var/www/html/snipe-it/public">
        Options Indexes FollowSymLinks MultiViews 
        AllowOverride All
        Require all granted
    </Directory>
    ErrorLog "/var/log/httpd/snipeit.lab.local-error_log"
    CustomLog "/var/log/httpd/snipeit.lab.local-access_log" combined
</VirtualHost>

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by EarlRamirez** [comment]
@ejw179 can you confirm your directory location, the logs show **snipeit** and your virtual host shows **snipe-it**

**Comment by EarlRamirez** [comment]
If you want to get straight into using Snipe-IT without the hassle of installation, you can take a log at https://github.com/EarlRamirez/snipeit_iso or you can use the reasonable priced hosted solution.

**Comment by ejw179** [comment]
Whoops! I copied from scratch notepad. here is my live copy- 
![image](https://user-images.githubusercontent.com/37702673/52922707-24f42d00-32f1-11e9-8c06-6002119682c9.png)

**Comment by EarlRamirez** [comment]
Out of curiously can you try the following command after you were able to reproduce the error. **ausearch -m avc -ts today**

**Comment by snipe** [comment]
**Also, your .env file shouldn't be in your public directory.** That's enormously dangerous, as it would expose your database credentials, etc to the outside world. It should be one level up in `/var/www/html/snipeit`, NOT `/var/www/html/snipeit/public`

**Comment by glyslxq** [comment]
Have you solved it? The new version has this problem again
