### ISSUE TITLE
Create New Api (Login and Register)

### ISSUE THREAD

**Issue by Blu3W0LF** [snipe/snipe-it#6738]
Hey Guys, 

I am trying to create new REST-API( login and register). 
But  I could not be successful and I couldn't find any resources in Snipe-IT Documentation... 
I might Login and register REST-API will be up this project. 
Can you help me with this?

Thanks.

**Comment by snipe** [comment]
Login doesn't work as you'd expect in the API - it requires a bearer token, per the API docs. 

We do not support registering at all (GUI or API), as that's not really the nature of this application. Users must be created by someone else.
