### ISSUE TITLE
Customization Form

### ISSUE THREAD

**Issue by luciankiddo** [snipe/snipe-it#6745]
**Server (please complete the following information):**
 - Snipe-IT 4.6.12
 - OS: Windows 
 - Web Server: Apache
 - PHP Version 7.x.x up

Add a Customization Form for requisition for specific asset, this include some approval of certain position.

**Comment by snipe** [comment]
I don't understand what you're asking for here - please clarify.

**Comment by luciankiddo** [comment]
It is possible to have an approval first of different user(s) (ex. IT Manager, Manager, Supervisor and HR Manager) before it will checkout.

**Comment by snipe** [comment]
That isn't currently possible
