### ISSUE TITLE
AH00558: apache2 error with docker image

### ISSUE THREAD

**Issue by charan432** [snipe/snipe-it#6748]
**Describe the bug**
I am creating a docker image with php & mysql containers using docker-compose. The containers started and running successfully in my computer. I can also access the application in browser using my IP address http://192.168.99.100/index.php. I created images for php and mysql and pushed to docker hub, but when I downloaded those images in a different computer and tried to run the images, I am getting an error as like below:

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message

[mpm_prefork:notice] [pid 7] AH00163: Apache/2.4.25 (Debian) PHP/5.6.40 configured -- resuming normal operations
[core:notice] [pid 7] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'

**To Reproduce**
1. Go to docker hub
2. Pull the docker image "sricharant/phpmysql".
3. run the images

**Expected behavior**
Launch Docker image with no issues. Run the application in browser.

**Server (please complete the following information):**
 - Docker Toolbox 
 - OS: Windows

**Error Messages**
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message

[mpm_prefork:notice] [pid 7] AH00163: Apache/2.4.25 (Debian) PHP/5.6.40 configured -- resuming normal operations
[core:notice] [pid 7] AH00094: Command line: '/usr/sbin/apache2 -D FOREGROUND'

Please help me to solve this issue.

**Comment by NateDreier** [comment]
I am having the same issue. Fresh CentOS install and following the instructions top to bottom produces the same result - 
`AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.3. Set the 'ServerName' directive globally to suppress this message`

**Comment by uberbrady** [comment]
The warning message is expected, due to how Apache works and that we do not know beforehand what IP address and/or name your server will run under. The warning message can be ignored.

There is already a Snipe-IT-generated Snipe-IT container available at: https://hub.docker.com/r/snipe/snipe-it

We do not support you building your own dockerhub images. If you want to do that, you may, but we will not support it.
