### ISSUE TITLE
Metric system (esp. for print)

### ISSUE THREAD

**Issue by stbc** [snipe/snipe-it#6749]
**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.12
 - OS: Debian
 - Web Server: Apache

**Is your feature request related to a problem? Please describe.**
There is no switch from inches (US) to cm (rest of world, except UK) regarding labels

**Describe the solution you'd like**
Add a possibility to switch to the metric system.

**Comment by stbc** [comment]
Oh yeah...still relevant. As I am still not used to use a comma as a separator for thousands and a point to separate the decimals...

**Comment by C-Fu** [comment]
The rest of the world desperately needs this IMO

**Comment by ckruetze** [comment]
We would also love this one. Not sure if we desperately need it but it would be really useful for use in continental Europe

**Comment by Kaphalor** [comment]
Totally agree!
Fiddling around with inch while all our system is in metric system is pure pain

**Comment by ghost** [comment]
+1 in support of implementation.

**Comment by jpflanegan** [comment]
This would be nice to use

**Comment by Sepiolx64** [comment]
Just to give this thing an update, I'm still in favour of seing this implemented.
