### ISSUE TITLE
Feature request: Prepared for user

### ISSUE THREAD

**Issue by D2nnyim** [snipe/snipe-it#675]
I was wondering: 
We are preparing a lot of systems for our users.
I was hoping that I can install systems for a user, and 'reserve' these system for those users (so not yet check out). With a future date for when they pick them up.
Is that easy to do?

**Comment by dbierspb** [comment]
@D2nnyim not currently although you can create a new status and call it "reserved" (part of ready to deploy) and check items out to users and change their status to reserved. 

This would probably be the workaround for you for now.
