### ISSUE TITLE
Can I change the sender's email address to the person who applied for it?

### ISSUE THREAD

**Issue by 2095311** [snipe/snipe-it#6753]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version : v4.6.12 build 3982 (gd687e1d76)
 - OS: [e.g. Ubuntu, CentOS] : Centos 7.1
 - Web Server: [e.g. Apache, IIS] : Apache
 - PHP Version : 7.1.11

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Windows 10
 - Browser [e.g. chrome, safari]  : chrome

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

![image](https://user-images.githubusercontent.com/47856667/53171479-30639300-3626-11e9-9d94-ef3659a4e560.png)

hi,
it is fixed at the e-mail address currently set to .env
can I change the sender's email address to the person who applied for it?

**Comment by 2095311** [comment]
![image](https://user-images.githubusercontent.com/47856667/53172586-0d86ae00-3629-11e9-8a67-792564b94b00.png)

**Comment by EarlRamirez** [comment]
Yes you can change the sender email

**Comment by snipe** [comment]
No, you can’t change the sender to the person who requested the item. We can potentially add a reply-to, if that would solve your issue (so the admin can reply directly), but we’d run into sending issues trying to impersonate people who do not have authentication info in the env.
