### ISSUE TITLE
Whoops something went wrong

### ISSUE THREAD

**Issue by invalidi11** [snipe/snipe-it#6758]
![image](https://user-images.githubusercontent.com/47954268/53306431-f7f8ca80-385a-11e9-85e9-46fe97ec496b.png)
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running
- Version of PHP you're running
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

(3/3) QueryExceptionSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '''' at line 1 (SQL: ALTER TABLE assets CHANGE _snipeit_mac_address _snipeit_mac_address_1 VARCHAR(191) DEFAULT ''NULL'')
--
in Connection.php line 647
at Connection->runQueryCallback('ALTER TABLE assets CHANGE _snipeit_mac_address _snipeit_mac_address_1 VARCHAR(191) DEFAULT \'\'NULL\'\'',array(), object(Closure))in Connection.php line 607
at Connection->run('ALTER TABLE assets CHANGE _snipeit_mac_address _snipeit_mac_address_1 VARCHAR(191) DEFAULT \'\'NULL\'\'', array(),object(Closure))in Connection.php line 450
at Connection->statement('ALTER TABLE assets CHANGE _snipeit_mac_address _snipeit_mac_address_1 VARCHAR(191) DEFAULT \'\'NULL\'\'')in Blueprint.php line 86
at Blueprint->build(object(MySqlConnection), object(MySqlGrammar))in Builder.php line 239
at Builder->build(object(Blueprint))in Builder.php line 148
at Builder->table('assets', object(Closure))in Facade.php line 221
at Facade::__callStatic('table', array('assets', object(Closure)))in 2017_01_25_063357_fix_utf8_custom_field_column_names.php line 31
at updateLegacyColumnName(object(CustomField))in 2017_01_25_063357_fix_utf8_custom_field_column_names.php line 71
at FixUtf8CustomFieldColumnNames->up()in Migrator.php line 359
at Migrator->Illuminate\Database\Migrations\{closure}()in Migrator.php line 365
at Migrator->runMigration(object(FixUtf8CustomFieldColumnNames), 'up')in Migrator.php line 177
at Migrator->runUp('C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_01_25_063357_fix_utf8_custom_field_column_names.php', 3, false)in Migrator.php line 146
at Migrator->runPending(array('C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_01_25_063357_fix_utf8_custom_field_column_names.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_03_03_154632_add_time_date_display_to_settings.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_03_10_210807_add_fields_to_manufacturer.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_05_08_195520_increase_size_of_field_values_in_custom_fields.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_05_22_204422_create_departments.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_05_22_233509_add_manager_to_locations_table.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_06_14_122059_add_next_autoincrement_to_settings.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_06_18_151753_add_header_and_first_row_to_importer_table.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_07_07_191533_add_login_text.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_07_25_130710_add_thumbsize_to_settings.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_08_03_160105_set_asset_archived_to_zero_default.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_08_22_180636_add_secure_password_options.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_08_25_074822_add_auditing_tables.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_08_25_101435_add_auditing_to_settings.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_09_18_225619_fix_assigned_type_not_being_nulled.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_10_03_015503_drop_foreign_keys.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_10_10_123504_allow_nullable_depreciation_id_in_models.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_10_17_133709_add_display_url_to_settings.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_10_19_120002_add_custom_forgot_password_url.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_10_19_130406_add_image_and_supplier_to_accessories.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_10_20_234129_add_location_indices_to_assets.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_10_25_202930_add_images_uploads_to_locations_manufacturers_etc.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_10_27_180947_denorm_asset_locations.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_10_27_192423_migrate_denormed_asset_locations.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_10_30_182938_add_address_to_user.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_11_08_025918_add_alert_menu_setting.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_11_08_123942_labels_display_company_name.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_12_12_010457_normalize_asset_last_audit_date.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_12_12_033618_add_actionlog_meta.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2017_12_26_170856_re_normalize_last_audit.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_01_17_184354_add_archived_in_list_setting.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_01_19_203121_add_dashboard_message_to_settings.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_01_24_062633_add_footer_settings_to_settings.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_01_24_093426_add_modellist_preferenc.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_02_22_160436_add_remote_user_settings.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_03_03_011032_add_theme_to_settings.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_03_06_054937_add_default_flag_on_statuslabels.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_03_23_212048_add_display_in_email_to_custom_fields.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_03_24_030738_add_show_images_in_email_setting.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_03_24_050108_add_cc_alerts.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_03_29_053618_add_canceled_at_and_fulfilled_at_in_requests.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_03_29_070121_add_drop_unique_requests.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_03_29_070511_add_new_index_requestable.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_04_02_150700_labels_display_model_name.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_04_16_133902_create_custom_field_default_values_table.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_05_04_073223_add_category_to_licenses.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_05_04_075235_add_update_license_category.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_05_08_031515_add_gdpr_privacy_footer.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_05_14_215229_add_indexes.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_05_14_223646_add_indexes_to_assets.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_05_14_233638_denorm_counters_on_assets.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_05_16_153409_add_first_counter_totals_to_assets.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_06_21_134622_add_version_footer.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_07_05_215440_add_unique_serial_option_to_settings.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_07_17_005911_create_login_attempts_table.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2018_07_24_154348_add_logo_to_print_assets.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2019_02_14_154310_change_auto_increment_prefix_to_nullable.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2019_02_16_143518_auto_increment_back_to_string.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2019_02_20_234421_make_serial_nullable.php', 'C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations/2019_02_21_224703_make_fields_nullable_for_integrity.php'), array('pretend' => false, 'step' => false))in Migrator.php line 95
at Migrator->run(array('C:\\inetpub\\wwwroot\\snipe-it\\database\\migrations'), array('pretend' => false, 'step' => false))in MigrateCommand.php line 69
at MigrateCommand->fire()
at call_user_func_array(array(object(MigrateCommand), 'fire'), array())in BoundMethod.php line 29
at BoundMethod::Illuminate\Container\{closure}()in BoundMethod.php line 87
at BoundMethod::callBoundMethod(object(Application), array(object(MigrateCommand), 'fire'), object(Closure))in BoundMethod.php line 31
at BoundMethod::call(object(Application), array(object(MigrateCommand), 'fire'), array(), null)in Container.php line 539
at Container->call(array(object(MigrateCommand), 'fire'))in Command.php line 182
at Command->execute(object(ArrayInput), object(OutputStyle))in Command.php line 255
at Command->run(object(ArrayInput), object(OutputStyle))in Command.php line 167
at Command->run(object(ArrayInput), object(BufferedOutput))in Application.php line 946
at Application->doRunCommand(object(MigrateCommand), object(ArrayInput), object(BufferedOutput))in Application.php line 248
at Application->doRun(object(ArrayInput), object(BufferedOutput))in Application.php line 148
at Application->run(object(ArrayInput), object(BufferedOutput))in Application.php line 141
at Application->call('migrate', object(Collection), null)in Kernel.php line 220
at Kernel->call('migrate', array('--force' => true))in Facade.php line 221
at Facade::__callStatic('call', array('migrate', array('--force' => true)))in SettingsController.php line 253
at SettingsController->getSetupMigrate()
at call_user_func_array(array(object(SettingsController), 'getSetupMigrate'), array())in Controller.php line 55
at Controller->callAction('getSetupMigrate', array())in ControllerDispatcher.php line 44
at ControllerDispatcher->dispatch(object(Route), object(SettingsController), 'getSetupMigrate')in Route.php line 203
at Route->runController()in Route.php line 160
at Route->run()in Router.php line 572
at Router->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CreateFreshApiToken.php line 49
at CreateFreshApiToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForTwoFactor.php line 49
at CheckForTwoFactor->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckLocale.php line 42
at CheckLocale->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in VerifyCsrfToken.php line 65
at VerifyCsrfToken->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in AddQueuedCookiesToResponse.php line 37
at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in EncryptCookies.php line 59
at EncryptCookies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Router.php line 574
at Router->runRouteWithinStack(object(Route), object(Request))in Router.php line 533
at Router->dispatchToRoute(object(Request))in Router.php line 511
at Router->dispatch(object(Request))in Kernel.php line 176
at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))in Pipeline.php line 30
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Debugbar.php line 51
at Debugbar->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TransformsRequest.php line 30
at TransformsRequest->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForDebug.php line 25
at CheckForDebug->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForSetup.php line 35
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 56
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 64
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 148
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

**Comment by invalidi11** [comment]
this is a fresh install

**Comment by EarlRamirez** [comment]
Since its a fresh install you can try a couple of things
- try running the migration 
- drop DB and recreate it (not a nice way)

**Comment by invalidi11** [comment]
Will do thanks.

**Comment by KARTHIKEYANINDIRAN** [comment]
check database collation type is utf8mb4_unicode_ci in snipeit database.

**Comment by invalidi11** [comment]
Thank you I know for a fact it was not that. Do you have a good source with step by step instructions?

**Comment by EarlRamirez** [comment]
You can give this a try https://github.com/EarlRamirez/snipeit_iso

**Comment by invalidi11** [comment]
Would this iso work on a Pi?

  On March 7, 2019 at 2:21 PM Earl Ramirez <notifications@github.com> wrote:
 
 
 You can give this a try https://github.com/EarlRamirez/snipeit_iso

**Comment by invalidi11** [comment]
if not, where can I find instructions for a Pi to run locally?

  On March 7, 2019 at 2:21 PM Earl Ramirez <notifications@github.com> wrote:
 
 
 You can give this a try https://github.com/EarlRamirez/snipeit_iso

**Comment by EarlRamirez** [comment]
> Would this iso work on a Pi? On March 7, 2019 at 2:21 PM Earl Ramirez <notifications@github.com> wrote: You can give this a try https://github.com/EarlRamirez/snipeit_iso —You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

Unfortunately, this will not work on an ARM architecture

<blockquote><img src="https://avatars0.githubusercontent.com/u/12306859?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/EarlRamirez/snipeit_iso">EarlRamirez/snipeit_iso</a></strong></div><div>Up and running with Snipe-IT. Contribute to EarlRamirez/snipeit_iso development by creating an account on GitHub.</div></blockquote>

**Comment by EarlRamirez** [comment]
> if not, where can I find instructions for a Pi to run locally? On March 7, 2019 at 2:21 PM Earl Ramirez <notifications@github.com> wrote: You can give this a try https://github.com/EarlRamirez/snipeit_iso —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

This should help you get going _https://snipe-it.readme.io/docs/installation_ 

<blockquote><img src="https://avatars0.githubusercontent.com/u/12306859?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/EarlRamirez/snipeit_iso">EarlRamirez/snipeit_iso</a></strong></div><div>Up and running with Snipe-IT. Contribute to EarlRamirez/snipeit_iso development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="/favicon.ico" width="48" align="right"><div><strong><a href="https://snipe-it.readme.io/docs/installation">Installation</a></strong></div><div>The installation instructions provided here are for a production installation of Snipe-IT. If you are a developer looking to contribute to Snipe-IT, please see the [Contributing](doc:contributing) page.  Once you have [downloaded Snipe-IT](doc:downloading), you'll need to complete all of the steps i...</div></blockquote>
