### ISSUE TITLE
Blank Assets Pages

### ISSUE THREAD

**Issue by dbierspb** [snipe/snipe-it#676]
I have a feeling this is more than likely due to a change in database structure or calls.

Currently seeing the following at asset pages (deployed, pending, etc):

![http://iaas.me/screenshots/2015-03-18_1343.png](http://iaas.me/screenshots/2015-03-18_1343.png)

Although, I can see the assets on other pages (like List All)

![http://iaas.me/screenshots/2015-03-18_1345.png](http://iaas.me/screenshots/2015-03-18_1345.png)

Commands for attempted update/upgrade:

```
[13:43:17] [root@asset asset]$ php composer.phar dump-autoload
Generating autoload files
[13:43:26] [root@asset asset]$ php artisan migrate
**************************************
*     Application In Production!     *
**************************************

Do you really wish to run this command? Y
Nothing to migrate.
```

The `git pull`:
```
[13:43:33] [root@asset asset]$ git pull
remote: Counting objects: 297, done.
remote: Compressing objects: 100% (171/171), done.
remote: Total 297 (delta 177), reused 76 (delta 76), pack-reused 50
Receiving objects: 100% (297/297), 106.07 KiB, done.
Resolving deltas: 100% (186/186), done.
From https://github.com/snipe/snipe-it
   61f1b14..7e573c7  develop    -> origin/develop
   cb171bc..1a615f8  master     -> origin/master
 * [new branch]      security-hotfix-sentry-2.1.5 -> origin/security-hotfix-sentry-2.1.5
Auto-merging CHANGELOG.md
Auto-merging CONTRIBUTING.md
Auto-merging README.md
Auto-merging app/controllers/admin/AssetsController.php
Auto-merging app/controllers/admin/UsersController.php
Auto-merging app/database/seeds/AssetsSeeder.php
Auto-merging app/lang/en/admin/users/table.php
Auto-merging app/lang/en/general.php
Auto-merging app/models/Asset.php
Auto-merging app/models/User.php
Auto-merging app/routes.php
Auto-merging app/views/backend/hardware/index.blade.php
Auto-merging app/views/backend/users/edit.blade.php
Auto-merging app/views/backend/users/index.blade.php
Auto-merging app/views/backend/users/view.blade.php
Auto-merging app/views/frontend/auth/signin.blade.php
Removing app/views/frontend/auth/signup.blade.php
Auto-merging composer.json
Removing public/assets/.siteflow
Auto-merging public/assets/css/bootstrap/bootstrap.css
Auto-merging public/assets/css/lib/jquery.dataTables.css
Auto-merging public/assets/js/jquery.dataTables.min.js
Auto-merging public/assets/js/snipeit.js
Merge made by recursive.
 CHANGELOG.md                                       |  170 +
 CODE_OF_CONDUCT.md                                 |   13 +
 CONTRIBUTING.md                                    |    6 +
 README.md                                          |    5 +
 app/config/packages/chumper/datatable/config.php   |  155 +
 app/config/version.php                             |    4 +-
 app/controllers/admin/AssetsController.php         |  150 +-
 app/controllers/admin/UsersController.php          |  151 +-
 .../2015_03_18_055327_add_note_to_user.php         |   32 +
 app/database/seeds/AssetsSeeder.php                |    4 +-
 app/lang/en/admin/users/table.php                  |    5 +-
 app/lang/en/general.php                            |    1 +
 app/models/Asset.php                               |    4 +-
 app/models/Throttle.php                            |   12 +
 app/models/User.php                                |   36 +-
 app/routes.php                                     |   11 +-
 app/views/backend/hardware/datatable.blade.php     |   32 +
 app/views/backend/hardware/index.blade.php         |  230 +-
 app/views/backend/layouts/default.blade.php        |   21 +-
 app/views/backend/users/edit.blade.php             |    9 +-
 app/views/backend/users/index.blade.php            |  142 +-
 app/views/backend/users/view.blade.php             |   22 +-
 app/views/frontend/auth/signin.blade.php           |   41 +-
 app/views/frontend/auth/signup.blade.php           |   85 -
 composer.json                                      |    4 +-
 composer.lock                                      |  149 +-
 public/assets/.siteflow                            |  531 -
 public/assets/css/bootstrap/bootstrap.css          |    4 +-
 public/assets/css/compiled/dataTables.colVis.css   |  185 +
 .../assets/css/compiled/dataTables.tableTools.css  |  345 +
 public/assets/css/compiled/layout.css              |    2 +-
 public/assets/css/lib/jquery.dataTables.css        |    8 +-
 public/assets/css/scss/layout.scss                 |    2 +-
 public/assets/img/tabletools/background.png        |  Bin 0 -> 944 bytes
 public/assets/img/tabletools/collection.png        |  Bin 0 -> 1166 bytes
 public/assets/img/tabletools/collection_hover.png  |  Bin 0 -> 1194 bytes
 public/assets/img/tabletools/copy.png              |  Bin 0 -> 2184 bytes
 public/assets/img/tabletools/copy_hover.png        |  Bin 0 -> 2797 bytes
 public/assets/img/tabletools/csv.png               |  Bin 0 -> 1607 bytes
 public/assets/img/tabletools/csv_hover.png         |  Bin 0 -> 1854 bytes
 public/assets/img/tabletools/pdf.png               |  Bin 0 -> 4325 bytes
 public/assets/img/tabletools/pdf_hover.png         |  Bin 0 -> 2786 bytes
 public/assets/img/tabletools/print.png             |  Bin 0 -> 2123 bytes
 public/assets/img/tabletools/print_hover.png       |  Bin 0 -> 2230 bytes
 public/assets/img/tabletools/xls.png               |  Bin 0 -> 1641 bytes
 public/assets/img/tabletools/xls_hover.png         |  Bin 0 -> 2061 bytes
 public/assets/js/dataTables.colVis.js              | 1107 ++
 public/assets/js/dataTables.tableTools.js          | 3215 +++++
 public/assets/js/jquery.dataTables.js              |14867 ++++++++++++++++++++
 public/assets/js/jquery.dataTables.min.js          | 3649 +-----
 public/assets/js/snipeit.js                        |    3 +-
 public/assets/swf/copy_csv_xls.swf                 |  Bin 0 -> 2232 bytes
 public/assets/swf/copy_csv_xls_pdf.swf             |  Bin 0 -> 58845 bytes
 53 files changed, 20819 insertions(+), 4593 deletions(-)
 create mode 100644 CODE_OF_CONDUCT.md
 create mode 100644 app/config/packages/chumper/datatable/.gitkeep
 create mode 100644 app/config/packages/chumper/datatable/config.php
 create mode 100644 app/database/migrations/2015_03_18_055327_add_note_to_user.php
 create mode 100644 app/models/Throttle.php
 create mode 100644 app/views/backend/hardware/datatable.blade.php
 delete mode 100644 app/views/frontend/auth/signup.blade.php
 delete mode 100644 public/assets/.siteflow
 create mode 100644 public/assets/css/compiled/dataTables.colVis.css
 create mode 100644 public/assets/css/compiled/dataTables.tableTools.css
 create mode 100644 public/assets/img/tabletools/background.png
 create mode 100644 public/assets/img/tabletools/collection.png
 create mode 100644 public/assets/img/tabletools/collection_hover.png
 create mode 100644 public/assets/img/tabletools/copy.png
 create mode 100644 public/assets/img/tabletools/copy_hover.png
 create mode 100644 public/assets/img/tabletools/csv.png
 create mode 100644 public/assets/img/tabletools/csv_hover.png
 create mode 100644 public/assets/img/tabletools/pdf.png
 create mode 100644 public/assets/img/tabletools/pdf_hover.png
 create mode 100644 public/assets/img/tabletools/print.png
 create mode 100644 public/assets/img/tabletools/print_hover.png
 create mode 100644 public/assets/img/tabletools/xls.png
 create mode 100644 public/assets/img/tabletools/xls_hover.png
 create mode 100644 public/assets/js/dataTables.colVis.js
 create mode 100644 public/assets/js/dataTables.tableTools.js
 create mode 100644 public/assets/js/jquery.dataTables.js
 create mode 100644 public/assets/swf/copy_csv_xls.swf
 create mode 100644 public/assets/swf/copy_csv_xls_pdf.swf
```

Correction to current ownership + permissions (as I am running this behind suPHP/suExec):
```
[13:47:23] [root@asset asset]$ chown asset:asset * -Rf
[13:47:30] [root@asset asset]$ find . -type d -exec chmod 755 {} \;
[13:47:43] [root@asset asset]$ find . -type f -exec chmod 644 {} \;
```

The last errors in httpd error logs is related to a script I was working on a few days ago.  Nothing has occured since then and all requests are showing 200 OK's.

There is probably something simple I am missing although I only followed the current documentation for upgrading (http://snipeitapp.com/documentation/upgrading/).  I have also updated `bootstrap/start.php` just in case but this has no effect.

**Comment by snipe** [comment]
What do you see when you go to /admin/hardware/api/hardware?

**Comment by dbierspb** [comment]
A wall of text which I can make out as my assets.  This is actually at https://internal.domain/hardware/api/hardware and no admin folder.

**Comment by madd15** [comment]
could you try removing the content of `app/storage/views` and `app/storage/cache`

**Comment by dbierspb** [comment]
```
[15:05:41] [asset@asset storage]$ rm -rfv views/* cache/*
removed `views/036150857543bb5673fdf63d7d368561'
removed `views/0aee9a81d171a12f723f5ce0a7fc9f23'
removed `views/0cba790600b55837f6ff66301de204af'
....
....
....
removed `views/f36a9d74e50d61ebc2199c42becc425c'
removed `views/f71af7a8db9dec7fcdb581a54d4fb455'
removed `views/f900dc8821d8788bdbb54c7f3a0fe89c'
removed `views/f92af1b467e11639af2d39c248a6d52e'
removed `views/fe77a8a7baa6d9cf5da5658a54005387'
```

Same behavior; even after clearing browser cache just to be sure.

**Comment by madd15** [comment]
What is the url that is appearing the address bar when irs not working?

**Comment by dbierspb** [comment]
URL:  https://asset.local/hardware?status=Deployed

**Comment by madd15** [comment]
The entire table was reworked to use server side processing

**Comment by dbierspb** [comment]
Hm; the same behavior seems to be present as well when looking at the People page but not the Licenses page.

**Comment by madd15** [comment]
What browser are you using?

**Comment by dbierspb** [comment]
```
Name 	Firefox
Version 	36.0.1
User Agent 	Mozilla/5.0 (Windows NT 6.3; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0
```

**Comment by madd15** [comment]
In firefox on a page with issues press ctrl shift k and see if there are any error messages there

**Comment by madd15** [comment]
Also did you run `composer update` and `php artisan migrate` after you pulled?

**Comment by dbierspb** [comment]
![http://iaas.me/screenshots/2015-03-18_1526.png](http://iaas.me/screenshots/2015-03-18_1526.png)

^ Screenshot was more organized.

Composer-update:  No, I did not.  This was not stated in the upgrading/updating documentation on the website.  I am giving it a run now.

**Comment by madd15** [comment]
Can you click the hardware:364:20 link from that console and post content

**Comment by dbierspb** [comment]
That did it; seems to be working without issue now. (after the composer update).

These still give me little to no output but should be virtually irrelevant now:

```
[15:30:29] [asset@asset asset]$ php composer.phar dump-autoload
Generating autoload files
[15:30:42] [asset@asset asset]$ php artisan migrate
**************************************
*     Application In Production!     *
**************************************

Do you really wish to run this command? y
Nothing to migrate.
```

**Comment by dbierspb** [comment]
Need to add the "php composer.phar update" to the Upgrade/Update instructions @ http://snipeitapp.com/documentation/upgrading/

**Comment by madd15** [comment]
Only thing is that it doesnt always need to be done

**Comment by dbierspb** [comment]
FYI it looks like exports are giving a lot of extra spaces:

![img](http://iaas.me/screenshots/2015-03-18_1535.png)

**Comment by snipe** [comment]
@dbierspb well, we do include that in the release notes. The develop branch is just that, so it's unstable and not recommended for production usage.

**Comment by snipe** [comment]
@dbierspb Basically, we don't expect anyone other than developers working on the code to use `develop`, or even `master`. Release notes are provided for actual software releases, which include things like the composer install.

`master` is the current (often unreleased) stable branch, while `develop` is the unstable development branch. I will almost never tell someone to grab the latest off of develop, unless I'm asking them to test if a fix we made may have resolved their issue. So, in general, stay away from `develop` unless you just can't wait to see what's being worked on. :) We do have some folks (like @madd15) who run two versions, one for developing on, as he contributes code pretty often, and one for production, but that use case is unusual, as most of the Snipe-IT users aren't devs.

**Comment by dbierspb** [comment]
@snipe righto -- Thanks for the help(s).  Will close it out now and keep it in my notes

**Comment by snipe** [comment]
I'll add a little more info that upgrading page, too. Thanks!

**Comment by snipe** [comment]
@dbierspb I just updated the Upgrading page - can you let me know if that's more clear? http://snipeitapp.com/documentation/upgrading/

**Comment by dbierspb** [comment]
@snipe that's better but there is no reference to developer for using `php composer.phar update` which is what fixed it for me.

**Comment by snipe** [comment]
Thing is, you shouldn't actually be running `composer update`, you should be running `composer install`. It's a far more unusual case where `composer update` is required, so it's not something that we'd recommend to most users.

I'm not sure how much you grok about composer, but basically, it works like this:

1. Developers change the required dependencies in `composer.json` and THEY run `composer update` on their system. `composer update` asks composer to run through all of the dependencies and grab whatever is latest according to the specifications in the `composer.json` file.
2. Running `composer update` generates a `composer.lock` file which gets checked into Git. 
3. Non-developers should be running `composer install` (or `composer install --no-dev`, ideally), which will use the `composer.lock` file that was generated by the devs.

Composer install is exponentially faster, since composer doesn't have to resolve all of the dependencies again, since the devs did that when they ran update. It looks at the `composer.lock` file, and assumes it should use the versions outlined there.

Make sense?

**Comment by dbierspb** [comment]
Yeah that's good -- Sorry I have never touched some of this stuff before. :)

**Comment by snipe** [comment]
It's no problem. Composer can be pretty overwhelming if you haven't used it.
