### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.settings' doesn't exist

### ISSUE THREAD

**Issue by CookieCrumbles** [snipe/snipe-it#6768]
I can't get passed step 2 of the setup page. It keeps throwing me this error.
Any solutions?

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**
1. Go to 'http://localhost:8383/setup/migrate'
2. Click on 'Create database tables'

**Expected behavior**
Create the tables?

**Server (please complete the following information):**
 - Snipe-IT Version snipe-it-4.6.13
 - OS: Windows server 12
 - Web Server: Apache
 - PHP Version 7.3.1
 - MySQL version 5.7.24

**Error Messages**
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.settings' doesn't exist (SQL: create table `settings` (`id` int unsigned not null auto_increment primary key, `option_name` varchar(191) not null, `option_value` varchar(191) not null, `created_at` timestamp null, `updated_at` timestamp null, `user_id` int null) default character set utf8mb4 collate utf8mb4_unicode_ci engine = InnoDB)

**Additional context**
- Fresh install
- What OS and web server you're running Snipe-IT on (**windows server 12**)
- What method you used to install Snipe-IT (**manual installation**)

[11:56:16] LOG.error: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.settings' doesn't exist in C:\wamp64\www\snipe-it\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:77

[11:56:16] LOG.error: PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.settings' doesn't exist in C:\wamp64\www\snipe-it\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:77

**Comment by CookieCrumbles** [comment]
I fixed it by changing PHP version and re-creating DB

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)

**Comment by Sudarmathi** [comment]
still am facing this error
Illuminate \ Database \ QueryException (42S02)
SQLSTATE[42S02]: Base table or view not found: 1932 Table 'snipeit.settings' doesn't exist in engine (SQL: alter table `settings` add `auto_increment_prefix` varchar(191) null)
i have recreated db also and my php version is 7.4.19
please anyone help me

**Comment by snipe** [comment]
It’s difficult to help when you haven’t given us much info, and are replying to a thread that 2 years old. 

I have no idea why your settings table wouldn’t exist, unless there was an error that triggered when it was being created - which I also don’t know about.

Please create a new issue and fill in the issue template with all of the info we ask there, as we’ll try to get you sorted.
