### ISSUE TITLE
can't type true or false for a boolean custom Field

### ISSUE THREAD

**Issue by ersatyle** [snipe/snipe-it#6769]
#### Expected Behavior (or desired behavior if a feature request)

in a custom field when specified a boolean text box it should accept the value  true, false, 1, 0, "1", and "0". as per the documentation
when editing an asset.

-----

#### Actual Behavior
it rejects true false "true" "false" and only accept  1 or 0

-----

#### Please confirm you have done the following before posting your bug report:

- [ no ] I have enabled debug mode 
- [YES ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
fresh
- Version of Snipe-IT you're running
**v4.6.7 build 3944 (g8f6ea84fc)**
- Version of PHP you're running
**7.0.33-0ubuntu0.16.04.1**

- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
**Win 10 1803, Chrome 72**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual install (not sure)

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Asset **management** / edit an asset  after adding a custom field set
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. 
**YES!**

![image](https://user-images.githubusercontent.com/21692877/53525345-8796b700-3aaf-11e9-8f96-d0f9c572aacd.png)

**Comment by snipe** [comment]
That’s part of Laravel’s Boolean value validation, not specific to SniPe-IT

**Comment by snipe** [comment]
(Also because it’s a form, any value is going to be treated as a string)

**Comment by stbc** [comment]
I just submitted an edit for https://snipe-it.readme.io/docs/custom-fields, as it needs to be adjusted to that fact :)

**Comment by snipe** [comment]
The better solution here would be to create a dropdown field and make true/false as the available options, IMHO

**Comment by Sxderp** [comment]
> The better solution here would be to create a dropdown field and make true/false as the available options, IMHO

With the current tools this is not possible. If we create a "listbox" then the sent value is "true" or "false" (strings) which does not evaluate.

**Comment by SonGokussj4** [comment]
Bump? This is still the issue. 
We've noticed this after a few edits that your true, false fields were reset... 

DOCS still say:

```R
The field under validation must be able to be cast as a boolean. Accepted input are true, false, 1, 0, "1", and "0".
```

Is this a bug or just normal behaviour and the docs are wrong.
