### ISSUE TITLE
artisan (or just plain PHP) upgrade script?

### ISSUE THREAD

**Issue by uberbrady** [snipe/snipe-it#677]
We've seen a few cases where people have tried to upgrade their Snipe-IT installations by hand and have run into various tiny little issues, which we then tend to have to walk people through.

What if we just put together a simple little `php artisan upgrade` script or `php ./upgrade.php` - and have it do the various things we've seen needed - like -
- blowing out composer cache directory
- blowing out rendered views
- re-running composer install (it should be 'install', not 'upgrade', right?)
- artisan migrate
- any other sneaky things we've seen work or not work in the past
- (we had to blow out the ./vendors directory a few times?)

And once we have this, any time we see that there's a new bit of mystical chicken-bone shaking we have to do to make the thing work, we can throw that in too.

The idea being - user does an in-place upgrade, runs the script, and it "just works". Voila, fewer support tickets :)
##

**Comment by uberbrady** [comment]
We can't say "artisan" unless Laravel is installed, so probably the plain-PHP script might be the best way.

**Comment by madd15** [comment]
@uberbrady great idea, have fun :P

**Comment by snipe** [comment]
BWAHAHA. @madd15 just "pull requests are welcome"-d you! 
![9aw5ox7](https://cloud.githubusercontent.com/assets/197404/6720752/5eab5d8e-cd83-11e4-8015-acbc43d7d8f0.gif)

**Comment by snipe** [comment]
My concern here has always been that we're basically asking a PHP script to run shell commands, which opens up a whole new can of worms with respect to support tickets. Additionally, you can't really run the migrations without artisan, at least not in any way that resembles the way Laravel wants you to do them. 

I feel like the closest we could get to this reasonably would be to have a PHP script that presents a web form and automatically copies the example configs over to where they belong, filling in the form data, and then shows the user what they need to do next on the command line.

**Comment by uberbrady** [comment]
How about a bash script? It could help handle little problems like - 

```sh
#!/bin/bash

rm -r ./vendors
if [ `which composer` ]]
then
  composer install
elsif [ -f ./composer.php ]
  php ./composer.php install
fi
php artisan migrate

rm -r ./app/storage/views/*
```

**Comment by snipe** [comment]
And for the windows users? I'll have to explain Cygwin in that case, no? (We have a lot of Windows users.)

**Comment by snipe** [comment]
(Or git-extensions)

**Comment by uberbrady** [comment]
UGH. Good point.

well, maybe someone smart can write a ```.BAT``` file that mirrors the functionality of the Unix one? I'm thinking @madd15 maybe?

Or maybe the PHP one after all - straw man:

```php
<?php //yes, no short-tags so @snipe doesn't kill me :/

some_function_to_recursively_delete("./vendors");
if(`which composer`) {
  `composer install`;
else if(is_file("./composer.php")) {
  `php ./composer.php install`;
} else {
  print("Can't find composer or composer.php. Aborting.");
  exit(1);
}
`php artisan migrate`;
some_function_to_recursive_delete("./app/storage/views");
?>
```

**Comment by snipe** [comment]
Lots of variables here though. Some folks have composer installed globally, so there wouldn't be a composer.phar. Also, some folks run this on shared hosting, where they have to specify the path to PHP in the composer invocation, since there are multipole versions of PHP installed. 

Deleting caches and vendors is trivial, it's all the rest of the hot mess (the part that's actually complicated for users to understand) that's complicated to execute via an installer. 

I think the real thing we should be trying to figure out is what part of the install/upgrade process actually trips the most people up. In general, most people can type `php composer.phar install`. If they run into issues doing that, a web-based installer isn't going to help with that, since it usually means some vendor moved their package, or the user is missing a dependency. A web installer will only obfuscate the error further there.

If composer has successfully been run, most people don't have an issue with `php artisan app:install` either, since it basically just asks a few questions, creates a user, and runs migrations.

**Comment by uberbrady** [comment]
I mean for people to type:

```php ./upgrade.php```

And I put in a switch for finding if composer is installed globally or just as composer.phar (which I incorrectly called "composer.php").

But still, you raise some valid points. I don't know if this is going to make things easier or not.

**Comment by snipe** [comment]
The gorgeous irony would be that we spend the time to make this thing, and it becomes the majority of the GH issues. :-/

![not-working](https://cloud.githubusercontent.com/assets/197404/7442729/ac6e62a2-f0d1-11e4-82fd-8a18b48d9453.gif)

**Comment by kobie-chasehansen** [comment]
I've got an upgrade bat that I can post tonight. Pretty simple though.

**Comment by kobie-chasehansen** [comment]
mine is pretty simple, I'm just updating from the develop branch

````bat
@echo off

echo.
echo Pulling Develop Branch from GitHub to install directory
echo.
svn update %systemdrive%\inetpub\wwwroot\snipe-it
echo.

cd %systemdrive%\inetpub\wwwroot\snipe-it
echo.
echo Running Composer Update
echo.
call composer install
echo.

echo Running Composer Dump-Autoload
echo.
call composer dump-autoload
echo.

echo Running Artisan Migrage
echo.
call php artisan migrate --force
echo.

pause
````

![image](https://cloud.githubusercontent.com/assets/10247644/7454671/ec21c8e4-f243-11e4-99f5-1937770bb1bc.png)

**Comment by snipe** [comment]
A simple upgrade.php is included in v4
