### ISSUE TITLE
Capitalise/Uppercase Serial Number and Asset Name

### ISSUE THREAD

**Issue by fyberoptik** [snipe/snipe-it#6770]
**Server (please complete the following information):**
Version v4.6.5 / CentOS 7 / Apache / PHP 7.1

**Is your feature request related to a problem? Please describe.**
I'm keen to get Serial Numbers and Asset Names be capitalised for when asset labels are printed out. It would be nice if this could perpetuate throughout the system too to give consistency.

**Describe the solution you'd like**
It would be nice to have a button in the settings which allows users to enforce characters are displayed in uppercase on selective fields (serial number / asset name). This would ensure a consist appear when browsing assets in the system but also when asset labels are printed.

**Describe alternatives you've considered**
To deal with the asset labels, I have put in place a custom CSS class to deal with the 2nd and 3rd element on the generated label's and configured this in the brand settings page. 
```
 /* Capitalise Serial Numbers and Tag on Labels */
 .qr_text .pull-left:nth-child(3n), .qr_text .pull-left:nth-child(2n){text-transform:uppercase !important;} 

```
For the table layout there aren't any field ID's passed through to the HTML so unable to customise the appearance of text in the rows. 

**Additional context**
<img width="202" alt="screenshot 2019-02-28 at 14 19 03" src="https://user-images.githubusercontent.com/3731693/53572734-daca4180-3b63-11e9-8890-90f062fcde4f.png">

**Comment by snipe** [comment]
I'm not sure this is something we'd want to add a setting for.... What happens if your admins add models, asset names, etc without capitalizing the first letter? The number of files this would touch would be a lot, for what I would consider to be an edge case that could be fixed by telling your admins to capitalize the first letter of the serial.
