### ISSUE TITLE
Images broken after upload on fresh install

### ISSUE THREAD

**Issue by awarre** [snipe/snipe-it#6771]
- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When uploading images to Snipe, the images successfully upload and are saved, but the URLs to the images 404. More detailed information below.

**To Reproduce**
1. Fresh install of Snipe-IT v5.0.0-beta-1.1
2. Upload a branding logo or manufacturer image
3. All references to these images are broken

**Server (please complete the following information):**
 - Snipe-IT Version: v5.0.0-beta-1.1
 - OS: Windows Server 2012 R2
 - Web Server: IIS
 - PHP Version: 7.3

**Error Messages**
- Only IIS error logged is a 404.

**Additional context**
- Fresh install
- Manual installation

### DETAILS
The images are uploading to 'public\uploads' rather than 'storage\app\public'.

I can see in upgrade.php there are references to migrating data from 'public\uploads', and creating a symlink. I **did not** perform an upgrade, but can verify a symlink *was not* created automatically, nor was any error presented during fresh installation.

Unfortunately manually migrating the files from  'public\uploads' to 'storage\app\public' and creating the symlink **does not** resolve the issue. The image files do successfully upload to 'storage\app\public', however the image links are still broken.

Local file system:
```
C:\inetpub\snipe-it\storage\app\public\logo.gif
```

URL to logo (broken):
```
http://192.168.97.42/storage/logo.gif
```

**Comment by AndroidCloned** [comment]
this is a permission error that I stumbled across. Ensure that your .env app_url is correct and clear your cache with artisan. Ensure that apache has the proper permissions to read and write to public and storage. I do have an issue with the email logo being broken in gmail. It works as intended with the master branch build but I am getting a broken link with the current beta. I have tried both formats png and jpeg with no success.

**Comment by awarre** [comment]
1. My .env APP_URL is correct
```
APP_URL=http://192.168.97.42
```

2. Clearly my cache and restarting my web server did not resolve.
```
php artisan config:clear
php artisan config:cache
```

3. In my case, it is not an Apache or permissions error. I am running Windows+IIS, and IIS has full RW to the folder. It is able to successfully save the images to the folder. After my manual creation of symlink to the correct folder, it even appears to place the images in the correct location.

**Comment by snipe** [comment]
> After my manual creation of symlink to the correct folder

You shouldn't need to symlink anything - we override that.

**Comment by awarre** [comment]
@snipe Is there anything useful I can do to give you more information on the source of my issue?

I can delete the symlink to get snipe back to the install state for testing.

**Comment by lopezio** [comment]
I can confirm the same problem here.

Setup: FreeBSD 11.2 / Apache 2.4.39, php 7.1.28, 
Snipe-it Branch: develop branch, on ded1a59914113. 

Some more detail about my setup (note that I replaced the actual local domain with "local" here)

Project Root is `/sites/snipeit/assets.local`
Document Root is `/sites/snipeit/assets.local/public`
APP_URL = `https://assets.local` (served via an apache proxy which terminates SSL)

URL in image sources: `/storage/assets/asset-IfUux0678KCC15JLIY.jpg` -> 404 Page not found, Sad panda.
File is uploaded and located in  `/sites/snipeit/assets.local/storage/app/private_uploads/assets/hardware-1-mnudy4Yl-screen-shot-2019-04-15-at-180715.png`

Webserver runs under dedicated user which has full ownership and r/w of resources in `/sites/snipeit/assets.local` and below.

Tried clearing config cache, didn't help.

Available for testing at any time, any hints appreciated!

**Comment by lopezio** [comment]
Hi, I am sorry to re-post on this issue, I tried to tweak other settings and revisit the common issues page, but no success. @awarre did you find a workaround? @snipe when You find a moment, can you give a pointer on what else to look up - to help debugging? Thanks a lot in advance and apologies for pushing on this issue.

**Comment by lopezio** [comment]
Solved on my part..! After exploring the artisan commands, I tried issuing 
`php artisan storage:link ` and the image paths all worked... Sorry for not finding this earlier...
