### ISSUE TITLE
Dashboard "Assets by status" total incorrect

### ISSUE THREAD

**Issue by AndroidCloned** [snipe/snipe-it#6773]
#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The dashboard "assets by status" is displaying the incorrect total. 
- Ready to deploy "1,273"
-Pending "50"
-Archived "50"

**To Reproduce**
1. upgrade from 4.6.13 to 5.0 1.1 beta
2. Dashboard is displaying example data
3. Scroll down to 'Assets by Status'

**Expected behavior**
Dashboard seems to be displaying the example data in the assets by status instead of actual data.

**Server (please complete the following information):**
 - Snipe-IT Version 5.0-1.1
 - OS: CentOs 7
 - Web Server: Apache2
 - PHP Version 7.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 72

**Additional context**
- Is this a fresh install or an upgrade? 
Upgrade
- What OS and web server you're running Snipe-IT on
CentOs 7 Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
upgrade.php
- Include what you've done so far in the installation, and if you got any error messages along the way.
permission errors when initially using upgrade.php which was corrected by giving apache group ownership
- Indicate whether or not you've manually edited any data directly in the database
- no data manipulation

**Comment by awarre** [comment]
These numbers are being statically set in **...\resources\views\dashboard.blade.php:321**, I'm assuming for testing purposes?

```
    "labels": [
        "Ready to Deploy (1,273)",
        "Pending (50)",
        "Archived (50)"
    ],
    "datasets": [
        {
            "data": [
                1273,
                50,
                50,
            ],
```

**Comment by AndroidCloned** [comment]
Issue has been resolved by commenting out the static data. Thank you!
