### ISSUE TITLE
Import Issue - Fresh Install Wamp

### ISSUE THREAD

**Issue by DaveCowley** [snipe/snipe-it#6779]
#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode (i think so)
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Import of CSV file stuck on import

**To Reproduce**
1. Go to 'import'
2. Click on 'select import file'
3. Select file and select headers to match references on snipe-it

**Expected behavior**
contents of file import to platform.

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.13 build 3985 (g5f3147cf3)
 - OS: Server 2012r2 with Wamp
 - Web Server: Wamp 3.1.7
 - PHP Version 7.2.14

**Desktop (please complete the following information):**
 - OS: w10
 - Browser chrome
 - Version 72.0.3626.121

**Additional context**
- Is this a fresh install or an upgrade? Fresh Install
- What OS and web server you're running Snipe-IT on 2012r2 Wamp
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) manual using link on snipe-it site
- Include what you've done so far in the installation, and if you got any error messages along the way. checked permissions on upload folder. 
- Indicate whether or not you've manually edited any data directly in the database - no

[laravel.log](https://github.com/snipe/snipe-it/files/2926589/laravel.log)

**Comment by EarlRamirez** [comment]
@DaveCowley it's complaining about the base table not found, try migrating the DB and see if that resolve the issue.
