### ISSUE TITLE
Add an arbitrary notes option for assets

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#678]
There are times when a problem is reported and fixed without the device needing to be checked back in. Having a notes field with a time and user stamp that isn't tied to the check in check out process would be great.

I feel like these notes could be kept in the asset log table, but we probably want to break them out so they're displayed separately on the page. Not sure tho.

**Comment by dbierspb** [comment]
There could be an additional table of asset notes  (asset_id, timestamp_note, note).  I could see this being useful.  I've had to actually manually add some notes with my own time stamps and description (item was dropped, crack on corner, 2015-03-20) etc

**Comment by snipe** [comment]
Notes (in general) are currently handled via the aset log. Not sure we'd change that just for this.

**Comment by dbierspb** [comment]
I don't think it's worth the extra work TBH and as the notes on the asset itself work fine for me but I was thinking more in terms of the condition of the item over time.  But, as I said, the notes section works fine for this and I don't think it's necessary.

**Comment by snipe** [comment]
This was a request from a user, I'm simply logging it here so it doesn't get lost. It's not actually a lot of extra work, and a few people have asked for it at this point. It may not be necessary for your use case, but it would apparently be useful for theirs.

**Comment by snipe** [comment]
Solved by new maintenances system
