### ISSUE TITLE
Base_DN in ldap settings are wrong and unable to change it

### ISSUE THREAD

**Issue by kgronn** [snipe/snipe-it#6782]
I have issue with Base_DN and unable to get the Base_DN to change. It has locked it self on a string where it searches for dc=ED. Cannot find where to change it. No matter what I write in Search filter and Base_DN it still adds the dc=ED in front. I need to get rid of DC=ED, but don't know how.

The Sync worked fine once and then when we tried to do a resync I get this error;

at HandleExceptions->handleError(2, 'ldap_search(): Search: No such object', '/var/www/snipeit/app/Models/Ldap.php', 265, array('base_dn' => 'dc=ED,dc=

Tried to clear out all cache and artisan config etc to no help. 
Double checked settings table in mysql and there is the correct string without the ED, but it still picks it up from somewhere??

#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
Snipe-IT version | v4.6.8  build 3959 (g194d0733d)
-- | --
Software License | AGPL3
PHP Version | 7.2.15-0ubuntu0.18.04.1
Laravel Version | 5.4.35

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win10
 - Browser [e.g. chrome, safari] Chrome and IE 11

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by andrefecto** [comment]
Did you try doing "php artisan config:clear" and/or "php artisan clear:cache" in your Snipe-IT root?

**Comment by kgronn** [comment]
Yes I did both of them but to no help. Can't get rid of the Base_DN  starting with dc=ED. Unable to locate where it picks up this ED string from. My "Base Bind DN" don't contain the letters "ED" at all.
Did it get this from the first initial sync with Active Directory since one of my OU's is named ED? But then it should not be dc=ED, it would be ou=ED?

**Comment by andrefecto** [comment]
Sorry I haven't gotten back to you on this. Have you tried specifying the LDAP query using the CLI to see if you get different results? https://snipe-it.readme.io/v4.6.3/docs/ldap-sync

**Comment by HinchK** [comment]
I think you may be having a unique front-end issue;  it only affects the ldap settings, and I’ve only seen it in chrome.


Can you please try an incognito browser, 
with no extensions?   You will need to log inn again and navigate to “admin/ldap”, make the change to Base DN and save

**Comment by kgronn** [comment]
Thanks guys but still no solution, same result with sync from CLI and unable to see or change to correct value in  Incognito window in Chrome. The Incognito window still displays the exact same Base-DN as before and no matter what I type it keeps adding the dc=ED infront of my string/value. At least according to the error message in debug mode. 
________________

at HandleExceptions->handleError(2, 'ldap_search(): Search: No such object', '/var/www/snipeit/app/Models/Ldap.php', 265, array('base_dn' => 'dc=ED,dc=****,dc=*****', 'ldapconn' => resource, 'ldap_bind' => null, 'filter' => '&(cn=*)', 'page_size' => 500, 'cookie' => '', 'result_set' => array(), 'global_count' => 0, 'ldap_paging' => true))
--
at ldap_search(resource, 'dc=ED,dc=******,dc=******', '(&(cn=*))')in Ldap.php line 265
______________________

**Comment by HinchK** [comment]
ok, so it sounds like any attempt to update the settings model is a being denied.    

Any chance you are currently logged in with a user profile that was imported from LDAP?


If so, let’s create a “superuser” admin account via the CLI, “php artisan snipeit:create-admin”.    There could be wrte-permission lock on the model -

**Comment by HinchK** [comment]
And thank you for being thorough @kgronn! This is a frustrating issue that is difficult to recreate!

**Comment by kgronn** [comment]
Created a new admin user with CLI and still same resul.
Is there a CLI command to change the Base_Dn settings?
Where can I find the CLI command library?

(1/1) ErrorExceptionldap_search(): Search: No such object
--
in Ldap.php line 265
at HandleExceptions->handleError(2, 'ldap_search(): Search: No such object', '/var/www/snipeit/app/Models/Ldap.php', 265, array('base_dn' => 'dc=ED,dc=*****,dc=******', 'ldapconn' => resource, 'ldap_bind' => null, 'filter' => '&(cn=*)', 'page_size' => 500, 'cookie' => '', 'result_set' => array(), 'global_count' => 0, 'ldap_paging' => true))
at ldap_search(resource, 'dc=ED,dc=*****,dc=******', '(&(cn=*))')in Ldap.php line 265
at Ldap::findLdapUsers('dc=ED,dc=*****,dc=*****l')in LdapSync.php line 128
at LdapSync->handle()
at call_user_func_array(array(object(LdapSync), 'handle'), array())in BoundMethod.php line 29
at BoundMethod::Illuminate\Container\{closure}()in BoundMethod.php line 87

**Comment by kgronn** [comment]
I finally found the problem. In the snipeit database, under locations, I found the culprit. Edited the location which had wrong value for "ldap_ou" and everything went back to normal again.

Not sure how the entry in the database got there but perhaps I misstyped something when installing snipeit or when configured the respective location.
