### ISSUE TITLE
Asset maintenances edit authority

### ISSUE THREAD

**Issue by mihni** [snipe/snipe-it#6787]
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Hi,

My english is bad :)

I have created an authorization group, group cannot edit asset maintenances. How to edit asset maintenance

Thanks...

**Comment by snipe** [comment]
You haven’t explained what you’re seeing here. What are you trying that isn’t working? What permissions does the user and group have? What error message happens when they try?

**Comment by mihni** [comment]
hi,

assigned authority : Assets: View full

but asset manintenance cannot edit
![asset](https://user-images.githubusercontent.com/48278178/53877025-24f66b80-4019-11e9-9273-25197c97b232.PNG)


asset maintenance edit not active, 
except super user, with which authority I can make active ?

thanks

**Comment by mihni** [comment]
@snipe  did I explain the problem?

**Comment by KFH-IT** [comment]
Same Problem here.

A bunch of Users is in a Group with every Right granted except "Global: Super User" and "Consumables: View" but don't have the ability to edit the Asset Maintenance.

There's no explicit Right to grant them in the Asset Section of the Permissions.

![image](https://user-images.githubusercontent.com/48587116/54424701-c4031d80-4713-11e9-8a8f-d1f71bc3cbf9.png)

**Comment by KFH-IT** [comment]
Answering on Stale: Problem still exists, would need a more granular right management.

**Comment by najamalvi** [comment]
Same, issue all non super users are unable to edit assets maintenances. 

its a bug, a user who can add maintenance should be allowed to edit the maintenance details. 
User A: added maintenance and accidently added cost as **$190** instead of **$90**  in such case the user is not able to correct this mistake. Only super user can edit it and correct the mistake.

ver: 4.6.6
Apache
PHP 7.2

**Comment by KSchmeeds** [comment]
We are seeing the same behavior on our installation of users being unable to edit asset Maintenances.

v4.6.16 - build 4018
CentOS 7
Apache 2.4.6
PHP 5.6.40

**Comment by Trog3r** [comment]
FYI: I just ran into this issue as well. Version v4.7.4 - build 4107

**Comment by King-GO** [comment]
need this feature too.

**Comment by najamalvi** [comment]
Please dont close. We need it.
