### ISSUE TITLE
Office365 Email MFA - Failed to authenticate on SMTP server

### ISSUE THREAD

**Issue by JacquesM7** [snipe/snipe-it#6789]
Good Afternoon,

I was wondering if I could get assistance with the above issue. We have Office365 for email with Multi-Factor Authentication enabled for security reasons. I tried to add our service desk email but with no success, O365 does allow App Password Generation to bypass the MFA but when that was used I still had no joy. Email details were added to the .env file.

If I have forgotten anything below, please let me know.

Debug mode is enabled and details are below.

Error: An Error has occured! Failed to authenticate on SMTP server with username "service.desk@shetlandfm.com" using 2 possible authenticators

**Message**
[15:23:57] LOG.error: Swift_TransportException: Failed to authenticate on SMTP server with username "service.desk@shetlandfm.com" using 2 possible authenticators in /home/cloud22/public_html/assets-ssc/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php:181
Stack trace:
#0 /home/cloud22/public_html/assets-ssc/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(332): Swift_Transport_Esmtp_AuthHandler->afterEhlo(Object(Swift_SmtpTransport))
#1 /home/cloud22/public_html/assets-ssc/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(118): Swift_Transport_EsmtpTransport->_doHeloCommand()
#2 /home/cloud22/public_html/assets-ssc/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#3 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(443): Swift_Mailer->send(Object(Swift_Message), Array)
#4 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(217): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#5 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(60): Illuminate\Mail\Mailer->send(Object(Illuminate\Support\HtmlString), Array, Object(Closure))
#6 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(113): Illuminate\Notifications\Channels\MailChannel->send(Object(App\Models\Setting), Object(App\Notifications\MailTest))
#7 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(89): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(App\Models\Setting), '3b90f572-261c-4...', Object(App\Notifications\MailTest), 'mail')
#8 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(64): Illuminate\Notifications\NotificationSender->sendNow(Object(Illuminate\Database\Eloquent\Collection), Object(App\Notifications\MailTest))
#9 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(36): Illuminate\Notifications\NotificationSender->send(Object(Illuminate\Database\Eloquent\Collection), Object(App\Notifications\MailTest))
#10 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Notifications\ChannelManager->send(Object(App\Models\Setting), Object(App\Notifications\MailTest))
#11 /home/cloud22/public_html/assets-ssc/app/Http/Controllers/Api/SettingsController.php(136): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#12 [internal function]: App\Http\Controllers\Api\SettingsController->ajaxTestEmail()
#13 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(55): call_user_func_array(Array, Array)
#14 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('ajaxTestEmail', Array)
#15 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\SettingsController), 'ajaxTestEmail')
#16 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Route.php(160): Illuminate\Routing\Route->runController()
#17 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(572): Illuminate\Routing\Route->run()
#18 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#21 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#25 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Router.php(511): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#26 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#27 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#28 /home/cloud22/public_html/assets-ssc/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /home/cloud22/public_html/assets-ssc/app/Http/Middleware/CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /home/cloud22/public_html/assets-ssc/app/Http/Middleware/CheckForSetup.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/cloud22/public_html/assets-ssc/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /home/cloud22/public_html/assets-ssc/app/Http/Middleware/NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /home/cloud22/public_html/assets-ssc/app/Http/Middleware/ContentSecurityPolicyHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\ContentSecurityPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /home/cloud22/public_html/assets-ssc/app/Http/Middleware/ReferrerPolicyHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\ReferrerPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /home/cloud22/public_html/assets-ssc/app/Http/Middleware/XssProtectHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /home/cloud22/public_html/assets-ssc/app/Http/Middleware/FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#65 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#66 /home/cloud22/public_html/assets-ssc/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#67 /home/cloud22/public_html/assets-ssc/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#68 {main}

**Exception**
[15:23:57] LOG.error: Swift_TransportException: Failed to authenticate on SMTP server with username "service.desk@shetlandfm.com" using 2 possible authenticators in /home/cloud22/public_html/assets ssc/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php:181

**Email .env**

# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=smtp.office365.com
MAIL_PORT=587
MAIL_USERNAME=service.desk@shetlandfm.com
MAIL_PASSWORD=******
MAIL_ENCRYPTION=TLS
MAIL_FROM_ADDR=service.desk@shetlandfm.com
MAIL_FROM_NAME='Assets - I.T Service Desk'
MAIL_REPLYTO_ADDR=service.desk@shetlandfm.com
MAIL_REPLYTO_NAME='Assets - I.T Service Desk'

**Comment by snipe** [comment]
Hm, I haven't seen this one before. Try lowercasing `tls`, and also try port 25 instead of 587

**Comment by snipe** [comment]
(Make sure you clear your config cache as well after making the changes - `php artisan config:clear`)

**Comment by williamsant** [comment]
I want to re-open this issue, same issue i have at the moment when installing from gitpull.

Even if i change the mail MAIL_HOST to gmail or any other, i will still get the unable to establish connection with smtp.office365.com

**Comment by williamsant** [comment]
My issue is that i had to let HTTPD make network socket connections & allow it to send out mail.
The below worked with CentOS

To allow for HTTPD  to make Network Socket connections
setsebool -P httpd_can_network_connect on

To allow for HTTPD  to send out mail.
setsebool -P httpd_can_sendmail on

Thx
