### ISSUE TITLE
Pie Chart shows dummy data

### ISSUE THREAD

**Issue by Mezzle** [snipe/snipe-it#6792]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Pie chart on dashboard is showing dummy data.

**To Reproduce**
1. Look at it

**Comment by Mezzle** [comment]
Fixed by #6793

**Comment by snipe** [comment]
Can you be sure to note that these issues are on develop moving forward? At first glance, these open issues make it look like our product is really broken :)

**Comment by Mezzle** [comment]
Ah! Sorry!  

I'm happy to just throw PRs at you if you want?  I just wanted to meet the contributing guidelines :)

**Comment by snipe** [comment]
No worries - we really appreciate the help! As long as the PR has the same info about what's actually being fixed (what problem it solves, etc), I'm fine with just PRs. Your PRs are small and clean and easy to read, so I don't need a lot more than that.
