### ISSUE TITLE
Add user tracking to Asset Maintenance

### ISSUE THREAD

**Issue by iwendol** [snipe/snipe-it#6796]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.13
 - OS: Ubuntu 18.04 Server LTS
 - Web Server: Apache
 - PHP Version 

**Is your feature request related to a problem? Please describe.**
New to SnipeIT.  I'd like to be able to tie users to asset Maintenance in order to track Asset abuse by users.  For example, when a user shatters an ipad screen, I swap tablets and get the user running again while i send the iPad out for a screen replacement.  I don't see an option to track repairs by user in the system.

**Describe the solution you'd like**
Custom fields in the maintenance reporting area with the ability to attach repair to a user.  And a report, or an ability to customize a report to track repairs by user.

**Describe alternatives you've considered**
The alternative is just manually updateing user notes with repair issues.

**Additional context**

**Comment by FE-sys** [comment]
Attempting to setup Snipe IT for a school district. Would also like to track user/location breakage when creating Maintenances! Right now only solution is notes. Saw it appear in Digest but didn't look like anything came of it.

**Comment by rov63rus** [comment]
we need this feature to track service per user. Or add custom field to setup what to track
