### ISSUE TITLE
How to automate Snipe-it?

### ISSUE THREAD

**Issue by SavageSquirrel** [snipe/snipe-it#6797]
**Server (please complete the following information):**
 - Snipe- unknown version
 - OS: Windows and/or CentOS
 - Web Server: 
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

We have thousands of data entry for the fields in our Snipe-it inventory system, and that is far too time consuming. We are IT support company for other companies, and this is a good free software, but it is too time consuming.

**Describe the solution you'd like**
We need as much automation of inventory updating as possible. Does anybody know if someone has created a feature that can add more automation of new data into Snipe-it? We are looking to have an inventory software such as Snipe-it receive and display data from hundreds of desktop computers automatically, with all the data points updating into Snipe-it.
Example: An office worker's desktop computer is upgraded from Windows 7 to Windows 10, and later in the day, that computer communicates somehow with Snipe-it, and tells it that it is now a Windows 10 computer.

**Describe alternatives you've considered**
Is there a software that can automatically send computer desktop system information, for example in a CSV file, to a plug-in or add-on for Snipe-it? Thank you!

We have also considered Switching to Spiceworks, as they have an inventory management system, and a ticketing system, but our business owner does not want to switch to that system, perhaps because it would cost him money.

**Additional context**
I am a new Snipe-it user, but I do have a degree in computers, so I am good with software, but new to this one. Please let me know if there is any way I can improve our situation, to get things moving, you will be of so much help, thank you!

**Comment by EarlRamirez** [comment]
I know there are a few in the community that will be able to shed some light here for you, for sure there is a posweshell script bthat works with AD

**Comment by SavageSquirrel** [comment]
:D

**Comment by EarlRamirez** [comment]
@SavageSquirrel check out https://github.com/snazy2000/SnipeitPS @snazy2000 is the man behind this.

**Comment by andrefecto** [comment]
I am working on a PowerShell script that will sync AD information to Snipe-IT but not from End User to Snipe-IT. The PS Module that @EarlRamirez linked to would require you to upgrade your PS version on all endpoints to v5+ or to also install the PowerShellGet on all older machines. (This means anything older than Windows 10 needs an upgrade or dependency install.) Also, running a script like this on endpoints would expose your local API key which probably isn't the best idea. 

There could be ways around this by having a script on each machine write a flat file that a then secure server picks up and uses the API to import but this would be a lot of orchestrating for just some attributes but if you're willing then go on you! 

You could also try having a script run on a secure server that remotely connects to every machine for its information, (see [here](https://docs.microsoft.com/en-us/powershell/scripting/samples/collecting-information-about-computers?view=powershell-6)) but your network administrators may not allow this and could be resource intensive depending on your total amount of endpoints.

Lastly, all of those methods bypass just using actual Active Directory lookups, which is what I am in the middle of doing. This also depends on what information you're actually getting and storing with Active Directory. You should also note that in Active Directory the "Operating System" field is ONLY updated when the computer is rebound to AD. So if you re-image a Windows 7 machine to Windows 10 in place and it doesn't change names/get rebound, then the OS field in AD will still say Windows 7.

With all this said if you have any experience with programming, picking up Powershell is very intuitive, very well documented, and a great skill if you have the time! Please let me know if you have any questions, I'll be happy to answer as best I can!

**Comment by SavageSquirrel** [comment]
Thank you for your advice.

**Comment by ReignSol** [comment]
https://github.com/ReignSol/snipeit-powershell

**Comment by bricelabelle** [comment]
We do this with the [Snipe API](https://snipe-it.readme.io/reference). Simply run a script on your client computers using your current management tools that gathers the data you want and then sends it to Snipe using a `curl` command. Curl is not native on windows but you can just put the curl binary on your machines or even run curl from a network path as well. We have our machines send info to snipe daily this way, which is especially effective with custom fields in Snipe. As far as syncing AD, we have a script running on the Snipe IT server that uses the API to get a list of all users in snipe, queries AD using the `ldapsearch` for each user, then writes the data we want to a CSV file. Then it runs a command to [import that CSV](https://snipe-it.readme.io/docs/importing) file so it's all automated and we get the fields we want.

**Comment by CireB1925** [comment]
> We do this with the [Snipe API](https://snipe-it.readme.io/reference). Simply run a script on your client computers using your current management tools that gathers the data you want and then sends it to Snipe using a `curl` command. Curl is not native on windows but you can just put the curl binary on your machines or even run curl from a network path as well. We have our machines send info to snipe daily this way, which is especially effective with custom fields in Snipe. I should also mention that we do this all using batch scripts on windows without the need for PowerShell or installing modules. On Macs, curl is native and we don't have to install anything there either.
> 
> As far as syncing AD, we have a script running on the Snipe IT server that uses the API to get a list of all users in snipe, queries AD using the `ldapsearch` (if using a linux server) for each user , then writes the data we want to a CSV file. Then it runs a command to [import that CSV](https://snipe-it.readme.io/docs/importing) file so it's all automated and we get the fields we want.

--------------

hi @bricelabelle , this is exactly what I wanna achieve, but I dont know how to use the api and how to use it as a script on the host. can you pls. guide me on the steps.  thank you so much

**Comment by CireB1925** [comment]
> **Server (please complete the following information):**
> 
> * Snipe- unknown version
> * OS: Windows and/or CentOS
> * Web Server:
> * PHP Version
> 
> **Is your feature request related to a problem? Please describe.**
> 
> We have thousands of data entry for the fields in our Snipe-it inventory system, and that is far too time consuming. We are IT support company for other companies, and this is a good free software, but it is too time consuming.
> 
> **Describe the solution you'd like**
> We need as much automation of inventory updating as possible. Does anybody know if someone has created a feature that can add more automation of new data into Snipe-it? We are looking to have an inventory software such as Snipe-it receive and display data from hundreds of desktop computers automatically, with all the data points updating into Snipe-it.
> Example: An office worker's desktop computer is upgraded from Windows 7 to Windows 10, and later in the day, that computer communicates somehow with Snipe-it, and tells it that it is now a Windows 10 computer.
> 
> **Describe alternatives you've considered**
> Is there a software that can automatically send computer desktop system information, for example in a CSV file, to a plug-in or add-on for Snipe-it? Thank you!
> 
> We have also considered Switching to Spiceworks, as they have an inventory management system, and a ticketing system, but our business owner does not want to switch to that system, perhaps because it would cost him money.
> 
> **Additional context**
> I am a new Snipe-it user, but I do have a degree in computers, so I am good with software, but new to this one. Please let me know if there is any way I can improve our situation, to get things moving, you will be of so much help, thank you!

--------------------------
hi @SavageSquirrel .. have you found a solution ??  thanks

**Comment by jgerle** [comment]
There is a rather basic open source Windows Agent available: https://github.com/Scope-IT/marksman. Maybe you can take it from there?

<blockquote><img src="https://avatars2.githubusercontent.com/u/40773778?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/Scope-IT/marksman">Scope-IT/marksman</a></strong></div><div>Windows agent for Snipe-IT asset management system  - Scope-IT/marksman</div></blockquote>

**Comment by javiercivica** [comment]
> Hay un Agente de Windows de código abierto bastante básico disponible: https://github.com/Scope-IT/marksman . ¿Quizás puedas tomarlo desde allí?
> 
> > <img alt="" width="48" src="https://avatars2.githubusercontent.com/u/40773778?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Alcance-IT / tirador](https://github.com/Scope-IT/marksman)**Agente de Windows para el sistema de gestión de activos Snipe-IT - Scope-IT / marksman

No funciona en las últimas versiones

<blockquote><img src="https://avatars2.githubusercontent.com/u/40773778?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/Scope-IT/marksman">Scope-IT/marksman</a></strong></div><div>Windows agent for Snipe-IT asset management system  - Scope-IT/marksman</div></blockquote>

**Comment by jmrmelo** [comment]
> We do this with the [Snipe API](https://snipe-it.readme.io/reference). Simply run a script on your client computers using your current management tools that gathers the data you want and then sends it to Snipe using a `curl` command. Curl is not native on windows but you can just put the curl binary on your machines or even run curl from a network path as well. We have our machines send info to snipe daily this way, which is especially effective with custom fields in Snipe. I should also mention that we do this all using batch scripts on windows without the need for PowerShell or installing modules. On Macs, curl is native and we don't have to install anything there either.
> 
> As far as syncing AD, we have a script running on the Snipe IT server that uses the API to get a list of all users in snipe, queries AD using the `ldapsearch` (if using a linux server) for each user , then writes the data we want to a CSV file. Then it runs a command to [import that CSV](https://snipe-it.readme.io/docs/importing) file so it's all automated and we get the fields we want.

Hi there! Sorry for bothering you. I am trying to automate Snipe IT like this but I am having some trouble finding out how will I auto-update the assets. Can you please help me? Thanks in advance!

**Comment by aadrsh** [comment]
Hi, please check https://github.com/aadrsh/snipe-it-python-agent 
i have used this method( deploying python exe on smb and running that from task scheduler) to automatically create assets along with their details in snipe it, but you can customize it a little bit according to your needs.

<blockquote><img src="https://opengraph.githubassets.com/5bbe2cdfd820f83c4b30b887e3d28d0fa3d4a1f83c10d117a5390ce8fb4fd958/aadrsh/snipe-it-python-agent" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/aadrsh/snipe-it-python-agent">GitHub - aadrsh/snipe-it-python-agent: Python script that can be used as snipe-it asset scanning agent</a></strong></div><div>Python script that can be used as snipe-it asset scanning agent - GitHub - aadrsh/snipe-it-python-agent: Python script that can be used as snipe-it asset scanning agent</div></blockquote>

**Comment by Patrick20240** [comment]
Hey hey :)
just wanted to ask if it is possible with any of the posted answers to automate Users and licenses.
We are a small MSP and i want to have a documentation about licenses from our customers.
So it´s important to get the data from and to multiple Companys.
It´s only for our own documentation and billing department. End users dont get access to snipeIT.

i see now: 
Agent
AzureAD API (?)
Python Script
Automate csv files? (Import Users, import licences, deleting users also possible via csv?)

When i would have the csv files from snipe-it i could automate a import job?
Syncing users and licenses via CSV?
And i want also so sync a list from our license supplier.
I can get a csv file with all Licenses we bought for our customers.
Is it possible to sync this also?

Users, users licenses
And all global licenses from our supplier.
So finally i want to have all licenses available, and licenses checked out to the users :)



Thank you so much for any hint. SnipeIT would be perfect :)

**Comment by aadrsh** [comment]
> Hey hey :) just wanted to ask if it is possible with any of the posted answers to automate Users and licenses. 

You can use the python script I've tried it but in a way I was aiming to save all software list of a PC in Snipe IT.
Do you have any way you can identify which PC has the license ? 
by any api or powershell script or by any command?
you can pipe the output of that command in python and 
use the api as is, and register the license to the user.
