### ISSUE TITLE
Fieldset order not affecting asset list order

### ISSUE THREAD

**Issue by ars3nic** [snipe/snipe-it#6798]
#### Expected Behavior (or desired behavior if a feature request)

I expect that changing the order of custom fields in a fieldset will change the order they are displayed on the asset list page.

![fieldset order](https://user-images.githubusercontent.com/14172512/53995635-a4f90000-4103-11e9-9a35-edb229e4ed1e.png)

-----

#### Actual Behavior

I believe this started out working correctly, but now at 9 custom fields in one fieldset, the asset list page is displaying those custom fields in a seemingly random order, instead of the order specified in the fieldset.  All of the assets currently added to the system use the same fieldset.

![asset list](https://user-images.githubusercontent.com/14172512/53995636-a6c2c380-4103-11e9-9802-3dac05068f36.png)

However, on the create asset page, they are still in the correct order.

![create asset](https://user-images.githubusercontent.com/14172512/53995849-6c0d5b00-4104-11e9-9625-bcad964c3606.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
     - Fresh install
- Version of Snipe-IT you're running
     - 4.6.13 build 3985
- Version of PHP you're running
     - 7.2.15
- Version of MySQL/MariaDB you're running
     - MariaDB 10.0.14
- What OS and web server you're running Snipe-IT on
     - Win7Pro, IIS 7.5
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
     - Manual
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
     - Assets -> List
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
     - Yes
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
     - Installed, added a few custom fields and asset models, and added 5 assets.
- Indicate whether or not you've manually edited any data directly in the database
     - No

**Comment by EarlRamirez** [comment]
@ars3nic I added 9 custom fields to a fieldset and re-arrange the order a few time and unfortunately, I am not able to reproduce the behaviour that you are experiencing.

See the sample below.
![image](https://user-images.githubusercontent.com/12306859/54065605-72701400-4277-11e9-9f7b-808e8bff8acf.png)

![image](https://user-images.githubusercontent.com/12306859/54065609-83208a00-4277-11e9-8a0a-ac27f633f3d6.png)

**Comment by ars3nic** [comment]
Well, I don't know what else is needed / what I can try; my screenshots clearly show that it is happening for me.
