### ISSUE TITLE
Feature request: Support u2f 2FA

### ISSUE THREAD

**Issue by Mezzle** [snipe/snipe-it#6799]
**Describe the solution you'd like**
I would like support for hardware 2 Factor Authentication for Snipe-IT.  I would prefer u2f as the mechanism

**Describe alternatives you've considered**
Currently there exists 2FA via TOTP in snipe-IT - other methods, U2F, FIDO2, WebAuthN etc could be made available - however, U2F is a simple starting block to expand u2f support.

**Additional context**
Written well, this could be expanded to offer other forms of 2FA.

**Comment by Mezzle** [comment]
Note: I'm looking into how easy this would be to implement myself :)

**Comment by ffuentes** [comment]
Hi @Mezzle that would be great. I ask @snipe about it in the v5 issue report (https://github.com/snipe/snipe-it/issues/6287#issuecomment-462585552)  but he says it's out of scope for now.

Any help you need for testing just let me know.

**Comment by snipe** [comment]
@ffuentes - I am not a he... 👎 Out of scope for now just means it likely won't make it into v5. We'd definitely welcome @Mezzle's PR if he can make it happen.

**Comment by ffuentes** [comment]
@snipe i'm sorry, I didn't mean that you don't want to, just that it's not in v5 roadmap for now, maybe v5.5 or v6.

For now I'm in  busy month/semester, but I'm very thankfully with the software. If I can get into the code I will try to help.
