### ISSUE TITLE
Unknown table 'COLUMN_STATISTICS' in information_schema (1109) .

### ISSUE THREAD

**Issue by shokinn** [snipe/snipe-it#6800]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
If I want to create a backup via the web interface I get an error that the 'COLUMN_STATISTICS' table is unknown.

**To Reproduce**
1. Go to Admin -> Backups interface
2. Click on 'Generate Backup'
3. See error

**Expected behavior**
A backup will be generated and available to download afterwards.

**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.13 - build 3985
 - OS: 16.04.1-Ubuntu 4.15.0-43-generic
 - Web Server: Apache HTTPD
 - PHP Version: 7.2.14
 - Database: AWS Amazon Aurora MySQL

**Desktop (please complete the following information):**
 - OS: macOS 10.14 mojave / Windows 10
 - Browser: Firefox
 - Version: 65.0.1 / 65.0.2

**Error Messages**
- Displayed error message
```
Error: Backup failed because The dump process failed with exitcode 2 : Misuse of shell builtins : mysqldump: Couldn't execute 'SELECT COLUMN_NAME, JSON_EXTRACT(HISTOGRAM, '$."number-of-buckets-specified"') FROM information_schema.COLUMN_STATISTICS WHERE SCHEMA_NAME = 'db_e46c6a80_d35b_4736_ae1e_84a5cf5fda6c' AND TABLE_NAME = 'accessories';': Unknown table 'COLUMN_STATISTICS' in information_schema (1109) . 
```

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
No. The Backup function is disabled in the demo. No way to reproduce.

**Additional context**
- Is this a fresh install or an upgrade? 
    - Fresh
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
    - Deployed from last stable to CloudFoundry
- CF manifest
    - ```yaml
      applications:
      - name: snipe-dev
        buildpacks:
        - php_buildpack
        memory: 512M
        instances: 1
        routes:
        - route: xxx.yyy.com
        stack: cflinuxfs3
        health-check-type: http
        health-check-http-endpoint: /login
        env:
          # --------------------------------------------
          # REQUIRED: BASIC APP SETTINGS
          # --------------------------------------------
          APP_ENV: development
          APP_DEBUG: true
          APP_KEY: xxx
          APP_URL: https://xxx.yyy.com
          # --------------------------------------------
          # OPTIONAL: SESSION SETTINGS
          # --------------------------------------------
          COOKIE_NAME: snipeit_session_dev
          COOKIE_DOMAIN: xxx.yyy.com
      ```
- Include what you've done so far in the installation, and if you got any error messages along the way.
    - Added custom field and field sets
    - Added status labels
    - Added categories
    - Added manufactures
- Indicate whether or not you've manually edited any data directly in the database
    - No, I don't

Looks like it's connected to this issue:
<https://serverfault.com/questions/912162/mysqldump-throws-unknown-table-column-statistics-in-information-schema-1109>

**Comment by shokinn** [comment]
Workaround:
`/etc/my.cnf` or `~/.my.cnf`:  
```
[mysqldump]
column-statistics=0
```

Source: <https://serverfault.com/questions/912162/mysqldump-throws-unknown-table-column-statistics-in-information-schema-1109/912677#912677>

**Comment by snipe** [comment]
Thanks for updating with a solution!

**Comment by karnoha** [comment]
Hi, thanks for sharing this solution. I had a the same problem and burned few hours on this issue.
@snipe Perhaps you can add this to the documentation, so other users can fix it faster?
Thanks and have a nice day!
K.
