### ISSUE TITLE
API Get asset by tag, returns the id of a deleted asset instead of existing

### ISSUE THREAD

**Issue by dutkaD** [snipe/snipe-it#6810]
#### Please confirm you have done the following before posting your bug report:

- [+] I have enabled debug mode 
- [+] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When using API to search "bytag", the request returns the id of the asset that was created first, meaning, that if the asset (with the same asset tag) was first created, then deleted and then created again - the search will return the tag of the first asset, which is currently deleted. 

**To Reproduce**
1. Create an asset with asset tag XXX 
2. Delete asset with the asset tag XXX
3. Create Create an asset with asset tag XXX again
4. Use API GET request to search for the Asset-ID by asset tag XXX

Response body returns ID of the asset created in step 1. 

**Expected behavior**
Response body returns ID of the asset created in step 3. 

**Error Messages**
- If you try to update the asset with the id returned by search you get "Asset existiert nicht", since the asset is actually deleted.

**Comment by Speed1** [comment]
Bug still present. Can we open the issue?
