### ISSUE TITLE
Upgraded Snipe-it now getting error 

### ISSUE THREAD

**Issue by LeeSharman** [snipe/snipe-it#6812]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode YES 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running
- Version of PHP you're running 7.1.26 
- Version of MySQL/MariaDB you're running MariaDB 10.0 
- What OS and web server you're running Snipe-IT on Server 2012 IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual then upgraded to GIT install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error  

(1/1) UnexpectedValueExceptionThe stream or file "C:\inetpub\wwwroot\snipe-it\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied
--
in StreamHandler.php line 107
at StreamHandler->write(array('message' => 'UnexpectedValueException: The stream or file "C:\\inetpub\\wwwroot\\snipe-it\\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\\inetpub\\wwwroot\\snipe-it\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\StreamHandler.php:107Stack trace:#0 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)#1 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(337): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#2 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(616): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#3 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#4 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#5 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(221): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#6 C:\\inetpub\\wwwroot\\snipe-it\\app\\Exceptions\\Handler.php(39): Illuminate\\Support\\Facades\\Facade::__callStatic(\'error\', Array)#7 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#9 C:\\inetpub\\wwwroot\\snipe-it\\public\\index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#10 {main}', 'context' => array(), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'production', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2019-03-12 13:46:41] production.ERROR: UnexpectedValueException: The stream or file "C:\\inetpub\\wwwroot\\snipe-it\\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\\inetpub\\wwwroot\\snipe-it\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\StreamHandler.php:107Stack trace:#0 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)#1 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(337): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#2 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(616): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#3 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#4 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#5 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(221): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#6 C:\\inetpub\\wwwroot\\snipe-it\\app\\Exceptions\\Handler.php(39): Illuminate\\Support\\Facades\\Facade::__callStatic(\'error\', Array)#7 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#9 C:\\inetpub\\wwwroot\\snipe-it\\public\\index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#10 {main} '))in AbstractProcessingHandler.php line 37
at AbstractProcessingHandler->handle(array('message' => 'UnexpectedValueException: The stream or file "C:\\inetpub\\wwwroot\\snipe-it\\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\\inetpub\\wwwroot\\snipe-it\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\StreamHandler.php:107Stack trace:#0 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)#1 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(337): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#2 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(616): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#3 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#4 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#5 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(221): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#6 C:\\inetpub\\wwwroot\\snipe-it\\app\\Exceptions\\Handler.php(39): Illuminate\\Support\\Facades\\Facade::__callStatic(\'error\', Array)#7 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#9 C:\\inetpub\\wwwroot\\snipe-it\\public\\index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#10 {main}', 'context' => array(), 'level' => 400, 'level_name' => 'ERROR', 'channel' => 'production', 'datetime' => object(DateTime), 'extra' => array(), 'formatted' => '[2019-03-12 13:46:41] production.ERROR: UnexpectedValueException: The stream or file "C:\\inetpub\\wwwroot\\snipe-it\\storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied in C:\\inetpub\\wwwroot\\snipe-it\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\StreamHandler.php:107Stack trace:#0 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\monolog\\monolog\\src\\Monolog\\Handler\\AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)#1 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(337): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)#2 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\monolog\\monolog\\src\\Monolog\\Logger.php(616): Monolog\\Logger->addRecord(400, Object(UnexpectedValueException), Array)#3 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(203): Monolog\\Logger->error(Object(UnexpectedValueException), Array)#4 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Log\\Writer.php(114): Illuminate\\Log\\Writer->writeLog(\'error\', Object(UnexpectedValueException), Array)#5 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Support\\Facades\\Facade.php(221): Illuminate\\Log\\Writer->error(Object(UnexpectedValueException))#6 C:\\inetpub\\wwwroot\\snipe-it\\app\\Exceptions\\Handler.php(39): Illuminate\\Support\\Facades\\Facade::__callStatic(\'error\', Array)#7 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(314): App\\Exceptions\\Handler->report(Object(UnexpectedValueException))#8 C:\\inetpub\\wwwroot\\snipe-it\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(118): Illuminate\\Foundation\\Http\\Kernel->reportException(Object(UnexpectedValueException))#9 C:\\inetpub\\wwwroot\\snipe-it\\public\\index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))#10 {main} '))in Logger.php line 337
at Logger->addRecord(400, object(UnexpectedValueException), array())in Logger.php line 616
at Logger->error(object(UnexpectedValueException), array())in Writer.php line 203
at Writer->writeLog('error', object(UnexpectedValueException), array())in Writer.php line 114
at Writer->error(object(UnexpectedValueException))in Facade.php line 221
at Facade::__callStatic('error', array(object(UnexpectedValueException)))in Handler.php line 39
at Handler->report(object(UnexpectedValueException))in HandleExceptions.php line 81
at HandleExceptions->handleException(object(UnexpectedValueException))

 

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error logon page
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by cdcs68** [comment]
Howdy!  

I have found at times after upgrades, the permissions are no longer set or working.  Can't explain why.  In my opinion, it appears you no longer have the proper permissions set on the f
 **storage** which is located in the c:\inetpub\wwwroot\snipeit directory.  I believe you need to make sure that both the IUSR and the IIS_IUSRS accounts have **full permission.**  I don't see where there is a need to do the same for the vendor folder.  

The next thing I would do is as follows:

1.  Change directory to c:\inetpub\wwwroot\snipeit
2.  Type in:  php artisan config:clear
3.  Type in:  php artisan cache:clear

Now see if it works.
