### ISSUE TITLE
Can't delete asset models

### ISSUE THREAD

**Issue by Ranlar** [snipe/snipe-it#6813]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I can not delete asset models.  It says there is an asset assigned to it so it can not be deleted.  But when I try to search for said asset it is not found.

**Expected behavior**
Once the asset is deleted should be able to delete the model.

**Screenshots**
![image](https://user-images.githubusercontent.com/48483838/54209260-76847780-44ab-11e9-87e7-d8f5f6185e85.png)

**Server (please complete the following information):**
Snipe-IT version | v4.2.0 build 3479 (gbf74bb1)
Software License | AGPL3
PHP Version | 7.0.21
Laravel Version | 5.4.35

**Desktop (please complete the following information):**
 - OS: Windows 10 1803
 - Chrome ersion 72.0.3626.121 (Official Build) (64-bit)

**Additional context**
- fresh install

**Comment by pcsmarts502** [comment]
Try and track down where the asset is located.  I had a similar issue.  My asset was in the achieved status

**Comment by Ranlar** [comment]
That got it thanks I was not aware the assets would not show up on the all assets list.
