### ISSUE TITLE
Fail to upgrade from 4.6.10 to 4.6.13

### ISSUE THREAD

**Issue by hoangdinhanphabe** [snipe/snipe-it#6816]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**
1. Coppy .env files, oauth-private.key, oauth-public.key, private_uploads folder, uploads folder to snipe-it ( v.4.6.13 )
2. Run the command composer install --no-dev --prefer-source
3. Run the command composer dump-autoload
4. Run the command php artisan migrate and the error shows up

**Expected behavior**
It should check SQL Migarate then finish up the upgrade process

**Screenshots**
![image](https://user-images.githubusercontent.com/42403971/54263051-6e5b3380-45a2-11e9-84e7-f4c0b57ec847.png)

**Server (please complete the following information):**
 - Snipe-IT Version : 4.6.10
 - OS: Windows Server 2012
 - Web Server: Wampserver
 - PHP Version : 7.1.9
 - SQL Version : 5.7.19

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 72

**Comment by snipe** [comment]
Please provide the entire output of the migrate command

**Comment by hoangdinhanphabe** [comment]
![2019-03-14-15-04-it anphabe net](https://user-images.githubusercontent.com/42403971/54340735-9b731900-466a-11e9-8481-0069bfbdd216.png)
Is it what you need ?

**Comment by snipe** [comment]
It sort of looks like it's choking on the email stuff, though I don't know why that would be triggering on a migration. What's your mail config block from your env? (Obscure any passwords, obviously)

**Comment by snipe** [comment]
My guess would be there's maybe a syntax error or something missing from your .env

**Comment by hoangdinhanphabe** [comment]
I just moved my old .env file to new directory without editing anything. This is my full .env file I used.

> # --------------------------------------------
> # REQUIRED: BASIC APP SETTINGS
> # --------------------------------------------
> APP_ENV=production
> APP_DEBUG=false
> APP_KEY=xxxxxxxxxxxxxxxx
> APP_URL=http://tech.com
> APP_TIMEZONE='Asia/Ho_Chi_Minh'
> APP_LOCALE=en
> 
> # --------------------------------------------
> # REQUIRED: DATABASE SETTINGS
> # --------------------------------------------
> DB_CONNECTION=mysql
> DB_HOST=127.0.0.1
> DB_DATABASE=itasset
> DB_USERNAME=root
> DB_PASSWORD=
> DB_PREFIX=null
> DB_DUMP_PATH='C:\\wamp64\\bin\\mysql\\mysql5.7.19\\bin\\'
> DB_CHARSET=utf8mb4
> DB_COLLATION=utf8mb4_unicode_ci
> 
> # --------------------------------------------
> # OPTIONAL: SSL DATABASE SETTINGS
> # --------------------------------------------
> DB_SSL=false
> DB_SSL_KEY_PATH=null
> DB_SSL_CERT_PATH=null
> DB_SSL_CA_PATH=null
> DB_SSL_CIPHER=null
> 
> # --------------------------------------------
> # REQUIRED: OUTGOING MAIL SERVER SETTINGS
> # --------------------------------------------
> MAIL_DRIVER=null
> MAIL_HOST=null
> MAIL_PORT=null
> MAIL_USERNAME=null
> MAIL_PASSWORD=null
> MAIL_ENCRYPTION=null
> MAIL_FROM_ADDR=null
> MAIL_FROM_NAME=null
> 
> #MAIL_DRIVER=smtp
> #MAIL_HOST=smtp.gmail.com
> #MAIL_PORT=587
> #MAIL_USERNAME=tech@gmail.com
> #MAIL_PASSWORD=
> #MAIL_ENCRYPTION=tls
> #MAIL_FROM_ADDR=tech@gmail.com
> #MAIL_FROM_NAME='tech'
> #MAIL_REPLYTO_ADDR=tech@gmail.com
> #MAIL_REPLYTO_NAME='tech'
> 
> # --------------------------------------------
> # REQUIRED: IMAGE LIBRARY
> # This should be gd or imagick
> # --------------------------------------------
> IMAGE_LIB=gd
> 
> # --------------------------------------------
> # OPTIONAL: SESSION SETTINGS
> # --------------------------------------------
> SESSION_LIFETIME=12000
> EXPIRE_ON_CLOSE=false
> ENCRYPT=false
> COOKIE_NAME=snipeit_session
> COOKIE_DOMAIN=null
> SECURE_COOKIES=false
> 
> # --------------------------------------------
> # OPTIONAL: SECURITY HEADER SETTINGS
> # --------------------------------------------
> REFERRER_POLICY=same-origin
> ENABLE_CSP=false
> 
> # --------------------------------------------
> # OPTIONAL: CACHE SETTINGS
> # --------------------------------------------
> CACHE_DRIVER=file
> SESSION_DRIVER=file
> QUEUE_DRIVER=sync
> 
> # --------------------------------------------
> # OPTIONAL: REDIS SETTINGS
> # --------------------------------------------
> REDIS_HOST=null
> REDIS_PASSWORD=null
> REDIS_PORT-null
> 
> # --------------------------------------------
> # OPTIONAL: AWS S3 SETTINGS
> # --------------------------------------------
> AWS_SECRET=null
> AWS_KEY=null
> AWS_REGION=null
> AWS_BUCKET=null
> 
> # --------------------------------------------
> # OPTIONAL: LOGIN THROTTLING
> # --------------------------------------------
> LOGIN_MAX_ATTEMPTS=10
> LOGIN_LOCKOUT_DURATION=60
> 
> # --------------------------------------------
> # OPTIONAL: MISC
> # --------------------------------------------
> APP_LOG=single
> APP_LOG_MAX_FILES=10
> APP_LOCKED=false
> FILESYSTEM_DISK=local
> APP_TRUSTED_PROXIES=192.168.1.1,10.0.0.1
> ALLOW_IFRAMING=false
> APP_CIPHER=AES-256-CBC
> GOOGLE_MAPS_API=

**Comment by hoangdinhanphabe** [comment]
I have solved this problem by edit the new .env file with old configuration in my old .env file and it works. Thank you so much for letting me know the problem comes from missing line in .env file. I doesn't know that there will be changes in new .env file.
