### ISSUE TITLE
While trying to generate Backup Error message- Error: Backup failed because The dump process failed with exitcode 1 : General error : 'C:\Program' is not recognized as an internal or external command, operable program or batch file. .

### ISSUE THREAD

**Issue by BharathKumarGajula** [snipe/snipe-it#6817]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode- No
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)- Yes

**Describe the bug**
While trying to generate Backup Error message- Error: Backup failed because The dump process failed with exitcode 1 : General error : 'C:\Program' is not recognized as an internal or external command, operable program or batch file. .

**To Reproduce**
1. Go to '.backups..'
2. Click on '..Generate Backup.'
4. See error- 
![image](https://user-images.githubusercontent.com/30508057/54275624-21328e00-45b1-11e9-8b42-9ded1fee7e4b.png)

**Expected behavior**
Backup generated 
**Screenshots**
![image](https://user-images.githubusercontent.com/30508057/54275643-2c85b980-45b1-11e9-8ebf-8a7d38af4ff3.png)

**Server (please complete the following information):**
 - Snipe-IT Version - 4.6.3
 - OS: [e.g. Ubuntu, CentOS]- Windows Server 2016
 - Web Server: [e.g. Apache, IIS]- IIS
 - PHP Version - 7.0.33

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]- Windows 10
 - Browser [e.g. chrome, safari]- Chrome
 - Version [e.g. 22]- 

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? - Yes
- What OS and web server you're running Snipe-IT on- Windows Server 2016
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)- Manual Install
- Include what you've done so far in the installation, and if you got any error messages along the way.- No
- Indicate whether or not you've manually edited any data directly in the database- No

I have given Full Control to IIS_USRS and IUSR to the complete Snipe-it folder and also windows/temp folder. And almost tried every step from all the previous issues mentioned. DB_DUMP_PATH is as below tried all combinations of double slashes \\and double and single quotes"".
DB_DUMP_PATH='C:\PROGRA~1\\MARIAD~1.0\\bin' 

Kindly help resolve.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by BharathKumarGajula** [comment]
Had to run php artisan confir:clear from Snipe IT folder CMD admin mode and restart IIS Server and it worked.

**Comment by WELLBOREIS** [comment]
> 
> 
> Had to run php artisan confir:clear from Snipe IT folder CMD admin mode and restart IIS Server and it worked.

Just FYI, it's "php artisan config:clear"
