### ISSUE TITLE
The email test passed the inbox but did not

### ISSUE THREAD

**Issue by BaronVIP** [snipe/snipe-it#6818]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by BaronVIP** [comment]
- 
MAIL_DRIVER=mail
MAIL_HOST=mail.qutoutiao.net
MAIL_PORT=587
MAIL_USERNAME=assets
MAIL_PASSWORD=mypassword
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=assets@qutoutiao.net
MAIL_FROM_NAME='assets-IT'
MAIL_REPLYTO_ADDR=assets@qutoutiao.net
MAIL_REPLYTO_NAME='assets-IT'

-

**Comment by BaronVIP** [comment]
![企业微信截图_15524833495385](https://user-images.githubusercontent.com/48519932/54282119-41287880-45d6-11e9-9a3b-850218024155.png)

**Comment by BaronVIP** [comment]
The test messages passed but there was no mail in the inbox

**Comment by BaronVIP** [comment]
Snipe-IT Version  V4.5.0
Centos 7
apache
php7.1
Windwos 10 
chrome

**Comment by snipe** [comment]
Check your SPAM folder. If it says it's sent, then the system believes it's been sent.

**Comment by BaronVIP** [comment]
> 检查您的垃圾邮件文件夹。如果它说它被发送，那么系统认为它已被发送。
![123](https://user-images.githubusercontent.com/48519932/54327898-d6fbec00-4646-11e9-9186-f9a94acf9460.png)
none

**Comment by snipe** [comment]
The only thing I can suggest is checking your mail server logs then. If there are connection or protocol issues, the email won't get sent, and the test will return an error.

**Comment by BaronVIP** [comment]
> 我唯一能建议的是检查你的邮件服务器日志。如果存在连接或协议问题，则不会发送电子邮件，测试将返回错误。

I am a newbie, can you tell me where to check my mail server log

**Comment by snipe** [comment]
I don't have any idea - I don't know who manages your mail server, what kind of mail server you're running, etc.

**Comment by snipe** [comment]
On a linux system it's usually `/var/log/maillog`. On Solaris it's `/var/adm/maillog`. On Debian/Ubuntu it's `/var/log/mail.log`, but it will depend on the OS of the server where the mail server lives, not where Snipe-IT lives.

**Comment by snipe** [comment]
If you do a forgotten password request after logging out, does that mail come through?

**Comment by BaronVIP** [comment]
> 如果您在注销后忘记了密码请求，那邮件是否会通过？

I am running Exchange 2016 and found that asstes users did not send emails on my mail server,After logging out, click "forget password" and enter the email address. Click "send" and it will be successful

**Comment by snipe** [comment]
> found that asstes users did not send emails on my mail server

I don't really know what this means - can you clarify?

**Comment by BaronVIP** [comment]
> > 发现asstes用户没有在我的邮件服务器上发送电子邮件
> 
> 我真的不知道这意味着什么 - 你能澄清一下吗？

Click the "forget password" email prompt to send successfully, but still did not receive

**Comment by snipe** [comment]
Shouldn't `MAIL_DRIVER=mail` be `MAIL_DRIVER=smtp`?

Also as you are using port 587 (MSA) you might wish to switch to port 465 (smtps) in your application to test that. Because MSA should accept email after authentication (e.g. after SMTP AUTH).

Remember to run `php artisan config:clear` after making changes to your .env

**Comment by BaronVIP** [comment]
> 不`MAIL_DRIVER=mail`应该`MAIL_DRIVER=smtp`？
> 
> 此外，当您使用端口587（MSA）时，您可能希望切换到应用程序中的端口465（smtps）以进行测试。因为MSA应该在验证后接受电子邮件（例如在SMTP AUTH之后）。
> 
> 记得`php artisan config:clear`在更改.env后运行

Changed to SMTP mail test failed

**Comment by snipe** [comment]
I'm out of ideas then, sorry.

**Comment by BaronVIP** [comment]
> 那时我没有想法，抱歉。

Thank you very much. Thank you for your help

**Comment by BaronVIP** [comment]
> 在Linux系统上通常是这样`/var/log/maillog`。在Solaris上它是`/var/adm/maillog`。在Debian / Ubuntu上`/var/log/mail.log`，它取决于邮件服务器所在服务器的操作系统，而不是Snipe-IT所在的位置。
In the Linux struggles   
maillog  :fatal: open /etc/postfix/main.cf: Permission denied

**Comment by snipe** [comment]
@BaronVIP if you're running Exchange, you're not running Linux

**Comment by BaronVIP** [comment]
> @BaronVIP如果您正在运行Exchange，则不会将 Linux作为邮件服务器运行

I found that I had received one email that was due, none of the latter, and none of the test emails were inbound

**Comment by BaronVIP** [comment]
fatal: open /etc/postfix/main.cf: Permission denied

**Comment by EarlRamirez** [comment]
@BaronVIP are you using exchange as your relay? I saw that you are running postfix on CentOS, which log did you see that _Permission denied_ did you enable the SELinux boolean for mail?

**Comment by BaronVIP** [comment]
Why would you prompt an invalid user when you've already read the user through ldap
![1](https://user-images.githubusercontent.com/48519932/54808035-f2f03500-4cb9-11e9-85e8-7504549e99f8.png)
![2](https://user-images.githubusercontent.com/48519932/54808037-f4b9f880-4cb9-11e9-893e-9238b6ec2d06.png)
![3](https://user-images.githubusercontent.com/48519932/54808042-f683bc00-4cb9-11e9-97ac-4b0322203ce2.png)
