### ISSUE TITLE
"Alerts are disabled in the settings. No mail will be sent."

### ISSUE THREAD

**Issue by mattgann** [snipe/snipe-it#6820]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I ran the commands manually (outside of cron)
I also got 
"Alerts are disabled in the settings. No mail will be sent."
I do have alerts enabled checked
and I do have email set

I do not get the message and I do receive email when I use
snipeit:backup
snipeit:expected-checkin

**To Reproduce**
snipe-it:inventory-alerts

**Expected behavior**
send alerts to specified email

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.13
 - server 2016
 - Web Server: [ IIS]
 - PHP Version 7.2.15

similar to #2040

**Comment by snipe** [comment]
I'm not able to reproduce this anywhere.

<img width="599" alt="Screen Shot 2019-03-13 at 6 55 40 PM" src="https://user-images.githubusercontent.com/197404/54325902-af167500-45c1-11e9-8106-9aa35d7c5d5d.png">
<img width="605" alt="Screen Shot 2019-03-13 at 6 55 50 PM" src="https://user-images.githubusercontent.com/197404/54325903-afaf0b80-45c1-11e9-9bf4-106a0ae4511a.png">

Can you show me your Alerts Settings page?

**Comment by mattgann** [comment]
![Capture](https://user-images.githubusercontent.com/19474739/54363975-45ca4c80-4629-11e9-87c1-fd9132b38fd8.PNG)

**Comment by mattgann** [comment]
I rebuilt the server, it was a new instance. 
Works now.
I do have a question
when the alert email comes, there is a link back to the item. It is going to localhost and therefore does not open correctly from the email. So I missed a step somewhere. Can you tell me where the generated emails are pulling the url"server name"

**Comment by EarlRamirez** [comment]
@mattgann check the APP_URL in .env.

**Comment by mattgann** [comment]
I did make sure the APP_URL was set
It was still NULL but
when I put in the server address the emails still linked to locahost
