### ISSUE TITLE
Menu Collapsing Issue

### ISSUE THREAD

**Issue by sha-fuq** [snipe/snipe-it#6825]
One of the menus (Settings) collapses when one of its sub-menus is clicked. This doesn't happen with  the Reports or Assets menus. I believe the necessary JS change was forgotten for the Settings menu and needs to be fixed.

To reproduce:

1. Login to the online snipe-it demo site.

2. Click the button at the top left corner (the 3 horizontal lines) for the left panel menu bar to show the menu names (not just the icons).

3. Click on the left menu named "Settings" > its sub-menus appear.

4. Under Settings click any one of its sub-menus (for example Custom Fields).

5. Once "Custom Fields" is clicked the top menu named "Settings" collapses. Meaning it STOPS displaying the sub-menus underneath it (Custom Fields, Status Labels, Asset Models, Categories and so on..).

6. If you try it on one of the sub-menus for "Assets" or "Reports" this behaviour is different. There the chosen menu keeps showing its sub-menus (does not collapse).

7. The Settings menu should act the same as Assets or Reports. Its annoying to have to expand it every time to change between its sub-menus.

All of this was tested on Windows , Linux and Mac with different browsers.

**Comment by ShamikhI** [comment]
Settings menu still collapse upon clicking any of the submenus under setting, it would be nice that if it behaves same like Assets and Reports.
Version: v5.1.2 build 5847
