### ISSUE TITLE
Import Errors   Asset "": The status id field is required.  

### ISSUE THREAD

**Issue by skywallger** [snipe/snipe-it#6827]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**
1 import Asset.
2 Click import
3. Error state  Asset "": The status id field is required.
4. CSV file have field  status    value int = 6

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT  v4.6.13 
 - OS:  Ubuntu
 - Web Server: Apache2
 - PHP 7

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser [chrome,]

**Error Messages**

Item | Errors

Import CSV
-- | --
    | Asset "": The status id field is required.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by EarlRamirez** [comment]
@skywallger do you have the status in your CSV, this is a required field; therefore, you need to include it.

**Comment by skywallger** [comment]
Hi sorry , I don't update .
Now  issue  on current . My CSV have field  status . But  process import error  is "  _Asset "Servername": The status id field is required._ " every row . I don't understand. It can't import .
