### ISSUE TITLE
D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory. Bitnami NGINX help.

### ISSUE THREAD

**Issue by x3inspire** [snipe/snipe-it#6830]
Hi, i'm using Bitnami from AWS.  The problem now only i got an error "D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory"

This is my bitnami.conf:

>     # HTTP server
> 
>     server {
>         listen       80;
>         server_name  localhost;
> 
>         include "/opt/bitnami/nginx/conf/bitnami/phpfastcgi.conf";
> 
>         include "/opt/bitnami/nginx/conf/bitnami/bitnami-apps-prefix.conf";
>     }
> 
>     # HTTPS server
> 
>     server {
>        listen       443 ssl;
>        server_name  localhost;
> 
>        ssl_certificate      server.crt;
>        ssl_certificate_key  server.key;
> 
>        ssl_session_cache    shared:SSL:1m;
>        ssl_session_timeout  5m;
> 
>        ssl_ciphers  HIGH:!aNULL:!MD5;
>        ssl_prefer_server_ciphers  on;
> 
>        include "/opt/bitnami/nginx/conf/bitnami/phpfastcgi.conf";
> 
>        include "/opt/bitnami/nginx/conf/bitnami/bitnami-apps-prefix.conf";
>     }
> 
> 
>     include "/opt/bitnami/nginx/conf/bitnami/bitnami-apps-vhosts.conf";

How to change the document root to public, where i need to change?

Thanks.

**Comment by x3inspire** [comment]
Ok an update, after i added this full code now i got error 403 Forbidden.

> 	root "/opt/bitnami/nginx/html/public";

    # HTTP server

    server {

        listen       80;
        server_name  localhost;

        include "/opt/bitnami/nginx/conf/bitnami/phpfastcgi.conf";

        include "/opt/bitnami/nginx/conf/bitnami/bitnami-apps-prefix.conf";
    }

    # HTTPS server

    server {
       listen       443 ssl;
       server_name  localhost;

       ssl_certificate      server.crt;
       ssl_certificate_key  server.key;

       ssl_session_cache    shared:SSL:1m;
       ssl_session_timeout  5m;

       ssl_ciphers  HIGH:!aNULL:!MD5;
       ssl_prefer_server_ciphers  on;

       include "/opt/bitnami/nginx/conf/bitnami/phpfastcgi.conf";

       include "/opt/bitnami/nginx/conf/bitnami/bitnami-apps-prefix.conf";
    }


    include "/opt/bitnami/nginx/conf/bitnami/bitnami-apps-vhosts.conf";


Any idea what is my mistake?

**Comment by EarlRamirez** [comment]
@x3inspire, what are you seeing in the server (Nginx) error logs?

**Comment by x3inspire** [comment]
> @x3inspire, what are you seeing in the server (Nginx) error logs?

Hi, here is error log.

> 2019/03/19 12:45:10 [error] 24552#0: *51 "/opt/bitnami/nginx/html/public/public/index.html" is not found (2: No such file or directory), client: 1x.xxx.xxx.xx, server: localhost, request: "GET /public/ HTTP/1.1", host: "aset.mydomainname.com"
2019/03/19 12:45:12 [error] 24552#0: *51 "/opt/bitnami/nginx/html/public/public/index.html" is not found (2: No such file or directory), client: 1x.xxx.xxx.xx, server: localhost, request: "GET /public/ HTTP/1.1", host: "aset.mydomainname.com"
2019/03/19 12:46:07 [error] 27666#0: *1 "/opt/bitnami/nginx/html/public/public/index.html" is not found (2: No such file or directory), client: 1x.xxx.xxx.xx, server: localhost, request: "GET /public/ HTTP/1.1", host: "aset.mydomainname.com"
2019/03/19 12:46:08 [error] 27666#0: *1 "/opt/bitnami/nginx/html/public/public/index.html" is not found (2: No such file or directory), client: 1x.xxx.xxx.xx, server: localhost, request: "GET /public/ HTTP/1.1", host: "aset.mydomainname.com"
2019/03/19 12:46:08 [error] 27666#0: *1 "/opt/bitnami/nginx/html/public/public/index.html" is not found (2: No such file or directory), client: 1x.xxx.xxx.xx, server: localhost, request: "GET /public/ HTTP/1.1", host: "aset.mydomainname.com"
2019/03/19 12:46:11 [error] 27666#0: *1 directory index of "/opt/bitnami/nginx/html/public/" is forbidden, client: 1x.xxx.xxx.xx, server: localhost, request: "GET / HTTP/1.1", host: "aset.mydomainname.com"
2019/03/19 12:46:12 [error] 27666#0: *1 directory index of "/opt/bitnami/nginx/html/public/" is forbidden, client: 1x.xxx.xxx.xx, server: localhost, request: "GET / HTTP/1.1", host: "aset.mydomainname.com"
2019/03/19 12:46:12 [error] 27666#0: *2 directory index of "/opt/bitnami/nginx/html/public/" is forbidden, client: 1x.xxx.xxx.xx, server: localhost, request: "GET / HTTP/1.1", host: "aset.mydomainname.com"

![Capture](https://user-images.githubusercontent.com/4635825/54607176-b2f63b80-4a88-11e9-9ab9-86275a67cf7c.PNG)
Public folder already set to 755, set to 777 also still same.  Do i need to change the group and owner from root to bitnami?

**Comment by ktk010** [comment]
sudo chmod -R 755 public/uploads

**Comment by ktk010** [comment]
> sudo chmod -R 755 public/uploads



-

**Comment by x3inspire** [comment]
> > sudo chmod -R 755 public/uploads

Still same.

Nginx error log

> 2019/03/20 00:06:34 [error] 27667#0: *19 directory index of "/opt/bitnami/nginx/html/public/" is forbidden, client: 189.98.238.119, server: localhost, request: "GET / HTTP/1.1", host: "1x.xxx.xxx.xxx:80"
2019/03/20 00:16:02 [error] 27666#0: *30 directory index of "/opt/bitnami/nginx/html/public/" is forbidden, client: 175.143.93.218, server: localhost, request: "GET / HTTP/1.1", host: "aset.mydomain.com"
2019/03/20 00:16:03 [error] 27666#0: *30 directory index of "/opt/bitnami/nginx/html/public/" is forbidden, client: 175.143.93.218, server: localhost, request: "GET / HTTP/1.1", host: "aset.mydomain.com"
2019/03/20 00:16:03 [error] 27666#0: *30 directory index of "/opt/bitnami/nginx/html/public/" is forbidden, client: 175.143.93.218, server: localhost, request: "GET / HTTP/1.1", host: "aset.mydomain.com"

![Capture](https://user-images.githubusercontent.com/4635825/54650288-bc16f500-4ae8-11e9-92a4-eda77ffaa63c.PNG)

**Comment by EarlRamirez** [comment]
Your Web server is nginx and it doesn't own the directory, make nginx the owner and if it a go and see.

**Comment by x3inspire** [comment]
> Your Web server is nginx and it doesn't own the directory, make nginx the owner and if it a go and see.

Hi, this is my full folder permission.

![Capture](https://user-images.githubusercontent.com/4635825/54693594-df31bb00-4b61-11e9-99ca-19cabfbde357.PNG)
![Capture1](https://user-images.githubusercontent.com/4635825/54693596-dfca5180-4b61-11e9-81bc-19cea41650e0.PNG)

Which file and folder should change the owner to nginx?

**Comment by ktk010** [comment]
`sudo chmod -R 755 /var/www/nginx-default/`

**Comment by EarlRamirez** [comment]
@x3inspire, it would be /opt/bitnami/nginx/html.

> 019/03/19 12:45:10 [error] 24552#0: *51 "/opt/bitnami/nginx/html/**public/public/**index.html" is not found (2: No such file or directory), client: 1x.xxx.xxx.xx, server: localhost, request: "GET /public/ HTTP/1.1", host: "aset.mydomainname.com"

This is off, why is Nginx looking for two public folders?

**Comment by x3inspire** [comment]
> @x3inspire, it would be /opt/bitnami/nginx/html.
> 
> > 019/03/19 12:45:10 [error] 24552#0: *51 "/opt/bitnami/nginx/html/**public/public/**index.html" is not found (2: No such file or directory), client: 1x.xxx.xxx.xx, server: localhost, request: "GET /public/ HTTP/1.1", host: "aset.mydomainname.com"
> 
> This is off, why is Nginx looking for two public folders?

When i set this configuration ill get error like this:
`root "/opt/bitnami/nginx/html";`
Error:
> D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory.
Nginx error:
> 2019/03/21 01:02:38 [error] 21941#0: *1 open() "/opt/bitnami/nginx/html/favicon.ico" failed (2: No such file or directory), client: 1xx.xxx.xx.218, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "aset.felcraperak.com.my", referrer: "http://aset.mydomain.com/"

2nd configuration:
`"/opt/bitnami/nginx/html/public";`
Error:
> 403 Forbidden
Nginx error:
> 2019/03/21 01:00:30 [error] 21501#0: *1 directory index of "/opt/bitnami/nginx/html/public/" is forbidden, client: 1xx.xxx.xxx.218, server: localhost, request: "GET / HTTP/1.1", host: "aset.mydomain.com"

So actually which configuration should i use?
`root "/opt/bitnami/nginx/html/public";`
or
`root "/opt/bitnami/nginx/html";`
