### ISSUE TITLE
Google Authenticator

### ISSUE THREAD

**Issue by ktk010** [snipe/snipe-it#6834]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

I turned on the option google auth and then I got logged out. Now when I try to login It should show a code for me to scan but I dont see anything. So now I am basicly locked out of snipeit?
[
![a4aeba1d42c86fbae8bc37c8a889d366](https://user-images.githubusercontent.com/48214791/54605382-6d664e00-4a49-11e9-9df9-ea759c42b042.png)
](url)

**Comment by snipe** [comment]
Can your install talk to the outside world?

**Comment by snipe** [comment]
(Also in the future, please fill out the entire issue form, as it helps us better troubleshoot for you.)

**Comment by snipe** [comment]
Huh. https://stackoverflow.com/questions/55247825/google-charts-api-qr-code-returns-http-error-502

Well, shit.

**Comment by snipe** [comment]
I'll get a patch out for this today.

**Comment by ktk010** [comment]
> Can your install talk to the outside world?

No it cannot.




> (Also in the future, please fill out the entire issue form, as it helps us better troubleshoot for you.)

Yes I will. I had to catch a train so i did not have the time to fully fill it out. Sorry!

**Comment by ktk010** [comment]
> I'll get a patch out for this today.

Thank you very much!!

**Comment by snipe** [comment]
@ktk010 I've pushed this out to master. Can you upgrade and see if this resolves your issue? (You'll need to run composer install, but no db migrations are necessary if you were running ~4.6.13)

**Comment by ktk010** [comment]
@snipe I didn't need to update anything ;) Its fixed now. Thanks allot

**Comment by snipe** [comment]
@ktk010 

>  I didn't need to update anything ;) 

That's... honestly... weird. I wonder if Google re-enabled their API temporarily since it blew up lots of things. You should still probably update to master, as I imagine they won't keep those APIs up for long.

And honest, per #6402, the new way is a more secure way to handle this stuff anyway. :)

**Comment by ktk010** [comment]
> @ktk010
> 
> > I didn't need to update anything ;)
> 
> That's... honestly... weird. I wonder if Google re-enabled their API temporarily since it blew up lots of things. You should still probably update to master, as I imagine they won't keep those APIs up for long.
> 
> And honestly, per #6402, the new way is a more secure way to handle this stuff anyway. :)

Yes I will definitely update to master! Thanks again for fixing it so fast.

**Comment by snipe** [comment]
:) Thanks for reporting it! We try to stay on top of critical stuff like this :)
