### ISSUE TITLE
License UI - View User/Asset in Columns under Software Licenses

### ISSUE THREAD

**Issue by scottservers** [snipe/snipe-it#6836]
**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.8 - Build 3959
 - OS: Ubuntu (64-bit)
 - Web Server: Apache/httpd
 - PHP Version: 5.6.38

**Is your feature request related to a problem? Please describe.**
_We have a need to be able to look up or verify the owner of a license quickly and easily to check for errors or for troubleshooting._

**Describe the solution you'd like**
_It would be very useful to have a column on the Software Licenses management screen that would show who each license is checked out to._  

**Describe alternatives you've considered**
_We know there is a way to look up what licenses are under the specific user or asset, or to click into a license from the management screen and see who it is assigned to.  It can be cumbersome and time consuming and would be significantly easier to see them all at once._

**Additional context**

![Snipe-IT License Feature Request](https://user-images.githubusercontent.com/48735993/54644033-57b35180-4a66-11e9-8c0f-958290709efc.png)
_

**Comment by stbc** [comment]
+1

**Comment by snipe** [comment]
How exactly would we do that though? There might be one user with that license or 100,000.

**Comment by scottservers** [comment]
A valid point, I hadn't taken that into consideration.  Thanks for the response.

**Comment by scottservers** [comment]
Also, awesome software.  We really like everything about it so far, and I'm hoping we are able to adopt it company-wide.
