### ISSUE TITLE
Not able to checkout assets from CSV on import v4.6.14

### ISSUE THREAD

**Issue by Hsherif90** [snipe/snipe-it#6841]
#### Please confirm you have done the following before posting your bug report:

- [YES] I have enabled debug mode 
- [YES] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Unable to checkout assets on import v4.6.14.
Was able on v4.3.0 by adding username field.
I've attempted all variations of the CSV as per the import guide fro v4.6.14, however assets are not getting checked out.

**To Reproduce**
1. Go to 'Import'
2. Click on 'Select Import file'
3. Chose CSV file.
4. Assets created but not checked out to user.

**Expected behavior**
Assets are created successfully but unable to checkout to users on import.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.14
 - OS: Windows 7 x64
 - Web Server: WAMP 3.1.3 x86 (Apache 2.4.33_
 - PHP Version 7.1

**Desktop (please complete the following information):**
 - OS: Windows 7 x64
 - Browser Chrome
 - Version 72

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Not getting any errors.

**Additional context**
- Upgraded from v.4.3.0
- Installed manually and updated manually.
- Imported users after update successfully with Department (main reason of update)
- Not able to checkout assets on import to old or new users.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
As far as we're aware, the importer is not broken in current versions. If you can provide us with a sample CSV (with PII obfuscated), we might be able to troubleshoot this for you.

**Comment by Hsherif90** [comment]
Great I'll check what I can do and let you know! Thanks!

**Comment by Hsherif90** [comment]
Hey sorry for the late reply, I had an issue after the upgrade, I couldn't check out assets at all, figured I did something wrong.
Did the update properly and everything is working fine, but still nothing is getting checked out on creation.
[Import_Sample.xlsx](https://github.com/snipe/snipe-it/files/2991019/Import_Sample.xlsx)
All the users and assets already exists, I have another sample with Full Name and Email of the users in other columns, but still the same issue.

Thanks.

**Comment by Hsherif90** [comment]
Hey @snipe just reverted back to v4.3.0, import worked smoothly and assets checked out on import.
Pretty sure it's either the upgrading is causing the issue or v4.6.14 itself.

**Comment by snipe** [comment]
I don't think that's correct though, as all of our customers are using 4.6.14 or higher, and haven't been seeing these issues. What's in your app logs when you import in 4.6.14? It should give you verbose output there.

**Comment by Hsherif90** [comment]
Okay, I'm trying a fresh install on 4.6.14 anyway. I will keep you updated.

**Comment by Hsherif90** [comment]
Still same issue. Fresh install of 4.6.15, pulled from git. New database.
Created fictional users, imported fictional equipment. Result is....they are still not getting checked out.

The import is successful but still not checking out. Logs are still the same in storage/logs/laravel.log
Meaning importer did not trigger any errors. Or am I doing something wrong? 

Worth mentioning the new install is running on Ubuntu server 18.04 LTS.
Just wanted to try it since I'm doing a fresh install. I can't test it on demo (import disabled).

**Comment by Hsherif90** [comment]
Getting weird now. I've imported the sample data from the documentation and it checked them out successfully.
Full Name and Email are the difference?? I will try again.

**Comment by Hsherif90** [comment]
IT WORKED!!!! Full Name and Email did the trick. Is this in the documentation??

**Comment by NiklasNord** [comment]
Having this same issue with Version v4.7.4 - build 4107.
Isn't the whole idea that the username is the anchor for updating users information and checking out assets?
Seems strange to have to specify the users full name due to this. Is this something @snipe are looking in to?

Short explanation.
When importing users you have to separate first name and last name. This I do as a separate process.
When importing, and in a perfect world checking out assets to users, I only have access to the user name (in my cas the users e-mailaddress).
