### ISSUE TITLE
Email text

### ISSUE THREAD

**Issue by jmartins1** [snipe/snipe-it#6843]
It would be great if we had the ability to modify the email templates.

**Comment by GuessWild** [comment]
+1

**Comment by williamsant** [comment]
+1

**Comment by snipe** [comment]
I mean, you certainly can modify them, but I wouldn't really recommend it, since it makes upgrading more difficult.

What exactly are you looking to change? There's tabular database data in there, so I'm not sure what sort of modifications you're looking for.

**Comment by jmartins1** [comment]
Many platforms provide:

 

1.       Variables to pull in or exclude information from the email template. To customize what information is provided to the end-user.

2.       Allow the admin to customize the verbiage displayed in the email template.

3.       Allow the admin to customize the look and feel of the template, i.e. graphics, layout etc.

 

 

 

Thank you,

 

 

 

Jose Martins, M.Ed., MCSA, MCP

IT Administrator

**Comment by jmartins1** [comment]
Would still like to see this implemented. Please close if you are not considering this change at this time.
