### ISSUE TITLE
Error cannot display QR code on device

### ISSUE THREAD

**Issue by phucth309** [snipe/snipe-it#6844]
When I created a Assets and clicked on Serial to display asset information, the QR code of the Assets didn't show up. I need to configure them how to display.

![Error qr code](https://user-images.githubusercontent.com/48684087/54710356-13b17100-4b7a-11e9-8fe3-c950bf05c8bd.PNG)

 - Snipe-IT Version v4.6.13 build 3985 (g5f3147cf3)
 - OS: Server 2016
 - Web Server: IIS
 - PHP Version: 7.0.33

**Comment by snipe** [comment]
Please provide answers to the questions you deleted.

#### Confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)


**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database


![enlkq1k](https://user-images.githubusercontent.com/197404/31936238-da7c20cc-b865-11e7-8706-4cf76a7ec461.gif)
