### ISSUE TITLE
Alerts not being sent for overdue assets.

### ISSUE THREAD

**Issue by justin222221** [snipe/snipe-it#6845]
#### Expected Behavior (or desired behavior if a feature request)

I was hoping to receive email alerts, as well as a notification in the GUI when assets are not returned by their Expected Checkin Date.

-----

#### Actual Behavior

No alerts are sent, received or displayed.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
Yes
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
Yes

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Yes
- Version of Snipe-IT you're running
Version 4.6.14 - build 4006.
- Version of PHP you're running
Php version 7.2
- Version of MySQL/MariaDB you're running
10.1.38-MariaDB
- What OS and web server you're running Snipe-IT on
Ubuntu Server 18.04 + Apache2.
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
No.
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Hardware page, for assets.
- If a stacktrace is provided in the error, include that too.
N/A
- Any errors that appear in your browser's error console.
None.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Not reproducible. 
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
No, only through the web gui.
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Have you set up the cron job to trigger them? https://snipe-it.readme.io/docs/configuring-alerts-backups

**Comment by justin222221** [comment]
> Have you set up the cron job to trigger them? https://snipe-it.readme.io/docs/configuring-alerts-backups
> 
> > <img alt="" width="48" src="/favicon.ico">**[Configuring Alerts & Backups](https://snipe-it.readme.io/docs/configuring-alerts-backups)**Starting from Snipe-IT v3.0, all automated tasks are handled via the scheduler. To set a cron job to run every minute to ping the scheduler:  The scheduler already knows how often it should trigger the individual tasks, because of this code in the Console Kernel:  So basically, the scheduler will fi...

My apologies, I missed this step. I have now configured it and it appears to be working.

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
