### ISSUE TITLE
Class 'PragmaRX\Google2FA\Vendor\Laravel\ServiceProvider' not found in Application.php line 683

### ISSUE THREAD

**Issue by sjelle** [snipe/snipe-it#6846]
#### Expected Behavior (or desired behavior if a feature request)

Hello,
Been upgrading Snipe the same way for a very long time (using git pull) - never had any issue at all.

Actually running v4.6.13.
Normal procedure I am following : 

git pull
php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan migrate
php artisan config;clear
php artisan config:cache
php artisan cache;clear
phg artisan view:clear

Never had any issues at all.

Now after php composer.phar install --no-dev --prefer-source and dump-autoload, I run php artisan migrate as usual. An error follows : 
In Application.php line 683:
Class 'PragmaRX\Google2FA\Vendor\Laravel\ServiceProvider' not found

Doing php artisan config;cache or config;clear returns the same error.

Note : snipe is still running without any issues. 

Any suggestions or help is much appreciated.

Thanks !

-----

#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  **Upgrade**
- Version of Snipe-IT you're running : **Version v4.6.13 - build 3985 (master)**
- Version of PHP you're running : **7.1.27**
- Version of MySQL/MariaDB you're running : **10.0.38**
- What OS and web server you're running Snipe-IT on : CentOS 6.10
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) : **docker**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by sokeada** [comment]
from your snipeit project root directory, install google2fa package.
~$ composer require pragmarx/google2fa

**Comment by snipe** [comment]
@sokeada - please do not suggest that people edit their composer files. 

Running composer install should already install that vendor library.

If it isn’t, that’s a different issue, however folks should not be modifying their composer file.

**Comment by snipe** [comment]
As you can see, the library is included already:
https://github.com/snipe/snipe-it/blob/master/composer.json#L31

@sjelle try deleting your entire vendor directory and running `composer install`

**Comment by sokeada** [comment]
> @sokeada - please do not suggest that people edit their composer files.
> 
> Running composer install should already install that vendor library.
> 
> If it isn’t, that’s a different issue, however folks should not be modifying their composer file.

Oh sorry, thanks for the advise.

**Comment by sjelle** [comment]
> As you can see, the library is included already:
> https://github.com/snipe/snipe-it/blob/master/composer.json#L31
> 
> @sjelle try deleting your entire vendor directory and running `composer install`
> 
> > <img alt="" width="48" src="https://avatars2.githubusercontent.com/u/197404?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[snipe/snipe-it](https://github.com/snipe/snipe-it)**A free open source IT asset/license management system - snipe/snipe-it

Hi Alison,
Unfortunately that didn't work. New vendor library was created after removing and reinstalling but same error keeps popping up.

Any other suggestions ?

**Comment by veen1981** [comment]
Good morning. I also just attempted to upgrade from 4.5.0 to the current stable using the same method and I am receiving the same error as @sjelle 

git stash
git pull
php composer.phar install --no-dev --prefer-source
php composer.phar dump-autoload
php artisan migrate

`In Application.php line 683:`
    `Class 'PragmaRX\Google2FA\Vendor\Laravel\ServiceProvider' not found`

I also tried removing the vendors unsuccessfully.

Thanks!

Jeff

**Comment by samotelf** [comment]
Hello.
I also have this same error when trying to update to the latest version from  v4.6.13 - build 3985.
Any ideas?

**Comment by Raj22223** [comment]
I also facing the same error when trying to update from v4.6.13 - build 3985 to v4.6.15.

In Application.php line 683:
Class 'PragmaRX\Google2FA\Vendor\Laravel\ServiceProvider' not found

Kindly advise the solution, I tried deleting entire vendor directory and running composer install still same error.

**Comment by JoatWiPete** [comment]
I had the same issue and it went away. I'm not positive what I did, but I think the issue was I was missing dependencies somehow.
When you run php upgrade.php, does it give any errors in the middle about dependencies missing?

**Comment by veen1981** [comment]
That worked for me! After running php upgrade.php my application updated.
Cheers!

**Comment by sjelle** [comment]
> I had the same issue and it went away. I'm not positive what I did, but I think the issue was I was missing some modules somehow.
> When you run php upgrade.php, does it give any errors in the middle about modules missing?

Doesn't work for me - error pops up
PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpwuid() in /var/www/html/snipeit/upgrade.php:7
Stack trace:
#0 {main}
  thrown in /var/www/html/snipeit/upgrade.php on line 7

So I'm kinda stuck here
@snipe can you point us in the right direction please ?

**Comment by samotelf** [comment]
@sjelle try:

yum install php-posix
service httpd restart

**Comment by samotelf** [comment]
Hello @snipe as far as I understand, people say that the issue go away by running php upgrade.php, however, I always updated snipe-it as @sjelle shows when opening this issue.
Won't the application be corrupted without doing php artisan migrate?

**Comment by snipe** [comment]
@samotelf upgraded.php just runs those commands for you. You can open it in a text editor and see for yourself. (You don't have to know a lot of PHP to read through it - it tells you what it's doing every step of the way.)

https://github.com/snipe/snipe-it/blob/25884a893e1f4ce1a7d66a366db726b5e42e976a/upgrade.php#L1-L166

**Comment by samotelf** [comment]
Hm. I'll try that :) and will give you a shout.

**Comment by samotelf** [comment]
@snipe.
god damn. 👎 .

PHP Fatal error:  Uncaught Error: Call to undefined function posix_getpwuid() in /var/www/html/snipeit/upgrade.php:7
Stack trace:
#0 {main}
  thrown in /var/www/html/snipeit/upgrade.php on line 7

Help please :(

**Comment by samotelf** [comment]
@snipe I've managed to go through wih it.
I am now at Version v4.6.15 - build 4011 (master) 

I've fixed the posix error with:
sudo yum -y install php71u-process

and then ran sudo -u apache php upgrade.php.

Is that  Class 'PragmaRX\Google2FALaravel\ServiceProvider' not found normal? Even though it is when "cleaning up old cached files"?
Do you think I'll have problems in the future?
Thank you so much.

--------------------------------------------------------
Step 4: Cleaning up old cached files:
--------------------------------------------------------

-- No bootstrap/cache/compiled.php, so nothing to delete.
-- Deleting bootstrap/cache/services.php. It it no longer used.
-- Deleting bootstrap/cache/config.php. It it no longer used.
--
In ProviderRepository.php line 208:

  Class 'PragmaRX\Google2FALaravel\ServiceProvider' not found


--
In ProviderRepository.php line 208:

  Class 'PragmaRX\Google2FALaravel\ServiceProvider' not found


--
In ProviderRepository.php line 208:

  Class 'PragmaRX\Google2FALaravel\ServiceProvider' not found


--
In ProviderRepository.php line 208:

  Class 'PragmaRX\Google2FALaravel\ServiceProvider' not found

[https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiS3___g6HhAhVDTxUIHYU_ASoQjRx6BAgBEAU&url=https%3A%2F%2Fwww.tumblr.com%2Ftagged%2Fjake%2B2&psig=AOvVaw1z-HR10rF0GkhMCo4wZNSn&ust=1553731746273683](url)

**Comment by snipe** [comment]
> Do you think I'll have problems in the future?

You shouldn't - we updated the library we're using for 2FA recently (since Google Image Charts shut down their API), which is why you'd be seeing that. Now that you've upgraded, you should be all set.
