### ISSUE TITLE
QR Code not showing 

### ISSUE THREAD

**Issue by vihangad** [snipe/snipe-it#6848]
![Screen Shot 2019-03-22 at 12 33 17 PM](https://user-images.githubusercontent.com/47201517/54806006-c37fff00-4c9e-11e9-8dbd-d6bfc51dc2cd.png)

plz help, qr code picture not show

**Comment by sjelle** [comment]
Hello,

Based on this limited information, I presume your APP_URL in .env does not match your real URL.

**Comment by vihangad** [comment]
Thank you.....
Now working

**Comment by EarlRamirez** [comment]
@vihangad complete the issue form and we will be able to provide more accurate assistance, for example, we don't know what OS you are running we need to understand the environment Snipe-IT is running in.

**Comment by sjelle** [comment]
I think this can be closed - he said it is working now...

**Comment by snipe** [comment]
@vihangad 

Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
