### ISSUE TITLE
Import bulk assets, users using CSV file or any other option. 

### ISSUE THREAD

**Issue by sreejoo** [snipe/snipe-it#685]
Hi,

please help me to upload bulk number of items like Assets, users, location etc. 

This is suggestion in the case of Laptop and Workstation better to add an column  "Configuration". It will be more effective while filter to get reports.

Thanks
Sreejoo

**Comment by sreejoo** [comment]
I got the the import option for users, But is it possible in the case of assets and accessories, it will be great..

**Comment by dbierspb** [comment]
This seems to already be planned for a later release:

https://github.com/snipe/snipe-it/issues/152

**Comment by thien154** [comment]
user  mysqlwork bench or phpmyadmin
sample file for using mysqkwork:
LOAD DATA LOCAL INFILE 'D:/user.csv' INTO TABLE snipeit_laravel.users FIELDS TERMINATED BY ',' ENCLOSED BY '"' LINES TERMINATED BY '\n';

1008	user@ishcmc.edu.vn	securepassword 	{"superuser":-1}	1	\N	\N	\N	\N	\N	Kim Dung	Nguyen	\N	\N	\N	\N	\N	\N	132	\N	\N	\N	\N	\N	adusername

**Comment by snipe** [comment]
That won't work, as the password is hashed via Sentry when new users are created.

**Comment by snipe** [comment]
(But there is already a user import anyway)

**Comment by thien154** [comment]
It just suuport 3fields no sample csv file

**Comment by thien154** [comment]
You can create one user manually then go to database to take hash paswword

**Comment by shahima** [comment]
hi snipe world recently i  installed  snipe-it application for license management can please help me how to load licenses into snipe-it and my license data in excel format

**Comment by dmeltzer** [comment]
https://snipe-it-manual.readme.io/docs/importing-licenses
