### ISSUE TITLE
Feature Request: QR Code for Consumables

### ISSUE THREAD

**Issue by williamsant** [snipe/snipe-it#6857]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.15
 - OS: CentOS

Would like to add a Standard QR code to the "consumable's page. 

It would help to have 1 standard QR code for each specific consumable, to be able to easily check in consumables on the go.

**Comment by williamsant** [comment]
This is till relevant, would love to have this featured.

Thanks!

**Comment by samuelT2** [comment]
Would love to have QR codes for Consumables!
