### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by duath** [snipe/snipe-it#6873]
#### Please confirm you have done the following before posting your bug report

- [yes ] I have enabled debug mode 
- [ yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
500 Internal Server Error after upgrading to 4.6.15

**Screenshots**
![image](https://user-images.githubusercontent.com/6200447/55395559-6f9cd200-554a-11e9-8c99-5229bce4dde4.png)

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.15
 - OS: Windows Server 2016
 - Web Server:  IIS
 - PHP Version 7.2.12

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser all browsers

**Error Messages**
[2019-04-02 10:21:48] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'PragmaRX\Google2FALaravel\ServiceProvider' not found in C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php:208
Stack trace:
#0 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php(144): Illuminate\Foundation\ProviderRepository->createProvider('PragmaRX\\Google...')
#1 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\ProviderRepository.php(61): Illuminate\Foundation\ProviderRepository->compileManifest(Array)
#2 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(549): Illuminate\Foundation\ProviderRepository->load(Array)
#3 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Bootstrap\RegisterProviders.php(17): Illuminate\Foundation\Application->registerConfiguredProviders()
#4 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(208): Illuminate\Foundation\Bootstrap\RegisterProviders->bootstrap(Object(Illuminate\Foundation\Application))
#5 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(267): Illuminate\Foundation\Application->bootstrapWith(Array)
#6 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(114): Illuminate\Foundation\Console\Kernel->bootstrap()
#7 C:\inetpub\wwwroot\snipeit\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 {main}  

**Additional context**

It was an upgrade using php upgrade.php
tried updating composer, deleting vendor folder and running  composer install, same issue

**Comment by duath** [comment]
[03-Apr-2019 13:51:12 Asia/Muscat] PHP Fatal error:  Uncaught Error: Class 'Log' not found in C:\inetpub\wwwroot\snipeit\app\Exceptions\Handler.php:39
Stack trace:
#0 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(314): App\Exceptions\Handler->report(Object(Dotenv\Exception\InvalidFileException))
#1 C:\inetpub\wwwroot\snipeit\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(118): Illuminate\Foundation\Http\Kernel->reportException(Object(Dotenv\Exception\InvalidFileException))
#2 C:\inetpub\wwwroot\snipeit\public\index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#3 {main}
  thrown in C:\inetpub\wwwroot\snipeit\app\Exceptions\Handler.php on line 39

**Comment by krazykenny** [comment]
Hi there. I experienced the same thing after upgrading.
I just had to roll back to the previous version to get it working again.

**Comment by krazykenny** [comment]
just an update.
performed a clean install using the github clone method and copying over files manually.
that got it working for me.

**Comment by duath** [comment]
> 
> 
> Hi there. I experienced the same thing after upgrading.
> I just had to roll back to the previous version to get it working again.

i also had to roll back, i will try to copying over the files manually

**Comment by PetzJohannes** [comment]
I think there are some php extensions missing.
