### ISSUE TITLE
Cannot use Log as Log because the name is already in use

### ISSUE THREAD

**Issue by terwey** [snipe/snipe-it#6874]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Duplicate `Log` namespace in the `LoginController.php`

**To Reproduce**
1. Checkout latest Docker container (v5.0.0-beta2)
2. Load login page
3. Error 500 appears
4. See error in `tail -f storage/logs/laravel.log`

**Expected behavior**
User can login

**Server (please complete the following information):**
Docker container from snipe-it directly

**Error Messages**
```
production.ERROR: Cannot use Log as Log because the name is already in use {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 64): Cannot use Log as Log because the name is already in use at /var/www/html/app/Http/Controllers/Auth/LoginController.php:18)
```

*Resolution*
Simply remove line 18.

**Comment by PetzJohannes** [comment]
This is already fixed in the develop branch.
https://github.com/snipe/snipe-it/commit/109a29b5fc2ddcbf977dae524218e760d5ffd44c#diff-7c891627c8bea7abd474ebe4712cee5f
