### ISSUE TITLE
No environment variable or api option to configure ldap

### ISSUE THREAD

**Issue by drduker** [snipe/snipe-it#6878]
per this documentation for api:  https://snipe-it.readme.io/v4.0/reference#usersid-1
and the env variables that can be set here: https://snipe-it.readme.io/docs/configuration

There is no way to automate the ldap server configuration.  I can do an ldap sync with artisan, but nothing else.

Is there some special undocumented way to configure an ldap server or is manual entry required for this?

Thanks

**Comment by andrefecto** [comment]
You've gone through the LDAP settings in the admin panel? https://snipe-it.readme.io/docs/ldap-sync-login 

What specifically are you trying to automate? The actual LDAP Sync? (nightly, weekly, monthly, etc.) Or are you trying to deploy Snipe-IT in different environments with different LDAP settings each time?

**Comment by drduker** [comment]
The whole purpose of having an api option is to automate this how I want.
There needs to be an api to configure ldap without doing manual steps
configuring it after the server is installed.  This is still relevant if
you don't have ldap options to configure everything that pertains to ldap
configuration.

Thanks,
Luke
