### ISSUE TITLE
Bug in Asset Acceptance, asset name missing

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#688]
When asset's are checked out that have a confirm asset delivery notification the item name is missing.

This may be because we don't assign a name to assets, would it be possible for it to fall back to maybe the make/model/asset id when name is null?

![image](https://cloud.githubusercontent.com/assets/10247644/6809932/f5fd9440-d233-11e4-8bcf-1a805d552d86.png)

**Comment by kobie-chasehansen** [comment]
here is how that asset is setup

![image](https://cloud.githubusercontent.com/assets/10247644/6809949/23c82ffc-d234-11e4-8bca-94404907ec8f.png)

**Comment by kobie-chasehansen** [comment]
Actually may be a bigger bug, i'm not even sure we had confirm asset delivery turned on...

![image](https://cloud.githubusercontent.com/assets/10247644/6809990/72087d84-d234-11e4-8c98-fa9c92166684.png)

**Comment by snipe** [comment]
Yeah, the name isn't showing because you didn't give it one. Can you confirm the bigger bug you're saying is possibly a thing. This was pretty well tested, but if you can confirm, we'll fix it.

**Comment by kobie-chasehansen** [comment]
Will test and try to confirm.

Is there a way to fall back to listing the model or asset tag if no name is assigned?

**Comment by snipe** [comment]
We can, but asset tag won't mean anything to the average user, which is why we didn't fall back to it before. Model may be smarter.

**Comment by kobie-chasehansen** [comment]
I agree, i like the model better as well.
