### ISSUE TITLE
Feature request: Attachment for Maintenances

### ISSUE THREAD

**Issue by ffuentes** [snipe/snipe-it#6881]
#### Expected Behavior (or desired behavior if a feature request)
Allow upload files to Maintenances.

#### Actual Behavior   

It's only possible to write notes.

Sometimes is useful to add external documents for  maintenances like reports, PDFs, images, logs, uzw.

**Comment by ajsy** [comment]
+1

**Comment by King-GO** [comment]
need this feature too
