### ISSUE TITLE
Checkout License Seat - Checkout to "Asset"

### ISSUE THREAD

**Issue by IVCH5264** [snipe/snipe-it#6882]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Can not type in the Asset name or Asset Number for the searching in the Checkout License seat to "Asset"

**To Reproduce**
1. Go to Checkout License Seat
2. Click on Checkout to Asset
3. Type in the Asset Number
4. The message is "The results could not be loaded" 

**Expected behavior**
Get the correct result when we type in the Asset Number.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version : 4.6.8 - build 3959 (master)
 - OS: CentOS 7
 - Web Server: Apache
 - PHP Version : 5.6.40

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 73.0.3683.86

**Comment by ajsy** [comment]
you are running older version of snipe-it, this bug resolved in v4.6.10
https://github.com/snipe/snipe-it/releases/tag/v4.6.10
