### ISSUE TITLE
Snipe doesn't allow "'" in email addresses

### ISSUE THREAD

**Issue by TheMysteriousX** [snipe/snipe-it#6883]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Hopefully a nice quick one to fix. We have a user, with a name like Firstname O'Lastname, with an email address of "firstname.o'lastname@company.uk". Firstname O'Lastname can't log into snipe though, because LDAP import won't import them because they have a symbol in their email address.

The LDAP sync process emits:
<img width="183" alt="Screenshot 2019-04-04 19 06 23" src="https://user-images.githubusercontent.com/590630/55578026-d9fd7000-570c-11e9-9a11-0edd101bf941.png">

**To Reproduce**
1. Add a user with an apostrophe in their email address to LDAP
2. Try an LDAP sync.
3. Observe the import error

**Expected behavior**
As ' is a valid character in an email address, it should be imported without error.

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.15
 - OS: RHEL 7.6
 - Web Server: Apache
 - PHP Version 7.2.14

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: All

**Error Messages**
"The email format is invalid."

Nothing in logs, even with APP_DEBUG set and threshold set to 'debug'.

**Additional context**
- Is this a fresh install or an upgrade?  **Upgrade**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Manual with Git upgrades**
- Indicate whether or not you've manually edited any data directly in the database **No database edits made.**

**Comment by snipe** [comment]
There's not really a whole lot we can do about that. That's the way the [PHP email filter validator](https://www.php.net/manual/en/filter.examples.validation.php) works on email addresses. The only way around that would be to write our own email validator, which is a road fraught with peril and has been for decades because of how loose the RFC is, and how badly email clients individually support the RFC. :(

**Comment by TheMysteriousX** [comment]
The validator you linked accepts it as valid, so maybe the behaviour has changed since it was implemented?

https://repl.it/repls/AptPeachpuffTechnologies

If the validation is done by a dependency I can go file an upstream bug, but I've not been able to find where the validation is called - the error string doesn't show up in a simple grep of the code.

**Comment by snipe** [comment]
It's possible they changed the behavior of the filter in php7.3

**Comment by TheMysteriousX** [comment]
I dug into this some more and I think I've got an explanation for the different behaviour we each see. I instrumented Laravel and came up with this:

```
filter_var: firstname.o&#039;lastname@company.uk is not valid
```

It looks like the address is encoded as html escape codes here:
  https://github.com/snipe/snipe-it/blob/master/app/Console/Commands/LdapSync.php#L196

If I remove the call to e() around the mail attribute it allows the user to be imported - I don't know if this comes with side effects though.

**Comment by adam-bishop** [comment]
Thanks for fixing this!
