### ISSUE TITLE
404 after access from nginx proxy server from Internet

### ISSUE THREAD

**Issue by vund1209** [snipe/snipe-it#6884]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
NGINX PROXY REVERSE leads to 404 not found
I'm running a domain with SSL enabled: https://mydomain.com
This directs to a nginx proxy reverse server with this config

 _location
 /snipeit {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		proxy_pass  http://mysnipeserverip;
       		proxy_set_header    X-Forwarded-Proto   $scheme;		
		proxy_read_timeout 6000;
	}_

1, I can access **http://mysnipeserver_local_ip** successfully and it led to login page.
2, I already set the env:
`APP_TRUSTED_PROXIES=nginx_reverse_local_ip`

I think that when I access **https://mydomain.com/snipeit** , I got content from **http://mysnipeserver_local_ip/snipeit** instead of **http://mysnipeserver_local_ip** then I get 404

**To Reproduce**
1. Go to 'https://mydomain.com/snipeit'
2. See error

**Expected behavior**
Get Snipe-It login interface at https://mydomain.com/snipeit

**Screenshots**
![image](https://user-images.githubusercontent.com/27663152/55620466-8a32ad80-57cd-11e9-918d-67b373616ab7.png)

**Server (please complete the following information):**
 - Snipe-IT Version : beta 5
 - OS: Ubuntu server 18.04
 - Web Server: Nginx
 - PHP Version : 7.2.15

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox Nightly
 - Version 68.0a1

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by vund1209** [comment]
Here is the nginx log from SnipeIt server
`192.168.11.6 - - [05/Apr/2019:17:14:26 +0700] "GET /snipeit HTTP/1.0"404 1150 "-""Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0" "-"
192.168.22.5 - - [05/Apr/2019:17:14:26 +0700] "GET /img/sad-panda.png HTTP/1.1"200 47027 "-""Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0" "-"
`

**Comment by andrefecto** [comment]
Have you checked out the reverse proxy section of the docs? https://snipe-it.readme.io/docs/reverse-proxies 

Also, the root folder for your site should actually be the "public" folder inside of the Snipe-IT files, as talked about here: https://snipe-it.readme.io/docs/linuxosx

**Comment by vund1209** [comment]
@andrefecto Hi, I already checked those documents.
I get SnipeIt working with local nginx setup (SnipeIT public folder as root) - http://mysnipeserver_local_ip/ - Login Page showed up when I connect
But the reverse proxy didn't serve it well with the url: https://mydomain.com/snipeit
Below is the nginx section to proxy_pass SnipeIT server
_location
/snipeit {
# First attempt to serve request as file, then
# as directory, then fall back to displaying a 404.
proxy_pass http://mysnipeserverip;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_read_timeout 6000;
}_

**Comment by kserradell** [comment]
Hello @andrefecto 

I'm having issues to display my snipeit behind an nginx proxy. Did you solve your issue? Would it be possible to see your nginx proxy configuration? Mine is:

```
location /inventory {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://my_server_local:port/;
        proxy_set_header Host $host;
        proxy_set_header Proxy "";
    }
```

What I'm doing wrong? Snipeit works like a charm when accessing directly `http://my_server_local:port`.

Thanks!

**Comment by andrefecto** [comment]
> 
> 
> Hello @andrefecto
> 
> I'm having issues to display my snipeit behind an nginx proxy. Did you solve your issue? Would it be possible to see your nginx proxy configuration? Mine is:
> 
> ```
> location /inventory {
>         proxy_set_header X-Forwarded-Host $host;
>         proxy_set_header X-Forwarded-Server $host;
>         proxy_set_header X-Forwarded-Proto $scheme;
>         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>         proxy_pass http://my_server_local:port/;
>         proxy_set_header Host $host;
>         proxy_set_header Proxy "";
>     }
> ```
> 
> What I'm doing wrong? Snipeit works like a charm when accessing directly `http://my_server_local:port`.
> 
> Thanks!

What does your root location block look like? It would be something like this:
```
location / {
  # stuff here
}
```

**Comment by kserradell** [comment]
Thanks for your answer @andrefecto. I'm not managing the proxy, so it's hard for me to get this information. I will work with the sysadmins to make it work.
