### ISSUE TITLE
login page error onFresh install

### ISSUE THREAD

**Issue by ryanp-javs** [snipe/snipe-it#6886]
#### Please confirm you have done the following before posting your bug report:

- [Yes ] I have enabled debug mode 
- [Yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
new install on clean server, pre-flight and setup complete, but unable to login.  log indicates

[2019-04-05 09:03:11] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Cannot use Log as Log because the name is already in use in C:\inetpub\SnipeIT\app\Http\Controllers\Auth\LoginController.php:18
Stack trace:
#0 {main}  
[2019-04-05 09:03:11] production.ERROR: Cannot use Log as Log because the name is already in use {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 64): Cannot use Log as Log because the name is already in use at C:\\inetpub\\SnipeIT\\app\\Http\\Controllers\\Auth\\LoginController.php:18)
[stacktrace]
#0 {main}
"} 

**To Reproduce**
1. Install new instance of 5.0.0-Beta-2, setup/configure. Complete pre-flight/setup, 
2. attempt to connect when not logged in

**Expected behavior**
A login page to be displayed

**Screenshots**
I can provide a screenshot if needed.

**Server (please complete the following information):**
 - Snipe-IT Version
5.0.0-Beta-2 
 - OS: [e.g. Ubuntu, CentOS]
Windows Server 2019 Datacenter
 - Web Server: [e.g. Apache, IIS]
IIS10
 - PHP Version 
7.2.17

**Desktop (please complete the following information):**
Any (tried both on-server, and win10 client)
any (tried IE and Chrome)
Latest

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Cannot use Log as Log because the name is already in use in C:\inetpub\SnipeIT\app\Http\Controllers\Auth\LoginController.php:18

- If a stacktrace is provided in the error, include that too.

Stack trace:
#0 {main}  
[2019-04-05 09:03:11] production.ERROR: Cannot use Log as Log because the name is already in use {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 64): Cannot use Log as Log because the name is already in use at C:\\inetpub\\SnipeIT\\app\\Http\\Controllers\\Auth\\LoginController.php:18)
[stacktrace]
#0 {main}
"} 

- Any errors that appear in your browser's error console.
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
it is not

- Include any additional information you can find in `storage/logs` and your webserver's logs.
above info is from the mentioned log

**Additional context**
- Is this a fresh install or an upgrade? 
fresh install

- What OS and web server you're running Snipe-IT on
Windows server 2019 Datacenter with IIS 10 in a VM
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual
- Include what you've done so far in the installation, and if you got any error messages along the way.
I have configured, run through pre-flight and setup. when first attempt resulted in this issue, I completely rebuilt the server , including fresh OS install.
- Indicate whether or not you've manually edited any data directly in the database
no manual edits of DB at all.

I have also tried installing 4.6 but was running into issues creating the DB so I elected to go with 5 as it proceeded further. Running MariaDB 10.3. I'm not a php developer, but this looks like an imports or namespace conflict.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
This is already fixed in the develop branch.
109a29b#diff-7c891627c8bea7abd474ebe4712cee5f
