### ISSUE TITLE
LDAP authentication without Bind Password

### ISSUE THREAD

**Issue by lblatlaswiki** [snipe/snipe-it#6888]
Is it possible to use LDAP authentication without providing (or knowing) the Bind Password?  

I want to use our institutional LDAP server, and we don't have access to that information.
I've installed many other applications that authenticate against LDAP without the application needing to provide the admin bind password, so I know it is possible.  Is this possible with snipe-it?

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
fresh
- Version of Snipe-IT you're running
v4.6.15 - build 4011
- Version of PHP you're running
PHP 7.1.27 (cli) (built: Mar  7 2019 12:14:02) ( NTS )
- Version of MySQL/MariaDB you're running
mariadb-5.5.60-1.el7_5.x86_64
- What OS and web server you're running Snipe-IT on
CentOS 7.6.1810,   apache 2.4.6
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
The "Test LDAP" button fails with this message: 
Your app key has changed! Could not decrypt LDAP password using your current app key, so LDAP authentication has been disabled. Login with a local account, update the LDAP password and re-enable it in Admin > Settings.
But this is nonsense.  This is a fresh install and the app key has definitely not changed.  
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
/admin/ldap
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
No manual edits.   This is a fresh install from install.sh

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by dominikborkowski** [comment]
I'll second the wish for anonymous LDAP bind feature for authentication. Vast majority of the software we use supports that mode of operation, and it would be great to have the same capability with SnipeIT.

Thanks!

**Comment by FelixHueftle** [comment]
I also would like to have anonymous LDAP bind feature for authentication.

**Comment by dominikborkowski** [comment]
Yes, this is still relevant.

**Comment by FelixHueftle** [comment]
Yeah, please review this and implement this - would be great!

**Comment by FelixHueftle** [comment]
Yeah, this is still relevant.
Please adress this issue seriously!

**Comment by txavier** [comment]
Is anyone going to look into this?

**Comment by jdanderson3** [comment]
Yes, this is still relevant.  I think it would be a very valuable feature.  Current LDAP authentication only serves as a convenience for managers running their own LDAP servers.  Many implementations would like to use institutional LDAP auth.

**Comment by diatzikis** [comment]
Yes I would also like to use LDAP just to validate users accounts and not have the admin password.

**Comment by Bhairava123** [comment]
Your app key has changed! Could not decrypt LDAP password using your current app key, so LDAP authentication has been disabled. Login with a local account, update the LDAP password and re-enable it in Admin > Settings.

**Comment by lmsmartins** [comment]
Yes, this is still relevant to me as well. As others mentioned in this issue, it's pretty common to use the anonymous LDAP bind in other systems. E.g. osTicket only requires the default domain, DNS servers, LDAP servers, and TLS option to set up the LDAP connection. Optionally, there are the LDAP bind options as well.

Is there any chance we could also display a different error message when trying to authenticate using anonymous LDAP bind? The following message may be misleading: "Your app key has changed! Could not decrypt LDAP password using your current app key, so LDAP authentication has been disabled. Login with a local account, update the LDAP password and re-enable it in Admin > Settings.".

![osticket_ldap_settings](https://user-images.githubusercontent.com/8367143/79255375-b7507c00-7e75-11ea-9305-ed45e880a740.png)
