### ISSUE TITLE
Importing assets creates duplicate asset model

### ISSUE THREAD

**Issue by Ranlar** [snipe/snipe-it#6889]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Duplicate asset models being created when importing assets

**To Reproduce**
Import .cvs with model that is already in the asset models.
then check asset model UI and see the duplicate model

**Expected behavior**
Should use the existing asset model that is already present.

**Screenshots**
![image](https://user-images.githubusercontent.com/48483838/55649787-8db43d80-57a9-11e9-959b-5f8b2ba4bd73.png)

**Server (please complete the following information):**
 - Snipe-IT Version - 4.2.0
 - PHP Version - 7.0.21

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 73.0.3683.86

**Comment by sreyemnayr** [comment]
Can confirm same in develop branch.

**Comment by snipe** [comment]
Can you provide a sample CSV that we can try to reproduce this with?

**Comment by sreyemnayr** [comment]
Actually it ended up being a thing with a model number having a weird character in it for us. We got it resolved.

Ryan

________________________________
