### ISSUE TITLE
Customer info for asset hire

### ISSUE THREAD

**Issue by danmcr** [snipe/snipe-it#6893]
Hi. Please excuse me if this is not the correct place to ask this as i cant find a forum for this app. 

In regards to checkout an asset, could you check it out to a barcode instead of a customer name. I ask this simply because we have a wordpress plugin for booking and rental of equipment but it has no check in or out features. It holds all the customer info and generates a barcode for the booking. I wanted to use this barcode to link the hire to the checkout of the asset. 

Thank you in advance for any reply and sorry again if its not the correct place to ask such a question. 

Daniel

**Comment by andrefecto** [comment]
You can checkout Assets to Users, Locations, and other Assets. See here: https://snipe-it.readme.io/docs/managing-assets

**Comment by snipe** [comment]
That's not really how our checkin/checkout/barcodes works. You can read more about it here: https://snipe-it.readme.io/docs/barcodes

The barcodes contain just the asset tag, and the QR codes contain a link to the asset page itself for quick reference.
