### ISSUE TITLE
User permission limiting

### ISSUE THREAD

**Issue by peter-madigan** [snipe/snipe-it#6895]
I think this borders between a bug and a feature request, but what I'm trying to do is this -- I want users to be able to modify their own user data (e.g. phone number, location, etc). However, if I grant users the ability to modify user data, they are also allowed to modify user permissions. This isn't necessarily a problem, but what I find is that users are able to modify all of their permissions, including elevating themselves to admin or superuser. It seems like a user's ability to grant/remove permissions should inherit from their own permissions.

For our specific use case, it would also be nice to allow users to modify their own data without granting them the ability to modify _all_ user data.

**Comment by snipe** [comment]
> I want users to be able to modify their own user data (e.g. phone number, location, etc). However, if I grant users the ability to modify user data, they are also allowed to modify user permissions.

Users can modify their own data by way of their profile (at `/account/profile`). You shouldn't have to grant them access to edit other users for this. (I don't think phone number is included in the list of fields they can edit in their profile, but we can add that.) All users who can login can change their own general info details.

**Comment by peter-madigan** [comment]
Maybe I'm missing something in the permissions, but for my test user account I can only modify the name, language, website, gravatar, and image:
![image](https://user-images.githubusercontent.com/18176192/56446078-684d2680-62b5-11e9-9be4-ed579dffe956.png)

I was hoping I could set things up so each user could modify everything in their user information:
email, company, employee number, title, etc.

**Comment by snipe** [comment]
Users cannot change those things, an in our opinion, shouldn't be able to. HR/IT/etc should be managing employee numbers, titles and companies, as they are not arbitrary fields. I could change my title to Grand Poobah, which would be cute, but not actually useful to an organization.

**Comment by peter-madigan** [comment]
OK I see. I guess my use case is a bit different.
I'm trying to use snipe to set up a lending library, so it doesn't really have a central management. I'll keep fiddling and see if I can come up with a sensible workflow.
