### ISSUE TITLE
Backup Failure - Exitcode 2

### ISSUE THREAD

**Issue by mrtinvan** [snipe/snipe-it#6897]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Generating backup fails with exitcode 2.

The dump process failed with exitcode 2 : Misuse of shell builtins : sh: 1: cannot create /var/www/snipeit/storage/laravel-backups/temp//snipeit.sql: Permission denied .

The directory does exist up to the /temp/ folder, and snipeit user does have read and write access. 

**To Reproduce**
1. Go to Settings
2. Click on Backups
3. Click Generate Backup

**Expected behavior**
A backup file should be generated

**Server (please complete the following information):**
 - Snipe-IT Version - v4.6.15 build 4011 (gd1e9fbfa2)
 - OS: Ubuntu Server 18.04
 - Web Server: Apache2
 - PHP Version: 7.2.15-0ubuntu0.18.04.2

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Browser Chrome 73 and Firefox

**Error Messages**
See above in Issue

**Additional context**
- Is this a fresh install or an upgrade? **Fresh**
- What OS and web server you're running Snipe-IT on **Ubuntu & Apache**
- What method you used to install Snipe-IT - **Install.sh**
- Include what you've done so far in the installation, and if you got any error messages along the way. **Added Assets, and changed the FQDN in both the .env and apache config. Did a artisan view and cache clear, as well as an apache restart **
- Indicate whether or not you've manually edited any data directly in the database - **NO**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by EarlRamirez** [comment]
You need to update your permissions on the storage directory

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)

**Comment by BW44b** [comment]
We are having this problem too, does anyone have a working fix for this?

**Comment by mrtinvan** [comment]
It only takes a permissions reset and folder creation.

Set your instance to be in debug mode, and find out which folders are
missing, and then set the permissions for that folder to match the parent
Snipe-IT folder.
