### ISSUE TITLE
Initial install script failing on db installation, tries to drop tables that don't exist

### ISSUE THREAD

**Issue by dstockto** [snipe/snipe-it#69]
On running 

php artisan app:install

I get the following error:

Migration table created successfully.
Migrated: 2012_12_06_225921_migration_cartalyst_sentry_install_users
Migrated: 2012_12_06_225929_migration_cartalyst_sentry_install_groups
Migrated: 2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot
Migrated: 2012_12_06_225988_migration_cartalyst_sentry_install_throttle

  [Exception]  
  SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'posts' (SQL: drop table `posts`) (Bindings: array ())            

In /app/database/migrations/2013_11_25_000345_drop_comments_posts_tables.php there are instructions to drop the 'posts' and 'comments' schema but neither exists and they will cause errors that stop the migration.

I don't know much about the migrations as far as if that file can just be removed and things will work, but commenting out the two drop instructions did allow it to complete successfully.

**Comment by ambarishrh** [comment]
I am getting the same error on my installation, but couldn't figure out how to fix it.

[root@snipeit snipeit]# php artisan db:seed


                                                                      
  [Illuminate\Database\QueryException]                                
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit  
  _www.assets' doesn't exist (SQL: truncate `assets`)                 
                                                                      


db:seed [--class[="..."]] [--database[="..."]]
