### ISSUE TITLE
Edit menu 

### ISSUE THREAD

**Issue by hocit001** [snipe/snipe-it#691]
How to edit menu snipe-IT?
Assets 
Deployed
Ready to Deploy
Pending 
Un-deployable
Archived
Requestable
List All
 
Asset Models
Asset Categories
Deleted
Accessories
Licenses
People
Repo

**Comment by snipe** [comment]
Edit how?

**Comment by hocit001** [comment]
EX:

Assets => Asset
Deployed=> Deplo
.....
Ready to Deploy
Pending 
Un-deployable
Archived
Requestable
List All

Asset Models
Asset Categories
Deleted
Accessories
Licenses
People
Repo

**Comment by snipe** [comment]
That text is kept in language files. What's the use case here?

**Comment by hocit001** [comment]
I want to translate it into another language. 
ex:
Vietnamese.....

**Comment by snipe** [comment]
We use CrowdIn to handle translations. You can translate to Vietnamese here: https://crowdin.com/project/snipe-it/vi

We'll add those to the Snpie-IT library files so that updates won't blow out your changes, and so that the community can benefit from the translations.

**Comment by hocit001** [comment]
Thanks.
