### ISSUE TITLE
The note must be a string (Error when checking in License from Asset)

### ISSUE THREAD

**Issue by ajsy** [snipe/snipe-it#6911]
- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I am getting this error message "The note must be a string" when checking in license from asset, I have to type anything in note or adding a white space in order to proceed.

**Screenshots**
![The note must be a string](https://user-images.githubusercontent.com/35658596/56154330-f3ca6d00-5fc0-11e9-8fd4-e341d336b0a9.jpg)

**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.13
 - OS: Ubuntu 18.04
 - Web Server: Apache
 - PHP Version: 7.2.10-0ubuntu0.18.04.1

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: chrome
 - Version: Latest

**Additional context**
- Is this a fresh install or an upgrade? Upgrade
- What method you used to install Snipe-IT? Git installation
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database? no

**Comment by afield1235** [comment]
I just ran into this also after upgrading to Version v4.6.15 - build 4011 (master). I can no longer check anything in or out without a mandatory comment?

**Comment by afield1235** [comment]
This issue has persisted through at least 3 different minor updates. v4.6.13, v4.6.14, v4.6.15. Can this be acknowledged please? It broke existing functionality that was working fine prior.

**Comment by afield1235** [comment]
thanks! <3

**Comment by ajsy** [comment]
confirmed thank you
