### ISSUE TITLE
Feature Request: Add General EULA to Print Asset List

### ISSUE THREAD

**Issue by AlfonsoQ** [snipe/snipe-it#6912]
**Server (please complete the following information):**
 - Snipe-IT Version Hosted User
 - OS: [e.g. Ubuntu, CentOS] Hosted User
 - Web Server: [e.g. Apache, IIS] Hosted User
 - PHP Version Hosted User

**Is your feature request related to a problem? Please describe.**
My company needs a signed paper when a user accepts a new IT asset.
Right now, I need to print my EULA, get signed by the user and in a separated page, the list of assets assigned to the user, from snipe.

**Describe the solution you'd like**
It would be useful to have the general EULA in the Asset List print form, in order to sign only one time.

**Describe alternatives you've considered**
There is already a Feature Request in order to get this document per checkout (#6851) but since is a digital signature, doesn't works for my company

**Additional context**

**Comment by rkthamizhan** [comment]
still we looking for the support to take the printout with EULA in the Asset List print form
Snipe-IT versionv6.0.14 build 9236 
PHP Version8.1.2-1ubuntu2.10
Software License[AGPL3](https://www.gnu.org/licenses/agpl-3.0.en.html)
Laravel Version8.83.27
