### ISSUE TITLE
When we click on asset list then getting error i.e. "Whoops, looks like something went wrong"

### ISSUE THREAD

**Issue by 123pal** [snipe/snipe-it#6913]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(When we click on asset list then getting error i.e. "Whoops, looks like something went wrong")

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
- Version of Snipe-IT you're running - Version v4.6.15 - build 4011
- Version of PHP you're running - 7.3.1
- Version of MySQL  you're running - 5.7.24
- What OS and web server you're running Snipe-IT on - OS- Windows 10 Prof. 64 bit, All browser
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual through wamp server
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - When we click on asset list then getting error i.e. "Whoops, looks like something went wrong"
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Asset page
- If a stacktrace is provided in the error, include that too. - no clue 
- Any errors that appear in your browser's error console. - nothing
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - 
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
> Include any additional information you can find in storage/logs and your webserver's logs.

Please complete the entire ticket form so we have the information we need to help you. We can't possibly know what's going on without a stack trace or error logs.

https://snipe-it.readme.io/docs/getting-help
https://snipe-it.readme.io/docs/whoops
