### ISSUE TITLE
Password Issue

### ISSUE THREAD

**Issue by painatas1** [snipe/snipe-it#6916]
#### Expected Behavior (or desired behavior if a feature request)

-----

#### Actual Behavior

When trying to insert the email and password for log in it fails even when the password was correct.
When trying to reset I get a server error 500 

-----

I took over a infra-estruture and here they have a Ubuntu CLI with SNIPE IT installed.
The problem is that when I use the credentials that they gave me it always fails and when i try to reset I get the Server error 500.

Is there any way for me to change the password on the server?

I really need some help and I would really appreciate it

Thank you all for your help!

**Comment by snipe** [comment]
> When trying to insert the email and password for log in it fails even when the password was correct.

Insert as in a database statement, or as in just trying to login normally? The login system works fine, but you can only login with your email address (versus username) if the email address is also the username.  We check logins with username+password not email+password.

> The problem is that when I use the credentials that they gave me it always fails and when i try to reset I get the Server error 500

That sounds like there is something else misconfigured on the server. We'd need to see the app log errors or a stack trace before we could know what that is. 

Additionally, in the future, please complete the entire Issue Template, so we have the information we need. 

https://snipe-it.readme.io/docs/getting-help

**Comment by painatas1** [comment]
> > When trying to insert the email and password for log in it fails even when the password was correct.
> 
> Insert as in a database statement, or as in just trying to login normally? The login system works fine, but you can only login with your email address (versus username) if the email address is also the username. We check logins with username+password not email+password.
> 
> > The problem is that when I use the credentials that they gave me it always fails and when i try to reset I get the Server error 500
> 
> That sounds like there is something else misconfigured on the server. We'd need to see the app log errors or a stack trace before we could know what that is.
> 
> Additionally, in the future, please complete the entire Issue Template, so we have the information we need.
> 
> https://snipe-it.readme.io/docs/getting-help
> 
> > <img alt="" width="48" src="/favicon.ico">**[Getting Help](https://snipe-it.readme.io/docs/getting-help)**If you're having trouble setting up Snipe-IT, don't worry!


Oh sorry.
I didn't complete the template because I don't know much about the Snipe IT that is installed...And linux is not my forte.

How can I get the logs?

**Comment by snipe** [comment]
> Now I've noticed that SNIPEIT is on version 1.2.8.

Holy moly... Yeah... you'll want to upgrade that. Because your version is so old, you'll need to complete the upgrade to v3 first, and then upgrade to v4.

https://snipe-it.readme.io/docs/upgrading-to-v3
https://snipe-it.readme.io/docs/upgrading-to-v4
