### ISSUE TITLE
custom fields

### ISSUE THREAD

**Issue by andreypetruk** [snipe/snipe-it#6917]
How i can see current version snipe-ip API have not option getting assets by some custom fields.
I believe this feature will be useful.

**Comment by snipe** [comment]
I don't understand what this questions means - can you please clarify?

**Comment by andreypetruk** [comment]
We have assets, assets include some custom-fields https://snipe-it.readme.io/docs/custom-fields.
We can get asset(s) by using API endpoint /hardware and QUERY PARAMS model_id, category_id or using search, etc.... But if need get asset by  custom-fields we can't do this. 
For example by https://your-server/api/v1/hardware?my-fields=abc get asset where custom-fields have value 'abc'

**Comment by snipe** [comment]
You can do `/api/v1/hardware?search=foo` to search for `foo` within all fields (including custom fields). If you need an exact match to fields, you have to pass the `filter` variable, and then JSON:

`/api/v1/hardware?filter={"_snipeit_test_field_5": "bar"}`

**Comment by wsidl** [comment]
Can I suggest adding some labels or editing the title to make the topic of this issue more identifiable?

This is definitely a feature I would like better documented.

**Comment by pjjmd** [comment]
Hey, this was a real helpful bit of info, I couldn't find anything in the api documentation about using filter to search custom fields. Am I missing something, if not, where would be a good place to add it?
