### ISSUE TITLE
Feature Request: Add Notes field to Accessories, Consumables and Components

### ISSUE THREAD

**Issue by miniexplorer** [snipe/snipe-it#6918]
**Server (please complete the following information):**
 - Snipe-IT Version (last version)

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be great to have a Notes field also on Accessories, Consumables and Components similar to the existing on Assets and Licenses.

**Comment by MaxDiOrio** [comment]
In the same vein, you are given an option to add a note when an accessory is checked out to a user, but nowhere can you actually view the note field.

**Comment by snipe** [comment]
@MaxDiOrio Yeah, we're aware of that oversight and will hopefully have a solution soon.

**Comment by MaxDiOrio** [comment]
More info - would be nice if the LDAP sync didn't overwrite the notes field.  We imported some data into that field and it appears that it was overwritten on the next sync.

**Comment by MaxDiOrio** [comment]
Another location - When viewing the user, you can't see the notes field.  Only in list view or when editing.

**Comment by MaxDiOrio** [comment]
Still relevant.

**Comment by miniexplorer** [comment]
Yes, still relevant. Thank you.

**Comment by miniexplorer** [comment]
Yes, please. It is still relevant. Thank you.

**Comment by miniexplorer** [comment]
Yes, please. It is still relevant. Thank you.

**Comment by namarie23** [comment]
Still relevant, notes are highly desired for the other areas!!

**Comment by berilslv** [comment]
bumping this up, as only consumables has notes!

**Comment by dataCore** [comment]
Still relevant - would be a need feature (adding notes to components)

**Comment by tehkillerbee** [comment]
Its been almost three years. Will this ever be added as a feature or should we look elsewhere for a solution?

**Comment by snipe** [comment]
Look elsewhere, I guess. 

This is not a particularly important feature to most people. If it’s important to you, give me a use case or a PR. And in either case, stow the attitude.

**Comment by tehkillerbee** [comment]
@snipe I apologize if I came off as demanding - as that was not my intention. I understand this is an open-source project and you have to prioritize important features. Thanks anyways.

**Comment by snipe** [comment]
It’s not off the table, it’s just not a high priority compared to the other stuff on deck. I can see if we can bang it out quickly, but it will also end up impacting the importer, visual displays, etc.

**Comment by snipe** [comment]
This is on master now

**Comment by tehkillerbee** [comment]
Thanks for the swift update! Looking forward to test it - we are still using 5.4.0 on our hosted snipe-it instance so I am not sure when it will be updated to latest.

It is a small feature but it will make our workflow much easier for sure.

**Comment by snipe** [comment]
@tehkillerbee you can ping me on discord or ask support@snipeitapp.com with your hosted subdomain and we'll get you updated ahead of the bigger rollout. 😄

**Comment by shinduke** [comment]
I would also be glad to have this feature. In our processes the hardware is only given with a ticket number and we fill this ticketnumber to every assesories in the notes. It would be awesome to see the notes in the overview when we select an user and aslo see the the numbers in the "Print all assigned" page afterwards.
