### ISSUE TITLE
FYI - AFK

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#6920]
Hi all - just a heads up that I'm out of town for a bit for a family emergency. I'll try my best to be responsive here, but my attention will largely be elsewhere for at least several weeks, as we provide care for my mother out of town. 

For Snipe-IT customers, our staff will still be answering questions and handling issues as normal and they have an escalation path to me when necessary.

Thank you for your understanding, and for all of the awesome community members that work so hard to support each other here. <3

**Comment by EarlRamirez** [comment]
@snipe, we wish you and your family a speedy recovery. Family is of utmost importance so take care miss Snipe.

**Comment by stbc** [comment]
Best whishes! Take care!

**Comment by ajsy** [comment]
Good luck & best wishes
