### ISSUE TITLE
Feature Request: Option to apply cost to Model instead of individual asset

### ISSUE THREAD

**Issue by omega9380** [snipe/snipe-it#6923]
**Server (please complete the following information):**
N/A

**Describe the solution you'd like**
When our company orders new PCs, we are given a "standard config" on the Dell Premier website, which are priced by model.  A nice option would be to apply Purchase Cost to the model instead of the individual asset in SnipeIT.  I would suggest making it an optional feature, I am sure not everyone tracks asset cost by model :).  Thanks!

**Comment by SirajQu** [comment]
Agreed, that's would be so helpful.

**Comment by SirajQu** [comment]
Yes

**Comment by allexxy** [comment]
thank you for the mail.  this feature request can be put to rest...
