### ISSUE TITLE
Auto-Increment Asset Tags incrementing even when entering tag manually

### ISSUE THREAD

**Issue by omega9380** [snipe/snipe-it#6924]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Auto-Increment Asset Tags incrementing even when entering tag manually.

**To Reproduce**
1. Enable Auto-Increment Asset Tags in settings. (I started mine at 300, but this happens even if you start at 1)
2. Add a new asset
3. Manually change the asset tag to a new number.
4. Save the asset
5. Create another new asset
6. Auto-generated asset tag is set as if 2 assets have been created.  IE, if the Auto Increment was set to 1, the first asset tries to set it to 2, you manually changed it to something else, the second asset starts at 3 instead of 2.

**Expected behavior**
When manually changing the asset tag, auto increment should ignore and not increment.

**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.15 build 4011 (gd1e9fbfa2)
 - OS: Windows 10
 - Web Server: Apache 2.4.37 (Wampserver 3.1.7 32bit)
 - PHP Version: 7.2.14 Apache, 7.2.14 CLI

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 1803
 - Browser: Chrome 
 - Version: 73.0.3683.103 64Bit

**Error Messages**
 - None

**Additional context**
- Is this a fresh install or an upgrade? - Yes
- What OS and web server you're running Snipe-IT on: Windows 10 Build 1803, Wampserver 32 v3.1.7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual install
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database: Yes, ran the following script to update the warranty on my assets table:

`UPDATE assets
SET warranty_months = 36
WHERE _snipeit_operating_system_3 IS NOT NULL`

All my computer assets have a 36m warranty and I have a custom field to track the OS.  I had to do this because I inadvertently forgot to change the warranty column to months instead of a date in my import CSV file when I was transferring my assets to SnipeIT

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by EarlRamirez** [comment]
You will see this behaviour as long as you have auto increment enabled. I will provide more details when I'm in front of my computer.
