### ISSUE TITLE
LDAP Sync

### ISSUE THREAD

**Issue by CRNata** [snipe/snipe-it#6925]
**Server 2012 R2
 - Snipe-IT 4.6.13
 - OS: Windows
 - Web Server: IIS
 - PHP 7.0.33

Hi team its just a query,
Can we able to add two OU's in LDAP sync??
And also after deleting users from AD(OU), the user name is still reflecting in Snipe-IT dashboard, is this normal?

**Comment by SirajQu** [comment]
You need to enable "LDAP Active Flag" to Ignore disabled users in LDAP Active Directory,
just put in the field "active"

and for having two OU I'm not sure about it.

**Comment by snipe** [comment]
You can assign different OUs to different locations, so when you sync your locations, it will pull from that OU.

**Comment by CRNata** [comment]
Hi team,

Getting below error while trying to configure slack channel
" cURL error 60 SSL certificate problem unable to get local issuer certificate()
