### ISSUE TITLE
Confirm acceptance email of assets sometimes works sometimes not.

### ISSUE THREAD

**Issue by SirajQu** [snipe/snipe-it#6926]
**Describe the bug**
I have set up email in the .env setting to send notification alert and confirmation acceptance of assets,
and the strange thing is that sometimes it works sometimes not, when make restart to the whole server it works first time then again not working and when I checkout asset to the user
it says that " This user will be emailed with a link to confirm acceptance of this item. " but then error message comes: Whoops, looks like something went wrong.

Please assist me with this and here is my .env setting for the email:
# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=smtp.office365.com
MAIL_PORT=587
MAIL_USERNAME=************
MAIL_PASSWORD=************
MAIL_ENCRYPTION=TLS
MAIL_FROM_ADDR=************
MAIL_REPLYTO_ADDR=************

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.15
 - OS: Windows Server 2012
 - Web Server: [IIS]
 - PHP Version 7.0.33
--

**Additional context**
- Is this a fresh install or an upgrade? was fresh installtion on Windows Server 2012 then moving the server from Ubuntu to Windows server with all files and database.

- What OS and web server you're running Snipe-IT on
Windows Server 2012

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Manual installation

**Comment by SirajQu** [comment]
When first moving the database and public files, I ran the command 
C:\inetpub\wwwroot\snipe-it>php artisan migrate
and it did complete the migration, when I run it now again it says:
"Nothing to migrate."

means already did the migration but I don't know what cause this issue?

**Comment by snipe** [comment]
You'd need to provide us with app error logs so we can determine what the stacktrace for the "Whoops" error is. This is why we ask for it in the Github Issue template.

https://snipe-it.readme.io/docs/whoops

**Comment by SirajQu** [comment]
Here are the logs from debug mode:
[2019-04-18 12:48:56] production.ERROR: Symfony\Component\Console\Exception\CommandNotFoundException: The namespace "" is ambiguous.
Did you mean one of these?
    debugbar
    backup
    passport
    cache
    auth
    config
    key
    migrate
    queue
    route
    db
    schedule
    storage
    view
    app
    make
    event
    notifications
    session
    vendor
    snipeit
    version in C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php:576
Stack trace:
#0 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(611): Symfony\Component\Console\Application->findNamespace('')
#1 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(236): Symfony\Component\Console\Application->find(':migrate')
#2 C:\inetpub\wwwroot\snipe-it\vendor\symfony\console\Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\inetpub\wwwroot\snipe-it\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 {main}  
error
-------------------------------------

[2019-04-18 12:48:56] production.ERROR: Symfony\Component\Console\Exception\CommandNotFoundException...
error
[2019-04-18 12:48:56] production.ERROR: Symfony\Component\Console\Exception\CommandNotFoundException: The namespace "" is ambiguous.#9 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(89): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(App\Models\Setting), 'd5fc9ce3-80e5-4...', Object(App\Notifications\MailTest), 'mail')
#10 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\NotificationSender.php(64): Illuminate\Notifications\NotificationSender->sendNow(Object(Illuminate\Database\Eloquent\Collection), Object(App\Notifications\MailTest))
#11 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Notifications\ChannelManager.php(36): Illuminate\Notifications\NotificationSender->send(Object(Illuminate\Database\Eloquent\Collection), Object(App\Notifications\MailTest))
#12 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(221): Illuminate\Notifications\ChannelManager->send(Object(App\Models\Setting), Object(App\Notifications\MailTest))
#13 C:\inetpub\wwwroot\snipe-it\app\Http\Controllers\Api\SettingsController.php(136): Illuminate\Support\Facades\Facade::__callStatic('send', Array)
#14 [internal function]: App\Http\Controllers\Api\SettingsController->ajaxTestEmail()
#15 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(55): call_user_func_array(Array, Array)
#16 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(44): Illuminate\Routing\Controller->callAction('ajaxTestEmail', Array)
#17 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Api\SettingsController), 'ajaxTestEmail')
#18 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Route.php(160): Illuminate\Routing\Route->runController()
#19 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(572): Illuminate\Routing\Route->run()
#20 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#23 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#27

**Comment by SirajQu** [comment]
> You'd need to provide us with app error logs so we can determine what the stacktrace for the "Whoops" error is. This is why we ask for it in the Github Issue template.
> 
> https://snipe-it.readme.io/docs/whoops
> 
> > <img alt="" width="48" src="/favicon.ico">**["Whoops!"](https://snipe-it.readme.io/docs/whoops)**500 error

Hopefully we can solve this,
thank you.

**Comment by SirajQu** [comment]
I can see now another log:
`[2019-04-26 00:17:39] production.ERROR: ErrorException: stream_socket_enable_crypto(): SSL: Handshake timed out in C:\inetpub\wwwroot\snipe-it\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php:103#20 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure), 'api')
#23 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(574): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Router.php(533): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#27 C:\inetpub\wwwroot\snipe-it\vendor\laravel\fra`

and in the test mail where it says "Mail Couldn't be sent" it show under it:
"Error: An Error has occured! stream_socket_enable_crypto(): SSL: Handshake timed out"

![2019-04-26_0-33-15](https://user-images.githubusercontent.com/30687897/56769805-02800380-67bb-11e9-822e-4c80fc8775e3.jpg)

Is this because I'm not using SSL certificate in the localhost server? and how to avoid that?

**Comment by SirajQu** [comment]
Yes, still same issue.

**Comment by Thejessicaduke** [comment]
I have same issue, mine sends email confirmation alert for only assets that are monitors but doesn't send mail notification for laptops, phones, cameras and access points.
