### ISSUE TITLE
If a user is not 'Super User' he doesn't see any custom fields when importing csv files

### ISSUE THREAD

**Issue by mihsu81** [snipe/snipe-it#6929]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
A user which is Admin and has full permissions (except Super User) doesn't see Custom Fields in "Import Field" when importing csv files. This issues doesn't happen when the user is granter Super User permissions

**To Reproduce**
1. Go to 'Import'
2. Click on 'Select Import File...'
3. Select the csvfile
4. Click on "Process"
5. Select Import type: 'Assets'
6. A custom field (i.e. MAC ADDRESS) doesn't appear in the drop down list of "Import Field"

**Expected behavior**
A user with full permissions (except Super User) should see "Custom Fields" in "Import Field" when importing csv files.

**Screenshots**
Missing Custom Field "MAC ADDRESS" when the user is not Super User
![image](https://user-images.githubusercontent.com/40715497/56396065-deb24000-6245-11e9-9199-cf41fbd4d384.png)
Custom Filed "MAC ADDRESS" present when the user has been granted the Super User permissions.
![image](https://user-images.githubusercontent.com/40715497/56396107-099c9400-6246-11e9-9804-75c6e0895500.png)

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.15 build 4011 (gd1e9fbfa2)
 - OS: CentOS 7.6.1810 (Core)
 - Web Server: Apache 2.4.6-88
 - PHP Version: 7.2.17

**Desktop (please complete the following information):**
 - OS: Windows 10 1709
 - Browser Chrome
 - Version 73.0.3683.103

**Desktop (please complete the following information):**
 - OS: Windows 10 1809
 - Browser Edge
 - Version 44.17763.1.0
 - EdgeHTML 18.17763

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error None
- If a stacktrace is provided in the error, include that too. None
- Any errors that appear in your browser's error console. None
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. No. The demo doesn't have the Import module enabled
- Include any additional information you can find in `storage/logs` and your webserver's logs. Nothing relevant

**Additional context**
- Is this a fresh install or an upgrade? Upgrade from 4.5
- What OS and web server you're running Snipe-IT on CentOS 7.6.1810 (Core) / Apache 2.4.6-88
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) git/install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way. No errors
- Indicate whether or not you've manually edited any data directly in the database No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by EarlRamirez** [comment]
I was under the impression that only super users can import,  I will try and reproduce this

**Comment by mihsu81** [comment]
Indeed, previously only a Super User was able to import.
Recently a permission was added which allowed Admins to perform csv imports.
