### ISSUE TITLE
Vcenter -SCCM objects discover

### ISSUE THREAD

**Issue by serhatbaydar** [snipe/snipe-it#6931]
Hi ALL,

I installed docker version of snipe-it. I want to keep all my inventory to this tool.

But I dont want to manage this tool statically,Also ı dont want to ımport all my assets to snipeit.
For example, If ı create 2 Vm's today . It added to own properties to snipeit asset tools ,end of the day.
 I want to automatize this cycle. 

So I need to integrate my Inventory tools to Snipeit.
How to integrate my Vcenter to snipeit or how to integrate my MS Sccm tools to Snipeit ?

In this way, If I'll achieve this integrations, I think many IT stuff will relax to manage own Asset.

Best Regards,

----------------------------------------------------------------------------------------
**Server (please complete the following information):**
 - Snipe-IT Version  : Latest
 - OS: [e.g. Ubuntu, CentOS]  : Centos 7 64 bit
 - Web Server: [e.g. Apache, IIS] : Apache
 - PHP Version  : 7

**Comment by therealjoshuad** [comment]
Learning to use the REST API will probably be your best bet. There isn’t anything that can automatically do this.
