### ISSUE TITLE
Feature Request: Component / Consumable / License checkout via API

### ISSUE THREAD

**Issue by sirastynax** [snipe/snipe-it#6935]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.15
 - OS: Ubuntu 16.04
 - Web Server: Apache
 - PHP Version 7.0.33

**Is your feature request related to a problem? Please describe.**
In trying to incorporate Snipe-IT into our IT workflow, there are a couple of features that would allow us to more easily monitor and manage our hardware lifecycle. This is one of those features. It is not so much a problem as an end-to-a-means. This would allow us to continuously monitor changed hardware in our systems, as well as inventory and automatically create assets with their constituent hardware in Snipe-IT, by running a script.

**Describe the solution you'd like**
We would like to be able to check-out components, consumables and licenses programmatically via API. 

**Describe alternatives you've considered**
Alternatives to this are to add the items programmatically and then check out the items to the asset one-by-one. this takes quite a bit of time if we have to provision and roll-out a large amount of servers. Another alternative would be create a csv file for imports, but I am not sure if you can make that association in the csv file, as I have not checked. This would be a quicker alternative, but still not ideal. 

**Additional context**
None

**Comment by scotteelp** [comment]
Hope this doesn't turn stale....this feature would be great for a software licensing project I'm currently working on.

**Comment by scotteelp** [comment]
Keep this alive!!

**Comment by TitoVince35** [comment]
Same as Scott : I need to remote checkout license seat with the API!
Maybe it's time to dig in Laravel..

**Comment by scotteelp** [comment]
Please keep open.

**Comment by viclou** [comment]
+1 FC

**Comment by pantherale0** [comment]
Too add to this, it seems the API already exists to checkout as the below is seen in my nginx logs
`"POST /components/1/checkout HTTP/1.1" 302`
It seems a number of available API endpoints haven't been documented....

**Comment by bzeus** [comment]
New FR
