### ISSUE TITLE
CentOS 7 php56 - The stream or file "/var/www/snipe-it/storage/logs/laravel.log"

### ISSUE THREAD

**Issue by poperann** [snipe/snipe-it#6936]
Hi, So I'm setting up and have been reading all types of open issue and google searching, I have came to same issue of "permission"  issue.
I have checked and even tried 777 but I yet get issue.

Below is my list of script to setup snipe-it for CentOS 7 (4/20/19) clean downloaded iso.
(If some one need manual, you can use this to setup)

If there is a solution for the "permission" this manual may help alot of people setting up on centOS.

Please help./

Thank you

-------------------------------------------------------------

yum -y update
yum -y install httpd
yum -y install nano
systemctl start httpd.service
systemctl enable httpd.service
systemctl status httpd

yum -y install mariadb-server
systemctl start mariadb.service
systemctl enable mariadb.service
systemctl status mariadb.service

mysql_secure_installation
***************
////// All questions by pressing Y.
***************

mysql -u root -p
***************************
CREATE DATABASE snipeit_data;
CREATE USER 'snipeit_user'@'localhost' IDENTIFIED BY 'Changeme';
GRANT ALL PRIVILEGES ON snipeit_data.* TO 'snipeit_user'@'localhost';
FLUSH PRIVILEGES;
EXIT
***************************

yum -y install epel-release 
rpm -Uvh http://rpms.remirepo.net/enterprise/remi-release-7.rpm
yum -y install yum-utils
yum-config-manager --enable remi-php56 
******************************
yum -y install php php-openssl php-pdo php-mbstring php-tokenizer php-curl php-mysql php-ldap php-zip php-fileinfo php-gd php-dom php-mcrypt
systemctl restart httpd

curl -sS https://getcomposer.org/installer | php 
mv composer.phar /usr/bin/composer

yum -y install git
cd /var/www/ 

git clone https://github.com/snipe/snipe-it snipe-it
cd /var/www/snipe-it

cp .env.example .env
nano .env
******************************************************************
APP_ENV=production
APP_DEBUG=false
APP_KEY=
APP_URL=10.0.0.19
APP_TIMEZONE='UTC'
APP_LOCALE=en

# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=snipeit_data
DB_USERNAME=snipeit_user
DB_PASSWORD=Changeme
DB_PREFIX=null
DB_DUMP_PATH='/usr/bin'
DB_CHARSET=utf8mb4
DB_COLLATION=utf8mb4_unicode_ci
***************************************************************

chown -R apache:apache storage public/uploads 
chmod -R 755 storage 
chmod -R 755 public/uploads 
yum --enablerepo=remi -y install php-tecnickcom-tc-lib-barcode
composer install --no-dev --prefer-source
********************************
composer dump-autoload
php artisan clear-compiled
composer update --no-scripts
********************************

php artisan key:generate
firewall-cmd --zone=public --permanent --add-service=http 
firewall-cmd --reload
nano /etc/httpd/conf.d/snipeit.example.com.conf
*******************************
<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /var/www/snipe-it/public
    <Directory /var/www/snipe-it/public>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
    </Directory>
</VirtualHost>
*******************************

systemctl restart httpd

**Comment by snipe** [comment]
Please check and make sure that SELinux isn't installed. 
https://snipe-it.readme.io/docs/linuxosx#section-notes-on-selinux

**Comment by poperann** [comment]
You are awesome.

Last Step needed is 

nano /etc/sysconfig/selinux
**********************************
SELINUX=disabled
**********************************

**Comment by EarlRamirez** [comment]
It is not recommended to disable SELinux, there is a custom CentOS ISO that is built with SELinux enabled. Can you run the following command *ausearch -m avc -ts recent* and share it with us

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
