### ISSUE TITLE
New joiner E-Mail notification 

### ISSUE THREAD

**Issue by CRNata** [snipe/snipe-it#6937]
**Server 2012 R2
 - Snipe-IT 4.6.13
 - OS: windows 
 - Web Server: IIS
 - PHP Version 7.0.33

Hi team,

How do we add new joiner to the group privileges, Every time do we need to add manually or after jioning, OU will they get access to see which accessories have allocated on their names?

**Comment by snipe** [comment]
I'm not sure I understand the question - can you clarify what you mean?
