### ISSUE TITLE
Issue : Asset Report error - Demo site

### ISSUE THREAD

**Issue by joseph707** [snipe/snipe-it#694]
hi @snipe 

We have an error when clicked on Custom Asset Report on the demo Website.

![report](https://cloud.githubusercontent.com/assets/9422649/6839645/3b5f32e4-d385-11e4-8b2d-96c059f0823b.JPG)

Regards

Joseph

**Comment by snipe** [comment]
Hi @joseph707 - I can't seem to reproduce this on the demo site.

![screen shot 2015-03-27 at 7 48 47 pm](https://cloud.githubusercontent.com/assets/197404/6879596/55c85c92-d4ba-11e4-90e7-b947287b2e65.png)

**Comment by joseph707** [comment]
hi snipe

good morning. my apologies. I meant just the Asset Report Page. My wording in the title was wrong. Sorry. When you click on the Asset report Page, you get an error as attached in my previous mail.

Regards

Joseph

**Comment by snipe** [comment]
Fixed.
