### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by Griehle** [snipe/snipe-it#6941]
I cannot find any forums of note or anywhere to discuss the SnipeIT program with other devs. For General questions that is. If there is somewhere please direct me.

Thank you.

**Comment by EarlRamirez** [comment]
Here is okay or your can chat on gitter.im, as far as I'm aware off, there isn't any dedicated forum for dev's in this community.

**Comment by Griehle** [comment]
I am trying to create a variation on the depreciation report where I can group and count totals in. so if dept (they called them accounts) Operations , asset type Computer equipment,  for the month of July depreciations are $8357 total   kind of thing.  listing 6 dept(accounts) and 2 asset types.

**Comment by Griehle** [comment]
I had to just figure it out. I would contribute but I doubt it would be useful to anyone else. This can be closed.
