### ISSUE TITLE
How to add custom text in the asset acceptance page above the signature

### ISSUE THREAD

**Issue by SirajQu** [snipe/snipe-it#6942]
Hi,
I want to add specific custom text inside the page of acceptance of the assets, where the user make accept then put his signature.

Screenshot example:
![2019-04-23_12-45-38](https://user-images.githubusercontent.com/30687897/56652141-50015100-6693-11e9-9551-a7638cbfe20e.jpg)

**Comment by acox216** [comment]
You can do that by updating the EULA (or custom text) on the desired asset category where the user is accepting the asset from.

**Comment by SirajQu** [comment]
> You can do that by updating the EULA (or custom text) on the desired asset category where the user is accepting the asset from.

Thank you dear, but where I can see the EULA text after I set it up? how the end user sees it and can it be displayed in the acceptance page?

**Comment by acox216** [comment]
It will look similar to the screenshot below once it's set up. 

![a2e246e-require-signature](https://user-images.githubusercontent.com/49688662/56700766-eb151d80-66c9-11e9-90bf-2e506e4db543.gif)

**Comment by SirajQu** [comment]
> It will look similar to the screenshot below once it's set up.
> 
> ![a2e246e-require-signature](https://user-images.githubusercontent.com/49688662/56700766-eb151d80-66c9-11e9-90bf-2e506e4db543.gif)

Thank you so much dear.
