### ISSUE TITLE
Buttons to print / export / import / do not appear

### ISSUE THREAD

**Issue by sqzandre** [snipe/snipe-it#695]

**Comment by sqzandre** [comment]
installed the 1.2.6.1 version and buttons to print / export / import / do not appear
PHP version 5.6.  As active?

**Comment by madd15** [comment]
Hi @sqzandre, 
If you are talking about the buttons (copy/print/export) above the asset table then these were not in the release you specified. If its not those buttons could you please provide more information on where you are experiencing this issue.

Thanks

**Comment by sqzandre** [comment]
hello @madd15, thanks for the reply.
 It is exactly above the active table buttons. I view only the search field. I do not see the options to copy, print, export. Do not see in any of the screens. How do I activate them?

![image](https://cloud.githubusercontent.com/assets/11639648/6857673/5715ebba-d3e7-11e4-9293-a2e7dc0ec107.png)

 thank you.

**Comment by snipe** [comment]
@sqzandre as @madd15 mentioned, that functionality is not yet in an official release. It's only on the develop branch, and will be merged into a release when we're done with development and testing for the next release.

**Comment by sqzandre** [comment]
thank's @madd15 @snipe
