### ISSUE TITLE
Backup Issue (From WebSite not working / with console working)

### ISSUE THREAD

**Issue by michaelhaerri** [snipe/snipe-it#6950]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
If I run from commandline "C:\inetpub\wwwroot\snipe-it>php artisan snipeit:backup" the backup file was created. But when I will do it from the Snipe-IT Webpage (https://"servername"/admin/backups) I receive the error:

 Error:  Backup failed because The dump process failed with exitcode 1 : General error : . 

No Backup-file is created. 

Path in .env is correct / All Permissions are made in any folder. I gave IUSR and IIS_IUSRS full access to any Folder in Snipe-IT and to C:\Windows\Temp

Same Issue on Server or from a client.

Any Idea? 

**Screenshots**
![image](https://user-images.githubusercontent.com/49979716/56727358-12a6cd00-6740-11e9-958a-3e5b381f2f74.png)

![image](https://user-images.githubusercontent.com/49979716/56726800-ffdfc880-673e-11e9-84ce-effa3ae8020d.png)

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.15 build 4011
 - OS: Windows Server 2012R2
 - Web Server: IIS
 - PHP Version: 7.0.31

**Error Messages**
Laravel-Log in C:\inetpub\wwwroot\snipe-it\storage\logs

[2019-04-25 11:51:09] production.ERROR: backups backups : error: Failed to backup  because: The dump process failed with exitcode 1 : General error :   
[2019-04-25 11:51:09] production.ERROR: backups backups : error: Failed to backup  because: The dump process failed with exitcode 1 : General error :   
[2019-04-25 11:51:10] production.ERROR: Debugbar exception: Route [debugbar.openhandler] not defined.  

**Additional context**
- Is this a fresh install or an upgrade? Fresh install
- What method you used to install Snipe-IT) Manuell
- Indicate whether or not you've manually edited any data directly in the database: No

**Comment by EarlRamirez** [comment]
I will have to install Snipe-IT on Windows and see if I can assist you with this issue

**Comment by michaelhaerri** [comment]
That will be great! Thank you.

**Comment by cdcs68** [comment]
Hi,
I'm running Snipe It v4.5.16 Build 4011 on Windows Server 2016 (and just recently on Windows Server 2012--I didn't have any problems after upgrading the OS).

You have to set your path in the your **.env** file.  I edit the .env file using NotePad++ on my Snipe It server.  Be sure to run in as administrator so you can save changes. 

This is the setting for my  backup path (see the following screenshot).  I left out security sensitive information.  Also, I haven't had any success with changing the default path for the backups.

![image](https://user-images.githubusercontent.com/25690788/57034625-a8959880-6c15-11e9-8c8e-ebce8734b517.png)

**Here's a screenshot with what is displayed in the Backups screen.** 

![image](https://user-images.githubusercontent.com/25690788/57035450-b3512d00-6c17-11e9-8f92-9cad51491d9d.png)

**Here's a screenshot of the successful backups.**

![image](https://user-images.githubusercontent.com/25690788/57039127-6a9e7180-6c21-11e9-9cc9-4b5be7ddddd4.png)

**After you make and save the changes, you need to run the following commands (run the command prompt as administrator):**

![image](https://user-images.githubusercontent.com/25690788/57038999-08457100-6c21-11e9-9715-a966ec9b3f11.png)

I hope this is helpful.

**Comment by michaelhaerri** [comment]
Hi

Thank you for your tests. This are the same setting like I do on my installation. Please see printscreen. If I run the task from command line with command php artisan snipeit:backup then it’s working. But not from the Webpage with the Button «Generate Backup».

Any other idea?

Best regards

Michael

Michael Härri
System Application Engineer
Back-End Management

Ricoh Schweiz AG
Bionstrasse 5
CH-9015 St. Gallen
Switzerland
Tel: +41 (0)44 832 32 79
Mobile: +41 (0)76 314 56 76
michael.haerri@ricoh.ch<mailto:michael.haerri@ricoh.ch>
www.ricoh.ch<file://ad.eu.rf-group.org/Public/RCH/Horgen/Public/MARKETINGCOMMUNICATION/PUBLIC/Marketing/Intranet/Outlook/www.ricoh.ch>

[cid:image012.gif@01D395E2.3C686B20]<http://www.ricoh.ch/>

[cid:image013.jpg@01D395E2.3C686B20]<http://www.facebook.com/ricohschweiz> [cid:image014.jpg@01D395E2.3C686B20] <https://twitter.com/ricohschweiz>  [cid:image015.jpg@01D395E2.3C686B20] <https://www.xing.com/companies/ricohschweizag>  [cid:image016.png@01D395E2.3C686B20] <https://www.linkedin.com/company/ricoh-schweiz-ag>  [cid:image004.png@01D4AD77.E0A6FAA0] <https://www.youtube.com/channel/UCc0qEZYNxmw-wSbIF-HcaLA>

[cid:image017.png@01D395E2.3C686B20]<http://www.ricoh.ch/eservice>

Von: cdcs68 <notifications@github.com>
Gesendet: Mittwoch, 1. Mai 2019 22:00
An: snipe/snipe-it <snipe-it@noreply.github.com>
Cc: Michael Haerri <Michael.Haerri@ricoh.ch>; Author <author@noreply.github.com>
Betreff: Re: [snipe/snipe-it] Backup Issue (From WebSite not working / with console working) (#6950)


Hi,
I'm running Snipe It v4.5.16 Build 4011 on Windows Server 2016 (and just recently on Windows Server 2012--I didn't have any problems after upgrading the OS).

You have to set your path in the your .env file. I edit the .env file using NotePad++ on my Snipe It server. Be sure to run in as administrator so you can save changes.

This is the setting for my backup path (see the following screenshot). I left out security sensitive information. Also, I haven't had any success with changing the default path for the backups.

[image]<https://user-images.githubusercontent.com/25690788/57034625-a8959880-6c15-11e9-8c8e-ebce8734b517.png>

Here's a screenshot with what is displayed in the Backups screen.

[image]<https://user-images.githubusercontent.com/25690788/57035450-b3512d00-6c17-11e9-8f92-9cad51491d9d.png>

Here's a screenshot of the successful backups.

[image]<https://user-images.githubusercontent.com/25690788/57039127-6a9e7180-6c21-11e9-9cc9-4b5be7ddddd4.png>

After you make and save the changes, you need to run the following commands (run the command prompt as administrator):

[image]<https://user-images.githubusercontent.com/25690788/57038999-08457100-6c21-11e9-9715-a966ec9b3f11.png>

I hope this is helpful.

**Comment by cdcs68** [comment]
Hi @michaelhaerri 
I've seen this before. This happened to me as well.  Would work from the command line but not from the web client.
Please paste a snapshot of your .env file, REQUIRED: DATA SETTINGS.
Mark out the database and database credentials information.
Thanks.

**Comment by michaelhaerri** [comment]
Hi cdcs68

Following my settings from the .env. 

Many thanks

Michael

# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=base64:WZwlreiiYIZFUZ+THhAmVnF+pqyNmW6exnaaiNGmBrw=
APP_URL=
APP_TIMEZONE='Europe/Zurich'
APP_LOCALE=de

# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_DATABASE=
DB_USERNAME=
DB_PASSWORD=
DB_PREFIX=null
DB_DUMP_PATH='C:\\PROGRA~1\\MariaD~1.0\\bin'
DB_CHARSET=utf8mb4
DB_COLLATION=utf8mb4_unicode_ci

# --------------------------------------------
# OPTIONAL: SSL DATABASE SETTINGS
# --------------------------------------------
DB_SSL=false
DB_SSL_KEY_PATH=null
DB_SSL_CERT_PATH=null
DB_SSL_CA_PATH=null
DB_SSL_CIPHER=null

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=
MAIL_PORT=587
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=
MAIL_FROM_NAME=
MAIL_REPLYTO_ADDR=
MAIL_REPLYTO_NAME=

# --------------------------------------------
# REQUIRED: IMAGE LIBRARY
# This should be gd or imagick
# --------------------------------------------
IMAGE_LIB=gd

# --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME=snipeit_session
COOKIE_DOMAIN=null
SECURE_COOKIES=false

# --------------------------------------------
# OPTIONAL: SECURITY HEADER SETTINGS
# --------------------------------------------
REFERRER_POLICY=same-origin
ENABLE_CSP=false

# --------------------------------------------
# OPTIONAL: CACHE SETTINGS
# --------------------------------------------
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync
CACHE_PREFIX=snipeit

# --------------------------------------------
# OPTIONAL: REDIS SETTINGS
# --------------------------------------------
REDIS_HOST=null
REDIS_PASSWORD=null
REDIS_PORT=null

# --------------------------------------------
# OPTIONAL: MEMCACHED SETTINGS
# --------------------------------------------
MEMCACHED_HOST=null
MEMCACHED_PORT=null

# --------------------------------------------
# OPTIONAL: AWS S3 SETTINGS
# --------------------------------------------
AWS_SECRET=null
AWS_KEY=null
AWS_REGION=null
AWS_BUCKET=null

# --------------------------------------------
# OPTIONAL: LOGIN THROTTLING
# --------------------------------------------
LOGIN_MAX_ATTEMPTS=5
LOGIN_LOCKOUT_DURATION=60

# --------------------------------------------
# OPTIONAL: MISC
# --------------------------------------------
APP_LOG=single
APP_LOG_MAX_FILES=10
APP_LOCKED=false
FILESYSTEM_DISK=local
APP_TRUSTED_PROXIES=192.168.1.1,10.0.0.1
ALLOW_IFRAMING=false
APP_CIPHER=AES-256-CBC
GOOGLE_MAPS_API=
BACKUP_ENV=true

**Comment by cdcs68** [comment]
@michaelhaerri 
Hi,
Your dump path should be something like:

**DB_DUMP_PATH='C:\PROGRA~1\MariaD1.0\bin'**
NOTE:  You will use single quotes ' before and after the folder name.

OR

DB_DUMP_PATH='C:\PROGRA~2\MariaD1.0\bin'

**Using Notepad++ (run it as administrator)**, **create** the following command file:

**@ECHO OFF
echo %~s1**

Save the file name as shortnamepath.cmd on the C:\ drive.
  
**Next, open the Windows command prompt (run it as administrator).**

Type the following:  **shortnamepath.cmd "c:\Program Files (x86)\MariaD1.0\bin"**

**NOTE:**  You will use double quotes " before and after the name of the folder.

or if it's "c:\Program Files\MariaD1.0\bin"

It will display the short name path that you must use for the DB_DUMP_PATH.

![shortnamepath2](https://user-images.githubusercontent.com/25690788/57319512-55fb2700-70c2-11e9-9eb4-3082fd30652f.JPG)
![shortnamepath1](https://user-images.githubusercontent.com/25690788/57319518-585d8100-70c2-11e9-882a-2f04f112a3c6.JPG)

Here's the website I used to help me:  https://superuser.com/questions/348079/how-can-i-find-the-short-path-of-a-windows-directory-file

**Comment by michaelhaerri** [comment]
Hi, I think my DB_DUMP_PATH is correct. I follow your instructions and receive this shortnamepath:

C:\>shortnamepath.cmd "C:\Program Files\MariaDB 10.0\bin"
C:\PROGRA~1\MARIAD~1.0\bin

The DB_DUMP_PATH in my .env is:

DB_DUMP_PATH='C:\PROGRA~1\MARIAD~1.0\bin'

After I change the DB_DUMP_PATH i run the commands

php artisan config:clear
and
php artisan config:cache

But it's not working. I receive always the same error-code on the webpage:

 Error:  Backup failed because The dump process failed with exitcode 1 : General error : . 

Any other idea?

**Comment by michaelhaerri** [comment]
Hi
I see that the DB_DUMP_PATH is not showing correctly in this form. Here is the printscreen from my .env and from the commandline:

![image](https://user-images.githubusercontent.com/49979716/57363867-42af9080-7182-11e9-876c-c02ba0f1e899.png)

![image](https://user-images.githubusercontent.com/49979716/57363881-4a6f3500-7182-11e9-9060-4ab6c7a01562.png)

**Comment by cdcs68** [comment]
@michaelhaerri 
P.S.  Don't forget to run the following after you modify and save your .env file:

php artisan config:clear
php artisan cache:clear

**Comment by cdcs68** [comment]
@michaelhaerri 
P.S.  After you modify and save your .env file, don't forgot to run the following commands:
php artisan config:clear
php artisan cache: clear

**Comment by michaelhaerri** [comment]
Hi

I try it with different configurations:

![image](https://user-images.githubusercontent.com/49979716/57430940-c28c3800-7220-11e9-8e2c-c3f1cf867ad2.png)

"C:\\PROGRA~1\\MARIAD~1.0\\bin"
"C:\PROGRA~1\MARIAD~1.0\bin"
'C:\\PROGRA~1\\MARIAD~1.0\\bin'
'C:\PROGRA~1\MARIAD~1.0\bin'

Every time after changing the configuration I run the commands:

php artisan config:clear
php artisan cache:clear

and Restart the Webservice

But no chance. Every time the same error....

Any other ideas?

**Comment by cdcs68** [comment]
@michaelhaerri 
Hi,
It looks like you are doing everything right so this is a puzzler.  Post a screenshot of your folder structure that shows up in file explorer for your Maria Database.
In the meantime, try this:

![image](https://user-images.githubusercontent.com/25690788/57456581-6da5ed00-7233-11e9-95fa-dfa71e756c0b.png)

You'll be changing the 1 to a 2.

Thanks.

**Comment by michaelhaerri** [comment]
Hi

Here's the screenshot:

![image](https://user-images.githubusercontent.com/49979716/57458774-7ad9d080-7261-11e9-9511-800208712a9b.png)

**Comment by cdcs68** [comment]
Hi Michael,

Please forgive me.  I didn’t notice that your Maria folder is MariaD10.0 versus what I was using Maria1.0.

So, your DB_­DUMP_PATH=’C:\PROGRA~1\MariaD10.0\bin’

OR

DB_­DUMP_PATH=’C:\\PROGRA~1\\MariaD10.0\\bin’


Cameshia

Cameshia Cargle
Senior Systems Administrator

TEXAS A&M FOUNDATION  |  LEADbyEXAMPLE
401 George Bush Dr.  |  College Station, TX 77840
Office: (800) 392-3310  |  Direct: (979) 845-7906
txamfoundation.com<http://give.am/cGWjAMb>  |  leadbyexample.tamu.edu<http://give.am/EikZSxS>
“Where passion finds purpose”

**Comment by michaelhaerri** [comment]
Hi, 

That's also not working. I try this combinations:

DB_­DUMP_PATH=’C:\PROGRA~1\MariaD10.0\bin’
DB_­DUMP_PATH='C:\PROGRA~1\MariaD10.0\bin'
DB_­DUMP_PATH="C:\PROGRA~1\MariaD10.0\bin"
DB_­DUMP_PATH="C:\\PROGRA~1\\MariaD10.0\\bin"

Every time after changing the configuration I run the commands:

php artisan config:clear
php artisan cache:clear

and Restart the Webservice

But no chance. Every time the same error....

**Comment by michaelhaerri** [comment]
I mean this combinations:

![image](https://user-images.githubusercontent.com/49979716/57506671-0b5cf300-72ec-11e9-9b4f-88238466cc4e.png)

**Comment by cdcs68** [comment]
@michaelhaerri 
Hi Michael,
At this point, I don't see anything wrong.  I can't imagine the problem being with uppercase/lowercase of the path.  Especially when you use the short path command, it shows you the exact path you should be using. 
I don't see any special permissions to my bin path.  I have included screen shots.  I'm running out of suggestions.

![image](https://user-images.githubusercontent.com/25690788/57538891-efb71400-730e-11e9-985d-a582917a8321.png)

![image](https://user-images.githubusercontent.com/25690788/57538905-f8a7e580-730e-11e9-8428-20bd033ce5a7.png)

**Comment by michaelhaerri** [comment]
Hi

I will do an other installation on a new server and check the functionality again.

Thanks for your support.

Michael

**Comment by cdcs68** [comment]
Ok, good luck.

I’m sorry this has been so difficult.

Cameshia

Cameshia Cargle
Senior Systems Administrator

TEXAS A&M FOUNDATION  |  LEADbyEXAMPLE
401 George Bush Dr.  |  College Station, TX 77840
Office: (800) 392-3310  |  Direct: (979) 845-7906
txamfoundation.com<http://give.am/cGWjAMb>  |  leadbyexample.tamu.edu<http://give.am/EikZSxS>
“Where passion finds purpose”
