### ISSUE TITLE
Failed to load image

### ISSUE THREAD

**Issue by arbalestx91** [snipe/snipe-it#6953]
#### Please confirm you have done the following before posting your bug report:

- [ x ] I have enabled debug mode 
- [ x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Images uploaded seems to be uploaded to storage/app/public/...

**To Reproduce**
1. Go to e.g. Asset
2. Click on "Edit Asset"
3. Scroll down to 'Upload Image'
4. Click "Save"
5. Image shows broken link 
6. Upon clicking the broken link it shows "Failed to load image"

**Expected behavior**
Asset image or any images are supposed to save into the public/uploads/... folder.

**Screenshots**
![image](https://user-images.githubusercontent.com/534403/56782512-0e4ee280-681a-11e9-9b39-bca494adbc84.png)
![image](https://user-images.githubusercontent.com/534403/56782564-4524f880-681a-11e9-9b03-9938f24f2bf6.png)
![image](https://user-images.githubusercontent.com/534403/56782575-4fdf8d80-681a-11e9-8d40-7e30e8e08fb8.png)

**Server (please complete the following information):**
 - Snipe-IT Version v5.0.0-beta-2 - build 4009
 - OS: [e.g. Ubuntu, CentOS] Windows Server 2012R2
 - Web Server: [e.g. Apache, IIS] IIS
 - PHP Version 7.3.4

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 Pro
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 66.0.3

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
no errors
- If a stacktrace is provided in the error, include that too.
[2019-04-26 03:48:49] production.INFO: ErrorException: unlink(C:\inetpub\wwwroot\snipe\public/uploads/assets/asset-lqy3k6RsIcPHJUfzbW.png): No such file or directory in C:\inetpub\wwwroot\snipe\app\Http\Controllers\Assets\AssetsController.php:308
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'unlink(C:\\inetp...', 'C:\\inetpub\\wwwr...', 308, Array)
#1 C:\inetpub\wwwroot\snipe\app\Http\Controllers\Assets\AssetsController.php(308): unlink('C:\\inetpub\\wwwr...')
#2 [internal function]: App\Http\Controllers\Assets\AssetsController->update(Object(App\Http\Requests\ImageUploadRequest), '3')
#3 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): call_user_func_array(Array, Array)
#4 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('update', Array)
#5 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\Assets\AssetsController), 'update')
#6 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Route.php(176): Illuminate\Routing\Route->runController()
#7 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Router.php(682): Illuminate\Routing\Route->run()
#8 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#9 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#11 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 C:\inetpub\wwwroot\snipe\vendor\laravel\passport\src\Http\Middleware\CreateFreshApiToken.php(50): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Laravel\Passport\Http\Middleware\CreateFreshApiToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 C:\inetpub\wwwroot\snipe\app\Http\Middleware\CheckForTwoFactor.php(53): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#16 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): App\Http\Middleware\CheckForTwoFactor->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 C:\inetpub\wwwroot\snipe\app\Http\Middleware\CheckLocale.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): App\Http\Middleware\CheckLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(75): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#28 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Router.php(684): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#32 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Router.php(659): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#33 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Router.php(625): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#34 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Router.php(614): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#35 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#36 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#37 C:\inetpub\wwwroot\snipe\vendor\barryvdh\laravel-debugbar\src\Middleware\InjectDebugbar.php(65): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Barryvdh\Debugbar\Middleware\InjectDebugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(31): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 C:\inetpub\wwwroot\snipe\app\Http\Middleware\CheckForDebug.php(25): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): App\Http\Middleware\CheckForDebug->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 C:\inetpub\wwwroot\snipe\app\Http\Middleware\CheckForSetup.php(26): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): App\Http\Middleware\CheckForSetup->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 C:\inetpub\wwwroot\snipe\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 C:\inetpub\wwwroot\snipe\app\Http\Middleware\NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 C:\inetpub\wwwroot\snipe\app\Http\Middleware\ContentSecurityPolicyHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): App\Http\Middleware\ContentSecurityPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 C:\inetpub\wwwroot\snipe\app\Http\Middleware\ReferrerPolicyHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#59 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): App\Http\Middleware\ReferrerPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 C:\inetpub\wwwroot\snipe\app\Http\Middleware\XssProtectHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#62 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): App\Http\Middleware\XssProtectHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 C:\inetpub\wwwroot\snipe\app\Http\Middleware\FrameGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#65 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): App\Http\Middleware\FrameGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#66 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#68 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#69 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(63): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#71 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#72 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#73 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#74 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(163): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#75 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#76 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#77 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#78 C:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#79 C:\inetpub\wwwroot\snipe\public\index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#80 {main}  
- Any errors that appear in your browser's error console.
Failed to load image:  http://xxxxxx.com/storage/assets/asset-WvpLcYsZOMQM3s901y.png
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
no errors
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? fresh
- What OS and web server you're running Snipe-IT on - Windows Server 2012R2 IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - manual install
- Include what you've done so far in the installation, and if you got any error messages along the way. - no
- Indicate whether or not you've manually edited any data directly in the database - no

.env file has been checked to ensure APP_URL is correct.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by EarlRamirez** [comment]
I'm not too familiar with Windows behaviour,  but it looks like you don't have sufficient permissions from your web server user to read the file.

**Comment by arbalestx91** [comment]
according to the guide i have included permissions to storage, cache, temp and upload folder to IUSR 

![image](https://user-images.githubusercontent.com/534403/56795909-0c9a1480-6844-11e9-9514-ec64d4e840ae.png)
![image](https://user-images.githubusercontent.com/534403/56795933-220f3e80-6844-11e9-9e05-50c114eb85b9.png)
![image](https://user-images.githubusercontent.com/534403/56795969-36ebd200-6844-11e9-881a-0cd9220f822d.png)
![image](https://user-images.githubusercontent.com/534403/56796029-5125b000-6844-11e9-8860-cb71f1aaef82.png)

**Comment by CSAS-Nicholas-Roberts** [comment]
Do your jpg images work and just the png's don't?

**Comment by arbalestx91** [comment]
jpg doesn't work either.

"Allow unlisted file name extensions" is checked

**Comment by cfasect** [comment]
I'm encountering a similar issue when attaching images to Asset Models. Though I'm running on Linux.

What I've discovered is the images for Asset Models are uploading properly. They are being placed into:
storage/app/public/assetmodels

But the software expects to find the images in:
storage/assetmodels

**Comment by MacCaloway** [comment]
Hi,

Same issue for us but the images aren't loading properly even in storage/app/public/assetmodels

**Comment by Mikey84** [comment]
+1 Ubuntu server same as issue after I upgraded to 5.0.1 version

**Comment by MuratDoganer** [comment]
Same here on the new stable master build, no images being loaded, no logos, just says failed to load asset 

I checked php7.4-gd was installed, ran updates but no luck

**Comment by eenturk** [comment]
Same problem here also the QR codes are not loading properly running in Docker container

**Comment by pascal-ts** [comment]
I am having the exact same issue, I upgraded from 4.9.2 to 5.0.7 on a CentOS 8 VM.
I tried php artisan config:clear, restarted the machine, cleared my browser cache, nothing helps.

going into the asset model shows the picture fine (and I can also delete and re-upload it, so permissions work fine)
but the assets itself won't show the pictures
accessing the supposed broken link "http://snipe-it/uploads/models/xyz.jpg" directly works fine

edit: I updated using the php upgrade.php script

**Comment by snipe** [comment]
@pascal-ts Please open a new issue for this - this issue is stale, as it’s over a year old, and whatever was the issue here is unlikely to be the issue for you.
