### ISSUE TITLE
Incorrect error message on login

### ISSUE THREAD

**Issue by codeasashu** [snipe/snipe-it#6954]
One of admins of my company ended up updating personal details with "This user can login" unchecked.

When trying to login, the error message he is getting is:

> Incorrect username or password

This made him send out couple of "reset-password" requests, which did no good obviously.

Expected:
The error message should say something along the lines of:

> Your login has been disabled by administrator

This will help prevent extra reset password mails and ofcourse us developers pulling their hairs out for 2 hours figuring out where the hell everything went wrong

**Comment by snipe** [comment]
We choose not to disclose more specific error messages so as to prevent attackers from learning whether a login/username is actually valid or not. It's the same reason we don't tell you whether the username or the password is incorrect.
