### ISSUE TITLE
Composer error when running install.sh script on Debian 9.8

### ISSUE THREAD

**Issue by wtc-jeff** [snipe/snipe-it#6957]
Hi there,

I am trying to install Snipe IT on a new install of Debian 9.8 and getting an error with Composer, I am following the instructions found at https://snipe-it.readme.io/docs/downloading section 3.

I searched the previous issues and ran across this link but it does not have a resolution: https://github.com/snipe/snipe-it/issues/6003

Looking over the Installation/Upgrade Issues page at https://snipe-it.readme.io/docs/installation-issues does not guide me to any solutions.

---

snipeit:~# wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh
--2019-04-26 10:34:54--  https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.124.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.124.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 371 [text/plain]
Saving to: ‘install.sh’

install.sh                           100%[===================================================================>]     371  --.-KB/s    in 0s      

2019-04-26 10:34:55 (10.5 MB/s) - ‘install.sh’ saved [371/371]
snipeit:~# chmod 744 install.sh 
snipeit:~# ./install.sh 
--2019-04-26 10:35:56--  https://raw.githubusercontent.com/snipe/snipe-it/master/snipeit.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.124.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.124.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21737 (21K) [text/plain]
Saving to: ‘snipeit.sh’

snipeit.sh                           100%[===================================================================>]  21.23K  --.-KB/s    in 0.004s  

2019-04-26 10:35:56 (5.37 MB/s) - ‘snipeit.sh’ saved [21737/21737]

       _____       _                  __________
      / ___/____  (_)___  ___        /  _/_  __/
      \__ \/ __ \/ / __ \/ _ \______ / /  / /
     ___/ / / / / / /_/ /  __/_____// /  / /
    /____/_/ /_/_/ .___/\___/     /___/ /_/
                /_/

  Welcome to Snipe-IT Inventory Installer for CentOS, Fedora, Debian and Ubuntu!

  The installer has detected Debian version 9.8 codename stretch.
  Q. What is the FQDN of your server? (snipeit.is.wtcnet.ca): 
     Setting to snipeit.is.wtcnet.ca

  Q. Do you want to automatically create the database user password? (y/n) n
  Q. What do you want your snipeit user password to be?
* Adding PHP repository.
* Updating installed packages./
* Installing Apache httpd, PHP, MariaDB and other requirements.
  * Installing mariadb-server
  * Installing mariadb-client
  * Installing apache2
  * Installing libapache2-mod-php7.1
  * Installing php7.1
  * Installing php7.1-mcrypt
  * Installing php7.1-curl
  * Installing php7.1-mysql
  * Installing php7.1-gd
  * Installing php7.1-ldap
  * Installing php7.1-zip
  * Installing php7.1-mbstring
  * Installing php7.1-xml
  * Installing php7.1-bcmath
  * Installing curl
  * Installing git
  * Installing unzip
* Configuring Apache.
* Setting up hosts file.
* Securing MariaDB.

NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MariaDB
      SERVERS IN PRODUCTION USE!  PLEASE READ EACH STEP CAREFULLY!

In order to log into MariaDB to secure it, we'll need the current
password for the root user.  If you've just installed MariaDB, and
you haven't set the root password yet, the password will be blank,
so you should just press enter here.

Enter current password for root (enter for none): 
OK, successfully used password, moving on...

Setting the root password ensures that nobody can log into the MariaDB
root user without the proper authorisation.

Set root password? [Y/n] Y
New password: 
Re-enter new password: 
Password updated successfully!
Reloading privilege tables..
 ... Success!

By default, a MariaDB installation has an anonymous user, allowing anyone
to log into MariaDB without having to have a user account created for
them.  This is intended only for testing, and to make the installation
go a bit smoother.  You should remove them before moving into a
production environment.

Remove anonymous users? [Y/n] 
 ... Success!

Normally, root should only be allowed to connect from 'localhost'.  This
ensures that someone cannot guess at the root password from the network.

Disallow root login remotely? [Y/n] 
 ... Success!

By default, MariaDB comes with a database named 'test' that anyone can
access.  This is also intended only for testing, and should be removed
before moving into a production environment.

Remove test database and access to it? [Y/n] 
 - Dropping test database...
 ... Success!
 - Removing privileges on test database...
 ... Success!

Reloading the privilege tables will ensure that all changes made so far
will take effect immediately.

Reload privilege tables now? [Y/n] 
 ... Success!

Cleaning up...

All done!  If you've completed all of the above steps, your MariaDB
installation should now be secure.

Thanks for using MariaDB!
* Creating Snipe-IT user.
* Creating MariaDB Database/User.
* Please Input your MariaDB root password:
Enter password: 
* Cloning Snipe-IT from github to the web directory.
* Configuring .env file.
* Installing composer.
su: invalid option -- 'r'
Usage: su [options] [LOGIN]

Options:
  -c, --command COMMAND         pass COMMAND to the invoked shell
  -h, --help                    display this help message and exit
  -, -l, --login                make the shell a login shell
  -m, -p,
  --preserve-environment        do not reset environment variables, and
                                keep the same shell
  -s, --shell SHELL             use SHELL instead of the default in passwd

su: invalid option -- 'r'
Usage: su [options] [LOGIN]

Options:
  -c, --command COMMAND         pass COMMAND to the invoked shell
  -h, --help                    display this help message and exit
  -, -l, --login                make the shell a login shell
  -m, -p,
  --preserve-environment        do not reset environment variables, and
                                keep the same shell
  -s, --shell SHELL             use SHELL instead of the default in passwd

ERROR: Invalid composer installer signature
No passwd entry for user 'composer-setup.php'
snipeit:~# 

---

Thanks

Jeff

**Comment by wtc-jeff** [comment]
Did a bit of digging and found that I needed sudo installed (we don't use sudo, just su) to properly run the composer install.  

After running 

> apt-get install sudo

The installer worked as expected.

Jeff

**Comment by EarlRamirez** [comment]
@wtc-jeff, can you close the issue since your issue is resolved, please.
