### ISSUE TITLE
Alerts related to license expiration do not work, other alerts work and send email properly

### ISSUE THREAD

**Issue by giuseppech** [snipe/snipe-it#6959]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

I receive email alerts related to anything except license expiration. I added some dummy license and even if I use "php artisan snipeit:expiring-alerts" command it doesn't work and the shell output is empty (returns the prompt).

**To Reproduce**

Snipe-It is installed on Linux, open a 'root' shell and issue the following commands:
1) cd /var/www/snipe-it
2) php artisan snipeit:expiring-alerts

The result is the shell prompt only and NO email sent. On the other hand if I issue 

3.a) php artisan snipeit:expected-checkin

or

3.b) php artisan snipeit:inventory-alerts

I get a proper response on the terminal and email.

**Expected behavior**

I expect to get email alerts for expiring licenses in the same way I get for expected check-ins and inventory low quantities. This is a fresh install, email alerts for expiring licenses never worked.

**Screenshots**

Screenshot of the above commands attached.

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.13 build 3985 (g5f3147cf3)
 - OS: CentOS Linux release 7.6.1810 (Core)
 - Web Server: Apache/2.4.6 (CentOS)
 - PHP Version | 5.6.40
 - Laravel Version | 5.4.35

**Desktop (please complete the following information):**
 
NOT RELEVANT

**Smartphone (please complete the following information):**

NOT RELEVANT

**Error Messages**

No error messages in console when I issue the command, just prompt:

[root@snipeit snipe-it]# php artisan snipeit:expiring-alerts
[root@snipeit snipe-it]#

No errors in /storage/logs/laravel.log

**Additional context**
- Is this a fresh install or an upgrade? 
fresh

- What OS and web server you're running Snipe-IT on
Centos and Apache as detailed above

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual  installation

- Include what you've done so far in the installation, and if you got any error messages along the way.
The installation is complete, the software working, the email alert working for everithing except license expiration

- Indicate whether or not you've manually edited any data directly in the database
none

![snipeit-email-alerts-for-licenses-not-working](https://user-images.githubusercontent.com/50026840/56824628-517b7680-6857-11e9-9bd6-791e3e9fc750.png)

**Comment by EarlRamirez** [comment]
@giuseppech, a few questions, is the expiration date of the licence set? If yes, how many days before the licence expires? These are a couple of reasons why you may not be receiving email alerts for expiring licence.

**Comment by giuseppech** [comment]
![snipeit-licenses-expiration](https://user-images.githubusercontent.com/50026840/56852760-5572cb80-691f-11e9-831c-a0d9607db460.png)

Thank you for replying, I attached just a small snippet of the licenses loaded.

As you can see there are many different dates.

How can I test the functionality? What data should insert?

**Comment by giuseppech** [comment]
Is there a way to debug "php artisan snipeit:expiring-alerts"?

**Comment by giuseppech** [comment]
@EarlRamirez Is there a way to debug "php artisan snipeit:expiring-alerts"?

**Comment by giuseppech** [comment]
@EarlRamirez what else can I do to find help?

**Comment by snipe** [comment]
1) Do you have an alerts email set in your Admin Settings > Notifications?
2) Are your alerts enabled in your Admin Settings > Notifications?
3) What is your Expiring Alerts Threshold in Admin Settings > Notifications?

**Comment by giuseppech** [comment]
>     1. Do you have an alerts email set in your Admin Settings > Notifications?

Yes (I receive other alerts)

>     2. Are your alerts enabled in your Admin Settings > Notifications?

Yes (I receive other alerts)

>     3. What is your Expiring Alerts Threshold in Admin Settings > Notifications?

The default values are 30 for expiring alerts, and 5 for inventory alerts.

I attach a screenshot.

@EarlRamirez how can I further troubleshoot my issue with expiring license alerts?

![Admin-notification](https://user-images.githubusercontent.com/50026840/57183681-c7638b80-6eb0-11e9-9930-dfba1966c99f.png)

**Comment by giuseppech** [comment]
@snipe I replyed above but tagged the wrong person.

How can I further troubleshoot my issue with expiring license alerts?

**Comment by snipe** [comment]
I don't see any licenses in that list that meet the criteria for an alert to fire though. You posted on April 27, and there's a 30-day threshold. The only licenses that aren't already expired is one far enough in the future that it wouldn't trigger an alert.

**Comment by giuseppech** [comment]
> 
> 
> I don't see any licenses in that list that meet the criteria for an alert to fire though. You posted on April 27, and there's a 30-day threshold. The only licenses that aren't already expired is one far enough in the future that it wouldn't trigger an alert.

@snipe so you are saying that 

1) the license alert is is triggered ONLY if the license expiration is exactly 30 days ahead?

2) anything shorter is ignored?

**Comment by snipe** [comment]
No, of course not - but if it's already expired, it won't be in the report. The only future-expiring licenses you have expire in July, and with a 30 day threshold, they wouldn't be included, because `July > (now + 30 days)`

**Comment by giuseppech** [comment]
> 
> 
> No, of course not - but if it's already expired, it won't be in the report. The only future-expiring licenses you have expire in July, and with a 30 day threshold, they wouldn't be included, because `July > (now + 30 days)`

Thanks @snipe tomorrow I will do some extensive testing and report back.

**Comment by giuseppech** [comment]
We have done some testing and yes, everything works like the last message from @snipe 

Closing the issue and thanks for the support.

**Comment by coriander222** [comment]
> We have done some testing and yes, everything works like the last message from @snipe

how did u solve this issue bro got same problem with the command php artisan snipeit:expiring-alerts not showing any information?

**Comment by Manunga** [comment]
how did u solve this issue bro got same problem with the command php artisan snipeit:expiring-alerts not showing any information?

**Comment by byu-syste** [comment]
how did u solve this issue bro got same problem with the command php artisan snipeit:expiring-alerts not showing any information?
