### ISSUE TITLE
Add an option to make some Common Fields required

### ISSUE THREAD

**Issue by jfbarthe-sls** [snipe/snipe-it#6960]
**Server :**
 - Snipe-IT Version 4.6.14
 - OS: Ubuntu 16.04
 - Web Server: Apache
 - PHP Version 7.0

**Is your feature request related to a problem? Please describe.**
When printing labels, the asset name is important for us to be listed. We print the labels in batch at the end of the month. Without asset name it is hard to identify which label goes wich asset.

**Describe the solution you'd like**
If we could have a way in the Admin settings to choose what fields are required or not would allow us to add the asset name as a mandatory field when creating a new asset. 

**Describe alternatives you've considered**
Coding this myself or adding a fake required CSS label for the field.

**Additional context**
This does not necessarily need to be true for bulk upload.

**Comment by EarlRamirez** [comment]
@jfbarthe-sls, there's already an option to make a custom field required; however, the option is only available at the custom field set when you are assigning a custom field to a custom field set, as shown in the screenshots below.

![Selection_013](https://user-images.githubusercontent.com/12306859/56849448-f1540580-6926-11e9-9548-f43fedbcee8e.png)
![Selection_012](https://user-images.githubusercontent.com/12306859/56849449-f4e78c80-6926-11e9-8c4c-d7ef87960bdb.png)

Hope this help

**Comment by jfbarthe-sls** [comment]
Regarding this issue of making the Common Fields required, I found the solution.
In [Assets.php](https://github.com/snipe/snipe-it/blob/master/app/Models/Asset.php), starting at line 73, the protected $rules define each Common Field. To make a field required, simply add required :
`'name'            => 'required|max:255|nullable',`

**Comment by snipe** [comment]
@jfbarthe-sls that's of course always an option, but it can become difficult to keep locally changed versions at parity with all of our changes over time.

**Comment by viclou** [comment]
+ FD requests
