### ISSUE TITLE
Checkout accessories via rest API

### ISSUE THREAD

**Issue by vovaled** [snipe/snipe-it#6963]
Sorry if I missed it somewhere in the issues or documentation, but is there an option to check out accessories to a user? If yes it will be great if someone can share it with me. 
So far I found the only option to check out is assets/hardware.

If there is no such option, is it expected to be released? If yes any estimated time?

**Comment by vovaled** [comment]
Any help on this one?

**Comment by sw-mreyes** [comment]
I did a PR for that feature a while ago - if you need that functionality I created a patched [branch](https://github.com/sw-mreyes/snipe-it/tree/v4.6.15-PATCH) for v.4.6.15 that contains the accessory and component checkin & checkout routes.

**Comment by vovaled** [comment]
> I did a PR for that feature a while ago - if you need that functionality I created a patched [branch](https://github.com/sw-mreyes/snipe-it/tree/v4.6.15-PATCH) for v.4.6.15 that contains the accessory and component checkin & checkout routes.

Thanks for sharing, will give it a try. 
Did you get any reply regarding your request?
