### ISSUE TITLE
Restrict Access to specific company through groups

### ISSUE THREAD

**Issue by HSoeren** [snipe/snipe-it#6964]
**Server (please complete the following information):**
 - Snipe-IT Version v4.6.15 build 4011
 - OS: CentOS
 - Web Server: [e.g. Apache, IIS] Nginx
 - PHP Version 7.0

**Is your feature request related to a problem? Please describe.**
We work for schools and also do their inventory stuff. As the guys from the school want to access the system and we aren't able to restrict their access only to their group we have to host multiple snipe IT Systems to get every school a seperate system. 

**Describe the solution you'd like**
We think it would be easier if I could enable a restriction for one or two specific companys (relating to the first question in every Asset Creation) in the groups edit menu. So could some users only access the inventory of their assets
This might be also interesting for companies as you could restrict the access to departments if you want.

**Describe alternatives you've considered**
Just as now: Hosting multiple Snipe IT Instances

**Additional context**
-

**Comment by snipe** [comment]
Does [Full Multiple Company Support](https://snipe-it.readme.io/docs/general-settings#section-full-multiple-companies-support) not handle this need for you?
