### ISSUE TITLE
Reykey from legacy (3.6.1) to current fails reporting unsupported cypher.

### ISSUE THREAD

**Issue by houninym** [snipe/snipe-it#6966]
#### Expected Behavior (or desired behavior if a feature request)

That the command php artisan snipeit:legacy-recrypt completes and re-encrypts data in the (ex) version 3 database to version 4 encryption standard

-----

#### Actual Behavior

The command php artisan snipeit:legacy-recrypt  fails with an error message telling me the only supported ciphers are as below. Session traffic for the command is below.

www-data@wikinew:/usr/share/snipe-it$ php artisan snipeit:legacy-recrypt
INFO: Your LEGACY_APP_KEY looks correct. Okay to continue.
================================!!!! WARNING !!!!================================
================================!!!! WARNING !!!!================================
This tool will attempt to decrypt your old Snipe-IT (mcrypt, now deprecated) encrypted data and re-encrypt it using OpenSSL.

You should only continue if you have backed up any and all old APP_KEYs and have backed up your data.

 Are you SURE you wish to continue? (yes/no) [no]:
 > yes

In McryptEncrypter.php line 48:

  The only supported ciphers are MCRYPT_RIJNDAEL_128 and MCRYPT_RIJNDAEL_256.

-----

#### Please confirm you have done the following before posting your bug report:

- [y ] I have enabled debug mode 
- [y ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh install on a new server, porting database from an older platform (snipe-it 3.6.4 build 12)
- Version of Snipe-IT you're running: 4.6.15 build 4011
- Version of PHP you're running: php7.0 (7.0.33-0ubuntu0)
- Version of MySQL/MariaDB you're running:10.0.38
- What OS and web server you're running Snipe-IT on: Ubuntu16.04, nginx 1.16.0-1
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) git pull
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error: No error in browser, error occurs on command line
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error: Command line issue, not using browser
- If a stacktrace is provided in the error, include that too.

Out of the storage/logs/laravel.log file:
[2019-04-29 10:07:37] production.ERROR: RuntimeException: The only supported ciphers are MCRYPT_RIJNDAEL_128 and MCRYPT_RIJNDAEL_256. in /usr/share/snipe-it/app/LegacyEncrypter/McryptEncrypter.php:48
Stack trace:
#0 /usr/share/snipe-it/app/Console/Commands/RecryptFromMcrypt.php(100): App\LegacyEncrypter\McryptEncrypter->__construct('USSulJsBCtIor6p...', 'rijndael-256')
#1 [internal function]: App\Console\Commands\RecryptFromMcrypt->handle()
#2 /usr/share/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#3 /usr/share/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 /usr/share/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#5 /usr/share/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(539): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#6 /usr/share/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\Container\Container->call(Array)
#7 /usr/share/snipe-it/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#8 /usr/share/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Command.php(167): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#9 /usr/share/snipe-it/vendor/symfony/console/Application.php(960): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /usr/share/snipe-it/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\RecryptFromMcrypt), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /usr/share/snipe-it/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /usr/share/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(122): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /usr/share/snipe-it/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

- Any errors that appear in your browser's error console: N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo :N/A
- Include any additional information you can find in `storage/logs` and your webserver's logs. See above for storage.log, webserver not involved.
- Include what you've done so far in the installation, and if you got any error messages along the way.
Following the instructions at https://snipe-it.readme.io/docs/upgrading-to-v4, followed instructions in Step 10.

The .env file contains the following:
# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=true
APP_KEY=base64:pk+<redacted>
LEGACY_APP_KEY=USS<redacted>
LEGACY_CIPHER=rijndael-256
APP_URL=https://snipe-new.<redacted>
APP_TIMEZONE='UTC'
APP_LOCALE=en-GB

- Indicate whether or not you've manually edited any data directly in the database. Not edited the database manually, just run the 'php artisan migrate' command to migrate the data from old to new structure.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Do you have encrypted custom fields?

**Comment by houninym** [comment]
At the time I raised the ticket I was not sure - it's not my data - but as the data owner says it's all working for him it appears likely that there are no encrypted custom fields.ThanksMatthew On 16 May 2019 at 03:03 snipe <notifications@github.com> wrote:  Do you have encrypted custom fields?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by 101Lizardman** [comment]
Hi!
I am encountering the same error. I am upgrading from v3 -> v4 and have encrypted custom fields. Any idea for a workaround?

**Comment by scortoise** [comment]
Having same issue. Upgraded successfully from v3 to v4, but the recrypter tells me that only MCRYPT_RIJNDAEL_128 and MCRYPT_RIJNDAEL_256 are supported whenever it is run. 

I have a backup of the old v3 install and the app config has rijndael-256 specified as the APP_CIPHER, and the new config has the old app key and legacy cipher set. 

When I open an asset with an encrypted custom field, I just get 'error decrypting: the payload is invalid', presumably because the fields are still encrypted via mcrypt instead of OpenSSL.
