### ISSUE TITLE
asset list all not displaying anything

### ISSUE THREAD

**Issue by windblade89** [snipe/snipe-it#6967]
#### Please confirm you have done the following before posting your bug report:

- [y ] I have enabled debug mode 
- [y ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**
1. Go to 'Assets'
2. Click on 'List All'
3. Scroll down to 'No items'

**Expected behavior**
Expecting it to show the Asset List of. But it's not showing anything.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.7 build 3944 (g8f6ea84fc)
 - OS: [e.g. Ubuntu, CentOS] Ubuntu Server 
![Snipe-IT Error](https://user-images.githubusercontent.com/43204460/56895149-7145b100-6a88-11e9-9414-8b75cb8d8a54.PNG)

 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.2.17-1+ 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]Windows 10
 - Browser [e.g. chrome, safari]Chrome
 - Version [e.g. 22] 74.0.3729.108

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
date_interval_create_from_date_string(): Unknown or bad format ( months) at position 0 (m): The timezone could not be found in the database
/home/snipe-it/public_html/app/Presenters/AssetPresenter.php#396
ErrorException
-api/v1/hardware?status=&order_number=&company_id=&status_id=&sort=name&order=asc&offset=0&limit=100:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by MrDarkfire** [comment]
I am having the same issue as this user.

**Comment by cdcs68** [comment]
Hi,
Did this occur after an upgrade?  If not, what changed? 
I'm using Windows Server 2016; however, I did a Google search and found this link that may be helpful to you both:   https://github.com/snipe/snipe-it/issues/6887

Read through them to see if anything is applicable to your situation.  In summary, it appears that the EOL field needs to be set to something besides being blank or NULL.  At the bottom of the link I included it shows that someone was successful setting the EOL field to 0 (zero).

I hope this helps.

**Comment by windblade89** [comment]
All my EOL field's are 0 so tried making it 1 but still not showing up. Only way something shows up now, Is if I manually search for the name. I'm using Ubuntu Server.

**Comment by ccastonguay** [comment]
Im  running Ubuntu, same issue occurred just recently.  I am only able to find Assets under one of my categories on search.  Unable to find deployed assets, just ready to deploy.

v4.6.15 build 4011 (gd1e9fbfa2)  php 7.2.17-0ubuntu0.18.10.1

**Comment by cdcs68** [comment]
@windblade89 
Did this problem occur after an upgrade?   Prior  to submitting your problem to GitHub when did it last work?  Just to rule out oddities, try opening Snipe It from a different browser.
Making sure you first have a good backup, consider the steps below taking from the **Common Issues** page (I've used these commands below to help with several different issues):  **https://snipe-it.readme.io/docs/common-issues**

composer dump-autoload
composer clear-compiled
php artisan config:clear
php artisan view:clear
php artisan cache:clear
php artisan route:clear
These commands clear out cached service files that help speed up modern PHP applications but can also very occasionally be out of date, resulting in odd errors. T**hese caches will be regenerated normally, so they can be cleared without repercussion.** (You can also run php update.php from the Snipe-IT project directory to run these commands and other helpful clean-up commands all at once.)

@ccastonguay  You can try the above steps too.
I hope this helps.

**Comment by ccastonguay** [comment]
Thank you @cdcs68 Fixed #6922 - date_add crashing if EOL is null i found this article which helped resolve the issue i was having.

**Comment by cdcs68** [comment]
@ccastonguay  Ok, that's great news!!!  Thanks for sharing the link.
