### ISSUE TITLE
Save view

### ISSUE THREAD

**Issue by pinguin222** [snipe/snipe-it#6972]
Hello,

is it possible to save the view?
I removed columns that I don't need, but every time I log on Snipe-IT, the standard view is back.

**Comment by ajsy** [comment]
same here

**Comment by cdcs68** [comment]
My installing is on Windows Server 2016 (have LDAP connected) and we are on version 4.6.15 Build 4011.  My selections stays in the All Assets screen.  I did have to widen my adjust my browser window which wasn't initially obvious to  me.  I have logged off, closed the browser (I'm using Chrome) and logged back in and my selections remain.

Hope this is helpful.

**Comment by snipe** [comment]
The selected columns are stored in a browser cookie.
