### ISSUE TITLE
Cache and cookie delete results in Error 500

### ISSUE THREAD

**Issue by MacCaloway** [snipe/snipe-it#6973]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

Hello,

We have Snipe IT hosted on our servers and we've encountered the problem that we saw nothing on "All Assets", so i cleared the cookies and cache like an old ticket here said so, but now we can't access to anything "500 Error, Whoops, something went wrong on our servers." 

Can you help us please ? Thanks a lot !

**Server (please complete the following information):**

 - Snipe-IT Version 4.6.15
 - OS: Windows Server 2012
 - Web Server: IIS
 - PHP Version 7.3.4.0

**Comment by cdcs68** [comment]
Hi,
Maybe you can try the following.  
Enable debug in the .env file located in the directory c:\inetpub\wwwroot\snipeit
Change it to true.

![image](https://user-images.githubusercontent.com/25690788/57025404-aa069700-6bfc-11e9-8b47-53bc01eefb23.png)

Then log into your Snipe It software.  In addition to seeing Whoops Something Went Wrong, you should see debugging information which will help provide additional information to troubleshoot the problem.

Post those results. 

Good luck.

**Comment by MacCaloway** [comment]
Hi, 
Thanks a lot for your response.

Unfortunately i have nothing in the folder,
![image](https://user-images.githubusercontent.com/50137333/57699013-3da58200-7657-11e9-9af3-e22334a74d5d.png)

I don't know what can i do ..
Thank you

**Comment by cdcs68** [comment]
@MacCaloway 
Hi,
You may have installed snipeit to a different directory.
Search for **snipe** on your c:\ and post a screenshot.
Thanks,
Cameshia

**Comment by MacCaloway** [comment]
Hello,
I finally found it, here's what i got.

It seems that i got a log error but i don't know how to solve it :/

Do you need the environment and details report also ?

Thank you !


 Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Cannot use Log as Log because the name is already in use


 C:\inetpub\wwwroot\app\Http\Controllers\Auth\LoginController.php

    <?php
     
    namespace App\Http\Controllers\Auth;
     
    use App\Http\Controllers\Controller;
    use App\Models\Setting;
    use App\Models\User;
    use App\Services\LdapAd;
    use Illuminate\Foundation\Auth\ThrottlesLogins;
    use Illuminate\Http\Request;
    use Illuminate\Support\Carbon;
    use Illuminate\Support\Facades\Auth;
    use Illuminate\Support\Facades\Input;
    use Illuminate\Support\Facades\Log;
    use Illuminate\Support\Facades\Session;
    use Illuminate\Support\Facades\Validator;
    use Redirect;
    use Log;
    use View;
    use Otp\Otp;
    use Otp\GoogleAuthenticator;
    use ParagonIE\ConstantTime\Encoding;
     
    /**
     * This controller handles authentication for the user, including local
     * database users and LDAP users.
     *
     * @author [A. Gianotto] [<snipe@snipe.net>]
     * @version    v1.0
     */
    class LoginController extends Controller
    {
     
        use ThrottlesLogins;
     
        // This tells the auth controller to use username instead of email address
        protected $username = 'username';
     
        /**
         * Where to redirect users after login / registration.

Arguments

    "Cannot use Log as Log because the name is already in use"

**Comment by cdcs68** [comment]
@MacCaloway 
Hi, I'm not familiar with the problem.  This is what I found on the internet: 
**Make sure you have a backup of your LoginController.php file.**

Remove the "app/Http/Controllers" from your classmap.
Add namespace App\Http\Controllers; above your use blocks.
Then run composer dump-auto

Here's the link (this info is in the middle of the website):  https://stackoverflow.com/questions/40406418/cannot-declare-class-controller-because-the-name-is-already-in-use

I hope this helps!
Cameshia

**Comment by snipe** [comment]
Try removing ` use Illuminate\Support\Facades\Log;` from that file.

**Comment by MacCaloway** [comment]
Hi guys,

Removing "use Illuminate\Support\Facades\Log;" from the file "LoginController.php" worked perfectly !

Thanks you sooo much !!!!
