### ISSUE TITLE
Tab For Monthly/annual Subscription and charges.

### ISSUE THREAD

**Issue by Liel4494** [snipe/snipe-it#6977]
**Server (please complete the following information):**
 - Snipe-IT Version v4.6.15
 - OS:  CentOS
 - Web Server: Apache
 - PHP Version  7.1.28

**Is your feature request related to a problem? Please describe.**
Licenses tab is great, but its possible to enter just one time purchases(like office serial key,windows 10 key...)
every company(!) have subscription to services that charge her monthly,(google G-suite,amazon,office 365...),and its not covered by licenses feature.

**Describe the solution you'd like**
create new tab that will be called "Bills" or "Subscription" ,and in this tab every one can insert there bills,and there is option to select if the charge is monthly or annual.

**Comment by ajsy** [comment]
good idea for cloud subscriptions
