### ISSUE TITLE
.Env Edit permission denied 

### ISSUE THREAD

**Issue by AMG-90** [snipe/snipe-it#6978]
Hey there i was installing snipe it server at the past and i want to make some changes in the smtp but i cant edit env file i got permission denied any suggestion how should i edit this file ?

**Comment by EarlRamirez** [comment]
Who is the owner of the file, try *sudo -u 'file_owner' vim path/to/.env.

**Comment by AMG-90** [comment]
works thanks a loot

**Comment by EarlRamirez** [comment]
awesome, can you close the issue.
