### ISSUE TITLE
SMTP Settings 

### ISSUE THREAD

**Issue by AMG-90** [snipe/snipe-it#6979]
Hello i am trying to set new smtp by sendgrid  its works for me in the same configuration in a lot of machine but in the snipe it it writes me  Mail could not be sent.

how i can diagnose what i am missing or debug it ? 
in addition do i need to edit anything else instead of the .env file

**Comment by AMG-90** [comment]
Error: undefined

**Comment by acox216** [comment]
You should only need to edit the .env file. Can you share your SMTP settings (without the password, etc) from the .env? 

We also need to know the Snipe-IT version, OS and web server you're using to better assist.

**Comment by snipe** [comment]
The issue template you deleted before posting your issue here gave you the instructions on how to troubleshoot, and what information we need to be able to assist you.

[According to the Sendgrid documentation](https://sendgrid.com/docs/for-developers/sending-email/laravel/), your SMTP settings should look something like this:

```
MAIL_DRIVER=smtp
MAIL_HOST=smtp.sendgrid.net
MAIL_PORT=587
MAIL_USERNAME=sendgrid_username
MAIL_PASSWORD=sendgrid_password
MAIL_ENCRYPTION=tls
MAIL_FROM_NAME="John Smith"
MAIL_FROM_ADDRESS=from@example.com
```

**Comment by yanagha** [comment]
Hi, 

I have the same problem with gmail. After updating to the latest version Version v4.9.4 - build 4437 (master) it doesn't send emails.
 I am getting Mail could not be sent. Error: undefined message 

MAIL_DRIVER=smtp
MAIL_HOST=smtp-relay.gmail.com
MAIL_PORT=587
MAIL_USERNAME=asset@mydomain.com
MAIL_PASSWORD=mypassword
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDR=asset@mydomain
MAIL_FROM_NAME='Snipe-IT'
MAIL_REPLYTO_ADDR=it-staff@mydomain.com
MAIL_REPLYTO_NAME='IT Assets Management'

**Comment by mostafaelnaggar2020** [comment]
Hi,

I have the same problem with gmail. After updating to the latest version Version v4.9.4 - build 4437 (master) it doesn't send emails.
I am getting Mail could not be sent. Error: undefined message

**Comment by acox216** [comment]
@mostafaelnaggar2020 @yanagha You should try some of the suggestions on this issue #8231

**Comment by yanagha** [comment]
Thank you, the issue is fixed. I have added server IP address in Gsuite SMTP relay settings page and activated less secure apps option in gmail account settings.
