### ISSUE TITLE
No matching records found on All Asset Page

### ISSUE THREAD

**Issue by mqnsupport** [snipe/snipe-it#6980]
#### Expected Behavior (or desired behavior if a feature request)

Dislpay all assests created
-----

#### Actual Behavior

Displays nothing. Cant search

-----

#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  Fresh
- Version of Snipe-IT you're running  v4.6.15
- Version of PHP you're running PHP version: 7.2.7 
- Version of MySQL/MariaDB you're running 5.6.43 - MySQL Community Server (GPL) 
- What OS and web server you're running Snipe-IT on - Centos
- What method you used to install Snipe-IT (cPanel)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error no
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error /public/hardware
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. no
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. no
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
[laravel.log](https://github.com/snipe/snipe-it/files/3138453/laravel.log)

- Indicate whether or not you've manually edited any data directly in the database no

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Try upgrading to latest
