### ISSUE TITLE
Can i GET account/api ?

### ISSUE THREAD

**Issue by Milansu** [snipe/snipe-it#6983]
- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I want to know if its possible to make a GET request for route account/api. Which contains names for API keys. I've tried bunch of different routes and I didn't see it in documentation.

**Error message I get:**
{
    "status": "error",
    "messages": "An Error has occured! Unauthenticated.",
    "payload": null
}

**Comment by snipe** [comment]
You'd want to look at the framework's underlying support for API routes: https://laravel.com/docs/5.4/passport#requesting-password-grant-tokens
https://laravel.com/docs/5.4/passport#client-credentials-grant-tokens
