### ISSUE TITLE
Import locations in bulk

### ISSUE THREAD

**Issue by anmol26s** [snipe/snipe-it#6984]
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**
Ability to import locations in bulk.

**Comment by anmol26s** [comment]
I want to import location address and location name in bulk.  The parent location can be selected after the bulk import.
Is there a way to achieve this?

**Comment by snipe** [comment]
Please upgrade to latest. https://snipe-it.readme.io/docs/importing-locations
