### ISSUE TITLE
Behind HTTP proxy installation failure - Ubuntu 18.04.2

### ISSUE THREAD

**Issue by Quinniedid** [snipe/snipe-it#6985]
#### Expected Behavior (or desired behavior if a feature request)

For the install.sh to be completed successfully.
-----

#### Actual Behavior

The script downloads all the needed packages just fine. When we get to "Installing composer" we run into an error:

```
* Installing composer.
PHP Warning:  copy(https://getcomposer.org/installer): failed to open stream: Connection timed out in Command line code on line 1
PHP Warning:  hash_file(composer-setup.php): failed to open stream: No such file or directory in Command line code on line 1
ERROR: Invalid composer installer signature
rm: cannot remove 'composer-setup.php': No such file or directory
```
Proxy is set in /etc/environment as follows:

```
http_proxy=http://ourproxy.domain.net:8080
https_proxy=http://ourproxy.domain.net:8080
ftp_proxy=http://ourproxy.domain.net:8080
```
Obviously replacing with fake DNS names for privacy purposes.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - Fresh install
- Version of Snipe-IT you're running - Just pulled from GitHub so whatever is the latest
- Version of PHP you're running - PHP 7.2.17-0ubuntu0.18.04.1
- Version of MySQL/MariaDB you're running - 10.1.38
- What OS and web server you're running Snipe-IT on - Ubuntu 18.04
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - Not able to, due to it not installing
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Don't get anything that I am aware of
- If a stacktrace is provided in the error, include that too. - N/A
- Any errors that appear in your browser's error console. - N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - N/A
- Include any additional information you can find in `storage/logs` and your webserver's logs. - N/A
- Include what you've done so far in the installation, and if you got any error messages along the way. 
```
Welcome to Snipe-IT Inventory Installer for CentOS, Fedora, Debian and Ubuntu!

  The installer has detected Ubuntu version 18.04 codename bionic.
  Q. What is the FQDN of your server? (asset.mydomain.net):
     Setting to asset.mydomain.net

  Q. Do you want to automatically create the database user password? (y/n) y

* Updating installed packages./
* Installing Apache httpd, PHP, MariaDB and other requirements.
  * Installing mariadb-server
  * Installing mariadb-client
  * Installing apache2
  * Installing libapache2-mod-php
  * Installing php
  * Installing php-mcrypt
  * Installing php-curl
  * Installing php-mysql
  * Installing php-gd
  * Installing php-ldap
  * Installing php-zip
  * Installing php-mbstring
  * Installing php-xml
  * Installing php-bcmath
  * curl already installed
  * git already installed
  * Installing unzip
* Configuring Apache.
* Setting up hosts file.
* Starting MariaDB.
* Securing MariaDB.

NOTE: RUNNING ALL PARTS OF THIS SCRIPT IS RECOMMENDED FOR ALL MariaDB
      SERVERS IN PRODUCTION USE!  PLEASE READ EACH STEP CAREFULLY!

In order to log into MariaDB to secure it, we'll need the current
password for the root user.  If you've just installed MariaDB, and
you haven't set the root password yet, the password will be blank,
so you should just press enter here.

Enter current password for root (enter for none):
OK, successfully used password, moving on...

Setting the root password ensures that nobody can log into the MariaDB
root user without the proper authorisation.

Set root password? [Y/n] y
New password:
Re-enter new password:
Password updated successfully!
Reloading privilege tables..
 ... Success!


By default, a MariaDB installation has an anonymous user, allowing anyone
to log into MariaDB without having to have a user account created for
them.  This is intended only for testing, and to make the installation
go a bit smoother.  You should remove them before moving into a
production environment.

Remove anonymous users? [Y/n] y
 ... Success!

Normally, root should only be allowed to connect from 'localhost'.  This
ensures that someone cannot guess at the root password from the network.

Disallow root login remotely? [Y/n] y
 ... Success!

By default, MariaDB comes with a database named 'test' that anyone can
access.  This is also intended only for testing, and should be removed
before moving into a production environment.

Remove test database and access to it? [Y/n] y
 - Dropping test database...
 ... Success!
 - Removing privileges on test database...
 ... Success!

Reloading the privilege tables will ensure that all changes made so far
will take effect immediately.

Reload privilege tables now? [Y/n] y
 ... Success!

Cleaning up...

All done!  If you've completed all of the above steps, your MariaDB
installation should now be secure.

Thanks for using MariaDB!
* Creating Snipe-IT user.
* Creating MariaDB Database/User.
* Please Input your MariaDB root password:
Enter password:
* Cloning Snipe-IT from github to the web directory.
* Configuring .env file.
```

- Indicate whether or not you've manually edited any data directly in the database - No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by Quinniedid** [comment]
This is still relevant and have not heard anything yet as to what can be done to resolve this issue.

**Comment by Quinniedid** [comment]
This is still relevant and have not heard anything yet as to what can be done to resolve this issue.

**Comment by NightyKnight** [comment]
@Quinniedid 
I feel your pain. 

I just struggled with this and documented everything.

Hopefully it can be of service to you.

The simple answer is edit the install script to use curl instead of php to copy the file. 
See the below gist section 2c for the exact code.

[Install Snipe-IT From Scratch Behind HTTP Proxy](https://gist.github.com/NightyKnight/8aeb9bb87c447e469d2b67b3d9b7a58b#file-install-snipeit-from-scratch)

It might be a little rough, but let me know if I can make any improvements.

-Brad O.

**Comment by Quinniedid** [comment]
@NightyKnight Thank you for providing that information! I am running this on Ubuntu, but was able to translate for the different file locations. I was able to successfully install Snipe-IT. Still had to make some adjustments to the config file as with 18.04, it appears to be an issue with google maps api being left blank that causes a PHP issue. A simple comment out that line and I was up and running.

The one thing that you mentioned in your script about logging, it appears that I am still getting that error even after moving that line to the snipeitapp user. This isn't anything harmful for me but it would be nice to see if the logging issue can be fixed somehow. (2e)
