### ISSUE TITLE
Non-AD LDAP sync makes all users inactive

### ISSUE THREAD

**Issue by JorisVanEijden** [snipe/snipe-it#6987]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
LDAP sync always sets inactive all users, unless an Active Directory server is used.

**To Reproduce**
- Configure Snipe-it to connect to a non-Active Directory LDAP
- LDAP sync to import users
- Enable login (activate) one or more users
- LDAP sync again
- Users are deactivated

The "LDAP Active Flag" has no influence on this behaviour at all.

This line causes all LDAP users to always be deactivated on every LDAP sync:
https://github.com/snipe/snipe-it/blob/25884a893e1f4ce1a7d66a366db726b5e42e976a/app/Console/Commands/LdapSync.php#L181

Commit that broke it:
https://github.com/snipe/snipe-it/commit/966a736602f6f308ef0091d7bbc4bae1abaa7e31

See also https://github.com/snipe/snipe-it/issues/6158

**Expected behavior**
My users can still log on after an LDAP sync.

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.15
 - OS: CentOS
 - Web Server: Apache
 - PHP Version 7.2

**Comment by snipe** [comment]
Try upgrading to latest.
