### ISSUE TITLE
"List All" blank, While "All Ready to Deploy" shows results

### ISSUE THREAD

**Issue by d90** [snipe/snipe-it#6989]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
All Assets shows no results. Any assets that have a status show under their respective status. An example is "All Ready to Deploy" 

**To Reproduce**
1. Go to All Assetts
2. See No results
3. Click on All Ready to Deploy
4. All assets with that status show. 

**Expected behavior**
When i click on "List All" under assetts I expect to see all the assetts in the db. In my case this is 99 assetts

**Screenshots**

![Uploading SnipeIT_ARTD.png…]()

**Server (please complete the following information):**
 - Version v4.6.15 - build 4011 (master)  
 - OS: Docker Alpine Linux
 - Web Server: nginx
 - PHP Version: 7 

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, firefox
 - Version: Latest (non canary)

**Smartphone (please complete the following information):**

**Error Messages**
I have no error messages

**Additional context**
- Fresh Install 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT: Docker
- I've imported a bunch of assetts from csv. I haven't logged for a week. This was working earlier last wee
- Indicate whether or not you've manually edited any data directly in the database: I have not.

**Comment by snipe** [comment]
> I have no error messages

That's unlikely. There will be messages in your browser console, or in your app logs. 

https://snipe-it.readme.io/docs/advanced-debugging

**Comment by snipe** [comment]
Hi there - We haven't heard back in a bit, so I'm going to close this ticket for now, but will re-open it if you're still having issues.

![hackerman-hacking](https://user-images.githubusercontent.com/197404/31936003-27a7f6d8-b865-11e7-8f5e-eb03062925f4.gif)
