### ISSUE TITLE
Can no longer see assets, models, users after upgrade to 1.2.6.1

### ISSUE THREAD

**Issue by bondo05** [snipe/snipe-it#699]
After I ran the latest upgrade which included the 3 commands, the assets, models, and users screens appears blank. The database still contains all the data. I can see my own assigned assets and I am still an admin.

The manufacturers, suppliers, and locations are all visible. If I create a new user, it is added but the user is not visible.

Did I miss a step somewhere during the upgrade? Thanks.

**Comment by madd15** [comment]
The command you ran were as below, yes?
```
php composer.phar install --no-dev 
php composer.phar dump-autoload
php artisan migrate
```

Can you try deleting the contents (just the contents, not the directories themselves) of `app/storage/cache` and `app/storage/views`?

**Comment by bondo05** [comment]
Yes, those are the commands I ran.

Clearing the contents of app/storage/views seems to have done the trick. The cache directory was already empty.

Thanks!

**Comment by madd15** [comment]
Glad its working for you now! :)
