### ISSUE TITLE
Parent/child Departments

### ISSUE THREAD

**Issue by Laoguoguo** [snipe/snipe-it#6991]
**Server (please complete the following information):**
 - Snipe-IT Version ：4.6.15
 - OS: CentOS
 - Web Server: Apache
 - PHP 7.1.28 

How to add secondary departments？
For example, department A is followed by department B, department C and department D.Section e is under section C

and my question is How to add secondary departments？

**Comment by snipe** [comment]
That is not currently possible. Department hierarchy is currently flat, with no parent/child relationship.

**Comment by Laoguoguo** [comment]
> That is not currently possible. Department hierarchy is currently flat, with no parent/child relationship.

Will this feature be added in future releases?
Thanks

**Comment by snipe** [comment]
It’s not on our short term roadmap, but we’d be willing to take a pull request
