### ISSUE TITLE
A few concerns

### ISSUE THREAD

**Issue by rakanriang** [snipe/snipe-it#6993]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.15
 - OS: [e.g. Ubuntu, CentOS]: Windows Server r2 2012
 - Web Server: [e.g. Apache, IIS]: IIS
 - PHP Version: 7.1

**Is your feature request related to a problem? Please describe.**
nil

**Describe the solution you'd like**
- To be able to put in serial numbers into accessories
- To be able to assign individual product key licenses to individual assets/users (for things like - Microsoft office license)
- Custom fields in not just assets. (license, accessories, people)
- See list of last checked in assets.
- Location is not a grabbable field from ldap.

**Describe alternatives you've considered**
Location: Use department as location. Messy for our ad, but do able if there is no alternative. Would prefer using locations for the parent location function though.

**Additional context**
Loving the app so far regardless the issues I’ve faced. Company is interested in getting pro support if there are workarounds to the above concerns or they are features being worked on a near future release.

**Comment by snipe** [comment]
There are github issues open for all of these requests. These features are not available at this time, but may be in future versions.
