### ISSUE TITLE
[FeatureRequest]  check-in questionaire/survey

### ISSUE THREAD

**Issue by azuercher** [snipe/snipe-it#6997]
We are a school district and use Snipe-IT to manage inventory and track equipment assignments for students.    As part of our workflow when an asset is checked it we have a 1 page inspection form that is to be completed manually and then we scan and attached it to the asset as a file.    It would streamline the process if we could do this internally through snipe-it.   During checkin they would be prompted to answer the questions on and the results would be recored with time/date stamp.  Besides our use case this could be used as a survey tool for end users who do self-checkout/self-checkin.
Thanks for your consideration.

**Comment by tankerkiller125** [comment]
I think this is a great idea as many businesses do the same thing for their assets. I could see this being used for not just checks but also maybe a survey of what the user thought about the asset/service.

**Comment by snipe** [comment]
A survey-builder seems a bit out of scope for an asset management system. :-/ Let me chew on this for a bit.

**Comment by azuercher** [comment]
Snipe,
I get that and I understand wanting to keep the scope focused.   What about some way to add API hooks or some way to redirect to a 3rd party tool/form that would let users fill out and then automatically attach that record to the asset?

P.S.  I'm not a programmer so if what I just said doesn't make any sense please ignore it  :)

**Comment by tankerkiller125** [comment]
I think it's still relevant I think @snipe is still chewing on it.
