### ISSUE TITLE
Whoops Error and no log file presented

### ISSUE THREAD

**Issue by adh1851** [snipe/snipe-it#6998]
I just upgraded to the latest version 4.6.15build4011 of Snipe-IT. We are running it on a WAMP server hosted on a 2008 R2 Server. PHP 5.6.35, Laravel 5.4.35, Apache 2.4.33, MySQL 5.7.21 and MariaDB 10.2.14. We had a manual install before and I switched it over to a Git upgrade. Since the upgrade I cannot make changes in the Admin settings area Branding and General Settings.  I get the Whoops error when I save and my settings do not save.  I have also gotten the whoops error when I check in or check out hardware.  With those even though I get the error it at least saves the change.

I have turned on the debug mode but even after that I still do not get anything posted on the whoops page like we would expect. 

I have run the composer dump-autoload, composer clear-compiled, php artisan config:clear, php artisan view:clear, php artisan cache:clear, php artisan route:clear, and php artisan migrate.

This is what i get when i run the PHP artisan migrate
In Connection.php line 647:

  SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name
  'action_logs_target_id_target_type_index' (SQL: alter table `action_logs` a
  dd index `action_logs_target_id_target_type_index`(`target_id`, `target_typ
  e`))

In PDOStatement.php line 107:

  SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name
  'action_logs_target_id_target_type_index'

In PDOStatement.php line 105:

  SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name
  'action_logs_target_id_target_type_index'

I have attached my Laravel.log

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/installation-issues#section-duplicate-key-name-action_logs_target_id_target_type_index

**Comment by adh1851** [comment]
I ran those commands but when I enter the Alter Table commands i just get a line with an arrow in the picture attached.  And nothing happens.  Is there something else i have to do after i enter that command? 
![Capture](https://user-images.githubusercontent.com/50334803/57255731-5d66f580-701a-11e9-84df-d6265330ba0a.JPG)

**Comment by snipe** [comment]
MySQL commands should end in a semi-colon

**Comment by adh1851** [comment]
OK thanks that worked and they ran now, but I am still getting the errors for Duplicate Key name now when i run the migrate. 
![Capture](https://user-images.githubusercontent.com/50334803/57256309-edf20580-701b-11e9-883f-82a985dc718b.JPG)

**Comment by adh1851** [comment]
I tried going through all the commands again and when I run the last two Drop commands I am getting errors that it does not exist
![Capture](https://user-images.githubusercontent.com/50334803/57256507-68228a00-701c-11e9-9077-aba80354fe66.JPG)

**Comment by snipe** [comment]
Well it can't exist and not exist at the same time though.

**Comment by adh1851** [comment]
Well the errors for where it is saying there are duplicates; reference the drop commands that ran successfully and shows that 0 records were affected. The drop commands that say check to make sure they exist are not showing up in the duplicate errors based on the screen shots I sent.  So I agree that we are getting conflicting answers that do not make sense.

**Comment by adh1851** [comment]
I have not heard anything back.  Was just wondering if you had any other ideas on what I should try to resolve this issue.  I am still getting the Whoops page and the above errors when I run those two drop commands.

**Comment by snipe** [comment]
Well, do those indexes exist or not? MySQL can't tell you something exists and doesn't at the same time. Drop them if they exist and re-run migrations. If they don't exist and you're getting the same duplicate key error, make doubly sure you're running those mysql commands on the right database.

**Comment by adh1851** [comment]
So strange.  I went through and ran the Migrate again and now it went through completely fine and the issues appear to not be happening now.  Thanks so much for all your help.

**Comment by snipe** [comment]
Glad you're sorted!
