### ISSUE TITLE
Unable to  take report of Assessories,Components,Consumable Items

### ISSUE THREAD

**Issue by arun767** [snipe/snipe-it#7000]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Not able to see options to get report of Assessories,Components,Consumable Items

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-4.6.15 
 - OS: Ubuntu 16.04
 - Web Server: Apache, IIS
 - PHP Version 7.0

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
You have not provided us enough information to proceed. Is this a feature request or a bug report?

**Comment by arun767** [comment]
I was trying to export the complete report. i have some asseccories and components which i have checked out but i am not able to see any option to generate the report for the asseccories and components. i am able to generate asset reports  .

**Comment by snipe** [comment]
That's not currently an option, outside of using the export features built into the table displays.
