### ISSUE TITLE
ERR_INVALID_RESPONSE when creating a custom asset report ticking "Warranty"

### ISSUE THREAD

**Issue by boingball** [snipe/snipe-it#7003]
#### Please confirm you have done the following before posting your bug report:

- [ Yes] I have enabled debug mode 
- [ Yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When trying to do a custom report - selecting the Warranty tick box and pressing generate gives the error 
This site can’t be reached The web page at http://snipeitserver/reports/custom might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

If I don't export with the warranty option ticked the custom asset report generates fine. 
I have 1300 assets most of them have the warranty set to 36 months - the reset blank.

**To Reproduce**
1. Go to 'Reports'
2. Click on 'Custom Asset Report'
3. Scroll down to 'Generate'
4. Error ERR_INVALID_RESPONSE is shown in Chrome, Internet Explorer try's to download a file called custom 1.45Kb and says it can't download the file

**Expected behavior**
The custom-assets-reports generates with the warranty field selected

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version Version v4.6.16 - build 4018 (features/6204_email_audit-alerts)
 - OS:  Ubuntu
 - Web Server: Apache
 - PHP Version : 7.2.17-0ubuntu0.18.03.1 (cli)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version Version 73.0.3683.103

**Error Messages**
Debug Log files shows this - don't know if it's relevant but mentions months - I wonder if the imported data I've put in somehow has a bad month format?
[2019-05-07 16:40:38] production.ERROR: ErrorException: date_interval_create_from_date_string(): Unknown or bad format ( months) at position 0 (m): The timezone could not be found in the database in /var/www/snipe-it/app/Presenters/AssetPresenter.php:496
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'date_interval_c...', '/var/www/snipe-...', 496, Array)
#1 /var/www/snipe-it/app/Presenters/AssetPresenter.php(496): date_interval_create_from_date_string(' months')
#2 /var/www/snipe-it/app/Http/Controllers/ReportsController.php(652): App\Presenters\AssetPresenter->warrantee_expires()
#3 /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(39): App\Http\Controllers\ReportsController->App\Http\Controllers\{closure}(Object(Illuminate\Database\Eloquent\Collection))
#4 /var/www/snipe-it/app/Http/Controllers/ReportsController.php(699): Illuminate\Database\Eloquent\Builder->chunk(500, Object(Closure))
#5 /var/www/snipe-it/vendor/symfony/http-foundation/StreamedResponse.php(114): App\Http\Controllers\ReportsController->App\Http\Controllers\{closure}()
#6 /var/www/snipe-it/vendor/symfony/http-foundation/Response.php(374): Symfony\Component\HttpFoundation\StreamedResponse->sendContent()
#7 /var/www/snipe-it/public/index.php(61): Symfony\Component\HttpFoundation\Response->send()
#8 {main}  
error

**Additional context**
- Is this a fresh install or an upgrade? - Upgrading via GIT since Jan install
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install script
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
Only used Import files

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Latest should already have the patch for that in there, so I'm a little confused. This is an artifact (I think) of having null dates as EOL/warranty. I'm not sure why that suddenly changed, as we haven't made any changes to EOL/warranty in some time.

In `/var/www/snipe-it/app/Presenters/AssetPresenter.php` try changing:

```
public function warrantee_expires()
    {
        $date = date_create($this->purchase_date);
        date_add($date, date_interval_create_from_date_string($this->warranty_months . ' months'));
        return date_format($date, 'Y-m-d');
    }
```

to:

```
    public function warrantee_expires()
    {
        if (($this->purchase_date) && ($this->warranty_months)) {
            $date = date_create($this->purchase_date);
            date_add($date, date_interval_create_from_date_string($this->warranty_months . ' months'));
            return date_format($date, 'Y-m-d');
        }
    }
```

and let me know if that helps.

**Comment by snipe** [comment]
(I feel like something must have changed in a version of PHP/MySQL/something - our hosted platform isn't seeing these issues, but some of our open source users are.)

**Comment by boingball** [comment]
> Latest should already have the patch for that in there, so I'm a little confused. This is an artifact (I think) of having null dates as EOL/warranty. I'm not sure why that suddenly changed, as we haven't made any changes to EOL/warranty in some time.
> 
> In `/var/www/snipe-it/app/Presenters/AssetPresenter.php` try changing:
> 
> ```
> public function warrantee_expires()
> {
>     $date = date_create($this->purchase_date);
>     date_add($date, date_interval_create_from_date_string($this->warranty_months . ' months'));
>     return date_format($date, 'Y-m-d');
> }
> ```
> 
> to:
> 
> ```
> public function warrantee_expires()
> {
>     if (($this->purchase_date) && ($this->warranty_months)) {
>         $date = date_create($this->purchase_date);
>         date_add($date, date_interval_create_from_date_string($this->warranty_months . ' months'));
>         return date_format($date, 'Y-m-d');
>     }
> }
> ```
> 
> and let me know if that helps.

This fixed the report and the generate button now works fine!
Many thanks for checking

**Comment by snipe** [comment]
@boingball Great - I'll push that change out to master today.

**Comment by johnbchron** [comment]
I had the exact same issue in v5.0.0 today... I looked at the logs and it seemed to be tripping over the null value for the depreciation date. I disabled depreciation in the report and it's fine.
