### ISSUE TITLE
 LDAP user Sync not working.

### ISSUE THREAD

**Issue by TwoTwenty** [snipe/snipe-it#7004]
This is the same as  #5222 
except I increase the php memory limit in /etc/php.ini to 7100M

php -i | grep memory_limit
memory_limit => 7100M => 7100M

except it still seems to be allocating 512M
```
php artisan snipeit:ldap-sync --location_id=1 --summary
PHP Fatal error:  Allowed memory size of 524288000 bytes exhausted (tried to allocate 20480 bytes) in /var/www/snipeit/app/Models/Ldap.php on line 272
PHP Fatal error:  Allowed memory size of 524288000 bytes exhausted (tried to allocate 20480 bytes) in /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php on line 122
```

**Comment by andrefecto** [comment]
TwoTwenty,
In our instance, we had to edit the LDAPSync file to get those RAM and runtime usage changes to stick. In that file there is:

` ini_set('max_execution_time', 600); //600 seconds = 10 minutes`
and
`ini_set('memory_limit', '500M');`

Changing those should help!
