### ISSUE TITLE
Add Checked Out To first and last name to Generate Labels

### ISSUE THREAD

**Issue by mcbmoreno** [snipe/snipe-it#7005]
**Server (please complete the following information):**
 - Snipe-IT Version v4.6.5
 - OS: [e.g. Ubuntu, CentOS] Server 2016
 - Web Server: [e.g. Apache, IIS] IIS
 - PHP Version 7.2.10

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
How can the First and Last name of the Checked Out To user for an asset be added as an option to show on Generate Labels?  It looks as though the snipeit\resources\views\hardware\labels.blade.php file gets passed the Snipe internal id of the Checked Out To user but does not have access to the first and last name of that user.  Also, can an option be added to ask for a starting label when printing? i.e. if a sheet of labels has 10 rows of 3 labels and the first 3 rows of the sheet of labels you will be printing on are already used, can you put in a starting label # of 10 to start the printing at the left most label of the 4th row on the sheet of labels?   

**Describe alternatives you've considered**
Exporting the assets to a CSV file and using that as the source for a mail merged word file.  

**Additional context**

**Comment by gilesytheking** [comment]
If you want to add custom info to your label you can edit the following file that outputs the label template. Bare in mind that this file maybe overwritten when you update your installation.

/your-snipe-it-install/resources/views/hardware/labels.blade.php

You can add the following code to the labels.blade.php to output the first & last name. This will only display on the label when the asset is Checked out to a user

`
@if (($asset->assigned_to!=' ') && ($asset->assigned_type=='App\Models\User'))
<div class="pull-left">
Assigned To: {{ $asset->assignedto->first_name }} {{ $asset->assignedto->last_name }}
</div>
@endif
`

You may have to add some custom CSS to style the label to suit your label size. The size of your label might mean you have to compromise the amount of info you put there.

**Comment by mcbmoreno** [comment]
Got this working.  Thanks for the help. 

I wanted to add a feature that would allow the user to input what the starting label is when printing the labels in case they are using a partially used label sheet.  

I was thinking I could add an option for "start at label" field on the Settings > Labels > Update Label Settings page, and then code the starting label into labels.blade.php. 

Does this sound like the right way to attack this?
