### ISSUE TITLE
Cannot create or use a category for an asset which already exists for accessories

### ISSUE THREAD

**Issue by mtausig** [snipe/snipe-it#7008]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

I have a category for my accessories named *Book*. If I want to put an asset model in a category with that same same, that doesn't work. I cannot select *Book* from the drop down and cannot create a new category with the same name

**To Reproduce**
1. Go to Settings -> Category
2. Create a setting called "Book" of type "Accessory"
3. Create a new Asset Model
4. Notice that "Book" cannot be selected from the Category Dropdown
5. Click on "new" next to Category
6. Name the new Category "Book" and click "Save"
7. Error message "Problem(s) with field name: The name must be unique." appears

**Expected behavior**

It should be possible to use the same category name for multiple types of devices. This caould be done either by allowing a duplicate name for two categories of different type, or by enabling a category to be used for multiple types.

**Screenshots**

![image](https://user-images.githubusercontent.com/1511226/57365385-3da01080-7185-11e9-99ba-e6a92f650ae2.png)

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.6
 - OS: Ubuntu 16.04
 - Web Server: nginx
 - PHP Version 7.0

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Firefox
 - Version 66

**Error Messages**

Present in the demo as well

**Comment by mtausig** [comment]
Still relevant.

**Comment by inietov** [comment]
This is precisely for the category you're using. The dropdown only charges models with category 'Assets'.  So if you need Book as Category of the model, you need to create it as type 'Asset' instead of 'Accessory'.

**Comment by mtausig** [comment]
> This is precisely for the category you're using. The dropdown only charges models with category 'Assets'. So if you need Book as Category of the model, you need to create it as type 'Asset' instead of 'Accessory'.

I know that it is that way. But that is IMO not a desirable behaviour. Having a category of the same name for accessory and assets can be useful.

**Comment by snipe** [comment]
@mtausig in your example, what is the use case for "Book" being an asset and other books being accessories?

**Comment by mtausig** [comment]
It's for a migration process. I started adding my books as accessories and now want to make them assets instead.
