### ISSUE TITLE
problem with snipe-it login redirect to auth/signin

### ISSUE THREAD

**Issue by aamarnath** [snipe/snipe-it#701]
Dear,

Setup was working all well and I had loaded most of the asset details. Restarted the system and Login page is not loading please do help.

![error page snipe-it](https://cloud.githubusercontent.com/assets/11160863/6865221/a95f0442-d491-11e4-9e37-fbf4ba88df95.png)

Document root is correct, pointed to: DocumentRoot "C:\wamp\www\snipe-it\public"

**Comment by snipe** [comment]
Please see the documentation on deporting bug and requesting help: http://snipeitapp.com/documentation/getting-help/

**Comment by aamarnath** [comment]
Dear,

As per common Issue page, web server is looking for public/.htaccess file and mod_rewrite is selected.

Snipe-IT.1.2.3 Version what I am using. I was loading asset details even this morning, just with a system restart it stopped loading the login page.

**Comment by aamarnath** [comment]
Stopped all the service and restarted the machine. Started all the service after reboot, it started working. 

Sounds crazy, but thanks for your support.

**Comment by snipe** [comment]
Thanks for the update!
