### ISSUE TITLE
Multiple Line in Additional note on checkout Asset broken

### ISSUE THREAD

**Issue by mailatbijoy** [snipe/snipe-it#7012]
![BUG-snipeit-checkout-email](https://user-images.githubusercontent.com/25344696/57383838-1ff69980-71cd-11e9-9836-a89706eca4f0.JPG)
**Describe the bug**
Multiple Line in Additional note on checkout Asset broken

**To Reproduce**
1. Go to 'List All Asset Tab'
2. Click on 'Checkout any asset'
3. Fill Additional notes column in multiple line using "enter key" and click checkout.
4. See error in Additional notes displayed in email which is sending to recipient

**Expected behavior**
Any data entered in "Additional notes" column should be in same column on email.

**Screenshots**
attached

**Server (please complete the following information):**
 - Snipe-IT Version :v4.2.0 build 3497
 - OS: Ubuntu 16.04
 - Web Server: Apache
 - PHP Version 7.0.25-0

**Additional context**
- Is this a fresh install

**Comment by ItsANoBrainer** [comment]
Reopen, this is still an issue. Multi-lining the additional notes causes it to be separated from the cell in the email as well. 

![issue1](https://user-images.githubusercontent.com/6852526/105410559-16f76700-5c00-11eb-8abc-43473e1a492e.png)
![issue2](https://user-images.githubusercontent.com/6852526/105410560-178ffd80-5c00-11eb-85ac-234388a6ee84.png)
