### ISSUE TITLE
More options to customise labels. 

### ISSUE THREAD

**Issue by JensRod** [snipe/snipe-it#7015]
**Server (please complete the following information):**
 - Snipe-IT Version  4.6.15
 - OS: [MacOS? Safari ]
 - Web Server: [Apache]
 - PHP Version 4011 

**Is your feature request related to a problem? Please describe.**
1D barcode is on its way out, and more barcode scanner do now support QR codes. The 1D barcode uses a lot of the space of the bottom of labels. Would really like to the have the option to fill inn optional text, when the 1D barcode function is disabled. 

**Describe the solution you'd like**
In the label menu. When 1D barcode is disabled you can get an option to write in text. That could be such as an address to the company exc. When the 1D barcode is enabled you can not have this option 

**Describe alternatives you've considered**
Yes I know it is possible to just have the address info in the log in page message field, but the option to use this space, when you don't need a 1D barcode line would I think is useful for others.

**Comment by gilesytheking** [comment]
You can add text to the label via the settings only when the QR code (Display 3D Codes) is enabled.

If you want to add custom info to your label you can edit the following file that outputs the label template. Bare in mind that this file maybe overwritten when you update your installation.

/your-snipe-it-install/resources/views/hardware/labels.blade.php

You may have to add some custom CSS to style the label to suit your label size. The size of your label might mean you have to compromise the amount of info you put there.

**Comment by JensRod** [comment]
Thanks for commenting @gilesytheking. We are not hosting Snipe-IT ourself, and are not educated with open-source. The placement you are referring to: **/your-snipe-it-install/resources/views/hardware/labels.blade.php** is this only possible to access when you are hosting yourself? If you are able to, maybe providing a screenshot of where to locate this. Thanks

**Comment by gilesytheking** [comment]
In order to edit the labels.blade.php you would need FTP access to the server hosting your snipe-IT install and a file editor to add the code.

If you are not familiar with open source or coding I would suggest getting a developer. If your install is hosted by Snipe-IT i would suggest contacting them directly
