### ISSUE TITLE
Label Avery 6577 Insanity

### ISSUE THREAD

**Issue by mrbryce2000** [snipe/snipe-it#7017]
The label generator is driving me crazy! I use the dimensions from Avery in the Label settings. The labels are crowded against the left side. I increase the left margin, and instead of moving them over, the labels themselves shrink in size and stay crammed on the left side.

**Server (please complete the following information):**
 - Snipe-IT Version:  4.6.8 build 3959
 - OS: CentOS 7
 - Web Server: Apache
 - PHP Version: 7.1.28

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 1809
 - Browser Chrome (this also happens in Firefox and Edge)
 - Version 74.0.3729

**Comment by gilesytheking** [comment]
have a look at this post - https://github.com/snipe/snipe-it/issues/7014

You may need to customise the CSS to adjust the the label output to suit your label size. If your label is small you may have to be selective about the info you put there.
