### ISSUE TITLE
Email not working

### ISSUE THREAD

**Issue by RaeesE007** [snipe/snipe-it#7019]
#### Please confirm you have done the following before posting your bug report:

- [yes] I have enabled debug mode 
- [ yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I finally tried setting up my email. There was 1 Log that I kept getting and it was the my MAIL_USERNAME='YOURUSERNAME', replaced the defaults with my details and that cleared me log. But I am not getting emails from checking in nor out. I used my gmail account as there was a working config that I found, but even using that didn't send emails.

**Expected behavior**
I expected it to just send the email to my account.

**Screenshots**
https://pasteboard.co/Ie20ixB.png
https://pasteboard.co/Ie20DSl.png

**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.7 
 - OS: Windows 10 Pro
 - Web Server: wamp
 - PHP Version: 7.0.33

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: 74.0.3729.131

**Additional context**
- Is this a fresh install or an upgrade? Fresh Install
- What OS and web server you're running Snipe-IT on: Windows 10 Pro, wamp
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way: No errors, Snipe is running fine.
- Indicate whether or not you've manually edited any data directly in the database: No

I've taken this over from another guy, so not entirely sure how he installed it. But The config files are good, it's just the mail notifications and notifications in general that I can't get to work. I'm so new to this that I don't even know how to add the 'test email button' from a previous that I found.

**Comment by gilesytheking** [comment]
the mail username & password should be your email account & email password. It will uses those details to authenticate with your email server.

MAIL_USERNAME=youremail@youraccount.com
MAIL_PASSWORD=yourpassword

**Comment by RaeesE007** [comment]
> the mail username & password should be your email account & email password. It will uses those details to authenticate with your email server.
> 
> MAIL_USERNAME=[youremail@youraccount.com](mailto:youremail@youraccount.com)
> MAIL_PASSWORD=yourpassword

I know this thanks, I just covered it for safety reasons.

**Comment by gilesytheking** [comment]
try changing the port to 465. This is generally the port used for SSL/TLS.

You can also try changing the authentication type to SSL rather than TLS

Port 587 is normally used for non secure connections. If you don't have a valid SSL certificate on your server you may need to use this port and leave authentication type blank

**Comment by RaeesE007** [comment]
> try changing the port to 465. This is generally the port used for SSL/TLS.
> 
> You can also try changing the authentication type to SSL rather than TLS
> 
> Port 587 is normally used for non secure connections. If you don't have a valid SSL certificate on your server you may need to use this port and leave authentication type blank

I have tried port 587 with a authentication type:null. But I'll try port 465 now.

**Comment by RaeesE007** [comment]
> try changing the port to 465. This is generally the port used for SSL/TLS.
> 
> You can also try changing the authentication type to SSL rather than TLS
> 
> Port 587 is normally used for non secure connections. If you don't have a valid SSL certificate on your server you may need to use this port and leave authentication type blank

Unfortunately that didn't work.

**Comment by gilesytheking** [comment]
the outgoing mail server settings should be the same settings you would use to configure your emails in outlook. 
Have you double checked your mail server is correct?
Check the correct ports as per your email server?
If you have a firewall that may also block emails being sent
Are you getting any kind of error message when you try to send send a test email from snipe admin?

Also Check the below posts they have plenty of info for setting up / troubleshooting email

https://snipe-it.readme.io/docs/configuration#section-required-outgoing-mail-settings

https://github.com/snipe/snipe-it/issues/4763#issuecomment-356761788

**Comment by RaeesE007** [comment]
> the outgoing mail server settings should be the same settings you would use to configure your emails in outlook.
> Have you double checked your mail server is correct?
> Check the correct ports as per your email server?
> If you have a firewall that may also block emails being sent
> Are you getting any kind of error message when you try to send send a test email from snipe admin?
> 
> Also Check the below posts they have plenty of info for setting up / troubleshooting email
> 
> https://snipe-it.readme.io/docs/configuration#section-required-outgoing-mail-settings
> 
> [#4763 (comment)](https://github.com/snipe/snipe-it/issues/4763#issuecomment-356761788)
> 
> > <img alt="" width="48" src="/favicon.ico">**[Configuration](https://snipe-it.readme.io/docs/configuration#section-required-outgoing-mail-settings)**This section is where you edit the Snipe-IT configuration file to reflect your own settings, such as your database credentials, mail server, preferred language, timezone, and so on. Some of the settings are optional, some are required.   **Don't be intimidated by the length of this page**. The confi...

All things check out, my config is the same, nothing is being blocked. Everything looks like it should be fine but it clearly isn't? I'm not sure how to send a test email from snipe admin? If you mean send an email from Admin email to admin email then that doesn't work either...

**Comment by snipe** [comment]
>  I'm not sure how to send a test email from snipe admin? 

In Admin Settings > General: 

<img width="704" alt="Screen Shot 2019-05-15 at 6 48 47 PM" src="https://user-images.githubusercontent.com/197404/57820546-1d9ebd00-7742-11e9-8b48-cd2df0220ff5.png">

**Comment by RaeesE007** [comment]
Figured out the issue, the email notification box was unchecked for the category.

**Comment by SajaEnergy** [comment]
I'm currently utilizing Snipe IT V6.30, and all my email configurations seem to be in order. I've conducted a test email and successfully received it in my Gmail account. However, when it comes to checking in or checking out assets, the emails aren't reaching my Office 365 Exchange. Can anyone offer assistance with this issue?
