### ISSUE TITLE
Method [checkModel] does not exist.

### ISSUE THREAD

**Issue by mdaniels5757** [snipe/snipe-it#702]
Hi,

Just installed Snipe-It, this is what happens when I try to add an asset:

Snipe-IT Version: v1.2.6.1-152
OS: Ubuntu 14.04
Webserver: Apache
'''
BadMethodCallException thrown with message "Method [checkModel] does not exist."

Stacktrace:
#20 BadMethodCallException in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:268
#19 Illuminate\Routing\Controller:__call in /opt/snipe-it/app/controllers/admin/AssetsController.php:158
#18 Controllers\Admin\AssetsController:checkModel in /opt/snipe-it/app/controllers/admin/AssetsController.php:158
#17 Controllers\Admin\AssetsController:postCreate in <#unknown>:0
#16 call_user_func_array in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:231
#15 Illuminate\Routing\Controller:callAction in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:93
#14 Illuminate\Routing\ControllerDispatcher:call in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:62
#13 Illuminate\Routing\ControllerDispatcher:dispatch in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php:962
#12 Illuminate\Routing\Router:Illuminate\Routing\{closure} in <#unknown>:0
#11 call_user_func_array in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Route.php:109
#10 Illuminate\Routing\Route:run in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1028
#9 Illuminate\Routing\Router:dispatchToRoute in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php:996
#8 Illuminate\Routing\Router:dispatch in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:777
#7 Illuminate\Foundation\Application:dispatch in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:747
#6 Illuminate\Foundation\Application:handle in /opt/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php:34
#5 Barryvdh\Debugbar\Middleware\Stack:handle in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware.php:72
#4 Illuminate\Session\Middleware:handle in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php:47
#3 Illuminate\Cookie\Queue:handle in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php:51
#2 Illuminate\Cookie\Guard:handle in /opt/snipe-it/vendor/stack/builder/src/Stack/StackedHttpKernel.php:23
#1 Stack\StackedHttpKernel:handle in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php:643
#0 Illuminate\Foundation\Application:run in /opt/snipe-it/public/index.php:49
'''
Please let me know what to do, and if you need any more info.

Thanks!

**Comment by snipe** [comment]
Is there a reason you're using the develop branch instead of a release version?

**Comment by mdaniels5757** [comment]
Not really. Is this a problem with my install or a bug with the branch? I
might just install the release version....

**Comment by snipe** [comment]
The develop branch shouldn't be used for installing the software, only for folks who want to contribute to the codebase, as it can sometimes be unstable as we're testing things. Please use the [latest stable release](https://github.com/snipe/snipe-it/releases).
