### ISSUE TITLE
Url in reset password mail

### ISSUE THREAD

**Issue by pingy82** [snipe/snipe-it#7025]
in the reset password email i have problem with the link

i see
http://SERVERNAME/SERVERNAME/password/reset/faa675061ec5758e9a52266dfe97ce16bdc20304f4fda09e1946500e20517c49

how to fix it?
Thanks

**Comment by snipe** [comment]
@pingy82 That variable is pulled from your .env file. Change APP_URL in your .env to whatever your application URL is and clear the config cache using `php artisan config:clear`.
