### ISSUE TITLE
Snipe-IT Builder.php line 1229 Error

### ISSUE THREAD

**Issue by OvercookedToast** [snipe/snipe-it#7028]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
On the drop down list there are a number of options that work fine and load the page correctly however Clicking "Assets"  then clicking any of the following: "All Deployed", "All Ready to Deploy", "All Pending", "All Un-deployable", "All Archived" or "Requestable". The error page loads up.

**To Reproduce**
1. Go to '"Assets"'
2. Click on '"All Deployed", "All Ready to Deploy", "All Pending", "All Un-deployable", "All Archived" or "Requestable"'
3. Scroll down to 'Error page loads'
4. See error uploaded 

**Expected behavior**
The relevant Asset page would load up.

**Screenshots**
I've added a text page with the errors.

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.15
 - OS: Windows server 2016
 - Web Server:  IIS
 - PHP Version 7.3.4

**Desktop (please complete the following information):**
 - Windows 10 Professional
 - Google Chrome
 - Version 74.0.3729.131

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- This is a fresh install 
- Windows 10 Professional & Windows server 2016

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.
[Github Error Assets.txt](https://github.com/snipe/snipe-it/files/3182042/Github.Error.Assets.txt)
[Github Error Requestable.txt](https://github.com/snipe/snipe-it/files/3182043/Github.Error.Requestable.txt)

**Comment by snipe** [comment]
Per the [requirements](https://snipe-it.readme.io/docs/requirements), Snipe-IT v4.x is not compatible with PHP 7.3. You'll need to use a version of PHP between 5.6.4 and 7.2.x. This is due to a limitation of the underlying framework. The upcoming v5 will support 7.3+.
