### ISSUE TITLE
[Feature Request] Autopopulate expected check-in dates with default values from model

### ISSUE THREAD

**Issue by Cabe** [snipe/snipe-it#7029]
**Server (please complete the following information):**
 - Snipe-IT Version 	v4.6.15 build 4011 (gd1e9fbfa2)
 - OS: Ubuntu 18.04.2
 - Web Server: Apache 2.4.29
 - PHP Version 7.2.17-0ubuntu0.18.04.1

**Is your feature request related to a problem? Please describe.**
Entirely a feature request.

**Describe the solution you'd like**
In asset model categories offer a default period for check-in dates. We have a number of self-service assets that could do with being audited regularly (mostly development phones and VR headsets) so it would be useful to have a default 7 day/30day/6month etc check-in date set in the asset model. 

This would then autofill from the check-out date, and serve to email the relevant department heads to confirm equipment which usually ends up in someone's drawer.

**Describe alternatives you've considered**
Unaware there are any other than manual user intervention.

**Additional context**
Users are fundamentally lazy, and there would be too much bandwidth overhead for IT to manually check it regularly.

**Comment by sambayford** [comment]
Would use this feature. As well as default periods we would also use default dates for each model. We have a number of different laptop models that need to be returned at specific dates due to warranty expiry.
