### ISSUE TITLE
Client/Asset Scan in the network

### ISSUE THREAD

**Issue by Rungea96** [snipe/snipe-it#7033]
#### Expected Behavior (or desired behavior if a feature request)

I have successfully installed Snipe-IT in my company. Because we have a lot of client computers, laptops and printers in the network, I would like to scan an IP address range. 
Does anyone know an extra tool that scans the network and allows me to import the data into Snipe It? So that it fits into the categories, departments, etc. created in Snipe IT.
As much information as possible. So hardware components and registered users should be scanned in any case.  

And if so, can anyone explain it?

-----

#### Actual Behavior

Currently I see it as an enormous effort to manually enter each client into Snipe IT.
Snipe IT makes a great impression when it comes to overview and functions. The IP network scan would complete it perfectly. 

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
fresh install
- Version of Snipe-IT you're running
4.6.16
- Version of PHP you're running
7.2.18
- Version of MySQL/MariaDB you're running
MariaDB 10.0.14.0
- What OS and web server you're running Snipe-IT on
Windows Server 2016 and a IIS Server
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual installation
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by Rungea96** [comment]
Thank you in advance!!

**Comment by mailanetworks** [comment]
Hi, 
Have you had any success with this issue?
I'm looking into the same funcionality.

Thanks,

**Comment by paoloirons** [comment]
Hi, I'm looking for the same IP Scan, is there any update about it? 

ty

**Comment by ashok-dangol** [comment]
I am also looking for same thing. It helps a lot in terms of cost and time.

**Comment by snipe** [comment]
Lots of people have written network agents. It's not on our roadmap, but you can try using the ones that already exist. https://github.com/ReticentRobot/SnipeAgent is one.

<blockquote><img src="https://opengraph.githubassets.com/648ba6b0c3d588cb6d48cffca8eb4e07da09e00b4c6a0d1e912eec99ba549063/ReticentRobot/SnipeAgent" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/ReticentRobot/SnipeAgent">GitHub - ReticentRobot/SnipeAgent: Windows Agent for Snipe-IT Open Source Asset Management</a></strong></div><div>Windows Agent for Snipe-IT Open Source Asset Management - GitHub - ReticentRobot/SnipeAgent: Windows Agent for Snipe-IT Open Source Asset Management</div></blockquote>
