### ISSUE TITLE
When clicked on license tab it is showing directory structure.

### ISSUE THREAD

**Issue by siddharthb1982** [snipe/snipe-it#7037]
#### Please confirm you have done the following before posting your bug report:

- [ dont know] I have enabled debug mode 
- [ yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

I have installe Snipe IT 4.6.15 on Windows server 2008 R2 with Xampp 3.2.3.
Every thing working fine in SnipeIT webpage, but when i click on License page it shows me directory stucture and not the web page which is expected.

What could be the issue?

**To Reproduce**
1. Go to 'Snipe IT Home page'
2. Click on 'License'

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.15
 - OS: [e.g. Windows server 2008 R2]
 - Web Server: [e.g. Apache, ]
 - PHP Version 4.8.5

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/xampp#section-remove-built-in-aliases
