### ISSUE TITLE
Mail could not be sent. An Error has occured! stream_socket_enable_crypto(): SSL: Handshake timed out

### ISSUE THREAD

**Issue by SirajQu** [snipe/snipe-it#7041]
Describe the bug
Email notification and confirmation acceptance of assets is not working.
When check out asset to user it shows that as the user will be emailed with a link to confirm acceptance of this item. " but then error message comes: Whoops, looks like something went wrong.

here is my .env setting for the email:
-------------------------------------------
REQUIRED: OUTGOING MAIL SERVER SETTINGS
--------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=smtp.office365.com
MAIL_PORT=587
MAIL_USERNAME=************
MAIL_PASSWORD=************
MAIL_ENCRYPTION=TLS
MAIL_FROM_ADDR=************
MAIL_REPLYTO_ADDR=************

Server (please complete the following information):

Snipe-IT Version v4.6.17
OS: Windows Server 2012
Web Server: [IIS]
PHP Version 7.0.33

**Error Messages**
[2019-05-18 15:28:36] production.ERROR: ErrorException: stream_socket_enable_crypto(): SSL: Handshake timed out in C:\inetpub\wwwroot\snipe-it\vendor\swiftmailer\swiftmailer\lib\classes\Swift\Transport\StreamBuffer.php:103#60 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\NosniffGuard.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\NosniffGuard->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\ContentSecurityPolicyHeader.php(18): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(148): App\Http\Middleware\ContentSecurityPolicyHeader->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 C:\inetpub\wwwroot\snipe-it\app\Http\Middleware\ReferrerPolicyHeader.php(17): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Pipeline\

**Comment by SirajQu** [comment]
Yes still

**Comment by snipe** [comment]
This is still not an issue on our end though. This is always a configuration error either in your .env, your SSL on your Snipe-IT server, or on the mail server's side.

**Comment by SirajQu** [comment]
> This is still not an issue on our end though. This is always a configuration error either in your .env, your SSL on your Snipe-IT server, or on the mail server's side.

This is what I have inside .env file:
`# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=smtp
MAIL_HOST=smtp.office365.com
MAIL_PORT=587
MAIL_USERNAME=xxxxxxxx
MAIL_PASSWORD=xxxxxxxxxx
MAIL_ENCRYPTION=TLS
MAIL_FROM_ADDR=xxxxxxxx
MAIL_FROM_NAME='xxxx'
MAIL_REPLYTO_ADDR=xxxxxx
MAIL_REPLYTO_NAME='xxxxx'`

and still I get this error:

>  Mail could not be sent.
Error: An Error has occured! stream_socket_enable_crypto(): SSL: Handshake timed out

I have SSL certificate installed properly on the server but I don't know if this casing the issue how do I check that?

**Comment by KevindelCid** [comment]
acabo de tener este problema con laravel 8 y el problema realmente estaba del lado de mi servidor unicamente tuve que habilitar el ssl y todo anduvo bien... lo hice usando laragon 
habilitando SSL en  Menú -> preferencias... -> puertos & servicios
desconozco como hacerlo en usando xamp, wamp o cualquiera de estos

**Comment by vitthal-repository** [comment]
I also facing the same issue. worked on this issue last 2 days but not getting resolution. Please help
![snipe error](https://user-images.githubusercontent.com/78343972/155319160-d714857d-28a1-42ed-b874-d1b81336e92e.PNG)

**Comment by snipe** [comment]
I'd suggest you talk to your IT team members in charge of the firewall, SSL certs, etc. This isn't something on our end. :(
