### ISSUE TITLE
[Feature Request] Add API Route to create a maintenance for a specific Asset

### ISSUE THREAD

**Issue by Techno11** [snipe/snipe-it#7043]
**Server (please complete the following information):**
 - Snipe-IT Version v4.6.16
 - OS: Ubuntu 18.04.1
 - Web Server: Apache2
 - PHP Version PHP 7.2.17

**Is your feature request related to a problem? Please describe.**
I need to be able to create an Asset Maintenance "report" through the API, as is available through the web GUI [here](https://develop.snipeitapp.com/hardware/maintenances/create?asset_id=500)

**Describe the solution you'd like**
An API Route added to allow the creation of asset maintenance.

**Additional context**
I'm trying to create an app that need to be able to add asset maintenances to various assets.

**Comment by diegogarciadev** [comment]
Take a look this issue: #8066
