### ISSUE TITLE
Asset update via API deletes custom field data

### ISSUE THREAD

**Issue by cslob** [snipe/snipe-it#7044]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When updating an asset via API (I've updated status, added notes, etc) any custom fields (MAC address for example) are removed. This has occurred since 4.6.17.

**To Reproduce**
1. Make a change to an asset via API (status, add a note, etc)
2. 200 Message is received with custom fields now null
3. Log into web and look at the asset to verify custom field is removed

**Expected behavior**
Updating asset via API should not remove custom fields.

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version:  7.1.17

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 74

**Comment by cslob** [comment]
@snipe Yes that fixed it!

**Comment by snipe** [comment]
Great - I've got that fix out on master, and it will be in a formal release later today. Thanks for the heads up!
