### ISSUE TITLE
Please add support for MariaDB 10.2.7 and later. 

### ISSUE THREAD

**Issue by jflatz** [snipe/snipe-it#7045]
The Doctrine repo fixed this issue and now supports up to MariaDB 10.3 when they released [Doctrine 2.9.0](https://github.com/doctrine/dbal/releases/tag/v2.9.0) which was released in December of 2018. #3947

**Comment by snipe** [comment]
We cannot do that (as we've explained in other tickets) because 2.9.0 requires PHP ^7.1, which would be a breaking change.

**Comment by snipe** [comment]
(This support is already in the upcoming v5)

**Comment by jflatz** [comment]
Thank you for the update! Is there an issue number or something I can follow the status of for upgrading PHP?
