### ISSUE TITLE
User profile website field only shown in own user profile

### ISSUE THREAD

**Issue by 1Jesper1** [snipe/snipe-it#7046]
See line: https://github.com/snipe/snipe-it/blob/420e8bc85a5008842542238c7fa8381237645cd1/resources/views/account/profile.blade.php#L87

Where is the website of a user shown in the application? Is the website field only shown in the user own profile?

Snipe-it 4.6.17

**Comment by snipe** [comment]
Yeah, I think we used to use it (like back in v1), but don't anymore, and just never took it out of the profile. 

Is it something you think would be useful for us to add back? The field still exists in the database. we just don't display it anywhere.

**Comment by 1Jesper1** [comment]
Thanks for the explanation, personally I wouldn't use it. For me this this field could be deleted.
