### ISSUE TITLE
Problem to login with a LDAP account (With Successful LDAP?)

### ISSUE THREAD

**Issue by rojz** [snipe/snipe-it#7049]
- Snipe-IT Version: v4.6.15 build 4011 (gd1e9fbfa2)
 - OS: Ubuntu0.18.04.1
 - Web Server: Apache
 - PHP Version: 7.2.17-0

Hello,

I'm trying to configure LDAP to a Snipe-IT server that I got handed to me and I'm not having so much luck as I wanted with it.

I get the LDAP to work so that "Test LDAP" will show "Connection to LDAP server established!" and that I can Import users in the People tab and can see that new users show up (Tried to delete  an account, and tried to sync again it it appears again.)

BUT the thing is that when I'm trying to use the "Test LDAP" for accounts.. Then it only says: "Login Failed. username did not successfully bind to LDAP."

And I cannot login to these accounts on Snipe-It if I don't reset the password with the "I forgot my password" link. Which indicated that the LDAP wasn't successful.

Any Ideas?
![LDAP1_LI](https://user-images.githubusercontent.com/30040797/58103271-00a33780-7be3-11e9-9d28-1633d19a9efa.jpg)
![LDAP3_LI](https://user-images.githubusercontent.com/30040797/58103319-1284da80-7be3-11e9-8500-3b23a9d5f003.jpg)
![LDAP2 (2)_LI](https://user-images.githubusercontent.com/30040797/58103325-157fcb00-7be3-11e9-8149-b4888d113a75.jpg)
![LDAP4](https://user-images.githubusercontent.com/30040797/58103333-17e22500-7be3-11e9-84a6-94bde32e5251.png)

**Comment by rojz** [comment]
Any one that have any idea what this could be?

**Comment by snipe** [comment]
Usually means your LDAP Authentication query is wrong. Try using `sAMAccountName=`, per the documentation:

https://snipe-it.readme.io/docs/ldap-sync-login

<img width="618" alt="Screen Shot 2019-05-24 at 1 01 40 AM" src="https://user-images.githubusercontent.com/197404/58312148-8a0f6100-7dbf-11e9-85c5-c66bd2bf1b8f.png">

**Comment by rojz** [comment]
Sorry, that didn't work and I have tried that before, been trying to look around and tried a lot of different settings with no luck.

**Comment by rojz** [comment]
Any update here? Would it be easier for me just to re-install a machine and install Snipe-IT from scratch? Or does anyone have any clue what could be wrong here?

**Comment by rojz** [comment]
I have now tried to install a new Snipe-IT server from the official guide: https://snipe-it.readme.io/docs/installation
I still have the same problem. When I test the LDAP connection it works, but when I'm trying to find a user with LDAP I still get: " Login Failed. username did not successfully bind to LDAP."...

But the thing is that when I go to "people" and sync with LDAP.. I can find everyone within the OU. Any suggestions?
