### ISSUE TITLE
Issue : Recent Activity Date in Dashboard - Demo Site

### ISSUE THREAD

**Issue by joseph707** [snipe/snipe-it#705]
hi @snipe 

Good morning. The dashboard recent activity at the demo site shows the first entry date as Apr 1. 

![capture](https://cloud.githubusercontent.com/assets/9422649/6879837/2c199f3c-d528-11e4-9a12-6939f4712386.JPG)

Regards

Joseph

**Comment by snipe** [comment]
That's because the user who checked out the asset set the date to April 1. This is expected behavior.
