### ISSUE TITLE
Unable to save/modify assets after update

### ISSUE THREAD

**Issue by therrienr** [snipe/snipe-it#7050]
#### Expected Behavior (or desired behavior if a feature request)

When modifing an asset I should see it save succesfully

-----

#### Actual Behavior

When I go to modify an asset and save it the page just refreshes and the changes are reverted where as before it use to save asset saved succesully and id be able to see the changes.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Upgrade
- Version of Snipe-IT you're running : v4.6.16 - build 4018
- Version of PHP you're running: PHP Version 7.0.33-6
- Version of MySQL/MariaDB you're running:  5.7.26-0
- What OS and web server you're running Snipe-IT on : Ubuntu 16.04 Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
We'd need to see what's in your app error logs to be able to help you.

**Comment by therrienr** [comment]
Where can i find the logs for that, I have debug mode turned on but no error messages pop up the page just simply refreshes

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/getting-help
