### ISSUE TITLE
state field text limit only 3 characters

### ISSUE THREAD

**Issue by inforhunter** [snipe/snipe-it#7062]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)
When I edit a people's properties,  in my country(CN),state name is more than 3 characters
-----

#### Actual Behavior

(what actually happens goes here)
 the "state" field limits text only for 3 character.
-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running v4.6.17
- Version of PHP you're running v7.2
- Version of MySQL/MariaDB you're running MariaDB 5.6
- What OS and web server you're running Snipe-IT on CentOS 7.6
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error   http://cmdb.flow-ever.com/users/1/edit
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. no
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. Yes
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by inforhunter** [comment]
I have checked that the state field type is varchar(3) of users table in DB

**Comment by snipe** [comment]
It's meant for abbreviations, not full state names.
