### ISSUE TITLE
Windows LDAP sync command

### ISSUE THREAD

**Issue by AusA380** [snipe/snipe-it#7063]
Running Snipe-IT on Windows Server 2012 r2. Everything is working well, however I'm wanting to set up an automatic LDAP sync daily in Task Scheduler.

If I were to run the command as: 
_php.exe C:\PATH\TO\SNIPE\ARTISAN snipeit:ldap-sync_
would this work?

I've configured LDAP in the GUI and have run the first LDAP sync successfully, but am wanting to do it automatically and daily now. Will running the ldap-sync command pull from the already configured LDAP settings that have been configured in the GUI or does the location or location ID have to be specified in this command?

**Comment by snipe** [comment]
> Will running the ldap-sync command pull from the already configured LDAP settings that have been configured in the GUI

Yes
