### ISSUE TITLE
Problem changing `LDAP Authentication query` value

### ISSUE THREAD

**Issue by sunjon** [snipe/snipe-it#7067]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Changing the `LDAP Authentication query` value does not update the LDAP query being sent to the server. I believe I require the value to be `cn=`, however with that setting (and saved to apply), the logs on the LDAP server is still showing `uid=` being sent when testing the LDAP auth functionality.

**To Reproduce**
1. Go to settings -> LDAP
2. Enter `cn=` in the `LDAP Authentication query` field and hit `save`.
3. Re-enter the LDAP settings page.
4. Attempt `Test LDAP Login`

**Expected behavior**
Successful login when DN uses `cn=` instead of `uid=`

**Screenshots**
![snipe-it-ldap_bind](https://user-images.githubusercontent.com/1448118/58260719-7daaea00-7d66-11e9-8b6f-272068f8da84.png)

**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.18 - build 4036 (master) Docker build.
 - OS: ubuntu:xenial
 - Web Server: Apache
 - PHP Version: 7.0

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.3
 - Browser: Firefox
 - Version: 66.0.3

**Error Messages**
```
16:18:07] LOG.debug: Preparing to test LDAP login
[16:18:07] LOG.debug: Attempting to bind to LDAP for LDAP test

[16:18:07] LOG.debug: Attempting to login using distinguished name:uid=aaabbbccc,ou=Employees,dc=xxxyyyzzz,dc=com

**Comment by bilde2910** [comment]
I can confirm that I am unable to bind to LDAP because of this. LDAP is set up to use `cn=Firstname Lastname,ou=...` as DN, but Snipe-It will insist on using `uid=username,ou=...`. This results in authentication failure since the uid DN does not exist. Using v4.9.2 against OpenLDAP.

**Comment by ocatex** [comment]
I have tihs problem too.  Version v5.1.2 - build 5847

**Comment by DepaMarco** [comment]
I have installed "Version v6.2.0 - build 11566 (master)" and I can confirm the presence of this issue.
Like said also by @bilde2910 , my setup use "cn=Name Surname, ou=..." as DN but in Snipe search query it still use "uid=...".
In this context, I cannot understand the exact meaning of the field "LDAP Authentication query" in the form "field=" if is not used in practice and is not possible to use "placeholders" that represents Snipe-IT user.

**Comment by DepaMarco** [comment]
Just upgraded my installation of Snipe-IT to version 8.0.4 but I'm still having the same issue...
It seems "LDAP Authentication query" is not used at all. Why forcing "uid=..." in the binding query to LDAP? It's a common used option to have "cn=" as DN and not the "uid=".
Please have a look to this.
