### ISSUE TITLE
Snipe-IT4.7 ETA? [NOT A BUG/FEATURE]

### ISSUE THREAD

**Issue by maxlehot1234** [snipe/snipe-it#7069]
Hi everyone,

2 days ago, with the 4.6.18 version, you say:
![image](https://user-images.githubusercontent.com/5159244/58270955-f6a34500-7d58-11e9-82ce-33be8b44448f.png)

Do you know when this version will be ready?

Thanks again

**Comment by snipe** [comment]
We had to change a lot more than we hoped when we upgraded the underlying framework and dependencies. There is one remaining bug outstanding that were working on today, but not sure how long that will take. Hoping to have a release out today or tomorrow tho.

**Comment by maxlehot1234** [comment]
> We had to change a lot more than we hoped when we upgraded the underlying framework and dependencies. There is one remaining bug outstanding that are working on today, but not sure how long that will take. Hoping to have a release out today or tomorrow tho.

Ok thanks a lot for the heads up ;)

Good luck with this bug.
Also, any idea how I can upgrade from 4.6.18 to 5.0.0. beta 2? I search everywhere, and not able to find anything :P 

Have a nice day

**Comment by snipe** [comment]
You’d upgrade the same as always (assuming you installed via git), just specify the develop branch. `php upgrade.php develop`

**Comment by maxlehot1234** [comment]
> You’d upgrade the same as always (assuming you installed via git), just specify the develop branch. `php upgrade.php develop`

Weird thing.

I run the command, but I get a lot of permission denied even if storage and public/uploads folders are chmod with the snipeit user

**Comment by jovibroz** [comment]
> > You’d upgrade the same as always (assuming you installed via git), just specify the develop branch. `php upgrade.php develop`
> 
> Weird thing.
> 
> I run the command, but I get a lot of permission denied even if storage and public/uploads folders are chmod with the snipeit user

Same here and sudo aint allowed :O Not sure what I did wrong..
