### ISSUE TITLE
[General Question] LDAP Import - Disable Login by Default

### ISSUE THREAD

**Issue by CBEZwPorter** [snipe/snipe-it#7072]
#### Expected Behavior (or desired behavior if a feature request)

Users are imported via LDAP and login in is set to disabled by default. 

-----

#### Actual Behavior

After import users are able to log in. 

-----
On version 4.6.8

Didn't see a specific place to put general inquiries. Please feel free to let me know if this request isn't possible. 

A bit of an unusual request but I'm looking to have users imported to Snipe-IT via LDAP and set to be disabled by default and thus unable to log in. Needing LDAP imports to manage users efficiently but from a security stand-point, prevent someone from having the ability to log in since the server is accessible from our wireless network to allow our IT staff to utilize the mobility feature. 

It's not so much wanting to prevent a user from access Snipe-IT. But to avoid creating issues with auditors saying that users have the ability to access a system from their mobile device. 

Thanks!

**Comment by snipe** [comment]
I believe this has already been fixed in later versions....
