### ISSUE TITLE
Custom Regex fields

### ISSUE THREAD

**Issue by uknzaeinozpas** [snipe/snipe-it#7074]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
It's impossible to edit a field that is set it to "CUSTOM REGEX", it will change it's field type to something else and you will no longer be able to set it to "CUSTOM REGEX".

**To Reproduce**
1. Open https://demo.snipeitapp.com/fields
2. Edit a field and set it to "CUSTOM REGEX", click ok
3. Wait for the magic

**Expected behavior**

**Screenshots**
![2019-05-24 09_07_17-Window](https://user-images.githubusercontent.com/22473767/58309253-07f55b80-7e04-11e9-8a9e-af0d0258e3dc.png)

**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.18 - build 4036 (master)
- Tested on the Snipe IT Demo page

**Comment by sreyemnayr** [comment]
So it looks like it is in fact saving it as a regex type, just when you go to edit the field it's not populating the form correctly.

**Comment by sreyemnayr** [comment]
Oh but then on the update form, if you choose "CUSTOM REGEX" it repopulates the input, but saves as "ANY" without the custom regex input data.

**Comment by sreyemnayr** [comment]
So initial save works as custom regex, but editing and saving does not.

**Comment by uknzaeinozpas** [comment]
Yes, right. It only happens when you edit an existing field. Creating a new one works fine ;)

**Comment by sreyemnayr** [comment]
This is just on the live demo. Works correctly in develop branch.

**Comment by uknzaeinozpas** [comment]
good to know, maybe it was fixed already.........
Forget everything, I filtered out closed tickets when I looked for the issue, it was already raised:
https://github.com/snipe/snipe-it/issues/5896
