### ISSUE TITLE
Check out to field "The results could not be loaded"

### ISSUE THREAD

**Issue by drumgod** [snipe/snipe-it#7075]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When checking out an asset the 'check out to' field is not searchable and does not auto/predictive type. I should be able to type the first few letters of the item we are searching for and have it displayed, but it does not. Other fields do the auto/predictive text just fine. 

When i manually type in the asset i get the message "The results could not be loaded". Users have to scroll through the entire list of assets manually (we have over 10K assets) and this is VERY time consuming. 

Just upgraded to the latest v4.6.18 b4036 and i still have this problem. 

**To Reproduce**
1. Go to home page
2. Click on Create New -> Asset
3. Select a model
4. Click status -> Ready to deploy
5. Select Asset in the checkout to field
6. Then type the first few characters of the first listed asset
7. Get the error "The results cannot be displayed"

**Expected behavior**
Typing the first few characters of the asset should auto type or predictive type and filter on the characters you have entered. Limiting the list of assets to items that match the characters you have typed.

**Screenshots**
![Drop down view](https://user-images.githubusercontent.com/36162901/58325730-ada2cd80-7df8-11e9-9ca9-0782b7a512a4.png)

![Results could not be loaded](https://user-images.githubusercontent.com/36162901/58325732-b0052780-7df8-11e9-9dfd-7d2c7d557796.png)

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.18 b4036
 - OS: [e.g. Ubuntu, CentOS] Windows 2008
 - Web Server: [e.g. Apache, IIS] IIS
 - PHP Version 7.1.3

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] IE, EDGE, Chrome, Fire fox

**Comment by snipe** [comment]
Are there any related errors in your app log?

**Comment by drumgod** [comment]
Looking in the /storage/logs/laravel.log i get this error:

roduction.ERROR: PDOException: could not find driver in C:\inetpub\wwwroot\snipe-it-4.1.9\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:43

**Comment by drumgod** [comment]
I see this error also:

production.ERROR: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'assets._snipeit_mac_address_1' in 'where clause' in C:\inetpub\wwwroot\snipe-it-4.1.9\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:77

**Comment by snipe** [comment]
I'm not sure that's a current error? Can't tell based on the timestamp. Can you try tailing the log file and triggering the error again? (If it couldn't find your PDO driver, the whole app wouldn't work.)

**Comment by drumgod** [comment]
I just deleted the log file; then reproduced the error. Here is the entire log


`
[laravel.log](https://github.com/snipe/snipe-it/files/3216795/laravel.log)
`

**Comment by snipe** [comment]
`[2019-05-24 08:10:01] production.ERROR: PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'assets._snipeit_mac_address_1' in 'where clause' in C:\inetpub\wwwroot\snipe-it-4.1.9\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:77`

That's your problem. It can't find the `_snipeit_mac_address_1` on the assets table. Is it possible it got manually deleted somehow?

**Comment by snipe** [comment]
(And your migrations are up to date, right?)

**Comment by drumgod** [comment]
Ok.. I just added snipeit_mac_address_1 manually to our database; and everything works now!!! Very awesome, thank you for your help!!
