### ISSUE TITLE
Active Directory doesn't sync users, although Import successful message appears.

### ISSUE THREAD

**Issue by MolnarPeter11** [snipe/snipe-it#7078]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Active Directory sync doesn't sync any user, altough the import was successful.

**Expected behavior**
Sync AD users.

**Screenshots**
![bug](https://user-images.githubusercontent.com/51078215/58410215-016c1b80-8072-11e9-97d9-b99520269913.PNG)
![config](https://user-images.githubusercontent.com/51078215/58410217-016c1b80-8072-11e9-8653-0bffbade0d4f.PNG)

**Server (please complete the following information):**
 - Snipe-IT Version **v4.6.12 - build 3982 (master)** 
 - OS: [e.g. Ubuntu, CentOS] **CentOS 7**
 - Web Server: [e.g. Apache, IIS] **Apache**
 - PHP Version **5.6**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] **Windows 8.1**
 - Browser [e.g. chrome, safari] Chrome, **Firefox**
 - Version [e.g. 22] **74.0.3729.169**

**Error Messages**
-

**Additional context**
- Is this a fresh install or an upgrade? **Upgrade**
- What OS and web server you're running Snipe-IT on **CentOS 7**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **manual installion**
- Include what you've done so far in the installation, and if you got any error messages along the way. **No**
- Indicate whether or not you've manually edited any data directly in the database **No**

The problem is Iam trying to sync users from an AD. The connection is successful. The Users are in a Group which in an OU. I included 2 screenshot where you could see my config. I haven't got any error message along the sync. Just a  "Success: LDAP Import successful." message, but none of the users got synced into snipe-it! I tried to provide all the information, please help solve this issue.

**Comment by thameerakn** [comment]
![LDAP-Config](https://user-images.githubusercontent.com/29269087/58619798-cf67ed00-82ef-11e9-8bc1-91f11196c4ca.png)

Try this config.

**Comment by MolnarPeter11** [comment]
Thanks for the answer! But its just part of the soluton, because i want to import every member of a specific group, for example: CN=Snipeit_members,OU=Groups,OU=Clarity,DC=CLA,DC=ORG.
But if i use givenName=* it will import every user, not just the group members =(

**Comment by thameerakn** [comment]
Why not use it in Base Bind DN? I tried and it worked as well. Or use "memberOf=CN=XXXXX", I haven't test this but I use this in another project to sync data from AD.

**Comment by MolnarPeter11** [comment]
Thanks for the insight! I tried this, and the result is the same as at the start, sync successful, although no user imported... Could you show me a screenshot of the config? I tried it out this way:
![1](https://user-images.githubusercontent.com/51078215/58881844-4da30580-86db-11e9-8afb-9bb0caa7fef3.PNG)
![2](https://user-images.githubusercontent.com/51078215/58881846-4e3b9c00-86db-11e9-892e-4cc2faa34251.PNG)

**Comment by thameerakn** [comment]
I think "LDAP Bind Username" should be a user who have right to query the detail of the AD. Please change the Username to "administrator" or user have proper rights.

**Comment by MolnarPeter11** [comment]
Thanks for the suggestion! I will try that! I hope it solves the issue, we will see :)

**Comment by MolnarPeter11** [comment]
I tried it, but now i have an invalid credentials error, but its probably on my end! I try to solve it quickly and leave a reply if the config worked or not :)

**Comment by MolnarPeter11** [comment]
Yes sadly the issue still persist, after the credentials error solved. If i try to synchronise its still successful, though not a single user imported. If it helps i try to create a few screens about the AD too.

**Comment by spencedit** [comment]
Hello, 

I'm experiencing this issue as well. We can sync AD successfully, but users are not created. We can have users login with their AD credentials, which creates the user, but only after a login. 

We would like to figure out how to auto create all of our users when Syncing AD.
