### ISSUE TITLE
Cannot delete users

### ISSUE THREAD

**Issue by kylevitale** [snipe/snipe-it#708]
I cannot delete any users. It tells me "Error: Insufficient permissions". I am using a user that is part of the Admin group. Any ideas?

Thanks!

**Comment by snipe** [comment]
User management require super admin permissions. 

![screen shot 2015-03-31 at 9 42 55 am](https://cloud.githubusercontent.com/assets/197404/6924007/5ccaf590-d78a-11e4-8e79-cab60f3ac734.png)

**Comment by kylevitale** [comment]
Got. Somehow I couldn't find that at first.
