### ISSUE TITLE
LDAP auth does not retrieve user's group (cn)

### ISSUE THREAD

**Issue by 0xmilkmix** [snipe/snipe-it#7082]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I'm configuring the ldap authentication and the sync testing is ok. Later, when I try to test the authentication using one user, I see on the ldap server that snipe is only using the base bind dn but does not add the user's group in it (cn in our case).

I tried with various ldap filters like the following:
```
&(ObjectClass=inetOrgPerson)(|(cn=group1,dc=plop,dc=net)(cn=group2,dc=plop,dc=net))
```

As such, the request is `uid=user,dc=plop,dc=net` instead of `uid=user,cn=group1,dc=plop,dc=net`

Could someone help me understanding the proper configuration so the group is added?

**Comment by thameerakn** [comment]
Hi,

I think you should try below configurations. I had the same Issue. These Configurations worked well for me. Please use tcpdump on port 389 to see what is the real issue.

**Comment by 0xmilkmix** [comment]
>  Please use tcpdump on port 389 to see what is the real issue

That's what I did and mentioned above:
```
As such, the request is uid=user,dc=plop,dc=net instead of uid=user,cn=group1,dc=plop,dc=net
```

Thank you

**Comment by viktorfs** [comment]
Try and change givenName to givenname. I had some issues with uppercase for some reason

**Comment by 0xmilkmix** [comment]
I'll try it this week and keep you informed. Thanks
