### ISSUE TITLE
4.7.0 Docker image released without PHP 7.1

### ISSUE THREAD

**Issue by timwsuqld** [snipe/snipe-it#7085]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
4.7.0 was released without updating the Dockerfile to reflect the dependency on PHP 7.1. 

**To Reproduce**
1. Attempt to run the docker image tag snipe/snipe-it:v4.7.0
4. A PHP syntax error is thrown

https://github.com/snipe/snipe-it/pull/7084 fixes the issue. It would be good if we can get a 4.7.1 out soon with this fix, as anyone who uses the official docker images (https://hub.docker.com/r/snipe/snipe-it/) will have a broken setup unless they use the "latest" tag that tracks master instead of the tag.

**Comment by snipe** [comment]
We're aware, and working on a point release for the docker folks.

**Comment by snipe** [comment]
https://github.com/snipe/snipe-it/releases/tag/v4.7.2
