### ISSUE TITLE
More than one LDAP Server support

### ISSUE THREAD

**Issue by loetmann** [snipe/snipe-it#7087]
**Describe the solution you'd like**
I would like to see support for more than one LDAP server. Think for example of a school: We have one domain for the administrativ staff and one for the educational environment (classrooms, teachers, pupils etc.). They are running in two different isolated networks. While the sinpe-it users are located in the administrative domain, the persons behind asset-requests would ble in the edu-net.

**Describe alternatives you've considered**
AD Federation. But this is a mess having MS AD and Samba 4 AD domains :-(. Regarding the example above there are also heavy security concerns.

**Additional context**
An alternative would be support for SAML. ;-)

**Comment by 6570** [comment]
We have this issue as well; using LDAP to try to sync users but Google Workspace has our users split up by domain name (`dc=example,dc=com`; `dc=example2,dc=com`; `dc=example3,dc=co`) so we need a way to either specify multiple directories or multiple bases in order to move away from managing users manually

**Comment by 6570** [comment]
@snipe Would it be possible to have this issue reopened? #6685 seems to be for more for fallback/load-balancing whilst this would be multiple LDAP sources

**Comment by jessenoyes-cire** [comment]
I'd like to second having this issue reopened. Having multiple LDAP sources would save us a tonne of manual intervention, as we have 2 domains in our AD forest.

**Comment by OMFCP** [comment]
Ran into a similar issue trying to get my child domains to sync via ldap.  To get the users in my child domains to sync all I had to do was add the port for the ldap global catalog server connection 3268 to the end of my ldap server entry in the settings.  I looked like ldap://server.domain:3268 and it immediately pulled in all users from all of my child domains.

**Comment by 6570** [comment]
@OMFCP Is that with Google Workspace?

**Comment by OMFCP** [comment]
> @OMFCP Is that with Google Workspace?

Sadly it is not.  What I did find though is that if I set up my different child domains as "Companies" i could define the child domain path (dc=child,dc=parnent,dc=local) as the search OU path to correctly group my users.  as far as having what appears to be 3 separate domains in Google Workspace from your earlier post (dc=example,dc=com; dc=example2,dc=com; dc=example3,dc=co), I'm not sure.

**Comment by OMFCP** [comment]
> @OMFCP Is that with Google Workspace?

Not sure if this would help but when adding a directory in your Directory Sync to sync Workspace with your On-Prem LDAP server you could try to point it to a Global Catalog, add the port 3268, and see if it changes how it shows up in your Google Workspace.  It might add them as child domains instead of multiple "parent" domains.

**Comment by devinbaeten** [comment]
In our organization we have two domains, one for students and one for staff. Right now I have to manually sync students and staff separately. It would be much appreciated if we could have multiple LDAP configurations at once.

**Comment by technomooney** [comment]
+1 to multiple domain LDAP connections.
