### ISSUE TITLE
It is not possible to select existing data when adding an asset

### ISSUE THREAD

**Issue by UserGoodtm** [snipe/snipe-it#7088]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After updating to the latest version. The program has previously added data on asset models, there are previously added data on suppliers. After the update, a new supplier has been added. When trying to add an asset, in the required fields there is no possibility to select existing asset models (do not appear for selection), there is no possibility to choose suppliers (do not appear for selection), there is no possibility to choose a location (do not appear for selection).

**Expected behavior**
When adding an asset, it should be possible to select asset models from existing ones, select suppliers from existing ones, select locations from existing ones.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.7.2 
 - OS: [e.g. Ubuntu, CentOS] CentOS Linux 7
 - Web Server: [e.g. Apache, IIS] Apache/2.4.6 (CentOS)
 - PHP Version  7.1.26

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10, CentOS Linux 7
 - Browser [e.g. chrome, safari] chrome, firefox, last ver
 - Version [e.g. 22] 74.0.3729.131

**Additional context**
- Is this a fresh install or an upgrade? Update to latest version 4.7.2
- What OS and web server you're running Snipe-IT on Apache/2.4.6 (CentOS)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) can just run php upgrade.php v4.6.18 - v4.7.2
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Temporary files and cookies have been cleared. Reboot the server with the program

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.
![1](https://user-images.githubusercontent.com/48224568/58552594-7595f300-821b-11e9-8abc-c7849522a9d6.jpg)
![2](https://user-images.githubusercontent.com/48224568/58552598-7a5aa700-821b-11e9-8b3f-6c00fd00f6cc.jpg)

**Comment by UserGoodtm** [comment]
Updating PHP to 7.3.6 did not help. Error remained

**Comment by n0creativity** [comment]
Check out this issue, it will likely resolve your issue.   
https://github.com/snipe/snipe-it/issues/7092#issuecomment-497126112

**Comment by Jarli01** [comment]
To summarize, update your installation this was just finalized moments ago.

**Comment by snipe** [comment]
@n0creativity is right, that should resolve your issue, particularly if you're running Snipe-IT behind a proxy or unusual internal DNS rules, or if you're using a custom port.
