### ISSUE TITLE
Do I need to manually upgrade the PHP version to 7.3 and then upgrade？

### ISSUE THREAD

**Issue by ChunshengZhao** [snipe/snipe-it#7089]
The version I am running now is v4.6.18, I want to upgrade to the latest v4.7.2, but I found that using "php upgrade.php" does not automatically upgrade the version of PHP, it still stays at 7.1.28, but SNIPE-IT can Normal use, do I need to manually upgrade the PHP version to 7.3 and then upgrade via "php upgrade.php"? What is the correct upgrade method?

Deployment using “install.sh” under Centos 7.

Thanks!

**Comment by ChunshengZhao** [comment]
login with root
yum remove php*
yum -y install php73 php73-mysqlnd php73-bcmath php73-cli php73-common php73-embedded php73-gd php73-mbstring php73-mcrypt php73-ldap php73-json php73-simplexml php73-process
su - snipeitapp
cd /var/www/snipeitapp
php upgrade.php
?

**Comment by ZhisongZhang** [comment]
The php7.2 is working fine for me no need to upgrade to php7.3. I have multiple attemp to use install.sh, however, all failed. below is what I did to upgrade:

sudo -s

cd /var/www/snipeit/

mkdir snipeit-bkup
cp -R /var/www/snipeit/ /var/www/snipeit-bkup 

php artisan down

rm bootstrap/cache/services.php

composer dump
php artisan cache:clear
php artisan view:clear
php artisan config:clear 

git pull 

composer install --no-dev --prefer-source
composer dump-autoload 

php artisan migrate

php artisan up

above work like a charm

**Comment by snipe** [comment]
> but I found that using "php upgrade.php" does not automatically upgrade the version of PHP, it still stays at 7.1.28

That script isn't meant to upgrade any of the systems stuff (PHP, Mysql, etc) - if it did, it would require sudo. We don't want to be messing with your system versions. (What if you had other apps running on that server that required a particular version of PHP? Running the upgrade - if it upgraded system stuff - could blow those up.)

PHP 7.2 should be just fine. It may even work with 7.1.2, so you may not have to upgrade anything, but I don't recall off the top of my head.

**Comment by ChunshengZhao** [comment]
yum -y install mod_php73 php73-mysqlnd php73-bcmath php73-cli php73-common php73-embedded php73-gd php73-mbstring php73-ldap php73-json php73-xml php73-process php73-pdo
