### ISSUE TITLE
Feature Request : E-mail Additional Asset Info when checked out and checked in

### ISSUE THREAD

**Issue by joseph707** [snipe/snipe-it#709]
hi @snipe 

Current Scenario
E-mail goes to the end-user when an asset is checked out but contains the 'Asset Name' only

Requested feature
Screenshot as an example. Contains additional info. Not a need but can work for Accessories part as well.
![capture](https://cloud.githubusercontent.com/assets/9422649/6926520/d7fe5f00-d7f7-11e4-824f-04dec4ea3bb0.PNG)

If possible an alert also stating that the Asset has been checked-in. I know it would create a lot of e-mails but using the above template, the IT user can enter additional notes under the 'Notes' section. We can write about damaged or there is dent on the Laptop edge and this is automatically conveyed to the end user via e-mail.

What do you think?

Regards

Joseph

**Comment by dbierspb** [comment]
This would be nice and should tie in with the future release of the ability to actually request specific items.

**Comment by madd15** [comment]
![snipeadditionalinfoemail](https://cloud.githubusercontent.com/assets/3274937/8769979/30e0ea38-2ee8-11e5-9a85-2fa231e76db1.png)
That is what I have come up with so far.

**Comment by snipe** [comment]
Fixed in PR https://github.com/snipe/snipe-it/pull/950
