### ISSUE TITLE
API Key Expiration After 1 Year

### ISSUE THREAD

**Issue by cwoods131** [snipe/snipe-it#7094]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
API Keys become non-functional after 1 year

**Expected behavior**
API Keys to work indefinitely or for there to be a specific spot to set the time that API Keys will expire.

**Server:**
 - Snipe-IT Version v4.4.1 - build 3636 (master)
 - Ubuntu 16.04.4 LTS

**Additional context**
We hadn't found any documentation on the expiration of API Keys and have many scripts that use Snipe-IT as a data source, with this reliance we would like to be able to not have API Keys expire or if there is a way we can set an expiration time that would also be extremely useful.

Thank you in advance!

**Comment by shinjijai** [comment]
Can we have this reopened? The API key expired for us, and I rack my brain on why all my scripts starts failing with SnipeIT for no obvious reasons.

**Comment by HinchK** [comment]
I believe this  falls under the realm of an advanced passport configuration:

https://laravel.com/docs/5.7/passport#configuration
