### ISSUE TITLE
Deleting Backups Error seemingly introduced in v4.7.0

### ISSUE THREAD

**Issue by Th3Tubby3d** [snipe/snipe-it#7098]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
It appears `laravel-backup.backup.name` was changed to `backup.backup.name` in `app/Http/Controllers/SettingsController.php` during commit [6cd25fb](https://github.com/snipe/snipe-it/commit/6cd25fbdebb09e3f31cb3971399d0c8c74d4b8d8), but it seems it was missed for `public function deleteFile($filename = null)` causing backup deletes to fail.

**To Reproduce**
1. Go to 'https://snipeit.example/admin/backups'
2. Click on 'a delete/trash icon next to a backup'
3. See error `Error: That backup file could not be found on the server.`

**Expected behavior**
A file attempting to be deleted to be removed and display a success message.

**Screenshots**
I hope these are unnecessary, but I'll gather some if helpful.

**Server (please complete the following information):**
 - Snipe-IT Version `v4.7.0 - build 4037 (master)`
 - OS: `Ubuntu 18.04 Server`
 - Web Server: `Apache`
 - PHP Version `PHP 7.2.17-0ubuntu0.18.04.1`

**Desktop (please complete the following information):**
 - OS: `OSX`
 - Browser `Chrome, Firefox, Safari`
 - Version `Multiple`

**Error Messages**
- Please see above.

**Additional context**
- Is this a fresh install or an upgrade? `upgrade`
- What OS and web server you're running Snipe-IT on `see above`
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) `git`
- Include what you've done so far in the installation, and if you got any error messages along the way. `see above`
- Indicate whether or not you've manually edited any data directly in the database `have not`

**Comment by snipe** [comment]
On line 1015 in app/Http/Controllers/SettingsController.php, change:

```
$path = storage_path().'/app/'.config('laravel-backup.backup.name');
```

to 

```
 $path = storage_path().'/app/'.config('backup.backup.name');
```

And let me know if that helps.

**Comment by Th3Tubby3d** [comment]
Sorry, I should have mentioned the fix... I was just trying to find the best way to bring it to your attention. It definitely fixed it. Thank you for the reply.
