### ISSUE TITLE
./config/backup.php hard-coded e-mail placeholder causes errors on backup generation

### ISSUE THREAD

**Issue by Th3Tubby3d** [snipe/snipe-it#7099]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
It appears that line 135 of ./config/backup.php references a hard-coded placeholder (`            'to' => 'your@example.com',`) instead of configured values from something like https://snipeit.example/admin/notifications ($setting->alert_email maybe?). This is easily fixed by manually modifying the file, but this reverts when upgraded as it doesn't appear it was intended to be directly modified.

**To Reproduce**
1. Go to 'https://snipeit.example/admin/backups'
2. Click on 'Generate Backup' with SMTP configured
3. See error `Whoops, looks like something went wrong.`

**Expected behavior**
I believe the intended/expected behavior is to have this value pulled from configuration elsewhere, but it seems to be a placeholder instead.

**Screenshots**
I believe in this scenario these are unnecessary, but I'll gather some if helpful.

**Server (please complete the following information):**
 - Snipe-IT Version `v4.7.3 - build 4098 (master)`
 - OS: `Ubuntu 18.04 Server`
 - Web Server: `Apache`
 - PHP Version `PHP 7.2.17-0ubuntu0.18.04.1`

**Desktop (please complete the following information):**
 - OS: `OSX`
 - Browser `Chrome, Firefox, Safari`
 - Version `Multiple`

**Error Messages**
- `(1/1)                                     Swift_TransportException                                                                  Expected response code 354 but got code "503", with message "503 5.5.1 Bad sequence of commands "
--
in AbstractSmtpTransport.php line 457
at Swift_Transport_AbstractSmtpTransport->assertResponseCode('503 5.5.1 Bad sequence of commands ', array(354))in AbstractSmtpTransport.php line 341
at Swift_Transport_AbstractSmtpTransport->executeCommand('DATA ', array(354), array('your@example.com', 'your@example.com', 'your@example.com', 'your@example.com'), false, null)in EsmtpTransport.php line 305
at Swift_Transport_EsmtpTransport->executeCommand('DATA ', array(354), array('your@example.com', 'your@example.com', 'your@example.com', 'your@example.com'))in AbstractSmtpTransport.php line 390
at Swift_Transport_AbstractSmtpTransport->doDataCommand(array('your@example.com', 'your@example.com', 'your@example.com', 'your@example.com'))in AbstractSmtpTransport.php line 497`

**Additional context**
- Is this a fresh install or an upgrade? `upgrade`
- What OS and web server you're running Snipe-IT on `Ubuntu 18.04 Server` `Apache`
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) `git`
- Include what you've done so far in the installation, and if you got any error messages along the way. `see above`
- Indicate whether or not you've manually edited any data directly in the database `have not`

`The backup does complete, despite the error. I tried to briefly review to see if it's intended to be replaced during install or something of the like, but was unable to find anything. If this isn't a bug, I apologize. `

**Comment by snipe** [comment]
You can change it to null:

```
'mail' => [
            'to' => null,
        ],
```

**Comment by snipe** [comment]
The fix is now on master. If you'd like to use backup notifications, add this to your .env in the email settings:

`MAIL_BACKUP_NOTIFICATION_ADDRESS=you@example.com`

(replacing `you@example.com` with a real address that you want to receive notifications to, of course.)

Then clear your config:

`php artisan config:clear`

If don't add that line to your .env, no email will be attempted.

**Comment by snipe** [comment]
(Note that the backup package doesn't actually attach the backup file, it just lets you know that one completed successfully, and notifies you if it didn't complete successfully, so it may or may not be useful, depending on your use-case.)

**Comment by snipe** [comment]
This is what the notification looks like if you enable them and have a successful backup, btw:

<img width="516" alt="Screen Shot 2019-05-29 at 7 22 43 PM" src="https://user-images.githubusercontent.com/197404/58603867-2e255c00-8247-11e9-9837-bd9a8f18295f.png">

**Comment by Th3Tubby3d** [comment]
Awesome. Thank you again. I had changed the e-mail address to an appropriate one previously and they were working, but when I upgraded earlier today it reverted, so I figured I would mention it.

**Comment by snipe** [comment]
No problem - thanks for the heads up!
