### ISSUE TITLE
The package has modified files during update

### ISSUE THREAD

**Issue by gilesytheking** [snipe/snipe-it#7102]
I have just updated my snipe install and came across the following whilst updating.

```
--------------------------------------------------------
Step 5: Updating composer dependencies:
(This may take an moment.)
--------------------------------------------------------

The package has modified files:
    M run-tests.sh
    Discard changes [y,n,v,d,s,?]? 
```

I took a stab and selected "Y" for this, my installation has completed and snipe is back up and running.

However what is the correct option to select for this scenario on future updates?

**Comment by snipe** [comment]
Y is the correct choice :)
