### ISSUE TITLE
Parse error: syntax error

### ISSUE THREAD

**Issue by jmartins1** [snipe/snipe-it#7108]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When upgrading from v4.6.18 to 4.7.0 or later. 
Unable to run the following commands without error:

composer install --no-dev --prefer-source
composer dump-autoload
php artisan config:clear
php artisan config:cache

Receive the following error:

Parse error: syntax error, unexpected '?' in C:\wamp\www\snipe-it\vendor\laravel
\framework\src\Illuminate\Foundation\helpers.php on line 233

**To Reproduce**
Download appropriate version SnipeIT version; in this case 4.7.0 or later.
Placed release in C:\wamp\www\snipe-it and moved over .env and other necessary contain from old installation to new installation, e.g. 

C:\wamp\www\snipe-it\*.env
C:\wamp\www\snipe-it\storage\*.key
C:\wamp\www\snipe-it\public\uploads
C:\wamp\www\snipe-it\storage\private_uploads

Ran the following commands

CD C:\wamp\www\snipe-it
composer install --no-dev --prefer-source (Release downloaded appropriately)
composer dump-autoload (Received Parse error indicated above)
php artisan config:clear (Received Parse error indicated above)
php artisan config:cache (Received Parse error indicated above)

Re-Ran:
composer install --no-dev --prefer-source 

Indicated:
C:\wamp\www\snipe-it>composer install --no-dev --prefer-source
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump

Parse error: syntax error, unexpected '?' in C:\wamp\www\snipe-it\vendor\laravel
\framework\src\Illuminate\Foundation\helpers.php on line 233

**Expected behavior**
SnipeIT did install but may indicate issues later due to the inability to run commands without error.
composer install --no-dev --prefer-source (Received Parse error indicated above)
composer dump-autoload (Received Parse error indicated above)
php artisan config:clear (Received Parse error indicated above)
php artisan config:cache (Received Parse error indicated above)

**Screenshots**

**Server (please complete the following information):**

Snipe-IT version | v4.7.0 build 4037()
Software License | AGPL3
PHP Version | 7.3.1
Laravel Version | 5.5.45

**Desktop (please complete the following information):**
 - OS: Server 2012 R2, running SnipeIT on latest version (3.1.7) of Wampserver
 - Browser Chrome
 - Version Latest version (Version 74.0.3729.169 (Official Build) (64-bit))

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error.

Does not appear to indicate any issues.
![Error](https://user-images.githubusercontent.com/31219479/58721682-c4b26400-8392-11e9-9cf8-fe11e36e1ef7.jpg)

[Error.pptx](https://github.com/snipe/snipe-it/files/3242149/Error.pptx)

Logs attached:
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- upgrade from v4.6.18 to 4.7.0 or later. 
- What method you used to install Snipe-IT (Wampserver)
![vers](https://user-images.githubusercontent.com/31219479/58721143-66d14c80-8391-11e9-8b7b-0af23b25d403.jpg)

- Include what you've done so far in the installation, and if you got any error messages along the way.
Attempted steps found here: https://snipe-it.readme.io/docs/getting-help

Ran:
composer dump-autoload
composer clear-compiled
php artisan config:clear
php artisan view:clear
php artisan cache:clear
php artisan route:clear

Received the following error after each command:
Parse error: syntax error, unexpected '?' in C:\wamp\www\snipe-it\vendor\laravel
\framework\src\Illuminate\Foundation\helpers.php on line 233

- Indicate whether or not you've manually edited any data directly in the database
Did not

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
That's the null coalesce operator, which was introduced in PHP7, so I'm guessing perhaps your command line PHP version isn't the same as the one your web server uses. Make sure your php-cli is also at 7+

**Comment by jmartins1** [comment]
My PHP version is 7.3.1. It appears my PHP CLI version is also 7.3.1

![error](https://user-images.githubusercontent.com/31219479/58725191-c6345a00-839b-11e9-8fca-af508081e1a2.jpg)

**Comment by jmartins1** [comment]
Thought I'd share.

This morning I attempted the 4.7.4 release and had no issues installing SnipeIT.
Prior to installation I updated my Composer to the latest version. I was able to run SnipeIT in PHP 7.2.14 and 7.3.1 without issue. Not sure if this was a change to SnipeIT or my upgrade to the latest composer; my only change.

Commands work as expected:
composer install --no-dev --prefer-source 
composer dump-autoload 
php artisan config:clear
php artisan config:cache

**Comment by jmartins1** [comment]
To add to my previous comment. 

Running commands stopped working again.
composer install --no-dev --prefer-source
composer dump-autoload
php artisan config:clear
php artisan config:cache

I reinstalled latest copy of Composer. The commands work again.

Interesting?
when I run composer update, it downloaded and installed approx. 30 updates.
when I run composer install --no-dev --prefer-source it removed approx. 29 of the updates. 

Why is this happening?

**Comment by jmartins1** [comment]
Closing this issue. I upgraded my installation of WAMP server 3.1.7 to 3.1.9. This resolved the indicated issues.

**Comment by HinchK** [comment]
> To add to my previous comment.
> 
> Running commands stopped working again.
> composer install --no-dev --prefer-source
> composer dump-autoload
> php artisan config:clear
> php artisan config:cache
> 
> I reinstalled latest copy of Composer. The commands work again.
> 
> Interesting?
> when I run composer update, it downloaded and installed approx. 30 updates.
> when I run composer install --no-dev --prefer-source it removed approx. 29 of the updates.
> 
> Why is this happening?

I am glad you got your installation running; when i first started i did the same "WTF?!" WRT `composer update` and `composer install`.

When it comes to Snipe-IT; @snipe has set the versions of the composer-packages that she wants by committing the composer.lock file.   In short, composer install will look to the lock file first for explicit instructions on pacakage + versions.

`composer update` take the much more flexible version information in `composer.json` (e.g."php": ">=7.1.2).  `composer update` will look for the latest version (as directed by the symbols) of all in packages in composer.json.  THEN, it writes a new composer.lock.

For Snipe-IT development; this means on master while i'm hunting bugs or testing something, i stick to composer install, because that's what is run in production environments.

**Comment by larsonreever** [comment]
Yes you may need to update your PHP CLI version from 7.3.1. This article here puts a detailed light on this hope you may find it helpful. https://secure.wphackedhelp.com/blog/fix-parse-error-syntax-error-unexpected-wordpress/

<blockquote><img src="https://secure.wphackedhelp.com/blog/wp-content/uploads/2019/06/fix-Syntax-Error-in-WordPress.png" width="48" align="right"><div>WP Hacked Help Blog - Latest WordPress Security Updates</div><div><strong><a href="https://secure.wphackedhelp.com/blog/fix-parse-error-syntax-error-unexpected-wordpress/">Parse Error: Syntax Error Unexpected in WordPress [FIXED]</a></strong></div><div>Parse Error: Syntax Error Unexpected ‘ ‘ in WordPress Trying something new on your WordPress site? Got any of the following errors like ⚠️ parse error: syntax error, unexpected t_string wordpress, ⚠️ parse error syntax error unexpected end of file in wordpress, ⚠️ parse error: syntax error, unexpected t_function wordpress, …</div></blockquote>
