### ISSUE TITLE
Do not update next-increment field when the asset tag number is changed while creating an asset.

### ISSUE THREAD

**Issue by vtacquet** [snipe/snipe-it#7112]
**Server (please complete the following information):**
 - Snipe-IT Version v4.6.16 build 4018
 - OS: [e.g. Ubuntu, CentOS] CentOS 7.6.1810 Docker Version
 - Web Server: [e.g. Apache, IIS] Docker Version
 - PHP Version Docker Version

**Is your feature request related to a problem? Please describe.**
We use the auto-increment asset tags but we do not label all assets with a tag (because they have a number on their own or because it is not convenient ex a digital doorkey). If a new asset is created with an auto-incremented tag and that tag is not used because we change it to the number printed on the asset or something else; it would be nice NOT to keep incrementing the tag. Currently we add our items without asset tag (it auto increments every time) and afterwards we go to the settings to change the next-increment back. This is a burden. 

**Describe the solution you'd like**
If the asset tag is changed - so if the auto increment is not used - do not update the next-increment field.

**Describe alternatives you've considered**
There are none.

**Additional context**
It is clear in the solution.

**Comment by vtacquet** [comment]
Sure it still is. Auto-increment should only update the next-increment field when the asset tag was not changed during creation.

**Comment by cybtachyon** [comment]
We definitely still need this one - it's on our backlog to get to it.
