### ISSUE TITLE
SnipeIT blank after upgrade to 4.7.4

### ISSUE THREAD

**Issue by dvogelho** [snipe/snipe-it#7114]
I ran php upgrade.php and after the upgrade I just get a blank page.
Following error appears in the php.log 

[Mon Jun 03 13:39:35.058257 2019] [:error] [pid 13372] [client 10.17.224.145:53012] PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0

[Mon Jun 03 13:39:35.058662 2019] [:error] [pid 13372] [client 10.17.224.145:53012] PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/html/snipe-it/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 24

If I try to run the php upgrade.php again, I receive an error in step 1 and step 6

--------------------------------------------------------
STEP 1: Backing up database: 
--------------------------------------------------------

-- Starting backup...

In BackupDestination.php line 147:
                                             
  Parse error: syntax error, unexpected '?'  

--------------------------------------------------------
Step 6: Migrating database:
--------------------------------------------------------

-- 
In PDOConnection.php line 24:
                                                                              
  Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)  

Debug mode is enabled, but there's no further error message shown. Just a blank page.

- Is this a fresh install or an upgrade? Upgrade to 4.7.4
- Version of Snipe-IT you're running - 4.7.4
- Version of PHP you're running - PHP 7.0.33-0+deb9u3 (cli) (built: Mar  8 2019 10:01:24)
- Version of MySQL/MariaDB you're running - mysql  Ver 15.1 Distrib 10.1.38-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- What OS and web server you're running Snipe-IT on - Server version: Apache/2.4.25 (Debian)
Server built:   2019-04-02T19:05:13
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - php upgrade.php
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - No error shown
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - Home page
- Any errors that appear in your browser's error console. - No errors

- Include any additional information you can find in `storage/logs` and your webserver's logs.
[2019-05-31 07:11:33] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/html/sn$
Stack trace:

**Comment by ThomasDE91** [comment]
I had the same issue. Try to disable PHP 7.0:
a2dismod  php 7.0 and restart your web server after that. It should work after that. If you get text aonly after that enable php7.3 a2enmod php7.3 and restart the web server one more time

**Comment by syaoran68** [comment]
yea i'm also having this happen? i'm currently on php version 7.0+35ubuntu 6.1. should i upgrade the php version to 7.1?

**Comment by ThomasDE91** [comment]
At least 7.1 if you want to continue to use snipe-it. Please check this site -> https://www.php.net/supported-versions.php PHP 7.1 will soon reacht it's EOL... I'd go for 7.2 or 7.3 if you are able to.

**Comment by syaoran68** [comment]
I updated the php to 7.3 and set it as the default for ubuntu but it looks like snipe is still trying to use 7.0? i still get the same T_VARIABLE error. do i have to make an adjustment the .env file to set the php default usage?

Thanks for the support!

![Screen Shot 2019-06-03 at 12 03 33 PM](https://user-images.githubusercontent.com/43255653/58827346-a6996d80-85f7-11e9-9640-a5bf3fbbb2d9.png)

**Comment by ThomasDE91** [comment]
if you want to rule out PHP 7.1 do a2dismod php 7.0 and restart apache. Have you installed all the dependencie php modules ?

sudo apt-get install php7.3-mbstring php7.3-xml php7.3-mcrypt php7.3-gd php7.3-zip php7.3-curl php7.3-bcmath (took this from a how to and changed 7.0 to 7.3)

I have the following packages installed on my box 

root@***:/var/www/html/snipe-it# dpkg --get-selections | grep -i php7.3
libapache2-mod-php7.3                           install
php7.3                                          install
php7.3-bcmath                                   install
php7.3-cli                                      install
php7.3-common                                   install
php7.3-curl                                     install
php7.3-gd                                       install
php7.3-json                                     install
php7.3-ldap                                     install
php7.3-mbstring                                 install
php7.3-mysql                                    install
php7.3-opcache                                  install
php7.3-phpdbg                                   install
php7.3-readline                                 install
php7.3-xml                                      install
php7.3-xmlrpc                                   install
php7.3-zip                                      install

**Comment by syaoran68** [comment]
ok so i installed all the items that you mentioned above, but for some odd reason it now doesn't allow me in it says system unavailable when i try to access the website. not sure if this is an issue with the files or? i've looked in the access and error logs and theres nothing new that crops up

thank you for the help. i'm a new sys admin that is taking over another sys admin's implementation so i'm new to the snipeIT system

**Comment by ThomasDE91** [comment]
Please share a screenshot of the error. Your application might still be in maintenance mode.

**Comment by syaoran68** [comment]
ah i totally forgot that i put it into maintenance mode. i thank you so much for that. haha. thanks for the prompt responses as well you guys are A+. btw, do you guys have any guides for migrating from a github deployment over to a docker deployment? i think it would be much more streamlined to deploy in a docker container. 

Thanks!

**Comment by syaoran68** [comment]
ah that was the trick. i had forgotten i had turned maintenance mode on at the time. Thank you soo much for the prompt responses. 

on a side note. is there a migration pattern for the native curl installs to be migrated over to a docker container. i'm gonna continue to use snipe-IT but i'd just like it in a slightly better management container haha.

Thank you so much again

**Comment by ThomasDE91** [comment]
Glad to hear that it worked out :) 
Just use the github version. Very simple to upgrade by using onboard php script.

**Comment by dak-csis** [comment]
Thank you for this. I was about to post a bug report but github hooked me up to a related post (this one) which told me to upgrade PHP to 7.3
