### ISSUE TITLE
Metric Units

### ISSUE THREAD

**Issue by mheelein** [snipe/snipe-it#7124]
When will we see the Implementation of Metric units in SnipeIT?
Especially as the majority of our planet uses the Metric system, I really dont understand why the Imperial system was chosen over the Metric system. Even NASA uses the Metric system.
I know this has been requested plenty of times, but there seems to be nothing but silence about it.
A update would be nice.
/rant
I still <3 Snipe

**Comment by stbc** [comment]
#6749

**Comment by stbc** [comment]
+1

**Comment by stbc** [comment]
Still relevant. See https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Metrication.svg/1280px-Metrication.svg.png
The red countries are NOT using the metric system... :')

**Comment by stbc** [comment]
Noes....

How do I reopen this?!
