### ISSUE TITLE
IP works, URL doesnt. 

### ISSUE THREAD

**Issue by mrmcox** [snipe/snipe-it#7125]
Hi All,

Got a successful instal of SnipIT running and when I go to the IP of the server all is good. When I setup a DNS records to allow for assets.comapny.com I get the apache server landing page. 

What am I missing?

Thanks.

**Comment by brandenwagner** [comment]
Your apache config is not set up to have the virtual host response to that name. 
```
<VirtualHost *:80>
    DocumentRoot "/your/file/path"
    ServerName assets.company.com

    # Other directives here
</VirtualHost>
```
