### ISSUE TITLE
Database Migration error SQLSTATE[HY000]: General Error

### ISSUE THREAD

**Issue by 101Lizardman** [snipe/snipe-it#7132]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I am upgrading from Snipe-it v  to v4.7.4

When attempting to migrate the database with `php artisan migrate`, I get a syntax error:
![image](https://user-images.githubusercontent.com/48175765/59082595-44ae7000-8937-11e9-84d6-edd489751c72.png)

...so I edit the file and remove the offending character...
![image](https://user-images.githubusercontent.com/48175765/59082617-5c85f400-8937-11e9-8f71-dee9c308ebce.png)

...and am then met with a collection of different errors:
![image](https://user-images.githubusercontent.com/48175765/59082636-70315a80-8937-11e9-9b01-b0ee3ce96421.png)

I have not received any error messages prior to this.

**Expected behavior**
A migration of the database

**Screenshots**
Shown above

**Server (please complete the following information):**
 - Snipe-IT Version: Upgrading from v to v4.7.4 
 - OS: Ubuntu 16.04.2
 - Web Server: Apache2
 - PHP Version: 7.0.18 

**Error Messages**
Error occurring on server, not site. See above for error messages.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade?  
Upgrade from v to v4.7.4
- What OS and web server you're running Snipe-IT on? 
Ubuntu, Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)? 
Git pull and [the upgrade page](https://snipe-it.readme.io/v4.0/docs/upgrading-to-v4)
- Include what you've done so far in the installation, and if you got any error messages along the way. 
Everything up until the database migration, no other error messages
- Indicate whether or not you've manually edited any data directly in the database
I have not manually edited any data.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by ThomasDE91** [comment]
Your PHP Version is below the required Version of at least 7.1.3. Check the following Bug. It has the solution for this issue:
https://github.com/snipe/snipe-it/issues/7114
