### ISSUE TITLE
Can't deactivate personal emails

### ISSUE THREAD

**Issue by cduverne** [snipe/snipe-it#7133]
#### Please confirm you have done the following before posting your bug report:

- [N/A] I have enabled debug mode 
- [*] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
All users are receiving individual mails when "Expected Checkin date" is close.

**Expected behavior**
Deactivate individual mails to users

**Server (please complete the following information):**
 - Snipe-IT Version : 4.7.4
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version : SnipeIT Docker embedded version

**Additional context**
- Is this a fresh install or an upgrade? Upgrade
- What OS and web server you're running Snipe-IT on : Docker version
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) : Docker

**Comment by mahesh2471990** [comment]
There is no option In GUI to disable the Excepted Checkin mail.

But that is one of the good features so the user will get a notification when they have returned the laptop.

It just reminder mail sent when you generate the PHP artisan for excepted-check-in.

**Comment by cduverne** [comment]
I don't want my users to receive daily mails about the assets with a close "expected check in" date.
How can I avoid this ?

**Comment by bwoiderski** [comment]
We are experiencing the same thing. I wouldn't mind a single reminder one week out and then another reminder on the due date, but daily emails will just be deleted. There are some users for whom I'd like to disable alerts altogether.

**Comment by cduverne** [comment]
Hello guys, 
This is indeed a feature which would be good.
Having the possibility to edit all parameters from the UI would be wonderful !
In the meantime, how can I deactivate these alerts ? 
Thanks

**Comment by HinchK** [comment]
@cduverne i remove the "email" field from the user accounts who I would not want to receive notifications.
