### ISSUE TITLE
Session not timing out on browser or even after browser close  - snipe it

### ISSUE THREAD

**Issue by muianelson** [snipe/snipe-it#7136]
Snipe-it session is not timing out. Kindly assist.

Below are my env settings
# --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_LIFETIME=10
EXPIRE_ON_CLOSE=true
ENCRYPT=true
COOKIE_NAME=snipeit_session
COOKIE_DOMAIN=null
SECURE_COOKIES=true

NB: we have implemented ldap authentication

**Comment by Cidwill** [comment]
We are having this same issue.  Could it be re-opened?

Our settings are as follows and we also have LDAP enabled for accounts.

# --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_LIFETIME=10
EXPIRE_ON_CLOSE=true
ENCRYPT=false
COOKIE_NAME=snipe
COOKIE_DOMAIN=null
SECURE_COOKIES=false

**Comment by Cidwill** [comment]
After some testing it appears this is only an issue for LDAP accounts.  It's likely related to #6482

**Comment by Cidwill** [comment]
If I manually delete the remember_me cookie and the snipeit_session cookie then the session expires correctly.

Since I assume the snipeit_session cookie is set to delete on the configured settings from var does this mean the remember_me cookie is not being removed alongside it ?
