### ISSUE TITLE
Custom Asset Report -- Generate duplicated asset rows

### ISSUE THREAD

**Issue by strive1314** [snipe/snipe-it#7137]
#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode 
- [yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
There are duplicated asset rows in the generated custom asset report. 

**To Reproduce**
1. Go to 'Customize Report'
2. Click on 'Generate'
3. Open the generated .csv file.

**Expected behavior**
The custom asset report should be the same with the data in database, and no duplicated rows.

**Screenshots**
![image](https://user-images.githubusercontent.com/30042989/59144641-008d9f00-8a0d-11e9-9f4b-239b43e9da88.png)
![image](https://user-images.githubusercontent.com/30042989/59144733-798cf680-8a0d-11e9-916c-3310d9d69afb.png)

**Server (please complete the following information):**
 - Snipe-IT Version: [v4.6.15 - build 4011 (master).]
 - OS: [Ubuntu]
 - Web Server: [Apache]

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [ 63.0.3239.132]

**Error Messages**
- No error message
- Confirm whether the error is NOT reproducible on the demo: https://snipeitapp.com/demo.

**Additional context**
- Is this a fresh install or an upgrade? [fresh install]
- What OS and web server you're running Snipe-IT on [Ubuntu]
- What method you used to install Snipe-IT [docker]
- Include what you've done so far in the installation, and if you got any error messages along the way.
  I checked the data in database is correct, only get duplicated assets rows in custom asset report.
- Indicate whether or not you've manually edited any data directly in the database
  No manually edit data directly in the database.

**Comment by strive1314** [comment]
Did someone get this error like me?

**Comment by firmank** [comment]
no i dont.
mine is quite different.  i cannot download more then 18027 row on custom report
