### ISSUE TITLE
iis error when click on report it ask for authentication.

### ISSUE THREAD

**Issue by thien154** [snipe/snipe-it#714]
![image](https://cloud.githubusercontent.com/assets/10879686/6933158/d6806956-d84d-11e4-8a42-2a4d360b56e0.png)

**Comment by snipe** [comment]
That looks like a server configuration issue on your end. Nothing we have would ask for http basic auth.

**Comment by thien154** [comment]
thank for quick response. it it working well on apache. how to config authentication on iis? this is my config on iis.
![image](https://cloud.githubusercontent.com/assets/10879686/6933234/b760dece-d84e-11e4-88a4-0582a95b3a4e.png)

**Comment by thien154** [comment]
i try one by one all that authentication mods none of them work

**Comment by snipe** [comment]
Configuration for IIS is outlined here: http://snipeitapp.com/documentation/installing-on-iis/
