### ISSUE TITLE
Hello Team, Does Snipe-IT software support Microsoft SQL Server ? OR Does it need only MYSQL and MariaDB

### ISSUE THREAD

**Issue by Aishwarya1146** [snipe/snipe-it#7140]
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by EarlRamirez** [comment]
I will have to go off on a limb and say, no it does support mssql

**Comment by tankerkiller125** [comment]
I tested this and I was unable to get it working with Microsoft SQL Server, both Dev, Express, and Regular. I recommend using MySQL or MariaDB
