### ISSUE TITLE
[Question] How I can update to a newer version or the developer version

### ISSUE THREAD

**Issue by maxlehot1234** [snipe/snipe-it#7147]
Hey,

I try to update for like a month now and I am not able to.

Each time I do php upgrade.php, I got permission denied, so no upgrade can be done.

If I try php composer.phar install --no-dev --prefer-source I still having permission denied, so can't do anything :(

If I try to put sudo in the front of the command, doesn,t work since I cant run it as admin...

So what thing I can do?

This is the ls-l of the snipe-it folder under /var/www

drwxr-xr-x 17 root     root         4096 mai 14 19:36 app
-rw-r--r--  1 root     root         1646 mai 14 19:36 artisan
-rw-r--r--  1 root     root        65260 mai 15 15:47 asset_05152019_034705.csv
drwxr-xr-x  3 root     root         4096 mai 14 19:36 bootstrap
-rw-r--r--  1 root     root          875 mai 14 19:36 bower.json
-rw-r--r--  1 root     root         9210 mai 14 19:36 c3.php
-rw-r--r--  1 root     root          373 mai 14 19:36 codeception.yml
-rw-r--r--  1 root     root         3228 mai 14 19:36 CODE_OF_CONDUCT.md
-rw-r--r--  1 root     root         2382 mai 22 09:47 composer.json
-rw-r--r--  1 root     root       238348 mai 22 09:47 composer.lock
-rwxr-xr-x  1 root     root      1914314 mai 15 11:39 composer.phar
drwxr-xr-x  2 root     root         4096 mai 22 09:47 config
-rw-r--r--  1 root     root          317 mai 14 19:36 CONTRIBUTING.md
-rw-r--r--  1 root     root           90 mai 14 19:36 crowdin.yml
drwxr-xr-x  5 root     root         4096 mai 14 19:36 database
drwxr-xr-x  2 root     root         4096 mai 14 19:36 docker
-rw-r--r--  1 root     root         3265 mai 14 19:36 Dockerfile
-rw-r--r--  1 root     root         1711 mai 14 19:36 gh-changelog.php
drwxrwxr-x 15     1002     1002     4096 mai 15 12:47 ImageMagick-7.0.8-45
-rw-r--r--  1 root     root     13726133 mai 12 15:53 ImageMagick.tar.gz
-rw-r--r--  1 root     root          956 mai 14 19:36 index.html
-rwxr-xr-x  1 root     root          371 mai 14 19:36 install.sh
-rwxr-xr-x  1 root     root        34519 mai 14 19:36 LICENSE
-rw-r--r--  1 root     root       450983 mai 14 19:36 npm-shrinkwrap.json
-rw-r--r--  1 root     root         1760 mai 14 19:36 package.json
-rw-r--r--  1 root     root         1097 mai 14 19:36 phpunit.xml
drwxr-xr-x  8 root     root         4096 mai 22 09:47 public
-rw-r--r--  1 root     root        45765 mai 14 19:36 README.md
drwxr-xr-x  6 root     root         4096 mai 14 19:36 resources
drwxr-xr-x  3 root     root         4096 mai 14 19:36 routes
drwxr-xr-x  2 root     root         4096 mai 14 19:36 sample_csvs
-rw-r--r--  1 root     root          567 mai 14 19:36 server.php
-rwxr-xr-x  1 root     root        21737 mai 14 19:36 snipeit.sh
drwxr-xr-x  8 www-data www-data     4096 mai 15 15:57 storage
drwxr-xr-x 10 root     root         4096 mai 14 19:36 tests
-rw-r--r--  1 root     root         6229 mai 14 19:36 upgrade.php
-rw-r--r--  1 root     root         3435 mai 14 19:36 Vagrantfile
drwxr-xr-x 52 root     root         4096 mai 15 12:55 vendor
-rw-r--r--  1 root     root         2133 mai 14 19:36 webpack.mix.js

I think the issue comes from permissions, but not so sure and I am not sure of which things I need to change and how?

Thanks again for your help

**Comment by EarlRamirez** [comment]
What OS  are you running, root should never be the owner of these files so dependingbon your OS run the following commands.

Chown www-data.www-data /path/to/Snipe-IT (for debian base OS) 
Chown apache.apache /path/to/Snipe-IT (for Redhat based OS)

Then run
Sudo -u apache or www-data php upgrade.php

**Comment by maxlehot1234** [comment]
Hey,

I just try and I have the same problem by running:
dudo -u www-data php upgrade.php

https://gist.github.com/maxlehot1234/7c7de41ae4b77db361b595234f6c1aa8

Permission non accordée means No permission
Impossible d'accéder means Can't access

**Comment by maxlehot1234** [comment]
Anyone?
