### ISSUE TITLE
File Uploads in User Section shows "admin/hardware/general.filetype_info" instead of allowed MIME Types

### ISSUE THREAD

**Issue by gitpel** [snipe/snipe-it#7151]
**Describe the bug**
Under the section **Users (People) > Select any user > File Uploads ** 
Insead of allowed MIME file types it shows: **"admin/hardware/general.filetype_info"** and the standard button **Select File**
The issue only at Users section and not appers in Assets sections

**To Reproduce**
1. Go to Users (People) > Select any user 
2. Click on File Uploads 
3. See error

**Server (please complete the following information):**
 - Snipe-IT version 	v4.7.4 build 4107 (g49a255c8f)
 - PHP Version 	7.2.19-0ubuntu0.18.04.1
 - Laravel Version 	5.5.45 
 - Server version: Apache/2.4.29 (Ubuntu) Server built:   2019-04-03T13:22:37
 - Ubuntu 18.04.2 LTS
 - SnipeIT Language EN

**Desktop (please complete the following information):**
 - OS: any
 - Browser any

**Smartphone (please complete the following information):**
 - Browser any

**Comment by hdub-tech** [comment]
Can confirm this is still an issue in: 

* Snipe-IT version | v4.7.8 build 4170 (g4fe689dc5)
* PHP Version | 7.1.33
* Laravel Version | 5.5.47
* Hosted

<img width="573" alt="Screen Shot 2019-12-11 at 6 15 14 PM" src="https://user-images.githubusercontent.com/14808878/70671654-623ff780-1c42-11ea-89f6-d4498be79054.png">

**Comment by swift2512** [comment]
Isn't this a missing translation string in **\resources\views\hardware\qr-view.blade.php** ?
This file has` <p><p>{{ trans('admin/hardware/general.filetype_info') }}</p>.</p>` in the code, but filetype_info is missing in **\resources\lang\en\admin\hardware\general.php**

**Comment by uberbrady** [comment]
This isn't the case any more, it now shows the list of acceptable files.
