### ISSUE TITLE
Error trying to generate API key.

### ISSUE THREAD

**Issue by hsigor** [snipe/snipe-it#7154]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When attempting to generate an API Key the attached message is returned

**To Reproduce**
1. Go to 'You can do this through the Snipe-IT web interface, by going to your account dropdown in the top right and clicking on "Manage API Keys".'

2. Click on 'Create new Token!'

**Screenshots**

![Capturar](https://user-images.githubusercontent.com/49869736/59363226-354e6e80-8d0b-11e9-9ed3-14e66aa8881f.PNG)

**Server (please complete the following information):**
 - Snipe-IT Version 4.7.4
 - OS: [Microsoft Windows]
 - Web Server: [Apache]
 - PHP Version: 7.3.5

**Desktop (please complete the following information):**
 - OS: [Microsoft Windows]
 - Browser [ Chrome]
 - Version [75.0.3770.80]

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy S9]
 - OS: [Android 9]
 - Browser [Chrome]
 - Version [74.0.3729.157]

**Additional context**
- Is this a fresh install or an upgrade? 
      * New Instalation
- What OS and web server you're running Snipe-IT on
      * Windows 10 Pro 64 and Apache 2.4.39
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
      * Manual instalation.
- Include what you've done so far in the installation, and if you got any error messages along the way.
      * No. I don't received any massage.
- Indicate whether or not you've manually edited any data directly in the database
      * No. It's a new and clean instalation.

**Comment by fbibeau** [comment]
I'm experiencing the same issue on version v4.6.15. Let me know if I need to provide details also.

**Comment by fbibeau** [comment]
Any update on this issue?

**Comment by doogalbeez** [comment]
I am having the same issues. Unable to create the API when logged in to the web interface, but able to get one created via the CLI. However, it doesn't work from my workstation to the server either. I'm going to dig around the forum for this issue and I'll try to update if I get anywhere.

>  [Invoke-SnipeitMethod] You are not Authorized to access the resource, check your token is correct

**Comment by fbibeau** [comment]
I was able to resolve it on my side by upgrading to PHP 7.3 & to the latest version of SnipeIT.

**Comment by MFeil21** [comment]
Thread is closed but I have the same problem. Fresh install with the latest version on a Windows 2019 Server using XAMPP. When I try to generate an API key I get the following messge: Whoops! Something went wrong! Server Error

![Screenshot (6)](https://user-images.githubusercontent.com/94377348/141798420-7d15a2d4-709d-43be-9255-682489b31bc3.png)

However it creates a new entry here for every time I try to create a key but I don't get a notification with this very long  personal access token and the name is missing from the list.

![Screenshot (8)](https://user-images.githubusercontent.com/94377348/141798579-c45f465c-c0ff-4e79-bfde-0cfd2cb2a34f.png)
 
I ran both php artisan passport:install and php artisan passport:client --personal successfully. 

Please help me what I am doing wrong. The rest works perfectly but I need to get the app working :)

Debug Mode tells me this: It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line
![Screenshot (9)](https://user-images.githubusercontent.com/94377348/141942505-c8691fab-f910-4133-8a14-cedd86a90243.png)

**Comment by FULLBL00M** [comment]
I am having the same issue currently myself. I am trying to troubleshoot possible config issues right now. If I find anything I will share it here, if you figure it out don't forget to comment here if you figure it out please lol :)

edit : sorry :/

**Comment by snipe** [comment]
Hi there - this issue is closed and doesn't seem necessarily) directly related to your issue. Please create a new issue and fill in all of the questions in the new issue form. (When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.)
