### ISSUE TITLE
Enhancements to Parent/Child Locations

### ISSUE THREAD

**Issue by marrodox** [snipe/snipe-it#7155]
**Server (please complete the following information):**
 - Snipe-IT Version **4.7.4**
 - OS: **Debian 9**
 - Web Server: **Apache**
 - PHP Version **v7.3.6**

**Is your feature request related to a problem? Please describe.**
Though I am able to set a parent/child relationship for locations, it does not behave as expected. I would expect the following from such a relationship:
- Inheritance of Manager, Currency, Address from parent unless specifically overwritten
- Prevention of deleting parent locations that have children
- Reporting of child locations on the parent location's details page
- Reporting of child location's assets/accessories/consumables on the parent location page

**Describe the solution you'd like**
I would love the behaviors above to become the normal behavior for parent/child locations. Additionally, the following features are closely related and would prove extremely useful:
- The ability to reuse location images once uploaded (i.e. an icon for a box)
- A location tag/barcode, especially for audits/bulk checkouts/etc.
- Reporting on Accessories/Consumables assigned to locations as well as People/Assets
- Prevent location deletion when assets/accessories/consumables assigned
- Ability to audit assets assigned to children during parent location audit
- Ability to assign users to a location and have assets "located" there if the user checks them out

**Describe alternatives you've considered**
Currently I am working around these limitations with less-accurate location naming, but I cannot fully utilize Snipe-it without proper child location behavior as they are a cornerstone of our asset tracking.

**Additional context**
Thank you!

**Comment by jtc44** [comment]
I have noticed this is an impactful issue and I would love to see that suggested solution implemented in new versions of Snipe-IT.

**Comment by marrodox** [comment]
Yes! Still eagerly awaiting this to be added

**Comment by Knightrain0** [comment]
Yes, it would definitely help if the parent location could have the sum total of all it's children locations users and assets.

**Comment by marrodox** [comment]
I'm hoping this gets fixed in #7192 - fingers crossed. Would love to see this!

**Comment by marrodox** [comment]
Yes, this is still relevant. It would be great if Snipe-it correctly handled locations.

**Comment by ajraymond** [comment]
I am interested in seeing Consumables in the Location view, as well as the tabs for each type instead of all on the same page.

**Comment by harracuda** [comment]
I also would love to see this. The lack of accessories and consumables in the location screen is slightly strange
