### ISSUE TITLE
[Feature Request] Request Assets for a future date

### ISSUE THREAD

**Issue by Cabe** [snipe/snipe-it#7161]
Server (please complete the following information):

Snipe-IT Version v4.6.15 build 4011 (gd1e9fbfa2)
OS: Ubuntu 18.04.2
Web Server: Apache 2.4.29
PHP Version 7.2.17-0ubuntu0.18.04.1
Is your feature request related to a problem? Please describe.
Entirely a feature request.

Describe the solution you'd like
Add a calendar option to the request assets dialogue, similar to the checkout page, but flipping the logic and allowing for dates in the future. The item should still remain as deployable/checked in but if someone else checks this item out, it should alert the user to a future request.

Describe alternatives you've considered
Tried to use the regular checkout system, but it only allows for dates in the past.

Additional context
We perform demos of our software at trade shows and other companies, this would allow us to see future availability - possibly with some kind of google calendar integration - of our demo hardware.

**Comment by Cabe** [comment]
I'm still interested in this feature request.

**Comment by Cabe** [comment]
Yep, would still like this feature, please.

**Comment by viclou** [comment]
same as [5081](https://github.com/snipe/snipe-it/issues/5081)
