### ISSUE TITLE
Backup from command line Failed

### ISSUE THREAD

**Issue by JThunder99** [snipe/snipe-it#7162]
#### Please confirm you have done the following before posting your bug report:

- [* ] I have enabled debug mode 
- [* ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I can backup from the web interface but when trying to back up from command line I get the following error:

C:\inetpub\wwwroot\snipe-it>php artisan snipeit:backup
Starting backup...

In BackupDestination.php line 147:

  Parse error: syntax error, unexpected '?'

**Expected behavior**
It will backup

**Server (please complete the following information):**
 - Snipe-IT Version 4.7.3
 - OS: [e.g. Ubuntu, CentOS] Windows Server 2016 Datacenter
 - Web Server: [e.g. Apache, IIS] IIS
 - PHP Version 7.2.14

**Comment by snipe** [comment]
via command line, run `php -v` to confirm your command-line PHP version

**Comment by JThunder99** [comment]
C:\inetpub\wwwroot\snipe-it>php -v
PHP 7.0.31 (cli) (built: Jul 18 2018 18:25:11) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

So that's the reason?

**Comment by snipe** [comment]
Yeah, I'd try upgrading the PHP cli version.

**Comment by JThunder99** [comment]
C:\inetpub\wwwroot\snipe-it>php artisan snipeit:backup
Starting backup...
Dumping database snipeit...
Determining files to backup...
Zipping 133 files...
Created zip containing 133 files. Size is 4.03 MB
Copying zip to disk named local...
Successfully copied zip to disk named local.
Backup completed!

That worked! Thank you.
I tried updating yesterday to the newest version but a lot of things messed up and end up having to restore from backup because we needed it back up and running could that be the reason why? 
I update quite regularly using php ugrade.php

**Comment by snipe** [comment]
> but a lot of things messed up and end up having to restore from backup 

Without knowing what messed up, I can't answer that for you

**Comment by JThunder99** [comment]
(1/1) UnexpectedValueException The stream or file "C:\inetpub\wwwroot\snipe-it\storage/logs/laravel.log" could not be opened: failed to open stream: Resource temporarily unavailable
(1/3) PDOException SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.permission_groups' doesn't exist

This is some of them that I was able to pull from my google history.

**Comment by JThunder99** [comment]
QueryException SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.permission_groups' doesn't exist (SQL: select `permission_groups`.*, `users_groups`.`user_id` as `pivot_user_id`, `users_groups`.`group_id` as `pivot_group_id` from `permission_groups` inner join `users_groups` on `permission_groups`.`id` = `users_groups`.`group_id` where `users_groups`.`user_id` = 1204)

**Comment by snipe** [comment]
That was pushed through yesterday, and that table would have been renamed via migration

**Comment by snipe** [comment]
> The stream or file "C:\inetpub\wwwroot\snipe-it\storage/logs/laravel.log" could not be opened: failed to open stream

That's usually a permissions problem
