### ISSUE TITLE
D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory.

### ISSUE THREAD

**Issue by hendry007** [snipe/snipe-it#7168]
D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory.

what i will do?

**Comment by tankerkiller125** [comment]
You need to point Nginx or Apache to the `/your/path/to/snip-it/public` directory instead of `/your/path/to/snipe-it`

**Comment by hendry007** [comment]
I already done this.but it showing the same error

**Comment by tankerkiller125** [comment]
Restart Nginx or Apache? This is the only thing I can think of that would cause this error. The file that displays this error is only located at the root directory. The public directory would show an actual error if it wasn't working properly (from experience anyways)

**Comment by gablex** [comment]
Is this issue really sorted? I have tried what is recommended above without success

**Comment by tankerkiller125** [comment]
This is a configuration error by end users, not an issue with flarum itself. So long as https://flarum.org/docs/install.html is followed carefully this issue should not happen. If you need further support with this I recommend asking on our discord support channel https://discord.gg/H8Z2GJZ for faster more realtime support.

<blockquote><div><strong><a href="https://flarum.org/docs/install.html">Installation | Flarum Documentation</a></strong></div></blockquote>
<blockquote><img src="https://cdn.discordapp.com/splashes/360670804914208769/d7d4ee5adfbde5f5344ea8eaf2d468bb.jpg?size=512" width="48" align="right"><div><img src="/assets/07dca80a102d4149e9736d4b162cff6f.ico" height="14"> Discord</div><div><strong><a href="https://discordapp.com/invite/H8Z2GJZ">Join the Flarum Discord Server!</a></strong></div><div>Check out the Flarum community on Discord - hang out with 3,792 other members and enjoy free voice and text chat.</div></blockquote>

**Comment by mazenitv** [comment]
Hi, I'm trying to get snipe-it to work on macos using xamp.
I should have setup everything properly my vhosts files my hosts file, mod_rewrite is enabled but i'm still getting the same message.
---http-vhosts.conf

<VirtualHost *:8888>
    ServerName localhost
    DocumentRoot "/opt/lamp/htdocs"
    <Directory "/opt/lamp/htdocs">
	ServerSignature Off
        Options Indexes FollowSymLinks IncludesNoExec
        AllowOverride All
        Require all granted
    </Directory>
    ErrorLog "logs/localhost-error_log"
</VirtualHost>

<VirtualHost *:8888>
    ServerName local.it
    DocumentRoot "/opt/lamp/htdocs/it/public/"
    <Directory "/opt/lamp/htdocs/it/public/">
        Options Indexes FollowSymLinks Includes execCGI
        AllowOverride None
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:8888>
    ServerName localhost/it
    DocumentRoot "/opt/lamp/htdocs/it/public/"
    <Directory "/opt/lamp/htdocs/it/public/">
	ServerSignature Off
        Options Indexes FollowSymLinks IncludesNoExec
        AllowOverride All
        Require all granted
    </Directory>
    ErrorLog "logs/it.dev-error_log"
</VirtualHost>

---hosts file
127.0.0.1       localhost
255.255.255.255 broadcasthost
::1             localhost
127.0.0.1       localhost/it
127.0.0.1       local.it

visiting http://localhost:8888/it/ gives me the message: D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory.

and visiting http://local.it/ takes me to the xamp dashboard.

where am i going wrong?

**Comment by stylish187** [comment]
I have not found a clear solution to this issue, can this please be re-opened.

**Comment by snipe** [comment]
No - it’s not an issue with Snipe-IT. It’s a server config. Make the public directory your document root in the web server. That’s the solution. The error is telling you how to fix it.

**Comment by jshrek** [comment]
I found the following solution that worked for me... modifying the .htaccess file instead:

Here is the .htaccess file with the modified rewrite lines near the end. Note that I figured this out from FreeScout which uses laravel and the public directory as well.

```
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    # Make sure .env files not not browseable if in a sub-directory.
    <FilesMatch "\.env$">
       # Apache 2.2
       <IfModule !authz_core_module>
          Deny from all
       </IfModule>
       
       # Apache 2.4+
       <IfModule authz_core_module>
          Require all denied
       </IfModule>
    </FilesMatch>
    
    # MOD starts here (taken from FreeScout htaccess file)
    # add these two lines:
       RewriteEngine on
       RewriteRule (.*) public/$1 [L]
    # MOD ends here

</IfModule>
```
