### ISSUE TITLE
Unable to save LDAP settings page

### ISSUE THREAD

**Issue by phsmichael** [snipe/snipe-it#7169]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Unable to save LDAP settings page "/admin/ldap"

**To Reproduce**
1. Browse to /admin/ldap
2. Do not make any changes to the page
3. Click save 

**Expected behavior**
Expected settings to be saved or meaningful error displayed

**Server (please complete the following information):**
 - Snipe-IT Version; v4.7.4  build 4107 (g49a255c8f)
 - OS: Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-51-generic x86_64)
 - Web Server: Apache/2.4.29 
 - PHP Version: 7.2.19-0ubuntu0.18.04.1
 - Composer version 1.8.6 2019-06-11 15:03:05
 - Laravel version:  5.5.45

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: FireFox Version: 67.0.1 (64-bit)

**Error Messages**
[snipe LDAP error.txt](https://github.com/snipe/snipe-it/files/3295017/snipe.LDAP.error.txt)

Can not reproduce on Demo as LDAP page is restricted

**Additional context**
- Is this a fresh install or an upgrade? Yes.
- What method you used to install Snipe-IT? install.sh
- Indicate whether or not you've manually edited any data directly in the database? No database fields have been modified

**Comment by Jonkke83** [comment]
problem is on file app/Http/Controllers/SettingsController.php row 868

Latest commit was
   -     if (Input::has('ldap_pword')) {
  +     if (Input::fille('ldap_pword')) {

it should have been 
  -      if (Input::has('ldap_pword')) {
  +     if (Input::fille**d**('ldap_pword')) {

changing that fixed it for me

**Comment by Alexithymia2014** [comment]
Thanks, this fixed it for me!

**Comment by phsmichael** [comment]
@Jonkke83 Thanks, that was the issue all happy now.

**Comment by HinchK** [comment]
Good eye @Jonkke83!  Thank you for pointing that out!

**Comment by allexxy** [comment]
confirmed
