### ISSUE TITLE
can't edit asset

### ISSUE THREAD

**Issue by roamergu** [snipe/snipe-it#7173]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
i created a assets Models named pc，and add some Fieldset,but when i upgrade to 3.7.4,i can't edit assest models pc,i can't set a asset to pc,and can't edit a pc assets.
**To Reproduce**
1. Go to 'Assts'
2. Click on 'All Ready to Deploy Assets'
3.Click a asses models pc,edit it,and save
4. but my fix no apply.

**Server (please complete the following information):**
 - Snipe-IT 3.7.4
 - OS: [ CentOS]
 - Web Server: [ Apache,]
 - PHP Version PHP 7.1.27

**Error Messages**
no any messages

**Additional context**
- Is this a fresh install or an upgrade? 
upgrade
- What OS and web server you're running Snipe-IT on
CentOS 7,i disabled selinux
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by soma115** [comment]
I have this issue also. History shows that field was changed but field has old value.
I've simple upgraded with 'php upgradphp artisan migrate
'php artisan migrate' said: 'Nothing to migrate'.
Handy commands from Common Issues didn't help.
Version 4.7.7, build 4160.
Please reopen this issue.
