### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/mywebsite.net/html/app/Exceptions/Handler.php:40

### ISSUE THREAD

**Issue by admiralzeech** [snipe/snipe-it#7174]
Hi, trying to install SnipeIT, but ran into an error during the compose step.

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
At the end of the composer step of the installation:
composer install --no-dev --prefer-source
(and when I run composer dump-autoload)

I get this error message:

admin@VM-SnipeIT:/var/www/mywebsite.net/html$ composer dump-autoload
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/mywebsite.net/html/app/Exceptions/Handler.php:40
Stack trace:
#0 /var/www/mywebsite.net/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(81): App\Exceptions\Handler->report(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#2 {main}
  thrown in /var/www/mywebsite.net/html/app/Exceptions/Handler.php on line 40
PHP Fatal error:  Uncaught Error: Class 'Log' not found in /var/www/mywebsite.net/html/app/Exceptions/Handler.php:40
Stack trace:
#0 /var/www/mywebsite.net/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(81): App\Exceptions\Handler->report(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#1 /var/www/mywebsite.net/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(123): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalErrorException))
#2 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()
#3 {main}
  thrown in /var/www/mywebsite.net/html/app/Exceptions/Handler.php on line 40
Script @php artisan package:discover handling the post-autoload-dump event returned with error code 255

I was following the instructions at:
https://www.digitalocean.com/community/tutorials/how-to-install-snipe-it-on-ubuntu-16-04
But also double checking with your official install instructions.

I tried the steps on your common issues page, but they did not solve the problem.

**To Reproduce**
1. Set up LEMP stack according to: https://www.digitalocean.com/community/tutorials/how-to-install-linux-nginx-mysql-php-lemp-stack-ubuntu-18-04
2. Follow all the linked guides to get everything working - I was able to browse to my website and see the PHP example page and the example index.html page.
3. Install Snipe IT following https://www.digitalocean.com/community/tutorials/how-to-install-snipe-it-on-ubuntu-16-04  (but with some changes due to package name differences)
4. When I get to the "composer install --no-dev --prefer-source" step, I receive the error.

**Expected behavior**
No error during composer, so I can begin configuring my .env file.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version : git clone https://github.com/snipe/snipe-it as of 2019-06-18
 - OS: Kubuntu 18.04.2 LTS
 - Web Server: nginx
 - PHP Version: PHP 7.2.19-0ubuntu0.18.04.1 (cli)

**Error Messages**
- Include any additional information you can find in `storage/logs` and your webserver's logs.

No files in storage/logs

**Additional context**
- Is this a fresh install or an upgrade? 

Fresh

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)

manual installation from git clone.

- Include what you've done so far in the installation, and if you got any error messages along the way.

As above.  I filled out all the required fields in the .env file to see if it would help.  I also reverted to the default .env to see if it would help.

- Indicate whether or not you've manually edited any data directly in the database

No

**Comment by admiralzeech** [comment]
Never mind, we switched to GLPI.

**Comment by CoolEarthMarkKendall** [comment]
As a note for users having this same problem:

I ran into the same problem and found that it was being caused by running composer as a user that was not added the web servers group, in my case www-data. As the install instructions only briefly mention the command `useradd -g apache snipeit` in the configuration section and I was working as a different user and with the web server running as 'www-data' the 0755 permissions were inadequate to write to the log directories. In my case I used `usermod -aG www-data myuser`.

You could also set the permissions on the relevant directories to 0777 which would also work but less preferable.

**Comment by moerkey** [comment]
Is it possible to reopen? The bug still exists with cloning the repo and with version 4.9.5. Version 4.9.4 runs fine on current Ubuntu 18.04 with PHP 7.2.

**Comment by moerkey** [comment]
I had this issue with .env file and not putting a value with spaces in colons. My bad.
