### ISSUE TITLE
Label Printer

### ISSUE THREAD

**Issue by TechLC1702** [snipe/snipe-it#7177]
**Server (please complete the following information):**
 - Snipe-IT Version: Not Sure
 - OS: CentOs
 - Web Server: Apache
 - PHP Version: Not Sure 

**Is your feature request related to a problem? Please describe.**
I want to see about getting a label maker that is all-in-one that can scan and print the labels. I wanted to see if the below one would be compatible with your system.

**Describe the solution you'd like**
Want to know if a the below label printer will work with SnipeIT.
Name:  Monarch Pathfinder 6057 Label Printer
Type: Monochrome Direct Thermal

**Describe alternatives you've considered**
Just that one unless you recommend something different

**Additional context**
None

**Comment by gilesytheking** [comment]
I'm using a a Dymo Label writer 450 with Durable Labels. This works perfect when printing from snipe IT, however I did have to play around with the label settings to get the best fit.
