### ISSUE TITLE
Asset Pie Chart and Logo Missing

### ISSUE THREAD

**Issue by knorquist** [snipe/snipe-it#7182]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Asset pie chart does not display on dashboard. Also, logo is missing when logged in (but appears on the sign-in screen).

**To Reproduce**
1. Navigate to Snipe-IT URL. Logo is present.
2. Login as admin/super admin.
3. Area for asset pie chart is empty. No logo displayed.
4. Login as non-admin (without access to dashboard).
5. No logo displayed.

**Expected behavior**
Pie chart displays with asset statuses. Logo displays beside branding.

**Screenshots**
![image](https://user-images.githubusercontent.com/3306524/59779011-59123700-926c-11e9-8b74-252c23687d41.png)
![image](https://user-images.githubusercontent.com/3306524/59777465-90331900-9269-11e9-9654-f2905bebe006.png)
![image](https://user-images.githubusercontent.com/3306524/59778849-17818c00-926c-11e9-8798-00f7cb8e858d.png)

**Server (please complete the following information):**
 - Snipe-IT Version: v.4.7.4 - build 4107 (master)
 - OS: Ubuntu 18.04.2
 - Web Server: Apache 2.4.29
 - PHP Version: 7.2.19

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise 1809
 - Browser: Chrome
 - Version: 74.0.3729.169

- Browser: Firefox
- Version: 67.0.3

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: 9
 - Browser: Chrome
 - Version: 75.0.3770.89

**Error Messages**
- None that I could see with debugging on that seemed related.

**Additional context**
- Fresh install.
- Installed with install.sh, did a git status and returned up to date.
- Added a logo, then checked "Remove" and uploaded a new one. Uploading logos appears to work because it changes on the login screen, and I can see the logo.png file update on the server.
- Haven't manually edited the database. Have done a few large (several thousand items) batch imports via command line and smaller ones using the web interface.

I have a vague bottom-of-the-stomach feeling the two problems (pie chart and missing logo) are related, otherwise I would have split into two issues.

**Comment by ajsy** [comment]
try to clear browser cookies and cache

**Comment by knorquist** [comment]
No change clearing cookies and cache, and this is happening on new devices accessing the site for the first time.

**Comment by pfmarques-git** [comment]
Have the same problem here with the assets piechart missing, but the logo works fine.

Were you able to fix it?

**Comment by knorquist** [comment]
No, not yet. We have some server maintenance planned soon and I'm going to see if I can dig around and get things working again. I'll update this issue if I fix it.

**Comment by knorquist** [comment]
Apparently, all I needed to do was wait for the pie chart. If I scroll down, mouse over the pie chart area, and then wait about ~30-60 seconds, the pie chart loads. We have about 17,000 assets.
