### ISSUE TITLE
API Documentation Request: Updating company_ID

### ISSUE THREAD

**Issue by andrefecto** [snipe/snipe-it#7186]
**Server (please complete the following information):**
 - Snipe-IT Version v4.7.0
 - OS: Any
 - Web Server: Any
 - PHP Version 7.2.7

**Is your feature request related to a problem? Please describe.**
I am creating a powershell script to sync Active Directory Groups with Snipe-IT groups so that we can manage Snipe-IT access using Active Directory. I noticed while doing PATCH company_ID on a user (could be null to remove them from a company or another company_ID to change them to another company) it removes them from all groups they belong to.

**Describe the solution you'd like**
This should be documented somewhere because I only found this behavior when I tested what would happen using PostMan. I know people should always be doing tests before running mass scripts but it was still an unexpected behavior.

**Comment by snipe** [comment]
I don't think its related to the company_id at all. I think it's an artifact of a change from 4.6.x to 4.7.x for `has()` and `filled()`. Are you passing a groups value at all?

**Comment by andrefecto** [comment]
@ColinMcNeil may be a better person to ask about this now. But if I remember correctly it's if you pass NULL into company_ID this removes them from any groups they belong to. I was not passing group_ID in the request, just company_ID=NULL.

**Comment by snipe** [comment]
@andrefecto So I think what's happening here is that it will blank those fields out if you don't re-supply the group IDs - which is obviously not the expected behavior. I think I see what happened here.

If you change the following: 
https://github.com/snipe/snipe-it/blob/f82ffe378ca436fcc46b58b094aaca93c4c11cba/app/Http/Controllers/Api/UsersController.php#L263-L267

to:

```php
// Check if the request has groups passed
if ($request->filled('groups')) {
    $user->groups()->sync($request->input('groups'));

// The groups value has been passed but it is null, so we should blank it out
} elseif (($request->has('groups')) && (!$request->filled('groups'))) {
    $user->groups()->sync(array());
} 
```

can you tell me if that resolves your issue?

**Comment by andrefecto** [comment]
I've emailed @ColinMcNeil to see if he can try it out. I no longer work for that group so don't have access to the system.

**Comment by snipe** [comment]
@andrefecto Sounds great, thanks!
