### ISSUE TITLE
Labels have extra space

### ISSUE THREAD

**Issue by dougbevan** [snipe/snipe-it#7190]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I setup a Zebra ZD410 to print asset labels.  Printing a test label works via printer settings and via text editor (i.e. Word).  When I print labels from the browser, I get extra space forcing a single label to split into two labels.  

Label settings in Snipe-IT were gathered from other posts using Zebra printers successfully.  They are: W 2.25 H 1.25, Page W 2.25, H 1.25, Label spacing 0.0, 0.0, Margins all 0.0.  

Settings in browsers are 2.25 x 1.25 with 0 margins.  Different browsers do have slightly different outcomes, but the results are similar.  Have tried Safari, Chrome, Opera, Firefox, Internet Explorer.

**To Reproduce**
Generate labels 
Print Labels

**Expected behavior**
Label prints with correct alignment. 

**Screenshots**
Picture of test from Word, CUPS, and finally attempt at a simple Snipe-It tag

**Server (please complete the following information):**
 - 4.6.16
 - OS: CentOS 7
 - Web Server: Apache
 - PHP Version 7

**Desktop (please complete the following information):**
 - OS: MacOS Mojave (have also tried from Win 10)
 - Browser: Have tried Safari, Chrome, Opera, Firefox, Internet Explorer.
 - Version: latest

**Error Messages**
No explicit errors as labels do print, just incorrectly

**Additional context**
Thanks for any help or tips.

![IMG_1194](https://user-images.githubusercontent.com/37080865/59929034-fce71880-940d-11e9-8a0e-66a0b0947c86.jpeg)

**Comment by paulo1624** [comment]
You may adjust the margins on the browser printer settings once you're printing the barcode.
![image](https://user-images.githubusercontent.com/32555803/59972554-b0ddd480-95c3-11e9-80b5-015621ac889b.png)

**Comment by dougbevan** [comment]
That was my first thought, and the image you see is the result of setting all 4 margins to "0".  I tried this in multiple browsers as well, and on multiple platforms (win/mac).  Although I get slightly different results, the results are similar with too much space on the top and left of the label.

**Comment by dougbevan** [comment]
I was able to get this to work, and margins were the key, although adjusting them was not so obvious.  I got this to work in Firefox. 

There is a parameter beyond the gui that sets a margin cushion.  To get to this, you need to go to "about:config" and edit the following parameters to 0:

print.print_margin_left
print.print_margin_right
print.print_margin_bottom
print.print_margin_top
