### ISSUE TITLE
Sub categories

### ISSUE THREAD

**Issue by jab9891** [snipe/snipe-it#7193]
**Server (please complete the following information):**
 - Snipe-IT Version 4.6.7
 - OS: Windows
 - Web Server: IIS
 - PHP Version 7.2.10

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
would it be possible to add sub categories to Asset Categories

**Describe alternatives you've considered**
Or use Parent categories to select level above

**Additional context**

**Comment by connected-mdeluco** [comment]
This or multiple categories would be a nice addition - that is, the "category" property of a hardware object should be a list of objects rather than a single object.
```
{
  "id": 523,
  "name": "iPhone 8"
  "categories": [
    { "id": 25, "name": "test device" },
    { "id": 32, "name": "iPhone" },
    { "id": 8, "name": "mobile device" }
  ],
  ...
}
```
