### ISSUE TITLE
Login failed with OpenLDAP

### ISSUE THREAD

**Issue by z-zhenbin** [snipe/snipe-it#7195]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I set up the LDAP with snipe it. Test LDAP is OK. But Test LDAP login always show the "ldap_search(): Search: No such object".

**To Reproduce**
1. Go to 'Admin'
2. Click on 'LDAP'
3. Scroll down to 'Test LDAP Login'
4. Click on 'Test LDAP Login'
5. See error

**Expected behavior**
Can use LDAP username and password login with snipe it.

**Screenshots**
![スクリーンショット 2019-06-25 16 35 08](https://user-images.githubusercontent.com/49152175/60078888-ce4ba380-9767-11e9-8500-28fdf3000b0e.png)
![スクリーンショット 2019-06-25 16 35 18](https://user-images.githubusercontent.com/49152175/60078902-d60b4800-9767-11e9-9fff-b7fcef15d0ee.png)
![スクリーンショット 2019-06-25 16 35 38](https://user-images.githubusercontent.com/49152175/60078909-da376580-9767-11e9-800f-c2aba27f19dd.png)
![スクリーンショット 2019-06-25 16 36 41](https://user-images.githubusercontent.com/49152175/60078963-f509da00-9767-11e9-8f05-9ac42bed64dd.png)

**Server (please complete the following information):**
 - Snipe-IT Version 4.7.4
 - OS: Docker

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version:  75.0.3770.100

**Error Messages**
[16:44:58] LOG.debug: Preparing to test LDAP login
[16:44:58] LOG.debug: Attempting to bind to LDAP for LDAP test
[16:44:58] LOG.debug: Attempting to login using distinguished name:cn=zhang-zb,cn=users,dc=xxx,dc=org
[16:44:58] LOG.debug: LDAP login failed

**Additional context**
I lookup our openldap server log. I found when the snipe it login to the ldap, it will bind twice. The first time use the LDAP Bind Username what I set up in snipe it. The second time, it will bind the server use my test username. I think the twice bind is very strange, because if you use the username to bind the server, you just can get the information for 'cn=zhang-zb,cn=users,dc=xxx,dc=org', you can not get the information for base DN 'cn=users,dc=xxx,dc=org'

**Comment by a3li** [comment]
I experience the same issue with LDAP ACLs that restrict users from accessing anything but their own entry in the directory (which setups like the most popular [OpenLDAP docker container](https://github.com/osixia/docker-openldap) seem to do by default).

What is fixing this for me is no longer searching the directory, but directly loading the user entry via its DN (`app/Models/Ldap.php`, `master` as of today):
``` Diff
-  if (!$results = ldap_search($connection, $baseDn, $filterQuery)) {
+  if (!$results = ldap_read($connection, $userDn, $settings->ldap_filter)) {
```

The LDAP setup seems to be redone on the `develop` branch, but I'm seeing similar `search` calls that I would imagine run into the same issue.

**Comment by a3li** [comment]
This is still relevant, dear bot. I was hoping your owner would comment on my approach to fixing this which I guess does not 100% concur with the way the LDAP setup in Snipe-IT is supposed to work.

**Comment by a3li** [comment]
see above

**Comment by splin13** [comment]
I have the same problem with openldap

**Comment by DunklerPhoenix** [comment]
Heho
Sry to get this old thing out of the archive, but I have the exact same problem.
I also use this container https://github.com/osixia/docker-openldap and get no such object.

![G4z2DHuCrI](https://user-images.githubusercontent.com/1261305/234027943-e731a577-4c29-4c8f-8ba6-f7ec888f4471.png)
