### ISSUE TITLE
Admin shouldn't be able to delete a super admin

### ISSUE THREAD

**Issue by cshulik** [snipe/snipe-it#7196]
#### Please confirm you have done the following before posting your bug report:

- [y ] I have enabled debug mode 
- [y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I'm an admin for my company's asset tracking database through SnipeIT and I was able to accidentally delete a super admin from our list of users. Fortunately we were able to restore the super admin.

**To Reproduce**
1. As an admin, go to users
2. Click on a super admin
3. Delete the super admin
4. Super admin is deleted and you panic

**Expected behavior**
An error to pop up that states that non super admins cannot delete superadmins.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.15- build 4011
 - OS: [e.g. Ubuntu, CentOS] Not sure
 - Web Server: [e.g. Apache, IIS] Not sure
 - PHP Version Not sure

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows Home x64
 - Browser [e.g. chrome, safari] Chrome 
 - Version [e.g. 22] 75.0.3770.100

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by tomholovis** [comment]
bump to stop it going stale
