### ISSUE TITLE
Sad Panda 404 after clicking reset password link sent via email

### ISSUE THREAD

**Issue by emerzws** [snipe/snipe-it#7197]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When clicking on the reset password link sent via email, it returns with a 404 sad panda page.

**To Reproduce**
1. Go to '...'  I forgot my password
2. Click on '....'  Fill out email address and click "Email password Reset"
3. Scroll down to '....' Open email and click on "Reset Password"
4. See error " 404 Page not found.
Sad panda. We could not find the page you were looking for. You should maybe return to the dashboard."

**Expected behavior**
It should be directed to a password reset page

**Screenshots**
It's just a 404 page with a Panda picture. 

**Server (please complete the following information):**
 - Snipe-IT Version  v4.6.15 build 4011 (gd1e9fbfa2)
 - OS: [e.g. Ubuntu, CentOS] Ubuntu 16.0.4
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.0.33-0ubuntu0.16.04.5
--

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari]  Chrome
 - Version [e.g. 22]  Version 75.0.3770.90 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] n/a
 - OS: [e.g. iOS8.1] n/a
 - Browser [e.g. stock browser, safari] n/a
 - Version [e.g. 22] n/a

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error

 404 Page not found.

Sad panda. We could not find the page you were looking for.You should maybe return to the dashboard. 

- If a stacktrace is provided in the error, include that too.   Laravel.log contains 4000 lines
- Any errors that appear in your browser's error console. Not sure, maybe this errors::404 (resources/views/errors/404.blade.php)
1
blade
layouts.basic (resources/views/layouts/basic.blade.php)
7
blade

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.  It is not reproducible due to the nature of the issue.  Email is not registered on the demo. 

- Include any additional information you can find in `storage/logs` and your webserver's logs.  Laravel.log contains 4000 lines

**Additional context**
- Is this a fresh install or an upgrade?  Fresh install
- What OS and web server you're running Snipe-IT on  Ubuntu and on Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)  install.sh I believe
- Include what you've done so far in the installation, and if you got any error messages along the way.  I do not recall the exact messages I got while installing this, but for what it's worth everything else seems to work but the reset email link function.  
- Indicate whether or not you've manually edited any data directly in the database    I have not edited anything in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
Please answer the rest of the questions in the issue template.

**Comment by emerzws** [comment]
> Please answer the rest of the questions in the issue template.

Ok, I've updated what I can answer

**Comment by CSAS-Nicholas-Roberts** [comment]
I am having a similar problem to this and I noticed that the link that the password reset email is giving me has my base url twice.

Example:
http://mysite.com/mysite.com/password/reset/1d05d62740fc4126871089f3bdd1d6efc8df254c9a7dcfeb0cfe1e350a3d3e77

If I remove one of the instances of the site name and go to that page instead, the reset works.

Example working url derived from the original url:
http://mysite.com/password/reset/1d05d62740fc4126871089f3bdd1d6efc8df254c9a7dcfeb0cfe1e350a3d3e77

I tried to repeat the problem in the demo by logging in as admin, creating and account for myself, assigning my email to it, logging in once, logging out, and then doing a password reset, but it looks like password resets don't send out an email in the demo.

**Comment by snipe** [comment]
What do you have as your APP_URL?

**Comment by CSAS-Nicholas-Roberts** [comment]
As an example, in my .env it's set to...

APP_URL=mysite.com

**Comment by snipe** [comment]
Per the [documentation](https://snipe-it.readme.io/docs/configuration#section-required-basic-app-settings), this should be a fully-qualified hostname, including `http://` or `https://`.

<img width="703" alt="Screen Shot 2019-07-15 at 3 35 32 PM" src="https://user-images.githubusercontent.com/197404/61253584-57764a80-a716-11e9-92f4-51b46f41eece.png">

**Comment by CSAS-Nicholas-Roberts** [comment]
Trying this now.

**Comment by snipe** [comment]
(You may need to clear your config cache as well, by running `php artisan config:clear`)

**Comment by CSAS-Nicholas-Roberts** [comment]
You're right on the mark! Thanks for your help in this one @snipe 😄 

Fix:
Ensure APP_URL contains http:// or https://
Run ``php artisan config:clear``
Resend a new password reset
