### ISSUE TITLE
Create Custom Dashboard in snipeIT and can calculations be done in Snipe IT

### ISSUE THREAD

**Issue by Mandeepasr** [snipe/snipe-it#7198]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)
I have been using Snipe-IT but have 2 things to resolve
1. Create Custom dashboard that should the Data in a particular way along with graphs
2. Is there a way to perform the calculation in Snipe IT if yes please provide an example.
----

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by marianampc** [comment]
It is relevant.

**Comment by yosiasz** [comment]
why dont you create your own dashboards outside of snipeit? leverage the snipeit rest api to get the data. then use something like grafana or some other visualization tool to display graphs

**Comment by PandiarajanSelvaraj** [comment]
It is relevant.

**Comment by DavidMunch** [comment]
It is relevant.
