### ISSUE TITLE
Multi select assets for label generation based on checked out user

### ISSUE THREAD

**Issue by mrmcox** [snipe/snipe-it#7199]
Hi All,

Is it possible to bulk generate assets labels by selecting those assets from the assigned users' group?

The reason I ask is that we have 400+ assets which are not assigned a team/group/dept etc but are checked out to their user.  I would like to bulk print labels based on user dept/group. 

Is this possible?

**Comment by mrmcox** [comment]
Any input on this would be great.

Thanks,

Matt.

**Comment by snipe** [comment]
Does doing a search on that user's name not return the results your expecting?
