### ISSUE TITLE
Location of checked-out assets isn't kept in sync with assigned-to assets

### ISSUE THREAD

**Issue by mmorais-idealsumario** [snipe/snipe-it#7203]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Scenario 1: When checking out an asset A to asset B, A's location is correctly updated to B's location. However, if after that one checks out asset B to another asset C, B assumes C's location, but A remains unchanged.

Scenario 2: A is checked out to B, B is checked out to C, and C is checked out to D. If one checks D in, with or without defining a new location, neither A, B or C see their locations updated to the new D.

**To Reproduce**
1. Go to 'Assets'
2. Deploy an asset to another asset
3. Verify that the former's location has been updated to correspond to the latter's
4. Deploy the latter asset to a third asset in a different location
5. Verify that the second asset's location has been correctly updated to the third, but the first asset's location has not.

**Expected behavior**
The expected behavior would be for all associated assets to keep their location in sync, recursively, with their assigned-to targets. In the end, the first asset should be in the same location as the second, which is the same as the third one.

**Server (please complete the following information):**
 - Snipe-IT Version 4, 5
 - OS: Ubuntu Bionic
 - Web Server: Apache, Nginx
 - PHP Version 7.1, 7.2

**Desktop (please complete the following information):**
 - OS: Ubuntu Bionic, OpenSUSE 15.1
 - Browser Firefox
 - Version 60.7.2

**Additional context**
- Is this a fresh install or an upgrade? - Fresh install.
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Both docker and manual, using also both master and develop branches.
- Include what you've done so far in the installation, and if you got any error messages along the way. - No error messages, everything running normally.
- Indicate whether or not you've manually edited any data directly in the database. - No.

**Comment by mmorais-idealsumario** [comment]
As a side note, I've begun implementing a fix which I'm already testing. There seems to be an artisan command called snipe-it:sync-asset-locations which uses method Asset::assetLoc() to recursively update all checked-out assets. Effectively it seems to fix the issue in the database when executed, but this is not a viable permanent solution.

As such, I'm picking up that method and am using it in AssestsTransformer, not to change the database, but to recursively fetch the correct location from the assigned-to assets, if any. I will post a pull request soon. Thank you!

(Please note that this is the first time I'm attempting to contribute to a github project, so bear with me :)

**Comment by mmorais-idealsumario** [comment]
Just to add to the previous comment, actually the method Asset::assetLoc(), when there is no more recursivity, only takes rtd_location_id into account and ignores location_id. The result is that the command snipe-it:sync-asset-locations might mess up some assets' locations.

This will also be fixed in my pull request.

**Comment by tothetopgg** [comment]
We are seeing the same behavior on version 4.7.6. We have a few assets(mainly flight cases) that have a lot of assets inside of them and go to different events. Currently we are only checking out these flight cases to a location and we would assume this would also update the location of the assets inside of the asset, which it does not.

**Comment by tothetopgg** [comment]
Still relevant.

**Comment by rpesta** [comment]
Still relevant.

**Comment by tommehgg** [comment]
Still relevant.

**Comment by tothetopgg** [comment]
This is still relevant.

**Comment by tommehgg** [comment]
Still relevant.

**Comment by Jaspotn0612** [comment]
still relevant.

**Comment by tommehgg** [comment]
still relevant.
