### ISSUE TITLE
several AD domains

### ISSUE THREAD

**Issue by TheAnahaym** [snipe/snipe-it#7205]
Snipe-IT version | v4.4.1 build 3636 (gece916e12)
Software License | AGPL3
PHP Version | 7.1.18-1+ubuntu16.04.1+deb.sury.org+1
Laravel Version | 5.4.35

Hi, would be it possible to add the second LDAP connector?
We have two AD domain, but now we can add only one AD domain into snipe-it.

Thank you in advance.

**Comment by ajsy** [comment]
Not stale
