### ISSUE TITLE
Question: Am I missing something? LDAP/AD Sync

### ISSUE THREAD

**Issue by lveitch** [snipe/snipe-it#7207]
This is more of a question than a bug...can someone tell me if I am missing something.  I have tried this every possible way using all the questions that had been posted previously in the bug reports and suggested modifications but I am unable to get this to sync. I understand there could be many variables in play here but more-so looking for someone to just look at my setup below and make sure that I have everything correct.  My setup is as follows:

OS = Windows Server 2016 (fully patched)
Snipe IT version: 4.7.5
DB = MariaDB 10.0.38
PHP = 7.3.6
Server = member of a domain, can ping DC and DNS as well as external DNS, firewalls are disabled, no proxies in play

![Annotation 2019-06-27 082929](https://user-images.githubusercontent.com/51424411/60279926-d534fc00-98b6-11e9-99a8-4eb53ec8565d.png)
![Annotation 2019-06-27 082959](https://user-images.githubusercontent.com/51424411/60279940-da924680-98b6-11e9-87a4-77691a2d6893.png)

**Comment by aliboduroglu** [comment]
i think you should use CN=Admins in the LDAP filter field
