### ISSUE TITLE
API won't work

### ISSUE THREAD

**Issue by Hr24612** [snipe/snipe-it#7208]
The API won't work for me. I generated a personal access token but I still get unauthorized. Please help!
![Capture](https://user-images.githubusercontent.com/31827194/60302520-ab50f900-98f9-11e9-93f3-e3fdbc12c389.PNG)

**Comment by snipe** [comment]
The endpoint should be on your own Snipe-IT installation, after generating an API token by going to `/account/api` on your installation.

**Comment by Hr24612** [comment]
I am doing that and it would still give me an error.
