### ISSUE TITLE
Incorrect version showing after upgrade to 1.2.6.1

### ISSUE THREAD

**Issue by drahamim** [snipe/snipe-it#721]
After downloading the 1.2.6.1 tar file and doing the commands 

php composer.phar install
php composer.phar dump-autoload
php artisan migrate

The version at the bottom of the page shows as 1.2.6-26.

**Comment by snipe** [comment]
Where did you download it from, the releases page, or from develop/master?

**Comment by drahamim** [comment]
Release page https://github.com/snipe/snipe-it/releases

**Comment by snipe** [comment]
That should be fixed in the next release. We switched how we annotate and display version numbers.
