### ISSUE TITLE
Feature Request: Expand Audit Functionality: Add Checklist

### ISSUE THREAD

**Issue by DJTim** [snipe/snipe-it#7210]
Our use-case is that an assigned (checked-out) asset can be audited by a third party or by the assigned user itself.
When the asset is audited by a third party, the auditor will approve or reject the asset and set the new due-date. 
When the asset is audited by the assigned user, a checklist needs to be filled in and the user can decide if the asset is approve or reject. This could be optimized that depending on the result of the checklist the asset is approved or rejected.
The product category decides the checklist. The category could also decide the approved new audit due-date and the reject new audit due-date.

•	Can a simple checklist functionality be added to audit?
•	Can buttons be added ex. In 1 month, In 6 months, In 1 year to set the due-date?
•	When an asset is assigned to a user, is an email sent to that user when the asset is due to be audited?
•	Can the assigned user see when an asset has to be audited?

**Comment by perezalvarezhi** [comment]
Hi @DJTim I have the same kind of need in my company. At the moment I use a combination of google forms / OSTicket / SnipeIT to do this but it would be aswesome to be able to have this.

**Comment by DJTim** [comment]
I will use office forms for the questionnaire for now. A better solution would be an integration into Snipe-It.
