### ISSUE TITLE
Issue upgrading SnipeIT version

### ISSUE THREAD

**Issue by redolphn** [snipe/snipe-it#7215]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I am running the "php upgrade.php" command and it appears to run properly and it says "Your branch is up to date with 'origin/master'" however when I open SnipeIT in an incognito tab/browser, it still shows the old version of SnipeIT (4.6.15).   If I then try to run "php upgrade.php" again, it goes through the script and during one one of the "phases" it outputs "Your branch is behind 'origin/master' by 109 commits, and can be fast-forwarded."

**To Reproduce**
Run the "php upgrade.php" command

**Expected behavior**
I expected to be able to log into SnipeIT after running the upgrade script and see the new version number

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.6.15 build 4011
 - OS: [e.g. Ubuntu, CentOS] Ubuntu 18.0.4.1
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.2.19

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 74

**Additional context**
- Is this a fresh install or an upgrade? - Upgrade
- What OS and web server you're running Snipe-IT on - Ubuntu 18.0.4.1 and Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - Git
- Include what you've done so far in the installation, and if you got any error messages along the way. - Trying to run the "php upgrade.php" script and it is not upgrading properly/successfully
- Indicate whether or not you've manually edited any data directly in the database - No

**Comment by davidmatthews85** [comment]
try using the command 'git pull' and see how you get on :)

**Comment by redolphn** [comment]
No luck with running 'git pull'

I also tried running 'git reset --hard' and then tried running 'php upgrade.php' again, but then it failed with a bunch of "permission denied errors" and these errors:

In Kernel.php line 59:
  Call to undefined method App\Console\Kernel::load()

@snipe  do you have any ideas for how I can get my SnipeIT installation successfully upgraded?

**Comment by snipe** [comment]
What about:

```
git checkout master
git pull origin
```

**Comment by redolphn** [comment]
@snipe  - When I run 'git checkout master' it shows a long list of files with an "M" next to them and then at the end it says:

Already on 'master'
Your branch is behind 'origin/master' by 109 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)

When I run 'git pull origin' it starts out with the following:

remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 28 (delta 23), reused 26 (delta 23), pack-reused 0
Unpacking objects: 100% (28/28), done.
From https://github.com/snipe/snipe-it
   e1b33f308..f82ffe378  master     -> origin/master
Updating 25884a893..f82ffe378
error: Your local changes to the following files would be overwritten by merge:

... followed by listed a whole bunch of files and then says "Aborting" at the end.

I then tried running 'php upgrade.php' again after those commands that you suggested and it still does not upgrade - just says the following on step 3:

Your branch is behind 'origin/master' by 113 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
Updating 25884a893..f82ffe378

**Comment by redolphn** [comment]
I fixed the issue... I had to change the ownership on the /var/www/snipeit folder to www-data and updated 'git stash'

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
