### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by markusr** [snipe/snipe-it#722]
I noticed some strings missing from the German translation. But the translation shows 99% so it seems to me that these strings are not yet included.

Main dashboard:
![2015-04-02 12_12_58-dashboard __ it asset management](https://cloud.githubusercontent.com/assets/1866703/6962198/8ab51fa4-d932-11e4-95b1-b7bda773e308.png)

Asset creation:
![2015-04-02 12_13_55-asset erstellen __ it asset management](https://cloud.githubusercontent.com/assets/1866703/6962202/8fff8d00-d932-11e4-8538-ddc4d1858082.png)

**Comment by markusr** [comment]
Adding a ```/admin/settings/manufacturers```

See:
![2015-04-02 12_29_08-asset hersteller __ it asset management](https://cloud.githubusercontent.com/assets/1866703/6963481/299960aa-d940-11e4-9c90-c1af219d3766.png)

**Comment by Gabisonfire** [comment]
Translations!

If you're not a coder but want to give back to the project and you're fluent in other languages, consider helping out with the translations. We use CrowdIn to manage translations, and it makes it super-simple for you to add translations to the project without messing with code. Check out the Snipe-IT CrowdIn translation project here.

We currently have English, Chinese, Finnish, Malay, Romanian and Spanish completed, and are looking for lots more!

https://crowdin.com/project/snipe-it/

**Comment by snipe** [comment]
Pending Assets in the sidebar is in `app/lang/general.php` as `pending`. If it's not showing in german for you, that means no one has translated it yet. You're welcome to do so using the link that @Gabisonfire provided.

In Asset Creation for Status, it's simply pulling the name of the status label, so you would just have to translate those in your Status Labels admin.

The Create New Location bit in Manufacturers is already fixed on develop (and has been for a bit), and will be in the next release.

We'll work on getting the other strings pulled out into language files. Some of them are generated by the plugins we're using (like Datatables), so it's not quite as straightforward.

**Comment by markusr** [comment]
> Pending Assets in the sidebar is in app/lang/general.php as pending.

It was marked as translated in German, but the translation was ```pending```. I corrected it. Additionally, I found some other strings that where marked as translated, but actual weren't.

> In Asset Creation for Status, it's simply pulling the name of the status label, so you would just have to translate those in your Status Labels admin.

I will do that. May be there is a 'clean' way of doing this automatically when the database is populated?  Something like:
```php artisan app:install_de``` 

> We'll work on getting the other strings pulled out into language files.

Thank you.
