### ISSUE TITLE
Assign a Department to a Location

### ISSUE THREAD

**Issue by KMinst** [snipe/snipe-it#7220]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.7.4 - build 4107 (master)
 - OS: [e.g. Ubuntu, CentOS] ? can obtain if necessary
 - Web Server: [e.g. Apache, IIS] ? can obtain if necessary
 - PHP Version ? can obtain if necessary

**Is your feature request related to a problem? Please describe.**
In custom reports, the department field is null for assets checked out to locations. Since there doesn't appear to be a way to assign a department when editing a location, I assume that Snipe-IT is behaving as designed and this is not a bug.

**Describe the solution you'd like**
I have assets checked out to either users or locations. Using custom reports, I am able to group assets by department for those assets checked out to users, but the department field is null for those assets which are checked out to locations. I'd like to have a consolidated report for all assets associated with a given department, including all assets, whether they are checked out to a user or to a location. Being able to specify a department when editing a location would seem to provide this functionality without impacting other uses for departments or locations.

**Describe alternatives you've considered**
I've (briefly) considered manually editing the exported custom report each time it is created to manually add the department field where it is missing. 
I'm open to other alternatives.

**Additional context**

**Comment by eldhom92** [comment]
Hey, 
I have got one case, while importing assets through CSV the department and manager details weren't added along with user information,
Any luck !! What can be done for this issue ?
Workaround is to add manually which really painful for many 🙂,

Help me on this issue,

Thanks
Eldhose
