### ISSUE TITLE
Unauthorized When Attempting To PUT / PATCH

### ISSUE THREAD

**Issue by derekritchison** [snipe/snipe-it#7222]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I cannot seem to troubleshoot this constant {"error":"Unauthorized."} response when attempting to 

**To Reproduce**
I believe the error is related to my CURLOPT_HTTPHEADER. I've tried writing this at least three different ways, each time I get the same "Unauthorized" error:

**METHOD 1** 

```
$ch = curl_init();

curl_setopt($ch, CURLOPT_URL, 'https://mysite.mydomain.net/api/v1/hardware/' . $itassets_id);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, "{\"requestable\":false,\"archived\":false,\"name\":\"$jamf_name\"}");
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PUT');
    
$headers = array();
$headers[] = 'Accept: application/json';
$headers[] = 'Authorization: Bearer ACCESS-TOKEN';
$headers[] = 'Content-Type: application/json';
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    
$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
echo "\n" . $result . "\n";
```

**METHOD 2**

```
$uri = 'https://mysite.mydomain.net/api/v1/hardware/' . $itassets_id;

$headers = array();
$headers[] = 'Authorization: Bearer ACCESS-TOKEN';
$headers[] = 'Accept: application/json';
$headers[] = 'Content-Type: application/json';

$ch = curl_init($uri);

curl_setopt_array($ch, array(
    CURLOPT_HTTPHEADER  => $headers,
    CURLOPT_RETURNTRANSFER  => true,
    CURLOPT_POSTFIELDS => 'array(\"name\":\"$jamf_name\")',
    CURLOPT_CUSTOMREQUEST => 'PUT',
    CURLOPT_VERBOSE => 1
));

$result = curl_exec($ch);
if (curl_errno($ch)) {
    echo 'Error:' . curl_error($ch);
}
curl_close($ch);
echo "\n" . $result . "\n";
```

**Expected behavior**
The expected behavior is that I can PUT/PATCH certain criteria that I am pulling from the machine's Jamf instance into our assets management system.

**Server (please complete the following information):**
 - Snipe-IT Version: 4.7
 - OS: Linux
 - Web Server: Apache
 - PHP Version: 

**Desktop (please complete the following information):**
 - OS: Windows 10 (running script in an Ubuntu shell)

**Comment by derekritchison** [comment]
And now I've tried a fifth or sixth way of writing this, and I am getting a new error:

_{"status":"error","messages":"Method not allowed","payload":null}_

Any suggestions at all would be much appreciated.

```
// set post fields
$payload = [
    'name' => $jamf_name,
];

// setup the request, you can also use CURLOPT_URL
$ch = curl_init($uri);

// returns the output as a string instead of raw data
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

// spec
curl_setopt($ch,CURLOPT_POST,1);

// set your auth headers
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'Accept: application/json',
    'Content-Type: application/json',
    'Authorization: Bearer '.$accessToken
    ));

// send the $data fields
curl_setopt($ch, CURLOPT_POSTFIELDS,$payload);

// get stringified data/output. See CURLOPT_RETURNTRANSFER
$output = curl_exec($ch);

// do something with the returned data, here we're just dumping it to the screen
print_r($output);

// get info about the request
$info = curl_getinfo($ch);

// close curl resource to free up system resources 
curl_close($ch);
}
```

**Comment by derekritchison** [comment]
Same results with PHP cURL class, rather than native PHP. Would seriously love any feedback. Certainly someone else has experienced this?

**Comment by snipe** [comment]
In the first ones (Unauthorized), I'm guessing you weren't actually passing the bearer token... 

In the last one, I'd need to know what the `$uri` endpoint is. Method not allowed means that whatever method you're using (`POST`, `GET`, `PUT`, etc) isn't allowed at the URL endpoint you're trying to talk to.
