### ISSUE TITLE
Deployed assest are still requestable by the users.

### ISSUE THREAD

**Issue by NaveenQLI** [snipe/snipe-it#7223]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 4.7.5
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 7.3.6

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
That's currently expected behavior. Just because an asset is currently deployed doesn't mean it will remain that way forever.

**Comment by NaveenQLI** [comment]
But we will be providing the end date for the users when the assets are
checked in. in that case the assets should have an options unavailable for
deployment. Think that would be the proper way of doing it.

**Comment by NaveenQLI** [comment]
Could you please check the above comments on this.

**Comment by dvasilevsky** [comment]
I actually added a few lines of code to get around this exact issue for my company's needs.

**BEFORE DOING THIS BACKUP THE FILES.**

Also, you may need to add:

`use App\models\AssetModel;`

To each file at the top with the other "use" helpers. I cannot remember if I added it myself.

In the files for checkout and checkin controller i added the following:

file: ~\snipeit\app\Http\Controllers\AssetCheckinController.php: placed on line 70 right after $asset->name = $request->get('name');

`		
$model = AssetModel::find(e($asset->model_id));
if($model->category_id == 2){
	$asset->requestable = '1'; 
}`

This says that if the model is a specific category, that when you press the checkin button to make the item requestable again.

Alternatively, the opposite would be this for checkout:
file: ~\snipeit\app\Http\Controllers\AssetCheckinController.php: placed on line 84 right after $expected_checkin = $request->get('expected_checkin');

`		$model = AssetModel::find(e($asset->model_id));
		if($model->category_id == 2){
			$asset->requestable = '1'; 
		}`

This will make items of category id 2 no longer requestable once the checkout button is pressed.

This has worked great for us so far and only does it for items under a specific category. To get the category ID I went into the SQL Database and just checked the id code there.
