### ISSUE TITLE
after run composer install found this issue

### ISSUE THREAD

**Issue by monkeydelufy** [snipe/snipe-it#7227]
Hi 

i try installing snipeit new version and found this after running composer install
PHP Parse error:  syntax error, unexpected '?' in /var/www/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 233

need help

**Comment by EarlRamirez** [comment]
@monkeydelufy, not much to go on, would you be able to complete the issue template so that we can have a better idea on how we can assist?

**Comment by monkeydelufy** [comment]
@EarlRamirez 

its working now we must run composer inside install-dirr

Thanks for reply
