### ISSUE TITLE
Custom Asset Report limited to 500 assets?

### ISSUE THREAD

**Issue by leejunfan1972** [snipe/snipe-it#7228]
When i try export a custom asset report, it will only list 500 items, i have about 1500, when it hite the 500 mark on the excel report it inserts some HTML?

Is this a fixed limit on Snipe-It?

#### Please confirm you have done the following before posting your bug report:

- [y ] I have enabled debug mode 
- [y ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
There isn't a limit on that report. If you're seeing HTML, I'd need to know what the HTML is. It's likely throwing an error that you're seeing streamed into the Excel document, but without that error (or your error logs, or literally any other info to go on), I'm not sure how we can help you.

**Comment by leejunfan1972** [comment]
this is the HTML, trying to obtain the error logs.

[html.txt](https://github.com/snipe/snipe-it/files/3396513/html.txt)
