### ISSUE TITLE
unable to generate app key due to supported cypher error

### ISSUE THREAD

**Issue by phatuous** [snipe/snipe-it#7230]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Attempting to run "php artisan key:generate" produces error "The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths."

**To Reproduce**
1. Follow the installation instructions (cloning the repository, not running install.sh)
2. perform all of the required modifications to .env - but leave APP_CIPHER=AES-256-CBC
3. run "php artisan key:generate"

**Expected behavior**
Key should be successfully generated

**Server (please complete the following information):**
 - Snipe-IT Version: 4.7.5
 - OS: [e.g. Ubuntu, CentOS]: Ubuntu
 - Web Server: [e.g. Apache, IIS]: Apache
 - PHP Version: 7.1.30

**Additional context**
fresh install, "manual installation" using recommended git clone (multiple installations on same server)
i also ran into issues with the vendor directory not being created, which I tried to work around using the "common issues" page (php composer.phar update)

**Comment by phatuous** [comment]
I was able to work around this by changing the "APP_KEY:ChangeMe" to an actual key that I stole from a different installation... afterwards I was then able to run "php artisan key:generate" to create a NEW APP_KEY in my .env file.

I'm not sure how this is supposed to work first time through, because the artisan key generate seems to be choking on the "ChangeMe". (I also tried just deleting it, but that gave me the same error as above)

**Comment by Skywalker-11** [comment]
This issue still exists with current Snipe-IT version on Debian with PHP 7.4.
It should probably be fixed or the documentation at [https://snipe-it.readme.io/docs/generate-your-app-key](https://snipe-it.readme.io/docs/generate-your-app-key) should be updated

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/generate-your-app-key">Generate Your App Key</a></strong></div><div>Once you've Downloaded Snipe-IT, set up your Configuration in your .env file, and Installed Dependencies, you'll need to set an app key.  The easiest way to do this is via the artisans command:This should automatically set the APP_KEY value in your .env file for you. After that, you're ready for the...</div></blockquote>
