### ISSUE TITLE
can't run 'php upgrade.php'

### ISSUE THREAD

**Issue by Liel4494** [snipe/snipe-it#7232]
#### Please confirm you have done the following before posting your bug report:

- [V] I have enabled debug mode 
- [V] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

when i try to run this command to upgrade my snipe-it i get this message:
"This script should not be run as root/admin. Exiting."

i try to run this command from non-root user but its not helping.

 - Snipe-IT Version: v4.6.15 build 4011 (gd1e9fbfa2) 
 - OS: CentOS 7
 - PHP Version: 7.1.28

**Comment by EarlRamirez** [comment]
@Liel4494 you need to run the script as the owner of the files, for example if the owner of the files in /var/www/html/snipeit is apache you need to run `sudo -u apache upgrade.php`

**Comment by worker-it** [comment]
What are the risk executing this script as root?

**Comment by snipe** [comment]
You should never execute anything in Snipe-IT as root. It will cause permission problems later down the line, as files and directories will be owned as root and then will not be writable by the web server, etc. (In fact, I think it doesn't even allow you to run it as root for this reason.)

**Comment by worker-it** [comment]
Thanks for the quick answer!!! I won't do it then!!! hehehe :)

I know, but commenting the condition in the php file is not a hard job...  But thanks for your help. :)
