### ISSUE TITLE
Expected Check-In email notification not firing 

### ISSUE THREAD

**Issue by djdamith** [snipe/snipe-it#7233]
#### Expected Behavior (or desired behavior if a feature request)

When a asset comes or over due the expected check-in date it should notify the admins & the owner of the asset via email.

-----

#### Actual Behavior

nothing happens even after the expected check-in date. However i can trigger the emails by using the **php artisan snipeit:expected-checkin** manually.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
YES
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
 
YES
-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh with migration
- Version of Snipe-IT you're running
v4.7.3 build 4098 (g087cdd859)
- Version of PHP you're running

7.2.19
- Version of MySQL/MariaDB you're running
10.0.38-MariaDB
- What OS and web server you're running Snipe-IT on
IIS 8.0 on windows server 2012 r2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
*.Zip file package
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
Asset expected check-in
- If a stacktrace is provided in the error, include that too.
N/A
- Any errors that appear in your browser's error console.
N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
N/A
- Include any additional information you can find in `storage/logs` and your webserver's logs.
N/A
- Include what you've done so far in the installation, and if you got any error messages along the way.
No issues on install
- Indicate whether or not you've manually edited any data directly in the database
Noting

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Do you actually have a cron (or scheduled task) to fire those alerts? They don't fire automagically, you have to set them up to fire: https://snipe-it.readme.io/docs/configuring-alerts-backups
