### ISSUE TITLE
Backup Failed because Excepted Response code

### ISSUE THREAD

**Issue by baer-ing** [snipe/snipe-it#7236]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When I run the Backup command in the GUI on Frontend I end up whit a Sorry Page and no backup. When I do it over the command line I end up with a lot of Error Message. But at the end it tells the following: "Expected response code 354 but got code "503", with message "503 5.5.2 Need rcpt command" As I have googled this Codes it says either the authentication is wrong or the command is not allow or not in the right order. However I can send Mail with Snipe and it works perfectly without issues so I think I can check the autentication as done.

**To Reproduce**
1. Go to 'Settings>Backup'
2. Click on 'Create Backup'
4. See error "Whoops, looks like something went wrong."

**Expected behavior**
Expected a Backup in the list.

**Screenshots**
No screens

**Server (please complete the following information):**
 - Snipe-IT Version : 4.7.5
 - OS: [e.g. Ubuntu, CentOS]: Ubuntu 1804 LTS
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.2

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: WIndows 10 1809
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]: Latest

**Error Messages**

Copying zip failed because: Expected response code 354 but got code "503", with message "503 5.5.2 Need rcpt command
".
Backup failed because Expected response code 354 but got code "503", with message "503 5.5.2 Need rcpt command
".
#0 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(341): Swift_Transport_AbstractSmtpTransport->assertResponseCode('503 5.5.2 Need ...', Array)
#1 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand('DATA\r\n', Array, Array, false, NULL)
#2 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(390): Swift_Transport_EsmtpTransport->executeCommand('DATA\r\n', Array, Array)
#3 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(497): Swift_Transport_AbstractSmtpTransport->doDataCommand(Array)
#4 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(516): Swift_Transport_AbstractSmtpTransport->doMailTransaction(Object(Swift_Message), 'ictinventar@bae...', Array, Array)
#5 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(206): Swift_Transport_AbstractSmtpTransport->sendTo(Object(Swift_Message), 'ictinventar@bae...', Array, Array)
#6 /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(71): Swift_Transport_AbstractSmtpTransport->send(Object(Swift_Message), Array)
#7 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(451): Swift_Mailer->send(Object(Swift_Message), Array)
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(235): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(64): Illuminate\Mail\Mailer->send(Object(Illuminate\Support\HtmlString), Array, Object(Closure))
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(113): Illuminate\Notifications\Channels\MailChannel->send(Object(Spatie\Backup\Notifications\Notifiable), Object(Spatie\Backup\Notifications\Notifications\BackupHasFailed))
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(89): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(Spatie\Backup\Notifications\Notifiable), 'c5812dd3-6e90-4...', Object(Spatie\Backup\Notifications\Notifications\BackupHasFailed), 'mail')
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(64): Illuminate\Notifications\NotificationSender->sendNow(Array, Object(Spatie\Backup\Notifications\Notifications\BackupHasFailed))
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(35): Illuminate\Notifications\NotificationSender->send(Array, Object(Spatie\Backup\Notifications\Notifications\BackupHasFailed))
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\Notifications\ChannelManager->send(Object(Spatie\Backup\Notifications\Notifiable), Object(Spatie\Backup\Notifications\Notifications\BackupHasFailed))
#15 /var/www/snipeit/vendor/spatie/laravel-backup/src/Notifications/EventHandler.php(33): Spatie\Backup\Notifications\Notifiable->notify(Object(Spatie\Backup\Notifications\Notifications\BackupHasFailed))
#16 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(350): Spatie\Backup\Notifications\EventHandler->Spatie\Backup\Notifications\{closure}(Object(Spatie\Backup\Events\BackupHasFailed))
#17 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(200): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('Spatie\\Backup\\E...', Array)
#18 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(467): Illuminate\Events\Dispatcher->dispatch('Spatie\\Backup\\E...')
#19 /var/www/snipeit/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(274): event(Object(Spatie\Backup\Events\BackupHasFailed))
#20 /var/www/snipeit/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(266): Spatie\Backup\Tasks\Backup\BackupJob->sendNotification(Object(Spatie\Backup\Events\BackupHasFailed))
#21 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Collection.php(339): Spatie\Backup\Tasks\Backup\BackupJob->Spatie\Backup\Tasks\Backup\{closure}(Object(Spatie\Backup\BackupDestination\BackupDestination), 0)
#22 /var/www/snipeit/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(268): Illuminate\Support\Collection->each(Object(Closure))
#23 /var/www/snipeit/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJob.php(150): Spatie\Backup\Tasks\Backup\BackupJob->copyToBackupDestinations('/var/www/snipei...')
#24 /var/www/snipeit/vendor/spatie/laravel-backup/src/Commands/BackupCommand.php(52): Spatie\Backup\Tasks\Backup\BackupJob->run()
#25 [internal function]: Spatie\Backup\Commands\BackupCommand->handle()
#26 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#27 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#28 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#29 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#30 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#31 /var/www/snipeit/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#32 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#33 /var/www/snipeit/vendor/spatie/laravel-backup/src/Commands/BaseCommand.php(16): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#34 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(198): Spatie\Backup\Commands\BaseCommand->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Illuminate\Console\OutputStyle))
#35 /var/www/snipeit/app/Console/Commands/SystemBackup.php(42): Illuminate\Console\Command->call('backup:run')
#36 [internal function]: App\Console\Commands\SystemBackup->handle()
#37 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
#38 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#39 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#40 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#41 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
#42 /var/www/snipeit/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#43 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#44 /var/www/snipeit/vendor/symfony/console/Application.php(960): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#45 /var/www/snipeit/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\SystemBackup), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#46 /var/www/snipeit/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#47 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#48 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#49 /var/www/snipeit/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#50 {main}
Backup failed because: Expected response code 354 but got code "503", with message "503 5.5.2 Need rcpt command
".

In AbstractSmtpTransport.php line 457:

  Expected response code 354 but got code "503", with message "503 5.5.2 Need
   rcpt command
  "

**Additional context**
- Is this a fresh install or an upgrade? ->Fresh Install
- What OS and web server you're running Snipe-IT on->Apache 2 on ubuntu
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)-> Using the Documentation with install.sh
- Include what you've done so far in the installation, and if you got any error messages along the way.-> Tried to edit the env file with user and password-> got authentication usucessfull error. Changed back and same error. I did not change Mail driver left it at smtp
- Indicate whether or not you've manually edited any data directly in the database->No

**Comment by snipe** [comment]
Did you add the `MAIL_BACKUP_NOTIFICATION_ADDRESS=you@example.com` detailed in the release notes?

https://github.com/snipe/snipe-it/releases/tag/v4.7.4

**Comment by baer-ing** [comment]
you were right. I forogt o set this variabl. Thanks.

Now I get a error within snipeit when I click the Button "Backup now":
 Error: Starting backup... Backup failed because: unlink(/var/www/snipeit/storage/app/backup-temp/temp/db-dumps/mysql-snipeit.sql): Permission denied.

Ithink since this is a temp folder I should be able to erase its contents?
