### ISSUE TITLE
Apple Mobile Web App (PWA)

### ISSUE THREAD

**Issue by ultramizer** [snipe/snipe-it#7238]
**Server (please complete the following information):**
 - Snipe-IT Version: latest

**Describe the solution you'd like**
I would love to get Snipe-IT on my iPhone without having to open the Browser everytime. This can be achieved by adding a few lines of code to the <head> of the landing page. Those lines then tell iOS to add the website to the homescreen by using it as a Progressive Web App or PWA for short. The benefits are that you don't have the URL bar on the top, you can add a nice icon for it and you can even add a splash screen. All this really needs is the following lines of code in the <head> tag.

```
<head>
<meta name="apple-mobile-web-app-capable" content="yes">
<link rel="apple-touch-icon" href="apple-touch-icon.png">
<link rel="apple-touch-startup-image" href="launch.png">
<title>Snipe-IT</title>
</head>
```

the images can be placed in the same folder or a subfolder. With those 4 lines of code, we basically have a PWA ready, there is not much else to do, since Snipe-IT works nicely in the mobile browser already.

I would add those lines to my Snipe-IT installation, but i am too stupid to find the <head> tag that gets loaded if you go to the start page anywhere in those thousands of PHP files, maybe we can implement this very, very simple thing into the main build, or maybe someone can tell me how i can integrate it on my installation!

Cheers

**Comment by hixair** [comment]
I use PWA for several tools and would love to have this too !

**Comment by ultramizer** [comment]
I have managed to find out where to put the tags! If you add them to the header in /resources/views/layouts/default.blade.php then it works.
But this doesn't seem to solve a single problem. Whenever i click on any link inside Snipe-IT, be it the "Asset list" on the left, or "Settings" or any single item in Snipe-IT, it automatically opens Safari Browser on the iPhone, and we start where we left off. It seems that because the link's are including the domain name, that the PWA thinks it's external links and thus open's the browser... I'm not so sure about that. Maybe someone with more knowledge about PWAs can look into that!

**Comment by ultramizer** [comment]
This is still relevant. I see that you referenced to integrate the PWA Code, what about my last comment? Will it still open every link in a browser?
