### ISSUE TITLE
Snipe-IT docker upgrade

### ISSUE THREAD

**Issue by Ajensen2019** [snipe/snipe-it#7239]
**Describe the bug**
Hello all, I have inherited two Snipe-IT docker assest management servers. Yes the servers are hosting the docker images. These two servers have no internet access so I am trying to figure out how to upgrade them to the most current version of Snipe-IT I believe they are both currently 4.1.7. Every guide I find tells you how to just run a command line and it will auto download but I do not have that option. Any help would be greatly appreciated. 

Thanks,
Alex

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by neudodo** [comment]
Hello, If i want to upgrade 4.7.4 to 4.7.5 a get error message from site. 
Snipe it version 4.7.5 in docker 
OS: ubuntu 18.04
nginx 

Can you help, what should and how to create


<img width="1679" alt="Screenshot 2019-07-10 at 11 34 05" src="https://user-images.githubusercontent.com/49764443/60958561-da5a6800-a306-11e9-9e1a-6e317f0693cf.png">

[snipe-it error.txt](https://github.com/snipe/snipe-it/files/3376828/snipe-it.error.txt)

**Comment by CoventryIT** [comment]
Im getting the same error after going from 4.7.4 to 4.7.5. Im using Windows Server 2012R2 IIS upgraded VIA Docker

Is there any current fix for this?

**Comment by CoventryIT** [comment]
I was able to get around the error by renaming the table from "groups" to "permission_groups"

**Comment by neudodo** [comment]
> I was able to get around the error by renaming the table from "groups" to "permission_groups"

this works thank you
