### ISSUE TITLE
Missing Entries

### ISSUE THREAD

**Issue by jacobwoffenden** [snipe/snipe-it#724]
Forgive me if this has been dealt with before.

I am unable to see assets or asset categories I've created in the main dashboard sections

As you can see in this screenshot, I have made and checked out an asset
![screen shot 2015-04-03 at 00 45 31](https://cloud.githubusercontent.com/assets/9742606/6975947/d54aab48-d99a-11e4-9eb3-7366838ad77c.png)

But when I view All Assets, none are listed
![screen shot 2015-04-03 at 00 45 38](https://cloud.githubusercontent.com/assets/9742606/6975960/f5483924-d99a-11e4-931c-7a3f40de3b6c.png)

I am using the following
OS - Ubuntu 14.04.2 LTS
Snipe-IT version -v1.2.6.1-179-gb53847c
PHP Version - 5.5.9-1ubuntu4.7
Laravel Version - 4.2.9

Please let me know if you require any more information.

Thanks,

Jacob

**Comment by snipe** [comment]
Looks like you grabbed this off of develop or master, versus using an official release, right? Is this a fresh install, or an upgrade?

**Comment by snipe** [comment]
Try doing the following:

- run `php composer update`
- remove content (not the directory itself) of `app/storage/cache` and `app/storage/views`

**Comment by jacobwoffenden** [comment]
I got the download from http://snipeitapp.com/download/ and this is a fresh install

running that command gave me no errors

**Comment by jacobwoffenden** [comment]
It's now showing the assets!

Thanks for this :)

**Comment by snipe** [comment]
![687474703a2f2f7777772e7265616374696f6e676966732e636f6d2f722f746366692e676966](https://cloud.githubusercontent.com/assets/197404/6976173/ae3abc22-d95a-11e4-8ae9-887070671be9.gif)
