### ISSUE TITLE
User Authorization(Permission) issue? bug?

### ISSUE THREAD

**Issue by yk48** [snipe/snipe-it#7240]
#### Please confirm you have done the following before posting your bug report:

- [yes] I have enabled debug mode 
- [yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

Users are unavailable to download attached asset files on the system before the authorization is granted by the admin. When the view authorization is granted by the admin, users are able to access/view the entire license instead of the particular license.

**To Reproduce**

**Expected behavior**
When user is granted view authorization, users should be able to view certain or particular licenses as it is set. However, an excessive authorization is given to the user such as accessing the entire license of the company.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version  v4.7.4
 - OS: [e.g. Ubuntu, CentOS] Ubuntu
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.3.6

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] IE

**Additional**
I am sure this is some kind of a bug or a feature that has not developed yet. I have seen numerous posts regarding this issue such as #6296, "make the permission of the user to view and edit only specific category in the assets not all of them." Any updates and feedback would be appreciated.

**Comment by yk48** [comment]
@snipe is this a feature that needs to be developed

**Comment by sinichi19** [comment]
like in my request https://github.com/snipe/snipe-it/issues/6426
