### ISSUE TITLE
 System Unavailable after upgrade to v4.7.5

### ISSUE THREAD

**Issue by dvogelho** [snipe/snipe-it#7242]
#### Actual Behavior

We have upgraded our SnipeIT virtual machine to Debian 10 (buster), installed all PHP7.3 modules which are required to run SnipeIT, but after the upgrade only the System Unavailable message will be shown.

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/35107170/61041987-9aad8200-a3d3-11e9-9577-3e4c4634603f.png">

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
Upgrade
- Version of Snipe-IT you're running
4.7.5
- Version of PHP you're running
PHP 7.3.4-2
- Version of MySQL/MariaDB you're running 
mysql  Ver 15.1 Distrib 10.3.15-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- What OS and web server you're running Snipe-IT on
Debian GNU/Linux 10 (buster)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Github
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
I'm only receiving the error "System Unavailable"
- Any errors that appear in your browser's error console.
No errors
- Include any additional information you can find in `storage/logs` and your webserver's logs.

There are no errors in the apache2 error or access log

laravel.log
[2019-07-11 12:00:00] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method App\Console\Kernel::load() in /var/www/html/snipe-it/app/Console/Kernel.php:59
Stack trace:
#0 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(117): App\Console\Kernel->commands()
#1 /var/www/html/snipe-it/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 {main}  
[2019-07-11 12:00:00] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to undefined method App\Console\Kernel::load() in /var/www/html/snipe-it/app/Console/Kernel.php:59
Stack trace:
#0 /var/www/html/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(117): App\Console\Kernel->commands()
#1 /var/www/html/snipe-it/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 {main} 

Hopefully you can help to get the system running again.

**Comment by snipe** [comment]
Uh, I think you just forgot to run `php artisan up` to bring it back out of maintenance mode?

**Comment by michaelc64** [comment]
I'm also seeing the same issue. Running on IIS.  Have upgraded using "php upgrade.php".  Getting the "System Unavailable" sad panda.  No other error messages logged even with debug turned on.  Have just tried php artisan up, but still the same. Anywhere else to look?  Thanks!

**Comment by dvogelho** [comment]
> Uh, I think you just forgot to run `php artisan up` to bring it back out of maintenance mode?

This is the result of 'php artisan up'

In Kernel.php line 59:
                                                       
  Call to undefined method App\Console\Kernel::load()
