### ISSUE TITLE
无法安装扩展？？

### ISSUE THREAD

**Issue by 57594261** [snipe/snipe-it#7243]
composer install --no-dev --prefer-source
Loading composer repositories with package information
Installing dependencies from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for tecnickcom/tc-lib-barcode 1.15.14 -> satisfiable by tecnickcom/tc-lib-barcode[1.15.14].
    - tecnickcom/tc-lib-barcode 1.15.14 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php.ini
    - /etc/php.d/curl.ini
    - /etc/php.d/dom.ini
    - /etc/php.d/fileinfo.ini
    - /etc/php.d/gd.ini
    - /etc/php.d/json.ini
    - /etc/php.d/ldap.ini
    - /etc/php.d/mbstring.ini
    - /etc/php.d/mysql.ini
    - /etc/php.d/mysqli.ini
    - /etc/php.d/pdo.ini
    - /etc/php.d/pdo_mysql.ini
    - /etc/php.d/pdo_sqlite.ini
    - /etc/php.d/phar.ini
    - /etc/php.d/sqlite3.ini
    - /etc/php.d/wddx.ini
    - /etc/php.d/xmlreader.ini
    - /etc/php.d/xmlwriter.ini
    - /etc/php.d/xsl.ini
    - /etc/php.d/zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by svpernova09** [comment]
`sudo apt install php7.0-bcmath` Swap `7.0` with whichever version you're using.

**Comment by snipe** [comment]
Thanks, @svpernova09!
