### ISSUE TITLE
Upgrade to Snipe-It 4.7.5 failing with "Whoops, looks like something went wrong"

### ISSUE THREAD

**Issue by tedying** [snipe/snipe-it#7245]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Upgraded snipe-it from 4.1.6 to 4.7.5.  Uninstalled PHP 5.6 and installed PHP 7.2.20.  Getting the "Whoops, looks like something went wrong" error.

**To Reproduce**
1. Go to http://server.domain
2. See error

**Expected behavior**
Looking for help reviewing the laravel.log to determine what the issue is.

**Server (please complete the following information):**
 - Snipe-IT Version: **4.7.5**
 - OS: [e.g. Ubuntu, CentOS]  **Centos 7.6.1810**
 - Web Server: [e.g. Apache, IIS]  **Apache 2.4.6**
 - PHP Version **PHP 7.2.20**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] **Windows 10**
 - Browser [e.g. chrome, safari]  **chrome**
 - Version [e.g. 22]  **75.0.3770.100**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
**DEBUG is turned on, laravel.log appended below**
**Error not reproducable on https://snipeitapp.com/demo**

**Additional context**
- Is this a fresh install or an upgrade? **Upgrade from 4.1.6**
- What OS and web server you're running Snipe-IT on:  **See above**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): 
**I followed the directions on https://snipe-it.readme.io/docs/upgrading-to-v4**
- Include what you've done so far in the installation, and if you got any error messages along the way.  **I did have some errors and with composer and php, but I backed all the to the git download and restarted and got no errors the second pass through**
- Indicate whether or not you've manually edited any data directly in the database
**No data manipulation.  I have a mysqldump backup of the database from prior to the installation just in case**

**Needed to remove PHP 5.6 from our system.  So I followed the directions to back up the system, then I removed PHP 5.6, installed PHP 7.2.20 and then followed the upgrade directions.  As mentioned, I had some issues with PHP and composer, but repulled the installation from git and ran through the commands without errors on the second pass.  Then found the "Whoops" error.  I have cleared the cookies and tried to reload, with the same issue.  I cleared the laravel.log and reproduced the error so that only the the part that was appended with the error is included**

**Please let me know if there are any additional details that you require that I missed.**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**laravel.log included:**

> [2019-07-11 13:01:34] production.ERROR: RuntimeException: The only supported ciphers are MCRYPT_RIJNDAEL_128 and MCRYPT_RIJNDAEL_256. in /opt/snipe-it/app/LegacyEncrypter/McryptEncrypter.php:48
> Stack trace:
> #0 /opt/snipe-it/app/Console/Commands/RecryptFromMcrypt.php(100): App\LegacyEncrypter\McryptEncrypter->__construct('Y5hJeC7x1i7OxhD...', 'rijndael-256')
> #1 [internal function]: App\Console\Commands\RecryptFromMcrypt->handle()
> #2 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
> #3 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
> #4 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
> #5 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
> #6 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\Container\Container->call(Array)
> #7 /opt/snipe-it/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
> #8 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
> #9 /opt/snipe-it/vendor/symfony/console/Application.php(969): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #10 /opt/snipe-it/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\RecryptFromMcrypt), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #11 /opt/snipe-it/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #12 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #13 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #14 /opt/snipe-it/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #15 {main}
> [2019-07-11 13:01:34] production.ERROR: The only supported ciphers are MCRYPT_RIJNDAEL_128 and MCRYPT_RIJNDAEL_256. {"exception":"[object] (RuntimeException(code: 0): The only supported ciphers are MCRYPT_RIJNDAEL_128 and MCRYPT_RIJNDAEL_256. at /opt/snipe-it/app/LegacyEncrypter/McryptEncrypter.php:48)
> [stacktrace]
> #0 /opt/snipe-it/app/Console/Commands/RecryptFromMcrypt.php(100): App\\LegacyEncrypter\\McryptEncrypter->__construct('Y5hJeC7x1i7OxhD...', 'rijndael-256')
> #1 [internal function]: App\\Console\\Commands\\RecryptFromMcrypt->handle()
> #2 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Array, Array)
> #3 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(87): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
> #4 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
> #5 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php(549): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
> #6 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Command.php(183): Illuminate\\Container\\Container->call(Array)
> #7 /opt/snipe-it/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
> #8 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Command.php(170): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
> #9 /opt/snipe-it/vendor/symfony/console/Application.php(969): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #10 /opt/snipe-it/vendor/symfony/console/Application.php(255): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\RecryptFromMcrypt), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #11 /opt/snipe-it/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #12 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Console/Application.php(88): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #13 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #14 /opt/snipe-it/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
> #15 {main}
> "}

**Comment by snipe** [comment]
The upgrade info you linked to is for upgrading from v3 to v4. You're saying you're upgrading 4.1.6 to 4.7.5, so you wouldn't use those directions.

**Comment by tedying** [comment]
Yes, I see that you are correct.

However, since I did follow those directions, any thoughts on how to fix the issue I am having or where I can find directions to help me reupgrade or repair the situation I am in?

Any pointers in the right general direction would help as I can't parse the error messages above.
