### ISSUE TITLE
Check out in future date

### ISSUE THREAD

**Issue by djdamith** [snipe/snipe-it#7247]
**Server (please complete the following information):**
 - Snipe-IT Version - v4.7.3 build 4098 (g087cdd859)
 - OS: [e.g. Ubuntu, CentOS] - Windows server 2012 r2
 - Web Server: [e.g. Apache, IIS] -IIS
 - PHP Version -7.2.19

**Is your feature request related to a problem? Please describe.**

When a new employee join the company ( in a future date may be in a week of time ) we prepare the devices and assign them to the user. I have create a MS SQL report which can pick the asset information and employee information and get a hard copy of the EULA which new joinees need to sign-off ( requirement of ISO audits ). I was able to pick future dates in older versions but after the upgrade its gone. Now i have to wait till the exact join date to assign the assets and prepare those hard copies which can be very difficult when the number of new joiners are high.

**Describe the solution you'd like**

Since this is removed by issue #4345 , is it possible to get a button to enable / disable this feature ?

**Describe alternatives you've considered**
Noting so far

**Additional context**

**Comment by djdamith** [comment]
any suggestions ?

**Comment by djdamith** [comment]
hi @snipe ,

any possible workaround?

**Comment by phil-flip** [comment]
Any chance, this can be worked on again? The idea being that we usually plan the asset checkouts, as they are shared with multiple users. So having like a like of future checkouts would be a nice touch.

**Comment by ginuso630-hub** [comment]
Hi, is there any news regarding this request?
We urgently need to set future dates for checking out and checking in the assets.
We use Snipe-IT Version v8.3.1 - build 19577 (master).
