### ISSUE TITLE
[Importing assets] Asset Tag should auto increment

### ISSUE THREAD

**Issue by 3ter** [snipe/snipe-it#7248]
**Server:**
 - Snipe-IT Version 4.6.5
 - OS: Windows Server 2016
 - Web Server: IIS
 - PHP Version 7.2.7

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to look for the next asset tag when I need to import assets with a .csv file using the web interface.

**Describe the solution you'd like**
I want to leave the Asset Tag column blank for assets that are new and expect them to take the next available asset tag following the increment details I've specified in the settings.

**Describe alternatives you've considered**
The workaround is to tell other people not to add assets right now and to look up the starting asset number and fill the column accordingly in the .csv.

**Additional context**
![image](https://user-images.githubusercontent.com/11499929/61114884-93e54480-a491-11e9-9411-ac0c060f05fc.png)
![image](https://user-images.githubusercontent.com/11499929/61114893-98116200-a491-11e9-9add-1edadd135a5a.png)

**Comment by htilly** [comment]
Plus one on this one.. seems to be requested before:
https://github.com/snipe/snipe-it/issues/2136
