### ISSUE TITLE
Snipe-it on windows 7 32bit Server Error: 500 (Internal Server Error)

### ISSUE THREAD

**Issue by vinodsinghp** [snipe/snipe-it#725]
Hi,
I have install the Apps on Windows 7 32 bit OS with the instruction as per
http://snipeitapp.com/documentation/installing-on-iis/
But after installation I am getting following error
Ouch.

Server Error: 500 (Internal Server Error)

Please help me to resolve the Issue.

**Comment by snipe** [comment]
Please see the Getting Help documentation. http://snipeitapp.com/documentation/getting-help/

**Comment by vinodsinghp** [comment]
hi,
Tried didn't find any thing useful

**Comment by vinodsinghp** [comment]
The storage logs says
[2015-04-04 10:06:00] production.ERROR: exception 'InvalidArgumentException' with message 'Database [] not configured.' in C:\inetpub\wwwroot\snipe-it\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php:265

**Comment by vinodsinghp** [comment]
but after that I did googled & database was created

**Comment by snipe** [comment]
"but after that I did googled & database was created" - I don't know what that means. Please see the common issues oage for help with the database not configured error. http://snipeitapp.com/documentation/common-issues/

**Comment by Tortschi** [comment]
Look at your app/config Folder you have no "database.php". You find an Example in app/config/production.

**Comment by snipe** [comment]
Any luck?

**Comment by vinodsinghp** [comment]
Sorry for late reply. I installed it using Xampp. Finally got it working. Thanks for your support.

Thanks
Vinod Pardeshi

**Comment by vinodsinghp** [comment]
how can I add or Edit Status Type in status Labels.

**Comment by snipe** [comment]
You should just be able to Admin > Status Labels in the top nav.

![screen shot 2015-04-15 at 9 42 37 am](https://cloud.githubusercontent.com/assets/197404/7164233/d18e9592-e353-11e4-982d-e9bc8344c6d1.png)

**Comment by vinodsinghp** [comment]
I want to edit Status Type

**Comment by vinodsinghp** [comment]
I want to edit status type - deployable , pending.etc

**Comment by snipe** [comment]
Status labels are how you edit those types.

**Comment by vinodsinghp** [comment]
I want to add In Use Status in Status Type. Who can I Add that.
e.g:-
Name - Blackberry Bold
Note - 
Status Type - In Use
Coz I am unable to Edit or Add Status Type.

**Comment by snipe** [comment]
As I have already said,u ou should just be able to Admin > Status Labels in the top nav. What do you see when you go there? And what do you see when you try to add/edit status labels? (Please include a screenshot)

**Comment by vinodsinghp** [comment]
Sorry Got it.
My Mistake.

**Comment by vinodsinghp** [comment]
Can I make changes to Dashboard. Means On left I want add Location on Top, then Asset and so on.

**Comment by snipe** [comment]
If you make any changes to the dashboard, they will be overwritten the next time you upgrade. There is no built-in way to change the dashboard at this time.

**Comment by vinodsinghp** [comment]
Okay.

**Comment by cgtechuae** [comment]
hi vinod,

Do you have any document for step by step snipe it installation with Xamp

**Comment by vaatamohan** [comment]
HI vinodsinghp,

How do configure snipe it using xamp,please give briefly full installion configuration instruaction
