### ISSUE TITLE
SnipeIT Office 365 SMTP Error

### ISSUE THREAD

**Issue by sadams1980** [snipe/snipe-it#7251]
#### Expected Behavior (or desired behavior if a feature request)

Email sends without issue.

-----

#### Actual Behavior

Hi all,

I am setting up SnipeIT at my school again, but I am struggling to get the email setting sorted. I am trying to use Office365, but getting this error.

Error: An Error has occured! Connection could not be established with host smtp.office365.com [Unable to find the socket transport "starttls" - did you forget to enable it when you configured PHP? #1361197232]

How do I enable starttls in PHP?

Any ideas?

Cheers

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh install
- Version of Snipe-IT you're running 4.7.5
- Version of PHP you're running - 
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by tankerkiller125** [comment]
In the `.env` file change `MAIL_ENCRYPTION=none` to `MAIL_ENCRYPTION=tls` this should resolve your issue.

**Comment by sadams1980** [comment]
Hi, sorry did not respond sooner I have been away.  I have done that and this is the issue i get:
"Error: An Error has occured! Connection could not be established with host smtp.office365.com [A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. #10060]"

Any continued help would be appreciated.
