### ISSUE TITLE
FEATURE REQUEST - Check out/in Emails for Managers or Assigned Users

### ISSUE THREAD

**Issue by gilesytheking** [snipe/snipe-it#7255]
#### Expected Behavior (or desired behavior if a feature request)

Send a check-in / checkout email to location managers when an asset is checked in/out from their location.

Send a check-in / checkout email to an asset assigned user when an Asset is checked in/out to another asset assigned to them. (EG. User has a vehicle assigned to them. Email is sent to the user when Equipment is checked in/out to the vehicle.) 

-----

#### Actual Behavior

Currently there aren't any email notifications when assets are checked out to a location or to another asset.

**Comment by baer-ing** [comment]
Well you could set it to send an Email on the Category based...? I think this will work...?

**Comment by sinichi19** [comment]
https://github.com/snipe/snipe-it/issues/6417

same request but dont know why already closed my request,

**Comment by ajsy** [comment]
+1

**Comment by usernet-vm** [comment]
+1

**Comment by pierinz** [comment]
Yes, this feature request is still relevant.

**Comment by pierinz** [comment]
Yes, this feature request is still relevant.

**Comment by pierinz** [comment]
Yes, this feature request is still relevant.

**Comment by pierinz** [comment]
yes
