### ISSUE TITLE
Set Snipe-it with a secondary URL

### ISSUE THREAD

**Issue by Pajaura** [snipe/snipe-it#7256]
#### Expected Behavior (or desired behavior if a feature request)

Going to http://serverurl/asset open snipe-it website, on http://serverurl/network open the network website, on http://serverurl/othersite open the othersite website, etc.

-----

#### Actual Behavior

Once snipe-it is installed, despite having configured the APP_URL with http://serverurl/asset and created the specific virtual host, I can no longer reach any website previously reachable on the server. If, for example, I open the url http://serverurl/network, the sad panda page of snipe-it appears on the browser, as if it were actually looking inside the application rather than on the server. Furthermore, the snipe-it url (which I modified, for convenience during installation, in ASSET) appears as http://serverurl

-----

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  **Fresh**
- Version of Snipe-IT you're running **v4.7.5 - build 4118**
- Version of PHP you're running **7.2.19**
- Version of MySQL/MariaDB you're running **5.7.26**
- What OS and web server you're running Snipe-IT on **Ubuntu 19.04 with Apache 2.4.38**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **Manual by Github clone**

**Comment by snipe** [comment]
I'd need to see your web server configs. My guess would be that you've got the wrong public directory for the Snipe-IT app, the wrong ServerName, you're missing [the alias necessary to run it in a subdirectory](https://snipe-it.readme.io/docs/subdirectories), or you didn't restart the web server after making changes.

**Comment by Pajaura** [comment]
Thank you for reply! Well. The host name is really really hard to go wrong, it's simply the ip address..
This is the main server directory structure:
- var
-- www
--- html
---- asset <-- This is Snipe-IT directory
---- srvmonitor
---- phpmyadmin
---- wiki
Snipe-IT's public directory is correct, I believe that if it were not so I wouldn't even be able to use it, am I right?
Regarding the configuration of the web server, what do you need to know? What data should I send you?

**Comment by Pajaura** [comment]
Hello. I haven't been able to solve my problem yet. I tried to configure everything again but without positive results. I also followed the instructions in this guide https://snipe-it.readme.io/docs/subdirectories but, although I thought they could contain the definitive solution, I still can't open snipe-it with a specific link without it overrides all sites and applications present in the server root. Can someone please help me?
