### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by mainstayit** [snipe/snipe-it#7257]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Updating from v4.5.0 build 3701 (gbf1e742df) to latest build using php upgrade.php

**Expected behavior**
Snipe-it login screen / homepage

**Screenshots**
![image](https://user-images.githubusercontent.com/40659449/61281123-08312800-a7b1-11e9-86ae-4d147e417005.png)
![image](https://user-images.githubusercontent.com/40659449/61281152-14b58080-a7b1-11e9-9068-91198a0b332f.png)

**Server (please complete the following information):**
 - Snipe-IT Version: v4.5.0 build 3701 (gbf1e742df)
 - OS: Debian 10
 - Web Server: Apache
 - PHP Version: PHP 7.3.7-1+ubuntu18.10.1+deb.sury.org+1

**Additional context**
- Is this a fresh install or an upgrade? Upgrade
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) followed the guide at https://www.howtoforge.com/tutorial/how-to-install-snipe-it-on-debian-9/
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database: Edited the labels file in var/www/sipe-it/resources/views/hardware

**Comment by mainstayit** [comment]
Just a note that although PHP 7.3.7-1+ubuntu18.10.1+deb.sury.org+1 is installed the snipe-it website is reporting 7.0.33-8+ubuntu18.10.1+deb.sury.org+1

**Comment by snipe** [comment]
> Just a note that although PHP 7.3.7-1+ubuntu18.10.1+deb.sury.org+1 is installed the snipe-it website is reporting 7.0.33-8+ubuntu18.10.1+deb.sury.org+1

That's kinda not possible though... Might be that you have 7.3.7 installed as the PHP cli version, but 7.0.33 as the web server version. 

Try running the standard cache clearing commands: https://snipe-it.readme.io/docs/common-issues#section-quick-tip-handy-commands

And running `composer install --no-dev`

**Comment by mainstayit** [comment]
Thanks for getting back to me. 

> > Just a note that although PHP 7.3.7-1+ubuntu18.10.1+deb.sury.org+1 is installed the snipe-it website is reporting 7.0.33-8+ubuntu18.10.1+deb.sury.org+1
> 
> That's kinda not possible though... Might be that you have 7.3.7 installed as the PHP cli version, but 7.0.33 as the web server version.

Agreed, I should have read this properly

> Try running the standard cache clearing commands: https://snipe-it.readme.io/docs/common-issues#section-quick-tip-handy-commands
> 
> And running `composer install --no-dev`
> 
> > <img alt="" width="48" src="/favicon.ico">**[Common Issues](https://snipe-it.readme.io/docs/common-issues#section-quick-tip-handy-commands)**     These commands should be run from your Snipe-IT project root, just like every other cli command we mention. They should not need to be run as root/sudo/admin.  These commands clear out cached service files that help speed up modern PHP applications but can also very occasionally be out of date,...

I have tried running those commands but got the below errors

![Capture](https://user-images.githubusercontent.com/40659449/63090798-4f4b3e00-bf54-11e9-8c25-2699e5749f7c.PNG)

**Comment by snipe** [comment]
Try deleting your `vendor` directory and then running `composer install --no-dev` again.

**Comment by mainstayit** [comment]
I think there are some issues with the installation, I will sort these out and if I still have a problem I will create a new ticket.
Thanks
