### ISSUE TITLE
AD Users cant Login using Ldap

### ISSUE THREAD

**Issue by ksuganthankumar** [snipe/snipe-it#7258]
Hi,

           I have recently installed snipeit.Ldap users are shown in peoples.But cant login using those id after enable login access also.

![ldap configuration](https://user-images.githubusercontent.com/52965027/61298023-23c12080-a7fb-11e9-8bca-53d74f39845c.JPG)
![Login Enabled](https://user-images.githubusercontent.com/52965027/61298024-2459b700-a7fb-11e9-9a1b-5cf1d38649c1.JPG)
![Login page Error](https://user-images.githubusercontent.com/52965027/61298026-2459b700-a7fb-11e9-86c8-e70fea7fcc38.JPG)

**Comment by CoventryIT** [comment]
Is this a windows Active directory your trying to connect too?

**Comment by ksuganthankumar** [comment]
After one successful login again it turned off automatically.Most of users can login.But some users cant.
![login access](https://user-images.githubusercontent.com/52965027/61348165-485ddc80-a87d-11e9-83bf-a44f70bd95f1.JPG)

**Comment by ksuganthankumar** [comment]
I found the solution.Some changes was made in our AD.Now its working fine.Thanks......

**Comment by braindonors** [comment]
Can you share what you changed in AD?

**Comment by ksuganthankumar** [comment]
I have changed the option in AD user properties.  Uncheck the option "store password in reversible encryption".
![Pass Encription](https://user-images.githubusercontent.com/52965027/62676239-beaab600-b9c7-11e9-87fd-c8c64743d756.JPG)
