### ISSUE TITLE
Support phpdocumentor/reflection-docblock:^4.0

### ISSUE THREAD

**Issue by Jelle-S** [snipe/snipe-it#7259]
**Server (please complete the following information):**
 - Snipe-IT 3.7.5 
 - OS: Ubuntu
 - Web Server: Apache
 - PHP 7.2 

**Is your feature request related to a problem? Please describe.**
I'm in a dependency-hell with one of my projects. It would help if snipe-it would support phpdocumentor/reflection-docblock:^4.0 (now fixed to version 3.2.2 in composer.json).

**Describe the solution you'd like**
Change version constraint to `^3.2.2|^4.0`

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by snipe** [comment]
How does our version of phpdocumentor affect your project?
