### ISSUE TITLE
complete restore of backup

### ISSUE THREAD

**Issue by L3nny5** [snipe/snipe-it#7260]
Hey Snipe,

sorry to ask this, maybe it was asked somewhere already. 

I did something really stupid. Upgrading without reading (it was working fine in the past). I upgraded (or should I say tried upgrading) from 4.6.8 to 4.7.5. I did not read, that I need to upgrade php before as well. So I got several issues, because only php 7.0 was installed. 
Then I tried to update php and also wanted to upgrade my ubuntu 14.04 to at least 16.04 or even better 18.04...

Well long story short: I now have a completely ruined system which is not booting at all anymore. So I want to start from scratch: Install ubuntu, install snipe, restore backup.
I found quite a lot of documentation how to create a backup and also installing snipe. But I couldn't find anything about how to restore it.

Could you give me a quick heads up or point me to the documentation article... I'm kinda stuck now. 

I have the backup of snipe (.zip file) and also a backup of my snipe-it root folder. As well as the apache2 configuration.

Thank you!

BTW: Love your twitter ❤️

**Comment by L3nny5** [comment]
I just found this doc: https://snipe-it.readme.io/docs/moving-snipe-it

Which answers a lot of questions. However it does not tell me how exactly I'll get my data back into the database. Could anybody give me a command?

**Comment by EarlRamirez** [comment]
@L3nny5 you can restore using the following command `mysql -u db_user -p db_name < db_backup.sql`
replace db_user, db_name and db_backup.sql with your details

**Comment by L3nny5** [comment]
@EarlRamirez Thank you. Is it the same command for MariaDB?

**Comment by EarlRamirez** [comment]
Yes sir

**Comment by L3nny5** [comment]
It worked like a charm! My system is now up to date and is working fine.
The only which was not working after the migrations was the API Token. I had to recreate it.
