### ISSUE TITLE
Ldap-Sync in Docker

### ISSUE THREAD

**Issue by Cobra1978** [snipe/snipe-it#7266]
Hi.

Maybe thi question was already answered, bu i wasn't able to find it.

There is any way to schedule ldap-syn inside the docker container without modifyng it with cron or any other external scheduler?

 - Snipe-IT Version: 4.7.5
 - Official Snipe-It Docker Image

Thanks and Best Regards

**Comment by mmasson** [comment]
I would also be interested in the answer.  I logged in the container and I saw that was a scheduler running (/bin/bash -c while true; do /var/www/html/artisan schedule:run; sleep 1m; done).  I'm not too familiar with it, could we use that to schedule an LDAP sync?

**Comment by ghost** [comment]
> 
> 
> I was able to workaround the problem getting the /supervisord.conf file from the container and replacing it with the same one but with this added to it:
> 
> ```
> [program:ldap_schedule]
> ; Run the LDAP sync every 2 hours
> command=/bin/bash -c "while true; do /var/www/html/artisan snipeit:ldap-sync --summary; sleep 120m; done"
> user=docker
> stdout_logfile=/dev/stdout
> stdout_logfile_maxbytes=0
> stderr_logfile=/dev/stderr
> stderr_logfile_maxbytes=0
> ```
> 
> Then I restarted the container, it noew syncs LDAP every 2 hours.
> 
> Thanks,
> Martin

As the default /etc/supervisord/supervisord.conf is not used, could it be a good idea to put in /supervisord.conf an include section, so everyone can add this (or other tasks) without overriding the whole file?

**Comment by ghost** [comment]
I've solved the problem by creating a Rancher Cron witth snipe-it image that performs scheduled ldapsync, anyway i thing that including custom conf to avoid the container duplication could be better.

**Comment by sashasimkin** [comment]
Still happens in 6.1.0, a separate cron needs to be created for ldap sync job, but it gets worse in the docker world, because one would need to duplicate the container definition and implement external scheduling.

Is it possible to have ldap-sync as part of existing scheduled jobs runs?
