### ISSUE TITLE
Fields and columns for computer parts, Ram amount, HDD size and HDD type

### ISSUE THREAD

**Issue by MartijnSnappet** [snipe/snipe-it#7267]
**Server (please complete the following information):**
 - Snipe-IT Version   v4.6.15 - build 4011
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

We like to create a CMDB overview, for a replacement list. herefore we like to know eactly what type of PC's we have, what the amount of RAM and HDD size and type is, on order to determine if a machine needs to be replaced.

**Describe the solution you'd like**
We like to have default fields to fill in  RAM amount, HDD size and HDD type

**Describe alternatives you've considered**
Notes field can be used but this does not  cover our problem

**Comment by CoventryIT** [comment]
Why don't you create custom fields called HDD, RAM and so on and apply them to a fieldset? Then when you creat a computer model have that fieldset apply?

**Comment by snipe** [comment]
That's what custom fields are for. https://snipe-it.readme.io/docs/custom-fields

**Comment by MartijnSnappet** [comment]
Thanks a lot, Since we are quite new here with the system we didn't know yet about custom fields.  I think this covers all my needs !
