### ISSUE TITLE
[Feature Request] Make Asset Tag Clickable Again

### ISSUE THREAD

**Issue by ss-dsheets** [snipe/snipe-it#727]
In an earlier version, you were able to click on the asset tag "ABC-1" to then view the asset. Looks like that feature has moved to the asset name. Could it come back to the asset tag, pretty please? :D 

As a side props, loving the new sorting features on the asset lists.

Thanks!

**Comment by snipe** [comment]
I believe this is already fixed on develop.

**Comment by snipe** [comment]
https://github.com/snipe/snipe-it/commit/e88a81141fd1d8929412e0e32a17cdfa8d53acd1
