### ISSUE TITLE
Upgrade remains on same version 4.6.3

### ISSUE THREAD

**Issue by RobotRabbit** [snipe/snipe-it#7277]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Trying to upgrade from Version v4.6.3 by running php upgrade.php. The upgrade completes successfully yet it remains on v4.6.3. Am I meant to do something before running php upgrade.php?

**To Reproduce**
1. Go to 'Snipe-IT project root folder'
2. Run: 'php upgrade.php'  as snipeitapp user
3. Upgrade completes successfully.
4. Upgrade completes successfully with below message
FINISHED! Clear your browser cookies and re-login to use :
your upgraded Snipe-IT.
5.Re-login and it's still on v4.6.3

**Expected behavior**
Upgrades to a newer version than 4.6.3

**Screenshots**
-

**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.3
 - OS: Ubuntu 18.04
 - Web Server: Apache
 - PHP Version 7.2.19

**Error Messages**
No errors, just doesn't upgrade
- Include any additional information you can find in `storage/logs` and your webserver's logs. Can't see anything regarding the upgrade in these log files

**Comment by sinichi19** [comment]
I think you edited some files or source code..
after you run php upgrade.php below that have a code you need to run first included email address then run the php upgrade.php again

**Comment by RobotRabbit** [comment]
Hi Sinichi, I'm not sure what you mean?

**Comment by sinichi19** [comment]
> Hi Sinichi, I'm not sure what you mean?

cant remember but please run the php upgrade.php then paste the screen shot here after you hit enter

**Comment by RobotRabbit** [comment]
![image](https://user-images.githubusercontent.com/53078810/61616282-4f636100-ac68-11e9-9d5c-d094c2d6b0be.png)

**Comment by RobotRabbit** [comment]
I suppose this is the issue? 
Warning: The lock file is not up to date with the latest changes in composer.json

**Comment by sinichi19** [comment]
@RobotRabbit  please screen shot below the line on php upgrade.php after you hit enter

**Comment by RobotRabbit** [comment]
![image](https://user-images.githubusercontent.com/53078810/61622626-75433280-ac75-11e9-9e53-8bcb91f79b89.png)

**Comment by sinichi19** [comment]
As sorry cant find the code not listed in your screen shot.. we have a same problem but after run first the code and run again the php upagrade,php its works ..

The code shows after i hit the enter.

(and make sure you installed your snipe-it using Git)

**Comment by RobotRabbit** [comment]
Hi Sinichi,

That resolved it, I thought I had installed via Git, I switched to a Git install with below link and the php upgrade.php worked.

https://snipe-it.readme.io/v4.6.3/docs/switching-to-a-git-install

Thanks for all the help!
