### ISSUE TITLE
Location overview should show consumables

### ISSUE THREAD

**Issue by berendt** [snipe/snipe-it#7283]
At the moment the location overview (e.g. `/locations/10`) shows no consumables.

Since it is possible to assign a location to the consumables, these should also be listed in the overview.

**Comment by iaingeorge** [comment]
The locations overview page is quite incomplete, it does not show either Accessories or Consumables. Would be fantastic if lists for these could be added.

**Comment by mtausig** [comment]
Still relevant.

**Comment by iaingeorge** [comment]
This appears to have been addressed in pull request #7192, however it has not actually been pushed out.
