### ISSUE TITLE
Add last name (smith@example.com) as username/email format

### ISSUE THREAD

**Issue by berendt** [snipe/snipe-it#7285]
At the moment it is not possible to use the last name as username/email format (`smith@example.com`). Often only the last name is used as account. Accordingly, this should be possible.

**Comment by berendt** [comment]
Since this is a feature request that has not yet been implemented, it is still relevant.

**Comment by marchwicki** [comment]
Please reopen and add this feature. Lastname@ is probably the most common email format.

**Comment by berendt** [comment]
I find it annoying that such little things are always closed without any reaction by a developer. For me this is now unfortunately a reason to look for alternatives.
