### ISSUE TITLE
Request user manual  in PDF format

### ISSUE THREAD

**Issue by hsigor** [snipe/snipe-it#7288]
**Server (please complete the following information):**
 - Snipe-IT Version: 4.7.5
 - OS: Windows Server 2008 R2
 - Web Server: Apache 2.4.93
 - PHP Version: 7.2.18

**Describe the solution you'd like**
Eu gostaria de saber se é possível enviar o manual do usuário e a documentação de instalação do sistema em formato PDF. Irá facilitar para ciração de treinamentos para os usuários do sistema.

**Comment by snipe** [comment]
Unfortunately that's not something our documentation platform offers at this time.
