### ISSUE TITLE
Option to customize or disable Serial Number splitting

### ISSUE THREAD

**Issue by b-** [snipe/snipe-it#729]
Snipe IT splits serial numbers up into 10-character groups separated by spaces (presumably for human readability?). When I enter a 25-character serial number separated by dashes into the Software Licenses section (a Microsoft Product Key, for instance) it still splits it up, making it impossible to copy and paste into a Product Key field without pasting it into Notepad first and getting rid of the spaces. For example, "XXXXX-XXXXX-XXXXX-XXXXX-XXXXX" is displayed as the following:

>**Serial:** XXXXX-XXXX X-XXXXX-XX XXX-XXXXX

Is there a way to force Snipe IT to display certain (or all) serial numbers verbatim? Or otherwise to customize the formatting? And if not, can there be?

**Comment by snipe** [comment]
This is in assets or licenses?

**Comment by b-** [comment]
This is in licenses.

**Comment by b-** [comment]
If it's for readability's sake (which I don't see the point of anyway since ten characters is a lot to group together) there are CSS tricks to add whitespace that isn't an additional character (thus achieving the same result without breaking copying and pasting).

As an example, let's say I want to install Microsoft Office on a computer. I can check out the license on Snipe-It, and then when Office asks for the key I have to manually enter it in when the setup wizard DOES accept copying and pasting of keys. If i paste the one from Snipe-It in, it gets all confused by the formatting and I have to enter it in manually anyway. This is only because Snipe-It is adding a space character after tenth character in the serial. I can type dashes into the serial number (for readability's sake, or because some keys have dashes), and it still breaks the key up.

**Comment by snipe** [comment]
Yeah, I understand the problem, was just asking to see where you were identifying it so I could test my fix.
