### ISSUE TITLE
Inconsistent date entry field formats.

### ISSUE THREAD

**Issue by lucasjkr** [snipe/snipe-it#7291]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Date field for  assets is inconsistent. If you edit a single asset, it is in YYYY-MM-DD format, but if you select multiple assets and edit them, you must enter the date as MM/DD/YYYY.

**To Reproduce**
1. Go to Assets->List All
2. Click the name of the first asset in the list.
3. On viewing the asset page, click the actions button, select edit.
4. On the resulting screen, purchase date needs to be entered as YYYY-MM-DD
5. Now, go to Assets->List All
6. Click the checkbox next to one or more assets
7.  Make sure the Bulk entry selector says Edit, and click Go.
8. Purchase Date entries need to be made in a different format.

**Expected behavior**
Expect both edit screens to want input in the same format.

**Server (please complete the following information):**
 - Snipe-IT Version: v4.6.13 build 3985 (g5f3147cf3)
**If this has been fixed in a later build, please accept my apology!

**Comment by CasseRedus** [comment]
@snipe Can you please assign this issue to me or add me as a collaborator? Is there a preference of which of the two formats should be used?
