### ISSUE TITLE
migrade error in sql server

### ISSUE THREAD

**Issue by thien154** [snipe/snipe-it#730]
migrade error in sql server tables are migrate but missing some fields.
![image](https://cloud.githubusercontent.com/assets/10879686/7047216/699267ca-de35-11e4-939d-6b64cd45efc4.png)

![image](https://cloud.githubusercontent.com/assets/10879686/7047109/aabd0530-de34-11e4-8cf7-d409fbb15944.png)

**Comment by snipe** [comment]
Can you use MySQL? A few of the migrations use ALTER TABLE, which AFAIK does not exist in SQL Server.
