### ISSUE TITLE
Have Custom Fields in 'Add New Field to Fieldset' dropdown list be ordered alphabetically

### ISSUE THREAD

**Issue by apizz** [snipe/snipe-it#7300]
**Server (please complete the following information):**
 - Snipe-IT Version : **4.7.5** in Docker
 - OS: **CentOS 7.5**

**Is your feature request related to a problem? Please describe.**
When creating or updating a fieldset with custom fields, when you select the 'Add New Field to Fieldset' dropdown menu, custom fields are listed in the order in which they were created in the system.  As such, it can be difficult to find the one you're looking for.

![Screen Shot 2019-07-25 at 3 46 45 PM](https://user-images.githubusercontent.com/11789931/61903802-6e295800-aef3-11e9-8393-b99926abe1b2.png)

**Describe the solution you'd like**
Would like to see custom fields in the dropdown menu be listed in alphabetical order.

**Describe alternatives you've considered**
Manually renaming all custom fields to be in alphabetical order ... ?  Manually changing the database field?  Seems dangerous & overly complicated ...

**Comment by snipe** [comment]
Not everyone will want that behavior though. You'd be better off alphabetizing the options in the textarea before adding those dropdown values so that they will be in order.

**Comment by apizz** [comment]
@snipe I don't think I understand your suggestion.  How would I go about accomplishing what I'm looking for in having this list of custom fields be alphabetized?

**Comment by apizz** [comment]
Yes still relevant

**Comment by apizz** [comment]
Yes

**Comment by cliff-LINKS** [comment]
+1
If you have an extensive list of custom fields, the chronologic order of the list makes no sense. It makes it extremely hard to find the field you are looking for.

As a work around, is there an way to alter the order of the fields in the popup directly in the database?

**Comment by cliff-LINKS** [comment]
Or rather, allow a custom order other than creation date in the custom fields list, and respect that custom order in the dropdown list.

Cliff

**Comment by apizz** [comment]
This is no longer necessary after the v4.9.1 release introduced the ability to search for custom fields when being added, which is ultimately a better solution.  Therefore, this FR is no longer relevant. Closing ...

**Comment by justwork500** [comment]
I would also like the ability to add a custom field drop down list. To do the sorting a setting that lets you set the numerical value of the order or just automatically sort by its alphanumerical value. Specifically why I would like it would be to add a field for my Copiers and Managed printers to let staff select the support vendor from a list when they create the asset and then add it to one of our support contracts.
