### ISSUE TITLE
X rows per page dropdown button at bottom of page shows list below, rather than above

### ISSUE THREAD

**Issue by apizz** [snipe/snipe-it#7301]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
This is less of a 'bug' and more of an 'unexpected behavior' report.

On any page that only shows 1 to X of Y rows, there is a dropdown menu to the right to select X number of rows to show on the page.  At the top of the page, when this # of rows dropdown is selected, it reveals the list below the button.  At the bottom of the page when the row list button is selected, the list also appears below the button.  As a result, you have to scroll further than what was previously considered the bottom of the page to actually see the list and select an option.

I've confirmed this behavior both in my Docker instance as well as in the Snipe-IT online demo.

Before selection
![Screen Shot 2019-07-25 at 4 04 33 PM](https://user-images.githubusercontent.com/11789931/61906096-95365880-aef8-11e9-89dd-a753fe9dcf3b.png)

When selected.  Note the list outline below the button
![Screen Shot 2019-07-25 at 4 04 39 PM](https://user-images.githubusercontent.com/11789931/61906130-a4b5a180-aef8-11e9-890c-4b9cdafd9d10.png)

After scrolling to the 'new' bottom of page
![Screen Shot 2019-07-25 at 4 04 44 PM](https://user-images.githubusercontent.com/11789931/61906152-b434ea80-aef8-11e9-8366-cee4182198ac.png)

**To Reproduce**
1. Go to the Models page, Assets page, any page that has many items but only shows a subset of total.
2. Scroll down to the bottom of the page and select the dropdown button next to 'rows per page'.
3. Note how part of list appears, but you have to scroll down past where the bottom of the page was to see it.

**Expected behavior**
Rather than having the dropdown menu list appear below the button, this should appear above the button.

**Server (please complete the following information):**
 - Snipe-IT Version: **4.7.5**.
 - OS: **CentOS 7.5** host running Docker.

**Desktop (please complete the following information):**
 - OS: macOS 10.12.6
 - Browser Chrome
 - Version 75.0.3770.142

**Comment by apizz** [comment]
Yes, still relevant

**Comment by apizz** [comment]
Yes

**Comment by apizz** [comment]
Yes

**Comment by apizz** [comment]
yes

**Comment by apizz** [comment]
Yes

**Comment by apizz** [comment]
Yes

**Comment by apizz** [comment]
yes

**Comment by snipe** [comment]
I think this was fixed a long time ago.
