### ISSUE TITLE
A problem was encountered importing the CSV file

### ISSUE THREAD

**Issue by FrankyLampard** [snipe/snipe-it#7302]
#### Expected Behavior (or desired behavior if a feature request)
I edited the required information into a CSV file which is downloaded on the web via export "CSV" button.The editing software used is EXCEL.Then I import the CSV file into the web.

(what you expect to happen goes here)
Import successfully
-----

#### Actual Behavior

(what actually happens goes here)
Import failed
-----

#### Please confirm you have done the following before posting your bug report:

- [ NO] I have enabled debug mode (I don't know how to enabled this option)
- [ YES] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? No
- Version of Snipe-IT you're running   4.7.5
- Version of PHP you're running   7.1.3
- Version of MySQL/MariaDB you're running  mariaDB 5.5.6
- What OS and web server you're running Snipe-IT on CENTOS 7
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error 
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error     Import page,select import file.
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. Nothing
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. No
- Include any additional information you can find in `storage/logs` and your webserver's logs.No relevant information
- Include what you've done so far in the installation, and if you got any error messages along the way.No
- Indicate whether or not you've manually edited any data directly in the database.Not yet, but U want to know the table structure relationships in the database if there is no way to import csv file successfully.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
We'll need a little more info to go on here.... "Import failed" isn't that useful. Are you sure your column names match the ones specified in the sample CSV here: https://snipe-it.readme.io/docs/importing

(Exporting from the UI still requires header changes, since the headers are not always the same.)

**Comment by FrankyLampard** [comment]
I am now able to import the CSV file successfully, but it will get stuck in the import process, as shown in the figure.
![image](https://user-images.githubusercontent.com/49389073/62027423-41858100-b210-11e9-9986-5f5a970d5b93.png)

**Comment by jaymaan07** [comment]
Try this https://github.com/snipe/snipe-it/issues/7322#issuecomment-517556498

**Comment by FrankyLampard** [comment]
No,thanks,I set the import file with description of the database.&nbsp;



---Original---
