### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by jmartins1** [snipe/snipe-it#7308]
Not sure if this is an issue. 

I updated SnipeIT this morning from v4.7.5 build 4118 (master) to v4.7.6.

However, after the update my version footer says v4.7.5 build 4137 (master) 

Is this correct or is there an issue?

![2019-07-29_10-30-00](https://user-images.githubusercontent.com/31219479/62065271-41778800-b1f4-11e9-938a-57e8d81ab034.jpg)

**Comment by snipe** [comment]
Seems to be correct in the version file. Perhaps try clearing your config cache:
https://github.com/snipe/snipe-it/commit/c7be25078ead860f387cbcff0564927dd5b10dc8#diff-971490f6c5113b833bb3ffb69827ac93

`php artisan config:clear` or `php artisan config:cache`

**Comment by jmartins1** [comment]
Just an FYI, running the provided commands to clear the config cache did not resolve the issue. SnipeIT however, seems to be working fine.

 

Joe
