### ISSUE TITLE
installing on wamp- file editing

### ISSUE THREAD

**Issue by Ezmeyers** [snipe/snipe-it#731]
Hello, I am following the steps for installing on wamp listed at https://github.com/snipe/snipe-it/issues/169 but I am stuck at #7. How do I "edit the files as per https://github.com/snipe/snipe-it#2-setup-environment-database-and-mail-settings" The link doesn't take me to any instructions for this step. Thank you!

**Comment by snipe** [comment]
Please see the WAMP installation guide: http://snipeitapp.com/documentation/installing-on-wamp/
