### ISSUE TITLE
Error After update snipe-it ver: 4.7.6

### ISSUE THREAD

**Issue by vpardeshi** [snipe/snipe-it#7310]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  - No
- Version of Snipe-IT you're running - 4.7.0
- Version of PHP you're running .- 7.0
- Version of MySQL/MariaDB you're running
- What OS and web server you're running Snipe-IT on -Ubuntu 16.0.4 & Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - php upgrade.php
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error -no
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.- Webpage cannot be displayed
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation and if you got any error messages along the way. - did get any error. Installation was Successful
- Indicate whether or not you've manually edited any data directly in the database -NO

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by vpardeshi** [comment]
[snipe-logfile.txt](https://github.com/snipe/snipe-it/files/3445316/snipe-logfile.txt)

**Comment by douglasac10** [comment]
If you're running PHP 7.0, you will need to upgrade to at least 7.1.3, [as per the release notes](https://github.com/snipe/snipe-it/releases/tag/v4.7.5).

**Comment by vpardeshi** [comment]
![php update](https://user-images.githubusercontent.com/46221977/62455459-ff21ee00-b793-11e9-9e89-089b1e5da593.jpg)

**Comment by vpardeshi** [comment]
already update php
 Still facing issue

**Comment by snipe** [comment]
That's only a partial log file, so I don't know what the issue is.

Also please confirm that the web server (not just the command line) is running PHP 7.1.x or higher.
