### ISSUE TITLE
No Matching records found

### ISSUE THREAD

**Issue by syaoran68** [snipe/snipe-it#7311]
#### Expected Behavior (or desired behavior if a feature request)

expecting the dashboard to show all our assets and the items in our inventory.

-----

#### Actual Behavior

nothing actually shows up. only thing that shows up is a 'no matching records found' like we're trying to search for something but nothing is in the search bar or anything.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
neither it just started happening

- Version of Snipe-IT you're running
Version v4.7.6 - build 4143 (master)

- Version of PHP you're running
php 7.3

- Version of MySQL/MariaDB you're running
mariadb 10.2

- What OS and web server you're running Snipe-IT on
ubuntu 16.03 / apache 2

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
install.sh method ( honestly not really sure previous admin created this install / but there is an install.sh in the folder)

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
debug mode is on and is throwing an error  ' ReflectionException: Class Barryvdh\Cors\Handle\Cors does exist in /web/snipe-it/vendor/laravel/framework/src/Illuminate/Container/Container.php:752

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
this issue happens on all pages dashboard, searching, people, etc etc

- If a stacktrace is provided in the error, include that too.
included in the screenshot
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
doesn't look like it

- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.

cleared all the standard cache in artisan and composer in the log all i see are permissions issues

- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

<img width="1726" alt="Screen Shot 2019-07-29 at 11 24 48 PM" src="https://user-images.githubusercontent.com/43255653/62105755-2c344500-b258-11e9-821f-446c89d50f4e.png">
<img width="1657" alt="Screen Shot 2019-07-29 at 11 09 46 PM" src="https://user-images.githubusercontent.com/43255653/62105765-33f3e980-b258-11e9-84d4-0c487107f3d8.png">

**Comment by syaoran68** [comment]
any updates on this?

**Comment by snipe** [comment]
Did you run composer install?

**Comment by syaoran68** [comment]
i just tried to run the composer install. looks like there is a php 7.3 issue where composer has a break issue. its an errorexception stating "continue" targeting switch is equivalent to "break".  did you mean to use "continue 2". would it just be easier to downgrade to php 7.2? or do you guys have a simple fix for this composer issue. 

Thanks!

**Comment by snipe** [comment]
> i just tried to run the composer install. looks like there is a php 7.3 issue where composer has a break issue

That's not true - we run 7.3 on customer servers all the time. 

Can you tell me the specific error message you're seeing on composer install?
