### ISSUE TITLE
Whoops, something went wrong

### ISSUE THREAD

**Issue by davoezzz** [snipe/snipe-it#7314]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 6.7.5
 - OS: [e.g. Ubuntu, CentOS] Windows
 - Web Server: [e.g. Apache, IIS] IIS
 - PHP Version 7.0.33

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome, IE 11
 - Version [e.g. 22] newest

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.

(1/1) FatalThrowableErrorParse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)
--
in PDOConnection.php line 24
at Composer\Autoload\includeFile('C:\\inetpub\\wwwroot\\snipe-it\\vendor\\composer/../doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php')in ClassLoader.php line 322
at ClassLoader->loadClass('Doctrine\\DBAL\\Driver\\PDOConnection')
at spl_autoload_call('Doctrine\\DBAL\\Driver\\PDOConnection')
at class_exists('Doctrine\\DBAL\\Driver\\PDOConnection')in Connector.php line 63
at Connector->createPdoConnection('mysql:host=127.0.0.1;port=3306;dbname=snipeit', 'snipeit', '', array(0, 2, 0, false, false))in Connector.php line 43
at Connector->createConnection('mysql:host=127.0.0.1;port=3306;dbname=snipeit', array('driver' => 'mysql', 'host' => '127.0.0.1', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipeit', 'password' => '', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => 'InnoDB', 'unix_socket' => '', 'dump' => array('dump_binary_path' => 'C:\\PROGRA~1\\MARIAD~1.0\\bin', 'use_single_transaction', 'timeout' => 300), 'options' =>array(), 'name' => 'mysql'), array(0, 2, 0, false, false))in MySqlConnector.php line 24
at MySqlConnector->connect(array('driver' => 'mysql', 'host' => '127.0.0.1', 'port' => '3306', 'database' => 'snipeit', 'username' => 'snipeit', 'password' => '', 'charset' => 'utf8mb4', 'collation' => 'utf8mb4_unicode_ci', 'prefix' => '', 'strict' => false, 'engine' => 'InnoDB', 'unix_socket' => '', 'dump' =>array('dump_binary_path' => 'C:\\PROGRA~1\\MARIAD~1.0\\bin', 'use_single_transaction', 'timeout' => 300), 'options' => array(), 'name' => 'mysql'))in ConnectionFactory.php line 183
at ConnectionFactory->Illuminate\Database\Connectors\{closure}()
at call_user_func(object(Closure))in Connection.php line 915
at Connection->getPdo()in Connection.php line 940
at Connection->getReadPdo()in Connection.php line 399
at Connection->getPdoForSelect(true)in Connection.php line 325
at Connection->Illuminate\Database\{closure}('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in Connection.php line 657
at Connection->runQueryCallback('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'),object(Closure))in Connection.php line 624
at Connection->run('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'), object(Closure))in Connection.php line 333
at Connection->select('select * from information_schema.tables where table_schema = ? and table_name = ?', array('snipeit', 'users'))in MySqlBuilder.php line 18
at MySqlBuilder->hasTable('users')in Facade.php line 221
at Facade::__callStatic('hasTable', array('users'))in Setting.php line 68
at Setting::setupCompleted()in CheckForSetup.php line 22
at CheckForSetup->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in TrustProxies.php line 57
at TrustProxies->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in NosniffGuard.php line 17
at NosniffGuard->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ContentSecurityPolicyHeader.php line 18
at ContentSecurityPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ReferrerPolicyHeader.php line 17
at ReferrerPolicyHeader->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in XssProtectHeader.php line 18
at XssProtectHeader->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in FrameGuard.php line 17
at FrameGuard->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in ShareErrorsFromSession.php line 49
at ShareErrorsFromSession->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in StartSession.php line 63
at StartSession->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in CheckForMaintenanceMode.php line 46
at CheckForMaintenanceMode->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in HandlePreflight.php line 29
at HandlePreflight->handle(object(Request), object(Closure))in Pipeline.php line 149
at Pipeline->Illuminate\Pipeline\{closure}(object(Request))in Pipeline.php line 53
at Pipeline->Illuminate\Routing\{closure}(object(Request))in Pipeline.php line 102
at Pipeline->then(object(Closure))in Kernel.php line 151
at Kernel->sendRequestThroughRouter(object(Request))in Kernel.php line 116
at Kernel->handle(object(Request))in index.php line 58

**Additional context**
- Is this a fresh install or an upgrade? upgrade changed from manual to git install
- What OS and web server you're running Snipe-IT on: Windows Server 2016
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Git
- Include what you've done so far in the installation, and if you got any error messages along the way. Change to newer PHP version. Extensions installed. 
- Indicate whether or not you've manually edited any data directly in the database NOT

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
There is no Snipe-IT version 6.7.5, so I'm not sure what you're actually installing here, but that's a PHP version issue. Upgrade to 7.1.3 or higher.
