### ISSUE TITLE
How do you install this program?

### ISSUE THREAD

**Issue by wes228** [snipe/snipe-it#732]
This program looks to be exactly what our office needs! I just cannot for the life of me figure out how to install it. I've never used github before...I'm not understanding any of this!

**Comment by snipe** [comment]
Hi @wes228 - this is web-based software, so you'll need access to a computer somewhere that has a web server installed on it. 

Go to https://github.com/snipe/snipe-it/releases/latest to download the latest release. Then go to http://snipeitapp.com/documentation/ and select the installation guide for whichever operating system you plan on installing Snipe-IT on.

**Comment by wes228** [comment]
Thanks...I think I'll have to get ITS to do this. I tried the demo, it looks great!

**Comment by snipe** [comment]
:) Tell them to let us know if they need any help.
