### ISSUE TITLE
Composer Package phpunit/phpunit-mock-objects

### ISSUE THREAD

**Issue by jaymaan07** [snipe/snipe-it#7320]
#### Please confirm you have done the following before posting your bug report:

- [ It does not require to enable debug mode in this case] I have enabled debug mode 
- [Yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When I install Composer on Windows Server 2019 through command line by following Snipe-IT documentation, I see this message when Composer finished installing dependencies and packages. **It prints on the command prompt "Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested."**

**To Reproduce**
1. I tried upgrading composer and it shows the same message

**Expected behavior**
I have installed Composer for SNIPE-IT before multiple times earlier this year and never have seen this. 

**Screenshots**
![image](https://user-images.githubusercontent.com/51443175/62273519-13f33e80-b481-11e9-9439-b4d4118d53c8.png)

**Server (please complete the following information):**
 - Snipe-IT Version 4.7.6
 - OS: Windows Server 2019
 - Web Server: IIS
 - PHP Version 7.3.7

**Desktop (please complete the following information):**
 - OS: Windows 10 (Not applicable)
 - Browser [Not Applicable]
 - Version [Not Applicable]

**Smartphone (please complete the following information):**
 - Device: [Not Applicable]
 - OS: [Not Applicable]
 - Browser [Not Applicable]
 - Version [Not Applicable]

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Not Applicable

**Additional context**
- Is this a fresh install or an upgrade? Yes
- What OS and web server you're running Snipe-IT on (Windows Server 2019 and IIS Web Server)
- What method you used to install Snipe-IT (Manual)
- Include what you've done so far in the installation, and if you got any error messages along the way. (Error message already mentioned)
- Indicate whether or not you've manually edited any data directly in the database (No)

**All I wanted to know that whether the above message will impact any functionality of Snipe-IT?**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by snipe** [comment]
It's not erroring, so it's a non-issue at this time.
