### ISSUE TITLE
Add documentation / note for running on Kubernetes

### ISSUE THREAD

**Issue by mschmidt291** [snipe/snipe-it#7321]
Hi,

I've created a Kubernetes Helm Chart for Snipe-IT which we're using in Production for quite some time now and I think it would be great, if this would be noted or mentioned in documentation or installation docs

Is there an interest in this? 
https://github.com/t3n/helm-charts/tree/master/snipeit

There is also a great overview available on: https://hub.helm.sh/charts/t3n/snipeit

**Comment by sguruswa** [comment]
Hi, am running into below issue...can you please help to fix this issue

NAME                                        READY   STATUS             RESTARTS   AGE
pod/nspl-snipeit-1-5fff46f845-blsg2         0/1     CrashLoopBackOff   27         79m
pod/nspl-snipeit-1-mysql-74b9cc7cd-phtq9    1/1     Running            0          79m

km1@km1:~$ kubectl -n ame describe pod/nspl-snipeit-1-5fff46f845-blsg2
Name:         nspl-snipeit-1-5fff46f845-blsg2
Namespace:    ame
Priority:     0
Node:         kn1/10.217.11.201
Start Time:   Sat, 17 Apr 2021 06:26:01 +0000
Labels:       app.kubernetes.io/instance=nspl-snipeit-1
              app.kubernetes.io/name=snipeit
              pod-template-hash=5fff46f845
Annotations:  checksum/secret: 9a3562d5d38b139720c8f51e4fb431d2c38adcef141c69ad0a46399313814408
Status:       Running
IP:           10.32.0.3
IPs:
  IP:           10.32.0.3
Controlled By:  ReplicaSet/nspl-snipeit-1-5fff46f845
Init Containers:
  config-data:
    Container ID:  docker://8639c7d5de5d883e0e6f37a0c334405ce13777cf8939af9d7a7b0b9ec97856c3
    Image:         busybox
    Image ID:      docker-pullable://busybox@sha256:ae39a6f5c07297d7ab64dbd4f82c77c874cc6a94cea29fdec309d0992574b4f7
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      find
      /var/www/html/storage/framework/sessions
      -not
      -user
      1000
      -exec
      chown 1000 {} \+
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 17 Apr 2021 06:26:04 +0000
      Finished:     Sat, 17 Apr 2021 06:26:05 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-h8dn5 (ro)
      /var/www/html/storage/framework/sessions from data (rw,path="sessions")
Containers:
  nspl-snipeit-1:
    Container ID:   docker://855a7a2ddf08aad497884425b3a496b9bf68d51bceaeca4a557f1ca33d35e697
    Image:          snipe/snipe-it:v5.1.3
    Image ID:       docker-pullable://snipe/snipe-it@sha256:00ad754cd793855b073677ec9348fe39894fca8bc77fbd8e6f0db03df19a006c
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 17 Apr 2021 07:53:50 +0000
      Finished:     Sat, 17 Apr 2021 07:54:35 +0000
    Ready:          False
    Restart Count:  31
    Liveness:       http-get http://:80/health delay=0s timeout=3s period=15s #success=1 #failure=3
    Readiness:      http-get http://:80/health delay=0s timeout=3s period=15s #success=1 #failure=3
    Environment Variables from:
      nspl-snipeit-1  Secret  Optional: false
    Environment:
      APP_ENV:       production
      APP_DEBUG:     false
      APP_URL:       http://example.local
      APP_TIMEZONE:  Europe/Berlin
      APP_LOCALE:    en
    Mounts:
      /var/lib/snipeit from data (rw,path="www")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-h8dn5 (ro)
      /var/www/html/storage/framework/sessions from data (rw,path="sessions")
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  kube-api-access-h8dn5:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From     Message
  ----     ------     ----                   ----     -------
  Warning  Unhealthy  37m (x62 over 91m)     kubelet  Liveness probe failed: Get "http://10.32.0.3:80/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy  17m (x82 over 91m)     kubelet  Readiness probe failed: Get "http://10.32.0.3:80/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  BackOff    2m13s (x319 over 87m)  kubelet  Back-off restarting failed container
km1@km1:~$
