### ISSUE TITLE
Importing CSV Stuck on Processing

### ISSUE THREAD

**Issue by kacicohn** [snipe/snipe-it#7322]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
**When trying to import a CSV file (both for users and assets), the process never finishes.  The document successfully imports, but then after you select import type and match header fields with import fields and select Import, the process never finishes. It's stuck on "Processing" indefinitely.  I've confirmed that the CSV file is using commas (not another character.)**

**Expected behavior**
**The import finishes processing.**

**Screenshots**
![Snipe It Import Screenshot](https://user-images.githubusercontent.com/52209577/62303257-c8716e00-b449-11e9-8d38-fbf091e8f7c7.PNG)

**Server (please complete the following information):**
Snipe-IT version | v4.7.6 build 4143 (g3dc2cc9f2)
Software License | AGPL3
PHP Version | 7.1.30-1+ubuntu16.04.1+deb.sury.org+1
Laravel Version | 5.5.45

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] **Windows 10**
 - Browser [e.g. chrome, safari]: **Chrome**

**Comment by jaymaan07** [comment]
I would recommend you to try the following if you have not tried that already:

1. Turn on the debug mode (from .env file), so you will see errors if there is any
2. [ Download the sample csv](https://snipe-it.readme.io/docs/importing)> delete most of the records and keep only one for testing > test with one record > if this works, it means there is something wrong with your csv file
3. If sample import does not work through GUI, try using shell for import. Here is the documentation https://snipe-it.readme.io/docs/importing

**Comment by jaymaan07** [comment]
I figured out the solution. It never happened to me in the previous versions of Snipe I used. 
Simple solution:

- Update the SMTP mail settings in .env file
- Send a test email from Admin Page (www.yoursnipe.com/admin)> General Settings (make sure SMTP mail settings are fully functional)
- Try Import or Purge (Even purge option does not work with default SMTP settings)

**Importing through Shell works as supposed it to be with the default SMTP settings.**

**Comment by Tomik2245** [comment]
Thanks that was it, 
MAIL_DRIVER=log should fix it temporarily if you don't use mails

**Comment by arkeyme** [comment]
Hey, did you fix this issue?
I set up mail settings to correct and now see an "Error" message instead of "Processing..." one.
I explained what happens in https://github.com/snipe/snipe-it/issues/7347 thread. 

If you don't mind, can you please share your .csv file which imported correctly on your system?
I will try to guess the difference with mine.

**Comment by jaymaan07** [comment]
Hi 

> Hey, did you fix this issue?
> I set up mail settings to correct and now see an "Error" message instead of "Processing..." one.
> I explained what happens in #7347 thread.
> 
> If you don't mind, can you please share your .csv file which imported correctly on your system?
> I will try to guess the difference with mine one.

You can download file from this blog post https://blog.teknex.com.au/snipe-it/snipe-it-file-import-stuck-on-processing/.

**Comment by arkeyme** [comment]
Hey, I just have downloaded your  Assets Sample file, and looks like it uses Tab separation between columns instead of ',' which are correct according to the official documentation. For example: https://snipeitapp.com/assets/downloads/sample-assets.csv 

When I try to import your file I see this:

![image](https://user-images.githubusercontent.com/5687846/63003589-26a64400-be81-11e9-801c-206cdb34cd5c.png)

I can't understand how you able to import your file? Maybe, it because you use Windows system as host?

Also, I have done all the steps, you mentioned in your article, and it doesn't help, with the same result. I also clean cache files by using this command:

```
php artisan config:clear
php artisan config:cache
```

**Comment by arkeyme** [comment]
Also, I able to import my file via command line, @jaymaan07, please check my comment here https://github.com/snipe/snipe-it/issues/7347#issuecomment-521146460

**Comment by jaymaan07** [comment]
I can try on Ubuntu if you like. I have a test VM configured.

Kind Regards,

Jay Singh

Sent from my iPhone

On 14 Aug 2019, at 6:11 pm, arkeyme <notifications@github.com<mailto:notifications@github.com>> wrote:


Also, I able to import my file via command line, @jaymaan07<https://github.com/jaymaan07>, please check my comment here #7347 (comment)<https://github.com/snipe/snipe-it/issues/7347#issuecomment-521146460>

**Comment by jaymaan07** [comment]
> Finally, I able to import my file via command line, @jaymaan07, please check my comment here [#7347 (comment)](https://github.com/snipe/snipe-it/issues/7347#issuecomment-521146460)

I have updated that file on the [blog](https://blog.teknex.com.au/snipe-it/snipe-it-file-import-stuck-on-processing/). I am not sure what went wrong with that file previously. I created a new one with the same name. You would be able to download that file now and test it. I have used on Ubuntu/Apache Server and it works.
Jay

**Comment by arkeyme** [comment]
Unfortunately, I have the same issue with your file as well. Seems some misconfiguration in my system, but how find which one?

**Comment by arkeyme** [comment]
Could you, please, validate the .env config? Mail settings work perfectly, and also backups work as they should.

And can I ask you to show me your folder/file access rights in public/uploads on Linux filesystem? If you don't mind of course.
```
root@SERVERNAME:/var/www/snipeit# cat .env
#Created By Snipe-it Installer
# --------------------------------------------
# REQUIRED: BASIC APP SETTINGS
# --------------------------------------------
APP_ENV=production
APP_DEBUG=false
APP_KEY=base64:?????????????????????????????
APP_URL=http://inventory.DOMAIN.com
APP_TIMEZONE=Etc/UTC
APP_LOCALE=en

# --------------------------------------------
# REQUIRED: DATABASE SETTINGS
# --------------------------------------------
DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=snipeit
DB_USERNAME=snipeit
DB_PASSWORD=?????????????
DB_PREFIX=null
DB_DUMP_PATH='/usr/bin'
DB_CHARSET=utf8mb4
DB_COLLATION=utf8mb4_unicode_ci

# --------------------------------------------
# OPTIONAL: SSL DATABASE SETTINGS
# --------------------------------------------
DB_SSL=false
DB_SSL_KEY_PATH=null
DB_SSL_CERT_PATH=null
DB_SSL_CA_PATH=null
DB_SSL_CIPHER=null

# --------------------------------------------
# REQUIRED: OUTGOING MAIL SERVER SETTINGS
# --------------------------------------------
MAIL_DRIVER=log
MAIL_HOST=HOSTNAME.ad.DOMAIN.com
MAIL_PORT=25
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=null
MAIL_FROM_ADDR=snipeit@DOMAIN.com
MAIL_FROM_NAME=snipeit
MAIL_REPLYTO_ADDR=My.Name@DOMAIN.com
MAIL_REPLYTO_NAME=MyName
MAIL_BACKUP_NOTIFICATION_ADDRESS=My.Name@DOMAIN.com

# --------------------------------------------
# REQUIRED: IMAGE LIBRARY
# This should be gd or imagick
# --------------------------------------------
#IMAGE_LIB=gd
#
IMAGE_LIB=imagick

# --------------------------------------------
# OPTIONAL: SESSION SETTINGS
# --------------------------------------------
SESSION_LIFETIME=12000
EXPIRE_ON_CLOSE=false
ENCRYPT=false
COOKIE_NAME=snipeit_session
COOKIE_DOMAIN=null
SECURE_COOKIES=false

# --------------------------------------------
# OPTIONAL: SECURITY HEADER SETTINGS
# --------------------------------------------
REFERRER_POLICY=same-origin
ENABLE_CSP=false
CORS_ALLOWED_ORIGINS=null

# --------------------------------------------
# OPTIONAL: CACHE SETTINGS
# --------------------------------------------
CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync
CACHE_PREFIX=snipeit

# --------------------------------------------
# OPTIONAL: REDIS SETTINGS
# --------------------------------------------
REDIS_HOST=null
REDIS_PASSWORD=null
REDIS_PORT=null

# --------------------------------------------
# OPTIONAL: MEMCACHED SETTINGS
# --------------------------------------------
MEMCACHED_HOST=null
MEMCACHED_PORT=null

# --------------------------------------------
# OPTIONAL: AWS S3 SETTINGS
# --------------------------------------------
AWS_SECRET=null
AWS_KEY=null
AWS_REGION=null
AWS_BUCKET=null

# --------------------------------------------
# OPTIONAL: LOGIN THROTTLING
# --------------------------------------------
LOGIN_MAX_ATTEMPTS=5
LOGIN_LOCKOUT_DURATION=60

# --------------------------------------------
# OPTIONAL: MISC
# --------------------------------------------
APP_LOG=single
APP_LOG_MAX_FILES=10
APP_LOCKED=false
FILESYSTEM_DISK=local
APP_TRUSTED_PROXIES=192.168.1.1,10.0.0.1
ALLOW_IFRAMING=false
APP_CIPHER=AES-256-CBC
GOOGLE_MAPS_API=
BACKUP_ENV=true

```

**Comment by jaymaan07** [comment]
> Could you, please, validate the .env config? Mail settings work perfectly, and also backups work as they should.
> 
> And can I ask you to show me your folder/file access rights in public/uploads on Linux filesystem? If you don't mind of course.
> 
> ```
> root@SERVERNAME:/var/www/snipeit# cat .env
> #Created By Snipe-it Installer
> # --------------------------------------------
> # REQUIRED: BASIC APP SETTINGS
> # --------------------------------------------
> APP_ENV=production
> APP_DEBUG=false
> APP_KEY=base64:?????????????????????????????
> APP_URL=http://inventory.DOMAIN.com
> APP_TIMEZONE=Etc/UTC
> APP_LOCALE=en
> 
> # --------------------------------------------
> # REQUIRED: DATABASE SETTINGS
> # --------------------------------------------
> DB_CONNECTION=mysql
> DB_HOST=localhost
> DB_DATABASE=snipeit
> DB_USERNAME=snipeit
> DB_PASSWORD=?????????????
> DB_PREFIX=null
> DB_DUMP_PATH='/usr/bin'
> DB_CHARSET=utf8mb4
> DB_COLLATION=utf8mb4_unicode_ci
> 
> # --------------------------------------------
> # OPTIONAL: SSL DATABASE SETTINGS
> # --------------------------------------------
> DB_SSL=false
> DB_SSL_KEY_PATH=null
> DB_SSL_CERT_PATH=null
> DB_SSL_CA_PATH=null
> DB_SSL_CIPHER=null
> 
> # --------------------------------------------
> # REQUIRED: OUTGOING MAIL SERVER SETTINGS
> # --------------------------------------------
> MAIL_DRIVER=log
> MAIL_HOST=HOSTNAME.ad.DOMAIN.com
> MAIL_PORT=25
> MAIL_USERNAME=
> MAIL_PASSWORD=
> MAIL_ENCRYPTION=null
> MAIL_FROM_ADDR=snipeit@DOMAIN.com
> MAIL_FROM_NAME=snipeit
> MAIL_REPLYTO_ADDR=My.Name@DOMAIN.com
> MAIL_REPLYTO_NAME=MyName
> MAIL_BACKUP_NOTIFICATION_ADDRESS=My.Name@DOMAIN.com
> 
> # --------------------------------------------
> # REQUIRED: IMAGE LIBRARY
> # This should be gd or imagick
> # --------------------------------------------
> #IMAGE_LIB=gd
> #
> IMAGE_LIB=imagick
> 
> # --------------------------------------------
> # OPTIONAL: SESSION SETTINGS
> # --------------------------------------------
> SESSION_LIFETIME=12000
> EXPIRE_ON_CLOSE=false
> ENCRYPT=false
> COOKIE_NAME=snipeit_session
> COOKIE_DOMAIN=null
> SECURE_COOKIES=false
> 
> # --------------------------------------------
> # OPTIONAL: SECURITY HEADER SETTINGS
> # --------------------------------------------
> REFERRER_POLICY=same-origin
> ENABLE_CSP=false
> CORS_ALLOWED_ORIGINS=null
> 
> # --------------------------------------------
> # OPTIONAL: CACHE SETTINGS
> # --------------------------------------------
> CACHE_DRIVER=file
> SESSION_DRIVER=file
> QUEUE_DRIVER=sync
> CACHE_PREFIX=snipeit
> 
> # --------------------------------------------
> # OPTIONAL: REDIS SETTINGS
> # --------------------------------------------
> REDIS_HOST=null
> REDIS_PASSWORD=null
> REDIS_PORT=null
> 
> # --------------------------------------------
> # OPTIONAL: MEMCACHED SETTINGS
> # --------------------------------------------
> MEMCACHED_HOST=null
> MEMCACHED_PORT=null
> 
> # --------------------------------------------
> # OPTIONAL: AWS S3 SETTINGS
> # --------------------------------------------
> AWS_SECRET=null
> AWS_KEY=null
> AWS_REGION=null
> AWS_BUCKET=null
> 
> # --------------------------------------------
> # OPTIONAL: LOGIN THROTTLING
> # --------------------------------------------
> LOGIN_MAX_ATTEMPTS=5
> LOGIN_LOCKOUT_DURATION=60
> 
> # --------------------------------------------
> # OPTIONAL: MISC
> # --------------------------------------------
> APP_LOG=single
> APP_LOG_MAX_FILES=10
> APP_LOCKED=false
> FILESYSTEM_DISK=local
> APP_TRUSTED_PROXIES=192.168.1.1,10.0.0.1
> ALLOW_IFRAMING=false
> APP_CIPHER=AES-256-CBC
> GOOGLE_MAPS_API=
> BACKUP_ENV=true
> ```

Environment file looks alright.

Have a look at my [LinkedIn article](https://www.linkedin.com/pulse/snipe-it-configuration-ubuntu-jay-singh/) to check out the folder permissions. I will add this article on my blog down the line.

**Comment by arkeyme** [comment]
Now I see in debug log:

[11:49:10] LOG.debug: [INVALID UTF-8 DATA]

The same file imported successfully from command line.
