### ISSUE TITLE
Remove user and assets assigned to them

### ISSUE THREAD

**Issue by dphelpsBrownco** [snipe/snipe-it#7324]
#### Expected Behavior (or desired behavior if a feature request)

Is there a way to remove users and the assets they have checked out?  We assign devices to students and all of the graduates devices are being retired from the fleet.  Even if I could pull all devices checked out against a list of users, that would be helpful.

-----

**Comment by snipe** [comment]
You can use the Bulk Checkin and Delete option from the user listing page: 
<img width="496" alt="Screen Shot 2019-08-15 at 1 12 04 AM" src="https://user-images.githubusercontent.com/197404/63081936-c56e8700-bef9-11e9-9f3d-ecfd19e5e6a6.png">

Or the Checkin and Delete option from the user's page:

<img width="227" alt="Screen Shot 2019-08-15 at 1 12 25 AM" src="https://user-images.githubusercontent.com/197404/63081937-c6071d80-bef9-11e9-8c36-3fff79af877d.png">
