### ISSUE TITLE
Legacy-recrypter fails with cipher issue

### ISSUE THREAD

**Issue by scortoise** [snipe/snipe-it#7325]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After upgrading from v3 to v4 successfully, I am unable to use the legacy-recrypter to migrate encrypted custom fields to OpenSSL. .env contains the LEGACY_APP_KEY and the LEGACY_CIPHER config, but whenever the php artisan snipeit:legacy-recrypt command is run, I receive an error that the only supported ciphers are MCRYPT_RIJNDAEL_128 and MCRYPT_RIJNDAEL_256.

**To Reproduce**
1. Upgrade from v3.6.6 to v4.7.4 build 4107 with encrypted fields in use. 
2. Copy legacy app key and cipher from backed up app.config to new .env file. 
3. After dumping cache and config, run "php artisan snipeit:legacy-recrypt" as web user (www-data in my case). 

**Expected behavior**
Encrypted custom fields should be decrypted via MCrypt/rijndael-256 and re-encrypted with OpenSSL. 

**Screenshots**
![recrypt_error](https://user-images.githubusercontent.com/52414922/62379540-261ebc80-b515-11e9-9c8b-860b0dd85791.png)

**Server (please complete the following information):**
 - Snipe-IT Version - 4.7.4
 - OS: Debian 9 
 - Web Server: Apache2
 - PHP Version - 7.1.3

**Error Messages**
No browser errors, app loads and operates fine- but pre-upgrade custom encrypted fields are unreadable post-upgrade ("Error decrypting: The payload is invalid"). 

When the recrypter is run from shell:
In McryptEncrypter.php line 48:
                                                                               
  The only supported ciphers are MCRYPT_RIJNDAEL_128 and MCRYPT_RIJNDAEL_256.  
                                                                               
See screenshot for full error context.

**Additional context**
- Is this a fresh install or an upgrade? This is an upgrade from v3.6.6.
- What OS and web server you're running Snipe-IT on: Debian 9/Apache2. 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): install.sh. 
- Include what you've done so far in the installation, and if you got any error messages along the way: During the upgrade, I fixed the composer install (was installed as root) and upgraded from PHP5 to PHP 7.1, along with upgrading all of the associated PHP7.1 modules, before using Composer to update the app to v4.
- Indicate whether or not you've manually edited any data directly in the database- Database untouched.

If I create new assets and enter encrypted field data, they appear to work fine and are readable.

**Comment by chedabob** [comment]
For anyone else that is running into this issue on newer versions of PHP:

From PHP 7.1 the MCrypt extension is not installed by default.

I followed this guide https://computingforgeeks.com/install-php-mcrypt-extension-on-ubuntu/

The general gist of it is get Pecl installed, use it to install Mcrypt, and then enable the Mcrypt extension in your `php.ini` file.

<blockquote><div><strong><a href="https://computingforgeeks.com/install-php-mcrypt-extension-on-ubuntu/">Attention Required! | Cloudflare</a></strong></div></blockquote>
