### ISSUE TITLE
Support external warranty check APIs

### ISSUE THREAD

**Issue by benwa** [snipe/snipe-it#7326]
- Snipe-IT Version: 4.7.6
 - OS: Windows Server 2019
 - Web Server: IIS
 - PHP Version: 7.3.7

Sometimes warranties can change on an asset, or be unknown to a person inputting an asset at creation.

Many enterprise manufacturers offer the ability to check the warranty dates and levels based on an API query.  By supporting those APIs (and requiring each instance to supply their own key), this can greatly reduce the amount of manual work it is to update an asset.

This can be done externally, and then written to Snipe-IT via its API or via writing to the database.

Here's a list of manufacturer warranty APIs I've found:

- Dell: https://techdirect.dell.com/portal/AboutAPIs.aspx
- HP: https://developers.hp.com/hp-client-management/doc/device-warranty
- Lenovo: http://supportapi.lenovo.com/Documentation/Index.html
- Cisco: https://developer.cisco.com/docs/support-apis/#!serial-number-to-information/cisco-serial-number-to-information-api-reference

**Comment by benwa** [comment]
This is still relevant

**Comment by Laim** [comment]
Agreed.  We've been looking for an asset tool that has the ability to pull warranty information without costing an arm and a leg, this would be a massive advantage for me pushing for Snipe-IT internally.

**Comment by chelming** [comment]
This is still relevant

**Comment by JohnBlunden** [comment]
I would love this as a feature as well.

**Comment by benwa** [comment]
This is still relevant

**Comment by 54656452** [comment]
This would be incredibly useful if implemented.

**Comment by rovingrambler** [comment]
Related issue. We would really like to push asset status to an API and ideally updating snipe it with a confirmation. The logic of this seems very similar to what has been requested here.

Especially if you kept it vague and simply provide a box or execute all in a directory where we could put our scripts. We could then write an external push and internal one putting whatever results we are after where we want them.

Could be used for warranty status or anything else.

**Comment by benwa** [comment]
This is still relevant

**Comment by rovingrambler** [comment]
I've been working around it with other systems apis but absolutely still a crucial feature.

As mentioned previously I think an ability to send a json string would be more useful than warranty specific function. It could accomplish a warranty check and much more.

Apr 25, 2020 9:06:11 AM stale[bot] <notifications@github.com>:

**Comment by viclou** [comment]
+1 FD15527

**Comment by z3m0n** [comment]
Just to keep this thread from going stale again, we are definitely looking for this feature, also. I suppose we could script it the hard way, but built-in functionality would be a huge plus.

**Comment by mikey-m** [comment]
This would be incredibly useful if implemented. Perhaps a connection to warrantymaster.com may be appropriate.

**Comment by AMG-90** [comment]
there is anything like that ? 
anyone knows ?

**Comment by benwa** [comment]
Yup

**Comment by kristofkeppens** [comment]
+1 interested in this as well!

**Comment by aarnold-sd68** [comment]
This would be great to have, any progress on this?

**Comment by Ng-marelec** [comment]
+100 for this idea!

Maybe a good idea to have a look at how similar tools like GoGenuity have this built in?
We actually were researched GoGenuity before choosing SnipeIT for this reason, but SnipeIT has better overall features.

**Comment by WELLBOREIS** [comment]
+1

**Comment by TheZachAttack01** [comment]
+1 would love to have dell warranty info lookup based on serial number

**Comment by JKC1993** [comment]
+1 please do this!!!!

**Comment by TechTucson** [comment]
Interested as well.

**Comment by vaneess** [comment]
+1 Lenovo and Microsoft (Surface)
Lenovo has a working API, Microsoft probably not, you have to enter a captcha... 
https://mybusinessservice.surface.com/en-US/CheckWarranty/CheckWarranty

**Comment by allanPHD** [comment]
+1

**Comment by Rieski** [comment]
+1 This would be crucial

**Comment by JemTaylorUHI** [comment]
In the same vein, it would be incredibly useful to check for End of Manufacturer Support for the Model. This is important for cybersecurity compliance checking, and I have already asked for Custom Fields on Model just to be able to record EOS.  If we could just have the Manufacturer/Model combination just go look itself up for EOS that would be doubly incredibly awesome!

**Comment by d3m0nz** [comment]
Yes please

**Comment by Anatharias** [comment]
Two years this has been opened, and none has been done about this. any update ?

**Comment by snipe** [comment]
@Anatharias Obviously not, but we welcome your pull request.

**Comment by JustinGGoodwin** [comment]
This would be enormous for us.  Even bigger for Snipe-IT and would make them compete with the big boys like Solarwinds, etc.

**Comment by snipe** [comment]
We already do this for Apple devices. We’d need the URLS and expected parameters to be passed in order to generate them for other suppliers.

**Comment by JustinGGoodwin** [comment]
> We already do this for Apple devices. We’d need the URLS and expected parameters to be passed in order to generate them for other suppliers.

Let me know how I can help.  We buy from Dell currently.  I can get our rep involved as well.

**Comment by snipe** [comment]
I can't see this being a huge priority for us tbh, as it requires a lot of overhead to store individual API keys for each of these APIs, and also the ability to map the proprietary responses from their APIs, and means we have to add a lot of stuff to the codebase that many people will never use.

We could potentially add this as optional fields (API key, parameters) to the manufacturer (or supplier?) table, but parsing each one of these private API responses is a lot of code that's tied to commercial manufacturers, which we generally try to avoid, in the spirit of FOSS. We do provide a *link* to Apple's coverage checker, but it's just a link, not full API parsing.

**Comment by JustinGGoodwin** [comment]
Ok thanks.  We'll look into other solutions that are doing it currently.  Appreciate the feedback.

**Comment by mikey-m** [comment]
I see this as extraordinarily valuable feature. It will help report on replacement cycles and help leaders make decisions and forecast budgets more quickly and easily. Perhaps instead of individual API's - Use a central one such as Warranty Master, where all that individual work is already done. Food for thought.

**Comment by snipe** [comment]
Where exactly would that central API come from? These are disparate companies. Their API responses will be different, and subject to change.

**Comment by Rieski** [comment]
I also feel that is crucial to have at least Lenovo, Dell, HP and Apple to fetch warranty dates automatically.
Cannot do any kind of life cycle management without it.

**Comment by mikey-m** [comment]
Warranty Master is the only centralised product that dovetails all the commons vendors that I know of, simply an idea. 

Perhaps focus on Apple, HP, Dell, Lenovo only.

**Comment by snipe** [comment]
I'm not ruling it out, but it's unlikely we would build this in, TBH. These are hundreds of lines of code, payload parsing, testing, etc to handle a small percentage of users. (And we don't use those those brands, so we'd need to maintain API keys for testing, and so on.)

**Comment by vaneess** [comment]
we work with this script https://github.com/KelvinTegelaar/PowerShellWarrantyReports

i created a scheduled task, which runs every day. it connects to snipe via API (https://github.com/snazy2000/SnipeitPS)
and gets all devices which where created today, then starts the warranty lookup. it works for lenovo and some microsoft devices. apple doesn't work at the moment.


```PowerShell

import-module -Name SnipeITPS
import-module -Name PSWarranty
Connect-SnipeitPS -URL "url" -apikey "key"

#get date of today
$filterdate = (get-date).AddDays(-1)
$filterdate = get-date $filterdate -format "yyyy-MM-dd"


#get all assets from category "notebook"
$assets = Get-SnipeitAsset -category_id 2 -all | Where-Object {$_.created_at.datetime -gt $filterdate}

#loop trough each found asset
foreach ($notebook in $assets)
{
    #reset variables
    $warranty = $null
    $warrantytime = $null 
    $days = $null
    $manufacturer = $notebook.manufacturer

    switch ($manufacturer)
    {
        Microsoft {$vendor = "MS"}
        Lenovo {$vendor = "Lenovo"}
        Dell {$vendor = "Dell"}
        HP {$vendor = "HP"}
    
    }
    #get warranty of notebook
    $warranty = Get-Warrantyinfo -DeviceSerial $notebook.serial -vendor $vendor

    #if lookup was sucessfull set the information on the assset (check if warranty is 24 or 36 months)
    if($warranty.enddate)
    {
        #write-host $notebook.name $notebook.model.name $warranty.Serial $warranty.StartDate $warranty.EndDate -ForegroundColor Green
        $warrantytime = New-TimeSpan -start $warranty.StartDate -End $warranty.EndDate
        $days = $warrantytime.Days
                
        if($days -ge 366 -and $days -le 792)
        {
            Set-SnipeitAsset $notebook.id -purchase_date $warranty.StartDate -warranty_months 24 | out-null
        }
        elseif($days -gt 792)
        {
                Set-SnipeitAsset $notebook.id -purchase_date $warranty.StartDate -warranty_months 36 | out-null
        }
    }
       
    else
    {
        #write-host $notebook.name $notebook.model.name $warranty.Serial $warranty.StartDate $warranty.EndDate -ForegroundColor Yellow
    }         
    
}
```

<blockquote><img src="https://opengraph.githubassets.com/5d9b5ea25a5030f022b3c838d4fb069538e5ad0cf61a0e435752c1284c0cc3c1/KelvinTegelaar/PowerShellWarrantyReports" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/KelvinTegelaar/PowerShellWarrantyReports">GitHub - KelvinTegelaar/PowerShellWarrantyReports: a repo dedicated to automatic warranty reporting and retrieval from different systems such as IT-Glue, Connectwise, Autotask, and N-central.</a></strong></div><div>a repo dedicated to automatic warranty reporting and retrieval from different systems such as IT-Glue, Connectwise, Autotask, and N-central. - GitHub - KelvinTegelaar/PowerShellWarrantyReports: a r...</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/bbfb2ac4c190d6d365eff1b8e55fe3ff7b2768b7b7ad3ffd2b7eb3080a03aaf0/snazy2000/SnipeitPS" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/snazy2000/SnipeitPS">GitHub - snazy2000/SnipeitPS: Powershell API Wrapper for Snipe-it</a></strong></div><div>Powershell API Wrapper for Snipe-it. Contribute to snazy2000/SnipeitPS development by creating an account on GitHub.</div></blockquote>

**Comment by Anatharias** [comment]
> I'm not ruling it out, but it's unlikely we would build this in, TBH. (...) to handle a small percentage of users.

You created an inventory solution for IT reps, for them to track their assets, assets mostly composed of Lenovo, Dell, HP and Apple products. I find it hard to believe that only "a small percentage of users" would benefit from having the warranty information automatically fetched. While I do appreciate the extra work that would be required (and I'm no coder), for creating/maintaining the code that would query the warranty info from the different vendors through their respective APIs, don't think for a single second that it would only serve a small percentage of users.

> This would be incredibly useful if implemented.

> +1 would love to have dell warranty

> This would be enormous for us.

> I see this as extraordinarily valuable feature.

The broad opinion in this thread shows that not a single user would find the warranty information irrelevant.

Edit: I manually fetch my Dell warranty through an AppleScript and a pasted {clip}... time-consuming.
```
{/AppleScript
do shell script "open -a Safari 'https://www.dell.com/support/home/en-ca/product-support/servicetag/{clip}'"
}
```

**Comment by Rieski** [comment]
I think it would drive a lot more users if it would be implemented. When new users see that this feature is missing, they just start using something else.

We also update warranties with collection of scripts. Not really an elegant solution.

This plus missing native agents are imho weakest points that should be considered crucial.

**Comment by Ng-marelec** [comment]
> I think it would drive a lot more users if it would be implemented. When new users see that this feature is missing, they just start using something else. We also update warranties with collection of scripts. Not really an elegant solution. This plus missing native agents are imho weakest points that should be considered crucial.

Totally agree.
Also using a bunch of scripts etc.
Competitors like e.g. GoGenuity have implemented this for a couple of years now. When will Snipe-IT follow?
An Agent is also a must-have. Not all corp devices are constantly accessible over the corp network(s). Some float across the world, so a cloud connected agent is a necessity then. Or link it with existing solutions? Most End Point solutions have an agent, also RMM solutions like NinjaRMM, N-Able...

IMO, if the devteam at Snipe-it doesn't agree on this part, it is probably time to look for other solutions.

**Comment by davidebonavita** [comment]
+1!

**Comment by 6sto** [comment]
+1!!!!

**Comment by Naddox** [comment]
+1

**Comment by rr831** [comment]
Can this please be implemented?? This would make a massive difference for our organization. I created an account just to put my 2 cents in since the dev thinks that we are a small percentage of users.

**Comment by RCM-Chad** [comment]
I know that maintaining API keys would be difficult I would offer that just to have the ability I would not even mind if we had to have our own API key that was entered into the respective manufacturer lookup.  This would save us in our company so much time.

**Comment by snipe** [comment]
It's not the API keys, it's each of the bespoke integrations. This issue is closed for a reason.

**Comment by JustinGGoodwin** [comment]
> I know that maintaining API keys would be difficult I would offer that just to have the ability I would not even mind if we had to have our own API key that was entered into the respective manufacturer lookup. This would save us in our company so much time.

they no likey this question

Solarwinds ServiceDesk not only has an IT ticketing system but also a built in PC/laptop inventory.  It can detect all devices currently connected to a machine, who the machine is assigned to, the service history on it, and keeps track of warranty and lifecycle, so it can be done.  Attached  is the info on an out of date machine, straight from Dell.
![warranty](https://github.com/snipe/snipe-it/assets/115116597/5cf8b445-c67d-424b-bc9b-710c9a9c1e8e)

**Comment by mikey-m** [comment]
There is possibly a missed opportunity to us by not thinking out of the box further on this one.

We are so close to moving to a PSA/RMM because of this issue, our deep SnipeIT history and use is keeping us using the platform.

Hence the suggestions to use an existing API partner that does create all the connections, or pick the big 5 and only support those.

The PSA/RMM guys seem to be making waves in this asset management space; we’d be doing ourselves a favour to support this.
