### ISSUE TITLE
Create New API

### ISSUE THREAD

**Issue by Blu3W0LF** [snipe/snipe-it#7329]
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**
I want to make user login and registration as api

**Describe the solution you'd like**
Login and Registration API

**Describe alternatives you've considered**

**Additional context**

**Comment by snipe** [comment]
Login wouldn't be done via API, it would be done via the Bearer token that's passed to the API, since a server-side API doesn't support sessions that way. Registration would be done using the [Create User API endpoint](https://snipe-it.readme.io/reference#users-2).
