### ISSUE TITLE
Depreciation Report - Value and Diff swapped?

### ISSUE THREAD

**Issue by marker** [snipe/snipe-it#733]
Admittedly, this may be something gone wonky with my installation as I've just set this up and added assets and whatnot.  When I run a Depreciation Report, the values appear to be swapped around.  For example, here are the columns for a laptop purchased in March of 2015:

    Purchased    Cost     Value  Diff
    2015-03-25, $1,210, $303, $-907

I supposed it's not just a straight swap though, as a laptop purchased in Feb would be reporting a higher value than the March laptop:

    Purchased    Cost     Value   Diff
    2015-02-01, $1,210, $262,  $-948

I played around with a straight swap in depreciation.blade.php and got a more reasonable looking report, but I doubt the true fix is that easy.  Haven't gotten into the getDepreciatedValue function yet.

    --- depreciation.blade.php.org	2015-04-08 17:23:04.118037529 -0500
    +++ assets/app/views/backend/reports/depreciation.blade.php	2015-04-08 17:05:58.944690493 -0500
    @@ -89,9 +89,9 @@
                 <td class="align-right">@lang('general.currency')
                 	{{{ number_format($asset->purchase_cost) }}}</td>
                 <td class="align-right">@lang('general.currency')
    -            	{{{ number_format($asset->getDepreciatedValue()) }}}</td>
    +            	{{{ number_format(($asset->purchase_cost - $asset->getDepreciatedValue())) }}}</td>
                 <td class="align-right">@lang('general.currency')
    -            	-{{{ number_format(($asset->purchase_cost - $asset->getDepreciatedValue())) }}}</td>
    +            	-{{{ number_format($asset->getDepreciatedValue()) }}}</td>
                 @else
     	            <td></td>
     	            <td></td>

That got these results for the two example laptops:

    Purchased    Cost        Value   Diff
    2015-03-25, $ 1,210, 	$ 907,  $ -303
    2015-02-01, $ 1,210,   $ 948,  $ -262

... though still seems odd that the slightly older laptop would have a higher value/less change due to depreciation.

Is this a known issue or a screwed up installation on my end?

**Comment by uberbrady** [comment]
No, but the person who wrote it - me - is not known to be very bright and could've screwed it up.

**Comment by snipe** [comment]
@uberbrady I can reproduce this. :P

**Comment by uberbrady** [comment]
If they're both the same depreciation duration, the older one should have less 'value' than the newer one.

**Comment by uberbrady** [comment]
the ```getDepreciatedValue() ``` is in Depreciable.php, a model. Asset.php and License.php both inherit from it. I'm poking around to see if anything obvious is wrong.

If so, based on the method names, we should probably actually change the getDepreciatedValue() method to return the correct one and then edit the appropriate blades so they're calling the right thing.

If you think you have a handle on it, a pull request would be awesome! Barring that, I'll try to find out what I did wrong and fix it.

**Comment by uberbrady** [comment]
Yeah, I donked something up in there. Let me get this fixed for you, nice catch!

**Comment by uberbrady** [comment]
This seems closer to me.
![screen shot 2015-04-08 at 4 40 34 pm](https://cloud.githubusercontent.com/assets/36335/7057756/0c00a382-de0e-11e4-839e-a2f344a5bd10.png)

**Comment by marker** [comment]
Now that was some seriously quick turnaround.  File right before leaving work, get home and it's closed.  Thanks!

**Comment by snipe** [comment]
@marker bear in mind, this fix is on the develop branch, not in an official release yet. I don't know how adventurous you are. :)

**Comment by marker** [comment]
Ah, I looked at the diff (3 characters) and just made the change to my existing installation  : )
