### ISSUE TITLE
Some C128 Barcodes unreadable, some readable. 

### ISSUE THREAD

**Issue by arkeyme** [snipe/snipe-it#7331]
- [ Yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

Hi! After generating barcodes for my inventory assets some barcodes become unreadable either for h/w scanner (We use CipherLab 1070) and android app. We already tried to change width, height settings in snipeit/resources/views/hardware/labels.blade.php:54 file and experimenting with Label settings. 

We tried to use C128/C96 format w/ the same effect. Other formats are not usable because of h/w scanner incompatibility. 

**Screenshots**
![SnipeIT](https://user-images.githubusercontent.com/5687846/62603825-6e682100-b8ff-11e9-8448-7bf138c6d16a.PNG)
I mark scannable barcodes as green V and not scannable as red X. It generated w/ C128 as 1D barcode type.

How we can overcome this issue?

**Comment by zebby-nick** [comment]
We have the same issue but I assumed it was our label printer. We also tried a number of print settings and ended up buying a new scanner all to no effect. Glad its not just us with the issue.

**Comment by gilesytheking90** [comment]
I had a similar issue. Here are my steps to fix.

**Image Library**
1. Ensure the IMAGE LIBRARY's gd or imagick are enabled on your server
2. Edit your .env file to correspond with the image library you will use. I believe gd, is default, however I found imagick generated a better quality barcode image.
3. update your .env and clear cache
4. delete all the barcode images from the following folder /public/uploads/barcodes/
5. Generating a barcode for your assets will generate a new barcode image using the updated library settings.

**Adjust Label CSS**
Depending on your label size and label settings you will need to add some custom CSS to ensure the label outputs the barcode image correctly. I have found that the default CSS code squashes the barcode image, making it unreadable.

I have disabled 3D Barcodes for my labels and use the below CSS code to restyle the label. I have also made changes to the label layout by editing /resources/views/hardware/labels.blade.php, however this is not required.

`div.barcode_container {
    height: auto;
}
img.barcode {
width: 75%;
padding-top: 0.05in;
height: auto;
}
.qr_text {
    height: auto;
padding-top: 0.02in;
}
.pull-left {
text-align: center;
font-weight: 600;
}`

![label](https://user-images.githubusercontent.com/53617393/62874131-8f25e180-bd18-11e9-905d-2f0f78973a3d.png)

**Comment by arkeyme** [comment]
Thank you very much for the detailed answer. Now it works well, all of bardcodes are readable, but some are still is hard to read (I need to manage my scanner to read it), seems it because of printer quality.

We will buy a specific device (Brother PT-P700, if someone interesting in) to do this job. Anyway, thank you again!

**Comment by gilesytheking90** [comment]
Glad you got it sorted. I have a dymo labelwriter which works really well. Make sure the print quality is set to 300 x 600.
