### ISSUE TITLE
Under Locations search for "201" does not working

### ISSUE THREAD

**Issue by yuliyaTEST** [snipe/snipe-it#7333]
- [ ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
If I search under Locations for "201" nothing happend. It does not searcht at all. If I search for any other number the search funktion is working. On your demo https://demo.snipeitapp.com/locations is the same behavior.

**To Reproduce**
1. Go to 'https://demo.snipeitapp.com/locations'
2. In the search field write “201”
3. See -> nothing is happened

**Expected behavior**
As also in other cases the search will be work. I mean this is until now only the one number combination what I found that the search does not work.

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.13 build 3985 
 - OS: [e.g. Ubuntu, CentOS] Ubuntu 18.04.1
 - Web Server: [e.g. Apache, IIS] 5.4.35
 - PHP Version 7.2.19-0ubuntu0.18.04.1

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] Version 75.0.3770.142 (Offizieller Build) (64-Bit)

**Smartphone (please complete the following information):**

**Error Messages**
I am not getting any error messages for this behavior

**Additional context**
- Is this a fresh install or an upgrade?  -> Fresh install
- What OS and web server you're running Snipe-IT on -> Ubuntu and Apache
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) -> install.sh

**Comment by snipe** [comment]
This is a pretty obscure issue. What exactly is 201? Is that the name of the location?

**Comment by yuliyaTEST** [comment]
In our case 201 is the part of the name of the location. But also in general case the search should probably work independent from word or number what I am looking for. Or is there some exceptions for the search?

**Comment by yuliyaTEST** [comment]
For us this is still relevant. I descovered also interesting thing. 
In the Version v4.4.2 build 3666 (gaa5003d29) 
PHP 7.1.18-1+ubuntu16.04.1+deb.sury.org+1
Laravel Version 5.4.35
the search does not have this problem. And in new installation (see above) what we use productive and also in your Demo Version, this problem exist.
