### ISSUE TITLE
Missing class `DOMDocument` when requesting assets

### ISSUE THREAD

**Issue by zmeggyesi** [snipe/snipe-it#7341]
#### Please confirm you have done the following before posting your bug report:

- [X ] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Upon trying to request a requestable asset, I get an error thrown

**To Reproduce**
1. Create a requestable asset
2. Go to Dashboard -> Requests
3. Try to request asset
4. Observe error

**Server (please complete the following information):**
 - Snipe-IT Version v4.7.6 build 4143 (g3dc2cc9f2)
 - OS: [e.g. Ubuntu, CentOS] Debian
 - Web Server: [e.g. Apache, IIS] Apace
 - PHP Version  `7.3.8-1+0~20190807.43+debian10~1.gbp7731bf`

**Error Messages**
Class 'DOMDocument' not found

in CssToInlineStyles.php line 111
at CssToInlineStyles->createDomDocumentFromHtml('[SNIP HTML]')
in CssToInlineStyles.php line 36

**Additional context**
- Is this a fresh install or an upgrade? Fresh install
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Modified install.sh due to Debian 10 not being supported yet

**Comment by snipe** [comment]
I'm not able to reproduce this on the demo.

<img width="1374" alt="Screen Shot 2019-08-15 at 12 55 11 AM" src="https://user-images.githubusercontent.com/197404/63081007-5ee86980-bef7-11e9-9f42-3a2239ff7fe3.png">

A [quick google search](https://stackoverflow.com/questions/14395239/class-domdocument-not-found) shows you need to install `php-dom` and/or `php-xml`.

**Comment by zmeggyesi** [comment]
Thanks for a double-check. I _did_ try installing `php-xml`, even before reporting this, but the issue is still occurring. I tried clearing my Laravel log, and reproducing the issue, attaching the resulting logfile:
[laravel.log](https://github.com/snipe/snipe-it/files/3508927/laravel.log)
Does this contain anything that helps?

**Comment by zmeggyesi** [comment]
Okay, so as it turns out, the crash was caused not by the rendering library, but by the _email_ library: emails were not configured properly, once I fixed the outgoing settings, the crash stopped happening...
