### ISSUE TITLE
Api listing error

### ISSUE THREAD

**Issue by Blu3W0LF** [snipe/snipe-it#7342]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**
1. Go to 'Opening the terminal on the server'
2. We access the Snipe-it folder via the terminal 'cd xampp\htdocs\snipe-it'
3. we enter the command line and run  'php artisan route:list'
           In HandlesAuthorization.php line 28:

           This action is unauthorized.

**Expected behavior**
See the list of all api

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Error Messages**
C:\xampp\htdocs\snipe-it>php artisan route:list

In HandlesAuthorization.php line 28:

  This action is unauthorized.
![snipe-it_bug](https://user-images.githubusercontent.com/47629268/62829188-db7dfe00-bc00-11e9-99a0-f4e8f1ff4d6b.png)

**Comment by snipe** [comment]
Comment out the auth gates in the constructors from these files:

<img width="428" alt="Screen Shot 2019-08-15 at 12 43 31 AM" src="https://user-images.githubusercontent.com/197404/63080392-c9000f00-bef5-11e9-9b62-ac758820d144.png">
