### ISSUE TITLE
snipe-it。 已搭建完毕，但是.env文件问题

### ISSUE THREAD

**Issue by 57594261** [snipe/snipe-it#7344]
![image](https://user-images.githubusercontent.com/48671397/62842909-5c63f500-bce8-11e9-853f-e8c3a422dc0b.png)
报错信息：

Config File |   | Please make sure your .env is not readable by the outside world via web browser. You don't ever want anyone able to see that file. Ever. Ever ever. An exposed .env file can disclose sensitive data about your system and database. Click here to check now (This should return a file not found or forbidden error.)
-- | -- | --
改了.env的权限 711  700 744 611 755各种，但是还是没有用。

**Comment by jacklibra** [comment]
[root@localhost snipeit]# chown -R www:www storage public/uploads
[root@localhost snipeit]# chmod -R 755 storage public/uploads

哥们，照我这个改文件夹下面的目录权限。

**Comment by sid8000** [comment]
Check your VirtualHost settings in your Apache configuration file.
Check Directory and Document Root. It should direct **Public** folder in your Snipe IT folder.

**Comment by nixueyao0216** [comment]
I also encountered this problem during the deployment process. Could you please tell me how you solved it?
