### ISSUE TITLE
Manually backup failed

### ISSUE THREAD

**Issue by MarioZuo** [snipe/snipe-it#7346]
#### Please confirm you have done the following before posting your bug report:

- [√] I have enabled debug mode 
- [√] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When I tried to backup the data manually by clicking the button 'generate backup' under http://IP/admin/backups. It goes wrong then shows me 'whoops, blabla....'. But the auto backup is normal
**To Reproduce**
1. Go to 'admin' ->'Backups'
2. Click on 'Generate backup'
3. See error

**Expected behavior**
I want to backup manually.
**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version: 5.5.45
 - OS: CentOS7
 - Web Server: Apache
 - PHP Version:7.1.30 

**Desktop (please complete the following information):**
 - OS: windows10
 - Browser firefox
 - Version 68.0.1 (64-bit)

**Error Messages**
You can get the log as the attachment.

**Additional context**
- Is this a fresh install or an upgrade? fresh install
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
 install.sh
- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

[Desktop.zip](https://github.com/snipe/snipe-it/files/3491586/Desktop.zip)

**Comment by arkeyme** [comment]
Did you check MAIL_BACKUP_NOTIFICATION_ADDRESS= in /var/www/snipeit/.env file?
Also, you should check and fix permissions on /var/www/snipeit/storage/app

drwxrwxr-x 3 snipeitapp www-data 4096 Aug 12 13:09 backups
drwxr-xr-x 2 www-data   www-data 4096 Aug 12 13:09 backup-temp

**Comment by MarioZuo** [comment]
> 
> 
> Did you check MAIL_BACKUP_NOTIFICATION_ADDRESS= in /var/www/snipeit/.env file?
> Also, you should check and fix permissions on /var/www/snipeit/storage/app
> 
> drwxrwxr-x 3 snipeitapp www-data 4096 Aug 12 13:09 backups
> drwxr-xr-x 2 www-data www-data 4096 Aug 12 13:09 backup-temp

I checked my configuration. The permissions are correct, but I didn't configure the SMTP and notification address. BTW, I found the network on the host is abnormal, because I can't ping any WAN address. :( 
Fixing this first.
