### ISSUE TITLE
Import Asset feature doesn't work via Web Interface only. (Command line works well)

### ISSUE THREAD

**Issue by arkeyme** [snipe/snipe-it#7347]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

During importing we got Error message w/out any details. 

To import we use .csv file originally based on the "Sample asset import CSV" file, which can be downloaded from this page: https://snipe-it.readme.io/docs/importing

[sample-assets44.csv (1).txt](https://github.com/snipe/snipe-it/files/3492807/sample-assets44.csv.1.txt)

All user-related data from this csv file is already in the snipe-it database 

To import we use this link: http://inventory.our-domain.com/import

**Screenshots**
![SnipeIT_Import](https://user-images.githubusercontent.com/5687846/62869937-73730900-bd21-11e9-8932-94d66339990c.PNG)

**Server (please complete the following information):**
 - Snipe-IT Version v4.7.6 - build 4143 (master)
 - OS: Ubuntu 18.04.3 LTS \n \l
 - Web Server: Apache/2.4.29 (Ubuntu)
 - PHP Version:
PHP 7.2.19-0ubuntu0.18.04.1 (cli) (built: Jun  4 2019 14:48:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies

**Desktop (please complete the following information):**
 - OS: Win10
 - chrome 
 - Google Chrome is up to date Version 76.0.3809.100 (Official Build) (64-bit)

**Error Messages**
- WITH DEBUG TURNED ON, 

```
[2019-08-12 12:41:47] production.ERROR: Expected response code 354 but got code "503", with message "503 5.5.2 Need rcpt command
#97 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#98 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#99 /var/www/snipeit/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#100 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\Cors\HandlePreflight->handle(Object(Illuminate\Http\Request), Object(Closure))
#101 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#102 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#103 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#104 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#105 /var/www/snipeit/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#106 {main}  

```

- Include any additional information you can find in `storage/logs` and your webserver's logs.

```
[2019-08-12 12:41:47] production.ERROR: Expected response code 354 but got code "503", with message "503 5.5.2 Need rcpt command^M
" {"userId":1,"email":"Ilya.Taskaev@swtecnn.com","exception":"[object] (Swift_TransportException(code: 503): Expected response code 354 but got code \"503\", with message \"503 5.5.2 Need rcpt command^M
\" at /var/www/snipeit/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:457)
[stacktrace]

```

**Additional context**
- fresh install 
- 7.2.19-0ubuntu0.18.04.1 
- install.sh
- No Data edited in database

**Comment by arkeyme** [comment]
Finally I able to import my csv file, but ... from command line:
```
root@hostname:/var/www/snipeit# php artisan snipeit:import /root/sample-assets2.csv
======= Importing Items from /root/sample-assets2.csv =========
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%The following Errors were encountered.
Error: Item: Bord failed validation: {"Asset Model \"Bord\"":{"manufacturer_id":["The manufacturer id field is required."]},"Asset \"Bord\"":{"model_id":["The model id field is required."]}}

root@hostname:/var/www/snipeit# php artisan snipeit:import /root/sample-assets2.csv
======= Importing Items from /root/sample-assets2.csv =========
 1/1 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%All Items imported successfully!

```
And it shows which fields are incorrect. But **I still can't import this file via web interface**.  

I use these articles to rich this result: 
https://github.com/snipe/snipe-it/issues/7322#issuecomment-521132313
https://blog.teknex.com.au/snipe-it/snipe-it-file-import-stuck-on-processing/
https://snipe-it.readme.io/docs/importing#section-usage

**Comment by lyte0ne** [comment]
Still doesn't work from web interface

**Comment by thecigura** [comment]
This feature still doesn't work via Web Interface - CSV import.  Stuck in **Processing...**
Snipeit v6.0.1 build 7750 (gb2e7572fe), Docker image, PHP 7.4.26

**Comment by ResRipper** [comment]
> This feature still doesn't work via Web Interface - CSV import. Stuck in **Processing...** Snipeit v6.0.1 build 7750 (gb2e7572fe), Docker image, PHP 7.4.26

Related to #7571 , you need to add `MYSQL_PORT_3306_TCP_PORT=3306` to your environment variable or .env file in order to have both import and backup working.
