### ISSUE TITLE
FEATURE REQUEST - Accessories/consumables quantity on checkout

### ISSUE THREAD

**Issue by gilesytheking90** [snipe/snipe-it#7348]
Could you please add on option to enter the quantity of accessories & consumables to be checked out to a user?

Quantity option is available for components, but not for accessories & consumables. More often than not we need to check out multiple quantities of an accessory / consumable at the same time.
Currently we have to do multiple checkouts.

![consumables](https://user-images.githubusercontent.com/53617393/62870818-2fc4d300-bd12-11e9-8b11-b4ade4fe37ea.png)
![accessories](https://user-images.githubusercontent.com/53617393/62870819-2fc4d300-bd12-11e9-94eb-f9877eea5e1b.png)
![component](https://user-images.githubusercontent.com/53617393/62870821-2fc4d300-bd12-11e9-8326-c7606530fc0e.png)

**Comment by paulo1624** [comment]
Just like components can input quantity for checking out of items.

example: If user requesting 100 pcs of VGA cable, do we need to checkout this item 100 times to users. Maybe its better have an option for checking out as a bulk items for once to users.

**Comment by jonathanroots** [comment]
I agree with Ghost. 
Hope to have quantity to check out accessories and consumables.

**Comment by jonathanroots** [comment]
It is not too hard to add the quantity. since it works for components.  hope developers add this features. Thanks,

**Comment by philjak** [comment]
+1 - Would really love to see that.

**Comment by jonathanroots** [comment]
When snipe it can add this feature?

We need the feature.

Should we download the free app to install it on our server? We can update
the app by ourselves?



Thanks

John

**Comment by snipe** [comment]
@jonathanroots it's currently being worked on. There are other (open) tickets about it.

**Comment by jonathanroots** [comment]
Thanks, estimate when it will be done.

**Comment by snipe** [comment]
No timeline right now. There is an open PR that's actively being discussed and improved, but I have no way to estimate when it will be done.
