### ISSUE TITLE
Can an item be moved from assets to accessories?

### ISSUE THREAD

**Issue by cfinch** [snipe/snipe-it#735]
A user has created items in Snipe as assets, but these items (such as office furniture) should really be listed as accessories. Is there any way to move an item from assets to accessories?

**Comment by madd15** [comment]
As far as i know this cant be done without messing with the database.

**Comment by snipe** [comment]
That's correct. There is no simple way to move them from one to the other, since they behave differently and have different attributes and db tables.

**Comment by cfinch** [comment]
Thank you.
