### ISSUE TITLE
Add options to customize user notification e-mails for expected checkin and so on (frequency, etc)

### ISSUE THREAD

**Issue by IcyPunch** [snipe/snipe-it#7354]
First of all, big thanks to the Snipe-IT team. We enjoy the project a lot and appreciate your work and commitment.

**Server (please complete the following information):**
 - Snipe-IT Version v4.7.6 - build 4143 (master)
 - OS: [CentOS]
 - Web Server: [Apache]
 - PHP Version 7.1.30

**Is your feature request related to a problem? Please describe.**
Users receive e-mails daily, starting at 7 days before expected checkin. This is too much for us and our users. We do not have a web dev, so we cannot customize snipe-it just for ourselves.

**Describe the solution you'd like**
I would like to be able to customize these notifications via the web interface. For example: i would like to be able to set the starting point for expected checkin emails via a dropdown field, maybe: start at 2 days before expected checkin. Where 2 would be only one of the selectable values. Next it would be cool to select the amount of emails which are to be sent out to the user per day. Maybe I would like to notify the user twice at the day of expected checkin, just before the office hours are over and once in the morning. Setting specific times to send out the different emails could also be interesting.
If you would like to take things further, the email alerts and notifications in general could be more granular and more customizable directly from the web interface.

**Describe alternatives you've considered**
Unfortunately I'm no programming genius, so I do not have an idea.

**Additional context**

If my language is unclear or not understandable, please let me know and I'll try to rephrase. I'm not a native english speaker.

**Comment by snipe** [comment]
That's unfortunately a lot more complicated than it seems, since some people use the "every minute" polling, and other people run the email notifications on a different schedule individually via cron, and the way Laravel is set up, there isn't really a way to handle that.

https://snipe-it.readme.io/docs/configuring-alerts-backups

You'd probably just want to skip the scheduler and set the reports cron jobs to whatever you see fit, for example:

```
/path/to/php /path/to/your/snipe-it/artisan snipeit:backup
/path/to/php /path/to/your/snipe-it/artisan backup:clean
/path/to/php /path/to/your/snipe-it/artisan snipeit:expiring-alerts
/path/to/php /path/to/your/snipe-it/artisan snipeit:inventory-alerts
/path/to/php /path/to/your/snipe-it/artisan snipeit:expected-checkin
/path/to/php /path/to/your/snipe-it/artisan snipeit:upcoming-audits
```

**Comment by IcyPunch** [comment]
Thanks!
This is complicated for me to do (skill), but I'll try to configure it of course. I understand that you cannot set this up in general for all snipe-it users. I have tried to use the documentation on this, maybe I've overlooked the specific topic.

**Comment by snipe** [comment]
> This is complicated for me to do (skill), but I'll try to configure it of course

If your alerts are currently working, that means you have a crontab set up already (which is good). Just use the documentation above to, for example, change the crontab to specify weekly instead of daily:

```
crontab -e
```

```
@weekly /path/to/php /path/to/your/snipe-it/artisan snipeit:expiring-alerts
@daily /path/to/php /path/to/your/snipe-it/artisan snipeit:backup
@daily /path/to/php /path/to/your/snipe-it/artisan backup:clean
@weekly /path/to/php /path/to/your/snipe-it/artisan snipeit:inventory-alerts
@weekly /path/to/php /path/to/your/snipe-it/artisan snipeit:expected-checkin
@weekly /path/to/php /path/to/your/snipe-it/artisan snipeit:upcoming-audits
```

(etc)

**Comment by IcyPunch** [comment]
Will try to set it up, thanks a lot!
