### ISSUE TITLE
Label Printing on Avery 61528 Labels

### ISSUE THREAD

**Issue by janderson121** [snipe/snipe-it#7357]
#### Expected Behavior (or desired behavior if a feature request)

I've set the Label Settings to match the Word Template for the Avery 61528 Labels, correct page size, margins, label dimensions, and labels per page.

Like this:
![image](https://user-images.githubusercontent.com/54153650/63120526-6c8e0580-bf70-11e9-8fc7-955d9a3207ee.png)

-----

#### Actual Behavior

Labels are printing squished, from the 2.75" to the ~1.55" width. They are also printing in 3 columns rather than two. Perhaps I have the incorrect numbers? Any help would be greatly appreciated!

![image](https://user-images.githubusercontent.com/54153650/63120557-7f083f00-bf70-11e9-8bde-5dcf9c1afe85.png)

Label Config:
![image](https://user-images.githubusercontent.com/54153650/63124765-07d7a880-bf7a-11e9-9b7d-b3294b9157dc.png)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh

- Version of Snipe-IT you're running
4.6.5

- Version of PHP you're running
7.2

- Version of MySQL/MariaDB you're running
5.5.56

- What OS and web server you're running Snipe-IT on
CentOS 7.5

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
https://github.com/EarlRamirez/snipeit_iso

- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
[No errors]

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
[No errors]

- If a stacktrace is provided in the error, include that too.
[No errors]

- Any errors that appear in your browser's error console.
[No errors]

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Yes, I copied my label settings to the demo site, and attempted to print the same amount of labels and it still broke them into 3 rather than 2 columns.

- Include any additional information you can find in `storage/logs` and your webserver's logs.
N/A
- Include what you've done so far in the installation, and if you got any error messages along the way.
N/A

- Indicate whether or not you've manually edited any data directly in the database
No

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by audra-n-c** [comment]
In case anyone else happens upon this thread and wants updated settings for avery labels 61528, these are the label settings I ended up with that worked.
<img width="660" alt="Screen Shot 2020-11-11 at 3 24 14 PM" src="https://user-images.githubusercontent.com/12849137/98866097-08d3e000-2432-11eb-8ad1-347c9fce5ae3.png">
