### ISSUE TITLE
Upload invoices/documents to all types of items

### ISSUE THREAD

**Issue by Blueing** [snipe/snipe-it#7358]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.7.5
 - OS: Ubuntu 16.04
 - Web Server: Apache
 - PHP Version: 7.3

**Is your feature request related to a problem? Please describe.**
No not really, just something missing for me.
I thought I saw a similir feature request some days ago but couldn't find it again, I'm sorry if this is a duplicate

**Describe the solution you'd like**
Like for licenses I would like to have the possibilty to upload a document/invoice for a component, consumable, asset etc.

Something like the Image upload, but for .pdf files

**Describe alternatives you've considered**
For now I just converted my invoices to .jpg and uploaded it as Image, which is kinda clunkly

**Additional context**
![license](https://user-images.githubusercontent.com/19912040/63153927-c98cc880-c00f-11e9-8d93-d49337e8c288.PNG)

Within a license I get the upload context menu - what I love to see within every item, not only licenses!

**Comment by mdaac37** [comment]
Hi, this is an important missing feature for me.

At the moment we can upload images (including PDF files) to Assets and licenses but it would be great to also have that feature for accessories, components, etc...
