### ISSUE TITLE
Feature Request: Bulk edit Purchase Cost / other items

### ISSUE THREAD

**Issue by rp-tech** [snipe/snipe-it#736]
I love the Bulk Edit features that were added.

Is it possible in a future release to add the ability to bulk edit some more advanced items, such as the Purchase Cost?

For example, select multiple assets in the list, and then use the Bulk Edit Feature - should be able to change the Cost, Warranty, etc. associated with that group of items.

Thanks!

**Comment by rp-tech** [comment]
Just a heads up, I was able to get this working however for some reason it requires that I select a status when making the bulk edits. This of course should not be required as some of my assets are Ready to Deploy, others are Broken / not fixable, etc and therefore if I want to update the purchase cost on all of them, then I must also change all of their status to a single status.


![example](https://cloud.githubusercontent.com/assets/10659713/7458277/068d305c-f248-11e4-9571-ba4c55e83d6c.png)

**Comment by snipe** [comment]
I don't think status is actually required there. Have you tried editing without setting a status?

**Comment by rp-tech** [comment]
Yes, I tried to do that and it tells me 

Info: No fields were selected, so nothing was updated. 

If I select a status then it works properly as expected.

**Comment by snipe** [comment]
How can I reproduce this? What fields are you editing, and with what values?

**Comment by rp-tech** [comment]
Just go to Assets -> Deployed and select a bunch of items and use the bulk Edit.

Then, enter a price and don't select anything else (don't select a status) - same way as I did in the screenshot.

Regards,
