### ISSUE TITLE
Kits with specific assets

### ISSUE THREAD

**Issue by betsfeedback** [snipe/snipe-it#7360]
**Server (please complete the following information):**
 - Snipe-IT Version: v5.0.0-beta-2 - build 4009 (develop)
 - OS: [e.g. Ubuntu, CentOS]: Debian 10 
 - Web Server: [e.g. Apache, IIS]: Apache2
 - PHP Version: 7.3.4-2

**Is your feature request related to a problem? Please describe.**
Would like kits to contain Assets as well as Asset Models

**Describe the solution you'd like**
We have kits that we check out that contain specific assets. These are pre-built and we don't switch around which assets are in which kit. The kit functionality only supports Asset Models and not specific Assets.  We would like functionality to checkout the kit and the assets within that also get checked out.  Then if updates are needed to specific assets we can check to see which kit it is in and get them updated.  If the kit is checked out, then the asset would also be checked out so we would know we can't update it right now.

**Describe alternatives you've considered**
We have looked at making our kits Assets themselves, and then assigning the other assets to them, but then the child assets stay always checked out and we have to look up to the parent asset to see if it is in the warehouse or not.

**Additional context**

**Comment by gilesytheking90** [comment]
I believe this feature or something very similar is under development as part of the new V5 update. Take a look at the V5 news update below

V5 News Update (Multi Asset Creation) - #6287

**Comment by apautz22** [comment]
@gilesytheking90 The kit feature is in the development branch, but it doesn't have functionality for assets, only models, accessories, licenses, and components. I hadn't seen any movement suggesting that it would be added. This seems like a very important component of a kit as I want to set them up ahead of time with specific assets in them.

**Comment by betsfeedback** [comment]
@VELIKII-DIVAN is this something you can add to what you have already developed?
Being able to make a kit of specific assets. Currently you have it as a kit of asset models, but that won't allow me to make a kit of specific assets.

**Comment by jovibroz** [comment]
This is the only feature that's missing for me to start using this for our camera kit rentals. Can't wait to create a "Canon XA10 Camera Kit 1" with all the accessories, external mic, SD-card, charger, extra battery etc. 
Looking forward.

**Comment by jovibroz** [comment]
Waiting with huge anticipation for kits in v5. Most of our check outs are Camera Kits so not having to check out every single item individually would be a great benefit.

**Comment by jovibroz** [comment]
My most anticipated new feature is predefined Kits for check out and rental.

Den fre 31 jan. 2020 kl 09:53 skrev stale[bot] <notifications@githubcom>:

**Comment by betsfeedback** [comment]
still relevant

**Comment by KV-CS** [comment]
Can we reopen this? It appears that the release of v5 still has only asset models and not actual assets. I will echo the desire to create a photography kit, but I can also create an iPad Kit (iPad, keyboard, Apple Pen) and much more.

**Comment by bugraceylan** [comment]
+1 to this. We're often sending demo kits containing multiple items. It would be very useful if we can track this as a kit.

**Comment by frequencebanane** [comment]
Would be great !

**Comment by jamesso** [comment]
+1 we would use it for shared tool bags as well.

**Comment by rbjt97** [comment]
Still really need this feature to send out, well, premade kits.

**Comment by reveal79** [comment]
Would love this right now it's just based on assets you create. We have asset models and components that have quantity we would like to assign based on that

**Comment by jovibroz** [comment]
I'm a fan of this too, but realized I can check out multiple assets to an asset and that asset to a user, which does the same thing as pre-defined kits but with more control. Or am I missing something?

**Comment by reveal79** [comment]
We're associating our assets as components in the system and a quantity on
hand to sign out to users
