### ISSUE TITLE
Debian 10 Installer Support

### ISSUE THREAD

**Issue by techiem2** [snipe/snipe-it#7361]
**Server (please complete the following information):**
 - Snipe-IT Version None Yet  :)
 - OS: [e.g. Ubuntu, CentOS] Debian 10
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version None Yet

**Is your feature request related to a problem? Please describe.**
The installer does not yet support Debian 10, which is now the default stable version.

**Describe the solution you'd like**
Updated installer to support the Debian 10 and the package differences for it.

**Describe alternatives you've considered**
None really.

**Additional context**
I managed to get it working on a test server a couple months ago, but it took some strange doings and I don't recall exactly what I had to do to make it work (I think I had to clone the OS version section but also had to change a number of packages used as well for the copy).  I also don't want to do unsupported installation methods on a production server.  :)

Thanks!

**Comment by uberbrady** [comment]
We do have a Debian 10 install section in the installer now.
