### ISSUE TITLE
Upgrade Resulting in a 500 HTTP Error

### ISSUE THREAD

**Issue by Juwami** [snipe/snipe-it#7363]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

Running php upgrade.php should run through the upgrade process and allow me to sign in after the "Handy Commands" are ran. 

#### Actual Behavior

Before turning on Debug mode - we were receiving a 500 HTTP error which is the first. After turning on Debug mode we received a "Whoops, Something Went Wrong/ Fatal Throwable Error"

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Upgrade using php upgrade.php
- Version of Snipe-IT you're running
Master branch of Git; 
- Version of PHP you're running
PHP 7.3.3
- Version of MySQL/MariaDB you're running
MariaDB 10.1.41
- What OS and web server you're running Snipe-IT on
Ubuntu 18.04.1 and Apache2
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
![image](https://user-images.githubusercontent.com/40397599/63286177-699f5780-c285-11e9-8b4e-a88d7152219e.png)
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
It's currently all pages
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
Error is no reproducible on demo
- Include any additional information you can find in `storage/logs` and your webserver's logs.
Added laravel.log, password has been redacted
[laravel.log](https://github.com/snipe/snipe-it/files/3516986/laravel.log)
- Include what you've done so far in the installation, and if you got any error messages along the way.
Only semi errors are Carbon 1 is deprecated
We couldn't find a local composer.phar - trying globally but no further issues
- Indicate whether or not you've manually edited any data directly in the database
No data was added directly
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by snipe** [comment]
Are you sure you’re running php 7.3.3 on the web server (not just the command line)? That looks like a PHP version error to me.

**Comment by Juwami** [comment]
Hello,

I believe this is showing 7.3.3 on command line via command 'php -v'. I believe it should be at least 7.0 as my apache2 mods-enabled are php7.0. Also php5.0 is not listed as installed.

**Comment by snipe** [comment]
Per the requirements documentation, Snipe-IT requires 7.1.2 or greater: https://snipe-it.readme.io/docs/requirements
