### ISSUE TITLE
Feature Request: Bulk Audit - Location Changing? 

### ISSUE THREAD

**Issue by innocuoussoul** [snipe/snipe-it#7365]
**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS]
 - Web Server: [e.g. Apache, IIS]
 - PHP Version 

**Is your feature request related to a problem? Please describe.**
It's annoying that we can audit a location but cant actually move those assets to those locations without checking in.  Ideally, I want to be able to send one of my techs into a space and audit a location to make sure our stuff stays current. 

**Describe the solution you'd like**
An option to confirm location change. What's the point of the audit if we can't see if the location matches and can't action on the audit.

**Comment by marrodox** [comment]
I second this, this would be incredibly useful in my deployment.

**Comment by jacobsen9026** [comment]
It in the works on the dev branch and I created a pull request with and additional option to checkout to the location if not already checked out to a user.

https://github.com/snipe/snipe-it/pull/7580

**Comment by innocuoussoul** [comment]
It looks like this was already implemented in the dev branch for 5.0, is this pr different?

**Comment by jacobsen9026** [comment]
I improved the logic of the change location check currently on the dev branch. It wasn't checking if the asset was already checked out before setting it's new location.

The rest of my PR is (not directly related to this issue) to add the functionality to properly check out assets that are not assigned to users already via the bulk audit page. Which has been requested before and I really could have used myself so I built it.

**Comment by innocuoussoul** [comment]
This is awesome thank you!

**Comment by jacobsen9026** [comment]
Yes

**Comment by collectingapples** [comment]
If anyone gets any manner of bulk location changing working I would be so happy.  The ability to audit a location and have the stuff I scan moved into that location would be huge.  I guess I don't really understand what auditing would even mean without that ability.  I am currently trying to wrap my mind around what the audit feature does at all currently. 

  If I could also have the stuff I fail to scan be removed to another location, like some kind of "missing inventory",  that would be a real dream.

**Comment by collectingapples** [comment]
Still important
