### ISSUE TITLE
User location keeps reverting to default location

### ISSUE THREAD

**Issue by acerspyro** [snipe/snipe-it#7376]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
30 to 60 minutes after a user's location being set, their location reverts back to the default location for the system (in our case, our address).

I have looked through the database, and I can see the location pointer being changed 30 to 60 minutes after the last interaction with the system, so this is not a front-end issue.

**To Reproduce**
1. Edit a user
2. Set their location to anything but the default location
3. Check in asset to user
4. Wait ~ an hour
5. User location occasionally switches back to the default

**Expected behavior**
The location does not revert

**Screenshots**
My notes on the issue:
![image](https://user-images.githubusercontent.com/4400999/63696141-14fd5e80-c7e8-11e9-99e3-04aee41940e8.png)

**Server (please complete the following information):**
 - Snipe-IT Version v4.7.5 - build 4118 (master)
 - Ubuntu Server 18.04
 - Web Server: Apache
 - PHP 7.4

**Desktop (please complete the following information):**
 - OS: Manjaro Linux, Kernel 5.2.8-1, GNOME Desktop
 - Browser Firefox
 - Version 68.0.1 (64-bit)

**Additional context**
- Installed via install.sh

Let me know if you need to know anything else.

**Comment by acerspyro** [comment]
Yes

**Comment by sidjai09** [comment]
I have this same issue with asset location

**Comment by acerspyro** [comment]
We'd be ready to pay for support to get this issue fixed.

**Comment by hdvan** [comment]
I also have this issue.

**Comment by jrbeyer93** [comment]
This is happening to me as well. It defaulted almost ALL of my users to a location they are not in. Is there a fix for this? 

I requested for the sysadmin team to make sure it is fully updated. Once they do that I will let you know if this is still an issue!

**Comment by jrbeyer93** [comment]
yup this is still happening even with it updated.

**Comment by acerspyro** [comment]
I can confirm that this is happening.

@snipe this is causing havoc in our system as we can no longer use the location field for user-assigned assets due to this bug, we had to create a separate custom field named "location-it" to circumvent it as the locations kept reverting back to our office address and we lost track of equipment that way.

**Comment by snipe** [comment]
> I have looked through the database, and I can see the location pointer being changed 30 to 60 minutes after the last interaction with the system, so this is not a front-end issue.

That’s not a thing we do. There is no service that runs every 30 minutes within Snipe-IT. Or even every hour.

@acerspyro i’m not sure I understand what’s even happening here. What version are you running?

**Comment by acerspyro** [comment]
@snipe Sorry for the delay in responding, I've been busy.

We are currently running Version v5.0.4 - build 5452 (master)

As you mentioned, I indeed could not find anywhere in the code a cyclic task that would run every 30 minutes, but it's what I noticed when watching the database: The user location reverts to the default one either immediately or within 30 minutes after assigning them an asset.

**Comment by jrbeyer93** [comment]
@snipe I am having the same issue as acerspyro and have for some time. the user's location defaults and the assets don't BUT the asset's location will change when it gets assigned to a user (which then goes to the same default location).

**Comment by jrbeyer93** [comment]
Yesterday at 9:40AM EST I started changing the user locations back to their appropriate locations which I ended up finishing late last night. When I looked today it hasn't defaulted the location yet. For me, it typically takes a couple days for it to go back to the wrong location.

**Comment by uberbrady** [comment]
Are you folks using LDAP? That's the only periodic process I know of that will change a *user's* location. If we're talking 30-60 minute times for locations to change, that sounds like a cron'ed ldap-sync. Of course I live in LDAP lately, so that could be just an assumption I make because that's a lot of what I see lately. If so, the most recently released v5.0.7 doesn't try so hard to move users around.

**Comment by jrbeyer93** [comment]
Yes, I am. But it doesn't pull location information from LDAP, just the name and email of the user. Could that still cause issues?

**Comment by uberbrady** [comment]
If you have specific OU settings for Locations (hit 'edit' on a particular Location to see) that will absolutely set a user's location to whatever you've specified based on which OU they exist in, no matter what. If you don't want that, you should definitely remove the OU from the Location. Or move the user in your directory to the appropriate OU (which is probably more correct).

But, regardless, in many cases under v5 (only before v5.0.7), we would reset users to their default location on LDAP sync, overriding the Administrator's explicit choices. So that definitely could be your problem.

As always, please make sure to backup or snapshot or_something_ before you do anything that could be destructive.

**Comment by acerspyro** [comment]
I just checked, the default (parent) location that all users revert to does not match anything present in the user's AD properties.

You may be onto something though with the LDAP import every 30 minutes or so, it may be overwriting the location even though we never specified anything related to getting the location from AD, nor did we specify a target OU for any of our locations.

**Comment by uberbrady** [comment]
I'm pretty sure that's it; from version 5.0.0 up through 5.0.6, we had a bug that would basically re-set the location to 'default' on sync if there weren't overriding OU's in-place. It sounds like you don't have that so...yeah. Sorry :( 

v5.0.7 shouldn't do that any more, if you can give it a whirl.

**Comment by jrbeyer93** [comment]
I updated the inventory to 5.0.7 and the user locations. When I looked today it changed the user locations back to a location most do not belong in. How can I fix this? It look me 10 hours last time to update the users to their correct location since we have so many

**Comment by acerspyro** [comment]
I can confirm that this is still an issue in v5.0.10 build 5680

I cannot trigger the bug by forcing an LDAP sync, so it must be something else.

Can we re-open this issue?

**Comment by jrbeyer93** [comment]
I would like this reopened as well

**Comment by acerspyro** [comment]
Correction: I can reproduce the issue by forcing an LDAP user sync and selecting a location there

![image](https://user-images.githubusercontent.com/4400999/101531750-ad7a0c80-3961-11eb-9964-12cdf19abc40.png)

This overwrites every LDAP-synced user's location to whatever is selected on there. This is incorrect behaviour, users who do not have a location should be set to the default location selected, and other users should be left with their current location.

https://github.com/snipe/snipe-it/blob/master/app/Services/LdapAd.php#L224

In this function, `$userInfo` seems to always have `location_id` set to the default location, which causes an overwrite of the user location in SnipeIT as per https://github.com/snipe/snipe-it/blob/master/app/Services/LdapAd.php#L243

https://github.com/snipe/snipe-it/blob/master/app/Services/LdapAd.php#L200 here is where `location_id` is set, the comment above describes correct behaviour, but that's not what we are seeing.

**Comment by jrbeyer93** [comment]
Usually when I do an LDAP sync, I don't select a location and I just select Synchronize. Today I selected an actual location and it made everyone who still has an AD account go to that location. I changed the location and it moved everyone's location to the new one. 

At one point I added the user's location in the notes but once I did an LDAP sync my notes were replaced with 'Imported from LDAP' so I have no easy way of knowing where these user's are actually at without double checking in Active Directory.

**Comment by acerspyro** [comment]
@jrbeyer93 I noticed this commit only 6 days ago pertaining to notes

https://github.com/snipe/snipe-it/commit/bec2b170ec3d1b1eb77e53971706867ad136591d

Hopefully this helps you on that front, but I believe more work is necessary to resolve the user location issue.

**Comment by jrbeyer93** [comment]
@acerspyro thank you!

And I second that more work is necessary. There's just something that's not working right. When I originally posted, the location defaulted to a location that I didn't have in AD and only had in SnipeIT. I then removed everyone from that location and deleted the location to see what would happen. It ended up just defaulting to a different location I had within SnipeIT. 

Everything else seems to be working great

**Comment by acerspyro** [comment]
@uberbrady I've updated my comment above with more details. Hopefully this helps you guys track down this issue.

https://github.com/snipe/snipe-it/issues/7376#issuecomment-740901914

**Comment by uberbrady** [comment]
Thanks @acerspyro - it definitely does.

**Comment by acerspyro** [comment]
Hello! Apologies for being pushy, any updates on this so far?

**Comment by jrbeyer93** [comment]
SOLUTION FOUND!!!

I was working with my co worker and he decided to try populating the LDAP Search OU field in each of their parent locations. He then did an LDAP sync and all the locations for the users were set to the correct location. 

![image](https://user-images.githubusercontent.com/68250831/108856857-7c9c9180-75b8-11eb-8302-71f45ebb5d48.png)

**Comment by uberbrady** [comment]
I'm so glad you finally got it working! I'll close this one out :)
