### ISSUE TITLE
Email bounces because of wrongly formatted From: header

### ISSUE THREAD

**Issue by k-ryo** [snipe/snipe-it#7377]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When trying to send email to Gmail via Sendgrid, email will be rejected by Google due to Snipe-IT (or Swiftmailer) not handling the From header correctly.

From header that will get rejected by Google:
```
From: Snipe-IT <sender@email.com>
Reply-To: Snipe-IT <receiver@google.com>
```

Google will return error:
```
550 5.7.1 [198.37.159.89 14] Messages missing a valid address in From: 5.7.1 header, or having no From: header, are not accepted. k15si8893088ejd.112 - gsmtp
```

What Google expects:
```
From: "Snipe-IT" <sender@email.com>
Reply-To: "Snipe-IT" <receiver@google.com>
```

What I tried to fix the issue: (In .env)
```
MAIL_FROM_ADDR='sender@email.com'
MAIL_FROM_NAME='""Snipe-IT""'
MAIL_REPLYTO_ADDR='receiver@mailtester.com'
MAIL_REPLYTO_NAME='""Snipe-IT""'
```

After the manual fix, somehow only Reply-To header is properly formatted:
```
From: Snipe-IT <sender@email.com>
Reply-To: "Snipe-IT" <receiver@mailtester.com>
```

**To Reproduce**
Send any email to Google via Sendgrid SMTP method.

**Expected behavior**
Name are in double quotation in From: and Reply-To: email header.

**Screenshots**
N/A

**Server (please complete the following information):**
 - Snipe-IT Version: v4.7.6 - build 4143
 - OS: [e.g. Ubuntu, CentOS] Amazon Linux 2
 - Web Server: [e.g. Apache, IIS] Nginx
 - PHP Version: 7.2.19

**Error Messages**
N/A

**Additional context**
- Is this a fresh install or an upgrade? 
upgrade

- What OS and web server you're running Snipe-IT on
Amazon Linux 2

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
Git

- Include what you've done so far in the installation, and if you got any error messages along the way.
N/A

- Indicate whether or not you've manually edited any data directly in the database
No

**Comment by arturochent** [comment]
@k-ryo I got a case with this recently. Turns out that the store name contained an & and the system is translating it to &amp; and breaking the validation chain. I changed the & for and and the emails started to flow...
