### ISSUE TITLE
Feature Request - Requestable tab, grey buttons if deployed and show checked out user column

### ISSUE THREAD

**Issue by selifka** [snipe/snipe-it#7378]
**Server (please complete the following information):**
 - Snipe-IT Version : _v4.7.6 build 4143 (g3dc2cc9f2)_
 - OS: [e.g. Ubuntu, CentOS]:  _Ubuntu 18.04_
 - Web Server: [e.g. Apache, IIS] : _Apache_
 - PHP Version : _7.2.19_

**Is your feature request related to a problem? Please describe.**

_- Under the 'Requestable' tab, items that are deployed still show a 'Request' button. When pressed, the button throws an error if the item being requested is deployed (as expected)._

**Describe the solution you'd like**

_- I would like it if the 'Request' button were greyed when an item is deployed since users do not notice the status in the 'Status' tab._
_- I would also like for the 'Checked Out User' to be available from the 'Requestable Assets' page, that way users can view who has what asset before they make their request._

**Describe alternatives you've considered**

_- We have considered having our users utilize the Assets tab for checking out specific devices, however, we do not want users to have access to all of the devices. We have a set of devices that are available for our employees to check out, and we have a set of devices that our regular employees cannot checkout. We want to utilize the 'Requestable' page to make this separation of privileges easy._

**Additional context**

**Requestable Assets tab, and the buttons available**
<img width="695" alt="Screen Shot 2019-08-27 at 4 11 00 PM" src="https://user-images.githubusercontent.com/6687294/63801074-e06fcc80-c8e5-11e9-8b23-5e5618921cd3.png">

**Column options on the Requestable assets tab**
<img width="200" alt="Screen Shot 2019-08-27 at 4 15 53 PM" src="https://user-images.githubusercontent.com/6687294/63801119-f54c6000-c8e5-11e9-9820-dae972d4c803.png">

**Comment by ajsy** [comment]
I am having the same as yours, you have two workaround

Edit the deployed Assets manually to clear the Requestable checkbox
or add event in mariadb to automatically clear the Requestable value when assets deployed

**Comment by selifka** [comment]
I ended up adding some additions to the code used for the requestable tab, now users cannot click a button if an item is deployed (instead the button shows as disabled), additionally users can now view who has which item from this tab thus preventing all users from having to use the assets tab. Making code changes is the only way I was able to resolve my feature request, as such I'll be refining the code and will be sending a pull request soon in case others may find this feature useful.

**Comment by ajsy** [comment]
Thank you for sharing the solution. I am interested please mention me when sending the pull request.
