### ISSUE TITLE
403 Forbidden Error when trying to create a custom report 

### ISSUE THREAD

**Issue by cupcak6024** [snipe/snipe-it#7379]
#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode 
- [ yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
It redirect me to the webpage /reports/custom and says the directory or file not found , i get a 403 forbidden error 

**To Reproduce**
try to run a custom report 

**Expected behavior**
my report to run 

**Screenshots**
File not found

Firefox can’t find the file at http://***************-1.compute.amazonaws.com/reports/custom.

    Check the file name for capitalization or other typing errors.
    Check to see if the file was moved, renamed or deleted.

**Server (please complete the following information):**
Snipe-IT version | v4.6.15  build 4011 (gd1e9fbfa2)
-- | --
Software License | AGPL3
PHP Version | 7.2.17-1+ubuntu16.04.1+deb.sury.org+3
Laravel Version | 5.4.35

**Desktop (please complete the following information):**
 - OS: windows 10 
 - Browser mozilla and chrome 
 - Version 

**Additional context**
- Is this a fresh install or an upgrade? 
purchased with aws marketplace 
- What OS and web server you're running Snipe-IT on
ubuntu and apache 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
aws marketplace 
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
no

**Comment by cupcak6024** [comment]
Hi Earl

Firstly the folder /var/www/html/snipe-it/public/reports/custom doesn’t exisit , so I created it using the same permissions as the rest of the folders in this directory , but it then told me I don’t have permission. So do I have to create the folder ? and if so what permissions does it require ? at the moment its 751 and belongs to www-data. Any help you can give me on this would be awesome as I am giving a presentation in 4 weeks !!! 😃

Best Regards

Kelly Angell
Technical Support Engineer
SmartCIC Global Services
54 Boulevard Carnot
Cannes 06400
France
Fixe: +33 (0) 486 688 045
Mobile : +33 (0)6 30 07 65 99
Email: kelly.angell@smartcic.com<mailto:kelly.angell@smartcic.com>
Web: www.smartcic.com<http://www.smartcic.com/>

∷SmartCIC::
Specialists in Off-Grid and Custom Connectivity Solutions
Connectivity | Infrastructure | Communications Nº SIRET:  503 618 290 00038 Nº TVA:    FR51 503 618 290

**Comment by EarlRamirez** [comment]
A couple of things
- There is no folder called reports, where did you get this? I spin up a new VM import data and generate custom data and it works as expected.
- I don't believe that @snipe supports the AWS image you purchased; therefore, you will have to work with them to identify why the custom report does not work.

If you want to gather some details to bring to the sellers of Snipe-IT AWS, you can spin up https://github.com/EarlRamirez/snipeit_iso to confirm that it is working. You can also use Snipe-IT demo or docker containers for this.

Did you get any errors when debug was enabled?
