### ISSUE TITLE
Custom asset report for more than one location

### ISSUE THREAD

**Issue by hendersony** [snipe/snipe-it#7381]
**Server (please complete the following information):**
 - Snipe-IT Version : v4.6.18 - build 4036 (master)
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version : 7.1.31

**Is your feature request related to a problem? Please describe.**
On the "Custom Asset Report" page to export only certain assets results may be fine-tuned by choosing options like: company, location, etc.

However, to fine tune using the "Location" drop-down you may choose only one location.  
Presently, an attempt to select add a secondary location overwrites the first choice.

**Describe the solution you'd like**
I would like to be able to create a custom asset report for more than one location; thus modify the "Location" drop-down to allow a secondary, or even a third choice in order to  fine-tune assets to be exported for more than one location.

**Describe alternatives you've considered**
Presently, I have considered concatenating the results of two custom asset reports using location1 and location2, and then merge the results into one report. The reports generated for location1 and location2 have the same asset attributes selected, like manufacturer, serial number, purchase cost, and location.

**Additional context**
None

**Comment by hendersony** [comment]
**Yes, this feature is still relevant!**
The **Custom Asset Report** window allows for the selection of one location from the drop-down list. However, requesting the ability to add a secondary location to the list, effectively allowing query results for custom asset report to include two locations versus the limitation of one location.  

The solution would operate like **Bulk Checkout** whereby on the **Checkout Assets** window more than one asset can be added to the list: with the click of the cursor, the asset list again displays for selection of another asset and then appended to the list; likewise the ability to fine-tune the export of assets with the click of the cursor, the location list displays for selection of a location and then appended to the list.

**Comment by twsit988** [comment]
I'd like this feature as well instead of generating a report for everything. The ability to have more than one selection would be very helpful.
