### ISSUE TITLE
Error 500 permission (confirmed FAQ page was followed)

### ISSUE THREAD

**Issue by dmarcsift** [snipe/snipe-it#7383]
#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode 
- [X ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After following all of the instructions, I receive an error 500 when resolving to the /setup page. Debug mode says:

>"The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied"

Confirmed permissions are set correctly.
**To Reproduce**
1. Follow getting setup instructions for bare metal install.
2. Go to initial web page setup.
3. Error 500.
4. Enable debug mode and reboot Apache.
5. Receive error.

**Expected behavior**
Should be able to complete the /setup page.
**Screenshots**
N/A
**Server (please complete the following information):**
 - Snipe-IT Version : 4.7.5
 - OS: 18.04 LTS
 - Web Server: Apache
 - PHP Version: 7.2

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Chrome
 - Version: 76.0.3809.132

**Error Messages**
- /var/www/html/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php
 - throw new \UnexpectedValueException(sprintf('The stream or file "%s" could not be opened: '.$this->errorMessage, $this->url));
- The stream or file "/var/www/html/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied

**Additional context**
- Fresh install. All services hosted locally.
- Followed all instructions for bare metal install.
- Googled the error 500 and consistent message is: "It's a permissions issue," that seems like a common problem sometimes in laraval deployments.
- chown -R snipeit:www-data /var/www/html which contained the files for snipe-it git pull
- Confirmed permissions for storage are as follows:

- server:/var/www/html$ ls -la storage/
- total 28
- drwxr-xr-x  7 snipeit www-data 4096 Aug 29 04:42 .
- drwxr-xr-x 16 snipeit www-data 4096 Aug 29 05:25 ..
- drwxr-xr-x  3 snipeit www-data 4096 Aug 29 04:42 app
- drwxr-xr-x  2 snipeit www-data 4096 Aug 29 04:42 debugbar
- drwxr-xr-x  5 snipeit www-data 4096 Aug 29 04:42 framework
- drwxr-xr-x  2 snipeit www-data 4096 Aug 29 05:14 logs
- drwxr-xr-x  9 snipeit www-data 4096 Aug 29 04:42 private_uploads
- server:/var/www/html$ ls -la storage/logs/
- total 12
- drwxr-xr-x 2 snipeit www-data 4096 Aug 29 05:14 .
- drwxr-xr-x 7 snipeit www-data 4096 Aug 29 04:42 ..
- -rwxr-xr-x 1 snipeit www-data   14 Aug 29 04:42 .gitignore

**Comment by EarlRamirez** [comment]
@dmarcsift Apache needs to write to the log, _chmod -R g+w /var/www/html/storage_ should resolve your issue.

**Comment by dmarcsift** [comment]
This worked. Thank you.
