### ISSUE TITLE
Switch (or option) to use OpenStreetMap

### ISSUE THREAD

**Issue by dmarcsift** [snipe/snipe-it#7385]
**Server (please complete the following information):**
 - Snipe-IT: 4.7.5
 - OS: Ubuntu 18.04 LTS
 - Web Server: Apache2
 - PHP Version: 7.2.19

**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like**
Since Google switched to charging for using the Maps API, it would be in the interest of the open source community to utilize an open source solution that has no cost associated with it to add the map functionality back with zero cost. Some IT organizations may not be able to afford the Google Maps API cost if they're already running an in house Snipe-IT deployment. 

**Describe alternatives you've considered**
Looked at Bing integration however that would involve setting up a platform with cost associated with it. Mapbox might work as they have a free tier for <50,000 web based loads per month.

**Additional context**
Integration for OpenStreetMaps can be found here: https://wiki.openstreetmap.org/wiki/Using_OpenStreetMap
Users would still need to register, but I still feel this might be a good alternative to being locked into Google Maps API.

**Comment by dmarcsift** [comment]
Still would like to see an alternative to using the paid version of Google Maps to integrate with Snipe. Unless I'm missing something about the integration. Looks like there's a fee to use Maps.

**Comment by MairusuPawa** [comment]
Hello! I'm still interested in this feature. Even better if this means we could use basic maps with a fully "offline" (no internet) instance.

**Comment by Iizuki** [comment]
OSM would still be preferable to google/apple maps.
