### ISSUE TITLE
Carbon 1 is deprecated

### ISSUE THREAD

**Issue by JoatWiPete** [snipe/snipe-it#7386]
I am receiving an error message when I run php upgrade.php

`Carbon 1 is deprecated, see how to migrate to Carbon 2. https://carbon.nesbot.com/docs/#api-carbon-2 You can run './vendor/bin/upgrade-carbon' to get help in updating carbon and other frameworks and libraries that depend on it.`

If I try running that command to upgrade, it asks me

```
Do you want us to try the following upgrade:
  - nesbot/carbon: ^2.0.0
  - laravel/framework: ^5.8.0
[Y/N]
```

which obviously fails because it requires laravel 5.8, and that gives problems with all my other dependencies and php version.

Has anyone else come across this? Is there any solution for this besides v5? Or should I just shut up and not worry because everything seems to still work?

**Server (please complete the following information):**
 - Snipe-IT Version **4.7.6** 
 - OS: [e.g. Ubuntu, CentOS] **Ubuntu 18.04**
 - Web Server: [e.g. Apache, IIS] **Apache/2.4.41**
 - PHP Version **7.3**

**Comment by dmeltzer** [comment]
Thats a warning, not an error.  You can safely ignore it.

**Comment by JoatWiPete** [comment]
Cool, thanks. I assume then that patches are dependant on future laravel upgrades in v5.
