### ISSUE TITLE
New assets should automatically set next audit date

### ISSUE THREAD

**Issue by rickheil** [snipe/snipe-it#7393]
**Server (please complete the following information):**
 - Snipe-IT Version 4.7.6
 - OS: [e.g. Ubuntu, CentOS] Ubuntu
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version  7.1.31

**Is your feature request related to a problem? Please describe.**
New assets do not automatically enter themselves into the audit queue - we need to either manually set the next audit date, or create the asset and then audit it right away to get Snipe to remind us after a year to audit it again.

**Describe the solution you'd like**
Assets should automatically set next_audit_date according to the user defined setting for audit period.

**Additional context**
I am working on a PR to add this feature.

**Comment by rickheil** [comment]
This is resolved on develop branch.

**Comment by ecoflac** [comment]
Please add this feature to the next release.
