### ISSUE TITLE
Admin Loophole

### ISSUE THREAD

**Issue by tomholovis** [snipe/snipe-it#7396]
**Describe the bug**
User can elevate themselves over their current permission level.

**To Reproduce**
- Create a user and assign to a group that does not have admin privileges, but can edit users.
- login as the new user.
- edit yourself and change your permission for "Admin" from "Inherit" to "Grant"

**Expected behavior**
Edit a user such as change their location, reset their password, disable their account. But not grand them access rights above your own.

**Server:**
 - Snipe-IT Version: v4.7.6 - build 4143 (master)
 - Ubuntu
 - Apache

**Further Information**
I am hiding the sections that we are not currently using (such as components) so that the UI stays as clean and as simple to use as possible. This loop hole allows people that can edit users to also turn on the hidden sections of the software.

**Comment by EarlRamirez** [comment]
@tomholovis I tried to reproduce the result but was unsuccessful. I did the following since I am working from a vanilla install.
- Create a group with permission to view reports and assets, also view, create, and edit users.
- Create and assign the user to the test group
- From a different browser, log in with the user
Let me know if there are additional permissions that need to be added to produce the result that you are experiencing.

**Comment by tomholovis** [comment]
@EarlRamirez thanks for testing this. I am also working on a fresh install (I am trying to create a template VM image).

I create the group "test group". And give the the same permissions as yourself.
I create the user "test" and assign them to "test group".
I login with a different browser as "test".
I then navigate to people and select the edit button on myself (the user "test").
I can then select the Permissions tab and give myself any permissions I want other than super user.

How is the behaviour that you see different? Can you also edit your own permissions?

**Comment by EarlRamirez** [comment]
@tomholovis, I just realise that I was on the vanilla version from https://github.com/EarlRamirez/snipeit_iso. I will upgrade from 4.6.5 to 4.7.6 and try again.

**Comment by EarlRamirez** [comment]
Confirmed its a bug, sent an email to Snipe-IT security team as instructed [here](https://github.com/snipe/snipe-it#Security)

**Comment by tomholovis** [comment]
Thanks. I missed that!

**Comment by tomholovis** [comment]
Did this get fixed?

**Comment by tomholovis** [comment]
@EarlRamirez  - did you spot if this got fixed?

**Comment by tomholovis** [comment]
@snipe - did this get fixed?

**Comment by tomholovis** [comment]
@snipe - did this get fixed?

**Comment by tomholovis** [comment]
I'll try this one more time. @snipe did this get fixed?

This is the last time I'm poking this thread as I'm not using the platform for future projects.

**Comment by snipe** [comment]
I believe this was fixed many versions ago.
