### ISSUE TITLE
Cannot upgrade to 4.7.6

### ISSUE THREAD

**Issue by pavilonsxx** [snipe/snipe-it#7398]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
I am using version 4.7.5. When I upgraded the manual to 4.7.6, when I went to see the version again, there was still version 4.7.5

**Server (please complete the following information):**
 - Snipe-IT Version 4.7.5
 - OS:  CentOS
 - Web Server: Apache
 - PHP Version 7.1.3

**Comment by EarlRamirez** [comment]
@pavilonsxx Did you clear your configs and cache after the upgrade?

**Comment by pavilonsxx** [comment]
Yes, I downloaded it from snipeitapp.com folder v4.7.6 but when I extracted and viewed the version file in the config folder, the version is still v4.7.5 build 4137
![2019-09-03_8-09-34](https://user-images.githubusercontent.com/33487841/64137426-6af28780-ce22-11e9-826c-f6020a8ae251.jpg)
![2019-09-03_8-10-36](https://user-images.githubusercontent.com/33487841/64137432-72199580-ce22-11e9-83a8-0b8e175f85de.jpg)
Please help me!!!

**Comment by mdugdale** [comment]
I am experiencing a similar problem, although I am using docker. The process I used to upgrade is (upgrading from 4.7.4 to 4.7.6):  
`docker-compose down`  
Edit the docker-compose file to pull version 4.7.6  
`docker-compose up -d`  
Then, I started a bash shell in the docker container and ran:  
```
export APP_ENV=maintenance 
php artisan down
php artisan migrate 
php artisan up 
export APP_ENV=production
```

I also tried clearing the config cache:  
`php artisan config:clear`  
`php artisan config:cache`  

It is showing that I am now on version 4.7.5:  
<img width="744" alt="Screen Shot 2019-09-03 at 9 09 49 AM" src="https://user-images.githubusercontent.com/6598874/64176080-a7c27c80-ce2a-11e9-9c2b-b7d89788290c.png">

**Comment by pavilonsxx** [comment]
Thanks @mdugdale, but I don't use docker. So in this case how to view the correct version?

**Comment by mdugdale** [comment]
well I am not suggesting that you actually have the correct version installed, I am saying I think I have the same problem as you. Docker says it pulled 4.7.6 but snipe-it says I'm on 4.7.5. So I think the docker upgrade process and manual upgrade processes might both be broken and it could be something similar. I commented mostly to give the developers more information to find a fix

**Comment by pavilonsxx** [comment]
Thanks @mdugdale.
