### ISSUE TITLE
Empty Data

### ISSUE THREAD

**Issue by superjj74** [snipe/snipe-it#740]
Hi,

i correct install (i hope) the snipeit on my server.. with dummy data to test it.. 
debug mode true,

the problem is that i do not view demo assets or demo user..

there is no exception in debug bar..

the selected language is italian ( i try also in english but get the same error).

any suggestion?

**Comment by madd15** [comment]
is there any details of the error in the logs?

**Comment by snipe** [comment]
@superjj74 can you try running `php composer.phar update` please and tell me if that fixes it?

**Comment by superjj74** [comment]
http error logs do not contain referecente to snipe-it

snipe-it/storage/logs is empty..

i do a php composer.phar update then i delete db and reinstall with php
artisan app:install ,but do not change... i create a new user (it is in db)
and i cannot see it on the view, same thing for assets the database
containts the 12 dummy asset but nothing in the view.

any suggestions?

**Comment by snipe** [comment]
What happened when you did the composer update *before* you deleted the DB and re-install? I want you to just run the update and refresh the page.

Delete the contents (not the directory) of `app/storage/cache` and `app/storage/views` and refresh the page.

Also please show me a screenshot of what you see on the assets page.

**Comment by superjj74** [comment]
Now it works! after deleting app/storage/views.

thank's a lot.

**Comment by snipe** [comment]
![anigif_enhanced-26281-1427581758-6](https://cloud.githubusercontent.com/assets/197404/7133261/4dfb1394-e246-11e4-9cc9-7d8ca1852f1d.gif)
