### ISSUE TITLE
Asset image not present after Cloning Asset

### ISSUE THREAD

**Issue by AZ-GIT** [snipe/snipe-it#7400]
After cloning asset with an image - asset image should be present for the new asset unless box to delete is ticked, but it is not.

Issue can be replicated in demo.

**Comment by gilesytheking90** [comment]
I have noticed this issue too. 

A quick work around is to add the image to the asset model rather than the individual asset.

**Comment by cybtachyon** [comment]
Please 👍 the original issue to upvote and keep it active. Thanks!
