### ISSUE TITLE
Feature request: The ability to retain "notes" for LDAP-synced users

### ISSUE THREAD

**Issue by x0m0n** [snipe/snipe-it#7404]
**Server (please complete the following information):**
 - Snipe-IT Version v4.6.15
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version 5

**Is your feature request related to a problem? Please describe.**
When users are synced from LDAP, whatever I had in the "notes" field gets overwritten with "Imported from LDAP". Also deleted users in LDAP would just be gone in Snipe-IT and consequentially orphans assets, making it hard to track the history.

**Describe the solution you'd like**
Retaining the content of the "note" field for synced users and/or add additional custom field for users to serve similar note-taking purpose, whichever is easier.
Please allow for a grace period from when the user is deleted in AD to when they're taken out of Snipe-IT through sync. Instead, put them in inactive state for a little while so assets checked out to said user can be seen at a glance.

**Describe alternatives you've considered**
Using a custom attribute in AD, but that fragments the asset-tracking side and the note can be lost with multiple AD administrators working on the accounts, as well as being a convoluted process.

**Additional context**

**Comment by snipe** [comment]
I think this was already handled in a previous release (April?).
https://github.com/snipe/snipe-it/commit/dae26e0378d9f554a5c415b28cc20caa555fe278#diff-d801ded3f2d6f3d8598e48e3a2962628

**Comment by snipe** [comment]
(Also you should definitely upgrade your version of PHP as soon as you can. PHP 7.1 is EOL in a month or two, so you're quite far behind.)
