### ISSUE TITLE
Unable to load pre-flight page | Blank Screen

### ISSUE THREAD

**Issue by lmjpixels** [snipe/snipe-it#7406]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
_**Installed everything, hitches along the way with PHP, re-installed with correct PHP version, changed folder permissions to 775 before installing composer, changed .env file as per instructions, however am getting a blank screen when going to the website. When put into debug mode, I'm getting the attached.
[errordebughomepage.pdf](https://github.com/snipe/snipe-it/files/3571785/errordebughomepage.pdf)
**_

**To Reproduce**
1. Go to 'mywebsite where snipe-it is installed'

**Expected behavior**
Load pre-flight screen

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version **Latest**
 - OS: [e.g. Ubuntu, CentOS] **Linux**
 - Web Server: [e.g. Apache, IIS] **Apache / Shared Hosting**
 - PHP Version php7.1-cli

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] OSX
 - Browser [e.g. chrome, safari] Safari

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
**Included as an attachment**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? _**Fresh**_
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **SSH/command via Terminal**
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by lmjpixels** [comment]
**UPDATE**
I'm using a shared hosting server by 1and1. I've changed the database from `localhost` to their database host name `db5000162742.hosting-data.io:3306`. I'm now getting an internal error / 500 screen without any debug info

**Comment by snipe** [comment]
That sounds like a question for your hosting company. Either `php-mysql` isn’t installed, or you’re not using the right database hostname (localhost vs something else).
