### ISSUE TITLE
No historical record on the assets

### ISSUE THREAD

**Issue by pavilonsxx** [snipe/snipe-it#7407]
**Describe the bug**
When I import assets from csv file. When I checkout or checkin or modify the assets, when I look at the assets history, there is no record. Assets created from the program are normally recorded.

**Comment by Diniver** [comment]
Hi @pavilonsxx, 

I am not able to reproduce the problem on 4.7.7 version. Would you be able to give more detiles how to reproduce the problem and what system are you running.

![image](https://user-images.githubusercontent.com/31882138/64267540-8054d800-cf2e-11e9-9a09-5a245dbfad0c.png)

**Comment by pavilonsxx** [comment]
I am using version 4.7.5. My assets after I imported. I checkout for many people. When I reviewed the history of an asset I imported. I didn't see logs.
