### ISSUE TITLE
QR Only Label

### ISSUE THREAD

**Issue by PC-MN** [snipe/snipe-it#7409]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.7.5 build 4137 (g55ee90b25) 
 - OS: Windows Server 2016
 - Web Server: IIS
 - PHP Version: 7.3.8 

Quite simply put, i'd like to print QR labels ONLY. The out of the box labels have whitespace reservations for all the "optional" information which even when unchecked consumes space on my labels. Instead of my 1" x 1" label filling with a QR square it wraps to another page as the barcode and other details seem to be "hidden" instead of removed from the label when it's generated.

**Comment by gilesytheking90** [comment]
I agree. QR code messes up the label layout when printing barcodes. The QR code would be much suited to a separate square label if required.
