### ISSUE TITLE
Unable to get more than 500 results via API

### ISSUE THREAD

**Issue by comisso** [snipe/snipe-it#7410]
**Describe the bug**
This morning I was able to get all my 1000+ items via API, now after the update I'm only able to get 500.

**To Reproduce**
This query will only get 500 results even if the limit is set to 1000000
```
curl --request GET \
  --url 'https://snipeiturl/api/v1/hardware?limit=1000000&offset=0&sort=created_at&order=desc' \
  --header 'accept: application/json' \
  --header 'authorization: Bearer xxxxxxx' \
  --header 'content-type: application/json'
```

**Expected behavior**
Get all the results up to "limit".

**Screenshots**
There is no need.

**Server (please complete the following information):**
 - Snipe-IT Version: v4.7.7 build 4160 (gb8f7cd81e)
 - OS: Ubuntu 18.04.3 LTS
 - Web Server: Apache
 - PHP Version: 7.2.19

**Desktop (please complete the following information):**
Not applicable.

**Smartphone (please complete the following information):**
Not applicable.

**Error Messages**
No errors, just few results than expected.

**Additional context**
I've found this in config/app.php:

```
    |--------------------------------------------------------------------------
    | Result Limit
    |--------------------------------------------------------------------------
    |
    | This value determines the max number of results to return, even if a higher limit
    | is passed in the API request. This is done to prevent server timeouts when
    | custom scripts are requesting 100k assets at a time.
    |
    */

    'max_results' => env('MAX_RESULTS', 500),
```

I suspect this is related to this issue.

Thanks,
Matteo

**Comment by danr12** [comment]
I mean, it literally says that in the update notes: https://github.com/snipe/snipe-it/releases/tag/v4.7.7

...

**Comment by comisso** [comment]
Shame on me for this!
I've read almost anything before posting this issue... but not the release notes! Sh*t!

Thanks for pointing me in the right direction.

Cheers,
Matteo

**Comment by mtridici** [comment]
Dear All, I set the MAX_RESULTS=700 in my .env file, I set the same value in app.php file and in GUI (Admin-> General Settings-> Rows per page), but this value is not relfected in dropdown button of "Assets-> List All" page. It is still showing 500 as maximum value and a list of 500 items. Where is my error? I cleared config using artisan, but nothing changed. Any suggestion about this? I'm using the latest version of Snipeit. Thanks

**Comment by mtridici** [comment]
Additional info about my issue: MAX_RESULTS=700 is reflected correctly on "asset maintenance report" page. The problem still persists on "asset list" page.

**Comment by najirod** [comment]
> Additional info about my issue: MAX_RESULTS=700 is reflected correctly on "asset maintenance report" page. The problem still persists on "asset list" page.

I have the same issue... Did you solve this?

**Comment by Josmansol** [comment]
Im trying to get 1011 users and I only get 500 using Python and postman. Is there anything to get them all available?

**Comment by snipe** [comment]
I have no idea what version of Snipe-IT you're running. Try upgrading to latest on master.

**Comment by Josmansol** [comment]
> I have no idea what version of Snipe-IT you're running. Try upgrading to latest on master.

You can disregard this. I used the pagination and offset to get my full dataset.

**Comment by ghost** [comment]
@Josmansol 
Could you help me by explaining how to make the pagination.

Thanks
Could you help me by explaining how to make the pagination.

Thanks!

**Comment by snipe** [comment]
Hi there - this issue is closed and doesn't seem directly related to your issue. Please create a new issue and fill in all of the questions in the new issue form. (When you reply to old, closed threads, it sends an email notification to everyone who ever participated in it, which can be pretty annoying to have happen on a thread that's been resolved for a while.)

I think you’re looking for the `offset` and `limit` parameters. You can see how these work in the API explorer. https://snipe-it.readme.io/reference/using-the-api-explorer

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/reference/using-the-api-explorer">Using the API Explorer</a></strong></div><div>Snipe-IT is a free, open source IT asset management system. Features include management of assets, users, licenses, accessories, consumables and components, as well as two-factor authentication, LDAP/AD syncing, and asset acceptance confirmation.</div></blockquote>

**Comment by cobacho-ui** [comment]
You just need to create a function and call it as many times as you need in your query, I load the assets 1000 by 1000

= (offset as number) =>
let  
    Source = Json.Document(Web.Contents("https://URL/api/v1/hardware?limit=1000&offset=" & Number.ToText(offset*1000) & "&sort=created_at&order=desc", [Headers=[Authorization="Bearer YOUR KEY", Accept="application/json", #"Content-Type"="application/json"]])),
    rows = Source[rows],
    transformacion= Table.FromRecords(rows)
in
    transformacion
