### ISSUE TITLE
Feature Request: Add new manufacturer and category when adding new model in new asset

### ISSUE THREAD

**Issue by cthulhu-uu** [snipe/snipe-it#7411]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.7.5 build 4137 (g55ee90b25)
 - OS: Windows Server 2012
 - Web Server: IIS 8.5
 - PHP Version: 7.3.9

**Is your feature request related to a problem? Please describe.**
I am trying to add a new asset model when creating a new asset, but the manufacturer and the category don't exist.

**Describe the solution you'd like**
I would like to be able to add a new manufacturer and a new category on the same screen as adding a new asset model.

**Describe alternatives you've considered**
It's not feasible to have to pre-create all manufacturers, categories, etc. prior to adding a new asset model. 

**Additional context**
Please see [linked ](https://imgur.com/9mvb9yv)screenshot.

**Comment by tonsofpcs** [comment]
This is still an issue.  There's no apparent standard workflow to enter an asset unless it is "try entering it and see if it exists, if not go back to items then try entering it and see if manufacturer exists, if not go to manufacturer then work forward" or it's "go to manufacturers and see if it exists - if not, enter it; go to items and see if it exists - if not, enter it; go to assets and create one".   If there is one and I'm missing it, please do correct me.  Thanks!
