### ISSUE TITLE
LDAP Import - Disable Login by Default 

### ISSUE THREAD

**Issue by Shotterke** [snipe/snipe-it#7412]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.7.7 build 4160 (gb8f7cd81e)
 - OS: [e.g. Ubuntu, CentOS]: Windows Server 2016
 - Web Server: [e.g. Apache, IIS]: IIS
 - PHP Version: 7.3.9

**Is your feature request related to a problem? Please describe.**
When I do a LDAP import the "Login Enabled" property is set to true by default.

**Describe the solution you'd like**
Have an option to set the "Login Enabled" property to false by default for new users

**Describe alternatives you've considered**
Have an option in the LDAP settings where you can pick what happens when you import new users (Login enable or disable).

**Comment by Shotterke** [comment]
This is still a relevant issue for me.

**Comment by Shotterke** [comment]
This is still a relevant issue for me.

**Comment by Mynty100** [comment]
Yes, having more control over LDAP and even custom fields would be great.
Or at least a responce to help us understand why this may not be possible.

**Comment by Mynty100** [comment]
Just looking for a response as this would be a welcomed feature. 
Thanking you.

**Comment by drhirn** [comment]
Same problem here too

Snipe-IT v4.9.5
RedHat 7
PHP 7.3
MS Active Directory

**Comment by FG-Lars** [comment]
I'm also looking for this ability

**Comment by itjedi42** [comment]
Same here

**Comment by uberbrady** [comment]
With the latest changes to the 'active' flag, this is **kinda** possible.

What I would do is this:

 1) Pick an LDAP field you literally **never** use. For me, on our AD server, that's the "Notes" field which shows up in the "Phones" tab for some inexplicable reason. In LDAP, that translates to the LDAP field of `info`. (Great job, Microsoft...)
2) Continue to not use that field as you already were not using.
3) But on the few, small number of people that you actually *do* want to be able to log in, set that field to "true" or "1" or "yes" or "active" or anything that seems kinda 'truthy'. (Fun (meaning: not fun) note - '0.0' will not be correctly parsed as 'false'. Most other things should correctly be parsed though).

Let me know if that makes sense to y'all. One thing to keep in mind is that if you do a later LDAP sync it can absolutely toggle users' active (meaning: can-log-in) statuses, so be very wary about how that goes.
