### ISSUE TITLE
Label printing

### ISSUE THREAD

**Issue by nebi52** [snipe/snipe-it#7416]
Hello. Can you tell me which printer, which paper and which setting you use to print the labels?

The paper should be as robust as possible? I would like to stick it on my laptops.

**Comment by gilesytheking90** [comment]
I use dymo labelwriter 450 with the dymo durable labels, but other brands are also compatible. You will have to configure the label settings according to the label size you decide to use.

**Comment by nebi52** [comment]
@gilesytheking90 can you send me screenshot from your settings?

**Comment by rdavis61** [comment]
I am having problems printing a label to the dymo labelwriter 450.  It prints out blank and then on the second label it prints garbage like Lables https, then on third label 1 of 1 9/11/.  A screenshot of your settings would help me too.

**Comment by gilesytheking90** [comment]
Hey guys, sorry for the delayed replay. see attached screen shots for my label settings. I am using the dymo label writer 450 and durable labels 25x54mm

![label-setting](https://user-images.githubusercontent.com/53617393/67192100-ddc3bc00-f3ea-11e9-80f2-17ab609284f5.png)

![label-settings2](https://user-images.githubusercontent.com/53617393/67191839-46f6ff80-f3ea-11e9-9288-77639d0f62e5.jpg)

**Comment by rdavis61** [comment]
@gilesytheking90 answered the question and it worked.  Thank you!

**Comment by fumunda** [comment]
**Edit**  Nevermind. Figured it out thanks to this post #7331 

How in the world did you get the barcode on top?  I cant even get the text from right off the edge of the label unless i use a qrcode or datamatrix.  Then the formatting looks okay. But i cant get the barcode at the top or text centered.  I would *love* to know how you did this, @gilesytheking90 

Thanks!
