### ISSUE TITLE
The link in e-mail alert is wrong

### ISSUE THREAD

**Issue by kolob4all** [snipe/snipe-it#7417]
When I receive e-mail alert with License Expiration the link in the body is broken.
The Link points to http://localhost/xxx.xxx.com/licenses/4 instead of http://xxx.xxx.com/licenses/4

Version v4.7.6 - build 4143 (master) on CentOS 7
Mail client is Outlook on Windows 10

**Comment by snipe** [comment]
Make sure you have a true url set in your env file for APP_URL, including the http/https protocol

**Comment by kolob4all** [comment]
Updated .env file and added https to the URL. When I run /usr/bin/php /var/www/snipe-it/artisan snipeit:inventory-alerts it doesn't send new alert. How can I recreate the alert?

**Comment by snipe** [comment]
Are you sure there are alerts that *should* fire with that alert?

**Comment by kolob4all** [comment]
Well, I created a test license, that expires in couple days. How many times alert will be sent for the specific license?
