### ISSUE TITLE
Create Asset Tag with different prefix and auto number

### ISSUE THREAD

**Issue by williamgh2019** [snipe/snipe-it#7422]
Here my current problem:

I use Excel to generate auto asset tag number with different prefix as below:

DT10001=Desktop
DT10002
DT10003
.
.
.

LT10001=Laptop
LT10002
LT10003
.
.
.

How could I create it with auto increasement number but with optional prefix like this?

**Comment by pavilonsxx** [comment]
I have same issue?

**Comment by Go2ClassPoorYorick** [comment]
Duplicate of #3286?

Still would be nice.

**Comment by pavilonsxx** [comment]
The issue has not been resolved yet!!

**Comment by 02ms05** [comment]
Same situation here, different categories - different prefix with different numbers. 
Seems like a simple feature, but  it's not made yet ? Or is it ?

**Comment by 02ms05** [comment]
Hope this can be revisited once again

**Comment by achuet** [comment]
Any updates on this feature please

**Comment by snipe** [comment]
Not at this time.
