### ISSUE TITLE
localization error in dates (Date format)

### ISSUE THREAD

**Issue by UserGoodtm** [snipe/snipe-it#7426]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
localization error in dates (Date format)

**Expected behavior**
The program is foreign. In existing fields (attributes) of assets, there are date (date of purchase, etc.). I use the Russian language and Russian date format DD.MM.YYYY. In existing fields that use dates, the date format shows correctly for me - DD.MM.YYYY. If you create Custom Fields with dates, date format turns out wrong for me YYYY-MM-DD. In the end, in the program I can see two date format as correct for me - DD.MM.YYYY and wrong for me YYYY-MM-DD. Is it possible, when using national date formats, to change them in all existing fields where possible?

The program itself uses several options (formats) of dates and times. Why is this done? Please make one option dates, default (from the manufacturer) and national date formats.

**Screenshots**
![11](https://user-images.githubusercontent.com/48224568/64548842-22622f00-d338-11e9-810f-32e051c346fd.jpg)
![12](https://user-images.githubusercontent.com/48224568/64550092-cbaa2480-d33a-11e9-8482-d921be0837b3.jpg)

**Server (please complete the following information):**
 - Snipe-IT Version  v4.7.7
 - OS: CentOS
 - Web Server: Apache
 - PHP Version 7.3.7

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version 76.0.3809.132

**Error Messages**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
(you can't change the language of the system)

**Additional context**
- Is this  upgrade
- What method you used to install Snipe-IT (install.sh)

There were similar cases from other users, but they were closed after the time!

**Comment by UserGoodtm** [comment]
The problem is urgent. Probably few people use the system in Russian (or in another language other than English)

**Comment by OneRFeris** [comment]
This is still relevant, and affects v4.8.0 - build 4186. 
Affects English users too.
