### ISSUE TITLE
SQLSTATE[42S02]: Base table or view not found

### ISSUE THREAD

**Issue by mrcuong** [snipe/snipe-it#743]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit_laravel.tt_settings' doesn't exist (SQL: select * from `tt_settings` where `tt_settings`.`id` = 1 limit 1) (View: /var/www/snipeit/app/views/backend/layouts/default.blade.php) (View: /var/www/snipeit/app/views/backend/layouts/default.blade.php) 
ASK:
- I need create DB in MySql( infor the same file DB file snipe-IT) ?

**Comment by snipe** [comment]
I don't really understand what you're asking here.
