### ISSUE TITLE
Depreciation reports for custom date instead current date

### ISSUE THREAD

**Issue by harsha1994** [snipe/snipe-it#7432]
**Server :**
 - Snipe-IT Version : v4.7.6 build 4143 (g3dc2cc9f2) 
 - OS: Windows
 - Web Server: Apache/2.4.39 (Win64)
 - PHP Version  7.2.21

**Is your feature request related to a problem? Please describe.**
_I need depreciation reports according to custom date instead to current date. Now snipe-it provide depreciation reports up to current system date._

**Describe the solution you'd like**
_If can add date picker to custom report generate page or depreciation report page, then we can select custom date range and can generate reports according to the custom date range._

**Comment by ISNL-PimP** [comment]
I'd like this to be reopened. We'd also like this as a feature

**Comment by tmsvl** [comment]
I also believe this would be very interesting!
