### ISSUE TITLE
Asset name editable by non qualified users

### ISSUE THREAD

**Issue by pfunk1978** [snipe/snipe-it#7438]
#### Expected Behavior (or desired behavior if a feature request)

As an administrator I should be able to allow a group to checkout a unit but restrict the users in the group from editing the properties of the unit.

-----

#### Actual Behavior

Users with only the Asset: view, checkin, and checkout permissions are able to edit the asset name. This can, and has, put us in the position of loosing a unit as now it is mis-labled.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
Fresh
- Version of Snipe-IT you're running
v4.7.5 build 4137 (g55ee90b25)
- Version of MySQL/MariaDB you're running
5
- What OS and web server you're running Snipe-IT on
Linux, Nginx
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
docker

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by tomholovis** [comment]
FYI: the process to recreate this feature is as follows:

- Create a user with check-in/check-out and view permissions
- Check out a device. In the check out screen the user has the option to change the name of the asset.

**Comment by pfunk1978** [comment]
@tomholovis

What you described is the bahavior that I don't want. Users without edit permissions should not be able to edit an asset name

**Comment by tomholovis** [comment]
Great, I just wanted to provide basic instructions for how to re-produce the situation. I think the idea is that you could check out a laptop and re-name it to "Dave's laptop" at the same time. But I understand that this might not be useful for everyone. Personally I don't actually use the asset name field.
