### ISSUE TITLE
Issue Generating API Keys / migrating 

### ISSUE THREAD

**Issue by AW-IT** [snipe/snipe-it#7440]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When attempting to generate an API key, I receive the error below. I've seen a resolution of **php artisan migrate**, but then I was unable to access any of my assets or other information...db issues seemingly:

An Error has occured! SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit_data.oauth_personal_access_clients' doesn't exist (SQL: select * from `oauth_personal_access_clients` order by `id` desc limit 1)

**To Reproduce**
1. Go to 'Manage API Keys'
2. Click on 'Create'
3. Enter name for Key
4. Create

**Expected behavior**
an API key should be generated

**Screenshots**
![image](https://user-images.githubusercontent.com/55441236/65037376-8e85f980-d91b-11e9-9997-5c5c8300d75e.png)

**Server (please complete the following information):**
 - Snipe-IT Version v4.6.6 build 3926 (g1a10aa0dd)
 - OS: [CentOS 7.x]
 - Web Server: Apache
 - PHP Version PHP 7.3.9 (cli) (built: Aug 27 2019 22:52:39) ( NTS )

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Error Messages**
An Error has occured! SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit_data.oauth_personal_access_clients' doesn't exist (SQL: select * from `oauth_personal_access_clients` order by `id` desc limit 1)

**Additional context**
- Is this a fresh install or an upgrade? Upgrade, I guess? Existing instance, but unable to create API 
- What method you used to install Snipe-IT - **not 100% sure, installed by other admin previously**
- No information edited directly in DB

Thanks!

**Comment by AW-IT** [comment]
I resolved this issue on my own - please ignore

**Comment by omaisali** [comment]
@AW-IT please guide how you solved this
