### ISSUE TITLE
Localisation: "Thanks," is not part of translation for checkout-/checkin-email

### ISSUE THREAD

**Issue by pfenning-IT-OPs** [snipe/snipe-it#7442]
#### Please confirm you have done the following before posting your bug report:

- [ No] I have enabled debug mode 
- [ Yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

"Thanks," is not part of the translation for checkout-/checkin-emails which users receive, for example on checkout of an asset.

While all included fields pull their respective localisation, "Thanks," is added as plain text in the corresponding *blade.php file in /var/www/snipeit/resources/views/notifications/markdown.

We work around this issue by deleting this text after every update and would love to see a fix for this.

Thank you!

**To Reproduce**
- see above

**Expected behavior**
"Thanks," is made part of the translation to other languages.

**Screenshots**
-

**Server (please complete the following information):**
 - Snipe-IT Version 4.7.7 
 - OS: Debian
 - Web Server: Apache
 - PHP: 7.3.9

**Desktop (please complete the following information):**
 - OS: Windows 10 1903
 - Browser: Firefox 
 - Version: 69

**Smartphone (please complete the following information):**
 - Device: -
 - OS: -
 - Browser -
 - Version -

**Error Messages**
-

**Additional context**
-

**Comment by matmair** [comment]
This error is still present in v4.9.2 build 4352
