### ISSUE TITLE
Categories Missing

### ISSUE THREAD

**Issue by e-latt** [snipe/snipe-it#7443]
#### Expected Behavior (or desired behavior if a feature request)

Categories should be listed under Settings>Categories and when creating/editing an asset. 
-----

#### Actual Behavior

Settings>Categories is empty and no categories are available from the drop-down. Existing categories are listed on existing assets.
-----

#### Please confirm you have done the following before posting your bug report:

- [ X] I have enabled debug mode 
- [ X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? - Fresh install
- Version of Snipe-IT you're running - 4.7.7
- Version of PHP you're running - 7.2.19
- Version of MySQL/MariaDB you're running - 
- What OS and web server you're running Snipe-IT on - ubuntu server 19.04 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - recomended git install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - 

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'category_id' in 'field list' (SQL: update `licenses` set `order_number` = , `notes` = , `updated_at` = 2019-09-17 10:54:57, `license_name` = , `license_email` = , `purchase_order` = , `maintained` = 0, `reassignable` = 1, `category_id` = 35 where `id` = 45)
--
 

- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - After attempting to create missing category, got "category already exisits" message, but it was listed in the drop down when editing a license.

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - no
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation - this started after a clean install and migrating our old backup from 4.1.x over.
- Indicate whether or not you've manually edited any data directly in the database - no

**Comment by snipe** [comment]
Resolved offline :)

**Comment by twsit988** [comment]
I created a Category and set the Type to Asset, however when I try to create an Asset, the Category drop down is not there. Please advise how this was fixed?

**Comment by aldoprogrammer** [comment]
@twsit988 same here, I also got nothing after creating the category

**Comment by aldoprogrammer** [comment]
@twsit988 maybe you ever comment the code about component, license etc to make them not showing up from the web browser? if yes, then uncomment it, cs that is causing the category does not want to show up
