### ISSUE TITLE
Pre-Flight User Loop

### ISSUE THREAD

**Issue by arretx** [snipe/snipe-it#7446]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Stuck at step 3 of the pre-flight.  User will not create.

**To Reproduce**
Run Pre-Flight, step 3.

**Expected behavior**
Move to step 4.

**Screenshots**
N/A

**Server (please complete the following information):**
 - 5.5.47 
 - OS: Ubuntu 16.04
 - Web Server: Apache2
 - PHP Version: 7.3.9 

**Desktop (please complete the following information):**
 - OS: Mojave
 - Browser: Chrome
 - Version: Version 76.0.3809.132 (Official Build) (64-bit)

**Error Messages**
No debug errors in laravel.log.  No errors showing in console.  Nothing recorded to apache error log for virtual host.

**Additional context**
Fresh install.
Apache2 and Ubuntu 16.04
Installed via manual installation.
Along the way I had to install a few dependencies as suggested by the guide, but nothing out of the ordinary.  I had to run the migrate command to finalize database tables for oauth.  No database edits have occurred.

I can't make sense of why I'm stuck in a loop.

**Comment by ajsy** [comment]
try to clear your browser's cache
if not working, check this https://github.com/snipe/snipe-it/issues/5128

**Comment by regjonh** [comment]
https://github.com/snipe/snipe-it/issues/4530#issuecomment-584852623

**Comment by regjonh** [comment]
Your fix might be here: https://github.com/snipe/snipe-it/issues/4530#issuecomment-584852623
