### ISSUE TITLE
Can not import assets.

### ISSUE THREAD

**Issue by Skrrrr8** [snipe/snipe-it#7447]
#### Expected Behavior (or desired behavior if a feature request)

Import new assets from CSV file
-----

#### Actual Behavior

"Processing...." Nothing happens.

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh
- Version of Snipe-IT you're running 4.7.7
- Version of PHP you're running 7.3.9
- Version of MySQL/MariaDB you're running MariaDB 10.2.0.5693
- What OS and web server you're running Snipe-IT on Windows Server 2016 IIS Version 10
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Manual Install
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error Import, Upload CSV Hit Import. 
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. 
Request URL:http://10.17.1.13/api/v1/imports/process/9
Request method:POST
Remote address:10.17.1.13:80
Status code:
500

- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
 N/a
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. 

Manually added assets and consumables.

- Indicate whether or not you've manually edited any data directly in the database
No

![2019-09-18 15_37_09-](https://user-images.githubusercontent.com/55510738/65180204-54574d80-da2a-11e9-9d86-f9e4db49ba9e.png)

**Comment by snipe** [comment]
We'd need output from the app log in order to be able to see what's going on here.

**Comment by Skrrrr8** [comment]
Attached is the log file from C:\inetpub\wwwroot\snipe-it\storage\logs Not sure if this is the right log or not. Let me know if a different file is needed.

[laravel.log](https://github.com/snipe/snipe-it/files/3630967/laravel.log)

**Comment by Skrrrr8** [comment]
Closing this thread. SMTP needed to be setup in the .env config file.
