### ISSUE TITLE
Do not run Docker image as root

### ISSUE THREAD

**Issue by verwilst** [snipe/snipe-it#7449]
Please set a non-zero numeric `USER` in the Dockerfile so it can be started on Podsecuritypolicy-enabled kubernetes clusters.

**Comment by verwilst** [comment]
"Error: container has runAsNonRoot and image will run as root"

**Comment by Anilreddy999** [comment]
I am facing same issue.
"Error: container has runAsNonRoot and image will run as root"

Please set a non-zero numeric USER in the Dockerfile so it can be started on Podsecuritypolicy-enabled kubernetes clusters.
