### ISSUE TITLE
Possible to add different username format (First Name Last Initial)?

### ISSUE THREAD

**Issue by shooln** [snipe/snipe-it#7453]
#### Expected Behavior (or desired behavior if a feature request)

(what you expect to happen goes here)

Our company uses a different username format. First Name and last initial. Example 
for a name "John Doe" the username would be johnd@companyname.com. Would this be possible to implement or something we can setup manually.  Thank you!

#### Actual Behavior

(what actually happens goes here)

only options that seem to be available are alternates of the above! 

#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?
 Fresh Install 
- Version of Snipe-IT you're running
 v4.7.5 - build 4118
- Version of PHP you're running
 PHP 7.1.30
- Version of MySQL/MariaDB you're running
 5.5.60-MariaDB
- What OS and web server you're running Snipe-IT on
 CentOs 7.2.1511 (Core), Apache 2.4.6
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
 Install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
 N/A
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error
 N/A
- If a stacktrace is provided in the error, include that too.
 N/A
- Any errors that appear in your browser's error console.
 N/A
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
 N/A
- Include any additional information you can find in `storage/logs` and your webserver's logs.
 N/A
- Include what you've done so far in the installation, and if you got any error messages along the way.
 N/A
- Indicate whether or not you've manually edited any data directly in the database
 N/A
Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by nbwpuk** [comment]
Did this ever happen? This is the same format a client uses, so would be great to be able to select FirstNameSurnameInitial@
Is this possible to set in config somewhere?
