### ISSUE TITLE
Upgrade from Version v4.1.14 - build 3416 (master) failed with 

### ISSUE THREAD

**Issue by biroistvangmailcom** [snipe/snipe-it#7457]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

 - after i run php upgrade.php from command line snipeit starts the upgrade process, after it finishes it tells i have to clear my browser cache , everithing went well.

**installation messages **
Step 8: Caching routes and config:
Configuration cache cleared!
Configuration cached successfully!
Route cache cleared!
Routes cached successfully!
Step 9: Taking application out of maintenance mode:
Application is now live.
FINISHED! Clear your browser cookies and re-login to use :
your upgraded Snipe-IT.

**Server (please complete the following information):**
 - Snipe-IT Version v4.1.14 - build 3416 (master) 
 - OS: Ubuntu 18.04.3 LTS
 - Web Server: Apache
 - PHP Version 7.2.19 Zend Engine v3.2.0

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux Desktop 18 
 - Browser chromium 76., firefox 69.

**Additional context**
- Upgrade from  Version v4.1.14 - build 3416 (master) 
- Linux Ubuntu 18.04 LTS
- to install Snipe-IT i used install.sh , to upgrade i used php upgrade.pph with user www-data

**Error Messages**
when i open the page i see an empty website , no error in browser window(firefox) and http 500 error in chromium. 
in /var/log/apache2/error.log i see this error:
[Tue Sep 24 07:17:41.691591 2019] [mpm_prefork:notice] [pid 1200] AH00169: caught SIGTERM, shutting down
[Tue Sep 24 07:17:41.883429 2019] [mpm_prefork:notice] [pid 24267] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Tue Sep 24 07:17:41.883508 2019] [core:notice] [pid 24267] AH00094: Command line: '/usr/sbin/apache2'
[Tue Sep 24 07:17:45.233829 2019] [:error] [pid 24275] [client 192.168.6.26:54110] PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/snipeit/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 24
[Tue Sep 24 07:17:45.233895 2019] [:error] [pid 24275] [client 192.168.6.26:54110] PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0
[Tue Sep 24 07:17:45.234620 2019] [:error] [pid 24275] [client 192.168.6.26:54110] PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/snipeit/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 24
[Tue Sep 24 07:17:45.234641 2019] [:error] [pid 24275] [client 192.168.6.26:54110] PHP Fatal error:  Exception thrown without a stack frame in Unknown on line 0

 - if i open that file , in the 24 line i see :
public function __construct($dsn, $user = null, $password = null, ?array $options = null)

**error messages from storage/logs/lavarel.log last 100 lines**
#27 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(55): Symfony\\Component\\HttpFoundation\\Response->__construct(Object(Illuminate\\View\\View), 500, Array)
#28 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\Routing\\ResponseFactory->make(Object(Illuminate\\View\\View), 500, Array)
#29 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(403): Illuminate\\Routing\\ResponseFactory->view('errors::500', Array, 500, Array)
#30 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(295): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException(Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#31 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(187): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#32 /var/www/snipeit/app/Exceptions/Handler.php(93): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#33 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(83): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#34 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(57): Illuminate\\Routing\\Pipeline->handleException(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#35 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#37 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#38 /var/www/snipeit/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#39 {main}
"} 
[2019-09-24 09:28:13] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/www/snipeit/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:24
Stack trace:
#0 /var/www/snipeit/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/snipei...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Doctrine\\DBAL\\D...')
#2 [internal function]: spl_autoload_call('Doctrine\\DBAL\\D...')
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(63): class_exists('Doctrine\\DBAL\\D...')
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(43): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=loca...', 'snipeit', '5Wsp8s4aYGxLfkp...', Array)
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(183): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#7 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(915): call_user_func(Object(Closure))
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(940): Illuminate\Database\Connection->getPdo()
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(399): Illuminate\Database\Connection->getReadPdo()
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(325): Illuminate\Database\Connection->getPdoForSelect(true)
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('select * from i...', Array)
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\Database\Connection->run('select * from i...', Array, Object(Closure))
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(18): Illuminate\Database\Connection->select('select * from i...', Array)
#16 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\Database\Schema\MySqlBuilder->hasTable('settings')
#17 /var/www/snipeit/app/Models/Setting.php(56): Illuminate\Support\Facades\Facade::__callStatic('hasTable', Array)
#18 /var/www/snipeit/app/Providers/SettingsServiceProvider.php(34): App\Models\Setting::getSettings()
#19 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesEvents.php(164): App\Providers\SettingsServiceProvider->App\Providers\{closure}(Object(Illuminate\View\View))
#20 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(347): Illuminate\View\Factory->Illuminate\View\Concerns\{closure}('composing: erro...', Array)
#21 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(200): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('composing: erro...', Array)
#22 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesEvents.php(179): Illuminate\Events\Dispatcher->dispatch('composing: erro...', Array)
#23 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(118): Illuminate\View\Factory->callComposer(Object(Illuminate\View\View))
#24 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(85): Illuminate\View\View->renderContents()
#25 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\View\View->render()
#26 /var/www/snipeit/vendor/symfony/http-foundation/Response.php(206): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#27 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(55): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 500, Array)
#28 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 500, Array)
#29 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(403): Illuminate\Routing\ResponseFactory->view('errors::500', Array, 500, Array)
#30 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(295): Illuminate\Foundation\Exceptions\Handler->renderHttpException(Object(Symfony\Component\HttpKernel\Exception\HttpException))
#31 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(187): Illuminate\Foundation\Exceptions\Handler->prepareResponse(Object(Illuminate\Http\Request), Object(Symfony\Component\HttpKernel\Exception\HttpException))
#32 /var/www/snipeit/app/Exceptions/Handler.php(93): Illuminate\Foundation\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#33 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(326): App\Exceptions\Handler->render(Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#34 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(124): Illuminate\Foundation\Http\Kernel->renderException(Object(Illuminate\Http\Request), Object(Symfony\Component\Debug\Exception\FatalThrowableError))
#35 /var/www/snipeit/public/index.php(58): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#36 {main}  
[2019-09-24 09:28:13] production.ERROR: Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE) at /var/www/snipeit/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:24)
[stacktrace]
#0 /var/www/snipeit/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/var/www/snipei...')
#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('Doctrine\\\\DBAL\\\\D...')
#2 [internal function]: spl_autoload_call('Doctrine\\\\DBAL\\\\D...')
#3 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(63): class_exists('Doctrine\\\\DBAL\\\\D...')
#4 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(43): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:host=loca...', 'snipeit', '5Wsp8s4aYGxLfkp...', Array)
#5 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\\Database\\Connectors\\Connector->createConnection('mysql:host=loca...', Array, Array)
#6 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(183): Illuminate\\Database\\Connectors\\MySqlConnector->connect(Array)
#7 [internal function]: Illuminate\\Database\\Connectors\\ConnectionFactory->Illuminate\\Database\\Connectors\\{closure}()
#8 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(915): call_user_func(Object(Closure))
#9 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(940): Illuminate\\Database\\Connection->getPdo()
#10 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(399): Illuminate\\Database\\Connection->getReadPdo()
#11 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(325): Illuminate\\Database\\Connection->getPdoForSelect(true)
#12 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\\Database\\Connection->Illuminate\\Database\\{closure}('select * from i...', Array)
#13 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('select * from i...', Array, Object(Closure))
#14 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Connection.php(333): Illuminate\\Database\\Connection->run('select * from i...', Array, Object(Closure))
#15 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Database/Schema/MySqlBuilder.php(18): Illuminate\\Database\\Connection->select('select * from i...', Array)
#16 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Illuminate\\Database\\Schema\\MySqlBuilder->hasTable('settings')
#17 /var/www/snipeit/app/Models/Setting.php(56): Illuminate\\Support\\Facades\\Facade::__callStatic('hasTable', Array)
#18 /var/www/snipeit/app/Providers/SettingsServiceProvider.php(34): App\\Models\\Setting::getSettings()
#19 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesEvents.php(164): App\\Providers\\SettingsServiceProvider->App\\Providers\\{closure}(Object(Illuminate\\View\\View))
#20 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(347): Illuminate\\View\\Factory->Illuminate\\View\\Concerns\\{closure}('composing: erro...', Array)
#21 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(200): Illuminate\\Events\\Dispatcher->Illuminate\\Events\\{closure}('composing: erro...', Array)
#22 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/Concerns/ManagesEvents.php(179): Illuminate\\Events\\Dispatcher->dispatch('composing: erro...', Array)
#23 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(118): Illuminate\\View\\Factory->callComposer(Object(Illuminate\\View\\View))
#24 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/View/View.php(85): Illuminate\\View\\View->renderContents()
#25 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\\View\\View->render()
#26 /var/www/snipeit/vendor/symfony/http-foundation/Response.php(206): Illuminate\\Http\\Response->setContent(Object(Illuminate\\View\\View))
#27 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(55): Symfony\\Component\\HttpFoundation\\Response->__construct(Object(Illuminate\\View\\View), 500, Array)
#28 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\Routing\\ResponseFactory->make(Object(Illuminate\\View\\View), 500, Array)
#29 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(403): Illuminate\\Routing\\ResponseFactory->view('errors::500', Array, 500, Array)
#30 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(295): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException(Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#31 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(187): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\HttpException))
#32 /var/www/snipeit/app/Exceptions/Handler.php(93): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#33 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(326): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#34 /var/www/snipeit/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(124): Illuminate\\Foundation\\Http\\Kernel->renderException(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\Debug\\Exception\\FatalThrowableError))
#35 /var/www/snipeit/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#36 {main}
"} 
[2019-09-24 09:28:13] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Exception thrown without a stack frame in Unknown:0
Stack trace:
#0 {main}  
[2019-09-24 09:28:13] production.ERROR: Exception thrown without a stack frame {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 16): Exception thrown without a stack frame at Unknown:0)
[stacktrace]
#0 {main}
"}

**Comment by snipe** [comment]
That looks like a PHP version issue. 
https://snipe-it.readme.io/docs/installation-issues#section-php-version-issues

Are you sure you're running PHP 7.2.19 on both the web server and the command line?

**Comment by biroistvangmailcom** [comment]
exactly was that i just adjusted php version on both webserver and command line , thank you for the hint!!!
