### ISSUE TITLE
command line import fails

### ISSUE THREAD

**Issue by StiM-git** [snipe/snipe-it#7459]
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When running command line import I get the following error: {"Asset \"\"":{"model_id":["The model id field is required."]}}. 

The csv is custom asset report from our old snipe-it server so I know all the headers are correct. I have looked through the data to see if there are any assets that have blank cells under the required mode fields but they are all populated and correct. It also says there are 758 assets and there are 759 rows (with header) so that looks good too.

**Server (please complete the following information):**
 - Snipe-IT Version: 4.7.7
 - OS: [Windows Server 2016]
 - Web Server: IIS
 - PHP Version: 7.3.1

**Comment by yeahlich** [comment]
![深度截图_选择区域_20190927160314](https://user-images.githubusercontent.com/19248774/65752874-531bd400-e140-11e9-9358-18e795dfd479.png)
+1  
need help
