### ISSUE TITLE
File Upload for People

### ISSUE THREAD

**Issue by DanielNemanic** [snipe/snipe-it#746]
Please add the ability to upload File for People.
We will use the People Overview for signatures. 
After signing the File should be uploaded to the user!

Thanks

**Comment by madd15** [comment]
File uploads to users will be in 2.0

**Comment by snipe** [comment]
![skills](https://cloud.githubusercontent.com/assets/197404/8663152/8c4f7a0e-297c-11e5-84ec-af28225406d4.gif)
