### ISSUE TITLE
E-Mail views won't change after editing php files

### ISSUE THREAD

**Issue by erenustun** [snipe/snipe-it#7468]
- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
At `resources/views/emails/` I changed the `checkin-asset.blade.php` & `layouts/default.blade.php`. I added text and removed couple of `td`'s but the email looks still like the default email with padding, etc.

I also did a `php artisan config:clear && php artisan config:cache` after editing the files but still no changes.

**To Reproduce**
1. Go to `resources/views/emails`
2. Remove padding in `layouts/default.blade.php`
3. Check if email looks different

**Expected behavior**
The emails should look like in the custom php files.

**Server (please complete the following information):**
 - Snipe-IT 4.7.4 
 - OS: Windows 10
 - Web Server: Apache (WAMP dev environment)
 - PHP 7.3.9

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by erenustun** [comment]
I deleted all files in `storage/framework/cache` & `storage/framework/views` and it's still not updating according to the custom php files.

**Comment by erenustun** [comment]
bump

**Comment by ajsy** [comment]
[Clearing the Config Cache](https://snipe-it.readme.io/docs/clearing-the-config-cache)

php artisan config:clear
php artisan config:cache
php artisan cache:clear
php artisan view:clear
php artisan route:clear

**Comment by erenustun** [comment]
@ajsy Hi! Thanks for the commands.

So I re-edited the `checkin-asset.blade.php`. Executed all commands successfully and then checked an asset out. Unfortunately the emails are still the same as the original `checkin-asset.blade.php`

I will now try to find out more using the debug function... Thanks anyway, didn't know about the last 3 commands! :-)

**Comment by erenustun** [comment]
**FOUND IT!**

I used the debugger and checked the `views` tab.

Turns out the styling is in:
`\resources\views\vendor\mail\html\themes\default.css`

**Comment by dtosun61** [comment]
Hello,
Hoe did you solve this? 
I changed the checkin-asset.blade.php and then clear all cache, but the email looks still like the default email.

**Comment by thasleemnazeer** [comment]
Hi I'm not familiar with scripts. How to add the asset-assigned user's name to the mail ?. Which script we have to add in "checkout-asset.blade.php". Please help.

**Comment by mdenkert** [comment]
Hello, is there a way to customize the email for a hosted instance?

**Comment by snipe** [comment]
@mdenkert Not currently, as these things are pretty complicated. If you’re hosted with us, you can tell us what you’re looking for and if it makes sense for the product as a whole, we might build it. We get this request a lot, but it’s unfortunately a lot more complicated than it seems. If you’d like to share more of your thoughts and you’re hosted with us, please do email us at support@snipeitapp.com. I cannot promise that what you ask will be implemented, but we’re always listening, there as we are here.
