### ISSUE TITLE
Server Error: 500 (Internal Server Error)

### ISSUE THREAD

**Issue by mrcuong** [snipe/snipe-it#747]
I install snipe-it, when access link error "Server Error: 500 (Internal Server Error)" ?? help me? thanks!

**Comment by snipe** [comment]
Please see the Getting Help documentation. http://snipeitapp.com/documentation/getting-help/

**Comment by grancardy** [comment]
Hi everybody!

I have the same problem. I´ve checked the documentation with the common issues, but I still get the same error.

I checked .htaccess (writing junk), apache2.conf (AllowOverride All) , and the file start.php (checking the array 'local' with the name of the local host) in the bootstrap folder.

During the installation everything gone fine.

Any Idea?

regards.

**Comment by snipe** [comment]
@grancardy Please see the Getting Help documentation. http://snipeitapp.com/documentation/getting-help/

**Comment by grancardy** [comment]
Hi @snipe 

I´ve installed Snipe-it with this script ; https://github.com/GR360RY/snipeit-ansible

The server is fresh Ubuntu 14.04 installation in a Virtual infrastructure.

During the installation I dind´t get any error message.


Next exception 'ErrorException' with message 'Database [] not configured. (View: /opt/snipe-it/app/views/backend/layouts/default.blade.php) (View: /opt/snipe-it/app/views/backend/layouts/default.blade.php)' in $
Stack trace:
#0 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(41): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/opt/snipe-it/a...', Array)
#2 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(134): Illuminate\View\Engines\CompilerEngine->get('/opt/snipe-it/a...', Array)
#3 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(102): Illuminate\View\View->getContents()
#4 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illuminate\View\View->renderContents()
#5 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Http/Response.php(43): Illuminate\View\View->render()
#6 /opt/snipe-it/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1498): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1031): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(777): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(747): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /opt/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /opt/snipe-it/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(643): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /opt/snipe-it/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []



Regards.

**Comment by snipe** [comment]
Unfortunately, we don't maintain that ansible installer. You should contact the maintainer.

**Comment by snipe** [comment]
(It does look like it can't find a database configuration file, but beyond that, I'm not sure what else the ansible installer might be doing.)

**Comment by grancardy** [comment]
Thanks @snipe I´ll contact with the developer.
Regards.

**Comment by diclophis** [comment]
I think some degree in the breakage is related to this issue: https://github.com/GR360RY/snipeit-ansible/issues/19

changes in the artisan setup script seem to be causing a breaking change in ansible scripts.
