### ISSUE TITLE
Powershell API - Get-Asset

### ISSUE THREAD

**Issue by mcbmoreno** [snipe/snipe-it#7470]
Snipe-IT version | v4.6.5 build 3897 (gff824ec4d)
PHP Version | 7.2.10
Laravel Version | 5.4.35
Installed on Windows Server 2016 Standard

When running Get-Asset from the Powershell module SnipeitPS it will sometimes return nothing but most of the time it will return some assets (around 20-50) but never all of the assets in the database.  We have about 1000 assets in the database.

I tried the following but still doesn't work:
Get-Asset -url "snipeit.domain.com" -apikey "api key" -limit 1000

Thanks.

**Comment by shinjijai** [comment]
I wrote my own functions in PS that interacts with SnipeIT's API and don't have this issue. Shouldn't this be on [SnipeitPS issue tracker](https://github.com/snazy2000/SnipeitPS/issues) instead of here?

**Comment by mcbmoreno** [comment]
shinjijai could you share that script?

**Comment by shinjijai** [comment]
> shinjijai could you share that script?

I've dumped it [here](https://gist.github.com/shinjijai/5c51fb33d898b5606cf27530f5e6d1c5). Please note that this was created for my use, so I can't guarantee that it'll work for your environment, and there's not much documentation on this. If you want to limit the results (all my results asks for 100000), you can easily update the functions to do so. 

The function you're looking for to replicate the `Get-Asset` is `Get-SIAll -TableName "hardware" -APIToken $APIToken`.

**Comment by mcbmoreno** [comment]
Thanks a lot shinjijai

**Comment by mcbmoreno** [comment]
Any idea why I might be getting this?

Invoke-WebRequest : The remote server returned an error: (500) Internal Server Error.
At C:\scripts\production\SnipeIt.ps1:75 char:9
+         Invoke-WebRequest @PostParams
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

I updated [string]$URI = "http://snipeit.mydomain.org/api/v1/$TableName`?limit=100000&sort=id&order=asc" 

Did a  import-module .\SnipeIt.ps1 -force  

Then tried running:
Get-SIAll -TableName "hardware" -APIToken "actual token from C:\inetpub\wwwroot\Snipe-IT\API directory"

**Comment by shinjijai** [comment]
Everything looks good, have you try this in cURL? 

`curl --request GET \
  --url 'https://snipeit.company.com/api/v1/hardware?limit=10&offset=0&sort=created_at&order=desc' \
  --header 'accept: application/json' \
  --header 'authorization: Bearer LONGAPISTRING' \
  --header 'content-type: application/json'`

And see if you're getting 500 errors?

**Comment by mcbmoreno** [comment]
Sorry for delay. 

Ok it looks like I only get the error when I use TableName "hardware".  Any ideas on why hardware wouldn't work?

When I set the TableName to any of the other options I am getting results.  Only thing is that the results only contain one record.  It is grabbing the correct amount of rows in the Content but I don't know how to reference each returned row in the content?  

Here is an example of the results for users:

 StatusCode        : 200
StatusDescription : OK
Content           : {"total":1499,"rows":[{"id":1,"avatar":"\/\/gravatar.com\/avatar\/96eec672839e7529160f78333b2500cd","name":"Global Admin","first_name":"Global","last_name":"Admin","username":"admin","employee_num":""...
RawContent        : HTTP/1.1 200 OK
                    X-Content-Type-Options: nosniff
                    Referrer-Policy: same-origin
                    X-XSS-Protection: 1;mode=block
                    X-Frame-Options: SAMEORIGIN
                    Content-Length: 1421313
                    Cache-Control: no-cache, private
                    ...
Forms             : {}
Headers           : {[X-Content-Type-Options, nosniff], [Referrer-Policy, same-origin], [X-XSS-Protection, 1;mode=block], [X-Frame-Options, SAMEORIGIN]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : System.__ComObject
RawContentLength  : 1421313

**Comment by shinjijai** [comment]
Lets say you do this:

`$Results = Get-SIAll -TableName "users" -APIToken $APIToken"`

Once you get the `$Results`, convert the Content of `$Results` from JSON by doing something like this.

`$Data = $Results.Content | ConvertFrom-JSON`

Now you'll have an object that you can work with. 

As for why it doesn't work on the `hardware` table, I'm not sure, as it works for my installation.
