### ISSUE TITLE
LDAP login not searching for user dn

### ISSUE THREAD

**Issue by rabidmullet** [snipe/snipe-it#7471]
#### Please confirm you have done the following before posting your bug report:

- [ x] I have enabled debug mode 
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
 Trying to bind using the username entered plus the dn (uername+basedn). Openldap logs show there is never a search to find the dn for the uid. 

**To Reproduce**
Login using the "Test LDAP Login" on the Update LDAP/AD setting page

**Expected behavior**
1. sinpe-it binds to openldap using service account (works)
2. search basedn for uid and get dn for user account (never happens)
3. bind with user's dn (the bind is attempted with uid+basedbn which doesn't exist)

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version: v4.7.7 build 4160
 - OS: Centos 7
 - Web Server: Apache
 - PHP Version: 7.3.10
- Openldap

**Additional context**
- Is this a fresh install or an upgrade? Fresh install
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): manual

- Indicate whether or not you've manually edited any data directly in the database: no manual db edits

LDAP Settings:

LDAP Integration: checked
Active Directory: un-checked
LDAP Password Sync: un-checked
Active Directory domain: blank
LDAP Server: ldap://<ldap server ip>
Use TLS: un-checked
LDAP SSL certificate validation: un-checked
LDAP Bind Username: <full dn for service account>
LDAP Bind Password: <Password for above account>
Base Bind DN: <basedn>
LDAP Filter: &(cn=*)
Username Field: uid
Last Name: sn
LDAP First Name: cn
LDAP Authentication query: uid=
LDAP Version: 3
...
LDAP Email: mail

I know the ldap settings are correct because the service accoutn binds but it never searches to get the users dn... snipe-it is just appending the basedn to the uid and trying to bind with that.

**Comment by rabidmullet** [comment]
From looking at ldap.php the user dn is constructed bu adding the username to the basedn:
       $userDn      = $ldap_username_field.'='.$username.','.$settings->ldap_basedn;

but that dn will only work if the user is at the root of the basedn. Shouldn't the uid be searched in the root and return the true dn for the user and bind with that? I inserted the following below the $userDN line to search and replace $userDn and to fix the issue but how is this working for other openldap users? Are all of the users at the baseDn?

This searches the basedn and replaces the userdn with the dn found:

        $ldap_host = Setting::getSettings()->ldap_server;
        $filter = $settings->ldap_auth_filter_query;
        $ds=ldap_connect($ldap_host);
        if($ds){
                $sr=ldap_search($ds, $baseDn, $filter . $username);
                $info = ldap_get_entries($ds, $sr);
                for ($i=0; $i<$info["count"]; $i++) {
                        $userDn = $info[$i]["dn"];
                }
        }

**Comment by kokel** [comment]
Hi there, we have the same issue.

I wonder if the current solution (contruction the DN as decribed above) fits to anyone, at all, because this is quite odd and not flexible.
With the current behaviour everyone using LDAP Authentication (can't speak of AD users, while we're using openldap) is forced to logging in with the RDN (here CN, "givenName sn").
Every other Software we are using is searching for the users DN (rather than constructing it) and uses the found one to authenticate the user while allowing the user to login via a configurable attribute (like uid in our case).

Please look into this issue and rethink the current LDAP behaviour. We would really appreciate a more flexible LDAP Authentication mechanism.

**Comment by rabidmullet** [comment]
The logic works for AD users because you can bind with a user’s UPN (username@domain.tld) and don’t have to use the dn. The same isn’t true for openldap, it requires you first bind either anon or with a known dn and search the basedn for the dn being authenticated. The final step would be to use the returned dn and the password provided by the user. Currently snipe it doesn’t do that... it only appends the username to the basedn. I found a workaround and asked the same question but got no response.
