### ISSUE TITLE
Recommended Asset label printer for Snipe-IT Hosted ?

### ISSUE THREAD

**Issue by babgond** [snipe/snipe-it#7474]
**Server (please complete the following information):**
 - Snipe-IT Version : v4.7.7 build 4160 (gb8f7cd81e)
 - OS: [e.g. Ubuntu, CentOS] : hosted by snipe-it.io
 - Web Server: [e.g. Apache, IIS] : hosted by snipe-it.io
 - PHP Version  : 7.1.30

Hello,
I have a Snipe-IT Hosted instance.
I would like to generate labels for the assets.
Which model of printer has a label could you recommend? indeed it seems that the printing of the labels is not so simple as that. (QRCode size problem, label length problem, etc.)

thanks for your advices

**Comment by ajsy** [comment]
[TSC TE200](https://www.tscprinters.com/EN/Product/Series/Desktop_Barcode_Printers/TE200_Series), working great with me

**Comment by viclou** [comment]
@ajsy can you share the settings you're using with your TSC (TE200)?

**Comment by taqniasoft** [comment]
@viclou the label size I am using is (50 mm x 25 mm)

Snipe Settings
![Snipe-IT](https://user-images.githubusercontent.com/56196250/86328677-d5946f80-bc4d-11ea-90d2-5261bb349f86.jpg)

Printer Settings
![Printer](https://user-images.githubusercontent.com/56196250/86328712-dcbb7d80-bc4d-11ea-904c-a2f8fd18ee86.jpg)

![Printer2](https://user-images.githubusercontent.com/56196250/86328724-dfb66e00-bc4d-11ea-9e5a-84582561526b.jpg)

![Printer3](https://user-images.githubusercontent.com/56196250/86328744-e5ac4f00-bc4d-11ea-974b-99851309852f.jpg)

![Printer4](https://user-images.githubusercontent.com/56196250/86328757-e80ea900-bc4d-11ea-97d6-fa34993dc129.jpg)

Brwoser Settings
![Brwoser](https://user-images.githubusercontent.com/56196250/86328764-eb099980-bc4d-11ea-9f76-c815fe97fd7d.jpg)

**Comment by ajsy** [comment]
@viclou the label size I am using is (50 mm x 25 mm)

Snipe Settings
![86328677-d5946f80-bc4d-11ea-90d2-5261bb349f86](https://user-images.githubusercontent.com/35658596/86330258-14c3c000-bc50-11ea-840d-c499bda169b0.jpg)

Printer Settings
![86328712-dcbb7d80-bc4d-11ea-904c-a2f8fd18ee86](https://user-images.githubusercontent.com/35658596/86330268-1a210a80-bc50-11ea-8798-18b4d680ad41.jpg)

![86328724-dfb66e00-bc4d-11ea-9e5a-84582561526b](https://user-images.githubusercontent.com/35658596/86330275-1db49180-bc50-11ea-974a-d8174526c790.jpg)

![86328744-e5ac4f00-bc4d-11ea-974b-99851309852f](https://user-images.githubusercontent.com/35658596/86330285-21481880-bc50-11ea-804b-ca62509d74dc.jpg)

![86328757-e80ea900-bc4d-11ea-97d6-fa34993dc129](https://user-images.githubusercontent.com/35658596/86330290-23aa7280-bc50-11ea-94ff-48b6911cbb31.jpg)

Brwoser Settings
![86328764-eb099980-bc4d-11ea-9f76-c815fe97fd7d](https://user-images.githubusercontent.com/35658596/86330301-273df980-bc50-11ea-956d-e7d1a7b32d18.jpg)

**Comment by viclou** [comment]
Thank you @ajsy !!

**Comment by ajsy** [comment]
you are welcome
