### ISSUE TITLE
Import Asset -  Checkout Type error

### ISSUE THREAD

**Issue by mpkr** [snipe/snipe-it#7477]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Import asset doesn't work if Checkout Type set to 'location'

**To Reproduce**
1. Prepare CSV file with Checkout Type column, set it to 'location'
2. Go to Import > Select import file > Process > Import
3. The browser redirect to the link: http://inventory.mydomain/undefined
4. If import with the command `php artisan snipeit:import`, There is an error:
`In Builder.php line 331:
No query results for model [App\Models\Location]`

**Expected behavior**
Expect assets will be imported and checked out to location

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version : v4.7.7  build 4160 (gb8f7cd81e)
 - OS: Windows Server 2016
 - Web Server: IIS
 - PHP Version: 7.3.7

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 69.0.1

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by opericgithub** [comment]
I get the same error on v4.9.2
