### ISSUE TITLE
DB_HOST value in .env is ignored despite clearing cache

### ISSUE THREAD

**Issue by jamesglong** [snipe/snipe-it#7480]
I'm working through a manual installation of Snipe-IT on FreeBSD 11.3 with
MySQL 5.7.27, PHP 7.3.7, and Apache 2.4.39_1.  I have MySQL installed and can
successfully initiate a command-line SQL client using the Snipe username and
password configured.  The 'snipeit' database exists but is otherwise empty.

With these DB_* settings:

DB_CONNECTION=mysql
DB_HOST=10.10.231.22
DB_DATABASE=snipeit
DB_USERNAME=snipeuser
DB_PASSWORD=mypassword
DB_PREFIX=null
DB_DUMP_PATH='/usr/local/bin'
DB_CHARSET=utf8mb4
DB_COLLATION=utf8mb4_unicode_ci
DB_SOCKET=/tmp/mysql.sock
DB_SSL=false
DB_SSL_KEY_PATH=null
DB_SSL_CERT_PATH=null
DB_SSL_CA_PATH=null
DB_SSL_CIPHER=null

When I run:

#!/usr/bin/env bash

grep ^DB_HOST .env

composer dump-autoload
#composer clear-compiled        # this command "not defined" it says
php artisan config:clear
php artisan view:clear
php artisan cache:clear
php artisan route:clear

service apache24 restart

I see this shell output:

DB_HOST=10.10.231.22
Generating optimized autoload files> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: barryvdh/laravel-debugbar
Discovered Package: eduardokum/laravel-mail-auto-embed
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: laravel/passport
Discovered Package: laravel/tinker
Discovered Package: laravelcollective/html
Discovered Package: nesbot/carbon
Discovered Package: pragmarx/google2fa-laravel
Discovered Package: rollbar/rollbar-laravel
Discovered Package: schuppo/password-strength
Discovered Package: spatie/laravel-backup
Discovered Package: tightenco/ziggy
Discovered Package: unicodeveloper/laravel-password
Package manifest generated successfully.
Generated optimized autoload files containing 4300 classes
Configuration cache cleared!
Compiled views cleared!
Cache cleared successfully.
Route cache cleared!
Performing sanity check on apache24 configuration:
Syntax OK
Stopping apache24.
Waiting for PIDS: 15422.
Performing sanity check on apache24 configuration:
Syntax OK
Starting apache24.

Then, when I aim my browser (Firefox) at the Snipe-IT target URL, I get
NOTHING, a blank white screen.  Using 'wget' instead:

$ wget http://snipeit.example.edu/ -O output.test

wget tells me there was a internal error 500, and still leaves output.test as a zero-byte
file.

The error logged in /var/log/httpd-error.log is:

[Mon Sep 30 14:48:45.077651 2019] [php7:error] [pid 13968] [client 10.10.161.35:43602] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'snipeuser'@'localhost' (using password: YES) in /usr/local/www/apache24/snipe-it/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27\nStack trace:\n#0 /usr/local/www/apache24/snipe-it/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(27): PDO->__construct('mysql:unix_sock...', 'sn...', 'mypassword', Array)\n#1 /usr/local/www/apache24/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(64): Doctrine\\DBAL\\Driver\\PDOConnection->__construct('mysql:unix_sock...', 'sn...', 'mypassword', Array)\n#2 /usr/local/www/apache24/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(43): Illuminate\\Database\\Connectors\\Connector->createPdoConnection('mysql:unix_sock...', 'sn...', 'mypassword', Array)\n#3 /usr/local/www/apache24/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php in /usr/local/www/apache24/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php on line 664

Notice that PHP is complaining about localhost even though .env has an IP
number.  That's the rub.  I can't get Snipe-IT to pick up on my DB_HOST
value, even after running all the config/cache-clearing stuff.

How can I inspect the cache to determine where PHP is getting the incorrect
value of DB_HOST?  Or optionally, how can I eliminate caching altogether.
It *appears* but I am not certain, that changes to APP_DEBUG get noticed
right away (refresh the page), without any need to clear the cache, but
perhaps APP_DEBUG just happens to be a config variable that is not cached.

Why is my DB_HOST setting being ignored?

Thank you!

Jim

**Comment by kraken-jim** [comment]
This issue is still unresolved, and continues to be a roadblock to deployment of Snipe-IT.  I believe I have placed my .env file where Snipe-IT is finding it, because I can control the APP_DEBUG value by editing the .env file.  However, the DB_HOST value in the .env file is disregarded.  We are still hoping for feedback that will assist in resolving this issue.
