### ISSUE TITLE
Asset tag url auto increment

### ISSUE THREAD

**Issue by kbeflo** [snipe/snipe-it#7481]
**Server (please complete the following information):**
 - v4.7.7 build 4160 (gb8f7cd81e) 
 - OS: Debian
 - Web Server: Nginx

**Is your feature request related to a problem? Please describe.**
An asset tag that was skipped and then updating auto increment does not update url for example:

Asset tag 92 url is https://assets/hardware/91 
Asset tag 93 url is https://assets/hardware/92

**Describe the solution you'd like**
Manually updating auto increment tag for asset tag skips will also update the url according to asset tag number.

**Comment by ajsy** [comment]
./hardware/91 is the asset record ID
