### ISSUE TITLE
license checkout to the user is not working during import

### ISSUE THREAD

**Issue by ssydorov** [snipe/snipe-it#7487]
#### Please confirm you have done the following before posting your bug report:

- [x ] I have enabled debug mode 
- [x ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Licenses checkout to the user is not working during import.
Import of license was finished without error (and with WEB, and with command-line.) 
But in my import file are 800 lines. After import, I have only 100 licenses. There are no checkout of licenses to users.

my import file looks like
'name, item name.....
user1, Office
user2, Office
User1, Photoshop
User2, Photoshop'

Finally, I have 2 licenses (not 4), and without checkout to user1 and user2

thanks

**Comment by ESikich** [comment]
I am having the same issue. Column names are Licensed to Name, Licensed to Email, Item Name, Supplier, Seats, and Category. It is only checking in unique license names, in my case 10 even though there are 289 rows of unique users.
