### ISSUE TITLE
Checkin consumable if checked out by error or mistake

### ISSUE THREAD

**Issue by hatimdegani** [snipe/snipe-it#7490]
- Snipe-IT Version v4.6.6 build 3926 (g1a10aa0dd)
 - OS: Windows 10
 - Web Server: [e.g. Apache, IIS] ???
 - PHP Version  7.2.19-0ubuntu0.18.04.2

   I made an honest mistake, by checking out the wrong consumable to the person I was suppose to check out the a different intended- ink toner, the consumable in question here.
   So requesting for the steps/guidelines to follow- to recall this aforementioned consumable so that I can revert back to the correct count of he consumable I wrongly checked out .
Or simply put I'd like to check-in the consumable.
Please help me resolve this issue. I'm going to have nightmares about it.
Thank you.

**Comment by ajsy** [comment]
No checkin for consumables, but you can delete that record from database.

Please note: manually editing data in database is not recommended, unless you know what you are doing.

![image](https://user-images.githubusercontent.com/35658596/66188784-b42f3480-e677-11e9-882b-98a82d516a5f.png)

**Comment by hatimdegani** [comment]
thank you  for your reply didn't try it out for now though, as my network admin is reluctant on me meddling around with the backend php .
