### ISSUE TITLE
Chart in dashboard become small

### ISSUE THREAD

**Issue by tao-lian** [snipe/snipe-it#7492]
When I turn off "Remote Script" in general settings, the chart in dashboard become tiny. I manually changed  "public/js/plugins/chartjs/Chart.min.js" file. Everything works fine, so that I assume it is just better of upgrade plugin version

**Comment by twsit988** [comment]
> When I turn off "Remote Script" in general settings, the chart in dashboard become tiny. I manually changed "public/js/plugins/chartjs/Chart.min.js" file. Everything works fine, so that I assume it is just better of upgrade plugin version

Hi, can you please tell me what you changed?

**Comment by tao-lian** [comment]
@twsit988 the "local" version of Chart JS it out of date, so I download newer version from https://github.com/chartjs/Chart.js/releases and replace its content.

**Comment by twsit988** [comment]
> @twsit988 the "local" version of Chart JS it out of date, so I download newer version from https://github.com/chartjs/Chart.js/releases and replace its content.
> 
> > <img alt="" width="48" src="https://avatars3.githubusercontent.com/u/10342521?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/4908d9947135e4536ef61d61512ee575f869bf6f/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e2e69636f"> GitHub**[chartjs/Chart.js](https://github.com/chartjs/Chart.js)**Simple HTML5 Charts using the  tag. Contribute to chartjs/Chart.js development by creating an account on GitHub.

Hi thanks for your response. I downloaded the .zip source code but there are so many files and folders. I am a bit confused which files/folders I need to replace. Unless there are only several files that I need to replace? Can you please advise which ones I need to replace and where?

Thank you!
