### ISSUE TITLE
Additional fields for licenses. 

### ISSUE THREAD

**Issue by AngelusDulcis** [snipe/snipe-it#7495]
At this time unless I'm dense but I cannot see a way to associate a fieldset with the licenses. You can assign them to assets.

Use case: I have a request to add custom fields to licenses of "Location of User" and "Responsible Party."

I don't see the licenses in the Asset list, and in the License list I don't see a way to change the fields. Please help? :)

**Comment by Eina61** [comment]
I am also interested in this - I just purchased a license for Snipe-IT and tried to add the product to my list of licences but would like to be able to add a field for renewal period for licence - such as Monthly or Yearly. (I know I have purchase date & expiry date but would like this for clarification).

Also ( reported in another issue but that is already stale) I am in Malaysia so default currency of MYR (Malaysian Ringgit) but most of our software purchases are in USD. Either having a field for real currency used or allowing multiple currencies for licences would be helpful.

**Comment by empressalae** [comment]
Still relevant

**Comment by empressalae** [comment]
Still relevant

**Comment by eina84** [comment]
I gave up hoping it would get added so I just canceled my monthly subscription. No longer relevant to me.

**Comment by NewStoreIT** [comment]
I am also interested in this. Being able to add fieldsets to licenses would be very useful.
