### ISSUE TITLE
Have Serial Number Display when Viewing Assets Assigned to Users

### ISSUE THREAD

**Issue by FE-sys** [snipe/snipe-it#7501]
**Server (please complete the following information):**
 - Snipe-IT Version: 4.6.15
 - OS: Ubuntu 18.04
 - Web Server: Apache II
 - PHP Version: 7.2.19

**Is your feature request related to a problem? Please describe.**
We would like to be able to view the Serial Number of Assets Checked Out to a User. If there are Asset damages it is the information they most easily know from our labels. It would help identify Assets much quicker. 

**Describe the solution you'd like**
Serial Number to be displayed in Assets for a User, I thought I saw it fixed, but it doesn't display (see screenshot attached).

**Describe alternatives you've considered**
We initially opted to Import and check out to a location. But bulk location imports, bulk imports themselves, as well as the Child-Parent Hierarchy aren't quite as flushed out as is feasible for 8,000+ devices.

**Additional context**

![Users Display Serial](https://user-images.githubusercontent.com/56308617/66419727-93961000-e9d2-11e9-9b2c-9f5e93afea60.PNG)

**Comment by mpkr** [comment]
Do you like this?
![Capture](https://user-images.githubusercontent.com/6811937/66546408-2798e080-eb67-11e9-958a-b132be466051.PNG)

**Comment by FE-sys** [comment]
That would be amazing! Preferably we could keep asset tag and serial number both shown. But what you created (including the order it's displayed in) would accomplish what we need it to!

**Comment by mpkr** [comment]
Replace your snipe-it\resources\views\users\view.blade.php file
[view.blade.zip](https://github.com/snipe/snipe-it/files/3715632/view.blade.zip)

The asset tag come with the asset name so I removed it. If you still want it, just uncomment the asset_tag code block.

**Comment by FE-sys** [comment]
Thank you! That worked, I appreciate it!
