### ISSUE TITLE
Dashboard not honoring companies?

### ISSUE THREAD

**Issue by cmeis** [snipe/snipe-it#7507]
#### Please confirm you have done the following before posting your bug report:

- [Y ] I have enabled debug mode 
- [Y] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
The dashboard doesn't seem to fully respect the "companies" feature. I.e. it doesn't show assets from a "foreign" company, but all numbers of devices etc. are the sum of all assets over all companies.

**Expected behavior**
I'd expect those dashboard informations to show only relevant numbers for the company the logged in user belongs to (as long as it's not a super admin).

**Server (please complete the following information):**
 - Snipe-IT Version 4.7.7
 - OS: CentOS 7
 - Web Server: Apache
 - PHP Version 7.1.30

**Comment by twsit988** [comment]
I think this may help:
In General Settings, check off:
Full Multiple Companies Support Full Multiple Companies Support
Restricting users (including admins) assigned to companies to their company's assets.
