### ISSUE TITLE
Whoops, something went wrong

### ISSUE THREAD

**Issue by davoezzz** [snipe/snipe-it#7508]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [e.g. Ubuntu, CentOS] Windows
 - Web Server: [e.g. Apache, IIS] IIS
 - PHP Version 7.3.10

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10
 - Browser [e.g. chrome, safari] Chrome, IEX

**Smartphone (please complete the following information):**

**Error Messages**

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.permission_groups' doesn't exist (SQL: select `permission_groups`.*, `users_groups`.`user_id` as `pivot_user_id`, `users_groups`.`group_id` as `pivot_group_id` from `permission_groups` inner join `users_groups` on `permission_groups`.`id` = `users_groups`.`group_id` where `users_groups`.`user_id` = 1)

Illuminate\Database\QueryException 
…\vendor\laravel\framework\src\Illuminate\Database\Connection.php664
56
Doctrine\DBAL\Driver\PDOException 
…\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php63
55
PDOException 
…\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php61
54
PDO prepare
…\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php61
53
Doctrine\DBAL\Driver\PDOConnection prepare
…\vendor\laravel\framework\src\Illuminate\Database\Connection.php326
52
Illuminate\Database\Connection Illuminate\Database\{closure}
…\vendor\laravel\framework\src\Illuminate\Database\Connection.php657
51
Illuminate\Database\Connection runQueryCallback
…\vendor\laravel\framework\src\Illuminate\Database\Connection.php624
50
Illuminate\Database\Connection run
…\vendor\laravel\framework\src\Illuminate\Database\Connection.php333
49
Illuminate\Database\Connection select
…\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php1719
48
Illuminate\Database\Query\Builder runSelect
…\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php1704
47
Illuminate\Database\Query\Builder get
…\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php481
46
Illuminate\Database\Eloquent\Builder getModels
…\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Relations\BelongsToMany.php531
45
Illuminate\Database\Eloquent\Relations\BelongsToMany get
…\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Relations\BelongsToMany.php511
44
Illuminate\Database\Eloquent\Relations\BelongsToMany getResults
…\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php413
43
Illuminate\Database\Eloquent\Model getRelationshipFromMethod
…\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php393
42
Illuminate\Database\Eloquent\Model getRelationValue
…\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Concerns\HasAttributes.php323
41
Illuminate\Database\Eloquent\Model getAttribute
…\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php1382
40
Illuminate\Database\Eloquent\Model __get
…\app\Models\User.php145
39
App\Models\User isSuperUser
…\app\Http\Middleware\CheckForDebug.php21
38
App\Http\Middleware\CheckForDebug handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
37
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
36
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\app\Http\Middleware\CheckForSetup.php27
35
App\Http\Middleware\CheckForSetup handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
34
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
33
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\fideloper\proxy\src\TrustProxies.php57
32
Fideloper\Proxy\TrustProxies handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
31
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
30
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\app\Http\Middleware\NosniffGuard.php17
29
App\Http\Middleware\NosniffGuard handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
28
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
27
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\app\Http\Middleware\ContentSecurityPolicyHeader.php18
26
App\Http\Middleware\ContentSecurityPolicyHeader handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
25
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
24
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\app\Http\Middleware\ReferrerPolicyHeader.php17
23
App\Http\Middleware\ReferrerPolicyHeader handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
22
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
21
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\app\Http\Middleware\XssProtectHeader.php18
20
App\Http\Middleware\XssProtectHeader handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
19
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
18
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\app\Http\Middleware\FrameGuard.php17
17
App\Http\Middleware\FrameGuard handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
16
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
15
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php49
14
Illuminate\View\Middleware\ShareErrorsFromSession handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
13
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
12
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php63
11
Illuminate\Session\Middleware\StartSession handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
10
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
9
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php46
8
Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
7
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
6
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\barryvdh\laravel-cors\src\HandlePreflight.php29
5
Barryvdh\Cors\HandlePreflight handle
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php149
4
Illuminate\Pipeline\Pipeline Illuminate\Pipeline\{closure}
…\vendor\laravel\framework\src\Illuminate\Routing\Pipeline.php53
3
Illuminate\Routing\Pipeline Illuminate\Routing\{closure}
…\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php102
2
Illuminate\Pipeline\Pipeline then
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php151
1
Illuminate\Foundation\Http\Kernel sendRequestThroughRouter
…\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php116
0
Illuminate\Foundation\Http\Kernel handle
…\public\index.php58

PHP artisan migrate output:

In PDOconnection.php line 24:

Parse error: syntax error, unexpected '?' , expecting variable _T_VARIABLE)

**Additional context**
- Is this a fresh install or an upgrade? Upgrade from normal install to Git
- What OS and web server you're running Snipe-IT on: Server 2016
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) Upgrade from normal install to Git
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by davoezzz** [comment]
@snipe Can you have a look into this?

**Comment by Pimmetje** [comment]
This give me a hint https://github.com/laravel/framework/issues/23537
For me changing my PATH to include the 7.3 binary first (plesk server) fixed it. Anything else i tried (alias running it with the given php version upgrade.php / composer did not work).
