### ISSUE TITLE
Feature Request:  New/multi-maintenance View

### ISSUE THREAD

**Issue by jdpatt** [snipe/snipe-it#7509]
**Server (please complete the following information):**
 - Snipe-IT Version: Latest
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version: 7.x

**Is your feature request related to a problem? Please describe.**
Maintenance is limited to a single asset.

**Describe the solution you'd like**
A new model to be added, where a maintenance can be added that affects all of a product type/number. From an IT asset standpoint, this can be thought as having the ability to say all of one type of a laptop model needs to be RMA'd for some defect or all of X need to be calibrated.  When completed on an asset, it appends a row to the individual asset’s maintenance table.  The view of this new model, should be able to show all affected and if the maintenance has been completed or not.  If not, a button on the row of that asset could “complete” the maintenance.  The asset maintenance view that exists today should also be able to list these maintenance that are needed but have not been completed.  The traditional ability to add “one-off” maintenance to an asset are still needed/valuable.  If checked out, the user should know that their asset requires maintenance.
Additionally, I think this model should be addressable much like the assets are. That way the maintenance could be shared/referenced with the responsible people. (i.e.: url.com/hardware/ID -> url.com/maintenance/ID).  It would also be great to have the ability to attach files to the maintenance much like you can assets.

**Describe alternatives you've considered**
Currently, this is managed externally via an excel sheet that rarely is up to date.

**Additional context**
From a non-IT standpoint, this additional feature makes snipe-it an amazing tool for hardware prototype tracking/development (my specific use-case).  The current features are amazing and provide a view of usage and allocation that is not available through excel sheets.  The API allows automated test benches/CI to checkout hardware and run on target without conflict between humans or other tests.  (Currently managed through custom software per project.)
This new feature allows one to say that part number x has an issue, this is what need to be done to fix it (via notes and attachments) and all of this part number must have this update done to perform correctly.  It provides a tracking/an audit path that all modifications were completed (when and by who) before customer delivery.

Even if this isn’t deemed viable for general consumption, any pointers on what all things are affected would be great, as I’ll most likely attempt some work for this feature.  I see a few similar ones but they are all marked as stale/lacking in detail.

**Comment by VOWA-O** [comment]
That feature would be great for recurring tasks in addition to the audit feature.
