### ISSUE TITLE
Export Licenses with CLI

### ISSUE THREAD

**Issue by pknutti** [snipe/snipe-it#7511]
**Server (please complete the following information):**
Snipe-IT Docker Version v4.7.5 - build 4137

**Describe the solution you'd like**

Hi,

I would like to have a possibility to download a CSV files from all of my licenses with a simple command. Maybe there is already a suitable solution available and I haven't found it. 

Furthermore I am searching for a possibility to remove multiple licenses and mark all seats as assigned.

Maybe you can give me a hint if there are already some possibilities to solve my issues.

Thanks

Pascal

**Comment by paixtis1** [comment]
I second pknutti request.
Export assets or licenses etc.. to CSVs via CLI tools or via a single API call is a very useful feature and it is a mandatory feature for many others, including myself.
