### ISSUE TITLE
non-admin users can fully view and edit ALL assets

### ISSUE THREAD

**Issue by gdmonnezza** [snipe/snipe-it#7513]
Hi. Im'using Snipe It v4.7.7 on a fresh LEMP installation
Everything is OK, but I really can't understand if this behaviour is normal:
If I set all user permissions to be "inherited", the user can only see few field of it's own assets ONLY.
If I set user permission enabling view and edit assets, the user can view and edit ALL company's assets (not only the ones assigned/checked out to him, as expected)

If this is not a bug, can anyone point me in the right direction to investigate possible misconfiguration?

Many thanks

**Comment by imphocused** [comment]
If you give the user rights to view and edit assets, then that is the expected behavior. By default they would only have access to their own individual assets.

https://snipe-it.readme.io/docs/permissions
