### ISSUE TITLE
Dashboard List all Assets - no matching records found.  search not working 

### ISSUE THREAD

**Issue by cupcak6024** [snipe/snipe-it#7514]
#### Please confirm you have done the following before posting your bug report:

- [ yes] I have enabled debug mode 
- [ yes ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When i click on Assets List All or enfact any of the buttons that are supposed to list all my assets , it returns , no matching records found. when there are over 214 assets in this DB. 

**To Reproduce**
1. Go to '.Dashboard..'
2. Click on 'Assets - List All ....'
4. See error - no matching records found.

**Expected behavior**
I expect to see a list of all the assets in the DB. 

**Screenshots**
![snipe dashboard](https://user-images.githubusercontent.com/48737194/66744536-098bf280-ee7d-11e9-86b3-a4161ef76751.JPG)
![snipe dashboard](https://user-images.githubusercontent.com/48737194/66744590-20cae000-ee7d-11e9-9942-cf1a56b935b3.JPG)

**Server (please complete the following information):**
Snipe-IT version | v4.6.15  build 4011 (gd1e9fbfa2)
-- | --
Software License | AGPL3
PHP Version | 7.2.17-1+ubuntu16.04.1+deb.sury.org+3
Laravel Version | 5.4.35
 - Web Server: [e.g. Apache, IIS] Apache Server version: Apache/2.4.18 (Ubuntu)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Mozilla Firefox Quantum
 - Version  69.0.2.

**Smartphone (please complete the following information):**

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
Nothing obvious , 
![snipe dashboard](https://user-images.githubusercontent.com/48737194/66744536-098bf280-ee7d-11e9-86b3-a4161ef76751.JPG)

- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? AWS install 
- What OS and web server you're running Snipe-IT (see above) 
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - NO 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by imaginethatca** [comment]
Hi
I am also having this issue. The Dashboard shows me the number of assets and licenses I have but when going to Assets or Licenses, zero results are found.
This happened to me immediately following an update from 4.7.4 to 4.7.7.
I have php 7.2.19 on Ubuntu 18.04 and did a "php upgrade.php" command, which seemed to run successfully.
Browser shows no errors, but turning snipit debug mode on shows 2 errors:
[16:10:24] LOG.error: ReflectionException: Class Barryvdh\Cors\HandleCors does not exist in /home/snipeit/git/Snipeit/vendor/laravel/framework/src/Illuminate/Container/Container.php:752
and
16:10:24] LOG.error: Class Barryvdh\Cors\HandleCors does not exist {"userId":1,"email":"myname@myemail.com","exception":{}}
Look forward to any suggestion for this issue.

**Comment by chay22** [comment]
@imaginethatca The 4.7.7 release contains [`barryvdh/laravel-cors`](https://github.com/snipe/snipe-it/blob/v4.7.7/composer.json#L9), though. I guess the composer installation does not completed. You might want to try to manually install it, run:

```
composer require barryvdh/laravel-cors:^0.11.3
```

**Comment by imaginethatca** [comment]
Thanks for the info @chay22 this fixed the issue, although it was not as easy as running that one command. I will show below what I did for anyone else that comes across this post.

> NOTE: I have no idea what I am doing! The following is what I did with no knowledge of what what going on, I am NOT suggesting you do this, it's just a record of what I did and what happened.
> I'm a windows guy and know only enough Linux to really break things. So I follow what others suggest.

I ran:
 `composer require barryvdh/laravel-cors:^0.11.3` 
and got error:

> _Command 'composer' not found, but can be installed with:
> sudo apt install composer_

So I ran that suggested command:
`sudo apt install composer`
and it installed successfully.

I then ran the first command again:
 `composer require barryvdh/laravel-cors:^0.11.3` 
and got error:

> Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - league/csv 9.3.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - league/csv 9.3.0 requires ext-dom * -> the requested PHP extension dom is missing from your system.
    - Installation request for league/csv (locked at 9.3.0, required as ^9.2) -> satisfiable by league/csv[9.3.0].

After a quick search on the google I ran command:
`php -v `
to confirm my php version(7.2)

I then ran command:
`sudo apt-get install php7.2-xml`
This updated and installed a lot of things, and finished with a message

> Package manifest generated successfully.

I then restarted Apache2:
`sudo service apache2 restart`

And my assets are now listed. I have a bit of tested to confirm all is working ok, but looks much better.
