### ISSUE TITLE
Issues when upgrading

### ISSUE THREAD

**Issue by mholtrlc** [snipe/snipe-it#752]
Every time I try and upgrade I end up with a glitchy system and not displaying any of my assets.  I'm not sure what im doing wrong.

**Comment by snipe** [comment]
Hi @mholtrlc - please see the Getting Help documentation and provide us with the information listed there, so we can try to help you. http://snipeitapp.com/documentation/getting-help/

Also, please describe what a "glitchy system" means.

**Comment by mholtrlc** [comment]
I resolved it by running php composer.phar update per https://github.com/snipe/snipe-it/issues/676#issuecomment-83175397

**Comment by snipe** [comment]
@mholtrlc glad you got it sorted. While we do try to keep the develop branch pretty stable, it's not recommended for production use.
