### ISSUE TITLE
syntax error, unexpected 'public' in /Api/UsersController - snipe v5.0 (develop)

### ISSUE THREAD

**Issue by phatuous** [snipe/snipe-it#7523]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
After upgrading to the v5.0 branch (develop), when going to the /users page, I am getting a syntax error in the /app/Http/Controllers/Api/UsersController.php file.

I opened the file in my local IDE, and it was also chirping about this particular line. Presumably the issue is not actually with the 'public' declaration, but some other lurking syntax error elsewhere. I switched back to master and the error went away.

**To Reproduce**
1. Upgrade to Snipe v5.0
2. navigate to /users (People) page

**Expected behavior**
Screen should show all my existing users.

**Screenshots**
not applicable

**Server (please complete the following information):**
 - Snipe-IT Version: v5.0.0-beta-2 - build 4009 (develop)
 - OS: Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-1087-aws x86_64)

 - Web Server: Apache
 - PHP Version: PHP 7.3.10-1+ubuntu16.04.1+deb.sury.org+1

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.14.6
 - Browser: Chrome
 - Version: Version 77.0.3865.90 (Official Build) (64-bit)

**Error Messages**
[2019-10-17 11:37:15] production.ERROR: syntax error, unexpected 'public' (T_PUBLIC) {"userId":1,"email":"kent.mcneill@bridgeinternationalacademies.com","exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): syntax error, unexpected 'public' (T_PUBLIC) at /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/app/Http/Controllers/Api/UsersController.php:351)
[stacktrace]
#0 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/composer/ClassLoader.php(322): Composer\\Autoload\\includeFile('/var/www/assets...')
#1 [internal function]: Composer\\Autoload\\ClassLoader->loadClass('App\\\\Http\\\\Contro...')
#2 [internal function]: spl_autoload_call('App\\\\Http\\\\Contro...')
#3 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(779): ReflectionClass->__construct('App\\\\Http\\\\Contro...')
#4 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(658): Illuminate\\Container\\Container->build('App\\\\Http\\\\Contro...')
#5 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(609): Illuminate\\Container\\Container->resolve('App\\\\Http\\\\Contro...', Array)
#6 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(759): Illuminate\\Container\\Container->make('App\\\\Http\\\\Contro...', Array)
#7 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(233): Illuminate\\Foundation\\Application->make('App\\\\Http\\\\Contro...')
#8 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(833): Illuminate\\Routing\\Route->getController()
#9 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(794): Illuminate\\Routing\\Route->controllerMiddleware()
#10 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(695): Illuminate\\Routing\\Route->gatherMiddleware()
#11 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\\Routing\\Router->gatherRouteMiddleware(Object(Illuminate\\Routing\\Route))
#12 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#13 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(625): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#14 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#15 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#16 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#17 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#21 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/app/Http/Middleware/CheckForDebug.php(25): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\CheckForDebug->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/app/Http/Middleware/CheckForSetup.php(26): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\CheckForSetup->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#30 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#31 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#32 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/app/Http/Middleware/NosniffGuard.php(17): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#33 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\NosniffGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#34 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#35 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/app/Http/Middleware/ContentSecurityPolicyHeader.php(18): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\ContentSecurityPolicyHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#37 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/app/Http/Middleware/ReferrerPolicyHeader.php(17): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\ReferrerPolicyHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/app/Http/Middleware/XssProtectHeader.php(18): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\XssProtectHeader->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/app/Http/Middleware/FrameGuard.php(17): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\FrameGuard->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#46 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#47 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#48 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#51 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#52 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#53 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#54 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#55 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#56 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#57 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Barryvdh\\Cors\\HandlePreflight->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#58 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#59 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#60 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#61 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#62 /var/www/assets-eastafrica-uat-snipev5.bridgeinternationalacademies.com/public/index.php(58): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#63 {main}
"} 

**Additional context**
- Is this a fresh install or an upgrade? 
Upgrade from 4.7.7

- What OS and web server you're running Snipe-IT on
Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-1087-aws x86_64) + Apache

- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
manual (git)

- Include what you've done so far in the installation, and if you got any error messages along the way.
Upgrade was a little bumpy, but I fought through the various issues.

- Indicate whether or not you've manually edited any data directly in the database
Nope

**Comment by disc** [comment]
It looks like *develop* branch is broken. Travis CI shows fallen tests

**Comment by chay22** [comment]
I actually have created a PR https://github.com/snipe/snipe-it/pull/7478 that fix this. But, I need a review.
I also almost finish to pass all the test by fully changed the tests flow that requires a lot of change here https://github.com/snipe/snipe-it/compare/develop...chay22:bulk-action that I haven't try to make to merge it, yet.

I neither have capability of properly doing it nor actually know how to configure travis to work with environment I've written there. Beside having some more changes which doesn't suit with my PR title up there, such as adding license and accessory ability to bulk edit and delete.

I need a discussion.

**Comment by RafaelFerreiraTVD** [comment]
HI @chay22 i've been working on snipeit and noticed this bug, and solved as well on PR #7518.

Let's wait for the review of @snipe 😃

**Comment by phatuous** [comment]
this issue has been resolved by this pull request, which has been merged into the develop branch:

https://github.com/snipe/snipe-it/pull/7528

closing ticket.
