### ISSUE TITLE
MySQL strict-mode still problematic?

### ISSUE THREAD

**Issue by t3easy** [snipe/snipe-it#7525]
In https://snipe-it.readme.io/docs/docker you write

> Newer MySQL containers (5.7 and later, or MariaDB) may run in strict-mode by default, and the initial migrations and application setup will fail in strict mode. If you want to use one of those versions, you need to disable strict mode first!

Is it still valid? As I don't see any info about strict mode in other installation methods and you use doctrine/dbal 2.9.

**Comment by tholu** [comment]
@t3easy Have you found an answer to this? Have you deployed it via docker?

**Comment by t3easy** [comment]
> @t3easy Have you found an answer to this? Have you deployed it via docker?

I've used MariaDB 10.1 in my Docker setup ATM and opened this issue.

**Comment by tholu** [comment]
But everything works fine with MariaDB 10.1 for you so far? Are you deploying via docker-compose?

**Comment by t3easy** [comment]
10.1 is fine for us. Yes, we use docker-composer.

**Comment by tholu** [comment]
@t3easy Are you willing to share your docker-compose configuration?

**Comment by t3easy** [comment]
sure:
https://gist.github.com/t3easy/6a8924261e390972d54901af6736c1d5

<blockquote><img src="https://github.githubassets.com/images/modules/gists/gist-og-image.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> Gist</div><div><strong><a href="https://gist.github.com/t3easy/6a8924261e390972d54901af6736c1d5">Snipe-it docker-compose stack</a></strong></div><div>Snipe-it docker-compose stack. GitHub Gist: instantly share code, notes, and snippets.</div></blockquote>
