### ISSUE TITLE
When creating new asset thru clone function photo is not saved with new asset

### ISSUE THREAD

**Issue by contman** [snipe/snipe-it#7526]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
When creating new asset thru clone function photo is displaed on new asset but not saved so after saving this cloned asset there is no photo of it

**To Reproduce**
1. Go to 'list of assets'
2. Click on 'clone'
3. Scroll down to 'bottom of page' and click save

**Expected behavior**
Photo of asset is saved

**Screenshots**
atfer clicking copy

![image](https://user-images.githubusercontent.com/23121723/67006738-2e36d300-f0e6-11e9-9d5a-c6f00cc6eff6.png)

after saving that asset

![image](https://user-images.githubusercontent.com/23121723/67006722-2119e400-f0e6-11e9-995e-12825b99a5fa.png)

Snipe-IT version | v4.7.7 build 4160 (gb8f7cd81e)
PHP Version | 7.3.9
Laravel Version | 5.5.47
OS: CentOS 7

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser chrome 77

**Comment by gilesytheking90** [comment]
this is a known issue and there are a couple of other recent posts about it. 

An easy work around is to add the image to the asset model (settings -> Asset models). This will automatically add the image to assets of the same model.
