### ISSUE TITLE
Organization Chart Report

### ISSUE THREAD

**Issue by sylphaxiom** [snipe/snipe-it#7532]
- Snipe-IT Version: 4.7.7
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version: 7.2.19

**Is your feature request related to a problem? Please describe.**
While this is not a problem with Snipe, I have a need for an updated Org chart for my organization. Since we are going to be using Snipe-IT as our most up to date records, having that information in there would be a good thing and it would be nice to be able to export an organization chart of some kind.

**Describe the solution you'd like**
I would like to be able to export an organization chart from snipe IT using who the user reports to as a reference. It would be convenient to be able to include department and title in this chart, but not necessary.

**Describe alternatives you've considered**
An alternative would be a way to view the reporting structure in some fashion on the site. Something that I could easily sort and find who reports to who and create my own Org chart

**Comment by twsit988** [comment]
Why??? You have other applications for that. Maybe create a page just for that in your company Sharepoint.

**Comment by sylphaxiom** [comment]
It's really a convenience issue to be honest. When things are in more than one place, they tend to not be updated as they should. With an integrated component, that would keep the tree updated as we update the system.
