### ISSUE TITLE
Feature Request - API Update accessories via Patch

### ISSUE THREAD

**Issue by boingball** [snipe/snipe-it#7533]
#### Desired Behaviour (or desired behaviour if a feature request)

With the API I can update Assets using a custom program to search and update where necessary.
However I'm want to use the Accessories part of SnipeIT to update our Accessories stock using a barcode reader.
I have the barcodes and I can write a program to talk to the API
But it doesn't have a accessories update option yet using Patch, only methods to check an ID and create a new one.
Just a feature request to get this put in at some point please.

-----

**Comment by boingball** [comment]
Would be nice if it was possible

**Comment by pbrink231** [comment]
I believe this is already in on master.  I saw and tested this on my pull request.

I think this should be closed.

**Comment by boingball** [comment]
It’s not in the API documentation for v4.8.0 yet... all you can do for accessory’s in the API is view, find or create a new one. No update which is what I’m looking for.

Use case would be : i have 10 HDMI cables in stock, I get a shipment of 5. My barcode reader scans in 5 and sends this to snipeit to update to make a total of 15.

At the moment all I could do is create a new HDMI entry with a value of 5, not update the current record

**Comment by boring10** [comment]
Just for reference, you can update an accessory by id with the following body/data.

Patch
- name
- category_id
- company_id
- location_id
- manufacturer_id
- model_number
- order_number
- purchase_cost
- qty
- supplier_id
- requestable

Put
- name
- category_id
- company_id
- location_id
- manufacturer_id
- model_number
- order_number
- purchase_cost
- purchase_date
- qty
- supplier_id
