### ISSUE TITLE
snipe won't read my .env file

### ISSUE THREAD

**Issue by mntsupport** [snipe/snipe-it#7534]
I have read [checked the Common Issues page, and I tried to enable debug but as the system isn't reading my.env file it didn't work.

**Describe the bug**
When I copied the .env.example file to .env and made changes within, the system doesn't recognize any of the changes.

**To Reproduce**
1. Go to snipe-it root
2. Copy .env.example to .env
3. Edit .env with preferences and save file
4. restarted apache and ran the php artisan config:clear command
5. rebooted the whole machine
6. none of the changes were implemented

**Expected behavior**
When editing the .env file and restarting the required services, the changes should go into effect.

**Server (please complete the following information):**
 - Snipe-IT Version: v4.7.7 build 4160 (gb8f7cd81e) 
 - OS: Ubuntu 16.04
 - Web Server: Apache2
 - PHP Version: 7.1.32-1+ubuntu16.04.1+deb.sury.org+1

**Comment by Diniver** [comment]
Try running _php artisan config:clear_ and _php artisan config:cache_

https://snipe-it.readme.io/docs/clearing-the-config-cache

**Comment by mntsupport** [comment]
I have run those commands and just ran them again and it still won't change according to my .env. Any other suggestions?

**Comment by mntsupport** [comment]
![image](https://user-images.githubusercontent.com/56934014/67512388-57171500-f65e-11e9-9b1a-b0f43ecffd10.png)

this is the specific area I am expecting to update.

**Comment by mntsupport** [comment]
Just curious if anyone is still looking at this?

**Comment by CoventryIT** [comment]
Hi mntsupport,

The field that updates this value is MAIL_REPLYTO_ADDR= (Your email you wish the test to go to)

Can you confirm that this email or section is filled out?

**Comment by mntsupport** [comment]
I can confirm I have that section filled out. The problem seems to be that the system won't read my .env file. For example I've tried to enable the debug mode by editing the .env file and it still doesn't work. Do I need to place the file in a different location than the env.example file? Sorry, I'm just lost on this...

**Comment by nerdsome** [comment]
Check the file permissions of your **.env** file
Try to clear the bootstrap cache manually. 
Go to <intall dir ->bootstrap->cache and delete everything in it. 

Then run **composer dump-autoload** 
Then clear configuration cache 
**php artisan cache:clear**
**php artisan config:cache**

**Comment by mntsupport** [comment]
Hi!

I have resolved this a month ago.
Thak you.
Dillan Picray
Systems Administrator

E: dpicray@minnesota-title.com (mailto:dpicray@minnesota-title.com)
P: (763) 228-4553 (tel:(763)%20228-4553)
