### ISSUE TITLE
Location of logs?

### ISSUE THREAD

**Issue by vinulogy** [snipe/snipe-it#7535]
Is there a place where one can find the logs users have done in the system? For an example, if someone was to deactivate an account. When are who deactivated that account?

The audit log is blank, which I think is more for the asset than user management. If anyone can point me where to look, it'll be greatly appreciated.

**Comment by HinchK** [comment]
If you bring up the user who was deactivated’s page, there should be a modified on date.   (This can also be found by accessing the database directly and finding the appropriate column within the users table.

Regarding the question of who:

 if all your users are super admins, I am not sure if you will  be able to really discern who could’ve done it.   

 That being said, if you pull in users from LDAP, I’m willing to bet an LDAP Sync operation Somehow lost ability to track whether or not a user is active.   This could happen after an update or after tweaking LDAP settings.

If you’re seeing a mass disabling of users, 
Take a look at either an LDAP sync or even a recent import.
