### ISSUE TITLE
Accept asset not working 

### ISSUE THREAD

**Issue by x3inspire** [snipe/snipe-it#7536]
Hello, i'm using the latest version of Snipe IT. I got some problem now, when user tried to accept the asset with signature, nothing happen after user accept, draw the signature and click submit.  

Example the accept asset page is https://mydomain.com/account/accept-asset/85 , it only return the same page after submit.

Any help please?

**Comment by narkelo** [comment]
I'm having a similar issue. except i get an "oops something went wrong" page after the users clicks submit

**Comment by x3inspire** [comment]
Any support please?

**Comment by narkelo** [comment]
bump

**Comment by x3inspire** [comment]
bumo
