### ISSUE TITLE
LDAP Sync Issue -  Could not bind to LDAP: Invalid credentials

### ISSUE THREAD

**Issue by ajoyrajan** [snipe/snipe-it#7546]
#### Please confirm you have done the following before posting your bug report:

- [YES ] I have enabled debug mode 
- [YES] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
LDAP is not syncing with the service account or any account. The account works on another server for LDAP but, not in Snipe. 

**To Reproduce**
1. Go to 'settings'--> LDAP
2. Click on 'Test LDAP Login'--> enter credentials and click test login

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/56373887/67723297-aa5ae000-fa2f-11e9-8dd9-f84d9dcba8ea.png)

**Server (please complete the following information):**
 - Snipe-IT Version 
 - OS: [Windows Server 2012R2]
 - Web Server: [Apache]
 - PHP Version 7.3.5

**Desktop (please complete the following information):**
 - OS: [windows 10 pro]
 - Browser [firefox]
 - Version [69.0.3]

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error:
debug
log [09:41:57] LOG.debug: Preparing to test LDAP login
debug
log [09:41:57] LOG.debug: Bind failed
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. Cannot try demo as the LDAP is not open for internet and we do not intend to. 
- Include any additional information you can find in `storage/logs` and your webserver's logs. 

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by joelmclean** [comment]
@ajoyrajan I bullied through configuring LDAP recently; the documentation is a bit lacking, but the info you need is something like this;
![image](https://user-images.githubusercontent.com/24534308/68005274-d218a500-fcc8-11e9-845a-94f2d874474c.png)
I've replaced our domain (i.e. domain.local) with contoso.com in keeping with Microsoft's examples.

The `ou` is whatever group you want to be searching against; i.e. Administrators, or "Users" or "staff".

I'd recommend saving your Bind Username and Bind User Password and saving the configuration, then testing whether or not you can even connect.

If you can connect, then it's simply just how you're filtering users, and whether you're authenticating with `userprincipalname` or `samaccountname`

Good luck!

**Comment by ajoyrajan** [comment]
Thanks Joel.

Ajoy Rajan
Managed Services Consultant
T 02 8235 3543   M 0468581352
E ajoy.rajan@brennanit.com.au
