### ISSUE TITLE
Edits to '.env' File Not Updating 'mail.php' File

### ISSUE THREAD

**Issue by Christian-UI** [snipe/snipe-it#7548]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
As I understand it, the mail.php file gets its settings from the "Outgoing Mail Server Settings" section of the .env file. I've edited those settings, but my 'mail.php' file is still showing only the default info.

**To Reproduce**
1. Go to '.env' file in root of Snipe-IT install directory.
2. Make edits to 'Outgoing Mail Server Settings' in '.env' file with Notepad++.
3. Save edits.
4. Check 'mail.php' file in 'config' folder.
5. All defaults still set, no changes visible.
6. Run 'php artisan config:clear', etc... in command prompt.
7. Run 'iisreset'.
8. Still no changes visible to 'mail.php'

**Expected behavior**
I expected the edits I made in my '.env' file to carry forward into my 'mail.php' file.

**Screenshots**

**Server (please complete the following information):**
 - Snipe-IT Version v4.7.7 build 4160 (gb8f7cd81e)
 - OS: Windows Server 2012
 - Web Server: IIS
 - PHP Version 7.3.10

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 70.0

**Smartphone (please complete the following information):**
 - Device: (N/A)
 - OS: (N/A)]
 - Browser (N/A)
 - Version (N/A)

**Error Messages** (N/A)
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.

**Additional context**
- Is this a fresh install or an upgrade? Fresh Install
- What OS and web server you're running Snipe-IT on: Windows Server 2012 / IIS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc): Manual..?
- Include what you've done so far in the installation, and if you got any error messages along the way. - I've been running for a little over a week, and I have a good amount of data inputted into my database. This is the first real issue I've encountered.
- Indicate whether or not you've manually edited any data directly in the database: Nope.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by 0stage** [comment]
So it's not just me :( can you please share your env configuration? Please mask sensible details

**Comment by Christian-UI** [comment]
I actually was able to resolve this issue by just removing the sign-in user. We have an internal mail server, so even though for some reason it wasn't accepting the correct credentials being provided, removing the credentials entirely still allowed it to sign in. Go figure ¯\_(ツ)_/¯
