### ISSUE TITLE
could not proceed further as it gives the error "Fatal error: require_once(): Failed opening required "

### ISSUE THREAD

**Issue by maheshvijapure** [snipe/snipe-it#755]
Hi ,

I have downloaded the latest stable snipit code and extracted and configured according to my environment but stuck as the below error -

tar -xzvf /opt/snipe-it-1.2.6.1.tar.gz
mv snipe-it-1.2.6.1/ assets
ls assets/
service mysqld start
chkconfig mysqld on
cd /var/www/html/assets

root@rtic-assets assets$ ll /var/www/html/assets/bootstrap/autoload.php
-rwxrwxrwx. 1 root root 2459 Mar 13 01:55 /var/www/html/assets/bootstrap/autoload.php
root@rtic-assets assets$ php artisan key:generate --env=production
PHP Warning:  require(/var/www/html/assets/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/assets/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/html/assets/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/assets/bootstrap/autoload.php on line 17
root@rtic-assets assets$ php composer.phar install --no-dev
Could not open input file: composer.phar
root@rtic-assets assets$ ls
app        CHANGELOG.md   CONTRIBUTING.md  gh-changelog.php  public
artisan    composer.json  docker           LICENSE           README.md
bootstrap  composer.lock  Dockerfile       phpunit.xml       server.php
root@rtic-assets assets$ php composer.phar dump-autoload
Could not open input file: composer.phar
root@rtic-assets assets$ php artisan migrate
PHP Warning:  require(/var/www/html/assets/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/assets/bootstrap/autoload.php on line 17
PHP Fatal error:  require(): Failed opening required '/var/www/html/assets/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/assets/bootstrap/autoload.php on line 17
root@rtic-assets assets$

Please let me know the root cause & also should you need more info.

**Comment by snipe** [comment]
`root@rtic-assets assets$ php composer.phar install --no-dev`
`Could not open input file: composer.phar`

So, composer install threw an error, which means none of the libraries were installed.

Did you actually install composer?

**Comment by maheshvijapure** [comment]
how we can install the composer

**Comment by snipe** [comment]
Please see the installation instructions. http://snipeitapp.com/documentation/installing-on-linuxosx/

**Comment by maheshvijapure** [comment]
Also while creating the secret key using "php artisan key:generate --env=production" getting the below error -

PHP Notice:  Constant LARAVEL_START already defined in /var/www/html/assets/bootstrap/autoload.php on line 2
PHP Fatal error:  Allowed memory size of 641728512 bytes exhausted (tried to allocate 7680 bytes) in /var/www/html/assets/bootstrap/autoload.php on line 17

**Comment by snipe** [comment]
Nothing is going to work until you install composer. It's a core requirement.

**Comment by maheshvijapure** [comment]
it looks my proxy server not able to reach the target server to install the composer -

root@rtic-assets assets$ curl -sS --insecure https://getcomposer.org/installer | php
#!/usr/bin/env php
Some settings on your machine may cause stability issues with Composer.
If you encounter issues, try to change the following:

Your PHP (5.3.3) is quite old, upgrading to PHP 5.3.4 or higher is recommended.
Composer works with 5.3.2+ for most people, but there might be edge case issues.

Downloading...
Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:func(144):reason(134)
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Cannot connect to HTTPS server through proxy
Downloading...
Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:func(144):reason(134)
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Cannot connect to HTTPS server through proxy
Downloading...
Download failed: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:func(144):reason(134)
file_get_contents(https://getcomposer.org/composer.phar): failed to open stream: Cannot connect to HTTPS server through proxy
The download failed repeatedly, aborting.
root@rtic-assets assets$

can we have another server or offline mode to install the composer and dependencies.

Please suggest

**Comment by snipe** [comment]
I'm afraid your server has to be able to talk to the outside world, even if just for installation and updates.

**Comment by maheshvijapure** [comment]
Yes I have made my server to talk outside world through proxy. .

But for this communication it's giving error ..

**Comment by snipe** [comment]
A quick google search showed this: https://github.com/composer/composer/issues/2021#issuecomment-19820919

**Comment by snipe** [comment]
Also, Snipe-IT requires PHP 5.4 or higher, so your install was never going to work if you're using 5.3. It looks like upgrading to 5.6 might solve your issue. https://github.com/composer/composer/issues/3120

**Comment by maheshvijapure** [comment]
Problem persists even after  PHP 5.6 upgrade.

**Comment by Nubianprince** [comment]
can you run php -v and double check your php version?

**Comment by snipe** [comment]
@maheshvijapure What's the status on this? Did you try `php -v` to confirm that PHP-cli is upgraded?
