### ISSUE TITLE
svg company logo upload

### ISSUE THREAD

**Issue by t3easy** [snipe/snipe-it#7554]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
Wrong mimetype for svg `image/svg` > `image/svg+xml`

**To Reproduce**
1. Go to 'admin/branding'
2. Click on 'Select file'
3. In Chrome you can't select a svg because of wrong mimetype in the accept property, in Firefox I can select an svg but save fails.

**Expected behavior**
SVG can be selected and uploades

**Screenshots**
<img width="989" alt="grafik" src="https://user-images.githubusercontent.com/3628035/67908552-311cd380-fb7c-11e9-9538-ad64d1e23504.png">
<img width="989" alt="grafik" src="https://user-images.githubusercontent.com/3628035/67908457-df744900-fb7b-11e9-9cdb-533748e65abb.png">

**Server (please complete the following information):**
 - Snipe-IT Version 4.7.8
 - OS: docker
 - Web Server: Apache
 - PHP Version 7.1.33

**Desktop (please complete the following information):**
 - OS: macOS 10.14
 - Browser chrome, firefox
 - Version latest

**Error Messages**
Accepted filetypes are jpg, png, gif, and svg. Max upload size allowed is 8M.
The image must be a file of type: png, gif, jpg, jpeg, svg.

**Additional context**
- Is this a fresh install or an upgrade? fresh
- What OS and web server you're running Snipe-IT on: your docker image
- What method you used to install Snipe-IT: docker
- Include what you've done so far in the installation, and if you got any error messages along the way: initial setup
- Indicate whether or not you've manually edited any data directly in the database: no

**Comment by tony-vi** [comment]
I can confirm the same issue as well as the similar error with **.lic** file upload under Licenses

**Comment by t3easy** [comment]
Haven't tested with 4.8.0.

**Comment by pguinet** [comment]
I have this problem on Version v4.8.0 - build 4186 (master) 
Server is CentOS 7.7

**Comment by brewerc1** [comment]
Still an issue in Version v4.8.0 - build 4186 (master)

**Comment by brewerc1** [comment]
This is still an issue on v4.9.2 build 4352 (gec723a3da). I've confirmed that SVG files cannot be uploaded in Safari 13.1 and Chrome 80.0.3987.163 on Mac.

**Comment by brewerc1** [comment]
@snipe can you mark this as a bug?

**Comment by RyanMorash** [comment]
This is still an issue on version 5.0.11 - build 5695. Following the steps in https://snipe-it.readme.io/docs/common-issues#svg-images-will-not-upload have not resolved the issue either.

<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/common-issues#svg-images-will-not-upload">Common Issues</a></strong></div><div>  These commands should be run from your Snipe-IT project root, just like every other cli command we mention. They should not need to be run as root/sudo/admin.These commands clear out cached service files that help speed up modern PHP applications but can also very occasionally be out of date, resu...</div></blockquote>

**Comment by brewerc1** [comment]
Doesn't seem the @snipe is paying attention to these threads, as this is still a bug and has been for a *long* time. Growing super tired of replying to stale bot for no apparent benefit.
