### ISSUE TITLE
IIS+PHP+SSO

### ISSUE THREAD

**Issue by t1r2iron** [snipe/snipe-it#7556]
First off thank you for the awesome work you have done with Snipe-It.
I have manage to finish the setup and its working fine .
Snipe-It is configured with IIS+PHP and LDAP working perfect.
Users can login to the site when visiting by entering there AD credentials .

Trying to implement SSO for the local network, so when users are visiting the site dont need to enter there credentials  .
Any ideas I have enabled Windows Authentication on IIS but other than that i dont have clue what else to do .
Any Help would be appreciated .

**Comment by namarie23** [comment]
Still relevant, wish there was feedback on this.

**Comment by snipe** [comment]
We have SAML coming out in v5. That's the best I can tell you. Lots of people want lots of things, and there are only so many hours in a day.
