### ISSUE TITLE
500 error after update

### ISSUE THREAD

**Issue by kwinters1** [snipe/snipe-it#756]
I tried to update snipe-it from V1.0 to the latest release and it's putting out a 500 error, it was working fine before the update. Here's what I've done so far:
Updated PHP from 5.3 to 5.4
Updated MariaDB from 5 to 10
copied over new files
ran composer and migrate commands with no errors

Here is the info from the log:
[2015-04-16 15:32:23] production.ERROR: exception 'PDOException' with message 'could not find driver' in D:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:47
Stack trace:
#0 D:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php(47): PDO->__construct('mysql:host=loca...', 'travis', '', Array)
#1 D:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Database\Connectors\MySqlConnector.php(20): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(7670): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(7665): Illuminate\Database\Connectors\ConnectionFactory->createSingleConnection(Array)
#4 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(7577): Illuminate\Database\Connectors\ConnectionFactory->make(Array, 'mysql')
#5 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(7531): Illuminate\Database\DatabaseManager->makeConnection('mysql')
#6 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(7411): Illuminate\Database\DatabaseManager->connection(NULL)
#7 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(7398): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
#8 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(6984): Illuminate\Database\Eloquent\Model->getConnection()
#9 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(6951): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#10 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(6524): Illuminate\Database\Eloquent\Model->newQuery()
#11 D:\inetpub\wwwroot\snipe\app\models\Setting.php(10): Illuminate\Database\Eloquent\Model::find(1)
#12 D:\inetpub\wwwroot\snipe\app\storage\views\2da2b1f98bd4ef92ee1a9e88c290ebf7(11): Setting::getSettings()
#13 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9834): include('D:\\inetpub\\wwwr...')
#14 D:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\\inetpub\\wwwr...', Array)
#15 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9712): Illuminate\View\Engines\CompilerEngine->get('D:\\inetpub\\wwwr...', Array)
#16 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9699): Illuminate\View\View->getContents()
#17 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9690): Illuminate\View\View->renderContents()
#18 D:\inetpub\wwwroot\snipe\app\storage\views\81d5fe3d2692e2370dca6bc925af5e65(74): Illuminate\View\View->render()
#19 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9834): include('D:\\inetpub\\wwwr...')
#20 D:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\\inetpub\\wwwr...', Array)
#21 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9712): Illuminate\View\Engines\CompilerEngine->get('D:\\inetpub\\wwwr...', Array)
#22 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9699): Illuminate\View\View->getContents()
#23 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9690): Illuminate\View\View->renderContents()
#24 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(10392): Illuminate\View\View->render()
#25 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9922): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#26 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(5226): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#27 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(5034): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#28 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(5020): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#29 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(721): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#30 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(702): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#31 D:\inetpub\wwwroot\snipe\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#32 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(7783): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#33 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(8390): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#34 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(8337): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#35 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(10999): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#36 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(664): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#37 D:\inetpub\wwwroot\snipe\public\index.php(49): Illuminate\Foundation\Application->run()
#38 {main}

Next exception 'ErrorException' with message 'could not find driver (View: D:\inetpub\wwwroot\snipe\app\views\backend\layouts\default.blade.php)' in D:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:47
Stack trace:
#0 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9836): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(PDOException), 1)
#1 D:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\\inetpub\\wwwr...', Array)
#2 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9712): Illuminate\View\Engines\CompilerEngine->get('D:\\inetpub\\wwwr...', Array)
#3 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9699): Illuminate\View\View->getContents()
#4 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9690): Illuminate\View\View->renderContents()
#5 D:\inetpub\wwwroot\snipe\app\storage\views\81d5fe3d2692e2370dca6bc925af5e65(74): Illuminate\View\View->render()
#6 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9834): include('D:\\inetpub\\wwwr...')
#7 D:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\\inetpub\\wwwr...', Array)
#8 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9712): Illuminate\View\Engines\CompilerEngine->get('D:\\inetpub\\wwwr...', Array)
#9 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9699): Illuminate\View\View->getContents()
#10 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9690): Illuminate\View\View->renderContents()
#11 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(10392): Illuminate\View\View->render()
#12 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9922): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#13 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(5226): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#14 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(5034): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#15 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(5020): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#16 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(721): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#17 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(702): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#18 D:\inetpub\wwwroot\snipe\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#19 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(7783): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#20 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(8390): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#21 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(8337): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#22 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(10999): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#23 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(664): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#24 D:\inetpub\wwwroot\snipe\public\index.php(49): Illuminate\Foundation\Application->run()
#25 {main}

Next exception 'ErrorException' with message 'could not find driver (View: D:\inetpub\wwwroot\snipe\app\views\backend\layouts\default.blade.php) (View: D:\inetpub\wwwroot\snipe\app\views\backend\layouts\default.blade.php)' in D:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:47
Stack trace:
#0 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9836): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 D:\inetpub\wwwroot\snipe\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('D:\\inetpub\\wwwr...', Array)
#2 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9712): Illuminate\View\Engines\CompilerEngine->get('D:\\inetpub\\wwwr...', Array)
#3 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9699): Illuminate\View\View->getContents()
#4 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9690): Illuminate\View\View->renderContents()
#5 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(10392): Illuminate\View\View->render()
#6 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(9922): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(5226): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(5034): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(5020): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(721): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(702): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 D:\inetpub\wwwroot\snipe\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(7783): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(8390): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(8337): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(10999): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 D:\inetpub\wwwroot\snipe\bootstrap\compiled.php(664): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 D:\inetpub\wwwroot\snipe\public\index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []

**Comment by snipe** [comment]
Sounds like you don't have the PDO driver installed

**Comment by snipe** [comment]
http://php.net/manual/en/pdo.installation.php

**Comment by kwinters1** [comment]
That worked. Thank you!
