### ISSUE TITLE
Asset Import stuck on processing. 

### ISSUE THREAD

**Issue by club227** [snipe/snipe-it#7563]
I am failing to import. The system gets on processing..... 

I did an inspect on my chrome browser and the error I got is below.
"POST http://.............../imports/process/22 500 (Internal Server Error)".

Further more I put snipe IT in debug mode and I got a php zip archive  error as shown below. 
Class 'ZipArchive' not found. I then installed the zip extension and restarted the apache server. But still asset importing is working. 

Please help.

**Comment by osimmasgard** [comment]
Same here.

**Comment by club227** [comment]
May I point out that I am using Snipe IT  v4.7.7 - build 4160 (master)

**Comment by osimmasgard** [comment]
Downgrade to PHP7.3 if you are running PHP7.4 like I was. It is now working.

**Comment by t3easy** [comment]
For docker deployments, we had to set
`MYSQL_PORT_3306_TCP_PORT=3306`
because else the .env retuns the string which leads to a type error in the DbDumper.

**Comment by jspitzen** [comment]
@t3easy That fixed my issues! And the issue that I couldn't generate exports as well! Thanks!

**Comment by Shadowfita** [comment]
Experiencing the same issue. Hosted on a windows machine with xampp. 

v4.7.8 build 4170 (g4fe689dc5)
--

**Comment by Shadowfita** [comment]
The issue for me ended up being because I didn't configure the SMTP server. Once configured I was able to process imported csv files fine.

I didn't set up the SMTP server initially because I didn't want/need it.

**Comment by club227** [comment]
I downgraded PHP to 7.3 and the system is working great. Thanks a lot guys.
