### ISSUE TITLE
Customize labels

### ISSUE THREAD

**Issue by pavilonsxx** [snipe/snipe-it#7565]
Hello Sir!
Can I edit the information displayed on the label? For example, do I want to show an asset purchase date instead of Asset name?
Thank you!

**Comment by gilesytheking90** [comment]
You would need to edit the following file to make changes to the label output and query the purchase date from the database. Note that it will overwrite any changes made when you update your Snipe IT version.

Resources -> Views -> Hardware -> labels.blade.php

More than likely, you will also need to add some custom CSS to style the label and ensure all the data displays correctly on your label

I shared some CSS code here  ( #7331 ) that might help you get started with the label styling.
