### ISSUE TITLE
Custom fields / fieldsets warning upon delete request

### ISSUE THREAD

**Issue by twsit988** [snipe/snipe-it#7566]
**Server (please complete the following information):**
 - Snipe-IT Version
v4.7.8 - build 4170 (master)
 - OS: [e.g. Ubuntu, CentOS]
CentOS
 - Web Server: [e.g. Apache, IIS]
Apache
 - PHP Version 
Latest

**Is your feature request related to a problem? Please describe.**
I noticed when I try to delete a custom field or a fieldset, it will delete it without warning. However, when I try to delete a Location, if it is being used, it wouldn't even let me delete it.

**Describe the solution you'd like**
 I think a warning or confirmation pop up should be a system-wide approach for anything you want to delete ESPECIALLY if the item/field or whatever you're deleting is in use.

**Describe alternatives you've considered**
Feature request :)

**Comment by Forusim** [comment]
As Admin I cannot delete a custom fields, if that is used within a fieldset.
As Admin I cannot delete a fieldset, if that is used within an asset model.
Are you sure, that your fields are in use?

**Comment by twsit988** [comment]
All I'm saying is it is better to pop a warning when you're deleting anything even if its not being used for any asset models.
