### ISSUE TITLE
Requestable Assets - Hide Individual Assets

### ISSUE THREAD

**Issue by enz1ey** [snipe/snipe-it#7568]
**Server (please complete the following information):**
 - Snipe-IT Version: v4.7.8 build 4170 (g4fe689dc5)
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version: 7.3.11-1+ubuntu16.04.1+deb.sury.org+1

**Is your feature request related to a problem? Please describe.**
Users often request assets from the first screen presented to them, which is the individual "Assets" tab. Users often don't see certain assets are assigned to specific locations, and will request assets in a location other than their own.

We've experimented with un-checking the "Requestable" box on the **individual assets** and leaving the "Users may request this model" box checked for the **model**, but then the "Asset Models" tab shows "0" in the "Avail" column, leading to confusion.

**Describe the solution you'd like**
We would prefer an option to hide the "Assets" tab in the "Requestable Assets" screen, while leaving the "Asset Models" screen visible. The "Avail" column should show the proper count of assets marked "Requestable."

**Describe alternatives you've considered**
We've experimented with un-checking the "Requestable" box on the individual assets and leaving the "Users may request this model" box checked for the model, but then the "Asset Models" tab shows "0" in the "Avail" column, leading to confusion.

**Additional context**
Here's a screenshot showing an example where the "Users may request this model" box is enabled for the asset **model** "Mobile Printer," however no **assets** have been enabled as "requestable" on an _individual_ basis. This screen implies there are no assets available to request.
![image](https://user-images.githubusercontent.com/6290727/68329505-5be8b980-009f-11ea-80f5-0a6c25cb7d7d.png)

**Comment by enz1ey** [comment]
Yes I’m still waiting for a response.

**Comment by DillyDilly72** [comment]
Hi we are exploring this option and found this closed issue. We tried both routes mentioned and had the same results. Any changes since this was closed?
