### ISSUE TITLE
Requestable Assets - Deployed Assets should not be Requestable

### ISSUE THREAD

**Issue by enz1ey** [snipe/snipe-it#7569]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
"Requestable Assets" screen > "Asset Models" tab > "Avail" column includes/counts assets already checked out to users.

**To Reproduce**
1. Go to "Requestable Assets"
2. Click on "Asset Models" tab
3. See "Avail" column

**Expected behavior**
Available quantity of requestable assets/models should not include deployed assets. Also, the "Assets" tab should not show a deployed asset with a "Request" button.

**Screenshots**
![image](https://user-images.githubusercontent.com/6290727/68330129-acace200-00a0-11ea-8583-10cde4b7b55f.png)

**Server (please complete the following information):**
 - Snipe-IT Version: v4.7.8 build 4170 (g4fe689dc5)
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version: 7.3.11-1+ubuntu16.04.1+deb.sury.org+1

**Desktop (please complete the following information):**
 - OS: Windows 10 1809
 - Browser: Google Chrome
 - Version: 78.0.3904.87

**Smartphone (please complete the following information):**
N/A

**Error Messages**
N/A

**Additional context**
N/A

N/A

**Comment by spotter-mmf** [comment]
Would this not be used to request an asset when it is returned?

**Comment by enz1ey** [comment]
> Would this not be used to request an asset when it is returned?

When it’s returned, it would be checked in and the status would be “ready to deploy” so it would be requestable. I don’t see any scenario where somebody would be requesting an asset already checked out to another person.

**Comment by spotter-mmf** [comment]
> > Would this not be used to request an asset when it is returned?
> 
> When it’s returned, it would be checked in and the status would be “ready to deploy” so it would be requestable. I don’t see any scenario where somebody would be requesting an asset already checked out to another person.

An example then: we have a number of projectors in the system that are entered as assets. These projectors can be checked out by staff and some have special features (speakers, size, short throw, etc). If someone wants a particular projector that is already checked out they can request it. We'll get the request and either get the requested projector to them when it's returned or hunt down the person with it and get it back if it's overdue. 

Think of it like the hold system at a library.

**Comment by enz1ey** [comment]
Okay, that’s an understandable scenario. Then perhaps this should be more of a feature request to hide the “Assets” tab on the “Requestable Assets” for those who don’t need it. I can see the need for certain assets to be individually requestable, but I think that’s the exception to the rule. There are far more scenarios where employees are going to be requesting one of any number of identical devices, so it wouldn’t matter which they get. I think that should be the default, so maybe the functionality of the “user requestable” checkbox on the asset page would enable the scenario you described. Otherwise, it’s assumed an asset is requestable in a general sense when its status is “ready to deploy,” it isn’t checked out to anybody, and that asset’s model has “user requestable” enabled. 

I still wouldn’t expect assets currently deployed to be counted in the “available” column on the “Asset Models” tab in “Requestable Assets” though, as those assets aren’t available because they’re already checked out.

**Comment by enz1ey** [comment]
Actually, thinking more about your scenario, wouldn’t those particular feature sets be specific to certain models? So users can still select an asset model with the features they require without requesting a specific individual asset. Even if the available quantity is “0” because they’re all currently checked out, the request still goes through and you can still handle the request like you normally do.

**Comment by twsit988** [comment]
Go into the specific Asset and make sure "Requestable" is not checked.

But go to Asset Models under Settings then make sure this is checked -> Users may request this model

**Comment by enz1ey** [comment]
> Go into the specific Asset and make sure "Requestable" is not checked.
> 
> But go to Asset Models under Settings then make sure this is checked -> Users may request this model
> 
> PS: You'd have to have the Asset in stock (in other words, it has to exist in the system) for you to pull up that Asset that is "available" so you can check it out to the User.

If you do that, then the asset model shows “0” available to request. I have dozens ready to deploy and still show 0 available.

**Comment by twsit988** [comment]
> > Go into the specific Asset and make sure "Requestable" is not checked.
> > But go to Asset Models under Settings then make sure this is checked -> Users may request this model
> > PS: You'd have to have the Asset in stock (in other words, it has to exist in the system) for you to pull up that Asset that is "available" so you can check it out to the User.
> 
> If you do that, then the asset model shows “0” available to request. I have dozens ready to deploy and still show 0 available.

Actually, I am wrong. Do this.

Go into the Asset model and make sure that model is checked for "Users may request this model".

Then for each individual Asset that you add, it has to be in a Status that is deployable (Ready to Deploy for example) and Requestable has to be checked otherwise it won't show up in the the Requestable page. See my attachment.

![image](https://user-images.githubusercontent.com/56913340/68442383-c454a980-020b-11ea-99da-1e07dbb87dc1.png)

**Comment by enz1ey** [comment]
> > > Go into the specific Asset and make sure "Requestable" is not checked.
> > > But go to Asset Models under Settings then make sure this is checked -> Users may request this model
> > > PS: You'd have to have the Asset in stock (in other words, it has to exist in the system) for you to pull up that Asset that is "available" so you can check it out to the User.
> > 
> > 
> > If you do that, then the asset model shows “0” available to request. I have dozens ready to deploy and still show 0 available.
> 
> Actually, I am wrong. Do this.
> 
> Go into the Asset model and make sure that model is checked for "Users may request this model".
> 
> Then for each individual Asset that you add, it has to be in a Status that is deployable (Ready to Deploy for example) and Requestable has to be checked otherwise it won't show up in the the Requestable page. See my attachment.
> 
> ![image](https://user-images.githubusercontent.com/56913340/68442383-c454a980-020b-11ea-99da-1e07dbb87dc1.png)

Correct, but this then also incorrectly counts assets that are already deployed as well.

**Comment by twsit988** [comment]
?? What do you mean?

It counts the ones that are available and NOT checked out. Makes sense to me...

**Comment by enz1ey** [comment]
> ?? What do you mean?
> 
> It counts the ones that are available and NOT checked out. Makes sense to me...

It does not. Here is a listing of all my mobile printers, there are 10 total, with 4 checked out (so only 6 are "ready to deploy" and **NOT** checked out:
![image](https://user-images.githubusercontent.com/6290727/68483384-73dc4c80-0209-11ea-9ff4-95eb5df7118f.png)

Here is what shows in the "Asset Models" tab of the "Requestable Assets" page:
![image](https://user-images.githubusercontent.com/6290727/68483452-95d5cf00-0209-11ea-9ec0-7fb9824b4870.png)

Notice the "Avail" count of the mobile printers? It says 10 available instead of 6.

**Comment by enz1ey** [comment]
Out of curiosity, I also tested changing the status of one asset to "Pending," which would make it un-deployable. This still does not change the "avail" count in the requestable assets table. So even if you manually changed the status of these assets to "undeployable," they would still appear as requestable to end users. This causes issues when somebody requests an asset which in reality isn't available, and then they want to know why they can't have their device because the site says there are plenty available.

**Comment by twsit988** [comment]
You have "Requestable" checked on 4 mobile printers so that's why they're showing up with the other 6. If they are deployed to a User, then these 4 should NOT have the "Requestable" fields checked.

**Comment by enz1ey** [comment]
> You have "Requestable" checked on 4 mobile printers so that's why they're showing up with the other 6. If they are deployed to a User, then these 4 should NOT have the "Requestable" fields checked.

Thus the reason for opening this ticket. Checking an asset out should take care of this. It’s unreasonable to have to edit an asset after checking it out for something like this, especially when you have hundreds or thousands of assets.

**Comment by dvasilevsky** [comment]
I actually added a few lines of code to get around this exact issue for my company's needs.

**BEFORE DOING THIS BACKUP THE FILES.**

Also, you may need to add:

`use App\models\AssetModel;`

To each file at the top with the other "use" helpers. I cannot remember if I added it myself.

In the files for checkout and checkin controller i added the following:

file: ~\snipeit\app\Http\Controllers\AssetCheckinController.php: placed on line 70 right after $asset->name = $request->get('name');

`		
$model = AssetModel::find(e($asset->model_id));
if($model->category_id == 2){
	$asset->requestable = '1'; 
}`

This says that if the model is a specific category, that when you press the checkin button to make the item requestable again.

Alternatively, the opposite would be this for checkout:
file: ~\snipeit\app\Http\Controllers\AssetCheckinController.php: placed on line 84 right after $expected_checkin = $request->get('expected_checkin');

`		$model = AssetModel::find(e($asset->model_id));
		if($model->category_id == 2){
			$asset->requestable = '1'; 
		}`

This will make items of category id 2 no longer requestable once the checkout button is pressed.

This has worked great for us so far and only does it for items under a specific category. To get the category ID I went into the SQL Database and just checked the id code there.

**Comment by TUCommOps** [comment]
I’m very interested in this feature! @dvasilevsky thank you so much for sharing your code! I tried this but now get an error page load when I try to check out the requested item. I backed up the files so I’m still safe, but I’d like to keep trying as I’m currently in the process of developing a workflow for this process. Any help would be greatly appreciated!
