### ISSUE TITLE
Dashboard Bug - Item name missing when asset isn't named

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#757]
A case where we don't use asset names but the dashboard is trying to pull them (I think)

![image](https://cloud.githubusercontent.com/assets/10247644/7191007/3dd5656e-e458-11e4-8fe9-05bd6a47ca7c.png)

**Comment by snipe** [comment]
"Item name missing when item isn't named". 

![explain](https://cloud.githubusercontent.com/assets/197404/7191041/6b248fae-e43f-11e4-85ba-98e4b1d91ae5.gif)

**Comment by snipe** [comment]
Do you mean it should show the serial number or something instead of a blank?

**Comment by kobie-chasehansen** [comment]
yes, I'm trying to remember the last time we had this issue but it reverted to the asset tag instead or model name instead. In this case on the dashboard the asset tag won't mean much. it might be nice to show the model name.
