### ISSUE TITLE
Docker setup needs MYSQL_PORT_3306_TCP_PORT to import

### ISSUE THREAD

**Issue by t3easy** [snipe/snipe-it#7571]
The Docker setup needs 
`MYSQL_PORT_3306_TCP_PORT=3306`
else the import fails with a type error of the DbDumper.

**Comment by rrobilla** [comment]
Type error: Argument 1 passed to Spatie\DbDumper\DbDumper::setPort() must be of the type integer, string given

Got the same error while trying to import assets from a .csv file. Using t3easy's line, or DB_PORT=3306 fixed the error.

**Comment by hapm** [comment]
Got the same error on trying to create a backup using the web interface.

**Comment by t3easy** [comment]
It is still a problem
