### ISSUE TITLE
Apache configuration I still cannot get PreFLight

### ISSUE THREAD

**Issue by paolrusso** [snipe/snipe-it#7573]
Hi All,
I amm Installing Snipe-it for the first time on a Debian 9 

I followed all the steps in the guide but I still cannot connect to preflight page, I still have the error

"D'oh. If you're seeing this, your DocumentRoot is set incorrectly. It should be set to the public directory."

The Apache is configured as follow

<VirtualHost *:80>
ServerAdmin webmaster@localhost
  <Directory /var/www/snipe-it/public>
        Allow From All
        AllowOverride All
        Options +Indexes
  </Directory>
  DocumentRoot /var/www/snipe-it/public
  ServerName xxxxxxxx.xxxxxxxs.com
        ErrorLog /var/log/apache2/snipeIT.error.log
        CustomLog /var/log/apache2/access.log combined
</VirtualHost>

Can you please help me?

Regards

**Comment by hapm** [comment]
If this is still relevant: `DocumentRoot` should be specified in`VirtualHost` and not in `Directory`. Try to move it after `ServerAdmin`. For Details refere to the [Docs on how to configure apache under linux](https://snipe-it.readme.io/docs/linuxosx).
