### ISSUE TITLE
Item Checkout Set Status to Deployed

### ISSUE THREAD

**Issue by jmartins1** [snipe/snipe-it#7575]
When checking out equipment the normal process is to lookup the desired item then going to Actions and selecting Checkout Asset. 

This issue is that doing this alone DOES NOT set the equipment's status to DEPLOYED. 
The Assets by Status graph on the Dashboard is then wrong and so are any reports run when attempting to lookup DEPLOYED equipment. 

To resolve this issue when checking out equipment the user must:

1. Lookup the desired item then go to Actions and selecting Edit Asset. 
2. Set Status to Deployed and Save.
3. Look up the desired item then go to Actions and selecting Checkout Asset. 

This is an unnecessary step. Users should simply checkout the equipment, which in turn sets the status to DEPLOYED; or provide an option at that point to set the status to an alternate verbiage.

**Comment by twsit988** [comment]
You're right. It only assumes a meta status of  Deployed after it is checked out.

What I do is leave things in "Ready to Deploy" status until you're ready to assign it or change it to "Active" status if I know my next step will be to assign it/check it out right away.

**Comment by jmartins1** [comment]
If I'm not mistaken it's already set to Ready to Deploy. What I mean is that one it place the item in my inventory it's ready to be deployed. The issue is after you check out the item. It's still set to Ready to he Deployed unless you change it manually.

⁣Sent from BlueMail ​

**Comment by twsit988** [comment]
> If I'm not mistaken it's already set to Ready to Deploy. What I mean is that one it place the item in my inventory it's ready to be deployed. The issue is after you check out the item. It's still set to Ready to he Deployed unless you change it manually. ⁣Sent from BlueMail ​
> […](#)
> On Nov 7, 2019, 7:06 PM, at 7:06 PM, twsit988 ***@***.***> wrote: You're right. It only assumes a meta status of Deployed after it is checked out. What I do is leave things in "Ready to Deploy" status until you're ready to assign it or change it to "Active" status if I know my next step will be to assign it/check it out right away. -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#7575 (comment)](https://github.com/snipe/snipe-it/issues/7575#issuecomment-551351339)

Then you probably have something setup incorrectly because the asset that is already deployed and checked out did not show up on the Requestable list. The only time it showed up is when I added another Asset and set it to the attributes as specified in my last post. You should probably triple check your settings.

**Comment by twsit988** [comment]
> If I'm not mistaken it's already set to Ready to Deploy. What I mean is that one it place the item in my inventory it's ready to be deployed. The issue is after you check out the item. It's still set to Ready to he Deployed unless you change it manually. ⁣Sent from BlueMail ​
> […](#)
> On Nov 7, 2019, 7:06 PM, at 7:06 PM, twsit988 ***@***.***> wrote: You're right. It only assumes a meta status of Deployed after it is checked out. What I do is leave things in "Ready to Deploy" status until you're ready to assign it or change it to "Active" status if I know my next step will be to assign it/check it out right away. -- You are receiving this because you authored the thread. Reply to this email directly or view it on GitHub: [#7575 (comment)](https://github.com/snipe/snipe-it/issues/7575#issuecomment-551351339)

Yup you are right. Same problem for me. I didn't get why it was setup this way but I believe it's because setting statuses is a manual process which also makes sense so the system wouldn't know what status you would want it set to after you deploy something.

**Comment by jmartins1** [comment]
If I'm not mistaken it's already set to Ready to Deploy. What I mean is that one it place the item in my inventory it's ready to be deployed. The issue is after you check out the item. It's still set to Ready to be Deployed unless you change it manually.

Sent from BlueMail <http://www.bluemail.me/r?b=15726>  

On Nov 7, 2019, at 7:06 PM, twsit988 <notifications@github.com <mailto:notifications@github.com> > wrote:

You're right. It only assumes a meta status of Deployed after it is checked out.

What I do is leave things in "Ready to Deploy" status until you're ready to assign it or change it to "Active" status if I know my next step will be to assign it/check it out right away.
