### ISSUE TITLE
I tried to make things better and I broke everything

### ISSUE THREAD

**Issue by gorilla511** [snipe/snipe-it#7578]
#### Expected Behavior (or desired behavior if a feature request)
Huge DB noob here.
I tried to update our software version using the php upgrade command now all of our records are gone. Users, assets, locations, everything. I at least took a back up before my colossal mistake but am having trouble importing it back into the database.

Using mysql db_name < sqldump.sql I get no response from the command line. Nothing happens no errors but not affirmations either.

-----

#### Actual Behavior

importing my back up does nothing and i still have lost all of my organizations records. I am 100% i am the issue here but after hours and hours of reading fear i lack the knowledge to piece it together.

-----

#### Please confirm you have done the following before posting your bug report:

- [?] I have enabled debug mode (currently in production should I still do this?)
- [ x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **Tried to update up to version 4.7 from 4.5**
- Version of Snipe-IT you're running **Currently 4.7 previously 4.5**
- Version of PHP you're running **7.2.24**
- Version of MySQL/MariaDB you're running **14.14**
- What OS and web server you're running Snipe-IT on **Ubuntu 18.04, apache2.4.29 (ubuntu)**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) **PHP composer. [followed this tutorial](https://www.linkedin.com/pulse/snipe-it-configuration-ubuntu-jay-singh/?published=t)**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error **Waiting for confirmation that I should enable this**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error **All pages**
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database
**I attempted to update the snipe it program using php upgrade.php. This did not work so I then proceeded (this is where I messed up I think) to try the manual process of upgrading. I took a back up before I did anything. I am hoping this will save me.** 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by twsit988** [comment]
Might be a good idea to try uploading the files via FTP and do a manual db restore.

Or try phpmyadmin.

**Comment by gorilla511** [comment]
Thanks for the suggestion twsit988. I so currently already have the files on the actual server which I remote into. Do you know if I am able to set up phpmyadmin on a system that has already been in production? Sorry if this is a stupid question.

**Comment by gorilla511** [comment]
Hey all,

Not sure what broke this but i got everything working again by building a whole new server and treating it as a server migration with my sql  backup file. Not the proper way but now its fixed and I will always be extra careful for now on. Lesson learned!
