### ISSUE TITLE
Add Custom field to the label

### ISSUE THREAD

**Issue by minhnguyen1921** [snipe/snipe-it#7579]
**Server (please complete the following information):**
 - Snipe-IT Version 4.7.8
 - OS: [Windows Server 2012R2]
 - Web Server: [Apache 2.4.41]
 - PHP Version 7.3.11 

**Is your feature request related to a problem? Please describe.**
Now my company has one field is Finance Code. This is a custom field and I set it is the default. I want to print a custom field Finance Code on the label with a barcode. But in the section the label setting, label visible field can't add a custom field. 

Can you add this feature?

Thanks!

**Comment by gilesytheking90** [comment]
you will need to edit the label file and query the custom field from the database. take a look at these posts for more info - #7565  #7331
