### ISSUE TITLE
Rename Fieldsets

### ISSUE THREAD

**Issue by TormundGiant** [snipe/snipe-it#7581]
Hello :)
Its like the case #5497.
I wanna rename a fieldset because ive chaned something in the assets to be more accurate.
Would be great to hear whats going on in this case. 
Thats my version: Version v4.7.8 - build 4170

**Comment by twsit988** [comment]
Rename it in your database.

custom_fieldsets.name

**Comment by sylvank** [comment]
Just want to express support for #7581 and #5497 - renaming custom fieldsets. 

v5.1.5 build 6029
