### ISSUE TITLE
LDAP sync without location 

### ISSUE THREAD

**Issue by TormundGiant** [snipe/snipe-it#7582]
Hello :)
LDAP is working very well but i wanna sync all the contacts without the location.
If im synchronizing now the contacts there is a location in it which is shown in all the assets. 
Its like a main point. 
I cant change the location in the assets, nothing is changing there because of the "main" location of the sync.

Could you please tell me which filter i should use to syn correctly?

Im actually using this one:
&(sAMAccountType=805306368)(!(userAccountControl:1.2.840.113556.1.4.803:=2))

This is the only configuration which is loading the accounts correctly until yet.

Version v4.7.8 - build 4170

**Comment by hapm** [comment]
I'm currently struggeling to get ldap sync running myself, but shouldn't it be enough to not specify a location? As I understand it, the location field is optional already.
