### ISSUE TITLE
Error while generating backup

### ISSUE THREAD

**Issue by akashIN444** [snipe/snipe-it#7588]
Error while generating backup

(what you expect to happen goes here)

-----

#### Actual Behavior

(what actually happens goes here)

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [ ] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  Fresh
- Version of Snipe-IT you're running - Version v4.6.15 - build 4011
- Version of PHP you're running - 7.0.31
- Version of MySQL/MariaDB you're running  - Mariadb 10.0
- What OS and web server you're running Snipe-IT on - Windows Server 2012 R2
- What method you used to install Snipe-IT  - install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - Error: Backup failed because The dump process failed with exitcode 1 : General error : Access is denied. . 
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - im on backup page trying to generate backup
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - Feature is disbaled in demo mode.
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way. - no error during installation.
- Indicate whether or not you've manually edited any data directly in the database - not edited.
![snipeit backup error](https://user-images.githubusercontent.com/50408472/68743965-957a7100-0619-11ea-9626-ac0a32c72521.png)

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by cgoulding93** [comment]
Is the php artistan snipeit:backup command successful?
