### ISSUE TITLE
Location Hierachy

### ISSUE THREAD

**Issue by MicaelRodrigues** [snipe/snipe-it#759]
Hi Snipe,
Congratulations on the great work!
I've come to understand that the asset allocation (checkout) to a particular location will now be a feature and that's great.
Along with this, what about the possibility of a Location Hierarchy?
Consider the case of a University... It can have multiple Locations (Associated to an address with a city, state, country) and within each one there are different Buildings (ex: Schools, I&D centers) with many classrooms, offices, laboratories and so on. 

It's would be cool, if we can checkout/checkin a Asset, or a quantity of an Asset Model to the "Laboratory X of the I&D Center Y which is located in Location Z.

What do you think about this?

Greetings

**Comment by snipe** [comment]
Hi @MicaelRodrigues - funny you should mention that, I was just thinking something similar. I think this is definitely something we would consider.

**Comment by snipe** [comment]
This is mostly done on the `v1.3.0` branch, the only thing remaining is getting the dropdown list to locations to show the hierarchy so it's not confusing.

**Comment by MicaelRodrigues** [comment]
Hi Snipe, 
I was preparing to help with this with my fork, but you've got to it first :) 
Are you considering that a child location may not have mandory data like city, address,... (because it's more like a departament or lab) or may simply inherit this information from the parent location?

Greetings

**Comment by kobie-chasehansen** [comment]
Think this would be a good change as well, would be nice to inherit those fields based off parent.

**Comment by kobie-chasehansen** [comment]
For the location dropdown list it may also be nice to show the city, state but i'm not sure if it would look cluttered or not.

**Comment by snipe** [comment]
This is out on the `1.3.0` development branch now, to be merged into `1.3.0`.
