### ISSUE TITLE
SnipeIT shows mixed content issue when loaded over https behind Ingress in k8s

### ISSUE THREAD

**Issue by kcan** [snipe/snipe-it#7592]
#### Please confirm you have done the following before posting your bug report:

- [X] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**

> My setup for snipeIT was running behind an Ingress on kubernetes cluster. The SSL loading was working for the ingress. But when trying setting up pre-light, chrome and Firefox both throws warning for mixed content issue. 

> As an example:
```
Mixed Content: The page at 'https://snipeitdev.demo.io/setup' was loaded over HTTPS, but requested an insecure script 'http://snipeitdev.demo.io/js/dist/all.js?id=bf1b244d8cc9096e4a18'. This request has been blocked; the content must be served over HTTPS.
```

> If choose to let Chrome ignore the issue, then I cannot go further with creating the user during pre-light setup. The page just reload and I am stuck on the page. 

**To Reproduce**

1. No image show when opening pre-light setup page
2. Open chrome developer tool 
3. Go to Console
4. Chrome shows mixed content warning
5. Go to right of chrome navigation bar, there is a shield symbol
6. Click on 'load unsafe scripts'
7. Click on 'create database tables'
8. Click on 'create user'
9. The page just reload and I am stuck on the page. 

**Expected behavior**

> SnipeIT works with https behind ingress during pre-light setup. 

**Screenshots**
![image](https://user-images.githubusercontent.com/3047481/68855205-0daa6a80-06de-11ea-8799-a54707554350.png)

**Server (please complete the following information):**
 - Snipe-IT Version : v.4.7.8
 - OS: [e.g. Ubuntu, CentOS] : EKS on AWS
 - Web Server: [e.g. Apache, IIS] : Ingress
 - PHP Version : PHP 7.1.33-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Oct 26 2019 19:28:18) ( NTS )

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: MacOS
 - Browser [e.g. chrome, safari]: chrome 
 - Version [e.g. 22]: 78.0.3904.97 (Official Build) (64-bit)

**Error Messages**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error:
> No error show in Debug mode
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
```
Mixed Content: The page at 'https://snipeitdev.demo.io/setup' was loaded over HTTPS, but requested an insecure script 'http://snipeitdev.demo.io/js/dist/all.js?id=bf1b244d8cc9096e4a18'. This request has been blocked; the content must be served over HTTPS.
```
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. 
> Not reproducible
- Include any additional information you can find in `storage/logs` and your webserver's logs.
> No logs under storage/logs

**Additional context**
- Is this a fresh install or an upgrade?  This is a fresh install
- What OS and web server you're running Snipe-IT on  EKS on AWS
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) EKS on AWS
- Include what you've done so far in the installation, and if you got any error messages along the way. 
I have setup Ingress as a reverse proxy for snipeIT docker instance, and have ingress configured to use https. By setup there is no error messages. The setup is working, but the snipeIT application does not work properly due to Mixed Content error. 
- Indicate whether or not you've manually edited any data directly in the database I did not manually edit any data in database

1. I tried also suggestion from https://snipe-it.readme.io/docs/configuration#section-optional-set-your-htaccess-to-redirect-to-ssl, it does not work. This will result browser to have error: ERR_TOO_MANY_REDIRECTS:
2. I tried also suggestion from https://snipe-it.readme.io/docs/reverse-proxies, it does not help. Chrome still shows Mixed Content warning.
3. It seems when running behind a reverse proxy, in snipeIT docker instance, the apache never listens on 443, but always on 80. I cannot add 443 in virtualhost settings because apache will require a ssl certificate to run behind 443, and this will not work when the reverse proxy is already doing ssl offloading.

**Comment by hapm** [comment]
> I tried also suggestion from https://snipe-it.readme.io/docs/reverse-proxies, it does not help. Chrome still shows Mixed Content warning.

Did you setup APP_TRUSTED_PROXIES correctly? Make sure the IP you see in the access.log of the snipe it container is the one you expect it to be, and that it is listed in APP_TRUSTED_PROXIES. Snipe-IT will not accept the X-Forwarded headers for ssl if the remote address is not listed as a trusted proxy. It took me some time to figure this out in my setup (not k8s, but dockerized reverse proxy with ssl offloading).

**Comment by kcan** [comment]
Hi @hapm ,

Thank you for reply. Because k8s ingress is changing IP addresses quite a lot. It seems not possible to whitelist a fixed IP.  Is it possible to allow from all IP sources? 

Previously what I have done:

1.APP_TRUSTED_PROXIES='0.0.0.0,*'
2.uncommenting 'proxies' => '*', in `config/trustedproxies.php'.
3. set header for ingress to use: proxy_set_header X-Forwarded-Proto https;

But still chrome warn about mixed content issue.

**Comment by hapm** [comment]
You can use [CIDR] notation to allow the full subnet used by k8s ingress network. In my case I used `10.0.0.0/8`.

[CIDR]:https://en.m.wikipedia.org/wiki/Classless_Inter-Domain_Routing

**Comment by kcan** [comment]
Hi @hapm,
Thank you for further reply. 
I tried to update the proxy setting:
```
root@snipeit-5769cff97d-pqcbm:/var/www/html# printenv | grep APP_TRUSTED_PROXIES
APP_TRUSTED_PROXIES=0.0.0.0/0, 8.17.0.0/16

root@snipeit-5769cff97d-pqcbm:/var/www/html# grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}' /var/log/apache2/access.log
8.17.0.141
8.17.2.143
8.17.0.141
8.17.2.143
8.17.0.141
8.17.2.143
8.17.0.141
8.17.2.143
8.17.0.141
8.17.2.143
8.17.0.141
8.17.2.143
8.17.0.141
8.17.2.143
8.17.0.141
8.17.2.143
8.17.0.141
8.17.2.143
8.17.0.141
8.17.2.143
8.17.0.141
8.17.2.143
8.17.0.141
8.17.2.143
```
But still chrome warn about mixed content issue.
Did I do correctly?

**Comment by kcan** [comment]
anyone could help? thanks

**Comment by justinh-rahb** [comment]
Ditto for me. Help.

**Comment by Marhbere** [comment]
Hello.
     May by you need set to options of Ingress with:

**`use-forwarded-headers: "true"`**

And in the config of proxy reverse set headers:

```
Host
X-Forwarded-Proto
X-Forwarded-Port
X-Forwarded-For
```

Remember too set on Snipe-it this ENV variable:

`APP_TRUSTED_PROXIES: 0.0.0.0/0 ` Warning This ACL is too much permisive

Regards.
Marhbere

**Comment by PaulChristophel** [comment]
Can this be reopened? I'm still seeing this problem with the helm chart.

**Comment by hapm** [comment]
If you know how to use the dev tools in your browser, use them to watch the network and look up the resources requested over http instead of https. Will probably be an image or something like that. Probably that helps to analyze the problem further.

**Comment by myevit** [comment]
Same issue

**Comment by snipe** [comment]
As mentioned in several other issues, you want to set `APP_ALLOW_INSECURE_HOSTS` to true. https://snipe-it.readme.io/docs/configuration#optional-misc

<img width="798" alt="Screenshot 2023-04-18 at 3 06 44 PM" src="https://user-images.githubusercontent.com/197404/232915732-4e430fca-51bc-40a3-969a-92b285f5c993.png">


<blockquote><img src="/favicon.ico" width="48" align="right"><div>Snipe-IT Documentation</div><div><strong><a href="https://snipe-it.readme.io/docs/configuration#optional-misc">Configuration</a></strong></div><div>This section is where you edit the Snipe-IT configuration file to reflect your own settings, such as your database credentials, mail server, preferred language, timezone, and so on. Some of the settings are optional, some are required.Don't be intimidated by the length of this page. The configuratio...</div></blockquote>

**Comment by myevit** [comment]
It is set to true 
<img width="229" alt="image" src="https://user-images.githubusercontent.com/13375246/232917942-a3cb6a9f-d899-4413-9031-82e3d3734bcf.png">
Have the warning Uh oh! Snipe-IT thinks your URL is https:/xxxxx, but your real URL is http://xxxxx Please update your APP_URL settings in your .env file
and Mixed content error in Chrome
Snipe-it just ignoring APP-URL
