### ISSUE TITLE
Potential install.sh improvement for Ubuntu

### ISSUE THREAD

**Issue by miniexplorer** [snipe/snipe-it#7597]
#### Please confirm you have done the following before posting your bug report:

- [No] I have enabled debug mode 

**Describe the bug**
After a fresh install, when backing up via _Admin Settings_, the browser presents the message _"Whoops, looks like something went wrong."_. However, the backup is generated and available at the next access to Admin Settings.
Looking at the directories, it turns out that the install script generated most of the files and directories with the **owner snipeitapp**, but also some with the **owner www-data**. For example:

![screenshot](https://user-images.githubusercontent.com/37416004/68955946-fc855a80-07be-11ea-994c-e35e08172bd1.PNG)

I have little experience with web servers, so it's possible that I did something wrong (sorry if it's the case 😊 ). Anyway, I thought it might be useful to inform, **for the possibility to improve the script**.
My thought would be that lines [224](https://github.com/snipe/snipe-it/blob/a73fd246954abea5466b48bcd32a579b79d48d88/snipeit.sh#L224) and [227](https://github.com/snipe/snipe-it/blob/a73fd246954abea5466b48bcd32a579b79d48d88/snipeit.sh#L227) are being executed without using _run_as_app_user_ function.
#### (UPDATE: doing `sudo chown -R snipeitapp:www-data /var/www/snipeit/storage/` didn't solve the problem either, but `sudo chown -R snipeitapp:www-data /var/www/snipeit/` solved)

**To Reproduce**
1. Install Ubuntu 18.04.3 LTS
2. Install Snipe-IT through install.sh:
2.1. wget https://raw.githubusercontent.com/snipe/snipe-it/master/install.sh
2.2. chmod 744 install.sh
2.3. ./install.sh
3. Go to _Admin Settings_ → _Generate Backup_

**Expected behavior**
Not show error on backup through _Admin Settings_.

**Server:**
 - Snipe-IT Version: v4.7.8 - build 4170 (master)
 - OS: Ubuntu 18.04.3 LTS
 - Web Server: Apache/2.4.29 (Ubuntu)
 - PHP Version: PHP 7.2.24-0ubuntu0.18.04.1 (cli) (built: Oct 28 2019 12:07:07)

**Error Messages**
- Browser: _"Whoops, looks like something went wrong."_

**Additional context**
- This is only a fresh install through install.sh.

**Comment by StantonSmall** [comment]
I have the same problem

**Comment by tdkl** [comment]
Somehow related is also the issue of using `php upgrade.php` after installing Snipe-IT via the install.sh script, just because of the `snipeitapp` user, which doesn't have privileges to write in .git.  (#7699)

I'd wish there were clear instructions about that in the Documentation, how the upgrade the instance after using install.sh.

**Comment by miniexplorer** [comment]
Yes, please. It is still relevant. Thank you.
