### ISSUE TITLE
Change the Expiring Assets Report email to not include disposed of assets.

### ISSUE THREAD

**Issue by TUmphress** [snipe/snipe-it#7598]
**Server (please complete the following information):**
 - Snipe-IT Version 4.7.8
 - OS: Windows Server
 - Web Server: IIS
 - PHP Version 

**Is your feature request related to a problem? Please describe.**
Expiring assets report, warrantees, includes disposed of assets.

**Describe the solution you'd like**
Filter disposed of assets from the report.

**Describe alternatives you've considered**
I could removed the purchase date to remove the expiration date, but I would like to have the history still.

**Additional context**

**Comment by TUmphress** [comment]
I think it is still valid, but it appears that I may be alone.

**Comment by cleandesign-hypervisor** [comment]
This still happens.

It would be good for Expiring Asset notification to not include Archived (disposed of) assets.
The current behavior leaves us either getting too many emails from Snipe, or going into the archived asset and deleting its warranty information. Neither is optimal...

**Comment by thatsnasty** [comment]
This is very annoying, been over 3 years since it was raised
