### ISSUE TITLE
forgot password not working in snipe-it

### ISSUE THREAD

**Issue by umerafridi** [snipe/snipe-it#760]
Dear All,
               forgot pasword in not working in snipe-it .error prompt to me ErrorException (E_UNKNOWN) 
Undefined index: driver

**Comment by Tortschi** [comment]
You must configure the "app/config/mail.php" File.

**Comment by umerafridi** [comment]
what should i configure in this file ?

**Comment by Tortschi** [comment]
Your Mailserver Settings.

**Comment by umerafridi** [comment]
we use gmail service so what setting i need to change

**Comment by Tortschi** [comment]
'host' => 'smtp.gmail.com',
'port' => 587,

I hope it work.

**Comment by umerafridi** [comment]
there is no mail.php file in this path

**Comment by umerafridi** [comment]
now i copy this file from some other site .now the error is look like this
Unsupported sendmail command flags [/usr/sbin/sendmail]. Must be one of "-bs" or "-t" but can include additional flags

**Comment by snipe** [comment]
Can you post your entire config file WITHOUT the password visible?

**Comment by snipe** [comment]
http://stackoverflow.com/questions/25572907/using-gmail-smtp-via-laravel-connection-could-not-be-established-with-host-smtp
Also 

http://stackoverflow.com/questions/25193467/gmail-locks-account-when-sending-mail-via-laravel

But you may just want to sign up for Mandrill. It's free up to 20k sends a month and is less hassle than setting the Gmail settings correctly

**Comment by umerafridi** [comment]
<?php

return array(

/*
|--------------------------------------------------------------------------
| Mail Driver
|--------------------------------------------------------------------------
|
| Laravel supports both SMTP and PHP's "mail" function as drivers for the
| sending of e-mail. You may specify which one you're using throughout
| your application here. By default, Laravel is setup for SMTP mail.
|
| Supported: "smtp", "mail", "sendmail"
|
*/

'driver' => 'smtp',

/*
|--------------------------------------------------------------------------
| SMTP Host Address
|--------------------------------------------------------------------------
|
| Here you may provide the host address of the SMTP server used by your
| applications. A default option is provided that is compatible with
| the Postmark mail service, which will provide reliable delivery.
|
*/
'host' => 'smtp.gmail.com',

/*
|--------------------------------------------------------------------------
| SMTP Host Port
|--------------------------------------------------------------------------
|
| This is the SMTP port used by your application to delivery e-mails to
| users of your application. Like the host we have set this value to
| stay compatible with the Postmark e-mail application by default.
|
*/

'port' => '587',

/*
|--------------------------------------------------------------------------
| Global "From" Address
|--------------------------------------------------------------------------
|
| You may wish for all e-mails sent by your application to be sent from
| the same address. Here, you may specify a name and address that is
| used globally for all e-mails that are sent by your application.
|
*/
'from' => array('address' => 'umer.shahzad@company.com', 'name' => 'DONOTREPLY'),

/*
|--------------------------------------------------------------------------
| E-Mail Encryption Protocol
|--------------------------------------------------------------------------
|
| Here you may specify the encryption protocol that should be used when
| the application send e-mail messages. A sensible default using the
| transport layer security protocol should provide great security.
|
*/

'encryption' => 'tls',

/*
|--------------------------------------------------------------------------
| SMTP Server Username
|--------------------------------------------------------------------------
|
| If your SMTP server requires a username for authentication, you should
| set it here. This will get used to authenticate with your server on
| connection. You may also set the "password" value below this one.
|
*/

'username' => '',

/*
/*
|--------------------------------------------------------------------------
| SMTP Server Password
|--------------------------------------------------------------------------
|
| Here you may set the password required by your SMTP server to send out
| messages from your application. This will be given to the server on
| connection so that the application will be able to send messages.
|
*/

'password' => ' ',

/*
|--------------------------------------------------------------------------
--------------------------------------------------------------------------
| Sendmail System Path
|--------------------------------------------------------------------------
|
| When using the "sendmail" driver to send e-mails, we will need to know
| the path to where Sendmail lives on this server. A default path has
| been provided here, which will work well on most of your systems.
|
*/

'sendmail' => '/usr/sbin/sendmail',

/*
|--------------------------------------------------------------------------
| Mail "Pretend"
|--------------------------------------------------------------------------
|
| When this option is enabled, e-mail will not actually be sent over the
| web and will instead be written to your application's logs files so
| you may inspect the message. This is great for local development.
|
*/

'pretend' => false,
);

**Comment by snipe** [comment]
Assuming you actually have a username and password in your mail config, please see the additional links I posted

**Comment by umerafridi** [comment]
where i set username and password please help me

**Comment by snipe** [comment]
You set the username and password in your mail config.

**Comment by jerm** [comment]
umerafridi: You yourself posted the sections that ask for username and password....

**Comment by umerafridi** [comment]
Problem solved thanks every one

**Comment by closterfield** [comment]
not working ..please tell me steps by steps

**Comment by closterfield** [comment]
i am stuck in this .... for registered emailid its not working says Whoops, looks like something went wrong. but for unregistered emailid its showing the correct error ..please guide
