### ISSUE TITLE
"Whoops, looks like something went wrong." - When editing an asset 

### ISSUE THREAD

**Issue by jimbo5687** [snipe/snipe-it#7602]
[laravel.log](https://github.com/snipe/snipe-it/files/3857970/laravel.log)
#### Expected Behavior (or desired behavior if a feature request)

Open the edit asset page by selecting "Edit Asset" from the "View Asset" screen. 

-----

#### Actual Behavior

When editing an asset we are a taken to a page which is blank other that the words "Whoops, looks like something went wrong." in the center of the page. 

-----

#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Fresh installation and a migration an existing database. 
- Version of Snipe-IT you're running - v4.7.8 build 4170 
- Version of PHP you're running 7.1.33
- Version of MySQL/MariaDB you're running mysql  Ver 15.1 Distrib 5.5.64-MariaDB, for Linux (x86_64) using readline 5.1
- What OS and web server you're running Snipe-IT on CentOS Linux release 7.7.1908 (Core)
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) install.sh
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error "Whoops, looks like something went wrong." 
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error. "View Asset" screen, clicking "Edit Asset" from right hand "Action" drop down menu. Same issues occurs when selecting "Create New" 
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. - N/A 
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - No 
- Include any additional information you can find in `storage/logs` and your webserver's logs.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database - No 

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by jimbo5687** [comment]
Issue is not present on the old (pre migration) server. 

Old Server Versions
"Snipe-IT version | v4.1.11-pre build 3307 (gf06852f)
Software License | AGPL3
PHP Version | 7.1.23
Laravel Version | 5.4.35"

New Server Versions
Snipe-IT version | v4.7.8 build 4170 (g4fe689dc5)
Software License | AGPL3
PHP Version | 7.1.33
Laravel Version | 5.5.47

**Comment by jimbo5687** [comment]
When hitting "New Asset" and incurring this issue, the Larevel.log file has the following entries. 

Is there any DB tools I can run to clean/check the DB? 

[laravel.log](https://github.com/snipe/snipe-it/files/3868824/laravel.log)

**Comment by Dobby16** [comment]
I have the same issue.

**Comment by jimbo5687** [comment]
Having spoken to a PHP we have at work, there was a missing table in the Database due to the version between the old and new server being on different versions. 

We added the field "default_label" in table "status_labels" and the issue is now resolved. 

@Dobby16 If you get debug mode on, it will likely display the exact issue you are having in the error on the page (instead of the "Whoops" message).

**Comment by snipe** [comment]
You should never, ever manually create fields or tables. Doing so will compromise your ability to upgrade moving forward. 

If you had run migrations, this probably would never have happened. If you tried to run migrations and it didn’t work, you should have asked us.
