### ISSUE TITLE
[BUG] Nested location - searching lower levels

### ISSUE THREAD

**Issue by Diniver** [snipe/snipe-it#7604]
#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [X] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
During creation of asset I am unable to search default location deeper than top level location.

**To Reproduce**

1. Start creation of new asset
2. go to default location
3. start typing the location which you need

Note: I am able to search only top level location 

**Expected behavior**
I expect to be able to search for lower level locations
Place
--floor
----room

**Screenshots**

![image](https://user-images.githubusercontent.com/31882138/69139446-7025b100-0ab8-11ea-81ac-783611e76509.png)
![image](https://user-images.githubusercontent.com/31882138/69139547-a6633080-0ab8-11ea-8543-bec62d5d9a43.png)
![image](https://user-images.githubusercontent.com/31882138/69139577-b3801f80-0ab8-11ea-8460-f4fbf1e434d1.png)
![image](https://user-images.githubusercontent.com/31882138/69139587-ba0e9700-0ab8-11ea-8bdb-3387e647c369.png)

**Server (please complete the following information):**
https://demo.snipeitapp.com

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 70.0.1

**Additional context**
Problem occure after update on Oct 2, 2019
https://github.com/snipe/snipe-it/pull/7483

**Comment by snipe** [comment]
This is a confirmed bug, and we’re working on a fix

**Comment by Diniver** [comment]
Thanks for fast responce. Since it is confirmed, I will close the issue.
