### ISSUE TITLE
 Function mcrypt_get_iv_size() is deprecated error when running php artisan snipeit:legacy-recrypt

### ISSUE THREAD

**Issue by asmiah** [snipe/snipe-it#7606]
#### Please confirm you have done the following before posting your bug report:

- [x] I have enabled debug mode yes
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues) yes

**Describe the bug**
Getting below error when running: php artisan snipeit:legacy-recrypt as per: https://snipe-it.readme.io/v4.0/docs/upgrading-to-v4

In McryptEncrypter.php line 46:

  Function mcrypt_get_iv_size() is deprecated

**To Reproduce**
1. running upgrade from v3 to v4 and trying to Step 10

**Expected behavior**
For the command to just work?

**Screenshots**
![image](https://user-images.githubusercontent.com/11227108/69241102-eb10c980-0b95-11ea-9fad-6ca8b5708fbe.png)

**Server (please complete the following information):**
 - Snipe-IT Version : 3.6.6 to v4
 - OS: [e.g. Ubuntu, CentOS] 7.7
 - Web Server: [e.g. Apache, IIS] apache
 - PHP Version 7.3

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 10
 - Browser [e.g. chrome, safari] All
 - Version [e.g. 22] All

**Smartphone (please complete the following information):**

**Error Messages**

In McryptEncrypter.php line 46:

  Function mcrypt_get_iv_size() is deprecated

from laravel.log
production.ERROR: Function mcrypt_get_iv_size() is deprecated {"exception":"[object] (ErrorException(code: 0): Function mcrypt_get_iv_size() is deprecated at /var/www/html/snipeit/app/LegacyEncrypter/McryptEncrypter.php:46)

**Additional context**
- Is this a fresh install or an upgrade? 
- What OS and web server you're running Snipe-IT on
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc)
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly in the database

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by hapm** [comment]
Looks like the reencryption tool is broken for php >= 7.2. You could still run it on >=7.1.2 and <7.2but the command will not work under 7.3 for sure. As for expected behaviour: there should be a check, that errors out cleanly when the command is run on php>=7.2.

**Comment by asmiah** [comment]
Okay I'll roll back and try again :(

**Comment by asmiah** [comment]
@hapm Thanks for your prompt response, not sure if you can help with this, I had got this error initially but didn't ask after your last comment as I assumed it may also be php 7.3 related.

So I have reverted back to a snapshot and upgraded to php 7.1 now.

Snipe loads but in the laravel.log I can see the below:

[2019-11-20 13:41:27] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to undefined function App\Models\ldap_connect()' in /var/www/html/snipeit/app/Models/Ldap.php:43

php ldap is installed if I run: yum install php-ldap

I see:

Package php-ldap-7.1.33-1.el7.remi.x86_64 already installed and latest version
Nothing to do

Any ideas?

**Comment by hapm** [comment]
Check if the ldap module is enabled:

```
php -m | grep ldap
```

If not, enable it as is appropriate for your plattform, possibly one of:

```
php7enmod ldap 
php7enmod php-ldap
phpenmod ldap
phpenmod php-ldap
```

If the module is enabled, but not recognized, this could mean there is a different php configuration loaded for your site. Put a [phpinfo] file in your public folder and visit it to check the php environment configuration.

[phpinfo]:https://www.php.net/manual/en/function.phpinfo.php#example-571

**Comment by asmiah** [comment]
So regardless of what I did and what version of PHP I used I was unable to do an in place upgrade of Snipe on the same server running php5.6 and trying to upgrade to php7.1 php7.2 and php7.3

I then resulted to setting up a new server with php7.2 installing snipe a fresh and then doing a database migration from current to new server and then running php artisan migrate...

The new version of Snipe(v4.7.8) then worked fine.

A quick few questions though on a seperate note/issue:

So when we intend to check a machine out we would like the status to automatically change to deployed from "Reserved" or "In stock - built" is there any exisiting functionality that does this?

Secondly as I understand, LDAP enabled should allow me to login using my LDAP credentials and should the password not match it fall back to local authentication, however this is not working and I cannot get any users to login authenticating with LDAP, when I test the connection this works successfully under "Admin"->"LDAP" and I can also authenticate using the username and password field under "Admin"->"LDAP" LDAP Sync under "People" also works fine without any issues.

can anyone advise?

@snipe  please can you help/advise?
