### ISSUE TITLE
PHP 7.4rc - ErrorException: Trying to access array offset on value of type int

### ISSUE THREAD

**Issue by bwilkinson23** [snipe/snipe-it#7607]
CentOS 8 1905 
v4.7.8 Build 4170
PHP 7.4.0RC6
Laravel 5.5.47

I stood up a CentOS 8 Apache server and installed Snipe-IT over the last few days. I ran into a few hurdles but there was one in particular that I thought is worth sharing in case anyone else runs into a similar thing.

At the pre-flight setup, after reviewing the results on the first page and click the button "Next: Create Database Tables", I would get a "Whoops" error. I looked at the logs in snipe-it/storage/logs/laravel.log and found this error saying:

ErrorException: Trying to access array offset on value of type int

I searched online and found this which basically says this is an issue in the PHP version: 

https://github.com/symfony/symfony/pull/32806

Then I issued the change detailed here:

https://github.com/symfony/symfony/pull/32806/commits/5f451e6f7074976aae60a65ba144fff684b7b48c

This solved the issue for me and I am now on my way.

**Comment by ajsy** [comment]
@bwilkinson23 Thank you very much for the fix
today after php upgrade from 7.3 to 7.4 I had the same error with ldap sync

your fix resolve the problem
