### ISSUE TITLE
LDAP sync with GSuite (Cloud Identity)

### ISSUE THREAD

**Issue by farizazmi** [snipe/snipe-it#7608]
**Server (please complete the following information):**
 - Snipe-IT Version v4.7.6
 - OS: [e.g. Ubuntu, CentOS] Windows
 - Web Server: [e.g. Apache, IIS] Apache
 - PHP Version 7.7

**Is your feature request related to a problem? Please describe.**
Our Snipe-it users 100% synced via LDAP from our Active Directory. Unfortunately, our management decided to shut this down very soon. As a replacement, we will be using a solution from Google GSuite (Cloud Identity). 

**Describe the solution you'd like**
Please help to implement LDAP/CI (cloud identity)

**Describe alternatives you've considered**
I am not really sure about what'd be the alternative for this, at the moment this will cause a major loss for me.

**Additional context**
Please help.

Thanks in advanced!

**Comment by hapm** [comment]
As soon as you can bind against an LDAP, that provides the required permission to list the users, that should be available in snipeit, I guess you can work out the needed filter and fieldname. If you aren't sure that this is the case, I would refer you to the documents available about this from Google. A fast Google search for "GSuite LDAP" got me his results. Among them was [this article], that looks like it should be no problem, if you have the right license.

[this article]:https://support.google.com/a/answer/9048516?hl=en

**Comment by jaimemcm** [comment]
I am looking to set this up with our google LDAP but can not fund any instructions on how to go about this.  I have reached out to support and they were unable to help me.  I am using the snipe cloud hosted version.  
I can not have welcome emails sent to any users and I do not want them to have access to login to an account with snip.

**Comment by Mistic92** [comment]
We are using only gsuite/workspace without any ldap and as I see there is no easy way to integrate snipe-it with gsuite users/organizations/groups etc.
Are there any plans to suppor it?
