### ISSUE TITLE
Import Export File and History

### ISSUE THREAD

**Issue by nemo081** [snipe/snipe-it#7611]
- [ ] NO debug
- [x] I have read [checked the Common Issues page]
-----
Ubuntu 18.04 Server
Snipe-IT 4.7.8
phpmyadmin 4.9
PHP 7.2
-----

Hello, 
in the old version of the program (1.2.7beta) the files I uploaded for the assets, were saved in the directory "./var/www/html/app/private_uploads" 
in the new version (4.7.8) instead of
"./var/www/snipeit/storage/private_uploads/assets/".

I tried to copy the files from the old VM to the new one in the new folder but they are not uploaded.

Is there a way to import files and history from the old version to the new one?

THANK YOU

**Comment by snipe** [comment]
Just move the physical files and you’ll probably be fine.

**Comment by nemo081** [comment]
Hi, thanks for the answer.
I tried, I copied the files to the new location but they are not read.

**Comment by nemo081** [comment]
![Untitled](https://user-images.githubusercontent.com/58031098/69526499-950f9d80-0f6a-11ea-9c1f-600307ad9860.png)

Nothing, nothing.
I can't load history and files from 1.2.7beta.
Any ideas?
