### ISSUE TITLE
Inventory scripts

### ISSUE THREAD

**Issue by globule** [snipe/snipe-it#7613]
**Server (please complete the following information):**
 - Snipe-IT Version v4.7.8 - build 4170
 - OS: Debian, Windows
 - Web Server: Apache2
 - PHP Version 7.3

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Please consider offering script to inventory items and submit information via the API.

**Describe alternatives you've considered**
Open-audit does it. You should take a look at their script for different OS !

[audit-scripts.zip](https://github.com/snipe/snipe-it/files/3879597/audit-scripts.zip)

**Additional context**
Attached files

**Comment by snipe** [comment]
@globule you're welcome to open a pull request. We as policy do not download zip files submitted here. Additionally, our README has several options that already work with our API.
