### ISSUE TITLE
Is it possible to create custom notification?

### ISSUE THREAD

**Issue by linkinpio** [snipe/snipe-it#7614]
#### Expected Behavior (or desired behavior if a feature request)

Hello,
Is it possible to create customer notification, where you can define your own query and have emeil notification about it. 
For example the one you would put in the cronjob 
/path/to/php /path/to/your/snipe-it/artisan snipeit:inventory-checked-out-assets

and it would send email notification about all checked out assets if they are any checked out assets. 
best regards
linkinpio

-----

#### Actual Behavior

Can find any data in the documentation or faq about it.

-----

#### Please confirm you have done the following before posting your bug report:

- [ ] I have enabled debug mode 
- [x] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)
N/A not an issue
-----
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? **LAB install for now fresh** 
- Version of Snipe-IT you're running - **v4.7.5 build 4133 (g0e93495ca)**
- Version of PHP you're running - **7.2.20**
- Version of MySQL/MariaDB you're running -  **Ver 15.1 Distrib 5.5.60-MariaDB, for Linux (x86_64) using readline 5.1**
- What OS and web server you're running Snipe-IT on - **CentOS Linux release 7.6.1810 (Core)**
- What method you used to install Snipe-IT (install.sh, manual installation, docker, etc) - **install.sh**
- WITH DEBUG TURNED ON, if you're getting an error in your browser, include that error - **N/A**
- What specific Snipe-IT page you're on, and what specific element you're interacting with to trigger the error - **N/A**
- If a stacktrace is provided in the error, include that too. - **N/A**
- Any errors that appear in your browser's error console. - **N/A**
- Confirm whether the error is reproducible on the demo: https://snipeitapp.com/demo. - **N/A**
- Include any additional information you can find in `storage/logs` and your webserver's logs. - **N/A**
- Include what you've done so far in the installation, and if you got any error messages along the way. - **N/A**
- Indicate whether or not you've manually edited any data directly in the database - **NO**

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

https://snipe-it.readme.io/docs/getting-help

**Comment by twisted3motions** [comment]
Notifications and checkout could use some polish.

a)  When my users are checked out an item, they receive an agreement, info contact if there was a mistake, etc.  They agree to taking the item.
b)However, while I have a report of who didn't agree....  I don't have any easy way of re-sending the mail to them.
c)finally, I would like checkouts to renew on a yearly basis.  IE.  Users to get another notice every 12 months agreeing if they have the item.
