### ISSUE TITLE
Unable to install with composer.json

### ISSUE THREAD

**Issue by irobinett** [snipe/snipe-it#762]
I am receiving the following when trying to run the composer install, using the included json file.  I admittedly am new to the composer world, and hope this is an easy fix.  I have looked for a solution for the past several hours, and come up short.  Any guidance will be much appreciated.

Command: composer install

Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/framework v4.2.17 requires classpreloader/classpreloader ~1.0.2 ->
 no matching package found.
    - laravel/framework v4.2.16 requires classpreloader/classpreloader ~1.0.2 ->
 no matching package found.
    - laravel/framework v4.2.15 requires classpreloader/classpreloader ~1.0.2 ->
 no matching package found.
    - laravel/framework v4.2.14 requires classpreloader/classpreloader ~1.0.2 ->
 no matching package found.
    - laravel/framework v4.2.13 requires classpreloader/classpreloader ~1.0.2 ->
 no matching package found.
    - laravel/framework v4.2.12 requires classpreloader/classpreloader ~1.0.2 ->
 no matching package found.
    - laravel/framework v4.2.11 requires classpreloader/classpreloader ~1.0.2 ->
 no matching package found.
    - laravel/framework v4.2.10 requires classpreloader/classpreloader ~1.0.2 ->
 no matching package found.
    - laravel/framework 4.2.x-dev requires classpreloader/classpreloader ~1.0.2
-> no matching package found.
    - Conclusion: don't install laravel/framework v4.2.9
    - Conclusion: don't install illuminate/support 5.0.x-dev
    - Conclusion: don't install laravel/framework v4.2.8
    - Conclusion: don't install illuminate/support v5.0.26
    - Conclusion: don't install illuminate/support v5.0.25
    - Conclusion: don't install laravel/framework v4.2.7
    - Conclusion: don't install illuminate/support v5.0.22
    - Conclusion: don't install illuminate/support v5.0.4
    - Conclusion: don't install laravel/framework v4.2.6
    - Installation request for dinesh/barcode dev-master -> satisfiable by dines
h/barcode[dev-master].
    - Can only install one of: laravel/framework[v4.2.0, 5.0.x-dev].
    - Can only install one of: laravel/framework[v4.2.0-BETA1, 5.0.x-dev].
    - Can only install one of: laravel/framework[v4.2.1, 5.0.x-dev].
    - Can only install one of: laravel/framework[v4.2.2, 5.0.x-dev].
    - Can only install one of: laravel/framework[v4.2.3, 5.0.x-dev].
    - Can only install one of: laravel/framework[v4.2.4, 5.0.x-dev].
    - Can only install one of: laravel/framework[v4.2.5, 5.0.x-dev].
    - dinesh/barcode dev-master requires illuminate/support 5.0.x -> satisfiable
 by laravel/framework[5.0.x-dev], illuminate/support[5.0.x-dev, v5.0.0, v5.0.22,
 v5.0.25, v5.0.26, v5.0.4].
    - Conclusion: don't install illuminate/support v5.0.0
    - Installation request for laravel/framework 4.2.* -> satisfiable by laravel
/framework[4.2.x-dev, v4.2.0, v4.2.0-BETA1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v
4.2.13, v4.2.14, v4.2.15, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2
.6, v4.2.7, v4.2.8, v4.2.9].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common
 problems.

C:\inetpub\wwwroot\snipe-it>

**Comment by snipe** [comment]
This one isn't your fault. I think the folks who maintain classpreloader changed their version number after the fact or something. :( 

Try replacing the `require` block in your `composer.json` to this:

	"require": {
		"classpreloader/classpreloader": "1.*",
		"symfony/console": "~2",
        "symfony/yaml": "~2",
        "symfony/config": "~2",
        "symfony/stopwatch": "~2",
		"laravel/framework": "4.2.17",
		"doctrine/dbal": "v2.4.2",
		"cartalyst/sentry": "2.1.5",
		"barryvdh/laravel-debugbar": "1.x",
		"chumper/datatable": "2.3.*",
		"dinesh/barcode": "4.0.*@dev",
		"intervention/image": "dev-master",
		"league/csv": "~7.0",
		"erusev/parsedown": "dev-master"
	},

Delete your `composer.lock` and run `composer update`, and see if that works.

**Comment by irobinett** [comment]
Much appreciated, Snipe!  This worked perfectly and I was able to troubleshoot the rest of the issues.  This is going to be a fantastic utility for me.

**Comment by snipe** [comment]
Awesome, glad it worked! 

![gmnj5vx](https://cloud.githubusercontent.com/assets/197404/7265709/0660f856-e853-11e4-963a-bd75be570722.gif)
