### ISSUE TITLE
Backup & Restore Snipe-IT

### ISSUE THREAD

**Issue by mrcuong** [snipe/snipe-it#765]
Hi!

I want backup & restore Snipe-IT ?

Thanks!

**Comment by snipe** [comment]
What is your question, specifically?

**Comment by rp-tech** [comment]
@mrcuong why not just back up the mysql database and use a script / scheduled job to back up the Snipe-It app folder? This is what I do for all my apache web apps and it works well.

**Comment by mrcuong** [comment]
@snipe :Now, I install snipe-it on Server01. 
This is Server01 can error OS, disk fail ...
I want backup and restore  all database snipe-it when server error !
