### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by jonnymbir** [snipe/snipe-it#767]
Could someone help me out with the installation. I placed the folder in xampp and browsed to it expecting to see a welcome page for installation but it just takes me to the parent directory.

I also run : php composer.phar install but i had : could not open input file : composer .phar

Please i need help. Very urgent though.
Thanks for your help.

**Comment by snipe** [comment]
http://snipeitapp.com/documentation/installing-on-wamp/

**Comment by d2205** [comment]
What you need to do before this is step is to install composer.
`curl -sS https://getcomposer.org/installer | php`
