### ISSUE TITLE
Support Installation on YunoHost

### ISSUE THREAD

**Issue by timjcraig** [snipe/snipe-it#771]
Are there any plans to support Snipe-it installation on Yunohost?

**Comment by dbierspb** [comment]
If Yunohost supports the required PHP packages and such then yes you can install it on Yunohost.

**Comment by timjcraig** [comment]
Yunohost requires application to be packaged for installation see link below, https://yunohost.org/#/packaging_apps

**Comment by snipe** [comment]
We do not currently have any plans to package Snipe-IT app up for Yunohost.
