### ISSUE TITLE
PHP Error "Failed opening ../vendor/autoload.php"

### ISSUE THREAD

**Issue by AquaGoat** [snipe/snipe-it#773]
I just finished going through the IIS install instructions for Snipe-IT.  It went well.  I had to add the fileinfo extension to PHP.  When I used composer to install artisan there were no prompts or anything, no error messages either (instructions say to follow prompts) so I'm not sure if thats related.

Anyways, now when I try to browse to my internal site, I get no errors in the browser.  When I check my PHP errors I have this:

"PHP Warning:  require(C:\inetpub\wwwroot\snipe-it\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\inetpub\wwwroot\snipe-it\bootstrap\autoload.php on line 17"

**Comment by snipe** [comment]
Did you actually run the composer install though? (Before the artisan install). That looks like composer install was never run successfully.

**Comment by AquaGoat** [comment]
You know what.  I tried to run the composer install again, and I see that it's failing to download d11wtq/boris.

I tried adding some of the fixes found [here](https://github.com/borisrepl/boris/issues/97#issuecomment-77574714) but they don't seem to work either.

**Comment by AquaGoat** [comment]
I got it.  Thanks for pointing me in the right direction.  I changed the directories it was looking for boris in the composer.lock file to https://github.com/borisrepl/boris/archive/1.0.8

Then it installed. Now the artisan install actually did its job and everything is happy!

**Comment by snipe** [comment]
That's going to cause you problems when you update though. Can you tell me which version of Snipe-IT you're using?

**Comment by AquaGoat** [comment]
Release v1.2.6.1

**Comment by snipe** [comment]
I *think* the Boris issue was resolved in the upcoming version, so you might be okay. (He moved the repo, which donked all of the references.)

**Comment by AquaGoat** [comment]
Ok.  I'll make sure to test out the update in my test environment.

Thanks again.
