### ISSUE TITLE
Interface issue when viewing user

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#774]
the contact user info gets pushed to the bottom of the screen.

![image](https://cloud.githubusercontent.com/assets/10247644/7404983/bae1c2f8-eeb9-11e4-8bfe-9af287d853df.png)

**Comment by snipe** [comment]
In what version?

**Comment by kobie-chasehansen** [comment]
just pulled a few moments ago DEV, was in older build as well

**Comment by snipe** [comment]
Hm, not seeing this on the demo. http://demo.snipeitapp.com/admin/users/1/view

**Comment by kobie-chasehansen** [comment]
Added a couple of assets to your user in the demo, didn't do it. Then attached a license and it started doing it.

**Comment by snipe** [comment]
Ahh, got it - thanks

**Comment by kobie-chasehansen** [comment]
what's odd is the user that I used as an example doesn't have licenses, he does however have an accessory assigned.

**Comment by snipe** [comment]
I'm sure the HTML is just donked somewhere around there - I'll get it sorted. Thanks for the extra troubleshooting!

**Comment by kobie-chasehansen** [comment]
Thanks, glad I could help!

**Comment by snipe** [comment]
Can you grab the latest from dev and see if that fixes it?

**Comment by kobie-chasehansen** [comment]
Fixed, entire view looks much better :) Thank you!
