### ISSUE TITLE
QR Codes not working

### ISSUE THREAD

**Issue by omriasta** [snipe/snipe-it#777]
I ran through install, system is running fine and added users and assets. I go to Admin->Settings, Hit the edit button.
I can change the company name, Results per page, send alerts etc and save.
When I try to check the "Display QR code", "Generate auto-incrementing IDs" and "This Snipe-IT install can load scripts from the outside world", this does not get saved. Checked the SQL table and it is not being changed. Also tried changing the value to "1" manually. It does change the appearance on the settings page but does not actually display qr codes. GD is enabled, results below. Any suggestions where to start?

php5 -i | grep -i --color gd
/etc/php5/cli/conf.d/20-gd.ini,
gd
GD Support => enabled
GD Version => 2.1.1-dev
gd.jpeg_ignore_warning => 0 => 0

**Comment by snipe** [comment]
This has already been fixed on develop, and will be going out in the next release.

**Comment by snipe** [comment]
Actually, wait. " It does change the appearance on the settings page but does not actually display qr codes. " <-- what does this bit mean, exactly?

**Comment by omriasta** [comment]
If I modify the value in the settings table to "1" the check box is ticked on the settings page but when I create an asset or edit an existing I dont see qr codes or any options for them.

On Apr 30, 2015 4:47 PM, snipe <notifications@github.com> wrote:

Actually, wait. " It does change the appearance on the settings page but does not actually display qr codes. " <-- what does this bit mean, exactly?

**Comment by snipe** [comment]
What do you have selected for the type of QR code? QR codes should appear on the asset detail view, and you should be able to select them from the listing page, click on "Generate labels" and see a page with them on it.

**Comment by omriasta** [comment]
Type is QR codes. Just left the office but will double check and send screenshot if I can't find later.

On Apr 30, 2015 4:51 PM, snipe <notifications@github.com> wrote:

What do you have selected for the type of QR code? QR codes should appear on the asset detail view, and you should be able to select them from the listing page, click on "Generate labels" and see a page with them on it.

**Comment by omriasta** [comment]
My bad, was looking in the asset edit screen instead of just clicking the asset to view details...
You can close this and THANKS AGAIN FOR YOUR FAST AND GREAT SUPPORT!

**Comment by snipe** [comment]
Awesome - glad go hear it wasn't an actual bug :)

**Comment by snipe** [comment]
*to

**Comment by snipe** [comment]
Any luck with a screenshot?

**Comment by omriasta** [comment]
Nope...thought we closed this ticket....was looking for them on the asset edit page....found them on the asset detail page.

On May 2, 2015 3:22 PM, snipe <notifications@github.com> wrote:

Any luck with a screenshot?

**Comment by snipe** [comment]
You're right, I'm a dummy. :P I had this window still open from before, as I was closing tickets. 

![tumblr_inline_nmpxhp5cea1raprkq_500](https://cloud.githubusercontent.com/assets/197404/7442472/d3ad81a4-f0c7-11e4-8d98-60eafea89194.gif)
