### ISSUE TITLE
Feature Request - Check out accessory item to nobody...

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#778]
We are using the accessory section to track toner and other consumables and while it helps keep an eye on stock the items never really come back to us.

to solve for this I was thinking maybe some kind of checkbox during accessory checkout to mark that checkout as a consumable and not require a user to be assigned to it.

**Comment by snipe** [comment]
Consumables is actually on the roadmap already as its own thing. I'd rather not complicate the existing stuff by checking out to no one.
