### ISSUE TITLE
Composer Install d11wtq/boris v1.0.8 download issues

### ISSUE THREAD

**Issue by jzderadicka** [snipe/snipe-it#779]
iis 7.5
php 5.6
snipe-it 1.2.6.1

  - Installing d11wtq/boris (v1.0.8)
    Downloading: Connecting...    Failed to download d11wtq/boris from dist: The
 "https://api.github.com/repos/d11wtq/boris/zipball/125dd4e5752639af7678a22ea597
115646d89c6e" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing d11wtq/boris (v1.0.8)
    Cloning 125dd4e5752639af7678a22ea597115646d89c6e

 [RuntimeException]
 Failed to clone git@github.com:d11wtq/boris.git, git was not found, check t
 hat it is installed and in your PATH env.
 'git' is not recognized as an internal or external command,
 operable program or batch file.

I tried deleting composer clear-cache and removing composer.lock in snipe-it root, however that does not seem to fix it as it did for others.  After deleting and running composer install.

Command: composer install

Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/framework v4.2.17 requires classpreloader/classpreloader ~1.0.2 ->
 no matching package found.
    - laravel/framework v4.2.16 requires classpreloader/classpreloader ~1.0.2 ->
 no matching package found.
    - laravel/framework v4.2.15 requires classpreloader/classpreloader ~1.0.2 ->
 no matching package found.
    - laravel/framework v4.2.14 requires classpreloader/classpreloader ~1.0.2 ->
 no matching package found.
    - laravel/framework v4.2.13 requires classpreloader/classpreloader ~1.0.2 ->
 no matching package found.
    - laravel/framework v4.2.12 requires classpreloader/classpreloader ~1.0.2 ->
 no matching package found.
    - laravel/framework v4.2.11 requires classpreloader/classpreloader ~1.0.2 ->
 no matching package found.
    - laravel/framework v4.2.10 requires classpreloader/classpreloader ~1.0.2 ->
 no matching package found.
    - laravel/framework 4.2.x-dev requires classpreloader/classpreloader ~1.0.2
-> no matching package found.
    - Conclusion: don't install laravel/framework v4.2.9
    - Conclusion: don't install illuminate/support 5.0.x-dev
    - Conclusion: don't install laravel/framework v4.2.8
    - Conclusion: don't install illuminate/support v5.0.28
    - Conclusion: don't install illuminate/support v5.0.26
    - Conclusion: don't install laravel/framework v4.2.7
    - Conclusion: don't install illuminate/support v5.0.25
    - Conclusion: don't install illuminate/support v5.0.22
    - Conclusion: don't install laravel/framework v4.2.6
    - Conclusion: don't install illuminate/support v5.0.4
    - Installation request for dinesh/barcode dev-master -> satisfiable by dines
h/barcode[dev-master].
    - Can only install one of: laravel/framework[v4.2.0, 5.0.x-dev].
    - Can only install one of: laravel/framework[v4.2.0-BETA1, 5.0.x-dev].
    - Can only install one of: laravel/framework[v4.2.1, 5.0.x-dev].
    - Can only install one of: laravel/framework[v4.2.2, 5.0.x-dev].
    - Can only install one of: laravel/framework[v4.2.3, 5.0.x-dev].
    - Can only install one of: laravel/framework[v4.2.4, 5.0.x-dev].
    - Can only install one of: laravel/framework[v4.2.5, 5.0.x-dev].
    - dinesh/barcode dev-master requires illuminate/support 5.0.x -> satisfiable
 by laravel/framework[5.0.x-dev], illuminate/support[5.0.x-dev, v5.0.0, v5.0.22,
 v5.0.25, v5.0.26, v5.0.28, v5.0.4].
    - Conclusion: don't install illuminate/support v5.0.0
    - Installation request for laravel/framework 4.2.* -> satisfiable by laravel
/framework[4.2.x-dev, v4.2.0, v4.2.0-BETA1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v
4.2.13, v4.2.14, v4.2.15, v4.2.16, v4.2.17, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2
.6, v4.2.7, v4.2.8, v4.2.9].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your min
imum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> f
or more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common
 problems.

If anyone could point me in the right direction.

Thanks

**Comment by snipe** [comment]
If you swap out the `require` section of your `composer.json` with this:

	"require": {
		"classpreloader/classpreloader": "1.*",
		"symfony/console": "~2",
        "symfony/yaml": "~2",
        "symfony/config": "~2",
        "symfony/stopwatch": "~2",
		"laravel/framework": "4.2.17",
		"doctrine/dbal": "v2.4.2",
		"cartalyst/sentry": "2.1.5",
		"barryvdh/laravel-debugbar": "1.x",
		"chumper/datatable": "2.3.*",
		"dinesh/barcode": "4.0.*@dev",
		"intervention/image": "dev-master",
		"league/csv": "~7.0",
		"maknz/slack": "dev-master",
		"erusev/parsedown": "dev-master"
	},

And re-run the composer install, what happens?

**Comment by jzderadicka** [comment]
Thanks for the help snipe, this worked and appears to already be included with 1.2.7.

I went ahead and downloaded snipe-it 1.2.7, received same first error with composer.lock but once removed composer install completed without issues.
