### ISSUE TITLE
Asset Logs woes

### ISSUE THREAD

**Issue by cwhittl** [snipe/snipe-it#781]
In one of the updates 1_2_3 was where we were before it looks like there was a bug that we didn't see until now....  

Basically the asset logs were updated with 00000 timestamps on created/updated and not actually timestamps.  

Is there anyway to get these back or at least rough times?

It doesn't look like the bug exists anymore so we're good going forward but anything between now and Jan 27 of this year (when we updated last) has the problem.

Thanks!

**Comment by snipe** [comment]
Unfortunately, the asset logs are the only place where those time stamps are kept. :( maybe update all of the 0000 records to Jan 27, so you have something at least rough?

**Comment by cwhittl** [comment]
thanks Snipe!
