### ISSUE TITLE
Consumables section 

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#782]
Similar to accessories, but no need to assign consumables

**Comment by madd15** [comment]
I can see if i can find my copy if you want

**Comment by snipe** [comment]
For folks looking for consumables, how would you want this to work? Just decrementing the qty, or actually assigning it to a location?

**Comment by kobie-chasehansen** [comment]
Our primary use is for toner, we would like to be able to assign to a printer/location and be able to pull that printer/location up in the future to see what its toner usage is.

**Comment by snipe** [comment]
There is a (slightly broken) version of consumables on the `1.3.0` branch. Should not be considered stable, but it's getting there.

**Comment by snipe** [comment]
(More info at https://github.com/snipe/snipe-it/commit/19604480bbecc29211e399a3f3372127abd22098)
