### ISSUE TITLE
Automatically refresh the page when selecting # of items / Show All

### ISSUE THREAD

**Issue by rp-tech** [snipe/snipe-it#786]
As the title says, when selecting the # of items or Show All, the page does not refresh.

**Comment by snipe** [comment]
I don't think I understand what this refers to

**Comment by rp-tech** [comment]
Ahh, it seems to be working now.

Must have been a browser issue. Basically when I was selecting the dropdown box for the # of items it wasn't updating immediately to show the new selection - if there was only 10 items showing and I clicked all, it would remain @ 10 items. But now it seems to be working for some reason - I can only assume it was an issue with Firefox?

Sorry! I'll test more next time to ensure I can re-produce the issue properly.
