### ISSUE TITLE
403 Forbidden Error

### ISSUE THREAD

**Issue by yodarx** [snipe/snipe-it#788]
Hi there

I just installed snipe-it on my webserver (Ubuntu 14.04 LTS / Apache 2.4.7).
Everything worked fine, but now when I try to access the url which I configured in app/config/production/app.php I get:

    Forbidden
    You don't have permission to access / on this server.

I double checked the manual.. but it seems that I did everything as said.
Also I have other websites on this server which I can access without any problems.

In the logs I see nothing (apache log & app/storage/logs) and mod_rewrite is enabled, user and group are correct.
For testing I gave the whole directory 777 rights, but still the same error.

Do you guys have any suggestions what I could try?

Thanks

**Comment by yodarx** [comment]
Update: Fixed it myself. Had to go change the url to yourserver.com/public ;)

**Comment by snipe** [comment]
You shouldn't have to do that though. Are you sure you set your DocumentRoot to the `public` directory in your web server configs?

**Comment by snipe** [comment]
(You'll need to restart the web server after making that change)

**Comment by snipe** [comment]
http://snipeitapp.com/documentation/installing-on-linuxosx/#Apache

**Comment by yodarx** [comment]
Too embarrassing, only changed under <Directory >, forgot DocumentRoot.

**Comment by koto137** [comment]
Hello snipe :) thanks for gr8 work, also trying to get it working on my centOS

I have same issue, but I did not use virtual host. I've used just alias and directory.. on my intranet

```
Alias /snipeit /usr/share/snipeit
Alias /snipeIT /usr/share/snipeit


<Directory /usr/share/snipeit/>
   AddDefaultCharset UTF-8
   Require all granted
</Directory>
```

works for every other site so far I've tried but not for this. Have you got any suggestion please ?

Thanks

**Comment by snipe** [comment]
@koto137 Can you describe "doesn't work"?

**Comment by koto137** [comment]
Sorr I ment the same error

```
Forbidden

You don't have permission to access /snipeit/ on this server.
```

when trying to access my "http://10.x.x.x/snipeit".
In app.php I have the following
```
'url' => 'http://10.x.x.x/snipeit',
```

**Comment by snipe** [comment]
Your alias should be set to the public directory. Like Alias `/snipeit /usr/share/snipeit/public`

**Comment by xycofryx** [comment]
Hello it's me again (this is embarrassing) I get 403 nginx error:

'url' => 'http://172.16.0.201:81',

Nginx:

server {
    root /srv/ams.panp.gov.ph/public/;
    index index.php index.html index.htm;
}

**Comment by xycofryx** [comment]
Rearrange my nginx.conf. sorry to disturb you snipe. my apologies. consider this closed
