### ISSUE TITLE
Objects don't show up in main view area after update to 1.2.7

### ISSUE THREAD

**Issue by nmerlintr** [snipe/snipe-it#789]
Users, hardware, and licenses still exist in snipe-it and are mostly editable but they do not show up in the standard places:

/hardware
/hardware/models
/admin/accessories
/admin/licenses
/admin/users

I can find all the users and hardware objects through /admin/settings/manufacturers

No errors are show up in the log files.

**Comment by snipe** [comment]
Can you delete the contents of `app/storage/views` and `app/storage/cache` and reload one of those pages?

**Comment by snipe** [comment]
(The contents only, not the directories themselves.)

**Comment by nmerlintr** [comment]
That worked.  Thank you for responding so quickly.

**Comment by snipe** [comment]
Awesome, thanks for following up. I've updated the release notes to instruct folks to do that as well.

**Comment by rp-tech** [comment]
Can we add this to the list of Common Issues? Or as a standard procedure for upgrading?

**Comment by snipe** [comment]
@rp-tech it's already in the release notes, which should be consulted on every update. https://github.com/snipe/snipe-it/releases

**Comment by rp-tech** [comment]
Ah! how did I miss this! :P

**Comment by snipe** [comment]
It happens :)
