### ISSUE TITLE
Services Management Section [big, needs fleshing out]

### ISSUE THREAD

**Issue by snipe** [snipe/snipe-it#79]
Will be creating a section of the admin that allows you to enter websites/domains/projects, associate them to a single point person on staff (who manages the client relationship, for example)

Hosting company contact info, domain expirations (with live whois), DNS health checks,  etc will be tracked here.

When a staffer is de-activated, you will have to reassign the project to a new staffer, so that a project can never be orphaned with no owner (making legacy systems nearly impossible to track down.)

Domain/SSL cert expiration will be included in on-site notifications and potentially automated email notifications.
##

**Comment by bradley-baker** [comment]
@snipe What's the status of this? We'd really like to import a list of our domains into snipe it but I'm a little uncertain where to put them. Licenses maybe? Although not really a good fit.
