### ISSUE TITLE
Feature Request: Adding Notes and History when changing Asset Status

### ISSUE THREAD

**Issue by cobrien165** [snipe/snipe-it#793]
Looking to add notes and have it create history to an asset like it does when checking in or out, but for when changing status labels. Workflow example for a laptop:

User leaves -> Laptop gets checked in -> Status label of asset would change to Pending if there were any work I would need to do to it to get it ready for someone else -> keyboard bezel was replaced, new battery etc. -> Status label would change from Pending to Ready to Deploy. -> laptop sits on shelf until ready to be checked out to new owner.

In this example, I'd like to add a note to the asset at the current point in time that I replaced the keyboard bezel and replaced the battery that made it Ready to Deploy before I check it out to the user. Essentially, record what I had to do in order to get it from Pending to Ready to Deploy. Would this be possible with something like a check in/out event for status changes?

**Comment by cobrien165** [comment]
To possibly simplify this: Would be looking to change status at the same time as checking in an asset. So when you check in an asset, it'd have a Notes field as well as a Status field. For example, I check in a user's laptop that immediately needs to go out for repair. I can select the "Out for Repair" status at the checkin event.

**Comment by Furchendackel** [comment]
I would appreciate such a feature, too. In my case it would be mostly something like "hard disk deleted, new system installed" after check in and before redeployment to a new user. In that way someone later can retrace if specific required actions have taken place.

Could maybe realized through an extra option like "change status" or "add history entry".

**Comment by cobrien165** [comment]
I like the "Add History Entry" idea. At it's simplest, I'd like to be able to add a general history note to any asset, to timestamp additional info outside of a check-in, check-out event. With the ideal scenario to also have Status Label Changes as history actions just like "created asset" "checkout" checked in from"

**Comment by snipe** [comment]
I think this is probably solved by the maintenance section that's added in 2.0
