### ISSUE TITLE
Server Error 500 (Internal Server Error)

### ISSUE THREAD

**Issue by fromitti** [snipe/snipe-it#797]
Hello, I resolved error Error in exception handler with permits but when trying to enter me throws Server Error 500 (Internal Server Error) any idea.

**Comment by cblervacques** [comment]
Same here ! Error 500.
I'm trying to start snipe-it with the docker container. (latest version: v1.2.7)

**Comment by fromitti** [comment]
install everything without problems with the script
wget --no- check -certificate https://raw.github.com/GR360RY/snipeit-ansible/master/scripts/snipeit.sh -O - | sh

In ubuntu 12 and 14 and both I have the same problem.
PHP: PHP 5.5.9-1ubuntu4.9
Apache : Server version: Apache / 2.4.7 (Ubuntu )
Mysql: Server version: 5.5.43-0ubuntu0.14.04.1 (Ubuntu )

**Comment by snipe** [comment]
Need log files to be able to help

**Comment by cblervacques** [comment]
Where is it ? 
I trying to install snipe 1.2.7 container with the procdure:
http://snipeitapp.com/documentation/installing-on-docker/

**Comment by fromitti** [comment]
after a clean install as detailed above I do not think I saw the user bd " snipeit "
so believe snipeit User and Password : secret
when entering the web log monitoring
tail -f / opt / snipe - it / app / storage / log / log - apache2handler -2015


[2015-05-12 17:05:09] production.ERROR: exception 'PDOException' with message 'S                                                                                       QLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.settings' does                                                                                       n't exist' in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Con                                                                                       nection.php:299
Stack trace:
#0 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php                                                                                       (299): PDO->prepare('select * from `...')
#1 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php                                                                                       (617): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illu                                                                                       minate\Database\MySqlConnection), 'select * from `...', Array)
#2 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php                                                                                       (581): Illuminate\Database\Connection->runQueryCallback('select * from `...', Ar                                                                                       ray, Object(Closure))
#3 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php                                                                                       (304): Illuminate\Database\Connection->run('select * from `...', Array, Object(C                                                                                       losure))
#4 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.                                                                                       php(1412): Illuminate\Database\Connection->select('select * from `...', Array)
#5 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.                                                                                       php(1397): Illuminate\Database\Query\Builder->runSelect()
#6 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.                                                                                       php(1384): Illuminate\Database\Query\Builder->getFresh(Array)
#7 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Build                                                                                       er.php(411): Illuminate\Database\Query\Builder->get(Array)
#8 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Build                                                                                       er.php(151): Illuminate\Database\Eloquent\Builder->getModels(Array)
#9 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Build                                                                                       er.php(125): Illuminate\Database\Eloquent\Builder->get(Array)
#10 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Buil                                                                                       der.php(82): Illuminate\Database\Eloquent\Builder->first(Array)
#11 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Mode                                                                                       l.php(656): Illuminate\Database\Eloquent\Builder->find(1, Array)
#12 /opt/snipe-it/app/models/Setting.php(10): Illuminate\Database\Eloquent\Model                                                                                       ::find(1)
#13 /opt/snipe-it/app/storage/views/399c5a385ff5b20bbe4e0e62480059ec(11): Settin                                                                                       g::getSettings()
#14 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine                                                                                       .php(37): include('/opt/snipe-it/a...')
#15 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerE                                                                                       ngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/opt/snipe-it/a.                                                                                       ..', Array)
#16 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(134): Il                                                                                       luminate\View\Engines\CompilerEngine->get('/opt/snipe-it/a...', Array)
#17 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(102): Il                                                                                       luminate\View\View->getContents()
#18 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(76): Ill                                                                                       uminate\View\View->renderContents()
#19 /opt/snipe-it/app/storage/views/6137ab1a0caaf3a3a19e5ac855a63fa1(65): Illumi                                                                                       nate\View\View->render()
#20 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine                                                                                       .php(37): include('/opt/snipe-it/a...')
#21 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerE                                                                                       ngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/opt/snipe-it/a.                                                                                       ..', Array)
#22 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(134): Il                                                                                       luminate\View\Engines\CompilerEngine->get('/opt/snipe-it/a...', Array)
#23 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(102): Il                                                                                       luminate\View\View->getContents()
#24 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(76): Ill                                                                                       uminate\View\View->renderContents()
#25 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Http/Response.php(43):                                                                                        Illuminate\View\View->render()
#26 /opt/snipe-it/vendor/symfony/http-foundation/Symfony/Component/HttpFoundatio                                                                                       n/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View                                                                                       \View))
#27 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(150                                                                                       1): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\Vie                                                                                       w\View))
#28 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(103                                                                                       6): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request),                                                                                        Object(Illuminate\View\View))
#29 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(100                                                                                       1): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#30 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application                                                                                       .php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#31 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application                                                                                       .php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Re                                                                                       quest))
#32 /opt/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34):                                                                                        Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, t                                                                                       rue)
#33 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware.php                                                                                       (72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request)                                                                                       , 1, true)
#34 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47):                                                                                        Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#35 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51):                                                                                        Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#36 /opt/snipe-it/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illu                                                                                       minate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#37 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application                                                                                       .php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#38 /opt/snipe-it/public/index.php(49): Illuminate\Foundation\Application->run()
#39 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[42S02                                                                                       ]: Base table or view not found: 1146 Table 'snipeit.settings' doesn't exist (SQ                                                                                       L: select * from `settings` where `settings`.`id` = 1 limit 1)' in /opt/snipe-it                                                                                       /vendor/laravel/framework/src/Illuminate/Database/Connection.php:625
Stack trace:
#0 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php                                                                                       (581): Illuminate\Database\Connection->runQueryCallback('select * from `...', Ar                                                                                       ray, Object(Closure))
#1 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php                                                                                       (304): Illuminate\Database\Connection->run('select * from `...', Array, Object(C                                                                                       losure))
#2 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.                                                                                       php(1412): Illuminate\Database\Connection->select('select * from `...', Array)
#3 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.                                                                                       php(1397): Illuminate\Database\Query\Builder->runSelect()
#4 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.                                                                                       php(1384): Illuminate\Database\Query\Builder->getFresh(Array)
#5 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Build                                                                                       er.php(411): Illuminate\Database\Query\Builder->get(Array)
#6 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Build                                                                                       er.php(151): Illuminate\Database\Eloquent\Builder->getModels(Array)
#7 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Build                                                                                       er.php(125): Illuminate\Database\Eloquent\Builder->get(Array)
#8 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Build                                                                                       er.php(82): Illuminate\Database\Eloquent\Builder->first(Array)
#9 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model                                                                                       .php(656): Illuminate\Database\Eloquent\Builder->find(1, Array)
#10 /opt/snipe-it/app/models/Setting.php(10): Illuminate\Database\Eloquent\Model                                                                                       ::find(1)
#11 /opt/snipe-it/app/storage/views/399c5a385ff5b20bbe4e0e62480059ec(11): Settin                                                                                       g::getSettings()
#12 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine                                                                                       .php(37): include('/opt/snipe-it/a...')
#13 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerE                                                                                       ngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/opt/snipe-it/a.                                                                                       ..', Array)
#14 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(134): Il                                                                                       luminate\View\Engines\CompilerEngine->get('/opt/snipe-it/a...', Array)
#15 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(102): Il                                                                                       luminate\View\View->getContents()
#16 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(76): Ill                                                                                       uminate\View\View->renderContents()
#17 /opt/snipe-it/app/storage/views/6137ab1a0caaf3a3a19e5ac855a63fa1(65): Illumi                                                                                       nate\View\View->render()
#18 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine                                                                                       .php(37): include('/opt/snipe-it/a...')
#19 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerE                                                                                       ngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/opt/snipe-it/a.                                                                                       ..', Array)
#20 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(134): Il                                                                                       luminate\View\Engines\CompilerEngine->get('/opt/snipe-it/a...', Array)
#21 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(102): Il                                                                                       luminate\View\View->getContents()
#22 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(76): Ill                                                                                       uminate\View\View->renderContents()
#23 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Http/Response.php(43):                                                                                        Illuminate\View\View->render()
#24 /opt/snipe-it/vendor/symfony/http-foundation/Symfony/Component/HttpFoundatio                                                                                       n/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View                                                                                       \View))
#25 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(150                                                                                       1): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\Vie                                                                                       w\View))
#26 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(103                                                                                       6): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request),                                                                                        Object(Illuminate\View\View))
#27 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(100                                                                                       1): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#28 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application                                                                                       .php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#29 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application                                                                                       .php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Re                                                                                       quest))
#30 /opt/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34):                                                                                        Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, t                                                                                       rue)
#31 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware.php                                                                                       (72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request)                                                                                       , 1, true)
#32 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47):                                                                                        Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#33 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51):                                                                                        Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#34 /opt/snipe-it/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illu                                                                                       minate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#35 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application                                                                                       .php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#36 /opt/snipe-it/public/index.php(49): Illuminate\Foundation\Application->run()
#37 {main}

Next exception 'ErrorException' with message 'SQLSTATE[42S02]: Base table or vie                                                                                       w not found: 1146 Table 'snipeit.settings' doesn't exist (SQL: select * from `se                                                                                       ttings` where `settings`.`id` = 1 limit 1) (View: /opt/snipe-it/app/views/backen                                                                                       d/layouts/default.blade.php)' in /opt/snipe-it/vendor/laravel/framework/src/Illu                                                                                       minate/Database/Connection.php:625
Stack trace:
#0 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.                                                                                       php(41): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Illu                                                                                       minate\Database\QueryException), 1)
#1 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEn                                                                                       gine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/opt/snipe-it/a..                                                                                       .', Array)
#2 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(134): Ill                                                                                       uminate\View\Engines\CompilerEngine->get('/opt/snipe-it/a...', Array)
#3 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(102): Ill                                                                                       uminate\View\View->getContents()
#4 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illu                                                                                       minate\View\View->renderContents()
#5 /opt/snipe-it/app/storage/views/6137ab1a0caaf3a3a19e5ac855a63fa1(65): Illumin                                                                                       ate\View\View->render()
#6 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.                                                                                       php(37): include('/opt/snipe-it/a...')
#7 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEn                                                                                       gine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/opt/snipe-it/a..                                                                                       .', Array)
#8 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(134): Ill                                                                                       uminate\View\Engines\CompilerEngine->get('/opt/snipe-it/a...', Array)
#9 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(102): Ill                                                                                       uminate\View\View->getContents()
#10 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(76): Ill                                                                                       uminate\View\View->renderContents()
#11 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Http/Response.php(43):                                                                                        Illuminate\View\View->render()
#12 /opt/snipe-it/vendor/symfony/http-foundation/Symfony/Component/HttpFoundatio                                                                                       n/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View                                                                                       \View))
#13 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(150                                                                                       1): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\Vie                                                                                       w\View))
#14 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(103                                                                                       6): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request),                                                                                        Object(Illuminate\View\View))
#15 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(100                                                                                       1): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#16 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application                                                                                       .php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#17 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application                                                                                       .php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Re                                                                                       quest))
#18 /opt/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34):                                                                                        Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, t                                                                                       rue)
#19 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware.php                                                                                       (72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request)                                                                                       , 1, true)
#20 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47):                                                                                        Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#21 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51):                                                                                        Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#22 /opt/snipe-it/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illu                                                                                       minate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#23 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application                                                                                       .php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#24 /opt/snipe-it/public/index.php(49): Illuminate\Foundation\Application->run()
#25 {main}

Next exception 'ErrorException' with message 'SQLSTATE[42S02]: Base table or vie                                                                                       w not found: 1146 Table 'snipeit.settings' doesn't exist (SQL: select * from `se                                                                                       ttings` where `settings`.`id` = 1 limit 1) (View: /opt/snipe-it/app/views/backen                                                                                       d/layouts/default.blade.php) (View: /opt/snipe-it/app/views/backend/layouts/defa                                                                                       ult.blade.php)' in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Databas                                                                                       e/Connection.php:625
Stack trace:
#0 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.                                                                                       php(41): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(Erro                                                                                       rException), 1)
#1 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEn                                                                                       gine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('/opt/snipe-it/a..                                                                                       .', Array)
#2 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(134): Ill                                                                                       uminate\View\Engines\CompilerEngine->get('/opt/snipe-it/a...', Array)
#3 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(102): Ill                                                                                       uminate\View\View->getContents()
#4 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/View/View.php(76): Illu                                                                                       minate\View\View->renderContents()
#5 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Http/Response.php(43):                                                                                        Illuminate\View\View->render()
#6 /opt/snipe-it/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation                                                                                       /Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\                                                                                       View))
#7 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1501                                                                                       ): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View                                                                                       \View))
#8 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1036                                                                                       ): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), O                                                                                       bject(Illuminate\View\View))
#9 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001                                                                                       ): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application                                                                                       .php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application                                                                                       .php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Re                                                                                       quest))
#12 /opt/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34):                                                                                        Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, t                                                                                       rue)
#13 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware.php                                                                                       (72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request)                                                                                       , 1, true)
#14 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47):                                                                                        Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51):                                                                                        Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /opt/snipe-it/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illu                                                                                       minate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application                                                                                       .php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /opt/snipe-it/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []

**Comment by snipe** [comment]
@cblervacques http://snipeitapp.com/documentation/getting-help/

**Comment by snipe** [comment]
@fromitti did you run the artisan installer? Looks like no tables are in the DB.

**Comment by fromitti** [comment]
I had not run , in doing so gave me the following error.


/opt/snipe-it# php artisan db:seed --env=production
**************************************
*     Application In Production!     *
**************************************

Do you really wish to run this command? y



  [Illuminate\Database\QueryException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.assets'
  doesn't exist (SQL: truncate `assets`)






  [PDOException]
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.assets'
  doesn't exist



db:seed [--class[="..."]] [--database[="..."]] [--force]

**Comment by fromitti** [comment]
Dear , successful installation :

Installation of Ubuntu 14
PHP: PHP 5.5.9-1ubuntu4.9
Apache : Server version: Apache / 2.4.7 (Ubuntu )
Mysql: Server version: 5.5.43-0ubuntu0.14.04.1 (Ubuntu )
steps ...
wget --no- check -certificate https://raw.github.com/GR360RY/snipeit-ansible/master/scripts/snipeit.sh -O - | sh
 in / opt / snipe - it / php artisan app : install
 
and then enter http : // hostname


Thanks a lot for your help

**Comment by snipe** [comment]
I'm not sure what to make of the last two messages. Is that the order you ran them in? You can't seed a database before the tables have been created. Artisan app install has to come before DB seed.

**Comment by fromitti** [comment]
I installed in that order and the product was up and running .
I saw that in the installation script wget - -NO- comprobar -Certificado https://raw.github.com/GR360RY/snipeit-ansible/master/scripts/snipeit.sh -O - | sh 
skips the steps of creating user and database

**Comment by snipe** [comment]
So is this issue resolved for you then?

**Comment by fromitti** [comment]
If it is definitely the easiest way to install. Thank you then furnishes a video step by step.
