### ISSUE TITLE
Prompt missing when deleting attachment

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#799]
duplicated in demo site

![image](https://cloud.githubusercontent.com/assets/10247644/7613354/32a6134e-f95e-11e4-893b-9aa65d5b018e.png)

**Comment by snipe** [comment]
Funny, I noticed that literally 5 minutes before you posted this. Definitely a bug. I'll get a fix out.

**Comment by snipe** [comment]
This is fixed in the 1.3.0 branch

**Comment by kobie-chasehansen** [comment]
thanks!
