### ISSUE TITLE
Install SnipIT on Shared Web Server like Godaddy

### ISSUE THREAD

**Issue by ankit-roy** [snipe/snipe-it#801]
Hi,

I want to host snipe-it over a shared server is it possible, like godaddy shared hosting with linux server.
Is there any way to do that?? As I am not sure how to run the commands over a shared server, How can I install dependencies with bower.

Please help.

Thanks

**Comment by snipe** [comment]
Hi @ankit-roy - as long as you have SSH access, you would install it on a GoDaddy-style server the same as you would for any other linux server.
