### ISSUE TITLE
Feature Request: Reminders

### ISSUE THREAD

**Issue by jrtoman** [snipe/snipe-it#803]
It would be nice to set up automated reminders to an assigned individual for assets that are evaluation units and have to be returned. We have ran into issue in which evals were forgotten about and we ended up having to purchase these eval units at very high costs. So some sort of system of reminders would be great! It would also be beneficial in situations where we loan systems out to other groups fro a specified time and would remind us and them that they have an loaner item due back to us.
##

**Comment by snipe** [comment]
So I think you're looking for a "due by" field, with reminders. Would that work?

**Comment by jrtoman** [comment]
Yes something along those lines. We had an issue where we forgot that we had an eval unit due by xx date and ended up 6 figures on it. If we had a field that would perhaps say this eval is due back in xx date and perhaps give you a week in advance reminder that would be sweet. Maybe even including a notification on the home page saying that there is an eval due back to the vendor soon would be sweet, just in case the designated person who is supposed to receive the reminder is out of the office and this would allow others in the group to also react to the unit.

**Comment by vr1994** [comment]
Will this feature be added to the software? If yes, how soon can we expect it ?

**Comment by snipe** [comment]
It's not currently on our short term roadmap, however I would accept a PR with this feature if someone wanted to submit one.

**Comment by snipe** [comment]
Just cleaning up some old tickets. We have had "expected checkin" since v3 somewhere, I believe.
