### ISSUE TITLE
Location not displaying on asset list

### ISSUE THREAD

**Issue by athena-harting** [snipe/snipe-it#805]
When I assign a location to an asset, the location does not appear under the location tab in my asset list and thus i cant sort my list based off of location. If i go to the reports section however it does show up under the location tab which is weird. The SQL entry seems to be written correctly....

**Comment by snipe** [comment]
Can you please provide the info listed here: http://snipeitapp.com/documentation/getting-help/

**Comment by snipe** [comment]
(Also, if you can post a screenshot, that would be really helpful.)

**Comment by athena-harting** [comment]
That worked! :smiley: 

Thank you so much!

**Comment by rp-tech** [comment]
Can you please let me know how you resolved the issue? I am having the same problem.

Thanks!
