### ISSUE TITLE
Display Custom Status Labels In Dropdown

### ISSUE THREAD

**Issue by athena-harting** [snipe/snipe-it#810]
Is there any way to display a custom status label that I made in the left drop down menu under Assets? I made a Recycled label and my manager wants easy access to it.

**Comment by n03lx** [comment]
I am also in a custom Status Type (beyond pending, archived, deployable, and undeployable) or the option of an "operational" status type. For example, there are assets in use within the office only and never go into the field unless there is dire need.

Is there any chance this could be doable?

**Comment by tanwedar** [comment]
I vote on the custom status type option. If this is going to be annoying/complex to code then one or two new status would be useful. As n03lx said, something to mark the item as generic in-use would be nice. My boss wants me to keep monitors in the system and "deploying" them to a user doesn't make any sense unless they take the item home. So a new status and the location field combo would be perfect.

**Comment by snipe** [comment]
This was added in 3.4.

Operational status would just be "deployable" and unassigned.
