### ISSUE TITLE
Cant Choose Version of Checked Out License 

### ISSUE THREAD

**Issue by athena-harting** [snipe/snipe-it#814]
We have Microsoft keys that were purchased using a MAK licensing structure. I would like to be able to pick the version of the installed product along with the key that i am assigning to the user\computer. For instance, we have two separate keys for Office 2010 and 2013 but they both apply to the same pool of seats. I would like to know which systems have Office 2010 installed and which ones have 2013 installed out of that pool.

**Comment by athena-harting** [comment]
Is there any way to see the notes that you added to a license checkout?

**Comment by athena-harting** [comment]
If that can be done, that would be enough for me.

**Comment by snipe** [comment]
@athena-harting That should be in the License History, when you look at the license details page. 

![screen shot 2015-06-23 at 12 28 04 am](https://cloud.githubusercontent.com/assets/197404/8300922/c895e24e-193e-11e5-9c24-ba173ca97461.png)
