### ISSUE TITLE
404 Page Not Found 

### ISSUE THREAD

**Issue by hineios** [snipe/snipe-it#815]
Hello.
I'm almost sure this is just a stupid misconfiguration problem, but I can't figure it out so maybe you can help me. Unless you simple can't do what I'm trying to do.

I have a new web server were I'm gooing to migrate all my stuff to.
Since I'm going to need Snipe-IT in the near future (never used it, I've actually done an install on a virtual machine and all went ok) I decided to start by installing Snipe-IT.
My objective is to use something like this:
mydomain.com -> my organization homepage
mydomain.com/snipe-it -> my snipe-it installation
mydomain.com/rhodecode -> my software repository
mydomain.com/.... -> all my other web apps

I figure I could use subdomains and configure apache to use VirtualHosts, but everybody in my organization is already used to this configuration and you all know how hard it is to change non-IT people minds.

Moving forward, I setted up my webserver with Debian 8, Apache2, PHP5, MySQL, FTP, and all seems to be working fine. I did a mockup instal of a Wordpress site, and all is right with the world.
I started the installation of Snipe-IT and added an Alias in my Apache default virtual host like this:

> # 000-default.conf
> < VirtualHost *:80>
>   ServerAdmin webmaster@localhost
>   DocumentRoot /var/www/html
>
>   ErrorLog ${APACHE_LOG_DIR}/error.log
>   CustomLog ${APACHE_LOG_DIR}/access.log combined
>
>   # Snipe-IT tool for managing IT assets 
>   Alias /snipe-it /var/www/snipe-it/public
>   < Directory /var/www/snipe-it/public>
>       AllowOverride All
>       RewriteEngine On
>       Order allow,deny
>       allow from all
>   </ Directory>
> </ VirtualHost>

I finished up the configuration of Snipe-IT as in the instructions, set up the user, and when I try to access the web-site through http://mydomain.com/snipe-it it automatically redirects to http://mydomain.com/snipe-it/auth/signin (so I guess the Alias and the mod_rewrite is working) but I get a 404 error with this message:
The requested URL /var/www/snipe-it/public/index.php was not found on this server.

This is the actual path to were the index.php file is.

I've checked the app/storage/logs and it has nothing of notice (I had some problems with mycript that I solved).
I've messed the permissions on everything and still nothing.
I'm almost sure it's a stupid error in my configurations and I can't figure it out...

Sorry for the wall of text and thanks in advance

PS - I should probably mention that this is my first time configuring a server of this kind...

**Comment by snipe** [comment]
Your `DocumentRoot` also needs to point to `/snipe-it /var/www/snipe-it/public`

**Comment by snipe** [comment]
Oh, never mind, sorry. I just realized the virtual host set up you have is for all the stuff on the server, not just Snipe-IT. 

That *is* peculiar. Give me a few to dig around a little.

And no worries about the wall of text. More info is always better than less info.

**Comment by snipe** [comment]
I'm not sure this would matter, but I think the Alias directive requires quotes around the dir:

`Alias /snipe-it "/var/www/snipe-it/public"`

Also, just to confirm, your snipe-it files are at `/var/www/snipe-it/public` not `/var/www/html/snipe-it/public`, right?

**Comment by hineios** [comment]
Yup, at /var/www/snipe-it/public
More correctly I cloned the project to /var/www/snipe-it, so there is a public directory in there.

I know it's quite a peculiar set up, but unfortunately it is what I have to work with. If I can't figure it out I'll just use a subdomain for snipe-it (something like snipe-it.mydomain.com)
Tomorrow I'll be back at the office again and I'll try that stuff with the quotes.

Besides, don't know if it is relevant (I doubt it matters), but the server is currently in my VPN with no DNS pointing to it since I haven't migrated everything to it. So I access it directly with the IP address (actually I added it to my hosts file).

Thank you so mush for you response.

**Comment by snipe** [comment]
Running it in a sub-directory isn't that peculiar, it's just that the Alias directive should be working, as you're trying to use it.

**Comment by hineios** [comment]
Well, I've tried some new stuff.

First I tried to use the `/var/www/snipe-it/public/` as the DocumentRoot of the server and it worked just fine.
Then I simply moved the DocumentRoot to `/var/www/` and removed the Alias and it still worked (but this is not a solution as all the apps files are acessible this way!).
I've tried the quotes and used something like this
```
Alias /snipe-it/ "/var/www/snipe-it/public"
< Directory "/var/www/snipe-it/">
    Options Indexes FollowSymLinks
    Order allow,deny
    Allow from all
    AllowOverride All
    Require all granted
</ Directory>
```
The result was the directory being listed... Not even by selecting `index.php` I could do it.

I really don't know what else I can do (I've even tried to install of snipe-it from scratch).

**Comment by rp-tech** [comment]
Kind of related to this since you guys are talking about what appears to be a permissions issue w/ Apache (but not really if that makes sense) - hope it's relevant enough that I'm not totally hijacking this thread apologies in advance if that is how it appears:

I have noticed each time I update my snipe-it install I have to re-do all of my permissions on my snipe-it dir (probably because the upgrade process currently involves copying and pasting the new installation over the old one)?

Is there a simpler way to do this that I'm missing? I've tried copying without preserving permissions but because the files + directories are still being over-written it didn't really make any difference - to be clear, my Apache web dirs are secured so that by default public users can't write to the web app dirs, unless explicitly given permission to do so (they have read and execute but not write by default) on the parent folders). That leaves me with having to set write permissions on the folders that require it each and every time.

Is there any way to upgrade Snipe-IT without having to keep resetting the write permission back to the folders that need to be written to?

**Comment by uberbrady** [comment]
I _feel_ like there has to be something with the Alias configuration interacting somehow with the .htaccess - 

```apache
<IfModule mod_rewrite.c>
    <IfModule mod_negotiation.c>
        Options -MultiViews
    </IfModule>

    RewriteEngine On

    # Redirect Trailing Slashes...
    RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>
```

Anytime we have a URL that ends with /, we always redirect to the slashless one.

And we have a Rewrite rule that says anytime we ask for ....anything at all, it ought to go to index.php

so browsing to: ```http://mydomain.com/snipe-it/``` ought to redirect instead to: ```http://mydomain.com/snipe-it``` - and then from there you ought to be looking for index.php - which would be at the wrong level. 

If we change the RewriteRule - the last one - to be:

```apache
    RewriteRule ^ /index.php [L]
```
or maybe ```/snipe-it/index.php``` - any luck there?

This is just my best guess having looked at it and read through the ticket a few times.

**Comment by snipe** [comment]
Shouldn't need to change that rewrite rule though. Other folks are using Apache alias using  `Alias /snipe /var/www/html/snipe-it/public` (or whatever their public path was)

**Comment by snipe** [comment]
@rp-tech - can you create a separate issue for your question? I'd rather not conflate these two things.

**Comment by hineios** [comment]
Finally I got it!

After endless tries (I can't really recall everything I did) I got this working!

This is what I ended up with:
Each web-site/web-application I have is on `/var/www/` on it's own folder. So snipe-it folder path is `/var/www/snipe-it`. My main site is on `/var/www/main-site` and so on.

After this I used this virtual-host configuration for apache:

        <VirtualHost *:80>
                ServerName my-domain.com 
                DocumentRoot /var/www/main-site

        <Directory /var/www/main-site/>
                AllowOverride All
                Options Indexes Multiviews FollowSymlinks
                Order allow,deny
                Allow from all
        </Directory>

        Alias /web-site /var/www/other-web-site
        <Directory /var/www/other-web-site/>
                Options +FollowSymLinks
                AllowOverride None
                Order allow,deny
                Allow from all
        </Directory>

        Alias /snipe-it /var/www/snipe-it/public
        <Directory /var/www/snipe-it/public/>
                AllowOverride All
                Options Indexes Multiviews FollowSymlinks
                Order allow,deny
                Allow from all
        </Directory>
        </VirtualHost>

But even after this I got some odd results. When I tried to access the snipe-it app I got a page not found from my main-site. I realised I was requesting my Snipe-IT pages to my main site.
I simply had to had a `RewriteBase /snipe-it` to the snipe-it .htacces file.

All allong this was only a problem with the .htaccess file...
I hope I can help anyone with this.
Thank you for you help.

**Comment by snipe** [comment]
@hineios that's not the right answer though. I mean, it can be for now if you need it to be and don't want to mess with it more, but the htacess is stock, and this all should have been able to be handled via Alias and virtual host settings. We don't change the htacess very often at all, so you should be okay, but changing core files always means further updates can blow out your specific install.

**Comment by hineios** [comment]
I completely understand what you are saying. But I found this https://github.com/snipe/snipe-it/issues/221 were @technogenus also added that rule to the htaccess.

Messing around with the application, I found out that the Dashboard button sends me to the wrong URL.
It sends me to `my-domain.com` when he should send me to `my-domain.com/snipe-it`.
Where is the correct place to change this behaviour?

**Comment by snipe** [comment]
Yeah, and there's a reason that guys pull requests didn't get merged. 

I thought we fixed that dashboard link issue a while ago. I'll fix it again on develop.

**Comment by hineios** [comment]
Ok, thanks for everything.

**Comment by koto137** [comment]
Hello SNIPE,

I wrote you couple hours back with my issue and you helped me really well, thank you for that. But getting a little forward I face another issue, that I cannot overcome myself yet. I am linux beginner so had to seek a lot of help sometimes :smiley_cat: 

The problem is when I finally got rid of the error "AUTH/SIGNIN" not found and enabled AllowOverride All in my snipeit.conf file. I get another error:

```
Not Found

The requested URL /usr/share/snipeit/public/index.php was not found on this server.
```

Here is my snipeit.conf file

```
Alias /snipeit /usr/share/snipeit/public
Alias /snipeIT /usr/share/snipeit/public


<Directory /usr/share/snipeit/public/>
    Options Indexes FollowSymLinks
    Order allow,deny
    Allow from all
    AllowOverride All
    Require all granted
</Directory>
```

the workaround using command bellow in ".httaccess" worked for me also
```
    RewriteBase /snipeit
```

Thanks you

**Comment by snipe** [comment]
Ca you do an `ls -al /usr/share/snipeit` via command line and show me what it says?

**Comment by koto137** [comment]
Sorry been out of work on weekend, here you go :+1: 

```
[admin@ICZ-webOS snipeit]$ ls -al
total 1392
drwxrwxrwx.   8 apache apache    4096 Jun 12 10:15 .
drwxr-xr-x. 149 root   root      4096 Jun 11 15:53 ..
drwxrwxrwx.  13 apache apache    4096 Jun 11 15:21 app
-rwxrwxrwx.   1 apache apache    2451 Jun  9 02:20 artisan
drwxrwxrwx.   2 apache apache      43 Jun 12 10:16 bin
drwxrwxrwx.   2 apache apache      57 Jun 11 15:22 bootstrap
-rwxrwxrwx.   1 apache apache   46713 Jun  9 02:20 CHANGELOG.md
-rwxrwxrwx.   1 apache apache    1432 Jun  9 02:20 CODE_OF_CONDUCT.md
-rwxrwxrwx.   1 apache apache    1516 Jun  9 02:20 composer.json
-rwxrwxrwx.   1 apache apache  143906 Jun  9 02:20 composer.lock
-rwxrwxrwx.   1 apache apache 1105755 Jun 11 16:20 composer.phar
-rwxrwxrwx.   1 apache apache    2315 Jun  9 02:20 CONTRIBUTING.md
drwxrwxrwx.   2 apache apache    4096 Jun 11 15:22 docker
-rwxrwxrwx.   1 apache apache    2484 Jun  9 02:20 Dockerfile
-rwxrwxrwx.   1 apache apache      67 Jun  9 02:20 .dockerignore
-rwxrwxrwx.   1 apache apache    1655 Jun  9 02:20 gh-changelog.php
-rwxrwxrwx.   1 apache apache      11 Jun  9 02:20 .gitattributes
-rwxrwxrwx.   1 apache apache     467 Jun  9 02:20 .gitignore
-rwxrwxrwx.   1 apache apache   34519 Jun  9 02:20 LICENSE
-rwxrwxrwx.   1 apache apache     567 Jun  9 02:20 phpunit.xml
drwxrwxrwx.   6 apache apache    4096 Jun 11 15:22 public
-rwxrwxrwx.   1 apache apache    4640 Jun  9 02:20 README.md
-rwxrwxrwx.   1 apache apache     522 Jun  9 02:20 server.php
-rwxrwxrwx.   1 apache apache    1570 Jun  9 02:20 .travis.yml
drwxrwxrwx.  31 apache apache    4096 Jun 12 10:20 vendor
```

**Comment by claydawg** [comment]
I was experiencing this same issue.  Turns out my .htaccess was in snipe-it/.  Moved it to snipe-it/public/ and everything worked as expected.

**Comment by snipe** [comment]
@claydawg There should not have been an htaccess in your snipe-it folder, only in public. How did it get there?

@koto137 are you still having trouble or are you all set?

**Comment by kenzkie30** [comment]
Im having trouble when I'm accessing snipe-it to other computer .
![1](https://user-images.githubusercontent.com/50512020/57566118-6598a980-73fb-11e9-9bdf-9731ba19c8d1.PNG)
