### ISSUE TITLE
Using inventory site but can not see deleted assets

### ISSUE THREAD

**Issue by sophiajaber** [snipe/snipe-it#817]
I'm having an issue where if I delete an asset and i want to put it back in, I can't.

there is no way to bring back the asset or if i try to create a new asset, it says it's already in use. 

Can there be a deleted assets tab? This helps with organizing units that have been recycled or destroyed and can be a separate inventory to export into an excel sheet. We have a show deleted users tab which is very helpful for that purpose, We just need the same thing for all assets that have been deleted.

Thanks

**Comment by kobie-chasehansen** [comment]
This already exists, in the left nav panel click Assets then Deleted

**Comment by sophiajaber** [comment]
I’m sorry but I have no idea what you’re talking about.

This is what I see…..


Sophia Jaber
IT Department | Engine | Deep Focus

460 Park Ave South, 7th Floor
New York, NY 10016
o: 212.792.6867
m: 212.792.6800
www.deepfocus.net

**Comment by snipe** [comment]
@sophiajaber - you can't send screenshots through GH mail, you have to upload them via the website.

If you're using the same version of Snipe-IT I set up for Noise a long time ago, it probably needs some serious updating. I lost access to that server at some point, so couldn't silently update for you guys.

**Comment by snipe** [comment]
@kobie-chasehansen this may be a special case. @sophiajaber works for a company that acquired my old company, so she may be dealing with the original versions I set up for them, versus a new install.

**Comment by sophiajaber** [comment]
Sorry about that i was multitasking and didn't send the reply through the web browser. So my guess is that it is still the noise inventory from a long time ago because all i changed was the title name to Deep Focus. So how do you gain access back so we can update it?

**Comment by snipe** [comment]
@sophiajaber I doubt they'll want me poking around there, since I don't work for Noise anymore, but you can try updating it yourself (or have someone like Warren do it, if he's still there.) I haven't worked there in over a year.

Upgrading instructions are here: http://snipeitapp.com/documentation/upgrading/

**Comment by sophiajaber** [comment]
Okay. Sorry about that. Troi told me to click the link on the bottom of the page and have whomever replies fix it.... -_- Warren is still here but he keeps giving me an IDK or a blank stare..... he says he doesn't have access. So i can do my best if I'm pointed in the right direction.....

**Comment by sophiajaber** [comment]
Where was the database stored? You said you lost access a long time ago. Do you know where i can look?

**Comment by snipe** [comment]
The DB is on the same server.

Haha - oh, jeez. Warren should definitely have access via the AWS account I gave him access to. Have him or Troi drop me an email and I'll try to walk Warren through the upgrade, or work with them ti do it myself.

**Comment by sophiajaber** [comment]
okay i am talking with him now I will lt you know. Thanks!

**Comment by snipe** [comment]
I just texted Warren as well. Closing this issue for now, since it's specific to us.
