### ISSUE TITLE
1364 Field 'notes' doesn't have a default value

### ISSUE THREAD

**Issue by whatdoesdfoxsay** [snipe/snipe-it#818]
Snipe -

I keep getting the following error when running the 'php artisan app:install --env:production' command:

  [Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1364 Field 'notes' doesn't have a default v
  alue (SQL: insert into `users` (`first_name`, `last_name`, `email`, `passwo
  rd`, `activated`, `manager_id`, `updated_at`, `created_at`) values (John, D
  oe, john.doe@example.com, y$TimJQURlZNcs5MZ/O999r.0jxu2DrefssIF/DI2x1digvwq
  wvXlZC, 1, 1, 2015-05-27 18:17:30, 2015-05-27 18:17:30))

  [PDOException]
  SQLSTATE[HY000]: General error: 1364 Field 'notes' doesn't have a default v
  alue"

I noticed you addressed a null values issue in #141, this seems similar?

The full output is below - Thanks! (I apologize for any formatting issues, this is my first ever post on GitHub)

C:\inetpub\wwwroot\snipe-it>php artisan app:install --env=production
=====================================

  Step: 1

    Please follow the following
    instructions to create your
    default user.

-------------------------------------

Please enter your first name: xxxx
Please enter your last name: xxxx
Please enter your user email: xxxx@xxxxxxxx.net
Please enter your user password (at least 8 characters): xxxxxxxx
Do you want to seed your database with dummy data? y/n (default is yes): y

=====================================

  Step: 2

    Preparing your Application

-------------------------------------

Application key [IV1wU1SZtjeF9EmD4M8dpvbqheZa3zGF] set successfully.
Migration table created successfully.
**************************************
*     Application In Production!     *
**************************************

Do you really wish to run this command? yes
Migrated: 2012_12_06_225921_migration_cartalyst_sentry_install_users
Migrated: 2012_12_06_225929_migration_cartalyst_sentry_install_groups
Migrated: 2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_p
t
Migrated: 2012_12_06_225988_migration_cartalyst_sentry_install_throttle
**************************************
*     Application In Production!     *
**************************************

Do you really wish to run this command? yes
Migrated: 2013_03_23_193214_update_users_table
Migrated: 2013_11_13_075318_create_models_table
Migrated: 2013_11_13_075335_create_categories_table
Migrated: 2013_11_13_075347_create_manufacturers_table
Migrated: 2013_11_15_015858_add_user_id_to_categories
Migrated: 2013_11_15_112701_add_user_id_to_manufacturers
Migrated: 2013_11_15_190327_create_assets_table
Migrated: 2013_11_15_190357_create_licenses_table
Migrated: 2013_11_15_201848_add_license_name_to_licenses
Migrated: 2013_11_16_040323_create_depreciations_table
Migrated: 2013_11_16_042851_add_depreciation_id_to_models
Migrated: 2013_11_16_084923_add_user_id_to_models
Migrated: 2013_11_16_103258_create_locations_table
Migrated: 2013_11_16_103336_add_location_id_to_assets
Migrated: 2013_11_16_103407_add_checkedout_to_to_assets
Migrated: 2013_11_16_103425_create_history_table
Migrated: 2013_11_17_054359_drop_licenses_table
Migrated: 2013_11_17_054526_add_physical_to_assets
Migrated: 2013_11_17_055126_create_settings_table
Migrated: 2013_11_17_062634_add_license_to_assets
Migrated: 2013_11_18_134332_add_contacts_to_users
Migrated: 2013_11_18_142847_add_info_to_locations
Migrated: 2013_11_18_152942_remove_location_id_from_asset
Migrated: 2013_11_18_164423_set_nullvalues_for_user
Migrated: 2013_11_19_013337_create_asset_logs_table
Migrated: 2013_11_19_061409_edit_added_on_asset_logs_table
Migrated: 2013_11_19_062250_edit_location_id_asset_logs_table
Migrated: 2013_11_20_055822_add_soft_delete_on_assets
Migrated: 2013_11_20_121404_add_soft_delete_on_locations
Migrated: 2013_11_20_123137_add_soft_delete_on_manufacturers
Migrated: 2013_11_20_123725_add_soft_delete_on_categories
Migrated: 2013_11_20_130248_create_status_labels
Migrated: 2013_11_20_130830_add_status_id_on_assets_table
Migrated: 2013_11_20_131544_add_status_type_on_status_labels
Migrated: 2013_11_20_134103_add_archived_to_assets
Migrated: 2013_11_21_002321_add_uploads_table
Migrated: 2013_11_21_024531_remove_deployable_boolean_from_status_labels
Migrated: 2013_11_22_075308_add_option_label_to_settings_table
Migrated: 2013_11_22_213400_edits_to_settings_table
Migrated: 2013_11_25_013244_create_licenses_table
Migrated: 2013_11_25_031458_create_license_seats_table
Migrated: 2013_11_25_032022_add_type_to_actionlog_table
Migrated: 2013_11_25_033008_delete_bad_licenses_table
Migrated: 2013_11_25_033131_create_new_licenses_table
Migrated: 2013_11_25_033534_add_licensed_to_licenses_table
Migrated: 2013_11_25_101308_add_warrantee_to_assets_table
Migrated: 2013_11_25_104343_alter_warranty_column_on_assets
Migrated: 2013_11_25_150450_drop_parent_from_categories
Migrated: 2013_11_25_151920_add_depreciate_to_assets
Migrated: 2013_11_25_152903_add_depreciate_to_licenses_table
Migrated: 2013_11_26_211820_drop_license_from_assets_table
Migrated: 2013_11_27_062510_add_note_to_asset_logs_table
Migrated: 2013_12_01_113426_add_filename_to_asset_log
Migrated: 2013_12_06_094618_add_nullable_to_licenses_table
Migrated: 2013_12_10_084038_add_eol_on_models_table
Migrated: 2013_12_12_055218_add_manager_to_users_table
Migrated: 2014_01_28_031200_add_qr_code_to_settings_table
Migrated: 2014_02_13_183016_add_qr_text_to_settings_table
Migrated: 2014_05_24_093839_alter_default_license_depreciation_id
Migrated: 2014_05_27_231658_alter_default_values_licenses
Migrated: 2014_06_19_191508_add_asset_name_to_settings
Migrated: 2014_06_20_004847_make_asset_log_checkedout_to_nullable
Migrated: 2014_06_20_005050_make_asset_log_purchasedate_to_nullable
Migrated: 2014_06_24_003011_add_suppliers
Migrated: 2014_06_24_010742_add_supplier_id_to_asset
Migrated: 2014_06_24_012839_add_zip_to_supplier
Migrated: 2014_06_24_033908_add_url_to_supplier
Migrated: 2014_07_08_054116_add_employee_id_to_users
Migrated: 2014_07_09_134316_add_requestable_to_assets
Migrated: 2014_07_17_085822_add_asset_to_software
Migrated: 2014_07_17_161625_make_asset_id_in_logs_nullable
Migrated: 2014_08_12_053504_alpha_0_4_2_release
Migrated: 2014_08_17_083523_make_location_id_nullable
Migrated: 2014_10_16_200626_add_rtd_location_to_assets
Migrated: 2014_10_24_000417_alter_supplier_state_to_32
Migrated: 2014_10_24_015641_add_display_checkout_date
Migrated: 2014_10_28_222654_add_avatar_field_to_users_table
Migrated: 2014_10_29_045924_add_image_field_to_models_table
Migrated: 2014_11_01_214955_add_eol_display_to_settings
Migrated: 2014_11_04_231416_update_group_field_for_reporting
Migrated: 2014_11_05_212408_add_fields_to_licenses
Migrated: 2014_11_07_021042_add_image_to_supplier
Migrated: 2014_11_20_203007_add_username_to_user
Migrated: 2014_11_20_223947_add_auto_to_settings
Migrated: 2014_11_20_224421_add_prefix_to_settings
Migrated: 2014_11_21_104401_change_licence_type
Migrated: 2014_12_09_082500_add_fields_maintained_term_to_licenses
Migrated: 2015_02_04_155757_increase_user_field_lengths
Migrated: 2015_02_07_013537_add_soft_deleted_to_log
Migrated: 2015_02_10_040958_fix_bad_assigned_to_ids
Migrated: 2015_02_10_053310_migrate_data_to_new_statuses
Migrated: 2015_02_11_044104_migrate_make_license_assigned_null
Migrated: 2015_02_11_104406_migrate_create_requests_table
Migrated: 2015_02_12_001312_add_mac_address_to_asset
Migrated: 2015_02_12_024100_change_license_notes_type
Migrated: 2015_02_17_231020_add_localonly_to_settings
Migrated: 2015_02_19_222322_add_logo_and_colors_to_settings
Migrated: 2015_02_24_072043_add_alerts_to_settings
Migrated: 2015_02_25_022931_add_eula_fields
Migrated: 2015_02_25_204513_add_accessories_table
Migrated: 2015_02_26_091228_add_accessories_user_table
Migrated: 2015_02_26_115128_add_deleted_at_models
Migrated: 2015_02_26_233005_add_category_type
Migrated: 2015_03_01_231912_update_accepted_at_to_acceptance_id
Migrated: 2015_03_05_011929_add_qr_type_to_settings
Migrated: 2015_03_18_055327_add_note_to_user
Migrated: 2015_04_29_234704_add_slack_to_settings

Admin group created successfully.

Reporting group created successfully.

Users group created successfully.

Your user was created successfully.

  [Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1364 Field 'notes' doesn't have a default v
  alue (SQL: insert into `users` (`first_name`, `last_name`, `email`, `passwo
  rd`, `activated`, `manager_id`, `updated_at`, `created_at`) values (John, D
  oe, john.doe@example.com, y$TimJQURlZNcs5MZ/O999r.0jxu2DrefssIF/DI2x1digvwq
  wvXlZC, 1, 1, 2015-05-27 18:17:30, 2015-05-27 18:17:30))

  [PDOException]
  SQLSTATE[HY000]: General error: 1364 Field 'notes' doesn't have a default v
  alue

app:install

C:\inetpub\wwwroot\snipe-it>_

**Comment by snipe** [comment]
What version are you installing?

**Comment by whatdoesdfoxsay** [comment]
I'm installing it Snipe-IT 1.2.7 on the following:

- MS Server 2012 R2
- IIS 8.5
- MariaDB 10.0.19 x64
- PHP 5.4

Basically as close to possible as your documentation at:
http://snipeitapp.com/documentation/installing-on-iis/

**Comment by snipe** [comment]
Okay, looks like your MySQL is running in strict mode, and we missed the notes field.

**Comment by snipe** [comment]
Sorry, I hit return too early. Can you drop your DB tables and try again, using the latest from `master`?

**Comment by whatdoesdfoxsay** [comment]
@snipe Thank you! Worked perfectly. Now let me see if I can get this thing running...

**Comment by snipe** [comment]
Awesome, glad it's sorted. 

Sorry about the bug in the first place. We try to make sure everything is MySQL strict-mode proof, but occasionally miss a few things. 

![untested-feature](https://cloud.githubusercontent.com/assets/197404/7844866/18a88020-0468-11e5-8f17-1e19f6c85734.gif)

**Comment by whatdoesdfoxsay** [comment]
@snipe Thanks for all of your help yesterday! Everything is running great, except (and I think it's basically the same issue?) when I try to upload a CSV file to import users, I get the following:

SQLSTATE[HY000]: General error: 1364 Field 'notes' doesn't have a default value (SQL: insert into `users` (`first_name`, `last_name`, `email`, `password`, `activated`, `permissions`) values (potato, chip, test@gmail.com, b7Tuj4P6wA, 0, {"user":1}))
