### ISSUE TITLE
Feature request: Simple Tasks

### ISSUE THREAD

**Issue by Furchendackel** [snipe/snipe-it#820]
I'd like to see a feature to create a task and assign it to multiple assets.

For example if I have to upgrade the firmware of 50 assets, I could create a task for it, select the affected assets and could keep track of my progress and avoid taking care of the same asset multiple times. In the asset history I would have a 'proof' that and when a specific action was taken. A column in the asset list showing the number of open tasks per asset would be nice, too.

For now, I help myself with creating an special named license and assigning it to the affected assets even its the hell of a click orgy to assign all assets in the beginning.
##

**Comment by oorahduc** [comment]
This is close to the request I wanted to make. To illustrate, what I envision is 'configurable actions' that could be made available in a drop down at the top, whereby I could perform an action on multiple checked assets.

This, and the lack of a Rest API are the only things keeping me from moving forward with the use of Snipeit. Outside of that, it's great!
