### ISSUE TITLE
Class Barryvdh\Debugbar\Middleware does not exist

### ISSUE THREAD

**Issue by tripolitrax** [snipe/snipe-it#821]
Hi 

After upgrading and I try load the application I get this error:

Please assist: 

ReflectionException
Class Barryvdh\Debugbar\Middleware does not exist

---

open: /var/www/assets/vendor/stack/builder/src/Stack/Builder.php
 
            if (is_callable($firstArg)) {
                $app = $firstArg($app);
            } else {
                $kernelClass = $firstArg;
                array_unshift($args, $app);
 
                $reflection = new \ReflectionClass($kernelClass);
                $app = $reflection->newInstanceArgs($args);
            }

**Comment by snipe** [comment]
What mode are you installing this as? (Production, Local, etc) Also can you provide more information? http://snipeitapp.com/documentation/getting-help/

**Comment by tripolitrax** [comment]
Hi, what I did was just re-installed completely, never upgraded and then just did the DB migrate and all was good, I was coming from one of the earliest builds ever. 

Kind Regards
