### ISSUE TITLE
Error on Import Users -> CSV Upload [1364 Field 'notes' doesn't have a default value]

### ISSUE THREAD

**Issue by whatdoesdfoxsay** [snipe/snipe-it#822]
@snipe Thanks for your help yesterday! Everything is running great, except (and I think it's basically the same issue you addressed in #818 but in a different place) when I try to upload a CSV file to import users, I get the following:

SQLSTATE[HY000]: General error: 1364 Field 'notes' doesn't have a default value (SQL: insert into users (first_name, last_name, email, password, activated, permissions) values (potato, chip, test@gmail.com, b7Tuj4P6wA, 0, {"user":1}))

**Comment by snipe** [comment]
Yeah, so this looks like it's related to MySQL being in strict mode again. 

Around line 636 in `app/controllers/admin/UsersController.php`, can you change:

							$newuser = array(
								'first_name' => $row[0],
								'last_name' => $row[1],
								'email' => $row[2],
								'password' => $pass,
								'activated' => $activated,
								'permissions'	=> '{"user":1}'
							);

to this:

							$newuser = array(
								'first_name' => $row[0],
								'last_name' => $row[1],
								'email' => $row[2],
								'password' => $pass,
								'activated' => $activated,
								'permissions'	=> '{"user":1}',
                                'notes'     => 'Imported user'
							);

and try importing again?

**Comment by snipe** [comment]
Any luck?

**Comment by whatdoesdfoxsay** [comment]
@snipe I haven't had the opportunity to modify the code you'd mentioned, but I trust that it will work! I will report back if I get the opportunity to test that out.
