### ISSUE TITLE
Title bar formatting issue

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#825]
Space missing between View License and the license name

![image](https://cloud.githubusercontent.com/assets/10247644/7914523/8f1f8010-0845-11e5-9331-f6f935906409.png)

**Comment by snipe** [comment]
LOL slow day at work? :P

**Comment by kobie-chasehansen** [comment]
I've been saving that one :)

**Comment by snipe** [comment]
![96ae9d29-4613-4c05-97f3-5b0f00703e63](https://cloud.githubusercontent.com/assets/197404/7926414/2100cd68-0887-11e5-91c7-f94329de50df.jpg)

:P
