### ISSUE TITLE
Q: Mass checkin/checkout?

### ISSUE THREAD

**Issue by Shane81** [snipe/snipe-it#827]
Hi I tried the demo, I didn't see a way to do this. 

I am using a Koha-community to manage my stuff now. It is a bit too much for just IT assets though. 

I was curious if there is a way to use a barcode scanner to mass checkin or checkout items.

Mostly check-in is my concern. I collect all 400+/- assets each summer to verify/clean/check, and then give them back.

I guess I was thinking a asset/serial box, a drop down for status (pending/deployable/etc), maybe a note field (like "initial checkin"). Fields could/should be persistent to allow mass scans.

If that isn't something available, would that fit your scope/vision of this project?

Thank you for the help/feedback!

**Comment by snipe** [comment]
Do you have existing barcodes that you're looking to use, or would you be using the ones we generate?
