### ISSUE TITLE
Cannot delete users

### ISSUE THREAD

**Issue by athena-harting** [snipe/snipe-it#828]
I saw that there was another issue submitted for this and was resolved but i don't know where to assign users super admin privileges so that we can delete users. I've looked though the entire program.....

**Comment by snipe** [comment]
Click on the user in People, selected the Afmin group, and click on the permissions tab and assign as super admin.

**Comment by athena-harting** [comment]
I dont see that. All I see is this 
![groupedit](https://cloud.githubusercontent.com/assets/11642137/7973506/e28d8a78-0a0a-11e5-89be-0ae002fd9327.PNG)

**Comment by snipe** [comment]
That's in the Group Edit. Go to People on the left side nav, pick a person, and click Edit. There is a Permissions tab on that page

**Comment by snipe** [comment]
Any luck?

**Comment by snipe** [comment]
Hey @athena-harting - can you confirm whether this is still an issue? Otherwise I'm going to close this ticket.

**Comment by fmagoufis** [comment]
I followed this process and am still unable to delete a user.  I am trying to delete the John Doe user that was loaded as part of the initial database seed.

**Comment by snipe** [comment]
@fmagoufis Are you logged in as the user you created during setup, or as someone else?

**Comment by fmagoufis** [comment]
I'm logging in with my own user account.

**Comment by ionreflex** [comment]
@snipe I think you can close it : I had problem deleting John Doe myself, your input fix it for me!

**Comment by fmagoufis** [comment]
Could I delete the user from the database?
