### ISSUE TITLE
You might want to add phar and json to the list of dependencies on the website

### ISSUE THREAD

**Issue by addisonamiri** [snipe/snipe-it#829]
I was going through the installation instructions and I couldn't get composer to run until I realized it required phar and json. I had only enabled what was listed on the dependincies page. It might be helpful to add a small note somewhere that these modules are required during the installation process.

**Comment by snipe** [comment]
`Phar` and `JSON` are pretty standard php5 extension modules. Phar extension is built into PHP as of PHP version 5.3.0, and as of PHP 5.2.0, the JSON extension is bundled and compiled into PHP by default.

http://php.net/manual/en/json.installation.php
http://php.net/manual/en/phar.installation.php
