### ISSUE TITLE
Feature request: Fast decomission / auto-check back in all items on disable user

### ISSUE THREAD

**Issue by rp-tech** [snipe/snipe-it#830]
Hi,

Each time I have to decommission a user who leaves the company, I'm required to check each of their assets back in manually.

It would greatly speed up on deboarding process if there was a 'fast-decomission' option i.e., if when I marked the user as inactive, it automatically checks all of their assets, including software licenses, back into the system.

Thoughts?

**Comment by snipe** [comment]
We had discussed this here: https://github.com/snipe/snipe-it/issues/588#issuecomment-76875030

**Comment by snipe** [comment]
Closing this, since you continued the convo over on the other issue. :)
