### ISSUE TITLE
Software license should be  assigned to a machine

### ISSUE THREAD

**Issue by razorfish-sl** [snipe/snipe-it#831]
1. Licences go in machines not to people.
   When the machine moves so does the license.
##

**Comment by snipe** [comment]
@razorfish-sl not necessarily. Adobe Creative Cloud, for example, is licensed to a person. Also, if a machine breaks and a replacement gets furnished, the license moves to the new machine. This is why we opted to have it assigned to a user versus a machine.

**Comment by Muhkoenig** [comment]
@razorfish-sl @snipe both should be possible. It looks to me it's almost possible already. You already can assign a license to an asset. Only hickup i found was that if an asset has an assigned user. And you check that asset in the license gets checked in to.

**Comment by eduardok** [comment]
With Microsoft you can license for product (e.g. you buy a SQL Server license for each SQL Server you have installed), for a person/user (e.g. you buy a SQL Server Client Access License for each user accessing the DBMS), or for a device (e.g.: an OEM license).
