### ISSUE TITLE
Feature request: Hide inactive users in the People list

### ISSUE THREAD

**Issue by rp-tech** [snipe/snipe-it#832]
As the title says, it would be nice to have an option to hide all inactive  users in the People list. A small but convenient feature (yes I know, you can just search the person's name you're looking for - it just makes things look neater, that's all).

Thanks!

**Comment by richjenks** [comment]
What about greying the row so it's clear graphically but doesn't require an extra filter, tab or view?

The value would be the ability to identify people either not relevant yet or any more (e.g. left an organisation).

**Comment by snipe** [comment]
Is there a reason you'd leave a user as inactive versus deleting them?

**Comment by richjenks** [comment]
Hi @snipe, if you're considering dropping it altogether, the inactive feature is very useful for me — here are a few use cases:

1. Staff hiatus/extended leave
1. Need to retain historical records of asset assignment, including non-current users
1. Need to prevent any more assets going to a particular user (e.g. a ban)
