### ISSUE TITLE
IIS installation but Problem loading page on Windows Server 2008 R2 Std

### ISSUE THREAD

**Issue by jnfresnoza** [snipe/snipe-it#835]
Hi,
I am installing Snipe-IT (snipe-it-1.2.7) on an Windows Server 2008 R2 Standard
Hostname of the machine is DAMServer
IP Address 192.168.30.31
My URL on app.php is damserver.svhc.local as well as in my start.php

I followed all the instructions and no errors appeared
but when I started to browse my site
http://damserver.svhc.local/
![problem](https://cloud.githubusercontent.com/assets/12760499/8004571/5379a1dc-0bb3-11e5-9d62-c5c05680a87b.png)

it will display Problem loading page server not found
tried using http://localhost/snipe-it/public/auth/signin
it will display Server Error: 500 (Internal Server Error)
tried http://localhost/snipe-it/
it will just browse folders and files...
![browse](https://cloud.githubusercontent.com/assets/12760499/8004534/08308628-0bb3-11e5-9986-93c43ec3c679.png)

Please help me with my installation.

**Comment by snipe** [comment]
You have to set your Physical path to the public folder in your server settings.

http://snipeitapp.com/documentation/installing-on-iis/#Setting_Up_an_IIS_Website

**Comment by jnfresnoza** [comment]
Hi there, actually i have already set the physical path to the public folder...
![public_path](https://cloud.githubusercontent.com/assets/12760499/8055657/b55e2fd0-0ed3-11e5-951b-2394fea9aafe.png)

My installation went pretty well, but the problem is that when browse it, it dose not work.
Please help....

**Comment by snipe** [comment]
If you're seeing a directory index with public in it, them your document root and/or physical path is not set to the public directory. This is s configuration issue on your end, I'm afraid. 

What do you see when you click on the index page?
