### ISSUE TITLE
404 - Assets - Edit Location

### ISSUE THREAD

**Issue by dmcnaughtan** [snipe/snipe-it#836]
From the Assets list, when I try to edit a location, I get a 404.
The link points to: /admin/location/9/edit

If I navigate to location via the admin menu - locations, the edit link points to:  /admin/settings/locations/9/edit

**Comment by nickmacwiz** [comment]
is this the reason when i view the list of assets it doesn't show the location of the asset?

**Comment by snipe** [comment]
@dmcnaughtan what version are you using?

**Comment by snipe** [comment]
@dmcnaughtan In the Assets Controller:

      ->addColumn('location',function($assets)
      {
            if ($assets->assigned_to && $assets->assigneduser->userloc) {
                return link_to('admin/settings/locations/'.$assets->assigneduser->userloc->id.'/edit', $assets->assigneduser->userloc->name);
            } elseif ($assets->defaultLoc){
                return link_to('admin/settings/locations/'.$assets->defaultLoc->id.'/edit', $assets->defaultLoc->name);
            } 
      })

So that URL looks right to me.

**Comment by nickmacwiz** [comment]
@snipe I have the latest version running and i have 2 installs of it and for some reason when i view the list of assets the asset locations doesn't show but if i go into edit the asset to change the location it shows the right asset location.

**Comment by dmcnaughtan** [comment]
I'm using snipe-it-1.2.7.  I'm looking at the Assets Controller to see now.

**Comment by dmcnaughtan** [comment]
This is what I have in 1.2.7:
                ->addColumn('location',function($assets)
            {
                if ($assets->assigned_to && $assets->assigneduser->userloc) {                   
                    return link_to('admin/location/'.$assets->assigneduser->userloc->id.'/edit', $assets->assigneduser->userloc->name);
                } elseif ($assets->defaultLoc){
                    return link_to('admin/location/'.$assets->defaultLoc->id.'/edit', $assets->defaultLoc->name);
                }
            })

**Comment by dmcnaughtan** [comment]
I added "settings" the link_to, but still get the 404.

**Comment by snipe** [comment]
Can I see the code you added?

**Comment by snipe** [comment]
It should be around line number 1077 in `AssetsController.php` where you make the changes.
