### ISSUE TITLE
Pagination problem

### ISSUE THREAD

**Issue by kevgtan** [snipe/snipe-it#837]
In V1.2.7-beta, pagination is not working for "List All" under Assets. 
1. The upper limit number never changes. For instance, if the total is 500, listing number is 50 items per page and if you click on page "3", it will say "showing from 101 to 500 of 500", it should be "showing from 101 to 150 of 500". 
2. The number format of first page is not correct, it says "showing 1 to 050 of 500", looks like not trimming the leading 0; it should be "showing 1 to 50 of 500". However, the rest pages are good.
3. "Next" button doesn't work.
Suggestion(not bug): Current page shouldn't have a link and should have a different css style to make it stand out.

**Comment by snipe** [comment]
After 2.0, we will be switching to a different display system for assets where this will not be an issue anymore, so I'm going to close this for now.
