### ISSUE TITLE
Server Error 500 on  /auth/signin    iis installation 

### ISSUE THREAD

**Issue by craig7716** [snipe/snipe-it#838]
Error Log 

#Software: Microsoft Internet Information Services 7.5
#Version: 1.0
#Date: 2015-06-05 19:39:21
#Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) sc-status sc-substatus sc-win32-status time-taken
2015-06-05 19:39:21 192.168.6.117 GET /auth/signin - 80 - 192.168.5.105 Mozilla/5.0+(Windows+NT+6.1;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/43.0.2357.81+Safari/537.36 500 0 0 483
2015-06-05 19:39:21 192.168.6.117 GET /favicon.ico - 80 - 192.168.5.105 Mozilla/5.0+(Windows+NT+6.1;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/43.0.2357.81+Safari/537.36 200 0 0 202

**Comment by snipe** [comment]
That's not the error log we need. We need the app error log.

**Comment by craig7716** [comment]
[2015-06-05 19:52:57] local.ERROR: exception 'InvalidArgumentException' with message 'Database [] not configured.' in C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php:263
Stack trace:
#0 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(156): Illuminate\Database\DatabaseManager->getConfig(NULL)
#1 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php(64): Illuminate\Database\DatabaseManager->makeConnection(NULL)
#2 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2922): Illuminate\Database\DatabaseManager->connection(NULL)
#3 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(2888): Illuminate\Database\Eloquent\Model::resolveConnection(NULL)
#4 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1849): Illuminate\Database\Eloquent\Model->getConnection()
#5 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1790): Illuminate\Database\Eloquent\Model->newBaseQueryBuilder()
#6 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1764): Illuminate\Database\Eloquent\Model->newQueryWithoutScopes()
#7 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(656): Illuminate\Database\Eloquent\Model->newQuery()
#8 C:\inetpub\wwwroot\app\models\Setting.php(10): Illuminate\Database\Eloquent\Model::find(1)
#9 C:\inetpub\wwwroot\app\storage\views\6679b352246cd28a347ac8c0194ad964(11): Setting::getSettings()
#10 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(37): include('C:\\inetpub\\wwwr...')
#11 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\inetpub\\wwwr...', Array)
#12 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\View.php(134): Illuminate\View\Engines\CompilerEngine->get('C:\\inetpub\\wwwr...', Array)
#13 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\View.php(102): Illuminate\View\View->getContents()
#14 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\View.php(76): Illuminate\View\View->renderContents()
#15 C:\inetpub\wwwroot\app\storage\views\7ad74552159f79e1e9776f0f1428b8e4(65): Illuminate\View\View->render()
#16 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(37): include('C:\\inetpub\\wwwr...')
#17 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\inetpub\\wwwr...', Array)
#18 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\View.php(134): Illuminate\View\Engines\CompilerEngine->get('C:\\inetpub\\wwwr...', Array)
#19 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\View.php(102): Illuminate\View\View->getContents()
#20 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\View.php(76): Illuminate\View\View->renderContents()
#21 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Http\Response.php(43): Illuminate\View\View->render()
#22 C:\inetpub\wwwroot\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#23 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#24 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1036): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#25 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#26 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#27 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#28 C:\inetpub\wwwroot\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#29 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#30 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#31 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#32 C:\inetpub\wwwroot\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#33 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#34 C:\inetpub\wwwroot\public\index.php(49): Illuminate\Foundation\Application->run()
#35 {main}

Next exception 'ErrorException' with message 'Database [] not configured. (View: C:\inetpub\wwwroot\app\views\backend\layouts\default.blade.php)' in C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php:263
Stack trace:
#0 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(41): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(InvalidArgumentException), 1)
#1 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\inetpub\\wwwr...', Array)
#2 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\View.php(134): Illuminate\View\Engines\CompilerEngine->get('C:\\inetpub\\wwwr...', Array)
#3 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\View.php(102): Illuminate\View\View->getContents()
#4 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\View.php(76): Illuminate\View\View->renderContents()
#5 C:\inetpub\wwwroot\app\storage\views\7ad74552159f79e1e9776f0f1428b8e4(65): Illuminate\View\View->render()
#6 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(37): include('C:\\inetpub\\wwwr...')
#7 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\inetpub\\wwwr...', Array)
#8 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\View.php(134): Illuminate\View\Engines\CompilerEngine->get('C:\\inetpub\\wwwr...', Array)
#9 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\View.php(102): Illuminate\View\View->getContents()
#10 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\View.php(76): Illuminate\View\View->renderContents()
#11 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Http\Response.php(43): Illuminate\View\View->render()
#12 C:\inetpub\wwwroot\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#13 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#14 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1036): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#15 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#16 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#17 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#18 C:\inetpub\wwwroot\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#19 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#20 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#21 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#22 C:\inetpub\wwwroot\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#23 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#24 C:\inetpub\wwwroot\public\index.php(49): Illuminate\Foundation\Application->run()
#25 {main}

Next exception 'ErrorException' with message 'Database [] not configured. (View: C:\inetpub\wwwroot\app\views\backend\layouts\default.blade.php) (View: C:\inetpub\wwwroot\app\views\backend\layouts\default.blade.php)' in C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Database\DatabaseManager.php:263
Stack trace:
#0 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(41): Illuminate\View\Engines\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(56): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\inetpub\\wwwr...', Array)
#2 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\View.php(134): Illuminate\View\Engines\CompilerEngine->get('C:\\inetpub\\wwwr...', Array)
#3 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\View.php(102): Illuminate\View\View->getContents()
#4 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\View\View.php(76): Illuminate\View\View->renderContents()
#5 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Http\Response.php(43): Illuminate\View\View->render()
#6 C:\inetpub\wwwroot\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#7 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1501): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View))
#8 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1036): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Illuminate\View\View))
#9 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#10 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 C:\inetpub\wwwroot\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 C:\inetpub\wwwroot\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 C:\inetpub\wwwroot\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 C:\inetpub\wwwroot\public\index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []

**Comment by craig7716** [comment]
looks like it's not seeing my hostname that I gave the server. Even-though it is listed in start.php and also in my Hosts file pointing to the server.

**Comment by snipe** [comment]
@craig7716 No, that's not the issue. See http://snipeitapp.com/documentation/common-issues/
