### ISSUE TITLE
DataTables Warning

### ISSUE THREAD

**Issue by arjunnaha** [snipe/snipe-it#839]
Hi There,

I have just installed Snipe IT. On the columns down the side, when clicking on Deployed and List All, I get this error 

    DataTables warning: table id=Al9ZtfGR - Ajax error. For more information about this error, please see       http://datatables.net/tn/7

The rest of the items are working. When you click on one of the affected links, it just says 'Loading', but with the rest of the links, it brings up the sample data.

Thanks,
Arjun

**Comment by arjunnaha** [comment]
Ah, just figured there was an issue with the seed data. Deleted it and it worked!

**Comment by snipe** [comment]
@arjunnaha what version did you install? There shouldn't be any issues with the seed data at this point in the stable release. If there is, we need to fix it.

**Comment by arjunnaha** [comment]
I installed this version...

https://github.com/snipe/snipe-it/releases/tag/v1.2.7-master

**Comment by snipe** [comment]
Hm. Do you still have the app error logs from before the seed data was deleted?

**Comment by arjunnaha** [comment]
I'm afraid I don't. It should be able to be replicated by following these steps...

1. Use CLI installer and DON'T select seed data
2. Run CLI installer again and press y to install seed data

**Comment by Gehirnfussel** [comment]
I have the same error now (just upgraded to 2.0 RC) when going to the deleted assets.

**Comment by snipe** [comment]
@Gehirnfussel this is with seed data? Or your regular data?

**Comment by Gehirnfussel** [comment]
@snipe I'm not sure what you mean with seed data.

**Comment by snipe** [comment]
This discussion thread was about bad seed data. If you have an issue unrelated to the seed data, please create a new issue so we can track it separately.
