### ISSUE TITLE
Windows Server 2012R2 IIS issue

### ISSUE THREAD

**Issue by gregcornell** [snipe/snipe-it#840]
Hi,

I have installed Snipe IT following the IIS installation guide on the main website. I was able to successfully make it through all the steps without running into any issues that i wasn't able to troubleshoot using topics already on the Github issue page. After I completed my installation I went to navigate to http://localhost and when I arrived I have a generic Windows server IIS welcome page. I followed each step meticulously and I am unable to pin down the exact issue that is leading to this problem. (I am a beginner to IIS and it's quite possible i don't have a something set up perfectly). Has anyone run into this issue or have a solution to my proble>
![snipeit](https://cloud.githubusercontent.com/assets/12778231/8021320/22aa5aee-0c60-11e5-94ef-b70b0825e869.PNG)

**Comment by snipe** [comment]
My guess would be that your document root is not set correctly in your web server settings. It should be whatever/your/path/to/snipe-it/public

**Comment by gregcornell** [comment]
I double checked that I had correctly set the right document root. This is where it took me to when I right clicked the Snipe IT site and selected "Explore". Any additional help would be greatly appreciated.
![directory](https://cloud.githubusercontent.com/assets/12778231/8021401/4461d8b6-0c64-11e5-9b6d-d7356de97946.PNG)

**Comment by snipe** [comment]
@gregcornell can I see your IIS server settings? Also, did you restart the server after setting the document root?

@madd15 any insight here? You're my go-to windows guy. Definitely still seems like the document root is wrong somewhere.

**Comment by gregcornell** [comment]
Here is a screenshot of the Snipe IT website advanced settings
![settings](https://cloud.githubusercontent.com/assets/12778231/8021438/97ec77f6-0c65-11e5-99da-60a0a7befa95.PNG)

**Comment by snipe** [comment]
Okay, so you see under Sites, it has Default Web Site? I think that's what you're seeing when you go to localhost, since localhost will always pull up the default if you haven't told it not to. What happens when you go to ams.sendiks.local in a browser? (If you get a DNS error, you'll have to add a DNS entry up. I don't remember how that works in IIS, since I haven't used it in > 10 years.)

**Comment by gregcornell** [comment]
That appears to be the issue in regards to the local host problem. I did navigate using the "Browse Website" selection in the actions panel and I did receive a DNS error. If anyone else could chime in on where to go from there it would be greatly appreciated. In the mean time I will see what I can do on my own here. Thanks for all the help so far.
![dnserror](https://cloud.githubusercontent.com/assets/12778231/8021470/6a391f16-0c66-11e5-869a-797887766f34.PNG)

**Comment by snipe** [comment]
Looks like your action binding is correct, so you should just need to create an entry for ams.sendiks.local in your hosts file. I think something like this is what you need: http://www.bloggingdeveloper.com/post/Accessing-Local-IIS-Web-Sites-via-Name-using-the-Hosts-File.aspx

**Comment by gregcornell** [comment]
Following the link you provided I as able to edit my hosts file and SnipeIT is successfully running on my Windows server. The one issue I am still having is that I cannot access the site unless I'm on the server its hosted on. Is there a way to set it up so that I can access it from other devices on the same network?

(Thanks for all the help so far)

**Comment by uberbrady** [comment]
If you try to browse to the server using its IP address, do you see the app?

**Comment by gregcornell** [comment]
I was able to figure out my issue by creating 2 sets of bindings. One for the local host and another for other PC's on the network.

Thanks for all the help again, so far Snipe IT has been running issue free.

**Comment by snipe** [comment]
Great to hear!

**Comment by wdavids** [comment]
I'm having trouble to installing it on windows server 12 any tips on how to help it's a bit difficult
