### ISSUE TITLE
I hope these guys keep the credit to the original project

### ISSUE THREAD

**Issue by eduardocruz** [snipe/snipe-it#843]
https://www.upwork.com/c/jobs/Convert-Existing-PHP-Laravel-Codebase-Python-Flask_~01a64ec2d1809163a5

**Comment by snipe** [comment]
I don't have an account, so I can't see it. But I suspect I know what it is.

**Comment by eduardocruz** [comment]
Basically they want to rewrite the project using Python and Flask. As I said, I hope they at least keep the reference to the original project :P

**Comment by snipe** [comment]
Ah, yes. That's what I figured. I'm not actually sure whether a complete rewrite would violate the Affero license if they don't release the source code.

**Comment by snipe** [comment]
(Although it sounds like they'll be keeping most of the front-end code)

**Comment by snipe** [comment]
BTW, I checked, with a Free Software Fellow, and they have license it as AGPL and keep a link to the original source (mine) on the front-end to be in compliance with the Affero license from the original project.

**Comment by Cabalist** [comment]
Hello!

We are the ones rewriting the software in Python.  Currently the tool is for internal use only and not a commercial product.  We had been working on our own versions of something similar and snipeit was far enough along that it acted as an excellent design document and jumping off point for us.

I really hope we haven't offended anyone.  PHP is not our language and we are going to be heavily modifying the source to fit our needs.

We do a provide a link to this project in our code and site.  It is my understanding that with AGPL we are required to release source to anyone who uses the software.  Currently (and for the foreseeable future) everyone that uses the code also develops it.  :)  If our project becomes something publically available we'll release our code on Github.  I see no reason not to.  I don't believe we are competing product and if there is significant interest we can release the code that has been written.

The conversion is complete at this point and we are currently writing 100s of tests and expanding docstrings throughout the code.  

If I am wrong about this or there are any other clarifications I need feel free to message me.  :)

Thanks!
