### ISSUE TITLE
DataTables Warning:    Ajax error

### ISSUE THREAD

**Issue by craig7716** [snipe/snipe-it#846]
Received this error whenever clicking on deployed

**Comment by craig7716** [comment]
[2015-06-12 19:45:48] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function fullName() on a non-object' in C:\inetpub\wwwroot\snipe-it\app\controllers\admin\AssetsController.php:1069
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []

**Comment by snipe** [comment]
Did you manually manipulate any data in the database, and/or are you using seed data?

**Comment by craig7716** [comment]
Seed data


On Fri, Jun 12, 2015 at 3:09 PM, snipe <notifications@github.com> wrote:

> Did you manually manipulate any data in the database, and/or are you using
> seed data?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snipe/snipe-it/issues/846#issuecomment-111602036>.
>



-- 
*Craig Johnson*
*Network Specialist*
*Certified Google Apps Administrator*


CESA5 - Your Education Solutions Partner
office:  608.745.5463
cell:  920.471.3426

-- 
*Notice: This email and any attachments may contain confidential 
information that is exempt from disclosure under applicable law. If you 
received this email in error, please notify the sender, delete the email 
and any attachments and do not use, disclose or store the information it 
contains. The views, opinions and statements contained in this transmission 
are not necessarily the views, opinions and statements of CESA 5.*

**Comment by snipe** [comment]
Try deleting the seed data.

**Comment by craig7716** [comment]
Is there a way to delete all seed data without having to go through each
manually?

On Fri, Jun 12, 2015 at 3:10 PM, snipe <notifications@github.com> wrote:

> Try deleting the seed data.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snipe/snipe-it/issues/846#issuecomment-111602253>.
>



-- 
*Craig Johnson*
*Network Specialist*
*Certified Google Apps Administrator*


CESA5 - Your Education Solutions Partner
office:  608.745.5463
cell:  920.471.3426

-- 
*Notice: This email and any attachments may contain confidential 
information that is exempt from disclosure under applicable law. If you 
received this email in error, please notify the sender, delete the email 
and any attachments and do not use, disclose or store the information it 
contains. The views, opinions and statements contained in this transmission 
are not necessarily the views, opinions and statements of CESA 5.*

**Comment by craig7716** [comment]
Got working

Thanks!

**Comment by Tsuroerusu** [comment]
@snipe I just upgraded from 1.1 to 1.2.8, and everything seems fine, however when I go to "Deleted" under "Assets" I get this error:

"DataTables warning: table id=sYTq0WVV - Ajax error. For more information about this error, please see http://datatables.net/tn/7"

Any idea what might be causing this?

**Comment by snipe** [comment]
@Tsuroerusu - can you go to http://yourdomain.com/api/hardware/list?status=Deleted and tell me what you see?

**Comment by madd15** [comment]
This issue can be caused by an asset not have a status_id set in the database.
