### ISSUE TITLE
404 when navigating to Dashboard from Settings

### ISSUE THREAD

**Issue by quix117** [snipe/snipe-it#848]
The Dashboard and "Snipe IT Asset Management" links in the top-left both link to /admin/settings/, a page that doesn't exist (there is a /admin/settings/app/). I'm fairly sure they're meant to link to /admin/ or the index page, as they do on every other page.

EDIT: This problem also occurs on the Reports pages, except they link to /reports/, another nonexistent page. It also occurs on every page listed under the Admin tab, linking to /admin/settings/.

One smaller opportunity for improvement is to make the Dashboard and "Snipe IT Asset Management" links link to the index page as well. Right now they link to /account/, which is a bit of an inconsistency.

EDIT2: I noticed in the default.blade.php file that Dashboard is linked to {{ Config::get('app.url') }}. Based on my limited Django (not PHP) experience, I'm guessing that this was a suitable fix when Snipe-IT was a single app, but the addition of a settings app and a reports app screwed that up. I'm going to edit my application to see if adding a simple link to the index would fix this problem.

EDIT3: Seems to have fixed it! You'll be seeing my first open-source contribution in a little while lmao.

**Comment by snipe** [comment]
"but the addition of a settings app and a reports app" <-- The `{{ Config::get('app.url') }}` is set in the config file. Reports and setting are not separate apps.

**Comment by snipe** [comment]
In your `app/config/<environment>/app.php`, do you have your app URL set correctly?

**Comment by quix117** [comment]
Thanks for the quick reply! I had it set to the IP of the server, as this is on a local network. I'm guessing this is the wrong way to do it. I've also tried using http://localhost/, http://localhost/snipe-it, and http://localhost/wwwroot/snipe-it. I apologize for such a simple question, I don't have much experience with web servers. Is there a standard URL that should be used for local servers? I'm using iis on Windows Server 2008.

**Comment by snipe** [comment]
it's always hard to tell, since different servers are set up differently, but http://localhost/ usually works, unless you've got something else set up. What's your web server configuration look like? IP address *should* work (since it's a URL, just like any other URL), as long as it starts with http://

**Comment by snipe** [comment]
(Meaning what's your DocumentRoot set as, etc)

**Comment by quix117** [comment]
I redownloaded the original dashboard.blade.php file, and I'm able to use the application with http://localhost/ as my URL. However, my original problem with the Dashboard and "Snipe IT Asset Management"/logo links is back. My DocumentRoot is C:\inetpub\wwwroot\snipe-it\public, I have the IP address of the virtual machine as the IP address, and the port is 80. No host name now, but I did try using the IP address as the host name, and that didn't seem to change anything.

Today, I reinstalled Snipe-IT according to the iis Snipe-IT install directions, and I'm having the exact same issues.

**Comment by snipe** [comment]
What do you have set as `app/config/<environment>/app.php,`?

**Comment by snipe** [comment]
The code is pretty straightforward.

	            @if (Setting::getSettings()->logo)
	            	<a class="navbar-brand" href="{{ Config::get('app.url') }}" style="padding: 5px;">
	            	<img src="/uploads/{{{ Setting::getSettings()->logo }}}">
	            	</a>
	            @else
	            	<a class="navbar-brand" href="{{ Config::get('app.url') }}">
	            	{{{ Setting::getSettings()->site_name }}}
	            	</a>
	            @endif

If the app URL is set correctly in your config file, it's not really clear how your issue could be reproduced.
