### ISSUE TITLE
Previous search stays in text box

### ISSUE THREAD

**Issue by seanism** [snipe/snipe-it#849]
When switching views it keeps the previous search active.  Perhaps it's just me but I'd prefer it to clear the search when leaving the screen.
![screen shot 2015-06-15 at 11 39 05 am](https://cloud.githubusercontent.com/assets/10472025/8167443/37648e24-1353-11e5-927d-18029f8b861e.png)

**Comment by modernknight** [comment]
I could see it being a great feature, personally. Looking through my assets, if you have a large amount that are in multiple status', such as a laptop that is Ready to Deploy, then a laptop that is un-deployable, and you wish to see those other categories without having to type in keywords again, such as a pre-fix, it's quicker to do from the "List All" to Un-deployable, etc. Just my opinion though :)

**Comment by snipe** [comment]
Yeah, this is kinda by design. Is it a big issue for you, @seanism?

**Comment by seanism** [comment]
@snipe It's fine just initially found it a bit strange but I've adjusted.  Thanks for following up.

**Comment by snipe** [comment]
![turtle high five](https://cloud.githubusercontent.com/assets/197404/10955381/2bebb21e-8308-11e5-8b7f-cf9cba46757e.gif)
