### ISSUE TITLE
Mass User deletions

### ISSUE THREAD

**Issue by modernknight** [snipe/snipe-it#851]
Good afternoon!

I work as an IT staff member at a high school, so every year we have a couple hundred new students, and a couple hundred students leaving. We currently use SnipeIT to monitor our IT assets that are given to faculty, as well as an iPad Loaning program for students, thus the need to import the students to the system (though I admit, we could always do it on a per user basis).

Perhaps I am currently over looking it, but is there a way to delete our large amounts of users at the same time, or does it currently have to be at one time? I'd like to keep it so we don't have to import a list of EVERYONE all over again, and only the new ones coming in.

Thanks for the help, and loving SnipeIT! Keep up the great work!! It has certainly been AMAZING since we first installed it around October/November!!!

**Comment by snipe** [comment]
Hi Jon,

So glad to hear you're enjoying Snipe-IT. I was just thinking about this use-case today, since we do have a lot of schools using Snipe-IT. It's not something you can easily do right now (since I didn't realize when I built it that it would appeal to so many schools), but it's something we'll be adding, I think.

**Comment by modernknight** [comment]
Hey Snipe!

That is awesome :) Looking forward to seeing it! Glad I'm not the only one that has a purpose for this! :+1: Again, keep up the great work! Looking forward to seeing what other changes you bring, as it has been a remarkable experience thus far! :)

**Comment by snipe** [comment]
Thanks, dude. Comments like that make this project totally worth it. :)

![affectionate](https://cloud.githubusercontent.com/assets/197404/8173442/555d65a2-1382-11e5-9d3a-0c2891f586e5.gif)

**Comment by snipe** [comment]
Almost there....

<img width="1048" alt="screen shot 2015-07-24 at 9 43 47 pm" src="https://cloud.githubusercontent.com/assets/197404/8887940/3273d064-324d-11e5-9cc2-4b79f20b0518.png">
