### ISSUE TITLE
Dell Service Tags

### ISSUE THREAD

**Issue by ESWBitto** [snipe/snipe-it#853]
I would like to have the option to add a dell service tag in a field. Currently I don't know if the notes section is searchable if I add the tag number there.

**Comment by snipe** [comment]
Hi @ESWBitto - it wouldn't be searchable in notes at this time. We should be able to add service tags pretty easily though.

**Comment by kobie-chasehansen** [comment]
@ESWBitto - just curious, what are you using as a serial number? We enter our Dell service tags in that field...

**Comment by seanism** [comment]
I also enter the service tag as a serial number.  It is unique to each machine.

**Comment by vsposato** [comment]
@ESWBitto - What would you like a second field for, if you are already using serial number for this purpose? I am considering taking this issue up, but wanted to understand the need better.

**Comment by misilot** [comment]
Some systems have serial numbers + service tags, for example if 3rd party company does servicing.

**Comment by vsposato** [comment]
Interesting, so we would want to call them just 'service tag' not 'Dell Service Tag' correct?

**Comment by misilot** [comment]
I think that would make sense (though i'm just coming to the party late on
this request).

**Comment by ESWBitto** [comment]
I would like to be able to have something along the lines of the source type being dell then another field come up that I can enter a service tag number. I do not want to use other fields that are meant for their intended purpose.

Generally speaking though.....having the ability to just create another field and call it something would be more granular.

**Comment by kobie-chasehansen** [comment]
this could be odd/confusing for users say like me who have Dell equipment and used the serial number field as the service tag...

**Comment by seanism** [comment]
What do you mean @kobie-chasehansen ?

**Comment by ESWBitto** [comment]
@seanism He has used the serial field as a field to track dell tag numbers instead of using the field to a devices serial number.

**Comment by dbierspb** [comment]
It may be best to not add a `Service Tag` field specifically but maybe add functionality for Custom Fields.  That way we could just simply add custom fields (via models?) for Location, Office Number, Service Tag, etc.

**Comment by snipe** [comment]
Custom fields are already in progress

**Comment by seanism** [comment]
@ESWBitto for Dells there are service tags and express service codes. Both are "serial numbers" and unique to the machine which is what's confusing me.

I agree with @dbierspb just adding the option for custom fields is def the way to go.

**Comment by dbierspb** [comment]
@snipe Then it sounds like this is all good and (almost) ready to go :+1: 

@seanism I want to say that the service tags are specific / unique to either the purchase order or the model.  I have about 10x Dell XPS12 i5 Models under my control that all have the same service tag while the 5x Dell XPS12 i7 models I have are using different service tags.

I cannot be 100% sure though as these were made with separate orders from the manufacturer.

**Comment by kobie-chasehansen** [comment]
@dbierspb - That's interesting.... I've never seen a machine have the same service tag. Are you sure you aren't thinking about the order number?

Every Dell machine has a unique Service Tag and Express Service Code.

**Comment by dbierspb** [comment]
@kobie-chasehansen Ah yes you're right.  I was remembering the DP/N, not the service tag. :)

**Comment by ESWBitto** [comment]
@seanism I don't want to use the serial number field for a service tag. I don't know about your environment, but not all of our equipment is Dell exclusive. That's why I mentioned having a field with it's intended purpose instead of doing what you mentioned.

**Comment by kobie-chasehansen** [comment]
We use the serial number field for the devices serial number. on a mac laptop they have a serial, on dell laptops/desktops they have a service tag. dell equipment doesn't have a serial AND a service tag. I can't see why you would want to have both fields for one asset.

**Comment by ESWBitto** [comment]
@kobie-chasehansen I'm not sure if you are fully understanding my scenario.

This has to do with reporting.
I want to be able to pull a report of "service tags" and not have to weed out other assets that have a serial number. That is the reason for both.

**Comment by seanism** [comment]
@ESWBitto are you able to pull a report on a particular category?  You can setup a Dell Laptop category that you can pull the report from?

I see what you are trying to do.

**Comment by ESWBitto** [comment]
@seanism I guess that could be an option, but I had intended the categories to be more simplistic.
Example: Chromebooks, desktops, Laptops....etc.

**Comment by seanism** [comment]
@ESWBitto agreed.  If you could filter the reports by supplier also would that work?  IE all Dell's supplied from Dell.

**Comment by snipe** [comment]
This will be handled by custom fields, so closing this issue.
