### ISSUE TITLE
Feature Request: Drop down for licenses when creating Assets

### ISSUE THREAD

**Issue by ESWBitto** [snipe/snipe-it#855]
When creating an asset. I would like to have the ability to select software from a dropdown menu and then have the ability to add more software assigned to that same asset.

So it would look like this.

I add 200 licenses for windows 7.
Create an asset....choose windows 7 from a license drop down.
Have a clickable link that says "hey smart guy! wanna add another license to this asset?" 
why yes I do...
Then another field comes up to select another license.

To me this makes less work....and I like to work less.
##

**Comment by snipe** [comment]
Hi @ESWBitto - that's a good suggestion - thanks! We'll see if we can work it into the next version or two.

**Comment by websafe** [comment]
:+1:

**Comment by dscherertfm** [comment]
:+1:
