### ISSUE TITLE
i have an issue like this..

### ISSUE THREAD

**Issue by AmalSan** [snipe/snipe-it#856]
while running my php artisan serve i got the error like this. i dont know where it means,

pls reply, thanks for advance

ERROR: exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'games.games' doesn't exist' in /home/user002/Laravel/Games/vendor/laravel/framework/src/Illuminate/Database/Connection.php:299

**Comment by snipe** [comment]
We don't have any tables called games in Snipe-IT
