### ISSUE TITLE
Feature request: Add asset repair/upgrade tracking

### ISSUE THREAD

**Issue by leobg** [snipe/snipe-it#857]
It will be really helpful if it is possible to track repair (and perhaps upgrade) costs for the assets. Right now I just run an excel spreadsheet to add and track repair costs, but I think it will be fairly easy to integrate such functionality in SnipeIT. Would you consider adding this?

**Comment by vsposato** [comment]
@leobg - What all would you want to track? I think you might want something like - Asset Actions / Activities. This would be able to support both upgrade or repairs, so we would need an asset activity category. However, after that what would you want to know about? Here are some items I would probably want to know - 

Category (Repair, Upgrade, Maintenance)
Warranty? (yes or no)
Start Date
Completion Date
Notes
Cost

What else might you want to know? Also, what type of information would you want to be able to get back out of this? Reports, views, etc.

Vinnie

**Comment by leobg** [comment]
Yes, pretty much I want to be able to track repair cost and repair times (how much time asset has spent in repair status). Also reason for damage (pick from a list of definable reasons). Report would be able to pull a list with repairs for all assets and provide totals at the bottom line - total cost and total time spent in repair. Ideally when asset is displayed there would be link to display report for this particular asset - same report as above but for just that one asset selected.

**Comment by leobg** [comment]
Above I meant reason for performing service on the asset (not damage - bad wording) as the reason could be upgrade - not necessary a repair job.

**Comment by vsposato** [comment]
@leobg - Ok, I think I understand what you want, and am working on this.

**Comment by vsposato** [comment]
@leobg - I have something ready for you to review. You can go to http://snipe-it.vjsposato.com. I have a username and password, do you have a way that I can provide it to you?

**Comment by leobg** [comment]
@vsposato - sorry for getting back so late - you can send me the credentials to leobg 775 @ yahoo[dot]com (remove the spaces :))

**Comment by leobg** [comment]
Reopening the issue as per @vsposato request.
