### ISSUE TITLE
Unable to install with some Clustered Databases

### ISSUE THREAD

**Issue by klemorali** [snipe/snipe-it#858]
### What
I was performing an install as per the documentation http://snipeitapp.com/documentation/ for Linux. Specifically a freshly installed Ubuntu 14.04 64Bit VM. I encountered an error running the artisan app:install.

```
php artisan app:install --env=production
```
Which results in the following error.
![image](https://cloud.githubusercontent.com/assets/1407367/8219831/c970b702-151a-11e5-9570-f8c8af9081c8.png)

The tables were certainly created.
![image](https://cloud.githubusercontent.com/assets/1407367/8219856/0a0e397e-151b-11e5-9293-0b19b9fa5548.png)

The groups table even has data.
![image](https://cloud.githubusercontent.com/assets/1407367/8219870/24f97a0a-151b-11e5-8332-8a840b7f20e1.png)

However, as the error states the groups table does not have an entry with id = 1

### Possible Cause
I believe the error is due to the nature of my Clustered Database.

I'm running 3 Nodes of Maria DB Galera Cluster 10.X with 2 HA Proxy Nodes providing a Single IP for connections. In this scenario the Auto Increment on a table includes a modifier and skips numbers to ensure no duplicates are created by the Nodes. 

Here's a good explanation of those inner workings https://blog.mariadb.org/auto-increments-in-galera/

### Opinion
I haven't had a chance to dig through and try to debug this, but I don't believe there should be a requirement for a DB entry with ID = 1. My assumption is that someone relied on the first insert on a table always getting ID = 1. This is one of those "Most of time" assumptions. It would be a better method to either log the ID of this entry at creation or to go looking for it at run time. I fully admit this adds complexity, but it would function in a wider array of environments without modification or "Hacking" (_as some would call it_). 

### Workaround
1. Create a stand alone MySQL compatible database
2. Configure database.php to point to the new database
3. Run the artisan install
4. Use mysqldump (or your preferred utility) to dump the schema to file
5. Load this SQL file into an empty schema on the DB Cluster
6. Reconfigure database.php to point to your DB Cluster and the schema you just loaded with data
7. Enjoy!!

**_NOTE: It is possible that adding a group later would case a collision in the DB. I have not tested this, but it's more in my wheelhouse than fixing the potential fallout of the install error._**

Now, I'm certain there's an easier way. However, this worked flawlessly and I didn't have to keep ratcheting up the amount of effort required to get it working until it did.

**Comment by snipe** [comment]
If I may ask, why would you be running this in clustered environment?

**Comment by klemorali** [comment]
### Short Answer
Company Policy followed closely by avoiding extra management overhead.

### Long Answer
We have an operating DB cluster with all the bells and whistles of administration already in place.

Using a stand alone DB for this application would add unnecessary management overhead to this one application. We're running a few dozen different Web Apps for dozens more reasons and centralizing the Databases has proven to greatly reduce the workload and troubleshooting for my department.

_As a side note, we're running compression on our tables with the XtraDB engine. With 3 nodes we're gaining HA for our Databases and saving more than 50% of the memory footprint across our whole Datacenter. It's a considerable gain overall and we'd like to continue the trend._

As far as performance goes, we could probably switch to the sqlite backend and be just fine. Backups would just be a matter of pushing a copy somewhere else via cron or some such.

We're not clustering the Application itself. I can't imagine it will see enough use to need clustering. I also can't imagine a situation where the business would lose money because the application was unavailable even for a day or two. 

Getting the application to work with our nginx proxies was a bit of an adventure. I'll be posting an issue about that later. Mostly a "Hey, please add this to documentation" as I haven't located a place to submit updates to the Docs.

**Comment by snipe** [comment]
"I can't imagine it will see enough use to need clustering. I also can't imagine a situation where the business would lose money because the application was unavailable even for a day or two." <-- that's why I was asking :) I couldn't imagine a world where Snipe-IT would get enough concurrent usage that clustering would be necessary. Glad to know I'm not crazy :)

The offending line is in `app/commands/AppCommand.php`, line 332, I think:

` $group = Sentry::getGroupProvider()->findById(1);`

I'll see if I can tweak that a bit to fetch the admin group ID instead of assuming it's 1.

We do have docs for nginx, but welcome any additions.

**Comment by klemorali** [comment]
I'm unsure about the Exception, but after reading [HERE](https://cartalyst.com/manual/sentry/2.1#finding-groups) this feels right.
```PHP
try {
    $group = Sentry::getGroupProvider()->findById(1);
} catch (Cartalyst\Sentry\Groups\GroupNotFoundException $e {
    $group = Sentry::getGroupProvider()->findByName('Admin');
} 
```

This would keep the original functionality and only do an additional Query if the initial assumption is untrue. Could also throw in a finally block and really blow up when nothing is working.... :dizzy_face:

If you don't beat me to the punch, I might fork it and give that a go a little later.

**Comment by snipe** [comment]
I just pushed out a change that just fetches it by name instead. https://github.com/snipe/snipe-it/commit/3d4607ebd3e7f6494912f38be40945eb4aa6a57b

**Comment by klemorali** [comment]
Yeah, sorry. I saw it after I finished my comment. 

Thank You.

**Comment by snipe** [comment]
No worries - thanks for pointing it out. Your situation is unusual, to be sure, but there's no reason not to fix it so it works.

**Comment by misilot** [comment]
@snipe Another issue might be this query when trying to login:

select * from `settings` where `settings`.`id` = '1' limit 1

settings.id might not always be 1.
