### ISSUE TITLE
Proxy Configuration for Documentation

### ISSUE THREAD

**Issue by klemorali** [snipe/snipe-it#859]
I'm opening an issue here as I am uncertain where else I should propose updates to the Documentation.

### Scenario
**Using a reverse proxy in front of your web server**
Internet -> Proxy Server (Public & Private IPs) -> Web Server (Private IPs)

The Proxy server is functioning as a reverse proxy. See [Wikipedia](https://en.wikipedia.org/wiki/Reverse_proxy), [Nginx](http://nginx.com/resources/admin-guide/reverse-proxy/), [Squid](http://www.squid-cache.org/), or [Varnish](https://www.varnish-cache.org/) _(which surprisingly doesn't have a good "why use me" page)_ for more information on reverse proxies

In most deployments the Proxy will perform HTTP to HTTPS redirection and only pass requests and responses via HTTPS to the remote client. All communication between the Proxy and the Web Server occurs over HTTPS. This is where the problem comes into play.

With This Scenario: **Has Issue**
Client <-HTTPS-> Proxy <-HTTP-> Web Server

With This Scenario: **Has Issue in Reverse**
Client <-HTTP-> Proxy <-HTTPS-> Web Server

With This Scenario: **No Issue**
Client <-HTTP-> Proxy <-HTTP-> Web Server
Client <-HTTPS-> Proxy <-HTTPS-> Web Server

### Issue
In the above scenario the generated HTML will reference HTTP:// instead of HTTPS:// for all assets. This causes most browsers to throw security warnings and refuse to display the content.

_This assumes that your Proxy and Web Server are correctly configured and working properly. Meaning you have other correctly functioning Applications behind the proxy and the Web Server for snipe-it works properly if accessed directly_

Laravel & Symfony are unaware that requests to the proxy are being handled through HTTPS instead of HTTP. As such no effort is made to generate HTTPS links for Assets. 

### Corrective actions
Laravel & Symfony need to be made aware of the presence of the Proxy Server. The X-Forwarded-Proto header should be passed from the Proxy to the Web Server. With Nginx this looks like `proxy_set_header X-Forwarded-Proto $scheme;`. The Web Server should read this header and adjust it's output accordingly

The most complete solution that I have found so far is https://github.com/fideloper/TrustedProxy . As snipe-it currently uses Laravel 4.X the proper release of TrustedProxy is 2.1.1

#### To install
_From [HERE](https://github.com/fideloper/TrustedProxy/tree/a0ec0f35c82dceecc0d8975f29e6e8e85acbd419)_
In shell from application root _as the correct user :smile:_
````
composer require fideloper/proxy:~2.1.1
composer update
````

Now modify `app/config/app.php`
```PHP
'providers' => array(
    ... other providers ...
    Fideloper\Proxy\ProxyServiceProvider,
);
```

again in shell from application root
```
php artisan config:publish fideloper/proxy
```

This will work right away because the default configuration trusts all proxies. This is insecure. modify `app/config/packages/fideloper/proxy/config.php`

change
```PHP
'proxies' => '*'
```
to
```PHP
'proxies' => array('YOUR.IP.GOES.HERE'),
```
IPs and CIDR Notation is accepted.

Please see https://github.com/fideloper/TrustedProxy for more information.

I can clean this up into something more in line with the current documentation if desirable. Just missing out on a means of submitting it.

**Comment by snipe** [comment]
Updates to composer.json will blow this out though, won't it? So we should probably mention that any time an upgrade is installed, this process has to be repeated, since the core base won't have the entry in the providers or in composer. (I wish you had asked about the proxy for this, I could have saved you some time. I use this package on a different, closed-source system)

**Comment by klemorali** [comment]
You are correct about composer.json updates. This would be a pain if one were keeping up with the updates. Though to be fair that could be scripted fairly easily baring major changes to the project.

**Comment by snipe** [comment]
Unfortunately, a lot of my users are not web people, so I'm not sure most of them would know how (or that they should) script this. :-/

**Comment by klemorali** [comment]
Hmm, would it be possible to build an artisan command to perform the necessary actions? I'm not familiar with it, but it looks possible from a quick glance of docs.

**Comment by snipe** [comment]
I don't think you can run composer updates within artisan.

**Comment by klemorali** [comment]
So that leaves a few options.

1. Leave dealing with this up to the handful of users that are affects _Currently known to be 1_
    * Update docs to make the resource easier to locate
2. Develop shells scripts to handle the modification after installation
3. Add fideloper/TrustedProxy to the dependencies

Frankly I support the first option at the moment. Option 2 is not very clean. I feel bad for even thinking about creating a Batch or PowerShell script. Option 3 seems like overkill, but might be useful as more enterprise users start considering the project.

**Comment by snipe** [comment]
Yeah, I was thinking option 3 myself. It doesn't create any noticeable overhead, and then it's checked into the source, and I can just add the config note.

**Comment by snipe** [comment]
(Sometimes we have to make decisions based on usability over technical advantage, as you know. Since most of our users are IT, which is most often not webby, option 3 will result in the smallest amount of user confusion and frustration, resulting in more support overhead.)

**Comment by klemorali** [comment]
I agree with that assessment. You certainly know the user base and the direction of your project far better than I do. 

I work mostly with Asterisk and FreePBX so I'm not accustomed to real change. _I think my 2nd doctorate in pushing a rope is due next week._ So thank you for this refreshing renewal in my faith of Open Source and humanity.

**Comment by snipe** [comment]
I've added this in https://github.com/snipe/snipe-it/commit/2aa357f31507f76bbf65b81f9cda30b14c78df3f - will update the docs once 2.0 is released.

And thanks for the kind words. I wish all of our GH issues were as well documented and concise as yours have been. 

![9c219b0058cd8dd6bee2bfc95ea78779](https://cloud.githubusercontent.com/assets/197404/8263729/862391f8-1692-11e5-9a63-d22ea9acbe9a.gif)
