### ISSUE TITLE
Snipe IT license expire email alert

### ISSUE THREAD

**Issue by sovannarothhul** [snipe/snipe-it#860]
HI,
My name is Sovannaroth, new with Snipe IT. I am trying to configure snipe IT to alert email when license expire. 
I could configure email notification when we need to reset password successfully. 
Could you tell me how could I configure and test email notification when license expire?

Thanks you very much for your help.

Thanks,

**Comment by sovannarothhul** [comment]
The email alert for Warranty expire is working, but I still could not bring it work for license expire. Please help. Is the feature already available or not yet? 

Thanks,

**Comment by snipe** [comment]
License expirations isn't implemented yet.

**Comment by sjlaird** [comment]
Sorry to dig this up but where can I find out how more about this feature? I'm not seeing anything in the documentation.

**Comment by snipe** [comment]
https://snipe-it.readme.io/docs/configuring-alerts

**Comment by KARTHIKEYANINDIRAN** [comment]
Is it possible to install composer in redhat linux without internet. Please give me your suggestion. I have installed snipe-it in Windows , But I need to install Redhat LAN system. That system dont have a internet connection. Please give me a solution for this. Thanks in advance
