### ISSUE TITLE
Asset location

### ISSUE THREAD

**Issue by smenghi** [snipe/snipe-it#862]
We have the following scenario: The ICT staff works from an office, but assets assigned to them are not all in the same location. If the user (ICT staff) does not have his location set, it would be nice to see the default location of the asset instead. So when ICT checks the inventory they can directly see where the equipment is located.
I'm not sure if this is related to the issue with sub locations or checkout asset to location, but this could avoid additional model changing, only a simple if condition is needed (if user location null, then asset location).

**Comment by snipe** [comment]
Hi @smenghi - location is a required field for users (unless you've imported them).

What you're describing should be the current behavior as long as the user has no location assigned, and the asset has a default location defined. 

            if ($assets->assigned_to && $assets->assigneduser->userloc) {
                return link_to('admin/settings/locations/'.$assets->assigneduser->userloc->id.'/edit', $assets->assigneduser->userloc->name);
            } elseif ($assets->defaultLoc){
                return link_to('admin/settings/locations/'.$assets->defaultLoc->id.'/edit', $assets->defaultLoc->name);
            }

**Comment by rp-tech** [comment]
This issue had me confused for quite awhile until I discovered in another thread that the location changes to that of the user.

Here is my issue: When my users were originally imported the location was not specified.

Now I am left with a ton of assets that don't show the location.

Is there any way to bulk edit the default location for all users?

Regards,

**Comment by snipe** [comment]
There isn't currently, but if you are decent with SQL, you can get it to work by updating their location ID in the database.

**Comment by rp-tech** [comment]
Thanks

**Comment by smenghi** [comment]
I just checked our local code and I realised that defaultLoc is always 0 so the elseif is never executed and does not display a value. I then went to your demo site (current version and v2) and same problem, when user does not have a location set, the default location should be shown, but location column is empty.

**Comment by smenghi** [comment]
Hey @snipe, I'm still convinced that this is a bug! Maybe defaultLoc does not return the correct value ? Currently only locations are shown where assets are checked out to users with location (assets with default location, not checked out AND assets with default location, checked out to users without location have nothing in the LOCATION column). I checked on our application and on your demo site. 
Don't know why you closed the issue already.

**Comment by snipe** [comment]
Because it's by design. That is how it was designed to work

**Comment by rp-tech** [comment]
FYI, I fixed my issue by running the following command:

UPDATE users SET location_id='5' WHERE location_id IS NULL;

cheers,

**Comment by snipe** [comment]
Yeah, that's the easiest way to handle it (assuming there is a  location_id of 5 in your locations table)

**Comment by smenghi** [comment]
I'm sorry to bring this up again, but I'm still confused.
If I understand the code you posted above right, you do display the default location of an asset if the user has no location or the asset is not assigned to a user. This is what we want, however nothing is displayed because $assets->defaultLoc returns for each asset "0", which means the default location was not found! I checked our MySQL database and if I'm not mistaken, $assets->defaultLoc contains the location object based on the ID from the assets table field "rtd_location_id" (Values are correct, so my assets do have a default location set). 
Or maybe tell me how you get the default location of an asset on the assets view screen.

**Comment by snipe** [comment]
@smenghi - This should be fixed on develop.
