### ISSUE TITLE
Clickable order number in asset view

### ISSUE THREAD

**Issue by seanism** [snipe/snipe-it#863]
When viewing assets it would be great to click the order number and have it show everything under that order number.  I also noticed if you search for order number it doesn't display any results.

That may be a separate issue.

**Comment by snipe** [comment]
Hi @seanism - this is in the asset listing (where you see all assets at once) or the asset detail page?

**Comment by seanism** [comment]
All assets page or any of the subsequent asset stages...
Deployed, Ready to deploy, and so on.  

Make sense?

**Comment by snipe** [comment]
This will be available in 2.0 :)
