### ISSUE TITLE
I have issue in activity report Kindly assist

### ISSUE THREAD

**Issue by nadimmoallem** [snipe/snipe-it#868]
![activity report error](https://cloud.githubusercontent.com/assets/12445238/8348521/d1799b78-1b1c-11e5-9e43-6279859afd56.PNG)

**Comment by nadimmoallem** [comment]
the activity report layout is not showing properly

**Comment by snipe** [comment]
I don't really understand what you mean it's not showing properly. That activity report looks weird anyway though, as if the style sheets are not loading. It should look like this. 

![screen shot 2015-06-25 at 4 23 12 pm](https://cloud.githubusercontent.com/assets/197404/8367764/8ec05224-1b56-11e5-9b1f-b23a1ddfc0a5.png)

**Comment by nadimmoallem** [comment]
Hi,


   I think that the styles sheets are not loading. And also there is an error in the bottom of the page.

Sent from Yahoo Mail on Android

**Comment by snipe** [comment]
Well, if style sheets are not loading and you're getting an error, something else is wrong. We're going to need more information.

**Comment by nadimmoallem** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/12445238/8500570/1bbcee62-21a6-11e5-9f36-23a15bfec696.PNG)

**Comment by nadimmoallem** [comment]
this is the error in the bottom of the page.

**Comment by Nubianprince** [comment]
Can you tell us what the permissions are for the "public" folder?

**Comment by nadimmoallem** [comment]
the public folder have full permissions as per the tutorial during installation, everything is working fine but only the view of the activity report is like that. and suddenly happened . It was fine before.

**Comment by snipe** [comment]
You need to turn debug to true in your app config, and provide the info requested here:
http://snipeitapp.com/documentation/getting-help/

**Comment by snipe** [comment]
@nadimmoallem did you manually edit or delete any data directly from the database?

**Comment by nadimmoallem** [comment]
Yes I did delete some records manually. 

Sent from Yahoo Mail on Android

**Comment by snipe** [comment]
Yeah, don't do that. You must have screwed up some of the relationships in the database.

**Comment by snipe** [comment]
http://docs.snipeitapp.com/installation/manually-editing-data.html

**Comment by shivu01** [comment]
Hi Snipe,

Sudden deleted in /var/www/snipe-it/resources/views - dashboard.blade.php file content, after that recent activity and pie chart is not displaying in dashboard of the Admin page, i tried copying file from the backup but it didn't work, can you please guide me on how to recovery back the dashboard content.
![dashboard content](https://user-images.githubusercontent.com/32868298/33722073-f69f7b86-db8e-11e7-85bc-a4baabfdbcf5.JPG)

**Comment by shivu01** [comment]
Hi Snipe,

Waiting for your Comment
