### ISSUE TITLE
Add support for Internet explorer in compatibility mode

### ISSUE THREAD

**Issue by fredno** [snipe/snipe-it#869]
I work in a company that have configured Internet explorer to run in compatibility mode for all internal servers.
I figured out that adding 
<meta http-equiv="X-UA-Compatible" content="IE=edge" /> 
in the file /app/views/backend/layouts/default.blade.php under 
        

fixed the problem for me. found the description on the META tag here https://www.modern.ie/en-us/performance/how-to-use-x-ua-compatible 

Is this something that you can consider to add

**Comment by snipe** [comment]
This will be in v2.0
