### ISSUE TITLE
Unable to Delete users

### ISSUE THREAD

**Issue by misilot** [snipe/snipe-it#870]
I am getting  Error: Insufficient permissions! when trying to delete users after installing v1.2.8

**Comment by snipe** [comment]
@misilot When you look at the Permissions tab on the Edit User screen for the user that's currently logged in, does it have super admin permissions?

**Comment by misilot** [comment]
I can check tomorrow. It was the account created during install that I was
logged in with.

**Comment by snipe** [comment]
Any luck?

**Comment by misilot** [comment]
Hi @snipe no the default user did not have Super User privilege. I added that and I was able to delete users.

Thanks
