### ISSUE TITLE
Add support for stock management

### ISSUE THREAD

**Issue by kbabioch** [snipe/snipe-it#871]
Maybe I'm missing some feature, since I'm relatively new to this great product, but I would like to use snipe-it for stock management, too. So when I'm creating a new asset (or checking in an existing one) I would like to be able to enter in which box / place I'm putting it. This makes sure I can find it quickly, when someone asks for it ;).

One could, in theory, use locations for that, but I then would have to create a new location for each box / storage place I have, but having hundreds of locations won't make things easier. It might even get confusing to users, since they get in touch with locations, too.

I guess, one could also use users for this purposes, but once again it feels kind of wrong, since it will be shown as "checked out" in this case.

Am I the first and only one to have such a specific need, or am I trying to use snipe-it for something it is simply not? Alternatives that provide stock management functionality like this, are usually not able to manage assets in the same way snipe-it does, e.g. they do not support warranties, licenses and the whole "checked in" and "checked out to" statuses ...
##

**Comment by snipe** [comment]
This is the first I'm hearing of anyone needing/wanting this feature. Would the sub-locations coming in v2.0 not work? (You would need to come up with sub-locations for every box, of course.) Short of using sub-locations, how would you propose to solve for this? A text field?

**Comment by kbabioch** [comment]
I haven't looked into sub-locations, to be honest, but as long as "customers" are also exposed to this, it doesn't really solve the issue. A text field would be fine for the beginning, although I would prefer a complete new "sub-section", i.e. something very similar to locations, but dedicated to stock management, which is only visible to "stock managers". Properties attached to each placement group would be dimensions and weight of the boxes, and things like that. 

There are quite a few (open source) solutions for these kind of tasks. One can find them under the term "stock management" or "iventory management". But AFAIK all of them lack support for asset tracking, where snipe-it comes in really handy.
