### ISSUE TITLE
MAC address field no longer shows up in Edit Asset

### ISSUE THREAD

**Issue by juchiu** [snipe/snipe-it#872]
On the 2.0 branch, the option to display the MAC address field is selected for the asset model, but when creating/editing an asset of that type, the field is missing.

**Comment by snipe** [comment]
I'm unable to reproduce this. It is showing for me, both locally and on the demo. (I'm using the Inspiron non-touch asset model as a test)

![screen shot 2015-06-25 at 4 16 39 pm](https://cloud.githubusercontent.com/assets/197404/8367686/adebca80-1b55-11e5-996e-97e910c2535d.png)
![screen shot 2015-06-25 at 4 16 52 pm](https://cloud.githubusercontent.com/assets/197404/8367687/ae0f15ee-1b55-11e5-9309-d89d269bfc6e.png)

**Comment by juchiu** [comment]
Hrm. This morning now I'm unable to reproduce it. Perhaps it was just a cached file that caused it?
