### ISSUE TITLE
Asset acceptance feature not working properly.

### ISSUE THREAD

**Issue by dzineradk** [snipe/snipe-it#875]
I have notice another issue that when i am checking out a asset to an user and acceptance mail is going to that user , that's great but after logging with respected link if the user cancel that acceptance of the assigned asset, though it showing the asset is being checked out to that user and on clicking cancel tab it takes to edit profile page. Here i required that if the user cancel the acceptance the assigned asset will automatically check in with the note "User Declined" and takes him/her to user homepage. Please have a look on this matter.
Thank you.

**Comment by snipe** [comment]
This is fixed in 2.0
