### ISSUE TITLE
Numbers in location address

### ISSUE THREAD

**Issue by vabue** [snipe/snipe-it#880]
While creating new location got error - "The address2 field may only contain letters, commas, spaces and dashes".
But there are building numbers, room numbers and so on.

Snipe-it ver 1.2.7-master

**Comment by snipe** [comment]
Is it not possible to simply use letters, numbers, spaces and dashes? 

123 Main Street
Bldg 4, Rm 7

Etc

**Comment by snipe** [comment]
I think this may already be fixed on v2.0

**Comment by snipe** [comment]
<img width="1009" alt="screen shot 2015-07-02 at 5 33 35 pm" src="https://cloud.githubusercontent.com/assets/197404/8490600/886c537a-20e0-11e5-9fd9-6e11cc94f1b2.png">
