### ISSUE TITLE
I installed in Subdomain, but i getting 403 error 

### ISSUE THREAD

**Issue by thomas1216** [snipe/snipe-it#882]
Hello

I Installed Snipe-it on Subdomain  ex:  inventory.example.com
But i getting 403 error 

the files are Public_html/inventory/

**Comment by snipe** [comment]
Please see the documentation on getting help: http://snipeitapp.com/documentation/getting-help/

**Comment by thomas1216** [comment]
i found the problem, if i open inventory.example.com/public/ works perfect, but how make to work going to inventory.example.com?  i using linux Server, i got last snipe-It Version.

thanks

**Comment by madd15** [comment]
@thomas1216 Check http://snipeitapp.com/documentation/installing-on-linuxosx/#Configuring_Your_Web_Server for details on setting the document root to the public directory.

**Comment by thomas1216** [comment]
Never mind, i fix the issue, thanks for the assistance

**Comment by omerzia** [comment]
@JarbyDev How did you fix the issue? Can you please share ?

Thanks
Regards
