### ISSUE TITLE
Feature Request: Track missing/lost assets and also generate reports

### ISSUE THREAD

**Issue by jrtoman** [snipe/snipe-it#885]
Would it be possible to add an option to label an asset as missing or lost track of? We have had problems where another team will borrow an asset and somehow loose track of it. The goal is to basically have an option that will let us know that an asset is missing and to keep our eyes peeled for it. If that asset is not recovered after a given amount of time we would then like to transfer it out.

**Comment by snipe** [comment]
I think most folks just create a status of "undeployable" and name it "Lost or Stolen". Would that not work?

**Comment by jrtoman** [comment]
Would it be easy to sort out in a report? I am currently unable to login to the demo site and test this.

**Comment by snipe** [comment]
@jrtoman Assets with a Lost/Stolen undeployable status will show up in the Undeployable link in the sidenav, and their undeployable status will show in the asset report.

**Comment by i5rov** [comment]
sorry for resurrecting this one, but would it be possible to add a report at the bottom for lost/stolen assets?
