### ISSUE TITLE
Upgrading

### ISSUE THREAD

**Issue by alexisskeates** [snipe/snipe-it#887]
Sorry this may seem like a stupid question, but I'm trying to upgrade from version v1.2.6-12-g3263543 to latest I think it is 1.2.8 or so.

I've read the upgrade documentation and I assume the easiest way to do this is via a git pull. My knowledge and use of git is very limited I can pull something down from it and that is about it. When I try this I get an error essentially telling me the clone can't be completed because the folder is not empty.

I assume this is happening because I'm trying to clone to the folder that already contains contents and what I need to do is to pull just the updated files from git-hub.

Would anyone have some instructions on how to do this and perhaps this could be added to the help documentation.

**Comment by snipe** [comment]
Doing a git pull will only really work easily if you did the initial install via `git clone` in an empty directory, and used that as your Snipe-IT code base. You can't clone into a directory that already has contents in it. Might be easiest to just download the zip file of the release and drop those files in over your existing ones.

**Comment by alexisskeates** [comment]
The original install was done via git clone using the following git clone https://github.com/snipe/snipe-it.git /var/www/

So in this case I assume I can then do a git pull?

**Comment by snipe** [comment]
Yes, you should be able to git pull
