### ISSUE TITLE
User unable to request for a request-able asset from user's request-able panel. 

### ISSUE THREAD

**Issue by dzineradk** [snipe/snipe-it#889]
User unable to request for a request-able asset from user's request-able panel. It will be better that if a request button is present beside the request-able assets and a request mail triggered to the specific admin on click the request button. According to the sent mail that admin should able to assign the requested asset to that user. Please have a look on this matter.

Thank you.

![snipe it](https://cloud.githubusercontent.com/assets/12966199/8518210/9bd86ae0-23e5-11e5-94f8-c7050a560e27.jpg)

**Comment by snipe** [comment]
Yes, that's the plan. It has t neem implemented yet.
