### ISSUE TITLE
Checkin/Checkout should, upon completion, take me back to whereever I came from

### ISSUE THREAD

**Issue by uberbrady** [snipe/snipe-it#89]
I was trying to 'fire' someone - so I went in to the User, saw the list of his assets/licenses, and then went to one-by-one check-in each thing before I deleted the user.

After having done the 'check in' - I wasn't where I came from.

Ideally, wherever I started the checkin/checkout process from, that should be where I end up going back to when it's complete.

If you wanted to get fancy, you could AJAX in a model content for those uses, but that would require that you refresh the page when you're done anyways - so that might be more difficult/confusing than doing it by just remembering where the user came from and sending them back to there.

**Comment by snipe** [comment]
You can't delete a user with assets checked out to them, so I don't think this issue is valid anymore.
