### ISSUE TITLE
Server error upgrading from 1.2.1 to 1.2.8

### ISSUE THREAD

**Issue by suiciety** [snipe/snipe-it#893]
I've tried an upgrade to the latest version (copied over original) and get a 500 error on the login page (below)

There were no errors doing the composer updates or artisian migrates and I removed files in storage/cache, views and sessions. Also removed cookies in my browser.

This is on Ubuntu 14.04, Apache2 which has been progressively upgraded since .3 release.

[2015-07-07 01:43:57] production.ERROR: exception 'ErrorException' with message 'Declaration of Illuminate\View\Engines\CompilerEngine::handleViewException() should be compatible with Illuminate\View\Engines\PhpEngine::handleViewException($e)' in /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php:0
Stack trace:
#0 /var/www/html/vendor/composer/ClassLoader.php(412): Illuminate\Exception\Handler->handleError(2048, 'Declaration of ...', '/var/www/html/v...', 0, Array)
#1 /var/www/html/vendor/composer/ClassLoader.php(412): Composer\Autoload\includeFile()
#2 /var/www/html/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/var/www/html/v...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Illuminate\View...')
#4 /var/www/html/bootstrap/compiled.php(4282): spl_autoload_call('Illuminate\View...')
#5 [internal function]: Illuminate\View\ViewServiceProvider->Illuminate\View\{closure}()
#6 /var/www/html/bootstrap/compiled.php(8869): call_user_func(Object(Closure))
#7 /var/www/html/bootstrap/compiled.php(9063): Illuminate\View\Engines\EngineResolver->resolve('blade')
#8 /var/www/html/bootstrap/compiled.php(9019): Illuminate\View\Environment->getEngineFromPath('/var/www/html/a...')
#9 /var/www/html/bootstrap/compiled.php(3176): Illuminate\View\Environment->make('frontend.auth.s...')
#10 /var/www/html/app/controllers/AuthController.php(18): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#11 /var/www/html/app/controllers/AuthController.php(18): Illuminate\Support\Facades\View::make('frontend.auth.s...')
#12 [internal function]: AuthController->getSignin()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231): call_user_func_array(Array, Array)
#14 /var/www/html/bootstrap/compiled.php(5437): Illuminate\Routing\Controller->callAction('getSignin', Array)
#15 /var/www/html/bootstrap/compiled.php(5425): Illuminate\Routing\ControllerDispatcher->call(Object(AuthController), Object(Illuminate\Routing\Route), 'getSignin')
#16 /var/www/html/bootstrap/compiled.php(4657): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'AuthController', 'getSignin')
#17 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#18 /var/www/html/bootstrap/compiled.php(4984): call_user_func_array(Object(Closure), Array)
#19 /var/www/html/bootstrap/compiled.php(4682): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 /var/www/html/bootstrap/compiled.php(4670): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#21 /var/www/html/bootstrap/compiled.php(706): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#22 /var/www/html/bootstrap/compiled.php(687): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#23 /var/www/html/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#24 /var/www/html/bootstrap/compiled.php(1146): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#25 /var/www/html/bootstrap/compiled.php(7311): Illuminate\Http\FrameGuard->handle(Object(Illuminate\Http\Request), 1, true)
#26 /var/www/html/bootstrap/compiled.php(7908): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#27 /var/www/html/bootstrap/compiled.php(7855): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#28 /var/www/html/bootstrap/compiled.php(10886): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#29 /var/www/html/bootstrap/compiled.php(648): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#30 /var/www/html/public/index.php(49): Illuminate\Foundation\Application->run()
#31 {main} [] []

**Comment by snipe** [comment]
Try: 

`php artisan clear-compiled` before running composer install or composer update, and/or remove `bootstrap/compiled.php`.

**Comment by suiciety** [comment]
Awesome, I'm in!

Thanks for the prompt response.

**Comment by snipe** [comment]
:) No problem
