### ISSUE TITLE
Dashboard link goes to current page

### ISSUE THREAD

**Issue by suiciety** [snipe/snipe-it#894]
Ok,

I love the dashboard which I don't remember seeing in previous versions but for some reason I only get it when I log in or manually change the URL to / . The link in the side bar always seems to point to the current page.

**Comment by snipe** [comment]
What happens when you click on the site name in the top bar?

**Comment by suiciety** [comment]
It also goes to the current page

**Comment by snipe** [comment]
Do you have this installed in a sub-folder or something?

(Also, the latest off of develop hopefully fixes this.)

**Comment by suiciety** [comment]
Installed under /var/www/html on Ubuntu

**Comment by suiciety** [comment]
Apache2 document root set to /var/www/html/public

**Comment by snipe** [comment]
What do you have set in your `app/config/production/app.php` for `url`?

**Comment by suiciety** [comment]
Ok, checked and it looks like I didn't update the production directory with a new app.php moving from testing at some point in the past. It's behaving as expected.

**Comment by snipe** [comment]
Great!

**Comment by suiciety** [comment]
Is it possible to have the default location listed in the asset lists? We use the default location for desktops etc. that aren't assigned to people and at the moment they just show as blank.

We use a status of 'Deployed on-site' to show they are on-site assets.

**Comment by snipe** [comment]
That's fixed on the latest version of develop.

**Comment by suiciety** [comment]
Ok, thanks. Also in the last version we used the checkout button was removed for these assets (which is what we expected), is that part of the fix as well?

**Comment by snipe** [comment]
I'm not sure I know what you mean

**Comment by suiciety** [comment]
In the version we were using before this one when we set our custom status to 'Deployed on site' this also removed the checkin/checkout button in the all assets list.

This works for us because these assets are in shared spaces an can't be checked out by anyone.

**Comment by snipe** [comment]
It will give you a checkout button if the status label is has an attribute of "deployable". If you don't want something to be considered deployable, just make sure the status label doesn't have that attribute set to true.

**Comment by suiciety** [comment]
That's what I thought, I toggled the undeployable option for the status on/off and it isn't reflected in the lists.

**Comment by snipe** [comment]
You'll have to open a bug about that

**Comment by suiciety** [comment]
Will do.

**Comment by snipe** [comment]
![sagan-awesome](https://cloud.githubusercontent.com/assets/197404/8537972/c739256e-241a-11e5-958e-7736a942e2da.gif)
