### ISSUE TITLE
Setting status to deployable does not remove checkin/checkout button

### ISSUE THREAD

**Issue by suiciety** [snipe/snipe-it#896]
We have created a custom status called 'Deployed on-site' which we have set to 'Undeployable'. In previous versions this correctly removed the checkin/checkout button on the asset and in lists.

However when upgrading to 1.2.7 this behavior does not work. The checkin/Checkout button still appears in lists.
![image](https://cloud.githubusercontent.com/assets/8053509/8538597/1e9bfeb6-24b2-11e5-9a0a-ede7e789be82.png)

![image](https://cloud.githubusercontent.com/assets/8053509/8538604/325cc138-24b2-11e5-9704-f74a9b45de5a.png)

**Comment by snipe** [comment]
I can confirm this bug on the demo. An asset with an undeployable staus should not have a checkout option

**Comment by madd15** [comment]
It seems in the switch to Datatables we left out a check of assetstatus with the inout column
