### ISSUE TITLE
Asset Cloning

### ISSUE THREAD

**Issue by Marc127** [snipe/snipe-it#899]
Hi,

has anyone got working a mass asset clone import function.  Where it will only pull in the asset and serial number?  The rest of the details are the same.

Or if anyone can point me in the right direction on where I could be making the changes so I can have a go?

cheers

**Comment by snipe** [comment]
Hi @Marc127 - why did you close this?

**Comment by Marc127** [comment]
Sorry, it was really related to importing assets, which i see now is already a feature request.  I had 2000 servers to input into snipeit, and in the end i just did it through mysql load csv file, which worked nicely, as they were all exactly the same purchase and model.

**Comment by snipe** [comment]
Got it. We do have a rough asset import tool on `develop` right now, but I guess you don't need it anymore.

**Comment by Marc127** [comment]
Thank you for the reply.. the import tool will definitely help a lot in the future, as there are groups which vary slightly.. so i'm looking forward to that feature.. SnipeIT is simply awesome

**Comment by snipe** [comment]
Thanks! The import tool is still rough, but I've successfully used it for a CSV of over 2000 records. It will get better over time, for sure. :)

Version 2.0 is coming out soon, which we're pretty stoked about. 

![dog-lips](https://cloud.githubusercontent.com/assets/197404/8632428/dc9a91a8-274f-11e5-801c-29c4df08e185.gif)
