### ISSUE TITLE
Only unique assets in license seat view

### ISSUE THREAD

**Issue by diekmanu** [snipe/snipe-it#900]
So what's really annoying to me. We have approx. 400 Windows licenses. When I check out these licenses (seats) to assets there is no warning/notice (unlike creating assets with duplicate asset id's) when there is a license already checked out to that particular asset/user for that software product. So there is high chance of having duplicates.

Any chance of having some mechanism which prevents duplicate asset entries when checking out license seats?

Regards.

**Comment by diekmanu** [comment]
To make things more clear:
![2015-07-09_14h54_16](https://cloud.githubusercontent.com/assets/13235891/8595886/30da0668-264c-11e5-8f71-b807723eb860.png)

This shouldn't be possible :'(

**Comment by snipe** [comment]
Why did you close this?

**Comment by diekmanu** [comment]
Wrong button...sorry

**Comment by diekmanu** [comment]
Any way to adapt this to the License/LicenseSeat.php (from model Asset.php)?
    protected $rules = array(
        ....
        'asset_tag'   		=> 'required|alpha_space|min:3|max:255|**unique:assets,asset_tag,{id}**',
        ....
        );

I can't get the validation to work for already license-assigned assets. I would like to have a message come up similar to the one from the "asset creation view" in case of duplicate entries  => The :attribute has already been taken.

**Comment by snipe** [comment]
Just so I'm clear on your requirements and use-case, you're asking that a license not be allowed to be checked out to the same person twice, correct? (So Jane Smith can't end up with two copies of Windows?) I think we need to get assigning to assets working before we can do that, because Jane Smith might have two computers, in which case she might actually need two copies of Windows.

**Comment by diekmanu** [comment]
For us the typical way is checking out licenses to assets. License seats to users is a very rare scenario. So when I check out a license seat I only choose the corresponding computer - not the currently assigned user (which changes quite often). Perhaps there should be a distinction between user-/asset-assigned licenses in the license seat overview? An example:

![2015-07-30_14h54_55](https://cloud.githubusercontent.com/assets/13235891/8983624/3c5ed1c2-36cc-11e5-8791-c8a5ac7afb97.png)

In this case I don't want an asset to hold a Windows copy twice. For me there is high chance of having these types of assets, when there's no kind of verification in the "license checkout wizard". 

Something like this:
![2015-07-30_15h28_52](https://cloud.githubusercontent.com/assets/13235891/8984255/bcd3c1ce-36d0-11e5-8dd4-940802cd72bb.png)

Before I forget...we really enjoy working with Snipe-IT. Thanks for making this possible!

**Comment by eduardok** [comment]
Snipe, I think this should (imho) be implemented like this:
1) in the license (e.g. http://snipe/admin/licenses/1/edit), add checkbox "Force uniqueness" (or whatever better wording).
2) in the checkout screen for the license seat (e.g. http://snipe/admin/licenses/1/checkout), make sure not even show in the combos the users or assets that already had that license assigned to :)

The other option would be to add a asterisk or something to indicate the ones that already have a license assigned, so we can easily spot and skip to next user without the given license.
