### ISSUE TITLE
Is the login IP based?

### ISSUE THREAD

**Issue by websafe** [snipe/snipe-it#903]
Hello :-)

I was logged in on my desktop. Then I've logged in on my smartphone and this caused a logout on the desktop. Can the same user be logged in only from one IP address?

BTW, this behavior makes the demo kinda unusable when multiple people are viewing it...

Can this be somehow turned off? I'm on v1.2.8-18.

**Comment by snipe** [comment]
@websafe It's based on browser, not IP. The same thing will happen if you login on the same machine using two different browsers. It's possible to disable (with some additional coding), but it's a security feature that we're not really interested in disabling. The easiest thing to do is to login as the general admin user and create your own login.

**Comment by websafe** [comment]
Wow! Thank You @snipe :+1:

**Comment by snipe** [comment]
`multi_login` is set to true in the local and staging versions to make development easier, but will be set to false by default for production. (Also, if you never copy over the new `session.example.php` in the config directory of your environment, it will also default to false.)
