### ISSUE TITLE
Pages not rendering correctly

### ISSUE THREAD

**Issue by scottwood** [snipe/snipe-it#904]
Hi,

I followed the install guide and am able to log in, but none of the pages seem to be rendering correclty, I cant find anything in the apache logs, and I'm at a loss is anyone able to help or point me in the right direction?

See the attached screenshot for how the pages are rendering.

![untitled](https://cloud.githubusercontent.com/assets/13256624/8597547/f5ed3bea-264d-11e5-8195-38f299e3c48c.jpg)

Thanks.

**Comment by snipe** [comment]
What do you you browser's developer tools show you?

**Comment by scottwood** [comment]
Not entirely sure what I need to be looking for within the browser dev tools, nothing stands out to me.

**Comment by snipe** [comment]
Look for any files that are coming up not found or are timing out. It looks like the CSS isn't loading correctly, or something else is blocking it.

**Comment by scottwood** [comment]
Everything looks be loading OK no errors reported, as long as I am looking in the right place? Sorry this isn't what I normally deal with!

![untitled1](https://cloud.githubusercontent.com/assets/13256624/8599769/40322c40-265a-11e5-8980-e93b9f65c8ff.jpg)

Thanks.

**Comment by madd15** [comment]
If you go into the console tab it should show any errors

**Comment by scottwood** [comment]
Hi, this is the only error that is generated:

signin:1 Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: only screen and (-webkit-min-device-pixel-ratio: 1.5), only screen and (min-resolution: 144dpi)

**Comment by scottwood** [comment]
I have just re-installed the application again and now its all working fine, I've clearly done something wrong somewhere in the installation previously, thanks for your help!

**Comment by snipe** [comment]
No worries, glad you got it sorted :)
