### ISSUE TITLE
unknown database "snipeit_laravel"

### ISSUE THREAD

**Issue by k-temp** [snipe/snipe-it#905]
PROBLEM: failed install/config while running "php artisan app:install --env=production"
ERROR MESSAGE:   [PDOException]
  SQLSTATE[HY000] [1049] Unknown database 'snipeit_laravel'

PLATFORM: Windows Server 2008 R2, IIS 7.5
I have successfully installed prerequisites IIS, IIS URL rewrite, PHP 5.4, MariaDB, PHP manager for IIS, Composer and Notepad++.
The "composer install" command succeeded to install all dependencies without error.

I assume my error is in configuration of database.php file, but I don't know how to rectify. Can someone help please?

**Comment by snipe** [comment]
Did you actually create a database and grant a user to it?

**Comment by k-temp** [comment]
I followed the steps on http://snipeitapp.com/documentation/installing-on-iis/.
Perhaps that step was not documented? 
If someone has instructions, please share them.

**Comment by snipe** [comment]
http://www.wikihow.com/Create-a-Database-in-MySQL

**Comment by snipe** [comment]
Alternatively, this one might help: http://www.lanexa.net/2011/08/create-a-mysql-database-username-password-and-permissions-from-the-command-line/
