### ISSUE TITLE
403 Error IIS install

### ISSUE THREAD

**Issue by clarm060** [snipe/snipe-it#910]
I have ran the install and when going to my URL i get a 403 Error but if i navagate to http://MYDomain.com/public/index.php/home  i get:

Whoops!

Server Error: 500 (Internal Server Error)

What does this mean?

Something went wrong on our servers while we were processing your request. We're really sorry about this, and will work hard to get this resolved as soon as possible.

Perhaps you would like to go to our home page?

Is there something i'm missing?

The IUSR has full control to the folder.

**Comment by snipe** [comment]
Please see the Getting Help documentation:
http://snipeitapp.com/documentation/getting-help/

(Also, the URL should be http://MYDomain.com/, not http://MYDomain.com/public/index.php/home)

**Comment by clarm060** [comment]
Looks like the IIS site needed to be pointed to \install Folder\public not \Install Folder\

Its working now thanks!
