### ISSUE TITLE
Select notes column from find

### ISSUE THREAD

**Issue by mtucker6784** [snipe/snipe-it#911]
Hey @snipe , I know you're swamped in stuff, sure appreciate you tagging in on Snipe-IT...It sure is an awesome tool!

Question:

Can you point me in the right direction to modify the "search" feature so that I can also query from assets' notes column?

I'm searching in : /vendor/laravel/framework/tests/Database/DatabaseQueryBuilderTest.php , which is where (I think) I need to be, but I'm not sure which function is used for the search feature. Does this make sense?

Thanks! 
-Mike

**Comment by snipe** [comment]
Hi @mtucker6784 - thanks for the kind words! 

To edit what fields are displayed or searchable in the list view, you'll need to edit `app/controllers/AssetsController.php`. The `getDatatables` method there is what you're looking for.

**Comment by mtucker6784** [comment]
Damn. Gotcha. Thanks much!  I'll go from here :P

**Comment by snipe** [comment]
![tumblr_nr4wo0unyd1s373hwo1_400](https://cloud.githubusercontent.com/assets/197404/8660722/7f929b8a-2967-11e5-8155-fa441bdfdb14.gif)
