### ISSUE TITLE
Enhancement: user selection dropdowns

### ISSUE THREAD

**Issue by aalaily** [snipe/snipe-it#916]
**Enhancement Proposed**
I would like to suggest that a unique identifier (email address) be displayed whenever a user selection dropdown is presented.

**Advantage**
When you have a long list of users, it is likely that two people will have the same name.  When this happens, the drop down list will only show their first & last names.  Unfortunately, this can prove to be problematic if you are looking to assign an asset or license to one particular user.

**Disadvantage**
The only one I can think of is that the dropdown list displayed will be wider

**Comment by snipe** [comment]
Hi @aalaily - that sounds reasonable.

**Comment by aalaily** [comment]
Good stuff - thanks.

**Comment by madd15** [comment]
This will be added by Version 2.0 when it is released.

**Comment by aalaily** [comment]
OK thanks.

**Comment by snipe** [comment]
@madd15 - remember that in 2.0, we're actually using usernames not email addresses though. Email addresses will no longer be required, so we should probably update that 2.0 code.

**Comment by aalaily** [comment]
Makes sense.

**Comment by madd15** [comment]
@snipe ok can update to username if you haven't already

**Comment by madd15** [comment]
PR #933 will change to username as the identifier
