### ISSUE TITLE
Issue with Permissions to Document Root

### ISSUE THREAD

**Issue by ESWBitto** [snipe/snipe-it#918]
I've tried changing the permissions per the installation instructions and when I do I'm not able to access the application via web browser. The only way for me to access it is if I do a 
chmod 777 /var/www/html -R

This isn't ideal and I wondered if anyone had any suggestions I could try.

Also when I change ownership to anything other than root it does the same thing.

**Comment by snipe** [comment]
"I'm not able to access the application via web browser." <-- what does this mean? What error are you seeing?

Can you show me the output of an `ls -al` on `/var/www/html`?

Also, what user did you run the composer install under?

**Comment by ESWBitto** [comment]
Hey Snipe,

In the browser I get "Error in exception handler." when I set the doc root as...
sudo chmod 755 -R /var/www/html/

The error goes away when I set it to 777. I'm logged in as a user with sudo powwa.

**Comment by snipe** [comment]
Handled via Gitter :)
