### ISSUE TITLE
Feature Request: Asset Packages/Kits

### ISSUE THREAD

**Issue by joeykhan** [snipe/snipe-it#922]
In our case, if someone wants to borrow a camera, they're not just going to check out the camera body

It would include 

body
2 batteries
memory card
charger

The package would preferably not be a separate asset itself, but a collection of the assets grouped together.

Also, the package would preferably not contain specific assets, but just asset models. So when you go to checkout a camera kit for example, it just compiles an available asset corresponding to each model in the package. That way I can checkout camera or battery or charger number 302 to someone without worrying that its part of camera package 1 because the package will just pick a camera and batteries etc. that are not checked out.

**Comment by kobie-chasehansen** [comment]
dup of #563

**Comment by joeykhan** [comment]
So do I delete this and add my comments to the other one?

**Comment by kobie-chasehansen** [comment]
I would say close it out, add any additional notes to #563
