### ISSUE TITLE
android app login

### ISSUE THREAD

**Issue by jesulo** [snipe/snipe-it#9234]
**Server (please complete the following information):**
 - Snipe-IT Version last
 - OS:CentOS
 - Web Server: [e.g. Apache, IIS]
 - PHP 7.3

**Is your feature request related to a problem? Please describe.**
new feature

**Describe the solution you'd like**
Hello, how can I define a controller login to access from an android application that I am creating, username and password, and use token. I just need a little guide. Regards

**Comment by novastream** [comment]
It depends, you can take a look at RestSharp if you are using Xamarin and C#.

[RestSharp home](https://restsharp.dev/)
[RestSharp authenticators](https://restsharp.dev/usage/authenticators.html)

And here you have the Api documentation for Snipe-it
https://snipe-it.readme.io/reference

**Comment by jesulo** [comment]
I m creating a native android app. I haved luck with login for app

**Comment by diegogarciadev** [comment]
@jesulo I'd lile know how you have developed the login. Can you contact me? Thank you
