### ISSUE TITLE
Question (not issue): Export filtered results

### ISSUE THREAD

**Issue by mtucker6784** [snipe/snipe-it#924]
Hey there!

quick question:

Is there a way I can force Snipe It to only export the results displayed on the screen from the filter? So example:  I search for "Elementary", and instead of exporting all the entries in my inventory, I only export the entries displayed for the "Elementary" results.

Is this something I could do through editing the search controller? If so, if someone can point me in the right direction, I'll be glad to proceed on my way and figure it out (if Snipe It can't do it already.)

**Comment by snipe** [comment]
We don't actually have a search controller. The searching is all handled via DataTables. http://datatables.net

**Comment by mtucker6784** [comment]
Sounds good, all I needed to know. Thanks
