### ISSUE TITLE
GoDaddy Hosting, Google Apps Email

### ISSUE THREAD

**Issue by joeykhan** [snipe/snipe-it#925]
Just posting this so I can add a tiny bounty.

Site is hosted by Godaddy but email is with Google Apps.

Snipe is able to get an email when she tries the forgot password feature at snipe.net, but emails for asset checkout acceptance and forgot password don't come to our own emails at our own domain.

**Comment by madd15** [comment]
@joeykhan have you setup `app/config/production/mail.php`? If possible can you post it here obv. you can remove sensitive information.

**Comment by snipe** [comment]
@madd15 - my hunch is that it's a GoDaddy issue. My thought is that something might be donked with them where they don't look outside their own domains. I honestly don't know tho. I personally set up @joeykhan's install and his mail server is working. Just not for his own domain.

**Comment by madd15** [comment]
How odd not 100% sure then

**Comment by joeykhan** [comment]
The amazing @snipe found the fix!!! Must use SMTP server of relay-hosting.secureserver.net with port 25 and no authentication!!

**Comment by snipe** [comment]
Documentation has been updated to reflect this.

**Comment by madd15** [comment]
![exc](http://www.reactiongifs.com/r/exc.gif)
