### ISSUE TITLE
copy button as flash on version 1.2.8

### ISSUE THREAD

**Issue by benunter** [snipe/snipe-it#926]
Hello,

I updated to v1.2.8 and there is a flash button on list of assets. The button is on the top right of the window near the search box.

Is it normal to have a flash button here (and html buttons for other actions) ? 

Thank you

**Comment by madd15** [comment]
The buttons in question are part of datatables

**Comment by snipe** [comment]
Yeah, there's nothing we can do about that. It does seem weird that DataTables is using Flash, but it's part of their javascript package.
