### ISSUE TITLE
IIS Configuration in Win 7 for SnipeIT

### ISSUE THREAD

**Issue by Biopticon** [snipe/snipe-it#927]
Hello,

I am trying to install SnipeIt on my computer running Win 7 OS.IN the IIS manager I created SnipeIt website.   Then according to instructions, I should double click on the SnipeIT entry and then "Double Click URL Rewrite" then "In the action pane click Import Rules..". nothing happens. How can I get to these to configure IIS as instructed? Thank you.

**Comment by snipe** [comment]
Hi @Biopticon - @madd15 might be able to help. He's the resident IIS expert :)

**Comment by Biopticon** [comment]
I am currently on the chat waiting somebody to help me. I downloaded the URL Rewrite  module and installed it, still see nothing though! Thank you responding.

**Comment by vaatamohan** [comment]
as per your document i have create iis website after that it is show error 500 .i have referred lot of document  even if i couldn't solve error. 

1.while installing composer software ask php path 
2.database created using marin DB ,i dont know  how do connect  connect database  snipe it.

given document in online not enough to configure

**Comment by snipe** [comment]
Please do not resurrect old threads, and instead start a new one with your own issues. And provide the information requested in the Getting Help documentation. https://snipe-it.readme.io/docs/getting-help
