### ISSUE TITLE
Asset Tag conflicts with deleted asset but deleted asset isn't in Deleted section

### ISSUE THREAD

**Issue by drahamim** [snipe/snipe-it#929]
Sorry for the title description. I hope it makes sense. 
Basically 
Create asset with tag 83. Delete asset as it was a mistake. 
Attempt to create new different asset with tag 83. Received error Asset tag already in use. 
Go to deleted assets but can't see asset with tag 83. 

Also wish there was a way to purge an asset after soft delete.

**Comment by ESWBitto** [comment]
I had this similar issue with the licenses. I assigned a license to a user and then deleted the user. I wasn't able to delete the license because it was still checked out by user that was deleted.

In both cases you have to go into the database and manually delete the entry. sqlyog is your friend. :)

**Comment by snipe** [comment]
You should never delete records directly from the database, as it can cause huge problems down the line. Instead, set the `deleted_at` field to null for the record you would like to restore.

**Comment by drahamim** [comment]
Never mind about not seeing it in the deleted items I was searching for a tag with 84 and it persisted across all views. (which confuses me on a separate note) Once I cleared the search field it shows all deleted items. I think what I will do as a work around is just restore the asset and change all other fields except asset tag

**Comment by drahamim** [comment]
I will close this as partly this was due to a user error.

**Comment by snipe** [comment]
Yeah, restoring an asset is the best way to handle this.

<img width="405" alt="screen shot 2015-07-17 at 3 52 44 pm" src="https://cloud.githubusercontent.com/assets/197404/8758698/e9643ce4-2c9b-11e5-9d44-4070e1209f9e.png">

**Comment by drahamim** [comment]
Another work around for future people seeing this is to Change asset tag numbers to something useless before deleting (or restore, change, then delete again) And this fixes the conflict issues. :D
