### ISSUE TITLE
Bug: new license

### ISSUE THREAD

**Issue by aalaily** [snipe/snipe-it#930]
When you create a new license and uncheck the Reassignable checkbox, the license is created as reassignable.

Steps to reproduce problem:
1. Create a license and uncheck "Reassignable"
2. Save
3. After saving the list of licenses is displayed.  Find the item that you've just added and click on it
4. Scroll down the page to "more info" and you will see: **Reassignable: Yes**

This problem only occurs on newly created items.  If you edit an item, the reassignment functionality works flawlessly.

I am using the 2.0 branch.

**Comment by madd15** [comment]
I have submitted a PR that will fix this issue
