### ISSUE TITLE
Remove Public from URL

### ISSUE THREAD

**Issue by jesulo** [snipe/snipe-it#9308]
Hi, can please help me for Remove Public from URL? I m try edith .htaccess, 

RewriteEngine On
RewriteCond %{REQUEST_URI} !^/public/
RewriteRule ^(.*)$ /public/$1 [L,QSA]

my root folder is a sub folder

error
Not Found
The requested URL was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

regards

**Comment by snipe** [comment]
Sounds like your DocumentRoot might not be set correctly. You’ll want that set to be the public directory, so that you don’t need to mess with the htaccess.

**Comment by jesulo** [comment]
Hi! thanks for reply.

I use cpanel and I have several projects in subfolders inside public_html, most of them are laravel and you don't need to put / public / to access those applications.  Do you have any suggestion?

**Comment by jesulo** [comment]
Solved.

just Add file index.php

<?php

/**
 * Laravel - A PHP Framework For Web Artisans
 *
 * @package  Laravel
 * @author   Taylor Otwell <taylorotwell@gmail.com>
 */

$uri = urldecode(
    parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH)
);

// This file allows us to emulate Apache's "mod_rewrite" functionality from the
// built-in PHP web server. This provides a convenient way to test a Laravel
// application without having installed a "real" web server software here.
if ($uri !== '/' && file_exists(__DIR__.'/public'.$uri)) {
    return false;
}

require_once __DIR__.'/public/index.php';



--
Then modify .htaccess file and add

    RewriteEngine On

    # Handle Authorization Header
    RewriteCond %{HTTP:Authorization} .
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]

    # Handle Front Controller...
    RewriteCond %{REQUEST_URI} !(\.css|\.js|\.png|\.jpg|\.jpeg|\.gif|robots\.txt|\.ico|\.woff|\.woff2|\.svg|\.ttf)$ [NC]
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]

    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_URI} !^/public/
    RewriteRule ^(css|assets|landing|storage|installer|js)/(.*)$ public/$1/$2 [L,NC]


but I m not sure what make this conditions

**Comment by snipe** [comment]
This is, overall, not a great idea. Setting the path correctly in the Apache settings is always going to be a better way to handle this, since adding new files that exist outside of the repo can cause issues upgrading later on.
