### ISSUE TITLE
Max Model Image Size

### ISSUE THREAD

**Issue by joeykhan** [snipe/snipe-it#934]
Seems that using images above a certain resolution (trying with 2500x2500) cause the model creation process to hang after clicking create/save

**Comment by snipe** [comment]
Not entirely sure that's a bug. Your PHP is probably exhausting memory. Can you just use a smaller image, or allocate more memory to PHP?

**Comment by joeykhan** [comment]
![screen shot 2015-07-20 at 4 03 25 pm](https://cloud.githubusercontent.com/assets/13342559/8785900/fd863ca4-2ef8-11e5-8097-a4c066606a86.png)

here's what GoDaddy shows for PHP settings. I should call and ask for something to be changed? Perhaps will incorporate with the email call..

**Comment by snipe** [comment]
You'd have to tell me what the server logs say, but my guess is that it's running out of memory. GoDaddy probably won't let you increase `memory_limit` past 64M, which it's currently set at, since you're on a shared host though. :(
