### ISSUE TITLE
Homepage typo - Custom Reports

### ISSUE THREAD

**Issue by Resseguie** [snipe/snipe-it#935]
There's a small typo in the Custom Reports scrolling header on the main website. I didn't see where to offer a PR for the site itself, so thought I'd put it here.

https://www.dropbox.com/s/0urocv61b4iky9j/Screenshot%202015-07-20%2021.36.19.png?dl=0

**Comment by snipe** [comment]
Whoops!

![tumblr_nq5j891ikh1s373hwo1_400](https://cloud.githubusercontent.com/assets/197404/8793182/f31aac9e-2f27-11e5-8b58-7483fcfd18fa.gif)

 Fixed, thanks!
