### ISSUE TITLE
Presenter datatable

### ISSUE THREAD

**Issue by jesulo** [snipe/snipe-it#9351]
Hi, is there a Presenter for datatable layaut tutorial? because I am trying to create a json but it does not recognize me some data for the columns.

Regards

**Comment by jesulo** [comment]
is just taking first items from json not sub item of array.  other example asset sub item name it can find by file-data asset_name how is that possible? regards

**Comment by snipe** [comment]
I don't really understand what you're trying to do. The presenters don't have anything to do with JSON output, the transformers do.

**Comment by jesulo** [comment]
I just didn't understand how bootstrap table creation worked.  already solved. Thanks

**Comment by snipe** [comment]
Glad to hear you're all sorted! In the future, if you've resolved your issue, please try to remember to close your ticket - it helps us out a lot. (We have to manage a lot of tickets.)

![tenant-tyvm](https://user-images.githubusercontent.com/197404/35019316-1bec03bc-fadb-11e7-92d3-0694b211e921.gif)
