### ISSUE TITLE
User asset history mistakes software log entries for hardware

### ISSUE THREAD

**Issue by bskertchly** [snipe/snipe-it#937]
On a user page, their asset history is displayed. The grid seems to think that every entry in the asset_logs table is hardware-related (essentially ignoring the asset_type column). The SQL it generates must be something along these lines:

    SELECT *
    FROM asset_logs l
    INNER JOIN assets a ON l.asset_id = a.id
    INNER JOIN users u ON l.checkedout_to = u.id
    WHERE l.checkedout_to = AUserID;

If there is a license and an an asset with the same ID, the query will interpret a software entry to be for the piece of hardware that is completely unrelated. Thus, we could have servers show up in users' histories :).

I think the query should look something more like this:

    SELECT *
    FROM asset_logs l
    LEFT JOIN assets a ON l.asset_id = a.id AND l.asset_type = 'hardware'
    LEFT JOIN licenses lc ON l.asset_id = lc.id AND l.asset_type = 'software'
    INNER JOIN users u ON l.checkedout_to = u.id
    WHERE l.checkedout_to = AUserID;

or maybe exclude the software ones, if that's easier:

    SELECT *
    FROM asset_logs l
    INNER JOIN assets a ON l.asset_id = a.id
    INNER JOIN users u ON l.checkedout_to = u.id
    WHERE l.checkedout_to = AUserID AND l.asset_type = 'hardware';

**Comment by bskertchly** [comment]
I'm not familiar with the ORM that snipe-it uses (or much PHP, for that matter), but looking at the code for ActionLog, I think the fix would be to replace:

    public function assetlog()
    {
        return $this->belongsTo('Asset','asset_id')->withTrashed();
    }
    ...
    public function licenselog()
    {
        return $this->belongsTo('License','asset_id')->withTrashed();
    }

with

    public function assetlog()
    {
        return $this->belongsTo('Asset','asset_id')->where('asset_type','=','hardware')->withTrashed();
    }
    ...
    public function licenselog()
    {
        return $this->belongsTo('License','asset_id')->where('asset_type','=','software')->withTrashed();
    }

**Comment by snipe** [comment]
How about you start with telling me what version of Snipe-IT you're using, and where you're seeing the bug?

**Comment by snipe** [comment]
Is this only on the user page?

**Comment by bskertchly** [comment]
Sorry, I meant to post my version details, but forgot.

v1.2.7 running on Ubuntu.

I've only noticed it in the user page. I'm checking other pages to see if it happens elsewhere.

**Comment by bskertchly** [comment]
I could only get it to happen on the user page.

**Comment by snipe** [comment]
This is in the log at the bottom of the user detail view page, correct?

**Comment by snipe** [comment]
This is fixed in 2.0
