### ISSUE TITLE
Server Error: 500 (Internal Server Error)

### ISSUE THREAD

**Issue by suneyo21** [snipe/snipe-it#945]
I was able to install the script without any issues, but i am having this error "Server Error: 500 (Internal Server Error)" upon accessing it, and i cant see any logs on apache.

**Comment by madd15** [comment]
I take it you fixed your issue?

**Comment by suneyo21** [comment]
Actually no i still have this issue, but is use the script install on snipeit-ansible.

Would you know the resolution to this one?  Thanks.

**Comment by snipe** [comment]
You'd have to open a ticket for the ansible repo. It's not officially supported by us.

**Comment by snipe** [comment]
(Also, we'd need to see app logs, per http://docs.snipeitapp.com/getting-help.html )

**Comment by suneyo21** [comment]
Thanks snipe.  I navigate to that file (/opt/snipe-it/app/config/app.php) and cannot see any debug option, only timezone, locale, cipher, etc.

**Comment by snipe** [comment]
Tell us what's in your app logs.

**Comment by suneyo21** [comment]
root@inventory:/opt/snipe-it/app/storage/logs# tail -f log-apache2handler-2015-07-26.txt
#10 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 /opt/snipe-it/vendor/barryvdh/laravel-debugbar/src/Middleware/Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#13 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#14 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#15 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#16 /opt/snipe-it/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#17 /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#18 /opt/snipe-it/public/index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []

**Comment by suneyo21** [comment]
Along with that error it is being redirected to /auth/signin

mod_rewrite is enabled and .htaccess is present on public folder

**Comment by snipe** [comment]
If it's redirecting to /auth/signin, that's a good sign, as it means it's trying to let you login. The logs don't seem to offer a lot of help in this case though, so not sure what the issue might be. Is that the entire contents of your log file?

**Comment by suneyo21** [comment]
I think i saw some error.

Full logs here: http://www.filedropper.com/log-apache2handler-2015-07-27

Sorry cannot upload txt file.

**Comment by snipe** [comment]
The very first line.

[2015-07-27 00:31:18] production.ERROR: exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'snipeit.settings' doesn't exist' in /opt/snipe-it/vendor/laravel/framework/src/Illuminate/Database/Connection.php:299

You either don't have a database set up, or the one it's looking for doesn't match what's in your config.

**Comment by snipe** [comment]
(Or the migrations never ran - did you run `php artisan app:install`? That's what sets up the tables.)

**Comment by suneyo21** [comment]
Ok thanks for that snipe, the db was empty during the ansible repo install.

I did a fresh install using the snipeit git repo and followed the instructions which all went well including seeding of database.

All working good now. Thanks for your help i really appreciate it.

**Comment by snipe** [comment]
No prob - glad you got it sorted
