### ISSUE TITLE
Model Name and Number overlap

### ISSUE THREAD

**Issue by Freaksed** [snipe/snipe-it#948]
It would be great if you could use the same Model Name for multiple Asset Numbers.
This would be like having different generation XBox 360s. e.g. XBox 360/Gen1 and XBox 360/Gen2.
This would be helpful for items where only the name is the same but the model number has changed over time.

**Comment by dscherertfm** [comment]
Or like the Dell Optiplex 390/380/790/etc. Definitely add my vote here.

**Comment by snipe** [comment]
Fixed in 2.0
