### ISSUE TITLE
Personal API Keys Blank

### ISSUE THREAD

**Issue by SeanGuoXuan** [snipe/snipe-it#9500]
#### Please confirm you have done the following before posting your bug report:

- [yes ] I have enabled debug mode 
- [ yes] I have read [checked the Common Issues page](https://snipe-it.readme.io/docs/common-issues)

**Describe the bug**
"Personal API Keys" page is blank.

**To Reproduce**
1. login as admin 
2. Click on 'Manage API Keys'
3. See Empty page with title "Personal API Keys".

**Expected behavior**
A page with "Personal Access Token" and also a button with name "Create new token".
Admin can not generate personal access token.

**Screenshots**
![Screenshot from 2021-04-28 17-53-55](https://user-images.githubusercontent.com/22338019/116385092-0c75ea80-a84b-11eb-98d4-1f027874c9f9.png)

**Server (please complete the following information):**
 - Snipe-IT Version:  Version v5.1.3 - build 5862 (master
 - OS: Ubuntu
 - Web Server: Apache
 - PHP Version: 7.4.16

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser chrome
 - Version: 90.0.4430.85 (Official Build) (64-bit)

**Error Messages**
No error message.

**Additional context**
- a fresh install, manual installation.

Steps [Testing in Postman](https://snipe-it.readme.io/reference#testing-in-postman) is not working neither:
1. generate api key by command: php artisan passport:client --personal
![Screenshot from 2021-04-28 18-12-12](https://user-images.githubusercontent.com/22338019/116387336-4c3dd180-a84d-11eb-93a2-c1e8fd8cf5e4.png)
2. open postman send request with token
![Screenshot from 2021-04-28 18-15-38](https://user-images.githubusercontent.com/22338019/116387806-c2423880-a84d-11eb-9ce8-23b14e2f2166.png)

3. get response message "This action is unauthorized."

**Comment by snipe** [comment]
Any browser console issues, or...?
