### ISSUE TITLE
Database move results in renamed table contents

### ISSUE THREAD

**Issue by JohnnyPicnic** [snipe/snipe-it#9510]
Moving a database from  Version v5.0.10 - build 5680 (master) to   Version v5.1.5 - build 6029 (master).
When viewing the tables in mysql the imported database has ver1 added to the contents name.
#mysql -u snipeadmin -p snipeitdb < ~/Downloads/mysql-snipeit.sql
For example:
 Tables_in_snipeitdb                |
+------------------------------------+
| accessories                        |
| accessories_users                  |
| action_logs                        |
| asset_logs                         |
| asset_maintenances

#imported database
| ver1_accessories                   |
| ver1_accessories_users             |
| ver1_action_logs                   |
| ver1_asset_logs                    |
| ver1_asset_maintenances            |

**Comment by snipe** [comment]
There is nothing we do to prefix db tables.

**Comment by JohnnyPicnic** [comment]
I figured it's not a snipe-it issue. I did a backup, copied over the database file and ran the import command. Guess I will rename the tables manually and re-import.

**Comment by snipe** [comment]
It seems weird that you should have to tho tbh. Is it possible your DB GUI client is grouping them based on prefix so you don’t actually *see* the prefixes even tho they’re there? Also you could just use the DB_PREFIX variable in the .env

**Comment by JohnnyPicnic** [comment]
Just tried an import again from the mysql-snipeit.sql file in the backup.zip and got the same results.
Every column has "ver1_" added to it. 
I'm running Server version: 10.3.27-MariaDB-0+deb10u1 Raspbian 10

**Comment by snipe** [comment]
Did you ever get this sorted? It's still so bizarre. I don't have any idea what would have caused that behavior. 

I'll close this for now I guess? Ping me back here if you still need help tho.
