### ISSUE TITLE
Class Controllers\Account\AuthController does not exist

### ISSUE THREAD

**Issue by mark-rbl** [snipe/snipe-it#952]
Hi after installing and trying to sign out of the default account. I get this error.

ReflectionException thrown with message "Class Controllers\Account\AuthController does not exist"

Stacktrace:
#19 ReflectionException in C:\inetpub\wwwroot\asmara\vendor\laravel\framework\src\Illuminate\Container\Container.php:504
#18 ReflectionClass:__construct in C:\inetpub\wwwroot\asmara\vendor\laravel\framework\src\Illuminate\Container\Container.php:504
#17 Illuminate\Container\Container:build in C:\inetpub\wwwroot\asmara\vendor\laravel\framework\src\Illuminate\Container\Container.php:428
#16 Illuminate\Container\Container:make in C:\inetpub\wwwroot\asmara\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:462
#15 Illuminate\Foundation\Application:make in C:\inetpub\wwwroot\asmara\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php:78
#14 Illuminate\Routing\ControllerDispatcher:makeController in C:\inetpub\wwwroot\asmara\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php:51
#13 Illuminate\Routing\ControllerDispatcher:dispatch in C:\inetpub\wwwroot\asmara\vendor\laravel\framework\src\Illuminate\Routing\Router.php:967
#12 Illuminate\Routing\Router:Illuminate\Routing\{closure} in <#unknown>:0
#11 call_user_func_array in C:\inetpub\wwwroot\asmara\vendor\laravel\framework\src\Illuminate\Routing\Route.php:109
#10 Illuminate\Routing\Route:run in C:\inetpub\wwwroot\asmara\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1033
#9 Illuminate\Routing\Router:dispatchToRoute in C:\inetpub\wwwroot\asmara\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1001
#8 Illuminate\Routing\Router:dispatch in C:\inetpub\wwwroot\asmara\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:775
#7 Illuminate\Foundation\Application:dispatch in C:\inetpub\wwwroot\asmara\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:745
#6 Illuminate\Foundation\Application:handle in C:\inetpub\wwwroot\asmara\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php:34
#5 Barryvdh\Debugbar\Middleware\Stack:handle in C:\inetpub\wwwroot\asmara\vendor\laravel\framework\src\Illuminate\Session\Middleware.php:72
#4 Illuminate\Session\Middleware:handle in C:\inetpub\wwwroot\asmara\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php:47
#3 Illuminate\Cookie\Queue:handle in C:\inetpub\wwwroot\asmara\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php:51
#2 Illuminate\Cookie\Guard:handle in C:\inetpub\wwwroot\asmara\vendor\stack\builder\src\Stack\StackedHttpKernel.php:23
#1 Stack\StackedHttpKernel:handle in C:\inetpub\wwwroot\asmara\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:641
#0 Illuminate\Foundation\Application:run in C:\inetpub\wwwroot\asmara\public\index.php:49

Could you please assist. Installed on Win 2012 R2 & IIS8

**Comment by snipe** [comment]
What version are you using?

**Comment by snipe** [comment]
It looks like you grabbed pre-2.0? That branch is not stable yet. You should stick to the master branch if you want something higher than 1.2.8.
