### ISSUE TITLE
When a User Sets their Gravatar Email, Avatar Does Not Change

### ISSUE THREAD

**Issue by dscherertfm** [snipe/snipe-it#953]
I set my gravatar E-mail in my profile, and the image appeared below the box as expected, however elsewhere the avatar does not update/display. Firefox 36, Windows 8.1 Pro.

**Comment by snipe** [comment]
Where else is it not updating?

**Comment by dscherertfm** [comment]
I actually haven't seen it anywhere really except under the box in the edit profile, I wasn't exactly paying attention aside from looking at my profile page and not seeing it. If I find other places it should be and isn't I'll make a note of it.

Side note: can you recommend a good place to get up to speed on Laravel? I'd really like to try and contribute a bit, I love snipe so far but there's a lot more I'd like to be able to do to taylor it more for the way my company manages assets, and I suspect much of it is likely to be beneficial for others or maybe even already on the map.

On 24 Jul 2015 7:39 pm, snipe <notifications@github.com> wrote:

Where else is it not updating?

-
Reply to this email directly or view it on GitHub<https://github.com/snipe/snipe-it/issues/953#issuecomment-124767199>.

CONFIDENTIALITY NOTICE: This electronic message contains information which may be legally confidential and/or privileged and does not in any case represent a firm TARGET FREIGHT MANAGEMENT bid or offer relating thereto which binds the sender without an additional express written confirmation to that effect. The information is intended solely for the individual or entity named above and access by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, distribution, or use of the contents of this information is prohibited and may be unlawful. If you have received this electronic transmission in error, please reply immediately to the sender that you have received the message in error, and delete it. Thank you.

**Comment by snipe** [comment]
I would strongly recommend getting a subscription to Laracasts. It's worth the money. http://laracasts.com/

Bear in mind that we're using Laravel 4.2, which is a slightly older version. The transition from 4.2 to 5.0 is a real beast, which is why we haven't tackled that yet.

**Comment by snipe** [comment]
Fixed in v3
