### ISSUE TITLE
Borders on labels

### ISSUE THREAD

**Issue by Freaksed** [snipe/snipe-it#954]
It would be nice to generate a thin border around the labels to make it easier to cut them out uniformly

**Comment by snipe** [comment]
Hi @Freaksed - I think that would have to be an optional feature, as many of our users use pre-cut labels (like Avery, etc), so the borders might be problematic for them.

**Comment by Freaksed** [comment]
Ah, yeah so a check box maybe? I wasn't sure if we could use label sheets or what size would be needed to fit the spacing it generates. Maybe include a bit of text that says what kind of label sheets (size, spacing, etc...) will print without alignment issues?

**Comment by snipe** [comment]
I believe we did most of out testing with Avery 5160 in portrait mode.

**Comment by snipe** [comment]
It's not your fault - our user's manual is still very much a work in progress, so some of this stuff isn't documented that well. 

I've added some basic documentation for you here:
http://docs.snipeitapp.com/manual/labels.html

**Comment by Freaksed** [comment]
great thanks, btw i was looking up the 5160, it looks like it is a 3 across sheet?

**Comment by snipe** [comment]
I think it's a two-across label set, actually. It should automatically create padding so that the page breaks cleanly and you don't run into issues with labels printing halfway between sheets, etc.

<img width="877" alt="screen shot 2015-07-24 at 1 33 01 pm" src="https://cloud.githubusercontent.com/assets/197404/8884085/b291048c-3208-11e5-81d9-0b2e2554089f.png">

**Comment by Freaksed** [comment]
I mean the 5160 sheets are 3 across, was it maybe the 5161? Those are 2 across sheets with 1"x4" labels.

**Comment by snipe** [comment]
I could have sworn it was 5160, but it wouldn't be the first time I was wrong. The current layout is 2-across, 9-down in portrait orientation.

**Comment by Freaksed** [comment]
hmmm, interesting, i see 3 possible sheets on the avery site 5160, 5161, and 5162 but none of them are 18 per sheet. 5160 is 3 across 30 per sheet. 5161 is 2 across 20 per sheet. 5162 is 2 across 14 per sheet. links below :)
http://www.avery.com/avery/en_us/Products/Labels/Addressing-Labels/Easy-Peel-White-Address-Labels_05160.htm?N=4294967290&Ns=Rank&refchannel=b3e659baa4c2a110VgnVCM1000002118140aRCRD
http://www.avery.com/avery/en_us/Products/Labels/Addressing-Labels/Easy-Peel-White-Mailing-Labels_05161.htm?N=&Ns=Rank&refchannel=b3e659baa4c2a110VgnVCM1000002118140aRCRD
http://www.avery.com/avery/en_us/Products/Labels/Addressing-Labels/Easy-Peel-White-Address-Labels_05162.htm?N=&Ns=Rank&refchannel=b3e659baa4c2a110VgnVCM1000002118140aRCRD

**Comment by snipe** [comment]
I'll take a look and see what might be happening. I know we definitely had a common label sheet in mind, but something may have gotten donked up.

**Comment by snipe** [comment]
Hi @Freaksed - sorry for the confusion. Avery 5027 or 8425 will be your best bet. I've updated the documentation. You can see the issue here: https://github.com/snipe/snipe-it/issues/978

And updated docs here:
http://docs.snipeitapp.com/manual/labels.html
