### ISSUE TITLE
Inventory Management (Feature Request)

### ISSUE THREAD

**Issue by dscherertfm** [snipe/snipe-it#958]
We have something like 5 printers in the office, and when it runs out usually whoever notices, fills it up. However, nobody ever seems to realize that when you put the last toner into the printer to tell someone, and even when they do remember to tell someone, it often gets left off the Quill order or not called into Konica right away. The ability to keep track of toner/other consumables as well as who changed what last would be nice. Maybe this has such limited use cases that it's impractical and we should just do a better job of being organized (also, nobody would update this for something like paper reams, for example).

**Comment by snipe** [comment]
Consumables is in 2.0.

**Comment by dscherertfm** [comment]
Sweet. :)
