### ISSUE TITLE
Asset Models are a bit Weird

### ISSUE THREAD

**Issue by dscherertfm** [snipe/snipe-it#962]
When you create an Asset Model, the Name is unique. This is weird because when I think of "Name" I'm thinking the Family name for that model, EG the Toshiba Satelite, and the model # like L455. Having Satelite multiple times in the name with each model sepparate in the Model # field would allow the dropdown to display in the way it appears to be intended to display. Currently I just don't use the model # field because I'm forced to put the whole string in the Model Name field.

**Comment by snipe** [comment]
Duplicate of #948
