### ISSUE TITLE
Auto increment tag number based on leading tag name

### ISSUE THREAD

**Issue by Freaksed** [snipe/snipe-it#964]
It would be nice if you could make the auto tag numbering account for an existing tag name "structure".
e.g. if you start naming assets "cam 001" "cam 002" then if you clone the asset it made the next one "cam 003"
##

**Comment by dscherertfm** [comment]
This would be cool, I propose you could assign the tag prefix to the asset category, and keep the increment stored on that category. We name our desktops TFMDESKTOP00n and laptops TFMLAPTOP00n and Printers TFMPR00n for example, this would be incredibly helpful for asset management as I usually end up consulting AD users/computers as well as a sheet of pre-printed barcode labels for new asset tags when I'm provisioning new hardware.

**Comment by othyn** [comment]
+1

Asset tag incrementing via Category would be fantastic! Although I can imagine it would take quite a lot of refactoring to achieve...

**Comment by therealjoshuad** [comment]
Would love to see this as well
