### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by thien154** [snipe/snipe-it#970]
Version pre 2.0 error with create location when no location in the database. can not delete location too

**Comment by snipe** [comment]
2.0 is not stable and shouldn't be installed by non-developers. That's why it's marked as a pre-release.

Can you describe your issue in more detail though?

**Comment by thien154** [comment]
when you try delete a location error message like this. thanks
[image: Inline image 1]

**Comment by snipe** [comment]
You can't send images to Github via email, have to upload in the web interface

**Comment by thien154** [comment]
when deleting location. this error happen. with v2.0
![image](https://cloud.githubusercontent.com/assets/10879686/8947677/f62b4f50-35c7-11e5-90cc-dbb55d34c5b0.png)

**Comment by snipe** [comment]
Please turn on debugging or tell us what's in the access logs, per the Getting Help page:
http://docs.snipeitapp.com/getting-help.html

**Comment by thien154** [comment]
Thanks this is error detail:
Object of class Illuminate\Database\Eloquent\Relations\HasMany could not be converted to int

![image](https://cloud.githubusercontent.com/assets/10879686/8947725/92c8ed86-35c8-11e5-880c-ed373ea9427d.png)
