### ISSUE TITLE
xls exports csv

### ISSUE THREAD

**Issue by Freaksed** [snipe/snipe-it#976]
The XLS export saves a CSV

**Comment by snipe** [comment]
The CSV can be opened in Excel though, right?

I think that may be an issue with the Datatables plugin (which is how that XLS/CSV/etc). We're currently looking into switching from Datatables to a different table library that better supports responsive design. (Once we gave users the ability to show/hide columns using the colVis Datatables library, it wrecked the responsiveness of the tables), so this may be a non-issue in 2.1.

**Comment by Freaksed** [comment]
yes excel can open cvs, just thought i would send up the bug since i noticed it. it is probably quite a low priority for most users.

**Comment by snipe** [comment]
We're actually going to be switching from DataTables to a different table display method (one that will handle large numbers of items more gracefully and will bring back the responsiveness in the tables), so I'm going to close this for now. This issue should be resolved once we switch over.
