### ISSUE TITLE
Minor documentation error for supported printed labels

### ISSUE THREAD

**Issue by JoeFaux** [snipe/snipe-it#978]
Page found at http://docs.snipeitapp.com/manual/labels.html states
"This will generate labels that should fit Avery 5160 in portrait mode, or a similarly-sized two-across, nine-down (in portrait mode) label sheet"
The Avery 5160 is a 10 down, three wide, 30 label sheet which will not print correctly.
The Avery 5027 is nine down, two wide,, 18 label sheet.  This sheet will print correctly.  The Avery 5026 will work to print, but it has a color band on the left that makes the QR code difficult to read.  An 8425 should print also, but was not tested and will probably peel up.

**Comment by snipe** [comment]
Thanks for the heads up - it's corrected now!

![easy-peasy](https://cloud.githubusercontent.com/assets/197404/8944354/143e5520-3535-11e5-9c79-fea973e07550.gif)
