### ISSUE TITLE
Feature Request: Searchable Seats within a license

### ISSUE THREAD

**Issue by ESWBitto** [snipe/snipe-it#979]
Would like the functionality to search seats for an asset. Would make life easier instead of scrolling through hundreds of seats to find one.
##

**Comment by snipe** [comment]
If anyone is interested in working on this, you know that we're looking into switching from Datatables to another table library that has more responsive support. Should maybe discuss with us before starting anything.

**Comment by madd15** [comment]
I think this should be done as part of the table switch.

**Comment by snipe** [comment]
@ESWBitto Can you describe your use-case in more detail here?
