### ISSUE TITLE
Location Create Error.

### ISSUE THREAD

**Issue by thien154** [snipe/snipe-it#985]
V 2.0 error with create new location as detail.
![image](https://cloud.githubusercontent.com/assets/10879686/8948411/26f64460-35d1-11e5-956c-be332154aca7.png)

**Comment by snipe** [comment]
I'm not able to reproduce this one - what are the characteristics of the location you're trying to delete? Does it have any children or parents? Any assets, etc? Is this on the save, or on the create location form?
