### ISSUE TITLE
Logo uploaded but does not show

### ISSUE THREAD

**Issue by koto137** [snipe/snipe-it#993]
Dear Snipe,

Today I've tried to add a Logo to your beautiful app, I chose file, clicked save on editing settings, I was first expecting to say something like upload went OK or something. So checked upload folder and logo.png was actually there, so upload went fine. Problem was that logo didn't show up, only "broken image" icon. So I started investigating and found out that the image getting error 404.

![image](https://cloud.githubusercontent.com/assets/11044793/8978334/79596eb4-36a1-11e5-90b4-37d2fc7cbafa.png)

As you can see in the bottom of picture, the path to the logo was **IP/uploads/logo.png**. Meanwhile my snipeit home address is **IP/snipeit/**.

So I found out to fix to this is either add to the source code a web root of snipeit or to remove one slash as below:

***ORIGINAL:***
```
<img src="/uploads/{{{ Setting::getSettings()->logo }}}">
```

***FIX:***
```
<img src="snipeit/uploads/{{{ Setting::getSettings()->logo }}}">
<img src="uploads/{{{ Setting::getSettings()->logo }}}">
```

Obviously the first solution is wrong, and the second should work all time. I am no web developer so I dont know other dependencies on this link path but this is what worked for me.

Thanks for great app anyways, good job.

**Comment by madd15** [comment]
I can see the issue and will supply a fix shortly

**Comment by madd15** [comment]
@snipe #994

**Comment by koto137** [comment]
Also when being in ***SNIPE-ROOT/admin/*** (manufactureres/people etc) the logo is a problem because it look for upload directory under admin subdir:

![image](https://cloud.githubusercontent.com/assets/11044793/9001849/ee8884d4-375c-11e5-9607-2d594d7898d8.png)

**Comment by madd15** [comment]
I think the error you experiencing now is due to the change you made, if you take a look at #994 that should fix your logo.

**Comment by koto137** [comment]
The logo wouldn't work either with my fix or without it hehe :smiling_imp: 

Yep your fix working like a charm, thanks a lot !
