### ISSUE TITLE
SSL connection error

### ISSUE THREAD

**Issue by Elvbray** [snipe/snipe-it#997]
Hello! 
im having ERR_SSL_PROTOCOL_ERROR

im using window 7, IIS7, mysql

thank you in advance

**Comment by snipe** [comment]
Hey, so, that info isn't useful without context.

In what stage of install are you? Literally anything more you can give would help.

**Comment by Elvbray** [comment]
im about to run the site i followed all instructions  and successfully done every steps.

**Comment by snipe** [comment]
Do you maybe have an https URL set for a site that does t have ssl? Check app/config/production/app.php

**Comment by brandonvictorblanco** [comment]
Hello Snipe, 
Here's what my app.php have. 

<?php

return array(

    /*
    |--------------------------------------------------------------------------
    | Application Debug Mode
    |--------------------------------------------------------------------------
    |
    | When your application is in debug mode, detailed error messages with
    | stack traces will be shown on every error that occurs within your
    | application. If disabled, a simple generic error page is shown.
    |
    */

    'debug' => false,

    /*
    |--------------------------------------------------------------------------
    | Application URL
    |--------------------------------------------------------------------------
    |
    | This URL is used by the console to properly generate URLs when using
    | the Artisan command line tool. You should set this to the root of
    | your application so that it is used when running Artisan tasks.
    |
    */

    'url' => 'http://production.yourserver.com'

    /*
    |--------------------------------------------------------------------------
    | Encryption Key
    |--------------------------------------------------------------------------
    |
    | This key is used by the Illuminate encrypter service and should be set
    | to a random, 32 character string, otherwise these encrypted strings
    | will not be safe. Please do this before deploying an application!
    |
    | Run a php artisan key:generate --env=staging to create a random one
    */

    'key' => 'p@s$w0Rd01',

);

**Comment by snipe** [comment]
What browser are you using?

**Comment by snipe** [comment]
Also make sure you're not redirecting to SSL in URLRewrite

**Comment by Elvbray** [comment]
Im using chome as my browser, import htaccess on URLrewrite as the instruction says.  Do you need any log file.

**Comment by snipe** [comment]
No, I don't think log files will help here. This is a server/browser/computer configuration issue, not an issue with Snipe-IT.

If you try accessing it in a different browser, do you get the same error?

**Comment by snipe** [comment]
Also, in your `app/config/production/app.php`, please turn `debug` and fill out the URL as outlined in the installation documentation. http://docs.snipeitapp.com/installation/configuration.html#application-settings

**Comment by Elvbray** [comment]
Solve this issue by disabling the 1st import rule in urlrewrite settings on my iis

Thanks

**Comment by snipe** [comment]
Is that different than https://github.com/snipe/snipe-it/issues/997#issuecomment-127812689

**Comment by Elvbray** [comment]
Check URL rule import1  it says https off. But then again disabling the import1 solve my prob. Thanks again snipe!
