### ISSUE TITLE
artisan commands

### ISSUE THREAD

**Issue by cinteck** [snipe/snipe-it#998]
Hi Everyone,

When I try running the commands listed in the installation documentation for Windows / IIS they do not return anything like it is stated they should. 

I run:

php artisan app:install --env=production from inside composer (whichw as started from the snipeit folder) and it brings me back to a blinking cursor. Same with the key generator. 

Does anyone have any idea what might be going on?

Thank you!

**Comment by mdaniels5757** [comment]
Did you run 'php composer.phar install --no-dev --prefer-source`?

**Comment by cinteck** [comment]
I don't recall seeing that in the installation area, maybe I overlooked it! Let me try to do that now.

**Comment by cinteck** [comment]
@mdaniels5757 is it composer.json .phar install?

**Comment by mdaniels5757** [comment]
that, then the command I mentioned

**Comment by snipe** [comment]
When you don't get any response from `php artisan app:install`, it usually means there is a parse error elsewhere in your config file. Check the config files that you edited and look for unclosed quotes or curly quotes.

**Comment by snipe** [comment]
Any update?

**Comment by cinteck** [comment]
Unfortunately not yet, this got put on the back burner at the moment
because we're moving offices in a week. :\

**Comment by cinteck** [comment]
Update on this, I tried everything above and still cannot seem to get the php artisan:install to work properly. I went through all of the files in /app/config/production and /app/config/local and verified the settings, checked for parse errors, open brackets, also verified my database settings and all smtp settings were correct. Also to note, I'm running on a Windows environment with PHP 5.6 and IIS. I followed the guide for this configuration on the setup. Sorry again it took a while to get back to this we moved offices and had quite a bit going on. Thank you for all of your help! :)

**Comment by snipe** [comment]
@cinteck I'm still going to bet there is a parse error somewhere in your config files, possibly your editor used curly apostrophes instead of regular, etc. It's very common, and really hard to spot. What editor did you use to change the config files?

**Comment by cinteck** [comment]
I'm using Notepad++ currently, do you have a better recommendation for and editor when working with SnipeIT files?

**Comment by snipe** [comment]
@cinteck - I'd recommend Atom.io for code editing. If you want to post your config files here (with passwords, etc obfuscated) we can try to help, but if you do a search in all of the config files, I'd bet you're going to find a curly apostrophe (or curly quotes), or you've left quotes off of something that needed quotes.
