### ISSUE TITLE
Bug - SQLSTATE error when checking in/out assets

### ISSUE THREAD

**Issue by kobie-chasehansen** [snipe/snipe-it#999]
Couldn't duplicate on demo, will try to duplicate on ours.

![image](https://cloud.githubusercontent.com/assets/10247644/9014074/08681082-378e-11e5-8ccc-f4ff2a63afd1.png)

**Comment by snipe** [comment]
Looks like you're running strict mode. I'll fix the migration. (This is only in 2.0 anyway)

**Comment by kobie-chasehansen** [comment]
Yepp damn strict mode

**Comment by kobie-chasehansen** [comment]
thanks, i pulled the latest but it still reported no migrations. does this seem right?

**Comment by snipe** [comment]
No, that doesn't seem right. Can you show me what you have in your `migrations` table?

**Comment by kobie-chasehansen** [comment]
"migration"	"batch"
"2012_12_06_225921_migration_cartalyst_sentry_install_users"	"1"
"2012_12_06_225929_migration_cartalyst_sentry_install_groups"	"1"
"2012_12_06_225945_migration_cartalyst_sentry_install_users_groups_pivot"	"1"
"2012_12_06_225988_migration_cartalyst_sentry_install_throttle"	"1"
"2013_03_23_193214_update_users_table"	"2"
"2013_11_13_075318_create_models_table"	"2"
"2013_11_13_075335_create_categories_table"	"2"
"2013_11_13_075347_create_manufacturers_table"	"2"
"2013_11_15_015858_add_user_id_to_categories"	"2"
"2013_11_15_112701_add_user_id_to_manufacturers"	"2"
"2013_11_15_190327_create_assets_table"	"2"
"2013_11_15_190357_create_licenses_table"	"2"
"2013_11_15_201848_add_license_name_to_licenses"	"2"
"2013_11_16_040323_create_depreciations_table"	"2"
"2013_11_16_042851_add_depreciation_id_to_models"	"2"
"2013_11_16_084923_add_user_id_to_models"	"2"
"2013_11_16_103258_create_locations_table"	"2"
"2013_11_16_103336_add_location_id_to_assets"	"2"
"2013_11_16_103407_add_checkedout_to_to_assets"	"2"
"2013_11_16_103425_create_history_table"	"2"
"2013_11_17_054359_drop_licenses_table"	"2"
"2013_11_17_054526_add_physical_to_assets"	"2"
"2013_11_17_055126_create_settings_table"	"2"
"2013_11_17_062634_add_license_to_assets"	"2"
"2013_11_18_134332_add_contacts_to_users"	"2"
"2013_11_18_142847_add_info_to_locations"	"2"
"2013_11_18_152942_remove_location_id_from_asset"	"2"
"2013_11_18_164423_set_nullvalues_for_user"	"2"
"2013_11_19_013337_create_asset_logs_table"	"2"
"2013_11_19_061409_edit_added_on_asset_logs_table"	"2"
"2013_11_19_062250_edit_location_id_asset_logs_table"	"2"
"2013_11_20_055822_add_soft_delete_on_assets"	"2"
"2013_11_20_121404_add_soft_delete_on_locations"	"2"
"2013_11_20_123137_add_soft_delete_on_manufacturers"	"2"
"2013_11_20_123725_add_soft_delete_on_categories"	"2"
"2013_11_20_130248_create_status_labels"	"2"
"2013_11_20_130830_add_status_id_on_assets_table"	"2"
"2013_11_20_131544_add_status_type_on_status_labels"	"2"
"2013_11_20_134103_add_archived_to_assets"	"2"
"2013_11_21_002321_add_uploads_table"	"2"
"2013_11_21_024531_remove_deployable_boolean_from_status_labels"	"2"
"2013_11_22_075308_add_option_label_to_settings_table"	"2"
"2013_11_22_213400_edits_to_settings_table"	"2"
"2013_11_25_013244_create_licenses_table"	"2"
"2013_11_25_031458_create_license_seats_table"	"2"
"2013_11_25_032022_add_type_to_actionlog_table"	"2"
"2013_11_25_033008_delete_bad_licenses_table"	"2"
"2013_11_25_033131_create_new_licenses_table"	"2"
"2013_11_25_033534_add_licensed_to_licenses_table"	"2"
"2013_11_25_101308_add_warrantee_to_assets_table"	"2"
"2013_11_25_104343_alter_warranty_column_on_assets"	"2"
"2013_11_25_150450_drop_parent_from_categories"	"2"
"2013_11_25_151920_add_depreciate_to_assets"	"2"
"2013_11_25_152903_add_depreciate_to_licenses_table"	"2"
"2013_11_26_211820_drop_license_from_assets_table"	"2"
"2013_11_27_062510_add_note_to_asset_logs_table"	"2"
"2013_12_01_113426_add_filename_to_asset_log"	"2"
"2013_12_06_094618_add_nullable_to_licenses_table"	"2"
"2013_12_10_084038_add_eol_on_models_table"	"2"
"2013_12_12_055218_add_manager_to_users_table"	"2"
"2014_01_28_031200_add_qr_code_to_settings_table"	"2"
"2014_02_13_183016_add_qr_text_to_settings_table"	"2"
"2014_05_24_093839_alter_default_license_depreciation_id"	"2"
"2014_05_27_231658_alter_default_values_licenses"	"2"
"2014_06_19_191508_add_asset_name_to_settings"	"2"
"2014_06_20_004847_make_asset_log_checkedout_to_nullable"	"2"
"2014_06_20_005050_make_asset_log_purchasedate_to_nullable"	"2"
"2014_06_24_003011_add_suppliers"	"2"
"2014_06_24_010742_add_supplier_id_to_asset"	"2"
"2014_06_24_012839_add_zip_to_supplier"	"2"
"2014_06_24_033908_add_url_to_supplier"	"2"
"2014_07_08_054116_add_employee_id_to_users"	"2"
"2014_07_09_134316_add_requestable_to_assets"	"2"
"2014_07_17_085822_add_asset_to_software"	"2"
"2014_07_17_161625_make_asset_id_in_logs_nullable"	"2"
"2014_08_12_053504_alpha_0_4_2_release"	"2"
"2014_08_17_083523_make_location_id_nullable"	"2"
"2014_10_16_200626_add_rtd_location_to_assets"	"2"
"2014_10_24_000417_alter_supplier_state_to_32"	"2"
"2014_10_24_015641_add_display_checkout_date"	"2"
"2014_10_28_222654_add_avatar_field_to_users_table"	"2"
"2014_10_29_045924_add_image_field_to_models_table"	"2"
"2014_11_01_214955_add_eol_display_to_settings"	"2"
"2014_11_04_231416_update_group_field_for_reporting"	"2"
"2014_11_05_212408_add_fields_to_licenses"	"2"
"2014_11_07_021042_add_image_to_supplier"	"3"
"2014_11_20_203007_add_username_to_user"	"3"
"2014_11_20_223947_add_auto_to_settings"	"3"
"2014_11_20_224421_add_prefix_to_settings"	"3"
"2014_11_21_104401_change_licence_type"	"3"
"2014_12_09_082500_add_fields_maintained_term_to_licenses"	"4"
"2015_02_04_155757_increase_user_field_lengths"	"5"
"2015_02_07_013537_add_soft_deleted_to_log"	"6"
"2015_02_10_040958_fix_bad_assigned_to_ids"	"7"
"2015_02_10_053310_migrate_data_to_new_statuses"	"7"
"2015_02_11_044104_migrate_make_license_assigned_null"	"8"
"2015_02_11_104406_migrate_create_requests_table"	"8"
"2015_02_12_001312_add_mac_address_to_asset"	"9"
"2015_02_12_024100_change_license_notes_type"	"10"
"2015_02_17_231020_add_localonly_to_settings"	"11"
"2015_02_19_222322_add_logo_and_colors_to_settings"	"12"
"2015_02_24_072043_add_alerts_to_settings"	"13"
"2015_02_25_022931_add_eula_fields"	"14"
"2015_02_25_204513_add_accessories_table"	"15"
"2015_02_26_091228_add_accessories_user_table"	"15"
"2015_02_26_115128_add_deleted_at_models"	"15"
"2015_02_26_233005_add_category_type"	"16"
"2015_03_01_231912_update_accepted_at_to_acceptance_id"	"17"
"2015_03_05_011929_add_qr_type_to_settings"	"17"
"2015_03_18_055327_add_note_to_user"	"18"
"2015_04_29_234704_add_slack_to_settings"	"19"
"2015_05_04_085151_add_parent_id_to_locations_table"	"20"
"2015_05_22_124421_add_reassignable_to_licenses"	"21"
"2015_06_10_003314_fix_default_for_user_notes"	"21"
"2015_06_10_003554_create_consumables"	"21"
"2015_06_15_183253_move_email_to_username"	"21"
"2015_06_23_070346_make_email_nullable"	"21"
"2015_07_09_014359_add_currency_to_settings_and_locations"	"22"
"2015_06_26_213716_create_asset_maintenances_table"	"23"
"2015_07_21_122022_add_expected_checkin_date_to_asset_logs"	"23"
"2015_07_24_093845_add_checkin_email_to_category_table"	"23"
"2015_07_25_055415_remove_email_unique_constraint"	"23"
"2015_07_29_230054_add_thread_id_to_asset_logs_table"	"24"

**Comment by snipe** [comment]
Can you delete that last migration (24) and re-run migrations?

**Comment by kobie-chasehansen** [comment]
[Illuminate\Database\QueryException]
  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'thread_
  id' (SQL: alter table `asset_logs` add `thread_id` int unsigned null)






  [PDOException]
  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'thread_
  id'



migrate [--bench[="..."]] [--database[="..."]] [--force] [--path[="..."]] [--pac
kage[="..."]] [--pretend] [--seed]

**Comment by madd15** [comment]
maybe delete the tread_id column from asset_logs and re-run migrations?

**Comment by kobie-chasehansen** [comment]
migration:rollback instead of deleting the last migration or instead of deleting the tread_id column from asset_logs?

**Comment by snipe** [comment]
migration:rollback instead of deleting the last migration

**Comment by madd15** [comment]
sorry should of made that a bit clearer :P
