### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by UserGoodtm** [snipe/snipe-it#9991]
Localization
Befor  (old ver) Version v5.1.8
![image](https://user-images.githubusercontent.com/48224568/130861657-bcea2ece-fe18-402b-b7c0-4b18eb799f3a.png)
New  Version v5.1.8 - build 6257
![image](https://user-images.githubusercontent.com/48224568/130861723-f33f6d8b-d1ca-4f83-9053-55960eb3b929.png)
The localization settings have changed in the new version.. please return the option 1234.56

**Comment by snipe** [comment]
They have changed to be more readable for standard currency formatting, as it was incorrect before. It's unlikely we will change this back.

**Comment by UserGoodtm** [comment]
> They have changed to be more readable for standard currency formatting, as it was incorrect before. It's unlikely we will change this back.

I understand that there is only one correct form of localization - American (USA)? It will be very difficult for users of other localizations to get used to the innovations. Sad news.

**Comment by snipe** [comment]
If there was only one, we [wouldn't offer a choice](https://www.dfa.cornell.edu/treasurer/cash-management/processinginternational/intl-currency), would we?
